### ISSUE TITLE
`The Flutter SDK is not available` when running `dart run ffigen`

### ISSUE THREAD

**Issue by noib3** [flutter/flutter#100059]
I'm trying to run `dart run ffigen` but I'm getting this error

```sh
$ dart run ffigen
The Flutter SDK is not available.
#0      BoundSdkSource.getDirectory (package:pub/src/source/sdk.dart:125:7)
#1      SystemCache.load (package:pub/src/system_cache.dart:113:52)
#2      Entrypoint._assertLockFileUpToDate (package:pub/src/entrypoint.dart:599:19)
#3      Entrypoint.assertUpToDate (package:pub/src/entrypoint.dart:525:7)
#4      getExecutableForCommand (package:pub/src/executable.dart:304:16)
#5      RunCommand.run (package:dartdev/src/commands/run.dart:232:32)
#6      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#7      DartdevRunner.runCommand (package:dartdev/dartdev.dart:232:30)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#9      new Future.sync (dart:async/future.dart:296:31)
#10     CommandRunner.run (package:args/command_runner.dart:119:14)
#11     runDartdev (package:dartdev/dartdev.dart:67:29)
#12     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

do I have to set some environment variable to let Dart find the Flutter SDK? On the other hand, flutter finds the dart sdk without problems, as `flutter doctor -v` outputs
```sh
[  +44 ms] executing: uname -m
[  +23 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/nix/store/lmja0xh3y2plnks22mg5v6cmd2w7rxjh-flutter-2.10.1-unwrapped/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] db747aa1331bd95bc9b3874c842261ca2d302cd5
[        ] executing: [/nix/store/lmja0xh3y2plnks22mg5v6cmd2w7rxjh-flutter-2.10.1-unwrapped/] git tag --points-at db747aa1331bd95bc9b3874c842261ca2d302cd5
[  +10 ms] Exit code 0 from: git tag --points-at db747aa1331bd95bc9b3874c842261ca2d302cd5
[        ] 2.10.1
[   +7 ms] executing: [/nix/store/lmja0xh3y2plnks22mg5v6cmd2w7rxjh-flutter-2.10.1-unwrapped/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/nix/store/lmja0xh3y2plnks22mg5v6cmd2w7rxjh-flutter-2.10.1-unwrapped/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +38 ms] executing: [/nix/store/lmja0xh3y2plnks22mg5v6cmd2w7rxjh-flutter-2.10.1-unwrapped/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +34 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +28 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +72 ms] executing: [/nix/store/lmja0xh3y2plnks22mg5v6cmd2w7rxjh-flutter-2.10.1-unwrapped/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] Skipping request to fetchTags - on well known channel stable.
[        ] executing: [/nix/store/lmja0xh3y2plnks22mg5v6cmd2w7rxjh-flutter-2.10.1-unwrapped/] git tag --points-at HEAD
[  +10 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 2.10.1
[   +7 ms] executing: /nix/store/rwkxxmjkyky2a8cvj0dk4qfdyyi1bxza-android-studio-beta-2021.2.1.8-unwrapped/jre/bin/java -version
[  +78 ms] Exit code 0 from: /nix/store/rwkxxmjkyky2a8cvj0dk4qfdyyi1bxza-android-studio-beta-2021.2.1.8-unwrapped/jre/bin/java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+0-b1504.28-7817840, mixed mode)
[   +1 ms] executing: /nix/store/cqzki4val7cgiazfxin930k5gr4aib2n-android-studio-beta-2021.1.1.18-unwrapped/jre/bin/java -version
[  +60 ms] Exit code 0 from: /nix/store/cqzki4val7cgiazfxin930k5gr4aib2n-android-studio-beta-2021.1.1.18-unwrapped/jre/bin/java -version
[        ] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+0-b60-7590822, mixed mode)
[   +6 ms] executing: /nix/store/rwkxxmjkyky2a8cvj0dk4qfdyyi1bxza-android-studio-beta-2021.2.1.8-unwrapped/jre/bin/java -version
[  +65 ms] Exit code 0 from: /nix/store/rwkxxmjkyky2a8cvj0dk4qfdyyi1bxza-android-studio-beta-2021.2.1.8-unwrapped/jre/bin/java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+0-b1504.28-7817840, mixed mode)
[        ] executing: /nix/store/cqzki4val7cgiazfxin930k5gr4aib2n-android-studio-beta-2021.1.1.18-unwrapped/jre/bin/java -version
[  +61 ms] Exit code 0 from: /nix/store/cqzki4val7cgiazfxin930k5gr4aib2n-android-studio-beta-2021.1.1.18-unwrapped/jre/bin/java -version
[        ] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+0-b60-7590822, mixed mode)
[   +8 ms] executing: [/nix/store/lmja0xh3y2plnks22mg5v6cmd2w7rxjh-flutter-2.10.1-unwrapped/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 5 weeks ago
[  +19 ms] java -version
[   +9 ms] executing: /nix/store/lfg1wh9ckm0l8q9dykgi7mfxjb1qx8ag-android-sdk-env/share/android-sdk/platform-tools/adb devices -l
[  +15 ms] [✓] Flutter (Channel stable, 2.10.1, on NixOS 22.05 (Quokka) 5.10.101, locale en_US.UTF-8)
[        ]     • Flutter version 2.10.1 at /nix/store/lmja0xh3y2plnks22mg5v6cmd2w7rxjh-flutter-2.10.1-unwrapped
[        ]     • Upstream repository https://github.com/flutter/flutter.git
[        ]     • Framework revision db747aa133 (5 weeks ago), 2022-02-09 13:57:35 -0600
[        ]     • Engine revision ab46186b24
[        ]     • Dart version 2.16.1
[        ]     • DevTools version 2.9.2
[  +30 ms] List of devices attached
           af5bf12d               device usb:1-1 product:Nord_EEA model:AC2003 device:Nord transport_id:4
[   +7 ms] /nix/store/lfg1wh9ckm0l8q9dykgi7mfxjb1qx8ag-android-sdk-env/share/android-sdk/platform-tools/adb -s af5bf12d shell getprop
[  +49 ms] ro.hardware = qcom
[   +2 ms] executing: /nix/store/lfg1wh9ckm0l8q9dykgi7mfxjb1qx8ag-android-sdk-env/share/android-sdk/platform-tools/adb devices -l
[  +13 ms] List of devices attached
           af5bf12d               device usb:1-1 product:Nord_EEA model:AC2003 device:Nord transport_id:4
[ +144 ms] [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[        ]     • Android SDK at /nix/store/lfg1wh9ckm0l8q9dykgi7mfxjb1qx8ag-android-sdk-env/share/android-sdk
[        ]     • Platform android-32, build-tools 30.0.2
[        ]     • ANDROID_SDK_ROOT = /nix/store/lfg1wh9ckm0l8q9dykgi7mfxjb1qx8ag-android-sdk-env/share/android-sdk
[        ]     • Java binary at: /nix/store/rwkxxmjkyky2a8cvj0dk4qfdyyi1bxza-android-studio-beta-2021.2.1.8-unwrapped/jre/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
[        ]     ✗ Android license status unknown.
[        ]       Run `flutter doctor --android-licenses` to accept the SDK licenses.
[        ]       See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[        ] [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
[        ]     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[        ] [✓] Android Studio (version 2021.2)
[        ]     • Android Studio at /nix/store/rwkxxmjkyky2a8cvj0dk4qfdyyi1bxza-android-studio-beta-2021.2.1.8-unwrapped
[        ]     • Flutter plugin can be installed from:
[        ]       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
[        ]     • Dart plugin can be installed from:
[        ]       🔨 https://plugins.jetbrains.com/plugin/6351-dart
[        ]     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
[        ] [✓] Android Studio (version 2021.1)
[        ]     • Android Studio at /nix/store/cqzki4val7cgiazfxin930k5gr4aib2n-android-studio-beta-2021.1.1.18-unwrapped
[        ]     • Flutter plugin can be installed from:
[        ]       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
[        ]     • Dart plugin can be installed from:
[        ]       🔨 https://plugins.jetbrains.com/plugin/6351-dart
[        ]     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
[        ] [✓] Connected device (1 available)
[        ]     • AC2003 (mobile) • af5bf12d • android-arm64 • Android 11 (API 30)
[+1209 ms] [✓] HTTP Host Availability
[        ]     • All required HTTP hosts are available
[        ] ! Doctor found issues in 2 categories.
[   +7 ms] "flutter doctor" took 1,940ms.
[  +64 ms] ensureAnalyticsSent: 61ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

Some more infos:
```sh
$ readlink -f (which flutter)
/nix/store/lw3dmab469hrqpwvmivjh2g56qi4ah59-flutter-2.10.1/bin/flutter
$ readlink -f (which dart)
/nix/store/nrabq29p4j14pxddmf6l8vc2z7zslzh8-dart-2.16.1/bin/dart
```

**Comment by darshankawar** [comment]
@noib3 
I am assuming you have already added `ffigen` package to your project and then you are running `dart run ffigen`.

Also, as asked above, I am not sure if the NixOS you are on is compatible with Flutter, but I maybe wrong here.

**Comment by noib3** [comment]
@iapicca With this flake

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    devshell.url = "github:numtide/devshell";
    android-nixpkgs.url = "github:tadfisher/android-nixpkgs/canary";
  };

  outputs = { self, nixpkgs, flake-utils, devshell, android-nixpkgs }:
    flake-utils.lib.eachDefaultSystem (system: {
      devShell =
        let
          pkgs = import nixpkgs {
            inherit system;
            overlays = [ devshell.overlay ];
          };

          # https://developer.android.com/studio/releases
          android-sdk = android-nixpkgs.sdk.${system} (sdkPkgs: with sdkPkgs; [
            cmdline-tools-latest
            emulator
            build-tools-30-0-2
            platforms-android-32
            platform-tools
            patcher-v4
            ndk-22-1-7171670

            system-images-android-30-google-apis-playstore-x86-64
          ]);

          ANDROID_SDK_ROOT = "${android-sdk}/share/android-sdk";
        in
        pkgs.devshell.mkShell {
          env = [
            {
              name = "JAVA_HOME";
              value = pkgs.jdk11.home;
            }
            {
              name = "ANDROID_SDK_ROOT";
              value = ANDROID_SDK_ROOT;
            }
            {
              name = "ANDROID_NDK_HOME";
              value = "${ANDROID_SDK_ROOT}/ndk/22.1.7171670/";
            }
            # Needed so bindgen can find libclang.so
            {
              name = "LIBCLANG_PATH";
              value = "${pkgs.llvmPackages.libclang.lib}/lib";
            }
            # Add the `dart` executable to the $PATH
            {
              name = "PATH";
              prefix = "${pkgs.flutter}/bin/cache/dart-sdk/bin";
            }
            {
              name = "FLUTTER_ROOT";
              prefix = "${pkgs.flutter}";
            }
          ];

          packages = with pkgs; [
            android-sdk
            jdk11
            flutter
            rustup
          ];
        };
    });
}
```

@darshankawar I don't think NixOS is the problem here, I can run and compile the template app created with `flutter create ..` without issues.

The problems seems to be that the dart sdk can't find flutter. I get the same error with other `dart` commands as well, it's not just an ffigen issue, for example

```sh
$ dart pub outdated
Package not available (the Flutter SDK is not available).
```

**Comment by iapicca** [comment]
@noib3 I have no idea how to deal with NixOS, but what about [this](https://search.nixos.org/packages?channel=21.11&show=flutter&from=0&size=50&sort=relevance&type=packages&query=flutter)?
regardless, since yours in clearly not the [official installation](https://docs.flutter.dev/get-started/install/linux), 
maybe this issue should be opened [here](https://github.com/NixOS/nixpkgs/issues)

**Comment by darshankawar** [comment]
@noib3 
Try filing the same issue in dedicated repo provided above and see what the owner says.
