### ISSUE TITLE
RangeError (end): Invalid value: Only valid value is 0: 5

### ISSUE THREAD

**Issue by praveenb** [flutter/flutter#100040]
In the App Screen, it has 3 TextFormField s where user can enter details to login to app.

As per report from client user, App getting below error.

```
---------- ERROR ----------
RangeError (end): Invalid value: Only valid value is 0: 5

------- STACK TRACE -------
#0      RangeError.checkValidRange (dart:core/errors.dart:338)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:393)
#2      TextRange.textBefore (dart:ui/text.dart:2785)
#3      RenderEditable.deleteByWord (package:flutter/src/rendering/editable.dart:1194)
#4      _DeleteByWordTextAction.invoke (package:flutter/src/widgets/default_text_editing_actions.dart:99)
#5      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:518)
#6      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:830)
#7      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:1171)
#8      FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1761)
#9      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:830)
#10     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73)
#11     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72)
#12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379)
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376)
#14     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205)
#15     _rootRun (dart:async/zone.dart:1428)
#16     _CustomZone.run (dart:async/zone.dart:1328)
#17     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#18     _invoke2 (dart:ui/hooks.dart:204)
#19     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)
#20     _Channel.push (dart:ui/channel_buffers.dart:132)
#21     ChannelBuffers.push (dart:ui/channel_buffers.dart:329)
#22     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544)
#23     _dispatchPlatformMessage (dart:ui/hooks.dart:92)
```

Flutter version details
```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.556], locale en-IN)
    • Flutter version 2.5.3 at D:\flutter_sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\praveenb\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at D:\Android_bumble
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (3 available)
    • Redmi 7 (mobile) • de84976b • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 99.0.1150.39

! Doctor found issues in 1 category.

```

</details>

Please need help to resolve this issue

**Comment by dopecoder** [comment]
Please check:

https://stackoverflow.com/questions/54977982/rangeerror-index-invalid-value-valid-value-range-is-empty-0

**Comment by praveenb** [comment]
> Please check:
> 
> https://stackoverflow.com/questions/54977982/rangeerror-index-invalid-value-valid-value-range-is-empty-0

ListBuilder not used in the app screen. So issue not related to it.

It seems issue is happening when editing Text in TextFormField and i see its invoke a method  `_DeleteByWordTextAction.invoke` as per crash log causing the issue.

**Comment by danagbemava-nc** [comment]
Hi @praveenb, your flutter doctor shows that you're on an older version of flutter, can you upgrade to the latest version of `stable`(2.10.3) to see if this issue still reproduces? 

If it does, can you please provide a complete minimal reproducible code sample, the updated flutter doctor -v as well as steps to reproduce? 

Thank you
