### ISSUE TITLE
Mac_ios platform_channels_benchmarks_ios failed to upload results to skia perf

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#100075]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20platform_channels_benchmarks_ios/3087/overview

```
Results to upload to skia perf: {CommitBranch: master, CommitSha: 11deb156c29d6252c6bd6c615b631db0ad4b011f
, BuilderName: Mac_ios platform_channels_benchmarks_ios, NewStatus: Succeeded, ResultData: {platform_channel_basic_standard_2host_small: 145.7368, platform_channel_basic_standard_2host_large: 1969.77, platform_channel_basic_binary_2host_large: 177.0332, platform_channel_basic_binary_2host_1MB: 883.9304, platform_channel_basic_standard_2host_small_parallel_3: 81.4644, platform_channel_basic_standard_2hostbackground_small: 160.9916, platform_channel_basic_standard_2hostbackground_small_parallel_3: 82.4076}, BenchmarkScoreKeys: [platform_channel_basic_standard_2host_small, platform_channel_basic_standard_2host_large, platform_channel_basic_binary_2host_large, platform_channel_basic_binary_2host_1MB, platform_channel_basic_standard_2host_small_parallel_3, platform_channel_basic_standard_2hostbackground_small, platform_channel_basic_standard_2hostbackground_small_parallel_3]}
Benchmark tags to upload to skia perf: {arch: intel, device_type: iPhone 6s, device_version: iOS-15.1, host_type: mac, host_version: mac-10.16}
Successfully uploaded metrics to skia perf
Unhandled exception:
DetailedApiRequestError(status: 504, message: )
#0      _validateResponse (package:_discoveryapis_commons/src/api_requester.dart:298:9)
<asynchronous suspension>
#1      ApiRequester.request (package:_discoveryapis_commons/src/api_requester.dart:72:16)
<asynchronous suspension>
#2      ObjectsResource.delete (package:googleapis/storage/v1.dart:2463:5)
<asynchronous suspension>
#3      GcsLock._unlock (package:metrics_center/src/gcs_lock.dart:82:5)
<asynchronous suspension>
#4      GcsLock.protectedRun (package:metrics_center/src/gcs_lock.dart:42:7)
<asynchronous suspension>
```

**Comment by christopherfujino** [comment]
The success log is from https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/command/upload_results.dart#L53, and yet the exception is from `package:metrics_center`, which I don't believe gets called after that, so I'm pretty confused. I didn't see any obvious unawaited Futures.

**Comment by keyonghan** [comment]
The lock was not released: `platform_channels_benchmarks_ios_values.json.lock`. Manually renamed to workaround, and re-triggered the test.
