### ISSUE TITLE
`Scaffold.of(context).showBottomSheet` crashes

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#100047]
### Steps
1, Show the bottom sheet first
2, Tap the back arrow and the `show bottom sheet` button at the same time
3, Repeat step 2 many times and observe the log output, which can be reproduced with a high probability

### Code
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo'),
        ),
        body: const MyHomePage(),
      ),
      // home : SizedBox.shrink(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void bottomSheet() {
    Scaffold.of(context).showBottomSheet((BuildContext context) {
      return const FractionallySizedBox(
        heightFactor: .2,
        child: Center(child: Text('This is a bottom sheet')),
      );
    }, backgroundColor: Colors.amber);
  }

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      child: const Text('Show bottom sheet'),
      onPressed: bottomSheet,
    );
  }
}

```

### Crash Log
```dart
E/flutter (22121): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:flutter/src/material/scaffold.dart': Failed assertion: line 2366 pos 14: 'bottomSheetKey.currentState != null': is not true.
E/flutter (22121): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (22121): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (22121): #2      ScaffoldState._buildBottomSheet._removeCurrentBottomSheet (package:flutter/src/material/scaffold.dart:2366:14)
E/flutter (22121): #3      ScaffoldState._buildBottomSheet.<anonymous closure> (package:flutter/src/material/scaffold.dart:2384:13)
E/flutter (22121): #4      LocalHistoryEntry._notifyRemoved (package:flutter/src/widgets/routes.dart:472:15)
E/flutter (22121): #5      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:665:13)
E/flutter (22121): #6      _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:2896:16)
E/flutter (22121): #7      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3868:22)
E/flutter (22121): #8      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4910:7)
E/flutter (22121): #9      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:4860:9)
E/flutter (22121): <asynchronous suspension>
E/flutter (22121): 
```

**Comment by xu-baolin** [comment]
The root cause of this issue is that after the `Scaffold.of(context).showBottomSheet` [adds a route entry](https://github.com/flutter/flutter/blob/4f4c7816c3376370c32688b5f40fe33470b7c63e/packages/flutter/lib/src/material/scaffold.dart#L2424-L2425), in the same frame, the `onRemove` of the route is triggered, and at this time, the new sheet has not been mounted on the tree.

**Comment by cbalmeida** [comment]
I have fixed a similar issue by passing BuildContext as parameter.

Try this:

  void showBottomSheet(BuildContext context) {
    Scaffold.of(context).showBottomSheet((BuildContext context) {
      return const FractionallySizedBox(
        heightFactor: .2,
        child: Center(child: Text('This is a bottom sheet')),
      );
    }, backgroundColor: Colors.amber);
  }

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      child: const Text('Show bottom sheet'),
      onPressed: () => showBottomSheet(context),
    );
  }
