### ISSUE TITLE
[windows] gclient sync failed using VS2022 without setting GYP_MSVS_VERSION and GYP_MSVS_OVERRIDE_PATH environment

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#100026]
```log
> gclient sync
Syncing projects: 100% (124/124), done.

________ running 'python3 src/flutter/tools/dia_dll.py' in 'C:\Users\eggfly\github\flutter_engine'
Traceback (most recent call last):
  File "src/flutter/tools/dia_dll.py", line 77, in <module>
    sys.exit(main())
  File "src/flutter/tools/dia_dll.py", line 72, in main
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "src/flutter/tools/dia_dll.py", line 67, in CopyDiaDllTo
    dia_dll = GetDiaDll()
  File "src/flutter/tools/dia_dll.py", line 43, in GetDiaDll
    win_sdk_dir = vs_toolchain.SetEnvironmentAndGetSDKDir()
  File "C:\Users\eggfly\github\flutter_engine\src\flutter\tools\..\..\build\vs_toolchain.py", line 517, in SetEnvironmentAndGetSDKDir
    SetEnvironmentAndGetRuntimeDllDirs()
  File "C:\Users\eggfly\github\flutter_engine\src\flutter\tools\..\..\build\vs_toolchain.py", line 96, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "C:\Users\eggfly\github\flutter_engine\src\flutter\tools\..\..\build\vs_toolchain.py", line 184, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
  File "C:\Users\eggfly\github\flutter_engine\src\flutter\tools\..\..\build\vs_toolchain.py", line 173, in GetVisualStudioVersion
    raise Exception('No supported Visual Studio can be found.'
Exception: No supported Visual Studio can be found. Supported versions are: 15.0 (2017), 16.0 (2019).
Error: Command 'python3 src/flutter/tools/dia_dll.py' returned non-zero exit status 1 in C:\Users\eggfly\github\flutter_engine
Traceback (most recent call last):
  File "src/flutter/tools/dia_dll.py", line 77, in <module>
    sys.exit(main())
  File "src/flutter/tools/dia_dll.py", line 72, in main
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "src/flutter/tools/dia_dll.py", line 67, in CopyDiaDllTo
    dia_dll = GetDiaDll()
  File "src/flutter/tools/dia_dll.py", line 43, in GetDiaDll
    win_sdk_dir = vs_toolchain.SetEnvironmentAndGetSDKDir()
  File "C:\Users\eggfly\github\flutter_engine\src\flutter\tools\..\..\build\vs_toolchain.py", line 517, in SetEnvironmentAndGetSDKDir
    SetEnvironmentAndGetRuntimeDllDirs()
  File "C:\Users\eggfly\github\flutter_engine\src\flutter\tools\..\..\build\vs_toolchain.py", line 96, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "C:\Users\eggfly\github\flutter_engine\src\flutter\tools\..\..\build\vs_toolchain.py", line 184, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
  File "C:\Users\eggfly\github\flutter_engine\src\flutter\tools\..\..\build\vs_toolchain.py", line 173, in GetVisualStudioVersion
    raise Exception('No supported Visual Studio can be found.'
Exception: No supported Visual Studio can be found. Supported versions are: 15.0 (2017), 16.0 (2019).
```

**Comment by chinmaygarde** [comment]
The linked PR has landed.
