### ISSUE TITLE
[image_picker][iOS]: `pickMultiImage` throws an invalid type cast exception on iOS 12

### ISSUE THREAD

**Issue by jonasfranz** [flutter/flutter#100132]
## Steps to Reproduce

1. Execute the code sample on an iOS 12 device (in my case iOS 12.4)
2. Select an image from the library
3. image_picker will throw the exception shown in logs

It should use the legacy image picker instead of throwing the exception since flutter/plugins#4718 got implemented.

**Expected results:** List of XFile with the selected image inside

**Actual results:** Exception `type 'String' is not a subtype of type 'List<dynamic>?' in type cast`

<details>
<summary>Code sample</summary>

```dart
await picker.pickMultiImage()
```

</details>

<details>
  <summary>Logs</summary>

```
flutter: type 'String' is not a subtype of type 'List<dynamic>?' in type cast
flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:41)
<asynchronous suspension>
#1      MethodChannelImagePicker.getMultiImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:206:34)
<asynchronous suspension>
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report.
I verified this behavior by running plugin [example](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker/example) on iOS 12.5.5 device and then trying select from multi image feature throws below exception on screen:

<img width="345" alt="Screenshot 2022-03-16 at 12 16 35 PM" src="https://user-images.githubusercontent.com/67046386/158532352-afc06ca0-4563-4601-a589-8d02f382a939.png">


<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.13.0-0.0.pre.103, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.103 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 509ddfda5c (2 hours ago), 2022-03-15 21:10:18 -0700
    • Engine revision dc22c4c7fe
    • Dart version 2.17.0 (build 2.17.0-202.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by vincentderidder** [comment]
Any timeframe on resolving this issue?

**Comment by pbelko** [comment]
having same issue on ios 13.0 emulator. works fine on 15.4 emulator and 15.3.1 device... any updates on this?
