### ISSUE TITLE
[video_player] 2.3.0  Playback error E/ExoPlayerImplInternal(18969):   com.google.android.exoplayer2.ExoPlaybackException: Source error E/ExoPlayerImplInternal(18969):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#100250]
error on player video from URL on Flutter 2.10.3

https://www.experimenteriodasostras.com.br/storage/turismo/midias/ffec8800-09d2-45a4-9b99-09ab04b057bf.mp4

```console
I/ViewRootImpl@ee198e1[MainActivity](18969): ViewPostIme pointer 0
I/ViewRootImpl@ee198e1[MainActivity](18969): ViewPostIme pointer 1
I/flutter (18969): -- TurismoModule INITIALIZED
W/riodasostrasap(18969): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (unsupported, reflection, allowed)
I/ExoPlayerImpl(18969): Init cd13e8f [ExoPlayerLib/2.14.1] [r8q, SM-G780G, samsung, 31]
D/CompatibilityChangeReporter(18969): Compat change id reported: 147600208; UID 10484; state: ENABLED
D/libmdf  (18969): libmdf v3.0.0.0 On 64bit PLATFORM
E/ExoPlayerImplInternal(18969): Playback error
E/ExoPlayerImplInternal(18969):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(18969):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
E/ExoPlayerImplInternal(18969):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(18969):       at android.os.Looper.loopOnce(Looper.java:226)
E/ExoPlayerImplInternal(18969):       at android.os.Looper.loop(Looper.java:313)
E/ExoPlayerImplInternal(18969):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(18969):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal(18969):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:346)
E/ExoPlayerImplInternal(18969):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(18969):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)   
E/ExoPlayerImplInternal(18969):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
E/ExoPlayerImplInternal(18969):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(18969):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(18969):       at java.lang.Thread.run(Thread.java:920)
E/ExoPlayerImplInternal(18969):   Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)    
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
E/ExoPlayerImplInternal(18969):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
E/ExoPlayerImplInternal(18969):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:608)
E/ExoPlayerImplInternal(18969):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:513)
E/ExoPlayerImplInternal(18969):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:339)
E/ExoPlayerImplInternal(18969):       ... 6 more
E/ExoPlayerImplInternal(18969):   Caused by: java.security.cert.CertificateException: Chain validation failed
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:719)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:570)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
E/ExoPlayerImplInternal(18969):       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
E/ExoPlayerImplInternal(18969):       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
E/ExoPlayerImplInternal(18969):       ... 28 more
E/ExoPlayerImplInternal(18969):   Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
E/ExoPlayerImplInternal(18969):       at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
E/ExoPlayerImplInternal(18969):       at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
E/ExoPlayerImplInternal(18969):       at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
E/ExoPlayerImplInternal(18969):       at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
E/ExoPlayerImplInternal(18969):       at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
E/ExoPlayerImplInternal(18969):       at android.sec.enterprise.certificate.DelegatingCertPathValidator.engineValidate(DelegatingCertPathValidator.java:63)      
E/ExoPlayerImplInternal(18969):       at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:715)
E/ExoPlayerImplInternal(18969):       ... 44 more
E/ExoPlayerImplInternal(18969):   Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Fri Mar 11 20:59:59 GMT-03:00 2022 (compared to Wed Mar 16 16:29:11 GMT-03:00 2022)
E/ExoPlayerImplInternal(18969):       at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:269)
E/ExoPlayerImplInternal(18969):       at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
E/ExoPlayerImplInternal(18969):       at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
E/ExoPlayerImplInternal(18969):       at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
E/ExoPlayerImplInternal(18969):       ... 51 more
E/flutter (18969): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (18969):

```

**Comment by hamdikahloun** [comment]
Hi @insinfo 
The provided link have SSL error `net::ERR_CERT_DATE_INVALID`.

**Comment by danagbemava-nc** [comment]
Hi @insinfo, as pointed out above, this is an issue with the server certificate, not the video_player plugin. Kindly resolve the certificate issues and try again.

Closing as this is a server certificate issue. 

If you still experience this after resolving the issue, kindly leave a comment below and I will reopen. 

Thank you

**Comment by danagbemava-nc** [comment]
I'm not entirely sure about that. You can check the exoplayer docs for information on that https://exoplayer.dev/troubleshooting.html#fixing-sslhandshakeexception-certpathvalidatorexception-and-err_cert_authority_invalid-errors
