### ISSUE TITLE
Exception caught by widgets library: Failed assertion: line 1964 pos 12: '_elements.contains(element)': is not true.

### ISSUE THREAD

**Issue by Ronak8602** [flutter/flutter#100240]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
<summary>logs</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building _EffectiveTickerMode(effective mode: enabled):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1964 pos 12: '_elements.contains(element)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/ronak/AndroidStudioProjects/ami_radio/lib/main.dart:17:12
When the exception was thrown, this was the stack: 
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:1964:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3746:30)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3772:33)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3524:20)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#8      ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#18     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#26     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#30     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#41     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#46     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#48     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#53     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#58     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#62     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#66     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#70     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#74     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#78     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#82     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#95     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#104    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#108    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#112    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#116    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#120    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#125    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#127    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#131    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#134    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#136    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#140    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#141    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#144    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#146    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#150    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#153    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#155    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#159    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#162    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#164    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#168    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#169    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#171    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#175    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#176    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#179    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#180    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#181    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#182    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#184    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#185    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#186    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#189    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#190    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#191    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#193    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#194    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#197    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#198    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#201    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#202    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#203    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#204    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#206    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#207    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#208    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#211    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#212    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#213    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#215    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#216    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#217    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#220    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#221    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#222    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#223    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#224    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#226    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#229    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#230    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#233    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#234    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#235    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#238    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#239    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#240    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#241    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#242    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#245    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#246    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#247    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#248    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#250    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#251    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#252    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#253    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#254    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#255    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#256    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#258    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#259    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#260    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#262    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#263    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#264    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#265    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#266    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#267    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#268    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#269    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#270    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#271    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#272    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#273    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#274    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================
```

**Comment by maheshmnj** [comment]
Hi @Ronak8602, Thanks for filing the issue.

> The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/ronak/AndroidStudioProjects/ami_radio/lib/main.dart:17:12

From the log it looks like an issue with your code in `main.dart`

 In order to investigate this issue further, we would need a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.
