### ISSUE TITLE
[tool_crash] _CastError: (#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49))

### ISSUE THREAD

**Issue by mauriceraguseinit** [flutter/flutter#100252]
## Command
```
flutter gen-l10n
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49))
```
#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49)
#1      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1137:34)
#2      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1238:46)
#3      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1313:47)
#4      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
#5      GenerateLocalizationsCommand.runCommand (package:flutter_tools/src/commands/generate_localizations.dart:210:7)
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:94:3)
```
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-x64, locale de-DE)
    • Flutter version 2.10.3 at /Users/mraguse/fvm/versions/2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mraguse/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/mraguse/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Appli

**Comment by danagbemava-nc** [comment]
Hi @mauriceraguseinit, kindly share your `pubspec.yaml` as well as your `l10n.yaml` files.

Thank you

**Comment by mauriceraguseinit** [comment]
i used a wrong language code (ua instead of uk for ukraine) ... after changing it... it work
