### ISSUE TITLE
unable to build ios

### ISSUE THREAD

**Issue by rjmacwan95** [flutter/flutter#100438]
Reproduce issue with following steps:

Step 1:
create new project with flutter create command

Step 2:
flutter run -v command terminal logs : 
```
Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```

--------------------------------------------------------------------------------------

flutter doctor -v :
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.3 at ~/Developement/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at ~/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • 481C711E-AD71-491C-A824-EC89AEAE9E5B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript •
      Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by laurensdewaele** [comment]
Have you tried the suggestions you find online? E.g. on [Stackoverflow](https://stackoverflow.com/questions/69900681/flutter-ios-got-throwtoolexit-error-when-running-on-simulator).

**Comment by rjmacwan95** [comment]
Well, none of them actually works

**Comment by ryzizub** [comment]
Did you tried cleaning emulator or different emulator? Also there is no error above, just this?

**Comment by rjmacwan95** [comment]
This error is only related to the iOS devices it works on Android & web. iOS simulators are fresh so it's not the issue before it was working well in iOS but after upgrading to latest xcode version this error come up.

**Comment by imrhk** [comment]
Looks like some terms needs to be accepted on XCode. 

Sometimes, XCode updates their TnC as well and developer needs to accept them before they can build/run app. Open XCode and build the app. 

It may or may not work but worth a try.

**Comment by darshankawar** [comment]
@rjmacwan95 
Can you provide `flutter run -v` ? The log will be huge so you can put that in a text file and share it here.
Also provide your `ios/podfile`.

**Comment by darshankawar** [comment]
@rjmacwan95 
From the verbose log, its failing due to below:

```
   +7 ms] Target debug_unpack_ios failed: Exception: Binary
               /Users/ronald/Developement/Projects/FlutterProjects/DemoProjects/flutter_starter_application/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter does not exist,
```

For which, see [this](https://github.com/flutter/flutter/issues/95972#issuecomment-1005201055) issue comment and possible solution.
Closing this as duplicate of same, ie, https://github.com/flutter/flutter/issues/95972

**Comment by rjmacwan95** [comment]
@darshankawar  the issue referred by you as #95972 and labeling this issue as duplicate does not provide the solution as changing the channel from stable to master & then master to stable, but by doing so my issue wasn't fixed it still appears to be same I have tried changing the flutter channels but it doesn't worked as mentioned in the issue as solution and labeled as solved. Please reopen this issue.

**Comment by rjmacwan95** [comment]
Full operation of commands & generated log file is also attached

[flutter_commands_log.txt](https://github.com/flutter/flutter/files/8344128/flutter_commands_log.txt)

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening.

**Comment by darshankawar** [comment]
@rjmacwan95 
Can you provide `ios/podfile` ?

**Comment by rjmacwan95** [comment]
There is not podfile in iOS directory

**Comment by darshankawar** [comment]
I am unable to replicate this at my end. Looking at the logs, it fails with below error:

```
`[   +6 ms] Target debug_unpack_ios failed: Exception: Binary\
               /Users/ronald/Developement/Projects/FlutterProjects/DemoProjects/flutter_starter_application/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter does not exist,\
cannot thin\`
```
There have been couple of closed reports for same error:

https://github.com/flutter/flutter/issues/96641
https://github.com/flutter/flutter/issues/95972

Probably could not find a way as why it could be causing this: https://github.com/flutter/flutter/issues/95972#issuecomment-1005201055

Labeling it for further insights from the team.

/cc @jmagman

**Comment by darshankawar** [comment]
> it was working well in iOS but after upgrading to latest xcode version this error come up.

Another point to note.

**Comment by rjmacwan95** [comment]
@darshankawar would you recommend me to uninstall & then reinstall flutter SDK?

**Comment by darshankawar** [comment]
No.

**Comment by jmagman** [comment]
From https://github.com/flutter/flutter/issues/95972#issuecomment-1005201055

> The `rsync` which was supposed to copy the Flutter.framework (directory) succeeded (this exception wasn't thrown):
> 
> https://github.com/flutter/flutter/blob/e56c83a1ac60c4ebc42e0272d6db89645a034db6/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L316-L321
> 
> 
> But then immediately the presence of the `Flutter.framework/Flutter` file is checked for, and it's not present.
> https://github.com/flutter/flutter/blob/e56c83a1ac60c4ebc42e0272d6db89645a034db6/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L288-L292

**Comment by jmagman** [comment]
What's the output of:
```
ls -la /Users/ronald/Developement/SDKs/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_armv7/Flutter.framework/Flutter
```

**Comment by rjmacwan95** [comment]
> What's the output of:
> 
> ```
> ls -la /Users/ronald/Developement/SDKs/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_armv7/Flutter.framework/Flutter
> ```

Output:
ls: /Users/ronald/Developement/SDKs/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_armv7/Flutter.framework/Flutter: No such file or directory

**Comment by rjmacwan95** [comment]
Also Output of :
ls -la /Users/ronald/Developement/SDKs/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_armv7/Flutter.framework/Flutter

Changed with upgrade to SDK Version As:
-rwxr-xr-x  1 ronald  staff  71146576 Mar 24 06:32 /Users/ronald/Developement/SDKs/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_armv7/Flutter.framework/Flutter

**Comment by jmagman** [comment]
> Strange behavior... Upgraded the Flutter SDK From 2.10.3 to 2.10.4 and this issue got solved Don't know how.

This is the same thing that happened in https://github.com/flutter/flutter/issues/96641 https://github.com/flutter/flutter/issues/95972 where the cache is corrupted somehow and those files are deleted.  Upgrading Flutter will resolve the issue, but makes it really hard for us to track down why it happened in the first place (which is why the other issues were closed).

Could your antivirus software be deleting it?

**Comment by rjmacwan95** [comment]
No I guess that would not be the case because I have not installed any of the Antivirus softwares

**Comment by jmagman** [comment]
@christopherfujino this reminds me of #43767, maybe we need to do the same explicit executable check for the `Flutter` framework binaries.

https://github.com/flutter/flutter/blob/50f3e47b67f5307657d71c9bcac9fed3129398b7/packages/flutter_tools/lib/src/flutter_cache.dart#L800-L811

https://github.com/flutter/flutter/blob/50f3e47b67f5307657d71c9bcac9fed3129398b7/packages/flutter_tools/lib/src/flutter_cache.dart#L822-L831

**Comment by jmagman** [comment]
I wish I could have known exactly which files were missing.

If anyone else sees this, **BEFORE UPDATING OR CLEARING YOUR CACHE** please give us the output of 
```
ls -R bin/cache/artifacts/engine/ios
```

**Comment by lucasbarretoluz** [comment]
I have the same error, it doesn't work on any project. I can create a sample project in Flutter that also doesn't work. It just doesn't compile for the iOS emulator. If I compile it on my physical iPhone, it works correctly.

I've already done a flutter upgrade to the latest version, but the same error persists. I was clearing space on my Mac and ended up deleting some files. I'm not sure if I accidentally deleted some cache files. However, I've already reinstalled Xcode completely from scratch.

**Comment by huycozy** [comment]
@lucasbarretoluz Could you please share the output of the command as mentioned at https://github.com/flutter/flutter/issues/100438#issuecomment-1082276393?

**Comment by giantss** [comment]
@huycozy  

Although the error  #144281 I mentioned is the same error, my environment and the error information entered in the specific log are different from the current issues. Please help analyze the reason for my error. This problem has been bothering me for a long time. What's strange to me is that this error only occurs on the iPhone simulator, and no error is reported when running on the real iPhone.

 [flutter run -v  logs](https://pastebin.com/raw/zvrizpGr)

**Comment by christopherfujino** [comment]
@vashworth I'm guessing that this might be the after effects of https://github.com/flutter/flutter/issues/99785, WDYT?

**Comment by vashworth** [comment]
> @vashworth I'm guessing that this might be the after effects of #99785, WDYT?

It could be since it is using `rsync`, but I kind of doubt it. The iOS Flutter.xcframework is different than the FlutterMacOS.framework since all engine iOS artifacts come from a single zip file, whereas macos is multiple zips. Also, I don't think we've had crash logs or reports of it being an issue for the Flutter.xcframework. I could be wrong, though.

**Comment by vashworth** [comment]
> @huycozy
> 
> Although the error #144281 I mentioned is the same error, my environment and the error information entered in the specific log are different from the current issues. Please help analyze the reason for my error. This problem has been bothering me for a long time. What's strange to me is that this error only occurs on the iPhone simulator, and no error is reported when running on the real iPhone.
> 
> [flutter run -v logs](https://pastebin.com/raw/zvrizpGr)

@giantss Assuming you're still having this issue, could you run `ls -R bin/cache/artifacts/engine/ios` and provide the output?

**Comment by giantss** [comment]
> > @huycozy
> > 虽然我提到的错误#144281是同一个错误，但我的环境以及具体日志中输入的错误信息与当前问题不同。请大家帮忙分析一下我的错误原因。这个问题已经困扰我很长时间了。令我奇怪的是，这个错误只发生在iPhone模拟器上，在真机上运行时却没有报错。
> > [flutter run -v 日志](https://pastebin.com/raw/zvrizpGr)
> 
> @giantss假设您仍然遇到此问题，您可以运行`ls -R bin/cache/artifacts/engine/ios`并提供输出吗？

After I execute this command in the project root directory, the console prints as follows：

`ls: bin/cache/artifacts/engine/ios: No such file or directory`
@vashworth

**Comment by giantss** [comment]
> > @huycozy
> > Although the error #144281 I mentioned is the same error, my environment and the error information entered in the specific log are different from the current issues. Please help analyze the reason for my error. This problem has been bothering me for a long time. What's strange to me is that this error only occurs on the iPhone simulator, and no error is reported when running on the real iPhone.
> > [flutter run -v logs](https://pastebin.com/raw/zvrizpGr)
> 
> @giantss Assuming you're still having this issue, could you run `ls -R bin/cache/artifacts/engine/ios` and provide the output?

After I execute this command in the project root directory, the console prints as follows：

`ls: bin/cache/artifacts/engine/ios: No such file or directory`
@vashworth

**Comment by vashworth** [comment]
> > > @huycozy
> > > Although the error #144281 I mentioned is the same error, my environment and the error information entered in the specific log are different from the current issues. Please help analyze the reason for my error. This problem has been bothering me for a long time. What's strange to me is that this error only occurs on the iPhone simulator, and no error is reported when running on the real iPhone.
> > > [flutter run -v logs](https://pastebin.com/raw/zvrizpGr)
> > 
> > 
> > @giantss Assuming you're still having this issue, could you run `ls -R bin/cache/artifacts/engine/ios` and provide the output?
> 
> After I execute this command in the project root directory, the console prints as follows：
> 
> `ls: bin/cache/artifacts/engine/ios: No such file or directory` @vashworth

Sorry, I should have specified, could you run `ls -R bin/cache/artifacts/engine/ios` within the Flutter SDK root directory. If you're unsure where that is, you can run `flutter doctor` and it should tell you the path following the Flutter version. For example, `Flutter version xx.xx.xx at ~/path/to/flutter`

**Comment by giantss** [comment]
> > > > @huycozy
> > > > Although the error #144281 I mentioned is the same error, my environment and the error information entered in the specific log are different from the current issues. Please help analyze the reason for my error. This problem has been bothering me for a long time. What's strange to me is that this error only occurs on the iPhone simulator, and no error is reported when running on the real iPhone.
> > > > [flutter run -v logs](https://pastebin.com/raw/zvrizpGr)
> > > 
> > > 
> > > @giantss Assuming you're still having this issue, could you run `ls -R bin/cache/artifacts/engine/ios` and provide the output?
> > 
> > 
> > After I execute this command in the project root directory, the console prints as follows：
> > `ls: bin/cache/artifacts/engine/ios: No such file or directory` @vashworth
> 
> Sorry, I should have specified, could you run `ls -R bin/cache/artifacts/engine/ios` within the Flutter SDK root directory. If you're unsure where that is, you can run `flutter doctor` and it should tell you the path following the Flutter version. For example, `Flutter version xx.xx.xx at ~/path/to/flutter`

Well, I used the `flutter doctor` command to execute and the Flutter SDK directory was not printed out, but it was printed using `flutter doctor -v`.
The following is the information printed by executing the `ls -R bin/cache/artifacts/engine/ios` command in the Flutter SDK directory:

```
$:flutter zhongpeng$ ls -R bin/cache/artifacts/engine/ios
Flutter.xcframework     LICENSE                 gen_snapshot_arm64

bin/cache/artifacts/engine/ios/Flutter.xcframework:
Info.plist                      ios-arm64                       ios-arm64_x86_64-simulator

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64:
Flutter.framework

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64/Flutter.framework:
Flutter         Headers         Info.plist      Modules         _CodeSignature  icudtl.dat

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64/Flutter.framework/Headers:
Flutter.h                               FlutterDartProject.h                    FlutterPlugin.h
FlutterAppDelegate.h                    FlutterEngine.h                         FlutterPluginAppLifeCycleDelegate.h
FlutterBinaryMessenger.h                FlutterEngineGroup.h                    FlutterTexture.h
FlutterCallbackCache.h                  FlutterHeadlessDartRunner.h             FlutterViewController.h
FlutterChannels.h                       FlutterMacros.h
FlutterCodecs.h                         FlutterPlatformViews.h

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64/Flutter.framework/Modules:
module.modulemap

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64/Flutter.framework/_CodeSignature:
CodeResources

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator:
Flutter.framework

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework:
Headers         Info.plist      Modules         _CodeSignature  icudtl.dat

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Headers:
Flutter.h                               FlutterDartProject.h                    FlutterPlugin.h
FlutterAppDelegate.h                    FlutterEngine.h                         FlutterPluginAppLifeCycleDelegate.h
FlutterBinaryMessenger.h                FlutterEngineGroup.h                    FlutterTexture.h
FlutterCallbackCache.h                  FlutterHeadlessDartRunner.h             FlutterViewController.h
FlutterChannels.h                       FlutterMacros.h
FlutterCodecs.h                         FlutterPlatformViews.h

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Modules:
module.modulemap

bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/_CodeSignature:
CodeResources

```

**Comment by giantss** [comment]
@vashworth Hello, can you find any problems from the output information?

**Comment by jmagman** [comment]
From the verbose logs:
```
error: [   +7 ms] Target debug_unpack_ios failed: Exception: Binary
/Users/x/file/code/flutter/my_flutter_app/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter does not exist, cannot thin
```
and from the cache:
```
bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework:
Headers         Info.plist      Modules         _CodeSignature  icudtl.dat
```
Sure enough, the `Flutter` binary is missing.

It actually does exist in the non-simulator framework, but this error is happening for the simulator
```
bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64/Flutter.framework:
Flutter         Headers         Info.plist      Modules         _CodeSignature  icudtl.dat
```

**Comment by jmagman** [comment]
@giantss do you know why this file would be missing?  Did you maybe delete it accidentally trying to make room on your Mac?  Do you have any antivirus software running that could have caused it.  When files get deleted out from under Flutter it's not going to work, any more than if you delete files out from any other app.

**Comment by giantss** [comment]
@jmagman 

I can’t remember clearly, maybe I didn’t delete it. Now I want to know how to recover? Hope you can help me.

**Comment by giantss** [comment]
@jmagman 

Thank you very much for the clue, my problem has been solved. Sure enough, the `Flutter` binary is missing.
Maybe I deleted it when I was cleaning up my computer some time.

I restored the `Flutter` binary in this directory (`bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework:`) and it can run normally on the iPhone simulator.

**Comment by jmagman** [comment]
If anyone else ever hits this, in your Flutter SDK directory run:

```
ls bin/cache/artifacts/engine/ios*/Flutter.xcframework/*/Flutter.framewor
```
If you don't see a relatively large `Flutter` binary in each directory, then your cache has been corrupted and you should run `flutter upgrade` to get them back.  Please don't delete them to clear up space--I know those files are large but they are the actual Flutter binaries that get embedded in your app.

The tool could detect these files are missing and give recovery steps.

**Comment by dai10512** [comment]
I was also in simmilar case, and resolved the issue by reinstall Flutter of fvm.

**Comment by JobGetabu** [comment]
Here's the most targeted way to fix this:

Navigate to your Flutter SDK directory:
Open your Terminal and go to where your Flutter SDK is installed. If you're not sure where it is, you can try which flutter. This will give you the path to the flutter executable, which is inside the bin directory of your SDK. For example, if it shows /Users/yourname/development/flutter/bin/flutter, your SDK directory is /Users/yourname/development/flutter.

Bash

`cd /path/to/your/flutter_sdk`
Clean the potentially corrupted iOS artifacts (Optional but often helpful):
This step ensures that any corrupted remnants are removed before trying to precache.

Bash

`rm -rf bin/cache/artifacts/engine/ios*`
`rm -rf`: This command forcefully removes directories and their contents. Be very careful to run this command only when you are inside your Flutter SDK directory.
`bin/cache/artifacts/engine/ios*`: This targets only the cached engine artifacts for iOS.
Run flutter precache specifically for iOS:
This command will download the necessary binary artifacts for iOS development for your currently active Flutter SDK version.

Bash

`flutter precache --ios`
