### ISSUE TITLE
Unable to create IOS build

### ISSUE THREAD

**Issue by bilalgodesto** [flutter/flutter#100410]
## Steps to Reproduce

I created a new project 

1. Execute `flutter create .`  
2. Add the following packages
 
<details>
<summary>pubspec.yaml</summary>

```
  cupertino_icons: ^1.0.2
  isar: 2.2.1
  isar_flutter_libs: 2.2.1 
  firebase_messaging: ^11.2.5
  firebase_core: ^1.11.0
  callkeep: ^0.3.2
  cloud_firestore: ^3.1.10
  shared_preferences: ^2.0.13
  
  shared_preferences_android: ^2.0.11
  audio_service: ^0.18.3
  one_context: ^1.1.1
  pin_code_fields: ^7.3.0
  flutter_local_notifications: ^5.0.0+4
  flutter_webrtc: ^0.8.3
  path_provider: ^2.0.2
  firebase_auth: ^1.4.1
  googleapis_auth: ^1.1.0
  firebase_storage: ^10.2.5
  firebase_crashlytics: ^2.0.0
  firebase_database: ^7.0.0
  vibration: ^1.7.4-nullsafety.0
```
</details>

3: Run ```flutter build ios --no-sound-null-safety``` 

**Expected results:**  Building successfully

**Actual results:** showing errors

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/bilalrabbi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bilalrabbi/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • 3AA1D2F9-3DD6-45B3-A823-91A56C2B25D6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
</details>

<details>
  <summary>Error Logs</summary>

   ```
 The following build commands failed:
                CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'vibration' from project 'Pods')
                Ld

/Users/bilalrabbi/Library/Developer/Xcode/DerivedData/Runner-eqtwcanhgaiurgblzcjnjgoffipl/Build/Intermediates.noindex/Pods.build/Release-iphoneos/shared_preferences_ios.buil
                d/Objects-normal/armv7/Binary/shared_preferences_ios normal armv7 (in target 'shared_preferences_ios' from project 'Pods')
               (2 failures)

[ +320 ms] Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

[   +6 ms] Error (Xcode): Framework not found Flutter

[  +12 ms] "flutter ios" took 47,010ms.
[   +8 ms] Encountered error while building for device.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:279:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


```

</details>

<details>
<summary>Pod file</summary>

```
platform :ios, '13.0'


ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |build_configuration|
      build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
    end
  end
end
```

</details>

**Comment by mihirj** [comment]
I have successfully built the app as per steps you provided. My dev environment is also same. The only difference is I’m running Xcode 13.1 and macOS 11.5.2.

**Comment by mihirj** [comment]
What happens if you comment this code and run project again?
`target.build_configurations.each do |build_configuration|
      build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386' `

**Comment by bilalgodesto** [comment]
Then i get below error

```
Lexical or Preprocessor Issue (Xcode): 'WebRTC/WebRTC.h' file not found
/Users/bilalrabbi/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.10+hotfix.1/ios/Classes/FlutterWebRTCPlugin.h:7:8


Lexical or Preprocessor Issue (Xcode): 'WebRTC/WebRTC.h' file not found
/Users/bilalrabbi/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.10+hotfix.1/ios/Classes/FlutterRTCMediaStream.m:2:8


Could not build the application for the simulator.
Error launching application on iPhone 8.
```

**Comment by darshankawar** [comment]
@bilalgodesto 
From the log you shared, its failing / pointing to below entry:```


The following build commands failed:
             CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'vibration' from project 'Pods')
             Ld
```

Pointing to `vibration` plugin you are using which is third party.

`vibration: ^1.7.4-nullsafety.0 `

You also have excluded below archs in your podfile `build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'`. But the vibration plugin may be using either of them and hence it could be throwing you an error. Try removing `arm64` and see if it helps.

You'll need to check what archs does `vibration` plugin support or doesn't support. Also since this is pointing to third party plugin, this doesn't seem to be flutter issue. Closing from here. If you disagree, write in comments and I'll reopen.
