### ISSUE TITLE
[tool_crash] _CastError: (#0      new AppResourceBundle (package:flutter_tools/src/localizations/gen_l10n_types.dart:420:56))

### ISSUE THREAD

**Issue by linnaingookkm** [flutter/flutter#100453]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      new AppResourceBundle (package:flutter_tools/src/localizations/gen_l10n_types.dart:420:56))
```
#0      new AppResourceBundle (package:flutter_tools/src/localizations/gen_l10n_types.dart:420:56)
#1      new AppResourceBundleCollection (package:flutter_tools/src/localizations/gen_l10n_types.dart:508:42)
#2      LocalizationsGenerator._allBundles (package:flutter_tools/src/localizations/gen_l10n.dart:709:56)
#3      LocalizationsGenerator._allBundles (package:flutter_tools/src/localizations/gen_l10n.dart)
#4      LocalizationsGenerator.loadResources (package:flutter_tools/src/localizations/gen_l10n.dart:1047:29)
#5      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:68:9)
#6      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:59:5)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:27)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
<asynchronous suspension>
#9      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#10     PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:130:7)
<asynchronous suspension>
#11     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:172:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1586], locale en-US)
    • Flutter version 2.5.2 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (6 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:/Users/domer/AppData/Local/Android/Sdk
    • Platform android-32, build-tools 32.0.0-rc1
    • ANDROID_HOME = C:/Users/domer/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code (version 1.65.0)
    • VS Code at C:\Users\domer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.74
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 99.0.1150.46

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.3.0+13
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aafb3a8b9b0c36241c5f5b34ee914770f015818

**Comment by danagbemava-nc** [comment]
Hi @linnaingookkm, you appear to be on an older version of `stable`. Can you upgrade to the latest version to see if you still experience this issue (stable 2.10.3)? If you do, kindly provide your `pubspec.yaml` as well as your `l10n.yaml` and your updated `flutter doctor -v`.

Thank you

**Comment by linnaingookkm** [comment]
Hello Hello my dear bro.
Thank you so much very very much,
Yes, Yes,
I downgrade flutter version and then it was working back :)

Thank you so much very very much my dear sir.

Kindly Regards,
Nai with big smile :)

**Comment by danagbemava-nc** [comment]
Hi @linnaingookkm, on which version of flutter is this working for you?
