### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by CoderAssets** [flutter/flutter#100408]
**iI am having problem  debugging, everything was working fine and suddenly I got these error I have tried removing every reference to get_connect in my app and also tried flutter clean . Please somebody help**
Launching lib\main.dart on M2012K11AG in debug mode...
Invalid depfile: D:\flutter\fastblood\.dart_tool\flutter_build\20f006f2dccca98ad77163f740feee90\kernel_snapshot.d
Invalid depfile: D:\flutter\fastblood\.dart_tool\flutter_build\20f006f2dccca98ad77163f740feee90\kernel_snapshot.d
/C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_connect/sockets/src/sockets_html.dart:4:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_connect/sockets/src/sockets_html.dart:11:3: Error: Type 'WebSocket' not found.
  WebSocket? socket;
  ^^^^^^^^^
/C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_connect/sockets/src/sockets_html.dart:11:3: Error: 'WebSocket' isn't a type.
  WebSocket? socket;
  ^^^^^^^^^
/C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_connect/sockets/src/sockets_html.dart:37:16: Error: The method 'WebSocket' isn't defined for the class 'BaseWebSocket'.
- 'BaseWebSocket' is from 'package:get/get_connect/sockets/src/sockets_html.dart' ('/C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_connect/sockets/src/sockets_html.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WebSocket'.
      socket = WebSocket(url);
               ^^^^^^^^^
/C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_connect/sockets/src/sockets_html.dart:104:49: Error: The getter 'WebSocket' isn't defined for the class 'BaseWebSocket'.
- 'BaseWebSocket' is from 'package:get/get_connect/sockets/src/sockets_html.dart' ('/C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_connect/sockets/src/sockets_html.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WebSocket'.
    if (socket != null && socket!.readyState == WebSocket.OPEN) {
                                                ^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:623:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:763:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:586:9)
<asynchronous suspension>
#4      starter (package:flutter_frontend_server/server.dart:85:12)
<asynchronous suspension>
#5      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter_windows_v1.5.4-hotfix.2-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter_windows_v1.5.4-hotfix.2-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 3s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by iapicca** [comment]
@CoderAssets  `v1.5.4-hotfix.2` 😱 
it's almost a 2 years old [release](https://docs.flutter.dev/development/tools/sdk/releases)
I recommend `flutter upgrade -f && flutter doctor -v`
and take in account some time and patient to port the app to 2022

**Comment by CoderAssets** [comment]
> @CoderAssets `v1.5.4-hotfix.2` 😱 it's almost a 2 years old [release](https://docs.flutter.dev/development/tools/sdk/releases) I recommend `flutter upgrade -f && flutter doctor -v` and take in account some time and patient to port the app to 2022
> 
> also this error isn't very representative of a bug with flutter as it uses 3rd party packages ([getx](https://github.com/jonataslaw/getx/issues/2251))

Thank you sir, respectfully thats only the folder name. I am on latest version.  I removed every reference to get_connect from getx but the same issue arises without any update to the code or the packages. It was working fine before.

**Comment by darshankawar** [comment]
@CoderAssets 
After removing packages, did you run `flutter clean` or `flutter pub cache repair` to see if it helps ?

**Comment by CoderAssets** [comment]
turns out we should be careful working with any API related stuff. It was just an import related to web socket which has not been used in the code. Why is this I don't know.
