### ISSUE TITLE
[flutter_tools] "SocketException: Write failed (OS Error: Broken pipe, errno = 32)" during `flutter create`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#100584]
On [beta/2.12.0-4.1.pre](https://github.com/flutter/flutter/tree/2.12.0-4.1.pre)
Command `flutter create app`

```
Thread 0 main threadSocketException: SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
at _NativeSocket.write(socket_patch.dart:1190)
at _RawSocket.write(socket_patch.dart:1906)
at _Socket._write(socket_patch.dart:2346)
at _SocketStreamConsumer.write(socket_patch.dart:2094)
at _SocketStreamConsumer.addStream.<anonymous closure>(socket_patch.dart:2068)
at _rootRunUnary(zone.dart:1434)
at _CustomZone.runUnary(zone.dart:1335)
at _CustomZone.runUnaryGuarded(zone.dart:1244)
at _BufferingStreamSubscription._sendData(stream_impl.dart:341)
at _BufferingStreamSubscription._add(stream_impl.dart:271)
at _SyncStreamControllerDispatch._sendData(stream_controller.dart:774)
at _StreamController._add(stream_controller.dart:648)
at _StreamController.add(stream_controller.dart:596)
at _StreamSinkImpl.add(io_sink.dart:136)
at _IOSinkImpl.write(io_sink.dart:269)
at _Socket.write(socket_patch.dart:2184)
at _StdSink.write(stdio.dart:315)
at _getCodeSigningIdentityDevelopmentTeam(code_signing.dart:236)
at <asynchronous gap>(async)
at CreateCommand.runCommand(create.dart:263)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1165)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:281)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:229)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:62)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:94)
at <asynchronous gap>(async)
```

**Comment by christopherfujino** [comment]
https://github.com/flutter/flutter/blob/2.12.0-4.1.pre/packages/flutter_tools/lib/src/ios/code_signing.dart#L236

**Comment by christopherfujino** [comment]
We should probably catch the SocketException to the write and then check to see if anything interesting was written to STDERR.

**Comment by jmagman** [comment]
I think we should detect that it exited != 0 and throw with stderr and trace stdout since who knows which it uses, before trying to write

**Comment by jmagman** [comment]
Wait is there some way to do this noninteractively?

**Comment by christopherfujino** [comment]
> Wait is there some way to do this noninteractively?

you mean like writing to a file first?

**Comment by christopherfujino** [comment]
per `man x509`, it looks like `openssl x509 -subject -in /path/to/file` will work

**Comment by jmagman** [comment]
> you mean like writing to a file first?

I guess I don't see an easier way to do it...

btw adding `-noout` will make that output slightly nicer when it does work. Although stdout isn't printed so it doesn't matter...

**Comment by ik6cgsg** [comment]
Hi!

I've faced with the same problem on MacBook Air (M1, 2020) with macOS Monterey 12.3
Here's crash report for dev channel (for stable/beta channel report is the same):

```
## command

flutter --no-color create --template app --description A new Flutter project. --org com.example --platforms android,ios,macos --project-name untitled untitled

## exception

SocketException: SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0

#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1190:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1906:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2346:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2094:26)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2068:11)
#5      _rootRunUnary (dart:async/zone.dart:1434:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     _StreamSinkImpl.add (dart:io/io_sink.dart:136:17)
#14     _IOSinkImpl.write (dart:io/io_sink.dart:269:5)
#15     _Socket.write (dart:io-patch/socket_patch.dart:2184:36)
#16     _StdSink.write (dart:io/stdio.dart:315:11)
#17     _getCodeSigningIdentityDevelopmentTeam (package:flutter_tools/src/ios/code_signing.dart:236:32)
<asynchronous suspension>
#18     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:263:25)
<asynchronous suspension>
#19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#21     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

## flutter doctor

[✓] Flutter (Channel dev, 2.12.0-4.1.pre, on macOS 12.3 21E230 darwin-arm, locale ru-RU)
    • Flutter version 2.12.0-4.1.pre at /Users/ilyakozlov/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 680962aa75 (9 дней назад), 2022-03-16 13:46:03 -0700
    • Engine revision e9f57b5d0f
    • Dart version 2.17.0 (build 2.17.0-182.1.beta)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/ilyakozlov/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

WDYT, is it apple silicon procs problem?

**Comment by andrewkolos** [comment]
Umbrella issue: https://github.com/flutter/flutter/issues/137184
