### ISSUE TITLE
Image.network still throwing exception with errorBuilder but only with 'https://' in link

### ISSUE THREAD

**Issue by leo-mangold** [flutter/flutter#100651]
## Steps to Reproduce

I have a list of links and some may point to a link that doesn't exist anymore. In that case I want my app to display not found icon.
Everything works fine with the url empty or with just anything in it except for 'https://'. If the latter occurs my debugger stops because there apparently is an unhandled exception, and then after manually continuing the expected icon is shown.
So my only problem is the debugger stopping even though the exception is handled by `onError`.
**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

class Test extends StatelessWidget {
  const Test({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Image.network(
        'https://sldkfjlsdkjf',
        errorBuilder:
            (BuildContext context, Object exception, StackTrace? stackTrace) {
          return const Icon(Icons.not_interested);
        },
      ),
    );
  }
}
```

</details>

<details>
  <summary>Error message  </summary>

```

════════ Exception caught by image resource service ════════════════════════════
The following SocketException was thrown resolving an image codec:
Failed host lookup: 'sldkfjlsdkjf' (OS Error: nodename nor servname provided, or not known, errno = 8)

When the exception was thrown, this was the stack
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:237:22)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:60:28)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2438:24)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2834:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2839:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2698:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2575:48)
#10     NetworkImage._loadAsync
#11     NetworkImage.load
#12     ImageProvider.resolveStreamForKey.<anonymous closure>
#13     ImageCache.putIfAbsent
#14     ImageProvider.resolveStreamForKey
#15     ScrollAwareImageProvider.resolveStreamForKey
#16     ImageProvider.resolve.<anonymous closure>
#17     ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure>
#18     SynchronousFuture.then
#19     ImageProvider._createErrorHandlerAndKey.<anonymous closure>
#23     ImageProvider._createErrorHandlerAndKey
#24     ImageProvider.resolve
#25     _ImageState._resolveImage
#26     _ImageState.reassemble
#27     StatefulElement.reassemble
#28     Element.reassemble.<anonymous closure>
#29     ComponentElement.visitChildren
#30     Element.reassemble
#31     Element.reassemble.<anonymous closure>
#32     ComponentElement.visitChildren
#33     Element.reassemble
#34     StatefulElement.reassemble
#35     Element.reassemble.<anonymous closure>
#36     SingleChildRenderObjectElement.visitChildren
#37     Element.reassemble
#38     Element.reassemble.<anonymous closure>
#39     ComponentElement.visitChildren
#40     Element.reassemble
#41     Element.reassemble.<anonymous closure>
#42     SingleChildRenderObjectElement.visitChildren
#43     Element.reassemble
#44     Element.reassemble.<anonymous closure>
#45     ComponentElement.visitChildren
#46     Element.reassemble
#47     StatefulElement.reassemble
#48     Element.reassemble.<anonymous closure>
#49     ComponentElement.visitChildren
#50     Element.reassemble
#51     StatefulElement.reassemble
#52     Element.reassemble.<anonymous closure>
#53     ComponentElement.visitChildren
#54     Element.reassemble
#55     Element.reassemble.<anonymous closure>
#56     ComponentElement.visitChildren
#57     Element.reassemble
#58     StatefulElement.reassemble
#59     Element.reassemble.<anonymous closure>
#60     ComponentElement.visitChildren
#61     Element.reassemble
#62     StatefulElement.reassemble
#63     Element.reassemble.<anonymous closure>
#64     ComponentElement.visitChildren
#65     Element.reassemble
#66     _InheritedProviderScopeElement.reassemble
#67     Element.reassemble.<anonymous closure>
#68     ComponentElement.visitChildren
#69     Element.reassemble
#70     Element.reassemble.<anonymous closure>
#71     ComponentElement.visitChildren
#72     Element.reassemble
#73     Element.reassemble.<anonymous closure>
#74     ComponentElement.visitChildren
#75     Element.reassemble
#76     Element.reassemble.<anonymous closure>
#77     ComponentElement.visitChildren
#78     Element.reassemble
#79     _InheritedProviderScopeElement.reassemble
#80     Element.reassemble.<anonymous closure>
#81     ComponentElement.visitChildren
#82     Element.reassemble
#83     Element.reassemble.<anonymous closure>
#84     ComponentElement.visitChildren
#85     Element.reassemble
#86     Element.reassemble.<anonymous closure>
#87     SingleChildRenderObjectElement.visitChildren
#88     Element.reassemble
#89     Element.reassemble.<anonymous closure>
#90     ComponentElement.visitChildren
#91     Element.reassemble
#92     Element.reassemble.<anonymous closure>
#93     SingleChildRenderObjectElement.visitChildren
#94     Element.reassemble
#95     Element.reassemble.<anonymous closure>
#96     SingleChildRenderObjectElement.visitChildren
#97     Element.reassemble
#98     Element.reassemble.<anonymous closure>
#99     ComponentElement.visitChildren
#100    Element.reassemble
#101    StatefulElement.reassemble
#102    Element.reassemble.<anonymous closure>
#103    MultiChildRenderObjectElement.visitChildren
#104    Element.reassemble
#105    Element.reassemble.<anonymous closure>
#106    ComponentElement.visitChildren
#107    Element.reassemble
#108    StatefulElement.reassemble
#109    Element.reassemble.<anonymous closure>
#110    SingleChildRenderObjectElement.visitChildren
#111    Element.reassemble
#112    Element.reassemble.<anonymous closure>
#113    ComponentElement.visitChildren
#114    Element.reassemble
#115    StatefulElement.reassemble
#116    Element.reassemble.<anonymous closure>
#117    SingleChildRenderObjectElement.visitChildren
#118    Element.reassemble
#119    Element.reassemble.<anonymous closure>
#120    ComponentElement.visitChildren
#121    Element.reassemble
#122    StatefulElement.reassemble
#123    Element.reassemble.<anonymous closure>
#124    SingleChildRenderObjectElement.visitChildren
#125    Element.reassemble
#126    Element.reassemble.<anonymous closure>
#127    ComponentElement.visitChildren
#128    Element.reassemble
#129    StatefulElement.reassemble
#130    Element.reassemble.<anonymous closure>
#131    ComponentElement.visitChildren
#132    Element.reassemble
#133    Element.reassemble.<anonymous closure>
#134    ComponentElement.visitChildren
#135    Element.reassemble
#136    StatefulElement.reassemble
#137    Element.reassemble.<anonymous closure>
#138    SingleChildRenderObjectElement.visitChildren
#139    Element.reassemble
#140    Element.reassemble.<anonymous closure>
#141    SingleChildRenderObjectElement.visitChildren
#142    Element.reassemble
#143    Element.reassemble.<anonymous closure>
#144    ComponentElement.visitChildren
#145    Element.reassemble
#146    Element.reassemble.<anonymous closure>
#147    SingleChildRenderObjectElement.visitChildren
#148    Element.reassemble
#149    Element.reassemble.<anonymous closure>
#150    ComponentElement.visitChildren
#151    Element.reassemble
#152    StatefulElement.reassemble
#153    Element.reassemble.<anonymous closure>
#154    ComponentElement.visitChildren
#155    Element.reassemble
#156    Element.reassemble.<anonymous closure>
#157    ComponentElement.visitChildren
#158    Element.reassemble
#159    Element.reassemble.<anonymous closure>
#160    ComponentElement.visitChildren
#161    Element.reassemble
#162    StatefulElement.reassemble
#163    Element.reassemble.<anonymous closure>
#164    ComponentElement.visitChildren
#165    Element.reassemble
#166    Element.reassemble.<anonymous closure>
#167    ComponentElement.visitChildren
#168    Element.reassemble
#169    Element.reassemble.<anonymous closure>
#170    SingleChildRenderObjectElement.visitChildren
#171    Element.reassemble
#172    Element.reassemble.<anonymous closure>
#173    ComponentElement.visitChildren
#174    Element.reassemble
#175    Element.reassemble.<anonymous closure>
#176    ComponentElement.visitChildren
#177    Element.reassemble
#178    Element.reassemble.<anonymous closure>
#179    ComponentElement.visitChildren
#180    Element.reassemble
#181    StatefulElement.reassemble
#182    Element.reassemble.<anonymous closure>
#183    ComponentElement.visitChildren
#184    Element.reassemble
#185    StatefulElement.reassemble
#186    Element.reassemble.<anonymous closure>
#187    ComponentElement.visitChildren
#188    Element.reassemble
#189    StatefulElement.reassemble
#190    Element.reassemble.<anonymous closure>
#191    SingleChildRenderObjectElement.visitChildren
#192    Element.reassemble
#193    Element.reassemble.<anonymous closure>
#194    ComponentElement.visitChildren
#195    Element.reassemble
#196    Element.reassemble.<anonymous closure>
#197    ComponentElement.visitChildren
#198    Element.reassemble
#199    StatefulElement.reassemble
#200    Element.reassemble.<anonymous closure>
#201    ComponentElement.visitChildren
#202    Element.reassemble
#203    StatefulElement.reassemble
#204    Element.reassemble.<anonymous closure>
#205    MultiChildRenderObjectElement.visitChildren
#206    Element.reassemble
#207    Element.reassemble.<anonymous closure>
#208    ComponentElement.visitChildren
#209    Element.reassemble
#210    StatefulElement.reassemble
#211    Element.reassemble.<anonymous closure>
#212    ComponentElement.visitChildren
#213    Element.reassemble
#214    Element.reassemble.<anonymous closure>
#215    ComponentElement.visitChildren
#216    Element.reassemble
#217    Element.reassemble.<anonymous closure>
#218    SingleChildRenderObjectElement.visitChildren
#219    Element.reassemble
#220    Element.reassemble.<anonymous closure>
#221    ComponentElement.visitChildren
#222    Element.reassemble
#223    StatefulElement.reassemble
#224    Element.reassemble.<anonymous closure>
#225    SingleChildRenderObjectElement.visitChildren
#226    Element.reassemble
#227    Element.reassemble.<anonymous closure>
#228    SingleChildRenderObjectElement.visitChildren
#229    Element.reassemble
#230    Element.reassemble.<anonymous closure>
#231    ComponentElement.visitChildren
#232    Element.reassemble
#233    Element.reassemble.<anonymous closure>
#234    ComponentElement.visitChildren
#235    Element.reassemble
#236    StatefulElement.reassemble
#237    Element.reassemble.<anonymous closure>
#238    ComponentElement.visitChildren
#239    Element.reassemble
#240    Element.reassemble.<anonymous closure>
#241    ComponentElement.visitChildren
#242    Element.reassemble
#243    Element.reassemble.<anonymous closure>
#244    ComponentElement.visitChildren
#245    Element.reassemble
#246    Element.reassemble.<anonymous closure>
#247    ComponentElement.visitChildren
#248    Element.reassemble
#249    Element.reassemble.<anonymous closure>
#250    ComponentElement.visitChildren
#251    Element.reassemble
#252    Element.reassemble.<anonymous closure>
#253    ComponentElement.visitChildren
#254    Element.reassemble
#255    Element.reassemble.<anonymous closure>
#256    ComponentElement.visitChildren
#257    Element.reassemble
#258    StatefulElement.reassemble
#259    Element.reassemble.<anonymous closure>
#260    ComponentElement.visitChildren
#261    Element.reassemble
#262    Element.reassemble.<anonymous closure>
#263    ComponentElement.visitChildren
#264    Element.reassemble
#265    StatefulElement.reassemble
#266    Element.reassemble.<anonymous closure>
#267    ComponentElement.visitChildren
#268    Element.reassemble
#269    Element.reassemble.<anonymous closure>
#270    ComponentElement.visitChildren
#271    Element.reassemble
#272    Element.reassemble.<anonymous closure>
#273    ComponentElement.visitChildren
#274    Element.reassemble
#275    Element.reassemble.<anonymous closure>
#276    ComponentElement.visitChildren
#277    Element.reassemble
#278    Element.reassemble.<anonymous closure>
#279    ComponentElement.visitChildren
#280    Element.reassemble
#281    Element.reassemble.<anonymous closure>
#282    SingleChildRenderObjectElement.visitChildren
#283    Element.reassemble
#284    Element.reassemble.<anonymous closure>
#285    ComponentElement.visitChildren
#286    Element.reassemble
#287    StatefulElement.reassemble
#288    Element.reassemble.<anonymous closure>
#289    ComponentElement.visitChildren
#290    Element.reassemble
#291    Element.reassemble.<anonymous closure>
#292    ComponentElement.visitChildren
#293    Element.reassemble
#294    StatefulElement.reassemble
#295    Element.reassemble.<anonymous closure>
#296    ComponentElement.visitChildren
#297    Element.reassemble
#298    Element.reassemble.<anonymous closure>
#299    ComponentElement.visitChildren
#300    Element.reassemble
#301    StatefulElement.reassemble
#302    Element.reassemble.<anonymous closure>
#303    ComponentElement.visitChildren
#304    Element.reassemble
#305    Element.reassemble.<anonymous closure>
#306    ComponentElement.visitChildren
#307    Element.reassemble
#308    StatefulElement.reassemble
#309    Element.reassemble.<anonymous closure>
#310    ComponentElement.visitChildren
#311    Element.reassemble
#312    Element.reassemble.<anonymous closure>
#313    ComponentElement.visitChildren
#314    Element.reassemble
#315    StatefulElement.reassemble
#316    Element.reassemble.<anonymous closure>
#317    ComponentElement.visitChildren
#318    Element.reassemble
#319    Element.reassemble.<anonymous closure>
#320    SingleChildRenderObjectElement.visitChildren
#321    Element.reassemble
#322    Element.reassemble.<anonymous closure>
#323    ComponentElement.visitChildren
#324    Element.reassemble
#325    Element.reassemble.<anonymous closure>
#326    ComponentElement.visitChildren
#327    Element.reassemble
#328    StatefulElement.reassemble
#329    Element.reassemble.<anonymous closure>
#330    ComponentElement.visitChildren
#331    Element.reassemble
#332    StatefulElement.reassemble
#333    Element.reassemble.<anonymous closure>
#334    ComponentElement.visitChildren
#335    Element.reassemble
#336    Element.reassemble.<anonymous closure>
#337    SingleChildRenderObjectElement.visitChildren
#338    Element.reassemble
#339    Element.reassemble.<anonymous closure>
#340    ComponentElement.visitChildren
#341    Element.reassemble
#342    Element.reassemble.<anonymous closure>
#343    ComponentElement.visitChildren
#344    Element.reassemble
#345    StatefulElement.reassemble
#346    Element.reassemble.<anonymous closure>
#347    ComponentElement.visitChildren
#348    Element.reassemble
#349    StatefulElement.reassemble
#350    Element.reassemble.<anonymous closure>
#351    ComponentElement.visitChildren
#352    Element.reassemble
#353    Element.reassemble.<anonymous closure>
#354    ComponentElement.visitChildren
#355    Element.reassemble
#356    StatefulElement.reassemble
#357    Element.reassemble.<anonymous closure>
#358    ComponentElement.visitChildren
#359    Element.reassemble
#360    Element.reassemble.<anonymous closure>
#361    ComponentElement.visitChildren
#362    Element.reassemble
#363    StatefulElement.reassemble
#364    Element.reassemble.<anonymous closure>
#365    ComponentElement.visitChildren
#366    Element.reassemble
#367    Element.reassemble.<anonymous closure>
#368    ComponentElement.visitChildren
#369    Element.reassemble
#370    StatefulElement.reassemble
#371    Element.reassemble.<anonymous closure>
#372    ComponentElement.visitChildren
#373    Element.reassemble
#374    StatefulElement.reassemble
#375    Element.reassemble.<anonymous closure>
#376    SingleChildRenderObjectElement.visitChildren
#377    Element.reassemble
#378    Element.reassemble.<anonymous closure>
#379    ComponentElement.visitChildren
#380    Element.reassemble
#381    Element.reassemble.<anonymous closure>
#382    ComponentElement.visitChildren
#383    Element.reassemble
#384    StatefulElement.reassemble
#385    Element.reassemble.<anonymous closure>
#386    ComponentElement.visitChildren
#387    Element.reassemble
#388    Element.reassemble.<anonymous closure>
#389    ComponentElement.visitChildren
#390    Element.reassemble
#391    Element.reassemble.<anonymous closure>
#392    ComponentElement.visitChildren
#393    Element.reassemble
#394    StatefulElement.reassemble
#395    Element.reassemble.<anonymous closure>
#396    ComponentElement.visitChildren
#397    Element.reassemble
#398    StatefulElement.reassemble
#399    Element.reassemble.<anonymous closure>
#400    ComponentElement.visitChildren
#401    Element.reassemble
#402    StatefulElement.reassemble
#403    Element.reassemble.<anonymous closure>
#404    ComponentElement.visitChildren
#405    Element.reassemble
#406    StatefulElement.reassemble
#407    Element.reassemble.<anonymous closure>
#408    RenderObjectToWidgetElement.visitChildren
#409    Element.reassemble
#410    BuildOwner.reassemble
#411    WidgetsBinding.performReassemble
#412    BindingBase.lockEvents
#413    BindingBase.reassembleApplication
#414    BindingBase.registerSignalServiceExtension.<anonymous closure>
#415    BindingBase.registerSignalServiceExtension.<anonymous closure>
#416    BindingBase.registerServiceExtension.<anonymous closure>
<asynchronous suspension>
(elided 3 frames from dart:async)
Image provider: NetworkImage("https://sldkfjlsdkjf", scale: 1.0)
Image key: NetworkImage("https://sldkfjlsdkjf", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)
    ! Error: WhiteXmass is not connected. Xcode will continue when WhiteXmass is connected. (code -13)
    ! Error: Leos’s iPhone is not connected. Xcode will continue when Leos’s iPhone is connected. (code -13)
    ! Error: Leos’s iPad is not connected. Xcode will continue when Leos’s iPad is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**some text as url**
<img width="1680" alt="Screenshot 2022-03-23 at 21 03 09" src="https://user-images.githubusercontent.com/42837960/159787897-23118d24-4576-4ebe-9953-e96b000873cc.png">
**empty url**
<img width="1680" alt="Screenshot 2022-03-23 at 21 03 21" src="https://user-images.githubusercontent.com/42837960/159787933-47d479bd-964d-4c06-94e9-26643361cf71.png">
**url with 'https://' where vs code breaks**
<img width="1680" alt="Screenshot 2022-03-23 at 21 03 45" src="https://user-images.githubusercontent.com/42837960/159788047-83d7e597-330a-4e18-837e-3669258b8cc4.png">
<img width="1680" alt="Screenshot 2022-03-23 at 21 03 30" src="https://user-images.githubusercontent.com/42837960/159788063-a2ee7ec1-5abb-4714-8b56-b4bd27907ed4.png">

**Comment by maheshmnj** [comment]
Hi @leo-mangold, Thanks for filing the issue.

There is a similar issue describing this case https://github.com/flutter/flutter/issues/69125, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
