### ISSUE TITLE
Waiting for observatory port to be available timeout exception

### ISSUE THREAD

**Issue by afgno** [flutter/flutter#10064]
Trying to run any of the examples on android emulator results in a timeout exception. The application is successfully installed and it runs as expected. However, the port forwarding needed to access the observatory is never configured. This is only happening while using the emulator. 

I did some quick testing and the problem seems to be inside protocol_discovery.dart:

This exception is being thrown:
```
 /// The [Future] returned by this function will complete when the next service
51    /// Uri is found.                                                            
  1   Future<Uri> nextUri() async {                                                
  2     final Uri deviceUri = await _completer.future.timeout(                     
  3       const Duration(seconds: 60), onTimeout: () {                             
  4         throwToolExit('Timeout while attempting to retrieve Uri for $_serviceName');
  5       }                                                                        
  6     );     
```

The function receives the correct Uri and the assertions are passed, but the completer is being deallocated before informing the listeners. By commenting line 100 out, the issue is resolved.

```
95    void _located(Uri uri) {                                                     
96     assert(_completer != null);                                                
97     assert(!_completer.isCompleted);                                           
98                                                                                
99     _completer.complete(uri);                                                  
100     _completer = new Completer<Uri>();                                         
101   }    
```   
I also tried assigning the new completer in the future's whenComplete() instead, and it also fixed the problem. 

## Logs

```
[            ] Android SDK built for x86 startApp
[            ] /home/afgno/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true io.flutter.examples.hello_world/io.flutter.examples.hello_world.MainActivity
[     +318 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=io.flutter.examples.hello_world/.MainActivity (has extras) }
[            ] Waiting for observatory port to be available...
[   +60006 ms] Error waiting for a debug connection: Exception: Timeout while attempting to retrieve Uri for Observatory
[       +1 ms] Error launching application on Android SDK built for x86.
[       +6 ms] "flutter run" took 62,860ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:327)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#3      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:210)
<asynchronous suspension>
#4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#8      Future.Future.sync (dart:async/future.dart:208)
#9      CommandRunner.run (package:args/command_runner.dart:109)
#10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:156)
#11     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#13     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     runZoned (dart:async/zone.dart:1465)
#17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#18     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#20     main (file:///home/afgno/Code/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[     +252 ms] ensureAnalyticsSent: 250ms
[       +2 ms] exiting with code 2

```

# Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /home/afgno/Code/flutter
    • Framework revision 4b7a1912ee (3 hours ago), 2017-05-12 17:45:17 -0700
    • Engine revision bc8e3b5e72
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/afgno/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

**Comment by eseidelGoogle** [comment]
@tvolkert might have some debugging tips.

**Comment by tvolkert** [comment]
That code is most definitely racy!  I'll send a PR to fix.

**Comment by ilhom0258** [comment]
Would you please suggest steps to setup flutter in VS code with external emulator running(USB debugging)? 
Thanks
