### ISSUE TITLE
`Mac_arm64_staging build_ios_framework_module_test` fails with `ProcessException: Bad CPU type in executable`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#100637]
Part of https://github.com/flutter/flutter/issues/87508

[Mac_arm64_staging build_ios_framework_module_test](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/b0b24ac5dd8076f5d07372b9bbf69897c36c31ca20a132533f912bbbde02a7fa/+/build.proto)

```
[build_ios_framework_module_test] [STDOUT] stdout: [   +1 ms] Done persisting file store
[build_ios_framework_module_test] [STDOUT] stderr: [   +1 ms] ProcessException: Bad CPU type in executable
[build_ios_framework_module_test] [STDOUT] stderr:              Command: /opt/s/w/ir/x/w/recipe_cleanup/tmp4og2i2t8/flutter sdk/bin/cache/artifacts/engine/ios-profile/gen_snapshot_armv7 --deterministic --snapshot_kind=app-aot-assembly --assembly=/opt/s/w/ir/x/t/flutter_module_test.Kkz7Vj/hello_module/.dart_tool/flutter_build/34fb20fb3c5fc2689586dc06dc1a0ed5/armv7/snapshot_assembly.S --strip --no-sim-use-hardfp --no-use-integer-division --dwarf-stack-traces --save-debugging-info=symbols/app.ios-armv7.symbols --obfuscate /opt/s/w/ir/x/t/flutter_module_test.Kkz7Vj/hello_module/.dart_tool/flutter_build/34fb20fb3c5fc2689586dc06dc1a0ed5/app.dill
[build_ios_framework_module_test] [STDOUT] stdout: [        ]  ├─Building App.xcframework... (completed in 6.6s)
[build_ios_framework_module_test] [STDOUT] stdout: [        ] "flutter ios-framework" took 25,542ms.
[build_ios_framework_module_test] [STDOUT] stderr: [   +1 ms] The App.xcframework build failed.
[build_ios_framework_module_test] [STDOUT] stderr: [        ] 
[build_ios_framework_module_test] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[build_ios_framework_module_test] [STDOUT] stderr:            #1      BuildIOSFrameworkCommand._produceAppFramework (package:flutter_tools/src/commands/build_ios_framework.dart:394:11)
[build_ios_framework_module_test] [STDOUT] stderr:            <asynchronous suspension>
[build_ios_framework_module_test] [STDOUT] stderr:            #2      BuildIOSFrameworkCommand.runCommand (package:flutter_tools/src/commands/build_ios_framework.dart:198:7)
[build_ios_framework_module_test] [STDOUT] stderr:            <asynchronous suspension>
[build_ios_framework_module_test] [STDOUT] stderr:            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1173:27)
[build_ios_framework_module_test] [STDOUT] stderr:            <asynchronous suspension>
[build_ios_framework_module_test] [STDOUT] stderr:            #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[build_ios_framework_module_test] [STDOUT] stderr:            <asynchronous suspension>
[build_ios_framework_module_test] [STDOUT] stderr:            #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[build_ios_framework_module_test] [STDOUT] stderr:            <asynchronous suspension>
[build_ios_framework_module_test] [STDOUT] stderr:            #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
[build_ios_framework_module_test] [STDOUT] stderr:            <asynchronous suspension>
[build_ios_framework_module_test] [STDOUT] stderr:            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[build_ios_framework_module_test] [STDOUT] stderr:            <asynchronous suspension>
```

**Comment by jmagman** [comment]
Also seen in https://ci.chromium.org/p/flutter/builders/staging/Mac_arm64_staging%20module_test_ios/424

**Comment by jmagman** [comment]
@keyonghan is Rosetta installed? I think that's what `Bad CPU type in executable` means.

@zanderso @cbracken on my M1 Mac all my iOS and macOS `gen_snapshot` binaries are `x86_64`, are we tracking building them as ARM executables anywhere?
```
./ios-profile/gen_snapshot_arm64:                 Mach-O 64-bit executable x86_64
./ios-profile/gen_snapshot_armv7:                 Mach-O 64-bit executable x86_64
./darwin-x64-profile/gen_snapshot_arm64:          Mach-O 64-bit executable x86_64
./darwin-x64-profile/gen_snapshot_x64:            Mach-O 64-bit executable x86_64
./darwin-x64-profile/gen_snapshot:                Mach-O 64-bit executable x86_64
./darwin-x64/gen_snapshot_arm64:                  Mach-O 64-bit executable x86_64
./darwin-x64/gen_snapshot_x64:                    Mach-O 64-bit executable x86_64
./darwin-x64/gen_snapshot:                        Mach-O 64-bit executable x86_64
./ios/gen_snapshot_arm64:                         Mach-O 64-bit executable x86_64
./ios/gen_snapshot_armv7:                         Mach-O 64-bit executable x86_64
./ios-release/gen_snapshot_arm64:                 Mach-O 64-bit executable x86_64
./ios-release/gen_snapshot_armv7:                 Mach-O 64-bit executable x86_64
./darwin-x64-release/gen_snapshot_arm64:          Mach-O 64-bit executable x86_64
./darwin-x64-release/gen_snapshot_x64:            Mach-O 64-bit executable x86_64
./darwin-x64-release/gen_snapshot:                Mach-O 64-bit executable x86_64
```

**Comment by zanderso** [comment]
@jmagman This is expected. Dart does not currently support targeting x64 from a non-x64 host.

**Comment by jmagman** [comment]
Should the `gen_snapshot_arm64` binaries be arm?

**Comment by zanderso** [comment]
> Should the `gen_snapshot_arm64` binaries be arm?

We could probably figure out how to do that, but for right now they are intentionally x64 binaries.

**Comment by keyonghan** [comment]
> @keyonghan[](https://teams.googleplex.com/keyonghan@google.com) is Rosetta installed? I think that's what Bad CPU type in executable means.

So for this case, in addition to the arm64 ruby, we also need to install Rosetta? Let me give it a try.

**Comment by jmagman** [comment]
> we also need to install Rosetta

All builders will require Rosetta, we still don't have arm64 native execution for all binaries (like `gen_snapshot_*`)

**Comment by jmagman** [comment]
> We could probably figure out how to do that, but for right now they are intentionally x64 binaries.

Filed https://github.com/flutter/flutter/issues/101138

**Comment by jmagman** [comment]
@keyonghan I think you already fixed this somewhere since the test is now passing, can this be closed?

**Comment by keyonghan** [comment]
> @keyonghan[](https://teams.googleplex.com/keyonghan@google.com) I think you already fixed this somewhere since the test is now passing, can this be closed?

I believe this is fixed by running swarming server against arm64 python.
