### ISSUE TITLE
`FollowerLayer` (`CompositedTransformFollower`) has null pointer error when using with some kinds of `Layer`s

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#100670]
## Steps to Reproduce

I have found the cause and will PR.

Run the minimal reproducible sample on flutter beta.

**Expected results:** 
no error

**Actual results:** 
has error

<details>
<summary>Code sample</summary>

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('FollowerLayer has bug', (tester) async {
    final link = LayerLink();
    await tester.pumpWidget(
      CompositedTransformTarget(
        link: link,
        child: CompositedTransformFollower(
          link: link,
          child: MyWidget(),
        ),
      ),
    );
  });
}

class MyWidget extends SingleChildRenderObjectWidget {
  const MyWidget({Key? key, Widget? child}) : super(key: key, child: child);

  @override
  MyRenderObject createRenderObject(BuildContext context) => MyRenderObject();

  @override
  void updateRenderObject(BuildContext context, MyRenderObject renderObject) {}
}

class MyRenderObject extends RenderProxyBox {
  MyRenderObject({RenderBox? child}) : super(child);

  @override
  void paint(PaintingContext context, Offset offset) {
    if (layer == null) {
      layer = MyLayer(
        computeSomething: _computeSomething,
      );
    } else {
      (layer as MyLayer?)?.computeSomething = _computeSomething;
    }

    context.pushLayer(layer!, super.paint, Offset.zero);
  }

  void _computeSomething() {
    // indeed, use `globalToLocal` to compute some useful data
    globalToLocal(Offset.zero);
  }
}

class MyLayer extends ContainerLayer {
  MyLayer({required this.computeSomething});

  VoidCallback computeSomething;

  @override
  void addToScene(ui.SceneBuilder builder) {
    computeSomething(); // indeed, need to use result of this function
    super.addToScene(builder);
  }
}
```

</details>

<details>
  <summary>Logs</summary>

flutter stable

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      FollowerLayer.getLastTransform (package:flutter/src/rendering/layer.dart:2435:66)
#1      RenderFollowerLayer.getCurrentTransform (package:flutter/src/rendering/proxy_box.dart:5286:19)
#2      RenderFollowerLayer.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:5355:24)
#3      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2532:24)
#4      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2580:31)
#5      MyRenderObject._computeSomething (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:50:5)
#6      MyLayer.addToScene (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:61:21)
#7      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
#8      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)
#9      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:2567:7)
#10     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
#11     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)
#12     LeaderLayer.addToScene (package:flutter/src/rendering/layer.dart:2270:5)
#13     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
#14     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)
#15     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1680:5)
#16     ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:937:5)
#17     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:228:37)
#18     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1138:26)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#22     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#26     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#27     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#30     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#31     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#32     main.<anonymous closure> (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:10:18)
#33     main.<anonymous closure> (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:8:40)
#34     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: FollowerLayer has bug [E]                                                                                                            
  Test failed. See exception logs above.
  The test description was: FollowerLayer has bug
```

flutter beta

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      FollowerLayer.getLastTransform (package:flutter/src/rendering/layer.dart:2397:66)
#1      RenderFollowerLayer.getCurrentTransform (package:flutter/src/rendering/proxy_box.dart:5286:19)
#2      RenderFollowerLayer.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:5355:24)
#3      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2534:24)
#4      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2577:31)
#5      MyRenderObject._computeSomething (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:50:5)
#6      MyLayer.addToScene (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:61:21)
#7      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#8      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
#9      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:2560:7)
#10     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#11     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
#12     LeaderLayer.addToScene (package:flutter/src/rendering/layer.dart:2252:5)
#13     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#14     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
#15     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1681:5)
#16     ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:938:5)
#17     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:228:37)
#18     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1138:26)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#22     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#26     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#27     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#30     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#31     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#32     main.<anonymous closure> (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:10:18)
#33     main.<anonymous closure> (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:8:40)
#34     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:11 +0 -1: FollowerLayer has bug [E]                                                                                                                                                                 
  Test failed. See exception logs above.
  The test description was: FollowerLayer has bug
  
00:11 +0 -1: Some tests failed.          
```

```
no errors
```

```
flutter 2.10 and flutter beta both has bug
```

</details>

**Comment by darshankawar** [comment]
This seems to be occurring on latest master and stable too.

<details>
<summary> console error log </summary>

```

flutter: (The following exception is now available via WidgetTester.takeException:)
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following _CastError was thrown during a scheduler callback:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      FollowerLayer.getLastTransform (package:flutter/src/rendering/layer.dart:2397:66)
flutter: #1      RenderFollowerLayer.getCurrentTransform (package:flutter/src/rendering/proxy_box.dart:5318:19)
flutter: #2      RenderFollowerLayer.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:5387:24)
flutter: #3      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2534:24)
flutter: #4      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2577:31)
flutter: #5      MyRenderObject._computeSomething (package:testdemo/main.dart:50:5)
flutter: #6      MyLayer.addToScene (package:testdemo/main.dart:61:21)
flutter: #7      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
flutter: #8      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
flutter: #9      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:2560:7)
flutter: #10     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
flutter: #11     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
flutter: #12     LeaderLayer.addToScene (package:flutter/src/rendering/layer.dart:2252:5)
flutter: #13     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
flutter: #14     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
flutter: #15     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1681:5)
flutter: #16     ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:938:5)
flutter: #17     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:228:37)
flutter: #18     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:505:18)
flutter: #19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
flutter: #20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:367:5)
flutter: #21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
flutter: #22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #23     LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1546:13)
flutter: #24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
flutter: #28     _invoke (dart:ui/hooks.dart:151:10)
flutter: #29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
flutter: #30     _drawFrame (dart:ui/hooks.dart:115:31)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following _CastError was thrown during a scheduler callback:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      FollowerLayer.getLastTransform (package:flutter/src/rendering/layer.dart:2397:66)
flutter: #1      RenderFollowerLayer.getCurrentTransform (package:flutter/src/rendering/proxy_box.dart:5318:19)
flutter: #2      RenderFollowerLayer.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:5387:24)
flutter: #3      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2534:24)
flutter: #4      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2577:31)
flutter: #5      MyRenderObject._computeSomething (package:testdemo/main.dart:50:5)
flutter: #6      MyLayer.addToScene (package:testdemo/main.dart:61:21)
flutter: #7      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
flutter: #8      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
flutter: #9      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:2560:7)
flutter: #10     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
flutter: #11     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
flutter: #12     LeaderLayer.addToScene (package:flutter/src/rendering/layer.dart:2252:5)
flutter: #13     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
flutter: #14     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
flutter: #15     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1681:5)
flutter: #16     ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:938:5)
flutter: #17     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:228:37)
flutter: #18     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:505:18)
flutter: #19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
flutter: #20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:367:5)
flutter: #21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
flutter: #22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #23     LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1546:13)
flutter: #24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
flutter: #28     _invoke (dart:ui/hooks.dart:151:10)
flutter: #29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
flutter: #30     _drawFrame (dart:ui/hooks.dart:115:31)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:00 +0: FollowerLayer has bug [E]
flutter:   Test failed. See exception logs above.
  The test description was: FollowerLayer has bug
flutter:
flutter: 00:00 +0 -1: Some tests failed.

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.232, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.232 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 703d8a0685 (2 hours ago), 2022-03-23 23:07:19 -0400
    • Engine revision 4fd8f7d068
    • Dart version 2.17.0 (build 2.17.0-231.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by fzyzcjy** [comment]
@darshankawar Hi I have made the PR and new tests are added and passed
