### ISSUE TITLE
[webview_flutter] Error in evaluateJavascriptFromInstance when restarting app

### ISSUE THREAD

**Issue by Z6P0** [flutter/flutter#100611]
This code works if run once, but crashes if restarted either with Hot Reload or with Run (without Stop).

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart' as webview;

main() {
  runApp(_Test());
}

class _Test extends StatelessWidget {
  final completer = Completer<webview.WebViewController>();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Future.value(1),
      builder: (context, snapshot) {
        if (snapshot.hasError) throw snapshot.error!;
        if (snapshot.connectionState != ConnectionState.done) return Container();
        return MaterialApp(
          home: Scaffold(
            body: Stack(
              children: [
                webview.WebView(
                  javascriptMode: webview.JavascriptMode.unrestricted,
                  onWebViewCreated: (controller) {
                    if (!completer.isCompleted) completer.complete(controller);
                  },
                ),
                Center(
                  child: FutureBuilder(
                    future: completer.future.then((controller) {
                      return controller.runJavascriptReturningResult('6*7');
                    }),
                    builder: (context, snapshot) {
                      if (snapshot.hasError) {
                        print(snapshot.stackTrace);
                        throw snapshot.error!;
                      }
                      if (snapshot.connectionState != ConnectionState.done) return Container();
                      return Text(snapshot.data.toString());
                    },
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}
```

Stack trace:

```
E/BufferItemConsumer(24103): [ImageReader-480x800f1m3-24103-0] Failed to release buffer: Unknown error -1 (1)
I/flutter (24103): #0      WebViewHostApiImpl.evaluateJavascriptFromInstance (package:webview_flutter_android/src/android_webview_api_impls.dart:210:48)
I/flutter (24103): #1      WebView.evaluateJavascript (package:webview_flutter_android/src/android_webview.dart:239:37)
I/flutter (24103): #2      WebViewAndroidPlatformController.runJavascriptReturningResult (package:webview_flutter_android/webview_android_widget.dart:287:26)
I/flutter (24103): #3      WebViewController.runJavascriptReturningResult (package:webview_flutter/src/webview.dart:755:10)
I/flutter (24103): #4      _Test.build.<anonymous closure>.<anonymous closure> (package:test_flutter_3/github_webview.dart:36:41)
I/flutter (24103): #5      _rootRunUnary (dart:async/zone.dart:1434:47)
I/flutter (24103): #6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter (24103): <asynchronous suspension>
I/flutter (24103): #7      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:627:33)
I/flutter (24103): <asynchronous suspension>

======== Exception caught by widgets library =======================================================
The following _CastError was thrown building FutureBuilder<String>(dirty, state: _FutureBuilderState<String>#fb253):
Null check operator used on a null value
```

webview_flutter version 3.0.1

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.4.0-104-generic,
    locale fr_FR.UTF-8)
    • Flutter version 2.10.3 at /opt/flutter_2.2.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (il y a 3 semaines), 2022-03-02 11:23:12
      -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/patrick/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /opt/idea-IC-202.8194.7
    • Flutter plugin version 65.2.4
    • Dart plugin version 213.7227

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android
      8.1.0 (API 27) (emulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @Z6P0, thanks for filing the issue. 

I am curious, what are you trying to achieve, perhaps there's a better way to go about it.

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master` using the code sample provided. 

On `android`, there is a crash but on `iOS`, there isn't a crash, however, the screen is just blank, it seems like the result is not being returned.

### Steps to reproduce
1. Run the code sample, you should see `42` on the screen
2. Hot reload the app
3. On android, an exception should be thrown. 
4. On ios, the screen should not have any text.

Leaving this for further insight from the team.

<details>
<summary>logs</summary>

[android.log](https://github.com/flutter/flutter/files/8340956/android.log)
[ios.log](https://github.com/flutter/flutter/files/8340957/ios.log)

</details>

<details>
<summary>flutter run -v</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 304CA91D-8D77-4AAE-A50F-ECFC57AFD011 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.233, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.233 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6e13f3d76e (6 hours ago), 2022-03-24 01:01:21 -0400
    • Engine revision 5d2aeca1d6
    • Dart version 2.17.0 (build 2.17.0-232.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 304CA91D-8D77-4AAE-A50F-ECFC57AFD011 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by stuartmorgan** [comment]
@bparrishMines Is the object tracking across the platform channel boundary being disrupted by hot reload?

**Comment by bparrishMines** [comment]
> @bparrishMines Is the object tracking across the platform channel boundary being disrupted by hot reload?

No, this is caused by the completer returning the same controller.

It is set once at:

```dart
final completer = Completer<webview.WebViewController>();
```

And then when hot reload is called, the `FutureBuilder` is using the completer that contains the old value.

```dart
future: completer.future.then((controller) {
    return controller.runJavascriptReturningResult('6*7');
}),
```

Also, a `Completer` will throw an error if complete is called on it twice, but code was included to prevent that.

```dart
onWebViewCreated: (controller) {
  if (!completer.isCompleted) completer.complete(controller);
}
``` 

The `WebView` is also being rebuilt because a new `Future` is being passed in the first `FutureBuilder`. Which causes the webView to be rebuilt each time.

@Z6P0 This should be fixable by setting the completer in the `build` method:

```dart
late Completer<webview.WebViewController> completer;

@override
Widget build(BuildContext context) {
  completer = Completer<webview.WebViewController>();
  return FutureBuilder(
  ...
}
```

or `Future.value(1)` needs to be saved to a variable. 

```dart
final Future<int> myFuture = Future<int>.value(1);

@override
Widget build(BuildContext context) {
  return FutureBuilder(
    future: myFuture,
    ...
}
```

**Comment by Z6P0** [comment]
> This should be fixable by setting the completer in the build method

But this won't work with the StatelessWidget that should be immutable. And a StatefulWidget also won't work because I want to have the method runJavascript in the Widget and not the State which is private.

**Comment by bparrishMines** [comment]
For a `StatelessWidget`, the completer could probably be moved into the build method.

```dart
@override
Widget build(BuildContext context) {
  final Completer<webview.WebViewController> completer = Completer<webview.WebViewController>();
  return FutureBuilder(
  ...
}
``` 

For `StatefulWidget`, I don't quite understand your use case. Are you trying to add a method to the widget that makes a `runJavascript` call? If so, I don't think this is a typical pattern with Flutter. Perhaps this widget could take an `onWebViewCreated` callback and return the `WebViewController` to the parent Widget?

```dart
class ParentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChildWidget(onWebViewReady: (WebViewController controller) {
      // do something with controller
    });
  }
}

class ChildWidget extends StatefulWidget {
  const ChildWidget({Key? key, required this.onWebViewReady}) : super(key: key);

  final void Function(WebViewController) onWebViewReady;

  @override
  State<StatefulWidget> createState() => ChildWidgetState();
}

class ChildWidgetState extends State<ChildWidget> {
  @override
  Widget build(BuildContext context) {
    return WebView(onWebViewCreated: widget.onWebViewReady);
  }
}
```

I'm not as familiar with creating custom widgets, so I can't really endorse an answer. I can only provide feedback on how to use the plugin.

**Comment by Z6P0** [comment]
> the completer could probably be moved into the build method

This won't work because I need the completer field to run Javascript. My goal is having a public function to run Javascript snippets.

**Comment by stuartmorgan** [comment]
Closing as obsolete; with the separate of the controller in webview_flutter 4.x, there should no longer be a transient object here that would be lost with hot reload.
