### ISSUE TITLE
GoogleSignInAccount.authentication throws an error 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>'

### ISSUE THREAD

**Issue by LeonManolo** [flutter/flutter#100768]
## Steps to Reproduce
1. Created OAuth credentials in the Google Cloud Console
![Screenshot 2022-03-17 at 12 59 50](https://user-images.githubusercontent.com/87019114/160140606-48d68acf-92a6-4c96-aa06-435abe38b0bc.png)
2. using google_sign_in: ^5.2.3

I dont use firebase Im planning on using Mongodb realm as the oauth provider, thats why I need the accessCode.

**Expected results:** a result of type GoogleSignInAuthentication

**Actual results:** Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>'

```dart
/// The only code Im using so far
  final scopes = ['profile', 'email'];
  const clientId = "127085625887-t9r6pl8abddu8f6fn1if2g65p9h1a51r.apps.googleusercontent.com";
  const web = "127085625887-57m8rb1laae0r9im0dvd8h6sqrgqetf5";

  final GoogleSignIn google = GoogleSignIn(
    scopes: scopes,
    serverClientId: "127085625887-57m8rb1laae0r9im0dvd8h6sqrgqetf5.apps.googleusercontent.com",
  );

  //google.currentUser.serverAuthCode

  final googleAccount = await google.signIn();
  final authCode = googleAccount?.serverAuthCode;
  final auth = await googleAccount?.authentication; //Throws the ERROR!
```

```
Binding to activity: com.google.android.gms.auth.api.signin.internal.SignInHubActivity
I/FIAM.Headless(13804): Setting display event component
I/FIAM.Headless(13804): Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
I/BranchSDK(13804): onActivityResumed, activity = com.google.android.gms.auth.api.signin.internal.SignInHubActivity@10f32d3
I/FIAM.Headless(13804): Fetching campaigns from service.
W/DynamiteModule(13804): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/FIAM.Display(13804): Unbinding from activity: com.google.android.gms.auth.api.signin.internal.SignInHubActivity
I/FIAM.Headless(13804): Removing display event component
I/BranchSDK(13804): onActivityPaused, activity = com.google.android.gms.auth.api.signin.internal.SignInHubActivity@10f32d3
I/FIAM.Display(13804): Binding to activity: MainActivity
I/FIAM.Headless(13804): Setting display event component
I/BranchSDK(13804): onActivityResumed, activity = com.fittastetic.fitnessrecipes.MainActivity@5427834
E/flutter (13804): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>' in type cast
E/flutter (13804): #0      GoogleSignInAccount.authentication (package:flutter_mongodb_realm/google_sign_in_git_mock/google_sign_in.dart:93:7)
E/flutter (13804): #1      authenticate (package:fitness_recipes/main.dart:62:24)
E/flutter (13804): <asynchronous suspension>
E/flutter (13804): 
I/BranchSDK(13804): onActivityStopped, activity = com.google.android.gms.auth.api.signin.internal.SignInHubActivity@10f32d3
D/FlutterBranchSDK(13804): onActivityStopped call
I/BranchSDK(13804): onActivityDestroyed, activity = com.google.android.gms.auth.api.signin.internal.SignInHubActivity@10f32d3
D/FlutterBranchSDK(13804): onActivityDestroyed call
I/DynamiteModule(13804): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller(13804): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
D/EGL_emulation(13804): app_time_stats: avg=836.94ms min=26.67ms max=10327.83ms count=13
I/FIAM.Headless(13804): Successfully fetched 0 messages from backend
```

**Comment by stuartmorgan** [comment]
> E/flutter (13804): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>' in type cast
E/flutter (13804): #0      GoogleSignInAccount.authentication (package:flutter_mongodb_realm/google_sign_in_git_mock/google_sign_in.dart:93:7)

Issues with third-party packages need to be reported to the developers of those packages. The error here is coming from `package:flutter_mongodb_realm`.
