### ISSUE TITLE
 HTTP Host Availability throws `HandshakeException:` error while running `flutter doctor -v`

### ISSUE THREAD

**Issue by jaymicm** [flutter/flutter#100762]
### Cant Build app, while try to run flutter doctor -v command below message i am getting. 

Let me know if there is any solution for this.

I have disabled firewall and antivirus still the same issue is there.

```

 C:\Windows\System32>flutter doctor -v
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19043.1586], locale en-IN)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at D:\JAY DATA\MyProjects\Android\android-sdk\
    • Platform android-32, build-tools 33.0.0-rc1
    • ANDROID_HOME = D:\JAY DATA\MyProjects\Android\android-sdk\
    • ANDROID_SDK_ROOT = D:\JAY DATA\MyProjects\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\jay\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] VS Code, 64-bit edition (version 1.54.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.53

[☠] HTTP Host Availability (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X HandshakeException: Handshake error in client (OS Error:
        BLOCK_TYPE_IS_NOT_01(../../third_party/boringssl/src/crypto/fipsmodule/rsa/padding.c:108)
        PADDING_CHECK_FAILED(../../third_party/boringssl/src/crypto/fipsmodule/rsa/rsa_impl.c:676)
        public key routines(../../third_party/boringssl/src/crypto/x509/a_verify.c:108)
        CERTIFICATE_VERIFY_FAILED: certificate signature failure(../../third_party/boringssl/src/ssl/handshake.cc:393))
    • #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:104:46)
      #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:147:25)
      #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:803:54)
      #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:933:19)
      <asynchronous suspension>


! Doctor found issues in 2 categories.

```

### 2. while run the app / build apk from android studio getting below error:

Please give any solution for this...
```

Downloading android-arm-profile/windows-x64 tools...                3.5s
Downloading android-arm-profile/windows-x64 tools...               110ms
Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/bd539267b42051b0da3d16ffa8f48949dce8aa8f/android-arm-profile/windows-x64.zip. Ensure you have network connectivity and then try again.
HandshakeException: Handshake error in client (OS Error: 
	BLOCK_TYPE_IS_NOT_01(../../third_party/boringssl/src/crypto/fipsmodule/rsa/padding.c:108)
	PADDING_CHECK_FAILED(../../third_party/boringssl/src/crypto/fipsmodule/rsa/rsa_impl.c:676)
	public key routines(../../third_party/boringssl/src/crypto/x509/a_verify.c:108)
	CERTIFICATE_VERIFY_FAILED: certificate signature failure(../../third_party/boringssl/src/ssl/handshake.cc:393))
```

**Comment by darshankawar** [comment]
I am unable to replicate this behavior after running `flutter doctor` on Windows machine. 

```
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

Keeping it open and labeling for further insights from the team.
