### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'.

### ISSUE THREAD

**Issue by AhlemKhng** [flutter/flutter#100734]
<details>
<summary>build logs</summary>

```console
Launching lib/main.dart on SM A205F in debug mode...
Running Gradle task 'assembleDebug'...
Invalid depfile: /Users/Admin/Desktop/newshour-406/codecanyon/main_files/source/newshour_app/.dart_tool/flutter_build/a98a031c63ffbdb89b9bf0527a16d63f/kernel_snapshot.d
Invalid depfile: /Users/Admin/Desktop/newshour-406/codecanyon/main_files/source/newshour_app/.dart_tool/flutter_build/a98a031c63ffbdb89b9bf0527a16d63f/kernel_snapshot.d
Error: Couldn't resolve the package 'news_app' in 'package:news_app/pages/welcome.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/config/ad_config.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/models/article.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/utils/toast.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/constants/constants.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/pages/notifications.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/utils/next_screen.dart'.
lib/pages/splash.dart:3:8: Error: Not found: 'package:news_app/pages/welcome.dart'
import 'package:news_app/pages/welcome.dart';
       ^
Error: Couldn't resolve the package 'news_app' in 'package:news_app/pages/article_details.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/pages/video_article_details.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/blocs/ads_bloc.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/blocs/notification_bloc.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/pages/categories.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/pages/explore.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/pages/profile.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/pages/videos.dart'.
lib/blocs/ads_bloc.dart:5:8: Error: Not found: 'package:news_app/config/ad_config.dart'
import 'package:news_app/config/ad_config.dart';
       ^
lib/blocs/article_notification_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/bookmark_bloc.dart:3:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/category_tab1_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/category_tab2_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/category_tab3_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/category_tab4_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/featured_bloc.dart:3:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/popular_articles_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/recent_articles_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/related_articles_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/search_bloc.dart:3:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/videos_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';
       ^
lib/blocs/comments_bloc.dart:4:8: Error: Not found: 'package:news_app/utils/toast.dart'
import 'package:news_app/utils/toast.dart';
       ^
lib/blocs/notification_bloc.dart:7:8: Error: Not found: 'package:news_app/constants/constants.dart'
import 'package:news_app/constants/constants.dart';
       ^
lib/blocs/notification_bloc.dart:8:8: Error: Not found: 'package:news_app/pages/notifications.dart'
import 'package:news_app/pages/notifications.dart';
       ^
lib/blocs/notification_bloc.dart:9:8: Error: Not found: 'package:news_app/utils/next_screen.dart'
import 'package:news_app/utils/next_screen.dart';
       ^
lib/utils/next_screen.dart:4:8: Error: Not found: 'package:news_app/pages/article_details.dart'
import 'package:news_app/pages/article_details.dart';
       ^
lib/utils/next_screen.dart:5:8: Error: Not found: 'package:news_app/pages/video_article_details.dart'
import 'package:news_app/pages/video_article_details.dart';
       ^
lib/pages/home.dart:4:8: Error: Not found: 'package:news_app/blocs/ads_bloc.dart'
import 'package:news_app/blocs/ads_bloc.dart';
       ^
lib/pages/home.dart:5:8: Error: Not found: 'package:news_app/blocs/notification_bloc.dart'
import 'package:news_app/blocs/notification_bloc.dart';
       ^
lib/pages/home.dart:6:8: Error: Not found: 'package:news_app/pages/categories.dart'
import 'package:news_app/pages/categories.dart';
       ^
lib/pages/home.dart:7:8: Error: Not found: 'package:news_app/pages/explore.dart'
import 'package:news_app/pages/explore.dart';
       ^
lib/pages/home.dart:8:8: Error: Not found: 'package:news_app/pages/profile.dart'
import 'package:news_app/pages/profile.dart';
       ^
lib/pages/home.dart:9:8: Error: Not found: 'package:news_app/pages/videos.dart'
import 'package:news_app/pages/videos.dart';
       ^
Error: Couldn't resolve the package 'news_app' in 'package:news_app/blocs/sign_in_bloc.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/blocs/theme_bloc.dart'.
Error: Couldn't resolve the package 'news_app' in 'package:news_app/config/config.dart'.
lib/services/app_service.dart:9:8: Error: Not found: 'package:news_app/utils/toast.dart'
import 'package:news_app/utils/toast.dart';
       ^
lib/services/app_service.dart:5:8: Error: Not found: 'package:news_app/blocs/sign_in_bloc.dart'
import 'package:news_app/blocs/sign_in_bloc.dart';
       ^
lib/services/app_service.dart:6:8: Error: Not found: 'package:news_app/blocs/theme_bloc.dart'
import 'package:news_app/blocs/theme_bloc.dart';
       ^
lib/services/app_service.dart:7:8: Error: Not found: 'package:news_app/config/config.dart'
import 'package:news_app/config/config.dart';
       ^
lib/blocs/article_notification_bloc.dart:15:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/article_notification_bloc.dart:16:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/blocs/category_tab1_bloc.dart:8:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/category_tab1_bloc.dart:9:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/blocs/category_tab2_bloc.dart:8:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/category_tab2_bloc.dart:9:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/blocs/category_tab3_bloc.dart:8:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/category_tab3_bloc.dart:9:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/blocs/category_tab4_bloc.dart:8:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/category_tab4_bloc.dart:9:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/blocs/featured_bloc.dart:9:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/featured_bloc.dart:10:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/blocs/popular_articles_bloc.dart:8:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/popular_articles_bloc.dart:9:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/blocs/recent_articles_bloc.dart:8:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/recent_articles_bloc.dart:9:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/blocs/related_articles_bloc.dart:8:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/related_articles_bloc.dart:9:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/blocs/videos_bloc.dart:14:8: Error: Type 'Article' not found.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/videos_bloc.dart:15:8: Error: Type 'Article' not found.
  List<Article> get data => _data;
       ^^^^^^^
lib/pages/splash.dart:42:32: Error: The method 'WelcomePage' isn't defined for the class '_SplashPageState'.
 - '_SplashPageState' is from 'package:zalet_myay/pages/splash.dart' ('lib/pages/splash.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WelcomePage'.
    nextScreenReplace(context, WelcomePage());
                               ^^^^^^^^^^^
lib/blocs/ads_bloc.dart:67:19: Error: The method 'AdConfig' isn't defined for the class 'AdsBloc'.
 - 'AdsBloc' is from 'package:zalet_myay/blocs/ads_bloc.dart' ('lib/blocs/ads_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'AdConfig'.
        adUnitId: AdConfig().getAdmobInterstitialAdUnitId(),
                  ^^^^^^^^
lib/blocs/article_notification_bloc.dart:15:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/article_notification_bloc.dart:62:38: Error: The getter 'Article' isn't defined for the class 'ArticleNotificationBloc'.
 - 'ArticleNotificationBloc' is from 'package:zalet_myay/blocs/article_notification_bloc.dart' ('lib/blocs/article_notification_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
            _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                                     ^^^^^^^
lib/blocs/article_notification_bloc.dart:63:35: Error: The getter 'timestamp' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'timestamp'.
            _data.sort((a,b) => b.timestamp!.compareTo(a.timestamp!));
                                  ^^^^^^^^^
lib/blocs/article_notification_bloc.dart:63:58: Error: The getter 'timestamp' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'timestamp'.
            _data.sort((a,b) => b.timestamp!.compareTo(a.timestamp!));
                                                         ^^^^^^^^^
lib/blocs/bookmark_bloc.dart:61:41: Error: The getter 'Article' isn't defined for the class 'BookmarkBloc'.
 - 'BookmarkBloc' is from 'package:zalet_myay/blocs/bookmark_bloc.dart' ('lib/blocs/bookmark_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
          d.addAll(snap.docs.map((e) => Article.fromFirestore(e)).toList());
                                        ^^^^^^^
lib/blocs/bookmark_bloc.dart:78:41: Error: The getter 'Article' isn't defined for the class 'BookmarkBloc'.
 - 'BookmarkBloc' is from 'package:zalet_myay/blocs/bookmark_bloc.dart' ('lib/blocs/bookmark_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
          d.addAll(snap.docs.map((e) => Article.fromFirestore(e)).toList());
                                        ^^^^^^^
lib/blocs/bookmark_bloc.dart:85:41: Error: The getter 'Article' isn't defined for the class 'BookmarkBloc'.
 - 'BookmarkBloc' is from 'package:zalet_myay/blocs/bookmark_bloc.dart' ('lib/blocs/bookmark_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
          d.addAll(snap.docs.map((e) => Article.fromFirestore(e)).toList());
                                        ^^^^^^^
lib/blocs/bookmark_bloc.dart:103:41: Error: The getter 'Article' isn't defined for the class 'BookmarkBloc'.
 - 'BookmarkBloc' is from 'package:zalet_myay/blocs/bookmark_bloc.dart' ('lib/blocs/bookmark_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
          d.addAll(snap.docs.map((e) => Article.fromFirestore(e)).toList());
                                        ^^^^^^^
lib/blocs/bookmark_bloc.dart:110:41: Error: The getter 'Article' isn't defined for the class 'BookmarkBloc'.
 - 'BookmarkBloc' is from 'package:zalet_myay/blocs/bookmark_bloc.dart' ('lib/blocs/bookmark_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
          d.addAll(snap.docs.map((e) => Article.fromFirestore(e)).toList());
                                        ^^^^^^^
lib/blocs/bookmark_bloc.dart:118:41: Error: The getter 'Article' isn't defined for the class 'BookmarkBloc'.
 - 'BookmarkBloc' is from 'package:zalet_myay/blocs/bookmark_bloc.dart' ('lib/blocs/bookmark_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
          d.addAll(snap.docs.map((e) => Article.fromFirestore(e)).toList());
                                        ^^^^^^^
lib/blocs/category_tab1_bloc.dart:8:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/category_tab1_bloc.dart:52:34: Error: The getter 'Article' isn't defined for the class 'CategoryTab1Bloc'.
 - 'CategoryTab1Bloc' is from 'package:zalet_myay/blocs/category_tab1_bloc.dart' ('lib/blocs/category_tab1_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
        _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                                 ^^^^^^^
lib/blocs/category_tab2_bloc.dart:8:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/category_tab2_bloc.dart:52:34: Error: The getter 'Article' isn't defined for the class 'CategoryTab2Bloc'.
 - 'CategoryTab2Bloc' is from 'package:zalet_myay/blocs/category_tab2_bloc.dart' ('lib/blocs/category_tab2_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
        _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                                 ^^^^^^^
lib/blocs/category_tab3_bloc.dart:8:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/category_tab3_bloc.dart:52:34: Error: The getter 'Article' isn't defined for the class 'CategoryTab3Bloc'.
 - 'CategoryTab3Bloc' is from 'package:zalet_myay/blocs/category_tab3_bloc.dart' ('lib/blocs/category_tab3_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
        _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                                 ^^^^^^^
lib/blocs/category_tab4_bloc.dart:8:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/category_tab4_bloc.dart:52:34: Error: The getter 'Article' isn't defined for the class 'CategoryTab4Bloc'.
 - 'CategoryTab4Bloc' is from 'package:zalet_myay/blocs/category_tab4_bloc.dart' ('lib/blocs/category_tab4_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
        _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                                 ^^^^^^^
lib/blocs/comments_bloc.dart:83:9: Error: The method 'openToast1' isn't defined for the class 'CommentsBloc'.
 - 'CommentsBloc' is from 'package:zalet_myay/blocs/comments_bloc.dart' ('lib/blocs/comments_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'openToast1'.
        openToast1(context, 'You have flagged this comment already');
        ^^^^^^^^^^
lib/blocs/featured_bloc.dart:9:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/featured_bloc.dart:44:32: Error: The getter 'Article' isn't defined for the class 'FeaturedBloc'.
 - 'FeaturedBloc' is from 'package:zalet_myay/blocs/featured_bloc.dart' ('lib/blocs/featured_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
      _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                               ^^^^^^^
lib/blocs/featured_bloc.dart:45:29: Error: The getter 'timestamp' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'timestamp'.
      _data.sort((a,b) => b.timestamp!.compareTo(a.timestamp!));
                            ^^^^^^^^^
lib/blocs/featured_bloc.dart:45:52: Error: The getter 'timestamp' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'timestamp'.
      _data.sort((a,b) => b.timestamp!.compareTo(a.timestamp!));
                                                   ^^^^^^^^^
lib/blocs/notification_bloc.dart:123:7: Error: The method 'nextScreen' isn't defined for the class 'NotificationBloc'.
 - 'NotificationBloc' is from 'package:zalet_myay/blocs/notification_bloc.dart' ('lib/blocs/notification_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'nextScreen'.
      nextScreen(context, NotificationsPage());
      ^^^^^^^^^^
lib/blocs/notification_bloc.dart:123:27: Error: The method 'NotificationsPage' isn't defined for the class 'NotificationBloc'.
 - 'NotificationBloc' is from 'package:zalet_myay/blocs/notification_bloc.dart' ('lib/blocs/notification_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'NotificationsPage'.
      nextScreen(context, NotificationsPage());
                          ^^^^^^^^^^^^^^^^^
lib/blocs/notification_bloc.dart:133:7: Error: The method 'nextScreen' isn't defined for the class 'NotificationBloc'.
 - 'NotificationBloc' is from 'package:zalet_myay/blocs/notification_bloc.dart' ('lib/blocs/notification_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'nextScreen'.
      nextScreen(context, NotificationsPage());
      ^^^^^^^^^^
lib/blocs/notification_bloc.dart:133:27: Error: The method 'NotificationsPage' isn't defined for the class 'NotificationBloc'.
 - 'NotificationBloc' is from 'package:zalet_myay/blocs/notification_bloc.dart' ('lib/blocs/notification_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'NotificationsPage'.
      nextScreen(context, NotificationsPage());
                          ^^^^^^^^^^^^^^^^^
lib/blocs/notification_bloc.dart:148:29: Error: The getter 'Constants' isn't defined for the class 'NotificationBloc'.
 - 'NotificationBloc' is from 'package:zalet_myay/blocs/notification_bloc.dart' ('lib/blocs/notification_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Constants'.
      _fcm.subscribeToTopic(Constants.fcmSubscriptionTopic);
                            ^^^^^^^^^
lib/blocs/notification_bloc.dart:154:33: Error: The getter 'Constants' isn't defined for the class 'NotificationBloc'.
 - 'NotificationBloc' is from 'package:zalet_myay/blocs/notification_bloc.dart' ('lib/blocs/notification_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Constants'.
      _fcm.unsubscribeFromTopic(Constants.fcmSubscriptionTopic);
                                ^^^^^^^^^
lib/blocs/notification_bloc.dart:210:17: Error: The method 'nextScreen' isn't defined for the class 'NotificationBloc'.
 - 'NotificationBloc' is from 'package:zalet_myay/blocs/notification_bloc.dart' ('lib/blocs/notification_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'nextScreen'.
                nextScreen(context, NotificationsPage());
                ^^^^^^^^^^
lib/blocs/notification_bloc.dart:210:37: Error: The method 'NotificationsPage' isn't defined for the class 'NotificationBloc'.
 - 'NotificationBloc' is from 'package:zalet_myay/blocs/notification_bloc.dart' ('lib/blocs/notification_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'NotificationsPage'.
                nextScreen(context, NotificationsPage());
                                    ^^^^^^^^^^^^^^^^^
lib/blocs/popular_articles_bloc.dart:8:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/popular_articles_bloc.dart:24:32: Error: The getter 'Article' isn't defined for the class 'PopularBloc'.
 - 'PopularBloc' is from 'package:zalet_myay/blocs/popular_articles_bloc.dart' ('lib/blocs/popular_articles_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
      _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                               ^^^^^^^
lib/blocs/recent_articles_bloc.dart:8:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/recent_articles_bloc.dart:47:34: Error: The getter 'Article' isn't defined for the class 'RecentBloc'.
 - 'RecentBloc' is from 'package:zalet_myay/blocs/recent_articles_bloc.dart' ('lib/blocs/recent_articles_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
        _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                                 ^^^^^^^
lib/blocs/related_articles_bloc.dart:8:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/related_articles_bloc.dart:27:32: Error: The getter 'Article' isn't defined for the class 'RelatedBloc'.
 - 'RelatedBloc' is from 'package:zalet_myay/blocs/related_articles_bloc.dart' ('lib/blocs/related_articles_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
      _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                               ^^^^^^^
lib/blocs/search_bloc.dart:61:10: Error: 'Article' isn't a type.
    List<Article> data = [];
         ^^^^^^^
lib/blocs/search_bloc.dart:76:29: Error: The getter 'Article' isn't defined for the class 'SearchBloc'.
 - 'SearchBloc' is from 'package:zalet_myay/blocs/search_bloc.dart' ('lib/blocs/search_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
    data = _snap.map((e) => Article.fromFirestore(e)).toList();
                            ^^^^^^^
lib/blocs/videos_bloc.dart:14:8: Error: 'Article' isn't a type.
  List<Article> _data = [];
       ^^^^^^^
lib/blocs/videos_bloc.dart:60:34: Error: The getter 'Article' isn't defined for the class 'VideosBloc'.
 - 'VideosBloc' is from 'package:zalet_myay/blocs/videos_bloc.dart' ('lib/blocs/videos_bloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Article'.
        _data = _snap.map((e) => Article.fromFirestore(e)).toList();
                                 ^^^^^^^
lib/utils/next_screen.dart:38:29: Error: Method not found: 'VideoArticleDetails'.
      builder: (context) => VideoArticleDetails(data: article)),
                            ^^^^^^^^^^^^^^^^^^^
lib/utils/next_screen.dart:43:29: Error: Method not found: 'ArticleDetails'.
      builder: (context) => ArticleDetails(data: article, tag: heroTag,)),
                            ^^^^^^^^^^^^^^
lib/utils/next_screen.dart:55:31: Error: Method not found: 'VideoArticleDetails'.
        builder: (context) => VideoArticleDetails(data: article)),
                              ^^^^^^^^^^^^^^^^^^^
lib/utils/next_screen.dart:60:31: Error: Method not found: 'ArticleDetails'.
        builder: (context) => ArticleDetails(data: article, tag: heroTag,)),
                              ^^^^^^^^^^^^^^
lib/pages/home.dart:51:32: Error: 'AdsBloc' isn't a type.
      final adb = context.read<AdsBloc>();
                               ^^^^^^^
lib/pages/home.dart:52:26: Error: 'NotificationBloc' isn't a type.
      await context.read<NotificationBloc>().initFirebasePushNotification(context)
                         ^^^^^^^^^^^^^^^^
lib/pages/home.dart:53:37: Error: 'NotificationBloc' isn't a type.
      .then((value) => context.read<NotificationBloc>().handleNotificationlength())
                                    ^^^^^^^^^^^^^^^^
lib/pages/home.dart:97:13: Error: The method 'Explore' isn't defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:zalet_myay/pages/home.dart' ('lib/pages/home.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Explore'.
            Explore(),
            ^^^^^^^
lib/pages/home.dart:98:13: Error: The method 'VideoArticles' isn't defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:zalet_myay/pages/home.dart' ('lib/pages/home.dart').
Try correcting the name to the name of an existing method, or defining a method named 'VideoArticles'.
            VideoArticles(),
            ^^^^^^^^^^^^^
lib/pages/home.dart:99:13: Error: The method 'Categories' isn't defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:zalet_myay/pages/home.dart' ('lib/pages/home.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Categories'.
            Categories(),
            ^^^^^^^^^^
lib/pages/home.dart:100:13: Error: The method 'ProfilePage' isn't defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:zalet_myay/pages/home.dart' ('lib/pages/home.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ProfilePage'.
            ProfilePage()
            ^^^^^^^^^^^
lib/services/app_service.dart:35:7: Error: The method 'openToast1' isn't defined for the class 'AppService'.
 - 'AppService' is from 'package:zalet_myay/services/app_service.dart' ('lib/services/app_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'openToast1'.
      openToast1(context, "Can't launch the url");
      ^^^^^^^^^^
lib/services/app_service.dart:45:13: Error: The method 'Config' isn't defined for the class 'AppService'.
 - 'AppService' is from 'package:zalet_myay/services/app_service.dart' ('lib/services/app_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Config'.
      path: Config().supportEmail,
            ^^^^^^
lib/services/app_service.dart:46:31: Error: The method 'Config' isn't defined for the class 'AppService'.
 - 'AppService' is from 'package:zalet_myay/services/app_service.dart' ('lib/services/app_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Config'.
      query: 'subject=About ${Config().appName}&body=', //add subject and body here
                              ^^^^^^
lib/services/app_service.dart:53:7: Error: The method 'openToast1' isn't defined for the class 'AppService'.
 - 'AppService' is from 'package:zalet_myay/services/app_service.dart' ('lib/services/app_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'openToast1'.
      openToast1(context, "Can't open the email app");
      ^^^^^^^^^^
lib/services/app_service.dart:65:35: Error: 'ThemeBloc' isn't a type.
        colorScheme: context.read<ThemeBloc>().darkTheme! ? CustomTabsColorScheme.dark : CustomTabsColorScheme.light,
                                  ^^^^^^^^^
lib/services/app_service.dart:78:7: Error: The method 'openToast1' isn't defined for the class 'AppService'.
 - 'AppService' is from 'package:zalet_myay/services/app_service.dart' ('lib/services/app_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'openToast1'.
      openToast1(context, 'Cant launch the url');
      ^^^^^^^^^^
lib/services/app_service.dart:86:11: Error: 'SignInBloc' isn't a type.
    final SignInBloc sb = Provider.of<SignInBloc>(context, listen: false);
          ^^^^^^^^^^
lib/services/app_service.dart:86:39: Error: 'SignInBloc' isn't a type.
    final SignInBloc sb = Provider.of<SignInBloc>(context, listen: false);
                                      ^^^^^^^^^^
lib/services/app_service.dart:89:19: Error: The method 'Config' isn't defined for the class 'AppService'.
 - 'AppService' is from 'package:zalet_myay/services/app_service.dart' ('lib/services/app_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Config'.
        iOSAppId: Config().iOSAppId,
                  ^^^^^^
lib/services/app_service.dart:92:11: Error: The method 'Config' isn't defined for the class 'AppService'.
 - 'AppService' is from 'package:zalet_myay/services/app_service.dart' ('lib/services/app_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Config'.
      if (Config().iOSAppId == '000000') {
          ^^^^^^
lib/services/app_service.dart:93:9: Error: The method 'openToast1' isn't defined for the class 'AppService'.
 - 'AppService' is from 'package:zalet_myay/services/app_service.dart' ('lib/services/app_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'openToast1'.
        openToast1(context, 'The iOS version is not available on the AppStore yet');
        ^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Anews_app%2Fpages%2Fwelcome.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:623:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:763:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:586:9)
<asynchronous suspension>
#4      starter (package:flutter_frontend_server/server.dart:85:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>



FAILURE: Build failed with an exception.

* Where:
Script '/Users/Admin/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/Admin/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Exception: Gradle task assembleDebug failed with exit code 1
```
</details>

**Comment by maheshmnj** [comment]
Hi @AhlemKhng, Thanks for filing the issue. When you run `flutter pub get` does it complete successfully 
with `exit code 0`? Also, the error seems to point to issues in your code.

**Comment by AhlemKhng** [comment]
> Yes, it completed successfully with exit code 0. It kept showing errors when i run it on device..

**Comment by maheshmnj** [comment]
Does your IDE show any errors? The error logs seems to point issues in your code which makes me think that this isn't an issue with flutter.

e.g this error

> lib/blocs/article_notification_bloc.dart:4:8: Error: Not found: 'package:news_app/models/article.dart'
import 'package:news_app/models/article.dart';

Can you ensure that you have this `article.dart` with the `Article` class in it?

**Comment by Splokhande** [comment]
I guess it is because of the wrong package name defined in pubspec.yaml. 
Can you check the name of the package in pubspec.yaml (top Line) file. 
is it 'news_app'?
if it is not 'news_app', try changing it back to news_app or replace 'news_app' with the defined name in the complete project. 
run flutter pub get command.
