### ISSUE TITLE
[tool_crash] ProcessException: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail. Command: C:\Users\vigole\AppData\Local\Google\Chrome\Application\chrome.exe, OS error code: 14001

### ISSUE THREAD

**Issue by vishalgole** [flutter/flutter#100747]
## Command
```
flutter run -d chrome --web-renderer html --no-sound-null-safety
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
 Command: C:\Users\vigole\AppData\Local\Google\Chrome\Application\chrome.exe, OS error code: 14001
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:256:53)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:221:36)
<asynchronous suspension>
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:17)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19043.1586], locale en-US)
    • Flutter version 2.10.3 at C:\Users\vigole\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\vigole\AppData\Local\Android\Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools

**Comment by danagbemava-nc** [comment]
Hi @vishalgole, can you take a look at this thread to see if it helps you resolve your issue? https://www.majorgeeks.com/content/page/solved_the_application_has_failed_to_start_because_its_side_by_side_configuration_is_incorrect_error.html
