### ISSUE TITLE
Flutter Web Error with Text foreground Paint by html renderer

### ISSUE THREAD

**Issue by CarGuo** [flutter/flutter#100877]
When I add `LinearGradient` to  `foreground` with `Text` ， it occur error in `createPaintStyle`.

```dart
Container(
  child: Text(
    '8',
    style: TextStyle(
        fontSize: 100,
        foreground: Paint()
          ..style = PaintingStyle.stroke
          ..strokeWidth = 2
          ..shader = LinearGradient(
                  begin: Alignment.bottomLeft,
                  end: Alignment.topRight,
                  colors: [Colors.limeAccent, Colors.cyanAccent])
              .createShader(Rect.fromLTWH(0, 0, 200, 100))),
  ),
),
```

I found that `shader ` will take  `Text` render into `canvas` with html renderer ,  but  `_applySpanStyleToCanvas`  will call `canvas.setUpPaint(paint.paintData, null)` with null shaderBounds,  **so `shaderBounds!` will thrown error in `_createCanvasGradient`**.

## Steps to Reproduce

like  the code above, when `flutter run -d chrome --web-renderer html`  will thrown `Unexpected null value`.

**Expected results:** 

Workaround in Mobile 

![image](https://user-images.githubusercontent.com/10770362/160316351-174a1676-3628-4f37-b0df-88964517f8b9.png)

**Actual results:** 

thrown `Unexpected null value` , If I add `fontFeatures` or `decoration`  could  be avoided this error , because  Text will render into `p+span` tag ，but  `foreground`  will not be able like below :

![](https://user-images.githubusercontent.com/10770362/160316562-c22afa01-2b72-4bbf-8db3-f1a78a08e382.png)

<details>
<summary>Code sample</summary>

```dart
Container(
  child: Text(
    '8',
    style: TextStyle(
        fontSize: 100,
        foreground: Paint()
          ..style = PaintingStyle.stroke
          ..strokeWidth = 2
          ..shader = LinearGradient(
                  begin: Alignment.bottomLeft,
                  end: Alignment.topRight,
                  colors: [Colors.limeAccent, Colors.cyanAccent])
              .createShader(Rect.fromLTWH(0, 0, 200, 100))),
  ),
),
```

</details>

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
js_primitives.dart:30 The following TypeErrorImpl was thrown during a scheduler callback:
js_primitives.dart:30 Unexpected null value.
js_primitives.dart:30 
js_primitives.dart:30 When the exception was thrown, this was the stack:
js_primitives.dart:30 dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
js_primitives.dart:30 dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
js_primitives.dart:30 lib/_engine/engine/html/shaders/shader.dart 179:42                                [_createCanvasGradient]
js_primitives.dart:30 lib/_engine/engine/html/shaders/shader.dart 169:14                                createPaintStyle
js_primitives.dart:30 lib/_engine/engine/canvas_pool.dart 956:25                                        setUpPaint
js_primitives.dart:30 lib/_engine/engine/html/bitmap_canvas.dart 249:31                                 setUpPaint
js_primitives.dart:30 lib/_engine/engine/text/paint_service.dart 139:11                                 [_applySpanStyleToCanvas]
js_primitives.dart:30 lib/_engine/engine/text/paint_service.dart 88:7                                   [_paintText]
js_primitives.dart:30 lib/_engine/engine/text/paint_service.dart 44:9                                   paint
js_primitives.dart:30 lib/_engine/engine/text/canvas_paragraph.dart 118:19                              paint
js_primitives.dart:30 lib/_engine/engine/html/bitmap_canvas.dart 929:16                                 drawParagraph
js_primitives.dart:30 lib/_engine/engine/html/recording_canvas.dart 1233:11                             apply
js_primitives.dart:30 lib/_engine/engine/html/recording_canvas.dart 190:20                              applyCommands
js_primitives.dart:30 lib/_engine/engine/html/recording_canvas.dart 132:5                               apply
js_primitives.dart:30 lib/_engine/engine/html/picture.dart 464:19                                       <fn>
js_primitives.dart:30 lib/_engine/engine/html/surface.dart 51:16                                        commitScene
js_primitives.dart:30 lib/_engine/engine/html/scene_builder.dart 542:7                                  <fn>
js_primitives.dart:30 lib/_engine/engine/profiler.dart 34:18                                            timeAction
js_primitives.dart:30 lib/_engine/engine/html/scene_builder.dart 536:12                                 build
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart 942:35                                  buildScene
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
```

</details>

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master` only with the `html` renderer. 

<details>
<summary>screenshots</summary>

| without shader | with shader | canvaskit |
| -- | -- | -- |
| <img width="612" alt="Screenshot 2022-03-28 at 11 26 54" src="https://user-images.githubusercontent.com/88313112/160388339-68538df8-b7fb-4008-b12f-1db873901db5.png"> | <img width="612" alt="Screenshot 2022-03-28 at 11 27 11" src="https://user-images.githubusercontent.com/88313112/160388382-f590dd64-94ca-4740-b42d-eda232f00722.png"> | <img width="612" alt="Screenshot 2022-03-28 at 12 04 18" src="https://user-images.githubusercontent.com/88313112/160394039-8b0a7ce5-dc3b-4c62-8194-1960dc77f0ff.png"> | 


</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TestEditableText(),
    );
  }
}

class TestEditableText extends StatefulWidget {
  const TestEditableText({Key? key}) : super(key: key);

  @override
  _TestEditableTextState createState() => _TestEditableTextState();
}

class _TestEditableTextState extends State<TestEditableText> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          '8',
          style: TextStyle(
            fontSize: 100,
            foreground: Paint()
              ..style = PaintingStyle.stroke
              ..strokeWidth = 2
              ..shader = const LinearGradient(
                      begin: Alignment.bottomLeft,
                      end: Alignment.topRight,
                      colors: [Colors.limeAccent, Colors.cyanAccent])
                  .createShader(const Rect.fromLTWH(0, 0, 200, 100)),
          ),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>logs</summary>

```console
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             11.5s
DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
This app is linked to the debug service: ws://127.0.0.1:63405/tHanL0pZQ3A=/ws
Debug service listening on ws://127.0.0.1:63405/tHanL0pZQ3A=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:63405/tHanL0pZQ3A=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:63405/tHanL0pZQ3A=

DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
Performing hot restart...                                        1,061ms
Restarted application in 1,069ms.

DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
Performing hot restart...                                        1,304ms
Restarted application in 1,307ms.
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown during a scheduler callback:
Unexpected null value.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
lib/_engine/engine/html/shaders/shader.dart 177:42                                [_createCanvasGradient]
lib/_engine/engine/html/shaders/shader.dart 167:14                                createPaintStyle
lib/_engine/engine/canvas_pool.dart 956:25                                        setUpPaint
lib/_engine/engine/html/bitmap_canvas.dart 249:31                                 setUpPaint
lib/_engine/engine/text/paint_service.dart 123:11                                 [_applySpanStyleToCanvas]
lib/_engine/engine/text/paint_service.dart 72:7                                   [_paintText]
lib/_engine/engine/text/paint_service.dart 39:9                                   paint
lib/_engine/engine/text/canvas_paragraph.dart 119:19                              paint
lib/_engine/engine/html/bitmap_canvas.dart 929:16                                 drawParagraph
lib/_engine/engine/html/recording_canvas.dart 1233:11                             apply
lib/_engine/engine/html/recording_canvas.dart 176:24                              applyCommands
lib/_engine/engine/html/recording_canvas.dart 132:5                               apply
lib/_engine/engine/html/picture.dart 464:19                                       <fn>
lib/_engine/engine/html/surface.dart 51:16                                        commitScene
lib/_engine/engine/html/scene_builder.dart 542:7                                  <fn>
lib/_engine/engine/profiler.dart 34:18                                            timeAction
lib/_engine/engine/html/scene_builder.dart 536:12                                 build
packages/flutter/src/rendering/layer.dart 943:35                                  buildScene
packages/flutter/src/rendering/view.dart 228:30                                   compositeFrame
packages/flutter/src/rendering/binding.dart 505:18                                drawFrame
packages/flutter/src/widgets/binding.dart 883:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 367:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1145:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1082:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 863:7                                 <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19           internalCallback
════════════════════════════════════════════════════════════════════════════════════════════════════
ENGINE LAYER TREE INCONSISTENT:
  - PersistedPicture has non-trivial picture but it has null canvas
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.278, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.278 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 654aaa8eb2 (6 hours ago), 2022-03-28 01:50:09 -0400
    • Engine revision b41870954b
    • Dart version 2.17.0 (build 2.17.0-246.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
