### ISSUE TITLE
ImagePickerPlugin has StrictMode violations for disk read/write on the main thread

### ISSUE THREAD

**Issue by math1man** [flutter/flutter#100966]
Plugins should not perform disk I/O during app startup, as this can lead to jank and bad performance.

```
03-29 04:51:07.460  2877  2877 D StrictMode: StrictMode policy violation; ~duration=315 ms: android.os.strictmode.DiskReadViolation
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:71)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7533)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at java.io.File.exists(File.java:815)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.ContextImpl.getDataDir(ContextImpl.java:2539)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:626)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:853)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:475)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at io.flutter.plugins.imagepicker.ImagePickerCache.<init>(ImagePickerCache.java:53)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.constructDelegate(ImagePickerPlugin.java:282)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at io.flutter.plugins.imagepicker.ImagePickerPlugin$ActivityState.<init>(ImagePickerPlugin.java:120)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.setup(ImagePickerPlugin.java:269)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onAttachedToActivity(ImagePickerPlugin.java:240)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivityInternal(FlutterEngineConnectionRegistry.java:345)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:324)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at internal.elided.FooFlutterFragment.onCreate()
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.support.v4.app.Fragment.performCreate(Fragment.java:2981)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.support.v4.app.FragmentStateManager.create(FragmentStateManager.java:474)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.support.v4.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.support.v4.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.support.v4.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.support.v4.app.FragmentManager.execSingleAction(FragmentManager.java:1670)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.support.v4.app.BackStackRecord.commitNow(BackStackRecord.java:317)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at internal.elided.FooActivity.onStart()
03-29 04:51:07.460  2877  2877 D StrictMode: 	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:39)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at com.google.apps.tiktok.inject.baseclasses.TracedActivityLifecycleRegistry.handleLifecycleEvent(TracedActivityLifecycleRegistry.java:27)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1362)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.Activity.performStart(Activity.java:8055)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.os.Looper.loop(Looper.java:223)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-29 04:51:07.460  2877  2877 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by darshankawar** [comment]
@math1man 
Thanks for the report. Can you provide a minimal reproducible code sample that triggers this log ?

**Comment by math1man** [comment]
Sure: https://github.com/math1man/plugins/tree/master/packages/image_picker/image_picker/example

**Comment by darshankawar** [comment]
@math1man 
Thanks for the repo. I ran it on Android but didn't get the said log. Are there any specific steps that triggers it ?

**Comment by darshankawar** [comment]
Thanks for the update. Following the steps to replicate on Android device (S10) I do get same log as reported.

`android.os.strictmode.DiskReadViolation` probably indicates a network or disk access on main thread. This probably can be enabled using below:

```
public void onCreate() {
     StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
             .detectDiskReads()
             .detectDiskWrites()
             .detectNetwork()   // or .detectAll() for all detectable problems
             .penaltyLog()
             .build());
     StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
             .detectLeakedSqlLiteObjects()
             .detectLeakedClosableObjects()
             .penaltyLog()
             .penaltyDeath()
             .build());
     super.onCreate();
 }
```

More info here: https://developer.android.com/reference/android/os/StrictMode

I'll keep it open for further insights from the team on this log related to 1P plugin.


<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.329, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.329 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c6918933e (77 minutes ago), 2022-03-30 20:30:09 -0700
    • Engine revision a1106daced
    • Dart version 2.17.0 (build 2.17.0-249.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by math1man** [comment]
Yep, that's roughly what I had implemented in my repro.

**Comment by stuartmorgan** [comment]
/cc @blasten 

We should ideally move the cache to a different thread, but as a short-term fix we could presumably just make getting the shared preferences lazy.
