### ISSUE TITLE
SelectableText / WidgetSpan: Null check operator used on a null value

### ISSUE THREAD

**Issue by everskies** [flutter/flutter#100915]
There seems to be an issue with SelectableText when using WidgetSpans mixed with TextSpans. This only seems to occur when trying to select text that contains a new line (\n) that pushes a WidgetSpan below itself.

![image](https://user-images.githubusercontent.com/17406493/160466999-6a6b0a3a-b273-40c3-a202-eb365d4b11ae.png)

## Steps to Reproduce

1. Execute `flutter run` on the code sample (Android / IOS only)
2. Attempt to select/Long press the empty square (above "hey!", marked with X on the screenshot)
3. Observe a "Null check operator used on a null value" error in the console

**Expected results:**
No exception should be thrown.

**Actual results:**
An exception is thrown

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: SelectableText.rich(
            TextSpan(children: [
              WidgetSpan(
                child: Container(
                  width: 100,
                  height: 100,
                  color: Colors.red,
                ),
              ),
              TextSpan(text: 'HEY!\n'),
              WidgetSpan(
                  child: Container(
                width: 100,
                height: 100,
                color: Colors.red,
              )),
              WidgetSpan(
                child: Container(
                  width: 100,
                  height: 100,
                  color: Colors.red,
                ),
              ),
            ]),
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      RenderEditable._onlyWhitespace (package:flutter/src/rendering/editable.dart:1549:47)
#1      RenderEditable._getPreviousWord (package:flutter/src/rendering/editable.dart:1534:12)
#2      RenderEditable._getWordAtOffset (package:flutter/src/rendering/editable.dart:2046:39)
#3      RenderEditable.selectWordsInRange (package:flutter/src/rendering/editable.dart:1995:37)
#4      _SelectableTextSelectionGestureDetectorBuilder.onSingleLongTapMoveUpdate (package:flutter/src/material/selectable_text.dart:74:22)
#5      _TextSelectionGestureDetectorState._handleLongPressMoveUpdate (package:flutter/src/widgets/text_selection.dart:1584:40)
#6      LongPressGestureRecognizer._checkLongPressMoveUpdate.<anonymous closure> (package:flutter/src/gestures/long_press.dart:756:85)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#8      LongPressGestureRecognizer._checkLongPressMoveUpdate (package:flutter/src/gestures/long_press.dart:756:11)
#9      LongPressGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/long_press.dart:652:9)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#26     _invoke1 (dart:ui/hooks.dart:170:10)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onLongPressMoveUpdate"
Recognizer: LongPressGestureRecognizer#ad1d6
  debugOwner: _TextSelectionGestureDetectorState#21f7c
  state: possible
====================================================================================================
```

```
[✓] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-GB)
    • Flutter version 2.10.4 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
```

</details>

**Comment by darshankawar** [comment]
@everskies 
Thanks for the report. Although I see the exception on latest stable, but not on latest master which brings me to this similar issue that was fixed: https://github.com/flutter/flutter/issues/79166

I was unable to replicate the error on latest master. Can you try the same at your end ?

`Channel master, 2.13.0-0.0.pre.296`


```
flutter channel master
flutter upgrade
```

/cc @chunhtai. Since the linked issue seem to have been last year, the error still occurs on latest stable but not on master. Wondering if the fix ever made it to stable ?

**Comment by everskies** [comment]
@darshankawar Can confirm that this does not happen on the master channel! 
Could this be cherry picked into stable, or is it too much of a change to allow for that? This is the top reported bug currently

**Comment by darshankawar** [comment]
Thanks for the update. Since this works on master, I will close it as fixed. I am not the correct person to answer whether this can be cherry-picked or not. I'll let the team decide on it. For now, please use master. I'll try to raise this to the team for their take on it.
