### ISSUE TITLE
TextFormField focus bug

### ISSUE THREAD

**Issue by martin-labanic** [flutter/flutter#101067]
Encountered what appears to be a focus bug on iOS devices where a TextFormField will stop responding.

## Steps to Reproduce

1. Execute `flutter run` on the [example project](https://github.com/martin-labanic/flutter_focus_bug) targetting a iOS device (simulator will NOT work).
2. Once loaded, start tapping in various places in the text field.
3. Keep tapping until the keyboard is no longer showing and the textfield cannot be interacted with.

**Expected results:** A text field that retains focus and can be interacted with.

**Actual results:** A text field that has lost focus and can no longer be interacted with in any capacity.

<details>
<summary>Sample Code</summary>

https://github.com/martin-labanic/flutter_focus_bug

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _form_key = GlobalKey<FormState>();

  void unfocusWidgets(BuildContext context) {
    FocusScope.of(context).unfocus();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: const Text('Focus Bug'),
      ),

      body: Listener( // Used to dismiss the keyboard if the user taps elsewhere on the screen.
        onPointerDown: (event) {
          unfocusWidgets(context);
        },
        child: SafeArea(
          child: SizedBox.expand(
            child: Container(
              color: Colors.white,
              padding: const EdgeInsets.all(10.0),
              child: Align(
                alignment: Alignment.topCenter,
                child: Form(
                  key: _form_key,
                  child: TextFormField(
                    initialValue: 'On iOS, tap this text field in various places. Eventually the keyboard will no longer show up and interacting with this widget will not work.',
                    keyboardType: TextInputType.text,
                    autofocus: false,
                    maxLines: 3,
                    onChanged: (value) { },
                  ),
                ),
              )
            )
          ),
        ),
      ),
    );
  }
}
```

</details>

## Logs

<details>
<summary>flutter run --verbose</summary>

[flutter_run_verbose.log](https://github.com/flutter/flutter/files/8383151/flutter_run_verbose.log)

</details>

<details>
<summary>flutter analyze</summary>

```
Analyzing focus_bug...                                                  

   info • Name non-constant identifiers using lowerCamelCase • lib/main.dart:51:9 • non_constant_identifier_names

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale en-CA)
    • Flutter version 2.10.4 at /Users/tt/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (6 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tt/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Mike’s iPad (mobile) • cba0debb2f88ef7bd67604d84601a01da040dfd0 • ios            • iOS 15.3.1 19D52
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by darshankawar** [comment]
@martin-labanic 
I tried the same on iPhone 6s (OS 15.3.1) using latest master version and didn't experience the behavior you reported.


https://user-images.githubusercontent.com/67046386/161007043-83f64a42-9f15-4226-a607-a46e286aa9a4.MP4


`Channel master, 2.13.0-0.0.pre.329`

**Comment by darshankawar** [comment]
Thanks for the update. This seem to be specific to iPads, as I was able to replicate this on iPad simulator (6th gen), as below:


https://user-images.githubusercontent.com/67046386/161204821-02da5286-3bb6-4763-b891-794f8cc61a92.mov



The same works properly on iOS simulator and on physical iOS device per my earlier comment and verification.


https://user-images.githubusercontent.com/67046386/161204859-62f9548d-ca75-48ca-b8e6-c51627649ced.mov

Tapping on the textfield and after couple of attempts, the keyboard doesn't show up. This behavior occurs on both, latest stable and master.

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.329, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.329 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c6918933e (77 minutes ago), 2022-03-30 20:30:09 -0700
    • Engine revision a1106daced
    • Dart version 2.17.0 (build 2.17.0-249.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

Maybe similar / related: https://github.com/flutter/flutter/issues/90238

**Comment by RaviAalphonic** [comment]
> [`_******nnmm**_`](

- [ ] @ #url

)

**Comment by zhongwuzw** [comment]
@fbcouch Can you help to have a check? seems it's related to scribble handwriting.

**Comment by fbcouch** [comment]
Is this still happening in 3.0? I just tried it and wasn't able to reproduce it, but if others are able to reproduce it in 3.0, I can look more. My suspicion would be that it might have something to do with the engine parts of scribble making it into 2.10, but the framework parts not making it till 3.0 (I think).

**Comment by zhongwuzw** [comment]
@fbcouch Yes, I can also reproduce on master branch iPad simulator. The issue fixed if I commented out these lines https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L2114-L2119.

**Comment by samumzizi** [comment]
This issues still exists 18 months later and I'm afraid much worse that just the textfield no longer being responsive.
In fact, all other widgets on the same screen become non-responsive.
In my use case, I am using scribble on a form in my ipad.

Once the issue begins:
- I can't add any more text to any of the text fields
- The UI gets distorted - For example my stationary form that's aligned Top Center, as I try scrolling vertically, suddenly becomes draggable and changes its alignment entirely
- The leading back icon in the app bar becomes unresponsive
- The floating action button for saving the form becomes unresponsive
- You're stuck on the same (form) screen until you relaunch the app

I've attached my flutter doctor for reference:

<img width="801" alt="image" src="https://github.com/flutter/flutter/assets/9431582/47995607-7a97-4332-a4b8-e4d00603e64c">

**Comment by subins829** [comment]
any updates related to this issue ?

**Comment by Mike-Benoit** [comment]
A fix for this would be wonderful. Its a nasty situation for users to get into and results in negative reviews.

**Comment by bryce-walton** [comment]
Could we please get an update on this issue and an estimated timeline for its resolution? This bug significantly impacts our operations, as all 100+ users of our app rely on iPads for their tasks. The recurring locking and unresponsiveness while filling out forms are causing substantial disruption.

It's concerning that such a critical bug affecting basic text inputs has remained unresolved for 2.5 years. Text input is a fundamental feature in any app, and it's difficult to understand how an issue that renders the app effectively unusable has persisted for this long. We appreciate your attention to this matter and look forward to a resolution soon.

**Comment by martin-labanic** [comment]
I had a app update rejected by apple due to this bug recently. Respectfully, at this point its been 3 years; an update on this bug's status, a work around, and or a fix would be greatly appreciated.

**Comment by dluksza** [comment]
I can confirm this reproduces on a current Flutter version and share some additional data points that narrow down the trigger conditions.

**Environment**
- Flutter 3.44.4 (stable), Dart 3.12.2
- iPad Simulator: `iPad Pro 13-inch (M5)`
- Xcode: `26.5`

**Symptom**

Tapping a plain `TextField`/`TextFormField` (no `autofocus`, standard `autofillHints`) does nothing on the first several taps; no cursor, no keyboard. After a few taps, the following is thrown:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building SystemContextMenu(dirty, dependencies: [MediaQuery,
_LocalizationsScope-[GlobalKey#13d69]], state: _SystemContextMenuState#21a37):
Currently, the system context menu can only be shown for an active text input connection
'package:flutter/src/services/text_input.dart':
Failed assertion: line 3020 pos 7: 'TextInput._instance._currentConnection != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=02_bug.yml

The relevant error-causing widget was:
  SystemContextMenu
  SystemContextMenu:file:///Users/darluk/workspace/post-office-app/lib/common/ui/widgets/input_fields/input_field.dart:199:30

When the exception was thrown, this was the stack:
#2      SystemContextMenuController.showWithItems (package:flutter/src/services/text_input.dart:3020:7)
#3      _SystemContextMenuState.build (package:flutter/src/widgets/system_context_menu.dart:220:36)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5931:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5817:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5799:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5973:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5793:5)
...     Normal element mounting (73 frames)
#83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4587:20)
#84     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7264:36)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:4059:18)
#86     Element.updateChildren (package:flutter/src/widgets/framework.dart:4255:32)
#87     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7295:17)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#90     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#92     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2750:15)
#93     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2807:11)
#94     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3111:18)
#95     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1571:21)
#96     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:509:5)
#97     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1430:15)
#98     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1345:9)
#99     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1198:5)
#100    _invoke (dart:ui/hooks.dart:423:13)
#101    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:447:5)
#102    _drawFrame (dart:ui/hooks.dart:395:31)
(elided 2 frames from class _AssertionError)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Currently, the system context menu can only be shown for an active text input connection
```

**Isolation testing we did**

| Configuration | Reproduces? |
|---|---|
| iPad Simulator, hardware keyboard connected | Yes |
| iPad Simulator, hardware keyboard disconnected | Yes |
| iPhone Simulator, hardware keyboard connected | No |
| Physical iPad (same app build) | No |

This rules out the hardware keyboard as a factor, it's specific to the iPad Simulator regardless of keyboard state, and does not reproduce on physical iPad hardware or on iPhone (simulator or device). A non-text widget (a checkbox) on the same screen remained responsive throughout, so it isn't a screen-wide input/hit-testing freeze, it's isolated to the text-input/focus subsystem specifically.

In our app, one particular form screen (four plain `TextField`s + a checkbox, no `autofocus`) reproduced this consistently across repeated attempts on iPad simulator, while other screens with similarly-configured `TextField`s did not reproduce it in the same session. We couldn't find any code difference between that screen and our other form screens that would explain a screen-specific trigger.

Happy to provide a full reproduction repo/log if useful.
