### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by modthier** [flutter/flutter#101053]
## Command
```
flutter test
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: Access is denied.
, errno = 5
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:946:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:786:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:691:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:246:53)
<asynchronous suspension>
#8      TestCommand._buildTestAsset (package:flutter_tools/src/commands/test.dart:475:23)
<asynchronous suspension>
#9      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:319:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19041.1], locale en-US)
    • Flutter version 2.5.3 at E:\programs\flutter windows\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at C:\Users\Muddathir\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 31.0.0-rc2
    • ANDROID_HOME = C:\Users\Muddathir\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-11.0.1\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.65.2)
    • VS Code at C:\Users\Muddathir\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b1395592de68cc8ac4522094ae59956dd21a91db

**Comment by danagbemava-nc** [comment]
Hi @modthier, you appear to be on an older version of flutter. Can you upgrade to the latest stable to see if you still experience this issue? 

Also, see https://github.com/flutter/flutter/issues/68810#issuecomment-714699148 for an explanation as to why this might happen.
