### ISSUE TITLE
DraggableScrollableSheet with BouncingScrollPhysics throw exception when closed too fast with scroll

### ISSUE THREAD

**Issue by SuperPenguin** [flutter/flutter#101061]
## Steps to Reproduce

1. Run code below
2. Press open
3. Drag the list up then drag it down really fast

**Expected results:** No exception

**Actual results:** Get exception when closed with scrolled down too fast, when scrolled slowly, it doesn't throw exception

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Demo'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            showModalBottomSheet(
              context: context,
              isScrollControlled: true,
              builder: (context) => const _DemoSheet(),
            );
          },
          child: const Text('Open'),
        ),
      ),
    );
  }
}

class _DemoSheet extends StatefulWidget {
  const _DemoSheet({Key? key}) : super(key: key);

  @override
  _DemoSheetState createState() => _DemoSheetState();
}

class _DemoSheetState extends State<_DemoSheet> {
  final _data = List.generate(
    100,
    (index) => Colors.primaries[index % Colors.primaries.length],
  );

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      initialChildSize: 0.5,
      minChildSize: 0.2,
      maxChildSize: 0.9,
      expand: false,
      builder: (context, scrollController) => ListView.separated(
        physics: const BouncingScrollPhysics(),
        controller: scrollController,
        separatorBuilder: (context, index) => const Divider(),
        itemCount: _data.length,
        itemBuilder: (context, index) => SizedBox(
          height: 100,
          child: ColoredBox(
            color: _data[index],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
FlutterError (ScrollableState#436e8(tickers: tracking 2 tickers, position: _DraggableScrollableSheetScrollPosition#462ec(offset: -119.2, range: -1.0..13063.7, viewport: 150.9, ScrollableState, BouncingScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, null, ScrollDirection.idle), effective physics: BouncingScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics) was disposed with an active Ticker.
ScrollableState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().
Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.
The offending ticker was:
  _WidgetTicker(created by ScrollableState#436e8)
  The stack trace when the _WidgetTicker was actually created was:
  #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
  #1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
  #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:385:81)
  #3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:295:34)
  #4      new AnimationController.unbounded (package:flutter/src/animation/animation_controller.dart:279:21)
  #5      _DraggableScrollableSheetScrollPosition.goBallistic (package:flutter/src/widgets/draggable_scrollable_sheet.dart:859:73)
  #6      BallisticScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:549:14)
  #7      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:623:15)
  #8      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:104:11)
  #9      ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:553:7)
  #10     _DraggableScrollableSheetScrollPosition.applyContentDimensions (package:flutter/src/widgets/draggable_scrollable_sheet.dart:794:18)
  #11     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1493:20)
  #12     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731:7)
  #13     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
  #14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
  #15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
  #16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
  #17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
  #18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
  #19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
  #23     _invoke (dart:ui/hooks.dart:151:10)
  #24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
  #25     _drawFrame (dart:ui/hooks.dart:115:31)
  (elided 3 frames from dart:async))
```

```
[✓] Flutter (Channel unknown, 2.10.4, on macOS 12.1 21C52 darwin-arm, locale en-ID)
    • Flutter version 2.10.4 at /Users/s21/Documents/GitHub/flutter/flutter
    • Upstream repository unknown
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/s21/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • E31DBB95-A1F1-4893-AF0C-48C839A6A434 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/1574722/160879510-322bfc7b-f503-4b1c-a6ee-b019942c977c.mov

**Comment by darshankawar** [comment]
Thanks for the report. I do see same behavior / exception running code sample on latest master and stable.

<details>
<summary> console error log </summary>

```

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
ScrollableState#c4bc3(tickers: tracking 2 tickers, position: _DraggableScrollableSheetScrollPosition#ec26b(offset: -251.2, range: -1.0..14143.6, viewport: 219.4, ScrollableState, BouncingScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, null, ScrollDirection.idle), effective physics: BouncingScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics) was disposed with an active Ticker.

ScrollableState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: _WidgetTicker(created by ScrollableState#c4bc3)
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
#2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:385:81)
#3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:295:34)
#4      new AnimationController.unbounded (package:flutter/src/animation/animation_controller.dart:279:21)
#5      _DraggableScrollableSheetScrollPosition.goBallistic (package:flutter/src/widgets/draggable_scrollable_sheet.dart:884:73)
#6      BallisticScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:549:14)
#7      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:623:15)
#8      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:104:11)
#9      ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:553:7)
#10     _DraggableScrollableSheetScrollPosition.applyContentDimensions (package:flutter/src/widgets/draggable_scrollable_sheet.dart:819:18)
#11     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1493:20)
#12     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#13     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:501:19)
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:367:5)
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#23     _invoke (dart:ui/hooks.dart:151:10)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#25     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

When the exception was thrown, this was the stack: 
#0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:342:13)
#1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:360:6)
#2      RestorationMixin.dispose (package:flutter/src/widgets/restoration.dart:983:11)
#3      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:516:11)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5014:11)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#13     _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:68:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#31     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#37     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#58     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#61     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#64     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#79     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#97     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#103    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#106    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#108    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#109    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#110    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#111    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#115    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#116    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#117    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#119    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#120    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#121    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#122    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#123    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#127    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#128    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#129    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#131    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#132    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#133    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#134    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#135    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#136    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#140    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#141    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#142    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#143    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#144    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#145    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#146    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#147    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#148    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#149    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#150    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#152    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#153    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#154    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6184:14)
#155    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#156    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#157    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#158    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#159    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#160    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#161    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#162    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1911:7)
#163    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4841:14)
#164    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1909:13)
#165    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#166    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1922:25)
#167    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2515:15)
#168    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2928:7)
#169    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#170    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:367:5)
#171    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#172    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#173    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#177    _invoke (dart:ui/hooks.dart:151:10)
#178    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#179    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

======== Exception caught by animation library =====================================================
The following _CastError was thrown while notifying listeners for AnimationController:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _DraggableScrollableSheetScrollPosition.goBallistic._tick (package:flutter/src/widgets/draggable_scrollable_sheet.dart:895:62)
#1      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:155:19)
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:830:5)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1058:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:975:5)
#12     _invoke1 (dart:ui/hooks.dart:170:10)
#13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:286:5)
#14     _beginFrame (dart:ui/hooks.dart:104:31)
(elided 3 frames from dart:async)
The AnimationController notifying listeners was: AnimationController#f839b(▶ 449.038; for _DraggableScrollableSheetScrollPosition)
====================================================================================================

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.329, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.329 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c6918933e (77 minutes ago), 2022-03-30 20:30:09 -0700
    • Engine revision a1106daced
    • Dart version 2.17.0 (build 2.17.0-249.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>
