### ISSUE TITLE
Different emoji fonts do not render correctly (no color)

### ISSUE THREAD

**Issue by ice-kylin** [flutter/flutter#101171]
## Steps to Reproduce

Different emoji fonts do not render correctly (no color).

This should be a problem as most of these fonts are rendered correctly in the browser, so it should also be rendered correctly in flutter. Sometimes I don't want to use the system default font, so this problem is very annoying.

**Expected results:** All the emoji fonts should render with color.

**Actual results:** Only Noto emoji render with color.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const <Widget>[
              Emj('💎🍨🍥', 'Seguiemj'),
              Emj('💎🍨🍥', 'Openmoji'),
              Emj('💎🍨🍥', 'Notoemj'),
              Emj('💎🍨🍥', null),
            ],
          ),
        ),
      ),
    );
  }
}

class Emj extends StatelessWidget {
  const Emj(this._text, this._fontFamily, {Key? key}) : super(key: key);

  final String _text;
  final String? _fontFamily;

  @override
  Widget build(BuildContext context) {
    return Text(
      _text,
      style: TextStyle(
        fontFamily: _fontFamily,
        fontSize: 64.0,
      ),
    );
  }
}
```

</details>

<img width="266" alt="image" src="https://user-images.githubusercontent.com/56141162/161220773-e5354b88-082c-4b4e-9b15-12d63edb6663.png">

As a comparison, you can see that the browser can correctly render fonts other than Openmoji.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/56141162/161221158-31e1603d-537c-4c82-9fda-83e32dfff50d.png">

**Comment by danagbemava-nc** [comment]
Hi @ice-kylin, thanks for filing the issue. 

Please provide the output of `flutter doctor -v`.

Thank you

**Comment by ice-kylin** [comment]
As follows:

![image](https://user-images.githubusercontent.com/56141162/161238867-2f469e86-0bd2-4410-9a62-b5a3fec981b9.png)

![image](https://user-images.githubusercontent.com/56141162/161238987-30ef8f10-0953-4ff8-b29d-4c555453f894.png)

**Comment by danagbemava-nc** [comment]
Hi @ice-kylin, I tested your code sample on `android`, `iOS`, `web`, and `macOS` and in all cases, the emojis are properly rendered. See screenshots below. Can you upgrade to stable 2.10.4 to see if you still experience this issue? 

For future reference, please copy and paste the output of `flutter doctor -v` rather than sending screenshots. Please also provide any logs in text format as screenshots are not searchable and can sometimes be difficult to see at a glance. 

<details>
<summary>screenshots</summary>

| ios | android | macOS | web | 
| -- | -- | -- | -- | 
| ![Simulator Screen Shot - iPhone 13 - 2022-04-01 at 10 46 44](https://user-images.githubusercontent.com/88313112/161250650-6e5a59a6-6b2a-4dda-bbb1-3fdaad85de75.png) | ![Screenshot_1648810165](https://user-images.githubusercontent.com/88313112/161250661-8d6336df-d93a-45a9-a8c7-023876458769.png) | <img width="558" alt="Screenshot 2022-04-01 at 10 51 35" src="https://user-images.githubusercontent.com/88313112/161250682-d7d32c77-8f26-45f4-af1d-256a147fe96e.png"> | <img width="650" alt="Screenshot 2022-04-01 at 10 52 34" src="https://user-images.githubusercontent.com/88313112/161250728-b91854fb-5f74-4086-a383-a88ba7020943.png"> |


</details>

**Comment by ice-kylin** [comment]
> 

There is no problem with your test because you did not add the corresponding font, so flutter use default noto font.

If you can use other emoji font, you need to add them to `pubspec.yaml` and test again.

```dart
  fonts:
    - family: Notoemj
      fonts:
        - asset: fonts/NotoColorEmoji.ttf
          weight: 400
    - family: Seguiemj
      fonts:
        - asset: fonts/seguiemj.ttf
          weight: 400
    - family: Openmoji
      fonts:
        - asset: fonts/OpenMoji-Color.ttf
          weight: 400
```

I update flutter to stable 2.10.4 and the problem still there:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/56141162/161252887-f82a4e7d-2c35-42a9-97b8-9bbebeeec1d5.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/56141162/161253083-81712b34-5f99-41e4-90fd-7effe29a8581.png">

**Comment by ice-kylin** [comment]
> Hi @ice-kylin, I tested your code sample on `android`, `iOS`, `web`, and `macOS` and in all cases, the emojis are properly rendered. See screenshots below. Can you upgrade to stable 2.10.4 to see if you still experience this issue?
> 
> For future reference, please copy and paste the output of `flutter doctor -v` rather than sending screenshots. Please also provide any logs in text format as screenshots are not searchable and can sometimes be difficult to see at a glance.
> 
> screenshots
> ios	android	macOS	web
> ![Simulator Screen Shot - iPhone 13 - 2022-04-01 at 10 46 44](https://user-images.githubusercontent.com/88313112/161250650-6e5a59a6-6b2a-4dda-bbb1-3fdaad85de75.png)	![Screenshot_1648810165](https://user-images.githubusercontent.com/88313112/161250661-8d6336df-d93a-45a9-a8c7-023876458769.png)	<img alt="Screenshot 2022-04-01 at 10 51 35" width="558" src="https://user-images.githubusercontent.com/88313112/161250682-d7d32c77-8f26-45f4-af1d-256a147fe96e.png">	<img alt="Screenshot 2022-04-01 at 10 52 34" width="650" src="https://user-images.githubusercontent.com/88313112/161250728-b91854fb-5f74-4086-a383-a88ba7020943.png">

By the way, If you use windows, you can copy `seguiemj.ttf` from windows fonts dict.

**Comment by danagbemava-nc** [comment]
@ice-kylin, Ah, I see, kindly provide the font files so that I can verify this. 

Thank you

**Comment by ice-kylin** [comment]
> @ice-kylin, Ah, I see, kindly provide the font files so that I can verify this.
> 
> Thank you

The font website is here:

- [Segoe UI Emoji](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui-emoji)
- [OpenMoji](https://openmoji.org/php/download_asset.php?type=url&target_url=https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/font/OpenMoji-Color.ttf)
- [Noto Emoji](https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf)

You can download them use this zip file:

[fonts.zip](https://github.com/flutter/flutter/files/8398145/fonts.zip)

**Comment by jason-simmons** [comment]
The Flutter master branch includes support for the COLRv1 format used by the Segoe emoji font.

The OpenMoji font appears to be using an SVG-based format that is not supported by Flutter.

**Comment by danagbemava-nc** [comment]
Hi @ice-kylin, thanks for the fonts. 

It looks like the issue with `Segoe UI Emoji` has been fixed on `master` for android,  however, the OpenMoji fonts are not rendered in color on either the web or android. 

iOS and macOS, however, do not seem to have this issue. See screenshots below. The screenshots were taken on the master branch.

<details>
<summary>screenshots</summary>

| iOS | macOS | android | web | 
| -- | -- | -- | -- |
| ![Simulator Screen Shot - iPhone 13 - 2022-04-04 at 07 04 48](https://user-images.githubusercontent.com/88313112/161494310-4c1c324a-8e31-4cb4-a4c8-6ca18f491a4d.png) | <img width="558" alt="Screenshot 2022-04-04 at 07 06 34" src="https://user-images.githubusercontent.com/88313112/161494375-f2f72f05-d4fe-416d-b673-27c60bd3a0bb.png"> | ![Screenshot_1649055367](https://user-images.githubusercontent.com/88313112/161494429-5c4eb685-0adb-4ace-922c-8c8ce203099f.png) | <img width="612" alt="Screenshot 2022-04-04 at 07 05 50" src="https://user-images.githubusercontent.com/88313112/161494480-c109c8cc-41c6-4939-a5bc-e6e4036f3c39.png"> |

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-arm, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (10 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle
      (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString
      (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read
      (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer
      (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes
      (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.366, on macOS 12.2.1 21D62
    darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.366 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b97874895 (2 days ago), 2022-04-01 21:20:01 -0400
    • Engine revision 801d8c530f
    • Dart version 2.17.0 (build 2.17.0-265.0.dev)
    • DevTools version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[complete project for repro](https://github.com/flutter/flutter/files/8407628/ico.zip)

Note: 
- The `OpenMoji` fonts do not render with color on both stable and master for android and web
- The `OpenMoji` fonts render correctly on iOS on both stable and master

**Comment by ice-kylin** [comment]
Thank you for your work! I switched to master channel and all fonts are rendered correctly except `OpenMoji`.

**Comment by hterkelsen** [comment]
@jason-simmons should we file an issue with the Skia team to render color emoji using this SVG format?

**Comment by yjbanov** [comment]
CanvasKit already supports [COLRv1](https://developer.chrome.com/blog/colrv1-fonts/). Not sure if we need to do anything special. But I will keep this open for us to verify that it works and add tests. We also need to change our default font from the enormous bitmap font to a color font.
