### ISSUE TITLE
Flutter reads clipboard on XiaoMi MIUI 13

### ISSUE THREAD

**Issue by Linloir** [flutter/flutter#101196]
I'm developing an app that doesn't really need the clipboard permission, but I can't get rid of the system alert of clipboard reading.
<img src="http://pic.linloir.xyz/images/2022/04/02/WeChat-Image_20220401235119.jpg" width="350">

## Ways I have tried to fix the problem

- switch to master channel
- run `flutter upgrade`
- set `enableInteractiveSelection` flag to `false` in TextField widget

Nothing has yet worked on my device nor my friend's

## Steps to Reproduce

1. Connect a XiaoMi device with MIUI 13 installed
2. Execute `flutter debug` on the code sample 
3. Copy any text from another place 
4. Open the debug app just built and the alert pops up 

**Expected results:** 
Textfield without reading clipboard

**Actual results:** 
Textfield still reading clipboard everytime it inits

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: TextField()
      ),
    );
  }
}
```

</details>

<details>
<summary>Flutter doctor</summary>

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.358, on Ubuntu 20.04.4 LTS
    5.11.0-27-generic, locale en_US.UTF-8)
    • Flutter version 2.13.0-0.0.pre.358 at /home/linloir/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff08bc4e85 (87 minutes ago), 2022-04-01 10:31:09 -0400
    • Engine revision 276261e5d8
    • Dart version 2.17.0 (build 2.17.0-263.0.dev)
    • DevTools version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /home/linloir/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /snap/android-studio/119/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • M2007J1SC (mobile) • c0063973 • android-arm64  • Android 12 (API 31)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome
      98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by Linloir** [comment]
I'm really sorry to post a similar issue to #74139, #85610 and #91591
But after checking the solutions commented in those issues which appears to be the same: `change to master channel and upgrade`, nothing has worked for me
So is this issue on Flutter side or MIUI side

**Comment by maheshmnj** [comment]
Hi @Linloir, Thanks for filing the issue. Unfortunately none of us on the triage team have a miui 13 to reproduce this issue. We verified on Xiaomi k20 pro (Android 11) `miui 12.5` on the latest stable/master channel and the issue was not reproducible. Labeling this issue for further investigation from the team.

https://user-images.githubusercontent.com/31410839/161491681-0c264413-16fd-4b98-be59-f7ec50b6ad9d.mov


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.277, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.277 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 13d2381109 (6 hours ago), 2022-03-27 21:00:08 -0400
    • Engine revision 559e259c54
    • Dart version 2.17.0 (build 2.17.0-246.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by Linloir** [comment]
@maheshmnj Thanks for testing! 

It's weird that I also tried this on my friend's RedmiK50P with MIUI 12.5 but it's reproducible.

Therefore I've done some research on this feature (clipboard monitoring) and found out it *seems* to be available only on Chinese version of MIUI, maybe this causes the problem not reproducible.

**Comment by Northsecond** [comment]
The divice I use is Xiaomi Redmi K30 pro with miui 12.5 public development version 21.11.3 (Android 11). I succeed in reproducing the problem. When I open this app from the Home screen, the MIUI's security application claims that this app has accessed the clipboard 8 times. (You can find the app behavior record in the `app info` interface).

![2dec6529aa74fd4e86445fc477b66ca](https://user-images.githubusercontent.com/72327996/161501847-b755c37c-9d45-4fe6-972b-859f81f9e4a3.jpg)

**Comment by chinmaygarde** [comment]
cc @blasten for guidance on whether the out of the box key input interface needs clipboard access by default.

**Comment by blasten** [comment]
maybe related to https://github.com/flutter/flutter/issues/85610, and https://github.com/flutter/flutter/pull/87678. 
cc @justinmc

**Comment by fzyzcjy** [comment]
I can reproduce it in latest Flutter stable: https://github.com/flutter/flutter/issues/129931

**Comment by fzyzcjy** [comment]
I can workaround this problem by using the following patch (effectively letting ClipboardStatusNotifier do nothing but say it is pasteable):

```diff
diff --git a/packages/flutter/lib/src/widgets/text_selection.dart b/packages/flutter/lib/src/widgets/text_selection.dart
index e3c600ad42..4e87466aaf 100644
--- a/packages/flutter/lib/src/widgets/text_selection.dart
+++ b/packages/flutter/lib/src/widgets/text_selection.dart
@@ -3209,33 +3209,35 @@ class ClipboardStatusNotifier extends ValueNotifier<ClipboardStatus> with Widget
       return;
     }
 
-    final bool hasStrings;
-    try {
-      hasStrings = await Clipboard.hasStrings();
-    } catch (exception, stack) {
-      FlutterError.reportError(FlutterErrorDetails(
-        exception: exception,
-        stack: stack,
-        library: 'widget library',
-        context: ErrorDescription('while checking if the clipboard has strings'),
-      ));
-      // In the case of an error from the Clipboard API, set the value to
-      // unknown so that it will try to update again later.
-      if (_disposed || value == ClipboardStatus.unknown) {
-        return;
-      }
-      value = ClipboardStatus.unknown;
-      return;
-    }
-
-    final ClipboardStatus nextStatus = hasStrings
-        ? ClipboardStatus.pasteable
-        : ClipboardStatus.notPasteable;
-
-    if (_disposed || nextStatus == value) {
-      return;
-    }
-    value = nextStatus;
+    // NOTE MODIFIED #9921
+    value = ClipboardStatus.pasteable;
+    // final bool hasStrings;
+    // try {
+    //   hasStrings = await Clipboard.hasStrings();
+    // } catch (exception, stack) {
+    //   FlutterError.reportError(FlutterErrorDetails(
+    //     exception: exception,
+    //     stack: stack,
+    //     library: 'widget library',
+    //     context: ErrorDescription('while checking if the clipboard has strings'),
+    //   ));
+    //   // In the case of an error from the Clipboard API, set the value to
+    //   // unknown so that it will try to update again later.
+    //   if (_disposed || value == ClipboardStatus.unknown) {
+    //     return;
+    //   }
+    //   value = ClipboardStatus.unknown;
+    //   return;
+    // }
+    //
+    // final ClipboardStatus nextStatus = hasStrings
+    //     ? ClipboardStatus.pasteable
+    //     : ClipboardStatus.notPasteable;
+    //
+    // if (_disposed || nextStatus == value) {
+    //   return;
+    // }
+    // value = nextStatus;
   }
 
   @override
```

**Comment by justinmc** [comment]
@fzyzcjy Ideally we don't need to flag this code off but can instead properly implement `hasStrings` for Android.  We need to be able to check if the clipboard can paste without actually reading its contents.  I believe this can be done on Android with [hasPrimaryClip](https://developer.android.com/reference/android/content/ClipboardManager#hasPrimaryClip()), but I tried this before years ago and couldn't get it to work (https://github.com/flutter/engine/pull/24021).

Likely this is easier to do nowadays.  If you want to try it I would start with that engine PR and see if you can get the permission notification to stop appearing.

Original Android hasStrings PR: https://github.com/flutter/engine/pull/20393
Overall origina hasStrings issue: https://github.com/flutter/flutter/issues/60145

**Comment by fzyzcjy** [comment]
@justinmc I see, thank you!

(Btw in my daily usage I never see clipboard being empty - it always stores *last* copied data)

**Comment by justinmc** [comment]
I'm able to empty the clipboard on my Android phone by restarting it. Then I don't see the Paste button in the context menu on native apps.

You're right that not many people probably care about that, though.  Always showing the Paste button is a pretty attractive easy solution.

**Comment by fzyzcjy** [comment]
@justinmc Thank you. By the way, if the paste button disappears like that, I (personally) may even think it is a bug not a feature - hey where is my button? ;)

> You're right that not many people probably care about that, though. Always showing the Paste button is a pretty attractive easy solution.

So, shall I make a PR to make it "always show the paste button"? As you said, that will be much easier to PR

**Comment by justinmc** [comment]
If this is affecting many people then it makes sense to always show Paste on Android for now. Otherwise we should look at hasPrimaryClip.

**Comment by ratiger** [comment]
the same problem. seemed like invokeMethod 'Clipboard.hasStrings' in xiaomi would show the warning dialog.

**Comment by LYFhub** [comment]
May I know any updates for this topic? Thanks.

**Comment by alicelifengmei** [comment]
I’m dealing with the same issue, I’ve been told that we can’t keep reading clipboard content too often, or the app might get taken down

**Comment by bleroux** [comment]
@justinmc
In https://github.com/flutter/flutter/issues/101196#issuecomment-1881922641, you gave direction to address this issue:
> If this is affecting many people then it makes sense to always show Paste on Android for now. Otherwise we should look at hasPrimaryClip.

Looking at the engine code it seems that `hasPrimaryClip` support was implemented some years ago in https://github.com/flutter/engine/pull/27215 on the engine side and in https://github.com/flutter/flutter/pull/87678 for the framework side.
It does not help to fix the issue because `hasPrimaryClip` will usually return true (having an empty clipboard is probably rare).

Do you think we should proceed with "always show Paste on Android for now"?

**Comment by Morris-Mao** [comment]
Flutter 3.16.6   same issue .  dozens of time per second。

`java.lang.Exception
	at android.content.ClipboardManager.getPrimaryClipDescription(Native Method)
	at io.flutter.plugin.platform.PlatformPlugin.clipboardHasStrings(PlatformPlugin.java:555)
	at io.flutter.plugin.platform.PlatformPlugin.access$1200(PlatformPlugin.java:31)
	at io.flutter.plugin.platform.PlatformPlugin$1.clipboardHasStrings(PlatformPlugin.java:144)
	at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:184)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8246)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1031)`

**Comment by justinmc** [comment]
@bleroux Why exactly is this still a problem if we are using hasPrimaryClip now? Do XiaoMi devices still show the dialog even when hasPrimaryClip is called? If that's true then I'm on board with just always showing Paste on Android.

I would think it should work and not show the dialog now though. On the framework side [hasStrings is used](https://github.com/flutter/flutter/blob/048e38976159022a0baa673bc018a5c1eae93e78/packages/flutter/lib/src/widgets/text_selection.dart#L3486) to decide to show Paste or not, and in the engine with https://github.com/flutter/engine/pull/27215 it looks like that should only call hasPrimaryClip now.

**Comment by bleroux** [comment]
> @bleroux Why exactly is this still a problem if we are using hasPrimaryClip now? Do XiaoMi devices still show the dialog even when hasPrimaryClip is called? If that's true then I'm on board with just always showing Paste on Android.

@justinmc Unfortunately I don't have such a device to look more closely.
I came to this issue because of some recent reports (https://github.com/flutter/flutter/issues/153750 and https://github.com/flutter/flutter/issues/153749), and I saw that some comments above are somewhat recent (2024).

> I would think it should work and not show the dialog now though. On the framework side [hasStrings is used](https://github.com/flutter/flutter/blob/048e38976159022a0baa673bc018a5c1eae93e78/packages/flutter/lib/src/widgets/text_selection.dart#L3486) to decide to show Paste or not, and in the engine with [flutter/engine#27215](https://github.com/flutter/engine/pull/27215) it looks like that should only call hasPrimaryClip now.

Yes you're right. I looked more closely at the code. At first I thought that `hasStrings` was just returning true when there is something in the clipboard and then that a call to `getClipboardData` was made to see if the content is a text. But I was wrong, `getPrimaryClipDescription` is called to get this information and it is not supposed to trigger any security concerns (based on https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#PastingSystemNotifications).

It looks like, on some devices, there is another layer of security which flags those calls to `hasPrimaryClip` and/or `getPrimaryClipDescription`.
Ideally, it would be great to see what happens if a we create a native Android app that calls `hasPrimaryClip` and `getPrimaryClipDescription` many times. My bet is that the warning would be the same of those devices.

Not sure how to proceed. Would it make sense to always show 'Paste' to accomodate those devices security check? This will apply to all devices, not sure about the impact for end users seeing a paste button when there no valid content to paste.

For reference:
- Engine [implementation for `clipboardHasStrings`](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L602-L616)
- Engine [implementation for `getClipboardData`](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L529-L593)
