### ISSUE TITLE
How to find where I have used container with both decoration and color ?

### ISSUE THREAD

**Issue by radha1990kumari** [flutter/flutter#101185]
#### Error:
```
Cannot provide both a color and a decoration
To provide both, use "decoration: BoxDecoration(color: color)".
'package:flutter/src/widgets/container.dart':
Failed assertion: line 274 pos 15: 'color == null || decoration == null'

When the exception was thrown, this was the stack: 
#2      new Container (package:flutter/src/widgets/container.dart:274:15)
#3      _HomeState.build.<anonymous closure>.<anonymous closure> (package:spice_learn/screens/home_page/pages/Home.dart:110:49)
#4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:457:22)
#5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1215:28)
#6      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1228:55)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2600:19)
#8      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1221:12)
#9      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)


```
Doesn't show where in my project the widget is present. And will it be possible to catch this error via lint itself ?
</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@radha1990kumari 
You need to check whereever you are using BoxDecoration and Container widgets and update your code implementation as indicated in the error.
Closing from here. Please ask support questions on StackOverflow.
