### ISSUE TITLE
Desktop-macOS Network error 

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#101199]
Flutter desktop: **macOS Monterey**
I am developing a program that supports web and desktop.
web works fine. However, the following error occurs on desktop (macOS). I couldn't find what my settings were causing this problem.

I followed all the installation procedures.
 - https://firebase.flutter.dev/docs/manual-installation/macos/
 

I can't log in to firebase.

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale ko-KR)
    • Flutter version 2.10.4 at /Users/patrick386/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (7 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/patrick386/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
Launching lib/main.dart on macOS in debug mode...
Running pod install...
Building macOS application...
2022-04-02 00:52:59.882 xcodebuild[38192:240721] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-04-02 00:52:59.883 xcodebuild[38192:240721] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:7891C02E-CE99-5FAC-8CC0-23C2241C66B8 }
{ platform:macOS, name:Any Mac }
ld: warning: object file (/Users/patrick386/StudioProjects/pronto/build/macos/Build/Products/Debug/Pods_Runner.framework/Pods_Runner(Pods-Runner-dummy.o)) was built for newer macOS version (12.0) than being linked (10.12)
ld: warning: object file (/Users/patrick386/StudioProjects/pronto/build/macos/Build/Products/Debug/Pods_Runner.framework/Pods_Runner(Pods_Runner_vers.o)) was built for newer macOS version (12.0) than being linked (10.12)
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in dependency order
/Users/patrick386/StudioProjects/pronto/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 12.3.99. (in target 'BoringSSL-GRPC' from project 'Pods')
/Users/patrick386/StudioProjects/pronto/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.6, but the range of supported deployment target versions is 10.9 to 12.3.99. (in target 'FMDB' from project 'Pods')
/Users/patrick386/StudioProjects/pronto/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 12.3.99. (in target 'leveldb-library' from project 'Pods')
Debug service listening on ws://127.0.0.1:57090/GSx2GQUyDGo=/ws
Syncing files to device macOS...
flutter: Desktop TargetPlatform:true
Warning: The MainFlutterWindowManipulator has not been started. Please make sure the flutter_acrylic plugin is initialized correctly in your MainFlutterWindow.swift file.
flutter: SharedPreferences 디스크 init 하였습니다.

======== Exception caught by widgets ===============================================================
The following message was thrown:
Warning: This application's locale, ko_KR, is not supported by all of its localization delegates.

• A FlutterFireUILocalizations<FlutterFireUILocalizationLabels> delegate that supports the ko_KR locale was not found.

The declared supported locales for this app are: en_US, ko_KR

See https://flutter.dev/tutorials/internationalization/ for more information about configuring an app's locale, supportedLocales, and localizationsDelegates parameters.
====================================================================================================
flutter: HomePage 페이지에 들어왔습니다.
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      VideoPlayerApi.initialize (package:video_player_platform_interface/messages.dart:156:7)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:181:7)
<asynchronous suspension>
#1      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:54:37)
<asynchronous suspension>
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:356:19)
<asynchronous suspension>


======== Exception caught by image resource service ================================================
The following SocketException was thrown resolving an image codec:
Connection failed (OS Error: Operation not permitted, errno = 1), address = firebasestorage.googleapis.com, port = 443
```
![스크린샷 2022-04-01 오후 9 27 55](https://user-images.githubusercontent.com/49754877/161302004-f2595525-7e34-47d3-894a-37eeebc5007b.png)

**main.dart**

```
/// Checks if the current environment is a desktop environment.
bool get isDesktop {
  if (kIsWeb) return false;
  return [
    TargetPlatform.windows,
    TargetPlatform.linux,
    TargetPlatform.macOS,
  ].contains(defaultTargetPlatform);
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  Logger.root.level = Level.INFO; // defaults to Level.INFO
  Logger.root.onRecord.listen((record) {
    debugPrint('${record.level.name}: ${record.time}: ${record.message}');
  });


  setPathUrlStrategy();

  if (isDesktop) {
    print('Desktop TargetPlatform:${isDesktop}');
    await flutter_acrylic.Window.initialize();
    await WindowManager.instance.ensureInitialized();
    windowManager.waitUntilReadyToShow().then((_) async {
      await windowManager.setTitleBarStyle('hidden',
          windowButtonVisibility: true);
      await windowManager.setSize(const Size(1200, 900));
      await windowManager.setMinimumSize(const Size(600, 700));
      await windowManager.center();
      await windowManager.show();
      await windowManager.setPreventClose(true);
      await windowManager.setSkipTaskbar(false);

    });
  }

  SharedDisk().init();
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends HookConsumerWidget {
  MyApp({Key? key}) : super(key: key);
  final BeamerDelegate routerDelegate = createDelegate();
  final BeamerParser routeInformationParser = BeamerParser();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      scrollBehavior: AppScrollBehavior(), 
      title: 'Pronto',
      localizationsDelegates: [
        flutter_ui.FlutterFireUILocalizations.withDefaultOverrides(
            const LabelOverrides()),
        GlobalMaterialLocalizations.delegate, //Internationalization
        GlobalWidgetsLocalizations.delegate, //Internationalization
        GlobalCupertinoLocalizations.delegate, //Internationalization
      ],     
      supportedLocales: L10n.all,
      theme: slpThemeData,
      routerDelegate: routerDelegate,
      routeInformationParser: BeamerParser(),
    );
  }
}
```

**Comment by stuartmorgan** [comment]
See https://docs.flutter.dev/desktop#entitlements-and-the-app-sandbox for information about accessing the Internet in a sandboxed application.

**Comment by Patrick386** [comment]
I solved the problem with additional settings as below.
Xcode > Runner > Signing & Capabilities > Outgoing Connections (Client)
![스크린샷 2022-04-02 오전 2 17 51](https://user-images.githubusercontent.com/49754877/161312457-f09f0a26-8a1d-40f6-abcd-2a072a93982c.png)

**Comment by Patrick386** [comment]
I solved the problem with additional settings as below.
Xcode > Runner > Signing & Capabilities > Outgoing Connections (Client)
![스크린샷 2022-04-02 오전 2 17 51](https://user-images.githubusercontent.com/49754877/161312747-ff944013-fb40-4358-a571-1d064a8e41ae.png)

**Comment by stuartmorgan** [comment]
Note that ignoring the guidance in the documentation I linked to, and using the Xcode capabilities UI, is likely to cause issues, as the documentation says.
