### ISSUE TITLE
Use file.readAsBytes() on Flutter web

### ISSUE THREAD

**Issue by MuhmdHsn313** [flutter/flutter#101104]
Hello

I used `file_selector` on flutter web to get an image file, after that I tried to get `Uint8List` of this file by using `readAsBytesSync` method but it's throw a bug, I tried to use `readAsBytes` and don't work too.

So how can I get `Uint8List` in flutter web?

**Comment by danagbemava-nc** [comment]
Hi @MuhmdHsn313, please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v` and `flutter run -v` that shows the error that you're experiencing. 

Thank you

**Comment by MuhmdHsn313** [comment]
Flutter doctor -v
```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.556], locale en-US)
    • Flutter version 2.10.3 at C:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\muham\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.66.0)
    • VS Code at C:\Users\muham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.84
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.55

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

the line of code that make the bug
```dart
final rawPath = file1.readAsBytesSync();
```

the error showing when I run flutter web app
```
Error: Unsupported operation: _Namespace
    at Object.throw_ [as throw] (http://localhost:53611/dart_sdk.js:5067:11)
    at Function.get _namespace [as _namespace] (http://localhost:53611/dart_sdk.js:56704:17)
    at io._File.new.openSync (http://localhost:53611/dart_sdk.js:54742:45)
    at io._File.new.readAsBytesSync (http://localhost:53611/dart_sdk.js:54795:25)
at printed_kyc.KycStepperPdf.new.generatePDF (http://localhost:53611/packages/merchant_portal/features/home/presentation/widgets/printed_kyc.dart.lib.js:310:29)
    at generatePDF.next (<anonymous>)
    at http://localhost:53611/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:53611/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:53611/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:53611/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:53611/dart_sdk.js:35969:17)
    at _Future.new.[_completeWithValue] (http://localhost:53611/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53611/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:53611/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:53611/dart_sdk.js:40714:13)
    at http://localhost:53611/dart_sdk.js:36191:9
```

**Comment by danagbemava-nc** [comment]
Hi @MuhmdHsn313, the error is due to the fact that `reasAsBytesSync` is from `dart:io` which is not available on web. Can you check this [SO comment](https://stackoverflow.com/questions/59761947/choose-a-file-and-send-through-post-with-flutter-web) to see if the solution used works for you?

**Comment by MuhmdHsn313** [comment]
Unfortunately, It's don't work!

I need to export a PDF file using [pdf](https://pub.dev/packages/pdf) package, so I need to get it as `Uint8List` from flutter web, after that I can use `Uint8List` to print image in PDF.

**Comment by MuhmdHsn313** [comment]
Thanks @danagbemava-nc 

I solve this bug using networkImage, this is be more easy when I understand this idea, we have to replace io with network in flutter web.

```dart
final netImage = await networkImage('https://www.nfet.net/nfet.jpg');
```

now it's work correctly!
