### ISSUE TITLE
Dart -> Engine roller blocked on null assert in Android test.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101242]
Starting with https://github.com/flutter/engine/pull/32399, the Dart -> Engine roll is failing https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20AOT%20Engine/34164/overview.

The culprit appears to be https://dart.googlesource.com/sdk.git/+/23ea9f3da45807c2c706483bfe3155f488a93e22

@bkonyi

**Comment by zanderso** [comment]
Did a trial roll here that includes the change above: https://github.com/flutter/engine/pull/32424

Something is still going wrong: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20AOT%20Engine/34213/overview

```
'E/flutter(22225): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Unexpected character (at character 1)',
'E/flutter(22225): This VM was built without the Observatory UI.',
'E/flutter(22225): ^',
'E/flutter(22225): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)',
'E/flutter(22225): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250)',
'E/flutter(22225): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915)',
'E/flutter(22225): #3      _parseJson (dart:convert-patch/convert_patch.dart:35)',
'E/flutter(22225): #4      JsonDecoder.convert (dart:convert/json.dart:612)', 'E/flutter(22225): #5      JsonCodec.decode (dart:convert/json.dart:216)',
'E/flutter(22225): #6      _getJson (package:scenario_app/main.dart:83)', 'E/flutter(22225): <asynchronous suspension>', 
'E/flutter(22225): #7      _getTimelineData (package:scenario_app/main.dart:66)',
'E/flutter(22225): <asynchronous suspension>',
'E/flutter(22225): #8      _handlePlatformMessage (package:scenario_app/main.dart:55)',
'E/flutter(22225): <asynchronous suspension>'
```

**Comment by zanderso** [comment]
@godofredoc I don't have access to the bucket that stores the logs for the firebase run.

**Comment by zanderso** [comment]
@bkonyi The failure is coming from here https://github.com/flutter/engine/blob/main/testing/scenario_app/lib/main.dart#L83. The app expects to be able to make requests to its own VM service, but instead of returning the json result, the requests are returning "This VM was built without the Observatory UI."

Is it really true that the Observatory UI has been removed in the Dart rolls? cc @a-siva

**Comment by bkonyi** [comment]
> Is it really true that the Observatory UI has been removed in the Dart rolls? cc @a-siva

No, it definitely hasn't been (not yet, anyway... :-) that would definitely be communicated before it happens). I'm guessing some of my refactoring did something strange. I'll take a look.

**Comment by godofredoc** [comment]
@keyonghan can you please take a look at the firebase log permissions?

**Comment by dnfield** [comment]
Better error in logcat:

```
04-02 00:44:13.272: I/flutter(24883): Could not load Observatory assets: type 'List<dynamic>' is not a subtype of type 'List<Object>' of 'function result'
04-02 00:44:13.273: E/DartVM(24883): vm-service: Error: Unhandled exception:
04-02 00:44:13.273: E/DartVM(24883): Null check operator used on a null value
04-02 00:44:13.273: E/DartVM(24883): #0      assets (dart:_vmservice/asset.dart:69)
04-02 00:44:13.273: E/DartVM(24883): #1      Server._requestHandler (dart:vmservice_io/vmservice_server.dart:370)
04-02 00:44:13.273: E/DartVM(24883): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618)
04-02 00:44:13.273: E/DartVM(24883): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
04-02 00:44:13.273: E/DartVM(24883): #4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
04-02 00:44:13.273: E/DartVM(24883): #5      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
04-02 00:44:13.273: E/DartVM(24883): #6      _StreamController._add (dart:async/stream_controller.dart:648)
04-02 00:44:13.273: E/DartVM(24883): #7      _StreamController.add (dart:async/stream_controller.dart:596)
04-02 00:44:13.273: E/DartVM(24883): #8      _HttpServer._handleRequest (dart:_http/http_impl.dart:3303)
04-02 00:44:13.273: E/DartVM(24883): #9      new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:3053)
04-02 00:44:13.273: E/DartVM(24883): #10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618)
04-02 00:44:13.273: E/DartVM(24883): #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
04-02 00:44:13.273: E/DartVM(24883): #12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
04-02 00:44:13.273: E/DartVM(24883): #1
04-02 00:44:13.273: E/flutter(24883): [ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
04-02 00:44:13.273: E/flutter(24883): Null check operator used on a null value
04-02 00:44:13.273: E/flutter(24883): #0      assets (dart:_vmservice/asset.dart:69)
04-02 00:44:13.273: E/flutter(24883): #1      Server._requestHandler (dart:vmservice_io/vmservice_server.dart:370)
04-02 00:44:13.273: E/flutter(24883): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618)
04-02 00:44:13.273: E/flutter(24883): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
04-02 00:44:13.273: E/flutter(24883): #4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
04-02 00:44:13.273: E/flutter(24883): #5      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
04-02 00:44:13.273: E/flutter(24883): #6      _StreamController._add (dart:async/stream_controller.dart:648)
04-02 00:44:13.273: E/flutter(24883): #7      _StreamController.add (dart:async/stream_controller.dart:596)
04-02 00:44:13.273: E/flutter(24883): #8      _HttpServer._handleRequest (dart:_http/http_impl.dart:3303)
04-02 00:44:13.273: E/flutter(24883): #9      new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:3053)
04-02 00:44:13.273: E/flutter(24883): #10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618)
04-02 00:44:13.273: E/flutter(24883): #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
04-02 00:44:13.273: E/flutter(24883): #12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
04-02 00:44:13.273: E/flutter(24883): #13     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
04-02 00:44:13.273: E/flutter(24883): #14     _StreamController._add (dart:async/stream_controller.dart:648)
04-02 00:44:13.273: E/flutter(24883): #15     _StreamController.add (dart:async/stream_controller.dart:596)
04-02 00:44:13.273: E/flutter(24883): #16     _HttpParser._headersEnd (dart:_http/http_parser.dart:389)
04-02 00:44:13.273: E/flutter(24883): #17     _HttpParser._doParse (dart:_http/http_parser.dart:745)
04-02 00:44:13.273: E/flutter(24883): #18     _HttpParser._parse (dart:_http/http_parser.dart:319)
04-02 00:44:13.273: E/flutter(24883): #19     _HttpParser._onData (dart:_http/http_parser.dart:873)
04-02 00:44:13.273: E/flutter(24883): #20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618)
04-02 00:44:13.273: E/flutter(24883): #21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
04-02 00:44:13.273: E/flutter(24883): #22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
04-02 00:44:13.273: E/flutter(24883): #23     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
04-02 00:44:13.273: E/flutter(24883): #24     _StreamController._add (dart:async/stream_controller.dart:648)
04-02 00:44:13.273: E/flutter(24883): #25     _StreamController.add (dart:async/stream_controller.dart:596)
04-02 00:44:13.273: E/flutter(24883): #26     _Socket._onData (dart:io-patch/socket_patch.dart:2314)
04-02 00:44:13.273: E/flutter(24883): #27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618)
04-02 00:44:13.273: E/flutter(24883): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
04-02 00:44:13.273: E/flutter(24883): #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
04-02 00:44:13.273: E/flutter(24883): #30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
04-02 00:44:13.273: E/flutter(24883): #31     _StreamController._add (dart:async/stream_controller.dart:648)
04-02 00:44:13.273: E/flutter(24883): #32     _StreamController.add (dart:async/stream_controller.dart:596)
04-02 00:44:13.273: E/flutter(24883): #33     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1839)
04-02 00:44:13.273: E/flutter(24883): #34     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322)
04-02 00:44:13.273: E/flutter(24883): #35     _microtaskLoop (dart:async/schedule_microtask.dart:40)
04-02 00:44:13.273: E/flutter(24883): #36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
04-02 00:44:13.273: E/flutter(24883): #37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122)
04-02 00:44:13.273: E/flutter(24883): #38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193)
```

**Comment by dnfield** [comment]
@keyonghan @godofredoc - 

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/8620741/161818248-ea6d23c3-ed33-45ba-b558-ff5f8be59bf4.png">


If I click `Download` itsends me to a 403 forbidden page. If I click `View test results` I can access the GCP project and find the logcat in there.

**Comment by keyonghan** [comment]
> @keyonghan @godofredoc -
> If I click `Download` itsends me to a 403 forbidden page. If I click `Test results` I can access the GCP project and find the logcat in there.

More context re the 403 page: b/201685683

@zanderso Are you able to access [gcs log](https://pantheon.corp.google.com/storage/browser/flutter_firebase_testlab/plugins_android_test/webview_flutter/webview_flutter/5557305593823232/fde556a5-d191-479a-aff3-f4ad1747de35/0/starqlteue-26-en-portrait;tab=objects?authuser=0&prefix=&forceOnObjectsSortingFiltering=false)? We have granted the following roles to flutter-team@
```
Firebase Test Lab Viewer
Storage Legacy Bucket Reader
Storage Legacy Object Reader
```

**Comment by bkonyi** [comment]
Should be an easy enough fix, but I'd like to make sure there's nothing else I'd missed. @dnfield, do you know how to run this application locally with a custom engine? I get all sorts of errors when I try (unsupported gradle project, use of v1 embedding API error, etc).

**Comment by dnfield** [comment]
@bkonyi it should build as part of the ninja build for e.g. android_debug. That will produce an apk under `out/android_debug/firebase_apks`

**Comment by bkonyi** [comment]
@dnfield just installing that APK with `adb install scenario_app.apk` and then opening it is enough? I can't reproduce the actual crash this way.

**Comment by bkonyi** [comment]
Fix has landed in https://dart-review.googlesource.com/c/sdk/+/240303. Re-assigning to @zanderso to try to roll again.

**Comment by a-siva** [comment]
I believe the Dart rolls are back on track after a revert was done of https://dart-review.googlesource.com/c/sdk/+/239421, can this be closed.

**Comment by zanderso** [comment]
Yes. Closing.
