### ISSUE TITLE
Enabling integration_test package trigger error to enable multidex

### ISSUE THREAD

**Issue by Bikram-Shrestha** [flutter/flutter#101272]
Hi, I have got a basic application which will build fine if I remove integration_test package from dev_dependencies but if I add it, it throw error asking me to enable multidex. Is this desired behaviour? I have similar looking project build prior to 2.5.3 and had no issue. 

My pubspec file
```
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies: 
  auto_route: ^3.2.4
  community_material_icon: ^5.9.55
  dio: ^4.0.4
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.3
  form_field_validator: ^1.1.0
  fpdart: ^0.0.14
  freezed_annotation: ^1.1.0
  google_fonts: ^2.3.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  package_info_plus: ^1.4.0
  path: ^1.8.0
  path_provider: ^2.0.9
  sembast: ^3.1.2
  shimmer: ^2.0.0
  timezone: ^0.8.0


dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

  freezed: ^1.0.2
  integration_test:
    sdk: flutter

  json_serializable: ^6.1.4
  lint: ^1.8.2
  mocktail: ^0.3.0-dev.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
```
<details>

  <summary>Logs</summary>

Error code
```
at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at java.base[/java.util.concurrent.FutureTask.run]()(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base[/java.util.concurrent.Executors]()$RunnableAdapter.call(Executors.java:515)
	at java.base[/java.util.concurrent.FutureTask.run]()(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base[/java.util.concurrent.ThreadPoolExecutor.runWorker]()(ThreadPoolExecutor.java:1128)
	at java.base[/java.util.concurrent.ThreadPoolExecutor]()$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base[/java.lang.Thread.run]()(Thread.java:829)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: null
	at Version.fakeStackEntry(Version_2.1.62.java:0)
	at com.android.tools.r8.utils.Y.a(SourceFile:78)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
	... 36 more
Caused by: com.android.tools.r8.utils.b: Cannot fit requested classes in a single dex file (# methods: 65813 > 65536)
	at com.android.tools.r8.utils.T0.error(SourceFile:1)
	at com.android.tools.r8.utils.T0.a(SourceFile:2)
	at com.android.tools.r8.dex.P.a(SourceFile:740)
	at com.android.tools.r8.dex.P$h.a(SourceFile:7)
	at com.android.tools.r8.dex.b.a(SourceFile:14)
	at com.android.tools.r8.dex.b.b(SourceFile:25)
	at com.android.tools.r8.D8.d(D8.java:133)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.utils.Y.a(SourceFile:36)
	... 38 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexDevProfile'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at [https://developer.android.com/tools/building/multidex.html]()

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 22s
[!] App requires Multidex support
┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────┐
│ Flutter multidex handling is disabled. If you wish to let the tool configure multidex, use the │
│ --mutidex flag.                                                                                │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDevProfile failed with exit code 1
#0      throwToolExit (package:flutter_tools[/src/base/common.dart:10:3]())
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools[/src/android/gradle.dart:431:9]())
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools[/src/android/gradle.dart:179:5]())
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools[/src/android/android_device.dart:579:7]())
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools[/src/resident_runner.dart:501:33]())
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools[/src/run_cold.dart:71:28]())
<asynchronous suspension>
#6      AppDomain.launch.<anonymous closure> (package:flutter_tools[/src/commands/daemon.dart:621:9]())
<asynchronous suspension>
#7      AppDomain.launch (package:flutter_tools[/src/commands/daemon.dart:619:5]())
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools[/src/commands/run.dart:571:15]())
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools[/src/runner/flutter_command.dart:1161:27]())
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools[/src/base/context.dart:150:19]())
<asynchronous suspension>
#11     CommandRunner.runCommand
package:args/command_runner.dart:209
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools[/src/runner/flutter_command_runner.dart:281:9]())
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools[/src/base/context.dart:150:19]())
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools[/src/runner/flutter_command_runner.dart:229:5]())
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools[/runner.dart:62:9]())
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools[/src/base/context.dart:150:19]())
<asynchronous suspension>
#17     main (package:flutter_tools[/executable.dart:94:3]())
<asynchronous suspension>
2

Exited (sigterm)at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at java.base[/java.util.concurrent.FutureTask.run]()(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base[/java.util.concurrent.Executors]()$RunnableAdapter.call(Executors.java:515)
	at java.base[/java.util.concurrent.FutureTask.run]()(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base[/java.util.concurrent.ThreadPoolExecutor.runWorker]()(ThreadPoolExecutor.java:1128)
	at java.base[/java.util.concurrent.ThreadPoolExecutor]()$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base[/java.lang.Thread.run]()(Thread.java:829)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: null
	at Version.fakeStackEntry(Version_2.1.62.java:0)
	at com.android.tools.r8.utils.Y.a(SourceFile:78)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
	... 36 more
Caused by: com.android.tools.r8.utils.b: Cannot fit requested classes in a single dex file (# methods: 65813 > 65536)
	at com.android.tools.r8.utils.T0.error(SourceFile:1)
	at com.android.tools.r8.utils.T0.a(SourceFile:2)
	at com.android.tools.r8.dex.P.a(SourceFile:740)
	at com.android.tools.r8.dex.P$h.a(SourceFile:7)
	at com.android.tools.r8.dex.b.a(SourceFile:14)
	at com.android.tools.r8.dex.b.b(SourceFile:25)
	at com.android.tools.r8.D8.d(D8.java:133)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.utils.Y.a(SourceFile:36)
	... 38 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexDevProfile'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at [https://developer.android.com/tools/building/multidex.html]()

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 22s
[!] App requires Multidex support
┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────┐
│ Flutter multidex handling is disabled. If you wish to let the tool configure multidex, use the │
│ --mutidex flag.                                                                                │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDevProfile failed with exit code 1
#0      throwToolExit (package:flutter_tools[/src/base/common.dart:10:3]())
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools[/src/android/gradle.dart:431:9]())
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools[/src/android/gradle.dart:179:5]())
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools[/src/android/android_device.dart:579:7]())
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools[/src/resident_runner.dart:501:33]())
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools[/src/run_cold.dart:71:28]())
<asynchronous suspension>
#6      AppDomain.launch.<anonymous closure> (package:flutter_tools[/src/commands/daemon.dart:621:9]())
<asynchronous suspension>
#7      AppDomain.launch (package:flutter_tools[/src/commands/daemon.dart:619:5]())
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools[/src/commands/run.dart:571:15]())
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools[/src/runner/flutter_command.dart:1161:27]())
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools[/src/base/context.dart:150:19]())
<asynchronous suspension>
#11     CommandRunner.runCommand
package:args/command_runner.dart:209
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools[/src/runner/flutter_command_runner.dart:281:9]())
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools[/src/base/context.dart:150:19]())
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools[/src/runner/flutter_command_runner.dart:229:5]())
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools[/runner.dart:62:9]())
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools[/src/base/context.dart:150:19]())
<asynchronous suspension>
#17     main (package:flutter_tools[/executable.dart:94:3]())
<asynchronous suspension>
2

Exited (sigterm)
```
</details>

**Expected results:** 
Code to build without requiring me to enable multidex
**Actual results:** 
Error with multidex issue
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3.1 21E258 darwin-arm, locale en-AU)
    • Flutter version 2.10.3 at /Users/user/fvm/versions/2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Bikram-Shrestha 
What's the `minsdkversion` of your app ? Check this for your reference: https://developer.android.com/studio/build/multidex?authuser=1

Also `integration_test` seems to be using `minsdkversion` as 16 and hence it may be asking you to enable multidex support.

**Comment by Bikram-Shrestha** [comment]
```
defaultConfig {
        applicationId "com.example"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
```
I am using minSdkVersion provided by flutter so in my case it is set as 16 in flutter.gradle file

**Comment by Bikram-Shrestha** [comment]
@darshankawar  manually setting the minSdkVersion to 21 solved the issue with the multidex error. Thank you for your help.  If there is anything else I need to be aware of please let me know, otherwise I am happy to close this ticket

**Comment by darshankawar** [comment]
Thanks for the update and good to know issue is resolved. We might need to raise a new issue to update integration_test package's minsdkversion to 21, but I am not sure if that'll have any other impact on the framework. 

I'll close this issue as resolved for now.
