### ISSUE TITLE
Another Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by kttary** [flutter/flutter#101225]
When building from xcode i get this error:

built and packaged successfully./Users/macos/Library/Developer/Xcode/DerivedData/Runner-fsjsfxksdjramohjctwfeextbmqj/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh: line 3: : command not found
Command PhaseScriptExecution failed with a nonzero exit code

flutter run --verbose raise the following error:

```
> [+37805 ms] Could not build the application for the simulator.
> [   +2 ms] Error launching application on iPhone SE (3rd generation).
> [   +5 ms] "flutter run" took 773,657ms.
> [   +8 ms] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
>            <asynchronous suspension>
>            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
>            <asynchronous suspension>
>            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
>            <asynchronous suspension>
>            #5      FlutterCommandRunner.runCommand.<anonymous closure>
> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
>            <asynchronous suspension>
>            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
>            <asynchronous suspension>
>            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
>            <asynchronous suspension>
>            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #10     main (package:flutter_tools/executable.dart:94:3)
>            <asynchronous suspension>

```

Flutter doctor:

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.355, on macOS 12.3.1 21E258 darwin-x64, locale en-ID)
    • Flutter version 2.13.0-0.0.pre.355 at /Users/macos/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c5819f4cb9 (21 hours ago), 2022-04-01 03:21:09 -0400
    • Engine revision c2de44a59c
    • Dart version 2.17.0 (build 2.17.0-261.0.dev)
    • DevTools version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/macos/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • 354B5D81-5FEC-461A-BC7B-F74B3C8769B2 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by darshankawar** [comment]
@kttary 
Please provide complete `flutter run -v` log. It'll be huge so you can put that in a text file and share it here.
Also provide your `ios/podfile`.

**Comment by kttary** [comment]
pls find my ios/podfile and complete `flutter run -v` result
[Podfile.txt](https://github.com/flutter/flutter/files/8414230/Podfile.txt)
[log.txt](https://github.com/flutter/flutter/files/8414477/log.txt)
.

**Comment by darshankawar** [comment]
@kttary 
From the verbose log, its failing due to below error:

`shared_preferences_ios.build/Objects-normal/x86_64/shared_preferences_ios-dummy.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'shared_preferences_ios' from project 'Pods')`

Can you try to upgrade your pods by running `pod repo update` and see if it helps ?

**Comment by kttary** [comment]
What i cannot understand is the error changing by the time.. Today i got different error as you can see from attachment below

[error.txt](https://github.com/flutter/flutter/files/8419265/error.txt)

Upgrade my pods seem not help

**Comment by darshankawar** [comment]
@kttary 
The new error from the log is:

`FLTURLLauncherPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found` which indicates a linker error, ie, the version between your podfile and podfile.lock / pubspec may not be matching. Can you try to delete `podfile.lock` and run `pod install` and then try to run the app and see if it helps ?

**Comment by kttary** [comment]
clean, pub get, pod clean, deintegrate, delete .symlink, pods, pod.lock, .pubcache etc not help me

**Comment by darshankawar** [comment]
I looked at your podfile again and you seem to have commented out below line:

 `#flutter_additional_ios_build_settings(target)`. which is required to setup the plugins. Uncomment it and it should resolve the issue.

Closing from here.

**Comment by kttary** [comment]
My mistake, now i got the original error when i create this issue. I guess i wrote my first reply after edited podfile. I should upload this pod file and `flutter run -v` result at my first reply.

[Podfile.txt](https://github.com/flutter/flutter/files/8438601/Podfile.txt)
[log.txt](https://github.com/flutter/flutter/files/8438602/log.txt)

The error message on my flutter terminal now more or less the same as my first message:

```
[+9800 ms] Could not build the application for the simulator.
[   +2 ms] Error launching application on iPhone SE (3rd generation).
[   +6 ms] "flutter run" took 131,337ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +101 ms] ensureAnalyticsSent: 98ms
[ +173 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
