### ISSUE TITLE
[Windows][MacOS][iOS] Context null in MaterialLocalizations.of(context)

### ISSUE THREAD

**Issue by Ephenodrom** [flutter/flutter#101292]
Hello,

Several user face strange errors with some parts of the app greyed out. This normally means, that there is an uncatched exception in a widget. I receive several different stacktraces via automatic error reporting that all have the same error "**Null check operator used on a null value**" and end with the same line  **"#0      MaterialLocalizations.of (package:flutter/src/material/material_localizations.dart:516)**" in the stacktrace.

Now my problem is, that the problem can not be reproduced on my testing devices. The app was build with the latest version 2.10.4 and shipped on the Windows and Apple App Store.

Any idea what is wrong ?

Full stacktrace.
```
#0      MaterialLocalizations.of (package:flutter/src/material/material_localizations.dart:516)
#1      BackButton.build (package:flutter/src/material/back_button.dart:101)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4827)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#8      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
#9      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#34     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
#35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#43     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
#44     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#76     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
#77     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
#78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#81     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#95     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#98     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#102    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#111    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#115    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#117    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#118    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#119    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#123    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#125    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#126    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#127    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#131    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#138    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#143    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#144    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#145    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#146    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#147    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#152    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#153    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#157    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#160    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#161    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#165    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#168    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#178    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#179    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#180    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#182    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#183    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#184    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#185    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#186    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#187    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#190    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#194    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#195    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#196    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#197    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#198    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#199    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#200    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#201    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#202    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#203    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#204    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#205    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#206    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#208    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#209    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#210    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#211    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#212    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#214    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#216    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#217    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#218    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#219    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#220    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#221    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#222    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#225    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#226    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#227    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#228    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#229    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#230    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#234    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#235    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#236    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#239    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#240    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#241    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#242    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#245    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#246    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#247    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#248    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#249    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#250    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#251    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#252    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#253    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#254    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#255    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#256    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#258    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#259    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#260    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#261    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#262    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#263    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#264    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#265    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#266    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#267    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#268    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#269    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#270    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#271    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#272    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#273    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#274    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#275    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#276    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#277    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#278    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#279    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#280    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#281    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#282    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#283    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#284    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#285    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#286    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#287    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#288    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#289    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#290    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#291    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#292    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#293    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#294    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#295    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#296    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#297    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#298    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#299    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#300    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#301    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#302    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#303    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
#304    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#305    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#306    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#307    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#308    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#309    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#310    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#311    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#312    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#313    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#314    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#315    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#316    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#317    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#318    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#319    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#320    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#321    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#322    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#323    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
#324    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
#325    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
#326    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
#327    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
#328    Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
#329    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5845)
#330    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445)
#331    Element.updateChild (package:flutter/src/widgets/framework.dart:3501)
#332    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#333    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#334    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#335    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960)
#336    Element.updateChild (package:flutter/src/widgets/framework.dart:3501)
#337    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#338    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#339    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108)
#340    Element.updateChild (package:flutter/src/widgets/framework.dart:3501)
#341    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#342    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#343    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108)
#344    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111)
#345    Element.updateChild (package:flutter/src/widgets/framework.dart:3501)
#346    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291)
#347    Element.updateChild (package:flutter/src/widgets/framework.dart:3501)
#348    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#349    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#350    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#351    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960)
#352    Element.updateChild (package:flutter/src/widgets/framework.dart:3501)
#353    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291)
#354    Element.updateChild (package:flutter/src/widgets/framework.dart:3501)
#355    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291)
#356    Element.updateChild (package:flutter/src/widgets/framework.dart:3501)
#357    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#358    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#359    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108)
#360    Element.updateChild (package:flutter/src/widgets/framework.dart:3501)
#361    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
#362    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
#363    Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
#364    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659)
#365    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882)
#366    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363)
#367    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
#368    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081)
#369    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995)
#370    _rootRun (dart:async/zone.dart:1426)
#371    _CustomZone.run (dart:async/zone.dart:1328)
#372    _CustomZone.runGuarded (dart:async/zone.dart:1236)
#373    _invoke (dart:ui/hooks.dart:151)
#374    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
#375    _drawFrame (dart:ui/hooks.dart:115)
```

**Comment by maheshmnj** [comment]
Hi @Ephenodrom, thanks for filling the issue. Please share a minimal and complete code sample to investigate the issue further.

**Comment by Ephenodrom** [comment]
The problem was that the **supportedLocales** parameter was set without setting the **localizationsDelegates** parameter on the MaterialApp.

The interesting thing still is, that the error did not appear on all devices.
