### ISSUE TITLE
Attempted to send a key down event when no keys are in keysPressed

### ISSUE THREAD

**Issue by ZoubairDaddow** [flutter/flutter#101275]
I'm using **onKey** and **onKeyEvent** to listen to tv remote control keys
but I have this error when press **SELECT** or **ENTER**

`Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#23bc9(logicalKey: LogicalKeyboardKey#0050c(keyId: "0x10000050c", keyLabel: "Select", debugName: "Select"), physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName: "Control Right"), repeat: false) and its data: RawKeyEventDataAndroid#92581(flags: 8, codePoint: 0, plainCodePoint: 0, keyCode: 23, scanCode: 97, metaState: 0)
'package:flutter/src/services/raw_keyboard.dart':
package:flutter/…/services/raw_keyboard.dart:1
Failed assertion: line 685 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'`

When I use **RawKeyboardListener** I have same issue but it call the method **onKey**

**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.4-0.0.pre.1, on Microsoft Windows [Version 10.0.19042.1266], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.8) 
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.66.0)
[√] Connected device (5 available)
[√] HTTP Host Availability

• No issues found!

**Comment by maheshmnj** [comment]
Hi @ZoubairDaddow, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the steps to reproduce the issue.

**Comment by ZoubairDaddow** [comment]
Hi @maheshmnj  
This is example for RawKeyboardListener
It works well , but when try to use it on tv remote pad the method (01) and the method (02) call

`RawKeyboardListener(
        onKey: (e) {
          if (e is RawKeyUpEvent &&
              (e.logicalKey == LogicalKeyboardKey.select ||
                  e.logicalKey == LogicalKeyboardKey.enter)) {
        //do something (01)
          }
        },
        focusNode: FocusNode(canRequestFocus: false),
        child: MaterialButton(
          onPressed: () {
         //do something (02)
          },
          child: Text("Click Here"),
        ));`




And this is Example for FocusNode and **this is the code I need** cause KeyEventResult.handled; handle the key and stop the key listening so the method 02 not call
  
`FocusNode(
        onKeyEvent: (node , e) {
          if (e is RawKeyUpEvent &&
              (e.logicalKey == LogicalKeyboardKey.select ||
                  e.logicalKey == LogicalKeyboardKey.enter)) {
        //do something (01)
            return KeyEventResult.handled;
          }
          return KeyEventResult.ignored;
        },
        focusNode: FocusNode(canRequestFocus: false),
        child: MaterialButton(
          onPressed: () {
         //do something (02)
        },
          child: Text("Click Here"),
  ));`

**Comment by maheshmnj** [comment]
Thanks for the info, I am unable to reproduce the error on Pressing "Enter" on windows macihine also we do not have the reproducible device to replicate the issue. Labeling this issue for further investigation from the team.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter(final BuildContext context) {
    showDialog(
        context: context,
        builder: (context) => AlertDialog(
              actions: [
                TextButton(
                  onPressed: () {
                    Navigator.pop(context);
                    setState(() {
                      _counter++;
                    });
                  },
                  child: const Text('OK'),
                )
              ],
              content: Text('Counter: $_counter.'),
            ));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Focus(
                onKeyEvent: (node, e) {
                  if (e is RawKeyUpEvent &&
                      (e.logicalKey == LogicalKeyboardKey.select ||
                          e.logicalKey == LogicalKeyboardKey.enter)) {
                    //do something (01)
                    return KeyEventResult.handled;
                  }
                  return KeyEventResult.ignored;
                },
                focusNode: FocusNode(canRequestFocus: false),
                child: MaterialButton(
                  onPressed: () {
                    //do something (02)
                  },
                  child: Text("Click Here"),
                )),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _incrementCounter(context),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586],
    locale en-US)
    • Flutter version 2.10.4 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.82      
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.30     

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[√] Flutter (Channel master, 2.13.0-0.0.pre.311, on Microsoft Windows [Version
    10.0.19044.1586], locale en-US)
    • Flutter version 2.13.0-0.0.pre.311 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a4bf257bc (5 days ago), 2022-03-30 07:40:51 +0200
    • Engine revision 0e7773bcca
    • Dart version 2.17.0 (build 2.17.0-249.0.dev)
    • DevTools version 2.11.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows        
      [Version 10.0.19044.1586]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome
      100.0.4896.60
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge
      99.0.1150.30

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!```
</details>

**Comment by maheshmnj** [comment]
cc: @dkwingsmt

**Comment by ZoubairDaddow** [comment]
I ran the application on [ TX 3 mini](https://www.amazon.com/TX3-Android-Amlogic-Decoding-2-4GHz/dp/B075N78F8J)  real device 

and this error appear

```

Exception has occurred.
_AssertionError ('package:flutter/src/services/raw_keyboard.dart': Failed assertion: line 685 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty': Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#aca73(logicalKey: LogicalKeyboardKey#0050c(keyId: "0x10000050c", keyLabel: "Select", debugName: "Select"), physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName: "Control Right"), repeat: false) and its data: RawKeyEventDataAndroid#92581(flags: 8, codePoint: 0, plainCodePoint: 0, keyCode: 23, scanCode: 97, metaState: 0))


```
![image](https://user-images.githubusercontent.com/32312290/161700641-dce53ca7-3dad-472c-baaa-fbfae0eef283.png)


and please note this issue appears just on Select or Enter

**Comment by devius** [comment]
> I ran the application on [ TX 3 mini](https://www.amazon.com/TX3-Android-Amlogic-Decoding-2-4GHz/dp/B075N78F8J) real device
> 
> and this error appear
> 
> ```
> 
> Exception has occurred.
> _AssertionError ('package:flutter/src/services/raw_keyboard.dart': Failed assertion: line 685 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty': Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#aca73(logicalKey: LogicalKeyboardKey#0050c(keyId: "0x10000050c", keyLabel: "Select", debugName: "Select"), physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName: "Control Right"), repeat: false) and its data: RawKeyEventDataAndroid#92581(flags: 8, codePoint: 0, plainCodePoint: 0, keyCode: 23, scanCode: 97, metaState: 0))
> ```
> 
> ![image](https://user-images.githubusercontent.com/32312290/161701347-9e5f18eb-cef9-4220-9562-884f56cc9a2e.png)
> 
> and please note this issue appears just on Select or Enter

Can you fix this error?

**Comment by FrancXPT** [comment]
@devius You can check a Workaround a found https://github.com/flutter/flutter/issues/65233#issuecomment-1364115011

**Comment by selvam920** [comment]
is there any fix for this?

**Comment by daddowzoubair** [comment]
@selvam920 
use onKey method
in focusNode widget

**Comment by selvam920** [comment]
I used focusedscope onkey

**Comment by rounce** [comment]
> is there any fix for this?

Workaround https://github.com/flutter/flutter/issues/65233#issuecomment-1381425823 works just fine.

**Comment by selvam920** [comment]
I faced in windows

**Comment by selvam920** [comment]
Another exception was thrown: Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#98957(logicalKey: LogicalKeyboardKey#df100(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#ed430(usbHidUsage: "0x000700e1", debugName: "Shift Left"), repeat: false) and its data: RawKeyEventDataWindows#be464(keyCode: 160, scanCode: 42, characterCodePoint: 0, modifiers: 0)

**Comment by rounce** [comment]
> I faced in windows

Try workaround https://github.com/flutter/flutter/issues/65233#issuecomment-1364115011.

**Comment by maurovanetti** [comment]
A similar error was detected by us when using a USB barcode scanner (it's Newland FR50 Pearl):

```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#6174e(logicalKey: LogicalKeyboardKey#df100(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#ed430(usbHidUsage: "0x000700e1", debugName: "Shift Left"), repeat: false) and its data: RawKeyEventDataWindows#debed(keyCode: 160, scanCode: 42, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 695 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:695:7)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1018:30)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#6      _invoke2 (dart:ui/hooks.dart:202:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:135:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by mariamhas** [comment]
thanks for flagging

**Comment by Renzo-Olivares** [comment]
cc @dkwingsmt do you have any thoughts on this issue?

**Comment by cbachiller** [comment]
> Newland

I have this error with usb barcode scanner too...
```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#afe07(logicalKey: LogicalKeyboardKey#df100(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#ed430(usbHidUsage: "0x000700e1", debugName: "Shift Left"), repeat: false) and its data: RawKeyEventDataWindows#12d5f(keyCode: 160, scanCode: 42, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 695 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:695:7)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1050:30)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:223:49)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#6      _invoke2 (dart:ui/hooks.dart:344:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:135:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:722:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by Mapashito1** [comment]
> A similar error was detected by us when using a USB barcode scanner (it's Newland FR50 Pearl):
> 
> ```
> ======== Exception caught by services library ======================================================
> The following assertion was thrown during a platform message callback:
> Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#6174e(logicalKey: LogicalKeyboardKey#df100(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#ed430(usbHidUsage: "0x000700e1", debugName: "Shift Left"), repeat: false) and its data: RawKeyEventDataWindows#debed(keyCode: 160, scanCode: 42, characterCodePoint: 0, modifiers: 0)
> 'package:flutter/src/services/raw_keyboard.dart':
> Failed assertion: line 695 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'
> 
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
>   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
> 
> When the exception was thrown, this was the stack: 
> #2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:695:7)
> #3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1018:30)
> #4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
> #5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
> #6      _invoke2 (dart:ui/hooks.dart:202:13)
> #7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
> #8      _Channel.push (dart:ui/channel_buffers.dart:135:31)
> #9      ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17)
> #10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22)
> #11     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
> (elided 2 frames from class _AssertionError)
> ====================================================================================================
> ```

I have same error with usb barcode scanner too...
```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#afe07(logicalKey: LogicalKeyboardKey#df100(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#ed430(usbHidUsage: "0x000700e1", debugName: "Shift Left"), repeat: false) and its data: RawKeyEventDataWindows#12d5f(keyCode: 160, scanCode: 42, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 695 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:695:7)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1050:30)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:223:49)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#6      _invoke2 (dart:ui/hooks.dart:344:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:135:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:722:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by itaginsexordium** [comment]
I get the same error but I have a custom IR remote control on the console that gives


```console
[log] ================================
[log] key down: LogicalKeyboardKey#4999d(keyId: "0x10000050c", keyLabel: "Select", debugName: "Select")
[log] character: null
[log] physical: PhysicalKeyboardKey#f5c25(usbHidUsage: "0x000700e4", debugName: "Control Right")
[log] ================================
```



```Exception has occurred.
_AssertionError ('package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 522 pos 11: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#c029a(physicalKey: PhysicalKeyboardKey#f5c25(usbHidUsage: "0x000700e4", debugName: "Control Right"), logicalKey: LogicalKeyboardKey#d24f3(keyId: "0x200000101", keyLabel: "Control Right", debugName: "Control Right"), character: null, timeStamp: 0:01:32.010261, synthesized))
```

sample 
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

// ------------------- DpadContainer -------------------
class DpadContainer extends StatefulWidget {
  final VoidCallback onEnter;
  final ValueChanged<bool>? onFocusChange;
  final Widget child;
  final bool autofocus;

  const DpadContainer({
    super.key,
    required this.onEnter,
    required this.child,
    this.onFocusChange,
    this.autofocus = false,
  });

  @override
  State<DpadContainer> createState() => _DpadContainerState();
}

class _DpadContainerState extends State<DpadContainer> {
  late FocusNode _focusNode;
  bool _isFocused = false;

  @override
  void initState() {
    super.initState();
    _focusNode = FocusNode();
    _focusNode.addListener(_handleFocusChange);
  }

  void _handleFocusChange() {
    final focused = _focusNode.hasFocus;
    if (_isFocused != focused) {
      setState(() => _isFocused = focused);
      widget.onFocusChange?.call(focused);
    }
  }

  KeyEventResult _handleKey(FocusNode node, KeyEvent event) {
    if (event is KeyDownEvent) {
      final logicalKey = event.logicalKey;

      if (logicalKey == LogicalKeyboardKey.enter ||
          logicalKey == LogicalKeyboardKey.space ||
          logicalKey == LogicalKeyboardKey.select) {
        widget.onEnter();
        return KeyEventResult.handled;
      }
    }

    return KeyEventResult.ignored;
  }

  @override
  void dispose() {
    _focusNode.removeListener(_handleFocusChange);
    _focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Focus(
      focusNode: _focusNode,
      autofocus: widget.autofocus,
      onKeyEvent: _handleKey,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 120),
        curve: Curves.easeOut,
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(8),
          boxShadow: _isFocused
              ? [
                  BoxShadow(
                    color: Theme.of(context)
                        .colorScheme
                        .primary
                        .withOpacity(0.4),
                    blurRadius: 16,
                    spreadRadius: 2,
                  ),
                ]
              : [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.15),
                    blurRadius: 6,
                    spreadRadius: 1,
                  ),
                ],
        ),
        child: widget.child,
      ),
    );
  }
}

// ------------------- Приложение -------------------
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DpadContainer Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  void _onEnter(int index) {
    debugPrint('Enter pressed on item $index');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[300],
      appBar: AppBar(title: const Text('DpadContainer Debug')),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: List.generate(3, (index) {
            return Padding(
              padding: const EdgeInsets.symmetric(vertical: 8),
              child: DpadContainer(
                autofocus: index == 0,
                onEnter: () => _onEnter(index),
                onFocusChange: (focused) =>
                    debugPrint('Item $index focused: $focused'),
                child: SizedBox(
                  width: 200,
                  height: 60,
                  child: Center(
                    child: Text(
                      'Item $index',
                      style: const TextStyle(fontSize: 20),
                    ),
                  ),
                ),
              ),
            );
          }),
        ),
      ),
    );
  }
}
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.35.2, on Ubuntu 24.04.2 LTS 6.14.0-27-generic, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2025.1.2)
[✓] VS Code (version 1.103.2)
[✓] Connected device (3 available)
[✓] Network resources
```
