### ISSUE TITLE
Flutter error: Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by kitzsable** [flutter/flutter#101333]
Hi! We received several reports of FlutterError: Unsupported operation: Infinity or NaN toInt in the getMinChildIndexForScrollOffset method of the RenderSliverFixedExtentBoxAdaptor class on our app.

<details><summary>Stack Trace:</summary>

```
#0 _Double.toInt (dart:core-patch/double.dart:219)
#1 _Double.round (dart:core-patch/double.dart:182)
#2 RenderSliverFixedExtentBoxAdaptor.getMinChildIndexForScrollOffset (package:flutter/src/rendering/sliver_fixed_extent_list.dart:70)
#3 RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:192)
#4 RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#5 RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137)
#6 _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167)
#7 RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#8 RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510)
#9 RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580)
#10 RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489)
#11 RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713)
#12 PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885)
#13 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453)
#14 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883)
#15 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319)
#16 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143)
#17 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080)
#18 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
#19 _rootRun (dart:async/zone.dart:1428)
#20 _CustomZone.run (dart:async/zone.dart:1328)
#21 _CustomZone.runGuarded (dart:async/zone.dart:1236)
#22 _invoke (dart:ui/hooks.dart:166)
#23 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
#24 _drawFrame (dart:ui/hooks.dart:129)
```
</details>

<details><summary>Output of flutter doctor -v:</summary>

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.2.1 21D62 darwin-arm, locale
    ru-RU)
    • Flutter version 2.5.2 at /Users/dns/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (6 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dns/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.3, Build version 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.75

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @kitzsable, you appear to be on an older version of flutter, can you upgrade to the latest version of `stable` (2.10.4) to see if you're still getting reports on this? 

Also, are you able to reproduce this locally? and what devices are experiencing this issue?

Thank you

**Comment by kitzsable** [comment]
@danagbemava-nc Unfortunately we can't reproduce this issue locally and we don't have the ability to update Flutter. We found this problem in the logs of our application and cannot find out why it occurs

**Comment by maheshmnj** [comment]
Looks like a duplicate of https://github.com/flutter/flutter/issues/77908
