### ISSUE TITLE
[google_maps_flutter_web] [repro] Maps cannot be retrieved before calling buildView!

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#101387]
Essentially the same as the now closed  https://github.com/flutter/flutter/issues/97913

I took the code furnished by OP and put it in a `TabBarView` like he explained.

# Repro

https://github.com/cedvdb/flutter_repros/tree/google_map_init

 1. get the correct branch `google_map_init`
 2. in index.html replace `YOUR_API_KEY_HERE` with a valid google map api key
 3.  run project
 4. go to third tab, back to second, back to third and back to second.
 
 
 the error will appear

**Comment by cedvdb** [comment]
@darshankawar pinging you since you originally tried to reproduce

**Comment by maheshmnj** [comment]
Hi @cedvdb, Thanks for filing the issue. I am able to reproduce the issue on stable and the master channel. Reproducible steps can be found in the [original post](https://github.com/flutter/flutter/issues/101387#issue-1193759930). The app continues to work but the error is thrown when switching the tabs.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late final TabController _tabController;

  @override
  void initState() {
    _tabController = TabController(length: 3, vsync: this);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        bottom: TabBar(
          controller: _tabController,
          tabs: const [
            Tab(icon: Icon(Icons.directions_car)),
            Tab(icon: Icon(Icons.directions_transit)),
            Tab(icon: Icon(Icons.directions_bike)),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          Container(
            color: Colors.green,
          ),
          Container(
            color: Colors.blue,
          ),
          const MapLocationPicker(),
        ],
      ),
    );
  }
}


typedef OnPositionUpdated = void Function(LatLng newPosition);

class MapLocationPicker extends StatefulWidget {
  final LatLng? initialPosition;
  final OnPositionUpdated? onPositionUpdated;
  final bool readOnly;

  const MapLocationPicker({
    this.initialPosition,
    this.onPositionUpdated,
    this.readOnly = true,
    Key? key,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => _MapLocationPickerState();
}

class _MapLocationPickerState extends State<MapLocationPicker> {
  final String _pickedLocationMarkerId = "pickedLocation";

  final _defaultPosition = const CameraPosition(
    target: LatLng(41.99, 21.42),
    zoom: 7.2373,
  );

  final double _defaultPickedLocationZoom = 14.4746;

  late GoogleMapController _mapController;
  bool _isMapCreated = false;

  LatLng? _position;

  @override
  void initState() {
    super.initState();

    _position = initialPosition;
  }

  @override
  void dispose() {
    if (_isMapCreated) {
      _mapController.dispose();
    }

    super.dispose();
  }

  void _updatePosition(LatLng newPosition) {
    if (readOnly) {
      return;
    }

    onPositionUpdated?.call(newPosition);

    if (mounted) {
      setState(() {
        _position = newPosition;
      });
    }
  }

  Set<Marker> _getMarkers() {
    return {
      if (_position != null)
        Marker(
          draggable: !readOnly,
          onDragEnd: _updatePosition,
          markerId: MarkerId(_pickedLocationMarkerId),
          position: _position!,
          infoWindow: InfoWindow(
            title: "${_position!.latitude}, ${_position!.longitude}",
          ),
        ),
    };
  }

  @override
  Widget build(BuildContext context) {
    return GoogleMap(
      initialCameraPosition: _defaultPosition,
      onMapCreated: (GoogleMapController controller) {
        if (mounted) {
          setState(() {
            _mapController = controller;
            _isMapCreated = true;

            if (_position != null) {
              controller.animateCamera(CameraUpdate.newCameraPosition(
                CameraPosition(
                  target: _position!,
                  zoom: _defaultPickedLocationZoom,
                ),
              ));
            }
          });
        }
      },
      markers: _getMarkers(),
      onTap: (LatLng? location) {
        if (!readOnly && _position == null && location != null) {
          _updatePosition(location);
        }
      },
    );
  }

  LatLng? get initialPosition => widget.initialPosition;
  OnPositionUpdated? get onPositionUpdated => widget.onPositionUpdated;
  bool get readOnly => widget.readOnly;
}

```
</details> 


<details>
<summary>logs</summary>

```
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:59629/7ZfmQfumpzg=/ws
Debug service listening on ws://127.0.0.1:59629/7ZfmQfumpzg=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:59629/7ZfmQfumpzg=/ws
You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started
Error: Assertion failed:
controller != null
"Maps cannot be retrieved before calling buildView!"
    at Object.throw_ [as throw] (http://localhost:59587/dart_sdk.js:5067:11)
    at Object.assertFailed (http://localhost:59587/dart_sdk.js:4992:15)
at google_maps_flutter_web.GoogleMapsPlugin.new.[_map] (http://localhost:59587/packages/google_maps_flutter_web/src/types.dart.lib.js:239:39)
at google_maps_flutter_web.GoogleMapsPlugin.new.dispose (http://localhost:59587/packages/google_maps_flutter_web/src/types.dart.lib.js:396:17)
at google_maps_flutter.GoogleMapController.__.dispose (http://localhost:59587/packages/google_maps_flutter/google_maps_flutter.dart.lib.js:259:71)
at google_maps_flutter._GoogleMapState.new._disposeController (http://localhost:59587/packages/google_maps_flutter/google_maps_flutter.dart.lib.js:797:20)
    at _disposeController.next (<anonymous>)
    at http://localhost:59587/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:59587/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:59587/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:59587/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:59587/dart_sdk.js:35969:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59587/dart_sdk.js:35698:27)
    at Object._microtaskLoop (http://localhost:59587/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:59587/dart_sdk.js:40714:13)
    at http://localhost:59587/dart_sdk.js:36191:9
Error: Assertion failed:
controller != null
"Maps cannot be retrieved before calling buildView!"
    at Object.throw_ [as throw] (http://localhost:59587/dart_sdk.js:5067:11)
    at Object.assertFailed (http://localhost:59587/dart_sdk.js:4992:15)
at google_maps_flutter_web.GoogleMapsPlugin.new.[_map] (http://localhost:59587/packages/google_maps_flutter_web/src/types.dart.lib.js:239:39)
at google_maps_flutter_web.GoogleMapsPlugin.new.dispose (http://localhost:59587/packages/google_maps_flutter_web/src/types.dart.lib.js:396:17)
at google_maps_flutter.GoogleMapController.__.dispose (http://localhost:59587/packages/google_maps_flutter/google_maps_flutter.dart.lib.js:259:71)
at google_maps_flutter._GoogleMapState.new._disposeController (http://localhost:59587/packages/google_maps_flutter/google_maps_flutter.dart.lib.js:797:20)
    at _disposeController.next (<anonymous>)
    at http://localhost:59587/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:59587/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:59587/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:59587/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:59587/dart_sdk.js:35969:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59587/dart_sdk.js:35698:27)
    at Object._microtaskLoop (http://localhost:59587/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:59587/dart_sdk.js:40714:13)
    at http://localhost:59587/dart_sdk.js:36191:9

```
</details>   

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.391, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.13.0-0.0.pre.391 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 08c46bcb58 (7 hours ago), 2022-04-05 22:24:05 -0400
    • Engine revision 45bedbe841
    • Dart version 2.17.0 (build 2.17.0-266.0.dev)
    • DevTools version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by cedvdb** [comment]
Okay so I investigated this a bit, and the example code in the repro I furnished (that was taken from another issue) is kind of wrong. because OP calls `controller.dispose` in the dispose method of the widget. Apparently you are not supposed to do that.

So first thing first, that should be documented with a better error or the method should be made private. 

Secondly in my case I was using an additional package `google_map_cluster_manager` that does the following: `await GoogleMapsFlutterPlatform.instance.getZoomLevel(mapId: mapId);`.

To resolve this I just had to check if the widget was mounted before calling cluster manager init.

There are still things inherently wrong here imo, because this happens too easily. Either this needs to be documented or the mapId should return a nullable which is null when the widget is unmounted.

**Comment by RoarGronmo** [comment]
Since this issue is still open, are there any advice how to avoid the error ?

**Comment by nzuqi** [comment]
Anyone with a work around? Related to [#97915](https://github.com/flutter/flutter/issues/97913)

**Comment by Yuya-Arashidani** [comment]
Same Error

**Comment by BenjiFarquhar** [comment]
I get this error on 2 separate apps. Seems to be a pervasive error.
