### ISSUE TITLE
Null check operator used on a null value exception

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#101499]
Our online app reports many exceptions when used null-safety, there is no useful stack information for these exceptions, these exceptions cannot be reproduced on development environment.

Do you have any suggestions about it? thanks.

```dart
Null check operator used on a null value
2
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
3
The following _CastError was thrown building Widget:
4
Null check operator used on a null value
5
When the exception was thrown, this was the stack:
6
#0      ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:3211)
7
#1      ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:3243)
8
#2      MultiChildRenderObjectElement.insertRenderObjectChild (package:flutter/src/widgets/framework.dart:6065)
9
#3      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5674)
10
#4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5365)
11
#5      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5986)
12
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3546)
13
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3311)
14
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4525)
15
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4194)
16
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4479)
17
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4474)
18
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3546)
19
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3311)
20
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4525)
21
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4194)
22
#16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4479)
23
#17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4474)
24
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3546)
25
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3311)
26
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4525)
27
#21     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4672)
28
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4194)
29
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4479)
30
#24     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4663)
31
#25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4474)
32
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3546)
33
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3311)
34
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4525)
35
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4194)
36
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4479)
37
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4474)
38
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3546)
39
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3311)
40
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4525)
41
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:4194)
42
#36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4479)
43
#37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4474)
44
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3546)
45
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3311)
46
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4525)
47
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:4194)
48
#42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4479)
49
#43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4474)
50
#44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3546)
51
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3311)
52
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4525)
53
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:4194)
54
#48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4479)
55
#49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4474)
56
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3546)
57
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3311)
58
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4525)
59
#53     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4672)
60
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4194)
61
#55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4479)
62
#56     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4663)
63
#57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4474)
64
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3546)
65
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3311)
66
#60     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5572)
67
#61     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6118)
68
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3298)
69
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4525)
70
#64     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4672)
71
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4194)
72
#66     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2694)
73
#67     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:893)
74
#68     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:322)
75
#69     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1176)
76
#70     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1114)
77
#71     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1030)
78
#75     _invoke (dart:ui/hooks.dart:204)
79
#76     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253)
80
#77     _drawFrame (dart:ui/hooks.dart:123)
81
(elided 3 frames from dart:async)


```

The framework version is **2.0.6-0.0.pre.315**
![origin_img_v2_922272d8-06ee-415d-906e-30daa0f754dg](https://user-images.githubusercontent.com/4476512/162187005-ab7ac499-f2a8-4dbb-a530-c061fe714960.jpg)

**Comment by maheshmnj** [comment]
Hi @wangying3426, Thanks for filing the issue. Can you please share a minimal code which reproduces these errors? However, You seem to be using the older version of flutter. Can you please try upgrading to the latest `stable 2.10.4` ?
