### ISSUE TITLE
Error: Bad state: Not connected to an application. Flutter web on (Safari browser)

### ISSUE THREAD

**Issue by PranayDosii** [flutter/flutter#101405]
I am using flutter web to develop our project. The project is running fine on Chrome, Firefox and other browsers but I am getting errors on the Safari browser it was working before the new update on mac. The version of my `Safari 15.4 (17613.1.17.1.13)`.  After getting the below error the site takes a long time to load.

<details>
<summary> console log </summary>

```

> Error: Bad state: Not connected to an application.
> Stack Trace:
> #0      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:259:13)
> #1      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:246:38)
> #2      _rootRunUnary (dart:async/zone.dart:1434:47)
> #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
> #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
> #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
> #7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
> #8      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
> #9      _rootRunUnary (dart:async/zone.dart:1442:13)
> #10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
> #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
> #13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
> #14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
> #15     _StreamController._add (dart:async/stream_controller.dart:648:7)
> #16     _StreamController.add (dart:async/stream_controller.dart:596:5)
> #17     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:730:21)
> #18     _rootRunUnary (dart:async/zone.dart:1434:47)
> #19     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
> #21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
> #22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
> #23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
> #24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
> #25     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:319:23)
> #26     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:218:46)
> #27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
> #28     _rootRunUnary (dart:async/zone.dart:1434:47)
> #29     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> #30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
> #31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
> #32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
> #33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
> #34     _StreamController._add (dart:async/stream_controller.dart:648:7)
> #35     _StreamController.add (dart:async/stream_controller.dart:596:5)
> #36     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
> #37     _rootRunUnary (dart:async/zone.dart:1442:13)
> #38     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> #39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
> #40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
> #41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
> #42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
> #43     _StreamController._add (dart:async/stream_controller.dart:648:7)
> #44     _StreamController.add (dart:async/stream_controller.dart:596:5)
> #45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1839:33)
> #46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
> #47     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
> #48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
> #49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
> #50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)

```

</details>

Flutter doctor 

```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.65.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability`

```

I have tried some sample sites of flutter 

[example_portfolio](https://tejrajkhanvilkar.github.io/portfolio/)
[flutter_gallery] (https://gallery.flutter.dev/#/)

I hope you will help me out.

**Comment by darshankawar** [comment]
@PranayDosii 
Thanks for the report. Using the example portfolio and running in safari browser, does it throw the exception consistently ?
I tried to run the gallery app on safari browser (Version 15.3 (17612.4.9.1.8), on which I didn't get the log you reported. Maybe this is another case of Safari's 15.4 version. I did notice that the loading the gallery app in safari browser does take a bit time to load.

Is there a way for you to check this on Safari's 15.3 version and see if your web project throws same error or not ?
Can you also provide a minimal code sample that can help to trigger the exception log ?

**Comment by PranayDosii** [comment]
I do not have access to The `Safari version (15.3)` but I am getting these logs which I have already shared. I am getting these logs when it is in debug mode and in release mode, it shows blank and take a longer time to load

**Comment by darshankawar** [comment]
> I am getting these logs

Do you get these logs while running your project or also with portfolio and gallery links you shared earlier ?

Can you also provide a minimal code sample that can help to trigger the exception log ?

**Comment by darshankawar** [comment]
@pranay289 assuming you are same as @PranayDosii , please provide updates on below questions asked earlier:

```
Do you get these logs while running your project or also with portfolio and gallery links you shared earlier ?

Can you also provide a minimal code sample that can help to trigger the exception log ?
```

**Comment by PranayDosii** [comment]
When I am using the below code I am getting this errors on `Safari`
`  </script>
  <script type="text/javascript">
    let usecanvaskit = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);// checking for chromium based browser.
    if (usecanvaskit) {
      console.log("Using canvaskit renderer");
      window.flutterWebRenderer = "canvaskit";
    } else {
      window.flutterWebRenderer = "html";
    }
  </script>`
`There are too many active WebGL contexts on this page, the oldest context will be lost.`

**Comment by darshankawar** [comment]
@PranayDosii 
I think you are hitting https://github.com/flutter/flutter/issues/75914, so please follow-up in it for further updates.
Closing this as a duplicate.

**Comment by pranay289** [comment]
Thanks for your feedback.
