### ISSUE TITLE
Ubuntu 22.04 running flutter app: Gdk message: 14:51:20.328: Error 71 (Protocol error) dispatch to Wayland display.

### ISSUE THREAD

**Issue by AndromedaX7** [flutter/flutter#101407]
## Steps to Reproduce

```
运行 flutter run -d linux:
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Gdk-Message: 14:53:47.937: Error 71 (协议错误) dispatching to Wayland display.
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on Linux.

操作系统:Ubuntu Jammy Jellyfish (development branch)   .
窗口类型:Wayland
Gnome版本:42.0
```

```
`flutter doctor -v `:
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel master, 2.13.0-0.0.pre.391, on Ubuntu Jammy Jellyfish (development branch)
    5.15.0-25-generic, locale zh_CN.UTF-8)
    • Flutter version 2.13.0-0.0.pre.391 at /home/juzi/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 08c46bcb58 (5 小时前), 2022-04-05 22:24:05 -0400
    • Engine revision 45bedbe841
    • Dart version 2.17.0 (build 2.17.0-266.0.dev)
    • DevTools version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/juzi/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at:
      /home/juzi/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at
      /home/juzi/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu Jammy Jellyfish (development branch) 5.15.0-25-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
• No issues found!

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>
使用 `flutter create ` 创建的原始代码。

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @AndromedaX7, Thanks for filing the issue. Are you seeing the error with a newly created flutter project in wayland session?

**Comment by AndromedaX7** [comment]
The same code can be run on Ubuntu22.04 x11 (translate by google)
(同样的代码可以运行在 Ubuntu22.04 x11 上面)
As follows, I think it might be useful：
(如下，我觉得可能有用)

```
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +1 ms] Error launching application on Linux.
[   +1 ms] "flutter run" took 2,843ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```

**Comment by AndromedaX7** [comment]
I use the same hard disk and run it on a pc, and the above problem occurs. It runs normally on a Vmware virtual machine.
I am trying more physical machines.
Similarly, the newly created Vmware virtual machine can also run normally.

**Comment by maheshmnj** [comment]
Thanks for the info @AndromedaX7, Can you check if switching to latest `stable 2.10.4` helps fix the issue? You can do so by running 
```
flutter channel stable
flutter upgrade
```

**Comment by AndromedaX7** [comment]
I followed the above procedure and got the same error.
The problem is also reproduced on other PCs.

Flutter is already up to date on channel stable
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter
Framework • revision c860cba910 (13 天前) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

**Comment by AndromedaX7** [comment]
I think it might be an issue with the Nvidia graphics card driver, as I run it successfully on a machine without an Nvidia graphics card.
On this machine, both the master branch and the stable branch work fine
![Screenshot from 2022-04-07 15-36-00](https://user-images.githubusercontent.com/38732113/162147113-5032fb7c-560b-4b65-9fcf-42ad6fe8c868.png)

**Comment by AndromedaX7** [comment]
This pc and Xiaomi Ruby2019 will have this problem. They both have Nidia graphics cards.
![image](https://user-images.githubusercontent.com/38732113/162150180-3fc39e45-07b5-43b5-9f2c-4ffecf55fbbf.png)

**Comment by maheshmnj** [comment]
> I think it might be an issue with the Nvidia graphics card driver, as I run it successfully on a machine without an Nvidia graphics card.

Thanks for your research @AndromedaX7, I am going to close this issue then, Feel free to write back or file a new issue, if you see this issue on a machine without Nvidia graphics card.
