### ISSUE TITLE
RefreshIndicator keeps rebuilding widgets

### ISSUE THREAD

**Issue by lodisy** [flutter/flutter#101576]
## Steps to Reproduce

1. Build a simple listview with listview.builder
2. Wrap it with RefreshIndicator, add a button at bottom, both with the same fetching data method
3. Click the button to refresh the list, log it
4. Pull to refresh the list, log it
5. The logs show that the state keeps changing when with Refreshindicator, and the ui is also laggy
6. Details seen in the logs

**Expected results:** 

Should perform the same as the load function is the same

**Actual results:** 

The ui is laggy and the logs show state keeps changing

<details>
<summary>Code sample</summary>

```dart
return RefreshIndicator(
      onRefresh: () async {
        logger.d("Refresh");
        return ref.read(usersNotifierProvider.notifier).getUsersFromGraphql(
              variables: VariablesQueryUsers(
                take: 10,
              ),
            );
      },
      child: Column(
        children: [
          if (_users.isNotEmpty)
            Expanded(
              child: ListView.builder(
                controller: _scrollController,
                physics: const AlwaysScrollableScrollPhysics(),
                itemCount: _users.length,
                itemBuilder: (context, index) {
                  final _user = _users[index];

                  return ListTile(
                    shape: const StadiumBorder(),
                    leading: CircleAvatar(
                      child: CachedNetworkImage(
                        imageUrl:
                            'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80',
                        placeholder: (context, url) => SvgPicture.asset(
                          'assets/icons/fallback_avatar.svg',
                          width: 36,
                        ),
                        errorWidget: (context, url, error) => SvgPicture.asset(
                          'assets/icons/fallback_avatar.svg',
                          width: 36,
                        ),
                      ),
                    ),
                    title: Text(
                      _user.name.toUpperCase(),
                    ).bold(),
                    subtitle: Text('@${_user.username}'),
                    trailing: Text(
                      format(_user.createdAt),
                    ),
                    onTap: () async => context.router.push(
                      UserDetailRoute(id: _user.id),
                    ),
                    onLongPress: () {},
                  );
                },
                //   itemCount: _userCount,
              ),
            ),
          Center(
            child: ElevatedButton(
              onPressed: () async {
                logger.d("Clicked");
                return ref
                    .read(usersNotifierProvider.notifier)
                    .getUsersFromGraphql(
                      variables: VariablesQueryUsers(
                        take: 10,
                      ),
                    );
              },
              child: const Text('Load'),
            ),
          ),
        ],
      ),
    );
```

</details>

<details>
  <summary>Logs</summary>

**Clicked with button:**
![Screenshot 2022-04-08 at 14 48 56](https://user-images.githubusercontent.com/8101584/162438717-5b4d2c85-42b8-4181-b3e8-bec758733548.jpg)

```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[        ] flutter: │ #0   UsersPage.build.<anonymous closure> (package:admin_flutter/core/user/view/users_page.dart:134:24)
[        ] flutter: │ #1   UsersPage.build.<anonymous closure> (package:admin_flutter/core/user/view/users_page.dart:133:26)
[        ] flutter:
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] flutter: │ 🐛 Clicked
[        ] flutter:
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[  +10 ms] flutter:
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[        ] flutter: │ #0   graphqlProvider.<anonymous closure> (package:admin_flutter/config/app_graphql.dart:9:10)
[   +6 ms] flutter: │ #1   ProviderFamily.create.<anonymous closure> (package:riverpod/src/provider/base.dart:297:23)
[        ] flutter:
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] flutter: │ 🐛 GraphQL Client initialized
[        ] flutter:
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[   +4 ms] flutter:
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[        ] flutter: │ #0   new TokenNotifier (package:admin_flutter/core/token/notifier/token_notifier.dart:13:12)
[        ] flutter: │ #1   tokenNotifierProvider.<anonymous closure>
(package:admin_flutter/core/token/notifier/token_notifier.dart:8:10)
[        ] flutter:
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] flutter: │ 🐛 TokenNotifier initialized
[        ] flutter:
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[  +92 ms] flutter:
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[   +7 ms] flutter: │ #0   Logger.didUpdateProvider (package:admin_flutter/main.dart:22:12)
[        ] flutter: │ #1   _runQuaternaryGuarded (package:riverpod/src/framework/container.dart:48:7)
[        ] flutter:
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] flutter: │ 🐛 {
[        ] flutter: │ 🐛   "provider": "StateNotifierProvider<TokenNotifier, TokenState>",
[   +3 ms] flutter: │ 🐛   "newValue": "TokenState(accessToken:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbDFnZTZpejgwMDAwNjNqbm1vOHdlZG04IiwiaWF0IjoxNjQ4OTc5Nzc1LCJleHAiOjE2NDg5ODAzNzV9
.9fKE4vhf1bF05Fc-thn2bWq85FNKM1Aj-JpEYtzz4hA, refreshToken:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbDFnZTZpejgwMDAwNjNqbm1vOHdlZG04IiwiaWF0IjoxNjQ4OTc5Nzc1LCJleHAiOjE2NDk1ODQ1NzV9
.BboA4PsNuou47ok78Ss8rGUaOnmAV_oxOEubasfzoJc)",
[        ] flutter: │ 🐛   "container": "Instance of 'ProviderContainer'"
[        ] flutter: │ 🐛 }
[        ] flutter:
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[ +215 ms] flutter:
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[   +1 ms] flutter: │ #0   Logger.didUpdateProvider (package:admin_flutter/main.dart:22:12)
[        ] flutter: │ #1   _runQuaternaryGuarded (package:riverpod/src/framework/container.dart:48:7)
[   +2 ms] flutter:
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[   +1 ms] flutter: │ 🐛 {
[        ] flutter: │ 🐛   "provider": "StateNotifierProvider<UsersNotifier, UsersState>",
[   +2 ms] flutter: │ 🐛   "newValue": "UsersState(users: [Instance of 'User', Instance of 'User'], allLoaded: false,
isUsersSelectable: false, selectedUsers: [])",
[        ] flutter: │ 🐛   "container": "Instance of 'ProviderContainer'"
[   +1 ms] flutter: │ 🐛 }
[   +2 ms] flutter:
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

With refreshindicator:

![Screenshot 2022-04-08 at 14 49 26](https://user-images.githubusercontent.com/8101584/162438844-dd670e46-88fe-4e4b-a5fc-a14d540486e7.jpg)

Unable to copy as the it sometimes keeps logging infinitely:

![Screenshot 2022-04-08 at 14 42 31](https://user-images.githubusercontent.com/8101584/162438057-2abe17ab-e835-42d5-a456-cf4deb2d31f1.jpg)

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@lodisy 
I see that you have used `provider` package which is third party. Does the same behavior occur without using that package code or any other third party code and just using core `RefreshIndicator` using `listView` ?

**Comment by lodisy** [comment]
> @lodisy I see that you have used `provider` package which is third party. Does the same behavior occur without using that package code or any other third party code and just using core `RefreshIndicator` using `listView` ?

Hello, probably it's because of the misuse of the riverpod.

As stated in docs: 

https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/WidgetRef/refresh.html

I would change the code to see if it helps.

**Comment by lodisy** [comment]
> > @lodisy I see that you have used `provider` package which is third party. Does the same behavior occur without using that package code or any other third party code and just using core `RefreshIndicator` using `listView` ?
> 
> Hello, probably it's because of the misuse of the riverpod.
> 
> As stated in docs:
> 
> https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/WidgetRef/refresh.html
> 
> I would change the code to see if it helps.

Yes, it is. 

You have to put the api call inside a FutureProvider, and call it with `ref.refresh` in the Refreshindicator's onRresh method.
