### ISSUE TITLE
NoSuchMethodError: method not found: 'toString' on null when calling StreamSubscription.cancel on Flutter Web

### ISSUE THREAD

**Issue by stx** [flutter/flutter#101647]
Rare issue seen in production on Flutter web when calling `myStreamSubscription.cancel()` in StatefulWidget `dispose()`. Appears to be a race condition and in release mode only. Not sure how to reproduce.

```
NoSuchMethodError: method not found: 'toString' on null
  at _StreamController._recordCancel(org-dartlang-sdk:///lib/html/dart2js/html_dart2js.dart:16962:34)
  at _ControllerSubscription._onCancel(org-dartlang-sdk:///lib/async/stream_controller.dart:722:30)
  at _BufferingStreamSubscription._cancel(org-dartlang-sdk:///lib/async/stream_controller.dart:850:12)
  at _BufferingStreamSubscription.cancel(org-dartlang-sdk:///lib/async/stream_impl.dart:252:5)
  at _ForwardingStreamSubscription._onCancel(org-dartlang-sdk:///lib/async/stream_impl.dart:198:7)
  at _BufferingStreamSubscription._cancel(org-dartlang-sdk:///lib/async/stream_pipe.dart:145:7)
  at _BufferingStreamSubscription.cancel(org-dartlang-sdk:///lib/async/stream_impl.dart:252:5)
```

## Logs

<details>
<summary>Logs</summary>

```
```

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-US)
    • Flutter version 2.10.4 at /Users/james/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Apollo (mobile) • da060dc78ac99566c39cb688206b34cb424a5ee1 • ios            • iOS 15.3.1 19D52
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 100.0.4896.75
    ! Error: Apollo is busy: Preparing the watch for development via Apollo. Xcode will continue when Apollo is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Labeling it for further investigation as there's no reproducible use case.

/cc @yjbanov

**Comment by nshahan** [comment]
@stx I'm just taking a look at the stack trace to see if anything jumps out at me. The top frame in the stack trace appears to be pointing to some code in the `Geoposition` API from dart:html. Is that used by your application?

**Comment by anliksim** [comment]
@stx I just had to troubleshoot a similar issue (`NoSuchMethodError: method not found: 'toString' on null`) although I do not have a useful stacktrace as this was captured by flutter web in release mode.

My app uses firebase firestore and I develop locally against the emulator. I could not reproduce the issue against the emulator, however I could reproduce it running locally in debug mode against my prod instance. This is likely due to the latency difference between the two causing the race.

The root cause of the issue was the order of my own code i.e. the call to `onClose` after popping the alert, which removes it from the widget tree (or deactivates as stated in the trace). Maybe this helps.

```dart
  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      actions: [
        TextButton(
          child: const Text('Close'),
          onPressed: () {
            Navigator.pop(context); // <--- pops this alert widget
            onClose(); // <--- should be called first
          },
        ),
      ],
      ...
    );
  }
```
The stack trace in debug mode:
```
Error: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
    at Object.throw_ [as throw] (http://localhost:49283/dart_sdk.js:5080:11)
at http://localhost:49283/packages/flutter/src/widgets/title.dart.lib.js:21196:21
at [_debugCheckStateIsActiveForAncestorLookup] (http://localhost:49283/packages/flutter/src/widgets/title.dart.lib.js:21199:26)
at framework.StatelessElement.new.findAncestorStateOfType (http://localhost:49283/packages/flutter/src/widgets/title.dart.lib.js:21244:62)
at Navigator.of (http://localhost:49283/packages/flutter/src/widgets/title.dart.lib.js:17641:61)
at Navigator.pop (http://localhost:49283/packages/flutter/src/widgets/title.dart.lib.js:17620:28)
at close_dialog._MyComponent.new.onClose (http://localhost:49283/packages/myproject/components/my_component.dart.lib.js:1038:31)
    at onClose.next (<anonymous>)
    at http://localhost:49283/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:49283/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:49283/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:49283/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:49283/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:49283/dart_sdk.js:35872:23)
    at http://localhost:49283/dart_sdk.js:36103:40
    at _RootZone.runUnary (http://localhost:49283/dart_sdk.js:40511:59)
    at _FutureListener.then.handleValue (http://localhost:49283/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:49283/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:49283/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:49283/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49283/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:49283/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:49283/dart_sdk.js:40784:13)
    at http://localhost:49283/dart_sdk.js:36261:9
```

**Comment by Justus-M** [comment]
I also had this on web in production reported by sentry, without a more detailed stack trace

**Comment by Justus-M** [comment]
I also had this on web in production reported by sentry, without a more detailed stack trace

**Comment by Elf80lvl** [comment]
For me the problem was in 'Shimmer' package. The issue was found only in web and only on iOS devices in release (tested in chrome and safari). The problem was solved after removing the widget with Shimmer library. Hope this helps someone who read this.
