### ISSUE TITLE
SIGSEGV in libflutter_engine.so kDartVmSnapshotInstructions on linux-x64

### ISSUE THREAD

**Issue by mzwtjp** [flutter/flutter#101637]
Seeing SIGSEGV while trying to run following embedder example on linux:

https://github.com/flutter/engine/blob/master/examples/glfw/README.md

SDK version is 2.10.4 (latest stable as of today), and linking with the matching
prebuilt libflutter_engine.so.
(Downloaded from https://storage.googleapis.com/flutter_infra_release/flutter/HASH/linux-x64/linux-x64-embedder,
where HASH is 57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab for SDK 2.10.4).

linux: linux environment on my Chromebook.
The sample is modified so that it uses software rendering, but I do not think it matters
(the engine is just trying to load app?)

Just after invoking run.sh (part of example), and I believe following error is happening while myapp app is being loaded?

```
[New Thread 0x7fffde77f700 (LWP 11103)]
[New Thread 0x7fffde67e700 (LWP 11104)]
[New Thread 0x7fffde27f700 (LWP 11105)]
flutter: Observatory listening on http://127.0.0.1:42679/y3A-0ASiv-0=/

Thread 2 "io.flutter.ui" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeca60700 (LWP 11096)]
0x00007ffff79922aa in ?? () from ./libflutter_engine.so
(gdb) bt
#0  0x00007ffff79922aa in ?? () from ./libflutter_engine.so
#1  0x00007ffff798faf3 in ?? () from ./libflutter_engine.so
#2  0x00007ffff799b427 in ?? () from ./libflutter_engine.so
#3  0x00007ffff7a80959 in ?? () from ./libflutter_engine.so
#4  0x00007ffff7a7fa28 in ?? () from ./libflutter_engine.so
#5  0x00007ffff7b65517 in kDartVmSnapshotInstructions ()
   from ./libflutter_engine.so
#6  0x00007fffe4102774 in ?? ()
#7  0x00007fffe803aef0 in ?? ()
#8  0x0000000001000002 in ?? ()
#9  0x00007fffeca5c818 in ?? ()
```

**Comment by mzwtjp** [comment]
Closing this for now.
Looks like my icudtl.dat (I copied it from somewhere) was wrong.  The file has build version / platform dependency?

I tried icudtl.dat from below, and now I no longer see this SIGSEGV.
(Even if it was from arm64 build archive, it did not matter.)

https://github.com/ardera/flutter-engine-binaries-for-arm/tree/main/arm64
