### ISSUE TITLE
【Crash!!!!!】After running flutter doctor I get the following error

### ISSUE THREAD

**Issue by kaission** [flutter/flutter#101677]
## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot resolve symbolic links, path = 'D:\SoftWare\develop\鍙嶇紪璇慭aapt.exe' (OS Error: 系统找不到指定的文件。
, errno = 2)

```
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:818:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:348:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:119:43)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:140:54)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#11     androidSdk (package:flutter_tools/src/globals_null_migrated.dart:34:39)
#12     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:184:29)
#13     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#14     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#15     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#16     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#18     deviceManager (package:flutter_tools/src/globals.dart:38:44)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:262:17)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

**Comment by kaission** [comment]
An error occurs when any flutter command is executed
![image](https://user-images.githubusercontent.com/20827437/162656054-7540819b-a4db-46c9-b5ec-681526a7d278.png)

**Comment by kaission** [comment]
Just delete the local aapt.exe
