### ISSUE TITLE
PointerInterceptor can't be screenshoted with canvaskit

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#101720]
When [`PointerInterceptor`](https://pub.dev/packages/pointer_interceptor) is in widget tree, calling `RenderRepaintBoundary.toImage()` throws on canvaskit. It works fine using the html renderer.

```
Uncaught (in promise) Error: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:251:49)
    at Object.nullCheck (operations.dart:528:63)
    at _engine.PlatformViewLayer.new.preroll (layer.dart:584:34)
    at _engine.OffsetEngineLayer.new.prerollChildren (layer.dart:125:12)
    at _engine.OffsetEngineLayer.new.preroll (layer.dart:357:9)
    at _engine.PhysicalShapeEngineLayer.new.prerollChildren (layer.dart:125:12)
    at _engine.PhysicalShapeEngineLayer.new.preroll (layer.dart:494:5)
    at _engine.OffsetEngineLayer.new.prerollChildren (layer.dart:125:12)
    at _engine.OffsetEngineLayer.new.preroll (layer.dart:357:9)
    at _engine.TransformEngineLayer.new.prerollChildren (layer.dart:125:12)
    at _engine.TransformEngineLayer.new.preroll (layer.dart:357:9)
    at _engine.RootLayer.new.prerollChildren (layer.dart:125:12)
    at _engine.RootLayer.new.preroll (layer.dart:114:19)
    at _engine.LayerTree.new.flatten (layer_tree.dart:67:15)
    at _engine.LayerScene.new.toImage (layer_scene_builder.dart:19:42)
    at layer$.OffsetLayer.new.toImage (layer.dart:1282:25)
    at toImage.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at layer$.OffsetLayer.new.toImage (layer.dart:1266:27)
    at proxy_box.RenderRepaintBoundary.new.toImage (proxy_box.dart:3204:23)
    at _takeScreenshot (bug_101720.dart:40:37)
    at _takeScreenshot.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at bug_101720.Bug101720.new.[_takeScreenshot] (bug_101720.dart:37:31)
    at bug_101720.dart:27:19
    at ink_well._InkResponseState.new.[_handleTap] (ink_well.dart:1005:21)
    at tap.TapGestureRecognizer.new.invokeCallback (recognizer.dart:198:24)
    at tap.TapGestureRecognizer.new.handleTapUp (tap.dart:613:48)
    at tap.TapGestureRecognizer.new.[_checkUp] (tap.dart:298:5)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (tap.dart:232:7)
    at tap.TapGestureRecognizer.new.handleEvent (recognizer.dart:563:9)
    at pointer_router.PointerRouter.new.[_dispatch] (pointer_router.dart:94:12)
    at pointer_router.dart:139:9
    at LinkedMap.new.forEach (linked_hash_map.dart:21:13)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (pointer_router.dart:137:17)
    at pointer_router.PointerRouter.new.route (pointer_router.dart:123:7)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (binding.dart:445:19)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:425:14)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:326:11)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (binding.dart:380:7)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (binding.dart:344:5)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (binding.dart:302:7)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (binding.dart:285:32)
    at Object.invoke1 (platform_dispatcher.dart:1118:13)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (platform_dispatcher.dart:185:5)
    at _engine.PointerBinding.__.[_onPointerData] (pointer_binding.dart:130:39)
    at pointer_binding.dart:543:18
    at pointer_binding.dart:496:21
    at loggedHandler (pointer_binding.dart:210:16)
```

## Steps to Reproduce

Add pointer_interceptor to dependencies 

```
flutter pub add pointer_interceptor:0.9.3
```

Run the code below with

```bash
flutter run -d chrome --web-renderer=canvaskit
````

Then press the "Take screenshot" button

```dart
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:pointer_interceptor/pointer_interceptor.dart';

void main() {
  runApp(Bug101720());
}

final _repaintBoundaryKey = GlobalKey<ScaffoldState>();

class Bug101720 extends StatelessWidget {
  const Bug101720({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: RepaintBoundary(
        key: _repaintBoundaryKey,
        child: Scaffold(
          body: Center(
            child: PointerInterceptor(
              child: ElevatedButton(
                child: Text('Take screenshot'),
                onPressed: () {
                  _takeScreenshot();
                },
              ),
            ),
          ),
        ),
      ),
    );
  }

  Future<void> _takeScreenshot() async {
    final canvas = _repaintBoundaryKey.currentContext?.findRenderObject()
        as RenderRepaintBoundary?;
    final _screenshot = await canvas!.toImage();
    final bytes = await _screenshot.toByteData(format: ImageByteFormat.png);
    print('Screenshot is ${bytes!.lengthInBytes} bytes');
  }
}
```

## Expected behavior:

The size of the image is printed to console. This is working for macOS and web (html renderer/ chrome 100)

## Actual behavior:

The app crashes with the exception above

## Relevant code

https://github.com/flutter/engine/blob/a624077dc4faef25ac9a510b2acd6db72d139cb7/lib/web_ui/lib/src/engine/canvaskit/layer.dart#L592-L602

## Additional information

[✓] Flutter (Channel master, 2.13.0-0.0.pre.486, on macOS 12.1 21C52 darwin-arm, locale en-DE)
    • Flutter version 2.13.0-0.0.pre.486 at /opt/homebrew/Caskroom/flutter/2.5.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6b461de012 (6 minutes ago), 2022-04-11 14:01:04 -0700
    • Engine revision 32a2cab5d1
    • Dart version 2.18.0 (build 2.18.0-10.0.dev)
    • DevTools version 2.12.2

I also tested it with Flutter 2.10 with the same result. I suspect it was never working.

**Comment by danagbemava-nc** [comment]
Issue is reproducible using the `canvaskit` renderer on `web`. I tested on `macOS` and it worked just fine. 

For the `html`-renderer, I ran into https://github.com/flutter/flutter/issues/49857 whether `pointer_interceptor` was in the tree or not.  Without `pointer_interceptor` in the widget tree, it works just fine on `canvaskit`. 

<details>
<summary>logs</summary>

[canvaskit_log.txt](https://github.com/flutter/flutter/files/8471500/canvaskit_log.txt)
[canvaskit_no_pointer_interceptor.txt](https://github.com/flutter/flutter/files/8471533/canvaskit_no_pointer_interceptor.txt)
[html_log.txt](https://github.com/flutter/flutter/files/8471502/html_log.txt)
[macos_log.txt](https://github.com/flutter/flutter/files/8471503/macos_log.txt)

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.498, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.498 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f34db33c5e (4 hours ago), 2022-04-12 00:49:09 -0400
    • Engine revision 42ada6fde3
    • Dart version 2.18.0 (build 2.18.0-10.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by yjbanov** [comment]
We may have broken it when we introduced non-painting platform views. cc @hterkelsen

**Comment by passsy** [comment]
Just SEO optimization. This `Uncaught TypeError: Cannot read properties of null (reading 'toString')` is shown when getting this error in profile mode on the current `master (829bddf)`.

```
// core_patch.dart:243
Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at PlatformViewLayer0.preroll$2 (layer.dart:584:32)
    at OffsetEngineLayer.prerollChildren$2 (layer.dart:125:7)
    at OffsetEngineLayer.preroll$2 (layer.dart:357:9)
    at OffsetEngineLayer.prerollChildren$2 (layer.dart:125:7)
    at OffsetEngineLayer.preroll$2 (layer.dart:357:9)
    at OffsetEngineLayer.prerollChildren$2 (layer.dart:125:7)
    at OffsetEngineLayer.preroll$2 (layer.dart:357:9)
    at OffsetEngineLayer.prerollChildren$2 (layer.dart:125:7)
    at OffsetEngineLayer.preroll$2 (layer.dart:357:9)
    at TransformEngineLayer.prerollChildren$2 (layer.dart:125:7)
```

**Comment by hterkelsen** [comment]
This can be fixed by making the rendering of Platform Views a no-op when `viewEmbedder` is not provided (as in the case of doing a screenshot).

**Comment by passsy** [comment]
PlatformViews also don't render on Android and iOS (basically a no-op by default), but it crashes for canvaskit. The same behavior as on iOS/Android would be much better than a hard crash.
