### ISSUE TITLE
[path_provider_android][path_provider_ios]: MissingPluginException on `2.0.12` and `2.0.7` respectively

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#101897]
Caught this when using the latest version of `cached_network_image`, which uses `flutter_cache_manager`, which uses `path_provider`, which uses `path_provider_android` and `path_provider_ios`.
Does not occur in `2.0.11` of `path_provider_android` and `2.0.7` of `path_provider_ios`.

Exception:
```

MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      getTemporaryDirectory (package:path_provider/path_provider.dart:55:24)
<asynchronous suspension>
#2      IOFileSystem.createDirectory (package:flutter_cache_manager/src/storage/file_system/file_system_io.dart:15:19)
<asynchronous suspension>

MissingPluginException(No implementation found for method getApplicationSupportDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      getApplicationSupportDirectory (package:path_provider/path_provider.dart:77:24)
<asynchronous suspension>
#2      CacheObjectProvider._getPath (package:flutter_cache_manager/src/storage/cache_info_repositories/cache_object_provider.dart:196:20)
<asynchronous suspension>
#3      CacheObjectProvider.open (package:flutter_cache_manager/src/storage/cache_info_repositories/cache_object_provider.dart:28:16)
<asynchronous suspension>
#4      CacheStore._getCacheDataFromDatabase (package:flutter_cache_manager/src/cache_store.dart:115:22)
<asynchronous suspension>
```

The culprit seems to be: https://github.com/flutter/plugins/pull/4912

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
    • Flutter version 2.10.3 at /Users/viren.khatri/fvm/versions/2.10.3
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 7e9793dee1 (6 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/viren.khatri/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • HD1901 (mobile) • b25e09dd • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by stuartmorgan** [comment]
That's the wrong channel name, which means Dart registration hasn't run. Is this in an isolate?

**Comment by werainkhatri** [comment]
> Is this in an isolate?

No
Its a module injected into an existing android app via add2app.
PS: this issue goes away if i reduce the version by one, both on android and ios.

**Comment by stuartmorgan** [comment]
If it's add-to-app, this may be the same underlying issue as https://github.com/flutter/flutter/issues/100844. Does this reproduce on master?

> PS: this issue goes away if i reduce the version by one, both on android and ios.

Since the issue is that Dart plugin registration is not running, that's expected; earlier versions don't use Dart plugin registration.

**Comment by niumj** [comment]
path_provider_android 2.0.14 with the same issue丅
Temporary solution:  https://github.com/flutter/flutter/issues/100844

**Comment by stuartmorgan** [comment]
Closing due to lack of response; please re-open if you can still reproduce on master.
