### ISSUE TITLE
[web] exception stack trace with javascript files instead of dart 

### ISSUE THREAD

**Issue by tgpsantos** [flutter/flutter#101888]
## Steps to Reproduce

Hi guys,

I've recently converted our mobile project into web. I'm in the process of adapting packages and dependencies, but realized it's **taking much more time to properly debug issues in web compared to mobile**.

One of the reasons is the following: 

![imagem](https://user-images.githubusercontent.com/48353485/163346076-0a57a3ba-9a99-4f91-bb20-28fa82b6823a.png)

As you can see in the above stack, every single line is a .js line, which makes it hard to understand which of the 5 calls to `getApplicationDocumentsDirectory()` is causing the exception (this is just an example - I know that path provider does not work for web). Clicking on the hyperlink opens up the browser and does nothing.

I'd expect a similar behaviour as in flutter-mobile, where we get the particular dart line that caused the exception. We can even click on it and go straight to the file-line mentioned in the stack trace.

<details><summary> Flutter Doctor</summary>

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1645], locale pt-PT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 4.2)
[√] VS Code (version 1.66.1)
[√] VS Code, 32-bit edition (version 1.32.3)
[√] Connected device (3 available)
[√] HTTP Host Availability
```
</details>

**Comment by maheshmnj** [comment]
Hi @tgpsantos, Thanks for filing the issue. I do see the same behavior when any kind of error or exception occurs on the web, The stack. traces do not show the dart line where the exception occurs. Labeling this issue as a proposal to show dart stack traces.

<details>
<summary>code sample</summary>


```dart
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  Future<void> _incrementCounter() async {
    final x = getApplicationDocumentsDirectory();
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details> 

<details>
<summary>logs</summary>

```
Performing hot restart...                                          150ms
Restarted application in 156ms.
Error: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
    at Object.throw_ [as throw] (http://localhost:50290/dart_sdk.js:5067:11)
    at MethodChannel._invokeMethod (http://localhost:50290/packages/flutter/src/services/restoration.dart.lib.js:1560:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:50290/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:50290/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50290/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:50290/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:50290/dart_sdk.js:35969:17)
    at _Future.new.[_completeWithValue] (http://localhost:50290/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50290/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:50290/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:50290/dart_sdk.js:40714:13)
    at http://localhost:50290/dart_sdk.js:36191:9

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (13 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.391, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.13.0-0.0.pre.391 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 08c46bcb58 (7 hours ago), 2022-04-05 22:24:05 -0400
    • Engine revision 45bedbe841
    • Dart version 2.17.0 (build 2.17.0-266.0.dev)
    • DevTools version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by yjbanov** [comment]
Do you have source maps enabled in your browser? You can check by going to settings in Chrome DevTools. If not, try enabling them. If that doesn't help, then this is likely a real bug.

This is what the option looks like:

<img width="209" alt="Screen Shot 2022-04-14 at 11 11 40 AM" src="https://user-images.githubusercontent.com/211513/163451478-81d93721-7dd3-44aa-9388-bae924bc8963.png">

**Comment by tgpsantos** [comment]
@yjbanov yes, the option is enabled

**Comment by kevmoo** [comment]
Is this running locally or remotely? Just want to check to understand if source_maps are being deploying somewhere remote.

**Comment by jason-simmons** [comment]
This will happen for any uncaught exception.

In the original example, the exception was being thrown by an async task.  If there is no uncaught exception handler in the zone that can receive the exception and a Dart `StackTrace`, then the JavaScript exception will be handled by the browser and printed to the console.

You can reproduce this by running `flutter run -d chrome` with an app that immediately throws:
```
void main() {
  throw Exception('test');
}
```

The source maps are built for the application as expected.  If you open the Chrome developer tools and view the console, you will see that the exception stack trace has been annotated with Dart source files and lines based on the source maps.

But the trace printed by the Flutter tools is based on the console log stream produced by DWDS.  DWDS receives an exceptionThrown event from the Chrome DevTools protocol, and the stack trace in the `ExceptionDetails` is a raw stack trace that does not use the source maps. 

As an experiment I tried patching DWDS' `_chromeConsoleStreamController` to call a version of `debugger.calculateDartFrameFor` that maps the `exceptionDetails.stackTrace.callFrames` to Dart source file and line info.  The results can then be logged to the console stream.

@annagrin @grouma Do you think something like that would be useful?

**Comment by jason-simmons** [comment]
The exception in Flutter Web is flowing through the `if (includeExceptions)` code path in `_chromeConsoleStreamController`.

But the exception event sent by the Chrome debug protocol contains a stack trace based on raw JavaScript stack frames.  I don't know if there is a way to configure Chrome to apply the stack trace mapper to the exception.

If that is not possible, then DWDS would need to apply the mapping itself.  AFAICT it is not currently doing that for exceptions that are sent to the `remoteDebugger.onExceptionThrown` stream.

**Comment by grouma** [comment]
> If that is not possible, then DWDS would need to apply the mapping itself. AFAICT it is not currently doing that for exceptions that are sent to the `remoteDebugger.onExceptionThrown` stream.

This seems to be my confusion, apologies. I *thought* we had logic to translate exceptions but I guess that is not the case.  What you outlined [here](https://github.com/flutter/flutter/issues/101888#issuecomment-1113877045) seems like an appropriate fix. I assume the result would be equivalent to using the stack trace mapper. Another alternative to consider is to call the stack trace mapper, from the DWDS backend, using the Chrome DevTools protocol. 

I'm happy to review an PRs you send my way.

**Comment by annagrin** [comment]
Matching issue in webdev: https://github.com/dart-lang/webdev/issues/1265
