### ISSUE TITLE
Missing salt grain causes jinja template errors

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#101870]
If our custom grain (device_os) has not been set on the minion, it causes jinja template render errors:
```
Traceback (most recent call last):
  File "/opt/salt/lib/python3.7/site-packages/salt-3002.7-py3.7.egg/salt/utils/templates.py", line 261, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/opt/salt/lib/python3.7/site-packages/salt-3002.7-py3.7.egg/salt/utils/templates.py", line 508, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {}{}".format(exc, out), buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'device_os'
[CRITICAL] Rendering SLS 'base:flutter.provision_mac' failed: Jinja variable 'dict object' has no attribute 'device_os'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:flutter.provision_mac' failed: Jinja variable 'dict object' has no attribute 'device_os'
```

**Comment by yusuf-goog** [comment]
fixed in go/fxcl/519173
