### ISSUE TITLE
An error occurs when using PlatformView

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#101982]
An error occurs when using PlatformView like below stack trace.
But unfortunately, we cannot reproduce it in the development environment.
Could you have any suggestions, please?

- C++ stacktrace

```C++
Signal 6(SIGABRT), Code -6(SI_TKILL)
abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(2085)] Check failed: CheckException(env).  '
#00 pc 0000000000022ed0  /system/lib64/libc.so (abort+116)
#01 pc 00000000002e34e0  /data/app/com.lvsongguo-O7-1X8_krJFne0EKb2ttPQ==/lib/arm64/libflutter.so (_vpaes_schedule_core)
```

- Java stacktrace

```java
 [SurfaceTexture-0-16782-28] detachFromContext: abandoned SurfaceTexture

  at io.flutter.embedding.engine.FlutterJNI.nativeSurfaceDestroyed(FlutterJNI.java)
  at io.flutter.embedding.engine.FlutterJNI.onSurfaceDestroyed(FlutterJNI.java:568)
  at io.flutter.embedding.engine.renderer.FlutterRenderer.stopRenderingToSurface(FlutterRenderer.java:234)
  at io.flutter.embedding.engine.renderer.FlutterRenderer.startRenderingToSurface(FlutterRenderer.java:183)
  at io.flutter.embedding.android.FlutterSurfaceView.connectSurfaceToRenderer(FlutterSurfaceView.java:257)
  at io.flutter.embedding.android.FlutterSurfaceView.attachToRenderer(FlutterSurfaceView.java:201)
  at io.flutter.embedding.android.FlutterView.revertImageView(FlutterView.java:1122)
  at io.flutter.plugin.platform.PlatformViewsController.onEndFrame(PlatformViewsController.java:817)
  at io.flutter.embedding.engine.FlutterJNI.onEndFrame(FlutterJNI.java:1146)
  at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
  at android.os.MessageQueue.next(MessageQueue.java:386)
  at android.os.Looper.loop(Looper.java:175)
  at android.app.ActivityThread.main(ActivityThread.java:7779)
  at java.lang.reflect.Method.invoke(Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)

```

- flutter doctor -v
current cmd: flutter  doctor -v
[✓] Flutter (Channel unknown, v2.0.6-0.0.pre.315, on macOS 12.0.1 21A559 darwin-x64, locale en-CN)
    • Flutter version 2.0.6-0.0.pre.315
    • Framework revision b8ad072162 (7 weeks ago), 2022-02-25 13:33:43 +0800
    • Engine revision 7eba6fac00
    • Dart version 2.12.3
    • Pub download mirror http://dart-pub.byted.org
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/wangying/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/wangying/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.3, Build version 13E113
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • Pixel 4 (mobile) • 98231FFAZ004C5 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos          • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 2 categories.
Android environments are well prepared.

**Comment by wangying3426** [comment]
fixed
