### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: google-chrome, OS error code: 2

### ISSUE THREAD

**Issue by jkmpariab** [flutter/flutter#101981]
## Command
```
flutter run
```

## Steps to Reproduce
1. flutter run
2. launch devtool by pressing 'v' on terminal
3. bingo. flutter crashed due to chrome not installed

## Logs
ProcessException: No such file or directory Command: google-chrome, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:134:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:122:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1667:55)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1685:13)
#8      _rootRunUnary (dart:async/zone.dart:1434:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _rootRunUnary (dart:async/zone.dart:1434:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
```
```
[✓] Flutter (Channel beta, 2.13.0-0.1.pre, on Ubuntu Jammy Jellyfish (development branch) 5.15.0-25-generic, locale en_US.UTF-8)
    • Flutter version 2.13.0-0.1.pre at /home/abed/.local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 13a2fb10b8 (3 days ago), 2022-04-12 15:34:25 -0500
    • Engine revision 499984f99c
    • Dart version 2.17.0 (build 2.17.0-266.1.beta)
    • DevTools 
```

BTW i'm running on flutter beta channel. Chances are the issue have been solved on master

**Comment by maheshmnj** [comment]
Hi @jkmpariab,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/95142, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
