### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/wangyao/development/flutter/bin/cache/artifacts/engine/android-x64-release/darwin-x64/gen_snapshot.

### ISSUE THREAD

**Issue by Three-FISH** [flutter/flutter#101975]
## Command
```
flutter --quiet assemble --depfile /Users/wangyao/AndroidStudioProjects/flutter_weighting_control_update/build/app/intermediates/flutter/release/flutter_build.d --output /Users/wangyao/AndroidStudioProjects/flutter_weighting_control_update/build/app/intermediates/flutter/release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/wangyao/development/flutter/bin/cache/artifacts/engine/android-x64-release/darwin-x64/gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      Ge

**Comment by darshankawar** [comment]
@Three-FISH 
This issue was fixed as part of https://github.com/flutter/flutter/issues/68475.
I recommend you to upgrade to the latest stable (2.10.4) or the latest master and try again to see it work properly.

Closing as this is already fixed. If after upgrading to the latest versions, you still see the issue, write in comments and I'll reopen.
