### ISSUE TITLE
[tool_crash] RPCError Oops; flutter has exited unexpectedly: "_flutter.screenshotSkp: (-32000) Could not capture SKP screenshot.".

### ISSUE THREAD

**Issue by draty01** [flutter/flutter#101962]
## Command
```
flutter screenshot --type=skia --observatory-url=http://127.0.0.1:55893/MlN5Xp9Cpo8=/
```

## Steps to Reproduce
1. flutter attach
2. flutter screenshot --type=skia --observatory-url=http://127.0.0.1:55893/MlN5Xp9Cpo8=/

## Logs
RPCError: _flutter.screenshotSkp: (-32000) Could not capture SKP screenshot.

```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1718:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2225:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2188:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:776:28)
#4      FlutterVmService.screenshotSkp (package:flutter_tools/src/vmservice.dart:937:12)
#5      ScreenshotCommand.runSkia (package:flutter_tools/src/commands/screenshot.dart:141:54)
<asynchronous suspension>
#6      ScreenshotCommand.runCommand (package:flutter_tools/src/commands/screenshot.dart:113:19)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1645], locale zh-CN)
    • Flutter version 2.10.4 at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Android\Sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\android-studio-2020.3.1.25\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\android-studio-2020.3.1.25
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] Android Studio (version 4.1)
    • Android Studio at E:\android-studio-4.1.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at E:\ideaIC-2021.3.win
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • S20iQ19 (mobile)  • c21c813c • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 100.0.4896.88
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 98.0.1108.62

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.huya.hive.dartmodule
**iOS bundle identifier**: com.huya.hive.dartmodule
**Creation channel**: dev
**Creation framework version**: 83b9e99cfbb8be5215514d7fa21191961b4a620d
### Plugins
fluttertoast-8.0.9
video_player-2.3.0
video_player_android-2.3.2
video_player_avfoundation-2.3.1
video_player_web-2.0.7
webview_flutter-2.8.0
webview_flutter_android-2.8.5
webview_flutter_wkwebview-2.7.2

**Comment by danagbemava-nc** [comment]
Labeling this for further investigation as I cannot find any existing open issues and I cannot also reproduce locally.
