### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException  | reasonPhrase can't be empty.

### ISSUE THREAD

**Issue by PawanFyers** [flutter/flutter#102065]
## Steps to Reproduce
We got this issue from the Firebase Crashlytics console, therefore we don't have the steps to reproduce.

**Expected results:** 
Webview should not crash the whole Mobile App.

**Actual results:**
Webview Crashes the whole Application

<details>
<summary>Code sample</summary>

```import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:fyers/presentation/screens/charts/Utils/ChartUtils.dart';
import 'package:fyers/src/models/GetQuotes.dart';
import 'package:fyers/src/network/ApiProvider.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:webview_flutter/webview_flutter.dart';

class ChartWebview extends StatefulWidget {
  String? symbol;

  V? v;
  var ltp;
  ChartWebview({Key? key, this.ltp, this.v, this.symbol}) : super(key: key);

  @override
  State<ChartWebview> createState() => ChartWebviewState();
}

class ChartWebviewState extends State<ChartWebview>
    with AutomaticKeepAliveClientMixin {
  bool get wantKeepAlive => true;

  String? initialUrl;
  String? symbol;
  var token = ApiProvider().tempTokenId;
  int currentTab = 0;
  ChartUtils _chartUtils = new ChartUtils();

  final Completer<WebViewController> _completerController =
      Completer<WebViewController>();
  late WebViewController _webViewController;

  @override
  void initState() {
    super.initState();
    String? theme = "";
    if (ApiProvider().isDarkTheme) {
      // if (userSettings.theme.toLowerCase() == "dark") {
      theme = "dark";
    } else {
      theme = "light";
    }
  }

  updateChartURL({String? url, String? symbolName}) {
    print("Yash at 4 _chartUtils.webviewUrl = ${_chartUtils.webviewUrl}");
    // _webViewController.loadUrl(url!.length > 0 ? url : _chartUtils.webviewUrl);
    changeSymbol(context, symbolName);
    print("Yash at 5 _chartUtils.webviewUrl = ${_chartUtils.webviewUrl}");
  }

  changeSymbol(BuildContext context, var symbol) async {
    print("Yash change symbol 1");
    final WebViewController controller = await _completerController.future;
    controller
        .evaluateJavascript('tvWidget.activeChart().setSymbol("$symbol");');
    print("Yash change symbol 2");
    // controller.evaluateJavascript(
    //     'localStorage.setItem("fyerstrade_themeStyle","dark")');
  }

  _launchChartInWebView(String chartURL) async {
    if (await canLaunch(chartURL)) {
      return launch(chartURL);
    } else
      return false;
  } //_launchChartInWebView closes here....

  @override
  Widget build(BuildContext context) {
    print("Yash at 3 _chartUtils.webviewUrl = ${_chartUtils.webviewUrl}");

    return WebView(
      debuggingEnabled: false,
      initialUrl: _chartUtils.webviewUrl,
      javascriptMode: JavascriptMode.unrestricted,
      gestureRecognizers: [
        Factory(() => new CustomGestureRecognizer(
            // maxScreenOffsetX: MediaQuery.of(context).size.width
            maxScreenOffsetX: MediaQuery.of(context).size.longestSide)),
      ].toSet(),
      onWebViewCreated: (WebViewController webViewController) {
        _completerController.complete(webViewController);
        _webViewController = webViewController;
        _chartUtils.updateChartURLLoadStatus(true);
      },
      javascriptChannels: <JavascriptChannel>[
        snackbarJavascriptChannel(context),
      ].toSet(),
      navigationDelegate: (NavigationRequest request) {
        String requestURL = request.url.trim().toString();
        if (requestURL.startsWith('https://charts.fyers.in') &&
            requestURL.endsWith('png')) {
          //The chart has to be shown in a new Browser....
          if (_launchChartInWebView(requestURL))
            //In case of launch success, prevent from loading ahead.
            return NavigationDecision.prevent;
          else //In case of launch failure, load ahead.
            return NavigationDecision.navigate;
        } else //In case of launch failure, load ahead.
          return NavigationDecision.navigate;
      },
      onPageStarted: (value) {
        // // //print("PAGE STARTED $value");
        // changeTheme(context);
      },
      onPageFinished: (value) {
        // changeTheme(context);
        // // //print("PAGE FINISHED $value");
      },
    );
  }
}

class CustomGestureRecognizer extends OneSequenceGestureRecognizer {
  double? maxScreenOffsetX;
  final double? edgeMargin = 20.0;

  CustomGestureRecognizer({required this.maxScreenOffsetX});

  @override
  void addAllowedPointer(PointerDownEvent event) {
    // // //print("CustomGestureRecognizer: Screen Width: " +
    //     maxScreenOffsetX.toString());
    // // //print("CustomGestureRecognizer: dx: " + event.position.dx.toString());

    if (event.position.dx < edgeMargin! ||
        event.position.dx > (maxScreenOffsetX! - edgeMargin!)) {
      // // //print("CustomGestureRecognizer: At the Edge.");
      return;
    }
    // // //print("CustomGestureRecognizer: Inside Safe Zone");
    startTrackingPointer(event.pointer, event.transform);
    resolve(GestureDisposition.accepted);
    stopTrackingPointer(event.pointer);
  }

  @override
  String get debugDescription => "";

  @override
  void didStopTrackingLastPointer(int pointer) {}

  @override
  void handleEvent(PointerEvent event) {}
}

JavascriptChannel snackbarJavascriptChannel(BuildContext context) {
  return JavascriptChannel(
    name: 'SnackbarJSChannel',
    onMessageReceived: (JavascriptMessage message) {
      // //print(message.message);

      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text(message.message),
      ));
    },
  );
}
```

</details>

<details>
  <summary>Logs:</summary>

```
Fatal Exception: java.lang.IllegalArgumentException: reasonPhrase can't be empty.
       at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
       at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedHttpError(WebViewContentsClientAdapter.java:308)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7402)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

```
```

```
```

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.10.3 at /Users/pawanshahani/fvm/versions/2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/pawanshahani/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi, @PawanFyers, can you provide the list of affected devices and the full stack trace?

Please also provide the version of `webview_flutter` you're using. 

Thank you

**Comment by PawanFyers** [comment]
> Hi, @PawanFyers, can you provide the list of affected devices and the full stack trace?
> 
> Please also provide the version of `webview_flutter` you're using.
> 
> Thank you

**_List of devices:_**
6.0 Lenovo PHAB2 Plus
6.0.1 Galaxy On5
6.0.1 Galaxy A5
5.1.1 K5 Plus
6.0.1 Redmi Note 3
6.0.1 Galaxy A5


_**Full Stack Trace:**_
```
Fatal Exception: java.lang.IllegalArgumentException: reasonPhrase can't be empty.
       at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
       at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedHttpError(WebViewContentsClientAdapter.java:331)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5773)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

```
ReferenceQueueDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:164)
       at java.lang.Thread.run(Thread.java:818)
```

```
com.google.firebase.crashlytics.startup1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java)
       at java.lang.Thread.run(Thread.java:818)
```

```
GAC_Executor[0]
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.google.android.gms.internal.zzbge.run(zzbge.java)
       at java.lang.Thread.run(Thread.java:818)
```

```
FinalizerWatchdogDaemon
       at java.lang.Thread.sleep(Thread.java)
       at java.lang.Thread.sleep(Thread.java:1031)
       at java.lang.Thread.sleep(Thread.java:985)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:316)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:327)
       at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:272)
       at java.lang.Thread.run(Thread.java:818)
```

```
OkHttp ConnectionPool
       at java.lang.Object.wait(Object.java)
       at com.android.okhttp.ConnectionPool.performCleanup(ConnectionPool.java:305)
       at com.android.okhttp.ConnectionPool.runCleanupUntilPoolIsEmpty(ConnectionPool.java:242)
       at com.android.okhttp.ConnectionPool.-wrap0(ConnectionPool.java)
       at com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:97)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

```
Firebase-Messaging-Init
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1078)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1071)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java)
       at java.lang.Thread.run(Thread.java:818)
```

```
com.it_nomads.fluttersecurestorage.worker
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

```
GAC_Executor[1]
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.google.android.gms.internal.zzbge.run(zzbge.java)
       at java.lang.Thread.run(Thread.java:818)
```

```
firebase-installations-executor-2
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:198)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2053)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:435)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1037)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

```
AsyncTask #1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```


_**webview_flutter version:**_
`webview_flutter: ^3.0.1`

**Comment by danagbemava-nc** [comment]
Hi @PawanFyers, thanks for the info. 

This was previously reported in https://github.com/flutter/flutter/issues/29446 and presumably fixed. Based on the affected devices, my guess is it only affects older devices. 

Labeling for further investigation

**Comment by stuartmorgan** [comment]
I re-opened the original issue; closing this one as a duplicate.
