### ISSUE TITLE
Gradient sometimes doesn't extend to the edges of the widget

### ISSUE THREAD

**Issue by lotusgate** [flutter/flutter#102149]
At certain widget sizes, the `BoxDecoration`'s gradient doesn't affect the last 1-2 pixels of the edges. If you zoom on the 2 images I've uploaded below, you will see that the gradient doesn't reach the end of any of the sides. If in the example code I set the `SizedBox`'s height to 400, while leaving the width at 300, only the left and right sides won't be reached.
The pattern I've noticed is: when the height is set to {100, 300, 500...} the gradient doesn't extend completely vertically and with {200, 400, 600...} it does. The width affects the horizontal axis the same way.

<details>
<summary>Images</summary>

<img width=45% src=https://user-images.githubusercontent.com/35681808/164038451-3371f03a-fbc2-4195-9673-09c88bca1c1a.png> <img width=45% src=https://user-images.githubusercontent.com/35681808/164038490-41f8ced5-02a9-45bd-8b45-7e977c898959.png>

</details>

<details>
<summary>Code to reproduce</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Center(
          child: SizedBox(
            width: 300,
            height: 300,
            child: DecoratedBox(
              decoration: const BoxDecoration(color: Colors.pink),
              child: DecoratedBox(
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.centerRight,
                    end: Alignment.centerLeft,
                    stops: const [0, 0.2, 0.3],
                    colors: [
                      Colors.black,
                      Colors.black.withAlpha(150),
                      Colors.black.withAlpha(0),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
    • Flutter version 2.10.5 at C:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (22 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at D:\Programs\Android_SDK
    • Platform android-31, build-tools 33.0.0-rc1
    • Java binary at: D:\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at D:\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\hrist\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 100.0.1185.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

<details>
<summary>flutter analyze</summary>

```                                            
No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @lotusgate, thanks for reporting this. 

My guess is this is related to https://github.com/flutter/flutter/issues/14288 but I'm not certain, so I'll be leaving this for further input from the team.

Reproducible on only android in my testing using the code sample provided above. See screenshots below. 

SN: It might be necessary to zoom into the screenshots below to see the issue clearly

<details>
<summary>screenshots</summary>

| android | ios | macos | web | 
| -- | -- | -- | -- |
| <img src="https://user-images.githubusercontent.com/88313112/164189882-208d7c59-031c-4568-9df1-e8443c5da8ee.png" /> | <img src="https://user-images.githubusercontent.com/88313112/164189164-ceb7318a-01d0-47eb-84ce-a711cf4fc6ce.png" /> | <img width="634" alt="Screenshot 2022-04-20 at 08 22 23" src="https://user-images.githubusercontent.com/88313112/164189250-08e93a82-83bf-4686-a658-5367bc8c88e7.png"> | <img width="612" alt="Screenshot 2022-04-20 at 08 26 25" src="https://user-images.githubusercontent.com/88313112/164189351-ed6bc6b1-6bbf-40b5-90b8-cebcfba24feb.png"> |

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 (mobile)          • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.635, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.635 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b31eb41bcb (8 hours ago), 2022-04-19 20:34:07 -0400
    • Engine revision 2ce50acf42
    • Dart version 2.18.0 (build 2.18.0-36.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 (mobile)          • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by chinmaygarde** [comment]
cc @flar

**Comment by flar** [comment]
The issue seems scale dependent. Even though it doesn't happen on my MBP/macos I can get it to appear by applying a scale. See the following scalable version and play with the scale until it appears.

<details>
  <summary>Click to expand!</summary>
  
```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  double scale = 1.0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Stack(
          children: [
            Center(
              child: Transform.scale(
                scale: scale,
                child: SizedBox(
                  width: 300,
                  height: 300,
                  child: DecoratedBox(
                    decoration: const BoxDecoration(color: Colors.pink),
                    child: DecoratedBox(
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment.centerRight,
                          end: Alignment.centerLeft,
                          stops: const [0, 0.2, 0.3],
                          colors: [
                            Colors.black,
                            Colors.black.withAlpha(150),
                            Colors.black.withAlpha(0),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
            Positioned(
              bottom: 0,
              left: 10,
              child: Row(
                children: [
                  const Text('Scale:', style: TextStyle(color: Colors.cyan)),
                  Slider(
                    value: scale,
                    min: 0.1,
                    max: 2.0,
                    onChanged: (v) => setState(() => scale = v),
                  ),
                  Text('$scale', style: TextStyle(color: Colors.yellow)),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by flar** [comment]
This appears to be an intersection/interaction of "odd scales and layout computations can produce non-integer coordinates for our rendering" and "antialiased rendering of 2 rectangles with non-integer coordinates does not cause the edge pixels to be replaced due to partial coverage".

You can see this with the following skia fiddle: https://fiddle.skia.org/c/4897c0f4ed01b87c93912216cb552738
But if you turn off antialiasing in the 2 places it is set, then the edge bleed goes away:
https://fiddle.skia.org/c/3bfb8bd287277e6874e9d596bf45221f

I'm not sure how to disable AA for box decorations, though?

**Comment by jdk-21** [comment]
This issue seems to still exist. I can reproduce it with certain sizes on macOS 14.1 (M1).
![grafik](https://github.com/flutter/flutter/assets/57756132/ba44ba02-1179-42eb-867b-4a11bfd6c845)

The provided code snippet in this issue also produces this error:
![grafik](https://github.com/flutter/flutter/assets/57756132/74139561-3c47-43c0-af12-2cc35d2ae755)

<details><summary>Code to reproduce</summary>
<p>

> The issue seems scale dependent. Even though it doesn't happen on my MBP/macos I can get it to appear by applying a scale. See the following scalable version and play with the scale until it appears.
> Click to expand!
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() => runApp(const MyApp());
> 
> class MyApp extends StatefulWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   @override
>   State createState() => MyAppState();
> }
> 
> class MyAppState extends State<MyApp> {
>   double scale = 1.0;
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         backgroundColor: Colors.black,
>         body: Stack(
>           children: [
>             Center(
>               child: Transform.scale(
>                 scale: scale,
>                 child: SizedBox(
>                   width: 300,
>                   height: 300,
>                   child: DecoratedBox(
>                     decoration: const BoxDecoration(color: Colors.pink),
>                     child: DecoratedBox(
>                       decoration: BoxDecoration(
>                         gradient: LinearGradient(
>                           begin: Alignment.centerRight,
>                           end: Alignment.centerLeft,
>                           stops: const [0, 0.2, 0.3],
>                           colors: [
>                             Colors.black,
>                             Colors.black.withAlpha(150),
>                             Colors.black.withAlpha(0),
>                           ],
>                         ),
>                       ),
>                     ),
>                   ),
>                 ),
>               ),
>             ),
>             Positioned(
>               bottom: 0,
>               left: 10,
>               child: Row(
>                 children: [
>                   const Text('Scale:', style: TextStyle(color: Colors.cyan)),
>                   Slider(
>                     value: scale,
>                     min: 0.1,
>                     max: 2.0,
>                     onChanged: (v) => setState(() => scale = v),
>                   ),
>                   Text('$scale', style: TextStyle(color: Colors.yellow)),
>                 ],
>               ),
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

</p>
</details>
