### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH Command: xcrun, OS error code: 72

### ISSUE THREAD

**Issue by crendy** [flutter/flutter#102123]
## Command
```
flutter build macos --release --build-name=0.0.4
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH Command: xcrun, OS error code: 72
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:305:30)
<asynchronous suspension>
#3      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:77:40)
<asynchronous suspension>
#4      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:58:5)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure

**Comment by danagbemava-nc** [comment]
Hi @crendy, can you take a look at this StackOverflow thread to see if it helps? https://stackoverflow.com/questions/40743713/command-line-tool-error-xcrun-error-unable-to-find-utility-xcodebuild-n

Please also provide the output of `flutter doctor -v`.

Thank you
