### ISSUE TITLE
I am unable to getApplicationDocumentsDirectory in WorkManager callback

### ISSUE THREAD

**Issue by bkleineibst** [flutter/flutter#102214]
## Steps to Reproduce

Trigger a callback using WorkManager and try to get the application documents directory using path provider plugin.

After seeing the same error reported in #99155, I tried the solution posted there: https://github.com/flutter/flutter/issues/99155#issuecomment-1052023743. 

After doing that, I am getting a different, but related error. Am I doing something wrong or is there another issue?

**Expected results:** 

No exceptions and I am able to get the requested directory using path provider.

**Actual results:** 

```
_AssertionError ('package:flutter/src/services/platform_channel.dart': Failed assertion: line 134 pos 7: '_binaryMessenger != null || ServicesBinding.instance != null': Cannot use this MethodChannel before the binary messenger has been initialized. This happens when you invoke platform methods before the WidgetsFlutterBinding has been initialized. You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().)
```

<details>
<summary>Code sample</summary>

```dart
await Workmanager().initialize(
    callbackDispatcher, // The top level function, aka callbackDispatcher
    isInDebugMode: true, // If enabled it will post a notification whenever the task is running. Handy for debugging tasks
  );

void callbackDispatcher() {
  if (Platform.isAndroid) PathProviderAndroid.registerWith(); 
  if (Platform.isIOS) PathProviderIOS.registerWith();

  final dir = getApplicationDocumentsDirectory();     // This throws the above exception when the callback is triggered
}
```

</details>

<details>
  <summary>Logs</summary>

```
[+740 ms] E[/flutter]() (27329): [ERROR:flutter[/lib/ui/ui_dart_state.cc]()(209)] Unhandled Exception: 'package:flutter[/src/services/platform_channel.dart]()': Failed assertion: line 134 pos 7: '_binaryMessenger != null || ServicesBinding.instance != null': Cannot use this MethodChannel before the binary messenger has been initialized. This happens when you invoke platform methods before the WidgetsFlutterBinding has been initialized. You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().
package:flutter/…/services/platform_channel.dart:134
[        ] E[/flutter]() (27329): #0      _AssertionError._doThrowNew (dart:core-patch[/errors_patch.dart:51:61]())
[        ] E[/flutter]() (27329): #1      _AssertionError._throwNew (dart:core-patch[/errors_patch.dart:40:5]())
[        ] E[/flutter]() (27329): #2      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:134
[        ] E[/flutter]() (27329): #3      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:167
[        ] E[/flutter]() (27329): #4      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:350
[        ] E[/flutter]() (27329): #5      PathProviderAndroid.getApplicationDocumentsPath
package:path_provider_android/path_provider_android.dart:39
[        ] E[/flutter]() (27329): #6      getApplicationDocumentsDirectory
package:path_provider/path_provider.dart:115
[        ] E[/flutter]() (27329): #7      callbackDispatcher
package:myapp/main_common.dart:103
[        ] E[/flutter]() (27329): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui[/hooks.dart:130:25]())
[        ] E[/flutter]() (27329): #9      _rootRun (dart:async[/zone.dart:1426:13]())
[        ] E[/flutter]() (27329): #10     _CustomZone.run (dart:async[/zone.dart:1328:19]())
[        ] E[/flutter]() (27329): #11     _runZoned (dart:async[/zone.dart:1861:10]())
[        ] E[/flutter]() (27329): #12     runZonedGuarded (dart:async[/zone.dart:1849:12]())
[        ] E[/flutter]() (27329): #13     _runMainZoned.<anonymous closure> (dart:ui[/hooks.dart:126:5]())
[        ] E[/flutter]() (27329): #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch[/isolate_patch.dart:297:19]())
[        ] E[/flutter]() (27329): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch[/isolate_patch.dart:192:12]())
```

```
No relevant issues
```

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-arm, locale en-CA)
    • Flutter version 2.10.5 at /Users/user/code/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/user/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 9 (API 28)
      (emulator)
    • sdk gphone64 arm64 (mobile)          • emulator-5556 • android-arm64  • Android 12 (API 32)
      (emulator)
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome
      100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@bkleineibst 
As the error message indicates `This happens when you invoke platform methods before the WidgetsFlutterBinding has been initialized. You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().`. 

Can you try the same as suggested ?

Also check [this](https://github.com/flutter/flutter/issues/99155#issuecomment-1058499437) issue comment and see if it helps.
