### ISSUE TITLE
Auto flake/deflake PRs are failing with `analyze`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#102258]
Example PRs:
https://github.com/flutter/flutter/pull/102225

Test `analyze-linux` fails with
```
▌16:12:25▐ ELAPSED TIME: 5min 19.593s for bin/flutter analyze --flutter-repo in .
▌16:12:25▐ Executable allowlist...
.ci.yaml is executable: 111101101
Unhandled exception:
Exception: found 1 unexpected executable file! If this was intended, you must add this file to kExecutableAllowlist in dev/bots/analyze.dart
#0      _checkForNewExecutables (file:///tmp/flutter%20sdk/dev/bots/analyze.dart:1737:5)
<asynchronous suspension>
#1      run (file:///tmp/flutter%20sdk/dev/bots/analyze.dart:162:3)
<asynchronous suspension>
#2      main (file:///tmp/flutter%20sdk/dev/bots/analyze.dart:52:5)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
Marking as P2 as this is blocking the flake workflow.

**Comment by keyonghan** [comment]
The culprit is here: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/flaky_handler_utils.dart#L41 is explicitly using  mode `100755` when creating PRs.

**Comment by keyonghan** [comment]
Fix is in: https://github.com/flutter/cocoon/pull/1743
