### ISSUE TITLE
[ipad]There is a problem with the external bluetooth physical keyboard on the ipad, and input content after switching the language

### ISSUE THREAD

**Issue by azhansy** [flutter/flutter#102288]
flutter: dashu, event.RawKeyUpEvent ....PhysicalKeyboardKey#7002c(usbHidUsage: "0x0007002c", debugName: "Space"),false
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞═══════════════════════
The following assertion was thrown during a platform message
callback:
A KeyDownEvent is dispatched, but the state shows that the
physical key is already pressed. If this occurs in real
application, please report this bug to Flutter. If this occurs in
unit tests, please ensure that simulated events follow Flutter's
event model as documented in `HardwareKeyboard`. This was the
event: KeyDownEvent#ed474(physicalKey:
PhysicalKeyboardKey#70039(usbHidUsage: "0x00070039", debugName:
"Caps Lock"), logicalKey: LogicalKeyboardKey#00104(keyId:
"0x100000104", keyLabel: "Caps Lock", debugName: "Caps Lock"),
character: null, timeStamp: 57:21:46.485890, synthesized)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 437 pos 16:
'!_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:437:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:374:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#14     _invoke2 (dart:ui/hooks.dart:189:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)
═════════════════════════════════════════════════════════════════

**Comment by maheshmnj** [comment]
Hi @azhansy, Thanks for filing the issue,  There have been [several reports of similar error ](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+%22A+KeyUpEvent+is+dispatched%22) in the past. Which is intermittent can you please try to identify when this issue occurs and share more info?  from your logs, it looks like this seems to have happened on pressing "Space" Key. 
Please also share the output of `flutter doctor -v`.

**Comment by azhansy** [comment]
> Hi @azhansy, Thanks for filing the issue, There have been [several reports of similar error ](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+%22A+KeyUpEvent+is+dispatched%22) in the past. Which is intermittent can you please try to identify when this issue occurs and share more info? from your logs, it looks like this seems to have happened on pressing "Space" Key. Please also share the output of `flutter doctor -v`.

SHUdeMacBook-Pro:~ shu$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-KH)
    • Flutter version 2.10.5 at /Users/shu/company/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/shu/company/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/shu/company/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (5 available)
    • IN2020 (mobile)      • b1c1c100                                 • android-arm64  • Android
      12 (API 31)
    • SM T835 (mobile)     • ce041824a273448b0d7e                     • android-arm64  • Android
      10 (API 29)
    • iPhonedashu (mobile) • 36265f23a5ced647f49c2655e617cc769cf0e84c • ios            • iOS
      15.1 19B74
    • macOS (desktop)      • macos                                    • darwin-x64     • macOS
      12.0.1 21A559 darwin-x64
    • Chrome (web)         • chrome                                   • web-javascript • Google
      Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by azhansy** [comment]
> > Hi @azhansy, Thanks for filing the issue, There have been [several reports of similar error ](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+%22A+KeyUpEvent+is+dispatched%22) in the past. Which is intermittent can you please try to identify when this issue occurs and share more info? from your logs, it looks like this seems to have happened on pressing "Space" Key. Please also share the output of `flutter doctor -v`.
> 
> SHUdeMacBook-Pro:~ shu$ flutter doctor -v [✓] Flutter (Channel stable, 2.10.5, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-KH) • Flutter version 2.10.5 at /Users/shu/company/flutter/flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision [5464c5b](https://github.com/flutter/flutter/commit/5464c5bac742001448fe4fc0597be939379f88ea) (3 days ago), 2022-04-18 09:55:37 -0700 • Engine revision 57d3bac3dd • Dart version 2.16.2 • DevTools version 2.9.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1) • Android SDK at /Users/shu/company/sdk • Platform android-32, build-tools 32.1.0-rc1 • ANDROID_HOME = /Users/shu/company/sdk • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822) • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.1) • Xcode at /Applications/Xcode.app/Contents/Developer • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.1) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
> 
> [✓] VS Code (version 1.64.0) • VS Code at /Applications/Visual Studio Code.app/Contents • Flutter extension version 3.34.0
> 
> [✓] Connected device (5 available) • IN2020 (mobile) • b1c1c100 • android-arm64 • Android 12 (API 31) • SM T835 (mobile) • ce041824a273448b0d7e • android-arm64 • Android 10 (API 29) • iPhonedashu (mobile) • 36265f23a5ced647f49c2655e617cc769cf0e84c • ios • iOS 15.1 19B74 • macOS (desktop) • macos • darwin-x64 • macOS 12.0.1 21A559 darwin-x64 • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127
> 
> [✓] HTTP Host Availability • All required HTTP hosts are available
> 
> • No issues found!

My colleague took the iPad away, and the approximate information is as follows:
iPad Pro 12.9-inch third generation
Software version: 15.4.1

**Comment by maheshmnj** [comment]
Thanks for the info @azhansy, However in order to investigate this issue further we would need the reproducible steps

**Comment by azhansy** [comment]
The bug is accidental, I switched [caps lock], [tab] [command] at will，then my keyboard doesn't work anymore

**Comment by maheshmnj** [comment]
Thanks for the info @azhansy, However, I am unable to reproduce with the above keys. Would it be possible for you to investigate this issue by trying to find a pattern of when this issue occurs?
