### ISSUE TITLE
`Linux web_long_running_tests` flakes due to `malformed response from the FlutterDriver extension`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#102385]
(part of https://github.com/flutter/flutter/issues/97036)

1 flake on `web_e2e_tests`: [3808](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_1_5/3808/overview)

```
▌02:52:16▐ RUNNING: cd dev/integration_tests/web_e2e_tests; ../../../bin/flutter drive --target=test_driver/image_loading_integration.dart --browser-name=chrome --no-sound-null-safety -d web-server --debug --web-renderer=html
Running "flutter pub get" in web_e2e_tests...                    1,186ms
Launching test_driver/image_loading_integration.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         25.9s
test_driver/image_loading_integration.dart is being served at http://localhost:42165
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Unhandled exception:
DriverError: Received malformed response from the FlutterDriver extension.
Expected a JSON map containing a "response" field and, optionally, an "isError" field, but got Null: null

#0      WebFlutterDriver._createMalformedExtensionResponseError (package:flutter_driver/src/driver/web_driver.dart:109:5)
#1      WebFlutterDriver.sendCommand (package:flutter_driver/src/driver/web_driver.dart:128:15)
<asynchronous suspension>
#2      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:522:39)
<asynchronous suspension>
#3      integrationDriver (package:integration_test/integration_test_driver.dart:76:29)
<asynchronous suspension>
Application finished.
```

**Comment by keyonghan** [comment]
This is happening more frequently:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_1_5/3699/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_1_5/3808/overview

Bumping to P2.

**Comment by yjbanov** [comment]
This also looks the same as https://github.com/flutter/flutter/issues/102660

**Comment by yjbanov** [comment]
Closing as duplicate
