### ISSUE TITLE
[camera] ArrayIndexOutOfBoundsException because of a logic bug

### ISSUE THREAD

**Issue by daohoangson** [flutter/flutter#102378]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Allow camera usage

**Expected results:** Camera preview shows up

**Actual results:** Black preview. `ArrayIndexOutOfBoundsException` in debug log.

```
E/MethodChannel#plugins.flutter.io/camera( 1934): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera( 1934): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.plugins.camera.CameraPermissions$CameraRequestPermissionsListener.onRequestPermissionsResult(CameraPermissions.java:92)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:812)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:420)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:722)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:709)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at android.app.Activity.requestPermissions(Activity.java:5278)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:516)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:45)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:73)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at android.os.Looper.loop(Looper.java:246)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#plugins.flutter.io/camera( 1934): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

This happens because the app triggers a permission request before the camera plugin so its request failed:

```
W/Activity( 1934): Can request only one set of permissions at a time
```

When the `onRequestPermissionsResult` is called, it didn't realize the incoming `permissions` and `grantResults` arrays are both empty. Ideally, this method should map the permission and result together instead of checking result array blindly. 

<details>
<summary>Code sample</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';
import 'package:permission_handler/permission_handler.dart';

late List<CameraDescription> cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  cameras = await availableCameras();
  runApp(const CameraApp());
}

class CameraApp extends StatefulWidget {
  const CameraApp({Key? key}) : super(key: key);

  @override
  _CameraAppState createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  CameraController? _controller;

  @override
  void initState() {
    super.initState();

    _checkCameraPermission().then((_) {
      _initCameraController();
    });
  }

  Future<void> _checkCameraPermission() async {
    var status = await Permission.camera.status;
    if (status.isDenied) {
      Permission.camera.request();
    }
  }

  void _initCameraController() async {
    final controller = _controller = CameraController(
      cameras[0],
      ResolutionPreset.max,
      enableAudio: false,
    );

    await controller.initialize();

    if (!mounted) return;
    setState(() {});
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final controller = _controller;
    if (controller == null || !controller.value.isInitialized) {
      return Container();
    }

    return MaterialApp(
      home: CameraPreview(controller),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

Verbose log is too long, see it in full at https://gist.github.com/daohoangson/d6b37b3ecebf3e7c948207730cfbe4e8

```
Analyzing bug...                              
No issues found! (ran in 2.4s)
```

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.3 20E232 darwin-x64, locale en)
    • Flutter version 2.10.3 at /Users/sondh/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/sondh/Library/Android/sdk
    • Platform android-31, build-tools 33.0.0-rc2
    • ANDROID_HOME = /Users/sondh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • SM A225F (mobile) • R58RC4J907E • android-arm64  • Android 11 (API 30)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @daohoangson, Thanks for filing the issue. I am able to reproduce the same exception on stable and the master channel.  
When the exception occurs the camera preview is shown as black. This seems to be happening because multiple permissions are being requested one from the camera plugin and other from the third-party plugin permission handler. 

<details>
<summary>logs</summary>

```dart
Launching lib/main.dart on Redmi K20 Pro in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:53257/tl7mRGGhPC8=/ws
I/CameraManagerGlobal(12511): Connecting to camera service
W/CameraManagerGlobal(12511): [soar.cts] ignore the status update of camera: 100
W/CameraManagerGlobal(12511): [soar.cts] ignore the status update of camera: 101
W/CameraManagerGlobal(12511): [soar.cts] ignore the status update of camera: 120
W/CameraManagerGlobal(12511): [soar.cts] ignore the status update of camera: 20
W/CameraManagerGlobal(12511): [soar.cts] ignore the status update of camera: 21
W/CameraManagerGlobal(12511): [soar.cts] ignore the status update of camera: 60
W/CameraManagerGlobal(12511): [soar.cts] ignore the status update of camera: 61
W/CameraManagerGlobal(12511): [soar.cts] ignore the status update of camera: 62
W/CameraManagerGlobal(12511): [soar.cts] ignore the status update of camera: 63
W/CameraManagerGlobal(12511): ignore the torch status update of camera: 100
W/CameraManagerGlobal(12511): ignore the torch status update of camera: 120
W/CameraManagerGlobal(12511): ignore the torch status update of camera: 20
W/CameraManagerGlobal(12511): ignore the torch status update of camera: 21
W/CameraManagerGlobal(12511): ignore the torch status update of camera: 60
W/CameraManagerGlobal(12511): ignore the torch status update of camera: 61
W/CameraManagerGlobal(12511): ignore the torch status update of camera: 62
W/CameraManagerGlobal(12511): ignore the torch status update of camera: 63
I/iagetest.newap(12511): ProcessProfilingInfo new_methods=1125 is saved saved_to_disk=1 resolve_classes_delay=8000
W/Activity(12511): Can request only one set of permissions at a time
E/MethodChannel#plugins.flutter.io/camera(12511): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera(12511): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.plugins.camera.CameraPermissions$CameraRequestPermissionsListener.onRequestPermissionsResult(CameraPermissions.java:92)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:812)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:420)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:722)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:709)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at android.app.Activity.requestPermissions(Activity.java:5321)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:516)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:45)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:73)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at android.os.Looper.loop(Looper.java:236)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/MethodChannel#plugins.flutter.io/camera(12511): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (12511): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: CameraException(error, length=0; index=0)
E/flutter (12511): #0      MethodChannelCamera.createCamera
E/flutter (12511): <asynchronous suspension>
E/flutter (12511): #1      CameraController.initialize
E/flutter (12511): <asynchronous suspension>
E/flutter (12511): #2      _CameraAppState._initCameraController
E/flutter (12511): <asynchronous suspension>
E/flutter (12511):

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.602, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.13.0-0.0.pre.602 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f4875ae865 (34 hours ago), 2022-04-17 15:19:07 -0400
    • Engine revision 3c6d4da868
    • Dart version 2.18.0 (build 2.18.0-24.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by daohoangson** [comment]
Completely agree with your assessment @maheshmnj 👍

**Comment by blasten** [comment]
cc @camsim99
