### ISSUE TITLE
Image picker is not working in IOS 15.0 simulator.

### ISSUE THREAD

**Issue by panchalAlpit** [flutter/flutter#102304]
it's working before but last few week but now  it's not working the image picker from gallery in IOS. I have also test in real device but also getting issue.

I have give permission in info.plist file.

```dart
final ImagePicker _picker = ImagePicker();
  XFile? image = await _picker.pickImage(source:  ImageSource.gallery);
  File newimage = File(image!.path);
```

getting below issue.

```console
2022-04-21 19:25:30.815615+0530 Runner[14306:1015864] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:187:20)
<asynchronous suspension>
#3      getImageFromDevice (package:myapp/PLUtils/PLGlobal.dart:461:18)
<asynchronous suspension>
#4      _PLChatScreenState._mediaSelect.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:myapp/PLScreen/PLChatScreen.dart:421:41)
<asynchronous suspension>
2022-04-21 19:25:30.976342+0530 Runner[14306:1041196] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:30.976692+0530 Runner[14306:1041196] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:32.166063+0530 Runner[14306:1041197] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:32.166529+0530 Runner[14306:1041197] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:32.174872+0530 Runner[14306:1041197] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:32.175276+0530 Runner[14306:1041197] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:32.177766+0530 Runner[14306:1041197] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:32.178599+0530 Runner[14306:1041197] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:32.546239+0530 Runner[14306:1041197] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:32.546354+0530 Runner[14306:1041197] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x70c86010 d759d5f8 7e36be4d 7efaa10d ... 66e9d063 80c3d8ce }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe7fe9041 cde3fcd6 7734c78c 22d80278 ... ac84189c 6152d178 }}
2022-04-21 19:25:32.548575+0530 Runner[14306:1041197] [claims] Upload preparation for claim B8368F07-2B33-4811-
**87C0-5B37088A3B62 completed with error: Error Domain=NSCocoaErrorDomain Code=256 "The file “version=1&uuid=9F983DBA-EC35-42B8-8773-B597CF782EDD&mode=compatible.jpeg” couldn’t be opened." UserInfo={NSURL=file:///Users/oliver/Library/Developer/CoreSimulator/Devices/782600C0-EC7D-4F47-86E6-5DF8D87ED177/data/Containers/Shared/AppGroup/D273B0E0-8CB0-4321-92FB-02141C4401FC/File%20Provider%20Storage/photospicker/version=1&uuid=9F983DBA-EC35-42B8-8773-_B597CF782EDD&mode=compatible.jpeg,_ NSFilePath=/Users/oliver/Library/Developer/CoreSimulator/Devices/782600C0-EC7D-4F47-86E6-5DF8D87ED177/data/Containers/Shared/AppGroup/D273B0E0-8CB0-4321-92FB-02141C4401FC/File Provider Storage/photospicker/version=1&uuid=9F983DBA-EC35-42B8-8773-B597CF78_2EDD&mode=compatible.jpeg_, NSUnderlyingError=0x600002958660 {Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)"}}**
```

**Comment by nomoreboredom** [comment]
+ 1 I started to encounter this today, file picker acts weird as well

**Comment by panchalAlpit** [comment]
@nomoreboredom I have also try the file picker but also getting similler issue.

**Comment by edritech93** [comment]
same for me

**Comment by maheshmnj** [comment]
Hi @panchalAlpit, thanks for filing the issue. 

There is a known issue, and it is being tracked here https://github.com/flutter/flutter/issues/82602, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
