### ISSUE TITLE
set clipboard data crashed on few phones

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#102300]
`setPrimaryClip` crashed on few phones.  The stack trace is:

```
PlatformException(error, Package com.miHoYo.Yuanshen does not belong to 10359, null, {}, java.lang.SecurityException: Package com.miHoYo.Yuanshen does not belong to 10359
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:430)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.bytedance.privacy.toolkit.service.core.IServiceHookBase.intercept(Unknown Source:9)
	at com.bytedance.privacy.toolkit.service.sys.Clipboard.invoke(Unknown Source:113)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy34.setPrimaryClip(Unknown Source)
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:133)
	at io.flutter.plugin.platform.PlatformPlugin.setClipboardData(Unknown Source:16)
	at io.flutter.plugin.platform.PlatformPlugin.access$800(Unknown Source:0)
	at io.flutter.plugin.platform.PlatformPlugin$1.setClipboardData(Unknown Source:2)
	at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(Unknown Source:210)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:54)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:337)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8085)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.AppOpsManager.checkPackage(AppOpsManager.java:8739)
	at com.android.server.clipboard.ClipboardService.clipboardAccessAllowed(ClipboardService.java:989)
	at com.android.server.clipboard.ClipboardService.sendClipChangedBroadcast(ClipboardService.java:704)
	at com.android.server.clipboard.ClipboardService.setPrimaryClipInternalLocked(ClipboardService.java:692)
	at com.android.server.clipboard.ClipboardService.setPrimaryClipInternalLocked(ClipboardService.java:618)
)
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:158)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:306)
<asynchronous suspension>
#2      _getZoneSpecification.<anonymous closure>.<anonymous closure> (package:bd_vessel/extension/errortrace/internal/error_trace_utils.dart:89)
<asynchronous suspension>

```

There are some discussion of similar issues on stackoverflow, such as [SecurityException: <<other_package>> from uid xxx not allowed to perform READ_CLIPBOARD when calling setPrimaryClip](https://stackoverflow.com/questions/65413648/securityexception-other-package-from-uid-xxx-not-allowed-to-perform-read-cl)

**Comment by danagbemava-nc** [comment]
Hi @wangying3426, thanks for reporting this. 

Can you provide the devices that are affected by this crash and their OS versions? 

Also, is this crash reproducible locally or does it only reproduce in production?

**Comment by wangying3426** [comment]
Based on the online monitoring data in production, all of the below devices may occur crash.
But it doesn't steadily reproduces, therefore it might be caused by some special operations.
```dart
Device: xiaomi m2011k2c,      ROM: miui_V130_V13.0.5.0.SKBCNXM,    OS: 12.0
Device: xiaomi mi 10,         ROM: miui_V130_V13.0.4.0.SJBCNXM,     OS: 12.0
Device: redmi m2012k11ac,   ROM: miui_V130_V13.0.3.0.SKHCNXM,    OS: 12.0
Device: redmi m2007j17c,     ROM: miui_V130_V13.0.4.0.SKMCNXM,    OS: 12.0
Device: xiaomi 2106118c,       ROM: miui_V130_V13.0.3.0.SJSCNXM,     OS: 12.0
```

**Comment by chinmaygarde** [comment]
The linked patch discards exceptions and we have no reproducible test case. So it is difficult to make the case for it to land.

**Comment by wangying3426** [comment]
> The linked patch discards exceptions and we have no reproducible test case. So it is difficult to make the case for it to land.

I found a related issue  https://github.com/react-native-clipboard/clipboard/pull/86 which may be helpful. It have a reproducible case, although the exception stack is slightly different.
