### ISSUE TITLE
Compiling the initial, default Flutter project is throwing errors galore when compiling for MacOS

### ISSUE THREAD

**Issue by mauricev** [flutter/flutter#102479]
## Steps to Reproduce

1. I created a flutter project in IntelliJ 2021.2.4 using Flutter 2.10.4. It was initially set to produce apps for web because MacOS is stil not currently selectable (it's own bug).
2. I ran "flutter create --platforms=windows,macos ." on the path of the project to allow to build for Mac and Windows.
3. I told the project to run in IntelliJ.

**Expected results:** 
It should just run.
**Actual results:** 
It threw a slew of errors

It’s the default project created by flutter in IntelliJ. There were no code changes.

```
[pre-error log truncated due to comment limit on github]
[   +5 ms] <unknown>:0: error: file '/Users/maurice/My Drive/utility belt
software/Programs/IdeaProjects/hangman_solver/build/macos/ModuleCache.noindex/828KCD8XAB5D/Cocoa-1ZSAXE79IU0C7.pcm' is not a valid
precompiled module file
[        ] /Users/maurice/My Drive/utility belt
software/Programs/IdeaProjects/hangman_solver/macos/Runner/MainFlutterWindow.swift:1:8: error: no such module 'Cocoa'
[        ] import Cocoa
[        ]        ^
[        ] <module-includes>:1:9: note: in file included from <module-includes>:1:
[        ] #import "Headers/FlutterMacOS.h"
[        ]         ^
[        ] /Users/maurice/My Drive/utility belt
software/Programs/IdeaProjects/hangman_solver/build/macos/Build/Products/Debug/FlutterMacOS.framework/Headers/FlutterMacOS.h:5:9:
note: in file included from /Users/maurice/My Drive/utility belt
software/Programs/IdeaProjects/hangman_solver/build/macos/Build/Products/Debug/FlutterMacOS.framework/Headers/FlutterMacOS.h:5:
[        ] #import "FlutterAppDelegate.h"
[        ]         ^
[        ] error: error: accessing build database "/Users/maurice/My Drive/utility belt
software/Programs/IdeaProjects/hangman_solver/build/macos/Build/Intermediates.noindex/XCBuildData/build.db": disk I/O error
[        ] ** BUILD FAILED **
[        ] The following build commands failed:
[        ] 	CompileSwift normal x86_64 /Users/maurice/My\ Drive/utility\ belt\
software/Programs/IdeaProjects/hangman_solver/macos/Flutter/GeneratedPluginRegistrant.swift (in target 'Runner' from project 'Runner')
[        ] 	CompileSwift normal x86_64 /Users/maurice/My\ Drive/utility\ belt\
software/Programs/IdeaProjects/hangman_solver/macos/Runner/AppDelegate.swift (in target 'Runner' from project 'Runner')
[        ] 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'Runner' from project 'Runner')
[        ] (3 failures)
[  +49 ms] Building macOS application... (completed in 31.3s)
[   +4 ms] Exception: Build process failed
[   +3 ms] "flutter run" took 43,985ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[  +71 ms] ensureAnalyticsSent: 69ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

```
Analyzing hangman_solver...                                             
No issues found! (ran in 11.0s)
```

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale en-US)
    • Flutter version 2.10.4 at /Users/maurice/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/maurice/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.2)
    • Android Studio at /Volumes/backuphd-boot/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 66.0.2
    • Dart plugin version 212.5744

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Volumes/backuphd-boot/Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 66.0.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] VS Code (version 1.60.1)
    • VS Code at /Volumes/backuphd-boot/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3 21E230 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @mauricev, can you provide the full output of `flutter run -v`? The output may be huge, so kindly put it into a .txt file and attach it here. 

Do you only experience this issue when you create it using Intellij IDEA or does it occur with other code editors and the command line as well?

**Comment by mauricev** [comment]
The errors occurs on the command line too as evidenced by the flutter run output attached.

[flutter-run-output.txt](https://github.com/flutter/flutter/files/8554549/flutter-run-output.txt)

**Comment by danagbemava-nc** [comment]
Hi @mauricev, are you able to run the default apps for other platforms?

**Comment by mauricev** [comment]
It runs on Windows, but here I am literally running it from an IntelliJ installation under Windows 10. 

iOs simulator also works and this is on the same Mac.

I ran it again on the Mac, and I think it produced some more errors that weren’t there initially:

```
2022-04-27 00:06:24.251 xcodebuild[10786:193586]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-19450/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
Details:  (null) deviceType from 00008110-0004148C2ED1801E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7f7f21d2eac0>
Method:   -platform
Thread:   <NSThread: 0x600002e5e7c0>{number = 4, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2022-04-27 00:06:24.477 xcodebuild[10786:193590]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-19450/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
Details:  (null) deviceType from 00008110-0004148C2ED1801E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7f7f21d2eac0>
Method:   -platform
Thread:   <NSThread: 0x600002ee8000>{number = 8, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2022-04-27 00:06:24.557 xcodebuild[10786:193590]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-19450/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
Details:  (null) deviceType from 00008110-0004148C2ED1801E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7f7f21d2eac0>
Method:   -platform
Thread:   <NSThread: 0x600002ee8000>{number = 8, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:CB7CA72A-222E-52F3-B6ED-0BD2634D150B }
{ platform:macOS, name:Any Mac }
```

**Comment by danagbemava-nc** [comment]
Hi @mauricev, please provide the full verbose output of the log you just provided in https://github.com/flutter/flutter/issues/102479#issuecomment-1110519446

Please provide the verbose output of the app running on `iOS` as well.

Thank you

**Comment by mauricev** [comment]
[flutter-run-output latest for macos.txt](https://github.com/flutter/flutter/files/8579158/flutter-run-output.latest.for.macos.txt)
[flutter ios output.txt](https://github.com/flutter/flutter/files/8579159/flutter.ios.output.txt)

**Comment by danagbemava-nc** [comment]
Hi @mauricev, thanks for the logs. 

I need you to try one more thing, can you switch to the `master` channel to see if you still have this issue? 

I'll need the verbose logs of the run on `master` as well. 

To switch to the `master` channel, run the following commands

```
flutter channel master
flutter upgrade
```

Thank you

**Comment by mauricev** [comment]
Master also fails. Log:
[master log.txt.zip](https://github.com/flutter/flutter/files/8588004/master.log.txt.zip)

**Comment by danagbemava-nc** [comment]
Hmmm, can you run the following commands and provide the logs at each step? 
You can do this on either the `master` or `stable` channel, `stable` will be preferable. 

```
flutter create test_project -v
flutter run -d macos -v
```

If you have enabled macos as a supported platform, `flutter create test_project` should create the macos files directly. 
You don't need to run  `flutter create --platforms=macos, windows .`  before the files are generated. 

If you like, you can run `flutter config --enable-macos-dektop` just to confirm that you have already enabled macos desktop before running the create and run commands. 

Thank you

**Comment by mauricev** [comment]
[run test project.txt](https://github.com/flutter/flutter/files/8595259/run.test.project.txt)
[test_project create.txt](https://github.com/flutter/flutter/files/8595261/test_project.create.txt)

This time it errors out because it tries to run as if my CPU is arm64?

**Comment by danagbemava-nc** [comment]
Hi @mauricev, the command I see in the `run test project.txt` file is `flutter -d macos -v`. The `run` command was missing. Can you rerun the command and provide the updated logs? 

Thank you

**Comment by mauricev** [comment]
For other reasons, I had to reinstall my OS (though I kept my Library profile). I created a fresh project here, and it works just fine. So whatever happened with this broken project remains a mystery. Thanks for all your help with this.

**Comment by danagbemava-nc** [comment]
Glad to see your issue has been resolved. 

If you ever run into any more issues in the future, don't hesitate to file a new one. 

Closing as resolved based on https://github.com/flutter/flutter/issues/102479#issuecomment-1116941683.

Thank you
