### ISSUE TITLE
Uncaught BindingError: Expected null or instance of Typeface, got an instance of Typeface

### ISSUE THREAD

**Issue by miraklecode** [flutter/flutter#102429]
There are no error during debug, but when I deploy I've got this error in the console:

```
Uncaught BindingError: Expected null or instance of Typeface, got an instance of Typeface
    at Error.<anonymous> (canvaskit.js:162:76)
    at new <anonymous> (canvaskit.js:161:188)
    at X (canvaskit.js:164:250)
    at vc (canvaskit.js:169:38)
    at Fc.yc [as toWireType] (canvaskit.js:170:404)
    at qc.<anonymous> (canvaskit.js:178:8)
    at qc.<anonymous> (canvaskit.js:213:261)
    at new <anonymous> (canvaskit.js:161:188)
    at Object.aX0 (main.dart.js?v=3.3.4+0422:266:18)
    at main.dart.js?v=3.3.4+0422:31711:17

```
Mouse is not responding just command with the physical keyboard

**Comment by darshankawar** [comment]
@miraklecode 
Can you provide `flutter doctor -v` and exact steps to replicate this error ? Can you also provide a minimal complete reproducible code sample without any third party plugin code that shows this error ? Does it occur while hot reloading / hot restarting ?

**Comment by miraklecode** [comment]
I've realized I've duplicated by mistake a script tag calling the dartmain.js in the index.html, that was causing the error. Thx
