### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by ganultap** [flutter/flutter#102450]
I'm trying to run a flutter test app and the error says

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "C:\Users\reypa\.android\debug.keystore": Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 22s
Running Gradle task 'assembleDebug'...                            204.8s
Exception: Gradle task assembleDebug failed with exit code 1
```

flutter run --verbose:

```
[ +164 ms] executing: [C:\Users\reypa\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+1234 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5464c5bac742001448fe4fc0597be939379f88ea
[   +1 ms] executing: [C:\Users\reypa\flutter/] git tag --points-at 5464c5bac742001448fe4fc0597be939379f88ea
[ +384 ms] Exit code 0 from: git tag --points-at 5464c5bac742001448fe4fc0597be939379f88ea
[   +1 ms] 2.10.5
[  +21 ms] executing: [C:\Users\reypa\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +102 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\Users\reypa\flutter/] git ls-remote --get-url origin
[ +112 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +284 ms] executing: [C:\Users\reypa\flutter/] git rev-parse --abbrev-ref HEAD
[ +111 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +374 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +159 ms] executing: C:\Users\reypa\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +246 ms] List of devices attached
                    l79hq4mny5kfvwws       device product:amber_global model:21081111RG device:amber transport_id:1
[  +33 ms] C:\Users\reypa\AppData\Local\Android\Sdk\platform-tools\adb.exe -s l79hq4mny5kfvwws shell getprop
[ +183 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +736 ms] Skipping pub get: version match.
[ +269 ms] Generating E:\Projects\test\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +205 ms] ro.hardware = mt6893
[   +1 ms] ro.build.characteristics = nosdcard
[ +130 ms] Initializing file store
[  +50 ms] Skipping target: gen_localizations
[  +36 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
E:\Projects\test\.dart_tool\package_config_subset}
[ +160 ms] gen_dart_plugin_registrant: Complete
[   +5 ms] Skipping target: _composite
[   +9 ms] complete
[  +27 ms] Launching lib\main.dart on 21081111RG in debug mode...
[  +26 ms] C:\Users\reypa\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\reypa\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\Users\reypa\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\reypa\AppData\Local\Temp\flutter_tools.234c9cc3\flutter_tool.2bdabecf\app.dill
--packages E:\Projects\test\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +73 ms] executing: C:\Users\reypa\AppData\Local\Android\Sdk\platform-tools\adb.exe -s l79hq4mny5kfvwws shell -x logcat -v time -t 1
[  +73 ms] <- compile package:test/main.dart
[ +336 ms] --------- beginning of main
                    04-24 10:52:30.769 D/MiuiNetworkPolicy( 1555): updateLimit mLimitEnabled=true,enabled=false,mNetworkPriorityMode=255
[  +41 ms] executing: C:\Users\reypa\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[  +99 ms] Android Debug Bridge version 1.0.41
           Version 33.0.1-8253317
           Installed as C:\Users\reypa\AppData\Local\Android\Sdk\platform-tools\adb.exe
[ +144 ms] executing: C:\Users\reypa\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[ +192 ms] Building APK
[  +58 ms] Running Gradle task 'assembleDebug'...
[  +29 ms] Using gradle from E:\Projects\test\android\gradlew.bat.
[ +101 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +376 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+9-b60-7590822, mixed mode)
[   +4 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +370 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+9-b60-7590822, mixed mode)
[   +7 ms] executing: [E:\Projects\test\android/] E:\Projects\test\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=E:\Projects\test\lib\main.dart
-Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+15397 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [ +182 ms] executing: [C:\Users\reypa\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+2180 ms] [+2197 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] [   +1 ms] 5464c5bac742001448fe4fc0597be939379f88ea
[  +26 ms] [   +2 ms] executing: [C:\Users\reypa\flutter/] git tag --points-at 5464c5bac742001448fe4fc0597be939379f88ea
[ +264 ms] [ +241 ms] Exit code 0 from: git tag --points-at 5464c5bac742001448fe4fc0597be939379f88ea
[   +1 ms] [        ] 2.10.5
[   +1 ms] [  +33 ms] executing: [C:\Users\reypa\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +101 ms] [ +109 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +1 ms] [        ] executing: [C:\Users\reypa\flutter/] git ls-remote --get-url origin
[  +95 ms] [ +128 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] [        ] https://github.com/flutter/flutter.git
[ +204 ms] [ +204 ms] executing: [C:\Users\reypa\flutter/] git rev-parse --abbrev-ref HEAD
[ +199 ms] [ +146 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] stable
[ +193 ms] [ +248 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +98 ms] [  +17 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +291 ms] [ +363 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +8 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +260 ms] [ +261 ms] Initializing file store
[  +99 ms] [ +145 ms] Done initializing file store
[ +308 ms] [ +227 ms] Skipping target: gen_localizations
[   +4 ms] [  +44 ms] Skipping target: gen_dart_plugin_registrant
[+2782 ms] [+2736 ms] Skipping target: kernel_snapshot
[+1502 ms] [+1517 ms] Skipping target: debug_android_application
[   +1 ms] [   +1 ms] Persisting file store
[   +2 ms] [  +35 ms] Done persisting file store
[   +5 ms] [  +17 ms] build succeeded.
[  +88 ms] [  +51 ms] "flutter assemble" took 5,500ms.
[ +305 ms] [ +358 ms] ensureAnalyticsSent: 342ms
[   +1 ms] [   +2 ms] Running shutdown hooks
[   +1 ms] [   +1 ms] Shutdown hooks complete
[  +92 ms] [  +14 ms] exiting with code 0
[ +201 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[ +100 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +111 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders NO-SOURCE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[  +90 ms] > Task :app:mergeDebugAssets
[ +894 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +3 ms] > Task :app:generateDebugResources UP-TO-DATE
[ +195 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +4 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[ +394 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifestForPackage UP-TO-DATE
[ +390 ms] > Task :app:processDebugResources UP-TO-DATE
[  +96 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +97 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :app:compileDebugSources UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[   +1 ms] > Task :app:compressDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +3 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[ +107 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +2 ms] > Task :app:dexBuilderDebug UP-TO-DATE
[   +1 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +83 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +2 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[  +91 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +1 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[ +105 ms] > Task :app:packageDebug FAILED
[ +295 ms] FAILURE: Build failed with an exception.
[   +6 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:packageDebug'.
[   +1 ms] > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
[   +1 ms]    > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "C:\Users\reypa\.android\debug.keystore": Integrity check failed:
java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available
[   +4 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 27s
[   +4 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +1 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] 31 actionable tasks: 5 executed, 26 up-to-date
[ +768 ms] Running Gradle task 'assembleDebug'... (completed in 29.6s)
[   +6 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 33,168ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +206 ms] ensureAnalyticsSent: 196ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by danagbemava-nc** [comment]
Hi @ganultap, kindly check this [SO thread](https://stackoverflow.com/questions/67631927/error-building-aab-flutter-android-integrity-check-failed-java-security-n) to see if it helps you with your issue. 

Closing from here as this isn't actually a framework issue. 

Thank you
