### ISSUE TITLE
[Framework] Using some widgets as compile time constants throw `Evaluation of this constant expression throws an exception`

### ISSUE THREAD

**Issue by dvoloshyn** [flutter/flutter#102460]
## Steps to Reproduce

**Expected results:**
I should be able to use `NavigationBar` as compile time constant as it has const constructor like this
```
const navigationBar = NavigationBar(
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.contacts),
            label: 'Contacts',
          ),
          NavigationDestination(
            icon: Icon(Icons.people),
            label: 'Players',
          ),
        ],
      );
```

**Actual results:**
The code above does not compile throwing
```
lib/domains/user/contacts.dart:55:29: Error: Constant evaluation error:
      const navigationBar = NavigationBar(
                            ^
/opt/flutter/packages/flutter/lib/src/material/navigation_bar.dart:76:53: Context: The property 'length' can't be accessed on '<Widget>[NavigationDestination {icon: Icon {icon: IconData {codePoint: 57743.0, fontFamily: "MaterialIcons", fontPackage: null, matchTextDirection: false}, size: null, color: null, semanticLabel: null, textDirection: null}, selectedIcon: null, label: "Contacts", tooltip: null}, NavigationDestination {icon: Icon {icon: IconData {codePoint: 58502.0, fontFamily: "MaterialIcons", fontPackage: null, matchTextDirection: false}, size: null, color: null, semanticLabel: null, textDirection: null}, selectedIcon: null, label: "Players", tooltip: null}]' in a constant expression.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/opt/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'NavigationDestination' is from 'package:flutter/src/material/navigation_bar.dart' ('/opt/flutter/packages/flutter/lib/src/material/navigation_bar.dart').
 - 'Icon' is from 'package:flutter/src/widgets/icon.dart' ('/opt/flutter/packages/flutter/lib/src/widgets/icon.dart').
 - 'IconData' is from 'package:flutter/src/widgets/icon_data.dart' ('/opt/flutter/packages/flutter/lib/src/widgets/icon_data.dart').
  }) :  assert(destinations != null && destinations.length >= 2),
                                                    ^
lib/domains/user/contacts.dart:55:13: Context: While analyzing:
      const navigationBar = NavigationBar(
            ^
Failed to compile application.
```

**`Flutter --version` output:**
```
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (6 days ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

**Comment by danagbemava-nc** [comment]
Hi @dvoloshyn, please provide a complete minimal reproducible code sample so that we may verify this. 

Thank you

**Comment by dvoloshyn** [comment]
Hi @danagbemava-nc,

Sure, here it is!
```
import 'package:flutter/material.dart';

void main() {
  const navigationBar = NavigationBar(
    destinations: const [
      NavigationDestination(
        icon: Icon(Icons.contacts),
        label: 'Contacts',
      ),
      NavigationDestination(
        icon: Icon(Icons.people),
        label: 'Players',
      ),
    ],
  );
}
```

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

I discovered that the same thing happens with `NavigationRail`. There may be other widgets that are affected by this but at this time, I haven't discovered any other widgets. The result of `flutter analyze -v` is shared below. Leaving this for further input from the team. 

SN: I noticed `BottomNavigationBar` doesn't have a const ctor, could this be the reason why?

@dvoloshyn in the interim, you can use `final` instead of `const` and it should work just fine. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
   return const MaterialApp(
     home:  MyHome(),
   );
  }
}

class MyHome extends StatefulWidget {
 const MyHome({Key? key}) : super(key: key);

  @override
  State<MyHome> createState() => _MyHomeState();
}

class _MyHomeState extends State<MyHome> {
  @override
  Widget build(BuildContext context) {
  const material = Material(
    color: Colors.blue,
    child: Text('Navigation Bar'),
  );

  const bottomAppBar = BottomAppBar(color: Colors.blue);

  const navigationBar = NavigationBar(
    destinations:  [
      NavigationDestination(icon: Icon(Icons.home), label: 'label'),
      NavigationDestination(icon: Icon(Icons.home), label: 'label'),
      NavigationDestination(icon: Icon(Icons.home), label: 'label'),
    ],
  );

  const navigationRail = NavigationRail(
    destinations: [
      NavigationRailDestination(icon: Icon(Icons.home), label: Text('label')),
      NavigationRailDestination(icon: Icon(Icons.home), label: Text('label')),
      NavigationRailDestination(icon: Icon(Icons.home), label: Text('label')),
    ],
    selectedIndex: 0,
  );

   return const Scaffold(
     body: Center(child: Text('Some text'),),
   );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (8 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.733, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.733 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision de6689aaa3 (2 hours ago), 2022-04-26 01:02:38 -0400
    • Engine revision 79152137a9
    • Dart version 2.18.0 (build 2.18.0-57.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[flutter analyze -v](https://github.com/flutter/flutter/files/8560551/analysis.txt)

**Comment by mraleph** [comment]
At this point this is working as intended (see details in https://github.com/dart-lang/language/issues/1296) 

Flutter framework should probably drop `const` constructor from this class to make it less surprising. 

/cc @lrhn @eernstg

**Comment by eernstg** [comment]
New kinds of constant expressions are always expensive, but it does seem [doable](https://github.com/dart-lang/language/issues/1296#issuecomment-1109466904) to support `length` on certain constant collections as a constant expression.

**Comment by goderbauer** [comment]
Interesting. So, `value.length` is only allowed in a const expression if `value` is a String? Is that the only case?

I wonder if we could get a lint that would remind us to not declare these constructors as const (https://github.com/dart-lang/linter/issues/3367).

Also, currently, if we remove the const from this class, another lint wants the const back on it: https://github.com/dart-lang/linter/issues/3366.

**Comment by eernstg** [comment]
@dvoloshyn, you may also be interested in the following issue: https://github.com/dart-lang/language/issues/2219.
