### ISSUE TITLE
State._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:645:12) #3  

### ISSUE THREAD

**Issue by diptesh2082** [flutter/flutter#102584]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
<summary> error log </summary>

```

State._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:645:12)
#3      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:449:55)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#5      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:449:7)
#6      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:298:9)
#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#22     _invoke1 (dart:ui/hooks.dart:170:10)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#ca987
  start behavior: start
====================================================================================================

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 651 pos 12: '_hold == null || _drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:

```

</details>

**Comment by darshankawar** [comment]
@diptesh2082 
Although you shared error log, but didn't provide any code sample which triggers it, so we can't make this actionable. Please don't create half-baked issues. Always try to use new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and fill out requested details so that we'll have enough details to work with.
Closing for now, as no details are provided.
