### ISSUE TITLE
Camera: stop after pause crashes camera

### ISSUE THREAD

**Issue by sunilguptasg** [flutter/flutter#102565]
## Steps to Reproduce
await cameraController.startVideoRecording(); < user button click
then
await cameraController.pauseVideoRecording(); < user button click
then
await cameraController.stopVideoRecording(); < user button click

causes this:

Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:56866/dart_sdk.js:5067:11)
    at Object.nullCheck (http://localhost:56866/dart_sdk.js:5394:30)
at master_camera._CameraMasterPageState.new.stopVideoRecording (http://localhost:56866/packages/tuotr_main_app/pages/master_camera.dart.lib.js:3103:127)
    at stopVideoRecording.next (<anonymous>)
    at runBody (http://localhost:56866/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:56866/dart_sdk.js:40621:7)
at master_camera._CameraMasterPageState.new.stopVideoRecording (http://localhost:56866/packages/tuotr_main_app/pages/master_camera.dart.lib.js:3102:20)
at master_camera._CameraMasterPageState.new.onStopButtonPressed (http://localhost:56866/packages/tuotr_main_app/pages/master_camera.dart.lib.js:3056:14)
    at onStopButtonPressed.next (<anonymous>)
    at http://localhost:56866/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:56866/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:56866/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:56866/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:56866/dart_sdk.js:35969:17)
    at _Future.new.[_complete] (http://localhost:56866/dart_sdk.js:35809:25)
    at http://localhost:56866/dart_sdk.js:34918:32
    at internalCallback (http://localhost:56866/dart_sdk.js:26619:11)

===========

await cameraController.startVideoRecording(); < user button click
then
await cameraController.pauseVideoRecording(); < user button click
then
await cameraController.resumeVideoRecording(); < user clicking 'stop'
await Future.delayed(const Duration(milliseconds: 2000), () {}); << not needed if resume was manually started by a button press
await cameraController.stopVideoRecording();

works fine.

the resume and delay is only needed if STOP is executed on a PAUSED video. A STOP on a RECORDING/RESUMED video has no problems.

**Comment by sunilguptasg** [comment]
Issue was something else.
