### ISSUE TITLE
M1 Command PhaseScriptExecution failed with a nonzero exit code / encounted error while building this device

### ISSUE THREAD

**Issue by Uniyo-Ltd** [flutter/flutter#102591]
Hi everyone,

Im Running flutter build iOS and flutter run on Xcode, android studio and terminal everything in rosseta 2 and Im getting this error not sure why, we have been weeks trying  different things and nothing is working.

I was expecting that it runs but its doesn't.

MacBook Pro (13-inch, M1, 2020)
macOS Monterey version 12.3.1
Home-brew 
CocoaPods

Command: flutter build iOS 

Xcode: 
Command PhaseScriptExecution failed with a nonzero exit code.

terminal: 
Encounted error while building this device.

Android studio:
Encountered error while building for device.

Xcode keeps asking me to update to recommended to recommended settings 12.0 repeatedly after updating something keeps changing them back.

Please someone help!

hope someone can help solve this mystery.

Excuse any mistake in the query, never posted before, please let me know if theres anything else needed.

thank you in advance  !
 
[android studio .pdf](https://github.com/flutter/flutter/files/8565271/android.studio.pdf)
[flutter analize.pdf](https://github.com/flutter/flutter/files/8565193/flutter.analize.pdf)
[flutter doctor -v.pdf](https://github.com/flutter/flutter/files/8565197/flutter.doctor.-v.pdf)
[podfile lock.pdf](https://github.com/flutter/flutter/files/85
<img width="953" alt="Screenshot 2022-04-26 at 13 11 34" src="https://user-images.githubusercontent.com/71023066/165351052-a0b4d48e-eb4b-49d7-9a92-a16dacf0847f.png">
65206/podfile.lock.pdf)
[Podfile.pdf](https://github.com/flutter/flutter/files/8565210/Podfile.pdf)
[xattr -lr ..pdf](https://github.com/flutter/flutter/files/8565215/xattr.-lr.pdf)
<img width="955" alt="Screenshot 2022-04-26 at 13 12 04" src="https://user-images.githubusercontent.com/71023066/165351941-e54c72e4-0be9-4602-8cc5-7c4dd4dd505b.png">
[android studio .pdf](https://github.com/flutter/flutter/files/8565769/android.studio.pdf)
>

**Comment by maheshmnj** [comment]
Hi @Uniyo-Ltd, Thanks for filing the issue. Looking at the logs in  seems to indicate errors in your code hence the build failure. 

```console
In module 'FirebaseFunctions' imported from /Users/aryuna/studioprojects/Uniyo/
ios/Pods/Headers/Public/Firebase/Firebase.h:54:
 /Users/aryuna/studioprojects/Uniyo/ios/Pods/FirebaseFunctions/
FirebaseFunctions/Sources/Public/FirebaseFunctions/FIRFunctions.h:92:24: note:
'useFunctionsEmulatorOrigin:' has been explicitly marked deprecated here
 __attribute__((deprecated("Use useEmulator(host:port:) instead.")));
 ^
 4 warnings generated.
 lib/Screens/add/supporting_screens_add/sell.dart:1084:7: Error: Comment starting
with '/*' must end with '*/'.
 /*Row(
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:1061:19: Error: Can't find ')' to
match '('.
 Text(
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:1060:31: Error: Can't find ']' to
match '['.
 children: <Widget>[
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:1058:17: Error: Can't find ')' to
match '('.
 Column(
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:1057:19: Error: Can't find ']' to
match '['.
 children: [
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:1056:14: Error: Can't find ')' to
match '('.
 Row(
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:1044:21: Error: Can't find ')' to
match '('.
 return Container(
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:1043:30: Error: Can't find '}' to
match '{'.
 Widget _titleInstruction() {
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:776:74: Error: Can't find '}' to
match '{'.
 class _SellState extends State<Sell> with SingleTickerProviderStateMixin {
 ^
 Error: Couldn't resolve the package 'quick_feedback' in 'package:quick_feedback/
quick_feedback.dart'.
 Error: Couldn't resolve the package 'lottie' in 'package:lottie/lottie.dart'.
 lib/Screens/add/supporting_screens_add/reviews4.dart:4:8: Error: Not found:
'package:quick_feedback/quick_feedback.dart'
 import 'package:quick_feedback/quick_feedback.dart';
 ^
 lib/Screens/add/supporting_screens_add/reviews4.dart:6:8: Error: Not found:
'package:lottie/lottie.dart'
 import 'package:lottie/lottie.dart';
 ^
 lib/Screens/add/supporting_screens_add/reviews2.dart:4:8: Error: Not found:
'package:lottie/lottie.dart'
 import 'package:lottie/lottie.dart';
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:776:7: Error: The non-abstract
class '_SellState' is missing implementations for these members:
 - State.build
 Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
 class _SellState extends State<Sell> with SingleTickerProviderStateMixin {
 ^^^^^^^^^^
 ../flutter/packages/flutter/lib/src/widgets/framework.dart:1341:10: Context:
'State.build' is defined here.
 Widget build(BuildContext context);
 ^^^^^
 lib/Screens/buy/listing_view.dart:448:56: Error: No named parameter with the
name 'data'.
 utils.changeScreen(context, utils.screen.CALENDAR, data: buyData);
 ^^^^
 lib/class/Util.dart:50:1: Context: Found this candidate, but the arguments don't
match.
 changeScreen(context, int screen) {
 ^^^^^^^^^^^^
 lib/Screens/chat/chat.dart:272:29: Error: Undefined name 'notificationService'.
 utils.notificationService.sendNotificationToUser(globals.receiverMail,
'New message from '+loggedInUser.email, messageText.substring(0, 50),
{'OPEN_SCREEN': 8, 'click_action': 'FLUTTER_NOTIFICATION_CLICK'});
 ^^^^^^^^^^^^^^^^^^^
 lib/Screens/add/supporting_screens_add/sell.dart:1076:7: Error: Expected named
argument.
 Text(
 ^
 lib/Screens/add/supporting_screens_add/sell.dart:1061:19: Error: No named
parameter with the name '#2'.
 Text(
 ^^...
 ../flutter/packages/flutter/lib/src/widgets/text.dart:362:9: Context: Found this
candidate, but the arguments don't match.
 const Text(
 ^^^^
 lib/Screens/add/supporting_screens_add/sell.dart:1083:8: Error: Expected ';' after
this.
 ),
 ^
 lib/widgets/floating_tabbar.dart:152:18: Error: The getter 'Lottie' isn't defined for
the class '_TabBarWidgetState'.
 - '_TabBarWidgetState' is from 'package:uniyo/widgets/floating_tabbar.dart' ('lib/
widgets/floating_tabbar.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'Lottie'.
 child: Lottie.asset(
 ^^^^^^
 lib/Screens/me/Selling/selling.dart:436:70: Error: The getter 'TEST' isn't defined for
the class 'Screen'.
 - 'Screen' is from 'package:uniyo/class/Util.dart' ('lib/class/Util.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'TEST'.
 utils.changeScreen(context, utils.screen.TEST);
 ^^^^
 lib/class/Basket.dart:175:33: Error: The getter 'bookingTime' isn't defined for the 
class 'BasketItem'.
 - 'BasketItem' is from 'package:uniyo/class/BasketItem.dart' ('lib/class/
BasketItem.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'bookingTime'.
 int bookingTime = service.bookingTime;
 ^^^^^^^^^^^
 lib/Screens/home/homepage.dart:140:27: Error: The getter 'SliverStaggeredGrid'
isn't defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:uniyo/Screens/home/homepage.dart' ('lib/
Screens/home/homepage.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'SliverStaggeredGrid'.
 SliverStaggeredGrid.count(
 ^^^^^^^^^^^^^^^^^^^
 lib/Screens/home/homepage.dart:247:42: Error: The getter 'StaggeredTile' isn't
defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:uniyo/Screens/home/homepage.dart' ('lib/
Screens/home/homepage.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'StaggeredTile'.
 return StaggeredTile.count(4, 4);
 ^^^^^^^^^^^^^
 lib/Screens/home/homepage.dart:253:42: Error: The getter 'StaggeredTile' isn't
defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:uniyo/Screens/home/homepage.dart' ('lib/
Screens/home/homepage.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'StaggeredTile'.
 return StaggeredTile.count(2, 4);
 ^^^^^^^^^^^^^
 lib/Screens/home/homepage.dart:262:42: Error: The getter 'StaggeredTile' isn't
defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:uniyo/Screens/home/homepage.dart' ('lib/
Screens/home/homepage.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'StaggeredTile'.
 return StaggeredTile.count(2, 2);
 ^^^^^^^^^^^^^
 lib/Screens/home/homepage.dart:265:42: Error: The getter 'StaggeredTile' isn't
defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:uniyo/Screens/home/homepage.dart' ('lib/
Screens/home/homepage.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'StaggeredTile'.
 return StaggeredTile.count(4, 2);
 ^^^^^^^^^^^^^
 lib/Screens/home/homepage.dart:273:42: Error: The getter 'StaggeredTile' isn't
defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:uniyo/Screens/home/homepage.dart' ('lib/
Screens/home/homepage.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'StaggeredTile'.
 return StaggeredTile.count(2, 2);
 ^^^^^^^^^^^^^
 lib/Screens/home/homepage.dart:275:40: Error: The getter 'StaggeredTile' isn't
defined for the class '_HomePageState'.
 - '_HomePageState' is from 'package:uniyo/Screens/home/homepage.dart' ('lib/
Screens/home/homepage.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'StaggeredTile'.
 return StaggeredTile.count(1, 1);
 ^^^^^^^^^^^^^
 lib/widgets/Search.dart:179:60: Error: The getter 'REQUEST2' isn't defined for the
class 'Screen'.
 - 'Screen' is from 'package:uniyo/class/Util.dart' ('lib/class/Util.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'REQUEST2'.
 utils.changeScreen(context, utils.screen.REQUEST2);
 ^^^^^^^^
 lib/Screens/add/supporting_screens_add/reviews4.dart:52:32: Error: The getter
'Lottie' isn't defined for the class 'reviews4'.
 - 'reviews4' is from 'package:uniyo/Screens/add/supporting_screens_add/
reviews4.dart' ('lib/Screens/add/supporting_screens_add/reviews4.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'Lottie'.
 child: Lottie.asset(
 ^^^^^^
 lib/Screens/add/supporting_screens_add/reviews2.dart:26:16: Error: The getter
'Lottie' isn't defined for the class 'reviews2'.
 - 'reviews2' is from 'package:uniyo/Screens/add/supporting_screens_add/
reviews2.dart' ('lib/Screens/add/supporting_screens_add/reviews2.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or
field named 'Lottie'.
 var anim = Lottie.asset('assets/animations/check9.json',
 ^^^^^^
 Unhandled exception:
 FileSystemException(uri=org-dartlang-untranslatableuri:package%3Aquick_feedback%2Fquick_feedback.dart;
message=StandardFileSystem only supports file:* and data:* URIs)
 #0 StandardFileSystem.entityForUri (package:front_end/src/api_prototype/
standard_file_system.dart:34:7)
 #1 asFileUri (package:vm/kernel_front_end.dart:623:37)
 #2 writeDepfile (package:vm/kernel_front_end.dart:763:21)
 <asynchronous suspension>
 #3 FrontendCompiler.compile (package:frontend_server/
frontend_server.dart:586:9)
 <asynchronous suspension>
 #4 starter (package:flutter_frontend_server/server.dart:85:12)
 <asynchronous suspension>
 #5 main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/
starter.dart:13:24)
 <asynchronous suspension>
 Failed to package /Users/aryuna/studioprojects/Uniyo.
 Command PhaseScriptExecution failed with a nonzero exit code
 note: Using new build system
 note: Planning
 note: Build preparation complete
 note: Building targets in dependency order
 /Users/aryuna/studioprojects/Uniyo/ios/Pods/Pods.xcodeproj: warning: The iOS
Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0,
but the range of supported deployment target versions is 9.0 to 15.4.99. (in target
'leveldb-library' from project 'Pods')
 Result bundle written to path:
 /var/folders/75/1k4jl9xd4qn5p8fstmtzs43h0000gn/T/flutter_tools.Ajgo6z/
flutter_ios_build_temp_dirfVfbjn/temporary_xcresult_bundle
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
``` 

 Please fix the above errors and feel free to write back if you still encounter the build failure after fixing those errors.
