### ISSUE TITLE
Trouble Installing Flutter

### ISSUE THREAD

**Issue by Edogmonkey** [flutter/flutter#10263]
## Explanation

I am new to Flutter (and Dart) and I was trying to install it on my Windows desktop (it installed fine on my Linux laptop).  I was initially able to install it but was getting a compilation error when I tried running the base app so I decided to reinstall the entire thing.  I used `git clone` to clone the repository and then used `flutter doctor` after adding flutter\bin to the path.  Every time I do so it outputs this same error log.  I've also tried uninstalling the Android SDK and Android Studio.  I suspect that it has to do with the registry as I was originally able to install it.

## Log

FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\DaVucci\flutter\bin\cache\artifacts\engine\android-arm-profile/windows-x64\gen_snapshot.exe' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:599)
#1      _File.openSync (dart:io/file_impl.dart:454)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:568)
#3      _LocalFileSystemEntity&ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:120)
#4      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:179)
#5      Cache._downloadFileToCache (package:flutter_tools/src/cache.dart:214)
<asynchronous suspension>
#6      FlutterEngine._downloadItem (package:flutter_tools/src/cache.dart:389)
#7      FlutterEngine.download (package:flutter_tools/src/cache.dart:362)
<asynchronous suspension>
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:197)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:200)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     Future.Future.sync (dart:async/future.dart:208)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:156)
#17     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1465)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#26     main (file:///C:/Users/DaVucci/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

[✓] Flutter (on Microsoft Windows [Version 10.0.15063], channel alpha)
    • Flutter at C:\Users\DaVucci\flutter
    • Framework revision 973304d5fb (4 days ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\DaVucci\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = C:\Users\DaVucci\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] WebStorm (version 2017.1)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • None

```

## Doctor

It seems that the line `✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)` is the most simple explanation of the problem and likely refers to `gen_snapshot.exe` on the first line.  I went to the link but it refers to Linux only and doesn't seem to be the same problem.

**Comment by eseidelGoogle** [comment]
Looks like it was unable to write to the file `C:\Users\DaVucci\flutter\bin\cache\artifacts\engine\android-arm-profile/windows-x64\gen_snapshot.exe` Are there any funny permissions going on?  FYI @goderbauer

**Comment by Edogmonkey** [comment]
@eseidelGoogle not to my knowledge.  `gen_snapshot.exe` doesn't even exist.  I'm guessing its created after I run `flutter doctor` by whatever is being downloaded.

**Comment by Edogmonkey** [comment]
Ok well it must of been something with the permissions because I installed to my desktop and it worked perfectly fine.  Very odd.

**Comment by toshoajibade** [comment]
@EvanVujcec Hello, were you able to solve this issue? I have been trying to install flutter on WSL for days to no avail
