### ISSUE TITLE
[web][Canvaskit]: App throws `Error: Failed to encode the image into bytes.` while decoding images into bytes.

### ISSUE THREAD

**Issue by CodeDoctorDE** [flutter/flutter#102683]
## Steps to Reproduce

1. Install flutter_file_picker (or use another method to get the data in a variable)
2. Put this action in a button 
3. Run the action (set the web renderer to canvaskit and use the chrome browser)
4. See the error 

**Expected results:** 

The data should get successfully compiled. I tried it on firefox and the native platforms (android, linux, windows) and it works.

**Actual results:** 

An error (see logs)

<details>
<summary>Code sample</summary>

```dart
            var files = await FilePicker.platform.pickFiles(
                type: FileType.image, allowMultiple: false, withData: true);
            if (files?.files.isEmpty ?? true) return;
            final e = files!.files.first;
            var content = e.bytes!;
            print(base64Encode(content));
            ui.Codec codec;
            try {
              codec = await ui
                  .instantiateImageCodec(content);
            } catch (e) {
              if (kDebugMode) {
                print(e);
              }
              return;
            }
            var frame = await codec.getNextFrame();
            var image = frame.image.clone();

            var bytes = await image.toByteData(format: ui.ImageByteFormat.png);
            print(bytes.toString());
```

</details>

<details>
  <summary>Logs</summary>

```
Error: Failed to encode the image into bytes.
    at Object.createErrorWithStack (http://localhost:56226/dart_sdk.js:5093:12)
    at Function._throw (http://localhost:56226/dart_sdk.js:20399:18)
    at Function.throwWithStackTrace (http://localhost:56226/dart_sdk.js:20396:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:56226/dart_sdk.js:40921:18)
    at Object._microtaskLoop (http://localhost:56226/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:56226/dart_sdk.js:40784:13)
    at http://localhost:56226/dart_sdk.js:36261:9

and the debugger stops in the line codec = await ui.instantiateImageCodec(content);
```

```
flutter analyze
Analyzing app...
No issues found! (ran in 2.6s)
```

```
[✓] Flutter (Channel beta, 2.13.0-0.2.pre, on Microsoft Windows [Version 10.0.22000.652], locale de-DE)
    • Flutter version 2.13.0-0.2.pre at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8662e22bac (7 days ago), 2022-04-20 08:21:52 -0700
    • Engine revision 24a02fa5ee
    • Dart version 2.17.0 (build 2.17.0-266.5.beta)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\src\Android
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\src\Android
    • Java binary at: C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\bin\java.exe
    • Java version OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[☠] Visual Studio - develop for Windows (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues. (This is already reported here: #102451


[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Users\wusel\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.7172.25
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\wusel\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5080.210
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at C:\Users\wusel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.39.20220405

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.652]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

I'm using the latest chromium 100.0.4896.127

</details>

<details>
  <summary>Preview in a running web app</summary>

  This problem can be seen in my note taking app: https://preview.butterfly.linwood.dev
  Try clicking on the background add click on insert. Then click on image and choose a random png image. In the console you get an error. On firefox everything works.

**Comment by darshankawar** [comment]
@CodeDoctorDE 
Can you provide us complete minimal code sample ?

**Comment by CodeDoctorDE** [comment]
Okay, do you know how I get a png picture data in the minimal code sample?

**Comment by CodeDoctorDE** [comment]
Okay I built a dartpad example for this: https://dartpad.dev/?id=d1008ae251cda51d1eebc611570638d2

Currently the decoding of the image works on dartpad. When creating a blank project, add this in the main.dart and run it on chrome using `flutter run -d chrome` it throws the error. An example input can be `https://cdn.pixabay.com/photo/2022/01/07/07/13/chicago-6921293_960_720.jpg` (it's an image from pixabay)

This is the minimal code that is needed. `content` is a variable where the image bytes are stored
```dart
ui.Codec codec;
            try {
              codec = await ui
                  .instantiateImageCodec(content);
            } catch (e) {
              print(e);
              return;
            }
            var frame = await codec.getNextFrame();
            var image = frame.image.clone();

            var bytes = await image.toByteData(format: ui.ImageByteFormat.png);
            print(bytes.toString());
```

**Comment by darshankawar** [comment]
Thanks for the updated code. Using it, I observed that, the error is shown in canvaskit mode, but the decoding seem to be working in html mode, as it generates the bytes and doesn't throw the error: `Error: Failed to encode the image into bytes.`.

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.5 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.791, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.791 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d873157287 (87 minutes ago), 2022-04-27 23:14:06 -0400
    • Engine revision 220613fc0b
    • Dart version 2.18.0 (build 2.18.0-65.0.dev)
    • DevTools version 2.12.2
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:ui' as ui;
import 'dart:convert';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  final TextEditingController _urlController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return ListView(children: [
      TextField(
        controller: _urlController,
      ),
      TextButton(
          child: const Text('Decode image!'),
          onPressed: () async {
            final response = await http.get(Uri.parse(_urlController.text));
            final content = response.bodyBytes;
            print(base64Encode(content));
            ui.Codec codec;
            try {
              codec = await ui
                  .instantiateImageCodec(content);
            } catch (e) {
              print(e);
              return;
            }
            var frame = await codec.getNextFrame();
            var image = frame.image.clone();

            var bytes = await image.toByteData(format: ui.ImageByteFormat.png);
            print(bytes.toString());
          }
      )
    ]);
  }
}

```

</details>

**Comment by jpohhhh** [comment]
Googler here, jamesoleary@, been chasing this issue for a few months on an internal project.

This seems to be related to the new image codec decoding support announced for Flutter 3: if I replace references to browserSupportsImageDecoder with `false` in ex. canvaskit/image.dart, it works again.

To summarize:
- on Chrome
- with a CanvasKit web app
- using web platform image decoders
- ui.Image.toByteData() fails and throws an error "Failed to encode the image into bytes."

**Comment by yjbanov** [comment]
The fix is likely the same as https://github.com/flutter/flutter/issues/103803, which @hterkelsen is currently working on.

**Comment by hterkelsen** [comment]
In the sample in https://github.com/flutter/flutter/issues/102683#issuecomment-1112161448 I can get it to work if I change the `toByteData` line to:

```
var bytes = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
```

Suggesting that the problem is with the PNG encoding. I will keep digging into this
