### ISSUE TITLE
Accessibility focus doesn't work as expected on landscape mode in Android (and iOS g3)

### ISSUE THREAD

**Issue by Caffo17** [flutter/flutter#102725]
Internal: b/317958179

I'm struggling with an accessibility issue on a project which i'm working on. 
I can't show you the code because the project is under NDA, but fortunately (or not) the issue is replicable on the Flutter template project (the counter one).

## Steps to Reproduce
1. Execute `flutter run` on the counter project sample on an Android device
2. Activate TalkBack
3. Turn the device on the right in landscape mode (NavBar should be on the left)

**Expected results:** 
Accessibility focus and TalkBack should work correctly.

**Actual results:** 
When the app is in portrait mode, the TalkBack and the accessibility focus work as expected. (image 1 and 2)

Instead, on landscape mode, the TalkBack work as expected, but the accessibility focus has a sort of left padding. In this way, the green box doesn't wrap correctly the components and often the double tap gesture doesn't work on the FAB. (image 3, 4 and video).

<img src="https://i.stack.imgur.com/NJVdO.png" width="270" height="585">
<img src="https://i.stack.imgur.com/CNkpv.png" width="270" height="585">

<img src="https://i.stack.imgur.com/jeik7.png" width="585" height="270">
<img src="https://i.stack.imgur.com/zoWvh.png" width="585" height="270">

https://user-images.githubusercontent.com/32623084/165699807-ea5c1cfb-5d83-4e80-89c3-7883e29887c8.mp4

<details>
  <summary>Logs</summary>

```
```

```
No issues found! (ran in 2.3s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6.1 20G224 darwin-x64, locale en-IT)
    • Flutter version 2.10.0 at /Users/EFACCOMA1/fvm/versions/2.10.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 months ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/EFACCOMA1/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (4 available)
    • SM G973F (mobile)  • RF8M32V5EFX                          • android-arm64  • Android 12 (API 31)
    • iPhone 13 (mobile) • 16F2ADD6-7EAC-4478-AD57-BABF5FF6C825 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. Tested on `Poco X3 NFC`. 

In my testing this issue only occurred when the device was in `Landscape_right`, it worked as expected in `Landscape_left`. See video below

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/165729414-7c2a1779-b284-47bc-aef0-d780eb0eebf4.mp4

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (10 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.792, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.792 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e42b9dd516 (4 hours ago), 2022-04-28 01:39:05 -0400
    • Engine revision ba644fafb2
    • Dart version 2.18.0 (build 2.18.0-65.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by xster** [comment]
Setting to P1 according to b/317958179

**Comment by bleroux** [comment]
I investigated this issue and I found it is related to some engine code, see: https://github.com/flutter/engine/blob/1405cb7b6e7454358953124914613616e53a5075/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L1701-L1711
which was added in https://github.com/flutter/engine/pull/27083.

<details><summary>Minimal code sample (without MaterialApp)</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const Directionality(
      textDirection: TextDirection.ltr,
      child: Center(
        child: Text('Hello', style: TextStyle(fontSize: 80)),
      ),
    );
  }
}

``` 

</details> 

The issue is only visible when system navigation is set to 'button navigation' (it does not repro with 'gesture navigation').
It is reproducible when the device is rotated to the right (navigation buttons are on the left in this case).


https://github.com/flutter/flutter/assets/840911/ab0d661d-84e6-4624-b3dd-cb475c3c637e

@camsim99 
> The buganizer issue shows that this also affects iOS devices, so we are assigning to the framework team to take a look.

We were not able to reproduce this issue on iOS (thank you @TahaTesser for trying this).
Maybe the buganizer issue is wrong for iOS or more context is needed?

**Comment by gmackall** [comment]
> We were not able to reproduce this issue on iOS (thank you @TahaTesser for trying this). Maybe the buganizer issue is wrong for iOS or more context is needed?

Thanks for the testing! We are trying to narrow down if this is a framework issue, or simultaneous embedder issues with iOS and Android. Here is the iOS reproduction that was provided, would it be possible to test this as well?

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: false),
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title, style: TextStyle(fontFamily: 'ProductSans')),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Padding(
            padding: EdgeInsets.symmetric(horizontal: 16.0, vertical: 100.0),
            child: Text(
              'Button tapped $_counter time${_counter == 1 ? '' : 's'}.',
              textAlign: TextAlign.center,
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
@gmackall 

I can reproduce the issue with your code sample on iPhone 14 Pro Max. Unlike Android, this bug  in both left and right landscape orientation and only on the centered text.

https://github.com/flutter/flutter/assets/48603081/cc0d8279-0ca1-43bf-b280-5a877510954b

**Comment by goderbauer** [comment]
@hangyujin could you take a look at this a11y issue?

**Comment by chunhtai** [comment]
downgrad to p2 as we may not have time to get to this in Q1 2025

**Comment by chunhtai** [comment]
It looks like the accessibility bound coordinates in native android and screen coordinate doesn't include safe area. It is probably the same thing for ios. will try to come up with a fix

**Comment by chunhtai** [comment]
looks like for Android a special logic is added to account for left inset four years ago https://github.com/flutter/engine/pull/27083

and the newer version of Android seems to not take this into account anymore. Will need to bisect which Android changes the behavior or whether this workaround is no longer needed

**Comment by chunhtai** [comment]
can't reproduce on iphone iOS 18.3.2 22D82

**Comment by chunhtai** [comment]
Android part is fixed. I will close this issue since i can't repro iOS, let me know if you are still having the issue

**Comment by jmagman** [comment]
@chunhtai can b/317958179 be closed?
