### ISSUE TITLE
TextField not work

### ISSUE THREAD

**Issue by zhecaoapp** [flutter/flutter#102821]
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 2469 pos 12: 'attached': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2469:12)
#3      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2548:39)
#4      RenderEditable._snapToPhysicalPixel (package:flutter/src/rendering/editable.dart:2103:33)
#5      RenderEditable.getLocalRectForCaret (package:flutter/src/rendering/editable.dart:1597:23)
#6      EditableTextState._updateComposingRectIfNeeded (package:flutter/src/widgets/editable_text.dart:2654:40)
#7      EditableTextState._updateComposingRectIfNeeded.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:2659:49)
#8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#10     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#14     _invoke (dart:ui/hooks.dart:150:10)
#15     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#16     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```

**Comment by darshankawar** [comment]
@zhecaoapp 
When you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with. Only providing error log isn't enough to debug. So please provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and steps to replicate that triggers this error.
