### ISSUE TITLE
ContinousRectangleBorder + BorderSide -> incorrect clipping of background image

### ISSUE THREAD

**Issue by cekrozl1** [flutter/flutter#102869]
## Steps to Reproduce

1. Run `flutter create crbissue` 
2. Import `https://pub.dev/packages/cached_network_image` - it's not mandatory, it's just easier to reproduce with this package
3. Replace the `scaffold body` in `main.dart` by this:
```dart
body: Column(
        children: [
          Container(
              height: 200,
              decoration: ShapeDecoration(
                  color: Colors.indigo,
                  shape: ContinuousRectangleBorder(
                    borderRadius: BorderRadius.circular(30),
                    side: _counter % 2 == 0
                        ? BorderSide.none
                        : BorderSide(color: Colors.orange, width: (_counter % 29).toDouble()),
                  ),
                  image: DecorationImage(
                      fit: _getBoxFit(),
                      image: const CachedNetworkImageProvider(
                          "https://pbs.twimg.com/media/FKNlhKZUcAEd7FY?format=jpg&name=4096x4096")))),
          const SizedBox(
            height: 30,
          ),
          Container(
              height: 200,
              decoration: ShapeDecoration(
                  color: Colors.indigo,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(30),
                    side: _counter % 2 == 0
                        ? BorderSide.none
                        : BorderSide(color: Colors.orange, width: (_counter % 29).toDouble()),
                  ),
                  image: DecorationImage(
                      fit: _getBoxFit(),
                      image: const CachedNetworkImageProvider(
                          "https://pbs.twimg.com/media/FKNlhKZUcAEd7FY?format=jpg&name=4096x4096")))),
        ],
      ),
```
4. Copy this function at the bottom of `_MyHomePageState` :
```dart
BoxFit? _getBoxFit() {
    switch (_counter % 8) {
      case 0:
        return BoxFit.contain;
      case 1:
        return BoxFit.cover;
      case 2:
        return BoxFit.fill;
      case 3:
        return BoxFit.fitHeight;
      case 4:
        return BoxFit.fitWidth;
      case 5:
        return BoxFit.none;
      case 6:
        return BoxFit.scaleDown;
      default:
        return null;
    }
  }
```
5. Press the + button a couple of times.

**Expected results:** 
The filling of the image should behave the exact same way whether `RoundedRectangleBorder` or `ContinousRectangleBorder` is used.

**Actual results:** 
The filling of the image for the `ContinousRectangleBorder` is showing the container background color in cases where it should not.

Here is an example where the `BoxFit` is set to `fitHeight`:
<img width="474" alt="Pasted_Image_30_04_2022__10_13" src="https://user-images.githubusercontent.com/86661185/166097786-1361a18d-337f-4523-97d9-74f12c2183e8.png">

Also : the wider the `BorderSide`, the more visible the background color becomes:
<img width="480" alt="Pasted_Image_30_04_2022__10_17" src="https://user-images.githubusercontent.com/86661185/166097960-c4e36c34-ffda-40c6-ad08-640b99d49256.png">

Without `BorderSide`, both the Continous and Rounded borders behave the same:
<img width="473" alt="Pasted_Image_30_04_2022__10_20" src="https://user-images.githubusercontent.com/86661185/166098004-4a721890-31cb-48bf-ba2d-ffba9fab2db1.png">

It seems like the issue is coming from the combination of ContinousRectangleBorder and BorderSide.

<details>
  <summary>flutter doctor -v</summary>
 
```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-BE)
    • Flutter version 2.10.5 at /Users/cekrozl1/Desktop/OneSpan/MSS/FLUTTER/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cekrozl1/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/cekrozl1/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • SM G973F (mobile) • R58N42DX67H • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you !

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/166203660-1825b6f6-f4be-4ce9-ac40-b755939ee28e.mov

</details>

<details>
<summary>complete code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: [
          Container(
            height: 200,
            decoration: ShapeDecoration(
              color: Colors.indigo,
              shape: ContinuousRectangleBorder(
                borderRadius: BorderRadius.circular(30),
                side: _counter % 3 == 0
                    ? BorderSide.none
                    : BorderSide(
                        color: Colors.orange,
                        width: (_counter % 29).toDouble()),
              ),
              image: DecorationImage(
                fit: _getBoxFit(),
                image: const NetworkImage(
                  "https://pbs.twimg.com/media/FKNlhKZUcAEd7FY?format=jpg&name=4096x4096",
                ),
              ),
            ),
          ),
          const SizedBox(
            height: 30,
          ),
          Container(
            height: 200,
            decoration: ShapeDecoration(
              color: Colors.indigo,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(30),
                side: _counter % 3 == 0
                    ? BorderSide.none
                    : BorderSide(
                        color: Colors.orange,
                        width: (_counter % 29).toDouble()),
              ),
              image: DecorationImage(
                fit: _getBoxFit(),
                image: const NetworkImage(
                  "https://pbs.twimg.com/media/FKNlhKZUcAEd7FY?format=jpg&name=4096x4096",
                ),
              ),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        child: const Icon(Icons.add),
      ),
    );
  }

  BoxFit? _getBoxFit() {
    switch (_counter % 8) {
      case 0:
        return BoxFit.contain;
      case 1:
        return BoxFit.cover;
      case 2:
        return BoxFit.fill;
      case 3:
        return BoxFit.fitHeight;
      case 4:
        return BoxFit.fitWidth;
      case 5:
        return BoxFit.none;
      case 6:
        return BoxFit.scaleDown;
      default:
        return null;
    }
  }

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.848, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.848 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea080e58ba (85 minutes ago), 2022-05-02 01:44:06 -0400
    • Engine revision f57cdbd468
    • Dart version 2.18.0 (build 2.18.0-75.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by bernaferrari** [comment]
Maybe I caused this 👀
If you are able to find in any other Border, please let me know.

**Comment by bleroux** [comment]
This issue is related to `ContinuousRectangleBorder` not respecting the `BorderSide.strokeAlign` property.

The sample could be simplified to illustrate this issue by comparing the border aligments between a `ContinuousRectangleBorder` and a `RoundedRectangleBorder`:

<details><summary>Simplified code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(title: 'Flutter 126561'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(vertical: 30, horizontal: 20),
        child: Column(
          children: [
            Container(
              height: 140,
              decoration: ShapeDecoration(
                color: Colors.indigo,
                shape: ContinuousRectangleBorder(
                  borderRadius: BorderRadius.circular(80),
                  side: const BorderSide(
                    color: Colors.orange,
                    width: 20.0,
                    strokeAlign: BorderSide.strokeAlignInside,
                  ),
                ),
              ),
            ),
            const SizedBox(
              height: 30,
            ),
            Container(
              height: 140,
              decoration: ShapeDecoration(
                color: Colors.indigo,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(30),
                  side: const BorderSide(
                    color: Colors.orange,
                    width: 20.0,
                    strokeAlign: BorderSide.strokeAlignInside,
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details> 

![image](https://github.com/flutter/flutter/assets/840911/b7e0bf3b-d90c-423e-a2b1-3650c050e0e3)

As shown in this screenshot, `ContinuousRectangleBorder` borders are larger than expected. 

`ContinuousRectangleBorder` relies on `Canvas.drawPath` with a `Paint.strokeWidth` set to the border side width. Doing so the drawn path is larger than expected by half of the border side width.

The call to `drawPath` can be adjusted to take this into account, as done in `StarBorder`, see
https://github.com/flutter/flutter/blob/fca152f2f14822b3a5c811616a37d89f56c288a0/packages/flutter/lib/src/painting/star_border.dart#L379
and https://github.com/flutter/flutter/blob/fca152f2f14822b3a5c811616a37d89f56c288a0/packages/flutter/lib/src/painting/star_border.dart#L408 

The problem is that the shape of a `ContinuousRectangleBorder` is not proportional so when using `drawPath` based on an adjusted path the drawn path will be smaller than the outer path which is used for clipping which leads to the following result where the non-proportionnality is visible in each corners:

![image](https://github.com/flutter/flutter/assets/840911/02167333-787b-4cb8-8776-eb44ae83b008)


One solution would be to paint the border using the difference of two calls to `drawPath` (tried in https://github.com/flutter/flutter/pull/126666 which needed more work). 

@gspencergoog for insights, especialy on how to get the correct result when using `drawPath` (which would be more efficient than drawing the difference of two paths).
@bernaferrari who might be interested if still planning a redesign of `ContinuousRectangleBorder`.

**Comment by richard457** [comment]
From this code
```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class MiniAppIcon extends StatelessWidget {
  const MiniAppIcon(
      {super.key,
      required this.icon,
      required this.gradientColorOne,
      required this.gradientColorTwo,
      required this.page,
      this.showPageName = true,
      this.sideSize = 72.0});

  final IconData icon;
  final Color gradientColorOne;
  final Color gradientColorTwo;
  final double sideSize;
  final String page;
  final bool showPageName;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          height: sideSize,
          width: sideSize,
          decoration: ShapeDecoration(
              shape: ContinuousRectangleBorder(
                  side: BorderSide.none,
                  borderRadius: BorderRadius.circular(80.0)),
              color: gradientColorOne,
              shadows: []),
          child: Center(
            child: Icon(
              icon,
              color: Colors.white,
            ),
          ),
        ),
        Padding(
          padding: const EdgeInsets.all(10.0),
          child: Visibility(
            visible: showPageName,
            child: Text(page, style: GoogleFonts.poppins(fontSize: 13)),
          ),
        )
      ],
    );
  }
}
```
When the size is 72.0 the ContinuousRectangleBorder shape created leaves some small shadow on each side
