### ISSUE TITLE
[shared_preferences] with custom entrypoint working on debug but not on profile or release

### ISSUE THREAD

**Issue by X-SLAYER** [flutter/flutter#102903]
Hi, i created a flutter package that caches flutter engine and uses custom entry point to display FlutterView inside an android overlay
the application works fine on debug and release mode but once I add `shared_preferences` plugin the debug mode works fine but isn't on release and profile mode.

## Steps to Reproduce

1. Add `flutter_overlay_window` package to my app 
2. add the entrypoint to my `main.dart`
```dart
@pragma("vm:entry-point")
void overlayMain() {
  runApp(const MaterialApp(
    debugShowCheckedModeBanner: false,
    home: Material(child: Text("My overlay"))
  ));
}
```

3. add `shared_preferences`  version `2.0.13`

**Expected results:** 
the app works fine on debug_mode with `shared_preferences` but not on release or profile mode.
app works fine without `shared_preferences` on release and profile mode

**Actual results:** 
```
Launching lib/main.dart on Infinix X682B in profile mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-profile.apk (13.2MB).
E/flutter (22733): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'overlayMain' declared.
E/flutter (22733): Receiver: top-level
E/flutter (22733): Tried calling: overlayMain, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:222)
E/flutter (22733):
E/flutter (22733): [ERROR:flutter/runtime/dart_isolate.cc(681)] Could not resolve main entrypoint function.
E/flutter (22733): [ERROR:flutter/runtime/dart_isolate.cc(165)] Could not run the run main Dart entrypoint.
E/flutter (22733): [ERROR:flutter/runtime/runtime_controller.cc(381)] Could not create root isolate.
E/flutter (22733): [ERROR:flutter/shell/common/shell.cc(580)] Could not launch engine with configuration.
```

**Flutter doctor:** 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on Ubuntu 20.04.4 LTS 5.13.0-40-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

**Comment by darshankawar** [comment]
@X-SLAYER 
The original issue was fixed and pushed into master: https://github.com/flutter/flutter/issues/91841.
I am not sure if it is in stable yet, so please try the same on latest master and check if you still see same error or not.

`flutter channel master`
`flutter upgrade`

**Comment by X-SLAYER** [comment]
switching to`master` channel caused some problems in running because of some packages 

 ```
 7 warnings
Note: /home/slayer/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/device_apps-2.2.0/android/src/main/java/fr/g123k/deviceapps/DeviceAppsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/slayer/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.3/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: /home/slayer/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (326, 50): Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: /home/slayer/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (344, 4): 'error' overrides nothing
e: /home/slayer/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (360, 52): Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: /home/slayer/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (366, 4): 'error' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_foreground_task:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
 
BUILD FAILED in 40s
Exception: Gradle task assembleRelease failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:408:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:576:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:505:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:71:28)
<asynchronous suspension>
#6      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:642:9)
<asynchronous suspension>
#7      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:640:5)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:584:15)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1194:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand
package:args/command_runner.dart:209
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

```

**Comment by darshankawar** [comment]
@X-SLAYER 
The errors seem to be related to third party plugins `device-apps` and `flutter_foreground_task`, so you'll need to fix them as mentioned in the errors.

**Comment by X-SLAYER** [comment]
I can't fix them because they are built on the stable version that's what i think 
i think the only solution is to wait for flutter to fix that on stable version or i don't use use these packages while on `master

**Comment by darshankawar** [comment]
> Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'overlayMain' declared.
> E/flutter (22733): Receiver: top-level

This is pointing to `flutter_overlay_window` package that you are using. 
Can you try something like below and see if it works for you ?

```
@pragma('vm:entry-point')
void main() {
  runApp(ColoredBox(color: Color(0xffcc0000)));
}
```

In your case:

```
@pragma("vm:entry-point")
void main() {
  runApp(const MaterialApp(
    debugShowCheckedModeBanner: false,
    home: Material(child: Text("My overlay"))
  ));
}
```

**Comment by X-SLAYER** [comment]
the problem is that I still need the main app with my custom one so I think this will not work

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

@pragma("vm:entry-point")
void overlayMain() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: TestOverlay(), //ClickableOverlay()
    ),
  );
}
```
