### ISSUE TITLE
[flutter_tools] RPCError at new _OutstandingRequest at package:vm_service/src/vm_service.dart

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#102994]
on `beta/2.13.0-0.3.pre`, with command `flutter run -d chrome` on Windows 10

```
Thread 0 main threadRPCError: ext.flutter.debugDumpApp: (-32603) ext.flutter.debugDumpApp: Unexpected error from chrome devtools:text: Uncaught (in promise)exception:  description: null  type: string  value: Unexpected null value.attempted JS eval: `require("dart_sdk").developer.invokeExtension(    "ext.flutter.debugDumpApp", JSON.stringify({}));

#0      handleErrorIfPresent (package:dwds/src/utilities/shared.dart:97:5)
#1      ChromeProxyService.callServiceExtension (package:dwds/src/services/chrome_proxy_service.dart:351:5)
<asynchronous suspension>
#2      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>

at new _OutstandingRequest(vm_service.dart:1734)
at VmService._call(vm_service.dart:2245)
at VmService.callServiceExtension(vm_service.dart:2216)
at FlutterVmService._checkedCallServiceExtension(vmservice.dart:776)
at FlutterVmService.invokeFlutterExtensionRpcRaw(vmservice.dart:795)
at FlutterVmService.flutterDebugDumpApp(vmservice.dart:544)
at ResidentHandlers.debugDumpApp(resident_runner.dart:651)
at <asynchronous gap>(async)
at TerminalHandler.processTerminalInput(resident_runner.dart:1685)
at <asynchronous gap>(async)
```

**Comment by christopherfujino** [comment]
Another, similar error message:

```
Thread 0 MAIN THREADRPCError: ext.flutter.profileWidgetBuilds: (-32603) ext.flutter.profileWidgetBuilds: Unexpected error from chrome devtools:
text: Uncaught (in promise)
exception:
  description: null
  type: string
  value: Unexpected null value.
attempted JS eval: `require("dart_sdk").developer.invokeExtension(
    "ext.flutter.profileWidgetBuilds", JSON.stringify({}));
`

#0      handleErrorIfPresent (package:dwds/src/utilities/shared.dart:97:5)
#1      ChromeProxyService.callServiceExtension (package:dwds/src/services/chrome_proxy_service.dart:351:5)
<asynchronous suspension>
#2      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>
at new _OutstandingRequest	(vm_service.dart:1734)
at VmService._call	(vm_service.dart:2245)
at VmService.callServiceExtension	(vm_service.dart:2216)
at FlutterVmService._checkedCallServiceExtension	(vmservice.dart:776)
at FlutterVmService.invokeFlutterExtensionRpcRaw	(vmservice.dart:795)
at FlutterVmService._flutterToggle	(vmservice.dart:598)
at FlutterVmService.flutterToggleProfileWidgetBuilds	(vmservice.dart:633)
at ResidentHandlers.debugToggleProfileWidgetBuilds	(resident_runner.dart:809)
at <asynchronous gap>	(async)
at TerminalHandler.processTerminalInput	(resident_runner.dart:1685)
at <asynchronous gap>	(async)
```

**Comment by RishabhShivhare770** [comment]
Did anyone find any solution to this? I'm facing the same issue for a project which, previously, did not have the web side enabled. Now, after enabling the web for the same project, i'm not able to run the app and it throws the same error with the same error code as mentioned above.
