### ISSUE TITLE
[image_picker] java.lang.RuntimeException: Failure delivering result (java.lang.SecurityException: Permission Denial)

### ISSUE THREAD

**Issue by WatchDogsDev** [flutter/flutter#102912]
## Steps to Reproduce

1. Run app on flutter device with **image_picker** plugin.
2. Try to pick image from gallery
3. On native view try to use another application (example: ES File Explorer)
4. Tap on a image file to pick

**Expected results:**
Something like a permission denied error to catch 

**Actual results:**
App crashed

<details>
<summary>Code sample</summary>

```dart
final selectedImage = await ImagePicker().pickImage(
        source: ImageSource.gallery,
        maxHeight: 2048,
        maxWidth: 2048,
        imageQuality: 100,
      );
```

</details>

<details>
  <summary>Logs</summary>

```
D/AndroidRuntime(13475): Shutting down VM
E/AndroidRuntime(13475): FATAL EXCEPTION: main
E/AndroidRuntime(13475): Process: com.example.app, PID: 13475
E/AndroidRuntime(13475): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.estrongs.files/storage/emulated/0/Download/image.png }} to activity {com.example.app/com.example.app.MainActivity}: java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{1ccf8d 13475:com.example.app/u0a160} (pid=13475, uid=10160) that is not exported from UID 10171
E/AndroidRuntime(13475): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5057)
E/AndroidRuntime(13475): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5098)
E/AndroidRuntime(13475): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(13475): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(13475): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(13475): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
E/AndroidRuntime(13475): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13475): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(13475): 	at android.app.ActivityThread.main(ActivityThread.java:7700)
E/AndroidRuntime(13475): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13475): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
E/AndroidRuntime(13475): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
E/AndroidRuntime(13475): Caused by: java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{1ccf8d 13475:com.example.app/u0a160} (pid=13475, uid=10160) that is not exported from UID 10171
E/AndroidRuntime(13475): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
E/AndroidRuntime(13475): 	at android.os.Parcel.createException(Parcel.java:2357)
E/AndroidRuntime(13475): 	at android.os.Parcel.readException(Parcel.java:2340)
E/AndroidRuntime(13475): 	at android.os.Parcel.readException(Parcel.java:2282)
E/AndroidRuntime(13475): 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5771)
E/AndroidRuntime(13475): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6855)
E/AndroidRuntime(13475): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2936)
E/AndroidRuntime(13475): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
E/AndroidRuntime(13475): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1967)
E/AndroidRuntime(13475): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
E/AndroidRuntime(13475): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1475)
E/AndroidRuntime(13475): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:45)
E/AndroidRuntime(13475): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:487)
E/AndroidRuntime(13475): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:464)
E/AndroidRuntime(13475): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
E/AndroidRuntime(13475): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
E/AndroidRuntime(13475): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:772)
E/AndroidRuntime(13475): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:685)
E/AndroidRuntime(13475): 	at android.app.Activity.dispatchActivityResult(Activity.java:8310)
E/AndroidRuntime(13475): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5050)
E/AndroidRuntime(13475): 	... 11 more
E/AndroidRuntime(13475): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(13475): 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7258)
E/AndroidRuntime(13475): 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7707)
E/AndroidRuntime(13475): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2416)
E/AndroidRuntime(13475): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2950)
E/AndroidRuntime(13475): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
E/AndroidRuntime(13475):
```

```
[✓] Flutter (Channel stable, 2.10.5, on Ubuntu 22.04 LTS 5.15.0-27-generic, locale en_US.UTF-8)
    • Flutter version 2.10.5 at ~/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at ~/AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • Java binary at: ~/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • Nokia 2 3 (mobile) • PT99621AA1A72700302 • android-arm    • Android 11 (API 30)
    • Linux (desktop)    • linux               • linux-x64      • Ubuntu 22.04 LTS 5.15.0-27-generic
    • Chrome (web)       • chrome              • web-javascript • Chromium 101.0.4951.41 snap

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @WatchDogsDev, I attempted to reproduce this on my device and Pixel 4a Emulator but in both cases, the app did not crash. What version of `image_picker` are you using and is the `Nokia` device the only device you're experiencing this issue on? 

I would like to point out that I did see an exception in my console

`Unable to decode stream: java.lang.NullPointerException` 

but the app did not crash and this exception was only when I used the `Es File Explorer` app

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/166214261-07ec5ffc-56d2-4bac-8541-f3e72931c00e.mov
</details>
