### ISSUE TITLE
io.flutter.embedding.engine.FlutterJNI.nativeSurfaceChanged (flutter 2.10.3)

### ISSUE THREAD

**Issue by LeeJunYoung-2823** [flutter/flutter#102910]
The app stops intermittently when it comes out to the main screen after processing the screen.
I have written the relevant code below

```dart
  dispose() {
    Main.printLog('dispose landscape page');
    _timer.cancel();
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);
    pageController.dispose();
    super.dispose();
  }

AlertDialog backWarning(context) {
    return AlertDialog(
      content: Text('test'),
      actions: [
        MaterialButton(
          minWidth: 50,
          onPressed: () {
            if (aiBookProvider.bookId != null) {
              LocalDB().tempDelete(aiBookProvider.bookId!);
            }
            Navigator.of(context).pop(true);
            Navigator.of(context).pop(true);
          },
          child: Text('true'),
        ),
        MaterialButton(
          minWidth: 50,
          onPressed: () {
            Navigator.of(context).pop(false);
          },
          child: Text('false'),
        ),
      ],
    );
  }

MaterialButton(
    child: Icon(
      Icons.arrow_back,
    ),
    onPressed: () async {
      if (aiBookProvider.changedPageIndexList.length > 0) {
        return await showDialog(
            context: context,
            builder: (_) {
              return backWarning(context);
            });
      } else {
        if (aiBookProvider.makingChk || firstPuzzleChk) {
          Navigator.of(context).pop();
        } else {
          Navigator.of(context)
              .pop(aiBookProvider.pageCount);
        }
      }
    }),
```

```console
--------------firebase error------------------
at io.flutter.embedding.engine.FlutterJNI.nativeSurfaceChanged(Native method)
       at io.flutter.embedding.engine.FlutterJNI.onSurfaceChanged(FlutterJNI.java:603)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.surfaceChanged(FlutterRenderer.java:271)
       at io.flutter.embedding.android.FlutterSurfaceView.changeSurfaceSize(FlutterSurfaceView.java:281)
       at io.flutter.embedding.android.FlutterSurfaceView.access$300(FlutterSurfaceView.java:35)
       at io.flutter.embedding.android.FlutterSurfaceView$1.surfaceChanged(FlutterSurfaceView.java:64)
       at android.view.SurfaceView.updateSurface(SurfaceView.java:1365)
       at android.view.SurfaceView.setFrame(SurfaceView.java:675)
       at android.view.View.layout(View.java:24458)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1330)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4583)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4005)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2893)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10445)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:797)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19043.1645], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.6)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.54.1)
[√] Connected device (5 available)
[√] HTTP Host Availability
```

**Comment by navaronbracke** [comment]
This was an issue with the Android embedder. That was fixed in Flutter 2.10.4. Please upgrade your Flutter version to `2.10.4` or higher and see if it still occurs.

**Comment by LeeJunYoung-2823** [comment]
> ------------flutter doctor----------------
> [√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19043.1645], locale ko-KR)
> [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
> [√] Chrome - develop for the web
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.6)
> [√] Android Studio (version 2021.1)
> [√] VS Code (version 1.54.1)
> [√] Connected device (5 available)
> [√] HTTP Host Availability


An error occurs even if it is 2.10.3

**Comment by LeeJunYoung-2823** [comment]
> This was an issue with the Android embedder. That was fixed in Flutter 2.10.3 (although the title states that you are on that version?).
> 
> Could you provide the output of `flutter doctor -v` so we can verify what Flutter version you are on?
> 
> Possible duplicate of #98779



------------flutter doctor----------------
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19043.1645], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.6)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.54.1)
[√] Connected device (5 available)
[√] HTTP Host Availability

An error occurs even if it is 2.10.3

**Comment by navaronbracke** [comment]
Could you provide the output of `flutter doctor -v` (provide the `-v` flag for verbose output) ? Then we can try to see if this is device specific.

**Comment by LeeJunYoung-2823** [comment]
> [√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19043.1645], locale ko-KR)
    • Flutter version 2.10.3 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at C:\Users\sweetbook15\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • ANDROID_HOME = C:\Users\sweetbook15\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31019.35
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\sweetbook15\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (5 available)
    • SM G977N (mobile)            • R3CM8013T6N   • android-arm64  • Android 12 (API 31)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 101.0.1210.32

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by maheshmnj** [comment]
Hi @LeeJunYoung-2823, Thanks for filing the issue. Please share a minimal and complete sample code along with the output of `flutter run -v` in a text file.

**Comment by LeeJunYoung-2823** [comment]
> Hi @LeeJunYoung-2823, Thanks for filing the issue. Please share a minimal and complete sample code along with the output of `flutter run -v` in a text file.

An existing project has created a sample code with suspicious code.
However, no errors occurred.
The method of sample code is similar to how existing projects are implemented.
First, attach the sample code address and the existing project's Flutter run-v (origin) file and the sample project Flutter run-v (test) file.

<test code git>
https://github.com/LeeJunYoung-2823/SystemChrome_test

[flutter run-v (test).txt](https://github.com/flutter/flutter/files/8608816/flutter.run-v.test.txt)
[flutter run-v (origin).txt](https://github.com/flutter/flutter/files/8608817/flutter.run-v.origin.txt)

**Comment by maheshmnj** [comment]
Thanks for the update @LeeJunYoung-2823, Can you please share minimal and complete sample code to investigate further?
