### ISSUE TITLE
Unable to build ios app due to "ld: Framework not found Flutter" error  

### ISSUE THREAD

**Issue by nikhilag** [flutter/flutter#103034]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
```
Launching lib/main.dart on iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: MX46R2WRAM
Running pod install...                                             16.2s
Running Xcode build...                                                  
Xcode build done.                                           14.6s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-05-04 17:02:11.098 xcodebuild[27981:160749] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
    Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-05-04 17:02:11.098 xcodebuild[27981:160749] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/ms/f2y61phj1b95qm3ynrsjpmfw0000gn/T/flutter_tools.flprkJ/flutter_ios_build_temp_dirfvo9Hz/temporary_xcresult_bundle

    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target
    versions is 9.0 to 15.4.99. (in target 'leveldb-library' from project 'Pods')
    /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target
    versions is 9.0 to 15.4.99. (in target 'Toast' from project 'Pods')
    /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target
    versions is 9.0 to 15.4.99. (in target 'FMDB' from project 'Pods')
    /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target
    versions is 9.0 to 15.4.99. (in target 'AppAuth' from project 'Pods')
    /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target
    versions is 9.0 to 15.4.99. (in target 'GoogleSignIn' from project 'Pods')

    Result bundle written to path:
        /var/folders/ms/f2y61phj1b95qm3ynrsjpmfw0000gn/T/flutter_tools.flprkJ/flutter_ios_build_temp_dirfvo9Hz/temporary_xcresult_bundle


Could not build the precompiled application for the device.
Error (Xcode): Framework not found Flutter



Error launching application on iPad.
```

3. After setting up custom schemes and ios distribution certificate, I tried to run the ios app and it didn't work

**Expected results:** 
Successful run on iPad device

**Actual results:** 
`flutter run --flavor=dev -t lib/main.dart` crashed with the error mentioned above
And in XCode, the build failed with the screenshot below

Error part of logs for `flutter run --flavor=dev --verbose`

```
Users/nikhilagarwal/Library/Developer/Xcode/DerivedData/Runner-hdgzxxzcrrwtnnbcxokiloyxiqtj/Build/Intermediates.noindex/Pods.build/Debug-Dev-iphoneos/permission_handler_apple.build/Objects-normal/arm64/Bl
                        uetoothPermissionStrategy.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'permission_handler_apple' from project
'Pods')
                    
                        /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 15.4.99. (in target 'GoogleSignIn' from project 'Pods')
                        /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 15.4.99. (in target 'AppAuth' from project 'Pods')
                        /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 15.4.99. (in target 'Toast' from project 'Pods')
                        /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 15.4.99. (in target 'FMDB' from project 'Pods')
                        /Users/nikhilagarwal/Documents/GitHub/decorum_crm/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 15.4.99. (in target 'leveldb-library' from project 'Pods')
                    
                        Result bundle written to path:
                                /var/folders/ms/f2y61phj1b95qm3ynrsjpmfw0000gn/T/flutter_tools.RNlGN9/flutter_ios_build_temp_dirVDJimA/temporary_xcresult_bundle
                    
                    
[ +697 ms] Could not build the precompiled application for the device.
[  +19 ms] Error (Xcode): Framework not found Flutter
           
[   +1 ms] Error launching application on iPad.
[  +12 ms] "flutter run" took 50,416ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +254 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
```

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.10.5 at /Users/nikhilagarwal/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/nikhilagarwal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPad (mobile)   • 00008101-000140D114D1003A • ios            • iOS 14.4 18D52
    • macOS (desktop) • macos                     • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Screenshot for XCode build:-

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/54072321/166675463-ca04d065-95b3-4a76-8a26-11f29d406904.png">

**Comment by darshankawar** [comment]
@nikhilag

Can you provide entire verbose log for both commands ?

```
flutter run --flavor=dev -t lib/main.dart -v

flutter run -v
```

Both logs will be huge, so you can put them in respective text files and share both of them here.

**Comment by darshankawar** [comment]
@nikhilag 
Thanks for the logs. Looking at them it seems to be occuring due to a linker error related to `permission_handler` plugin which is third party to Flutter.

From XCode, can you try to remove the linker as follows for the said plugin and see if it helps ?

```
XCode-> target->build setting -> Other Linker Flags

-framework ""permission_handler_apple
```

**Comment by wangmir** [comment]
I had the same problem with,

In my case, I uncommented this in the `Podfile`

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
```

and it derives the problem. So, I re-commented this. After that, it works.

But I'm not sure why this derives the problem. (when I run the app with F5 to the ios emulator, it works fine).
