### ISSUE TITLE
flutter config should report an error if it fails to write to .flutter

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10309]
The welcome banner keeps printing and I can't get rid if it by running `flutter config --analytics` or `flutter config --no-analytics`

```
$ flutter run -d s --profile                                               (05-24 19:01:31)

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.io                   ║
  ║                                                                            ║
  ║ The Flutter tool anonymously reports feature usage statistics and crash    ║
  ║ reports to Google in order to help Google contribute improvements to       ║
  ║ Flutter over time.                                                         ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting        ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ║                                                                            ║
  ║ Use "flutter config --no-analytics" to disable analytics and crash         ║
  ║ reporting.                                                                 ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Launching lib/main.dart on SM G950U in profile mode...
Running 'gradle assembleProfile'...

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.io                   ║
  ║                                                                            ║
  ║ The Flutter tool anonymously reports feature usage statistics and crash    ║
  ║ reports to Google in order to help Google contribute improvements to       ║
  ║ Flutter over time.                                                         ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting        ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ║                                                                            ║
  ║ Use "flutter config --no-analytics" to disable analytics and crash         ║
  ║ reporting.                                                                 ║
  ╚════════════════════════════════════════════════════════════════════════════╝


  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.io                   ║
  ║                                                                            ║
  ║ The Flutter tool anonymously reports feature usage statistics and crash    ║
  ║ reports to Google in order to help Google contribute improvements to       ║
  ║ Flutter over time.                                                         ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting        ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ║                                                                            ║
  ║ Use "flutter config --no-analytics" to disable analytics and crash         ║
  ║ reporting.                                                                 ║
  ╚════════════════════════════════════════════════════════════════════════════╝


  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.io                   ║
  ║                                                                            ║
  ║ The Flutter tool anonymously reports feature usage statistics and crash    ║
  ║ reports to Google in order to help Google contribute improvements to       ║
  ║ Flutter over time.                                                         ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting        ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ║                                                                            ║
  ║ Use "flutter config --no-analytics" to disable analytics and crash         ║
  ║ reporting.                                                                 ║
  ╚════════════════════════════════════════════════════════════════════════════╝


  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.io                   ║
  ║                                                                            ║
  ║ The Flutter tool anonymously reports feature usage statistics and crash    ║
  ║ reports to Google in order to help Google contribute improvements to       ║
  ║ Flutter over time.                                                         ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting        ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ║                                                                            ║
  ║ Use "flutter config --no-analytics" to disable analytics and crash         ║
  ║ reporting.                                                                 ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Built build/app/outputs/apk/app-profile.apk (9.6MB).
```

**Comment by eseidelGoogle** [comment]
Presumably this is a regression.  Maybe @tvolkert knows?

**Comment by Hixie** [comment]
What are the permissions on your home directory? That's where we try to put the message.

**Comment by xster** [comment]
ah you got it. I had a directory in the home directory called `.flutter` which was causing this. 

Repurposing this bug to handling `.flutter` file write failure during `flutter config`

**Comment by zoechi** [comment]
Looks fixed.

I get

```
zoechi@mac ~/dart/playground/flutter/flutter_10309_flutter_config
 $ mv ~/.flutter ~/.flutter.bak
zoechi@mac ~/dart/playground/flutter/flutter_10309_flutter_config
 $ mkdir ~/.flutter
zoechi@mac ~/dart/playground/flutter/flutter_10309_flutter_config
 $ flutter config --no-analytics

Unhandled exception:
FileSystemException: Cannot create file, path = '/Users/zoechi/.flutter' (OS Error: Is a directory, errno = 21)
#0      _File.throwIfError (dart:io/file_impl.dart:647:7)
#1      _File.createSync (dart:io/file_impl.dart:285:5)
#2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:119:13)
#3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30:17)
#4      new Usage (package:flutter_tools/src/usage.dart:29:18)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:83:20)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#9      AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#10     Usage.instance (package:flutter_tools/src/usage.dart:53:39)
#11     flutterUsage (package:flutter_tools/src/usage.dart:21:33)
#12     _handleToolError (package:flutter_tools/runner.dart:107:7)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#21     run (package:flutter_tools/runner.dart:51:10)
#22     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#23     main (file:///Users/zoechi/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#24     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
