### ISSUE TITLE
App doesn't build after update Flutter and Dart plugins

### ISSUE THREAD

**Issue by Psychosynthesis** [flutter/flutter#103055]
## Steps to Reproduce
Just agreed to update the flutter and dart plugin's by clicking on the button in the dialog shown by the Android Studio. And after that my app can't build anymore.

**Expected results:** App build
**Actual results:** App doesn't build 

I can't put the whole log here as it is very large. Here is the end of the output:
```
[+13131 ms] /C:/Users/Username/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
[   +1 ms]       io.Platform.packageRoot; // ignore: deprecated_member_use
[        ]                   ^^^^^^^^^^^
[{"event":"app.progress","params":{"appId":"fb5840dc-5de8-4773-a5b9-7c2ef51cb98f","id":"0","progressId":null,"finished":true}}]
[+30022 ms] Synced 0.0MB.
[        ] Failed to compile application.
[  +10 ms] 
 #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
 #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:589:9)
 <asynchronous suspension>
 #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
 <asynchronous suspension>
 #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 <asynchronous suspension>
 #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
 <asynchronous suspension>
 #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
 <asynchronous suspension>
 #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 <asynchronous suspension>
 #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
 <asynchronous suspension>
 #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
 <asynchronous suspension>
 #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 <asynchronous suspension>
 #10     main (package:flutter_tools/executable.dart:94:3)
 <asynchronous suspension>
```
Output of _C:\Develop\Mobile>flutter doctor -v_:
```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale ru-RU)
    • Flutter version 2.10.5 at C:\Develop\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Username\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.55

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

Any of these commands, in any order, **doesn't help**:
```
flutter clean
flutter pub outdated
flutter pub cache repair
```

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/96711
