### ISSUE TITLE
DropdownButtonFormField is using the key for an option multiple times

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#103266]
# Repro

 - clone `https://github.com/cedvdb/flutter_repros/tree/dropdown_selection_keys` 
 - use branch `dropdown_selection_keys`
 - `flutter test`
 
 # Result 
 
 The finder "2 widgets with key [<'option-hello'>] (ignoring offstage widgets)
 
 # code example
 
 ```dart
 DropdownButtonFormField<String>(
        key: const ValueKey('dropdown'),
        items: const [
          DropdownMenuItem(
            key: ValueKey('option-hello'),
            child: Text('hello'),
            value: 'hello',
          ),
        ]
 ```

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`.

Repo attached below for easy access. 

The source code is on the `dropdown_selection_keys` branch. 

[test_log.txt](https://github.com/flutter/flutter/files/8650190/test_log.txt)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                             • android-arm64  • Android 11 (API 30)
    • iPhone 13 (mobile)  • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)     • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.987, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.987 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0656a5c033 (9 hours ago), 2022-05-08 18:24:04 -0400
    • Engine revision c930e64a13
    • Dart version 2.18.0 (build 2.18.0-98.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                             • android-arm64  • Android 11 (API 30)
    • iPhone 13 (mobile)  • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)     • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[!] HTTP Host Availability
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: Failed to connect to host in 10 seconds

! Doctor found issues in 1 category.
```
</details>


[flutter_repros.zip](https://github.com/flutter/flutter/files/8650185/flutter_repros.zip)

**Comment by TahaTesser** [comment]
This is expected, 
DropdownMenuItem is used in the selected menu and also passed to the popup menu without manipulation hence keys are also passed to the menu 

https://github.com/flutter/flutter/blob/dfb4ff2f765338bb7ceba89eb400da25351a5a75/packages/flutter/lib/src/material/dropdown.dart#L1272

You can use `.first` or `.last` to determine which item you're looking for.

**Comment by cedvdb** [comment]
@TahaTesser what do you mean by "is used by the selection menu". If the value of the drop down field is null, and the menu is opened, the value "hello" appears only once in the screen.

Furthermore the key being reused is not really what I would qualify as "expected". If I expect to test the click on an option of the menu, I expect it to work with the key like I would for virtually everything else. Calling it expected is a bit of a stretch.

**Comment by TahaTesser** [comment]
`DropdownMenuItem` is used to show a selected item and pass it to the popup menu item. The menu item is passed not recreated as I pointed out in https://github.com/flutter/flutter/issues/103266#issuecomment-1122045854. Since it is the same object, creating a different key would create other problems. 


Leaving the issue open.

**Comment by cedvdb** [comment]
@TahaTesser The workaround you proposed generates warning. You can see it in the branch `dropdown_selection_keys_2` of the same flutter_repros repository.

I got to say I feel quite strongly that this is a weird api to have the same key twice. Is that something commonly done in flutter ? This is the first time I encounter that.

**Comment by TahaTesser** [comment]
@cedvdb 
Thanks, I'll look into it.

**Comment by cedvdb** [comment]
You are impressive taha. Answering everywhere + pull requests. Do you sleep ? :D

Anyway, I'll reiterate what confuses me, I was under the impression that a key should appear only once in the view and here flutter is doing the opposite ( even though it's the same object, it appears twice in the view).

**Comment by TahaTesser** [comment]
I looked into this further.

The problem is that when `items` are provided as `DropdownButton` or `DropdownFormField`, they're passed primarily for two things.
1. To calculate which item from `items` is selected, this is the first set of `items` containing provided keys.

https://github.com/flutter/flutter/blob/a12a69a47c928e6017196f75fd9f691f32866e88/packages/flutter/lib/src/material/dropdown.dart#L1381-L1383

2. To present `items` in a popup menu, This is the second set of `items` containing provided keys.
 
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dropdown.dart#L1269

(This is the reason we get duplicate keys)

This is the reason I commented this is working as designed, `dropdown_test.dart` itself finds these based `.first` or `.last`  position.

Regarding 

> The workaround you proposed generates warning.

I can see these warnings so I was curious how `dropdown_test.dart` is dealing with this it looks like it suppresses  these warnings using `warnIfMissed : false` and this parameter is used in many widgets tests.

https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/dropdown_test.dart#L382

Currently, if you find the last key and add `warnIfMissed : false`, working as expected.


### Problem.
We need a way to pass `items` for the selected items and for the popup menu without creating duplicates.

- `items` keys for the popup menu are required to select an item based on the key just the test in [description](https://github.com/flutter/flutter/issues/103266#issue-1228599612).
- `items` keys are for the selected items are not needed but removing them causes other tests to fail.


Since this is complex I'll continue finding a proper solution for duplicate keys.

**Comment by cedvdb** [comment]
I'll have to disagree on a few things, but you know best. The ideal scenario would be to not echo this on the end user (in this case me), which in my opinion would be a better design.

 > Currently, if you find the last key and add warnIfMissed : false, working as expected.
 
 "As expected" is a bit of a stretch, here, but I understand what you mean, it's a workaround. The fact that the key is reused is in my opinion unexpected, so I don't think the internal design here is sound too.
 
 >  finding a proper solution for duplicate keys.
 
I'm under the impression that reusing keys is not something that should not be done at all. As an end user of the flutter API (not looking at the internals) it seems strange to me that the argument is :

 > The menu item is passed not recreated as I pointed out in [...]. Since it is the same object, creating a different keys would create other problems.
 
If you think that this is correct, and duplicating key is all right then my bad I had misunderstood something then.

**Comment by HansMuller** [comment]
As of Flutter 3.16, DropdownMenu is preferred and does not have the problem described here.
