### ISSUE TITLE
call 'io.flutter.embedding.engine.FlutterEngineGroup#createAndRunEngine' anr

### ISSUE THREAD

**Issue by hello-soon** [flutter/flutter#103296]
call 'io.flutter.embedding.engine.FlutterEngineGroup#createAndRunEngine' anr

<details>
<summary> error log </summary>

```
------------------------------------
DALVIK THREADS (165):
"Signal Catcher" daemon prio=10 tid=3 Runnable
  | group="system" sCount=0 dsCount=0 flags=0 obj=0x13542238 self=0xb400006f7714e2c0
  | sysTid=17234 nice=-20 cgrp=top-app sched=0/0 handle=0x6df7a7bcc0
  | state=R schedstat=( 5075330 113167 17 ) utm=0 stm=0 core=3 HZ=100
  | stack=0x6df7984000-0x6df7986000 stackSize=995KB
  | held mutexes= "mutator lock"(shared held)
  native: #00 pc 000000000049ee50  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+140)
  native: #01 pc 00000000005abfa8  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+376)
  native: #02 pc 00000000005c90e0  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+924)
  native: #03 pc 00000000005c3020  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+528)
  native: #04 pc 00000000005c21ec  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1920)
  native: #05 pc 00000000005c168c  /apex/com.android.art/lib64/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+776)
  native: #06 pc 000000000056d64c  /apex/com.android.art/lib64/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+196)
  native: #07 pc 0000000000582be0  /apex/com.android.art/lib64/libart.so (art::SignalCatcher::HandleSigQuit()+1396)
  native: #08 pc 0000000000581bac  /apex/com.android.art/lib64/libart.so (art::SignalCatcher::Run(void*)+348)
  native: #09 pc 00000000000af8c8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  native: #10 pc 000000000004fe08  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
  (no managed stack frames)


"main" prio=5 tid=1 Native
 | group="main" sCount=1 dsCount=0 flags=1 obj=0x729476a8 self=0xb400006f77147380
 | sysTid=17218 nice=-10 cgrp=top-app sched=0/0 handle=0x709d9514f8
 | state=S schedstat=( 23951114520 8334561796 108910 ) utm=1846 stm=548 core=3 HZ=100
 | stack=0x7ff335d000-0x7ff335f000 stackSize=8192KB
 | held mutexes=
 native: #00 pc 000000000004aecc /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
 native: #01 pc 000000000004eab4 /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+144)
 native: #02 pc 00000000000aecb0 /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+60)
 native: #03 pc 000000000147e8f8 /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #04 pc 000000000147ead8 /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #05 pc 00000000013816bc /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #06 pc 000000000137bc84 /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #07 pc 000000000137b6d8 /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #08 pc 000000000138189c /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #09 pc 000000000137b1ec /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #10 pc 00000000013824d8 /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #11 pc 0000000001382400 /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #12 pc 0000000001344e6c /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #13 pc 000000000137d3d8 /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #14 pc 000000000131d7d0 /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #15 pc 00000000013252ac /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/lib/arm64/libflutter.so (???)
 native: #16 pc 000000000013ced4 /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148)
 native: #17 pc 0000000000133564 /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
 native: #18 pc 00000000001a8a78 /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
 native: #19 pc 0000000000318330 /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376)
 native: #20 pc 000000000030e65c /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996)
 native: #21 pc 000000000067eb70 /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576)
 native: #22 pc 000000000012d914 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20)
 native: #23 pc 000000000017a570 [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (io.flutter.embedding.engine.FlutterJNI.spawn+24)
 native: #24 pc 000000000067c794 /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520)
 native: #25 pc 000000000012d814 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20)
 native: #26 pc 0000000000179d60 [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (io.flutter.embedding.engine.FlutterEngine.spawn+24)
 native: #27 pc 000000000067c794 /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520)
 native: #28 pc 000000000012d814 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20)
 native: #29 pc 0000000000179c60 [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine+72)
 native: #30 pc 000000000067c794 /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520)
 native: #31 pc 000000000012d814 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20)
 native: #32 pc 000000000023f870 [anon:dalvik-classes11.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes11.dex] (com.tlive.madcat.flutter.EngineBindings.<init>+88)
 native: #33 pc 000000000067ee10 /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1248)
 native: #34 pc 000000000012d914 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20)
 native: #35 pc 00000000003bea20 [anon:dalvik-classes11.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes11.dex] (com.tlive.madcat.presentation.mainframe.MainActivityVideoRoomUtil$createEngine$1$createEngine$1.invokeSuspend+64)
 native: #36 pc 000000000067c794 /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520)
 native: #37 pc 000000000012d814 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20)
 native: #38 pc 00000000002d29ac [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith+40)
 native: #39 pc 000000000067e1cc /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1808)
 native: #40 pc 000000000012da14 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20)
 native: #41 pc 00000000003d9712 [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (kotlinx.coroutines.DispatchedTask.run+442)
 native: #42 pc 000000000067e1cc /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1808)
 native: #43 pc 000000000012da14 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20)
 native: #44 pc 00000000003da53a [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (kotlinx.coroutines.EventLoopImplBase.processNextEvent+202)
 native: #45 pc 000000000067c794 /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520)
 native: #46 pc 000000000012d814 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20)
 native: #47 pc 00000000003d3fe4 [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (kotlinx.coroutines.BlockingCoroutine.joinBlocking+80)
 native: #48 pc 000000000067c794 /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520)
 native: #49 pc 000000000012d814 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20)
 native: #50 pc 00000000003d4278 [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking+180)
 native: #51 pc 000000000067f6f0 /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+1224)
 native: #52 pc 000000000012d994 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20)
 native: #53 pc 00000000003d4528 [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (kotlinx.coroutines.BuildersKt.runBlocking)
 native: #54 pc 000000000067f6f0 /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+1224)
 native: #55 pc 000000000012d994 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20)
 native: #56 pc 00000000003d41a8 [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default+16)
 native: #57 pc 000000000067f6f0 /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+1224)
 native: #58 pc 000000000012d994 /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20)
 native: #59 pc 00000000003d450c [anon:dalvik-classes2.dex extracted in memory from /data/app/~~DKjapNuga2ZWcYIGUaU4Sw==/com.tlive.madcat-JybSBBQ53hrOq_4WzZsj_A==/base.apk!classes2.dex] (kotlinx.coroutines.BuildersKt.runBlocking$default)
 native: #60 pc 0000000000305c58 /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.8100235316906539105)+268)
 native: #61 pc 000000000066b1fc /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780)
 native: #62 pc 000000000013cff8 /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88)
 native: #63 pc 00000000020710f0 /memfd:jit-cache (deleted) (offset 2000000) (com.tlive.madcat.presentation.mainframe.MainActivityVideoRoomUtil.createEngine+224)
 native: #64 pc 00000000020708d4 /memfd:jit-cache (deleted) (offset 2000000) (com.tlive.madcat.flutter.channel.handle.trovo.flutter.Business.onFlutterChannelInit+628)
 native: #65 pc 0000000000133564 /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
 native: #66 pc 00000000001a8a78 /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
 native: #67 pc 00000000005556f8 /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1364)
 native: #68 pc 00000000004d4f04 /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
 at io.flutter.embedding.engine.FlutterJNI.nativeSpawn(Native method)
 at io.flutter.embedding.engine.FlutterJNI.spawn(FlutterJNI.java:341)
 at io.flutter.embedding.engine.FlutterEngine.spawn(FlutterEngine.java:385)
 at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:101)

```

</details>

------------------------------------
```
flutter doctor -v
[✓] Flutter (Channel unknown, 2.2.3, on macOS 12.3.1 21E258 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/accountname/Documents/app/flutter
    • Framework revision f4abaa0735 (10 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/accountname/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /Users/accountname/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 101.0.4951.54

! Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment]
> Channel unknown, 2.2.3

You seem to be on older version. Current is 2.10.5, and chances are that if you upgrade to latest, this ANR would have been fixed already most probably. So I suggest you to upgrade and try again to see if this crash still persists or not. If so, please try to provide steps to replicate to properly address this.
