### ISSUE TITLE
Displaying big images in full quality is not possible.

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#103295]
Consider the following example:
```dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() => runApp(
      InteractiveViewer(
        minScale: 1.0,
        maxScale: 100.0,
        child: Image.file(
          File(
            "USE_PATH_TO_BIG_IMAGE/big_image.png",
          ),
          filterQuality: FilterQuality.none,
        ),
      ),
    );
```

with this image:

![big_image](https://user-images.githubusercontent.com/24444584/167289445-4d5e98ae-e6b6-481e-9840-e12109d9ad8c.png)

Expected output when zoomed in (viewed in IntelliJ):

<img width="567" alt="Bildschirmfoto 2022-05-08 um 11 11 18" src="https://user-images.githubusercontent.com/24444584/167289528-eadb58af-42fc-4127-b86a-931e3af68204.png">

When running the example code from above, on macos, with the large image from above, and after zooming in, shows a lower res version i.e.: 

<img width="471" alt="Bildschirmfoto 2022-05-08 um 11 11 30" src="https://user-images.githubusercontent.com/24444584/167289552-b7333f0f-5616-4f5f-b03f-c1dded2ac877.png">

**Comment by jonahwilliams** [comment]
FilterQuality.none = the lowest possible quality of transformation, what happens if you set it to FilterQuality.high? Also consider removing the filter quality to do a "regular" transformation of the child

**Comment by modulovalue** [comment]
Changing the filterQuality argument to a different value doesn't seem to display the image at a higher resolution. It appears to just apply a different filtering algorithm (which is consistent with the documentation of the FilterQuality enum).

> what happens if you set it to FilterQuality.high

FilterQuality.high
<img width="518" alt="Bildschirmfoto 2022-05-08 um 21 18 06" src="https://user-images.githubusercontent.com/24444584/167312286-10b3bb15-21f4-486c-ab25-ad9ee8f9d89a.png">

FilterQuality.medium
<img width="699" alt="Bildschirmfoto 2022-05-08 um 21 17 43" src="https://user-images.githubusercontent.com/24444584/167312294-22a0f657-ca6a-48e8-a379-7bb4ecc68dc2.png">

FilterQuality.low
<img width="485" alt="Bildschirmfoto 2022-05-08 um 21 17 24" src="https://user-images.githubusercontent.com/24444584/167312306-cb1ac580-310f-4538-9671-fe1654280e8b.png">

> Also consider removing the filter quality to do a "regular" transformation of the child

The default value of the filterQuality parameter on Image.file is FilterQuality.low.

**Comment by jonahwilliams** [comment]
Ahh yeah, I misread that and thought that the filter quality was going to interactive viewer. My guess at what is happening is that the image is given a fairly small size that is appropriate for the initial state, but not for the scaled up state. Ideally you'd choose a different mipmap at a certain point.

Needs more investigation

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

The `HTML` renderer produced a good enough enough, but this was reproducible on pretty much every other platform I tested on. I could not, however, test with the `canvaskit` renderer because the image couldn't load. I was getting an error
similar to https://github.com/flutter/flutter/issues/101524

Project attached below for easy access

<details>
<summary>screenshots</summary>

`macOS`
<img src="https://user-images.githubusercontent.com/88313112/167405687-44d37c3b-f1da-46c0-8798-ae0cd106cd5b.png" width="300" />

`HTML`
<img src="https://user-images.githubusercontent.com/88313112/167405673-a07345e0-1f8d-4ed6-847b-1d4c4db192ab.png" width="300"/>

`iOS`
<img src="https://user-images.githubusercontent.com/88313112/167405857-8196e6fb-7fb1-47f4-b05d-fc2e75e8bdf1.PNG" width="300"/>

`android`
<img src="https://user-images.githubusercontent.com/88313112/167406014-17f162d3-bc91-473f-aed1-353970212607.jpeg" width="300"/>
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                             • android-arm64  • Android 11 (API 30)
    • iPhone 13 (mobile)  • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)     • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.987, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.987 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0656a5c033 (9 hours ago), 2022-05-08 18:24:04 -0400
    • Engine revision c930e64a13
    • Dart version 2.18.0 (build 2.18.0-98.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                             • android-arm64  • Android 11 (API 30)
    • iPhone 13 (mobile)  • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)     • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[!] HTTP Host Availability
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: Failed to connect to host in 10 seconds

! Doctor found issues in 1 category.
```
</details>

[sample.zip](https://github.com/flutter/flutter/files/8651481/wbt.zip)

**Comment by CodeCakePie** [comment]
Any news on this topic? :)

**Comment by maxmitchenko** [comment]
Hi! I can't make zoom-in/zoom-out in InteractiveViewer without quality decreasing. Any updates?

**Comment by maxmitchenko** [comment]
Or maybe workarounds?

**Comment by murat-ti** [comment]
Hi. I am also faced this issue.

On image you see the result of showing two images:
1. Image is 1.09mb with 1341 x 616 px dimension
2. Image is 7.72mb with 14041x9933 px dimension

I need to show image in original dimension, because it has map points with coordinates on it.

![image](https://github.com/flutter/flutter/assets/33370868/f6f90e4d-7a1f-4fd1-a01b-5a7616496994)

Because show image on screen I need to calculate dimension for putting that coordinates. And before when I tried recommended ways for calulation dimension it crashed on this step 

Get Image Width and Height Dimensions Examples: https://www.woolha.com/tutorials/flutter-get-image-width-and-height-dimensions-examples

Then I found another way for getting dimension with https://pub.dev/packages/image_size_getter, which read dimension in from metadata and passed this step. Now I need to show image in original size/dimension.

Thanks

**Comment by ufo512** [comment]
Any news?

**Comment by murat-ti** [comment]
Backend guy has rewrite tme 3-rd party library and problem solved.

**Comment by JulianSchmidtZollsoft** [comment]
I wanted to enable zooming on any widget. However, some widgets, such as a PdfViewer, determined their rendering quality based on their constraints. My solution was to render the widget at a resolution suitable for the highest zoom level and initially display it slightly zoomed out so that it occupies the same space. This is basically "virtual super resolution". Be aware that this solution is not very performant.

```dart
/// Allows the user to zoom in and out of the child widget.
/// The child widget will be rendered at a higher resolution ([renderScale]) to reduce pixelation when zooming in.
class ScaledInteractiveViewer extends StatefulWidget {
  const ScaledInteractiveViewer({
    super.key,
    required this.renderScale,
    this.minScale = 0.8,
    this.maxScale = 2.5,
    required this.child,
  });

  final double minScale;
  final double maxScale;

  /// The scale at which the child should be rendered.
  /// If it is 2, the child will be rendered at four times the pixels (2 * width * 2 * height),
  /// while still only taking up the same amount of space on the screen.
  ///
  /// Must not be changed after the widget is built.
  final double renderScale;
  final Widget child;

  @override
  State<ScaledInteractiveViewer> createState() => ScaledInteractiveViewerState();
}

class ScaledInteractiveViewerState extends State<ScaledInteractiveViewer> {
  late final TransformationController transformationController =
      TransformationController(Matrix4.identity().scaled(1 / widget.renderScale));

  @override
  void dispose() {
    transformationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) => InteractiveViewer(
        maxScale: widget.maxScale / widget.renderScale,
        minScale: widget.minScale / widget.renderScale,
        transformationController: transformationController,
        constrained: false,
        child: ConstrainedBox(
          constraints: BoxConstraints(
            maxWidth: constraints.maxWidth * widget.renderScale,
            maxHeight: constraints.maxHeight * widget.renderScale,
          ),
          child: widget.child,
        ),
      ),
    );
  }
}

````
