### ISSUE TITLE
Assertion thrown if a FutureBuilder emits a different type of sliver as the first child in a CustomScrollView

### ISSUE THREAD

**Issue by Maistho** [flutter/flutter#103282]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
3. Wait 5 seconds
4. The app crashes

**Expected results:** The app doesn't crash

**Actual results:** The app crashes

<details>
<summary>Code sample</summary>

```dart
class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('It will crash after 5 seconds')),
      body: CustomScrollView(
        slivers: [
          FutureBuilder<String>(
            future: Future.delayed(const Duration(seconds: 5), () => "Crash"),
            builder: (context, snapshot) {
              if (!snapshot.hasData) {
                return const SliverToBoxAdapter(
                  child: SizedBox(),
                );
              }
              return SliverList(
                delegate: SliverChildListDelegate.fixed([
                  Text(snapshot.data!),
                ]),
              );
            },
          ),
        ],
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
           ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
           The following assertion was thrown during a scheduler callback:
           'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1702 pos 12: 'center!.parent
           == this': is not true.

           Either the assertion indicates an error in the framework itself, or we should provide substantially
           more information in this error message to help you determine and fix the underlying cause.
           In either case, please report this assertion by filing a bug on GitHub:
             https://github.com/flutter/flutter/issues/new?template=2_bug.md

           When the exception was thrown, this was the stack:
           #2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1702:12)
           #3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:974:17)
           #4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:3041:48)
           #5      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1600:32)
           #6      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1641:6)
           #7      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1665:19)
           #8      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
           #9      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
           #10     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206:27)
           #11     new _GrowableList.of (dart:core-patch/growable_array.dart:153:28)
           #12     new List.of (dart:core-patch/array_patch.dart:51:28)
           #13     ListIterable.toList (dart:_internal/iterable.dart:213:44)
           #14     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1666:8)
           #15     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1628:25)
           #16     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1641:6)
           #17     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1513:18)
           #18     WidgetInspectorService._reportStructuredError (package:flutter/src/widgets/widget_inspector.dart:922:44)
           #19     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1177:14)
           #20     RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1389:18)
           #21     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1734:7)
           #22     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
           #23     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
           #24     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
           #25     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
           #26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
           #27     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
           #28     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
           #32     _invoke (dart:ui/hooks.dart:151:10)
           #33     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
           #34     _drawFrame (dart:ui/hooks.dart:115:31)
           (elided 5 frames from class _AssertionError and dart:async)
           ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing flutter_crash_repro...                                        
No issues found! (ran in 2.4s)
```

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
    • Flutter version 2.10.5 at /Users/maistho/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/maistho/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • moto g 8 power (mobile) • ZY227B5C25 • android-arm64 • Android 11 (API 30)
    • macOS (desktop)         • macos      • darwin-x64    • macOS 12.3.1 21E258 darwin-x64
    ! Error: Gustav’s iPhone is not connected. Xcode will continue when Gustav’s iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by Maistho** [comment]
Notes:
- If there is another sliver (ex. `SliverToBoxAdapter(child: SizedBox())`) before the FutureBuilder, the app doesn't crash
- If the FutureBuilder emits another `SliverToBoxAdapter`, the app doesn't crash
- The timing doesn't matter, if I use a `Future.value()` the app will crash immediately when starting
- If the FutureBuilder is given some initialData so that it only emits a SliverList, the app doesn't crash

**Comment by danagbemava-nc** [comment]
Hi @Maistho, this was a known issue and has been fixed in the `beta` and `master` versions. See https://github.com/flutter/flutter/pull/96377. 

It should be available in the next version of stable whenever that may be. 

Closing this as it has already been fixed in recent versions. 

Thank you
