### ISSUE TITLE
NetworkImage Error Text not helpful enough

### ISSUE THREAD

**Issue by viperciyes** [flutter/flutter#103278]
I am in the final days of completing a project, but whenever I do a hot reload, I get this error in the console coming from who knows where. The error shows me no point of origin, and I have tens of FadeINImage widgets in the project. It doesn't matter which page I do the hot reload, I still get the error below. I'm thinking there is no actual error in the code, just some parameter not received by one of the many buildcontext functions, as there are no issues or errors when the app is running for the first time. Either way, I believe it should not return an exception, or it should tell me what part of the code I need to fix.

```
======== Exception caught by image resource service ================================================
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI file:///

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2667:9)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2575:48)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:87:59)
#3      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50:14)
#4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:505:13)
#5      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:380:22)
#6      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:503:83)
#7      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#8      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:333:9)
#9      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:464:26)
#10     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:35)
#11     ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:461:11)
#15     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:453:16)
#16     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:330:5)
#17     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1119:16)
#18     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1071:5)
#19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4925:13)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#22     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#26     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#30     _invoke (dart:ui/hooks.dart:151:10)
#31     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#32     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 6 frames from dart:async)
Image provider: NetworkImage("", scale: 1.0)
Image key: NetworkImage("", scale: 1.0)
====================================================================================================
```

**Comment by Mohamed-7018** [comment]
I predict this error can be caused due to one of the following errors:

- I think this problem occurs when your URL is not having ``` https:// ``` before the URL. This problem can be solved by adding ``` https:// ``` before the URL.

- The error may also occur if you use the following code:
```dart
image: new NetworkImage(imageUrl ?? ''),
```

This is because the app tries to get imageUrl asynchronously. Before the render Url is fetched back, it is null.
NetworkImage(imageUrl ?? '') then tries to use empty string as the url and result in the exception.
I am not sure if this is the best solution, but this seems to work:

``` dart
  Widget get dogImage {
    return imageUrl == null ?
      Container() :
      Container(
        width: 100.0,
        height: 100.0,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          image: DecorationImage(
            fit: BoxFit.cover,
            image: NetworkImage(renderUrl),
          ),
        ),
      );
  }

```

I hope this will help you. If you are still experiencing a similar issue, please reply with a message, including the output of ```flutter doctor -v``` and the code which you predict that it's the reason of this error.

**Comment by tewedaj** [comment]
you should also try `Uri.parse(urlPath)`

**Comment by darshankawar** [comment]
@viperciyes 
You seem to have filed same issue previously https://github.com/flutter/flutter/issues/101082 for which the conclusion from our side was to ask support questions on stackOverflow, so please do the same.
If you think this is a genuine bug in `NetworkImage` and you have concrete steps / code to replicate this error, please provide the same and we'll reopen it to further address it.
Closing for now.
