### ISSUE TITLE
 No static method getMainExecutor

### ISSUE THREAD

**Issue by tigrenok00** [flutter/flutter#103294]
Hi,
l have trouble running a specific app which worked on earlier flutter versions.
On emulator I'm getting the following error:

```
`Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
lib\main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
W/FlutterActivityAndFragmentDelegate(17314): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
E/AndroidRuntime(17314): FATAL EXCEPTION: main
E/AndroidRuntime(17314): Process: XXX, PID: 17314
**E/AndroidRuntime(17314): java.lang.NoSuchMethodError: No static method getMainExecutor(Landroid/content/Context;)Ljava/util/concurrent/Executor; in class Landroidx/core/content/ContextCompat; or its super classes (declaration of 'androidx.core.content.ContextCompat' appears in /data/app/~~9BJxuN7z5AmQPo8xmEEe_Q==/XXX-iz5CrEQ1CIST6D0OKQzgww==/base.apk)**
E/AndroidRuntime(17314): 	at io.flutter.embedding.android.FlutterView.onAttachedToWindow(FlutterView.java:483)
E/AndroidRuntime(17314): 	at android.view.View.dispatchAttachedToWindow(View.java:20753)
E/AndroidRuntime(17314): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
4
E/AndroidRuntime(17314): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
E/AndroidRuntime(17314): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2613)
E/AndroidRuntime(17314): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
E/AndroidRuntime(17314): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
E/AndroidRuntime(17314): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
E/AndroidRuntime(17314): 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
E/AndroidRuntime(17314): 	at android.view.Choreographer.doFrame(Choreographer.java:780)
E/AndroidRuntime(17314): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
E/AndroidRuntime(17314): 	at android.os.Handler.handleCallback(Handler.java:938)
`
```

On physical device I'm getting:

`Error connecting to the service protocol: failed to connect to http://127.0.0.1:51292/8dGuTc40nXk=/`

Flutter doctor output:

```
`[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
    • Flutter version 2.10.5 at C:\flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\admin\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\admin\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Work\chrome_debug.bat

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[!] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (5 available)
    • M2101K9AG (mobile)           • fd22dae3      • android-arm64  • Android 11 (API 30)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 101.0.1210.32

[√] HTTP Host Availability
    • All required HTTP hosts are available`
```

**Comment by darshankawar** [comment]
@tigrenok00 
The error `**E/AndroidRuntime(17314): java.lang.NoSuchMethodError: No static method getMainExecutor(Landroid/content/Context;)Ljava/util/concurrent/Executor; in class Landroidx/core/content/ContextCompat; or its super classes (declaration of 'androidx.core.content.ContextCompat' appears in /data/app/~~9BJxuN7z5AmQPo8xmEEe_Q==/XXX-iz5CrEQ1CIST6D0OKQzgww==/base.apk)**` seems to be coming from third party plugin which you might be using, but I can't tell which plugin since you didn't provide much info. 
I suggest you to take a look at plugins you are using and check which plugin might be throwing the error and accordingly reach out to dedicated plugin repo, or you may also ask the same on support channels like StackOverflow.

Closing from here.
