### ISSUE TITLE
BottomNavigationBar can't handle the number of items changing dynamically

### ISSUE THREAD

**Issue by floitschG** [flutter/flutter#10322]
## Steps to Reproduce

Take the following app:
``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: const Text("Door Manager")),
      bottomNavigationBar: new BottomNavigationBar(
          items: new List.generate(2, (i) {  // <================== 2 to 3
            return new BottomNavigationBarItem(
                icon: new Icon(Icons.bug_report), title: new Text("$i"));
          }),
          currentIndex: _currentIndex,
          onTap: (int index) {
            setState(() {
              _currentIndex = index;
            });
          }),
      body: const Text("foo"),
    );
  }
}
```

1. Start the app on the phone.
2. Change the marked line from 2 to 3
3. Press hot reload.

The app crashes. No hot-reload will fix the issue. From a user's perspective it looks like there is a bug in the code.

## Logs
```
$ flutter run
Launching lib/main.dart on Pixel in debug mode...
Running 'gradle assembleDebug'...                     8.8s
Built build/app/outputs/apk/app-debug.apk (21.5MB).
Installing build/app/outputs/apk/app.apk...           6.5s
Syncing files to device Pixel...                      4.7s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Pixel is available at: http://127.0.0.1:8108/
For a more detailed help message, press "h". To quit, press "q".

Initializing hot reload...                                
I/flutter ( 2938): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2938): The following RangeError was thrown building BottomNavigationBar(dirty; state:
I/flutter ( 2938): _BottomNavigationBarState#321338430(tracking 2 tickers)):
I/flutter ( 2938): RangeError (index): Invalid value: Not in range 0..1, inclusive: 2
I/flutter ( 2938): 
I/flutter ( 2938): When the exception was thrown, this was the stack:
I/flutter ( 2938): #0      List.[] (dart:core-patch/growable_array.dart:151)
I/flutter ( 2938): #1      _BottomNavigationBarState.build (package:flutter/src/material/bottom_navigation_bar.dart:336:49)
I/flutter ( 2938): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3241:27)
I/flutter ( 2938): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3151:15)
I/flutter ( 2938): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #5      StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #9      ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #11     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3826:32)
I/flutter ( 2938): #12     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4208:17)
I/flutter ( 2938): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #16     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #20     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #26     StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #44     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #60     StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #68     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #72     StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #80     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #90     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #94     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #96     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3826:32)
I/flutter ( 2938): #97     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4208:17)
I/flutter ( 2938): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #99     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 2938): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #103    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #107    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #113    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #121    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #125    StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #129    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #133    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #137    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #143    StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #147    StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #151    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #155    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #159    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #163    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #167    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #171    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1905:33)
I/flutter ( 2938): #172    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:360:20)
I/flutter ( 2938): #173    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
I/flutter ( 2938): #174    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:685:15)
I/flutter ( 2938): #175    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:633:9)
I/flutter ( 2938): #176    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/rendering/binding.dart:247:20)
I/flutter ( 2938): #178    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
I/flutter ( 2938): #179    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
I/flutter ( 2938): #180    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
I/flutter ( 2938): (elided one frame from package dart:async-patch)
I/flutter ( 2938): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 410 of 425 libraries in 3,687ms.

```

## Flutter Doctor
```
$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /mnt/ssd/floitsch/code/flutter_apps/flutter
    • Framework revision 973304d5fb (7 days ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /usr/local/google/home/floitsch/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio-with-blaze-2.3/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin version 162.2485
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] IntelliJ IDEA Community Edition (version 2016.1)
    • Dart plugin version 145.971.7
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 14.0

[✓] Connected devices
    • Pixel • FA6B90302512 • android-arm • Android 7.1.2 (API 25)
```

**Comment by floitschG** [comment]
The tabbar has a similar issue:

```
I/flutter (26468): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (26468): The following assertion was thrown while handling a gesture:
I/flutter (26468): 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 93 pos 12: 'value >= 0 &&
I/flutter (26468): value < length': is not true.
I/flutter (26468): 
I/flutter (26468): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (26468): more information in this error message to help you determine and fix the underlying cause.
I/flutter (26468): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (26468):   https://github.com/flutter/flutter/issues/new
I/flutter (26468): 
I/flutter (26468): When the exception was thrown, this was the stack:
I/flutter (26468): #2      TabController._changeIndex (package:flutter/src/material/tab_controller.dart:93:12)
I/flutter (26468): #3      TabController.animateTo (package:flutter/src/material/tab_controller.dart:145:5)
I/flutter (26468): #4      _TabBarState._handleTap (package:flutter/src/material/tabs.dart:622:17)
I/flutter (26468): #5      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:694:21)
I/flutter (26468): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:194:14)
I/flutter (26468): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:65:24)
I/flutter (26468): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:148:9)
I/flutter (26468): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
I/flutter (26468): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:260:9)
I/flutter (26468): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (26468): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (26468): #13     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:122:19)
I/flutter (26468): #14     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:100:22)
I/flutter (26468): #15     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:81:7)
I/flutter (26468): #16     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:40:7)
I/flutter (26468): #17     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:33:5)
I/flutter (26468): #18     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:73)
I/flutter (26468): (elided 2 frames from class _AssertionError)
I/flutter (26468): 
I/flutter (26468): Handler: onTap
I/flutter (26468): Recognizer:
I/flutter (26468):   Instance of 'TapGestureRecognizer'
I/flutter (26468): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (26468): Another exception was thrown: 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 93 pos 12: 'value >= 0 && value < length': is not true.
I/flutter (26468): Another exception was thrown: 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 93 pos 12: 'value >= 0 && value < length': is not true.
```
