### ISSUE TITLE
Strange flutter fuchsia_reload flag behavior

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#10327]
## Steps to Reproduce

When I use flutter fuchsia_reload with -a, it crashes with "exited unexpectedly". 
When I use flutter fuchsia_reload with --address, it crashes and generates a stack dump.

This seems strange, I would expect both to fail in the same way. 

Examples of both command lines are shown below.

## Logs

```
jimbe:/media/jimbe/mojossd/fuchsia$ lib/flutter/bin/flutter fuchsia_reload  --address 192.168.42.39 -f `pwd` --list

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 4b26a85b70000000)
Crash report written to /media/jimbe/mojossd/fuchsia/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```
```
jimbe:/media/jimbe/mojossd/fuchsia$ lib/flutter/bin/flutter fuchsia_reload  -a 192.168.42.39 -f `pwd` --list
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: No route to host, errno = 113, address = 192.168.42.39, port = 43798
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:670)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:500)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:348)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:176)
#5      FuchsiaReloadCommand._listVMs (package:flutter_tools/src/commands/fuchsia_reload.dart:249)
<asynchronous suspension>
#6      FuchsiaReloadCommand.runCommand (package:flutter_tools/src/commands/fuchsia_reload.dart:98)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:206)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#15     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1467)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#24     main (file:///media/jimbe/mojossd/fuchsia/lib/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
jimbe:/media/jimbe/mojossd/fuchsia$ 
```

## Flutter Doctor

```
## flutter doctor

[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /media/jimbe/mojossd/fuchsia/lib/flutter
    • Framework revision 7fb798f5f1 (4 hours ago), 2017-05-25 09:42:55 -0700
    • Engine revision af60e003d0
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • Java binary at: /usr/local/buildtools/java/jdk/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-google-v7-155411648-155195300)

[✓] Android Studio (version 2.1)
    • Android Studio at /opt/android-studio-2.1
    • Gradle version 2.14.1
    • Unable to find bundled Java version.

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 14.0

[✓] Connected devices
    • None
```

**Comment by tvolkert** [comment]
Closing this, as we're tracking hot reload on Fuchsia in separate bugs.  Please feel free to reopen if necessary,

**Comment by joshjinlee** [comment]
Though this an old issue, I've recently got the same error message after an Android update and can't send outgoing http requests from my device to a server running on my computer:

`SocketException: OS Error: No route to host, errno = 113, address = 169.254.206.240, port = 43026`

I've tried turning off the firewall and still nothing.

**Comment by tvolkert** [comment]
@joshjinlee this issue was specific to the Fuchsia workflow, so if you're using Android, you're on a different code path.  The "no route to host" error message simply indicates a lack of network connectivity to the desired host.
