### ISSUE TITLE
[in_app_purchase] Fatal Exception: java.lang.IllegalStateException Reply already submitted

### ISSUE THREAD

**Issue by youssefali424** [flutter/flutter#103432]
I've got an error through Crashlytics
with in_app_purchase: ^3.0.0

## Steps to Reproduce

I couldn't reproduce it locally but I guess it happens because of a race condition 
<details>
  <summary>Logs</summary>

```
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl$1.onSkuDetailsResponse(MethodCallHandlerImpl.java:30)
       at com.android.billingclient.api.zzac.run(zzac.java:36)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:7080)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)</summary>
```

```
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (3 weeks ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.25)
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.67.0)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

</details>

**Comment by darshankawar** [comment]
> at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl$1.onSkuDetailsResponse(MethodCallHandlerImpl.java:30)
>        at com.android.billingclient.api.zzac.run(zzac.java:36)

Seems to be indeed coming from the plugin. There was an old similar but fixed issue: https://github.com/flutter/flutter/issues/32462

Labeling it for further investigation as there doesn't seem to be reproducible use case.

**Comment by deskangel** [comment]
![Screenshot_20230412_200326_org telegram messenger](https://user-images.githubusercontent.com/63033549/231451714-06801323-3d36-4255-99bb-306b8959cc71.png)
encounter the same issue.

**Comment by ozzy1873** [comment]
I am seeing this too:

Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.lambda$queryProductDetailsAsync$0(MethodCallHandlerImpl.java:26)
       at com.android.billingclient.api.BillingClientImpl.zzJ(BillingClientImpl.java:19)
       at com.android.billingclient.api.zzl.run(zzl.java:4)
       at com.android.billingclient.api.zzw.run(zzw.java:29)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by serhii-k** [comment]
Hello, I don't think my comment is related to the original issue, however it seems to be related with @deskangel and @ozzy1873 comments.

In Crashlytics recently I started to see plenty of similar crashes (for the past 7 days 77 users affected).

**Important** (which may be different to the original issue)
In the case of my app the crashes happen:
- in 94% cases on Huawei devices
- 89% Android 8
- 97% background

Please check these stack traces from Crashlytics:

<details><summary>Stack trace 1 (very common)</summary>

```console
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.lambda$queryProductDetailsAsync$0(MethodCallHandlerImpl.java:26)
       at com.android.billingclient.api.BillingClientImpl.zzJ(BillingClientImpl.java:19)
       at com.android.billingclient.api.zzl.run(zzl.java:4)
       at com.android.billingclient.api.zzw.run(zzw.java:29)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

</details>

<details><summary>Stack trace 2 (much less common)</summary>

```console
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.lambda$queryPurchasesAsync$2(MethodCallHandlerImpl.java:33)
       at com.android.billingclient.api.BillingClientImpl.zzL(BillingClientImpl.java:19)
       at com.android.billingclient.api.zzu.run(zzu.java:4)
       at com.android.billingclient.api.zzw.run(zzw.java:29)
       at android.os.Handler.handleCallback(Handler.java:809)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7555)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

</details>

**Comment by serhii-k** [comment]
I have found that developers of RevenueCat also had a similar issue that happened mostly on Huawei devices which was resolved after some investigation. Maybe that can be helpful in the resolution of this issue.
[https://github.com/RevenueCat/purchases-flutter/issues/245](https://github.com/RevenueCat/purchases-flutter/issues/245)

**Comment by youssefali424** [comment]
@darshankawar https://github.com/RevenueCat/purchases-flutter/issues/245#issuecomment-931708590
please look at this comment if possible I think this is the issue.
this issue has been active for so long and it affected a lot four user base but at the same time it is s hard reproduce but crashlytics reports it

**Comment by putnokiabel** [comment]
Looks like the original issue originates from `onSkuDetailsResponse`.

I just wanted to add that I'm seeing the same issue from `queryProductDetailsAsync` on the latest version of the plugin:
```
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
       at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.lambda$queryProductDetailsAsync$0(MethodCallHandlerImpl.java:228)
       at com.android.billingclient.api.BillingClientImpl.zzJ(com.android.billingclient:billing@@6.0.1:3)
       at com.android.billingclient.api.zzl.run(com.android.billingclient:billing@@6.0.1:4)
       at com.android.billingclient.api.zzw.run(com.android.billingclient:billing@@6.0.1:4)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Seems to happen exclusively on Samsung and Huawei devices on my end, and 100% of the crashes happen when the app is in the background:
<img width="557" alt="image" src="https://github.com/flutter/flutter/assets/29568469/dea1926d-5ef1-46e9-97b4-1e52ba63b94c">

**Comment by FluffyBunniesTasteTheBest** [comment]
Same here with version 3.1.13 and a slightly different stack trace. Happens mainly on Huawei devices, though some Samsung, Nokia and TCL devices are reported as well. 56 effected users, of which 30 are running either Android 8 or 8.1. The remaining 26 crashes are distributed over Android 9 - 14. 

```
Exception java.lang.IllegalStateException: Reply already submitted
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:435)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java)
  at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.lambda$queryProductDetailsAsync$0 (MethodCallHandlerImpl.java:228)
  at com.android.billingclient.api.BillingClientImpl.zzJ (com.android.billingclient:billing@@6.0.1:3)
  at com.android.billingclient.api.zzl.run (com.android.billingclient:billing@@6.0.1)
  at com.android.billingclient.api.zzw.run (com.android.billingclient:billing@@6.0.1:4)
  at android.os.Handler.handleCallback (Handler.java:808)
  at android.os.Handler.dispatchMessage (Handler.java:101)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7529)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
```

**Comment by AsjadSiddiqui** [comment]
Same here with 3.22.3

Stack trace from Vivo S19 running Android 14

```  
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:14)
       at io.flutter.plugins.inapppurchase.Messages$InAppPurchaseApi$7.success(Messages.java:10)
       at io.flutter.plugins.inapppurchase.Messages$InAppPurchaseApi$7.success(Messages.java:2)
       at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.lambda$queryProductDetailsAsync$4(MethodCallHandlerImpl.java:28)
       at com.android.billingclient.api.BillingClientImpl.zzS(BillingClientImpl.java:19)
       at com.android.billingclient.api.zzz.run(zzz.java:4)
       at com.android.billingclient.api.zzn.run(zzn.java:29)
       at android.os.Handler.handleCallback(Handler.java:1013)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:328)
       at android.app.ActivityThread.main(ActivityThread.java:9233)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
```
        
        
More stack traces from Itel P17 running Android 11

```      
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2015, result=0, data=null} to activity {com.mineswap.app/com.mineswap.app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5157)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5198)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2125)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7989)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:635)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```


```  
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at com.jayesh.flutter_contact_picker.FlutterContactPickerPlugin.onActivityResult(FlutterContactPickerPlugin.java:15)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:14)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:10)
       at android.app.Activity.dispatchActivityResult(Activity.java:8462)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5150)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5198)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2125)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7989)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:635)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by jiagengArctuition** [comment]
same here with flutter `3.27.4` and  `in_app_purchase_android: 0.4.0+2`

<img width="476" height="562" alt="Image" src="https://github.com/user-attachments/assets/0ea7a355-dfdd-47c4-8d65-3b0df096e502" />
