### ISSUE TITLE
[Multiple Flutter] Occasional MissingPluginException

### ISSUE THREAD

**Issue by canluhuang** [flutter/flutter#103483]
We found occasional MissingPluginException occurs when our application used the multi-flutter feature：

MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_android)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:183)
    <asynchronous suspension>
    #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:116)
    <asynchronous suspension>
    #2      RMonitorConfigManager._getConfigStorageFile (package:rmonitor_flutter/src/config/rmonitor_config.dart:94)
    <asynchronous suspension>
    #3      RMonitorConfigManager._loadConfigContent (package:rmonitor_flutter/src/config/rmonitor_config.dart:114)
    <asynchronous suspension>

We analyzed the source code of the swap engine and found swap engine may run before plugin register：

` 
// 1. The engine is run immediately when FlutterJNI.swap is executed
    FlutterJNI newFlutterJNI =
        flutterJNI.spawn(
            dartEntrypoint.dartEntrypointFunctionName,
            dartEntrypoint.dartEntrypointLibrary,
            initialRoute,
            dartEntrypointArgs);

 // 2. Plugin register in FlutterEngine Constructor
    return new FlutterEngine(
        context, // Context.
        null, // FlutterLoader. A null value passed here causes the constructor to get it from the
        // FlutterInjector.
        newFlutterJNI); // FlutterJNI.
  }
`
These two steps run in different threads，so it may cause an error.
Is there any way we can avoid this error？

**Comment by darshankawar** [comment]
@canluhuang 
Thanks for the report. Can you provide `flutter doctor -v` and a minimal code sample that we can directly run which triggers the exception you reported ?

**Comment by canluhuang** [comment]
@darshankawar Thanks for your reply,  this my flutter version info:
```
[✓] Flutter (Channel unknown, 2.10.4, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/lukehuang/.rflutter_sdk/rflutter
    • Upstream repository unknown
    • Framework revision c860cba910 (7 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lukehuang/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 211.7798

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.6668.124

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • IN2010 (mobile) • 61545440 • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by canluhuang** [comment]
@darshankawar 
The simple code that reproduce the problem push to https://github.com/canluhuang/multi_flutters_simaple

The problem can be reproduced by quickly entering and exiting, like this video：
https://user-images.githubusercontent.com/7105187/168107563-434caee3-119a-45c5-8da8-a983f46ca62a.mp4

This is the exception log：
```
2022-05-12 23:10:36.082 28718-14488/com.tencent.multi_flutters E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_android)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175)
    <asynchronous suspension>
    #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115)
    <asynchronous suspension>
    #2      main (package:multi_flutters_module/main.dart:9)
    <asynchronous suspension>
```

In addition, this problem only occurs in the release version, and the debug version does not appear.

**Comment by darshankawar** [comment]
@canluhuang 
You are probably hitting same issue as mentioned in this link and check this issue comment for solutioon which is available on latest master. https://github.com/flutter/flutter/issues/99155#issuecomment-1058499437

So please upgrade to latest master and try per solution mentioned in it and see if it helps.

**Comment by canluhuang** [comment]
@darshankawar It doesn't seem to be the same problem.
The issue #99155 is in the backgroud isolates scene, the dart side is not registered, but our problem is caused by the swap engine scene, the native side is registered after the main function is executed.
The latest master still has this problem.

**Comment by darshankawar** [comment]
> The simple code that reproduce the problem push to https://github.com/canluhuang/multi_flutters_simaple

I tried to replicate on Samsung device but was unable to see the `MissingPluginException`. 

Based on the report, I'll keep it open and label for further insights from the team.

**Comment by chinmaygarde** [comment]
cc @gaaclarke

**Comment by zewsummer** [comment]
> 



> @darshankawar It doesn't seem to be the same problem. The issue #99155 is in the backgroud isolates scene, the dart side is not registered, but our problem is caused by the swap engine scene, the native side is registered after the main function is executed. The latest master still has this problem.

hi,could you please tell me how you solve this problem? So did I

**Comment by gaaclarke** [comment]
This would need some reproduction code.  It sounds you are running into a threading issue where you are sending messages before a handler is set on a different thread, or as a result of an asynchronous operation.

**Comment by zewsummer** [comment]
> This would need some reproduction code. It sounds you are running into a threading issue where you are sending messages before a handler is set on a different thread, or as a result of an asynchronous operation.

Hello, I can basically reproduce, the probability is relatively high, the conclusion is certain, that is, when executing the code of dart side in SPWAN, when dart side  sending the message, I found that the plug-in was not registered, so I reported MissingPluginException. My temporary solution is to make the dart build return one loading Widget first, and then wait for the registerPlugins to send a message to the dart side for page display, which can temporarily avoid this problem. Could you please give me a better solution?

FlutterEngine code is

if (automaticallyRegisterPlugins && flutterLoader.automaticallyRegisterPlugins()) {
    
      registerPlugins();
//makesure dart scrren refresh when  after registerPlugins
      MethodChannel sSchemeServiceChannel = new MethodChannel(this.getDartExecutor(),
              "com.xxx/engine_startservice");

      sSchemeServiceChannel.setMethodCallHandler(new MethodChannel.MethodCallHandler() {
        @Override
        public void onMethodCall(MethodCall call, MethodChannel.Result result) {
          switch (call.method) {
            default:
              result.notImplemented();
          }
          result.success(null);
        }
      });

      sSchemeServiceChannel.invokeMethod("flutter_view_refresh", new ArrayList<String>() , new MethodChannel.Result() {
        @Override
        public void success(@android.support.annotation.Nullable Object result) {
          Log.i("xxx_flutter_engine","success");
        }

        @Override
        public void error(String errorCode, @android.support.annotation.Nullable String errorMessage, @android.support.annotation.Nullable Object errorDetails) {
          Log.i("xxx_flutter_engine","errorMessage:"+errorMessage);
        }

        @Override
        public void notImplemented() {
          Log.i("xxx_flutter_engine","notImplemented");
        }
      });

    }
  }

**Comment by zewsummer** [comment]
> This would need some reproduction code. It sounds you are running into a threading issue where you are sending messages before a handler is set on a different thread, or as a result of an asynchronous operation.

Hello, I can basically reproduce, the probability is relatively high, the conclusion is certain, that is, when executing the code of dart side in SPWAN, when dart side  sending the message, I found that the plug-in was not registered, so I reported MissingPluginException. My temporary solution is to make the dart build return one loading Widget first, and then wait for the registerPlugins to send a message to the dart side for page display, which can temporarily avoid this problem. Could you please give me a better solution?

FlutterEngine code is

if (automaticallyRegisterPlugins && flutterLoader.automaticallyRegisterPlugins()) {
    
      registerPlugins();
//makesure dart scrren refresh when  after registerPlugins
      MethodChannel sSchemeServiceChannel = new MethodChannel(this.getDartExecutor(),
              "com.xxx/engine_startservice");

      sSchemeServiceChannel.setMethodCallHandler(new MethodChannel.MethodCallHandler() {
        @Override
        public void onMethodCall(MethodCall call, MethodChannel.Result result) {
          switch (call.method) {
            default:
              result.notImplemented();
          }
          result.success(null);
        }
      });

      sSchemeServiceChannel.invokeMethod("flutter_view_refresh", new ArrayList<String>() , new MethodChannel.Result() {
        @Override
        public void success(@android.support.annotation.Nullable Object result) {
          Log.i("xxx_flutter_engine","success");
        }

        @Override
        public void error(String errorCode, @android.support.annotation.Nullable String errorMessage, @android.support.annotation.Nullable Object errorDetails) {
          Log.i("xxx_flutter_engine","errorMessage:"+errorMessage);
        }

        @Override
        public void notImplemented() {
          Log.i("xxx_flutter_engine","notImplemented");
        }
      });

    }
  }

**Comment by zewsummer** [comment]
> or as a result of an asynchronous operation.

The best solution would be synchronous, where  execute the Dart code only after you register the plug-in, and I believe this problem should always exist

**Comment by gaaclarke** [comment]
I'm sorry, when I say reproduction code, I mean something I can execute locally to reproduce the problem.  It helps you communicate your problem and allows me to understand what is a bug versus what is a bad API, etc.  I responded to a similar issue, maybe this is what you are running into: https://github.com/flutter/flutter/issues/108272#issuecomment-1194332979

**Comment by Nayuta403** [comment]
> > or as a result of an asynchronous operation.
> 
> The best solution would be synchronous, where execute the Dart code only after you register the plug-in, and I believe this problem should always exist

Yes, I think so too. In fact, for FlutterActivity, plugin registration is separate from Dart running. And plugins were registered in `onCreate`, Dart run in `onStart`.

@zewsummer  

For your question, you can try calling this line of code after the engine is created
```java
 mFlutterEngine.getDartExecutor().getBinaryMessenger().enableBufferingIncomingMessages();
```
This change is being submitted by @gaaclarke in https://github.com/flutter/engine/pull/29147.  When this flag is turned on, plugins that have not yet been registered on the Java side are put into a buffer queue, waiting to be called back to dart when the plugin is registered.

Note that this will no longer cause the long beard to throw a MissingPluginException.

**Comment by zewsummer** [comment]
> 

Can this PR solve the problem of dart and plugin registration being out of sync?

**Comment by zewsummer** [comment]
> > > or as a result of an asynchronous operation.
> > 
> > 
> > The best solution would be synchronous, where execute the Dart code only after you register the plug-in, and I believe this problem should always exist
> 
> Yes, I think so too. In fact, for FlutterActivity, plugin registration is separate from Dart running. And plugins were registered in `onCreate`, Dart run in `onStart`.
> 
> @zewsummer
> 
> For your question, you can try calling this line of code after the engine is created
> 
> ```java
>  mFlutterEngine.getDartExecutor().getBinaryMessenger().enableBufferingIncomingMessages();
> ```
> 
> This change is being submitted by @gaaclarke in [flutter/engine#29147](https://github.com/flutter/engine/pull/29147). When this flag is turned on, plugins that have not yet been registered on the Java side are put into a buffer queue, waiting to be called back to dart when the plugin is registered.
> 
> Note that this will no longer cause the long beard to throw a MissingPluginException.
> 
> But I think in the long run this problem needs to be solved because other people are facing the same problem.

Hello, I still get an error using this method。
error：MissingPluginException was thrown: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)


if (activeEngines.size() == 0) {
      LoggerFactory.getTraceLogger().info("FlutterEngineGroup","create main engine："+initialRoute);
      engine = createEngine(context);
      if (initialRoute != null) {
        engine.getNavigationChannel().setInitialRoute(initialRoute);
      }
      engine.getDartExecutor().executeDartEntrypoint(dartEntrypoint);
      engine.getDartExecutor().getBinaryMessenger().enableBufferingIncomingMessages();
    } else {
      Log.i("FlutterEngineGroup","create fork engine："+initialRoute);
      engine = activeEngines.get(0).spawn(context, dartEntrypoint, initialRoute);
    }

**Comment by Nayuta403** [comment]
You should move to the end, otherwise this will not work for the spawn engine

if (activeEngines.size() == 0) {
Log.i("FlutterEngineGroup","create main engine："+initialRoute);
engine = createEngine(context);
if (initialRoute != null) {
engine.getNavigationChannel().setInitialRoute(initialRoute);
}
engine.getDartExecutor().executeDartEntrypoint(dartEntrypoint);
} else {
Log.i("FlutterEngineGroup","create fork engine："+initialRoute);
engine = activeEngines.get(0).spawn(context, dartEntrypoint, initialRoute);
}

engine.getDartExecutor().getBinaryMessenger().enableBufferingIncomingMessages();

**Comment by zewsummer** [comment]
> engine.getDartExecutor().getBinaryMessenger().enableBufferingIncomingMessages();

I just tested it and it still gets an error

MissingPluginException was thrown: MissingPluginException(No implementation found for method getApplicationSupportDirectory on channel plugins.flutter.io/path_provider)



    if (activeEngines.size() == 0) {
      LoggerFactory.getTraceLogger().info("FlutterEngineGroup","create main engine："+initialRoute);
      engine = createEngine(context);
      if (initialRoute != null) {
        engine.getNavigationChannel().setInitialRoute(initialRoute);
      }
      engine.getDartExecutor().executeDartEntrypoint(dartEntrypoint);
    } else {
      LoggerFactory.getTraceLogger().info("FlutterEngineGroup","create fork engine："+initialRoute);
      engine = activeEngines.get(0).spawn(context, dartEntrypoint, initialRoute);
    }

    engine.getDartExecutor().getBinaryMessenger().enableBufferingIncomingMessages();

**Comment by Nayuta403** [comment]
It may not be the same problem, but can you provide a reproducible example

**Comment by zewsummer** [comment]
> It may not be the same problem, but can you provide a reproducible example

There is no example, I look at your issue. I have tested that the spwan engine still generates MissingPluginException
https://github.com/flutter/flutter/issues/108272

**Comment by Nayuta403** [comment]
In my example, the plugin registration delay was 100ms, resulting in the initialization of FlutterEngine and the plugin registration not being in the same event.

**Comment by Nayuta403** [comment]
> > It may not be the same problem, but can you provide a reproducible example
> 
> There is no example, I look at your issue. I have tested that the spwan engine still generates MissingPluginException #108272

@zewsummer 
In fact, as mentioned by https://github.com/flutter/flutter/issues/108272#issuecomment-1194332979 , the initialization of FlutterEngine takes place in the same event as the plugin registration, while the Dart side call plugin will be added to eventLoop, which in theory must be later than the plug-in registration. 

I tried to make the Platform thread sleep for 200 milliseconds (still in the same event) when the plugin was registered, and no more exceptions would be thrown.

```kotlin
    init {
        val app = activity.applicationContext as App
        // This has to be lazy to avoid creation before the FlutterEngineGroup.
        val dartEntrypoint =
            DartExecutor.DartEntrypoint(
                FlutterInjector.instance().flutterLoader().findAppBundlePath(), entrypoint
            )
        engine = app.engines.createAndRunEngine(activity, dartEntrypoint, initialRoute);
        this.delegate = delegate
        Thread.sleep(200)
        Log.i("Nayuta", " multiple-flutters channel register ")
        channel = MethodChannel(engine.dartExecutor.binaryMessenger, "multiple-flutters")
        attach()
    }
```

**Comment by Nayuta403** [comment]
Is your question bound to arise? I think first you can check where the plugins are registered to make sure they are in the same event. Second, you can add a log to the location where the plugins are called and registered on the Dart side to observe their timing.

**Comment by zewsummer** [comment]
> Is your question bound to arise? I think first you can check where the plugins are registered to make sure they are in the same event. Second, you can add a log to the location where the plugins are called and registered on the Dart side to observe their timing.

It is OK for me. The problem in yesterday's test is due to other problems. This scheme is feasible
