### ISSUE TITLE
Devicelab Mac41 is failing testing consistently with `BOT_DIED`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#103522]
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-41

Currently it is refusing connection:
```
ssh flutter@flutter-devicelab-mac-41.mtv.corp.google.com
F0511 11:53:55.761759   92915 helper.go:391] Failed to initialize session: upgrading to websocket: bad status
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

**Comment by yusuf-goog** [comment]
Looks like the machine is in a boot loop. It gets to the login screen and then reboots.

Mac-46 seems to also be in the same situation.

Will need to go back and take a closer look at what might be causing this.

**Comment by yusuf-goog** [comment]
On [mac-46](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-46) it shows it was 


```
Device doctor tool error: b'2022-05-11 12:32:51.228 defaults[620:5398] \nThe domain/default pair of (/Library/Preferences/com.apple.loginwindow, autoLoginUser) does not exist\nsecurity: cert import failed: One or more parameters passed to a function were not valid.\nsecurity: problem decoding\n'
--
```

**Comment by keyonghan** [comment]
I cannot ssh to mac-46 neither. Is that possible we bring the ssh back? We do need to quarantine mac-41 as it continuously picks up and fails new tasks (somehow I cannnot stop the bot gracefully from LUCI UI).

**Comment by yusuf-goog** [comment]
On mac-41, looks like this was the issue which was constantly restarting the bot (and when it automatically recovered):

```
563 2022-05-12 13:01:06.741 E: Singleton "/opt/s/swarming.lck" is held by "b''"
Traceback (most recent call last):
  File "/opt/s/swarming_bot.1.zip/bot_code/singleton.py", line 61, in acquire
    fcntl.flock(self.handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 35] Resource temporarily unavailable
563 2022-05-12 13:01:06.742 I: Restarting machine with command sudo -n /sbin/shutdown -r now (Found a previous bot, 563 rebooting as a workaround for https://crbug.com/569610.)
563 2022-05-12 13:01:06.766 I: Restart command exited successfully
563 2022-05-12 13:01:06.766 I: Sleeping for 300
524 2022-05-12 13:01:06.793 I: Got signal 15
524 2022-05-12 13:01:09.250 I: RAM GB/core = 2.000
524 2022-05-12 13:01:09.257 E: Failed to read disk info: Command '['diskutil', 'list', '-plist', 'physical']' returned non-zero exit status 1.
524 2022-05-12 13:01:09.277 I: get_dimensions(): 3.864s
524 2022-05-12 13:01:10.611 I: [mmutex] Not reporting state as maintenance
524 2022-05-12 13:01:10.611 I: get_state(): 1.334s
524 2022-05-12 13:01:10.611 I: get_settings(): 0s
524 2022-05-12 13:01:10.611 I: Early quit 2
524 2022-05-12 13:01:10.612 I: on_bot_shutdown(): 0s
524 2022-05-12 13:01:10.612 I: main() returning
524 2022-05-12 13:01:10.612 I: bot_main exit code: 0
125 2022-05-12 13:01:33.855 I: start_bot with args: []
125 2022-05-12 13:01:34.387 I: importing bot_main: /opt/s/swarming_bot.1.zip, 8d6f0c4722297cda8a97768f583c37ef42a36c37a10e49b73df1b343e412ecc5
125 2022-05-12 13:01:34.388 I: [singleton] acquire: /opt/s/swarming.lck = <_io.BufferedRandom name='/opt/s/swarming.lck'>
125 2022-05-12 13:01:34.422 D: Starting new HTTP connection (1): metadata.google.internal:80
125 2022-05-12 13:01:34.432 I: Configuration file does not exist, ignoring: /etc/chrome-infra/ts-mon.json
125 2022-05-12 13:01:34.432 E: ts_mon monitoring is disabled because the endpoint provided is invalid or not supported:
125 2022-05-12 13:01:34.434 D: Starting new HTTPS connection (1): chromium-swarm.appspot.com:443
125 2022-05-12 13:01:35.193 D: https://chromium-swarm.appspot.com:443 "GET /swarming/api/v1/bot/server_ping HTTP/1.1" 200 None
125 2022-05-12 13:01:35.194 D: Request https://chromium-swarm.appspot.com/swarming/api/v1/bot/server_ping succeeded
531 2022-05-12 13:01:35.829 I: start_bot with args: []
531 2022-05-12 13:01:36.052 I: importing bot_main: /opt/s/swarming_bot.1.zip, 8d6f0c4722297cda8a97768f583c37ef42a36c37a10e49b73df1b343e412ecc5
531 2022-05-12 13:01:36.053 E: Singleton "/opt/s/swarming.lck" is held by "b''"
Traceback (most recent call last):
  File "/opt/s/swarming_bot.1.zip/bot_code/singleton.py", line 61, in acquire
    fcntl.flock(self.handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 35] Resource temporarily unavailable
531 2022-05-12 13:01:36.080 I: Restarting machine with command sudo -n /sbin/shutdown -r now (Found a previous bot, 531 rebooting as a workaround for https://crbug.com/569610.)
125 2022-05-12 13:01:36.512 I: Got signal 15
125 2022-05-12 13:01:38.816 I: RAM GB/core = 2.000
125 2022-05-12 13:01:38.823 E: Failed to read disk info: Command '['diskutil', 'list', '-plist', 'physical']' returned non-zero exit status 1.
125 2022-05-12 13:01:38.838 I: get_dimensions(): 3.644s
125 2022-05-12 13:01:40.040 I: [mmutex] Not reporting state as maintenance
125 2022-05-12 13:01:40.041 I: get_state(): 1.202s
125 2022-05-12 13:01:40.041 I: get_settings(): 0s
125 2022-05-12 13:01:40.041 I: Early quit 2
125 2022-05-12 13:01:40.042 I: on_bot_shutdown(): 0.001s
125 2022-05-12 13:01:40.042 I: main() returning
125 2022-05-12 13:01:40.042 I: bot_main exit code: 0
125 2022-05-12 13:02:03.720 I: start_bot with args: []
125 2022-05-12 13:02:04.071 I: importing bot_main: /opt/s/swarming_bot.1.zip, 8d6f0c4722297cda8a97768f583c37ef42a36c37a10e49b73df1b343e412ecc5
125 2022-05-12 13:02:04.072 I: [singleton] acquire: /opt/s/swarming.lck = <_io.BufferedRandom name='/opt/s/swarming.lck'>
125 2022-05-12 13:02:04.126 D: Starting new HTTP connection (1): metadata.google.internal:80
125 2022-05-12 13:02:04.136 I: Configuration file does not exist, ignoring: /etc/chrome-infra/ts-mon.json
125 2022-05-12 13:02:04.136 E: ts_mon monitoring is disabled because the endpoint provided is invalid or not supported:
125 2022-05-12 13:02:04.138 D: Starting new HTTPS connection (1): chromium-swarm.appspot.com:443
125 2022-05-12 13:02:05.023 D: https://chromium-swarm.appspot.com:443 "GET /swarming/api/v1/bot/server_ping HTTP/1.1" 200 None
125 2022-05-12 13:02:05.026 D: Request https://chromium-swarm.appspot.com/swarming/api/v1/bot/server_ping succeeded
125 2022-05-12 13:02:07.625 I: RAM GB/core = 2.000
125 2022-05-12 13:02:08.498 I: get_dimensions(): 3.471s
125 2022-05-12 13:02:08.951 I: [mmutex] Not reporting state as maintenance
125 2022-05-12 13:02:08.952 I: get_state(): 0.453s
125 2022-05-12 13:02:08.952 I: get_settings(): 0s
125 2022-05-12 13:02:08.952 I: Fetching initial auth headers
125 2022-05-12 13:02:08.952 I: ts_mon hook_name='get_authentication_headers' pool='cores:8|cpu:arm-64|cpu:arm64-64-Apple_M1|device:iPhone8,1|display_attached:1|gce:0|gpu:none|mac_model:Macmini9,1|machine_type:n1-highcpu-8|os:Mac-12.2-21D49|os:iOS-15.1|pool:default|python:3.8.10+chromium.23|ssd:1|zone:us-corp-mtv'
125 2022-05-12 13:02:08.952 I: get_authentication_headers(): 0s
125 2022-05-12 13:02:08.952 I: Fetched auth headers (dict_keys(['X-Luci-Machine-Token'])), they expire in 2879 sec. Next check in 2309 sec.
125 2022-05-12 13:02:08.952 I: Got auth headers: dict_keys(['X-Luci-Machine-Token'])
125 2022-05-12 13:02:08.957 I: Removing file /Users/swarming/Library/Application Support/CrashReporter/Intervals_5E5FEDF7-17A1-5503-B5B5-D04D195828CE.plist
125 2022-05-12 13:02:08.958 I: ts_mon hook_name='on_bot_startup' pool='cores:8|cpu:arm-64|cpu:arm64-64-Apple_M1|device:iPhone8,1|display_attached:1|gce:0|gpu:none|mac_model:Macmini9,1|machine_type:n1-highcpu-8|os:Mac-12.2-21D49|os:iOS-15.1|pool:default|python:3.8.10+chromium.23|ssd:1|zone:us-corp-mtv'
125 2022-05-12 13:02:08.958 I: on_bot_startup(): 0.005s
125 2022-05-12 13:02:09.492 I: ts_mon hook_name='get_dimensions' pool='cores:8|cpu:arm-64|cpu:arm64-64-Apple_M1|device:iPhone8,1|display_attached:1|gce:0|gpu:none|mac_model:Macmini9,1|machine_type:n1-highcpu-8|os:Mac-12.2-21D49|os:iOS-15.1|pool:default|python:3.8.10+chromium.23|ssd:1|zone:us-corp-mtv'
125 2022-05-12 13:02:09.493 I: get_dimensions(): 0.533s
125 2022-05-12 13:02:09.772 I: [mmutex] Not reporting state as maintenance
125 2022-05-12 13:02:09.772 I: ts_mon hook_name='get_state' pool='cores:8|cpu:arm-64|cpu:arm64-64-Apple_M1|device:iPhone8,1|display_attached:1|gce:0|gpu:none|mac_model:Macmini9,1|machine_type:n1-highcpu-8|os:Mac-12.2-21D49|os:iOS-15.1|pool:default|python:3.8.10+chromium.23|ssd:1|zone:us-corp-mtv'
125 2022-05-12 13:02:09.772 I: get_state(): 0.279s
125 2022-05-12 13:02:09.773 I: ts_mon hook_name='get_settings' pool='cores:8|cpu:arm-64|cpu:arm64-64-Apple_M1|device:iPhone8,1|display_attached:1|gce:0|gpu:none|mac_model:Macmini9,1|machine_type:n1-highcpu-8|os:Mac-12.2-21D49|os:iOS-15.1|pool:default|python:3.8.10+chromium.23|ssd:1|zone:us-corp-mtv'
125 2022-05-12 13:02:09.773 I: get_settings(): 0s
125 2022-05-12 13:02:09.773 I: Calling /swarming/api/v1/bot/handshake
125 2022-05-12 13:02:09.773 D: GOOGAPPUID = sha1(2022-05-12-flutter-devicelab-mac-41:/opt/s) % 1000 = 3
125 2022-05-12 13:02:10.250 D: https://chromium-swarm.appspot.com:443 "POST /swarming/api/v1/bot/handshake HTTP/1.1" 200 None
125 2022-05-12 13:02:10.251 D: Request https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake succeeded
125 2022-05-12 13:02:10.251 I: Connected to 6584-3940133
125 2022-05-12 13:02:10.251 W: Found out we'll need to update: server said d29ebf4ace222f61bf52ac83cc2c8d2c43d2895e25ee937312c8e28fcdbe5581; we're 8d6f0c4722297cda8a97768f583c37ef42a36c37a10e49b73df1b343e412ecc5
125 2022-05-12 13:02:10.253 D: extra bot_config flutter_ios.py at rev  was injected.
125 2022-05-12 13:02:10.254 I: ts_mon hook_name='on_handshake' pool='bot_config:flutter_ios.py|cores:8|cpu:arm-64|cpu:arm64-64-Apple_M1|device:iPhone8,1|display_attached:1|gce:0|gpu:none|mac_model:Macmini9,1|machine_type:n1-highcpu-8|os:Mac-12.2-21D49|os:iOS-15.1|pool:luci.flutter.prod|python:3.8.10+chromium.23|ssd:1|zone:us-corp-mtv'
125 2022-05-12 13:02:10.254 I: on_handshake(): 0s
125 2022-05-12 13:02:10.264 I: ts_mon hook_name='get_settings' pool='bot_config:flutter_ios.py|cores:8|cpu:arm-64|cpu:arm64-64-Apple_M1|device:iPhone8,1|display_attached:1|gce:0|gpu:none|mac_model:Macmini9,1|machine_type:n1-highcpu-8|os:Mac-12.2-21D49|os:iOS-15.1|pool:luci.flutter.prod|python:3.8.10+chromium.23|ssd:1|zone:us-corp-mtv'
125 2022-05-12 13:02:10.264 I: get_settings(): 0.006s
125 2022-05-12 13:02:10.270 I: size 948584, partition {'size': 214748364800, 'min_percent': 7.0, 'wiggle': 262144000, 'max_percent': 50.0}, min_free 215010508800
125 2022-05-12 13:02:10.271 I: Running: ['/Users/swarming/.vpython-root/b468f2/bin/python', '/opt/s/swarming_bot.1.zip', 'run_isolated', '--clean', '--log-file', '/opt/s/logs/run_isolated.log', '--min-free-space', '215010508800', '--max-cache-size', '53687091200', '--cas-cache', '/opt/s/cas_cache', '--named-cache-root', '/opt/s/c', '--kvs-dir', '/opt/s/cas_kvs_cache_db']
125 2022-05-12 13:02:10.717 I: Result:
b''
```

**Comment by yusuf-goog** [comment]
Looks like there might be some issue with the singleton code, it should have written the pid of the locking process into the file. Also, probably add a bigger sleep before restarting the machine, so it doesn't go into a loop.

Singleton "/opt/s/swarming.lck" is held by "b''"

**Comment by yusuf-goog** [comment]
Let me take a look. It was recovered before. We need to figure out if its still the lockfile issue and why the swarming process is not letting go of the lock.

**Comment by yusuf-goog** [comment]
The original issue with mac-41 was that it was in a bootloop. #103910 is a different issue now. 

The bot is running, so closing this issue. The failing jobs will be investigated in its own bug.
