### ISSUE TITLE
Unexpected Closing Flutter Docotor 

### ISSUE THREAD

**Issue by AstroProgrammer** [flutter/flutter#10367]
## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /home/naveen/Android/Sdk/platform-tools/adb.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:86)
#2      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:286)
#3      runSync (package:flutter_tools/src/base/process.dart:261)
#4      getAdbDevices (package:flutter_tools/src/android/android_device.dart:527)
#5      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:40)
#6      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:132)
#7      DeviceManager.getAllConnectedDevices.<anonymous closure> (package:flutter_tools/src/device.dart:88)
#8      ExpandIterator.moveNext (dart:_internal/iterable.dart:480)
#9      _IterablePendingEvents.handleNext (dart:async/stream_impl.dart:528)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for /home/naveen/Android/Sdk/platform-tools/adb.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:86)
#2      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:286)
#3      runSync (package:flutter_tools/src/base/process.dart:261)
#4      getAdbDevices (package:flutter_tools/src/android/android_device.dart:527)
#5      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:40)
#6      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:132)
#7      DeviceManager.getAllConnectedDevices.<anonymous closure> (package:flutter_tools/src/device.dart:88)
#8      ExpandIterator.moveNext (dart:_internal/iterable.dart:480)
#9      _IterablePendingEvents.handleNext (dart:async/stream_impl.dart:528)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by eseidelGoogle** [comment]
I wouldn't expect `flutter doctor` to crash.  @tvolkert would know.

**Comment by cbracken** [comment]
@AstroProgrammer is there any output from `flutter doctor` above the stack trace (e.g. some version info)? 

Is output any better if you run `flutter upgrade` then re-run `flutter doctor`?

**Comment by tvolkert** [comment]
@AstroProgrammer in addition to trying the upgrade that @cbracken listed, can you also paste the output of running `flutter doctor -v`?
