### ISSUE TITLE
Error: Couldn't resolve the package 'jaguar_serializer' in 'package:jaguar_serializer/jaguar_serializer.dart'. Upgrading 3.0 fails to build app

### ISSUE THREAD

**Issue by zhao004** [flutter/flutter#103679]
# Error content

```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on MI 8 in debug mode...
Running Gradle task 'assembleDebug'...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Invalid depfile: I:\Flutter\FlutterProject\untitled3\.dart_tool\flutter_build\69d1d97bc7733e0d6873449d0aed52eb\kernel_snapshot.d
Invalid depfile: I:\Flutter\FlutterProject\untitled3\.dart_tool\flutter_build\69d1d97bc7733e0d6873449d0aed52eb\kernel_snapshot.d
Error: Couldn't resolve the package 'jaguar_serializer' in 'package:jaguar_serializer/jaguar_serializer.dart'.
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:12:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'dart:ui' as ui show Image, ImageFilter, TextHeightBehavior;
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:14:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'package:flutter/animation.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:15:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'package:flutter/foundation.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:16:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'package:flutter/gestures.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:17:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'package:flutter/rendering.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:18:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'package:flutter/services.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:20:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'binding.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:21:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'debug.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:22:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'framework.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:23:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'localizations.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:24:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'widget_span.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:26:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/animation.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:27:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/foundation.dart' show
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:33:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/painting.dart';
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:34:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/rendering.dart' show
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:77:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/services.dart' show
^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:1:8: Error: Not found: 'package:jaguar_serializer/jaguar_serializer.dart'
import 'package:jaguar_serializer/jaguar_serializer.dart';
       ^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:3:6: Error: Error when reading '/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.jser.dart': 系统找不到指定的文件�?

part 'basic.jser.dart';
     ^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:3:6: Error: Can't use '/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.jser.dart' as a part, because it has no 'part of' declaration.
part 'basic.jser.dart';
     ^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:6:47: Error: Type 'TestWidget' not found.
class TestWidgetSerializer extends Serializer<TestWidget> with _$TestWidgetSerializer{}
                                              ^^^^^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:6:36: Error: Type 'Serializer' not found.
class TestWidgetSerializer extends Serializer<TestWidget> with _$TestWidgetSerializer{}
                                   ^^^^^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:6:64: Error: Type '_$TestWidgetSerializer' not found.
class TestWidgetSerializer extends Serializer<TestWidget> with _$TestWidgetSerializer{}
                                                               ^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:6:7: Error: The type '_$TestWidgetSerializer' can't be mixed in.
class TestWidgetSerializer extends Serializer<TestWidget> with _$TestWidgetSerializer{}
      ^
/D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart:5:2: Error: Couldn't find constructor 'GenSerializer'.
@GenSerializer()
 ^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Ajaguar_serializer%2Fjaguar_serializer.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:652:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:792:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:615:9)
<asynchronous suspension>
#4      starter (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:1433:12)
<asynchronous suspension>
#5      main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
<asynchronous suspension>



FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter_sdk\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter_sdk\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1
```
<h1>flutter doctor</h1>
```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本 10.0.19043.1706],
    locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version        
    32.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.13) 
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```
<h1>flutter --version</h1>
```
• No issues found!
I:\Flutter\FlutterProject\untitled3>flutter --version
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (3 days ago) • 2022-05-09 16:45:18 -0700        
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2
```
<h1>Code screenshot, the official counter example I use</h1>
![20220513134415](https://user-images.githubusercontent.com/82579833/168218974-bd473e08-4806-446b-adcb-525ad366dc18.png)

<h1>Unable to build app.</h1>

**Comment by pradeep14598** [comment]
Try flutter pub cache clean and flutter pub get

**Comment by Hixie** [comment]
Before you do that, can you paste the top 20 lines of `D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart` here?

**Comment by zhao004** [comment]
> Try flutter pub cache clean and flutter pub get
Useless.
![20220513172028](https://user-images.githubusercontent.com/82579833/168253230-4f830347-3a47-4f78-80bb-86d22e8302a3.png)

**Comment by zhao004** [comment]
> Before you do that, can you paste the top 20 lines of `D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart` here?

what?

**Comment by zhao004** [comment]
> D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart
![20220513172439](https://user-images.githubusercontent.com/82579833/168253965-ae3c6e3f-ce0d-4edd-972f-e796630e6269.png)

**Comment by darshankawar** [comment]
Keeping it open and labeling for further investigation.

**Comment by mraleph** [comment]
From the screenshot it is pretty clear that Flutter SDK source is damaged, looks like you have accidentally pasted some random code into `D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart`. 

Check if you have any intentional edits by doing `git status` in `D:\flutter_sdk`. If you don't have any (i.e. you did not intend to edit Flutter SDK), then just purge all local changes by doing `git reset --hard`.

**Comment by zhao004** [comment]
> From the screenshot it is pretty clear that Flutter SDK source is damaged, looks like you have accidentally pasted some random code into `D:/flutter_sdk/packages/flutter/lib/src/widgets/basic.dart`.
> 
> Check if you have any intentional edits by doing `git status` in `D:\flutter_sdk`. If you don't have any (i.e. you did not intend to edit Flutter SDK), then just purge all local changes by doing `git reset --hard`.
> 
> @Hixie Flutter tool should probably detect and warn about dirty source tree in `flutter doctor`.
<h3>I deleted the original fluttersdk, downloaded a new fluttersdk, and then I can use it.</h3>
