### ISSUE TITLE
webview throw exception    java.lang.Integer cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by Tonigt** [flutter/flutter#103676]
E/MethodChannel#flutter/platform_views(23226): Failed to handle method call
E/MethodChannel#flutter/platform_views(23226): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Map
E/MethodChannel#flutter/platform_views(23226): 	at com.wzm.webviewflutter.WebViewFactory.create(WebViewFactory.java:29)
E/MethodChannel#flutter/platform_views(23226): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:152)
E/MethodChannel#flutter/platform_views(23226): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views(23226): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views(23226): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views(23226): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#flutter/platform_views(23226): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#flutter/platform_views(23226): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(23226): 	at android.os.Handler.handleCallback(Handler.java:900)
E/MethodChannel#flutter/platform_views(23226): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/MethodChannel#flutter/platform_views(23226): 	at android.os.Looper.loop(Looper.java:219)
E/MethodChannel#flutter/platform_views(23226): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/MethodChannel#flutter/platform_views(23226): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(23226): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#flutter/platform_views(23226): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

the code is:

var text = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *{
            padding:0;
            margin:0;
            font-size: 14px;
        }
        body{
            padding:20px;
        }
        .ue-table-interlace-color-single{
            background-color: #fcfcfc;
        }
        .ue-table-interlace-color-double {
            background-color: #f7faff;
        }
        table{
            border-collapse: collapse;
        }
        td, th {
            font-size: 14px;
            padding: 5px 10px;
            border: 1px solid #DDD;
        }
    </style>
</head>
<body>
    <div style="white-space: normal;letter-spacing:2px">
        <span style="font-size:16px;font-weight: 700">
        </span> 
        </div>
</body>
</html>
""";

WebView(
        javascriptChannels: Set<JavascriptChannel>(),
        initialUrl: "https://www.baidu.com",
        onWebViewCreated: (controller) async{
          final String contentBase64 = base64Encode(const Utf8Encoder().convert(text));
          await controller.loadUrl('data:text/html;base64,$contentBase64');
          // controller.loadHtmlString(text);
        },
        javascriptMode: JavascriptMode.unrestricted,
        allowsInlineMediaPlayback: false
      )

**Comment by Tonigt** [comment]
just my fault
