### ISSUE TITLE
Release Web "TypeError: Instance of 'minified:c7': type 'minified:c7' is not a subtype of type 'minified:eN'"

### ISSUE THREAD

**Issue by gisborne** [flutter/flutter#103654]
## Steps to Reproduce

Run https://github.com/gisborne/resume (94bd6c19d2d92223e4347af2b8e4065b8900386b) for web locally. Click "Software Design" and then click on the expand arrows. Everything fine.

Build release. Try again. Note that the expanded text is now a grey block. Check console and see the error "TypeError: Instance of 'minified:c7': type 'minified:c7' is not a subtype of type 'minified:eN"

**Expected results:**

Release version should work without fresh bugs.

**Actual results:**

Bug only in release version.

```dart
```

<details>
  <summary>Logs</summary>
Here is the error from release mode in Chrome:

```
TypeError: Instance of 'minified:bT': type 'minified:bT' is not a subtype of type 'minified:eo'
main.dart.js:18750     at Object.c (https://gisborne.github.io/main.dart.js:2492:3)
main.dart.js:18750     at Object.akP (https://gisborne.github.io/main.dart.js:3076:18)
main.dart.js:18750     at hl.axe [as a] (https://gisborne.github.io/main.dart.js:3071:3)
main.dart.js:18750     at Eh.nM (https://gisborne.github.io/main.dart.js:50838:6)
main.dart.js:18750     at xB.rb (https://gisborne.github.io/main.dart.js:54263:11)
main.dart.js:18750     at xB.dZ (https://gisborne.github.io/main.dart.js:54182:3)
main.dart.js:18750     at xB.dZ (https://gisborne.github.io/main.dart.js:54290:3)
main.dart.js:18750     at mG.t9 (https://gisborne.github.io/main.dart.js:53947:3)
main.dart.js:18750     at mG.cw (https://gisborne.github.io/main.dart.js:53901:16)
main.dart.js:18750     at mG.hk (https://gisborne.github.io/main.dart.js:54069:32)
```

As the problem only occurs in release mode, I'm not sure how helpful this is (although there _is_ a different error, that doesn't affect the app that I can see (shortened because too long for github):

```
[  +46 ms] executing: sysctl hw.optional.arm64
[   +9 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[   +3 ms] executing: [/Users/gisborne/dev/bin/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +17 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] executing: [/Users/gisborne/dev/bin/flutter/] git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[  +95 ms] Exit code 0 from: git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] 3.0.0
[   +4 ms] executing: [/Users/gisborne/dev/bin/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/gisborne/dev/bin/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +52 ms] executing: [/Users/gisborne/dev/bin/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +3 ms] executing: sw_vers -productName
[  +12 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +10 ms] Exit code 0 from: sw_vers -productVersion
[        ] 12.3.1
[        ] executing: sw_vers -buildVersion
[  +10 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 21E258
[        ] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] arm64
[  +21 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
… more like this…
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +13 ms] executing: sysctl hw.optional.arm64
[   +2 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -version
[ +755 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun xcodebuild -version
[   +1 ms] Xcode 13.3.1
           Build version 13E500a
[        ] objc[94015]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1eeca9eb0) and
/Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e384f8). One of the two will be used. Which one is
undefined.
           objc[94015]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1eeca9f00) and
           /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e38548). One of the two will be used.
           Which one is undefined.
           objc[94015]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1eeca9f50) and
           /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e38598). One of the two will be used.
           Which one is undefined.
           objc[94015]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1eeca9fa0) and
           /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e385e8). One of the two will be used.
           Which one is undefined.
           objc[94015]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1eeca9ff0) and
           /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e38638). One of the two will be used.
           Which one is undefined.
           objc[94015]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1eecaa040) and
           /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e38688). One of the two will be used.
           Which one is undefined.
[  +31 ms] Skipping pub get: version match.
[  +20 ms] Found plugin device_info_plus at /Users/gisborne/.pub-cache/hosted/pub.dartlang.org/device_info_plus-3.2.2/
[   +3 ms] Found plugin device_info_plus_linux at /Users/gisborne/.pub-cache/hosted/pub.dartlang.org/device_info_plus_linux-2.1.1/
[   +1 ms] Found plugin device_info_plus_macos at /Users/gisborne/.pub-cache/hosted/pub.dartlang.org/device_info_plus_macos-2.2.2/
[   +1 ms] Found plugin device_info_plus_web at /Users/gisborne/.pub-cache/hosted/pub.dartlang.org/device_info_plus_web-2.1.0/
… more like this…
[        ] Found plugin url_launcher_windows at /Users/gisborne/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.0/
[  +45 ms] <- reset
[   +4 ms] /Users/gisborne/dev/bin/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/gisborne/dev/bin/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/Users/gisborne/dev/bin/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /var/folders/6f/g8mlsykn1vg85svt2149pzpr0000gp/T/flutter_tools.ImkzjE/flutter_tool.KmHx9f/app.dill
--libraries-spec file:///Users/gisborne/dev/bin/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/Users/gisborne/Documents/03-work/resume/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root /var/folders/6f/g8mlsykn1vg85svt2149pzpr0000gp/T/flutter_tools.ImkzjE/flutter_tools.MbuxJZ
--filesystem-scheme org-dartlang-app --initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///Users/gisborne/dev/bin/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+12251 ms] Waiting for connection from debug service on Chrome... (completed in 12.3s)
[   +1 ms] Synced 38.7MB.
[        ] <- accept
[        ] Caching compiled dill
[  +87 ms] Using Google Chrome 101.0.4951.64 

[  +91 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[   +9 ms] Found ARM Chrome installation at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome, forcing native launch.
[ +516 ms] [CHROME]: 
[   +1 ms] [CHROME]: DevTools listening on ws://127.0.0.1:62131/devtools/browser/e319d6e2-7082-48e4-ae17-7afcb0856eef
[+1393 ms] DwdsInjector: Received request for entrypoint at http://localhost:61897/main_module.bootstrap.js
[   +8 ms] MetadataProvider: Loading debug metadata...
[   +7 ms] MetadataProvider: Loaded debug metadata for module: web_entrypoint.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/resume/generated_plugin_registrant.dart
… more like this…
[        ] MetadataProvider: Loaded debug metadata (sound null safety)
[  +12 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:61897/main_module.bootstrap.js
[+1909 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +40 ms] DevHandler: Debug service listening on ws://127.0.0.1:62172/ivEG4wwZG-E=/ws

[   +9 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 9, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 9,
           params: {streamId: Stdout, includePrivateMembers: false}}}}
[   +2 ms] This app is linked to the debug service: ws://127.0.0.1:62172/ivEG4wwZG-E=/ws
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 10, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           10, params: {streamId: Stderr, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 11, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           11, params: {streamId: Isolate, includePrivateMembers: false}}}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 12, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           12, params: {streamId: Extension, includePrivateMembers: false}}}}
[   +2 ms] Debug service listening on ws://127.0.0.1:62172/ivEG4wwZG-E=/ws
[        ] 💪 Running with sound null safety 💪
[   +1 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[        ] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:62172/ivEG4wwZG-E=
[  +14 ms] Flutter Web Bootstrap: Auto
[+1364 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:62172/ivEG4wwZG-E=
[+3395 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] The following assertion was thrown while applying parent data.:
[        ] Incorrect use of ParentDataWidget.
[        ] The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a
[        ] RenderObject, which has been set up to accept ParentData of incompatible type ParentData.
[        ] Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically,
[        ] Expanded widgets are placed directly inside Flex widgets.
[        ] The offending Expanded is currently placed inside a FadeTransition widget.
[        ] The ownership chain for the RenderObject that received the incompatible parent data was:
[        ]   Padding ← Expanded ← FadeTransition ← _FocusMarker ← Focus ← ExcludeFocus ← ExcludeSemantics ←
[        ] IgnorePointer ← _EffectiveTickerMode ← TickerMode-[<CrossFadeState.showFirst>] ← ⋯
[        ] When the exception was thrown, this was the stack:
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
[        ] packages/flutter/src/widgets/framework.dart 5960:11                           <fn>
[  +13 ms] packages/flutter/src/widgets/framework.dart 5976:14                           [_updateParentData]
[        ] packages/flutter/src/widgets/framework.dart 5999:82                           attachRenderObject
[        ] packages/flutter/src/widgets/framework.dart 5673:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 6214:11                           mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4787:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4781:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 6215:14                           mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4787:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4781:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4977:11                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4787:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4968:11                           [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4781:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4787:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4781:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 6215:14                           mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 6215:14                           mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4787:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4781:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4977:11                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4787:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4968:11                           [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4781:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[   +7 ms] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4787:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4781:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 6350:36                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 6362:32                           mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 6215:14                           mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4977:11                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4787:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4968:11                           [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4781:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 6215:14                           mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3551:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4977:11                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4787:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4968:11                           [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4781:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3817:15                           inflateWidget
[   +5 ms] packages/flutter/src/widgets/framework.dart 3545:20                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 5154:5                            update
[        ] packages/flutter/src/widgets/framework.dart 3530:14                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 5825:32                           updateChildren
[        ] packages/flutter/src/widgets/framework.dart 6375:17                           update
[        ] packages/flutter/src/widgets/framework.dart 3530:14                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4832:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4977:11                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4529:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 2659:18                           buildScope
[        ] packages/flutter/src/widgets/binding.dart 891:9                               drawFrame
[   +1 ms] packages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]
[        ] packages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]
[        ] packages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame
[        ] packages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]
[        ] lib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke
[        ] lib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame
[        ] lib/_engine/engine/initialization.dart 194:45                                 <fn>
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +14 ms] Another exception was thrown: Incorrect use of ParentDataWidget.

```

```
% flutter analyze
Analyzing resume...                                                     

   info • Don't import implementation files from another package • lib/generated_plugin_registrant.dart:11:8 • implementation_imports
   info • Use key in widget constructors • lib/macos/about.dart:5:7 • use_key_in_widget_constructors
   info • Prefer const with constant constructors • lib/macos/about.dart:29:24 • prefer_const_constructors
   info • Use key in widget constructors • lib/macos/design.dart:7:7 • use_key_in_widget_constructors
   info • 'isAlwaysShown' is deprecated and shouldn't be used. Use thumbVisibility instead. This feature was deprecated after v2.9.0-1.0.pre. •
          lib/macos/design.dart:21:7 • deprecated_member_use
   info • Use key in widget constructors • lib/macos/link_card.dart:10:3 • use_key_in_widget_constructors
   info • 'isAlwaysShown' is deprecated and shouldn't be used. Use thumbVisibility instead. This feature was deprecated after v2.9.0-1.0.pre. •
          lib/macos/link_card_list.dart:25:7 • deprecated_member_use
   info • Use key in widget constructors • lib/macos/narrow.dart:8:7 • use_key_in_widget_constructors
   info • Prefer const with constant constructors • lib/macos/narrow.dart:28:25 • prefer_const_constructors
   info • Use key in widget constructors • lib/macos/pdf_widget.dart:8:3 • use_key_in_widget_constructors
   info • Use key in widget constructors • lib/macos/presentations.dart:6:7 • use_key_in_widget_constructors
   info • Use key in widget constructors • lib/macos/resume.dart:5:7 • use_key_in_widget_constructors
   info • Prefer const with constant constructors • lib/macos/selected_tile.dart:14:29 • prefer_const_constructors
   info • Prefer declaring const constructors on `@immutable` classes • lib/macos/side_menu.dart:11:3 • prefer_const_constructors_in_immutables
   info • Don't put any logic in createState • lib/macos/side_menu.dart:21:42 • no_logic_in_create_state
   info • The operand can't be null, so the condition is always false • lib/macos/side_menu.dart:37:13 • unnecessary_null_comparison
   info • Use key in widget constructors • lib/macos/wide.dart:6:7 • use_key_in_widget_constructors
   info • SizedBox for whitespace • lib/macos/wide.dart:17:11 • sized_box_for_whitespace
   info • Use key in widget constructors • lib/macos/writing.dart:9:7 • use_key_in_widget_constructors
   info • Use key in widget constructors • lib/macos_main.dart:15:7 • use_key_in_widget_constructors
   info • Use key in widget constructors • lib/main.dart:15:7 • use_key_in_widget_constructors
   info • Use key in widget constructors • lib/shared/root.dart:8:7 • use_key_in_widget_constructors
   info • Avoid using web-only libraries outside Flutter web plugin packages • lib/web/iframe.dart:4:1 • avoid_web_libraries_in_flutter
   info • Use key in widget constructors • lib/web/iframe.dart:9:3 • use_key_in_widget_constructors

```

```
% flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /Users/gisborne/dev/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gisborne/Library/Android/sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Volumes/Backup/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/gisborne/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 66.0.4
    • Dart plugin version 221.5177

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

Bug:
![image](https://user-images.githubusercontent.com/28639/168162472-0adf9a5a-125f-4ee9-8f80-cb0b46a197cf.png)
Correct behavior:
![image](https://user-images.githubusercontent.com/28639/168162969-1f9ed285-b8f2-4250-9793-aff3d340ec82.png)

**Comment by gisborne** [comment]
Turned out I had a "Incorrect use of parentData" error I'd introduced at the last minute.

The desktop version worked fine in spite, so I was confused when the web version didn't.

Not a great failure mode.

Might still be worth a quick look at the checkout I tagged here.

**Comment by darshankawar** [comment]
@gisborne 
Please check [this](https://github.com/flutter/flutter/issues/78041) similar issue and see underlying comments in it helps in your case.
Thanks.
