### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by agusprayogi02** [flutter/flutter#103693]
## Command
```
flutter --quiet assemble --no-version-check --depfile /media/agus/SSD1/ProjectKu/Flutter/kmipn/sistor/build/app/intermediates/flutter/debug/flutter_build.d --output /media/agus/SSD1/ProjectKu/Flutter/kmipn/sistor/build/app/intermediates/flutter/debug -dTargetFile=/media/agus/SSD1/ProjectKu/Flutter/kmipn/sistor/lib/main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#6      SourceVisitor.visitDepfile (package:flutter_tools/src/build_system/source.dart:55:37)
#7      List.forEach (dart:core-patch/growable_array.dart:416:8)
#8      Target._resolveConfiguration (package:flutter_tools/src/build_system/build_system.dart:249:14)
#9      Target.resolveInputs (package:flutter_tools/src/build_system/build_system.dart:194:12)
#10     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:147:39)
#11     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:154:58)
#12     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:30)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:320:51)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1342:12)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 3.0.0, on Ubuntu 22.04 LTS 5.15.0-27-generic, locale en_US.UTF-8)
    • Flutter version 3.0.0 at /media/agus/SSD2/src/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /media/agus/SSD2/LINUX_AND_SDK
    • Platform android-Tiramisu, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /media/agus/SSD2/LINUX_AND_SDK
    • Java binary at: /home/agus/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/agus/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/agus/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5080.210
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Realme 3 Phone (mobile) • 192.168.56.104:5555 • android-x86    • Android 8.1.0 (API 27)
    • Linux (desktop)         • linux               • linux-x64      • Ubuntu 22.04 LTS 5.15.0-27-generic
    • Chrome (web)            • chrome              • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ee4e09cce01d6f2d7f4baebd247fde02e5008851
### Plugins
camera_deep_ar-0.0.2+3
firebase_auth-3.3.11
firebase_auth_web-3.3.9
firebase_core-1.13.1
firebase_core_web-1.6.1
flutter_archive-5.0.0
flutter_plugin_android_lifecycle-2.0.5
geolocator-8.2.1
geolocator_android-3.1.8
geolocator_apple-2.1.3
geolocator_web-2.1.5
geolocator_windows-0.1.1
google_maps_flutter-2.1.5
google_maps_flutter_web-0.3.2+1
google_sign_in-5.2.4
google_sign_in_web-0.10.0+5
image_picker-0.8.5+1
image_picker_android-0.8.4+11
image_picker_for_web-2.1.6
image_picker_ios-0.8.5
path_provider-2.0.9
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
permission_handler-8.3.0
workmanager-0.5.0-dev.8

**Comment by agusprayogi02** [comment]
> ## Command
> ```
> flutter --quiet assemble --no-version-check --depfile /media/agus/SSD1/ProjectKu/Flutter/kmipn/sistor/build/app/intermediates/flutter/debug/flutter_build.d --output /media/agus/SSD1/ProjectKu/Flutter/kmipn/sistor/build/app/intermediates/flutter/debug -dTargetFile=/media/agus/SSD1/ProjectKu/Flutter/kmipn/sistor/lib/main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
> ```
> 
> ## Steps to Reproduce
> 1. ...
> 2. ...
> 3. ...
> 
> ## Logs
> FileSystemException: Failed to decode data using encoding 'utf-8', null
> 
> ```
> #0      _File._tryDecode (dart:io/file_impl.dart:564:7)
> #1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
> #2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
> #3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
> #4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
> #5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
> #6      SourceVisitor.visitDepfile (package:flutter_tools/src/build_system/source.dart:55:37)
> #7      List.forEach (dart:core-patch/growable_array.dart:416:8)
> #8      Target._resolveConfiguration (package:flutter_tools/src/build_system/build_system.dart:249:14)
> #9      Target.resolveInputs (package:flutter_tools/src/build_system/build_system.dart:194:12)
> #10     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:147:39)
> #11     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:154:58)
> #12     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:30)
> #13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:320:51)
> #14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1342:12)
> <asynchronous suspension>
> #15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
> <asynchronous suspension>
> #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> <asynchronous suspension>
> #17     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
> <asynchronous suspension>
> #18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
> <asynchronous suspension>
> #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> ```
> 
> ```
> [✓] Flutter (Channel stable, 3.0.0, on Ubuntu 22.04 LTS 5.15.0-27-generic, locale en_US.UTF-8)
>     • Flutter version 3.0.0 at /media/agus/SSD2/src/flutter
>     • Upstream repository https://github.com/flutter/flutter
>     • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
>     • Engine revision d1b9a6938a
>     • Dart version 2.17.0
>     • DevTools version 2.12.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
>     • Android SDK at /media/agus/SSD2/LINUX_AND_SDK
>     • Platform android-Tiramisu, build-tools 32.0.0
>     • ANDROID_SDK_ROOT = /media/agus/SSD2/LINUX_AND_SDK
>     • Java binary at: /home/agus/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at google-chrome
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • Ubuntu clang version 14.0.0-1ubuntu1
>     • cmake version 3.22.1
>     • ninja version 1.10.1
>     • pkg-config version 0.29.2
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at /home/agus/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546
>     • Flutter plugin version 67.1.2
>     • Dart plugin version 212.5744
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
>     • IntelliJ at /home/agus/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5080.210
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
> [✓] VS Code (version 1.67.1)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.32.0
> 
> [✓] Connected device (3 available)
>     • Realme 3 Phone (mobile) • 192.168.56.104:5555 • android-x86    • Android 8.1.0 (API 27)
>     • Linux (desktop)         • linux               • linux-x64      • Ubuntu 22.04 LTS 5.15.0-27-generic
>     • Chrome (web)            • chrome              • web-javascript • Google Chrome 101.0.4951.64
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
> ```
> 
> ## Flutter Application Metadata
> **Type**: app **Version**: 1.0.0+1 **Material**: true **Android X**: false **Module**: false **Plugin**: false **Android package**: null **iOS bundle identifier**: null **Creation channel**: stable **Creation framework version**: [ee4e09c](https://github.com/flutter/flutter/commit/ee4e09cce01d6f2d7f4baebd247fde02e5008851)
> 
> ### Plugins
> camera_deep_ar-0.0.2+3 firebase_auth-3.3.11 firebase_auth_web-3.3.9 firebase_core-1.13.1 firebase_core_web-1.6.1 flutter_archive-5.0.0 flutter_plugin_android_lifecycle-2.0.5 geolocator-8.2.1 geolocator_android-3.1.8 geolocator_apple-2.1.3 geolocator_web-2.1.5 geolocator_windows-0.1.1 google_maps_flutter-2.1.5 google_maps_flutter_web-0.3.2+1 google_sign_in-5.2.4 google_sign_in_web-0.10.0+5 image_picker-0.8.5+1 image_picker_android-0.8.4+11 image_picker_for_web-2.1.6 image_picker_ios-0.8.5 path_provider-2.0.9 path_provider_android-2.0.12 path_provider_ios-2.0.8 path_provider_linux-2.1.5 path_provider_macos-2.0.5 path_provider_windows-2.0.5 permission_handler-8.3.0 workmanager-0.5.0-dev.8
