### ISSUE TITLE
Flutter Mac M1 - Cocoapods installed but broken

### ISSUE THREAD

**Issue by SportApps** [flutter/flutter#103863]
Hi I am using a Mac Book PRO with M1 Chip and run into the following problem when I want to run my project:

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-ES)
    • Flutter version 2.10.5 at /Users/timknogel/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/timknogel/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/timknogel/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.64
    ! Device 247c764ccf0d7ece is not authorized.
      You might need to check your device for an authorization dialog.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

```
timknogel@Tims-MacBook-Pro ios % pod env
objc[30757]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x2119bdeb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1080504f8). One of the two will be used. Which one is undefined.
objc[30757]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x2119bdf00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108050548). One of the two will be used. Which one is undefined.
objc[30757]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x2119bdf50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108050598). One of the two will be used. Which one is undefined.
objc[30757]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x2119bdfa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1080505e8). One of the two will be used. Which one is undefined.
objc[30757]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x2119bdff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108050638). One of the two will be used. Which one is undefined.
objc[30757]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x2119be040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108050688). One of the two will be used. Which one is undefined.

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.3.1 (21E258)
       Xcode : 13.3.1 (13E500a)
         Git : git version 2.36.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 4efe6b3ea1f9c308556b47165ab4960da62c8258

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'


# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

```
 git --version
git version 2.36.0

```

Does anybody know a fix?

**Comment by truonghoangnguyen** [comment]
This guide saved me: https://stackoverflow.com/a/69626078/19124420

**Comment by SportApps** [comment]
> This guide saved me: https://stackoverflow.com/a/69626078/19124420

Thank you for your answer. 

After implementing all steps, I get this notification when I update pods:

Pod installation complete! There are 20 dependencies from the Podfile and 50 total pods installed.

```
[!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```
Is that normal and to be ignored or an error?


The new flutter doctor -v looks good.

```
timknogel@Tims-MacBook-Pro ios % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-ES)
    • Flutter version 2.10.5 at /Users/timknogel/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/timknogel/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/timknogel/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
**But the project will still not run on IOS**


```
Here an extract of flutter run --verbose

   objc[35521]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both
                    /usr/lib/libauthinstall.dylib (0x2119bdeb0) and
                    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
                    (0x1043144f8). One of the two will be used. Which one is undefined.
                    objc[35521]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both
                    /usr/lib/libauthinstall.dylib (0x2119bdf00) and
                    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
                    (0x104314548). One of the two will be used. Which one is undefined.
                    objc[35521]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both
                    /usr/lib/libauthinstall.dylib (0x2119bdf50) and
                    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
                    (0x104314598). One of the two will be used. Which one is undefined.
                    objc[35521]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib
                    (0x2119bdfa0) and
                    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
                    (0x1043145e8). One of the two will be used. Which one is undefined.
                    objc[35521]: Class AppleTypeCRetimerFirmwareCopier is implemented in both
                    /usr/lib/libauthinstall.dylib (0x2119bdff0) and
                    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
                    (0x104314638). One of the two will be used. Which one is undefined.
                    objc[35521]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib
                    (0x2119be040) and
                    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
                    (0x104314688). One of the two will be used. Which one is undefined.
                    2022-05-16 08:13:38.509 xcodebuild[35521:447954] Requested but did not find extension point with
                    identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
                    Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
                    2022-05-16 08:13:38.510 xcodebuild[35521:447954] Requested but did not find extension point with
                    identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
                    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in
                    com.apple.dt.IDEWatchSupportCore
[+1828 ms] Found plugin add_2_calendar at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.3/
[   +5 ms] Found plugin cloud_firestore at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.1.14/
[   +1 ms] Found plugin cloud_firestore_web at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-2.6.14/
[        ] Found plugin cloud_functions at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-3.2.14/
[        ] Found plugin cloud_functions_web at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions_web-4.2.13/
[   +4 ms] Found plugin firebase_auth at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.3.17/
[   +1 ms] Found plugin firebase_auth_web at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-3.3.14/
[        ] Found plugin firebase_core at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.16.0/
[        ] Found plugin firebase_core_web at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.6.3/
[        ] Found plugin firebase_dynamic_links at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.2.2/
[        ] Found plugin firebase_messaging at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-11.3.0/
[        ] Found plugin firebase_messaging_web at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.3.0/
[        ] Found plugin firebase_storage at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-10.2.15/
[        ] Found plugin firebase_storage_web at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage_web-3.2.14/
[   +2 ms] Found plugin flutter_native_splash at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.1.6/
[        ] Found plugin flutter_plugin_android_lifecycle at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.5/
[   +1 ms] Found plugin hexcolor at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/hexcolor-2.0.7/
[   +2 ms] Found plugin image_picker at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.5+2/
[        ] Found plugin image_picker_android at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_android-0.8.4+11/
[        ] Found plugin image_picker_for_web at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.6/
[        ] Found plugin image_picker_ios at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.4+11/
[   +4 ms] Found plugin path_provider at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.9/
[        ] Found plugin path_provider_android at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.12/
[        ] Found plugin path_provider_ios at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.8/
[        ] Found plugin path_provider_linux at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.5/
[        ] Found plugin path_provider_macos at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.5/
[        ] Found plugin path_provider_windows at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.5/
[   +2 ms] Found plugin purchases_flutter at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/purchases_flutter-3.10.0/
[        ] Found plugin share at /Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/share-2.0.4/
[        ] Found plugin shared_preferences at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.15/
[        ] Found plugin shared_preferences_android at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_android-2.0.11/
[        ] Found plugin shared_preferences_ios at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.0/
[        ] Found plugin shared_preferences_linux at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.1.0/
[        ] Found plugin shared_preferences_macos at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.3/
[        ] Found plugin shared_preferences_web at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.3/
[        ] Found plugin shared_preferences_windows at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.1.0/
[   +1 ms] Found plugin sqflite at /Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.2/
[   +1 ms] Found plugin stripe_android at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_android-2.5.0/
[        ] Found plugin stripe_ios at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_ios-2.5.0/
[   +2 ms] Found plugin url_launcher at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.2/
[        ] Found plugin url_launcher_android at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.15/
[        ] Found plugin url_launcher_ios at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.15/
[        ] Found plugin url_launcher_linux at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.0/
[        ] Found plugin url_launcher_macos at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.0/
[        ] Found plugin url_launcher_web at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.9/
[        ] Found plugin url_launcher_windows at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.0/
[   +1 ms] Found plugin webview_flutter at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-3.0.4/
[        ] Found plugin webview_flutter_android at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter_android-2.8.3/
[        ] Found plugin webview_flutter_wkwebview at
/Users/timknogel/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.1/
[  +21 ms] executing: which pod
[  +35 ms] executing: pod --version
[ +656 ms] /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in
`git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
                        from
                        /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in
                        `verify_minimum_git_version!'
                        from
                        /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in
                        `run'
                        from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top
                        (required)>'
                        from /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `load'
                        from /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `<main>'
[   +2 ms] Warning: CocoaPods is installed but broken. Skipping pod install.
             You appear to have CocoaPods installed but it is not working.
             This can happen if the version of Ruby that CocoaPods was installed with is different from the one being
used to
             invoke it.
             This can usually be fixed by re-installing CocoaPods.
           To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
           
[   +8 ms] CocoaPods not installed or not in valid state.
[   +1 ms] Error launching application on iPhone SE (3rd generation).
[  +27 ms] "flutter run" took 18,791ms.
[  +17 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +103 ms] ensureAnalyticsSent: 58ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

**Comment by truonghoangnguyen** [comment]
Hi, review my terminal history end this is my all step:

```
arch -x86_64 pod install --repo-update
sudo gem uninstall cocoapods
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew --version
brew install cocoapods
pod --version
flutter doctor
```

Note: For now I still got error when run `xcodebuild -runFirstLaunch`, But my project worked well
```
code@kazus ~ % sudo xcodebuild -runFirstLaunch
Password:
objc[7724]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1ec4f1eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105f0c4f8). One of the two will be used. Which one is undefined.
...

```

**Comment by SportApps** [comment]
> 

Hey ! Thanks for your answer! 

Do you launch this from the normal terminal or from Android Studio? 

For example pod install must be launched from the IOS folder of my project right?
On the other hand CocoaPods can be launched globally from the terminal and is not project specific? 

pod version aswell only gives a result back if launched from the IOS folder of the project?

**Comment by truonghoangnguyen** [comment]
All my commands run from normal Terminal, from user root folder (not  project folder)
(and I using vscode) 
<img width="945" alt="Screen Shot 2022-05-16 at 14 58 47" src="https://user-images.githubusercontent.com/1657877/168546176-a967c868-0fda-445e-853d-eddab74622e1.png">

**Comment by SportApps** [comment]
`> arch -x86_64 pod install --repo-update`


```
timknogel@Tims-MacBook-Pro ~ % pwd
/Users/timknogel
```
The problem is when I try to run then it says:



```
timknogel@Tims-MacBook-Pro ~ % arch -x86_64 pod install --repo-update
[!] No `Podfile' found in the project directory.

```

**Comment by truonghoangnguyen** [comment]
Sorry, my mistake. 
try `arch -x86_64 pod install --repo-update` from project ios folder. 

And others from user root folder.
``` 
sudo gem uninstall cocoapods
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew --version
brew install cocoapods
pod --version
flutter doctor```

I try to search a lot so I don't remember detail. Good luck.

**Comment by SportApps** [comment]
> Sorry, my mistake. try `arch -x86_64 pod install --repo-update` from project ios folder.
> 
> And others from user root folder.
> 
> ```
> sudo gem uninstall cocoapods
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
> brew --version
> brew install cocoapods
> pod --version
> flutter doctor 
> ```
> 
> I try to search a lot so I don't remember detail. Good luck friend

Hey!!! Thank you very much for your effort but I still get the exact same error as before.

**Comment by darshankawar** [comment]
@SportApps 
I couldn't find the exact error you are reporting in your original post. Are you reporting that you are getting:

`Failed to extract git version from `git --version` ("") (RuntimeError)` or
`CocoaPods not installed or not in valid state.` ?

If it is `Failed to extract git version from git --version ("") (RuntimeError)`, then it is not a Flutter issue, but most probably a git version or somehow git is failing to extract the version properly..

If it is the latter,  does it throw same error if you try to run from command line / terminal ? or through IDE only ?

**Comment by SportApps** [comment]
> @SportApps I couldn't find the exact error you are reporting in your original post. Are you reporting that you are getting:
> 
> `Failed to extract git version from `git --version` ("") (RuntimeError)` or `CocoaPods not installed or not in valid state.` ?
> 
> If it is `Failed to extract git version from git --version ("") (RuntimeError)`, then it is not a Flutter issue, but most probably a git version or somehow git is failing to extract the version properly..
> 
> If it is the latter, does it throw same error if you try to run from command line / terminal ? or through IDE only ?

Hi darshankawar!

The error is

```
 +656 ms] /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in
`git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
                        from
                        /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in
                        `verify_minimum_git_version!'
                        from
                        /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in
                        `run'
                        from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top
                        (required)>'
                        from /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `load'
                        from /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `<main>'
[   +2 ms] Warning: CocoaPods is installed but broken. Skipping pod install.
             You appear to have CocoaPods installed but it is not working.
             This can happen if the version of Ruby that CocoaPods was installed with is different from the one being
used to
             invoke it.
             This can usually be fixed by re-installing CocoaPods.
           To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
           
[   +8 ms] CocoaPods not installed or not in valid state.
[   +1 ms] Error launching application on iPhone SE (3rd generation).
[  +27 ms] "flutter run" took 18,791ms.
```

Do you know where I can post this issue if its not flutter related? The Github Cocoapods team say it doesn't respond to them cause I can do the pod install and have a pod version. But Flutter in the end can not extract the git version....

But I have git installed as you can see.

**Comment by darshankawar** [comment]
I think your issue is same as https://github.com/CocoaPods/CocoaPods/issues/8661, so please follow-up in it for further reference.
Closing from here.
