### ISSUE TITLE
Android app crashes when using ImagePicker()

### ISSUE THREAD

**Issue by chamile** [flutter/flutter#103892]
Hi I'm getting this bug when after taking a photo from the camera and I'm using following,

``` dart
   XFile? image = await ImagePicker()
          .pickImage(source: ImageSource.camera, imageQuality: 10);
```
when capture an image and press OK app will crash and get this error message,

Followings are the configurations
![image](https://user-images.githubusercontent.com/12965257/168581688-9a1c9762-05b5-4b66-81f8-10ab8bd94cf9.png)

This not happens always but most of the time

```
I/ViewRootImpl@fe39af9[MainActivity](12604): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputTransport(12604): Input channel destroyed: 'ClientS', fd=174
I/ViewRootImpl@fe39af9[MainActivity](12604): handleAppVisibility mAppVisible=true visible=false
I/SurfaceView@4fa1c19(12604): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{4fa1c19 V.E...... ........ 0,0-1080,2256} of ViewRootImpl@fe39af9[MainActivity]
I/SurfaceView@4fa1c19(12604): pST: mTmpTransaction.apply, mTmpTransaction = android.view.SurfaceControl$Transaction@1997cdd
I/SurfaceView@4fa1c19(12604): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{4fa1c19 V.E...... ........ 0,0-1080,2256}
E/flutter (12604): [ERROR:flutter/fml/platform/android/jni_util.cc(211)] java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: 1.raster
E/flutter (12604): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1405)
E/flutter (12604): 	at io.flutter.embedding.engine.FlutterJNI.destroyOverlaySurfaces(FlutterJNI.java:1174)
E/flutter (12604):
F/flutter (12604): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1559)] Check failed: fml::jni::CheckException(env).
F/libc    (12604): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12649 (1.raster), pid 12604 (obile_wallet.qa)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/o1sxxx/o1s:12/SP1A.210812.016/G991BXXU4CVD2:user/release-keys'
Revision: '22'
ABI: 'arm64'
Processor: '0'
Timestamp: 2022-05-16 16:24:49.214714810+0530
Process uptime: 46s
Cmdline: com.cti.cti_mobile_wallet.qa
pid: 12604, tid: 12649, name: 1.raster  >>> com.cti.cti_mobile_wallet.qa <<<
uid: 10516
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1559)] Check failed: fml::jni::CheckException(env).
'
    x0  0000000000000000  x1  0000000000003169  x2  0000000000000006  x3  0000006f963fb5e0
    x4  6d602e6c716e6573  x5  6d602e6c716e6573  x6  6d602e6c716e6573  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  95e530192f7b6731  x10 0000000000000000  x11 ffffff80fffffbdf
    x12 0000000000000001  x13 000000000000007e  x14 0000000000000000  x15 0000000026762762
    x16 00000072c71a8058  x17 00000072c7185570  x18 0000006f30c32000  x19 000000000000313c
    x20 0000000000003169  x21 00000000ffffffff  x22 b40000705a4a1720  x23 b40000705a4a1708
    x24 000000000000005a  x25 0000006f963fc000  x26 0000000000000000  x27 0000000000000001
    x28 000000000000005a  x29 0000006f963fb660
    lr  00000072c7137fe4  sp  0000006f963fb5c0  pc  00000072c7138010  pst 0000000000001000
backtrace:
      #00 pc 0000000000051010  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 673fbd01d6413e96a0627f6f32291870)
      #01 pc 000000000151e73c  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #02 pc 00000000015407dc  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #03 pc 0000000001527fb4  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #04 pc 0000000001bfe618  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #05 pc 0000000001bfd374  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #06 pc 000000000185478c  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #07 pc 000000000185fbc8  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #08 pc 000000000154149c  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #09 pc 0000000001547a08  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #10 pc 0000000000016918  /system/lib64/libutils.so (android::Looper::pollInner(int)+912) (BuildId: a8e5883b039c6d018dc9ced53f79b1d0)
      #11 pc 0000000000016520  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: a8e5883b039c6d018dc9ced53f79b1d0)
      #12 pc 0000000000017160  /system/lib64/libandroid.so (ALooper_pollOnce+100) (BuildId: f44137a3e76d47c9451ac1a90d085ac1)
      #13 pc 0000000001547990  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #14 pc 00000000015413e4  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #15 pc 0000000001545290  /data/app/~~QHKqzAPih2rQl77PphD7SA==/com.cti.cti_mobile_wallet.qa-9yxHWr2-i-ax1eIpAvhC2w==/lib/arm64/libflutter.so (BuildId: 8a89f3c622e5b28e48b4b8ebd66fb3d81014ddf7)
      #16 pc 00000000000b2fd0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: 673fbd01d6413e96a0627f6f32291870)
      #17 pc 0000000000052834  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 673fbd01d6413e96a0627f6f32291870)
Lost connection to device.
```

**Comment by Paitomax** [comment]
I have the same ploblem, but I realized that error doesn't just happen when using ImagePicker, but when the app is resumed and contains PlatformViews (ad) #103870

**Comment by maheshmnj** [comment]
Hi @chamile, Thanks for filing the issue. I tried running the below code sample on Xiaomi k20 pro Android 11, and I am unable to reproduce the crash or any exception.  Also, I see that you are using an old version of a flutter on a dev channel (which no longer exists). I would suggest switching to the latest stable channel and try to reproduce the problem again. You can switch to stable channel by running

```console
flutter channel stable
flutter upgrade
```
 
<details>
<summary>code sample</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const MyHomePage(title: 'Flutter ImagePicker Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget imageBuilder(File file, int index) {
    if (file != null && file.path.isNotEmpty) {
      return Image.file(
        File(
          file.path,
        ),
        fit: BoxFit.cover,
      );
    } else {
      return imagePlaceHolder(index);
    }
  }

  Future<XFile?> pickImage(ImageSource source) async {
    final image = await _picker.pickImage(
        source: source,
        maxWidth: 800,
        maxHeight: 800,
        preferredCameraDevice: CameraDevice.rear);
    return image;
  }

  Widget imagePlaceHolder(int index) {
    return Container(
// padding: EdgeInsets.only(right),
      alignment: Alignment.center,
      decoration: BoxDecoration(
        border: Border(
            right: index % 2 == 0 ? BorderSide() : BorderSide.none,
            bottom: BorderSide()),
      ),
      child: Icon(Icons.add_a_photo),
    );
  }

  final _picker = ImagePicker();

  List<File> images = [];

  @override
  void initState() {
// TODO: implement initState
    super.initState();
    List.generate(4, (x) => images.add(File('')));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: GridView.builder(
                itemCount: 4,
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 2),
                itemBuilder: (context, index) => GestureDetector(
                    onTap: () async {
                      final image = await pickImage(index % 2 == 0
                          ? ImageSource.camera
                          : ImageSource.gallery);
                      setState(() {
                        images[index] = File(image!.path);
                      });
                    },
                    child: imageBuilder(images[index], index)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>
  
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>
