### ISSUE TITLE
DateTime millisecondsSinceEpoch inconsistency with emulator

### ISSUE THREAD

**Issue by woolfman007** [flutter/flutter#103908]
Hi all, 

first I wanted to point out that Flutter is an amazing piece of software. I've seen quite some UI frameworks during my career, but this one basically blew my mind. 

But, I encountered something strange. As far as I understand it, DateTime.millisecondsSinceEpoch must be timezone agnostic. That means, that 

            var tsu = DateTime.now().toUtc().millisecondsSinceEpoch ~/ 1000;
            var tsl = DateTime.now().toLocal().millisecondsSinceEpoch ~/ 1000;

must report the same number (unless by some coincidence, the two calls fall into different 1000s bucket, but let's forget about that for a moment). So, millisecondsSinceEpoch is a universal number, regardless on which device and from which timezone it is called. That's what the definition says: "The number of milliseconds since 1970-01-01T00:00:00Z (UTC)"

And yes, both values are the same in my tests, like one would expect. But, the result of the above code differs between my Android emulator and a real device. The real device and the browser version show the correct value as seen on https://www.unixtimestamp.com/ while the emulator is one or two hours off. I guess the emulator queries the Windows API in the end and uses local time instead of UTC by accident. 

Not a deal breaker for me (since the real device works correctly), but would be nice if it worked on the emulator, too.

**Comment by huycozy** [comment]
Hi. Thanks for filing the issue. What platform are you trying? I verified on both Android real device and emulator but I don't see the difference as yours.
Please share the output of `flutter doctor -v` to investigate this issue further.

**Comment by woolfman007** [comment]
I'm developing on Windows 11. Here's what I got:

```flutter doctor -v
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22000.675], locale de-DE)
    • Flutter version 3.0.0 at C:\Users\wschn\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (7 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\wschn\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: [
        {
          "instanceId": "991700b0",
          "installDate": "2020-11-11T10:22:07Z",
          "installationName": "VisualStudio/16.11.14+32428.217",
          "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
          "installationVersion": "16.11.32428.217",
          "productId": "Microsoft.VisualStudio.Product.Community",
          "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
          "state": 4294967295,
          "isComplete": true,
          "isLaunchable": true,
          "isPrerelease": false,
          "isRebootRequired": false,
          "displayName": "Visual Studio Community 2019",
          "description": "Leistungsstarke IDE, kostenlos f�r Studenten, Open-Source-Mitwirkende und Einzelpersonen",
          "channelId": "VisualStudio.16.Release",
          "channelUri": "https://aka.ms/vs/16/release/channel",
          "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
          "installedChannelUri": "https://aka.ms/vs/16/release/channel",
          "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.11#16.11.14",
          "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
          "updateDate": "2022-05-16T08:52:52.015515Z",
          "catalog": {
            "buildBranch": "d16.11",
            "buildVersion": "16.11.32428.217",
            "id": "VisualStudio/16.11.14+32428.217",
            "localBuild": "build-lab",
            "manifestName": "VisualStudio",
            "manifestType": "installer",
            "productDisplayVersion": "16.11.14",
            "productLine": "Dev16",
            "productLineVersion": "2019",
            "productMilestone": "RTW",
            "productMilestoneIsPreRelease": "False",
            "productName": "Visual Studio",
            "productPatchVersion": "14",
            "productPreReleaseMilestoneSuffix": "1.0",
            "productSemanticVersion": "16.11.14+32428.217",
            "requiredEngineVersion": "2.11.69.53063"
          },
          "properties": {
            "campaignId": "2034058544.1605090064",
            "channelManifestId": "VisualStudio.16.Release/16.11.14+32428.217",
            "nickname": "",
            "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
          }
        }
      ]
      . The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
      https://github.com/flutter/flutter/issues/new/choose
      The source bytes were:
      [91, 13, 10, 32, 32, 123, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 110, 99, 101, 73, 100, 34, 58, 32, 34, 57, 57, 49, 55, 48, 48, 98, 48, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 68, 97, 116, 101, 34, 58, 32, 34, 50, 48, 50, 48, 45, 49, 49, 45,
      49, 49, 84, 49, 48, 58, 50, 50, 58, 48, 55, 90, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 78, 97, 109, 101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 47, 49, 54, 46, 49, 49, 46, 49, 52, 43, 51, 50, 52,
      50, 56, 46, 50, 49, 55, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 80, 97, 116, 104, 34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 32, 40, 120, 56, 54, 41, 92, 92, 77, 105, 99, 114, 111,
      115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92, 92, 50, 48, 49, 57, 92, 92, 67, 111, 109, 109, 117, 110, 105, 116, 121, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 86, 101, 114, 115, 105, 111,
      110, 34, 58, 32, 34, 49, 54, 46, 49, 49, 46, 51, 50, 52, 50, 56, 46, 50, 49, 55, 34, 44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 73, 100, 34, 58, 32, 34, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 80,
      114, 111, 100, 117, 99, 116, 46, 67, 111, 109, 109, 117, 110, 105, 116, 121, 34, 44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 80, 97, 116, 104, 34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 32, 40, 120, 56, 54, 41, 92,
      92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92, 92, 50, 48, 49, 57, 92, 92, 67, 111, 109, 109, 117, 110, 105, 116, 121, 92, 92, 67, 111, 109, 109, 111, 110, 55, 92, 92, 73, 68, 69, 92, 92, 100, 101, 118, 101, 110, 118,
      46, 101, 120, 101, 34, 44, 13, 10, 32, 32, 32, 32, 34, 115, 116, 97, 116, 101, 34, 58, 32, 52, 50, 57, 52, 57, 54, 55, 50, 57, 53, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115, 67, 111, 109, 112, 108, 101, 116, 101, 34, 58, 32, 116, 114, 117, 101, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115,
      76, 97, 117, 110, 99, 104, 97, 98, 108, 101, 34, 58, 32, 116, 114, 117, 101, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115, 80, 114, 101, 114, 101, 108, 101, 97, 115, 101, 34, 58, 32, 102, 97, 108, 115, 101, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115, 82, 101, 98, 111, 111, 116, 82, 101, 113,
      117, 105, 114, 101, 100, 34, 58, 32, 102, 97, 108, 115, 101, 44, 13, 10, 32, 32, 32, 32, 34, 100, 105, 115, 112, 108, 97, 121, 78, 97, 109, 101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 32, 67, 111, 109, 109, 117, 110, 105, 116, 121, 32, 50, 48, 49,
      57, 34, 44, 13, 10, 32, 32, 32, 32, 34, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 34, 58, 32, 34, 76, 101, 105, 115, 116, 117, 110, 103, 115, 115, 116, 97, 114, 107, 101, 32, 73, 68, 69, 44, 32, 107, 111, 115, 116, 101, 110, 108, 111, 115, 32, 102, 129, 114, 32, 83, 116,
      117, 100, 101, 110, 116, 101, 110, 44, 32, 79, 112, 101, 110, 45, 83, 111, 117, 114, 99, 101, 45, 77, 105, 116, 119, 105, 114, 107, 101, 110, 100, 101, 32, 117, 110, 100, 32, 69, 105, 110, 122, 101, 108, 112, 101, 114, 115, 111, 110, 101, 110, 34, 44, 13, 10, 32, 32, 32, 32, 34, 99,
      104, 97, 110, 110, 101, 108, 73, 100, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 49, 54, 46, 82, 101, 108, 101, 97, 115, 101, 34, 44, 13, 10, 32, 32, 32, 32, 34, 99, 104, 97, 110, 110, 101, 108, 85, 114, 105, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58,
      47, 47, 97, 107, 97, 46, 109, 115, 47, 118, 115, 47, 49, 54, 47, 114, 101, 108, 101, 97, 115, 101, 47, 99, 104, 97, 110, 110, 101, 108, 34, 44, 13, 10, 32, 32, 32, 32, 34, 101, 110, 103, 105, 110, 101, 80, 97, 116, 104, 34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109,
      32, 70, 105, 108, 101, 115, 32, 40, 120, 56, 54, 41, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92, 92, 73, 110, 115, 116, 97, 108, 108, 101, 114, 92, 92, 114, 101, 115, 111, 117, 114, 99, 101, 115, 92, 92, 97,
      112, 112, 92, 92, 83, 101, 114, 118, 105, 99, 101, 72, 117, 98, 92, 92, 83, 101, 114, 118, 105, 99, 101, 115, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 83, 101, 116, 117, 112, 46, 83, 101, 114, 118, 105, 99, 101,
      34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 101, 100, 67, 104, 97, 110, 110, 101, 108, 85, 114, 105, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58, 47, 47, 97, 107, 97, 46, 109, 115, 47, 118, 115, 47, 49, 54, 47, 114, 101, 108, 101, 97, 115, 101, 47, 99, 104, 97,
      110, 110, 101, 108, 34, 44, 13, 10, 32, 32, 32, 32, 34, 114, 101, 108, 101, 97, 115, 101, 78, 111, 116, 101, 115, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58, 47, 47, 100, 111, 99, 115, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 101, 110, 45, 117, 115, 47,
      118, 105, 115, 117, 97, 108, 115, 116, 117, 100, 105, 111, 47, 114, 101, 108, 101, 97, 115, 101, 115, 47, 50, 48, 49, 57, 47, 114, 101, 108, 101, 97, 115, 101, 45, 110, 111, 116, 101, 115, 45, 118, 49, 54, 46, 49, 49, 35, 49, 54, 46, 49, 49, 46, 49, 52, 34, 44, 13, 10, 32, 32, 32, 32,
      34, 116, 104, 105, 114, 100, 80, 97, 114, 116, 121, 78, 111, 116, 105, 99, 101, 115, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58, 47, 47, 103, 111, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 102, 119, 108, 105, 110, 107, 47, 63, 76, 105, 110, 107, 73, 100, 61,
      54, 54, 48, 57, 48, 57, 34, 44, 13, 10, 32, 32, 32, 32, 34, 117, 112, 100, 97, 116, 101, 68, 97, 116, 101, 34, 58, 32, 34, 50, 48, 50, 50, 45, 48, 53, 45, 49, 54, 84, 48, 56, 58, 53, 50, 58, 53, 50, 46, 48, 49, 53, 53, 49, 53, 90, 34, 44, 13, 10, 32, 32, 32, 32, 34, 99, 97, 116, 97,
      108, 111, 103, 34, 58, 32, 123, 13, 10, 32, 32, 32, 32, 32, 32, 34, 98, 117, 105, 108, 100, 66, 114, 97, 110, 99, 104, 34, 58, 32, 34, 100, 49, 54, 46, 49, 49, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 98, 117, 105, 108, 100, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 54,
      46, 49, 49, 46, 51, 50, 52, 50, 56, 46, 50, 49, 55, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 105, 100, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 47, 49, 54, 46, 49, 49, 46, 49, 52, 43, 51, 50, 52, 50, 56, 46, 50, 49, 55, 34, 44, 13, 10, 32, 32, 32, 32,
      32, 32, 34, 108, 111, 99, 97, 108, 66, 117, 105, 108, 100, 34, 58, 32, 34, 98, 117, 105, 108, 100, 45, 108, 97, 98, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 109, 97, 110, 105, 102, 101, 115, 116, 78, 97, 109, 101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105,
      111, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 109, 97, 110, 105, 102, 101, 115, 116, 84, 121, 112, 101, 34, 58, 32, 34, 105, 110, 115, 116, 97, 108, 108, 101, 114, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 68, 105, 115, 112, 108, 97, 121, 86, 101,
      114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 54, 46, 49, 49, 46, 49, 52, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 76, 105, 110, 101, 34, 58, 32, 34, 68, 101, 118, 49, 54, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116,
      76, 105, 110, 101, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 50, 48, 49, 57, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 77, 105, 108, 101, 115, 116, 111, 110, 101, 34, 58, 32, 34, 82, 84, 87, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112,
      114, 111, 100, 117, 99, 116, 77, 105, 108, 101, 115, 116, 111, 110, 101, 73, 115, 80, 114, 101, 82, 101, 108, 101, 97, 115, 101, 34, 58, 32, 34, 70, 97, 108, 115, 101, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 78, 97, 109, 101, 34, 58, 32, 34, 86,
      105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 80, 97, 116, 99, 104, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 52, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99,
      116, 80, 114, 101, 82, 101, 108, 101, 97, 115, 101, 77, 105, 108, 101, 115, 116, 111, 110, 101, 83, 117, 102, 102, 105, 120, 34, 58, 32, 34, 49, 46, 48, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 83, 101, 109, 97, 110, 116, 105, 99, 86, 101, 114, 115,
      105, 111, 110, 34, 58, 32, 34, 49, 54, 46, 49, 49, 46, 49, 52, 43, 51, 50, 52, 50, 56, 46, 50, 49, 55, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 114, 101, 113, 117, 105, 114, 101, 100, 69, 110, 103, 105, 110, 101, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 50, 46, 49, 49, 46,
      54, 57, 46, 53, 51, 48, 54, 51, 34, 13, 10, 32, 32, 32, 32, 125, 44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 112, 101, 114, 116, 105, 101, 115, 34, 58, 32, 123, 13, 10, 32, 32, 32, 32, 32, 32, 34, 99, 97, 109, 112, 97, 105, 103, 110, 73, 100, 34, 58, 32, 34, 50, 48, 51, 52, 48, 53,
      56, 53, 52, 52, 46, 49, 54, 48, 53, 48, 57, 48, 48, 54, 52, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 99, 104, 97, 110, 110, 101, 108, 77, 97, 110, 105, 102, 101, 115, 116, 73, 100, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 49, 54, 46, 82, 101, 108,
      101, 97, 115, 101, 47, 49, 54, 46, 49, 49, 46, 49, 52, 43, 51, 50, 52, 50, 56, 46, 50, 49, 55, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 110, 105, 99, 107, 110, 97, 109, 101, 34, 58, 32, 34, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 115, 101, 116, 117, 112, 69, 110, 103, 105, 110,
      101, 70, 105, 108, 101, 80, 97, 116, 104, 34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 32, 40, 120, 56, 54, 41, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92, 92, 73,
      110, 115, 116, 97, 108, 108, 101, 114, 92, 92, 118, 115, 95, 105, 110, 115, 116, 97, 108, 108, 101, 114, 115, 104, 101, 108, 108, 46, 101, 120, 101, 34, 13, 10, 32, 32, 32, 32, 125, 13, 10, 32, 32, 125, 13, 10, 93, 13, 10]


    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      Utf8Decoder.convert (package:flutter_tools/src/convert.dart:54:7)
      #2      Codec.decode (dart:convert/codec.dart:26:34)
      #3      _ProcessImpl._runAndWait.getOutput (dart:io-patch/process_patch.dart:498:23)
      #4      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:506:9)
      #5      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
      #6      Process.runSync (dart:io-patch/process_patch.dart:68:12)
      #7      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:103:22)
      #8      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:712:24)
      #9      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
      #10     ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:711:12)
      #11     _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:373:51)
      #12     VisualStudio._visualStudioDetails (package:flutter_tools/src/windows/visual_studio.dart:314:51)
      #13     VisualStudio._usableVisualStudioDetails.<anonymous closure> (package:flutter_tools/src/windows/visual_studio.dart:373:33)
      #14     VisualStudio._usableVisualStudioDetails (package:flutter_tools/src/windows/visual_studio.dart:391:4)
      #15     VisualStudio._usableVisualStudioDetails (package:flutter_tools/src/windows/visual_studio.dart)
      #16     VisualStudio._bestVisualStudioDetails (package:flutter_tools/src/windows/visual_studio.dart:416:9)
      #17     VisualStudio.isInstalled (package:flutter_tools/src/windows/visual_studio.dart:36:27)
      #18     VisualStudioValidator.validate (package:flutter_tools/src/windows/visual_studio_validator.dart:29:23)
      #19     Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:216:72)
      #20     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #21     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #22     _rootRun (dart:async/zone.dart:1426:13)
      #23     _CustomZone.run (dart:async/zone.dart:1328:19)
      #24     _runZoned (dart:async/zone.dart:1861:10)
      #25     runZonedGuarded (dart:async/zone.dart:1849:12)
      #26     runZoned (dart:async/zone.dart:1780:12)
      #27     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #28     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:208:9)
      #29     Doctor.diagnose (package:flutter_tools/src/doctor.dart:339:72)
      #30     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #31     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1342:12)
      <asynchronous suspension>
      #32     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
      <asynchronous suspension>
      #33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #34     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #35     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #37     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #38     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #39     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #40     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[!] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\wschn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (5 available)
    • SM A520F (mobile)            • 5200ae654733a43d • android-arm64  • Android 8.0.0 (API 26)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.675]
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)                   • edge             • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by huycozy** [comment]
Hello, I tried on Windows 10 but the result still is the same:

<details>
<summary>Demo</summary>

| Physical device | Emulator |
| --------------- | --------------- |
<img width="300" src="https://user-images.githubusercontent.com/104349824/168952880-23a2cfbb-f8fd-4e65-a3b1-b5257b6a4f91.png">|<img width="300" src="https://user-images.githubusercontent.com/104349824/168952886-6b4f3657-021e-4c50-ae01-9cfa44aef43e.png">

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19043.1706], locale en-US)
    • Flutter version 3.0.0 at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (8 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (5 available)
    • Pixel 3a (mobile)       • 964AY0WL20    • android-arm64  • Android 12 (API 32)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[√] Flutter (Channel master, 3.1.0-0.0.pre.767, on Microsoft Windows [Version 10.0.19043.1706], locale en-US)
    • Flutter version 3.1.0-0.0.pre.767 at C:\WIP\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 851c9521c7 (51 minutes ago), 2022-05-17 19:52:10 -0700
    • Engine revision 2a4f04533b
    • Dart version 2.18.0 (build 2.18.0-126.0.dev)
    • DevTools version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (5 available)
    • Pixel 3a (mobile)       • 964AY0WL20    • android-arm64  • Android 12 (API 32)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Can you check the timezone on Emulator settings to make sure that it's enabled `Use network-provided time zone`?
