### ISSUE TITLE
API `file_flaky_issue_and_pr` fails when calling `_getIgnoreFlakiness`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#104099]
This blocks flake bot to file flaky issues and PRs.

```
curl 'http://flutter-dashboard.appspot.com/api/file_flaky_issue_and_pr?threshold=0.02'  -H "X-Flutter-IdToken: $(gcloud auth print-identity-token)"
Bad state: No element
#0      ListMixin.singleWhere (dart:collection/list.dart:202:5)
#1      FileFlakyIssueAndPR._getIgnoreFlakiness (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:146:52)
#2      FileFlakyIssueAndPR.get (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:52:11)
<asynchronous suspension>
#3      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#4      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:151:7)
<asynchronous suspension>
#5      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:150:5)
<asynchronous suspension>
#6      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:260:9)
<asynchronous suspension>
```

**Comment by yusuf-goog** [comment]
@CaseyHillers  and I had discussed this case before, and he seemed to think that the buildername should always be found. 

@keyonghan does flakey targets come from presubmit tests as well? The ignore flakiness function is only looking at postsubmit targets.

**Comment by keyonghan** [comment]
> @keyonghan does flakey targets come from presubmit tests as well? The ignore flakiness function is only looking at postsubmit targets.

It looks for historical prod builds which possibly contain those that have been deprecated.

**Comment by yusuf-goog** [comment]
Fixed by https://github.com/flutter/cocoon/pull/1869
