### ISSUE TITLE
[CP] <title>

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#104107]
### issue_link

https://github.com/flutter/flutter/issues/103630

### Commit Hash

https://github.com/flutter/flutter/commit/012952ba475a4380341b8d4b1f6fe5b2aa494cdf

### Target

stable

### Impacted Users

Developers of 3P plugins such as flutter-mapbox-gl on Android

### Impact Description

Crash due to 

```
Launching lib/main.dart on Pixel 3 XL in debug mode...
W/TelemetryUtils( 3225): java.lang.SecurityException: getDataNetworkTypeForSubscriber
V/Mbgl-ConnectivityReceiver( 3225): connected - true
I/Mbgl-EGLConfigChooser( 3225): In emulator: false
W/Mbgl    ( 3225): {GLThread 4356}[Android]: MapRenderer::onSurfaceCreated GlyphsRasterizationMode was specified without providing LocalIdeographFontFamily. Switching glyphsRasterizationMode to NoGlyphsRasterizedLocally mode.
I/Mbgl    ( 3225): {GLThread 4356}[General]: GPU Identifier: Adreno (TM) 630
E/flutter ( 3225): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
E/flutter ( 3225): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:732)
E/flutter ( 3225): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:791)
E/flutter ( 3225): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1380)
E/flutter ( 3225): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 3225): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 3225): 	at android.os.Looper.loopOnce(Looper.java:161)
E/flutter ( 3225): 	at android.os.Looper.loop(Looper.java:288)
E/flutter ( 3225): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/flutter ( 3225): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3225): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter ( 3225): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter ( 3225):
F/flutter ( 3225): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env).
F/libc    ( 3225): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 3225 (.dynamic_forest), pid 3225 (.dynamic_forest)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/crosshatch/crosshatch:12/SP1A.210812.016.C1/8029091:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2022-05-18 11:21:51.450777354+0200
Process uptime: 0s
Cmdline: io.ocell.dynamic_forest
pid: 3225, tid: 3225, name: .dynamic_forest  >>> io.ocell.dynamic_forest <<<
uid: 11210
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env).
'
    x0  0000000000000000  x1  0000000000000c99  x2  0000000000000006  x3  0000007fd2d46b00
    x4  6d602e6c716e6573  x5  6d602e6c716e6573  x6  6d602e6c716e6573  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  9fc9e2991523aa9a  x10 0000000000000000  x11 ffffff80fffffbdf
    x12 0000000000000001  x13 000000000000007e  x14 0000007fd2d459b0  x15 00123e205a248c91
    x16 00000077e38f5050  x17 00000077e38d1eb0  x18 00000077f98d6000  x19 0000000000000c99
    x20 0000000000000c99  x21 00000000ffffffff  x22 000000759d9687b8  x23 000000000000016f
    x24 00000075fd9521f0  x25 0000000000000000  x26 0000000000000001  x27 0000000000000081
    x28 0000007fd2d46e08  x29 0000007fd2d46b80
    lr  00000077e3884ba0  sp  0000007fd2d46ae0  pc  00000077e3884bcc  pst 0000000000000000
backtrace:
      #00 pc 000000000004fbcc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: ba489d4985c0cf173209da67405662f9)
      #01 pc 000000000156fbcc  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #02 pc 00000000015947b4  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #03 pc 000000000157ba18  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #04 pc 0000000001c6c210  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #05 pc 00000000018bd894  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #06 pc 00000000018bc4c8  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #07 pc 00000000018bcfb8  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #08 pc 00000000018bdddc  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #09 pc 00000000018bc90c  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #10 pc 00000000018bc664  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #11 pc 00000000018c8cac  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #12 pc 00000000015954b0  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #13 pc 000000000159ad58  /data/app/~~m4ZHsB0JPtFepCvXDqUD3A==/io.ocell.dynamic_forest-bCjpySnabOAOsgSNibVTsA==/lib/arm64/libflutter.so (BuildId: ebe4d2530023f7fca8a3bc8baa9e8063ba160e75)
      #14 pc 000000000001691c  /system/lib64/libutils.so (android::Looper::pollInner(int)+912) (BuildId: a3acb0eba7fd91ea48db6f0befa41c65)
      #15 pc 0000000000016524  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: a3acb0eba7fd91ea48db6f0befa41c65)
      #16 pc 000000000014acf8  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: f21e19bfa4e5c3afad804a71681c9fca)
      #17 pc 00000000001cf22c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (art_jni_trampoline+108)
      #18 pc 000000000200ffbc  /memfd:jit-cache (deleted) (android.os.MessageQueue.next+204)
      #19 pc 00000000002ca764  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #20 pc 00000000002ee6b0  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+312) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #21 pc 000000000040ade4  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+820) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #22 pc 00000000002c0ea4  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+5380) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #23 pc 00000000002c4e94  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #24 pc 000000000044cc10  /system/framework/framework.jar
      #25 pc 000000000076ce1c  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+2120) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #26 pc 00000000002c5014  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #27 pc 000000000044d394  /system/framework/framework.jar
      #28 pc 000000000076c840  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+620) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #29 pc 00000000002c5014  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #30 pc 00000000001c8542  /system/framework/framework.jar
      #31 pc 000000000027d840  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.3351068054637636664)+644) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #32 pc 000000000027c9e8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1176) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #33 pc 00000000002d4178  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #34 pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #35 pc 000000000035b5d0  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+608) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #36 pc 000000000035b348  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #37 pc 00000000000b2f74  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+132) (BuildId: ad9ee401645a5135206a62ff86fc2ef5cdc29120)
      #38 pc 00000000002ca764  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #39 pc 00000000002ee6b0  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+312) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #40 pc 000000000040ade4  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+820) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #41 pc 00000000002c0ea4  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+5380) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #42 pc 00000000002c4e94  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #43 pc 0000000000247596  /system/framework/framework.jar
      #44 pc 000000000027d840  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.3351068054637636664)+644) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #45 pc 000000000027c9e8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1176) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #46 pc 00000000002d4178  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #47 pc 00000000008598c8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2232)
      #48 pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #49 pc 000000000044ca04  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+464) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #50 pc 000000000062cf30  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+268) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #51 pc 00000000000aeac4  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120) (BuildId: f21e19bfa4e5c3afad804a71681c9fca)
      #52 pc 00000000000ba05c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+836) (BuildId: f21e19bfa4e5c3afad804a71681c9fca)
      #53 pc 000000000000258c  /system/bin/app_process64 (main+1336) (BuildId: 4ecb2c57d6667e4a94a73568ce392d22)
      #54 pc 00000000000488c8  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+96) (BuildId: ba489d4985c0cf173209da67405662f9)
Lost connection to device.
Exited
```

### Workaround

Avoid upgrading to Flutter 3.0.0

### Risk

low

### Test Coverage

yes

**Comment by HansMuller** [comment]
@cbracken - I think you would have more insight into this one.
