### ISSUE TITLE
fix flutter_gallery_ios__transition_perf flakiness

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#10419]
It's been timing out while scrolling on iOS:

```
Testing "Modal bottom sheet" demo
00:44 [32m+0[0m[31m -1[0m: flutter gallery transitions all demos[0m
  DriverError: Failed to fulfill ScrollIntoView: Flutter application not responding
  Original error: TimeoutException after 0:00:07.500000: Future not completed
  Original stack trace:
  #0      FlutterDriver._sendCommand (package:flutter_driver/src/driver.dart:295:18)
  
  #1      FlutterDriver.scrollIntoView (package:flutter_driver/src/driver.dart:378:18)
  
  #2      runDemos (file:///Users/mac4/.cocoon/flutter/examples/flutter_gallery/test_driver/transitions_perf_test.dart:157:18)
  
  #3      main.. (file:///Users/mac4/.cocoon/flutter/examples/flutter_gallery/test_driver/transitions_perf_test.dart:210:13)
  
  #4      Declarer.test.. (package:test/src/backend/declarer.dart:124:19)
  
  #5      Invoker.waitForOutstandingCallbacks.. (package:test/src/backend/invoker.dart:204:17)
  
  #6      _rootRun (dart:async/zone.dart:1120)
  #7      _CustomZone.run (dart:async/zone.dart:1001)
  #8      _CustomZone.runGuarded (dart:async/zone.dart:901)
  #9      runZoned (dart:async/zone.dart:1465)
  #10     Invoker.waitForOutstandingCallbacks. (package:test/src/backend/invoker.dart:201:7)
  #11     _rootRun (dart:async/zone.dart:1120)
  #12     _CustomZone.run (dart:async/zone.dart:1001)
  #13     runZoned (dart:async/zone.dart:1467)
  #14     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:200:5)
  #15     Declarer.test. (package:test/src/backend/declarer.dart:122:29)
  
  #16     Invoker._onRun... (package:test/src/backend/invoker.dart:341:23)
  
  #17     new Future. (dart:async/future.dart:158)
  #18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:187:15)
  #19     StackZoneSpecification._registerCallback. (package:stack_trace/src/stack_zone_specification.dart:99:48)
  #20     _rootRun (dart:async/zone.dart:1116)
  #21     _CustomZone.run (dart:async/zone.dart:1001)
  #22     _CustomZone.runGuarded (dart:async/zone.dart:901)
  #23     _CustomZone.bindCallback. (dart:async/zone.dart:926)
  #24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:187:15)
  #25     StackZoneSpecification._registerCallback. (package:stack_trace/src/stack_zone_specification.dart:99:48)
  #26     _rootRun (dart:async/zone.dart:1120)
  #27     _CustomZone.run (dart:async/zone.dart:1001)
  #28     _CustomZone.runGuarded (dart:async/zone.dart:901)
  #29     _CustomZone.bindCallback. (dart:async/zone.dart:926)
  #30     Timer._createTimer. (dart:async-patch/timer_patch.dart:21)
  #31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
  #32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
  #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
  
      
  package:flutter_driver/src/driver.dart 300:7    FlutterDriver._sendCommand
  package:flutter_driver/src/driver.dart 378:18   FlutterDriver.scrollIntoView
  test_driver/transitions_perf_test.dart 157:18   runDemos
  test_driver/transitions_perf_test.dart 210:13   main..
  ===== asynchronous gap ===========================
  dart:async                                      _Completer.completeError
  package:flutter_driver/src/driver.dart 315:3    FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async                                      _asyncErrorWrapperHelper
  package:flutter_driver/src/driver.dart 290:68   FlutterDriver._sendCommand
  package:flutter_driver/src/driver.dart 378:18   FlutterDriver.scrollIntoView
  ===== asynchronous gap ===========================
  dart:async                                      new Future.microtask
  package:flutter_driver/src/driver.dart 377:109  FlutterDriver.scrollIntoView
  test_driver/transitions_perf_test.dart 157:18   runDemos
  ===== asynchronous gap ===========================
  dart:async                                      _asyncThenWrapperHelper
  test_driver/transitions_perf_test.dart 153:73   runDemos
  test_driver/transitions_perf_test.dart 210:13   main..
  ===== asynchronous gap ===========================
  dart:async                                      _asyncThenWrapperHelper
  test_driver/transitions_perf_test.dart 189:32   main..
  ```

**Comment by yjbanov** [comment]
Based on empirical data, this is fixed. We haven't seen flakes from this test in a long time.
