### ISSUE TITLE
iOS archive failed: ProcessException: release_ios_bundle_flutter_assets No such file or directory

### ISSUE THREAD

**Issue by Stewioie** [flutter/flutter#104196]
## Steps to Reproduce

1. start iOS archive

## Logs

<details>
<summary>Logs</summary>

```
    ProcessException: No such file or directory
      Command: /Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/bin/flutter assemble --no-version-check --output=/Users/runner/work/1/s/build/ios/XXXX_Release-iphoneos/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=arm64 -dSdkRoot=/Applications/Xcode_13.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=false -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= -dCodesignIdentity=87C926BAA945F2EDEB078B4A2C2E3BA633786233 release_ios_bundle_flutter_assets
    #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
    #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
    #2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
    #3      Context.runSync (file:///Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/packages/flutter_tools/bin/xcode_backend.dart:92:42)
    #4      Context.buildApp (file:///Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/packages/flutter_tools/bin/xcode_backend.dart:449:34)
    #5      Context.run (file:///Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/packages/flutter_tools/bin/xcode_backend.dart:51:9)
    #6      main (file:///Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
    #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/runner/work/1/s/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'ReachabilitySwift' from project 'Pods')
    /Users/runner/work/1/s/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'SQLCipher' from project 'Pods')
    /Users/runner/work/1/s/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'MobileVLCKit' from project 'Pods')
    /Users/runner/work/1/s/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'FMDB' from project 'Pods')
    Result bundle written to path:
    	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/flutter_tools.57gjkg/flutter_ios_build_temp_dirnm6l0k/temporary_xcresult_bundle


Encountered error while building for device.
##[error]Bash exited with code '1'.

```

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale en)
    • Flutter version 3.0.0 at /Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (10 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/runner/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/runner/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/runner/Library/Android/sdk
    • Java binary at: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.332-9/x64/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Temurin)(build 1.8.0_332-b09)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode_13.3.1.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@Stewioie 
Can you provide the complete verbose log ? It'll be huge so you can put that in a text file and share it here.

Also, please provide the commands you are running to archive.

Maybe related / similar to https://github.com/flutter/flutter/issues/67153

**Comment by Stewioie** [comment]
Every commands attached to top of logs file

[log.txt](https://github.com/flutter/flutter/files/8737385/log.txt)

**Comment by darshankawar** [comment]
@Stewioie 
From the log, I see below error lines:

`Fingerprint write error: FileSystemException: Cannot open file, path = 'build/ios/pod_inputs.fingerprint' (OS Error: No such file or directory, errno = 2)`

Pointing to `build/ios/pod_inputs.fingerprint` which I am not where is it coming from. Maybe you can double check and see if the file really exists or not and it seems to be point to third party pod ?

**Comment by Stewioie** [comment]
with the last run the issue fixed:
Fingerprint write error: FileSystemException: Cannot open file, path = 'build/ios/pod_inputs.fingerprint' (OS Error: No such file or directory, errno = 2)

but the original problem still exists

**Comment by darshankawar** [comment]
Thanks for the update. Can you provide a minimal reproducible code sample that shows this issue ?
If you create a new Flutter project and try to archive it, does it work or give you same error ?
