### ISSUE TITLE
[image_picker][iOS]: `pickMultiImage` throws an invalid type cast exception on iOS 13

### ISSUE THREAD

**Issue by mrverdant13** [flutter/flutter#104101]
## Steps to Reproduce

1. Execute the code sample on an iOS 13 device (iOS 13.6.1)
2. Pick one or more images from the gallery (with multiple selection option ofc)
3. `image_picker` will throw the exception shown in logs

### **Expected results:** 

List of `XFile`s including the selected images.

### **Actual results:** 

Exception `type '_OneByteString' is not a subtype of type 'List<dynamic>?' in type cast`

<details>
<summary>Code sample</summary>

```dart
// The throwing method
await picker.pickMultiImage();
```

</details>

<details>
  <summary>Logs</summary>

<br>

Exception log:

```
type '_OneByteString' is not a subtype of type 'List<dynamic>?' in type cast. Error thrown null.

#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177)
<asynchronous suspension>
#1      MethodChannelImagePicker.getMultiImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:204)
<asynchronous suspension>
```

<br>

`flutter analyze` result:

```
Analyzing everything_money_app...
No issues found! (ran in 152.0s)
```

<!-- 
```
``` -->



</details>

### Related issues

- #100132

<!--
      Consider also attaching screenshots and/or videos to better
      illustrate the issue.

      You can upload them directly on GitHub.
      Beware that video file size is limited to 10MB.
-->

<br>

Besides that, I noticed that the doc comments on the `pickMultiImage` states that the method is not supported in iOS versions lower than 14. Thus, **this issue might be the result of this package misuse**.
However, I wonder why it just works fine in some devices.
Anyway, I think we can remark this limitation in a more explicit manner within the README doc.

**Comment by stuartmorgan** [comment]
This appears to be an exact duplicate of the issue you referenced. What version of `image_picker_ios` do you see in your `pubspec.lock`?

**Comment by mrverdant13** [comment]
I've got the `0.8.4+11` version for `image_picker_ios`
I notice it is not the latest one (`0.8.5+4`) and I see the changelog includes an entry for this bugfix.

Thank you for pointing this out!
Just one last question. Does that mean that we can actually use the multi picker for iOS versions lower than 14?

**Comment by stuartmorgan** [comment]
Closing as a duplicate then.

> Does that mean that we can actually use the multi picker for iOS versions lower than 14?

You can call the method, but it will do the same thing as `pickImage` on older iOS versions.
