### ISSUE TITLE
Firebase database doesn't have offline syncing

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10411]
The current plugin for firebase database doesn't have offline capabilities, and I would like to have that so a user doesn't required a connection at all times.

**Comment by eseidelGoogle** [comment]
@collinjackson

**Comment by collinjackson** [comment]
flutter upgrade to firebase_database: "^0.0.6" and use FirebaseDatabase.instance.setPersistenceEnabled(true)

**Comment by KevinTheGray** [comment]
This doesn't work for me, I've tried settingPerisistenceEnabled, keepSynced, and the data just never comes through when I set my device offline.

**Comment by KevinTheGray** [comment]
here's some logs i hit when using 0.0.6 on android 
```
E/flutter (12804): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (12804): MissingPluginException(No implementation found for method Query#keepSynced on channel plugins.flutter.io/firebase_database)
E/flutter (12804): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153)
E/flutter (12804): <asynchronous suspension>
E/flutter (12804): #1      Query.keepSynced (package:firebase_database/src/query.dart:170)
E/flutter (12804): #2      new NewsFeedManager._internal (package:hamilton/managers/news_feed_manager.dart:75)
E/flutter (12804): #3      NewsFeedManager._newsFeedManager (package:hamilton/managers/news_feed_manager.dart:45)
E/flutter (12804): #4      NewsFeedManager._newsFeedManager (package:hamilton/managers/news_feed_manager.dart:44)
E/flutter (12804): #5      new NewsFeedManager (package:hamilton/managers/news_feed_manager.dart:48)
E/flutter (12804): #6      new _NewsFeedComponentState (package:hamilton/components/newsfeed/news_feed_component.dart:31)
E/flutter (12804): #7      new NewsFeedComponent (package:hamilton/components/newsfeed/news_feed_component.dart:19)
E/flutter (12804): #8      new _MainComponentState (package:hamilton/components/main/main_component.dart:37)
E/flutter (12804): #9      new MainComponent (package:hamilton/components/main/main_component.dart:19)
E/flutter (12804): #10     new AppState (package:hamilton/components/app/app_state.dart:22)
E/flutter (12804): #11     App.createState (package:hamilton/components/app/app.dart:15)
E/flutter (12804): #12     new StatefulElement (package:flutter/src/widgets/framework.dart:3461)
E/flutter (12804): #13     StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:734)
E/flutter (12804): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2748)
E/flutter (12804): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
E/flutter (12804): #16     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:732)
E/flutter (12804): #17     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:703)
E/flutter (12804): #18     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:649)
E/flutter (12804): #19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2122)
E/flutter (12804): #20     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:648)
E/flutter (12804): #21     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:543)
E/flutter (12804): #22     runApp (package:flutter/src/widgets/binding.dart:581)
E/flutter (12804): #23     main (file:///Users/KG/Developer/Client/hamilton-flutter/lib/main.dart:14)
E/flutter (12804): #24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
E/flutter (12804): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by collinjackson** [comment]
Thanks, I'm investigating.

**Comment by collinjackson** [comment]
Thanks! I'm investigating.

**Comment by collinjackson** [comment]
Fixed in firebase_database 0.0.7.

**Comment by StephaneBischoff** [comment]
Added new issue related to Offline support #15653

**Comment by kroikie** [comment]
@KevinTheGray

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1005. Any further collaboration will be done there.
