### ISSUE TITLE
ci.yaml validation check never got scheduled

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#104269]
https://github.com/flutter/flutter/pull/104257

**Comment by CaseyHillers** [comment]
When I moved it from draft->ready for review the tests were scheduled

**Comment by keyonghan** [comment]
Seems a temporary github request error:
```
2022-05-20 06:45:42.440 PDT
Applying framework repo labels for: owner=flutter repo=flutter and pr=104257
2022-05-20 06:45:42.584 PDT
GitHub Error: Requested Resource was Not Found
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:444:9)
#1      GitHub.request (package:github/src/common/github.dart:409:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:38:20)
<asynchronous suspension>
#3      PaginationHelper.jsonObjects (package:github/src/common/util/pagination.dart:95:5)
<asynchronous suspension>
```

Please reopen if this still happens.
