### ISSUE TITLE
Crash on launch on Android API Level 32 (Android 12L)

### ISSUE THREAD

**Issue by th0rgall** [flutter/flutter#104279]
## Steps to Reproduce

1. Create an Android Virtual Device (Pixel 4) with a Google Play & arm64 **API Level 32** system image.
2. Build a flutter app. The build completes.
3. Launch the flutter app on the created device. It crashes on launch, with the following exception (details in the logs):

```
E/AndroidRuntime(12950): java.lang.NoSuchMethodError: No interface method addWindowLayoutInfoListener(Landroid/app/Activity;Lj$/util/function/Consumer;)V in class Landroidx/window/extensions/layout/WindowLayoutComponent; or its super classes (declaration of 'androidx.window.extensions.layout.WindowLayoutComponent' appears in /system_ext/framework/androidx.window.extensions.jar)
```

## More context
- The app builds and runs fine on an API Level 29 virtual android device.
- I see that Android 12L / API Level 32 is not explicitly mentioned on the [supported platforms](https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms) page. Does that mean that all Flutter apps are simply broken on devices with Android 12L?

## Logs

<details>
<summary>Logs</summary>

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(12950): FATAL EXCEPTION: main
E/AndroidRuntime(12950): Process: app.potential.android, PID: 12950
E/AndroidRuntime(12950): java.lang.NoSuchMethodError: No interface method addWindowLayoutInfoListener(Landroid/app/Activity;Lj$/util/function/Consumer;)V in class Landroidx/window/extensions/layout/WindowLayoutComponent; or its super classes (declaration of 'androidx.window.extensions.layout.WindowLayoutComponent' appears in /system_ext/framework/androidx.window.extensions.jar)
E/AndroidRuntime(12950): 	at androidx.window.layout.ExtensionWindowLayoutInfoBackend.registerLayoutChangeCallback(ExtensionWindowLayoutInfoBackend.kt:68)
E/AndroidRuntime(12950): 	at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invokeSuspend(WindowInfoTrackerImpl.kt:52)
E/AndroidRuntime(12950): 	at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(Unknown Source:8)
E/AndroidRuntime(12950): 	at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(Unknown Source:4)
E/AndroidRuntime(12950): 	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
E/AndroidRuntime(12950): 	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
E/AndroidRuntime(12950): 	at androidx.window.java.layout.WindowInfoTrackerCallbackAdapter$addListener$1$1.invokeSuspend(WindowInfoTrackerCallbackAdapter.kt:96)
E/AndroidRuntime(12950): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(12950): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(12950): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(12950): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12950): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(12950): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(12950): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(12950): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12950): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(12950): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Error connecting to the service protocol: failed to connect to http://127.0.0.1:54959/u_yYlROrEsY=/
Exited
```

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-arm (Rosetta), locale en-FI)
    • Flutter version 3.0.0 at /Users/thor/fvm/versions/3.0.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (11 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/thor/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/thor/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)          • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • Android SDK built for arm64 (mobile) • emulator-5556                        • android-arm64  • Android 10 (API 29) (emulator)
    • iPhone SE (3rd generation) (mobile)  • 449A68C2-F506-46D9-B59F-16F398EE38BD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm (Rosetta)
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by blasten** [comment]
I tried on a x64 emulator as I don't think that would make any difference.
<img width="556" alt="Screen Shot 2022-05-20 at 12 16 40 PM" src="https://user-images.githubusercontent.com/1410613/169596906-c68e003f-570b-4a29-9893-d4ef946cf982.png">


What are the concrete steps to reproduce this issue (including `flutter create`)?

**Comment by th0rgall** [comment]
Ok, when building & launching the `flutter create` demo project on my emulator I also can't reproduce this issue. So my reproduction steps weren't accurate.

I'm experiencing this issue in a more complex production Flutter app. There is probably some custom Android code or a 3rd party dependency is causing it. We'll try to debug it further to get more insight on what's going wrong. I'll close this for now, thanks!
