### ISSUE TITLE
My app doesn't run on iOS Simulator

### ISSUE THREAD

**Issue by fedecarroz** [flutter/flutter#104260]
Hi everyone, I've been facing a problem for several days. My app works perfectly on the android emulator, but I can't run it anymore on the iOS simulator because of the following problem.

## Steps to Reproduce
1. Run my app on iOS Simulator

**Expected results:**
Working app

**Actual results:**
Error

<details>
  <summary>Logs</summary>

```
[+3862 ms] Observatory URL on device: http://127.0.0.1:49960/eKCrxJvDlbc=/
[  +11 ms] Caching compiled dill
[ +136 ms] Connecting to service protocol: http://127.0.0.1:49960/eKCrxJvDlbc=/
[ +861 ms] Fail to connect to service protocol: http://127.0.0.1:49960/eKCrxJvDlbc=/: HttpException: Connection reset by peer, uri =
http://127.0.0.1:49960/eKCrxJvDlbc=/ws
[   +1 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:49960/eKCrxJvDlbc=/
[   +4 ms] "flutter run" took 1.214.053ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 2
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.6.5 20G527 darwin-x64, locale it-IT)
    • Flutter version 3.0.1 at /Users/federico/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (16 hours ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/federico/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 8FEB929E-6A40-43D3-B13E-3A9EE7B4991F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.6.5 20G527 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

## O.S. version
MacOS Big Sur 11.6.5

## Xcode version
Xcode 13.2.1

## What I have already tried
- search the internet of course (stackoverflow / other flutter similar issues on github)
- flutter clean
- flutter channel master
- uninstall flutter sdk and re-download it (3.0.0 and 3.0.1 stable)
- pod install / pod update / pod repo update
- Podfile deleted
- delete ios folder and re build it from scratch

**Comment by maheshmnj** [comment]
Hi @fedecarroz, Thanks for filing the issue. Does this issue occur with a newly created flutter project too? Please share the output of `flutter run -v` in a text file (as the output will be long)

**Comment by fedecarroz** [comment]
Thank you for your response. I "solved" the issue. The problem was a conflict between two facebook imported packages. I actually didn't understand the problem. If I find out what is the problem I'll let you know
