### ISSUE TITLE
Users reported App Crash while picking image (Both single or multi) (Got from Firebase Crashlytics)

### ISSUE THREAD

**Issue by anirudhkh1** [flutter/flutter#104255]
## Issue
Hi, my app is getting crashed while using Image Picker. I got to know by the logs from crashlytics. Users have reported crash while picking images (singleImage or MultiImage), it crashes in both mode.

Also this crash is very random.

Here is a specific crash report of specific user.

Phone Model -> GM1901
Android Version -> 11

I previously opened almost the same [issue](https://github.com/flutter/flutter/issues/104168) (not sure if related to this). It has reproducible steps.

## Steps to Reproduce

1. Steps cannot be reproduced as the crash is very random.

<details>
<summary>Part of my code</summary>

```
List<XFile> pickedFiles = await imagePicker.pickMultiImage(imageQuality: 50);
              if (pickedFiles != null) {
                int imagesLeft = 0;
                futureOrderProvider.referenceImages.forEach((imageFile) {
                  if (imageFile == null) imagesLeft += 1;
                });
                if (pickedFiles.length > imagesLeft) {
                  FlutterToastHelper().showToast(
                    msg: "Can't select more than $totalRefImages images",
                  );
                }
                futureOrderProvider.setReferenceImages(pickedFiles);
              }
```

</details>

<details>
<summary>Image Picker Version</summary>

```
image_picker: ^0.8.5
```

</details>

## Firebase Crashlytics Log

<details>
  <summary>Fatal Exception: java.lang.RuntimeException</summary>

```
Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:259662 flg=0x1 }} to activity {com.bakerAssist/com.bakerAssist.MainActivity}: java.lang.IllegalStateException: Reply already submitted


Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:259662 flg=0x1 }} to activity {com.bakerAssist/com.bakerAssist.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5213)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5254)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

</details>

<details>
  <summary>Caused by java.lang.IllegalStateException</summary>

```
Reply already submitted


Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.finishWithResult(ContactsServicePlugin.java:4)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:90)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:20)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:10)
       at android.app.Activity.dispatchActivityResult(Activity.java:8316)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5206)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5254)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

</details>

![issue1](https://user-images.githubusercontent.com/43062587/169537699-c1527743-ddae-4103-b8fc-28fefe1d2afc.png)
![issue2](https://user-images.githubusercontent.com/43062587/169537744-725fa908-0b49-4280-905c-890d3a8ad11d.png)

**Comment by danagbemava-nc** [comment]
Hi @anirudhkh1, the second stacktrace shows that the crash is from the `contactsservice` plugin. You may need to file an issue on their repo. 

With regards to the first stacktrace, is that all there is to the crash log?
