### ISSUE TITLE
Firebase Database Lib fails with onChildChanged 

### ISSUE THREAD

**Issue by zhangandyx** [flutter/flutter#10439]
My guess is the problem is that the `[]=` operator was not implemented

```
  // ListBase implementation
  final List<DataSnapshot> _snapshots = <DataSnapshot>[];
  int get length => _snapshots.length;
  DataSnapshot operator [](int index) => _snapshots[index];
```
## Steps to Reproduce

* Start with the finished Firebase Flutter Codelab
* Send a few messages
* Go into the Firebase Database and edit a message

## Logs

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Built build/app/outputs/apk/app-debug.apk (25.2MB).
D/        (29965): HostConnection::get() New Host Connection established 0x8bbfe040, tid 29986
I/DynamiteModule(29965): Considering local module com.google.android.gms.firebase_database:4 and remote module com.google.android.gms.firebase_database:6
I/DynamiteModule(29965): Selected remote version of com.google.android.gms.firebase_database, version >= 6
W/System  (29965): ClassLoader referenced unknown path: 
W/System  (29965): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000008/n/x86
D/NetworkSecurityConfig(29965): No Network Security Config specified, using platform default
I/FA      (29965): Tag Manager is not found and thus will not be used
W/DynamiteModule(29965): Local module descriptor class for com.google.firebase.auth not found.
E/flutter (29965): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (29965): NoSuchMethodError: Class 'FirebaseSortedList' has no instance method '[]='.
E/flutter (29965): Receiver: Instance of 'FirebaseSortedList'
E/flutter (29965): Tried calling: []=(0, Instance of 'DataSnapshot')
E/flutter (29965): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
E/flutter (29965): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
E/flutter (29965): #2      FirebaseSortedList._onChildChanged (package:firebase_database/ui/firebase_sorted_list.dart:81)
E/flutter (29965): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
E/flutter (29965): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
E/flutter (29965): #5      _DelayedData.perform (dart:async/stream_impl.dart:578)
E/flutter (29965): #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
E/flutter (29965): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
E/flutter (29965): #8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (29965): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

Run `flutter analyze` and attach any output of that command also.

```
andy@andy-ubuntu:~/code/myflutterapp$ flutter analyze
Analyzing /home/andy/code/myflutterapp...
No issues found!
Ran in 2.9s
```

## Flutter Doctor

Paste the output of running `flutter doctor` here.
```
andy@andy-ubuntu:~/code/myflutterapp$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/andy/code/flutter
    • Framework revision 973304d5fb (2 weeks ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/andy/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
@collinjackson has at least one patch in flight to improve the firebase_database plugin, and would know if such fixes this.

**Comment by ZhangBanger** [comment]
@eseidel Thanks!
@collinjackson Great! Is there a branch I can follow and suggest a PR for?

**Comment by collinjackson** [comment]
Follow https://github.com/flutter/plugins/pull/89 for updates. Should be landing soon.

**Comment by ZhangBanger** [comment]
Is the plan to support the` onChildChanged` event?

**Comment by collinjackson** [comment]
It's coming shortly! Follow flutter/plugins#101 for updates. (I ended up splitting flutter/plugins#89 into two parts)

**Comment by zoechi** [comment]
I think this is fixed

**Comment by zoechi** [comment]
I assume this was fixed.

**Comment by kroikie** [comment]
@zhangandyx

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1002. Any further collaboration will be done there.
