### ISSUE TITLE
[web][html] App crashes with `element.parent == _resourcesHost is not true` when scrolling through svg images

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#104305]
This code I'm running is years old and has always worked until now.

I'm on the latest flutter, but not sure when this started.

I have a big grid of a hundred or so SVGs and now it randomly crashes and hangs the browser.

<details>
<summary> logs</summary>

```
Exception has occurred.
"Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/embedder.dart:494:12
element.parent == _resourcesHost
is not true
    at Object.throw_ [as throw] (http://localhost:45379/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:45379/dart_sdk.js:5005:15)
    at _engine.FlutterViewEmbedder.new.removeResource (http://localhost:45379/dart_sdk.js:153654:72)
    at _engine.PersistedColorFilter.new.apply (http://localhost:45379/dart_sdk.js:157290:35)
    at _engine.PersistedColorFilter.new.build (http://localhost:45379/dart_sdk.js:154543:12)
    at _engine.PersistedColorFilter.new.build (http://localhost:45379/dart_sdk.js:154746:13)
    at _engine.PersistedOffset.new.build (http://localhost:45379/dart_sdk.js:154762:17)
    at _engine.PersistedClipRect.new.[_updateManyToMany] (http://localhost:45379/dart_sdk.js:154951:22)
    at _engine.PersistedClipRect.new.update (http://localhost:45379/dart_sdk.js:154787:32)
    at _engine.PersistedClipRect.new.update (http://localhost:45379/dart_sdk.js:156713:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45379/dart_sdk.js:154878:18)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:154783:31)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:157975:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45379/dart_sdk.js:154878:18)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:154783:31)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:157975:13)
    at _engine.PersistedOffset.new.[_updateManyToMany] (http://localhost:45379/dart_sdk.js:154939:20)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:154787:32)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:157975:13)
    at _engine.PersistedPhysicalShape.new.[_updateManyToMany] (http://localhost:45379/dart_sdk.js:154939:20)
    at _engine.PersistedPhysicalShape.new.update (http://localhost:45379/dart_sdk.js:154787:32)
    at _engine.PersistedPhysicalShape.new.update (http://localhost:45379/dart_sdk.js:157087:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45379/dart_sdk.js:154878:18)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:154783:31)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:157975:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45379/dart_sdk.js:154878:18)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:154783:31)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:157975:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45379/dart_sdk.js:154878:18)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:154783:31)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:157975:13)
    at _engine.PersistedOffset.new.[_updateManyToMany] (http://localhost:45379/dart_sdk.js:154939:20)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:154787:32)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:157975:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45379/dart_sdk.js:154878:18)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:154783:31)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:157975:13)
    at _engine.PersistedOffset.new.[_updateManyToMany] (http://localhost:45379/dart_sdk.js:154939:20)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:154787:32)
    at _engine.PersistedOffset.new.update (http://localhost:45379/dart_sdk.js:157975:13)
    at _engine.PersistedTransform.new.[_updateManyToOne] (http://localhost:45379/dart_sdk.js:154878:18)
    at _engine.PersistedTransform.new.update (http://localhost:45379/dart_sdk.js:154783:31)
    at _engine.PersistedTransform.new.update (http://localhost:45379/dart_sdk.js:170066:13)
    at _engine.PersistedScene.new.[_updateManyToOne] (http://localhost:45379/dart_sdk.js:154878:18)
    at _engine.PersistedScene.new.update (http://localhost:45379/dart_sdk.js:154783:31)
    at http://localhost:45379/dart_sdk.js:167866:33
    at Object.timeAction (http://localhost:45379/dart_sdk.js:191830:14)
    at _engine.SurfaceSceneBuilder.new.build (http://localhost:45379/dart_sdk.js:167862:22)
    at layer$.TransformLayer.new.buildScene (http://localhost:45379/packages/flutter/src/rendering/layer.dart.lib.js:1177:27)
    at view.RenderView.new.compositeFrame (http://localhost:45379/packages/flutter/src/rendering/layer.dart.lib.js:4772:48)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:45379/packages/flutter/src/rendering/layer.dart.lib.js:5511:25)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:45379/packages/flutter/src/widgets/title.dart.lib.js:56093:15)
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:45379/packages/flutter/src/rendering/layer.dart.lib.js:5472:12)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:45379/packages/flutter/src/scheduler/binding.dart.lib.js:736:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:45379/packages/flutter/src/scheduler/binding.dart.lib.js:707:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:45379/packages/flutter/src/scheduler/binding.dart.lib.js:660:12)
    at Object.invoke (http://localhost:45379/dart_sdk.js:191736:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnDrawFrame (http://localhost:45379/dart_sdk.js:171933:15)
    at http://localhost:45379/dart_sdk.js:191477:57"
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on Debian GNU/Linux 11 (bullseye) 5.10.0-14-amd64, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /home/steve/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (28 hours ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /home/steve/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: /home/steve/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.15.2
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/steve/android-studio
    • Flutter plugin version 64.0.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.67.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 11 (bullseye) 5.10.0-14-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
</details>

**Comment by sgehrman** [comment]
https://github.com/dnfield/flutter_svg/issues/706

**Comment by mdeandrea-mrmilu** [comment]
This error happens with Flutter 2.10.5. I don't know if with previous versions happens too

**Comment by mdeandrea-mrmilu** [comment]
@danagbemava-nc you can see a minimal reproducible code sample **with package flutter_svg**, in https://github.com/dnfield/flutter_svg/issues/706

**Comment by ElAdrixHD** [comment]
Hello, I just did some more tests and it seems that it only fails when you are in development mode. If you put the --release flag, it works fine. It is strange and this can be confusing.

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master` only in `debug` mode when using the `html` renderer. `Profile` and `release` mode work just fine.

The `flutter_svg` package is required to reproduce this issue.
I used https://github.com/dnfield/flutter_svg/blob/master/example/assets/flutter_logo.svg in my reproduction, but I think any svg asset will also reproduce the issue.

### Steps to reproduce
- Run the code sample below on web using the HTML renderer
- Repeatedly scroll up and down very fast (easiest done with the mouse scrollwheel)

I attempted to capture a recording of the crash, but the recorder app always reset itself whenever the app crashed. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.separated(
          shrinkWrap: true,
          itemBuilder: (context, index) => SvgPicture.asset(
                'assets/images/flutter_logo.svg',
                color: Theme.of(context).colorScheme.primary,
              ),
          separatorBuilder: (context, index) => const SizedBox(
                height: 20,
              ),
          itemCount: 1000),
    );
  }
}

```
</details>

<details>
<summary>logs</summary>


[canvaskit_log.txt](https://github.com/flutter/flutter/files/8768561/canvaskit_log.txt)
[html_log.txt](https://github.com/flutter/flutter/files/8768562/html_log.txt)
[html_release_log.txt](https://github.com/flutter/flutter/files/8768563/html_release_log.txt)

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.0.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.897, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.897 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 680a8192b0 (2 hours ago), 2022-05-24 21:23:09 -0700
    • Engine revision 7274f79325
    • Dart version 2.18.0 (build 2.18.0-149.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by ali-thegilfoyle** [comment]
Settings `shrinkWrap` property to `true` resolve this issue for me, I am not sure that the issue is permanently gone, but it is not occurring as frequently as before. Hope it will help others and developers to fix it.

**Comment by sgehrman** [comment]
Just updated to Flutter 3.3.0 and am seeing this again.

lib/_engine/engine/html/surface.dart 709:7                                        update
lib/_engine/engine/html/scene_builder.dart 540:25                                 <fn>
lib/_engine/engine/profiler.dart 34:18                                            timeAction
lib/_engine/engine/html/scene_builder.dart 536:12                                 build
packages/flutter/src/rendering/layer.dart 1062:35                                 buildScene
packages/flutter/src/rendering/view.dart 231:30                                   compositeFrame
packages/flutter/src/rendering/binding.dart 517:18                                drawFrame
packages/flutter/src/widgets/binding.dart 884:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 378:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1175:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1104:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1015:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1168:13                               invoke
lib/_engine/engine/platform_dispatcher.dart 219:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 195:45                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
