### ISSUE TITLE
[tool_crash] FileSystemException: readSync failed, OS Error: Invalid argument, errno = 22

### ISSUE THREAD

**Issue by horo99** [flutter/flutter#104336]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readSync failed, OS Error: Invalid argument, errno = 22
```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:763:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:552:23)
#2      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#4      _calculateSha (package:flutter_tools/src/android/gradle.dart:759:32)
#5      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:489:34)
<asynchronous suspension>
#6      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#7      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:109:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.0.1 at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 天前), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] And

**Comment by horo99** [comment]
my project is running in good condition before add many assets, which are hundreds of audios files, totally around 3.75GB .
and when I removed these assets, and commented the import in `pubspec.yaml` as below
`  assets:
    - assets/images/
#    - data/audios/
`
then my project builds normally as before.
so I think the problem is caused by these audios assets files with big size, but don't know how to solve it?

**Comment by danagbemava-nc** [comment]
Hi @horo99, there's a similar issue describing what you're experiencing in https://github.com/flutter/flutter/issues/94324.

Kindly follow up there for more information. 

Closing from here as duplicate. 

Thank you
