### ISSUE TITLE
RenderSliverPadding.debugPaint doesn't handle negative padding

### ISSUE THREAD

**Issue by zhangandyx** [flutter/flutter#10445]
I think the assertion is failing because it doesn't check the absolute value of the rectangles coords (which from the looks of the code was the intent)

```
          assert(innerRect.top >= outerRect.top);
          assert(innerRect.left >= outerRect.left);
          assert(innerRect.right <= outerRect.right);
          assert(innerRect.bottom <= outerRect.bottom);  // fails here!
```
In the debugger:

`outerRect=Rect.fromLTRB(0.0, 0.0, 411.4, -555.4)`
`innerRect=Rect.fromLTRB(8.0, 0.0, 403.4, -547.4)`

## Steps to Reproduce
* Start with completed FlutterFirebase codelab
* Add import for rending `import 'package:flutter/rendering.dart';`
* Add `debugPaintSizeEnabled = true;` in first line of `main()

## Logs

Run your application with `flutter run` and attach all the log output.

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Built build/app/outputs/apk/app-debug.apk (25.2MB).
I/OpenGLRenderer( 2918): Initialized EGL, version 1.4
D/OpenGLRenderer( 2918): Swap behavior 1
D/        ( 2918): HostConnection::get() New Host Connection established 0x9c012d40, tid 2947
W/OpenGLRenderer( 2918): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer( 2918): Swap behavior 0
D/        ( 2918): HostConnection::get() New Host Connection established 0x9c038200, tid 2939
I/DynamiteModule( 2918): Considering local module com.google.android.gms.firebase_database:4 and remote module com.google.android.gms.firebase_database:6
I/DynamiteModule( 2918): Selected remote version of com.google.android.gms.firebase_database, version >= 6
W/System  ( 2918): ClassLoader referenced unknown path: 
W/System  ( 2918): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000008/n/x86
D/NetworkSecurityConfig( 2918): No Network Security Config specified, using platform default
I/flutter ( 2918): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 2918): The following assertion was thrown during paint():
I/flutter ( 2918): 'package:flutter/src/rendering/sliver_padding.dart': Failed assertion: line 275: 'innerRect.bottom
I/flutter ( 2918): <= outerRect.bottom': is not true.
I/flutter ( 2918): 
I/flutter ( 2918): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 2918): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 2918): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 2918):   https://github.com/flutter/flutter/issues/new
I/flutter ( 2918): 
I/flutter ( 2918): When the exception was thrown, this was the stack:
I/flutter ( 2918): #2      RenderSliverPadding.debugPaint.<anonymous closure> (package:flutter/src/rendering/sliver_padding.dart:275)
I/flutter ( 2918): #4      RenderSliverPadding.debugPaint (package:flutter/src/rendering/sliver_padding.dart:262)
I/flutter ( 2918): #5      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2295)
I/flutter ( 2918): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2294)
I/flutter ( 2918): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 2918): #9      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:298)
I/flutter ( 2918): #10     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:277)
I/flutter ( 2918): #11     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:289)
I/flutter ( 2918): #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #13     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97)
I/flutter ( 2918): #14     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:134)
I/flutter ( 2918): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:115)
I/flutter ( 2918): #16     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:118)
I/flutter ( 2918): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 2918): #19     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:118)
I/flutter ( 2918): #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 2918): #22     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:118)
I/flutter ( 2918): #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 2918): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:118)
I/flutter ( 2918): #26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #27     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97)
I/flutter ( 2918): #28     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:134)
I/flutter ( 2918): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:115)
I/flutter ( 2918): #30     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:118)
I/flutter ( 2918): #31     RenderCustomPaint.paint (package:flutter/src/rendering/proxy_box.dart:2166)
I/flutter ( 2918): #32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 2918): #34     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:118)
I/flutter ( 2918): #35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #36     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97)
I/flutter ( 2918): #37     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:134)
I/flutter ( 2918): #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:115)
I/flutter ( 2918): #39     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2075)
I/flutter ( 2918): #40     RenderFlex.paint (package:flutter/src/rendering/flex.dart:692)
I/flutter ( 2918): #41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 2918): #43     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2075)
I/flutter ( 2918): #44     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:343)
I/flutter ( 2918): #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 2918): #47     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:118)
I/flutter ( 2918): #48     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:324)
I/flutter ( 2918): #49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 2918): #51     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:118)
I/flutter ( 2918): #52     PaintingContext.pushPhysicalModel (package:flutter/src/rendering/object.dart:471)
I/flutter ( 2918): #53     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1299)
I/flutter ( 2918): #54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 2918): #56     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:118)
I/flutter ( 2918): #57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2288)
I/flutter ( 2918): #58     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97)
I/flutter ( 2918): #59     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1120)
I/flutter ( 2918): #60     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:234)
I/flutter ( 2918): #61     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:361)
I/flutter ( 2918): #62     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170)
I/flutter ( 2918): #63     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:685)
I/flutter ( 2918): #64     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:633)
I/flutter ( 2918): #65     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:88)
I/flutter ( 2918): (elided 4 frames from class _AssertionError)
I/flutter ( 2918): 
I/flutter ( 2918): The following RenderObject was being processed when the exception was fired:
I/flutter ( 2918):   RenderViewport#493455516
I/flutter ( 2918):   creator: Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#484189140] ← Listener ←
I/flutter ( 2918):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#426675668] ←
I/flutter ( 2918):   RepaintBoundary ← CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification> ←
I/flutter ( 2918):   GlowingOverscrollIndicator ← Scrollable ← ⋯
I/flutter ( 2918):   parentData: <none> (can use size)
I/flutter ( 2918):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=555.4)
I/flutter ( 2918):   layer: OffsetLayer#338543366 DETACHED
I/flutter ( 2918):   size: Size(411.4, 555.4)
I/flutter ( 2918):   AxisDirection.up
I/flutter ( 2918):   offset: ScrollPositionWithSingleContext#972922520(offset: 0.0, range: 0.0..600.6, viewport: 555.4,
I/flutter ( 2918):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics,
I/flutter ( 2918):   IdleScrollActivity#936211136, ScrollDirection.idle)
I/flutter ( 2918):   anchor: 0.0
I/flutter ( 2918): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 2918):   RenderSliverPadding#190575141 relayoutBoundary=up1
I/flutter ( 2918):     RenderSliverList#568512175 relayoutBoundary=up2
I/flutter ( 2918):       RenderRepaintBoundary#933112465 relayoutBoundary=up3
I/flutter ( 2918):         RenderClipRect#981420142 relayoutBoundary=up4
I/flutter ( 2918):           RenderPositionedBox#1024994627 relayoutBoundary=up5
I/flutter ( 2918):       RenderRepaintBoundary#166746113 relayoutBoundary=up3
I/flutter ( 2918):         RenderClipRect#337200091 relayoutBoundary=up4
I/flutter ( 2918):           RenderPositionedBox#661686918 relayoutBoundary=up5
I/flutter ( 2918):       RenderRepaintBoundary#288210293 relayoutBoundary=up3
I/flutter ( 2918):         RenderClipRect#530963776 relayoutBoundary=up4
I/flutter ( 2918):           RenderPositionedBox#808385887 relayoutBoundary=up5
I/flutter ( 2918):       RenderRepaintBoundary#668443489 relayoutBoundary=up3
I/flutter ( 2918):         RenderClipRect#111371580 relayoutBoundary=up4
I/flutter ( 2918):           RenderPositionedBox#716832371 relayoutBoundary=up5
I/flutter ( 2918):       RenderRepaintBoundary#458732142 relayoutBoundary=up3
I/flutter ( 2918):         RenderClipRect#41435097 relayoutBoundary=up4
I/flutter ( 2918):           RenderPositionedBox#829263211 relayoutBoundary=up5
I/flutter ( 2918):       RenderRepaintBoundary#972876192 relayoutBoundary=up3
I/flutter ( 2918):         RenderClipRect#529812423 relayoutBoundary=up4
I/flutter ( 2918):           RenderPositionedBox#770570930 relayoutBoundary=up5
I/flutter ( 2918):       RenderRepaintBoundary#864671893 relayoutBoundary=up3
I/flutter ( 2918):         RenderClipRect#1057149847 relayoutBoundary=up4
I/flutter ( 2918):           RenderPositionedBox#674463850 relayoutBoundary=up5
I/flutter ( 2918):       RenderRepaintBoundary#360101503 relayoutBoundary=up3
I/flutter ( 2918):         RenderClipRect#722978464 relayoutBoundary=up4
I/flutter ( 2918):           RenderPositionedBox#570235328 relayoutBoundary=up5
I/flutter ( 2918):       RenderRepaintBoundary#975960227 relayoutBoundary=up3
I/flutter ( 2918):         RenderClipRect#633207885 relayoutBoundary=up4
I/flutter ( 2918):           RenderPositionedBox#330633692 relayoutBoundary=up5
I/flutter ( 2918): ════════════════════════════════════════════════════════════════════════════════════════════════════
F/libc    ( 2918): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 2940 (ui_thread)
Lost connection to device.
```

Run `flutter analyze` and attach any output of that command also.
```
andy@andy-ubuntu:~/code/myflutterapp$ flutter analyze
Analyzing /home/andy/code/myflutterapp...
No issues found!
Ran in 2.8s
```

## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
andy@andy-ubuntu:~/code/myflutterapp$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/andy/code/flutter
    • Framework revision 973304d5fb (2 weeks ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/andy/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
This should be clamping the dimensions of the two rects to zero, not allowing negative values, before doing the assert.

**Comment by Piinks** [comment]
This is a dup of https://github.com/flutter/flutter/issues/28406 which will be fixed once https://github.com/flutter/flutter/pull/37033 has landed.
If this is not the case and this bug persists on master after that PR lands, please feel free to re-open.
