### ISSUE TITLE
Android Crash (live app release mode) signal 6 (SIGABRT), code -1 (SI_QUEUE)

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#104514]
## Steps to Reproduce

Unfortunately i can't reproduce this issue, but i hope that you will have an idea of what this is about.

Affected phones of this are only under Android 11 (SDK 30). 

**Expected results:** 

The app should not crash / should not go in ANR state.

**Actual results:** 

ANRs occur and the app crashes.

<details>
  <summary>Logs</summary>

Regarding the crash, here is the trace i am getting from Google Play Console : 

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.listeen.android <<<

backtrace:
  #00  pc 0000000000089a8c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #00  pc 000000000055d060  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2308)
  #00  pc 0000000000013978  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76)
  #00  pc 0000000000006e7c  /system/lib64/liblog.so (__android_log_assert+336)
  #00  pc 0000000000216870  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::getFrame()+52)
  #00  pc 000000000021f9b4  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+412)
  #00  pc 0000000000222308  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+588)
  #00  pc 00000000002105f0  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+220)
  #00  pc 0000000000232018  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+88)
  #00  pc 00000000000154cc  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260)
  #00  pc 0000000000014d90  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412)
  #00  pc 00000000000eb6c8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #00  pc 000000000008ba48  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

ANR from crashlytics maybe linked because it's the same affected phones : 

```
main (native): tid=1 systid=18282 
#00 pc 0x5e4a8 libc.so 
#01 pc 0x636a9 libc.so 
#02 pc 0xaa5b3 libc.so 
#03 pc 0x16c631 split_config.armeabi_v7a.apk!libflutter.so 
#04 pc 0x530fb base.odex 
       at io.flutter.embedding.engine.FlutterJNI.nativeSurfaceDestroyed(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterJNI.onSurfaceDestroyed(FlutterJNI.java)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.stopRenderingToSurface(FlutterRenderer.java)
       at io.flutter.embedding.android.FlutterSurfaceView.disconnectSurfaceFromRenderer(FlutterSurfaceView.java)
       at io.flutter.embedding.android.FlutterSurfaceView.access$400(FlutterSurfaceView.java)
       at io.flutter.embedding.android.FlutterSurfaceView$1.surfaceDestroyed(FlutterSurfaceView.java)
       at android.view.SurfaceView.notifySurfaceDestroyed(SurfaceView.java:2025)
       at android.view.SurfaceView.updateSurface(SurfaceView.java:1245)
       at android.view.SurfaceView.setWindowStopped(SurfaceView.java:343)
       at android.view.SurfaceView.surfaceDestroyed(SurfaceView.java:1845)
       at android.view.ViewRootImpl.notifySurfaceDestroyed(ViewRootImpl.java:2374)
       at android.view.ViewRootImpl.setWindowStopped(ViewRootImpl.java:2330)
       at android.view.WindowManagerGlobal.setStoppedState(WindowManagerGlobal.java:741)
       at android.app.Activity.performStop(Activity.java:8432)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5356)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5329)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5409)
       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale fr-FR)
    • Flutter version 3.0.1 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/104514#issue-1246770479 force flutter#v3.0.1 android release arm64

**Comment by chartreux** [comment]
I borrowed a terminal with a problem and confirmed it.
Vivo vivo 1901

I was able to reproduce it by the following operation.
1. Launch the file selection app in the app.
2. Change the language in the smartphone settings.
3. Return to the app and select a file.
4. A crash occurs after selecting a file.

Isn't this the same issue? [#103870](https://github.com/flutter/flutter/issues/103870)

<details>
<summary>Logs</summary>

```
2022-05-28 12:21:27.709 20961-20961/? A/DEBUG: Softversion: PD1901BF_EX_A_6.12.21
2022-05-28 12:21:27.710 20961-20961/? A/DEBUG: Time: 2022-05-28 12:21:27
2022-05-28 12:21:27.710 20961-20961/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2022-05-28 12:21:27.710 20961-20961/? A/DEBUG: Build fingerprint: 'vivo/1901/1901:11/RP1A.200720.012/compiler0218164247:user/release-keys'
2022-05-28 12:21:27.711 20961-20961/? A/DEBUG: Revision: '0'
2022-05-28 12:21:27.711 20961-20961/? A/DEBUG: ABI: 'arm64'
2022-05-28 12:21:27.711 20961-20961/? A/DEBUG: Timestamp: 2022-05-28 12:21:27+0900
2022-05-28 12:21:27.711 20961-20961/? A/DEBUG: pid: 17581, tid: 17651, name: RenderThread 
2022-05-28 12:21:27.711 20961-20961/? A/DEBUG: uid: 10254
2022-05-28 12:21:27.711 20961-20961/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2022-05-28 12:21:27.712 20961-20961/? A/DEBUG: Abort message: 'drawRenderNode called on a context with no surface!'
2022-05-28 12:21:27.712 20961-20961/? A/DEBUG:     x0  0000000000000000  x1  00000000000044f3  x2  0000000000000006  x3  00000078d1d37220
2022-05-28 12:21:27.712 20961-20961/? A/DEBUG:     x4  00000078d1d36f4c  x5  00000078d1d36f4c  x6  00000078d1d36f4c  x7  0000000000000000
2022-05-28 12:21:27.712 20961-20961/? A/DEBUG:     x8  00000000000000f0  x9  00000079d25f1718  x10 ffffff80fffffbdf  x11 0000000000000001
2022-05-28 12:21:27.712 20961-20961/? A/DEBUG:     x12 000000000e4f8518  x13 0000000000000001  x14 0000000000030000  x15 00002352113b1cbc
2022-05-28 12:21:27.713 20961-20961/? A/DEBUG:     x16 00000079d26c3948  x17 00000079d26a2470  x18 00000078d1084000  x19 00000000000000ac
2022-05-28 12:21:27.713 20961-20961/? A/DEBUG:     x20 00000000000044ad  x21 00000000000000b2  x22 00000000000044f3  x23 00000000ffffffff
2022-05-28 12:21:27.713 20961-20961/? A/DEBUG:     x24 00000000000000e6  x25 0000000000000002  x26 b4000079d5e59340  x27 00000000ffffffff
2022-05-28 12:21:27.713 20961-20961/? A/DEBUG:     x28 000000794fc3b000  x29 00000078d1d372a0
2022-05-28 12:21:27.713 20961-20961/? A/DEBUG:     lr  00000079d265501c  sp  00000078d1d37200  pc  00000079d265504c  pst 0000000000000000
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG: backtrace:
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #00 pc 000000000008a04c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180) (BuildId: 0e42b7e3ae2ec29133fdbeea7227e56b)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #01 pc 00000000005675d8  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2320) (BuildId: d87c45932bb990f2f9827b991ffa059a)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #02 pc 0000000000013ab0  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+80) (BuildId: 6d398535cd6d9315930f056432520bb9)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #03 pc 0000000000006ec8  /system/lib64/liblog.so (__android_log_assert+336) (BuildId: dd2c72fa114d9fa74bb08255a471890e)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #04 pc 0000000000318214  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::getFrame()+52) (BuildId: 303264fc687e51b5c015f7358534e38c)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #05 pc 0000000000320e7c  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+188) (BuildId: 303264fc687e51b5c015f7358534e38c)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #06 pc 0000000000323570  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+480) (BuildId: 303264fc687e51b5c015f7358534e38c)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #07 pc 0000000000311eb4  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+220) (BuildId: 303264fc687e51b5c015f7358534e38c)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #08 pc 0000000000333500  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+88) (BuildId: 303264fc687e51b5c015f7358534e38c)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #09 pc 000000000001567c  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260) (BuildId: b81fad2b6b7b7f85c6217d2cb80c9e61)
2022-05-28 12:21:27.769 20961-20961/? A/DEBUG:       #10 pc 0000000000014f14  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412) (BuildId: b81fad2b6b7b7f85c6217d2cb80c9e61)
2022-05-28 12:21:27.770 20961-20961/? A/DEBUG:       #11 pc 00000000000ecd10  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 0e42b7e3ae2ec29133fdbeea7227e56b)
2022-05-28 12:21:27.770 20961-20961/? A/DEBUG:       #12 pc 000000000008c360  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 0e42b7e3ae2ec29133fdbeea7227e56b)
2022-05-28 12:21:27.857 3428-3624/? E/azqr: Phenotype API error. Event # cush@2954f9d2, EventCode: 5 [CONTEXT service_id=51 ]
```
</details>

**Comment by 0xZOne** [comment]
> Abort message: 'drawRenderNode called on a context with no surface!'

@chartreux yes, it is.  See https://github.com/flutter/engine/pull/33655 for more details.

**Comment by chinmaygarde** [comment]
The crash is in the Android framework. None of the stack frames are in the Flutter engine.
