### ISSUE TITLE
ProcessException: No such file or directory

### ISSUE THREAD

**Issue by hehawjq** [flutter/flutter#104596]
/Users/taoli-blue/Library/Developer/Xcode/DerivedData/Runner-fjqqglukmistzcemtudzjrvxvsvk/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/Script-9
                   740EEB61CF901F6004384FC.sh
               ♦ /Users/taoli-blue/fvm/versions/2.10.3/bin/flutter --verbose assemble --no-version-check
--output=/Users/taoli-blue/Downloads/flutter_taoli_app/build/ios/Debug-dev-iphoneos/
               -dTargetPlatform=ios -dTargetFile=/Users/taoli-blue/taoli/flutter_taoli_app/lib/main_dev.dart -dBuildMode=debug -dIosArchs=arm64
               -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -dSplitDebugInfo= -dTreeShakeIcons=false
               -dTrackWidgetCreation=true -dDartObfuscation= -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions=
               -dCodesignIdentity=21E6A88880ED32FA5B3525F5134308364DAB1434 debug_ios_bundle_flutter_assets
               Unhandled exception:
               ProcessException: No such file or directory
                 Command: /Users/taoli-blue/fvm/versions/2.10.3/bin/flutter --verbose assemble --no-version-check
                 --output=/Users/taoli-blue/Downloads/flutter_taoli_app/build/ios/Debug-dev-iphoneos/ -dTargetPlatform=ios
                 -dTargetFile=/Users/taoli-blue/taoli/flutter_taoli_app/lib/main_dev.dart -dBuildMode=debug -dIosArchs=arm64
                 -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -dSplitDebugInfo= -dTreeShakeIcons=false
                 -dTrackWidgetCreation=true -dDartObfuscation= -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions=
                 -dCodesignIdentity=21E6A88880ED32FA5B3525F5134308364DAB1434 debug_ios_bundle_flutter_assets
               #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
               #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
               #2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
               #3      Context.runSync (file:///Users/taoli-blue/fvm/versions/2.10.3/packages/flutter_tools/bin/xcode_backend.dart:92:42)
               #4      Context.buildApp (file:///Users/taoli-blue/fvm/versions/2.10.3/packages/flutter_tools/bin/xcode_backend.dart:448:34)
               #5      Context.run (file:///Users/taoli-blue/fvm/versions/2.10.3/packages/flutter_tools/bin/xcode_backend.dart:51:9)
               #6      main (file:///Users/taoli-blue/fvm/versions/2.10.3/packages/flutter_tools/bin/xcode_backend.dart:17:5)
               #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
               #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
               Command PhaseScriptExecution failed with a nonzero exit code
           
               /Users/taoli-blue/Downloads/flutter_taoli_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
of
               supported deployment target versions is 9.0 to 15.5.99. (in target 'UMDevice' from project 'Pods')
               /Users/taoli-blue/Downloads/flutter_taoli_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
of
               supported deployment target versions is 9.0 to 15.5.99. (in target 'UMCommon' from project 'Pods')
               /Users/taoli-blue/Downloads/flutter_taoli_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
of
               supported deployment target versions is 9.0 to 15.5.99. (in target 'JPush' from project 'Pods')
               /Users/taoli-blue/Downloads/flutter_taoli_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
of
               supported deployment target versions is 9.0 to 15.5.99. (in target 'JCore' from project 'Pods')
               warning: no rule to process file '/Users/taoli-blue/.pub-cache/hosted/pub.dartlang.org/record_mp3-3.0.0/ios/Classes/Fat-Lame/lib/libmp3lame.a' of type 'archive.ar'
for
               architecture 'arm64' (in target 'record_mp3' from project 'Pods')
               /Users/taoli-blue/Downloads/flutter_taoli_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
of
               supported deployment target versions is 9.0 to 15.5.99. (in target 'Reachability' from project 'Pods')
               /Users/taoli-blue/Downloads/flutter_taoli_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
of
               supported deployment target versions is 9.0 to 15.5.99. (in target 'FMDB' from project 'Pods')
               /Users/taoli-blue/Downloads/flutter_taoli_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
of
               supported deployment target versions is 9.0 to 15.5.99. (in target 'AppAuth' from project 'Pods')
           
               Result bundle written to path:
                /var/folders/fc/x8_69xsn1dq3p510xkhktqv00000gn/T/flutter_tools.8budVV/flutter_ios_build_temp_dirEQ6HCT/temporary_xcresult_bundle
           
           
[  +67 ms] Could not build the precompiled application for the device.
[  +37 ms] Error launching application on Blue iPhone.
[  +11 ms] "flutter run" took 19,867ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +259 ms] ensureAnalyticsSent: 255ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by darshankawar** [comment]
@hehawjq 
Can you provide `flutter doctor -v` ?
Are you getting this error while archiving or while running `flutter run` ?

Can you provide complete `flutter run -v` ? It'll be huge so you can put that in a text file and share it here.

Also, from the log you shared: you seem to have installed flutter using `fvm` : `/Users/taoli-blue/fvm/` Would you confirm if the same occurs without using `fvm` ?

Also from the log:

```
-dTargetFile=/Users/taoli-blue/taoli/flutter_taoli_app/lib/main_dev.dart -dBuildMode=debug -dIosArchs=arm64
               -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -dSplitDebugInfo= -dTreeShakeIcons=false
               -dTrackWidgetCreation=true -dDartObfuscation= -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions=
               -dCodesignIdentity=21E6A88880ED32FA5B3525F5134308364DAB1434 debug_ios_bundle_flutter_assets
               Unhandled exception:
               ProcessException: No such file or directory
```
the tool doesn't seem to find `lib/main_dev.dart` file. Does it exist ?

**Comment by hehawjq** [comment]
**[✓] Flutter (Channel stable, 2.10.3, on macOS 12.4 21F79 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 2.10.3 at /Users/taoli-blue/fvm/versions/2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 3731ea1c0c4dc4870443080606201eb14df3f51e • ios
      • iOS 14.7.1 18G82
    • Chrome (web)    • chrome                                   •
      web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available**

lib/main_dev.dart is exist，I am sure.

**Comment by hehawjq** [comment]
[log.txt](https://github.com/flutter/flutter/files/8770283/log.txt)
A detail log use for flutter run -v

**Comment by darshankawar** [comment]
> Are you getting this error while archiving or while running `flutter run` ?



> Also, from the log you shared: you seem to have installed flutter using `fvm` : `/Users/taoli-blue/fvm/` Would you confirm if the same occurs without using `fvm` ?

Also the error seems to be pointing to `main_dev` indicating flavors in your app. Does the same error occur if you remove flavor base ?

Also, sounds like a conflicting between flavor based configuration in your app and in xcode so I suggest you to try to confirm if you have correctly configured your flavors in build settings in XCode.

**Comment by hehawjq** [comment]
Thanks, I'll try
