### ISSUE TITLE
[Linux] Newly created linux project fails to build in VS Code 

### ISSUE THREAD

**Issue by sebastianhaberey** [flutter/flutter#104581]
## Steps to Reproduce

1. `flutter create --platforms=linux foo`
2. `cd foo`
3. `flutter build linux --debug`
4. VS Code 2022 > Menu > File > Open Folder > foo/linux 
5. Ctrl + Shift + P > CMake: Configure
6. Ctrl + Shift + P > CMake: Build

**Expected results:**

Build succeeds

**Actual results:** 

Build fails with `RangeError (index): Invalid value: Only valid value is 0: 1`

<details>
  <summary>Build log</summary>

  ```

  [main] Building folder: linux 
  [build] Starting build
  [proc] Executing command: /usr/bin/cmake --build /home/user/Projects/foo/linux/build --config Debug --target all --
  [build] [1/5  20% :: 0.166] Generating ../../flutter/ephemeral/libflutter_linux_gtk.so, ../../flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, ../../flutter/ephemeral/flutter_linux/fl_binary_codec.h, ../../flutter/ephemeral/flutter_linux/fl_binary_messenger.h, ../../flutter/ephemeral/flutter_linux/fl_dart_project.h, ../../flutter/ephemeral/flutter_linux/fl_engine.h, ../../flutter/ephemeral/flutter_linux/fl_json_message_codec.h, ../../flutter/ephemeral/flutter_linux/fl_json_method_codec.h, ../../flutter/ephemeral/flutter_linux/fl_message_codec.h, ../../flutter/ephemeral/flutter_linux/fl_method_call.h, ../../flutter/ephemeral/flutter_linux/fl_method_channel.h, ../../flutter/ephemeral/flutter_linux/fl_method_codec.h, ../../flutter/ephemeral/flutter_linux/fl_method_response.h, ../../flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, ../../flutter/ephemeral/flutter_linux/fl_plugin_registry.h, ../../flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, ../../flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, ../../flutter/ephemeral/flutter_linux/fl_string_codec.h, ../../flutter/ephemeral/flutter_linux/fl_value.h, ../../flutter/ephemeral/flutter_linux/fl_view.h, ../../flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
  [build] FAILED: ../flutter/ephemeral/libflutter_linux_gtk.so ../flutter/ephemeral/flutter_linux/fl_basic_message_channel.h ../flutter/ephemeral/flutter_linux/fl_binary_codec.h ../flutter/ephemeral/flutter_linux/fl_binary_messenger.h ../flutter/ephemeral/flutter_linux/fl_dart_project.h ../flutter/ephemeral/flutter_linux/fl_engine.h ../flutter/ephemeral/flutter_linux/fl_json_message_codec.h ../flutter/ephemeral/flutter_linux/fl_json_method_codec.h ../flutter/ephemeral/flutter_linux/fl_message_codec.h ../flutter/ephemeral/flutter_linux/fl_method_call.h ../flutter/ephemeral/flutter_linux/fl_method_channel.h ../flutter/ephemeral/flutter_linux/fl_method_codec.h ../flutter/ephemeral/flutter_linux/fl_method_response.h ../flutter/ephemeral/flutter_linux/fl_plugin_registrar.h ../flutter/ephemeral/flutter_linux/fl_plugin_registry.h ../flutter/ephemeral/flutter_linux/fl_standard_message_codec.h ../flutter/ephemeral/flutter_linux/fl_standard_method_codec.h ../flutter/ephemeral/flutter_linux/fl_string_codec.h ../flutter/ephemeral/flutter_linux/fl_value.h ../flutter/ephemeral/flutter_linux/fl_view.h ../flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_ 
  [build] cd /home/user/Projects/foo/linux/build/flutter && /usr/bin/cmake -E env FLUTTER_ROOT=/home/user/snap/flutter/common/flutter PROJECT_DIR=/home/user/Projects/foo DART_OBFUSCATION=false TRACK_WIDGET_CREATION=true TREE_SHAKE_ICONS=false PACKAGE_CONFIG=/home/user/Projects/foo/.dart_tool/package_config.json FLUTTER_TARGET=lib/main.dart /home/user/snap/flutter/common/flutter/packages/flutter_tools/bin/tool_backend.sh Debug
  [build] Unhandled exception:
  [build] RangeError (index): Invalid value: Only valid value is 0: 1
  [build] #0      _Array.[] (dart:core-patch/array.dart:10:36)
  [build] #1      main (file:///home/user/snap/flutter/common/flutter/packages/flutter_tools/bin/tool_backend.dart:12:37)
  [build] #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
  [build] #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
  [build] ninja: build stopped: subcommand failed.
  [build] Build finished with exit code 1

  ```

</details>

<details>
  <summary>Flutter doctor</summary>

  ```
  [✓] Flutter (Channel stable, 3.0.1, on Ubuntu 21.10 5.13.0-44-generic, locale en_US.UTF-8)
      • Flutter version 3.0.1 at /home/user/snap/flutter/common/flutter
      • Upstream repository https://github.com/flutter/flutter.git
      • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
      • Engine revision caaafc5604
      • Dart version 2.17.1
      • DevTools version 2.12.2
  
  [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
      • Android SDK at /home/user/Android/Sdk
      • Platform android-32, build-tools 32.1.0-rc1
      • Java binary at: /usr/local/android-studio/jre/bin/java
      • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
      • All Android licenses accepted.
  
  [✓] Chrome - develop for the web
      • Chrome at google-chrome
  
  [✓] Linux toolchain - develop for Linux desktop
      • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
      • cmake version 3.10.2
      • ninja version 1.8.2
      • pkg-config version 0.29.1
  
  [✓] Android Studio (version 2021.2)
      • Android Studio at /usr/local/android-studio
      • Flutter plugin version 67.1.2
      • Dart plugin version 212.5744
      • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
  
  [✓] VS Code (version 1.67.2)
      • VS Code at /usr/share/code
      • Flutter extension version 3.40.0
  
  [✓] Connected device (2 available)
      • Linux (desktop) • linux  • linux-x64      • Ubuntu 21.10 5.13.0-44-generic
      • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64
  
  [✓] HTTP Host Availability
      • All required HTTP hosts are available
  ```

</details>

**Comment by sebastianhaberey** [comment]
Don't forget that I may be doing this wrong, this is just how I _figured_ the workflow under Linux + VS Code might be.

**Comment by stuartmorgan** [comment]
No specific work was ever done to make directly driving `cmake` from an IDE work; the build was designed to be run from `flutter`. Currently `flutter` passes extra flags to the configure step, which would need to be restructured in order to make this workflow work.

Is there a specific reason you want to drive the build directly, or was this just something you tried because of the IDE prompts?

**Comment by sebastianhaberey** [comment]
Ah okay. My use case is I was planning to be working on the Linux desktop side of my plugin for the next days and I'd like to build and debug it from within the IDE. 

So if I understand you correctly I'd have to build using Flutter for now. I can live with that, but would I be able to debug within VS Code anyways?

**Comment by stuartmorgan** [comment]
I filed https://github.com/flutter/flutter/issues/104605 for documenting a workflow for that use case. We can leave this open specifically for the CMake aspect.

**Comment by stuartmorgan** [comment]
Adding
```
if(NOT FLUTTER_TARGET_PLATFORM)
    set(FLUTTER_TARGET_PLATFORM linux-x64)
endif()
```

to the top-level CMake will fix the specific error here. We need to validate that this doesn't cause an issues for the normal `flutter build`/`run` flow, but I wouldn't expect it to since we have separate output directories for each target arch. We'd also ideally want to make it default to the current arch, not x64, since this wouldn't work right on an ARM Linux machine.

That just gets us to a place where it builds and launches a blank app though, because of our use of the `install` step. We'd need to either:
- rework our local-run packaging not to be `install`-based, and figure out a different way of making sure the `rpath` is correct for everything and that all the plugins are in the right location, or
- provide, or at least document, custom run commands for popular editors like VS Code that would do the right extra things (like run `install` before launching, and launch the bundled version).
