### ISSUE TITLE
DropdownButton seems buggy when centered at bottom of screen, and isDense = true

### ISSUE THREAD

**Issue by g-regoz** [flutter/flutter#104678]
Tapping on a dropdown that has isDense set to True when its centered at the bottom center of the screen throws errors.  If you don't center the DroppdownButton, you don't get the error.  Also works OK as long as isDense is false.

## Steps to Reproduce
1. Execute `flutter run` on the code sample 

```
The following assertion was thrown during performLayout():
'package:flutter/src/material/dropdown.dart': Failed assertion: line 363 pos 16: 'menuLimits.top + menuLimits.height <= size.height': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///C:/Users/User/AndroidStudioProjects/FlutterProjects/startup_namer/lib/main.dart:70:19
When the exception was thrown, this was the stack: 
#2      _DropdownMenuRouteLayout.getPositionForChild.<anonymous closure> (package:flutter/src/material/dropdown.dart:363:16)
#3      _DropdownMenuRouteLayout.getPositionForChild (package:flutter/src/material/dropdown.dart:366:6)
#4      RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1363:41)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#6      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:318:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#19     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462:13)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#23     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749:15)
#24     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#25     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#26     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#27     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#28     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#29     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#30     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#31     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#35     _invoke (dart:ui/hooks.dart:151:10)
#36     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#37     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderCustomSingleChildLayoutBox#6705b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=480.0, h=642.4)
...  size: Size(480.0, 642.4)
RenderObject: RenderCustomSingleChildLayoutBox#6705b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(w=480.0, h=642.4)
  size: Size(480.0, 642.4)
...  child: RenderAnimatedOpacity#58a16 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=252.0, 0.0<=h<=546.4)
...    size: Size(252.0, 208.0)
...    opacity: AnimationController#1e5f9(▶ 0.000; for _DropdownRoute<String>)➩ProxyAnimation➩Interval(0.0⋯0.25)ₒₙ/Interval(0.75⋯1.0)
...    child: RenderCustomPaint#a0fec relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=252.0, 0.0<=h<=546.4)
...      size: Size(252.0, 208.0)
...      painter: _DropdownMenuPainter#c5891(AnimationController#1e5f9(▶ 0.000; for _DropdownRoute<String>)➩ProxyAnimation➩Interval(0.25⋯0.5)ₒₙ/Threshold)
...      child: RenderSemanticsAnnotations#f4304 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=252.0, 0.0<=h<=546.4)
...        size: Size(252.0, 208.0)
...        child: RenderClipPath#14ead relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=252.0, 0.0<=h<=546.4)
...          size: Size(252.0, 208.0)
```

```
```

```
flutter doctor -v
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19043.1706], locale en-US)
    • Flutter version 3.0.0 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31613.86
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • SM N975U1 (mobile) • RF8NA20GQZL • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows     • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)         • edge        • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @g-regoz, it looks like there's a similar issue addressing this in https://github.com/flutter/flutter/issues/104678. 

Kindly follow up there for more info. 

Closing from here as duplicate.

Thank you
