### ISSUE TITLE
Invalid argument(s): Type parameter TypeParameter(KeySet.T) is not indexed

### ISSUE THREAD

**Issue by xuzhongpeng** [flutter/flutter#104615]
## Steps to Reproduce

1. I build flutter engine for macos
```
./flutter/tools/gn --unoptimized --mac --mac-cpu=x64 --no-goma
./flutter/tools/gn --unoptimized
 ninja -C out/mac_debug_unopt &&  ninja -C out/host_debug_unopt
``` 
The compilation succeeds and the directory `host_debug_unopt`、`mac_debug_unopt`  is generated.

2. When I want to run with local engine it's crashed.
```
flutter run -d macOS --local-engine-src-path /Users/xxx/Desktop/myCode/flutter/flutter_engine/engine/src --local-engine=mac_debug_unopt
Launching lib/main.dart on macOS in debug mode...
Unhandled exception:
Invalid argument(s): Type parameter TypeParameter(KeySet.T) is not indexed
#0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:2927:8)
#1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2432:38)
#2      TypeParameterType.accept (package:kernel/ast.dart:11900:42)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#4      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:2271:5)
#5      BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:331:16)
#6      BinaryPrinter.writeVariableDeclarationList (package:kernel/binary/ast_to_binary.dart:2279:5)
#7      BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1483:5)
#8      FunctionNode.accept (package:kernel/ast.dart:3867:38)
#9      BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:437:10)
#10     BinaryPrinter.visitConstructor (package:kernel/binary/ast_to_binary.dart:1254:5)
#11     Constructor.accept (package:kernel/ast.dart:2488:40)
#12     BinaryPrinter.writeConstructorNode (package:kernel/binary/ast_to_binary.dart:486:10)
#13     BinaryPrinter.writeConstructorNodeList (package:kernel/binary/ast_to_binary.dart:385:7)
#14     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1220:5)
#15     Class.accept (package:kernel/ast.dart:1433:38)
#16     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:472:10)
#17     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:367:7)
#18     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1058:5)
#19     Library.accept (package:kernel/ast.dart:565:38)
#20     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:451:10)
#21     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:756:9)
#22     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:595:7)
#23     Timeline.timeSync (dart:developer/timeline.dart:157:22)
#24     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:577:14)
#25     IncrementalSerializer.serialize (package:front_end/src/fasta/incremental_serializer.dart:308:13)
#26     IncrementalSerializer.writePackagesToSinkAndTrimComponent (package:front_end/src/fasta/incremental_serializer.dart:158:24)
#27     FrontendCompiler.writeDillFile (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:727:29)
#28     FrontendCompiler.compile (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:604:13)
<asynchronous suspension>
#29     listenAndCompile.<anonymous closure> (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:1198:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Building macOS application...     
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel flutter-3.1-candidate.2, 3.1.0-0.0.pre.594, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.1.0-0.0.pre.594 at /Users/admin/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0ef3eceab0 (7 days ago), 2022-05-18 09:57:44 -0700
    • Engine revision 2b6125fb47
    • Dart version 2.18.0 (build 2.18.0-97.0.dev)
    • DevTools version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /usr/local/Caskroom/android-sdk/4333796
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.0 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/admin/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</detail>

**Comment by maheshmnj** [comment]
Hi @xuzhongpeng, Thanks for filing the issue.  I tried running the macOS app with the locally compiled engine and it the app built successfully. Please see the below logs. Also your flutter SDK doesn't seem to show the channel you are using, Can you try switching to master channel?

> Flutter (Channel flutter-3.1-candidate.2, 3.1.0-0.0.pre.594,

```
flutter channel master
flutter upgrade
```

#### logs
```
mahesh@Maheshs-MacBook-Air-M1 Desktop % mkdir engine
mahesh@Maheshs-MacBook-Air-M1 Desktop % cd engine 
mahesh@Maheshs-MacBook-Air-M1 engine % touch .gclient
mahesh@Maheshs-MacBook-Air-M1 engine % nano .gclient 
mahesh@Maheshs-MacBook-Air-M1 engine % source ~/.zshrc
mahesh@Maheshs-MacBook-Air-M1 engine % gclient sync
Updating depot_tools...

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress git@github.com:maheshmnj/engine.git /Users/mahesh/Desktop/engine/src/_gclient_flutter_f8iruphx' in '/Users/mahesh/Desktop/engine'
Cloning into '/Users/mahesh/Desktop/engine/src/_gclient_flutter_f8iruphx'...
remote: Enumerating objects: 282490, done.
remote: Total 282490 (delta 0), reused 0 (delta 0), pack-reused 282490
Receiving objects: 100% (282490/282490), 302.68 MiB | 6.11 MiB/s, done.
Resolving deltas: 100% (208389/208389), done.
Syncing projects: 100% (120/120), done.
Running hooks: 100% (10/10), done.                 
mahesh@Maheshs-MacBook-Air-M1 engine % ./flutter/tools/gn --unoptimized --mac --mac-cpu=x64 --no-goma
zsh: no such file or directory: ./flutter/tools/gn
mahesh@Maheshs-MacBook-Air-M1 engine % cd src/              
mahesh@Maheshs-MacBook-Air-M1 src % ./flutter/tools/gn --unoptimized --mac --mac-cpu=x64 --no-goma
Using prebuilt Dart SDK binary. If you are editing Dart sources and wish to compile the Dart SDK, set `--no-prebuilt-dart-sdk`.
Generating GN files in: out/mac_debug_unopt
Generating Xcode projects took 147ms
Generating compile_commands took 43ms
Done. Made 914 targets from 283 files in 2571ms
mahesh@Maheshs-MacBook-Air-M1 src % ./flutter/tools/gn --unoptimized
 ninja -C out/mac_debug_unopt &&  ninja -C out/host_debug_unopt
GOMA usage was specified but can't be found, falling back to local builds. Set the GOMA_DIR environment variable to fix GOMA.
Using prebuilt Dart SDK binary. If you are editing Dart sources and wish to compile the Dart SDK, set `--no-prebuilt-dart-sdk`.
Generating GN files in: out/host_debug_unopt
Generating Xcode projects took 134ms
Generating compile_commands took 45ms
Done. Made 914 targets from 283 files in 1192ms
ninja: Entering directory `out/mac_debug_unopt'
[4666/5879] ACTION //flutter/impeller/...aders(//build/toolchain/mac:clang_x64)
objc[33668]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x213772098) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e642c8). One of the two will be used. Which one is undefined.
objc[33668]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x2137720e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e64318). One of the two will be used. Which one is undefined.
objc[33668]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x213771eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e644f8). One of the two will be used. Which one is undefined.
objc[33668]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x213771f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e64548). One of the two will be used. Which one is undefined.
objc[33668]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x213771f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e64598). One of the two will be used. Which one is undefined.
objc[33668]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x213771fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e645e8). One of the two will be used. Which one is undefined.
objc[33668]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x213771ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e64638). One of the two will be used. Which one is undefined.
objc[33668]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x213772040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105e64688). One of the two will be used. Which one is undefined.
objc[33716]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x213772098) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107dc82c8). One of the two will be used. Which one is undefined.
objc[33716]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x2137720e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107dc8318). One of the two will be used. Which one is undefined.
objc[33716]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x213771eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107dc84f8). One of the two will be used. Which one is undefined.
objc[33716]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x213771f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107dc8548). One of the two will be used. Which one is undefined.
objc[33716]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x213771f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107dc8598). One of the two will be used. Which one is undefined.
objc[33716]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x213771fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107dc85e8). One of the two will be used. Which one is undefined.
objc[33716]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x213771ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107dc8638). One of the two will be used. Which one is undefined.
objc[33716]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x213772040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107dc8688). One of the two will be used. Which one is undefined.
[5879/5879] STAMP obj/default.stamp
ninja: Entering directory `out/host_debug_unopt'
[5879/5879] STAMP obj/default.stamp
mahesh@Maheshs-MacBook-Air-M1 ~ % cd ~/Desktop 
mahesh@Maheshs-MacBook-Air-M1 Desktop % cd newapp 
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter run -d macOS --local-engine-src-path ~/Desktop/engine/src --local-engine= ~/Desktop/engine/src/out/mac_debug_unopt
No Flutter engine build found at /Users/mahesh/Desktop/engine/src/host_out.
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter run -d macOS --local-engine-src-path ~/Desktop/engine/src --local-engine=~/Desktop/engine/src/out/mac_debug_unopt 
No Flutter engine build found at
/Users/mahesh/Desktop/engine/src/out/~/Desktop/engine/src/out/mac_debug_unopt.
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter run -d macOS --local-engine-src-path ~/Desktop/engine/src --local-engine ~/Desktop/engine/src/out/mac_debug_unopt
Running "flutter pub get" in newapp...                           2,784ms
Launching lib/main.dart on macOS in debug mode...
Warning: CocoaPods recommended version 1.11.0 or greater not installed.
Pods handling may fail on some projects involving plugins.
To upgrade see
https://guides.cocoapods.org/using/getting-started.html#installation for
instructions.



Running pod install...                                             763ms
objc[50388]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x213772098) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105ce82c8). One of the two will be used. Which one is undefined.
objc[50388]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x2137720e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105ce8318). One of the two will be used. Which one is undefined.
objc[50388]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x213771eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105ce84f8). One of the two will be used. Which one is undefined.
objc[50388]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x213771f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105ce8548). One of the two will be used. Which one is undefined.
objc[50388]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x213771f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105ce8598). One of the two will be used. Which one is undefined.
objc[50388]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x213771fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105ce85e8). One of the two will be used. Which one is undefined.
objc[50388]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x213771ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105ce8638). One of the two will be used. Which one is undefined.
objc[50388]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x213772040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105ce8688). One of the two will be used. Which one is undefined.
/Users/mahesh/Desktop/newapp/macos/Runner.xcodeproj: error: The linked framework 'Pods_Runner.framework' is missing one or more architectures required by this target: x86_64. (in target 'Runner' from project 'Runner')
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter clean
Cleaning Xcode workspace...                                      1,397ms
Cleaning Xcode workspace...                                      1,894ms
Deleting build...                                                  561ms
Deleting .dart_tool...                                             187ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting Flutter.podspec...                                          0ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter pub get
Running "flutter pub get" in newapp...                           1,678ms
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter run -d macOS --local-engine-src-path ~/Desktop/engine/src --local-engine ~/Desktop/engine/src/out/mac_debug_unopt
Launching lib/main.dart on macOS in debug mode...
Warning: CocoaPods recommended version 1.11.0 or greater not installed.
Pods handling may fail on some projects involving plugins.
To upgrade see
https://guides.cocoapods.org/using/getting-started.html#installation for
instructions.



Running pod install...                                             554ms
objc[50625]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x213772098) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1083ec2c8). One of the two will be used. Which one is undefined.
objc[50625]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x2137720e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1083ec318). One of the two will be used. Which one is undefined.
objc[50625]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x213771eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1083ec4f8). One of the two will be used. Which one is undefined.
objc[50625]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x213771f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1083ec548). One of the two will be used. Which one is undefined.
objc[50625]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x213771f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1083ec598). One of the two will be used. Which one is undefined.
objc[50625]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x213771fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1083ec5e8). One of the two will be used. Which one is undefined.
objc[50625]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x213771ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1083ec638). One of the two will be used. Which one is undefined.
objc[50625]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x213772040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1083ec688). One of the two will be used. Which one is undefined.
Building macOS application...                                           
Syncing files to device macOS...                                   181ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at:
http://127.0.0.1:65096/XCbwxmhcVhk=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:65096/XCbwxmhcVhk=/
```
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by xuzhongpeng** [comment]
> Hi @xuzhongpeng, Thanks for filing the issue. I tried running the macOS app with the locally compiled engine and it the app built successfully. Please see the below logs. Also your flutter SDK doesn't seem to show the channel you are using, Can you try switching to master channel?
> 
> > Flutter (Channel flutter-3.1-candidate.2, 3.1.0-0.0.pre.594,
> 
> ```
> flutter channel master
> flutter upgrade
> ```
> 
> #### logs
> logs
> flutter doctor -v (mac)

Thanks for your test.The problem goes away when I switch to stable.
