### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/mac/Library/Android/sdk/build-tools/31.0.0-rc5/aapt.

### ISSUE THREAD

**Issue by BugMonkey** [flutter/flutter#104799]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=6ebb6c1d --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/mac/Library/Android/sdk/build-tools/31.0.0-rc5/aapt.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:419:51)
#3      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:120:33)
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
<asynchronous suspension>
#5      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:598:34)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:541:54)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:368:31)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
```
```
[✓] Flutter (Channel stable, 1.20.1, on macOS 11.6.5 20G527, locale zh-Hans-CN)
    • Flutter version 1.20.1 at /Users/mac/Develop/environment/flutter
    • Framework revision 2ae34518b8 (1 year, 10 months ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://mirrors.sjtug.sjtu.edu.cn

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc5
    ✗ Android SDK file not found: /Users/mac/Library/Android/sdk/build-tools/31.0.0-rc5/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.3

[!] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • GM1900 (mobile)  • 6ebb6c1d                  • android-arm64 • Android 11 (API 30)
    • iPhonei (mobile) • 00008101-000478D93690001E • ios           • iOS 15.4.1

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: null
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: 840c9205b344a59e48a5926ee2d791cc5640924c
### Plugins
images_picker-0.0.9
video_player-0.10.12+5
video_player_web-0.1.4+1
flutter_ali_vod_upload

**Comment by danagbemava-nc** [comment]
Hi @BugMonkey, you appear to be on an older version of flutter. 

Kindly upgrade to the latest version of flutter to see if you still experience this issue. 

If you do, please provide the output of `flutter doctor -v`.

Thank you
