### ISSUE TITLE
NestedScrollView / Material3: _StretchController throws  the error: Build scheduled during frame

### ISSUE THREAD

**Issue by JoanSchi** [flutter/flutter#104798]
## Steps to Reproduce

Problem
If the NestedScrollView example from _api.flutter.dev_  is used with material3 the stretch controller throws a _**Build scheduled during frame**_  error. The error appears when the CustomScrollView is stretched  multiple times (pulled down).  I think the errors occurs when the dimension is changed and trigger applyNewDimensions -> BallisticScrollActivity, etc, etc,

Error:
Build scheduled during frame.
While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.
This might be because setState() was called from a layout or paint callback.

**Expected results:** 
It is expected that this standard code example runs without errors.

**Actual results:** 
If the error occurs the CustomScrollView cannot be stretched anymore until a complete rebuild of the widget. The components in the slivers are also not always completely visible after the error, I think the view is than still partly stretched. :)

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      title: _title,
      home: const MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final List<String> tabs = <String>['Tab 1', 'Tab 2'];
    return DefaultTabController(
      length: tabs.length, // This is the number of tabs.
      child: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            // These are the slivers that show up in the "outer" scroll view.
            return <Widget>[
              SliverOverlapAbsorber(
                // This widget takes the overlapping behavior of the SliverAppBar,
                // and redirects it to the SliverOverlapInjector below. If it is
                // missing, then it is possible for the nested "inner" scroll view
                // below to end up under the SliverAppBar even when the inner
                // scroll view thinks it has not been scrolled.
                // This is not necessary if the "headerSliverBuilder" only builds
                // widgets that do not overlap the next sliver.
                handle:
                    NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  title:
                      const Text('Books'), // This is the title in the app bar.
                  pinned: true,
                  expandedHeight: 150.0,
                  // The "forceElevated" property causes the SliverAppBar to show
                  // a shadow. The "innerBoxIsScrolled" parameter is true when the
                  // inner scroll view is scrolled beyond its "zero" point, i.e.
                  // when it appears to be scrolled below the SliverAppBar.
                  // Without this, there are cases where the shadow would appear
                  // or not appear inappropriately, because the SliverAppBar is
                  // not actually aware of the precise position of the inner
                  // scroll views.
                  forceElevated: innerBoxIsScrolled,
                  bottom: TabBar(
                    // These are the widgets to put in each tab in the tab bar.
                    tabs: tabs.map((String name) => Tab(text: name)).toList(),
                  ),
                ),
              ),
            ];
          },
          body: TabBarView(
            // These are the contents of the tab views, below the tabs.
            children: tabs.map((String name) {
              return SafeArea(
                top: false,
                bottom: false,
                child: Builder(
                  // This Builder is needed to provide a BuildContext that is
                  // "inside" the NestedScrollView, so that
                  // sliverOverlapAbsorberHandleFor() can find the
                  // NestedScrollView.
                  builder: (BuildContext context) {
                    return CustomScrollView(
                      // The "controller" and "primary" members should be left
                      // unset, so that the NestedScrollView can control this
                      // inner scroll view.
                      // If the "controller" property is set, then this scroll
                      // view will not be associated with the NestedScrollView.
                      // The PageStorageKey should be unique to this ScrollView;
                      // it allows the list to remember its scroll position when
                      // the tab view is not on the screen.
                      key: PageStorageKey<String>(name),
                      slivers: <Widget>[
                        SliverOverlapInjector(
                          // This is the flip side of the SliverOverlapAbsorber
                          // above.
                          handle:
                              NestedScrollView.sliverOverlapAbsorberHandleFor(
                                  context),
                        ),
                        SliverPadding(
                          padding: const EdgeInsets.all(8.0),
                          // In this example, the inner scroll view has
                          // fixed-height list items, hence the use of
                          // SliverFixedExtentList. However, one could use any
                          // sliver widget here, e.g. SliverList or SliverGrid.
                          sliver: SliverFixedExtentList(
                            // The items in this example are fixed to 48 pixels
                            // high. This matches the Material Design spec for
                            // ListTile widgets.
                            itemExtent: 48.0,
                            delegate: SliverChildBuilderDelegate(
                              (BuildContext context, int index) {
                                // This builder is called for each child.
                                // In this example, we just number each list item.
                                return ListTile(
                                  title: Text('Item $index'),
                                );
                              },
                              // The childCount of the SliverChildBuilderDelegate
                              // specifies how many children this inner list
                              // has. In this example, each tab has a list of
                              // exactly 30 items, but this is arbitrary.
                              childCount: 30,
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for _StretchController:
Build scheduled during frame.

While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.

This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.

When the exception was thrown, this was the stack
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure>
#1      WidgetsBinding._handleBuildScheduled
#2      BuildOwner.scheduleBuildFor
#3      Element.markNeedsBuild
#4      State.setState
#5      _AnimatedState._handleChange
#6      ChangeNotifier.notifyListeners
#7      AnimationLocalListenersMixin.notifyListeners
#8      AnimationController.value=
#9      AnimationController.forward
#10     _StretchController._recede
#11     _StretchController.scrollEnd
#12     _StretchingOverscrollIndicatorState._handleScrollNotification
#13     _NotificationElement.onNotification
#14     _NotificationNode.dispatchNotification
#15     _NotificationNode.dispatchNotification
#16     Element.dispatchNotification
#17     Notification.dispatch
#18     ScrollActivity.dispatchScrollEndNotification
#19     ScrollPosition.didEndScroll
#20     ScrollPosition.beginActivity
#21     _NestedInnerBallisticScrollActivity.applyNewDimensions
#22     ScrollPosition.applyNewDimensions
#23     _NestedScrollPosition.applyNewDimensions
#24     ScrollPosition.applyContentDimensions
#25     RenderViewport.performLayout
#26     RenderObject.layout
#27     RenderProxyBoxMixin.performLayout
#28     RenderObject.layout
#29     RenderProxyBoxMixin.performLayout
#30     RenderObject.layout
#31     RenderProxyBoxMixin.performLayout
#32     RenderObject.layout
#33     RenderProxyBoxMixin.performLayout
#34     RenderObject.layout
#35     RenderProxyBoxMixin.performLayout
#36     RenderObject.layout
#37     RenderProxyBoxMixin.performLayout
#38     RenderObject.layout
#39     RenderProxyBoxMixin.performLayout
#40     RenderObject.layout
#41     RenderProxyBoxMixin.performLayout
#42     _RenderCustomClip.performLayout
#43     RenderObject.layout
#44     RenderPadding.performLayout
#45     RenderObject.layout
#46     RenderProxyBoxMixin.performLayout
#47     RenderObject.layout
#48     RenderProxyBoxMixin.performLayout
#49     RenderObject.layout
#50     RenderSliverFixedExtentBoxAdaptor.performLayout
#51     RenderObject.layout
#52     RenderSliverEdgeInsetsPadding.performLayout
#53     _RenderSliverFractionalPadding.performLayout
#54     RenderObject.layout
#55     RenderViewportBase.layoutChildSequence
#56     RenderViewport._attemptLayout
#57     RenderViewport.performLayout
#58     RenderObject.layout
#59     RenderProxyBoxMixin.performLayout
#60     RenderObject.layout
#61     RenderProxyBoxMixin.performLayout
#62     RenderObject.layout
#63     RenderProxyBoxMixin.performLayout
#64     RenderObject.layout
#65     RenderProxyBoxMixin.performLayout
#66     RenderObject.layout
#67     RenderProxyBoxMixin.performLayout
#68     RenderObject.layout
#69     RenderProxyBoxMixin.performLayout
#70     RenderObject.layout
#71     RenderProxyBoxMixin.performLayout
#72     RenderObject.layout
#73     RenderProxyBoxMixin.performLayout
#74     _RenderCustomClip.performLayout
#75     RenderObject.layout
#76     RenderSliverFillRemainingWithScrollable.performLayout
#77     RenderObject.layout
#78     RenderViewportBase.layoutChildSequence
#79     RenderViewport._attemptLayout
#80     RenderViewport.performLayout
#81     RenderObject._layoutWithoutResize
#82     PipelineOwner.flushLayout
#83     RendererBinding.drawFrame
#84     WidgetsBinding.drawFrame
#85     RendererBinding._handlePersistentFrameCallback
#86     SchedulerBinding._invokeFrameCallback
#87     SchedulerBinding.handleDrawFrame
#88     SchedulerBinding._handleDrawFrame
#92     _invoke (dart:ui/hooks.dart:151:10)
#93     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#94     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
The _StretchController sending notification was: _StretchController()
════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing flutter_application_1...                                      

   info • Unused import: 'package:flutter/material.dart' • lib/test.dart:3:8 • unused_import
```

```
[✓] Flutter (Channel stable, 3.0.1, on openSUSE Leap 15.3 5.3.18-150300.59.68-default,
    locale en_US.UTF-8)
    • Flutter version 3.0.1 at /home/joan/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (7 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/joan/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/joan/App/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.0.1
    • cmake version 3.17.0
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/joan/App/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.57.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API
      32) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • openSUSE Leap 15.3
      5.3.18-150300.59.68-default
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome
      102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @JoanSchi, Thanks for filing the issue. I am able to reproduce the issue on the stable and master channels. When the scroll view is pulled down the error is reproduced. This error does not occur if `useMaterial3: false`


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.854, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.854 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ec20ea80ad (35 hours ago), 2022-05-21 16:28:06 -0400
    • Engine revision 1bfe551d6b
    • Dart version 2.18.0 (build 2.18.0-142.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

<details>
<summary>logs</summary>

```
Restarted application in 512ms.

════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for _StretchController:
Build scheduled during frame.

While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.

This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.

When the exception was thrown, this was the stack
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure>
#1      WidgetsBinding._handleBuildScheduled
#2      BuildOwner.scheduleBuildFor
#3      Element.markNeedsBuild
#4      State.setState
#5      _AnimatedState._handleChange
#6      ChangeNotifier.notifyListeners
#7      AnimationLocalListenersMixin.notifyListeners
#8      AnimationController.value=
#9      AnimationController.forward
#10     _StretchController._recede
#11     _StretchController.scrollEnd
#12     _StretchingOverscrollIndicatorState._handleScrollNotification
#13     _NotificationElement.onNotification
#14     _NotificationNode.dispatchNotification
#15     _NotificationNode.dispatchNotification
#16     Element.dispatchNotification
#17     Notification.dispatch
#18     ScrollActivity.dispatchScrollEndNotification
#19     ScrollPosition.didEndScroll
#20     ScrollPosition.beginActivity
#21     _NestedInnerBallisticScrollActivity.applyNewDimensions
#22     ScrollPosition.applyNewDimensions
#23     _NestedScrollPosition.applyNewDimensions
#24     ScrollPosition.applyContentDimensions
#25     RenderViewport.performLayout
#26     RenderObject.layout
#27     RenderBox.layout
#28     RenderProxyBoxMixin.performLayout
#29     RenderObject.layout
#30     RenderBox.layout
#31     RenderProxyBoxMixin.performLayout
#32     RenderObject.layout
#33     RenderBox.layout
#34     RenderProxyBoxMixin.performLayout
#35     RenderObject.layout
#36     RenderBox.layout
#37     RenderProxyBoxMixin.performLayout
#38     RenderObject.layout
#39     RenderBox.layout
#40     RenderProxyBoxMixin.performLayout
#41     RenderObject.layout
#42     RenderBox.layout
#43     RenderProxyBoxMixin.performLayout
#44     RenderObject.layout
#45     RenderBox.layout
#46     RenderProxyBoxMixin.performLayout
#47     RenderObject.layout
#48     RenderBox.layout
#49     RenderProxyBoxMixin.performLayout
#50     _RenderCustomClip.performLayout
#51     RenderObject.layout
#52     RenderBox.layout
#53     RenderPadding.performLayout
#54     RenderObject.layout
#55     RenderBox.layout
#56     RenderProxyBoxMixin.performLayout
#57     RenderObject.layout
#58     RenderBox.layout
#59     RenderProxyBoxMixin.performLayout
#60     RenderObject.layout
#61     RenderBox.layout
#62     RenderSliverFixedExtentBoxAdaptor.performLayout
#63     RenderObject.layout
#64     RenderSliverEdgeInsetsPadding.performLayout
#65     _RenderSliverFractionalPadding.performLayout
#66     RenderObject.layout
#67     RenderViewportBase.layoutChildSequence
#68     RenderViewport._attemptLayout
#69     RenderViewport.performLayout
#70     RenderObject.layout
#71     RenderBox.layout
#72     RenderProxyBoxMixin.performLayout
#73     RenderObject.layout
#74     RenderBox.layout
#75     RenderProxyBoxMixin.performLayout
#76     RenderObject.layout
#77     RenderBox.layout
#78     RenderProxyBoxMixin.performLayout
#79     RenderObject.layout
#80     RenderBox.layout
#81     RenderProxyBoxMixin.performLayout
#82     RenderObject.layout
#83     RenderBox.layout
#84     RenderProxyBoxMixin.performLayout
#85     RenderObject.layout
#86     RenderBox.layout
#87     RenderProxyBoxMixin.performLayout
#88     RenderObject.layout
#89     RenderBox.layout
#90     RenderProxyBoxMixin.performLayout
#91     RenderObject.layout
#92     RenderBox.layout
#93     RenderProxyBoxMixin.performLayout
#94     _RenderCustomClip.performLayout
#95     RenderObject.layout
#96     RenderBox.layout
#97     RenderSliverFillRemainingWithScrollable.performLayout
#98     RenderObject.layout
#99     RenderViewportBase.layoutChildSequence
#100    RenderViewport._attemptLayout
#101    RenderViewport.performLayout
#102    RenderObject._layoutWithoutResize
#103    PipelineOwner.flushLayout
#104    RendererBinding.drawFrame
#105    WidgetsBinding.drawFrame
#106    RendererBinding._handlePersistentFrameCallback
#107    SchedulerBinding._invokeFrameCallback
#108    SchedulerBinding.handleDrawFrame
#109    SchedulerBinding._handleDrawFrame
#110    _invoke (dart:ui/hooks.dart:148:13)
#111    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#112    _drawFrame (dart:ui/hooks.dart:115:31)
The _StretchController sending notification was: _StretchController()
════════════════════════════════════════════════════════════════════════════════
Application finished.
Exited

```

</details>

**Comment by trymnilsen** [comment]
Did some quick snooping. The error seems to be because an animation is started and this causes a call to setState in `AnimatedWidget`. The animation is started in the `_StretchController` in it's [_recede](https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/overscroll_indicator.dart#L499) method because it in turn is called by `scrollEnd` because a notification is received. The notification is indeed sent in `applyContentDimensions`.  Which is invoked in the [applyContentDimensions](https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/scroll_position.dart#L557) method.

So far we have just been backtracking but it seems like we are indeed starting an animation that causes a setState call while we are performing layout (as we can see by the stacktrace). But if we look at the lines below where we call `applyNewDimensions` it seems like this has been an issue or delt with before.

```
...
    assert(haveDimensions);
    if (_pendingDimensions) {
      applyNewDimensions();
      _pendingDimensions = false;
    }
    assert(!_didChangeViewportDimensionOrReceiveCorrection, 'Use correctForNewDimensions() (and return true) to change the scroll offset during applyContentDimensions().');

    if (_isMetricsChanged()) {
      // It isn't safe to trigger the ScrollMetricsNotification if we are in
      // the middle of rendering the frame, the developer is likely to schedule
      // a new frame(build scheduled during frame is illegal).
      if (!_haveScheduledUpdateNotification) {
        scheduleMicrotask(didUpdateScrollMetrics);
        _haveScheduledUpdateNotification = true;
      }
      _lastMetrics = copyWith();
    }
...
```

Here we send the `didUpdateScrollMetrics` notification in its own `scheduleMicrotask` avoid the chance that it will be sent during layout. @Piinks I see that you worked a bit on the overscroll_indicator code, do you think it would make sense to move the call to [_recede](https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/overscroll_indicator.dart#L499) into a scheduleMicrotask as well to avoid calling it during layout?

**Comment by JoanSchi** [comment]
The scheduleMicrotask, got me thinking again. BallisticScrollActivity doesn't use or is triggered in a scheduleMicrotask a far I know .

If the renderviewport performs a layout  and triggers applyContentDimensions in ScrollPosition (offset) than eventually BallisticScrollActivity is called during the layout. The BallisticScrollActivity is not wrapped in a scheduleMicrotask, and is probably causing the error.  Maybe if ballisticScrollActivity is scheduled in a microtask when a new dimension is applied (initiated by the stretch controller, or maybe a fancy animation which change the dimension) could solves the issue?  

```
#80     RenderViewport.performLayout
package:flutter/…/rendering/viewport.dart:1489

do {
      assert(offset.pixels != null);
      correction = _attemptLayout(mainAxisExtent, crossAxisExtent, offset.pixels + centerOffsetAdjustment);
      if (correction != 0.0) {
        offset.correctBy(correction);
      } else {
        if (offset.applyContentDimensions(
              math.min(0.0, _minScrollExtent + mainAxisExtent * anchor),
              math.max(0.0, _maxScrollExtent - mainAxisExtent * (1.0 - anchor)),
           ))
          break;
      }
      count += 1;
    }



class BallisticScrollActivity extends ScrollActivity {
  /// Creates an activity that animates a scroll view based on a [simulation].
  ///
  /// The [delegate], [simulation], and [vsync] arguments must not be null.
  BallisticScrollActivity(
    ScrollActivityDelegate delegate,
    Simulation simulation,
    TickerProvider vsync,
  ) : super(delegate) {
    _controller = AnimationController.unbounded(
      debugLabel: kDebugMode ? objectRuntimeType(this, 'BallisticScrollActivity') : null,
      vsync: vsync,
    )
      ..addListener(_tick)
      ..animateWith(simulation)
       .whenComplete(_end); // won't trigger if we dispose _controller first
  }
```

**Comment by Mayb3Nots** [comment]
Hi I believe I opened this issue months before this did here #100967. Going to close mine since this one is more recent and active

**Comment by JoanSchi** [comment]
Hi,

I made a temporal fix, by scheduling the applydimension in a scheduleMicrotask:
 
https://github.com/JoanSchi/nested_scroll_view_3m

It is a package with the example above included, but the only file you need is:

[nested_scroll_view_3m.dart](https://github.com/JoanSchi/nested_scroll_view_3m/blob/main/lib/nested_scroll_view_3m.dart) 

In the example  NestedScrollView should be changed  in  NestedScrollView3M (3x).

I hope this helps :)

**Comment by JoanSchi** [comment]
Update:

With issue [#118145](https://github.com/flutter/flutter/issues/118145) the overscroll of material 3 for android shows a unexpected behavior.  After stretch of a short list the view is jumping up and down. Maybe this is a trigger of this issue #104798.

[#118145](https://github.com/flutter/flutter/issues/118145)  is also only an android issue, is this also only a android issue?   

I do not have iOS ,so I can not test it.

**Comment by Piinks** [comment]
> With issue https://github.com/flutter/flutter/issues/118145 the overscroll of material 3 for android shows a unexpected behavior. After stretch of a short list the view is jumping up and down. Maybe this is a trigger of this issue https://github.com/flutter/flutter/issues/104798.

That sounds like a separate issue, and potentially a regression. Can you file a new issue with a reproduction of the bug you are seeing @JoanSchi?

**Comment by Piinks** [comment]
Oh I see you filed https://github.com/flutter/flutter/issues/118145, let's follow up there

**Comment by MichaelSowah** [comment]
Any updates on this issue?

**Comment by rakshit2k18** [comment]
Any update I am  facing same issue while using Nestedscrollview it throwing build error

**Comment by zeddyyz** [comment]
I face this issue using NestedScrollView as well as @rakshit2k18 
I can confirm that this issue exists only on Android. It is smooth on iOS.

**Comment by EDeLeon9** [comment]
I refused to disable material 3 for the whole app, so I used Theme() widget to disable it in CustomScrollView, and enable it in the sliver:
`...
Theme(
    data: Theme.of(context).copyWith(useMaterial3: false),
    child: CustomScrollView(
    slivers: [
        SliverOverlapInjector(handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context)),
        Theme(
            data: Theme.of(context),
            child: SliverPadding( ...`

**Comment by JoanSchi** [comment]
Material 3 with GlowingOverscrollIndicator.

If you like to use material 3 without StretchingOverscrollIndicator, you can extent MaterialScrollBehavior and override buildOverscrollIndicator and choose GlowingOverscrollIndicator. Use ScrollConfiguration to implement the behavior.  :)

```
class AdjustedScrollConfiguration extends StatelessWidget {
  final Widget child;

  const AdjustedScrollConfiguration({super.key, required this.child});

  @override
  Widget build(BuildContext context) {
    return ScrollConfiguration(
      behavior: MyMaterialScrollBehavior(),
      child: child,
    );
  }
}

class MyMaterialScrollBehavior extends MaterialScrollBehavior {
  @override
  Widget buildOverscrollIndicator(
      BuildContext context, Widget child, ScrollableDetails details) {
    switch (getPlatform(context)) {
      case TargetPlatform.iOS:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        return child;
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        return GlowingOverscrollIndicator(
          axisDirection: details.direction,
          color: Theme.of(context).colorScheme.secondary,
          child: child,
        );
    }
  }
}

```

**Comment by hagen00** [comment]
I'm experiencing the same problem on 3.13.0. 

Using `3.10.6` the the below, works! 
```
ThemeData(
        useMaterial3: true,
```
 
When I upgrade to `3.13.0` it stops working and `NestedScrollView` with `headerSliverBuilder` no longer scroll. This happens on an actual device and emulator. Downgrading to 3.10.6 fixes the problem.

**Comment by ZyrusLeo** [comment]
I prevented the error from occurring by using
scrollPhysics: const AlwaysScrollableScrollPhysics(),

**Comment by nbnD** [comment]
Getting same thing in SingleChildScrollView only in android app.

**Comment by khaven** [comment]
Any updates?

**Comment by Piinks** [comment]
Per our wiki on [issue hygiene](https://github.com/flutter/flutter/tree/master/docs/contributing/issue_hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-issues-or-prs):

> Do not add "me too" or "same" or "is there an update" comments to issues or PRs

Continued posts like this are not constructive and will result in restrictions to make further comments in this repository.

**Comment by victorsanni** [comment]
Workaround [here](https://github.com/flutter/flutter/issues/104798#issuecomment-1950787631)

**Comment by muhammadkamel** [comment]
Hi @Piinks 

Any updates?
