### ISSUE TITLE
`TabBarView` may throw out when work with `LayoutBuilder`

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#104994]
### Code 1
```dart
import 'package:flutter/material.dart';

List<String> tabTextContent = <String>[];
void main() => runApp(MaterialApp(
      home: StatefulBuilder(
        builder: (BuildContext context, StateSetter setState) {
          return DefaultTabController(
            length: tabTextContent.length,
            child: Scaffold(
              appBar: AppBar(
                title: const Text('Default TabBar Preview'),
                bottom: tabTextContent.isNotEmpty
                    ? TabBar(
                        isScrollable: true,
                        tabs: tabTextContent
                            .map((String textContent) => Tab(text: textContent))
                            .toList(),
                      )
                    : null,
              ),
              body: LayoutBuilder(
                builder: (_, __) {
                  return tabTextContent.isNotEmpty
                      ? TabBarView(
                          children: tabTextContent
                              .map((String textContent) =>
                                  Tab(text: "$textContent's view"))
                              .toList(),
                        )
                      : const Center(
                          child: Text('No tabs'),
                        );
                },
              ),
              bottomNavigationBar: BottomAppBar(
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    IconButton(
                      key: const Key('Add tab'),
                      icon: const Icon(Icons.add),
                      onPressed: () {
                        setState(() {
                          tabTextContent = List<String>.from(tabTextContent)
                            ..add('Tab ${tabTextContent.length + 1}');
                        });
                      },
                    ),
                    IconButton(
                      key: const Key('Delete tab'),
                      icon: const Icon(Icons.delete),
                      onPressed: () {
                        setState(() {
                          tabTextContent = List<String>.from(tabTextContent)
                            ..removeLast();
                        });
                      },
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    ));
```

### Code 2
```dart
import 'package:flutter/material.dart';

List<String> tabTextContent = <String>[];
void main() => runApp(MaterialApp(
      home: StatefulBuilder(
        builder: (BuildContext context, StateSetter setState) {
          return DefaultTabController(
            length: tabTextContent.length,
            child: Scaffold(
              extendBodyBehindAppBar: true,
              appBar: AppBar(
                title: const Text('Default TabBar Preview'),
                bottom: tabTextContent.isNotEmpty
                    ? TabBar(
                        isScrollable: true,
                        tabs: tabTextContent
                            .map((String textContent) => Tab(text: textContent))
                            .toList(),
                      )
                    : null,
              ),
              body: tabTextContent.isNotEmpty
                  ? TabBarView(
                      children: tabTextContent
                          .map((String textContent) =>
                              Tab(text: "$textContent's view"))
                          .toList(),
                    )
                  : const Center(
                      child: Text('No tabs'),
                    ),
              bottomNavigationBar: BottomAppBar(
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    IconButton(
                      key: const Key('Add tab'),
                      icon: const Icon(Icons.add),
                      onPressed: () {
                        setState(() {
                          tabTextContent = List<String>.from(tabTextContent)
                            ..add('Tab ${tabTextContent.length + 1}');
                        });
                      },
                    ),
                    IconButton(
                      key: const Key('Delete tab'),
                      icon: const Icon(Icons.delete),
                      onPressed: () {
                        setState(() {
                          tabTextContent = List<String>.from(tabTextContent)
                            ..removeLast();
                        });
                      },
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    ));
```

### Steps
1, Run the code 1 or 2, both are ok
2, Tap the add icon to add a tab view
2, Tap the recycle icon to del a tab view

Then the framework will throw out,

```dart
======== Exception caught by widgets library =======================================================
The following assertion was thrown building TabBarView(dirty, dependencies: [_TabControllerScope], state: _TabBarViewState#f654a):
Controller's length property (0) does not match the number of tabs (1) present in TabBar's tabs property.

The relevant error-causing widget was: 
  TabBarView TabBarView:file:///D:/My%20Documents/Desktop/untitled/lib/main.dart:24:21
When the exception was thrown, this was the stack: 
#0      _TabBarViewState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:1557:9)
#1      _TabBarViewState.build (package:flutter/src/material/tabs.dart:1563:6)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4975:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4861:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5033:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4587:5)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1172:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1101:9)
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1012:5)
#12     _invoke (dart:ui/hooks.dart:148:13)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#14     _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================
```

**Comment by exaby73** [comment]
I am able to reproduce this in stable and master channels. I got the following error on adding 2 tabs (tapping the add button twice in OP's code sample):

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building TabBarView(dirty, dependencies: [_TabControllerScope],
state: _TabBarViewState#c0153):
Controller's length property (2) does not match the number of tabs (1) present in TabBar's tabs
property.

The relevant error-causing widget was:
  TabBarView TabBarView:file:///Users/nabeelparkar/dev/nevercode/issue_104994/lib/main.dart:26:27

When the exception was thrown, this was the stack:
#0      _TabBarViewState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:1557:9)
#1      _TabBarViewState.build (package:flutter/src/material/tabs.dart:1563:6)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4975:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4861:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5033:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4587:5)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1172:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1101:9)
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1012:5)
#12     _invoke (dart:ui/hooks.dart:148:13)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#14     _drawFrame (dart:ui/hooks.dart:115:31)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

List<String> tabTextContent = <String>[];
void main() => runApp(
      MaterialApp(
        home: StatefulBuilder(
          builder: (BuildContext context, StateSetter setState) {
            return DefaultTabController(
              length: tabTextContent.length,
              child: Scaffold(
                appBar: AppBar(
                  title: const Text('Default TabBar Preview'),
                  bottom: tabTextContent.isNotEmpty
                      ? TabBar(
                          isScrollable: true,
                          tabs: tabTextContent
                              .map((String textContent) =>
                                  Tab(text: textContent))
                              .toList(),
                        )
                      : null,
                ),
                body: LayoutBuilder(
                  builder: (_, __) {
                    return tabTextContent.isNotEmpty
                        ? TabBarView(
                            children: tabTextContent
                                .map((String textContent) =>
                                    Tab(text: "$textContent's view"))
                                .toList(),
                          )
                        : const Center(
                            child: Text('No tabs'),
                          );
                  },
                ),
                bottomNavigationBar: BottomAppBar(
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: <Widget>[
                      IconButton(
                        key: const Key('Add tab'),
                        icon: const Icon(Icons.add),
                        onPressed: () {
                          setState(() {
                            tabTextContent = List<String>.from(tabTextContent)
                              ..add('Tab ${tabTextContent.length + 1}');
                          });
                        },
                      ),
                      IconButton(
                        key: const Key('Delete tab'),
                        icon: const Icon(Icons.delete),
                        onPressed: () {
                          setState(() {
                            tabTextContent = List<String>.from(tabTextContent)
                              ..removeLast();
                          });
                        },
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
```

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.1 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (11 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1014, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1014 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 08e61c3be2 (2 hours ago), 2022-05-31 00:18:09 -0400
    • Engine revision 693f95391e
    • Dart version 2.18.0 (build 2.18.0-152.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
