### ISSUE TITLE
[WEB] Text editing IME inconsistency

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#104944]
I was doing some recent manual verification of Super Editor editing on Web via IME. I started receiving error logs like the following:

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text_editing/text_editing.dart:431:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
    at Object.throw_ [as throw] (http://localhost:62307/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:62307/dart_sdk.js:5005:15)
    at Object._replace (http://localhost:62307/dart_sdk.js:192844:105)
    at Function.inferDeltaState (http://localhost:62307/dart_sdk.js:185414:38)
    at _engine.GloballyPositionedTextEditingStrategy.new.handleChange (http://localhost:62307/dart_sdk.js:178091:66)
    at Object._checkAndCall (http://localhost:62307/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:62307/dart_sdk.js:5284:17)
    at HTMLTextAreaElement.<anonymous> (http://localhost:62307/dart_sdk.js:109003:100)
```

The error indicates some kind of replacement range mismatch, but the stack trace doesn't help me root-cause the problem. I don't know if this is a range issue that Super Editor is causing, or if there's a legitimate IME bug on Web.

I don't have a precise set of reproduction steps, but generally speaking, if I enter a compound character like ü, delete it, and then continue typing and deleting, I'll trigger the above situation.

I haven't seen this issue when making similar changes on Mac desktop.

Flutter version:
```
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (10 days ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2
```

**Comment by matthew-carroll** [comment]
CC @justinmc

**Comment by darshankawar** [comment]
I was able to replicate this error while running `super_editor` example on web and playing around the compound char as mentioned above and while inserting and deleting the text.

<details>
<summary> error console log </summary>

```

(53.546) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor
change
(53.547) ExampleApp > FINE: Anchor is non-null: Offset(614.4, 534.0), child:
ValueListenableBuilder<DocumentSelection?>
(53.548) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "707c548c-aad0-430b-81b6-a87d60bd762f",
  position: (TextNodePosition(offset: 72, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "707c548c-aad0-430b-81b6-a87d60bd762f",
  position: (TextNodePosition(offset: 4, affinity: TextAffinity.downstream)))
Error: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text_editing/text_editing
.dart:431:10
replacedRange.start <= originalText.length && replacedRange.end <=
originalText.length
is not true
    at Object.throw_ [as throw] (http://localhost:50986/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:50986/dart_sdk.js:5005:15)
    at Object._replace (http://localhost:50986/dart_sdk.js:192844:105)
    at Function.inferDeltaState (http://localhost:50986/dart_sdk.js:185414:38)
    at _engine.GloballyPositionedTextEditingStrategy.new.handleChange
    (http://localhost:50986/dart_sdk.js:178091:66)
    at Object._checkAndCall (http://localhost:50986/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:50986/dart_sdk.js:5284:17)
    at HTMLDocument.<anonymous> (http://localhost:50986/dart_sdk.js:109003:100)
Error: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text_editing/text_editing
.dart:431:10
replacedRange.start <= originalText.length && replacedRange.end <=
originalText.length
is not true
    at Object.throw_ [as throw] (http://localhost:50986/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:50986/dart_sdk.js:5005:15)
    at Object._replace (http://localhost:50986/dart_sdk.js:192844:105)
    at Function.inferDeltaState (http://localhost:50986/dart_sdk.js:185414:38)
    at _engine.GloballyPositionedTextEditingStrategy.new.handleChange
    (http://localhost:50986/dart_sdk.js:178091:66)
    at Object._checkAndCall (http://localhost:50986/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:50986/dart_sdk.js:5284:17)
    at HTMLDocument.<anonymous> (http://localhost:50986/dart_sdk.js:109003:100)
Error: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text_editing/text_editing
.dart:431:10
replacedRange.start <= originalText.length && replacedRange.end <=
originalText.length
is not true
    at Object.throw_ [as throw] (http://localhost:50986/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:50986/dart_sdk.js:5005:15)
    at Object._replace (http://localhost:50986/dart_sdk.js:192844:105)
    at Function.inferDeltaState (http://localhost:50986/dart_sdk.js:185414:38)
    at _engine.GloballyPositionedTextEditingStrategy.new.handleChange
    (http://localhost:50986/dart_sdk.js:178091:66)
    at Object._checkAndCall (http://localhost:50986/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:50986/dart_sdk.js:5284:17)
    at HTMLDocument.<anonymous> (http://localhost:50986/dart_sdk.js:109003:100)
Error: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text_editing/text_editing
.dart:431:10
replacedRange.start <= originalText.length && replacedRange.end <=
originalText.length
is not true
    at Object.throw_ [as throw] (http://localhost:50986/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:50986/dart_sdk.js:5005:15)
    at Object._replace (http://localhost:50986/dart_sdk.js:192844:105)
    at Function.inferDeltaState (http://localhost:50986/dart_sdk.js:185414:38)
    at _engine.GloballyPositionedTextEditingStrategy.new.handleChange
    (http://localhost:50986/dart_sdk.js:178091:66)
    at Object._checkAndCall (http://localhost:50986/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:50986/dart_sdk.js:5284:17)
    at HTMLDocument.<anonymous> (http://localhost:50986/dart_sdk.js:109003:100)

    ```

    </details>

**Comment by matthew-carroll** [comment]
This issue came up as I was trying to use IME on web. We haven't published that release yet. We'll need to resolve this before doing so.

**Comment by zbjumper** [comment]
+1

**Comment by louisifn** [comment]
+1
