### ISSUE TITLE
Cannot create or run existing flutter project

### ISSUE THREAD

**Issue by Shery573** [flutter/flutter#105227]
Unabl to run existing flutter projects and can't create a new one
This is what I get when running flutter doctor

```
`[☠] Flutter (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Could not determine engine revision.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      Cache.engineRevision (package:flutter_tools/src/cache.dart:447:7)
      #2      FlutterVersion.engineRevision
      (package:flutter_tools/src/version.dart:152:46)
      #3      FlutterVersion.engineRevisionShort
      (package:flutter_tools/src/version.dart:153:55)
      #4      FlutterValidator.validate
      (package:flutter_tools/src/doctor.dart:458:75)
      #5      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #6      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #7      _rootRun (dart:async/zone.dart:1426:13)
      #8      _CustomZone.run (dart:async/zone.dart:1328:19)
      #9      _runZoned (dart:async/zone.dart:1861:10)
      #10     runZonedGuarded (dart:async/zone.dart:1849:12)
      #11     runZoned (dart:async/zone.dart:1780:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:205:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #15     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:48)
      #16     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #17     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #18     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #19     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #20     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #21     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #23     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #25     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/sheheryartariq/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.`
```

**Comment by darshankawar** [comment]
https://github.com/flutter/flutter/blob/1a7a766de5937cd66a8f32834d5879cdcf95c9c3/packages/flutter_tools/lib/src/flutter_cache.dart#L447

https://github.com/flutter/flutter/blob/1a7a766de5937cd66a8f32834d5879cdcf95c9c3/packages/flutter_tools/lib/src/version.dart#L152

Looks like user does not have engine revision and seems to be on Mac. 

Could it be similar to https://github.com/flutter/flutter/issues/90092?

Labeling it for further insights from the team.

/cc @christopherfujino

**Comment by christopherfujino** [comment]
@Shery573 so your cache is in a bad state. I'm wondering, how did you get the Flutter SDK? (Did you download the prepackaged zip from the website? git clone from github? flutter upgrade from a previous version?)

In order to get back into a good state, you can delete your entire Flutter cache, which should be a command like (substitute your actual file path):

`rm -rf $FLUTTER_SDK/bin/cache`
