### ISSUE TITLE
update-excerpts failing to get base sha

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#105238]
example: https://github.com/flutter/packages/pull/2157/checks?check_run_id=6712967600

error:
```
./script/tool_runner.sh update-excerpts --fail-on-change
--packages-for-branch: running on changed packages
Unhandled exception:
ProcessException: fatal: Not a valid object name FETCH_HEAD
  Command: git merge-base FETCH_HEAD HEAD
#0      _throwIfProcessFailed (package:git/src/top_level.dart:39:5)
#1      runGit (package:git/src/top_level.dart:17:5)
<asynchronous suspension>
#2      GitVersionFinder.getBaseSha (package:flutter_plugin_tools/src/common/git_version_finder.dart:87:30)
<asynchronous suspension>
#3      PluginCommand._getAllPackages (package:flutter_plugin_tools/src/common/plugin_command.dart:336:30)
<asynchronous suspension>
#4      Stream.toList.<anonymous closure> (dart:async/stream.dart:1298:9)
<asynchronous suspension>

Exit status: 255
```

cc @stuartmorgan

**Comment by keyonghan** [comment]
This also blocks recipes repo: https://ci.chromium.org/ui/p/flutter/builders/try/recipes-with-led/b8812441723219190897/overview

**Comment by keyonghan** [comment]
Bumping to P0 as this is blocking multiple repos (https://github.com/flutter/packages/pull/2194, https://flutter-review.googlesource.com/c/recipes/+/30888).
