### ISSUE TITLE
Gradle threw an error while downloading artifacts from the network. Retrying to download.

### ISSUE THREAD

**Issue by Shiba-Kar** [flutter/flutter#105397]
```
 flutter create shiva
Creating project shiva...
Connection closed before full header was received
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Running "flutter pub get" in shiva...                              69.5s
Wrote 96 files.

All done!
In order to run your application, type:

  $ cd shiva
  $ flutter run

Your application code is in shiva\lib\main.dart.

PS C:\Users\shiva\OneDrive\Programming\OFFICE> cd shiva
PS C:\Users\shiva\OneDrive\Programming\OFFICE\shiva> flutter build apk --split-per-abi

💪 Building with sound null safety 💪

Exception in thread "main" java.net.SocketException: Connection reset by peer: socket write error
        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
        at java.base/sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
        at java.base/sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:89)
        at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:658)
        at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:525)
        at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:107)
        at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:232)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:443)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleRelease'...                            3.7s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception in thread "main" java.net.SocketException: Connection reset by peer: socket write error
        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
        at java.base/sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
        at java.base/sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:89)
        at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:658)
        at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:525)
        at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:107)
        at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:232)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:443)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleRelease'...                         1,724ms
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Gradle task assembleRelease failed with exit code 1
PS C:\Users\shiva\OneDrive\Programming\OFFICE\shiva> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.22621.1], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[✓] Android Studio (version 2021.2)
[✓] VS Code, 64-bit edition (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

**Comment by darshankawar** [comment]
> flutter build apk --split-per-abi

Is this only happening if you pass the argument `--split-per-abi` or occurs without it too ? 

Looking at the error, it could be happening if your ISP is blocking the connection. 

`Gradle threw an error while downloading artifacts from the network. Retrying to download...` This also indicates a network related issue, so can you try to be on a faster internet connection or a different network and see if it still persists or not ?

Also, there are several similar questions asked on StackOverflow that you may check and see if any of them helps to resolve the issue.

https://stackoverflow.com/questions/59587977/os-error-connection-reset-by-peer-errno-104-address-storage-googleapis-co

https://stackoverflow.com/questions/60042508/flutter-exception-in-thread-main-java-net-socketexception-connection-reset

also check [this](https://github.com/flutter/flutter/issues/30894) similar issue and see if it helps.

**Comment by Shiba-Kar** [comment]
Apparently I have a poor network  ``` cd android ; ./gradlew assembleDebug ``` helped a lot to get the resources !!.
