### ISSUE TITLE
Flutter -> package roll failure on windows: ProcessException: fatal: Not a valid object name FETCH_HEAD

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#105329]
Flutter -> package roll is failing on Windows: https://github.com/flutter/packages/pull/2198/checks?check_run_id=6729946236

When the plugin_tool tries to get the diff between local branch and master, it runs `merge-base', '--fork-point', 'FETCH_HEAD', 'HEAD'`: https://github.com/flutter/plugins/blob/main/script/tool/lib/src/common/git_version_finder.dart#L81-L83

```
--packages-for-branch: running on changed packages
Unhandled exception:
ProcessException: fatal: Not a valid object name FETCH_HEAD
  Command: git merge-base FETCH_HEAD HEAD
#0      _throwIfProcessFailed (package:git/src/top_level.dart:39:5)
#1      runGit (package:git/src/top_level.dart:17:5)
<asynchronous suspension>
#2      GitVersionFinder.getBaseSha (package:flutter_plugin_tools/src/common/git_version_finder.dart:87:30)
<asynchronous suspension>
#3      PluginCommand._getAllPackages (package:flutter_plugin_tools/src/common/plugin_command.dart:336:30)
<asynchronous suspension>
#4      Stream.toList.<anonymous closure> (dart:async/stream.dart:1292:9)
<asynchronous suspension>
```

**Comment by stuartmorgan** [comment]
This was fixed by https://github.com/flutter/packages/pull/2200
