### ISSUE TITLE
engine->flutter roller blocked on `test/integration.shard/test_test.dart`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#105340]
example: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20tool_integration_tests_3_4/11556/overview

**Comment by gaaclarke** [comment]
@alexmarkov can you verify that the change in the stacktrace is acceptable so we can just update the golden for that test?

cc @jason-simmons @zanderso

**Comment by jason-simmons** [comment]
Running this test with the new async implementation produces a much shorter stack trace for the "uncaught Future error" phase:
```
cd dev/automated_tests/flutter_test
flutter test exception_handling_test.dart
```

With the roll:
```
When the exception was thrown, this was the stack:
#2      main.<anonymous closure> (file:///usr/local/google/home/jsimmons/ssd/sky/flutter/dev/automated_tests/flutter_test/exception_handling_test.dart:16:5)
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:25)
#7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:831:5)
#9      Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:214:9)
#11     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:389:11)
(elided 5 frames from dart:async)
```

Before the roll:
```
When the exception was thrown, this was the stack:
#2      main.<anonymous closure> (file:///usr/local/google/home/jsimmons/ssd/sky/flutter/dev/automated_tests/flutter_test/exception_handling_test.dart:16:5)
#3      main.<anonymous closure> (file:///usr/local/google/home/jsimmons/ssd/sky/flutter/dev/automated_tests/flutter_test/exception_handling_test.dart:15:77)
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:0:0)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:841:19)
#13     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:820:14)
#14     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1247:24)
#15     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:182:54)
#20     withClock (package:clock/src/default.dart:48:10)
#21     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:182:22)
#26     FakeAsync.run (package:fake_async/fake_async.dart:182:7)
#27     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1244:15)
#28     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:164:24)
#29     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
#32     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:0:0)
#37     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:213:13)
#38     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:196:45)
#39     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:257:15)
#40     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:254:14)
#45     Invoker._waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:254:5)
#46     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:391:17)
#49     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:0:0)
#54     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:380:9)
#55     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:423:15)
#56     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:379:7)
#63     Invoker._onRun (package:test_api/src/backend/invoker.dart:378:11)
#64     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#65     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:273:16)
#70     RemoteListener._runLiveTest (package:test_api/src/backend/remote_listener.dart:272:5)
#71     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:220:7)
#89     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#90     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#92     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#118    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
#124    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
#125    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
#133    _Socket._onData (dart:io-patch/socket_patch.dart:2320:41)
#140    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1845:33)
#141    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
(elided 104 frames from dart:async, dart:async-patch, and package:stack_trace)
```

**Comment by gaaclarke** [comment]
Here is the golden for quick comparison: https://github.com/flutter/flutter/blob/master/dev/automated_tests/flutter_test/exception_handling_expectation.txt

Here is the new output:
```
00:42 +3 -1: flutter test should report nice errors for exceptions thrown within testWidgets() [E]                                    
  Expected: an object with length of a value greater than <63>
    Actual: [
              '\r00:00 +0: loading /Users/aaclarke/dev/flutter/dev/automated_tests/flutter_test/exception_handling_test.dart                                                                                            \r00:01 +0: loading /Users/aaclarke/dev/flutter/dev/automated_tests/flutter_test/exception_handling_test.dart                                                                                            \r00:02 +0: loading /Users/aaclarke/dev/flutter/dev/automated_tests/flutter_test/exception_handling_test.dart                                                                                            \r00:02 +0: Exception handling in test harness - string                                                                                                                                                  \r00:02 +0: Exception handling in test harness - string                                                                                                                                                  ',
              '══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════',
              'The following message was thrown running a test:',
              'Who lives, who dies, who tells your story?',
              '',
              'When the exception was thrown, this was the stack:',
              '#0      main.<anonymous closure> (file:///Users/aaclarke/dev/flutter/dev/automated_tests/flutter_test/exception_handling_test.dart:10:5)',
              '#1      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)',
              '<asynchronous suspension>',
              '<asynchronous suspension>',
              '(elided one frame from package:stack_trace)',
              '',
              'The test description was:',
              '  Exception handling in test harness - string',
              '════════════════════════════════════════════════════════════════════════════════════════════════════',
              '\r00:02 +0 -1: Exception handling in test harness - string [E]                                                                                                                                           ',
              '  Test failed. See exception logs above.',
              '  The test description was: Exception handling in test harness - string',
              '  ',
              '\r00:02 +0 -1: Exception handling in test harness - FlutterError                                                                                                                                         \r00:02 +0 -1: Exception handling in test harness - FlutterError                                                                                                                                         ',
              '══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════',
              'The following assertion was thrown running a test:',
              'Who lives, who dies, who tells your story?',
              '',
              ...
            ]
     Which: has length of <63>
  Failure in exception_handling to compare to ../../dev/automated_tests/flutter_test/exception_handling_expectation.txt
```
