### ISSUE TITLE
Exception: _debugLifecycleState was called on null

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#10549]
With lastest update to Flutter I've started getting exceptions thrown when switching between tabs with scroll views in them. I only get the exception when switching between two non-adjacent tabs. When switching between tabs next to each other everything is always fine.

If I'm doing something wrong, a more helpful error message would be great.

## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The getter '_debugLifecycleState' was called on null.
Receiver: null
Tried calling: _debugLifecycleState
When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1635:20)
#3      _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:143:12)
#4      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#6      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#8      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#9      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4412:16)
#10     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#12     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4312:14)
#14     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#15     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4312:14)
#16     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4312:14)
#18     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#20     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#22     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#24     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#26     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#28     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#30     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3418:14)
#32     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#33     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4312:14)
#34     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1638:13)
#35     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1647:7)
#36     Element.deactivateChild (package:flutter/src/widgets/framework.dart:2777:29)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2521:9)
#38     SliverMultiBoxAdaptorElement.removeChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:620:32)
#39     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2113:19)
#40     SliverMultiBoxAdaptorElement.removeChild (package:flutter/src/widgets/sliver.dart:616:11)
#41     RenderSliverMultiBoxAdaptor.collectGarbage.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:302:23)
#42     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2022:58)
#43     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1120:15)
#44     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2022:13)
#45     RenderSliverMultiBoxAdaptor.collectGarbage (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:300:5)
#46     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:134:9)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1926:7)
#48     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:248:13)
#49     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:882:12)
#50     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:806:20)
#51     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1803:7)
#52     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1098:18)
#53     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:251:19)
#54     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:504:22)
#55     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189:5)
#56     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:688:15)
#57     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:636:9)
#58     _drawFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:88)
The following RenderObject was being processed when the exception was fired:
  RenderSliverFillViewport#73680391 relayoutBoundary=up1 NEEDS-LAYOUT
  creator: SliverFillViewport ← Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#436933217] ←
  Listener ← _GestureSemantics ←
  RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#816117697] ← Scrollable ←
  NotificationListener<ScrollNotification> ← PageView ← NotificationListener<ScrollNotification> ←
  TabBarView ← ⋯
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle,
  scrollOffset: 640.0, remainingPaintExtent: 320.0, crossAxisExtent: 444.0, viewportMainAxisExtent:
  320.0)
  geometry: SliverGeometry(scrollExtent: 1920.0, paintExtent: 320.0, maxPaintExtent: 1920.0,
  hasVisualOverflow: true, scrollOffsetCorrection: 0.0)
  currently live children: 2 to 2
This RenderObject had the following descendants (showing up to depth 5):
  RenderRepaintBoundary#1073716361
    RenderSemanticsGestureHandler#318907156
      RenderPointerListener#580511158
        RenderIgnorePointer#389621311
          RenderViewport#865338495
════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision 1b56cb790c (7 hours ago), 2017-06-06 18:40:32 -0700
    • Engine revision 8686a45810
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2016.3.4)
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 14.0.0
    • Dart plugin version 163.13137
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected devices
    • iPhone SE • B19052F4-91FF-48C7-85B4-26C1D2D1A148 • ios • iOS 10.3 (simulator)
```

**Comment by eseidelGoogle** [comment]
Is this fallout from @HansMuller's pagestate changes?

**Comment by HansMuller** [comment]
I was unable to reproduce the problem with https://gist.github.com/HansMuller/e43fecb89706a0245e5b300352482012

I tried creating scroll controllers keepScrollOffset true/false, providing PageStorageKeys per scrollable or not, etc.

**Comment by HansMuller** [comment]
Aha. I have been able to reproduce the problem by adding a SliverAppBar (which has a SliverPersistentHeader widget) to each CustomScrollView.  The failure occurs if the custom scroll view has a ValueKey. It doesn't appear to have anything to do with PageStorage; investigating...
