### ISSUE TITLE
WidgetsBinding.instance.window.frameData.frameNumber throws in tests

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#105530]
```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('frameData', (WidgetTester tester) async {
    print(WidgetsBinding.instance.window.frameData.frameNumber);
  });
}
```

throws:

```
00:02 +0: frameData                                                                                                                                                                                       
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _TypeError was thrown running a test:
type 'Null' is not a subtype of type 'FrameData'

When the exception was thrown, this was the stack:
#0      TestWindow.frameData (dart:ui/window.dart:687:17)
#1      main.<anonymous closure> (file:///Users/dnfield/src/flutter/flutter.widgets/packages/visibility_detector/test/window_test.dart:6:42)
#2      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  frameData
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: frameData [E]                                                                                                                                                                                
  Test failed. See exception logs above.
  The test description was: frameData
  
00:02 +0 -1: Some tests failed.             
```

**Comment by dnfield** [comment]
This actually makes me wonder why frameData is getting delegated to PlatformDispatcher at all - it seems very window specific.

@goderbauer @gspencergoog might have more context

**Comment by dnfield** [comment]
I guess onBeginFrame is part of PD, and the idea is there's only a current frame and frame number for all windows.

**Comment by dnfield** [comment]
This is happening because `TestWindow` is handling `get_frameData` via `noSuchMethod`.

We can implement it and not throw, but should probably connect it up to the scheduler binding so that it gets the actual frame number.

**Comment by goderbauer** [comment]
Re-opening this since it got reverted.
