### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Illegal character in path: assetsF:\PROJECTS\ham-hub\assets\font

### ISSUE THREAD

**Issue by vectorcrop** [flutter/flutter#105520]
## Command
```
flutter --quiet assemble --no-version-check --depfile F:\PROJECTS\ham-hub\build\app\intermediates\flutter\debug/flutter_build.d --output F:\PROJECTS\ham-hub\build\app\intermediates\flutter\debug -dTargetFile=F:\PROJECTS\ham-hub\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Illegal character in path: assetsF:\PROJECTS\ham-hub\assets\font
```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1829:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2863:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2835:38)
#3      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:744:29)
#4      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:685:9)
#5      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:50:26)
<asynchronous suspension>
#7      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:64:34)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
<asynchronous suspension>
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:320:32)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.25120.1010], locale en-US)
    • Flutter version 3.0.1 at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\mhdss\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at C:\Users\mhdss\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Redmi 9T Note 9 4G 9 Power (mobile) • 20f65b500321 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)                   • windows      • windows-x64    • Microsoft Windows [Version 10.0.25120.1010]
    • Chrome (web)                        • chrome       • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)                          • edge         • web-javascript • Microsoft Edge 101.0.1210.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: fb57da5f945d02ef4f98dfd9409a72b7cce74268
### Plugins
file_picker-4.6.1
firebase_auth-3.3.19
firebase_auth_web-3.3.16
firebase_core-1.17.1
firebase_core_web-1.6.4
firebase_database-9.0.15
firebase_database_web-0.2.0+14
flutter_plugin_android_lifecycle-2.0.6
fluttertoast-8.0.9
google_sign_in-5.3.2
google_sign_in_android-5.2.8
google_sign_in_ios-5.3.1
google_sign_in_web-0.10.1+2
image_picker-0.8.5+3
image_picker_android-0.8.5
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+5

**Comment by huycozy** [comment]
Hi @vectorcrop
As I see your project name `ham-hub` is an invalid name which could be a reason you are getting the error. Try to rename it and see whether the error is fixed.
Closing this for now. If it's not fixed, write in comments and I'll reopen it.
