### ISSUE TITLE
Google Map Plugin Fatal Crash

### ISSUE THREAD

**Issue by guccisekspir** [flutter/flutter#105584]
When I try to use google maps flutter it works perfectly but sometimes gives this crash. Usually happen when change map page fast.
My Flutter version : 3.0.1
My Google Maps version : google_maps_flutter: ^2.1.7

<details>
<summary>Logs</summary>

```bash 
E/AndroidRuntime(10854): FATAL EXCEPTION: GLThread 1664
E/AndroidRuntime(10854): Process: com.sekspir.moody, PID: 10854
E/AndroidRuntime(10854): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime(10854): 	at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
E/AndroidRuntime(10854): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.l(:com.google.android.gms.dynamite_mapsdynamite@221514099@22.15.14 (190408-0):5)
E/AndroidRuntime(10854): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.o(:com.google.android.gms.dynamite_mapsdynamite@221514099@22.15.14 (190408-0):1)
E/AndroidRuntime(10854): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.g(:com.google.android.gms.dynamite_mapsdynamite@221514099@22.15.14 (190408-0):3)
E/AndroidRuntime(10854): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ai.s(:com.google.android.gms.dynamite_mapsdynamite@221514099@22.15.14 (190408-0):30)
E/AndroidRuntime(10854): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@221514099@22.15.14 (190408-0):10)
E/AndroidRuntime(10854): 	at com.google.maps.api.android.lib6.gmm6.vector.bz.s(:com.google.android.gms.dynamite_mapsdynamite@221514099@22.15.14 (190408-0):29)
E/AndroidRuntime(10854): 	at com.google.maps.api.android.lib6.gmm6.vector.bs.b(:com.google.android.gms.dynamite_mapsdynamite@221514099@22.15.14 (190408-0):151)
E/AndroidRuntime(10854): 	at com.google.maps.api.android.lib6.gmm6.vector.av.run(:com.google.android.gms.dynamite_mapsdynamite@221514099@22.15.14 (190408-0):48) 
```

</details>

My Google Map Widget : 

```dart 
GoogleMap(
    minMaxZoomPreference: const MinMaxZoomPreference(0, 14),
     initialCameraPosition: initialCameraPosition,
    myLocationButtonEnabled: false,
    zoomControlsEnabled: false,
    buildingsEnabled: false,
    mapToolbarEnabled: false,
    compassEnabled: false,
    onMapCreated: _onMapCreated,
    onCameraMove: _manager.onCameraMove,
    onCameraIdle: _manager.updateMap,
    markers: markers,
),
```

**Comment by huycozy** [comment]
Hi @guccisekspir,
It seems you got the issue on Android platform. I tried to reproduce but didn't see the exception as yours.
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) with detail reproduction steps so that we may verify this. 
Thank you!

**Comment by guccisekspir** [comment]
Hi @huycozy  

Yes this is about only Android platform. When try to rebuild faster like click 2nd navbar then click map page, it gives this error. When click normal speed there arent any error throwing. It looks like there are some missing await function on android google map side.

**Comment by huycozy** [comment]
@guccisekspir,

I tried running an example with `BottomNavigationBar` with embedded Google Map inside a tab, but still can not see the exception as yours even with switching very fast between Google Map tab and another tab. 
I performed the test on Pixel 3a (Android 12) and Samsung Galaxy Tab A7 Lite (Android 11, OneUI 3.1).

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  if (defaultTargetPlatform == TargetPlatform.android) {
    AndroidGoogleMapsFlutter.useAndroidViewSurface = true;
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
        brightness: Brightness.light,
        //appBarTheme: const AppBarTheme(backgroundColor: Colors.blue)
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  CameraPosition initialCameraPosition =
      const CameraPosition(target: LatLng(-33.852, 151.211), zoom: 11.0);

  late List<Widget> _pages;
  int _selectedIndex = 0;

  @override
  void initState() {
    super.initState();
    _pages = <Widget>[
      GoogleMap(
        minMaxZoomPreference: const MinMaxZoomPreference(0, 14),
        initialCameraPosition: initialCameraPosition,
        myLocationButtonEnabled: false,
        zoomControlsEnabled: false,
        buildingsEnabled: false,
        mapToolbarEnabled: false,
        compassEnabled: false,
      ),
      const Icon(
        Icons.camera,
        size: 150,
      ),
      const Icon(
        Icons.chat,
        size: 150,
      )
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: _pages.elementAt(_selectedIndex),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _selectedIndex,
        onTap: _onItemTapped,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.call),
            label: 'Calls',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.camera),
            label: 'Camera',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.chat),
            label: 'Chats',
          ),
        ],
      ),
    );
  }

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }
}

```
</details>

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/172761666-fb2191fb-62b2-46c9-943a-a7da1bf12de5.mp4

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.1 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1183, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1183 at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 725db2f0bf (70 minutes ago), 2022-06-08 21:48:08 -0400
    • Engine revision d7ef306fd3
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

It'll be great if you could provide us a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify this issue.

**Comment by LeonidVeremchuk** [comment]
Step to reproduce on Android (every 3-4 times)
1) open screen with map
2) switch to another app
3) back to app
4) press back to prev screen
5) repeat step 1

**Comment by plusema86** [comment]
It happens to me too, it crashes every time I go back from the screen with the map and the map has not been loaded completely. If, however, I allow time to load it completely then there is no crash.

**Comment by gianmarcocalbi** [comment]
I believe I am having the same issue.

Some users have started to report some crashes on a Screen using a GoogleMap widget right after updating the app to the version introducing flutter 3.0...

For me, it's very difficult to understand the problem as I do not use Crashlytics 😔.

---

So far I succeeded to get a crash in debug mode while "playing" around with the GoogleMap, for the sake of completeness I describe it below but it's not related to a real scenario use case.

### Logs
```
E/AndroidRuntime(10818): FATAL EXCEPTION: GLThread 303
E/AndroidRuntime(10818): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime(10818): 	at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.l(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):5)
E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.o(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):1)
E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.g(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):3)
E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ai.s(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):27)
E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):10)
E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.bz.s(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):29)
E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.bs.b(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):151)
E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.av.run(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):48)
E/flutter (10818): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method camera#move on channel plugins.flutter.io/google_maps_5)
E/flutter (10818): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (10818): <asynchronous suspension>
E/flutter (10818): #1      _PositionModalScreenState._animateToSuggestedPlace (package:wayt_app/ui/common/map/position_modal_screen.dart:126:7)
E/flutter (10818): <asynchronous suspension>
E/flutter (10818): #2      _PlaceAutocompletePickerState._onSelectSuggestion (package:wayt_app/ui/common/input/place_autocomplete_picker.dart:128:7)
E/flutter (10818): <asynchronous suspension>
E/flutter (10818): 
I/Process (10818): Sending signal. PID: 10818 SIG: 9
Lost connection to device.
```

### Steps to reproduce
In order to reproduce the crash:

* push a screen with a GoogleMap widget
* trigger the code below

```dart
for (var i = 0; i < 1e4; i++) {
  await _mapController?.moveCamera(
    CameraUpdate.newCameraPosition(
      CameraPosition(
        target: LatLng(0, 0),
        zoom: 17,
      ),
    ),
  );
  await _mapController?.moveCamera(
    CameraUpdate.newCameraPosition(
      CameraPosition(
        target: LatLng(40.4154556, -3.699510899999999),
        zoom: 17,
      ),
    ),
  );
}
```

* try to go back / pop the screen while the for loop is executing
* approx 1 time over 10, while popping, the app crashes with  `java.lang.NullPointerException`

---


<details>
<summary>flutter doctor -v</summary>
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 3.0.1 at /Users/gcalbi/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gcalbi/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/gcalbi/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 68.1.3
    • Dart plugin version 213.7371

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/212.4746.92/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.7172.25/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
    • IntelliJ at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6461.79/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Pixel 3 (mobile) • 192.168.1.70:43491 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos              • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)     • chrome             • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by gianmarcocalbi** [comment]
> I believe I am having the same issue.
> 
> Some users have started to report some crashes on a Screen using a GoogleMap widget right after updating the app to the version introducing flutter 3.0...
> 
> For me, it's very difficult to understand the problem as I do not use Crashlytics 😔.
> 
> So far I succeeded to get a crash in debug mode while "playing" around with the GoogleMap, for the sake of completeness I describe it below but it's not related to a real scenario use case.
> 
> ### Logs
> ```
> E/AndroidRuntime(10818): FATAL EXCEPTION: GLThread 303
> E/AndroidRuntime(10818): java.lang.NullPointerException: Attempt to get length of null array
> E/AndroidRuntime(10818): 	at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
> E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.l(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):5)
> E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.o(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):1)
> E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.g(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):3)
> E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ai.s(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):27)
> E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):10)
> E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.bz.s(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):29)
> E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.bs.b(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):151)
> E/AndroidRuntime(10818): 	at com.google.maps.api.android.lib6.gmm6.vector.av.run(:com.google.android.gms.dynamite_mapsdynamite@221820097@22.18.20 (190400-0):48)
> E/flutter (10818): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method camera#move on channel plugins.flutter.io/google_maps_5)
> E/flutter (10818): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
> E/flutter (10818): <asynchronous suspension>
> E/flutter (10818): #1      _PositionModalScreenState._animateToSuggestedPlace (package:wayt_app/ui/common/map/position_modal_screen.dart:126:7)
> E/flutter (10818): <asynchronous suspension>
> E/flutter (10818): #2      _PlaceAutocompletePickerState._onSelectSuggestion (package:wayt_app/ui/common/input/place_autocomplete_picker.dart:128:7)
> E/flutter (10818): <asynchronous suspension>
> E/flutter (10818): 
> I/Process (10818): Sending signal. PID: 10818 SIG: 9
> Lost connection to device.
> ```
> 
> ### Steps to reproduce
> In order to reproduce the crash:
> 
> * push a screen with a GoogleMap widget
> * trigger the code below
> 
> ```dart
> for (var i = 0; i < 1e4; i++) {
>   await _mapController?.moveCamera(
>     CameraUpdate.newCameraPosition(
>       CameraPosition(
>         target: LatLng(0, 0),
>         zoom: 17,
>       ),
>     ),
>   );
>   await _mapController?.moveCamera(
>     CameraUpdate.newCameraPosition(
>       CameraPosition(
>         target: LatLng(40.4154556, -3.699510899999999),
>         zoom: 17,
>       ),
>     ),
>   );
> }
> ```
> 
> * try to go back / pop the screen while the for loop is executing
> * approx 1 time over 10, while popping, the app crashes with  `java.lang.NullPointerException`
> 
> flutter doctor -v

I succeeded to replicate the issue within my app. 
Basically, it's what others are saying here.
It happens indeed when popping a screen with a GoogleMap that is rebuilding, in my case the pop occurred while a `_mapController.moveCamera` was executing.

**Comment by gianmarcocalbi** [comment]
I have just rolled back my project to flutter 2 and the crash does not occur anymore
