### ISSUE TITLE
Issue when trying to play a .webm video from a network source on Firebase Storage

### ISSUE THREAD

**Issue by skypopcorn1** [flutter/flutter#105649]
When my page loads, while attempting to load certain .webm videos from a network source on Firebase Storage, I receive the error below. The audio from the video begins to automatically play even before _controller.play() is triggered and the video is not visible on the screen. This issue does not occur when loading .mp4 files from the same Firebase Storage instance and only occurs with some .webm files.
 
Below are two sample videos, one an .webm video that can be used to reproduce the issue and the other a .mp4 to verify that this issue does not occur with .mp4 videos stored on the same Firebase Storage instance.   

Strangely, this is not a problem when using the .webm video at "https://dl8.webmfiles.org/big-buck-bunny_trailer.webm".  I also uploaded this video to my Firebase Storage instance and it works. So I don't think Firebase Storage is the issue rather something to do with the other video files. The video files that cause the problem are able to be opened and played in a chrome browser if you simply paste the link. The error produced in the logs doesn't give me much to go on. 

**Reproducible code:**
This issue is reproducible using the video_player package’s example code.  

**Links for testing / reproducing**
webm (**not working**): https://firebasestorage.googleapis.com/v0/b/disc-doctor-284de.appspot.com/o/form_review%2F1654157014042.webm?alt=media&token=04d61a4f-8b8f-47aa-bf9e-c063740fe48d

webm (**working**): https://firebasestorage.googleapis.com/v0/b/disc-doctor-284de.appspot.com/o/form_review%2Fbig-buck-bunny_trailer.webm?alt=media&token=0eebd572-3b46-4b2a-a95e-a73d43989d5e

mp4 (**working**): https://firebasestorage.googleapis.com/v0/b/disc-doctor-284de.appspot.com/o/form_review_pro_examples%2Fcatrina_allen_side.mp4?alt=media&token=3f45933f-2247-4fb7-a374-b54ac4e4dedd

**Running with:**
flutter run -d chrome --web-renderer html 

**pubspec.yaml**
video_player: ^2.3.0

**Video player package information from logs:**
[        ] Found plugin video_player at /Users/…/development/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-2.3.0/
[        ] Found plugin video_player_android at /Users/…/development/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_android-2.3.1/
[        ] Found plugin video_player_avfoundation at /Users/…/development/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_avfoundation-2.3.1/
[        ] Found plugin video_player_web at /Users/…/development/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_web-2.0.7/

**Flutter doctor:**
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.2.1 21D62 darwin-arm, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

 **Error:** 
Error: Unsupported operation: Infinity
                        at Object.throw_ [as throw] (http://localhost:56005/dart_sdk.js:5405:11)
                        at [dartx.round] (http://localhost:56005/dart_sdk.js:18483:17)
                        at video_player_web._VideoPlayer.new.sendInitialized (http://localhost:56005/packages/video_player_web/video_player_web.dart.lib.js:392:259)
                        at http://localhost:56005/packages/video_player_web/video_player_web.dart.lib.js:325:16
                        at Object._checkAndCall (http://localhost:56005/dart_sdk.js:5609:16)
                        at Object.dcall (http://localhost:56005/dart_sdk.js:5614:17)
                        at HTMLVideoElement.<anonymous> (http://localhost:56005/dart_sdk.js:115590:21)

**Comment by maheshmnj** [comment]
Hi @skypopcorn1, Thanks for filing the issue. I am able to reproduce the issue on the latest stable and master channel with both Renderers (HTML and canvaskit).  The video URL specified does not play on any flutter supported platform(verified on web, android, ios).

This is the error  in the chome console when the video fails to play.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/31410839/172789950-22fdb86c-9ea9-4d01-9202-ef8ae20ff46d.png">

_error from chrome console_
```
Flutter Web Bootstrap: Programmatic
errors.dart:266 Uncaught Error: Unsupported operation: Infinity
    at Object.throw_ [as throw] (errors.dart:266:49)
    at [dartx.round] (js_number.dart:109:5)
    at [_sendInitialized] (video_player.dart:199:53)
    at video_player.dart:72:9
    at Object._checkAndCall (operations.dart:334:14)
    at Object.dcall (operations.dart:339:39)
    at HTMLVideoElement.<anonymous> (html_dart2js.dart:37300:58)
throw_ @ errors.dart:266
[dartx.round] @ js_number.dart:109
[_sendInitialized] @ video_player.dart:199
(anonymous) @ video_player.dart:72
_checkAndCall @ operations.dart:334
dcall @ operations.dart:339
(anonymous) @ html_dart2js.dart:37300
js_primitives.dart:30 Flutter Web Bootstrap: Auto
errors.dart:266 Uncaught Error: Unsupported operation: Infinity
    at Object.throw_ [as throw] (errors.dart:266:49)
    at [dartx.round] (js_number.dart:109:5)
    at [_sendInitialized] (video_player.dart:199:53)
    at video_player.dart:72:9
    at Object._checkAndCall (operations.dart:334:14)
    at Object.dcall (operations.dart:339:39)
    at HTMLVideoElement.<anonymous> (html_dart2js.dart:37300:58)
```

> The audio from the video begins to automatically play even before _controller.play() is triggered and the video is not visible on the screen.

Also, I can confirm this behavior, 
- Just run the below code sample
- hit play and hot restart.
- Audio plays but the video doesn't render


<details>
<summary>code sample</summary>

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://firebasestorage.googleapis.com/v0/b/disc-doctor-284de.appspot.com/o/form_review%2F1654157014042.webm?alt=media&token=04d61a4f-8b8f-47aa-bf9e-c063740fe48d')
      ..initialize().then((_) {
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}

```
</details> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1138, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1138 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9be807192 (26 hours ago), 2022-06-06 21:16:49 -0700
    • Engine revision 48864fc837
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 6AE1D692-DB57-4C3E-ADCA-66842182426B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by skypopcorn1** [comment]
Any update?

**Comment by wisekiddo** [comment]
Any update on this issue, facing the same.

**Comment by ditman** [comment]
Thanks for the repro videos @skypopcorn1, @maheshmnj and the JS console dump! Both were very useful!

This had happened in [other platforms](https://github.com/flutter/plugins/pull/3360), but not in the web yet. The difference between the video that is failing and the ones that aren't is that the bad video has a `.duration` of `Infinity` and the ones that work return a "proper" float:

| Bad | Good |
|---|---|
| <img width="315" alt="Screenshot of the Bad video showing Infinity duration" src="https://user-images.githubusercontent.com/1255594/178857391-ff915272-c329-450a-874f-90477edc4d3b.png"> | <img width="213" alt="Screenshot of a working video showing a finite, float, duration" src="https://user-images.githubusercontent.com/1255594/178857445-5b339685-f27f-4e19-b873-0dd33b25075f.png"> |

You can even see the difference when the browser opens the videos:

* "Finite" videos will display the total length next to the current progress, and the progress bar will advance "normally"
* "Infinite" videos won't display a total length (normally this is for "live" shows), and that the progress bar will advance in a non-linear way (it'll reach the 50% point rather quickly, and then start to advance more and more slowly).

Anyway, let's take a look at the web video player code to see if it can be made more robust when the duration of a video is `Infinity`!

**Comment by ditman** [comment]
I've posted a PR for this issue: https://github.com/flutter/plugins/pull/6101
