### ISSUE TITLE
Expected a value of type 'ItemSimple', but got one of type 'Null'

### ISSUE THREAD

**Issue by ajhwb** [flutter/flutter#105635]
Hi Devs,

I got the following errors, but assert() isn't fail, is this a bug?

```
// model.items is a List<ItemSimple>
for (ItemSimple? e in list) {
  debugPrint('id=${e?.id} title=${e?.title}');
  assert(e != null);
  model.items.add(e!);
}
```

Output

```
id=30 title=Jual Ban Second
Error: Expected a value of type 'ItemSimple', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:49430/dart_sdk.js:5080:11)
    at Object.castError (http://localhost:49430/dart_sdk.js:5039:15)
    at Object.cast [as as] (http://localhost:49430/dart_sdk.js:5356:17)
    at ItemSimple.as_C [as as] (http://localhost:49430/dart_sdk.js:4985:19)
    at set [dartx.length] (http://localhost:49430/dart_sdk.js:17536:42)
    at set length [as length] (http://localhost:49430/packages/kebi_web/models/item.dart.lib.js:709:33)
    at item$.ItemSimpleList.fromJson.add (http://localhost:49430/dart_sdk.js:19076:57)
    at items._ItemsViewState.new.getItems (http://localhost:49430/packages/kebi_web/views/items.dart.lib.js:1326:32)
    at getItems.next (<anonymous>)
    at http://localhost:49430/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:49430/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:49430/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:49430/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:49430/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:49430/dart_sdk.js:35872:23)
    at http://localhost:49430/dart_sdk.js:36103:40
    at _RootZone.runUnary (http://localhost:49430/dart_sdk.js:40511:59)
    at _FutureListener.then.handleValue (http://localhost:49430/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:49430/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:49430/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:49430/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49430/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:49430/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:49430/dart_sdk.js:40784:13)
    at http://localhost:49430/dart_sdk.js:36261:9
```

Version:
```

[✓] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 3.0.1 at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\Ardhan\AppData\Local\Android\sdk
    • Platform android-31, build-tools 32.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.
```

**Comment by ajhwb** [comment]
Update: 

with ```--no-sound-null-safety``` it seems to be okay

**Comment by stuartmorgan** [comment]
Issues with Dart need to be filed in the [Dart repository](https://github.com/dart-lang/sdk/issues) rather than the Flutter repository.

(It's not clear to me what you believe the Dart issue is here though, so you should provide more context when you file it there.)
