### ISSUE TITLE
Failed to access the internal image decoder registry on this isolate

### ISSUE THREAD

**Issue by zhengxiaoguan** [flutter/flutter#105662]
<details>
<summary>Logs</summary>

```bash
======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: Failed to access the internal image decoder registry on this isolate. Please file a bug on https://github.com/flutter/flutter/issues.

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:5522:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5390:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2053:60)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "images/ic_grounding_jilu.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#a74f3(), name: "images/3.0x/ic_grounding_jilu.png", scale: 3.0)
====================================================================================================
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)

• No issues found!
```
</details>

<details>
<summary>Sample code</summary>

- Object-C:

```objective-c
AppDelegate *appdelegate = (AppDelegate*)(UIApplication.sharedApplication.delegate);
    self.groundFlutterEngine = [appdelegate.engineGroup makeEngineWithEntrypoint:@"groundPage" libraryURI:nil];
    [GeneratedPluginRegistrant registerWithRegistry:self.groundFlutterEngine];
    self.flutterCtrl = [[FlutterViewController alloc] initWithEngine:self.groundFlutterEngine nibName:nil bundle:nil];
    self.flutterCtrl.modalPresentationStyle = UIModalPresentationFullScreen;
    [self presentViewController:self.flutterCtrl animated:YES completion:nil];
    FlutterMethodChannel * methodChannel = [FlutterMethodChannel methodChannelWithName:@"ground_page" binaryMessenger:self.flutterCtrl.binaryMessenger];
    [methodChannel invokeMethod:@"ground" arguments:nil];
    [methodChannel setMethodCallHandler:^(FlutterMethodCall * _Nonnull call, FlutterResult  _Nonnull result) {
        if ([call.method isEqualToString:@"exit"]) {
            [self.flutterCtrl dismissViewControllerAnimated:YES completion:nil];
        }
    }];

```

- Flutter

```dart
final MethodChannel _groundChannel = const MethodChannel("ground_page");
IconButton(
        icon: Image.asset('images/ic_back.png', width: 20),
        onPressed: () {
          _groundChannel.invokeMethod("exit");
      }),

```
</details>

problem:
1. push(flutter image show normal) -> dismiss
2. push, (flutter image exception) 
3. I want the picture to work  want the picture to work

**Comment by huycozy** [comment]
Hi @zhengxiaoguan,
From your `flutter doctor -v` output, I can see you're working on old Flutter SDK, please try upgrading it to the latest (stable `3.0.1` and master `3.1.0-0.0.pre.1183`) then try running application again to see if it works without error.
This issue might be fixed on new Flutter, see: https://github.com/flutter/flutter/issues/98013#issuecomment-1048327181

If the issue still persists after upgrading SDK, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Thank you!
