### ISSUE TITLE
Multiple `TestGestures` with pointers cannot be cleaned up

### ISSUE THREAD

**Issue by Stumblinbear** [flutter/flutter#105777]
When creating multiple pointer gestures for a single test, they cannot be cleaned up using `removePointer` due to an assertion.

- Using a single `TestGesture` with multiple pointers is not supported
- `createGesture` does not allow passing in a `device` identifier, meaning every new pointer ends up with the same `device`.
- Creating many gestures (which gives them the same `device` identifier), then calling `removePointer` on one of them will remove the device, but not the remaining pointers that were created, leading to complaints about pointers remaining: `'!RendererBinding.instance.mouseTracker.mouseIsConnected'`

A potential solution is allowing a `device` identifier to be passed to `createGesture`, however `removePointer` will delete the device from the states list `_mouseStates.remove(event.device);`, where the next removal will have a `device` identifier that is no longer at that position in the List. This would mean you'd likely need to remove the pointers in reverse order. This could be resolved by using a tombstone instead of direct removal.

**Expected results:**

The buttons should all be marked as hovered simultaneously and the pointers should be properly removed.

**Actual results:**

The test throws an exception on `removePointer`.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('gesture hover exception', (tester) async {
    await tester.pumpWidget(
      Container(
        constraints: const BoxConstraints(maxWidth: 800, maxHeight: 800),
        child: Column(
          children: [
            TextButton(
              onPressed: () {},
              child: const SizedBox(width: 32, height: 32),
            ),
            TextButton(
              onPressed: () {},
              child: const SizedBox(width: 32, height: 32),
            ),
            TextButton(
              onPressed: () {},
              child: const SizedBox(width: 32, height: 32),
            )
          ],
        ),
      ),
    );

    final finder = find.byType(TextButton);

    List<TestGesture> gestures = [];

    for (var i = 0; i < finder.evaluate().length; i++) {
      final TestGesture gesture = await tester.createGesture(
        kind: PointerDeviceKind.mouse,
      );

      await gesture.moveTo(
        tester.getCenter(
          finder.at(i),
          warnIfMissed: true,
          callee: 'hover',
        ),
      );

      gestures.add(gesture);
    }

    await tester.pump();

    for (final gesture in gestures) {
      await gesture.removePointer();
    }
  });
}
```

</details>

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 324 pos 18: 'event is!
PointerRemovedEvent': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      MouseTracker.updateWithEvent.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:324:18)
#3      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:211:9)
#4      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:317:7)
#5      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:195:9)
#6      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:316:5)
#7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:321:20)
#8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#10     TestWidgetsFlutterBinding.handlePointerEventForSource.<anonymous closure> (package:flutter_test/src/binding.dart:523:42)
#11     TestWidgetsFlutterBinding.withPointerEventSource (package:flutter_test/src/binding.dart:533:11)
#12     TestWidgetsFlutterBinding.handlePointerEventForSource (package:flutter_test/src/binding.dart:523:5)
#13     WidgetTester.sendEventToBinding.<anonymous closure> (package:flutter_test/src/widget_tester.dart:808:15)
#14     WidgetTester.sendEventToBinding.<anonymous closure> (package:flutter_test/src/widget_tester.dart:807:39)
#17     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#18     WidgetTester.sendEventToBinding (package:flutter_test/src/widget_tester.dart:807:27)
#19     TestGesture.removePointer.<anonymous closure> (package:flutter_test/src/test_pointer.dart:365:25)
#22     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#23     TestGesture.removePointer (package:flutter_test/src/test_pointer.dart:364:27)

```

```
No issues found! (ran in 3.1s)
```

```
[✓] Flutter (Channel stable, 3.0.1, on Zorin OS 16.1 5.13.0-44-generic, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /home/stumblinbear/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/stumblinbear/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /var/lib/flatpak/exports/bin/com.google.Chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Zorin OS 16.1 5.13.0-44-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115 unknown

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment]
Hello @Stumblinbear. Seem like a feature request. Though I have a couple of concerns. It seems logical that a single pointer is created as the expected use case is that the user would have one mouse and not many connected. Could you explain a use case where this type of behavior is justified?

**Comment by danagbemava-nc** [comment]
Hi @Stumblinbear, is the sample you provided representative of the test you have in your actual project? 

I'm asking this because when I run your code sample, there were some framework assertions errors (which I tried to fix by wrapping your sample with a `MaterialApp`),  although I was able to reproduce the test failure. 

However, when I tested on the `master` channel (after wrapping the code with a `MaterialApp`), the test passed for me on the `master` channel. 

Can you check on the `master` channel after wrapping the sample with a `MaterialApp` to see whether or not you still experience this issue?

Thank you

[test_master.log](https://github.com/flutter/flutter/files/8897410/test_master.log)
[test.log](https://github.com/flutter/flutter/files/8897411/test.log)

**Comment by exaby73** [comment]
Hey @Stumblinbear. Can you point me to how you know that the hover events are not triggered? I get the following logs when wrapping with `MaterialApp`. How would I understand if hover is being triggered or not?

```
00:00 +0: loading /Users/nabeelparkar/dev/nevercode/issue_105777/test/widget_test.dart                                                            
00:01 +0: loading /Users/nabeelparkar/dev/nevercode/issue_105777/test/widget_test.dart                                                            
00:02 +0: loading /Users/nabeelparkar/dev/nevercode/issue_105777/test/widget_test.dart                                                            
00:02 +0: gesture hover exception                                                                                                                 
00:03 +0: gesture hover exception                                                                                                                 
00:03 +1: gesture hover exception                                                                                                                 
00:03 +1: All tests passed!
```
