### ISSUE TITLE
Fuchsia build appears to be broken on macOS

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#105794]
I get errors like this locally, seems to be impeller related:

```
ninja: Entering directory `out/fuchsia_debug_x64'
[8444/9239] ACTION //flutter/impeller/entity:genlib_mtl_entity_shaders(//build/toolchain/mac:clang_x64)
FAILED: clang_x64/shaders/entity.metallib 
python3 ../../flutter/impeller/tools/build_metal_library.py --output shaders/entity.metallib --depfile /Users/dnfield/src/flutter/engine/src/out/fuchsia_debug_x64/clang_x64/gen/flutter/impeller/entity/mtl/entity.depfile --optimize --platform=mac --source gen/flutter/impeller/entity/advanced_blend.vert.metal --source gen/flutter/impeller/entity/advanced_blend_color.frag.metal --source gen/flutter/impeller/entity/advanced_blend_colorburn.frag.metal --source gen/flutter/impeller/entity/advanced_blend_colordodge.frag.metal --source gen/flutter/impeller/entity/advanced_blend_darken.frag.metal --source gen/flutter/impeller/entity/advanced_blend_difference.frag.metal --source gen/flutter/impeller/entity/advanced_blend_exclusion.frag.metal --source gen/flutter/impeller/entity/advanced_blend_hardlight.frag.metal --source gen/flutter/impeller/entity/advanced_blend_hue.frag.metal --source gen/flutter/impeller/entity/advanced_blend_lighten.frag.metal --source gen/flutter/impeller/entity/advanced_blend_luminosity.frag.metal --source gen/flutter/impeller/entity/advanced_blend_multiply.frag.metal --source gen/flutter/impeller/entity/advanced_blend_overlay.frag.metal --source gen/flutter/impeller/entity/advanced_blend_saturation.frag.metal --source gen/flutter/impeller/entity/advanced_blend_screen.frag.metal --source gen/flutter/impeller/entity/advanced_blend_softlight.frag.metal --source gen/flutter/impeller/entity/blend.frag.metal --source gen/flutter/impeller/entity/blend.vert.metal --source gen/flutter/impeller/entity/border_mask_blur.frag.metal --source gen/flutter/impeller/entity/border_mask_blur.vert.metal --source gen/flutter/impeller/entity/gaussian_blur.frag.metal --source gen/flutter/impeller/entity/gaussian_blur.vert.metal --source gen/flutter/impeller/entity/glyph_atlas.frag.metal --source gen/flutter/impeller/entity/glyph_atlas.vert.metal --source gen/flutter/impeller/entity/gradient_fill.frag.metal --source gen/flutter/impeller/entity/gradient_fill.vert.metal --source gen/flutter/impeller/entity/solid_fill.frag.metal --source gen/flutter/impeller/entity/solid_fill.vert.metal --source gen/flutter/impeller/entity/solid_stroke.frag.metal --source gen/flutter/impeller/entity/solid_stroke.vert.metal --source gen/flutter/impeller/entity/texture_fill.frag.metal --source gen/flutter/impeller/entity/texture_fill.vert.metal --source gen/flutter/impeller/entity/vertices.vert.metal --source gen/flutter/impeller/entity/vertices.frag.metal
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_color.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_colorburn.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_colordodge.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_darken.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_difference.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_exclusion.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_hardlight.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_hue.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_lighten.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_luminosity.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_multiply.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_overlay.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_saturation.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_screen.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/advanced_blend_softlight.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/blend.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/blend.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/border_mask_blur.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/border_mask_blur.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/gaussian_blur.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/gaussian_blur.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/glyph_atlas.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/glyph_atlas.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/gradient_fill.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/gradient_fill.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/solid_fill.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/solid_fill.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/solid_stroke.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/solid_stroke.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/texture_fill.frag.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/texture_fill.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/vertices.vert.metal'
metal: error: no such file or directory: 'gen/flutter/impeller/entity/vertices.frag.metal'
metal: error: no input files
Traceback (most recent call last):
  File "/Users/dnfield/src/flutter/engine/src/out/fuchsia_debug_x64/../../flutter/impeller/tools/build_metal_library.py", line 131, in <module>
    main()
  File "/Users/dnfield/src/flutter/engine/src/out/fuchsia_debug_x64/../../flutter/impeller/tools/build_metal_library.py", line 125, in main
    subprocess.check_call(command)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xcrun', '-sdk', 'macosx', 'metal', '-Wno-unused-variable', '-MMD', '-MF', '/Users/dnfield/src/flutter/engine/src/out/fuchsia_debug_x64/clang_x64/gen/flutter/impeller/entity/mtl/entity.depfile', '-o', 'shaders/entity.metallib', '--std=macos-metal1.2', '-Oz', '-ffast-math', 'gen/flutter/impeller/entity/advanced_blend.vert.metal', 'gen/flutter/impeller/entity/advanced_blend_color.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_colorburn.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_colordodge.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_darken.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_difference.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_exclusion.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_hardlight.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_hue.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_lighten.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_luminosity.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_multiply.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_overlay.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_saturation.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_screen.frag.metal', 'gen/flutter/impeller/entity/advanced_blend_softlight.frag.metal', 'gen/flutter/impeller/entity/blend.frag.metal', 'gen/flutter/impeller/entity/blend.vert.metal', 'gen/flutter/impeller/entity/border_mask_blur.frag.metal', 'gen/flutter/impeller/entity/border_mask_blur.vert.metal', 'gen/flutter/impeller/entity/gaussian_blur.frag.metal', 'gen/flutter/impeller/entity/gaussian_blur.vert.metal', 'gen/flutter/impeller/entity/glyph_atlas.frag.metal', 'gen/flutter/impeller/entity/glyph_atlas.vert.metal', 'gen/flutter/impeller/entity/gradient_fill.frag.metal', 'gen/flutter/impeller/entity/gradient_fill.vert.metal', 'gen/flutter/impeller/entity/solid_fill.frag.metal', 'gen/flutter/impeller/entity/solid_fill.vert.metal', 'gen/flutter/impeller/entity/solid_stroke.frag.metal', 'gen/flutter/impeller/entity/solid_stroke.vert.metal', 'gen/flutter/impeller/entity/texture_fill.frag.metal', 'gen/flutter/impeller/entity/texture_fill.vert.metal', 'gen/flutter/impeller/entity/vertices.vert.metal', 'gen/flutter/impeller/entity/vertices.frag.metal']' returned non-zero exit status 1.
[8485/9239] ACTION //flutter/shell/platform/fuchsia/flutter/kernel:kernel_platform_files(//build/toolchain/mac:clang_x64)^C
```

**Comment by chinmaygarde** [comment]
I don't think the Fuchsia stuff ever worked on macOS. Only a few targets had to be explicitly chosen build. Closing this as wont-fix.
