### ISSUE TITLE
flutter build apk --analyze-size --target-platform android-arm fails with Exception: AOT snapshotter exited with code -2147483645

### ISSUE THREAD

**Issue by OutdatedGuy** [flutter/flutter#105980]
Flutter version: `3.0.1`

Logs with the `--verbose` flag for both *with* and *without* `--analyze-size` flag

<details>

<summary>For command, "flutter build apk --target-platform android-arm --analyze-size --verbose"</summary>

```
[ +151 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +475 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] executing: [C:\flutter/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[ +165 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] 3.0.1
[   +9 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +106 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +79 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +269 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +117 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +149 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +85 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +179 ms] Skipping pub get: version match.
[ +137 ms] Generating E:\Test Area\Flutter dummy\flutter_application_1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +167 ms]  Building with sound null safety 
[  +40 ms] Running Gradle task 'assembleRelease'...
[  +16 ms] Using gradle from E:\Test Area\Flutter dummy\flutter_application_1\android\gradlew.bat.
[  +26 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +243 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +3 ms] executing: [E:\Test Area\Flutter dummy\flutter_application_1\android/] E:\Test Area\Flutter dummy\flutter_application_1\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-arm -Ptarget=lib\main.dart -Pbase-application-name=android.app.Application -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=true -Pcode-size-directory=build\flutter_size_02 assembleRelease
[+2207 ms] Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
[+16696 ms] Observed package id 'platform-tools' in inconsistent location 'C:\Users\Dell\AppData\Local\Android\sdk\platform-tools-2' (Expected
'C:\Users\Dell\AppData\Local\Android\sdk\platform-tools')
[+2898 ms] > Task :app:buildKotlinToolingMetadata UP-TO-DATE
[+29997 ms] > Task :app:compileFlutterBuildRelease
[+3799 ms] ../../third_party/dart/runtime\vm/hash_map.h: 144: error: expected: ++probes < FLAG_hash_map_probes_limit
[   +5 ms] version=2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "windows_simarm"
[   +1 ms] pid=16964, thread=-1, isolate_group=isolate(01504B18), isolate=isolate(01508320)
[   +1 ms] isolate_instructions=0, vm_instructions=0
[   +3 ms]   pc 0x00be1da2 fp 0x012ff884 Unknown symbol
[   +3 ms]   pc 0x00af7d70 fp 0x012ff894 Unknown symbol
[   +2 ms]   pc 0x00c3f3d7 fp 0x012ff8d8 Unknown symbol
[   +1 ms]   pc 0x00b1ad51 fp 0x012ff908 Unknown symbol
[   +1 ms]   pc 0x00b371f0 fp 0x012ff928 Unknown symbol
[   +1 ms]   pc 0x00b1ee3e fp 0x012ff974 Unknown symbol
[   +1 ms]   pc 0x00b219b2 fp 0x012ffaa0 Unknown symbol
[   +1 ms]   pc 0x00b220c7 fp 0x012ffaac Unknown symbol
[   +1 ms]   pc 0x00dc0eca fp 0x012ffc18 Unknown symbol
[   +1 ms]   pc 0x00dc1a2d fp 0x012ffc88 Unknown symbol
[   +1 ms]   pc 0x00af226a fp 0x012ffd70 Unknown symbol
[   +1 ms]   pc 0x00dc3f9d fp 0x012ffdb8 Unknown symbol
[  +74 ms]   pc 0x76947ba9 fp 0x012ffdc8 BaseThreadInitThunk+0x19
[   +1 ms]   pc 0x77dab7db fp 0x012ffe20 RtlInitializeExceptionChain+0x6b
[   +1 ms]   pc 0x77dab75f fp 0x012ffe30 RtlClearBits+0xbf
[   +1 ms] -- End of DumpStackTrace
[+5497 ms] Dart snapshot generator failed with exit code -1073740791
[ +507 ms] > Task :app:compileFlutterBuildRelease FAILED
[   +2 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[   +2 ms] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.  
[   +2 ms] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[   +2 ms] 2 actionable tasks: 1 executed, 1 up-to-date
[   +5 ms] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[   +1 ms] Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156
[   +2 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:compileFlutterBuildRelease'.
[   +1 ms] > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[   +1 ms] * Try:
[   +1 ms] > Run with --stacktrace option to get the stack trace.
[   +3 ms] > Run with --info or --debug option to get more log output.
[   +1 ms] > Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 1m 1s
[ +860 ms] Running Gradle task 'assembleRelease'... (completed in 62.9s)
[   +6 ms] "flutter apk" took 63,576ms.
[   +7 ms] Gradle task assembleRelease failed with exit code 1
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:406:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:109:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +256 ms] ensureAnalyticsSent: 251ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
</details>

<details>

<summary>For command, "flutter build apk --target-platform android-arm --verbose"</summary>

```
[  +73 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +337 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[   +1 ms] executing: [C:\flutter/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[ +144 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] 3.0.1
[   +9 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +60 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +136 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +73 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +92 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +64 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +121 ms] Skipping pub get: version match.
[ +128 ms] Generating E:\Test Area\Flutter dummy\flutter_application_1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +177 ms]  Building with sound null safety 
[  +25 ms] Running Gradle task 'assembleRelease'...
[   +7 ms] Using gradle from E:\Test Area\Flutter dummy\flutter_application_1\android\gradlew.bat.
[   +8 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +178 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +2 ms] executing: [E:\Test Area\Flutter dummy\flutter_application_1\android/] E:\Test Area\Flutter dummy\flutter_application_1\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-arm -Ptarget=lib\main.dart -Pbase-application-name=android.app.Application -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=true assembleRelease
[+2874 ms] > Task :app:buildKotlinToolingMetadata UP-TO-DATE
[+3590 ms] > Task :app:compileFlutterBuildRelease
[   +1 ms] Parameter format not correct -
[   +1 ms] > Task :app:packLibsflutterBuildRelease UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preReleaseBuild UP-TO-DATE
[   +1 ms] > Task :app:compileReleaseAidl NO-SOURCE
[   +1 ms] > Task :app:compileReleaseRenderscript NO-SOURCE
[   +1 ms] > Task :app:generateReleaseBuildConfig UP-TO-DATE
[ +283 ms] > Task :app:checkReleaseAarMetadata UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeReleaseAssets
[   +1 ms] > Task :app:mergeReleaseShaders UP-TO-DATE
[   +2 ms] > Task :app:compileReleaseShaders NO-SOURCE
[   +1 ms] > Task :app:generateReleaseAssets UP-TO-DATE
[  +97 ms] > Task :app:mergeReleaseAssets
[  +94 ms] > Task :app:copyFlutterAssetsRelease
[   +1 ms] > Task :app:generateReleaseResValues UP-TO-DATE
[        ] > Task :app:generateReleaseResources UP-TO-DATE
[ +100 ms] > Task :app:mergeReleaseResources UP-TO-DATE
[   +2 ms] > Task :app:createReleaseCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :app:extractDeepLinksRelease UP-TO-DATE
[ +101 ms] > Task :app:processReleaseMainManifest UP-TO-DATE
[   +1 ms] > Task :app:processReleaseManifest UP-TO-DATE
[   +5 ms] > Task :app:processReleaseManifestForPackage UP-TO-DATE
[ +101 ms] > Task :app:processReleaseResources UP-TO-DATE
[+1090 ms] > Task :app:compileReleaseKotlin UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileRelease UP-TO-DATE
[        ] > Task :app:writeReleaseApplicationId UP-TO-DATE
[        ] > Task :app:analyticsRecordingRelease
[   +1 ms] > Task :app:compileReleaseJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :app:extractProguardFiles UP-TO-DATE
[ +207 ms] > Task :app:lintVitalAnalyzeRelease UP-TO-DATE
[   +1 ms] > Task :app:lintVitalReportRelease UP-TO-DATE
[   +1 ms] > Task :app:lintVitalRelease
[   +1 ms] > Task :app:mergeReleaseJniLibFolders UP-TO-DATE
[  +90 ms] > Task :app:mergeReleaseNativeLibs UP-TO-DATE
[   +6 ms] > Task :app:stripReleaseDebugSymbols UP-TO-DATE
[   +4 ms] > Task :app:extractReleaseNativeSymbolTables UP-TO-DATE
[   +4 ms] > Task :app:mergeReleaseNativeDebugMetadata NO-SOURCE
[  +97 ms] > Task :app:mergeReleaseArtProfile UP-TO-DATE
[  +74 ms] > Task :app:checkReleaseDuplicateClasses UP-TO-DATE
[ +103 ms] > Task :app:mergeReleaseGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :app:processReleaseJavaRes NO-SOURCE
[   +1 ms] > Task :app:mergeReleaseJavaResource UP-TO-DATE
[ +196 ms] > Task :app:minifyReleaseWithR8 UP-TO-DATE
[   +1 ms] > Task :app:compileReleaseArtProfile UP-TO-DATE
[   +1 ms] > Task :app:processApplicationManifestReleaseForBundle UP-TO-DATE
[   +1 ms] > Task :app:bundleReleaseResources UP-TO-DATE
[   +1 ms] > Task :app:shrinkReleaseRes UP-TO-DATE
[   +3 ms] > Task :app:optimizeReleaseResources UP-TO-DATE
[   +2 ms] > Task :app:collectReleaseDependencies UP-TO-DATE
[   +4 ms] > Task :app:compressReleaseAssets
[   +3 ms] Execution optimizations have been disabled for task ':app:compressReleaseAssets' to ensure correctness due to the following reasons:       
[   +1 ms]   - Gradle detected a problem with the following location: 'E:\Test Area\Flutter
dummy\flutter_application_1\build\app\intermediates\assets\release\mergeReleaseAssets'. Reason: Task ':app:compressReleaseAssets' uses this output of 
task ':app:copyFlutterAssetsRelease' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced,
depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for
more details about this problem.
[  +76 ms] > Task :app:sdkReleaseDependencyData UP-TO-DATE
[   +3 ms] > Task :app:validateSigningRelease UP-TO-DATE
[   +2 ms] > Task :app:writeReleaseAppMetadata UP-TO-DATE
[   +2 ms] > Task :app:writeReleaseSigningConfigVersions UP-TO-DATE
[   +9 ms] > Task :app:packageRelease UP-TO-DATE
[  +29 ms] > Task :app:createReleaseApkListingFileRedirect UP-TO-DATE
[ +257 ms] > Task :app:assembleRelease
[  +90 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[   +1 ms] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.  
[   +2 ms] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[   +3 ms] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[   +1 ms] Please consult deprecation warnings for more details.
[   +4 ms] BUILD SUCCESSFUL in 9s
[   +3 ms] 49 actionable tasks: 8 executed, 41 up-to-date
[ +568 ms] Running Gradle task 'assembleRelease'... (completed in 10.4s)
[  +21 ms] calculateSha: LocalDirectory: 'E:\Test Area\Flutter dummy\flutter_application_1\build\app\outputs\flutter-apk'/app.apk
[  +79 ms] √  Built build\app\outputs\flutter-apk\app-release.apk (5.3MB).
[   +3 ms] "flutter apk" took 11,099ms.
[  +85 ms] ensureAnalyticsSent: 80ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

</details>

I wasn't able to build `android-arm` apk with the `--analyze-size` flag

_Originally posted by @OutdatedGuy in https://github.com/flutter/flutter/issues/97764#issuecomment-1142498153_

**Comment by huycozy** [comment]
Hi @OutdatedGuy 
I reopened your issue #97764
Closing as a duplication, so please follow up on it for further updates.
