### ISSUE TITLE
Null check error when using "Show Debug Paint" for some widgets

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [flutter/flutter#105969]
Error is thrown when using "Show Debug Paint" from Android Studio. The issue is reproducible when using some specific widgets, e.g. SliverAppBar, BottomAppBar.

## Steps to Reproduce

1. Start sample app (below)
2. Enable debug paint
3. Observe crash

SliverAppBar example app
```dart
import 'package:flutter/material.dart';
 
void main() => runApp(const MyApp());
 
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
 
  static const String _title = 'Flutter Code Sample';
 
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}
 
class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);
 
  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}
 
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  bool _pinned = true;
  bool _snap = false;
  bool _floating = false;
 
// [SliverAppBar]s are typically used in [CustomScrollView.slivers], which in
// turn can be placed in a [Scaffold.body].
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar(
            pinned: _pinned,
            snap: _snap,
            floating: _floating,
            expandedHeight: 160.0,
            flexibleSpace: const FlexibleSpaceBar(
              title: Text('SliverAppBar'),
              background: FlutterLogo(),
            ),
          ),
          const SliverToBoxAdapter(
            child: SizedBox(
              height: 20,
              child: Center(
                child: Text('Scroll to see the SliverAppBar in effect.'),
              ),
            ),
          ),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index) {
                return Container(
                  color: index.isOdd ? Colors.white : Colors.black12,
                  height: 100.0,
                  child: Center(
                    child: Text('$index', textScaleFactor: 5),
                  ),
                );
              },
              childCount: 20,
            ),
          ),
        ],
      ),
      bottomNavigationBar: BottomAppBar(
        child: Padding(
          padding: const EdgeInsets.all(8),
          child: OverflowBar(
            overflowAlignment: OverflowBarAlignment.center,
            children: <Widget>[
              Row(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  const Text('pinned'),
                  Switch(
                    onChanged: (bool val) {
                      setState(() {
                        _pinned = val;
                      });
                    },
                    value: _pinned,
                  ),
                ],
              ),
              Row(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  const Text('snap'),
                  Switch(
                    onChanged: (bool val) {
                      setState(() {
                        _snap = val;
                        // Snapping only applies when the app bar is floating.
                        _floating = _floating || _snap;
                      });
                    },
                    value: _snap,
                  ),
                ],
              ),
              Row(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  const Text('floating'),
                  Switch(
                    onChanged: (bool val) {
                      setState(() {
                        _floating = val;
                        _snap = _snap && _floating;
                      });
                    },
                    value: _floating,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

Error thrown:

```
======== Exception caught by rendering library =====================================================
The following _CastError was thrown during paint():
Null check operator used on a null value
 
The relevant error-causing widget was: 
  SliverAppBar SliverAppBar:google3:///mobile/flutter/samples/hello_flutter/app/lib/main.dart:38:11
When the exception was thrown, this was the stack: 
#0      RenderClipPath.debugPaintSize.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:1854:38)
#1      RenderClipPath.debugPaintSize (package:flutter/src/rendering/proxy_box.dart:1858:6)
#2      RenderBox.debugPaint.<anonymous closure> (package:flutter/src/rendering/box.dart:2725:9)
#3      RenderBox.debugPaint (package:flutter/src/rendering/box.dart:2734:6)
#4      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2722:7)
```

**Comment by maheshmnj** [comment]
Hi @ChristianEdwardPadilla, Thanks for filing the issue. I am able to reproduce the issue on stable and the master channel.  

```
Launching lib/main.dart on sdk gphone arm64 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:49293/_xhyFY8QH2w=/ws

════════ Exception caught by rendering library ═════════════════════════════════
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was
SliverAppBar
When the exception was thrown, this was the stack
#0      RenderClipPath.debugPaintSize.<anonymous closure>
#1      RenderClipPath.debugPaintSize
#2      RenderBox.debugPaint.<anonymous closure>
#3      RenderBox.debugPaint
#4      RenderObject._paintWithContext.<anonymous closure>
#5      RenderObject._paintWithContext
#6      PaintingContext.paintChild
#7      RenderProxyBoxMixin.paint
#8      RenderObject._paintWithContext
#9      PaintingContext.paintChild
#10     RenderBoxContainerDefaultsMixin.defaultPaint
#11     RenderStack.paintStack
#12     RenderStack.paint
#13     RenderObject._paintWithContext
#14     PaintingContext.paintChild
#15     RenderProxyBoxMixin.paint
#16     RenderObject._paintWithContext
#17     PaintingContext.paintChild
#18     RenderProxyBoxMixin.paint
#19     _RenderInkFeatures.paint
#20     RenderObject._paintWithContext
#21     PaintingContext.paintChild
#22     RenderProxyBoxMixin.paint
#23     PaintingContext.pushLayer
#24     RenderPhysicalModel.paint
#25     RenderObject._paintWithContext
#26     PaintingContext.paintChild
#27     RenderProxyBoxMixin.paint
#28     PaintingContext.pushLayer
#29     RenderAnnotatedRegion.paint
#30     RenderObject._paintWithContext
#31     PaintingContext.paintChild
#32     RenderProxyBoxMixin.paint
#33     RenderObject._paintWithContext
#34     PaintingContext.paintChild
#35     RenderSliverPersistentHeader.paint
#36     RenderObject._paintWithContext
#37     PaintingContext.paintChild
#38     RenderViewportBase._paintContents
#39     PaintingContext.pushLayer
#40     PaintingContext.pushClipRect
#41     RenderViewportBase.paint
#42     RenderObject._paintWithContext
#43     PaintingContext._repaintCompositedChild
#44     PaintingContext.repaintCompositedChild
#45     PipelineOwner.flushPaint
#46     RendererBinding.drawFrame
#47     WidgetsBinding.drawFrame
#48     RendererBinding._handlePersistentFrameCallback
#49     SchedulerBinding._invokeFrameCallback
#50     SchedulerBinding.handleDrawFrame
#51     SchedulerBinding._handleDrawFrame
#55     _invoke (dart:ui/hooks.dart:151:10)
#56     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#57     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#72872 relayoutBoundary=up8
RenderObject: RenderSemanticsAnnotations#72872 relayoutBoundary=up8
    parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(w=392.7, 0.0<=h<=184.0)
    size: Size(392.7, 184.0)
    child: RenderClipPath#252e6 relayoutBoundary=up9
        parentData: <none> (can use size)
        constraints: BoxConstraints(w=392.7, 0.0<=h<=184.0)
        size: Size(392.7, 184.0)
        child: RenderCustomPaint#616e0 relayoutBoundary=up10
            parentData: <none> (can use size)
            constraints: BoxConstraints(w=392.7, 0.0<=h<=184.0)
            size: Size(392.7, 184.0)
            painter: null
            foregroundPainter: _ShapeBorderPainter#4cf57()
            child: _RenderInkFeatures#4d1d9 relayoutBoundary=up11
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=392.7, 0.0<=h<=184.0)
                size: Size(392.7, 184.0)
                child: RenderPositionedBox#510a3 relayoutBoundary=up12
                    parentData: <none> (can use size)
                    constraints: BoxConstraints(w=392.7, 0.0<=h<=184.0)
                    size: Size(392.7, 184.0)
                    alignment: Alignment.topCenter
                    textDirection: ltr
                    widthFactor: expand
                    heightFactor: expand
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was
BottomAppBar
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/rendering/layer.dart': Failed assertion: line 713 pos 12: 'picture != null': is not true.
════════════════════════════════════════════════════════════════════════════════

```

**Comment by jeff-odopass** [comment]
I just filled a new issue for the exact same problem before finding yours.
I'va added more details in it and a minimum reproductible example, here is the link : https://github.com/flutter/flutter/issues/106022.

The issue is critical and prevent us from going forward actually
