### ISSUE TITLE
Tree red on tool test failure: "test/commands.shard/hermetic/run_test.dart"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#105924]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_tests_commands/5443/overview on tip of tree

**Comment by christopherfujino** [comment]
First failed on https://github.com/flutter/flutter/pull/105874

**Comment by christopherfujino** [comment]
I think this is due to today's random seed

**Comment by jmagman** [comment]
For posterity the failure is
```
00:53 +419 -1: test/commands.shard/hermetic/run_test.dart: run run app passes device target platform to usage [E]                                                                                      
  ToolExit expected, got UnimplementedError: hasTerminal
  #0      Fake.noSuchMethod (package:test_api/src/frontend/fake.dart:50:5)
  #1      FakeStdin.hasTerminal (dart:io/stdio.dart:187:12)
  #2      Stdio.stdinHasTerminal (package:flutter_tools/src/base/io.dart:302:18)
  #3      AnsiTerminal.singleCharMode= (package:flutter_tools/src/base/terminal.dart:283:17)
  #4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:722:24)
```

**Comment by aam** [comment]
The error seems real as the https://github.com/flutter/flutter/pull/105462 did introduce `hasTerminal` with seemingly invalid override pragma
