### ISSUE TITLE
Process flutter finished with non-zero exit value 1

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#105952]
Hi, my app was building and running fine yesterday. This morning it's giving me the non-zero exit value error that seems to keep cropping up. 

I've tried upgraded flutter, running flutter clean but I can no longer get it to run. I've included (hopefully) all the necessary details below.

## Logs

<details>
<summary>flutter run error</summary>

```

jimmyff@jimmys-mbp os_app % flutter run --debug -v > ../flutter-build-error.txt
[ +498 ms] [+2580 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux-0.9.0/lib/flutter_redux.dart:474:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
[        ] [        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ] [        ]       WidgetsBinding.instance?.addPostFrameCallback((_) {
[        ] [        ]                      ^
[        ] [   +2 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux-0.9.0/lib/flutter_redux.dart:577:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
[        ] [        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ] [        ]       WidgetsBinding.instance?.addPostFrameCallback((_) {
[        ] [        ]                      ^
[  +83 ms] [+1471 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:32:39: Error: Expected ';' after this.
[        ] [        ]       'name: ${navigationAction.name}')
[        ] [        ]                                       ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:33:48: Error: Expected ';' after this.
[        ] [        ]       'predicate: ${navigationAction.predicate}')
[        ] [        ]                                                ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:33:49: Error: Expected an identifier, but got ')'.
[        ] [        ] Try inserting an identifier before ')'.
[        ] [        ]       'predicate: ${navigationAction.predicate}')
[        ] [        ]                                                 ^
[        ] [   +1 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:33:49: Error: Unexpected token ')'.
[        ] [        ]       'predicate: ${navigationAction.predicate}')
[        ] [        ]                                                 ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:34:48: Error: Expected ';' after this.
[        ] [        ]       'arguments: ${navigationAction.arguments}');
[        ] [        ]                                                ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:34:49: Error: Expected an identifier, but got ')'.
[        ] [        ] Try inserting an identifier before ')'.
[        ] [        ]       'arguments: ${navigationAction.arguments}');
[        ] [        ]                                                 ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:34:49: Error: Unexpected token ')'.
[        ] [        ]       'arguments: ${navigationAction.arguments}');
[        ] [        ]                                                 ^
[ +899 ms] [ +910 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/intl_phone_number_input-0.7.0+2/lib/src/widgets/input_widget.dart:321:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ] [        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ] [        ]     WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
[        ] [        ]                    ^
[        ] [   +5 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.4/lib/src/pinput_state.dart:81:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ] [        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ] [        ]     WidgetsBinding.instance!.addObserver(this);
[        ] [        ]                    ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.4/lib/src/pinput_state.dart:190:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ] [        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ] [        ]     WidgetsBinding.instance!.removeObserver(this);
[        ] [        ]                    ^
[        ] [  +20 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_placeholder_textlines-1.1.2/lib/placeholder_lines.dart:113:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ] [        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ] [        ]     WidgetsBinding.instance!.addPostFrameCallback(_setupAnimation);
[        ] [        ]                    ^
[        ] [  +12 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/confetti-0.6.0/lib/src/confetti.dart:229:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ] [        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ] [        ]     WidgetsBinding.instance!.addPostFrameCallback((_) {
[        ] [        ]                    ^
[        ] [   +7 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/cached_network_image_provider.dart:109:29: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
[        ] [        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/painting/binding.dart').
[        ] [        ]       () => PaintingBinding.instance?.imageCache?.evict(key),
[        ] [        ]                             ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/multi_image_stream_completer.dart:152:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
[        ] [        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ] [        ]     SchedulerBinding.instance?.scheduleFrameCallback(_handleAppFrame);
[        ] [        ]                      ^
[ +494 ms] [ +508 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/reorderables-0.4.3/lib/src/widgets/passthrough_overlay.dart:133:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ] [        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ] [        ]     if (SchedulerBinding.instance!.schedulerPhase ==
[        ] [        ]                          ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/reorderables-0.4.3/lib/src/widgets/passthrough_overlay.dart:135:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ] [        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ] [        ]       SchedulerBinding.instance!.addPostFrameCallback((Duration duration) {
[        ] [        ]                        ^
[ +304 ms] [ +289 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/ink_page_indicator-0.2.1/lib/src/base/page_indicator.dart:123:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ] [        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../sdks/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ] [        ]       WidgetsBinding.instance!.addPostFrameCallback(
[        ] [        ]                      ^
[        ] [   +1 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:241:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
[        ]            <asynchronous suspension>
[        ]            #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
[        ]            <asynchronous suspension>
[        ]            #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:320:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
[        ]            <asynchronous suspension>
[        ]            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
[        ]            <asynchronous suspension>
[        ]            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     main (package:flutter_tools/executable.dart:94:3)
[        ]            <asynchronous suspension>
[        ] [   +2 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:337:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:94:3)
[        ]            <asynchronous suspension>
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/jimmyff/sdks/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1156
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/Users/jimmyff/sdks/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 11s
[   +1 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


```

</details>
<details>
<summary>flutter doctor -v</summary>

```
jimmyff@jimmys-mbp os_app % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.0.2 at /Users/jimmyff/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (6 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • Pixel 5 (mobile) • 09021FDD40027X • android-arm64 • Android 12 (API 31)
    • macOS (desktop)  • macos          • darwin-arm64  • macOS 12.4 21F79 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>
<details>
<summary>flutter.gradle line 1156</summary>

```gradle

        project.exec {
            logging.captureStandardError LogLevel.ERROR
            executable flutterExecutable.absolutePath
            workingDir sourceDir
            if (localEngine != null) {
                args "--local-engine", localEngine
                args "--local-engine-src-path", localEngineSrcPath
            }
            if (verbose) {
                args "--verbose"
            } else {
                args "--quiet"
            }
            args "assemble"
            args "--no-version-check"
            args "--depfile", "${intermediateDir}/flutter_build.d"
            args "--output", "${intermediateDir}"
            if (performanceMeasurementFile != null) {
                args "--performance-measurement-file=${performanceMeasurementFile}"
            }
            if (!fastStart || buildMode != "debug") {
                args "-dTargetFile=${targetPath}"
            } else {
                args "-dTargetFile=${Paths.get(flutterRoot.absolutePath, "examples", "splash", "lib", "main.dart")}"
            }
            args "-dTargetPlatform=android"
            args "-dBuildMode=${buildMode}"
            if (trackWidgetCreation != null) {
                args "-dTrackWidgetCreation=${trackWidgetCreation}"
            }
            if (splitDebugInfo != null) {
                args "-dSplitDebugInfo=${splitDebugInfo}"
            }
            if (treeShakeIcons == true) {
                args "-dTreeShakeIcons=true"
            }
            if (dartObfuscation == true) {
                args "-dDartObfuscation=true"
            }
            if (dartDefines != null) {
                args "--DartDefines=${dartDefines}"
            }
            if (bundleSkSLPath != null) {
                args "-dBundleSkSLPath=${bundleSkSLPath}"
            }
            if (codeSizeDirectory != null) {
                args "-dCodeSizeDirectory=${codeSizeDirectory}"
            }
            if (extraGenSnapshotOptions != null) {
                args "--ExtraGenSnapshotOptions=${extraGenSnapshotOptions}"
            }
            if (extraFrontEndOptions != null) {
                args "--ExtraFrontEndOptions=${extraFrontEndOptions}"
            }
            args ruleNames
        }
```

</details>

Output of `flutter run --debug -v`
[flutter-build-error.txt](https://github.com/flutter/flutter/files/8899546/flutter-build-error.txt)

Thanks,
Jimmy

**Comment by jimmyff** [comment]
Hey @huycozy thanks for the response, I can confirm a new flutter project works correctly.

I have included my pubspec in case that is of use:

<details>

<summary>pubspec.yaml</summary>

```yaml

name: myappname
description: A new Flutter project.
publish_to: none

version: 0.1.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.2
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  redux_logging: any
  flutter_redux: ^0.9.0
  flutter_redux_navigation: ^0.7.0
  intl: any
  uuid: any

  page_transition: ^2.0.2

  logging: ^1.0.1

  path_provider: any # path_provider required for temp directory on upload
  image: ^3.0.2
  image_picker: any
  palette_generator: any
  image_cropper: ^1.2.3

  blurhash_dart: ^1.0.2
  shimmer: any

  photofilters: ^3.0.1
  exif: ^3.1.1
  reorderables: any
  in_app_purchase: ^3.0.2
  dotted_border: any
  flutter_image: ^4.1.0
  meta: ^1.1.8
  onescene_brand:
    path: ../os_brand
  os_core:
    path: ../os_core
  chroma:
    path: ../chroma

  http: ^0.13.4
  # bitmap: ^0.1.2

  device_info: any

  # Firebase - version locked for issue
  # https://github.com/FirebaseExtended/flutterfire/issues/1969
  # 0.14+ should resolve...

  firebase_core: ^1.5.0
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.0.2
  firebase_storage: ^10.0.2
  firebase_analytics: ^9.0.4
  firebase_remote_config: ^2.0.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.0.3
  audioplayers: ^0.20.1
  store_redirect: ^2.0.1
  flutter_markdown: ^0.6.9+1

  url_launcher: ^6.0.18
  csv: ^5.0.1

  # TODO: ADD THIS
  # firebase_crashlytics: ^0.2.0

  googleapis: ^8.0.0
  package_info: any
  encrypt: any

  quiver: any
  cloud_firestore_platform_interface: any

  settings_ui: ^2.0.2
  ink_page_indicator: ^0.2.1
  transparent_image: ^2.0.0
  cached_network_image: ^3.1.0

  # For geo
  geolocator: ^8.2.0

  # for GCP
  googleapis_auth: ^1.0.0

  # Auth
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^4.0.1
  sign_in_with_apple: ^3.0.0

  crypto: ^3.0.1
  intl_phone_number_input: ^0.7.0+2
  pinput: ^2.2.4

  confetti: ^0.6.0-nullsafety
  material_design_icons_flutter: ^5.0.5955-rc.1
  badges: ^2.0.1
  animate_countdown_text: ^1.1.2
  flutter_placeholder_textlines: ^1.1.2

  cupertino_icons: ^1.0.3

  recase: any

  shared_preferences: any


dev_dependencies:
  lints: ^1.0.1
  flutter_test:
    sdk: flutter


```

</details>

**Comment by jimmyff** [comment]
My packages are as up to date as they can be:

<details>

<summary>flutter pub outdated</summary>

```
jimmyff@jimmys-mbp os_app % flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name                              Current  Upgradable  Resolvable  Latest  

direct dependencies:                     
meta                                      *1.7.0   *1.7.0      *1.7.0      1.8.0   

dev_dependencies: all up-to-date.        

transitive dependencies:                 
async                                     *2.8.2   *2.8.2      *2.8.2      2.9.0   
characters                                *1.2.0   *1.2.0      *1.2.0      1.2.1   
copy_with_extension                       *2.0.2   *2.0.2      *2.0.2      4.0.2   
flutter_facebook_auth_platform_interface  *3.1.2   *3.1.2      *3.1.2      4.0.0   
flutter_facebook_auth_web                 *3.1.2   *3.1.2      *3.1.2      4.0.0   
material_color_utilities                  *0.1.4   *0.1.4      *0.1.4      0.1.5   
path                                      *1.8.1   *1.8.1      *1.8.1      1.8.2   
source_span                               *1.8.2   *1.8.2      *1.8.2      1.9.0   
string_scanner                            *1.1.0   *1.1.0      *1.1.0      1.1.1   
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
```
</details>

**Comment by jimmyff** [comment]
This is also affecting another of my apps that I have.

<details>
<summary>Here is the android/build.gradle for this project:</summary>

```gradle

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"


// added by jimmy for firebase
apply plugin: 'com.google.gms.google-services'

// Added by Jimmy for signing
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}


android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion '24.0.8215888'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.foo.bar"
        minSdkVersion 21
        // targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        
        // added by jimmy for multidexing    
        multiDexEnabled true
    }

    // Added bu jimmy for signing
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // added by jimmy for firebase
    implementation "androidx.multidex:multidex:2.0.0" // use latest version
}

```
</details>

**Comment by huycozy** [comment]
@jimmyff 

> Hey @huycozy thanks for the response, I can confirm a new flutter project works correctly.
> 
> I have included my pubspec in case that is of use:
> 
> pubspec.yaml

Please try to create a completely new project to make sure your Flutter setup is still fine.

```bash
[  +83 ms] [+1471 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:32:39: Error: Expected ';' after this.
[        ] [        ]       'name: ${navigationAction.name}')
[        ] [        ]                                       ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:33:48: Error: Expected ';' after this.
[        ] [        ]       'predicate: ${navigationAction.predicate}')
[        ] [        ]                                                ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:33:49: Error: Expected an identifier, but got ')'.
[        ] [        ] Try inserting an identifier before ')'.
[        ] [        ]       'predicate: ${navigationAction.predicate}')
[        ] [        ]                                                 ^
[        ] [   +1 ms] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:33:49: Error: Unexpected token ')'.
[        ] [        ]       'predicate: ${navigationAction.predicate}')
[        ] [        ]                                                 ^
[        ] [        ] ../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux_navigation-0.7.1/lib/src/navigation_middleware.dart:34:48: Error: Expected ';' after this.
[        ] [        ]       'arguments: ${navigationAction.arguments}');
```
And from your above `flutter run` output, I see there are errors of `flutter_redux_navigation` that could lead to the failed run.
Could you remove `flutter_redux_navigation` and retry running?
