### ISSUE TITLE
Shell subprocess crashed with unexpected exit code -4.

### ISSUE THREAD

**Issue by ejan-089** [flutter/flutter#105943]
### Steps to reproduce

1. run `flutter clean`
2. run `flutter pub get`
3. run `flutter test`

### Expected result

Flutter can load test files and run all tests.

### Actual result

Flutter failed to load tests.
The error messages look like this:
```
root@5e65703a14dd:/flutter/project/root/dir# flutter test
00:07 +6 -1: loading /flutter/project/root/dir/test/path/to/case_test.dart [E]
  Failed to load "/flutter/project/root/dir/test/path/to/case_test.dart": Shell subprocess crashed with unexpected exit code -4.
00:15 +37 -1: ... ChatDetails Check if title is correctly rendered.                                                          unhandled error during finalization of test:
/flutter/project/root/dir/test/path/to/case2_test.dart
TestDeviceException(Shell subprocess crashed with unexpected exit code -4.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:224:5)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>


00:20 +48 -1: ... ChatDetails Check if title is correctly rendered.                                                          unhandled error during finalization of test:
/flutter/project/root/dir/test/path/to/case3_test.dart
TestDeviceException(Shell subprocess crashed with unexpected exit code -4.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:224:5)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>

```

Unfortunately, it happens inconsistently.
There are 400+ test cases, and I end up with around 10 failed test cases at random for the above reason.
If I run the test individually via `flutter test test/path/to/test/file_test.dart`, it passed but sometimes fail if I repeat.

### Environment

I'm using M1 Macbook Pro.
I use docker-compose to run the tests.
This is my Dockerfile for the image I use:
```yml
# Use the python image
FROM python:3.9.7-slim-bullseye

# Install required packages
RUN apt update && apt install -y git curl unzip lcov \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# Install Flutter
ENV FLUTTER_VERSION=2.2.3
ENV FLUTTER_HOME=/usr/local/flutter
ENV PATH "$PATH:$FLUTTER_HOME/bin"
RUN \
    git clone --depth 1 --branch ${FLUTTER_VERSION} https://github.com/flutter/flutter.git ${FLUTTER_HOME} && \
    flutter doctor
```

### flutter doctor -v

```
# flutter doctor -v
[✓] Flutter (Channel unknown, 2.2.3, on Linux, locale C.UTF-8)
    • Flutter version 2.2.3 at /usr/local/flutter
    • Framework revision f4abaa0735 (12 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by danagbemava-nc** [comment]
Hi @ejan-089, appear to be using an older version of flutter. Kindly upgrade to the latest version of flutter to see if you still experience this issue. If you do, please provide the updated `flutter doctor -v` as well as complete verbose logs. 

Do you also experience this issue with the tests if you run the locally?

Also, what type of tests are you running? flutter unit tests or integration tests?

**Comment by ejan-089** [comment]
@danagbemava-nc 
I tried it using Flutter 3.0.2, and it worked fine.
Thanks.

P.S. it was flutter unit tests.
