### ISSUE TITLE
In Android, Flutter screenshot of first state to background when background transparent

### ISSUE THREAD

**Issue by onatcipli** [flutter/flutter#106084]
## Steps to Reproduce

I have a problem with my application, the problem is appearing only in android devices in iOS I'm not seeing this problem, and it's very strange. I will attach and video but the sort explanation is I have a chat page and in android, the chat page scrollable part is like taking a screenshot of its first state and pasting it to the background, and that causes overlapping but if I give some color to the background the issue solved. The background needs to be transparent because there could be some background images on the page.

We didn't have a problem like this before and it's only happening in android We are creating the landscape of that page and the widget tree is getting bigger and bigger may this cause this problem?

Flutter version ; `Channel stable, 2.5.2` maybe already fixed in newer versions

**Expected results:** 
I was expecting the background was transparent

**Actual results:** 
I see that background has the first state of the widget you take a screenshot of that widget and paste that screenshot to that background.

</details>

<details>
  <summary>Logs</summary>

The console log has no issues

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.1 21C52 darwin-arm, locale en-TR)
    • Flutter version 2.5.2 at /Users/onatcipli/fvm/versions/2.5.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (9 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/onatcipli/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Users/onatcipli/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.3.1, Build version 13E500a
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/onatcipli/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/onatcipli/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/onatcipli/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/onatcipli/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 67.0.3
    • Dart plugin version 213.7371

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/onatcipli/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 102.0.5005.115

• No issues found!

```

</details>

https://user-images.githubusercontent.com/26159899/173990987-cfc1d8e1-fe83-482d-bc9b-bc2e1f0dc89f.mov

**Comment by danagbemava-nc** [comment]
Hi @onatcipli, you are on an older version of flutter, and unfortunately, we do not provide support for older versions. 
As such I would advise you to upgrade to the latest version of stable to see whether or not you still experience this issue. 

If you do, kindly provide the updated `flutter doctor -v` as well as a complete minimal reproducible code sample, preferably without any third-party package/plugins so that we can investigate this. 

Thank you

**Comment by moesama** [comment]
Same problem with flutter 3.0.2，happens randomly on Android when back to app from launcher\recent tasks.

I have tried to make background color using a 50% alpha white, and it seems that the screenshot is under the background, according to facts above, I think **transparent background is not the true cause of this issue, it just can't be seen when background has no alpha, but it exists there**.

This issue has been exist at least from flutter 2.0, and my team may have give up flutter only because this unnecessary bug.

Hope the flutter team could put some effort on this issue, thank you~

here is the `flutter doctor -v` log:
```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.0.2 at /Users/moesama/Develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (13 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/moesama/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • V2046A (mobile) • 000008f58d8589a0 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos            • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome           • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @moesama, can you provide a minimal sample so that we can investigate this?

**Comment by moesama** [comment]
@danagbemava-nc , thanks for your reply.

I have a minimal sample here [https://github.com/moesama/GhostDemo](url)

## Steps to Reproduce

1. start up the demo app;
2. fast scroll the list, make sure it is animating;
3. press home key or back key;
4. switch back to the demo app quickly;
5. if you are lucky(not lucky at all), you will find there is a screenshot on the back.

notice: I use FlutterFragment instead of FlutterActivity to have an independent view on the back, I have no idea if that is one of the reasons why it happens, but my product needs that.

**Comment by danagbemava-nc** [comment]
Hi @moesama, when I run your sample I get the exception below, can you check? 


<details>
<summary>logs</summary>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.vc/com.example.vc.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(19779): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3494)
E/AndroidRuntime(19779): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3666)
E/AndroidRuntime(19779): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(19779): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(19779): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(19779): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112)
E/AndroidRuntime(19779): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19779): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(19779): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
E/AndroidRuntime(19779): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19779): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/AndroidRuntime(19779): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime(19779): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(19779): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
E/AndroidRuntime(19779): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
E/AndroidRuntime(19779): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
E/AndroidRuntime(19779): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/AndroidRuntime(19779): 	at com.example.vc.MainActivity.onCreate(MainActivity.kt:17)
E/AndroidRuntime(19779): 	at android.app.Activity.performCreate(Activity.java:8109)
E/AndroidRuntime(19779): 	at android.app.Activity.performCreate(Activity.java:8083)
E/AndroidRuntime(19779): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
E/AndroidRuntime(19779): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3467)
E/AndroidRuntime(19779): 	... 11 more
Exited
```
</details>

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master` using the code sample and the steps outlined in https://github.com/flutter/flutter/issues/106084#issuecomment-1161793900. 

The code sample has been attached below for easier repro. I did have to increase the items in the list to give more room for scrolling. 

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/175891035-d3ea54f3-6c75-4acb-87a7-57f63649e148.mp4
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.0.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (5 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1376, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1376 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3598f20002 (10 hours ago), 2022-06-26 18:19:04 -0400
    • Engine revision ee56813c14
    • Dart version 2.18.0 (build 2.18.0-228.0.dev)
    • DevTools version 2.14.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[GhostDemo.zip](https://github.com/flutter/flutter/files/8989819/GhostDemo.zip)

**Comment by chinmaygarde** [comment]
The scaffold has a transparent background. I am not sure what the expected behavior ought to be. The engine can't control what is beneath the Flutter view. Perhaps the solution is to use a texture view instead?

**Comment by dnfield** [comment]
I think using a TextureView on Android might make this work. Maybe there's some way to get it working with SurfaceView, but I'm not entirely sure about that. 

FWIW, I think this approach is probably going to create a bad UX - it would be better to just composite everything in Flutter so that you can properly handle gestures etc. For example, if something that looks like an interactive control shows up in the transparent area, it will not actually be interactive...

**Comment by moesama** [comment]
Hi, @dnfield, these two workarounds may sounds good to other teams, but not to us.

Our team needs to render an opengl content behind the ui, I have tried **PlatformView and sharing Texture**, they both have **frame drop** issue;
By the way, use TextureView will lead to frame drop on UI layer, **our product pay great attention to fluency**;

So, unless there is a way to composite everything(include the opengl content) in Flutter with no frame drop, we can only keep on using the native view behind FlutterFragment.

**Comment by dnfield** [comment]
Have you considered using a `Texture` widget?

It's a little hard to help here - the use case isn't entirely clear to me. Yes, using a TextureView will be slower than a SurfaceView. It's possible there's some way to use SurfaceView here but it will probably take some experimentation with the Android embedding.

**Comment by moesama** [comment]
After these days with some deeper testing, I found this issue seems not blame to flutter, it is an issue from Android SurfaceView.
It happens when two SurfaceView overlying and the one in the front has a clear color with alpha below 1.

**Comment by moesama** [comment]
Btw, flutter's texture render mode has a splashing problem, it flashes in some area of the screen between a history state or just a texture from other render thread, I have not found a stable way to reproduce this problem yet.
