### ISSUE TITLE
local_auth: Following Installation and ReadMe instructions leads to code that crashes

### ISSUE THREAD

**Issue by labaxter** [flutter/flutter#106045]
It is possible that this is an environment issue, so First my environment:

The flutter version:

```
$ flutter doctor  -v

[✓] Flutter (Channel stable, 3.0.2, on Debian GNU/Linux 11 (bullseye) 5.10.0-11-amd64, locale en_US.UTF-8)
    • Flutter version 3.0.2 at /home/lab/devel/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (7 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/lab/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /home/lab/devel/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/lab/devel/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Debian GNU/Linux 11 (bullseye) 5.10.0-11-amd64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
The Andriod Studio version:

Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 28, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-11-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart (212.5744), IdeaVIM (1.9.2), idea.plugin.protoeditor (212.5080.8), org.jetbrains.kotlin (212-1.6.21-release-334-AS5457.46), io.flutter (67.1.2), org.intellij.plugins.markdown (212.5457.16)
Current Desktop: XFCE
Steps to reproduce:
Create a new project with flutter create:

flutter create biometric
Creating project biometric...
Running "flutter pub get" in biometric...                          934ms
Wrote 127 files.

All done!
In order to run your application, type:
$ cd biometric
```

Open Project in Android studio, and run lib/main.dart, Flutter Demo Home Page Runs: (see image)
![image](https://user-images.githubusercontent.com/20759467/173875172-b6972cb6-4a03-45a3-b07e-23ddd723654f.png)

Now stop application and follow installation instructions:

```
$ flutter pub add local_auth
Resolving dependencies...
  async 2.8.2 (2.9.0 available)
  characters 1.2.0 (1.2.1 available)
+ flutter_plugin_android_lifecycle 2.0.6
+ intl 0.17.0
+ local_auth 2.1.0
+ local_auth_android 1.0.5
+ local_auth_ios 1.0.7
+ local_auth_platform_interface 1.0.4
+ local_auth_windows 1.0.1
  material_color_utilities 0.1.4 (0.1.5 available)
  meta 1.7.0 (1.8.0 available)
  path 1.8.1 (1.8.2 available)
+ plugin_platform_interface 2.1.2
  source_span 1.8.2 (1.9.0 available)
  string_scanner 1.1.0 (1.1.1 available)
Changed 8 dependencies!
```
In lib/main import local_auth package:

```
import 'package:flutter/material.dart';
import 'package:local_auth/local_auth.dart';
```

With no other changes, run lib/main, (it still runs but the there are compiler notes about using a deprecated API):

```
Running "flutter pub get" in biometric...
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Note: /home/lab/.pub-cache/hosted/pub.dartlang.org/local_auth_android-1.0.5/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:36277/mNCJcKlTLB0=/ws
Syncing files to device Android SDK built for x86...
```
Now follow Android integration instruction in ReadMe:
Modify `./android/app/src/main/kotlin/com/example/biometric/MainActivity.kt` with the following contents:

On opening the file contents are:

```
package com.example.biometric

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```
AND, Android studio highlights `imbedded` in the import line, and `FlutterActivity` in the class definition with unresolved symbol errors:

```
Unresolved reference: embedding
Unresolved reference: FlutterActivity
```
Before make the changes.. the app still runs.

Now replace the contents with:

```
import io.flutter.embedding.android.FlutterFragmentActivity

 class MainActivity: FlutterFragmentActivity() {
     // ...
 }
```

Now `imbedding` is still unresolved and `FlutterFragmentActivity` is unresolved.
Run the app again,
Following is the run output (and the application crashes):
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...

Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
E/AndroidRuntime(13270): FATAL EXCEPTION: main
E/AndroidRuntime(13270): Process: com.example.biometric, PID: 13270
E/AndroidRuntime(13270): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.biometric/com.example.biometric.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.biometric.MainActivity" on path: DexPathList[[zip file "/data/app/~~TCzieKco01xEtq05pWgBwA==/com.example.biometric-ZQiYz2-SQa6GxUQe6ATV1A==/base.apk"],nativeLibraryDirectories=[/data/app/~~TCzieKco01xEtq05pWgBwA==/com.example.biometric-ZQiYz2-SQa6GxUQe6ATV1A==/lib/x86, /data/app/~~TCzieKco01xEtq05pWgBwA==/com.example.biometric-ZQiYz2-SQa6GxUQe6ATV1A==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(13270): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
E/AndroidRuntime(13270): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(13270): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(13270): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(13270): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(13270): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(13270): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13270): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(13270): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(13270): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13270): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(13270): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(13270): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.biometric.MainActivity" on path: DexPathList[[zip file "/data/app/~~TCzieKco01xEtq05pWgBwA==/com.example.biometric-ZQiYz2-SQa6GxUQe6ATV1A==/base.apk"],nativeLibraryDirectories=[/data/app/~~TCzieKco01xEtq05pWgBwA==/com.example.biometric-ZQiYz2-SQa6GxUQe6ATV1A==/lib/x86, /data/app/~~TCzieKco01xEtq05pWgBwA==/com.example.biometric-ZQiYz2-SQa6GxUQe6ATV1A==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(13270): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(13270): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(13270): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(13270): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(13270): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
E/AndroidRuntime(13270): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
E/AndroidRuntime(13270): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
E/AndroidRuntime(13270): 	... 11 more
```
Continue Readme android integration with changes to ./android/app/src/main/AndroidManifest.xml, adding just below the `package=` line, and above  the `application` line
`
    <uses-permission android:name="android.permission.USE_BIOMETRIC"/>

`
Note that `android.permission.USE_FINGERPRINT` is crossed out as deprecated.

Run the application. It still crashes as above.

Change `USE_FINGERPRINT` to `USE_BIOMETRIC`

Application still crashes.

Comment out import of `local_auth.dart` in lib/main.dart; application still crashes;

Replace main.dart code with code from the example page:
<details>
<summary>code sample</summary>

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final LocalAuthentication auth = LocalAuthentication();
  _SupportState _supportState = _SupportState.unknown;
  bool? _canCheckBiometrics;
  List<BiometricType>? _availableBiometrics;
  String _authorized = 'Not Authorized';
  bool _isAuthenticating = false;

  @override
  void initState() {
    super.initState();
    auth.isDeviceSupported().then(
          (bool isSupported) => setState(() => _supportState = isSupported
              ? _SupportState.supported
              : _SupportState.unsupported),
        );
  }

  Future<void> _checkBiometrics() async {
    late bool canCheckBiometrics;
    try {
      canCheckBiometrics = await auth.canCheckBiometrics;
    } on PlatformException catch (e) {
      canCheckBiometrics = false;
      print(e);
    }
    if (!mounted) {
      return;
    }

    setState(() {
      _canCheckBiometrics = canCheckBiometrics;
    });
  }

  Future<void> _getAvailableBiometrics() async {
    late List<BiometricType> availableBiometrics;
    try {
      availableBiometrics = await auth.getAvailableBiometrics();
    } on PlatformException catch (e) {
      availableBiometrics = <BiometricType>[];
      print(e);
    }
    if (!mounted) {
      return;
    }

    setState(() {
      _availableBiometrics = availableBiometrics;
    });
  }

  Future<void> _authenticate() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticate(
        localizedReason: 'Let OS determine authentication method',
        options: const AuthenticationOptions(
          useErrorDialogs: true,
          stickyAuth: true,
        ),
      );
      setState(() {
        _isAuthenticating = false;
      });
    } on PlatformException catch (e) {
      print(e);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Error - ${e.message}';
      });
      return;
    }
    if (!mounted) {
      return;
    }

    setState(
        () => _authorized = authenticated ? 'Authorized' : 'Not Authorized');
  }

  Future<void> _authenticateWithBiometrics() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticate(
        localizedReason:
            'Scan your fingerprint (or face or whatever) to authenticate',
        options: const AuthenticationOptions(
          useErrorDialogs: true,
          stickyAuth: true,
          biometricOnly: true,
        ),
      );
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Authenticating';
      });
    } on PlatformException catch (e) {
      print(e);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Error - ${e.message}';
      });
      return;
    }
    if (!mounted) {
      return;
    }

    final String message = authenticated ? 'Authorized' : 'Not Authorized';
    setState(() {
      _authorized = message;
    });
  }

  Future<void> _cancelAuthentication() async {
    await auth.stopAuthentication();
    setState(() => _isAuthenticating = false);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: ListView(
          padding: const EdgeInsets.only(top: 30),
          children: <Widget>[
            Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                if (_supportState == _SupportState.unknown)
                  const CircularProgressIndicator()
                else if (_supportState == _SupportState.supported)
                  const Text('This device is supported')
                else
                  const Text('This device is not supported'),
                const Divider(height: 100),
                Text('Can check biometrics: $_canCheckBiometrics\n'),
                ElevatedButton(
                  onPressed: _checkBiometrics,
                  child: const Text('Check biometrics'),
                ),
                const Divider(height: 100),
                Text('Available biometrics: $_availableBiometrics\n'),
                ElevatedButton(
                  onPressed: _getAvailableBiometrics,
                  child: const Text('Get available biometrics'),
                ),
                const Divider(height: 100),
                Text('Current State: $_authorized\n'),
                if (_isAuthenticating)
                  ElevatedButton(
                    onPressed: _cancelAuthentication,
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: const <Widget>[
                        Text('Cancel Authentication'),
                        Icon(Icons.cancel),
                      ],
                    ),
                  )
                else
                  Column(
                    children: <Widget>[
                      ElevatedButton(
                        onPressed: _authenticate,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: const <Widget>[
                            Text('Authenticate'),
                            Icon(Icons.perm_device_information),
                          ],
                        ),
                      ),
                      ElevatedButton(
                        onPressed: _authenticateWithBiometrics,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: <Widget>[
                            Text(_isAuthenticating
                                ? 'Cancel'
                                : 'Authenticate: biometrics only'),
                            const Icon(Icons.fingerprint),
                          ],
                        ),
                      ),
                    ],
                  ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

enum _SupportState {
  unknown,
  supported,
  unsupported,
}

```
</details> 

Application still crashes, with same error as above. At this point I'm at a total loss for integrating local_auth into my application.

**Comment by maheshmnj** [comment]
Hi @labaxter, I am unable to reproduce the issue app builds fine for me on both emulator and a physical device. Ensure that you have added the fingerprint permission outside the application tag.


```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.sample">

    <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
   <application
        android:label="sample"
```



Also ensure that in your mainactivity.kt you have your app package name 


_Heres is my mainactivity.kt after configuration for reference_
```kt
package com.example.sample

import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}
```


Xiaomi k20 pro(Android 11)            |  Pixel 3 Api 30 Emulator
:-------------------------:|:-------------------------:
![flutter_03](https://user-images.githubusercontent.com/31410839/174049784-b478a0bc-43ee-405c-ad28-02fdb77c4475.png) | ![flutter_04](https://user-images.githubusercontent.com/31410839/174049793-0e2b1654-6837-4666-8772-90d53c6b309f.png)


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by labaxter** [comment]
THIS:
`package com.example.biometric
`
At the top of MainActivity seems to have done the trick.  Thank you.

Example application now compiles and runs. :-D

I would love to understand why Android Studio still complains about `embedding` and `FlutterFragmentActivity`:

![image](https://user-images.githubusercontent.com/20759467/174391926-a19e3b51-3501-49c1-a93a-25dc500f67e9.png)

I'm not sure if I can configure the emulator to authenticate biometrically. I'll dig for that answer.  But it does run and authenticate on my pixel 2 XL.

USE_FINGERPRINT permission does appear to be deprecated.  But USE_BIOMETRIC is not.  You might want to make a note of that in the readme. (But it does compile, install, and run with USE_FINGERPRINT)

![image](https://user-images.githubusercontent.com/20759467/174392591-21181434-1a69-4351-a376-4aae63e2173f.png)

And this is with USE_BIOMETRIC:
![image](https://user-images.githubusercontent.com/20759467/174392977-3b88c70a-1671-41f1-b0d4-6ee9c900217e.png)

Thanks for your quick response. I think I can move ahead with integration in my app. :-D

**Comment by labaxter** [comment]
See my response above.
