### ISSUE TITLE
Failed to send crash report due to a network error: SocketException: 信号灯超时时间已到

### ISSUE THREAD

**Issue by ylmyg** [flutter/flutter#106015]
Failed to send crash report due to a network error: SocketException: 信号灯超时时间已到
 (OS Error: 信号灯超时时间已到
, errno = 121), address = clients2.google.com, port = 52059
Oops; flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\YG2\FlutterSDK\flutter\packages\flutter_tools\templates\app_shared\.idea\libraries\Dart_SDK.xml.tmpl'".
A crash report has been written to D:\YG2\Flutter\flutter_03.log.

----
How can I solve it ?

**Comment by danagbemava-nc** [comment]
Hi @ylmyg, please share the contents of `D:\YG2\Flutter\flutter_03.log.`

Thank you

**Comment by ylmyg** [comment]
@danagbemava-nc Thank you
==============
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color create --template app --description A new Flutter project. --org com.example --platforms android,ios --project-name untitled3 untitled3

## exception

FileSystemException: FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\YG2\FlutterSDK\flutter\packages\flutter_tools\templates\app_shared\.idea\libraries\Dart_SDK.xml.tmpl'

```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#6      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:330:52)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#8      Template.render (package:flutter_tools/src/template.dart:253:24)
#9      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:479:21)
<asynchronous suspension>
#10     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:502:23)
<asynchronous suspension>
#11     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:317:31)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.0.2, on Microsoft Windows [版本 10.0.19043.928], locale zh-CN)
    • Flutter version 3.0.2 at D:\YG2\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (7 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\YG\SDK\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: D:\YG\AS2\AS-\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\SZ4311\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.31829.152
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\YG\AS2\AS-
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code (version 1.67.1)
    • VS Code at C:\Users\SZ4311\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • 21091116C (mobile) • 9pxoyhceq85xontc • android-arm64  • Android 11 (API 30)
    • Windows (desktop)  • windows          • windows-x64    • Microsoft Windows [版本 10.0.19043.928]
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 89.0.4389.90

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment]
There's an existing issue addressing this in https://github.com/flutter/flutter/issues/65021. 

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you
