### ISSUE TITLE
Failed assertion: line 570 pos 12: 'size.isFinite': is not true.

### ISSUE THREAD

**Issue by jeluyapp** [flutter/flutter#106081]
## Steps to Reproduce

To make reproduction easy I pushed the code with the error found here: https://github.com/jeluyapp/jeluymobile/commit/30b392fc2314c3f09853e0f9cb451f5472f11031

**Expected results:** 

A mostly blank project with a green navbar at the bottom.

**Actual results:**

A completely blank screen.

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 570 pos 12: 'size.isFinite': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Stack Stack:file:///home/bradly/Documents/jeluy/lib/navbar.dart:108:16

When the exception was thrown, this was the stack:
#2      RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:12)
#3      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:579:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#5      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277:14)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#11     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#12     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#13     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#15     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#19     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#20     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:955:48)
#21     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#22     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#27     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#62     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462:13)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#66     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749:15)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#75     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#85     RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#86     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#87     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#88     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#89     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#90     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#91     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#92     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#93     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderStack#b4e69 relayoutBoundary=up7
NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: Stack ← SizedBox ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ←
    NavbarElement ← Row ← Padding ← ColoredBox ← Container ← Navbar ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=Infinity, h=75.0)
  size: MISSING
  alignment: AlignmentDirectional.topStart
  textDirection: ltr
  fit: loose
This RenderObject had the following descendants (showing up to depth 5):
    child 1: RenderAnimatedOpacity#b13b8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderSemanticsAnnotations#8a788 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderExcludeSemantics#3cf9e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderConstrainedBox#3fbcb NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderPositionedBox#cbe03 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    child 2: RenderAnimatedOpacity#0f3f5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderFlex#96b4b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child 1: RenderParagraph#381d5 NEEDS-LAYOUT NEEDS-PAINT
          text: TextSpan
        child 2: RenderPadding#9f9d8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderConstrainedBox#71bd7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderDecoratedBox#b8582 NEEDS-LAYOUT NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: RenderBox was not laid out: RenderStack#b4e69 relayoutBoundary=up7 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#b6767 relayoutBoundary=up6 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderPointerListener#6f08f relayoutBoundary=up5 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#3a7c1 relayoutBoundary=up4 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderFlex#67f11 relayoutBoundary=up3 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderPadding#1b84c relayoutBoundary=up2 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: _RenderColoredBox#5fde3 relayoutBoundary=up1 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: _RenderColoredBox#5fde3 relayoutBoundary=up1

Another exception was thrown: Updated layout information required for RenderAnimatedOpacity#b13b8 NEEDS-LAYOUT NEEDS-PAINT to
calculate semantics.

Another exception was thrown: 'package:flutter/src/widgets/binding.dart': Failed assertion: line 866 pos 14:
'!_firstFrameCompleter.isCompleted': is not true.
```

```
```

```
```

</details>

**Comment by wuweijian1997** [comment]
You can try adding width to SizedBox.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/29529286/173985983-f863d87b-db26-4691-b778-d957d13ca245.png">

**Comment by danagbemava-nc** [comment]
Hi @jeluyapp, all you need to do is wrap your NavbarElements with `Expanded` and the error should go away. 

Closing this as an implementation error. 

<img width="1680" alt="Screenshot 2022-06-16 at 09 57 30" src="https://user-images.githubusercontent.com/88313112/174045504-fd85db36-9485-4dc6-af28-dd8fa558cc42.png">
