### ISSUE TITLE
App crashes on Android when the screen rotates using a Webview

### ISSUE THREAD

**Issue by LudmilKirov** [flutter/flutter#106173]
Using package:
webview_flutter: Tried  ^3.0.4 and  ^2.8.0
  
Steps to Reproduce:
1. Open a webview 
2. Rotate the phone

Device used:
moto e 7i power (mobile) • ZE222P5PCB • android-arm    • Android 10 (API 29)

<details>
<summary>logs</summary>

```
I/WebViewFactory(30274): Loading com.google.android.webview version 102.0.5005.78 (code 500507830)
I/WebViewFactory(30274): SystemProperties GMSVERSION = 10_202012.go
I/WebViewFactory(30274): Get WebViewChromiumFactoryProviderForO
W/test(30274): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/test(30274): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/test(30274): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/test(30274): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/test(30274): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider(30274): Loaded version=102.0.5005.78 minSdkVersion=29 isBundle=true multiprocess=false packageId=2
I/cr_LibraryLoader(30274): Successfully loaded native library
I/cr_CachingUmaRecorder(30274): Flushed 9 samples from 9 histograms.
E/chromium(30274): [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/com/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
E/chromium(30274): [ERROR:simple_index_file.cc(582)] Could not reconstruct index from disk
W/test(30274): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(30274): Requires BLUETOOTH permission
W/PlatformViewsController(30274): Creating a virtual display of size: [720, 1371] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1472, 720].
W/Gralloc3(30274): allocator 3.x is not supported
D/        (30274): Gralloc Register  w:720, h:1371, f:0x1, usage:0x300, ui64Stamp:998992, sSize:3964928, line = 2270
D/        (30274): Gralloc Free  w:720, h:1516, f:0x1, usage:0xb00, ui64Stamp:998760 line = 2376
D/        (30274): Gralloc Register  w:1516, h:720, f:0x1, usage:0xb00, ui64Stamp:999009, sSize:4378624, line = 2270
D/        (30274): Gralloc Free  w:720, h:1600, f:0x1, usage:0xb00, ui64Stamp:998680 line = 2376
D/        (30274): Gralloc Free  w:720, h:1600, f:0x1, usage:0xb00, ui64Stamp:998691 line = 2376
D/        (30274): Gralloc Free  w:720, h:1600, f:0x1, usage:0xb00, ui64Stamp:998694 line = 2376
D/        (30274): Gralloc Free  w:720, h:1516, f:0x1, usage:0xb00, ui64Stamp:998675 line = 2376
D/        (30274): Gralloc Free  w:1516, h:720, f:0x1, usage:0xb00, ui64Stamp:999009 line = 2376
D/        (30274): Gralloc Free  w:720, h:1516, f:0x1, usage:0xb00, ui64Stamp:998764 line = 2376
D/        (30274): Gralloc Register  w:720, h:1472, f:0x1, usage:0xb00, ui64Stamp:999013, sSize:4239360, line = 2270
D/SurfaceCallbackHelper(30274): dispatchSurfaceRedrawNeededAsync, callbacks=[Landroid.view.SurfaceHolder$Callback;@c14346c, callbacks.length=1
D/SurfaceCallbackHelper(30274): mFinishDrawingRunnable, mFinishDrawingCollected=1, mFinishDrawingExpected=1
D/        (30274): Gralloc Register  w:720, h:1556, f:0x1, usage:0xb00, ui64Stamp:999022, sSize:4517888, line = 2270
D/        (30274): Gralloc Register  w:1371, h:720, f:0x1, usage:0xb00, ui64Stamp:999044, sSize:3964928, line = 2270
D/        (30274): Gralloc Register  w:720, h:1371, f:0x1, usage:0x300, ui64Stamp:999073, sSize:3964928, line = 2270
D/        (30274): Gralloc Register  w:720, h:1556, f:0x1, usage:0xb00, ui64Stamp:999081, sSize:4517888, line = 2270
D/        (30274): Gralloc Register  w:1371, h:720, f:0x1, usage:0xb00, ui64Stamp:999089, sSize:3964928, line = 2270
E/InputMethodManager(30274): b/117267690: Failed to get fallback IMM with expected displayId=82 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.WebViewHostApiImpl$InputAwareWebViewPlatformView{e635c0e VFEDHVC.. ........ 0,0-720,1371}
D/        (30274): Gralloc Free  w:720, h:1371, f:0x1, usage:0x300, ui64Stamp:999073 line = 2376
D/        (30274): Gralloc Register  w:1472, h:575, f:0x1, usage:0x300, ui64Stamp:999178, sSize:3391488, line = 2270
D/        (30274): Gralloc Free  w:720, h:1371, f:0x1, usage:0x300, ui64Stamp:998992 line = 2376
E/IMGSRV  (30274): :0: IsTextureConsistent: IMGEGLImage is not consistent
D/        (30274): Gralloc Register  w:1472, h:575, f:0x1, usage:0x300, ui64Stamp:999222, sSize:3391488, line = 2270
D/        (30274): Gralloc Free  w:1371, h:720, f:0x1, usage:0xb00, ui64Stamp:999044 line = 2376
D/        (30274): Gralloc Free  w:1371, h:720, f:0x1, usage:0xb00, ui64Stamp:999089 line = 2376
D/        (30274): Gralloc Register  w:575, h:1472, f:0x1, usage:0xb00, ui64Stamp:999297, sSize:3391488, line = 2270
D/        (30274): Gralloc Register  w:575, h:1472, f:0x1, usage:0xb00, ui64Stamp:999356, sSize:3391488, line = 2270
D/        (30274): Gralloc Register  w:575, h:1472, f:0x1, usage:0xb00, ui64Stamp:999368, sSize:3391488, line = 2270
D/        (30274): Gralloc Register  w:720, h:1472, f:0x1, usage:0xb00, ui64Stamp:999388, sSize:4239360, line = 2270
D/        (30274): Gralloc Register  w:1472, h:575, f:0x1, usage:0x300, ui64Stamp:999502, sSize:3391488, line = 2270
D/        (30274): Gralloc Register  w:720, h:1472, f:0x1, usage:0xb00, ui64Stamp:999514, sSize:4239360, line = 2270
D/        (30274): Gralloc Free  w:575, h:1472, f:0x1, usage:0xb00, ui64Stamp:999297 line = 2376
D/        (30274): Gralloc Register  w:1472, h:575, f:0x1, usage:0xb00, ui64Stamp:999674, sSize:3391488, line = 2270
D/        (30274): Gralloc Free  w:575, h:1472, f:0x1, usage:0xb00, ui64Stamp:999356 line = 2376
D/        (30274): Gralloc Register  w:1472, h:575, f:0x1, usage:0xb00, ui64Stamp:999683, sSize:3391488, line = 2270
D/        (30274): Gralloc Free  w:575, h:1472, f:0x1, usage:0xb00, ui64Stamp:999368 line = 2376
D/        (30274): Gralloc Register  w:1472, h:575, f:0x1, usage:0xb00, ui64Stamp:999706, sSize:3391488, line = 2270
D/TransportRuntime.CctTransportBackend(30274): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
I/TransportRuntime.CctTransportBackend(30274): Status Code: 200
I/TransportRuntime.CctTransportBackend(30274): Content-Type: application/json; charset=UTF-8
I/TransportRuntime.CctTransportBackend(30274): Content-Encoding: gzip
D/        (30274): Gralloc Free  w:720, h:1472, f:0x1, usage:0xb00, ui64Stamp:999013 line = 2376
D/        (30274): Gralloc Register  w:1472, h:720, f:0x1, usage:0xb00, ui64Stamp:1004212, sSize:4239360, line = 2270
D/        (30274): Gralloc Free  w:720, h:1556, f:0x1, usage:0xb00, ui64Stamp:999022 line = 2376
D/        (30274): Gralloc Free  w:720, h:1556, f:0x1, usage:0xb00, ui64Stamp:999081 line = 2376
D/        (30274): Gralloc Free  w:1472, h:720, f:0x1, usage:0xb00, ui64Stamp:1004212 line = 2376
D/        (30274): Gralloc Free  w:720, h:1472, f:0x1, usage:0xb00, ui64Stamp:999388 line = 2376
D/        (30274): Gralloc Free  w:720, h:1472, f:0x1, usage:0xb00, ui64Stamp:999514 line = 2376
D/        (30274): Gralloc Register  w:720, h:1516, f:0x1, usage:0xb00, ui64Stamp:1004216, sSize:4378624, line = 2270
D/SurfaceCallbackHelper(30274): dispatchSurfaceRedrawNeededAsync, callbacks=[Landroid.view.SurfaceHolder$Callback;@e9baa30, callbacks.length=1
D/SurfaceCallbackHelper(30274): mFinishDrawingRunnable, mFinishDrawingCollected=1, mFinishDrawingExpected=1
D/        (30274): Gralloc Register  w:720, h:1600, f:0x1, usage:0xb00, ui64Stamp:1004226, sSize:4608000, line = 2270
D/        (30274): Gralloc Register  w:720, h:1600, f:0x1, usage:0xb00, ui64Stamp:1004235, sSize:4608000, line = 2270
E/InputMethodManager(30274): b/117267690: Failed to get fallback IMM with expected displayId=83 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.WebViewHostApiImpl$InputAwareWebViewPlatformView{e635c0e VFEDHVC.. ........ 0,0-1472,575}
D/        (30274): Gralloc Free  w:1472, h:575, f:0x1, usage:0x300, ui64Stamp:999178 line = 2376
D/        (30274): Gralloc Free  w:1472, h:575, f:0x1, usage:0x300, ui64Stamp:999222 line = 2376
W/Sensors (30274): sensorservice died [0x9c7bd540]
E/MethodChannel#flutter/platform_views(30274): Failed to handle method call
E/MethodChannel#flutter/platform_views(30274): DeadSystemException: The system died; earlier logs will point to the root cause
I/Choreographer(30274): Skipped 37 frames!  The application may be doing too much work on its main thread.
E/flutter (30274): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, android.os.DeadSystemException, null, java.lang.RuntimeException: android.os.DeadSystemException
E/flutter (30274): 	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:156)
E/flutter (30274): 	at android.view.Display.updateDisplayInfoLocked(Display.java:1126)
E/flutter (30274): 	at android.view.Display.getMetrics(Display.java:1038)
E/flutter (30274): 	at android.app.Presentation.isConfigurationStillValid(Presentation.java:307)
E/flutter (30274): 	at android.app.Presentation.onStart(Presentation.java:237)
E/flutter (30274): 	at android.app.Dialog.show(Dialog.java:323)
E/flutter (30274): 	at android.app.Presentation.show(Presentation.java:257)
E/flutter (30274): 	at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:161)
E/flutter (30274): 	at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:292)
E/flutter (30274): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:141)
E/flutter (30274): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:65)
E/flutter (30274): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (30274): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter (30274): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/flutter (30274): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter (30274): 	at android.os.Handler.handleCallback(Handler.java:883)
E/flutter (30274): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/flutter (30274): 	at android.os.Looper.loop(Looper.java:214)
E/flutter (30274): 	at android.app.ActivityThread.main(ActivityThread.java:7649)
E/flutter (30274): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (30274): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
E/flutter (30274): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (30274): Caused by: android.os.DeadSystemException
E/flutter (30274): 	... 22 more
E/flutter (30274): )
E/flutter (30274): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (30274): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter (30274): <asynchronous suspension>
E/flutter (30274): #2      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1027:5)
E/flutter (30274): <asynchronous suspension>
E/flutter (30274): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:191:7)
E/flutter (30274): <asynchronous suspension>
E/flutter (30274): 
```
</details>

<details>
<summary>flutter doctor - v</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/lkirov/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome


[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Arctic android studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • moto e 7i power (mobile) • ZE222P5PCB • android-arm    • Android 10 (API 29)
    • Chrome (web)             • chrome     • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @LudmilKirov, you appear to be on an older version of flutter. Can you upgrade to the latest version of stable to see whether or not you experience this issue? 

If you do, kindly provide the updated flutter doctor -v as well as a complete minimal reproducible code sample so that we can investigate this. 

Also, is the `Moto e 7i power` the only device you're experiencing this issue on?
