### ISSUE TITLE
[go_router] Pop is not functional when using `refreshListenable`

### ISSUE THREAD

**Issue by sarbagyastha** [flutter/flutter#106166]
## Steps to Reproduce

1. Clone the repo https://github.com/sarbagyastha/router
2. Checkout the `refresh` branch
3. Run the app and tap on "Go to Second page"
4. Tap on the back button in App Bar.

**Expected results:** I should be able to pop to the first page.

**Actual results:** I see the following error.
```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
have popped the last page off of the stack; there are no pages left to show
'package:go_router/src/go_router_delegate.dart':
Failed assertion: line 71 pos 12: '_matches.isNotEmpty'

When the exception was thrown, this was the stack: 
#2      GoRouterDelegate.pop (package:go_router/src/go_router_delegate.dart:71:12)
#3      GoRouter.pop (package:go_router/src/go_router.dart:167:32)
#4      GoRouterHelper.pop (package:go_router/go_router.dart:75:35)
#5      GoRouterHelper.pop.<anonymous closure> (package:go_router/go_router.dart:75:8)
#6      BackButton.build.<anonymous closure> (package:flutter/src/material/back_button.dart:104:21)

```

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-NP)
    • Flutter version 3.0.2 at /Users/sarbagya/Development/flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = ssh://git@github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (9 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/sarbagya/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/sarbagya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 52A89D3C-1D4B-42EE-817A-C77345806588 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @sarbagyastha thanks for filing the issue. 
This issue is reproducible on the latest `stable` and `master` channels.

It seems the issue is caused by using with `Stream.periodic`.
I also tried with [router_stream_refresh](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/router_stream_refresh.dart
) that using normal stream and see it works well without exception.

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/174287250-54413985-4ac6-4395-91ea-fdc25981f53a.mp4

</details>


<details>
<summary>Logs</summary>

```bash
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
Assertion failed: file:///Users/huynq/.pub-cache/hosted/pub.dartlang.org/go_router-4.0.0/lib/src/go_router_delegate.dart:71:12
_matches.isNotEmpty
"have popped the last page off of the stack; there are no pages left to show"

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/go_router/src/go_router_delegate.dart 71:21                          pop
packages/go_router/src/go_router.dart 167:32                                  pop
packages/go_router/go_router.dart 75:35                                       GoRouterHelper.pop
packages/go_router/go_router.dart 75:8                                        <fn>
packages/flutter/src/material/back_button.dart 104:11                         <fn>
packages/flutter/src/material/ink_well.dart 1005:21                           [_handleTap]
packages/flutter/src/gestures/recognizer.dart 198:24                          invokeCallback
packages/flutter/src/gestures/tap.dart 613:48                                 handleTapUp
packages/flutter/src/gestures/tap.dart 298:5                                  [_checkUp]
packages/flutter/src/gestures/tap.dart 269:7                                  acceptGesture
packages/flutter/src/gestures/arena.dart 157:12                               sweep
packages/flutter/src/gestures/binding.dart 449:20                             handleEvent
packages/flutter/src/gestures/binding.dart 425:14                             dispatchEvent
packages/flutter/src/rendering/binding.dart 329:11                            dispatchEvent
packages/flutter/src/gestures/binding.dart 380:7                              [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 344:5                              handlePointerEvent
packages/flutter/src/gestures/binding.dart 302:7                              [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 285:32                             [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1105:13                           invoke1
lib/_engine/engine/platform_dispatcher.dart 185:5                             invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                [_onPointerData]
lib/_engine/engine/pointer_binding.dart 543:18                                <fn>
lib/_engine/engine/pointer_binding.dart 496:21                                <fn>
lib/_engine/engine/pointer_binding.dart 210:16                                loggedHandler
Handler: "onTap"
Recognizer: TapGestureRecognizer#3116f
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(21.0, 20.3)
  button: 1
  sent tap down
====================================================================================================
```
</details>

<details>
<summary>Sample code (only main classes from repo)</summary>

- router.dart

```dart
import 'package:go_router/go_router.dart';
import 'package:router/first_page.dart';
import 'package:router/second_page.dart';

int count = 1;

final stream = Stream.periodic(
  const Duration(seconds: 1),
  (computationCount) => count = computationCount,
);

final router = GoRouter(
  initialLocation: '/first',
  refreshListenable: GoRouterRefreshStream(stream),
  routes: [
    GoRoute(
      path: '/first',
      builder: (_, __) => const FirstPage(),
    ),
    GoRoute(
      path: '/second',
      name: 'second',
      builder: (_, state) => SecondPage(
        queryParams: state.queryParams,
        extra: state.extra,
      ),
    ),
  ],
  redirect: (state) {
    print(state.location);
    print('Called $count times.');

    return null;
  },
);

```

- first_page.dart

```dart
import 'package:flutter/material.dart';
import 'package:router/router.dart';

class FirstPage extends StatelessWidget {
  const FirstPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('First Page')),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            router.pushNamed(
              'second',
              queryParams: {'a': 'b'},
              extra: 'test-extra',
            );
          },
          child: const Text('Go to Second Page'),
        ),
      ),
    );
  }
}

```

- second_page.dart

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class SecondPage extends StatelessWidget {
  const SecondPage({
    super.key,
    required this.queryParams,
    required this.extra,
  });

  final Map<String, String> queryParams;
  final Object? extra;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: BackButton(
          onPressed: context.pop,
        ),
        title: const Text('Second Page'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text('Query Params: $queryParams'),
          const SizedBox(height: 8),
          Text('Extra: $extra'),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.2 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1284, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1284 at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fae31eecce (30 minutes ago), 2022-06-16 19:58:05 -0700
    • Engine revision f8c0dc87bc
    • Dart version 2.18.0 (build 2.18.0-189.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by FloLecoeuche** [comment]
I have the exact same exception, any updates on this issue ?

**Comment by claudius-kienle** [comment]
I also get this exception after upgrading to gorouter from 4.1.0 to 5.2.4.

**Comment by steevedevops** [comment]
Any idea about this problem, guys ?

**Comment by rirjkl19** [comment]
Any updates?
