### ISSUE TITLE
Android Crash: androidx.fragment.app.L: Unable to instantiate fragment

### ISSUE THREAD

**Issue by anderscheow** [flutter/flutter#106116]
My production application crash randomly on Android 12, 11 and 10. Mostly on Samsung and Xiaomi devices.

I've attached the crash log from Crashlytics

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.excite.plus/com.excite.app.MainActivity}: androidx.fragment.app.L: Unable to instantiate fragment l.l.i0: could not find Fragment constructor
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3592)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3752)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2178)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8051)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

Caused by androidx.fragment.app.L: Unable to instantiate fragment l.l.i0: could not find Fragment constructor
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:66)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:1)
       at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:1)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:1)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:1)
       at androidx.fragment.app.FragmentManager.G0(FragmentManager.java:123)
       at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:5)
       at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:5)
       at androidx.fragment.app.FragmentActivity.lambda$init$1(FragmentActivity.java:1)
       at androidx.fragment.app.-$$Lambda$FragmentActivity$QtiQ2ZI3e38UkO1_xuJ8vE_JZj4.onContextAvailable(-.java:1)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:20)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:7)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java)
       at io.flutter.embedding.android.FlutterFragmentActivity.onCreate(FlutterFragmentActivity.java:4)
       at com.excite.app.MainActivity.onCreate(MainActivity.java:23)
       at android.app.Activity.performCreate(Activity.java:8142)
       at android.app.Activity.performCreate(Activity.java:8114)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3565)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3752)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2178)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8051)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

Caused by java.lang.NoSuchMethodException: l.l.i0.<init> []
       at java.lang.Class.getConstructor0(Class.java:2332)
       at java.lang.Class.getConstructor(Class.java:1728)
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:15)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:1)
       at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:1)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:1)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:1)
       at androidx.fragment.app.FragmentManager.G0(FragmentManager.java:123)
       at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:5)
       at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:5)
       at androidx.fragment.app.FragmentActivity.lambda$init$1(FragmentActivity.java:1)
       at androidx.fragment.app.-$$Lambda$FragmentActivity$QtiQ2ZI3e38UkO1_xuJ8vE_JZj4.onContextAvailable(-.java:1)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:20)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:7)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java)
       at io.flutter.embedding.android.FlutterFragmentActivity.onCreate(FlutterFragmentActivity.java:4)
       at com.excite.app.MainActivity.onCreate(MainActivity.java:23)
       at android.app.Activity.performCreate(Activity.java:8142)
       at android.app.Activity.performCreate(Activity.java:8114)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3565)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3752)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2178)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8051)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

<details>

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-MY)
    • Flutter version 3.0.1 at /Users/anderscheow/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/anderscheow/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by huycozy** [comment]
@anderscheow 

Please see these StackOverflow answers that might help you: https://stackoverflow.com/questions/61046199/java-lang-runtimeexception-unable-to-instantiate-activity-in-flutter

If you encounter behavior that you believe could be a bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem.

Thank you!

**Comment by haoqiangyu** [comment]
Same occasional problem
