### ISSUE TITLE
Crash on restoring app from background 

### ISSUE THREAD

**Issue by SiarheiSm** [flutter/flutter#106192]
## Steps to Reproduce
1. create native app
2. create flutter module 
3. attach flutter fragment from native 
4. send app to background
5. enable "Don't keep activities" and "No Background Processes"
6. open app again:
```
java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: '/route'

io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine FlutterActivityAndFragmentDelegate.java:240
2io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach FlutterActivityAndFragmentDelegate.java:175
3io.flutter.embedding.android.FlutterFragment.onAttach FlutterFragment.java:777
4androidx.fragment.app.Fragment.performAttach Fragment.java:2954
5androidx.fragment.app.FragmentStateManager.attach FragmentStateManager.java:463
6androidx.fragment.app.FragmentStateManager.moveToExpectedState FragmentStateManager.java:254
7androidx.fragment.app.FragmentStore.moveToExpectedState FragmentStore.java:113
8androidx.fragment.app.FragmentManager.moveToState FragmentManager.java:1374
9androidx.fragment.app.FragmentManager.dispatchStateChange FragmentManager.java:2841
10androidx.fragment.app.FragmentManager.dispatchCreate FragmentManager.java:2773
11androidx.fragment.app.Fragment.restoreChildFragmentState Fragment.java:1935
12androidx.fragment.app.Fragment.onCreate Fragment.java:1911
13androidx.fragment.app.Fragment.performCreate Fragment.java:2981
14androidx.fragment.app.FragmentStateManager.create FragmentStateManager.java:474
15androidx.fragment.app.FragmentStateManager.moveToExpectedState FragmentStateManager.java:257
16androidx.fragment.app.FragmentStore.moveToExpectedState FragmentStore.java:113
17androidx.fragment.app.FragmentManager.moveToState FragmentManager.java:1374
18androidx.fragment.app.FragmentManager.dispatchStateChange FragmentManager.java:2841
19androidx.fragment.app.FragmentManager.dispatchCreate FragmentManager.java:2773
20androidx.fragment.app.Fragment.restoreChildFragmentState Fragment.java:1935
21androidx.fragment.app.Fragment.onCreate Fragment.java:1911
22androidx.navigation.fragment.NavHostFragment.onCreate NavHostFragment.java:169
23androidx.fragment.app.Fragment.performCreate Fragment.java:2981
24androidx.fragment.app.FragmentStateManager.create FragmentStateManager.java:474
25androidx.fragment.app.FragmentStateManager.moveToExpectedState FragmentStateManager.java:257
26androidx.fragment.app.FragmentStore.moveToExpectedState FragmentStore.java:113
27androidx.fragment.app.FragmentManager.moveToState FragmentManager.java:1374
28androidx.fragment.app.FragmentManager.dispatchStateChange FragmentManager.java:2841
29androidx.fragment.app.FragmentManager.dispatchCreate FragmentManager.java:2773
30androidx.fragment.app.Fragment.restoreChildFragmentState Fragment.java:1935
31androidx.fragment.app.Fragment.onCreate Fragment.java:1911
```

I've found a fix: https://stackoverflow.com/questions/64010393/requested-flutter-engine-does-not-exist-in-add-to-app
but it looks like a workaround to create engine before super.OnCreate(). For example in app I have few flutter fragments, and engine been destroyed with the fragment. At the other hand I should keep in mind what fragments with flutter engine is in stack and then recreate all required engines, in other case I'll get a crash. 

```
 Flutter (Channel stable, 3.0.1, on macOS 12.2.1 21D62 darwin-arm, locale en-DE)
    • Flutter version 3.0.1 at /Users/siarheism/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2
Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

```

**Comment by huycozy** [comment]
Hi @SiarheiSm, thanks for filing the issue. 

> I've found a fix: https://stackoverflow.com/questions/64010393/requested-flutter-engine-does-not-exist-in-add-to-app
but it looks like a workaround to create engine before super.OnCreate(). For example in app I have few flutter fragments, and engine been destroyed with the fragment. At the other hand I should keep in mind what fragments with flutter engine is in stack and then recreate all required engines, in other case I'll get a crash.

Did you try implementing this?  Can you provide a sample code for this?
I also see a solution [here](https://stackoverflow.com/a/69159840/5921933) in that SO thread, did you try it too?

**Comment by SiarheiSm** [comment]
Hi, ok, I hope I'll have a time to prepare code example in next 1-2 weeks.

**Comment by SiarheiSm** [comment]
was able to reproduce when put flutter fragment to pager 
please check
[FL_test.zip](https://github.com/flutter/flutter/files/9046375/FL_test.zip)

**Comment by huycozy** [comment]
@SiarheiSm, thanks for your sample code. But my crash log is quite different than yours

<details>
<summary>Logs</summary>

```bash
    --------- beginning of crash
2022-07-06 10:04:29.416 14052-14052/cat.flutter.fl E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cat.flutter.fl, PID: 14052
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cat.flutter.fl/cat.flutter.fl.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.detachFromFlutterEngine()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.detachFromFlutterEngine()' on a null object reference
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDestroyView(FlutterActivityAndFragmentDelegate.java:613)
        at io.flutter.embedding.android.FlutterFragment.detachFromFlutterEngine(FlutterFragment.java:869)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.detachFromFlutterEngine(FlutterActivityAndFragmentDelegate.java:649)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:319)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:189)
        at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:777)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1891)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1867)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
        at cat.flutter.fl.MainActivity.onCreate(MainActivity.kt:12)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7870) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
2022-07-06 10:04:29.447 14052-14052/cat.flutter.fl I/Process: Sending signal. PID: 14052 SIG: 9

```
</details>

Could you confirm that you get the same crash log from your side?

**Comment by SiarheiSm** [comment]
Oh, right =) I was a bit tired yesterday and haven't noticed. 
I'm also see such crash in production crash reports _(we also use the pager there)_ should I create separate issue for this case?
regarding an issue I've mentioned in the first message: I have to make more research, it is stable reproducible in prod app if I remove "workaround". I'll continue when have a time and prepare new test sample.
thank you

**Comment by SiarheiSm** [comment]
@huycozy I had no time to prepare sample, but noticed that issue is reproducible in this code sample https://github.com/flutter/samples/tree/main/add_to_app/multiple_flutters/multiple_flutters_android 

<details>
   java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.flutter.multipleflutters/dev.flutter.multipleflutters.DoubleFlutterActivity}: java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: '0'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: '0'
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:240)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:175)
        at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:777)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2574)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:828)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
        at dev.flutter.multipleflutters.DoubleFlutterActivity.onCreate(DoubleFlutterActivity.kt:34)
</details>

please check the video: https://drive.google.com/file/d/1tqmTGUnh9R0yFsXqNO5QdroqMjX1MvDB/view?usp=sharing

it looks like when restoring state in `FlutterActivityAndFragmentDelegate->setupFlutterEngine()` it fetches cache id from the flutter fragment bundle: `host.getCachedEngineId();`, and it exists. but Engine cache been destroyed, so it crashes here:
```
if (cachedEngineId != null) {
      flutterEngine = FlutterEngineCache.getInstance().get(cachedEngineId);
```  

also I've tried to set `FlutterFragment.withCachedEngine.destroyEngineWithFragment(true)`, but seems it has no effect in case of restoring state

**Comment by huycozy** [comment]
Hi @SiarheiSm 
I tried running the [sample code](https://github.com/flutter/samples/tree/main/add_to_app/multiple_flutters/multiple_flutters_android)  with reproduction steps in https://github.com/flutter/flutter/issues/106192#issue-1275066506, and I can reproduce this issue but after several times. The app has crashed after resuming from the background.
The crash clearly visible if I try repeating click on `Open Flutter Docs` (This behavior is similar to what is happening in your demo video)

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/179897624-9df11996-7c80-4f7d-b5d9-99f82ee16505.mp4


</details>

<details>
<summary>Logs</summary>

```bash
2022-07-20 11:27:39.337 2752-2752/dev.flutter.multipleflutters E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.flutter.multipleflutters, PID: 2752
    java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.flutter.multipleflutters/dev.flutter.multipleflutters.DoubleFlutterActivity}: java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: '0'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: '0'
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:240)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:175)
        at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:777)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2574)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:828)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
        at dev.flutter.multipleflutters.DoubleFlutterActivity.onCreate(DoubleFlutterActivity.kt:34)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1751, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1751 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e56047a62c (14 minutes ago), 2022-07-19 23:17:05 -0400
    • Engine revision d9ba4345fc
    • Dart version 2.19.0 (build 2.19.0-12.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Labeling the issue for further investigation from the team. Thanks!

**Comment by SiarheiSm** [comment]
as a workaround for now I've wrapped to try/catch and remove arguments from state

<details>
class FlutterFragmentFix : FlutterFragment() {

    companion object {
        fun builder(engineId: String): CachedEngineFragmentBuilder {
            return CachedEngineFragmentBuilder(FlutterFragmentFix::class.java, engineId)
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        try {
            super.onCreate(savedInstanceState)
        } catch (e: Throwable) {
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return try {
            super.onCreateView(inflater, container, savedInstanceState)
        } catch (e: Throwable) {
            null
        }
    }

    override fun onDetach() {
        try {
            super.onDetach()
        } catch (e: Throwable) {
        }
    }

    override fun shouldDestroyEngineWithHost(): Boolean {
        return try {
            super.shouldDestroyEngineWithHost()
        } catch (e: Exception) {
            false
        }
    }

    override fun onAttach(context: Context) {
        try {
            super.onAttach(context)
        } catch (e: Throwable) {
        }
    }

    override fun onSaveInstanceState(outState: Bundle) {
        arguments?.clear()
        super.onSaveInstanceState(outState)
    }
}
</details>

seems fixes both https://github.com/flutter/flutter/issues/106192#issuecomment-1188701059 and https://github.com/flutter/flutter/issues/106192#issuecomment-1175737384

**Comment by korilin** [comment]
Our project has another crash in this scenario.

<details><summary>Log</summary>
<p>

```
java.lang.IllegalArgumentException: No view found for id 0x7f0a0377 (package_name:id/frame) for fragment FlutterFragment{6fe82ec} (1bbedbaf-eda8-44b1-a146-25929d0aa46d id=0x7f0a0377 tag=3e4adccee02045d7ae44d1824bd0ef7e)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1529)
at android.app.Activity.performStart(Activity.java:8422)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3893)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
```
</p>
</details>

**Comment by arc-yong** [comment]
any update on this issue? we still have the same issue on flutter 3.27.4.

**Comment by chontzopoulouSte** [comment]
Any update on this issue?
