### ISSUE TITLE
Generating localizations when having an empty key in the `.arb` should print a better error message.

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#106182]
This has been reported in #104783, #100217, #99981, #99762, #97550, and possibly others.

This happens when the arb file has empty key, e.g.

```
{
  "": "will crash"
}
```

Steps:
- Create a new Flutter project with [internationalization](https://docs.flutter.dev/development/accessibility-and-localization/internationalization) steps
- Have `app_en.arb` to be:
```
{
  "": "will crash"
}
```
- Run the app

<details>
<summary>error details</summary>

RangeError: RangeError (index): Invalid value: Valid value range is empty: 0

```
#0      _StringBase.[] (dart:core-patch/string_patch.dart:260:41)
#1      LocalizationsGenerator._isValidGetterAndMethodName (package:flutter_tools/src/localizations/gen_l10n.dart:1048:13)
#2      LocalizationsGenerator.loadResources (package:flutter_tools/src/localizations/gen_l10n.dart:1073:12)
#3      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:68:9)
#4      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#7      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1336:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1195:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1288, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 3.1.0-0.0.pre.1288 at C:\use\flutter
    • Upstream repository https://github.com/asashour/flutter.git
    • Framework revision 58007fc64c (3 hours ago), 2022-06-17 08:16:06 +0200
    • Engine revision ee71e31c36
    • Dart version 2.18.0 (build 2.18.0-190.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\ahmed_ashour\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = C:\Users\ahmed_ashour\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.20348.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 221.5080.93
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 221.5480

[✓] VS Code (version 1.67.1)
    • VS Code at C:\Users\ahmed_ashour\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 102.0.1245.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by exaby73** [comment]
If you have an empty key, it seems like an error on the user's side. Is this a bug report or a feature request for a better error message?

**Comment by asashour** [comment]
Yes, it is an error from the user, but the tool should not crash. It should say something like:

>Empty key found in abc.file, please correct it.

**Comment by exaby73** [comment]
Okay. This seems like a feature request to include a better error message. Thanks for the feedback :)

**Comment by asashour** [comment]
Fixed in https://github.com/flutter/flutter/commit/94da724868a795d201288dc6f5efdd60f92eef00
