### ISSUE TITLE
camera_android 0.9.8+1 registerWith() made a big mistake

### ISSUE THREAD

**Issue by SakurasDuck** [flutter/flutter#106236]
## camera_android: 0.9.8+1 

<details>
<summary>flutter doctor -v</summary>

[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19044.1766], locale zh-CN)
    • Flutter version 3.0.2 at D:\Tools\Android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (10 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2
    • Pub download mirror http://pub.lan.wiqun.com
    • Flutter download mirror https://storage.flutter-io.cn

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Tools\Android\SDK
    • Platform android-32, build-tools 30.0.3
    • ANDROID_HOME = D:\Tools\Android\SDK
    • Java binary at: C:\Users\Pawn\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7322048\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Users\Pawn\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7322048
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Users\Pawn\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\203.6682.168
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Users\Pawn\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\211.7628.21
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\Pawn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • LND AL40 (mobile) • 3SLBB18414213204 • android-arm64  • Android 8.0.0 (API 26)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 102.0.1245.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

<details>
  <summary>Logs</summary>

 AndroidCamera.registerWith (package:camera_android/src/android_camera.dart:32:66)
I/flutter ( 1198): #1      _PluginRegistrant.register (file:///xxxx/.dart_tool/flutter_build/dart_plugin_registrant.dart:36:23)
I/flutter ( 1198): `camera_android` threw an error: Binding has not yet been initialized.
I/flutter ( 1198): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
I/flutter ( 1198): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
I/flutter ( 1198): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
I/flutter ( 1198): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.. The app may not function as expected until you remove this plugin from pubspec.yaml
E/flutter ( 1198): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: Binding has not yet been initialized.
E/flutter ( 1198): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
E/flutter ( 1198): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
E/flutter ( 1198): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
E/flutter ( 1198): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter., stack trace: #0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:281:9)
E/flutter ( 1198): #1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:363:6)
E/flutter ( 1198): #2      ServicesBinding.instance (package:flutter/src/services/binding.dart:48:54)
E/flutter ( 1198): #3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:387:51)
E/flutter ( 1198): #4      new AndroidCamera (package:camera_android/src/android_camera.dart:26:13)
E/flutter ( 1198): #5      AndroidCamera.registerWith (package:camera_android/src/android_camera.dart:33:31)
E/flutter ( 1198): #6      _PluginRegistrant.register (file:///xxxx/.dart_tool/flutter_build/dart_plugin_registrant.dart:36:23)
E/flutter ( 1198): 
</details>

### I can't run  `WidgetsFlutterBinding.ensureInitialized()` before  camera_android's`registerWith()`, plz fix it

**Comment by SakurasDuck** [comment]
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  ...
```
It doesn't working either

**Comment by masewo** [comment]
Regression. After upgrading camera_android and camera_avfoundation from 0.9.7+1 to 0.9.8+1 my app does not start anymore.

**Comment by DenisMrGnusa** [comment]
same error, i was trying to use version ^0.9.7+1 and ^0.9.8+1, but not luck.

**this my flutter spec:**
Flutter is already up to date on channel stable
Flutter 3.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cd41fdd495 (10 days ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2

**Comment by masewo** [comment]
Use this:

´´´
dependency_overrides:
  camera_android: 0.9.7+1
  camera_avfoundation: 0.9.7+1
´´´

**Comment by ufogxl** [comment]
> 

your solution helps my day! could you please tell the reason?

**Comment by SakurasDuck** [comment]
look this:

AndroidCamera.registerWith (package:camera_android/src/android_camera.dart:32:66)
I/flutter ( 1198): #1 _PluginRegistrant.register (file:///xxxx/.dart_tool/flutter_build/dart_plugin_registrant.dart:36:23)

I print stack in my app,and i find this![IMG20220618235534.jpg](https://user-images.githubusercontent.com/40283698/174446580-58c76eab-1438-4c07-ac06-609d62a9137d.jpg)  
Didn't work as expected？？？

**Comment by stuartmorgan** [comment]
This is an unintended side effect of moving to a per-package platform channel. The default method channel didn't have this problem because static class fields are lazily evaluated in Dart, so the default method channel class constructor was only being run once the camera is actually used, whereas the new version's constructors are explicitly triggered in `registerWith()`.

We'll need to make the reverse channel creation lazy in those implementations, rather than setting it up in the constructor.

**Comment by stuartmorgan** [comment]
@SakurasDuck In the future, please don't ping random people in issue reports.

**Comment by SakurasDuck** [comment]
@stuartmorgan sorry,never again

**Comment by bhanuka96** [comment]
Same Issue, Any Updates

```
I/flutter ( 6677): `camera_android` threw an error: Binding has not yet been initialized.
I/flutter ( 6677): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
I/flutter ( 6677): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
I/flutter ( 6677): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
I/flutter ( 6677): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.. The app may not function as expected until you remove this plugin from pubspec.yaml
E/flutter ( 6677): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: Binding has not yet been initialized.
E/flutter ( 6677): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
E/flutter ( 6677): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
E/flutter ( 6677): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
E/flutter ( 6677): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter., stack trace: #0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:281:9)
E/flutter ( 6677): #1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:363:6)
E/flutter ( 6677): #2      ServicesBinding.instance (package:flutter/src/services/binding.dart:48:54)
E/flutter ( 6677): #3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:387:51)
E/flutter ( 6677): #4      new AndroidCamera (package:camera_android/src/android_camera.dart:26:13)
E/flutter ( 6677): #5      AndroidCamera.registerWith (package:camera_android/src/android_camera.dart:32:31)
E/flutter ( 6677): #6      _PluginRegistrant.register (file:///Users/bhanukaisuru/Documents/REBORN/YELLO/user-app/.dart_tool/flutter_build/dart_plugin_registrant.dart:47:23)
E/flutter ( 6677): 
```

**Comment by bhanuka96** [comment]
Temp Solution:

Downgrade the plugin to 0.9.7+1

`camera: 0.9.7+1`

**Comment by islom9797** [comment]
> Use this in your `pubspec.yaml`:
> 
> ```
> dependency_overrides:
>   camera_android: 0.9.7+1
>   camera_avfoundation: 0.9.7+1
> ```

also helped me .I add camera  and this packege at the same time and worked me thanks

**Comment by ayansg** [comment]
> This is an unintended side effect of moving to a per-package platform channel. The default method channel didn't have this problem because static class fields are lazily evaluated in Dart, so the default method channel class constructor was only being run once the camera is actually used, whereas the new version's constructors are explicitly triggered in `registerWith()`.
> 
> We'll need to make the reverse channel creation lazy in those implementations, rather than setting it up in the constructor.

Just a note on regression, `path_provider` package also stops working after this error is thrown. It fails to get the platform specific channel and throws a `MissingPluginException` whenever a platform directory is requested. You should also be adding this to your regression testing.

**Comment by RaistlinTAO** [comment]
> Temp Solution:
> 
> Downgrade the plugin to 0.9.7+1
> 
> `camera: 0.9.7+1`

Downgrading the plugin seems still not working, using override method.

And **shared_preferences** is also broken.

**Comment by AlexV525** [comment]
Should we increase the priority since multiple plugins are affected by the regression?

**Comment by yy1300326388** [comment]
The latest version has been fixed:

```
flutter clean
flutter packages get
flutter run
```
or

```
dependency_overrides:
  camera_android: 0.9.8+2
  camera_avfoundation: 0.9.8+2
```

**Comment by stuartmorgan** [comment]
You should not use `dependency_overrides` to get the latest version of packages; what you have shown there would prevent ever getting any new updates to the camera implementations.

You should instead remove any pinning from `pubspec.yaml`, then `flutter pub upgrade`.

**Comment by yy1300326388** [comment]
> 您不应该使用`dependency_overrides`来获取最新版本的软件包；您在那里展示的内容将阻止对相机实现进行任何新的更新。
> 
> 您应该改为从`pubspec.yaml`, 然后删除任何固定`flutter pub upgrade`。

The reason is that I really want to use a definite version, so as not to bring unnecessary trouble, I have crashes on both Android and iOS, my camera is the fixed version 0.9.8, and it turns out that camera_android and camera_avfoundation have no definite version.

So if you want to follow the upgrade then use `dependency_overrides `

**Comment by AlexV525** [comment]
> So if you want to follow the upgrade then use `dependency_overrides `

@yy1300326388 Please don't use `dependency_overrides` if you want to follow up further upgrades as @stuartmorgan mentioned. It only helps with two cases typically:
- Debugging with a local version, then overrides with a local one.
- Some breaking changes happened without proper semantics version updates and you need to stick with old APIs.

Other than that, use `flutter pub upgrade`.

**Comment by yy1300326388** [comment]
Yes, I am currently the second case, and I also do not recommend using `dependency_overrides`
I will regularly check the upgrade and verify the relevant stability before upgrading. Generally, I will use a definite version

**Comment by stuartmorgan** [comment]
The combination of `pubspec.yaml` (for constraints) and `pubspec.lock` (to keep specific versions until you intentionally upgrade them) already allow you to use specific versions. And it does do without breaking normal workflows like `upgrade`.

If you personally want to follow anti-patterns like force-pinning exact versions of your transitive dependencies you certainly can, but please don't tell people to do it in our issue tracker as a way of updating packages--especially without any context that would alert newer community members to the future problems it would cause (like never getting bugfixes to those packages again).

**Comment by yy1300326388** [comment]
Ok, I have edited, thanks for the patient guidance ❤️
