### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Illegal character in path: assetsE:\gym_app\assets\Images

### ISSUE THREAD

**Issue by mohammedNaserHassan** [flutter/flutter#106243]
## Command
```
flutter --quiet assemble --no-version-check --depfile E:\gym_app\build\app\intermediates\flutter\debug/flutter_build.d --output E:\gym_app\build\app\intermediates\flutter\debug -dTargetFile=E:\gym_app\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Illegal character in path: assetsE:\gym_app\assets\Images
```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1860:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2890:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2862:38)
#3      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:744:29)
#4      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:685:9)
#5      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:50:26)
<asynchronous suspension>
#7      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:64:34)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
<asynchronous suspension>
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 2.10.3 at C:\development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\shoak\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32516.85
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code (version 1.68.1)
    • VS Code at C:\Users\shoak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • M2004J19C (mobile) • fff29b840407 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)  • windows      • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)       • chrome       • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)         • edge         • web-javascript • Microsoft Edge 102.0.1245.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7e9793dee1b85a243edd0e06cb1658e98b077561
### Plugins
fluttertoast-8.0.9
path_provider-2.0.11
path_provider_android-2.0.14
path_provider_ios-2.0.9
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7

**Comment by darshankawar** [comment]
> Unsupported operation: Illegal character in path: assetsE:\gym_app\assets\Images

This indicates there could be a formatting issue in your pubspec file. So you need to double check and confirm the alignment / formatting is correct in that file and there are no extra spaces or any illegal char. The tool seems to correctly throwing the error as it is telling that there's an illegal char in the path.

Closing from here as this doesn't seem to be a tool issue. If you disagree or think this is a genuine bug, write in comments and I'll reopen it.

**Comment by mohammedNaserHassan** [comment]
Thanks , the problem has been solved

‫في الاثنين، 20 يونيو 2022 في 11:06 ص تمت كتابة ما يلي بواسطة
‪darshankawar‬‏ ***@***.***‬‏>:‬
