### ISSUE TITLE
MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)

### ISSUE THREAD

**Issue by lukeellison** [flutter/flutter#106271]
## Steps to Reproduce

1. `flutter create camera_test`
2. `cd camera_test`
3. `flutter pub add camera`
4. `flutter pub get`
5. set `minSdkVersion 21` in `android/app/build.gradle`
6. replace code in `lib main.dart` with code from [docs example](https://github.com/flutter/plugins/tree/main/packages/camera/camera#example)
7. `flutter run`

You then get the error:
```
I/flutter ( 7655): `camera_android` threw an error: Binding has not yet been initialized.
I/flutter ( 7655): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
I/flutter ( 7655): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
```
although it already calls this function.
If you modify the code with `await` in front of the `WidgetsFlutterBinding.ensureInitialized();` (even though the editor says that it won't make a difference as it's not a future) and restart you get the following error instead:
```
E/flutter ( 7655): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)
```

<details>
<summary>Code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

late List<CameraDescription> _cameras;

Future<void> main() async {
  await WidgetsFlutterBinding.ensureInitialized();

  _cameras = await availableCameras();
  runApp(const CameraApp());
}

/// CameraApp is the Main Application.
class CameraApp extends StatefulWidget {
  /// Default Constructor
  const CameraApp({Key? key}) : super(key: key);

  @override
  State<CameraApp> createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  late CameraController controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(_cameras[0], ResolutionPreset.max);
    controller.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    }).catchError((Object e) {
      if (e is CameraException) {
        switch (e.code) {
          case 'CameraAccessDenied':
            print('User denied camera access.');
            break;
          default:
            print('Handle other errors.');
            break;
        }
      }
    });
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!controller.value.isInitialized) {
      return Container();
    }
    return MaterialApp(
      home: CameraPreview(controller),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 3.0.2 at /Users/LEllison/dev_tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (11 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/LEllison/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • AC2003 (mobile) • 62ea1068 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 102.0.5005.115
    ! Device emulator-5554 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by navaronbracke** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/106236 where the issue with the Method Channel setup has already been discussed.

**Comment by lukeellison** [comment]
Apologies, Googling around I didn't find that issue!
Thank you for the quick response! The temporary solution in that issue worked for me too:
```
dependency_overrides:
  camera_android: 0.9.7+1
  camera_avfoundation: 0.9.7+1
```

**Comment by nizamrex** [comment]
> Apologies, Googling around I didn't find that issue! Thank you for the quick response! The temporary solution in that issue worked for me too:
> 
> ```
> dependency_overrides:
>   camera_android: 0.9.7+1
> ```

E/flutter (31276): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)
E/flutter (31276): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (31276): <asynchronous suspension>
E/flutter (31276): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:353:35)
E/flutter (31276): <asynchronous suspension>
E/flutter (31276): #2      MethodChannelCamera.availableCameras (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:66:52)
E/flutter (31276): <asynchronous suspension>
E/flutter (31276): #3      main (package:camera_test/main.dart:7:16)
E/flutter (31276): <asynchronous suspension>
E/flutter (31276):

**Comment by EdwinXiang** [comment]
I have the same issue, how to solve it?

**Comment by hrxiang** [comment]
+1
