### ISSUE TITLE
[video_player] : Video Streaming(HLS) is stopping time to time in Android(playback error)

### ISSUE THREAD

**Issue by onatcipli** [flutter/flutter#106328]
Hi guys, I have a problem with `video_player` package. 

I have a main project that works on `flutter version 2.5.2` and I installed the `video_player: ^2.2.17` in this project, and to be sure that it is not related to versions [**I created a new flutter project with the latest versions of flutter and also the video player package**](https://github.com/onatcipli/test_video_stream) **so the issue is also in the latest version**

We are implementing a live stream feature and we are using [Wowza](https://www.wowza.com/) for the live stream provider and we are using the **HLS protocol** which the package already supports.

In iOS, everything works fine.
In Android, we have some stopping issues. 

Let's say I started the live stream from Wowza and run our applications on both platforms. 

In iOS, the video plays perfectly without pausing or stopping,
but in Android video is playing for 2 to 3(the time is changing sometimes it pauses in 1 min sometimes in 5 min) min after that it stops. 

what did I do so far; 
* I tried to `seekTo` 1 second forward(I see that recommendation on GitHub there are some others who face this issue too), it works in some cases but sometimes this walkaround is not working too.
* I tried to catch the error log, but sometimes it is not providing the error message too, without any logs its stopping

**Expected results:** 
The video player should play as same as on the iOS platform

**Actual results:** 
The video player stopped in like 3-5 mins intervals, sometimes I was able to play it again with seekTo but sometimes I was not.

### Example project to replicate
You can see the example project to replicate and since I'm not streaming currently, you need to replace it with a new URL that is in the HLS protocol. if you want We can plan and I can stream for you or you can create a trial account from Wowza and stream with OBS which is very straightforward.
https://github.com/onatcipli/test_video_stream

### Error Logs
As I mention sometimes the video stops without any error logs but sometimes I get the following error logs

```
E/ExoPlayerImplInternal(28311): Playback error
E/ExoPlayerImplInternal(28311):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:615)
E/ExoPlayerImplInternal(28311):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(28311):       at android.os.Looper.loop(Looper.java:224)
E/ExoPlayerImplInternal(28311):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(28311):   Caused by: com.google.android.exoplayer2.source.BehindLiveWindowException
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:440)
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:762)
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:386)
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.continueLoading(MaskingMediaPeriod.java:226)
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:221)
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:2312)
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:2275)
E/ExoPlayerImplInternal(28311):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
E/ExoPlayerImplInternal(28311):       ... 3 more
D/SurfaceUtils(28311): disconnecting from surface 0x7ba4761010, reason disconnectFromSurface
I/flutter (28311): VideoPlayerValue(duration: 0:00:00.000000, size: Size(0.0, 0.0), position: 0:00:00.000000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), captionOffset: 0:00:00.000000, buffered: [], isInitialized: false, isPlaying: false, isLooping: false, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error)
```

flutter analyze
```
Analyzing test_video_stream...                                  

   info • Prefer const with constant constructors • lib/main.dart:60:13 • prefer_const_constructors
   info • The import of 'dart:ui' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/cupertino.dart' • lib/video_stream.dart:1:8 • unnecessary_import
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' • lib/video_stream.dart:3:8 • unnecessary_import
   info • Prefer const with constant constructors • lib/video_stream.dart:55:17 • prefer_const_constructors
   info • This method overrides a method annotated as '@mustCallSuper' in 'AutomaticKeepAliveClientMixin', but doesn't invoke the overridden method • lib/video_stream.dart:97:10 • must_call_super
   info • Prefer const over final for declarations • lib/video_stream.dart:98:5 • prefer_const_declarations
   info • Prefer const with constant constructors • lib/video_stream.dart:129:28 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/video_stream.dart:158:35 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/video_stream.dart:184:20 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/video_stream.dart:270:30 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/video_stream.dart:301:35 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/video_stream.dart:328:17 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/video_stream.dart:331:17 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/video_stream.dart:337:23 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/video_stream.dart:339:17 • prefer_const_constructors

15 issues found. (ran in 1.1s)

```

flutter doctor -v
```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.1 21C52 darwin-arm (Rosetta), locale en-TR)
    • Flutter version 3.0.2 at /Users/onatcipli/fvm/versions/3.0.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (13 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/onatcipli/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Users/onatcipli/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/onatcipli/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/onatcipli/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/onatcipli/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 67.0.3
    • Dart plugin version 213.7371

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/onatcipli/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

I will attach screen recording today

**Comment by maheshmnj** [comment]
Hi @onatcipli, Thanks for filing the issue. From your video description, the issue looks the same as https://github.com/flutter/flutter/issues/94449 Can you please check and confirm?

**Comment by onatcipli** [comment]
Hi @maheshmnj I check that issue and it's pretty similar but for my case I have only problem in android
