### ISSUE TITLE
Flutter doesn't understand filesystem paths used by gradle plugin 3.0.0

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10630]
I'm using Android Studio 3 preview 3 and updated my gradle plugin version to 3.0.0-alpha3 and when running flutter run in terminal I get a FileSystemException. The path does exist on my machine so I'm unsure why the error is being generated. I also filed an issue related to running flutter build apk (link below).

https://github.com/flutter/flutter/issues/10629

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d FA71A0302167

## exception

FileSystemException: FileSystemException: Cannot copy file to 'build/app/outputs/apk/app.apk', path = 'build/app/outputs/apk/app-debug.apk' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:599)
#1      _File.copySync (dart:io/file_impl.dart:321)
#2      _LocalFileSystemEntity&ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:25)
#3      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:250)
<asynchronous suspension>
#4      buildGradleProject (package:flutter_tools/src/android/gradle.dart:192)
<asynchronous suspension>
#5      buildApk (package:flutter_tools/src/commands/build_apk.dart:83)
<asynchronous suspension>
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:354)
<asynchronous suspension>
#7      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:233)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:183)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:329)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#11     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:217)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:206)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#19     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     runZoned (dart:async/zone.dart:1467)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#28     main (file:///Users/albertlardizabal/dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/albertlardizabal/dev/flutter
    • Framework revision 0f277fcc8a (6 days ago), 2017-06-06 17:19:27 +0200
    • Engine revision 8686a45810
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Pixel        • FA71A0302167                             • android-arm • Android 7.1.2 (API 25)
    •              • c0e109b7e55a826627aa0f3e79af8931534f3554 • ios         • iOS  ()
    • Posse iPhone • ac24c3de3cbe39efed542095769ce83fc89630f7 • ios         • iOS 10.3.1 (14E304)
    • iPhone 6     • 97A6FC25-AE09-4302-A8B3-565058389FE7     • ios         • iOS 10.3 (simulator)

```

**Comment by miksen** [comment]
Sorry to hear, do the instructions in https://github.com/flutter/flutter/issues/10236#issuecomment-303029027 work as a workaround?

**Comment by alardizabal** [comment]
I tried different combinations but this is what I see after pointing flutter config to an earlier version of gradle (3.3 - previously 3.5). The new exception is immediately below (file exception seems to be gone). I also included the outputs from flutter doctor and flutter run.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Failed to transform file 'flutter-x86.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file /Users/albertlardizabal/Posse/clients/test/test-flutter/build/app/intermediates/flutter/flutter-x86.jar does not exist.
```


```
☆ flutter doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/albertlardizabal/dev/flutter
    • Framework revision 37e32d5aee (20 hours ago), 2017-06-12 12:23:13 -0700
    • Engine revision ffe8181ffe
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Gradle (3.3)
    • gradle-dir = /usr/local/Cellar/gradle/3.3
    • Flutter supports building with Gradle from Android Studio.
      Consider removing your gradle-dir setting by running:
      flutter config --gradle-dir=

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29
```

```
☆ flutter run -d FA71A0302167
Launching lib/main.dart on Pixel in debug mode...
Running 'gradle assembleDebug'...                         
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
Configuration 'profileCompile' in project ':app' is deprecated. Use 'profileImplementation' instead.
Configuration 'releaseCompile' in project ':app' is deprecated. Use 'releaseImplementation' instead.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Configuration 'compile' in project ':firebase_analytics' is deprecated. Use 'implementation' instead.
Configuration 'debugProvided' in project ':firebase_analytics' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':firebase_analytics' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'compile' in project ':firebase_database' is deprecated. Use 'implementation' instead.
Configuration 'debugProvided' in project ':firebase_database' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':firebase_database' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'debugProvided' in project ':path_provider' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':path_provider' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'compile' in project ':permit' is deprecated. Use 'implementation' instead.
Configuration 'debugProvided' in project ':permit' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':permit' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'debugProvided' in project ':url_launcher' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':url_launcher' is deprecated. Use 'releaseCompileOnly' instead.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Failed to transform file 'flutter-x86.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file /Users/albertlardizabal/Posse/clients/test/test-flutter/build/app/intermediates/flutter/flutter-x86.jar does not exist.
```

**Comment by Hixie** [comment]
cc @mit-mit @mravn-google

**Comment by Hixie** [comment]
cc @jakobr-google

**Comment by asaarnak** [comment]
>@alardizabal 
>```
>FileSystemException: FileSystemException: Cannot copy file to 'build/app/outputs/apk/app.apk', path = >'build/app/outputs/apk/app-debug.apk' (OS Error: No such file or directory, errno = 2)
>```

Similar issue, after upgrading to gradle build tools "3.0.0-alpha3" and running flutter run --release.
I noticed that the file _app-release.apk_ that is not found is actually in 'build/app/outputs/apk/***release***/app-release.apk' folder.
But the path in exception logs is without the ***/release/*** folder.
```
FileSystemException: FileSystemException: Cannot copy file to 'build/app/outputs/apk/app.apk', path = 'build/app/outputs/apk/app-release.apk' (OS Error: No such file or directory, errno = 2)
```

**Comment by asaarnak** [comment]
Guide about migration to the new Android plugin 3.0.0-x. 
https://developer.android.com/studio/preview/features/new-android-plugin-migration.html

**Comment by asaarnak** [comment]
Current workaround for me was:
In file: flutterApp/android/app/build.gradle
```gradle
android {
    applicationVariants.all { variant ->
        variant.outputs.each  { output ->
            //outputs file to build/app/outputs/apk instead of build/app/outputs/apk/release
            output.outputFileName = "../app-release.apk"
        }
    }
}
```

**Comment by asaarnak** [comment]
I tried fixing in the flutter.gradle.
1. Adding the: `"project.compileDebugKotlin.dependsOn project.flutterBuildX86Jar"`, fixes the error `"flutter-x86.jar does not exist."` when using `"flutter run --debug"`
2. Adding the hack(currently no time to find better way): `output.outputFileName = "../app-${variant.name}.apk"` fixes the `(OS Error: No such file or directory, errno = 2)` when using `"flutter run --release"`

Complite diff of the flutter.gradle, testing on "gradle 4.0-rc-3" and "com.android.tools.build:gradle:3.0.0-alpha3":
```diff
Index: packages/flutter_tools/gradle/flutter.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- packages/flutter_tools/gradle/flutter.gradle	(revision 1a1bbacf0d16c1780377ea77580ec3b05c387f88)
+++ packages/flutter_tools/gradle/flutter.gradle	(revision )
@@ -19,9 +19,10 @@
 buildscript {
   repositories {
     jcenter()
+    google()
   }
   dependencies {
-    classpath 'com.android.tools.build:gradle:2.2.3'
+    classpath 'com.android.tools.build:gradle:3.0.0-alpha3'
   }
 }
 
@@ -100,7 +101,7 @@
             localEngineSrcPath = engineOut.parentFile.parent
 
             project.dependencies {
-                compile project.files(flutterJar)
+                implementation project.files(flutterJar)
             }
         } else {
             Path baseEnginePath = Paths.get(flutterRoot.absolutePath, "bin", "cache", "artifacts", "engine")
@@ -131,9 +132,9 @@
             }
 
             project.dependencies {
-                debugCompile project.files(flutterX86Jar, debugFlutterJar)
-                profileCompile project.files(profileFlutterJar)
-                releaseCompile project.files(releaseFlutterJar)
+                debugImplementation project.files(flutterX86Jar, debugFlutterJar)
+                profileImplementation project.files(profileFlutterJar)
+                releaseImplementation project.files(releaseFlutterJar)
             }
         }
 
@@ -147,7 +148,7 @@
             def pluginProject = project.rootProject.findProject(":$name")
             if (pluginProject != null) {
                 project.dependencies {
-                    compile pluginProject
+                    implementation pluginProject
                 }
                 pluginProject.afterEvaluate this.&addFlutterJarDependency
             } else {
@@ -182,6 +183,7 @@
 
         if (project.tasks.findByName('flutterBuildX86Jar')) {
             project.compileDebugJavaWithJavac.dependsOn project.flutterBuildX86Jar
+            project.compileDebugKotlin.dependsOn project.flutterBuildX86Jar
         }
 
         File kernel
@@ -226,6 +228,11 @@
                 with flutterTask.assets
             }
             variant.outputs[0].processResources.dependsOn(copyFlxTask)
+            variant.outputs.each  { output ->
+                //outputs file to build/app/outputs/apk instead of build/app/outputs/apk/$variant.name
+                //fast workaround, find better way
+                output.outputFileName = "../app-${variant.name}.apk"
+            }
         }
     }
 }
```

**Comment by jason-simmons** [comment]
We could also change flutter_tools to look for the APK in either the old (outputs/apk/app-$variant.apk) and new (outputs/apk/$variant/app-$variant.apk) locations

**Comment by eseidelGoogle** [comment]
@lukef my understanding is your team has moved back to gradle plugin 2.3 and this is no longer an immediate blocker?  Is that correct?

**Comment by lukef** [comment]
Correct

**Comment by alibitek** [comment]
For some reason, release APK builds fine, whereas debug APK does not. It fails with the following error when trying to build on GitLab CI:
```
[ +236 ms] :app:compileDebugKotlin
[  +10 ms] Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.1.4-3/kotlin-stdlib-jre7-1.1.4-3.jar
[ +103 ms] Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.1.4-3/kotlin-stdlib-1.1.4-3.jar
[  +20 ms] :app:compileDebugKotlin FAILED
[  +46 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] Could not resolve all files for configuration ':app:debugCompileClasspath'.
[        ] > Failed to transform file 'flutter-x86.jar' to match attributes {artifactType=android-classes} using transform JarTransform
[   +4 ms]    > Transform output file /builds/mycompany/myapp/build/app/intermediates/flutter/flutter-x86.jar does not exist.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 32s
[        ] 98 actionable tasks: 98 executed
[ +901 ms] "flutter apk" took 144,400ms.
Gradle build failed: 1
```

Locally both debug and release work fine. 

classpath 'com.android.tools.build:gradle:3.0.1'
compileSdkVersion 26
buildToolsVersion '27.0.2'
minSdkVersion 16
targetSdkVersion 26

**Comment by mit-mit** [comment]
@alibitek would you mind opening a new bug please with some details about the issue you are seeing?

**Comment by alibitek** [comment]
I think the issue I'm having is fixed in `master` branch by PR [Support Android Gradle plugin v3.0.1](https://github.com/flutter/flutter/pull/13492) , which is not yet merged into `alpha` branch

Meanwhile, I've applied the workaround mentioned by @asaarnak in https://github.com/flutter/flutter/issues/10992#issuecomment-337356417 and now the debug build successfully:
```
android/build.gradle 
...

// FIXME: Workaround for failing debug build https://github.com/flutter/flutter/issues/10992#issuecomment-337356417
// FIXED in https://github.com/flutter/flutter/pull/13492
configure(project(':app')) {
    tasks.compileDebugKotlin.dependsOn flutterBuildX86Jar
}
```

**Comment by 1and1get2** [comment]
it's Aug 2018 and I'm still having this issue

**Comment by zoechi** [comment]
@1and1get2 the issue is closed since a long time your issue is probably a different one or perhaps a regression.
Please create a new issue with the information that allows to reproduce.

**Comment by 1and1get2** [comment]
I don't yet aware a way to reliably reproduce this issue, however, most of the time it happens on a newly setup kotlin projects (probably fresh git clone?) the compiler complains about flutterBuildX86Jar task, once manually ran `./gradlew flutterBuildX86Jar` all is good.

I'll remember to gather more information on the next occurrence.

**Comment by zoechi** [comment]
@1and1get2 

> with the information that allows to reproduce.

at least as much as you can provide.

I'm just pretty sure comments on closed issues won't get enough attention.
