### ISSUE TITLE
Flutter web sometimes throw exception when popping a route

### ISSUE THREAD

**Issue by SuperPenguin** [flutter/flutter#106391]
## Steps to Reproduce

1. Run code below
2. Open browser debugger set device to any mobile phone models
3. Press open search
4. Tap on any result card
5. Open search again
6. Press back icon on app bar
7. repeat 4 and 5

**Expected results:** No exception

**Actual results:** Uncaught Error: Unexpected null value.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/',
      routes: {
        '/': (context) => const HomeScreen(),
        '/search': (context) => const SearchScreen(),
      },
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  String? _result;

  Future<void> _openSearch() async {
    final result = await Navigator.of(context).pushNamed('/search');

    if (mounted && result is String) {
      setState(() {
        _result = result;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        title: const Text('Home'),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('Result: $_result'),
            const SizedBox(height: 8.0),
            ElevatedButton(
              onPressed: _openSearch,
              child: const Text('Open Search'),
            ),
          ],
        ),
      ),
    );
  }
}

const List<String> searchItems = ['A', 'B', 'C', 'D', 'E'];

class SearchScreen extends StatefulWidget {
  const SearchScreen({Key? key}) : super(key: key);

  @override
  State<SearchScreen> createState() => _SearchScreenState();
}

class _SearchScreenState extends State<SearchScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        leading: const BackButton(),
        title: const Text('Search'),
      ),
      body: ListView.builder(
        itemCount: searchItems.length,
        itemBuilder: (context, index) {
          final item = searchItems[index];

          return Card(
            shape: const RoundedRectangleBorder(
              borderRadius: BorderRadius.all(
                Radius.circular(8.0),
              ),
            ),
            child: InkWell(
              onTap: () {
                Navigator.of(context).pop(item);
              },
              borderRadius: const BorderRadius.all(
                Radius.circular(8.0),
              ),
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text(item),
              ),
            ),
          );
        },
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:54591/dart_sdk.js:5080:11)
    at Object.nullCheck (http://localhost:54591/dart_sdk.js:5399:30)
    at [_getSanitizer] (http://localhost:54591/dart_sdk.js:173260:28)
    at http://localhost:54591/dart_sdk.js:173312:42
    at http://localhost:54591/dart_sdk.js:173273:16
    at loggedHandler (http://localhost:54591/dart_sdk.js:172978:11)
```

```
[✓] Flutter (Channel unknown, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-ID)
    • Flutter version 3.0.2 at /Users/s21/Documents/GitHub/flutter/flutter
    • Upstream repository unknown
    • Framework revision cd41fdd495 (13 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/s21/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

I'm not quite sure where it break. I already set it to debug code + packages + sdk, but it doesn't jump to where it break. It seems it throws deep inside dart js sdk
https://user-images.githubusercontent.com/1574722/174941043-b4588255-6da6-4b02-9ce0-8a41c8d843cd.mov

**Comment by huycozy** [comment]
Hi @SuperPenguin, thanks for filing the issue. 

I can reproduce this issue but I see there's an open issue #105458 that had the same behavior when clicking on AppBar's left side. 
Please notice that the sample works normally when using `pop` from ListView item (watch below demo video).

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/174995026-d6f0f266-0ef2-475d-bf21-783a433c5196.mp4

</details>

So I close this issue as a duplication, so please follow up on it for further updates.
If you disagree, please write in the comments and I will reopen it.
