### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: File name too long, errno = 63

### ISSUE THREAD

**Issue by GaurFlutter** [flutter/flutter#106470]
## Command
```
flutter run --no-sound-null-safety
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: File name too long, errno = 63
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:953:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:792:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:697:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#8      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:502:26)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:287:41)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 3.0.3 at /Users/gauravnegi/Development/flutter
    • Upstream repository https://g
    
    
    
Can anyone help me in this
build is not making

**Comment by huycozy** [comment]
Hi @GaurFlutter, thanks for filing the issue. 
I see there's an open issue addressing the case you described #80873
Closing as a duplication, so please follow up on it for further updates.
