### ISSUE TITLE
[camera] _startPlatformStream not working Xiaomi 11 pro 5g

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#106490]
We have a customer and the camera refuses to work for him and we get this error on firebase. 

It works for everyone else so it seems to be related to the device.

PlatformException(CameraAccess, CAMERA_ERROR (3): deleteStream:941: Camera 1: Unexpected error Invalid argument (-22) when deleting stream 0, null, null). Error thrown null.

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(CameraAccess, CAMERA_ERROR (3): deleteStream:941: Camera 1: Unexpected error Invalid argument (-22) when deleting stream 0, null, null). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:607)
       at MethodChannel._invokeMethod(platform_channel.dart:167)
       at MethodChannelCamera._startPlatformStream(method_channel_camera.dart:295)

flutter doctor:
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3.1 21E258 darwin-arm, locale en-GR)
    • Flutter version 3.0.2 at /Users/nikostsesmelis/Tools/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

camera plugin version: 0.9.7+1 (not able to upgrade due to ios issue)

**Comment by huycozy** [comment]
Hi @NikosTsesmelis 
Could you provide the full log from Firebase Crashlytics here? 
Also, the same thought in https://github.com/flutter/flutter/issues/106493#issuecomment-1165430734
Thank you!

**Comment by NikosTsesmelis** [comment]
<img width="1289" alt="Screenshot 2022-06-24 at 1 25 01 PM" src="https://user-images.githubusercontent.com/100851392/175517244-e679cd49-6653-47c8-a424-4623af319c1f.png">

this is pretty much all I have from the crash. Or do you need something different? In that case please tell me where to find these logs

**Comment by huycozy** [comment]
@NikosTsesmelis
Thank you! Labeling this issue for further investigation from the team.

**Comment by Miko2x** [comment]
@huycozy 
These are all the logs I got when debugging using the Xiaomi Redmi Note 11 Pro 5G.

```
I/CameraManagerGlobal( 7888): Connecting to camera service
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 2
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 3
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 4
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 5
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 6
W/CameraManagerGlobal( 7888): ignore the torch status update of camera: 2
W/CameraManagerGlobal( 7888): ignore the torch status update of camera: 3
W/CameraManagerGlobal( 7888): ignore the torch status update of camera: 4
W/CameraManagerGlobal( 7888): ignore the torch status update of camera: 5
I/CameraMetadataJV( 7888): setAppNameAndSensorId all [com.antutu:0,ssize,12032x9024,0,false]
I/CameraMetadataJV( 7888): setAppNameAndSensorId all [com.antutu:1,ssize,4608x3456,0,false]
2
D/FrameIndicator( 7888): support status: 1 0x72ab3b5018 0x72ab3b54c4
D/CameraInjector( 7888): notifyRF for API 2 : cameraRoleId = 1, active = true
D/CameraInjector( 7888): notifyRF cameraId = 1, active ? true
I/Camera  ( 7888): startPreview
D/FrameIndicator( 7888): support status: 1 0x72ab3b5018 0x72ab3b54c4
I/Camera  ( 7888): CameraCaptureSession onConfigured
I/Camera  ( 7888): Updating builder settings
D/Camera  ( 7888): Updating builder with feature: ExposureLockFeature
D/Camera  ( 7888): Updating builder with feature: ExposurePointFeature
D/Camera  ( 7888): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 7888): Updating builder with feature: AutoFocusFeature
D/Camera  ( 7888): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 7888): updateNoiseReduction | currentSetting: fast
D/Camera  ( 7888): Updating builder with feature: FocusPointFeature
D/Camera  ( 7888): Updating builder with feature: ResolutionFeature
D/Camera  ( 7888): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 7888): Updating builder with feature: FlashFeature
D/Camera  ( 7888): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 7888): Updating builder with feature: FpsRangeFeature
I/Camera  ( 7888): refreshPreviewCaptureSession
I/Camera  ( 7888): open | onError
I/Camera  ( 7888): close
D/CameraInjector( 7888): notifyRF for API 2 : cameraRoleId = 1, active = false
D/CameraInjector( 7888): notifyRF cameraId = 1, active ? false
W/BpBinder( 7888): Slow Binder: BpBinder transact took 802 ms, interface=android.hardware.camera2.ICameraDeviceUser, code=1 oneway=false
E/MethodChannel#plugins.flutter.io/camera_android( 7888): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera_android( 7888): java.lang.IllegalStateException: CameraDevice was already closed
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2324)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:821)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at io.flutter.plugins.camera.Camera$DefaultCameraDeviceWrapper.createCaptureRequest(Camera.java:171)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:399)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:389)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at io.flutter.plugins.camera.Camera.startPreviewWithImageStream(Camera.java:1088)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:255)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at android.os.Looper.loop(Looper.java:237)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at android.app.ActivityThread.main(ActivityThread.java:8163)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/MethodChannel#plugins.flutter.io/camera_android( 7888): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:972)
E/flutter ( 7888): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, CameraDevice was already closed, null, java.lang.IllegalStateException: CameraDevice was already closed
E/flutter ( 7888): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2324)
E/flutter ( 7888): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:821)
E/flutter ( 7888): 	at io.flutter.plugins.camera.Camera$DefaultCameraDeviceWrapper.createCaptureRequest(Camera.java:171)
E/flutter ( 7888): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:399)
E/flutter ( 7888): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:389)
E/flutter ( 7888): 	at io.flutter.plugins.camera.Camera.startPreviewWithImageStream(Camera.java:1088)
E/flutter ( 7888): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:255)
E/flutter ( 7888): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 7888): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 7888): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/flutter ( 7888): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter ( 7888): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 7888): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7888): 	at android.os.Looper.loop(Looper.java:237)
E/flutter ( 7888): 	at android.app.ActivityThread.main(ActivityThread.java:8163)
E/flutter ( 7888): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7888): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/flutter ( 7888): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:972)
E/flutter ( 7888): )
E/flutter ( 7888): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter ( 7888): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:167
E/flutter ( 7888): <asynchronous suspension>
E/flutter ( 7888): #2      AndroidCamera._startPlatformStream
package:camera_android/src/android_camera.dart:308
E/flutter ( 7888): <asynchronous suspension>
E/flutter ( 7888):
W/CameraManagerGlobal( 7888): ignore the torch status update of camera: 5
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 5
W/CameraManagerGlobal( 7888): ignore the torch status update of camera: 3
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 3
W/CameraManagerGlobal( 7888): ignore the torch status update of camera: 2
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 2
W/CameraManagerGlobal( 7888): ignore the torch status update of camera: 4
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 4
W/CameraManagerGlobal( 7888): [soar.cts] ignore the status update of camera: 6
E/CameraManagerGlobal( 7888): Camera 4 is not available. Ignore physical camera status change
```

**Comment by CaoGiaHieu-dev** [comment]
Hi . i have same problem with this device . It happen when i call startImageStream  after initialize camera 
im using camera version 0.10.0+4
Example code :
<img width="307" alt="Ảnh màn hình 2022-12-06 lúc 08 16 29" src="https://user-images.githubusercontent.com/57854043/205783595-1ac12fae-5dbe-4656-ac35-e29be69d90df.png">

Logs:
`
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
	at io.flutter.plugins.camera.Camera.startPreviewWithImageStream(Camera.java:1076)
	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:255)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8301)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1043)
). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:296)
       at AndroidCamera._startPlatformStream(android_camera.dart:307)`

flutter doctor -v

   [✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64, locale vi)
    • Flutter version 3.3.9 on channel stable at /Users/caogiahieu/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (13 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/caogiahieu/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Users/caogiahieu/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • Cao Gia Hiếu (mobile)              • e3010bcca1500cf8a43f8baba42c0d712114c722 • ios         • iOS 16.1 20B82

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by aap01** [comment]
I am having the same issue.

@NikosTsesmelis 
Did you find any alternative solution to this?

**Comment by singlapriyanka315** [comment]
@aap01  @NikosTsesmelis getting a issue that when camera captures image from back camera it is taking 5-8 seconds which is a lot and getting this in logs Slow Binder: BpBinder transact took 386 ms, interface=android.hardware.camera2.ICameraDeviceUser, code=1 oneway=false .Can i get a solution for this.

**Comment by madmouse17** [comment]
can i get solution for this? 
 Slow Binder: BpBinder transact took 512 ms, interface=android.hardware.ICameraService, code=4 oneway=false
W/MessageQueue(  328): Handler (android.os.Handler) {8356a21} sending message to a Handler on a dead thread

i use version camera [latest](camera: ^0.10.5+3) and i use device redmi note 9pro

**Comment by thassio-vinicius** [comment]
Seems like this issue is still happening on the latest v0.10.5. Could we bring some awareness to this?

**Comment by darshankawar** [comment]
Revisiting this issue, @NikosTsesmelis I suggest you to reverify this issue using latest stable sdk (3.38.4) and latest camera plugin [version](https://pub.dev/packages/camera) which makes use of https://pub.dev/packages/camera_android_camerax that is built with cameraX library and undergone lot of updates and then check if you still get reported behavior on affected device or not.
