### ISSUE TITLE
Hot Reload: FormatException: Source contains non-ASCII bytes. 

### ISSUE THREAD

**Issue by Khalid-Nowaf** [flutter/flutter#10652]
## Steps to Reproduce
hot reload failed while using non-latin strings in the source code, I used 'Arabic'. 
````dart
 new TextStyleItem(name: 'Display 3', style: textTheme.display3, text: 'تجربة');
````

## Logs
````
Unhandled exception:
FormatException: Source contains non-ASCII bytes.
#0      _SimpleAsciiDecoderSink.add (dart:convert/ascii.dart:293)
#1      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#2      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#3      _rootRunUnary (dart:async/zone.dart:1128)
#4      _CustomZone.runUnary (dart:async/zone.dart:1012)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#8      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#9      _StreamController._add (dart:async/stream_controller.dart:667)
#10     _StreamController.add (dart:async/stream_controller.dart:613)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#12     _rootRunUnary (dart:async/zone.dart:1132)
#13     _CustomZone.runUnary (dart:async/zone.dart:1012)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#17     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#18     _StreamController._add (dart:async/stream_controller.dart:667)
#19     _StreamController.add (dart:async/stream_controller.dart:613)
#20     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#21     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
../../runtime/vm/dart_api_impl.cc: 1878: error: Dart_GetMainPortId expects there to be a current isolate. Did you forget to call Dart_CreateIsolate or Dart_EnterIsolate?
`````

Run `flutter analyze` and attach any output of that command also.
````
Analyzing /Users/xxxx/projects/flutter/examples/flutter_gallery...
No issues found!
Ran in 9.1s
````
## Flutter Doctor
````
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-CA, channel master)
    • Flutter at /Users/xxxx/Library/flutter
    • Framework revision db75aa768c (2 hours ago), 2017-06-12 19:46:38 -0700
    • Engine revision ffe8181ffe
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[-] IntelliJ IDEA Ultimate Edition (version 2016.3.1)
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 14.0.0
    • Dart plugin version 163.13137
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[-] WebStorm (version 2016.3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected devices
    • iPhone SE • 71C81361-B8E3-4343-AD61-4D4BB4BF581E • ios • iOS 10.3 (simulator)
````

**Comment by eseidelGoogle** [comment]
That's definitely bad. :/  Thanks for the report!  FYI @a-siva

**Comment by Hixie** [comment]
@Khalid-Nowaf Can you confirm that your source is encoded as UTF-8?

**Comment by jason-simmons** [comment]
I was able to do a successful hot reload using a source file containing the example Arabic text (encoded in UTF-8).

This was on Linux and Mac hosts with an Android device target.

**Comment by Khalid-Nowaf** [comment]
The first hot reload usually ok. When I change a string to arabic and hit 'r' I get this error. How can I confirm if my source as UTF-8 ?

**Comment by Khalid-Nowaf** [comment]
BTW, I edit the Gallery example text to Arabic, and then I got this problem.

**Comment by jason-simmons** [comment]
Check the encoding settings in your text editor.

Or try a Python script like this:
```
x = file("lib/main.dart").read()
print x.decode("utf-8")
```
and verify that the file decodes as expected.

**Comment by eseidelGoogle** [comment]
If we do validate that it's non-utf8 characters causing this, we definitely should turn this into a fix-our-error-messages bug. :D

**Comment by Khalid-Nowaf** [comment]
I use the hello world example to test the decoding
![](https://media.giphy.com/media/l0IyaYVOeRHlWBXRC/giphy.gif)

and here also Gif to that illustrate the issue
![](https://media.giphy.com/media/3oKIPxMpcVf1pQxuUw/giphy.gif)

*note: if I use Arabic text then run `flutter run` everything will work as expected, after changing the "adding" or "modifying" any Arabic text then press I `r`, I will get the `FormatException: Source contains non-ASCII bytes.`

**Comment by Hixie** [comment]
Hot reload after adding arabic seems to work for me now. Please reopen if it is still broken for you.

**Comment by daneshvar** [comment]
Your keyboard layout is Arabic in terminal and hit r and in fact your typing ق (non ASCII) instead r, and "flutter" raise this error. befor press "r" key in terminal, change your keyboard layout to English.

**Comment by Khalid-Nowaf** [comment]
thanks, @daneshvar !!.

**Comment by Hixie** [comment]
Oh, interesting.

**Comment by Khalid-Nowaf** [comment]
@Hixie, do thing the CLI should ignore any non-ASCII,  instead of crashing

**Comment by Hixie** [comment]
Yeah, totally. We shall investigate further!

**Comment by Hixie** [comment]
Filed https://github.com/flutter/flutter/issues/18007 to track the crash mentioned above.
