### ISSUE TITLE
[tool_crash] ProcessException: flutter_FlutterMacOS.framework.zip.rYrplJ/Versions/A/FlutterMacOS is probably truncated Command: unzip, OS error code: 50

### ISSUE THREAD

**Issue by selaboudi** [flutter/flutter#106606]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs

```
ProcessException: The command failed
Stdout:

Stderr:
/var/folders/7r/snn2t6w10plc14h0f49l343r0000gn/T/flutter_tools.sp27VQ/flutter_FlutterMacOS.framework.zip.rYrplJ/Versions/A/FlutterMacOS:  write error (disk full?).  Continue? (y/n/^C) 
warning:  /var/folders/7r/snn2t6w10plc14h0f49l343r0000gn/T/flutter_tools.sp27VQ/flutter_FlutterMacOS.framework.zip.rYrplJ/Versions/A/FlutterMacOS is probably truncated
 Command: unzip, OS error code: 50
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:411:17)
#2      _MacOSUtils.unzip (package:flutter_tools/src/base/os.dart:438:23)
#3      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:919:30)
<asynchronous suspension>
#4      CachedArtifact.update (package:flutter_tools/src/cache.dart:812:5)
<asynchronous suspension>
#5      Cache.updateAll (package:flutter_tools/src/cache.dart:681:9)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1294:7)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.3, on Mac OS X 10.13.6 17G65 darwin-x64, locale fr-FR)
    • Flutter version 3.0.3 at /Users/saadelaboudi/Downloads/Diskyver/Produit/TrustCall/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (3 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    • Android SDK at /Users/saadelaboudi/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.13.6 17G65 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
awesome_notifications-0.6.21
call_log-3.2.3
connectivity_plus-2.3.5
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.4
connectivity_plus_web-1.2.2
connectivity_plus_windows-1.2.2
flutter_native_splash-2.2.3+1
flutter_phone_direct_caller-2.1.1
fluttertoast-8.0.9
path_provider-2.0.11
path_provider_android-2.0.15
path_provider_ios-2.0.10
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.0
permission_handler-9.2.0
permission_handler_android-9.0.2+1
permission_handler_apple-9.0.4
permission_handler_windows-0.1.0
phone_call_notifier-1.0.0
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
unique_identifier-0.2.2
workmanager-0.5.0

**Comment by darshankawar** [comment]
There were couple of instances of this crash which got closed due to inactivity:

https://github.com/flutter/flutter/issues/78132
https://github.com/flutter/flutter/issues/73202

Keeping it open and labeling based on above.

/cc @christopherfujino
