### ISSUE TITLE
Tree red on "Windows framework_tests_widgets" failure

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#106697]
Several failures in `flutter\packages\flutter\test\widgets\widget_inspector_test.dart`:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8810172323157034049/+/u/run_test.dart_for_framework_tests_shard_and_subshard_widgets/test_stdout

**Comment by christopherfujino** [comment]
```
02:24 +4159 ~51: C:\b\s\w\ir\x\w\flutter\packages\flutter\test\widgets\widget_inspector_test.dart: ext.flutter.inspector.trackRepaintWidgets                                                           
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <18>
  Actual: <0>

When the exception was thrown, this was the stack:
#4      _TestWidgetInspectorService.runTests.<anonymous closure> (file:///C:/b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/widget_inspector_test.dart:2689:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///C:/b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/widget_inspector_test.dart line 2689
The test description was:
  ext.flutter.inspector.trackRepaintWidgets
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by christopherfujino** [comment]
```
02:24 +4159 ~51 -1: C:\b\s\w\ir\x\w\flutter\packages\flutter\test\widgets\widget_inspector_test.dart: ext.flutter.inspector.show                                                                       
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The value of a rendering debug variable was changed by the test.

When the exception was thrown, this was the stack:
#0      debugAssertAllRenderVarsUnset.<anonymous closure> (package:flutter/src/rendering/debug.dart:308:7)
#1      debugAssertAllRenderVarsUnset (package:flutter/src/rendering/debug.dart:311:4)
#2      TestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:887:12)
#3      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1285:11)
#4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:863:7)
<asynchronous suspension>

The test description was:
  ext.flutter.inspector.show
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by christopherfujino** [comment]
cc @dnfield, possibly caused by https://github.com/flutter/flutter/pull/105537/files ?

**Comment by christopherfujino** [comment]
This went green on the next (unrelated) commit, so it must be a flake: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20framework_tests_widgets/5375/overview
