### ISSUE TITLE
Firebase Plugin crashes in iOS Airplane mode

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10669]
## Steps to Reproduce
Build an app with a decent amount of complexity, run it in airplane mode and crash

## Logs

```
Launching lib/main.dart on Kevin's iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3MT3K2SKK7
Firebase automatic screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO in the Info.plist
libMobileGestalt MobileGestaltSupport.m:153: pid 298 (Runner) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)
You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2017-06-13 15:50:37.394 Runner[298:14798] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-06-13 15:50:37.404 Runner[298] <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-06-13 15:50:37.407: <FIRInstanceID/WARNING> FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
Faulting in NSHTTPCookieStorage singleton
Faulting in CFHTTPCookieStorage singleton
Creating default cookie storage with default identifier
TIC TCP Conn Start [1:0x170196580]
TIC TCP Conn Event [1:0x170196580]: 3 Err(50)
TIC TCP Conn Failed [1:0x170196580]: 1:50 Err(50)
TIC TCP Conn Cancel [1:0x170196580]
TIC TCP Conn Destroyed [1:0x170196580]
_CFNetworkIsConnectedToInternet returning 0, flagsValid: 1, flags: 0x0
HTTP load failed (error code: -1009 [1:50])
NSURLSessionTask finished with error - code: -1009
<FIRAnalytics/INFO> Firebase Analytics v.3501000 started
2017-06-13 15:50:37.473 Runner[298:] <FIRAnalytics/INFO> Firebase Analytics v.3501000 started
<FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
2017-06-13 15:50:37.477 Runner[298:] <FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
<FIRAnalytics/INFO> Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
2017-06-13 15:50:37.508 Runner[298:] <FIRAnalytics/INFO> Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
<FIRAnalytics/WARNING> The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
2017-06-13 15:50:37.513 Runner[298:] <FIRAnalytics/WARNING> The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
<Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}
2017-06-13 15:50:37.519 Runner[298:14798] <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _k
2017-06-13 15:50:37.519 Runner[298:14798] <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _k
2017-06-13 15:50:37.519 Runner[298:14798] <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _k
[Firebase/Core][I-COR000020] Error posting to Clearcut: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}, with Status Code: 0
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:51577/ws
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:670)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:500)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:348)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:176)
#5      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:89)
<asynchronous suspension>
#6      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:537)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:93)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:193)
<asynchronous suspension>
#9      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:413)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1467)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:766)
#17     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:411)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:250)
<asynchronous suspension>
#19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#20     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:217)
<asynchronous suspension>
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#22     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:206)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#28     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#29     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#30     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#31     _rootRun (dart:async/zone.dart:1120)
#32     _CustomZone.run (dart:async/zone.dart:1001)
#33     runZoned (dart:async/zone.dart:1467)
#34     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#35     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#36     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#37     main (file:///Users/KG/Developer/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 272faba1c0 (4 hours ago), 2017-06-13 08:28:16 -0700
    • Engine revision 4f5d6fab11
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • SM G930V       • a674c503                                 • android-arm • Android 6.0.1 (API 23)
    • Kevin's iPhone • c95c86bdc3aac565adb373de3dc2dbedcdecc900 • ios         • iOS 10.3.1 (14E304)
    • iPhone 7       • 9ED2849F-A511-4383-8EEA-B57640557B49     • ios         • iOS 10.3 (simulator)
```

**Comment by Hixie** [comment]
cc @cbracken Can you look at this?

**Comment by cbracken** [comment]
Happy to!

**Comment by cbracken** [comment]
Narrowing down the scope a bit:
Running an app that doesn't rely on networking should work fine -- i.e., there doesn't appear to be anything inherent to Flutter development/debugging that breaks when aeroplane mode is enabled. I'm able to do hot-reload development on a basic hello-world app with no issues.

In this case, it looks like there may be an unhandled network error from Firebase on the native side:
```
<Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}
2017-06-13 15:50:37.519 Runner[298:14798] <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _k
2017-06-13 15:50:37.519 Runner[298:14798] <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _k
2017-06-13 15:50:37.519 Runner[298:14798] <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _k
[Firebase/Core][I-COR000020] Error posting to Clearcut: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x170247110 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}, with Status Code: 0
```

I'm assuming you're using the Firebase plugin? I'll see if I can wire it up and get a repro.

**Comment by KevinTheGray** [comment]
@cbracken yeah, here are our plugins from pubspec.yaml

```
dependencies:
  flutter:
    sdk: flutter
  path_provider: "^0.2.1+1"
  fluro: "^1.1.0"
  firebase_analytics: "^0.0.2"
  firebase_database: "^0.0.6"
  url_launcher: "^0.4.2+1"
```

**Comment by eseidelGoogle** [comment]
@collinjackson can you drive this to completion?

**Comment by collinjackson** [comment]
Yes, I'd be happy to investigate. Thanks for filing this.

**Comment by collinjackson** [comment]
** Hot reloading in airplane **

Hot reload/refresh on a device is not working for me in airplane mode, either from the command line or IntelliJ. The app launches, but I see messages like this:

```
$ flutter run -d 14710ae2e8497590643751c5532d907ed1ff2eed
Launching lib/main.dart on  in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: EQHXZ8M8AV
Running pod install...                                2.9s
Running Xcode build...                               14.1s
Timeout while attempting to retrieve URL for Observatory
```

I'm testing on an iPhone 7 in airplane mode with a basic hello world template app, as well as firebase_auth's example with the other FlutterFire plugins added. I wonder if @cbracken was testing a different scenario than me, or he just meant that the app didn't crash.

** Firebase crash **

I'm able to consistently repro the airplane mode crash when launching the Firebase Analytics example app reliably in airplane mode (works fine when network is available). It also crashes on the simulator when I turn my laptop's wifi off. The only Firebase related code we are calling is this:

    if (![FIRApp defaultApp]) {
      [FIRApp configure];
    }

I see a lot of log messages coming from Firebase as it starts up and tries to log its attempts to connect to the network. If I run in the debugger it traps on these with SIGPIPE. If I continue past them in the debugger, the app doesn't crash.

The crash goes away if I add this do the Firebase Analytics plugin somewhere.

    signal(SIGPIPE, SIG_IGN);

That's something we're [doing already](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m#L45) in the Google Sign In plugin.

It also goes away when I build with --no-redirect-to-syslog as shown in [this video](https://www.youtube.com/watch?v=_NhSTyWvZbs)

So we could fixt this by ignorning SIGPIPE in the plugin, but we're going to keep running into this with future plugins unless we can make --no-redirect-to-syslog behave more nicely.

@chinmaygarde @tvolkert WDYT? Maybe we can disable SIGPIPE right before [calling asl_log_descriptor in engine](https://github.com/flutter/engine/blob/f5a7a086ec8d5aeaf2abd9bf3f7f4e0f3320837e/shell/platform/darwin/common/platform_mac.mm#L29) and re-enable it afterwards?

I'm wondering if we should just do this in the engine by default so that plugins don't have to.

@tvolkert @mit-mit @goderbauer @jakobr-google @mravn-google @szakarias WDYT?

P.S. here's are my `flutter doctor` results

[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision 3db402ec98 (9 hours ago), 2017-06-15 23:01:25 -0700
    • Engine revision f741647d49
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/jackson/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/jackson/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.1
    • CocoaPods version 1.0.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.1.3)
    ✗ Flutter plugin version 13.1 - the recommended minimum version is 14.0.0
    • Dart plugin version 171.4424.63
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    •               • 14710ae2e8497590643751c5532d907ed1ff2eed • ios • iOS  ()
    • iPhone 7 Plus • F8A917C4-9848-49C2-8F0D-664B49E0B635     • ios • iOS 10.3 (simulator)

Here are the crash logs I get (using simulator).

```
CoreSimulatorBridge: Launch successful for 'io.flutter.firebaseAnalyticsExample'
You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2017-06-16 09:25:14.239 Runner[25475:9793550] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
2017-06-16 09:25:14.258 Runner[25475] <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
[Firebase/Analytics][I-ACS005000] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
2017-06-16 09:25:14.261 Runner[25475] <Warning> [Firebase/Analytics][I-ACS005000] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
[Firebase/Analytics][I-ACS023007] Firebase Analytics v.4000000 started
2017-06-16 09:25:14.262 Runner[25475] <Notice> [Firebase/Analytics][I-ACS023007] Firebase Analytics v.4000000 started
[Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2017-06-16 09:25:14.264 Runner[25475] <Notice> [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[Firebase/Analytics][I-ACS003007] Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
2017-06-16 09:25:14.273 Runner[25475] <Notice> [Firebase/Analytics][I-ACS003007] Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
<Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x608000056080 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}
2017-06-16 09:25:14.593 Runner[25475:9793550] <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x608000056080 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKe
2017-06-16 09:25:14.593 Runner[25475:9793550] <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x608000056080 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKe
[Firebase/Core][I-NET901017] <Firebase/Network/ERROR> Encounter network error. Code, error: -1009, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x608000056080 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}
```

**Comment by collinjackson** [comment]
I split off the hot reload question into a separate issue #10775. It looks like my libimobiledevice was out of date.

I talked to @cbracken and it sounds like this issue will be fixed with the same fix he is working on for #10358 #6758. Assigning back to him since this isn't really about plugins, though I'm happy to clean up the SIGPIPE hack in google_sign_in plugin when he's done.

**Comment by eseidelGoogle** [comment]
Unclear what the current status of this bug is?

**Comment by eseidelGoogle** [comment]
The result of this bug is that it's a crash as a result of too many log statements on iOS causing a crash.  This root bug @cbracken is currently working on resolving.

**Comment by mit-mit** [comment]
Is this log issue related to the plugin, or a general iOS platform issue?

**Comment by eseidelGoogle** [comment]
The log issue is a general iOS issue which @cbracken is working on resolving.  The Firebase plugin just happens to log enough in airplane mode to trigger the crash.

**Comment by cbracken** [comment]
A fix to the SIGPIPE issue was landed in flutter/engine#3797. Rolled into the framework in #10859. This will be part of the `0.0.11` alpha release when it's cut.

@collinjackson is there anything further for this one?

**Comment by collinjackson** [comment]
Let me test to make sure the crash is fixed, and then I'll close it out.

**Comment by collinjackson** [comment]
I tested just now on 2f979914e4 which includes your engine roll and it no longer crashes. Thanks!

**Comment by kroikie** [comment]
@KevinTheGray

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/998. Any further collaboration will be done there.
