### ISSUE TITLE
[tool crash] StdinException: StdinException: Error setting terminal line mode, OS Error: The handle is invalid. , errno = 6

### ISSUE THREAD

**Issue by Massawe14** [flutter/flutter#106722]
## command

flutter run --no-sound-null-safety

## exception

StdinException: StdinException: Error setting terminal line mode, OS Error: The handle is invalid.
, errno = 6

```
#0      Stdin.lineMode= (dart:io-patch/stdio_patch.dart:129:7)
#1      AnsiTerminal.singleCharMode= (package:flutter_tools/src/base/terminal.dart:292:13)
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:722:24)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1195:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1243, on Microsoft Windows [Version 10.0.19044.1766], locale en-US)
    • Flutter version 3.1.0-0.0.pre.1243 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dc06326caa (13 days ago), 2022-06-13 16:48:09 -0700
    • Engine revision 6670f92130
    • Dart version 2.18.0 (build 2.18.0-180.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\MASSAWE\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.2.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.2.32519.379
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and
      include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.68.1)
    • VS Code at C:\Users\MASSAWE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.37

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by danagbemava-nc** [comment]
Labeling this for further investigation as I can't find any existing issues

**Comment by christopherfujino** [comment]
@Massawe14 thank you for filing this! It looks to me like you were running this from the terminal? And I'm guessing you didn't do anything weird like close your terminal while the CLI tool was running?

I'm trying to figure out why the OS is saying the STDIN handle in invalid.
