### ISSUE TITLE
Process 'command 'E:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by vanred79** [flutter/flutter#106850]
Hello! Error when creating apk:

Running Gradle task 'assembleRelease'...                        
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:carousel_pro
 - package:full_screen_image

For solutions, see https://dart.dev/go/unsound-null-safety

FAILURE: Build failed with an exception.

* Where:
Script 'E:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'E:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
Running Gradle task 'assembleRelease'...                           58,5s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

E:\myapplication>flutter run --verbose
[ +172 ms] executing: [E:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +231 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[   +1 ms] executing: [E:\flutter/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[ +325 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] 3.0.1
[  +16 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +115 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [E:\flutter/] git ls-remote --get-url origin
[ +101 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +272 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref HEAD
[ +153 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[ +190 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +145 ms] executing: C:\Users\vanred79\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +730 ms] List of devices attached
[ +193 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ +301 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ +318 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +615 ms] No supported devices connected.
[  +77 ms] The following devices were found, but are not supported by this project:
           Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1766]
           Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.115
           Edge (web)        • edge    • web-javascript • Microsoft Edge 102.0.1245.30
           If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.
           
[  +32 ms] "flutter run" took 2 480ms.
[  +61 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:484:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1298:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +272 ms] ensureAnalyticsSent: 262ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

E:\myapplication>flutter doctor -v
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1766], locale kk-KZ)
    • Flutter version 3.0.1 at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\vanred79\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: E:\android1\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 2020.3)
    • Android Studio at E:\android1\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\vanred79\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 102.0.1245.30

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

Please tell me how to solve this problem?

**Comment by vanred79** [comment]
tried deleting the pubspec.lock file
and
flutter clean
flutter pub get
did not help

**Comment by danagbemava-nc** [comment]
Hi @vanred79, I would advise that you update to null-safe alternatives of the packages that you are using. From what I see on pub.dev `carousel_pro` was last updated 3 years ago and `full_screen_image` was updated 2 years ago. 

This means these packages are no longer being maintained and may cause bugs in your app in the future since they may be using deprecated code. There should be null-safe alternatives for each of these packages on pub.dev. 

If you are pressed for time, you can try running any of the following commands to see if it helps

`flutter build apk --no-sound-null-safety` or `flutter build appbundle --no-sound-null-safety`
