### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.Receiver: nullTried calling: assetPathsToEvict

### ISSUE THREAD

**Issue by deva666** [flutter/flutter#106880]
## Command
```
flutter run
```

## Steps to Reproduce
--

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:510:20)
#2      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:578:5)
<asynchronous suspension>
#3      HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:760:16)
<asynchronous suspension>
#4      HotRunner.restart (package:flutter_tools/src/run_hot.dart:707:38)
<asynchronous suspension>
#5      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1645:40)
<asynchronous suspension>
#6      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1685:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 3.0.3 at /Users/marko/Documents/Repos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (8 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/marko/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • GM1913 (mobile) • 68f90884 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: cf4400006550b70f28e4b4af815151d1e74846c6
### Plugins
cloud_firestore-3.1.18
cloud_firestore_web-2.6.17
desktop_webview_auth-0.0.9
firebase_auth-3.3.20
firebase_auth_web-3.3.17
firebase_core-1.18.0
firebase_core_web-1.6.5
firebase_database-9.0.16
firebase_database_web-0.2.0+15
firebase_dynamic_links-4.2.6
flutter_facebook_auth-4.3.4+2
flutter_facebook_auth_web-3.1.2
google_sign_in-5.3.3
google_sign_in_android-5.2.8
google_sign_in_ios-5.3.1
google_sign_in_web-0.10.1+3
path_provider-2.0.11
path_provider_android-2.0.16
path_provider_ios-2.0.10
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.0
sign_in_with_apple-3.3.0
sign_in_with_apple_web-1.0.1
twitter_login-4.2.3
url_launcher-6.1.4
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.12
url_launcher_windows-3.0.1

**Comment by maheshmnj** [comment]
Hi @deva666,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/89738, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
