### ISSUE TITLE
[iOS] Running on a physical device fails with `Target debug_unpack_ios failed: Exception: Failed to codesign: errSecInternalComponent`

### ISSUE THREAD

**Issue by SyferDev** [flutter/flutter#106876]
I tried to run a project on multiple physical iOS devices but the same `Command PhaseScriptExecution failed with a nonzero exit code` error keeps happening.

It works on the simulator but does not work on physical devices. Same results happen on a fresh blank project. The same error also pops up when building using Xcode.

## Steps to Reproduce

1. Create new Flutter project
2. Connect iOS device
3. Run the project

## Logs

<details>
<summary>Logs</summary>

```
  Launching lib/main.dart on aaaa in debug mode...
lib/main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: WVN3D5J9Q3
Xcode build done.                                            9.3s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-06-30 21:46:03.153 xcodebuild[35773:845109] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-06-30 21:46:03.153 xcodebuild[35773:845109] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-06-30 21:46:03.712 xcodebuild[35773:845111]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
    Details:  (null) deviceType from 00008101-0009196C3A7A001E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x13176cc30>
    Method:   -platform
    Thread:   <NSThread: 0x600003078400>{number = 3, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/n6/pn8cjglx0qlbpzv_fqv3frmc0000gn/T/flutter_tools.FnYXJg/flutter_ios_build_temp_dirXKzhW9/temporary_xcresult_bundle
    rsync: link_stat "/Users/seifer/dev/projects/likecash/baryacard/build/ios/Debug-iphoneos/App.framework" failed: No such file or directory (2)
    rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
    rsync: link_stat "/Users/seifer/dev/projects/likecash/baryacard/build/ios/Debug-iphoneos/App.framework" failed: No such file or directory (2)
    rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
    Unhandled exception:
    Exception: Command "rsync -8 -av --delete --filter - .DS_Store /Users/seifer/dev/projects/likecash/baryacard/build/ios/Debug-iphoneos/App.framework /Users/seifer/dev/projects/likecash/baryacard/build/ios/Debug-iphoneos/Runner.app/Frameworks" exited with code 23
#0      Context.runSync
../…/bin/xcode_backend.dart:105
#1      Context.embedFlutterFrameworks
../…/bin/xcode_backend.dart:190
#2      Context.run
../…/bin/xcode_backend.dart:61
#3      main
../…/bin/xcode_backend.dart:17
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/seifer/dev/projects/likecash/baryacard/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'Toast' from project 'Pods')
    /Users/seifer/dev/projects/likecash/baryacard/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'FMDB' from project 'Pods')
    Result bundle written to path:
    	/var/folders/n6/pn8cjglx0qlbpzv_fqv3frmc0000gn/T/flutter_tools.FnYXJg/flutter_ios_build_temp_dirXKzhW9/temporary_xcresult_bundle
Could not build the precompiled application for the device.

Error launching application on aaaa.
Exited
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale
    en-PH)
    • Flutter version 3.0.1 at /Users/seifer/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/seifer/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • aaaa (mobile)   • 00008101-0009196C3A7A001E • ios            • iOS 15.1.1 19B81
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @SyferDev, I just tried running the counter app on my physical device (iPhone XS running iOS 15.5) and it worked just fine.  See logs below.

From your flutter doctor output, I see the device you're using is running iOS 15.1.1 but I can seem to find any support for this version in XCode. Can you try upgrading the version of iOS on your device to see if this helps?

<details>
<summary>logs</summary>

```
Launching lib/main.dart on Nexus in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        22.0s
Xcode build done.                                           32.7s
(lldb) 2022-07-01 06:58:58.697458+0000 Runner[92469:4618734] Warning: Unable to create restoration in progress marker file
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
Installing and launching...                                        41.0s
Syncing files to device Nexus...                                   231ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Nexus is available at: http://127.0.0.1:55581/Gh1WbKUWEZE=/
The Flutter DevTools debugger and profiler on Nexus is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:55581/Gh1WbKUWEZE=/

Application finished.
```
</details>

**Comment by SyferDev** [comment]
Thanks for replying @danagbemava-nc! I updated my phone to the latest iOS version (15.5), and its still giving me the same error.

**Comment by danagbemava-nc** [comment]
Hi @SyferDev, kindly upgrade to the latest version of flutter stable (3.0.4) to see if you still experience this issue. 

If you do, please provide the full output of `flutter doctor -v` as well as the complete output of `flutter run -v`. The output of `flutter run -v` may be huge, so kindly put it into a .txt file and attach it here. 

Thank you

**Comment by SyferDev** [comment]
Hello @danagbemava-nc, I updated both my flutter and Xcode and im still getting the same error.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-PH)
    • Flutter version 3.0.4 at /Users/seifer/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/seifer/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • aaaa (mobile)   • 00008101-0009196C3A7A001E • ios            • iOS 15.5 19F77
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

[run.txt](https://github.com/flutter/flutter/files/9038671/run.txt)

**Comment by danagbemava-nc** [comment]
Hi @SyferDev, can you try one last thing? Try switching to the master channel to see if you still experience this issue. 

Please provide the `flutter doctor -v` output of the `master` channel as well as the full verbose log. 

Thank you

**Comment by SyferDev** [comment]
Hello @SyferDev, switching to master broke the firebase/auth package so i tried it out on a clean project. Running the project still gives out the same error.

**flutter doctor -v**

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1503, on macOS 12.4 21F79 darwin-arm,
    locale en-PH)
    • Flutter version 3.1.0-0.0.pre.1503 on channel master at
      /Users/seifer/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d7bacf9b3f (4 hours ago), 2022-07-05 05:14:08 -0400
    • Engine revision c49de3fc08
    • Dart version 2.18.0 (build 2.18.0-254.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/seifer/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • aaaa (mobile)   • 00008101-0009196C3A7A001E • ios            • iOS 15.5
      19F77
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.4
      21F79 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google
      Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
[verbose-run.txt](https://github.com/flutter/flutter/files/9046813/run.txt)

**Comment by danagbemava-nc** [comment]
Thanks, from the logs of `master` and `stable`, the common errors I see seem to be related to code signing. 

```
Target debug_unpack_ios failed: Exception: Failed to codesign /Users/seifer/dev/projects/iostest/build/ios/Debug-iphoneos/Flutter.framework/Flutter with identity 3C8015CB972D5FC7BACB34563A0B12809C2BDFFD.
                          /Users/seifer/dev/projects/iostest/build/ios/Debug-iphoneos/Flutter.framework/Flutter: errSecInternalComponent
```

Labeling for further investigation from the team

**Comment by SyferDev** [comment]
Hello @danagbemava-nc! I finally made my test project run on a physical device. All I had to do was to delete all Apple Developer certificates in Keychain Access and let it create new ones. For some reason it had duplicate certificates and I think that was the cause of the problem. Thanks for the help!

**Comment by jmagman** [comment]
We should have the tool detect this error and instruct the user to recreate their developer certificates.

**Comment by MythologyJH** [comment]
@SyferDev 

If your physical device continues to fail, try this method.

1. Go to the keychain.
2. Delete all keys in the xcode team.
3. Reauthenticate team account in xcode.
4. flutter run

I solved it in that way.

xcode version 14.1
iphone 12 - 16.0.1
macbook m1 - 13.0(22A380)

**Comment by vgribok** [comment]
I worked around the problem by adding a new developer certificate in Xcode. I didn't need to mess with the keychain or delete any certificates.
![image](https://user-images.githubusercontent.com/757185/216383161-9a1ab08e-be3d-41a5-8a51-05af4f584ce1.png)

**Comment by danagbemava-nc** [comment]
Hi @SyferDev, let's keep this open. I don't think the tool has been updated for https://github.com/flutter/flutter/issues/106876#issuecomment-1183869558

**Comment by gotnull** [comment]
This is ridiculous. One day it deploys to a physical iOS device and then the next day it doesn't. What on Earth goes so wrong with the environment that this happens almost every single day?

Usually a flutter clean followed by a flutter build ios works but not every time. It takes a few hundred flutter cleans and then a build and maybe a shake of Xcode and then maybe something else.

It is SO inconsistent. ALL THE TIME.

It is incredible frustrating and makes the entire development experience horrible.

**Comment by jmagman** [comment]
@gotnull Please consider our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md).  Comments like "This is ridiculous" is neither courteous nor welcoming.

> One day it deploys to a physical iOS device and then the next day it doesn't. What on Earth goes so wrong with the environment that this happens almost every single day?

You can see this frustrating failure happening in Xcode without Flutter being involved at all, so it seems to be a question for Apple.  Trust me, vanilla iOS development involves lots of fighting with the keychain and missing and expired certs.  The `flutter` tool can be more helpful here with the error message, but there's really not much we can do other than direct you to fix the error in Keychain/Xcode.

**Comment by gotnull** [comment]
> You can see this frustrating failure happening in Xcode without Flutter being involved at all, so it seems to be a question for Apple.

Agreed.

**Comment by nichady** [comment]
this worked for me:

`security unlock-keychain login.keychain`
