### ISSUE TITLE
TabBarView not showing expected widgets only in release mode

### ISSUE THREAD

**Issue by varunbhalerao56** [flutter/flutter#106871]
## Steps to Reproduce
1. Build and release the APK of the app.
2. Keep opening and closing it (Fully close it and clear it from the stack)
3. You shall see that the expected results don't seem to work.

**Expected results:**
The widgets in the `TabBarView` need to be shown. 

**Actual results:**
Sometimes a blank screen is shown instead where the `TabBarView` is unresponsive (unable to swipe between the tabs).

<details>
<summary>Code sample</summary>

```dart
class CalculatorView extends StatefulWidget {
  const CalculatorView({Key? key}) : super(key: key);

  @override
  State<CalculatorView> createState() => _CalculatorViewState();
}

class _CalculatorViewState extends State<CalculatorView> {
  final List<Tab> myTabs = const [Tab(text: "Resin"), Tab(text: "Jesmonite")];

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          leading: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Image.asset(Assets.logo),
          ),
          centerTitle: true,
          elevation: 4,
          shadowColor: Colors.black.withOpacity(0.2),
          backgroundColor: backgroundColor,
          title: const Text(
            "Calculator",
            style: TextStyle(fontSize: 20, color: primaryColor, fontWeight: FontWeight.bold),
          ),
          bottom: TabBar(
            labelColor: primaryColor,
            tabs: myTabs,
          ),
          actions: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 8),
              child: IconButton(
                  onPressed: () {},
                  icon: const Icon(
                    Icons.school_rounded,
                    color: primaryColor,
                  )),
            )
          ],
        ),
        body: const TabBarView(children: [TestView(), TestView2()]),
      ),
    );
  }
}

class TestView extends StatelessWidget {
  const TestView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.amber,
    );
  }
}

class TestView2 extends StatelessWidget {
  const TestView2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.blue,
    );
  }
}


```
</details>

<details>
  <summary>Logs</summary>

**flutter run** 
Unable to run flutter since it only appears sometimes when closing and restarting the app. Never happened in a debug apk or while running from the console.

**Edit: UPDATE of flutter run --release logs**
```
I/flutter ( 7091): Null check operator used on a null value
I/flutter ( 7091): #0      _PagePosition.applyViewportDimension (package:flutter/src/widgets/page_view.dart:455)
I/flutter ( 7091): #1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1456)
I/flutter ( 7091): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #18     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545)
I/flutter ( 7091): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #22     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
I/flutter ( 7091): #23     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003)
I/flutter ( 7091): #24     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
I/flutter ( 7091): #25     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403)
I/flutter ( 7091): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #30     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376)
I/flutter ( 7091): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #65     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462)
I/flutter ( 7091): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #69     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749)
I/flutter ( 7091): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 7091): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 7091): #85     RenderView.performLayout (package:flutter/src/rendering/view.dart:165)
I/flutter ( 7091): #86     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757)
I/flutter ( 7091): #87     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887)
I/flutter ( 7091): #88     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504)
I/flutter ( 7091): #89     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892)
I/flutter ( 7091): #90     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370)
I/flutter ( 7091): #91     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
I/flutter ( 7091): #92     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083)
I/flutter ( 7091): #93     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997)
I/flutter ( 7091): #97     _invoke (dart:ui/hooks.dart:151)
I/flutter ( 7091): #98     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
I/flutter ( 7091): #99     _drawFrame (dart:ui/hooks.dart:115)
```

```
Analyzing bhoriali...                                                   
No issues found! (ran in 1.5s)
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale en-SG)
    • Flutter version 3.0.1 at /Users/skywar56/Documents/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/skywar56/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.69.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 12.3.1 21E258 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

<details>
<summary>Screenshot & Video</summary>

https://user-images.githubusercontent.com/59999892/176682810-ade2f372-510d-4c3a-a97d-43660c637f5c.mp4

![WhatsApp Image 2022-06-30 at 6 01 39 PM (2)](https://user-images.githubusercontent.com/59999892/176683284-0e9eadff-86b9-452a-9083-6e735f073888.jpeg)

![WhatsApp Image 2022-06-30 at 6 01 39 PM (1)](https://user-images.githubusercontent.com/59999892/176683302-fb24375c-ef03-46be-9184-60e65af9f3e5.jpeg)

![WhatsApp Image 2022-06-30 at 6 01 39 PM](https://user-images.githubusercontent.com/59999892/176683313-085a7f0c-ca76-4417-8b55-5266eda43211.jpeg)

</details>

**Comment by maheshmnj** [comment]
Hi @varunbhalerao56, Thanks for filing the issue. I was able to reproduce the issue in release mode on stable 3.0.3 and the beta channel, But not on the latest master channel. So I believe this issue is fixed and it should land on stable in future releases. You may verify the fix by switching to the master channel by running 
```
flutter channel master
flutter upgrade
```

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const CalculatorView(),
    );
  }
}

class CalculatorView extends StatefulWidget {
  const CalculatorView({Key? key}) : super(key: key);

  @override
  State<CalculatorView> createState() => _CalculatorViewState();
}

class _CalculatorViewState extends State<CalculatorView> {
  final List<Tab> myTabs = const [Tab(text: "Resin"), Tab(text: "Jesmonite")];

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          bottom: TabBar(
            tabs: myTabs,
          ),
          actions: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 8),
              child: IconButton(
                  onPressed: () {},
                  icon: const Icon(
                    Icons.school_rounded,
                  )),
            )
          ],
        ),
        body: const TabBarView(children: [TestView(), TestView2()]),
      ),
    );
  }
}

class TestView extends StatelessWidget {
  const TestView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.amber,
    );
  }
}

class TestView2 extends StatelessWidget {
  const TestView2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.blue,
    );
  }
}
```
</details> 

<details>
<summary>logs (stable)</summary>

```
mahesh@Maheshs-MacBook-Air-M1 sample % flutter run --release
Launching lib/main.dart on Redmi K20 Pro in release mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Running Gradle task 'assembleRelease'...                           10.9s
✓  Built build/app/outputs/flutter-apk/app-release.apk (8.4MB).

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (12914): Null check operator used on a null value
I/flutter (12914): #0      _PagePosition.applyViewportDimension (package:flutter/src/widgets/page_view.dart:455)
I/flutter (12914): #1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1456)
I/flutter (12914): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #18     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545)
I/flutter (12914): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #22     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
I/flutter (12914): #23     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003)
I/flutter (12914): #24     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
I/flutter (12914): #25     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403)
I/flutter (12914): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #30     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376)
I/flutter (12914): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #65     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462)
I/flutter (12914): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #69     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749)
I/flutter (12914): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (12914): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (12914): #85     RenderView.performLayout (package:flutter/src/rendering/view.dart:165)
I/flutter (12914): #86     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757)
I/flutter (12914): #87     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887)
I/flutter (12914): #88     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504)
I/flutter (12914): #89     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892)
I/flutter (12914): #90     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370)
I/flutter (12914): #91     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
I/flutter (12914): #92     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083)
I/flutter (12914): #93     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997)
I/flutter (12914): #97     _invoke (dart:ui/hooks.dart:151)
I/flutter (12914): #98     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
I/flutter (12914): #99     _drawFrame (dart:ui/hooks.dart:115)
I/flutter (12914): (elided 3 frames from dart:async)

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (5 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1376, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1376 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3598f20002 (9 hours ago), 2022-06-26 18:19:04 -0400
    • Engine revision ee56813c14
    • Dart version 2.18.0 (build 2.18.0-228.0.dev)
    • DevTools version 2.14.1
```
```
[✓] Flutter (Channel beta, 3.1.0-9.0.pre, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-9.0.pre at /Users/mahesh/Documents/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f28e570c8c (2 weeks ago), 2022-06-14 13:39:33 -0500
    • Engine revision 74ee6b5afd
    • Dart version 2.18.0 (build 2.18.0-165.1.beta)
    • DevTools version 2.14.0
```

</details>
