### ISSUE TITLE
Flutter Bad State: Stream has already been listened to

### ISSUE THREAD

**Issue by abhineetchandan** [flutter/flutter#106927]
## Steps to Reproduce

I am trying to use methodChannel in flutter to receive events from native Android code. But once I cancel the stream subscription I can no longer create new subscriptons even if I set the stream asBroadcastStream()

**Receiver.dart**

    static Stream<dynamic> get accessStream {
      _stream ??= _eventChannel.receiveBroadcastStream().map<dynamic>(
        (event) {
          return MainEvent.fromMap(event);
        },
      );
      return _stream!.asBroadcastStream();
    }

**When trying to call the function**
```
subs = Receiver.accessStream.listen((event) async {
          if (event != null) {
            events.add(event);
          }
        });

//After Some Time in Cancel Function
await subs.cancel()
```

It works for the first time but when I call the same function in app_listen.dart again. It gives the following error
**Logs**
```
[ +100 ms] E/flutter (32159): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: Stream has already been listened to.
[        ] E/flutter (32159): #0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
[        ] E/flutter (32159): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
[        ] E/flutter (32159): #2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
[        ] E/flutter (32159): #3      listenEvent(package:trying/util/struct/app_listen.dart:49:51)
[        ] E/flutter (32159): <asynchronous suspension>
```

**Flutter Docotor -v**
```
C:\Users\lenovo>flutter doctor -v
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1288], locale en-US)
    • Flutter version 3.0.1 at
      C:\Users\lenovo\AppData\Local\Flutter\flutter_windows_2.10.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at G:\Android\Sdk\
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = G:\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • ASUS X00TD (mobile) • J7AAGF0408905JK • android-arm64  • Android 9 (API 28)
    • Windows (desktop)   • windows         • windows-x64    • Microsoft Windows [Version 10.0.19043.1288]
    • Chrome (web)        • chrome          • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)          • edge            • web-javascript • Microsoft Edge 96.0.1054.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

I had created an issue StackOverflow at 
https://stackoverflow.com/questions/72784942/flutter-bad-state-stream-has-already-been-listened-to 
but got no response from the community, so I had to ask here.

**Comment by maheshmnj** [comment]
Hi @abhineetchandan, Thanks for filing the issue. We would need a minimal and complete code sample to investigate further. 

Thanks

**Comment by abhineetchandan** [comment]
**Listener.java**
```
package com.new.somethingnew;

import android.accessibilityservice.AccessibilityService;
import android.content.Intent;
import android.os.Build;
import android.util.Log;
import android.view.accessibility.AccessibilityEvent;

public class AccessibilityListener extends AccessibilityService {

    public static String ACCESSIBILITY_INTENT = "accessibility_event";
    public static String ACCESSIBILITY_EVENT_TYPE = "eventType";

    @Override
    protected void onServiceConnected() {}

    @Override
    public void onAccessibilityEvent(AccessibilityEvent accessibilityEvent) {
        final int eventType = accessibilityEvent.getEventType();
        Intent intent = new Intent(ACCESSIBILITY_INTENT);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            //Gets the event type
            intent.putExtra(ACCESSIBILITY_EVENT_TYPE, eventType);
        }
        sendBroadcast(intent);
    }

    @Override
    public void onInterrupt() {}
}
```

**Receiver.java**
```
package com.new.somethingnew;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;

import java.util.HashMap;

import io.flutter.plugin.common.EventChannel;

public class AccessibilityReceiver extends BroadcastReceiver {

    private EventChannel.EventSink eventSink;

    public AccessibilityReceiver(EventChannel.EventSink eventSink) {
        this.eventSink = eventSink;
    }
    @Override
    public void onReceive(Context context, Intent intent) {
            /// Send data back via the Event Sink
            HashMap<String, Object> data = new HashMap<>();
            data.put("eventType", intent.getIntExtra(AccessibilityListener.ACCESSIBILITY_EVENT_TYPE, -1));
            eventSink.success(data);
        }
    }
}
```

**MainActivity.kt**
```
package com.new.somethingnew

import android.annotation.SuppressLint
import android.app.Activity
import android.content.Intent
import android.content.IntentFilter
import android.content.pm.PackageManager
import android.content.res.Configuration
import android.os.Bundle
import android.os.PersistableBundle
import android.provider.Settings
import android.util.Log
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterActivityLaunchConfigs.BackgroundMode.transparent
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.EventChannel.EventSink
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler


class MainActivity : FlutterActivity(), EventChannel.StreamHandler, MethodCallHandler {

    private val channelTag = "com.new.somethingnew/channel"
    private val eventTag = "com.new.somethingnew/event"

    private var accessibilityReceiver: AccessibilityReceiver? = null
    private var eventChannel: EventChannel? = null
    private lateinit var methodChannel: MethodChannel
    private var mActivity: Activity? = null
    private var accessibilityListener: AccessibilityListener? = null
    private var pendingResult: MethodChannel.Result? = null
    private val requestCodeForAccessibility = 16634

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        mActivity = activity
        super.configureFlutterEngine(flutterEngine)
        methodChannel = MethodChannel(flutterEngine.dartExecutor.binaryMessenger, channelTag)
        methodChannel.setMethodCallHandler{ call, result -> onMethodCall(call, result)}
        eventChannel = EventChannel(flutterEngine.dartExecutor.binaryMessenger, eventTag)
        eventChannel!!.setStreamHandler(this)
    }

    override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        this.mActivity = activity
    }

    override fun onListen(arguments: Any?, events: EventSink?){
        if (Utils.isAccessibilitySettingsOn(context)) {
            /// Set up receiver
            val intentFilter = IntentFilter()
            intentFilter.addAction(AccessibilityListener.ACCESSIBILITY_INTENT)
            accessibilityReceiver = Receiver(events)
            context.registerReceiver(accessibilityReceiver, intentFilter)

            accessibilityListener = Listener()
            /// Set up listener intent
            val listenerIntent = Intent(context, accessibilityListener!!::class.java)
            context.startService(listenerIntent)
            Log.i("Successfully", "Started the accessibility service.")
        }
    }

    override fun onCancel(arguments: Any?) {
        context.unregisterReceiver(accessibilityReceiver)
        accessibilityReceiver = null
    }

    @SuppressLint("NewApi")
    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        pendingResult = result
        when (call.method) {
            "isAccessibilityPermissionEnabled" -> {
                result.success(Utils.isAccessibilitySettingsOn(context))
            }
            "requestAccessibilityPermission" -> {
                val intent = Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)
                mActivity!!.startActivityForResult(intent, requestCodeForAccessibility)
            }

            "returnCancelledAccessibility" -> {
                result.success(false)
            }
        }
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?){
            if (requestCode == requestCodeForAccessibility) {
                if (resultCode != RESULT_CANCELED) {
                    if (resultCode == RESULT_OK) {
                        pendingResult!!.success(true)
                    }
                } else if (resultCode == RESULT_CANCELED) {
                    methodChannel.invokeMethod("returnCancelledAccessibility", 1)
                }
            }
    }

    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
        super.onCreate(savedInstanceState, persistentState)
    }
}
```

**Service.dart**
```dart
import 'dart:async';
import 'dart:developer';
import 'dart:io';

import 'package:flutter/services.dart';

class Service {
  Service._();

  static const MethodChannel _methodeChannel =
      MethodChannel('com.somethingnew/channel');
  static const EventChannel _eventChannel =
      EventChannel('com.somethingnew/event');
  static Stream<dynamic>? _stream;

  /// stream the incoming Accessibility events
  static Stream<dynamic> get accessStream {
    if (Platform.isAndroid) {
      _stream ??= _eventChannel.receiveBroadcastStream().map<dynamic>(
        (event) {
//TODO- Flutter bad state - stream already listened to error occuring here.
          print(event["eventType"]);
        },
      );
      return _stream!.asBroadcastStream();
    }
    throw Exception("Accessibility API exclusively available on Android!");
  }

  /// request accessibility permission
  static Future<bool> requestAccessibilityPermission() async {
    try {
      bool enabled =
          await _methodeChannel.invokeMethod('requestAccessibilityPermission');
      FlutterAccessibilityService.accessStream.listen((event) {});
      return enabled;
    } on PlatformException catch (error) {
      log("$error");
      return Future.value(false);
    }
  }

  /// check if accessibility permission is enabled
  static Future<bool> isAccessibilityPermissionEnabled() async {
    try {
      return await _methodeChannel
          .invokeMethod('isAccessibilityPermissionEnabled');
    } on PlatformException catch (error) {
      log("$error");
      return false;
    }
  }
}
```

**When the accessStream function is called first time then it gives the output but the second time it generates the error.**

**Comment by abhineetchandan** [comment]
@maheshmnj any response?

**Comment by maheshmnj** [comment]
@abhineetchandan The `main.dart` or some entry point is missing. I wouldn't be able to investigate from the available code. Could you please share a minimal and complete sample project rather than sharing the independent classes? Also if you can eliminate and further reduce the code to minimal sample code that would be great.

Thanks

**Comment by abhineetchandan** [comment]
@maheshmnj I have solved it. Just removed the ?? in accessStream function of service.dart. Thanks for you response. Now I'm closing the issue.
