### ISSUE TITLE
[add-to-app] multi-engine loading assets throws exception when loading assets after hot restarting when using flutter attach

### ISSUE THREAD

**Issue by impeiwei** [flutter/flutter#107091]
## Steps to Reproduce

source code:   https://github.com/impeiwei/flutter-samples/tree/main-assets-attach/add_to_app/multiple_flutters 

1.  open Multiple Flutter Apps   
2. Run the android module
3. exec `flutter attach`  in Android Studio  IDE attach icon
4.  run  `hot restart`  when at FlutterActivity
5.  asset images  load exception

https://user-images.githubusercontent.com/55788007/177273227-df812545-5d24-42e0-920b-a81da4d8050c.mp4

## Logs

<details>
<summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown while resolving an image:
Unable to load asset: AssetManifest.json

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:72:27)
<asynchronous suspension>

Image provider: ScrollAwareImageProvider<Object>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#b9419(), devicePixelRatio: 2.8,
  locale: en_US, textDirection: TextDirection.ltr, size: Size(100.0, 100.0), platform: android)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
we found in flutter 2.10.5  and also found at Flutter 3.1.0-0.0.pre.1467

Flutter 3.1.0-0.0.pre.1467 • channel main • https://github.com/flutter/flutter.git
Framework • revision 64a73a7a5f (4 days ago) • 2022-06-30 22:19:08 -0400
Engine • revision b9547182c3
Tools • Dart 2.18.0 (build 2.18.0-241.0.dev) • DevTools 2.14.1
```

</details>

**Comment by impeiwei** [comment]
Uploading flutter-attach.mp4…

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master` only on android using the code sample and steps provided above.

Code sample has been zipped and attached below for easy access. 


[code sample](https://github.com/flutter/flutter/files/9045172/impeiwei.flutter-samples.main-assets-attach.add_to_app-multiple_flutters.zip)


[android studio logs.log](https://github.com/flutter/flutter/files/9045183/as_logs.log)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.0.4 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (5 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 Pro Max (mobile)  • FD5949EA-E739-4960-9E9D-16F3DE69816E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1502, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1502 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 363b0f1050 (6 hours ago), 2022-07-04 23:14:07 -0400
    • Engine revision 69901542b7
    • Dart version 2.18.0 (build 2.18.0-254.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 Pro Max (mobile)  • FD5949EA-E739-4960-9E9D-16F3DE69816E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by ColdPaleLight** [comment]
Closing it by linked PR
