### ISSUE TITLE
Android Crash - io.flutter.embedding.android.FlutterActivity.onStart

### ISSUE THREAD

**Issue by carman247** [flutter/flutter#107095]
Started happening with the last two builds of our app. The stack trace seems to vary slightly depending on device/os version

### Stack Trace
```console
Fatal Exception: java.lang.NoSuchMethodError: No virtual method a(Landroid/app/Activity;)V in class Landroidx/core/app/h; or its super classes (declaration of 'androidx.core.app.h' appears in /data/app/~~RmoIH6vrzylGYyOYEBuoXg==/androidx.test.tools.crawler-ATFFqrJ3qWJP4A8TA5V_kA==/base.apk)
       at com.google.firebase.perf.application.AppStateMonitor.onActivityStarted(AppStateMonitor.java:17)
       at android.app.Application.dispatchActivityStarted(Application.java:406)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1348)
       at android.app.Activity.onStart(Activity.java:1833)
       at io.flutter.embedding.android.FlutterActivity.onStart(FlutterActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:2)
       at android.app.Activity.performStart(Activity.java:8018)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Flutter Doctor
```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.3 at /Users/chris/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/chris/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • Mi 9T Pro (mobile) • 94b9d1dc • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 103.0.5060.53

• No issues found!
```

**Comment by huycozy** [comment]
Hi @carman247, 
Did you take the above stack trace from analytic tools such as Firebase Crashlytic? Or did it come from local run/build output?
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
And you are using the old Flutter version, the latest Flutter stable is `3.0.4` and the master is `3.1.0-0.0.pre.1501`. Please try upgrading them and retry to see if this issue still reproduces.

**Comment by carman247** [comment]
Hi @huycozy thanks for the reply. I think it's going to quite difficult for me to provide a minimal reproducible code sample, or even reproduce the error myself - the error is happening in the wild so to speak. Also, although upgrading Flutter sounds like fun, I maintain quite a few apps and I worry that upgrading only to fix this new error may cause even more problems. 

Thankfully there hasn't been any new logs of this error since 04/07/2022. It seems very strange as it has only started occurring after minor UI updates to the app.

### Android versions affected
- 8
- 8.1
- 9
- 10
- 11
- 12

### Devices affected
- Samsung Galaxy S8, S9, S20
- Google Pixel 5, 6
- Fujitsu F-01L
- AQUOS Sense 2

**Comment by huycozy** [comment]
Hi @carman247
We need more information to be able to conclude the issue. Try to provide more information so that we can continue investigating the issue, such as Android files: `pubspec.yaml`, `android/gradle.properties`, `build.gradle` (app and project level), etc.
Also, the issue may not happen on the new Flutter versions. So please try to upgrade it and see if the issue still reproduces.

**Comment by carman247** [comment]
Hi @huycozy 

The error no longer seems to be occurring currently and so I will close this issue. If there are further problems in future I will open a new issue and provide more info.
