### ISSUE TITLE
PageView throwing Exception for the first launch

### ISSUE THREAD

**Issue by reytum** [flutter/flutter#107133]
## Details
I am using PageView in my App to create Carousel of images. I am using the flutter View inside android recycler view cells for banners. The issue is for the first few seconds, the PageView shows blank white cell. When I checked the flutter logs, i was getting a crash. 

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was:
  PageView
  PageView:file:///Users/reytum/Documents/Flutter/FlutterTest/bb_flutter/lib/cell.dart:118:24

When the exception was thrown, this was the stack:
#0      _PagePosition.applyViewportDimension (package:flutter/src/widgets/page_view.dart:455:25)
#1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1456:16)
#2      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#18     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#22     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#23     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003:7)
#24     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#25     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#30     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#65     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462:13)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#69     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749:15)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#78     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#88     RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#89     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#90     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#91     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#92     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#93     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#94     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#95     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#96     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#100    _invoke (dart:ui/hooks.dart:151:10)
#101    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#102    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
```

**Target Platform: Flutter**
**Target OS version/browser: Android**
**Devices: Emulator**

## Logs

Below is my code:

```
class Cell extends StatefulWidget {
  const Cell({Key? key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => _CellState();
}

class _CellState extends State<Cell> with WidgetsBindingObserver {
  int cellNumber = 0;
  String cellText = "";
  int clickCounter = 0;
  Random? _random;
  AppLifecycleState? appLifecycleState;
  List<Widget> imageSliders = List.empty();
  List<CachedNetworkImageProvider> imageProviders = List.empty(growable: true);
  List<Map<String, dynamic>> sectionData = List.empty(growable: true);

  //final CarouselController _controller = CarouselController();
  final PageController _pageController = PageController(viewportFraction: 0.99);
  int _currentPage = 0;

  @override
  void initState() {
    const channel = MethodChannel('my_cell');
    channel.setMethodCallHandler((call) async {
      if (call.method == 'setCellData') {
        setState(() {
          //cellNumber = call.arguments as int;
          List<Object?> sectionDataRaw = call.arguments as List<Object?>;
          for (var element in sectionDataRaw) {
            if (element != null) {
              sectionData.add(HashMap<String, dynamic>.from(
                  json.decode(jsonEncode(element))));
            }
          }
          _random = Random(cellNumber);

          if (imageSliders.isNotEmpty) {
            imageSliders.clear();
          }

          if (imageProviders.isNotEmpty) {
            imageProviders.clear();
          }

          imageSliders = sectionData
              .map((item) => InkWell(
                  onTap: () {
                    dev.log("Clicked item: $item");
                    channel.invokeMethod("onBannerClick", item);
                  },
                  child: CachedNetworkImage(
                    imageUrl: item["image"] as String,
                    imageBuilder: (context, imageProvider) => Container(
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: imageProvider,
                          fit: BoxFit.fill,
                        ),
                      ),
                    ),
                    errorWidget: (context, url, error) =>
                        const Icon(Icons.error),
                  )))
              .toList();
        });
      }
    });
    // Keep track of what the current platform lifecycle state is.
    WidgetsBinding.instance.addObserver(this);
    super.initState();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    setState(() {
      appLifecycleState = state;
    });
  }

  // Show a random bright color.
  Color randomLightColor() {
    _random ??= Random(cellNumber);

    return Color.fromARGB(255, _random!.nextInt(50) + 205,
        _random!.nextInt(50) + 205, _random!.nextInt(50) + 205);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // The Flutter cells will be noticeably different (due to background color
      // and the Flutter logo). The banner breaks immersion.
      debugShowCheckedModeBanner: true,
      home: Scaffold(
        backgroundColor: Colors.white,
        body: PageView.builder(
            controller: _pageController,
            scrollDirection: Axis.horizontal,
            itemCount: imageSliders.length,
            onPageChanged: (page) {
              print("Called on page: $page");
              setState(() {
                _currentPage = page;
              });
            },
            itemBuilder: (_, index) {
              return SizedBox(
                  width: 240.0, height: 240.0, child: imageSliders[index]);
            }),
      ),
    );
  }
```

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @reytum, this issue was reported in https://github.com/flutter/flutter/issues/101007 and has since been fixed by https://github.com/flutter/flutter/pull/104405. 

Kindly upgrade to the master channel to see whether or not you still experience this issue. 

If you do, kindly provide the `flutter doctor -v` of the master channel as well as  a **complete minimal reproducible code sample** so that we can investigate this. 

Thank you

**Comment by reytum** [comment]
Thanks @danagbemava-nc. I am not seeing the crash on the master channel.  Is there any ETA for this fix to be on stable channel?

For any one looking to fix this, here are the steps:
1. flutter channel master
2. flutter upgrade
3. flutter pub get

Then run your app.

**Comment by danagbemava-nc** [comment]
> Is there any ETA for this fix to be on stable channel?

Unfortunately, I do not have that information.

> I am not seeing the crash on the master channel

Thanks for confirming that it has been fixed. 

Per our triage policy, I'll be closing this issue as it has already been fixed on the master channel. 

Thank you

**Comment by bleroux** [comment]
@reytum
In the meanwhile, there is a small hack to avoid this issue : add a small delay before calling runApp().

```dart
void main() async {
  await Future.delayed(const Duration(milliseconds: 200));
  runApp(const MyApp());
}
```
