### ISSUE TITLE
SocketException Error: SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64), address = login.parker.com, port = 443

### ISSUE THREAD

**Issue by sitakanta136** [flutter/flutter#107107]
Case 1:  First Time connect with public wifi
Successfuly login :

 ** Connectivity -result = [InternetAddress('142.250.183.206', IPv4), InternetAddress('2404:6800:4009:80f::200e', IPv6)]
[log]  ** Connectivity - internetAddress= 142.250.183.206
[log]  ** Connectivity - Mobile network - Online

Case 2 : Connect Gateway(IOT Device)
 Connectivity - Mobile network - Offline
Error- SocketException: Failed host lookup: 'google.com' (OS Error: No address associated with hostname, errno = 7)
[log]  Socket connection error in Internet Check

Case 3: again connect with public wifi
>  succesfully Login ** Connectivity -result = [InternetAddress('216.58.203.46', IPv4), InternetAddress('2404:6800:4009:80d::200e', IPv6)]
[log]  ** Connectivity - internetAddress= 216.58.203.46
[log]  ** Connectivity - Mobile network - Online

Case 4: scan nearby gw=> connect to Gateway(IOT Device)=> disconnect Gateway (IOT Device) Wi-Fi  => Connect Public Wi-Fi
** Connectivity -result = [InternetAddress('2404:6800:4009:80f::200e', IPv6), InternetAddress('142.250.183.206', IPv4)]
[log]  ** Connectivity - internetAddress= 2404:6800:4009:80f::200e
[log]  ** Connectivity - Mobile network - Online

but http.post() method returned exception
 ** SocketException Error: SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64), address = login.parker.com, port = 443
 [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64), address = login.parker.com, port = 443
E/flutter (15591): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
E/flutter (15591): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
E/flutter (15591): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
E/flutter (15591): #3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299:22)
E/flutter (15591): #4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
E/flutter (15591): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2449:26)
E/flutter (15591): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2867:12)
E/flutter (15591): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2872:12)
E/flutter (15591): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2727:12)
 IOClient.send
package:http/src/io_client.dart:35
E/flutter (15591): #11     BaseClient._sendUnstreamed
package:http/src/base_client.dart:93
E/flutter (15591): #12     BaseClient.post
package:http/src/base_client.dart:32
E/flutter (15591): #13     _LoginView.authenticateLoginPage
package:mobileiot_service_tool/…/login/login_view.dart:362
E/flutter (15591): #14     _LoginView.signInClickEven

Please help me to resolve this issue. it's a blocker in the client App

**Comment by sitakanta136** [comment]
If I killed the app and start it again, Login worked fine.

**Comment by exaby73** [comment]
Hi @sitakanta136, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by sitakanta136** [comment]
Sir Ji,
Login functionality not working, After ssh connection using flutter (using ssh2 plugin).
I/flutter (32252): ⛔  LoginView : ** SocketException Error: SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64), address = 
login.parker.com, port = 443

Login Code:
 Future<void> authenticateLoginPage(String userName, String password,
      BuildContext context, String userType) async {
    final String loginApiURL = Environment().config.loginApi;
    final String authVal = Environment().config.authorization;
    final uri = Uri.parse(loginApiURL);

    final headers = {
      'content-type': 'application/x-www-form-urlencoded',
      'accept': '*/*',
      'authorization': authVal,
      "cache-control": "no-cache"
    };

    Map<String, String> body = {
      'grant_type': 'password',
      'scope': 'openid',
      'username': userName,
      'password': password,
    };

    //String jsonBody = json.encode(body);
    //String formBody = Uri.encodeQueryComponent(jsonBody);

    try {
      if (client != null) {
        client.close();
      }

      client = new http.Client();
      final response = await client.post(uri, headers: headers, body: body);
      if (response.statusCode == 200) {
        log.i('Login Successfully');
        StoreLogs.setLog(
            "LoginPage", "authenticateLoginPage()", 'Login Successfuly');
        Map<String, dynamic> _map = jsonDecode(response.body);
        String value = _map["access_token"];
        //store UserTpe
        PreferenceUtils.setString(StringConstants.accessToken, value);
        _isLoding(false);
        if (userType == StringConstants.registerUser) {
          _showToast(context, StringConstants.loginSuccessfulMsg);
        }
        Future.delayed(const Duration(seconds: 1), () {
          Navigator.of(context).pushReplacementNamed('/auth');
        });
      } else {
        _isLoding(false);
        _showToast(context, StringConstants.invalidCredMsg);
      }
    } on SocketException catch (e) {
      _isLoding(false);
      log.e('** SocketException Error: $e');
      _showToast(context, "SocketException Machine is not on the network ");
      rethrow;
    } on Error catch (e) {
      _isLoding(false);
      _showToast(context, "Please check Internet Connection.");

      StoreLogs.setLog(
          "LoginPage", "authenticateLoginPage()", 'lOGIN Error: $e');
      log.e('** lOGIN Error: $e');
    }
  }

InternerAdress change to
 Connectivity -result = [InternetAddress('2404:6800:4009:80f::200e', IPv6), InternetAddress('216.58.203.46', IPv4)]

The issue occurs, after an ssh connection using ssh2 flutter. Please help me.

**Comment by exaby73** [comment]
If this error is occurring only when using this plugin, I think it's best to raise this issue on their [issue tracker](https://github.com/jda258/flutter_ssh2/issues). Since this is not a bug in Flutter, I am closing this issue.
