### ISSUE TITLE
Flutter Google Play Release Error

### ISSUE THREAD

**Issue by yasburg** [flutter/flutter#107288]
My app works fine on a local emulator but when I tried to release it on google play, I received the following two crash reports:
I put both errors because I don't know if they are related to each other.
(This only happens on google virtual machines so I don't know how to reproduce it.)

Error 1
![image](https://user-images.githubusercontent.com/34233254/177878423-34f77f49-2340-4d39-8dd3-225b5c9d4ba4.png)

Error 2
![image](https://user-images.githubusercontent.com/34233254/177880756-d505456c-602d-4613-bb72-e710f8488322.png)

Error 1
```
FATAL EXCEPTION: main
Process: com.company.name, PID: 21699
java.lang.VerifyError: Superclass androidx.core.app.f of androidx.activity.ComponentActivity is declared final (declaration of 'androidx.activity.ComponentActivity' appears in /data/app/~~Dura1domJxadyzOLcFBeCg==/com.company.name-uKPGlMIJl80xn9wZBHj-DA==/base.apk)
	at com.google.firebase.auth.internal.l0.b(Unknown Source:0)
	at com.google.firebase.auth.FirebaseAuth.<init>(Unknown Source:22)
	at com.google.firebase.auth.internal.b1.<init>(Unknown Source:0)
	at com.google.firebase.auth.FirebaseAuthRegistrar.lambda$getComponents$0(Unknown Source:16)
	at com.google.firebase.auth.x1.a(Unknown Source:0)
	at com.google.firebase.components.s.k(Unknown Source:9)
	at com.google.firebase.components.s.l(Unknown Source:0)
	at com.google.firebase.components.d.get(Unknown Source:4)
	at com.google.firebase.components.z.get(Unknown Source:13)
	at com.google.firebase.components.s.h(Unknown Source:46)
	at com.google.firebase.components.s.i(Unknown Source:23)
	at com.google.firebase.i.r(Unknown Source:72)
	at com.google.firebase.i.u(Unknown Source:71)
	at com.google.firebase.i.t(Unknown Source:2)
	at com.google.firebase.i.s(Unknown Source:35)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source:4)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:3)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7246)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6787)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
Error 2
```
FATAL EXCEPTION: main
Process: com.company.name, PID: 19614
java.lang.VerifyError: Superclass androidx.core.app.f of androidx.activity.ComponentActivity is declared final (declaration of 'androidx.activity.ComponentActivity' appears in /data/app/~~SZJrYjd84x9CmselkA3gtA==/com.company.name-DTkoJ0eSx8NC7zjcQhJVbQ==/base.apk)
	at com.google.android.gms.common.e.m(Unknown Source:0)
	at com.google.android.gms.common.api.internal.f.y(Unknown Source:21)
	at com.google.android.gms.common.api.e.<init>(Unknown Source:78)
	at com.google.android.gms.common.api.e.<init>(Unknown Source:6)
	at com.google.android.gms.common.api.e.<init>(Unknown Source:12)
	at com.google.android.gms.auth.api.signin.b.<init>(Unknown Source:7)
	at com.google.android.gms.auth.api.signin.a.a(Unknown Source:7)
	at io.flutter.plugins.b.c$a.q(Unknown Source:163)
	at io.flutter.plugins.b.c.onMethodCall(Unknown Source:228)
	at g.a.d.a.k$a.a(Unknown Source:17)
	at io.flutter.embedding.engine.f.e.k(Unknown Source:18)
	at io.flutter.embedding.engine.f.e.l(Unknown Source:20)
	at io.flutter.embedding.engine.f.e.m(Unknown Source:0)
	at io.flutter.embedding.engine.f.c.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Here is app\build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion flutter.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.company.name"
        minSdkVersion 23
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
//            multiDexKeepFile file('multidex-config.txt')
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    implementation platform('com.google.firebase:firebase-bom:30.2.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'com.google.firebase:firebase-firestore'
}
```

android\build.gradle

```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.13'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

gradle.properties

```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
```

Flutter firebase packages and versions

```
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  firebase_database: ^9.0.18
  cloud_firestore: ^3.2.1
  firebase_storage: ^10.3.1
```

AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.company.name">
    <uses-permission android:name="android.permission.INTERNET"/>
   <application
        android:label="CompanyName"
        android:name="androidx.multidex.MultiDexApplication"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            ...
```

**Comment by darshankawar** [comment]
@yasburg 
This seems to be originally being tracked here, so I suggest you to follow-up in it for further updates, as this doesn't seem to be flutter specific https://issuetracker.google.com/issues/237785592

Closing from here.
