### ISSUE TITLE
[camera] Nullpointer exception on cameraController initialization function

### ISSUE THREAD

**Issue by yurtemre7** [flutter/flutter#107237]
## Steps to Reproduce

0. Have a Pixel 6 with the Android 13 (API 33) Beta from June 5th 2022
1. Camera Plugin and a regular Flutter App with the CameraPreview Widget
2. Initialize cameraController e.g. in initState
3. Camera Plugin raised nullpointer exception and CameraPreview shows nothing

**Expected results:** 
CameraPreview shows an actual preview

**Actual results:** 
No image output

<details>
<summary>Code sample</summary>

```dart
selectCamera() async {
    if (appmelder.cameras.isEmpty) {
      return null;
    }
    var controller = CameraController(
      appmelder.cameras[0],
      ResolutionPreset.veryHigh,
      enableAudio: false,
      imageFormatGroup: ImageFormatGroup.jpeg,
    );

    try {
      await controller.initialize(); // <-- here is the error 
    } on CameraException catch (e) { 
      // catch it because it can throw it :)
      log('Error: $e');
      setState(() {
        hasError = true;
      });
    }

    return controller;
  }
```
</details>

<details>
  <summary>Logs</summary>

```
D/CompatibilityChangeReporter(25675): Compat change id reported: 206033068; UID 10738; state: ENABLED
E/MethodChannel#plugins.flutter.io/camera_android(25675): Failed to handle method call
// HERE IS THE IMPORTANT PART
E/MethodChannel#plugins.flutter.io/camera_android(25675): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference 
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.features.resolution.ResolutionFeature.configureResolution(ResolutionFeature.java:244)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.features.resolution.ResolutionFeature.<init>(ResolutionFeature.java:50)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.features.CameraFeatureFactoryImpl.createResolutionFeature(CameraFeatureFactoryImpl.java:58)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.features.CameraFeatures.init(CameraFeatures.java:71)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.Camera.<init>(Camera.java:217)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:386)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$io-flutter-plugins-camera-MethodCallHandlerImpl(MethodCallHandlerImpl.java:81)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.MethodCallHandlerImpl$$ExternalSyntheticLambda0.onResult(Unknown Source:6)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:53)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:74)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at android.app.ActivityThread.main(ActivityThread.java:7929)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#plugins.flutter.io/camera_android(25675): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

```
flutter doctor -v
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\emrey\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (5 available)
    • Pixel 6 (mobile)             • 192.168.2.112:39729 • android-arm64  • Android 13 (API 33)
    • sdk gphone64 x86 64 (mobile) • emulator-5554       • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows             • windows-x64    • Microsoft Windows [Version 10.0.22000.778]
    • Chrome (web)                 • chrome              • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)                   • edge                • web-javascript • Microsoft Edge 103.0.1264.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by exaby73** [comment]
Hello @yurtemre7. Could you edit your code to include the entire `main.dart` file as described by [this](https://stackoverflow.com/help/minimal-reproducible-example)? Also, please post your entire `flutter doctor -v` output, which includes the version of Flutter you are running. Finally, posting the output to `flutter run -v` would also be helpful.

**Comment by yurtemre7** [comment]
All fine, my problem was stupid. It was caused when I have set the 
![image](https://user-images.githubusercontent.com/28185198/177977591-c6878993-b35c-4ee4-beea-3a9688b6a669.png)
targetSdkVersion to 33 the camera plugin would get an error. Maybe relevant for the next android version ?
But we can close this because its working as intended now. Human error all along.

**Comment by exaby73** [comment]
@yurtemre7 Thanks for this feedback. Usually, you'd need to keep the target version greater or equal to the device version you're running it on. It might not be specific to just the camera plugin. But thanks for posting the solution
