### ISSUE TITLE
Error when enabling web | macos on an existing flutter codelab application ("Null check operator used on a null value".)

### ISSUE THREAD

**Issue by manshilk** [flutter/flutter#107299]
Steps to reproduce:

- git clone https://github.com/material-components/material-components-flutter-codelabs.git
- cd material-components-flutter-codelabs/mdc_100_series
- git checkout 101-starter

- Enable web or macos for this project.

flutter create --platforms web .

## exception

_CastError: Null check operator used on a null value

```
#0      _validateMetadataMap (package:flutter_tools/src/flutter_project_metadata.dart:58:33)
#1      new FlutterProjectMetadata (package:flutter_tools/src/flutter_project_metadata.dart:99:11)
#2      CreateBase.determineTemplateType (package:flutter_tools/src/commands/create_base.dart:221:9)
#3      CreateCommand._getProjectType (package:flutter_tools/src/commands/create.dart:170:29)
#4      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:210:41)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1342:12)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-ZA)
    • Flutter version 3.0.3 at /Users/manshilkanhai/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (2 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/manshilkanhai/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment]
@manshilk 

This issue was initially reported in https://github.com/flutter/flutter/issues/104021 and has since been fixed by https://github.com/flutter/flutter/pull/104022.

The fix is available on the beta and master channels, so you will need to switch to latest beta or master channel and try again to see the fix.

Per our triage policy, I'll be closing this as it has already been fixed on the master channel.

If you run into this issue on either the beta channel or master channel, write in comments and I'll reopen it.
