### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: Operation did not complete successfully because the file contains a virus or potentially unwanted software., errno = 225

### ISSUE THREAD

**Issue by saurabhjadhavv** [flutter/flutter#107245]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
, errno = 225
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:23:16)
#3      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:323:24)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:322:5)
#6      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:483:13)
<asynchronous suspension>
#7      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#8      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:109:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22621.160], locale en-IN)
    • Flutter version 3.0.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (7 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.34)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.28307.1440
    • Windows 10 SDK version 10.0.17763.0
    ✗ Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.68.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version
      10.0.22621.160]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 103.0.5060.66
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 103.0.1264.37

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
cloud_firestore-3.1.8
cloud_firestore_web-2.6.8
connectivity_plus-2.2.1
connectivity_plus_linux-1.3.0
connectivity_plus_macos-1.2.1
connectivity_plus_web-1.2.0
connectivity_plus_windows-1.2.0
firebase_core-1.12.0
firebase_core_web-1.5.4
google_mobile_ads-1.1.0
share_plus-3.0.4
share_plus_macos-2.0.2
share_plus_web-2.0.4
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.6
url_launcher_windows-3.0.0

**Comment by huycozy** [comment]
Hi @saurabhjadhavv, thanks for filing the issue. 
I see there's an open issue addressing the case you described #61997
Closing as a duplication, so please follow up on it for further updates.
