### ISSUE TITLE
Unable to install release mode on some phones

### ISSUE THREAD

**Issue by gaetan1903** [flutter/flutter#107251]
## Steps to Reproduce

1. Execute `flutter run build apk` on the code sample 
2. Install the release in phone

**Expected results:** Success Installation

**Actual results:** 
![lutter_issue](https://user-images.githubusercontent.com/43904633/177835670-da59bf2e-b448-42c5-a514-252d174d5aec.jpg)

On many phone, it works, but with this phone, same model, it can't install, 

However this phone have Android 10 version. 
<img src="https://user-images.githubusercontent.com/43904633/177836024-7ffb7934-7f7e-450e-b931-3dc6f277257b.jpg" width ="300"> 

I can't have a flutter doctor, cause it's a release mode, 

The architecture of this phone is not supported ?

**Comment by maheshmnj** [comment]
Hi @gaetan1903, Thanks for filing the issue. please share the output of `flutter doctor -v`  which helps us understand the version of flutter you are using.

**Comment by gaetan1903** [comment]
```
[✓] Flutter (Channel stable, 2.10.4, on Arch Linux 5.18.7-arch1-1, locale fr_FR.UTF-8)
    • Flutter version 2.10.4 at /home/gaetan1903/environnements/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (il y a 4 mois), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/gaetan1903/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/gaetan1903/environnements/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.2
    • ninja version 1.11.0
    • pkg-config version 1.8.0

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/gaetan1903/environnements/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • Redmi Note 9 Pro Max (mobile) • 213b45b0 • android-arm64  • Android 11 (API 30)
    • Linux (desktop)               • linux    • linux-x64      • Arch Linux 5.18.7-arch1-1
    • Chrome (web)                  • chrome   • web-javascript • Chromium 103.0.5060.53 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The phone is not mine, but i can't test it in debug mode, I will try to find the same model to try it

**Comment by maheshmnj** [comment]
Thanks for the update @gaetan1903, Since you are using an older version of flutter, I would suggest upgrading to latest stable release and try to install the app on the reproducible device in both debug and release mode.

**Comment by gaetan1903** [comment]
Another device with the same problem 

`flutter run -v` give this 

```
        ... 
        ] executing: /home/gaetan1903/Android/Sdk/platform-tools/adb -s 283064c8 shell am force-stop com.iteams.bjj_library
[  +73 ms] executing: /home/gaetan1903/Android/Sdk/platform-tools/adb -s 283064c8 shell pm list packages com.iteams.bjj_library
[  +69 ms] Installing APK.
[   +1 ms] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /home/gaetan1903/Android/Sdk/platform-tools/adb -s 283064c8 install -t -r
/home/gaetan1903/Dev/BJJ-Library/build/app/outputs/flutter-apk/app.apk
[+3273 ms] Performing Streamed Install

                    adb: failed to install /home/gaetan1903/Dev/BJJ-Library/build/app/outputs/flutter-apk/app.apk: Failure
                    [INSTALL_FAILED_USER_RESTRICTED: Invalid apk]
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 3,3s)
[   +1 ms] Error: ADB exited with exit code 1
[        ] Performing Streamed Install
           
           adb: failed to install /home/gaetan1903/Dev/BJJ-Library/build/app/outputs/flutter-apk/app.apk: Failure [INSTALL_FAILED_USER_RESTRICTED:
Invalid apk]
[        ] Warning: Failed to install APK.
[   +1 ms] Error launching application on M2102J20SG.
[   +8 ms] "flutter run" took 42 341ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +253 ms] ensureAnalyticsSent: 251ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```



`flutter doctor -v` give this 

```

flutter doctor -v
[✓] Flutter (Channel stable, 3.0.4, on Arch Linux 5.18.7-arch1-1, locale fr_FR.UTF-8)
    • Flutter version 3.0.4 at /home/gaetan1903/environnements/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (il y a 9 jours), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/gaetan1903/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/gaetan1903/environnements/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.2
    • ninja version 1.11.0
    • pkg-config version 1.8.0

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/gaetan1903/environnements/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • M2102J20SG (mobile) • 283064c8 • android-arm64  • Android 12 (API 31)
    • Linux (desktop)     • linux    • linux-x64      • Arch Linux 5.18.7-arch1-1
    • Chrome (web)        • chrome   • web-javascript • Chromium 103.0.5060.53 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by maheshmnj** [comment]
Thanks for the info @gaetan1903, `INSTALL_FAILED_USER_RESTRICTED` generally happens when the device blocks the installation.  Could you please try the following

1. connect the reproducible device 
2. execute `sudo adb shell`
3. execute `pm uninstall <package name>`. /// e.g `pm uninstall com.mypackage.name`
4. try installing the release apk and ensure in your phone settings the device allows installation from another source.

**Comment by gaetan1903** [comment]
Failure [INSTALL_FAILED_USER_RESTRICTED: Invalid apk]
 
same error

**Comment by maheshmnj** [comment]
@gaetan1903 Are both the devices you tested Xiaomi phones? if yes then please try the following answer https://stackoverflow.com/a/71939786/8253662 and see if it helps.

Is this issue only when installing on a physical device or a emulator too? please share the physical device names where it fails to install and the android version.
