### ISSUE TITLE
[tool_crash] _CastError: (#0      _validateMetadataMap (package:flutter_tools/src/flutter_project_metadata.dart:58:33))

### ISSUE THREAD

**Issue by zhangjian78** [flutter/flutter#107247]
## Command
```
flutter create mdc_100_series
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      _validateMetadataMap (package:flutter_tools/src/flutter_project_metadata.dart:58:33))
```
#0      _validateMetadataMap (package:flutter_tools/src/flutter_project_metadata.dart:58:33)
#1      new FlutterProjectMetadata (package:flutter_tools/src/flutter_project_metadata.dart:99:11)
#2      CreateBase.determineTemplateType (package:flutter_tools/src/commands/create_base.dart:221:9)
#3      CreateCommand._getProjectType (package:flutter_tools/src/commands/create.dart:170:29)
#4      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:210:41)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1342:12)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.3, on Microsoft Windows [版本 10.0.19043.1766], locale zh-CN)
    • Flutter version 3.0.3 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (2 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code, 64-bit edition (version 1.68.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19043.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.44

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment]
Hi @zhangjian78, this issue was initially reported in https://github.com/flutter/flutter/issues/104021 and has since been fixed by https://github.com/flutter/flutter/pull/104022.

The fix is available on the `beta` and `master` channels. 

Per our triage policy, I'll be closing this as it has already been fixed on the `master` channel. 

If you run into this issue on either the beta channel or master channel, kindly file a new issue. 

Thank you
