### ISSUE TITLE
[image_picker] Support `pickMultiImage` on web

### ISSUE THREAD

**Issue by SnowZero** [flutter/flutter#107391]
I need upload images on the web, 
I have to use ``image_picker_for_web``, but no work when Debug Chrome.
only happens when using pickMultiImage.

``  image_picker: ^0.8.5+3``

<details>
<summary>Code sample</summary>

```dart

import 'package:image_picker_for_web/image_picker_for_web.dart' as webPicket;
import 'package:image_picker/image_picker.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var viewList = new List<int>.generate(100, (i) => i + 1);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: TextButton(
        onPressed: () async {
          _uploadAction();
        },
        child: Text('Button'),
      ),
    );
  }

  _uploadAction() async {
    var getImage = await webPicket.ImagePickerPlugin().pickMultiImage();
  }
}
```

</details>

<details>
  <summary> flutter doctor </summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm (Rosetta), locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.69.0)
Scanning for devices is taking a long time...[✓] Connected device (8 available)
[✓] HTTP Host Availability


```

</details>

<details>
  <summary>Debug Console</summary>

```
Error: UnimplementedError: pickMultiImage() has not been implemented.
    at Object.throw_ [as throw] (http://localhost:49603/dart_sdk.js:5080:11)
at image_picker_for_web.ImagePickerPlugin.new.pickMultiImage (http://localhost:49603/packages/image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart.lib.js:122:17)
at _uploadAction (http://localhost:49603/packages/flutter_test_web_keyboard/main.dart.lib.js:300:80)
    at _uploadAction.next (<anonymous>)
    at runBody (http://localhost:49603/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:49603/dart_sdk.js:40691:7)
at [_uploadAction] (http://localhost:49603/packages/flutter_test_web_keyboard/main.dart.lib.js:299:20)
at main._MyHomePageState.new.<anonymous> (http://localhost:49603/packages/flutter_test_web_keyboard/main.dart.lib.js:295:38)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:49603/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:49603/dart_sdk.js:40691:7)
at http://localhost:49603/packages/flutter_test_web_keyboard/main.dart.lib.js:294:420
at [_handleTap] (http://localhost:49603/packages/flutter/src/material/icon_button.dart.lib.js:42247:31)
at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:49603/packages/flutter/src/gestures/recognizer.dart.lib.js:198:18)
at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:49603/packages/flutter/src/gestures/tap.dart.lib.js:411:42)
at [_checkUp] (http://localhost:49603/packages/flutter/src/gestures/tap.dart.lib.js:217:12)
at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:49603/packages/flutter/src/gestures/tap.dart.lib.js:166:23)
at tap.TapGestureRecognizer.new.handleEvent (http://localhost:49603/packages/flutter/src/gestures/recognizer.dart.lib.js:444:16)
at [_dispatch] (http://localhost:49603/packages/flutter/src/gestures/pointer_router.dart.lib.js:86:9)
at http://localhost:49603/packages/flutter/src/gestures/pointer_router.dart.lib.js:112:26
    at LinkedMap.new.forEach (http://localhost:49603/dart_sdk.js:27745:11)
at [_dispatchEventToRoutes] (http://localhost:49603/packages/flutter/src/gestures/pointer_router.dart.lib.js:110:29)
at pointer_router.PointerRouter.new.route (http://localhost:49603/packages/flutter/src/gestures/pointer_router.dart.lib.js:105:37)
at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:49603/packages/flutter/src/gestures/binding.dart.lib.js:367:26)
at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:49603/packages/flutter/src/gestures/binding.dart.lib.js:355:24)
at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:49603/packages/flutter/src/rendering/layer.dart.lib.js:5440:13)
at [_handlePointerEventImmediately] (http://localhost:49603/packages/flutter/src/gestures/binding.dart.lib.js:331:14)
at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:49603/packages/flutter/src/gestures/binding.dart.lib.js:305:43)
at [_flushPointerEventQueue] (http://localhost:49603/packages/flutter/src/gestures/binding.dart.lib.js:295:14)

```

</details>

**Comment by exaby73** [comment]
Hello @SnowZero. Thanks for filing this issue. As the error says, `pickMultiImage` is not implemented on web, only on Android and iOS. If you want to have such functionality, you can use [`file_picker`](https://pub.dev/packages/file_picker), which does provide such functionality.

I am marking this issue as a feature request, rather than a bug

**Comment by exaby73** [comment]
Hello @SnowZero. Upon further investigation, looks like `pickMultiImage` has been introduced in `2.1.1`. Please upgrade your plugin version. See the changelog [here](https://pub.dev/packages/image_picker_for_web/changelog#211).

<details>
<summary>Code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:image_picker/image_picker.dart';
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(const VideoPlayerIssueApp());
}

class VideoPlayerIssueApp extends StatefulWidget {
  const VideoPlayerIssueApp({Key? key}) : super(key: key);

  @override
  State<VideoPlayerIssueApp> createState() => _VideoPlayerIssueAppState();
}

class _VideoPlayerIssueAppState extends State<VideoPlayerIssueApp> {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyHomePage(title: "IMP Test"));
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<XFile> images = [];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: [
          TextButton(
            onPressed: () async {
              _uploadAction();
            },
            child: Text('Button'),
          ),
          Expanded(
              child: ListView.builder(
            itemBuilder: (BuildContext context, int index) {
              if (kIsWeb) {
                return Image.network(images[index].path);
              } else {
                return Image.file(File(images[index].path));
              }
            },
            itemCount: images.length,
          ))
        ],
      ),
    );
  }

  _uploadAction() async {
    var getImage = await ImagePicker().pickMultiImage();

    setState(() {
      if (getImage != null) {
        images = getImage;
      }
    });
  }
}
```

</details>

Closing this issue as solved.
