### ISSUE TITLE
[ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage

### ISSUE THREAD

**Issue by huangsir0** [flutter/flutter#107471]
## logs

``` dart

I/flutter (22717): SETTING HEIGHT TO 5405.0
E/OpenGLRenderer(22717): [SurfaceTexture-0-22717-1] bindTextureImage: error binding external image: 0x501
E/flutter (22717): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter (22717): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter (22717): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
E/flutter (22717): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:55)
E/flutter (22717): 
F/flutter (22717): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1322)] Check failed: fml::jni::CheckException(env). 
F/libc    (22717): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 22892 (1.raster), pid 22717 (.kbit.fusion.an)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/EML-AL00/HWEML:10/HUAWEIEML-AL00/10.0.0.176C00:user/release-keys'
Revision: '0'
ABI: 'arm64'
SYSVMTYPE: Maple
APPVMTYPE: Art
Timestamp: 2022-07-12 22:39:43+0800
pid: 22717, tid: 22892, name: 1.raster  >>> com.kbit.fusion.an <<<
uid: 11042
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1322)] Check failed: fml::jni::CheckException(env). 
'
    x0  0000000000000000  x1  000000000000596c  x2  0000000000000006  x3  0000006fe64d9030
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  2b1ff6e9818b38a3  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 0000000000000003  x14 0000000000000001  x15 ffffffffffffffff
    x16 00000070f0caf908  x17 00000070f0c8f6f0  x18 0000006fd80fa000  x19 00000000000058bd
    x20 000000000000596c  x21 00000000ffffffff  x22 0000007001f51818  x23 0000006f84dac6e8
    x24 0000006feca7fd80  x25 0000000000000000  x26 0000000000000001  x27 0000000000000001
    x28 0000000000000087  x29 0000006fe64d90d0
    sp  0000006fe64d9010  lr  00000070f0c44580  pc  00000070f0c445ac
backtrace:
      #00 pc 00000000000705ac  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: dd332e039fe8318b6348d1305e5e0c7c)
      #01 pc 000000000156e9cc  /data/app/com.kbit.fusion.an-d9gHa41Uvh8H-9atHYMnXw==/lib/arm64/libflutter.so (BuildId: bdbfddd1a50329f00753bdc31442cc4f3b66b4c7)
Lost connection to device.
```

## flutter doctor
``` dart

[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [版本 10.0.19044.1766], locale zh-CN)
    • Flutter version 3.0.4 at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (12 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\Program Files\Android\SDK
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (2 available)
    • EML AL00 (mobile) • VED7N18904004000 • android-arm64 • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64   • Microsoft Windows [版本 10.0.19044.1766]

HTTP Host availability check is taking a long time...[!] HTTP Host Availability
    X HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到

    X HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到


```

## code 

``` dart
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Crash Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Crash'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late double _webViewHeight;

  @override
  void didChangeDependencies() {
    _webViewHeight = MediaQuery.of(context).size.height;
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: SingleChildScrollView(
          child: Column(
            children: [
              const Text('Some scrollable header'),
              SizedBox(
                height: _webViewHeight,
                child: InAppWebView(
                  initialUrlRequest: URLRequest(
                      url: Uri.parse(
                          "https://inappwebview.dev/")),
                  initialOptions: InAppWebViewGroupOptions(
                    android: AndroidInAppWebViewOptions(
                      useHybridComposition: true,
                    ),
                  ),
                  onWebViewCreated: (controller) {},
                  onLoadStop: (controller, uri) async {
                    final height = await controller.evaluateJavascript(
                        source: 'document.body.scrollHeight');
                    print('SETTING HEIGHT TO ${height + 10.0}');
                    setState(() {
                      _webViewHeight = height + 10.0;
                    });
                  },
                ),
              ),
            ],
          ),
        ));
  }
}


```

### pubspec.yaml

flutter_inappwebview: ^5.4.3+7

### More info

``` dart

Carsh when _webViewHeight changed.

 I'm not sure the Crash belone to flutter or flutter_inappwebview,

The code run no problem in flutter 2.10.4. 

```

**Comment by maheshmnj** [comment]
Hi @huangsir0, Thanks for filing the issue. I am unable to reproduce the issue, the app runs fine on the latest stable 3.0.4. Does the crash happen every time? Are there any specific steps to reproduce the crash? What device is the crash happening on ?


<img src="https://user-images.githubusercontent.com/31410839/178680510-8a6f2def-4fca-486a-a00e-8b0068692d21.png" width ="300">  


<details>
<summary>logs</summary>

```
Could not load custom device from config index 0: Expected enabled to be a boolean.
Launching lib/main.dart on sdk gphone arm64 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:61423/fenYfOuJ8jU=/ws
W/.example.sampl( 9990): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
W/.example.sampl( 9990): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
W/.example.sampl( 9990): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
I/System.out( 9990): recordForce value 6
W/.example.sampl( 9990): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
D/HostConnection( 9990): HostConnection::get() New Host Connection established 0xb4000078418f8010, tid 10358
D/HostConnection( 9990): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
D/EGL_emulation( 9990): eglCreateContext: 0xb400007831924d50: maj 3 min 0 rcv 3
D/EGL_emulation( 9990): eglMakeCurrent: 0xb400007831924d50: ver 3 0 (tinfo 0xb4000077d195cd60) (first time)
W/cr_media( 9990): Requires BLUETOOTH permission
I/PlatformViewsController( 9990): Hosting view in view hierarchy for platform view: 0
W/Gralloc4( 9990): allocator 3.x is not supported
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
D/EGL_emulation( 9990): eglCreateContext: 0xb400007831926980: maj 3 min 0 rcv 3
I/Choreographer( 9990): Skipped 63 frames!  The application may be doing too much work on its main thread.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/OpenGLRenderer( 9990): Davey! duration=1081ms; Flags=0, IntendedVsync=3751438644933, Vsync=3752488644891, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=3752498073872, AnimationStart=3752498074747, PerformTraversalsStart=3752498239205, DrawStart=3752500237122, SyncQueued=3752505075455, SyncStart=3752591908288, IssueDrawCommandsStart=3752592360997, SwapBuffers=3752600490330, FrameCompleted=3752607226455, DequeueBufferDuration=793917, QueueBufferDuration=953792, GpuCompleted=60129542144,
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/.example.sampl( 9990): Background young concurrent copying GC freed 7827(811KB) AllocSpace objects, 18(788KB) LOS objects, 31% free, 3827KB/5626KB, paused 124us total 146.775ms
D/EGL_emulation( 9990): eglCreateContext: 0xb400007831922780: maj 3 min 0 rcv 3
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/.example.sampl( 9990): Background young concurrent copying GC freed 28473(1227KB) AllocSpace objects, 54(2364KB) LOS objects, 43% free, 4310KB/7577KB, paused 6.087ms total 52.078ms
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 9 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 6 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/flutter ( 9990): SETTING HEIGHT TO 5313.0
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/Choreographer( 9990): Skipped 36 frames!  The application may be doing too much work on its main thread.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 2 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 1 line
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 1 line
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 5 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 2 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 4 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 18 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 58 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 12 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 100 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 283 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 11 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 111 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 11 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 8 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 2 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 8 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 2 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 3 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 4 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 16 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 4 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 2 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 3 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 12 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 28 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 832 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 8 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 136 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 492 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 45 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 118 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 290 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 188 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 291 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 14 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 24 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 181 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 472 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 651 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 7 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 78 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 366 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 543 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 640 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 1015 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
I/chatty  ( 9990): uid=10178(com.example.sample) RenderThread identical 6 lines
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.
E/FrameEvents( 9990): updateAcquireFence: Did not find frame.

```
</details>

**Comment by huangsir0** [comment]
``` dart
device: HUAWEI p20
ios: HarmonyOS 2.0
more: Carsh when _webViewHeight changed.

often crash
```

**Comment by maheshmnj** [comment]
Thanks for the info @huangsir0, Can you also please check if this reproduces on other devices?
I did try a slightly modified version of code and that doesn't crash either verified on Xiaomi k20 pro (android 11) and pixle 3 emulator.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Crash Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Crash'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late double _webViewHeight;

  @override
  void didChangeDependencies() {
    _webViewHeight = MediaQuery.of(context).size.height;
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        floatingActionButton: FloatingActionButton(onPressed: () async {
          setState(() {
            _webViewHeight = _webViewHeight + 10.0;
          });
        }),
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: SingleChildScrollView(
          child: Column(
            children: [
              const Text('Some scrollable header'),
              SizedBox(
                height: _webViewHeight,
                child: InAppWebView(
                  initialUrlRequest:
                      URLRequest(url: Uri.parse("https://inappwebview.dev/")),
                  initialOptions: InAppWebViewGroupOptions(
                    android: AndroidInAppWebViewOptions(
                      useHybridComposition: true,
                    ),
                  ),
                  onWebViewCreated: (controller) {},
                  onLoadStop: (controller, uri) async {
                    final height = await controller.evaluateJavascript(
                        source: 'document.body.scrollHeight');
                    print('SETTING HEIGHT TO ${height + 10.0}');
                    setState(() {
                      _webViewHeight = height + 10.0;
                    });
                  },
                ),
              ),
            ],
          ),
        ));
  }
}
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
