### ISSUE TITLE
[video_player] 2.3.0 Playback error E/ExoPlayerImplInternal(18969): com.google.android.exoplayer2.ExoPlaybackException: Source error E/ExoPlayerImplInternal(18969): at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)

### ISSUE THREAD

**Issue by aakashpatel7979** [flutter/flutter#107496]
<details>
<summary>error logs</summary>

```
Playback error
E/ExoPlayerImplInternal( 2745):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
E/ExoPlayerImplInternal( 2745):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 2745):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 2745):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 2745):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:396)
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal( 2745):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 2745):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 2745):       at java.lang.Thread.run(Thread.java:923)
E/ExoPlayerImplInternal( 2745): Playback error
E/ExoPlayerImplInternal( 2745):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
E/ExoPlayerImplInternal( 2745):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 2745):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 2745):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 2745):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:396)
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
E/ExoPlayerImplInternal( 2745):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal( 2745):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 2745):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 2745):       at java.lang.Thread.run(Thread.java:923)
```
</details>

**Comment by aakashpatel7979** [comment]
i'm using certified server URL like that,
![image](https://user-images.githubusercontent.com/75755337/178600597-b9d81adc-8f36-4d3b-a18c-f957134e50b1.png)

**Comment by aakashpatel7979** [comment]
Can you please check @danagbemava-nc @hamdikahloun

**Comment by danagbemava-nc** [comment]
Hi @aakashpatel7979

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide the relevant steps to reproduce. 

Thank you

**Comment by aakashpatel7979** [comment]
Hello @danagbemava-nc,
  ```
@override
  void initState() {
    super.initState();
    _videoPlayerController =
        VideoPlayerController.network('${APIUtils().imageURL + widget.video}');
    _videoPlayerController.addListener(() {
      setState(() {});
    });
    _initialVideoPlayer = _videoPlayerController.initialize();
    _videoPlayerController.setLooping(true);
    _videoPlayerController.play();
  }

  @override
  Widget build(BuildContext context) {
    var size = MediaQuery.of(context).size;

    return FutureBuilder(
        future: _initialVideoPlayer,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            return GestureDetector(
              onTap: () {
                pauseVideo();
              },
              child: Stack(
                alignment: Alignment.center,
                children: [
                  Center(
                      child: AspectRatio(
                    aspectRatio: _videoPlayerController.value.aspectRatio,
                    child: Stack(
                      alignment: Alignment.bottomCenter,
                      children: <Widget>[
                        VideoPlayer(_videoPlayerController),
                      ],
                    ),
                  ))
 });
```



- Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale en-IN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.69.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

**Comment by danagbemava-nc** [comment]
Hi @aakashpatel7979, please provide a sample video link that you are experiencing the issue with so that we can investigate further.

Thank you

**Comment by aakashpatel7979** [comment]
Please find the sample video link:

`https://dev.fwittyindia.com/storage/user-video/lGrabXcmuNZQG1EzSz1NqM1LhlT5mG2L6aLbK6YR.mp4`

**Comment by danagbemava-nc** [comment]
Hi @aakashpatel7979, please provide the complete runnable sample. Your sample isn't runnable in it's current state.

Thank you
