### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: Not a directory, errno = 20

### ISSUE THREAD

**Issue by hamada81993** [flutter/flutter#107410]
## Command
```
flutter --no-color run --machine --device-id=chrome --start-paused lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: Not a directory, errno = 20
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      _File.createSync (dart:io/file_impl.dart:270:14)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:23:16)
#3      ErrorHandlingFile.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:286:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.createSync (package:flutter_tools/src/base/error_handling_io.dart:285:5)
#6      _renderTemplateToFile (package:flutter_tools/src/flutter_plugins.dart:32:8)
#7      _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:448:3)
#8      injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1114:11)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:381:5)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1328:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
```
```
[✓] Flutter (Channel stable, 3.0.3, on macOS 11.6.7 20G630 darwin-x64, locale en-EG)
    • Flutter version 3.0.3 at /Users/apple/Pictures/js_composer/wetransfer_scooter-logo_2022-05-08_2256/6amMart_v1.1_GambitSteel_NULLED/3ndey_Logo_ID_1-1.2-1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (3 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Users/apple/Pictures/js_composer/wetransfer_scooter-logo_2022-05-08_2256/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/apple/Pictures/js_composer/wetransfer_scooter-logo_2022-05-08_2256/6amMart_v1.1_GambitSteel_NULLED/3ndey_Logo_ID_1-1.2-1/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6.7 20G630 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b22742018b3edf16c6cadd7b76d9db5e7f9064b5
### Plugins
device_info-2.0.2
flutter_plugin_android_lifecycle-2.0.2
geolocator-7.4.0
geolocator_android-1.0.0
geolocator_apple-1.0.0
geolocator_web-2.0.6
image_picker-0.8.2
image_picker_for_web-2.1.2
path_provider-2.0.2
path_provider_linux-2.0.2
path_provider_macos-2.0.2
path_provider_windows-2.0.3
shared_preferences-2.0.6
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.1
shared_preferences_windows-2.0.2
sqflite-2.0.0+3

**Comment by huycozy** [comment]
Hi @hamada81993 
There is a similar issue #103822 that contains a crash report message but I don't see it in your logs. Do you see it when trying again?
Also, could you retry on the lastest Flutter version stable `3.0.4` and master `3.1.0-0.0.pre.1609` to see if the issue still reproduces? 
And please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
Thank you!
