### ISSUE TITLE
[flutter_tools] ArgumentError during Hot restart

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#107592]
On `beta/3.1.0-9.0.pre`

with command `flutter run -d chrome`

```
ArgumentError: Invalid argument(s): Uri org-dartlang-app:/web_entrypoint.dart must have scheme 'file:'.
at WindowsStyle.pathFromUri(windows.dart:86)
at Context.fromUri(context.dart:1000)
at FileSystem.getPath(file_system.dart:158)
at LocalFileSystem.file(local_file_system.dart:26)
at ErrorHandlingFileSystem.file(error_handling_io.dart:123)
at ProjectFileInvalidator.findInvalidated(run_hot.dart:1464)
at ResidentWebRunner._updateDevFS(resident_web_runner.dart:481)
at ResidentWebRunner.restart(resident_web_runner.dart:359)
at <asynchronous gap>(async)
at TerminalHandler._commonTerminalInputHandler(resident_runner.dart:1688)
at <asynchronous gap>(async)
at TerminalHandler.processTerminalInput(resident_runner.dart:1741)
at <asynchronous gap>(async)
```

**Comment by christopherfujino** [comment]
Link from stacktrace: https://github.com/flutter/flutter/blob/f28e570c8cb12a004fae2d796d0d9cd46603bde9/packages/flutter_tools/lib/src/run_hot.dart#L1464

```dart
      for (final Uri uri in urisToScan) {
        // Calling fs.statSync() is more performant than fs.file().statSync(), but
        // uri.toFilePath() does not work with MultiRootFileSystem.
        final DateTime updatedAt = uri.hasScheme && uri.scheme != 'file'
          ? _fileSystem.file(uri).statSync().modified
          : _fileSystem.statSync(uri.toFilePath(windows: _platform.isWindows)).modified;
```

**Comment by huycozy** [comment]
There is also a duplicate [issue](https://github.com/flutter/flutter/issues/124036) with similar stack trace but different uri (`org-dartlang-app:/web_plugin_registrant.dart `):

```
ArgumentError: Invalid argument(s): Uri org-dartlang-app:/web_plugin_registrant.dart must have scheme 'file:'.

#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:86:7)
#1      Context.fromUri (package:path/src/context.dart:1000:32)
#2      FileSystem.getPath (package:file/src/interface/file_system.dart:158:24)
#3      LocalFileSystem.file (package:file/src/backends/local/local_file_system.dart:26:54)
#4      ErrorHandlingFileSystem.file (package:flutter_tools/src/base/error_handling_io.dart:123:24)
#5      ProjectFileInvalidator.findInvalidated (package:flutter_tools/src/run_hot.dart:1486:25)
#6      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:477:80)
#7      ResidentWebRunner.restart (package:flutter_tools/src/isolated/resident_web_runner.dart:355:43)
<asynchronous suspension>
#8      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1720:40)
<asynchronous suspension>
#9      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1760:7)
<asynchronous suspension>
```
