### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by 309791679** [flutter/flutter#107798]
Flutter new build project

Flutter version : 3.0.5

flutter doctor
```
[√] Flutter (Channel stable, 3.0.5, on Windows, locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] Android Studio (version 2021.2)
[√] Android Studio (version 2021.3)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

android studio 2021.2.1
plugins Dart:212.5744 Flutter 69.0.2

```
FAILURE: Build failed with an exception.

* Where:
Script 'H:\flutter_3.0.5\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'H:\flutter_3.0.5\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1
```
flutter run --verbose
```
The system cannot find the specified path.
The system cannot find the specified path.
The system cannot find the specified path.
[  +79 ms] executing: [H:\flutter_3.0.5/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +212 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] f1875d570e39de09040c8f79aa13cc56baab8db1
[   +1 ms] executing: [H:\flutter_3.0.5/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[ +186 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[   +1 ms] 3.0.5
[  +11 ms] executing: [H:\flutter_3.0.5/] git rev-parse --abbrev-ref --symbolic @{u}
[ +174 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [H:\flutter_3.0.5/] git ls-remote --get-url origin
[ +168 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +260 ms] executing: [H:\flutter_3.0.5/] git rev-parse --abbrev-ref HEAD
[ +178 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +195 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +5 ms] Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[  +63 ms] executing: C:\Users\z\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +285 ms] List of devices attached
                    adb-22b38ce-ByP4Dq._adb-tls-connect._tcp device product:alioth model:M2012K11AC device:alioth transport_id:1
[  +25 ms] C:\Users\z\AppData\Local\Android\sdk\platform-tools\adb.exe -s adb-22b38ce-ByP4Dq._adb-tls-connect._tcp shell getprop
[ +337 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +153 ms] Skipping pub get: version match.
[  +79 ms] Generating C:\Users\z\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +85 ms] ro.hardware = qcom
[  +48 ms] Initializing file store
[  +16 ms] Skipping target: gen_localizations
[  +10 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: C:\Users\z\myapp\.dart_tool\package_config_subset}
[  +37 ms] gen_dart_plugin_registrant: Complete
[   +2 ms] Skipping target: _composite
[   +2 ms] complete
[   +7 ms] Launching lib\main.dart on M2012K11AC in debug mode...
[   +6 ms] H:\flutter_3.0.5\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev H:\flutter_3.0.5\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
H:\flutter_3.0.5\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\z\AppData\Local\Temp\flutter_tools.3ec29b5a\flutter_tool.db8f9fa4\app.dill --packages C:\Users\z\myapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +21 ms] executing: C:\Users\z\AppData\Local\Android\sdk\platform-tools\adb.exe -s adb-22b38ce-ByP4Dq._adb-tls-connect._tcp shell -x logcat -v time -t 1
[ +237 ms] <- compile package:myapp/main.dart
[+3862 ms] --------- beginning of main
                    07-17 20:26:40.285 D/MdSpeechManager( 4571): registerChargingState time cost : 1
[ +149 ms] executing: C:\Users\z\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +205 ms] Android Debug Bridge version 1.0.41
                    Version 33.0.2-8557947
                    Installed as C:\Users\z\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\z\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +202 ms] Building APK
[  +21 ms] Running Gradle task 'assembleDebug'...
[   +6 ms] Using gradle from C:\Users\z\myapp\android\gradlew.bat.
[  +21 ms] executing: H:android studio\android-studio2021.1.1\jre\bin\java -version
[ +309 ms] Exit code 0 from: H:android studio\android-studio2021.1.1\jre\bin\java -version
[        ] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+9-b60-7590822, mixed mode)
[   +2 ms] executing: H:android studio\android-studio2021.2.1\jre\bin\java -version
[ +306 ms] Exit code 0 from: H:android studio\android-studio2021.2.1\jre\bin\java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +3 ms] executing: H:android studio\android-studio 2021.3.1\jre\bin\java -version
[ +351 ms] Exit code 0 from: H:android studio\android-studio 2021.3.1\jre\bin\java -version
[   +1 ms] openjdk version "11.0.13" 2021-10-19
           OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
           OpenJDK 64-Bit Server VM (build 11.0.13+0-b1751.21-8125866, mixed mode)
[   +1 ms] executing: H:android studio\android-studio 2021.3.1\jre\bin\java -version
[ +304 ms] Exit code 0 from: H:android studio\android-studio 2021.3.1\jre\bin\java -version
[   +1 ms] openjdk version "11.0.13" 2021-10-19
           OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
           OpenJDK 64-Bit Server VM (build 11.0.13+0-b1751.21-8125866, mixed mode)
[   +2 ms] executing: [C:\Users\z\myapp\android/] C:\Users\z\myapp\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=C:\Users\z\myapp\lib\main.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +176 ms] ϵͳ�Ҳ���ָ����·����
[+3427 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[+1962 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] ϵͳ�Ҳ���ָ����·����
[   +1 ms] ϵͳ�Ҳ���ָ����·����
[        ] ϵͳ�Ҳ���ָ����·����
[ +782 ms] Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[+2311 ms] > Task :app:compileFlutterBuildDebug FAILED
[   +1 ms] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[        ] Script 'H:����������\flutter_3.0.5\packages\flutter_tools\gradle\flutter.gradle' line: 1156
[   +1 ms] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command 'H:����������\flutter_3.0.5\bin\flutter.bat'' finished with non-zero exit value 1
[   +1 ms] * Try:
[        ] > Run with --stacktrace option to get the stack trace.
[   +1 ms] > Run with --info or --debug option to get more log output.
[   +1 ms] > Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 8s
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[   +2 ms] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[   +1 ms] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] 1 actionable task: 1 executed
[ +526 ms] Running Gradle task 'assembleDebug'... (completed in 10.5s)
[   +4 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 16,458ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +170 ms] ensureAnalyticsSent: 166ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

**Comment by 309791679** [comment]
Please reply to me as soon as possible

**Comment by znromonk** [comment]
I know there could be various reasons for this happening but when I had similar issue it was solved by doing the following:
1. delete `pubspec.lock`
2. `flutter clean`
3. `flutter pub get`
4. `flutter pub upgrade`

Just to note, I did not remember having `The system cannot find the specified path.` in the `flutter run` logs.

**Comment by 309791679** [comment]
> 我知道发生这种情况可能有多种原因，但是当我遇到类似的问题时，通过执行以下操作可以解决：
> 
> 1. 删除`pubspec.lock`
> 2. `flutter clean`
> 3. `flutter pub get`
> 4. `flutter pub upgrade`
> 
> 只是要注意，我不记得日志中有。`The system cannot find the specified path.``flutter run`

I have tried the same effect. I found that other people also have this problem, but there is no solution

**Comment by huycozy** [comment]
Hi @309791679 
Based on your `flutter run --verbose` output:

> The system cannot find the specified path.
...
Script 'H:����������\flutter_3.0.5\packages\flutter_tools\gradle\flutter.gradle' line: 1156

Could you try copying Flutter SDK folder to another drive and retry to see if the issue still reproduces?
