### ISSUE TITLE
 Failed assertion: line 4531 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by helalramadan** [flutter/flutter#107753]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by helalramadan** [comment]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building AnimatedPhysicalModel(duration: 200ms, shape: rectangle, borderRadius: BorderRadius.zero, elevation: 0.0, color: Color(0xff333739), animateColor: false, shadowColor: Color(0xff000000), animateShadowColor: true, state: _AnimatedPhysicalModelState#9d149(ticker inactive)):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4531 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///C:/Users/helal/Desktop/GitHub/News_App/lib/webview/webview.dart:12:12
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4531:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4534:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
