### ISSUE TITLE
[tool_crash] _CastError: (#0      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:275:18))

### ISSUE THREAD

**Issue by nullLuli** [flutter/flutter#107709]
## Command
```
flutter attach -d iPhone 13 mini
```

## Steps to Reproduce
1. open iOS simulator（iOS15.5）
2. run 'Flutter Demo'
3. execute 'flutter attach' command

## Logs
_CastError: (#0      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:275:18))
```
#0      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:275:18)
#1      AttachCommand.runCommand.<anonymous closure> (package:flutter_tools/src/commands/attach.dart:222:19)
#2      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#3      _rootRun (dart:async/zone.dart:1391:13)
#4      _CustomZone.run (dart:async/zone.dart:1293:19)
#5      _runZoned (dart:async/zone.dart:1829:10)
#6      runZoned (dart:async/zone.dart:1751:10)
#7      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:221:19)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1195:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1307, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.1.0-0.0.pre.1307 at /Users/lilu/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db829c1e20 (4 weeks ago), 2022-06-17 21:34:27 -0700
    • Engine revision d4a0dda5ca
    • Dart version 2.18.0 (build 2.18.0-190.0.dev)
    • DevTools version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lilu/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • iPhone 13 mini (mobile) • CE869A8F-4B1E-46C9-B7DB-28CAB7B75071 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 102.0.5005.115

[!] HTTP Host Availability
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed out
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed out

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: db829c1e200823cd655a6e0ca326967ff89d9c4f

**Comment by darshankawar** [comment]
@nullLuli 
`flutter attach` command is usually used for add2app project. Is the `flutter demo` project you mentioned an add2app ?
If not, does running `flutter run` on it gives you any other error or it compiles and builds properly on the device ?

**Comment by nullLuli** [comment]
Yes, it isn't a add2app, it a flutter project. I have run it success with android studio run button, but i found that breakpoint not work. So i use attach command, hope make breakpoint work again.

**Comment by darshankawar** [comment]
Thanks for the update. I am able to replicate the tool crash by following steps to replicate.

<details>
<summary> console error log </summary>

```

dhs@Dhss-MacBook-Pro test_app % flutter attach -d 3BD8F2FF-FDB5-4074-8C91-54F99C79156D

Oops; flutter has exited unexpectedly: "Null check operator used on a null value".
A crash report has been written to /Users/dhs/Documents/NCFlutter/test_app/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+Null+check+operator+used+on+a+null+value

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+_CastError%3A+%28%230++++++AttachCommand._attachToDevice+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fattach.dart%3A275%3A18%29%29&body=%23%23+Command%0A%60%60%60%0Aflutter+attach+-d+3BD8F2FF-FDB5-4074-8C91-54F99C79156D%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0A_CastError%3A+%28%230++++++AttachCommand._attachToDevice+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fattach.dart%3A275%3A18%29%29%0A%60%60%60%0A%230++++++AttachCommand._attachToDevice+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fattach.dart%3A275%3A18%29%0A%231++++++AttachCommand.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fattach.dart%3A222%3A19%29%0A%232++++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A29%29%0A%233++++++_rootRun+%28dart%3Aasync%2Fzone.dart%3A1391%3A13%29%0A%234++++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1293%3A19%29%0A%235++++++_runZoned+%28dart%3Aasync%2Fzone.dart%3A1829%3A10%29%0A%236++++++runZoned+%28dart%3Aasync%2Fzone.dart%3A1751%3A10%29%0A%237++++++AppContext.run+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A149%3A12%29%0A%238++++++AttachCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fattach.dart%3A221%3A19%29%0A%3Casynchronous+suspension%3E%0A%239++++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1209%3A27%29%0A%3Casynchronous+suspension%3E%0A%2310+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2311+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%3Casynchronous+suspension%3E%0A%2312+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A281%3A9%29%0A%3Casynchronous+suspension%3E%0A%2313+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2314+++++FlutterCommandRunner.runCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A229%3A5%29%0A%3Casynchronous+suspension%3E%0A%2315+++++run.%3Canonymous+closure%3E.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Frunner.dart%3A62%3A9%29%0A%3Casynchronous+suspension%3E%0A%2316+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel+master%2C+3.1.0-0.0.pre.1698%2C+on+macOS+12.2.1+21D62+darwin-x64%2C+locale+en-GB%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.1.0-0.0.pre.1698+on+channel+master+at+%2FUsers%2Fdhs%2Fdocuments%2Ffluttersdk%2Fflutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Framework+revision+a4ba62fd9d+%2820+hours+ago%29%2C+2022-07-17+05%3A48%3A06+-0400%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+b438edfd1a%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+2.19.0+%28build+2.19.0-5.0.dev%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+version+2.15.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Xcode+-+develop+for+iOS+and+macOS+%28Xcode+13.2.1%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Xcode+at+%2FApplications%2FXcode.app%2FContents%2FDeveloper%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Build+13C100%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+CocoaPods+version+1.11.2%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+%2FApplications%2FGoogle+Chrome.app%2FContents%2FMacOS%2FGoogle+Chrome%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+IntelliJ+IDEA+Ultimate+Edition+%28version+2021.3.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+IntelliJ+at+%2FApplications%2FIntelliJ+IDEA.app%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+version+65.1.4%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+version+213.7228%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.62.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+%2FApplications%2FVisual+Studio+Code.app%2FContents%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+3.29.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%283+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+iPhone+13+%28mobile%29+%E2%80%A2+3BD8F2FF-FDB5-4074-8C91-54F99C79156D+%E2%80%A2+ios++++++++++++%E2%80%A2+com.apple.CoreSimulator.SimRuntime.iOS-15-2+%28simulator%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+macOS+%28desktop%29++++%E2%80%A2+macos++++++++++++++++++++++++++++++++%E2%80%A2+darwin-x64+++++%E2%80%A2+macOS+12.2.1+21D62+darwin-x64%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28web%29+++++++%E2%80%A2+chrome+++++++++++++++++++++++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+103.0.5060.114%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+HTTP+Host+Availability%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+required+HTTP+hosts+are+available%0A%0A%1B%5B32m%E2%80%A2%1B%5B39m+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+1aafb3a8b9b0c36241c5f5b34ee914770f015818%0A%0A&labels=tool%2Csevere%3A+crash

dhs@Dhss-MacBook-Pro test_app % 

```

</details>

<details>
<summary> master flutter doctor -v </summary>

```

[✓] Flutter (Channel master, 3.1.0-0.0.pre.1698, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1698 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a4ba62fd9d (20 hours ago), 2022-07-17 05:48:06 -0400
    • Engine revision b438edfd1a
    • Dart version 2.19.0 (build 2.19.0-5.0.dev)
    • DevTools version 2.15.0

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 3BD8F2FF-FDB5-4074-8C91-54F99C79156D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by jmagman** [comment]
@christopherfujino fallout from https://github.com/flutter/flutter/pull/105798/files#diff-70164e71957eed4bf8b4119543e779e808e3ddfedeceef98d4a24ab23efc99ecR275

**Comment by christopherfujino** [comment]
Fixed
