### ISSUE TITLE
Flutter application debug error

### ISSUE THREAD

**Issue by discoveruz** [flutter/flutter#107832]
Google Pixel 2 android sdk 28 debugging error.

```
[ +976 ms] E/FlutterLoader( 7051): Flutter initialization failed.
[   +1 ms] E/FlutterLoader( 7051): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip
file
"/data/app/com.ecompany_uz.staff_application-wkQ6gx6JF1de6YsrjjStLg==/base.apk"],nativeLibraryDirectories=[/data/app/com.ecompany_uz.staff_application-wkQ6gx6JF1de6YsrjjStLg==/lib/arm, /data/app/com.ecompany_uz.staff_application-wkQ6gx6JF1de6YsrjjStLg==/base.apk!/lib/armeabi-v7a, /system/lib]]] couldn't find
"libflutter.so"
[   +1 ms] E/FlutterLoader( 7051):      at java.util.concurrent.FutureTask.report(FutureTask.java:123)
[        ] E/FlutterLoader( 7051):      at java.util.concurrent.FutureTask.get(FutureTask.java:193)
[        ] E/FlutterLoader( 7051):      at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:236)
[        ] E/FlutterLoader( 7051):      at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
[        ] E/FlutterLoader( 7051):      at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
[        ] E/FlutterLoader( 7051):      at
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:266)
[        ] E/FlutterLoader( 7051):      at
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:175)
[   +1 ms] E/FlutterLoader( 7051):      at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
[        ] E/FlutterLoader( 7051):      at android.app.Activity.performCreate(Activity.java:7136)
[        ] E/FlutterLoader( 7051):      at android.app.Activity.performCreate(Activity.java:7127)
[        ] E/FlutterLoader( 7051):      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
[        ] E/FlutterLoader( 7051):      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
[        ] E/FlutterLoader( 7051):      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
[        ] E/FlutterLoader( 7051):      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[        ] E/FlutterLoader( 7051):      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[        ] E/FlutterLoader( 7051):      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[        ] E/FlutterLoader( 7051):      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
[        ] E/FlutterLoader( 7051):      at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/FlutterLoader( 7051):      at android.os.Looper.loop(Looper.java:193)
[        ] E/FlutterLoader( 7051):      at android.app.ActivityThread.main(ActivityThread.java:6669)
[        ] E/FlutterLoader( 7051):      at java.lang.reflect.Method.invoke(Native Method)
[        ] E/FlutterLoader( 7051):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/FlutterLoader( 7051):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[        ] E/FlutterLoader( 7051): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file
"/data/app/com.ecompany_uz.staff_application-wkQ6gx6JF1de6YsrjjStLg==/base.apk"],nativeLibraryDirectories=[/data/app/com.ecompany_uz.staff_application-wkQ6gx6JF1de6YsrjjStLg==/lib/arm, /data/app/com.ecompany_uz.staff_application-wkQ6gx6JF1de6YsrjjStLg==/base.apk!/lib/armeabi-v7a, /system/lib]]] couldn't find
"libflutter.so"
[        ] E/FlutterLoader( 7051):      at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
[        ] E/FlutterLoader( 7051):      at java.lang.System.loadLibrary(System.java:1669)
[        ] E/FlutterLoader( 7051):      at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
[        ] E/FlutterLoader( 7051):      at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:186)
[        ] E/FlutterLoader( 7051):      at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:179)
[        ] E/FlutterLoader( 7051):      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[        ] E/FlutterLoader( 7051):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/FlutterLoader( 7051):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/FlutterLoader( 7051):      at java.lang.Thread.run(Thread.java:764)
```

**Comment by danagbemava-nc** [comment]
Hi @discoveruz, you have not provided the output of `flutter doctor -v` or any of the information requested in https://github.com/flutter/flutter/issues/107832#issuecomment-1187451036.

Please provide the output of `flutter doctor -v` as well as the full output of `flutter run -v`. 

Please provide the content of your `android/app/build.gradle` as well so that we can investigate further. 

Thank you

**Comment by discoveruz** [comment]
`android/app/build.gradle `
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '3'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '0.1.2+1'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        ndk {
         abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64',"armeabi"
}

        applicationId "com.ecompany_uz.staff_application"
        minSdkVersion 22
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }

}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.android.material:material:1.7.0-alpha01'
    implementation platform('com.google.firebase:firebase-bom:29.3.1')
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
}
```

`flutter doctor -v`

```
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19044.1826], locale en-US)
    • Flutter version 3.0.2 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (6 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.1.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 103.0.1264.49

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by discoveruz** [comment]
`android/build.gradle`
```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
`android/gradle/wrapper/gradle-wrapper.properties`
```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
```

**Comment by discoveruz** [comment]
still i get the same result

**Comment by danagbemava-nc** [comment]
Hi @discoveruz, can you try running `flutter build apk` with the abiFilters in your `android/app/build.gradle` to see if you're able to generate the apk?

**Comment by discoveruz** [comment]
the app worked, but there are problems with debugging. What is the reason for this?

**Comment by danagbemava-nc** [comment]
Hi @discoveruz, this is a known issue that is being tracked in https://github.com/flutter/flutter/issues/29710. 

Kindly follow up in that issue for updates. 

Closing from here as duplicate. 

Thank you
