### ISSUE TITLE
Invariant violation in release mode is hard to debug

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#107875]
The framework has many asserts that guard against invariant violation when running in debug mode.

If an application is released to the wild, some edge case may violate the invariant and dump a stack trace that provides little clue to the developer about how to identify the violation. For example, accessing `size` in `layout` incorrectly may result in a stack trace like 

```
Thread 0 MAIN THREAD_CastError: Null check operator used on a null value
at RenderProxyBoxMixin.performLayout    (box.dart:2023)
at RenderObject.layout    (object.dart:2054)
at RenderBox.layout    (box.dart:2418)
at RenderProxyBoxMixin.performLayout    (proxy_box.dart:122)
at RenderObject.layout    (object.dart:2054)
at RenderBox.layout    (box.dart:2418)
at RenderProxyBoxMixin.performLayout    (proxy_box.dart:122)
at RenderObject.layout    (object.dart:2054)
```

We currently store `debugActivePaint` and `debugActiveLayout` in debug mode, but if we stored something like that in release mode we could print better errors here that might give developers a better clue about where to look when a failure in the wild happens like this.

Developers cannot use the `debugDump*` methods in release mode in these cases, as they are unavailable/print nothing at all.

One other potentially interesting option is if Dart could somehow provide an "even more expensive" `StackTrace.toString` that includes the concrete runtime type instead of/in addition to the actual source location - I'm not sure if that's really feasible or not though (@a-siva @rmacnak-google would know).

The main goal here is to help developers act on crash reports from the wild - the above stack is based on an actual crash report for customer: money. They do not know how to further act on this crash because the entire stack is in framework code - they don't even know if the bug is in the framework or in their own app.

@goderbauer @Hixie @jacob314

**Comment by jonahwilliams** [comment]
I think debugOwners could help, but we'd need to make heavy use of WeakRefs to avoid memory regressions

**Comment by dnfield** [comment]
I don't think we could use a weak ref - if the exception gets thrown and we go to read it and it was the last reference and the finalizer ran, we'd be right where we are today. We'd just need to be careful about clearing it out correctly.

**Comment by Hixie** [comment]
These debugging tools are expensive in aggregate. Enabling some specific ones in release builds is certainly a choice we can make, but we need to be _really_ careful about what precedent we set, we need to be really sure that the value is very high, and we need to keep it as simple as possible because these features are going to be very hard to reliably debug and test since all our normal infrastructure for debugging and testing them will be absent. (So for instance, I would try really hard to not involve anything like WeakRefs.)

Things like `debugActiveLayout` will likely appear to be cheap in benchmarks, but even something that simple is a tax we would be asking everyone to pay for every render object for every layout on every device for every user. (A very real tax, measured in Watts.) Same with `debugOwner` — this is bytes we would be charging literally everyone who uses a Flutter app all the time.

I would probably lean more towards post-failure diagnostics (e.g. a release mode version of dumping the trees) that costs nothing until a failure has happened. I would also focus more on how to reproduce the problem (e.g. what series of events did the app receive and what state was it in) than diagnosing the problem (this particular widget failed to layout correctly) because if we can reproduce the problem then we can diagnose it in debug mode but if we can't reproduce it then diagnosing it often isn't enough (since we have no way to be confident that the bug is fixed), even assuming it's possible to get good enough diagnostics to pin point the problem (which is unlikely).

**Comment by rmacnak-google** [comment]
> One other potentially interesting option is if Dart could somehow provide an "even more expensive" StackTrace.toString that includes the concrete runtime type instead of/in addition to the actual source location - I'm not sure if that's really feasible or not though 

Smalltalk always displays the stack in this way, with both the method's defining class and the receiver's class if they are different. For exceptions, Dart would require additional work at throw to record the receiver's class, which is probably small enough. Async traces would also requires some additional bookkeeping; I don't know exactly where that would need to go, but I expect it is about as expensive as an additional field write. The full runtime type including type arguments will cost more than just the receiver class.

```
#0      RenderProxyBoxMixin.performLayout (.../box.dart:2023)
```
=>
```
#0      RenderFlex(RenderProxyBoxMixin).performLayout (.../box.dart:2023)
```

But changing this may be intractable because although the output of StackTrace.toString is Undefined Behavior, it is often programmatically interpreted. I notice the trace in this very issue is not the output of StackTrace.toString but has been parsed and transformed.

Does having the receiver classes help that much in this example though? I would expect one would really need to get a hold of that top-most performLayout receiver and print a lot more properties starting from there. The Dart VM's compiler maintains a small amount of state like the current compilation phase and current instruction being processed that is the basis for a bunch of diagnostic printing upon a crash. Perhaps the Flutter framework could always track the current render object even when the expensive asserts are disabled so that it has a place to start printing upon a layout exception.

**Comment by Hixie** [comment]
If we made StackTrace introspectable we could avoid having to serialize it when we don't need to and could avoid having to parse the undefined format. :-)

**Comment by dnfield** [comment]
If it's not clear, my suggestion here wasn't to modify `toString`, but to have some new API.

**Comment by a-siva** [comment]
based on the discussion above seems like we haven't concluded on a path forward, lowering priority to P3
