### ISSUE TITLE
Getting error in flutter sdk *java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity*

### ISSUE THREAD

**Issue by SagarPandit54** [flutter/flutter#107824]
We are able to launch sdk , but after redirect to another, we get this error.

<details>
<summary>logs</summary>

```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime( 6350): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3539)
E/AndroidRuntime( 6350): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3699)
E/AndroidRuntime( 6350): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime( 6350): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6350): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6350): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
E/AndroidRuntime( 6350): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6350): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime( 6350): 	at android.app.ActivityThread.main(ActivityThread.java:8037)
E/AndroidRuntime( 6350): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6350): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime( 6350): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime( 6350): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime( 6350): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
E/AndroidRuntime( 6350): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
E/AndroidRuntime( 6350): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
E/AndroidRuntime( 6350): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
E/AndroidRuntime( 6350): 	at com.billdesk.sdk.v2.ui.redirect.RedirectActivity.onCreate(RedirectActivity.kt:59)
E/AndroidRuntime( 6350): 	at android.app.Activity.performCreate(Activity.java:8157)
E/AndroidRuntime( 6350): 	at android.app.Activity.performCreate(Activity.java:8129)
E/AndroidRuntime( 6350): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
E/AndroidRuntime( 6350): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3512)
E/AndroidRuntime( 6350): 	... 11 more
I/Process ( 6350): Sending signal. PID: 6350 SIG: 9
```
</details>

My flutter version 3.0.3

**Comment by danagbemava-nc** [comment]
Hi @SagarPandit54

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

You also appear to be on an older version of flutter, can you upgrade to the latest version of flutter stable (3.0.5) to see if you can still reproduce this issue? 

If you do, please provide the updated flutter doctor -v. 

Thank you
