### ISSUE TITLE
[macOS] First multi-touch scroll after hover or tap+swipe doesn't work 

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#107962]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Either hover the cursor over the ListView or try to drag the ListView a few times using the touchpad (tap+swipe)
3. Try to scroll using the touchpad (without tapping, swipe using two fingers)

**Expected results:** scrolling works

**Actual results:** scrolling works on the second swipe; on the first one the following error is seen in the debug build:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/gestures/events.dart': Failed assertion: line 1040 pos 15: '!identical(kind, PointerDeviceKind.trackpad)': is not true.
package:flutter/…/gestures/events.dart:1040
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      new PointerHoverEvent
package:flutter/…/gestures/events.dart:1040
#3      PointerEventConverter.expand.<anonymous closure>
package:flutter/…/gestures/converter.dart:87
#4      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#5      ListQueue.addAll (dart:collection/queue.dart:748:25)
#6      GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:293
#7      _invoke1 (dart:ui/hooks.dart:167:13)
#8      PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#9      _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final List<String> items = List<String>.generate(100, (index) => 'item $index');

    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: ListView.builder(
          itemCount: items.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text(items[index]),
              selected: index == 6,
              selectedTileColor: Colors.amber,
            );
          },
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
% flutter doctor -v
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1737, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1737 on channel master at /Library/Frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ed3c32c9d2 (62 minutes ago), 2022-07-19 15:30:06 -0400
    • Engine revision 203f4eedf2
    • Dart version 2.19.0 (build 2.19.0-10.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tgucio/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by tgucio** [comment]
This was introduced in https://github.com/flutter/flutter/pull/105987.
/cc @dkwingsmt

**Comment by dkwingsmt** [comment]
I can loosen the assertion, but I want to confirm with @moffatman : Is it expected in this scenario a hover event with kind trackpad?

**Comment by moffatman** [comment]
@dkwingsmt This must be a synthesized add/move event. I guess all the add events for trackpad would be `PointerDeviceKind.trackpad`, so that assertion couldn't hold? And not all of them will have `synthesized = true`, so can't update the assertion with that condition.

**Comment by moffatman** [comment]
It's not the same cursor, on each platform it should use a separate device identifier. That's because we need drag to stay with its initial location, even if the cursor is moved (let's say mouse + trackpad at the same time, or Mac magic mouse).

**Comment by dkwingsmt** [comment]
Fixing with https://github.com/flutter/flutter/pull/108116
