### ISSUE TITLE
[macOS][Desktop] Unhandled exception thrown when typing certain Khmer Unicode characters in the TextField

### ISSUE THREAD

**Issue by fidele007** [flutter/flutter#107978]
## Steps to Reproduce

1. Execute `flutter run -d macos` on the code sample 
2. Using the macOS Khmer keyboard, type the character [Khmer Sign Samyok Sannya](https://unicode-table.com/en/17D0/)​ ័ (Shift + 7)​ or [Khmer Sign Ahsda](https://unicode-table.com/en/17CF/) ៏ (Shift + 8)

**Expected results:**

The characters to be shown correctly.

**Actual results:**

An unhandled exception is thrown and the application hangs until a restart or a hot restart.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
        home: Scaffold(
            body: Center(
      child: TextField(),
    )));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 802 pos 16: 'data.physical != 0 && data.logical != 0': is not true.
package:flutter/…/services/hardware_keyboard.dart:802
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      KeyEventManager.handleKeyData
package:flutter/…/services/hardware_keyboard.dart:802
#3      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:400:41)
#4      _invoke1 (dart:ui/hooks.dart:168:13)
#5      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:398:7)
#6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#7      _rootRun (dart:async/zone.dart:1426:13)
#8      _CustomZone.run (dart:async/zone.dart:1328:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#10     _invoke2 (dart:ui/hooks.dart:189:10)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
```

```
Analyzing flutter_tuto...                                               
No issues found! (ran in 1.2s)
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-FR)
    • Flutter version 3.0.5 at /Users/fidele007/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by chinmaygarde** [comment]
cc @gspencergoog

**Comment by gspencergoog** [comment]
cc @dkwingsmt

**Comment by dkwingsmt** [comment]
Fixed by https://github.com/flutter/engine/pull/35044. (Might take a few days to be rolled in.)
