### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by Titanium2099** [flutter/flutter#107987]
## Command
```
flutter run --machine --start-paused -d 4E7A103D-B68F-4FEC-BAA0-5505163A7F6B --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart
```

## Steps to Reproduce
Running the project

## Logs
HttpException
```
#0      new _HttpClientConnection.<anonymous closure> (dart:_http/http_impl.dart:2053:9)
#1      _rootRunUnary (dart:async/zone.dart:1434:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#7      _StreamController._add (dart:async/stream_controller.dart:648:7)
#8      _StreamController.add (dart:async/stream_controller.dart:596:5)
#9      _HttpParser._headersEnd (dart:_http/http_parser.dart:403:17)
#10     _HttpParser._doParse (dart:_http/http_parser.dart:745:15)
#11     _HttpParser._parse (dart:_http/http_parser.dart:319:7)
#12     _HttpParser._onData (dart:_http/http_parser.dart:873:5)
#13     _rootRunUnary (dart:async/zone.dart:1434:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#19     _StreamController._add (dart:async/stream_controller.dart:648:7)
#20     _StreamController.add (dart:async/stream_controller.dart:596:5)
#21     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
#22     _rootRunUnary (dart:async/zone.dart:1434:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
```
```
[✓] Flutter (Channel stable, 3.0.4, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 3.0.4 at /Users/yoyo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/yoyo/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 4E7A103D-B68F-4FEC-BAA0-5505163A7F6B • ios        • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64 • macOS 11.4 20F71 darwin-x64

[!] HTTP Host Availability
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: Failed to connect to host in 10 seconds
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: Failed to connect to host in 10 seconds

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 85684f9300908116a78138ea4c6036c35c9a1236

**Comment by Titanium2099** [comment]
running `flutter clean` fixes it.
