### ISSUE TITLE
Video Record Failed on some Devices when set >=veryHigh. The ResolutionPreset is not auto-downgrade to a proper one

### ISSUE THREAD

**Issue by JmyW** [flutter/flutter#107980]
Looks like old issue but still appear.
I set ResolutionPreset.veryHigh. The takePicture() is working fine but RecordVideo() is "freeze". I'm using the latest version 0.10.0. It can be reproduced easily with example code (https://github.com/flutter/plugins/tree/main/packages/camera/camera). And just like a lot of discussions mentioned the ResolutionPreset.medium may make it work, me too. I set high and medium, they both works. From LogCat, I found a message "Surface with size (w=1920, h=1080) and format 0x1 is not valid, size not in valid set: [1440x1080, 1280x960, 1088x1088, 1280x720, 960x540, 720x480, 640x480, 352x288, 320x240, 176x144]". Looks like the setting "veryHigh" is asking 1920x1080, it's out of what the camera supportable resolution then failed. In "resolution_preset.dart", that said "If a preset is not available on the camera being used a preset of lower quality will be selected automatically.", but not really happen. It's just generating failure. Could team review again whether the "automatic selection" can really work to resolve it? Thanks!

**[Device] Oppo A79
[OS] Android 7.1.1
[Code] Camera 0.10.0 example (https://github.com/flutter/plugins/tree/main/packages/camera/camera)
[Camera] Both front and back camera failed
[Symptom] Freeze when startRecordVideo(). If do stopRecordVideo(), the file size is 0 byte.
[Pass] ResolutionPreset.high, ResolutionPreset.medium, ResolutionPreset.low
[Fail] ResolutionPreset.veryHigh, ResolutionPreset.ultraHigh, ResolutionPreset.max**

My flutter doctor:
C:\src\flutter\bin\flutter.bat doctor --verbose
Flutter assets will be downloaded from https://storage.flutter-io.cn/. Make sure you trust this source!
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.739], locale zh-TW)
• Flutter version 2.10.3 at C:\src\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 7e9793dee1 (5 months ago), 2022-03-02 11:23:12 -0600
• Engine revision bd539267b4
• Dart version 2.16.1
• DevTools version 2.9.2
• Pub download mirror https://pub.flutter-io.cn/
• Flutter download mirror https://storage.flutter-io.cn/

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
• Android SDK at C:\Users\Jemmy_Wu\AppData\Local\Android\Sdk
• Platform android-33, build-tools 31.0.0
• ANDROID_HOME = C:\Users\Jemmy_Wu\AppData\Local\Android\Sdk
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
• Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
• Visual Studio Community 2019 version 16.10.31321.278
• Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
• OPPO A79 (mobile) • S4NZ9L7HWG6SSC8P • android-arm64 • Android 7.1.1 (API 25)
• Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.22000.739]
• Chrome (web) • chrome • web-javascript • Google Chrome 103.0.5060.66
• Edge (web) • edge • web-javascript • Microsoft Edge 103.0.1264.62

[√] HTTP Host Availability
• All required HTTP hosts are available

• No issues found!
Process finished with exit code 0

**Comment by huycozy** [comment]
Hi @JmyW 
I can not reproduce the issue on the latest `stable` and `master` channels with [sample code](https://github.com/flutter/plugins/tree/main/packages/camera/camera_android/example)
I tested with `veryHigh`, `ultraHigh` and `max` on `Samsung Galaxy Tab A7 Lite Android 11`. It can record video normally.

<details>
<summary>Demo</summary>

| veryHigh | ultraHigh | max |
| --------------- | --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/179961320-ba6d7555-76f1-4b2e-8869-62d24fcd4bcf.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/179961358-44c0918d-d453-4d3a-b4bb-b240f5d9f5b3.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/179961375-72054a4f-f7e4-456e-b5f6-7657cfb658ef.mp4"/>

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1751, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1751 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e56047a62c (14 minutes ago), 2022-07-19 23:17:05 -0400
    • Engine revision d9ba4345fc
    • Dart version 2.19.0 (build 2.19.0-12.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Are there any exception logs? Could you please provide it so that we may verify this?

As far as I can see, you are using the old Flutter version `2.10.3`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please try upgrading them and retry to see if this issue still reproduces.

Also, is this issue only reproducible on your device? Does it happen on another device?

**Comment by JmyW** [comment]
@huycozy Thanks for prompt feedback.
It's device depends. I have several phones on hand. 
- The two old HTC (android 6.0) works
- A new phone "Vivo Y52 (android 12)" also works
- An old phone "Oppo A57 (android 6.0.1)" also works
*** Only failed on the "Oppo A79 (android 7.1.1) , sounds like you don't have this device.

I'm trying on emulator, so far so good. Keep trying, hopefully find another one for easily reproducing issue.

**Comment by huycozy** [comment]
Hi @JmyW 
Could you provide exception logs on `Oppo A79 (android 7.1.1)`?
Also, please try upgrading Flutter SDK and retry to see if this issue still reproduces.

**Comment by JmyW** [comment]
Hopefully the log provides some helpful information.

BTW, I tested most of versions of Android, found:
1. Android 12: work and the view can move during recording (view moving by press shift+arrowKey)
2. Android 11: work and the view can move during recording
3. Android 10: work and the view can move during recording
4. **Android 8.0**: work but the view is **frozen** during recording. But finally still has the mp4 file in storage although it's froze video.
5. **Android 7.1.1**: work but the view is **frozen** during recording. But finally still has the mp4 file in storage although it's froze video.

In my case, the view of Oppo A79 is froze with 0 bytes mp4 file. It's even worse than Android 8.0/7.1.1 emulators. But maybe referable or relative.

**Comment by huycozy** [comment]
@JmyW thanks for providing information. Labeling the issue for further investigation from the team!

**Comment by anchaoLu** [comment]
Same problem on "vivo x21 UD A"

**Comment by anchaoLu** [comment]
On this issue, I found some interesting operations on "vivo x21 UD A"：
this code in camera_android-0.10.0+1
```java
  // path : /android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java 
  /**
   * Gets the best possible {@link android.media.CamcorderProfile} for the supplied {@link
   * ResolutionPreset}. Supports SDK < 31.
   *
   * @param cameraId Camera identifier which indicates the device's camera for which to select a
   *     {@link android.media.CamcorderProfile}.
   * @param preset The {@link ResolutionPreset} for which is to be translated to a {@link
   *     android.media.CamcorderProfile}.
   * @return The best possible {@link android.media.CamcorderProfile} that matches the supplied
   *     {@link ResolutionPreset}.
   */
  public static CamcorderProfile getBestAvailableCamcorderProfileForResolutionPresetLegacy(
      int cameraId, ResolutionPreset preset) {
    if (cameraId < 0) {
      throw new AssertionError(
          "getBestAvailableCamcorderProfileForResolutionPreset can only be used with valid (>=0) camera identifiers.");
    }

    switch (preset) {
        // All of these cases deliberately fall through to get the best available profile.
      case max:
        if (CamcorderProfile.hasProfile(cameraId, CamcorderProfile.QUALITY_HIGH)) {
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_HIGH);
        }
      case ultraHigh:
        if (CamcorderProfile.hasProfile(cameraId, CamcorderProfile.QUALITY_2160P)) {
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_2160P);
        }
      case veryHigh:
        if (CamcorderProfile.hasProfile(cameraId, CamcorderProfile.QUALITY_1080P)) {
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_1080P);
        }
      case high:
        if (CamcorderProfile.hasProfile(cameraId, CamcorderProfile.QUALITY_720P)) {
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_720P);
        }
      case medium:
        if (CamcorderProfile.hasProfile(cameraId, CamcorderProfile.QUALITY_480P)) {
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);
        }
      case low:
        if (CamcorderProfile.hasProfile(cameraId, CamcorderProfile.QUALITY_QVGA)) {
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_QVGA);
        }
      default:
        if (CamcorderProfile.hasProfile(cameraId, CamcorderProfile.QUALITY_LOW)) {
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_LOW);
        } else {
          throw new IllegalArgumentException(
              "No capture session available for current capture session.");
        }
    }
  }
```
this line return true
```java
case veryHigh:
        if (CamcorderProfile.hasProfile(cameraId, CamcorderProfile.QUALITY_1080P)) {
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_1080P);
        }
```
However, "vivo x21 UD A" doesn't actually support 1920x1080
"vivo x21 UD A" valid set: [1440x1080, 1280x960, 1280x720, 1024x768, 960x540, 800x480, 720x480, 768x432, 640x480, 384x288, 352x288, 320x240, 176x144]

Maybe on "vivo x21 UD A"：veryHigh means 1440x1080 ???

**Comment by zbs-ha** [comment]
I have the same problem

**Comment by m1n093** [comment]
the same problem on Asus ZenFone 3 Max

**Comment by bungabear** [comment]
I have same problem

[Device] Galaxy A52s 
[OS] Android 13
[Code] Camera 0.10.5+2 example 
[Camera] Back only tested
[Symptom] startRecordVideo() fail, if resolution setting over high.
[Pass] ResolutionPreset.medium, ResolutionPreset.low
[Fail] ResolutionPreset.high, ResolutionPreset.veryHigh, ResolutionPreset.ultraHigh, ResolutionPreset.max

succss log at `medium`
```
I/Camera  (18291): prepareMediaRecorder
I/MediaRecorderJNI(18291): release
D/MediaRecorder(18291): Constructor MediaRecorder
I/MediaRecorderJNI(18291): setup
I/MediaRecorderJNI(18291): setAudioSource(1)
I/MediaRecorderJNI(18291): setVideoSource(2)
I/MediaRecorderJNI(18291): setAudioEncoder(3)
I/MediaRecorderJNI(18291): setParameter(), params: audio-param-encoding-bitrate=256000
I/MediaRecorderJNI(18291): setParameter(), params: audio-param-sampling-rate=48000
I/MediaRecorderJNI(18291): setVideoEncoder(2)
I/MediaRecorderJNI(18291): setParameter(), params: video-param-encoding-bitrate=3449000
I/MediaRecorderJNI(18291): setVideoFrameRate(30)
I/MediaRecorderJNI(18291): setVideoSize(720, 480)
I/MediaRecorderJNI(18291): setParameter(), params: video-param-rotation-angle-degrees=90
I/MediaRecorderJNI(18291): setOutputFile
I/MediaRecorderJNI(18291): prepare
I/MediaRecorder(18291): prepare elapsed time : 177 ms
I/MediaRecorderJNI(18291): getSurface
I/CameraManagerGlobal(18291): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.***.***API Level 2
W/om.***.***(18291): Long monitor contention with owner main (18291) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1402) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 579ms
I/Camera  (18291): CameraCaptureSession onConfigured
I/Camera  (18291): Updating builder settings
W/om.***.***(18291): Long monitor contention with owner main (18291) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1402) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative, android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 577ms
D/Camera  (18291): Updating builder with feature: ExposureLockFeature
D/Camera  (18291): Updating builder with feature: ExposurePointFeature
D/Camera  (18291): Updating builder with feature: ZoomLevelFeature
D/Camera  (18291): Updating builder with feature: AutoFocusFeature
D/Camera  (18291): Updating builder with feature: NoiseReductionFeature
I/Camera  (18291): updateNoiseReduction | currentSetting: fast
D/Camera  (18291): Updating builder with feature: FocusPointFeature
D/Camera  (18291): Updating builder with feature: ResolutionFeature
D/Camera  (18291): Updating builder with feature: SensorOrientationFeature
D/Camera  (18291): Updating builder with feature: FlashFeature
D/Camera  (18291): Updating builder with feature: ExposureOffsetFeature
D/Camera  (18291): Updating builder with feature: FpsRangeFeature
I/Camera  (18291): refreshPreviewCaptureSession
I/CameraManagerGlobal(18291): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.***.app API Level 2
I/MediaRecorderJNI(18291): start
```

error log at `high`
```
I/Camera  (18291): prepareMediaRecorder
D/MediaRecorder(18291): Constructor MediaRecorder
I/MediaRecorderJNI(18291): setup
I/MediaRecorderJNI(18291): setAudioSource(1)
I/MediaRecorderJNI(18291): setVideoSource(2)
I/MediaRecorderJNI(18291): setAudioEncoder(3)
I/MediaRecorderJNI(18291): setParameter(), params: audio-param-encoding-bitrate=256000
I/MediaRecorderJNI(18291): setParameter(), params: audio-param-sampling-rate=48000
I/MediaRecorderJNI(18291): setVideoEncoder(2)
I/MediaRecorderJNI(18291): setParameter(), params: video-param-encoding-bitrate=48000000
I/MediaRecorderJNI(18291): setVideoFrameRate(30)
I/MediaRecorderJNI(18291): setVideoSize(3840, 2160)
I/MediaRecorderJNI(18291): setParameter(), params: video-param-rotation-angle-degrees=90
I/MediaRecorderJNI(18291): setOutputFile
I/MediaRecorderJNI(18291): prepare
E/MediaRecorder(18291): prepare failed: -12
E/MethodChannel#plugins.flutter.io/camera_android(18291): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera_android(18291): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.MediaRecorder.getSurface()' on a null object reference
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at io.flutter.plugins.camera.Camera.startCapture(Camera.java:540)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at io.flutter.plugins.camera.Camera.startVideoRecording(Camera.java:772)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:122)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#plugins.flutter.io/camera_android(18291): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/flutter (18291): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(videoRecordingFailed, prepare failed:-12)
E/flutter (18291): #0      CameraController.startVideoRecording (package:camera/src/camera_controller.dart:538:7)
E/flutter (18291): <asynchronous suspension>
E/flutter (18291): #1      _CameraRecordPageState._recordVideo (package:***/page/camera/camera_record_page.dart:94:7)
E/flutter (18291): <asynchronous suspension>
E/flutter (18291): 
E/DartMessenger(18291): Uncaught exception in binary message listener
E/DartMessenger(18291): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(18291): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/DartMessenger(18291): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:278)
E/DartMessenger(18291): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(18291): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/DartMessenger(18291): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(18291): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger(18291): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(18291): 	at android.os.Looper.loopOnce(Looper.java:226)
E/DartMessenger(18291): 	at android.os.Looper.loop(Looper.java:313)
E/DartMessenger(18291): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/DartMessenger(18291): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(18291): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/DartMessenger(18291): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/MediaRecorderJNI(18291): finalize
I/MediaRecorderJNI(18291): release
I/MediaRecorderJNI(18291): finalize
I/MediaRecorderJNI(18291): release

```

**Comment by jellynoone** [comment]
Experiencing the same problem on a Pixel 1 (Android version 10).
When using the **BACK** camera to record a video at `ResolutionPreset.max` the video recording preview freezes and only captures a frame every so often. The recorded video is the same in that it only shows a few frames.

The interesting bit is that using the **FRONT** camera, everything works as expected. The video recording goes through smoothly.

I can reproduce this behaviour, with a Pixel 1, using the camera example app with one minor modification, setting the line: 
https://github.com/flutter/packages/blob/e578a16580c725d774319076e7e81c6528ca7e35/packages/camera/camera/example/lib/main.dart#L634
from:
```dart
      kIsWeb ? ResolutionPreset.max : ResolutionPreset.medium,
```
to:
```dart
      ResolutionPreset.max,
```

**Comment by jellynoone** [comment]
After additional research I found a [StackOverflow question](https://stackoverflow.com/questions/56342378/camcorderprofile-videocodec-returning-wrong-value) which may be related in relation to the `CamcorderProfile.hasProfile` method the plugin uses to check if a given resolution is supported.

Essentially, as far as I understand it. `CamcorderProfile.hasProfile` may return true for unsupported resolutions in certain situations. [The Android docs, confirm this](https://developer.android.com/reference/android/media/CamcorderProfile#hasProfile(int,%20int)).

I'm not an Android developer myself so I don't known if the plugin implements the checking correctly to work on all devices. But these failures being experienced suggests, more validation might need to be performed before choosing a CamcorderProfile.

**Comment by darshankawar** [comment]
Revisiting this issue, below are the list of affected device mentioned in above thread along with current status of each:

Oppo A79 - available, rest of below devices have been discontinued per gsmarena:
vivo x21 UD A, Samsung Galaxy J2 Prime, Asus ZenFone 3 Max and Pixel 1

@JmyW If you still have the affected device, I suggest you to reverify the reported behavior using latest stable sdk (3.38.4) and latest camera plugin  [version](https://pub.dev/packages/camera) which makes use of https://pub.dev/packages/camera_android_camerax that is built for android implementation of plugin using cameraX library and has undergone lot of updates, so check using this config if it still persist or not.
