### ISSUE TITLE
[mac + codesign] m2crypto error when applying salt state

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#108059]
```
----------

          ID: m2crypto

    Function: pip.installed

        Name: m2crypto == 0.36.0

      Result: False

     Comment: Failed to install packages: m2crypto == 0.36.0. Error: Collecting m2crypto==0.36.0

                Downloading M2Crypto-0.36.0.tar.gz (1.1 MB)

                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 22.6 MB/s eta 0:00:00

                Preparing metadata (setup.py): started

                Preparing metadata (setup.py): finished with status 'done'

              Building wheels for collected packages: m2crypto

                Building wheel for m2crypto (setup.py): started

                Building wheel for m2crypto (setup.py): finished with status 'error'

                Running setup.py clean for m2crypto

              Failed to build m2crypto

              Installing collected packages: m2crypto

                Running setup.py install for m2crypto: started

                Running setup.py install for m2crypto: finished with status 'error' WARNING: The directory '/Users/flutter/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

                error: subprocess-exited-with-error

                

                × python setup.py bdist_wheel did not run successfully.

                │ exit code: 1

                ╰─> [55 lines of output]

                    /private/tmp/pip-install-oc2pdpm1/m2crypto_bdf605cdf95e448296aeca2ba1870cc2/setup.py:294: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

                      return StrictVersion(ver_str) >= StrictVersion(req_ver)

                    running bdist_wheel

                    running build

                    running build_py

                    copying M2Crypto/callback.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/EVP.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/AuthCookie.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/ftpslib.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/EC.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/httpslib.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/X509.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/util.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/RSA.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/BIO.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/DH.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/threading.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/Rand.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/SMIME.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/Engine.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2xmlrpclib.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/RC4.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2urllib2.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/DSA.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/six.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2urllib.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/BN.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2crypto.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/Err.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/ASN1.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    creating build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/cb.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Session.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/timeout.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Cipher.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Connection.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Context.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/SSLServer.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Checker.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    running build_ext

                    building 'M2Crypto._m2crypto' extension

                    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c

                    swig -python -py3 -I/opt/salt/.pyenv/versions/3.7.12/include/python3.7m -I/usr/include/openssl -I/usr/local/include -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include "-I/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks (framework directory)" -I/usr/local/include -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include "-I/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks (framework directory)" -includeall -modern -builtin -outdir /private/tmp/pip-install-oc2pdpm1/m2crypto_bdf605cdf95e448296aeca2ba1870cc2/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i

                    Deprecated command line option: -modern. This option is now always on.

                    SWIG/_m2crypto.i:62: Error: Unable to find 'openssl/opensslv.h'

                    SWIG/_m2crypto.i:68: Error: Unable to find 'openssl/safestack.h'

                    SWIG/_evp.i:12: Error: Unable to find 'openssl/opensslconf.h'

                    SWIG/_rc4.i:5: Error: Unable to find 'openssl/opensslconf.h'

                    SWIG/_ec.i:7: Error: Unable to find 'openssl/opensslconf.h'

                    error: command '/usr/local/bin/swig' failed with exit code 1

                    [end of output]

                

                note: This error originates from a subprocess, and is likely not a problem with pip.

                ERROR: Failed building wheel for m2crypto

                error: subprocess-exited-with-error

                

                × Running setup.py install for m2crypto did not run successfully.

                │ exit code: 1

                ╰─> [60 lines of output]

                    /private/tmp/pip-install-oc2pdpm1/m2crypto_bdf605cdf95e448296aeca2ba1870cc2/setup.py:294: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

                      return StrictVersion(ver_str) >= StrictVersion(req_ver)

                    running install

                    /opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.

                      setuptools.SetuptoolsDeprecationWarning,

                    running build

                    running build_py

                    creating build

                    creating build/lib.macosx-10.15-x86_64-cpython-37

                    creating build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/callback.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/EVP.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/AuthCookie.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/ftpslib.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/EC.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/httpslib.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/X509.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/util.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/RSA.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/BIO.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/DH.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/threading.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/Rand.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/SMIME.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/Engine.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2xmlrpclib.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/RC4.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2urllib2.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/DSA.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/six.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2urllib.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/BN.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/m2crypto.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/Err.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    copying M2Crypto/ASN1.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto

                    creating build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/cb.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Session.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/timeout.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Cipher.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Connection.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Context.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/SSLServer.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    copying M2Crypto/SSL/Checker.py -> build/lib.macosx-10.15-x86_64-cpython-37/M2Crypto/SSL

                    running build_ext

                    building 'M2Crypto._m2crypto' extension

                    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c

                    swig -python -py3 -I/opt/salt/.pyenv/versions/3.7.12/include/python3.7m -I/usr/include/openssl -I/usr/local/include -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include "-I/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks (framework directory)" -I/usr/local/include -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include "-I/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks (framework directory)" -includeall -modern -builtin -outdir /private/tmp/pip-install-oc2pdpm1/m2crypto_bdf605cdf95e448296aeca2ba1870cc2/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i

                    Deprecated command line option: -modern. This option is now always on.

                    SWIG/_m2crypto.i:62: Error: Unable to find 'openssl/opensslv.h'

                    SWIG/_m2crypto.i:68: Error: Unable to find 'openssl/safestack.h'

                    SWIG/_evp.i:12: Error: Unable to find 'openssl/opensslconf.h'

                    SWIG/_rc4.i:5: Error: Unable to find 'openssl/opensslconf.h'

                    SWIG/_ec.i:7: Error: Unable to find 'openssl/opensslconf.h'

                    error: command '/usr/local/bin/swig' failed with exit code 1

                    [end of output]

                

                note: This error originates from a subprocess, and is likely not a problem with pip.

              error: legacy-install-failure

              

              × Encountered error while trying to install package.

              ╰─> m2crypto

              

              note: This is an issue with the package mentioned above, not pip.

              hint: See above for output from the failure.

     Started: 14:30:02.008339

    Duration: 5671.112 ms

     Changes:   
```

**Comment by XilaiZhang** [comment]
This happens on provisioned mac code sign machine, even after the machine's disk has been entirely wiped out. As Yusuf pointed out this could be affecting all the mac machines.

**Comment by XilaiZhang** [comment]
cc @yusuf-goog

**Comment by yusuf-goog** [comment]
When setting up a new macOS bot, we encountered the above issues. These procedures were used successfully to bring up machines a few weeks ago.

The only difference, is that today we needed to rev the salt minion package version to atleast 3002.8, because older packages have been removed from the salt site.

It is unknown if the newer minion version has some issues working with opensll/m2crypto that the previous version did not.

We tried a number of things, including manually installing the m2crypto lib via:

```
$ brew install openssl
$ pip install --global-option=build_ext --global-option="-I/usr/local/opt/openssl/include" m2crypto
```
This seemed to install version m2crypto==0.38 successfully (0.36 is what is specified via our current salt states, and that fails to install).

After it was installed, we are still unable to import m2crypto:
```
>>> import M2Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/flutter/.local/lib/python3.7/site-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/Users/flutter/.local/lib/python3.7/site-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, six
  File "/Users/flutter/.local/lib/python3.7/site-packages/M2Crypto/BIO.py", line 11, in <module>
    from M2Crypto import m2, six
  File "/Users/flutter/.local/lib/python3.7/site-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto.m2crypto import *
  File "/Users/flutter/.local/lib/python3.7/site-packages/M2Crypto/m2crypto.py", line 13, in <module>
    from ._m2crypto import *
ImportError: dlopen(/Users/flutter/.local/lib/python3.7/site-packages/M2Crypto/_m2crypto.cpython-37m-darwin.so, 0x0002): symbol not found in flat namespace '_EVP_CIPHER_CTX_get_block_size'
```

**Comment by yusuf-goog** [comment]
It is uncertain the impact of any issues with versions/dependencies on our existing fleet, since some of these states don't get applied if the packages are already installed. We may encounter problems if the states need to be applied on our existing fleet and the updates break our current bots.

**Comment by yusuf-goog** [comment]
Tried installing m2crypto via:
```brew install openssl@1.1

env LDFLAGS="-L$(brew --prefix openssl@1.1)/lib" \
CFLAGS="-I$(brew --prefix openssl@1.1)/include" \
SWIG_FEATURES="-cpperraswarn -includeall -I$(brew --prefix openssl@1.1)/include" \
pip install m2crypto```

and it seems to allow us to import m2crypto correctly.

**Comment by yusuf-goog** [comment]
If we modify the salt state to allow using 0.38 instead of 0.36, then all the states seems to run successfully. This atleast mitigates possible critical issue with not being able to deploy new hosts.

**Comment by XilaiZhang** [comment]
As Yusuf pointed out, https://github.com/flutter/flutter/issues/108059#issuecomment-1190872254 would fix everything except the cron job. To fix the cron job, we go to system preferences -> security -> and grant full disk access to terminal. this would help `Sudo salt-call state.apply` to succeed

**Comment by XilaiZhang** [comment]
as verified, SSL1.1 would work with either 0.36 or 0.38, so we don't have to upgrade the other mac machines. As a next step, we will figure out how to install openssl from the provision script, instead of manually install it

**Comment by XilaiZhang** [comment]
Appended the openssl 1.1 and env flags after provision script and it worked. state-apply worked as well.

**Comment by XilaiZhang** [comment]
I will try to move openssl installation block into salt state

**Comment by godofredoc** [comment]
This was fixed by running the following command at provisioning time.

```
env LDFLAGS="-L$(brew --prefix openssl@1.1)/lib" \
CFLAGS="-I$(brew --prefix openssl@1.1)/include" \
SWIG_FEATURES="-cpperraswarn -includeall -I$(brew --prefix openssl@1.1)/include" \
/opt/salt/bin/pip install m2crypto==0.36.0
```

**Comment by godofredoc** [comment]
@ricardoamador is this something we can add to the documentation?

**Comment by ricardoamador** [comment]
Yes. It was added to the steps to ensure the minion is picked up automatically.

**Comment by godofredoc** [comment]
Perfect then closing this bug! thanks Ricardo
