### ISSUE TITLE
[iOS] cursor position error and unexpected char was deleted after long press the space key to move the cursor to the middle

### ISSUE THREAD

**Issue by jiangkang** [flutter/flutter#108016]
https://user-images.githubusercontent.com/12570868/180020978-b7f2269e-4c89-4a8d-b301-a3d48facc556.mp4

## Steps to Reproduce
1. Use iOS to input some Chinese，not choose the exact word；
2. long press the space key to move the cursor pos, to the first or the any position of middle;
3. press the backspace to delete char

**Expected results:** 
delete the char before the position of the cursor

**Actual results:** 
the end char was deleted ,and the cursor position jump to the end

<details>
Demo code:
```dart
Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: const Text("Demo Page"),
      ),
      body: Center(
        child: Column(
          children: const [
            TextField(),
          ],
        ),
      ),
    )
```

</details>

flutter doctor:
```
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (7 天前) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.69.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

**Comment by maheshmnj** [comment]
Hi @jiangkang, Thanks for filing the issue. I am able to reproduce the issue on the latest stable and the master channel. The cursor jumps to end when it has been moved using the space key. I also see a typecase exception when moving the caret.

https://user-images.githubusercontent.com/31410839/180173179-91c5cde8-424b-40c6-9560-36c9292c6628.mov

This issue occurs only the with Chinese language and works fine with English

<details>
<summary>logs</summary>

```
Performing hot restart...                                               
Restarted application in 677ms.

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following _CastError was thrown during method call TextInputClient.updateFloatingCursor:
type 'int' is not a subtype of type 'double' in type cast

When the exception was thrown, this was the stack:
#0      _toTextPoint (package:flutter/src/services/text_input.dart:1516:51)
#1      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1830:58)
#2      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1704:20)
#3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:536:55)
#4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529:34)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#6      _invoke2 (dart:ui/hooks.dart:186:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)

call:
  MethodCall(TextInputClient.updateFloatingCursor, [1, FloatingCursorDragState.update, {X:
  -0.3348251229786763, Y: 0}])
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: type 'int' is not a subtype of type 'double' in type cast

Another exception was thrown: type 'int' is not a subtype of type 'double' in type cast

Another exception was thrown: type 'int' is not a subtype of type 'double' in type cast

```
</details>

**Comment by jiangkang** [comment]
keep it active😂

**Comment by jiangkang** [comment]
> cc: @LongCatIsLooong

Is there any progress on this issue? @LongCatIsLooong @maheshmnj

**Comment by maheshmnj** [comment]
@jiangkang There are no updates so far, This issue is waiting to be prioritized.

**Comment by jiangkang** [comment]
Is there any progress on this issue? @maheshmnj  @LongCatIsLooong

**Comment by demoYang** [comment]
same to me , i get a exception 
```
flutter: [exception: type 'int' is not a subtype of type 'double' in type cast]
flutter: [library: Flutter framework]
flutter: [stack: #0      _toTextPoint
package:flutter/…/services/text_input.dart:1513
flutter: #1      TextInput._handleTextInputInvocation
package:flutter/…/services/text_input.dart:1827
flutter: #2      TextInput._loudlyHandleTextInputInvocation
package:flutter/…/services/text_input.dart:1701
flutter: #3      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:536
flutter: #4      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:529
flutter: #5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:387
flutter: #6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
flutter: #7      _rootRun (dart:async/zone.dart:1391:13)
flutter: #8      _CustomZone.run (dart:async/zone.dart:1293:19)
flutter: #9      _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
flutter: #10     _invoke2 (dart:ui/hooks.dart:188:10)
flutter: #11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
flutter: #12     _Channel.push (dart:ui/channel_buffers.dart:132:31)
flutter: #13     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
flutter: #14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
flutter: #15     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
flutter: ]

```
flutter version: 3.3.7 

https://user-images.githubusercontent.com/7134823/209527989-1c987c36-c754-4687-a38b-b955e2195fd2.MP4

**Comment by gnprice** [comment]
From experimenting with this a bit:
* The issue is not specific to the delete key. If you type additional letters they appear at the end of the region, just like if you hit the delete key the deletion happens at the end.

  So in short it seems that after you try to move the cursor to the middle, the platform text input plugin is continuing to consider the cursor to be at the end, even though the framework is painting it in the middle. Effectively it's not possible to move the cursor to another spot within the composing region.

* The issue appears not only if you long-press the space bar to move the cursor, but also if you tap in the middle of the text field to place the cursor.

* On the other hand, the issue does *not* appear if you move the cursor outside of the composing region. It only happens if the place you try to put the cursor is somewhere inside the composing region (including the start of the region.)

  If you move the cursor outside the composing region (either via long-pressing space, or by tapping in the text field to place the cursor), then composing ends and your cursor goes where you put it, and works normally there.

  * This is much better, but also differs from native behavior. In a native iOS text input, if you try to move the cursor outside the composing region, you can't — it will stay within the region. For example, if you long-press space and drag the cursor far to the right, it will go along while you're dragging it, but when you release the drag it will snap back to the end of the region.

    This native behavior seems quite helpful. It makes it easy to go quickly back to the end of the composing region after you've gone back to the middle to correct something: you just drag hastily to the right, with no need for precision, and it goes exactly where you want.

* The issue affects the Japanese kana keyboard in the same way as the Chinese pinyin keyboard.

* The issue does not affect Android. There, something different happens. I'll look to see if there's an existing issue for that, and if not then file one.

My experiments were with the current Flutter main/master channel, on an iPhone 7 with iOS 15.

**Comment by gnprice** [comment]
@demoYang: That appears to be a case of an unrelated issue #109632, which was fixed by #109635. If you're still seeing it, please file a separate issue and fill out the information in the issue template, so that it can be addressed.

**Comment by LongCatIsLooong** [comment]
I created a UIKit app with a custom `UITextInput` and I was able to reproduce the same bug. I'm not aware of any other methods that are supposed to be called after changing the selection to notify the keyboard, other than `selectionDidChange`.

This works in `UITextField` and `UITextView` so maybe there's a secret method we need to call after setting the selection.

**Comment by LongCatIsLooong** [comment]
Radar filed. If you happen to know which methods a custom UITextInput implementation needs to call after changing the selection in marked text feel free to leave a comment / submit a patch. Thank you!
