### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /Users/gv/AndroidStudioProjects/MVP-Flutter/android/gradlew, OS error code: 2

### ISSUE THREAD

**Issue by git-jkumar** [flutter/flutter#108087]
## Command
```
flutter --no-color build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: /Users/gv/AndroidStudioProjects/MVP-Flutter/android/gradlew, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:424:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:443:35)
#8      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:382:38)
#9      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:11)
#10     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:109:27)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[!] Flutter (Channel unknown, 3.1.0-0.0.pre.1503, on macOS 11.6.7 20G630 darwin-x64, locale en-IN)
    ! Flutter version 3.1.0-0.0.pre.1503 on channel unknown at /Users/gv/flutter
    ! Upstream repository unknown
    • Framework revision d7bacf9b3f (2 weeks ago), 2022-07-05 05:14:08 -0400
    • Engine revision c49de3fc08
    • Dart version 2.18.0 (build 2.18.0-254.0.dev)
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/gv/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/gv/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)
    • macOS (desktop)                  • macos         • darwin-x64  • macOS 11.6.7 20G630 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
firebase_auth-3.4.2
firebase_auth_web-4.0.0
firebase_core-1.19.2
firebase_core_web-1.7.0
firebase_messaging-10.0.9
firebase_messaging_web-2.4.4
fluttertoast-8.0.9

**Comment by git-jkumar** [comment]
> Hi @git-jkumar, can you check if the `gradlew` file exists in the `android` directory?

Yes. It does.

**Comment by danagbemava-nc** [comment]
Thanks. 

Labeling for further investigation as I can't find any existing issues.

**Comment by stuartmorgan** [comment]
Does this happen with every project you create, or is it specific to this one?

**Comment by Frankdroid7** [comment]
I'm experiencing this right now for a new flutter project I cloned.
