### ISSUE TITLE
[macOS] Asserts on scrolling using trackpad

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#108176]
Similar to https://github.com/flutter/flutter/issues/107962 which got fixed in https://github.com/flutter/flutter/pull/108116 but there appear to be more failing cases.

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Scroll the ListView back and forth using trackpad a bunch of times

**Expected results:** scrolling works every time, no asserts

**Actual results:** asserts are seen:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/gestures/events.dart': Failed assertion: line 1721 pos 15: '!identical(kind, PointerDeviceKind.trackpad)': is not true.
package:flutter/…/gestures/events.dart:1721
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      new PointerSignalEvent
package:flutter/…/gestures/events.dart:1721
#3      new _PointerScrollInertiaCancelEvent&PointerSignalEvent&_PointerEventDescription (package:flutter/src/gestures/events.dart)
package:flutter/…/gestures/events.dart:1
#4      new _PointerScrollInertiaCancelEvent&PointerSignalEvent&_PointerEventDescription&_CopyPointerScrollInertiaCancelEvent (package:flutter/src/gestures/events.dart)
package:flutter/…/gestures/events.dart:1
#5      new PointerScrollInertiaCancelEvent (package:flutter/src/gestures/events.dart)
package:flutter/…/gestures/events.dart:1
#6      PointerEventConverter.expand.<anonymous closure>
package:flutter/…/gestures/converter.dart:263
#7      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#8      ListQueue.addAll (dart:collection/queue.dart:748:25)
#9      GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:293
#10     _invoke1 (dart:ui/hooks.dart:165:13)
#11     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:339:7)
#12     _dispatchPointerDataPacket (dart:ui/hooks.dart:92:31)
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final List<String> items = List<String>.generate(100, (index) => 'item $index');

    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: ListView.builder(
          itemCount: items.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text(items[index]),
              selected: index == 6,
              selectedTileColor: Colors.amber,
            );
          },
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
% flutter doctor -v
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1813, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1813 on channel master at /Library/Frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9ae37030ae (2 hours ago), 2022-07-22 08:58:04 -0700
    • Engine revision 90b25f2ec6
    • Dart version 2.19.0 (build 2.19.0-25.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tgucio/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by dkwingsmt** [comment]
Fixed by https://github.com/flutter/flutter/pull/108190
