### ISSUE TITLE
`Incorrect use of ParentDataWidget` exception may not appear visually in debug mode. 

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#108186]
I think `Column(Padding(Expanded))` should fail in debug mode, because it is ultra hard to debug it is wrong in release mode in a complex layout:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/351125/180503995-48879148-2095-4aa0-a089-2c25c8079186.png">

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(body: Demo()),
    );
  }
}

class Demo extends StatelessWidget {
  const Demo({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: const [
        Padding(
          padding: EdgeInsets.all(16),
          child: Expanded(
            child: Text("This is only shown in debug mode!"),
          ),
        ),
      ],
    );
  }
}
```

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.4 20F71 darwin-x64, locale
    en-BR)
    • Flutter version 3.0.5 at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
```

**Comment by danagbemava-nc** [comment]
Hi @bernaferrari, when I run your code sample, I got the error below in my console. I believe you should get the error below no matter how complex the UI is. 

Is your request for the error screen to be shown in this case in debug mode?

<details>
<summary>logs</summary>

```
Launching lib/main.dart on iPhone 13 Pro Max in debug mode...
Xcode build done.                                           33.5s
Connecting to VM Service at ws://127.0.0.1:49657/EQJyWm2ye1g=/ws

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Padding widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  RichText ← Text ← Expanded ← Padding ← Column ← Demo ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← ⋯
When the exception was thrown, this was the stack
#0      RenderObjectElement._updateParentData.<anonymous closure>
#1      RenderObjectElement._updateParentData
#2      RenderObjectElement.attachRenderObject
#3      RenderObjectElement.mount
#4      MultiChildRenderObjectElement.mount
...     Normal element mounting (16 frames)
#20     Element.inflateWidget
#21     MultiChildRenderObjectElement.inflateWidget
#22     MultiChildRenderObjectElement.mount
...     Normal element mounting (25 frames)
#47     Element.inflateWidget
#48     MultiChildRenderObjectElement.inflateWidget
#49     MultiChildRenderObjectElement.mount
...     Normal element mounting (108 frames)
#157    Element.inflateWidget
#158    MultiChildRenderObjectElement.inflateWidget
#159    MultiChildRenderObjectElement.mount
...     Normal element mounting (175 frames)
#334    Element.inflateWidget
#335    MultiChildRenderObjectElement.inflateWidget
#336    MultiChildRenderObjectElement.mount
...     Normal element mounting (377 frames)
#713    Element.inflateWidget
#714    Element.updateChild
#715    RenderObjectToWidgetElement._rebuild
#716    RenderObjectToWidgetElement.mount
#717    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
#718    BuildOwner.buildScope
#719    RenderObjectToWidgetAdapter.attachToRenderTree
#720    WidgetsBinding.attachRootWidget
#721    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════

```
</details>

**Comment by bernaferrari** [comment]
I get the error, but visually it works and only breaks in release, which is tricky.

**Comment by danagbemava-nc** [comment]
I agree that it's tricky considering this exception is also not caught by the debugger. 

I believe there are some instances where using the incorrect ParentDataWidget may show an exception on the screen, but this seems like one of the corner cases that are not captured. 

I'll therefore be treating this as a bug and labeling for further investigation. 

Reproducible on the latest stable and master. 

Code sample can be found in https://github.com/flutter/flutter/issues/108186#issue-1315318039

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (13 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1865, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1865 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision be14858464 (73 minutes ago), 2022-07-26 01:44:06 -0400
    • Engine revision 8eca26d130
    • Dart version 2.19.0 (build 2.19.0-33.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by iontaroberto** [comment]
I have the same problem. Is it possible to catch this error and handle it with a custom widget?

**Comment by SaraAkwad** [comment]
I faced the same issue, any solution?

**Comment by rsanjuan87** [comment]
It would be useful if some visual mark like a color overlay was added to the component that throws this exception so that it can be visually determined which widget is the one that is defective

**Comment by RoarGronmo** [comment]
Could "lint" flag this error ?

**Comment by markrheeGI** [comment]
The main issue here is that because of this bug what seems to work during development in debug mode suddenly fails in production in release mode. The developers have faith in the Flutter framework to at least render what was rendered in debug mode in release mode as well.

**Comment by lubritto** [comment]
It seems Flutter is ignoring it on purpose to avoid other rendering issues by adding the ErrorWidget, but honestly, the current behavior is leading to misassumptions given in debug mode everything looks ok on the UI. For sure there might be a better way of handling it.

<img width="635" alt="Screenshot 2024-07-15 at 2 14 26 PM" src="https://github.com/user-attachments/assets/3cf0e9dc-b08e-4464-af1a-efec72e56a9c">

**Comment by lubritto** [comment]
@goderbauer @Hixie Is there another way to handle such scenarios in the current state of the framework? Relying on debuggers to catch it is not safe enough. A lint rule maybe? It would prevent people from causing it but still have a bad error report on debug mode if any edge case happens. A bit more context would allow me to contribute here.

**Comment by c-lucera-pvotal** [comment]
Following,  also I want to notice that is not only a UI issue, but the app somehow completely breaks and become non responsive as I pointed in the [duplicated issue](https://github.com/flutter/flutter/issues/151891)

**Comment by Hixie** [comment]
What is the problem it causes in release mode? I would have expected the rendering to be the same in both modes.

**Comment by danagbemava-nc** [comment]
@Hixie, in release/profile mode it typically shows up as a grey screen like the screenshot in https://github.com/flutter/flutter/issues/108186#issue-1315318039.

**Comment by Hixie** [comment]
What exception is reported in the console when you get that?

**Comment by iontaroberto** [comment]
> What exception is reported in the console when you get that?

Only one log line and therefore not very visible: `[ Incorrect use of ParentDataWidget ]`

**Comment by Hixie** [comment]
That's so weird. The only two places in the codebase that I see "Incorrect use of ParentDataWidget" are in asserts, which aren't supposed to be enabled in release builds. Also in both cases the exception is immediately caught, which should mean no exception is available to trigger the grey box failure. Someone will have to try to debug this to figure out what's going on.

**Comment by Hixie** [comment]
Looks like actually the exception in release mode is:
```
flutter: type 'BoxParentData' is not a subtype of type 'FlexParentData' in type cast
flutter: #0      Flexible.applyParentData (package:flutter/src/widgets/basic.dart:5220)
flutter: #1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:6694)
flutter: #2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6735)
flutter: #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6597)
```

**Comment by Hixie** [comment]
The fix is probably to remove the `applyParentData` variable in `_updateParentData` in framework.dart, and just always apply it, even when we know it's going to throw. Or, maybe simpler, just don't catch the error in that assert, just let it throw and get caught by the framework normally. There's a comment there saying that this will likely lead to more confusing errors, but since the current setup is also confusing people, maybe it's worth it.

Should be a relatively straight-forward change to make, if anyone here is motivated to do it. Feel free to reach out on #hackers-new in our discord if you need advice. (Invite link in the contributor docs.)

**Comment by darajava** [comment]
@Hixie Thanks for the pointer - I'm going to attempt a PR for this, having never contributed to a large project before as I believe it's very important and the disparity between debug and release modes is at odds with the rest of Flutter's DX. This issue has caught me out a few times now, causing full or partial outages for my users (and some 1-star reviews) and having to wait anywhere from 4-24 hours for Apple/Google's review process to remediate. 

I am surprised that this issue isn't more popular/critical though—is there something wrong with my workflow in that I am trusting debug mode too much?

**Comment by darajava** [comment]
@iontaroberto I fixed the issue, please check out the PR #155091

**Comment by erlangparasu** [comment]
Got same issue

**Comment by oktajianto** [comment]
this is funny, I have fixed expanded and flexible elements, now in release build it works fine no more grey layout but when I try to debug in localhost it only shows white layout.

**Comment by AndreLuizNogueira** [comment]
[darajava](https://github.com/darajava) tried to fix it, but after hours of work it was closed without merging because the tests didn't satisfy everyone. Come on, we need this fix. Please someone review and merge it.

**Comment by darajava** [comment]
FYI I have run into this issue again, where everything seemed okay in debug mode but I still released to live users where it broke the app for them. Obviously, I should be more careful (and I have been), but something that can be so easily checked by Flutter with as bad consequences as these (caused by logic in an `assert`) should really be fixed.
