### ISSUE TITLE
"setPersistenceEnabled() must be made before any other usage error" thrown after performing full restart

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10821]
## Steps to Reproduce
- Use this plugin, `  firebase_database: "^0.0.7"`
- In the `main` function, do this: `FirebaseDatabase.instance.setPersistenceEnabled(true);`
- Run the app
- Now re-run the app using the little bug icon with the play button
- See that error i described in the title.

## Logs

```
E/flutter (30887): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (30887): PlatformException(error, Calls to setPersistenceEnabled() must be made before any other usage of FirebaseDatabase instance., null)
E/flutter (30887): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514:7)
E/flutter (30887): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
E/flutter (30887): <asynchronous suspension>
E/flutter (30887): #2      FirebaseDatabase.setPersistenceEnabled (package:firebase_database/src/firebase_database.dart:48:21)
E/flutter (30887): #3      main (/data/user/0/com.myapp.app/cache/myapp-flutterV2MhKb/myapp-flutter/lib/main.dart:7:29)
E/flutter (30887): #4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
E/flutter (30887): #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 6965312822 (2 days ago), 2017-06-16 10:05:18 -0700
    • Engine revision 784e975672
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 7.0 (API 24) (emulator)
    • Nexus 5X                  • 0106bcc49c8ca3eb                         • android-arm • Android 7.1.2 (API 25)
    • Kevin's iPhone            • c95c86bdc3aac565adb373de3dc2dbedcdecc900 • ios         • iOS 10.3.1 (14E304)
    • iPhone 5s                 • AB2FA880-541C-49D7-BDB2-9720261982A3     • ios         • iOS 10.3 (simulator)
```

**Comment by eseidelGoogle** [comment]
This looks like an incompatibility between the firebase datastore plugin and hot-restart.  Correct?  FYI @collinjackson @mit-mit

**Comment by lukef** [comment]
This is somewhat to be expected, but it raises an issue generally.

This call can only be made 1x per application launch. We have added this code into the application `main` and it is still being called multiple times per application session (resulting in a crash). It would seem that the solution would be to tell people to add this code into their native workflow?

**Comment by collinjackson** [comment]
I think we should check to see whether the value is the same value that was set previously and if so, allow it. Otherwise, we can return an error to Dart-land saying that changing the value is not allowed. That's a pretty easy fix and should work well for the case where devs just want to always enable or disable it.

**Comment by collinjackson** [comment]
In flutter/plugins#144, I'm catching the exceptions and return true on success and false on failure. This should prevent the app from crashing while still giving the app a way to tell whether the call succeeded.

**Comment by kroikie** [comment]
@KevinTheGray

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/995. Any further collaboration will be done there.
