### ISSUE TITLE
Build tool doesn't allow iOS Simulator Release apps

### ISSUE THREAD

**Issue by electricbolt** [flutter/flutter#108277]
The flutter build tool currently doesn't allow building an iOS Simulator **Release** app, which appears to be an artificial limitation? (unless there are other internal details that I'm unaware of).

The flutter build tool currently allows building both:
- iOS Simulator **Debug** apps, _and_ 
- iOS **Release** XCFrameworks, which contain Simulator and Device binaries.

I have need to distribute iOS Simulator Release app binaries. The workaround for us is to generate an iOS Release XCFramework, then re-package the XCFramework into another app and distribute, but that's effectively twice the work. I'm sure others would like to test their apps in Release mode on the iOS Simulator as well.

### Attempting a build using Flutter build tool

I created an empty iOS only Flutter project:
```bash
flutter create untitled --project-name=untitled --platforms=ios --template=app
```

Then attempt building with the build tool:
```bash
cd untitled
flutter build ios --simulator --release
```

The output is:  
```
Release mode is not supported for simulators.`
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:338:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           ...
```

### Bypassing the build tool, using xcode directly.

The following command is what the build tool does internally to invoke Xcode:
```bash
cd ios    
xcrun xcodebuild -configuration Release VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/Shared/build/untitled/build/ios -sdk iphonesimulator -destination generic/platform=iOS\ Simulator
```

The output is:
```
[   +5 ms] Target aot_assembly_release failed: Exception: release/profile builds are only supported for physical devices. attempted to build for simulator.
           #0      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:73:7)
           #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
           <asynchronous suspension>
           ...
```

At this point I can continue on with a workaround of using the XCFramework option (below) and repacking into another app and using that to distribute, or I could clone flutter and change the build tool to remove the limitations and see how much further the build process goes without the limitations above.

### XCFramework is fine

For completeness, and to show the build tool has the ingredients to make an iOS Simulator Release binary, building an XCFramework in Release mode is fine. This outputs Device and Simulator binaries:
```bash
flutter build ios-framework --release --no-debug --no-profile
```

The output is:
```
      App.xcframework
        ios-arm64_armv7
        ios-arm64_x86_x64-simulator
      Flutter.xcframework
        ios-arm64_armv7
        ios-arm64_x86_x64-simulator
```

**Expected results:** 

Allow `flutter build ios --simulator --release` to generate a iOS Simulator Release app.

**Actual results:** 

<details>
<summary>Code sample</summary>

I created an empty iOS only Flutter project:
```bash
flutter create untitled --project-name=untitled --platforms=ios --template=app
```

</details>

<details>
  <summary>Logs</summary>
```
```

```
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale en-NZ)
    • Flutter version 3.0.1 at /Users/m773271/Documents/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (9 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/m773271/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5787.37

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @electricbolt, there is an existing issue requesting that this limitation be removed being tracked in https://github.com/flutter/flutter/issues/11754. 

Kindly follow up for updates there and please feel free to upvote the issue. 

Closing from here as duplicate. 

Thank you
