### ISSUE TITLE
[tool_crash](OS Error: The system cannot find the  path specified., errno = 3)

### ISSUE THREAD

**Issue by au-top** [flutter/flutter#108311]
It only happens when I develop Android. Windows looks good, new empty project also looks good

He blocked the construction of my vscode, but I can still use 'flutter run'. He doesn't affect my app, but he will make flutter cli crash quickly

# info 

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

```
FileSystemException: FileSystemException: Directory listing failed, path = 
'D:\project\flutterProject\free_message\build\app\intermediates\compressed_assets
\debug\out\assets\flutter_assets\dist\windows\data\flutter_assets\plugins\bitsdojo_window\bitsdojo_window\example\windows\flutter\ephemeral\.plugin_symlinks\bitsdojo_window_windows\*'
 (OS Error: 系统找不到指定的路径。, errno = 3)

#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1041:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:866:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:753:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:261:54)
<asynchronous suspension>
#8      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:447:26)
<asynchronous suspension>
#9      HotRunner.attach (package:flutter_tools/src/run_hot.dart:269:40)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:707:27)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

_translated using Google Translate_ 

```
FileSystemException: FileSystemException: Directory listing failed,
path='D:\project\flutterProject\free_message\build\app\intermediates\compressed_assets\debug\out\assets\flutter_assets\dist\windows\data\flutter_assets\plugins\bitsdojo_window\bitsdojo_window\ 
example\windows\flutter\ephemeral\.plugin_symlinks\bitsdojo_window_windows\*' (OS Error: The system cannot find the 
path specified., errno = 3)

#0 _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1 _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2 ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3 ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4 _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1041:78)
#5 ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:866:37)
#6 ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:753:9)
#7 ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:261:54)
<asynchronous suspension>
#8 HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:447:26)
<asynchronous suspension>
#9 HotRunner.attach (package:flutter_tools/src/run_hot.dart:269:40)
<asynchronous suspension>
#10 RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:707:27)
<asynchronous suspension>
#11 FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#12 AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13 CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14 FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15 AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16 FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#17 run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#18 AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19 main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, 3.1.0-0.0.pre.1846, on Microsoft Windows [版本 10.0.22000.795], locale zh-CN)
    [32m•[39m Flutter version 3.1.0-0.0.pre.1846 on channel master at D:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 72163a8919 (3 hours ago), 2022-07-25 08:03:09 -0700
    [32m•[39m Engine revision daa4263877
    [32m•[39m Dart version 2.19.0 (build 2.19.0-33.0.dev)
    [32m•[39m DevTools version 2.15.0
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    [32m•[39m Android SDK at D:\AndroidSDK
    [32m•[39m Platform android-33, build-tools 32.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    [32m•[39m Visual Studio at D:\VSSDK\IDE
    [32m•[39m Visual Studio Community 2022 version 17.1.32421.90
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2021.2)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.1
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m VS Code (version 1.69.2)
    [32m•[39m VS Code at C:\Users\autop\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.42.0

[32m[✓][39m VS Code (version 1.70.0-insider)
    [32m•[39m VS Code at C:\Users\autop\AppData\Local\Programs\Microsoft VS Code Insiders
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (4 available)
    [32m•[39m DBY W09 (mobile)  • DXQBB21C02222514 • android-arm64  • Android 10 (API 29)
    [32m•[39m Windows (desktop) • windows          • windows-x64    • Microsoft Windows [版本 10.0.22000.795]
    [32m•[39m Chrome (web)      • chrome           • web-javascript • Google Chrome 103.0.5060.134
    [32m•[39m Edge (web)        • edge             • web-javascript • Microsoft Edge 103.0.1264.71

[33m[!][39m HTTP Host Availability
    [31m✗[39m HTTP host "https://cocoapods.org/" is not reachable. Reason: Failed to connect to host in 10 seconds

[33m![39m Doctor found issues in 1 category.
```

**Comment by maheshmnj** [comment]
Hi @au-top, Thanks for filing the issue. 

There is a similar issue describing this case https://github.com/flutter/flutter/issues/108311, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by au-top** [comment]
thanks but this link is to me issues

can you provide a link? Thank you

**Comment by maheshmnj** [comment]
Oops sorry about that Please follow up here https://github.com/flutter/flutter/issues/106953
