### ISSUE TITLE
Enhanced Enum Classes, name keyword, and flutter test --coverage result in a segmentation fault

### ISSUE THREAD

**Issue by tony-ditchlabs** [flutter/flutter#108319]
## Issue Summary
With [Dart Enhanced Enum Classes](https://github.com/dart-lang/language/blob/d16704ae6c9a5fd8f30b7ba9d33a5ab650c7447d/accepted/future-releases/enhanced-enums/feature-specification.md), we can now simply and easily extend an `enum`. An `enum` has a `name` field by default, but we can override that using Enhanced Enum Classes. (though without the `@override` annotation). This compiles, runs, and tests fine, but for some reason, the `--coverage` flag chokes on this and results in a segfault.

As the segfault readout gives no indication on where this error originated from, it's very difficult to track down. Even though this is an edge case, it seems unlikely I'm the first to encounter this issue - just the first to reproduce and report it.

## Workarounds

1. Don't use the `--coverage` flag when running tests. Silly, but it works.
2. Refactor and don't "override" the `name` field, instead opting for something like `title` or `extendedName`.

## Unknowns

I found this issue with the `name` field, but there may be other reserved namespaces that throw similar errors.

## Steps to Reproduce

1. run `fluter create enum_error` to create a new project
4. Add the following code block to the top of main.dart
```dart
enum EnumNameTestFail {
  a("a");

  final String name;
  const EnumNameTestFail(this.name);
}
```
5. In the terminal, run `flutter test`
6. In the terminal, run `flutter test --coverage`

**Expected results:** Both `flutter test` and `flutter test --coverage` should say "All tests passed!".

**Actual results:** While `flutter test` succeeds, `flutter test --coverage` throws a segfault. See logs below for the full read-out.

<details>
<summary>Code sample: lib/main.dart</summary>

```dart
import 'package:flutter/material.dart';
enum EnumNameTestFail {
  a("a");

  final String name;
  const EnumNameTestFail(this.name);
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

<details>
<summary>Code sample: test/widget_test.dart</summary>

```dart

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:enum_name/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(const MyApp());

    // Verify that our counter starts at 0.
    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    // Tap the '+' icon and trigger a frame.
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    // Verify that our counter has incremented.
    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}
```
</details>

<details>
  <summary>Logs</summary>

```

x@y enum_name % flutter test --coverage
00:02 +1: Counter increments smoke test                                                                                     unhandled error during test:
/Users/x/enum_name/test/widget_test.dart
Shell subprocess crashed with segmentation fault.
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:240:73)
<asynchronous suspension>
#1      Future.any.onValue (dart:async/future.dart:611:5)
<asynchronous suspension>


unhandled error during finalization of test:
/Users/tony/Development/enum_name/test/widget_test.dart
TestDeviceException(Shell subprocess crashed with segmentation fault.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:240:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:222:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:485:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:538:11)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
<asynchronous suspension>
#5      _FlutterPlatformStreamSinkWrapper.close.<anonymous closure>
(package:flutter_tools/src/test/flutter_platform.dart:648:7)
<asynchronous suspension>


00:03 +1 -1: loading /Users/tony/Development/enum_name/test/widget_test.dart [E]                                            
  Shell subprocess crashed with segmentation fault.
  package:flutter_tools/src/test/flutter_tester_device.dart 240:73  FlutterTesterTestDevice.finished
  ===== asynchronous gap ===========================
  dart:async/future.dart 611:5                                      Future.any.onValue
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-CA)
    • Flutter version 3.0.5 at /Users/tony/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (12 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/tony/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • F619C039-3837-44E3-A901-EDE6EFCC1DB3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5
      (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by jason-simmons** [comment]
This is working as expected on the current Flutter master branch

**Comment by liamappelbe** [comment]
The fix is in Dart 2.18

**Comment by a-siva** [comment]
@tony-ditchlabs are you able to upgrade to a newer version of Flutter that includes Dart 2.18 ?

**Comment by tony-ditchlabs** [comment]
> @tony-ditchlabs are you able to upgrade to a newer version of Flutter that includes Dart 2.18 ?

No; for a handful of reasons, we're sticking with the stable branch. But for now, it's easy enough to just not use `name` on our enums - we're using `title` instead.

**Comment by zanderso** [comment]
It sounds like this is fixed in master and beta channels, and will be fixed in the upcoming stable release, so I will go ahead and close this. Unfortunately, since it's a bit late in the 3.0 cycle, the fix will likely not be backported there.
