### ISSUE TITLE
Flutter failed to delete a directory at "build". The flutter tool cannot access the file or directory.

### ISSUE THREAD

**Issue by YowFung** [flutter/flutter#108351]
## Steps to Reproduce

1. Everything was fine at first.
2. Run `flutter upgrade` to update flutter SDK to version 3.0.5.
3. Run `flutter run -d windows`, but it fails.
4. Run `flutter clean`, the build directory cannot be deleted because some files are occupied.
5. Kill all dart processes and retry `flutter clean`, same problem.
6. Delete the build folder manually after restarting my computer, and then retry `flutter run -d windows`, no response for a long time.
7. Kill the process, then run the `flutter clean` command, and get an error as the title described

## Error Log
```shell
$ flutter clean
Deleting build...                                                  625ms
Flutter failed to delete a directory at "build". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
```
```shell
$ flutter run -d windows --verbose
{omitted}......
[  +11 ms] FinalizeBuildStatus:
[        ]   ����ɾ���ļ���x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild����
[        ]   ���ڶԡ�x64\Debug\INSTALL\INSTALL.tlog\INSTALL.lastbuildstate��ִ�� Touch ����
[        ] �����������Ŀ��D:\{path to my project}\build\windows\INSTALL.vcxproj��(Ĭ��Ŀ��)�Ĳ�����
[   +1 ms] �ѳɹ����ɡ�
[        ]     0 ������
[        ]     0 ������
[        ] ����ʱ�� 00:00:34.50
[+41685 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +1 ms] Error launching application on Windows.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:601:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[  +10 ms] "flutter run" took 115,537ms.
```

<details>
<summary>flutter doctor -v</summary>

```txt
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.17763.3046], locale zh-CN)
    • Flutter version 3.0.5 at D:\SDK\fvm\current
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (13 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\SDK\Android
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0
    • ANDROID_HOME = D:\SDK\Android
    • ANDROID_SDK_ROOT = D:\SDK\Android
    • Java binary at: D:\ProgramFiles\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.16)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32602.291
    • Windows 10 SDK version 10.0.17763.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\ProgramFiles\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.3
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744

[√] VS Code (version 1.66.0)
    • VS Code at C:\Users\Zhanghuifeng\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,0.0.0.0,127.0.0.1,192.168.1.253,192.168.1.250,192.168.1.251,192.168.1.145,192.168.3.36,192.168.*,169.254.1.1,169.254.*,172.*,10.168.*,*.yowfung.cn,*.yowfung.zos
    • NO_PROXY contains localhost
    ! NO_PROXY does not contain ::1
    • NO_PROXY contains 127.0.0.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.17763.3046]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.62
    ! Device R8U5VYESMN is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

It even caused problems with my Windows operating system, such as the inability to open the Start menu and System Settings.

![image](https://user-images.githubusercontent.com/26346560/180937398-9b560b25-b72e-4442-847d-451f42246825.png)

**Comment by maheshmnj** [comment]
Hi @YowFung, please ensure your flutter project is located in the directory where read/write permissions are available.

**Comment by maheshmnj** [comment]
Thanks for the info @YowFung, I am already on stable 3.0.5 on windows and I can't reproduce the issue. Does this happen every time or happened only once. Can you also check if this happens with a newly created project too? if it does then please share the output of `flutter clean -v`.
