### ISSUE TITLE
cmListFileCache: error can not open file

### ISSUE THREAD

**Issue by abrekhov** [flutter/flutter#108487]
## Steps to Reproduce

I want to build app using Gitlab CI/CD pipeline. I am using windows image with flutter installed by choco. 

## Logs

Here are job logs of `flutter build windows -v `

```
[   +8 ms] Building Windows application...
[  +25 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S C:\builds\apps\neiry-esports\windows -B
build\windows -G Visual Studio 17 2022
[  +74 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
[  +52 ms] CMake Error in flutter/ephemeral/.plugin_symlinks/connectivity_plus_windows/windows/CMakeLists.txt:
[   +2 ms]   cmListFileCache: error can not open file.
[        ] CMake Error in flutter/ephemeral/.plugin_symlinks/local_notifier/windows/CMakeLists.txt:
[        ]   cmListFileCache: error can not open file.
[        ] CMake Error in flutter/ephemeral/.plugin_symlinks/screen_retriever/windows/CMakeLists.txt:
[        ]   cmListFileCache: error can not open file.
[        ] CMake Error in flutter/ephemeral/.plugin_symlinks/window_manager/windows/CMakeLists.txt:
[        ]   cmListFileCache: error can not open file.
[        ] CMake Error in flutter/ephemeral/.plugin_symlinks/window_size/windows/CMakeLists.txt:
[        ]   cmListFileCache: error can not open file.
[   +1 ms] -- Configuring incomplete, errors occurred!
[        ] See also "C:/builds/apps/neiry-esports/build/windows/CMakeFiles/CMakeOutput.log".
[  +41 ms] Building Windows application... (completed in 191ms)
[        ] "flutter windows" took 1,112ms.
[   +7 ms] Unable to generate build files
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmakeGeneration (package:flutter_tools/src/windows/build_windows.dart:272:5)
           <asynchronous suspension>
           #2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:71:5)
           <asynchronous suspension>
           #3      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:55:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[  +60 ms] ensureAnalyticsSent: 55ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1



```

```
 flutter doctor -v
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 3.0.5 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = C:\Android\android-sdk
      but Android SDK not found at this location.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.2.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.17763.615]

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

</details>

**Comment by huycozy** [comment]
Hi @abrekhov 
Does the build work fine on your local machine?
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.
