### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by JESICAJJ** [flutter/flutter#108568]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=edge --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.19043.1826], locale zh-CN)
    • Flutter version 3.0.5 at C:\flutter_windows_3.0.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror http://pub.flutter-io.cn
    • Flutter download mirror http://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 103.0.1264.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03

**Comment by huycozy** [comment]
Hi @JESICAJJ, this issue was previously reported and was tracked in #95916.
It has since been fixed and the fix is available on the master channel.

I'll be closing this issue since it has already been fixed on the master channel.
If you still experience this issue on the master channel or later versions of flutter, kindly file a new issue.

Thank you!
