### ISSUE TITLE
ExpansionPanelList throw exception during debug paint

### ISSUE THREAD

**Issue by jhonToni** [flutter/flutter#108740]
## Steps to Reproduce

1. I add an ExpansionPanelList to my app;
2. I run the flutter inspector on IntelliJ IDEA;
3. I enable debug paint.

**Expected results:** 

**Actual results:** 
The ExpansionPanelList throw the exception: `Null check operator used on a null value`
<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';
class Item {
  Item({
    required this.expandedValue,
    required this.headerValue,
    this.isExpanded = false,
  });

  String expandedValue;
  String headerValue;
  bool isExpanded;
}

List<Item> generateItems(int numberOfItems) {
  return List<Item>.generate(numberOfItems, (int index) {
    return Item(
      headerValue: 'Panel $index',
      expandedValue: 'This is item number $index',
    );
  });
}
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<Item> _data = generateItems(8);
  int _counter = 0;
  Widget _buildPanel() {
    return ExpansionPanelList(
      expansionCallback: (int index, bool isExpanded) {
        setState(() {
          _data[index].isExpanded = !isExpanded;
        });
      },
      children: _data.map<ExpansionPanel>((Item item) {
        return ExpansionPanel(
          headerBuilder: (BuildContext context, bool isExpanded) {
            return ListTile(
              title: Text(item.headerValue),
            );
          },
          body: ListTile(
              title: Text(item.expandedValue),
              subtitle:
              const Text('To delete this panel, tap the trash can icon'),
              trailing: const Icon(Icons.delete),
              onTap: () {
                setState(() {
                  _data.removeWhere((Item currentItem) => item == currentItem);
                });
              }),
          isExpanded: item.isExpanded,
        );
      }).toList(),
    );
  }


  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body:Column(children: [_buildPanel()],),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
======== Exception caught by rendering library =====================================================
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  ExpansionPanelList ExpansionPanelList:file:///C:/Users/Daniele/Documents/ProgrammingProjects/flutter_projects/test_expansion_panel/lib/main.dart:73:12
When the exception was thrown, this was the stack: 
#0      RenderClipPath.debugPaintSize.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:1738:38)
#1      RenderClipPath.debugPaintSize (package:flutter/src/rendering/proxy_box.dart:1742:6)
#2      RenderBox.debugPaint.<anonymous closure> (package:flutter/src/rendering/box.dart:2676:9)
#3      RenderBox.debugPaint (package:flutter/src/rendering/box.dart:2682:6)
#4      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2484:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2488:6)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#7      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#8      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2191:11)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#11     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#12     RenderListBody.paint (package:flutter/src/rendering/list_body.dart:305:5)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#15     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#16     _RenderMergeableMaterialListBody.paint (package:flutter/src/material/mergeable_material.dart:718:5)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#19     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#20     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#23     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#24     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#28     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:604:11)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#32     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#33     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1951:15)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#36     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#41     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#42     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#43     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#44     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:506:19)
#45     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#46     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#47     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#48     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#49     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#53     _invoke (dart:ui/hooks.dart:151:10)
#54     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#55     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#20419 relayoutBoundary=up4
...  needs compositing
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=1264.0, 0.0<=h<=Infinity)
...  size: Size(1264.0, 56.5)
...  decoration: BoxDecoration
...    color: Color(0xffffffff)
...    borderRadius: BorderRadius.only(topLeft: Radius.circular(2.0), topRight: Radius.circular(2.0))
...  configuration: ImageConfiguration(bundle: PlatformAssetBundle#8c087(), devicePixelRatio: 1.0, locale: en_US, textDirection: TextDirection.ltr, platform: windows)
RenderObject: RenderDecoratedBox#20419 relayoutBoundary=up4
  needs compositing
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(w=1264.0, 0.0<=h<=Infinity)
  size: Size(1264.0, 56.5)
  decoration: BoxDecoration
    color: Color(0xffffffff)
    borderRadius: BorderRadius.only(topLeft: Radius.circular(2.0), topRight: Radius.circular(2.0))
  configuration: ImageConfiguration(bundle: PlatformAssetBundle#8c087(), devicePixelRatio: 1.0, locale: en_US, textDirection: TextDirection.ltr, platform: windows)
...  child: RenderClipPath#6ab8b relayoutBoundary=up5
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=1264.0, 0.0<=h<=Infinity)
...    size: Size(1264.0, 56.5)
...    child: RenderCustomPaint#0caf7 relayoutBoundary=up6
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=1264.0, 0.0<=h<=Infinity)
...      size: Size(1264.0, 56.5)
...      painter: null
...      foregroundPainter: _ShapeBorderPainter#c61f3()
...      child: _RenderInkFeatures#16dd6 relayoutBoundary=up7
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=1264.0, 0.0<=h<=Infinity)
...        size: Size(1264.0, 56.5)
...        child: RenderDecoratedBox#56fbd relayoutBoundary=up8
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=1264.0, 0.0<=h<=Infinity)
...          size: Size(1264.0, 56.5)
...          decoration: BoxDecoration
...            border: Border(bottom: BorderSide(Color(0x1f000000), 0.5, BorderStyle.solid))
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#8c087(), devicePixelRatio: 1.0, locale: en_US, textDirection: TextDirection.ltr, platform: windows)
====================================================================================================
```

Flutter doctor -v output:

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Versione 10.0.22000.795], locale it-IT)
    • Flutter version 3.0.5 at C:\google\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.22621.0

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\Daniele\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.6008.13
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 221.5921.27

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Users\Daniele\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.3345.118
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\Daniele\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.22000.795]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

App during the debug:
![Immagine 2022-08-01 175146](https://user-images.githubusercontent.com/29796059/182189487-828c3908-5a09-446c-a94b-17a987f8e37b.png)

**Comment by danagbemava-nc** [comment]
Hi @jhonToni, it would appear that this issue has been fixed on the `beta` and `master` branches as I could reproduce the issue on stable, but not on those branches. See the recordings below

Per our triage policy, I'll be closing this issue as it has been fixed on the `beta` and `master` branches. If you experience this issue on either of those branches, kindly leave a comment below with the steps to reproduce as well as the output of `flutter doctor -v` and I will reopen this issue. 

Thank you

<details>
<summary>videos</summary>

| stable | master & beta | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/182315031-d5cd85fb-a309-46a6-b7b9-7cfc23530808.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/182315041-6f99314b-502f-4ef0-bd8c-7fcc3456a9f5.mov" /> |

</details>



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel beta, 3.3.0-0.0.pre, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.3.0-0.0.pre on channel beta at /Users/nexus/dev/sdks/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f90da9b167 (2 weeks ago), 2022-07-18 18:59:23 -0700
    • Engine revision 1388adb442
    • Dart version 2.18.0 (build 2.18.0-271.2.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2028, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2028 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3bc09a6df (2 hours ago), 2022-08-02 01:15:06 -0400
    • Engine revision 1c3b1b305e
    • Dart version 2.19.0 (build 2.19.0-52.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
