### ISSUE TITLE
Flutter upgrade issue

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#10879]
## command

flutter upgrade

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/joelt/dev/3rd_party/flutter/bin/cache/dart-sdk/bin/pub.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43)
#2      runCommand (package:flutter_tools/src/base/process.dart:107)
#3      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:125)
<asynchronous suspension>
#4      pub (package:flutter_tools/src/dart/pub.dart:79)
<asynchronous suspension>
#5      pubGet (package:flutter_tools/src/dart/pub.dart:58)
<asynchronous suspension>
#6      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:71)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:206)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#15     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1467)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#24     main (file:///Users/joelt/dev/3rd_party/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.11.6 15G1510, locale en, channel alpha)
    • Flutter at /Users/joelt/dev/3rd_party/flutter
    • Framework revision e2f54df5ab (3 weeks ago), 2017-06-16 12:58:23 -0700
    • Engine revision 784e975672
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/joelt/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.3)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[✓] Connected devices
    • None

**Comment by eseidelGoogle** [comment]
This looks like the Dart revision failed to install correctly.

`rm /Users/joelt/dev/3rd_party/flutter/bin/cache/dart-sdk.stamp`

should fix.

**Comment by Hixie** [comment]
We're going to close this bug because we have no idea what the problem could be and it's really old so the code has probably changed by now anyway. Please do file a new bug if you still see problems.
