### ISSUE TITLE
Navigator not built on app startup if LocalizationsDelegate returns a non-immediate Future

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [flutter/flutter#108885]
At app startup, if locales are loaded in [an async fashion](https://github.com/flutter/flutter/blob/2979ff6f13429a37d3c7b2083029b71b0d413738/packages/flutter/lib/src/widgets/localizations.dart#L542-L555), Flutter is told not to render the first frame and an [empty Container is returned](https://github.com/flutter/flutter/blob/2979ff6f13429a37d3c7b2083029b71b0d413738/packages/flutter/lib/src/widgets/localizations.dart#L573-L574) instead of the widget hierarchy that contains the `WidgetApp`'s `Navigator`.

Trying to use a `GlobalKey<NavigatorState>` in `addPostFrameCallback` thus fails to find the `NavigatorState` and returns `null`.

The error in a sample app looks like:
```
E/flutter (29132): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
E/flutter (29132): #0      _MyHomePageState.initState.<anonymous closure> (package:test_app.l10n_widget_bug.app/main.dart:25:39)
E/flutter (29132): #1      _MyHomePageState.initState.<anonymous closure> (package:test_app.l10n_widget_bug.app/main.dart:23:51)
E/flutter (29132): #2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
E/flutter (29132): #3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
E/flutter (29132): #4      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
E/flutter (29132): #5      _rootRun (dart:async/zone.dart:1418:47)
E/flutter (29132): #6      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (29132): #7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (29132): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (29132): #9      _rootRun (dart:async/zone.dart:1426:13)
E/flutter (29132): #10     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (29132): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter (29132): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (29132): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (29132): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (29132): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

DartPad sample app demonstrating the problem: https://dartpad.dev/?id=351c6e1e8dea472d122710ca7303e0f9

If either example is changed to return Future.value(Object()) on L103 it works as expected.

## Steps to Reproduce

See description above.

**Comment by dowski** [comment]
The DartPad demo demonstrates the error by throwing a JS error. You can see this in the console when clicking Run:

```
errors.dart:251 Uncaught (in promise) Error: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:251:49)
    at Object.nullCheck (operations.dart:528:63)
    at main._MyHomePageState.new.<anonymous> (<anonymous>:4037:46)
    at Generator.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at <anonymous>:4036:79
    at [_invokeFrameCallback] (binding.dart:1146:15)
    at binding$.WidgetsFlutterBinding.new.handleDrawFrame (binding.dart:1091:9)
    at binding.dart:864:7
    at internalCallback (isolate_helper.dart:48:19)
```

**Comment by maheshmnj** [comment]
Hi @ChristianEdwardPadilla, Thanks for filing the issue. I am able to reproduce the same behavior on both stable and the master channel. Labeling for further insights from the team.  

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyHomePage());

/// This sample demonstrates how using a [LocalizationsDelegate] that returns
/// a non-immediate Future breaks a sign-in flow that depends on [Navigator]
/// getting unconditionally built.
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _navigatorKey = GlobalKey<NavigatorState>();
  bool _signedIn = false;

  @override
  void initState() {
    super.initState();
    // Sign-in flow triggered by pushing a route after the Widget tree is built.
    WidgetsBinding.instance!.addPostFrameCallback((_) async {
      var result =
          await _navigatorKey.currentState!.pushNamed('sign_in') as bool;
      setState(() {
        _signedIn = result;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      navigatorKey: _navigatorKey,
      initialRoute: '/',
      routes: {
        '/': (context) => HomeScreen(
              signedIn: _signedIn,
            ),
        'sign_in': (context) => const SignInScreen(),
      },
      localizationsDelegates: [FakeDelayedLocalizationsDelegate()],
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({Key? key, required this.signedIn}) : super(key: key);

  final bool signedIn;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home Screen'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {},
          child: Text(signedIn ? 'Signed in :-)' : 'Not signed in :-('),
        ),
      ),
    );
  }
}

class SignInScreen extends StatelessWidget {
  const SignInScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Screen'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            // Fake sign in
            Navigator.of(context).pop(true);
          },
          child: const Text('Sign in'),
        ),
      ),
    );
  }
}

/// This delegate returns a non-immediate Future in its [load] method which
/// messes with normal [WidgetsApp] startup (causes the app to not build a
/// [Navigator]) and thus the sign-in flow as written doesn't work.
class FakeDelayedLocalizationsDelegate extends LocalizationsDelegate<Object> {
  @override
  bool isSupported(Locale locale) {
    return true;
  }

  @override
  Future<Object> load(Locale locale) {
    // return Future.delayed(const Duration(seconds: 1), () => Object()); // this doesn't work
    return Future.value(Object());
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<Object> old) {
    return false;
  }
}

```
</details> 


<details>
<summary>logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 sample % flutter run
Could not load custom device from config index 0: Expected enabled to be a boolean.
Running "flutter pub get" in sample...                           2,795ms
Using hardware rendering with device sdk gphone arm64. If you notice graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone arm64 in debug mode...
Running Gradle task 'assembleDebug'...                             11.8s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                627ms
E/flutter (10006): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (10006): #0      _MyHomePageState.initState.<anonymous closure> (package:sample/main.dart:25:43)
E/flutter (10006): #1      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
E/flutter (10006): #2      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:9)
E/flutter (10006): #3      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
E/flutter (10006): #4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (10006): #5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (10006): #6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (10006): #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10006): 
Syncing files to device sdk gphone arm64...                        229ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on sdk gphone arm64 is available at: http://127.0.0.1:58951/t5u2aOqX2x4=/
The Flutter DevTools debugger and profiler on sdk gphone arm64 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:58951/t5u2aOqX2x4=/

Performing hot restart...                                               
Restarted application in 681ms.
E/flutter (10006): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (10006): #0      _MyHomePageState.initState.<anonymous closure> (package:sample/main.dart:25:43)
E/flutter (10006): #1      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
E/flutter (10006): #2      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:9)
E/flutter (10006): #3      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
E/flutter (10006): #4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (10006): #5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (10006): #6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (10006): #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10006): 
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2009, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2009 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9d96c7b8be (3 days ago), 2022-08-01 00:39:06 -0400
    • Engine revision cf0db3e546
    • Dart version 2.19.0 (build 2.19.0-49.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by goderbauer** [comment]
This is kind of working as intended. While the locale isn't loaded, we can't really render any meaningful text. The idea is that we keep the splash screen of the app up while the locales are loading. Can you share a little more about your use case that requires you to push a route while locales are not loaded?

**Comment by dowski** [comment]
I think that's fair, I guess it's just hard to debug what's actually wrong when a null value gets hit deep in the framework like that. I think a more clear error message could help.

I'm not 100% sure what the use case was - I was working on code that someone else wrote. I think maybe the intent was to bring up the main Widget in the app and then immediately navigate to a sign-in page.
