### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method, error in google play console

### ISSUE THREAD

**Issue by alhamri** [flutter/flutter#108837]
I upload my flutter app for internal testing in google play console, the first time it passed without issue. but today I upload it again after making minor changes (only in codes) not in the manifest or gradle file, it fail in the test and throw this fatal error:

```
FATAL EXCEPTION: main
Process: com.google.android.gm, PID: 8648
java.lang.NullPointerException: Attempt to invoke virtual method 'android.accounts.Account com.android.mail.providers.Account.b()' on a null object reference
    at dgg.Z(PG:3)
    at dgg.onPrepareOptionsMenu(PG:6)
    at com.google.android.gm.ComposeActivityGmail.onPrepareOptionsMenu(PG:1)
    at android.app.Activity.onPreparePanel(Activity.java:4137)
    at gn.onPreparePanel(PG:2)
    at vz.onPreparePanel(Unknown Source:2)
    at tm.onPreparePanel(PG:3)
    at tv.a(PG:192)
    at tv.f(PG:7)
    at tc.run(PG:2)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8016)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```
I cannot reproduce the error because it works fine in both emulator and physical device, the exception suddenly appeared in google play console after internal testing!

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1826], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.1)
[√] Android Studio (version 2021.1)
[√] Android Studio (version 4.1)
[√] Android Studio (version 4.2)
[√] VS Code (version 1.69.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```
 what this error means? and how to solve it?

**Comment by alhamri** [comment]
I'm not sure what happened here, but today I tried again without changing anything in the project, and it passed the test with any issue (the device where the exception occurred was included in the test). 

![google test](https://user-images.githubusercontent.com/56443760/182527778-7afadbcf-c99f-4343-8fc7-d3c675fc8f7d.PNG)
