### ISSUE TITLE
Calling TextController.clear() raises exception

### ISSUE THREAD

**Issue by pcomans** [flutter/flutter#10890]
## Steps to Reproduce
Call _textController.clear(); in an event handler.
```dart
void _handleSubmitted(String text) {
 _textController.clear();
}
```
This used to work, see the example in the CodeLab: https://codelabs.developers.google.com/codelabs/flutter/index.html#4 

## Logs

```
E/flutter (10914): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (10914): PlatformException(error, setSpan (-1 ... -1) starts before 0, null)
E/flutter (10914): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:145)
E/flutter (10914): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter (10914): <asynchronous suspension>
E/flutter (10914): #2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:228)
E/flutter (10914): <asynchronous suspension>
E/flutter (10914): #3      TextInputConnection.setEditingState (package:flutter/src/services/text_input.dart:248)
E/flutter (10914): #4      EditableTextState._updateRemoteEditingValueIfNeeded (package:flutter/src/widgets/editable_text.dart:342)
E/flutter (10914): #5      EditableTextState._didChangeTextEditingValue (package:flutter/src/widgets/editable_text.dart:516)
E/flutter (10914): #6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:129)
E/flutter (10914): #7      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:184)
E/flutter (10914): #8      TextEditingController.clear (package:flutter/src/widgets/editable_text.dart:95)
E/flutter (10914): #9      ChatScreenState._handleSubmitted (file:///Users/philipp/IdeaProjects/chatty/lib/main.dart:164)
E/flutter (10914): <asynchronous suspension>
E/flutter (10914): #10     ChatScreenState._buildTextComposer.<anonymous closure> (file:///Users/philipp/IdeaProjects/chatty/lib/main.dart:154)
E/flutter (10914): #11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:229)
E/flutter (10914): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:67)
E/flutter (10914): #13     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:149)
E/flutter (10914): #14     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:92)
E/flutter (10914): #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:268)
E/flutter (10914): #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73)
E/flutter (10914): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
E/flutter (10914): #18     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:127)
E/flutter (10914): #19     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:105)
E/flutter (10914): #20     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:86)
E/flutter (10914): #21     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:45)
E/flutter (10914): #22     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:38)
E/flutter (10914): #23     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:55)
```

## Flutter Doctor

Running flutter doctor...
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel alpha)
    • Flutter at /Users/philipp/code/flutter
    • Framework revision 3b6d84b083 (5 days ago), 2017-06-16 12:58:23 -0700
    • Engine revision 784e975672
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/philipp/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.3.0.beta.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Moto G 5 Plus • ZY2242PN6T • android-arm • Android 7.0 (API 24)

**Comment by jason-simmons** [comment]
This should have been fixed by https://github.com/flutter/engine/commit/e5b79ba63b92aa0c4299836f4433ec0de23b7cb3

(If you're on the alpha branch, try switching to master)

**Comment by jason-simmons** [comment]
This is rolled out to alpha now

**Comment by pcomans** [comment]
@jason-simmons That fixes it
