### ISSUE TITLE
[tool_crash] _CastError: new AppResourceBundle 

### ISSUE THREAD

**Issue by Abhaww** [flutter/flutter#108965]
i tried to get dependencies but i end up getting this error i tried several times but to no avail

**Comment by danagbemava-nc** [comment]
Hi @Abhaww, can you share the crash log as well as the output of `flutter doctor -v`? 

Please also provide the file that looks similar to `flutter_01.log`.

Thank you

**Comment by Abhaww** [comment]
C:\src\flutter\bin\flutter.bat --no-color pub get

Oops; flutter has exited unexpectedly: "type 'List<dynamic>' is not a subtype of type 'Map<String, Object?>' in type cast".
A crash report has been written to C:\Users\DELL\Documents\flutter projects\valodam_source_code\flutter_10.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+type+%27List%3Cdynamic%3E%27+is+not+a+subtype+of+type+%27Map%3CString%2C+Object%3F%3E%27+in+type+cast

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+_CastError%3A+%28%230++++++new+AppResourceBundle+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n_types.dart%3A441%3A56%29%29&body=%23%23+Command%0A%60%60%60%0Aflutter+--no-color+pub+get%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0A_CastError%3A+%28%230++++++new+AppResourceBundle+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n_types.dart%3A441%3A56%29%29%0A%60%60%60%0A%230++++++new+AppResourceBundle+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n_types.dart%3A441%3A56%29%0A%231++++++new+AppResourceBundleCollection+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n_types.dart%3A529%3A42%29%0A%232++++++LocalizationsGenerator._allBundles+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A746%3A56%29%0A%233++++++LocalizationsGenerator._allBundles+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%29%0A%234++++++LocalizationsGenerator.loadResources+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A1084%3A29%29%0A%235++++++generateLocalizations+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A68%3A9%29%0A%236++++++GenerateLocalizationsTarget.build+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Ftargets%2Flocalizations.dart%3A56%3A5%29%0A%237++++++_BuildInstance._invokeInternal+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Fbuild_system.dart%3A839%3A27%29%0A%3Casynchronous+suspension%3E%0A%238++++++FlutterBuildSystem.build+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Fbuild_system.dart%3A606%3A16%29%0A%3Casynchronous+suspension%3E%0A%239++++++generateLocalizationsSyntheticPackage+%28package%3Aflutter_tools%2Fsrc%2Fdart%2Fgenerate_synthetic_packages.dart%3A58%3A30%29%0A%3Casynchronous+suspension%3E%0A%2310+++++PackagesGetCommand._runPubGet+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fpackages.dart%3A133%3A7%29%0A%3Casynchronous+suspension%3E%0A%2311+++++PackagesGetCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fpackages.dart%3A176%3A5%29%0A%3Casynchronous+suspension%3E%0A%2312+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1183%3A27%29%0A%3Casynchronous+suspension%3E%0A%2313+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2314+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%3Casynchronous+suspension%3E%0A%2315+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A281%3A9%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+3.0.5%2C+on+Microsoft+Windows+%5BVersion+10.0.22000.795%5D%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+3.0.5+at+C%3A%5Csrc%5Cflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+f1875d570e+%283+weeks+ago%29%2C+2022-07-13+11%3A24%3A16+-0700%0A++++%E2%80%A2+Engine+revision+e85ea0e79c%0A++++%E2%80%A2+Dart+version+2.17.6%0A++++%E2%80%A2+DevTools+version+2.12.2%0A%0A%5B%21%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.0%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5CDELL%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%9C%97+cmdline-tools+component+is+missing%0A++++++Run+%60path%2Fto%2Fsdkmanager+--install+%22cmdline-tools%3Blatest%22%60%0A++++++See+https%3A%2F%2Fdeveloper.android.com%2Fstudio%2Fcommand-line+for+more+details.%0A++++%E2%9C%97+Android+license+status+unknown.%0A++++++Run+%60flutter+doctor+--android-licenses%60+to+accept+the+SDK+licenses.%0A++++++See+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall%2Fwindows%23android-setup+for+more+details.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%E2%9C%97%5D+Visual+Studio+-+develop+for+Windows%0A++++%E2%9C%97+Visual+Studio+not+installed%3B+this+is+necessary+for+Windows+development.%0A++++++Download+at+https%3A%2F%2Fvisualstudio.microsoft.com%2Fdownloads%2F.%0A++++++Please+install+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+including+all+of+its+default+components%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2021.2%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.69.1%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5CDELL%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flutter+extension+version+3.44.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%284+available%29%0A++++%E2%80%A2+sdk+gphone64+x86+64+%28mobile%29+%E2%80%A2+emulator-5554+%E2%80%A2+android-x64++++%E2%80%A2+Android+13+%28API+33%29+%28emulator%29%0A++++%E2%80%A2+Windows+%28desktop%29++++++++++++%E2%80%A2+windows+++++++%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.22000.795%5D%0A++++%E2%80%A2+Chrome+%28web%29+++++++++++++++++%E2%80%A2+chrome++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+104.0.5112.79%0A++++%E2%80%A2+Edge+%28web%29+++++++++++++++++++%E2%80%A2+edge++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+103.0.1264.77%0A%0A%5B%E2%9C%93%5D+HTTP+Host+Availability%0A++++%E2%80%A2+All+required+HTTP+hosts+are+available%0A%0A%21+Doctor+found+issues+in+2+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+3.0.0%2B16%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+1aafb3a8b9b0c36241c5f5b34ee914770f015818%0A%0A&labels=tool%2Csevere%3A+crash

Process finished with exit code 1

**Comment by christopherfujino** [comment]
Command
```
flutter+--no-color+pub+get
```

##+Steps+to+Reproduce
1.+...
2.+...
3.+...

##+Logs
_CastError:+(#0++++++new+AppResourceBundle+(package:flutter_tools/src/localizations/gen_l10n_types.dart:441:56))
```
#0++++++new+AppResourceBundle+(package:flutter_tools/src/localizations/gen_l10n_types.dart:441:56)
#1++++++new+AppResourceBundleCollection+(package:flutter_tools/src/localizations/gen_l10n_types.dart:529:42)
#2++++++LocalizationsGenerator._allBundles+(package:flutter_tools/src/localizations/gen_l10n.dart:746:56)
#3++++++LocalizationsGenerator._allBundles+(package:flutter_tools/src/localizations/gen_l10n.dart)
#4++++++LocalizationsGenerator.loadResources+(package:flutter_tools/src/localizations/gen_l10n.dart:1084:29)
#5++++++generateLocalizations+(package:flutter_tools/src/localizations/gen_l10n.dart:68:9)
#6++++++GenerateLocalizationsTarget.build+(package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#7++++++_BuildInstance._invokeInternal+(package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous+suspension>
#8++++++FlutterBuildSystem.build+(package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous+suspension>
#9++++++generateLocalizationsSyntheticPackage+(package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous+suspension>
#10+++++PackagesGetCommand._runPubGet+(package:flutter_tools/src/commands/packages.dart:133:7)
<asynchronous+suspension>
#11+++++PackagesGetCommand.runCommand+(package:flutter_tools/src/commands/packages.dart:176:5)
<asynchronous+suspension>
#12+++++FlutterCommand.run.<anonymous+closure>+(package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous+suspension>
#13+++++AppContext.run.<anonymous+closure>+(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous+suspension>
#14+++++CommandRunner.runCommand+(package:args/command_runner.dart:209:13)
<asynchronous+suspension>
#15+++++FlutterCommandRunner.runCommand.<anonymous+closure>+(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous+suspension>
```
```
[â]+Flutter+(Channel+stable,+3.0.5,+on+Microsoft+Windows+[Version+10.0.22000.795],+locale+en-US)
++++â¢+Flutter+version+3.0.5+at+C:\src\flutter
++++â¢+Upstream+repository+https://github.com/flutter/flutter.git
++++â¢+Framework+revision+f1875d570e+(3+weeks+ago),+2022-07-13+11:24:16+-0700
++++â¢+Engine+revision+e85ea0e79c
++++â¢+Dart+version+2.17.6
++++â¢+DevTools+version+2.12.2

[!]+Android+toolchain+-+develop+for+Android+devices+(Android+SDK+version+33.0.0)
++++â¢+Android+SDK+at+C:\Users\DELL\AppData\Local\Android\sdk
++++â+cmdline-tools+component+is+missing
++++++Run+`path/to/sdkmanager+--install+"cmdline-tools;latest"`
++++++See+https://developer.android.com/studio/command-line+for+more+details.
++++â+Android+license+status+unknown.
++++++Run+`flutter+doctor+--android-licenses`+to+accept+the+SDK+licenses.
++++++See+https://flutter.dev/docs/get-started/install/windows#android-setup+for+more+details.

[â]+Chrome+-+develop+for+the+web
++++â¢+Chrome+at+C:\Program+Files\Google\Chrome\Application\chrome.exe

[â]+Visual+Studio+-+develop+for+Windows
++++â+Visual+Studio+not+installed;+this+is+necessary+for+Windows+development.
++++++Download+at+https://visualstudio.microsoft.com/downloads/.
++++++Please+install+the+"Desktop+development+with+C++"+workload,+including+all+of+its+default+components

[â]+Android+Studio+(version+2021.2)
++++â¢+Android+Studio+at+C:\Program+Files\Android\Android+Studio
++++â¢+Flutter+plugin+can+be+installed+from:
++++++ð¨+https://plugins.jetbrains.com/plugin/9212-flutter
++++â¢+Dart+plugin+can+be+installed+from:
++++++ð¨+https://plugins.jetbrains.com/plugin/6351-dart
++++â¢+Java+version+OpenJDK+Runtime+Environment+(build+11.0.12+7-b1504.28-7817840)

[â]+VS+Code+(version+1.69.1)
++++â¢+VS+Code+at+C:\Users\DELL\AppData\Local\Programs\Microsoft+VS+Code
++++â¢+Flutter+extension+version+3.44.0

[â]+Connected+device+(4+available)
++++â¢+sdk+gphone64+x86+64+(mobile)+â¢+emulator-5554+â¢+android-x64++++â¢+Android+13+(API+33)+(emulator)
++++â¢+Windows+(desktop)++++++++++++â¢+windows+++++++â¢+windows-x64++++â¢+Microsoft+Windows+[Version+10.0.22000.795]
++++â¢+Chrome+(web)+++++++++++++++++â¢+chrome++++++++â¢+web-javascript+â¢+Google+Chrome+104.0.5112.79
++++â¢+Edge+(web)+++++++++++++++++++â¢+edge++++++++++â¢+web-javascript+â¢+Microsoft+Edge+103.0.1264.77

[â]+HTTP+Host+Availability
++++â¢+All+required+HTTP+hosts+are+available

!+Doctor+found+issues+in+2+categories.

```

##+Flutter+Application+Metadata
**Type**:+app
**Version**:+3.0.0+16
**Material**:+true
**Android+X**:+false
**Module**:+false
**Plugin**:+false
**Android+package**:+null
**iOS+bundle+identifier**:+null
**Creation+channel**:+stable
**Creation+framework+version**:+1aafb3a8b9b0c36241c5f5b34ee914770f015818

&labels=tool,severe:+crash

**Comment by Abhaww** [comment]
> Hi @Abhaww, can you share the crash log as well as the output of `flutter doctor -v`?
> 
> Please also provide the file that looks similar to `flutter_01.log`.
> 
> Thank you

here is the flutter doctor -v

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale en-US)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.795]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.79
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by Abhaww** [comment]
> Hi @Abhaww, can you share the crash log as well as the output of `flutter doctor -v`?
> 
> Please also provide the file that looks similar to `flutter_01.log`.
> 
> Thank you

flutter_01.log

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter pub get

## exception

_CastError: type 'List<dynamic>' is not a subtype of type 'Map<String, Object?>' in type cast

```
#0      new AppResourceBundle (package:flutter_tools/src/localizations/gen_l10n_types.dart:441:56)
#1      new AppResourceBundleCollection (package:flutter_tools/src/localizations/gen_l10n_types.dart:529:42)
#2      LocalizationsGenerator._allBundles (package:flutter_tools/src/localizations/gen_l10n.dart:746:56)
#3      LocalizationsGenerator._allBundles (package:flutter_tools/src/localizations/gen_l10n.dart)
#4      LocalizationsGenerator.loadResources (package:flutter_tools/src/localizations/gen_l10n.dart:1084:29)
#5      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:68:9)
#6      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#9      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#10     PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:133:7)
<asynchronous suspension>
#11     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:176:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.22000.795], locale en-US)
    • Flutter version 3.0.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (6 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.69.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.795]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 104.0.5112.79
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 103.0.1264.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
