### ISSUE TITLE
Platform view hasn't been initialized from the platform view channel

### ISSUE THREAD

**Issue by fitterfly-parth** [flutter/flutter#109045]
```
D/CompatibilityChangeReporter( 6138): Compat change id reported: 171228096; UID 10153; state: ENABLED
D/EGL_emulation( 6138): eglMakeCurrent: 0xb4000072e66faf90: ver 3 0 (tinfo 0x74fc39e080) (first time)
E/flutter ( 6138): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
E/flutter ( 6138): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:732)
E/flutter ( 6138): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:791)
E/flutter ( 6138): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1380)
E/flutter ( 6138): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 6138): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 6138): 	at android.os.Looper.loopOnce(Looper.java:161)
E/flutter ( 6138): 	at android.os.Looper.loop(Looper.java:288)
E/flutter ( 6138): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/flutter ( 6138): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6138): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter ( 6138): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter ( 6138): 
F/flutter ( 6138): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env). 
F/libc    ( 6138): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 6138 (terFly.Wellness), pid 6138 (terFly.Wellness)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone64_arm64/emulator64_arm64:12/SE1A.220203.002.A1/8151367:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-08-05 20:32:38.692882463+0530
Process uptime: 0s
Cmdline: com.FitterFly.Wellness
pid: 6138, tid: 6138, name: terFly.Wellness  >>> com.FitterFly.Wellness <<<
uid: 10153
tagged_addr_ctrl: 0000000000000001
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env). 
'
    x0  0000000000000000  x1  00000000000017fa  x2  0000000000000006  x3  0000007fca83b0c0
    x4  6d602e6c716e6573  x5  6d602e6c716e6573  x6  6d602e6c716e6573  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  50a8661d49e2ce1e  x10 0000000000000000  x11 ffffff80fffffbdf
    x12 0000000000000001  x13 000000000000007e  x14 0000007fca839f70  x15 000002c054794089
    x16 00000074eb794050  x17 00000074eb770eb0  x18 0000007502b46000  x19 00000000000017fa
    x20 00000000000017fa  x21 00000000ffffffff  x22 b4000072b67161f8  x23 0000000000000207
    x24 b4000073166fdab0  x25 0000000000000000  x26 0000000000000000  x27 0000000000000071
    x28 0000007fca83b3c8  x29 0000007fca83b140
    lr  00000074eb723ba0  sp  0000007fca83b0a0  pc  00000074eb723bcc  pst 0000000000001000
backtrace:
      #00 pc 000000000004fbcc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: ba489d4985c0cf173209da67405662f9)
      #01 pc 000000000156f9cc  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #02 pc 00000000015945b4  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #03 pc 000000000157b818  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #04 pc 0000000001c6c1cc  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #05 pc 00000000018bd600  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #06 pc 00000000018bc234  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #07 pc 00000000018bcd24  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #08 pc 00000000018bdb48  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #09 pc 00000000018bc678  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #10 pc 00000000018bc3d0  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #11 pc 00000000018bde28  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #12 pc 00000000015952b0  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #13 pc 000000000159ab58  /data/app/~~jydQuQyHdOf-llbTdDYXYw==/com.FitterFly.Wellness-ad6eY3S75M0r2NZM8dlzOQ==/lib/arm64/libflutter.so (BuildId: 4eada3eb5afdd9bb6982917520d32254e275a824)
      #14 pc 000000000001691c  /system/lib64/libutils.so (android::Looper::pollInner(int)+912) (BuildId: a3acb0eba7fd91ea48db6f0befa41c65)
      #15 pc 0000000000016524  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: a3acb0eba7fd91ea48db6f0befa41c65)
      #16 pc 000000000014ad6c  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: e5ec2f754b518abdb10fc3507273ac59)
      #17 pc 000000000019c22c  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+108) (BuildId: 591477803b64c1a755412cea018708f85997389b)
      #18 pc 0000000002010e7c  /memfd:jit-cache (deleted) (android.os.MessageQueue.next+204)
      #19 pc 00000000020184c8  /memfd:jit-cache (deleted) (android.os.Looper.loopOnce+168)
      #20 pc 0000000000218be8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #21 pc 0000000000284224  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+216) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #22 pc 00000000003e34ac  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+400) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #23 pc 00000000003de320  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+804) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #24 pc 0000000000757de0  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+980) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #25 pc 0000000000203994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #26 pc 000000000044d6e8  /system/framework/framework.jar
      #27 pc 000000000075833c  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+2352) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #28 pc 0000000000203994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #29 pc 00000000001c85e2  /system/framework/framework.jar
      #30 pc 00000000003d6150  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #31 pc 000000000073b6b8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+776) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #32 pc 0000000000222378  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #33 pc 0000000000218be8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #34 pc 0000000000284224  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+216) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #35 pc 000000000061e8f8  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1384) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #36 pc 000000000058fa68  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #37 pc 00000000000b2f74  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+132) (BuildId: 715d0a044ea13bcf499cd6094001f85c3246944e)
      #38 pc 0000000000218964  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #39 pc 0000000000284208  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+188) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #40 pc 00000000003e34ac  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+400) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #41 pc 00000000003de320  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+804) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #42 pc 000000000074cc98  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1168) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #43 pc 0000000000203814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #44 pc 0000000000247fae  /system/framework/framework.jar
      #45 pc 00000000003d6150  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #46 pc 000000000073b6b8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+776) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #47 pc 0000000000222378  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #48 pc 0000000000823028  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2232) (BuildId: 591477803b64c1a755412cea018708f85997389b)
      #49 pc 0000000000218be8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #50 pc 0000000000284224  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+216) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #51 pc 000000000061f050  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #52 pc 000000000061f514  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #53 pc 00000000004fa784  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+616) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #54 pc 00000000000aeac4  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120) (BuildId: e5ec2f754b518abdb10fc3507273ac59)
      #55 pc 00000000000ba05c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+836) (BuildId: e5ec2f754b518abdb10fc3507273ac59)
      #56 pc 000000000000258c  /system/bin/app_process64 (main+1336) (BuildId: 4ecb2c57d6667e4a94a73568ce392d22)
      #57 pc 00000000000488c8  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+96) (BuildId: ba489d4985c0cf173209da67405662f9)
```

```
192:flutter-wellness-app user$ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/user/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 Pro Max (mobile)  • C55DF62E-3D6C-4F78-B383-763B299DD24A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment]
Hi @fitterfly-parth, 
I see there was a similar issue #108429 that has been confirmed that it was fixed on [beta](https://github.com/flutter/flutter/issues/108429#issuecomment-1201177276) and [master](https://github.com/flutter/flutter/issues/108429#issuecomment-1200101038). So please retry on the latest beta or master to see if the issue still reproduces.

If the issue still persists, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
Thank you!

**Comment by fitterfly-parth** [comment]
Working fine on Master

**Comment by huycozy** [comment]
Closing as fixed on the master channel. The fix should land on the stable channel in future releases. Thanks!

**Comment by huycozy** [comment]
@mericgerceker It takes a couple of months to land stable fixes to release channels. You can read more about the build release channels here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels.
