### ISSUE TITLE
Restart app during integration tests

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#109035]
Hello,

I am trying to set up integration tests.
If I create a group, and the second test start it will fail because of dispose. (also happens without a group)

In this example I duplicated the same test, to try this out:

```
  group('Authentication tests', () {
    testWidgets('Password login', (WidgetTester tester) async {
      await SharedAppTest.initializeApp(tester);
      await SharedLoginTest.loginPassword(tester);

      expect(find.text('See all rides'), findsOneWidget);

      await SharedLoginTest.logout(tester);
    });

    testWidgets('Password login2', (WidgetTester tester) async {
      await SharedAppTest.initializeApp(tester);
      await SharedCommonTest.addDelay(10000);
      await SharedLoginTest.loginPassword(tester);

      expect(find.text('See all rides'), findsOneWidget);

      await SharedLoginTest.logout(tester);
    });

    testWidgets('Password login3', (WidgetTester tester) async {
      await SharedAppTest.initializeApp(tester);
      await SharedLoginTest.loginPassword(tester);

      expect(find.text('See all rides'), findsOneWidget);

      await SharedLoginTest.logout(tester);
    });
  });
```

The first test succeeds, the second fails because of:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MainNavigationMobileView(dirty):
A AppTheme was used after being disposed.
Once you have called dispose() on a AppTheme, it can no longer be used.

The relevant error-causing widget was:
  MainNavigationMobileView
  MainNavigationMobileView:file:///Users/glennruysschaert/Code/flutter-package-app-core/lib/screens/main/main_navigation_screen.dart:332:12

When the exception was thrown, this was the stack:
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:125:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:131:6)
#2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:184:12)
#3      ListenableProvider._startListening (package:provider/src/listenable_provider.dart:61:12)
#4      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:786:50)
#5      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:590:33)
#6      Provider.of (package:provider/src/provider.dart:303:37)
#7      ThemeMixin.theme (package:gd_ui/src/mixins/theme_mixin.dart:7:44)
#8      MainNavigationMobileView.build (package:gd_app_core/screens/main/main_navigation_view.dart:40:32)
#9      StatelessElement.build (package:flutter/src/widgets/framework.dart:4876:49)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
...     Normal element mounting (192 frames)
#205    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#206    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#207    Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#208    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5883:32)
#209    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#212    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#214    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#215    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#216    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#217    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#218    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#219    LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1546:13)
#220    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#224    _invoke (dart:ui/hooks.dart:151:10)
#225    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#226    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with key [<'welcome_login_button'>] (ignoring offstage widgets)" (used in a
call to "tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:900:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:839:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:273:18)
#3      SharedLoginTest.loginPassword (file:///Users/glennruysschaert/Code/get-driven-flutter-app/get_driven_customer/integration_test/shared/shared_login_test.dart:6:18)
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/glennruysschaert/Code/get-driven-flutter-app/get_driven_customer/integration_test/authentication_test.dart:34:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Password login2
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Password login2
```

Is there a way to fully restart the app in between tests (like hot restart would do)?

**Comment by exaby73** [comment]
Hi @..., please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
