### ISSUE TITLE
`CupertinoListTile` is missing `mounted` checks

### ISSUE THREAD

**Issue by alex-sandri** [flutter/flutter#109024]
**Note:**

The first import in the code sample:

```dart
import 'package:cupertinolisttileerrordemo/cupertino_list_tile.dart';
```

is just the `CupertinoListTile`'s file from this repo with a few edits to make it work outside of the Flutter repo as I'm currently on the stable branch and as such do not have that widget available right now.

If you are on the master channel you can just remove this line.

## Steps to Reproduce

1. See the code sample. (This reproduces a similar issue to the one I'm facing in my app but I'm unfortunately unable to reproduce the exact error, but it is related to calling setState when the widget is not mounted anyways).

Here are the Firebase Crashlytics logs for the app (line numbers on the cupertino list tile do not match the ones in this repo but are still on that setState call):

```
Non-fatal Exception: FlutterError
0  ???                            0x0 State.setState + 1129 (framework.dart:1129)
1  ???                            0x0 _CupertinoListTileState.build.<fn> + 399 (cupertino_list_tile.dart:399)
```

**Expected results:** 

No error thrown.

**Actual results:** 

`setState()` called after widget has been disposed.

## Fix

Return early if not mounted before this line https://github.com/flutter/flutter/blob/fe7b6de4df7fde836d4e04f26b9fb70f7e3c9f3e/packages/flutter/lib/src/cupertino/list_tile.dart#L388

like this:

```dart

if (!mounted) {
    return;
}

setState(() { _tapped = false; });
```

<details>
<summary>Code sample</summary>

```dart
import 'package:cupertinolisttileerrordemo/cupertino_list_tile.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _show = true;

  Future<void> _onTap() async {
    setState(() => _show = false);

    await Future.delayed(const Duration(seconds: 3));

    Future.delayed(
      const Duration(seconds: 1),
      () => setState(() => _show = true),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              if (_show)
                CupertinoListTile.notched(
                  title: const Text('Tap me'),
                  onTap: _onTap,
                ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: setState() called after dispose(): _CupertinoListTileState#4a9c1(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code 
calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1073:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1108:6)
#2      _CupertinoListTileState.build.<anonymous closure> (package:cupertinolisttileerrordemo/cupertino_list_tile.dart:400:9)
<asynchronous suspension>
```

```
Analyzing cupertinolisttileerrordemo...                                 
No issues found! (ran in 2.5s)
```

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Versione 10.0.19044.1865], locale it-IT)
    • Flutter version 3.0.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = C:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.0)
    • VS Code at C:\Users\Alex Sandri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.19044.1865]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.37

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @alex-sandri 
Thanks for filing the bug report.


Looks like the issue reproduced due to onTap ` await`  and setState being called at the same time. 

https://github.com/flutter/flutter/blob/fe7b6de4df7fde836d4e04f26b9fb70f7e3c9f3e/packages/flutter/lib/src/cupertino/list_tile.dart#L386-L389

As you suggest it's the mounting issue, however, we can call setState only when mounted. 

<details> 
<summary>Code Sample</summary> 

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      theme: CupertinoThemeData(brightness: Brightness.light),
      home: Example(),
    );
  }
}

class Example extends StatefulWidget {
  const Example({super.key});

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  bool showTile = true;

  Future<void> onTap() async {
    setState(() {
      showTile = false;
    });
    await Future<void>.delayed(const Duration(seconds: 3));
    await Future<void>.delayed(
      const Duration(seconds: 1),
      () => setState(() => showTile = true),
    );
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: const CupertinoThemeData(
        brightness: Brightness.light,
      ),
      home: CupertinoPageScaffold(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              if (showTile)
                CupertinoListTile.notched(
                  title: const Text('Tap me'),
                  onTap: onTap,
                ),
            ],
          ),
        ),
      ),
    );
  }
}

``` 
	
</details>


<details> 
<summary>flutter doctor -v</summary> 

```dart
[!] Flutter (Channel master, 3.1.0-0.0.pre.2105, on macOS 13.0 22A5311f
    darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2105 on channel master at
      /Users/tahatesser/Code/flutter
    ! Upstream repository git@github.com:NevercodeHQ/flutter.git is not a
      standard remote.
      Set environment variable "FLUTTER_GIT_URL" to
      git@github.com:NevercodeHQ/flutter.git to dismiss this error.
    • Framework revision fe7b6de4df (6 hours ago), 2022-08-05 09:04:08 +0200
    • Engine revision 25bad51f09
    • Dart version 2.19.0 (build 2.19.0-66.0.dev)
    • DevTools version 2.16.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 14A5270f
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20                             •
      android-arm64  • Android 12 (API 32)
    • iPhone 13 (mobile)     • 44C2C534-56A8-4315-B74E-33D4ABBCB0F8 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                •
      darwin-arm64   • macOS 13.0 22A5311f darwin-arm
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

``` 
	
</details>
