### ISSUE TITLE
PageView fails to show pages in Release

### ISSUE THREAD

**Issue by RyanRamchandar** [flutter/flutter#109106]
PageView seems to be broken when running release builds on iOS (I haven't tested other platforms).

In the sample code below I expect to see four pages that can be horizontally scrolled. However, running the app as release, and opening and killing the app a few times, eventually the PageView will not display any children. I cannot reproduce this error in debug mode it only happens in release mode.

I tested on an iPhone 12 Pro, running iOS 15.5.

This appears to be a regression in newer versions of Flutter, perhaps 3.0+ but I'm not sure exactly when it first occured.

## Steps to Reproduce

1. Execute `flutter run --release` on the code sample 
2. The first launch works correctly. All pages are displayed and scrollable.
3. Kill the app (by tossing it from recents) and relaunch it. You may need to do this a few times.
4. Eventually, its children will not be displayed and a red background will be displayed.

**Expected results:** 

I expect to see the four scrollable pages: blue, green, yellow and purple.

**Actual results:** 

After relaunching the app, the pages are no longer there.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.red,
      child: PageView(
        children: [
          Container(color: Colors.blue,),
          Container(color: Colors.green,),
          Container(color: Colors.yellow,),
          Container(color: Colors.purple,),
        ],
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale
    en-CA)
    • Flutter version 3.0.5 at /Users/ryan/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ryan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/ryan/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8309675
      /Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/ryan/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8309675
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /Users/ryan/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/222.3345.118/IntelliJ IDEA
      CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 00008101-00060D321440001E • ios            • iOS
      15.5 19F77
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 12.4 21F79 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @RyanRamchandar, Thanks for filing the issue. I am able to reproduce the issue on Android too. On relaunching the app the pageview is not rendered and a red container is displayed. But this is not reproducible on the latest master and the beta channel. So I believe this issue is fixed and should land on the stable channel in the upcoming stable release.
You may verify this by switching to beta/master by running 

```
flutter channel beta
flutter upgrade
```  

<details>
<summary>logs(stable)</summary>

```
mahesh@Maheshs-MacBook-Air-M1 sample % flutter run --release
Launching lib/main.dart on Redmi K20 Pro in release mode...
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.30/5fd47535cc85f9e24996f939c2de6583991481b0/kotlin-stdlib-jdk8-1.5.30.jar (version 1.5)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1.6.21.jar (version 1.6)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-stdlib-common-1.6.21.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.30/5fd47535cc85f9e24996f939c2de6583991481b0/kotlin-stdlib-jdk8-1.5.30.jar (version 1.5)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1.6.21.jar (version 1.6)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-stdlib-common-1.6.21.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
Running Gradle task 'assembleRelease'...                           36.5s
✓  Built build/app/outputs/flutter-apk/app-release.apk (6.2MB).
Installing build/app/outputs/flutter-apk/app.apk...                 4.4s

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter ( 1332): Null check operator used on a null value
I/flutter ( 1332): #0      _PagePosition.applyViewportDimension (package:flutter/src/widgets/page_view.dart:455)
I/flutter ( 1332): #1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1456)
I/flutter ( 1332): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #18     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545)
I/flutter ( 1332): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #57     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462)
I/flutter ( 1332): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #61     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749)
I/flutter ( 1332): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter ( 1332): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter ( 1332): #77     RenderView.performLayout (package:flutter/src/rendering/view.dart:165)
I/flutter ( 1332): #78     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757)
I/flutter ( 1332): #79     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887)
I/flutter ( 1332): #80     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504)
I/flutter ( 1332): #81     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892)
I/flutter ( 1332): #82     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370)
I/flutter ( 1332): #83     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
I/flutter ( 1332): #84     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083)
I/flutter ( 1332): #85     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997)
I/flutter ( 1332): #89     _invoke (dart:ui/hooks.dart:151)
I/flutter ( 1332): #90     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
I/flutter ( 1332): #91     _drawFrame (dart:ui/hooks.dart:115)
I/flutter ( 1332): (elided 3 frames from dart:async)
```
</details>   

Closing as fixed on beta and master.

**Comment by RyanRamchandar** [comment]
@maheshmnj I can confirm that on iOS this is fixed in beta and master. Thanks for checking that on Android.

As there is no release date for the next stable version, is there a workaround for apps that are broken in this release?

**Comment by maheshmnj** [comment]
Unfortunately, I am not aware of any such workaround. My guess is there should be a new stable release soon considering it gets released every quarter, last stable release was on 12/05/2022

<img width="961" alt="image" src="https://user-images.githubusercontent.com/31410839/183784979-d26047ce-5894-439e-9620-fbdfeffb2fc6.png">

You may read more about the release process here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels
