### ISSUE TITLE
Image.asset throws `Unable to load asset` when the filename contains space

### ISSUE THREAD

**Issue by Anas35** [flutter/flutter#109195]
## Steps to Reproduce

Clone https://github.com/Anas35/Demo and run in latest beta verison, You will see Actual result.

Change version and run the same application in the stable branch, You will Expected result. 

**Expected results:** 

![Screenshot_1660017428](https://user-images.githubusercontent.com/65850618/183562417-91d6426a-6cc3-4d16-94ea-600f51baf17d.png)

**Actual results:** 

![Screenshot_1660016779](https://user-images.githubusercontent.com/65850618/183562129-764aa982-cde1-4cdb-8533-8fa9c04dacd1.png)

*Exception:*

```
════════ Exception caught by image resource service ════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: assets/Flutter Logo.png.

When the exception was thrown, this was the stack
#0      PlatformAssetBundle.loadBuffer
#1      AssetBundleImageProvider._loadAsync
#2      AssetBundleImageProvider.loadBuffer
#3      ImageProvider.resolveStreamForKey.<anonymous closure>
#4      ImageCache.putIfAbsent
#5      ImageProvider.resolveStreamForKey
#6      ScrollAwareImageProvider.resolveStreamForKey
#7      ImageProvider.resolve.<anonymous closure>
#8      ImageProvider._createErrorHandlerAndKey.<anonymous closure>
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "assets/Flutter Logo.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#71b20(), name: "assets/Flutter Logo.png", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════
```
 
**Flutter doctor:**
```
flutter doctor -v
[√] Flutter (Channel beta, 3.3.0-0.2.pre, on Microsoft Windows [Version 10.0.19043.1826], locale en-IN)
    • Flutter version 3.3.0-0.2.pre on channel beta at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ac27ac8e6 (6 days ago), 2022-08-02 14:35:08 -0700
    • Engine revision d1e7dc18bf
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at -\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.70.0)
    • VS Code at -\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1826]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 103.0.1264.44

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by jonahwilliams** [comment]
Possibly an issue with expected URI encoding missing from the new image loading path. Thanks for the heads up!

**Comment by maheshmnj** [comment]
#### Desktop

Mac             |  Windows
:-------------------------:|:-------------------------:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/31410839/183591014-067285d7-4efc-40b2-b779-86d8e98cd494.png"> | <img src="https://user-images.githubusercontent.com/31410839/183592017-8efdf325-b399-47a3-9a90-9d57f2b82746.png" width ="300"> 

### Web 

<img width="869" alt="image" src="https://user-images.githubusercontent.com/31410839/183591856-adb2a0fd-524b-4cda-9896-25984ecafc19.png">


Android |  IOS
:-------------------------:|:-------------------------:
![Screenshot_1660030440](https://user-images.githubusercontent.com/31410839/183591462-86f15592-048b-42aa-a15a-b1f531d36d94.png) | 


<details>
<summary>logs(windows)</summary>

```
PS C:\Users\mahesh\Desktop\ice_live_viewer> flutter run -d windows

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Running "flutter pub get" in ice_live_viewer...                     4.0s
Launching lib\main.dart on Windows in debug mode...
Building Windows application...                                         
Syncing files to device Windows...                                 177ms

Flutter run key commands.
r Hot reload. 
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).       
c Clear the screen
q Quit (terminate the application on the device).

 Running with sound null safety 

An Observatory debugger and profiler on Windows is available at:
http://127.0.0.1:51246/EFWCfsYIuAQ=/

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE
╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: assets/sample image.jpg.

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:272:7)    
#1      AssetBundleImageProvider._loadAsync
(package:flutter/src/painting/image_provider.dart:731:35)
#2      AssetBundleImageProvider.loadBuffer
(package:flutter/src/painting/image_provider.dart:695:14)
#3      ImageProvider.resolveStreamForKey.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:513:13)
#4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:384:22)
#5      ImageProvider.resolveStreamForKey
(package:flutter/src/painting/image_provider.dart:511:81)
#6      ScrollAwareImageProvider.resolveStreamForKey
(package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#7      ImageProvider.resolve.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:358:9)
#8      ImageProvider._createErrorHandlerAndKey.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:473:24)
<asynchronous suspension>

Image provider: AssetImage(bundle: null, name: "assets/sample image.jpg")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#468ee(), name: "assets/sample
image.jpg",
  scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
The Flutter DevTools debugger and profiler on Windows is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:51246/EFWCfsYIuAQ=/

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.

Another exception was thrown: Unable to load asset: assets/sample image.jpg.
Lost connection to device.
```
</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Image.asset('assets/flutter dash.png'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details> 


<details>
<summary>logs (macos)</summary>

```
mahesh@Maheshs-MacBook-Air-M1 sample % flutterm run -d all
Could not load custom device from config index 0: Expected enabled to be a boolean.
Using hardware rendering with device sdk gphone arm64. If you notice graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Redmi K20 Pro in debug mode...
Launching lib/main.dart on sdk gphone arm64 in debug mode...
Launching lib/main.dart on macOS in debug mode...
objc[34550]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1dfbdb640) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1089442c8). One of the two will be used. Which one is undefined.
objc[34550]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1dfbdb690) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108944318). One of the two will be used. Which one is undefined.
objc[34550]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1dfbdb458) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1089444f8). One of the two will be used. Which one is undefined.
objc[34550]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1dfbdb4a8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108944548). One of the two will be used. Which one is undefined.
objc[34550]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1dfbdb4f8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108944598). One of the two will be used. Which one is undefined.
objc[34550]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1dfbdb548) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1089445e8). One of the two will be used. Which one is undefined.
objc[34550]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1dfbdb598) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108944638). One of the two will be used. Which one is undefined.
objc[34550]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1dfbdb5e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108944688). One of the two will be used. Which one is undefined.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-0019553C36F2001E }
{ platform:macOS, arch:x86_64, id:00008103-0019553C36F2001E }
Running Gradle task 'assembleDebug'...                             11.3s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              1,984ms
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                17.8s
Syncing files to device Redmi K20 Pro...                           259ms
Syncing files to device sdk gphone arm64...                        180ms
Syncing files to device macOS...                                   141ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Redmi K20 Pro is available at: http://127.0.0.1:58109/fX_RE7PB4uU=/
An Observatory debugger and profiler on sdk gphone arm64 is available at: http://127.0.0.1:58113/LGiMNlISvcM=/
An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:58117/kVV_XPacrwQ=/

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: assets/flutterdash.png.

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:272:7)
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:731:35)
#2      AssetBundleImageProvider.loadBuffer (package:flutter/src/painting/image_provider.dart:695:14)
#3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:513:13)
#4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:384:22)
#5      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:511:81)
#6      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:358:9)
#8      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:473:24)
<asynchronous suspension>

Image provider: AssetImage(bundle: null, name: "assets/flutterdash.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#56f69(), name: "assets/flutterdash.png",
  scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
The Flutter DevTools debugger and profiler on Redmi K20 Pro is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:58109/fX_RE7PB4uU=/
The Flutter DevTools debugger and profiler on sdk gphone arm64 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:58113/LGiMNlISvcM=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:58117/kVV_XPacrwQ=/
I/.example.sampl(12672): ProcessProfilingInfo new_methods=986 is saved saved_to_disk=1 resolve_classes_delay=8000
D/SurfaceView(12672): UPDATE null, mIsCastMode = false

Another exception was thrown: Unable to load asset: assets/flutterdash.png.

Another exception was thrown: Unable to load asset: assets/flutterdash.png.
Application finished.
```
</details> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2009, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2009 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9d96c7b8be (3 days ago), 2022-08-01 00:39:06 -0400
    • Engine revision cf0db3e546
    • Dart version 2.19.0 (build 2.19.0-49.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale en-IN)
    • Flutter version 3.0.5 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.0)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[√] Flutter (Channel master, 3.1.0-0.0.pre.2057, on Microsoft Windows [Version 10.0.19044.1826], locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2057 on channel master at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a880c4ed35 (6 days ago), 2022-08-03 04:29:18 -0400
    • Engine revision 05228ad454
    • Dart version 2.19.0 (build 2.19.0-59.0.dev)
    • DevTools version 2.16.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0) 
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)   
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)      • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 104.0.5112.79
    • Edge (web)             • edge             • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
