### ISSUE TITLE
[google_maps_flutter] Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.d.c()' on a null object reference

### ISSUE THREAD

**Issue by aea91** [flutter/flutter#109236]
The flutter app is based on the location tracking.

App crash suddenly and close the location service running on the background.

package: google_maps_flutter: ^2.0.11

Flutter Doctor:
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] VS Code (version 1.67.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

The error shown on the Firebase Crashlytics
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.d.c()' on a null object reference
       at io.flutter.plugins.googlemaps.GoogleMapController.lambda$destroyMapViewIfNecessary$0(GoogleMapController.java:2)
       at io.flutter.plugins.googlemaps.GoogleMapController.lambda$destroyMapViewIfNecessary$0$GoogleMapController(GoogleMapController.java)
       at io.flutter.plugins.googlemaps.-$$Lambda$GoogleMapController$z5trzuhb4pJJGItyEPmCMiQOtYA.run(lambda:2)
       at io.flutter.plugins.googlemaps.GoogleMapController$2.doFrame(GoogleMapController.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1140)
       at android.view.Choreographer.doCallbacks(Choreographer.java:946)
       at android.view.Choreographer.doFrame(Choreographer.java:870)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8118)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by huycozy** [comment]
Hi @aea91 
Is this issue reproducible locally? If so, can you please share the output of `flutter run -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
And could you please provide the full crash log (if it's too long, please save it to a file and attach the file here) and affected device list?

**Comment by Osama0habib** [comment]
This issue only happened on flutter 3+ ....to be more specific flutter 3 embedded dart versions... when downgrading flutter and keep the flutter 3+ dart version the issue stell happens to solve this issue i downgrade flutter and used dart version comming with that flutter version...


This issue happened when i keep reopen map widget and fasly reclosing it..

I notice an animation happen while popping widget "dispose" in older version of dart sdk ... that behaviour prevents map from crashing ...

Or i can delay disposing if that issue still

I hope this issue to be solved i want to upgrade flutter without affecting user experience
