### ISSUE TITLE
late final incorrectly claims to already be initialized

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#109261]
Use `compute` from flutter foundation with a function that asynchronously throws an error. The following stack trace is printed.

```
E/flutter (27630): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Local 'computationResult' has already been initialized.
E/flutter (27630): #0      LateError._throwLocalAlreadyInitialized (dart:_internal-patch/internal_patch.dart:214)
E/flutter (27630): #1      _spawn (package:flutter/src/foundation/_isolates_io.dart:129)
E/flutter (27630): <asynchronous suspension>
```

The code is as follows: It does not seem possible for `computationResult` to be set twice

```dart
/// The spawn point MUST guarantee only one result event is sent through the
/// [SendPort.send] be it directly or indirectly i.e. [Isolate.exit].
///
/// In case an [Error] or [Exception] are thrown AFTER the data
/// is sent, they will NOT be handled or reported by the main [Isolate] because
/// it stops listening after the first event is received.
///
/// Also use the helpers [_buildSuccessResponse] and [_buildErrorResponse] to
/// build the response
Future<void> _spawn<Q, R>(_IsolateConfiguration<Q, R> configuration) async {
  late final List<dynamic> computationResult;

  try {
    computationResult = _buildSuccessResponse(await configuration.applyAndTime());
  } catch (e, s) {
    computationResult = _buildErrorResponse(e, s);
  }

  Isolate.exit(configuration.resultPort, computationResult);
}
```

**Comment by jonahwilliams** [comment]
I only observed this in release mode

**Comment by jonahwilliams** [comment]
maybe @alexmarkov ?

**Comment by alexmarkov** [comment]
Small repro:

```dart
main() {
  late final int computationResult;

  try {
    throw 'bye';
  } catch (e, s) {
    computationResult = 42;
  }
}
```

**Comment by alexmarkov** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/254440.

**Comment by alexmarkov** [comment]
The fix rolled into Flutter in https://github.com/flutter/flutter/commit/1dfa8477852025491fd90f01164343df9fde46d3.
