### ISSUE TITLE
[AnimatedController] unsafe setState cause an exception in test unit

### ISSUE THREAD

**Issue by LongXiangGuo** [flutter/flutter#109378]
## The AnimatedController did not check mounted before the setState method, cause an exception in my project

```
The following assertion was thrown while notifying status listeners for AnimationController:

setState() or markNeedsBuild() called during build.

This WeeklyChartContentLoading widget cannot be marked as needing to build because the framework is

already in the process of building widgets. A widget can be marked as needing to be built during the

build phase only if one of its ancestors is currently building. This exception is allowed because

the framework builds parent widgets before children, which means a dirty descendant will always be

built. Otherwise, the framework might not visit this widget during this build phase.

The widget on which setState() or markNeedsBuild() was called was:

  WeeklyChartContentLoading

The widget which was currently being built when the offending call was made was:

  JoyPadding


When the exception was thrown, this was the stack:

#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4424:11)

#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4439:6)

#2      State.setState (package:flutter/src/widgets/framework.dart:1141:15)

#3      _WeeklyChartContentLoadingState.build.<anonymous closure> (package:bmw_points/src/activity/widgets/weekly_chart/weekly_chart_content_loading.dart:329:43)

#4      ImplicitlyAnimatedWidgetState.initState.<anonymous closure> (package:flutter/src/widgets/implicit_animations.dart:372:25)

#5      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:233:19)

#6      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:815:7)

```

- The setState in `_handleAnimationChanged ` not check the widget is mounted or not, when AnimatedController embed as the child in parent widget.
```
AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:815:7)


abstract class AnimatedWidgetBaseState<T extends ImplicitlyAnimatedWidget> extends ImplicitlyAnimatedWidgetState<T> {
  @override
  void initState() {
    super.initState();
    controller.addListener(_handleAnimationChanged);
  }

  void _handleAnimationChanged() {
    setState(() { /* The animation ticked. Rebuild with new animation value */ });
  }
}

``` 

## Flutter doctor
```
[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.5 21G72 darwin-x64, locale
    en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[✓] VS Code (version 1.70.0)
[✓] Connected device (1 available)
    ! Error: US的iPhone is not connected. Xcode will continue when US的iPhone is
      connected and unlocked. (code -13)
[✓] HTTP Host Availability
```

**Comment by LongXiangGuo** [comment]
any update?

**Comment by maheshmnj** [comment]
Hi @LongXiangGuo, Thanks for filing the issue. Inorder to investigate the issue further we would need a minimal and complete code sample.

**Comment by LongXiangGuo** [comment]
I have both tried the project and example code locally on Mac but there is no such problem. But the jenkins  server some times throw the error above.

example code

````
import 'package:flutter/material.dart';
import 'dart:core';
import 'dart:math';

import 'package:flutter/scheduler.dart';

void main(List<String> args) {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: IssueWidget(
        itemCount: 200,
      ),
    );
  }
}

class IssueWidget extends StatefulWidget {
  final int itemCount;

  const IssueWidget({
    Key? key,
    required this.itemCount,
  }) : super(key: key);

  @override
  _IssueWidgetState createState() => _IssueWidgetState();
}

class _IssueWidgetState extends State<IssueWidget> {
  @override
  void initState() {
    super.initState();

    SchedulerBinding.instance!.addPostFrameCallback((timeStamp) {
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        ShaderMask(
          shaderCallback: (rect) {
            return const LinearGradient(
              begin: Alignment.centerRight,
              end: Alignment.centerLeft,
              colors: [Colors.black, Colors.transparent],
            ).createShader(
              Rect.fromLTRB(0, 0, 30, rect.height),
            );
          },
          blendMode: BlendMode.dstIn,
          child: Container(
            constraints: const BoxConstraints().loosen().tighten(height: 150),
            child: Stack(
              clipBehavior: Clip.none,
              children: [
                Positioned.fill(
                  top: -12,
                  left: -16,
                  right: widget.itemCount > 8 ? 0 : 46,
                  child: SizedBox(
                    key: const Key('__container__'),
                    height: 162,
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.end,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        for (var i = 0; i < widget.itemCount; i++) ...[
                          Flexible(
                            flex: 8,
                            child: ShaderMask(
                              shaderCallback: (rect) {
                                return const LinearGradient(
                                  begin: Alignment.centerRight,
                                  end: Alignment.centerLeft,
                                  colors: [Colors.transparent, Colors.black],
                                ).createShader(
                                  Rect.fromLTRB(
                                    0,
                                    0,
                                    i == 8 ? rect.width / 2.5 : 0,
                                    i == 8 ? rect.height : 0,
                                  ),
                                );
                              },
                              blendMode: BlendMode.dstIn,
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.end,
                                children: [
                                  Padding(
                                    padding: const EdgeInsets.only(
                                      right: 16,
                                      bottom: 8,
                                    ),
                                    child: AnimatedContainer(
                                      color: Colors.blue,
                                      onEnd: () {
                                        if (mounted) {
                                          print('object');
                                        }
                                      },
                                      height: () {
                                        return Random().nextInt(20).toDouble();
                                      }(),
                                      duration: () {
                                        return const Duration(seconds: 1600);
                                      }(),
                                      curve: Curves.easeIn,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

```

**Comment by maheshmnj** [comment]
Thanks for the code sample @LongXiangGuo, I ran your code sample and unfortunately it doesn't seem to render anything nor do I see any error in the console. Can you please recheck if the code sample is correct and is working as intended locally? And then we can investigate what could be wrong in your deployed environment.

Also please ensure you are using the latest stable version of flutter `3.0.5`.


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
