### ISSUE TITLE
FlutterEngineConnectionRegistry `getIntent().getBooleanExtra()` throws NullPointerException (NPE）

### ISSUE THREAD

**Issue by JunhuaLin** [flutter/flutter#109364]
`FlutterEngineConnectionRegistry activity.getIntent().getBooleanExtra()` throws NPE

```java
boolean useSoftwareRendering = activity.getIntent().getBooleanExtra("enable-software-rendering", false);
```

The return result from `getIntent()` may be null

<details>
<summary>FlutterEngineConnectionRegistry.java on flutter 3.0.5</summary>

<img width="1200" alt="企业微信截图_22c4197e-486e-4f37-b4e2-45e8d4b86143" src="https://user-images.githubusercontent.com/20511081/184053077-5023e6bb-a6a4-4aef-8e0f-c4f3cf5ff506.png">

</details>

<details>
<summary>Activity.java：The intent is nullable</summary>

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/20511081/184053268-033c445f-82f6-44af-a18f-d82c0688de14.png">

</details>

<details>
<summary>FlutterEngineConnectionRegistry.java on flutter 2.5.3: There is no problem</summary>

<img width="1200" alt="企业微信截图_bd3bd11e-6f32-49ee-97cd-0ef73ca733ef" src="https://user-images.githubusercontent.com/20511081/184053354-e10d373e-fe69-4d74-aa8a-19bb177b526b.png">

</details>

```
➜  ~ flutter doctor --verbose
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6 20G165 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.0.5 at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/junhualin/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by JunhuaLin** [comment]
The logic of the code is obviously wrong, so why example？

**Comment by JunhuaLin** [comment]
There is an example of NPE for getIntent() !
https://github.com/JunhuaLin/npe_flutter_exmple

**Comment by exaby73** [comment]
I can reproduce this issue on stable and master. I can confirm it works on `2.10.5`.

<details>
<summary>Crash logs</summary>

```
E/AndroidRuntime(18087): FATAL EXCEPTION: main
E/AndroidRuntime(18087): Process: com.example.npe.npe_example, PID: 18087
E/AndroidRuntime(18087): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
E/AndroidRuntime(18087): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivityInternal(FlutterEngineConnectionRegistry.java:336)
E/AndroidRuntime(18087): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:324)
E/AndroidRuntime(18087): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:189)
E/AndroidRuntime(18087): 	at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:777)
E/AndroidRuntime(18087): 	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
E/AndroidRuntime(18087): 	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
E/AndroidRuntime(18087): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
E/AndroidRuntime(18087): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime(18087): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime(18087): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
E/AndroidRuntime(18087): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
E/AndroidRuntime(18087): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
E/AndroidRuntime(18087): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
E/AndroidRuntime(18087): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
E/AndroidRuntime(18087): 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
E/AndroidRuntime(18087): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
E/AndroidRuntime(18087): 	at android.app.Activity.performStart(Activity.java:8315)
E/AndroidRuntime(18087): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3701)
E/AndroidRuntime(18087): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(18087): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(18087): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(18087): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(18087): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(18087): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18087): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(18087): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(18087): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(18087): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18087): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(18087): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
    • Flutter version 3.0.5 at C:\Users\Nabeel Parkar\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at C:\Users\Nabeel Parkar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.47

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2246, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2246 on channel master at C:\Users\Nabeel Parkar\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision edea0f0c1c (30 minutes ago), 2022-08-12 03:21:24 -0400
    • Engine revision 913f6b23e2
    • Dart version 2.19.0 (build 2.19.0-91.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at C:\Users\Nabeel Parkar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.47

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
