### ISSUE TITLE
Semantics for a home page won't render when going back after a --route load

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10948]
Turn on accessibility.
In the stocks example, run `flutter run --route '/stock:AAL'` (this requires Android until https://github.com/flutter/flutter/issues/10947 is fixed), then, once the page is showing, hit back.

cc @goderbauer

**Comment by goderbauer** [comment]
I see the following exception in the log right after `flutter run --route '/stock:AAL'` even before hitting the back button:

```
I/flutter (15253): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (15253): The following assertion was thrown during _updateSemantics():
I/flutter (15253): 'package:flutter/src/rendering/object.dart': Failed assertion: line 2571: '_semantics != null': is
I/flutter (15253): not true.
I/flutter (15253): 
I/flutter (15253): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15253): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15253): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15253):   https://github.com/flutter/flutter/issues/new
I/flutter (15253): 
I/flutter (15253): When the exception was thrown, this was the stack:
I/flutter (15253): #2      RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2571)
I/flutter (15253): #3      RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #4      RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #5      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #6      RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #7      RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #8      RenderBox&ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3127)
I/flutter (15253): #9      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #10     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #11     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #12     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #13     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #14     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #15     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #16     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #17     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #18     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #19     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #20     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #21     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #22     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #23     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #24     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #25     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #26     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #27     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #28     RenderBox&ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3127)
I/flutter (15253): #29     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #30     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #31     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #32     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #33     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #34     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #35     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #36     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #37     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #38     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #39     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #40     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #41     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #42     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #43     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #44     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #45     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #46     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #47     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #48     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #49     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #50     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #51     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #52     RenderBox&ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3127)
I/flutter (15253): #53     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #54     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #55     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #56     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #57     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #58     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #59     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #60     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #61     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #62     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #63     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #64     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #65     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #66     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #67     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #68     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #69     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #70     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #71     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #72     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:2522)
I/flutter (15253): #73     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #74     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #75     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #76     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #77     RenderOffstage.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:2631)
I/flutter (15253): #78     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #79     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #80     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #81     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #82     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #83     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #84     RenderBox&ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3127)
I/flutter (15253): #85     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #86     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #87     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #88     _RenderTheatre.visitChildrenForSemantics (package:flutter/src/widgets/overlay.dart:591)
I/flutter (15253): #89     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #90     RenderObject._getSemanticsFragment.<anonymous closure> (package:flutter/src/rendering/object.dart:2584)
I/flutter (15253): #91     RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2849)
I/flutter (15253): #92     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2630)
I/flutter (15253): #93     RenderObject._getSemanticsFragment (package:flutter/src/rendering/object.dart:2576)
I/flutter (15253): #94     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2552)
I/flutter (15253): #95     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1197)
I/flutter (15253): #96     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:255)
I/flutter (15253): #97     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:504)
I/flutter (15253): #98     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189)
I/flutter (15253): #99     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:688)
I/flutter (15253): #100    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:636)
I/flutter (15253): #101    _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:70)
I/flutter (15253): (elided 2 frames from class _AssertionError)
I/flutter (15253): 
I/flutter (15253): The following RenderObject was being processed when the exception was fired:
I/flutter (15253):   RenderSemanticsAnnotations#159bf
I/flutter (15253):   creator: Semantics ← FocusScope ← AbsorbPointer ← Listener ←
I/flutter (15253):   Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#f763d] ← Title ← LocaleQuery ←
I/flutter (15253):   MediaQuery ← DefaultTextStyle ← CustomPaint ← Banner ← CheckedModeBanner ← ⋯
I/flutter (15253):   parentData: <none> (can use size)
I/flutter (15253):   constraints: BoxConstraints(w=411.4, h=683.4)
I/flutter (15253):   semantics: SemanticsNode(1 (dirty); Rect.fromLTRB(0.0, 0.0, 411.4, 683.4) scaled by 3.5x)
I/flutter (15253):   semantic boundary
I/flutter (15253):   size: Size(411.4, 683.4)
I/flutter (15253): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (15253):   _RenderTheatre#68cb6
I/flutter (15253):     RenderStack#9a2fa
I/flutter (15253):       RenderIgnorePointer#c1b7d
I/flutter (15253):         RenderBlockSemantics#b5fd9
I/flutter (15253):           RenderExcludeSemantics#116d1
I/flutter (15253):       RenderSemanticsAnnotations#1f47d
I/flutter (15253):         RenderOffstage#40bb8
I/flutter (15253):           RenderIgnorePointer#d0017
I/flutter (15253):       RenderIgnorePointer#d88c7
I/flutter (15253):         RenderBlockSemantics#02dcb
I/flutter (15253):           RenderExcludeSemantics#2a422
I/flutter (15253):       RenderSemanticsAnnotations#33fec
I/flutter (15253):         RenderOffstage#0c7bb
I/flutter (15253):           RenderIgnorePointer#91292
I/flutter (15253): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Fallenstedt** [comment]
Hello, 

I am experiencing something somewhat similar in the app I am developing. I have numerous screens and can navigate between them properly. However, when using a screen reader I notice that the previous page's text is read instead of the current page!

As an example. 

* I am on `screen1`. Using text to speech, I can hear audio of contents on `screen1`. 
* I tap on a button which calls `Navigator.of(context).pushReplacementNamed('/screen2')`
* `screen2` loads. Using text to speech, I can hear audio of contents on `screen1` still. It's expected that I hear contents of `screen2`. 

I look forward to Milestone 4!

**Comment by chunhtai** [comment]
@Fallenstedt To make us debugging easier, can you provide a minimal reproducible example?

**Comment by markusaksli-nc** [comment]
Hi @Hixie 
This issue no longer seems reproducible on the latest master `1.20.0-8.0.pre.102`.
This is the case in both the heavily outdated stocks example (after fixing it) and in this small sample:
<details>
 <summary>Sample code</summary>
Use flutter run --route '/second'

 ```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: "Routing",
    initialRoute: '/',
    onGenerateRoute: (settings) {
      return RouteGenerator.generateRoute(settings);
    },
    home: FirstRoute(),
  ));
}

class FirstRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Open route'),
          onPressed: () {
            Navigator.pushNamed(context, '/second');
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}

class RouteGenerator {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case '/':
        return MaterialPageRoute(builder: (_) => FirstRoute());
      case '/second':
        return MaterialPageRoute(
          builder: (_) => SecondRoute(),
        );
      default:
        // If there is no such named route in the switch statement, e.g. /third
        return _errorRoute();
    }
  }

  static Route<dynamic> _errorRoute() {
    return MaterialPageRoute(builder: (_) {
      return Scaffold(
        appBar: AppBar(
          title: Text('Error'),
        ),
        body: Center(
          child: Text('ERROR'),
        ),
      );
    });
  }
}

```
</details>
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.20.0-8.0.pre.102, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.20.0-8.0.pre.102 at C:\Development\flutter_master
    • Framework revision f95f46e910 (4 hours ago), 2020-07-15 01:46:01 -0400
    • Engine revision be7595bafb
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```
</details>

Can you confirm?
Thank you

**Comment by markusaksli-nc** [comment]
Closing as probably fixed, feel free to reopen if this is not the case.
