### ISSUE TITLE
[Windows 7] App crashes immediately if using master channel

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#109412]
## Steps to Reproduce

On a Windows 7 computer:

1. Switch to Flutter's master channel
2. Checkout flutter repo and navigate to [`hello_world` app](https://github.com/flutter/flutter/tree/master/examples/hello_world): `cd examples/hello_world`
3. Run it `flutter run -d windows`

**Expected results:** An app launches with text `Hello world`

**Actual results:** App crashes:

![image](https://user-images.githubusercontent.com/737941/184231110-46718079-36ec-4664-bf7c-b19c36338914.png)

This issue does not reproduce on Flutter's stable channel.

<details>
<summary>Code sample</summary>

https://github.com/flutter/flutter/tree/master/examples/hello_world

</details>

<details>
  <summary>Logs</summary>

```
[  +86 ms] executing: [C:\Users\gspencer\code\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +79 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[        ] executing: [C:\Users\gspencer\code\flutter/] git tag --points-at 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[  +43 ms] Exit code 0 from: git tag --points-at 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[   +2 ms] executing: [C:\Users\gspencer\code\flutter/] git describe --match *.*.* --long --tags 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[ +127 ms] Exit code 0 from: git describe --match *.*.* --long --tags 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[   +1 ms] 3.0.0-0.0.pre-849-g6aaabf6d56
[  +62 ms] executing: [C:\Users\gspencer\code\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +24 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] fatal: HEAD does not point to a branch
[ +149 ms] Unable to locate an Android SDK.
[   +4 ms] executing: [C:\Users\gspencer\code\flutter/] git rev-parse --abbrev-ref HEAD
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +60 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +84 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +119 ms] Skipping pub get: version match.
[ +211 ms] Generating C:\Users\gspencer\code\flutter\examples\hello_world\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +159 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[  +15 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: C:\Users\gspencer\code\flutter\examples\hello_world\.dart_tool\package_config_subset}
[  +43 ms] gen_dart_plugin_registrant: Complete
[   +8 ms] Skipping target: _composite
[   +3 ms] complete
[   +8 ms] Launching lib\main.dart on Windows in debug mode...
[   +6 ms] C:\Users\gspencer\code\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\gspencer\code\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root C:\Users\gspencer\code\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\gspencer\AppData\Local\Temp\flutter_tools.2d0fb160\flutter_tool.c291f81a\app.dill --packages C:\Users\gspencer\code\flutter\examples\hello_world\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --verbosity=error --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[  +34 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +20 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "9d5f6a15",
               "installDate": "2021-11-03T15:10:06Z",
               "installationName": "VisualStudio/16.11.5+31729.503",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.11.31729.503",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 14906289591156735,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.11#16.11.5",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2021-11-03T15:10:06.1446174Z",
               "catalog": {
                 "buildBranch": "d16.11",
                 "buildVersion": "16.11.31729.503",
                 "id": "VisualStudio/16.11.5+31729.503",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.11.5",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "5",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.11.5+31729.503",
                 "requiredEngineVersion": "2.11.40.25675"
               },
               "properties": {
                 "campaignId": "600132639.1635897622",
                 "channelManifestId": "VisualStudio.16.Release/16.11.5+31729.503",
                 "defaultProgram": "VisualStudio.9d5f6a15",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +2 ms] Building Windows application...
[  +13 ms] <- compile package:hello_world/main.dart
[   +4 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S C:\Users\gspencer\code\flutter\examples\hello_world\windows -B build\windows -G Visual Studio 16 2019
[  +56 ms] -- Selecting Windows SDK version 10.0.22000.0 to target Windows 6.1.7601.
[  +32 ms] -- Configuring done
[ +797 ms] -- Generating done
[  +25 ms] -- Build files have been written to: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows
[  +13 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build build\windows --config Debug --target INSTALL --verbose
[ +209 ms] Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET Framework
[        ] Copyright (C) Microsoft Corporation. All rights reserved.
[  +88 ms] Build started 8/11/2022 1:15:39 PM.
[ +351 ms] Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\INSTALL.vcxproj" on node 1 (default targets).
[        ] Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\INSTALL.vcxproj" (1) is building "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +37 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +43 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
[   +2 ms] Done Building Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\ZERO_CHECK.vcxproj" (default targets).
[ +145 ms] Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\INSTALL.vcxproj" (1) is building "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\ALL_BUILD.vcxproj" (3) on node 1 (default targets).
[        ] Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\ALL_BUILD.vcxproj" (3) is building "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\flutter\flutter_wrapper_app.vcxproj" (4) on node 1 (default targets).
[        ] Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\flutter\flutter_wrapper_app.vcxproj" (4) is building "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\flutter\flutter_assemble.vcxproj" (5) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +31 ms] CustomBuild:
[        ]   "The build of 'C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\CMakeFiles\d89b9640d4ad5b40328688cb204e8724\flutter_assemble.rule' depends on 'C:\USERS\GSPENCER\CODE\FLUTTER\EXAMPLES\HELLO_WORLD\WINDOWS\FLUTTER\EPHEMERAL\FLUTTER_WINDOWS.DLL' which is produced by the build of 'C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\CMakeFiles\d26855d1e97cb3540500425ddf3e7186\flutter_windows.dll.rule'. The items cannot be built in parallel."
[  +76 ms]   Generating C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/flutter_windows.dll, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/flutter_export.h, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/flutter_windows.h, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/flutter_messenger.h, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/flutter_plugin_registrar.h, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/flutter_texture_registrar.h, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/cpp_client_wrapper/core_implementations.cc, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/cpp_client_wrapper/standard_codec.cc, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/cpp_client_wrapper/plugin_registrar.cc, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/cpp_client_wrapper/flutter_engine.cc, C:/Users/gspencer/code/flutter/examples/hello_world/windows/flutter/ephemeral/cpp_client_wrapper/flutter_view_controller.cc, _phony_
[+1250 ms]   [ +158 ms] executing: [C:\Users\gspencer\code\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +48 ms]   [  +88 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ]   [        ] 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[   +1 ms]   [   +1 ms] executing: [C:\Users\gspencer\code\flutter/] git tag --points-at 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[  +68 ms]   [  +67 ms] Exit code 0 from: git tag --points-at 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[   +1 ms]   [   +3 ms] executing: [C:\Users\gspencer\code\flutter/] git describe --match *.*.* --long --tags 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[ +196 ms]   [ +196 ms] Exit code 0 from: git describe --match *.*.* --long --tags 6aaabf6d569543b982b1d23ac3bf81d3b2667751
[        ]   [        ] 3.0.0-0.0.pre-849-g6aaabf6d56
[ +384 ms]   [ +385 ms] Unable to locate an Android SDK.
[   +5 ms]   [   +6 ms] executing: [C:\Users\gspencer\code\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms]   [  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +7 ms]   [        ] HEAD
[        ]   [        ] executing: [C:\Users\gspencer\code\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +36 ms]   [  +44 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ]   [        ] fatal: HEAD does not point to a branch
[  +66 ms]   [  +67 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms]   [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +181 ms]   [ +181 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ]   [   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +57 ms]   [  +58 ms] Initializing file store
[  +20 ms]   [  +21 ms] Done initializing file store
[  +53 ms]   [  +53 ms] Skipping target: gen_localizations
[  +28 ms]   [  +27 ms] Skipping target: gen_dart_plugin_registrant
[+4741 ms]   [+4741 ms] Skipping target: unpack_windows
[ +421 ms]   [ +420 ms] Skipping target: kernel_snapshot
[ +200 ms]   [ +201 ms] Skipping target: debug_bundle_windows_assets
[        ]   [   +1 ms] Persisting file store
[  +13 ms]   [  +13 ms] Done persisting file store
[   +9 ms]   [   +9 ms] build succeeded.
[  +11 ms]   [  +11 ms] "flutter assemble" took 5,785ms.
[   +4 ms]   [   +4 ms] Running shutdown hooks
[        ]   [        ] Shutdown hooks complete
[   +4 ms]   [   +4 ms] exiting with code 0
[  +79 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "x64\Debug\flutter_assemble\flutter_assemble.tlog\flutter_assemble.lastbuildstate".
[   +2 ms] Done Building Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\flutter\flutter_assemble.vcxproj" (default targets).
[  +11 ms] InitializeBuildStatus:
[        ]   Creating "flutter_wrapper_app.dir\Debug\flutter_.3941F68D.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +5 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +56 ms] ClCompile:
[        ]   All outputs are up-to-date.
[  +23 ms] Lib:
[        ]   All outputs are up-to-date.
[   +1 ms]   flutter_wrapper_app.vcxproj -> C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\flutter\Debug\flutter_wrapper_app.lib
[  +15 ms] FinalizeBuildStatus:
[        ]   Deleting file "flutter_wrapper_app.dir\Debug\flutter_.3941F68D.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "flutter_wrapper_app.dir\Debug\flutter_.3941F68D.tlog\flutter_wrapper_app.lastbuildstate".
[   +1 ms] Done Building Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\flutter\flutter_wrapper_app.vcxproj" (default targets).
[  +40 ms] Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\ALL_BUILD.vcxproj" (3) is building "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (6) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "flutter_wrapper_plugin.dir\Debug\flutter_.84E99C94.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +6 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[   +8 ms] ClCompile:
[        ]   All outputs are up-to-date.
[   +4 ms] Lib:
[        ]   All outputs are up-to-date.
[        ]   flutter_wrapper_plugin.vcxproj -> C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\flutter\Debug\flutter_wrapper_plugin.lib
[  +10 ms] FinalizeBuildStatus:
[        ]   Deleting file "flutter_wrapper_plugin.dir\Debug\flutter_.84E99C94.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "flutter_wrapper_plugin.dir\Debug\flutter_.84E99C94.tlog\flutter_wrapper_plugin.lastbuildstate".
[   +1 ms] Done Building Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (default targets).
[  +35 ms] Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\ALL_BUILD.vcxproj" (3) is building "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\runner\hello_world.vcxproj" (7) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "hello_world.dir\Debug\hello_world.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +25 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +42 ms] ClCompile:
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /IC:\Users\gspencer\code\flutter\examples\hello_world\windows /IC:\Users\gspencer\code\flutter\examples\hello_world\windows\flutter\ephemeral /IC:\Users\gspencer\code\flutter\examples\hello_world\windows\flutter\ephemeral\cpp_client_wrapper\include /Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D _DEBUG /D NOMINMAX /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"hello_world.dir\Debug\\" /Fd"hello_world.dir\Debug\vc142.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue C:\Users\gspencer\code\flutter\examples\hello_world\windows\flutter\generated_plugin_registrant.cc C:\Users\gspencer\code\flutter\examples\hello_world\windows\runner\flutter_window.cpp
[  +48 ms]   generated_plugin_registrant.cc
[ +494 ms]   flutter_window.cpp
[+1053 ms]   Generating Code...
[ +115 ms] ResourceCompile:
[        ]   All outputs are up-to-date.
[  +43 ms] Link:
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\runner\Debug\hello_world.exe" /INCREMENTAL /ILK:"hello_world.dir\Debug\hello_world.ilk" /NOLOGO ..\flutter\Debug\flutter_wrapper_app.lib C:\Users\gspencer\code\flutter\examples\hello_world\windows\flutter\ephemeral\flutter_windows.dll.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /manifestinput:C:\Users\gspencer\code\flutter\examples\hello_world\windows\runner\runner.exe.manifest /DEBUG /PDB:"C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/hello_world.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/hello_world.lib" /MACHINE:X64  /machine:x64 hello_world.dir\Debug\Runner.res
[        ]   hello_world.dir\Debug\flutter_window.obj
[        ]   hello_world.dir\Debug\main.obj
[        ]   hello_world.dir\Debug\utils.obj
[        ]   hello_world.dir\Debug\win32_window.obj
[        ]   hello_world.dir\Debug\generated_plugin_registrant.obj
[ +287 ms]   hello_world.vcxproj -> C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\runner\Debug\hello_world.exe
[  +14 ms] FinalizeBuildStatus:
[        ]   Deleting file "hello_world.dir\Debug\hello_world.tlog\unsuccessfulbuild".
[        ]   Touching "hello_world.dir\Debug\hello_world.tlog\hello_world.lastbuildstate".
[   +2 ms] Done Building Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\runner\hello_world.vcxproj" (default targets).
[  +17 ms] InitializeBuildStatus:
[        ]   Creating "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +9 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +52 ms] FinalizeBuildStatus:
[   +3 ms]   Deleting file "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate".
[   +1 ms] Done Building Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\ALL_BUILD.vcxproj" (default targets).
[  +10 ms] InitializeBuildStatus:
[        ]   Creating "x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +66 ms] PostBuildEvent:
[        ]   setlocal
[        ]   "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
[        ]   if %errorlevel% neq 0 goto :cmEnd
[        ]   :cmEnd
[        ]   endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
[        ]   :cmErrorLevel
[        ]   exit /b %1
[        ]   :cmDone
[        ]   if %errorlevel% neq 0 goto :VCEnd
[        ]   :VCEnd
[  +48 ms]   -- Install configuration: "Debug"
[        ]   -- Up-to-date: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/data/icudtl.dat
[   +1 ms]   -- Up-to-date: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/flutter_windows.dll
[  +15 ms]   -- Installing: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/data/flutter_assets
[   +4 ms]   -- Installing: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/data/flutter_assets/AssetManifest.json
[   +4 ms]   -- Installing: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/data/flutter_assets/FontManifest.json
[   +2 ms]   -- Installing: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/data/flutter_assets/kernel_blob.bin
[ +203 ms]   -- Installing: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/data/flutter_assets/NOTICES.Z
[   +6 ms]   -- Installing: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/data/flutter_assets/shaders
[   +2 ms]   -- Installing: C:/Users/gspencer/code/flutter/examples/hello_world/build/windows/runner/Debug/data/flutter_assets/shaders/ink_sparkle.frag
[  +18 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "x64\Debug\INSTALL\INSTALL.tlog\INSTALL.lastbuildstate".
[   +1 ms] Done Building Project "C:\Users\gspencer\code\flutter\examples\hello_world\build\windows\INSTALL.vcxproj" (default targets).
[   +1 ms] Build succeeded.
[        ]     0 Warning(s)
[        ]     0 Error(s)
[        ] Time Elapsed 00:00:11.50
[  +22 ms] Building Windows application... (completed in 12.7s)
flutter : [  +21 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
At line:1 char:1
+ flutter run -d windows -v *>> output.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([  +21 ms] Erro... never started.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[   +2 ms] Error launching application on Windows.

[   +3 ms] "flutter run" took 13,562ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:709:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> 
(package:flutter_tools/src/runner/flutter_command.dart:1194:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> 
(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>



[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

**Comment by loic-sharma** [comment]
This is the first bad commit: https://github.com/flutter/flutter/commit/080f5d964c9efac74cbec1191c555b4fa13d1fba
