### ISSUE TITLE
[Android] TabBarView makes GridView's items not showing on release version on Android 7.0

### ISSUE THREAD

**Issue by salahmak** [flutter/flutter#109504]
## Steps to Reproduce

1. Build release version of the app.
2. Run it on an Android 7.0 device (or AVD).
4. You see that the GridView doesn't appear and the tabs are empty.

**Expected results:** 
![image](https://user-images.githubusercontent.com/49586511/184549121-85b83d8b-030e-4556-aa2f-f13ffa4d37ce.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/49586511/184549142-dd82cf65-232d-43db-aa39-4df574ded087.png)

<details>
<summary>Code sample</summary>

```dart
// Home page file
import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      child: Scaffold(
        appBar: AppBar(
          bottom: TabBar(
            indicatorColor: Colors.red,
            tabs: [
              Tab(
                text: "All",
              ),
              Tab(
                text: "Watching",
              ),
              Tab(
                text: "Watched",
              ),
            ],
          ),
          title: Text("Home"),
          centerTitle: true,
        ),
        body: TabBarView(
          physics: NeverScrollableScrollPhysics(),
          children: [
            GridView.builder(
              itemCount: 3,
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2, crossAxisSpacing: 8, mainAxisSpacing: 8, mainAxisExtent: 250),
              itemBuilder: (context, index) {
                return Text("test");
              },
            ),
            GridView.builder(
              itemCount: 2,
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2, crossAxisSpacing: 8, mainAxisSpacing: 8, mainAxisExtent: 250),
              itemBuilder: (context, index) {
                return Text("test");
              },
            ),
            GridView.builder(
              itemCount: 1,
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2, crossAxisSpacing: 8, mainAxisSpacing: 8, mainAxisExtent: 250),
              itemBuilder: (context, index) {
                return Text("test");
              },
            ),
          ],
        ),
      ),
    );
  }
}




```

</details>

<details>
  <summary>Logs</summary>

```
Showing SM G928C logs:
I/flutter (  545): Null check operator used on a null value
I/flutter (  545): #0      _PagePosition.applyViewportDimension (package:flutter/src/widgets/page_view.dart:455)
I/flutter (  545): #1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1456)
I/flutter (  545): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #18     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545)
I/flutter (  545): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #22     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
I/flutter (  545): #23     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003)
I/flutter (  545): #24     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
I/flutter (  545): #25     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403)
I/flutter (  545): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #30     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376)
I/flutter (  545): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #65     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462)
I/flutter (  545): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #69     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749)
I/flutter (  545): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
I/flutter (  545): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
I/flutter (  545): #85     RenderView.performLayout (package:flutter/src/rendering/view.dart:165)
I/flutter (  545): #86     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757)
I/flutter (  545): #87     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887)
I/flutter (  545): #88     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504)
I/flutter (  545): #89     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892)
I/flutter (  545): #90     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370)
I/flutter (  545): #91     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
I/flutter (  545): #92     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083)
I/flutter (  545): #93     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997)
I/flutter (  545): #97     _invoke (dart:ui/hooks.dart:151)
I/flutter (  545): #98     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
I/flutter (  545): #99     _drawFrame (dart:ui/hooks.dart:115)
I/flutter (  545): (elided 3 frames from dart:async)
```

```
```

```
```

</details>

### Note:
- When I install and run the release version of the app on an Android 11 emulator or phone, it works fine.
- When I run the release version on an Android 7.0 device, it **doesn't work** and behaves as described above.
- When I run the debug version on an Android 7.0 device (tried on both physical and virtual), it works fine.

So the problem only happens when I run the **release** version on an **Android 7.0** device.

### Edit:
- Reduced code for minimal reproduction

### Edit 2:
- I have tried running the release version on an Android 11 device and it worked fine, but when I have also tried to run it on my Android 7.0 phone or an Android 7.0 virtual device it doesn't (behaves as described above). So we can safely assume that it is a problem with Android 7.0. Thus, I have updated the above issue description to match the new results.

Possibly related issue: [#19692](https://github.com/flutter/flutter/issues/19692) (not solved due to not being able to reproduce from the info provided by the person who opened the issue)

**Comment by salahmak** [comment]
##Update
I have tried to remove the **TabBarView** and only left one **GridView.builder**, and it showed fine, so I guess the combination of **TabBarView** and **GridView.builder** is causing the issue

**Comment by salahmak** [comment]
Here is the code of the MovieCard widget in case if it is relevant to the issue:
```dart
import 'package:flutter/material.dart';
import 'package:movies_tracker/services/global_theme.dart';
import 'package:movies_tracker/services/movie.dart';

class MovieCard extends StatelessWidget {

  late Movie? movie;


  MovieCard({Key? key, required this.movie}) : super(key: key);


  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Positioned.fill(
          bottom: 0,
          child: ClipRRect(
            borderRadius: BorderRadius.circular(15),
            child: GridTile(
              footer: GridTileBar(
                title: Text(movie!.Title,
                    overflow: TextOverflow.ellipsis,
                    maxLines: 1,
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 16)),
                backgroundColor: Color(0xd91e1b26),
              ),
              child: ClipRRect(
                  borderRadius: BorderRadius.circular(15),
                  child: Image.network(
                    movie!.Poster,
                    fit: BoxFit.fitWidth,
                  )),
            ),
          ),
        ),
        Positioned.fill(
          child: Material(
            type: MaterialType.transparency,
            child: InkWell(
              borderRadius: BorderRadius.circular(15),
              onTap: () {},
            ),
          ),
        )
      ],
    );
  }
}


```

**Comment by salahmak** [comment]
## Update: found a weird workaround


When I switch between the tabs many times, it randomly starts showing the elements of the grid after few switches, here is a video to demonstrate it:
https://user-images.githubusercontent.com/49586511/184552089-5a5ddad8-3280-44c7-955c-5f9c60194e8c.mp4

**So what do you think is causing it not show the grid elements until I switch those few times between tabs???**

Also notice the blue ripple effect on the right side of the screen when switching tabs during the first attempts before it starts working.

Now I'm completely confused and convinced that it is a bug in flutter in Android 7.0.

**Comment by chunlee-thong** [comment]
I think the problem is cause by `mainAxisExtent`. From what i see it may cause the viewport error in `PageView` which is use by `TabBarView`. But why does it works on your Android 11 device? Well, that device probably has a viewport width > 500

**Comment by salahmak** [comment]
@chunlee-thong but why does it work with no problem in the debug version and the problem only happens in the release version?

**Comment by huycozy** [comment]
Hi @salahmak. This issue is reproducible on the `stable` channel.
But it seems to have been fixed on `master` & `beta` channels. 

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/184628212-e460cef7-c8a9-49ef-baa3-d60409bd3fd1.mov

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2272, on macOS 12.5 21G72 darwin-x64, locale en-FR)
    • Flutter version 3.1.0-0.0.pre.2272 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ed3238e8ed (6 hours ago), 2022-08-14 20:54:09 -0400
    • Engine revision cc9f4c63b7
    • Dart version 2.19.0 (build 2.19.0-96.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[✓] Flutter (Channel beta, 3.3.0-0.3.pre, on macOS 12.5 21G72 darwin-x64, locale en-FR)
    • Flutter version 3.3.0-0.3.pre on channel beta at /Users/huynq/Documents/GitHub/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c1149878b (5 days ago), 2022-08-10 12:15:36 -0500
    • Engine revision f16e757d5d
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Please try the issue again on the latest `beta` and `master` channels and confirm if this issue is fixed.

**Comment by salahmak** [comment]
@huycozy Oh, is there a way to use master or beta version without having to compile from source?

**Comment by salahmak** [comment]
> @huycozy Oh, is there a way to use master or beta version without having to compile from source?

nvm I have discovered how, I'll try and see

**Comment by salahmak** [comment]
@huycozy changing channel to `master` and building the app worked, so I'm gonna close this.

Thank you so much
