### ISSUE TITLE
[Image_Picker] does not load images in release mode and throws PlatformException when ImageSource.camera

### ISSUE THREAD

**Issue by jonaswre** [flutter/flutter#109549]
I have a similar issue like #72759. 
It's only on release build and using the camera, gallery works. 

I've tried up and downgrading gradle. 
> flutter clean
> changing compiledSdkVersion
> flutter upgrade
> flutter pub upgrade

nothing helps. 

I've create a repo to reproduce. : https://github.com/jonaswre/image_picker_debug

1. Create project ```flutter create image_picker_debug --platforms=android```
2. Install image_picker: ```image_picker: ^0.8.5+3```
3. Update main.dart to open image_picker
4. Run app: ```flutter run --release --verbose```
5. Look at error: 
```
[+10383 ms] E/flutter (29377): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception:
PlatformException(error, null, null, java.lang.NullPointerException
[   +1 ms] E/flutter (29377):   at java.util.Objects.requireNonNull(Objects.java:220)
[        ] E/flutter (29377):   at java.util.Arrays$ArrayList.<init>(Arrays.java:3738)
[        ] E/flutter (29377):   at java.util.Arrays.asList(Arrays.java:3725)
[        ] E/flutter (29377):   at io.flutter.plugins.imagepicker.f.a(Unknown Source:16)
[        ] E/flutter (29377):   at io.flutter.plugins.imagepicker.f.b(Unknown Source:15)
[        ] E/flutter (29377):   at io.flutter.plugins.imagepicker.e$a.b(Unknown Source:2)
[        ] E/flutter (29377):   at io.flutter.plugins.imagepicker.e.E(Unknown Source:6)
[        ] E/flutter (29377):   at io.flutter.plugins.imagepicker.e.J(Unknown Source:10)
[        ] E/flutter (29377):   at io.flutter.plugins.imagepicker.ImagePickerPlugin.a(Unknown Source:229)
[        ] E/flutter (29377):   at w.i$a.a(Unknown Source:17)
[        ] E/flutter (29377):   at j.c.i(Unknown Source:18)
[        ] E/flutter (29377):   at j.c.j(Unknown Source:20)
[        ] E/flutter (29377):   at j.c.f(Unknown Source:0)
[        ] E/flutter (29377):   at j.b.run(Unknown Source:12)
[        ] E/flutter (29377):   at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/flutter (29377):   at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/flutter (29377):   at android.os.Looper.loopOnce(Looper.java:233)
[        ] E/flutter (29377):   at android.os.Looper.loop(Looper.java:344)
[        ] E/flutter (29377):   at android.app.ActivityThread.main(ActivityThread.java:8212)
[        ] E/flutter (29377):   at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (29377):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
[        ] E/flutter (29377):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
[        ] E/flutter (29377): )
[        ] E/flutter (29377): #0      StandardMethodCodec.decodeEnvelope
(package:flutter/src/services/message_codecs.dart:607)
[        ] E/flutter (29377): #1      MethodChannel._invokeMethod
(package:flutter/src/services/platform_channel.dart:167)
[        ] E/flutter (29377): <asynchronous suspension>
[        ] E/flutter (29377): #2      ImagePickerAndroid.getImage
(package:image_picker_android/image_picker_android.dart:161)
[        ] E/flutter (29377): <asynchronous suspension>
[        ] E/flutter (29377): #3      _MyHomePageState._incrementCounter (package:image_picker_debug/main.dart:57)
[        ] E/flutter (29377): <asynchronous suspension>
[        ] E/flutter (29377):


```

flutter doctor -v

```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-DE)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\JonasWrede\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at C:\Users\JonasWrede\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (5 available)
    • AC2003 (mobile)         • 06f28144      • android-arm64  • Android 12 (API 31)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 103.0.1264.44

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

Thanks for the help

**Comment by danagbemava-nc** [comment]
Hi @jonaswre, I can't seem to reproduce this issue.

Does it occur only in release mode or does it reproduce in debug mode as well? 

Also, can you try the plugin example code to see if it works for you or not?

**Comment by jonaswre** [comment]
Hi @danagbemava-nc 
its only with ImageSource.camera and release mode.

**Comment by jonaswre** [comment]
I've tried the example that works. 

I replaced the android folder that was create by "flutter create" with the one from the example. That works. 

https://github.com/jonaswre/image_picker_debug/pull/1

It should be documented if something needs to be changed after "flutter create"

**Comment by danagbemava-nc** [comment]
> I replaced the android folder created by "flutter create" with the one from the example. That works.

I don't think that should be necessary. What happens if you create a new flutter app and just use the code sample from the package without changing anything in the android folder?

**Comment by jonaswre** [comment]
https://github.com/jonaswre/image_picker_debug

This is what I did in this repo!


1. Create project ```flutter create image_picker_debug --platforms=android```
2. Install image_picker: ```image_picker: ^0.8.5+3```
3. Update main.dart to open image_picker
4. Run app: ```flutter run --release --verbose```

**Comment by danagbemava-nc** [comment]
Using the code sample from the plugin and the steps you have outlined in https://github.com/flutter/flutter/issues/109549#issuecomment-1216680538, I cannot reproduce the issue. The camera opens just fine. 

What device(s) do you experience the issue on?

**Comment by jonaswre** [comment]
The sample codes works!!!!! Please try it with my sample code.  Its a freshly created app just with image_picker installed!

**Comment by jonaswre** [comment]
The sample from the plugin is very old it uses gradle 3.3.0

**Comment by jonaswre** [comment]
```
flutter create i_p_test --platform=android
cd .\i_p_test\
flutter pub add image_picker
```
Change the [main.dart](https://github.com/flutter/flutter/files/9352137/main.txt) content. 

Start emulator and then: `flutter run --release --verbose`

If you click on the FAB it won't open the camera and you see the PlatformException in the console.

**Comment by danagbemava-nc** [comment]
I can reproduce it now. 


###  Observations
- This only occurs when the source `ImageSource.camera`
- This works fine in debug mode
- This issue does not reproduce on iOS. 
- The plugin example seems to work fine for some as noted in https://github.com/flutter/flutter/issues/109549#issuecomment-1216698911

Labeling for further investigation. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
      return FloatingActionButton(
        onPressed: () async {
          final ImagePicker _picker = ImagePicker();
          final XFile? image = await _picker.pickImage(source: ImageSource.camera);
        },
      );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (5 available)
    • M2007J20CG (mobile)         • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 13 (API 33) (emulator)
    • Nexus (mobile)              • 00008020-001875E83A38002E • ios            • iOS 15.6 19G71
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2346, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2346 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision adda088bcc (4 hours ago), 2022-08-17 22:59:07 -0400
    • Engine revision a77ead45a8
    • Dart version 2.19.0 (build 2.19.0-108.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (5 available)
    • M2007J20CG (mobile)         • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 13 (API 33) (emulator)
    • Nexus (mobile)              • 00008020-001875E83A38002E • ios            • iOS 15.6 19G71
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[android-camera.log](https://github.com/flutter/flutter/files/9368201/android-camera.log)
[android-gallery.log](https://github.com/flutter/flutter/files/9368202/android-gallery.log)

**Comment by MaiTheLord** [comment]
Is there any progress regarding this, or a workaround, perhaps?

**Comment by MaiTheLord** [comment]
After reviewing the changes at https://github.com/Iconica-Development/flutter_image_picker/pull/2, it seems that adding the following to `android/app/src/main/AndroidManifest.xml` prevents the error.
```xml
<uses-permission android:name="android.permission.CAMERA" />
```
I think this needs more testing, but I guess it should be added to the documentation if it is accurate.

**Comment by jonaswre** [comment]
That's not the resolution but it's works now. 
I didn't change anything. The example I provided seams to work now.

**Comment by StephenWithPH** [comment]
https://github.com/flutter/flutter/issues/109549#issuecomment-1257306145 was the exact solution that worked for me.

When running in _release_ mode on the devices, I got the exact error that started this ticket. Making the permissions change solved it.

When that permission is in place, the first use of `image_picker` in the app causes Android to display the typical permissions ask.

This was consistent on the following physical devices:

![Screen Shot 2023-02-09 at 5 14 47 PM](https://user-images.githubusercontent.com/2990492/217975713-b0f19a23-5285-4379-96e8-1421cc5c93bf.png)

**Comment by MaiTheLord** [comment]
Forgot to share my latest finding regarding this. For me, either adding the permission to the manifest or making sure `androidx.test:core` is an implementation dependency in the app level `build.gradle` fixed it, not sure why.

**Comment by garlicPasta** [comment]
None of the fixes actually working for me. 
It seems to be problem on Xiaomi devices. My Samsung devices work as expected.
