### ISSUE TITLE
API `/api/reset-try-task` complains no targets

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#109626]
When triggering builds:
curl 'http://flutter-dashboard.appspot.com/api/reset-try-task?repo=flutter&pr=109617' -H "X-Flutter-IdToken: $(gcloud auth print-identity-token)"

`ci.yaml validation` fails with (https://github.com/flutter/flutter/pull/109617/checks?check_run_id=7864478375)
```
HTTP 500: flutter/flutter does not have any targets
```

Backend log:
```
2022-08-16 11:19:20.180 PDT
List of files: [Instance of 'PullRequestFile']
2022-08-16 11:19:20.192 PDT
#0 LuciBuildService._targetsToSchedule (package:cocoon_service/src/service/luci_build_service.dart:192:7) #1 LuciBuildService.scheduleTryBuilds (package:cocoon_service/src/service/luci_build_service.dart:175:21) #2 Scheduler.triggerPresubmitTargets (package:cocoon_service/src/service/scheduler.dart:311:30) <asynchronous suspension> #3 ResetTryTask.get (package:cocoon_service/src/request_handlers/reset_try_task.dart:48:5) <asynchronous suspension> #4 RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22) <asynchronous suspension> #5 ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:151:7) <asynchronous suspension> #6 ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:150:5) <asynchronous suspension> #7 main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:248:9) <asynchronous suspension>
2022-08-16 11:19:20.192 PDT
Marking PR #109617 ci.yaml validation as failed
2022-08-16 11:19:20.192 PDT
HTTP 500: flutter/flutter does not have any targets
2022-08-16 11:19:20.192 PDT
neat_cache: reading cache entry for "configgithubToken-flutter/flutter"
2022-08-16 11:19:20.596 PDT
Finished triggering builds for: pr 109617, commit 068fb57d5f82e26bb8ef644ca0f685ede6b214a4, branch flutter-engine-flutter-autoroll-ef1b5fb9-496a-4737-ac42-0052e519411e-1660662541 and slug flutter/flutter}
```

**Comment by keyonghan** [comment]
When no `builders` parameter is specified, the API parses the list incorrectly without excluding the empty string case.
