### ISSUE TITLE
 java.lang.RuntimeException: Unable to destroy activity when used back button

### ISSUE THREAD

**Issue by MohsenHaydari** [flutter/flutter#109666]
after I use `FlutterFragmentActivity` in `MainActivity` When I exit the program  with the android back button, I get the following error 

```
APPNAME keeps stooping
```

flutter logs when pressed back button

 ```
E/AndroidRuntime(11114): FATAL EXCEPTION: main E/AndroidRuntime(11114): Process: com.example.com, 
PID: 11114 E/AndroidRuntime(11114): java.lang.RuntimeException: Unable to destroy activity 
{com.example.com/com.example.com.MainActivity}: java.lang.NullPointerException: Attempt to 
invoke virtual method 'void 
androidx.lifecycle.Lifecycle.removeObserver(androidx.lifecycle.LifecycleObserver)' on a null object 
reference E/AndroidRuntime(11114):        at 
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5111) 
E/AndroidRuntime(11114):        at 
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140) 
E/AndroidRuntime(11114):        at 
android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
E/AndroidRuntime(11114):        at 
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:17 
6) E/AndroidRuntime(11114):        at 
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
E/AndroidRuntime(11114):        at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
E/AndroidRuntime(11114):        at android.os.Handler.dispatchMessage(Handler.java:106) 
E/AndroidRuntime(11114):        at android.os.Looper.loop(Looper.java:223) 
E/AndroidRuntime(11114):        at android.app.ActivityThread.main(ActivityThread.java:7656) 
E/AndroidRuntime(11114):        at java.lang.reflect.Method.invoke(Native Method) 
E/AndroidRuntime(11114):        at 
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
E/AndroidRuntime(11114):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
E/AndroidRuntime(11114): Caused by: java.lang.NullPointerException: Attempt to invoke virtual 
method 'void androidx.lifecycle.Lifecycle.removeObserver(androidx.lifecycle.LifecycleObserver)' on 
a null object reference E/AndroidRuntime(11114):        at 
com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.clearPluginSetup(FlutterBarcodeScannerP 
lugin.java:295)       E/AndroidRuntime(11114):        at 
com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onDetachedFromActivity(FlutterBarcodeSc 
annerPlugin.java:285) E/AndroidRuntime(11114):        at 
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnect 
ionRegistry.java:383) E/AndroidRuntime(11114):        at 
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragment 
Delegate.java:681)    E/AndroidRuntime(11114):        at 
io.flutter.embedding.android.FlutterFragment.onDetach(FlutterFragment.java:878) 
E/AndroidRuntime(11114):        at androidx.fragment.app.Fragment.performDetach(Fragment.java:3370) 
E/AndroidRuntime(11114):        at 
androidx.fragment.app.FragmentStateManager.detach(FragmentStateManager.java:819) 
E/AndroidRuntime(11114):        at 
androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:338) 
E/AndroidRuntime(11114):        at 
androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffect 
sController.java:771) E/AndroidRuntime(11114):        at 
androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:615) 
E/AndroidRuntime(11114):        at 
androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController. 
java:350) E/AndroidRuntime(11114):        at 
androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2971) 
E/AndroidRuntime(11114):        at 
androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2922) 
E/AndroidRuntime(11114):        at 
androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:346) 
E/AndroidRuntime(11114):        at 
androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:259) 
E/AndroidRuntime(11114):        at android.app.Activity.performDestroy(Activity.java:8245) 
E/AndroidRuntime(11114):        at 
android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344) 
E/AndroidRuntime(11114):        at 
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5096)
```
Mainactivity.tk

```
package com.***

import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterFragmentActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}

```
flutter run

```
An Observatory debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:65033/XBYPNJ3Dqw8=/
W/FlutterJNI(14300): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(14300): FlutterJNI.prefetchDefaultFontManager called more than once
I/ResourceExtractor(14300): Found extracted resources res_timestamp-1-1660714336919
W/FlutterJNI(14300): FlutterJNI.init called more than once
I/FLTFireBGExecutor(14300): Creating background FlutterEngine instance, with args: [--enable-dart-profiling]
D/EGL_emulation(14300): eglCreateContext: 0xebcc76a0: maj 2 min 0 rcv 2
D/EGL_emulation(14300): eglCreateContext: 0xebcca880: maj 2 min 0 rcv 2
D/HostConnection(14300): HostConnection::get() New Host Connection established 0xebcc7b70, tid 14376
D/HostConnection(14300): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2
D/EGL_emulation(14300): eglMakeCurrent: 0xebcca880: ver 2 0 (tinfo 0xb7e0c970) (first time)
D/FlutterGeolocator(14300): Geolocator foreground service connected
D/FlutterGeolocator(14300): Initializing Geolocator services
The Flutter DevTools debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:65033/XBYPNJ3Dqw8=/I/FLTFireMsgService(14300): FlutterFirebaseMessagingBackgroundService started!

```

flutter doctor

```
  • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

```
``
thanks

**Comment by exaby73** [comment]
Hello @MohsenHaydari. Can you provide some more information about the issue:

- Are you using [add-to-app](https://docs.flutter.dev/development/add-to-app)?
- Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this issue?
- Can you provide the entire log of running `flutter doctor -v`?

Thank you.

**Comment by MohsenHaydari** [comment]
Problem solved, it was related to a 3rd party plugin
thanks
