### ISSUE TITLE
Null members of the actions property in AppBar should show a more detailed message when asserted

### ISSUE THREAD

**Issue by ArcticZeroo** [flutter/flutter#10961]
## Steps to Reproduce

- Add [this dart file/source](https://github.com/ArcticZeroo/flutter-search-bar/blob/master/lib/src/search_bar_base.dart) somewhere in your app
- Create a StatefulWidget, and inside the State class for that widget, store an instance of SearchBar and initialize it inside the constructor of the State.
- Inside the build method, for the appBar set it equal to `searchBar.get(context)`

My full "app" which has this issue can be found here https://gist.github.com/ArcticZeroo/31f4dc66b0f04d3a97645f1459c143fc#file-main-dart-L58

See the build method on L105 to see how the appBar is built.

When you actually run the app, you'll get a gnarly message in the debugger (which told me to submit this issue!) and the app will have a large red block and yellow lines going all over.

p.s. I know most of the code is probably garbage, so uh.. expect that I guess.

## Logs

Log output: https://gist.github.com/ArcticZeroo/d9ac587b3095e2b086b404003feb3f1a

Flutter analyze only came up with 2 unused imports that should not really cause issues, since the app ran fine before I had SearchBar but still had those unused imports.

## Flutter Doctor
```
[√] Flutter (on Microsoft Windows [Version 10.0.14393], locale en-US, channel master)
    • Flutter at C:\flutter
    • Framework revision 148565eed5 (22 hours ago), 2017-06-23 22:12:30 -0700
    • Engine revision 8a2d337446
    • Tools Dart version 1.24.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Spencer\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4424

[√] Connected devices
    • Pixel XL • HT7540208118 • android-arm • Android 7.1.2 (API 25)
```

**Comment by zoechi** [comment]
Is this issue still relevant?
The linked gist can't be run. It uses a non-existing SearchBar. 
Was this part of Flutter at some point?

**Comment by ArcticZeroo** [comment]
I think it's still relevant, you should probably be able to reproduce by just making an `AppBar` inside a scaffold with a member of the `actions` list set to explicitly null.  

It's non existing because it was renamed, it is now https://github.com/ArcticZeroo/flutter-search-bar/blob/master/lib/src/flutter_search_bar_base.dart

I would try to reproduce it myself but am not at my desktop which has Android Studio installed

**Comment by markusaksli-nc** [comment]
Reproducible on latest master `1.20.0-8.0.pre.125`.
<details>
 <summary>Minimal reproducible sample</summary>

 ```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          actions: [null],
          title: Text('Welcome to Flutter'),
        ),
        body: Container(),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.20.0-8.0.pre.125, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.20.0-8.0.pre.125 at C:\Development\flutter_master
    • Framework revision 9c4a5ef1ed (13 hours ago), 2020-07-15 21:41:27 +0100
    • Engine revision 774ae0313d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 89fe12b12a)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
</details>
<details>
 <summary>Relevant logs</summary>

 ```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building AppBar(dirty, dependencies: [_InheritedTheme,
MediaQuery, _ModalScopeStatus, _LocalizationsScope-[GlobalKey#00d2b]], state: _AppBarState#4eccb):
Row's children must not contain any null values, but a null value was found at index 0

The relevant error-causing widget was:
  AppBar file:///C:/Users/Isa/Google%20Drive/Nevercode/untitled/lib/main.dart:11:17

When the exception was thrown, this was the stack:
#0      new MultiChildRenderObjectWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:1836:11)
#1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1842:8)
#2      new Flex (package:flutter/src/widgets/basic.dart:3913:8)
#3      new Row (package:flutter/src/widgets/basic.dart:4255:8)
#4      _AppBarState.build (package:flutter/src/material/app_bar.dart:607:17)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4674:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4557:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4730:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4536:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4721:11)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4531:5)
...     Normal element mounting (22 frames)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3501:14)
#34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6002:32)
...     Normal element mounting (202 frames)
#236    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3501:14)
#237    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6002:32)
...     Normal element mounting (273 frames)
#510    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3501:14)
#511    Element.updateChild (package:flutter/src/widgets/framework.dart:3260:18)
#512    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1217:16)
#513    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1188:5)
#514    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1130:17)
#515    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
#516    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1129:13)
#517    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
#518    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```
</details>

**Comment by exaby73** [comment]
With the introduction of null safety, this issue is fixed/no long relevant. Closing as fixed for the same reason.
