### ISSUE TITLE
[camera] after calling controller.takepicture() function screen get stuck and never return XFile

### ISSUE THREAD

**Issue by shivamCDP** [flutter/flutter#109758]
in some of the devices like Samsung M40 , Samsung M31 , Redmi note 8 pro , one plus 6 etc . when user tries to click picture then controller.takepicture() function calls some time its works but most of the time its doesn't return anything and keep waits for File

when I tries to debug the plugin using try catch block then its showing following issue 

```
IPlatformException(error, Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
I/flutter (16612):      at io.flutter.plugins.camera.Camera.runPrecaptureSequence(Camera.java:569)
I/flutter (16612):      at io.flutter.plugins.camera.Camera.takePicture(Camera.java:554)
I/flutter (16612):      at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:110)
I/flutter (16612):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/flutter (16612):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (16612):      at io.flutter.embedding.en
```

**Comment by danagbemava-nc** [comment]
Hi @shivamCDP, 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs that captures the exception, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide the version of camera you're using. 

Thank you
