### ISSUE TITLE
EXCEPTION CAUGHT BY SERVICES LIBRARY: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs

### ISSUE THREAD

**Issue by ljfreelancer88** [flutter/flutter#109902]
I'm using Ubuntu 20. Just upgrade with the later version of Flutter. Created a new project and run `flutter run -d linux`.
Then I got the exception message below. This might help on the improvement on the next release.

```bash
EXCEPTION CAUGHT BY SERVICES LIBRARY
╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not
pressed. If this occurs
in real application, please report this bug to Flutter. If this occurs in unit
tests, please ensure
that simulated events follow Flutter's event model as documented in
`HardwareKeyboard`. This was the
event: KeyUpEvent#aae2b(physicalKey: PhysicalKeyboardKey#7001b(usbHidUsage:
"0x0007001b", debugName:
"Key X"), logicalKey: LogicalKeyboardKey#00078(keyId: "0x00000078", keyLabel:
"X", debugName: "Key
X"), character: null, timeStamp: 6:00:01.183000)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
(package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular
(package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent
(package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage
(package:flutter/src/services/hardware_keyboard.dart:881:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:197:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:387:35)
#8      _invoke2 (dart:ui/hooks.dart:186:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:224:31)
(elided 4 frames from class _AssertionError and dart:async)

```

**Comment by maheshmnj** [comment]
Hi @ljfreelancer88, Thanks for filing the issue. There have been several reports of this issue in the past and most of which have been fixed in the latest release of flutter. Could you please share the output of `flutter doctor -v`  and the steps to reproduce the issue? Also, ensure that you are on the latest stable release of `flutter 3.0.5`.
