### ISSUE TITLE
[camera] startImageStream throws MissingPluginException and callback is not called

### ISSUE THREAD

**Issue by JonasJW** [flutter/flutter#109910]
## Steps to Reproduce

1. Create a new Flutter App
2. Install camera package `camera: 0.10.0+1`
3. Add the following in your Info.plist
```
	<key>NSCameraUsageDescription</key>
	<string>your usage description here</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>your usage description here</string>
```
5. Use the code below as your `main.dart`
6. Run on an iOS device

**Expected results:** 

The code renders a `CameraPreview`. It should call the callback of the `startImageStream` function and thus print "STREAM" in the console on every frame.

I have tested this on an iOS device (not simulator)

**Actual results:** 

I receive a MissingPluginException, the callback of the `startImageStream` is not called and nothing is printed to the console.

What is particularly odd is, sometimes (not always!) after I run `flutter clean` it resolves the issue on the first run however when refreshing the app, this issue occurs again.

> ════════ Exception caught by services library ══════════════════════════════════
> The following MissingPluginException was thrown while activating platform stream on channel plugins.flutter.io/camera_avfoundation/imageStream:
> MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/camera_avfoundation/imageStream)
> 
> When the exception was thrown, this was the stack
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
> <asynchronous suspension>
> #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:506:9)
> <asynchronous suspension>
> ════════════════════════════════════════════════════════════════════════════════

<details>
<summary>Code sample</summary>

```
import 'package:camera/camera.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Digital Coach',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  late CameraController controller;
  List<CameraDescription>? cameras;

  @override
  void initState() {
    loadCameras();
    super.initState();
  }

  loadCameras() async {
    try {
      cameras = await availableCameras();
      setState(() {});
    } on CameraException catch (e) {
      print('Error: ${e.code}\nError Message: ${e.description}');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Digital Coach"),
      ),
      body: body(),
    );
  }

  body() {
    if (cameras?.isNotEmpty ?? false) {
      return Center(
        child: MyCameraPreview(cameras: cameras!),
      );
    }
    return const Center(
      child: Text("Loading Model"),
    );
  }
}

class MyCameraPreview extends StatefulWidget {
  final List<CameraDescription> cameras;

  const MyCameraPreview({
    Key? key,
    required this.cameras,
  }) : super(key: key);

  @override
  State<MyCameraPreview> createState() => _MyCameraPreviewState();
}

class _MyCameraPreviewState extends State<MyCameraPreview> {
  late CameraController controller;
  bool isDetecting = false;

  @override
  void initState() {
    initController();
    super.initState();
  }

  initController() async {
    controller = CameraController(
      widget.cameras[1],
      ResolutionPreset.low,
      enableAudio: false,
      imageFormatGroup: ImageFormatGroup.bgra8888,
    );
    await controller.initialize();
    if (!mounted) {
      return;
    }

    controller.startImageStream((CameraImage img) async {
      print("STREAM");
    });

    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return CameraPreview(controller);
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing digital_coach...                                              

   info • Avoid `print` calls in production code • lib/main.dart:50:7 • avoid_print
   info • Avoid `print` calls in production code • lib/main.dart:111:7 • avoid_print

```

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-arm, locale en-DE)
    • Flutter version 3.0.0 at /Users/jonas/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/jonas/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • B4B1B502-82B3-410C-BF1E-4FFC61A12433 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master` using the code sample provided above.

In my testing, this was only reproducible on iOS, however, it didn't reproduce 100% of the time. I run a series of tests and on my end, there was a coin flip chance of the exception being thrown. 

Labeling for further investigation

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 13 (API 33) (emulator)
    • Nexus (mobile)              • 00008020-001875E83A38002E • ios            • iOS 15.6 19G71
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 104.0.5112.101
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2403, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2403 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a10c921aba (6 hours ago), 2022-08-21 23:44:38 -0400
    • Engine revision d311584c79
    • Dart version 2.19.0 (build 2.19.0-120.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 13 (API 33) (emulator)
    • Nexus (mobile)              • 00008020-001875E83A38002E • ios            • iOS 15.6 19G71
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
<summary>iOS log</summary>

```
Launching lib/main.dart on Nexus in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Xcode build done.                                           16.7s
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Connecting to VM Service at ws://127.0.0.1:63443/Z4BkRXWA0ok=/ws

════════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel plugins.flutter.io/camera_avfoundation/imageStream:
MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/camera_avfoundation/imageStream)

When the exception was thrown, this was the stack
#0      MethodChannel._invokeMethod
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure>
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
Application finished.
Exited

```
</details>

<details>
<summary>android log</summary>

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:63225/zp-k4a--3yA=/ws
I/CameraManagerGlobal( 4519): Connecting to camera service
D/CompatibilityChangeReporter( 4519): Compat change id reported: 206033068; UID 10162; state: DISABLED
E/SurfaceSyncer( 4519): Failed to find sync for id=0
W/Parcel  ( 4519): Expecting binder but got null!
W/Camera  ( 4519): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
I/Camera  ( 4519): startPreview
I/Camera  ( 4519): CameraCaptureSession onConfigured
I/Camera  ( 4519): Updating builder settings
D/Camera  ( 4519): Updating builder with feature: ExposureLockFeature
D/Camera  ( 4519): Updating builder with feature: ExposurePointFeature
D/Camera  ( 4519): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 4519): Updating builder with feature: AutoFocusFeature
D/Camera  ( 4519): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 4519): updateNoiseReduction | currentSetting: fast
D/Camera  ( 4519): Updating builder with feature: FocusPointFeature
D/Camera  ( 4519): Updating builder with feature: ResolutionFeature
D/Camera  ( 4519): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 4519): Updating builder with feature: FlashFeature
D/Camera  ( 4519): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 4519): Updating builder with feature: FpsRangeFeature
I/Camera  ( 4519): refreshPreviewCaptureSession
I/Camera  ( 4519): CameraCaptureSession onConfigured
I/Camera  ( 4519): Updating builder settings
I/Camera  ( 4519): startPreviewWithImageStream
D/Camera  ( 4519): Updating builder with feature: ExposureLockFeature
D/Camera  ( 4519): Updating builder with feature: ExposurePointFeature
D/Camera  ( 4519): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 4519): Updating builder with feature: AutoFocusFeature
D/Camera  ( 4519): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 4519): updateNoiseReduction | currentSetting: fast
D/Camera  ( 4519): Updating builder with feature: FocusPointFeature
D/Camera  ( 4519): Updating builder with feature: ResolutionFeature
D/Camera  ( 4519): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 4519): Updating builder with feature: FlashFeature
D/Camera  ( 4519): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 4519): Updating builder with feature: FpsRangeFeature
I/Camera  ( 4519): refreshPreviewCaptureSession
I/Camera  ( 4519): CameraCaptureSession onClosed
I/flutter ( 4519): STREAM
D/EGL_emulation( 4519): app_time_stats: avg=267.75ms min=9.90ms max=797.56ms count=4
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
D/EGL_emulation( 4519): app_time_stats: avg=41.97ms min=5.37ms max=99.69ms count=23
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
D/EGL_emulation( 4519): app_time_stats: avg=69.82ms min=12.59ms max=197.26ms count=14
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
D/EGL_emulation( 4519): app_time_stats: avg=44.50ms min=6.78ms max=110.03ms count=24
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
I/flutter ( 4519): STREAM
Application finished.
Exited
</details>

**Comment by jmagman** [comment]
I wasn't able to see `MissingPluginException` but I did reproduce that the callback wasn't being called.

@hellohuanlin I think this was caused by https://github.com/flutter/plugins/pull/6277.
`threadSafeEventChannel` is released by the end of this block:
https://github.com/flutter/plugins/blob/fbdf7e3e9617748166ede491d96ab41322cd8e6d/packages/camera/camera_avfoundation/ios/Classes/FLTCam.m#L922-L940

which means by the time the completion block runs on the main queue, `weakSelf` is `nil` and the block doesn't run.
https://github.com/flutter/plugins/blob/fbdf7e3e9617748166ede491d96ab41322cd8e6d/packages/camera/camera_avfoundation/ios/Classes/FLTThreadSafeEventChannel.m#L26-L28

**Comment by hellohuanlin** [comment]
@jmagman thanks for the investigation. you are absolutely right.

**Comment by MohanQ** [comment]
When are you planning to release a new version of camera package that contains this fix? 
Thank you!

**Comment by hellohuanlin** [comment]
@MohanQ 0.9.8+5 is the version

**Comment by jmagman** [comment]
That's `camera_avfoundation` version 0.9.8+5, not `camera`: https://pub.dev/packages/camera_avfoundation/changelog
