### ISSUE TITLE
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key.

### ISSUE THREAD

**Issue by sanekyy** [flutter/flutter#109952]
```
D/21-08-2022–19:54:48:5448 error_handler: onError. error = Assertion failed: file:///Users/sanekyy/Programs/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart:444:16
_pressedKeys[event.physicalKey] == event.logicalKey
"A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, **please report this bug to Flutter**. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#645fa(physicalKey: PhysicalKeyboardKey#70004(usbHidUsage: \"0x00070004\", debugName: \"Key A\"), logicalKey: LogicalKeyboardKey#00444(keyId: \"0x00000444\", keyLabel: \"Ф\", debugName: \"Key Ф\"), character: null, timeStamp: 0:00:31.914599, synthesized) and the recorded logical key LogicalKeyboardKey#00061(keyId: \"0x00000061\", keyLabel: \"A\", debugName: \"Key A\")", stack = dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/flutter/src/services/hardware_keyboard.dart 444:56                   <fn>
packages/flutter/src/services/hardware_keyboard.dart 451:14                   [_assertEventIsRegular]
packages/flutter/src/services/hardware_keyboard.dart 544:5                    handleKeyEvent
packages/flutter/src/services/hardware_keyboard.dart 812:29                   handleKeyData
lib/_engine/engine/platform_dispatcher.dart 214:33                            <fn>
dart-sdk/lib/async/zone.dart 1426:13                                          _rootRun
dart-sdk/lib/async/zone.dart 1328:19                                          run
dart-sdk/lib/async/zone.dart 1236:7                                           runGuarded
lib/_engine/engine/platform_dispatcher.dart 1092:9                            invoke
lib/_engine/engine/platform_dispatcher.dart 213:7                             invokeOnKeyData
lib/_engine/engine/keyboard_binding.dart 134:39                               [_onKeyData]
lib/_engine/engine/keyboard_binding.dart 539:36                               <fn>
lib/_engine/engine/keyboard_binding.dart 416:11                               [_handleEvent]
lib/_engine/engine/keyboard_binding.dart 542:7                                handleEvent
lib/_engine/engine/keyboard_binding.dart 141:25                               <fn>
lib/_engine/engine/keyboard_binding.dart 113:23                               loggedHandler

D/21-08-2022–19:54:48:5448 route_observer_service: Push from /words to null
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:57292/dart_sdk.js:5080:11)
    at Object.nullCheck (http://localhost:57292/dart_sdk.js:5399:30)
    at [_onKeyData] (http://localhost:57292/dart_sdk.js:170645:19)
    at http://localhost:57292/dart_sdk.js:171008:21
    at [_handleEvent] (http://localhost:57292/dart_sdk.js:170935:51)
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:57292/dart_sdk.js:171011:27)
    at http://localhost:57292/dart_sdk.js:170648:76
    at loggedHandler (http://localhost:57292/dart_sdk.js:170625:18)
```

**Comment by danagbemava-nc** [comment]
Hi @sanekyy,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by mkhamat** [comment]
same issue. It stays very long time from version to version. It's very annoying. Sometimes it works fine, sometimes it just does nothing and in other cases it's just throws these keyup logs.

And i noticed that numeric inputs works fine. Only letters have this problem. Maybe this is somehow connected to multiple input languages. I have two input layouts - en and ru. Even if I have EN layout enabled typing results to cyrillic characters in text fields.

**Comment by danagbemava-nc** [comment]
Hi @mkhamat,

Can you please provide your flutter doctor -v and flutter run --verbose logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by mkhamat** [comment]
@danagbemava-nc 

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-x64, locale en-RU)
    • Flutter version 3.0.5 at /Users/mkhamat/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/mkhamat/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (1 available)
    • iPhone 13 Pro (mobile) • 9DE5186B-571A-406C-AB83-8CBDAD66DB20 • ios • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
Simple login page:
```
class LoginPage extends StatelessWidget {
  const LoginPage({Key? key}) : super(key: key);

  static const String routeName = 'loginPage';

  LoginState get state => service<LoginState>();
  ApplicationState get appState => service<ApplicationState>();

  @override
  Widget build(BuildContext context) {
    return Observer(
      name: 'login-page',
      builder: (context) {
        return Stack(
          children: [
            Scaffold(
              body: Center(
                child: SingleChildScrollView(
                  padding: const EdgeInsets.all(24),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Padding(
                        padding: const EdgeInsets.only(bottom: 60.0),
                        child: Center(
                          child: Container(
                              width: 200,
                              height: 150,
                              child: Image.asset('asset/logo.png')),
                        ),
                      ),
                      const Center(child: Text('Вход в личный кабинет')),
                      DropdownButtonFormField(
                          value: state.cityId,
                          items: const [
                            DropdownMenuItem(
                                child: Text('Ессентуки'), value: 2),
                            DropdownMenuItem(
                                child: Text('Железноводск'), value: 1),
                            DropdownMenuItem(
                                child: Text('Лермонтов'), value: 3),
                            DropdownMenuItem(
                                child: Text('Минеральные воды'), value: 4),
                            DropdownMenuItem(
                                child: Text('Невынномысск'), value: 5),
                            DropdownMenuItem(
                                child: Text('Пятигорск'), value: 8),
                          ],
                          onChanged: (v) => state.changeCity(v)),
                      const SizedBox(
                        height: 15,
                      ),
                      TextFormField(
                        controller: state.loginController,
                        decoration: const InputDecoration(
                          labelText: '№ счета',
                          border: OutlineInputBorder(),
                        ),
                      ),
                      const SizedBox(
                        height: 15,
                      ),
                      TextFormField(
                        controller: state.passwordController,
                        obscureText: true,
                        decoration: const InputDecoration(
                          labelText: 'Пароль',
                          border: OutlineInputBorder(),
                        ),
                      ),
                      const SizedBox(
                        height: 15,
                      ),
                      ElevatedButton(
                        onPressed: () => state.authorize(context),
                        child: const Text('Войти'),
                      ),
                      SizedBox(
                        height: 15,
                      ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          TextButton(
                              onPressed: () {
                                Navigator.of(context).push(MaterialPageRoute(
                                    builder: (context) => SignUpPage()));
                              },
                              child: Text('Регистрация')),
                          TextButton(
                              onPressed: () {
                                Navigator.push(
                                    context,
                                    MaterialPageRoute(
                                        builder: (ctx) => RecoveryPage()));
                              },
                              child: Text('Забыли пароль?')),
                        ],
                      )
                    ],
                  ),
                ),
              ),
            ),
            if (state.isSigning) const LoadingNode(),
          ],
        );
      },
    );
  }
}
```

**Comment by mkhamat** [comment]
@danagbemava-nc no logs except mobx spy. Happens after hot restart and once i change layout to ru I can't bring en layout back. In first field it types only in cyrillic, in second field nothing happens at all.

**Comment by danagbemava-nc** [comment]
Hi @mkhamat, can you provide a minimal sample without any third-party packages? 

Also, if possible, kindly provide a screen recording that captures the steps to reproduce clearly. 

Thank you
