### ISSUE TITLE
[Camera] [Android] Exception with android.os.ServiceSpecificException: cancelRequest:522: Camera 0: Error clearing streaming request: Function not implemented (-38) (code 10)

### ISSUE THREAD

**Issue by MeowTechOpenSource** [flutter/flutter#109945]
## Steps to Reproduce

1. Use the camera plugin to take a picture.
```

_controller = CameraController(
        widget.camera[0],
        ResolutionPreset.medium,
);


final image = await _controller.takePicture();

```
(This only happens in some devices that I have, not all) 
(specifically Mi Pad 4 Plus, which supports Camera2)

**Expected results:** 
The camera works and take a photo.
**Actual results:** 
The camera preview stuck for a while loading and then throws a error.

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```

I/Camera  (32723): runPictureAutoFocus
I/Camera  (32723): lockAutoFocus
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
V/MediaPlayer(32723): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(32723): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(32723): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(32723): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 4 | aeState: 2
I/Camera  (32723): captureStillPicture
D/Camera  (32723): Updating builder with feature: ExposureLockFeature
D/Camera  (32723): Updating builder with feature: ExposurePointFeature
D/Camera  (32723): Updating builder with feature: ZoomLevelFeature
D/Camera  (32723): Updating builder with feature: AutoFocusFeature
D/Camera  (32723): Updating builder with feature: NoiseReductionFeature
I/Camera  (32723): updateNoiseReduction | currentSetting: fast
D/Camera  (32723): Updating builder with feature: FocusPointFeature
D/Camera  (32723): Updating builder with feature: ResolutionFeature
D/Camera  (32723): Updating builder with feature: SensorOrientationFeature
D/Camera  (32723): Updating builder with feature: FlashFeature
D/Camera  (32723): Updating builder with feature: ExposureOffsetFeature
D/Camera  (32723): Updating builder with feature: FpsRangeFeature
I/Camera  (32723): sending capture request
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 1 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
I/Camera  (32723): unlockAutoFocus
I/Camera  (32723): refreshPreviewCaptureSession
D/CameraCaptureCallback(32723): CameraCaptureCallback | state: STATE_CAPTURING | afState: 2 | aeState: 2
E/CameraCaptureSession(32723): Session 0: Exception while stopping repeating:
E/CameraCaptureSession(32723): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:522: Camera 0: Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession(32723): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1272)
E/CameraCaptureSession(32723): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
E/CameraCaptureSession(32723): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1348)
E/CameraCaptureSession(32723): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:594)
E/CameraCaptureSession(32723): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:805)
E/CameraCaptureSession(32723): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:273)
E/CameraCaptureSession(32723): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(32723): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(32723): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CameraCaptureSession(32723): 	at android.os.Looper.loop(Looper.java:288)
E/CameraCaptureSession(32723): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/CameraCaptureSession(32723): Caused by: android.os.ServiceSpecificException: cancelRequest:522: Camera 0: Error clearing streaming request: Function not implemented (-38) (code 10)
E/CameraCaptureSession(32723): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2440)
E/CameraCaptureSession(32723): 	at android.os.Parcel.createException(Parcel.java:2410)
E/CameraCaptureSession(32723): 	at android.os.Parcel.readException(Parcel.java:2393)
E/CameraCaptureSession(32723): 	at android.os.Parcel.readException(Parcel.java:2335)
E/CameraCaptureSession(32723): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:749)
E/CameraCaptureSession(32723): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession(32723): 	... 9 more
I/Camera  (32723): open | onDisconnected
I/Camera  (32723): close
W/s.random.picke(32723): Long monitor contention with owner CameraBackground (13377) at void android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating()(CameraDeviceImpl.java:1366) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl.onDeviceError(int, android.hardware.camera2.impl.CaptureResultExtras) for 142ms
I/Camera  (32723): dispose
I/Camera  (32723): close

```

</details>

**Comment by maheshmnj** [comment]
Hi @MeowTechOpenSource, Thanks for filing the issue. Please share a minimal and complete code sample along with the output of `flutter doctor -v`. The device OS version and the complete logs of `flutter run -v` in a text file (as the output will be long).

Looks related to https://github.com/flutter/flutter/issues/92762

**Comment by MeowTechOpenSource** [comment]
Device :XIAOMI MI PAD 4 PLUS (ANDROID 12L)

**Comment by huycozy** [comment]
Hi @MeowTechOpenSource
I see there's an open issue addressing the case you described #102644 that has similar logs as yours. 
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
