### ISSUE TITLE
[Android] [Add-to-app] destroyEngineWithFragment destroys engine in onDetach instead of onDestroy

### ISSUE THREAD

**Issue by Smoofie** [flutter/flutter#110074]
### How to reproduce

1. Create FlutterFragment with a cached FlutterEngine
`FlutterFragment.withCachedEngine(engineId)
            .destroyEngineWithFragment(true)
            .build<FlutterFragment>()`
2. Attach created FlutterFragment
3. Launch app and navigate to created FlutterFragment
4. Go to system settings and change system language
5. Return to application (it will trigger activity relaunch after language changed)
6. Application crashes

Stacktrace:
` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test/com.example.activity.MainActivity}: java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: '1'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3616)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5693)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5592)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8068)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: '1'
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:240)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:175)
        at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:777)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
        at com.example.activity.MainActivity.onCreate(MainActivity.kt:76)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5693) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5592) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:8068) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) `

The crash is caused by FlutterEngine.destroy() called during FlutterFragment.onDetach lifecycle method.

Javadoc of [FlutterFragment.CachedEngineFragmentBuilder#destroyEngineWithFragment](https://github.com/flutter/engine/blob/flutter-3.4-candidate.15/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java#L560) says the following:

> Pass {@code true} to destroy the cached {@link io.flutter.embedding.engine.FlutterEngine} when this {@code FlutterFragment} is destroyed

With destroyEngineWithFragment set to true, FlutterEngine.destroy is called in [FlutterActivityAndFragmentDelegate#onDetach](https://github.com/flutter/engine/blob/flutter-3.4-candidate.15//shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L708)
which is called in [FlutterFragment#onDetach](https://github.com/flutter/engine/blob/flutter-3.4-candidate.15//shell/platform/android/io/flutter/embedding/android/FlutterFragment.java#L892)
which is in contrary to the documentation of destroyEngineWithFragment flag, because onDetach does not imply a Fragment being destroyed. It can be reattached later.

According to the documentation of destroyEngineWithFragment, FlutterEngine.destroy should be called in FlutterFragment.onDestroy.

**Comment by exaby73** [comment]
Hi @Smoofie, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
