### ISSUE TITLE
line 186 pos 16: 'earliestUsefulChild != null': is not true.

### ISSUE THREAD

**Issue by imagfd** [flutter/flutter#110094]
I have a list view with scroll infinite. The scroll infinite works perfectly even I reach the last item of the list, but when I scrolled down at the **end** of the list again or many times , the mobile application crashed and I got an error said :

```
Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale
    fr-FR)
    • Flutter version 3.0.5 at /____/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
```

```
List<Widget> _children =List<Widget>.of([],growable: true) ;
ListView(
               physics:  BouncingScrollPhysics(),
                controller: _scrollController,
               shrinkWrap: true,
               addRepaintBoundaries :true,
                addAutomaticKeepAlives: true,
                addSemanticIndexes: true,

                padding: FxSpacing.all(24),
                children: _children..addAll(
                    List.generate(value.addedItems!.length, (index) => _getTicket(value.addedItems![index]))
                )
            )
```

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_list.dart': Failed assertion: line 186 pos 16: 'earliestUsefulChild != null': is not true.


The relevant error-causing widget was: 
  ListView ListView:file:///____/lib/screens/ticket_list.dart:196:12
When the exception was thrown, this was the stack: 
#2      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:186:16)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#5      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#8      RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1938:12)
#9      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1884:20)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#26     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#30     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#31     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:552:43)
#32     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:579:12)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#34     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#35     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896:45)
#36     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#38     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#39     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003:7)
#40     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#41     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#48     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#50     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#51     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003:7)
#52     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#53     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#54     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#55     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#56     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#57     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#58     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#59     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#60     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#61     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#65     _invoke (dart:ui/hooks.dart:151:10)
#66     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#67     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderSliverList#41716 relayoutBoundary=up18 NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(24.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse, scrollOffset: 0.0, remainingPaintExtent: 0.0, overlap: -49139.7, crossAxisExtent: 363.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 720.8, remainingCacheExtent: 946.8, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0, scrollOffsetCorrection: -422.1)
...    scrollExtent: 0.0
...    hidden
...    maxPaintExtent: 0.0
...    scrollOffsetCorrection: -422.1
...  currently live children: 5 to 14
RenderObject: RenderSliverList#41716 relayoutBoundary=up18 NEEDS-PAINT
  needs compositing
  parentData: paintOffset=Offset(24.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse, scrollOffset: 0.0, remainingPaintExtent: 0.0, overlap: -49139.7, crossAxisExtent: 363.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 720.8, remainingCacheExtent: 946.8, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0, scrollOffsetCorrection: -422.1)
    scrollExtent: 0.0
    hidden
    maxPaintExtent: 0.0
    scrollOffsetCorrection: -422.1
  currently live children: 5 to 14
...  child with index 5: RenderIndexedSemantics#c9297 relayoutBoundary=up19
...    needs compositing
...    parentData: index=5; layoutOffset=0.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 5
...    child: RenderRepaintBoundary#80441 relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#98482 DETACHED
...        engine layer: OffsetEngineLayer#9fe37
...        handles: 1
...        offset: Offset(24.0, -71.3)
...      size: Size(363.4, 85.0)
...      metrics: 92.3% useful (1 bad vs 12 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#e9aa6 relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#0d640 relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
...  child with index 6: RenderIndexedSemantics#d8a1b relayoutBoundary=up19
...    needs compositing
...    parentData: index=6; layoutOffset=510.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 6
...    child: RenderRepaintBoundary#1565d relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#e8fa3 DETACHED
...        engine layer: OffsetEngineLayer#7af61
...        handles: 1
...        offset: Offset(24.0, -79.2)
...      size: Size(363.4, 85.0)
...      metrics: 97.5% useful (1 bad vs 39 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#d0e91 relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#dc0b4 relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
...  child with index 7: RenderIndexedSemantics#05db7 relayoutBoundary=up19
...    needs compositing
...    parentData: index=7; layoutOffset=595.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 7
...    child: RenderRepaintBoundary#eea43 relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#bc1b6
...        engine layer: OffsetEngineLayer#89df0
...        handles: 2
...        offset: Offset(24.0, -57.5)
...      size: Size(363.4, 85.0)
...      metrics: 98.4% useful (1 bad vs 61 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#3ab92 relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#c578f relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
...  child with index 8: RenderIndexedSemantics#8fa93 relayoutBoundary=up19
...    needs compositing
...    parentData: index=8; layoutOffset=680.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 8
...    child: RenderRepaintBoundary#5ddd3 relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#ccbab
...        engine layer: OffsetEngineLayer#e3540
...        handles: 2
...        offset: Offset(24.0, 27.5)
...      size: Size(363.4, 85.0)
...      metrics: 98.4% useful (1 bad vs 61 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#10aa7 relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#e40d7 relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
...  child with index 9: RenderIndexedSemantics#7bb8a relayoutBoundary=up19
...    needs compositing
...    parentData: index=9; layoutOffset=765.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 9
...    child: RenderRepaintBoundary#8c4c0 relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#f5902
...        engine layer: OffsetEngineLayer#084d1
...        handles: 2
...        offset: Offset(24.0, 112.5)
...      size: Size(363.4, 85.0)
...      metrics: 98.3% useful (1 bad vs 58 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#e7e4f relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#36dea relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
...  child with index 10: RenderIndexedSemantics#59fab relayoutBoundary=up19
...    needs compositing
...    parentData: index=10; layoutOffset=850.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 10
...    child: RenderRepaintBoundary#e6ba8 relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#a5db8
...        engine layer: OffsetEngineLayer#18674
...        handles: 2
...        offset: Offset(24.0, 197.5)
...      size: Size(363.4, 85.0)
...      metrics: 98.3% useful (1 bad vs 57 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#812a3 relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#e7d69 relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
...  child with index 11: RenderIndexedSemantics#8a261 relayoutBoundary=up19
...    needs compositing
...    parentData: index=11; layoutOffset=935.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 11
...    child: RenderRepaintBoundary#4dd5e relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#0ea2d
...        engine layer: OffsetEngineLayer#455dd
...        handles: 2
...        offset: Offset(24.0, 282.5)
...      size: Size(363.4, 85.0)
...      metrics: 98.2% useful (1 bad vs 56 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#1109f relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#300ba relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
...  child with index 12: RenderIndexedSemantics#a73d6 relayoutBoundary=up19
...    needs compositing
...    parentData: index=12; layoutOffset=1020.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 12
...    child: RenderRepaintBoundary#96111 relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#43c7f
...        engine layer: OffsetEngineLayer#aacf8
...        handles: 2
...        offset: Offset(24.0, 367.5)
...      size: Size(363.4, 85.0)
...      metrics: 98.2% useful (1 bad vs 54 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#b94d1 relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#7ee7d relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
...  child with index 13: RenderIndexedSemantics#8cf82 relayoutBoundary=up19
...    needs compositing
...    parentData: index=13; layoutOffset=1105.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 13
...    child: RenderRepaintBoundary#fd500 relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#ab7b3
...        engine layer: OffsetEngineLayer#4bd5d
...        handles: 2
...        offset: Offset(24.0, 452.5)
...      size: Size(363.4, 85.0)
...      metrics: 98.1% useful (1 bad vs 52 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#b5ced relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#b9a88 relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
...  child with index 14: RenderIndexedSemantics#39b4d relayoutBoundary=up19
...    needs compositing
...    parentData: index=14; layoutOffset=1190.0 (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 85.0)
...    index: 14
...    child: RenderRepaintBoundary#df791 relayoutBoundary=up20
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#869e0
...        engine layer: OffsetEngineLayer#6ad7b
...        handles: 2
...        offset: Offset(24.0, 537.5)
...      size: Size(363.4, 85.0)
...      metrics: 98.0% useful (1 bad vs 49 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#52afa relayoutBoundary=up21
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...        size: Size(363.4, 85.0)
...        child: RenderMouseRegion#cec11 relayoutBoundary=up22
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...          size: Size(363.4, 85.0)
...          behavior: opaque
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
====================================================================================================

```

**Comment by UsamaKarim** [comment]
https://github.com/flutter/flutter/issues/73600#issuecomment-757920137

**Comment by huycozy** [comment]
Hi @imagfd, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
Also, there was a hint [here](https://github.com/flutter/flutter/issues/73097#issuecomment-753276111) that you can try to solve this issue.
Thank you!

**Comment by imagfd** [comment]
Hi @huycozy , thank for your reply. I apologize if I misexplained the issue. 
I tried and I'm glad that finally I fixed it :)  

The error occured at this line
        _children.clear(); 
which is used to refresh the list (pull to refresh) . After removing this line, the error went away. Thanks  ! 

```
List<Widget> _children =List<Widget>.of([],growable: true) ;

get _ticketsListWidget{
    Widget resultWidget =_loadWidget;
    return   Consumer<Tickets>(
      builder: (_, value, __) {
        //if(value.infiniteScroll.page==0) _children.clear();   <=====remove this line 

        if(value.items != null){
          if(value.addedItems!=null){
            if(value.items!.length==0)
              resultWidget = _noTicketsWidget;
            else
              resultWidget = _getListWidget(value);
          }
        }
        return resultWidget;
      }
    );
  }

_getListWidget(dynamic value){
    return RefreshIndicator(
        onRefresh: _refresh,
        child: ListView(
                physics:  const BouncingScrollPhysics(),
                controller: _scrollController,
                shrinkWrap: true,
                children: _children..addAll(
                    List.generate(value.addedItems!.length, (index) => _getTicketWidget(value.addedItems![index]))
                )
        )
    );
  }

```

**Comment by huycozy** [comment]
@imagfd Glad to see you solved it. Close the issue as solved. Thank you!
