### ISSUE TITLE
[quick_actions] Flaky failure in `appShortcutLaunchActivityAfterStarting`

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#110022]
Android failed `appShortcutLaunchActivityAfterStarting`, but passed on a re-run.

```
java.lang.AssertionError: AppShortcut:action_one does not launch the correct activity
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at io.flutter.plugins.quickactionsexample.QuickActionsTest.appShortcutLaunchActivityAfterStarting(QuickActionsTest.java:114)
at java.lang.reflect.Method.invoke(Native Method)
```

The video does show that the title has updated to "action_one has launched", so it's not clear why the assertion failed; it suggests that there's a problem in the test assertions rather than the plugin functionality. This test is only about a month old, which also points to a test issue rather than a regression.

This failed both devices on the first run, only one device on the auto-rerun, and then passed when the task was manually re-run. So it's potentially quite flaky.

**Comment by stuartmorgan** [comment]
https://cirrus-ci.com/task/5617863904985088 is the failing run.

**Comment by stuartmorgan** [comment]
This is continuing to be flaky; we should disable it for now if we can't resolve it soon.
