### ISSUE TITLE
Dashboard builds are queued up without being back scheduled

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#110059]
Tasks are not being scheduled:
<img width="1192" alt="Screen Shot 2022-08-22 at 9 31 15 PM" src="https://user-images.githubusercontent.com/54558023/186071264-82ddf640-b8dd-448a-b82a-3cbe32f3d571.png">

API `/api/scheduler/batch-backfiller` is failing:
```
RangeError (index): Invalid value: Not in inclusive range 0..3: 4
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      shouldRerunPriority (package:cocoon_service/src/service/scheduler/policy.dart:94:24)
#2      BatchBackfiller.backfillPriority (package:cocoon_service/src/request_handlers/scheduler/batch_backfiller.dart:121:9)
#3      BatchBackfiller.backfillRepository (package:cocoon_service/src/request_handlers/scheduler/batch_backfiller.dart:76:28)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      BatchBackfiller.get (package:cocoon_service/src/request_handlers/scheduler/batch_backfiller.dart:46:5)
<asynchronous suspension>
#6      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#7      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:250:9)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
This happens when available task list length is smaller than batch size (happens only on newly enabled target).

**Comment by keyonghan** [comment]
A test version is pushed to unblock. https://github.com/flutter/cocoon/pull/2070 to fix.

**Comment by keyonghan** [comment]
Resolved.
