### ISSUE TITLE
[Add2App][Android][Crash] FlutterFragment crash by activity / fragment recycled

### ISSUE THREAD

**Issue by bradchien** [flutter/flutter#110138]
Our App got a lot of crashes while doing flutter migration. The stack trace as below
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void io.flutter.embedding.android.m.e()' on a null object reference

===========================================
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDestroyView (FlutterActivityAndFragmentDelegate.java:613)
io.flutter.embedding.android.FlutterFragment.detachFromFlutterEngine (FlutterFragment.java:869)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.detachFromFlutterEngine (FlutterActivityAndFragmentDelegate.java:649)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity (FlutterEngineConnectionRegistry.java:319)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:189)
```

## Steps to Reproduce

1. clone code sample from [crash_demo](git@github.com:bradchien/crash_demo.git) 
2. before run demo, turn on `Don't keep activities` in android settings > system > developer options > apps 
3. run app, fast switch apps by swiping system navigation bar 
(you could follow the steps as [demo video](https://drive.google.com/file/d/1lGIuHS5aHCX3VQoQSf7wsPYisOy5RgE6/view?usp=sharing) shown)

**Expected results:** 
App could restore without any error.

**Actual results:** 
App crash randomly while restoring activity with flutter fragment.

<details>
<summary>Code sample</summary>

```kotlin
	override fun onCreate(savedInstanceState: Bundle?) {
		engineBindings.attach()

		super.onCreate(savedInstanceState)
		setContentView(R.layout.activity_main)

		flutterFragment =
			FlutterFragment.withCachedEngine("shared_engine").renderMode(RenderMode.texture).build()
		val transaction = supportFragmentManager.beginTransaction()
		transaction.add(R.id.container, flutterFragment!!, "Flutter_Page")
		transaction.commit()
	}

	override fun onDestroy() {
		super.onDestroy()
		engineBindings.detach()
	}
```
and implement event handler from the tutorial [Adding a Flutter Fragment to an Android app](https://docs.flutter.dev/development/add-to-app/android/add-flutter-fragment?tab=forward-activity-calls-kotlin-tab)

</details>

<details>
  <summary>Logs</summary>

```
FATAL EXCEPTION: main
Process: dev.flutter.multipleflutters, PID: 24902
java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.flutter.multipleflutters/dev.flutter.multipleflutters.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.detachFromFlutterEngine()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.detachFromFlutterEngine()' on a null object reference
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDestroyView(FlutterActivityAndFragmentDelegate.java:613)
	at io.flutter.embedding.android.FlutterFragment.detachFromFlutterEngine(FlutterFragment.java:869)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.detachFromFlutterEngine(FlutterActivityAndFragmentDelegate.java:649)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:319)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:189)
	at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:777)
	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2574)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:828)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
	at dev.flutter.multipleflutters.MainActivity.onCreate(MainActivity.kt:24)
	at android.app.Activity.performCreate(Activity.java:8050)
	at android.app.Activity.performCreate(Activity.java:8030)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7839) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

```
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-arm, locale zh-Hant-TW)
    • Flutter version 3.0.5 at /Users/bradchien/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/bradchien/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (4 available)
    • Pixel 6 (mobile)            • 1A021FDF6008KX            • android-arm64  • Android 12 (API 31)
    • KKTV iPhone 11 Pro (mobile) • 00008030-001139100E00802E • ios            • iOS 15.6 19G71
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 104.0.5112.101
    ! Error: 遙遠的TV is not connected. Xcode will continue when 遙遠的TV is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by danagbemava-nc** [comment]
I can reproduce the crash using the code sample and steps provided above.

Labeling for further investigation from the team. 

<details>
<summary>logs</summary>

```
08/24 10:27:39: Launching 'app' on Xiaomi M2007J20CG.
Install successfully finished in 4 s 948 ms.
$ adb shell am start -n "dev.flutter.multipleflutters/dev.flutter.multipleflutters.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 7431 on device 'xiaomi-m2007j20cg-5dd3be00'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/Perf: Connecting to perf service.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/ResourceExtractor: Found extracted resources res_timestamp-1-1661336434953
I/ResourceExtractor: Resource version mismatch res_timestamp-1-1661336865790
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
W/ultipleflutters: type=1400 audit(0.0:817751): avc: denied { read } for name="max_map_count" dev="proc" ino=39479012 scontext=u:r:untrusted_app:s0:c128,c258,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=dev.flutter.multipleflutters
I/AdrenoGLES-0: QUALCOMM build                   : 3142bdd, I7afe4835b7
    Build Date                       : 09/16/20
    OpenGL ES Shader Compiler Version: EV031.32.02.00
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
I/AdrenoGLES-0: Build Config                     : S P 10.0.6 AArch64
I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
D/View: dev.flutter.multipleflutters initForcedUseForceDark: 1
D/DecorView[]: getWindowModeFromSystem  windowmode is 1
D/DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
W/ultipleflutter: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/ultipleflutter: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/flutter: The Dart VM service is listening on http://127.0.0.1:38323/0BwSMOX_bXU=/
W/ultipleflutter: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/ultipleflutter: Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/ultipleflutter: Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/ultipleflutter: Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
D/DecorView[]: getWindowModeFromSystem  windowmode is 1
W/Looper: PerfMonitor looperActivity : package=dev.flutter.multipleflutters/.MainActivity time=335ms latency=572ms running=271ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem } historyMsgCount=3 (msgIndex=3 wall=570ms seq=3 running=192ms runnable=16ms late=4ms h=android.app.ActivityThread$H w=110)
W/Looper: PerfMonitor looperActivity : package=dev.flutter.multipleflutters/.MainActivity time=0ms latency=907ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=4 (msgIndex=3 wall=570ms seq=3 running=192ms runnable=16ms late=4ms h=android.app.ActivityThread$H w=110) (msgIndex=4 wall=335ms seq=4 running=271ms runnable=15ms io=1ms late=572ms h=android.app.ActivityThread$H w=159)
I/ultipleflutter: ProcessProfilingInfo new_methods=2032 is saved saved_to_disk=1 resolve_classes_delay=8000
W/Activity: Slow Operation: Activity dev.flutter.multipleflutters/.MainActivity onDestroy took 321ms
W/Looper: PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=355ms procState=18 historyMsgCount=2 (msgIndex=1 wall=354ms seq=54 running=42ms runnable=84ms late=26ms h=android.app.ActivityThread$H w=159)
W/ultipleflutters: type=1400 audit(0.0:817752): avc: denied { read } for name="max_map_count" dev="proc" ino=39488875 scontext=u:r:untrusted_app:s0:c128,c258,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=dev.flutter.multipleflutters
D/DecorView[]: getWindowModeFromSystem  windowmode is 1
D/DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
W/FlutterFragment: FlutterFragment FlutterFragment{156a8b9 (8698156b-83a6-4454-b2c0-172dd00c03bf) id=0x7f080059 Flutter_Page} connection to the engine io.flutter.embedding.engine.FlutterEngine@e65f114 evicted by another attaching activity
W/FlutterFragment: FlutterFragment 22456505 onStart called after detach.
W/FlutterFragment: FlutterFragment 22456505 onResume called after detach.
D/DecorView[]: getWindowModeFromSystem  windowmode is 1
W/FlutterView: Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
I/flutter: The Dart VM service is listening on http://127.0.0.1:43023/0wuYY3dOEAA=/
W/FlutterView: Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
W/FlutterView: Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
W/FlutterFragment: FlutterFragment 22456505 onPause called after detach.
W/FlutterFragment: FlutterFragment 22456505 onStop called after detach.
W/FlutterFragment: FlutterFragment 22456505 onSaveInstanceState called after detach.
W/FlutterFragment: FlutterFragment 22456505 onTrimMemory called after detach.
W/FlutterFragment: FlutterFragment 22456505 onDestroyView called after detach.
E/FlutterEngineCxnRegstry: Attempted to detach plugins from an Activity when no Activity was attached.
W/Activity: Slow Operation: Activity dev.flutter.multipleflutters/.MainActivity onDestroy took 2506ms
W/Looper: PerfMonitor longMsg : seq=101 plan=10:28:12.612 late=17ms wall=2519ms running=35ms runnable=44ms h=android.app.ActivityThread$H w=159 procState=18
W/ultipleflutters: type=1400 audit(0.0:817754): avc: denied { read } for name="max_map_count" dev="proc" ino=39488875 scontext=u:r:untrusted_app:s0:c128,c258,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=dev.flutter.multipleflutters
W/FlutterFragment: FlutterFragment FlutterFragment{5f6670f (8698156b-83a6-4454-b2c0-172dd00c03bf) id=0x7f080059 Flutter_Page} connection to the engine io.flutter.embedding.engine.FlutterEngine@1eaa39c evicted by another attaching activity
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.flutter.multipleflutters, PID: 7431
    java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.flutter.multipleflutters/dev.flutter.multipleflutters.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.detachFromFlutterEngine()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3494)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3666)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7889)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.detachFromFlutterEngine()' on a null object reference
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDestroyView(FlutterActivityAndFragmentDelegate.java:622)
        at io.flutter.embedding.android.FlutterFragment.detachFromFlutterEngine(FlutterFragment.java:882)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.detachFromFlutterEngine(FlutterActivityAndFragmentDelegate.java:658)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:319)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:195)
        at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:789)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2574)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:828)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at dev.flutter.multipleflutters.MainActivity.onCreate(MainActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:8109)
        at android.app.Activity.performCreate(Activity.java:8083)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3467)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3666) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:7889) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
I/Process: Sending signal. PID: 7431 SIG: 9
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 104.0.5112.101

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by peer

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2443, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2443 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e45031bf2a (5 hours ago), 2022-08-24 01:59:20 -0400
    • Engine revision 55c461f286
    • Dart version 2.19.0 (build 2.19.0-130.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 104.0.5112.101

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by peer

! Doctor found issues in 1 category.
```
</details>

**Comment by hai046** [comment]
I have same problem, i added the fragment according to the docs:  https://docs.flutter.dev/development/add-to-app/android/add-flutter-fragment

**Comment by hai046** [comment]
> I have same problem, i added the fragment according to the docs: https://docs.flutter.dev/development/add-to-app/android/add-flutter-fragment


It is related to memory tension and life cycle

Fix by


```

  @Override
    protected void onCreate(Bundle savedInstanceState) {
        flutterFragment = retrieveExistingFlutterFragmentIfPossible();
        ensureFlutterFragmentCreated();
        if (!flutterFragment.isAdded()) {
            getSupportFragmentManager().beginTransaction().add(R.id.flutter_layout, flutterFragment, TAG_FLUTTER_FRAGMENT).commit();
        }
   }

    FlutterFragment retrieveExistingFlutterFragmentIfPossible() {
        FragmentManager fragmentManager = getSupportFragmentManager();
        return (FlutterFragment) fragmentManager.findFragmentByTag(TAG_FLUTTER_FRAGMENT);
    }

    private void ensureFlutterFragmentCreated() {
        if (flutterFragment == null) {
            // If both activity and fragment have been destroyed, the activity restore may have
            // already recreated a new instance of the fragment again via the FragmentActivity.onCreate
            // and the FragmentManager.
            flutterFragment = retrieveExistingFlutterFragmentIfPossible();
        }
        if (flutterFragment == null) {
            // No FlutterFragment exists yet. This must be the initial Activity creation. We will create
            // and add a new FlutterFragment to this Activity.
            flutterFragment = FlutterFragment.withCachedEngine(MyApp.ENGINE_ID).shouldAttachEngineToActivity(true).destroyEngineWithFragment(false).build();
        }
    }

```

**Comment by patilvishwanath** [comment]
@hai046 @bradchien Does code sample solve your issue, as i am also facing the same issue for prod app.

Logs for FireBase Crashlytics
<details>
<summary>RuntimeException</summary>

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tatadigital.tcp/com.tatadigital.tcp.main.ui.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.detachFromFlutterEngine()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3947)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8280)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
</details>

<details>
<summary>NullPointerException</summary>
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.detachFromFlutterEngine()' on a null object reference
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDestroyView(FlutterActivityAndFragmentDelegate.java:618)
       at io.flutter.embedding.android.FlutterFragment.detachFromFlutterEngine(FlutterFragment.java:882)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.detachFromFlutterEngine(FlutterActivityAndFragmentDelegate.java:654)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:319)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:194)
       at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:789)
       at com.tatadigital.tcp.flutter_embed.OffersFlutterFragment.onAttach(OffersFlutterFragment.kt:20)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:3063)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:121)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2884)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
       at com.tatadigital.tcp.common.view.BaseActivity.onCreate(BaseActivity.kt:60)
       at com.tatadigital.tcp.main.ui.HomeActivity.onCreate(HomeActivity.kt:354)
       at android.app.Activity.performCreate(Activity.java:8163)
       at android.app.Activity.performCreate(Activity.java:8130)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3753)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3947)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8280)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

</details>

<details>
<summary>ScreenShot from FireBase Crashlytics</summary>
<img width="1440" alt="Screenshot 2023-04-04 at 2 25 53 PM" src="https://user-images.githubusercontent.com/23475948/229741353-c0bad56c-fa01-4acf-9981-05edbad15cf9.png">

</details>

**Comment by hai046** [comment]
> ```java
> ensureFlutterFragmentCreated
> ```

use `ensureFlutterFragmentCreated()` or You can study the source code carefully, they all don’t have this problem, I also found it from his android flutter code
