### ISSUE TITLE
flutter doctor crash

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#11014]
## Steps to Reproduce

Just ran `flutter doctor` on Windows.

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\mit\AppData\Local\Android\sdk\platform-tools\adb.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:86)
#2      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:286)
#3      runSync (package:flutter_tools/src/base/process.dart:261)
#4      getAdbDevices (package:flutter_tools/src/android/android_device.dart:549)
#5      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:51)
<asynchronous suspension>
#6      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:138)
<asynchronous suspension>
#7      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:91)
<asynchronous suspension>
#8      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:493)
<asynchronous suspension>
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:105)
<asynchronous suspension>
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:27)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:206)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#19     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     runZoned (dart:async/zone.dart:1467)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#28     main (file:///C:/Users/mit/dev/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for C:\Users\mit\AppData\Local\Android\sdk\platform-tools\adb.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:86)
#2      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:286)
#3      runSync (package:flutter_tools/src/base/process.dart:261)
#4      getAdbDevices (package:flutter_tools/src/android/android_device.dart:549)
#5      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:51)
<asynchronous suspension>
#6      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:138)
<asynchronous suspension>
#7      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:91)
<asynchronous suspension>
#8      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:493)
<asynchronous suspension>
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:105)
<asynchronous suspension>
#10     _doctorText.<anonymous closure> (package:flutter_tools/executable.dart:289)
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     runZoned (dart:async/zone.dart:1467)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     _doctorText (package:flutter_tools/executable.dart:289)
<asynchronous suspension>
#18     _createLocalCrashReport (package:flutter_tools/executable.dart:264)
<asynchronous suspension>
#19     _handleToolError (package:flutter_tools/executable.dart:219)
<asynchronous suspension>
#20     run.<anonymous closure> (package:flutter_tools/executable.dart:146)
<asynchronous suspension>
#21     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#22     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#23     _rootRun (dart:async/zone.dart:1120)
#24     _CustomZone.run (dart:async/zone.dart:1001)
#25     runZoned (dart:async/zone.dart:1467)
#26     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#27     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#28     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#29     main (file:///C:/Users/mit/dev/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## Flutter Doctor Output

```
C:\Users\mit\dev\github>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.10586], locale en-US, channel alpha)
    • Flutter at C:\Users\mit\dev\github\flutter
    • Framework revision d36e2f6191 (7 days ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[-] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\mit\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    X Android SDK file not found: C:\Users\mit\AppData\Local\Android\sdk\platform-tools\adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4694.29


Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: c8de4fca38000000)
```

**Comment by lassemedina** [comment]
Works for me (windows 10). Do you have a adb.exe file in C:\Users\mit\AppData\Local\Android\sdk\platform-tools\ ?

(My flutter doctor...) 
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale sv-SE, channel alpha)
    • Flutter at c:\dev\tools\google\flutter
    • Framework revision d36e2f6191 (7 days ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Lars\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

**Comment by mit-mit** [comment]
Yes, my platform-tools installation was broken; after fixing that it works fine. But flutter doctor should still fail more graciously.
