### ISSUE TITLE
Android plugin crash: `IllegalStateException: Unexpected platform view context`

### ISSUE THREAD

**Issue by linslouis** [flutter/flutter#110146]
## Steps to Reproduce

 
I am trying to implement a video player in may application.
I used "native_video_view: ^1.0.5" plugin for that.It worked as expected on **Flutter 2.10.5**.
But not working properly on the current stable version of flutter( **Flutter 3.0.4** ).
In stable version, the video player widget displaying over all the other views in the device.And also sticks to the top of the display.
Then i tried it with latest flutter from github(**Flutter 3.1.0-0.0.pre.2428**).
In that case it showing a crash.But if I run it with 'flutter run ' command , then it will run, but showing same issue as in the stable version.

Below is my implementation of the native_video_view.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:native_video_view/native_video_view.dart';

void main() => runApp(const MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: _buildVideoPlayerWidget(),
    );
  }

  Widget _buildVideoPlayerWidget() {
    return Container(
      alignment: Alignment.center,
      child: NativeVideoView(
        keepAspectRatio: true,
        showMediaController: true,
        enableVolumeControl: true,
        onCreated: (controller) {
          controller.setVideoSource(
            'assets/example.mp4',
            sourceType: VideoSourceType.asset,
            requestAudioFocus: true,
          );
        },
        onPrepared: (controller, info) {
          debugPrint('NativeVideoView: Video prepared');
          controller.play();
        },
        onError: (controller, what, extra, message) {
          debugPrint(
              'NativeVideoView: Player Error ($what | $extra | $message)');
        },
        onCompletion: (controller) {
          debugPrint('NativeVideoView: Video completed');
        },
      ),
    );
  }
}

```
 </details>

| Expected results | Actual results |
| -- | -- |
| <img alt="Screenshot 2022-08-24 at 10 56 13 AM" src="https://user-images.githubusercontent.com/6736869/186336150-b76770d9-427c-424c-b174-de659992c634.png" /> | <img src="https://user-images.githubusercontent.com/6736869/186335227-2ff73c2f-d8d3-432b-9b81-9a744ea45e27.jpg" /> |

<details>
<summary>Log</summary>

```
Running "flutter pub get" in videoplayernativeplatform...
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:49988/LsQCbapa508=/ws
Syncing files to device sdk gphone64 arm64...
I/PlatformViewsController(10892): Hosting view in a virtual display for platform view: 0
E/flutter (10892): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Unexpected platform view context. When constructing a platform view in the factory, use the context from PlatformViewFactory#create, view id: 0
E/flutter (10892): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:187)
E/flutter (10892): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:432)
E/flutter (10892): 	at android.app.Dialog.show(Dialog.java:321)
E/flutter (10892): 	at android.app.Presentation.show(Presentation.java:279)
E/flutter (10892): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:119)
E/flutter (10892): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:64)
E/flutter (10892): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:267)
E/flutter (10892): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter (10892): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (10892): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:261)
E/flutter (10892): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (10892): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:321)
E/flutter (10892): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (10892): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (10892): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (10892): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (10892): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (10892): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/flutter (10892): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10892): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (10892): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (10892): , null, null)
E/flutter (10892): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (10892): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (10892): <asynchronous suspension>
E/flutter (10892): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146:18)
E/flutter (10892): <asynchronous suspension>
E/flutter (10892): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792:5)
E/flutter (10892): <asynchronous suspension>
E/flutter (10892): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:819:7)
E/flutter (10892): <asynchronous suspension>
E/flutter (10892): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:182:29)
E/flutter (10892): <asynchronous suspension>
E/flutter (10892): 
W/System  (10892): A resource failed to call release. 
D/EGL_emulation(10892): app_time_stats: avg=954.98ms min=3.11ms max=2768.19ms count=3
```
 
</details>

<details>
<summary>Logs</summary>

```
 flutter analyze      
Analyzing videoplayernativeplatform...                                  
No issues found! (ran in 1.7s)
``` 

flutter doctor -v

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.5.1 21G83 darwin-arm, locale en-IN)
    • Flutter version 3.0.4 at /Users/linslouis/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (8 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/linslouis/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/linslouis/Library/Android/sdk
    • Java binary at: /Users/linslouis/Library/Java/JavaVirtualMachines/azul-15.0.8/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu15.42+15-CA (build 15.0.8+4-MTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
``` 

</details>

**Comment by danagbemava-nc** [comment]
This seems like another case of https://github.com/flutter/flutter/issues/103630 that was not fixed by https://github.com/flutter/engine/pull/33599.

On the `beta` and `master` channels, there's a crash and the video_player doesn't render whereas on the `stable` channel, we have the issue in #103630

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:native_video_view/native_video_view.dart';

void main() => runApp(const MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: _buildVideoPlayerWidget(),
    );
  }

  Widget _buildVideoPlayerWidget() {
    return Container(
      alignment: Alignment.center,
      child: NativeVideoView(
        keepAspectRatio: true,
        showMediaController: true,
        enableVolumeControl: true,
        onCreated: (controller) {
          controller.setVideoSource(
            'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
            sourceType: VideoSourceType.network,
            requestAudioFocus: true,
          );
        },
        onPrepared: (controller, info) {
          debugPrint('NativeVideoView: Video prepared');
          controller.play();
        },
        onError: (controller, what, extra, message) {
          debugPrint(
              'NativeVideoView: Player Error ($what | $extra | $message)');
        },
        onCompletion: (controller) {
          debugPrint('NativeVideoView: Video completed');
        },
      ),
    );
  }
}
```
</details>

<details>
<summary>logs</summary>

```
Launching lib/main.dart on M2007J20CG in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:57685/TLW-R2zdmBM=/ws
I/PlatformViewsController( 2710): Hosting view in a virtual display for platform view: 0
E/flutter ( 2710): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Unexpected platform view context. When constructing a platform view in the factory, use the context from PlatformViewFactory#create, view id: 0
E/flutter ( 2710): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:187)
E/flutter ( 2710): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
E/flutter ( 2710): 	at android.app.Dialog.show(Dialog.java:315)
E/flutter ( 2710): 	at android.app.Presentation.show(Presentation.java:257)
E/flutter ( 2710): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:119)
E/flutter ( 2710): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:64)
E/flutter ( 2710): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:267)
E/flutter ( 2710): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter ( 2710): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter ( 2710): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 2710): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 2710): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 2710): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 2710): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 2710): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 2710): 	at android.os.Looper.loop(Looper.java:236)
E/flutter ( 2710): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
E/flutter ( 2710): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 2710): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/flutter ( 2710): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter ( 2710): , null, null)
E/flutter ( 2710): #0      StandardMethodCodec.decodeEnvelope
E/flutter ( 2710): #1      MethodChannel._invokeMethod
E/flutter ( 2710): <asynchronous suspension>
E/flutter ( 2710): #2      TextureAndroidViewController._sendCreateMessage
E/flutter ( 2710): <asynchronous suspension>
E/flutter ( 2710): #3      AndroidViewController.create
E/flutter ( 2710): <asynchronous suspension>
E/flutter ( 2710): #4      AndroidViewController.setSize
E/flutter ( 2710): <asynchronous suspension>
E/flutter ( 2710): #5      RenderAndroidView._sizePlatformView
E/flutter ( 2710): <asynchronous suspension>
E/flutter ( 2710):
I/m.example.vdp_( 2710): ProcessProfilingInfo new_methods=1530 is saved saved_to_disk=1 resolve_classes_delay=8000
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 104.0.5112.101

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by peer

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel beta, 3.3.0-0.5.pre, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0-0.5.pre on channel beta at /Users/nexus/dev/sdks/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 096162697a (2 days ago), 2022-08-22 15:34:14 -0700
    • Engine revision ad3d868e0d
    • Dart version 2.18.0 (build 2.18.0-271.7.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 104.0.5112.101

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by peer

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2443, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2443 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e45031bf2a (7 hours ago), 2022-08-24 01:59:20 -0400
    • Engine revision 55c461f286
    • Dart version 2.19.0 (build 2.19.0-130.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 104.0.5112.101

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by peer

! Doctor found issues in 1 category.
```
</details>

**Comment by stuartmorgan** [comment]
> This seems like another case of #103630 that was not fixed by [flutter/engine#33599](https://github.com/flutter/engine/pull/33599).

The existence of a completely different issue that happens before we ever reach the point of display doesn't mean that the display issue isn't fixed for this plugin. Based on the logging, it is falling back to Virtual Display here, so if it weren't crashing on create it should display correctly.

Retitling for the issue that needs to be tracked.

**Comment by huvi8161** [comment]
Having the same issue in our app!

**Comment by Pisey-Nguon** [comment]
I have the same issue in my app

**Comment by danagbemava-nc** [comment]
To anyone else who may be facing this issue, kindly read this section of our [Issue Hygiene wiki](https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-comments-to-bugs) 

It would be best if you just add a thumbs up to the original post. 

Thank you

**Comment by stuartmorgan** [comment]
It looks like the issue here is that `LayoutInflator` apparently doesn't wire the views it creates to point to the context it is using. The plugin is calling:

```
        this.constraintLayout = LayoutInflater.from(context)
            .inflate(R.layout.video_layout, null) as ConstraintLayout
```

where `context` is the context provided to the view controller factory, but `this.constraintLayout.getContex()` doesn't return that context; instead it returns the main activity.

It seems likely that the behavior prior to the TLHC-with-VD-fallback restructuring was that the workarounds specific to the `ProviderContext` just silently failed to work. In the restructuring, it was made an assert. Given that it seems non-trivial for affected plugins to set up the intended context in at least the `LayoutInflator` case, the best option is probably to change the new assertion to a warning log so that affected plugins will have their pre-3.0 behavior. (Presumably the lack of those workaround wasn't critical to the use case of those plugins in the first place.)

Testing with a local engine with that change, the plugin does appear to work when running its example app.
