### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#110143]
## Command
```
flutter run
```

## Steps to Reproduce

Login to Ubuntu using a Wayland Session​

Run script to setup Flutter Workspace
```
gnome-terminal -- bash -c "mkdir -p $HOME/workspace && cd $HOME/workspace && wget https://raw.githubusercontent.com/meta-flutter/meta-flutter/kirkstone/tools/flutter_workspace_config.json && curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/meta-flutter/meta-flutter/kirkstone/tools/setup_flutter_workspace.py | python3"​
```

Open Terminal Window and type​:
```
source ${FLUTTER_WORKSPACE}/setup_env.sh​
cd ${FLUTTER_WORKSPACE}/app​
flutter create hello_world -t app​
cd hello_world​
flutter run​
```
Select "Toyota flutter-auto (desktop-auto)"​

## Logs
FormatException
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1859:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1434:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
#14     _rootRunUnary (dart:async/zone.dart:1442:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#20     _StreamController._add (dart:async/stream_controller.dart:648:7)
#21     _StreamController.add (dart:async/stream_controller.dart:596:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1839:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel unknown, 3.0.1, on Ubuntu 20.04.4 LTS 5.14.0-1048-oem, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /home/joel.winarske@toyotaconnected.com/workspace/flutter
    • Upstream repository unknown
    • Framework revision fb57da5f94 (3 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 10.0.1-++20211003085942+ef32c611aa21-1~exp1~20211003090334.2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] VS Code (version 1.69.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • Linux (desktop)              • linux        • linux-x64 • Ubuntu 20.04.4 LTS 5.14.0-1048-oem
    • Toyota flutter-auto (mobile) • desktop-auto • linux-x64 • flutter-auto x86_64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: fb57da5f945d02ef4f98dfd9409a72b7cce74268

**Comment by huycozy** [comment]
Hi @jwinarske, thanks for filing the issue. 

I also see there's an open issue that has similar logs to this: #81666, and takes a look at https://github.com/flutter/flutter/issues/81666#issuecomment-890047409 that redirects to a general issue https://github.com/dart-lang/sdk/issues/44994.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. 
Thanks!
