### ISSUE TITLE
flutter create . command shows error

### ISSUE THREAD

**Issue by rapurva2002** [flutter/flutter#110395]
![Screenshot 2022-08-27 092251](https://user-images.githubusercontent.com/82507299/187013374-e73fd9e9-6dae-4c5a-8fcc-e0d70f553759.png)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

![image](https://user-images.githubusercontent.com/82507299/187013457-178c36de-f490-4aa3-ac81-4ede5eea0255.png)

![image](https://user-images.githubusercontent.com/82507299/187013420-262cce76-44f4-40a0-aea6-0ed2bcff232d.png)

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@rapurva2002 
When you open an issue, please try to use new issue template and fill out requested details so that we have enough info to work with. Also, please avoid posting screenshots of errors as we cannot search using it.

Please provide the `flutter_07.log` file generated and also provide `flutter doctor -v` and complete error log in properly formatted text.

**Comment by rapurva2002** [comment]
Thank you, sir for pointing this out. I'll try to add it

**Comment by rapurva2002** [comment]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter create .

## exception

_CastError: Null check operator used on a null value

```
#0      _validateMetadataMap (package:flutter_tools/src/flutter_project_metadata.dart:58:33)
#1      new FlutterProjectMetadata (package:flutter_tools/src/flutter_project_metadata.dart:99:11)
#2      CreateBase.determineTemplateType (package:flutter_tools/src/commands/create_base.dart:221:9)
#3      CreateCommand._getProjectType (package:flutter_tools/src/commands/create.dart:170:29)
#4      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:210:41)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1342:12)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856],
    locale en-IN)
    • Flutter version 3.0.5 at C:\Users\Rapurva\AppData\Local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Rapurva\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.2.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\Rapurva\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment]
Thanks for the detailed log. This issue was initially reported in https://github.com/flutter/flutter/issues/104021 and has since been fixed by https://github.com/flutter/flutter/pull/104022.

The fix is available on the latest beta and master channels, so you will need to switch to either of them and try again to see the fix.

Per our triage policy, I'll be closing this as it has already been fixed on the master channel.

If you run into this issue on either the beta channel or master channel, write in comments and I'll reopen it.
