### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by jmscxnulleins** [flutter/flutter#110391]
System: Windows 11 Pro-V-21H2-Build:22000.856-64-Bit-Betriebssystem, x64-basierter Prozessor . Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz   3.10 GHz .12,0 GB (11,9 GB verwendbar) .

Tools - Terminal -  PS Win11, VS Code Terminal

## Command
```
flutter run
```

## Steps to Reproduce
1.

PS E:\xxx\xxx\xxx\xxx\xxx\Web\dev> flutter create xxx_fl_test
Creating project xxx_fl_test...
Running "flutter pub get" in xxx_fl_test...                      2.291ms
Wrote 127 files.

All done!

2. Launching lib\main.dart on Chrome in debug mode...

Waiting for connection from debug service on Chrome...                 ⠸
Oops; flutter has exited unexpectedly: "ShaderCompilerException: Shader compilation of
"C:\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag" to
"build\flutter_assets\shaders/ink_sparkle.frag" failed with exit code -1073740791.
impellerc stdout:

impellerc stderr:
".

3. 
## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:189:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:185:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:163:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:866:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:489:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.1.0-0.0.pre.2534, on Microsoft Windows [Version 10.0.22000.856], locale de-DE)
    [32m•[39m Flutter version 3.1.0-0.0.pre.2534 on channel master at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 7092c1129c (3 hours ago), 2022-08-26 19:14:19 -0400
    [32m•[39m Engine revision e21a23e0a3
    [32m•[39m Dart version 2.19.0 (build 2.19.0-144.0.dev)
    [32m•[39m DevTools version 2.16.0

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.11)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.32228.343
    [31m✗[39m The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[32m[✓][39m VS Code, 64-bit edition (version 1.70.2)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.63

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 7092c1129c79f50d606c586e53c088e7983a67cd

**Comment by darshankawar** [comment]
I believe this is similar to https://github.com/flutter/flutter/issues/107590, so please follow-up in it for further updates.
Closing this as a duplicate.

**Comment by jmscxnulleins** [comment]
Thank you! I have a look at https://github.com/flutter/flutter/issues/107590!
I´m new here and try to learn more. This was my first Issue. Try to get better in this. :)
