### ISSUE TITLE
[macOS] UiKitView throws a "PlatformException(recreating_view, trying to create an already created view, view id: '0', null)" after hot-restart

### ISSUE THREAD

**Issue by akaboshinit** [flutter/flutter#110381]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Whenever I develop with UIKitView on macOS and restart, I get `[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(recreating_view, trying to create an already created view, view` This error occurs. Trying to insert a key or use a unique key for key does not solve the problem.

**Expected results:** 
Ability to restart correctly during development

**Actual results:** 
Duplicate id not reset correctly and error occurs.

I have an idea of the problem, and it's in the error, but it's a duplicate id!
I found an implementation that is issuing ids, but they are either resetting unexpectedly or issuing incorrect ids.

flutter/3.0.5-stable/packages/flutter/lib/src/widgets/platform_view.dart
```
class PlatformViewsRegistry {
  PlatformViewsRegistry._instance();

  // Always non-negative. The id value -1 is used in the accessibility bridge
  // to indicate the absence of a platform view.
  int _nextPlatformViewId = 0;

  /// Allocates a unique identifier for a platform view.
  ///
  /// A platform view identifier can refer to a platform view that was never created,
  /// a platform view that was disposed, or a platform view that is alive.
  ///
  /// Typically a platform view identifier is passed to a platform view widget
  /// which creates the platform view and manages its lifecycle.
  int getNextPlatformViewId() => _nextPlatformViewId++;
}
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  InlineWebViewMacOsController? _controller;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            const UIKitViewErrorMacOsWidget()
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class UIKitViewErrorMacOsWidget extends StatelessWidget {
  const UIKitViewErrorMacOsWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      return SizedBox(
        width: 200,
        height: 200,
        child: UiKitView(
          key: key,
          viewType: 'uikitview_error_macos_view',
        ),
      );
    }

    return const SizedBox();
  }
}

```

```swift
import Cocoa
import FlutterMacOS

class MainFlutterWindow: NSWindow {
  override func awakeFromNib() {
    let flutterViewController = FlutterViewController.init()
    let windowFrame = self.frame
    self.contentViewController = flutterViewController
    self.setFrame(windowFrame, display: true)

    RegisterGeneratedPlugins(registry: flutterViewController)

    SwiftFlutterPlugin.register(
        with: flutterViewController.registrar(forPlugin: "SwiftFlutterPlugin")
    )

    super.awakeFromNib()
  }
}

public class SwiftFlutterPlugin: NSObject, FlutterPlugin {

    static var instance: SwiftFlutterPlugin?
    var registrar: FlutterPluginRegistrar?

    public init(with registrar: FlutterPluginRegistrar) {
        super.init()

        self.registrar = registrar
        registrar.register(
            NativeViewFactory(messenger: registrar.messenger) as FlutterPlatformViewFactory,
            withId: "uikitview_error_macos_view")
    }

    public static func register(with registrar: FlutterPluginRegistrar) {
        SwiftFlutterPlugin.instance = SwiftFlutterPlugin(with: registrar)
    }

    public func detachFromEngine(for registrar: FlutterPluginRegistrar) {
    }
}

public class NativeViewFactory: NSObject, FlutterPlatformViewFactory
{
    init(messenger: FlutterBinaryMessenger) {
        self.messenger = messenger
        super.init()
    }

    public func createArgsCodec() -> FlutterMessageCodec & NSObjectProtocol {
        return FlutterStandardMessageCodec.sharedInstance()
    }
    
    private var messenger: FlutterBinaryMessenger

    public func create(
        withViewIdentifier viewId: Int64,
        arguments args: Any?
    )
        -> NSView
    {
        return NativeView(
            viewIdentifier: viewId,
            arguments: args,
            binaryMessenger: messenger)
    }
}

public func createLabel() -> NSTextField {
    let nativeLabel = NSTextField()
    nativeLabel.frame = CGRect(x: 0, y: 0, width: 180, height: 48.0)
    nativeLabel.stringValue = "Native text from macOS"
    nativeLabel.textColor = NSColor.red
    nativeLabel.isBezeled = false
    nativeLabel.isEditable = false
    nativeLabel.sizeToFit()
    return nativeLabel
}

class NativeView: NSView {

    init(
        viewIdentifier viewId: Int64,
        arguments args: Any?,
        binaryMessenger messenger: FlutterBinaryMessenger?
    ) {
        let frame = CGRect(x: 0, y: 0, width: 200, height: 200)
        super.init(frame: frame)
        super.wantsLayer = true
        super.layer?.backgroundColor = NSColor.blue.cgColor
        super.frame = frame
        super.addSubview(createLabel())
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:51030/1RLhAwPR0yE=/
[ +182 ms] The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9108?uri=http://127.0.0.1:51030/1RLhAwPR0yE=/
[+11975 ms] Skipping target: gen_localizations
[        ] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Performing hot reload...
[   +6 ms] Scanned through 531 files in 3ms
[        ] Syncing files to device macOS...
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:all/main.dart 2a5f529b-6f22-414a-9aec-669f46f08913
[        ] <- 2a5f529b-6f22-414a-9aec-669f46f08913
[        ] Bundle processing done.
[   +6 ms] Updating files.
[   +1 ms] DevFS: Sync finished
[        ] Syncing files to device macOS... (completed in 8ms)
[        ] Synced 0.0MB.
[   +8 ms] Reassembling application
[  +34 ms] Hot reload performed in 55ms.
[        ] Performing hot reload... (completed in 58ms)
[        ] Reloaded 0 libraries in 62ms.
[+1764 ms] Skipping target: gen_localizations
[        ] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Performing hot restart...
[   +3 ms] Scanned through 531 files in 2ms
[        ] Syncing files to device macOS...
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:all/main.dart dddac9ea-9201-45eb-99ba-7727e5adce2d
[        ] <- dddac9ea-9201-45eb-99ba-7727e5adce2d
[        ] Bundle processing done.
[  +36 ms] Updating files.
[  +14 ms] DevFS: Sync finished
[        ] Syncing files to device macOS... (completed in 52ms)
[        ] Synced 29.3MB.
[        ] <- accept
[ +196 ms] Hot restart performed in 252ms.
[        ] Performing hot restart... (completed in 254ms)
[        ] Restarted application in 256ms.
[ +317 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(recreating_view, trying to create an already created view, view
id: '0', null)
[        ] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
[        ] <asynchronous suspension>
[        ] #2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:229:5)
[        ] <asynchronous suspension>
[        ] #3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:639:44)
[        ] <asynchronous suspension>
```

```
% flutter analyze
Analyzing all...                                                        
No issues found! (ran in 1.4s)
```

```
% flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.0.1 21A559 darwin-arm, locale ja-JP)
    • Flutter version 3.0.5 at /Users/redstar16/.asdf/installs/flutter/3.0.5-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/redstar16/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<img width="300" alt="" src="https://user-images.githubusercontent.com/69136342/186996404-66028da0-908f-4966-81a0-c1308ff4c936.png">

**Comment by danagbemava-nc** [comment]
I can reproduce the issue with the code sample provided.

Labeling for further investigation.

<details>
<summary>Code sample</summary>

### main.dart

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            const UIKitViewErrorMacOsWidget()
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class UIKitViewErrorMacOsWidget extends StatelessWidget {
  const UIKitViewErrorMacOsWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      return SizedBox(
        width: 200,
        height: 200,
        child: UiKitView(
          key: key,
          viewType: 'uikitview_error_macos_view',
        ),
      );
    }

    return const SizedBox();
  }
}
```


### MainFlutterWindow.swift

```swift
import Cocoa
import FlutterMacOS

class MainFlutterWindow: NSWindow {
  override func awakeFromNib() {
    let flutterViewController = FlutterViewController.init()
    let windowFrame = self.frame
    self.contentViewController = flutterViewController
    self.setFrame(windowFrame, display: true)

    RegisterGeneratedPlugins(registry: flutterViewController)

    SwiftFlutterPlugin.register(
        with: flutterViewController.registrar(forPlugin: "SwiftFlutterPlugin")
    )

    super.awakeFromNib()
  }
}

public class SwiftFlutterPlugin: NSObject, FlutterPlugin {

    static var instance: SwiftFlutterPlugin?
    var registrar: FlutterPluginRegistrar?

    public init(with registrar: FlutterPluginRegistrar) {
        super.init()

        self.registrar = registrar
        registrar.register(
            NativeViewFactory(messenger: registrar.messenger) as FlutterPlatformViewFactory,
            withId: "uikitview_error_macos_view")
    }

    public static func register(with registrar: FlutterPluginRegistrar) {
        SwiftFlutterPlugin.instance = SwiftFlutterPlugin(with: registrar)
    }

    public func detachFromEngine(for registrar: FlutterPluginRegistrar) {
    }
}

public class NativeViewFactory: NSObject, FlutterPlatformViewFactory
{
    init(messenger: FlutterBinaryMessenger) {
        self.messenger = messenger
        super.init()
    }

    public func createArgsCodec() -> FlutterMessageCodec & NSObjectProtocol {
        return FlutterStandardMessageCodec.sharedInstance()
    }

    private var messenger: FlutterBinaryMessenger

    public func create(
        withViewIdentifier viewId: Int64,
        arguments args: Any?
    )
        -> NSView
    {
        return NativeView(
            viewIdentifier: viewId,
            arguments: args,
            binaryMessenger: messenger)
    }
}

public func createLabel() -> NSTextField {
    let nativeLabel = NSTextField()
    nativeLabel.frame = CGRect(x: 0, y: 0, width: 180, height: 48.0)
    nativeLabel.stringValue = "Native text from macOS"
    nativeLabel.textColor = NSColor.red
    nativeLabel.isBezeled = false
    nativeLabel.isEditable = false
    nativeLabel.sizeToFit()
    return nativeLabel
}

class NativeView: NSView {

    init(
        viewIdentifier viewId: Int64,
        arguments args: Any?,
        binaryMessenger messenger: FlutterBinaryMessenger?
    ) {
        let frame = CGRect(x: 0, y: 0, width: 200, height: 200)
        super.init(frame: frame)
        super.wantsLayer = true
        super.layer?.backgroundColor = NSColor.blue.cgColor
        super.frame = frame
        super.addSubview(createLabel())
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2552, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2552 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f66a097919 (7 hours ago), 2022-08-28 20:20:36 -0400
    • Engine revision 4e36ebc1f3
    • Dart version 2.19.0 (build 2.19.0-146.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[mac.log](https://github.com/flutter/flutter/files/9442962/mac.log)

**Comment by chinmaygarde** [comment]
cc @jmagman

**Comment by jmagman** [comment]
@cbracken working on macOS platform views.

**Comment by cbracken** [comment]
This is a sub-issue of https://github.com/flutter/flutter/issues/41722.

@danagbemava-nc PlatformViews are not yet supported on macOS (as suggested by UIKitView rather than AppKitView or NSView). Support in the engine and framework are work-in-progress.

**Comment by manojdcoder** [comment]
After upgrading to v3.27.x, expereincing this issue with ad mob plugin (googleads/googleads-mobile-flutter/issues/1217).
Does not happen with v3.24.5.

**Comment by EliaTolin** [comment]
Me too.

**Comment by BenjiFarquhar** [comment]
Happens with google_maps_flutter too.

**Comment by willsmanley** [comment]
Experiencing this with flutter_inappwebview on ios physical device with flutter v3.27.0. Is this a regression from 3.27? I don't recall this happening prior to a couple of weeks ago but haven't tried rolling back flutter.

**Comment by skaterschikov** [comment]
Same here

**Comment by SerdarYildiz06** [comment]
For fix add release and debug .entitlements files this line;
 <key>com.apple.security.app-sandbox</key>
<true/>

**Comment by MuhammedOzdogan** [comment]
I also have the same issue, I have BannerAd from `google_mobile_ads`

Flutter Version:  `Flutter 3.27.3`

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(recreating_view, trying to create an already created view, view id: '2', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:646:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:248:5)
<asynchronous suspension>
#3      _DarwinViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:921:36)
<asynchronous suspension>
```

**Comment by armenarutjunjan** [comment]
Is it normal that the Google Map View freezes after a hot reload? (the entire app freezes)

**Comment by aitzhanovalen** [comment]
the same error 
`PlatformException (PlatformException(recreating_view, trying to create an already created view, view id: '1', null))`

for webview_flutter and google_maps_flutter
Flutter Version:  Flutter 3.27.3

**Comment by BunnyBuddy** [comment]
I am not even using Webview where this error is fetched in Crashlytics and I am still seeing this issue occasionally while switching pages on Flutter 3.27.3. Never happened in older versions.

**Comment by BenjiFarquhar** [comment]
Can we add platform iOS to this ticket? The ticket makes it look like it is a MacOS only issue which might lower the priority.

**Comment by aitzhanovalen** [comment]
> the same error 
> `PlatformException (PlatformException(recreating_view, trying to create an already created view, view id: '1', null))`
> 
> for webview_flutter and google_maps_flutter
> Flutter Version:  Flutter 3.27.3
> 
> sometimes app crashes and closes when I try to open WebView with such kind of issue
> ```
> flutter: WebView is loading (progress : 25%)
> Could not cast value of type 'NSNull' (0x1040b6480) to 'webview_flutter_wkwebview.AuthenticationChallengeResponse' (0x10115eef8).
> Lost connection to device.
> ```
> 

I tried flutter beta channel and mistake disappeared. Then I moved back to stable channel and mistake came back.

Where can I see the planning date of new release of stable channel?

**Comment by zz1521** [comment]
I solved it by adding a GlobalKey to the view.It was useful for me.

`final GlobalKey gKey = GlobalKey();`

``` 
InAppWebView(
        key: gKey,
        initialUrlRequest: URLRequest(url: WebUri(state.currentUrl)),
        initialSettings: state.settings,
        onWebViewCreated: (controller) {
          state.webViewController = controller;
        },
        onLoadStop: (controller, url) {
          state.currentUrl = url.toString();
          state.urlController.text = url.toString();
        }
)
```

**Comment by MuhammedOzdogan** [comment]
Any update regarding this issue?

**Comment by aitzhanovalen** [comment]
> I solved it by adding a GlobalKey to the view.It was useful for me.
> 
> `final GlobalKey gKey = GlobalKey();`
> 
> ```
> InAppWebView(
>         key: gKey,
>         initialUrlRequest: URLRequest(url: WebUri(state.currentUrl)),
>         initialSettings: state.settings,
>         onWebViewCreated: (controller) {
>           state.webViewController = controller;
>         },
>         onLoadStop: (controller, url) {
>           state.currentUrl = url.toString();
>           state.urlController.text = url.toString();
>         }
> )
> ```

did not helped me.

upgraded to new version 3.27.4
and have the same issue

`Could not cast value of type 'NSNull' (0x10e0c3298) to 'webview_flutter_wkwebview.AuthenticationChallengeResponse' (0x103c62ef8).`

**Comment by alexquant1993** [comment]
I face the same issue with Flutter 3.27.4 using hot restart with google admob and also with mapbox. Any solutions besides downgrading?

**Comment by yesterdam** [comment]
`Could not cast value of type ‘NSNull’ (0x10a810100) to ‘webview_flutter_wkwebview.AuthenticationChallengeResponse’ (0x10187eef8).`

I resolved this issue by downgrading `webview_flutter_wkwebview` to version 3.17.0. It fixed the crash when loading specific websites. Hope this helps others!

**How to Fix:**
In your `pubspec.yaml`, add the following override:

```yaml
dependency_overrides:
  webview_flutter_wkwebview: 3.17.0

**Comment by venbrinoDev** [comment]
currently facing this issue with google map 

where google map freeze and throws this same platffrom exception

**Comment by PaulAllanSturm** [comment]
The problem here is that `FlutterEngine` does not clean up the old platform views in `_platformViewController` when it is hot-restarting:

https://github.com/flutter/flutter/blob/ce659cda5e1cf0d0ea3138c657169cb57da257d8/engine/src/flutter/shell/platform/darwin/macos/framework/Source/FlutterEngine.mm#L1121-L1127

We can add a line at the end of this function to do the cleanup:
```obj-c
  [_platformViewController onPreEngineRestart];
```

Then we can define the cleanup routine in `FlutterPlatformViewController.mm` (and the corresponding .h):
```obj-c
- (void)onPreEngineRestart {
    for (const auto& pair : _platformViews) {
        _platformViewsToDispose.insert(pair.first);
    }
    [self disposePlatformViews];
}
```
I hacked this together locally and it fixes the PlatformException. Should I pursue getting a patch created and submitted?

**Comment by jmagman** [comment]
> I hacked this together locally and it fixes the PlatformException. Should I pursue getting a patch created and submitted?

Sure, we would take a look at that PR.  Thank you!

**Comment by PaulAllanSturm** [comment]
PR submitted: https://github.com/flutter/flutter/pull/163439

**Comment by PaulAllanSturm** [comment]
Some of the comments here mention an error with "webview_flutter_wkwebview.AuthenticationChallengeResponse" in the message. That is possibly a separate issue. This issue and my PR address only the "recreating_view" error message.

Separately, note that this is a macos-only problem. The iOS PlatformView implementation does not share this code, and Hot Restart works fine with Platform Views on iOS.

**Comment by yanweimin7** [comment]
> Some of the comments here mention an error with "webview_flutter_wkwebview.AuthenticationChallengeResponse" in the message. That is possibly a separate issue. This issue and my PR address only the "recreating_view" error message.
> 
> Separately, note that this is a macos-only problem. The iOS PlatformView implementation does not share this code, and Hot Restart works fine with Platform Views on iOS.

ios still face this issue , it can repreduce。
![Image](https://github.com/user-attachments/assets/de913823-db97-42ff-9276-b448304e1131)

**Comment by PaulAllanSturm** [comment]
> ios still face this issue , it can repreduce。

The reproducing code in this issue only runs on macOS. Can you post your code that reproduces this exception on iOS? I'm not sure if it is best to write that up as a separate issue, because it would require a separate fix.

**Comment by shinriyo** [comment]
WebView simulator bug? not fix yet?
iOS simulator too
It happnes mapbox one also

**Comment by PaulAllanSturm** [comment]
I wrote up the iOS issue separately at https://github.com/flutter/flutter/issues/163935.

**Comment by PaulAllanSturm** [comment]
Should this issue be closed now that https://github.com/flutter/flutter/pull/163439 has been merged to main?

**Comment by danagbemava-nc** [comment]
Closing this as fixed since the PR has been merged.
