### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by caltinsoy** [flutter/flutter#110409]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:189:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:185:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:163:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:866:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:489:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.1.0-0.0.pre.2539, on Microsoft Windows [Version 10.0.19044.1889], locale tr-TR)
    [32m•[39m Flutter version 3.1.0-0.0.pre.2539 on channel master at C:\Users\cemal\OneDrive\Masaüstü\Flutter\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 281c2b9a68 (3 hours ago), 2022-08-27 05:59:34 -0400
    [32m•[39m Engine revision e5a8c34176
    [32m•[39m Dart version 2.19.0 (build 2.19.0-145.0.dev)
    [32m•[39m DevTools version 2.16.0

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[32m[✓][39m IntelliJ IDEA Community Edition (version 2021.3)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2021.1)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.1
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2022.2)
    [32m•[39m IntelliJ at C:\Users\cemal\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.3739.54
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m VS Code (version 1.67.1)
    [32m•[39m VS Code at C:\Users\cemal\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.46.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.70

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 281c2b9a6889ce6d2e474ddc9f25d73d111c801a

**Comment by darshankawar** [comment]
This is similar to https://github.com/flutter/flutter/issues/107590, so please follow-up in it for further updates.
Closing this as duplicate.
