### ISSUE TITLE
[Cocoon] GitHub webhooks failing to publish to pubsub

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#110487]
Culprit is https://github.com/flutter/cocoon/pull/2068

I've rolled back the Cocoon version for now as it should be a quick fix forward.

**Comment by CaseyHillers** [comment]
Logs are filled with

```
Converting object to an encodable object failed: Instance of 'GithubWebhookMessage'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:794:7)
#1      _JsonStringStringifier.printOn (dart:convert/json.dart:983:17)
#2      _JsonStringStringifier.stringify (dart:convert/json.dart:968:5)
#3      JsonEncoder.convert (dart:convert/json.dart:345:30)
#4      JsonCodec.encode (dart:convert/json.dart:231:45)
#5      jsonEncode (dart:convert/json.dart:114:10)
#6      PubSub.publish (package:cocoon_service/src/request_handling/pubsub.dart:28:32)
<asynchronous suspension>
#7      GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:44:5)
<asynchronous suspension>
#8      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:52:22)
<asynchronous suspension>
#9      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:275:9)
<asynchronous suspension>
```

**Comment by CaseyHillers** [comment]
I rolled back today's release as well.

The issue today is it can't find the pubsub topic even though it exists. It is 404'ing as github-webhooks (the resource) cannot be found.
