### ISSUE TITLE
Flutter widgets get distorted while scrolling along with platform views

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/flutter#110414]
<table>
<thead>
  <tr>
    <th>Frame</th>
    <th>Video</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><img width="652" alt="CleanShot 2022-08-27 at 15 58 23@2x" src="https://user-images.githubusercontent.com/16854239/187033472-6d33a44d-6705-445a-88a2-86985617e60b.png"> </td>
    <td><video src="https://user-images.githubusercontent.com/16854239/187033488-01f9b0bd-c5ad-45fd-a9bd-70facdadd47f.mp4">https://user-images.githubusercontent.com/16854239/187033488-01f9b0bd-c5ad-45fd-a9bd-70facdadd47f.mp4</video></td>
  </tr>
</tbody>
</table>

## Steps to Reproduce

1. Execute `flutter run` on the code sample [in flutter benchmarks](https://github.com/flutter/flutter/blob/master/dev/benchmarks/platform_views_layout_hybrid_composition/lib/main.dart)
2. Scroll very fast on Android (SM G950F (Samsung S8) • android-arm64  • Android 9 (API 28))
3. Observe rotating widgets to be displayed as wide rectangles (see image above)

**Expected results:** 

Widgets should not distort

**Actual results:** 

Blue widget seems to be distorted

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2539, on macOS 12.4 21F79 darwin-arm, locale pl-PL)
    • Flutter version 3.1.0-0.0.pre.2539 on channel master at /Users/dominik/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 281c2b9a68 (4 hours ago), 2022-08-27 05:59:34 -0400
    • Engine revision e5a8c34176
    • Dart version 2.19.0 (build 2.19.0-145.0.dev)
    • DevTools version 2.16.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dominik/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • SM G950F (mobile) • ce031713b404900c0d • android-arm64  • Android 9 (API 28)
    • macOS (desktop)   • macos              • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by adilwahla** [comment]
Hey did you tried ScrollPhysics class? give a try 
https://api.flutter.dev/flutter/widgets/ScrollPhysics-class.html

**Comment by adilwahla** [comment]
give a try 
1- connect the ScrollController to your list
2- use AnimatedContainer()  for animation
```
ListView.builder(
              controller: _controller,

```
 get detailed insight here 
https://medium.com/@diegoveloper/flutter-lets-know-the-scrollcontroller-and-scrollnotification-652b2685a4ac

**Comment by huycozy** [comment]
Hi @orestesgaolin, thanks for filing the issue. This issue is reproducible on the latest `stable` and `master` channels with code sample [in flutter benchmarks](https://github.com/flutter/flutter/blob/master/dev/benchmarks/platform_views_layout_hybrid_composition/lib/main.dart)
<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/187163929-5742109c-6d68-4eb7-abcd-44a81deed4b4.mp4


</details>

<details>
<summary>Logs</summary>

```bash
An Observatory debugger and profiler on iPhone 13 is available at: http://127.0.0.1:53753/mDTp2wkfuTQ=/
The Flutter DevTools debugger and profiler on iPhone 13 is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:53753/mDTp2wkfuTQ=/

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
_RotationContainerState#f4057(ticker active) was disposed with an active Ticker.
_RotationContainerState created a Ticker via its SingleTickerProviderStateMixin, but at the time
dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before
calling super.dispose().
Tickers used by AnimationControllers should be disposed by calling dispose() on the
AnimationController itself. Otherwise, the ticker will leak.
The offending ticker was:
  Ticker(created by _RotationContainerState#f4057)
  The stack trace when the Ticker was actually created was:
  #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
  #1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
  #2      SingleTickerProviderStateMixin.createTicker
  (package:flutter/src/widgets/ticker_provider.dart:198:15)
  #3      new AnimationController (package:flutter/src/animation/animation_controller.dart:246:21)
  #4      _RotationContainerState.initState
  (package:platform_views_layout_hybrid_composition/main.dart:113:27)
  #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4942:57)
  #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
  #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
  #8      MultiChildRenderObjectElement.inflateWidget
  (package:flutter/src/widgets/framework.dart:6350:36)
  #9      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
  ...     Normal element mounting (78 frames)
  #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
  #88     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
  #89     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1265:37)
  #90     SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
  (package:flutter/src/widgets/sliver.dart:1250:20)
  #91     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
  #92     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1242:12)
  #93     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
  (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
  #94     RenderObject.invokeLayoutCallback.<anonymous closure>
  (package:flutter/src/rendering/object.dart:2025:59)
  #95     PipelineOwner._enableMutationsToDirtySubtrees
  (package:flutter/src/rendering/object.dart:918:15)
  #96     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2025:14)
  #97     RenderSliverMultiBoxAdaptor._createOrObtainChild
  (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
  #98     RenderSliverMultiBoxAdaptor.insertAndLayoutChild
  (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:484:5)
  #99     RenderSliverList.performLayout.advance
  (package:flutter/src/rendering/sliver_list.dart:239:19)
  #100    RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:281:12)
  #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #102    RenderSliverEdgeInsetsPadding.performLayout
  (package:flutter/src/rendering/sliver_padding.dart:137:12)
  #103    RenderSliverPadding.performLayout
  (package:flutter/src/rendering/sliver_padding.dart:371:11)
  #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #105    RenderViewportBase.layoutChildSequence
  (package:flutter/src/rendering/viewport.dart:510:13)
  #106    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
  #107    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
  #108    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #121    MultiChildLayoutDelegate.layoutChild
  (package:flutter/src/rendering/custom_layout.dart:171:12)
  #122    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003:7)
  #123    MultiChildLayoutDelegate._callPerformLayout
  (package:flutter/src/rendering/custom_layout.dart:240:7)
  #124    RenderCustomMultiChildLayoutBox.performLayout
  (package:flutter/src/rendering/custom_layout.dart:403:14)
  #125    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #126    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #127    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #128    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #129    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
  #130    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #131    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #132    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #133    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #134    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #135    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #136    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #137    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
  #138    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:552:43)
  #139    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:579:12)
  #140    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #141    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #142    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #143    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #144    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #145    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #146    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #147    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #148    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #149    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #150    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #151    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #152    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #153    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #154    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462:13)
  #155    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #156    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #157    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #158    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749:15)
  #159    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #160    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #161    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #162    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #163    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #164    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #165    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #166    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #167    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
  #168    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #169    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #170    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #171    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #172    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #173    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #174    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #175    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
  #176    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
  #177    RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
  #178    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
  #179    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
  #180    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
  #181    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
  #182    RendererBinding._handlePersistentFrameCallback
  (package:flutter/src/rendering/binding.dart:370:5)
  #183    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
  #184    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
  #185    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
  (package:flutter/src/scheduler/binding.dart:864:7)
  (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

When the exception was thrown, this was the stack:
#0      SingleTickerProviderStateMixin.dispose.<anonymous closure>
(package:flutter/src/widgets/ticker_provider.dart:209:7)
#1      SingleTickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:223:6)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5032:11)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1914:13)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#5      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6314:16)
#6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#14     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#29     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#35     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
#49     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#50     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1923:25)
#51     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2516:15)
#52     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2932:7)
#53     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:893:19)
#54     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#55     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#56     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#57     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#61     _invoke (dart:ui/hooks.dart:151:10)
#62     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#63     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: _RotationContainerState#eb84d(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#f7121(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#95898(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#2c048(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#26726(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#0a7e8(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#63093(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#6e403(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#17a40(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#f9244(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#40a11(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#8b481(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#6bd35(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#34b2f(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#6bd99(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#8eb92(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#18b48(ticker active) was disposed with an active Ticker.

Another exception was thrown: _RotationContainerState#26c66(ticker active) was disposed with an active Ticker.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2552, on macOS 12.5 21G72 darwin-x64, locale en-EE)
    • Flutter version 3.1.0-0.0.pre.2552 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f66a097919 (2 hours ago), 2022-08-28 20:20:36 -0400
    • Engine revision 4e36ebc1f3
    • Dart version 2.19.0 (build 2.19.0-146.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by orestesgaolin** [comment]
@huycozy just to avoid confusion - this error is also shown when [this change](https://github.com/flutter/flutter/pull/110413) is applied i.e. tickers get properly disposed
