### ISSUE TITLE
Hero assertion due to dismissed AnimationStatus on toRoute

### ISSUE THREAD

**Issue by markphillips100** [flutter/flutter#110426]
I'm using [https://pub.dev/packages/routemaster](https://pub.dev/packages/routemaster) for navigation and come across an issue when using Heroes in my setup.  I've added a demo app to replicate the issue at [https://github.com/markphillips100/herotest](https://github.com/markphillips100/herotest).

The strategy of the app is to show how to switch between responsive layouts; one for mobiles with a single page navigator, and one for wider viewports with a splitview where the left side is the root page and the right side uses it's own page navigator stack (using `StackPage`).  Rotating the device would switch between the layouts and retain the existing route path.

Hero transitions should work within the mobile layout for all pages.  For the wider layout, the left side heroes should be disabled, and the right side hero transitions should work inside of their own navigator stack.

This all seems to works fine.  Navigation okay, and heroes isolated to their navigator stack okay.  Problem occurs only when rotating from wide layout to mobile layout, and only when the right side has pushed another page above the stack's default path.

The exception I get is an assertion in flutter's heroes.dart file:
```
      final Animation<double> initial = initialManifest.animation;
      assert(initial != null);
      final HeroFlightDirection type = initialManifest.type;
      assert(type != null);
      switch (type) {
        case HeroFlightDirection.pop:
          return initial.value == 1.0 && initialManifest.isUserGestureTransition
              // During user gesture transitions, the animation controller isn't
              // driving the reverse transition, but should still be in a previously
              // completed stage with the initial value at 1.0.
              ? initial.status == AnimationStatus.completed
              : initial.status == AnimationStatus.reverse;
        case HeroFlightDirection.push:
          return initial.value == 0.0 && initial.status == AnimationStatus.forward;
      }
    }()': is not true.
```
I've stepped through the assertion logic using Android Studio and it fails because the last line's `initial.status` is `AnimationStatus.declined`.

To reproduce just follow these steps:
1. Start an Android emulator (haven't tried iOS) and rotate to landscape mode.  Ensure the OS AutoRotate is enabled in settings.
2. Launch app.  Should see a split view with "Wide Layout" Page on left and Page Two on right.
3. Press "Select three".  Navigates right side to page three.
4. Rotate emulator to portrait.  App will respond and throw the exception above.

My solution to this is to provide a custom HeroController via a new HeroControllerScope wrapped around the root Navigator.  It's purpose is purely to filter routes in the `didPush` where the route's animation status is dismissed, and just not call the  `super.didPush(...)`, as shown in this code:

```
class CustomHeroController extends HeroController {
  CustomHeroController({ createRectTween })
  : super(createRectTween: createRectTween);

  static HeroController createMaterialHeroController() {
    return CustomHeroController(createRectTween: (Rect? begin, Rect? end) {
        return MaterialRectArcTween(begin: begin, end: end);
      },
    );
  }

  @override
  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) {
    if (route is PageRoute<dynamic> && route.animation?.status == AnimationStatus.dismissed) {
      return;
    }
    super.didPush(route, previousRoute);
  }
}
```

What I'm wondering though is whether this logic should be in the base HeroController's `_maybeStartHeroTransition(...)` method and therefore not initiate an animation that will throw the assertion?

**Comment by markphillips100** [comment]
Hi @danagbemava-nc, and thank you for taking a look.  Apologies for not providing environment details.  I've added them below.

Also, I forgot to mention the branch you would have tried has the workaround `CustomHeroController` enabled in the `main.dart` file so probably why it didn't exception for you.  I've commited a change to use the standard `MaterialApp.createMaterialHeroController()` so you just need to git pull and retest.

I get the exception on a Pixel 3a and 4 emulator so far.  Not tried anything else.

The exception is due to the `initial.status` value being `AnimationStatus.dismissed` in this line:
```
return initial.value == 0.0 && initial.status == AnimationStatus.forward;
```
The full exception:
```
Restarted application in 738ms.
I/flutter ( 4627): Current responsive view is ResponsiveViewEnum.mobile
I/flutter ( 4627): Current responsive view is ResponsiveViewEnum.tablet
I/flutter ( 4627): Current responsive view is ResponsiveViewEnum.mobile

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 639 pos 12: '() {
package:flutter/…/widgets/heroes.dart:639
      final Animation<double> initial = initialManifest.animation;
      assert(initial != null);
      final HeroFlightDirection type = initialManifest.type;
      assert(type != null);
      switch (type) {
        case HeroFlightDirection.pop:
          return initial.value == 1.0 && initialManifest.isUserGestureTransition
              // During user gesture transitions, the animation controller isn't
              // driving the reverse transition, but should still be in a previously
              // completed stage with the initial value at 1.0.
              ? initial.status == AnimationStatus.completed
              : initial.status == AnimationStatus.reverse;
        case HeroFlightDirection.push:
          return initial.value == 0.0 && initial.status == AnimationStatus.forward;
      }
    }()': is not true.

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      _HeroFlight.start
package:flutter/…/widgets/heroes.dart:639
#3      HeroController._startHeroTransition
package:flutter/…/widgets/heroes.dart:962
#4      HeroController._maybeStartHeroTransition.<anonymous closure>
package:flutter/…/widgets/heroes.dart:884
#5      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1146
#6      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1091
#7      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:997
#11     _invoke (dart:ui/hooks.dart:151:10)
#12     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#13     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

```

```
flutter doctor -v

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-AU)
    • Flutter version 3.0.5 at D:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\mark_\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32804.467
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\mark_\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 104.0.1293.63

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by markphillips100** [comment]
As for an alternative demo without the 3rd party Routemaster, my knowledge of Navigator 2.0 is limited but I've started something in another branch https://github.com/markphillips100/herotest/tree/basic-nav2-router.  It's not quite behaving yet, as in it doesn't really replicate my use case, and isn't throwing the exception yet either.

I shall persist, but in the meantime the current demo will hopefully be enough.

**Comment by danagbemava-nc** [comment]
> I shall persist, but in the meantime the current demo will hopefully be enough.

I have been able to reproduce the assertion you were referring to so, yes, the code sample is enough

### Steps to reproduce (copied from initial post)
1. Start an emulator/simulator and rotate to landscape mode. Ensure the OS AutoRotate is enabled in settings.
2. Launch app. You should see a split view with "Wide Layout" Page on left and Page Two on right.
3. Press "Select three". Navigates right side to page three.
4. Rotate emulator to portrait. App will respond and throw the exception above.

The code sample has been attached below for easy access.

Labeling for further insight from the team

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1889], locale en-GH)
    • Flutter version 3.0.5 at c:\src\sdks\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1889]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 104.0.1293.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[√] Flutter (Channel master, 3.1.0-0.0.pre.2574, on Microsoft Windows [Version 10.0.19043.1889], locale en-GH)
    • Flutter version 3.1.0-0.0.pre.2574 on channel master at c:\src\sdks\master\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 052cd87246 (2 hours ago), 2022-08-30 00:26:24 -0400
    • Engine revision 28e8fe2765
    • Dart version 2.19.0 (build 2.19.0-150.0.dev)
    • DevTools version 2.16.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1889]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 104.0.1293.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[verbose.log](https://github.com/flutter/flutter/files/9450342/verbose.log)

[herotest.zip](https://github.com/flutter/flutter/files/9450339/herotest.zip)
