### ISSUE TITLE
[go_router] throws when calling an unknown route in profile or release mode

### ISSUE THREAD

**Issue by Cteq3132** [flutter/flutter#110511]
Hello, I have an issue regarding GoRouter : 

## Steps to Reproduce

1. Create a new flutter app
2. Replace `main.dart` by this :
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final GoRouter router = GoRouter(
      routes: <GoRoute>[
        GoRoute(
          path: '/',
          builder: (BuildContext context, GoRouterState state) =>
              const MyHomePage(title: 'Flutter Demo Home Page'),
        ),
      ],
    );
    return MaterialApp.router(
      title: 'Flutter Demo',
      routeInformationParser: router.routeInformationParser,
      routeInformationProvider: router.routeInformationProvider,
      routerDelegate: router.routerDelegate,
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
          child: ElevatedButton(
        onPressed: () => context.push('/unknown'),
        child: const Text('Navigate to unknown page'),
      )),
    );
  }
}
```
4. Build in release or profile mode `flutter run --release`
5. Clic on the button and the following error appears : 

## Logs

<details>
<summary>Logs</summary>

```
I/flutter (14066): LateInitializationError: Local 'initialMatches' has already been initialized.
I/flutter (14066): #0      LateError._throwLocalAlreadyInitialized (dart:_internal-patch/internal_patch.dart:204)
I/flutter (14066): #1      GoRouteInformationParser.parseRouteInformation (package:go_router/src/parser.dart:69)
I/flutter (14066): #2      GoRouter.push (package:go_router/src/router.dart:186)
I/flutter (14066): #3      GoRouterHelper.push (package:go_router/src/misc/extensions.dart:41)
I/flutter (14066): #4      MyHomePage.build.<anonymous closure> (package:go_router_error/main.dart:44)
I/flutter (14066): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005)
I/flutter (14066): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198)
I/flutter (14066): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613)
I/flutter (14066): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298)
I/flutter (14066): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:232)
I/flutter (14066): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563)
I/flutter (14066): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94)
I/flutter (14066): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139)
I/flutter (14066): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
I/flutter (14066): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137)
I/flutter (14066): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123)
I/flutter (14066): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445)
I/flutter (14066): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425)
I/flutter (14066): #18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329)
I/flutter (14066): #19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380)
I/flutter (14066): #20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344)
I/flutter (14066): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302)
I/flutter (14066): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285)
I/flutter (14066): #26     _invoke1 (dart:ui/hooks.dart:170)
I/flutter (14066): #27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331)
I/flutter (14066): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:94)
I/flutter (14066): (elided 3 frames from dart:async)
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale fr-FR)
    • Flutter version 3.0.5 at /Users/louisdachet/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (il y a 7 semaines), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/louisdachet/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 13 mini (mobile)     • 8D6A52D0-A181-4227-A9E7-33CAAF891258 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPhone 13 (mobile)          • D3C89832-C658-4ABD-8AE1-64451C94A5F3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

## Expected behavior 

The expected behavior is the behavior than in debug mode, ie. landing on the following default error page : 
<img src="https://user-images.githubusercontent.com/87450402/187258724-0aaf8502-723f-42af-910a-583892deab0d.png"  height="800">

Thanks for your answers !

**Comment by exaby73** [comment]
Hello @Cteq3132. This issue is reproducible on stable and beta but seems to work as expected in master. Therefore, I am closing this issue. If you disagree, please comment and I'll reopen it.
