### ISSUE TITLE
Exception thrown when a DraggableScrollableSheet is taken out of the tree before animateTo finishes

### ISSUE THREAD

**Issue by gbarbieripederiva** [flutter/flutter#110584]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap the button to trigger the DraggableScrollableSheet (the one that says trigger).
3. Just after you press the previous button, and before the animation finishes, tap the hide button. 

**Expected results:** 
This should just take the DraggableScrollableSheet out of the tree without errors.

**Actual results:** 

This produced the error below.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool showDraggable = false;
  bool scrollTrigger = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: SafeArea(
        child: Stack(
          children: [
            if (showDraggable)
              DraggableWidget(
                scrollTrigger: scrollTrigger,
              ),
            Positioned(
              left: 0,
              top: 0,
              child: ElevatedButton(
                onPressed: () {
                  setState(() {
                    showDraggable = !showDraggable;
                  });
                },
                child: showDraggable ? const Text('hide') : const Text('show'),
              ),
            ),
            Positioned(
              right: 0,
              top: 0,
              child: ElevatedButton(
                onPressed: () {
                  setState(() {
                    scrollTrigger = !scrollTrigger;
                  });
                },
                child: const Text('trigger'),
              ),
            ),
          ],
        ),
      )),
    );
  }
}

class DraggableWidget extends StatefulWidget {
  final bool scrollTrigger;

  const DraggableWidget({required this.scrollTrigger, Key? key})
      : super(key: key);

  @override
  State<DraggableWidget> createState() => _DraggableWidgetState();
}

class _DraggableWidgetState extends State<DraggableWidget> {
  late DraggableScrollableController controller;
  double scrollSize = 0.3;

  @override
  void initState() {
    super.initState();
    controller = DraggableScrollableController();
    controller.addListener(updateSize);
  }

  void updateSize() {
    scrollSize = controller.size;
  }

  @override
  void dispose() {
    controller.removeListener(updateSize);
    controller.dispose();
    super.dispose();
  }

  @override
  void didUpdateWidget(DraggableWidget oldWidget) {
    super.didUpdateWidget(oldWidget);

    WidgetsBinding.instance.addPostFrameCallback((timestamp) {
      if (0.5 > controller.size) {
        controller.animateTo(0.8,
            duration: const Duration(milliseconds: 500), curve: Curves.ease);
      } else {
        controller.animateTo(0.3,
            duration: const Duration(milliseconds: 500), curve: Curves.ease);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      minChildSize: 0.3,
      maxChildSize: 0.8,
      initialChildSize: scrollSize,
      controller: controller,
      builder: ((context, scrollController) {
        return SingleChildScrollView(
          controller: scrollController,
          child: Container(
            height: 100,
            color: Colors.red,
          ),
        );
      }),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
                     ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                     The following assertion was thrown while finalizing the widget tree:
                     ScrollableState#641cc(tickers: tracking 1 ticker, position:
                     _DraggableScrollableSheetScrollPosition#576a8(offset: 0.0, range: -1.0..1.0, viewport: 471.3,
                     ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, null,
                     ScrollDirection.idle), effective physics: ClampingScrollPhysics -> RangeMaintainingScrollPhysics)
                     was disposed with an active Ticker.
                     ScrollableState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was
                     called on the mixin, that Ticker was still active. All Tickers must be disposed before calling
                     super.dispose().
                     Tickers used by AnimationControllers should be disposed by calling dispose() on the
                     AnimationController itself. Otherwise, the ticker will leak.
                     The offending ticker was:
                       _WidgetTicker(created by ScrollableState#641cc)
                       The stack trace when the _WidgetTicker was actually created was:
                       #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
                       #1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
                       #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:385:81)
                       #3      TickerProviderStateMixin.createTicker
                       (package:flutter/src/widgets/ticker_provider.dart:295:34)
                       #4      new AnimationController.unbounded
                       (package:flutter/src/animation/animation_controller.dart:279:21)
                       #5      DraggableScrollableController.animateTo
                       (package:flutter/src/widgets/draggable_scrollable_sheet.dart:107:73)
                       #6      _DraggableWidgetState.didUpdateWidget.<anonymous closure> (package:issue/main.dart:98:20)
                       #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
                       #8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1091:9)
                       #9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
                       #13     _invoke (dart:ui/hooks.dart:151:10)
                       #14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
                       #15     _drawFrame (dart:ui/hooks.dart:115:31)
                       (elided 3 frames from dart:async)
                     
                     When the exception was thrown, this was the stack:
                     #0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:342:13)
                     #1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:360:6)
                     #2      RestorationMixin.dispose (package:flutter/src/widgets/restoration.dart:983:11)
                     #3      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:516:11)
                     #4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5032:11)
                     #5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1914:13)
                     #6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
                     #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
                     #8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
                     #9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
                     #10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
                     #11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
                     #12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
                     #13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
                     #14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
                     #15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
                     #16     _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:68:14)
                     #17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
                     #18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
                     #19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
                     #20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
                     #21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1912:7)
                     #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
                     #23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1910:13)
                     #24     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
                     #25     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1923:25)
                     #26     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2516:15)
                     #27     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2932:7)
                     #28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:893:19)
                     #29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
                     #30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
                     #31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
                     #32     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
                     #36     _invoke (dart:ui/hooks.dart:151:10)
                     #37     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
                     #38     _drawFrame (dart:ui/hooks.dart:115:31)
                     (elided 3 frames from dart:async)
                     ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +2 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[  +15 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[  +15 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[  +15 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[   +8 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[   +8 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[   +8 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[   +8 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[   +6 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[   +9 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[  +13 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[  +45 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[  +45 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[  +44 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[        ] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[   +1 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[   +3 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.
[   +8 ms] 
           Another exception was thrown: ScrollController not attached to any scroll views.

```

```
Analyzing issue...                                                      
No issues found! (ran in 1.4s)
```

```
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 22.04.1 LTS 5.15.0-46-generic, locale en_US.UTF-8)
    • Flutter version 3.0.5 at /home/guido/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/guido/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /snap/android-studio/123/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • motorola edge 20 pro (mobile) • ZY22DZ85NZ • android-arm64  • Android 12 (API 31)
    • Linux (desktop)               • linux      • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-46-generic
    • Chrome (web)                  • chrome     • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by gbarbieripederiva** [comment]
Hi @danagbemava-nc. Thank you very much ! Yes, it seems to be fixed in the latest version. I tried both with my example and the app i'm working on and neither show the error

**Comment by danagbemava-nc** [comment]
Thanks for confirming this. 

Closing as fixed.
