### ISSUE TITLE
 Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by sudikrt** [flutter/flutter#11051]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build flx --suppress-analytics --target /home/foolish-guy/project/lib/main.dart --output-file /home/foolish-guy/project/build/app/intermediates/flutter/debug/app.flx --snapshot /home/foolish-guy/project/build/app/intermediates/flutter/debug/snapshot_blob.bin --depfile /home/foolish-guy/project/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --working-dir /home/foolish-guy/project/build/app/intermediates/flutter/debug/flx

## exception

ProcessException: ProcessException: No such file or directory
  Command: /home/foolish-guy/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot --snapshot_kind=script --vm_snapshot_data=/home/foolish-guy/flutter/bin/cache/artifacts/engine/linux-x64/vm_isolate_snapshot.bin --isolate_snapshot_data=/home/foolish-guy/flutter/bin/cache/artifacts/engine/linux-x64/isolate_snapshot.bin --packages=/home/foolish-guy/project/.packages --script_snapshot=/home/foolish-guy/project/build/app/intermediates/flutter/debug/snapshot_blob.bin --dependencies=/home/foolish-guy/project/build/app/intermediates/flutter/debug/snapshot_blob.bin.d /home/foolish-guy/project/lib/main.dart

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:125)
<asynchronous suspension>
#1      createSnapshot (package:flutter_tools/src/flx.dart:58)
#2      build (package:flutter_tools/src/flx.dart:86)
<asynchronous suspension>
#3      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:44)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#5      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#6      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#10     new Future.sync (dart:async/future.dart:206)
#11     CommandRunner.run (package:args/command_runner.dart:109)
#12     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#13     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#14     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#15     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1467)
#19     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#20     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#22     main (file:///home/foolish-guy/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Linux, locale en_IN, channel alpha)
    • Flutter at /home/foolish-guy/flutter
    • Framework revision d36e2f6191 (8 days ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /home/foolish-guy/Android/Sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /home/foolish-guy/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/foolish-guy/Downloads/android-studio
    • Gradle version 4.0-rc-1
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Gradle (2.14.1)
    • gradle-dir = /home/foolish-guy/Downloads/android-studio/gradle/gradle-2.14.1/bin/gradle
    • Flutter supports building with Gradle from Android Studio.
      Consider removing your gradle-dir setting by running:
      flutter config --gradle-dir=

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Lenovo PB1 750M • 8f6fca88 • android-arm • Android 6.0.1 (API 23)

```

**Comment by eseidelGoogle** [comment]
`bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot` should exist on a linux system?

**Comment by goderbauer** [comment]
There is a failing flutter doctor check in your output:
```
✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)
```

You should be able to follow https://github.com/flutter/flutter/issues/6207#issuecomment-310912958 to fix that.

And we should probably also fail the top-level Flutter doctor check if this sub-check fails to make this more visible...

**Comment by lyrachord** [comment]
downloading engine and packages failed

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

SocketException: SocketException: OS Error: signal timeout...(translated)
, errno = 121, address = storage.googleapis.com, port = 65194

```
#0      fetchUrl (package:flutter_tools/src/base/net.dart:18)
<asynchronous suspension>
#1      _downloadFile (package:flutter_tools/src/cache.dart:400)
<asynchronous suspension>
#2      _downloadZipArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:407)
<asynchronous suspension>
#3      _withTemporaryFile (package:flutter_tools/src/cache.dart:428)
<asynchronous suspension>
#4      _downloadZipArchive (package:flutter_tools/src/cache.dart:406)
#5      FlutterEngine._downloadItem (package:flutter_tools/src/cache.dart:373)
#6      FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:348)
<asynchronous suspension>
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:223)
<asynchronous suspension>
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:196)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:206)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     new Future.sync (dart:async/future.dart:222)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#17     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1467)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#26     main (file:///D:/dart/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[-] Flutter (on Microsoft Windows [Version 10.0.15063], locale zh-CN, channel master)
    • Flutter at D:\dart\flutter
    • Framework revision 4da5e9b249 (3 days ago), 2017-08-04 17:44:20 -0700
    • Engine revision 73afec4081
    • Tools Dart version 1.25.0-dev.7.0
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at D:\android\SDK
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = D:\android\SDK
    • Java binary at: C:\work\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at C:\work\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[✓] Connected devices
    • None

```

**Comment by eseidelGoogle** [comment]
@lyrachord your issue looks different.  Looks like your computer is having trouble connecting to `storage.googleapis.com`.  I recommend filing a separate bug https://github.com/flutter/flutter/issues/new

**Comment by txthinking** [comment]
Should i fix this `✗ Downloaded executables cannot execute on host ` on MacOS, if then how?

```
[-] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/tx/flutter
    • Framework revision b156a0f054 (3 weeks ago), 2017-08-11 22:01:40 -0700
    • Engine revision fef7d827d6
    • Tools Dart version 1.25.0-dev.9.0
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /usr/local/opt/android-sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version openjdk version "1.8.0_112-release"

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version openjdk version "1.8.0_112-release"

[✓] Connected devices
    • None
```
thx.

**Comment by cbracken** [comment]
@txthinking is this still an issue?

**Comment by txthinking** [comment]
It looks like be fixed.

Clouds-MacBook-Pro:txthinking tx$ flutter doctor
[✓] Flutter (on Mac OS X 10.13.2 17C205, locale en-US, channel alpha)
    • Flutter at /Users/tx/flutter
    • Framework revision 8f65fec5f5 (5 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version
2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native
profiling support)
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-915-b08)

[-] Connected devices
    • None

**Comment by cbracken** [comment]
Thanks. Closing this specific issue. Sounds like the #6207 and its followup issue #12582 cover anything remaining.

**Comment by jojoberrah** [comment]
Oops; flutter has exited unexpectedly.
In the terminal type: xcode-select --install

**Comment by jjarral** [comment]
what to do in case of ubuntu 18? 
Here is also a fresh install of android studio and flutter. But flutter exits unexpectedly when I run flutter doctor --android-licenses or any command with flutter doctor. what to do now?
the path is also verified and correct.

**Comment by Hunter3173** [comment]
I had open the log created by flutter and I saw that in this file flutter didn't have permission to do somethings so I run sudo su on my Osx. But I think, it could be possible to add permissions to flutter installation. This solution works for me but I don't guarantee that it's work for you. Just try to run flutter in a root mode, to see if the problem comes from permissions

**Comment by uzairleo** [comment]
what should i do in case of windows 10 if i face the same issue OOPS FLUTTER HAS EXITED UNEXPECTEDLY
