### ISSUE TITLE
[windows] Key Events Not Working 

### ISSUE THREAD

**Issue by ashutosh2014** [flutter/flutter#110662]
## Steps to Reproduce

1.  App Code
```
import 'dart:io';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Focus(
        focusNode: FocusNode(),
        onKey: (_, __) {
          print("Key Pressed>> $_ $__");
          return KeyEventResult.ignored;
        },
        child: Listener(
          behavior: HitTestBehavior.translucent,
          onPointerSignal: (_) {
            print("pointerSignal>> $_");
          },
          onPointerHover: (_) {
            print("__>> $_");
          },
          onPointerPanZoomStart: (_) {
            print("onPointerPanZoomStart>> $_");
          },
          onPointerPanZoomUpdate: (_) {
            print("onPointerPanZoomUpdate>> $_");
          },
          onPointerPanZoomEnd: (_) {
            print("onPointerPanZoomEnd>> $_");
          },
          child: Center(
            // Center is a layout widget. It takes a single child and positions it
            // in the middle of the parent.
            child: Column(
              // Column is also a layout widget. It takes a list of children and
              // arranges them vertically. By default, it sizes itself to fit its
              // children horizontally, and tries to be as tall as its parent.
              //
              // Invoke "debug painting" (press "p" in the console, choose the
              // "Toggle Debug Paint" action from the Flutter Inspector in Android
              // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
              // to see the wireframe for each widget.
              //
              // Column has various properties to control how it sizes itself and
              // how it positions its children. Here we use mainAxisAlignment to
              // center the children vertically; the main axis here is the vertical
              // axis because Columns are vertical (the cross axis would be
              // horizontal).
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const Text(
                  'You have pushed the button this many times:',
                ),
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ],
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
**Now, flutter run -d windows**

flutter doctor -v
```

[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1889], locale en-IN)
    • Flutter version 3.3.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (35 hours ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\ashut\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32811.315
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\ashut\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
<details>
<summary> logs </summary>

```

__>> _TransformedPointerHoverEvent#f3e71(position: Offset(749.0, 74.0))
flutter: __>> _TransformedPointerHoverEvent#f617c(position: Offset(725.0, 107.0))
flutter: __>> _TransformedPointerHoverEvent#5764e(position: Offset(696.0, 124.0))
flutter: __>> _TransformedPointerHoverEvent#8bf21(position: Offset(663.0, 134.0))
flutter: __>> _TransformedPointerHoverEvent#7c506(position: Offset(630.0, 145.0))
flutter: __>> _TransformedPointerHoverEvent#701ce(position: Offset(606.0, 149.0))
flutter: __>> _TransformedPointerHoverEvent#ab9fe(position: Offset(598.0, 151.0))
flutter: __>> _TransformedPointerHoverEvent#910a4(position: Offset(597.0, 152.0))
flutter: __>> _TransformedPointerHoverEvent#4eb01(position: Offset(597.0, 155.0))
flutter: __>> _TransformedPointerHoverEvent#8c1d1(position: Offset(597.0, 163.0))
flutter: __>> _TransformedPointerHoverEvent#1b975(position: Offset(601.0, 173.0))
flutter: __>> _TransformedPointerHoverEvent#dd68e(position: Offset(607.0, 187.0))
flutter: __>> _TransformedPointerHoverEvent#231c4(position: Offset(610.0, 201.0))
flutter: __>> _TransformedPointerHoverEvent#6ac46(position: Offset(614.0, 214.0))
flutter: __>> _TransformedPointerHoverEvent#20837(position: Offset(614.0, 224.0))
flutter: __>> _TransformedPointerHoverEvent#22dcd(position: Offset(614.0, 233.0))
flutter: __>> _TransformedPointerHoverEvent#4f13d(position: Offset(612.0, 242.0))
flutter: __>> _TransformedPointerHoverEvent#71156(position: Offset(608.0, 251.0))
flutter: __>> _TransformedPointerHoverEvent#92564(position: Offset(602.0, 260.0))
flutter: __>> _TransformedPointerHoverEvent#e17d0(position: Offset(598.0, 264.0))
flutter: __>> _TransformedPointerHoverEvent#b0e6d(position: Offset(590.0, 272.0))
flutter: __>> _TransformedPointerHoverEvent#0aaaf(position: Offset(585.0, 279.0))
flutter: __>> _TransformedPointerHoverEvent#a6f7f(position: Offset(582.0, 285.0))
flutter: __>> _TransformedPointerHoverEvent#7e3bb(position: Offset(580.0, 290.0))
flutter: __>> _TransformedPointerHoverEvent#145e8(position: Offset(579.0, 294.0))
flutter: __>> _TransformedPointerHoverEvent#adc45(position: Offset(579.0, 298.0))
flutter: __>> _TransformedPointerHoverEvent#10fff(position: Offset(579.0, 299.0))
flutter: __>> _TransformedPointerHoverEvent#cbcb4(position: Offset(579.0, 300.0))
flutter: __>> _TransformedPointerHoverEvent#b56cf(position: Offset(579.0, 301.0))
flutter: __>> _TransformedPointerHoverEvent#d942b(position: Offset(581.0, 303.0))
flutter: __>> _TransformedPointerHoverEvent#83297(position: Offset(584.0, 303.0))
flutter: __>> _TransformedPointerHoverEvent#48c60(position: Offset(588.0, 303.0))
flutter: __>> _TransformedPointerHoverEvent#302d7(position: Offset(591.0, 305.0))
flutter: __>> _TransformedPointerHoverEvent#f372e(position: Offset(596.0, 305.0))
flutter: __>> _TransformedPointerHoverEvent#748d5(position: Offset(601.0, 306.0))
flutter: __>> _TransformedPointerHoverEvent#9c8ea(position: Offset(604.0, 308.0))
flutter: __>> _TransformedPointerHoverEvent#70723(position: Offset(606.0, 308.0))
flutter: __>> _TransformedPointerHoverEvent#7dcf2(position: Offset(608.0, 309.0))
flutter: __>> _TransformedPointerHoverEvent#0ea6c(position: Offset(609.0, 310.0))
flutter: __>> _TransformedPointerHoverEvent#d9665(position: Offset(609.0, 311.0))
flutter: __>> _TransformedPointerHoverEvent#06a45(position: Offset(611.0, 314.0))
flutter: __>> _TransformedPointerHoverEvent#16ed3(position: Offset(613.0, 316.0))
flutter: __>> _TransformedPointerHoverEvent#d7656(position: Offset(616.0, 317.0))
flutter: __>> _TransformedPointerHoverEvent#7f58b(position: Offset(621.0, 320.0))
flutter: __>> _TransformedPointerHoverEvent#9ae5c(position: Offset(625.0, 322.0))
flutter: __>> _TransformedPointerHoverEvent#3cd02(position: Offset(628.0, 322.0))
flutter: __>> _TransformedPointerHoverEvent#2c26a(position: Offset(630.0, 322.0))
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.

======== Exception caught by services library ======================================================
Unable to parse JSON message:
The document is empty.

 KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#d2858(physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left"), logicalKey: LogicalKeyboardKey#00100(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), character: null, timeStamp: 42:02:34.697007)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:881:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#8      _invoke2 (dart:ui/hooks.dart:186:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

```
</details>

**Comment by impure** [comment]
I'm having this issue too. Happened when I upgraded to 3.3. Apparently, someone posted about it here: https://stackoverflow.com/questions/73469047/flutter-desktop-on-long-press-returns-error-windows
It happens when you hold down Ctrl, Alt, or Shift.

**Comment by darshankawar** [comment]
@ashutosh2014 @impure 
I believe this is same issue as https://github.com/flutter/flutter/issues/108646 which was fixed and merged to Master branch. https://github.com/flutter/flutter/issues/108646#issuecomment-1200947402, I am not sure if the fix made it to stable because the cherry-pick request was closed without being completed, so the issue could still be in stable version.

I suggest you both to switch to latest master and try again to see if you still get same error or not.

`flutter channel master`
`flutter upgrade`

**Comment by ashutosh2014** [comment]
Hi @darshankawar, thanks for sharing theses cherrypick commits.
For repeat Keys, it is fixed in master, but I'm trying to pinch-zoom from trackpad it is crashing.
```


======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#ccc70(physicalKey: PhysicalKeyboardKey#00000(usbHidUsage: "0x1600000000", debugName: "Key with ID 0x1600000000"), logicalKey: LogicalKeyboardKey#00100(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), character: null, timeStamp: 16:55:20.187883)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:954:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#8      _invoke2 (dart:ui/hooks.dart:183:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:610:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 2 frames from class _AssertionError)
```

**Comment by darshankawar** [comment]
Thanks for checking and confirming the original use case.



> pinch-zoom from trackpad it is crashing.

I believe you are hitting https://github.com/flutter/flutter/issues/95496#issuecomment-1013891281, so please follow-up in that issue for further updates.
If you are okay with that, you can close this issue as your original report is fixed on master.

```
Unable to parse JSON message:
The document is empty.
```
