### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by loqmanali** [flutter/flutter#110668]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-SA)
    • Flutter version 3.0.5 at /Users/loqmanelgrahysmart/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/loqmanelgrahysmart/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
firebase_analytics-9.3.3
firebase_analytics_web-0.4.2+3
firebase_auth-3.7.0
firebase_auth_web-4.3.0
firebase_core-1.21.1
firebase_core_web-1.7.2
firebase_crashlytics-2.8.9
firebase_database-9.1.3
firebase_database_web-0.2.1+5
firebase_messaging-13.0.0
firebase_messaging_web-3.1.3
firebase_performance-0.8.2+4
firebase_performance_web-0.1.1+4
firebase_remote_config-2.0.16
firebase_remote_config_web-1.1.4
firebase_storage-10.3.7
firebase_storage_web-3.3.5
path_provider_linux-2.1.7
path_provider_windows-2.1.2
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1

**Comment by darshankawar** [comment]
@loqmanali 
A similar issue was fixed and pushed to master https://github.com/flutter/flutter/issues/95916 
Can you switch to latest master and run the command again to see if you still get same tool crash or not ?

`flutter channel master`
`flutter upgrade`

**Comment by loqmanali** [comment]
problem solved 
flutter clean
flutter pub get

**Comment by darshankawar** [comment]
Good to know. Closing as resolved.
