### ISSUE TITLE
Host lookup fails on Android with flutter 3.3.0

### ISSUE THREAD

**Issue by felix-barz-brickmakers** [flutter/flutter#110752]
When building an Android app with flutter 3.3.0, in release mode, host lookup is broken and will throw an exception. In debug mode, it works fine.

## Steps to Reproduce
1. Create a new flutter project (`flutter create bugreport`)
2. Run `flutter pub add http`
3. Replace the `main` with the following:
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final response = await get(Uri.parse('https://google.de'));
  print(response.statusCode);

  runApp(const MyApp());
}
```
4. Execute `flutter run`: App starts normally and prints "200"
5. Execure `flutter run --release`: App gets stuck on splashscreen and prints a "Failed host lookup: 'google.de'" exception

**Expected results:**
App starts normally and prints "200"

**Actual results:**
App gets stuck on splashscreen and prints exception:
```
E/flutter (21945): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Failed host lookup: 'google.de'
E/flutter (21945): #0      IOClient.send (package:http/src/io_client.dart:88)
E/flutter (21945): <asynchronous suspension>
E/flutter (21945): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
E/flutter (21945): <asynchronous suspension>
E/flutter (21945): #2      _withClient (package:http/http.dart:164)
E/flutter (21945): <asynchronous suspension>
E/flutter (21945): #3      main (package:bugreport/main.dart:7)
E/flutter (21945): <asynchronous suspension>
E/flutter (21945): 
```

This happens on the emulator as well as on real devices. It does not matter which host you try, it fails for all of them.

<details>
<summary>Code sample</summary>
See description of the issue. I simply created an empty flutter project, added the http package and sent a request. The code that throws the error is simply the HTTP request, trying to be resolved

```dart
final response = await get(Uri.parse('https://google.de'));
print(response.statusCode);
```

</details>

<details>
  <summary>Logs</summary>
flutter run

[flutter_run_verbose.txt](https://github.com/flutter/flutter/files/9467380/flutter_run_verbose.txt)

flutter analyze
```
Analyzing bugreport...                                               

   info • Avoid `print` calls in production code • lib/main.dart:8:3 • avoid_print

1 issue found. (ran in 2.7s)
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-x64, locale de-DE)
    • Flutter version 3.3.0 on channel stable at /Users/felix.barz/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (2 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/felix.barz/sdk/android
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/felix.barz/sdk/android
    • ANDROID_SDK_ROOT = /Users/felix.barz/sdk/android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 105.0.5195.52

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by felix-barz-brickmakers** [comment]
I did forget to add it to the minimal example where I tried to reproduce the issue, which is why it failed there. So adding it did help here.

However, in the original application where I had the issue the internet permission was already added, so this was not the cause here. However, a simple "delete all caches and build files" did actually solve the problem here as well! So sorry for creating an issue for nothing and thank you for your quick reply and the helpful hint!
