### ISSUE TITLE
[tool_crash] ProcessException: Bad CPU type in executable Command: /Users/gonzalodiascenzi/Desktop/flutter/bin/cache/artifacts/engine/darwin-x64/impellerc, OS error code: 86

### ISSUE THREAD

**Issue by DIASG009** [flutter/flutter#110792]
## Command
```
flutter run -d web-server
```

## Steps to Reproduce
1. Upgrade flutter with flutter upgrade to version 3.3
2. Go to the directory of your proyect that have main.dart
3. Execute flutter run -d web-server 

## Logs
ProcessException: Bad CPU type in executable Command: /Users/gonzalodiascenzi/Desktop/flutter/bin/cache/artifacts/engine/darwin-x64/impellerc, OS error code: 86
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:72:60)
#7      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:184:46)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#9      writeBundle (package:flutter_tools/src/bundle_builder.dart:162:3)
<asynchronous suspension>
#10     WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:843:9)
<asynchronous suspension>
#11     ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:488:35)
<asynchronous suspension>
#12     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#13     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-arm, locale es-419)
    • Flutter version 3.3.0 on channel stable at /Users/gonzalodiascenzi/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/gonzalodiascenzi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 105.0.5195.52

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadat

**Comment by darshankawar** [comment]
@DIASG009 
This seems to be fixed and merged into master as part of this issue: https://github.com/flutter/flutter/issues/109892.
I suggest you to switch to latest master and try the steps to replicate and confirm if you still see the crash or not.

`flutter channel master`
`flutter upgrade`
