### ISSUE TITLE
Cannot build new application

### ISSUE THREAD

**Issue by Dohxis** [flutter/flutter#11076]
## Steps to Reproduce
I just created a new project, added some plugins and now I cannot build my project. Running everything from a terminal(running from WebStorm gives same results). Those are the plugins I installed:
```
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.0.2
  google_sign_in: ^0.2.1
  firebase_analytics: ^0.0.2
  firebase_auth: ^0.1.0
  firebase_database: ^0.0.4
  firebase_storage: ^0.0.2
```

## Logs
**flutter run**
```
Launching lib/main.dart on LG H500 in debug mode...
FAILURE: Build failed with an exception.

* Where:
Build file '/home/domas/Development/Prakalbk/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':app:_debugApk'.
         > A problem occurred configuring project ':firebase_analytics'.
            > Could not resolve all dependencies for configuration ':firebase_analytics:_debugPublishCopy'.
               > Could not find com.google.firebase:firebase-auth:11.0.1.
                 Required by:
                     project :firebase_analytics
               > Could not find com.google.firebase:firebase-analytics:11.0.1.
                 Required by:
                     project :firebase_analytics
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: /home/domas/AndroidStudio/gradle/gradle-3.2/bin/gradle app:properties
Running 'gradle assembleDebug'...                         

FAILURE: Build failed with an exception.

* Where:
Build file '/home/domas/Development/Prakalbk/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':app:_debugApk'.
         > A problem occurred configuring project ':firebase_analytics'.
            > Could not resolve all dependencies for configuration ':firebase_analytics:_debugPublishCopy'.
               > Could not find com.google.firebase:firebase-auth:11.0.1.
                 Required by:
                     project :firebase_analytics
               > Could not find com.google.firebase:firebase-analytics:11.0.1.
                 Required by:
                     project :firebase_analytics
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```
**flutter build -v apk** 
```
[      +32 ms] [/home/domas/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[      +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[            ] origin/alpha
[            ] [/home/domas/flutter/] git ls-remote --get-url origin
[       +5 ms] Exit code 0 from: git ls-remote --get-url origin
[            ] https://github.com/flutter/flutter.git
[            ] [/home/domas/flutter/] git log -n 1 --pretty=format:%H
[       +6 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[            ] 3b6d84b083956df5652b2fe34c68287579e9b73d
[            ] [/home/domas/flutter/] git log -n 1 --pretty=format:%ar
[       +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[            ] 2 weeks ago
[     +213 ms] Found plugin firebase_analytics at /home/domas/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-0.0.3/
[       +3 ms] Found plugin firebase_auth at /home/domas/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.1.0/
[       +3 ms] Found plugin firebase_database at /home/domas/.pub-cache/hosted/pub.dartlang.org/firebase_database-0.0.11/
[       +2 ms] Found plugin firebase_storage at /home/domas/.pub-cache/hosted/pub.dartlang.org/firebase_storage-0.0.4/
[       +6 ms] Found plugin google_sign_in at /home/domas/.pub-cache/hosted/pub.dartlang.org/google_sign_in-0.2.1/
[       +7 ms] Found plugin image_picker at /home/domas/.pub-cache/hosted/pub.dartlang.org/image_picker-0.0.3/
[     +153 ms] Using gradle from /home/domas/AndroidStudio/gradle/gradle-3.2/bin/gradle.
[       +6 ms] Running 'gradle assembleRelease'...
[       +2 ms] [android/] /home/domas/AndroidStudio/gradle/gradle-3.2/bin/gradle -Ptarget=lib/main.dart assembleRelease
[    +1526 ms] google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
[       +1 ms] please apply google-services plugin at the bottom of the build file.
[    +7271 ms] FAILURE: Build failed with an exception.
[       +1 ms] * Where:
[            ] Build file '/home/domas/Development/Prakalbk/android/build.gradle' line: 27
[            ] * What went wrong:
[            ] A problem occurred evaluating root project 'android'.
[            ] > A problem occurred configuring project ':app'.
[            ]    > Failed to notify project evaluation listener.
[            ]       > Could not resolve all dependencies for configuration ':app:_debugApk'.
[            ]          > A problem occurred configuring project ':firebase_analytics'.
[            ]             > Could not resolve all dependencies for configuration ':firebase_analytics:_debugPublishCopy'.
[            ]                > Could not find com.google.firebase:firebase-auth:11.0.1.
[            ]                  Required by:
[            ]                      project :firebase_analytics
[            ]                > Could not find com.google.firebase:firebase-analytics:11.0.1.
[            ]                  Required by:
[            ]                      project :firebase_analytics
[            ]       > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.
[            ] * Try:
[            ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[       +4 ms] BUILD FAILED
[            ] Total time: 8.724 secs
[     +479 ms] "flutter apk" took 9,630ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:244)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:192)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/commands/build_apk.dart:83)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:55)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#6      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#7      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#11     new Future.sync (dart:async/future.dart:206)
#12     CommandRunner.run (package:args/command_runner.dart:109)
#13     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#14     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     runZoned (dart:async/zone.dart:1467)
#20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#21     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#23     main (file:///home/domas/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[     +259 ms] ensureAnalyticsSent: 252ms
[       +1 ms] exiting with code 1
```

## Flutter Doctor
```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/domas/flutter
    • Framework revision 3b6d84b083 (2 weeks ago), 2017-06-16 12:58:23 -0700
    • Engine revision 784e975672
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/domas/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /home/domas/Android/Sdk
    • Java binary at: /home/domas/AndroidStudio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/domas/AndroidStudio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] WebStorm (version 2017.1)
    • Flutter plugin version 14.0

[✓] Connected devices
    • LG H500 • JNN7DQJRNJAM4PWK • android-arm • Android 6.0 (API 23)
```

**Comment by olostan** [comment]
Can it be related to https://github.com/flutter/flutter/issues/10962 ?

For me updating "pusbec.yaml file with google_sign_in: ^0.2.1 and firebase_auth: ^0.1.0" helped

**Comment by mit-mit** [comment]
Sorry to hear @Dohxis. Can you try to edit your `android/build.gradle` file to contain a reference to the jitpack.io repo, like this:

<pre>
allprojects {
   repositories {
       jcenter()
<b>       maven { url "https://jitpack.io" }    // Enable getting dependencies from jitpack.io. </b>
   }
}
</pre>

**Comment by sudikrt** [comment]
Try by adding following in your build.gradle in android folder 

allprojects {
   repositories {
       jcenter()
       maven {
            url "https://maven.google.com"
       }
   }
}

**Comment by mayinhosa** [comment]
I'm getting the same error from `flutter run` 

I already have the jitpack repository in my `android/build.gradle`, and tried the `maven.google.com` one for good measure but I get the same error.

All on a fresh install of *everything*

**Comment by sudikrt** [comment]
can you post the error

**Comment by mayinhosa** [comment]
I did manage to fix by updating `Google Repository` under `Support Repository` in SDK Tools to the latest version (v.55 at time of writing).

**Comment by PGMacDesign** [comment]
Still having this issue myself within Android Studio. Whenever I try to create a new application, this error is posted:
java.io.FileNotFoundException: D:/Flutter_Workspace_2018-02-27/FirstFlutterApp/.idea
	at com.intellij.openapi.util.io.FileUtil.isFileSystemCaseSensitive(FileUtil.java:1708)
	at com.intellij.ide.startup.impl.StartupManagerImpl.checkFsSanity(StartupManagerImpl.java:251)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:172)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$6(ProjectManagerImpl.java:375)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Despite the file actually being in that exact spot.

**Comment by Hixie** [comment]
I'm going to close this since @Dohxis did not provide any follow-up information. @Dohxis if you still see this please don't hesitate to file a new bug, and we'll try to help.

@PGMacDesign if you are still seeing this please don't hesitate to file a new bug and we'll track your specific issue separately. Thanks.

**Comment by Anish110910** [comment]
Hey everyone I have also faced this issue
Can anyone explain?

**Comment by zoechi** [comment]
@Anish110910 probably better to create a new issue with full information (and perhaps a link to this issue).

**Comment by muhammednazil** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/qlinksoftware/Documents/FlutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.4+1/android/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'firebase_auth'.
> Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s


Exception: The plugin firebase_auth could not be built due to the issue above.


did any can help me
