### ISSUE TITLE
[tool_crash] YamlException

### ISSUE THREAD

**Issue by DanielLimaFN** [flutter/flutter#110815]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=0063227560 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
YamlException
```
#0      Scanner._fetchValue (package:yaml/src/scanner.dart:723:9)
#1      Scanner._fetchNextToken (package:yaml/src/scanner.dart:465:11)
#2      Scanner._fetchMoreTokens (package:yaml/src/scanner.dart:347:7)
#3      Scanner.peek (package:yaml/src/scanner.dart:325:27)
#4      Parser._parseDocumentEnd (package:yaml/src/parser.dart:221:26)
#5      Parser._stateMachine (package:yaml/src/parser.dart:73:16)
#6      Parser.parse (package:yaml/src/parser.dart:56:19)
#7      Loader._loadDocument (package:yaml/src/loader.dart:67:29)
#8      Loader.load (package:yaml/src/loader.dart:57:20)
#9      loadYamlDocument (package:yaml/yaml.dart:69:25)
#10     loadYamlNode (package:yaml/yaml.dart:54:5)
#11     generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:31:29)
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1318:13)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
```
```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [versÆo 10.0.22622.586], locale pt-BR)
    • Flutter version 3.0.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\danie\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\danie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • motorola one hyper (mobile) • 0063227560 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)           • windows    • windows-x64    • Microsoft Windows [versÆo 10.0.22622.586]
    • Chrome (web)                • chrome     • web-javascript • Google Chrome 105.0.5195.53
    • Edge (web)                  • edge       • web-javascript • Microsoft Edge 104.0.1293.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.1+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
bs_flutter_selectbox-1.3.0
bs_flutter_utils-1.0.2
camera-0.9.8+1
camera_android-0.9.8+3
camera_avfoundation-0.9.8+2
camera_web-0.2.1+6
flutter_barcode_scanner-2.0.0
flutter_native_splash-2.2.3+1
flutter_plugin_android_lifecycle-2.0.6
path_provider_linux-2.1.7
path_provider_windows-2.1.2
permission_handler-10.0.0
permission_handler_android-10.0.0
permission_handler_apple-9.0.4
permission_handler_windows-0.1.0
qr_code_scanner-1.0.0
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1

**Comment by darshankawar** [comment]
Labeling this issue based on the report. Although there were similar issues reported earlier, but were closed due to inactivity and I don't see a similar issue with stack trace open.

/cc @christopherfujino

**Comment by andrewkolos** [comment]
From the stack trace, we can see this happened in `generateLocalizationsSyntheticPackage`. However, debugging this would be difficult to be debug without the original YAML that produced this crash.

@DanielLimaFN if you can still produce this crash, posting the YAML in question would be helpful. For the meantime, I'll be closing this issue since it is stale and not reproducible with current knowledge.
