### ISSUE TITLE
firebase_database plugin tests fail on linux

### ISSUE THREAD

**Issue by kroikie** [flutter/flutter#11097]
## Steps to Reproduce
1. On Linux machine clone flutter/plugins repo
2. In the firebase_database directory run `flutter test`
3. Test fails with:

```
plugins/packages/firebase_database/test/firebase_database_test.dart': error: line 46 pos 76: non-const constructor 'MethodCall' cannot be used in const object creation
            const MethodCall('FirebaseDatabase#setPersistenceEnabled', false),
                                                                             ^
  
  package:test         serializeSuite
  listener.dart 17:27  main
  
[     +149 ms] test 0: process with pid 36197 no longer needed by test harness
[            ] test 0: cleaning up...
00:00 +0 -1: Some tests failed.                                                                    
[       +4 ms] test 0: shutting down test harness socket server
[      +13 ms] test package returned with exit code 1
[      +13 ms] "flutter test" took 643ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:230)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#3      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      new Future.sync (dart:async/future.dart:206)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#10     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     runZoned (dart:async/zone.dart:1467)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#19     main (file:///<HOME_DIR>/opt/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[       +6 ms] test 0: deleting temporary directory
[            ] test 0: ensuring end-of-process for shell
[       +6 ms] test 0: finished
[      +30 ms] ensureAnalyticsSent: 39ms
[       +1 ms] exiting with code 1
```
## flutter doctor output
```
flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /usr/local/google/home/arthurthompson/opt/flutter
    • Framework revision e2f54df5ab (5 weeks ago), 2017-06-02 10:43:54 -0700
    • Engine revision 1f2aa07571
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /usr/local/google/home/arthurthompson/opt/android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /usr/local/google/home/arthurthompson/opt/android/sdk
    • Java binary at: /usr/local/google/home/arthurthompson/opt/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 3.0)
    • Android Studio at /usr/local/google/home/arthurthompson/opt/android-studio
    • Gradle version 4.0-rc-1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.2)
    • Android Studio at /opt/android-studio-2.2
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Android Studio (version 2.4)
    • Android Studio at /opt/android-studio-2.4
    • Gradle version 3.4.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-2.3
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 15.0

[-] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] IntelliJ IDEA Ultimate Edition (version 2016.2)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] IntelliJ IDEA Ultimate Edition (version 2016.1)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

Device HT7360200657 is not authorized.
You might need to check your device for an authorization dialog.
[✓] Connected devices
    • None
```

**Comment by goderbauer** [comment]
Your Flutter version is pretty old. Can you run `flutter upgrade` and try again?

**Comment by kroikie** [comment]
That did it, thanks!
