### ISSUE TITLE
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter...

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#110950]
```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#f6fd2(physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left"), logicalKey: LogicalKeyboardKey#00100(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), character: null, timeStamp: 356:30:23.304155)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:881:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#8      _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#12     _invoke2 (dart:ui/hooks.dart:188:10)
#13     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#14     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#15     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#16     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#17     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```

**Flutter version: 3.3.0 from stable channel, platform: windows**
![studio64_zKcfR8Jcmg](https://user-images.githubusercontent.com/63228361/188330500-a14cef34-bb9c-454f-9763-86d71508e106.gif)
Steps to reproduce: create an app, launch it, minimize it, press(and hold) ctrl+alt(on the left keyboard's side) and maximize the app from the taskbar without releasing the buttons. (This is the easiest way to reproduce the issue. Another way to reproduce the problem is: you'll have click numlock+capslock very very very fast and simultaneously but it's hard to repeat so use the first method).

**Comment by guchengxi1994** [comment]
I hava another bug here. I was using vscode writing flutter codes. After upgrade flutter to 3.3.0, every time I use "Control Left" to click into codes in vscode, raising this error:
```
Another exception was thrown: A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please
report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`.   
This was the event: KeyRepeatEvent#fd187(physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left"), logicalKey:
LogicalKeyboardKey#00100(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), character: null, timeStamp: 2:54:57.346350)
```
![20220905](https://user-images.githubusercontent.com/33513462/188357311-d79f70ec-0205-4af2-8b38-95ac93eb91ab.gif)

**Comment by kirill-21** [comment]
> I hava another bug here. I was using vscode writing flutter codes. After upgrade flutter to 3.3.0, every time I use "Control Left" to click into codes in vscode, raising this error:
> 
> ```
> Another exception was thrown: A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please
> report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`.   
> This was the event: KeyRepeatEvent#fd187(physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left"), logicalKey:
> LogicalKeyboardKey#00100(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), character: null, timeStamp: 2:54:57.346350)
> ```
> 
> ![20220905](https://user-images.githubusercontent.com/33513462/188357311-d79f70ec-0205-4af2-8b38-95ac93eb91ab.gif) [ ![20220905](https://user-images.githubusercontent.com/33513462/188357311-d79f70ec-0205-4af2-8b38-95ac93eb91ab.gif) ](https://user-images.githubusercontent.com/33513462/188357311-d79f70ec-0205-4af2-8b38-95ac93eb91ab.gif) [ ](https://user-images.githubusercontent.com/33513462/188357311-d79f70ec-0205-4af2-8b38-95ac93eb91ab.gif)

I found my issue in flutter 2.0.3 but did not know how to recreate it)

**Comment by kirill-21** [comment]
```dart
Syncing files to device Windows...
[DartError] 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 435 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey': A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#ff421(physicalKey: PhysicalKeyboardKey#70053(usbHidUsage: "0x00070053", debugName: "Num Lock"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x100000104", keyLabel: "Caps Lock", debugName: "Caps Lock"), character: null, timeStamp: 377:00:30.990538, synthesized) and the recorded logical key LogicalKeyboardKey#0010a(keyId: "0x10000010a", keyLabel: "Num Lock", debugName: "Num Lock"); #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:435:16)#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)#5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:881:29)#6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:412:41)#7      _invoke1 (dart:ui/hooks.dart:164:13)#8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:410:7)#9      _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)#10     _rootRun (dart:async/zone.dart:1398:13)#11     _CustomZone.run (dart:async/zone.dart:1300:19)#12     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)#13     _invoke2 (dart:ui/hooks.dart:185:10)#14     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)#15     _Channel.push (dart:ui/channel_buffers.dart:130:31)#16     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)#17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:610:22)#18     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
[DartError] 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 428 pos 16: '!_pressedKeys.containsKey(event.physicalKey)': A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#686ac(physicalKey: PhysicalKeyboardKey#70053(usbHidUsage: "0x00070053", debugName: "Num Lock"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x100000104", keyLabel: "Caps Lock", debugName: "Caps Lock"), character: null, timeStamp: 377:00:30.990544, synthesized); #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:428:16)#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)#5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:881:29)#6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:412:41)#7      _invoke1 (dart:ui/hooks.dart:164:13)#8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:410:7)#9      _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)#10     _rootRun (dart:async/zone.dart:1398:13)#11     _CustomZone.run (dart:async/zone.dart:1300:19)#12     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)#13     _invoke2 (dart:ui/hooks.dart:185:10)#14     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)#15     _Channel.push (dart:ui/channel_buffers.dart:130:31)#16     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)#17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:610:22)#18     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
[DartError] 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 435 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey': A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#b6b4b(physicalKey: PhysicalKeyboardKey#70053(usbHidUsage: "0x00070053", debugName: "Num Lock"), logicalKey: LogicalKeyboardKey#0010c(keyId: "0x10000010c", keyLabel: "Scroll Lock", debugName: "Scroll Lock"), character: null, timeStamp: 377:00:30.990547, synthesized) and the recorded logical key LogicalKeyboardKey#0010a(keyId: "0x10000010a", keyLabel: "Num Lock", debugName: "Num Lock"); #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:435:16)#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)#5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:881:29)#6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:412:41)#7      _invoke1 (dart:ui/hooks.dart:164:13)#8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:410:7)#9      _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)#10     _rootRun (dart:async/zone.dart:1398:13)#11     _CustomZone.run (dart:async/zone.dart:1300:19)#12     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)#13     _invoke2 (dart:ui/hooks.dart:185:10)#14     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)#15     _Channel.push (dart:ui/channel_buffers.dart:130:31)#16     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)#17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:610:22)#18     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
[DartError] 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 428 pos 16: '!_pressedKeys.containsKey(event.physicalKey)': A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#d09a7(physicalKey: PhysicalKeyboardKey#70053(usbHidUsage: "0x00070053", debugName: "Num Lock"), logicalKey: LogicalKeyboardKey#0010c(keyId: "0x10000010c", keyLabel: "Scroll Lock", debugName: "Scroll Lock"), character: null, timeStamp: 377:00:30.990548, synthesized); #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:428:16)#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)#5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:881:29)#6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:412:41)#7      _invoke1 (dart:ui/hooks.dart:164:13)#8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:410:7)#9      _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)#10     _rootRun (dart:async/zone.dart:1398:13)#11     _CustomZone.run (dart:async/zone.dart:1300:19)#12     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)#13     _invoke2 (dart:ui/hooks.dart:185:10)#14     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)#15     _Channel.push (dart:ui/channel_buffers.dart:130:31)#16     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)#17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:610:22)#18     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
Unable to parse JSON message:
The document is empty.

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#b5f14(logicalKey: LogicalKeyboardKey#00104(keyId: "0x100000104", keyLabel: "Caps Lock", debugName: "Caps Lock"), physicalKey: PhysicalKeyboardKey#70053(usbHidUsage: "0x00070053", debugName: "Num Lock"), repeat: false) and its data: RawKeyEventDataWindows#3d7e1(keyCode: 20, scanCode: 57413, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 683 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:683:7)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:951:30)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)
#10     _invoke2 (dart:ui/hooks.dart:185:10)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:610:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.
[DartError] 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 435 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey': A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#c98a8(physicalKey: PhysicalKeyboardKey#70053(usbHidUsage: "0x00070053", debugName: "Num Lock"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x100000104", keyLabel: "Caps Lock", debugName: "Caps Lock"), character: null, timeStamp: 377:00:31.030940, synthesized) and the recorded logical key LogicalKeyboardKey#0010c(keyId: "0x10000010c", keyLabel: "Scroll Lock", debugName: "Scroll Lock"); #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:435:16)#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)#5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:881:29)#6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:412:41)#7      _invoke1 (dart:ui/hooks.dart:164:13)#8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:410:7)#9      _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)#10     _rootRun (dart:async/zone.dart:1398:13)#11     _CustomZone.run (dart:async/zone.dart:1300:19)#12     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)#13     _invoke2 (dart:ui/hooks.dart:185:10)#14     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)#15     _Channel.push (dart:ui/channel_buffers.dart:130:31)#16     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)#17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:610:22)#18     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)

======== Exception caught by services library ======================================================
```

**Comment by greggameplayer** [comment]
I'm getting the same error on flutter 3.3.0 : 
![image](https://user-images.githubusercontent.com/33609333/188522793-fd17c2c1-7844-43fd-b1ed-6649e1f012b2.png)
![image](https://user-images.githubusercontent.com/33609333/188522811-9c1d3d42-21b0-4cd6-be40-c527ef868b69.png)

**Comment by greggameplayer** [comment]
here is a `flutter doctor -v` for info : 
![image](https://user-images.githubusercontent.com/33609333/188522968-4d58a5ef-a5ec-4959-9e80-17804068d6a8.png)

**Comment by huycozy** [comment]
Hi @kirill-21 
>YEs, i can reproduce it on master channel but with insert+numlock keys

From your response and the logs at https://github.com/flutter/flutter/issues/110950#issuecomment-1237246690, I see there's an open issue addressing the case you described #94502. Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

@greggameplayer I believe you are hitting #106475, so please follow up on that issue for further updates. Next time, please provide information in text format for better readability. Thank you!
