### ISSUE TITLE
Flutter 3.3.0 Fatal Exception: java.lang.AssertionError: Unexpected masked action

### ISSUE THREAD

**Issue by meomap** [flutter/flutter#111068]
## Steps to Reproduce

I've got fatal errors after upgrading to Flutter 3.3.0 that affect multiple devices running in production.

From what I've seen, it seems only tablet (maybe with a Stylus Pen) are affected.

Devices:
- Galaxy Tab S6 (Lite) (Android 11, 12)
- Galaxy Tab S7 (FE) (11, 12)
- Galaxy Tab A with S Pen (11)

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
Fatal Exception: java.lang.AssertionError: Unexpected masked action
       at io.flutter.embedding.android.AndroidTouchProcessor.getPointerChangeForAction(AndroidTouchProcessor.java:384)
       at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:124)
       at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:104)
       at io.flutter.embedding.android.FlutterView.onTouchEvent(FlutterView.java:940)
       at android.view.View.dispatchTouchEvent(View.java:15076)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3917)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3581)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1015)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4265)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:973)
       at android.view.View.dispatchPointerEvent(View.java:15335)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7794)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7567)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6901)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7122)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7179)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10354)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10202)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10158)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10486)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 11.6.8 20G730 darwin-x64, locale en-VN)
    • Flutter version 3.3.0 on channel stable at /Users/meomap/code/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (8 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @meomap
Is this issue reproducible locally? If so, can you please share the output of `flutter run -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? 
I have a tablet device that can help to reproduce this: `Samsung Galaxy Tab A7 Lite Android 12 OneUI 4.1, SM-T225` (it has no SPen)
Thanks!

**Comment by meomap** [comment]
Hi @huycozy
Unfortunately, I don't have the appropriate devices to reproduce the problem locally yet :(

I would be very grateful if you could try to run sample code in your device 🙏

Here's a minimal sample code

```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          child: Navigator(
        onGenerateRoute: (settings) => PageRouteBuilder(
            settings: settings,
            opaque: false,
            pageBuilder: (context, animation, secondaryAnimation) {
              return InteractiveViewer(
                child: CustomGestureDetector(
                    child: Container(
                        color: Colors.red,
                        child: const Center(
                            child: Text('Tap any where, or Pan, or Zoom')))),
              );
            }),
      )),
    );
  }
}

class CustomGestureDetector extends StatelessWidget {
  const CustomGestureDetector({super.key, required this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return RawGestureDetector(
      behavior: HitTestBehavior.opaque,
      gestures: {
        _DragGestureDetector:
            GestureRecognizerFactoryWithHandlers<_DragGestureDetector>(
          () => _DragGestureDetector(),
          (_) {},
        ),
      },
      child: child,
    );
  }
}

class _DragGestureDetector extends OneSequenceGestureRecognizer {
  _DragGestureDetector() : super();

  @override
  void addPointer(PointerEvent event) {
    print('** addPointer $event **');
  }

  @override
  void didStopTrackingLastPointer(int pointer) {
    print('** onGestureEnd $pointer **');
  }

  @override
  void handleEvent(PointerEvent event) {
    print('** handleEvent $event **');
  }

  @override
  String get debugDescription => '_DragGestureDetector';
}

```

**Comment by huycozy** [comment]
Hi @meomap, thanks for providing a sample code, but I can not reproduce this issue (please see the demo). Maybe it only happens on devices with SPen or specific device model like above in https://github.com/flutter/flutter/issues/111068#issue-1364149657.
I also tried running sample code in `release` mode, but the result is still the same as `debug` mode.

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/189023222-59cddf26-a7e7-42b1-b662-1eff014c03cb.mp4


</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5 21G72 darwin-x64, locale en-VN)
    • Flutter version 3.3.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (26 hours ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.136, on macOS 12.5 21G72 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.136 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 165cb0b986 (5 minutes ago), 2022-09-08 08:11:31 +0530
    • Engine revision 24babd254b
    • Dart version 2.19.0 (build 2.19.0-177.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Could you please confirm that the issue is only happening in the new flutter stable version `3.3.0`? And which version did you use before?

**Comment by meomap** [comment]
@huycozy Thank you so much for your help!

I confirm that the issue is only happening in new flutter stable version `3.3.0`. Before that my flutter version is `3.0.5`. 

It occurs only on Samsung tablets. Current fatal rate is once or twice per session. I think it's a un-normal interaction that triggers this, maybe a SPen button.

**Comment by huycozy** [comment]
@meomap thank you for the confirmation. Labeling this issue for further investigation/insight from the team.

**Comment by FusoraTech** [comment]
Maybe the hardware is signaling an ACTION_BUTTON that could be read by getActionMasked() and as such value is not mapped at getPointerChangeForAction(int maskedAction) it fires the assertion in engine/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java

**Comment by FusoraTech** [comment]
Also maybe related to this 2019 still open case https://github.com/flutter/flutter/issues/42846

**Comment by chinmaygarde** [comment]
cc @stuartmorgan Perhaps we should have an assertion thrown for unexpected actions? If OEMs can add to this, discarding the events might be better? Not sure.

**Comment by FusoraTech** [comment]
In my opinion, native support for Apple Pencil and Samsung Pen should be studied (people would love if implemented), unknown events from unknown hardware should be ignored in release versions and asserted in debug versions. Currently it seems asserted and not implemented and is breaking apps in the presence of the pen.

For Samsung studies: 
https://developer.samsung.com/galaxy-spen-remote/overview.html
https://developer.samsung.com/galaxy-spen-remote/api-reference/constant-values.html

For Apple studies:
https://developer.apple.com/documentation/uikit/pencil_interactions/

**Comment by adil192** [comment]
I'm having the same error but it occurs whenever I press the screen with the S Pen's button pressed.

Device: Samsung Galaxy Tab S7, Android 12


```Python
[✓] Flutter (Channel stable, 3.3.2, on Pop!_OS 22.04 LTS 5.19.0-76051900-generic, locale en_GB.UTF-8)
    • Flutter version 3.3.2 on channel stable at /home/adil/Documents/Sources/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (10 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/adil/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/adil/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/adil/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM T870 (mobile) • R52N91CRFYX • android-arm64  • Android 12 (API 31)
    • Linux (desktop)  • linux       • linux-x64      • Pop!_OS 22.04 LTS 5.19.0-76051900-generic
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

<details>
<summary>
java.lang.AssertionError: Unexpected masked action
</summary>

```Java
D/ViewRootImpl@26148ea[MainActivity](27820): reportDrawFinished (fn: 1) 
I/ViewRootImpl@26148ea[MainActivity](27820): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(27820): startInputInner - Id : 0
I/InputMethodManager(27820): startInputInner - mService.startInputOrWindowGainedFocus
D/InputMethodManager(27820): startInputInner - Id : 0
I/ViewRootImpl@26148ea[MainActivity](27820): ViewPostIme pointer 0
I/ViewRootImpl@26148ea[MainActivity](27820): ViewPostIme pointer 1
I/ViewRootImpl(27820): updatePointerIcon pointerType = 20001, calling pid = 27820
D/InputManager(27820): setPointerIconType iconId = 20001, callingPid = 27820
I/[DWTE]  (27820): onPenEvent no editText
I/ViewRootImpl@26148ea[MainActivity](27820): ViewPostIme pointer 0
E/InputEventReceiver(27820): Exception dispatching input event.
E/MessageQueue-JNI(27820): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI(27820): java.lang.AssertionError: Unexpected masked action
E/MessageQueue-JNI(27820): 	at io.flutter.embedding.android.AndroidTouchProcessor.getPointerChangeForAction(AndroidTouchProcessor.java:384)
E/MessageQueue-JNI(27820): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:124)
E/MessageQueue-JNI(27820): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:104)
E/MessageQueue-JNI(27820): 	at io.flutter.embedding.android.FlutterView.onTouchEvent(FlutterView.java:940)
E/MessageQueue-JNI(27820): 	at android.view.View.dispatchTouchEvent(View.java:15076)
E/MessageQueue-JNI(27820): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3917)
E/MessageQueue-JNI(27820): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3581)
E/MessageQueue-JNI(27820): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/MessageQueue-JNI(27820): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/MessageQueue-JNI(27820): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/MessageQueue-JNI(27820): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/MessageQueue-JNI(27820): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/MessageQueue-JNI(27820): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/MessageQueue-JNI(27820): 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1016)
E/MessageQueue-JNI(27820): 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
E/MessageQueue-JNI(27820): 	at android.app.Activity.dispatchTouchEvent(Activity.java:4265)
E/MessageQueue-JNI(27820): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:974)
E/MessageQueue-JNI(27820): 	at android.view.View.dispatchPointerEvent(View.java:15335)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7807)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7580)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6914)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6971)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6937)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7135)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6945)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7192)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6918)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6971)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6937)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6945)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6918)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10390)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10238)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10194)
E/MessageQueue-JNI(27820): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10522)
E/MessageQueue-JNI(27820): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
E/MessageQueue-JNI(27820): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI(27820): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MessageQueue-JNI(27820): 	at android.os.Looper.loopOnce(Looper.java:186)
E/MessageQueue-JNI(27820): 	at android.os.Looper.loop(Looper.java:313)
E/MessageQueue-JNI(27820): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MessageQueue-JNI(27820): 	at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI(27820): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MessageQueue-JNI(27820): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
D/AndroidRuntime(27820): Shutting down VM
E/AndroidRuntime(27820): FATAL EXCEPTION: main
E/AndroidRuntime(27820): Process: com.adilhanney.saber, PID: 27820
E/AndroidRuntime(27820): java.lang.AssertionError: Unexpected masked action
E/AndroidRuntime(27820): 	at io.flutter.embedding.android.AndroidTouchProcessor.getPointerChangeForAction(AndroidTouchProcessor.java:384)
E/AndroidRuntime(27820): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:124)
E/AndroidRuntime(27820): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:104)
E/AndroidRuntime(27820): 	at io.flutter.embedding.android.FlutterView.onTouchEvent(FlutterView.java:940)
E/AndroidRuntime(27820): 	at android.view.View.dispatchTouchEvent(View.java:15076)
E/AndroidRuntime(27820): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3917)
E/AndroidRuntime(27820): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3581)
E/AndroidRuntime(27820): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/AndroidRuntime(27820): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/AndroidRuntime(27820): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/AndroidRuntime(27820): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/AndroidRuntime(27820): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/AndroidRuntime(27820): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/AndroidRuntime(27820): 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1016)
E/AndroidRuntime(27820): 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
E/AndroidRuntime(27820): 	at android.app.Activity.dispatchTouchEvent(Activity.java:4265)
E/AndroidRuntime(27820): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:974)
E/AndroidRuntime(27820): 	at android.view.View.dispatchPointerEvent(View.java:15335)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7807)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7580)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6914)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6971)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6937)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7135)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6945)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7192)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6918)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6971)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6937)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6945)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6918)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10390)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10238)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10194)
E/AndroidRuntime(27820): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10522)
E/AndroidRuntime(27820): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
E/AndroidRuntime(27820): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(27820): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(27820): 	at android.os.Looper.loopOnce(Looper.java:186)
E/AndroidRuntime(27820): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(27820): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/AndroidRuntime(27820): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27820): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(27820): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Lost connection to device.
```

</details>

**Comment by jean-gblr** [comment]
Hello we are having the same issue, crash when clicking anywhere on screen with the button. Can this please be worked on ? It works on 3.0.5 but we need to update packages that use 3.3.5

**Comment by moffatman** [comment]
I would agree, better to ignore the event and print an error in release mode than crash. So probably that assertion should be caught in onTouchEvent and return false (event was not handled). But I don't have an android device with stylus to try this out. @dkwingsmt do you have any device to reproduce this on?

**Comment by Marc-R2** [comment]
Hi, I have the same problem with my Samsung Galaxy Tab S7 and my Galaxy Note. Every time I touch the screen in a Flutter app with the function key pressed, it crashes immediately.

**Comment by Marc-R2** [comment]
After a bit of trial and error, I assume that the error occurs from commit d08a1b02 (17.06.22 07:38) in the framework. Changes were made to the versions of the engine there.

**Comment by Marc-R2** [comment]
I can confirm that the app no longer crashes when I touch the touchscreen with the stylus and hold down the button. 👍
However, the pen then seems to disappear completely for the app and is no longer recognised at all. This means that no PointerDown, PointerMove, PointerUp or similar events are triggered when the button is pressed. This also means that no onTap, onPressed etc. reacts.
Tested in master 721fbe111

**Comment by jean-gblr** [comment]
Hello everyone, I wish to say thank you for working on the bug and "fixing" it. But is it possible to actually fix it ? And not just "disable" it ?

I mean it just worked on 3.0.5, so I don't think it's really acceptable to have it disabled now.

**Comment by moffatman** [comment]
@Marc-R2 Did that happen pre-https://github.com/flutter/flutter/commit/d08a1b02aeea59f43f1218f2dc9cde7247c09668?

**Comment by Marc-R2** [comment]
@moffatman You're right, it doesn't happen before that either. Then how do I get the information where the stylus is on the touchscreen when the function key is pressed?
I would expect that this then works as PointerMoveEvent as PointerDeviceKind.invertedStylus or as PointerDeviceKind.stylus with kPrimaryStylusButton (as with onPointerHover).
