### ISSUE TITLE
firebase_storage Unsupported value: [Ljava.lang.StackTraceElement;@a24b287

### ISSUE THREAD

**Issue by PixelToast** [flutter/flutter#11104]
## Steps to Reproduce

1. Upload a file to a place you don't have write permission
2. App crashes completely

## Logs

```E/StorageException(27468): StorageException has occurred.
E/StorageException(27468): User does not have permission to access this object.
E/StorageException(27468):  Code: -13021 HttpResult: 403
E/StorageException(27468): The server has terminated the upload session
E/StorageException(27468): java.io.IOException: The server has terminated the upload session
E/StorageException(27468): 	at com.google.firebase.storage.UploadTask.zzKZ(Unknown Source)
E/StorageException(27468): 	at com.google.firebase.storage.UploadTask.zzKY(Unknown Source)
E/StorageException(27468): 	at com.google.firebase.storage.UploadTask.run(Unknown Source)
E/StorageException(27468): 	at com.google.firebase.storage.zzr.run(Unknown Source)
E/StorageException(27468): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/StorageException(27468): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/StorageException(27468): 	at java.lang.Thread.run(Thread.java:818)
E/StorageException(27468): StorageException has occurred.
E/StorageException(27468): User does not have permission to access this object.
E/StorageException(27468):  Code: -13021 HttpResult: 403
E/StorageException(27468): The server has terminated the upload session
E/StorageException(27468): java.io.IOException: The server has terminated the upload session
E/StorageException(27468): 	at com.google.firebase.storage.UploadTask.zzKZ(Unknown Source)
E/StorageException(27468): 	at com.google.firebase.storage.UploadTask.zzKY(Unknown Source)
E/StorageException(27468): 	at com.google.firebase.storage.UploadTask.run(Unknown Source)
E/StorageException(27468): 	at com.google.firebase.storage.zzr.run(Unknown Source)
E/StorageException(27468): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/StorageException(27468): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/StorageException(27468): 	at java.lang.Thread.run(Thread.java:818)
D/AndroidRuntime(27468): Shutting down VM
E/AndroidRuntime(27468): FATAL EXCEPTION: main
E/AndroidRuntime(27468): Process: com.foo.bar, PID: 27468
E/AndroidRuntime(27468): java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.StackTraceElement;@a24b287
E/AndroidRuntime(27468): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:250)
E/AndroidRuntime(27468): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:65)
E/AndroidRuntime(27468): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:199)
E/AndroidRuntime(27468): 	at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin$2.onFailure(FirebaseStoragePlugin.java:58)
E/AndroidRuntime(27468): 	at com.google.firebase.storage.zzj.zzi(Unknown Source)
E/AndroidRuntime(27468): 	at com.google.firebase.storage.zzz.run(Unknown Source)
E/AndroidRuntime(27468): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(27468): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(27468): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(27468): 	at android.app.ActivityThread.main(ActivityThread.java:5551)
E/AndroidRuntime(27468): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27468): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
E/AndroidRuntime(27468): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)```
```
## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/pixel/flutter
    • Framework revision f946171817 (11 days ago), 2017-06-25 21:17:39 -0700
    • Engine revision 8a2d337446
    • Tools Dart version 1.24.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/pixel/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /home/pixel/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/pixel/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4424

[✓] Connected devices
    • LGMS428 • LGMS428cd6b9a61 • android-arm • Android 6.0.1 (API 23)
```

## Offending code
https://github.com/flutter/plugins/blob/master/packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java#L58

**Comment by collinjackson** [comment]
Fixed in flutter/plugins#166
