### ISSUE TITLE
`flutter run -d iphone` fails to connect to simulator observatory on Xcode 14

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#111167]
Flutter run output: 

```console
[   +3 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch 4C18E3C5-7886-4AE4-A9A1-275B52AA0D45 com.example.iosTest --enable-dart-profiling --enable-checked-mode
--verify-entry-points --observatory-port=0
[ +213 ms] com.example.iosTest: 53684
[        ] Waiting for observatory port to be available...
[   +4 ms] Error waiting for a debug connection: The log reader failed unexpectedly
[   +1 ms] Error launching application on iPhone 14 Pro.
[   +1 ms] "flutter run" took 20,384ms.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

Flutter doctor:

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-arm, locale en)
    • Flutter version 3.3.1 on channel stable at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 4f9d92fbbd (29 hours ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 4C18E3C5-7886-4AE4-A9A1-275B52AA0D45 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by jmagman** [comment]
Downloading the RC now on this machine to try to reproduce.  Did the app launch and start on the simulator?

**Comment by domesticmouse** [comment]
Yes, on the second run. First run was blank white screen. Seems this previously seen artifact is becoming repeatable, if only on my M1.

**Comment by domesticmouse** [comment]
Actually, it just takes an unseemingly long time to boot the first time on a new simulator.

**Comment by jmagman** [comment]
Did it attach correctly on the second run?  Or what does "Seems this previously seen artifact is becoming repeatable, if only on my M1" mean, that it never attaches or gives a white screen the first time?

This worked for me on a simulator on 14A309 the first time.
```
$ flutter run -d iphone
Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...
 └─Compiling, linking and signing...                        17.2s
Xcode build done.                                           36.1s
Syncing files to device iPhone 11...                                71ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 11 is available at: http://127.0.0.1:52172/VM31Utsux8Y=/
The Flutter DevTools debugger and profiler on iPhone 11 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:52172/VM31Utsux8Y=/
```
```
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Users/m/Applications/Xcode-14_rc.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3
```

If you quit it and then run `xcrun simctl launch 4C18E3C5-7886-4AE4-A9A1-275B52AA0D45 com.example.iosTest --enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0` does it launch?

**Comment by workerbee22** [comment]
@domesticmouse How does this go on `master` channel?

**Comment by domesticmouse** [comment]
Moved to `master` channel:

```console
$ flutter doctor -v
[✓] Flutter (Channel master, 3.4.0-19.0.pre.192, on macOS 12.5.1 21G83 darwin-arm64, locale en)
    • Flutter version 3.4.0-19.0.pre.192 on channel master at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 4930444f4a (2 days ago), 2022-09-09 21:58:23 -0400
    • Engine revision f72107f457
    • Dart version 2.19.0 (build 2.19.0-183.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 mini (mobile) • FCB1BDAE-A8A2-4F45-AD61-AEB693A90C6B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The lag at startup is gone, but still failing to connect to Observatory.

```console
$ flutter run -d iphone
Launching lib/main.dart on iPhone 13 mini in debug mode...
Running Xcode build...
 └─Compiling, linking and signing...                      2,549ms
Xcode build done.                                            7.9s
Error waiting for a debug connection: The log reader failed unexpectedly
Error launching application on iPhone 13 mini.
```

**Comment by greenhaixia** [comment]
Has the same issue on Xcode 14

**Comment by workerbee22** [comment]
I noted there is a new **_Developer mode_** required now for iOS 16 and above now, so perhaps that needs to be enabled in the iOS Simulator for the iPhone mini ?

https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device

So just wondering if you have this enabled in the Simulator?

<img width="950" alt="image" src="https://user-images.githubusercontent.com/5154664/189815131-81fb1152-c50a-499a-a21c-54c6fda97cac.png">

**Comment by quetool** [comment]
To be clear, THIS IS NOT HAPPENING on a real iPhone I use to debug... And that's weird cause most of the times is real devices to fail, Simulator always worked solid.

**Comment by jmagman** [comment]
I'm still not able to reproduce this.

@domesticmouse would you be able to `xcode-select` to the previous version of Xcode that worked for you and confirm it connects?  What version was that?

**Comment by domesticmouse** [comment]
Downgrading to XCode 13.4.1 hasn't fixed the issue.

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale en)
    • Flutter version 3.3.1 on channel stable at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 4f9d92fbbd (7 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • CEDEBBB5-D466-4A4E-9F12-0F50AF2E616D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Attempting to run the app fails to connect:

```console
$ flutter run -d iphone -v
[...]
[   +4 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch CEDEBBB5-D466-4A4E-9F12-0F50AF2E616D com.example.iosTest --enable-dart-profiling --enable-checked-mode
--verify-entry-points --observatory-port=0
[ +269 ms] com.example.iosTest: 97567
[        ] Waiting for observatory port to be available...
[   +3 ms] Error waiting for a debug connection: The log reader failed unexpectedly
[   +1 ms] Error launching application on iPhone 8.
[   +1 ms] "flutter run" took 12,052ms.
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +115 ms] ensureAnalyticsSent: 114ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

Oddly, I can run the `simctl` successfully.

```console
$ /usr/bin/arch -arm64e xcrun simctl launch CEDEBBB5-D466-4A4E-9F12-0F50AF2E616D com.example.iosTest --enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
com.example.iosTest: 97567
```

**Comment by quetool** [comment]
Same here, what happened to me is that my Xcode was automatically updated to 14 and I started to face the issue, therefor I downgraded again to 13.4.1, which it was working great before but now Im getting the same issue on 13.4.1 as well.
I can run the app just fine from within Xcode but when running it from flutter I get that issue.

**Comment by greenhaixia** [comment]
Latest flutter 3.3.2 fix this for me.

**Comment by domesticmouse** [comment]
@greenhaixia which version of XCode are you running? I'm seeing it again on upgrading to XCode 14.

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en)
    • Flutter version 3.3.2 on channel stable at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision e3c29ec00c (5 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 4C18E3C5-7886-4AE4-A9A1-275B52AA0D45 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by greenhaixia** [comment]
Xcode 14Sent from my iPhoneOn Sep 19, 2022, at 20:42, Brett Morgan ***@***.***> wrote:﻿
@greenhaixia which version of XCode are you running? I'm seeing it again on upgrading to XCode 14.
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en)
    • Flutter version 3.3.2 on channel stable at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision e3c29ec00c (5 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 4C18E3C5-7886-4AE4-A9A1-275B52AA0D45 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by greenhaixia** [comment]
> @greenhaixia could you please format your message?

sorry, i re-edit it and i use Xcode 14.

**Comment by quetool** [comment]
So essentially you have 
- macOS 12.6
- flutter on channel stable 3.3.2
and
- Xcode 14.0

And this is not happening to you anymore?

**Comment by greenhaixia** [comment]
yes

**Comment by wandriputra** [comment]
> So essentially @greenhaixia you have
> 
> * macOS 12.6
> * flutter on channel stable 3.3.2
>   and
> * Xcode 14.0
> 
> And this is not happening to you anymore?


I have same issue with this version

**Comment by Tumist76** [comment]
Rushed to update to Ventura and couldn't use XCode 13. Updated to XCode 14 and faced the same problem.

**Comment by Ali1Ammar** [comment]
i have same bugs after upgrade to macos 13 and xcode 14.0.1 
is there any workaround for this ?

**Comment by Ali1Ammar** [comment]
after I restart the computer the error gone and every things work again

**Comment by domesticmouse** [comment]
Everything seems to be working as intended on Flutter 3.3.6, macOS 13.1 beta, and XCode 14.1 RC. I suspect this is safe(ish) to close.

**Comment by dmitrybolt** [comment]
> after I restart the computer the error gone and every things work again

Can confirm. Restart fixes the issue

**Comment by domesticmouse** [comment]
Closing
