### ISSUE TITLE
Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = 0.0.0.0, port = 5353

### ISSUE THREAD

**Issue by AlexeySpiridonov** [flutter/flutter#111166]
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = 0.0.0.0, port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:110:40)
<asynchronous suspension>
#2      MDNSProvider.scan (package:wifi_extender2/modules/mdns/mdns_provider.dart:26:5)
<asynchronous suspension>for using Flutter!
```

```dart
import 'dart:io';

import 'package:multicast_dns/multicast_dns.dart';
import '../logger/logger.dart';
import 'models.dart';

class MDNSProvider {
  MDNSProvider();

  static const String name = '_mi-connect._udp.local'; // _http._tcp.local

  static Future<List<ScanResult>> scan() async {
    List<ScanResult> result = [];

    logger.d("scan(): start");

    final MDnsClient client = MDnsClient(rawDatagramSocketFactory:
        (dynamic host, int port,
            {bool? reuseAddress, bool? reusePort, int? ttl}) {
      return RawDatagramSocket.bind(host, port,
          reuseAddress: true,
          reusePort: Platform.isAndroid ? false : false,
          ttl: ttl!);
    });
    // Start the client with default options.
    await client.start();
    await for (final PtrResourceRecord ptr in client
        .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
      // Use the domainName from the PTR record to get the SRV record,
      // which will have the port and local hostname.
      // Note that duplicate messages may come through, especially if any
      // other mDNS queries are running elsewhere on the machine.
      await for (final SrvResourceRecord srv
          in client.lookup<SrvResourceRecord>(
              ResourceRecordQuery.service(ptr.domainName))) {
        // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
        final String bundleId =
            ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
        logger.d('Dart observatory instance found at '
            '${srv.target}:${srv.port} for "$bundleId".'); //TODO тут нам надо выдернуть имя / ip / port и mac из txt записи
        result.add(ScanResult(
            ipport: "${srv.target}:${srv.port}", name: bundleId, mac: ""));
      }
    }
    client.stop();
    logger.d("scan(): end");

    return result;
  }
}
```

**Comment by danagbemava-nc** [comment]
Hi @AlexeySpiridonov, what platform(s) are you experiencing this issue on? 

What version of `multicast_dns` are you using? 

Please also provide the output of `flutter doctor -v`.

Thank you
