### ISSUE TITLE
Flutter run crashes for new project

### ISSUE THREAD

**Issue by bulki24** [flutter/flutter#11129]
## Steps to Reproduce

Hi, 

I was trying out the Flutter codelab for building the frindlychat app. Everything worked well so I started with the firebass flutter codelab. After doing all of the steps for integrating firebase in my flutter app I can not run the project anymore. I tried to rollback to the start of the firebase flutter codelab but I am not able to run the version which runs befor. To figure out whats going on I startet a new project (created out of the IDE) and after generating it flutter run crashes with a fresh project too. I guess something is wrong with my configuration, maybe because of some (package) updates suring trying to integrate firebase.

```
Launching lib\main.dart on SM G925F in debug mode...
Running 'gradle assembleDebug'...

Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\sbrei\Dev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 285

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command 'C:\Users\sbrei\Dev\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Finished with error: Gradle build failed: 1
```

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build flx --suppress-analytics --target C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two\lib/main.dart --output-file C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two\build\app\intermediates\flutter\debug/app.flx --snapshot C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two\build\app\intermediates\flutter\debug/snapshot_blob.bin --depfile C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --working-dir C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two\build\app\intermediates\flutter\debug/flx

## exception

ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\sbrei\Dev\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\gen_snapshot.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43)
#2      runCommand (package:flutter_tools/src/base/process.dart:107)
#3      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:125)
<asynchronous suspension>
#4      createSnapshot (package:flutter_tools/src/flx.dart:58)
#5      build (package:flutter_tools/src/flx.dart:86)
<asynchronous suspension>
#6      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:44)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#8      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:206)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#16     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#25     main (file:///C:/Users/sbrei/Dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

Run `flutter analyze` and attach any output of that command also.

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 10.0.15063], locale de-DE, channel alpha)
    • Flutter at C:\Users\sbrei\Dev\flutter
    • Framework revision d36e2f6191 (3 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\sbrei\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Users\sbrei\Dev\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at C:\Users\sbrei\Dev\Android\Android Studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4424.63

[✓] Connected devices
    • SM G925F • 02157df29588d618 • android-arm • Android 7.0 (API 24)

```

```
C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two>flutter analyze
Analyzing C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two...
No issues found!
Ran in 13.5s

C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two>flutter run -v
[      +64 ms] [C:\Users\sbrei\Dev\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[     +210 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[       +3 ms] origin/alpha
[       +2 ms] [C:\Users\sbrei\Dev\flutter\] git ls-remote --get-url origin
[     +155 ms] Exit code 0 from: git ls-remote --get-url origin
[       +2 ms] https://github.com/flutter/flutter.git
[       +2 ms] [C:\Users\sbrei\Dev\flutter\] git log -n 1 --pretty=format:%H
[     +161 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[       +2 ms] d36e2f6191793de66e0a132ad8c86885829bc6b2
[       +2 ms] [C:\Users\sbrei\Dev\flutter\] git log -n 1 --pretty=format:%ar
[     +164 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[       +2 ms] 3 weeks ago
[    +1094 ms] Listing devices using C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb
[       +2 ms] C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb devices -l
[     +345 ms] Exit code 0 from: C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb devices -l
[       +2 ms] List of devices attached
               02157df29588d618       device product:zeroltexx model:SM_G925F device:zerolte
[      +58 ms] C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb -s 02157df29588d618 shell getprop
[     +583 ms] ro.hardware = samsungexynos7420
[    +1779 ms] Launching lib/main.dart on SM G925F in debug mode...
[     +266 ms] Using gradle from C:\Users\sbrei\Dev\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat.
[       +8 ms] [android\] C:\Users\sbrei\Dev\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat app:properties
[    +4669 ms] Exit code 0 from: C:\Users\sbrei\Dev\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat app:properties
[     +135 ms] C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb -s 02157df29588d618 logcat -v time -t 1
[     +512 ms] Exit code 0 from: C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb -s 02157df29588d618 logcat -v time -t 1
[       +2 ms] --------- beginning of system
               07-09 18:12:18.665 D/SSRM:v  ( 3643): SIOP:: AP = 280, PST = 275 (W:30), CP = 269, CUR = 252, LCD = 0
[       +5 ms] C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb -s 02157df29588d618 logcat -v time
[      +23 ms] C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb version
[     +720 ms] Android Debug Bridge version 1.0.39
                       Revision 3db08f2c6889-android
                       Installed as C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb.EXE
[      +12 ms] C:\Users\sbrei\AppData\Local\Android\sdk\platform-tools\adb start-server
[     +368 ms] Building APK
[     +247 ms] Using gradle from C:\Users\sbrei\Dev\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat.
[      +12 ms] Running 'gradle assembleDebug'...
[       +8 ms] [android\] C:\Users\sbrei\Dev\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat -Ptarget=C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two\lib/main.dart assembleDebug
[    +5474 ms] Incremental java compilation is an incubating feature.
[      +15 ms] The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
[       +2 ms]  at build_9deg0y8s5ui95lhkxkvb3zmtt$_run_closure2.doCall(C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two\android\build.gradle:23)
[     +260 ms] :app:flutterBuildX86Jar UP-TO-DATE
[       +3 ms] :app:preBuild UP-TO-DATE
[       +2 ms] :app:preDebugBuild UP-TO-DATE
[       +3 ms] :app:checkDebugManifest
[       +3 ms] :app:prepareDebugDependencies
[      +23 ms] :app:compileDebugAidl UP-TO-DATE
[      +34 ms] :app:compileDebugRenderscript UP-TO-DATE
[      +20 ms] :app:generateDebugBuildConfig UP-TO-DATE
[    +3262 ms] Oops; flutter has exited unexpectedly.
[    +1922 ms] Crash report written to C:\Users\sbrei\Dev\Workspace\flutter\flutter_test_two\flutter_02.log;
[       +3 ms] please let us know at https://github.com/flutter/flutter/issues.
[      +60 ms] :app:flutterDependenciesDebug FAILED
[       +4 ms] FAILURE: Build failed with an exception.
[       +6 ms] * Where:
[       +2 ms] Script 'C:\Users\sbrei\Dev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 285
[       +4 ms] * What went wrong:
[       +2 ms] Execution failed for task ':app:flutterDependenciesDebug'.
[       +3 ms] > Process 'command 'C:\Users\sbrei\Dev\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[       +4 ms] * Try:
[       +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[       +4 ms] BUILD FAILED
[       +2 ms] Total time: 10.636 secs
[     +771 ms] "flutter run" took 22,492ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:255)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:192)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/commands/build_apk.dart:83)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:354)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:233)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:183)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:329)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#9      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:217)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     new Future.sync (dart:async/future.dart:206)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#17     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1467)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#26     main (file:///C:/Users/sbrei/Dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[     +164 ms] ensureAnalyticsSent: 134ms
[       +5 ms] exiting with code 1
```

**Comment by eseidelGoogle** [comment]
Looks like it failed to find gen_snapshot (which should be downloaded automatically).  @goderbauer knows about our Windows support and I believe @bkonyi is learning about it.

**Comment by goderbauer** [comment]
Your `flutter doctor` shows an error:

> ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

Can you delete the `cache` directory inside the `bin` directory of your flutter installation? After that, execute `flutter doctor` again. It should re-download the executables and the error should be gone.

(I made this error slightly more discoverable in https://github.com/flutter/flutter/pull/11087, which has not been included in the alpha branch though)

**Comment by Hixie** [comment]
Could be the same as https://github.com/flutter/flutter/issues/16008.

We're going to close this bug because we've significantly changed the code at this point. Please don't hesitate to file a new bug if you still see this.
