### ISSUE TITLE
[tool_crash] flutter symbolize

### ISSUE THREAD

**Issue by II11II** [flutter/flutter#111284]
## Command
```
flutter symbolize -d /Users/user/Downloads/native-debug-symbols/x86_64/libstringcare.so.sym
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      SectionHeaderEntry.setName (package:native_stack_traces/src/elf.dart:426:32))
```
#0      SectionHeaderEntry.setName (package:native_stack_traces/src/elf.dart:426:32)
#1      Elf.fromReader (package:native_stack_traces/src/elf.dart:893:13)
#2      Dwarf.fromReader (package:native_stack_traces/src/dwarf.dart:1220:21)
#3      Dwarf.fromBytes (package:native_stack_traces/src/dwarf.dart:1229:13)
#4      _defaultTransformer (package:flutter_tools/src/commands/symbolize.dart:121:29)
#5      DwarfSymbolizationService.decode (package:flutter_tools/src/commands/symbolize.dart:177:30)
#6      SymbolizeCommand.runCommand (package:flutter_tools/src/commands/symbolize.dart:108:38)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale
    en-UZ)
    • Flutter version 2.5.3 at /Users/User/flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (11 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/User/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.7371

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • SM G960F (mobile) • 23ca9b3c980c7ece • android-arm64  • Android 10 (API
      29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      105.0.5195.102

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
> Channel unknown, 2.5.3

@II11II  You are on very old version of framework. Current version is 3.3.1. Try upgrading to latest and run same command again to see if you still get same error or not.

`flutter channel stable`
`flutter upgrade`

**Comment by II11II** [comment]
Hope it is fixed in the latest version of flutter, for now I close the ticket
