### ISSUE TITLE
[go_router] Crash when router trying to restore state

### ISSUE THREAD

**Issue by uncledoc** [flutter/flutter#111348]
Flutter 3.3.1, go_router 4.4.1, Emulator (Android 12.0)

How to reproduce (crash only in debug mode, in release - it's ok):

1. Run android emulator and set "Don't keep activities" as enabled in developer settings
2. Run [example](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/others/state_restoration.dart) 
3. Move app to a backstack (press home) and move back
4. Crash with message "**This GoRouteInformationParser needs to be used with GoRouteInformationProvider, did you forget to pass in GoRouter.routeInformationProvider to the Router constructor?
'package:go_router/src/parser.dart':
Failed assertion: line 51 pos 11: 'routeInformation is DebugGoRouteInformation**'"

**Comment by huycozy** [comment]
Hi, thanks for filing the issue. 
This issue is reproducible on the latest Flutter `stable` and `master` channels with reproduction steps as above.
Plugin version: `go_router: ^4.4.1`

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/189604926-f80ee9ac-b7c3-4e84-b424-e2d9578fc104.mp4

</details>

<details>
<summary>Logs</summary>

```bash
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building DefaultSelectionStyle:
This GoRouteInformationParser needs to be used with GoRouteInformationProvider, did you forget to
pass in GoRouter.routeInformationProvider to the Router constructor?
'package:go_router/src/parser.dart':
Failed assertion: line 51 pos 11: 'routeInformation is DebugGoRouteInformation'

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/reproduce_issues/lib/go_router_crash_111348.dart:34:53

When the exception was thrown, this was the stack:
#2      GoRouteInformationParser.parseRouteInformation.<anonymous closure> (package:go_router/src/parser.dart:51:11)
#3      GoRouteInformationParser.parseRouteInformation (package:go_router/src/parser.dart:58:6)
#4      RouteInformationParser.parseRouteInformationWithDependencies (package:flutter/src/widgets/router.dart:1213:12)
#5      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:707:8)
#6      _RouterState.restoreState (package:flutter/src/widgets/router.dart:582:7)
#7      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:872:5)
#8      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:858:7)
#9      _RouterState.didChangeDependencies (package:flutter/src/widgets/router.dart:655:11)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5046:11)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4871:5)
...     Normal element mounting (396 frames)
#407    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3883:16)
#408    Element.updateChild (package:flutter/src/widgets/framework.dart:3606:20)
#409    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4920:16)
#410    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5060:11)
#411    Element.rebuild (package:flutter/src/widgets/framework.dart:4617:5)
#412    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2687:19)
#413    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:21)
#414    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:375:5)
#415    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1271:15)
#416    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1200:9)
#417    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:924:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
<summary>Sample code</summary>

Sample code is from https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/others/state_restoration.dart
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.3.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (31 hours ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.192, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.192 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4930444f4a (2 days ago), 2022-09-09 21:58:23 -0400
    • Engine revision f72107f457
    • Dart version 2.19.0 (build 2.19.0-183.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by huycozy** [comment]
Hi @uncledoc, thanks for filing the issue. 
This issue is reproducible on the latest Flutter `stable` and `master` channels with reproduction steps as above.
Plugin version: `go_router: ^4.4.1`

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/189604926-f80ee9ac-b7c3-4e84-b424-e2d9578fc104.mp4

</details>

<details>
<summary>Logs</summary>

```bash
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building DefaultSelectionStyle:
This GoRouteInformationParser needs to be used with GoRouteInformationProvider, did you forget to
pass in GoRouter.routeInformationProvider to the Router constructor?
'package:go_router/src/parser.dart':
Failed assertion: line 51 pos 11: 'routeInformation is DebugGoRouteInformation'

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/reproduce_issues/lib/go_router_crash_111348.dart:34:53

When the exception was thrown, this was the stack:
#2      GoRouteInformationParser.parseRouteInformation.<anonymous closure> (package:go_router/src/parser.dart:51:11)
#3      GoRouteInformationParser.parseRouteInformation (package:go_router/src/parser.dart:58:6)
#4      RouteInformationParser.parseRouteInformationWithDependencies (package:flutter/src/widgets/router.dart:1213:12)
#5      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:707:8)
#6      _RouterState.restoreState (package:flutter/src/widgets/router.dart:582:7)
#7      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:872:5)
#8      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:858:7)
#9      _RouterState.didChangeDependencies (package:flutter/src/widgets/router.dart:655:11)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5046:11)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4871:5)
...     Normal element mounting (396 frames)
#407    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3883:16)
#408    Element.updateChild (package:flutter/src/widgets/framework.dart:3606:20)
#409    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4920:16)
#410    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5060:11)
#411    Element.rebuild (package:flutter/src/widgets/framework.dart:4617:5)
#412    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2687:19)
#413    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:21)
#414    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:375:5)
#415    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1271:15)
#416    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1200:9)
#417    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:924:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
<summary>Sample code</summary>

Sample code is from https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/others/state_restoration.dart
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.3.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (31 hours ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.192, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.192 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4930444f4a (2 days ago), 2022-09-09 21:58:23 -0400
    • Engine revision f72107f457
    • Dart version 2.19.0 (build 2.19.0-183.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by chunhtai** [comment]
we should remove the check, it was originally created to remind people to use GoRouteInformationProvider, and it should be removed.
