### ISSUE TITLE
Flutter FadeInImage _CastError: Null check operator used on a null value

### ISSUE THREAD

**Issue by appcapsergen** [flutter/flutter#111455]
Since I upgraded my Flutter project to 3.3+, I've been experiencing this error.

It has so far only occurred for me if I navigate to a second screen and then after some time navigate back to the previous screen, given that this previous screen contains a FadeInImage

Here's the specific FadeInImage in my code where the error's so far have occurred:
```dart
        ...
        return FadeInImage(
          image: NetworkImage(imageUrl ?? ''),
          placeholder: MemoryImage(Uint8List.fromList(<int>[0x89,  0x50,  0x4E,  0x47,  0x0D,  0x0A,  0x1A,  0x0A,  0x00,  0x00,  0x00,  0x0D,  0x49,  0x48,  0x44,  0x52,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x08,  0x06,  0x00,  0x00,  0x00,  0x1F,  0x15,  0xC4,  0x89,  0x00,  0x00,  0x00,  0x0A,  0x49,  0x44,  0x41,  0x54,  0x78,  0x9C,  0x63,  0x00,  0x01,  0x00,  0x00,  0x05,  0x00,  0x01,  0x0D,  0x0A,  0x2D,  0xB4,  0x00,  0x00,  0x00,  0x00,  0x49,  0x45,  0x4E,  0x44, 0xAE])),
          fit: fit,
          placeholderFit: fit, // BoxFit.fill by default, BoxFit.contain or BoxFit.cover in other cases
          imageErrorBuilder: imageErrorBuilder ?? _defaultImageErrorBuilder,
          fadeInDuration: Duration(milliseconds: 300),
        );
    }

    Widget _defaultImageErrorBuilder(_, __, ___) => const SizedBox.shrink();
```

Exception in logs:
<details> 

```
  ======== Exception caught by widgets library =======================================================
  The following _CastError was thrown building _AnimatedFadeOutFadeIn(duration: 600ms, dirty, state: _AnimatedFadeOutFadeInState#64912(ticker inactive, targetOpacity: null, placeholderOpacity: null)):
  Null check operator used on a null value
  
  The relevant error-causing widget was: 
  FadeInImage FadeInImage:file:///Users/sepekerimu/Apps/huddle-flutter-app/lib/presentation/widgets/ui/fade_image.dart:51:12
  When the exception was thrown, this was the stack: 
  #0      _AnimatedFadeOutFadeInState.build (package:flutter/src/widgets/fade_in_image.dart:542:70)
  #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
  #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
  #3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #5      StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #10     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #21     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #34     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #44     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #45     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #48     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #49     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #50     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #53     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #54     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #55     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #56     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
  #57     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
  #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #62     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #64     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #66     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #68     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #69     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #70     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #71     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #73     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #74     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #76     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
  #77     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
  #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #80     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #81     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #82     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #84     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #86     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #87     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #88     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #90     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #91     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #92     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #94     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #95     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #97     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #98     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #99     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #101    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #102    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #103    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #104    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #105    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #107    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #108    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #109    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #111    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #113    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #114    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #115    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #116    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #118    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #120    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #121    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #123    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #124    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #125    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #127    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #129    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #130    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #131    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #133    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #134    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #135    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #137    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #138    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #139    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #141    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #142    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #143    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #145    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #146    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #147    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #148    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #149    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #150    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #152    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #153    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #154    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #155    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #156    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #158    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #159    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #160    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #161    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #163    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #164    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #165    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #166    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #168    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #169    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #170    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #172    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #173    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #174    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #175    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
  #176    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
  #177    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #179    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #180    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #181    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #183    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #184    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #185    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #186    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #188    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #189    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #190    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #191    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #193    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #194    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #195    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #197    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #198    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #199    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #200    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #201    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #202    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #204    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #205    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #206    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #207    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #208    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #210    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #211    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #212    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #213    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #215    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #216    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #217    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #218    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #220    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #221    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #222    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #223    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #224    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #225    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #226    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #227    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #228    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #229    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #230    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #232    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #233    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #234    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #235    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #237    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #238    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #239    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #241    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #242    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #243    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
  #244    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #246    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #247    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
  #248    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #249    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #250    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #252    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #253    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #254    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #255    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
  #256    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #257    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #258    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #259    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #260    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #262    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #263    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #264    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #265    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #266    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #267    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
  #268    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
  #269    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
  #270    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
  #271    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
  #272    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
  #273    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
  #274    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
  #275    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
  ====================================================================================================
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @appcapsergen, this was initially reported in https://github.com/flutter/flutter/issues/111011 and has since been fixed. 

The fix is available on the master channel and should rollout to stable sometime soon. 

Per our triage policy, I'll be closing this issue as it has already been fixed. 

If you do run into this issue on the master channel, kindly leave a comment below and I will reopen this. 

Thank you
