### ISSUE TITLE
Getting 404 status code for a valid https url

### ISSUE THREAD

**Issue by nassimus26** [flutter/flutter#111579]
I am getting a `404` status code for this url, I tried with https or http, it gives the same error, but the url is working on any navigator.

It didn't just failed in test mode, but also in running mode.

I also try it with Java, it's working fine too !

```
String url = "http://showflix.org:5890/get.php?username=Wadihh15&password=15012021dggdj&type=m3u"
httpClient = new IO.HttpClient();
httpClient.badCertificateCallback = ((X509Certificate cert, String host, int port) {
        return true;
}); //
Uri uri = Uri.parse(url);
IO.HttpClientRequest request = await httpClient.openUrl("GET", uri);
IO.HttpClientResponse response = await request.close();
print (response.statusCode) 
```
When I run the `check_domain_access.dart` with this URL , I get :

```
Testing host resolves...
- showflix.org IPv4 resolve and connect succeeded: 0 / 1
- showflix.org IPv6 lookup failed: SocketException: Failed host lookup: 'showflix.org' (OS Error: Hôte inconnu.
, errno = 11001)
- pub.dev IPv4 resolve and connect succeeded: 4 / 4
- pub.dev IPv6 lookup failed: SocketException: Failed host lookup: 'pub.dev' (OS Error: Le nom demandé est valide, mais aucune donnée du type requise n’a été trouvée.
, errno = 11004)
....

```
```
PS C:\Users\cd_bo\StudioProjects\dart_vlc\example> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [version 10.0.19044.1889], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.67.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by exaby73** [comment]
Hello @nassimus26. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`

**Comment by nassimus26** [comment]
Hi @exaby73 , I think I put everything you need to reproduce, you just need the URL, try to call it with any Http dart client, it won't works, that's it !, but it works on Java or any navigator !

**Comment by nassimus26** [comment]
Hi @exaby73 it has nothing to do with Flutter, it seems it's an android JVM bug 

In a normal JVM it's wroks, but not an android or Dart Jvm.

   ```
try {
      InetAddress[] dnsNames = InetAddress.getAllByName("showflix.org");
      System.out.println(Arrays.toString(dnsNames) );
    } catch (Throwable e) {
      e.printStackTrace();
    }
```
```
at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
```

**Comment by nassimus26** [comment]
So actually writing an alternative native wrapped Java client is not solving the issue !

**Comment by nassimus26** [comment]
I think it's related to this https://forum.developer.samsung.com/t/unknownhostexception-after-android-11-update/12126
please close this issue it has nothing to do with Flutter
