### ISSUE TITLE
[Android] "[DP] cancelDraw" warning prints while app is starting on some Samsung devices

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#111593]
On some Samsung devices, the warning

```
I/ViewRootImpl@91023c2[MainActivity]( 2630): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@a3ede7d isViewVisible: true
```

is printed many times before the app starts up and the Flutter Ui is displayed.

**This warning is Samsung-specific, but is **not** an error. If you are experiencing the warning **and** the app is printing at all, please report this under TODO.**

**Comment by SivkovSavely** [comment]
Samsung Galaxy S21 Ultra 5G, Android 12, One UI 4.1. Can confirm, but it's printing `I/ViewRootImpl@339ef58[MainActivity](11750): [DP] cancelDraw null isViewVisible: true` for me, so the delegate is null.

Also it's printing this line indefinitely if there was another exception thrown (in my case my own app threw an Exception in main(), and "cancelDraw" message was logging even after the exception, cluttering the log and making finding an exception harder.

**Comment by YukiAttano** [comment]
I've experienced the same bug on Samsung Galaxy Note 20. At the time of writing on the latest software version available.
In my case, the message that repeats is:
`I/MSHandlerLifeCycle(18544): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=false this: DecorView@e6099c3[MainActivity]`

I do also get every user interaction printed to console. like locking/unlocking the screen. Interacting with any visible element (Flutter and Android system) while the app is in foreground.

Starting the App without an asynchronous main does fail with `'owner!._debugCurrentBuildTarget == this': is not true`

**Comment by AKR-2803** [comment]
I've the same issue as on 08-02-2023
Device : Samsung Galaxy A50
Flutter SDK 3.0.2 
Android Studio Dolphin 2021.3.1

I've tried editing the ```AndroidManifest.xml``` by adding these lines : 

```<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />```


Also tried removing them, but nothing helped. There's no concrete solution is available on this issue.

The console is flooded with these messages :
 
```I/ViewRootImpl@772f9db[MainActivity]( 5651): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@4d8da9f  isViewVisible: true``` 

The complete message on my console : 

```
PS D:\Development\FlutterProjects\nike_application> flutter run
Launching lib\main.dart on SM A505F in debug mode...
Running Gradle task 'assembleDebug'...                             71.0s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                17.5s
E/flutter ( 6697): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
E/flutter ( 6697): #0      FirebaseCoreHostApi.optionsFromResource (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:246:7)
E/flutter ( 6697): <asynchronous suspension>
E/flutter ( 6697): #1      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:89:25)
E/flutter ( 6697): <asynchronous suspension>
E/flutter ( 6697): #2      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
E/flutter ( 6697): <asynchronous suspension>
E/flutter ( 6697): #3      main (package:nike_application/main.dart:9:3)
E/flutter ( 6697): <asynchronous suspension>
E/flutter ( 6697): 
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
Syncing files to device SM A505F...                                211ms
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true

Flutter run key commands.
r Hot reload. 
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

 Running with sound null safety 

An Observatory debugger and profiler on SM A505F is available at: http://127.0.0.1:49634/Fl6tIstDZ28=/
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
The Flutter DevTools debugger and profiler on SM A505F is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:49634/Fl6tIstDZ28=/
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true
```
and this goes on indefinitely...

**Comment by AndreRidho** [comment]
Try removing your VS Code breakpoints.

**Comment by AKR-2803** [comment]
Already did, its no use.

**Comment by SeniruHasith** [comment]
"WidgetsFlutterBinding.ensureInitialized();"
add this to the void main method in main.Dart

Void main looks like this after :

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  runApp(new MyApp());
}

**Comment by AKR-2803** [comment]
Hey, I've upgraded my flutter SDK to 3.7.1, but now I'm facing the same error because of 
```SystemChrome.setPreferredOrientations```

The main method is as below : 

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);

  SystemChrome.setPreferredOrientations(
          [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown])
      .then((value) => () {
            //initializing firebase
            _initializeFirebase();
            runApp(const MyApp());
          });
}
```

Its working without the ```SystemChrome.setPreferredOrientations``` but why does it happen in the first place?

**Comment by AndreRidho** [comment]
Try wrapping the offending lines with
`WidgetsBinding.instance.addPostFrameCallback((_) {
        // Your code here
      });`

**Comment by erturkalan** [comment]
I'm still having this trouble, I create new flutter project and it works but still cant hot reload. And if I change home page create new page as a start point like it doesn't work. It keep stalling on this error:
 I/ViewRootImpl@d118f8d[MainActivity]( 6697): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@db63516  isViewVisible: true

my main is like:

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        initialRoute: '/',
        getPages: [
          GetPage(name: "/", page: () => const ChatPage()),
        ]);
  }
}

**Comment by LearnerLeo24** [comment]
Can anyone please solve the following Cancel Draw issue.

I/ViewRootImpl@97c1579[MainActivity](28245): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@a428f5d  isViewVisible: true

**Comment by ucsama** [comment]
having same issue how to fix it

**Comment by darshankawar** [comment]
I observed this behavior when running a newly created Flutter app via latest Android Studio version and running on latest master version with Samsung A03 device (Android 11). For a counter app, the console log is filled with below:

```
Launching lib/main.dart on SM A035F in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...
I/flutter (20058): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
Debug service listening on ws://127.0.0.1:59320/liFG6xWm3I0=/ws
Syncing files to device SM A035F...
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
I/ViewRootImpl@2b57094[MainActivity](20058): [DP] cancelDraw  isViewVisible: true
```

**Comment by AKR-2803** [comment]
As of now, it would be advisable to switch from Samsung to some other alternative device (its what I did back then), this issue is specific to Samsung devices.

**Comment by barilki** [comment]
Any updates?

**Comment by GiovanniPoggi** [comment]
hi, is there any updates? i have the same problem

**Comment by guilhermelmello** [comment]
I was facing the same problem. But the device had no internet connection and the firebase could not be correctly configured, showing some error messages related to that but also resulting in the message `[DP] cancelDraw null  isViewVisible: true` to appear indefinitely while the app got stuck in the splash screen.

Enabling the internet connection in the device fixed the issue for me.

Hope this helps someone else.
