### ISSUE TITLE
`flutter` tool should initialize Intl.defaultLocale manually and catch errors.

### ISSUE THREAD

**Issue by lihe6666** [flutter/flutter#11151]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Invalid locale 'ns_US'

```
#0      Intl._throwLocaleError (package:intl/intl.dart:229)
#1      Intl.verifiedLocale (package:intl/intl.dart:223)
#2      Intl.verifiedLocale (package:intl/intl.dart:208)
#3      new NumberFormat._forPattern (package:intl/src/intl/number_format.dart:486)
#4      new NumberFormat.decimalPattern (package:intl/src/intl/number_format.dart:175)
#5      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:92)
#6      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:92)
#7      getElapsedAsMilliseconds (package:flutter_tools/src/base/utils.dart:100)
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:206)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#15     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1467)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#24     main (file:///Users/lion/Documents/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale zh-Hans-US, channel alpha)
    • Flutter at /Users/lion/Documents/flutter
    • Framework revision d36e2f6191 (3 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Volumes/MAC_OS_DATA/AndroidSDK-MACOS
    • Platform android-26, build-tools 25.0.2
    • ANDROID_HOME = /Volumes/MAC_OS_DATA/AndroidSDK-MACOS
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • None

```

**Comment by lihe6666** [comment]
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

problem solve.

**Comment by alan-knight** [comment]
This is expected behavior in Intl. We couldn't find any locale to fall back to from ns_US, so it throws.
This is presumably getting the locale from the platform, and at that time it could verify it.  Something like

      Intl.defaultLocale = Intl.verifiedLocale(Platform.localeName, NumberFormat.localeExists,
          onFailure: (_) => 'en_US');

The NumberFormat part is because locale existence depends on purpose. We might e.g. have number formatting for a locale but not translations. That would get messy.

**Comment by eseidelGoogle** [comment]
This is occurring inside flutter_tools, which is a normal dart:io program run in the command-line dart VM, I believe this is where the locale is set:
https://github.com/dart-lang/intl/blob/master/lib/intl_standalone.dart#L26

@alan-knight does your comment above mean that intl_standalone should change to be more robust?  Or should flutter_tools do its own initialization of defaultLocale?

**Comment by tvolkert** [comment]
It sounds like flutter_tools should just do its own initialization of `defaultLocale` in its `main()` method.

**Comment by alan-knight** [comment]
I don't think that findSystemLocale should change. That's telling us what the operating system thinks the locale is, and I don't think it should hide that if we're missing data for it.

There's an argument that the various Intl calls should fall back to something if a locale isn't found rather than throwing, but that's a non-trivial change, and there might even be an argument that the something shouldn't be hardcoded to en_US.

But the quick answer would be to change flutter to do the verification. Like

```
// Initialize the system locale.
var systemLocale = await intl.findSystemLocale();
intl.Intl.defaultLocale = intl.Intl.verifiedLocale(systemLocale, intl.NumberFormat.localeExists,
      onFailure: (_) => 'en_US');
```

**Comment by Hixie** [comment]
This is causing Flutter to crash in many non-English locales. We should consider it a high priority.
