### ISSUE TITLE
issue with video controller re-initialization

### ISSUE THREAD

**Issue by alpeshshiyal** [flutter/flutter#111657]
Not able to re-initialize(restart) video controller after controller.value.hasError is true

```
Init 37a39ef [ExoPlayerLib/2.18.1] [m30s, SM-M307F, samsung, 30]
I/System.out(21994): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(21994): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter (21994): 0.0 of my widget is visible
I/flutter (21994): video Ended
E/flutter (21994): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: Future already completed
E/flutter (21994): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
E/flutter (21994): #1      VideoPlayerController.initialize (package:video_player/video_player.dart:365:25)
E/flutter (21994): <asynchronous suspension>
E/flutter (21994): #2      ChewieController._initialize (package:chewie/src/chewie_player.dart:546:7)
E/flutter (21994): <asynchronous suspension>
E/flutter (21994): 
```

here my verbase log:

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.556], locale en-US)
    • Flutter version 3.0.5 at C:\src\flutter_windows_stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\niles\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\niles\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.16)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32602.291
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.71.0)
    • VS Code at C:\Users\niles\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM M307F (mobile) • RZ8MC06QV4P • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 105.0.1343.33

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by huycozy** [comment]
Hi @alpeshshiyal
Which `video_player` plugin version are you using?
Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
Thank you!

May be related/similar: #25738

**Comment by waqadArshad** [comment]
@alpeshshiyal how did you resolve this?
