### ISSUE TITLE
[go_router] Empty redirect routes don't work on 4.5.0

### ISSUE THREAD

**Issue by hugofpsilva** [flutter/flutter#111789]
## Description
Empty redirect routes, as shown below, don't work on 4.5.0, but they were working on 4.4.1

```dart
GoRoute(
  path: '/',
  redirect: (_) => '/otherRoute',
),
```

## Steps to Reproduce

1. Install go_router 4.5.0
2. Execute `flutter run` on the code sample below 
3. An assert error occurs

**Expected results:**
No error to occur on empty redirect routes. I might want to use a route simply to redirect to another route, without building anything. This was working on 4.4.1

**Actual results:**
An assert error occurs when an empty redirect route is declared.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final GoRouter _goRouter = GoRouter(routes: [
    GoRoute(
      path: '/',
      redirect: (_) => '/otherRoute',
    ),
    GoRoute(
      path: '/otherRoute',
      builder: (context, state) => const Scaffold(),
    )
  ]);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Redirect not working in 4.5.0',
      routerDelegate: _goRouter.routerDelegate,
      routeInformationParser: _goRouter.routeInformationParser,
      routeInformationProvider: _goRouter.routeInformationProvider,
    );
  }
}
```

</details>

<details>
  <summary>Log</summary>

```
[  +91 ms] E/flutter (30726): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:go_router/src/route.dart': Failed assertion: line 131
pos 16: '!(builder == null && pageBuilder == null)': builder or pageBuilder must be provided
[        ] E/flutter (30726): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
[        ] E/flutter (30726): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
[        ] E/flutter (30726): #2      new GoRoute (package:go_router/src/route.dart:131:16)
[        ] E/flutter (30726): #3      new MyApp (package:gorouterredirect/main.dart:12:5)
[        ] E/flutter (30726): #4      main (package:gorouterredirect/main.dart:5:10)
[        ] E/flutter (30726): #5      _runMain.<anonymous closure> (dart:ui/hooks.dart:134:23)
[        ] E/flutter (30726): #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
[        ] E/flutter (30726): #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

</details>

<details>
  <summary>Doctor</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-PT)
    • Flutter version 3.3.2 on channel stable at /Users/hugofpsilva/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (2 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/hugofpsilva/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • LE2123 (mobile) • 987f7dba • android-arm64  • Android 12 (API 31)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by hugofpsilva** [comment]
Duplicate of #111763
