### ISSUE TITLE
Google Sign In throws an exception if offline

### ISSUE THREAD

**Issue by Skylled** [flutter/flutter#11178]
## Steps to Reproduce

Run an Android app that uses Google Sign In, with airplane mode on.
I'm simulating a no-network condition (which is somewhat common in my use case) trying to rely on the Firebase database cache in some cases when offline.

The popup appears, to select an account to sign in, then it throws an exception after selecting one.

I wasn't expecting it to function correctly, but I was hoping for a more targeted Exception to catch, as there are probably a few different scenarios that could throw a `PlatformException`.

## Logs
```
D/NetworkSecurityConfig( 6234): No Network Security Config specified, using platform default
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): remote DNS query failed we don't need to try local DNS query result_code =401
Syncing files to device LG H910...
I/flutter ( 6234): Silent login failed
I/Timeline( 6234): Timeline: Activity_launch_request id:net.hotfixit.cybertronix time:564367150
I/Timeline( 6234): Timeline: Activity_idle id: android.os.BinderProxy@9b38f9e time:564367385
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): remote DNS query failed we don't need to try local DNS query result_code =401
D/libc    ( 6234): getaddrinfo called from pid =6234

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on LG H910 is available at: http://127.0.0.1:8116/
For a more detailed help message, press "h". To quit, press "q".
D/FirebaseInstanceId( 6234): background sync failed: SERVICE_NOT_AVAILABLE, retry in 30s
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): remote DNS query failed we don't need to try local DNS query result_code =401
D/libc    ( 6234): getaddrinfo called from pid =6234
E/flutter ( 6234): [ERROR:lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 6234): PlatformException(status, Status{statusCode=NETWORK_ERROR, resolution=null}, null)
E/flutter ( 6234): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514)
E/flutter ( 6234): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter ( 6234): <asynchronous suspension>
E/flutter ( 6234): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:156)
E/flutter ( 6234): <asynchronous suspension>
E/flutter ( 6234): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:196)
E/flutter ( 6234): #4      _RootZone.run (dart:async/zone.dart:1366)
E/flutter ( 6234): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:152)
E/flutter ( 6234): #6      _Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:606)
E/flutter ( 6234): #7      _Future._propagateToListeners (dart:async/future_impl.dart:662)
E/flutter ( 6234): #8      _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:343)
E/flutter ( 6234): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter ( 6234): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
I/Timeline( 6234): Timeline: Activity_idle id: android.os.BinderProxy@e80409f time:564375639
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): getaddrinfo called from pid =6234
D/libc    ( 6234): remote DNS query failed we don't need to try local DNS query result_code =401
```

**Comment by cyanglaz** [comment]
Does `statusCode=NETWORK_ERROR` in the exception object help you in this case?
