### ISSUE TITLE
background message crash while using firebase_messaging 7.0.3 in flutter 

### ISSUE THREAD

**Issue by arun2799** [flutter/flutter#111858]
I am using firebase messaging package for getting the notification in flutter, but background message is not working properly i.e. getting crash while the message is tap.
Getting this error:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Unsupported value: Bundle[mParcelledData.dataSize=100], null, java.lang.IllegalArgumentException: Unsupported value: Bundle[mParcelledData.dataSize=100]
E/flutter ( 5904):      at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:276)
E/flutter ( 5904):      at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:273)
E/flutter ( 5904):      at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:273)
E/flutter ( 5904):      at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/flutter ( 5904):      at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:99)
E/flutter ( 5904):      at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:83)
E/flutter ( 5904):      at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.sendMessageFromIntent(FirebaseMessagingPlugin.java:324)
E/flutter ( 5904):      at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:196)
E/flutter ( 5904):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 5904):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 5904):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter ( 5904):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 5904):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 5904):      at android.os.Looper.loopOnce(Looper.java:186)
E/flutter ( 5904):      at android.os.Looper.loop(Looper.java:313)
E/flutter ( 5904):      at android.app.ActivityThread.main(ActivityThread.java:8669)
E/flutter ( 5904):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5904):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter ( 5904):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter ( 5904): )
E/flutter ( 5904): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter ( 5904): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 5904): <asynchronous suspension> 
```

Please help me out if any body finds the solutions.
Thanks

**Comment by danagbemava-nc** [comment]
Hi @arun2799, this is a crash in the `FirebaseMessagingPlugin` and should be reported in their repo. 

Closing from here as this is not a flutter issue. 

Thank you
