### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException Error flutter

### ISSUE THREAD

**Issue by Chonkosaurus-rex** [flutter/flutter#111919]
Hey guys,

Please help me with my flutter project. this is my first project ever and i am facing some problems with it.
i try to run this app but it does not appear on paired.

```
PS C:\projekt\dear> flutter run
Using hardware rendering with device AOSP on IA Emulator. If you notice graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".                                                                                                       
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Exception in thread "main" java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                           2,754ms
Exception: Gradle task assembleDebug failed with exit code 1
```
![Capture error](https://user-images.githubusercontent.com/113284711/191117689-91f0aab0-57e2-4368-99cd-771d8475e302.PNG)

**Comment by huycozy** [comment]
Hi @Chonkosaurus-rex 
As I can see that you're using Windows, so please try solve the issue by this workaround: https://github.com/flutter/flutter/issues/73852#issuecomment-760146447

**Comment by huycozy** [comment]
@Chonkosaurus-rex 
As far as I can see, the original issue has been fixed.

>Error: unable to locate asset entry in pubspec.yaml: "fonts/andina.ttf".

For this new error, please check https://docs.flutter.dev/development/ui/assets-and-images or you can ask this on support channels like StackOverflow.

I feel safe to close this issue now, if you disagree please write in the comments and I will reopen it. Thank you!
