### ISSUE TITLE
[tool_crash] _TypeError: (#0      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart))

### ISSUE THREAD

**Issue by antoniobarcebal012** [flutter/flutter#111982]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart))
```
#0      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart)
#1      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:305:31)
<asynchronous suspension>
#2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.355, on Microsoft Windows [Version 10.0.19044.2006], locale en-US)
    • Flutter version 3.4.0-19.0.pre.355 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6906493a94 (23 hours ago), 2022-09-19 10:28:37 -0700
    • Engine revision f2f0839aac
    • Dart version 2.19.0 (build 2.19.0-216.0.dev)
    • DevTools version 2.17.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\POU\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code, 64-bit edition (version 1.71.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.67

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null

**Comment by danagbemava-nc** [comment]
Hi @antoniobarcebal012, this was recently reported in https://github.com/flutter/flutter/issues/111877 and has since been fixed. It looks like it was fixed not long after you filed this issue. 

As such I'll be closing this issue as fixed. 

If you run into this issue on a newer version of the master channel, kindly leave a comment below and I will reopen this. 

Thank you
