### ISSUE TITLE
NoSuchMethodError: method not found: 'toString' / Uncaught TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by dargoz** [flutter/flutter#112056]
I've experiencing error when deploying flutter web in hosting / cloud platform with error 
``NoSuchMethodError: method not found: 'toString'`` or  ``Uncaught TypeError: Cannot read properties of null (reading 'toString')``. What make me confused is when I tried it in my local machine (use the release build) the problem didn't occured. ( I also tried build in docker image and simulate it in local docker container (work without issue in local) and still experiencing the same way when I deploy my image in cloud platform).

## Steps to Reproduce

1. Clone this project : https://github.com/dargoz/grimoire
2. Build project ``flutter pub get`` and ``flutter pub run build_runner build --delete-conflicting-outputs``
3. Execute ``flutter build web --web-renderer canvaskit`` 
4. Deploy on Cloud platform (I've tried some of hosting platform and experiencing the same issue) 
5. Click one of the menu button to trigger the code sample below

**Expected results:** 
after click one of the button in image below
![image](https://user-images.githubusercontent.com/30622151/191481147-912799e9-11c0-4f9d-876d-78c014d4393e.png)
it should navigate to next page (/grimoire/explorer) like image below
![image](https://user-images.githubusercontent.com/30622151/191480817-02340033-98ba-49b1-86ce-d447c56af0af.png)

**Actual results:** 

after click one of the button in image below

![image](https://user-images.githubusercontent.com/30622151/191481147-912799e9-11c0-4f9d-876d-78c014d4393e.png)

using github pages .. the screen stuck (nothing happen) or when window size changed, it show error in console

![image](https://user-images.githubusercontent.com/30622151/191481964-3b1f6514-a6b3-4ca5-9178-2d57a0f2c74a.png)

using another platform ( I used openshift ) I got different behaviour.. (can process to next page), but I think to causes are same

![image](https://user-images.githubusercontent.com/30622151/191484179-906d742f-d700-4a1a-bf41-fc2dbcf30007.png)

<details>
<summary>Code sample</summary>

just clone my public project :  https://github.com/dargoz/grimoire. 
I've suspected issue related to encryption process during Hive creation
```dart
@override
Future<String> loadProject() async {
    var encryptedBox = await Hive.openBox(projectBox,
        encryptionCipher: HiveAesCipher(encryptionKey!));
    return encryptedBox.get('project_id');
}
```

</details>

<details>
  <summary>Logs</summary>

```
Flutter Web Bootstrap: Programmatic
main.dart.js:31707 Encryption key: [169, 87, 170, 230, 156, 72, 197, 197, 167, 77, 140, 145, 254, 91, 54, 65, 205, 35, 42, 128, 177, 190, 17, 242, 145, 6, 117, 219, 32, 13, 103, 168]
main.dart.js:31707 Got object store box in database projectbox.
main.dart.js:31707 RESPONSE[200] => PATH: /projects/39138680/repository/tree
main.dart.js:31707 NoSuchMethodError: method not found: 'toString' on null
main.dart.js:31707     at ia.gdj (https://dargoz.github.io/grimoire-demo/main.dart.js:78358:3)
main.dart.js:31707     at BM.kV (https://dargoz.github.io/grimoire-demo/main.dart.js:78269:49)
main.dart.js:31707     at Object.h9 (https://dargoz.github.io/grimoire-demo/main.dart.js:20179:25)
main.dart.js:31707     at zr.Sk (https://dargoz.github.io/grimoire-demo/main.dart.js:95507:14)
main.dart.js:31707     at amK.$0 (https://dargoz.github.io/grimoire-demo/main.dart.js:95522:10)
main.dart.js:31707     at rC.fd (https://dargoz.github.io/grimoire-demo/main.dart.js:93842:20)
main.dart.js:31707     at tear_off.<anonymous> (https://dargoz.github.io/grimoire-demo/main.dart.js:2992:79)
main.dart.js:31707     at OM.I (https://dargoz.github.io/grimoire-demo/main.dart.js:93834:5)
main.dart.js:31707     at ia.fd (https://dargoz.github.io/grimoire-demo/main.dart.js:78356:28)
main.dart.js:31707     at ia.mc (https://dargoz.github.io/grimoire-demo/main.dart.js:78329:9)
```

```
C:\dev\ideaProject\grimoire>flutter analyze
Analyzing grimoire...                                                   

   info - Avoid `print` calls in production code - lib\core\api\interceptor.dart:19:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\data\sources\local\local_data_source_impl.dart:38:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_document_use_case.dart:21:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_document_use_case.dart:34:7 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_document_use_case.dart:36:7 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_document_use_case.dart:38:7 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_document_use_case.dart:40:7 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_document_use_case.dart:46:9 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_document_use_case.dart:49:7 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_document_use_case.dart:54:9 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_document_use_case.dart:61:5 - avoid_print
   info - Depend on referenced packages - lib\features\wiki\domain\usecases\get_image_use_case.dart:3:8 - depend_on_referenced_packages
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\get_image_use_case.dart:20:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\domain\usecases\search_document_use_case.dart:21:9 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\controllers\document_controller.dart:32:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\controllers\document_controller.dart:36:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\controllers\document_controller.dart:78:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\controllers\document_controller.dart:108:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\controllers\file_tree_controller.dart:30:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\controllers\keyboard_controller.dart:25:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\pages\explorer_page.dart:194:31 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\pages\explorer_page.dart:201:31 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\pages\explorer_page.dart:214:15 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\admonition_syntax.dart:51:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\admonition_syntax.dart:52:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\reference_render.dart:21:3 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\table_render.dart:9:3 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\table_render.dart:10:3 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\table_render.dart:11:3 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\table_render.dart:14:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\table_render.dart:15:5 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\table_render.dart:44:3 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\table_render.dart:45:3 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\table_render.dart:46:3 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\utils\table_render.dart:47:3 - avoid_print
   info - Avoid `print` calls in production code - lib\features\wiki\presentation\widgets\breadcrumb_widget.dart:15:5 - avoid_print
   info - The operand can't be null, so the condition is always true - lib\features\wiki\presentation\widgets\custom_expansion_tile.dart:69:34 - unnecessary_null_comparison
   info - The operand can't be null, so the condition is always true - lib\features\wiki\presentation\widgets\custom_expansion_tile.dart:70:30 - unnecessary_null_comparison
   info - The declaration '_buildLeadingIcon' isn't referenced - lib\features\wiki\presentation\widgets\custom_expansion_tile.dart:358:11 - unused_element
   info - The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' -
          lib\features\wiki\presentation\widgets\section_widget_v2.dart:1:8 - unnecessary_import
   info - Avoid `print` calls in production code - test\features\wiki\data\remote\responses\commit_response_test.dart:13:5 - avoid_print
   info - Avoid `print` calls in production code - test\features\wiki\data\remote\type_sense_client_test.dart:20:5 - avoid_print
   info - Avoid `print` calls in production code - test\features\wiki\data\remote\type_sense_client_test.dart:26:5 - avoid_print
   info - Avoid `print` calls in production code - test\features\wiki\data\remote\type_sense_client_test.dart:34:5 - avoid_print
   info - Avoid `print` calls in production code - test\features\wiki\data\remote\type_sense_client_test.dart:40:5 - avoid_print
   info - Prefer const with constant constructors - test\widget_test.dart:16:29 - prefer_const_constructors

46 issues found. (ran in 16.5s)

```

```
flutter doctor -v
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.19044.1826], locale en-US)
    • Flutter version 3.3.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (2 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at C:\Users\u066757\AppData\Local\Android\sdk
    • Platform android-32, build-tools 33.0.0-rc2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32228.430
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2022.1.1
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.3739.24

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\u066757\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

C:\dev\ideaProject\grimoire>

```

</details>

**Comment by exaby73** [comment]
Hello @dargoz. Unfortunately, it's not feasible for us to find a bug in a large codebase. Lot of the times, it could be because of bugs in the user code or packages/plugins that you are using.

Please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) along with your `flutter doctor -v` output.

**Comment by dargoz** [comment]
Hi @exaby73 , actually after following your suggestion, I found out that the root cause related to the usage of getx package. I've already found the replacement but still don't get why it have a different behavior's in the hosting platform. I will get back after I make the minimal reproducible example. Thanks! 😁

**Comment by exaby73** [comment]
No issues @dargoz. If you can reproduce this issue without the use of 3rd party packages or plugins, please do share a code sample with reproduction steps. Thank you

**Comment by exaby73** [comment]
Glad you found a solution. Thanks for sharing it :)
