### ISSUE TITLE
[tool_crash] _TypeError: (#0      IOSDevice.stopApp (package:flutter_tools/src/ios/devices.dart)) type 'Null' is not a subtype of type 'IOSApp' of 'app'

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#112030]
Similar to https://github.com/flutter/flutter/issues/111877

## Command
```
flutter attach --app-id io.flutter.examples.gallery
```

## Steps to Reproduce
1. `flutter run` app on iPhone, then `d` to detach without quitting.
2. `flutter attach` to running app.
3. `q` to quit

## Logs
_TypeError: (#0      IOSDevice.stopApp (package:flutter_tools/src/ios/devices.dart))
```
#0      IOSDevice.stopApp (package:flutter_tools/src/ios/devices.dart)
#1      FlutterDevice.exitApps (package:flutter_tools/src/resident_runner.dart:358:19)
#2      ResidentRunner.exitApp (package:flutter_tools/src/resident_runner.dart:1431:67)
#3      ResidentRunner.exit (package:flutter_tools/src/resident_runner.dart:1276:11)
<asynchronous suspension>
#4      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1701:9)
<asynchronous suspension>
#5      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1760:7)
<asynchronous suspension>
```
```
[!] Flutter (Channel main, 3.4.0-19.0.pre.370, on macOS 12.6 21G115 darwin-x64, locale en-US)
    • Flutter version 3.4.0-19.0.pre.370 on channel main at /Users/magder/Projects/flutter
    ! Upstream repository git@github.com:jmagman/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:jmagman/flutter.git to dismiss this error.
    • Framework revision 29943e5f73 (26 hours ago), 2022-09-19 19:40:06 -0400
    • Engine revision 5956aa6f38
    • Dart version 2.19.0 (build 2.19.0-217.0.dev)
    • DevTools version 2.17.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/magder/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/magder/Library/Android/sdk
    • Java binary at: /Applications/Android Studio with Blaze Beta.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Users/magder/Applications/Xcode-14.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio with Blaze Beta.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/magder/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ CE (stable).app
    • Flutter plugin version 67.0.3
    • Dart plugin version 213.7371

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Purple 14 (mobile) • 00008110-0009588C2651401E • ios            • iOS 16.0 20A357
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

## Flutter Application Metadata
**Type**: malformed
**Version**: null
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info-2.0.3
integration_test
url_launcher-6.1.5
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_player-2.2.11
video_player_web-2.0.12

**Comment by jmagman** [comment]
Though when I fix the TypeError it crashes later:
```
Bad state: Cannot add event after closing
```
the event is `{\"jsonrpc\":\"2.0\",\"method\":\"streamCpuSamplesWithUserTag\",\"id\":26,\"params\":{\"userTags\":[]}}`, something is still adding to a stream.

**Comment by ClementG63** [comment]
Same problem

**Comment by christopherfujino** [comment]
On beta/3.14.0-0.1.pre with this stacktrace:

```
_TypeError: type 'Null' is not a subtype of type 'IOSApp' of 'package'
at IOSSimulator.startApp(simulators.dart:471)
at FlutterDriverService.start(drive_service.dart:178)
at <asynchronous gap>(async)
at DriveCommand.runCommand(drive.dart:270)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1323)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:212)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:339)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:285)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:115)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:90)
at <asynchronous gap>(async)
```

**Comment by vashworth** [comment]
> On beta/3.14.0-0.1.pre with this stacktrace:
> 
> ```
> _TypeError: type 'Null' is not a subtype of type 'IOSApp' of 'package'
> at IOSSimulator.startApp(simulators.dart:471)
> at FlutterDriverService.start(drive_service.dart:178)
> at <asynchronous gap>(async)
> at DriveCommand.runCommand(drive.dart:270)
> at <asynchronous gap>(async)
> at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1323)
> at <asynchronous gap>(async)
> at AppContext.run.<anonymous closure>(context.dart:150)
> at <asynchronous gap>(async)
> at CommandRunner.runCommand(command_runner.dart:212)
> at <asynchronous gap>(async)
> at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:339)
> at <asynchronous gap>(async)
> at AppContext.run.<anonymous closure>(context.dart:150)
> at <asynchronous gap>(async)
> at FlutterCommandRunner.runCommand(flutter_command_runner.dart:285)
> at <asynchronous gap>(async)
> at run.<anonymous closure>.<anonymous closure>(runner.dart:115)
> at <asynchronous gap>(async)
> at AppContext.run.<anonymous closure>(context.dart:150)
> at <asynchronous gap>(async)
> at main(executable.dart:90)
> at <asynchronous gap>(async)
> ```
> 
> Possible related fix: #111935
> 
> cc @vashworth

So I don't think this is the same issue as this Github issue. This Github issue is for `stopApp` and this stack trace is for `startApp`, I filed a new issue for this crash along with my findings: https://github.com/flutter/flutter/issues/134073

**Comment by matanlurey** [comment]
I ran into this as recently as September 4th 2024.

In my case, it's because I did not add `ios` as a platform using `flutter create`, but I have an iOS simulator (and only iOS, not an Android emualtor, etc) running. It seems like the Flutter tool thinks that I should be using iOS, and then panics (with no real error message) when things don't line up.

I could fix the problem by running `flutter create . --platform ios`

---

## Command
```sh
flutter drive lib/ping_health_main.dart
```

## Logs
_TypeError: (#0      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:471:12))
```console
#0      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:471:12)
#1      FlutterDriverService.start (package:flutter_tools/src/drive/drive_service.dart:175:29)
<asynchronous suspension>
#2      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:281:9)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```
```console
[33m[!][39m Flutter (Channel [user-branch], 3.25.0-1.0.pre.243, on macOS 14.6.1 23G93 darwin-arm64, locale en)
    [33m![39m Flutter version 3.25.0-1.0.pre.243 on channel [user-branch] at /Users/matanl/Developer/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    [33m![39m Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    [32m•[39m Framework revision 7ae629a41e (2 minutes ago), 2024-09-04 13:52:36 -0700
    [32m•[39m Engine revision e042202099
    [32m•[39m Dart version 3.6.0 (build 3.6.0-198.0.dev)
    [32m•[39m DevTools version 2.39.0
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/matanl/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/matanl/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15C500b
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m iPhone SE (3rd generation) (mobile) • D293194E-69C1-4D46-A4B6-9F104BE97FDE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    [32m•[39m macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    [32m•[39m Chrome (web)                        • chrome                               • web-javascript • Google Chrome 128.0.6613.119

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: null
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: [user-branch]
**Creation framework version**: 6a346df51b97840ff2c06805e5482be28c6dd7c4
