### ISSUE TITLE
[multicast_dns] iOS Broken after upgrade to iOS 16.0

### ISSUE THREAD

**Issue by koleto** [flutter/flutter#112180]
On a Linux board an avahi service is broadcasting:
```bash
debian@220920:/etc/avahi/services$ cat test.service 
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">

<service-group>

  <name replace-wildcards="yes">test</name>

  <service>
    <type>_http._tcp</type>
    <port>80</port>
  </service>

</service-group>
```
Here is my test application based on the **muticast_dns** example:

```dart
import 'package:flutter/material.dart';
import 'package:multicast_dns/multicast_dns.dart';

void main() {
  runApp(TestApp());
}

class TestApp extends StatelessWidget {
  Future<void> test() async {
    const String name = '_http._tcp.local';
    final MDnsClient client = MDnsClient();
    // Start the client with default options.
    await client.start();

    // Get the PTR record for the service.
    await for (final PtrResourceRecord ptr in client
        .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
      // Use the domainName from the PTR record to get the SRV record,
      // which will have the port and local hostname.
      // Note that duplicate messages may come through, especially if any
      // other mDNS queries are running elsewhere on the machine.
      await for (final SrvResourceRecord srv
          in client.lookup<SrvResourceRecord>(
              ResourceRecordQuery.service(ptr.domainName))) {
        // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
        final String bundleId =
            ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
        print('Dart observatory instance found at '
            '${srv.target}:${srv.port} for "$bundleId".');
      }
    }
    client.stop();

    print('Done.');
  }

  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Test'),
        ),
        body: Container(),
        floatingActionButton: FloatingActionButton(
          onPressed: test,
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}
```

This is what I get from Android exactly as expected.
`I/flutter (19901): Dart observatory instance found at 220920.local:80 for "test._http._tcp.local".`

It was working on iOS before I made an upgrade to iOS 16.0. and this is the output from the same app now:

```bash
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2460:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      TestApp.test (package:mdnssd/main.dart:17:10)
<asynchronous suspension>
flutter: Done.
```

I am using:  **multicast_dns: ^0.3.2+2**

```bash
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-DE)
    • Flutter version 3.3.2 on channel stable at /Users/nikolay/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (8 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nikolay/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • ANDROID_HOME = /Users/nikolay/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • SM J730F (mobile)        • 192.168.0.52:5555         • android-arm    • Android 9 (API 28)
    • Koleto’s iPhone (mobile) • 00008030-000E30123E04802E • ios            • iOS 16.0 20A362
    • macOS (desktop)          • macos                     • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment]
Hi @koleto, thanks for filing the issue.
Does this issue happen on lower iOS versions or lower `multicast_dns` plugin versions?

**Comment by koleto** [comment]
Hi @huycozy!  On my dev, iPhone 6 (iOS 15.6.1) is working without problems. The same code on another one iPhone 11 (iOS 16.0) cause the problem, and Android is OK. Since it was working with the last one, I didn't check the lower `multicast_dns` version. I will let you know about lowering the plugin version tests.

**Comment by koleto** [comment]
@huycozy I have been testing 0.3.2+1, 0.3.2, 0.3.1 and 0.3.0 on both iOS 15.6.1 and 16.0. The same test application, always the same results:

- iOS 15.6.1
 `flutter: Dart observatory instance found at 220920.local:80 for "test._http._tcp.local".` 

- iOS 16.0 
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2460:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      TestApp.test (package:mdnssd/main.dart:17:10)
<asynchronous suspension>
flutter: Done.
```

**Comment by huycozy** [comment]
@koleto thanks for doing the test on iOS and package versions. It looks like the issue is only reproducible on a specific iOS version.
Labeling this issue for further insights from the team.

**Comment by jmagman** [comment]
This was an iOS 14 thing, but does your app have the `com.apple.developer.networking.multicast` entitlement?

**Comment by koleto** [comment]
@jmagman Thanks for the info! I think I don't have one. It was enough with the entries in the **Info.plist** as required from iOS 14.+, and was working on iOS 15.+, but not in iOS 16.+
```xml
...
   <key>NSLocalNetworkUsageDescription</key>
    <string>Network usage is required for macOS/iOS communication</string>
  <key>NSBonjourServices</key>
  <array>
    <string>_http._tcp</string>
    <string>_http._tcp.local</string>
  </array>
...
```

**Comment by jmagman** [comment]
Duplicating to https://github.com/flutter/flutter/issues/112180

**Comment by huycozy** [comment]
@jmagman You are marking this issue as a duplicate of itself:)

**Comment by jmagman** [comment]
Sorry, meant this is a duplicate of https://github.com/flutter/flutter/issues/42102.
