### ISSUE TITLE
Tapping on scrollbar on web can throw Bad state: No element

### ISSUE THREAD

**Issue by stx** [flutter/flutter#112141]
Seen on Flutter 3.3.0 and Chrome 105.0.0 using the CanvasKit renderer. No idea what the cause is or how to reproduce it.

```
Bad state: No element
  at JSArray.single(org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart:1123:37)
  at RawScrollbarState._handleTrackTapDown(org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_array.dart:474:22)
  at Closure.cspForwardCall(../../../../programs/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart:109:23)
  at TapGestureRecognizer.handleTapDown.<anonymous function>(org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart:2109:9)
  at GestureRecognizer.invokeCallback(../../../../programs/flutter/packages/flutter/lib/src/gestures/tap.dart:596:51)
  at GestureRecognizer.invokeCallback[function-entry$2](../../../../programs/flutter/packages/flutter/lib/src/gestures/recognizer.dart:253:16)
  at TapGestureRecognizer.handleTapDown(../../../../programs/flutter/packages/flutter/lib/src/gestures/recognizer.dart:239:6)
  at BaseTapGestureRecognizer._checkDown(../../../../programs/flutter/packages/flutter/lib/src/gestures/tap.dart:596:11)
  at BaseTapGestureRecognizer.acceptGesture(../../../../programs/flutter/packages/flutter/lib/src/gestures/tap.dart:297:5)
  at rk.kl(../../../../programs/flutter/packages/flutter/lib/src/gestures/tap.dart:274:7)
```

**Comment by darshankawar** [comment]
I tried https://api.flutter.dev/flutter/material/Scrollbar-class.html on latest stable and master on web in debug and release mode but didn't get this exception log.

Is this coming from production @stx ?

**Comment by stx** [comment]
> I tried https://api.flutter.dev/flutter/material/Scrollbar-class.html on latest stable and master on web in debug and release mode but didn't get this exception log.
> 
> Is this coming from production @stx ?

Yep. Rare production issue.

**Comment by darshankawar** [comment]
@stx 
I tried below code sample from https://github.com/flutter/flutter/issues/78486#issuecomment-807183638 and ran it on iOS simulator and tapping on the scrollbar track gives me below exception which is very similar to the one you shared above:

```
The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1583:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1608:6)
#2      RawScrollbarState._handleTrackTapDown (package:flutter/src/widgets/scrollbar.dart:1825:12)
#3      TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:596:61)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#5      TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:596:11)
#6      BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:297:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:274:7)
#8      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:264:25)
#9      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:244:31)
(elided 2 frames from dart:async)
Handler: "onTapDown"
Recognizer: _TrackTapGestureRecognizer#d1324
  debugOwner: _CupertinoScrollbarState#16b99(tickers: tracking 2 tickers)
  state: possible
  button: 1
```

Although the code I used has `CupertinoScrollbar`, just using `Scrollbar` and running on web in canvaskit mode, gives me below error which may not be similar to the one you reported:

```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The Scrollbar's ScrollController has no ScrollPosition attached.
A Scrollbar cannot be painted without a ScrollPosition.
The Scrollbar attempted to use the provided ScrollController. This ScrollController should be
associated with the ScrollView that the Scrollbar is being applied to.When providing your own
ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
packages/flutter/src/widgets/scrollbar.dart 1583:9                                <fn>
packages/flutter/src/widgets/scrollbar.dart 1607:14                               [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1550:14                               [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 240:19                       notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 822:7                    [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 756:5                    [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 619:12                   [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 467:12                   forward
packages/flutter/src/widgets/scrollbar.dart 2058:35                               handleHover
packages/flutter/src/material/scrollbar.dart 449:11                               handleHover
packages/flutter/src/widgets/scrollbar.dart 2117:23                               <fn>
packages/flutter/src/rendering/proxy_box.dart 3261:14                             handleEvent
packages/flutter/src/gestures/binding.dart 440:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 334:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 395:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 357:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 314:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 295:7                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1175:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 243:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 147:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 630:16                                    <fn>
lib/_engine/engine/pointer_binding.dart 593:14                                    <fn>
lib/_engine/engine/pointer_binding.dart 288:16                                    loggedHandler
lib/_engine/engine/pointer_binding.dart 179:80                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 352:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 357:39  dcall

```
Using solution provided here https://github.com/flutter/flutter/issues/78486#issuecomment-807373082 gets rid of above issue. So is there a way for you to check in your code if something similar is happening with `ScrollController()` and see if solution provided in the link helps in your case ?

**Comment by stx** [comment]
@darshankawar Yes, it is your second error. No, the linked doesn't help.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open and labeling.

**Comment by yjbanov** [comment]
Does this happen in macOS desktop builds? It doesn't look web-specific.

**Comment by stx** [comment]
> Does this happen in macOS desktop builds? It doesn't look web-specific.

I don't know. We're not able to test that. Maybe @darshankawar can in his repro.

**Comment by stx** [comment]
> @stx could you please provide a sample code and clear steps to reproduce your issue? Please also include the output of `flutter doctor -v`.

https://github.com/flutter/flutter/issues/112141#issuecomment-1255835964

**Comment by mdebbar** [comment]
@stx that comment doesn't reproduce the same `Bad state: No element` error that you reported. Please share a code sample that reproduces your error.

Also, if the workaround mentioned in the other issue isn't working for you, please share your code sample with the workaround.
