### ISSUE TITLE
Google maps crashed

### ISSUE THREAD

**Issue by MuathSawalqah** [flutter/flutter#112153]
Hello there, 

I have an issue with google maps in my app, I took the same basic example from `google_maps_flutter` package on pub.dev

The map was working fine on v2.10.3 but after updating to v3.3.2 the app shut down unexpectedly.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.22000.978], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.3.4)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include
      these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
! Doctor found issues in 2 categories.
```

**`This is the debugging console:`**
<details>
<summary>Console</summary>

```
D/MapsInitializer( 2969): preferredRenderer: null
D/zzca    ( 2969): preferredRenderer: null
W/GooglePlayServicesUtil( 2969): com.microcare.microcarelocal requires the Google Play Store, but it is missing.
D/zzca    ( 2969): preferredRenderer: null
W/GooglePlayServicesUtil( 2969): com.microcare.microcarelocal requires the Google Play Store, but it is missing.
W/GooglePlayServicesUtil( 2969): com.microcare.microcarelocal requires the Google Play Store, but it is missing.
D/MapsInitializer( 2969): preferredRenderer: null
D/zzca    ( 2969): preferredRenderer: null
W/GooglePlayServicesUtil( 2969): com.microcare.microcarelocal requires the Google Play Store, but it is missing.
D/zzca    ( 2969): preferredRenderer: null
W/GooglePlayServicesUtil( 2969): com.microcare.microcarelocal requires the Google Play Store, but it is missing.
D/MapsInitializer( 2969): preferredRenderer: null
D/zzca    ( 2969): preferredRenderer: null
W/GooglePlayServicesUtil( 2969): com.microcare.microcarelocal requires the Google Play Store, but it is missing.
D/zzca    ( 2969): preferredRenderer: null
W/GooglePlayServicesUtil( 2969): com.microcare.microcarelocal requires the Google Play Store, but it is missing.
I/PlatformViewsController( 2969): Using hybrid composition for platform view: 0
D/EGL_emulation( 2969): eglMakeCurrent: 0xeff9ac60: ver 2 0 (tinfo 0xf02fbcb0) (first time)
W/Gralloc4( 2969): allocator 3.x is not supported
D/AndroidRuntime( 2969): Shutting down VM
E/AndroidRuntime( 2969): FATAL EXCEPTION: main
E/AndroidRuntime( 2969): Process: com.microcare.microcarelocal, PID: 2969
E/AndroidRuntime( 2969): java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
E/AndroidRuntime( 2969): 	at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:632)
E/AndroidRuntime( 2969): 	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:639)
E/AndroidRuntime( 2969): 	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:73)
E/AndroidRuntime( 2969): 	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:113)
E/AndroidRuntime( 2969): 	at android.graphics.Canvas.drawBitmap(Canvas.java:1600)
E/AndroidRuntime( 2969): 	at io.flutter.embedding.android.FlutterImageView.onDraw(FlutterImageView.java:241)
E/AndroidRuntime( 2969): 	at android.view.View.draw(View.java:22350)
E/AndroidRuntime( 2969): 	at android.view.View.draw(View.java:22223)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
E/AndroidRuntime( 2969): 	at android.view.View.draw(View.java:22353)
E/AndroidRuntime( 2969): 	at android.view.View.draw(View.java:22223)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
E/AndroidRuntime( 2969): 	at android.view.View.draw(View.java:22221)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
E/AndroidRuntime( 2969): 	at android.view.View.draw(View.java:22221)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
E/AndroidRuntime( 2969): 	at android.view.View.draw(View.java:22221)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
E/AndroidRuntime( 2969): 	at android.view.View.draw(View.java:22221)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
E/AndroidRuntime( 2969): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
E/AndroidRuntime( 2969): 	at android.view.View.draw(View.java:22353)
E/AndroidRuntime( 2969): 	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
E/AndroidRuntime( 2969): 	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:4221)
E/AndroidRuntime( 2969): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4129)
E/AndroidRuntime( 2969): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3828)
E/AndroidRuntime( 2969): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3099)
E/AndroidRuntime( 2969): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
E/AndroidRuntime( 2969): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
E/AndroidRuntime( 2969): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
E/AndroidRuntime( 2969): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
E/AndroidRuntime( 2969): 	at android.view.Choreographer.doFrame(Choreographer.java:731)
E/AndroidRuntime( 2969): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
E/AndroidRuntime( 2969): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 2969): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2969): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 2969): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 2969): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2969): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 2969): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 2969): Sending signal. PID: 2969 SIG: 9
Lost connection to device.
Exited (sigterm)

```
</details>

**Comment by danagbemava-nc** [comment]
Hi @MuathSawalqah, what version of `google_maps_flutter` are you using? 

Please also provide a complete minimal reproducible code sample along with steps to reproduce so that we can investigate this issue. 

Thank you

**Comment by MuathSawalqah** [comment]
Hi @danagbemava-nc 

this is the version of google_maps_flutter: v2.2.0

This is the code:

<details>
<summary>Code</summary>
```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @MuathSawalqah, what device are you experiencing this crash on? What mode are you also experiencing this bug on? 
I attempted to reproduce this but I was not able to. See the recording below. Is there any more additional information you can provide?

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/192208715-3fd1ef40-7d10-49b4-b733-6df84bedf77a.mov
</details>

<details>
<summary>code sample used</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          child: Text('Open Map'),
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (context) => const MapSample()));
          },
        ),
      ),
    );
  }
}

class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

```
</details>

**Comment by MuathSawalqah** [comment]
Hi @danagbemava-nc 
I faced this issue on the emulator, and on my personal devices:
Samsung Note 10 Plus (Android 12)
Huawei Y9s (Android 10)

Everything was working fine in flutter v2.10.3 before I updated to flutter v3.3.2

**Comment by danagbemava-nc** [comment]
Hi @MuathSawalqah, how frequently does it crash for you? 

Can you also upgrade your version of `google_maps_android` to see if this bug reproduces? You can do this by running `flutter pub upgrade`.

Also, is the crash only happening in your project or does it reproduce in a dummy project as well? 

Thank you

**Comment by MuathSawalqah** [comment]
Hi @danagbemava-nc 
the crash happened in my app, I didn't try with a dummy project.

I'll try and share the results.

**Comment by danagbemava-nc** [comment]
Kindly update when you do.

Thank you

**Comment by MuathSawalqah** [comment]
Hi @danagbemava-nc 
It's working now in my app and in the dummy app

I changed `android:hardwareAccelerated` to true instead of false

 Thank you for your valuable time.

**Comment by danagbemava-nc** [comment]
Hi @MuathSawalqah, I'm curious, in the dummy app, does it work even with `android:hardwareAccelerated=true`?

**Comment by MuathSawalqah** [comment]
Hi @danagbemava-nc 

In the dummy app, It's working **without** this `android:hardwareAccelerated=true`
In my app, it's working **with** this `android:hardwareAccelerated=true`

**Comment by danagbemava-nc** [comment]
Hi @MuathSawalqah, can you share the `AndroidManifest.xml` for both apps?

Also, are you using any packages in your app that require that you turn off hardware acceleration?
