### ISSUE TITLE
Using `FocusableActionDetector` with space as SingleActivator crashes when a text field has focus

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#112190]
When setting up a FocusableActionDetector with `LogicalKeyboardKey.space`, an exception is thrown when a text field is focused and space is typed.

This also happens with other keys (I.e. `LogicalKeyboardKey.keyA`). I suspect that both are fighting for the key event which leads to the crash.

## Steps to Reproduce

1. `flutter create bug`
2. Replace main.dart with the code sample
3. `flutter run -d chrome`
4. Focus the text field
5. Press `space`
6. The app crashes

**Expected results:** Since focus starts at the text field in this case, I'd expect the `FocusableActionDetector` to _not_ get the event?

**Actual results:** An exception is thrown

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return FocusableActionDetector(
      shortcuts: {
        const SingleActivator(LogicalKeyboardKey.space):
            RequestFocusIntent(focusNode),
      },
      child: Scaffold(
        appBar: AppBar(title: Text(widget.title)),
        body: const Center(
          child: TextField(
            decoration: InputDecoration(hintText: 'A text field'),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             16.6s
This app is linked to the debug service: ws://127.0.0.1:65421/YgGkeCgfs0s=/ws
Debug service listening on ws://127.0.0.1:65421/YgGkeCgfs0s=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:65421/YgGkeCgfs0s=
Flutter Web Bootstrap: Programmatic
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:65421/YgGkeCgfs0s=
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown while processing the key message handler:
Unexpected null value.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
packages/flutter/src/widgets/focus_traversal.dart 39:40                           _focusAndEnsureVisible
packages/flutter/src/widgets/focus_traversal.dart 1648:5                          invoke
packages/flutter/src/widgets/actions.dart 576:20                                  invokeAction
packages/flutter/src/widgets/shortcuts.dart 754:36                                handleKeypress
packages/flutter/src/widgets/shortcuts.dart 938:20                                [_handleOnKey]
packages/flutter/src/widgets/focus_manager.dart 1683:25                           [_handleKeyMessage]
packages/flutter/src/services/hardware_keyboard.dart 824:16                       [_dispatchKeyMessage]
packages/flutter/src/services/hardware_keyboard.dart 889:75                       handleRawKeyMessage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/hardware_keyboard.dart 850:51                       handleRawKeyMessage
packages/flutter/src/services/platform_channel.dart 197:49                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/platform_channel.dart 196:58                        <fn>
packages/flutter/src/services/binding.dart 387:35                                 <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/binding.dart 384:98                                 <fn>
lib/_engine/engine/platform_dispatcher.dart 1199:13                               invoke2
lib/ui/channel_buffers.dart 25:12                                                 invoke
lib/ui/channel_buffers.dart 65:7                                                  push
lib/ui/channel_buffers.dart 130:16                                                push
lib/_engine/engine/platform_dispatcher.dart 364:25                                invokeOnPlatformMessage
lib/_engine/engine/keyboard.dart 130:39                                           [_handleHtmlEvent]
lib/_engine/engine/keyboard.dart 32:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall

KeyMessage: KeyMessage([KeyDownEvent#4891c(physicalKey: PhysicalKeyboardKey#7002c(usbHidUsage:
  "0x0007002c", debugName: "Space"), logicalKey: LogicalKeyboardKey#00020(keyId: "0x00000020",
  keyLabel: " ", debugName: "Space"), character: " ", timeStamp: 0:00:44.697700)])
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.2.1 21D62 darwin-x64, locale en-BE)
    • Flutter version 3.3.2 on channel stable at /Users/navaronbracke/Documents/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision e3c29ec00c (8 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Issue is reproducible using the code sample provided above. 

It seems to be a desktop issue as I was able to reproduce this on macOS and chrome. 

Labeling for further investigation from the team. 

<details>
<summary>logs</summary>

### web

```
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:54306/Y2TTUViHIPM=/ws
Debug service listening on ws://127.0.0.1:54306/Y2TTUViHIPM=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:54306/Y2TTUViHIPM=/ws
Flutter Web Bootstrap: Programmatic
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown while processing the key message handler:
Unexpected null value.
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 546:63  nullCheck
packages/flutter/src/widgets/focus_traversal.dart 43:40                           _focusAndEnsureVisible
packages/flutter/src/widgets/focus_traversal.dart 1664:5                          invoke
packages/flutter/src/widgets/actions.dart 580:20                                  invokeAction
packages/flutter/src/widgets/shortcuts.dart 815:36                                handleKeypress
packages/flutter/src/widgets/shortcuts.dart 999:20                                [_handleOnKey]
packages/flutter/src/widgets/focus_manager.dart 1682:25                           [_handleKeyMessage]
packages/flutter/src/services/hardware_keyboard.dart 897:16                       [_dispatchKeyMessage]
packages/flutter/src/services/hardware_keyboard.dart 962:75                       handleRawKeyMessage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/hardware_keyboard.dart 923:51                       handleRawKeyMessage
packages/flutter/src/services/platform_channel.dart 214:49                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/platform_channel.dart 213:58                        <fn>
packages/flutter/src/services/binding.dart 393:35                                 <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/binding.dart 390:98                                 <fn>
lib/_engine/engine/platform_dispatcher.dart 1191:13                               invoke2
lib/ui/channel_buffers.dart 25:12                                                 invoke
lib/ui/channel_buffers.dart 65:7                                                  push
lib/ui/channel_buffers.dart 131:16                                                push
lib/_engine/engine/platform_dispatcher.dart 378:25                                invokeOnPlatformMessage
lib/_engine/engine/keyboard.dart 130:39                                           [_handleHtmlEvent]
lib/_engine/engine/keyboard.dart 12:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 352:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 357:39  dcall
KeyMessage: KeyMessage([KeyDownEvent#22050(physicalKey: PhysicalKeyboardKey#7002c(usbHidUsage:
  "0x0007002c", debugName: "Space"), logicalKey: LogicalKeyboardKey#00020(keyId: "0x00000020",
  keyLabel: " ", debugName: "Space"), character: " ", timeStamp: 0:01:43.507900)])
════════════════════════════════════════════════════════════════════════════════════════════════════
Application finished.
Exited
```

### macos

```
Multiple devices found:
macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125
[1]: macOS (macos)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-000329201AD1001E }
{ platform:macOS, arch:x86_64, id:00008103-000329201AD1001E }
Building macOS application...                                           
Syncing files to device macOS...                                   155ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:54604/QUWoShmiMdA=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:54604/QUWoShmiMdA=/

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following _CastError was thrown while processing the key message handler:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      _focusAndEnsureVisible (package:flutter/src/widgets/focus_traversal.dart:43:40)
#1      RequestFocusAction.invoke (package:flutter/src/widgets/focus_traversal.dart:1664:5)
#2      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:580:21)
#3      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:815:38)
#4      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:999:20)
#5      FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1682:32)
#6      KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:897:34)
#7      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:962:17)
#8      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:214:49)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#10     _invoke2 (dart:ui/hooks.dart:183:13)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:663:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)

KeyMessage: KeyMessage([KeyDownEvent#80511(physicalKey: PhysicalKeyboardKey#7002c(usbHidUsage:
  "0x0007002c", debugName: "Space"), logicalKey: LogicalKeyboardKey#00020(keyId: "0x00000020",
  keyLabel: " ", debugName: "Space"), character: " ", timeStamp: 28:02:09.169339)])
════════════════════════════════════════════════════════════════════════════════════════════════════

Application finished.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.2 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (9 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-28.0.pre.123, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-28.0.pre.123 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4aa27d844e (4 hours ago), 2022-09-22 21:00:22 -0700
    • Engine revision a5489ce4f9
    • Dart version 2.19.0 (build 2.19.0-229.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by goderbauer** [comment]
@gspencergoog

**Comment by gspencergoog** [comment]
This is working as intended.

The problem here is that you create a focus node, but don't attach it to anything, so it doesn't have a valid `context` to use for focusing.

To fix your sample, add the focus node to the text field like so:
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final FocusNode focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return FocusableActionDetector(
      shortcuts: <ShortcutActivator, Intent>{
        const SingleActivator(LogicalKeyboardKey.space):
            RequestFocusIntent(focusNode),
      },
      child: Scaffold(
        appBar: AppBar(title: Text(widget.title)),
        body: Center(
          child: TextField(
            focusNode: focusNode, // <---  This is the line you need to add.
            decoration: const InputDecoration(hintText: 'A text field'),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }
}
```
