### ISSUE TITLE
basic BottomNavigationBar got an "Invalid value" error

### ISSUE THREAD

**Issue by nanowang** [flutter/flutter#11226]
# repro case

```dart
import 'package:flutter/material.dart';

class DemoPage extends StatefulWidget {
  const DemoPage({ Key key }) : super(key: key);

  @override
  _DemoPageState createState() => new _DemoPageState();
}

class _DemoPageState extends State<DemoPage> {
  int _botNavBarIndex = 0;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: _buildBody(context),
      bottomNavigationBar: _buildBotNavBar(context),
    );
  }

  Widget _buildBody(BuildContext context) {
    return new Container(
      child: new Text('t'),
    );
  }

  BottomNavigationBar _buildBotNavBar(BuildContext context){
    return new BottomNavigationBar(
      items: [
        new BottomNavigationBarItem( icon: const Icon(Icons.history), title: const Text('yesterday'), backgroundColor: Colors.amber ),
        new BottomNavigationBarItem( icon: const Icon(Icons.history), title: const Text('today'), backgroundColor: Colors.red ),
        new BottomNavigationBarItem( icon: const Icon(Icons.history), title: const Text('tomorrow'), backgroundColor: Colors.yellow ),
      ],
      currentIndex: _botNavBarIndex,
      type: BottomNavigationBarType.shifting,
      onTap: (int index) {
        setState(() {
          _botNavBarIndex = index;
        });
      },
    );
  }
}
```

# log

```
I/flutter ( 1090): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1090): The following RangeError was thrown building BottomNavigationBar(dirty; state:
I/flutter ( 1090): _BottomNavigationBarState#a103d(tracking 2 tickers)):
I/flutter ( 1090): RangeError (index): Invalid value: Not in range 0..1, inclusive: 2
I/flutter ( 1090):
I/flutter ( 1090): When the exception was thrown, this was the stack:
I/flutter ( 1090): #0      List.[] (dart:core-patch/growable_array.dart:139)
I/flutter ( 1090): #1      _BottomNavigationBarState.build (package:flutter/src/material/bottom_navigation_bar.dart:348:39)
I/flutter ( 1090): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3524:27)
I/flutter ( 1090): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3434:15)
I/flutter ( 1090): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #5      StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #9      ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #11     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4151:32)
I/flutter ( 1090): #12     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4533:17)
I/flutter ( 1090): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #16     ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #20     StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #26     StatelessElement.update (package:flutter/src/widgets/framework.dart:3496:5)
I/flutter ( 1090): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #44     ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #60     StatelessElement.update (package:flutter/src/widgets/framework.dart:3496:5)
I/flutter ( 1090): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #68     StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #72     StatelessElement.update (package:flutter/src/widgets/framework.dart:3496:5)
I/flutter ( 1090): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #80     ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #90     StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #94     StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #96     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4151:32)
I/flutter ( 1090): #97     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4533:17)
I/flutter ( 1090): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #99     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:505:16)
I/flutter ( 1090): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #103    StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #107    ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #113    StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #121    StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #125    StatelessElement.update (package:flutter/src/widgets/framework.dart:3496:5)
I/flutter ( 1090): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #129    ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #133    ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #137    ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4425:14)
I/flutter ( 1090): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #143    StatelessElement.update (package:flutter/src/widgets/framework.dart:3496:5)
I/flutter ( 1090): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #147    StatelessElement.update (package:flutter/src/widgets/framework.dart:3496:5)
I/flutter ( 1090): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #151    StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #155    ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #159    ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #163    StatelessElement.update (package:flutter/src/widgets/framework.dart:3496:5)
I/flutter ( 1090): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #167    StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #171    ProxyElement.update (package:flutter/src/widgets/framework.dart:3682:5)
I/flutter ( 1090): #172    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #174    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #175    StatefulElement.update (package:flutter/src/widgets/framework.dart:3571:5)
I/flutter ( 1090): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2585:15)
I/flutter ( 1090): #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3446:16)
I/flutter ( 1090): #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3335:5)
I/flutter ( 1090): #179    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2171:33)
I/flutter ( 1090): #180    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:503:20)
I/flutter ( 1090): #181    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189:5)
I/flutter ( 1090): #182    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:688:15)
I/flutter ( 1090): #183    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:636:9)
I/flutter ( 1090): #184    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/rendering/binding.dart:275:20)
I/flutter ( 1090): #186    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
I/flutter ( 1090): #187    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
I/flutter ( 1090): #188    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
I/flutter ( 1090): (elided one frame from package dart:async-patch)
```

# doctor
```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/x/workspace/vendor/sdk/flutter
    • Framework revision 547708b327 (11 hours ago), 2017-07-13 18:08:14 -0700
    • Engine revision f56da86f98
    • Tools Dart version 1.25.0-dev.4.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/x/workspace/vendor/sdk/android-sdk-macosx
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    ✗ Your Mac needs to enabled for developer mode before using Xcode for the first time.
      Run 'sudo DevToolsSecurity -enable' or open Xcode
    ✗ Missing Xcode dependency: Python module "six".
      Install via 'pip install six' or 'sudo easy_install six'.
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew update
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew update
        brew install cocoapods
        pod setup

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices
    • Pixel • FA6B40303026 • android-arm • Android 8.0.0 (API 26)
```

# more

1. it works fine with `type` being `fixed` instead of `shifting`
2. idk if it's related, though the error msg suggest some relation with https://github.com/flutter/flutter/issues/10322

**Comment by nanowang** [comment]
aha, a `full restart` instead of `hot reload` solved the issue.

I guess that's a total dup with #10322 then.
