### ISSUE TITLE
Tree is red on invalid bbagent cipd version

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#112238]
This is affecting arm64 tasks only.

<img width="469" alt="Screen Shot 2022-09-22 at 4 31 47 PM" src="https://user-images.githubusercontent.com/54558023/191868859-aee76760-588b-4b7b-97ba-1d0f5b59ba77.png">

Example: https://chromium-swarm.appspot.com/task?id=5d8022b2665d1d10&o=true&w=true

```
38872 2022-09-22 22:28:43.058 E: internal failure: CIPD error: invalid_version_error with package infra/tools/luci/bbagent/mac-arm64, version git_revision:6585e496edc248fe871a0847bdfa00cd14a09bf7 on path None
Traceback (most recent call last):
  File "/opt/s/swarming_bot.2.zip/client/run_isolated.py", line 870, in map_and_run
    with data.install_packages_fn(run_dir, cas_client_dir,
  File "/opt/swarming-support/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/s/swarming_bot.2.zip/client/run_isolated.py", line 1211, in install_client_and_packages
    package_pins = _install_packages(run_dir, cipd_cache_dir, client,
  File "/opt/s/swarming_bot.2.zip/client/run_isolated.py", line 1135, in _install_packages
    pins = client.ensure(
  File "/opt/s/swarming_bot.2.zip/client/cipd.py", line 254, in ensure
    raise errors.NonRecoverableCipdException(status, cipd_package,
errors.NonRecoverableCipdException: CIPD error: invalid_version_error with package infra/tools/luci/bbagent/mac-arm64, version git_revision:6585e496edc248fe871a0847bdfa00cd14a09bf7 on path None
CIPD error: invalid_version_error with package infra/tools/luci/bbagent/mac-arm64, version git_revision:6585e496edc248fe871a0847bdfa00cd14a09bf7 on path None
```

**Comment by keyonghan** [comment]
Confirmed there was a new deployment, and LUCI team is working on a revert.

**Comment by keyonghan** [comment]
New deployment is reverted. 
Refreshed our swarming server all mac-arm64 bots, reran failed tests, and tree is green.
