### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by amdtechno** [flutter/flutter#112338]
## Command
```
flutter run --profile
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:133:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:54:22)
<asynchronous suspension>
#3      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:266:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.22000.978], locale en-IN)
    • Flutter version 3.3.1 on channel stable at C:\develop\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (3 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\amdte\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32505.173
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at C:\Users\amdte\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • IV2201 (mobile)   • YT95GQVCLB5LIBPN • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 105.0.1343.42

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+5
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
connectivity_plus-2.3.7
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.4
connectivity_plus_web-1.2.3
connectivity_plus_windows-1.2.2
flutter_local_notifications-9.9.1
flutter_native_splash-2.2.9
flutter_plugin_android_lifecycle-2.0.7
google_mlkit_commons-0.2.0
google_mlkit_text_recognition-0.4.0
image_picker-0.8.5+3
image_picker_android-0.8.5+3
image_picker_for_web-2.1.8
image_picker_ios-0.8.6+1
package_info_plus-1.4.3+1
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-2.1.0
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
shared_preferences-2.0.15
shared_preferences_android-2.0.13
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
speech_to_text-5.6.1
sqflite-2.1.0
url_launcher-6.1.5
url_launcher_android-6.0.19
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
workmanager-0.5.0

**Comment by darshankawar** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/108812
