### ISSUE TITLE
Attempting to delete whole words throws error

### ISSUE THREAD

**Issue by theskyblockman** [flutter/flutter#112334]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Write text in the Field
3. Use the key Control and Backspace

**Expected results:** 
The full word gets deleted
**Actual results:** 
An error is thrown by flutter
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(title: 'MyApp',home: HomePage());
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(body: TextField());
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[ +109 ms] executing: uname -m
[  +26 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +1 ms] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +246 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8b36f4fb07c70090c2188a1808710a10044592c9
[        ] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git tag --points-at 8b36f4fb07c70090c2188a1808710a10044592c9
[ +392 ms] Exit code 0 from: git tag --points-at 8b36f4fb07c70090c2188a1808710a10044592c9
[   +4 ms] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags 8b36f4fb07c70090c2188a1808710a10044592c9
[ +277 ms] Exit code 0 from: git describe --match *.*.* --long --tags 8b36f4fb07c70090c2188a1808710a10044592c9
[        ] 3.4.0-28.0.pre-40-g8b36f4fb07
[   +9 ms] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/master
[        ] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +115 ms] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +130 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +36 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1081 ms] executing: /home/theskyblockman/Android/Sdk/platform-tools/adb devices -l
[ +185 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +26 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +189 ms] Skipping pub get: version match.
[ +736 ms] Generating /home/theskyblockman/StudioProjects/testctrlback/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +241 ms] Initializing file store
[  +50 ms] Skipping target: gen_localizations
[   +6 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/theskyblockman/StudioProjects/testctrlback/.dart_tool/package_config_subset}
[  +18 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/theskyblockman/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/theskyblockman/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/theskyblockman/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.PIFRAN/flutter_tool.KHKDXH/app.dill --packages /home/theskyblockman/StudioProjects/testctrlback/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --verbosity=error --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +93 ms] Building Linux application...
[  +20 ms] <- compile package:testctrlback/main.dart
[   +3 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/theskyblockman/StudioProjects/testctrlback/linux
[ +803 ms] -- Configuring done
[  +81 ms] -- Generating done
[        ] -- Build files have been written to: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug
[  +44 ms] executing: ninja -C build/linux/x64/debug install
[ +185 ms] ninja: Entering directory `build/linux/x64/debug'
[+18738 ms] [1/5] Generating /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/theskyblockman/StudioProjects/testctrlback/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +5 ms] [   +4 ms] executing: uname -m
[        ] [   +9 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [        ] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 8b36f4fb07c70090c2188a1808710a10044592c9
[        ] [        ] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git tag --points-at 8b36f4fb07c70090c2188a1808710a10044592c9
[        ] [  +11 ms] Exit code 0 from: git tag --points-at 8b36f4fb07c70090c2188a1808710a10044592c9
[        ] [   +1 ms] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags 8b36f4fb07c70090c2188a1808710a10044592c9
[        ] [  +51 ms] Exit code 0 from: git describe --match *.*.* --long --tags 8b36f4fb07c70090c2188a1808710a10044592c9
[        ] [        ] 3.4.0-28.0.pre-40-g8b36f4fb07
[        ] [  +12 ms] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +13 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +101 ms] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/theskyblockman/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [        ] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [  +18 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +63 ms] Initializing file store
[        ] [  +14 ms] Skipping target: gen_localizations
[        ] [  +39 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/theskyblockman/StudioProjects/testctrlback/.dart_tool/package_config_subset}
[        ] [   +2 ms] unpack_linux: Starting due to {}
[        ] [+1839 ms] unpack_linux: Complete
[        ] [ +637 ms] gen_dart_plugin_registrant: Complete
[        ] [        ] kernel_snapshot: Starting due to {}
[   +2 ms] [   +7 ms] /home/theskyblockman/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/theskyblockman/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot
--sdk-root /home/theskyblockman/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --packages /home/theskyblockman/StudioProjects/testctrlback/.dart_tool/package_config.json --output-dill
/home/theskyblockman/StudioProjects/testctrlback/.dart_tool/flutter_build/b3c7fadeb1d84e55059353c7d5ca1f81/app.dill --depfile
/home/theskyblockman/StudioProjects/testctrlback/.dart_tool/flutter_build/b3c7fadeb1d84e55059353c7d5ca1f81/kernel_snapshot.d --incremental --initialize-from-dill
/home/theskyblockman/StudioProjects/testctrlback/.dart_tool/flutter_build/b3c7fadeb1d84e55059353c7d5ca1f81/app.dill --verbosity=error package:testctrlback/main.dart
[   +1 ms] [+9597 ms] kernel_snapshot: Complete
[        ] [ +597 ms] debug_bundle_linux-x64_assets: Starting due to {}
[        ] [+2852 ms] debug_bundle_linux-x64_assets: Complete
[        ] [ +471 ms] Persisting file store
[        ] [  +36 ms] Done persisting file store
[        ] [  +47 ms] build succeeded.
[   +2 ms] [  +63 ms] "flutter assemble" took 16 377ms.
[   +1 ms] [ +153 ms] ensureAnalyticsSent: 125ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[+2135 ms] [2/5] Building CXX object CMakeFiles/testctrlback.dir/flutter/generated_plugin_registrant.cc.o
[  +20 ms] [3/5] Building CXX object CMakeFiles/testctrlback.dir/my_application.cc.o
[ +431 ms] [4/5] Linking CXX executable intermediates_do_not_run/testctrlback
[        ] [4/5] Install the project...
[ +157 ms] -- Install configuration: "Debug"
[ +249 ms] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/testctrlback
[   +2 ms] -- Set runtime path of "/home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/testctrlback" to "$ORIGIN/lib"
[   +1 ms] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/icudtl.dat
[  +18 ms] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[ +511 ms] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/shaders
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/shaders/ink_sparkle.frag
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +4 ms] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +54 ms] -- Installing: /home/theskyblockman/StudioProjects/testctrlback/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[  +17 ms] Building Linux application... (completed in 23,5s)
[+1268 ms] Observatory URL on device: http://127.0.0.1:41935/ad1GRIWzDYI=/
[   +3 ms] Caching compiled dill
[ +792 ms] Connecting to service protocol: http://127.0.0.1:41935/ad1GRIWzDYI=/
[ +138 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:41935/ad1GRIWzDYI=/.
[ +285 ms] DDS is listening at http://127.0.0.1:41661/wTlnid-QClQ=/.
[ +218 ms] Successfully connected to service protocol: http://127.0.0.1:41935/ad1GRIWzDYI=/
[ +122 ms] DevFS: Creating new filesystem on the device (null)
[  +25 ms] DevFS: Created new filesystem on the device (file:///tmp/testctrlbackDSMVVG/testctrlback/)
[   +2 ms] Updating assets
[ +272 ms] Syncing files to device Linux...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:testctrlback/main.dart cf1a94f3-2c9e-45dd-9740-648221177b47
[        ] <- cf1a94f3-2c9e-45dd-9740-648221177b47
[   +1 ms] Bundle processing done.
[ +186 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 190ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0x100bf30.
[ +118 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:41661/wTlnid-QClQ=/
[+2721 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:41661/wTlnid-QClQ=/
[+6590 ms] 
                    ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following RangeError was thrown while processing the key message handler:
                    RangeError (index): Invalid value: Not in inclusive range 0..19: 20
                    
                    When the exception was thrown, this was the stack:
                    #0      String.codeUnitAt (dart:core-patch/string_patch.dart:1001:37)
                    #1      _WhitespaceBoundary.getLeadingTextBoundaryAt (package:flutter/src/widgets/editable_text.dart:4294:47)
                    #2      _ExpandedTextBoundary.getLeadingTextBoundaryAt (package:flutter/src/widgets/editable_text.dart:4341:25)
                    #3      _MixedBoundary.getLeadingTextBoundaryAt (package:flutter/src/widgets/editable_text.dart:4419:87)
                    #4      _PushTextPosition.getLeadingTextBoundaryAt (package:flutter/src/widgets/editable_text.dart:4400:30)
                    #5      TextBoundary.getTextBoundaryAt (package:flutter/src/services/text_boundary.dart:37:14)
                    #6      _DeleteTextAction.invoke (package:flutter/src/widgets/editable_text.dart:4474:22)
                    #7      _OverridableContextAction.invokeDefaultAction (package:flutter/src/widgets/actions.dart:1732:28)
                    #8      _OverridableActionMixin.invoke (package:flutter/src/widgets/actions.dart:1595:9)
                    #9      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:578:21)
                    #10     ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:815:38)
                    #11     _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:999:20)
                    #12     FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1682:32)
                    #13     KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:897:34)
                    #14     KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:962:17)
                    #15     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:214:49)
                    #16     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
                    #17     _invoke2 (dart:ui/hooks.dart:183:13)
                    #18     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
                    #19     _Channel.push (dart:ui/channel_buffers.dart:130:31)
                    #20     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
                    #21     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:667:22)
                    #22     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
                    
                    KeyMessage: KeyMessage([KeyDownEvent#f7322(physicalKey: PhysicalKeyboardKey#7002a(usbHidUsage:
                      "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#00008(keyId: "0x100000008",
                      keyLabel: "Backspace", debugName: "Backspace"), character: ", timeStamp: 10:23:37.196000)])
                    ════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
Analyzing testctrlback...                                               
No issues found! (ran in 33.3s)
```

```
[✓] Flutter (Channel master, 3.4.0-29.0.pre.40, on Fedora Linux 37 (Workstation Edition Prerelease) 5.19.10-300.fc37.x86_64, locale fr_FR.UTF-8)
    • Flutter version 3.4.0-29.0.pre.40 on channel master at /home/theskyblockman/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8b36f4fb07 (il y a 4 jours), 2022-09-20 12:17:20 -0700
    • Engine revision 48f9f1fe2d
    • Dart version 2.19.0 (build 2.19.0-222.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/theskyblockman/Android/Sdk/
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/theskyblockman/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/theskyblockman/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526
    • Flutter plugin version 70.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /home/theskyblockman/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/222.3739.54
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.3739.24

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /home/theskyblockman/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5921.22
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 37 (Workstation Edition Prerelease) 5.19.10-300.fc37.x86_64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by jason-simmons** [comment]
@chunhtai This is related to https://github.com/flutter/flutter/commit/bcc1dc6b99409d6d54b3782c7f111de0561a5ffb

**Comment by chunhtai** [comment]
This looks serious, I will fix asap

**Comment by chunhtai** [comment]
ah it is fixed by https://github.com/flutter/flutter/pull/112085 i remember I fixed some weirdness in WhiteSpaceBoundary in the pr and added tests. We should be good now
