### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by RalghRao** [flutter/flutter#112449]
## Command
```
flutter run --machine --start-paused -d edge --devtools-server-address http://127.0.0.1:9100/ --target lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.3, on Microsoft Windows [版本 10.0.19042.1889], locale zh-CN)
    • Flutter version 3.0.3 at D:\Z20070114\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (3 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Z20070114\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.71.2)
    • VS Code at C:\Users\Z20070114\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 105.0.1343.50

[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Connection terminated during handshake
    • 

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 676cefaaff197f27424942307668886253e1ec35

**Comment by danagbemava-nc** [comment]
Hi @RalghRao, this issue was previously reported and was tracked in https://github.com/flutter/flutter/issues/95916.
It has since been fixed and the fix is available on the master channel.

I'll be closing this issue since it has already been fixed on the master channel.
If you still experience this issue on the master channel or later versions of flutter, kindly file a new issue.

Thank you!
