### ISSUE TITLE
Fail to process pubsub message

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#112426]
Logs link(internal): https://pantheon.corp.google.com/logs/query;query=severity%3DERROR;cursorTimestamp=2022-09-27T00:50:18.442Z?project=flutter-dashboard

```
Bad state: No element
#0      List.single (dart:core-patch/growable_array.dart:353:22)
#1      Scheduler.processCheckRun (package:cocoon_service/src/service/scheduler.dart:441:88)
#2      GithubWebhookSubscription.post (package:cocoon_service/src/request_handlers/github/webhook_subscription.dart:90:29)
#3      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:52:28)
#4      _rootRun (dart:async/zone.dart:1398:13)
#5      _CustomZone.run (dart:async/zone.dart:1300:19)
#6      _runZoned (dart:async/zone.dart:1803:10)
#7      runZoned (dart:async/zone.dart:1746:10)
#8      RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:42:12)
#9      SubscriptionHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/subscription_handler.dart:134:31)
#10     _rootRun (dart:async/zone.dart:1398:13)
#11     _CustomZone.run (dart:async/zone.dart:1300:19)
#12     _runZoned (dart:async/zone.dart:1803:10)
#13     runZoned (dart:async/zone.dart:1746:10)
#14     SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:133:11)
<asynchronous suspension>
#15     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:275:9)
<asynchronous suspension>
```

**Comment by godofredoc** [comment]
We may need to purge the malformed messages.

**Comment by keyonghan** [comment]
@CaseyHillers Do you mind take a quick look?

**Comment by CaseyHillers** [comment]
Marking fixed. Logs don't show anything today since the fix was rolled out
