### ISSUE TITLE
dart bug or misunderstanding?

### ISSUE THREAD

**Issue by zhiliang729** [flutter/flutter#112531]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

```dart
void main() {
  Future<int> hello() async {
    // return 1;
    throw 'Hello';
  }

  void test() {
    hello().then((value) => {print('qwe')}).catchError((err) {
      print("Hello");
    });

    hello().then((value) => {1, 2, 3}).catchError((err) {
      print("Hello");
    });
  }

  test();
}
```

it crashed, it is a mistake or bug, i do not know.
I want to know why ?

**Expected results:** 

**Actual results:** 

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type
#0      _FutureListener.handleError (dart:async/future_impl.dart:181:7)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:799:13)
#3      Future._completeError (dart:async/future_impl.dart:574:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:665:7)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#6      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.6 21G115 darwin-x64, locale en-CN)
    • Flutter version 3.3.0 on channel stable at /Users/zhiliang/Desktop/work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (4 weeks ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zhiliang/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/zhiliang/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/zhiliang/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Users/zhiliang/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/222.4167.29/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
    • IntelliJ at /Users/zhiliang/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/222.3739.54/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125
    ! Error: super的 iPhone has recently restarted. Xcode will continue when super的 iPhone is unlocked. (code -14)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by zhiliang729** [comment]
hello().then((value) => {1, 2, 3}).catchError((err) {
  print("Hello");
return {};
});

it works;

**Comment by mraleph** [comment]
`(value) => {1, 2, 3}` means `(value) { return {1, 2, 3} }` - meaning that you are returning `Set<int>` rather than int.

Same applies to `(value) => { print('qwe') }` - you are returning `Set<void>`. 

I think you are confusing JS and Dart arrow function syntax. Dart syntax is `(...) => expr` or `(...) { body; }`. Not `() => {body}` like in JS. 

Furthermore, as error states: `catchError` handle should return the value that is compatible with `Future`'s type, so if you have `Future<int>` handler should return an `int` value.
