### ISSUE TITLE
firebase_analytics can't handle long parameters on Android

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#11250]
## Steps to Reproduce
```
    await analytics.logEvent(name: 'test_event', parameters: <String, dynamic>{
      'string': 'string',
      'int': 42,
      'long': 12345678910,
      'bool': true,
    });
```

## Logs

```
E/MethodChannel#firebase_analytics(24403): Failed to handle method call
E/MethodChannel#firebase_analytics(24403): java.lang.IllegalArgumentException: Unsupported value type: java.lang.Long
E/MethodChannel#firebase_analytics(24403): 	at io.flutter.firebaseanalytics.FirebaseAnalyticsPlugin.createBundleFromMap(FirebaseAnalyticsPlugin.java:139)
E/MethodChannel#firebase_analytics(24403): 	at io.flutter.firebaseanalytics.FirebaseAnalyticsPlugin.handleLogEvent(FirebaseAnalyticsPlugin.java:71)
E/MethodChannel#firebase_analytics(24403): 	at io.flutter.firebaseanalytics.FirebaseAnalyticsPlugin.onMethodCall(FirebaseAnalyticsPlugin.java:38)
E/MethodChannel#firebase_analytics(24403): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#firebase_analytics(24403): 	at io.flutter.view.FlutterView.handlePlatformMessage(FlutterView.java:643)
E/MethodChannel#firebase_analytics(24403): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#firebase_analytics(24403): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#firebase_analytics(24403): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#firebase_analytics(24403): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E/MethodChannel#firebase_analytics(24403): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#firebase_analytics(24403): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/MethodChannel#firebase_analytics(24403): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/980. Any further collaboration will be done there.
