### ISSUE TITLE
ANR android.os.MessageQueue.nativePollOnce(Native method)

### ISSUE THREAD

**Issue by DjordjeMancic97** [flutter/flutter#112541]
Hello,

We have some users who experience this crash, unclear steps to reproduce. App just won't start.
I saw somewhere that issue can be related to admob plugin, but we are not using it.

**Flutter doctor:**
```
✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.2 on channel stable at /Users/admin/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (2 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 (mobile)          • 8F1E68EE-ED4C-4D30-B651-AB593E029D7D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
**Crashlytics report:**
```
main (native): tid=1 systid=13513 
#00 pc 0x4abcc libc.so (syscall + 28)
#01 pc 0x19dd34 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 148)
#02 pc 0x3824f8 libart.so (art::JNI<false>::CallObjectMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list) + 504)
#03 pc 0x4040 libnativehelper.so (_JNIEnv::CallObjectMethod(_jobject*, _jmethodID*, ...) + 124)
#04 pc 0xe84e0 libandroid_runtime.so (android::NativeDisplayEventReceiver::dispatchVsync(long, unsigned long, unsigned int) + 48)
#05 pc 0x8e358 libgui.so (android::DisplayEventDispatcher::handleEvent(int, int, void*) + 160)
#06 pc 0x1a4c0 libutils.so (android::Looper::pollInner(int) + 896)
#07 pc 0x1a0d8 libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 112)
#08 pc 0x1156d8 libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int) + 44)
       at android.os.MessageQueue.nativePollOnce(Native method)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:183)
       at android.app.ActivityThread.main(ActivityThread.java:7701)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```

**Comment by huycozy** [comment]
@DjordjeMancic97 
Could you share the complete stack trace? (You may also find the similar stack traces from Play Developer console). Thank you!

**Comment by huycozy** [comment]
@DjordjeMancic97 
Could you share the complete stack trace? (You may also find the similar stack traces from Play Developer console). 
Also, please share the affected device information (mode, OS version).
Thank you!

**Comment by DjordjeMancic97** [comment]
@huycozy it is happening on Android 11 and 12, some of the devices are Nokia 7.2 (11), Galaxy A32 (12), Galaxy S20 FE (12), Galaxy A12 (11)... 

Full Stacktrace:

Thread
"Signal Catcher" tid=5 Runnable

  #00  pc 0x00000000005376cc  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+128)
  #01  pc 0x00000000006f0e24  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+236)
  #02  pc 0x00000000006fe6b0  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+208)
  #03  pc 0x0000000000364174  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+440)
  #04  pc 0x00000000006fce50  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+280)
  #05  pc 0x00000000006fc844  /apex/com.android.art/lib64/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+292)
  #06  pc 0x00000000006d5914  /apex/com.android.art/lib64/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+184)
  #07  pc 0x00000000006e19c0  /apex/com.android.art/lib64/libart.so (art::SignalCatcher::HandleSigQuit()+468)
  #08  pc 0x0000000000573e40  /apex/com.android.art/lib64/libart.so (art::SignalCatcher::Run(void*)+264)
  #09  pc 0x00000000000eb370  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #10  pc 0x000000000008ab70  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)


Thread
"main" tid=1 Native

  #00  pc 0x0000000000085a1c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  #01  pc 0x000000000047cc80  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+140)
  #02  pc 0x00000000005d0e50  /apex/com.android.art/lib64/libart.so (art::JNI<false>::FindClass(_JNIEnv*, char const*)+1884)
  #03  pc 0x0000000000119d70  /system/lib64/libandroid_runtime.so (android::NativeDisplayEventReceiver::dispatchVsync(long, android::PhysicalDisplayId, unsigned int, android::VsyncEventData)+76)
  #04  pc 0x00000000000af70c  /system/lib64/libgui.so (android::DisplayEventDispatcher::handleEvent(int, int, void*)+200)
  #05  pc 0x00000000000167fc  /system/lib64/libutils.so (android::Looper::pollInner(int)+908)
  #06  pc 0x0000000000016408  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
  #07  pc 0x0000000000150dd4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:335)
  at android.os.Looper.loopOnce (Looper.java:186)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8669)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)


Thread
"perfetto_hprof_listener" tid=7 Native

  #00  pc 0x00000000000d6e34  /apex/com.android.runtime/lib64/bionic/libc.so (read+4)
  #01  pc 0x000000000001d840  /apex/com.android.art/lib64/libperfetto_hprof.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ArtPlugin_Initialize::$_34> >(void*)+260)
  #02  pc 0x00000000000eb370  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #03  pc 0x000000000008ab70  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)


Thread
"Jit thread pool worker thread 0" tid=8 Native

  #00  pc 0x0000000000085a1c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  #01  pc 0x000000000047cc80  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+140)
  #02  pc 0x000000000047cb18  /apex/com.android.art/lib64/libart.so (art::ThreadPool::GetTask(art::Thread*)+120)
  #03  pc 0x0000000000619810  /apex/com.android.art/lib64/libart.so (art::ThreadPoolWorker::Run()+136)
  #04  pc 0x00000000006196f0  /apex/com.android.art/lib64/libart.so (art::ThreadPoolWorker::Callback(void*)+160)
  #05  pc 0x00000000000eb370  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #06  pc 0x000000000008ab70  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)


Thread
"HeapTaskDaemon" tid=9 Waiting

  #00  pc 0x0000000000085a1c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  #01  pc 0x000000000047cc80  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+140)
  #02  pc 0x000000000046d13c  /apex/com.android.art/lib64/libart.so (art::gc::TaskProcessor::GetTask(art::Thread*)+736)
  #03  pc 0x000000000046ce10  /apex/com.android.art/lib64/libart.so (art::gc::TaskProcessor::RunAllTasks(art::Thread*)+32)
  at dalvik.system.VMRuntime.runHeapTasks (Native method)
  at java.lang.Daemons$HeapTaskDaemon.runInternal (Daemons.java:609)
  at java.lang.Daemons$Daemon.run (Daemons.java:140)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"FinalizerDaemon" tid=10 Waiting


  at java.lang.Object.wait (Native method)
  at java.lang.Object.wait (Object.java:442)
  at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:203)
  at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:224)
  at java.lang.Daemons$FinalizerDaemon.runInternal (Daemons.java:300)
  at java.lang.Daemons$Daemon.run (Daemons.java:140)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"ReferenceQueueDaemon" tid=11 Waiting

  at java.lang.Object.wait (Native method)
  at java.lang.Object.wait (Object.java:442)
  at java.lang.Object.wait (Object.java:568)
  at java.lang.Daemons$ReferenceQueueDaemon.runInternal (Daemons.java:232)
  at java.lang.Daemons$Daemon.run (Daemons.java:140)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"FinalizerWatchdogDaemon" tid=12 Timed Waiting

  at java.lang.Thread.sleep (Native method)
  at java.lang.Thread.sleep (Thread.java:450)
  at java.lang.Thread.sleep (Thread.java:355)
  at java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos (Daemons.java:438)
  at java.lang.Daemons$FinalizerWatchdogDaemon.waitForProgress (Daemons.java:480)
  at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal (Daemons.java:369)
  at java.lang.Daemons$Daemon.run (Daemons.java:140)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"Binder:14324_1" tid=13 Native

  #00  pc 0x00000000000d70d4  /apex/com.android.runtime/lib64/bionic/libc.so (__ioctl+4)
  #01  pc 0x0000000000092b64  /apex/com.android.runtime/lib64/bionic/libc.so (ioctl+156)
  #02  pc 0x00000000000457e0  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+288)
  #03  pc 0x0000000000045ab8  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+24)
  #04  pc 0x00000000000463b8  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+68)
  #05  pc 0x000000000006c548  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+380)
  #06  pc 0x0000000000011fac  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260)
  #07  pc 0x00000000000bde88  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140)
  #08  pc 0x0000000000011864  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+404)
  #09  pc 0x00000000000eb370  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #10  pc 0x000000000008ab70  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)


Thread
"Binder:14324_2" tid=14 Native


  #00  pc 0x00000000000d70d4  /apex/com.android.runtime/lib64/bionic/libc.so (__ioctl+4)
  #01  pc 0x0000000000092b64  /apex/com.android.runtime/lib64/bionic/libc.so (ioctl+156)
  #02  pc 0x00000000000457e0  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+288)
  #03  pc 0x0000000000045ab8  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+24)
  #04  pc 0x00000000000463b8  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+68)
  #05  pc 0x000000000006c548  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+380)
  #06  pc 0x0000000000011fac  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260)
  #07  pc 0x00000000000bde88  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140)
  #08  pc 0x0000000000011864  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+404)
  #09  pc 0x00000000000eb370  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #10  pc 0x000000000008ab70  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)



Thread
"Profile Saver" tid=15 Native

  #00  pc 0x0000000000085a1c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  #01  pc 0x000000000047cc80  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+140)
  #02  pc 0x0000000000540760  /apex/com.android.art/lib64/libart.so (art::ProfileSaver::Run()+372)
  #03  pc 0x0000000000535fac  /apex/com.android.art/lib64/libart.so (art::ProfileSaver::RunProfileSaverThread(void*)+148)
  #04  pc 0x00000000000eb370  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #05  pc 0x000000000008ab70  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)


Thread
"pool-3-thread-1" tid=17 Waiting


  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:194)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2081)
  at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:433)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1063)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"Firebase-Messaging-Init" tid=18 Waiting


  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:194)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2081)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:1176)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:905)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1063)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at com.google.android.gms.common.util.concurrent.zza.run (com.google.android.gms:play-services-basement@@18.0.0:2)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"Firebase-Messaging-Topics-Io" tid=19 Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:194)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2081)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:1176)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:905)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1063)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at com.google.android.gms.common.util.concurrent.zza.run (com.google.android.gms:play-services-basement@@18.0.0:2)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"pool-9-thread-1" tid=21 Timed Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:234)
  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill (SynchronousQueue.java:463)
  at java.util.concurrent.SynchronousQueue$TransferStack.transfer (SynchronousQueue.java:361)
  at java.util.concurrent.SynchronousQueue.poll (SynchronousQueue.java:939)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1062)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"pool-11-thread-1" tid=20 Timed Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:234)
  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill (SynchronousQueue.java:463)
  at java.util.concurrent.SynchronousQueue$TransferStack.transfer (SynchronousQueue.java:361)
  at java.util.concurrent.SynchronousQueue.poll (SynchronousQueue.java:939)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1062)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"pool-12-thread-1" tid=22 Timed Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:234)
  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill (SynchronousQueue.java:463)
  at java.util.concurrent.SynchronousQueue$TransferStack.transfer (SynchronousQueue.java:361)
  at java.util.concurrent.SynchronousQueue.poll (SynchronousQueue.java:939)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1062)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)



Thread
"pool-10-thread-1" tid=23 Timed Waiting


  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:234)
  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill (SynchronousQueue.java:463)
  at java.util.concurrent.SynchronousQueue$TransferStack.transfer (SynchronousQueue.java:361)
  at java.util.concurrent.SynchronousQueue.poll (SynchronousQueue.java:939)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1062)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"ScionFrontendApi" tid=24 Timed Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:234)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2123)
  at java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:458)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1062)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"TAG" tid=25 Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:194)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2081)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:1176)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:905)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1063)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at com.google.android.gms.common.util.concurrent.zza.run (com.google.android.gms:play-services-basement@@18.0.0:2)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"Crashlytics Exception Handler1" tid=26 Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:194)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2081)
  at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:433)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1063)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun (ExecutorUtils.java:64)
  at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run (BackgroundPriorityRunnable.java:27)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"queued-work-looper" tid=27 Native

  #00  pc 0x00000000000d8098  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+8)
  #01  pc 0x0000000000016524  /system/lib64/libutils.so (android::Looper::pollInner(int)+180)
  #02  pc 0x0000000000016408  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
  #03  pc 0x0000000000150dd4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:335)
  at android.os.Looper.loopOnce (Looper.java:186)
  at android.os.Looper.loop (Looper.java:313)
  at android.os.HandlerThread.run (HandlerThread.java:67)


Thread
"com.google.firebase.crashlytics.startup1" tid=28 Waiting


  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:194)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2081)
  at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:433)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1063)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun (ExecutorUtils.java:64)
  at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run (BackgroundPriorityRunnable.java:27)
  at java.lang.Thread.run (Thread.java:1012)



Thread
"firebase-installations-executor-1" tid=29 Timed Waiting


  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:234)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2123)
  at java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:458)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1062)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"awaitEvenIfOnMainThread task continuation executor1" tid=30 Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:194)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2081)
  at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:433)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1063)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun (ExecutorUtils.java:64)
  at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run (BackgroundPriorityRunnable.java:27)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"firebase-installations-executor-2" tid=31 Timed Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:234)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2123)
  at java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:458)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1062)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)


Thread
"heartbeat-information-executor" tid=32 Timed Waiting

  at jdk.internal.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:234)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2123)
  at java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:458)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1062)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)

**Comment by huycozy** [comment]
@DjordjeMancic97 Do you use `firebase_messaging` in your app? Could you share `pubspec.yaml` file content?

**Comment by kekko7072** [comment]
+1

**Comment by DjordjeMancic97** [comment]
@huycozy Yes, these are my plugins:

firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  firebase_analytics: ^9.3.0
  firebase_remote_config: ^2.0.16
  firebase_storage: ^10.3.4
  firebase_crashlytics: ^2.8.6
 intl: ^0.17.0
  path_provider: ^2.0.11
  flutter_jailbreak_detection: ^1.8.0
  photo_view: ^0.14.0

  crypto: ^3.0.1
  elliptic: ^0.3.8
  ecdsa: ^0.0.4
  package_signature: ^0.1.2

  provider: ^6.0.3
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.15

  http_interceptor: ^1.0.2
  http: ^0.13.4

  flutter_svg: ^1.1.1+1
  pinput: ^2.2.11
  lottie: ^1.3.0
  pdfx: 2.0.1+2
  just_debounce_it: ^4.1.0
  iban: ^1.0.1
  libphonenumber: ^2.0.2
  html: ^0.15.0
  sms_autofill: ^2.2.0
  image_picker: ^0.8.5+3
  local_auth: ^2.1.0
  open_mail_app: ^0.4.5
  uni_links: ^0.5.1
  url_launcher: ^6.1.5
  flutter_inappwebview:
    git: https://github.com/CodeEagle/flutter_inappwebview
  flutter_local_notifications: ^9.6.1
  share_plus: ^4.0.10
  app_settings: ^4.1.8
  device_info_plus: ^3.2.1
  connectivity_plus: ^2.3.5
  mask_text_input_formatter: ^2.3.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  gleap_sdk: ^6.4.8
  livechatt: ^1.4.0
  facebook_app_events: ^0.16.0
  expandable_text: ^2.3.0
  cached_network_image: ^3.2.1
  yaml: ^3.1.1
  touchable: 
    git:
      url: https://github.com/N1colasVega/touchable
  

However really important note, I was luckily able to run in this error myself. This is how it happened, we had a bug which allowed user to tap multiple times on a navigation bar item and it would open multiple instances of the same screens. This same error occurred when there were multiple instances opened of webview , plugin for webview is flutter_inappwebview if it matters. We will release this fix to production and wait to see if crashlytics report with this error appears again, if it doesnt that this was the issue.

**Comment by huycozy** [comment]
>However really important note, I was luckily able to run in this error myself.

@DjordjeMancic97 
Is this issue reproducible locally? If so, can you please share the output of `flutter run -v` and a minimal code sample? 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.
Thank you!
