### ISSUE TITLE
[tool_crash] FileSystemException: Getting current working directory failed, OS Error: Operation not supported, errno = 45

### ISSUE THREAD

**Issue by wechulimaven** [flutter/flutter#112538]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Getting current working directory failed, OS Error: Operation not supported, errno = 45
```
#0      _Directory.current (dart:io/directory_impl.dart:42:7)
#1      Directory.current (dart:io/directory.dart:136:25)
#2      LocalFileSystem.currentDirectory (package:file/src/backends/local/local_file_system.dart:42:60)
#3      ErrorHandlingFileSystem.currentDirectory.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:106:49)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFileSystem.currentDirectory (package:flutter_tools/src/base/error_handling_io.dart:106:14)
#6      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1464:67)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1298:11)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.6.8 20G730 darwin-x64, locale en-KE)
    • Flutter version 3.0.1 at /Users/astroboy/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/astroboy/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Astroboy  (mobile) • 3f223dc3003a2a9bc0c9d8bfeb3bd4bf17558638 • ios            • iOS 12.5.6 16H71
    • macOS (desktop)    • macos                                    • darwin-x64     • macOS 11.6.8 20G730 darwin-x64
    • Chrome (web)       • chrome                                   • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment]
Might be related to https://github.com/flutter/flutter/issues/66235. 

Labeling for further investigation as I cannot seem to find any existing issues.
