### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists., errno = 183

### ISSUE THREAD

**Issue by davidmuhumuza** [flutter/flutter#112552]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists.
, errno = 183
```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1061:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:996:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:359:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:177:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19042.1586], locale en-US)
    • Flutter version 3.0.5 at C:\M\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\ABCD\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at C:\Users\ABCD\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • itel A16 Plus (mobile) • 0639035162005860 • android-arm    • Android 10 (API 29)
    • Windows (desktop)      • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1586]
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)             • edge             • web-javascript • Microsoft Edge 105.0.1343.50

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
url_launcher-6.1.5
url_launcher_android-6.0.19
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
ddd
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+create+link%2C+path+%3D+%27C%3A%5CM%5Cme%5Cwindows%5Cflutter%5Cephemeral%5C.plugin_symlinks%5Curl_launcher_windows%27+%28OS+Error%3A+Cannot+create+a+file+when+that+file+already+exists.%0D%0A%2C+errno+%3D+183%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Cannot+create+link%2C+OS+Error%3A+Cannot+create+a+file+when+that+file+already+exists.%0D%0A%2C+errno+%3D+183&body=%23%23+Command%0A%60%60%60%0Aflutter+pub+get%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Cannot+create+link%2C+OS+Error%3A+Cannot+create+a+file+when+that+file+already+exists.%0D%0A%2C+errno+%3D+183%0A%60%60%60%0A%230++++++_Link.throwIfError+%28dart%3Aio%2Flink.dart%3A263%3A7%29%0A%231++++++_Link.createSync+%28dart%3Aio%2Flink.dart%3A184%3A5%29%0A%232++++++ForwardingLink.createSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_link.dart%3A20%3A16%29%0A%233++++++ForwardingLink.createSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_link.dart%3A20%3A16%29%0A%234++++++_createPlatformPluginSymlinks+%28package%3Aflutter_tools%2Fsrc%2Fflutter_plugins.dart%3A1061%3A12%29%0A%235++++++createPluginSymlinks+%28package%3Aflutter_tools%2Fsrc%2Fflutter_plugins.dart%3A996%3A5%29%0A%236++++++refreshPluginsList+%28package%3Aflutter_tools%2Fsrc%2Fflutter_plugins.dart%3A1087%3A5%29%0A%3Casynchronous+suspension%3E%0A%237++++++FlutterProject.ensureReadyForPlatformSpecificTooling+%28package%3Aflutter_tools%2Fsrc%2Fproject.dart%3A359%3A5%29%0A%3Casynchronous+suspension%3E%0A%238++++++PackagesGetCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fpackages.dart%3A177%3A5%29%0A%3Casynchronous+suspension%3E%0A%239++++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1183%3A27%29%0A%3Casynchronous+suspension%3E%0A%2310+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2311+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%3Casynchronous+suspension%3E%0A%2312+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A281%3A9%29%0A%3Casynchronous+suspension%3E%0A%2313+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2314+++++FlutterCommandRunner.runCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A229%3A5%29%0A%3Casynchronous+suspension%3E%0A%2315+++++run.%3Canonymous+closure%3E.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Frunner.dart%3A62%3A9%29%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+3.0.5%2C+on+Microsoft+Windows+%5BVersion+10.0.19042.1586%5D%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+3.0.5+at+C%3A%5CM%5Cflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+f1875d570e+%283+months+ago%29%2C+2022-07-13+11%3A24%3A16+-0700%0A++++%E2%80%A2+Engine+revision+e85ea0e79c%0A++++%E2%80%A2+Dart+version+2.17.6%0A++++%E2%80%A2+DevTools+version+2.12.2%0A%0A%5B%21%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.0%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5CABCD%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%9C%97+cmdline-tools+component+is+missing%0A++++++Run+%60path%2Fto%2Fsdkmanager+--install+%22cmdline-tools%3Blatest%22%60%0A++++++See+https%3A%2F%2Fdeveloper.android.com%2Fstudio%2Fcommand-line+for+more+details.%0A++++%E2%9C%97+Android+license+status+unknown.%0A++++++Run+%60flutter+doctor+--android-licenses%60+to+accept+the+SDK+licenses.%0A++++++See+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall%2Fwindows%23android-setup+for+more+details.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files+%28x86%29%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%E2%9C%97%5D+Visual+Studio+-+develop+for+Windows%0A++++%E2%9C%97+Visual+Studio+not+installed%3B+this+is+necessary+for+Windows+development.%0A++++++Download+at+https%3A%2F%2Fvisualstudio.microsoft.com%2Fdownloads%2F.%0A++++++Please+install+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+including+all+of+its+default+components%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2021.2%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.71.2%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5CABCD%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flutter+extension+version+3.48.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%284+available%29%0A++++%E2%80%A2+itel+A16+Plus+%28mobile%29+%E2%80%A2+0639035162005860+%E2%80%A2+android-arm++++%E2%80%A2+Android+10+%28API+29%29%0A++++%E2%80%A2+Windows+%28desktop%29++++++%E2%80%A2+windows++++++++++%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.19042.1586%5D%0A++++%E2%80%A2+Chrome+%28web%29+++++++++++%E2%80%A2+chrome+++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+105.0.5195.127%0A++++%E2%80%A2+Edge+%28web%29+++++++++++++%E2%80%A2+edge+++++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+105.0.1343.50%0A%0A%5B%E2%9C%93%5D+HTTP+Host+Availability%0A++++%E2%80%A2+All+required+HTTP+hosts+are+available%0A%0A%21+Doctor+found+issues+in+2+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+f1875d570e39de09040c8f79aa13cc56baab8db1%0A%23%23%23+Plugins%0Aurl_launcher-6.1.5%0Aurl_launcher_android-6.0.19%0Aurl_launcher_ios-6.0.17%0Aurl_launcher_linux-3.0.1%0Aurl_launcher_macos-3.0.1%0Aurl_launcher_web-2.0.13%0Aurl_launcher_windows-3.0.1%0A%0A&labels=tool%2Csevere%3A+crash

**Comment by exaby73** [comment]
Hi @davidmuhumuza 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/90028
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
