### ISSUE TITLE
Flake bot is creating multiple flake bugs for same target located in staging

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#112581]
Examples:
https://github.com/flutter/flutter/issues/112555
https://github.com/flutter/flutter/issues/112081
https://github.com/flutter/flutter/issues/111569

When checking `bringup: true` targets and there is no tracking issue in `.ci.yaml`, the bot will create a new bug if the flake ratio exceeds 2%. This will cause multiple bugs filed for the same target, and will result in API failures:
```
There should not be two open issues for the same test
#0      _isOtherIssueMoreImportant (package:cocoon_service/src/request_handlers/flaky_handler_utils.dart:471:5)
#1      getExistingIssues (package:cocoon_service/src/request_handlers/flaky_handler_utils.dart:247:53)
<asynchronous suspension>
#2      FileFlakyIssueAndPR.get (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:50:53)
<asynchronous suspension>
#3      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#4      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:150:7)
<asynchronous suspension>
#5      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)
<asynchronous suspension>
#6      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:275:9)
<asynchronous suspension>
```

We should check bug existence before creating a new bug for staging targets, same as what we are doing for prod targets.

**Comment by keyonghan** [comment]
Team wants to avoid creating bugs for `bringup: true` targets. Marking as dup of https://github.com/flutter/flutter/issues/107563
