### ISSUE TITLE
[SliverAppBar] Sliver bug when adding flexibleSpace and opening DevTools

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#112631]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Run the app
3. Open dev tools
4. See error on console
5. If you add actions inside the appbar they could disappear.

**Expected results:** 
No error
**Actual results:** 
Many errors in console
Actions which can disappear when adding them
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home:  MyWidget(),
    );
  }
}

class MyWidget extends StatelessWidget {
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          const SliverAppBar(
            backgroundColor: Colors.red,
            toolbarHeight: 60,
            expandedHeight: 190,
            flexibleSpace: FlexibleSpaceBar(
              title: Text("test"),
            ),
          ),
          SliverToBoxAdapter(
            child: Container(
              height: 1000,
              width: double.maxFinite,
              color: Colors.green,
            ),
          ),
        ],
      ),
    );
  }
  }
```

</details>

<details>
  <summary>Logs</summary>

```

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
Tried to paint a RenderObject reentrantly.

The following RenderObject was already being painted when it was painted again: RenderClipPath#cfa8f relayoutBoundary=up9 NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=392.7, 0.0<=h<=174.0)
...  size: Size(392.7, 174.0)
Since this typically indicates an infinite recursion, it is disallowed.
The relevant error-causing widget was: 
  SliverAppBar SliverAppBar:file:///Users/earminjon/Documents/projects/flutter-app/lib/view/home/home.dart:89:17
When the exception was thrown, this was the stack: 
#0      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2379:9)
#1      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2392:6)
#2      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#3      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#6      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#7      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
#8      RenderStack.paint (package:flutter/src/rendering/stack.dart:627:7)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#15     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:604:11)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#19     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#20     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1951:15)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#24     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#25     RenderAnnotatedRegion.paint (package:flutter/src/rendering/proxy_box.dart:5456:13)
#26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#31     RenderSliverPersistentHeader.paint (package:flutter/src/rendering/sliver_persistent_header.dart:318:15)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#34     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:660:17)
#35     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#36     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:443:7)
#37     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:635:38)
#38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#39     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#40     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#41     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#42     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:506:19)
#43     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#44     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#45     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#46     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#47     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#51     _invoke (dart:ui/hooks.dart:151:10)
#52     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#53     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#2f5d5 relayoutBoundary=up8
...  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=392.7, 0.0<=h<=174.0)
...  size: Size(392.7, 174.0)
RenderObject: RenderSemanticsAnnotations#2f5d5 relayoutBoundary=up8
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(w=392.7, 0.0<=h<=174.0)
  size: Size(392.7, 174.0)
...  child: RenderClipPath#cfa8f relayoutBoundary=up9 NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=392.7, 0.0<=h<=174.0)
...    size: Size(392.7, 174.0)
...    child: RenderCustomPaint#8fff2 relayoutBoundary=up10 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=392.7, 0.0<=h<=174.0)
...      size: Size(392.7, 174.0)
...      painter: null
...      foregroundPainter: _ShapeBorderPainter#19cfa()
...      child: _RenderInkFeatures#f5e85 relayoutBoundary=up11 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=392.7, 0.0<=h<=174.0)
...        size: Size(392.7, 174.0)
...        child: RenderPositionedBox#4bff8 relayoutBoundary=up12 NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=392.7, 0.0<=h<=174.0)
...          size: Size(392.7, 174.0)
...          alignment: Alignment.topCenter
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
====================================================================================================

```

```
none
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale fr-FR)
    • Flutter version 3.0.5 at /Users/earminjon/fvm/versions/3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/earminjon/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/earminjon/Library/Android/Sdk
    • Java binary at: /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Users/earminjon/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4167.29/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 106.0.5249.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by exaby73** [comment]
Hello @EArminjon. Your code sample includes some constants that isn't included, namely `HOME_APPBAR_COLLAPSED_HEIGHT` and `HOME_APPBAR_HEIGHT`. Please include those as well.

**Comment by EArminjon** [comment]
@exaby73  sorry, i edited the code !

**Comment by exaby73** [comment]
With the updated code sample, I couldn't reproduce this issue. No error logs are printed in the console, devtools or the `flutter run` instance. Tested on API 33 emulator (Pixel 4 XL)

**Comment by EArminjon** [comment]
@exaby73 , I can't reproduce on Flutter 3.3.3. So the suggestion is to upgrade to it.
