### ISSUE TITLE
[go_router] 'No GoRouter found in context' after opening the deeplink

### ISSUE THREAD

**Issue by dmitry-nechaev** [flutter/flutter#112652]
Hi! 
I have a problem with getting go router via `GoRouter.of(context)` after opening a deeplink.
The error message: `No GoRouter found in context`

> I/flutter ( 9162): Caught error: 'package:go_router/src/router.dart': Failed assertion: line 280 pos 12: 'inherited != null': No GoRouter found in context
I/flutter ( 9162): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
I/flutter ( 9162): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
I/flutter ( 9162): #2      GoRouter.of (package:go_router/src/router.dart:280:12)

Inside the app everything works good.

It started after go_router upgrate to 5.0 version.

**go_router version**: 5.0.3

**flutter doctor**
```
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Version 10.0.19044.1766], locale ru-RU)
    • Flutter version 3.3.3 on channel stable at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (2 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at E:\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = E:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 4.2)
    • Android Studio at C:\Android Studio 3.2\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (4 available)
    • SM G955F (mobile) • ce03171393e1893505 • android-arm64  • Android 8.0.0 (API 26)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**main.dart**
```
import 'dart:async';

import 'package:app_links/app_links.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  late AppLinks _appLinks;
  StreamSubscription<Uri>? _linkSubscription;

  final _title = 'GoRouter Example';

  final GoRouter _router = GoRouter(
    routes: <GoRoute>[
      GoRoute(
        path: '/',
        builder: (BuildContext context, GoRouterState state) => const Page1Screen(),
        routes: <GoRoute>[
          GoRoute(
            path: 'page2',
            builder: (BuildContext context, GoRouterState state) => const Page2Screen(),
          ),
        ],
      ),
    ],
  );

  @override
  void initState() {
    super.initState();

    initDeepLinks();
  }

  @override
  void dispose() {
    _linkSubscription?.cancel();

    super.dispose();
  }

  Future<void> initDeepLinks() async {
    _appLinks = AppLinks();

    final appLink = await _appLinks.getInitialAppLink();
    if (appLink != null) {
      openAppLink(appLink);
    }

    _linkSubscription = _appLinks.uriLinkStream.listen((uri) {
      openAppLink(uri);
    });
  }

  void openAppLink(Uri uri) {
    final destination = uri.pathSegments.join('/');
    context.go('/$destination');
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MaterialApp.router(
        routerConfig: _router,
        title: _title,
      ),
    );
  }
}

class Page1Screen extends StatelessWidget {
  const Page1Screen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('Screen 1')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                onPressed: () => context.go('/page2'),
                child: const Text('Go to page 2'),
              ),
            ],
          ),
        ),
      );
}

class Page2Screen extends StatelessWidget {
  const Page2Screen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('Screen 2')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                onPressed: () => context.go('/'),
                child: const Text('Go back to home page'),
              ),
            ],
          ),
        ),
      );
}
```
You also have to add an intent filter to the activity:
```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
            android:host="link.go_router_example.com"
            android:scheme="http" />
</intent-filter>
```

The deeplink: http://link.go_router_example.com/page2

**Comment by danagbemava-nc** [comment]
Hi @dmitry-nechaev, please provide a complete minimal reproducible code sample along with steps to reproduce so that we can verify this. 

Please also provide the output of `flutter doctor -v` and the exact version of `go_router` you're using. 

Thank you

**Comment by dmitry-nechaev** [comment]
@danagbemava-nc I can use `_router.go('/$destination');` instead of `context.go('/$destination');`, but what if I don't have access to the router object? In the version 4 it was the working solution.

**Comment by danagbemava-nc** [comment]
Hi @dmitry-nechaev, have you tried using the built-in `deep_linking` that comes with flutter?

You can find the resource here https://docs.flutter.dev/development/ui/navigation/deep-linking. 

I believe with your current example, there won't be an instance of go_router in the widget at the time the deeplink is being resolved, which explains why you are getting that error.

**Comment by dmitry-nechaev** [comment]
We found another solution, but it's wierd - the current one worked fine in the previous version.
