### ISSUE TITLE
[iOS][Flutter 3.3.2][buyNonConsumable] storekit_duplicate_product_object

### ISSUE THREAD

**Issue by SalsabeelaHasan** [flutter/flutter#112784]
## Detailes: 
Flutter version: 3.3.2
in_app_purchase: 3.0.7 
iOS version: happen in all versions, in last test i use 15.7 version. 
purchase type: buyNonConsumable.
Dart version: 2.18.1.
Xcode versio: 14.0.1
CocoaPods version: 1.11.3

## Steps to Reproduce
When i did update the flutter and plugin version to the latest, i faced a problem with bought a new NonConsumable product, the  "storekit_duplicate_product_object " exception appeared every time, even when i did:
InAppPurchase.instance.restorePurchases();  and paymentWrapper.finishTransaction(transaction);  before or after the buyNonConsumable process! 

**The exception in details is:**

```
Runner[9556:364372] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Exception: error acquired doPurchase : code : storekit_duplicate_product_object
#0      GoogleSubscriptionMethods.doPurchase.<anonymous closure>.<anonymous closure> (package:main_app/util/services/in_app_purchase/subscription_products/google_subscription/google_subscription.dart:126:6)
#1      _RootZone.runUnary (dart:async/zone.dart:1653:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:165:22)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:799:13)
#5      Future._completeError (dart:async/future_impl.dart:574:5)
#6      _completeOnAsyncError (dart:async-patch/async_patch.dart:318:13)
#7      _RootZone.runBinary (dart:async/zone.dart:1658:54)
#8      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#9      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
#10     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
#11     Future._completeError (dart:async/future_impl.dart:574:5)
#12     _completeOnAsyncError (dart:async-patch/async_patch.dart:318:13)
#13     _RootZone.runBinary (dart:async/zone.dart:1658:54)
#14     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#15     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
#16     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
#17     Future._completeError (dart:async/future_impl.dart:574:5)
#18     _completeOnAsyncError (dart:async-patch/async_patch.dart:318:13)
<asynchronous suspension>
```

<details>
<summary>Code sample</summary>

```dart    
final ProductDetails productDetails = await getUserChoiceSubscriptionProductDetails(productIdUserChoice:productIdUserChoiceButton);
    final PurchaseParam purchaseParam = PurchaseParam(productDetails: productDetails);
    await InAppPurchase.instance.restorePurchases();
    InAppPurchase.instance.buyNonConsumable(purchaseParam: purchaseParam).catchError((err) async {
      if (err is PlatformException && err.code == "storekit_duplicate_product_object") {
        _refreshIOSTransactions();
          AwLogHelper.awLog('error acquired doPurchase: msg : storekit_duplicate_product_object ',level: AwLogLevelType.error);
      }else if (err is PlatformException && err.code == "storekit_finish_transaction_exception") {
          AwLogHelper.awLog('error acquired doPurchase: msg : storekit_finish_transaction_exception');
      }else{
          AwLogHelper.awLog('error acquired doPurchase: msg : $err ');
      }
      SubscriptionErrorAndSucssesDialogs.popupFailedSubscription();
      InAppPurchase.instance.restorePurchases();
      AwIapRedeem.doRedeem();
     throw Exception('error acquired doPurchase : code : ${(err as PlatformException).code ?? "no code"}');
    })
```

</details>

<details>
  <summary>Logs</summary>

```
Runner[9556:364372] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Exception: error acquired doPurchase : code : storekit_duplicate_product_object
#0      GoogleSubscriptionMethods.doPurchase.<anonymous closure>.<anonymous closure> (package:main_app/util/services/in_app_purchase/subscription_products/google_subscription/google_subscription.dart:126:6)
#1      _RootZone.runUnary (dart:async/zone.dart:1653:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:165:22)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:799:13)
#5      Future._completeError (dart:async/future_impl.dart:574:5)
#6      _completeOnAsyncError (dart:async-patch/async_patch.dart:318:13)
#7      _RootZone.runBinary (dart:async/zone.dart:1658:54)
#8      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#9      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
#10     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
#11     Future._completeError (dart:async/future_impl.dart:574:5)
#12     _completeOnAsyncError (dart:async-patch/async_patch.dart:318:13)
#13     _RootZone.runBinary (dart:async/zone.dart:1658:54)
#14     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#15     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
#16     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
#17     Future._completeError (dart:async/future_impl.dart:574:5)
#18     _completeOnAsyncError (dart:async-patch/async_patch.dart:318:13)
<asynchronous suspension>
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @SalsabeelaHasan, at what point in your application do you start listening to the purchase stream? 

Please provide the complete code sample you use to handle your in-app purchases.
Please also provide the version of `in_app_purchase_storekit` you're using. You can find this in your `pubspec.lock`

Thank you

**Comment by SalsabeelaHasan** [comment]
Hi @danagbemava-nc ,
the point i start listening to the purchase stream is in the main.dart .
in_app_purchase_storekit version is "0.3.2+2".
about the request to attach a complete code sample, i attached the code in when the exception appear in the main post (buyNonConsumable function), is there any special part to add?

**Comment by danagbemava-nc** [comment]
Hi @SalsabeelaHasan, do you call `InAppPurchase.instance.completePurchase` at any point in your application? 

>  is there any special part to add

How you handle your stream will be a good sample to add.

**Comment by SalsabeelaHasan** [comment]
Hi @danagbemava-nc , use we call the completePurchase function, in :
1- in the stream.
```
 if(purchase.pendingCompletePurchase){
         await InAppPurchase.instance.completePurchase(purchase);
      }
```
2- after the user do purchase, even if  the process done successfully or failed, is that right?

**Comment by danagbemava-nc** [comment]
Hi @SalsabeelaHasan, `restorePurchases` is usually only called once. Typically when a user has changed their device and you need to get all their purchases from a previous device os similar situations such as that. 

So to answer your question, it should not be called as part of the regular purchase flow but it should be called when you need to restore their purchases from a previous device or similar situations.

**Comment by SalsabeelaHasan** [comment]
@danagbemava-nc thank you for your detailed answer!
do you have any recommendation to enhance my code that i shared here?

**Comment by danagbemava-nc** [comment]
Hi @SalsabeelaHasan, kindly look at the in-app purchase codelab code sample. This might help you out. https://github.com/flutter/codelabs/tree/main/in_app_purchases
