### ISSUE TITLE
[tool_crash] _CastError: (#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49))

### ISSUE THREAD

**Issue by amirmhrzan123** [flutter/flutter#112745]
## Command
```
flutter gen-l10n
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49))
```
#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49)
#1      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1137:34)
#2      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1238:46)
#3      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1313:47)
#4      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
#5      GenerateLocalizationsCommand.runCommand (package:flutter_tools/src/commands/generate_localizations.dart:210:7)
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1342:12)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:94:3)
```
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-x64, locale en-NP)
    • Flutter version 3.0.5 at /Users/amirmaharjan/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/amirmaharjan/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • ANDROID_HOME = /Users/amirmaharjan/Library/Android/sdk/platform-tools/adb
    • Java binary at: /Users/amirmaharjan/Library/Java/JavaVirtualMachines/corretto-1.8.0_292/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[!] Android Studio
    • Android Studio at /Users/amirmaharjan/Library/Android/sdk/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Users/amirmaharjan/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • ONEPLUS A6003 (mobile) • 7a5c4ea8 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 106.0.5249.91

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.1+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5464c5bac742001448fe4fc0597be939379f88ea
### Plugins
audio_service-0.18.7
audio_service_web-0.1.1
audio_session-0.1.10
firebase_analytics-9.3.0
firebase_analytics_web-0.4.2
firebase_auth-3.6.2
firebase_auth_web-4.2.2
firebase_core-1.20.0
firebase_core_web-1.7.1
firebase_messaging-12.0.1
firebase_messaging_web-3.1.0
firebase_remote_config-2.0.13
firebase_remote_config_web-1.1.1
flutter_inappwebview-5.4.3+7
flutter_local_notifications-9.7.0
flutter_native_splash-2.2.7
flutter_plugin_android_lifecycle-2.0.7
flutter_stripe-4.0.0
image_picker-0.8.5+3
image_picker_android-0.8.5+2
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+6
just_audio-0.9.3
just_audio_web-0.4.7
path_provider-2.0.11
path_provider_android-2.0.17
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.2
permission_handler-8.3.0
share_plus-4.0.10+1
share_plu

**Comment by darshankawar** [comment]
@amirmhrzan123 
This has been fixed as part of https://github.com/flutter/flutter/issues/87851 so the fix should be available in the latest master and according to the tag, this should be fixed on the latest version of flutter stable.
So I suggest you upgrade to the latest version of stable and try the command again to see the fix.

I'll be closing this since it has been fixed, but if you run into this issue on the latest version of flutter stable, kindly leave a comment below and I will reopen this.

Thank you
