### ISSUE TITLE
Windows plugin template is broken

### ISSUE THREAD

**Issue by Fintasys** [flutter/flutter#112744]
## Steps to Reproduce

```
flutter create --org com.example --template=plugin --platforms=android,ios,linux,macos,windows -i swift hello
```
Then try to run example

## Logs

<details>
<summary>Cannot open include file: 'hello/hello_plugin.h': No such file or directory </summary>

```
```
[        ]  C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\CL.exe /c /IC:\Users\Stefan\Documents\GitHub\test\hello\example\windows /IC:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\ephemeral /IC:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\ephemeral\cpp_client_wrapper\include /IC:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\ephemeral\.plugin_symlinks\hello\windows\include /Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D _DEBUG /D "FLUTTER_VERSION=\"1.0.0\"" /D FLUTTER_VERSION_MAJOR=1 /D FLUTTER_VERSION_MINOR=0 /D FLUTTER_VERSION_PATCH=0 /D FLUTTER_VERSION_BUILD=0 /D NOMINMAX /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"hello_example.dir\Debug\\" /Fd"hello_example.dir\Debug\vc143.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue C:\Users\Stefan\Documents\GitHub\test\hello\example\windows\runner\flutter_window.cpp C:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\generated_plugin_registrant.cc
[  +48 ms]   flutter_window.cpp
[ +710 ms]   generated_plugin_registrant.cc
[ +194 ms] C:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\generated_plugin_registrant.cc(9,10): fatal  error C1083: Cannot open include file: 'hello/hello_plugin.h': No such file or directory [C:\Users\Stefan\Documents\GitHub\test\hello\example\build\windows\runner\hello_example.vcxproj]
[        ]   Generating Code...
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\CL.exe /c /IC:\Users\Stefan\Documents\GitHub\test\hello\example\windows /IC:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\ephemeral /IC:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\ephemeral\cpp_client_wrapper\include /IC:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\ephemeral\.plugin_symlinks\hello\windows\include /Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D _DEBUG /D "FLUTTER_VERSION=\"1.0.0\"" /D FLUTTER_VERSION_MAJOR=1 /D FLUTTER_VERSION_MINOR=0 /D FLUTTER_VERSION_PATCH=0 /D FLUTTER_VERSION_BUILD=0 /D NOMINMAX /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"hello_example.dir\Debug\\" /Fd"hello_example.dir\Debug\vc143.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue C:\Users\Stefan\Documents\GitHub\test\hello\example\windows\runner\flutter_window.cpp C:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\generated_plugin_registrant.cc
[  +48 ms]   flutter_window.cpp
[ +710 ms]   generated_plugin_registrant.cc
[ +194 ms] C:\Users\Stefan\Documents\GitHub\test\hello\example\windows\flutter\generated_plugin_registrant.cc(9,10): fatal  error C1083: Cannot open include file: 'hello/hello_plugin.h': No such file or directory [C:\Users\Stefan\Documents\GitHub\test\hello\example\build\windows\runner\hello_example.vcxproj]
[        ]   Generating Code...
Exited (sigterm)
[   +3 ms] 
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:615:9)
           <asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
#8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```
```

</details>

## Expected behavior

Can compile and run example on Windows

## Actual behavior
Build process fails with above verbose log

**Comment by danagbemava-nc** [comment]
Hi @Fintasys, please provide the output of `flutter doctor -v`.  

I used the command you specified above on the latest stable and I was able to run the example on windows just fine. 

Please also provide any additional information you can. 

Thank you

**Comment by Fintasys** [comment]
Sorry after some tries it is working again - But thx for looking into it 🙏

**Comment by nmfisher** [comment]
Note for future self - this can happen if you add Windows to an existing plugin and then manually insert the wrong class in your plugin's `pubspec.yaml`. You need to use the *CApi class, e.g.
```
plugin:
    platforms:
      windows:
        pluginClass: MyPluginCApi
```

not the `MyPlugin` class.
