### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Illegal character in path: assetsC:\Users\lenovo\AndroidStudioProjects\flutter\delivery_app\assets

### ISSUE THREAD

**Issue by samichhipa** [flutter/flutter#112835]
## Command
```
flutter --quiet assemble --no-version-check --depfile C:\Users\lenovo\AndroidStudioProjects\flutter\delivery_app\build\app\intermediates\flutter\debug/flutter_build.d --output C:\Users\lenovo\AndroidStudioProjects\flutter\delivery_app\build\app\intermediates\flutter\debug -dTargetFile=C:\Users\lenovo\AndroidStudioProjects\flutter\delivery_app\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Illegal character in path: assetsC:\Users\lenovo\AndroidStudioProjects\flutter\delivery_app\assets
```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1832:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2866:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2838:38)
#3      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:816:29)
#4      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:741:9)
#5      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:261:54)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:53:26)
<asynchronous suspension>
#7      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:64:34)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
<asynchronous suspension>
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:316:32)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.22000.978], locale en-US)
    • Flutter version 3.3.2 on channel stable at C:\Users\lenovo\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (3 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\lenovo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32901.82
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • RMX1851 (mobile)  • 477b824a • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 105.0.1343.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
cloud_firestore-3.4.9
cloud_firestore_web-2.8.8
firebase_auth-3.10.0
firebase_auth_web-4.5.0
firebase_core-1.23.0
firebase_core_web-1.7.2
firebase_crashlytics-2.8.11
firebase_database-9.1.5
firebase_database_web-0.2.1+7
firebase_messaging-13.0.3
firebase_messaging_web-3.1.5
firebase_storage-10.3.9
firebase_storage_web-3.3.7
flutter_auth_ui-3.0.0
flutter_auth_ui_web-2.0.0
flutter_braintree-2.3.1
flutter_image_compress-1.1.3
flutter_plugin_android_lifecycle-2.0.7
image_cropper-3.0.0
image_cropper_for_web-1.0.2
image_picker-0.8.5+3
image_picker_android-0.8.5+3
image_picker_for_web-2.1.8
image_picker_ios-0.8.6+1
location-4.4.0
location_web-3.1.1
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
shared_preferences-2.0.15
shared_preferences_android-2.0.13
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.3+1

**Comment by darshankawar** [comment]
@samichhipa 
This indicates there could be a formatting issue in your pubspec.yaml file. So you need to double-check and confirm the alignment/formatting is correct in that file and there are no extra spaces or any illegal char. The tool seems to correctly throw the error as it is telling that there's an illegal char in the path.

Closing from here as this doesn't seem to be a tool issue. If you disagree or think this is a genuine bug, write in comments and I'll reopen it!
