### ISSUE TITLE
[video_player] java.lang.IllegalStateException: Surface has already been released.

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#112853]
## Steps to Reproduce

I have no idea how to reproduce it but i play my `VideoPlayer` widgets inside `ListView.builder` widgets and i am disposing them as it should be done, in the `dispose` method of the item. 
This seems to be a race condition somewhere on very low performant android phones (i have tested on multiple Android devices).

In any case, the error should not be thrown in such case. 

**Expected results:** 

The error should not appear when using the `VideoPlayerController` properly.

Properly means : 
- initialize and then play the controller in the `initState` method of a `StatefulWidget` 
- Dispose the controller in the `dispose` method

It's working in my case 99% of the time except sometimes on some Android phones that have very bad performances (Flutter is not to blame for the performances)
I am using these phones especially to test the limit of my application, but they are all above Android 8. 
My app config for android is : 

```
minSdkVersion 24
targetSdkVersion 33
```

**Actual results:** 

A method called on `exoplayer` on a dead surface, probably because the `VideoPlayer` no longer exists.

<details>
<summary>Logs</summary>

```
E/VideoFrameReleaseHelper(20836): Failed to call Surface.setFrameRate
E/VideoFrameReleaseHelper(20836):   java.lang.IllegalStateException: Surface has already been released.
E/VideoFrameReleaseHelper(20836):       at android.view.Surface.checkNotReleasedLocked(Surface.java:696)
E/VideoFrameReleaseHelper(20836):       at android.view.Surface.setFrameRate(Surface.java:905)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.video.VideoFrameReleaseHelper$Api30.setSurfaceFrameRate(VideoFrameReleaseHelper.java:440)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.clearSurfaceFrameRate(VideoFrameReleaseHelper.java:380)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.onStopped(VideoFrameReleaseHelper.java:230)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onStopped(MediaCodecVideoRenderer.java:550)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.BaseRenderer.stop(BaseRenderer.java:175)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.ExoPlayerImplInternal.ensureStopped(ExoPlayerImplInternal.java:1641)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1650)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1392)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1355)
E/VideoFrameReleaseHelper(20836):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:506)
E/VideoFrameReleaseHelper(20836):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/VideoFrameReleaseHelper(20836):       at android.os.Looper.loop(Looper.java:250)
E/VideoFrameReleaseHelper(20836):       at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-x64, locale fr-FR)
    • Flutter version 3.3.3 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (6 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • moto g 8 power (mobile) • 172.16.1.195:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)         • macos             • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)            • chrome            • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @Tom3652 
Which `video_player` version are you using? We need to verify if the issue is caused by the plugin or comes from your implementation.

So, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. In order not to spend a lot of time creating a sample code, you can edit [video_player's example](https://github.com/flutter/plugins/tree/main/packages/video_player/video_player/example).

And please provide list of affected device information as well (model, OS version). Thank you!
