### ISSUE TITLE
`flutter test` always loading and timeout after minutes.

### ISSUE THREAD

**Issue by johz-chen** [flutter/flutter#113082]
Just run `flutter test` and it will reproduce, I don't know how to trigger the problem, but every time after restarting the computer, it is solved, and it reappears in the next day.

Thanks.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on Mac OS X 10.15.7 19H2026 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
[✓] VS Code (version 1.71.2)
[✓] VS Code (version 1.48.2)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

here is the log:

```
flutter test --verbose
[  +75 ms] executing: sysctl hw.optional.arm64
[  +12 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +5 ms] executing: [/usr/local/Caskroom/flutter/3.0.5/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] executing: [/usr/local/Caskroom/flutter/3.0.5/flutter/] git tag --points-at
f1875d570e39de09040c8f79aa13cc56baab8db1
[  +13 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] 3.0.5
[   +8 ms] executing: [/usr/local/Caskroom/flutter/3.0.5/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/Caskroom/flutter/3.0.5/flutter/] git ls-remote --get-url
origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +87 ms] executing: [/usr/local/Caskroom/flutter/3.0.5/flutter/] git rev-parse --abbrev-ref
HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +4 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.7
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19H2026
[        ] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +51 ms] Found 3 files which will be executed as Widget Tests.
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +44 ms] Skipping pub get: version match.
[  +40 ms] Found plugin path_provider at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0
.11/
[   +4 ms] Found plugin path_provider_android at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_and
roid-2.0.20/
[   +3 ms] Found plugin path_provider_ios at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios
-2.0.11/
[   +2 ms] Found plugin path_provider_linux at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_lin
ux-2.1.7/
[   +1 ms] Found plugin path_provider_macos at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_mac
os-2.0.6/
[   +2 ms] Found plugin path_provider_windows at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_win
dows-2.1.3/
[   +5 ms] Found plugin sqflite at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.3+1/
[  +31 ms] Found plugin integration_test at
/usr/local/Caskroom/flutter/3.0.5/flutter/packages/integration_test/
[  +49 ms] Found plugin path_provider at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0
.11/
[   +1 ms] Found plugin path_provider_android at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_and
roid-2.0.20/
[   +1 ms] Found plugin path_provider_ios at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios
-2.0.11/
[        ] Found plugin path_provider_linux at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_lin
ux-2.1.7/
[   +1 ms] Found plugin path_provider_macos at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_mac
os-2.0.6/
[   +1 ms] Found plugin path_provider_windows at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_win
dows-2.1.3/
[   +3 ms] Found plugin sqflite at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.3+1/
[  +12 ms] Found plugin integration_test at
/usr/local/Caskroom/flutter/3.0.5/flutter/packages/integration_test/
[  +57 ms] Generating
/path/to/project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegi
strant.java
[  +32 ms] executing: sysctl hw.optional.arm64
[   +2 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +549 ms] Exit code 0 from: xcrun xcodebuild -version
[   +1 ms] Xcode 12.4
           Build version 12D4e
[ +128 ms] Manifest contained wildcard assets. Inserting missing file into build graph to
force rerun. for more information see #56466.
[   +8 ms] running test package with arguments: [-r, compact, --timeout, 30s,
--concurrency=14, --chain-stack-traces, --,
/path/to/project/test/database/entry_test.dart,
/path/to/project/test/service/crypto_test.dart,
/path/to/project/test/service/password_test.dart]
00:00 +0: loading /path/to/project/test/database/entry_test.dart                [ +174 ms] test 0: starting test /path/to/project/test/database/entry_test.dart
[   +5 ms] Stopping scan for flutter_test_config.dart; found project root at
/Users/chenjunxu/data/www/app
[   +3 ms] Compiler will use the following file as its incremental dill file:
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_compiler.pI
cZ0p/output.dill
[        ] Listening to compiler controller...
[  +11 ms] Compiling
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.fP89eO/listener.dart
[  +22 ms] Found plugin path_provider at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0
.11/
[   +1 ms] Found plugin path_provider_android at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_and
roid-2.0.20/
[   +2 ms] Found plugin path_provider_ios at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios
-2.0.11/
[   +1 ms] Found plugin path_provider_linux at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_lin
ux-2.1.7/
[   +1 ms] Found plugin path_provider_macos at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_mac
os-2.0.6/
[   +1 ms] Found plugin path_provider_windows at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_win
dows-2.1.3/
[   +2 ms] Found plugin sqflite at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.3+1/
[  +13 ms] Found plugin integration_test at
/usr/local/Caskroom/flutter/3.0.5/flutter/packages/integration_test/
[  +13 ms] /usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dar
t.snapshot --sdk-root
/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/artifacts/engine/common/flutter_patched_sd
k/ --incremental --no-print-incremental-dependencies --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_compiler.pI
cZ0p/output.dill --packages /path/to/project/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--initialize-from-dill
/path/to/project/build/test_cache/build/c075001b96339384a97db4862b8ab8db.cache.di
ll.track.dill --source
/path/to/project/.dart_tool/flutter_build/dart_plugin_registrant.dart --source
package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///path/to/project/.dart_tool/flutter_build
/dart_plugin_registrant.dart
[   +3 ms] test 1: starting test /path/to/project/test/service/crypto_test.dart
[   +1 ms] Stopping scan for flutter_test_config.dart; found project root at
/Users/chenjunxu/data/www/app
[        ] test 2: starting test /path/to/project/test/service/password_test.dart
[   +1 ms] Stopping scan for flutter_test_config.dart; found project root at
/Users/chenjunxu/data/www/app
[  +35 ms] <- compile
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.fP89eO/listener.dart
00:01 +0: loading /path/to/project/test/database/entry_test.dart                [+1566 ms] <- accept
[        ] <- reset
[        ] Compiling
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.fP89eO/listener.dart took 1667ms
[        ] Compiling
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.4VEDCt/listener.dart
[        ] test 0: starting test device
[   +4 ms] test 0: awaiting connection to test device
[  +14 ms] Found plugin path_provider at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0
.11/
[   +1 ms] Found plugin path_provider_android at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_and
roid-2.0.20/
[        ] Found plugin path_provider_ios at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios
-2.0.11/
[        ] Found plugin path_provider_linux at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_lin
ux-2.1.7/
[        ] Found plugin path_provider_macos at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_mac
os-2.0.6/
[   +1 ms] Found plugin path_provider_windows at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_win
dows-2.1.3/
[   +2 ms] Found plugin sqflite at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.3+1/
[   +8 ms] Found plugin integration_test at
/usr/local/Caskroom/flutter/3.0.5/flutter/packages/integration_test/
[   +2 ms] test 0: Observatory uri is not available
[   +4 ms] test 0: test harness socket server is running at port:51172
[   +3 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +1 ms] Using this directory for fonts configuration:
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_fonts.egZUN
Y
[        ] test 0: Starting flutter_tester process with
command=[/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/artifacts/engine/darwin-x64/flutt
er_tester, --disable-observatory, --enable-checked-mode, --verify-entry-points,
--enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling,
--non-interactive, --use-test-fonts,
--packages=/path/to/project/.dart_tool/package_config.json,
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_listener.fP
89eO/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_fonts.egZUN
Y/fonts.conf, SERVER_PORT: 51172, APP_NAME: teampassword, UNIT_TEST_ASSETS:
/path/to/project/build/unit_test_assets}
[   +3 ms] <- recompile
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.4VEDCt/listener.dart 049e6e64-fe6f-4713-ae75-7cbc6d18206c
[        ]
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.4VEDCt/listener.dart
[        ]
file:///path/to/project/.dart_tool/flutter_build/dart_plugin_registrant.dart
[        ] <- 049e6e64-fe6f-4713-ae75-7cbc6d18206c
[   +3 ms] test 0: Started flutter_tester process at pid 53102
[ +188 ms] <- accept
[        ] <- reset
[        ] Compiling
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.4VEDCt/listener.dart took 248ms
[        ] Compiling
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.6yGKm2/listener.dart
[        ] test 1: starting test device
[        ] test 1: awaiting connection to test device
[   +9 ms] Found plugin path_provider at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0
.11/
[        ] Found plugin path_provider_android at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_and
roid-2.0.20/
[        ] Found plugin path_provider_ios at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios
-2.0.11/
[        ] Found plugin path_provider_linux at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_lin
ux-2.1.7/
[        ] Found plugin path_provider_macos at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_mac
os-2.0.6/
[        ] Found plugin path_provider_windows at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_win
dows-2.1.3/
[   +1 ms] Found plugin sqflite at
/usr/local/Caskroom/flutter/3.0.5/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.3+1/
[   +6 ms] Found plugin integration_test at
/usr/local/Caskroom/flutter/3.0.5/flutter/packages/integration_test/
[   +1 ms] test 1: Observatory uri is not available
[        ] test 1: test harness socket server is running at port:51175
[   +3 ms] executing: sysctl hw.optional.arm64
[   +2 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] test 1: Starting flutter_tester process with
command=[/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/artifacts/engine/darwin-x64/flutt
er_tester, --disable-observatory, --enable-checked-mode, --verify-entry-points,
--enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling,
--non-interactive, --use-test-fonts,
--packages=/path/to/project/.dart_tool/package_config.json,
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_listener.4V
EDCt/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_fonts.egZUN
Y/fonts.conf, SERVER_PORT: 51175, APP_NAME: teampassword, UNIT_TEST_ASSETS:
/path/to/project/build/unit_test_assets}
[   +1 ms] <- recompile
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.6yGKm2/listener.dart 284b450f-f76f-47c2-ac24-14f1974286d8
[        ]
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.6yGKm2/listener.dart
[        ]
file:///path/to/project/.dart_tool/flutter_build/dart_plugin_registrant.dart
[        ] <- 284b450f-f76f-47c2-ac24-14f1974286d8
[   +1 ms] test 1: Started flutter_tester process at pid 53106
00:02 +0: loading /path/to/project/test/database/entry_test.dart                [ +170 ms] <- accept
[        ] <- reset
[        ] Compiling
file:///var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_list
ener.6yGKm2/listener.dart took 203ms
[        ] test 2: starting test device
[        ] test 2: awaiting connection to test device
[        ] test 2: Observatory uri is not available
[        ] test 2: test harness socket server is running at port:51176
[   +3 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] test 2: Starting flutter_tester process with
command=[/usr/local/Caskroom/flutter/3.0.5/flutter/bin/cache/artifacts/engine/darwin-x64/flutt
er_tester, --disable-observatory, --enable-checked-mode, --verify-entry-points,
--enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling,
--non-interactive, --use-test-fonts,
--packages=/path/to/project/.dart_tool/package_config.json,
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_listener.6y
GKm2/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_fonts.egZUN
Y/fonts.conf, SERVER_PORT: 51176, APP_NAME: teampassword, UNIT_TEST_ASSETS:
/path/to/project/build/unit_test_assets}
[   +2 ms] test 2: Started flutter_tester process at pid 53109
[ +191 ms] test 0: connected to test device, now awaiting test result
[        ] test 0: Waiting for test harness or tests to finish
[ +155 ms] test 1: connected to test device, now awaiting test result
[        ] test 1: Waiting for test harness or tests to finish
[ +173 ms] test 2: connected to test device, now awaiting test result
[        ] test 2: Waiting for test harness or tests to finish
12:00 +0 -1: loading /path/to/project/test/database/entry_test.dart [E]
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 334:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1418:47                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 332:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 288:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1426:13                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 287:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 192:12      _RawReceivePortImpl._handleMessage

12:00 +0 -2: loading /path/to/project/test/service/crypto_test.dart [E]
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 334:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1418:47                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 332:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 288:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1426:13                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 287:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 192:12      _RawReceivePortImpl._handleMessage

12:00 +0 -3: loading /path/to/project/test/service/password_test.dart [E]
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 334:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1418:47                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 332:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 288:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1426:13                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 287:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 192:12      _RawReceivePortImpl._handleMessage

12:00 +0 -3: Some tests failed.
[+717426 ms] Deleting
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_compiler.pI
cZ0p...
[   +5 ms] killing pid 53091
[  +40 ms] Deleting
/var/folders/6p/r9djvd5n1_x2k35d_cdjd8l40000gn/T/flutter_tools.QzeiAB/flutter_test_fonts.egZUN
Y...
[   +4 ms] test package returned with exit code 1
[  +11 ms] "flutter test" took 721,454ms.
[   +6 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:471:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +257 ms] ensureAnalyticsSent: 253ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

**Comment by darshankawar** [comment]
Based on the logs,it is similar to https://github.com/flutter/flutter/issues/105913, so please follow-up in it for further updates.
Closing as duplicate.
