### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by nikkolasedi** [flutter/flutter#113019]
## Command
```
flutter run -d Chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1041:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:866:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:753:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:261:54)
<asynchronous suspension>
#8      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:470:26)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19043.2006], locale en-GB)
    • Flutter version 3.3.4 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (28 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Nikkolas Edi P\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.2)
    • VS Code at C:\Users\Nikkolas Edi P\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • Redmi Note 8 Pro (mobile) • rcypyxrszplz8tfe • android-arm64  • Android 11 (API 30)
    • Windows (desktop)         • windows          • windows-x64    • Microsoft Windows [Version 10.0.19043.2006]
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 105.0.5195.128
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 103.0.1264.44

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: fb3c8ea2b44a20317dd8b3c9e48bf47650fccf85
### Plugins
audio_session-0.1.10
flutter_plugin_android_lifecycle-2.0.7
google_maps_flutter-2.2.1
google_maps_flutter_android-2.3.2
google_maps_flutter_ios-2.1.12
just_audio-0.9.29
just_audio_web-0.4.7
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
shared_preferences-2.0.15
shared_preferences_android-2.0.13
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.3+1
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.1.6
url_launcher_android-6.0.19
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_player-2.4.7
video_player_android-2.3.9
video_player_avfoundation-2.3.6
video_player_web-2.0.12
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.4
webview_flutter_android-2.10.3
webview_flutter_wkwebview-2.9.5

**Comment by huycozy** [comment]
I don't see a similar issue present already, so labeling it for further investigation from the team.
