### ISSUE TITLE
Image widget with errorBuilder crash when push navigator

### ISSUE THREAD

**Issue by 623637646** [flutter/flutter#113015]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Click "Next Page" to enter the next page.

**Expected results:** 

No crash with the invalid URL because the Image widget has `errorBuilder`.

**Actual results:** 
Check the console. It shows the crash as below.

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 404, https://www.google.com/invalid_image.jpg

When the exception was thrown, this was the stack:
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:117:9)
<asynchronous suspension>

Image provider: NetworkImage("https://www.google.com/invalid_image.jpg", scale: 1.0)
Image key: NetworkImage("https://www.google.com/invalid_image.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: FirstPage(),
    ),
  );
}

class FirstPage extends StatelessWidget {
  const FirstPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('First Page'),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (context) {
                    return const SecondPage();
                  },
                ),
              );
            },
            child: const Text(
              "Next Page",
              style: TextStyle(color: Colors.white),
            ),
          ),
        ],
      ),
      body: Center(
        child: Image.network(
          'https://www.google.com/invalid_image.jpg',
          errorBuilder: (context, error, stackTrace) {
            return const Icon(Icons.error);
          },
        ),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Page'),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
flutter run
Multiple devices found:
sdk gphone64 arm64 (mobile)    • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
iPad (9th generation) (mobile) • BFED4B50-C1A4-43DA-A305-B7049D3F27A9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5
(simulator)
Chrome (web)                   • chrome                               • web-javascript • Google Chrome 106.0.5249.103
[1]: sdk gphone64 arm64 (emulator-5554)
[2]: iPad (9th generation) (BFED4B50-C1A4-43DA-A305-B7049D3F27A9)
[3]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Using hardware rendering with device sdk gphone64 arm64. If you notice graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Running Gradle task 'assembleDebug'...                              6.0s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Syncing files to device sdk gphone64 arm64...                       36ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on sdk gphone64 arm64 is available at: http://127.0.0.1:59493/10wOfd2HDIw=/
The Flutter DevTools debugger and profiler on sdk gphone64 arm64 is available at:
http://127.0.0.1:9103?uri=http://127.0.0.1:59493/10wOfd2HDIw=/
E/SurfaceSyncer( 9176): Failed to find sync for id=0
W/Parcel  ( 9176): Expecting binder but got null!
D/EGL_emulation( 9176): app_time_stats: avg=1212.28ms min=2.04ms max=3535.14ms count=3

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 404, https://www.google.com/invalid_image.jpg

When the exception was thrown, this was the stack:
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:117:9)
<asynchronous suspension>

Image provider: NetworkImage("https://www.google.com/invalid_image.jpg", scale: 1.0)
Image key: NetworkImage("https://www.google.com/invalid_image.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
D/EGL_emulation( 9176): app_time_stats: avg=80.86ms min=6.27ms max=1339.54ms count=21
Application finished.
```

```
flutter analyze
Analyzing FlutterTest...                                                
No issues found! (ran in 1.3s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale en-SG)
    • Flutter version 3.3.3 on channel stable at /Users/wangyy/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (8 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/wangyy/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)    • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPad (9th generation) (mobile) • BFED4B50-C1A4-43DA-A305-B7049D3F27A9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                   • chrome                               • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
There's an existing issue tracking this bug in https://github.com/flutter/flutter/issues/97077. 

Kindly follow up in the issue linked above for updates. Please upvote the original issue. 

Closing this as duplicate. 

Thank you
