### ISSUE TITLE
Clearing all children in `ListView.custom` throws error

### ISSUE THREAD

**Issue by iamsahilsonawane** [flutter/flutter#113156]
When using `ListView.custom` if x children are available in the list (where x > 0), for a condition where no elements are to be shown and `null` is passed for the first item [conditionally], the assertion fails and thus the error is thrown.

This is a major issue in Riverpod pagination suggestion in the official examples. 

I am not quite sure if this is expected behavior or not. If it is, is there any workaround to this?

## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 
Should not throw the error.

**Actual results:** 
Throws error. 

<details>
<summary>Code sample</summary>

```dart
class ListViewIssue extends StatefulWidget {
  const ListViewIssue({Key? key}) : super(key: key);

  @override
  State<ListViewIssue> createState() => _ListViewIssueState();
}

class _ListViewIssueState extends State<ListViewIssue> {
  bool limit = false;

  @override
  void initState() {
    Future.delayed(const Duration(seconds: 2), () {
      setState(() => limit = true);
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.custom(
        padding: const EdgeInsets.only(top: 30),
        childrenDelegate: SliverChildBuilderDelegate((context, index) {
          if (limit && index == 0) {
            return null;
          }
          return Text(index.toString());
        }),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54555/0jCUHDU_XCk=/ws
I/experimentatio(12902): ProcessProfilingInfo new_methods=966 is saved saved_to_disk=1 resolve_classes_delay=8000

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_list.dart': Failed assertion: line 186 pos 16: 'earliestUsefulChild != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
ListView
When the exception was thrown, this was the stack
#2      RenderSliverList.performLayout
#3      RenderObject.layout
#4      RenderSliverEdgeInsetsPadding.performLayout
#5      RenderSliverPadding.performLayout
#6      RenderObject.layout
#7      RenderViewportBase.layoutChildSequence
#8      RenderViewport._attemptLayout
#9      RenderViewport.performLayout
#10     RenderObject._layoutWithoutResize
#11     PipelineOwner.flushLayout
#12     RendererBinding.drawFrame
#13     WidgetsBinding.drawFrame
#14     RendererBinding._handlePersistentFrameCallback
#15     SchedulerBinding._invokeFrameCallback
#16     SchedulerBinding.handleDrawFrame
#17     SchedulerBinding._handleDrawFrame
#21     _invoke (dart:ui/hooks.dart:151:10)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#23     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderSliverList#5f0b2 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderSliverList#5f0b2 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
    needs compositing
    parentData: paintOffset=Offset(0.0, 30.0) (can use size)
    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 826.7, crossAxisExtent: 392.7, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 856.7, remainingCacheExtent: 1076.7, cacheOrigin: 0.0)
    geometry: SliverGeometry(scrollExtent: Infinity, paintExtent: 826.7, maxPaintExtent: Infinity, hasVisualOverflow: true, cacheExtent: 1076.7)
        scrollExtent: Infinity
        paintExtent: 826.7
        maxPaintExtent: Infinity
        hasVisualOverflow: true
        cacheExtent: 1076.7
    currently live children: 1 to 67
    child with index 1: RenderIndexedSemantics#bc38a relayoutBoundary=up3
        needs compositing
        parentData: index=1; layoutOffset=0.0 (can use size)
        constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
        size: Size(392.7, 16.0)
        index: 1
        child: RenderRepaintBoundary#5684f relayoutBoundary=up4
            needs compositing
            parentData: <none> (can use size)
            constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
            layer: OffsetLayer#df5fd
                engine layer: OffsetEngineLayer#03d2d
                handles: 2
                offset: Offset(0.0, 46.0)
            size: Size(392.7, 16.0)
            metrics: 0.0% useful (1 bad vs 0 good)
            diagnosis: insufficient data to draw conclusion (less than five repaints)
            child: RenderParagraph#2b0e2 relayoutBoundary=up5
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
                size: Size(392.7, 16.0)
                textAlign: start
                textDirection: ltr
                softWrap: wrapping at box width
                overflow: clip
                locale: en_US
                maxLines: unlimited
                text: TextSpan
                    debugLabel: (englishLike bodyMedium 2014).merge(blackMountainView bodyMedium)
                    inherit: false
                    color: Color(0xdd000000)
                    family: Roboto
                    size: 14.0
                    weight: 400
                    baseline: alphabetic
                    decoration: TextDecoration.none
                    "1"
    child with index 2: RenderIndexedSemantics#522ce relayoutBoundary=up3
        needs compositing
        parentData: index=2; layoutOffset=32.0 (can use size)
        constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
        size: Size(392.7, 16.0)
        index: 2
        child: RenderRepaintBoundary#ced6c relayoutBoundary=up4
            needs compositing
            parentData: <none> (can use size)
            constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
            layer: OffsetLayer#940bb
                engine layer: OffsetEngineLayer#9db50
                handles: 2
                offset: Offset(0.0, 62.0)
            size: Size(392.7, 16.0)
            metrics: 0.0% useful (1 bad vs 0 good)
            diagnosis: insufficient data to draw conclusion (less than five repaints)
            child: RenderParagraph#6a220 relayoutBoundary=up5
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
                size: Size(392.7, 16.0)
                textAlign: start
                textDirection: ltr
                softWrap: wrapping at box width
                overflow: clip
                locale: en_US
                maxLines: unlimited
                text: TextSpan
                    debugLabel: (englishLike bodyMedium 2014).merge(blackMountainView bodyMedium)
                    inherit: false
                    color: Color(0xdd000000)
                    family: Roboto
                    size: 14.0
                    weight: 400
                    baseline: alphabetic
                    decoration: TextDecoration.none
                    "2"
    child with index 3: RenderIndexedSemantics#a1bee relayoutBoundary=up3
        needs compositing
        parentData: index=3; layoutOffset=48.0 (can use size)
        constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
        size: Size(392.7, 16.0)
        index: 3
        child: RenderRepaintBoundary#ec640 relayoutBoundary=up4
            needs compositing
            parentData: <none> (can use size)
            constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
            layer: OffsetLayer#54971
                engine layer: OffsetEngineLayer#e6b7d
                handles: 2
                offset: Offset(0.0, 78.0)
            size: Size(392.7, 16.0)
            metrics: 0.0% useful (1 bad vs 0 good)
            diagnosis: insufficient data to draw conclusion (less than five repaints)
            child: RenderParagraph#4a34a relayoutBoundary=up5
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
                size: Size(392.7, 16.0)
                textAlign: start
                textDirection: ltr
                softWrap: wrapping at box width
                overflow: clip
                locale: en_US
                maxLines: unlimited
                text: TextSpan
                    debugLabel: (englishLike bodyMedium 2014).merge(blackMountainView bodyMedium)
                    inherit: false
                    color: Color(0xdd000000)
                    family: Roboto
                    size: 14.0
                    weight: 400
                    baseline: alphabetic
                    decoration: TextDecoration.none
                    "3"
   
—— TRIMMED —— 

    child with index 68: RenderIndexedSemantics#6634e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: index=68; layoutOffset=None
        constraints: MISSING
        size: MISSING
        index: 68
        child: RenderRepaintBoundary#20033 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            needs compositing
            parentData: <none>
            constraints: MISSING
            size: MISSING
            usefulness ratio: no metrics collected yet (never painted)
            child: RenderParagraph#1597a NEEDS-LAYOUT NEEDS-PAINT
                parentData: <none>
                constraints: MISSING
                size: MISSING
                textAlign: start
                textDirection: ltr
                softWrap: wrapping at box width
                overflow: clip
                locale: en_US
                maxLines: unlimited
                text: TextSpan
                    debugLabel: (englishLike bodyMedium 2014).merge(blackMountainView bodyMedium)
                    inherit: false
                    color: Color(0xdd000000)
                    family: Roboto
                    size: 14.0
                    weight: 400
                    baseline: alphabetic
                    decoration: TextDecoration.none
                    "68"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was
ListView
════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 636 libraries in 2,491ms.
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 3.0.5 at /Users/iamsahilsonawane/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/iamsahilsonawane/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • 2201116PI (mobile) • 9cd4a37cf581 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)    • macos        • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)       • chrome       • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment]
From the documentation of [`SliverChildBuilderDelegate`](https://api.flutter.dev/flutter/widgets/SliverChildBuilderDelegate-class.html)

> This delegate provides children using a [NullableIndexedWidgetBuilder](https://api.flutter.dev/flutter/widgets/NullableIndexedWidgetBuilder.html) callback, so that the children do not even have to be built until they are displayed.

You should only return `null` if the child is not on the screen. By returning `null` as the first item, Flutter cannot build a `null` widget which is why it's throwing the error. You can instead return a `const SizedBox()` to solve the issue. 

Closing as this is working as expected. If you disagree, please comment and I can reopen it. Thank you

**Comment by iamsahilsonawane** [comment]
@exaby73 I understand your suggestion here. 

So for this case [where I have to programmatically make it empty] I can conditionally add `SizedBox` as first item and null as second. is this a good solution or there can be any workaround to this?

**Comment by exaby73** [comment]
I don't think you would need to return `null` in either case. Just returning `const SizedBox()`, Dart will make it a canonical instance, meaning it will be shared across all instances of usage. You can read more about it [here](https://resocoder.com/2020/01/06/dart-const-tutorial-all-you-need-to-know-const-expressions-canonical-instances-and-more/#t-1665496174918). It would still be performant while you don't need to think about null reference errors during build

**Comment by iamsahilsonawane** [comment]
Got it. Thanks!
