### ISSUE TITLE
 EXCEPTION CAUGHT BY FOUNDATION LIBRARY

### ISSUE THREAD

**Issue by a1573595** [flutter/flutter#113267]
## Steps to Reproduce

1. Execute `flutter run` on the code sample.
2. Click ExpansionTile and scroll the CupertinoPicker.
3. Click ExpansionTile again to close CupertinoPicker.
4. Click ExpansionTile to open CupertinoPicker again and scroll it.

**Expected results:** 
Nothing error to show.

**Actual results:**
 EXCEPTION CAUGHT BY FOUNDATION LIBRARY（See Logs）.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _selectedFruit = 0;

  final List<String> _fruitNames = <String>[
    'Apple',
    'Mango',
    'Banana',
    'Orange',
    'Pineapple',
    'Strawberry',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: Center(
      child: ExpansionTile(
          title: Text('Your choice is ${_fruitNames[_selectedFruit]}'),
          children: [
            SizedBox(
              height: 130,
              child: CupertinoPicker(
                scrollController:
                FixedExtentScrollController(initialItem: _selectedFruit),
                squeeze: 1.2,
                useMagnifier: true,
                magnification: 1.3,
                itemExtent: 32,
                onSelectedItemChanged: (int selectedItem) {
                  setState(() {
                    _selectedFruit = selectedItem;
                  });
                },
                children: List<Widget>.generate(
                  _fruitNames.length,
                      (int index) {
                    return Center(
                      child: Text(
                        _fruitNames[index],
                      ),
                    );
                  },
                ),
              ),
            )
          ]),
    ),);
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
           ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
           The following assertion was thrown while dispatching notifications for FixedExtentScrollController:
           'package:flutter/src/rendering/object.dart': Failed assertion: line 3093 pos 12: '!_debugDisposed':
           is not true.
           
           Either the assertion indicates an error in the framework itself, or we should provide substantially
           more information in this error message to help you determine and fix the underlying cause.
           In either case, please report this assertion by filing a bug on GitHub:
             https://github.com/flutter/flutter/issues/new?template=2_bug.md
           
           When the exception was thrown, this was the stack:
           #2      RenderObject.markNeedsSemanticsUpdate (package:flutter/src/rendering/object.dart:3093:12)
           #3      _RenderCupertinoPickerSemantics._handleScrollUpdate (package:flutter/src/cupertino/picker.dart:479:5)
           #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:351:24)
           #5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:351:24)
           #6      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:985:11)
           #7      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:281:9)
           #8      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:78:18)
           #9      ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:122:5)
           #10     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:386:14)
           #11     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:671:12)
           #12     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:483:55)
           #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
           #14     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:483:7)
           #15     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:330:9)
           #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
           #17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
           #18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
           #19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
           #20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
           #21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
           #22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
           #23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
           #24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
           #25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
           #26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
           #27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
           #28     _invoke1 (dart:ui/hooks.dart:167:13)
           #29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
           #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
           (elided 2 frames from class _AssertionError)
           
           The FixedExtentScrollController sending notification was:
             FixedExtentScrollController#37891(one client, offset 19.2)
           ════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
Analyzing untitled...                                                   
No issues found! (ran in 1.5s)
```

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale
    zh-Hant-TW)
    • Flutter version 3.3.4 on channel stable at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (6 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/chien/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/chien/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • SM A5360 (mobile)           • R5CT8024XET   • android-arm64  • Android 12
      (API 31)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13
      (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.6
      21G115 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
@a1573595 This issue is reproducible on the `stable` channel. But it seems to have been fixed on the latest `master` channel. Please see the demo. 

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/195062693-1cf1b58b-6cde-4e35-b07b-ed109a8aeb34.mov


</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (23 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-6.0.pre.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-6.0.pre.4 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6e5f95bc3c (15 minutes ago), 2022-10-10 22:57:32 -0400
    • Engine revision 593ae56f04
    • Dart version 2.19.0 (build 2.19.0-298.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Pixel 3a (mobile)      • 964AY0WL20                           • android-arm64  • Android 12 (API 32)
    • iPhone 14 Pro (mobile) • 7CB497D7-2159-4F84-BDBE-D79330FA1E48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

Please try running app again on the latest master channel and confirm if this issue is fixed.

**Comment by a1573595** [comment]
> @a1573595 This issue is reproducible on the `stable` channel. But it seems to have been fixed on the latest `master` channel. Please see the demo.
> 
> Demo
> flutter doctor -v (stable and master)
> Please try running app again on the latest master channel and confirm if this issue is fixed.

Thanks, I will try it later.

**Comment by a1573595** [comment]
it works well on the master channel, thanks for your help.
