### ISSUE TITLE
[multicast_dns] plugin fails on lookup() on ios, 16.0.3

### ISSUE THREAD

**Issue by nilsmagnus** [flutter/flutter#113219]
Using multicast_dns plugin 0.3.2+2 fails on ios.

## Steps to Reproduce

1. clone the repo at https://github.com/nilsmagnus/mdns_test and run the app on ios
2. Press the floating action-button and view the results in the log

The mdns_repo is created using `flutter create mdns_test` and the only code-file changed  is main.dart, where I have removed a lot of comments and added a `_scan()`-function.

**Expected results:** 

listing of mdns-entries

**Actual results:** 

        Reloaded 1 of 600 libraries in 278ms (compile: 32 ms, reload: 73 ms, reassemble: 131 ms).
        [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353
        #0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
        #1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2460:15)
        #2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
        #3      _MyHomePageState._startScan (package:mdns_test/main.dart:76:10)
        <asynchronous suspension>

<details>
<summary>Code sample</summary>

```dart

_startScan() async {
    final MDnsClient client = MDnsClient();
    await client.start();
    String name ="_http._tcp.local";
    await for (final IPAddressResourceRecord record in client
        .lookup<IPAddressResourceRecord>(ResourceRecordQuery.addressIPv4(name))) {
      print('Found address (${record.address}).');
    }

    await for (final IPAddressResourceRecord record in client
        .lookup<IPAddressResourceRecord>(ResourceRecordQuery.addressIPv6(name))) {
      print('Found address (${record.address}).');
    }
    client.stop();
  }
```

</details>

<details>
  <summary>Logs</summary>

```

      Reloaded 1 of 600 libraries in 278ms (compile: 32 ms, reload: 73 ms, reassemble: 131 ms).
        [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353
        #0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
        #1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2460:15)
        #2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
        #3      _MyHomePageState._startScan (package:mdns_test/main.dart:76:10)
        <asynchronous suspension>
```

```
    flutter doctor -v
    [✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm (Rosetta), locale en-NO)
    • Flutter version 3.3.4 on channel stable at /opt/homebrew/Caskroom/flutter/1.22.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (6 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0
    
    [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/larsgard/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.
    
    [✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3
    
    [✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
    [✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
    🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
    🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    
    [✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21
    
    [✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
    🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
    
    [✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125
    
    [✓] HTTP Host Availability
    • All required HTTP hosts are available
    
    • No issues found!
```

</details>

**Comment by huycozy** [comment]
@nilsmagnus thanks for reporting this but looks like this is duplicated with #112180. Please take a look at https://github.com/flutter/flutter/issues/112180#issuecomment-1256689530 and check if you have `com.apple.developer.networking.multicast` entitlement. If you haven't had it yet, please see #42102.

**Comment by nilsmagnus** [comment]
@huycozy i dont have that entitlement. Maybe the doc on this plugin should be updated?

**Comment by huycozy** [comment]
@nilsmagnus Yes. Please see https://github.com/flutter/flutter/issues/42102#issuecomment-935161503. Closing this issue as a duplicate, so please follow up on #42102 for further updates.

**Comment by Liberations** [comment]
same #113263
