### ISSUE TITLE
Failed to build iOS app - after submitting the app to App Store Connect it can't build anymore 

### ISSUE THREAD

**Issue by TheJeopardizer** [flutter/flutter#113289]
```
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running Xcode build...                                                  
Xcode build done.                                           129,7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/ys/bhqfdt_n0k183kt_38tdl3_m0000gn/T/flutter_tools.loFQVF/flutt
    	er_ios_build_temp_dir4b7T2m/temporary_xcresult_bundle

    Invalid depfile: /Users/macbookpro/Desktop/E-shango
    Dev/app/.dart_tool/flutter_build/ff3363ced105b3850c1350c772b083bb/kernel_sna
    pshot.d
    Invalid depfile: /Users/macbookpro/Desktop/E-shango
    Dev/app/.dart_tool/flutter_build/ff3363ced105b3850c1350c772b083bb/kernel_sna
    pshot.d
    Invalid depfile: /Users/macbookpro/Desktop/E-shango
    Dev/app/.dart_tool/flutter_build/ff3363ced105b3850c1350c772b083bb/kernel_sna
    pshot.d
    Invalid depfile: /Users/macbookpro/Desktop/E-shango
    Dev/app/.dart_tool/flutter_build/ff3363ced105b3850c1350c772b083bb/kernel_sna
    pshot.d
    Error: Couldn't resolve the package 'google_sign_in' in
    'package:google_sign_in/google_sign_in.dart'.
    Error: Couldn't resolve the package 'flutter_facebook_auth' in
    'package:flutter_facebook_auth/flutter_facebook_auth.dart'.
    Error: Couldn't resolve the package 'sign_in_with_apple' in
    'package:sign_in_with_apple/sign_in_with_apple.dart'.
    lib/src/ui/accounts/login/login2/login.dart:8:8: Error: Not found:
    'package:google_sign_in/google_sign_in.dart'
    import 'package:google_sign_in/google_sign_in.dart';
           ^
    lib/src/blocs/login_bloc.dart:16:8: Error: Not found:
    'package:google_sign_in/google_sign_in.dart'
    import 'package:google_sign_in/google_sign_in.dart';
           ^
    lib/src/blocs/login_bloc.dart:14:8: Error: Not found:
    'package:flutter_facebook_auth/flutter_facebook_auth.dart'
    import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';
           ^
    lib/src/blocs/login_bloc.dart:18:8: Error: Not found:
    'package:sign_in_with_apple/sign_in_with_apple.dart'
    import 'package:sign_in_with_apple/sign_in_with_apple.dart';
           ^
    lib/src/ui/accounts/login/login2/login.dart:24:9: Error: Type 'GoogleSignIn'
    not found.
      final GoogleSignIn _googleSignIn = GoogleSignIn();
            ^^^^^^^^^^^^
    lib/src/ui/accounts/login/login2/login.dart:24:9: Error: 'GoogleSignIn'
    isn't a type.
      final GoogleSignIn _googleSignIn = GoogleSignIn();
            ^^^^^^^^^^^^
    lib/src/ui/accounts/login/login2/login.dart:24:38: Error: Method not found:
    'GoogleSignIn'.
      final GoogleSignIn _googleSignIn = GoogleSignIn();
                                         ^^^^^^^^^^^^
    lib/src/blocs/login_bloc.dart:41:11: Error: 'GoogleSignInAccount' isn't a
    type.
        final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();
              ^^^^^^^^^^^^^^^^^^^
    lib/src/blocs/login_bloc.dart:48:13: Error: 'GoogleSignInAuthentication'
    isn't a type.
          final GoogleSignInAuthentication? googleAuth = await
          googleUser.authentication;
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    lib/src/blocs/login_bloc.dart:41:51: Error: The method 'GoogleSignIn' isn't
    defined for the class 'AccountBloc'.
     - 'AccountBloc' is from 'package:app/src/blocs/login_bloc.dart'
     ('lib/src/blocs/login_bloc.dart').
    Try correcting the name to the name of an existing method, or defining a
    method named 'GoogleSignIn'.
        final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();
                                                      ^^^^^^^^^^^^
    lib/src/blocs/login_bloc.dart:73:11: Error: 'LoginResult' isn't a type.
        final LoginResult loginResult = await FacebookAuth.instance.login();
              ^^^^^^^^^^^
    lib/src/blocs/login_bloc.dart:73:43: Error: The getter 'FacebookAuth' isn't
    defined for the class 'AccountBloc'.
     - 'AccountBloc' is from 'package:app/src/blocs/login_bloc.dart'
     ('lib/src/blocs/login_bloc.dart').
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'FacebookAuth'.
        final LoginResult loginResult = await FacebookAuth.instance.login();
                                              ^^^^^^^^^^^^
    lib/src/blocs/login_bloc.dart:108:35: Error: The getter 'SignInWithApple'
    isn't defined for the class 'AccountBloc'.
     - 'AccountBloc' is from 'package:app/src/blocs/login_bloc.dart'
     ('lib/src/blocs/login_bloc.dart').
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'SignInWithApple'.
        final appleCredential = await SignInWithApple.getAppleIDCredential(
                                      ^^^^^^^^^^^^^^^
    lib/src/blocs/login_bloc.dart:110:9: Error: The getter
    'AppleIDAuthorizationScopes' isn't defined for the class 'AccountBloc'.
     - 'AccountBloc' is from 'package:app/src/blocs/login_bloc.dart'
     ('lib/src/blocs/login_bloc.dart').
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'AppleIDAuthorizationScopes'.
            AppleIDAuthorizationScopes.email,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    lib/src/blocs/login_bloc.dart:111:9: Error: The getter
    'AppleIDAuthorizationScopes' isn't defined for the class 'AccountBloc'.
     - 'AccountBloc' is from 'package:app/src/blocs/login_bloc.dart'
     ('lib/src/blocs/login_bloc.dart').
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'AppleIDAuthorizationScopes'.
            AppleIDAuthorizationScopes.fullName,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Agoogle_sig
    n_in%2Fgoogle_sign_in.dart; message=StandardFileSystem only supports file:*
    and data:* URIs)
    #0      StandardFileSystem.entityForUri
    (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:659:37)
    #2      writeDepfile (package:vm/kernel_front_end.dart:799:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile
    (package:frontend_server/frontend_server.dart:625:9)
    <asynchronous suspension>
    #4      starter (package:frontend_server/frontend_server.dart:1451:12)
    <asynchronous suspension>
    #5      main
    (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.
    dart:10:14)
    <asynchronous suspension>
    Failed to package /Users/macbookpro/Desktop/E-shango Dev/app.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Create Symlinks to Header Folders' will be
    run during every build because it does not specify any outputs. To address
    this warning, either add output dependencies to the script phase, or
    configure it to run in every build by unchecking "Based on dependency
    analysis" in the script phase. (in target 'abseil' from project 'Pods')
    warning: Run script build phase 'Create Symlinks to Header Folders' will be
    run during every build because it does not specify any outputs. To address
    this warning, either add output dependencies to the script phase, or
    configure it to run in every build by unchecking "Based on dependency
    analysis" in the script phase. (in target 'Libuv-gRPC' from project 'Pods')
    warning: Run script build phase 'Create Symlinks to Header Folders' will be
    run during every build because it does not specify any outputs. To address
    this warning, either add output dependencies to the script phase, or
    configure it to run in every build by unchecking "Based on dependency
    analysis" in the script phase. (in target 'BoringSSL-GRPC' from project
    'Pods')
    warning: no rule to process file
    '/Users/macbookpro/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_ios
    -3.3.0/ios/Classes/Stripe Sdk/StripeSdk.xcodeproj/project.pbxproj' of type
    'text.pbxproject' for architecture 'arm64' (in target 'stripe_ios' from
    project 'Pods')
    warning: no rule to process file
    '/Users/macbookpro/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_ios
    -3.3.0/ios/Classes/Stripe
    Sdk/StripeSdk.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme' of type
    'text.xml' for architecture 'arm64' (in target 'stripe_ios' from project
    'Pods')
    warning: no rule to process file
    '/Users/macbookpro/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_ios
    -3.3.0/ios/Classes/Stripe Sdk/StripeSdk.xcodeproj/project.pbxproj' of type
    'text.pbxproject' for architecture 'x86_64' (in target 'stripe_ios' from
    project 'Pods')
    warning: no rule to process file
    '/Users/macbookpro/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_ios
    -3.3.0/ios/Classes/Stripe
    Sdk/StripeSdk.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme' of type
    'text.xml' for architecture 'x86_64' (in target 'stripe_ios' from project
    'Pods')
    warning: Run script build phase 'Create Symlinks to Header Folders' will be
    run during every build because it does not specify any outputs. To address
    this warning, either add output dependencies to the script phase, or
    configure it to run in every build by unchecking "Based on dependency
    analysis" in the script phase. (in target 'gRPC-Core' from project 'Pods')
    warning: Run script build phase 'Create Symlinks to Header Folders' will be
    run during every build because it does not specify any outputs. To address
    this warning, either add output dependencies to the script phase, or
    configure it to run in every build by unchecking "Based on dependency
    analysis" in the script phase. (in target 'gRPC-C++' from project 'Pods')
    warning: Run script build phase 'Run Script' will be run during every build
    because it does not specify any outputs. To address this warning, either add
    output dependencies to the script phase, or configure it to run in every
    build by unchecking "Based on dependency analysis" in the script phase. (in
    target 'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build
    because it does not specify any outputs. To address this warning, either add
    output dependencies to the script phase, or configure it to run in every
    build by unchecking "Based on dependency analysis" in the script phase. (in
    target 'Runner' from project 'Runner')

    Result bundle written to path:
    	/var/folders/ys/bhqfdt_n0k183kt_38tdl3_m0000gn/T/flutter_tools.loFQVF/flutt
    	er_ios_build_temp_dir4b7T2m/temporary_xcresult_bundle


Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
```

**Comment by TheJeopardizer** [comment]
My verbose :
[verbose.txt](https://github.com/flutter/flutter/files/9757889/verbose.txt)

**Comment by danagbemava-nc** [comment]
Hi @TheJeopardizer, please provide the following information 

- Your `flutter doctor -v` output
- Your `pubspec.yaml` & `pubspec.lock`
- Your `Podfile` & `Podfile.lock`

Your verbose logs are also a bit difficult to read because some special characters are polluting it. Kindly provide some clean verbose logs.

Thank you
