### ISSUE TITLE
SharedPreferences DiskReadViolation: shared preferences do work in UI thread

### ISSUE THREAD

**Issue by DoTheMonkeyBusiness** [flutter/flutter#113279]
## Details

I observe slow performance on Android platform when an App starts. I see in logs that not all methods of SharedPreferences plugin work in the background. In my case I see that SharedPreferences instance is created in the main thread [please see](https://github.com/flutter/plugins/blob/5239062837ef235c614b646d3143ffda6ec57dd0/packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java#L54). Also I see that [getAllPrefs](https://github.com/flutter/plugins/blob/5239062837ef235c614b646d3143ffda6ec57dd0/packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java#L185) works in the Main thread too.
Please move these methods into background.

**Target Platform:** Android

<details>
<summary>Logs</summary>

```bash
StrictMode policy violation; ~duration=658 ms: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
	at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
	at java.io.File.exists(File.java:815)
	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:645)
	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:636)
	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:592)
	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:787)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:439)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.<init>(MethodCallHandlerImpl.java:54)
	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.setupChannel(SharedPreferencesPlugin.java:36)
	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.onAttachedToEngine(SharedPreferencesPlugin.java:26)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:145)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:199)
	at MainActivity.configureFlutterEngine(MainActivity.kt:159)
	at io.flutter.embedding.android.FlutterFragment.configureFlutterEngine(FlutterFragment.java:1183)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:199)
	at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:743)
	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at MainActivity.onStart(MainActivity.kt:144)
```
</details>

**Comment by huycozy** [comment]
@DoTheMonkeyBusiness It seems you've enabled `StrictMode`, right?
I ran [shared_preferences example](https://github.com/flutter/plugins/tree/main/packages/shared_preferences/shared_preferences/example) along with enabling [StrictMode](https://developer.android.com/reference/android/os/StrictMode) but didn't see this log. Can you share `Steps to reproduce` this issue? 
Also, which `shared_preferences` and Flutter version are you using?

**Comment by DoTheMonkeyBusiness** [comment]
@huycozy Hello, yes, I enabled `StrictMode`.

I ran [shared_preferences example](https://github.com/flutter/plugins/tree/main/packages/shared_preferences/shared_preferences/example) too and I observe this issue.
There is no difference in `shared_preferences` and Flutter versions as the issue is in native Android code.
To observe this issue just run the app, the log will be thrown on app start.

Please try with my `StrictMode` settings:
```
private fun setupStrictModeForDebugBuild() {
        if (BuildConfig.DEBUG) {
            StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder()
                .detectAll()
                .penaltyDeathOnNetwork()
                .penaltyLog()
                .build())
        }
    }
```

My flutter doctor:
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.2)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2022.1.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by huycozy** [comment]
@DoTheMonkeyBusiness 
I can reproduce this issue on my other device (Samsung Galaxy Tab A7 Lite, Android 12 OneUI 4.1, SM-T225) even with the sample policy in [StrictMode](https://developer.android.com/reference/android/os/StrictMode).

Labeling this issue for further investigation. This issue is reproducible on the latest `stable` and `master` channels.
Plugin version: `shared_preferences: ^2.0.15`

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (23 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-6.0.pre.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-6.0.pre.4 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6e5f95bc3c (15 minutes ago), 2022-10-10 22:57:32 -0400
    • Engine revision 593ae56f04
    • Dart version 2.19.0 (build 2.19.0-298.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Pixel 3a (mobile)      • 964AY0WL20                           • android-arm64  • Android 12 (API 32)
    • iPhone 14 Pro (mobile) • 7CB497D7-2159-4F84-BDBE-D79330FA1E48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by stuartmorgan-g** [comment]
This is addressed in the new API surfaces; we don't plan to change the implementation of the legacy implementation going forward.
