### ISSUE TITLE
local_auth with flutter_appauth causes RuntimeException on Android

### ISSUE THREAD

**Issue by paul-charlton** [flutter/flutter#113208]
## Problem
When both local_auth is installed and flutter_appauth is used then the application experiences a crash.  Removing local_auth removes the issue.  Downgrading to version 1.1.11 of local_auth also acts as a workaround

## Steps to Reproduce

Android issue
1. Install and configure local_auth
2. Install and configure flutter_appauth
3. Run and login using oauth via flutter_appauth
4. Crash after login

**Expected results:**
The App should return to focus and run

**Actual results:**
Crash (full error in logs):
```
E/AndroidRuntime(12637): java.lang.RuntimeException: Unable to start activity ComponentInfo{XXX/net.openid.appauth.RedirectUriReceiverActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```

<details>
<summary>Code sample</summary>
Not included as needs configuration for oauth provider etc
</details>

<details>
  <summary>Logs</summary>

Crash below with flutter run --verbose:
```
[ +303 ms] W/Parcel  (12905): Expecting binder but got null!
[+22068 ms] D/AndroidRuntime(12905): Shutting down VM
[  +10 ms] E/AndroidRuntime(12905): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(12905): Process: XXX, PID: 12905
[        ] E/AndroidRuntime(12905): java.lang.RuntimeException: Unable to start activity ComponentInfo{XXX/net.openid.appauth.RedirectUriReceiverActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with   
this activity.
[        ] E/AndroidRuntime(12905):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
[   +1 ms] E/AndroidRuntime(12905):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
[        ] E/AndroidRuntime(12905):     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
[        ] E/AndroidRuntime(12905):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[        ] E/AndroidRuntime(12905):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[        ] E/AndroidRuntime(12905):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
[        ] E/AndroidRuntime(12905):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(12905):     at android.os.Looper.loopOnce(Looper.java:201)
[        ] E/AndroidRuntime(12905):     at android.os.Looper.loop(Looper.java:288)
[        ] E/AndroidRuntime(12905):     at android.app.ActivityThread.main(ActivityThread.java:7898)
[        ] E/AndroidRuntime(12905):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(12905):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[        ] E/AndroidRuntime(12905):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[   +1 ms] E/AndroidRuntime(12905): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
[        ] E/AndroidRuntime(12905):     at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
[   +1 ms] E/AndroidRuntime(12905):     at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
[   +1 ms] E/AndroidRuntime(12905):     at androidx.appcompat.app.AppCompatDelegateImpl.initWindowDecorActionBar(AppCompatDelegateImpl.java:550)
[        ] E/AndroidRuntime(12905):     at androidx.appcompat.app.AppCompatDelegateImpl.getSupportActionBar(AppCompatDelegateImpl.java:537)
[        ] E/AndroidRuntime(12905):     at androidx.appcompat.app.AppCompatDelegateImpl.invalidateOptionsMenu(AppCompatDelegateImpl.java:1220)
[        ] E/AndroidRuntime(12905):     at androidx.appcompat.app.AppCompatActivity.invalidateOptionsMenu(AppCompatActivity.java:314)
[        ] E/AndroidRuntime(12905):     at androidx.activity.ComponentActivity.invalidateMenu(ComponentActivity.java:553)
[        ] E/AndroidRuntime(12905):     at androidx.activity.ComponentActivity$$ExternalSyntheticLambda2.run(Unknown Source:2)
[        ] E/AndroidRuntime(12905):     at androidx.core.view.MenuHostHelper.addMenuProvider(MenuHostHelper.java:116)
[        ] E/AndroidRuntime(12905):     at androidx.activity.ComponentActivity.addMenuProvider(ComponentActivity.java:531)
[        ] E/AndroidRuntime(12905):     at androidx.fragment.app.FragmentActivity$HostCallbacks.addMenuProvider(FragmentActivity.java:736)
[        ] E/AndroidRuntime(12905):     at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2784)
[        ] E/AndroidRuntime(12905):     at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:117)
[        ] E/AndroidRuntime(12905):     at androidx.fragment.app.FragmentActivity.lambda$init$3$androidx-fragment-app-FragmentActivity(FragmentActivity.java:140)
[        ] E/AndroidRuntime(12905):     at androidx.fragment.app.FragmentActivity$$ExternalSyntheticLambda0.onContextAvailable(Unknown Source:2)
[        ] E/AndroidRuntime(12905):     at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
[        ] E/AndroidRuntime(12905):     at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:352)
[        ] E/AndroidRuntime(12905):     at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:217)
[        ] E/AndroidRuntime(12905):     at net.openid.appauth.RedirectUriReceiverActivity.onCreate(RedirectUriReceiverActivity.java:49)
[        ] E/AndroidRuntime(12905):     at android.app.Activity.performCreate(Activity.java:8290)
[   +1 ms] E/AndroidRuntime(12905):     at android.app.Activity.performCreate(Activity.java:8269)
[   +2 ms] E/AndroidRuntime(12905):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
[   +1 ms] E/AndroidRuntime(12905):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
[   +1 ms] E/AndroidRuntime(12905):     ... 12 more
[  +16 ms] I/Process (12905): Sending signal. PID: 12905 SIG: 9
[  +44 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/XXX/code_cache/XXXZUAPEN/XXX/)
[ +266 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 99,366ms.
[ +102 ms] ensureAnalyticsSent: 97ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

flutter doctor -v:
```[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22000.1042], locale en-GB)
    • Flutter version 3.3.4 on channel stable at C:\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (5 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\pchar\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.72.0)
    • VS Code at C:\Users\pchar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1042]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 106.0.1370.37

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
The exception is coming from the other plugin, not `local_auth`, and based on https://github.com/MaikuB/flutter_appauth/issues/362#issuecomment-1219176612 the problem is triggered by `local_auth` using an up-to-date version of `androidx.fragment:fragment`.

Using current versions of dependencies isn't an issue with `local_auth`; it's up to `flutter_appauth` developers to make their plugin compatible with current Android libraries.
