### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Illegal character in path: assets\images

### ISSUE THREAD

**Issue by TonyGoarge** [flutter/flutter#113207]
## Command
```
flutter --quiet assemble --no-version-check --depfile G:\flutter_windows_2.5.2-stable\projects flutter\test2\build\app\intermediates\flutter\debug/flutter_build.d --output G:\flutter_windows_2.5.2-stable\projects flutter\test2\build\app\intermediates\flutter\debug -dTargetFile=G:\flutter_windows_2.5.2-stable\projects flutter\test2\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Illegal character in path: assets\images
```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1644:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2674:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2646:38)
#3      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:738:29)
#4      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:679:9)
#5      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:246:53)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:53:26)
<asynchronous suspension>
#7      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:65:34)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:9)
<asynchronous suspension>
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
<asynchronous suspension>
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.2006], locale en-GB)
    • Flutter version 2.5.2 at G:\flutter_windows_2.5.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (1 year ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\pc lab top\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at C:\Users\pc lab top\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • CPH1911 (mobile) • 45HAN7EQNJUKVK6D • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 106.0.5249.103
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 106.0.1370.37

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 3595343e20a61ff16d14e8ecc25f364276bb1b8b

**Comment by darshankawar** [comment]
@TonyGoarge 
This indicates there could be a formatting issue in your pubspec file. So you need to double check and confirm the alignment / formatting is correct in that file and there are no extra spaces or any illegal char. The tool seems to correctly throwing the error as it is telling that there's an illegal char in the path.

Closing from here as this doesn't seem to be a tool issue. If you disagree or think this is a genuine bug, write in comments and I'll reopen it.
