### ISSUE TITLE
[in_app_purchase][android] Upgrade to Billing 5.0.0 with in_app_purchse 3.0.7 crashes the app.

### ISSUE THREAD

**Issue by jdevp** [flutter/flutter#113259]
## Steps to Reproduce

1. Install the apk. 
2. Run the app to invoke one-time purchase, app crashes 
3. Revert the Billing version back to 3.0.2, app works as expected. 

<details>
Implement in_app_purchase 3.0.7 with Billing version 5.0.0. App crashes with following error.

```
E/AndroidRuntime(23846): java.lang.NoSuchMethodError: No virtual method setReplaceSkusProrationMode(I)Lcom/android/billingclient/api/BillingFlowParams$Builder; in class Lcom/android/billingclient/api/BillingFlowParams$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingFlowParams$Builder' appears in /data/app/~~GvoxvqhUqjnfLMJ0RDGp5w==/com.blueedgez.paintover-LATaomnopy6BbsUjIKseDA==/base.apk!classes2.dex)
E/AndroidRuntime(23846):        at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.launchBillingFlow(MethodCallHandlerImpl.java:263)
E/AndroidRuntime(23846):        at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:123)
```
App works normal by removing the following from build.gradle

```
dependencies {
     implementation 'com.android.billingclient:billing:5.0.0'
}
```
And remove following lines from AndroidManifest.xml

```
 <meta-data
            android:name="com.google.android.play.billingclient.version"
            android:value="5.0.0" />

```

</details>

<details>
  <summary>Logs</summary>

```
[   +2 ms] E/AndroidRuntime( 2718): java.lang.NoSuchMethodError: No virtual method
setReplaceSkusProrationMode(I)Lcom/android/billingclient/api/BillingFlowParams$Builder; in class
Lcom/android/billingclient/api/BillingFlowParams$Builder; or its super classes (declaration of
'com.android.billingclient.api.BillingFlowParams$Builder' appears in
/data/app/~~GvoxvqhUqjnfLMJ0RDGp5w==/com.blueedgez.paintover-LATaomnopy6BbsUjIKseDA==/base.apk!classes2.dex)
[   +3 ms] E/AndroidRuntime( 2718):     at
io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.launchBillingFlow(MethodCallHandlerImpl.java:263)
[   +6 ms] E/AndroidRuntime( 2718):     at
io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:123)
[   +2 ms] E/AndroidRuntime( 2718):     at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[   +2 ms] E/AndroidRuntime( 2718):     at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[   +1 ms] E/AndroidRuntime( 2718):     at
io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
[   +4 ms] E/AndroidRuntime( 2718):     at
io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
[   +1 ms] E/AndroidRuntime( 2718):     at android.os.Handler.handleCallback(Handler.java:938)
[   +1 ms] E/AndroidRuntime( 2718):     at android.os.Handler.dispatchMessage(Handler.java:99)
[   +1 ms] E/AndroidRuntime( 2718):     at android.os.Looper.loop(Looper.java:250)
[        ] E/AndroidRuntime( 2718):     at android.app.ActivityThread.main(ActivityThread.java:7886)
[   +1 ms] E/AndroidRuntime( 2718):     at java.lang.reflect.Method.invoke(Native Method)
[   +2 ms] E/AndroidRuntime( 2718):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[   +1 ms] E/AndroidRuntime( 2718):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:970)
[   +1 ms] I/Process ( 2718): Sending signal. PID: 2718 SIG: 9
[ +136 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device
(file:///data/user/0/com.blueedgez.paintover/code_cache/paintoverUZGQLD/paintover/)
[ +254 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[  +14 ms] "flutter run" took 85,883ms.
[  +96 ms] ensureAnalyticsSent: 89ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

```
flutter analyze
Analyzing app...
No issues found! (ran in 1.2s)
```

```
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 3.3.4 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (6 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Jay\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32516.85
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++"
      workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Jay\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (4 available)
    • motorola one 5G ace (mobile) • ZY22FKS36K • android-arm64  • Android 11 (API 30)
    • Windows (desktop)            • windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.592]
    • Chrome (web)                 • chrome     • web-javascript • Google Chrome 106.0.5249.103
    • Edge (web)                   • edge       • web-javascript • Microsoft Edge 104.0.1293.70 (unsupported)

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi, @jdevp, did you add the play-billing library to your own `android/app/build.gradle`? 

If you did, that's probably why you got the crash. You do not need to add it to your own `build.gradle` file since the plugin will add it for you.

**Comment by grizzlei** [comment]
Hi @danagbemava-nc,
I'm experiencing the exact same issue. `in_app_purchase: ^3.0.7` is present in pubspec.yaml and I've already added the following is from android/app/build.gradle:
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    def billingVersion = "5.0.0"
    implementation "com.android.billingclient:billing:$billingVersion"
}
```
Best, Hasan.

**Comment by jdevp** [comment]
Hi @danagbemava-nc 

I have the following in `gradle.build`
```
dependencies {
       implementation 'com.android.billingclient:billing:5.0.0'
}
```
I also have the following in `AndroidManifest.xml`

```
<meta-data
            android: name="com.google.android.play.billingclient.version"
            android: value="5.0.0" />
```
If I don't specify the billing version, the built apk still uses version 3.0.2. If I don't specify the version in `gradle.build`, it doesn't allow me to build with the following error:

```
Attribute meta-data#com.google.android.play.billingclient.version@value value=(5.0.0) from (unknown)
        is also present at [com.android.billingclient:billing:3.0.2] AndroidManifest.xml:15:13-34 value=(3.0.2).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml to override.

```
So, basically, I have to put billing version in `AndroidManifest.xml` in order to migrate to version 5.0.0 and I have to specify the billing version in `gradle.build` in order to build apk.

**Comment by jdevp** [comment]
After hours of research and tries, I finally figured out the issue. This is the solution for me.

1. Remove billing version specification from `gradle.build`.
2. Add the following in AndroidManifest.xml. I'm not sure if this step is needed since I don't know a way to check which Billing version is being used by an APK without uploading it to Play Console.
```
<meta-data
            android: name="com.google.android.play.billingclient.version"
            android: value="5.0.0" />
```
4. Remove `pubspec.lock`, which will allow 3.0.7 to be installed and remove the old version. 
5. `flutter clean` followed by `flutter pub get`.  Everything works as expected, no crash.

**Comment by grizzlei** [comment]
> After hours of research and tries, I finally figured out the issue. This is the solution for me.
> 
> 1. Remove billing version specification from `gradle.build`.
> 2. Add the following in AndroidManifest.xml. I'm not sure if this step is needed since I don't know a way to check which Billing version is being used by an APK without uploading it to Play Console.
> 
> ```
> <meta-data
>             android: name="com.google.android.play.billingclient.version"
>             android: value="5.0.0" />
> ```
> 
> 4. Remove `pubspec.lock`, which will allow 3.0.7 to be installed and remove the old version.
> 5. `flutter clean` followed by `flutter pub get`.  Everything works as expected, no crash.

By the way, after removing `pubspec.lock`, adding `dependencies {implementation 'com.android.billingclient:billing:5.0.0'}` `gradle.build` started working. I didn't need to change AndroidManifest.xml. Thanks for the update @jdevp.
