### ISSUE TITLE
[multicast_dns] IOS16 can not found any device

### ISSUE THREAD

**Issue by Liberations** [flutter/flutter#113263]
1. ios16 before work normal .update to ios16 ,log report 
SocketException:Send failed (OS Error:No route to host errno=65),address e.0.0.0，port=53535

code below

``` void getLanDeviceList() async {
    EasyLoading.show();
    var isShow = true;
    const String name = '_mymei._tcp.local';
    lanDevices.clear();
    final sets = HashSet<LanDevice>();
    var factory = (dynamic host, int port, {bool reuseAddress = false, bool reusePort = false, int ttl = 0}) {
      return RawDatagramSocket.bind(host, port, reuseAddress: true, reusePort: Platform.isIOS, ttl: ttl);
    };

    var client = MDnsClient(rawDatagramSocketFactory: factory);
    // Start the client with default options.
    await client.start();

    // Get the PTR record for the service.
    await for (final PtrResourceRecord ptr
        in client.lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
      // Use the domainName from the PTR record to get the SRV record,
      // which will have the port and local hostname.
      // Note that duplicate messages may come through, especially if any
      // other mDNS queries are running elsewhere on the machine.
      await for (final SrvResourceRecord srv
          in client.lookup<SrvResourceRecord>(ResourceRecordQuery.service(ptr.domainName))) {
        // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
        final String bundleId = ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
        print('Dart observatory instance found at${ptr.toString()} '
            '${srv.target}:${srv.port} for "$bundleId".');
        if (srv.port != LocalServer.dnsPort) continue;
        await for (final IPAddressResourceRecord ip
            in client.lookup<IPAddressResourceRecord>(ResourceRecordQuery.addressIPv4(srv.target))) {
          print('IP: ${ip.toString()}');
          sets.add(LanDevice(ptr.domainName.replaceAll('._mymei._tcp.local', ''), ip.address.address));
          lanDevices.clear();
          lanDevices.addAll(sets);
          update(['lanDeviceList']);
          isShow = false;
          EasyLoading.dismiss();
        }
      }
    }
    client.stop();
    if (isShow) {
      EasyLoading.dismiss();
    }
    print('mymeiDevice ${lanDevices.toString()}');
    print('Done.');
  }
```

```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.22621.1], locale zh-CN)
    • Flutter version 2.10.5 at D:\fluttersdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (6 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = D:\Android\sdk
    • ANDROID_SDK_ROOT = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at D:\soft\as4.1.3\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.63

[!] HTTP Host Availability
    ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host:
      信号灯超时时间已到


! Doctor found issues in 2 categories.
```

**Comment by huycozy** [comment]
@Liberations 
Please provide the information indicated below:

- Completed exception logs
- Which `multicast_dns` version are you using? Please retry on the latest version `multicast_dns: ^0.3.2+2`.
- Also, does the issue happen on lower iOS versions? Or does it only reproduce on iOS 16.0? 

Thank you!

**Comment by Liberations** [comment]
VERSION multicast_dns: ^0.3.2+2
error below. system ios16.0.2 iphone XR
```
flutter: ** GOING TO ROUTE /TestMulticastDns. isError: [false]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2450:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      _TestMulticastDnsState.loadDevices (package:playremote/app/modules/home/TestMulticastdNS.dart:61:19)
<asynchronous suspension>
flutter: Done.
```
@huycozy

**Comment by Liberations** [comment]
test code below 

```
import 'dart:collection';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:multicast_dns/multicast_dns.dart';

class TestMulticastDns extends StatefulWidget {
  const TestMulticastDns({Key? key}) : super(key: key);

  @override
  State<TestMulticastDns> createState() => _TestMulticastDnsState();
}

class _TestMulticastDnsState extends State<TestMulticastDns> {
  var ips = HashSet<String>();
  var ipsArray = <String>[];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
        actions: [ GestureDetector(
            onTap: () {
              loadDevices();
            },
            child: Container(
              color: Colors.red,
              width: 100,
              height: 100,
              child: Center(child: Text('scan')),
            ))],
      ),
      body: ListView.builder(
        itemBuilder: (context, index) {
          return Container(
            child: Text(ipsArray[index]),
          );
        },
        itemCount: ipsArray.length,
      ),
    );
  }

  void loadDevices() async {
    setState(() {
      ips.clear();
      ipsArray.clear();
    });
    const String name = '_mymei._tcp.local';
    var factory = (dynamic host, int port, {bool reuseAddress = false, bool reusePort = false, int ttl = 0}) {
      return RawDatagramSocket.bind(host, port, reuseAddress: true, reusePort: Platform.isIOS, ttl: ttl);
    };

    var client = MDnsClient(rawDatagramSocketFactory: factory);
    // Start the client with default options.
    await client.start();

    // Get the PTR record for the service.
    await for (final PtrResourceRecord ptr
        in client.lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
      // Use the domainName from the PTR record to get the SRV record,
      // which will have the port and local hostname.
      // Note that duplicate messages may come through, especially if any
      // other mDNS queries are running elsewhere on the machine.
      await for (final SrvResourceRecord srv
          in client.lookup<SrvResourceRecord>(ResourceRecordQuery.service(ptr.domainName))) {
        // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
        final String bundleId = ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
        print('Dart observatory instance found at${ptr.toString()} '
            '${srv.target}:${srv.port} for "$bundleId".');
        await for (final IPAddressResourceRecord ip
            in client.lookup<IPAddressResourceRecord>(ResourceRecordQuery.addressIPv4(srv.target))) {
          print('IP: ${ip.address.host}');
          ips.add(ip.address.host);
          ipsArray.clear();
          setState(() {
            ips.forEach((element) {
              ipsArray.add(element);
            });
          });
        }
      }
    }
    client.stop();
    print('Done.');
  }
}

```

**Comment by Liberations** [comment]
lower iOS versions is normal

**Comment by Liberations** [comment]
Info.plist
```
<key>NSBonjourServices</key>
	<array>
		<string>_http._tcp</string>
		<string>_mymei._tcp.local</string>
		<string>_dartobservatory._tcp</string>
	</array>
```

**Comment by huycozy** [comment]
@Liberations 
This issue is similar to #113219 which is reported recently (it's duplicated of https://github.com/flutter/flutter/issues/42102).
Closing this issue as a duplicate, so please follow up on #42102 for further updates.
