### ISSUE TITLE
video_player plugin doesn't play m3u8 file format.

### ISSUE THREAD

**Issue by Biplab-Dutta** [flutter/flutter#113362]
I was creating a video player app and the video that needs to be played is in m3u8 format. But the `video_player` plugin is unable to play my video and throws some exception which looks like originating from the ExoPlayer.
Here's the debug console log:
<details>
<summary> Debug Console Log </summary>

```
E/ExoPlayerImplInternal(21087):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(21087):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
E/ExoPlayerImplInternal(21087):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
E/ExoPlayerImplInternal(21087):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(21087):       at android.os.Looper.loop(Looper.java:201)
E/ExoPlayerImplInternal(21087):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(21087):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal(21087):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:404)
E/ExoPlayerImplInternal(21087):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(21087):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
E/ExoPlayerImplInternal(21087):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
E/ExoPlayerImplInternal(21087):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
E/ExoPlayerImplInternal(21087):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(21087):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(21087):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(21087):       at java.lang.Thread.run(Thread.java:764)
E/flutter (21087): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (21087):
```
</details>

The same m3u8 file works fine when opened on apps like `vlc player`.
So, what is the issue here as the official [ExoPlayer docs](https://exoplayer.dev/supported-formats#hls) claims that it supports HLS.

<details>
<summary> Code Sample </summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(const VideoApp());

class VideoApp extends StatefulWidget {
  const VideoApp({Key? key}) : super(key: key);

  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://wwwx14.gogocdn.stream/videos/hls/epEdDNXc5OT8hNu1n2X72w/1665658023/193173/0b594d900f47daabc194844092384914/ep.1035.1664679897.m3u8')
      ..initialize().then((_) {
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
```
</details>

**Comment by Biplab-Dutta** [comment]
I think it's because of the 403 issue. Closing it for now.
