### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by wuyuzhou12345** [flutter/flutter#113320]
## Command
```
flutter clean
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: Operation not permitted, errno = 1
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      AndroidSdk.reinitialize (package:flutter_tools/src/android/android_sdk.dart:334:10)
#5      new AndroidSdk (package:flutter_tools/src/android/android_sdk.dart:38:5)
#6      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:153:12)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:439:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#12     androidSdk (package:flutter_tools/src/globals_null_migrated.dart:56:39)
#13     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:191:29)
#14     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:439:23)
#16     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#18     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#19     deviceManager (package:flutter_tools/src/globals.dart:18:44)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:266:17)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
```
```
encountered exception: FileSystemException: Directory listing failed, path = '/Users/zhouluying/Downloads/android-sdk-mac_x86-1.6_r1/build-tools/' (OS Error: Operation not permitted, errno = 1)

#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      AndroidSdk.reinitialize (package:flutter_tools/src/android/android_sdk.dart:334:10)
#5      new AndroidSdk (package:flutter_tools/src/android/android_sdk.dart:38:5)
#6      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:153:12)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:439:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#11     androidSdk (package:flutter_tools/src/globals_null_migrated.dart:56:39)
#12     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:122:29)
#13     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#14     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:439:23)
#15     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#16     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#17     androidWorkflow (package:flutter_tools/src/android/android_workflow.dart:26:49)
#18     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:80:11)
#19     Doctor.validators (package:flutter_tools/src/doctor.dart:187:46)
#20     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:193:45)
#21     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
#22     _doctorText (package:flutter_tools/runner.dart:232:18)
#23     _handleToolError (package:flutter_tools/runner.dart:157:27)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by exaby73** [comment]
Hello @wuyuzhou12345. Thank you for filing this issue. Can you please provide the following information?

- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
