### ISSUE TITLE
Error build example stocks

### ISSUE THREAD

**Issue by mdmunir** [flutter/flutter#11334]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor
```
debian8@debian8:stocks$ flutter doctor
[✓] Flutter (on Linux, locale en_US.utf8, channel alpha)
    • Flutter at /opt/flutter
    • Framework revision d36e2f6191 (4 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 15.1
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • ASUS Z00AD • G2AZFG02A930CPH • android-x86 • Android 6.0.1 (API 23)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

```
debian8@debian8:stocks$ flutter run
Launching lib/main.dart on ASUS Z00AD in debug mode...
Running 'gradle assembleDebug'...                     2.5s
Built build/app/outputs/apk/app-debug.apk (21.7MB).
Syncing files to device ASUS Z00AD...                     
I/flutter (30562): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30562): The following _CompileTimeError was thrown building StockHome(dirty; state: StockHomeState#092ba()):
I/flutter (30562): 'file:///home/mdmunir/projects/android/flutter-master/examples/stocks/lib/stock_home.dart':
I/flutter (30562): malformed type: line 274: cannot resolve class 'Listenable' from 'StockHomeState'
I/flutter (30562):         animation : new Listenable.merge(< Listenable >[_searchQuery, widget.stocks]),
I/flutter (30562):                         ^
I/flutter (30562): When the exception was thrown, this was the stack:
I/flutter (30562): #0      StockHomeState.build (file:///home/mdmunir/projects/android/flutter-master/examples/stocks/lib/stock_home.dart:326)
I/flutter (30562): #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3481)
I/flutter (30562): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3391)
I/flutter (30562): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (30562): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (30562): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (30562): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (30562): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (30562): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (30562): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (30562): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #58     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (30562): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (30562): #66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (30562): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #75     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4438)
I/flutter (30562): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #78     _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:491)
I/flutter (30562): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (30562): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #94     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (30562): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #100    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (30562): #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #104    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (30562): #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #107    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (30562): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #113    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (30562): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #120    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #125    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #141    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (30562): #142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #145    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #146    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #147    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #152    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (30562): #153    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (30562): #154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (30562): #155    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (30562): #156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (30562): #157    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (30562): #158    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2142)
I/flutter (30562): #159    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:503)
I/flutter (30562): #160    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189)
I/flutter (30562): #161    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:688)
I/flutter (30562): #162    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:636)
I/flutter (30562): #163    _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:70)
I/flutter (30562): ════════════════════════════════════════════════════════════════════════════════════════════════════

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on ASUS Z00AD is available at: http://127.0.0.1:8102/
For a more detailed help message, press "h". To quit, press "q".
W/IInputConnectionWrapper(30562): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(30562): endBatchEdit on inactive InputConnection

```

**Comment by jonahwilliams** [comment]
I believe this was most likely an issue caused by a stale build or out of sync flutter vs example repo. Since the flutter commit is very old it is unlikely to happen again.
