### ISSUE TITLE
[camera][android] `takePicture` not completed after `pausePreview`

### ISSUE THREAD

**Issue by SofiSheromova** [flutter/flutter#113532]
Hi! I found a bug on my android device. If you call `_cameraController.takePicture()` before calling `_cameraController.pausePreview()`, then the `takePicture` function will not completed.   

Device: Redmi Note 8 Pro, Android 11

**Expected results:** the snapshot was saved successfully

**Actual results:** the function `takePicture` is not completed.

<details>
<summary>Code sample</summary>

The example is taken from https://docs.flutter.dev/cookbook/plugins/picture-using-camera and supplemented with a line `await _controller.pausePreview();` before `final image = await _controller.takePicture();`

```dart
import 'dart:async';
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  // Ensure that plugin services are initialized so that `availableCameras()`
  // can be called before `runApp()`
  WidgetsFlutterBinding.ensureInitialized();

  // Obtain a list of the available cameras on the device.
  final cameras = await availableCameras();

  // Get a specific camera from the list of available cameras.
  final firstCamera = cameras.first;

  runApp(
    MaterialApp(
      theme: ThemeData.dark(),
      home: TakePictureScreen(
        // Pass the appropriate camera to the TakePictureScreen widget.
        camera: firstCamera,
      ),
    ),
  );
}

// A screen that allows users to take a picture using a given camera.
class TakePictureScreen extends StatefulWidget {
  const TakePictureScreen({
    super.key,
    required this.camera,
  });

  final CameraDescription camera;

  @override
  TakePictureScreenState createState() => TakePictureScreenState();
}

class TakePictureScreenState extends State<TakePictureScreen> {
  late CameraController _controller;
  late Future<void> _initializeControllerFuture;

  @override
  void initState() {
    super.initState();
    // To display the current output from the Camera,
    // create a CameraController.
    _controller = CameraController(
      // Get a specific camera from the list of available cameras.
      widget.camera,
      // Define the resolution to use.
      ResolutionPreset.medium,
    );

    // Next, initialize the controller. This returns a Future.
    _initializeControllerFuture = _controller.initialize();
  }

  @override
  void dispose() {
    // Dispose of the controller when the widget is disposed.
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Take a picture')),
      // You must wait until the controller is initialized before displaying the
      // camera preview. Use a FutureBuilder to display a loading spinner until the
      // controller has finished initializing.
      body: FutureBuilder<void>(
        future: _initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the Future is complete, display the preview.
            return CameraPreview(_controller);
          } else {
            // Otherwise, display a loading indicator.
            return const Center(child: CircularProgressIndicator());
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        // Provide an onPressed callback.
        onPressed: () async {
          // Take the Picture in a try / catch block. If anything goes wrong,
          // catch the error.
          try {
            // Ensure that the camera is initialized.
            await _initializeControllerFuture;

            // Attempt to take a picture and get the file `image`
            // where it was saved.
            await _controller.pausePreview();
            final image = await _controller.takePicture();

            if (!mounted) return;

            // If the picture was taken, display it on a new screen.
            await Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) => DisplayPictureScreen(
                  // Pass the automatically generated path to
                  // the DisplayPictureScreen widget.
                  imagePath: image.path,
                ),
              ),
            );
          } catch (e) {
            // If an error occurs, log the error to the console.
            print(e);
          }
        },
        child: const Icon(Icons.camera_alt),
      ),
    );
  }
}

// A widget that displays the picture taken by the user.
class DisplayPictureScreen extends StatelessWidget {
  final String imagePath;

  const DisplayPictureScreen({super.key, required this.imagePath});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Display the Picture')),
      // The image is stored as a file on the device. Use the `Image.file`
      // constructor with the given path to display the image.
      body: Image.file(File(imagePath)),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[        ] An Observatory debugger and profiler on Redmi Note 8 Pro is available at: http://127.0.0.1:62833/Db369jd81Ig=/
[ +836 ms] E/ion     ( 7463): ioctl c0044901 failed with code -1: Invalid argument
[  +29 ms] The Flutter DevTools debugger and profiler on Redmi Note 8 Pro is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:62833/Db369jd81Ig=/
[+2168 ms] I/BufferQueueConsumer( 7463): [](id:1d2700000000,api:0,p:-1,c:7463) connect(): controlledByApp=true
[  +23 ms] V/PhoneWindow( 7463): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@9d812f7, this = DecorView@8d18564[MainActivity]
[  +13 ms] I/BufferQueueConsumer( 7463): [](id:1d2700000001,api:0,p:-1,c:7463) connect(): controlledByApp=true
[        ] W/Camera  ( 7463): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
[        ] I/BufferQueueConsumer( 7463): [](id:1d2700000002,api:0,p:-1,c:7463) connect(): controlledByApp=true
[   +3 ms] E/libc    ( 7463): Access denied finding property "persist.vendor.camera.privapp.list"
[   +7 ms] E/CameraManagerGlobal( 7463): Camera 61 is not available. Ignore physical camera status change
[   +5 ms] W/CameraManagerGlobal( 7463): ignore the torch status update of camera: 21
[        ] W/CameraManagerGlobal( 7463): ignore the torch status update of camera: 22
[        ] W/CameraManagerGlobal( 7463): ignore the torch status update of camera: 61
[   +3 ms] I/Camera  ( 7463): startPreview
[  +87 ms] I/BufferQueueProducer( 7463): [SurfaceTexture-0-7463-0](id:1d2700000000,api:4,p:845,c:7463) connect(): api=4 producerControlledByApp=true
[        ] I/BufferQueueProducer( 7463): [ImageReader-640x480f100m1-7463-0](id:1d2700000001,api:4,p:845,c:7463) connect(): api=4
producerControlledByApp=false
[   +5 ms] I/Camera  ( 7463): CameraCaptureSession onConfigured
[        ] I/Camera  ( 7463): Updating builder settings
[        ] D/Camera  ( 7463): Updating builder with feature: ExposureLockFeature
[        ] D/Camera  ( 7463): Updating builder with feature: ExposurePointFeature
[        ] D/Camera  ( 7463): Updating builder with feature: ZoomLevelFeature
[        ] D/Camera  ( 7463): Updating builder with feature: AutoFocusFeature
[        ] D/Camera  ( 7463): Updating builder with feature: NoiseReductionFeature
[        ] I/Camera  ( 7463): updateNoiseReduction | currentSetting: fast
[        ] D/Camera  ( 7463): Updating builder with feature: FocusPointFeature
[        ] D/Camera  ( 7463): Updating builder with feature: ResolutionFeature
[        ] D/Camera  ( 7463): Updating builder with feature: SensorOrientationFeature
[        ] D/Camera  ( 7463): Updating builder with feature: FlashFeature
[        ] D/Camera  ( 7463): Updating builder with feature: ExposureOffsetFeature
[   +1 ms] D/Camera  ( 7463): Updating builder with feature: FpsRangeFeature
[        ] I/Camera  ( 7463): refreshPreviewCaptureSession
[ +400 ms] I/mali_config( 7463): @get_buffer_dataspace_setting: update dataspace (0x10020000 -> 0x08020000)
[  +66 ms] I/mali_config( 7463): @get_buffer_dataspace_setting: update dataspace (0x10020000 -> 0x08020000)
[  +83 ms] I/mali_config( 7463): @get_buffer_dataspace_setting: update dataspace (0x10020000 -> 0x08020000)
[  +66 ms] I/mali_config( 7463): @get_buffer_dataspace_setting: update dataspace (0x10020000 -> 0x08020000)
[  +66 ms] I/mali_config( 7463): @get_buffer_dataspace_setting: update dataspace (0x10020000 -> 0x08020000)
[  +66 ms] I/mali_config( 7463): @get_buffer_dataspace_setting: update dataspace (0x10020000 -> 0x08020000)
[ +451 ms] I/mali_config( 7463): @get_buffer_dataspace_setting: update dataspace (0x10020000 -> 0x08020000)
[ +586 ms] I/mali_config( 7463): @get_buffer_dataspace_setting: update dataspace (0x10020000 -> 0x08020000)
[+2107 ms] I/r_application_( 7463): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
[ +378 ms] I/Camera  ( 7463): runPictureAutoFocus
[        ] I/Camera  ( 7463): lockAutoFocus
[   +7 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[   +7 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[   +7 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: null | aeState: null
[  +21 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[   +6 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[   +8 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: null | aeState: null
[  +18 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[  +11 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[   +7 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: null | aeState: null
[  +18 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[  +12 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[   +5 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: null | aeState: null
[  +14 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[   +6 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[   +8 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: null | aeState: null
[  +24 ms] D/CameraCaptureCallback( 7463): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2

```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale en-AU)
    • Flutter version 3.3.3 on channel stable at /Users/ssheromova/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (3 weeks ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ssheromova/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ssheromova/Library/Android/sdk
    • Java binary at: /Users/ssheromova/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/ssheromova/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Redmi Note 8 Pro (mobile) • rkda597hcqdm7pfq                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 mini (mobile)   • 0093DF38-785E-4BCF-B58C-6AE49ED2D75D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
 </details>

**Comment by danagbemava-nc** [comment]
Hi @SofiSheromova, out of curiosity, why do you need to call `pausePreview` before `takePicture`?

**Comment by SofiSheromova** [comment]
In our flow, the user photographs the image, and then it is processed. During these actions, the user should see a frozen preview of the camera. 
If we first call takePicture, and then display the resulting image, then this leads to delays (the photo is taken in maximum quality), which we want to avoid.

**Comment by danagbemava-nc** [comment]
Thanks for the context. 

Issue is reproducible using the code sample provided above. This is only an issue on android. iOS and web work just fine. 
If you attempt to capture another image while it is not complete, you get 

```
CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)
```

Labeling for further investigation.

<details>
<summary>logs</summary>

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
I/CameraManagerGlobal( 5205): Connecting to camera service
I/Choreographer( 5205): Skipped 85 frames!  The application may be doing too much work on its main thread.
E/SurfaceSyncer( 5205): Failed to find sync for id=0
W/Parcel  ( 5205): Expecting binder but got null!
D/EGL_emulation( 5205): app_time_stats: avg=52.66ms min=2.71ms max=218.40ms count=25
D/EGL_emulation( 5205): app_time_stats: avg=35.18ms min=11.44ms max=158.93ms count=26
D/EGL_emulation( 5205): app_time_stats: avg=23.87ms min=2.31ms max=87.00ms count=36
D/EGL_emulation( 5205): app_time_stats: avg=12.24ms min=2.97ms max=44.60ms count=53
D/EGL_emulation( 5205): app_time_stats: avg=6.81ms min=1.44ms max=34.99ms count=58
D/EGL_emulation( 5205): app_time_stats: avg=16.37ms min=1.95ms max=112.69ms count=45
D/EGL_emulation( 5205): app_time_stats: avg=16.61ms min=4.00ms max=121.31ms count=50
D/EGL_emulation( 5205): app_time_stats: avg=20.28ms min=2.07ms max=164.58ms count=38
D/EGL_emulation( 5205): app_time_stats: avg=19.73ms min=2.15ms max=149.66ms count=42
D/CompatibilityChangeReporter( 5205): Compat change id reported: 78294732; UID 10160; state: DISABLED
D/EGL_emulation( 5205): app_time_stats: avg=30.54ms min=2.44ms max=145.12ms count=27
D/CompatibilityChangeReporter( 5205): Compat change id reported: 206033068; UID 10160; state: DISABLED
W/Camera  ( 5205): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
I/Camera  ( 5205): startPreview
D/EGL_emulation( 5205): app_time_stats: avg=25.54ms min=2.75ms max=149.09ms count=31
I/Camera  ( 5205): CameraCaptureSession onConfigured
I/Camera  ( 5205): Updating builder settings
D/Camera  ( 5205): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5205): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5205): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5205): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5205): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5205): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5205): Updating builder with feature: FocusPointFeature
D/Camera  ( 5205): Updating builder with feature: ResolutionFeature
D/Camera  ( 5205): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5205): Updating builder with feature: FlashFeature
D/Camera  ( 5205): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5205): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5205): refreshPreviewCaptureSession
D/EGL_emulation( 5205): app_time_stats: avg=111.46ms min=14.22ms max=569.67ms count=9
D/EGL_emulation( 5205): app_time_stats: avg=35.85ms min=9.23ms max=61.77ms count=28
D/EGL_emulation( 5205): app_time_stats: avg=34.93ms min=17.11ms max=55.91ms count=29
D/EGL_emulation( 5205): app_time_stats: avg=39.79ms min=8.96ms max=130.20ms count=23
D/EGL_emulation( 5205): app_time_stats: avg=33.67ms min=13.93ms max=50.88ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=33.87ms min=28.47ms max=50.20ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=33.87ms min=29.08ms max=52.03ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=33.89ms min=18.69ms max=50.28ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=33.90ms min=26.43ms max=51.15ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=33.86ms min=28.71ms max=54.94ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=33.81ms min=17.73ms max=51.07ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=33.81ms min=17.22ms max=52.23ms count=30
I/com.example.hs( 5205): Background concurrent copying GC freed 32137(1807KB) AllocSpace objects, 3(60KB) LOS objects, 49% free, 2721KB/5442KB, paused 440us,93us total 235.518ms
D/EGL_emulation( 5205): app_time_stats: avg=37.37ms min=7.95ms max=71.92ms count=27
D/EGL_emulation( 5205): app_time_stats: avg=33.94ms min=11.04ms max=53.79ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=38.79ms min=16.51ms max=76.00ms count=26
D/EGL_emulation( 5205): app_time_stats: avg=34.31ms min=7.94ms max=57.02ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=33.78ms min=14.94ms max=50.76ms count=30
D/EGL_emulation( 5205): app_time_stats: avg=52.07ms min=30.53ms max=498.90ms count=25
I/Camera  ( 5205): runPrecaptureSequence
I/Camera  ( 5205): refreshPreviewCaptureSession
D/CameraCaptureCallback( 5205): CameraCaptureCallback | state: STATE_WAITING_PRECAPTURE_START | afState: 0 | aeState: 2
D/CameraCaptureCallback( 5205): CameraCaptureCallback | state: STATE_WAITING_PRECAPTURE_DONE | afState: 0 | aeState: 2
I/Camera  ( 5205): captureStillPicture
D/Camera  ( 5205): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5205): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5205): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5205): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5205): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5205): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5205): Updating builder with feature: FocusPointFeature
D/Camera  ( 5205): Updating builder with feature: ResolutionFeature
D/Camera  ( 5205): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5205): Updating builder with feature: FlashFeature
D/Camera  ( 5205): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5205): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5205): sending capture request
D/CameraCaptureCallback( 5205): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
I/Camera  ( 5205): unlockAutoFocus
I/Camera  ( 5205): refreshPreviewCaptureSession
I/Camera  ( 5205): open | onDisconnected
I/Camera  ( 5205): close
I/Camera  ( 5205): CameraCaptureSession onClosed
W/MessageQueue( 5205): Handler (android.os.Handler) {1d9fae} sending message to a Handler on a dead thread
W/MessageQueue( 5205): java.lang.IllegalStateException: Handler (android.os.Handler) {1d9fae} sending message to a Handler on a dead thread
W/MessageQueue( 5205): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
W/MessageQueue( 5205): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue( 5205): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue( 5205): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue( 5205): 	at android.os.Handler.post(Handler.java:427)
W/MessageQueue( 5205): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2353)
W/MessageQueue( 5205): 	at android.hardware.camera2.utils.TaskDrainer.postDrained(TaskDrainer.java:202)
W/MessageQueue( 5205): 	at android.hardware.camera2.utils.TaskDrainer.checkIfDrainFinished(TaskDrainer.java:197)
W/MessageQueue( 5205): 	at android.hardware.camera2.utils.TaskDrainer.beginDrain(TaskDrainer.java:185)
W/MessageQueue( 5205): 	at android.hardware.camera2.utils.TaskSingleDrainer.beginDrain(TaskSingleDrainer.java:87)
W/MessageQueue( 5205): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$SequenceDrainListener.onDrained(CameraCaptureSessionImpl.java:946)
W/MessageQueue( 5205): 	at android.hardware.camera2.utils.TaskDrainer.lambda$postDrained$0$android-hardware-camera2-utils-TaskDrainer(TaskDrainer.java:207)
W/MessageQueue( 5205): 	at android.hardware.camera2.utils.TaskDrainer$$ExternalSyntheticLambda0.run(Unknown Source:2)
W/MessageQueue( 5205): 	at android.os.Handler.handleCallback(Handler.java:942)
W/MessageQueue( 5205): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/MessageQueue( 5205): 	at android.os.Looper.loopOnce(Looper.java:201)
W/MessageQueue( 5205): 	at android.os.Looper.loop(Looper.java:288)
W/MessageQueue( 5205): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/Camera  ( 5205): open | onClosed
D/EGL_emulation( 5205): app_time_stats: avg=1555.75ms min=12.81ms max=12020.17ms count=8
I/flutter ( 5205): CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)
D/EGL_emulation( 5205): app_time_stats: avg=428.47ms min=1.58ms max=4981.90ms count=13
I/flutter ( 5205): CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.4 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (13 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • Nexus (mobile)              • 00008020-001875E83A38002E            • ios            • iOS 16.0.2 20A380
    • iPhone 14 Pro (mobile)      • 4302007A-B132-4B89-887A-C5993FCA3284 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 106.0.5249.119
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

```
[✓] Flutter (Channel master, 3.5.0-8.0.pre.31, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
    • Flutter version 3.5.0-8.0.pre.31 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0ad71e8727 (11 hours ago), 2022-10-18 10:06:30 +0800
    • Engine revision 465ccd2974
    • Dart version 2.19.0 (build 2.19.0-314.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • Nexus (mobile)              • 00008020-001875E83A38002E            • ios            • iOS 16.0.2 20A380
    • iPhone 14 Pro (mobile)      • 4302007A-B132-4B89-887A-C5993FCA3284 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 106.0.5249.119
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

**Comment by GaryQian** [comment]
@camsim99

**Comment by SofiSheromova** [comment]
The same bug on Android 12 (Pixel 5a device)

**Comment by vysotsky** [comment]
@danagbemava-nc I ran into the same problem. My initial thought was that this method `pausePreview` should actually be used to preview the image before shooting, so that we don't have to worry about cleaning up the file if the user wants to retake the shot. Also it would help to avoid the delay while processing the image. So this is definitely a weird behaviour. I would appreciate if you could somehow prioritise this issue or at least provide some information that you are or are not going to work on it. Thank you in advance!

**Comment by Fintasys** [comment]
I can reproduce it with my Pixel 6. Are there any workarounds for this issue? 😢

**Comment by camsim99** [comment]
This issue should be fixed in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin. If you try it out and find a similar issue with that implementation, please file a separate issue!
