### ISSUE TITLE
App crashes when touch the screen with stlyus button pressed

### ISSUE THREAD

**Issue by KRBILNR** [flutter/flutter#113503]
Hi I'm making a drawing app using Samsung tablet S6, when I touch the screen with the pressed stylus button, app crashes.

I checked the gitHub discussion but couldn't find the solution.

all I want is just app is not crashing when I touch the screen with stylus button pressed.

Here's my sample code 

```
import 'dart:ui
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main () {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      child: Scaffold(
        body: Stack(
          children: [
            Positioned.fill(child: Container(
              color: Colors.yellow,
            )),
            GestureDetector(
              child: Listener(
                behavior: HitTestBehavior.opaque,
                onPointerHover: (s) {
                  if(s.kind == PointerDeviceKind.stylus && s.buttons == kPrimaryStylusButton) {
                    print("Stylus is hovering");
                    // it works well
                  }
                },
                onPointerDown: (s) {
                  if(s.kind == PointerDeviceKind.stylus) {
                    print("Stylus is touched the screen");
                    // works well
                  } else if (s.kind == PointerDeviceKind.stylus && s.buttons == kPrimaryStylusButton) {
                    print("Stylus is touched the screen with pressed button");
                  }
                },
                onPointerMove: (s) {
                  if(s.kind == PointerDeviceKind.stylus) {
                    print("Stylus is moving on the screen");
                    // it works well
                  } else if (s.kind == PointerDeviceKind.stylus && s.buttons == kPrimaryStylusButton) {
                    print("Stylus is moving on the screen with pressed button");
                  }
                },
                onPointerCancel: (s) {
                  print("detached the stylus");
                },
              ),
            ),

          ],
        ),
      ),
    );
  }
}
```

and Error Log 
>Error Log 

```
E/MessageQueue-JNI(26267): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI(26267): java.lang.AssertionError: Unexpected masked action
E/MessageQueue-JNI(26267):  at io.flutter.embedding.android.AndroidTouchProcessor.getPointerChangeForAction(AndroidTouchProcessor.java:384)
E/MessageQueue-JNI(26267):  at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:124)
E/MessageQueue-JNI(26267):  at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:104)
E/MessageQueue-JNI(26267):  at io.flutter.embedding.android.FlutterView.onTouchEvent(FlutterView.java:940)
E/MessageQueue-JNI(26267):  at android.view.View.dispatchTouchEvent(View.java:15076)
E/MessageQueue-JNI(26267):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3917)
E/MessageQueue-JNI(26267):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3581)
E/MessageQueue-JNI(26267):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/MessageQueue-JNI(26267):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/MessageQueue-JNI(26267):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/MessageQueue-JNI(26267):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/MessageQueue-JNI(26267):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/MessageQueue-JNI(26267):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/MessageQueue-JNI(26267):  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1015)
E/MessageQueue-JNI(26267):  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
E/MessageQueue-JNI(26267):  at android.app.Activity.dispatchTouchEvent(Activity.java:4265)
E/MessageQueue-JNI(26267):  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:973)
E/MessageQueue-JNI(26267):  at android.view.View.dispatchPointerEvent(View.java:15335)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7794)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7567)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6901)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7122)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7179)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10354)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10202)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10158)
E/MessageQueue-JNI(26267):  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10486)
E/MessageQueue-JNI(26267):  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
E/MessageQueue-JNI(26267):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI(26267):  at android.os.MessageQueue.next(MessageQueue.java:335)
E/MessageQueue-JNI(26267):  at android.os.Looper.loopOnce(Looper.java:186)
E/MessageQueue-JNI(26267):  at android.os.Looper.loop(Looper.java:313)
E/MessageQueue-JNI(26267):  at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MessageQueue-JNI(26267):  at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI(26267):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MessageQueue-JNI(26267):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
D/AndroidRuntime(26267): Shutting down VM
I/flutter (26267): Hovering stylus and button is pressed!
E/AndroidRuntime(26267): FATAL EXCEPTION: main
E/AndroidRuntime(26267): Process: com.example.stylus_test2, PID: 26267
E/AndroidRuntime(26267): java.lang.AssertionError: Unexpected masked action
E/AndroidRuntime(26267):    at io.flutter.embedding.android.AndroidTouchProcessor.getPointerChangeForAction(AndroidTouchProcessor.java:384)
E/AndroidRuntime(26267):    at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:124)
E/AndroidRuntime(26267):    at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:104)
E/AndroidRuntime(26267):    at io.flutter.embedding.android.FlutterView.onTouchEvent(FlutterView.java:940)
E/AndroidRuntime(26267):    at android.view.View.dispatchTouchEvent(View.java:15076)
E/AndroidRuntime(26267):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3917)
E/AndroidRuntime(26267):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3581)
E/AndroidRuntime(26267):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/AndroidRuntime(26267):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/AndroidRuntime(26267):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/AndroidRuntime(26267):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/AndroidRuntime(26267):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/AndroidRuntime(26267):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/AndroidRuntime(26267):    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1015)
E/AndroidRuntime(26267):    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
E/AndroidRuntime(26267):    at android.app.Activity.dispatchTouchEvent(Activity.java:4265)
E/AndroidRuntime(26267):    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:973)
E/AndroidRuntime(26267):    at android.view.View.dispatchPointerEvent(View.java:15335)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7794)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7567)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6901)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7122)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7179)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10354)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10202)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10158)
E/AndroidRuntime(26267):    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10486)
E/AndroidRuntime(26267):    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
E/AndroidRuntime(26267):    at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(26267):    at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(26267):    at android.os.Looper.loopOnce(Looper.java:186)
E/AndroidRuntime(26267):    at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(26267):    at android.app.ActivityThread.main(ActivityThread.java:8663)
E/AndroidRuntime(26267):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26267):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/AndroidRuntime(26267):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/Process (26267): Sending signal. PID: 26267 SIG: 9
Lost connection to device.
```

> My flutter doctor 

```
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.19043.2006], locale ko-KR)
    • Flutter version 3.3.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (6 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\park\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • SM P610 (mobile)  • R54N602BPJX • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19043.2006]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 106.0.1370.34

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by FusoraTech** [comment]
Related: https://github.com/flutter/flutter/issues/111068

**Comment by KRBILNR** [comment]
For my project, I downgrade the flutter to 3.0.5 but my app cannot detect the touch event with stylus button pressed

**Comment by huycozy** [comment]
@FusoraTech 
This is a known issue being tracked at #111068. You can leave there your comment and react an upvote to the original comment will help to raise the issue.

Closing this issue as a duplicate, so please follow up on it for further updates.
