### ISSUE TITLE
examples/platform_view build failures on iOS simulator

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#113566]
Engine roll: https://github.com/flutter/flutter/pull/113560
Build output: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8800033243652895169/+/u/run_test.dart_for_build_tests_shard_and_subshard_2_4/test_stdout

There is quite a lot of output, but note that the actual test entries which are failing are iOS simulator builds.

```
[        ] "flutter ios" took 25,854ms.
[   +4 ms] Encountered error while building for device.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:361:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1244:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[        ] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1
╔═╡ERROR╞═══════════════════════════════════════════════════════════════════════
║ Command exited with exit code 1 but expected: zero exit code.
║ Command: ../../bin/flutter build ios --no-codesign --debug -v
║ Relative working directory: examples/platform_view
╚═══════════════════════════════════════════════════════════════════════════════
```

**Comment by zanderso** [comment]
Maybe related https://github.com/flutter/flutter/issues/113539

**Comment by bdero** [comment]
Yup, that looks like the same issue, closing this one.
