### ISSUE TITLE
Flutter fails under Fedora 25

### ISSUE THREAD

**Issue by macropas** [flutter/flutter#11351]
Strange message from `flutter doctor` : `Downloaded executables cannot execute on host` and the fail after `flutter run`
---

```bash
$ flutter create myapp
Creating project myapp...
Wrote 54 files.

Running "flutter packages get" in myapp...            7.1s

[✓] Flutter is fully installed. (on Linux, locale en_US.UTF-8, channel alpha)
[✓] Android toolchain - develop for Android devices is fully installed. (Android SDK 26.0.0)
[✓] Android Studio is fully installed. (version 2.3)
[✓] IntelliJ IDEA Community Edition is fully installed. (version 2017.2)
[✓] Connected devices is fully installed.

All done! In order to run your application, type:

  $ cd myapp
  $ flutter run

Your main program file is lib/main.dart in the myapp directory.

```

```bash
$ cd myapp
```

```bash
$ flutter run
Launching lib/main.dart on MotoG3 in debug mode...
Running 'gradle assembleDebug'...                         

Oops; flutter has exited unexpectedly.
Crash report written to /home/johndoe/myapp/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.

* Where:
Script '/home/johndoe/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 285

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command '/home/johndoe/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

```bash
$ cat /home/johndoe/myapp/flutter_01.log
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build flx --suppress-analytics --target /home/johndoe/myapp/lib/main.dart --output-file /home/johndoe/myapp/build/app/intermediates/flutter/debug/app.flx --snapshot /home/johndoe/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin --depfile /home/johndoe/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --working-dir /home/johndoe/myapp/build/app/intermediates/flutter/debug/flx

## exception

ProcessException: ProcessException: No such file or directory
  Command: /home/johndoe/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot --snapshot_kind=script --vm_snapshot_data=/home/johndoe/flutter/bin/cache/artifacts/engine/linux-x64/vm_isolate_snapshot.bin --isolate_snapshot_data=/home/johndoe/flutter/bin/cache/artifacts/engine/linux-x64/isolate_snapshot.bin --packages=/home/johndoe/myapp/.packages --script_snapshot=/home/johndoe/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin --dependencies=/home/johndoe/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin.d /home/johndoe/myapp/lib/main.dart


#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:125)
<asynchronous suspension>
#1      createSnapshot (package:flutter_tools/src/flx.dart:58)
#2      build (package:flutter_tools/src/flx.dart:86)
<asynchronous suspension>
#3      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:44)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#5      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#6      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#10     new Future.sync (dart:async/future.dart:206)
#11     CommandRunner.run (package:args/command_runner.dart:109)
#12     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#13     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#14     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#15     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1467)
#19     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#20     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#22     main (file:///home/johndoe/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


## flutter doctor


[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/johndoe/flutter
    • Framework revision d36e2f6191 (4 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /home/johndoe/Android/Sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /home/johndoe/Android/Sdk
    • Java binary at: /home/johndoe/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/johndoe/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 15.1
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • MotoG3 • ZY223D95JP • android-arm • Android 6.0.1 (API 23)



```

```bash
$ flutter analyze
Analyzing /home/johndoe/myapp...
No issues found!
Ran in 6.1s
```

**Comment by macropas** [comment]
Solution
```bash
$ sudo dnf install libstdc++.i686
```
