### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Invalid port 80810

### ISSUE THREAD

**Issue by shafikvpz** [flutter/flutter#113531]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Invalid port 80810
```
#0      _throwOnBadPort (dart:io-patch/socket_patch.dart:125:5)
#1      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:668:5)
#2      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1827:26)
#3      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#4      Socket._startConnect (dart:io-patch/socket_patch.dart:2048:22)
#5      Socket.startConnect (dart:io/socket.dart:759:21)
#6      _ConnectionTarget.connect (dart:_http/http_impl.dart:2453:20)
#7      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2867:12)
#8      _HttpClient._getConnection (dart:_http/http_impl.dart:2872:12)
#9      _HttpClient._openUrl (dart:_http/http_impl.dart:2727:12)
#10     _HttpClient.openUrl (dart:_http/http_impl.dart:2591:7)
#11     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)
#12     WebSocket.connect (dart:_http/websocket.dart:320:22)
#13     _defaultOpenChannel.<anonymous closure> (package:flutter_tools/src/vmservice.dart:145:22)
#14     _defaultOpenChannel (package:flutter_tools/src/vmservice.dart:150:33)
#15     createVmServiceDelegate (package:flutter_tools/src/vmservice.dart:343:50)
#16     _connect (package:flutter_tools/src/vmservice.dart:365:54)
#17     connectToVmService (package:flutter_tools/src/vmservice.dart:326:19)
#18     FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:252:27)
#19     _rootRunUnary (dart:async/zone.dart:1399:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#24     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
```
```
[✓] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19043.2130], locale en-US)
    • Flutter version 3.3.4 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (12 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\shafi\AppData\Local\Android\sdk
    • Platform android-31, build-tools 33.0.0
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    • Visual Studio Community 2017 version 15.9.28307.1000
    • Windows 10 SDK version 10.0.17763.0
    ✗ Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.3)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at C:\Users\shafi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.2130]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 106.0.1370.42

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: eb6d86ee27deecba4a83536aa20f366a6044895c

**Comment by exaby73** [comment]
Hello @shafikvpz. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
