### ISSUE TITLE
[flutter_tools] RPCError: lookupResolvedPackageUris: (-32603)

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#113636]
on `beta/3.4.0-34.1.pre`
with command `flutter debug_adapter`

```
RPCError: lookupResolvedPackageUris: (-32603)
lookupResolvedPackageUris: [Sentinel kind: Collected, valueAsString: Unrecognized isolateId: 2157] from lookupResolvedPackageUris()
#0      ChromeProxyService._throwSentinel (package:dwds/src/services/chrome_proxy_service.dart:1104:5)
#1      ChromeProxyService._checkIsolate (package:dwds/src/services/chrome_proxy_service.dart:1096:7)
#2      ChromeProxyService.lookupResolvedPackageUris (package:dwds/src/services/chrome_proxy_service.dart:686:5)<asynchronous suspension>
#3      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)<asynchronous suspension>

at new _OutstandingRequest(vm_service.dart:1746)
at VmService._call(vm_service.dart:2262)
at VmService.lookupResolvedPackageUris(vm_service.dart:2095)
at IsolateManager._lookupResolvedPackageUris(isolate_manager.dart:550)
at ThreadInfo.resolveUrisToPathsBatch(isolate_manager.dart:910)
at ThreadInfo.resolveUrisToPackageLibPathsBatch(isolate_manager.dart:877)
at IsolateManager._sendLibraryDebuggables(isolate_manager.dart:720)
at <asynchronous gap>(async)
at Future.wait.<anonymous closure>(future.dart:522)
at <asynchronous gap>(async)
at IsolateManager._configureIsolate(isolate_manager.dart:361)
at <asynchronous gap>(async)
at IsolateManager.registerIsolate(isolate_manager.dart:215)
at <asynchronous gap>(async)
at IsolateManager.handleEvent(isolate_manager.dart:163)
at <asynchronous gap>(async)
at DartDebugAdapter.handleIsolateEvent(dart.dart:1859)
at <asynchronous gap>(async)
at DartDebugAdapter._withErrorHandling(dart.dart:2100)
at <asynchronous gap>(async)
```

**Comment by christopherfujino** [comment]
cc @elliette

**Comment by christopherfujino** [comment]
cc @elliette

**Comment by christopherfujino** [comment]
Updated stacktrace from beta/3.7.0-1.2.pre (with package:dwds version 16.0.1):

```
RPCError:
lookupResolvedPackageUris: (-32603) lookupResolvedPackageUris: [Sentinel kind: Collected, valueAsString: Unrecognized isolateId: 9154] from lookupResolvedPackageUris()
#0      ChromeProxyService._throwSentinel (package:dwds/src/services/chrome_proxy_service.dart:1109:5)
#1      ChromeProxyService._checkIsolate (package:dwds/src/services/chrome_proxy_service.dart:1101:7)
#2      ChromeProxyService.lookupResolvedPackageUris (package:dwds/src/services/chrome_proxy_service.dart:691:5)
<asynchronous suspension>
#3      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
```

**Comment by elliette** [comment]
Adding @annagrin 

This might be related to https://github.com/dart-lang/webdev/issues/1869. Essentially we can get into a bad state on a multiple hot restarts due to stale isolates. 

Let's close this once https://github.com/dart-lang/webdev/issues/1869 is fixed, and if it appears again after that we will know there is still more investigation that is needed.

**Comment by christopherfujino** [comment]
> Let's close this once [dart-lang/webdev#1869](https://github.com/dart-lang/webdev/issues/1869) is fixed, and if it appears again after that we will know there is still more investigation that is needed.

SGTM

**Comment by annagrin** [comment]
Now this looks to me very similar to https://github.com/flutter/flutter/issues/123018. The sentinel exception is converted to an error. @bkonyi the following code in DDS throws: https://github.com/dart-lang/sdk/blob/2d1373bc56f7ebb4391f3f458ebb3c1e9591be6d/pkg/dds/lib/src/dap/isolate_manager.dart#L967

Should it check for a sentinel exception and retry getting a new isolate id instead?
