### ISSUE TITLE
I dont know if this is bugs or my code conventions using GetX

### ISSUE THREAD

**Issue by haroldcalayan-mycwt** [flutter/flutter#113664]
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
                      The following assertion was thrown while notifying listeners for AnimationController:
                      'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14:
                      'notification.metrics.axis == widget.axis': is not true.

                      Either the assertion indicates an error in the framework itself, or we should provide substantially
                      more information in this error message to help you determine and fix the underlying cause.
                      In either case, please report this assertion by filing a bug on GitHub:
                        https://github.com/flutter/flutter/issues/new?template=2_bug.md

                      When the exception was thrown, this was the stack:
                      #2      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:243:14)
                      #3      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
                      #4      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3094:18)
                      #5      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
                      #6      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
                      #7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
                      #8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
                      #9      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
                      #10     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
                      #11     Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4441:24)
                      #12     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
                      #13     DrivenScrollActivity.dispatchOverscrollNotification (package:flutter/src/widgets/scroll_activity.dart:658:108)
                      #14     ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:933:15)
                      #15     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:285:9)
                      #16     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:78:18)
                      #17     DrivenScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:647:18)
                      #18     AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
                      #19     AnimationController._tick (package:flutter/src/animation/animation_controller.dart:837:5)
                      #20     Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
                      #21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
                      #22     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1079:11)
                      #23     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
                      #24     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1077:17)
                      #25     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:994:5)
                      #26     _invoke1 (dart:ui/hooks.dart:167:13)
                      #27     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:296:5)
                      #28     _beginFrame (dart:ui/hooks.dart:104:31)
                      (elided 2 frames from class _AssertionError)

                      The AnimationController notifying listeners was:
                        AnimationController#9c2e0(⏭ 822.857; paused; for DrivenScrollActivity)
                      ════════════════════════════════════════════════════════════════════════════════════════════════════

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22621.674], locale en-PH)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Community Edition (version 2022.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by darshankawar** [comment]
@haroldcalayan-mycwt 
Check [this](https://github.com/flutter/flutter/issues/107772) similar issue and underlying comments / solutions mentioned and see if they work in your case.

https://github.com/flutter/flutter/issues/107772#issuecomment-1199083857
https://github.com/flutter/flutter/issues/107772#issuecomment-1219906155
https://github.com/flutter/flutter/issues/107772#issuecomment-1233937098

Closing for now. If above doesn't work in your case, please provide a complete minimal reproducible code sample without using third party plugin which throws the same error log, so that we can properly analyze the issue.
