### ISSUE TITLE
_castError: null check operator used on a null value

### ISSUE THREAD

**Issue by wildanfh** [flutter/flutter#113742]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

_CastError: Null check operator used on a null value

```
#0      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:497:20)
#1      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:565:5)
<asynchronous suspension>
#2      HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:754:16)
<asynchronous suspension>
#3      HotRunner.restart (package:flutter_tools/src/run_hot.dart:694:38)
<asynchronous suspension>
#4      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1699:40)
<asynchronous suspension>
#5      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1739:7)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19042.2130], locale en-ID)
    • Flutter version 3.3.4 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\DTECH-ENGINEERING\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development
      with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.1
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.3739.24

[✓] VS Code (version 1.72.2)
    • VS Code at C:\Users\DTECH-ENGINEERING\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • LUNA G9 (mobile)  • NJED00200B9E • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [Version 10.0.19042.2130]
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 105.0.1343.42

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host
      lookup: 'cocoapods.org'
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed
      host lookup: 'maven.google.com'
    ✗ HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host
      lookup: 'pub.dev'
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed
      host lookup: 'cloud.google.com'

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
@wildanfh 
This issue has already been fixed and merged into master branch: https://github.com/flutter/flutter/pull/108771, so I suggest you to switch to latest master to see the change. It may not be in stable version yet.

Since this is fixed already, I will close it. If you disagree, write in comments and I'll reopen it.
