### ISSUE TITLE
[iOS] Moving textfield cursor with space button gesture causes exception

### ISSUE THREAD

**Issue by DjordjeMancic97** [flutter/flutter#113936]
## Steps to Reproduce

1. Open keyboard on iOS and try moving cursor inside TextField with the space button gesture

Everything looks fine but terminal is spamming exception:

```
The following _CastError was thrown during method call
TextInputClient.updateFloatingCursor:
type 'int' is not a subtype of type 'double' in type cast

When the exception was thrown, this was the stack:
#0      _toTextPoint (package:flutter/src/services/text_input.dart:1513:51)
#1      TextInput._handleTextInputInvocation
(package:flutter/src/services/text_input.dart:1827:58)
#2      TextInput._loudlyHandleTextInputInvocation
(package:flutter/src/services/text_input.dart:1701:20)
#3      MethodChannel._handleAsMethodCall
(package:flutter/src/services/platform_channel.dart:536:55)
#4      MethodChannel.setMethodCallHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:529:34)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:387:35)
#6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#10     _invoke2 (dart:ui/hooks.dart:188:10)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#14     PlatformDispatcher._dispatchPlatformMessage
(dart:ui/platform_dispatcher.dart:599:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 3 frames from dart:async)

call:
  MethodCall(TextInputClient.updateFloatingCursor, [1, FloatingCursorDragState.update,
  {X:
  0.3348251229786763, Y: 0}])

```

Flutter doctor output:
```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.72.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

Also another important point is- this exception is not caught by Crashlytics somehow. Don't know why but I would like to be notified about everything. If someone knows the reason why its not reporting this please let me know or is this question better to ask in Crashlytics github?

**Comment by exaby73** [comment]
Hello @DjordjeMancic97. I can reproduce this issue on stable but it seems fixed on master. Please upgrade to the master channel and confirm if this is the case.
