### ISSUE TITLE
[flutter_tools] `flutter create --platforms=<>` on a project with flavors will crash

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#113978]
For example:

```
[   +1 ms] The Xcode project defines schemes: free, paid
[   +5 ms] "flutter create" took 2,080ms.
[   +2 ms] You must specify a --flavor option to select one of the available schemes.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      XcodeProjectInfo.reportFlavorNotFoundAndExit
           (package:flutter_tools/src/ios/xcodeproj.dart:489:7)
           #2      IosProject.buildSettingsForBuildInfo
(package:flutter_tools/src/xcode_project.dart:270:12)
           <asynchronous suspension>
           #3      IosProject._parseProductBundleIdentifier
           (package:flutter_tools/src/xcode_project.dart:202:51)
           <asynchronous suspension>
           #4      IosProject.productBundleIdentifier
(package:flutter_tools/src/xcode_project.dart:179:41)
           <asynchronous suspension>
           #5      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:141:40)
           <asynchronous suspension>
           #6      CreateBase.getOrganization
(package:flutter_tools/src/commands/create_base.dart:259:49)
           <asynchronous suspension>
           #7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:243:33)
           <asynchronous suspension>
           #8      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1244:27)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #14     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

Note that `flutter create` does not implement the `--flavors` flag, so this comment is misleading.

**Comment by christopherfujino** [comment]
cc @a-wallen
