### ISSUE TITLE
```FlutterEngine```s created from ```FlutterEngineGroup``` produces errors after hot restart

### ISSUE THREAD

**Issue by dayoul** [flutter/flutter#114005]
Currently I have 2 different ```FlutterEngine``` made from a same ```FlutterEngineGroup```.
One engine is created at ```class Application extends FlutterApplication > onCreate()```, and another one is created inside ```class BaseActivity extends FlutterActivity > provideFlutterEngine()```.
And my app is using ```SendPort``` to communicate between engines(isolates), and it works fine even if I send any dart instances(```sendPort.send(MyInstance())```) before hot restart. 
But after hot restart, I get error like below and only basic dart type is allowed to be sent(int, String...).
```
Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
```
Any workaround for this? It seems like after the hot restart, ```FlutterEngine``` s seems not sharing resources even if they are created from same ```FlutterEngineGroup```.

Thanks in advance.

Result of ```flutter doctor -v```
```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.18363.2212], locale ko-KR)
    • Flutter version 3.0.1 at C:\flutter_windows_3.0.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2
```

**Comment by danagbemava-nc** [comment]
Hi @dayoul, can you upgrade to the latest version of flutter to see if you still experience this issue? 

If you do, please provide the updated output of `flutter doctor -v` along with a complete minimal reproducible code sample, preferably in a repo, that we can clone along with steps to reproduce so that we can investigate this issue. 

Thank you

**Comment by dayoul** [comment]
Hello @danagbemava-nc, I have upgraded flutter to the latest version and the issue is again reproduced. 
Below is the result of ```flutter doctor -v```
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.4 21F79 darwin-x64, locale ko-KR)
    • Flutter version 3.3.5 on channel stable at /Users/Dan/KnoxTeams/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (6 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

And I have created [sample repository](https://github.com/dayoul/flutter_engine_group_error) to reproduce this issue. 
Please check in Android device.

Thanks.

**Comment by danagbemava-nc** [comment]
Issue is reproducible using the code sample provided above. 

The code sample has been attached below for easy access. 

Labeling for further insight from the team. 

<details>
<summary>logs</summary>


### On First Load

```
I/flutter ( 9162): REQUEST from ActivityEngine::: 1
I/flutter ( 9162): RESPONSE from ApplicationEngine::: 2
```

### After hot restart

```
I/flutter ( 9402): REQUEST from ActivityEngine::: 1
I/flutter ( 9402): Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance) #0      _SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:249:43)
I/flutter ( 9402): #1      _SendPortImpl.send (dart:isolate-patch/isolate_patch.dart:230:5)
I/flutter ( 9402): #2      setApplicationEngineReceiver.<anonymous closure>
package:flutter_engine_group_project/isolate_executor.dart:22
I/flutter ( 9402): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
I/flutter ( 9402): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
I/flutter ( 9402): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
I/flutter ( 9402): #6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
I/flutter ( 9402): #7      _StreamController._add (dart:async/stream_controller.dart:648:7)
I/flutter ( 9402): #8      _StreamController.add (dart:async/stream_controller.dart:596:5)
I/flutter ( 9402): #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.5, on macOS 13.0 22A380 darwin-arm, locale en-GB)
    • Flutter version 3.3.5 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (6 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

```
[!] Flutter (Channel master, 3.5.0-10.0.pre.101, on macOS 13.0 22A380 darwin-arm64, locale en-GB)
    • Flutter version 3.5.0-10.0.pre.101 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b00b2f1bea (49 minutes ago), 2022-10-26 01:55:24 -0400
    • Engine revision ac95a3a4cc
    • Dart version 2.19.0 (build 2.19.0-339.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```
</details>

[flutter_engine_group_error.zip](https://github.com/flutter/flutter/files/9866860/flutter_engine_group_error.zip)

**Comment by GaryQian** [comment]
@gaaclarke This seems to be in your domain, have any thoughts?

**Comment by gaaclarke** [comment]
> @gaaclarke This seems to be in your domain, have any thoughts?

Yea, it's very odd.  I don't have any ideas off the top of my head but since the error manifests in the Dart VM I bet they may have a pretty good idea what is causing this.  They are very interested in making sure `FlutterEngineGroup` functions properly too so that will help.

**Comment by dayoul** [comment]
Hello @GaryQian , @gaaclarke . Do I have to raise this issue to [Dart](https://github.com/dart-lang/sdk)?

**Comment by gaaclarke** [comment]
@dayoul, I'll page them.  Paging @a-siva

**Comment by a-siva** [comment]
I presume by 'hot restart' it means the isolate running the engine is shutdown and a new isolate is started.

In the case of 'hot reload' all the isolates in the group are reloaded and so it is possible to continue sending any Dart instance.
In this case I think only one of the isolates is being re started and not the other and so the two engines (isolates) end up in different isolate groups as a result of which it is an error to send any Dart instance and only basic dart types are allowed across ports.

**Comment by dayoul** [comment]
I found a workaround for this issue. I was using ```IsolateNameServer``` from ```dart:ui``` only when sending data from Engine A to Engine B(Engine B's ```SendPort``` is stored in ```IsolateNameServer```). When Engine B responses to Engine A, Engine B was getting Engine A's ```SendPort``` from the instance data received from Engine A. But I have fixed my code to store Engine A's ```SendPort``` in ```IsolateNameServer``` and to let Engine B fetch the response ```SendPort```(Engine A's) from ```IsolateNameServer```, it finally works event if I do hot restart. 
What is the difference between using ```SendPort``` from ```IsolateNameServer``` and just the ```SendPort```?

**Comment by gaaclarke** [comment]
The other workaround is to use platform channels.  That's what the sample code for FlutterEngineGroup uses.  Enabling SendPort communication between engines was kind of an accident.  What a-siva said makes sense.  I don't think this is high priority since there are 3 workarounds:
1) Use platform channels
1) Only communiate with basic dart types
1) The workaround described by dayoul

**Comment by a-siva** [comment]
This appears to be a duplicate of https://github.com/flutter/flutter/issues/124546 and most of the work to fix it appears to be in the engine. Will use the other issue for tracking purposes.
