### ISSUE TITLE
[image_picker] ANR: io.flutter.plugins.imagepicker.FileUtils.getImageExtension

### ISSUE THREAD

**Issue by rohansohonee** [flutter/flutter#114080]
**ANR stack trace:**
```
main (timed waiting): tid=1 systid=21806 
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at android.content.ContentResolver$ResultListener.waitForResult(ContentResolver.java:979)
       at android.content.ContentResolver.getType(ContentResolver.java:930)
       at io.flutter.plugins.imagepicker.FileUtils.getImageExtension(FileUtils.java)
       at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java)
       at android.app.Activity.dispatchActivityResult(Activity.java:8541)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5537)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5585)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2315)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8550)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Device details:**
```
Device
Brand:samsung
Model:Galaxy A50
Orientation: Unknown
RAM free: Unknown
Disk free: Unknown
Operating System
Version:Android 11
Orientation: Unknown
Rooted:No
ANR
Date:Oct 25, 2022, 6:20:19 AM
```

**Pubspec.yaml:**
```
image_picker: 0.8.5+3
```

**Flutter version:**
```
Flutter 3.3.3 • channel stable
```

**Additional context**
Reported from firebase crashlytics. Don't know the steps to reproduce this ANR.

**Comment by huycozy** [comment]
@rohansohonee Look like the issue is caused when choosing image from gallery. Since it occurred in production and can not reproduce locally, I will label this for further insights from the team. Thanks!

**Comment by stuartmorgan** [comment]
Hanging to the extent that it triggers an ANR seems like a potential OS issue, but in general since that codepath is doing file operations we should move it off of the main thread (especially since we can trivially reply from other threads now).
