### ISSUE TITLE
Confusing error message when NetworkImage receives invalid url

### ISSUE THREAD

**Issue by hundeva** [flutter/flutter#11405]
## Steps to Reproduce

I realise that this is a very minor issue, though it is fairly inconvenient. For example, the following exception was thrown by something like this:

``` dart
new Image.network('invalidurl');
```

The helpful part of the exception are the last two lines, a more descriptive error would be appreciated.

## Logs

```I/flutter ( 3788): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter ( 3788): The following ArgumentError was thrown resolving a single-frame image stream:
I/flutter ( 3788): Invalid argument(s): No host specified in URI
I/flutter ( 3788): file:///data/user/0/com.example.app/cache/AppCLU8O5/App/lib/invalidurl
I/flutter ( 3788): 
I/flutter ( 3788): When the exception was thrown, this was the stack:
I/flutter ( 3788): #0      _HttpClient._openUrl (http_impl.dart:1788)
I/flutter ( 3788): #1      _HttpClient.openUrl (http_impl.dart:1718)
I/flutter ( 3788): #2      IOClient.send (package:http/src/io_client.dart:30:36)
I/flutter ( 3788): <asynchronous suspension>
I/flutter ( 3788): #3      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171:38)
I/flutter ( 3788): <asynchronous suspension>
I/flutter ( 3788): #4      BaseClient.get (package:http/src/base_client.dart:34:5)
I/flutter ( 3788): #5      NetworkImage._loadAsync (package:flutter/src/services/image_provider.dart:431:54)
I/flutter ( 3788): <asynchronous suspension>
I/flutter ( 3788): #6      NetworkImage.load (package:flutter/src/services/image_provider.dart:417:7)
I/flutter ( 3788): #7      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/services/image_provider.dart:253:61)
I/flutter ( 3788): #8      ImageCache.putIfAbsent (package:flutter/src/services/image_cache.dart:82:22)
I/flutter ( 3788): #9      ImageProvider.resolve.<anonymous closure> (package:flutter/src/services/image_provider.dart:253:38)
I/flutter ( 3788): #10     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter ( 3788): #11     ImageProvider.resolve (package:flutter/src/services/image_provider.dart:251:30)
I/flutter ( 3788): #12     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:334:33)
I/flutter ( 3788): #13     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:315:5)
I/flutter ( 3788): #14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:12)
I/flutter ( 3788): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3517:5)
I/flutter ( 3788): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2901:14)
I/flutter ( 3788): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2704:12)
I/flutter ( 3788): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3554:16)
I/flutter ( 3788): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3443:5)
I/flutter ( 3788): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3522:5)
I/flutter ( 3788): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3517:5)
I/flutter ( 3788): #22     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3836:16)
I/flutter ( 3788): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2901:14)
I/flutter ( 3788): #24     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4631:32)
I/flutter ( 3788): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2901:14)
I/flutter ( 3788): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2704:12)
I/flutter ( 3788): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4526:14)
I/flutter ( 3788): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2901:14)
I/flutter ( 3788): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2704:12)
I/flutter ( 3788): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3554:16)
I/flutter ( 3788): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3443:5)
I/flutter ( 3788): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3522:5)
I/flutter ( 3788): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3517:5)
I/flutter ( 3788): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2901:14)
I/flutter ( 3788): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2704:12)
I/flutter ( 3788): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4526:14)
I/flutter ( 3788): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2901:14)
I/flutter ( 3788): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2704:12)
I/flutter ( 3788): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3554:16)
I/flutter ( 3788): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3443:5)
I/flutter ( 3788): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3522:5)
I/flutter ( 3788): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3517:5)
I/flutter ( 3788): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2901:14)
I/flutter ( 3788): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2704:12)
I/flutter ( 3788): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3554:16)
I/flutter ( 3788): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3443:5)
I/flutter ( 3788): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3522:5)
I/flutter ( 3788): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3517:5)
I/flutter ( 3788): #49     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3836:16)
I/flutter ( 3788): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2901:14)
I/flutter ( 3788): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2704:12)
I/flutter ( 3788): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3554:16)
I/flutter ( 3788): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3443:5)
I/flutter ( 3788): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3522:5)
I/flutter ( 3788): #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3660:22)
I/flutter ( 3788): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3517:5)
I/flutter ( 3788): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2901:14)
I/flutter ( 3788): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2704:12)
I/flutter ( 3788): #59     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:723:20)
I/flutter ( 3788): #60     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2259:19)
I/flutter ( 3788): #61     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:716:11)
I/flutter ( 3788): #62     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:239:23)
I/flutter ( 3788): #63     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1974:58)
I/flutter ( 3788): #64     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1066:15)
I/flutter ( 3788): #65     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1974:13)
I/flutter ( 3788): #66     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:228:5)
I/flutter ( 3788): #67     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:308:5)
I/flutter ( 3788): #68     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
I/flutter ( 3788): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #70     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:248:13)
I/flutter ( 3788): #71     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:900:12)
I/flutter ( 3788): #72     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:824:20)
I/flutter ( 3788): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #74     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #76     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #78     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #80     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #82     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #84     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #86     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:300:13)
I/flutter ( 3788): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #88     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124:11)
I/flutter ( 3788): #89     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:85:7)
I/flutter ( 3788): #90     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
I/flutter ( 3788): #91     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
I/flutter ( 3788): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #93     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #95     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #96     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1015:24)
I/flutter ( 3788): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #98     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #100    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #102    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #103    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #104    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #105    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2621:26)
I/flutter ( 3788): #106    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #107    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #108    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #109    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:433:15)
I/flutter ( 3788): #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #111    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #113    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #115    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #117    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #119    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3788): #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1878:7)
I/flutter ( 3788): #121    RenderView.performLayout (package:flutter/src/rendering/view.dart:142:13)
I/flutter ( 3788): #122    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1753:7)
I/flutter ( 3788): #123    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1044:18)
I/flutter ( 3788): #124    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:251:19)
I/flutter ( 3788): #125    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:504:22)
I/flutter ( 3788): #126    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189:5)
I/flutter ( 3788): #127    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:688:15)
I/flutter ( 3788): #128    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:636:9)
I/flutter ( 3788): #129    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/rendering/binding.dart:275:20)
I/flutter ( 3788): #131    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
I/flutter ( 3788): #132    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
I/flutter ( 3788): #133    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
I/flutter ( 3788): (elided one frame from package dart:async-patch)
I/flutter ( 3788): 
I/flutter ( 3788): Image provider: NetworkImage("invalidurl", scale: 1.0)
I/flutter ( 3788): Image key: NetworkImage("invalidurl", scale: 1.0)
I/flutter ( 3788): ════════════════════════════════════════════════════════════════════════════════════════════════════```

**Comment by lishuhao** [comment]
I have the same problem, i use try catch but it's not working

**Comment by ride4sun** [comment]
@hundeva same here - what is the fix?

**Comment by hundeva** [comment]
As far as I remember, I've manually validated the urls before trying to load them, and if the validation failed, I've displayed an error image instead of trying to fetch the image.

**Comment by sethladd** [comment]
Should we add a way for users to catch exceptions when using networkimages? Is NetworkImage hiding too much from the developer?

**Comment by hundeva** [comment]
The thing I was missing the most is to be able to provide an easy fallback image in case the loading fails for whatever reason. To be honest, it took me quite a while until I figured out that I did everything correctly, but that the provided image urls were wrong (I was trying out an API that I never did before, and didn't know what to expect).

There could be one more optional parameter, which could be a fallback `Image`. I created something like this when I was playing around with this:

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:reddit/resources/dimensions.dart';
import 'package:validator/validator.dart';

class RedditImage extends StatelessWidget {
  final String url;
  final String fallback;
  final double _size;

  RedditImage({
    Key key,
    @required this.url,
    this.fallback: 'assets/icon/reddit_icon',
    ImageSize imageSize: ImageSize.small,
  })
      : _size = imageSize == ImageSize.small
            ? smallIcon
            : imageSize == ImageSize.medium ? mediumIcon : largeIcon,
        super(key: key);

  @override
  Widget build(BuildContext context) {
    return isURL(url)
        ? new Image.network(
            url,
            width: _size,
            height: _size,
          )
        : new Image.asset(
            'assets/icons/reddit_icon.png',
            width: _size,
            height: _size,
          );
  }
}

enum ImageSize { small, medium, large }
```

where the dimensions were the following:

```dart
const double smallIcon = 32.0;
const double mediumIcon = 64.0;
const double largeIcon = 96.0;
```

and `isURL(string)` is part of a third party validator package.

**Comment by ride4sun** [comment]
@hundeva do you show that alternate picture also when the URL is correct but the network is down or the server is not reachable or the loading is just slow. I did not find a documentation about those cases. I currently show a placeholder until the image is uploaded from the phone to the server. The next step is the download from the server back to the phone. Both ways I have to show something and I have to deal with errors. Wondering what the recommendation are.

**Comment by hundeva** [comment]
Currently not, I haven't dealt with what to display while loading is in progress. Again, the snippet I just posted is the result of a few minutes of playing around, and incomplete. The next step would have been a placeholder image for progress, were I to continue.

**Comment by Hixie** [comment]
The original complaint here will change soon since we're moving from package:http to dart:io for HTTP.

The overall issue here is probably best handled by something like https://github.com/flutter/flutter/issues/9676. I'm going to close this issue in favour of that one since we're unlikely to specifically do anything about the error message in the meantime.
