### ISSUE TITLE
Camera CameraCaptureSession.close() crash

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#114012]
I keep getting these crashes on firebase on various devices:

flutter: 3.3.5
camera: 0.10.0+4

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
       at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1176)
       at io.flutter.plugins.camera.Camera.access$500(Camera.java:100)
       at io.flutter.plugins.camera.Camera$1.onClosed(Camera.java:344)
       at android.hardware.camera2.impl.CameraDeviceImpl$5.run(CameraDeviceImpl.java:215)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by huycozy** [comment]
@NikosTsesmelis Can you share the list of affected devices? And how often does this error occur?

**Comment by harsha-main** [comment]
I found this in my crashlytics. It's very rare, only three issues have been reported so far. 
Here is the stacktrace. @huycozy 
`o.flutter.plugins.camera.Camera.closeCaptureSession (Camera.java:1176)
io.flutter.plugins.camera.Camera.access$500 (Camera.java:100)
io.flutter.plugins.camera.Camera$1.onClosed (Camera.java:344)`

**Comment by NikosTsesmelis** [comment]
We have encountered this issue with:
Redmi Note 10 Pro
Redmi Note 10 5G
Redmi 10C
Redmi 8A
POCO X3 NFC
Galaxy A71
Galaxy Note20
Galaxy A6
moto e40
P9 Plus

and some others so it doesn't seem to be device specific

**Comment by huycozy** [comment]
Hi @NikosTsesmelis, @harsha-main 
Is there the remaining log from the firebase? Please share the complete log if any.

**Comment by harsha-main** [comment]
@NikosTsesmelis 
Here is the complete log from that thread in Firebase

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
io.flutter.plugins.camera.Camera.closeCaptureSession (Camera.java:1176)
io.flutter.plugins.camera.Camera.access$500 (Camera.java:100)
io.flutter.plugins.camera.Camera$1.onClosed (Camera.java:344)
android.hardware.camera2.impl.CameraDeviceImpl$5.run (CameraDeviceImpl.java:247)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:233)
android.os.Looper.loop (Looper.java:344)
android.os.HandlerThread.run (HandlerThread.java:67)`

**Comment by cmoraless** [comment]
I've been getting the same issue on firebase since I updated flutter to version 3. I'm attaching the complete log
[cl.optiroute.driver_issue_7f14a846bbaef4755fb95fc5a040d5f7_crash_session_6385099A024400016842488550752A79_DNE_0_v2_stacktrace.txt](https://github.com/flutter/flutter/files/10108705/cl.optiroute.driver_issue_7f14a846bbaef4755fb95fc5a040d5f7_crash_session_6385099A024400016842488550752A79_DNE_0_v2_stacktrace.txt)

**Comment by huycozy** [comment]
@cmoraless thanks for providing the log. Reopen the issue for further investigation.

Can you share the affected `camera` plugin version, along with the list of affected device info and the percentage occurrence of the crash? Thanks!

**Comment by cmoraless** [comment]
> @cmoraless thanks for providing the log. Reopen the issue for further investigation.
> 
> Can you share the affected `camera` plugin version, along with the list of affected device info and the percentage occurrence of the crash? Thanks!

Hi @huycozy , we are using the version **0.10.0+4** of the plugin along with flutter **3.3.4**.

The percentage of occurrence of the bug per model:

* 58 % samsung
    * 29% Galaxy A20
    * 6% Galaxy A71
    * 6% Galaxy A33 5G
    * 17% Otros
* 37% Xiaomi
    * 15% Redmi 9
    * 5% Redmi Note 10 5G
    * 4% Redmi Note 9
    * 13% Otros (5)
* 4% motorola
    * 3% motorola one fusion
    * 1% moto g(9) play

per SO:
* 65% Android 11
* 33% Android 12
* 2% Android 10

Thanks!

<img width="443" alt="Screen Shot 2022-12-01 at 15 47 16" src="https://user-images.githubusercontent.com/1929611/205135143-aa38ad41-2bd4-4340-81c8-817c4f908192.png">

**Comment by UnCheon** [comment]
I've been getting the same issue on firebase since I updated flutter to version 3.

I use camera every 30 seconds. when I shorten the time, it happen.

**Comment by reidbaker** [comment]
Thank you for the report. @camsim99 can you add this to the list of issues to look at after the camera x migration is done.

**Comment by lytian** [comment]
Not solved yet? Is there any temporary solution?

**Comment by HuiRenBujuanWind** [comment]
i have same issue, is camera2 . whether change to camerax

**Comment by mspapant** [comment]
Is there any update on this issue, i have the same problem

**Comment by pfistnerm** [comment]
We're having the same issue. Same logs in Firebase and we can't reproduce this issue. 
Some customers complain, that they have to start the camera multiple times for it to be working. sometimes the camera feed is displayed the first time already and sometimes they need to reopen the camera to be able to see the feed.

This issue popped up recently and we didn't change the way we use the camera plugin. It could be because of the update to Flutter 3. On our end, we wern't able to reproduce this issue.

**Comment by mehmettezcan** [comment]
Is there any solution?

**Comment by pengge924** [comment]
V2203A 
Android 12,level 31 
ROM
 vivo/FUNTOUCH 
arm64-v8a



# CameraBackground(211)

java.lang.NullPointerException

Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference

1
io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1241)
2
io.flutter.plugins.camera.Camera.access$600(Camera.java:81)
3
io.flutter.plugins.camera.Camera$1.onClosed(Camera.java:347)
4
android.hardware.camera2.impl.CameraDeviceImpl$5.run(CameraDeviceImpl.java:269)
5
android.os.Handler.handleCallback(Handler.java:938)
6
android.os.Handler.dispatchMessage(Handler.java:99)
7
android.os.Looper.loopOnce(Looper.java:233)
8
android.os.Looper.loop(Looper.java:334)
9
android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by pengge924** [comment]
V2203A 
Android 12,level 31 
ROM
 vivo/FUNTOUCH 
arm64-v8a

V1911A 
Android 10,level 29 
ROM 
vivo/FUNTOUCH 
arm64-v8a

22041216C 
Android 12,level 31 
ROM 
XiaoMi/MIUI 
arm64-v8a

V2203A 
Android 12,level 31 
ROM 
vivo/FUNTOUCH 
arm64-v8a

ANE-AL00 
Android 9,level 28
 ROM 
HuaWei/EMOTION 
arm64-v8a

CameraBackground(211)
java.lang.NullPointerException

Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference

io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1241)
io.flutter.plugins.camera.Camera.access$600(Camera.java:81)
io.flutter.plugins.camera.Camera$1.onClosed(Camera.java:347)
android.hardware.camera2.impl.CameraDeviceImpl$5.run(CameraDeviceImpl.java:269)
android.os.Handler.handleCallback(Handler.java:938)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loopOnce(Looper.java:233)
android.os.Looper.loop(Looper.java:334)
android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by ashkryab-fl** [comment]
samsung dm3q
samsung a33x
samsung b0s

Android 13 (SDK 33)

Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
  at io.flutter.plugins.camera.Camera.closeCaptureSession (Camera.java)
  at io.flutter.plugins.camera.Camera.access$500 (Camera.java)
  at io.flutter.plugins.camera.Camera$1.onClosed (Camera.java)
  at android.hardware.camera2.impl.CameraDeviceImpl$5.run (CameraDeviceImpl.java:237)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.os.HandlerThread.run (HandlerThread.java:67)

**Comment by MohamedSafvanKP-MSIL** [comment]
any update for this crash?

**Comment by sahilpsahil** [comment]
Still facing this issue, please someone look up on this issue.

**Comment by camsim99** [comment]
This issue should be fixed in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin. If you try it out and find a similar issue with that implementation, please file a separate issue!

**Comment by alihassan04ali** [comment]
anyone find the solution?

**Comment by tzeyangcarsome** [comment]
Is there any solutions yet?

**Comment by dev-mingo** [comment]
Also facing the same problem.

Galaxy A32 and other Samsung devices. Logs retrieved through Firebase Crashlytics.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
       at io.flutter.plugins.camera.Camera.closeCaptureSession(:13)
       at io.flutter.plugins.camera.Camera$1.onClosed(:12)
       at android.hardware.camera2.impl.CameraDeviceImpl$5.run(CameraDeviceImpl.java:237)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by tzeyangcarsome** [comment]
Hi, do we have any update on this crash? Is there any workaround to this?

**Comment by fabiangruss** [comment]
I'm also getting this error even more frequently in the last days.
@Lesmm did your last commit solve the issue?

**Comment by Ritsz123** [comment]
any updates on this?
can someone confirm if it is fixed?

**Comment by fabiangruss** [comment]
I tried the same things that @Lesmm did in his repo ([https://github.com/Lesmm/flutter_camera_crash](url). This solves the crashing but now my camera takes 3-4 seconds to actually capture. So still waiting for another solution

**Comment by sanderrr** [comment]
I am also getting this error

**Comment by fabiangruss** [comment]
> @fabiangruss if the camera is taking 3-4 seconds to capture image, you can try this solution [#84957 (comment)](https://github.com/flutter/flutter/issues/84957#issuecomment-1642136687) it worked for me.

Helped a lot, thanks!

**Comment by GitFromGeeks** [comment]
is this issue fixed yet?

**Comment by phu-bc** [comment]
I am facing same issue
camera: ^0.10.5+3

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
  at io.flutter.plugins.camera.Camera.closeCaptureSession (Camera.java:1228)
  at io.flutter.plugins.camera.Camera$1.onClosed (Camera.java:348)
  at android.hardware.camera2.impl.CameraDeviceImpl$5.run (CameraDeviceImpl.java:221)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:236)
  at android.os.HandlerThread.run (HandlerThread.java:67)
```

**Comment by Bondidos** [comment]
I also can't reproduce this crash(
Just an idea:
Can this error appear when, for example one of cameras is not response(damaged or smith else), but plugin tries to get it?

**Comment by huycozy** [comment]
Adding `customer: crowd` label based on number of reports and upvotes.

**Comment by Mend-AmarM** [comment]
> I tried the same things that @Lesmm did in his repo [https://github.com/Lesmm/flutter_camera_crash](url). This solves the crashing but now my camera takes 3-4 seconds to actually capture. So still waiting for another solution

Can you elaborate on how to do that?

**Comment by fabiangruss** [comment]
@Mend-AmarM here's what I did:
- Integrated the camera_android package as a local package into my Flutter App
- Inside that package, changed the functions `closeCaptureSession`, `close` & `stopAndReleaseCamera` to `synchronized` (e.g. `synchronized private void stopAndReleaseCamera()`)

That solved the error but caused a delay when taking photos. But this comment https://github.com/flutter/flutter/issues/84957#issuecomment-1661155095 solved that problem.

In general, I'd advise against using the package as a local dependency and wait for a proper fix. In my case, this was a short-term solution to hotfix the bug for our users.

**Comment by Rovalx** [comment]
> This issue should be fixed in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin. If you try it out and find a similar issue with that implementation, please file a separate issue!

I can confirm that using CameraX instead of the default solution for camera solves most of the problems. I know that CameraX is not fully ready and lacks some functionality (which, luckily, I don't use), but I've shipped it to over 200k users now, and the number of issues has decreased to almost none with the camera.

**Comment by gilmar-oliveira** [comment]
I'm getting this error:
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
  at io.flutter.plugins.camera.Camera.closeCaptureSession (Camera.java)
  at io.flutter.plugins.camera.Camera$1.onClosed (Camera.java)
  at android.hardware.camera2.impl.CameraDeviceImpl$5.run (CameraDeviceImpl.java:258)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:210)
  at android.os.Looper.loop (Looper.java:299)
  at android.os.HandlerThread.run (HandlerThread.java:67)
```
  
How to solve?

**Comment by Stiuk** [comment]
> is this issue fixed yet?

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
	at kd.q.t(Unknown Source:13)
	at kd.q$a.onClosed(Unknown Source:12)
	at android.hardware.camera2.impl.CameraDeviceImpl$5.run(CameraDeviceImpl.java:239)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.os.HandlerThread.run(HandlerThread.java:110)

**Comment by tzeyangcarsome** [comment]
@fabiangruss Hi, can you elaborate on how do you integrate the camera_android as local repo? Because when we're importing the camera package, how do we specify that we wanna use our own camera_android repo?

**Comment by camsim99** [comment]
> @fabiangruss Hi, can you elaborate on how do you integrate the camera_android as local repo? Because when we're importing the camera package, how do we specify that we wanna use our own camera_android repo?

https://docs.flutter.dev/packages-and-plugins/using-packages#dependencies-on-unpublished-packages may help you!

**Comment by Areion0** [comment]
any update on this issue?

**Comment by Tellmeok** [comment]
Modifications from @Lesmm
1. First pull the [pub camera_android](https://github.com/flutter/packages/tree/main/packages/camera/camera_android) sources into your project, and change path in `dependencies` in `pubspec.yaml`
2. Edit file `camera_android/android/src/main/java/io/flutter/plugins/camera/Camera.java`, add `synchronized` keyword before the following three `close` methods:

    ````
    synchronized void closeCaptureSession() {
    // on Line 1224
    ...
    
    synchronized public void close() {
    // on Line 1233
    ...
    
    synchronized private void stopAndReleaseCamera() {
    // on Line 1256
    ...

In addition, the 3~4 seconds delay in taking photos is due to the camera's autofocus problem, and is most likely unrelated to the modification here.

**Comment by m-akbarfauzi** [comment]
i have same issue on flutter version 3.19.4 with dependency camera version 0.10.5+9

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
io.flutter.plugins.camera.Camera.closeCaptureSession (Camera.java:13)
io.flutter.plugins.camera.Camera$1.onClosed (Camera.java:12)
android.hardware.camera2.impl.CameraDeviceImpl$5.run (CameraDeviceImpl.java:247)
android.os.Handler.handleCallback (Handler.java:942)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:211)
android.os.Looper.loop (Looper.java:300)
android.os.HandlerThread.run (HandlerThread.java:67)`

**Comment by camsim99** [comment]
This issue should be fixed in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin, so please try it out!

If you find a similar issue with that implementation (or any other issues), please feel free to file a separate issue.

**Comment by hinaabbaskhan** [comment]
I encountered the same issue on flutter version 3.13.7 with dependency `camera version ^0.10.5+4`. 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
       at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:13)
       at io.flutter.plugins.camera.Camera$1.onClosed(Camera.java:12)
       at android.hardware.camera2.impl.CameraDeviceImpl$5.run(CameraDeviceImpl.java:215)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:268)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by chaoyifei** [comment]
> > This issue should be fixed in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin. If you try it out and find a similar issue with that implementation, please file a separate issue!
> 
> I can confirm that using CameraX instead of the default solution for camera solves most of the problems. I know that CameraX is not fully ready and lacks some functionality (which, luckily, I don't use), but I've shipped it to over 200k users now, and the number of issues has decreased to almost none with the camera.

How to use camera_android_camerax

**Comment by camsim99** [comment]
The most up-to-date instructions are [here](https://pub.dev/packages/camera_android_camerax).

As of now, you just need to run `flutter pub add camera_android_camerax`.

**Comment by pfistnerm** [comment]
> > How to use camera_android_camerax
> 
> The most up-to-date instructions are [here](https://pub.dev/packages/camera_android_camerax).
> 
> As of now, you just need to run `flutter pub add camera_android_camerax`.

My probelm was that I have an already existing app for android and iOS where the android implementation made problems.
So in my case only adding `camera_android_camerax` wasn't an option since I need to support iOS as well and I don't want to have 2 different implementations based on the OS.
I couldn't find anything in the documentation but I eventually made it work. 

What I had to do was:
- Add camera
- Add camera_android_camerax
- Change the implementation used by the camera package:
``` dart
// in main.dart
if (Platform.isAndroid) {
    CameraPlatform.instance = AndroidCameraCameraX();
}
```
Like this I can use my current implementation for camera on android and iOS.

If there is a different way how I should have done this, please let me know.

**Comment by camsim99** [comment]
> My probelm was that I have an already existing app for android and iOS where the android implementation made problems.
So in my case only adding camera_android_camerax wasn't an option since I need to support iOS as well and I don't want to have 2 different implementations based on the OS.

Opting into camera_android_camerax does not limit you to Android; it only swaps out the camera_android implementation of the plugin on Android out with camera_android_camerax. All other platforms work the same as before!

**Comment by asiteandroid** [comment]
Any update on this? We are facing same issue.

**Comment by MDSADABWASIM** [comment]
> > How to use camera_android_camerax
> 
> The most up-to-date instructions are [here](https://pub.dev/packages/camera_android_camerax).
> 
> As of now, you just need to run `flutter pub add camera_android_camerax`.

As mentioned in the plugin home page:
As of camera: ^0.11.0, this package is [endorsed](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#endorsed-federated-plugin), which means you can simply use camera normally. This package will be automatically be included in your app when you do, so you do not need to add it to your pubspec.yaml

if you're using 0.11.0 or above it's endorsed already and there's no need to add it.

**Comment by luiges90** [comment]
Unfortunately we cannot use camera: ^0.11.0 because of https://github.com/flutter/flutter/issues/145961. 
This issue happens very often for us and is blocking. Can anyone point how to fix this issue in code?

**Comment by Swastik-Neodocs** [comment]
> Unfortunately we cannot use camera: ^0.11.0 because of #145961. This issue happens very often for us and is blocking. Can anyone point out which part of code in 0.11.0 fixes this issue?

In #145961  a user has posted an solution you can use that for android as i have done the same and it works for me
