### ISSUE TITLE
NPE in PlatformViewsController.getDisplayDensity

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#114095]
Copied from internal bug b/254856490 which has more context and part of a fix suggestion.

We're seeing ~400 crashes per day  in a launched production app with the stack trace below. We're seeing the crashes primarily (60%) on Android 30 devices, and mostly affecting Samsung devices.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at io.flutter.plugin.platform.PlatformViewsController.getDisplayDensity(PlatformViewsController.java:953)
	at io.flutter.plugin.platform.PlatformViewsController.toLogicalPixels(PlatformViewsController.java:961)
	at io.flutter.plugin.platform.PlatformViewsController.-$$Nest$mtoLogicalPixels(Unknown Source:0)
	at io.flutter.plugin.platform.PlatformViewsController$1.lambda$resize$2$io-flutter-plugin-platform-PlatformViewsController$1(PlatformViewsController.java:468)
	at io.flutter.plugin.platform.PlatformViewsController$1$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7815)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1094)
```

**Comment by stuartmorgan** [comment]
It looks like we're probably trying to finish servicing an async resize (on the VD codepath) after `detach` has been called.

https://github.com/flutter/engine/blob/9c3c233e2639bbb984b27937653b4335d50ee0a9/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L468

**Comment by khyati82** [comment]
@stuartmorgan - Can you help with an approx ETA for this fix? This is a hard crash impacting production users in FamilyLink with greater than 1600 reports in total at 10% roll out.

**Comment by stuartmorgan** [comment]
I'll be looking at this today, and should have an ETA soon.

**Comment by stuartmorgan** [comment]
A fix is posted for review.

I wasn't able to reproduce it in a real app, since I don't have steps to reproduce, but I recreated the race synthetically and verified that the reply process completes without crashing now.
