### ISSUE TITLE
Tree red on Android a11y exception in Linux_build_test flutter_gallery__transition_perf 

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#114161]
It started failing on an Engine roll here https://github.com/flutter/flutter/pull/114125, but the Engine roll contains only a Dart roll with a single commit to the CFE, which looks unrelated.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Devicelab%20Test%20Drone/2238/overview

```
[flutter_gallery__transition_perf] [STDOUT] stdout: D/AndroidRuntime(32372): Shutting down VM
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): FATAL EXCEPTION: main
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): Process: io.flutter.demo.gallery, PID: 32372
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): java.lang.NoSuchMethodError: No virtual method setHintText(Ljava/lang/CharSequence;)V in class Landroid/view/accessibility/AccessibilityNodeInfo; or its super classes (declaration of 'android.view.accessibility.AccessibilityNodeInfo' appears in /system/framework/framework.jar:classes2.dex)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo(AccessibilityBridge.java:889)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1144)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1047)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:844)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:156)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController.-wrap1(AccessibilityInteractionController.java)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1198)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.os.Handler.dispatchMessage(Handler.java:102)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.os.Looper.loop(Looper.java:154)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at android.app.ActivityThread.main(ActivityThread.java:6123)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at java.lang.reflect.Method.invoke(Native Method)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
[flutter_gallery__transition_perf] [STDOUT] stdout: E/AndroidRuntime(32372): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

Tagging infra since I'm wondering if this is related to this test using the new recipe.

**Comment by keyonghan** [comment]
There were not any related change from recipes side these days. Same recipes are used by `Linux_build_test flutter_gallery__transition_perf_e2e` and `Linux_build_test flutter_gallery__transition_perf_hybrid` as well, both of which are passing.
Checked the failed tasks: 4 ran on 3 different bots.

All these do not sound an infra related issue to me.

Could we try reverting to see if it helps?

**Comment by zanderso** [comment]
I reverted the Engine roll.

**Comment by christopherfujino** [comment]
Hmm, the revert DID indeed fix the tree. Not sure how...

Green build on revert commit: https://ci.chromium.org/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf/978

**Comment by christopherfujino** [comment]
On the bad engine roll: https://github.com/flutter/flutter/commit/d9a2229babbc7e28cabd0ad42470c527a6cd9d3e
We rolled a single engine commit: https://github.com/flutter/engine/commit/1ea6e5e2de955f16a8529b4e1b418e7971a0e94b
Which picked up a Dart dev build: https://github.com/dart-lang/sdk/commit/4f5e556d1e333ff9f3d470c236e86f42677edc8c
Which pulled in a single upstream main Dart commit: https://github.com/dart-lang/sdk/commit/142bf694400

**Comment by zanderso** [comment]
The re-run on the engine roll commit passed: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf/979/overview

I am going to restart the rollers.

**Comment by christopherfujino** [comment]
On zach's revert this happened again on [Linux_android android_semantics_integration_test](https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20android_semantics_integration_test/3041), so almost positive that:

1. this is unrelated to the engine roll/Dart CFE change
2. it is not contained to a single android target, or bot.

**Comment by christopherfujino** [comment]
cc @sealesj infra on-call, and @GaryQian regarding Java runtime error

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/36846 added a call to `setTextHint` @chunhtai ptal

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/37083 Reverts https://github.com/flutter/engine/pull/36846 which caused the breakage.

**Comment by christopherfujino** [comment]
Revert rolled to the framework, this should be fixed
