### ISSUE TITLE
Cannot execute operation because FlutterJNI is not attached to native

### ISSUE THREAD

**Issue by 12ndxu** [flutter/flutter#114147]
we use flutter in ours app, it crash accidentally after I close the flutterActivity.
log:
java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(Unknown Source:9)
	at io.flutter.embedding.engine.FlutterJNI.setViewportMetrics(Unknown Source:43)
	at io.flutter.embedding.android.FlutterView.j(:6)
	at io.flutter.embedding.android.FlutterView.setWindowInfoListenerDisplayFeatures(:2)
	at io.flutter.embedding.android.FlutterView$d.accept(:1)
	at z3.a$a.emit(Unknown Source:2)
	at lm.u$a.invoke(:1)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(Unknown Source:0)
	at androidx.window.layout.u$a.invokeSuspend(:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(:2)
	at gm.r0.run(Unknown Source:90)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
local message:
[✓] Flutter (Channel stable, 3.3.4, on macOS 13.0 22A380 darwin-arm, locale
  zh-Hans-CN)
  • Flutter version 3.3.4 on channel stable at /Users/liucheng/Library/flutter
  • Upstream repository https://github.com/flutter/flutter.git
  • Framework revision eb6d86ee27 (3 weeks ago), 2022-10-04 22:31:45 -0700
  • Engine revision c08d7d5efc
  • Dart version 2.18.2
  • DevTools version 2.15.0
  • Pub download mirror https://pub.flutter-io.cn/
  • Flutter download mirror https://storage.flutter-io.cn/

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
  • Android SDK at /Users/liucheng/Library/Android/sdk
  • Platform android-33, build-tools 33.0.0
  • Java binary at: /Applications/Android
   Studio.app/Contents/jre/Contents/Home/bin/java
  • Java version OpenJDK Runtime Environment (build
   11.0.12+0-b1504.28-7817840)
  • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Build 14A400
  • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
  • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
  • Android Studio at /Applications/Android Studio.app/Contents
  • Flutter plugin can be installed from:
   🔨 https://plugins.jetbrains.com/plugin/9212-flutter
  • Dart plugin can be installed from:
   🔨 https://plugins.jetbrains.com/plugin/6351-dart
  • Java version OpenJDK Runtime Environment (build
   11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
  • VS Code at /Users/liucheng/Desktop/family/工具/Visual Studio
   Code.app/Contents
  • Flutter extension version 3.50.0

[✓] Connected device (3 available)
  • TECNO CI7n (mobile) • 0123456789ABCDEF • android-arm64 • Android 13 (API 33)
  • macOS (desktop)   • macos      • darwin-arm64  • macOS 13.0 22A380
   darwin-arm
  • Chrome (web)    • chrome      • web-javascript • Google Chrome
   106.0.5249.119

[✓] HTTP Host Availability
  • All required HTTP hosts are available

• No issues found!
how to close flutter page:
SystemNavigator.pop();

It happened heavily, so please solve this issue, thank you.

**Comment by 12ndxu** [comment]
yesterday it happen again，this is log：
 java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to nativ
 at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(Unknown Source:9)
 at io.flutter.embedding.engine.FlutterJNI.setViewportMetrics(Unknown Source:43)
 at io.flutter.embedding.android.FlutterView.j(:6)
 at io.flutter.embedding.android.FlutterView.onApplyWindowInsets(:2)
 at io.flutter.plugin.editing.ImeSyncDeferringInsetsCallback$b.onApplyWindowInsets(Unknown So
 at android.view.View.dispatchApplyWindowInsets(View.java:11653)
 at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7454)
 at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7479)
 at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7461)
 at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7479)
 at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7461)
 at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7479)
 at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7461)
 at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:2814)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3049)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2462)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9383)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1316)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1324)
 at android.view.Choreographer.doCallbacks(Choreographer.java:957)
 at android.view.Choreographer.doFrame(Choreographer.java:871)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1299)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:8107)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

we use our app normally, it will happen in close the flutter page, return to native activity. if you need, I can send the video to your email

**Comment by exaby73** [comment]
> Hello @12ndxu. This issue looks like a duplicate of https://github.com/flutter/flutter/issues/81830. Can you confirm if this is what you are experiencing?

Please confirm the above

**Comment by 12ndxu** [comment]
it is similar but not same, my issue happen after close page, use FlutterActivity; 81830 happen in reopen page, use FlutterFragmentActivity

**Comment by exaby73** [comment]
Can you please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify the issue? Ideally could be in a public github repo

**Comment by 12ndxu** [comment]
I can try, bug it is not must present

**Comment by exaby73** [comment]
If you feel there is an issue with the code, you could always submit a PR. But, I cannot take this issue further without a reproducible example.

**Comment by 12ndxu** [comment]
I try it most time, I can't show it again, It happen in our test team casually, so it is necessary to solve it.

**Comment by exaby73** [comment]
Unfortunately, without a reproducible example, this issue is unactionable. I am closing this issue for now. If you are able to produce a reproducible example, please post and I can reopen the issue. Thank you.
