### ISSUE TITLE
Use certificate with encrypted password to authenticate client on server?

### ISSUE THREAD

**Issue by madsane29** [flutter/flutter#114155]
On the server I have an nginx that asks for a given certificate before it let the flutter app to communicate with the backend. I could make it work if the password is not encrypted but found no solution how to make it work if it is...

This is the plaintext password version:

```
void main() async {  
  final clientCert = await rootBundle.load('assets/plaintext_mobile.client.cert.pem');
  final keystore = await rootBundle.load('assets/plaintext_mobile.client.key.pem');
  final truststore = await rootBundle.load('assets/chain-bundle.cert.pem');
  final password = await rootBundle.loadString('assets/plaintext_mobile_pass.txt');

  
  HttpOverrides.global = SslConfig(
    mobileClientCert: clientCert,
    mobileClientChainBundleCert: truststore,
    mobileClientKey: keystore,
    password: password,
  );
}

class SslConfig extends HttpOverrides {
  ByteData mobileClientCert;
  ByteData mobileClientKey;
  ByteData mobileClientChainBundleCert;
  String password;

  SslConfig({
    required this.mobileClientCert,
    required this.mobileClientKey,
    required this.mobileClientChainBundleCert,
    required this.password,
  });

  @override
  HttpClient createHttpClient(SecurityContext? context) {
    context = SecurityContext.defaultContext;

    bool certificateCheck(truststore, String host, int port) => true;

    context.useCertificateChainBytes(mobileClientCert.buffer.asUint8List(), password: password);
    context.usePrivateKeyBytes(mobileClientKey.buffer.asUint8List(), password: password);
    HttpClient client = super.createHttpClient(context);
    client.badCertificateCallback = (certificateCheck);

    return client;
  }
}
```

It works great. Now I generated some certificates using an encrypted password and does not seem to work:

```
openssl enc -aes256 -pbkdf2 -salt -in ./privatekeys/client_pass -out client_pass.enc

openssl genrsa -des3 -passout file:./client_pass.enc -out ./privatekeys/mobile.client.key.pem 2048

openssl req -new -key ./privatekeys/mobile.client.key.pem -passin file:./client_pass.enc -out ./csr/mobile.client.csr.pem -config ./certs/mobile.client_cert.cnf

openssl ca -config ./openssl-intermediateca.cnf -extensions client_cert -days 364 -notext -batch -passin file:CA_pass.enc -in ./csr/mobile.client.csr.pem -out ./certs/mobile.client.cert.pem
```

I change the file names and when I start the app:

```
E/flutter ( 2940): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Missing extension byte (at offset 10)
E/flutter ( 2940): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1755:7)
E/flutter ( 2940): #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
E/flutter ( 2940): #2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
E/flutter ( 2940): #3      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:90:19)
E/flutter ( 2940): <asynchronous suspension>
E/flutter ( 2940): #4      main (package:myapp/main.dart:56:20)
E/flutter ( 2940): <asynchronous suspension>
E/flutter ( 2940): 
```

at the line:

```
final password = await rootBundle.loadString('assets/password.enc');
```

I wonder what goes wrong and where?

`flutter run --verbose` does not show anything else than what I already can see in my AndroidStudio.

Flutter doctor:

```
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Version 10.0.19044.2130], locale hu-HU)
    • Flutter version 3.3.3 on channel stable at D:\programozas\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (4 weeks ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at E:\Work\android-sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0
    • ANDROID_SDK_ROOT = E:\Work\android-sdk
    • Java binary at: E:\Work\android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)
    • Visual Studio at D:\Program Files (x86)\VisualStudio
    • Visual Studio Community 2019 version 16.11.32126.315
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at E:\Work\android
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • Redmi Note 8 Pro (mobile) • cyv4vwem5pq4jvqk • android-arm64  • Android 10 (API 29)
    • Windows (desktop)         • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.2130]
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 107.0.5304.62
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Flutter analyze:

```

   info - The value of the local variable 'aaaa' isn't used -
    
   info - The type of type can't be inferred; a type must be explicitly provided -
          lib\lll.dart:69:33 - inference_failure_on_untyped_parameter
   info - The operand can't be null, so the condition is always false - lib\main.dart:59:27 -
          unnecessary_null_comparison
   info - The operand can't be null, so the condition is always false - lib\main.dart:60:25 -
          unnecessary_null_comparison
   info - The operand can't be null, so the condition is always false - lib\main.dart:61:27 -
          unnecessary_null_comparison
   info - Avoid using braces in interpolation when not needed - lib\main.dart:62:14 -
          unnecessary_brace_in_string_interps
   info - The value of the local variable 'kkkkkkk' isn't used - lib\repository\pppp.dart:43:16 -
          unused_local_variable
   info - The declaration '_isItOkay' isn't referenced -
          lib\dddd.dart:64:23 - unused_element
   info - The declaration '_areTheseOkay' isn't referenced -
          lib\iiii.dart:72:23 - unused_element

9 issues found. (ran in 78.2s)
```

So I wonder if any of you made a flutter application that should send a certificate (with encrypted password) with every http request to not get denied by the server?

Thanks in advance.

**Comment by stuartmorgan** [comment]
Per the docs, `loadString` expects a valid string:
> The function expects the stored string to be UTF-8-encoded as [Utf8Codec](https://api.flutter.dev/flutter/dart-convert/Utf8Codec-class.html) will be used for decoding the string.

If you are loading arbitrary data instead of a UTF-8 string, you need to use `load`.

Closing as this is behaving as documented.
