### ISSUE TITLE
Assert triggered in focus traversal: RenderBox was not laid out

### ISSUE THREAD

**Issue by saintmac-google** [flutter/flutter#114254]
Hi,

the following snippet causes an assert during focus traversal that a RenderBox has not been laid out (it doesn't have a size).
Repro steps are: click on "Click me", then press tab.

`class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          _EditField(),
          _Panel(),
        ],
      ),
    );
  }
}

class _EditField extends StatefulWidget {
  @override
  State<_EditField> createState() => _EditFieldState();
}

class _EditFieldState extends State<_EditField> {
  final _focusNode = FocusNode(debugLabel: '_EditField');

  @override
  Widget build(BuildContext context) {
    return TextField(
      focusNode: _focusNode,
      decoration: InputDecoration(
        contentPadding: EdgeInsets.fromLTRB(12, 18, 12, 18),
        filled: true,
        hintText: 'Click me',
      ),
    );
  }
}

class _Panel extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 300.0,
      height: 100.0,
      child: Navigator(
        requestFocus: false,
        pages: <MaterialPage<Object>>[
          MaterialPage<Object>(name: 'root', child: Container()),
          MaterialPage<Object>(name: 'panel', child: Text('Then press tab')),
        ],
        onPopPage: (_, __) => false,
      ),
    );
  }
}
`

Here is the output from the chrome console:
`
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
js_primitives.dart:30 The following assertion was thrown while processing the key message handler:
js_primitives.dart:30 Assertion failed: google3:///third_party/dart/flutter/lib/src/rendering/box.dart:2009:12
js_primitives.dart:30 hasSize
js_primitives.dart:30 "RenderBox was not laid out: RenderSemanticsAnnotations#6193f NEEDS-LAYOUT NEEDS-PAINT"
js_primitives.dart:30 
js_primitives.dart:30 When the exception was thrown, this was the stack:
js_primitives.dart:30 dart:sdk_internal 5653:11                                   throw_
js_primitives.dart:30 dart:sdk_internal 5568:15                                   assertFailed
js_primitives.dart:30 package:flutter/src/rendering/box.dart 2009:12              get size
js_primitives.dart:30 package:flutter/src/rendering/box.dart 2147:44              get semanticBounds
js_primitives.dart:30 package:flutter/src/widgets/focus_manager.dart 796:90       get rect
js_primitives.dart:30 package:flutter/src/widgets/focus_traversal.dart 872:20     new
js_primitives.dart:30 package:flutter/src/widgets/focus_traversal.dart 1115:49    <fn>
js_primitives.dart:30 package:flutter/src/widgets/focus_traversal.dart 1115:75    sortDescendants
js_primitives.dart:30 package:flutter/src/widgets/focus_traversal.dart 333:55     [_sortAllDescendants]
js_primitives.dart:30 package:flutter/src/widgets/focus_traversal.dart 406:41     [_moveFocus]
js_primitives.dart:30 package:flutter/src/widgets/focus_traversal.dart 238:39     next
js_primitives.dart:30 package:flutter/src/widgets/focus_manager.dart 1136:46      nextFocus
js_primitives.dart:30 package:flutter/src/widgets/focus_traversal.dart 1687:5     invoke
js_primitives.dart:30 package:flutter/src/widgets/actions.dart 580:20             invokeAction
js_primitives.dart:30 package:flutter/src/widgets/shortcuts.dart 815:36           handleKeypress
js_primitives.dart:30 package:flutter/src/widgets/shortcuts.dart 999:20           [_handleOnKey]
js_primitives.dart:30 package:flutter/src/widgets/focus_manager.dart 1682:25      [_handleKeyMessage]
js_primitives.dart:30 package:flutter/src/services/hardware_keyboard.dart 897:16  [_dispatchKeyMessage]
js_primitives.dart:30 package:flutter/src/services/hardware_keyboard.dart 962:17  handleRawKeyMessage
js_primitives.dart:30 dart:sdk_internal 42528:34                                  runBody
js_primitives.dart:30 dart:sdk_internal 42560:7                                   _async
js_primitives.dart:30 package:flutter/src/services/hardware_keyboard.dart 923:51  handleRawKeyMessage
js_primitives.dart:30 package:flutter/src/services/platform_channel.dart 214:49   <fn>
js_primitives.dart:30 dart:sdk_internal 42528:34                                  runBody
js_primitives.dart:30 dart:sdk_internal 42560:7                                   _async
js_primitives.dart:30 package:flutter/src/services/platform_channel.dart 213:58   <fn>
js_primitives.dart:30 package:flutter/src/services/binding.dart 393:35            <fn>
js_primitives.dart:30 dart:sdk_internal 42528:34                                  runBody
js_primitives.dart:30 dart:sdk_internal 42560:7                                   _async
js_primitives.dart:30 package:flutter/src/services/binding.dart 390:46            <fn>
js_primitives.dart:30 dart:sdk_internal 228129:7                                  invoke2
js_primitives.dart:30 dart:sdk_internal 141412:15                                 invoke
js_primitives.dart:30 dart:sdk_internal 141489:54                                 push
js_primitives.dart:30 dart:sdk_internal 141587:29                                 push
js_primitives.dart:30 dart:sdk_internal 198205:27                                 invokeOnPlatformMessage
js_primitives.dart:30 dart:sdk_internal 200752:49                                 [_handleHtmlEvent]
js_primitives.dart:30 dart:sdk_internal 200777:29                                 <fn>
js_primitives.dart:30 dart:sdk_internal 5857:16                                   _checkAndCall
js_primitives.dart:30 dart:sdk_internal 5862:17                                   dcall
js_primitives.dart:30 dart:sdk_internal 66501:21                                  ret
js_primitives.dart:30 
js_primitives.dart:30 KeyMessage: KeyMessage([KeyDownEvent#a2d91(physicalKey: PhysicalKeyboardKey#7002b(usbHidUsage:
js_primitives.dart:30   "0x0007002b", debugName: "Tab"), logicalKey: LogicalKeyboardKey#b151c(keyId: "0x100000009",
js_primitives.dart:30   keyLabel: "Tab", debugName: "Tab"), character: null, timeStamp: 0:00:04.291300)])
js_primitives.dart:30 ════════════════════════════════════════════════════════════════════════════════════════════════════
`

**Comment by danagbemava-nc** [comment]
Issue is reproducible using the code sample provided above. 

Labeling for further investigation from the team. 

<details>
<summary>logs</summary>

```
Launching lib/main.dart on macOS in debug mode...
Updating minimum macOS deployment target to 10.13.
Upgrading project.pbxproj
Upgrading Podfile
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Removing script build phase dependency analysis.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-000329201AD1001E }
{ platform:macOS, arch:x86_64, id:00008103-000329201AD1001E }

flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during method call TextInputClient.performSelectors:
flutter: RenderBox was not laid out: RenderSemanticsAnnotations#7bfdf NEEDS-LAYOUT NEEDS-PAINT
flutter: 'package:flutter/src/rendering/box.dart':
flutter: Failed assertion: line 2009 pos 12: 'hasSize'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderBox.size (package:flutter/src/rendering/box.dart:2009:12)
flutter: #3      RenderBox.semanticBounds (package:flutter/src/rendering/box.dart:2147:44)
flutter: #4      FocusNode.rect (package:flutter/src/widgets/focus_manager.dart:796:91)
flutter: #5      new _ReadingOrderSortData (package:flutter/src/widgets/focus_traversal.dart:872:21)
flutter: #6      ReadingOrderTraversalPolicy.sortDescendants (package:flutter/src/widgets/focus_traversal.dart:1115:49)
flutter: #7      FocusTraversalPolicy._sortAllDescendants (package:flutter/src/widgets/focus_traversal.dart:333:65)
flutter: #8      FocusTraversalPolicy._moveFocus (package:flutter/src/widgets/focus_traversal.dart:406:41)
flutter: #9      FocusTraversalPolicy.next (package:flutter/src/widgets/focus_traversal.dart:238:39)
flutter: #10     FocusNode.nextFocus (package:flutter/src/widgets/focus_manager.dart:1136:56)
flutter: #11     NextFocusAction.invoke (package:flutter/src/widgets/focus_traversal.dart:1687:19)
flutter: #12     ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:580:21)
flutter: #13     Actions.invoke.<anonymous closure> (package:flutter/src/widgets/actions.dart:878:48)
flutter: #14     Actions._visitActionsAncestors (package:flutter/src/widgets/actions.dart:659:18)
flutter: #15     Actions.invoke (package:flutter/src/widgets/actions.dart:872:30)
flutter: #16     EditableTextState.performSelector (package:flutter/src/widgets/editable_text.dart:3706:17)
flutter: #17     ListMixin.forEach (dart:collection/list.dart:86:13)
flutter: #18     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:19)
flutter: #19     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1657:20)
flutter: #20     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555:55)
flutter: #21     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548:34)
flutter: #22     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:392:35)
flutter: #23     _invoke2 (dart:ui/hooks.dart:183:13)
flutter: #24     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
flutter: #25     _Channel.push (dart:ui/channel_buffers.dart:130:31)
flutter: #26     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
flutter: #27     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
flutter: #28     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: call:
flutter:   MethodCall(TextInputClient.performSelectors, [1, [insertTab:]])
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Application finished.

Exited.

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-arm, locale en-GB)
    • Flutter version 3.3.6 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (6 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

```
[!] Flutter (Channel master, 3.5.0-10.0.pre.167, on macOS 13.0 22A380 darwin-arm64, locale en-GB)
    • Flutter version 3.5.0-10.0.pre.167 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 533b3a1e49 (2 hours ago), 2022-10-31 02:18:06 -0400
    • Engine revision 32d2d937ba
    • Dart version 2.19.0 (build 2.19.0-353.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```
</details>

**Comment by justinmc** [comment]
@chunhtai Is this a valid use of Navigator?  Your name came into my head because of go_router, but let me know if you're not the right person for that question.

**Comment by chunhtai** [comment]
I see no problem using navigator this way. I can't tell why it crash but we should fix it

**Comment by justinmc** [comment]
Thanks, that's what I needed to know.  I'll take a closer look at this.

**Comment by justinmc** [comment]
@gspencergoog It looks like the cause of this assertion is that inactive Navigator pages are a part of the focus traversal.  So in the repro code (pasted below), the "root" page is not shown, but pressing tab traverses to it.  Since it's not laid out, it triggers the assertion.

```dart
Navigator(
  pages: <MaterialPage<Object>>[
    MaterialPage<Object>(name: 'root', child: Container()),
    const MaterialPage<Object>(name: 'panel', child: Text('Then press tab')),
  ],
  ...
),
```

Does that sound like an accurate assessment to you?  I assume the solution would be to exclude inactive pages somewhere?

**Comment by amin79** [comment]
@saintmac-google Hi. Did you solve you problem?

**Comment by saintmac-google** [comment]
oh that's old.
either that has been solved a while ago or I ended up doing it differently
