### ISSUE TITLE
[Flutter Web][Integration Test][tool_crash] UnknownException

### ISSUE THREAD

**Issue by ahnkiot123a** [flutter/flutter#114208]
## Command
```
flutter drive --driver=integration_test/integration_test_driver.dart --target=integration_test/integration_test_index.dart -d web-server --release --browser-name=android-chrome --web-port=8080 --web-renderer=html
```

## Steps to Reproduce
1. Start adb server: adb start-server
2. Start the Chrome driver on port 4444: chromerdirver --port=4444
3. Run integration test on android chrome.

## Logs
UnknownException
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:99:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:103:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:64:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:146:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:275:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-arm, locale en-JP)
    • Flutter version 3.3.5 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (8 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (5 available)
    • Pixel 5 (mobile)       • 09201FDD40011Y                       • android-arm64  • Android 13 (API 33)
    • iPhone 14 Pro (mobile) • 3404C9F4-5C70-4FF9-A078-59729AC97A7A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

I follow the guide of the link: https://github.com/flutter/flutter/wiki/Running-Flutter-Driver-tests-with-Web  to run the Integration Test on the android browser (Chrome). It gets trouble (error) when relating the Main Activity class on Chrome of Android 13:
```
Oops; flutter has exited unexpectedly: "UnknownException (500): unknown error: Failed to start com.android.chrome on device 09201FDD40011Y: Starting: Intent { dat=data: cmp=com.android.chrome/com.google.android.apps.chrome.Main }
Error type 3
Error: Activity class {com.android.chrome/com.google.android.apps.chrome.Main} does not exist.
".
```

**Comment by exaby73** [comment]
Hello @ahnkiot123a. Can you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for the Flutter code and test code as well?
