### ISSUE TITLE
Flutter run on emulator; with error : ADB exited with exit code -15 

### ISSUE THREAD

**Issue by karlzhouzhi** [flutter/flutter#114292]
## Steps to Reproduce

1. open AS Chipmunk and open emulator
2. open a Flutter Demo APP which is created by AS default
3. got the project root dir, then flutter run

## Logs

<details>
<summary>Logs</summary>

```
  +37 ms] cat: /data/local/tmp/sky.com.karl.flutter_app_first.sha1: No such file or directory
[        ] Installing APK.
[   +1 ms] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /Users/zhouzhi96/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r
/Users/zhouzhi96/work/source/jrpaas/demo/flutter/flutter_app/flutter_app_first/build/app/outputs/flutter-apk/a
pp.apk
[ +635 ms] Installing build/app/outputs/flutter-apk/app.apk... (completed in 633ms)
[   +1 ms] Error: ADB exited with exit code -15
[   +1 ms] Warning: Failed to install APK.
[        ] Uninstalling old version...
[        ] executing: /Users/zhouzhi96/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall
com.karl.flutter_app_first
[ +128 ms] Success
[        ] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /Users/zhouzhi96/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r
/Users/zhouzhi96/work/source/jrpaas/demo/flutter/flutter_app/flutter_app_first/build/app/outputs/flutter-apk/a
pp.apk
[ +947 ms] Installing build/app/outputs/flutter-apk/app.apk... (completed in 947ms)
[        ] Error: ADB exited with exit code -15
[        ] Error: Failed to install APK again.
[   +1 ms] Error launching application on sdk gphone64 x86 64.
[+2787 ms] "flutter run" took 11,304ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +71 ms] ensureAnalyticsSent: 69ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

```
[✓] Flutter (Channel stable, 3.3.2, on Mac OS X 10.15.7 19H1824 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.2 on channel stable at /Users/zhouzhi96/tools/dev/flutter/flutter_3.3.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/zhouzhi96/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/zhouzhi96/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/zhouzhi96/.nvm/versions/node/v10.16.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/zhouzhi96/Library/Android/sdk/platform-tools/adb
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 12D4e
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio-1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Users/zhouzhi96/tools/dev/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • Mac OS X 10.15.7 19H1824 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by huycozy** [comment]
Hi @karlzhouzhi 
Does this issue happen on the Flutter default sample project (counter app)? And have you tried with a physical device to check if the project can run normally?
