### ISSUE TITLE
`SnapshotWidget` renders incorrectly when enabled

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#114398]
Please see linked PR for reproduction

copied here:

In short, the SnapshotWidget is rendered differently when enabled vs disabled.

Reproduction:

<details>

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final binding = TestWidgetsFlutterBinding.ensureInitialized();
  testWidgets('SnapshotWidget should have same result when enabled', (tester) async {
    binding.window
      ..physicalSizeTestValue = const Size(10, 10)
      ..devicePixelRatioTestValue = 1;
    addTearDown(() => binding.window
      ..clearPhysicalSizeTestValue()
      ..clearDevicePixelRatioTestValue());

    final controller = SnapshotController(allowSnapshotting: false);
    await tester.pumpWidget(MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Container(
        color: Colors.black,
        padding: const EdgeInsets.only(right: 0.6, bottom: 0.6),
        child: SnapshotWidget(
          controller: controller,
          child: Container(
            margin: const EdgeInsets.only(right: 0.4, bottom: 0.4),
            color: Colors.blue,
          ),
        ),
      ),
    ));

    final imageWhenDisabled = await _captureImage(tester.element(find.byType(MaterialApp)));

    controller.allowSnapshotting = true;
    await tester.pump();

    final imageWhenEnabled = await _captureImage(tester.element(find.byType(MaterialApp)));
    await expectLater(imageWhenEnabled, matchesReferenceImage(imageWhenDisabled));
  });
}

Future<ui.Image> _captureImage(Element element) {
  assert(element.renderObject != null);
  RenderObject renderObject = element.renderObject!;
  while (!renderObject.isRepaintBoundary) {
    renderObject = renderObject.parent! as RenderObject;
  }
  assert(!renderObject.debugNeedsPaint);
  final OffsetLayer layer = renderObject.debugLayer! as OffsetLayer;
  return layer.toImage(renderObject.paintBounds);
}
```

</details>

If you dump the images, will see:

imageWhenDisabled
![image](https://user-images.githubusercontent.com/5236035/199182280-2001019b-0b3c-452a-99fa-42d42c60dcf8.png)

imageWhenEnabled
![image](https://user-images.githubusercontent.com/5236035/199182308-d4c65422-085a-4e86-b849-55043bd4d481.png)

**Comment by huycozy** [comment]
Hi @fzyzcjy, I can reproduce this issue on the latest `master` channel with sample code at https://github.com/flutter/flutter/pull/114400#issue-1431012954.

<details>
<summary>Test result log</summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: rasterized image matches that of a [10×10] reference image
  Actual: Image:<[10×10]>
   Which: does not match on 17 pixels

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _expect.<anonymous closure> (package:test_api/src/expect/expect.dart:109:9)
<asynchronous suspension>
<asynchronous suspension>
(elided 6 frames from dart:async and package:stack_trace)

The test description was:
  SnapshotWidget should have same result when enabled
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: SnapshotWidget should have same result when enabled

```
</details>

<details>
<summary>Sample code</summary>

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final binding = TestWidgetsFlutterBinding.ensureInitialized();
  testWidgets('SnapshotWidget should have same result when enabled', (tester) async {
    binding.window
      ..physicalSizeTestValue = const Size(10, 10)
      ..devicePixelRatioTestValue = 1;
    addTearDown(() => binding.window
      ..clearPhysicalSizeTestValue()
      ..clearDevicePixelRatioTestValue());

    final controller = SnapshotController(allowSnapshotting: false);
    await tester.pumpWidget(MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Container(
        color: Colors.black,
        padding: const EdgeInsets.only(right: 0.6, bottom: 0.6),
        child: SnapshotWidget(
          controller: controller,
          child: Container(
            margin: const EdgeInsets.only(right: 0.4, bottom: 0.4),
            color: Colors.blue,
          ),
        ),
      ),
    ));

    final imageWhenDisabled = await _captureImage(tester.element(find.byType(MaterialApp)));

    controller.allowSnapshotting = true;
    await tester.pump();

    final imageWhenEnabled = await _captureImage(tester.element(find.byType(MaterialApp)));
    await expectLater(imageWhenEnabled, matchesReferenceImage(imageWhenDisabled));
  });
}

Future<ui.Image> _captureImage(Element element) {
  assert(element.renderObject != null);
  RenderObject renderObject = element.renderObject!;
  while (!renderObject.isRepaintBoundary) {
    renderObject = renderObject.parent! as RenderObject;
  }
  assert(!renderObject.debugNeedsPaint);
  final OffsetLayer layer = renderObject.debugLayer! as OffsetLayer;
  return layer.toImage(renderObject.paintBounds);
}
```
</details>

<details>
<summary>flutter doctor -v (master)</summary>

```bash
[!] Flutter (Channel master, 3.5.0-10.0.pre.183, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-10.0.pre.183 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 37b72342b0 (4 hours ago), 2022-10-31 16:09:09 -0700
    • Engine revision c16e2c0872
    • Dart version 2.19.0 (build 2.19.0-354.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>
