### ISSUE TITLE
[flutter_tools] tool should tool exit hitting Xcode error about "disk I/O error" accessing XCBuildData/build.db

### ISSUE THREAD

**Issue by mauricev** [flutter/flutter#114388]
Errors similar to https://github.com/flutter/flutter/issues/102479 are back due to popular demand

1. On my specific Mac running Monterey 12.6 and XCode 14.0.1 on an Intel Mac Pro, I run:
2. flutter create test_project -v, then 
3. flutter run -d macos -v

## Logs
This error occurs
```
[Logs](error: error: accessing build database "/Users/maurice/My Drive/utility belt software/Programs/Hangman Solver/test/test_project/build/macos/Build/Intermediates.noindex/XCBuildData/build.db": disk I/O error)
```
One response online here https://stackoverflow.com/questions/51850850/xcode-10-beta-6-error-accessing-build-database seems to suggest something that is no longer available with current XCode.

This response https://stackoverflow.com/questions/72162000/error-xcode-unable-to-attach-db-error-accessing-build-databaseflutter doesn't work either because there is no podfile.

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-US)
    • Flutter version 3.3.4 on channel stable at /Users/maurice/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (4 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/maurice/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Volumes/backup boot/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Stud
[flutter error output.txt](https://github.com/flutter/flutter/files/9906377/flutter.error.output.txt)
io (version 2021.3)
    • Android Studio at /Volumes/backup boot/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.6008.17

[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
    • IntelliJ at /Volumes/backup boot/Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.6008.17

[✓] Connected device (4 available)
    • iPhone SE (3rd generation) (mobile) • B63853FE-94F6-4DBD-A447-68E8692DB469 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • iPhone 14 Pro (mobile)              • 72146547-D535-4982-861B-E62ED3F5949B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
Some items may be repeated because they’re part of a backup disk
</details>

[flutter error output.txt](https://github.com/flutter/flutter/files/9906380/flutter.error.output.txt)

**Comment by huycozy** [comment]
Hi @mauricev 
This issue looks similar to https://github.com/flutter/flutter/issues/56654. Please try some workarounds at https://github.com/flutter/flutter/issues/56654#issuecomment-627507578 and https://github.com/flutter/flutter/issues/56654#issuecomment-650734939 to see if they can help solve the issue.

**Comment by mauricev** [comment]
Neither workaround is related. It turns out that my project is sitting inside my local copy of my Google drive. When I created a project on _plain_ disk space, it compiles just fine. When I compile inside the Google “My Drive”, this error message occurs. There is some interaction between it and XCode.

**Comment by huycozy** [comment]
@mauricev Thanks for providing more information. Now I can reproduce this issue on the latest `stable` and `master` channels after running project inside Google Drive app. 

- macOS: ❌
- iOS: ✅

✅: No Issue ❌: Issue reproduced

Labeling this issue for further investigation from the team.

<details>
<summary>Error logs</summary>

```bash
[  +44 ms] error: error: accessing build database
"/Users/huynq/Documents/GoogleDrive/test_issue_114388_macos_build/build/macos/Build/Intermediates.noindex/XCBuildData/build.db": disk I/O error
[   +8 ms] ** BUILD FAILED **
[  +51 ms] Building macOS application... (completed in 13.4s)
[   +3 ms] Exception: Build process failed
[   +6 ms] "flutter run" took 16,867ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +175 ms] ensureAnalyticsSent: 173ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (30 hours ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.62

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.5.0-12.0.pre.69, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-12.0.pre.69 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 97d0247d59 (51 minutes ago), 2022-11-02 04:31:00 +0200
    • Engine revision 81f5c30b23
    • Dart version 2.19.0 (build 2.19.0-359.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by jmagman** [comment]
You would see the same issue if you created a vanilla non-Flutter Xcode project in a cloud directory.  This has nothing to do with Flutter except that we could maybe make the message more actionable.
