### ISSUE TITLE
[google_maps_flutter] Android only - loading custom icon from SVG assets crash the app

### ISSUE THREAD

**Issue by suesitran** [flutter/flutter#114326]
## Steps to Reproduce

1. Use an **Android** device, and ensure location service is ON
2. Execute `flutter run` on the code sample 
3. tap 'Continue' to use default location
4. app crash

**Expected results:** map is loaded with custom marker icon from SVG asset

**Actual results:** App crash with stacktrace below

<details>
<summary>Code sample</summary>

Link to GitHub project: https://github.com/suesitran/interactive_diary/blob/dev/lib/features/home/widgets/googe_map.dart

</details>

<details>
  <summary>Logs</summary>

```
I/DynamiteModule(31015): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203115000
I/DynamiteModule(31015): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203115000
V/DynamiteModule(31015): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/DynamiteDebugLogger(31015): [71] com.google.android.gms.maps_dynamite
I/Google Maps Android API(31015): Google Play services client version: 12451000
I/Google Maps Android API(31015): Google Play services package version: 224113045
I/Google Maps Android API(31015): Google Play services maps renderer version(legacy): 203115000
D/MapsInitializer(31015): loadedRenderer: LEGACY
D/zzca    (31015): preferredRenderer: null
I/Google Maps Android API(31015): Google Play services package version: 224113045
I/Google Maps Android API(31015): Google Play services maps renderer version(legacy): 203115000
D/CompatibilityChangeReporter(31015): Compat change id reported: 171228096; UID 10411; state: ENABLED
I/PlatformViewsController(31015): Hosting view in a virtual display for platform view: 0
E/SchedPolicy(31015): Failed to find cgroup for tid 31015
I/Dialog  (31015): mIsDeviceDefault = false, mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/DecorView(31015): [INFO] isPopOver=false, config=false
I/DecorView(31015): updateCaptionType >> DecorView@2e85e97[], isFloating=false, isApplication=false, hasWindowControllerCallback=false, hasWindowDecorCaption=false
D/DecorView(31015): setCaptionType = 0, this = DecorView@2e85e97[]
I/ViewRootImpl@84a4d33[](31015): setView = com.android.internal.policy.DecorView@2e85e97 TM=true
D/skia    (31015): --- Failed to create image decoder with message 'unimplemented'
D/AndroidRuntime(31015): Shutting down VM
E/AndroidRuntime(31015): FATAL EXCEPTION: main
E/AndroidRuntime(31015): Process: com.nartus.interactiveDiary.dev, PID: 31015
E/AndroidRuntime(31015): java.lang.IllegalArgumentException: Unable to interpret bytes as a valid image.
E/AndroidRuntime(31015): 	at io.flutter.plugins.googlemaps.Convert.getBitmapFromBytes(Convert.java:78)
E/AndroidRuntime(31015): 	at io.flutter.plugins.googlemaps.Convert.toBitmapDescriptor(Convert.java:66)
E/AndroidRuntime(31015): 	at io.flutter.plugins.googlemaps.Convert.interpretMarkerOptions(Convert.java:407)
E/AndroidRuntime(31015): 	at io.flutter.plugins.googlemaps.MarkersController.addMarker(MarkersController.java:154)
E/AndroidRuntime(31015): 	at io.flutter.plugins.googlemaps.MarkersController.addMarkers(MarkersController.java:36)
E/AndroidRuntime(31015): 	at io.flutter.plugins.googlemaps.GoogleMapController.updateInitialMarkers(GoogleMapController.java:800)
E/AndroidRuntime(31015): 	at io.flutter.plugins.googlemaps.GoogleMapController.onMapReady(GoogleMapController.java:206)
E/AndroidRuntime(31015): 	at com.google.android.gms.maps.zzaf.zzb(com.google.android.gms:play-services-maps@@18.0.0:1)
E/AndroidRuntime(31015): 	at com.google.android.gms.maps.internal.zzaq.zza(com.google.android.gms:play-services-maps@@18.0.0:5)
E/AndroidRuntime(31015): 	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.0.0:3)
E/AndroidRuntime(31015): 	at android.os.Binder.transact(Binder.java:1100)
E/AndroidRuntime(31015): 	at ex.c(:com.google.android.gms.dynamite_mapsdynamite@224113045@22.41.13 (190408-0):2)
E/AndroidRuntime(31015): 	at com.google.maps.api.android.lib6.impl.bg.run(:com.google.android.gms.dynamite_mapsdynamite@224113045@22.41.13 (190408-0):1)
E/AndroidRuntime(31015): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(31015): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31015): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(31015): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(31015): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
E/AndroidRuntime(31015): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31015): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(31015): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime(31015): Caused by: java.lang.IllegalArgumentException: Unable to decode bytes as a valid bitmap.
E/AndroidRuntime(31015): 	at io.flutter.plugins.googlemaps.Convert.toBitmap(Convert.java:281)
E/AndroidRuntime(31015): 	at io.flutter.plugins.googlemaps.Convert.getBitmapFromBytes(Convert.java:75)
E/AndroidRuntime(31015): 	... 20 more
I/Process (31015): Sending signal. PID: 31015 SIG: 9
```

</details>

<details>
  <summary>Flutter analyze</summary>

```
Analyzing interactive_diary...                                          
No issues found! (ran in 6.5s)
```
</details>

<details>
  <summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@suesitran From the code sample you provided, you seem to be passing  the `format` as `toByteData(format: ImageByteFormat.png)`.

https://github.com/suesitran/interactive_diary/blob/4aa3e3e743a2067e4f82f6333364b7e1512cdd37/lib/features/home/widgets/googe_map.dart#L180

But the default format for the method seem to be `ImageByteFormat.rawRgba`. Can you check if using the default `format` parameter still gives same error crash or not ?

**Comment by suesitran** [comment]
I tried with all values of `ImageByteFormat`, and all results in a crash.

Here are what I've tried:
1. change to other values of `ImageByteFormat`
2. use `ImageByteFormat.png`, comment out `icon: icon` in `Marker`, then launch the app. While app is running, uncomment `icon: icon` and let app hot reload => app run successfully, with icon loaded correctly
3. use below code to create Marker in initState(), but result is still a crash
```
WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      _generateMarkerIcon();
    });
```

What's odd is, it works fine the day before yesterday, and started to fail around 6pm yesterday (Sydney time)

**Comment by darshankawar** [comment]
Thanks for the update. Can you take a look at [this](https://stackoverflow.com/a/60112985) and see if it helps ?

**Comment by suesitran** [comment]
Hi,

My assets is SVG, not PNG, so I can't follow that steps exactly. I made this changes to suit my SVG assets, but it still result in a crash, although I really think the extra conversion is not needed.

```
final ByteData? data = await (await recorder
            .endRecording()
            .toImage(markerSize.toInt(), markerSize.toInt()))
        .toByteData(format: ImageByteFormat.png);

    if (data != null) {
      Codec codec = await instantiateImageCodec(data.buffer.asUint8List(), targetWidth: markerSize.toInt());
      FrameInfo fi = await codec.getNextFrame();
      final Uint8List? pngBytes = (await fi.image.toByteData(format: ImageByteFormat.png))?.buffer.asUint8List();
      if (pngBytes != null && !_streamController.isClosed) {
        _streamController.sink.add(Uint8List.view(pngBytes.buffer));
      }
    }
```

**Comment by suesitran** [comment]
I think I upgraded my Flutter from 3.3.2 to 3.3.5 before this issue happened, after a few days delay, but now I can't downgrade to 3.3.2 anymore. Any idea?

**Comment by darshankawar** [comment]
> but now I can't downgrade to 3.3.2 anymore. Any idea?

Running `flutter downgrade` will only downgrade to immediate previous version, ie, 3.3.4. If you want specific version, you may use `git checkout 3.3.2` from your Flutter SDK path.

**Comment by coolkiecat** [comment]
Use svg cleaner to clean the svg picture before use into you project may help you

**Comment by coolkiecat** [comment]
Use svg cleaner to clean the svg picture before use into you project may help you

**Comment by suesitran** [comment]
i reverted flutter to 3.3.2, and issue still happens.

@coolkiecat thanks for suggestion, let me check my SVG again.

**Comment by suesitran** [comment]
my teammate found the issue, we need to check to avoid `data.isEmpty` as well.

Close this issue now.
