### ISSUE TITLE
Failed to run 'flutter build apk', I have tried several versions of flutter.

### ISSUE THREAD

**Issue by qinrunhao** [flutter/flutter#114414]
An error occurs when I run the command 'flutter build apk'. I'm not sure if it was a version conflict. Thank you very much for your help!
```
Compilation failed.
G:\bin\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag: GLSL to SPIRV failed; Compilation error. 2 error(s) and 0 warning(s).
G:\bin\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag:1: error: '�?' : unexpected token
G:\bin\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag:1: error: '' :  syntax error, unexpected RIGHT_BRACE

FAILURE: Build failed with an exception.

* Where:
Script 'G:\bin\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'G:\bin\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 19s
Running Gradle task 'assembleRelease'...                          201.2s
Gradle task assembleRelease failed with exit code 1
```
flutter doctor -v 
```
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.18363.1916], locale zh-CN)
    • Flutter version 3.3.6 on channel stable at G:\bin\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (7 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at G:\bin\android-sdk-windows
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = G:\bin\android-sdk-windows
    • Java binary at: D:\soft\soft\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
    • Visual Studio at D:\soft\soft\Visual Studio\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 3.6)
    • Android Studio at D:\soft\soft\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\soft\soft\IDEA
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at D:\soft\soft\IntelliJ IDEA 2020.2.1
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7206

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1916]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.26

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

build.gradle
````
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20'
    }
}

android {
    compileSdkVersion 33
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33
    }
}
````

gradle-wrapper.properties
````
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
````

When I run the command 'flutter run --release', there is an extra error message in addition to the above error:
````
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:408:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:575:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:504:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:706:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

````

**Comment by huycozy** [comment]
Hi @qinrunhao 
Does this issue happen on the Flutter default sample project (counter app)?  
If not so, please provide the output of `flutter run --release -v`. If the log is too long, please save it into a file and attach it here. Thanks!

**Comment by qinrunhao** [comment]
Hi @huycozy 
This issue happened when I created the default project. There are two log files.
[error_default_project.txt](https://github.com/flutter/flutter/files/9915425/error_default_project.txt)
[error_my_project.txt](https://github.com/flutter/flutter/files/9915426/error_my_project.txt)

**Comment by huycozy** [comment]
Hi @qinrunhao thanks for providing the logs. 
I checked the log and see that the issue happens when running with `release` mode. Can you check the project run/build normally with `debug` mode?

May be related/similar: #113270

**Comment by huycozy** [comment]
Hi @qinrunhao thanks for providing the logs. 
I checked the log and see that the issue happens when running with `release` mode. Can you check the project run/build normally with `debug` mode?
Also, does this issue happen on old Flutter versions (if you remember this)? 

May be related/similar: #113270

**Comment by qinrunhao** [comment]
Hi @Huycozy
The issue was settled. 
I removed the local flutter and downloaded the new one. The issue disappeared when I recreated a default project and migrated my project code to the default project. Thank you very much.

**Comment by qinrunhao** [comment]
Hi @Huycozy
The issue was settled. 
I removed the local flutter and downloaded the new one. The issue disappeared when I recreated a default project and migrated my project code to the default project. Thank you very much.

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
