### ISSUE TITLE
[webview_flutter] `PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference, null, null)`

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#114500]
### Problem description

stack trace:

![image](https://user-images.githubusercontent.com/5236035/199498046-4c44f515-715a-474c-99a5-e514c9141d75.png)

### Cause analysis

This seems to be caused by a racing condition. 

[TODO]

**Comment by danagbemava-nc** [comment]
Hi @fzyzcjy, thanks for the detailed analysis. For the sake of completeness, can you share the full crash log in properly formatted text? Text logs are easier to read than screenshots.

Thank you

**Comment by fzyzcjy** [comment]
Sure

```
PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference, null, null)
mechanism
PlatformDispatcher.onError
WebViewHostApi.loadUrl(android_webview.pigeon.dart:279)
_SuspendState._createAsyncCallbacks.thenCallback(async_patch.dart:344)
_RootZone.runUnary(zone.dart:1653)
_FutureListener.handleValue(future_impl.dart:147)
... all below are meaningless for the issue, since it is nothing but Dart async logic

**Comment by danagbemava-nc** [comment]
Labeling for further insight from the team.

**Comment by GaryQian** [comment]
cc @bparrishMines

**Comment by stuartmorgan** [comment]
> * java dispose is triggered and finished firstly, before java loadUrl is run

How would this happen? The messages are being handled on a single thread, and my understanding is that platform channel messages are FIFO even across channels (@gaaclarke please correct me if I'm wrong; I remember we talked about this when discussing Pigeon's design). Given that, I don't see how messages sent as A, B could be handled on the native side as B, A.

**Comment by fzyzcjy** [comment]
@stuartmorgan The fact is:

> When using WebView, even just the simplest usage WebView(initialUrl: ...), an NPE happens sometimes.

And that is my guess. Feel free to correct me if I am wrong!

> my understanding is that platform channel messages are FIFO even across channels

Ah I did not know that. May I get a bit of source (i.e. more details) to check

**Comment by stuartmorgan** [comment]
> @stuartmorgan The fact is:
> 
> > When using WebView, even just the simplest usage WebView(initialUrl: ...), an NPE happens sometimes.

What is the repro case for this?

If everything described in the analysis section was speculative, we'll need an actual repro case to figure out what the cause actually is.

**Comment by fzyzcjy** [comment]
> @stuartmorgan What is the repro case for this?

It happens from time to time in production environment without a clear repro :(

> my understanding is that platform channel messages are FIFO even across channels

May I know a bit more deteails (e..g a reference)?

**Comment by gaaclarke** [comment]
> and my understanding is that platform channel messages are FIFO even across channels

@stuartmorgan That's correct with the caveat that if you are using platform channel features like specifying taskqueues or invoking from background threads, while fifo, you may not get the order you expected when considering multiple channels with different setups.  With concurrent taskqueues, it is explicitly not fifo.

**Comment by samuelnub** [comment]
Any update on a fix/workaround? I've been experiencing this quite frequently as well

**Comment by fzyzcjy** [comment]
@samuelnub I do not have update :/ Looking forward for someone fixing this1

**Comment by dragongesa** [comment]
i can confirm experienced this in the latest version of webview_flutter. that crash actually appear when i navigate into other page frequently then the webviewWidget start showing blank and the console showing me this error everytime i invoke the method in the controller. i store the webviewController in `Cubit` in the main/root of widget tree. so the state of the webview could be persistent

**Comment by fzyzcjy** [comment]
@dragongesa Hi, did you find a solution?

**Comment by dragongesa** [comment]
```
E/flutter (22836): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference, NullPointerException, Cause: null, Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference
E/flutter (22836): 	at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.loadUrl(WebViewHostApiImpl.java:280)
E/flutter (22836): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$3(GeneratedAndroidWebView.java:837)
E/flutter (22836): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda10.onMessage(Unknown Source:2)
E/flutter (22836): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/flutter (22836): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (22836): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (22836): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (22836): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (22836): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (22836): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (22836): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (22836): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/flutter (22836): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (22836): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (22836): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (22836): , null)
E/flutter (22836): #0      WebViewHostApi.loadUrl
E/flutter (22836): <asynchronous suspension>
E/flutter (22836):
E/flutter (22836): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference, NullPointerException, Cause: null, Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference
E/flutter (22836): 	at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.evaluateJavascript(WebViewHostApiImpl.java:335)
E/flutter (22836): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$12(GeneratedAndroidWebView.java:1120)
E/flutter (22836): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda20.onMessage(Unknown Source:2)
E/flutter (22836): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/flutter (22836): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (22836): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (22836): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (22836): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (22836): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (22836): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (22836): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (22836): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/flutter (22836): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (22836): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (22836): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (22836): , null)
E/flutter (22836): #0      WebViewHostApi.evaluateJavascript
E/flutter (22836): <asynchronous suspension>
E/flutter (22836): #1      TradeBloc.toggleChartSidebar
E/flutter (22836): <asynchronous suspension>
E/flutter (22836):
```

That is the log 
and below is whats in the function i invoke
```
Future<void> toggleChartSidebar() async {
...
    await webViewController.runJavaScript(
      'window.onmessage($data)',
    );
  }
...
```

Still looking for the solution, @fzyzcjy. did yours showed blank too?

**Comment by fzyzcjy** [comment]
@dragongesa Mine happens in production, so I do not know whether the user sees blank or not...

**Comment by 0x1af2aec8f957** [comment]
Same error

**Comment by pushpendraKh** [comment]
Any update? we also have millions of non-fatal events on firebase for the same.
