### ISSUE TITLE
_CastError at FixedExtentScrollPhysics.createBallisticSimulation at package:flutter/src/widgets/list_wheel_scroll_view.dart

### ISSUE THREAD

**Issue by math1man** [flutter/flutter#114543]
Hi, we're seeing a regular error in our application with the following stack trace. We haven't reproduced this ourselves, but we have a couple thousand error reports from real users in production.

I think this is an issue somewhere in `ListWheelScrollView`, which we use transitively via `CupertinoPicker`.

```
type 'FixedScrollMetrics' is not a subtype of type '_FixedExtentScrollPosition' in type cast
#0 FixedExtentScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/list_wheel_scroll_view.dart:469)
#1 ScrollPositionWithSingleContext.updateBallisticAnimation (package:flutter/src/widgets/scroll_position_with_single_context.dart:168)
#2 BallisticScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:570)
#3 ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:627)
#4 ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:101)
#5 ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:557)
#6 RenderListWheelViewport.performLayout (package:flutter/src/rendering/list_wheel_viewport.dart:687)
#7 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#8 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#9 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#10 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#11 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#12 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#13 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#14 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#15 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#16 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#17 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#18 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#19 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#20 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#21 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#22 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#23 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#24 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#25 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#26 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#27 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#28 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#29 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#30 RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:521)
#31 RenderStack.performLayout (package:flutter/src/rendering/stack.dart:635)
#32 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#33 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#34 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#35 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#36 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#37 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#38 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#39 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#40 RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:521)
#41 RenderStack.performLayout (package:flutter/src/rendering/stack.dart:635)
#42 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#43 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#44 RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:249)
#45 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#46 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#47 RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:292)
#48 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#49 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#50 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#51 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#52 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#53 ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#54 RenderStack._computeSize (package:flutter/src/rendering/stack.dart:595)
#55 RenderStack.performLayout (package:flutter/src/rendering/stack.dart:622)
#56 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#57 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#58 ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#59 RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:903)
#60 RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:938)
#61 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#62 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#63 RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:249)
#64 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#65 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#66 ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#67 RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:836)
#68 RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:938)
#69 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#70 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#71 _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:517)
#72 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#73 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#74 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#75 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#76 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#77 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#78 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#79 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#80 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#81 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#82 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#83 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#84 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#85 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#86 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#87 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#88 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#89 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#90 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#91 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#92 RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:249)
#93 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#94 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#95 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#96 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#97 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#98 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#99 RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:552)
#100 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#101 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#102 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#103 _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1467)
#104 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#105 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#106 RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:292)
#107 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#108 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#109 RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:451)
#110 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#111 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#112 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#113 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#114 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#115 RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1399)
#116 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#117 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#118 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#119 _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1467)
#120 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#121 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#122 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#123 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#124 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#125 RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:249)
#126 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#127 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#128 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#129 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#130 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#131 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#132 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#133 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#134 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#135 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#136 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#137 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#138 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#139 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#140 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#141 RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3808)
#142 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#143 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#144 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#145 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#146 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#147 _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:818)
#148 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#149 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#150 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#151 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#152 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#153 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#154 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#155 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#156 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#157 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#158 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#159 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#160 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#161 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#162 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#163 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#164 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#165 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#166 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#167 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#168 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#169 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#170 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#171 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#172 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#173 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#174 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#175 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#176 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#177 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#178 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#179 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#180 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#181 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#182 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#183 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
#184 RenderObject.layout (package:flutter/src/rendering/object.dart:2148)
#185 RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
#186 RenderView.performLayout (package:flutter/src/rendering/view.dart:170)
#187 RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1986)
#188 PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1012)
#189 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:509)
#190 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884)
#191 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:374)
#192 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175)
#193 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104)
#194 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015)
#195 _rootRun (dart:async/zone.dart:1398)
#196 _CustomZone.run (dart:async/zone.dart:1300)
#197 _CustomZone.runGuarded (dart:async/zone.dart:1208)
#198 _invoke (dart:ui/hooks.dart:147)
#199 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:320)
#200 _drawFrame (dart:ui/hooks.dart:112)
```

Internal bug: b/255643979

**Comment by jacobsimionato** [comment]
Hans, would you be able to assign this to someone? There is no repro, but I suspect the details in b/255643979 and the fact that it's a cast error might make it easy enough to track down?

**Comment by Piinks** [comment]
This looks like a bug that has already been fixed thankfully! :)

From the stack trace:

```
#1 ScrollPositionWithSingleContext.updateBallisticAnimation (package:flutter/src/widgets/scroll_position_with_single_context.dart:168)
```

`updateBallisticAnimation` was added in https://github.com/flutter/flutter/pull/107735, but then reverted in https://github.com/flutter/flutter/pull/111201 after being reported in https://github.com/flutter/flutter/issues/110340

So the good news is, this should no longer be an issue anymore. :)

**Comment by Piinks** [comment]
Closing as fixed.
