### ISSUE TITLE
Impellerc crashes when providing a bias to `texture` when targeting SkSL

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#114545]
Example repro.

```glsl
#version 460 core

precision highp float;

layout(location = 0) uniform float width;
layout(location = 1) uniform float height;
layout(location = 2) uniform float animation;
layout(location = 3) uniform sampler2D source;

out vec4 fragColor;

void main() {
    vec2 uv = gl_FragCoord.xy / vec2(width, height);
    fragColor = texture(source, uv, -1.0) * animation;
}
```

There is no stacktrace when this happens, and the flutter tool exits.

**Comment by jonahwilliams** [comment]
Sometimes it doesn't crash, but I get a runtime exception:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid SkSL:
// This SkSL shader is autogenerated by spirv-cross.

float4 flutter_FragCoord;

uniform vec4 color;
uniform shader value;
uniform half2 value_size;

vec4 fragColor;

void FLT_main()
{
    fragColor = value.eval(value_size *  vec2(0.5), 10.0);
}

half4 main(float2 iFragCoord)
{
      flutter_FragCoord = float4(iFragCoord, 0, 0);
      FLT_main();
      return fragColor;
}

SkSL Error:
error: 13: no match for shader::eval(vec2, float)
    fragColor = value.eval(value_size *  vec2(0.5), 10.0);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 error

#0      new FragmentProgram._fromAsset (dart:ui/painting.dart:4154:7)
#1      FragmentProgram.fromAsset.<anonymous closure> (dart:ui/painting.dart:4176:55)
#2      new Future.microtask.<anonymous closure> (dart:async/future.dart:277:37)
#3      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#4      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
