### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'contains' was called on null.Receiver: nullTried calling: contains("ext.flutter.activeDevToolsServerAddress")

### ISSUE THREAD

**Issue by ologunB** [flutter/flutter#114602]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains("ext.flutter.activeDevToolsServerAddress")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      waitForExtension (package:flutter_tools/src/resident_runner.dart:1483:31)
<asynchronous suspension>
#2      ResidentRunner._callDevToolsUriExtension (package:flutter_tools/src/resident_runner.dart:1302:5)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#4      ResidentRunner.maybeCallDevToolsUriServiceExtension (package:flutter_tools/src/resident_runner.dart:1291:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 2.0.6, on macOS 13.0 22A380 darwin-x64, locale en-NG)
    • Flutter version 2.0.6 at /Users/temitopedaniel/fvm/versions/2.0.6
    • Framework revision 1d9032c7e1 (1 year, 6 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/temitopedaniel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 14.0.1, Build version 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 107.0.5304.87

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
### Plugins
awesome_notifications-0.6.21
flutter_plugin_android_lifecycle-2.0.5
image_picker-0.7.5+4
image_picker_for_web-2.1.4
path_provider-2.0.4
path_provider_linux-2.1.4
path_provider_macos-2.0.4
path_provider_windows-2.0.4
pusher-channels-flutter-72ae996ad052b113adca8fd46ca12f7c3f7ffe21
share-2.0.4
social_share-2.1.1
sqflite-2.0.1

**Comment by exaby73** [comment]
Hello @ologunB. Looks like you're running an old version of Flutter (Channel unknown, 2.0.6). Please upgrade to the latest version of Flutter (3.3.7) and confirm if this issue still persists.
