### ISSUE TITLE
Failed assertion: line 5334 pos 14: '_dependents.isEmpty': is not true.

### ISSUE THREAD

**Issue by nyck33** [flutter/flutter#114787]
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#945df](state: OverlayState#d7f9b(entries: [OverlayEntry#2b3d5(opaque: true; maintainState: false), OverlayEntry#0dc92(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5334 pos 14: '_dependents.isEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///media/nobu/NTFSUbuWin1/Flutter2022/the_plant_base/lib/main.dart:32:53
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5334:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5336:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1939:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1941:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#39     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#41     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#42     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#43     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#45     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#47     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#49     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#51     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#53     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#55     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#57     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#59     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#60     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#61     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#63     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#64     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#65     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#66     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#67     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#69     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#71     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#73     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#75     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#77     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#78     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#79     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#80     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#81     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#83     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#84     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#85     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#87     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#89     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#90     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#91     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#93     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#94     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#95     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#96     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#97     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#98     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#99     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#101    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#102    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#103    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#105    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#107    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#108    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#109    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#110    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#111    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#113    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#114    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#115    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#117    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
#118    _InactiveElements.add (package:flutter/src/widgets/framework.dart:1949:7)
#119    Element.deactivateChild (package:flutter/src/widgets/framework.dart:3906:30)
#120    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5999:11)
#121    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#124    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#126    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#127    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#128    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#129    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#130    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#131    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#132    _invoke (dart:ui/hooks.dart:148:13)
#133    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#134    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
V/InputMethodManager(26551): Starting input: tba=android.view.inputmethod.EditorInfo@4ca82f6 nm : com.example.the_plant_base ic=null
I/InputMethodManager(26551): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(26551): Input channel constructed: fd=94
D/InputTransport(26551): Input channel destroyed: fd=96
D/ViewRootImpl@6f3d379[MainActivity](26551): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@6f3d379[MainActivity](26551): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 545523657728}
V/InputMethodManager(26551): Starting input: tba=android.view.inputmethod.EditorInfo@e64e6f7 nm : com.example.the_plant_base ic=null
I/InputMethodManager(26551): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(26551): Input channel constructed: fd=96
D/InputTransport(26551): Input channel destroyed: fd=94

```

**Comment by nyck33** [comment]
My repo is here, just started using gorouter, branch gorouter is where the problems occur.

https://github.com/nyck33/the-plant-base/tree/gorouter

**Comment by darshankawar** [comment]
@nyck33 
Is it possible to narrow down the repo code to only `go_router` and framework so that it'll be easier to analyze this issue ?

**Comment by nyck33** [comment]
I'm not going to do that as I'm not a contributor to Flutter.

**Comment by nyck33** [comment]
@darshankawar what is the alternative to go_router?

**Comment by darshankawar** [comment]
> what is the alternative to go_router? With deep-linking.

You may try community plugins on pub.dev which offers such feature.
