### ISSUE TITLE
flutter doctor - Error: Unable to create dart snapshot for flutter tool

### ISSUE THREAD

**Issue by manshilk** [flutter/flutter#114763]
OS details:

- Edition	Windows 11 Pro
- Version	21H2
- OS build	22000.1165
- Experience	Windows Feature Experience Pack 1000.22000.1165.0

## Steps to Reproduce

1. installed flutter stable via git: git clone https://github.com/flutter/flutter.git -b stable
2. run flutter doctor -v on Win 11-based system

## Logs

<details>
<summary>Logs</summary>

```
git clone https://github.com/flutter/flutter.git -b stable
cd .\flutter\
cd .\bin\
```

```
PS C:\apps\flutter\bin> flutter doctor -v
Building flutter tool...
Running pub upgrade...
Crash when formatting: [Encoding] Unable to decode bytes as UTF-8.
RangeError (index): Invalid value: Not in inclusive range 0..1378: 1400
#0      _StringBase.[] (dart:core-patch/string_patch.dart:260:41)
#1      Source.getTextLine (package:kernel/ast.dart:14292:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:28:38)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:95:28)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:225:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:248:9)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      SourceLoader.addMessage (package:front_end/src/fasta/source/source_loader.dart:744:20)
#8      SourceLoader.addProblem (package:front_end/src/fasta/source/source_loader.dart:699:12)
#9      LibraryBuilderImpl.addProblem (package:front_end/src/fasta/builder/library_builder.dart:221:19)
#10     SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1697:48)
#11     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:931:24)
<asynchronous suspension>
#12     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:1115:20)
<asynchronous suspension>
#13     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:1009:7)
<asynchronous suspension>
#14     KernelTarget.computeNeededPrecompilations.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:364:7)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:99:11)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#18     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:47:12)
<asynchronous suspension>
#19     generateKernel (package:front_end/src/kernel_generator_impl.dart:46:10)
<asynchronous suspension>
#20     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#21     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:412:11)
<asynchronous suspension>
#22     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:221:45)
<asynchronous suspension>
#23     _processLoadRequest (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:914:37)
<asynchronous suspension>

Crash when compiling file:///C:/Users/mansh/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/xml-6.1.0/lib/src/xml/navigation/descendants.dart,
at character offset 597:
RangeError (index): Invalid value: Not in inclusive range 0..1378: 1400
#0      _StringBase.[] (dart:core-patch/string_patch.dart:260:41)
#1      Source.getTextLine (package:kernel/ast.dart:14292:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:28:38)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:95:28)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:225:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:248:9)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      SourceLoader.addMessage (package:front_end/src/fasta/source/source_loader.dart:744:20)
#8      SourceLoader.addProblem (package:front_end/src/fasta/source/source_loader.dart:699:12)
#9      LibraryBuilderImpl.addProblem (package:front_end/src/fasta/builder/library_builder.dart:221:19)
#10     SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1697:48)
#11     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:931:24)
<asynchronous suspension>
#12     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:1115:20)
<asynchronous suspension>
#13     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:1009:7)
<asynchronous suspension>
#14     KernelTarget.computeNeededPrecompilations.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:364:7)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:99:11)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#18     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:47:12)
<asynchronous suspension>
#19     generateKernel (package:front_end/src/kernel_generator_impl.dart:46:10)
<asynchronous suspension>
#20     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#21     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:412:11)
<asynchronous suspension>
#22     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:221:45)
<asynchronous suspension>
#23     _processLoadRequest (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:914:37)
<asynchronous suspension>


#0      format (package:front_end/src/fasta/command_line_reporting.dart:113:5)
#1      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:225:32)
#2      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:248:9)
#3      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#4      SourceLoader.addMessage (package:front_end/src/fasta/source/source_loader.dart:744:20)
#5      SourceLoader.addProblem (package:front_end/src/fasta/source/source_loader.dart:699:12)
#6      LibraryBuilderImpl.addProblem (package:front_end/src/fasta/builder/library_builder.dart:221:19)
#7      SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1697:48)
#8      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:931:24)
<asynchronous suspension>
#9      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:1115:20)
<asynchronous suspension>
#10     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:1009:7)
<asynchronous suspension>
#11     KernelTarget.computeNeededPrecompilations.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:364:7)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#13     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:99:11)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#15     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:47:12)
<asynchronous suspension>
#16     generateKernel (package:front_end/src/kernel_generator_impl.dart:46:10)
<asynchronous suspension>
#17     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#18     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:412:11)
<asynchronous suspension>
#19     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:221:45)
<asynchronous suspension>
#20     _processLoadRequest (file:///C:/b/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:914:37)
<asynchronous suspension>
```

</details>

**Comment by mraleph** [comment]
Try running `dart pub cache repair` or deleting the whole folder `C:\Users\mansh\AppData\Local\Pub`, most likely your pub cache is corrupted (or you have accidentally edited it).

**Comment by manshilk** [comment]
Thank you, deleting contents of Pub\ folder resolved the issue
