### ISSUE TITLE
Intrinsics are not available for CrossAxisAlignment.baseline

### ISSUE THREAD

**Issue by bitinerant** [flutter/flutter#114748]
This issue seems closely related to "Markdown lists do not support intrinsic sizing #311" ([former link (now 404 error)](https://github.com/flutter/flutter_markdown/issues/311); [PDF version](https://github.com/flutter/flutter/files/8980606/Markdown.lists.do.not.support.intrinsic.sizing.Issue.311.flutter_flutter_markdown.pdf); [bug about the missing link](https://github.com/flutter/flutter/issues/102527)) but this is clearly not fixed. See also [Column intrinsic height measurement broken on latest dev](https://github.com/flutter/flutter/issues/71990).

## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 

A dialog box displaying:

* one
* two

Note that this Markdown text works correctly in the `build()` widget but crashes in `showDialog()`.

**Actual results:** 

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Intrinsics are not available for CrossAxisAlignment.baseline.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 524 pos 9: 'RenderObject.debugCheckingIntrinsics'
```
(full output below)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      showDialog(
          context: context,
          barrierDismissible: false,
          builder: (BuildContext context) => AlertDialog(
                title: Text('This is the title'),
                content: const MarkdownBody(
                  // data: 'test text',
                  data: '* one\n* two\n',
                ),
                actions: <Widget>[
                  TextButton(
                    style: TextButton.styleFrom(
                      textStyle: Theme.of(context).textTheme.labelLarge,
                    ),
                    onPressed: () {
                      Navigator.of(context).pop(context);
                    },
                    child: Text('OK'),
                  )
                ],
              ));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const MarkdownBody(
              data: '* one\n* two\n',
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
$ flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           

(yelb20:8193): dbind-WARNING **: 13:36:56.983: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus: No such file or directory
Syncing files to device Linux...                                    57ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:34225/Jrja3w9Imio=/
The Flutter DevTools debugger and profiler on Linux is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:34225/Jrja3w9Imio=/

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Intrinsics are not available for CrossAxisAlignment.baseline.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 524 pos 9: 'RenderObject.debugCheckingIntrinsics'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  AlertDialog AlertDialog:file:///home/ubuntu/docs/code/flutter/yelb20/lib/main.dart:48:46

When the exception was thrown, this was the stack:
#2      RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:524:9)
#3      RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:633:12)
#4      RenderBox._computeIntrinsicDimension.<anonymous closure>
(package:flutter/src/rendering/box.dart:1416:23)
#5      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#6      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1414:57)
#7      RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1781:12)
#8      RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:574:32)
#9      RenderFlex.computeMaxIntrinsicWidth (package:flutter/src/rendering/flex.dart:615:12)
#10     RenderBox._computeIntrinsicDimension.<anonymous closure>
(package:flutter/src/rendering/box.dart:1416:23)
#11     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#12     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1414:57)
#13     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1616:12)
#14     RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:80:21)
#15     RenderBox._computeIntrinsicDimension.<anonymous closure>
(package:flutter/src/rendering/box.dart:1416:23)
#16     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#17     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1414:57)
#18     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1616:12)
#19     RenderPadding.computeMaxIntrinsicWidth (package:flutter/src/rendering/shifted_box.dart:189:21)
#20     RenderBox._computeIntrinsicDimension.<anonymous closure>
(package:flutter/src/rendering/box.dart:1416:23)
#21     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#22     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1414:57)
#23     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1616:12)
#24     RenderFlex.computeMaxIntrinsicWidth.<anonymous closure>
(package:flutter/src/rendering/flex.dart:618:60)
#25     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:594:58)
#26     RenderFlex.computeMaxIntrinsicWidth (package:flutter/src/rendering/flex.dart:615:12)
#27     RenderBox._computeIntrinsicDimension.<anonymous closure>
(package:flutter/src/rendering/box.dart:1416:23)
#28     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#29     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1414:57)
#30     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1616:12)
#31     RenderIntrinsicWidth._computeSize (package:flutter/src/rendering/proxy_box.dart:728:37)
#32     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:753:12)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#34     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#37     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#40     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#42     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:552:11)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1462:11)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#49     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:292:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#52     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:451:14)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#54     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#55     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:249:12)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#57     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#58     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:249:12)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#61     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:249:12)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#63     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#66     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#69     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#72     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#75     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#78     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#81     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#84     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#86     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3737:13)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#88     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#91     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#92     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:804:15)
#93     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1973:7)
#94     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:999:18)
#95     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:513:19)
#96     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#97     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#98     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#99     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#100    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#101    _invoke (dart:ui/hooks.dart:148:13)
#102    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#103    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)

The following RenderObject was being processed when the exception was fired: RenderIntrinsicWidth#2547c
relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: IntrinsicWidth ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
    _InkFeatures-[GlobalKey#c238c ink renderer] ← NotificationListener<LayoutChangedNotification> ←
    CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ← ConstrainedBox ←
    ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(280.0<=w<=1200.0, 0.0<=h<=672.0)
  size: MISSING
  stepWidth: null
  stepHeight: null
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderFlex#decf5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child 1: RenderPadding#d5880 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderSemanticsAnnotations#2f398 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderParagraph#f60ae NEEDS-LAYOUT NEEDS-PAINT
            text: TextSpan
      child 2: RenderPadding#e033c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderSemanticsAnnotations#ab21f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderFlex#71ee4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child 1: RenderFlex#da796 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child 2: RenderConstrainedBox#e1c27 NEEDS-LAYOUT NEEDS-PAINT
            child 3: RenderFlex#87384 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child 3: RenderPadding#d0e7b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: _RenderOverflowBar#2347e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child 1: RenderSemanticsAnnotations#2f7b3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: _RenderInputPadding#c2958 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: RenderBox was not laid out: RenderIntrinsicWidth#2547c relayoutBoundary=up6
NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#74464
relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#7b6f5 relayoutBoundary=up4
NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#1b164 relayoutBoundary=up3
NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#80bc8 relayoutBoundary=up2
NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 361
pos 12: 'child!.hasSize': is not true.

Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#80bc8 relayoutBoundary=up2

Another exception was thrown: Updated layout information required for RenderFlex#decf5 NEEDS-LAYOUT
NEEDS-PAINT to calculate semantics.
Lost connection to device.

(yelb20:8193): GLib-GObject-WARNING **: 13:37:49.655: ../../../gobject/gsignal.c:2731: instance '0x556b01b091b0' has no handler with id '238'

```

```
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.7, on Ubuntu 22.04.1 LTS 5.14.0-1046-oem, locale C.UTF-8)
    • Flutter version 3.3.7 on channel stable at /home/ubuntu/docs/code/flutter/builder
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (4 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.14.0-1046-oem
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Based on the error log, it seems to be similar to https://github.com/flutter/flutter/issues/96806, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
