### ISSUE TITLE
[tool_crash] FileSystemException: readSync failed, OS Error: The cloud file provider is not running., errno = 362

### ISSUE THREAD

**Issue by Alex1-ai** [flutter/flutter#114773]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readSync failed, OS Error: The cloud file provider is not running.
, errno = 362
```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:763:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:552:23)
#2      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#4      ErrorHandlingFile.readAsStringSync.<anonymous c

**Comment by darshankawar** [comment]
@Alex1-ai 
Can you provide `flutter doctor -v` and complete stacktrace ?
