### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by nshiraki** [flutter/flutter#114771]
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2221:3)
#1      _BytesBuilder.takeBytes (dart:_internal/bytes_builder.dart:205:18)
#2      ZLibDecoder.convert (dart:io/data_transformer.dart:365:25)
#3      inflateBuffer_ (package:archive/src/zlib/_inflate_buffer_io.dart:4:33)
#4      inflateBuffer (package:archive/src/zlib/inflate_buffer.dart:6:10)
#5      ArchiveFile.decompress (package:archive/src/archive_file.dart:154:22)
#6      ArchiveFile.content (package:archive/src/archive_file.dart:125:7)
#7      _WindowsUtils._unpackArchive (package:flutter_tools/src/base/os.dart:557:45)
#8      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:510:5)
#9      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1111:18)
#10     _rootRunUnary (dart:async/zone.dart:1399:47)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:147:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:766:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:795:13)
#14     _rootRunUnary (dart:async/zone.dart:1399:47)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:147:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:766:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:795:13)
#18     Future._complete (dart:async/future_impl.dart:557:7)
#19     Stream.last.<anonymous closure> (dart:async/stream.dart:1612:20)
#20     _rootRun (dart:async/zone.dart:1383:47)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
#22     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#23     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#24     _DelayedDone.perform (dart:async/stream_impl.dart:534:14)
```
```
[✓] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.22621.521], locale ja-JP)
    • Flutter version 3.3.7 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (5 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\uminekoken\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code, 64-bit edition (version 1.72.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.521]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 107.0.5304.88
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 105.0.1343.33

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
Labeling this based on stacktrace and there's not an existing issue alreaddy for this.

/cc @christopherfujino

**Comment by christopherfujino** [comment]
Deduping with https://github.com/flutter/flutter/issues/133371 (basically stop using package:archive to extract zips on windows)
