### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = 'C:\Users\sps.mark.cabansag\Desktop\EAggroApp\ios\Runner\GeneratedPluginRegistrant.h' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by mcabansag** [flutter/flutter#114864]
## Command
```
flutter run --machine --start-paused -d emulator-5554 --target lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\sps.mark.cabansag\Desktop\EAggroApp\ios\Runner\GeneratedPluginRegistrant.h' (OS Error: Access is denied.
, errno = 5)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:137:22)
#6      ErrorHandlingFile._runSync (package:flutter_tools/src/base/error_handling_file_system.dart:163:16)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_file_system.dart:136:5)
#8      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:28:8)
#9      _writeIOSPluginRegistrant (package:flutter_tools/src/plugins.dart:860:5)
#10     injectPlugins (package:flutter_tools/src/plugins.dart:1082:11)
<asynchronous suspension>
#11     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:232:11)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:708:21)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.22000.856], locale en-PH)
    • Flutter version 1.17.5 at C:\Users\sps.mark.cabansag\Documents\flutter
    • Framework revision 8af6b2f038 (2 years, 4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\sps.mark.cabansag\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.73.0)
    • VS Code at C:\Users\sps.mark.cabansag\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • Lenovo TB 8505X     • HGR2AAJR      • android-arm64 • Android 10 (API 29)
    • AOSP on IA Emulator • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
android_intent-0.3.7+7
connectivity-0.4.9+5
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
file_picker-1.13.3
flutter_local_notifications-1.5.0+1
flutter_plugin_android_lifecycle-1.0.11
fluttertoast-7.1.8
g_captcha-1.0.0
image_gallery_saver-1.6.8
image_picker-0.6.7+22
open_file-2.1.1
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
permission_handler-5.1.0+2
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.1+2
syncfusion_flutter_pdfviewer-18.3.47-beta
url_launcher-5.7.6
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.4+1
url_launcher_windows-0.0.1+3
vibration-1.5.0

**Comment by exaby73** [comment]
Hello @mcabansag. This could be possibly caused by Windows Defender blocking access to that folder. Try moving the project to another folder or disabling Windows Defender to see if that fixes this issue?

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/92695
