### ISSUE TITLE
Investigate codesigning failures on `Mac_ios`

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/flutter#114837]
In https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20new_gallery_impeller_ios__transition_perf/2080/overview and https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20fullscreen_textfield_perf_impeller_ios__e2e_summary/1182/overview we ran into codesigning failures that caused the tree to go red. A re-run has cleared up these failures.

Tree is currently green.

**Comment by christopherfujino** [comment]
So I'm seeing:

```
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:             [   +9 ms] Target profile_unpack_ios failed: Exception: Failed to codesign /opt/s/w/ir/x/t/flutter_new_gallery_test.KQxHx3/gallery/build/ios/Profile-iphoneos/Flutter.framework/Flutter with identity CC21BF11AB9925313E54CD4FCCFEB82347E75AFA.
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        /opt/s/w/ir/x/t/flutter_new_gallery_test.KQxHx3/gallery/build/ios/Profile-iphoneos/Flutter.framework/Flutter: errSecInternalComponent
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout: 
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #0      _signFramework (package:flutter_tools/src/build_system/targets/ios.dart:714:5)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #1      UnpackIOS.build (package:flutter_tools/src/build_system/targets/ios.dart:299:5)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:27)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #3      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #5      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #6      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:337:32)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        #17     main (package:flutter_tools/executable.dart:91:3)
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                        <asynchronous suspension>
```

And also:

```
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:            2022-11-07 10:16:19.781 xcdevice[59905:247440]  DVTDownloadable: Unexpected error attempting to parse downloadable from index: Error Domain=DVTDownloadableErrors Code=16 "Unable to read in downloadable data. See underlying errors for details." UserInfo={DownloadablePlist={
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                category = simulator;
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                contentType = package;
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                dictionaryVersion = 2;
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                fileSize = 1173622072;
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                hostRequirements =     {
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                    maxHostVersion = "12.99.0";
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                };
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                identifier = "com.apple.pkg.AppleTVSimulatorSDK12_4";
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                name = "tvOS 12.4 Simulator";
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                platform = "com.apple.platform.appletvos";
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                simulatorVersion =     {
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                    buildUpdate = 16M567;
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                    version = "12.4";
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                };
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                source = "https://devimages-cdn.apple.com/downloads/xcode/simulators/com.apple.pkg.AppleTVSimulatorSDK12_4-12.4.1.1568665771.dmg";
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                version = "12.4.1.1568665771";
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:            }, NSLocalizedDescription=Unable to read in downloadable data. See underlying errors for details., DVTUnderlyingErrorsKey=(
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:                "Error Domain=DVTDownloadableErrors Code=23 \"'com.apple.platform.appletvos' is an unknown platform identifier.\" UserInfo={NSLocalizedDescription='com.apple.platform.appletvos' is an unknown platform identifier.}"
[new_gallery_impeller_ios__transition_perf] [STDOUT] stdout:            )}
```

The former is the build error, not sure if the latter is related.

**Comment by ricardoamador** [comment]
We are tracking the code signing investigate/fix here: https://github.com/flutter/flutter/issues/115000. That issue is a P0 so closing this as a duplicate.
