### ISSUE TITLE
[local_auth][Android] Unable to instantiate fragment androidx.biometric.FingerprintDialogFragment: could not find Fragment constructor

### ISSUE THREAD

**Issue by DjordjeMancic97** [flutter/flutter#114971]
Hello, I am getting this error in Firebase Crashlytics and unfortunately was unable to reproduce it myself. 
We are using local_auth plugin and we followed the instructions specified in plugin docs. So `MainActivity` is extending `FlutterFragmentActivity()` as specified there.

local_auth version is 2.1.0

Flutter doctor: 
```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

Full stacktrace:
```
Caused by java.lang.NoSuchMethodException: <init> []
       at java.lang.Class.getConstructor0(Class.java:2320)
       at java.lang.Class.getConstructor(Class.java:1725)
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
       at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
       at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:352)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
       at io.flutter.embedding.android.FlutterFragmentActivity.onCreate(FlutterFragmentActivity.java:279)
       at de.bank.clanq.MainActivity.onCreate(MainActivity.kt:307)
       at android.app.Activity.performCreate(Activity.java:6984)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2783)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2909)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

**Comment by huycozy** [comment]
Hi @DjordjeMancic97 
I don't see the error message `Unable to instantiate fragment androidx.biometric.FingerprintDialogFragment: could not find Fragment constructor` in your stacktrace. Is that the full log of stracktrace? If not, please provide them all so we can investigate better. 

Also, please provide the list of affected device info and the percentage occurrence of the crash. Thanks!

**Comment by DjordjeMancic97** [comment]
@huycozy Hi, I updated my first comment with more details

**Comment by reidbaker** [comment]
@DjordjeMancic97   Can you share anything about this user that might make them stand out amongst your other users? Ex they are on an older version of android? That they might have denied permissions to your app for fingerprint etc? Does a fresh uninstall and resinstall solve this issue? 


@camsim99 Can you do a quick double check to ensure that our local auth plugin works when permission is denied.

**Comment by DjordjeMancic97** [comment]
> @DjordjeMancic97 Can you share anything about this user that might make them stand out amongst your other users? Ex they are on an older version of android? That they might have denied permissions to your app for fingerprint etc? Does a fresh uninstall and resinstall solve this issue?
> 
> @camsim99 Can you do a quick double check to ensure that our local auth plugin works when permission is denied.

Unfortunately, we dont have more information about this user. Device this happened on is Moto Z2 Play with Android 8.0, about permission, I thought USE_FINGERPRINT can't be denied and is used automatically. At least I am not seeing any permission dialogs regarding this functionality.

**Comment by camsim99** [comment]
@reidbaker I misspoke when we first talked about this bug. This has to do with the prompt that shows to actually receive the fingerprint, not request permissions.

Seems like this is a known bug https://issuetracker.google.com/issues/181805603. I will follow up on that and can also try the noted [work around](https://issuetracker.google.com/issues/181805603#comment14).

**Comment by markusrubey** [comment]
@camsim99 could you share insights on the workaround?

**Comment by stuartmorgan-g** [comment]
Per [this comment in the upstream issue](https://issuetracker.google.com/issues/181805603#comment26), this is waiting for an updated (1.4.x or later) release of `androidx.biometric:biometric`.
