### ISSUE TITLE
'dart:ui/painting.dart': Failed assertion: line 1682 pos 12: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by dev-zl** [flutter/flutter#115064]
What was the mistake?

<details>
<summary>Logs</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while rebuilding dirty elements:
'dart:ui/painting.dart': Failed assertion: line 1682 pos 12: '<optimized out>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///E:/dev/app/untitled_ly/flutter_ly/lib/main.dart:82:14
When the exception was thrown, this was the stack: 
#2      Image.dispose (dart:ui/painting.dart:1682:12)
#3      ImageInfo.dispose (package:flutter/src/painting/image_stream.dart:125:11)
#4      DecorationImagePainter.dispose (package:flutter/src/painting/decoration_image.dart:386:13)
#5      _BoxDecorationPainter.dispose (package:flutter/src/painting/box_decoration.dart:486:20)
#6      RenderDecoratedBox.detach (package:flutter/src/rendering/proxy_box.dart:2323:15)
#7      RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#8      RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#9      RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#10     RenderDecoratedBox.detach (package:flutter/src/rendering/proxy_box.dart:2325:11)
#11     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#12     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#13     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#14     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#15     ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3842:13)
#16     ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3842:13)
#17     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#18     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#19     ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3842:13)
#20     ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3842:13)
#21     ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3842:13)
#22     ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3842:13)
#23     RenderCustomMultiChildLayoutBox.detach (package:flutter/src/rendering/custom_layout.dart:354:11)
#24     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#25     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#26     _RenderCustomClip.detach (package:flutter/src/rendering/proxy_box.dart:1438:11)
#27     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#28     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#29     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#30     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#31     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#32     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#33     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#34     RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:3557:15)
#35     ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3842:13)
#36     AbstractNode.dropChild (package:flutter/src/foundation/node.dart:155:13)
#37     RenderObject.dropChild (package:flutter/src/rendering/object.dart:1498:11)
#38     RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:3537:7)
#39     SingleChildRenderObjectElement.insertRenderObjectChild (package:flutter/src/widgets/framework.dart:6315:18)
#40     RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6079:35)
#41     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5751:5)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4918:16)
#45     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#47     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#48     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#49     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#50     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#51     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#52     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#53     _invoke (dart:ui/hooks.dart:148:13)
#54     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#55     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
The element being rebuilt at the time was index 0 of 7: Overlay-[LabeledGlobalKey<OverlayState>#60629]
  dependencies: [MediaQuery]
  state: OverlayState#13dfb(entries: [OverlayEntry#b06c6(opaque: true; maintainState: false), OverlayEntry#f462a(opaque: false; maintainState: true), OverlayEntry#c9c22(opaque: true; maintainState: false), OverlayEntry#b37be(opaque: false; maintainState: true)])
====================================================================================================
```

</details>

**Comment by dev-zl** [comment]
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [版本 10.0.17134.112], locale zh-CN)
    • Flutter version 3.3.7 on channel stable at \SDK\flutter_windows_3.3.7-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (8 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Users\a\AppData\Local\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\app\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at E:\ProgramFiles\JetBrains\IntelliJ IDEA 2019.3.5
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [版本 10.0.17134.112]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.146

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by exaby73** [comment]
Hello @dev-zl. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
