### ISSUE TITLE
Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null) #0      PathProviderApi.getApplicationDocumentsPath (package:path_provider_ios/messages.g.dart:108:7)

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#115229]
Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      PathProviderApi.getApplicationDocumentsPath (package:path_provider_ios/messages.g.dart:108:7)

**Comment by danagbemava-nc** [comment]
Hi @jinfagang,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce?

Please also provide the version of `path_provider` you're using. 

Thank you

**Comment by Subarkah7** [comment]
Found the same issue with path_provider: ^2.0.11 on flutter 3.3.4

**Comment by Subarkah7** [comment]
> 

Solved by flutter clean & flutter pub get again

**Comment by jinfagang** [comment]
@Subarkah7 its not work,

**Comment by danagbemava-nc** [comment]
Hi @jinfagang,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce?

Please also provide the version of `path_provider` you're using. 

Thank you

**Comment by jinfagang** [comment]
I solved it, but I am not gonna post solution.
