### ISSUE TITLE
Global key is null when navigating outside my Local/internal package

### ISSUE THREAD

**Issue by mkassir95** [flutter/flutter#115233]
I have an internal/local package, when I navigate outside the package and then return back to the pages of the package the global keys  of the package become null. The first time I enters the page, all things work fine without error.

These are the logs

<details>
<summary>logs</summary>

```
Unhandled Exception: NoSuchMethodError: The method 'insertItem' was called on null.
E/flutter (10976): Receiver: null
E/flutter (10976): Tried calling: insertItem(100)
E/flutter (10976): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (10976): #1      _AplimanAssistantState.flushResponses.<anonymous closure> (package:aida_chat_bot_pkg/pages/assistant.dart:713:16)
E/flutter (10976): #2      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (10976): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (10976): #5      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (10976): #6      _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (10976): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #8      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (10976): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (10976): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (10976): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10976): 
E/flutter (10976): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'insertItem' was called on null.
E/flutter (10976): Receiver: null
E/flutter (10976): Tried calling: insertItem(101)
E/flutter (10976): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (10976): #1      _AplimanAssistantState.flushResponses.<anonymous closure> (package:aida_chat_bot_pkg/pages/assistant.dart:713:16)
E/flutter (10976): #2      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (10976): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (10976): #5      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (10976): #6      _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (10976): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #8      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (10976): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (10976): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (10976): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10976): 
E/flutter (10976): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'insertItem' was called on null.
E/flutter (10976): Receiver: null
E/flutter (10976): Tried calling: insertItem(102)
E/flutter (10976): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (10976): #1      _AplimanAssistantState.flushResponses.<anonymous closure> (package:aida_chat_bot_pkg/pages/assistant.dart:713:16)
E/flutter (10976): #2      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (10976): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (10976): #5      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (10976): #6      _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (10976): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #8      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (10976): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (10976): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (10976): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10976): 
E/flutter (10976): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'insertItem' was called on null.
E/flutter (10976): Receiver: null
E/flutter (10976): Tried calling: insertItem(103)
E/flutter (10976): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (10976): #1      _AplimanAssistantState.flushResponses.<anonymous closure> (package:aida_chat_bot_pkg/pages/assistant.dart:713:16)
E/flutter (10976): #2      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (10976): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (10976): #5      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (10976): #6      _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (10976): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #8      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (10976): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (10976): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (10976): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10976): 
E/flutter (10976): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'insertItem' was called on null.
E/flutter (10976): Receiver: null
E/flutter (10976): Tried calling: insertItem(104)
E/flutter (10976): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (10976): #1      _AplimanAssistantState.flushResponses.<anonymous closure> (package:aida_chat_bot_pkg/pages/assistant.dart:713:16)
E/flutter (10976): #2      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (10976): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (10976): #5      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (10976): #6      _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (10976): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #8      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (10976): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (10976): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (10976): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10976): 
E/flutter (10976): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'insertItem' was called on null.
E/flutter (10976): Receiver: null
E/flutter (10976): Tried calling: insertItem(105)
E/flutter (10976): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (10976): #1      _AplimanAssistantState.flushResponses.<anonymous closure> (package:aida_chat_bot_pkg/pages/assistant.dart:713:16)
E/flutter (10976): #2      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (10976): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (10976): #5      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (10976): #6      _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (10976): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #8      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (10976): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (10976): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (10976): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10976): 
E/flutter (10976): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'insertItem' was called on null.
E/flutter (10976): Receiver: null
E/flutter (10976): Tried calling: insertItem(106)
E/flutter (10976): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (10976): #1      _AplimanAssistantState.flushResponses.<anonymous closure> (package:aida_chat_bot_pkg/pages/assistant.dart:713:16)
E/flutter (10976): #2      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (10976): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (10976): #5      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (10976): #6      _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (10976): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #8      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (10976): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (10976): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (10976): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10976): 
E/flutter (10976): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'insertItem' was called on null.
E/flutter (10976): Receiver: null
E/flutter (10976): Tried calling: insertItem(107)
E/flutter (10976): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (10976): #1      _AplimanAssistantState.flushResponses.<anonymous closure> (package:aida_chat_bot_pkg/pages/assistant.dart:713:16)
E/flutter (10976): #2      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (10976): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (10976): #5      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (10976): #6      _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (10976): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (10976): #8      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (10976): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (10976): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (10976): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
</details>

And this is the code making the error

<details>
<summary> code</summary>

```dart
          currentAssistantResponseList
              .add(tempAssistantResponseList[messageListAnimationIndex]);
          _listKey.currentState
              .insertItem(currentAssistantResponseList.length - 1);
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @mkassir95,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

In the future, when filing an issue, please provide some or all of the information in the template.

Thank you

**Comment by mkassir95** [comment]
Kindly note I updates my question

**Comment by mkassir95** [comment]
this is my flutter doctor
`PS C:\Users\user\Documents\AIDA-BOT-CHANGES> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19045.2251], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.7)
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.70.0)
[√] Connected device (4 available)
[√] HTTP Host Availability
`

**Comment by danagbemava-nc** [comment]
Hi @mkassir95, you are on an older version of flutter. Kindly upgrade to the latest version of flutter to see if you still experience the issue. 

If you do, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can run without needing to make a lot of changes so that we can investigate this. 

Thank you
