### ISSUE TITLE
[camera] Unhandled Exception: MissingPluginException when running from Isolate

### ISSUE THREAD

**Issue by RUSSCITY** [flutter/flutter#115282]
I'm trying to get available cameras, when I get an FCM in background (so this code is running in isolate):
`final availableCamerasList = await availableCameras();`

I have tried to ensure initialization before requesting available cameras, but nothing helps:
```
    WidgetsFlutterBinding.ensureInitialized();
    DartPluginRegistrant.ensureInitialized();
    final availableCamerasList = await availableCameras();
```

Running this code in main works fine. Is there some another part I have forgot to initialize before running in isolate?

Stacktrace:
```
E/flutter ( 4745): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)
E/flutter ( 4745): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter ( 4745): <asynchronous suspension>
E/flutter ( 4745): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:485:35)
E/flutter ( 4745): <asynchronous suspension>
E/flutter ( 4745): #2      MethodChannelCamera.availableCameras (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:66:52)
E/flutter ( 4745): <asynchronous suspension>
E/flutter ( 4745): #3      ActionsProvider.provideCameraSettings (package:alltrackervideosecurity/application/socket/actions_provider.dart:110:34)
E/flutter ( 4745): <asynchronous suspension>
```

pubspec.yaml:
`  camera: ^0.10.0+4`

flutter doctor:
```
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.22000.1219], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.0)
[√] Android Studio (version 2021.3)
[√] Connected device (5 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by RUSSCITY** [comment]
> Hi @RUSSCITY This issue seems to be fixed on the latest `master` channel as mentioned at [#13937 (comment)](https://github.com/flutter/flutter/issues/13937#issuecomment-1268778461). Please try retry on master channel and confirm if the issue is fixed.

Thank you @huycozy for your answer. Sadly I don't see any `master` branch on this project, only the `main` branch. And sadly I still face the same problem when I trying to use latest `main` branch. Is there something I do wrong?

Here is the dependency I used:
```
  camera:
    git:
      url: https://github.com/flutter/plugins.git
      ref: main
      path: ./packages/camera/camera
```

Still get this error:
```
E/flutter (22639): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera_android)
E/flutter (22639): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (22639): <asynchronous suspension>
E/flutter (22639): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:485:35)
E/flutter (22639): <asynchronous suspension>
E/flutter (22639): #2      AndroidCamera.availableCameras (package:camera_android/src/android_camera.dart:74:52)
E/flutter (22639): <asynchronous suspension>
E/flutter (22639): #3      ActionsProvider.provideCameraSettings (package:alltrackervideosecurity/application/socket/actions_provider.dart:110:34)
E/flutter (22639): <asynchronous suspension>
```

**Comment by huycozy** [comment]
@RUSSCITY Sorry for not being clear. I mean `master` in [Flutter channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels). You can switch to master as below commands:

```
flutter channel master
flutter upgrade
```

Or follow this [guideline](https://medium.com/@sarbagyastha/using-two-or-more-different-versions-of-flutter-in-single-machine-484293c2a7ff) to setup multiple Flutter version. 
And then retry running your project on with `master` channel.

**Comment by RUSSCITY** [comment]
@huycozy Thank you for your explanation. Sadly this hasn't helped me to fix this issue. 
Getting the same error:
```
E/flutter (17885): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera_android)
E/flutter (17885): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
E/flutter (17885): <asynchronous suspension>
E/flutter (17885): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:504:35)
E/flutter (17885): <asynchronous suspension>
E/flutter (17885): #2      AndroidCamera.availableCameras (package:camera_android/src/android_camera.dart:74:52)
E/flutter (17885): <asynchronous suspension>
E/flutter (17885): #3      ActionsProvider.provideCameraSettings (package:alltrackervideosecurity/application/socket/actions_provider.dart:110:34)
E/flutter (17885): <asynchronous suspension>
```

Used library: `camera: 0.10.0+4`

flutter doctor:
```
[√] Flutter (Channel master, 3.6.0-3.0.pre.54, on Microsoft Windows [Version 10.0.22000.1219], locale de-DE)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.0)
[√] Android Studio (version 2021.3)
[√] Connected device (5 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

Is there any hope?

**Comment by huycozy** [comment]
Hi @RUSSCITY 
Thanks for providing sample code, but I see there is a 3rd plugin `flutter_foreground_task`. 

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.

Thank you!

**Comment by RUSSCITY** [comment]
Hi @huycozy thank you again for your answer! My fault, you are right. Looks like some problem with exactly this plugin. I will try to reproduce it without this plugin, or to find out why this happening. I will write back, whenever I have more info on it.
