### ISSUE TITLE
[iOS]: macOS 13.* (Ventura) -> Library not found for -liPhone-lib

### ISSUE THREAD

**Issue by Ahmadre** [flutter/flutter#115300]
## Steps to Reproduce

1. You have a macOS with Ventura 13.*
2. You have at least XCode 14.*
3. You have at least iOS/iPadOS 16.*
4. Start debugging your iOS App like always (main flutter counter template for example)
5. You'll get an `Library not found for -liPhone-lib` error before your app is even starting.

**Expected results:**

iOS/iPadOS are starting successfully.

**Actual results:**

<details>
<summary>Error</summary>

```
[  +18 ms] Could not build the precompiled application for the device.
[   +2 ms] Error (Xcode): Library not found for -liPhone-lib

[        ] Error launching application on iPad von Rebar.
[   +1 ms] 
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:615:9)
           <asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#4      CommandRunner.runCommand
package:args/command_runner.dart:209
           <asynchronous suspension>
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
#8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
3
Exited
```

</details>

**What I tried till now:**

- Re-install XCode completely
- Re-install iOS Platform Support for XCode
- Clean XCode-Workspace
- Remove Pods and re-install them
- Check if App is still working on Web and Android -> YES
- Check and Uncheck `Based on dependency analysis` -> same error
- Restart my mac -> same error

## Logs

<details>
  <summary>Logs</summary>

-> Google Drive Logfile: https://drive.google.com/file/d/1xbeJVvuxHIOoCfTWlmKCFCnd668ZoSlp/view?usp=sharing

```
❯ flutter analyze
Analyzing fenzta-home...                                                
No issues found! (ran in 5.1s)
```

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm (Rosetta), locale de-DE)
    • Flutter version 3.3.8 on channel stable at /Users/rebar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (vor 6 Tagen), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/rebar/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 56.0.3
    • Dart plugin version 203.8173

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPad von Rebar (mobile) • 00008103-0018042034FB001E • ios            • iOS 16.1.1 20B101
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm (Rosetta)
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by Ahmadre** [comment]
Solved -> I had to build and link symbols again to get in working :)
