### ISSUE TITLE
linux run with local engine results in dart compiler unexepectedly exiting

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#115384]
## Description

I'm unable to run flutter on linux with a local engine, the dart compiler crashes.

## Log
```
clarkeaa@gamer:~/dev/flutter-examples/linux_plugin/example$ flutter -d linux --local-engine-src-path ~/dev/engine/src --local-engine=host_debug_unopt -v run
[  +29 ms] executing: uname -m
[  +12 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +2 ms] executing: [/home/clarkeaa/dev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 52b3dc25f6471c27b2144594abb11c741cb88f57
[        ] executing: [/home/clarkeaa/dev/flutter/] git tag --points-at 52b3dc25f6471c27b2144594abb11c741cb88f57
[   +5 ms] Exit code 0 from: git tag --points-at 52b3dc25f6471c27b2144594abb11c741cb88f57
[        ] 3.3.8
[  +19 ms] Local engine source at /home/clarkeaa/dev/engine/src
[   +4 ms] executing: [/home/clarkeaa/dev/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +1 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/home/clarkeaa/dev/flutter/] git ls-remote --get-url origin
[        ] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +55 ms] Unable to locate an Android SDK.
[   +4 ms] executing: [/home/clarkeaa/dev/flutter/] git rev-parse --abbrev-ref HEAD
[   +1 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +23 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] Skipping pub get: version match.
[   +9 ms] Found plugin linux_plugin at /home/clarkeaa/dev/flutter-examples/linux_plugin/
[  +18 ms] Found plugin linux_plugin at /home/clarkeaa/dev/flutter-examples/linux_plugin/
[  +47 ms] Initializing file store
[   +4 ms] Skipping target: gen_localizations
[   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/clarkeaa/dev/flutter-examples/linux_plugin/example/.dart_tool/package_config_subset}
[   +2 ms] Found plugin linux_plugin at /home/clarkeaa/dev/flutter-examples/linux_plugin/
[   +5 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib/main.dart on Linux in debug mode...
[   +2 ms] /home/clarkeaa/dev/engine/src/out/host_debug_unopt/dart-sdk/bin/dart --disable-dart-dev /home/clarkeaa/dev/engine/src/out/host_debug_unopt/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/clarkeaa/dev/engine/src/out/host_debug_unopt/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.FRQCKH/flutter_tool.GSLPFK/app.dill --packages /home/clarkeaa/dev/flutter-examples/linux_plugin/example/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +13 ms] Building Linux application...
[   +8 ms] <- compile package:linux_plugin_example/main.dart
[   +1 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/clarkeaa/dev/flutter-examples/linux_plugin/example/linux
[  +15 ms] -- Configuring done
[   +5 ms] -- Generating done
[        ] -- Build files have been written to: /home/clarkeaa/dev/flutter-examples/linux_plugin/example/build/linux/x64/debug
[   +2 ms] executing: ninja -C build/linux/x64/debug install
[   +3 ms] ninja: Entering directory `build/linux/x64/debug'
[   +6 ms] ERROR: FormatException: Could not find an option named "verbosity".
[        ] Usage: server [options] [input.dart]
[        ] If filename or uri pointing to the entrypoint is provided on the command line,
[        ] then the server compiles it, generates dill file and exits.
[        ] If no entrypoint is provided on the command line, server waits for
[        ] instructions from stdin.
[        ] Instructions:
[        ] - compile <input.dart>
[        ] - recompile [<input.dart>] <boundary-key>
[        ] <invalidated file uri>
[        ] <invalidated file uri>
[        ] ...
[        ] <boundary-key>
[        ] - accept
[        ] - quit
[        ] Output:
[        ] - result <boundary-key>
[        ] <compiler output>
[        ] <boundary-key> [<output.dill>]
[        ] Options:
[        ]     --train                                    Run through sample command line to produce snapshot
[        ]     --[no-]incremental                         Run compiler in incremental mode
[        ]     --sdk-root                                 Path to sdk root
[        ]                                                (defaults to "../../out/android_debug/flutter_patched_sdk")
[        ]     --platform                                 Platform kernel filename
[        ]     --[no-]aot                                 Run compiler in AOT mode (enables whole-program transformations)
[        ]     --[no-]tfa                                 Enable global type flow analysis and related transformations in AOT mode.
[        ]     --[no-]tree-shake-write-only-fields        Enable tree shaking of fields which are only written in AOT mode.
[        ]                                                (defaults to on)
[        ]     --[no-]protobuf-tree-shaker-v2             Enable protobuf tree shaker v2 in AOT mode.
[        ]     --[no-]minimal-kernel                      Produce minimal tree-shaken kernel file.
[        ]     --[no-]link-platform                       When in batch mode, link platform kernel file into result kernel file. Intended use is to satisfy different loading strategies implemented by gen_snapshot(which needs platform embedded) vs
Flutter engine(which does not)
[        ]                                                (defaults to on)
[        ]     --import-dill                              Import libraries from existing dill file
[        ]     --from-dill                                Read existing dill file instead of compiling from sources
[        ]     --output-dill                              Output path for the generated dill
[        ]     --output-incremental-dill                  Output path for the generated incremental dill
[        ]     --depfile                                  Path to output Ninja depfile. Only used in batch mode.
[        ]     --packages                                 .packages file to use for compilation
[        ]     --target                                   Target model that determines what core libraries are available
[        ]                                                [vm (default), flutter, flutter_runner, dart_runner, dartdevc]
[        ]     --[no-]verbose                             Enables verbose output from the compiler.
[        ] -D, --define                                   The values for the environment constants (e.g. -Dkey=value).
[        ]     --[no-]embed-source-text                   Includes sources into generated dill file. Having sources allows to effectively use observatory to debug produced application, produces better stack traces on exceptions.
[        ]                                                (defaults to on)
[        ]     --[no-]track-widget-creation               Run a kernel transformer to track creation locations for widgets.
[        ]     --delete-tostring-package-uri=<dart:ui>    Replaces implementations of `toString` with `super.toString()` for specified package
[        ]     --[no-]enable-asserts                      Whether asserts will be enabled.
[        ]     --[no-]sound-null-safety                   Respect the nullability of types at runtime.
[        ]     --[no-]split-output-by-packages            Split resulting kernel file into multiple files (one per package).
[        ]     --component-name                           Name of the Fuchsia component
[        ]     --data-dir                                 Name of the subdirectory of //data for output files
[        ]     --far-manifest                             Path to output Fuchsia package manifest
[        ]     --libraries-spec                           A path or uri to the libraries specification JSON file
[        ]     --[no-]debugger-module-names               Use debugger-friendly modules names
[        ]                                                (defaults to on)
[        ]     --[no-]experimental-emit-debug-metadata    Emit module and library metadata for the debugger
[        ]     --[no-]emit-debug-symbols                  Emit debug symbols for the debugger
[        ]     --dartdevc-module-format                   The module format to use on for the dartdevc compiler
[        ]                                                (defaults to "amd")
[        ]     --[no-]flutter-widget-cache                Enable the widget cache to track changes to Widget subtypes
[        ]     --[no-]print-incremental-dependencies      Print list of sources added and removed from compilation
[        ]                                                (defaults to on)
[   +1 ms] the Dart compiler exited unexpectedly.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:817:13)
           #2      _rootRun (dart:async/zone.dart:1383:47)
           #3      _CustomZone.run (dart:async/zone.dart:1293:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:154:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1383:47)
           #14     _CustomZone.run (dart:async/zone.dart:1293:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1383:47)
           #26     _CustomZone.run (dart:async/zone.dart:1293:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:630:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2331:21)
           #35     _rootRunUnary (dart:async/zone.dart:1407:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:648:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:596:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1856:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)


[   +2 ms] the Dart compiler exited unexpectedly.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:817:13)
           #2      _rootRun (dart:async/zone.dart:1383:47)
           #3      _CustomZone.run (dart:async/zone.dart:1293:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:154:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1383:47)
           #14     _CustomZone.run (dart:async/zone.dart:1293:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1383:47)
           #26     _CustomZone.run (dart:async/zone.dart:1293:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:630:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2331:21)
           #35     _rootRunUnary (dart:async/zone.dart:1407:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:648:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:596:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1856:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)


[  +81 ms] ensureAnalyticsSent: 82ms
[        ] Running shutdown hooks
[        ] ensureAnalyticsSent: 81ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

## Doctor

```
[✓] Flutter (Channel stable, 3.3.8, on Ubuntu 22.04.1 LTS 5.15.68.1-microsoft-standard-WSL2, locale C.UTF-8)
    • Flutter version 3.3.8 on channel stable at /home/clarkeaa/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (7 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2
```

**Comment by gaaclarke** [comment]
I commented out the verbosity flags from the compile.dart file and I get a different error.  It seems like the tool isn't using the correct version of dart when using a local engine?

```
[   +2 ms] ninja: Entering directory `build/linux/x64/debug'
[ +106 ms] lib/main.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.15.
[        ] import 'package:flutter/material.dart';
[        ] ^
[   +3 ms] lib/main.dart:12:16: Error: 'super' can't be used as an identifier because it's a keyword.
[        ] Try renaming this to be an identifier that isn't a keyword.
[        ]   const MyApp({super.key});
[        ]                ^^^^^
[        ] lib/main.dart:12:21: Error: Expected '}' before this.
[        ]   const MyApp({super.key});
[        ]                     ^
[        ] ../../../flutter/packages/flutter/lib/material.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.15.
[        ] // Copyright 2014 The Flutter Authors. All rights reserved.
[        ] ^
```

**Comment by gaaclarke** [comment]
I was accidentally not on a compatible commit for the engine.  It would be nice if we had some sort of handshake so we had a better error message for this.
