### ISSUE TITLE
flutter doctor - exception at 'flutter_tools.dart:16'

### ISSUE THREAD

**Issue by titanseason** [flutter/flutter#11534]
## Steps to Reproduce
I just cloned flutter sdk, and execute `flutter doctor`, an exception happened, and when I execute `flutter create myapp`, the same crash happened.
Is this at the reason of Great Fire Wall in China?

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

SocketException: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = android.googlesource.com, port = 60859

```
#0      fetchUrl (package:flutter_tools/src/base/net.dart:18)
<asynchronous suspension>
#1      _downloadFile (package:flutter_tools/src/cache.dart:400)
<asynchronous suspension>
#2      _downloadZippedTarball.<anonymous closure> (package:flutter_tools/src/cache.dart:416)
<asynchronous suspension>
#3      _withTemporaryFile (package:flutter_tools/src/cache.dart:428)
<asynchronous suspension>
#4      _downloadZippedTarball (package:flutter_tools/src/cache.dart:415)
#5      GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:389)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:223)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:196)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:206)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#16     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#25     main (file:///D:/Android/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 6.1.7601], locale zh-CN, channel alpha)
    • Flutter at D:\Android\flutter
    • Framework revision bbcfb8d51a (6 days ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at D:\Android\SDK
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[✓] Connected devices
    • Nexus 6 • ZX1G22GVLM • android-arm • Android 7.0 (API 24)

```

## Flutter Doctor

D:\Android\flutter\bin>flutter doctor
Downloading Gradle Wrapper...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: ä
¿¡å·ç¯è¶…æ—¶æ—¶é—´å·²åˆ°
, errno = 121, address = clients2.google.com, port = 60972
Crash report written to D:\Android\flutter\bin\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by titanseason** [comment]
It seems that something error occurred while downloading gradle wrapper

**Comment by lyrachord** [comment]
hi here: #11546  flutter doctor failed to download engine, tools and other packages
1, Yes, there are sites not stable to access from China, and some hosts' ip can be changed in etc/hosts
2, some flutter tool logics polished

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/11681
