### ISSUE TITLE
flutter doctor failed to download engine, tools and other packages 

### ISSUE THREAD

**Issue by lyrachord** [flutter/flutter#11546]
## Steps to Reproduce
flutter doctor

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

SocketException: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = storage.googleapis.com, port = 50537

```
#0      fetchUrl (package:flutter_tools/src/base/net.dart:18)
<asynchronous suspension>
#1      _downloadFile (package:flutter_tools/src/cache.dart:400)
<asynchronous suspension>
#2      _downloadZipArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:407)
<asynchronous suspension>
#3      _withTemporaryFile (package:flutter_tools/src/cache.dart:428)
<asynchronous suspension>
#4      _downloadZipArchive (package:flutter_tools/src/cache.dart:406)
#5      FlutterEngine._downloadItem (package:flutter_tools/src/cache.dart:373)
#6      FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:348)
<asynchronous suspension>
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:223)
<asynchronous suspension>
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:196)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:206)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     new Future.sync (dart:async/future.dart:222)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#17     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1467)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#26     main (file:///D:/dart/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[-] Flutter (on Microsoft Windows [Version 10.0.15063], locale zh-CN, channel master)
    • Flutter at D:\dart\flutter
    • Framework revision 4da5e9b249 (3 days ago), 2017-08-04 17:44:20 -0700
    • Engine revision 73afec4081
    • Tools Dart version 1.25.0-dev.7.0
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at D:\android\SDK
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = D:\android\SDK
    • Java binary at: C:\work\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at C:\work\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[✓] Connected devices
    • None

```

**Comment by lyrachord** [comment]
this point: address = storage.googleapis.com, port = 50537
The downloading is not always be failed.
port?

**Comment by lyrachord** [comment]
jump from #11051 
https://github.com/flutter/flutter/issues/11051#issuecomment-320694455

**Comment by Hixie** [comment]
Related to https://github.com/flutter/flutter/issues/1800

Basically we need to be much better about handling network failures when dealing with `pub` and other upstream dependencies.

This also affects our build (our main source of flakiness is this kind of thing).

**Comment by lyrachord** [comment]
pull flutter, doctor 
it works
There is a sample exception

> Download failed: https://storage.googleapis.com/flutter_infra/flutter/f0d440bec3ed79f01890e956b07b6e8e6182db62/android-x86/artifacts.zip
  HttpException: Connection closed while receiving data, uri = https://storage.googleapis.com/flutter_infra/flutter/f0d440bec3ed79f01890e956b07b6e8e6182db62/android-x86/artifacts.zip

there is a nano bug, after completed flutter ends  with a message retry...
