### ISSUE TITLE
linux web engine: timeout downloading firefox

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#115404]
Currently the engine tree is red on failures to download firefox.  The first pr where it appears doesn't appear to make any change in the downloading of firefox.

## example failure 
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/11356/overview

## log
```
Dart file test/canvaskit/canvaskit_api_test.dart compiled to JavaScript: build/canvaskit_tests/test/canvaskit/canvaskit_api_test.dart.browser_test.dart.js
Compiled 14,191,569 characters Dart to 2,451,737 characters JavaScript in 19.7 seconds using 441.625 MB of memory
Dart file test/canvaskit/canvaskit_api_tt_on_test.dart compiled to JavaScript: build/canvaskit_tests/test/canvaskit/canvaskit_api_tt_on_test.dart.browser_test.dart.js
Built 167 tests in 572 seconds using 8 concurrent compile processes.
Unhandled exception:
Connection timed out
#0      IOClient.send (package:http/src/io_client.dart:88:7)
<asynchronous suspension>
#1      FirefoxInstaller._download (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/firefox_installer.dart:154:39)
<asynchronous suspension>
#2      FirefoxInstaller.install (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/firefox_installer.dart:136:36)
<asynchronous suspension>
#3      getOrInstallFirefox (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/firefox_installer.dart:57:7)
<asynchronous suspension>
#4      FirefoxEnvironment.prepare (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/firefox.dart:33:21)
<asynchronous suspension>
#5      RunTestsStep.run (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/steps/run_tests_step.dart:68:5)
<asynchronous suspension>
#6      Pipeline.run (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/pipeline.dart:128:9)
<asynchronous suspension>
#7      TestCommand.run (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/test_runner.dart:153:7)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      main (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/felt.dart:45:26)
<asynchronous suspension>
```

## First pr where it appears
https://github.com/flutter/engine/pull/37522

**Comment by godofredoc** [comment]
\cc @eyebrowsoffire @yjbanov

**Comment by hterkelsen** [comment]
We should download Firefox and upload it to CIPD like the other browsers instead of relying on Mozilla CDN

**Comment by hterkelsen** [comment]
This has been fixed with the above PRs. We are now downloading Firefox from CIPD
