### ISSUE TITLE
Flutter crash report; 

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#11549]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'D:\AndroidDev\flutter\bin\cache\artifacts\engine' (OS Error: The directory is not empty.
, errno = 145)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:162)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:411)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:68)
#3      CachedArtifact.update (package:flutter_tools/src/cache.dart:221)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:196)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:206)
<asynchronous suspension>
#6      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#10     new Future.sync (dart:async/future.dart:222)
#11     CommandRunner.run (package:args/command_runner.dart:109)
#12     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#13     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#14     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#15     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1467)
#19     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#20     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#22     main (file:///D:/AndroidDev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[-] Flutter (on Microsoft Windows [Version 6.3.9600], locale en-US, channel master)
    вЂў Flutter at D:\AndroidDev\flutter
    вЂў Framework revision 02c214479f (14 hours ago), 2017-08-07 16:55:37 -0700
    вЂў Engine revision ff50334587
    вЂў Tools Dart version 1.25.0-dev.7.0
    вњ— Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[вњ“] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    вЂў Android SDK at D:\AndroidSDK
    вЂў Platform android-26, build-tools 26.0.1
    вЂў ANDROID_HOME = D:\AndroidSDK
    вЂў Java binary at: C:\Program Files\Java\jdk1.8.0_131\bin\java
    вЂў Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

[-] Android Studio (version 2.1)
    вЂў Android Studio at C:\Program Files\Android\Android Studio
    вњ— Unable to find bundled Java version.
    вЂў Try updating or re-installing Android Studio.

[вњ“] IntelliJ IDEA Community Edition (version 2017.2)
    вЂў Flutter plugin version 16.0
    вЂў Dart plugin version 172.3317.48


```

**Comment by eseidelGoogle** [comment]
This doesn't surprise me.  This sounds similar to the dart-sdk upgrade dance we have to do.  Likely we need to move the cache folder out of the way before updating. Thoughts @goderbauer @tvolkert @bkonyi

**Comment by goderbauer** [comment]
Since you filed https://github.com/flutter/flutter/issues/11550 it looks like you got past this crash. What did you do?

**Comment by JFixby** [comment]
I reinstalled Flutter. No I can't reproduce it.

**Comment by fralways** [comment]
Im getting similar crash each time after I restart my computer:
Error is: ```FileSystemException: FileSystemException: Deletion failed, path = 'xxxprojectdirxxx\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: The directory is not empty.
, errno = 145)```
Fix is to go to that path, rename/delete flutter_assets folder and then it builds.
 ## flutter doctor

```
[✓] Flutter (Channel master, v0.2.4-pre.64, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
    • Flutter version 0.2.4-pre.64 at C:\Users\Filip\Documents\credeo\Flutter\flutter
    • Framework revision 619ebd67a9 (2 days ago), 2018-03-20 00:26:10 -0700
    • Engine revision c3ab0c9143
    • Dart version 2.0.0-dev.39.0.flutter-f1ebe2bd5c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Filip\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by tvolkert** [comment]
@fralways can you submit a new issue with the crash after rebooting, and run with:

```
flutter --verbose <command>
```

I'm interested in the stack trace showing where that happens.

Please cc me on the issue once you file it.  Thanks!
