### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by yu893145181** [flutter/flutter#115415]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:47:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:486:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:93:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:156:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:188:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19044.2251], locale zh-CN)
    • Flutter version 2.0.0 at D:\soft\flutter_sdk\flutter_windows_2.0.0-stable\flutter
    • Framework revision 60bd88df91 (1 year, 8 months ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at E:/soft/AsSdk
    • Platform android-32, build-tools 33.0.0
    • ANDROID_HOME = E:/soft/AsSdk
    • Java binary at: D:\yufs\As\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at D:\yufs\As
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • MI 8 (mobile) • c6bffdb3 • android-arm64  • Android 10 (API 29)
    • Chrome (web)  • chrome   • web-javascript • Google Chrome 106.0.5249.103
    • Edge (web)    • edge     • web-javascript • Microsoft Edge 107.0.1418.42

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 60bd88df915880d23877bfc1602e8ddcf4c4dd2a

**Comment by danagbemava-nc** [comment]
Hi @yu893145181, this issue was previously reported and was tracked in https://github.com/flutter/flutter/issues/95916.
It has since been fixed and the fix is available on the latest versions of flutter. 

I'll be closing this issue since it has already been fixed on the latest versions of flutter.
If you still experience this issue on the master channel or later versions of flutter, kindly file a new issue.

Thank you!
