### ISSUE TITLE
[tool_crash] ProcessException: 请求的操作需要提升。 Command: "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe", OS error code: 740

### ISSUE THREAD

**Issue by q3920687** [flutter/flutter#115535]
## Command
```
flutter run -d edge
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs

ProcessException: 请求的操作需要提升。
_ProcessException: The requested operation requires elevation._
 Command: "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe", OS error code: 740
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:260:53)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:225:36)
<asynchronous suspension>
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:145:17)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:304:9)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.8, on Microsoft Windows [版本 10.0.22621.819], locale zh-CN)
    • Flutter version 3.3.8 on channel stable at D:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (8 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\AndroidSDK
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (4 available)
    • V1916A (mobile)   • 127.0.0.1:5555 • android-x64    • Android 9 (API 28)
    • V1916A (mobile)   • emulator-5554  • android-x64    • Android 9 (API 28)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [版本 10.0.22621.819]
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 107.0.1418.42
    ! Device b0368da is not authorized.
      You might need to check your device for an authorization dialog.

[!] HTTP Host Availability
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到

    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到


! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 52b3dc25f6471c27b2144594abb11c741cb88f57

**Comment by exaby73** [comment]
Hello @q3920687. Are you running this from a Windows Standard account or an Admin account?
