### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by vadimlukutin** [flutter/flutter#115642]
## Command
```
flutter test --update-goldens --tags=golden
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: Permission denied, errno = 13
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1041:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:866:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:753:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:326:58)
<asynchronous suspension>
#8      TestCommand._buildTestAsset (package:flutter_tools/src/commands/test.dart:474:23)
<asynchronous suspension>
#9      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:318:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.7, on Fedora Linux 37 (Workstation Edition) 6.0.8-300.fc37.x86_64, locale en_US.UTF-8)
    • Flutter version 3.3.7 on channel stable at /home/vadimlukutin/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (2 weeks ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /home/vadimlukutin/Android/Sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: /var/lib/snapd/snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /var/lib/snapd/snap/android-studio/125/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • 2107113SG (mobile) • 86835209 • android-arm64 • Android 12 (API 31)
    • Linux (desktop)    • linux    • linux-x64     • Fedora Linux 37 (Workstation Edition) 6.0.8-300.fc37.x86_64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e99c9c7cd9f6c0b2f8ae6e3ebfd585239f5568f4
### Plugins
flutter_secure_storage-6.0.0
flutter_secure_storage_linux-1.1.1
flutter_secure_storage_macos-1.1.1
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
path_provider-2.0.11
path_provider_android-2.0.21
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3

**Comment by darshankawar** [comment]
I don't see an exact duplicate issue for it, so labeling it for team's attention.

/cc @christopherfujino

**Comment by christopherfujino** [comment]
Closing as stale
