### ISSUE TITLE
Longpress on TextField throws exception

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#11573]
Longpress on TextField with maxLines set to null, an exception occurs.
If maxLines is a number, no exception.

```
The following NoSuchMethodError was thrown building _TextSelectionHandleOverlay(dirty, state:
_TextSelectionHandleOverlayState#c8639):
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      double./ (dart:core-patch/double.dart:39)
#3      _TextSelectionHandleOverlayState.build (package:flutter/src/widgets/text_selection.dart:512:49)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3624:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3534:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3435:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3514:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3652:22)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3509:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2685:12)
#12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4516:14)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2685:12)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3546:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:3435:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3514:5)
#18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3652:22)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3509:5)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2685:12)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3546:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:3435:5)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3514:5)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3652:22)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3509:5)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2685:12)
#29     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4308:32)
#30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4631:17)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2674:15)
#32     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2674:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3546:16)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:3435:5)
#36     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2260:33)
#37     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:503:20)
#38     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189:5)
#39     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:695:15)
#40     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:643:9)
#41     _invoke (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:86)
#42     _drawFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:75)
```

Simple reproduction:

```dart
void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      body: new Container(
        child: new TextField(maxLines: null),
        constraints: const BoxConstraints.expand(),
      ),
    ),
  ));
}
```

Flutter doctor:

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale ja-JP, channel master)
    • Flutter at /Applications/flutter
    • Framework revision 3b76e7e258 (28 hours ago), 2017-08-08 15:46:47 -0700
    • Engine revision f0d440bec3
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.1)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34
```

**Comment by zoechi** [comment]
looks like #12046

https://github.com/flutter/flutter/issues/12046#issuecomment-388721323

> maxLines: null works if you specify keyboardType: TextInputType.text

**Comment by jonahwilliams** [comment]
Closed via https://github.com/flutter/flutter/pull/12833
