### ISSUE TITLE
[WEB] Failed to compile application for the Web in release mode

### ISSUE THREAD

**Issue by sahmadreza** [flutter/flutter#115712]
## Steps to Reproduce

1. flutter create bug
2. cd bug
3. flutter run -d chrome --release --verbose --dart-flags=verbose_gc

**Expected results:** 
I expected the flutter counter project to compile successfully. (Web release)

**Actual results:** 
```
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is
deprecated, please use 'dart compile js' instead.
```
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>
 
```properties
>>> flutter run -d chrome --release --verbose --dart-flags=verbose_gc

[   +8 ms] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] x86_64
[        ] executing: [/home/ahmadreza/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d8a091ce984915da5fb1bdef33ffa123d036594e
[        ] executing: [/home/ahmadreza/snap/flutter/common/flutter/] git tag --points-at
d8a091ce984915da5fb1bdef33ffa123d036594e
[  +10 ms] Exit code 0 from: git tag --points-at d8a091ce984915da5fb1bdef33ffa123d036594e
[   +1 ms] executing: [/home/ahmadreza/snap/flutter/common/flutter/] git describe --match *.*.*
--long --tags d8a091ce984915da5fb1bdef33ffa123d036594e
[  +16 ms] Exit code 0 from: git describe --match *.*.* --long --tags
d8a091ce984915da5fb1bdef33ffa123d036594e
[        ] 3.6.0-5.0.pre-24-gd8a091ce98
[   +7 ms] executing: [/home/ahmadreza/snap/flutter/common/flutter/] git rev-parse --abbrev-ref
--symbolic @{upstream}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/master
[        ] executing: [/home/ahmadreza/snap/flutter/common/flutter/] git ls-remote --get-url
origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +10 ms] executing: [/home/ahmadreza/snap/flutter/common/flutter/] git rev-parse --abbrev-ref
HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +30 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +40 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +62 ms] Skipping pub get: version match.
[ +119 ms] Generating
/home/ahmadreza/StudioProjects/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPlugin
Registrant.java
[  +83 ms] Launching lib/main.dart on Chrome in release mode...
[  +64 ms] generated_plugin_registrant.dart not found. Skipping.
[   +1 ms] Compiling lib/main.dart for the Web...
[   +4 ms] Initializing file store
[   +1 ms] Done initializing file store
[  +16 ms] Skipping target: web_entrypoint
[   +1 ms] Skipping target: gen_localizations
[   +1 ms] Skipping target: web_static_assets
[        ] dart2js: Starting due to {}
[+9936 ms] Persisting file store
[   +2 ms] Done persisting file store
[   +2 ms] Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is
deprecated,
           please use 'dart compile js' instead.
           The compiler crashed: WebSocketException: Connection to
           'http://127.0.0.1:38929/IyxHSwW3PMA=/ws#' was not upgraded to websocket
           #0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
           #1      WebSocket.connect (dart:_http/websocket.dart:320:22)
           #2      vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
           #3      _currentHeapCapacity (package:compiler/src/common/ram_usage.dart:27:41)
           <asynchronous suspension>
           #4      currentHeapCapacityInMb (package:compiler/src/common/ram_usage.dart:38:20)
           <asynchronous suspension>
           #5      compile.compilationDone (package:compiler/src/dart2js.dart:1068:12)
           <asynchronous suspension>
           #6      main (package:compiler/src/dart2js.dart:1425:3)
           <asynchronous suspension>
           
           
           #0      Dart2JSTarget.build
           (package:flutter_tools/src/build_system/targets/web.dart:216:7)
           <asynchronous suspension>
           #1      _BuildInstance._invokeInternal
           (package:flutter_tools/src/build_system/build_system.dart:847:9)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
           <asynchronous suspension>
           #3      _BuildInstance.invokeTarget
           (package:flutter_tools/src/build_system/build_system.dart:785:32)
           <asynchronous suspension>
           #4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
           <asynchronous suspension>
           #5      _BuildInstance.invokeTarget
           (package:flutter_tools/src/build_system/build_system.dart:785:32)
           <asynchronous suspension>
           #6      FlutterBuildSystem.build
           (package:flutter_tools/src/build_system/build_system.dart:614:16)
           <asynchronous suspension>
           #7      buildWeb (package:flutter_tools/src/web/compile.dart:51:32)
           <asynchronous suspension>
           #8      ResidentWebRunner.run.<anonymous closure>
           (package:flutter_tools/src/isolated/resident_web_runner.dart:293:11)
           <asynchronous suspension>
           #9      asyncGuard.<anonymous closure>
           (package:flutter_tools/src/base/async_guard.dart:111:24)
           <asynchronous suspension>


[  +11 ms] Compiling lib/main.dart for the Web... (completed in 10.0s)
[   +3 ms] "flutter run" took 10,376ms.
[   +3 ms] Exception: Failed to compile application for the Web.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:97:5)
           <asynchronous suspension>
           #2      ResidentWebRunner.run.<anonymous closure>
           (package:flutter_tools/src/isolated/resident_web_runner.dart:293:11)
           <asynchronous suspension>
           #3      asyncGuard.<anonymous closure>
(package:flutter_tools/src/base/async_guard.dart:111:24)
           <asynchronous suspension>
           
           
[ +199 ms] ensureAnalyticsSent: 198ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1

```
</details>

**Information:** 

<details>
  <summary>flutter doctor -v</summary>

```properties
>>> flutter doctor -v
✓] Flutter (Channel master, 3.6.0-6.0.pre.24, on Ubuntu 22.04.1 LTS 5.15.0-53-generic, locale
    en_US.UTF-8)
    • Flutter version 3.6.0-6.0.pre.24 on channel master at
      /home/ahmadreza/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d8a091ce98 (2 hours ago), 2022-11-19 15:36:23 -0500
    • Engine revision e9bdd5ef51
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /home/ahmadreza/Android/Sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0-rc4
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.52.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is FE80::/64, 127.0.0.1/8, ::1, FD00::/8, 192.168.0.0/16, 10.0.0.0/8, localhost
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-53-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.110

```
</details>

<details>
  <summary>System information</summary>

```properties
>>> uname -r
5.15.0-53-generic
>>> uname -m
x86_64
>>> uname -v
#59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022
```

```properties
>>> df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.6G  2.6M  1.6G   1% /run
/dev/nvme0n1p8   98G   89G  4.2G  96% /
tmpfs           7.8G  125M  7.7G   2% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
/dev/nvme0n1p1   96M   57M   40M  59% /boot/efi
tmpfs           1.6G  7.4M  1.6G   1% /run/user/1000
```

```properties
>>> ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

```properties
>>> htop
```
![image](https://user-images.githubusercontent.com/56578605/202874580-59957da4-ed94-49bf-b63e-15877bb45cc6.png)

</details>

**Comment by huycozy** [comment]
Hi @sahmadreza, I can not reproduce this issue from my end with the same Ubuntu version. Does this issue happen anytime running the project in release mode? Is it fine with debug mode? 

Also, I see your proxy configuration from your `flutter doctor -v` output. Can you retry running the project without using proxy?

>[   +2 ms] Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is
deprecated,
           please use 'dart compile js' instead.
           The compiler crashed: WebSocketException: Connection to
           'http://127.0.0.1:38929/IyxHSwW3PMA=/ws#' was not upgraded to websocket

This issue seems to be similar to issue #114346, but not exactly with above exception.

**Comment by sahmadreza** [comment]
> Also, I see your proxy configuration from your `flutter doctor -v` output. Can you retry running the project without using proxy?

Hi @huycozy, thank you for your high accuracy. I turned off the proxy and the problem was solved.
