### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by longnh208** [flutter/flutter#115747]
## Command
```
flutter --quiet assemble --no-version-check --depfile F:\LongNH\Long\TimeBird\timebird-bet\build\app\intermediates\flutter\debug/flutter_build.d --output F:\LongNH\Long\TimeBird\timebird-bet\build\app\intermediates\flutter\debug -dTargetFile=F:\LongNH\Long\TimeBird\timebird-bet\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:271:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:270:5)
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:634:8)
<asynchronous suspension>
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:316:32)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    • Flutter version 3.3.2 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (10 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at D:\sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = D:\Android\Sdk
    • ANDROID_SDK_ROOT = D:\Android\Sdk
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Connected device (3 available)
    • Redmi 8A (mobile) • 1348d3e60506 • android-arm    • Android 10 (API 29)
    • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [Version 10.0.17134.648]
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 107.0.5304.107

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e3c29ec00c9c825c891d75054c63fcc46454dca1
### Plugins
flutter_facebook_auth-4.4.1+1
flutter_facebook_auth_web-3.2.0
flutter_keyboard_visibility-5.3.0
flutter_keyboard_visibility_web-2.0.0
flutter_native_splash-2.2.9
flutter_plugin_android_lifecycle-2.0.7
google_sign_in-5.4.2
google_sign_in_android-6.1.1
google_sign_in_ios-5.5.0
google_sign_in_web-0.10.2
image_picker-0.8.6
image_picker_android-0.8.5+3
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+1
path_provider-2.0.11
path_provider_android-2.0.21
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
qr_code_scanner-1.0.1
qr_code_tools-afec713bd329bbc588de7aac2ade392def0b7872
share_plus-4.4.0
share_plus_linux-3.0.0
share_plus_macos-3.0.1
share_plus_web-3.0.1
share_plus_windows-3.0.1
shared_preferences-2.0.15
shared_preferences_android-2.0.13
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sign_in_with_apple-4.2.0
sign_in_with_apple_web-1.0.1
sqflite-2.0.3+1
url_launcher-6.1.6
url_launcher_android-6.0.19
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
webview_flutter-3.0.4
webview_flutter_android-2.10.3
webview_flutter_wkwebview-2.9.5

**Comment by exaby73** [comment]
Hi @longnh208 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/91559
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.

Thank you
