### ISSUE TITLE
Hero widget crashes when opening a deep link

### ISSUE THREAD

**Issue by isaaclyman** [flutter/flutter#115770]
## Steps to Reproduce

I am posting this bug because the Flutter compiler told me to. I don't have an MCVE ready right now, sorry. It's a big application.

The bug reliably happens when I launch a deep link from the command line that points to a different top-level route than the app is currently open to. I use the following command:

`xcrun simctl openurl booted customscheme://myapp.url/deep/link`

The error appears to be with the Hero widget. I only have one Hero widget in my app. The `BottomNavigationBar` is wrapped in a `Hero` widget because (AFAIK) this is the only way to keep it in place as I navigate between top-level routes.

**Expected results:** Deep link opens.

**Actual results:** Application crashes with the error below.

<details>
  <summary>Logs</summary>

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 651 pos 12: '() {
package:flutter/…/widgets/heroes.dart:651
      final Animation<double> initial = initialManifest.animation;
      assert(initial != null);
      final HeroFlightDirection type = initialManifest.type;
      assert(type != null);
      switch (type) {
        case HeroFlightDirection.pop:
          return initial.value == 1.0 && initialManifest.isUserGestureTransition
              // During user gesture transitions, the animation controller isn't
              // driving the reverse transition, but should still be in a previously
              // completed stage with the initial value at 1.0.
              ? initial.status == AnimationStatus.completed
              : initial.status == AnimationStatus.reverse;
        case HeroFlightDirection.push:
          return initial.value == 0.0 && initial.status == AnimationStatus.forward;
      }
    }()': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

When the exception was thrown, this was the stack
#2      _HeroFlight.start
package:flutter/…/widgets/heroes.dart:651
#3      HeroController._startHeroTransition
package:flutter/…/widgets/heroes.dart:978
#4      HeroController._maybeStartHeroTransition.<anonymous closure>
package:flutter/…/widgets/heroes.dart:899
#5      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#6      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1113
#7      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#8      _invoke (dart:ui/hooks.dart:148:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#10     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing ux...                                                         
No issues found! (ran in 2.5s)
```

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
    • Flutter version 3.3.3 on channel stable at /Users/isaaclyman/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (8 weeks ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/isaaclyman/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] VS Code (version 1.71.2)
    • VS Code at /Users/isaaclyman/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 04BFBC75-1CD2-4CF9-9F54-C93E34164838 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by isaaclyman** [comment]
I'm sorry, I really don't have time for that. Maybe in a few months.
