### ISSUE TITLE
[tool_crash] _CastError: (#0      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:497:20))

### ISSUE THREAD

**Issue by rishabhmishra208** [flutter/flutter#115834]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:497:20))
```
#0      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:497:20)
#1      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:565:5)
<asynchronous suspension>
#2      HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:754:16)
<asynchronous suspension>
#3      HotRunner.restart (package:flutter_tools/src/run_hot.dart:694:38)
<asynchronous suspension>
#4      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1699:40)
<asynchronous suspension>
#5      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1739:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.19045.2251], locale en-IN)
    • Flutter version 3.3.8 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (13 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\gigabyte\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at C:\Users\gigabyte\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • ONEPLUS A6000 (mobile) • 192.168.0.106:5555 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)      • windows            • windows-x64    • Microsoft Windows [Version 10.0.19045.2251]
    • Chrome (web)           • chrome             • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)             • edge               • web-javascript • Microsoft Edge 107.0.1418.52

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
flutter_barcode_scanner-2.0.0
flutter_inappwebview-5.7.1
flutter_plugin_android_lifecycle-2.0.7
flutter_secure_storage-6.0.0
flutter_secure_storage_linux-1.1.1
flutter_secure_storage_macos-1.1.1
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
fluttertoast-8.1.1
image_picker-0.8.6
image_picker_android-0.8.5+3
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+1
path_provider-2.0.11
path_provider_android-2.0.21
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
share_plus-6.3.0
sqflite-2.2.0+3
url_launcher_linux-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1

**Comment by danagbemava-nc** [comment]
Hi @rishabhmishra208, 
This issue has already been fixed and merged into the master branch: https://github.com/flutter/flutter/pull/108771, so I suggest you switch to the latest master to see the change. It may not be in stable version yet.

Since this is fixed already, I will close it. 

Thank you
