### ISSUE TITLE
[google_sign_in] Login fails with Java null pointer exception when Android device has custom date/time set

### ISSUE THREAD

**Issue by nicoroy2561** [flutter/flutter#115818]
The users of my app have been reporting inability to sign in with google on certain devices, and I later received the following error reports:
<details>

```
Reported by HUAWEI Y6 2019, running Android 9

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'io.flutter.plugin.common.MethodChannel$Result io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$PendingOperation.result' on a null object reference
       at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.finishWithError(GoogleSignInPlugin.java:558)
       at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.onSignInResult(GoogleSignInPlugin.java:521)
       at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.access$000(GoogleSignInPlugin.java:263)
       at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$1.onComplete(GoogleSignInPlugin.java:415)
       at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

```
Reported by HGalaxy Tab A7, running Android 12

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'io.flutter.plugin.common.MethodChannel$Result io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$PendingOperation.result' on a null object reference in method 'void io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.finishWithError(java.lang.String, java.lang.String)'
       at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.finishWithError(GoogleSignInPlugin.java:558)
       at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.onSignInResult(GoogleSignInPlugin.java:521)
       at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.access$000(GoogleSignInPlugin.java:263)
       at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$1.onComplete(GoogleSignInPlugin.java:415)
       at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

</details>
According to the reports, users tap on the "Sign in with Google" button but nothing appears.

My app's current version was compiled using Flutter 3.3.6, using
```
google_sign_in: ^5.4.2
```

Flutter doctor output:
<details>

```
[✓] Flutter (Channel stable, 3.3.8, on Ubuntu 22.04 LTS 5.17.0-amd64, locale en_US.UTF-8)
    • Flutter version 3.3.8 on channel stable at /home/user/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (13 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-33, build-tools 33.0.0-rc3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.52.0

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.52.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by nicoroy2561** [comment]
EDIT: the user has reported that this happens when the device has custom date / time. Apparently, syncing the date/time on their device allowed them to sign in properly.

I just tried myself, and I can attest that sign in with google fails when the device has a custom date / time.

**Comment by huycozy** [comment]
Hi @nicoroy2561 
Is this issue reproducible locally with sample code at https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in/example? If so, can you please share the output of `flutter run -v`?

**Comment by nicoroy2561** [comment]
@huycozy the default app doesn't work on my device. I just tried both with correct and wrong time&date, the same exception is thrown.

relevant output of flutter run -v:
```
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Mi 9T is available at: http://127.0.0.1:33699/xHqtRNof_5w=/
[ +684 ms] The Flutter DevTools debugger and profiler on Mi 9T is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:33699/xHqtRNof_5w=/
[  +24 ms] E/LB      (21477): fail to open file: No such file or directory
[  +10 ms] I/lesigninexampl(21477): ProcessProfilingInfo new_methods=1590 is saved saved_to_disk=1 resolve_classes_delay=8000
[+5966 ms] I/Timeline(21477): Timeline: Activity_launch_request time:191074156
[  +52 ms] I/Timeline(21477): Timeline: Activity_launch_request time:191074209
[+2100 ms] I/flutter (21477): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
[+1857 ms] I/Timeline(21477): Timeline: Activity_launch_request time:191078164
[  +34 ms] I/Timeline(21477): Timeline: Activity_launch_request time:191078201
[+1721 ms] I/flutter (21477): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
[+1914 ms] Application finished.
```

Full output was too big for Github and even Pastebin.
hosted it here [https://controlc.com/11a10cf9](https://controlc.com/11a10cf9)

**Comment by huycozy** [comment]
@nicoroy2561 thanks for providing more info. Based on the log at https://github.com/flutter/flutter/issues/115818#issuecomment-1323711275, I see there are two known issues #33393, #75224. You may follow up on them for further updates. 

With regard to the issue from OP at https://github.com/flutter/flutter/issues/115818#issue-1459439136, I also see there's an open issue addressing the case you described #74308.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment about this case and react an upvote to the original comment will help to raise the issue. Thank you!

**Comment by nicoroy2561** [comment]
This doesn't address the issue my clients are facing in our live, production app.

I don't think an issue should be closed simply because the example app for google_sign_in is broken, and therefore it can't be used to replicate any other issue the package might be having.
If anything fixing the example app should be priority number 1, and all issues with the package should be left open until that is done and the example app can be used to check whether the other issues are reproducible with it.
