### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by ravimandal06** [flutter/flutter#115838]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:427:7)
#2      _File._deleteSync (dart:io/file_impl.dart:295:50)
#3      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:427:7)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:82:12)
#6      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:352:33)
#7      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#8      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:336:5)
#9      ResidentRunner.cacheInitialDillCompilation (package:flutter_tools/src/resident_runner.dart:1320:18)
#10     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:290:11)
<asynchronous suspension>
#11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.1.0-0.0.pre.2270, on Microsoft Windows [Version 10.0.22000.1219], locale en-IN)
    [32m•[39m Flutter version 3.1.0-0.0.pre.2270 on channel master at C:\Users\91707\fvm\default
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 5fcd9c255e (3 months ago), 2022-08-14 08:39:21 -0700
    [32m•[39m Engine revision f49a617535
    [32m•[39m Dart version 2.19.0 (build 2.19.0-96.0.dev)
    [32m•[39m DevTools version 2.16.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    [32m•[39m Android SDK at C:\Users\91707\AppData\Local\Android\Sdk
    [32m•[39m Platform android-33, build-tools 33.0.0-rc2
    [32m•[39m ANDROID_HOME = C:\Users\91707\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.9.4)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.9.31205.134
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.73.1)
    [32m•[39m VS Code at C:\Users\91707\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.52.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.107
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.56

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 5fcd9c255eb3d0e9672d5467cdaa45d354388bf7
### Plugins
cloud_firestore_web-3.1.0
firebase_auth-4.1.3
firebase_auth_web-5.1.3
firebase_core-2.3.0
firebase_core_web-2.0.1

**Comment by danagbemava-nc** [comment]
Hi @ravimandal06, can you upgrade to the latest version of `master` to see if you still experience this issue? 

If you do, please provide the updated output of `flutter doctor -v`

Thank you

**Comment by ravimandal06** [comment]
thank you @danagbemava-nc  , issues solved
