### ISSUE TITLE
Ballistic simulations may be created too frequently

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11599]
Make a normal fling gesture. 
~50% of the time, many goBallistic calls are triggered when I would have expected just one. 

In this example, it took 78ms cumulative recreating the simulations and causes frame drops. 
![cw5hukq7xsp](https://user-images.githubusercontent.com/156888/29236274-6aabf178-7ebd-11e7-88e3-7a001e3a2653.png)

Call stack
```
#0      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:150:16)
#1      BallisticScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:399:14)
#2      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:441:14)
#3      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:110:29)
#4      ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:411:7)
#5      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:827:20)
#6      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1767:7)
#7      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1056:18)
#8      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:251:19)
#9      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:504:22)
#10     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189:5)
#11     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:695:15)
#12     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:643:9)
#13     _invoke (file:///Users/xster/development/flutter/bin/cache/pkg/sky_engine/lib/ui/hooks.dart:86)
#14     _drawFrame (file:///Users/xster/development/flutter/bin/cache/pkg/sky_engine/lib/ui/hooks.dart:75)
```

**Comment by eseidelGoogle** [comment]
Are these used on both iOS and Android or would this cause performance degradations specific to one or the other?

**Comment by Hixie** [comment]
This happens if something within the list is changing dimensions (because we have to recompute the fling in case it would hit the edge). The question is, what is changing dimensions? And can we report it somehow (e.g. on the timeline) to make it obvious...

This will depend on exactly what you're flinging.

**Comment by Hixie** [comment]
The other thing is, goBallistic shouldn't be _that_ expensive, yikes.

**Comment by Hixie** [comment]
Looks from the timeline like maybe this is a long list with many items of various sizes so every time we render a new item, we change our estimate of the total list length, which would trigger this also.

**Comment by Hixie** [comment]
Not sure what to do with this bug. Assuming I'm right about the cause, it's working as intended (modulo taking so long). Should we keep this open specifically to track down why it's so expensive?

**Comment by xster** [comment]
Seems like it's mostly coming from recreating new AnimationControllers. 

Do you think it makes sense to let the position min/max extents be observables passed into the simulation instead of having them immutably baked in on construction? 

Or perhaps create new simulations but keep the old BallisticScrollActivity and AnimationController and just update the simulation? All the math in the simulation's constructor turned out to not be that expensive it seems.

**Comment by Hixie** [comment]
We need to more precisely understand the cost. We could try doing a microbenchmark of just calling `goBallistic` in a tight loop and see what appears on the profile.

**Comment by knopp** [comment]
@xster, @Hixie, this is not just a performance problem. Calling `goBallistic` during scrolling means that the scrolling stops way sooner than it normally would. Also the momentum from multiple flings is not carried over.

Look at example from #24715 or even Licenses screen from flutter gallery. It is pretty much impossible to scroll through all licenses on iPhone. No matter the fling speed or number of flings, scrolling stops on next page.

It seems wrong to me to recreate ballistic simulation on viewport size change then the extent is far from the final position of current simulation.

**Comment by knopp** [comment]
@xster, any chance of looking into this? We have long list of items with different heights and iOS scrolling is downright painful with all momentum lost severely impacting application usability.

**Comment by knopp** [comment]
Somewhat hacky solution that fixes the problem for us

https://github.com/knopp/flutter/commit/4fe1d23ae3e570249d3b13f610139ff332d48192

Not meant as proper fix as it relies on runtime type testing.

**Comment by knopp** [comment]
On second thought, this is not a complete solution. On iOS, when reaching the end (finalX being outside min/max scroll extent), what you would actually need to do is to restart the simulation with original position and velocity, but with new extent. Otherwise the bounce at the end does not feel right.

**Comment by iamarnas** [comment]
OMG this error still remains from 2017. I have also this problem when I expand ExpansionTile in my list. Otherwise work well with single widget in the list.

Here is cleanest och simplest code. If all list items are expanded or collapsed then scrollbar work well but if you expand or ellapse few items then scrollbar indicator shaking.

`final kItemCount = 200;`
  `final int kItemChildCount = 10;`

  `@override
  Widget build(BuildContext context) {`

    return Scaffold(
      appBar: AppBar(
        title: const Text('ExpansionTile'),
      ),
      body: Scrollbar(
        child: ListView.builder(
            itemCount: kItemCount,
            itemBuilder: (BuildContext context, int index) {
              final Widget title = Text('Item $index');
              return ExpansionTile(
                title: title,
                initiallyExpanded: true,
                key: PageStorageKey(index),
                children: List.generate(kItemChildCount, (int childIndex) {
                  return ListTile(title: Text('  Item $index.$childIndex'));
                }).toList(),
              );
            }),
      ),
    );
  `}`

**Comment by nt4f04uNd** [comment]
This is something that I was recently looking at, as it prevents a proper implementation of the Android's scroll logic from this PR https://github.com/flutter/flutter/pull/77497, because each frame the new layout pass happens and the ballistic simulation is recreated, resulting that returned velocity sample is always of the first index, instead of going through all the samples.

FYI @grouma

**Comment by Piinks** [comment]
The PR that closed this is being reverted. Reopening.

**Comment by Piinks** [comment]
For the next crack at solving this, this reproduction should be included as a test case: https://github.com/flutter/flutter/issues/110340

Also, the [latest attempt](https://github.com/flutter/flutter/pull/107735) included creating and passing updated FixedScrollMetrics to createBallisticScrollAnimation. This was a breaking change for customers with their own custom scroll physics that expect a scroll position be provided to createBallisticScrollAnimation, not just ScrollMetrics. Either migrating the customer off of this currently safe assumption will be required, or a different approach that preserves that.

**Comment by knopp** [comment]
Sad to see this reverted :-/ There was however one more issue in the last attempt (fixed by revert): 
Scroll offset correction (`ScrollPosition.correctBy`) was overridden by the `BallisticScrollActivity` animator.

I had a local workaround and was going to report this:
```dart
class CorrectingScrollPositionWithSingleContext
    extends ScrollPositionWithSingleContext {
  CorrectingScrollPositionWithSingleContext({
    required super.physics,
    required super.context,
    super.initialPixels = 0.0,
    super.keepScrollOffset,
    super.oldPosition,
    super.debugLabel,
  });

  @override
  Simulation? updateBallisticAnimation(
      double initVelocity, double initPosition) {
    return super
        .updateBallisticAnimation(initVelocity, initPosition + _correction);
  }

  double _correction = 0;

  @override
  void beginActivity(ScrollActivity? newActivity) {
    _correction = 0;
    super.beginActivity(newActivity);
  }

  @override
  void correctBy(double correction) {
    _correction += correction;
    super.correctBy(correction);
  }
}
```

**Comment by Piinks** [comment]
Another test case for when we revisit this: https://github.com/flutter/flutter/issues/114543
