### ISSUE TITLE
Application working for weeks. Since the 21/11, click on TextFormField make the visual crash on ios.

### ISSUE THREAD

**Issue by Alkabann** [flutter/flutter#115970]
We tried but were never able to reproduce the client error this is why I ask here.

The user is able to fill some TextEditing Widget but, at one point, clicking on any widget is making him crash.

Because we are not able to reproduce it, the only hint we have is this log that we send to ourself when production crash:

```
Null check operator used on a null value

#0 State.setState (package:flutter/src/widgets/framework.dart:1134)
#1 _InstalledEquipementPageState.refresh (package:myApp/Pages/Report/installed_equipment_page.dart:30)
#2 updateRefreshFunction.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:myApp/Pages/Report/installed_equipment_page.dart:275)
#3 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:351)
#4 ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:456)
#5 TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:156)
#6 EditableTextState._value= (package:flutter/src/widgets/editable_text.dart:2353)
#7 EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:2765)
#8 EditableTextState.updateEditingValue (package:flutter/src/widgets/editable_text.dart:2105)
#9 TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1801)
#10 TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1701)
#11 MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:536)
#12 MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529)
#13 _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387)
#14 _invoke2.<anonymous closure> (dart:ui/hooks.dart:189)
#15 _rootRun (dart:async/zone.dart:1391)
#16 _CustomZone.run (dart:async/zone.dart:1293)
#17 _CustomZone.runGuarded (dart:async/zone.dart:1201)
#18 _invoke2 (dart:ui/hooks.dart:188)
#19 _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)
```

The application has been running and working without problems for weeks, but now, since the 21/11, some of our users encounter this problem on ios tablet and iphone. It still working fine on macos.
We ask them to update their devices. It still crash.

**Comment by exaby73** [comment]
Hello @Alkabann. From your stack trace, it looks like an error in your code. If possible, could you share the snippet of code in your application or an edited one that does the same thing?
