### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Illegal character in path: assetsC:\Users\Asus\AndroidStudioProjects\AbalfazlTV\assets\font

### ISSUE THREAD

**Issue by abolfazlirani** [flutter/flutter#116057]
## Command
```
flutter --quiet assemble --no-version-check --depfile C:\Users\Asus\AndroidStudioProjects\AbalfazlTV\build\app\intermediates\flutter\debug/flutter_build.d --output C:\Users\Asus\AndroidStudioProjects\AbalfazlTV\build\app\intermediates\flutter\debug -dTargetFile=C:\Users\Asus\AndroidStudioProjects\AbalfazlTV\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Illegal character in path: assetsC:\Users\Asus\AndroidStudioProjects\AbalfazlTV\assets\font
```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1829:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2863:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2835:38)
#3      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:744:29)
#4      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:685:9)
#5      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:50:26)
<asynchronous suspension>
#7      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:64:34)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
<asynchronous suspension>
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:320:32)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22621.819], locale en-US)
    • Flutter version 3.0.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (6 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Asus\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Connected device (4 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)                • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 107.0.5304.108
    • Edge (web)                       • edge          • web-javascript • Microsoft Edge 107.0.1418.56

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: cd41fdd495f6944ecd3506c21e94c6567b073278
### Plugins
audio_session-0.1.11
fluttertoast-8.1.1
just_audio-0.9.30
just_audio_web-0.4.7
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
video_player-2.4.8
video_player_android-2.3.9
video_player_avfoundation-2.3.7
video_player_web-2.0.12

**Comment by exaby73** [comment]
Hello @abolfazlirani. Could you include your project structure as well as your `pubspec.yaml` file contents?
