### ISSUE TITLE
[tool_crash] StateError: Bad state: No element

### ISSUE THREAD

**Issue by goodLunk** [flutter/flutter#116262]
## Command
```
flutter attach --app-id com.klook.klook
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No element
```
#0      List.first (dart:core-patch/growable_array.dart:343:5)
#1      _defaultReloadSourcesHelper.<anonymous closure> (package:flutter_tools/src/run_hot.dart:1132:61)
#2      _rootRunUnary (dart:async/zone.dart:1399:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _defaultReloadSourcesHelper (package:flutter_tools/src/run_hot.dart:1142:44)
<asynchronous suspension>
#6      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:904:38)
<asynchronous suspension>
#7      HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:812:16)
<asynchronous suspension>
#8      HotRunner.restart (package:flutter_tools/src/run_hot.dart:707:36)
<asynchronous suspension>
#9      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1686:40)
<asynchronous suspension>
#10     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1739:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.5.1 21G83 darwin-arm (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.3.5 on channel stable at /Users/tea.li/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (6 weeks ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)

**Comment by darshankawar** [comment]
There's no similar issue open currently with similar stacktrace, so keeping it open and labeling for tracking.

/cc @christopherfujino
