### ISSUE TITLE
Error while building in Fuchsia infrastructure

### ISSUE THREAD

**Issue by lin-erik** [flutter/flutter#116297]
`flutter_tools/bin/fuchsia_asset_builder.dart` seems to be attempting to call `FileSystemEntity.deleteSync` on a non-existent file. This happens occasionally in Fuchsia infra and causes tree blockage (latest fxb/115954).

Fix may involve adding a check for file or directory existence before running `deleteSync`

```
FAILED: gen/src/experiences/session_shells/ermine/login/build/login_pkgassets 
../../build/rbe/output-scanner.sh --label //src/experiences/session_shells/ermine/login:component_asset_manifest\(//build/toolchain/fuchsia:x64\) gen/src/experiences/session_shells/ermine/login/build/login_pkgassets -- ../../prebuilt/third_party/python3/linux-x64/bin/python3.8 -S ../../build/tracer/action_tracer.py --fsatrace-path ../../prebuilt/fsatrace/fsatrace --label //src/experiences/session_shells/ermine/login:component_asset_manifest\(//build/toolchain/fuchsia:x64\) --trace-output .traces/gen/src/experiences/session_shells/ermine/login/component_asset_manifest_trace.txt --failed-check-status=1 --inputs ../../src/experiences/session_shells/ermine/login/pubspec.yaml host_x64/dart-tools/fuchsia_asset_builder host_x64/gen/third_party/dart-pkg/git/flutter/packages/flutter_tools/fuchsia_asset_builder.snapshot ../../build/flutter/internal/gen_asset_manifest.py ../../prebuilt/third_party/python3/linux-x64/bin/python3.8 ../../prebuilt/fsatrace/fsatrace ../../build/tracer/action_tracer.py --outputs gen/src/experiences/session_shells/ermine/login/build/login_pkgassets --depfile gen/src/experiences/session_shells/ermine/login/build/login_pkgassets.d -- ../../prebuilt/third_party/python3/linux-x64/bin/python3.8 -S ../../build/flutter/internal/gen_asset_manifest.py --flutter-root ../../third_party/dart-pkg/git/flutter --flutter-tools host_x64/dart-tools/fuchsia_asset_builder --asset-dir gen/src/experiences/session_shells/ermine/login/build/__untraced_flutter_assets__ --packages gen/src/experiences/session_shells/ermine/login/component_dart_package_package_config.json --output gen/src/experiences/session_shells/ermine/login/build/login_pkgassets --component-name login --manifest ../../src/experiences/session_shells/ermine/login/pubspec.yaml --depfile gen/src/experiences/session_shells/ermine/login/build/login_pkgassets.d
Failed to decode preferences in /tmp/tool_state.
You may need to reapply any previously saved configuration with the "flutter config" command.
Unhandled exception:
FileSystemException: Cannot delete file, path = '/tmp/tool_state' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File._deleteSync (dart:io/file_impl.dart:312:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      new Config.createForTesting (package:flutter_tools/src/base/config.dart:119:15)
#6      new Config._common (package:flutter_tools/src/base/config.dart:77:19)
#7      new Config (package:flutter_tools/src/base/config.dart:37:19)
#8      new _DefaultPersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:65:18)
#9      new PersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:21:9)
#10     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:294:34)
#11     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#12     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:530:23)
#13     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#15     PersistentToolState.instance (package:flutter_tools/src/persistent_tool_state.dart:35:55)
#16     persistentToolState (package:flutter_tools/src/globals.dart:74:69)
#17     _defaultBotDetector (package:flutter_tools/src/globals.dart:80:24)
#18     _defaultBotDetector (package:flutter_tools/src/globals.dart)
#19     botDetector (package:flutter_tools/src/globals.dart:76:62)
#20     isRunningOnBot (package:flutter_tools/src/globals.dart:86:36)
#21     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:80:34)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#23     _rootRun (dart:async/zone.dart:1398:13)
#24     _CustomZone.run (dart:async/zone.dart:1300:19)
#25     _runZoned (dart:async/zone.dart:1803:10)
#26     runZoned (dart:async/zone.dart:1746:10)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
#28     runInContext (package:flutter_tools/src/context_runner.dart:84:18)
#29     main (file:///b/s/w/ir/cache/incremental/third_party/dart-pkg/git/flutter/packages/flutter_tools/bin/fuchsia_asset_builder.dart:35:10)
#30     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
[7945/155170] ACTION //src/flutter/tests/bin/pingable-flutter-component:pingable-flutter-component-debug-build-cfg_asset_manifest(//build/toolchain/fuchsia:x64)
Could not read preferences in /tmp/tool_state.
FileSystemException: Cannot open file, path = '/tmp/tool_state' (OS Error: No such file or directory, errno = 2)
You may need to resolve the error above and reapply any previously saved configuration with the "flutter config" command.
[7946/155170] ACTION //src/flutter/tests/bin/pingable-flutter-component:pingable-flutter-component-profile-build-cfg_asset_manifest(//build/toolchain/fuchsia:x64)
FAILED: gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-profile-build-cfg_pkgassets 
../../build/rbe/output-scanner.sh --label //src/flutter/tests/bin/pingable-flutter-component:pingable-flutter-component-profile-build-cfg_asset_manifest\(//build/toolchain/fuchsia:x64\) gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-profile-build-cfg_pkgassets -- ../../prebuilt/third_party/python3/linux-x64/bin/python3.8 -S ../../build/tracer/action_tracer.py --fsatrace-path ../../prebuilt/fsatrace/fsatrace --label //src/flutter/tests/bin/pingable-flutter-component:pingable-flutter-component-profile-build-cfg_asset_manifest\(//build/toolchain/fuchsia:x64\) --trace-output .traces/gen/src/flutter/tests/bin/pingable-flutter-component/pingable-flutter-component-profile-build-cfg_asset_manifest_trace.txt --failed-check-status=1 --inputs ../../src/flutter/tests/bin/pingable-flutter-component/pubspec.yaml host_x64/dart-tools/fuchsia_asset_builder host_x64/gen/third_party/dart-pkg/git/flutter/packages/flutter_tools/fuchsia_asset_builder.snapshot ../../build/flutter/internal/gen_asset_manifest.py ../../prebuilt/third_party/python3/linux-x64/bin/python3.8 ../../prebuilt/fsatrace/fsatrace ../../build/tracer/action_tracer.py --outputs gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-profile-build-cfg_pkgassets --depfile gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-profile-build-cfg_pkgassets.d -- ../../prebuilt/third_party/python3/linux-x64/bin/python3.8 -S ../../build/flutter/internal/gen_asset_manifest.py --flutter-root ../../third_party/dart-pkg/git/flutter --flutter-tools host_x64/dart-tools/fuchsia_asset_builder --asset-dir gen/src/flutter/tests/bin/pingable-flutter-component/build/__untraced_flutter_assets__ --packages gen/src/flutter/tests/bin/pingable-flutter-component/pingable-flutter-component-profile-build-cfg_dart_package_package_config.json --output gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-profile-build-cfg_pkgassets --component-name pingable-flutter-component-profile-build-cfg --manifest ../../src/flutter/tests/bin/pingable-flutter-component/pubspec.yaml --depfile gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-profile-build-cfg_pkgassets.d
Failed to decode preferences in /tmp/tool_state.
You may need to reapply any previously saved configuration with the "flutter config" command.
Unhandled exception:
FileSystemException: Cannot delete file, path = '/tmp/tool_state' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File._deleteSync (dart:io/file_impl.dart:312:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      new Config.createForTesting (package:flutter_tools/src/base/config.dart:119:15)
#6      new Config._common (package:flutter_tools/src/base/config.dart:77:19)
#7      new Config (package:flutter_tools/src/base/config.dart:37:19)
#8      new _DefaultPersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:65:18)
#9      new PersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:21:9)
#10     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:294:34)
#11     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#12     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:530:23)
#13     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#15     PersistentToolState.instance (package:flutter_tools/src/persistent_tool_state.dart:35:55)
#16     persistentToolState (package:flutter_tools/src/globals.dart:74:69)
#17     _defaultBotDetector (package:flutter_tools/src/globals.dart:80:24)
#18     _defaultBotDetector (package:flutter_tools/src/globals.dart)
#19     botDetector (package:flutter_tools/src/globals.dart:76:62)
#20     isRunningOnBot (package:flutter_tools/src/globals.dart:86:36)
#21     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:80:34)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#23     _rootRun (dart:async/zone.dart:1398:13)
#24     _CustomZone.run (dart:async/zone.dart:1300:19)
#25     _runZoned (dart:async/zone.dart:1803:10)
#26     runZoned (dart:async/zone.dart:1746:10)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
#28     runInContext (package:flutter_tools/src/context_runner.dart:84:18)
#29     main (file:///b/s/w/ir/cache/incremental/third_party/dart-pkg/git/flutter/packages/flutter_tools/bin/fuchsia_asset_builder.dart:35:10)
#30     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
[7947/155170] ACTION //src/ui/a11y/bin/demo:component_asset_manifest(//build/toolchain/fuchsia:x64)
Failed to decode preferences in /tmp/tool_state.
You may need to reapply any previously saved configuration with the "flutter config" command.
```

**Comment by christopherfujino** [comment]
@lin-erik sorry we didn't look at this sooner. Can you confirm this is still happening?
