### ISSUE TITLE
Could not build the application for the simulator and physics device via Android Studio or `flutter run -v`, but the app can launched via Xcode directly

### ISSUE THREAD

**Issue by zeewell** [flutter/flutter#116323]
Could not build the application for the simulator and physics device via Android Studio or `flutter run -v`

But, the app can launched via Xcode directly

## important logs

```
               [   +3 ms] Target debug_unpack_ios failed: Exception: Failed to codesign /xxx/path/example/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter with identity
-.
                          The following argument was not expected: --timestamp=none
                          Run with --help for more information.
           
                          #0      _signFramework (package:flutter_tools/src/build_system/targets/ios.dart:646:5)
                          #1      UnpackIOS.build (package:flutter_tools/src/build_system/targets/ios.dart:296:5)
                          #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
                          <asynchronous suspension>
                          #3      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
                          <asynchronous suspension>
                          #4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
                          <asynchronous suspension>
                          #5      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
                          <asynchronous suspension>
                          #6      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
                          <asynchronous suspension>
                          #7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
                          <asynchronous suspension>
                          #8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:316:32)
                          <asynchronous suspension>
                          #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
                          <asynchronous suspension>
                          #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                          <asynchronous suspension>
                          #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
                          <asynchronous suspension>
                          #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
                          <asynchronous suspension>
                          #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #17     main (package:flutter_tools/executable.dart:91:3)
                          <asynchronous suspension>
           
               [   +1 ms] 
                          #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                          #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:333:7)
                          <asynchronous suspension>
                          #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
                          <asynchronous suspension>
                          #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                          <asynchronous suspension>
                          #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
                          <asynchronous suspension>
                          #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
                          <asynchronous suspension>
                          #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #10     main (package:flutter_tools/executable.dart:91:3)
                          <asynchronous suspension>
               Failed to package /xxx/path/example.
               Command PhaseScriptExecution failed with a nonzero exit code
           
           
               Result bundle written to path:
                /var/folders/dr/hytz4ydj6qzbzlj0jwt1d2v80000gn/T/flutter_tools.oSCauU/flutter_ios_build_temp_dirFyqbYQ/temporary_xcresult_bundle
           
           
[  +30 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14 Pro Max.
[   +1 ms] "flutter run" took 8,219ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +252 ms] ensureAnalyticsSent: 251ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

## flutter doctor Logs

<details>
<summary>flutter doctor -v</summary>
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-CN)
    • Flutter version 3.3.9 on channel stable at /xxx/path/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (8 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /xxx/path/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode-14.1.0.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.2.5
    • Dart plugin version 222.4345.14

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone (mobile)        • 00008101-001E75492EC2001E            • ios          • iOS 16.1.1 20B101
    • iPhone 14 Pro Max (mobile) • E86F856F-B426-456B-AF9A-ABF6AEDEF188 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64 • macOS 13.0.1 22A400 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by exaby73** [comment]
Hello @zeewell. Thank you for filing this issue. Can you please provide detailed reproduction steps, along with a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) if applicable?

**Comment by zeewell** [comment]
@exaby73 
In one of my actual projects everything was fine, because other projects need some testing, I reinstalled xcode, updated the certificate in the keychain, etc. (there are many, many adjustments to the environment, the process is not particularly clear). Then when I returned to the project, I found that I could not build it, but directly using xcode was still all right.

I have done some tests.
1. switched flutter to the master and beta channels, no luck
2. reinstalled command line tool and Xcode again, but it didn't work either.
and more

Then I created a new flutter project using `flutter create`. The problem is still the same in this new project.

**Comment by zeewell** [comment]
@exaby73 
I found the problem because my machine recently installed conda, and the default codesign was directed to `/opt/homebrew/anaconda3/bin/codesign` but this `codesign` was not the right one

**Comment by zeewell** [comment]
The python package installed on my machine that affects codesign is sigtool
https://github.com/thefloweringash/sigtool

**Comment by exaby73** [comment]
What's the output of `which codesign`?
