### ISSUE TITLE
Will not build on Windows: Obscure error messages about CMake

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#116392]
## Steps to Reproduce

```
 flutter run
Multiple devices found:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.35
[1]: Windows (windows)
[2]: Edge (edge)
Please choose one (To quit, press "q/Q"): 1
Launching lib\main.dart on Windows in debug mode...
CMake Error at CMakeLists.txt:50 (add_subdirectory):
  The source directory

    C:/Users/64211/flutter_views/windows/flutter

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:77 (install):
  install FILES given directory "" to install.


CMake Error at CMakeLists.txt:80 (install):
  install FILES given directory "" to install.


CMake Error at CMakeLists.txt:99 (install):
  install FILES given directory "" to install.


Building Windows application...
Exception: Unable to generate build files
```

The sample app runs.  So I do not think I can blame flutter for the failure.

The issue is the output does not help me diagnose the problem.  

```
CMake Error at CMakeLists.txt:50 (add_subdirectory):
  The source directory

    C:/Users/64211/flutter_views/windows/flutter

  does not contain a CMakeLists.txt file.
````

Does not mean anything to me.  I know what `CMake` is, but I have not installed it here

```
flutter upgrade
Flutter is already up to date on channel stable
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (9 days ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
C:\Users\64211\flutter_views [WorikWork ≡ +0 ~1 -0 !]> flutter pub get
Running "flutter pub get" in flutter_views...                    2,467ms
C:\Users\64211\flutter_views [WorikWork ≡ +0 ~1 -0 !]> flutter run --verbose
[  +52 ms] executing: [c:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +61 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] b8f7f1f9869bb2d116aa6a70dbeac61000b52849
[   +1 ms] executing: [c:\src\flutter/] git tag --points-at b8f7f1f9869bb2d116aa6a70dbeac61000b52849
[  +57 ms] Exit code 0 from: git tag --points-at b8f7f1f9869bb2d116aa6a70dbeac61000b52849
[   +1 ms] 3.3.9
[  +36 ms] executing: [c:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[   +1 ms] origin/stable
[        ] executing: [c:\src\flutter/] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +155 ms] Unable to locate an Android SDK.
[   +4 ms] executing: [c:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +60 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +83 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Multiple devices found:
[   +4 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
[   +1 ms] Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.35
[        ] [1]: Windows (windows)
[        ] [2]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] :
[+16972 ms] 1
[  +12 ms] Skipping pub get: version match.
[  +33 ms] Found plugin device_info_plus at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_info_plus-8.0.0\
[  +24 ms] Found plugin package_info_plus at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-3.0.2\
[   +4 ms] Found plugin path_provider_linux at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.7\
[   +5 ms] Found plugin path_provider_windows at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.1.3\
[   +8 ms] Found plugin shared_preferences at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.15\
[   +4 ms] Found plugin shared_preferences_android at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_android-2.0.14\
[   +2 ms] Found plugin shared_preferences_ios at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_ios-2.1.1\
[   +1 ms] Found plugin shared_preferences_linux at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.1.1\
[   +2 ms] Found plugin shared_preferences_macos at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.4\
[   +2 ms] Found plugin shared_preferences_web at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.4\
[   +1 ms] Found plugin shared_preferences_windows at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.1.1\
[  +59 ms] Found plugin device_info_plus at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_info_plus-8.0.0\
[  +14 ms] Found plugin package_info_plus at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-3.0.2\
[   +3 ms] Found plugin path_provider_linux at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.7\
[   +2 ms] Found plugin path_provider_windows at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.1.3\
[   +4 ms] Found plugin shared_preferences at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.15\
[   +1 ms] Found plugin shared_preferences_android at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_android-2.0.14\
[   +1 ms] Found plugin shared_preferences_ios at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_ios-2.1.1\
[   +1 ms] Found plugin shared_preferences_linux at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.1.1\
[   +1 ms] Found plugin shared_preferences_macos at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.4\
[   +1 ms] Found plugin shared_preferences_web at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.4\
[   +1 ms] Found plugin shared_preferences_windows at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.1.1\
[  +36 ms] Found plugin device_info_plus at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_info_plus-8.0.0\
[  +11 ms] Found plugin package_info_plus at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-3.0.2\
[   +2 ms] Found plugin path_provider_linux at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.7\
[   +2 ms] Found plugin path_provider_windows at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.1.3\
[   +5 ms] Found plugin shared_preferences at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.15\
[   +1 ms] Found plugin shared_preferences_android at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_android-2.0.14\
[   +1 ms] Found plugin shared_preferences_ios at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_ios-2.1.1\
[   +1 ms] Found plugin shared_preferences_linux at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.1.1\
[        ] Found plugin shared_preferences_macos at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.4\
[   +1 ms] Found plugin shared_preferences_web at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.4\
[   +1 ms] Found plugin shared_preferences_windows at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.1.1\
[  +57 ms] Generating
C:\Users\64211\flutter_views\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +77 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents: C:\Users\64211\flutter_views\.dart_tool\package_config_subset}
[  +14 ms] Found plugin device_info_plus at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_info_plus-8.0.0\
[  +11 ms] Found plugin package_info_plus at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-3.0.2\
[   +1 ms] Found plugin path_provider_linux at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.7\
[   +2 ms] Found plugin path_provider_windows at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.1.3\
[   +4 ms] Found plugin shared_preferences at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.15\
[   +1 ms] Found plugin shared_preferences_android at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_android-2.0.14\
[   +1 ms] Found plugin shared_preferences_ios at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_ios-2.1.1\
[   +1 ms] Found plugin shared_preferences_linux at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.1.1\
[   +1 ms] Found plugin shared_preferences_macos at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.4\
[   +1 ms] Found plugin shared_preferences_web at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.4\
[        ] Found plugin shared_preferences_windows at
c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.1.1\
[  +14 ms] gen_dart_plugin_registrant: Complete
[   +3 ms] _composite: Starting due to {}
[   +1 ms] _composite: Complete
[   +9 ms] complete
[   +3 ms] Launching lib\main.dart on Windows in debug mode...
[   +3 ms] c:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
c:\src\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
c:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\64211\AppData\Local\Temp\flutter_tools.78ff4e44\flutter_tool.15bba9b6\app.dill --packages
C:\Users\64211\flutter_views\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --source
C:\Users\64211\flutter_views\.dart_tool\flutter_build\dart_plugin_registrant.dart --source
package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///C:/Users/64211/flutter_views/.dart_tool/flutter_build/dart_plugin_registrant.da
rt --verbosity=error --enable-experiment=alternative-invalidation-strategy
[   +7 ms] CMake project not found, skipping add_custom_command() VERBATIM migration
[   +9 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products *
-utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +38 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products
* -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] [
             {
               "instanceId": "7b8d3e82",
               "installDate": "2022-10-01T00:07:31Z",
               "installationName": "VisualStudio/17.3.5+32922.545",
               "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "installationVersion": "17.3.32922.545",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelId": "VisualStudio.17.Release",
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.3#17.3.5",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2022-10-01T00:07:31.3528495Z",
               "catalog": {
                 "buildBranch": "d17.3",
                 "buildVersion": "17.3.32922.545",
                 "id": "VisualStudio/17.3.5+32922.545",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.3.5",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "5",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "17.3.5+32922.545",
                 "requiredEngineVersion": "3.3.2182.10694"
               },
               "properties": {
                 "campaignId": "2030:315769c7-33bc-49b0-8a38-6772ddbc9793",
                 "channelManifestId": "VisualStudio.17.Release/17.3.5+32922.545",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +3 ms] Building Windows application...
[  +13 ms] <- compile package:flutter_views/main.dart
[   +1 ms] executing: C:\Program Files\Microsoft Visual
Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
C:\Users\64211\flutter_views\windows -B build\windows -G Visual Studio 17 2022
[  +39 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
[  +29 ms] CMake Error at CMakeLists.txt:50 (add_subdirectory):
[   +2 ms] -- Configuring incomplete, errors occurred!
[   +1 ms]   The source directory
[        ]     C:/Users/64211/flutter_views/windows/flutter
[        ]   does not contain a CMakeLists.txt file.
[        ] CMake Error at CMakeLists.txt:77 (install):
[        ]   install FILES given directory "" to install.
[        ] CMake Error at CMakeLists.txt:80 (install):
[        ]   install FILES given directory "" to install.
[        ] CMake Error at CMakeLists.txt:99 (install):
[        ]   install FILES given directory "" to install.
[        ] See also "C:/Users/64211/flutter_views/build/windows/CMakeFiles/CMakeOutput.log".
[   +9 ms] Building Windows application... (completed in 95ms)
[+8746 ms] Exception: Unable to generate build files
[   +1 ms] "flutter run" took 26,563ms.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>



[ +160 ms] ensureAnalyticsSent: 159ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
C:\Users\64211\flutter_views [WorikWork ≡ +0 ~1 -0 !]>
```

```
 flutter analyze
Analyzing flutter_views...
No issues found! (ran in 3.2s)
```

```
cat .\doctor.txt
[ΓêÜ] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22000.1219], locale en-NZ)
    ΓÇó Flutter version 3.3.9 on channel stable at c:\src\flutter
    ΓÇó Upstream repository https://github.com/flutter/flutter.git
    ΓÇó Framework revision b8f7f1f986 (9 days ago), 2022-11-23 06:43:51 +0900
    ΓÇó Engine revision 8f2221fbef
    ΓÇó Dart version 2.18.5
    ΓÇó DevTools version 2.15.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[ΓêÜ] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    ΓÇó Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    ΓÇó Visual Studio Community 2022 version 17.3.32922.545
    ΓÇó Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    ΓÇó Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[ΓêÜ] VS Code (version 1.72.1)
    ΓÇó VS Code at C:\Users\64211\AppData\Local\Programs\Microsoft VS Code
    ΓÇó Flutter extension version 3.50.0

[ΓêÜ] Connected device (2 available)
    ΓÇó Windows (desktop) ΓÇó windows ΓÇó windows-x64    ΓÇó Microsoft Windows [Version 10.0.22000.1219]
    ΓÇó Edge (web)        ΓÇó edge    ΓÇó web-javascript ΓÇó Microsoft Edge 107.0.1418.35

[ΓêÜ] HTTP Host Availability
    ΓÇó All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

**Comment by stuartmorgan** [comment]
> The issue is the output does not help me diagnose the problem.
> 
> ```
> CMake Error at CMakeLists.txt:50 (add_subdirectory):
>   The source directory
> 
>     C:/Users/64211/flutter_views/windows/flutter
> 
>   does not contain a CMakeLists.txt file.
> ```
> 
> Does not mean anything to me.

`windows/flutter/CMakeLists.txt` is a file that should exist in your project; this error message is saying that you don't have it.

How did you create this project? Do you get the same error if you `flutter create` a new project?

**Comment by WorikQCI** [comment]
> The sample app runs. So I do not think I can blame flutter for the failure.

**Comment by WorikQCI** [comment]
> How did you create this project? Do you get the same error if you `flutter create` a new project?

No.

Cloned a git repository from a different platform (MacOS/iOS)

**Comment by stuartmorgan** [comment]
The project you cloned from is damaged then; that file is a necessary part of the Linux build. You'll need to contact the creator of that project about fixing it, or re-add Linux support to it yourself.

Closing as this is an issue with the project, not Flutter. There's not much we can reasonably do about the error message here at the Flutter level, since pre-checking each individual required file just to handle the case where someone damages a project by deleting a sub-component of the build but not the entire build wouldn't make much sense (and there will always be ways to corrupt the native build that we couldn't validate).

**Comment by WorikQCI** [comment]
Thank you for the attention.

We created the project on MacOS for iOS.

In the early stages we had no problem using the same code bas for all three platforms we are targeting.  This has cropped up.

**Comment by stuartmorgan** [comment]
> In the early stages we had no problem using the same code bas for all three platforms we are targeting. This has cropped up.

If this project used to work and now you have this error, then someone must have deleted the file from the project at some point; it has always been required.

**Comment by WorikQCI** [comment]
Rightio:  I created a new project in Windows and copieed the CMakeLists.txt file 

Thank you
