### ISSUE TITLE
I cant Build ios projects

### ISSUE THREAD

**Issue by Mcmhee** [flutter/flutter#116479]
Building com.ariyo.treegar for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: PMQTLQL47J
Running pod install...                                           1,862ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (`$(ARCHS_STANDARD)`)

    Finding Podfile changes
      - Flutter
      - device_info
      - device_info_plus
      - firebase_core
      - firebase_crashlytics
      - firebase_messaging
      - flutter_inappwebview
      - flutter_local_notifications
      - flutter_pdfview
      - flutter_secure_storage
      - flutter_web_browser
      - flutter_webview_plugin
      - fluttertoast
      - intercom_flutter
      - launch_review
      - local_auth_ios
      - mixpanel_flutter
      - open_file_safe
      - package_info_plus
      - path_provider_ios
      - permission_handler_apple
      - shared_preferences_ios
      - smile_flutter_3
      - uni_links
      - url_launcher_ios
      - video_player_avfoundation
      - wakelock
      - webview_flutter_wkwebview

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `device_info_plus` from `.symlinks/plugins/device_info_plus/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    firebase_core: Using Firebase SDK version '10.2.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`
    firebase_crashlytics: Using Firebase SDK version '10.2.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    firebase_messaging: Using Firebase SDK version '10.2.0' defined in 'firebase_core'
    -> Fetching podspec for `flutter_inappwebview` from `.symlinks/plugins/flutter_inappwebview/ios`
    -> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
    -> Fetching podspec for `flutter_pdfview` from `.symlinks/plugins/flutter_pdfview/ios`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `flutter_web_browser` from `.symlinks/plugins/flutter_web_browser/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `intercom_flutter` from `.symlinks/plugins/intercom_flutter/ios`
    -> Fetching podspec for `launch_review` from `.symlinks/plugins/launch_review/ios`
    -> Fetching podspec for `local_auth_ios` from `.symlinks/plugins/local_auth_ios/ios`
    -> Fetching podspec for `mixpanel_flutter` from `.symlinks/plugins/mixpanel_flutter/ios`
    -> Fetching podspec for `open_file_safe` from `.symlinks/plugins/open_file_safe/ios`
    -> Fetching podspec for `package_info_plus` from `.symlinks/plugins/package_info_plus/ios`
    -> Fetching podspec for `path_provider_ios` from `.symlinks/plugins/path_provider_ios/ios`
    -> Fetching podspec for `permission_handler_apple` from `.symlinks/plugins/permission_handler_apple/ios`
    -> Fetching podspec for `shared_preferences_ios` from `.symlinks/plugins/shared_preferences_ios/ios`
    -> Fetching podspec for `smile_flutter_3` from `.symlinks/plugins/smile_flutter_3/ios`
    -> Fetching podspec for `uni_links` from `.symlinks/plugins/uni_links/ios`
    -> Fetching podspec for `url_launcher_ios` from `.symlinks/plugins/url_launcher_ios/ios`
    -> Fetching podspec for `video_player_avfoundation` from `.symlinks/plugins/video_player_avfoundation/ios`
    -> Fetching podspec for `wakelock` from `.symlinks/plugins/wakelock/ios`
    -> Fetching podspec for `webview_flutter_wkwebview` from `.symlinks/plugins/webview_flutter_wkwebview/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/10.2.0/Firebase.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/10.2.0/Firebase.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/10.2.0/Firebase.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: all_pods_versions_6_8_6.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/6/8/6/OrderedSet/5.0.0/OrderedSet.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_5_1_0.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/5/1/0/Toast/4.0.0/Toast.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_6_2.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/a/6/2/Intercom/14.0.3/Intercom.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: all_pods_versions_2_d_e.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/2/d/e/Mixpanel-swift/4.0.2/Mixpanel-swift.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_e_3_3.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/e/3/3/Smile_Identity_SDK/2.1.18.beta2/Smile_Identity_SDK.podspec.json exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/10.2.0/Firebase.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/a/6/2/Intercom/14.0.3/Intercom.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/2/d/e/Mixpanel-swift/3.3.0/Mixpanel-swift.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/2/d/e/Mixpanel-swift/3.3.0/Mixpanel-swift.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_8_b_d.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/8/b/d/FirebaseCore/10.2.0/FirebaseCore.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/e/3/3/Smile_Identity_SDK/2.1.17/Smile_Identity_SDK.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_b_e_b.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/3.2.0/GoogleMLKit.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/3.2.0/GoogleMLKit.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_e_7_d.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/e/7/d/FirebaseCrashlytics/10.2.0/FirebaseCrashlytics.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/5/1/0/Toast/4.0.0/Toast.podspec.json exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/6/8/6/OrderedSet/5.0.0/OrderedSet.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/8/b/d/FirebaseCore/10.2.0/FirebaseCore.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_8_4.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_7_9_1.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/7/9/1/FirebaseCoreInternal/10.2.0/FirebaseCoreInternal.podspec.json exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/3.2.0/GoogleMLKit.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_f_4.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/a/f/4/MLKitFaceDetection/2.2.0/MLKitFaceDetection.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_2_d_6.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/2/d/6/FirebaseMessaging/10.2.0/FirebaseMessaging.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_b_5.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/0/b/5/PromisesObjC/2.1.1/PromisesObjC.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/9/1/FirebaseCoreInternal/10.2.0/FirebaseCoreInternal.podspec.json exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_c_6.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/a/f/4/MLKitFaceDetection/2.2.0/MLKitFaceDetection.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_8_1_e.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/8/1/e/MLKitVision/4.2.0/MLKitVision.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/e/7/d/FirebaseCrashlytics/10.2.0/FirebaseCrashlytics.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_2_f_7.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/2/f/7/FirebaseInstallations/10.2.0/FirebaseInstallations.podspec.json exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_6_a.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/0/6/a/GoogleDataTransport/9.2.0/GoogleDataTransport.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_6_1_e.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/6/1/e/nanopb/2.30909.0/nanopb.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/8/b/d/FirebaseCore/10.2.0/FirebaseCore.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_e_3.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/3.0.0/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.7.2/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_7_4_b.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/3.0.0/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_8_8_9.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/8/8/9/GoogleUtilitiesComponents/1.1.0/GoogleUtilitiesComponents.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_e_c_d.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/e/c/d/Protobuf/3.21.10/Protobuf.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/8/1/e/MLKitVision/4.2.0/MLKitVision.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_a_c.txt exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: Specs/0/a/c/MLImage/1.0.0-beta3/MLImage.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/0/a/c/MLImage/1.0.0-beta3/MLImage.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/0/6/a/GoogleDataTransport/9.2.0/GoogleDataTransport.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/6/a/GoogleDataTransport/9.2.0/GoogleDataTransport.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/b/5/PromisesObjC/2.1.1/PromisesObjC.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/2/f/7/FirebaseInstallations/10.2.0/FirebaseInstallations.podspec.json exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/b/5/PromisesObjC/2.1.1/PromisesObjC.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/8/8/9/GoogleUtilitiesComponents/1.1.0/GoogleUtilitiesComponents.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/6/1/e/nanopb/2.30909.0/nanopb.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/6/1/e/nanopb/2.30909.0/nanopb.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/6/1/e/nanopb/2.30909.0/nanopb.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/2/d/6/FirebaseMessaging/10.2.0/FirebaseMessaging.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/e/c/d/Protobuf/3.21.10/Protobuf.podspec.json exists! Returning local because checking is
      only performed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.10.0/GoogleUtilities.podspec.json exists! Returning local because
      checking is only performed in repo update

    Comparing resolved specification to the sandbox manifest
      A Firebase
      A FirebaseCore
      A FirebaseCoreInternal
      A FirebaseCrashlytics
      A FirebaseInstallations
      A FirebaseMessaging
      A Flutter
      A GTMSessionFetcher
      A GoogleDataTransport
      A GoogleMLKit
      A GoogleToolboxForMac
      A GoogleUtilities
      A GoogleUtilitiesComponents
      A Intercom
      A MLImage
      A MLKitCommon
      A MLKitFaceDetection
      A MLKitVision
      A Mixpanel-swift
      A OrderedSet
      A PromisesObjC
      A Protobuf
      A Smile_Identity_SDK
      A Toast
      A device_info
      A device_info_plus
      A firebase_core
      A firebase_crashlytics
      A firebase_messaging
      A flutter_inappwebview
      A flutter_local_notifications
      A flutter_pdfview
      A flutter_secure_storage
      A flutter_web_browser
      A flutter_webview_plugin
      A fluttertoast
      A intercom_flutter
      A launch_review
      A local_auth_ios
      A mixpanel_flutter
      A nanopb
      A open_file_safe
      A package_info_plus
      A path_provider_ios
      A permission_handler_apple
      A shared_preferences_ios
      A smile_flutter_3
      A uni_links
      A url_launcher_ios
      A video_player_avfoundation
      A wakelock
      A webview_flutter_wkwebview

    Downloading dependencies

    -> Installing Firebase (10.2.0)
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update

    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    ### Command

    ```
    /usr/local/bin/pod install --verbose
    ```

    ### Report

    * What did you do?

    * What did you expect to happen?

    * What happened instead?

    ### Stack

    ```
       CocoaPods : 1.11.3
            Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]
        RubyGems : 3.0.3.1
            Host : macOS 13.0.1 (22A400)
           Xcode : 14.1 (14B47b)
             Git : git version 2.37.1 (Apple Git-137.1)
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
    Repositories : trunk - CDN - https://cdn.cocoapods.org/
    ```

    ### Plugins

    ```
    cocoapods-deintegrate : 1.0.5
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.1
    cocoapods-trunk       : 1.6.0
    cocoapods-try         : 1.2.0
    ```

    ### Podfile

    ```ruby
    # Uncomment this line to define a global platform for your project
    platform :ios, '14.0'

    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def flutter_root
      generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
      unless File.exist?(generated_xcode_build_settings_path)
        raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub
        get is executed first"
      end

      File.foreach(generated_xcode_build_settings_path) do |line|
        matches = line.match(/FLUTTER_ROOT\=(.*)/)
        return matches[1].strip if matches
      end
      raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run
      flutter pub get"
    end

    require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

    flutter_ios_podfile_setup

    target 'Runner' do
      use_frameworks!
      use_modular_headers!

      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
      end
    end
    # post_install do |installer|
    #   installer.pods_project.targets.each do |target|
    #     target.build_configurations.each do |config|
    #       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    #     end
    #   end
    # end
    # post_install do |installer|
    #   installer.pods_project.targets.each do |target|
    #     flutter_additional_ios_build_settings(target)
    #     target.build_configurations.each do |config|
    #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    #     end
    #   end
    # end
    ```

    ### Error

    ```
    Errno::EACCES - Permission denied @ rb_sysopen - /Users/noel/Library/Caches/CocoaPods/Pods/VERSION
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:171:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:171:in `open'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:171:in `open'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:171:in `ensure_matching_version'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:22:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:41:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:41:in `download'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:563:in `install_source_of_pod'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:514:in `block (2 levels) in install_pod_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:86:in `titled_section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:513:in `block in install_pod_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:496:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:496:in `install_pod_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:255:in `block in download_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:254:in `download_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```

    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+%40+rb_sysopen+-+%2FUsers%2Fnoel%2FLibrary%2FCaches%2FCoc
    oaPods%2FPods%2FVERSION&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...
    Found no similar issues. To create a new issue, please visit:
    https://github.com/cocoapods/cocoapods/issues/new

Error output from CocoaPods:
↳
    Project at /Users/noel/Treegar/Runner.xcodeproj does not exist. Please check paths or incorporate Crashlytics upload
    symbols manually.

**Comment by Mcmhee** [comment]
the main thing that baffles me is i dont know how to change path cause this:: /Users/noel/Treegar/Runner.xcodeproj is not my runner.xcodeproj path
