### ISSUE TITLE
google_maps_flutter: Platform view hasn't been initialized from the platform view channel

### ISSUE THREAD

**Issue by sami-samcla** [flutter/flutter#116414]
Hi.

This error occurs only in release mode  when I close a screen with a google maps widget inside. 

## Steps to Reproduce

To reproduce this error I use fvm to run the app.

1. Execute `fvm flutter run -t lib/main.dart --release` on the code sample 
2. Tap on button
3. When map screen is visible and map is loaded completely, press back button. 
4. Repeat step 2 and 3 until app crash.

**Expected results:** Previous screen is shown and app doesn't crash

**Actual results:** App crash while is returning to previous screen 

<details>
<summary>Code sample</summary>

**pubspec.yaml**
```dart
name: google_maps_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.2.1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

```

**main.dart**
```dart
import 'package:flutter/material.dart';
import 'package:google_maps_example/map.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: OutlinedButton(
          child: const Text('Click me!'),
          onPressed: () async {
            Navigator.of(context).push(createRoute(const MapSample()));
          },
        ),
      ),
    );
  }
}

Route<Object> createRoute(Widget targetScreen) {
  return PageRouteBuilder(
    pageBuilder: (context, animation, secondaryAnimation) => targetScreen,
    transitionsBuilder: (context, animation, secondaryAnimation, child) {
      var begin = const Offset(1.0, 0.0);
      var end = Offset.zero;
      var curve = Curves.ease;

      var tween = Tween(begin: begin, end: end).chain(CurveTween(curve: curve));

      return SlideTransition(
        position: animation.drive(tween),
        child: child,
      );
    },
  );
}

```
**map_sample.dart**
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller = Completer();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

**ERROR:**
```
[ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
	at io.flutter.plugin.platform.o.O(Unknown Source:96)
	at io.flutter.plugin.platform.o.X(Unknown Source:3)
	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(Unknown Source:19)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6762)

                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1466)] Check failed: fml::jni::CheckException(env). 
Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 7782 (le_maps_example), pid 7782 (le_maps_example)
obtaining output fd from tombstoned, type: kDebuggerdTombstone
received crash request for pid 7782
performing dump of process 7782 (target tid = 7782)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/tissot/tissot_sprout:9/PKQ1.180917.001/V10.0.24.0.PDHMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 7782, tid: 7782, name: le_maps_example  >>> com.example.google_maps_example <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1466)] Check failed: fml::jni::CheckException(env). 
'
    x0  0000000000000000  x1  0000000000001e66  x2  0000000000000006  x3  0000000000000008
    x4  0000000000800000  x5  0000000000800000  x6  0000000000800000  x7  0000800000000000
    x8  0000000000000083  x9  18b244317a945d0a  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 0000000000000010  x14 ffffffffffffffff  x15 0000fd64fa53b62c
    x16 00000077c076a2b0  x17 00000077c068b9d8  x18 0000000000000010  x19 0000000000001e66
    x20 0000000000001e66  x21 0000007fc2137358  x22 000000771fe22000  x23 000000771fe22000
    x24 000000773cce8460  x25 000000771b561758  x26 0000000000000002  x27 0000000000000079
    x28 0000000000000085  x29 0000007fc2137330
    sp  0000007fc21372f0  lr  00000077c067d00c  pc  00000077c067d034
backtrace:
    #00 pc 0000000000022034  /system/lib64/libc.so (abort+116)
    #01 pc 000000000031db54  /data/app/com.example.google_maps_example-Rl3EaQMF40rxWVM_z7iB8A==/lib/arm64/libflutter.so (offset 0x315000)
```

**flutter analyze**
```
Analyzing google_maps_example...                                
No issues found! (ran in 3.4s)

```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-x64, locale en-GB)
    • Flutter version 3.3.9 on channel stable at /Users/sissa/fvm/versions/3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (10 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sissa/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/sissa/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Mi A1 (mobile)  • 9c6b9a7c0504 • android-arm64  • Android 9 (API 28)
    • macOS (desktop) • macos        • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome       • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @sami-samcla 
Looking at the error, it seems specific to platform-views in Android rather than specific to `google_maps_flutter` plugin and seems similar to https://github.com/flutter/flutter/issues/112542, so please follow-up in it for further updates.
Closing this as a duplicate.
