### ISSUE TITLE
multicast_dns Too many open files error

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#116528]
## Steps to Reproduce

1. Find arm device using Linux
2. git clone https://github.com/CyBear-Jinni/cbj_hub
4. run the project
5. Wait several hours 

**Expected results:** 
mDNS search function keeps searching in the background for devices with 2m delay between calling a new search. 

**Actual results:** 
Getting an error from inside flutter `multicast_dns` package 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```dart
Unhandled exception:
SocketException: Failed to create datagram socket (OS Error: Too many open files, errno = 24), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#2      MdnsScanner._findingMdnsWithAddress (package:network_tools/src/mdns_scanner/mdns_scanner.dart:72:5)
```

```
```

```
It is dart native so not relevant 
```

</details>

The project is running inside a Linux arm machine, dart version `Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_arm"` mDNS package version `multicast_dns: ^0.3.2+1` that is being used from within [network_tools](https://github.com/osociety/network_tools/tree/main/network_tools) package.

I think it happening in my arm device first is because of the small ram 1gb so it will take much longer to reproduce on a 8+gb ram x64 computer

**Comment by darshankawar** [comment]
Thanks for the report @guyluz11 
The github repo you shared seems to be a full fledged app with lots of third party plugins / libraries. Can you confirm if the same error occurs using minimal code sample without third party plugins or just using default counter app on same device ?

**Comment by guyluz11** [comment]
Hi, I will open a new issue.

I found time to create minimal code to reproduce.
Here is a link to the repo 
https://github.com/guyluz11/multicast_dns_error_repo

**Comment by darshankawar** [comment]
> 4\. Wait several hours.

Thanks for the repo. Is there a way to consistently replicate this without this step ?

**Comment by guyluz11** [comment]
> > 4. Wait several hours.
> 
> Thanks for the repo. Is there a way to consistently replicate this without this step ?

Not consistent but I have removed the delay function, did several tests and measured the time and it didn't exceed 11m.

I have updated the code and instructions.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open based on the report and error shown.
