### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by shacharmiron** [flutter/flutter#116500]
## Command
```
flutter run
```

---
* I have found a temporary fix: if I delete the build and android/app/build folders content, it does work for the next build, but I don't know what is making it happen and how to stop it
---

## Logs
FileSystemException: Directory listing failed, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:953:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:792:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:697:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#8      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:459:26)
<asynchronous suspension>
#9      HotRunner.attach (package:flutter_tools/src/run_hot.dart:280:40)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:692:26)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 3.0.2, on Microsoft Windows [Version 10.0.19044.2251], locale en-US)
    • Flutter version 3.0.2 at C:\Users\Lab\flutter
    • Upstream repository unknown
    • Framework revision cd41fdd495 (6 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Lab\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\Lab\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Lab\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33103.184
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code, 64-bit edition (version 1.73.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.54.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 108.0.5359.73
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 107.0.1418.62

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.53.6+4
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
advance_expansion_tile-1.0.2
cloud_firestore_web-3.1.0
firebase_analytics-10.0.6
firebase_analytics_web-0.5.1+5
firebase_core-2.3.0
firebase_core_web-2.0.1
firebase_crashlytics-3.0.6
firebase_performance-0.9.0+6
firebase_performance_web-0.1.1+15
flutter_secure_storage-4.2.1
flutter_webview_plugin-0.4.0
fluttertoast-8.1.1
package_info-2.0.2
package_info_plus-3.0.2
path_provider_linux-2.1.7
path_provider_windows-2.1.3
qr_code_scanner-0feca6f15042c279ff575c559a3430df917b623d
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.3+1
url_launcher-6.1.7
url_launcher_android-6.0.22
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
webview_flutter-2.8.0
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by exaby73** [comment]
Hello @shacharmiron. Looks like you're using an old version of Flutter. Please upgrade to the latest stable 3.3.9 and confirm if this still persists

**Comment by shacharmiron** [comment]
Hey @exaby73, thanx for the fast response, I upgraded to 3.3.9 and it is still the same.

**Comment by exaby73** [comment]
Could you tell me where your Flutter install is located and where your project is on your computer? Are they in different partitions/drives?

**Comment by shacharmiron** [comment]
Im not exactly sure what I did but its working now... Thank you for the help:)
