### ISSUE TITLE
Hot Reload Deselected

### ISSUE THREAD

**Issue by TitikshaDaga** [flutter/flutter#11654]
I am currently workin on Intellij IDEA IDE and in that I have connected a Redmi device. The hot reload button is always deselected. Is it only for fuschia or for every os? How do i enable it?

**Comment by devoncarew** [comment]
The hot reload button become enabled when a Flutter app is running on a device. If you run an app (via the run or debug buttons), hot reload should become enabled once the app starts up on the phone.

**Comment by TitikshaDaga** [comment]
@devoncarew  it doesn't get enabled.

**Comment by devoncarew** [comment]
We'll probably need a bit more details. Can you go to the Tools menu, and run Flutter > Flutter Doctor (an attach the output here)?

And, and deices showing up in the device pulldown, and is there a flutter app available in the launch config selector? Here's what my screen looks like before and during a launch:

<img width="374" alt="screen shot 2017-08-17 at 3 50 36 am" src="https://user-images.githubusercontent.com/1269969/29409121-ae1b940e-82ff-11e7-9290-872c4b2099e0.png">

<img width="355" alt="screen shot 2017-08-17 at 3 53 25 am" src="https://user-images.githubusercontent.com/1269969/29409126-b4a3b914-82ff-11e7-8974-806a5b185f83.png">

**Comment by TitikshaDaga** [comment]
![screenshot from 2017-08-17 16-25-30](https://user-images.githubusercontent.com/12954116/29409204-daf99b2e-8368-11e7-8372-a8af5bd24da1.png)
after screen
![screenshot from 2017-08-17 16-27-38](https://user-images.githubusercontent.com/12954116/29409297-32713b5a-8369-11e7-9edd-d2f77402e5a9.png)
and the before screen

 
![screenshot from 2017-08-17 16-26-53](https://user-images.githubusercontent.com/12954116/29409286-2482c86a-8369-11e7-9490-5048d470a1a6.png)

**Comment by devoncarew** [comment]
Hmm, it's not clear to me what's going on - the reload button definitely should be active for you. It's interesting that the run button doesn't become re-enabled (it disables at the start of a run, but once the app is up, it should re-enable). Perhaps we're missing some event that signals that the app has come up on the phone.

Can you try two other things? If you run your app from the command-line (`flutter run`), I'd like to see if it can get to the `To hot reload your app on the fly...` message, and if you can reload from the command line.

2nd, in the IntelliJ preferences, if you could toggle verbose logging on run (https://github.com/flutter/flutter-intellij/wiki/Diagnosing-Problems#running-apps), re-run your app, and look for issues in the log, and / or paste the output here. Thanks!

**Comment by TitikshaDaga** [comment]
I am attaching the log file

[logs.txt](https://github.com/flutter/flutter/files/1233275/logs.txt)

**Comment by devoncarew** [comment]
Here's the tail end of it:

```
[        ] Waiting for observatory port to be available...
[ +726 ms] Diagnostic server URL on device: http://127.0.0.1:43772/
[   +3 ms] /home/power/Android/Sdk/platform-tools/adb -s 3284a4a29904 forward tcp:8101 tcp:43772
[   +7 ms] Forwarded host port 8101 to device port 43772 for Diagnostic server
[  +33 ms] Observatory URL on device: http://127.0.0.1:47746/
[        ] /home/power/Android/Sdk/platform-tools/adb -s 3284a4a29904 forward tcp:8100 tcp:47746
[   +7 ms] Forwarded host port 8100 to device port 47746 for Observatory
[  +14 ms] Connected to service protocol: http://127.0.0.1:8100/
[   +1 ms] getVM: {}

//log when run on command line

Unhandled exception:
TimeoutException: Request to Dart VM Service timed out: getVM({})
#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:735)
<asynchronous suspension>
#1      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:566)
<asynchronous suspension>
#2      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:414)
<asynchronous suspension>
#3      VMService.getVM (package:flutter_tools/src/vmservice.dart:243)
#4      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:81)
<asynchronous suspension>
#5      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:543)
<asynchronous suspension>
#6      HotRunner.attach (package:flutter_tools/src/run_hot.dart:106)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:206)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:339)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:220)
<asynchronous suspension>
#10     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:227)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
```

Sounds like the same issue is affecting the command-line workflow as well.

It looks like the VM is coming up on the device, we're properly setting up port forwarding, and are able to connect to the debugger port. It's dying at the initial debugger call (`getVM()`), which I don't believe I've seen before.

From the log, it looks like your flutter repo is ~2 weeks old, and you're on the `alpha` channel. You could try updating and switching to the master channel to see if the issue still exists.

```
flutter channel master
flutter upgrade
```

**Comment by TitikshaDaga** [comment]
No it didn't solve the problem.

**Comment by TitikshaDaga** [comment]
Hey, 
@devoncarew  Did u find a work around?

**Comment by devoncarew** [comment]
Sorry, I didn't. cc'ing @tvolkert since the issue (a timeout in the `getVM` service protocol call) also happens on the cli.

**Comment by Hixie** [comment]
@TitikshaDaga do you still see this with the most recent updates?

**Comment by fzngagan** [comment]
I am facing the same issue on Redmi Note 5 pro

**Comment by leorachit** [comment]
I am having this. 

```
Gradle task 'assembleProdDebug'...
timeout waiting for the application to start
```

It could be the issue

**Comment by zoechi** [comment]
Is anybody still seeing this?

**Comment by skyhigh123** [comment]
I still have this error.
I am using

I Flutter 1.3.11-pre.9 • channel master • https://github.com/flutter/flutter.git
Framework • revision a29906d5f5 (5 hours ago) • 2019-03-14 23:51:18 -0700
Engine • revision 403337ebb8
Tools • Dart 2.2.1 (build 2.2.1-dev.1.0 None)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.3.11-pre.10, on Microsoft Windows [Version 10.0.15063], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[!] Proxy Configuration
    ! NO_PROXY is not set
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

![ide](https://user-images.githubusercontent.com/13783350/54414725-b017e580-472c-11e9-824f-1a2517bb00a4.PNG)

**Comment by ariaenggar** [comment]
> 
> 
> Hmm, it's not clear to me what's going on - the reload button definitely should be active for you. It's interesting that the run button doesn't become re-enabled (it disables at the start of a run, but once the app is up, it should re-enable). Perhaps we're missing some event that signals that the app has come up on the phone.
> 
> Can you try two other things? If you run your app from the command-line (`flutter run`), I'd like to see if it can get to the `To hot reload your app on the fly...` message, and if you can reload from the command line.
> 
> 2nd, in the IntelliJ preferences, if you could toggle verbose logging on run (https://github.com/flutter/flutter-intellij/wiki/Diagnosing-Problems#running-apps), re-run your app, and look for issues in the log, and / or paste the output here. Thanks!

Hi, in case of someone needs information, I just tried @devoncarew 's suggestion. The hot reload worked if I using `flutter run` command, I did it at intellij's terminal panel, although the hot reload button is still disabled.

![image](https://user-images.githubusercontent.com/3667474/55005951-835aac80-500f-11e9-9bb5-51e2a3e247bc.png)

In case you need my flutter doctor result:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
[√] Connected device (1 available)

• No issues found!

Device used: LG K350, Android Marshmallow
IDE used: IntelliJ IDEA

Probably flutter plugin bug?
