### ISSUE TITLE
Failed assertion: line 917 pos 12: 'activity!.isScrolling': is not true.

### ISSUE THREAD

**Issue by shunplus** [flutter/flutter#116503]
```console
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 917 pos 12: 'activity!.isScrolling': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:917:12)
#3      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:282:9)
#4      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
#5      ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:124:5)
#6      ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
#7      ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:651:12)
#8      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:449:55)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#10     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:449:7)
#11     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:298:9)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#27     _invoke1 (dart:ui/hooks.dart:170:10)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onUpdate"
Recognizer: HorizontalDragGestureRecognizer#deaea
  start behavior: start
```

**Comment by exaby73** [comment]
Hello @shunplus. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
