### ISSUE TITLE
Unit tests don't fail if expect fails inside ChangeNotifier callback

### ISSUE THREAD

**Issue by flbaue** [flutter/flutter#116653]
## Steps to Reproduce

1. Create a unit test (not widget test) to test a change notifier implementation.
2. Add a listener with expectAsync0 that will throw an exception when called

**Actual results:**
- The exception is logged to the console, but the test completes successful.

**Expected results:**
- The test should fail

 I assume, that the issue is, that inside ChangeNotifier callback errors are caught and not propagated to the test runner.

<details>
<summary>Code sample</summary>

```dart
// ChangeNotifier
class MyController extends ChangeNotifier {
  bool isLoading = false;
Future<void> fetch() async {
    isLoading = true;
    notifyListeners();
   await Future.delayed(Duration(seconds:1, () {});
    isLoading = false;
    notifyListeners();
  }
}

// test
void main() {
  test('my test', () async {
   final controller = MyController();
   controller.addListener(expectAsync0((){
     expect(1,2); // supposed to fail for demonstration
    }));
   await controller.fetch();
  })
}
```

</details>

<details>
  <summary>Logs</summary>

This will log something like this:

```
═╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following TestFailure was thrown while dispatching notifications for MyController:
Expected: <2>
  Actual: <1>

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue on `Master (3.7.0-4.0.pre.38)`. The error is logged to the console, but all tests pass.

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class MyController extends ChangeNotifier {
  bool isLoading = false;
  Future<void> fetch() async {
    isLoading = true;
    notifyListeners();
    await Future.delayed(const Duration(seconds: 1), () {});
    isLoading = false;
    notifyListeners();
  }
}

// test
void main() {
  test('my test', () async {
    final controller = MyController();
    controller.addListener(expectAsync0(() {
      expect(1, 2); // supposed to fail for demonstration
    }));
    await controller.fetch();
  });
}
```

</details>

<details>
<summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following TestFailure was thrown while dispatching notifications for MyController:
Expected: <2>
  Actual: <1>

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _expect (package:test_api/src/expect/expect.dart:129:3)
#2      expect (package:test_api/src/expect/expect.dart:46:3)
#3      expect (package:flutter_test/src/widget_tester.dart:460:16)
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/nabeelparkar/dev/nevercode/issue_116653/test/widget_test.dart:21:7)
#5      Function._apply (dart:core-patch/function_patch.dart:11:73)
#6      Function.apply (dart:core-patch/function_patch.dart:34:12)
#7      _ExpectedFunction._run (package:test_api/src/expect/expect_async.dart:195:23)
#8      _ExpectedFunction.max6 (package:test_api/src/expect/expect_async.dart:178:7)
#9      _ExpectedFunction.max0 (package:test_api/src/expect/expect_async.dart:144:15)
#10     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:381:24)
#11     MyController.fetch (file:///Users/nabeelparkar/dev/nevercode/issue_116653/test/widget_test.dart:9:5)
#12     main.<anonymous closure> (file:///Users/nabeelparkar/dev/nevercode/issue_116653/test/widget_test.dart:23:22)
#13     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The MyController sending notification was:
  Instance of 'MyController'
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Callback called more times than expected (1).
00:05 +1: my test                                                                                                                        
00:05 +1: All tests passed! 
```

</details>

**Comment by tirth-patel-nc** [comment]
# Triage Report

I was able to reproduce the issue using the provided code sample on both the `stable (3.29.3)` and `master (3.32.0-1.0.pre.474)` channels.

<details>
<summary>Code Sample (Same as OP)</summary>

```dart
import 'package:flutter/material.dart';

class MyController extends ChangeNotifier {
  bool isLoading = false;
  Future<void> fetch() async {
    isLoading = true;
    notifyListeners();
    await Future.delayed(const Duration(seconds: 1), () {});
    isLoading = false;
    notifyListeners();
  }
}
```

</details>

<details>
<summary>Test File (Same as OP)</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:hello_world/main.dart';

void main() {
  test('my test', () async {
    final controller = MyController();
    controller.addListener(
      expectAsync0(() {
        expect(1, 2); // supposed to fail for demonstration
      }),
    );
    await controller.fetch();
  });
}
```

</details>

<details>
<summary>Exception</summary>

```dart
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following TestFailure was thrown while dispatching notifications for MyController:
Expected: <2>
  Actual: <1>
When the exception was thrown, this was the stack:
#0      fail (package:matcher/src/expect/expect.dart:149:31)
#1      _expect (package:matcher/src/expect/expect.dart:144:3)
#2      expect (package:matcher/src/expect/expect.dart:56:3)
#3      expect (package:flutter_test/src/widget_tester.dart:474:18)
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/tirthpatel/StudioProjects/hello_world/test/widget_test.dart:9:9)
#5      Function._apply (dart:core-patch/function_patch.dart:11:71)
#6      Function.apply (dart:core-patch/function_patch.dart:38:12)
#7      _ExpectedFunction._run (package:matcher/src/expect/expect_async.dart:196:23)
#8      _ExpectedFunction.max6 (package:matcher/src/expect/expect_async.dart:178:7)
#9      _ExpectedFunction.max0 (package:matcher/src/expect/expect_async.dart:144:15)
#10     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:435:24)
#11     MyController.fetch (package:hello_world/main.dart:7:5)
#12     main.<anonymous closure> (file:///Users/tirthpatel/StudioProjects/hello_world/test/widget_test.dart:12:22)
#13     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:229:19)
<asynchronous suspension>
#14     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:227:7)
<asynchronous suspension>
#15     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:258:9)
<asynchronous suspension>
The MyController sending notification was:
  Instance of 'MyController'
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Callback called more times than expected (1).
```

</details>

<details>
  <summary>stable (3.29.3) - flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale
    en-IN) [970ms]
    • Flutter version 3.29.3 on channel stable at
      /Users/tirthpatel/Development/flutter_stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    [855ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [556ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [9ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available) [5.5s]
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.4.1 24E263 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 135.0.7049.115

[✓] Network resources [559ms]
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
  <summary>master (3.32.0-1.0.pre.474) - flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.32.0-1.0.pre.474, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [1,380ms]
    • Flutter version 3.32.0-1.0.pre.474 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83082c19b7 (6 hours ago), 2025-05-08 15:54:18 -0700
    • Engine revision 83082c19b7
    • Dart version 3.9.0 (build 3.9.0-100.2.beta)
    • DevTools version 2.46.0

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [761ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [428ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [5.5s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.93

[✓] Network resources [599ms]
    • All expected network resources are available.

• No issues found!
```

</details>
