### ISSUE TITLE
[go_router] nested Navigating back with ShellRoute throw Duplicate GlobalKey in go_router 5.2.4 (worked in 5.2.1)

### ISSUE THREAD

**Issue by gemunet** [flutter/flutter#116784]
Hello,

I have a problem using ShellRoute with a nested path, it gives a Duplicate GlobalKey error when clicking back from the appbar

https://user-images.githubusercontent.com/22581144/206748079-92fd1a98-0769-47a5-b1e3-31284e82b246.mp4

![Snap 2022-12-09 at 13 03 36](https://user-images.githubusercontent.com/22581144/206747847-a1f627cd-22c9-4691-bcb4-cdd1fdea8e3f.png)

**code that reproduces the error**

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (context, state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        ShellRoute(
          builder: (context, state, child) {
            return Scaffold(
              body: child,
              appBar: AppBar(title: const Text('ShellRoute Appbar')),
            );
          },
          routes: [
            GoRoute(
              path: 'a',
              builder: (context, state) {
                return const ScreenA();
              },
              routes: <RouteBase>[
                GoRoute(
                  path: 'details',
                  builder: (BuildContext context, GoRouterState state) {
                    return const DetailsScreen();
                  },
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
);

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Appbar')),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            const Text('HomeScreen'),
            TextButton(
              onPressed: () {
                GoRouter.of(context).go('/a');
              },
              child: const Text('Go to A Screen'),
            ),
          ],
        ),
      ),
    );
  }
}

class ScreenA extends StatelessWidget {
  const ScreenA({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          const Text('Screen A'),
          TextButton(
            onPressed: () {
              GoRouter.of(context).go('/a/details');
            },
            child: const Text('View A details'),
          ),
        ],
      ),
    );
  }
}

class DetailsScreen extends StatelessWidget {
  const DetailsScreen({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: Text('Details Screen'),
    );
  }
}
```

**Flutter doctor -v**

```
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Versi¢n 10.0.19044.2251], locale es-CL)
    • Flutter version 3.3.7 on channel stable at C:\Users\g3mu\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (5 weeks ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\g3mu\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.5)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)    

[!] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter       
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\g3mu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.19044.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

Thank!

**Comment by darshankawar** [comment]
Thanks for the report. Seeing same behavior as reported.

<details>
<summary> console error log </summary>

```

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<NavigatorState>#d8e4b]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- KeyedSubtree-[GlobalKey#af1e7]
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:3107:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3132:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#7      _invoke (dart:ui/hooks.dart:145:13)
#8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#9      _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================

```

</details>

Looks similar / related to https://github.com/flutter/flutter/issues/112181

**Comment by ahmednfwela** [comment]
@chunhtai how is this not handled by these tests ?
https://github.com/flutter/packages/blob/main/packages/go_router/test/go_router_test.dart#L688-L882

**Comment by chunhtai** [comment]
I will have to take a look
