### ISSUE TITLE
flutter doctor  Downloading Gradle Wrapper...

### ISSUE THREAD

**Issue by phyooos** [flutter/flutter#11674]
## command

flutter doctor

## exception

SocketException: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = android.googlesource.com, port = 443

```
#0      fetchUrl (package:flutter_tools/src/base/net.dart:18)
<asynchronous suspension>
#1      _downloadFile (package:flutter_tools/src/cache.dart:400)
<asynchronous suspension>
#2      _downloadZippedTarball.<anonymous closure> (package:flutter_tools/src/cache.dart:416)
<asynchronous suspension>
#3      _withTemporaryFile (package:flutter_tools/src/cache.dart:428)
<asynchronous suspension>
#4      _downloadZippedTarball (package:flutter_tools/src/cache.dart:415)
#5      GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:389)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:223)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:196)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:206)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#16     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#25     main (file:///Users/phyooos/develop/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale zh-Hans-CN, channel master)
    • Flutter at /Users/phyooos/develop/flutter
    • Framework revision 47fe630e4e (30 hours ago), 2017-08-16 19:31:59 -0700
    • Engine revision a246501917
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/phyooos/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/phyooos/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Ultimate Edition (version 2017.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • PRO 5 • 860BCML228J8 • android-arm • Android 5.1 (API 22)

```

when use Chrome, https://android.googlesource.com/   is OK!!

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/11681
