### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Uri c:/Users/Msi/AndroidStudioProjects/Soccer-App-master/pubspec.yaml must have scheme 'file:'.

### ISSUE THREAD

**Issue by elgunismayiloff** [flutter/flutter#116737]
## Command
```
flutter --no-color build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Uri c:/Users/Msi/AndroidStudioProjects/Soccer-App-master/pubspec.yaml must have scheme 'file:'.
```
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:86:7)
#1      Context.fromUri (package:path/src/context.dart:1000:32)
#2      FileSystem.getPath (package:file/src/interface/file_system.dart:158:24)
#3      LocalFileSystem.file (package:file/src/backends/local/local_file_system.dart:26:54)
#4      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:38:31)
#5      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:350:5)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1360:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22621.819], locale en-US)
    • Flutter version 3.3.9 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Msi\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:/Users/Msi/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.0)
    • VS Code at C:\Users\Msi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.96
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.42
    ! Device emulator-5554 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
### Plugins
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
sqflite-2.2.2

**Comment by darshankawar** [comment]
Thanks for the report. I don't see existing issue with similar tracktrace, so keeping this issue open and labeling for team's attention.

**Comment by andrewkolos** [comment]
Error source (from the path package):

https://github.com/dart-lang/path/blob/18ec71f7dde21d8518702d77215fb0b2fa45e970/lib/src/style/windows.dart#L84-L87

In the filepath provided in this report, "c:" is getting interpreted as a scheme rather than a Windows drive volume label.

**Comment by andrewkolos** [comment]
Something that may (not) be useful to know is that in the related tests, the file URIs naturally start with the scheme `file:///`, so I wonder if this crash is a result of a rare situation where the scheme is not prepended somewhere.
