### ISSUE TITLE
[go_router] Facing issue while redirection in go router.

### ISSUE THREAD

**Issue by PRBaraiya** [flutter/flutter#116729]
When I use go_router in my app, it gives an error when I run the application.

## Steps to Reproduce

1. Use configurations given in code sample in flutter default application.
2. Run `flutter run`.

**Expected results:**

It should display `LoginPage` when.

**Actual results:**
It shows Bad State error with red screen.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      theme: ThemeData.light(useMaterial3: true),
      darkTheme: ThemeData.dark(useMaterial3: true),
      routerConfig: RoutingConfigurations.router,
    );
  }
}

// Router configurations

class RoutingConfigurations {
  static final GoRouter router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/',
        builder: (_, __) => HomePage(),
      ),
      GoRoute(
        path: '/login',
        builder: (_, __) => LoginPage(),
      ),
    ],
    redirect: (_, state) async {
      await Future.delayed(Duration(seconds: 1));
      return '/login';
    },
  );
}

class HomePage extends StatelessWidget {
  HomePage(): super();

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(title: Text('home')),
    );
  }


}

class LoginPage extends StatelessWidget {
  LoginPage(): super();

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(title: Text('login')),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

***Stack trace***
```
======== Exception caught by widgets library =======================================================
The following StateError was thrown building DefaultSelectionStyle:
Bad state: No element

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/xyz/Projects/my_app/lib/main.dart:13:24
When the exception was thrown, this was the stack: 
#0      List.last (dart:core-patch/growable_array.dart:348:5)
#1      GoRouteInformationParser.restoreRouteInformation (package:go_router/src/parser.dart:103:31)
#2      _RouterState._retrieveNewRouteInformation (package:flutter/src/widgets/router.dart:616:43)
#3      _RouterState._maybeNeedToReportRouteInformation (package:flutter/src/widgets/router.dart:647:31)
#4      _RouterState.didChangeDependencies (package:flutter/src/widgets/router.dart:663:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5036:11)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (371 frames)
#377    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#378    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#379    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#380    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1164:5)
#381    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1111:18)
#382    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:19)
#383    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1110:13)
#384    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:945:7)
#385    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:925:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
```

***flutter analyze***
```
Analyzing my_app...                                   
No issues found! (ran in 1.6s)
```

***flutter doctor -v***
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.3 21E230 darwin-arm (Rosetta), locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/xyz/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/xyz/AppDev/Android/SDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/xyz/AppDev/Android/SDK
    • ANDROID_SDK_ROOT = /Users/xyz/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A1030d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 769AFA38-6505-4C3A-A2C5-E465190C9CF9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm (Rosetta)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by PRBaraiya** [comment]
This error only occurs when I pass the redirect parameter.

**Comment by Gorter-dev** [comment]
For a quick fix or reason why this is happening: 

https://github.com/flutter/flutter/issues/116730
