### ISSUE TITLE
Windows packaging_release_builder failing to find .ci.yaml file. 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#116795]
```
The recipe has crashed at point 'Uncaught exception'!

Traceback (most recent call last):
  File "C:\b\s\w\ir\kitchen-checkout\recipe_engine\recipe_engine\internal\engine.py", line 585, in run_steps
    raw_result = recipe_obj.run_steps(api, engine)
  File "C:\b\s\w\ir\kitchen-checkout\recipe_engine\recipe_engine\internal\recipe_deps.py", line 931, in run_steps
    recipe_result = self.global_symbols['RunSteps'](*args)
  File "C:\b\s\w\ir\kitchen-checkout\flutter\recipes\release\release_builder.py", line 72, in RunSteps
    ci_yaml = api.yaml.read('read ci yaml', ci_yaml_path, api.json.output())
  File "C:\b\s\w\ir\kitchen-checkout\recipe_engine\recipe_engine\recipe_api.py", line 627, in _inner
    return func(*a, **kw)
  File "C:\b\s\w\ir\kitchen-checkout\flutter\recipe_modules\yaml\api.py", line 28, in read
    content = self.m.file.read_text('read', file_path)
  File "C:\b\s\w\ir\kitchen-checkout\recipe_engine\recipe_engine\recipe_api.py", line 627, in _inner
    return func(*a, **kw)
  File "C:\b\s\w\ir\kitchen-checkout\recipe_engine\recipe_modules\file\api.py", line 326, in read_text
    self.m.path.assert_absolute(source)
  File "C:\b\s\w\ir\kitchen-checkout\recipe_engine\recipe_engine\recipe_api.py", line 627, in _inner
    return func(*a, **kw)
  File "C:\b\s\w\ir\kitchen-checkout\recipe_engine\recipe_modules\path\api.py", line 337, in assert_absolute
    raise AssertionError('%s is not absolute' % path)
AssertionError('C:\b\s\w\ir\x\w\mirrors/flutter\.ci.yaml is not absolute')
```

**Comment by godofredoc** [comment]
Fix here: https://flutter-review.googlesource.com/c/recipes/+/37120
