### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by LEHOANGLONG0807** [flutter/flutter#116949]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9101 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      DateTime.parse (dart:core/date_time.dart:347:7)
#1      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:255:43)
#2      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:255:40)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#5      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 0.0.0-unknown, on macOS 12.3.1 21E258 darwin-x64, locale en-VN)
    ! Flutter version 0.0.0-unknown on channel stable at /Users/mac/fvm/versions/3.3.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision  (), 
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.4746.57

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 Pro (mobile)      • 271295FB-2302-41E2-92D1-29CE5D1F6810 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
### Plugins
cloud_firestore_web-3.1.1
downloads_path_provider-0.1.0
firebase_core-2.4.0
firebase_core_web-2.0.2
firebase_messaging-14.1.4
firebase_messaging_web-3.2.9
image_gallery_saver-1.7.1
libphonenumber-2.0.2
libphonenumber_plugin-0.2.3
libphonenumber_web-0.2.0+1
open_file-3.2.1
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.2.2
webview_flutter-3.0.4
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by exaby73** [comment]
Hello @LEHOANGLONG0807. Can you provide [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify the issue?
