### ISSUE TITLE
Windows_android android_flavors_test failing with 'Manifest merger failed with multiple errors'

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#117173]
The Windows_android android_flavors_test is failing with the following error in staging:

```
] * Exception is:
[flavors_test] [STDOUT] stderr: [        ] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processPaidDebugMainManifest'.
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
[flavors_test] [STDOUT] stderr: [   +1 ms] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[flavors_test] [STDOUT] stderr: [        ] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[flavors_test] [STDOUT] stderr: [        ] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[flavors_test] [STDOUT] stderr: [        ] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
[flavors_test] [STDOUT] stderr: [        ] 	at java.base/java.lang.Thread.run(Thread.java:834)
[flavors_test] [STDOUT] stderr: [        ] Caused by: java.lang.RuntimeException: Manifest merger failed with multiple errors, see logs
[flavors_test] [STDOUT] stderr: [        ] 	at com.android.build.gradle.internal.tasks.manifest.ManifestHelperKt.mergeManifests(ManifestHelper.kt:95)
```

A failing build can be found here: 
https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Windows_android%20flavors_test_win/2613/overview

**Comment by ricardoamador** [comment]
This is failing every time on win-5.

**Comment by reidbaker** [comment]
Gary is no longer working on this. 
Also we think it might be working now https://ci.chromium.org/p/flutter/builders/staging/Windows_android%20flavors_test_win
