### ISSUE TITLE
Tapping a TextField can result in weird exception 

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#11719]
I don't know what I did wrong to cause this nor how to fix it. (meaning a better error message would be good)

```
[00055.892] 09540.09581>  EXCEPTION CAUGHT BY GESTURE 
[00055.896] 09540.09581> The following assertion was thrown while handling a gesture:
[00055.896] 09540.09581> 'package:flutter/src/widgets/focus_manager.dart': Failed assertion: line 289: 'node._parent ==
[00055.896] 09540.09581> null': is not true.
[00055.897] 09540.09581> 
[00055.897] 09540.09581> Either the assertion indicates an error in the framework itself, or we should provide substantially
[00055.897] 09540.09581> more information in this error message to help you determine and fix the underlying cause.
[00055.897] 09540.09581> In either case, please report this assertion by filing a bug on GitHub:
[00055.897] 09540.09581>   https://github.com/flutter/flutter/issues/new
[00055.897] 09540.09581> 
[00055.897] 09540.09581> When the exception was thrown, this was the stack:
[00055.901] 09540.09581> #2      FocusScopeNode._setFocus (package:flutter/src/widgets/focus_manager.dart:289)
[00055.901] 09540.09581> #3      FocusScopeNode.requestFocus (package:flutter/src/widgets/focus_manager.dart:253)
[00055.901] 09540.09581> #4      EditableTextState.requestKeyboard (package:flutter/src/widgets/editable_text.dart:427)
[00055.901] 09540.09581> #5      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:451)
[00055.901] 09540.09581> #6      RenderEditable._handleTap (package:flutter/src/rendering/editable.dart:435)
[00055.901] 09540.09581> #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102)
[00055.901] 09540.09581> #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:149)
[00055.901] 09540.09581> #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:119)
[00055.901] 09540.09581> #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156)
[00055.901] 09540.09581> #11     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147)
[00055.901] 09540.09581> #12     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121)
[00055.901] 09540.09581> #13     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101)
[00055.901] 09540.09581> #14     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64)
[00055.901] 09540.09581> #15     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48)
[00055.901] 09540.09581> #16     _invoke1 (file:///usr/local/google/home/anwilson/fuchsia/flutter/lib/ui/hooks.dart:100)
[00055.901] 09540.09581> #17     _dispatchPointerDataPacket (file:///usr/local/google/home/anwilson/fuchsia/flutter/lib/ui/hooks.dart:58)
[00055.901] 09540.09581> (elided 2 frames from class _AssertionError)
[00055.902] 09540.09581> 
[00055.902] 09540.09581> Handler: onTap
[00055.902] 09540.09581> Recognizer:
[00055.902] 09540.09581>   TapGestureRecognizer#b6abd(debugOwner: RenderEditable#46d18 relayoutBoundary=up18, state: ready)
[00055.902] 09540.09581> 
```

**Comment by Hixie** [comment]
cc @abarth in case you have any insight

**Comment by abarth** [comment]
We're attempting to focus a FocusNode that is already focused in another scope.

**Comment by abarth** [comment]
(We should generate a better error message for that case.)

**Comment by sjmcdowall** [comment]
@abarth and @Hixie -- this issue is still open?  Also can someone explain what you mean when you say "scope" .  What is a scope?  How is that different than context?

**Comment by kerberjg** [comment]
This issue is still relevant as of Flutter 1.3.8

**Comment by kerberjg** [comment]
I can confirm the same behavior on iPad (6th gen) with iOS 12.1 and Flutter 1.3.8

Interestingly enough, this doesn't happen on iPhone under the same conditions

**Comment by Hixie** [comment]
This code has changed quite a bit. If you still see this please file a new bug.
