### ISSUE TITLE
[BUG] Crash on foldable device (Bounds must be non zero)

### ISSUE THREAD

**Issue by btrautmann** [flutter/flutter#117241]
## Steps to Reproduce

1. Create a foldable device with the following specs/details (I'm unsure yet whether the specs below matter, but the device being _foldable_ definitely matters):
- 7.6" Fold-in without outer display, API 32 arm 64
- Advanced settings: RAM 4GB, VM Heap 1GB, Internal Storage 10GB
2. `git clone https://github.com/btrautmann/does-it-crash.git`
3. `cd does-it-crash/`
4. `flutter run` on the newly created device
5. The app should build and run successfully
6. Now, select the Closed posture for the foldable by going to the extended settings on the emulator and viewing Virtual Sensors, and then select Closed posture (left-most option)
7. Quit the emulator
8. Do a cold boot of the emulator
9. `flutter run` again inside `does-it-crash/`
10. App hangs on startup and crashes (see below)

**NOTE** The `flutter run` logs are not helpful here, because they stop saying:

```console
[  +90 ms] Fail to connect to service protocol: http://127.0.0.1:50380/O4JJLRxvztY=/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:50380/O4JJLRxvztY=/ws
[        ] "flutter run" took 7,080ms.
[  +32 ms] ensureAnalyticsSent: 31ms
[   +1 ms] Running shutdown hooks
```

In order to get the below logs, use `adb logcat`.

**Expected results:** 

App runs normally

**Actual results:** 

```console
com.example.does_it_crash            E  FATAL EXCEPTION: main
Process: com.example.does_it_crash, PID: 7016
java.lang.IllegalArgumentException: Bounds must be non zero
at androidx.window.extensions.layout.FoldingFeature.validateFeatureBounds(FoldingFeature.java:125)
at androidx.window.extensions.layout.FoldingFeature.<init>(FoldingFeature.java:95)
at androidx.window.extensions.layout.WindowLayoutComponentImpl.getDisplayFeatures(WindowLayoutComponentImpl.java:227)
at androidx.window.extensions.layout.WindowLayoutComponentImpl.getWindowLayoutInfo(WindowLayoutComponentImpl.java:176)
at androidx.window.extensions.layout.WindowLayoutComponentImpl.onDisplayFeaturesChanged(WindowLayoutComponentImpl.java:168)
at androidx.window.extensions.layout.WindowLayoutComponentImpl.updateRegistrations(WindowLayoutComponentImpl.java:242)
at androidx.window.extensions.layout.WindowLayoutComponentImpl.addWindowLayoutInfoListener(WindowLayoutComponentImpl.java:95)
at androidx.window.layout.ExtensionWindowLayoutInfoBackend.registerLayoutChangeCallback(ExtensionWindowLayoutInfoBackend.kt:68)
at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invokeSuspend(WindowInfoTrackerImpl.kt:52)
at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(Unknown Source:8)
at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
at androidx.window.java.layout.WindowInfoTrackerCallbackAdapter$addListener$1$1.invokeSuspend(WindowInfoTrackerCallbackAdapter.kt:96)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7842)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-12-16 16:55:28.398   532-546   ActivityTaskManager     system_process                       W    Force finishing activity com.example.does_it_crash/.MainActivity
```

<details>
<summary>Code sample</summary>

See repository.

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing does_it_crash...                                              
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6.1 21G217 darwin-arm, locale en-US)
    • Flutter version 3.0.5 at /Users/brandontrautmann/fvm/versions/3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/brandontrautmann/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = /Users/brandontrautmann/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio Chipmunk.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @btrautmann 
A similar [issue](https://github.com/flutter/flutter/issues/114868) is already open describing your case, so I suggest you to follow-up in it for further updates.
Closing this as a duplicate.
