### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Function not implemented, errno = 38

### ISSUE THREAD

**Issue by freetim01237** [flutter/flutter#117266]
Hello, I have a problem during the compilation of my application on linux, can someone help me ?

## Command
```
flutter build linux
```

## Logs
FileSystemException: Cannot create link, OS Error: Function not implemented, errno = 38
```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1057:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:994:5)
#6      buildLinux (package:flutter_tools/src/linux/build_linux.dart:67:3)
#7      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:85:11)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.10, on Linux Mint 19.1 4.15.0-200-generic, locale fr_FR.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/zilles/prog/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (il y a 2 jours), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/zilles/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/zilles/prog/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/zilles/prog/android-studio
    • Flutter plugin version 71.1.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 19.1 4.15.0-200-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18a827f3933c19f51862dde3fa472197683249d6
### Plugins
cloud_firestore-3.5.1
cloud_firestore_web-2.8.10
file_picker-4.6.1
firebase_core-1.24.0
firebase_core_web-1.7.3
firebase_storage-10.3.11
firebase_storage_web-3.3.9
flutter_inappwebview-5.7.1+2
flutter_keyboard_visibility-5.4.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_plugin_android_lifecycle-2.0.7
printing-5.9.3
url_launcher-6.1.6
url_launcher_android-6.0.21
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
webview_flutter-2.8.0
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by huycozy** [comment]
@freetim01237 Thanks for reporting this.
Labeling this issue for further insights since there is no similar tool issue with above error message/code and build target.

**Comment by eliasyishak** [comment]
@tim-tiret are you still experiencing this issue?  Have you tried to do this with a new flutter project as well?

```
flutter create test_app
cd test_app

flutter build linux
```

Can you try the above and let me know if you are still seeing the same issue?
