### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by lktinh2018** [flutter/flutter#117315]
Hi all, I can build aab with debug mode and run successful but error with release mode aab.
Please help me!

## Command
```
flutter build appbundle --release --target-platform=android-arm64 --analyze-size --no-validate-deferred-components
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#8      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:119:64)
#9      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:520:60)
#10     AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:459:15)
<asynchronous suspension>
#11     AndroidGradleBuilder.buildAab (package:flutter_tools/src/android/gradle.dart:202:5)
<asynchronous suspension>
#12     BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:152:5)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous clos

**Comment by huycozy** [comment]
Hi @lktinh2018 
What is your Flutter version? Please provide the output of `flutter doctor -v` and `flutter run -v` so that we may verify it. Thank you!
