### ISSUE TITLE
My flutter applications keep throwing KeyRepeatEvent is dispatched exception,

### ISSUE THREAD

**Issue by AyeshaIftikhar** [flutter/flutter#117378]
## Steps to Reproduce
I am working with Flutter 3.3.9 and while debugging the application, the following error/warning message keep showing up on the screen and is making the application way too slow.

![image](https://user-images.githubusercontent.com/63361634/208604369-41f1496c-1e0f-46ae-8aa1-d2c3cc90931a.png)

<details>
<summary>Logs</summary>

```
════════ Exception caught by services library ══════════════════════════════════
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#2874e(physicalKey: PhysicalKeyboardKey#10083(usbHidUsage: "0x00010083", debugName: "Wake Up"), logicalKey: LogicalKeyboardKey#0060b(keyId: "0x10000060b", keyLabel: "Wake Up", debugName: "Wake Up"), character: null, timeStamp: 0:02:23.275759)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#2874e(physicalKey: PhysicalKeyboardKey#10083(usbHidUsage: "0x00010083", debugName: "Wake Up"), logicalKey: LogicalKeyboardKey#0060b(keyId: "0x10000060b", keyLabel: "Wake Up", debugName: "Wake Up"), character: null, timeStamp: 0:02:23.275759)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#2874e(physicalKey: PhysicalKeyboardKey#10083(usbHidUsage: "0x00010083", debugName: "Wake Up"), logicalKey: LogicalKeyboardKey#0060b(keyId: "0x10000060b", keyLabel: "Wake Up", debugName: "Wake Up"), character: null, timeStamp: 0:02:23.275759)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'
```
</details>

**Comment by exaby73** [comment]
Hello @AyeshaIftikhar. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by AyeshaIftikhar** [comment]
> Hello @AyeshaIftikhar. Thank you for filing this issue. Can you please provide the following information?
> 
> * A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
> * The output of `flutter doctor -v`
> * The output of `flutter run -v`
> 
> Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

I am working on an extensive project and its confidential so I can't share the code but it just appears randomly on hot reload or hot restart but sometimes it just appears on pressing back button as well.

**Comment by chifandeyu** [comment]
I pressed Ctrl + v to paste with this exception.

```
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [版本 10.0.19044.2006], locale zh-CN)
    • Flutter version 3.3.8 on channel stable at D:\DevTools\flutter3.3.8_custom\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (6 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\yuchang.xu\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    X Android SDK file not found: C:\Users\yuchang.xu\AppData\Local\Android\sdk\build-tools\32.0.0\aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.74.2)
    • VS Code at C:\Users\yuchang.xu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [版本 10.0.19044.2006]

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#582d3(physicalKey: PhysicalKeyboardKey#00036(usbHidUsage: "0x1600000036", debugName: "Key with ID 0x1600000036"), logicalKey: LogicalKeyboardKey#00103(keyId: "0x200000103", keyLabel: "Shift Right", debugName: "Shift Right"), character: null, timeStamp: 135:58:43.316975)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:881:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#8      _invoke2 (dart:ui/hooks.dart:186:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by huycozy** [comment]
@chifandeyu There are two known issues being tracked: `KeyUpEvent` + `Shift` key:  #99653 and `KeyRepeatEvent` + `Ctrl` key: #106475. Please follow up on these issues for further updates.

**Comment by huycozy** [comment]
@AyeshaIftikhar Is there a separate `Wake up` key on your keyboard?  (look like [this](https://www.flickr.com/photos/c_x/105962938)). 

Did you press it when focusing on a TextField? If so, can you reproduce it with a minimal sample code that has only a TextField? 

>I am working on an extensive project and its confidential so I can't share the code but it just appears randomly on hot reload or hot restart but sometimes it just appears on pressing back button as well.

Can also you clarify the issue with `back button`? And please provide the exception log when the issue happens with this key. 

I would suggest you keep an eye on it if you are able to replicate it consistently and see if it has any pattern. If you are unable to see it again, feel free to close it and write a comment when you have clear steps to reproduce. Thanks!

A template issue may be related that you can refer to: #106475

**Comment by AyeshaIftikhar** [comment]
> @AyeshaIftikhar Is there a separate `Wake up` key on your keyboard? (look like [this](https://www.flickr.com/photos/c_x/105962938)).
> 
> Did you press it when focusing on a TextField? If so, can you reproduce it with a minimal sample code that has only a TextField?
> 
> > I am working on an extensive project and its confidential so I can't share the code but it just appears randomly on hot reload or hot restart but sometimes it just appears on pressing back button as well.
> 
> Can also you clarify the issue with `back button`? And please provide the exception log when the issue happens with this key.
> 
> I would suggest you keep an eye on it if you are able to replicate it consistently and see if it has any pattern. If you are unable to see it again, feel free to close it and write a comment when you have clear steps to reproduce. Thanks!
> 
> A template issue may be related that you can refer to: #106475

The logs I have mentioned in the question are literally logs. And it just appears from nowhere while working in debug mode and the app gets really slow and some times stop responding.

**Comment by huycozy** [comment]
@AyeshaIftikhar The issue should be actionable with clear steps to reproduce it. In case you can not reproduce it again, feel free to close this issue. Once you can find a pattern for this again, please write a comment along with filled information from [issue teamplate](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) so that we may verify it. Thanks!

**Comment by alevinetx** [comment]
I've had this same issue repeatedly across many projects, for at least over a year, and the only common factor is that I'm running Android Studio under Windows, and obviously it's a Windows desktop application.

There's not necessarily a consistent way to reproduce it - usually it happens when the application is focused, and I alt-tab back to Android Studio.

This literally just happened and I finally searched the bug list to see there are many reports of it

<details>
<summary>Error Log</summary>


```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#28c77(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 518:21:36.021435)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:881:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#8      _invoke2 (dart:ui/hooks.dart:186:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

</details>

**Comment by ThraaxSession** [comment]
Same but with "Shift Left" when I press it for longer time. It is pretty annoying as I have to close my app to make it work again.
https://github.com/flutter/flutter/issues/117901

**Comment by ThraaxSession** [comment]
The issue seems the be fixed on master branch. You can try it with changing flutter channel master.
