### ISSUE TITLE
Tapping with S-Pen causes app to crash

### ISSUE THREAD

**Issue by Nuckerr** [flutter/flutter#117552]
## Steps to Reproduce
(tested on Samsung Galaxy Tab S6 Lite)
1. Hover S-Pen over screen while app is focused
2. Hold down side button
3. Tap screen

**Expected results:**
Just tap the screen like any normal gesture

**Actual results:**
The app crashes with this error:

<details>
<summary>Code sample</summary>
Any code, whatever the flutter app I have this issue.
</details>

<details>
  <summary>Logs</summary>

```
E/InputEventReceiver( 7009): Exception dispatching input event.
E/MessageQueue-JNI( 7009): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI( 7009): java.lang.AssertionError: Unexpected masked action
E/MessageQueue-JNI( 7009): 	at io.flutter.embedding.android.AndroidTouchProcessor.getPointerChangeForAction(AndroidTouchProcessor.java:384)
E/MessageQueue-JNI( 7009): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:124)
E/MessageQueue-JNI( 7009): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:104)
E/MessageQueue-JNI( 7009): 	at io.flutter.embedding.android.FlutterView.onTouchEvent(FlutterView.java:940)
E/MessageQueue-JNI( 7009): 	at android.view.View.dispatchTouchEvent(View.java:15155)
E/MessageQueue-JNI( 7009): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/MessageQueue-JNI( 7009): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3584)
E/MessageQueue-JNI( 7009): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3926)
E/MessageQueue-JNI( 7009): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3541)
E/MessageQueue-JNI( 7009): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3926)
E/MessageQueue-JNI( 7009): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3541)
E/MessageQueue-JNI( 7009): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3926)
E/MessageQueue-JNI( 7009): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3541)
E/MessageQueue-JNI( 7009): 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1081)
E/MessageQueue-JNI( 7009): 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
E/MessageQueue-JNI( 7009): 	at android.app.Activity.dispatchTouchEvent(Activity.java:4297)
E/MessageQueue-JNI( 7009): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:1039)
E/MessageQueue-JNI( 7009): 	at android.view.View.dispatchPointerEvent(View.java:15418)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7944)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7717)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7045)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7102)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7068)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7266)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7076)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7323)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7049)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7102)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7068)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7076)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7049)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10584)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10432)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10388)
E/MessageQueue-JNI( 7009): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10716)
E/MessageQueue-JNI( 7009): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
E/MessageQueue-JNI( 7009): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI( 7009): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MessageQueue-JNI( 7009): 	at android.os.Looper.loopOnce(Looper.java:186)
E/MessageQueue-JNI( 7009): 	at android.os.Looper.loop(Looper.java:313)
E/MessageQueue-JNI( 7009): 	at android.app.ActivityThread.main(ActivityThread.java:8855)
E/MessageQueue-JNI( 7009): 	at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI( 7009): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MessageQueue-JNI( 7009): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
D/AndroidRuntime( 7009): Shutting down VM
E/AndroidRuntime( 7009): FATAL EXCEPTION: main
E/AndroidRuntime( 7009): Process: com.example.vivaldi, PID: 7009
E/AndroidRuntime( 7009): java.lang.AssertionError: Unexpected masked action
E/AndroidRuntime( 7009): 	at io.flutter.embedding.android.AndroidTouchProcessor.getPointerChangeForAction(AndroidTouchProcessor.java:384)
E/AndroidRuntime( 7009): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:124)
E/AndroidRuntime( 7009): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:104)
E/AndroidRuntime( 7009): 	at io.flutter.embedding.android.FlutterView.onTouchEvent(FlutterView.java:940)
E/AndroidRuntime( 7009): 	at android.view.View.dispatchTouchEvent(View.java:15155)
E/AndroidRuntime( 7009): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/AndroidRuntime( 7009): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3584)
E/AndroidRuntime( 7009): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3926)
E/AndroidRuntime( 7009): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3541)
E/AndroidRuntime( 7009): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3926)
E/AndroidRuntime( 7009): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3541)
E/AndroidRuntime( 7009): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3926)
E/AndroidRuntime( 7009): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3541)
E/AndroidRuntime( 7009): 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1081)
E/AndroidRuntime( 7009): 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
E/AndroidRuntime( 7009): 	at android.app.Activity.dispatchTouchEvent(Activity.java:4297)
E/AndroidRuntime( 7009): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:1039)
E/AndroidRuntime( 7009): 	at android.view.View.dispatchPointerEvent(View.java:15418)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7944)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7717)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7045)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7102)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7068)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7266)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7076)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7323)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7049)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7102)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7068)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7076)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7049)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10584)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10432)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10388)
E/AndroidRuntime( 7009): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10716)
E/AndroidRuntime( 7009): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
E/AndroidRuntime( 7009): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 7009): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime( 7009): 	at android.os.Looper.loopOnce(Looper.java:186)
E/AndroidRuntime( 7009): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 7009): 	at android.app.ActivityThread.main(ActivityThread.java:8855)
E/AndroidRuntime( 7009): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7009): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime( 7009): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/Process ( 7009): Sending signal. PID: 7009 SIG: 9
Lost connection to device.
```

```
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.04.1 LTS 5.15.0-56-generic, locale en_GB.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/nucker/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (7 days ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/nucker/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/nucker/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/nucker/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /home/nucker/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52
    • Flutter plugin version 71.2.6
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM P610 (mobile) • R52R30MANHN • android-arm64  • Android 12 (API 32)
    • Linux (desktop)  • linux       • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-56-generic
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

This seems related to #111068 which was apparently solved.

**Comment by huycozy** [comment]
Hi @Nuckerr 
Issue #111068 has just been fixed recently and is available on the latest `master`, so please retry on the latest `master` channel. 
However, in case the crash is disappeared but you may hit https://github.com/flutter/flutter/issues/111068#issuecomment-1315138150, please follow up on #42846 for further updates.

**Comment by Nuckerr** [comment]
Thanks so much, it no longer crashes, I have found that the side button on the stylus does not trigger the tap (tested on a normal button), however I can still use the stylus without the button afterwards

**Comment by huycozy** [comment]
@Nuckerr Yes, that's the issue I mentioned above #42846, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
