### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally: Command: xcrun, OS error code: -4

### ISSUE THREAD

**Issue by zhangdong** [flutter/flutter#117530]
## Command
```
flutter build ios --no-codesign
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
 Command: xcrun, OS error code: -4
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:126:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:279:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:321:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/xcode_project.dart:318:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/xcode_project.dart:278:36)
<asynchronous suspension>
#5      IosProject._parseHostAppBundleName (package:flutter_tools/src/xcode_project.dart:254:55)
<asynchronous suspension>
#6      IosProject.hostAppBundleName (package:flutter_tools/src/xcode_project.dart:243:35)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:116:39)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:82:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp.<anonymous closure> (package:flutter_tools/src/commands/build_ios.dart:604:34)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:641:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1275:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.7.0-10.0.pre.33, on macOS 13.0.1 22A400 darwin-x64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.7.0-10.0.pre.33 on channel master at /Users/ccMoving/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision cee3e6cc3d (5 days ago), 2022-12-17 04:03:24 -0500
    [32m•[39m Engine revision b107699980
    [32m•[39m Dart version 3.0.0 (build 3.0.0-35.0.dev)
    [32m•[39m DevTools version 2.20.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    [32m•[39m Android SDK at /Users/ccMoving/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.1
    [32m•[39m ANDROID_HOME = /Users/ccMoving/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14C18
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[32m[✓][39m VS Code (version 1.74.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.56.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m 22081212C (mobile)         • 370c298d                             • android-arm64  • Android 13 (API 33)
    [32m•[39m iPhone 14 Pro Max (mobile) • 2A038D2D-11FD-480B-AF3C-1882794B91CE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    [32m•[39m macOS (desktop)            • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    [32m•[39m Chrome (web)               • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: cee3e6cc3da3ab8de491fb5c8e586e7cb48969b2
### Plugins
audioplayers-1.1.1
audioplayers_android-1.1.1
audioplayers_darwin-1.0.3
audioplayers_linux-1.0.1
audioplayers_web-2.0.1
audioplayers_windows-1.1.0
flutter_aliplayer
flutter_native_splash-2.2.16
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.2
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.2
sqflite-2.2.2

**Comment by darshankawar** [comment]
I don't see an existing duplicate issue for this, although there are similar ones but with different stacktrace and OS error, so keeping this issue open and labeling for team's attention.

**Comment by jmagman** [comment]
@zhangdong can you attach the full output of:
```
flutter build ios --no-codesign --verbose
```
