### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by Myself-MPSingh** [flutter/flutter#117648]
## Command
```
flutter pub add firebase_auth
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      ForwardingFile.openSync (package:file/src/forwarding/forwarding_file.dart:71:16)
#3      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:315:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:314:5)
#6      CocoaPods.setupPodfile (package:flutter_tools/src/macos/cocoapods.dart

**Comment by huycozy** [comment]
@Myself-MPSingh Can you share the complete output of `flutter pub add firebase_auth` command? And please provide the output of `flutter doctor -v` as well. Thanks!
