### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by Luoyunlong** [flutter/flutter#117655]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: Operation not permitted, errno = 1
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      AndroidSdk.reinitialize (package:flutter_tools/src/android/android_sdk.dart:334:10)
#5      new AndroidSdk (package:flutter_tools/src/android/android_sdk.dart:38:5)
#6      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:153:12)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#12     androidSdk (package:flutter_tools/src/globals.dart:63:39)
#13     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:189:29)
#14     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#16     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#18     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#19     deviceManager (package:flutter_tools/src/globals.dart:55:45)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:259:17)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
```
```
encountered exception: FileSystemException: Directory listing failed, path = '/Users/luoyunlong/Documents/Tools/AndroidStudio/sdk/build-tools/' (OS Error: Operation not permitted, errno = 1)

#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      AndroidSdk.reinitialize (package:flutter_tools/src/android/android_sdk.dart:334:10)
#5      new AndroidSdk (package:flutter_tools/src/android/android_sdk.dart:38:5)
#6      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:153:12)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#11     androidSdk (package:flutter_tools/src/globals.dart:63:39)
#12     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:121:29)
#13     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#14     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#15     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#16     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#17     androidWorkflow (package:flutter_tools/src/android/android_workflow.dart:28:49)
#18     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:87:11)
#19     Doctor.validators (package:flutter_tools/src/doctor.dart:203:47)
#20     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:209:45)
#21     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:651:60)
#22     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
#23     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:655:71)
#24     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart:648:47)
#25     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart)
#26     CrashReporter.informUser (package:flutter_tools/src/reporting/crash_reporting.dart:92:32)
#27     _handleToolError (package:flutter_tools/runner.dart:166:36)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#29     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b8f7f1f9869bb2d116aa6a70dbeac61000b52849

**Comment by darshankawar** [comment]
OP seems to be on stable 3.3.9 per framework version mentioned above. Keeping this issue open and labeling for team's attention. There have been similar reports but closed due to inactivity.

**Comment by GaryQian** [comment]
@Luoyunlong Can you provide us with the output of `flutter doctor -v`? Thanks!
