### ISSUE TITLE
Crash by Asynchronous Double Platform Result

### ISSUE THREAD

**Issue by suleymanoz** [flutter/flutter#117623]
In our app we use several plugins and platform libraries. We are expriencing some crashes. In order to our app never crash we have followed [Handling all types of errors](https://docs.flutter.dev/testing/errors#handling-all-types-of-errors) section in the document [Handling errors in Flutter](https://docs.flutter.dev/testing/errors).

We handled all Flutter errors and Platform errors:
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  FlutterError.onError = (details) {
    debugPrint('Flutter error caught: ${details.exception}');
    return;
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    debugPrint('Platform error caught: $error, $stack');
    return true;
  };

  runApp(const MyApp());
}
```

## Steps to Reproduce
I have prepared a repro [Flutter 3.3.10 Inevitable Platform Crash](https://github.com/suleymanoz/flutter_3310_inevitable_crash)

![Screenshot_1](https://user-images.githubusercontent.com/34645335/209449754-e5b53b61-daeb-43cd-850c-75bb60b5ea83.png)

"Raise Error" button execute Kotlin code on platform to return an error result:
`result.error("ERROR", "This will be a platform error.", null)`

"Throw Exception" button executes Kotlin code on platform to throw an exception:
`throw Exception("This will be a platform exception.")`

"Test Crash" button executes following Kotlin code to return a delayed asynchronous result 3 seconds after the first result:
```
Log.d("MainActivity", "Test crash")
GlobalScope.launch {
    delay(3000) // delay execution after a while
    result.success("Test crash-1")
}

result.success("Test crash-1")
```
As expected logs show that double reply causes this problem. But `PlatformDispatcher.instance.onError` does not catch this error. Application crashes.
```
I/flutter (12370):
E/AndroidRuntime(12370): FATAL EXCEPTION: DefaultDispatcher-worker-2
E/AndroidRuntime(12370): Process: dev.overtech.inevitable_crash, PID: 12370
E/AndroidRuntime(12370): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(12370):        at k.c$e.a(Unknown Source:35)
E/AndroidRuntime(12370):        at w.i$a$a.b(Unknown Source:14)
E/AndroidRuntime(12370):        at dev.overtech.inevitable_crash.MainActivity$a.invokeSuspend(Unknown Source:41)
E/AndroidRuntime(12370):        at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:13)
E/AndroidRuntime(12370):        at r0.x0.run(Unknown Source:129)
E/AndroidRuntime(12370):        at kotlinx.coroutines.scheduling.a.l(Unknown Source:0)
E/AndroidRuntime(12370):        at kotlinx.coroutines.scheduling.a$c.c(Unknown Source:14)
E/AndroidRuntime(12370):        at kotlinx.coroutines.scheduling.a$c.m(Unknown Source:28)
E/AndroidRuntime(12370):        at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)

Application finished.
```
flutter version is 3.3.10
flutter doctor is clean

**Comment by huycozy** [comment]
@suleymanoz Thanks for reporting the issue. This issue is reproducible on the latest `stable` and `master` channels. Labeling this issue for further investigation from the team.

<details>
<summary>Detailed crash log</summary>

```bash
D/MainActivity(15762): Test crash
E/AndroidRuntime(15762): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(15762): Process: dev.overtech.inevitable_crash, PID: 15762
E/AndroidRuntime(15762): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(15762): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime(15762): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime(15762): 	at dev.overtech.inevitable_crash.MainActivity$configureFlutterEngine$1$1.invokeSuspend(MainActivity.kt:26)
E/AndroidRuntime(15762): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(15762): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(15762): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
E/AndroidRuntime(15762): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/AndroidRuntime(15762): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
E/AndroidRuntime(15762): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
I/Process (15762): Sending signal. PID: 15762 SIG: 9
Lost connection to device.
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-13.0.pre.68, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-13.0.pre.68 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 239f80ed6c (6 hours ago), 2022-12-25 14:48:16 -0500
    • Engine revision 3ae55014ff
    • Dart version 3.0.0 (build 3.0.0-63.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by stuartmorgan** [comment]
The page you linked to is about Dart exceptions. There's no way, in general, to catch every native exception in any native code. If you want custom handling of native exceptions in your own native code you'll need to set up your own handlers. (Note that in some languages, crashes aren't exceptions that can theoretically be caught at all. E.g., if an ObjC iOS plugin has a null pointer deference, it will crash, period.)

Closing as this is the expected behavior; this isn't a Dart exception and isn't subject to Dart exception handling.

**Comment by suleymanoz** [comment]
It is clear that there is no way to handle all exceptions in all languages and all platforms. But for some, if there is a way to do it, it is better to do it.
The repro I prepared contains only code that works from within the JVM. There is not any pure native (non-managed) code.

If we examine the crash stacktrace
```
D/asyncDoubleResult( 8461): Async after delay
E/AndroidRuntime( 8461): FATAL EXCEPTION: Thread-4
E/AndroidRuntime( 8461): Process: dev.overtech.inevitable_crash, PID: 8461
E/AndroidRuntime( 8461): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 8461): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime( 8461): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime( 8461): 	at dev.overtech.inevitable_crash.MainActivity$configureFlutterEngine$1$1.invoke(MainActivity.kt:47)
```
We see that cause of the crash is IllegalStateException. I think this exception is thrown at: (https://github.com/flutter/engine/blob/801559ac4ed3aca67041b4ff76956568856c3807/shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java#L139) 
```
    @Override
    public void reply(@Nullable ByteBuffer reply) {
      if (done.getAndSet(true)) {
        throw new IllegalStateException("Reply already submitted");
      }
      if (reply == null) {
        flutterJNI.invokePlatformMessageEmptyResponseCallback(replyId);
      } else {
        flutterJNI.invokePlatformMessageResponseCallback(replyId, reply, reply.position());
      }
    }
```
I guess before throwing an exception, a thread check must be performed. Such as:
```
if (!Looper.getMainLooper().isCurrentThread()){
  Handler(Looper.getMainLooper()).post {  
      ///
  }
}
```
Maybe there is a better way to make this method thread or async safe. Maybe crashing is already an option but before crashing  application can be notified via `PlatformDispatcher.instance.onError`. If callback returns false crash can be done.

On the other hand, the "**Handling all types of errors**" title in the document increases the expectation a lot. Adding a warning here that not all errors can be stopped by platform will balance expectations.

**Comment by stuartmorgan** [comment]
> On the other hand, the "**Handling all types of errors**" title in the document increases the expectation a lot. Adding a warning here that not all errors can be stopped by platform will balance expectations.

Reopening and retitling to track this as a documentation issue.

**Comment by mcmah309** [comment]
Agree this should be clarified. Also noted that the lack of native exceptions being thrown on the flutter side can cause integration tests to succeed (since the test was exited), when they should have failed. I'd argue that just this alone should warrant some sort of effort to throw exceptions on the flutter side in the languages where it is possible. But reading this thread, it sounds like since it cant be done for some, don't do it for any..

**Comment by dam-ease** [comment]
I am able to reproduce this on the latest `master` and `stable` channels. The crash only occurs on Android devices.

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.6 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • BB55E997-7F31-462D-B3B1-6B177D9B40C7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.13.0-3.0.pre.91, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.13.0-3.0.pre.91 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5a866a031f (9 hours ago), 2023-07-16 17:36:30 -0700
    • Engine revision 683087731f
    • Dart version 3.1.0 (build 3.1.0-315.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • BB55E997-7F31-462D-B3B1-6B177D9B40C7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>
