### ISSUE TITLE
Google Sign In Android

### ISSUE THREAD

**Issue by alexanderpehlivanov** [flutter/flutter#117761]
```
I/flutter (10253): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
I/flutter (10253): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
I/flutter (10253): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
I/flutter (10253): <asynchronous suspension>
I/flutter (10253): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
I/flutter (10253): <asynchronous suspension>
I/flutter (10253): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:273:30)
I/flutter (10253): <asynchronous suspension>
I/flutter (10253): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:407:5)
I/flutter (10253): <asynchronous suspension>
```

**Comment by DevMansoor** [comment]
Have you register SHA fingerprint in firebase?

**Comment by darshankawar** [comment]
Please follow-up in below similar issues:

https://github.com/flutter/flutter/issues/75224
https://github.com/flutter/flutter/issues/33393

Closing this as a duplicate.

**Comment by alexanderpehlivanov** [comment]
I have registered the SHA1 key which I got from my jks signature additionally I have done all the settings to the gradle and manifest files. In the end, I made it work when I put in the Web key instead of the Android key.

**Comment by andvalsol** [comment]
@alexanderpehlivanov can you please tell me how can I do that?

**Comment by alexanderpehlivanov** [comment]
For IOS you will be using OAuth2.0 IOS key
For Android you will be using OAuth2.0 Web key
