### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Operation not supported, errno = 95

### ISSUE THREAD

**Issue by user1121114685** [flutter/flutter#117780]
## Command
```
flutter build linux
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Operation not supported, errno = 95
```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1057:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:987:5)
#6      buildLinux (package:flutter_tools/src/linux/build_linux.dart:67:3)
#7      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:85:11)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.04.1 LTS 5.15.0-56-generic,
    locale en_US.UTF-8)
    • Flutter version 3.3.10 on channel stable at
      /home/shaoxia/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    • Android SDK at /home/shaoxia/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/shaoxia/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.1 LTS 5.15.0-56-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.9+28
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: d9111f64021372856901a1fd5bfbc386cade3318
### Plugins
awesome_notifications-0.7.4+1
file_picker-5.2.4
flutter_plugin_android_lifecycle-2.0.7
package_info_plus-3.0.2
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
r_get_ip-0.1.1
system_alert_window-1.2.1
tobias-2.4.1

**Comment by exaby73** [comment]
Hello @user1121114685. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by user1121114685** [comment]
[flutter_01.log](https://github.com/flutter/flutter/files/10331435/flutter_01.log)
[2.txt](https://github.com/flutter/flutter/files/10331437/2.txt)

`Oops; flutter has exited unexpectedly: "FileSystemException: Cannot create link,
path =
'/mnt/hgfs/flutter_115sha_1/windows/flutter/ephemeral/.plugin_symlinks/awesome_n
otifications' (OS Error: Operation not supported, errno = 95)".
A crash report has been written to /mnt/hgfs/flutter_115sha_1/flutter_01.log.
`

I'm very sorry that I may not be able to provide a separate repro example, but the windows path is mentioned in the error using flutter build linux, is this the correct result?

**Comment by darshankawar** [comment]
Since this is tool_crash issue, there's no need to provide a repro example. Based on the error log, labeling it for team's attention, as there's not a similar existing issue present already. Below could be related:

https://github.com/flutter/flutter/issues/114259

**Comment by Jon4242** [comment]
I believe this happens when you are building Linux and the project is on a mounted Windows file system; the clue is in user1121114685's last comment that mentions "/mnt" and "the windows path is mentioned in the error". I have exactly the same problem.

Making a link on a Windows file system needs to be done differently (the Windows command is "mklink").

**Comment by bkonyi** [comment]
I'm 99% sure the issue here is the attempt to create a symbolic link on an NTFS volume while running on Linux. NTFS handles symbolic links differently than other file system formats, and the Linux APIs used by `dart:io` on Linux probably don't support NTFS volumes. @brianquinlan, can you confirm?

**Comment by brianquinlan** [comment]
Do I understand correctly that the failure occurs on Linux where the file system is NTFS?

**Comment by Jon4242** [comment]
> Do I understand correctly that the failure occurs on Linux where the file system is NTFS?

Yes, exactly. The link is attempting to be made on a mounted Windows NTFS folder/directory. In my case I build on both platforms and like to have a single copy of the checked out files on Windows, so I mount the whole project folder/directory on Linux.
