### ISSUE TITLE
Uncaught LateInitializationError: Field '' has not been initialized

### ISSUE THREAD

**Issue by FlorianFlatscher** [flutter/flutter#117880]
I get the following error message in the browser in production:

```
main.dart.js:4949 

Uncaught LateInitializationError: Field '' has not been initialized. 
    at Object.c (main.dart.js:4949:3)
    at Object.q (main.dart.js:4956:14)
    at Object.a (main.dart.js:5327:14)
    at Ud.vw (main.dart.js:45327:10)
    at Ud.gll (main.dart.js:45322:28)
    at a1s.a50 (main.dart.js:68217:32)
    at a1s.kq (main.dart.js:78891:18)
    at a1s.ahz (main.dart.js:56140:3)
    at Object.aXs (main.dart.js:20690:3)
    at aTy.$0 (main.dart.js:137912:16)
```

Meanwhile the app is stuck on the splash screen.

The weird thing is that this error only appears when I serve the generated files from `flutter build web`. I am unable to reproduce it with `flutter run` locally. 

How can it happen that I get a LateInitializationError on Field ''?

![image](https://user-images.githubusercontent.com/47723555/210264437-9ebafb78-3523-4f00-9b7b-9c5577213b69.png)

**Comment by FlorianFlatscher** [comment]
Closing this issue as it is a recent issue with the package mobile_scanner: 

https://github.com/juliansteenbakker/mobile_scanner/issues/437
