### ISSUE TITLE
flutter engine throws PlatformException

### ISSUE THREAD

**Issue by AballahEhab** [flutter/flutter#117894]
when requesting permission for location and the permission is already denied forever

the resulting log:
```
D/EGL_emulation(19525): app_time_stats: avg=211.82ms min=29.01ms max=542.19ms count=6
D/CompatibilityChangeReporter(19525): Compat change id reported: 78294732; UID 10170; state: DISABLED
E/flutter (19525): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(permission_denied, Permission Request Denied By User., [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION], null)
E/flutter (19525): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (19525): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (19525): <asynchronous suspension>
E/flutter (19525): 
D/AndroidRuntime(19525): Shutting down VM
E/AndroidRuntime(19525): FATAL EXCEPTION: main
E/AndroidRuntime(19525): Process: com.creditor.anuta.retailer, PID: 19525
E/AndroidRuntime(19525): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=109, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.creditor.anuta.retailer/com.creditor.anuta.retailer.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(19525): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5323)
E/AndroidRuntime(19525): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5362)
E/AndroidRuntime(19525): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(19525): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(19525): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(19525): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(19525): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/AndroidRuntime(19525): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19525): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(19525): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(19525): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(19525): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19525): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(19525): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(19525): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(19525): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime(19525): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:272)
E/AndroidRuntime(19525): 	at com.shounakmulay.telephony.sms.SmsMethodCallHandler.onPermissionDenied(SmsMethodCallHandler.kt:383)
E/AndroidRuntime(19525): 	at com.shounakmulay.telephony.sms.SmsMethodCallHandler.onRequestPermissionsResult(SmsMethodCallHandler.kt:377)
E/AndroidRuntime(19525): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(19525): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(19525): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:757)
E/AndroidRuntime(19525): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime(19525): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8774)
E/AndroidRuntime(19525): 	at android.app.Activity.dispatchActivityResult(Activity.java:8632)
E/AndroidRuntime(19525): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5316)
```

**Comment by AballahEhab** [comment]
flutter doctor 

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
