### ISSUE TITLE
WebView.destroy() called while WebView is still attached to window. Potential memory leak?

### ISSUE THREAD

**Issue by davidhicks980** [flutter/flutter#117887]
## Steps to Reproduce

1. Toggle the "Show Webview" button multiple times and look at console

## Logs

<details>
<summary>Logs</summary>

```
  +34 ms] Syncing files to device sdk gphone64 arm64...
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:bug/main.dart de4b6503-955f-4203-9010-2f89509c83a8
[        ] <- de4b6503-955f-4203-9010-2f89509c83a8
[        ] Bundle processing done.
[  +49 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device sdk gphone64 arm64... (completed in 51ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms]



 Connected to _flutterView/0xb400007dcd0018d0.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on sdk gphone64 arm64 is available at:
           http://127.0.0.1:63233/V7HZcV8YcOI=/
[ +124 ms] The Flutter DevTools debugger and profiler on sdk gphone64 arm64 is available at:
                    http://127.0.0.1:9101?uri=http://127.0.0.1:63233/V7HZcV8YcOI=/
[+18598 ms] I/WebViewFactory( 7242): Loading com.google.android.webview version 91.0.4472.114 (code
447211484)
[   +4 ms] D/nativeloader( 7242): Configuring classloader-namespace for other apk
/data/app/~~ctsuX7JjAntmd9A-GA0A1Q==/com.google.android.trichromelibrary_447211484-P_aLjgq6UA1BWC9Mf5crpw=
=/TrichromeLibrary.apk. target_sdk_version=31, uses_libraries=ALL,
library_path=/data/app/~~SXF7BX-3hyYesN7iQ_yoVA==/com.google.android.webview-FAbofLmMthUGtgorbIQ8tQ==/lib/
arm64:/data/app/~~SXF7BX-3hyYesN7iQ_yoVA==/com.google.android.webview-FAbofLmMthUGtgorbIQ8tQ==/WebViewGoog
le.apk!/lib/arm64-v8a:/data/app/~~ctsuX7JjAntmd9A-GA0A1Q==/com.google.android.trichromelibrary_447211484-P
_aLjgq6UA1BWC9Mf5crpw==/TrichromeLibrary.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
[   +2 ms] D/nativeloader( 7242): Configuring classloader-namespace for other apk
/data/app/~~SXF7BX-3hyYesN7iQ_yoVA==/com.google.android.webview-FAbofLmMthUGtgorbIQ8tQ==/WebViewGoogle.apk
. target_sdk_version=31, uses_libraries=,
library_path=/data/app/~~SXF7BX-3hyYesN7iQ_yoVA==/com.google.android.webview-FAbofLmMthUGtgorbIQ8tQ==/lib/
arm64:/data/app/~~SXF7BX-3hyYesN7iQ_yoVA==/com.google.android.webview-FAbofLmMthUGtgorbIQ8tQ==/WebViewGoog
le.apk!/lib/arm64-v8a:/data/app/~~ctsuX7JjAntmd9A-GA0A1Q==/com.google.android.trichromelibrary_447211484-P
_aLjgq6UA1BWC9Mf5crpw==/TrichromeLibrary.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
[  +35 ms] W/com.example.bu( 7242): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z
(unsupported, reflection, allowed)
[        ] W/com.example.bu( 7242): Accessing hidden method
Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
[        ] W/com.example.bu( 7242): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported,
reflection, allowed)
[        ] W/com.example.bu( 7242): Accessing hidden method
Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
[        ] W/com.example.bu( 7242): Accessing hidden method
Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
[  +12 ms] I/cr_LibraryLoader( 7242): Loaded native library version number "91.0.4472.114"
[        ] I/cr_CachingUmaRecorder( 7242): Flushed 6 samples from 6 histograms.
[  +90 ms] W/chromium( 7242): [WARNING:dns_config_service_android.cc(153)] Failed to read DnsConfig.
[  +20 ms] D/CompatibilityChangeReporter( 7242): Compat change id reported: 171228096; UID 10146; state:
ENABLED
[  +14 ms] W/com.example.bu( 7242): Accessing hidden method
Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
[   +1 ms] D/HostConnection( 7242): createUnique: call
[        ] D/HostConnection( 7242): HostConnection::get() New Host Connection established
0xb400007d2cfdd550, tid 7365
[   +1 ms] W/cr_media( 7242): Requires BLUETOOTH permission
[        ] D/HostConnection( 7242): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1
ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1
ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan
ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings
ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache
ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator
ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8
ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands
ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3
GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing
ANDROID_EMU_gles_max_version_3_0 
[        ] D/EGL_emulation( 7242): eglCreateContext: 0xb400007d2cfdf7d0: maj 3 min 0 rcv 3
[        ] D/EGL_emulation( 7242): eglMakeCurrent: 0xb400007d2cfdf7d0: ver 3 0 (tinfo 0x7f5f7ab280) (first
time)
[   +2 ms] I/PlatformViewsController( 7242): Hosting view in view hierarchy for platform view: 0
[   +4 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[   +5 ms] D/EGL_emulation( 7242): eglCreateContext: 0xb400007d2cfdda90: maj 3 min 0 rcv 3
[  +28 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[   +9 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +16 ms] D/EGL_emulation( 7242): eglCreateContext: 0xb400007d2cfde390: maj 3 min 0 rcv 3
[ +145 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[+1048 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[        ] D/EGL_emulation( 7242): app_time_stats: avg=313.02ms min=7.98ms max=1048.29ms count=4
[   +2 ms] D/EGL_emulation( 7242): app_time_stats: avg=5001.14ms min=6.31ms max=18792.68ms count=4
[   +3 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +11 ms] D/EGL_emulation( 7242): app_time_stats: avg=643.41ms min=1.56ms max=18440.10ms count=31
[        ] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +15 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +15 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +15 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +15 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +15 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[  +15 ms] E/FrameEvents( 7242): updateAcquireFence: Did not find frame.
[ +801 ms] D/EGL_emulation( 7242): app_time_stats: avg=50.84ms min=12.77ms max=704.11ms count=20
[  +42 ms] W/cr_AwContents( 7242): WebView.destroy() called while WebView is still attached to window.
[  +23 ms] D/EGL_emulation( 7242): app_time_stats: avg=58.04ms min=3.70ms max=853.02ms count=16
[+121662 ms] Application finished.

(base) bug flutter analyze
Analyzing bug...                                                        
No issues found! (ran in 1.6s)

(base) bug flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.2.1 21D62 darwin-arm, locale en-US)
    • Flutter version 3.3.10 on channel stable at /Users/davidhicks/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/davidhicks/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/davidhicks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.57.20221221

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/59215665/210310539-d5efd6ca-47e0-437e-ae69-ccc5644c04c4.mov

I have limited knowledge of Android, but it appears others on the web have pointed this causing [memory leaks in their applications](https://stackoverflow.com/questions/11995270/error-webview-destroy-called-while-still-attached). I'm not sure of the validity of this claim, but I wanted to bring it to your attention regardless. Thanks!

**Comment by danagbemava-nc** [comment]
Issue is reproducible using the code sample provided above. Labeling for further insight from the team

<details>
<summary>logs</summary>

```
Launching lib/main.dart on M2007J20CG in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:65348/GGs2Rp7SNPs=/ws
E/com.example.tt(16210): open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
D/DecorView[](16210): onWindowFocusChanged hasWindowFocus true
W/ziparchive(16210): Unable to open '/data/app/~~IpZVEvAZbk3HPces-JWqfA==/com.google.android.trichromelibrary_535912833-CdGQJYEj2v0PbRIKJZzKzw==/base.dm': No such file or directory
W/ziparchive(16210): Unable to open '/data/app/~~IpZVEvAZbk3HPces-JWqfA==/com.google.android.trichromelibrary_535912833-CdGQJYEj2v0PbRIKJZzKzw==/base.dm': No such file or directory
W/com.example.tt(16210): Entry not found
D/nativeloader(16210): Configuring classloader-namespace for other apk /data/app/~~IpZVEvAZbk3HPces-JWqfA==/com.google.android.trichromelibrary_535912833-CdGQJYEj2v0PbRIKJZzKzw==/base.apk. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~AiHeU7n_wMCDk2HPxyra7g==/com.google.android.webview-boygCbwNyys8mFdJn5oUZg==/lib/arm64:/data/app/~~AiHeU7n_wMCDk2HPxyra7g==/com.google.android.webview-boygCbwNyys8mFdJn5oUZg==/base.apk!/lib/arm64-v8a:/data/app/~~IpZVEvAZbk3HPces-JWqfA==/com.google.android.trichromelibrary_535912833-CdGQJYEj2v0PbRIKJZzKzw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
D/nativeloader(16210): Extending system_exposed_libraries: libvraudio_client.qti.so:libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libcamera_algoup_jni.xiaomi.so:libcamera_mianode_jni.xiaomi.so:libupdateprof.qti.so:libthermalclient.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:libqesdk_ndk_platform.qti.so:liblistenjni.qti.so
D/nativeloader(16210): Configuring classloader-namespace for other apk /data/app/~~AiHeU7n_wMCDk2HPxyra7g==/com.google.android.webview-boygCbwNyys8mFdJn5oUZg==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~AiHeU7n_wMCDk2HPxyra7g==/com.google.android.webview-boygCbwNyys8mFdJn5oUZg==/lib/arm64:/data/app/~~AiHeU7n_wMCDk2HPxyra7g==/com.google.android.webview-boygCbwNyys8mFdJn5oUZg==/base.apk!/lib/arm64-v8a:/data/app/~~IpZVEvAZbk3HPces-JWqfA==/com.google.android.trichromelibrary_535912833-CdGQJYEj2v0PbRIKJZzKzw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
I/WebViewFactory(16210): Loading com.google.android.webview version 108.0.5359.128 (code 535912833)
W/com.example.tt(16210): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/com.example.tt(16210): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/com.example.tt(16210): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/com.example.tt(16210): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/com.example.tt(16210): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_WVCFactoryProvider(16210): Loaded version=108.0.5359.128 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(16210): Successfully loaded native library
I/cr_CachingUmaRecorder(16210): Flushed 9 samples from 9 histograms.
W/chromium(16210): [WARNING:dns_config_service_android.cc(115)] Failed to read DnsConfig.
E/chromium(16210): [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/com.example.tt/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
E/chromium(16210): [ERROR:simple_index_file.cc(614)] Could not reconstruct index from disk
D/CompatibilityChangeReporter(16210): Compat change id reported: 171228096; UID 10026; state: ENABLED
W/com.example.tt(16210): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
W/cr_media(16210): BLUETOOTH_CONNECT permission is missing.
W/cr_media(16210): registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
I/PlatformViewsController(16210): Hosting view in view hierarchy for platform view: 0
E/FrameEvents(16210): updateAcquireFence: Did not find frame.
W/chromium(16210): [WARNING:display_webview.cc(31)] WebView overlays are enabled!
E/FrameEvents(16210): updateAcquireFence: Did not find frame.
E/FrameEvents(16210): updateAcquireFence: Did not find frame.
E/FrameEvents(16210): updateAcquireFence: Did not find frame.
W/cr_AwContents(16210): WebView.destroy() called while WebView is still attached to window.
I/PlatformViewsController(16210): Hosting view in view hierarchy for platform view: 1
E/FrameEvents(16210): updateAcquireFence: Did not find frame.
W/chromium(16210): [WARNING:display_webview.cc(31)] WebView overlays are enabled!
E/FrameEvents(16210): updateAcquireFence: Did not find frame.
E/FrameEvents(16210): updateAcquireFence: Did not find frame.
E/FrameEvents(16210): updateAcquireFence: Did not find frame.
W/cr_AwContents(16210): WebView.destroy() called while WebView is still attached to window.
W/chromium(16210): [WARNING:spdy_session.cc(3487)] Received HEADERS for invalid stream 1
Application finished.
Exited
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-GB)
    • Flutter version 3.3.10 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • adb-5dd3be00-22GXB2._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • macOS (desktop)     • macos                                      • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)        • chrome                                     • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.7.0-13.0.pre.138, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
    • Flutter version 3.7.0-13.0.pre.138 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b938dc13df (22 hours ago), 2023-01-02 05:47:23 -0500
    • Engine revision 472e34cbbc
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • adb-5dd3be00-22GXB2._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • macOS (desktop)     • macos                                      • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)        • chrome                                     • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

``	`
</details>

**Comment by davidhicks980** [comment]
I should add that I also get this warning on an application I unfortunately cannot share. I was unable to reproduce the issue:

```dart
W/cr_AwContents( 8582): Application attempted to call on a destroyed WebView
W/cr_AwContents( 8582): java.lang.Throwable
W/cr_AwContents( 8582):         at org.chromium.android_webview.AwContents.r(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:2)
W/cr_AwContents( 8582):         at org.chromium.android_webview.AwContents.j(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:1)
W/cr_AwContents( 8582):         at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:8)
W/cr_AwContents( 8582):         at android.webkit.WebView.evaluateJavascript(WebView.java:893)
W/cr_AwContents( 8582):         at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.evaluateJavascript(WebViewHostApiImpl.java:337)
W/cr_AwContents( 8582):         at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$12(GeneratedAndroidWebView.java:1023)
W/cr_AwContents( 8582):         at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda19.onMessage(Unknown Source:2)
W/cr_AwContents( 8582):         at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
W/cr_AwContents( 8582):         at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/cr_AwContents( 8582):         at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/cr_AwContents( 8582):         at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/cr_AwContents( 8582):         at android.os.Handler.handleCallback(Handler.java:938)
W/cr_AwContents( 8582):         at android.os.Handler.dispatchMessage(Handler.java:99)
W/cr_AwContents( 8582):         at android.os.Looper.loopOnce(Looper.java:201)
W/cr_AwContents( 8582):         at android.os.Looper.loop(Looper.java:288)
W/cr_AwContents( 8582):         at android.app.ActivityThread.main(ActivityThread.java:7839)
W/cr_AwContents( 8582):         at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents( 8582):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/cr_AwContents( 8582):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
This occurs after I hide the WebView widget.

**Comment by bparrishMines** [comment]
This looks like this is caused by a bug in the engine:

The engine is calling `PlatformView.dispose` before the platform is actually removed from the window:
Where `dispose` is called: https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L238
Where the platform view is being removed from window: https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L262
I verified this is correct because you would get the same error in pre-4.0 versions of `webview_flutter_android`.

Although, this also highlights that we shouldn't be calling `destroy` in the new Android implementation because a `WebViewController` can be reused in a new `WebViewWidget`. And this could cause a similar error.

**Comment by stuartmorgan** [comment]
Thanks, adjusting labels accordingly!

**Comment by apremalal** [comment]
Is there a workaround that can be used till it get fixed?

**Comment by Max-Job** [comment]
any news?

**Comment by Max-Job** [comment]
It is impolite to mark a post asking for a possible solution as off-topic.
let me repeat - any news how to fix this?

**Comment by stuartmorgan** [comment]
@Max-Job It is not impolite to enforce our [clearly documented policies](https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs):

> Do not add "me too" or "same" or "is there an update" comments to bugs

**Comment by Max-Job** [comment]
> @Max-Job It is not impolite to enforce our [clearly documented policies](https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs):

ok, I got it. but could you clarify if there is a workaround or when we can expect a fix?

**Comment by stuartmorgan** [comment]
> could you clarify if there is a workaround

That was already asked above, in the last comment. Posting the same question a second time isn't constructive.

> or when we can expect a fix?

Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed

**Comment by zonda-alias** [comment]
@davidhicks980 我这 Android 端使用了WebViewFlutterAndroidExternalApi.getWebView 好像可以解决

``` kotlin FlutterNativeBridge.mEngine?.also { flutterEngine ->
    FlutterNativeBridge.invokeFlutterWebViewIdentifierList { webViewIds ->
        webViewIds.forEach { identifier ->
            WebViewFlutterAndroidExternalApi.getWebView(flutterEngine, identifier)
                ?.also { webView ->
                    ULog.i("ToFlutterContainerActivity in webView.destroy: $identifier")
                   // webView.destroy()
                    if(webView.parent is ViewGroup){
                        ULog.i("ToFlutterContainerActivity in webView.removeView: $identifier")
                        (webView.parent as ViewGroup).removeView(webView)
                        webView.destroy()
                    }
                }
        }
    }
}
`
