### ISSUE TITLE
Moving/Resizing Windows app using AltSnap causes exceptions

### ISSUE THREAD

**Issue by ricardoboss** [flutter/flutter#117825]
## Steps to Reproduce

1. Install [AltSnap](https://github.com/RamonUnch/AltSnap) on Windows
2. Execute `flutter run` on the code sample 
3. While holding the alt key, move the app window using left click or resize using right click

**Expected results:** App window gets moved/resized.

**Actual results:** Multiple errors in console and the app crashing.

<details>
<summary>Code sample</summary>

```dart
// main.dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

Only relevant log message for brevity. This exception gets printed a few hundred times every time I use AltSnap.

```
[+1906 ms] 
                    ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following assertion was thrown during a platform message callback:
                    A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this
                    occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please
                    ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This
                    was the event: KeyRepeatEvent#93bbe(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage:
                    "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104",
                    keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 10:34:29.965711)
                    'package:flutter/src/services/hardware_keyboard.dart':
                    Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md

                    When the exception was thrown, this was the stack:
                    #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
                    #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
                    #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
                    #5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:881:37)
                    #6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
                    #7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
                    #8      _invoke2 (dart:ui/hooks.dart:186:13)
                    #9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
                    #10     _Channel.push (dart:ui/channel_buffers.dart:132:31)
                    #11     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
                    #12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
                    #13     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
                    (elided 2 frames from class _AssertionError)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
No issues found!
```

```
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.963], locale de-DE)
    • Flutter version 3.3.10 on channel stable at S:\repos\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at C:\Users\ricar\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = C:\Users\ricar\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\ricar\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.11.32901.82
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Users\ricar\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.2)
    • Android Studio at C:\Users\ricar\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\222.4459.24.2221.9409768
    • Flutter plugin version 71.2.5
    • Dart plugin version 222.4459.16
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.74.1)
    • VS Code at C:\Users\ricar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.963]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.103
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @ricardoboss 
Looking at the error log, it is similar to another [open issue](https://github.com/flutter/flutter/issues/107972) describing same case, it, using `alt` key which throws the same error as reported, so I suggest you to please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
