### ISSUE TITLE
Failing to render asked to report assertion.

### ISSUE THREAD

**Issue by peter-allday** [flutter/flutter#117895]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

```
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderViewport#eefa0 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2001 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  ListView ListView:file:///Users/peter/Library/CloudStorage/OneDrive-Personal/AndroidStudioProjects/games_night_planner/lib/games_list.dart:39:13
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2001:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:121:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#8      RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#14     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#17     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#20     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#23     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#25     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:552:11)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#27     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#30     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#31     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#32     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:836:43)
#33     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:938:32)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#36     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:249:12)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#39     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#40     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1055:7)
#41     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#42     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410:14)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#47     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#49     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1462:11)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#54     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#57     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#63     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#66     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#69     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#72     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#75     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#78     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#81     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#84     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#87     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#89     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#90     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#92     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#93     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#96     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#99     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#100    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3735:14)
#101    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#102    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#105    RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#106    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:804:15)
#107    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1973:7)
#108    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:999:18)
#109    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:513:19)
#110    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#111    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#112    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#113    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#114    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#115    _invoke (dart:ui/hooks.dart:148:13)
#116    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#117    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderIgnorePointer#5eef0 relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...  size: MISSING
...  ignoring: false
...  ignoringSemantics: false
RenderObject: RenderIgnorePointer#5eef0 relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
  size: MISSING
  ignoring: false
  ignoringSemantics: false
...  child: RenderViewport#eefa0 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...    size: MISSING
...    axisDirection: down
...    crossAxisDirection: right
...    offset: ScrollPositionWithSingleContext#21569(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#ba5c8, ScrollDirection.idle)
...    anchor: 0.0
...    center child: RenderSliverPadding#ca452 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: paintOffset=Offset(0.0, 0.0)
...      constraints: MISSING
...      geometry: null
...      padding: EdgeInsets.zero
...      textDirection: ltr
...      child: RenderSliverList#1456e NEEDS-LAYOUT NEEDS-PAINT
...        parentData: paintOffset=Offset(0.0, 0.0)
...        constraints: MISSING
...        geometry: null
...        no children current live
====================================================================================================
D/TrafficStats( 7013): tagSocket(139) with statsTag=0xffffffff, statsUid=-1
W/s_night_planner( 7013): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (unsupported, reflection, allowed)

This then repeats several times. followed by

The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#139fc NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=392.7, h=826.9)
...  size: Size(392.7, 826.9)
RenderObject: RenderCustomMultiChildLayoutBox#139fc NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=392.7, h=826.9)
  size: Size(392.7, 826.9)
...  child 1: RenderPadding#39232 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...    constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=746.9)
...    size: MISSING
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: RenderFlex#d3f92 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=746.9)
...      size: MISSING
...      direction: vertical
...      mainAxisAlignment: start
...      mainAxisSize: max
...      crossAxisAlignment: center
...      verticalDirection: down
...      child 1: RenderErrorBox#0cd09 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...        size: Size(392.7, 100000.0)
...      child 2: RenderRepaintBoundary#43981 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...        size: MISSING
...        usefulness ratio: no metrics collected yet (never painted)
...        child: RenderCustomPaint#9e24b relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...          size: MISSING
...          painter: null
...          foregroundPainter: _GlowingOverscrollIndicatorPainter(_GlowController(color: Color(0xff2196f3), axis: vertical), _GlowController(color: Color(0xff2196f3), axis: vertical))
...  child 2: RenderConstrainedBox#5a365 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.appBar (can use size)
...    constraints: BoxConstraints(w=392.7, 0.0<=h<=826.9)
...    size: Size(392.7, 80.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=80.0)
...    child: RenderSemanticsAnnotations#630a8 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=392.7, 0.0<=h<=80.0)
...      semantic boundary
...      size: Size(392.7, 80.0)
...      child: RenderAnnotatedRegion<SystemUiOverlayStyle>#32939 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=392.7, 0.0<=h<=80.0)
...        size: Size(392.7, 80.0)
...        child: RenderPhysicalModel#e0656 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=392.7, 0.0<=h<=80.0)
...          size: Size(392.7, 80.0)
...          elevation: 4.0
...          color: MaterialColor(primary value: Color(0xff2196f3))
...          shadowColor: MaterialColor(primary value: Color(0xff2196f3))
...          shape: BoxShape.rectangle
...          borderRadius: BorderRadius.zero
...  child 3: RenderStack#570b9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.floatingActionButton
...    constraints: MISSING
...    size: MISSING
...    alignment: Alignment.centerRight
...    textDirection: ltr
...    fit: loose
...    child 1: RenderTransform#fa6d0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: not positioned; offset=Offset(0.0, 0.0)
...      constraints: MISSING
...      size: MISSING
...      transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...      origin: null
...      alignment: Alignment.center
...      textDirection: ltr
...      transformHitTests: true
...      child: RenderTransform#d92d3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        transform matrix: [0] 1.0,0.0,0.0,0.0
[1] -0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: Alignment.center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderMergeSemantics#677e1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          semantic boundary
...          size: MISSING
```

**Comment by darshankawar** [comment]
Thanks for the report @peter-allday 
Although the stack trace has a link to report the assertion and looking at it, it does seem to be coming from framework itself, but we would need a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) as mentioned in the link, that will help us to properly identify the root-cause of the assertion.

Also, from the error log, it seems to be pointing to `ListView` you might be using:



> The relevant error-causing widget was: 
>   ListView ListView

So you'll probably need to check if the assertion is occuring due to code implementation or not. Also, [this](https://github.com/flutter/flutter/issues/82055) issue seems similar / related that you can check for your reference.

If you are able to provide a minimal code sample, it would be great to make this issue actionable.
