### ISSUE TITLE
[flutter_tools] _CastError in WebPlugin.fromYaml

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#117926]
on `beta/3.7.0-1.2.pre`

```
_CastError: type 'Null' is not a subtype of type 'String' in type cast
at new WebPlugin.fromYaml(platform_plugins.dart:548)
at new Plugin._fromMultiPlatformYaml(plugins.dart:142)
at new Plugin.fromYaml(plugins.dart:78)
at _pluginFromPackage(flutter_plugins.dart:63)
at findPlugins(flutter_plugins.dart:88)
at <asynchronous gap>(async)
at refreshPluginsList(flutter_plugins.dart:1080)
at <asynchronous gap>(async)
at FlutterProject.ensureReadyForPlatformSpecificTooling(project.dart:357)
at <asynchronous gap>(async)
at PackagesGetCommand.runCommand(packages.dart:179)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1257)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:283)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:229)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:64)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:91)
at <asynchronous gap>(async)
```

**Comment by krishh-apnaklub** [comment]
I am still getting this error in the latest stable version (v3.7.3) of the Flutter SDK.

## Command
```
flutter pub get
```

## Steps to Reproduce
1. Open Terminal
2. Execute `flutter pub get` command.

## Logs
_CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))
```
#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34)
#1      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:142:21)
#2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:78:21)
#3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#5      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:179:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[32m[✓] [39m Flutter (Channel stable, 3.7.3, on macOS 13.2 22D49
    darwin-arm64, locale en-IN)
     [32m• [39m Flutter version 3.7.3 on channel stable at /Users/user/tools/flutter-arm64
     [32m• [39m Upstream repository https://github.com/flutter/flutter.git
     [32m• [39m Framework revision 9944297138 (30 hours ago), 2023-02-08 15:46:04 -0800
     [32m• [39m Engine revision 248290d6d5
     [32m• [39m Dart version 2.19.2
     [32m• [39m DevTools version 2.20.1

 [32m[✓] [39m Android toolchain - develop for Android devices (Android SDK version 33.0.1)
     [32m• [39m Android SDK at /Users/krishh/Library/Android/sdk
     [32m• [39m Platform android-33, build-tools 33.0.1
     [32m• [39m ANDROID_HOME = /Users/krishh/Library/Android/sdk
     [32m• [39m Java binary at: /Users/krishh/Library/ApplicationSupport/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/AndroidStudio.app/Contents/jre/Contents/Home/bin/java
     [32m• [39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
     [32m• [39m All Android licenses accepted.

 [32m[✓] [39m Xcode - develop for iOS and macOS (Xcode 14.2)
     [32m• [39m Xcode at /Applications/Xcode.app/Contents/Developer
     [32m• [39m Build 14C18
     [32m• [39m CocoaPods version 1.11.3

 [32m[✓] [39m Chrome - develop for the web
     [32m• [39m Chrome at /Applications/GoogleChrome.app/Contents/MacOS/Google Chrome

 [32m[✓] [39m Android Studio (version 2022.1)
     [32m• [39m Android Studio at /Users/krishh/Library/ApplicationSupport/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents
     [32m• [39m Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter
     [32m• [39m Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart
     [32m• [39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

 [32m[✓] [39m Android Studio (version 2022.1)
     [32m• [39m Android Studio at /Users/krishh/Library/ApplicationSupport/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
     [32m• [39m Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter
     [32m• [39m Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart
     [32m• [39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

 [32m[✓] [39m VS Code (version 1.72.1)
     [32m• [39m VS Code at /Applications/Visual Studio Code.app/Contents
     [32m• [39m Flutter extension version 3.52.0

 [32m[✓] [39m Connected device (2 available)
     [32m• [39m macOS (desktop) • macos  • darwin-arm64   • macOS 13.222D49 darwin-arm64
     [32m• [39m Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.77

 [32m[✓] [39m HTTP Host Availability
     [32m• [39m All required HTTP hosts are available

 [32m• [39m No issues found!
```

## Flutter Application Metadata
**Type**: app
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03

**Comment by christopherfujino** [comment]
> I have just upgraded the Flutter SDK from v3.3.7 to v3.7.3. I am still getting this error in the latest stable version (v3.7.3).
> 
> ## Command
> ```
> flutter pub get
> ```
> 
> ## Steps to Reproduce
> 1. Open Terminal
> 2. Execute `flutter pub get` command.
> 
> ## Logs
> _CastError: (#0 new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))
> 
> ```
> #0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34)
> #1      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:142:21)
> #2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:78:21)
> #3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
> #4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
> <asynchronous suspension>
> #5      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
> <asynchronous suspension>
> #6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
> <asynchronous suspension>
> #7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:179:5)
> <asynchronous suspension>
> #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
> <asynchronous suspension>
> #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> <asynchronous suspension>
> #10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
> <asynchronous suspension>
> #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
> <asynchronous suspension>
> #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> <asynchronous suspension>
> #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
> <asynchronous suspension>
> #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
> ```
> 
> ```
> [32m[✓] [39m Flutter (Channel stable, 3.7.3, on macOS 13.2 22D49
>     darwin-arm64, locale en-IN)
>      [32m• [39m Flutter version 3.7.3 on channel stable at /Users/user/tools/flutter-arm64
>      [32m• [39m Upstream repository https://github.com/flutter/flutter.git
>      [32m• [39m Framework revision 9944297138 (30 hours ago), 2023-02-08 15:46:04 -0800
>      [32m• [39m Engine revision 248290d6d5
>      [32m• [39m Dart version 2.19.2
>      [32m• [39m DevTools version 2.20.1
> 
>  [32m[✓] [39m Android toolchain - develop for Android devices (Android SDK version 33.0.1)
>      [32m• [39m Android SDK at /Users/user/Library/Android/sdk
>      [32m• [39m Platform android-33, build-tools 33.0.1
>      [32m• [39m ANDROID_HOME = /Users/user/Library/Android/sdk
>      [32m• [39m Java binary at: /Users/user/Library/ApplicationSupport/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/AndroidStudio.app/Contents/jre/Contents/Home/bin/java
>      [32m• [39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
>      [32m• [39m All Android licenses accepted.
> 
>  [32m[✓] [39m Xcode - develop for iOS and macOS (Xcode 14.2)
>      [32m• [39m Xcode at /Applications/Xcode.app/Contents/Developer
>      [32m• [39m Build 14C18
>      [32m• [39m CocoaPods version 1.11.3
> 
>  [32m[✓] [39m Chrome - develop for the web
>      [32m• [39m Chrome at /Applications/GoogleChrome.app/Contents/MacOS/Google Chrome
> 
>  [32m[✓] [39m Android Studio (version 2022.1)
>      [32m• [39m Android Studio at /Users/user/Library/ApplicationSupport/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents
>      [32m• [39m Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>      [32m• [39m Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart
>      [32m• [39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
> 
>  [32m[✓] [39m Android Studio (version 2022.1)
>      [32m• [39m Android Studio at /Users/user/Library/ApplicationSupport/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
>      [32m• [39m Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>      [32m• [39m Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart
>      [32m• [39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
> 
>  [32m[✓] [39m VS Code (version 1.72.1)
>      [32m• [39m VS Code at /Applications/Visual Studio Code.app/Contents
>      [32m• [39m Flutter extension version 3.52.0
> 
>  [32m[✓] [39m Connected device (2 available)
>      [32m• [39m macOS (desktop) • macos  • darwin-arm64   • macOS 13.222D49 darwin-arm64
>      [32m• [39m Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.77
> 
>  [32m[✓] [39m HTTP Host Availability
>      [32m• [39m All required HTTP hosts are available
> 
>  [32m• [39m No issues found!
> ```
> 
> ## Flutter Application Metadata
> **Type**: app **Creation channel**: stable **Creation framework version**: [f4abaa0](https://github.com/flutter/flutter/commit/f4abaa0735eba4dfd8f33f73363911d63931fe03)
> 
> For now, I have downgraded to v3.3.10 and it is working fine.

So, the fix for this was merged to master, but has not yet reached stable. However, the "fix", as you can see here: https://github.com/flutter/flutter/pull/117939/files, was just to throw a more specific error. I'm guessing that a plugin is missing the `fileName` field, and the tool is now being more strict. You can temporarily check out the `master` channel, run `flutter pub get` on your app, and have the tool report exactly what you need to fix.
