### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by icgoogo** [flutter/flutter#117988]
## Command
```
flutter run --flavor dev -t lib/main_dev.dart
```

## Steps to Reproduce
1. execute the command on terminal 
2. wait until `💪 Running with sound null safety 💪` message appears
3. press j button on your keyboard
4. RPC error appears

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2233:14)
#3      VmService.callMethod (package:vm_service/src/vm_service.dart:2215:12)
#4      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:463:28)
#5      FlutterVmService.renderFrameWithRasterStats (package:flutter_tools/src/vmservice.dart:562:49)
#6      ResidentHandlers.debugFrameJankMetrics (package:flutter_tools/src/resident_runner.dart:691:35)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1739:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale es-ID)
    • Flutter version 3.3.10 on channel stable at /Users/hammadsyr/Hammad/JadiAnakIT/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/hammadsyr/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/hammadsyr/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.2.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.2.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • CPH1803 (mobile) • 39f81776 • android-arm64  • Android 8.1.0 (API 27)
    • macOS (desktop)  • macos    • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.1.0+55
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
app_settings-4.1.8
audio_session-0.1.11
camera-0.10.0+4
camera_android
camera_avfoundation-0.9.8+6
camera_web-0.3.0+1
cloud_firestore_web-3.1.0
connectivity_plus-3.0.2
firebase_analytics-10.0.6
firebase_analytics_web-0.5.1+5
firebase_core-2.3.0
firebase_core_web-2.0.1
firebase_crashlytics-3.0.6
firebase_messaging-14.1.1
firebase_messaging_web-3.2.7
firebase_remote_config-3.0.6
firebase_remote_config_web-1.1.15
flutter_local_notifications-12.0.4
flutter_native_timezone-e975c46ecb481dd67c98f1832f13df83776d8521
flutter_plugin_android_lifecycle-2.0.7
fluttertoast-8.1.1
geocoding-2.0.5
geolocator-9.0.2
geolocator_android-4.1.4
geolocator_apple-2.2.3
geolocator_web-2.1.6
geolocator_windows-0.1.1
http_certificate_pinning-2.0.6
integration_test
just_audio-0.9.30
just_audio_web-0.4.7
package_info_plus-3.0.2
path_provider-2.0.11
path_provider_android-2.0.21
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
smart_auth-1.0.6
sqflite-2.2.0+3
url_launcher-6.1.7
url_launcher_android-6.0.22
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_player-2.4.8
video_player_android-2.3.9
video_player_avfoundation-2.3.7
video_player_web-2.0.12
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.4
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by danagbemava-nc** [comment]
Hi @icgoogo, what platform(s) do you experience this issue on?

**Comment by icgoogo** [comment]
i experienced on android @danagbemava-nc

**Comment by danagbemava-nc** [comment]
Hi @icgoogo, does this happen every time, or it happens intermittently? 

Can you also check on the `master` channel to see if you still reproduce it? 

You can check out the master branch by running 

```
flutter channel master
flutter upgrade
```

**Comment by icgoogo** [comment]
## Command
```
flutter run --flavor prod -t lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2233:14)
#3      VmService.callMethod (package:vm_service/src/vm_service.dart:2215:12)
#4      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:462:28)
#5      FlutterVmService.renderFrameWithRasterStats (package:flutter_tools/src/vmservice.dart:562:49)
#6      ResidentHandlers.debugFrameJankMetrics (package:flutter_tools/src/resident_runner.dart:717:35)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1766:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.7.0-14.0.pre.41, on macOS 13.0.1 22A400 darwin-arm64, locale es-ID)
    [32m•[39m Flutter version 3.7.0-14.0.pre.41 on channel master at /Users/hammadsyr/Hammad/JadiAnakIT/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 45886068cf (4 hours ago), 2023-01-05 04:35:28 -0500
    [32m•[39m Engine revision a01548f5fa
    [32m•[39m Dart version 3.0.0 (build 3.0.0-85.0.dev)
    [32m•[39m DevTools version 2.20.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/hammadsyr/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m ANDROID_HOME = /Users/hammadsyr/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14B47b
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [32m•[39m Flutter plugin version 71.2.5
    [32m•[39m Dart plugin version 222.4167.21

[32m[✓][39m IntelliJ IDEA Community Edition (version 2022.2.2)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 70.2.5
    [32m•[39m Dart plugin version 222.4167.21

[32m[✓][39m VS Code (version 1.74.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.56.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m CPH1803 (mobile) • 39f81776 • android-arm64  • Android 8.1.0 (API 27)
    [32m•[39m macOS (desktop)  • macos    • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    [32m•[39m Chrome (web)     • chrome   • web-javascript • Google Chrome 108.0.5359.124

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.1.0+55
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
app_settings-4.1.8
audio_session-0.1.13
camera-0.10.1
camera_android
camera_avfoundation-0.9.10
camera_web-0.3.1
connectivity_plus-3.0.2
firebase_analytics-10.1.0
firebase_analytics_web-0.5.1+8
firebase_core-2.4.1
firebase_core_web-2.1.0
firebase_crashlytics-3.0.9
firebase_messaging-14.2.1
firebase_messaging_web-3.2.11
firebase_remote_config-3.0.9
firebase_remote_config_web-1.1.18
flutter_inappwebview-6.0.0-beta.22
flutter_local_notifications-12.0.4
flutter_native_timezone-e975c46ecb481dd67c98f1832f13df83776d8521
flutter_plugin_android_lifecycle-2.0.7
fluttertoast-8.1.2
geocoding-2.0.5
geolocator-9.0.2
geolocator_android-4.1.4
geolocator_apple-2.2.3
geolocator_web-2.1.6
geolocator_windows-0.1.1
http_certificate_pinning-bf7fa7ac7f433bad19531cb9746a1dc6a1047fe8
integration_test
just_audio-0.9.31
just_audio_web-0.4.7
package_info_plus-3.0.2
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.2
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.2
smart_auth-1.0.8
sqflite-2.2.2
url_launcher-6.1.7
url_launcher_android-6.0.22
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_player-2.4.10
video_player_android-2.3.10
video_player_avfoundation-2.3.8
video_player_web-2.0.13
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-4.0.1
webview_flutter_android-3.1.1
webview_flutter_wkwebview-3.0.1

**Comment by icgoogo** [comment]
> 
the error is not intermittent. always get the error whenever pressing j button on my keyboard. what is j button doing exactly?

then quoted the error from master channel

**Comment by danagbemava-nc** [comment]
Hi @icgoogo,

The `j` command tries to print out the jank metrics. 

One final thing, can you try with a new flutter create app to see if it reproduces in there? I attempted to reproduce but it did not on my end.

**Comment by icgoogo** [comment]
yes, i can reproduce it with new flutter app. here is the link to issue the crash

https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+RPCError&body=%23%23+Command%0A%60%60%60%0Aflutter+run%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0ARPCError%0A%60%60%60%0A%230++++++new+_OutstandingRequest+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A1746%3A45%29%0A%231++++++VmService._call+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A2262%3A21%29%0A%232++++++VmService.callServiceExtension+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A2233%3A14%29%0A%233++++++VmService.callMethod+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A2215%3A12%29%0A%234++++++FlutterVmService.callMethodWrapper+%28package%3Aflutter_tools%2Fsrc%2Fvmservice.dart%3A463%3A28%29%0A%235++++++FlutterVmService.renderFrameWithRasterStats+%28package%3Aflutter_tools%2Fsrc%2Fvmservice.dart%3A562%3A49%29%0A%236++++++ResidentHandlers.debugFrameJankMetrics+%28package%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A691%3A35%29%0A%3Casynchronous+suspension%3E%0A%237++++++TerminalHandler.processTerminalInput+%28package%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A1739%3A7%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+3.3.10%2C+on+macOS+13.0.1+22A400+darwin-arm%2C+locale+es-ID%29%0A++++%E2%80%A2+Flutter+version+3.3.10+on+channel+stable+at+%2FUsers%2Fhammadsyr%2FHammad%2FJadiAnakIT%2Fflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+135454af32+%285+weeks+ago%29%2C+2022-12-15+07%3A36%3A55+-0800%0A++++%E2%80%A2+Engine+revision+3316dd8728%0A++++%E2%80%A2+Dart+version+2.18.6%0A++++%E2%80%A2+DevTools+version+2.15.0%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.0%29%0A++++%E2%80%A2+Android+SDK+at+%2FUsers%2Fhammadsyr%2FLibrary%2FAndroid%2Fsdk%0A++++%E2%80%A2+Platform+android-33%2C+build-tools+33.0.0%0A++++%E2%80%A2+ANDROID_HOME+%3D+%2FUsers%2Fhammadsyr%2FLibrary%2FAndroid%2Fsdk%0A++++%E2%80%A2+Java+binary+at%3A+%2FApplications%2FAndroid+Studio.app%2FContents%2Fjre%2FContents%2FHome%2Fbin%2Fjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Xcode+-+develop+for+iOS+and+macOS+%28Xcode+14.1%29%0A++++%E2%80%A2+Xcode+at+%2FApplications%2FXcode.app%2FContents%2FDeveloper%0A++++%E2%80%A2+Build+14B47b%0A++++%E2%80%A2+CocoaPods+version+1.11.3%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+%2FApplications%2FGoogle+Chrome.app%2FContents%2FMacOS%2FGoogle+Chrome%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2021.3%29%0A++++%E2%80%A2+Android+Studio+at+%2FApplications%2FAndroid+Studio.app%2FContents%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0A%0A%5B%E2%9C%93%5D+IntelliJ+IDEA+Ultimate+Edition+%28version+2022.2.2%29%0A++++%E2%80%A2+IntelliJ+at+%2FApplications%2FIntelliJ+IDEA.app%0A++++%E2%80%A2+Flutter+plugin+version+71.2.5%0A++++%E2%80%A2+Dart+plugin+version+222.4167.21%0A%0A%5B%E2%9C%93%5D+IntelliJ+IDEA+Community+Edition+%28version+2022.2.2%29%0A++++%E2%80%A2+IntelliJ+at+%2FApplications%2FIntelliJ+IDEA+CE.app%0A++++%E2%80%A2+Flutter+plugin+version+70.2.5%0A++++%E2%80%A2+Dart+plugin+version+222.4167.21%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.74.2%29%0A++++%E2%80%A2+VS+Code+at+%2FApplications%2FVisual+Studio+Code.app%2FContents%0A++++%E2%80%A2+Flutter+extension+version+3.56.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%282+available%29%0A++++%E2%80%A2+macOS+%28desktop%29+%E2%80%A2+macos++%E2%80%A2+darwin-arm64+++%E2%80%A2+macOS+13.0.1+22A400+darwin-arm%0A++++%E2%80%A2+Chrome+%28web%29++++%E2%80%A2+chrome+%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+109.0.5414.87%0A%0A%5B%E2%9C%93%5D+HTTP+Host+Availability%0A++++%E2%80%A2+All+required+HTTP+hosts+are+available%0A%0A%E2%80%A2+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+135454af32477f815a7525073027a3ff9eff1bfd%0A%0A&labels=tool%2Csevere%3A+crash

**Comment by danagbemava-nc** [comment]
Labeling for further investigation
