### ISSUE TITLE
Inconsistency between command line and plugin - successful hot reload in command line, `LateInitializationError` on hot reloading with plugin

### ISSUE THREAD

**Issue by CicadaCinema** [flutter/flutter#117938]
## Steps to Reproduce

1) Run `flutter create myapp`.
2) Paste the following code into `main.dart`:
```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(const ExampleApp());
}
class Data {
  late double _i;

  void initI(double i) => _i = i;

  void printI() => print(_i);
}

class DataDisplay extends StatefulWidget {
  final Data data;

  const DataDisplay({
    Key? key,
    required this.data,
  }) : super(key: key);

  @override
  State<DataDisplay> createState() => _DataDisplayState();
}

class _DataDisplayState extends State<DataDisplay> {
  late final Timer _timer;

  @override
  initState() {
    super.initState();

    widget.data.initI(5);

    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      widget.data.printI();
      print('a');
    });
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}


class ExampleApp extends StatelessWidget {
  const ExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: DataDisplay(
          data: Data(),
        ),
      ),
    );
  }
}

```

3) Open the project using Android Studio.
4) Select the "Windows (desktop)" device, and run the app. Observe that no error is thrown and output is printed to the terminal every second.
5) Click "hot restart", observe a `LateInitializationError`:
```
Performing hot restart...
Syncing files to device Windows...
Restarted application in 345ms.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_i@18264790' has not been initialized.
#0      Data._i (package:myapp/main.dart)
flutter/flutter-intellij#1      Data.printI (package:myapp/main.dart:14:26)
flutter/flutter-intellij#2      _DataDisplayState.initState.<anonymous closure> (package:myapp/main.dart:39:19)
flutter/flutter-intellij#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
flutter/flutter-intellij#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
flutter/flutter-intellij#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Note that when using the terminal (`flutter run -d Windows` to run the app and `R` to perform a hot restart) no error is thrown.

## Version info

```
C:\Users\Atom>flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2364], locale en-GB)
    • Flutter version 3.3.10 on channel stable at C:\Software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Atom\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at:
      C:\Users\Atom\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31605.320
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Users\Atom\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683
    • Flutter plugin version 70.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Users\Atom\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code, 64-bit edition (version 1.74.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2364]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.46

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment]
@CicadaCinema thanks for filing the issue. This issue is reproducible on the latest `stable` and `master` channels. 

There are a few additional tests that I have tried doing:
- The issue happens on macOS, but not on Web (Web: ✅, macOS: ❌)
- It also happens with `Hot reload` on Android Studio and VSCode.

Labeling the issue for further insights from the team!

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-14.0.pre.27, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-14.0.pre.27 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 63653e8272 (2 hours ago), 2023-01-03 17:13:21 -0800
    • Engine revision 2213b80dd9
    • Dart version 3.0.0 (build 3.0.0-77.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124
    ! Device R9JT3004VRJ is not authorized.
      You might need to check your device for an authorization dialog.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by mraleph** [comment]
Note that exception is expected when doing _hot reload_. Should not happen when doing hot restart though. Maybe the tool is claiming to restart, but does reload instead - which would be a bug. 

I don't think there is any dependency on dart here though.

**Comment by CicadaCinema** [comment]
> I know it looks like an IDE problem but I don't think it is. The IDE effectively does `flutter run` but adds additional arguments, putting the `flutter` tool into a different mode. You'd probably see the same problem if you included all the additional arguments when you run it from the command line. If you want to know what the additional args are you can find them in the log file. Search for "start-paused".

I didn't know this, thank you!

**Comment by CicadaCinema** [comment]
@stevemessick 
I tried to follow your advice, but I could not find such a log file in my project directory, or anything mentioning "start-paused". I am using Windows, if it matters.

I found the following 'run configuration' - `main_dart.xml`:
```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="main.dart" type="FlutterRunConfigurationType" factoryName="Flutter">
    <option name="filePath" value="$PROJECT_DIR$/lib/main.dart" />
    <method v="2" />
  </configuration>
</component>
```

Adding -v as an argument in this run configuration displayed some build logs, including the following:
```
...
[   +5 ms] Launching lib\main.dart on Windows in debug mode...
[   +3 ms] C:\Software\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Software\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root C:\Software\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\Atom\AppData\Local\Temp\flutter_tools.5d3b7e57\flutter_tool.89a764c6\app.dill --packages C:\Users\Atom\Downloads\contrived_example\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\4f2a58af27abc49ecf55570043bbf938.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
...
```

Running this command in the terminal did not produce any output, and dart.exe didn't even terminate, even after a few minutes - there are probably additional build steps executed by the IDE. I must be missing something.

**Comment by stevemessick** [comment]
In IntelliJ, you can find the log file from the menu `Help > Show Log in Files` (something like that).

**Comment by CicadaCinema** [comment]
> In IntelliJ, you can find the log file from the menu `Help > Show Log in Files` (something like that).

Found it! Thanks again

**Comment by christopherfujino** [comment]
@CicadaCinema this is working as intended, per https://docs.flutter.dev/development/tools/hot-reload a hot reload does NOT re-run `initState()`.

The reason you don't get an error from the terminal, is because you are hitting `R`, which does a hot RESTART, which completely re-runs the `main()` function, re-initializating the state and initializing your late field.

**Comment by mraleph** [comment]
@christopherfujino I am a bit confused both by console output and UI labels. Note that @CicadaCinema says that they are clicking "hot **restart**" button (not **reload**) and the messaging in the console claims that hot restart is performed, but then the error occurs which can only occur in hot reload. I think that's the inconsistency the user is pointing to. 

```
Performing hot restart...
Syncing files to device Windows...
Restarted application in 345ms.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_i@18264790' has not been initialized.
#0      Data._i (package:myapp/main.dart)
flutter/flutter-intellij#1      Data.printI (package:myapp/main.dart:14:26)
flutter/flutter-intellij#2      _DataDisplayState.initState.<anonymous closure> (package:myapp/main.dart:39:19)
flutter/flutter-intellij#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
flutter/flutter-intellij#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
flutter/flutter-intellij#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by CicadaCinema** [comment]
agh I'm so sorry about the confusion - I don't know why I wrote 'reload' in the title, I really meant 'restart', as in my reproduction instructions ('Steps to Reproduce')

> I think that's the inconsistency the user is pointing to.

I was originally pointing to the inconsistency of _hot restarting in the command line_ vs _hot restarting with the IntelliJ plugin_.

Maybe it makes sense to open a new issue with the correct title..?

**Comment by mraleph** [comment]
friendly ping @christopherfujino 

(@CicadaCinema you will probably get an answer tomorrow, as Monday is a holiday in US)
