### ISSUE TITLE
Cannot re-run failed ci.yaml validation

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#117904]
Here: https://github.com/flutter/flutter/pull/117468. Clicking "re-run" in this case would be helpful because the failure is reported as a rate-limit violation.

**Comment by zanderso** [comment]
Looks like the same story here https://github.com/flutter/flutter/pull/116664

**Comment by nehalvpatel** [comment]
I found this: https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-secondary-rate-limits

Looks like we might need to check for the `Retry-After` header. But first, we need to look into the logs to see if we receive that header.

**Comment by godofredoc** [comment]
Running with `curl 'https://flutter-dashboard.appspot.com/api/reset-try-task?repo=flutter&pr=117468'` works sometimes.

**Comment by godofredoc** [comment]
Some more info for https://github.com/flutter/flutter/pull/112950

```
Retrieved .ci.yaml for flutter/flutter/464e6d1f8d58b7d7b6998ef0d890e48023916cbd/.ci.yaml

#0      CiYaml._checkExceptions (package:cocoon_service/src/model/ci_yaml/ci_yaml.dart:200:7)
#1      CiYaml._validate (package:cocoon_service/src/model/ci_yaml/ci_yaml.dart:194:5)
#2      new CiYaml (package:cocoon_service/src/model/ci_yaml/ci_yaml.dart:26:5)
#3      Scheduler.getCiYaml (package:cocoon_service/src/service/scheduler.dart:232:12)
<asynchronous suspension>
#4      Scheduler.getPresubmitTargets (package:cocoon_service/src/service/scheduler.dart:403:16)
<asynchronous suspension>
#5      Scheduler.triggerPresubmitTargets (package:cocoon_service/src/service/scheduler.dart:301:45)
<asynchronous suspension>
#6      ResetTryTask.get (package:cocoon_service/src/request_handlers/reset_try_task.dart:47:5)
<asynchronous suspension>
#7      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:50:24)
<asynchronous suspension>
#8      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:151:9)
<asynchronous suspension>
#9      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)
<asynchronous suspension>
#10     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:286:11)
<asynchronous suspension>
```

**Comment by godofredoc** [comment]
For a message like:

```
{"action":"rerequested","check_run":{"id":10594673828,"name":"ci.yaml validation","node_id":"CR_kwDOAeUeuM8AAAACd33kpA","head_sha":"464e6d1f8d58b7d7b6998ef0d890e48023916cbd","external_id":"","url":"https://api.github.com/repos/flutter/flutter/check-runs/10594673828","html_url":"https://github.com/flutter/flutter/runs/10594673828","details_url":"https://flutter-dashboard.appspot.com","status":"completed","conclusion":"failure","started_at":"2023-01-12T02:38:16Z","completed_at":"2023-01-12T02:38:17Z","output":{"title":"ci.yaml validation","summary":".ci.yaml has failures","text":"FormatException: ERROR: Linux build_tests_1_2 is a new builder added. it needs to be marked bringup: true\nIf ci.yaml wasn't changed, try `git fetch upstream && git merge upstream/master`\n\n\n","annotations_count":0,"annotations_url":"https://api.github.com/repos/flutter/flutter/check-runs/10594673828/annotations"},"check_suite":{"id":8629678134,"node_id":"CS_kwDOAeUeuM8AAAACAl5wNg","head_branch":null,"head_sha":"464e6d1f8d58b7d7b6998ef0d890e48023916cbd","status":"queued","conclusion":null,"url":"https://api.github.com/repos/flutter/flutter/check-suites/8629678134","before":null,"after":null,"pull_requests":[],"app":{"id":64368,"slug":"flutter-dashboard","node_id":"MDM6QXBwNjQzNjg=","owner":{"login":"flutter","id":14101776,"node_id":"MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2","avatar_url":"https://avatars.githubusercontent.com/u/14101776?v=4","gravatar_id":"","url":"https://api.github.com/users/flutter","html_url":"https://github.com/flutter","followers_url":"https://api.github.com/users/flutter/followers","following_url":"https://api.github.com/users/flutter/following{/other_user}","gists_url":"https://api.github.com/users/flutter/gists{/gist_id}","starred_url":"https://api.github.com/users/flutter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/flutter/subscriptions","organizations_url":"https://api.github.com/users/flutter/orgs","repos_url":"https://api.github.com/users/flutter/repos","events_url":"https://api.github.com/users/flutter/events{/privacy}","received_events_url":"https://api.github.com/users/flutter/received_events","type":"Organization","site_admin":false},"name":"flutter-dashboard","description":"Flutter Dashboard and build/test orchestrator. The source code for the application can be found at https://github.com/flutter/cocoon/tree/main/app_dart.","external_url":"https://flutter-dashboard.appspot.com","html_url":"https://github.com/apps/flutter-dashboard","created_at":"2020-05-10T00:32:46Z","updated_at":"2022-08-26T19:06:29Z","permissions":{"checks":"write","contents":"read","issues":"write","metadata":"read","pull_requests":"write","statuses":"write"},"events":["check_run","check_suite","create","label","pull_request"]},"created_at":"2022-10-05T16:26:54Z","updated_at":"2023-01-12T03:16:18Z"},"app":{"id":64368,"slug":"flutter-dashboard","node_id":"MDM6QXBwNjQzNjg=","owner":{"login":"flutter","id":14101776,"node_id":"MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2","avatar_url":"https://avatars.githubusercontent.com/u/14101776?v=4","gravatar_id":"","url":"https://api.github.com/users/flutter","html_url":"https://github.com/flutter","followers_url":"https://api.github.com/users/flutter/followers","following_url":"https://api.github.com/users/flutter/following{/other_user}","gists_url":"https://api.github.com/users/flutter/gists{/gist_id}","starred_url":"https://api.github.com/users/flutter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/flutter/subscriptions","organizations_url":"https://api.github.com/users/flutter/orgs","repos_url":"https://api.github.com/users/flutter/repos","events_url":"https://api.github.com/users/flutter/events{/privacy}","received_events_url":"https://api.github.com/users/flutter/received_events","type":"Organization","site_admin":false},"name":"flutter-dashboard","description":"Flutter Dashboard and build/test orchestrator. The source code for the application can be found at https://github.com/flutter/cocoon/tree/main/app_dart.","external_url":"https://flutter-dashboard.appspot.com","html_url":"https://github.com/apps/flutter-dashboard","created_at":"2020-05-10T00:32:46Z","updated_at":"2022-08-26T19:06:29Z","permissions":{"checks":"write","contents":"read","issues":"write","metadata":"read","pull_requests":"write","statuses":"write"},"events":["check_run","check_suite","create","label","pull_request"]},"pull_requests":[]},"repository":{"id":31792824,"node_id":"MDEwOlJlcG9zaXRvcnkzMTc5MjgyNA==","name":"flutter","full_name":"flutter/flutter","private":false,"owner":{"login":"flutter","id":14101776,"node_id":"MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2","avatar_url":"https://avatars.githubusercontent.com/u/14101776?v=4","gravatar_id":"","url":"https://api.github.com/users/flutter","html_url":"https://github.com/flutter","followers_url":"https://api.github.com/users/flutter/followers","following_url":"https://api.github.com/users/flutter/following{/other_user}","gists_url":"https://api.github.com/users/flutter/gists{/gist_id}","starred_url":"https://api.github.com/users/flutter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/flutter/subscriptions","organizations_url":"https://api.github.com/users/flutter/orgs","repos_url":"https://api.github.com/users/flutter/repos","events_url":"https://api.github.com/users/flutter/events{/privacy}","received_events_url":"https://api.github.com/users/flutter/received_events","type":"Organization","site_admin":false},"html_url":"https://github.com/flutter/flutter","description":"Flutter makes it easy and fast to build beautiful apps for mobile and beyond","fork":false,"url":"https://api.github.com/repos/flutter/flutter","forks_url":"https://api.github.com/repos/flutter/flutter/forks","keys_url":"https://api.github.com/repos/flutter/flutter/keys{/key_id}","collaborators_url":"https://api.github.com/repos/flutter/flutter/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/flutter/flutter/teams","hooks_url":"https://api.github.com/repos/flutter/flutter/hooks","issue_events_url":"https://api.github.com/repos/flutter/flutter/issues/events{/number}","events_url":"https://api.github.com/repos/flutter/flutter/events","assignees_url":"https://api.github.com/repos/flutter/flutter/assignees{/user}","branches_url":"https://api.github.com/repos/flutter/flutter/branches{/branch}","tags_url":"https://api.github.com/repos/flutter/flutter/tags","blobs_url":"https://api.github.com/repos/flutter/flutter/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/flutter/flutter/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/flutter/flutter/git/refs{/sha}","trees_url":"https://api.github.com/repos/flutter/flutter/git/trees{/sha}","statuses_url":"https://api.github.com/repos/flutter/flutter/statuses/{sha}","languages_url":"https://api.github.com/repos/flutter/flutter/languages","stargazers_url":"https://api.github.com/repos/flutter/flutter/stargazers","contributors_url":"https://api.github.com/repos/flutter/flutter/contributors","subscribers_url":"https://api.github.com/repos/flutter/flutter/subscribers","subscription_url":"https://api.github.com/repos/flutter/flutter/subscription","commits_url":"https://api.github.com/repos/flutter/flutter/commits{/sha}","git_commits_url":"https://api.github.com/repos/flutter/flutter/git/commits{/sha}","comments_url":"https://api.github.com/repos/flutter/flutter/comments{/number}","issue_comment_url":"https://api.github.com/repos/flutter/flutter/issues/comments{/number}","contents_url":"https://api.github.com/repos/flutter/flutter/contents/{+path}","compare_url":"https://api.github.com/repos/flutter/flutter/compare/{base}...{head}","merges_url":"https://api.github.com/repos/flutter/flutter/merges","archive_url":"https://api.github.com/repos/flutter/flutter/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/flutter/flutter/downloads","issues_url":"https://api.github.com/repos/flutter/flutter/issues{/number}","pulls_url":"https://api.github.com/repos/flutter/flutter/pulls{/number}","milestones_url":"https://api.github.com/repos/flutter/flutter/milestones{/number}","notifications_url":"https://api.github.com/repos/flutter/flutter/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/flutter/flutter/labels{/name}","releases_url":"https://api.github.com/repos/flutter/flutter/releases{/id}","deployments_url":"https://api.github.com/repos/flutter/flutter/deployments","created_at":"2015-03-06T22:54:58Z","updated_at":"2023-01-12T03:08:02Z","pushed_at":"2023-01-12T03:05:31Z","git_url":"git://github.com/flutter/flutter.git","ssh_url":"git@github.com:flutter/flutter.git","clone_url":"https://github.com/flutter/flutter.git","svn_url":"https://github.com/flutter/flutter","homepage":"https://flutter.dev","size":234894,"stargazers_count":148265,"watchers_count":148265,"language":"Dart","has_issues":true,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":false,"has_discussions":false,"forks_count":24239,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":11455,"license":{"key":"bsd-3-clause","name":"BSD 3-Clause \"New\" or \"Revised\" License","spdx_id":"BSD-3-Clause","url":"https://api.github.com/licenses/bsd-3-clause","node_id":"MDc6TGljZW5zZTU="},"allow_forking":true,"is_template":false,"web_commit_signoff_required":false,"topics":["android","app-framework","cross-platform","dart","dart-platform","desktop","flutter","flutter-package","fuchsia","ios","linux-desktop","macos","material-design","mobile","mobile-development","skia","web","web-framework","windows"],"visibility":"public","forks":24239,"open_issues":11455,"watchers":148265,"default_branch":"master"},"organization":{"login":"flutter","id":14101776,"node_id":"MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2","url":"https://api.github.com/orgs/flutter","repos_url":"https://api.github.com/orgs/flutter/repos","events_url":"https://api.github.com/orgs/flutter/events","hooks_url":"https://api.github.com/orgs/flutter/hooks","issues_url":"https://api.github.com/orgs/flutter/issues","members_url":"https://api.github.com/orgs/flutter/members{/member}","public_members_url":"https://api.github.com/orgs/flutter/public_members{/member}","avatar_url":"https://avatars.githubusercontent.com/u/14101776?v=4","description":"Flutter is Google's UI toolkit for building beautiful, natively compiled applications for mobile, web, desktop, and embedded devices from a single codebase."},"enterprise":{"id":1732,"slug":"alphabet","name":"Alphabet","node_id":"MDEwOkVudGVycHJpc2UxNzMy","avatar_url":"https://avatars.githubusercontent.com/b/1732?v=4","description":"","website_url":"https://abc.xyz/","html_url":"https://github.com/enterprises/alphabet","created_at":"2019-12-19T00:30:52Z","updated_at":"2022-12-20T00:46:37Z"},"sender":{"login":"godofredoc","id":54371434,"node_id":"MDQ6VXNlcjU0MzcxNDM0","avatar_url":"https://avatars.githubusercontent.com/u/54371434?v=4","gravatar_id":"","url":"https://api.github.com/users/godofredoc","html_url":"https://github.com/godofredoc","followers_url":"https://api.github.com/users/godofredoc/followers","following_url":"https://api.github.com/users/godofredoc/following{/other_user}","gists_url":"https://api.github.com/users/godofredoc/gists{/gist_id}","starred_url":"https://api.github.com/users/godofredoc/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/godofredoc/subscriptions","organizations_url":"https://api.github.com/users/godofredoc/orgs","repos_url":"https://api.github.com/users/godofredoc/repos","events_url":"https://api.github.com/users/godofredoc/events{/privacy}","received_events_url":"https://api.github.com/users/godofredoc/received_events","type":"User","site_admin":false},"installation":{"id":10381585,"node_id":"MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTAzODE1ODU="}}
```

We get:

```
> INFO 2023-01-12T03:16:18.986Z CheckName: ci.yaml validation State: false
> WARNING 2023-01-12T03:16:18.986Z Failed to process Instance of 'PushMessage'
> WARNING 2023-01-12T03:16:18.986Z Purged write lock from cache

```

**Comment by godofredoc** [comment]
Checking the output of the ci.yaml shows the real error. 

![image](https://user-images.githubusercontent.com/54371434/211974290-be017a8f-3055-4627-ac53-57927fa161a3.png)


```
FormatException: ERROR: Linux build_tests_1_2 is a new builder added. it needs to be marked bringup: true
If ci.yaml wasn't changed, try git fetch upstream && git merge upstream/master
```

This is most likely a problem with the comparison of an old version of the .ci.yaml with the ToT .ci.yaml when some builds were added in the middle.

**Comment by godofredoc** [comment]
Seems like this is working as intended but we need to provide functionality to get this kind of PR out of that state. I opened https://github.com/flutter/flutter/issues/118361 for that.

With this approach whenever we get this error we can run `@autosubmit rebase` to rebase and retry all the builds. If the rebase fails then we will need to close the PR to force the deflake logic to recreate it.

**Comment by CaseyHillers** [comment]
Duping with https://github.com/flutter/flutter/issues/100081
