### ISSUE TITLE
file_selector_windows & url_launcher causing errors while debugging in Windows desktop

### ISSUE THREAD

**Issue by AndyProtech** [flutter/flutter#118037]
## Steps to Reproduce

1. Created new Flutter project.
2. Added to pubspec.yaml to dependencies:
  file_selector_windows: ^0.8.2
  url_launcher: ^6.1.7  
3. Started debugging in Windows desktop.
4. Debug console result:
-----------------------------------------------------------------------------------------------------------
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
  add_subdirectory given source
  "flutter/ephemeral/.plugin_symlinks/file_selector_windows/windows" which is
  not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:57 (include)

CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
  add_subdirectory given source
  "flutter/ephemeral/.plugin_symlinks/url_launcher_windows/windows" which is
  not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:57 (include)

Exception: Unable to generate build files
Exited (sigterm)
-----------------------------------------------------------------------------------------------------------
5. If I change "file selector windows" version to latest:
  file_selector_windows: ^0.9.1+4
First error dissapears. But I need version ^0.8,2 in case other plugin I'm using in other project depends on this version.
-----------------------------------------------------------------------------------------------------------

```
flutter run --verbose
[  +29 ms] executing: [C:\ProgramData\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 135454af32477f815a7525073027a3ff9eff1bfd
[        ] executing: [C:\ProgramData\flutter/] git tag --points-at 135454af32477f815a7525073027a3ff9eff1bfd
[  +30 ms] Exit code 0 from: git tag --points-at 135454af32477f815a7525073027a3ff9eff1bfd
[        ] 3.3.10
[  +22 ms] executing: [C:\ProgramData\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\ProgramData\flutter/] git ls-remote --get-url origin
[  +23 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +36 ms] executing: [C:\ProgramData\flutter/] git rev-parse --abbrev-ref HEAD
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +34 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +21 ms] executing: C:\Users\Andreus\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +26 ms] List of devices attached
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +29 ms] Multiple devices found:
[  +16 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1288]
[        ] Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54
[        ] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[        ] Please choose one (To quit, press "q/Q")
[        ] : 
[+5170 ms] 1
[  +11 ms] Skipping pub get: version match.
[  +17 ms] Found plugin file_selector_windows at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\file_selector_windows-0.8.2+2\
[   +8 ms] Found plugin url_launcher at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.7\
[   +1 ms] Found plugin url_launcher_android at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.22\
[   +1 ms] Found plugin url_launcher_ios at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[   +1 ms] Found plugin url_launcher_linux at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[   +1 ms] Found plugin url_launcher_macos at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[   +1 ms] Found plugin url_launcher_web at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.13\
[   +1 ms] Found plugin url_launcher_windows at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[  +22 ms] Found plugin file_selector_windows at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\file_selector_windows-0.8.2+2\
[   +8 ms] Found plugin url_launcher at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.7\
[   +1 ms] Found plugin url_launcher_android at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.22\
[        ] Found plugin url_launcher_ios at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[        ] Found plugin url_launcher_linux at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[   +1 ms] Found plugin url_launcher_macos at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[   +1 ms] Found plugin url_launcher_web at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.13\
[        ] Found plugin url_launcher_windows at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[  +12 ms] Found plugin file_selector_windows at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\file_selector_windows-0.8.2+2\
[   +3 ms] Found plugin url_launcher at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.7\
[        ] Found plugin url_launcher_android at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.22\
[        ] Found plugin url_launcher_ios at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[        ] Found plugin url_launcher_linux at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[        ] Found plugin url_launcher_macos at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[        ] Found plugin url_launcher_web at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.13\
[        ] Found plugin url_launcher_windows at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[  +23 ms] Generating C:\work\zenkov\flutter_application_1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +41 ms] Initializing file store
[   +4 ms] Skipping target: gen_localizations
[   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\work\zenkov\flutter_application_1\.dart_tool\package_config_subset,C:\work\zenkov\flutter_application_1\.dart_tool\flutter_build\dart_plugin_registrant.dart}
[   +5 ms] Found plugin file_selector_windows at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\file_selector_windows-0.8.2+2\
[   +3 ms] Found plugin url_launcher at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.7\
[        ] Found plugin url_launcher_android at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.22\
[        ] Found plugin url_launcher_ios at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[        ] Found plugin url_launcher_linux at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[        ] Found plugin url_launcher_macos at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[        ] Found plugin url_launcher_web at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.13\
[        ] Found plugin url_launcher_windows at C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[   +3 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +2 ms] Launching lib\main.dart on Windows in debug mode...
[   +1 ms] C:\ProgramData\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\ProgramData\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\ProgramData\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Andreus\AppData\Local\Temp\flutter_tools.1b152fd8\flutter_tool.c8d7256e\app.dill --packages C:\work\zenkov\flutter_application_1\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false      
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --source
C:\work\zenkov\flutter_application_1\.dart_tool\flutter_build\dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///C:/work/zenkov/flutter_application_1/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +10 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +20 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "6fde9c23",
               "installDate": "2023-01-05T00:00:56Z",
               "installationName": "VisualStudio/17.4.3+33205.214",
               "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "installationVersion": "17.4.33205.214",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "Мощная интегрированная среда разработки, бесплатная для студентов, участников проектов с открытым кодом и отдельных пользователей.",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelId": "VisualStudio.17.Release",
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.4#17.4.3",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2023-01-05T00:00:56.6197555Z",
               "catalog": {
                 "buildBranch": "d17.4",
                 "buildVersion": "17.4.33205.214",
                 "id": "VisualStudio/17.4.3+33205.214",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.4.3",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "3",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "17.4.3+33205.214",
                 "requiredEngineVersion": "3.4.2246.31370"
               },
               "properties": {
                 "campaignId": "2030:3b30e9e6a2214f05ad3b44c4e0e5da72",
                 "channelManifestId": "VisualStudio.17.Release/17.4.3+33205.214",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +4 ms] Building Windows application...
[   +7 ms] <- compile package:flutter_application_1/main.dart
[        ] executing: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S C:\work\zenkov\flutter_application_1\windows -B build\windows -G Visual     
Studio 17 2022
[  +30 ms] -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
[  +10 ms] CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
[   +1 ms]   add_subdirectory given source
[        ]   "flutter/ephemeral/.plugin_symlinks/file_selector_windows/windows" which is
[        ]   not an existing directory.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:57 (include)
[        ] CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
[        ]   add_subdirectory given source
[        ]   "flutter/ephemeral/.plugin_symlinks/url_launcher_windows/windows" which is
[        ]   not an existing directory.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:57 (include)
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "C:/work/zenkov/flutter_application_1/build/windows/CMakeFiles/CMakeOutput.log".
[   +7 ms] Building Windows application... (completed in 57ms)
[ +351 ms] .dart_tool/flutter_build/dart_plugin_registrant.dart:13:8: Error: Error when reading '/C:/ProgramData/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.8.2+2/lib/file_selector_windows.dart': Thesystem cannot find the path specified.
[        ] import 'package:file_selector_windows/file_selector_windows.dart';
[        ]        ^
[        ] .dart_tool/flutter_build/dart_plugin_registrant.dart:14:8: Error: Error when reading '/C:/ProgramData/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/lib/url_launcher_windows.dart': The    
system cannot find the path specified.
[        ] import 'package:url_launcher_windows/url_launcher_windows.dart';
[        ]        ^
[+1029 ms] .dart_tool/flutter_build/dart_plugin_registrant.dart:67:9: Error: Undefined name 'FileSelectorWindows'.
[        ]         FileSelectorWindows.registerWith();
[        ]         ^^^^^^^^^^^^^^^^^^^
[        ] .dart_tool/flutter_build/dart_plugin_registrant.dart:77:9: Error: Undefined name 'UrlLauncherWindows'.
[        ]         UrlLauncherWindows.registerWith();
[        ]         ^^^^^^^^^^^^^^^^^^
[+1993 ms] Exception: Unable to generate build files
[   +1 ms] "flutter run" took 8 962ms.
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[   +9 ms] ensureAnalyticsSent: 7ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
Analyzing flutter_application_1...
No issues found! (ran in 1.1s)
```

```
flutter doctor -v
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.1288], locale ru-RU)
    • Flutter version 3.3.10 on channel stable at C:\ProgramData\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Andreus\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.2)
    • VS Code at C:\Users\Andreus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1288]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
What are the contents of
- `/C:/ProgramData/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.8.2+2` and
- `/C:/ProgramData/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1`?

It looks like you might have a damaged pub cache, where those specific package versions are missing files in your cache.

**Comment by AndyProtech** [comment]
> What are the contents of
> 
> * `/C:/ProgramData/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.8.2+2` and
> * `/C:/ProgramData/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1`?
> 
> It looks like you might have a damaged pub cache, where those specific package versions are missing files in your cache.

There're only files and no directories like I see in other folders of plugins.
05.01.2023  02:27               190 AUTHORS
05.01.2023  02:27               549 CHANGELOG.md
05.01.2023  02:27             1я519 LICENSE
05.01.2023  02:27               691 pubspec.yaml
05.01.2023  02:27               600 README.md
and
05.01.2023  02:14             2я454 AUTHORS
05.01.2023  02:14             1я242 CHANGELOG.md
05.01.2023  02:14             1я519 LICENSE
05.01.2023  02:14               694 pubspec.yaml
05.01.2023  02:14               397 README.md

In other plugins folders I see not only these files but other folders:
example
lib
test

How could I fix that?

**Comment by AndyProtech** [comment]
> It looks like you might have a damaged pub cache, where those specific package versions are missing files in your cache.

flutter pub cache repair
+ this fixed the problem. Thank you so much!

**Comment by stuartmorgan** [comment]
Closing as the issue was a local pub cache problem, not an issue with the plugins.
