### ISSUE TITLE
[webview_flutter] Flaky Android failures

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#118199]
I just hit the following flake in `webview_flutter_android` in CI ([run link](https://cirrus-ci.com/task/5409817729171456?logs=firebase_test_lab#L2241)):

```
java.lang.AssertionError: Manager has already been closed.
     FATAL EXCEPTION: main
Process: io.flutter.plugins.webviewflutterandroidexample, PID: 24654
java.lang.AssertionError: Manager has already been closed.
	at io.flutter.plugins.webviewflutter.InstanceManager.assertManagerIsNotClosed(InstanceManager.java:205)
	at io.flutter.plugins.webviewflutter.InstanceManager.getIdentifierForStrongReference(InstanceManager.java:102)
	at io.flutter.plugins.webviewflutter.WebChromeClientFlutterApiImpl.onProgressChanged(WebChromeClientFlutterApiImpl.java:35)
	at io.flutter.plugins.webviewflutter.WebChromeClientHostApiImpl$WebChromeClientImpl.onProgressChanged(WebChromeClientHostApiImpl.java:46)
	at Fa.d(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3)
	at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410683:57)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

It failed this way on one of the two devices on the first run, and the other on the automatic internal-to-repo-tooling rerun.

**Comment by bparrishMines** [comment]
Ah, thanks for finding this error. It is most likely caused by callback methods being triggered and attempting to communicate with Dart after the plugin has been removed from the engine. I'll work on a fix
