### ISSUE TITLE
 right click on the text field after  focusNode.requestFocus()

### ISSUE THREAD

**Issue by androidwoman** [flutter/flutter#118138]
hi 

I found a problem in Flutter Windows
when I focusNode.requestFocus() and then right click on the text field
 it gives the following error and does not display the selection menu.

The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/editable_text.dart': Failed assertion: line 3122 pos 12: '_selectionOverlay != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      EditableTextState.toggleToolbar (package:flutter/src/widgets/editable_text.dart:3122:12)
#3      TextSelectionGestureDetectorBuilder.onSecondaryTap (package:flutter/src/widgets/text_selection.dart:1715:22)
#4      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:635:71)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:635:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:239:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:615:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#22     _invoke1 (dart:ui/hooks.dart:167:13)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 2 frames from class _AssertionError)
Handler: "onSecondaryTap"
Recognizer: TapGestureRecognizer#807f0
  debugOwner: _TextSelectionGestureDetectorState#c1963
  state: possible
  won arena
  finalPosition: Offset(62.7, 630.0)
  finalLocalPosition: Offset(18.7, 22.7)
  button: 2
  sent tap down

**Comment by bitbeter** [comment]
I have same issue in TextFields

**Comment by danagbemava-nc** [comment]
Hi @androidwoman,

Can you please provide your `flutter doctor -v`  and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can investigate this issue? 

Thank you

**Comment by androidwoman** [comment]
flutter doctor -v:
```
$ flutter doctor -v
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2364], locale en-US)
    • Flutter version 3.3.10 on channel stable at C:\Users\security\Desktop\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\security\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\security\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.21)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.33027.164
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2
    • Flutter plugin version 65.2.1
    • Dart plugin version 203.8452

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2364]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.62

[!] HTTP Host Availability
    X HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup:
      'cocoapods.org'
    X HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host
      lookup: 'maven.google.com'
    X HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup:
      'pub.dev'
    X HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host
      lookup: 'cloud.google.com'

! Doctor found issues in 1 category.


```
code:
```
void main()  {

  runApp(
      app()
  );
}
class app extends StatefulWidget {
  const app({Key? key}) : super(key: key);

  @override
  _appState createState() => _appState();
}

class _appState extends State<app> {
  final focus=FocusNode();
  @override
  Widget build(BuildContext context) {
    return  MaterialApp(
      home: Scaffold(body: Column(
        children: [
          TextFormField(focusNode: focus,),
          TextButton(onPressed: (){FocusScope.of(context).requestFocus(focus);}, child: Text("focus"))
        ],
      ),),
    );
  }
}
```

**Comment by androidwoman** [comment]
When I click on the focus button and then right click on the text field, it gives the following error
```
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/editable_text.dart': Failed assertion: line 3122 pos 12: '_selectionOverlay != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      EditableTextState.toggleToolbar (package:flutter/src/widgets/editable_text.dart:3122:12)
#3      TextSelectionGestureDetectorBuilder.onSecondaryTap (package:flutter/src/widgets/text_selection.dart:1715:22)
#4      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:635:71)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:635:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:239:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:615:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#22     _invoke1 (dart:ui/hooks.dart:167:13)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 2 frames from class _AssertionError)
Handler: "onSecondaryTap"
Recognizer: TapGestureRecognizer#807f0
  debugOwner: _TextSelectionGestureDetectorState#c1963
  state: possible
  won arena
  finalPosition: Offset(62.7, 630.0)
  finalLocalPosition: Offset(18.7, 22.7)
  button: 2
  sent tap down
```

**Comment by danagbemava-nc** [comment]
Hi @androidwoman, an issue with a similar exception to yours was previously reported in https://github.com/flutter/flutter/issues/111660 and has since been fixed. The fix is in the master channel now, can you switch to the master channel to see whether or not you still experience this issue? 

If you do, please provide the updated output of `flutter doctor -v`. 

Thank you

**Comment by androidwoman** [comment]
thank @danagbemava-nc 
Yes, the problem has been solved in master channel , but many of the packages that I use in  Stable Channel have errors in master channel.
Is there any other solution to solve this problem?
When will master channel  and stable channel  merge together?

**Comment by androidwoman** [comment]
flutter doctor -v in master channel 
```
[√] Flutter (Channel master, 3.7.0-17.0.pre.3, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
    • Flutter version 3.7.0-17.0.pre.3 on channel master at D:\flutter                                      
    • Upstream repository https://github.com/flutter/flutter.git                                            
    • Framework revision 583a8122bc (22 hours ago), 2023-01-10 01:18:03 -0800                               
    • Engine revision 716bb9172c                
    • Dart version 3.0.0 (build 3.0.0-103.0.dev)
    • DevTools version 2.20.0                   
                                                
[√] Windows Version (Installed version of Windows is version 10 or higher)
                                                                          
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\fchit\AppData\Local\Android\sdk                       
    • Platform android-33, build-tools 32.1.0-rc1                                   
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.22)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.33130.400
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.2
    • Flutter plugin version 63.2.4
    • Dart plugin version 213.5744.122

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\fchit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @androidwoman, you can check on the `beta` channel to see if this issue is fixed there as well. If it is, then the fix should roll out in the next stable version. 

Per our triage policy, I'll be closing this issue since it has been fixed on the master channel. 

Thank you
