### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The device is not ready., errno = 21

### ISSUE THREAD

**Issue by kcibdev** [flutter/flutter#118165]
I had a windows 8.1 and now upgraded to windows 10 and i copied my flutter sdk from the windows 8.1 with path (`D:\flutter\Sdk\flutter\`) to the new windows 10 and changed the path to (`C:\Programming\Flutter\Sdk\flutter`) and i installed android studio, changed path in my system variables and set everything up but whenever i try running `flutter doctor` i get the error below
## Command
```
flutter doctor
```

## Steps to Reproduce
1. upgrade windows from 8.1 to 10
2. copied flutter sdk from windows 8.1 to 10
3. changed path from `D:\flutter\Sdk\flutter\` to `C:\Programming\Flutter\Sdk\flutter`
4. run `flutter doctor`

## Logs
FileSystemException: FileSystemException: Exists failed, path = 'D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\_fe_analyzer_shared-41.0.0\lib\' (OS Error: The device is not ready.
, errno = 21)

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:497:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:496:12)
#5      PubDependencies.isUpToDate (package:flutter_tools/src/flutter_cache.dart:101:57)
<asynchronous suspension>
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:673:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1325:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.10240], locale en-US)
    • Flutter version 3.3.4 on channel stable at C:\Programming\Flutter\Sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (3 months ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\kcib\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.74.2)
    • VS Code at C:\Users\kcib\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.10240]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.76

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

Please how do i make change my path to listen to the new one

**Comment by kcibdev** [comment]
Checked https://github.com/flutter/flutter/issues/81146 still no valid answer

**Comment by danagbemava-nc** [comment]
Closing this in favor of #81146 

Kindly follow up in the linked issue for updates. 

Thank you

**Comment by kcibdev** [comment]
I finally fixed it
i went into the packages and .pub-cache folder in my new sdk folder `C:\Programming\Flutter\Sdk\flutter`  and used vscode to search for all occurence of `D:\flutter\Sdk\flutter\` found them in `package_config.json` file and renamed it to ``C:\Programming\Flutter\Sdk\flutter`` which made it work

**Comment by SarahGhorbani** [comment]
> 

I get this error too.
But I did not find any response to all of this thread and another thread with this topic except this response.
Can you please tell more detail about your solution? 
Which file of packages and .pub-cache folder did you search?
Where is the ```packages_config.json``` path exactly?
