### ISSUE TITLE
Failing to run `flutter run` before cleaning project

### ISSUE THREAD

**Issue by Andrej123456789** [flutter/flutter#118143]
Can't run my project before cleaning it and fetching all packages again. This is not happening with another Flutter projects and this wasn't happening with counter app.

GitHub repo of the project: https://github.com/Andrej123456789/blagajna_gui

## Steps to Reproduce

1. Close application after debug session
2. Run `flutter run` again in my terminal
3. `Exception: Build process failed` error

## Logs

<details>
<summary>Logs</summary>

```
~/Documents/Programming/Andrej123456789/blagajna_gui master !3 ?2                                                                                                                             
❯ flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Exception: Build process failed
```

```
~/Documents/Programming/Andrej123456789/blagajna_gui master !3 ?2                                                                                                                           4s
❯ flutter run -v
[  +50 ms] executing: uname -m
[  +23 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/home/vangu/development/flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 135454af32477f815a7525073027a3ff9eff1bfd
[        ] executing: [/home/vangu/development/flutter/flutter/] git tag --points-at 135454af32477f815a7525073027a3ff9eff1bfd
[   +9 ms] Exit code 0 from: git tag --points-at 135454af32477f815a7525073027a3ff9eff1bfd
[        ] 3.3.10
[  +37 ms] executing: [/home/vangu/development/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/home/vangu/development/flutter/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +28 ms] Unable to locate an Android SDK.
[   +3 ms] executing: [/home/vangu/development/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +44 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] Skipping pub get: version match.
[  +31 ms] Found plugin url_launcher at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.7/
[   +3 ms] Found plugin url_launcher_android at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.22/
[   +1 ms] Found plugin url_launcher_ios at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.17/
[   +1 ms] Found plugin url_launcher_linux at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[   +1 ms] Found plugin url_launcher_macos at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[   +4 ms] Found plugin url_launcher_web at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.13/
[   +1 ms] Found plugin url_launcher_windows at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +35 ms] Found plugin url_launcher at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.7/
[        ] Found plugin url_launcher_android at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.22/
[   +1 ms] Found plugin url_launcher_ios at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.17/
[   +1 ms] Found plugin url_launcher_linux at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[        ] Found plugin url_launcher_macos at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[   +1 ms] Found plugin url_launcher_web at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.13/
[        ] Found plugin url_launcher_windows at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +32 ms] Found plugin url_launcher at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.7/
[        ] Found plugin url_launcher_android at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.22/
[   +1 ms] Found plugin url_launcher_ios at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.17/
[   +1 ms] Found plugin url_launcher_linux at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[        ] Found plugin url_launcher_macos at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[        ] Found plugin url_launcher_web at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.13/
[        ] Found plugin url_launcher_windows at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +42 ms] Generating /home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +68 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/.dart_tool/package_config_subset,/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/.dart_tool/flutter_build/dart_pl
ugin_registrant.dart}
[  +15 ms] Found plugin url_launcher at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.7/
[        ] Found plugin url_launcher_android at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.22/
[        ] Found plugin url_launcher_ios at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.17/
[        ] Found plugin url_launcher_linux at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[        ] Found plugin url_launcher_macos at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[        ] Found plugin url_launcher_web at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.13/
[        ] Found plugin url_launcher_windows at /home/vangu/development/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[   +5 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/vangu/development/flutter/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/vangu/development/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/vangu/development/flutter/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.DVKAAV/flutter_tool.EJXHUT/app.dill --packages
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --source
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error
--enable-experiment=alternative-invalidation-strategy
[  +21 ms] Building Linux application...
[  +15 ms] <- compile package:blagajna_gui/main.dart
[   +2 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux
[  +30 ms] -- Configuring done
[   +9 ms] -- Generating done
[  +10 ms] -- Build files have been written to: /home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/build/linux/x64/debug
[   +7 ms] executing: ninja -C build/linux/x64/debug install
[  +30 ms] ninja: Entering directory `build/linux/x64/debug'
[+1996 ms] [1/7] Generating /home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +10 ms] FAILED: /home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/libflutter_linux_gtk.so
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_engine.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_method_call.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_method_response.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_value.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/fl_view.h
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/build/linux/x64/debug/flutter/_phony_
[   +2 ms] cd /home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/build/linux/x64/debug/flutter && /usr/bin/cmake -E env FLUTTER_ROOT=/home/vangu/development/flutter/flutter
PROJECT_DIR=/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== DART_OBFUSCATION=false TRACK_WIDGET_CREATION=true
TREE_SHAKE_ICONS=false PACKAGE_CONFIG=/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/.dart_tool/package_config.json
FLUTTER_TARGET=/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/lib/main.dart /home/vangu/development/flutter/flutter/packages/flutter_tools/bin/tool_backend.sh linux-x64 Debug
[        ] [  +68 ms] executing: uname -m
[        ] [  +33 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +5 ms] executing: [/home/vangu/development/flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 135454af32477f815a7525073027a3ff9eff1bfd
[        ] [        ] executing: [/home/vangu/development/flutter/flutter/] git tag --points-at 135454af32477f815a7525073027a3ff9eff1bfd
[        ] [  +10 ms] Exit code 0 from: git tag --points-at 135454af32477f815a7525073027a3ff9eff1bfd
[        ] [        ] 3.3.10
[        ] [  +48 ms] Unable to locate an Android SDK.
[        ] [   +2 ms] executing: [/home/vangu/development/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +43 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +78 ms] executing: [/home/vangu/development/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[   +1 ms] [        ] origin/stable
[        ] [        ] executing: [/home/vangu/development/flutter/flutter/] git ls-remote --get-url origin
[        ] [   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [        ] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +33 ms] Initializing file store
[        ] [  +12 ms] Done initializing file store
[        ] [  +37 ms] Skipping target: gen_localizations
[        ] [  +12 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +360 ms] Skipping target: unpack_linux
[        ] [ +274 ms] Skipping target: kernel_snapshot
[        ] [   +2 ms] invalidated build due to missing files: /home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/DOES_NOT_EXIST_RERUN_FOR_WILDCARD704924352
[        ] [  +74 ms] debug_bundle_linux-x64_assets: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing:
/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/DOES_NOT_EXIST_RERUN_FOR_WILDCARD704924352}
[        ] [ +140 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[        ] [ +136 ms] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +4 ms] Target debug_bundle_linux-x64_assets failed: FileSystemException: Cannot copy file to
'/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/build/flutter_assets/assets/image.bmp', path =
'/home/vangu/Documents/Programming/Andrej123456789/blagajna_gui/assets/image.bmp' (OS Error: Permission denied, errno = 13)
[   +2 ms]            #0      _File.copy.<anonymous closure> (dart:io/file_impl.dart:328:9)
[        ]            #1      _rootRunUnary (dart:async/zone.dart:1399:47)
[        ]            #2      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
[        ]            <asynchronous suspension>
[        ]            #3      ForwardingFile.copy (package:file/src/forwarding/forwarding_file.dart:26:51)
[        ]            <asynchronous suspension>
[        ]            #4      ForwardingFile.copy (package:file/src/forwarding/forwarding_file.dart:26:51)
[        ]            <asynchronous suspension>
[        ]            #5      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:131:13)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[        ]            <asynchronous suspension>
[        ]            #7      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:95:3)
[        ]            <asynchronous suspension>
[        ]            #8      BundleLinuxAssets.build (package:flutter_tools/src/build_system/targets/linux.dart:140:29)
[        ]            <asynchronous suspension>
[        ]            #9      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
[        ]            <asynchronous suspension>
[        ]            #11     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:316:32)
[        ]            <asynchronous suspension>
[        ]            #12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
[        ]            <asynchronous suspension>
[        ]            #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #20     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [   +7 ms] "flutter assemble" took 1,209ms.
[        ] [   +3 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:333:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [ +119 ms] ensureAnalyticsSent: 114ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[  +13 ms] Building Linux application... (completed in 2,134ms)
[   +1 ms] Exception: Build process failed
[   +2 ms] "flutter run" took 2,596ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +47 ms] ensureAnalyticsSent: 45ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

~/Documents/Programming/Andrej123456789/blagajna_gui master !3 ?2                                                                                                                           3s
❯ 
```

</details>

**Comment by Andrej123456789** [comment]
I fixed problem by removing `image.bmp`, it was problematic
