### ISSUE TITLE
`flutter build ipa` throws an exception within flutter_tools package

### ISSUE THREAD

**Issue by phipps980316** [flutter/flutter#118261]
Running `flutter build ipa` on CI & locally throws the following exception

```
Result bundle written to path:
               	/var/folders/rr/zm44dqqd3wq359qrwdqpzf9m0000gn/T/flutter_tools.pR9Mr7/flutter_ios_build_temp_dirTIO5EP/temporary_xcresult_bundle


[ +774 ms] Uncategorized (Xcode): Exited with status code 1

[   +1 ms] "flutter ipa" took 138,426ms.
[   +1 ms] Encountered error while archiving for device.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:374:7)
           <asynchronous suspension>
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:144:50)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +177 ms] ensureAnalyticsSent: 177ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

Flutter Version Details (also 3.3.0 & 3.3.10 gave same error)
```Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (8 months ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2```

Flutter Doctor Output
```[✓] Flutter (Channel stable, 3.0.0, on macOS 12.5.1 21G83 darwin-arm, locale en-GB)
    • Flutter version 3.0.0 at /Users/jonphipps/fvm/versions/3.0.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (8 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/jonphipps/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop)               • macos                     • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)                  • chrome                    • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

What I've tried so far:

- Running ```flutter clean```
- Clearing derived data
- Updating project to 3.3.10
- Different MacOS and Xcode versions
- Running ```flutter create .```
- Running ```flutter pub upgrade``` while on 3.3.10
- Deintegrating and reinstalling pods

The flutter counter app builds as expected also ```flutter build ios``` also functions as expected

**Comment by darshankawar** [comment]
Thanks for the report @phipps980316 
Can you provide complete error log by running `flutter build ipa -v` ? It'll be huge so you can put that in a text file and share it here.
