### ISSUE TITLE
[framework issue][Android] io.flutter.embedding.engine.FlutterJNI.onSurfaceChanged log leading to a half black screen and then ANR. 

### ISSUE THREAD

**Issue by twostarchoi** [flutter/flutter#118422]
## Steps to Reproduce

1. Execute my app `CLOi Station` on the code sample 
2. Login after input id/pwd 
3. Leave for 5 minutes on the first screen 
4. Rotate the screen from portrait to landscape
5. Show a half black screen and then ANR is occurred on my app

**Expected results: No half black screen and No ANR on my app 

**Actual results: Show a half black screen and then ANR is occurred on my app (about one or two times among ten times) 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>
main (native):tid=1 systid=30833 
#00 pc 0x4bd0c libc.so (syscall + 28)
#01 pc 0x4fb68 libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb5588 libc.so (pthread_cond_wait + 60)
#03 pc 0x15ce340 base.apk!libflutter.so 
#04 pc 0x15e8e04 base.apk!libflutter.so 
#05 pc 0x15c8384 base.apk!libflutter.so 
#06 pc 0x15cb228 base.apk!libflutter.so 
#07 pc 0x13ded4 libart.so (art_quick_generic_jni_trampoline + 148)
#08 pc 0x134564 libart.so (art_quick_invoke_stub + 548)
#09 pc 0x198e94 libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*) + 204)
#10 pc 0x30c254 libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*) + 376)
#11 pc 0x30736c libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) + 884)
#12 pc 0x63d5fc libart.so (MterpInvokeDirect + 592)
#13 pc 0x12e914 libart.so (mterp_op_invoke_direct + 20)
#14 pc 0x375214 base.apk (io.flutter.embedding.engine.FlutterJNI.onSurfaceChanged + 24)
#15 pc 0x63b310 libart.so (MterpInvokeVirtual + 1440)
#16 pc 0x12e814 libart.so (mterp_op_invoke_virtual + 20)
#17 pc 0x37b468 base.apk (io.flutter.embedding.engine.renderer.FlutterRenderer.surfaceChanged + 4)
#18 pc 0x63b310 libart.so (MterpInvokeVirtual + 1440)
#19 pc 0x12e814 libart.so (mterp_op_invoke_virtual + 20)
#20 pc 0x36a914 base.apk (io.flutter.embedding.android.FlutterSurfaceView.changeSurfaceSize + 72)
#21 pc 0x63d838 libart.so (MterpInvokeDirect + 1164)
#22 pc 0x12e914 libart.so (mterp_op_invoke_direct + 20)
#23 pc 0x36a820 base.apk 
#24 pc 0x63e098 libart.so (MterpInvokeStatic + 1120)
#25 pc 0x12e994 libart.so (mterp_op_invoke_static + 20)
#26 pc 0x36a55e base.apk (io.flutter.embedding.android.FlutterSurfaceView$1.surfaceChanged + 34)
#27 pc 0x2fed48 libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.13759017899667232327) + 268)
#28 pc 0x629a84 libart.so (artQuickToInterpreterBridge + 796)
#29 pc 0x13dff8 libart.so (art_quick_to_interpreter_bridge + 88)
#30 pc 0x203d394 memfd:jit-cache (android.view.SurfaceView.updateSurface + 5972)
#31 pc 0x20ae440 memfd:jit-cache (android.view.SurfaceView.setFrame + 96)
#32 pc 0x204def8 memfd:jit-cache (android.view.View.layout + 232)
#33 pc 0x204ad84 memfd:jit-cache (android.widget.FrameLayout.layoutChildren + 868)
#34 pc 0x205839c memfd:jit-cache (android.widget.FrameLayout.onLayout + 92)
#35 pc 0x204df64 memfd:jit-cache (android.view.View.layout + 340)
#36 pc 0x2056990 memfd:jit-cache (android.view.ViewGroup.layout + 208)
#37 pc 0x204ad84 memfd:jit-cache (android.widget.FrameLayout.layoutChildren + 868)
#38 pc 0x205839c memfd:jit-cache (android.widget.FrameLayout.onLayout + 92)
#39 pc 0x204df64 memfd:jit-cache (android.view.View.layout + 340)
#40 pc 0x2056990 memfd:jit-cache (android.view.ViewGroup.layout + 208)
#41 pc 0x204ad84 memfd:jit-cache (android.widget.FrameLayout.layoutChildren + 868)
#42 pc 0x205839c memfd:jit-cache (android.widget.FrameLayout.onLayout + 92)
#43 pc 0x204df64 memfd:jit-cache (android.view.View.layout + 340)
#44 pc 0x2056990 memfd:jit-cache (android.view.ViewGroup.layout + 208)
#45 pc 0x2099428 memfd:jit-cache (android.widget.LinearLayout.setChildFrame + 104)
#46 pc 0x2057d08 memfd:jit-cache (android.widget.LinearLayout.layoutVertical + 808)
#47 pc 0x2094424 memfd:jit-cache (android.widget.LinearLayout.onLayout + 100)
#48 pc 0x204df64 memfd:jit-cache (android.view.View.layout + 340)
#49 pc 0x2056990 memfd:jit-cache (android.view.ViewGroup.layout + 208)
#50 pc 0x204ad84 memfd:jit-cache (android.widget.FrameLayout.layoutChildren + 868)
#51 pc 0x205839c memfd:jit-cache (android.widget.FrameLayout.onLayout + 92)
#52 pc 0x20aeac8 memfd:jit-cache (com.android.internal.policy.DecorView.onLayout + 72)
#53 pc 0x204df64 memfd:jit-cache (android.view.View.layout + 340)
#54 pc 0x2056990 memfd:jit-cache (android.view.ViewGroup.layout + 208)
#55 pc 0x2058b0c memfd:jit-cache (android.view.ViewRootImpl.performLayout + 236)
#56 pc 0x134564 libart.so (art_quick_invoke_stub + 548)
#57 pc 0x198e94 libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*) + 204)
#58 pc 0x30c254 libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*) + 376)
#59 pc 0x30736c libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) + 884)
#60 pc 0x63d5fc libart.so (MterpInvokeDirect + 592)
#61 pc 0x12e914 libart.so (mterp_op_invoke_direct + 20)
#62 pc 0x3481b4 framework.jar (android.view.ViewRootImpl.performTraversals + 5304)
#63 pc 0x2fed48 libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.13759017899667232327) + 268)
#64 pc 0x629a84 libart.so (artQuickToInterpreterBridge + 796)
#65 pc 0x13dff8 libart.so (art_quick_to_interpreter_bridge + 88)
#66 pc 0x203df80 memfd:jit-cache (android.view.ViewRootImpl.doTraversal + 224)
#67 pc 0x2005afc memfd:jit-cache (android.view.ViewRootImpl$TraversalRunnable.run + 60)
#68 pc 0x203593c memfd:jit-cache (android.view.Choreographer$CallbackRecord.run + 252)
#69 pc 0x2024ca4 memfd:jit-cache (android.view.Choreographer.doCallbacks + 564)
#70 pc 0x202a46c memfd:jit-cache (android.view.Choreographer.doFrame + 1052)
#71 pc 0x203e604 memfd:jit-cache (android.view.Choreographer$FrameDisplayEventReceiver.run + 84)
#72 pc 0x201c694 memfd:jit-cache (android.os.Handler.handleCallback + 68)
#73 pc 0x200c370 memfd:jit-cache (android.os.Handler.dispatchMessage + 64)
#74 pc 0x2040950 memfd:jit-cache (android.os.Looper.loop + 1328)
#75 pc 0x13487c libart.so (art_quick_osr_stub + 60)
#76 pc 0x32a5dc libart.so (art::jit::Jit::MaybeDoOnStackReplacement(art::Thread*, art::ArtMethod*, unsigned int, int, art::JValue*) + 336)
#77 pc 0x646794 libart.so (MterpMaybeDoOnStackReplacement + 208)
#78 pc 0x133350 libart.so (MterpHelpers + 240)
#79 pc 0x44dc1e framework.jar (android.os.Looper.loop + 1082)
#80 pc 0x2fed48 libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.13759017899667232327) + 268)
#81 pc 0x306a10 libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) + 200)
#82 pc 0x307cf0 libart.so (bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) + 1780)
#83 pc 0x16f3e4 libart.so (void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*) + 54148)
#84 pc 0x1407d8 libart.so (ExecuteSwitchImplAsm + 8)
#85 pc 0x1cbae8 framework.jar 
#86 pc 0x2fee50 libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.13759017899667232327) + 532)
#87 pc 0x629a84 libart.so (artQuickToInterpreterBridge + 796)
#88 pc 0x13dff8 libart.so (art_quick_to_interpreter_bridge + 88)
#89 pc 0x1347e8 libart.so (art_quick_invoke_static_stub + 568)
#90 pc 0x198eb0 libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*) + 232)
#91 pc 0x532198 libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*) + 104)
#92 pc 0x533e8c libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long) + 1352)
#93 pc 0x4b5438 libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) + 52)
       at io.flutter.embedding.engine.FlutterJNI.nativeSurfaceChanged(Native method)
       at io.flutter.embedding.engine.FlutterJNI.onSurfaceChanged(FlutterJNI.java:613)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.surfaceChanged(FlutterRenderer.java:361)
       at io.flutter.embedding.android.FlutterSurfaceView.changeSurfaceSize(FlutterSurfaceView.java:281)
       at io.flutter.embedding.android.FlutterSurfaceView.access$300(FlutterSurfaceView.java:35)
       at io.flutter.embedding.android.FlutterSurfaceView$1.surfaceChanged(FlutterSurfaceView.java:64)
       at android.view.SurfaceView.updateSurface(SurfaceView.java:1300)
       at android.view.SurfaceView.setFrame(SurfaceView.java:646)
       at android.view.View.layout(View.java:24472)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4260)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3695)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
```

```
```

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-x64, locale ko-KR)

    • Flutter version 3.3.10 on channel stable at /Users/companionlge/project/utils/flutter

    • Upstream repository https://github.com/flutter/flutter.git

    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800

    • Engine revision 3316dd8728

    • Dart version 2.18.6

    • DevTools version 2.15.0



[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)

    • Android SDK at /Users/companionlge/Library/Android/sdk

    • Platform android-33, build-tools 31.0.0

    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java

    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

    • All Android licenses accepted.



[✓] Xcode - develop for iOS and macOS (Xcode 14.2)

    • Xcode at /Applications/Xcode.app/Contents/Developer

    • Build 14C18

    • CocoaPods version 1.11.3



[✓] Chrome - develop for the web

    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome



[✓] Android Studio (version 2021.2)

    • Android Studio at /Applications/Android Studio.app/Contents

    • Flutter plugin can be installed from:

      🔨 https://plugins.jetbrains.com/plugin/9212-flutter

    • Dart plugin can be installed from:

      🔨 https://plugins.jetbrains.com/plugin/6351-dart

    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)



[✓] VS Code (version 1.67.2)

    • VS Code at /Users/companionlge/Downloads/Visual Studio Code.app/Contents

    • Flutter extension can be installed from:

      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter



[✓] Connected device (2 available)

    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64

    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87



[✓] HTTP Host Availability

    • All required HTTP hosts are available



• No issues found!
```

</details>

![image](https://user-images.githubusercontent.com/59695960/212219664-911987ec-999d-40ce-89a3-0279632fdd79.png)

![image](https://user-images.githubusercontent.com/59695960/212220132-87f1557f-225e-487f-aaa9-e6b874c621b6.png)

![image](https://user-images.githubusercontent.com/59695960/212220171-4a5af90d-2913-4c01-b845-9f6afc7d23df.png)

**Comment by twostarchoi** [comment]
Please help me to fix this issue (a half black screen) !!

**Comment by darshankawar** [comment]
@twostarchoi 
There's no code sample or `flutter doctor -v` to know which version are you seeing this error on, so please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party plugin code along with your `flutter doctor -v`.

Also, please don't post screenshot of the exceptions, as we can't use them. Please provide the logs in properly formatted text.

**Comment by twostarchoi** [comment]
1. please provide a complete minimal reproducible code sample
--> Unfortunately i do not know which code makes this issue happen. Therefore i cannot provide the right sample code.

2. please provide your flutter doctor -v.
--> Actually I provided flutter doctor -v within ▶ Logs. And I provided that again below ▶ Logs.

3. please don't post screenshot of the exceptions, as we can't use them.
--> I removed screeshot.

4. Please provide the logs in properly formatted text.
--> I made the logs in properly formatted text below ▶ Logs.
