### ISSUE TITLE
Animation in showDialog causes --> 'package:flutter/src/widgets/framework.dart': Failed assertion: '!_dirty': is not true

### ISSUE THREAD

**Issue by juskek** [flutter/flutter#118499]
## Steps to Reproduce

1. Checkout the following [commit](https://github.com/juskek/flutter_bugs/tree/5e50a0e18f6eca67f564ca07644454c7296a7207)
2. Execute `flutter run`
3. Press 'Show Dialog' button to show working animation
4. Dismiss dialog by pressing outside barrier
5. Press 'Show Dialog' button again to show error

**Expected results:** 
Upon invoking showDialog, I was expecting to see the same animation widget again.

**Actual results:** 
Error screen with log:
```
The following assertion was thrown building FutureBuilder<bool>(state:
_FutureBuilderState<bool>#56eb9):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4610 pos 12: '!_dirty': is not
true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
```
<details>
<summary>Code sample</summary>

```dart
ElevatedButton(
            child: const Text('Show Dialog'),
            //! showDialog + LoadingWidget
            onPressed: () => showDialog(
                  barrierDismissible: true,
                  context: context,
                  builder: (context) => Dialog(
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        LoadingWidget(key: GlobalKey(), future: future),
                        const Text('Tap outside dialog to dismiss'),
                      ],
                    ),
                  ),
                )
            ),
```
```dart
class LoadingWidget extends StatefulWidget {
  const LoadingWidget({required this.future, this.size = 200, super.key});

  final double size;

  /// Return true for success, false for failure
  final Future<bool> future;
  @override
  State<LoadingWidget> createState() => _LoadingWidgetState();
}

class _LoadingWidgetState extends State<LoadingWidget> {
  final _ratioSuccess =
      100 / 107; // ratio of loading to success animation sizes
  final _ratioError = 100 / 145; // ratio of loading to error animation sizes

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      // future: Future.delayed(const Duration(milliseconds: 2500)), // for testing
      future: widget.future,
      builder: (context, snapshot) {
        // Widget child;
        if (snapshot.connectionState == ConnectionState.done) {
          if (snapshot.data as bool) {
            return LottieAnimationWidget(
                size: widget.size * _ratioSuccess,
                assetPath: 'assets/animations/loading_success.json');
          } else {
            return LottieAnimationWidget(
                size: widget.size * _ratioError,
                startValue: 0.57,
                assetPath: 'assets/animations/loading_error.json');
          }
        } else {
          return LottieLoopingAnimationWidget(
            assetPath: 'assets/animations/loading.json',
            size: widget.size,
            startValue: 0,
            stopValue: 0.193,
          );
        }
        // return child;
      },
    );
  }
}
```
```dart
class LottieAnimationWidget extends StatefulWidget {
  const LottieAnimationWidget(
      {required this.assetPath,
      this.size = 300,
      this.startValue = 0,
      super.key});

  final String assetPath;
  final double startValue;
  final double size;

  @override
  State<LottieAnimationWidget> createState() => _LottieAnimationWidgetState();
}

class _LottieAnimationWidgetState extends State<LottieAnimationWidget>
    with TickerProviderStateMixin {
  late final AnimationController _controller;

  @override
  void initState() {
    super.initState();

    _controller = AnimationController(vsync: this)..value = widget.startValue;
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: widget.size,
      width: widget.size,
      child: Lottie.asset(
        widget.assetPath,
        controller: _controller,
        onLoaded: (composition) {
          setState(() {
            _controller.duration = composition.duration;
            _controller.forward();
          });
        },
      ),
    );
  }
}
```
```dart
class LottieLoopingAnimationWidget extends StatefulWidget {
  const LottieLoopingAnimationWidget(
      {required this.assetPath,
      this.size = 300,
      this.startValue = 0,
      this.stopValue = 1,
      this.reverse = false,
      super.key});

  final String assetPath;

  /// Pass a controller if access to controller methods is required.
  final double size;
  final double startValue;
  final double stopValue;
  final bool reverse;

  @override
  State<LottieLoopingAnimationWidget> createState() =>
      _LottieLoopingAnimationWidgetState();
}

class _LottieLoopingAnimationWidgetState
    extends State<LottieLoopingAnimationWidget> with TickerProviderStateMixin {
  late final AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(vsync: this)..value = widget.startValue;
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: widget.size,
      width: widget.size,
      child: Lottie.asset(
        widget.assetPath,
        controller: _controller,
        height: widget.size,
        width: widget.size,
        onLoaded: (composition) {
          setState(() {
            _controller.duration = composition.duration;
            _controller.repeat(
              min: widget.startValue,
              max: widget.stopValue,
              reverse: widget.reverse,
              period: _controller.duration! *
                  (widget.stopValue - widget.startValue),
            );
          });
        },
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
flutter run --verbose

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
                    ╞═══════════════════════════════════════════════════════════
                    The following assertion was thrown building
FutureBuilder<bool>(state:
                    _FutureBuilderState<bool>#21da7):
                    'package:flutter/src/widgets/framework.dart': Failed assertion:
line 4610 pos 12:
                    '!_dirty': is not
                    true.
                    
                    Either the assertion indicates an error in the framework itself,
or we should provide
                    substantially
                    more information in this error message to help you determine and
fix the underlying
                    cause.
                    In either case, please report this assertion by filing a bug on
GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md
                    
                    The relevant error-causing widget was:
                      FutureBuilder<bool>

FutureBuilder:file:///Users/justinkek/Desktop/Repositories/_temp/flutter_bugs/lib/an
                      imation_widget/loading_widget.dart:25:12
                    
                    When the exception was thrown, this was the stack:
                    #2      Element.rebuild
(package:flutter/src/widgets/framework.dart:4610:12)
                    #3      ComponentElement._firstBuild
                    (package:flutter/src/widgets/framework.dart:4859:5)
                    #4      StatefulElement._firstBuild
                    (package:flutter/src/widgets/framework.dart:5041:11)
                    #5      ComponentElement.mount
(package:flutter/src/widgets/framework.dart:4853:5)
                    ...     Normal element mounting (17 frames)
                    #22     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3863:16)
                    #23     MultiChildRenderObjectElement.inflateWidget
                    (package:flutter/src/widgets/framework.dart:6435:36)
                    #24     MultiChildRenderObjectElement.mount
                    (package:flutter/src/widgets/framework.dart:6447:32)
                    ...     Normal element mounting (276 frames)
                    #300    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3863:16)
                    #301    MultiChildRenderObjectElement.inflateWidget
                    (package:flutter/src/widgets/framework.dart:6435:36)
                    #302    Element.updateChild
(package:flutter/src/widgets/framework.dart:3592:18)
                    #303    RenderObjectElement.updateChildren
                    (package:flutter/src/widgets/framework.dart:5964:32)
                    #304    MultiChildRenderObjectElement.update
                    (package:flutter/src/widgets/framework.dart:6460:17)
                    #305    Element.updateChild
(package:flutter/src/widgets/framework.dart:3570:15)
                    #306    ComponentElement.performRebuild
                    (package:flutter/src/widgets/framework.dart:4904:16)
                    #307    StatefulElement.performRebuild
                    (package:flutter/src/widgets/framework.dart:5050:11)
                    #308    Element.rebuild
(package:flutter/src/widgets/framework.dart:4604:5)
                    #309    StatefulElement.update
(package:flutter/src/widgets/framework.dart:5082:5)
                    #310    Element.updateChild
(package:flutter/src/widgets/framework.dart:3570:15)
                    #311    ComponentElement.performRebuild
                    (package:flutter/src/widgets/framework.dart:4904:16)
                    #312    Element.rebuild
(package:flutter/src/widgets/framework.dart:4604:5)
                    #313    ProxyElement.update
(package:flutter/src/widgets/framework.dart:5228:5)
                    #314    Element.updateChild
(package:flutter/src/widgets/framework.dart:3570:15)
                    #315    ComponentElement.performRebuild
                    (package:flutter/src/widgets/framework.dart:4904:16)
                    #316    Element.rebuild
(package:flutter/src/widgets/framework.dart:4604:5)
                    #317    ProxyElement.update
(package:flutter/src/widgets/framework.dart:5228:5)
                    #318    _InheritedNotifierElement.update
                    (package:flutter/src/widgets/inherited_notifier.dart:107:11)
                    #319    Element.updateChild
(package:flutter/src/widgets/framework.dart:3570:15)
                    #320    SingleChildRenderObjectElement.update
                    (package:flutter/src/widgets/framework.dart:6307:14)
                    #321    Element.updateChild
(package:flutter/src/widgets/framework.dart:3570:15)
                    #322    ComponentElement.performRebuild
                    (package:flutter/src/widgets/framework.dart:4904:16)
                    #323    StatefulElement.performRebuild
                    (package:flutter/src/widgets/framework.dart:5050:11)
                    #324    Element.rebuild
(package:flutter/src/widgets/framework.dart:4604:5)
                    #325    StatefulElement.update
(package:flutter/src/widgets/framework.dart:5082:5)
                    #326    Element.updateChild
(package:flutter/src/widgets/framework.dart:3570:15)
                    #327    SingleChildRenderObjectElement.update
                    (package:flutter/src/widgets/framework.dart:6307:14)
                    #328    Element.updateChild
(package:flutter/src/widgets/framework.dart:3570:15)
                    #329    SingleChildRenderObjectElement.update
                    (package:flutter/src/widgets/framework.dart:6307:14)
                    #330    Element.updateChild
(package:flutter/src/widgets/framework.dart:3570:15)
                    #331    ComponentElement.performRebuild
                    (package:flutter/src/widgets/framework.dart:4904:16)
                    #332    Element.rebuild
(package:flutter/src/widgets/framework.dart:4604:5)
                    #333    ProxyElement.update
(package:flutter/src/widgets/framework.dart:5228:5)
                    #334    Element.updateChild
(package:flutter/src/widgets/framework.dart:3570:15)
                    #335    ComponentElement.performRebuild
                    (package:flutter/src/widgets/framework.dart:4904:16)
                    #336    StatefulElement.performRebuild
                    (package:flutter/src/widgets/framework.dart:5050:11)
                    #337    Element.rebuild
(package:flutter/src/widgets/framework.dart:4604:5)
                    #338    BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2667:19)
                    #339    WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:882:21)
                    #340    RendererBinding._handlePersistentFrameCallback
                    (package:flutter/src/rendering/binding.dart:378:5)
                    #341    SchedulerBinding._invokeFrameCallback
                    (package:flutter/src/scheduler/binding.dart:1175:15)
                    #342    SchedulerBinding.handleDrawFrame
                    (package:flutter/src/scheduler/binding.dart:1104:9)
                    #343    SchedulerBinding._handleDrawFrame
                    (package:flutter/src/scheduler/binding.dart:1015:5)
                    #344    _invoke (dart:ui/hooks.dart:148:13)
                    #345    PlatformDispatcher._drawFrame
(dart:ui/platform_dispatcher.dart:318:5)
                    #346    _drawFrame (dart:ui/hooks.dart:115:31)
                    (elided 2 frames from class _AssertionError)
                    

══════════════════════════════════════════════════════════════════════════════════════
                    ══════════════
[  +12 ms] 
           Another exception was thrown: 'package:flutter/src/widgets/framework.dart':
Failed
           assertion: line 4610 pos 12: '!_dirty': is not true.
[  +25 ms] 
           Another exception was thrown: A RenderFlex overflowed by 99689 pixels on
the bottom.
```

```
flutter analyze
Analyzing flutter_bugs...                                               
No issues found! (ran in 2.8s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale en-SG)
    • Flutter version 3.3.10 on channel stable at
      /Users/justinkek/Desktop/Repositories/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/justinkek/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • Justin’s iPhone (mobile) • 00008101-00084C921110001E • ios            • iOS 16.1
      20B82
    • macOS (desktop)          • macos                     • darwin-x64     • macOS
      13.1 22C65 darwin-x64
    • Chrome (web)             • chrome                    • web-javascript • Google
      Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @juskek 
As I can see, you are using `lottie` package for displaying an animated widget. 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. Thank you!

**Comment by juskek** [comment]
Hi @huycozy, thanks for the advice.

I tried substituting the Lottie animation widgets with the in-built Flutter ScaleTransition widget, and the issue stopped occurring, so it seems like the problem lies with the `lottie` package. I've opened a separate issue in the Lottie repo, thanks for the help!

[Link to issue in Lottie repo](https://github.com/xvrh/lottie-flutter/issues/258)
