### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by Handelika** [flutter/flutter#118400]
## Command
```
flutter --no-color run --machine --device-id=11f164dc --start-paused --profile --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:133:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:54:22)
<asynchronous suspension>
#3      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:266:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-TR)
    • Flutter version 3.3.8 on channel stable at /Users/handelika/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (9 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/handelika/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • Redmi Note 8 (mobile) • 11f164dc                  • android-arm64 • Android 10 (API 29)
    • Handelika (mobile)    • 00008030-000208D41A46402E • ios           • iOS 14.3 18C66
    • macOS (desktop)       • macos                     • darwin-arm64  • macOS 12.6 21G115 darwin-arm
    ! Error: (null) needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+13
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
app_tracking_transparency-2.0.3
camera-0.9.8+1
camera_android-0.9.8+3
camera_avfoundation-0.9.8+6
camera_web-0.2.1+6
cloud_firestore_web-3.0.5
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
device_info_plus-3.2.4
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
file_picker-4.6.1
firebase_core-2.2.0
firebase_core_web-2.0.1
firebase_crashlytics-3.0.5
flutter_app_badger-1.5.0
flutter_downloader-1.9.1
flutter_html_to_pdf-0.7.0
flutter_inappwebview-5.7.1
flutter_plugin_android_lifecycle-2.0.7
flutter_ringtone_player-3.2.0
fluttertoast-8.1.1
geolocator-8.2.1
geolocator_android-3.2.1
geolocator_apple-2.2.3
geolocator_web-2.1.6
geolocator_windows-0.1.1
google_maps_flutter-2.2.1
google_maps_flutter_android-2.3.3
google_maps_flutter_ios-2.1.12
image_cropper-1.5.1
image_picker-0.8.6
image_picker_android-0.8.5+3
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+1
in_app_review-2.0.4
onesignal_flutter-3.4.2
path_provider-2.0.11
path_provider_android-2.0.21
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
share_plus-4.5.3
share_plus_linux-3.0.1
share_plus_macos-3.0.1
share_plus_web-3.1.0
share_plus_windows-3.0.1
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.3+1
syncfusion_flutter_pdfviewer-20.3.57
syncfusion_pdfviewer_macos-20.3.57
syncfusion_pdfviewer_web-20.3.57
syncfusion_pdfviewer_windows-20.3.57
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.1.6
url_launcher_android-6.0.21
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_player-2.4.7
video_player_android-2.3.9
video_player_avfoundation-2.3.7
video_player_web-2.0.12
webview_flutter-3.0.4
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by danagbemava-nc** [comment]
This seems like it might be related to https://github.com/flutter/flutter/issues/108812, but https://github.com/flutter/flutter/issues/108812 only shows `String: failed to connect to http://127.0.0.1:50047/` in the exception. 

Labeling for further insight from the team.
