### ISSUE TITLE
Fuchsia infra flake: `Cannot delete file, path = '/tmp/tool_state' (OS Error: No such file or directory, errno = 2)`

### ISSUE THREAD

**Issue by akbiggs** [flutter/flutter#118458]
From https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=118045 we see an occasional flake in Fuchsia infra that builds Flutter apps for Fuchsia:

```
[10280/230674](640) ACTION //src/flutter/tests/bin/pingable-flutter-component:pingable-flutter-component-debug-build-cfg_asset_manifest(//build/toolchain/fuchsia:arm64)
FAILED: gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-debug-build-cfg_pkgassets
../../build/rbe/output-scanner.sh --label //src/flutter/tests/bin/pingable-flutter-component:pingable-flutter-component-debug-build-cfg_asset_manifest\(//build/toolchain/fuchsia:arm64\) gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-debug-build-cfg_pkgassets -- ../../prebuilt/third_party/python3/linux-x64/bin/python3.8 -S ../../build/flutter/internal/gen_asset_manifest.py --flutter-root ../../third_party/dart-pkg/git/flutter --flutter-tools host_x64/dart-tools/fuchsia_asset_builder --asset-dir gen/src/flutter/tests/bin/pingable-flutter-component/build/__untraced_flutter_assets__ --packages gen/src/flutter/tests/bin/pingable-flutter-component/pingable-flutter-component-debug-build-cfg_dart_package_package_config.json --output gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-debug-build-cfg_pkgassets --component-name pingable-flutter-component-debug-build-cfg --manifest ../../src/flutter/tests/bin/pingable-flutter-component/pubspec.yaml --depfile gen/src/flutter/tests/bin/pingable-flutter-component/build/pingable-flutter-component-debug-build-cfg_pkgassets.d
Failed to decode preferences in /tmp/tool_state.
You may need to reapply any previously saved configuration with the "flutter config" command.
Unhandled exception:
PathNotFoundException: Cannot delete file, path = '/tmp/tool_state' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:618:7)
#1      _File._deleteSync (dart:io/file_impl.dart:312:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      new Config.createForTesting (package:flutter_tools/src/base/config.dart:119:15)
#6      new Config._common (package:flutter_tools/src/base/config.dart:77:19)
#7      new Config (package:flutter_tools/src/base/config.dart:37:19)
#8      new _DefaultPersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:65:18)
#9      new PersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:21:9)
#10     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:293:34)
#11     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#12     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#13     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#15     PersistentToolState.instance (package:flutter_tools/src/persistent_tool_state.dart:35:55)
#16     persistentToolState (package:flutter_tools/src/globals.dart:74:69)
#17     _defaultBotDetector (package:flutter_tools/src/globals.dart:80:24)
#18     _defaultBotDetector (package:flutter_tools/src/globals.dart)
#19     botDetector (package:flutter_tools/src/globals.dart:76:62)
#20     isRunningOnBot (package:flutter_tools/src/globals.dart:86:36)
#21     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:80:34)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#23     _rootRun (dart:async/zone.dart:1398:13)
#24     _CustomZone.run (dart:async/zone.dart:1300:19)
#25     _runZoned (dart:async/zone.dart:1803:10)
#26     runZoned (dart:async/zone.dart:1746:10)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
#28     runInContext (package:flutter_tools/src/context_runner.dart:84:18)
#29     main (file:///b/s/w/ir/cache/incremental/third_party/dart-pkg/git/flutter/packages/flutter_tools/bin/fuchsia_asset_builder.dart:35:10)
#30     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#31     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

This is coming from https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/fuchsia_asset_builder.dart#L35 which is a pretty straightforward invocation of `runInContext`. I'm concerned it might point to a flake in `runInContext` so labelling this bug as a flake.

**Comment by ricardoamador** [comment]
@christopherfujino
