### ISSUE TITLE
Unable to catch NetworkImageLoadException exception

### ISSUE THREAD

**Issue by lconer** [flutter/flutter#118586]
## Steps to Reproduce

1. Add AssetImage.png into lib folder
1. Build and run the app for iOS
2. After app will launch you will see blank page

**Expected results:** 
White Image with Asset Image text on it 

**Actual results:**
White page without image

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              width: 300,
              height: 300,
              decoration: BoxDecoration(
                shape: BoxShape.rectangle,
                image: DecorationImage(
                    image: imageTest(
                      // 'https://www.muddymatches.co.uk/data/photos/mobile/11347efed27430cabacdb73c6731aa9e_1673885453.jpg', //Correct image
                      'https://www.muddymatches.co.uk/data/photos/mobile/11347efed274cabacdb73c6731aa9e_1673885453.jpg', //Incorrect image, try catch should be used
                    ),
                    fit: BoxFit.cover),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

ImageProvider imageTest(String url) {
  try {
    return NetworkImage(url);
  } catch (e) {
    return const AssetImage('lib/AssetImage.png');
  }
}

```

</details>

Exception I'm unable to catch:
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
           The following NetworkImageLoadException was thrown resolving an image codec:
           HTTP request failed, statusCode: 403,
           https://www.muddymatches.co.uk/data/photos/mobile/11347efed274cabacdb73c6731aa9e_1673885453.jpg

           When the exception was thrown, this was the stack:
           #0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:97:9)
           <asynchronous suspension>

           Image provider:
             NetworkImage("https://www.muddymatches.co.uk/data/photos/mobile/11347efed274cabacdb73c6731aa9e_1673885453.jpg",
             scale: 1.0)
           Image key:
             NetworkImage("https://www.muddymatches.co.uk/data/photos/mobile/11347efed274cabacdb73c6731aa9e_1673885453.jpg",
             scale: 1.0)
           ════════════════════════════════════════════════════════════════════════════════════════════════════
```

<details>
  <summary>Logs</summary>

Flutter run --verbose
Had to limit it, it was to long and I was unable to submit the issue.

```
[   +2 ms] executing: rsync -8 -av --delete /Users/lukaszconer/Development/flutter_test_app/build/ios/Debug-iphonesimulator/Runner.app /Users/lukaszconer/Development/flutter_test_app/build/ios/iphonesimulator
[ +163 ms] building file list ... done
           Runner.app/
           Runner.app/Info.plist
           Runner.app/PkgInfo
           Runner.app/Runner
           Runner.app/Frameworks/App.framework/
           Runner.app/Frameworks/App.framework/App
           Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources
           Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json
           Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json
           Runner.app/Frameworks/App.framework/flutter_assets/NOTICES.Z
           Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
           Runner.app/_CodeSignature/CodeResources

           sent 39555283 bytes  received 252 bytes  79111070.00 bytes/sec
           total size is 88834857  speedup is 2.25
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun simctl install 615251AB-C965-49B4-B887-A67EA2F43317 /Users/lukaszconer/Development/flutter_test_app/build/ios/iphonesimulator/Runner.app
[ +352 ms] executing: /usr/bin/plutil -convert xml1 -o - /Users/lukaszconer/Development/flutter_test_app/build/ios/iphonesimulator/Runner.app/Info.plist
[   +4 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o - /Users/lukaszconer/Development/flutter_test_app/build/ios/iphonesimulator/Runner.app/Info.plist
[        ] <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
           <dict>
           	<key>BuildMachineOSBuild</key>
           	<string>22A400</string>
           	<key>CADisableMinimumFrameDurationOnPhone</key>
           	<true/>
           	<key>CFBundleDevelopmentRegion</key>
           	<string>en</string>
           	<key>CFBundleExecutable</key>
           	<string>Runner</string>
           	<key>CFBundleIcons</key>
           	<dict>
           		<key>CFBundlePrimaryIcon</key>
           		<dict>
           			<key>CFBundleIconFiles</key>
           			<array>
           				<string>AppIcon60x60</string>
           			</array>
           			<key>CFBundleIconName</key>
           			<string>AppIcon</string>
           		</dict>
           	</dict>
           	<key>CFBundleIcons~ipad</key>
           	<dict>
           		<key>CFBundlePrimaryIcon</key>
           		<dict>
           			<key>CFBundleIconFiles</key>
           			<array>
           				<string>AppIcon60x60</string>
           				<string>AppIcon76x76</string>
           			</array>
           			<key>CFBundleIconName</key>
           			<string>AppIcon</string>
           		</dict>
           	</dict>
           	<key>CFBundleIdentifier</key>
           	<string>com.example.flutterTestApp</string>
           	<key>CFBundleInfoDictionaryVersion</key>
           	<string>6.0</string>
           	<key>CFBundleName</key>
           	<string>flutter_test_app</string>
           	<key>CFBundlePackageType</key>
           	<string>APPL</string>
           	<key>CFBundleShortVersionString</key>
           	<string>1.0.0</string>
           	<key>CFBundleSignature</key>
           	<string>????</string>
           	<key>CFBundleSupportedPlatforms</key>
           	<array>
           		<string>iPhoneSimulator</string>
           	</array>
           	<key>CFBundleVersion</key>
           	<string>1</string>
           	<key>DTCompiler</key>
           	<string>com.apple.compilers.llvm.clang.1_0</string>
           	<key>DTPlatformBuild</key>
           	<string>20C52</string>
           	<key>DTPlatformName</key>
           	<string>iphonesimulator</string>
           	<key>DTPlatformVersion</key>
           	<string>16.2</string>
           	<key>DTSDKBuild</key>
           	<string>20C52</string>
           	<key>DTSDKName</key>
           	<string>iphonesimulator16.2</string>
           	<key>DTXcode</key>
           	<string>1420</string>
           	<key>DTXcodeBuild</key>
           	<string>14C18</string>
           	<key>LSRequiresIPhoneOS</key>
           	<true/>
           	<key>MinimumOSVersion</key>
           	<string>11.0</string>
           	<key>UIDeviceFamily</key>
           	<array>
           		<integer>1</integer>
           		<integer>2</integer>
           	</array>
           	<key>UILaunchStoryboardName</key>
           	<string>LaunchScreen</string>
           	<key>UIMainStoryboardFile</key>
           	<string>Main</string>
           	<key>UISupportedInterfaceOrientations</key>
           	<array>
           		<string>UIInterfaceOrientationPortrait</string>
           		<string>UIInterfaceOrientationLandscapeLeft</string>
           		<string>UIInterfaceOrientationLandscapeRight</string>
           	</array>
           	<key>UISupportedInterfaceOrientations~ipad</key>
           	<array>
           		<string>UIInterfaceOrientationPortrait</string>
           		<string>UIInterfaceOrientationPortraitUpsideDown</string>
           		<string>UIInterfaceOrientationLandscapeLeft</string>
           		<string>UIInterfaceOrientationLandscapeRight</string>
           	</array>
           	<key>UIViewControllerBasedStatusBarAppearance</key>
           	<false/>
           </dict>
           </plist>
[   +3 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch 615251AB-C965-49B4-B887-A67EA2F43317 com.example.flutterTestApp --enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
[ +116 ms] com.example.flutterTestApp: 87847
[        ] Waiting for observatory port to be available...
[+2933 ms] Observatory URL on device: http://127.0.0.1:56892/QBsdff0Qmnk=/
[   +3 ms] Caching compiled dill
[  +60 ms] Connecting to service protocol: http://127.0.0.1:56892/QBsdff0Qmnk=/
[  +58 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:56892/QBsdff0Qmnk=/.
[  +76 ms] DDS is listening at http://127.0.0.1:56897/xCRmij174lw=/.
[  +26 ms] Successfully connected to service protocol: http://127.0.0.1:56892/QBsdff0Qmnk=/
[  +12 ms] DevFS: Creating new filesystem on the device (null)
[   +7 ms] DevFS: Created new filesystem on the device (file:///Users/lukaszconer/Library/Developer/CoreSimulator/Devices/615251AB-C965-49B4-B887-A67EA2F43317/data/Containers/Data/Application/E2025FDE-0C60-4B42-9E5B-6A380A92B6CA/tmp/flutter_test_appsCCBih/flutter_test_app/)
[   +1 ms] Updating assets
[  +34 ms] Syncing files to device iPhone 12 Pro Max...
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:flutter_test_app/main.dart 12a420db-035c-4e82-b86b-c67905f4ab3b
[        ] <- 12a420db-035c-4e82-b86b-c67905f4ab3b
[        ] Bundle processing done.
[  +30 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device iPhone 12 Pro Max... (completed in 32ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] Connected to _flutterView/0x129035820.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:56897/xCRmij174lw=/
[ +189 ms] The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:56897/xCRmij174lw=/
[ +242 ms] 
           ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
           The following NetworkImageLoadException was thrown resolving an image codec:
           HTTP request failed, statusCode: 403,
           https://www.muddymatches.co.uk/data/photos/mobile/11347efed274cabacdb73c6731aa9e_1673885453.jpg

           When the exception was thrown, this was the stack:
           #0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:97:9)
           <asynchronous suspension>

           Image provider:
             NetworkImage("https://www.muddymatches.co.uk/data/photos/mobile/11347efed274cabacdb73c6731aa9e_1673885453.jpg",
             scale: 1.0)
           Image key:
             NetworkImage("https://www.muddymatches.co.uk/data/photos/mobile/11347efed274cabacdb73c6731aa9e_1673885453.jpg",
             scale: 1.0)
           
[+82182 ms] Application finished.
```

flutter analyze:

```
Analyzing flutter_test_app...                                           
No issues found! (ran in 1.0s)
```

flutter doctor -v

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 13.0.1 22A400 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/lukaszconer/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lukaszconer/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 615251AB-C965-49B4-B887-A67EA2F43317 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

flutter versions

```
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (6 months ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```
</details>

AssetImage.png file which should be displayed when NetworkImage unable to load a file:
![AssetImage](https://user-images.githubusercontent.com/1197895/212774911-e033523b-5a89-4ce0-8b04-532d56a5e449.png)

App and photo I expect to see:
![Simulator Screen Shot - iPhone 12 Pro Max - 2023-01-16 at 22 39 24](https://user-images.githubusercontent.com/1197895/212775549-8ae64790-f5d4-4441-98e2-c9b50e631158.png)

**Comment by iapicca** [comment]
@lconer 
try using `precacheImage`
here is a [code sample](https://dartpad.dartlang.org/?id=3145c3d6829cfb0b2bffee53300bb77c)

**Comment by huycozy** [comment]
@lconer You may use @iapicca's solution or below simple one:

```
Image.network(
  'https://www.muddymatches.co.uk/data/photos/mobile/11347efed274cabacdb73c6731aa9e_1673885453.jpg',
  errorBuilder: (context, error, stackTrace) {
    return Image.asset('assets/AssetImage.png');
  },
),
```

May be related: #118586

**Comment by lconer** [comment]
@huycozy thanks for you suggestion, but this will not work for me. I need a ImageProvider to be able to use it in BexDecoration.

@iapicca solution works for me.

I still have fillings that 
```
try {
NetworkImage(url);
}catch (e) {
}
```
should work correctly and exception should be catch by it.

**Comment by iapicca** [comment]
@lconer 
I'd 2 options:

- I believe NetworkImage works as intended

- I personally really dislike how NetworkImage and more in general how Images are handled in flutter 
and I feel that is technical debt (at best) based on a forcefully object oriented approach 
probably adopted not upset android developers

Going rhetorical: 
Is it a bug? probably not. 
Could the whole Image Widget and its parts rewritten in a more modern, consistent and functional-programming-friendly? 
Absolutely yes!

**Comment by huycozy** [comment]
Hi guys, since it's reproducible on the latest stable and master channels, labeling the issue for further insights. 

This issue may be related to a proposal at #111996 and perhaps also related to #110359.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-22.0.pre.9, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-22.0.pre.9 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 780563ce05 (88 minutes ago), 2023-01-18 09:55:33 +0900
    • Engine revision f790304409
    • Dart version 3.0.0 (build 3.0.0-122.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Dolphin 2021.3.1.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio Dolphin 2021.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio Electric Eel 2022.1.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • SM T225 (mobile) • R9JT3004VRJ                              • android-arm64  • Android 13 (API 33)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
</details>

**Comment by iapicca** [comment]
@huycozy what is reproducible exactly?
what you have here is essentially this
```dart

class Foo {
  Foo( void Function() callback);
}

void definitelyThrow() => throw Exception();

void main() => print(Foo(definitelyThrow));
```

I'm quite sure the current behavior is intended (albeit extremely annoying)

**Comment by slaci** [comment]
I ran into this issue today on flutter 3.7.3. Simply doing:

```dart
Image.network('http://google.com/image-which-not-exists.png',
        width: 50,
        height: 50,
        errorBuilder: (context, error, stackTrace) => const SizedBox.shrink());
```

Will throw an unhandled exception from [here](https://github.com/flutter/flutter/blob/3.7.5/packages/flutter/lib/src/painting/_network_image_io.dart#LL147C11-L147C11). 

The app still works and the widget will be displayed from `errorBuilder` but when I run the app with a debugger attached, then it breaks on that line (per bad image with empty stacktrace). 
`Flutter.onErrror` is not invoked thought, because if `onError` is defined and it does not throw, then the error is not propagated there (`errorBuilder` defines `onError`), so in prod it may not cause any problem (like spamming crashlytics).

So as I see it is a problem (bug) in debug. The mentioned `precacheImage()` workaround works, that does not throw an uncatchable exception. But with that solution basically I have to reimplement the network image widget.

**Comment by guopeng1994** [comment]
> I ran into this issue today on flutter 3.7.3. Simply doing:
> 
> ```dart
> Image.network('http://google.com/image-which-not-exists.png',
>         width: 50,
>         height: 50,
>         errorBuilder: (context, error, stackTrace) => const SizedBox.shrink());
> ```
> 
> Will throw an "uncatchable" exception from [here](https://github.com/flutter/flutter/blob/3.7.5/packages/flutter/lib/src/painting/_network_image_io.dart#LL147C11-L147C11).
> 
> The app still works and the widget will be displayed from `errorBuilder` but when I run the app with a debugger attached, then it breaks on that line (per bad image with empty stacktrace). `Flutter.onErrror` is not invoked thought, because if `onError` is defined and it does not throw, then the error is not propagated there (`errorBuilder` defines `onError`), so in prod it may not cause any problem (like spamming crashlytics).
> 
> So as I see it is a problem (bug) in debug. The mentioned `precacheImage()` workaround works, that does not throw an uncatchable exception. But with that solution basically I have to reimplement the network image widget.
> 
> Edit: not even `PlatformDispatcher.instance.onError` catches that exception which that `rethrow` rethrows. Anyway its a `NetworkImageLoadException`.

yeah, it's awful in development environment, because there may have lots of broken images, and we even can not catch this error!!!

**Comment by ansh-les** [comment]
Bump.

**Comment by TheCarpetMerchant** [comment]
The problem is that the exception gets rethrown, which means it's uncatchable by the context who issued the request unless by use of `catchError`, which NetworkImage does not make available.

**Comment by TheCarpetMerchant** [comment]
@huycozy Can this issue be prioritize ? I'm not even sure how an uncatchable error was ever put into the framework to begin with. There absolutely should be a callback to handle the exception, not an uncatchable rethrow...

**Comment by huycozy** [comment]
Hi @TheCarpetMerchant, this issue has been prioritized as `P2` which means the team agrees it is important to work on. Please also see [How issue prioritization works](https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities)

**Comment by CEichmueller** [comment]
it has been now more than 10 months, is there any update on this?

**Comment by alimoli** [comment]
Any news?
