### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.

### ISSUE THREAD

**Issue by hootyjeremy** [flutter/flutter#118532]
I installed a new hard drive and Windows 11 and I'm trying to re-setup flutter to work with my existing project. `flutter doctor` looks good and I can create a new boilerplate counter app and launch it on Windows with no issue. But my existing project has this error when running `flutter run -v -d windows`: 

```
[  +18 ms] Building Windows application... (completed in 7.3s)
[+2955 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +1 ms] Error launching application on Windows.
[   +2 ms] "flutter run" took 10,791ms.
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.525], locale en-US)
    • Flutter version 3.3.10 on channel stable at M:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at E:\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\twist\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.525]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.52

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

I have found a duplicate issue where `Windows 11 SDK 10.0.22000.0` solved the problem but I am already on that version so I'm not sure what to look for here.
https://github.com/flutter/flutter/issues/93635

Thanks.

**Comment by exaby73** [comment]
Hello @hootyjeremy. Have you tried the debugging steps highlighted in https://github.com/flutter/flutter/issues/115981?

**Comment by hootyjeremy** [comment]
After doing those troubleshooting steps with the Visual Studio debugger, it looks like it was an issue with the bitsdojo_window version I was using. I have updated that package and no longer getting this error. I now have a different issue but I'll work on that and see what I can find. 

https://github.com/bitsdojo/bitsdojo_window/issues/195#issuecomment-1259054065

Thanks for steps.
