### ISSUE TITLE
Gradle build failed to produce an .apk file. It's likely that this file was generated under

### ISSUE THREAD

**Issue by Vedsaga** [flutter/flutter#118671]
## Steps to Reproduce

1. Execute `flutter create test`
2.  Then replace the `app/build.gralde` file with one one share
3. then create `key.properties` file add to the android folder
4. then create `upload-keystore.jks`  add to the android folder
5. Execute `flutter build apk --release -v` 

`gradle file`
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.trail"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias System.getenv('KEY_ALIAS') ?: keystoreProperties['keyAlias']
            keyPassword System.getenv('KEY_PASSWORD') ?: keystoreProperties['keyPassword']
            storeFile System.getenv('KEYSTORE') ? file(System.getenv('KEYSTORE')) : keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword System.getenv('STORE_PASSWORD') ?: keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release

            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions "app"
    productFlavors {
        prod {
            isDefault true
            dimension "app"
        }
        demo {
            dimension "app"
            applicationIdSuffix ".demo"
        }
    }

    variantFilter { variant ->
        def names = variant.flavors*.name
            if (variant.buildType.name == "release") {
                if (names.contains("demo")) {
                    setIgnore(true)
            }
        }
    }

    android.applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "app-release.apk"
        }
    }

}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

---
**Expected results:** 
I thought that we will normal success messaging saying apk is generated at `build\....` path 

**Actual results:** 
Got error saying  ```Gradle build failed to produce an .apk file. It's likely that this file was generated under `C:\path\build`, but the tool couldn't find it.```  but, if you check the build path file does got created. 
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

Github says ` There was an error creating your Issue: body is too long, body is too long (maximum is 65536 characters). ` So, I am attaching `log.txt` file
[log.txt](https://github.com/flutter/flutter/files/10445579/log.txt)

```
[   +1 ms] :app:mergeDexDemoDebug (Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 1.465 secs.
[   +1 ms] :app:packageDemoDebug (Thread[Execution worker for ':' Thread 11,5,main]) started.
[   +1 ms] > Task :app:mergeDexProdDebug
[   +3 ms] Caching disabled for task ':app:mergeDexProdDebug' because:
[   +1 ms]   Build cache is disabled
[        ] Task ':app:mergeDexProdDebug' is not up-to-date because:
[   +1 ms]   No history is available.
[   +1 ms] The input changes require a full rebuild for incremental task ':app:mergeDexProdDebug'.
[        ] Merging to 'C:\trial-learn\trail\build\app\intermediates\dex\prodDebug\mergeDexProdDebug' with D8 from all or
a subset of dex files in C:\trial-learn\trail\build\app\intermediates\project_dex_archive\prodDebug\out,
C:\trial-learn\trail\build\app\intermediates\project_dex_archive\prodDebug\out,
C:\trial-learn\trail\build\app\intermediates\project_dex_archive\prodDebug\out,
C:\trial-learn\trail\build\app\intermediates\external_libs_dex\prodDebug\mergeExtDexProdDebug,
C:\trial-learn\trail\build\app\intermediates\project_dex_archive\prodDebug\out\f76325bf88184d3c4a8eefaa46f6dc732b656a071
4df651a0917124aa8919ca9_0.jar,
C:\trial-learn\trail\build\app\intermediates\project_dex_archive\prodDebug\out\f76325bf88184d3c4a8eefaa46f6dc732b656a071
4df651a0917124aa8919ca9_1.jar,
C:\trial-learn\trail\build\app\intermediates\project_dex_archive\prodDebug\out\f76325bf88184d3c4a8eefaa46f6dc732b656a071
4df651a0917124aa8919ca9_2.jar,
C:\trial-learn\trail\build\app\intermediates\project_dex_archive\prodDebug\out\f76325bf88184d3c4a8eefaa46f6dc732b656a071
4df651a0917124aa8919ca9_3.jar,
C:\trial-learn\trail\build\app\intermediates\project_dex_archive\prodDebug\out\f76325bf88184d3c4a8eefaa46f6dc732b656a071
4df651a0917124aa8919ca9_4.jar,
C:\trial-learn\trail\build\app\intermediates\project_dex_archive\prodDebug\out\f76325bf88184d3c4a8eefaa46f6dc732b656a071
4df651a0917124aa8919ca9_5.jar
[   +1 ms] :app:mergeDexProdDebug (Thread[included builds,5,main]) completed. Took 1.41 secs.
[        ] :app:packageProdDebug (Thread[included builds,5,main]) started.
[        ] > Task :app:packageDemoDebug
[        ] Caching disabled for task ':app:packageDemoDebug' because:
[   +1 ms]   Build cache is disabled
[        ] Task ':app:packageDemoDebug' is not up-to-date because:
[        ]   No history is available.
[   +4 ms] The input changes require a full rebuild for incremental task ':app:packageDemoDebug'.
[        ] :app:packageDemoDebug (Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 2.714 secs.
[   +1 ms] :app:createDemoDebugApkListingFileRedirect (Thread[Execution worker for ':' Thread 11,5,main]) started.
[        ] > Task :app:createDemoDebugApkListingFileRedirect
[        ] Caching disabled for task ':app:createDemoDebugApkListingFileRedirect' because:
[        ]   Build cache is disabled
[        ] Task ':app:createDemoDebugApkListingFileRedirect' is not up-to-date because:
[        ]   No history is available.
[   +1 ms] :app:createDemoDebugApkListingFileRedirect (Thread[Execution worker for ':' Thread 11,5,main]) completed.
Took 0.003 secs.
[        ] :app:assembleDemoDebug (Thread[Execution worker for ':' Thread 11,5,main]) started.
[        ] > Task :app:assembleDemoDebug
[        ] Caching disabled for task ':app:assembleDemoDebug' because:
[        ]   Build cache is disabled
[   +2 ms] Task ':app:assembleDemoDebug' is not up-to-date because:
[        ]   Task has not declared any outputs despite executing actions.
[        ] :app:assembleDemoDebug (Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 0.21 secs.
[   +1 ms] > Task :app:packageProdDebug
[        ] Caching disabled for task ':app:packageProdDebug' because:
[   +1 ms]   Build cache is disabled
[   +1 ms] Task ':app:packageProdDebug' is not up-to-date because:
[        ]   No history is available.
[        ] The input changes require a full rebuild for incremental task ':app:packageProdDebug'.
[        ] :app:packageProdDebug (Thread[included builds,5,main]) completed. Took 2.827 secs.
[        ] :app:createProdDebugApkListingFileRedirect (Thread[included builds,5,main]) started.
[   +1 ms] > Task :app:createProdDebugApkListingFileRedirect
[   +1 ms] Caching disabled for task ':app:createProdDebugApkListingFileRedirect' because:
[   +3 ms]   Build cache is disabled
[        ] Task ':app:createProdDebugApkListingFileRedirect' is not up-to-date because:
[        ]   No history is available.
[        ] :app:createProdDebugApkListingFileRedirect (Thread[included builds,5,main]) completed. Took 0.004 secs.
[        ] :app:assembleProdDebug (Thread[included builds,5,main]) started.
[        ] > Task :app:assembleProdDebug
[        ] Caching disabled for task ':app:assembleProdDebug' because:
[        ]   Build cache is disabled
[        ] Task ':app:assembleProdDebug' is not up-to-date because:
[        ]   Task has not declared any outputs despite executing actions.
[        ] :app:assembleProdDebug (Thread[included builds,5,main]) completed. Took 0.152 secs.
[        ] :app:assembleDebug (Thread[included builds,5,main]) started.
[        ] > Task :app:assembleDebug
[        ] Skipping task ':app:assembleDebug' as it has no actions.
[        ] :app:assembleDebug (Thread[included builds,5,main]) completed. Took 0.001 secs.
[   +1 ms] producer locations for task group 0 (Thread[included builds,5,main]) started.
[   +2 ms] producer locations for task group 0 (Thread[included builds,5,main]) completed. Took 0.0 secs.
[   +1 ms] AAPT2 aapt2-7.1.2-7984345-windows Daemon #0: shutdown
[        ] AAPT2 aapt2-7.1.2-7984345-windows Daemon #1: shutdown
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from
your own scripts or plugins.
[        ] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[        ] Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure
correctness.
[        ] Please consult deprecation warnings for more details.
[        ] BUILD SUCCESSFUL in 58s
[        ] 70 actionable tasks: 68 executed, 2 up-to-date
[        ] Watched directory hierarchies: [C:\trial-learn\trail\android]
[ +596 ms] Running Gradle task 'assembleDebug'... (completed in 104.0s)
[   +7 ms] LocalFile: 'C:\trial-learn\trail\android\build.gradle' provides AGP version: 7.1.2
[   +9 ms] Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under
           C:\trial-learn\trail\build, but the tool couldn't find it.
[  +12 ms] "flutter run" took 1,05,717ms.
[   +8 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +268 ms] ensureAnalyticsSent: 262ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1

```

```
C:\trial-learn\trail>flutter analyze
Analyzing trail...
No issues found! (ran in 5.0s)
```

```
```

</details>

![image](https://user-images.githubusercontent.com/59083528/213162008-3d7c27f9-486d-4b97-85e5-7aa51cfb5d85.png)

**Comment by danagbemava-nc** [comment]
Hi @Vedsaga, it looks like you have flavors set up in your project. Do you get the same issue when you specify a flavor? 

You can do so by running `flutter build apk --release --flavor=<enter flavor name here>`

**Comment by Vedsaga** [comment]
> Hi @Vedsaga, it looks like you have flavors set up in your project. Do you get the same issue when you specify a flavor?
> You can do so by running `flutter build apk --release --flavor=<enter flavor name here>`

Hi @danagbemava-nc , no when I specify the flavor flag then, I don't get the error, but I am not specfiy the flavor for a reason because, when I do specify the flavor then apk file name is saving to `flavor -release.apk` which I don't want that is why I am avoiding to putting flavor. I want to gradle to add flavor.

**Comment by danagbemava-nc** [comment]
AFAICT, You will need to specify a flavor when you're building if you have flavors set up in your project. 
It seems this is the way gradle has been designed. See https://issuetracker.google.com/issues/36988145. 

There's not much flutter can do regarding that. 

Closing from here. 

Thank you
