### ISSUE TITLE
Swift unable to find symbols at compile-time that are present in the iOS artifacts

### ISSUE THREAD

**Issue by ricoberger** [flutter/flutter#118832]
Hi, this is a duplicate of https://github.com/flutter/flutter/issues/97968 reported by @gaaclarke, sorry that I had to open a new issue, but I'm not able to comment on the other issue.

I'm also able to reproduce this on two different MacBooks (both with an M1 chip), one with a new installation of Xcode, so that I'm not sure if this is really just related to some `weird caching happening locally`.

## Steps to Reproduce

When I want to switch to background threads on iOS as shown in the following:

```diff
+let taskQueue = registrar.messenger.makeBackgroundTaskQueue()
+let channel = FlutterMethodChannel(name: "kubenav.io", binaryMessenger: registrar.messenger(), codec: FlutterStandardMethodCodec.sharedInstance, taskQueue: taskQueue)
-let channel = FlutterMethodChannel(name: "kubenav.io", binaryMessenger: registrar.messenger())
```

I receive the following error for `flutter run`:

```
[   +4 ms] Swift Compiler Error (Xcode): Value of type '() -> any FlutterBinaryMessenger' has no member 'makeBackgroundTaskQueue'
           /Users/ricoberger/Documents/GitHub/kubenav/kubenav/ios/Runner/KubenavPlugin.swift:8:40

[        ] Swift Compiler Error (Xcode): Extra argument 'taskQueue' in call
           /Users/ricoberger/Documents/GitHub/kubenav/kubenav/ios/Runner/KubenavPlugin.swift:9:160

[        ] Swift Compiler Error (Xcode): Function produces expected type 'FlutterStandardMethodCodec'; did you mean to call it with '()'?
           /Users/ricoberger/Documents/GitHub/kubenav/kubenav/ios/Runner/KubenavPlugin.swift:9:133

[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14 Pro.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

The complete file can be found here: the source code of the whole file can be found here: https://github.com/kubenav/kubenav/blob/main/ios/Runner/KubenavPlugin.swift

<details>
  <summary>Logs</summary>

```
Analyzing kubenav...
No issues found! (ran in 4.1s)
```

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale de-DE)
    • Flutter version 3.3.10 on channel stable at /Users/ricoberger/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ricoberger/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ricoberger/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 89F2C125-1D72-4516-AEEB-1EBECB5A143A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ricoberger,

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can investigate this?

I tried adding the portion commented out from your code, but for me, it seems like the apis are not available. 

<img width="1263" alt="Screenshot 2023-01-20 at 09 55 03" src="https://user-images.githubusercontent.com/88313112/213667088-227cb762-ad61-4240-8288-b6be026667ad.png">



Thank you

**Comment by ricoberger** [comment]
Hi @danagbemava-nc, I will do so, but what you shared is exactly the problem. The question for me is why is `makeBackgroundTaskQueue` not defined.

If I go to the definition of `FlutterPluginRegistrar` and from there to the definition of `FlutterBinaryMessenger` in Xcode it seems to be defined:

```objc
FLUTTER_DARWIN_EXPORT
@protocol FlutterBinaryMessenger <NSObject>
/// TODO(gaaclarke): Remove optional when macos supports Background Platform Channels.
@optional
- (NSObject<FlutterTaskQueue>*)makeBackgroundTaskQueue;

- (FlutterBinaryMessengerConnection)
    setMessageHandlerOnChannel:(NSString*)channel
          binaryMessageHandler:(FlutterBinaryMessageHandler _Nullable)handler
                     taskQueue:(NSObject<FlutterTaskQueue>* _Nullable)taskQueue;
```

I'm not sure if it helps, but I also tried to import `Flutter.FlutterBinaryMessenger` in the swift file via:

```swift
import Flutter.FlutterBinaryMessenger
```

If I then jump to definition of the import in Xcode it looks as follow and doesn't contain the `makeBackgroundTaskQueue`, but only the comment:

```swift
public protocol FlutterBinaryMessenger : NSObjectProtocol {

    /// TODO(gaaclarke): Remove optional when macos supports Background Platform Channels.
```

**Comment by danagbemava-nc** [comment]
@ricoberger, thanks for the clarification. I don't think the sample will be necessary anymore. 

I saw the same thing as reported in https://github.com/flutter/flutter/issues/118832#issuecomment-1398316657 when I looked up the definitions. 

Labeling for further investigation. 

The code sample I used is attached below. 

[ct.zip](https://github.com/flutter/flutter/files/10466746/ct.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-GB)
    • Flutter version 3.3.10 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

```
[!] Flutter (Channel master, 3.7.0-24.0.pre.22, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
    • Flutter version 3.7.0-24.0.pre.22 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee9c9b6927 (7 hours ago), 2023-01-20 01:27:09 -0500
    • Engine revision 3876320cbd
    • Dart version 3.0.0 (build 3.0.0-136.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```
</details>

**Comment by jmagman** [comment]
Huh I can reproduce this too.  As @ricoberger says only the required methods are in the generated Swift protocol:
```
public protocol FlutterBinaryMessenger : NSObjectProtocol {

    /// TODO(gaaclarke): Remove optional when macos supports Background Platform Channels.
    
    /**
     * Sends a binary message to the Flutter side on the specified channel, expecting
     * no reply.
     *
     * @param channel The channel name.
     * @param message The message.
     */
    func send(onChannel channel: String, message: Data?)

    
    /**
     * Sends a binary message to the Flutter side on the specified channel, expecting
     * an asynchronous reply.
     *
     * @param channel The channel name.
     * @param message The message.
     * @param callback A callback for receiving a reply.
     */
    func send(onChannel channel: String, message: Data?, binaryReply callback: FlutterBinaryReply? = nil)

    
    /**
     * Registers a message handler for incoming binary messages from the Flutter side
     * on the specified channel.
     *
     * Replaces any existing handler. Use a `nil` handler for unregistering the
     * existing handler.
     *
     * @param channel The channel name.
     * @param handler The message handler.
     * @return An identifier that represents the connection that was just created to the channel.
     */
    func setMessageHandlerOnChannel(_ channel: String, binaryMessageHandler handler: FlutterBinaryMessageHandler? = nil) -> FlutterBinaryMessengerConnection

    
    /**
     * Clears out a channel's message handler if that handler is still the one that
     * was created as a result of
     * `setMessageHandlerOnChannel:binaryMessageHandler:`.
     *
     * @param connection The result from `setMessageHandlerOnChannel:binaryMessageHandler:`.
     */
    func cleanUpConnection(_ connection: FlutterBinaryMessengerConnection)
}

```
Objective-C code here:
https://github.com/flutter/engine/blob/3fead63ba1008d86f4c8f386896643f82bbfcb99/shell/platform/darwin/common/framework/Headers/FlutterBinaryMessenger.h#L47-L103

I would have expected it to generate an `optional func` for `-makeBackgroundTaskQueue` and -setMessageHandlerOnChannel:::`.  Is there some annotation we can add to the Objective-C header to make it visible to Swift?

cc @hellohuanlin who might be interested in this.

**Comment by jtdLab** [comment]
When will the definitions be available from swift?

**Comment by hellohuanlin** [comment]
@gaaclarke curious have tried moving the full definition of `FlutterTaskQueue` from  `platform_message_handler_ios.h` to `FlutterBinaryMessenger.h`?

**Comment by gaaclarke** [comment]
> @gaaclarke curious we have tried moving the full definition of `FlutterTaskQueue` from `platform_message_handler_ios.h` to `FlutterBinaryMessenger.h`?

Yea, I'm doing that right now.  I think that should be enough to fix it, starting to work on it: https://github.com/flutter/engine/pull/47348. It's a bit tricky because I wanted to make it private.  Unfortunately some people have hacked around the issue so I may have to take that into consideration.

**Comment by gaaclarke** [comment]
fyi @chickenblood this has landed, it will take a while to roll to you though.

**Comment by chickenblood** [comment]
Many thanks for the turnaround.
