### ISSUE TITLE
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed.

### ISSUE THREAD

**Issue by b-will-c** [flutter/flutter#118946]
After 5 to 60 minutes of editing a `TextField`, occasionally this gets thrown:

```
Unable to parse JSON message:
The document is empty.

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#89cd3(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 2:04:44.497059)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
package:flutter/…/services/hardware_keyboard.dart:432
#3      HardwareKeyboard._assertEventIsRegular
package:flutter/…/services/hardware_keyboard.dart:443
#4      HardwareKeyboard.handleKeyEvent
package:flutter/…/services/hardware_keyboard.dart:535
#5      KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:881
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:197
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:387
#8      _invoke2 (dart:ui/hooks.dart:186:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
(elided 2 frames from class _AssertionError)
```

The `Unable to parse JSON` with `Exception caught by services library` then goes on to be repeated for another 10 to 25 times.

The whole application doesn't crash, as it's possible to manually step over this via the debugger, but it's certainly disconcerting.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Type in random gibberish for 5 to 15 minutes
3. Watch it scream at you in the console

**Expected results:** 

Type for as long as needed, exit as required.

**Actual results:** 

Random freezing and `Could not load source 'dart:core-patch/errors_patch.dart': <source not available>.` 

<details>
<summary>Code sample</summary>

```dart

void main() {
  // using Riverpod's providers
  runApp(const ProviderScope(
    // created just for the sake of this reproduction
    child: KeyboardCrasher() 
    // child: App() 
  ));
}

class KeyboardCrasher extends HookConsumerWidget { // riverpod + flutter_hooks
  const KeyboardCrasher({super.key});
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final text = useTextEditingController();
    return MaterialApp(
      home: Scaffold(
        body: Container(
          child: TextField(
            controller: text,
            minLines: 100,
            maxLines: null,
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Unable to parse JSON message:
The document is empty.

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#ecc81(logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), repeat: false) and its data: RawKeyEventDataWindows#3c00f(keyCode: 160, scanCode: 42, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
package:flutter/…/services/raw_keyboard.dart:1
Failed assertion: line 682 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      RawKeyboard.handleRawKeyEvent
package:flutter/…/services/raw_keyboard.dart:682
#3      KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:878
#4      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:197
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:387
#6      _invoke2 (dart:ui/hooks.dart:186:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
(elided 2 frames from class _AssertionError)
```

```
   info - Avoid unnecessary containers - lib\main.dart:17:15 - avoid_unnecessary_containers
```

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2486], locale en-GB)
    • Flutter version 3.3.10 on channel stable at E:\Development\Flutter\3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\Programs\AndroidSDK
    • Platform android-30, build-tools 30.0.3
    • Java binary at: E:\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.21)
    • Visual Studio at E:\Development\VS\Community
    • Visual Studio Community 2019 version 16.11.33027.164
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at E:\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Additional note: if the actual application tends to longer respond to any Ctrl / Shift / Backspace after the crash, the reproducible sample keeps working fine with all keys on the `Continue (F5)` and `Step Over (F10)` in the VS Code's debugger. Sometimes the `Continue` will refuse to get back to normal, however, and will begin going through random lines of code, instead. `Step Over` does appear to be able to help in that case - but it's barely a viable solution for an app to be deployed to real users later on.

**Comment by danagbemava-nc** [comment]
Hi @b-will-c, this issue is known and is being tracked in https://github.com/flutter/flutter/issues/99653. 

Feel free to share your observations in the issue linked above. 

Closing from here as duplicate. 

Thank you
