### ISSUE TITLE
Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists, after deleting the app from firebase console and re-running flutterfire configure in my existing flutter project root

### ISSUE THREAD

**Issue by sivang** [flutter/flutter#118904]
## Steps to Reproduce

Create a new app in firebase console.
Start a new flutter app locally in your development environment.
Install all required dependencies for `flutterfire` (-and ofc flutter cli etc)
Configure your flutter app using `flutterfire configure` , choose the app you created previously in firebase console.
Run your app (I'm doing this always to a MacOS target as I'm trying to develop a desktop app) make sure it initialized with Firebase (basically, no runtime exception on the init Future)
Shut down your app.
Delete your firebase console app.
recreate the firebase console app with the same base name as before, this doesn't matter as firebase ass a random uid with hyphen to the app's name.
Reconfigure you flutter local app with `fireflutter configure`, this time choose the newly created app after deleting the previous by the same name from your firebase console.
Rerun your app with `flutter run`.
 
**Expected results:** App runs and displays UI etc.

**Actual results:** App hangs up in suspension on the async await of the firebase init, giving the logged error in console:
```ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists
#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:134:11)
```

**Extra Notes**: Before this change I could actually store stuff to my cloud firestore and retrieve some items from it, but nowhere in the firebase console could these documents and collection be found. Despite this, again - it was possible to store documents to a collection and retrieve them programmatically in Flutter(!!) Where is this `[DEFAULT]` app? is it an in memory thing or does it refer to some sort of cloud instance at the firebase backend?

<details>
<summary>Code sample</summary>

I'm initializing the app as `firebase_options.dart` was created successfully and includes all the required data.

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // await FirebaseApi.addRandomUsers(Users.initUsers);
  runApp(const MyApp());
}
```

</details>

<details>
  <summary>Logs</summary>

```
Building macOS application...                                           
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/duplicate-app] A Firebase App named "[DEFAULT]" already exists
#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:134:11)
<asynchronous suspension>
#1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
<asynchronous suspension>
#2      main (package:executiveapp/main.dart:11:3)
<asynchronous suspension>
```

Attached analyze issues, however they are widget and style stuff not related (AFAICT) to the existing app issue.

```
   info • Avoid `print` calls in production code • lib/api/firebase_api.dart:17:5 • avoid_print
   info • Avoid `print` calls in production code • lib/api/firebase_api.dart:24:9 • avoid_print
   info • Unused import: 'package:meta/meta.dart' • lib/model/user.dart:1:8 • unused_import
   info • Avoid using private types in public APIs • lib/page/chat_page.dart:16:3 • library_private_types_in_public_api
   info • Avoid `print` calls in production code • lib/page/chats_page.dart:22:23 • avoid_print
   info • Unused import: 'dart:async' • lib/utils.dart:1:8 • unused_import
   info • Unused import: 'dart:convert' • lib/utils.dart:2:8 • unused_import
   info • Prefer const with constant constructors • lib/widget/chat_body_widget.dart:29:18 • prefer_const_constructors
   info • SizedBox for whitespace • lib/widget/chat_body_widget.dart:33:18 • sized_box_for_whitespace
   info • SizedBox for whitespace • lib/widget/chat_header_widget.dart:20:13 • sized_box_for_whitespace
   info • SizedBox for whitespace • lib/widget/chat_header_widget.dart:32:13 • sized_box_for_whitespace

11 issues found. (ran in 4.3s)

```

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale en-IL)
    • Flutter version 3.3.10 on channel stable at /Users/sivan/FlutterInstall2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available


```

</details>

**Comment by iapicca** [comment]
@sivang looks like a [flutterfire](https://github.com/firebase/flutterfire/issues) issue

**Comment by sivang** [comment]
@iapicca should I open there as well? Got an idea to where this `[DEFAULT]` app is created so I can perhaps delete it to continue?

**Comment by iapicca** [comment]
> @iapicca should I open there as well? 

@sivang 
I think the issue should be opened **_only_** there

**Comment by darshankawar** [comment]
Closing from here as this is not a Flutter issue.
