### ISSUE TITLE
Warning about finding CupertinoIcons when building a web app with only material

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#119074]
> Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons), but found (MaterialIcons). This usually means you are referring to font families in an IconData class but not including them in the assets section of your
pubspec.yaml, are missing the package that would include them, or are missing "uses-material-design: true".
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7680 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Compiling lib/main.dart for the Web...                           1,853ms

**Comment by danagbemava-nc** [comment]
Hi @kevmoo, I think this might have been fixed in a more recent version of master. I attempted to reproduce this with the counter app, but the only message I got was about the font assets being tree-shaken. I didn't see anything about the cupertino_icons not being found. See the logs attached below

```
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 1236 bytes (99.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7504 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
```

Can you confirm if this is the case for you as well?

[web_log.log](https://github.com/flutter/flutter/files/10496823/web_log.log)


<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel master, 3.7.0-26.0.pre.14, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
    • Flutter version 3.7.0-26.0.pre.14 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 351466aea6 (60 minutes ago), 2023-01-24 21:46:24 -0800
    • Engine revision bffb983524
    • Dart version 3.0.0 (build 3.0.0-157.0.dev)
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```
</details>

**Comment by christopherfujino** [comment]
> Hi @kevmoo, I think this might have been fixed in a more recent version of master. I attempted to reproduce this with the counter app, but the only message I got was about the font assets being tree-shaken. I didn't see anything about the cupertino_icons not being found. See the logs attached below
> 
> ```
> Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 1236 bytes (99.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
> Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7504 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
> ```
> 
> Can you confirm if this is the case for you as well?
> 
> [web_log.log](https://github.com/flutter/flutter/files/10496823/web_log.log)
> 
> flutter doctor -v

@danagbemava-nc you are correct, however there was some additional discussion offline around this issue. Users would still run into this if they explicitly removed the `cupertino_icons` package from the pubspec.yaml. It is unclear what the "best" solution in the tool would be, however we asked kevmoo to file this for tracking.

**Comment by christopherfujino** [comment]
@danagbemava-nc thanks for checking and verifying however that this works with a newly created app!

**Comment by levifeldman** [comment]
Hi, I am getting this error on flutter 3.10.2. I do not include use cupertino icons in my pubspec.yaml.

**Comment by danger-ahead** [comment]
> Hi, I am getting this message on flutter 3.10.2. I do not include use cupertino icons in my pubspec.yaml.

same here. +1

**Comment by guavacoderepo** [comment]
"flutter build web --no-tree-shake-icons " this worked for me !!!

**Comment by kevmoo** [comment]
@guavacoderepo – you WANT to tree-shake icons, though. If you're using material icons.

The warning is annoying (and we should fix it), but it shouldn't hurt anything.

**Comment by danger-ahead** [comment]
> @guavacoderepo – you WANT to tree-shake icons, though. If you're using material icons.
> 
> The warning is annoying (and we should fix it), but it shouldn't hurt anything.

I noticed this same warning while building a release version of Android APK just now.

**Comment by atebitftw** [comment]
What's the entry to put back into pubspec to remove this warning?

**Comment by bakboem** [comment]
Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons), but found (MaterialIcons). This usually means you
are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the
package that would include them, or are missing "uses-material-design: true".
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7916 bytes (99.5% reduction). Tree-shaking can be
disabled by providing the --no-tree-shake-icons flag when building your app.

[✓] Flutter (Channel stable, 3.10.1, on macOS 13.4 22F66 darwin-x64, locale zh-Hans-KR)
    • Flutter version 3.10.1 on channel stable at /Users/bakbeom/install/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (4 weeks ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/bakbeom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/bakbeom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4 22F66 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by greensopinion** [comment]
The following fixed the issue for me:

`flutter pub add cupertino_icons`

**Comment by BolisettySujith** [comment]
I was also facing the same issue, does this cause any performance issues in the app ? or can we skip it ?

**Comment by TiffApps** [comment]
How about not putting this warning if we don't use/include cupertino icons?

**Comment by nohli** [comment]
Exactly since the Flutter 3.10.0 update my app doesn't build for web any more (iOS and Android are fine).

I don't use any `CupertinoIcons`, and adding `cupertino_icons` didn't help, but stops complaining about `Expected to find fonts...`.

<details>
  <summary>Codemagic logs with cupertino_icons</summary>

```
== Building for Web ==

> flutter build web --release

Upgrading .gitignore
Compiling lib/main.dart for the Web...                          
Codepoint 32 not found in font, aborting.

Codepoint 32 not found in font, aborting.

Codepoint 32 not found in font, aborting.

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 10904 bytes (99.3% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 1272 bytes (99.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Target web_release_bundle failed: IconTreeShakerException: Font subsetting failed with exit code 255.

To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command
#0      IconTreeShaker.subsetFont (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:216:7)
<asynchronous suspension>
#1      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:128:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:106:3)
<asynchronous suspension>
#4      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:401:29)
<asynchronous suspension>
#5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:198:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             26.9s
Exception: Failed to compile application for the Web.


Build failed :|
Failed to build for Web
```

</details>

<details>
  <summary>Codemagic logs without cupertino_icons</summary>

```
== Building for Web ==

> flutter build web --release

Upgrading .gitignore
Compiling lib/main.dart for the Web...                          
Expected to find fonts for (packages/font_awesome_flutter/FontAwesomeSolid, MaterialIcons, packages/font_awesome_flutter/FontAwesomeBrands, packages/font_awesome_flutter/FontAwesomeRegular, packages/cupertino_icons/CupertinoIcons), but found (MaterialIcons, packages/font_awesome_flutter/FontAwesomeBrands, packages/font_awesome_flutter/FontAwesomeRegular, packages/font_awesome_flutter/FontAwesomeSolid). This usually means you are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the package that would include them, or are missing "uses-material-design: true".
Codepoint 32 not found in font, aborting.

Codepoint 32 not found in font, aborting.

Codepoint 32 not found in font, aborting.

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 10904 bytes (99.3% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Target web_release_bundle failed: IconTreeShakerException: Font subsetting failed with exit code 255.

To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command
#0      IconTreeShaker.subsetFont (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:216:7)
<asynchronous suspension>
#1      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:128:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:106:3)
<asynchronous suspension>
#4      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:401:29)
<asynchronous suspension>
#5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:198:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             26.9s
Exception: Failed to compile application for the Web.


Build failed :|
Failed to build for Web
```

</details>

**Comment by gaddlord** [comment]
Still present in latest 3.13.0 stable.

Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons, packages/syncfusion_flutter_datagrid/UnsortIcon, packages/syncfusion_flutter_datagrid/FilterIcon), but found (MaterialIcons, packages/syncfusion_flutter_datagrid/UnsortIcon, packages/syncfusion_flutter_datagrid/FilterIcon)

**Comment by smp27768** [comment]
Hotfix currently in the works to resolve this issue: [https://github.com/flutter/flutter/issues/132711#issuecomment-1684152978](https://github.com/flutter/flutter/issues/132711#issuecomment-1684152978)

**Comment by Flutterboy17** [comment]
> 

I am getting the same issue. How to resolve it?

**Comment by christopherfujino** [comment]
> Hotfix currently in the works to resolve this issue: [#132711 (comment)](https://github.com/flutter/flutter/issues/132711#issuecomment-1684152978)

that is an unrelated fix

**Comment by WajahtAli** [comment]
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 1236 bytes (99.6% reduction). Tree-shaking can be
disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7700 bytes (99.5% reduction). Tree-shaking   
can be disabled by providing the --no-tree-shake-icons flag when building your app.
i am getting this kindly help how to fix

**Comment by jhj0517** [comment]
still happens to me when I build a bundle.
I don't know if it's because of this or not, but after upgrading Flutter SDK build time has increased significantly. (about 1 hour)

Here's my `flutter doctor -v` .

```
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.19045.3324], locale ko-KR)
    • Flutter version 3.13.2 on channel stable at C:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (2 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
```

**Comment by soulinmaikadua** [comment]
I have a same issue

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1412 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

`flutter doctor -v`

[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5 22G74 darwin-arm64, locale en-LA)
    • Flutter version 3.13.3 on channel stable at /Users/soulin/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (5 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

**Comment by Chancilson** [comment]
This is not an error you are seeing, it is an informational message that Flutter displays when it is optimizing the Material Icons and Cupertino Icons tree in Flutter web. This optimization reduces the size of the font files used to render these icons, saving space and improving the performance of your Flutter web app.

However, if you want to disable this optimization and keep the original size of the icon font files, you can use the --no-tree-shake-icons option when running the flutter build web command. This will prevent Flutter from optimizing these icons. The command would look like this:


`flutter build web --no-tree-shake-icons`



Keep in mind that when you disable optimization, your icon font files may be larger, which may affect the performance and size of your web application. Therefore, make this decision based on the specific needs of your project.

**Comment by faizanIqbal001** [comment]
This is due to png file. Don't Generate Launcher icons from a jpeg image
Always Use png file

**Comment by neoacevedo** [comment]
> This is due to png file. Don't Generate Launcher icons from a jpeg image Always Use png file

No, that's not the issue. If you run a basic flutter app without touching something you anyway will receive the same warning.

**Comment by mcsken** [comment]
Oddly for me, removing the existing `uses-material-design: true` from my `pubspec.yaml` removes the warning. I would imagine removing this line wouldn't have an impact since [`ThemeData.useMaterial3` is now set to true by default since Flutter 3.16.](https://docs.flutter.dev/release/breaking-changes/material-3-default)

**Comment by rumax** [comment]
> uses-material-design

If it’s not an error (it’s actually a warning), why does it appear in the logs? Building production software with warnings is generally considered bad practice, just as it is to disable optimisations like tree shaking. Both should be addressed appropriately to ensure a clean and efficient production build.

**Comment by MarcoPeli** [comment]
After 2 years the issue still reproduces on my side. Does anyone care to fix?

**Comment by kevmoo** [comment]
@MarcoPeli – I think this is just low-priority. It doesn't affect the quality/speed of shipped apps.

PRs for a fix are welcome!

**Comment by guidezpl** [comment]
I think I may have found clues to the cause with some logging. These are the icons used

```
cupertino_icons CupertinoIcons 62629.0
cupertino_icons CupertinoIcons 62419.0
cupertino_icons CupertinoIcons 62415.0
cupertino_icons CupertinoIcons 62318.0
```

`0xF4A5`: `CupertinoIcons.search`
`0xF3D3`: `CupertinoIcons.chevron_right`
`0xF3CF`: `CupertinoIcons.back`
`0xF36E`: `CupertinoIcons.clear_thick_circled`

Now, why are these four icons finding themselves in the build for an app which doesn't use `cupertino_icons` and `CupertinoIcons` at all, I do not know.
