### ISSUE TITLE
AnimationController .reset() dismissed too early callback

### ISSUE THREAD

**Issue by shadowmelds** [flutter/flutter#119120]
## Steps to Reproduce

AnimationController
use ` controller.reset();` animation callback dismissed,but animation doesn't not yet end。

<details>
<summary>Code sample</summary>

```dart

  @override
  void initState() {
    super.initState();
    controller =
        AnimationController(duration: const Duration(milliseconds: 200), vsync: this);
    animation = ColorTween(begin: BaseColor.transparent, end: BaseColor.meldSurfaceTouchRipper).animate(controller);
    controller.addListener(() {

      print("controller===${controller.value}===${controller.status}");

      if (controller.value == 0.0 && controller.status == AnimationStatus.dismissed) {
        // appWindow.minimize(); too early callback ，In the Windows minimized window，color not reset，Restoration window still has color
      }
    });
  }

```

</details>

<details>
  <summary>Logs</summary>

```
flutter: controller===1.0===AnimationStatus.completed
flutter: controller===0.0===AnimationStatus.dismissed
```

```
```

```
```

</details>

## temporary solution

````dart
controller.reset();
controller.animateTo(0.01);

animation.addListener((){
    if(controller.value == 0.01 && animation.status == AnimationStatus.completed) {
        appWindow.minimize();
    }
});

````

**Comment by exaby73** [comment]
Hello @shadowmelds. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by shadowmelds** [comment]
OS: Windows 11

```
flutter create test

flutter pub add bitsdojo_window
```

<details><summary>edit ./windows/runner/main.cpp</summary>
<p>

#### Inside your application folder, go to windows\runner\main.cpp and add these two lines at the beginning of the file:

```
#include <bitsdojo_window_windows/bitsdojo_window_plugin.h>
auto bdw = bitsdojo_window_configure(BDW_CUSTOM_FRAME | BDW_HIDE_ON_STARTUP);
```

</p>
</details>


<details><summary>main.dart</summary>
<p>

#### main.dart

```dart
import 'package:flutter/material.dart';
import 'package:bitsdojo_window/bitsdojo_window.dart';
import 'package:test/minimize_button.dart';

void main() {
  runApp(const MyApp());
  doWhenWindowReady(() {
    final win = appWindow;
    const initialSize = Size(600, 450);
    win.minSize = initialSize;
    win.size = initialSize;
    win.alignment = Alignment.center;
    win.title = "Custom window with Flutter";
    win.show();
  });
}

const borderColor = Color(0xFF805306);

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: WindowBorder(
          color: borderColor,
          width: 1,
          child: Column(
            children: [
              RightSide(),
              Expanded(child: Container(
                color: Color(0xFFF6FCF7),
                alignment: Alignment.center,
                child: MinimizeButton(),
              ))
            ],
          )
        ),
      ),
    );
  }
}

class RightSide extends StatelessWidget {
  const RightSide({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(children: [
        WindowTitleBarBox(
          child: Row(
          children: [Expanded(child: MoveWindow()), const WindowButtons()],
          ),
        )
      ]),
    );
  }
}

final buttonColors = WindowButtonColors(
    iconNormal: const Color(0xFF805306),
    mouseOver: const Color(0xFFF6A00C),
    mouseDown: const Color(0xFF805306),
    iconMouseOver: const Color(0xFF805306),
    iconMouseDown: const Color(0xFFFFD500));

final closeButtonColors = WindowButtonColors(
    mouseOver: const Color(0xFFD32F2F),
    mouseDown: const Color(0xFFB71C1C),
    iconNormal: const Color(0xFF805306),
    iconMouseOver: Colors.white);

class WindowButtons extends StatelessWidget {
  const WindowButtons({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        MinimizeWindowButton(colors: buttonColors),
        MaximizeWindowButton(colors: buttonColors),
        CloseWindowButton(colors: closeButtonColors),
      ],
    );
  }
}
```

</p>
</details>

<details><summary>minimize_button.dart</summary>
<p>

#### minimize_button.dart

```dart
import 'package:bitsdojo_window/bitsdojo_window.dart';
import 'package:flutter/cupertino.dart';

class MinimizeButton extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MinimizeButtonState();
}

class _MinimizeButtonState extends State<MinimizeButton> with SingleTickerProviderStateMixin{

  late Animation<Color?> ripperAnimation;
  late AnimationController ripperController;
  bool _onMinimize = false;

  @override
  void initState() {
    super.initState();
    ripperController =
        AnimationController(duration: const Duration(milliseconds: 100), vsync: this);
    ripperAnimation = ColorTween(begin: Color(0x00000000), end: Color(0x33557C5C)).animate(ripperController);

    ripperController.addListener(() {
      print("controller===${ripperController.value}===${ripperController.status}===${ripperAnimation.value == Color(0x00000000)}");

      // /* Bad
      if (_onMinimize && ripperController.value == 0.0 && ripperAnimation.status == AnimationStatus.dismissed) {
        _onMinimize = false;
        appWindow.minimize();
      }
      // */

      // /* Good
      // if (_onMinimize && ripperController.value == 0.01 && ripperAnimation.status == AnimationStatus.completed) {
      //   _onMinimize = false;
      //   appWindow.minimize();
      //   ripperController.animateTo(0.0);
      // }
      // */
    });
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(animation: ripperAnimation, builder: (context, child){
      return Container(
        child: MouseRegion(
            onEnter: (event) {
              ripperController.forward();
            },
            onExit: (event) {
              ripperController.reverse();
            },
            child: GestureDetector(
                onTap: () {
                  _onMinimize = true;

                  // /* Bad
                  ripperController.reset();
                  // */

                  // /* Good
                  // ripperController.reset();
                  // ripperController.animateTo(0.01);
                  // */
                },
                child: Container(
                    width: 200,
                    height: 200,
                    decoration: BoxDecoration(
                        color: ripperAnimation.value,
                        shape: BoxShape.circle
                    ),

                child:  Center(
                  child: Container(
                    width: 100,
                    height: 100,
                    decoration: BoxDecoration(
                        color: Color(0xFF739278),
                        borderRadius: BorderRadius.circular(100)
                      //more than 50% of width makes circle
                    ),
                  ),
                )
              )
            )
        ),
      );
    });
  }
  @override
  void dispose() {
    ripperController.dispose();
    super.dispose();
  }
}
```

</p>
</details>

and run on Windows.

---

<details><summary>flutter doctor -v</summary>
<p>

#### flutter doctor -v

```
   [√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [版本 10.0.22621.900], locale zh-CN)
    • Flutter version 3.3.10 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\shadowmeld\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\shadowmeld\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-18.0.2.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\shadowmeld\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.900]        
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.52
```

</p>
</details>


<details><summary>flutter run -v</summary>
<p>

#### flutter run -v

```
   [  +60 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 135454af32477f815a7525073027a3ff9eff1bfd
[        ] executing: [C:\flutter/] git tag --points-at 135454af32477f815a7525073027a3ff9eff1bfd    
[  +59 ms] Exit code 0 from: git tag --points-at 135454af32477f815a7525073027a3ff9eff1bfd
[        ] 3.3.10
[  +39 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +43 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +70 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +67 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.   
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.        
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.        
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.       
[  +43 ms] executing: C:\Users\shadowmeld\AppData\Local\Android\Sdk\platform-tools\adb.exe devices
-l
[  +57 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.   
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.        
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.        
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.       
[  +60 ms] Multiple devices found:
[  +33 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.900]
[   +1 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.52
[        ] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+5862 ms] q
[   +8 ms] "flutter run" took 6,104ms.
[  +19 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DeviceManager._chooseOneOfAvailableDevices
(package:flutter_tools/src/device.dart:314:7)
           <asynchronous suspension>
           #2      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:302:37)   
           <asynchronous suspension>
           #3      FlutterCommand.findAllTargetDevices
           (package:flutter_tools/src/runner/flutter_command.dart:1410:28)
           <asynchronous suspension>
           #4      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:489:15)  
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1330:5)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +232 ms] ensureAnalyticsSent: 228ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

</p>
</details>

**Comment by exaby73** [comment]
Hello @shadowmelds. Unfortunately, I cannot use this code as it includes a 3rd party library (`bitsdojo_window`). Please provide steps to reproduce without any 3rd party libraries, and make sure it's minimal and complete.
