### ISSUE TITLE
`flutter pub get` crashes if there is a plugin using legacy yaml format without defining androidPackage

### ISSUE THREAD

**Issue by gabrielgarciagava** [flutter/flutter#119127]
Crash found using flutter 3.7.0. No problem in version 3.3.7.

Crash caused in the first of the following 2 lines:
```
      final String androidPackage = pluginYaml['androidPackage'] as String;
      if (androidPackage != null) {
```
Considering the first line tries to cast to `String`, and the second lines checks for nullability, I believe that what has changed is that flutter tools now runs with null-safety, but this line of code was not adapted for it. I would also expect a warning on the `if` line.

## Steps to Reproduce

1. Create a flutter project
2. Add a dependecy to a plugin that uses legacy yaml format, but does not define `androidPackage` (e.g. https://pub.dev/packages/ios_app_group)
3. Run `flutter pub get`

## Logs

<details>
<summary>Logs</summary>

```
_CastError: type 'Null' is not a subtype of type 'String' in type cast

#0      new Plugin._fromLegacyYaml (package:flutter_tools/src/plugins.dart:198:66)
#1      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:88:19)
#2      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#3      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#4      PackagesGetCommand.usageValues (package:flutter_tools/src/commands/packages.dart:102:36)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1423:15)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

```
[32m[✓][39m Flutter (Channel stable, 3.7.0, on macOS 12.5 21G72 darwin-arm64, locale en-NL)
    [32m•[39m Flutter version 3.7.0 on channel stable at ---
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision b06b8b2710 (34 hours ago), 2023-01-23 16:55:55 -0800
    [32m•[39m Engine revision b24591ed32
    [32m•[39m Dart version 2.19.0
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    [32m•[39m Android SDK at /Users/gabrielgava/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0-rc1
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 13.3)
    [32m•[39m Xcode at /Applications/Xcode-13.3.0.app/Contents/Developer
    [32m•[39m Build 13E113
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.74.3)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.58.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @gabrielgarciagava, I see `androidPackage` is defined in https://github.com/mingchen/ios_app_group/blob/2acfd54af7b3e2647c3cd5d23478a9d3dc328f70/pubspec.yaml#L28

Did you perhaps want to reference a different plug? 

I didn't get any issues when I used `ios_app_group`

<details>
<summary>repro</summary>

```
nexus@Daniels-MBP nevercode % flutter create lpft
Signing iOS app for device deployment using developer identity: "Apple
Development: Daniel Agbemava (QBN99L4HAJ)"
Creating project lpft...
Running "flutter pub get" in lpft...
Resolving dependencies in lpft... (1.7s)
+ async 2.10.0
+ boolean_selector 2.1.1
+ characters 1.2.1
+ clock 1.1.1
+ collection 1.17.0
+ cupertino_icons 1.0.5
+ fake_async 1.3.1
+ flutter 0.0.0 from sdk flutter
+ flutter_lints 2.0.1
+ flutter_test 0.0.0 from sdk flutter
+ js 0.6.5 (0.6.6 available)
+ lints 2.0.1
+ matcher 0.12.13 (0.12.14 available)
+ material_color_utilities 0.2.0
+ meta 1.8.0
+ path 1.8.2 (1.8.3 available)
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.9.1
+ stack_trace 1.11.0
+ stream_channel 2.1.1
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ test_api 0.4.16 (0.4.18 available)
+ vector_math 2.1.4
Changed 24 dependencies in lpft!
Wrote 127 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider:
https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd lpft
  $ flutter run

Your application code is in lpft/lib/main.dart.

nexus@Daniels-MBP nevercode % cd lpft
nexus@Daniels-MBP lpft % flutter pub add ios_app_group
Resolving dependencies...
+ ios_app_group 1.0.2
  js 0.6.5 (0.6.6 available)
  matcher 0.12.13 (0.12.14 available)
  path 1.8.2 (1.8.3 available)
  test_api 0.4.16 (0.4.18 available)
Changed 1 dependency!
The plugin `ios_app_group` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if
this plugin supports the Android V2 embedding. Otherwise, consider removing it
since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to
the V2 embedding: https://flutter.dev/go/android-plugin-migration.
nexus@Daniels-MBP lpft % flutter pub get
Running "flutter pub get" in lpft...
Resolving dependencies...
  js 0.6.5 (0.6.6 available)
  matcher 0.12.13 (0.12.14 available)
  path 1.8.2 (1.8.3 available)
  test_api 0.4.16 (0.4.18 available)
Got dependencies!
The plugin `ios_app_group` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if
this plugin supports the Android V2 embedding. Otherwise, consider removing it
since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to
the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
    • Flutter version 3.7.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
</details>

**Comment by gabrielgarciagava** [comment]
Ah, that is true. Unfortunatelly I don't have any public example. The issue happens in a local plugin of my project. I fixed it locally by upgrading the package to use the new yaml format instead.

But it is easily reproducible, just removing the `androidPackage` from any package using the legacy format will trigger the crash. The code is also trying to do a null safe cast to a variable that is already cast to `String` which does not make sense.

Should I maybe create an example project with a local plugin affected by this problem?

**Comment by gabrielgarciagava** [comment]
Doing some research in the public iOS plugins, I could not find any example with such problem. Almost all plugin already upgraded to new yaml format. Any new plugin will probably already use the new format as well.

In this case, I think this issue has very low priority. In my case, I just upgraded the yaml to the new format to deal with the crash. Thanks for checking @danagbemava-nc

**Comment by danagbemava-nc** [comment]
Hi @gabrielgarciagava, looking at the current source code for `Plugin._fromLegacyYaml` on the `master` branch, it looks it is being checked properly for null safety. See https://github.com/flutter/flutter/blob/c9affdba9dcd2ac6569092509a44c9c84eba46f5/packages/flutter_tools/lib/src/plugins.dart#L192

I do see the issue in the source code for 3.7.0, but since it has been updated on the master channel to properly check for null values, I will be closing this since it has been fixed, per our triage policy. 

Thank you

**Comment by gabrielgarciagava** [comment]
Ah, that is indeed correct @danagbemava-nc 
Thank you for checking.
