### ISSUE TITLE
Incompatible checksum version crash

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#11915]
```
$ flutter build apk
Initializing gradle...                                0.7s
Resolving dependencies...                            204.1s
Running 'gradlew assembleRelease'...                      
Error during AOT snapshot checksum check: Invalid argument(s): Incompatible checksum version: null
#0      new Checksum.fromJson (package:flutter_tools/src/base/build.dart:92)
#1      _buildAotSnapshot (package:flutter_tools/src/commands/build_aot.dart:296)
<asynchronous suspension>
#2      buildAotSnapshot (package:flutter_tools/src/commands/build_aot.dart:101)
<asynchronous suspension>
#3      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:63)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#5      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#6      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#10     new Future.sync (dart:async/future.dart:222)
#11     CommandRunner.run (package:args/command_runner.dart:109)
#12     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#13     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#14     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#15     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1467)
#19     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#20     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#22     main (file:///home/j/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


```

```
$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/j/flutter/
    • Framework revision ea8da05f25 (11 hours ago), 2017-09-01 22:01:17 -0700
    • Engine revision 29e0c1c281
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/j/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /home/j/Android/Sdk
    • Java binary at: /home/j/.local/share/umake/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/j/.local/share/umake/android/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.2)
    ✗ Flutter plugin version 15.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 172.3317.48
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[-] IntelliJ IDEA Community Edition (version 2017.1)
    ✗ Flutter plugin version 15.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 172.3317.48
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • None

```

**Comment by Hixie** [comment]
@JFixby Do you know the steps to reproduce?

**Comment by JFixby** [comment]
It turned out the machine I was working on had damaged RAM. Possibly this was the reason for checksum mismatch.
