### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by cputoaster** [flutter/flutter#119165]
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. flutter upgrade, from 3.3.10 to 3.7

```
Downloading Material fonts...                                      253ms

Oops; flutter has exited unexpectedly: "PathNotFoundException: Directory listing failed, path = '/opt/homebrew/Caskroom/flutter/2.5.3/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/fonts/' (OS Error: No such file or directory, errno = 2)".
A crash report has been written to /opt/homebrew/Caskroom/flutter/2.5.3/flutter/flutter_01.log.
```

## Logs
FileSystemException: Directory listing failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      ArtifactUpdater.removeDownloadedFiles (package:flutter_tools/src/cache.dart:1245:23)
#5      CachedArtifact.update (package:flutter_tools/src/cache.dart:829:21)
<asynchronous suspension>
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#7      PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:168:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
```
```
[✓] Flutter

**Comment by darshankawar** [comment]
Labeling this issue, since there's no exact duplicate with stacktrace already filed.

/cc @christopherfujino

**Comment by darshankawar** [comment]
@cputoaster 
Are you getting this error consistently ?

From the log, it seems to have failed after trying to download the files. Could be cache or one-off case. Can you try that same upgrade again to see if you still get same crash again ?

**Comment by cputoaster** [comment]
ok, did a flutter precache, downgrade and upgrade, that seems to have fixed it.
