### ISSUE TITLE
[SelectionArea] Selecting text inside a scrollable throws a null check exception

### ISSUE THREAD

**Issue by JeisonSanches** [flutter/flutter#119355]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Long tap and select "Select all" on the context menu
3. Scroll to the latest highlited snippet of text and do a long tap

**Expected results:** 

The context menu should reappear to handle the current selection

**Actual results:** 

The context menu is not showing up, with the code throwing a exception

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SelectionArea(
        child: ListView.builder(
          itemCount: 25,
          itemBuilder: (_, index) {
            return Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                "[$index] - ${"Lorem Ipsum is simply dummy text" * 12}",
              ),
            );
          },
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[+4750 ms] D/EGL_emulation(  727): app_time_stats: avg=4751.11ms min=4751.11ms max=4751.11ms count=1
[+1015 ms] D/EGL_emulation(  727): app_time_stats: avg=168.43ms min=22.94ms max=732.31ms count=6
[+2274 ms] D/EGL_emulation(  727): app_time_stats: avg=1129.16ms min=15.25ms max=2243.07ms count=2
[+1063 ms] D/EGL_emulation(  727): app_time_stats: avg=132.86ms min=64.91ms max=174.86ms count=8
[+2732 ms] 
                    ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
                    The following _CastError was thrown while handling a gesture:
                    Null check operator used on a null value

                    When the exception was thrown, this was the stack:
                    #0      _SelectableRegionContainerDelegate._updateLastEdgeEventsFromGeometries (package:flutter/src/widgets/selectable_region.dart:1279:68)
                    #1      _SelectableRegionContainerDelegate.handleSelectWord (package:flutter/src/widgets/selectable_region.dart:1314:5)
                    #2      MultiSelectableSelectionContainerDelegate.dispatchSelectionEvent (package:flutter/src/widgets/selectable_region.dart:2014:18)
                    #3      _SelectionContainerState.dispatchSelectionEvent (package:flutter/src/widgets/selection_container.dart:187:29)
                    #4      SelectableRegionState._selectWordAt (package:flutter/src/widgets/selectable_region.dart:857:18)
                    #5      SelectableRegionState._handleTouchLongPressStart (package:flutter/src/widgets/selectable_region.dart:472:5)
                    #6      LongPressGestureRecognizer._checkLongPressStart.<anonymous closure> (package:flutter/src/gestures/long_press.dart:720:75)
                    #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
                    #8      LongPressGestureRecognizer._checkLongPressStart (package:flutter/src/gestures/long_press.dart:720:11)
                    #9      LongPressGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/long_press.dart:618:5)
                    #10     PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:643:5)
                    #11     PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:586:41)
                    #15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
                    (elided 3 frames from class _Timer and dart:async-patch)

                    Handler: "onLongPressStart"
                    Recognizer:
                      LongPressGestureRecognizer#f1d3b
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
```

```
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [versÆo 10.0.22621.1105], locale pt-BR)
    • Flutter version 3.7.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (4 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\jeison\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\jeison\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [versÆo 10.0.22621.1105]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 109.0.1518.70

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

[device-2023-01-27-152027.webm](https://user-images.githubusercontent.com/16905038/215164409-3a91c6d8-ca20-4bee-b31b-4cc8371430a8.webm)

**Comment by darshankawar** [comment]
Thanks for the report @JeisonSanches 
Looking at the error log, it seems similar to https://github.com/flutter/flutter/issues/115787, so please follow-up in that issue for further updates and also upvote the issue for team's attention.
Closing this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.
