### ISSUE TITLE
Build error running flutter_gallery

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11937]
Attempted to run flutter_gallery just now.  The first time I got the error below.  After that I did `flutter build clean` and it fixed it.  

I had previously run flutter_gallery with 0783ec906 I believe, and just now I used 93438245f047cb0e199a32fc6d428ee0f7f588b6.  Is there some error handling we need to add to our build code to catch this case?  Will alpha users hit this when we next push alpha?

@aam @jakobr-google @cbracken 

```
Launching lib/main.dart on SAMSUNG SM G730A in profile mode...
Running 'gradlew assembleProfile'...                      
Error during AOT snapshot checksum check: Invalid argument(s): Incompatible checksum version: null
#0      new Checksum.fromJson (package:flutter_tools/src/base/build.dart:92)
#1      _buildAotSnapshot (package:flutter_tools/src/commands/build_aot.dart:296)
<asynchronous suspension>
#2      buildAotSnapshot (package:flutter_tools/src/commands/build_aot.dart:101)
<asynchronous suspension>
#3      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:63)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#5      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#6      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#10     new Future.sync (dart:async/future.dart:222)
#11     CommandRunner.run (package:args/command_runner.dart:109)
#12     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#13     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#14     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#15     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1467)
#19     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#20     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#22     main (file:///src/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Error detected in pubspec.yaml:
#/properties/flutter: unallowed additional property plugin
^C
```

**Comment by cbracken** [comment]
Hrm - the existing code is meant to verify snapshot version and rebuild in case of a mismatch; it definitely should exit. Taking a look.

**Comment by cbracken** [comment]
Putting together a fix now.
