### ISSUE TITLE
Flutter 3.7.0 build error "Error (Xcode): No file or variants found for asset:" on CodeMagic

### ISSUE THREAD

**Issue by 781flyingdutchman** [flutter/flutter#119388]
## Steps to Reproduce

1. Build the app on CodeMagic using Flutter channel Stable (version 3.7.0-stable, XCode 14.2):
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (4 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
3. Build fails with error "Error (Xcode): No file or variants found for asset: terms_and_conditions.txt." (a file that is included in the assets folder and listen in the pubspec.yaml

The exact same app (i.e. same github branch etc) build successfully when I set the CodeMag Flutter version to 3.3.9 stable, where I had it on my desktop machine and where it also builds fine.
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (9 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

## Logs

<details>
<summary>Logs</summary>

```
PhaseScriptExecution Run\ Script /Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target 'Runner' from project 'Runner')
                cd /Users/builder/clone/ios
                export ACTION\=install
  <LOTS MORE EXPORT STATEMENTS>
                /bin/sh -c /Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh
            ♦ /Users/builder/programs/flutter/bin/flutter --verbose assemble --no-version-check --output=/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=arm64 -dSdkRoot=/Applications/Xcode-14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk -dSplitDebugInfo= -dTreeShakeIcons=true -dTrackWidgetCreation=false -dDartObfuscation=false -dAction=install --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= -dCodesignIdentity=55EAE7D7F8F38B382083D715944EA98D4B88AB49 release_ios_bundle_flutter_assets
            [  +16 ms] executing: sysctl hw.optional.arm64
            [   +6 ms] Exit code 0 from: sysctl hw.optional.arm64
            [        ] hw.optional.arm64: 1
            [        ] executing: [/Users/builder/programs/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
            [   +9 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
            [        ] b06b8b2710955028a6b562f5aa6fe62941d6febf
            [        ] executing: [/Users/builder/programs/flutter/] git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
            [  +52 ms] Exit code 0 from: git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
            [        ] 3.7.0
            [   +7 ms] executing: [/Users/builder/programs/flutter/] git rev-parse --abbrev-ref HEAD
            [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
            [        ] stable
            [   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
            [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
            [  +64 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
            [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
            [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
            [   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
            [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
            [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
            [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
            [   +8 ms] Initializing file store
            [  +11 ms] release_unpack_ios: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/builder/programs/flutter/packages/flutter_tools/lib/src/build_system/targets/ios.dart,/Users/builder/programs/flutter/bin/internal/engine.version}
            [ +102 ms] Skipping lipo for non-fat file /Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/Flutter.framework/Flutter
            [ +874 ms] Skipping target: gen_localizations
            [   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/builder/clone/.dart_tool/package_config_subset}
            [   +1 ms] release_unpack_ios: Complete
            [  +62 ms] Found plugin flutter_pdfview at /Users/builder/programs/flutter/.pub-cache/git/flutter_pdfview-aa8ee15e667a8533ad49fb0fcf5e39758d04250b/
            [   +4 ms] Found plugin app_settings at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/app_settings-4.2.0/
            [   +3 ms] Found plugin background_downloader at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/background_downloader-2.0.1/
            [   +4 ms] Found plugin cloud_firestore_web at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/cloud_firestore_web-2.8.10/
            [   +1 ms] Found plugin connectivity_plus at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/connectivity_plus-2.3.9/
            [   +1 ms] Found plugin connectivity_plus_linux at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/connectivity_plus_linux-1.3.1/
            [   +1 ms] Found plugin connectivity_plus_macos at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/connectivity_plus_macos-1.2.6/
            [   +1 ms] Found plugin connectivity_plus_web at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/connectivity_plus_web-1.2.5/
            [   +1 ms] Found plugin connectivity_plus_windows at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/connectivity_plus_windows-1.2.2/
            [   +7 ms] Found plugin firebase_core at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/firebase_core-1.24.0/
            [   +1 ms] Found plugin firebase_core_web at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/firebase_core_web-1.7.3/
            [        ] Found plugin firebase_crashlytics at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/firebase_crashlytics-2.9.0/
            [   +1 ms] Found plugin firebase_messaging at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/firebase_messaging-13.1.0/
            [   +1 ms] Found plugin firebase_messaging_web at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/firebase_messaging_web-3.2.0/
            [   +3 ms] Found plugin flutter_plugin_android_lifecycle at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
            [   +3 ms] Found plugin google_maps_flutter at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/google_maps_flutter-2.2.3/
            [   +1 ms] Found plugin google_maps_flutter_android at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/google_maps_flutter_android-2.4.3/
            [        ] Found plugin google_maps_flutter_ios at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/google_maps_flutter_ios-2.1.13/
            [   +4 ms] Found plugin in_app_purchase at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/in_app_purchase-3.1.1/
            [        ] Found plugin in_app_purchase_android at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/in_app_purchase_android-0.2.3+9/
            [   +1 ms] Found plugin in_app_purchase_storekit at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/in_app_purchase_storekit-0.3.4+1/
            [   +2 ms] Found plugin location at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/location-4.4.0/
            [   +1 ms] Found plugin location_web at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/location_web-3.1.1/
            [   +3 ms] Found plugin package_info_plus at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/package_info_plus-1.4.2/
            [        ] Found plugin package_info_plus_linux at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/package_info_plus_linux-1.0.5/
            [        ] Found plugin package_info_plus_macos at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/package_info_plus_macos-1.3.0/
            [   +1 ms] Found plugin package_info_plus_web at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/package_info_plus_web-1.0.6/
            [        ] Found plugin package_info_plus_windows at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/package_info_plus_windows-1.0.5/
            [        ] Found plugin path_provider at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
            [        ] Found plugin path_provider_android at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
            [        ] Found plugin path_provider_foundation at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
            [        ] Found plugin path_provider_linux at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.7/
            [   +1 ms] Found plugin path_provider_windows at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/path_provider_windows-2.0.7/
            [   +4 ms] Found plugin shared_preferences at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/shared_preferences-2.0.17/
            [   +1 ms] Found plugin shared_preferences_android at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/shared_preferences_android-2.0.15/
            [        ] Found plugin shared_preferences_foundation at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/shared_preferences_foundation-2.1.2/
            [        ] Found plugin shared_preferences_linux at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/shared_preferences_linux-2.1.3/
            [   +1 ms] Found plugin shared_preferences_web at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/shared_preferences_web-2.0.4/
            [        ] Found plugin shared_preferences_windows at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/shared_preferences_windows-2.1.3/
            [   +1 ms] Found plugin sqflite at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/sqflite-2.2.4+1/
            [   +5 ms] Found plugin wakelock at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/wakelock-0.6.2/
            [        ] Found plugin wakelock_macos at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/wakelock_macos-0.4.0/
            [   +1 ms] Found plugin wakelock_web at /Users/builder/programs/flutter/.pub-cache/hosted/pub.dev/wakelock_web-0.4.0/
            [  +14 ms] gen_dart_plugin_registrant: Complete
            [        ] kernel_snapshot: Starting due to {}
            [   +4 ms] /Users/builder/programs/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/builder/programs/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /Users/builder/programs/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --compact-async --aot --tfa --packages /Users/builder/clone/.dart_tool/package_config.json --output-dill /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/app.dill --depfile /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/kernel_snapshot.d --source file:///Users/builder/clone/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///Users/builder/clone/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error package:avinavi/main.dart
            [+19597 ms] kernel_snapshot: Complete
            [+1382 ms] aot_assembly_release: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/builder/programs/flutter/packages/flutter_tools/lib/src/build_system/targets/ios.dart,/Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/app.dill,/Users/builder/programs/flutter/bin/internal/engine.version,/Users/builder/programs/flutter/bin/internal/engine.version}
            [   +3 ms] targetingApplePlatform = true
            [        ] extractAppleDebugSymbols = true
            [        ] Will strip AOT snapshot manually after build and dSYM generation.
            [        ] executing: /Users/builder/programs/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64 --deterministic --snapshot_kind=app-aot-assembly --assembly=/Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/arm64/snapshot_assembly.S /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/app.dill
            [+17549 ms] executing: sysctl hw.optional.arm64
            [   +4 ms] Exit code 0 from: sysctl hw.optional.arm64
            [        ] hw.optional.arm64: 1
            [        ] executing: /usr/bin/arch -arm64e xcrun cc -arch arm64 -miphoneos-version-min=11.0 -isysroot /Applications/Xcode-14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk -c /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/arm64/snapshot_assembly.S -o /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/arm64/snapshot_assembly.o
            [+3767 ms] executing: /usr/bin/arch -arm64e xcrun clang -arch arm64 -miphoneos-version-min=11.0 -isysroot /Applications/Xcode-14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk -dynamiclib -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -install_name @rpath/App.framework/App -o /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/arm64/App.framework/App /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/arm64/snapshot_assembly.o
            [ +415 ms] executing: /usr/bin/arch -arm64e xcrun dsymutil -o /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/arm64/App.framework.dSYM /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/arm64/App.framework/App
            [ +498 ms] executing: /usr/bin/arch -arm64e xcrun strip -x /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/arm64/App.framework/App -o /Users/builder/clone/.dart_tool/flutter_build/9d094cd39e4176b998aa98b6e1c29618/arm64/App.framework/App
            [ +363 ms] aot_assembly_release: Complete
            [   +1 ms] release_ios_bundle_flutter_assets: Starting due to {}
            [  +98 ms] Error detected in pubspec.yaml:
            [   +1 ms] Sending archive event if usage enabled.
            [        ] Persisting file store
            [   +5 ms] Done persisting file store
            [   +5 ms] "flutter assemble" took 44,943ms.
            [        ] Running 0 shutdown hooks
            [        ] Shutdown hooks complete
            [        ] exiting with code 1
            error: [        ] No file or variants found for asset: terms_and_conditions.txt.

            [   +6 ms] Target release_ios_bundle_flutter_assets failed: Exception: Failed to bundle asset files.
                       #0      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:62:5)
                       <asynchronous suspension>
                       #1      IosAssetBundle.build (package:flutter_tools/src/build_system/targets/ios.dart:515:34)
                       <asynchronous suspension>
                       #2      ReleaseIosApplicationBundle.build (package:flutter_tools/src/build_system/targets/ios.dart:622:7)
                       <asynchronous suspension>
                       #3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
                       <asynchronous suspension>
                       #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
                       <asynchronous suspension>
                       #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:337:32)
                       <asynchronous suspension>
                       #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
                       <asynchronous suspension>
                       #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                       <asynchronous suspension>
                       #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
                       <asynchronous suspension>
                       #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
                       <asynchronous suspension>
                       #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
                       <asynchronous suspension>
                       #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #14     main (package:flutter_tools/executable.dart:91:3)
                       <asynchronous suspension>

            [   +1 ms] 
                       #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                       #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:354:7)
                       <asynchronous suspension>
                       #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
                       <asynchronous suspension>
                       #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                       <asynchronous suspension>
                       #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
                       <asynchronous suspension>
                       #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
                       <asynchronous suspension>
                       #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
                       <asynchronous suspension>
                       #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #10     main (package:flutter_tools/executable.dart:91:3)
                       <asynchronous suspension>
            Failed to package /Users/builder/clone.

            /Users/builder/clone/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'Firebase' from project 'Pods')
            /Users/builder/clone/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'ReachabilitySwift' from project 'Pods')
            /Users/builder/clone/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'PromisesObjC' from project 'Pods')
            /Users/builder/clone/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'GoogleUtilities' from project 'Pods')
            /Users/builder/clone/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'GoogleDataTransport' from project 'Pods')
            /Users/builder/clone/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'FirebaseCoreInternal' from project 'Pods')
            /Users/builder/clone/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'FirebaseCoreDiagnostics' from project 'Pods')
            /Users/builder/clone/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'FirebaseCrashlytics' from project 'Pods')

            Result bundle written to path:
            	/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/flutter_tools.3VXbDo/flutter_ios_build_temp_dirBfJu0C/temporary_xcresult_bundle


            ** ARCHIVE FAILED **

              <SKIPPED>
[   +6 ms] Failed to build iOS app
[  +48 ms] Error (Xcode): [        ] No file or variants found for asset: terms_and_conditions.txt.

[   +2 ms] "flutter ipa" took 136,108ms.
[   +1 ms] Encountered error while archiving for device.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:528:7)
           <asynchronous suspension>
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:295:50)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1


Build failed :|
Failed to build for iOS

```

Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (4 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
</details>

**Comment by mas222** [comment]
I had the same problem and the fix or workaround for me was to put in the full relative path instead of starting inside the assets folder.

before: - icon.jpg
after: - assets/icon.jpg

**Comment by 781flyingdutchman** [comment]
Thank you!  That was it, though it's interesting that this never was an issue until this Flutter version.
