### ISSUE TITLE
Failed assertion: line 4605 pos 12: '_lifecycleState != _ElementLif

### ISSUE THREAD

**Issue by eximius313** [flutter/flutter#119305]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Click "es" button

**Expected results:**
No exception

**Actual results:**
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4605 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      Element.markNeedsBuild
#3      State.setState
#4      _TestScreenState._resetState
#5      _TestScreenState.dispose
#6      StatefulElement.unmount
#7      _InactiveElements._unmount
#8      _InactiveElements._unmount.<anonymous closure>
#9      SingleChildRenderObjectElement.visitChildren
#10     _InactiveElements._unmount
#11     _InactiveElements._unmount.<anonymous closure>
#12     ComponentElement.visitChildren
#13     _InactiveElements._unmount
#14     _InactiveElements._unmount.<anonymous closure>
#15     SingleChildRenderObjectElement.visitChildren
#16     _InactiveElements._unmount
#17     _InactiveElements._unmount.<anonymous closure>
#18     SingleChildRenderObjectElement.visitChildren
#19     _InactiveElements._unmount
#20     _InactiveElements._unmount.<anonymous closure>
#21     ComponentElement.visitChildren
#22     _InactiveElements._unmount
#23     _InactiveElements._unmount.<anonymous closure>
#24     SingleChildRenderObjectElement.visitChildren
#25     _InactiveElements._unmount
#26     _InactiveElements._unmount.<anonymous closure>
#27     ComponentElement.visitChildren
#28     _InactiveElements._unmount
#29     _InactiveElements._unmount.<anonymous closure>
#30     SingleChildRenderObjectElement.visitChildren
#31     _InactiveElements._unmount
#32     _InactiveElements._unmount.<anonymous closure>
#33     ComponentElement.visitChildren
#34     _InactiveElements._unmount
#35     _InactiveElements._unmount.<anonymous closure>
#36     ComponentElement.visitChildren
#37     _InactiveElements._unmount
#38     _InactiveElements._unmount.<anonymous closure>
#39     SingleChildRenderObjectElement.visitChildren
#40     _InactiveElements._unmount
#41     _InactiveElements._unmount.<anonymous closure>
#42     ComponentElement.visitChildren
#43     _InactiveElements._unmount
#44     _InactiveElements._unmount.<anonymous closure>
#45     SingleChildRenderObjectElement.visitChildren
#46     _InactiveElements._unmount
#47     _InactiveElements._unmount.<anonymous closure>
#48     ComponentElement.visitChildren
#49     _InactiveElements._unmount
#50     _InactiveElements._unmount.<anonymous closure>
#51     ComponentElement.visitChildren
#52     _InactiveElements._unmount
#53     _InactiveElements._unmount.<anonymous closure>
#54     ComponentElement.visitChildren
#55     _InactiveElements._unmount
#56     _InactiveElements._unmount.<anonymous closure>
#57     ComponentElement.visitChildren
#58     _InactiveElements._unmount
#59     _InactiveElements._unmount.<anonymous closure>
#60     SingleChildRenderObjectElement.visitChildren
#61     _InactiveElements._unmount
#62     _InactiveElements._unmount.<anonymous closure>
#63     ComponentElement.visitChildren
#64     _InactiveElements._unmount
#65     _InactiveElements._unmount.<anonymous closure>
#66     SingleChildRenderObjectElement.visitChildren
#67     _InactiveElements._unmount
#68     _InactiveElements._unmount.<anonymous closure>
#69     ComponentElement.visitChildren
#70     _InactiveElements._unmount
#71     _InactiveElements._unmount.<anonymous closure>
#72     ComponentElement.visitChildren
#73     _InactiveElements._unmount
#74     _InactiveElements._unmount.<anonymous closure>
#75     ComponentElement.visitChildren
#76     _InactiveElements._unmount
#77     _InactiveElements._unmount.<anonymous closure>
#78     ComponentElement.visitChildren
#79     _InactiveElements._unmount
#80     _InactiveElements._unmount.<anonymous closure>
#81     ComponentElement.visitChildren
#82     _InactiveElements._unmount
#83     _InactiveElements._unmount.<anonymous closure>
#84     ComponentElement.visitChildren
#85     _InactiveElements._unmount
#86     _InactiveElements._unmount.<anonymous closure>
#87     SingleChildRenderObjectElement.visitChildren
#88     _InactiveElements._unmount
#89     _InactiveElements._unmount.<anonymous closure>
#90     ComponentElement.visitChildren
#91     _InactiveElements._unmount
#92     _InactiveElements._unmount.<anonymous closure>
#93     ComponentElement.visitChildren
#94     _InactiveElements._unmount
#95     _InactiveElements._unmount.<anonymous closure>
#96     ComponentElement.visitChildren
#97     _InactiveElements._unmount
#98     _InactiveElements._unmount.<anonymous closure>
#99     ComponentElement.visitChildren
#100    _InactiveElements._unmount
#101    _InactiveElements._unmount.<anonymous closure>
#102    ComponentElement.visitChildren
#103    _InactiveElements._unmount
#104    _InactiveElements._unmount.<anonymous closure>
#105    SingleChildRenderObjectElement.visitChildren
#106    _InactiveElements._unmount
#107    _InactiveElements._unmount.<anonymous closure>
#108    ComponentElement.visitChildren
#109    _InactiveElements._unmount
#110    _InactiveElements._unmount.<anonymous closure>
#111    ComponentElement.visitChildren
#112    _InactiveElements._unmount
#113    _InactiveElements._unmount.<anonymous closure>
#114    ComponentElement.visitChildren
#115    _InactiveElements._unmount
#116    _InactiveElements._unmount.<anonymous closure>
#117    MultiChildRenderObjectElement.visitChildren
#118    _InactiveElements._unmount
#119    _InactiveElements._unmount.<anonymous closure>
#120    ComponentElement.visitChildren
#121    _InactiveElements._unmount
#122    _InactiveElements._unmount.<anonymous closure>
#123    ComponentElement.visitChildren
#124    _InactiveElements._unmount
#125    _InactiveElements._unmount.<anonymous closure>
#126    ComponentElement.visitChildren
#127    _InactiveElements._unmount
#128    _InactiveElements._unmount.<anonymous closure>
#129    ComponentElement.visitChildren
#130    _InactiveElements._unmount
#131    _InactiveElements._unmount.<anonymous closure>
#132    ComponentElement.visitChildren
#133    _InactiveElements._unmount
#134    _InactiveElements._unmount.<anonymous closure>
#135    ComponentElement.visitChildren
#136    _InactiveElements._unmount
#137    _InactiveElements._unmount.<anonymous closure>
#138    ComponentElement.visitChildren
#139    _InactiveElements._unmount
#140    _InactiveElements._unmount.<anonymous closure>
#141    ComponentElement.visitChildren
#142    _InactiveElements._unmount
#143    _InactiveElements._unmount.<anonymous closure>
#144    SingleChildRenderObjectElement.visitChildren
#145    _InactiveElements._unmount
#146    _InactiveElements._unmount.<anonymous closure>
#147    SingleChildRenderObjectElement.visitChildren
#148    _InactiveElements._unmount
#149    _InactiveElements._unmount.<anonymous closure>
#150    ComponentElement.visitChildren
#151    _InactiveElements._unmount
#152    _InactiveElements._unmount.<anonymous closure>
#153    ComponentElement.visitChildren
#154    _InactiveElements._unmount
#155    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#156    _InactiveElements._unmountAll
#157    BuildOwner.lockState
#158    BuildOwner.finalizeTree
#159    WidgetsBinding.drawFrame
#160    RendererBinding._handlePersistentFrameCallback
#161    SchedulerBinding._invokeFrameCallback
#162    SchedulerBinding.handleDrawFrame
#163    SchedulerBinding._handleDrawFrame
#164    _invoke (dart:ui/hooks.dart:145:13)
#165    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#166    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider<AppLanguage>(create: (_) => AppLanguage(),),
      ],
      child: Builder(
        builder: (context) => MyApp()
      ),
    )
  );
}

class AppState extends ChangeNotifier {
}

class AppLanguage with ChangeNotifier {
  Locale _locale = const Locale.fromSubtags(languageCode: 'en');

  Locale get locale => _locale;

  set locale(Locale locale) {
      _locale = locale;
      notifyListeners();
  }
}

class MyApp extends StatelessWidget {

  @override
  Widget build(final BuildContext context) => MaterialApp.router(
      routerDelegate: AppRouterDelegate(),
      backButtonDispatcher: RootBackButtonDispatcher(),
      locale: context.watch<AppLanguage>().locale,
    );
}

class AppRouterDelegate extends RouterDelegate<AppState> with ChangeNotifier, PopNavigatorRouterDelegateMixin<AppState> {

  @override
  final GlobalKey<NavigatorState> navigatorKey;

  AppRouterDelegate() : navigatorKey = GlobalKey<NavigatorState>();
  @override
  Widget build(final BuildContext context) => Navigator(
      key: navigatorKey,
      pages: [
        MaterialPage(child: TestScreen())
      ],
      onPopPage: (route, result) {
        final bool didPop = route.didPop(result);
        
        if (!didPop) {
          return false;
        }

        return true;
      },
    );

  @override
  Future<void> setNewRoutePath(final AppState appState) async {
  }
}

class TestScreen extends StatefulWidget {

  @override
  State<TestScreen> createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  int state = 0;

  void _resetState() {
    setState(() {
      state = 1;
    });
  }

  void _changeLang(final AppLanguage appLanguage, final Locale languageCode) {
    appLanguage.locale = languageCode;
  }
  
  @override
  void dispose() {
    _resetState();
    super.dispose();
  }

  @override
  Widget build(final BuildContext context) {
    var selectedLanguageCode = context.select((AppLanguage appLanguage) => appLanguage.locale);
    return Scaffold(
      body: Container(
        child: ChangeLanguage(
          selectedLocale: selectedLanguageCode,
          onSelection: (lng) => _changeLang(context.read<AppLanguage>(), lng),
        ),
      ),
    );
  }
}

class ChangeLanguage extends StatelessWidget {
  const ChangeLanguage({required this.selectedLocale, required this.onSelection});
  
  final Locale selectedLocale;
  final void Function(Locale locale) onSelection;

  @override
  Widget build(final BuildContext context) => 
    Row(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: [
        ElevatedButton(onPressed: () => onSelection(const Locale.fromSubtags(languageCode: 'en')),
          child: const Text("en"),
        ),
        ElevatedButton(onPressed: () => onSelection(const Locale.fromSubtags(languageCode: 'es')),
        child: const Text("es"),
        )
      ],
    );
}
```

</details>

<details>
  <summary>Logs</summary>

```
just exception
```

```
Analyzing test_case.dart...                                             
No issues found! (ran in 20.1s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.7.0-24.0.pre.52, on Microsoft Windows [Version 10.0.19044.2006], locale pl-PL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @eximius313 
I see that you are using provider which is third party package. Does the same exception occur without using it ? If so, can you provide updated code sample ?

**Comment by eximius313** [comment]
1. The exception is related to ChangeNotifier and Language, so how else could I inject it into widget?
2. Exception comes directly from Flutter, not from 3rd party library:
```
#2      Element.markNeedsBuild
#3      State.setState
```
3. Exception says `Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub` which I just did ;)

**Comment by darshankawar** [comment]
Thanks for the update. This seems to be similar to https://github.com/flutter/flutter/issues/25536, so please follow-up in it for further updates. 
Closing this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.
