### ISSUE TITLE
[BUG] The following assertion was thrown during a scheduler callback

### ISSUE THREAD

**Issue by JaffaKetchup** [flutter/flutter#119422]
Hi all,

I cannot provide an MRE or steps to reproduce, as I do not know where this issue is being thrown. The issue is as below (it states to raise a bug here):

```
I/flutter ( 3797): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 3797): The following assertion was thrown during a scheduler callback:
I/flutter ( 3797): SemanticsNode#114(Rect.fromLTRB(0.0, 0.0, 0.0, 0.0), tags: [RenderViewport.twoPane], invisible)
I/flutter ( 3797): (with null) tried to set a non-finite rect.
I/flutter ( 3797): 'package:flutter/src/semantics/semantics.dart':
package:flutter/…/semantics/semantics.dart:1
I/flutter ( 3797): Failed assertion: line 1605 pos 12: 'value.isFinite'
I/flutter ( 3797):
I/flutter ( 3797): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3797): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3797): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3797):   https://github.com/flutter/flutter/issues/new?template=2_bug.md
I/flutter ( 3797):
I/flutter ( 3797): When the exception was thrown, this was the stack:
I/flutter ( 3797): #2      SemanticsNode.rect=
package:flutter/…/semantics/semantics.dart:1605
I/flutter ( 3797): #3      _SwitchableSemanticsFragment.compileChildren
package:flutter/…/rendering/object.dart:4223
I/flutter ( 3797): #4      _SwitchableSemanticsFragment.compileChildren
package:flutter/…/rendering/object.dart:4235
I/flutter ( 3797): #5      RenderObject._updateSemantics
package:flutter/…/rendering/object.dart:3159
I/flutter ( 3797): #6      PipelineOwner.flushSemantics
package:flutter/…/rendering/object.dart:1221
I/flutter ( 3797): #7      RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:518
I/flutter ( 3797): #8      WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:884
I/flutter ( 3797): #9      RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:378
I/flutter ( 3797): #10     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
I/flutter ( 3797): #11     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1104
I/flutter ( 3797): #12     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
I/flutter ( 3797): #13     _invoke (dart:ui/hooks.dart:148:13)
I/flutter ( 3797): #14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
I/flutter ( 3797): #15     _drawFrame (dart:ui/hooks.dart:115:31)
I/flutter ( 3797): (elided 2 frames from class _AssertionError)
I/flutter ( 3797): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Although this error is raised, there doesn't appear to be anything wrong with the UI.

`flutter doctor` output:
```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.1105], locale en-GB)
    • Flutter version 3.3.10 on channel stable at C:\Users\lukas\fvm\versions\3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\lukas\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.4.33122.133
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code, 64-bit edition (version 1.74.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (2 available)
    • M2101K6G (mobile) • 95e93891 • android-arm64 • Android 12 (API 31)
    • Windows (desktop) • windows  • windows-x64   • Microsoft Windows [Version 10.0.22621.1105]

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by Paguiar735** [comment]
Unfortunately without a minimal working example or at least the link to the project, it's nearly impossible to tell what that is.

If you don't know right away what's causing it, remove parts of the app incrementally until you arrive in a minimal working example.

**Comment by JaffaKetchup** [comment]
Hi @Paguiar735, thanks for your response. I'll do that.

**Comment by JaffaKetchup** [comment]
Can't include all the code, but this is the triggering widget. It's wrapped in a whole bunch of widgets and slivers. It only triggers on some screen sizes it seems.

```dart
Padding(
  padding: const EdgeInsets.only(
    left: 16.0,
    right: 16.0,
    top: 16.0,
    bottom: 8.0,
  ),
  child: Text(
    'Recent Comments',
    style: context.typography.caption1.bold.primary,
  ),
),
```

**Comment by darshankawar** [comment]
Thanks for the report @JaffaKetchup 
There was an old issue triggering similar error as you reported: https://github.com/flutter/flutter/issues/48043. The code sample mentioned in it didn't throw the reported anymore at my end. I also tried to club your code snippet in it but I didn't get the said error. So please try to provide a reproducible code sample. I also suggest you to try the code you have on latest master and stable to see if you still get same error on them as well or not.

**Comment by JaffaKetchup** [comment]
@darshankawar I'll try updating the project to 3.10 first to see if that helps, but that might take a while, but I'm unlikley to be able to form a complete example (I guess DevTools might help). My colleagues couldn't reproduce it, so there's a good chance that even with an example, you won't be able to reproduce.

**Comment by darshankawar** [comment]
See if your code is using same implementation as mentioned in this issue https://github.com/flutter/flutter/issues/36419. 
[This](https://github.com/flutter/flutter/issues/36419#issuecomment-1018378306) comment from the linked issue describes same error as you reported.

**Comment by JaffaKetchup** [comment]
Unfortunatley, I can no longer reproduce this, and I'm not sure what's changed. Therefore, I'll have to close this issue.
