### ISSUE TITLE
Unable to Wirelessly Debug the App on iOS

### ISSUE THREAD

**Issue by AmitSonkhiya** [flutter/flutter#119493]
I m trying to wirelessly debug the app on iOS and have followed the [discussions](https://github.com/flutter/flutter/issues/15072#issuecomment-1399056235) as mentioned.

1. The Mac and iOS devices are on the same network
2. The iPhone has a passcode set
3. The Mac and iPhone are connected wirelessly
4. Launch argument `--observatory-host=0.0.0.0` is set in Xcode > Product > Scheme > Edit Scheme
5. The app is run in iPhone through Xcode wirelessly
6. The command `flutter attach --device-timeout 5` is run

Yet the process is stuck with the message

> Waiting for a connection from Flutter on Mac Designed for iPad...

## Steps to Reproduce

As mentioned
https://github.com/flutter/flutter/issues/15072#issuecomment-1399056235

**Expected results:** 
Being capable to wirelessly debug the Flutter app on iOS with Android Studio.

**Actual results:** 
An indefinite message on console followed by cursor blink.

> Waiting for a connection from Flutter on Mac Designed for iPad...

<details>
  <summary>Logs</summary>

```
[   +7 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: [/Volumes/Data/programs/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +10 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] executing: [/Volumes/Data/programs/flutter/] git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[  +33 ms] Exit code 0 from: git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] 3.7.0
[   +5 ms] executing: [/Volumes/Data/programs/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/Volumes/Data/programs/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +14 ms] executing: [/Volumes/Data/programs/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: sw_vers -productName
[   +9 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +7 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.1
[        ] executing: sw_vers -buildVersion
[   +7 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22C65
[        ] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] arm64
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +27 ms] executing: /Volumes/Data/programs/studio/platform-tools/adb devices -l
[  +12 ms] executing: sysctl hw.optional.arm64
[   +4 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -version
[ +107 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun xcodebuild -version
[   +1 ms] Xcode 14.2
Build version 14C18
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun xcdevice list --timeout 2
[        ] /usr/bin/arch -arm64e xcrun simctl list devices booted iOS --json
[        ] executing: /usr/bin/arch -arm64e xcrun simctl list devices booted iOS --json
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun simctl list devices booted
[  +70 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun simctl list devices booted
[        ] == Devices ==
-- iOS 16.2 --
[  +17 ms] List of devices attached
[  +58 ms] {
"devices" : {
"com.apple.CoreSimulator.SimRuntime.iOS-16-2" : [

]
}
}
[+2306 ms] [
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPhone15,3",
"identifier" : "7479898C-D865-4C1E-891B-AF46A1BB665B",
"architecture" : "arm64",
"modelUTI" : "com.apple.iphone-14-pro-max-1",
"modelName" : "iPhone 14 Pro Max",
"name" : "iPhone 14 Pro Max"
},
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPad13,18",
"identifier" : "021C7181-7B61-4EFD-A4D1-4B7226AF80AA",
"architecture" : "arm64",
"modelUTI" : "com.apple.ipad-10-1",
"modelName" : "iPad (10th generation)",
"name" : "iPad (10th generation)"
},
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPad14,3",
"identifier" : "CFBC6644-E3BC-4368-8949-2EAB5C335E36",
"architecture" : "arm64",
"modelUTI" : "com.apple.ipad-pro-11-4th-1",
"modelName" : "iPad Pro (11-inch) (4th generation)",
"name" : "iPad Pro (11-inch) (4th generation)"
},
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPhone14,7",
"identifier" : "E06E3B2D-96C9-4BC5-A045-DE7B8A36C38E",
"architecture" : "arm64",
"modelUTI" : "com.apple.iphone-14-1",
"modelName" : "iPhone 14",
"name" : "iPhone 14"
},
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPad13,17",
"identifier" : "532DA4B7-D06F-45EB-AC95-FA960C01E110",
"architecture" : "arm64",
"modelUTI" : "com.apple.ipad-air5-1",
"modelName" : "iPad Air (5th generation)",
"name" : "iPad Air (5th generation)"
},
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPhone14,8",
"identifier" : "09DB01D3-8F3E-455C-BFEE-E66B74ADB421",
"architecture" : "arm64",
"modelUTI" : "com.apple.iphone-14-plus-1",
"modelName" : "iPhone 14 Plus",
"name" : "iPhone 14 Plus"
},
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPhone15,2",
"identifier" : "D5C52252-E5E5-487D-9111-DBB62461D83F",
"architecture" : "arm64",
"modelUTI" : "com.apple.iphone-14-pro-1",
"modelName" : "iPhone 14 Pro",
"name" : "iPhone 14 Pro"
},
{
"simulator" : false,
"operatingSystemVersion" : "13.1 (22C65)",
"interface" : "usb",
"available" : true,
"platform" : "com.apple.platform.macosx",
"modelCode" : "MacBookPro17,1",
"identifier" : "00008103-0004113622D3001E",
"architecture" : "arm64e",
"modelUTI" : "com.apple.macbookpro-13-retina-touchid-late-2020",
"modelName" : "MacBook Pro",
"name" : "My Mac"
},
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPad14,1",
"identifier" : "C66CB2A8-B568-412A-946F-495C27AD5DFD",
"architecture" : "arm64",
"modelUTI" : "com.apple.ipad-mini6-1",
"modelName" : "iPad mini (6th generation)",
"name" : "iPad mini (6th generation)"
},
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPad14,5",
"identifier" : "3E7E59F7-95F5-4929-B8B9-999A1BA3E102",
"architecture" : "arm64",
"modelUTI" : "com.apple.ipad-pro-12point9-6th-1",
"modelName" : "iPad Pro (12.9-inch) (6th generation)",
"name" : "iPad Pro (12.9-inch) (6th generation)"
},
{
"simulator" : true,
"operatingSystemVersion" : "16.2 (20C52)",
"available" : true,
"platform" : "com.apple.platform.iphonesimulator",
"modelCode" : "iPhone14,6",
"identifier" : "3EAEA4D9-66B9-44FA-9288-1E29AA878084",
"architecture" : "arm64",
"modelUTI" : "com.apple.iphone-se3-1",
"modelName" : "iPhone SE (3rd generation)",
"name" : "iPhone SE (3rd generation)"
},
{
"modelCode" : "iPhone12,1",
"simulator" : false,
"modelName" : "iPhone 11",
"error" : {
"code" : -13,
"failureReason" : "",
"underlyingErrors" : [
{
"code" : 4,
"failureReason" : "",
"description" : "Amit’s iPhone is locked.",
"recoverySuggestion" : "To use Amit’s iPhone with Xcode, unlock it.",
"domain" : "DVTDeviceIneligibilityErrorDomain"
}
],
"description" : "Amit’s iPhone is not connected",
"recoverySuggestion" : "Xcode will continue when Amit’s iPhone is connected and unlocked.",
"domain" : "com.apple.platform.iphoneos"
},
"operatingSystemVersion" : "15.6.1 (19G82)",
"identifier" : "00008030-001965A01E87802E",
"platform" : "com.apple.platform.iphoneos",
"architecture" : "arm64e",
"interface" : "usb",
"available" : false,
"name" : "Amit’s iPhone",
"modelUTI" : "com.apple.iphone-11-1"
}
]
[  +18 ms] Error: Amit’s iPhone is not connected. Xcode will continue when Amit’s iPhone is connected and unlocked. (code -13)
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +34 ms] No supported devices connected.
[  +61 ms] The following devices were found, but are not supported by this project:
macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119
If you would like your app to run on macos or web, consider running `flutter create .` to generate projects for these platforms.

[   +4 ms] "flutter run" took 2,777ms.
[   +9 ms]
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:499:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1381:5)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>


[ +303 ms] ensureAnalyticsSent: 251ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

## Flutter doctor
```
Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
• Flutter version 3.7.0 on channel stable at /Volumes/Data/programs/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision b06b8b2710 (6 days ago), 2023-01-23 16:55:55 -0800
• Engine revision b24591ed32
• Dart version 2.19.0
• DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
• Android SDK at /Volumes/Data/programs/studio
• Platform android-33, build-tools 33.0.1
• ANDROID_HOME = /Volumes/Data/studio
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14C18
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
• VS Code at /Users/amit/Downloads/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
• macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
• Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
• All required HTTP hosts are available

• No issues found!
```

</details>

Also tried: `flutter attach -d "Amit\’s iPhone" --device -timeout 5`
Output

> No supported devices found with name or id matching 'Amit\'s iPhone'

Although it says in _Logs_

> Amit’s iPhone is not connected. Xcode will continue when Amit’s iPhone is connected and unlocked. (code -13)

Yet the app is running on iPhone wirelessly through Xcode without any issue.
However I'm unable to attach it with Flutter.

**Comment by danagbemava-nc** [comment]
Hi @AmitSonkhiya, this feature is currently not available on the `stable` channel. You'll need to test this on the `master` channel. 

Can you switch over to the `master` channel to see if you still face any issues wirelessly debugging? 

If you do please provide the updated output of `flutter doctor -v` on the master channel. 

Please also make sure that the globe shows next to your device in the Xcode Devices window as seen below

![Screenshot 2023-01-30 at 11 14 36](https://user-images.githubusercontent.com/88313112/215462413-a69a4749-c362-41e0-97e5-31753decc876.png)

Thank you

**Comment by AmitSonkhiya** [comment]
@danagbemava-nc 

Yes, the globe icon is present in the Xcode > Windows > Devices and Simulators

### Output of flutter doctor command
It is already there in the initial issue in the bottom of the Logs section, perhaps I messed with the markdown so posting again.
```
Flutter (Channel master, 3.7.0-30.0.pre.8, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
• Flutter version 3.7.0-30.0.pre.8 on channel master at /Volumes/Data/programs/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 530c3f2d13 (4 hours ago), 2023-01-30 10:19:14 +0000
• Engine revision a7bb0e4108
• Dart version 3.0.0 (build 3.0.0-179.0.dev)
• DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
• Android SDK at /Volumes/Data/programs/studio
• Platform android-33, build-tools 33.0.1
• ANDROID_HOME = /Volumes/Data/programs/studio
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14C18
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
• VS Code at /Users/amit/Downloads/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
• SM A305F (mobile) • 192.168.1.7:38902 • android-arm64  • Android 11 (API 30)
• macOS (desktop)   • macos             • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
• Chrome (web)      • chrome            • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
• All required HTTP hosts are available

• No issues found!
```
**Switching to the master channel made iOS wireless debugging successful. Very nice 👍**

Just firing `q` after attaching the running app to Flutter doesn't terminate the application on the device.
I guess it only detach.

### Steps to reproduce

1. Complete Xcode setup for attaching the app
2. Run the app through Xcode
3. Issue the command flutter attach --device-timeout 5
4. Press the q key after successful attach

Thanks for prompting and adding this feature.

**Comment by vashworth** [comment]
When running the app through Xcode and using `flutter attach`, it is expected behavior for the app to remain running when pressing `q` since Xcode is still running it. 

You can run the flutter app on a wireless device without Xcode using `flutter run --device-timeout 5`.

**Comment by AmitSonkhiya** [comment]
Yeah, can be run as well, I was testing both.

In the case of `attach`, somehow Flutter output on the console (after syncing files to device) is misleading.
I was trying `q` basis on that output.

```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
```

Anyway, thanks for letting me know.

**Comment by vashworth** [comment]
@AmitSonkhiya I see what you're saying, that is confusing. I've filed a new issue for it: https://github.com/flutter/flutter/issues/119550. Thank you for the feedback!

**Comment by jmagman** [comment]
@AmitSonkhiya looks like you were testing on stable, and https://github.com/flutter/flutter/issues/119550 is tracking the confusion with `q` == detach, so I think this can be closed.  Thanks for filing, please continue to create new issues as you find them on master. 🙂

**Comment by simplenotezy** [comment]
@jmagman / @vashworth I have the exact same symptons as reported by @AmitSonkhiya. I did briefly get the simulator to work once via flutter run, but now I won't work anymore.

- I have verified I have the globe in XCode
- I have verified I am on the same network
- I can debug wirelessly using xcode

`flutter doctor -v`:

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6 21G115 darwin-arm64, locale en-DK)
    • Flutter version 3.7.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.7.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (12 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/mf/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • iPhone 14 Pro (mobile) • ED147E0A-6D06-44CB-A789-231A2A6BC765 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64 • macOS 12.6 21G115 darwin-arm64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by simplenotezy** [comment]
Update:
-
Had to run `flutter channel master` - not sure why it worked briefly before without it.
