### ISSUE TITLE
Hitting the "Re-run" button on a CI failure doesn't actually register the new build

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#119588]
Example: https://github.com/flutter/engine/pull/39268

Mac Unopt failed, but was run on infra canary. I tried clicking re-run from the GitHub UI, and it says a re-run is scheduled, but it doesn't register in GitHub's checks.

**Comment by godofredoc** [comment]
Checkrun.rerequested event was generated from github and delivered successfully to cocoon backend
```
{
  "action": "rerequested",
  "check_run": {
    "id": 10991318050,
    "name": "Mac Unopt",
    "node_id": "CR_kwDOAlZRSc8AAAACjyI0Ig",
    "head_sha": "f93a6f5f9e2406e8a16a203c3d6e4c803fdb64bd",
    "external_id": "",
    "url": "https://api.github.com/repos/flutter/engine/check-runs/10991318050",
    "html_url": "https://github.com/flutter/engine/runs/10991318050",
    "details_url": "https://ci.chromium.org/b/8790495779766226513",
    "status": "completed",
    "conclusion": "failure",
    "started_at": "2023-01-31T01:02:38Z",
    "completed_at": "2023-01-31T02:08:34Z",
    "output": {
      "title": "Mac Unopt",
      "summary": "**[Understanding a LUCI build failure](https://github.com/flutter/flutter/wiki/Understanding-a-LUCI-build-failure)**\n\nStep('test: Host Tests for ios_debug_sim (3)') (retcode: 1)",
      "text": null,
      "annotations_count": 0,
      "annotations_url": "https://api.github.com/repos/flutter/engine/check-runs/10991318050/annotations"
    },
```

**Comment by godofredoc** [comment]
The backend is failing to process the rerequests:

```
Null check operator used on a null value
#0      Scheduler.processCheckRun (package:cocoon_service/src/service/scheduler.dart:475:84)
#1      GithubWebhookSubscription.post (package:cocoon_service/src/request_handlers/github/webhook_subscription.dart:87:29)
#2      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:30)
#3      _rootRun (dart:async/zone.dart:1398:13)
#4      _CustomZone.run (dart:async/zone.dart:1300:19)
#5      _runZoned (dart:async/zone.dart:1803:10)
#6      runZoned (dart:async/zone.dart:1746:10)
#7      RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:42:12)
#8      SubscriptionHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/subscription_handler.dart:139:31)
#9      _rootRun (dart:async/zone.dart:1398:13)
#10     _CustomZone.run (dart:async/zone.dart:1300:19)
#11     _runZoned (dart:async/zone.dart:1803:10)
#12     runZoned (dart:async/zone.dart:1746:10)
#13     SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:11)
<asynchronous suspension>
#14     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:286:11)
<asynchronous suspension>
```

**Comment by godofredoc** [comment]
Event data
```
{"action":"rerequested","check_run":{"id":10991318050,"name":"Mac Unopt","node_id":"CR_kwDOAlZRSc8AAAACjyI0Ig","head_sha":"f93a6f5f9e2406e8a16a203c3d6e4c803fdb64bd","external_id":"","url":"https://api.github.com/repos/flutter/engine/check-runs/10991318050","html_url":"https://github.com/flutter/engine/runs/10991318050","details_url":"https://ci.chromium.org/b/8790495779766226513","status":"completed","conclusion":"failure","started_at":"2023-01-31T01:02:38Z","completed_at":"2023-01-31T02:08:34Z","output":{"title":"Mac Unopt","summary":"**[Understanding a LUCI build failure](https://github.com/flutter/flutter/wiki/Understanding-a-LUCI-build-failure)**\n\nStep('test: Host Tests for ios_debug_sim (3)') (retcode: 1)","text":null,"annotations_count":0,"annotations_url":"https://api.github.com/repos/flutter/engine/check-runs/10991318050/annotations"},"check_suite":{"id":10675553991,"node_id":"CS_kwDOAlZRSc8AAAACfFAGxw","head_branch":null,"head_sha":"f93a6f5f9e2406e8a16a203c3d6e4c803fdb64bd","status":"queued","conclusion":null,"url":"https://api.github.com/repos/flutter/engine/check-suites/10675553991","before":null,"after":null,"pull_requests":[],"app":{"id":64368,"slug":"flutter-dashboard","node_id":"MDM6QXBwNjQzNjg=","owner":{"login":"flutter","id":14101776,"node_id":"MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2","avatar_url":"https://avatars.githubusercontent.com/u/14101776?v=4","gravatar_id":"","url":"https://api.github.com/users/flutter","html_url":"https://github.com/flutter","followers_url":"https://api.github.com/users/flutter/followers","following_url":"https://api.github.com/users/flutter/following{/other_user}","gists_url":"https://api.github.com/users/flutter/gists{/gist_id}","starred_url":"https://api.github.com/users/flutter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/flutter/subscriptions","organizations_url":"https://api.github.com/users/flutter/orgs","repos_url":"https://api.github.com/users/flutter/repos","events_url":"https://api.github.com/users/flutter/events{/privacy}","received_events_url":"https://api.github.com/users/flutter/received_events","type":"Organization","site_admin":false},"name":"flutter-dashboard","description":"Flutter Dashboard and build/test orchestrator. The source code for the application can be found at https://github.com/flutter/cocoon/tree/main/app_dart.","external_url":"https://flutter-dashboard.appspot.com","html_url":"https://github.com/apps/flutter-dashboard","created_at":"2020-05-10T00:32:46Z","updated_at":"2022-08-26T19:06:29Z","permissions":{"checks":"write","contents":"read","issues":"write","metadata":"read","pull_requests":"write","statuses":"write"},"events":["check_run","check_suite","create","label","pull_request"]},"created_at":"2023-01-31T01:02:26Z","updated_at":"2023-01-31T02:24:12Z"},"app":{"id":64368,"slug":"flutter-dashboard","node_id":"MDM6QXBwNjQzNjg=","owner":{"login":"flutter","id":14101776,"node_id":"MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2","avatar_url":"https://avatars.githubusercontent.com/u/14101776?v=4","gravatar_id":"","url":"https://api.github.com/users/flutter","html_url":"https://github.com/flutter","followers_url":"https://api.github.com/users/flutter/followers","following_url":"https://api.github.com/users/flutter/following{/other_user}","gists_url":"https://api.github.com/users/flutter/gists{/gist_id}","starred_url":"https://api.github.com/users/flutter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/flutter/subscriptions","organizations_url":"https://api.github.com/users/flutter/orgs","repos_url":"https://api.github.com/users/flutter/repos","events_url":"https://api.github.com/users/flutter/events{/privacy}","received_events_url":"https://api.github.com/users/flutter/received_events","type":"Organization","site_admin":false},"name":"flutter-dashboard","description":"Flutter Dashboard and build/test orchestrator. The source code for the application can be found at https://github.com/flutter/cocoon/tree/main/app_dart.","external_url":"https://flutter-dashboard.appspot.com","html_url":"https://github.com/apps/flutter-dashboard","created_at":"2020-05-10T00:32:46Z","updated_at":"2022-08-26T19:06:29Z","permissions":{"checks":"write","contents":"read","issues":"write","metadata":"read","pull_requests":"write","statuses":"write"},"events":["check_run","check_suite","create","label","pull_request"]},"pull_requests":[]},"repository":{"id":39211337,"node_id":"MDEwOlJlcG9zaXRvcnkzOTIxMTMzNw==","name":"engine","full_name":"flutter/engine","private":false,"owner":{"login":"flutter","id":14101776,"node_id":"MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2","avatar_url":"https://avatars.githubusercontent.com/u/14101776?v=4","gravatar_id":"","url":"https://api.github.com/users/flutter","html_url":"https://github.com/flutter","followers_url":"https://api.github.com/users/flutter/followers","following_url":"https://api.github.com/users/flutter/following{/other_user}","gists_url":"https://api.github.com/users/flutter/gists{/gist_id}","starred_url":"https://api.github.com/users/flutter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/flutter/subscriptions","organizations_url":"https://api.github.com/users/flutter/orgs","repos_url":"https://api.github.com/users/flutter/repos","events_url":"https://api.github.com/users/flutter/events{/privacy}","received_events_url":"https://api.github.com/users/flutter/received_events","type":"Organization","site_admin":false},"html_url":"https://github.com/flutter/engine","description":"The Flutter engine","fork":false,"url":"https://api.github.com/repos/flutter/engine","forks_url":"https://api.github.com/repos/flutter/engine/forks","keys_url":"https://api.github.com/repos/flutter/engine/keys{/key_id}","collaborators_url":"https://api.github.com/repos/flutter/engine/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/flutter/engine/teams","hooks_url":"https://api.github.com/repos/flutter/engine/hooks","issue_events_url":"https://api.github.com/repos/flutter/engine/issues/events{/number}","events_url":"https://api.github.com/repos/flutter/engine/events","assignees_url":"https://api.github.com/repos/flutter/engine/assignees{/user}","branches_url":"https://api.github.com/repos/flutter/engine/branches{/branch}","tags_url":"https://api.github.com/repos/flutter/engine/tags","blobs_url":"https://api.github.com/repos/flutter/engine/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/flutter/engine/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/flutter/engine/git/refs{/sha}","trees_url":"https://api.github.com/repos/flutter/engine/git/trees{/sha}","statuses_url":"https://api.github.com/repos/flutter/engine/statuses/{sha}","languages_url":"https://api.github.com/repos/flutter/engine/languages","stargazers_url":"https://api.github.com/repos/flutter/engine/stargazers","contributors_url":"https://api.github.com/repos/flutter/engine/contributors","subscribers_url":"https://api.github.com/repos/flutter/engine/subscribers","subscription_url":"https://api.github.com/repos/flutter/engine/subscription","commits_url":"https://api.github.com/repos/flutter/engine/commits{/sha}","git_commits_url":"https://api.github.com/repos/flutter/engine/git/commits{/sha}","comments_url":"https://api.github.com/repos/flutter/engine/comments{/number}","issue_comment_url":"https://api.github.com/repos/flutter/engine/issues/comments{/number}","contents_url":"https://api.github.com/repos/flutter/engine/contents/{+path}","compare_url":"https://api.github.com/repos/flutter/engine/compare/{base}...{head}","merges_url":"https://api.github.com/repos/flutter/engine/merges","archive_url":"https://api.github.com/repos/flutter/engine/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/flutter/engine/downloads","issues_url":"https://api.github.com/repos/flutter/engine/issues{/number}","pulls_url":"https://api.github.com/repos/flutter/engine/pulls{/number}","milestones_url":"https://api.github.com/repos/flutter/engine/milestones{/number}","notifications_url":"https://api.github.com/repos/flutter/engine/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/flutter/engine/labels{/name}","releases_url":"https://api.github.com/repos/flutter/engine/releases{/id}","deployments_url":"https://api.github.com/repos/flutter/engine/deployments","created_at":"2015-07-16T17:39:56Z","updated_at":"2023-01-30T14:56:05Z","pushed_at":"2023-01-31T02:23:55Z","git_url":"git://github.com/flutter/engine.git","ssh_url":"git@github.com:flutter/engine.git","clone_url":"https://github.com/flutter/engine.git","svn_url":"https://github.com/flutter/engine","homepage":"https://flutter.dev","size":392011,"stargazers_count":6381,"watchers_count":6381,"language":"C++","has_issues":false,"has_projects":false,"has_downloads":true,"has_wiki":false,"has_pages":false,"has_discussions":false,"forks_count":4972,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":105,"license":{"key":"bsd-3-clause","name":"BSD 3-Clause \"New\" or \"Revised\" License","spdx_id":"BSD-3-Clause","url":"https://api.github.com/licenses/bsd-3-clause","node_id":"MDc6TGljZW5zZTU="},"allow_forking":true,"is_template":false,"web_commit_signoff_required":false,"topics":["c-plus-plus"],"visibility":"public","forks":4972,"open_issues":105,"watchers":6381,"default_branch":"main"},"organization":{"login":"flutter","id":14101776,"node_id":"MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2","url":"https://api.github.com/orgs/flutter","repos_url":"https://api.github.com/orgs/flutter/repos","events_url":"https://api.github.com/orgs/flutter/events","hooks_url":"https://api.github.com/orgs/flutter/hooks","issues_url":"https://api.github.com/orgs/flutter/issues","members_url":"https://api.github.com/orgs/flutter/members{/member}","public_members_url":"https://api.github.com/orgs/flutter/public_members{/member}","avatar_url":"https://avatars.githubusercontent.com/u/14101776?v=4","description":"Flutter is Google's UI toolkit for building beautiful, natively compiled applications for mobile, web, desktop, and embedded devices from a single codebase."},"enterprise":{"id":1732,"slug":"alphabet","name":"Alphabet","node_id":"MDEwOkVudGVycHJpc2UxNzMy","avatar_url":"https://avatars.githubusercontent.com/b/1732?v=4","description":"","website_url":"https://abc.xyz/","html_url":"https://github.com/enterprises/alphabet","created_at":"2019-12-19T00:30:52Z","updated_at":"2023-01-20T00:41:48Z"},"sender":{"login":"godofredoc","id":54371434,"node_id":"MDQ6VXNlcjU0MzcxNDM0","avatar_url":"https://avatars.githubusercontent.com/u/54371434?v=4","gravatar_id":"","url":"https://api.github.com/users/godofredoc","html_url":"https://github.com/godofredoc","followers_url":"https://api.github.com/users/godofredoc/followers","following_url":"https://api.github.com/users/godofredoc/following{/other_user}","gists_url":"https://api.github.com/users/godofredoc/gists{/gist_id}","starred_url":"https://api.github.com/users/godofredoc/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/godofredoc/subscriptions","organizations_url":"https://api.github.com/users/godofredoc/orgs","repos_url":"https://api.github.com/users/godofredoc/repos","events_url":"https://api.github.com/users/godofredoc/events{/privacy}","received_events_url":"https://api.github.com/users/godofredoc/received_events","type":"User","site_admin":false},"installation":{"id":10381585,"node_id":"MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTAzODE1ODU="}}
```

**Comment by nehalvpatel** [comment]
This was fixed last night through a manual deploy with local cocoon changes but broke again this morning with the auto deploy of cocoon at 8 AM PST. The PR was merged at 9:40 AM PST and the fix has now been re-deployed. 👍

**Comment by yusuf-goog** [comment]
@nehalvpatel assigned to you, please close once the fix lands.

**Comment by nehalvpatel** [comment]
The fix has been landed and validated to be working. 👍

<img width="765" alt="Screenshot 2023-01-31 at 1 53 25 PM" src="https://user-images.githubusercontent.com/159021/215892148-ea31b815-2690-4914-8b75-cdb6ec2896e2.png">
