### ISSUE TITLE
The getter 'supportsColor' was called on null.

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#11955]
```
Unhandled exception:
NoSuchMethodError: The getter 'supportsColor' was called on null.
Receiver: null
Tried calling: supportsColor
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:79)
#3      VerboseLogger._emit (package:flutter_tools/src/base/logger.dart:244)
#4      VerboseLogger.printTrace (package:flutter_tools/src/base/logger.dart:207)
#5      _AppRunLogger.printTrace (package:flutter_tools/src/commands/daemon.dart:826)
#6      printTrace (package:flutter_tools/src/globals.dart:50)
#7      ResidentRunner._serviceProtocolDone (package:flutter_tools/src/resident_runner.dart:603)
#8      _rootRunUnary (dart:async/zone.dart:1128)
#9      _CustomZone.runUnary (dart:async/zone.dart:1012)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#13     _Future._complete (dart:async/future_impl.dart:468)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#15     ChannelManager.listen.<anonymous closure> (package:json_rpc_2/src/channel_manager.dart:60)
#16     _rootRun (dart:async/zone.dart:1116)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     _CustomZone.runGuarded (dart:async/zone.dart:901)
#19     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:384)
#20     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:394)
#21     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277)
#22     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106)
#23     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172)
#24     _rootRun (dart:async/zone.dart:1116)
#25     _CustomZone.run (dart:async/zone.dart:1001)
#26     _CustomZone.runGuarded (dart:async/zone.dart:901)
#27     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:384)
#28     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:394)
#29     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277)
#30     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106)
#31     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172)
#32     _rootRun (dart:async/zone.dart:1116)
#33     _CustomZone.run (dart:async/zone.dart:1001)
#34     _CustomZone.runGuarded (dart:async/zone.dart:901)
#35     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:384)
#36     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:394)
#37     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277)
#38     _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:804)
#39     _StreamController._closeUnchecked (dart:async/stream_controller.dart:656)
#40     _StreamController.close (dart:async/stream_controller.dart:649)
#41     _rootRun (dart:async/zone.dart:1116)
#42     _CustomZone.run (dart:async/zone.dart:1001)
#43     _FutureListener.handleWhenComplete (dart:async/future_impl.dart:152)
#44     _Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:606)
#45     _Future._propagateToListeners (dart:async/future_impl.dart:662)
#46     _Future._completeWithValue (dart:async/future_impl.dart:478)
#47     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#48     _rootRun (dart:async/zone.dart:1120)
#49     _CustomZone.run (dart:async/zone.dart:1001)
#50     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
#51     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#53     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

```

Far Manager, version 3.0 (build 4040) x86
Copyright © 1996-2000 Eugene Roshal, Copyright © 2000-2014 Far Group

C:\Program Files (x86)\Far Manager>flutter doctor
[√] Flutter (on Microsoft Windows [Version 6.3.9600], locale en-US, channel master)
    • Flutter at D:\AndroidDev\flutter
    • Framework revision 02c10b78d2 (30 hours ago), 2017-09-05 09:42:24 +0200
    • Engine revision 29e0c1c281
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at D:\AndroidSDK
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Java\jdk1.8.0_131\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

[-] Android Studio (version 2.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[√] Connected devices
    • GT N8000 • android-arm • Android 4.4.2 (API 19)

```

**Comment by goderbauer** [comment]
What command were you executing when this happened? Does it happen every time?

**Comment by JFixby** [comment]
It is a random crash happening on mobile device.
I suggest someone go down the stack, investigate the code and make a more detailed exception.

**Comment by JFixby** [comment]
But it looks like a logger problem ```package:flutter_tools/src/base/logger.dart:79```

**Comment by zoechi** [comment]
I get this exception frequently recently.
[log.txt](https://github.com/flutter/flutter/files/1466880/log.txt)

**Comment by romaluca** [comment]
I also have this error in linux
```

Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk (29.6MB).
I/FlutterActivityDelegate( 4118): onResume setting current activity to this
Error -32603 received from application: Internal error
Error initializing DevFS: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("uri")
Unhandled exception:
NoSuchMethodError: The getter 'supportsColor' was called on null.
Receiver: null
Tried calling: supportsColor
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:79)
#2      _AppRunLogger.printStatus (package:flutter_tools/src/commands/daemon.dart:841)
#3      printStatus (package:flutter_tools/src/globals.dart:39)
#4      FlutterDevice.startEchoingDeviceLog.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:233)
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _DelayedData.perform (dart:async/stream_impl.dart:578)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#17     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:111)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)

```

flutter doctor:
```

[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter version 0.0.21 at /home/luca/Programs/flutter
    • Framework revision 2e449f06f0 (3 weeks ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /home/luca/Android/Sdk
    • Android NDK at /home/luca/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = /home/luca/Android/Sdk
    • Java binary at: /home/luca/Programs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/luca/Programs/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

```

**Comment by romaluca** [comment]
With channel master i receive this other error:
```

I/FlutterActivityDelegate( 4616): onResume setting current activity to this
Error -32603 received from application: Internal error
Error initializing DevFS: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("uri")
Unhandled exception:
NoSuchMethodError: The getter 'stdout' was called on null.
Receiver: null
Tried calling: stdout
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      stdout (package:flutter_tools/src/base/io.dart:176)
#2      StdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:100)
#3      StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:95)
#4      _AppRunLogger.printStatus (package:flutter_tools/src/commands/daemon.dart:849)
#5      printStatus (package:flutter_tools/src/globals.dart:39)
#6      FlutterDevice.startEchoingDeviceLog.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:237)
#7      _rootRunUnary (dart:async/zone.dart:1134)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#11     _DelayedData.perform (dart:async/stream_impl.dart:578)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#19     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

```

**Comment by lovasoa** [comment]
I have the same problem that seems to happen randomly (Ubuntu 16.04)

```
F/libc    (21552): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 21580 (ui_thread)
Unhandled exception:
NoSuchMethodError: The getter 'stdout' was called on null.
Receiver: null
Tried calling: stdout
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      stdout (package:flutter_tools/src/base/io.dart:176)
#2      StdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:100)
#3      StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:95)
#4      _AppRunLogger.printStatus (package:flutter_tools/src/commands/daemon.dart:849)
#5      printStatus (package:flutter_tools/src/globals.dart:39)
#6      ResidentRunner._serviceDisconnected (package:flutter_tools/src/resident_runner.dart:756)
#7      _rootRun (dart:async/zone.dart:1122)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151)
#10     _Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603)
#11     _Future._propagateToListeners (dart:async/future_impl.dart:659)
#12     _Future._completeWithValue (dart:async/future_impl.dart:477)
#13     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#19     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
