### ISSUE TITLE
Engine roll failing on Windows integration tests

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#119665]
[dart_for_build_tests_shard_and_subshard_3_3/test_stdout](https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20build_tests_3_3/35058/overview):
```
[ +744 ms]   [ +744 ms] Persisting file store
[  +13 ms]   [  +13 ms] Done persisting file store
[  +10 ms]   [   +8 ms] Target unpack_windows failed: Exception: Unsupported file type "notFound" for C:\b\s\w\ir\x\w\flutter\bin\cache\artifacts\engine\windows-x64\flutter_windows.dll.exp
[        ]              #0      unpackDesktopArtifacts (package:flutter_tools/src/build_system/targets/desktop.dart:33:7)
[        ]              #1      UnpackWindows.build (package:flutter_tools/src/build_system/targets/windows.dart:80:29)
[        ]              #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:27)
[        ]              <asynchronous suspension>
[        ]              #3      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[        ]              <asynchronous suspension>
[        ]              #4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
[        ]              <asynchronous suspension>
[        ]              #5      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
```

[run_windows_home_scroll_perf__timeline_summary/test_stdout](https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20windows_home_scroll_perf__timeline_summary/17378/overview):
```
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [   +5 ms]   [   +4 ms] executing: C:\b\s\w\ir\x\w\recipe_cleanup\tmp8h5hnvuy\flutter sdk\bin\cache\artifacts\engine\windows-x64-profile\gen_snapshot --deterministic --snapshot_kind=app-aot-elf --elf=C:\b\s\w\ir\x\w\recipe_cleanup\tmp8h5hnvuy\flutter sdk\dev\integration_tests\flutter_gallery\.dart_tool\flutter_build\ab45c735ff0a8dbdfd4d0223d2e8cb22\app.so --strip C:\b\s\w\ir\x\w\recipe_cleanup\tmp8h5hnvuy\flutter sdk\dev\integration_tests\flutter_gallery\.dart_tool\flutter_build\ab45c735ff0a8dbdfd4d0223d2e8cb22\app.dill
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [   +3 ms]   [   +4 ms] Persisting file store
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [  +20 ms]   [  +19 ms] Done persisting file store
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [  +15 ms]   [  +12 ms] Target unpack_windows failed: Exception: Unsupported file type "notFound" for C:\b\s\w\ir\x\w\recipe_cleanup\tmp8h5hnvuy\flutter sdk\bin\cache\artifacts\engine\windows-x64-profile\flutter_windows.dll.exp
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #0      unpackDesktopArtifacts (package:flutter_tools/src/build_system/targets/desktop.dart:33:7)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #1      UnpackWindows.build (package:flutter_tools/src/build_system/targets/windows.dart:80:29)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:27)
```

[run_test.dart_for_tool_integration_tests_shard_and_subshard_4_6/test_stdout](https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_4_6/11546/overview):
```
RUNNING: cd packages\flutter_tools; ..\..\bin\cache\dart-sdk\bin\dart.exe run test --test-randomize-ordering-seed=20230131 -j1 --no-color test\integration.shard\flutter_build_windows_test.dart test\integration.shard\flutter_build_with_compilation_error_test.dart test\integration.shard\flutter_gen_test.dart test\integration.shard\flutter_run_test.dart test\integration.shard\flutter_run_with_error_test.dart test\integration.shard\forbidden_imports_test.dart test\integration.shard\gen_l10n_test.dart test\integration.shard\gradle_non_android_plugin_test.dart test\integration.shard\hot_reload_errors_test.dart test\integration.shard\hot_reload_test.dart --file-reporter=json:C:\b\s\w\ir\x\w\flutter\metrics.json
Shuffling test order with --test-randomize-ordering-seed=20230131
00:00 +0: test\integration.shard\flutter_build_windows_test.dart: flutter build windows command (setUpAll)
00:05 +0: test\integration.shard\flutter_build_windows_test.dart: flutter build windows command flutter build windows creates exe
00:42 +0 -1: test\integration.shard\flutter_build_windows_test.dart: flutter build windows command flutter build windows creates exe [E]
  Expected: <0>
    Actual: <1>
  
  package:test_api                                             expect
  test\integration.shard\flutter_build_windows_test.dart 69:7  main.<fn>.<fn>
  dart:async                                                   runZoned
  test\src\common.dart 197:14                                  testWithoutContext.<fn>
  test\src\common.dart 166:18                                  test.<fn>
  
00:42 +0 -1: test\integration.shard\flutter_build_windows_test.dart: flutter build windows command flutter build windows sets build name and build number
00:49 +0 -2: test\integration.shard\flutter_build_windows_test.dart: flutter build windows command flutter build windows sets build name and build number [E]
  Exception: GetVersionInfo failed.
  test\integration.shard\flutter_build_windows_test.dart 148:5   _getProductVersion
  test\integration.shard\flutter_build_windows_test.dart 113:37  main.<fn>.<fn>
  dart:async                                                     runZoned
  test\src\common.dart 197:14                                    testWithoutContext.<fn>
  test\src\common.dart 166:18                                    test.<fn>
  
00:49 +0 -2: test\integration.shard\flutter_build_windows_test.dart: flutter build windows command flutter build windows sets build name
00:55 +0 -3: test\integration.shard\flutter_build_windows_test.dart: flutter build windows command flutter build windows sets build name [E]
  Exception: GetVersionInfo failed.
  test\integration.shard\flutter_build_windows_test.dart 148:5  _getProductVersion
  test\integration.shard\flutter_build_windows_test.dart 93:37  main.<fn>.<fn>
  dart:async                                                    runZoned
  test\src\common.dart 197:14                                   testWithoutContext.<fn>
  test\src\common.dart 166:18                                   test.<fn>
```

**Comment by bdero** [comment]
Failed roll: https://github.com/flutter/flutter/pull/119662

**Comment by bdero** [comment]
This is expected to be fixed when this recipe revert propagates: https://flutter-review.git.corp.google.com/c/recipes/+/38340

**Comment by bdero** [comment]
This has been resolved.
