### ISSUE TITLE
Files missing in gn windows artifacts

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#119663]
https://ci.chromium.org/p/flutter/builders/try/Windows%20windows_home_scroll_perf__timeline_summary/17378?

```
+20 ms]   [  +19 ms] Done persisting file store
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [  +15 ms]   [  +12 ms] Target unpack_windows failed: Exception: Unsupported file type "notFound" for C:\b\s\w\ir\x\w\recipe_cleanup\tmp8h5hnvuy\flutter sdk\bin\cache\artifacts\engine\windows-x64-profile\flutter_windows.dll.exp
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #0      unpackDesktopArtifacts (package:flutter_tools/src/build_system/targets/desktop.dart:33:7)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #1      UnpackWindows.build (package:flutter_tools/src/build_system/targets/windows.dart:80:29)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:27)
```

**Comment by godofredoc** [comment]
More failures:

* https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_test/24633?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20build_tests_1_3/35075?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20build_tests_2_3/34699?
* bhttps://ci.chromium.org/p/flutter/builders/try/Windows%20build_tests_3_3/35058?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20framework_tests_misc/32574?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20tool_integration_tests_3_6/11556?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20tool_integration_tests_4_6/11548?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20windows_home_scroll_perf__timeline_summary/17378?

**Comment by godofredoc** [comment]
The issue is because gn targets do not generate the following files:

* flutter_windows.dll.exp
* flutter_windows.dll.lib
* flutter_windows.dll.pdb

https://cs.opensource.google/flutter/flutter/+/master:packages/flutter_tools/lib/src/build_system/targets/windows.dart;l=18?q=flutter_windows.dll.exp&ss=flutter%2Fflutter
