### ISSUE TITLE
hot reload failing with -d all

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#11978]
## Steps to Reproduce

1. Start an iOS simulator and an Android emulator

2. Run these commands in a terminal:

```
flutter upgrade
cd examples/hello_world
flutter run -d all
```

When the app is up on both, hit `r` in the terminal and get this crash:

```
Initializing hot reload...                               |Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39)
#1      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:497)
#2      _rootRunUnary (dart:async/zone.dart:1128)
#3      _CustomZone.runUnary (dart:async/zone.dart:1012)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#7      _Future._completeWithValue (dart:async/future_impl.dart:478)
#8      Future.wait.<anonymous closure> (dart:async/future.dart:392)
#9      _rootRunUnary (dart:async/zone.dart:1128)
#10     _CustomZone.runUnary (dart:async/zone.dart:1012)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#14     _Future._complete (dart:async/future_impl.dart:468)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#17     Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1022)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:30)
#19     _rootRunUnary (dart:async/zone.dart:1128)
#20     _CustomZone.runUnary (dart:async/zone.dart:1012)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#22     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#23     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#24     _Future._complete (dart:async/future_impl.dart:468)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#27     VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:731)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:30)
#29     _rootRunUnary (dart:async/zone.dart:1128)
#30     _CustomZone.runUnary (dart:async/zone.dart:1012)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#32     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#33     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#34     _Future._completeWithValue (dart:async/future_impl.dart:478)
#35     _Future.timeout.<anonymous closure> (dart:async/future_impl.dart:734)
#36     _rootRunUnary (dart:async/zone.dart:1128)
#37     _CustomZone.runUnary (dart:async/zone.dart:1012)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#39     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#40     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#41     _Future._complete (dart:async/future_impl.dart:468)
#42     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#43     Future.any.<anonymous closure> (dart:async/future.dart:451)
#44     _rootRunUnary (dart:async/zone.dart:1128)
#45     _CustomZone.runUnary (dart:async/zone.dart:1012)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#47     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#48     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#49     _Future._complete (dart:async/future_impl.dart:468)
#50     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#51     Client._handleSingleResponse (package:json_rpc_2/src/client.dart:191)
#52     Client._handleResponse (package:json_rpc_2/src/client.dart:181)
#53     _rootRunUnary (dart:async/zone.dart:1128)
#54     _CustomZone.runUnary (dart:async/zone.dart:1012)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#58     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#59     _StreamController._add (dart:async/stream_controller.dart:667)
#60     _StreamController.add (dart:async/stream_controller.dart:613)
#61     Peer.listen.<anonymous closure> (package:json_rpc_2/src/peer.dart:91)
#62     _rootRunUnary (dart:async/zone.dart:1128)
#63     _CustomZone.runUnary (dart:async/zone.dart:1012)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#67     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#68     _MapStream._handleData (dart:async/stream_pipe.dart:232)
#69     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#70     _rootRunUnary (dart:async/zone.dart:1128)
#71     _CustomZone.runUnary (dart:async/zone.dart:1012)
#72     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#73     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#74     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#75     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#76     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)
#77     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#78     _rootRunUnary (dart:async/zone.dart:1128)
#79     _CustomZone.runUnary (dart:async/zone.dart:1012)
#80     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#81     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#82     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#83     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#84     _StreamController._add (dart:async/stream_controller.dart:667)
#85     _rootRunUnary (dart:async/zone.dart:1128)
#86     _CustomZone.runUnary (dart:async/zone.dart:1012)
#87     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#88     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#89     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#90     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#91     _StreamController._add (dart:async/stream_controller.dart:667)
#92     _StreamController.add (dart:async/stream_controller.dart:613)
#93     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:io/websocket_impl.dart:1116)
#94     _rootRunUnary (dart:async/zone.dart:1128)
#95     _CustomZone.runUnary (dart:async/zone.dart:1012)
#96     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#97     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#98     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#99     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#100    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#101    _WebSocketProtocolTransformer._messageFrameEnd (dart:io/websocket_impl.dart:337)
#102    _WebSocketProtocolTransformer.add (dart:io/websocket_impl.dart:232)
#103    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#104    _rootRunUnary (dart:async/zone.dart:1128)
#105    _CustomZone.runUnary (dart:async/zone.dart:1012)
#106    _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#107    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#108    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#109    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#110    _StreamController._add (dart:async/stream_controller.dart:667)
#111    _StreamController.add (dart:async/stream_controller.dart:613)
#112    _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#113    _rootRunUnary (dart:async/zone.dart:1132)
#114    _CustomZone.runUnary (dart:async/zone.dart:1012)
#115    _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#116    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#117    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#118    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#119    _StreamController._add (dart:async/stream_controller.dart:667)
#120    _StreamController.add (dart:async/stream_controller.dart:613)
#121    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#122    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#123    _microtaskLoop (dart:async/schedule_microtask.dart:41)
#124    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#125    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#126    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
mit-macbookpro2:hello_world mit$
```

**Comment by mit-mit** [comment]
Cc @a-siva

**Comment by zanderso** [comment]
The Completer `retrieveFirstReloadReport` at https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L505 should be completed only once.

**Comment by zanderso** [comment]
Fixed by https://github.com/flutter/flutter/pull/12178

**Comment by mit-mit** [comment]
Works great now, thanks!
