### ISSUE TITLE
`ios_content_validation_test` flaked: Crash when compiling scroll_notification_observer.dart "NoSuchMethodError: Class 'int' has no instance getter 'name'."

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#119778]
```
[ios_content_validation_test] [STDOUT] stdout:            error: [+5172 ms] Unhandled exception:
[ios_content_validation_test] [STDOUT] stdout:                       Crash when compiling package:flutter/src/widgets/scroll_notification_observer.dart:
[ios_content_validation_test] [STDOUT] stdout:                       NoSuchMethodError: Class 'int' has no instance getter 'name'.
[ios_content_validation_test] [STDOUT] stdout:                       Receiver: 3322010
[ios_content_validation_test] [STDOUT] stdout:                       Tried calling: name
[ios_content_validation_test] [STDOUT] stdout: 
[ios_content_validation_test] [STDOUT] stdout:                       #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
[ios_content_validation_test] [STDOUT] stdout:                       #1      SourceFunctionBuilderImpl.computeFormalParameterScope (package:front_end/src/fasta/source/source_function_builder.dart:215:22)
```
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20ios_content_validation_test/9122

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8790312798644413297/+/u/run_ios_content_validation_test/test_stdout

**Comment by a-siva** [comment]
Do we still see these flaky errors with the latest version of Flutter ?

**Comment by jmagman** [comment]
@keyonghan do you know if there's a way to search the build logs to see if this recently flaked?

**Comment by keyonghan** [comment]
> @keyonghan do you know if there's a way to search the build logs to see if this recently flaked?

Does this test still exist in the CI? https://flutter-dashboard.appspot.com/#/build?repo=flutter&branch=master&taskFilter=ios_content_validation_test returns nothing.

**Comment by jmagman** [comment]
@keyonghan it lives in the `tool_host_cross_arch_tests` tests now https://github.com/flutter/flutter/pull/142272

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/host_cross_arch.shard/ios_content_validation_test.dart

However this crash wouldn't be specific to this test, are we able to search logs for any version of this crash?

**Comment by keyonghan** [comment]
No. It's not supported as of today. But @vashworth has a proposal flutter.dev/go/ci-post-test-analysis
