### ISSUE TITLE
Clipboard.setData crashes the app on Android

### ISSUE THREAD

**Issue by duckprogrammerr** [flutter/flutter#119754]
hi guys , i'm facing a problem when i use Clipboard.setData its craches my app on Android Emulator

<details>
<summary>Code sample</summary>
 

  ``` dart  
 ElevatedButton.icon(
      onPressed: () async {
          if (place.contact.contains('.')) {
             // place.contact can't be null                          
             await Clipboard.setData( ClipboardData(text: place.contact) );
}
...
)
```

</details>

<details>
  <summary>Logs</summary>

```
E/AndroidRuntime(24524): *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-9
E/AndroidRuntime(24524): java.lang.IllegalStateException: beginBroadcast() called while already in a broadcast
E/AndroidRuntime(24524): 	at android.os.RemoteCallbackList.beginBroadcast(RemoteCallbackList.java:242)
E/AndroidRuntime(24524): 	at com.android.server.clipboard.ClipboardService.setPrimaryClipInternal(ClipboardService.java:583)
E/AndroidRuntime(24524): 	at com.android.server.clipboard.ClipboardService$1.onHostClipboardUpdated(ClipboardService.java:205)
E/AndroidRuntime(24524): 	at com.android.server.clipboard.HostClipboardMonitor.run(ClipboardService.java:125)
E/AndroidRuntime(24524): 	at java.lang.Thread.run(Thread.java:923)

```

```
```

```
[√] Flutter (Channel stable, 3.3.8)
    • Flutter version 3.3.8 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
 
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Platform android-33, build-tools 32.1.0-rc1
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.



[√] Android Studio (version 2021.1)
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.74.3)
    • Flutter extension version 3.48.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)     
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19044.2486]
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 109.0.1518.69
      (unsupported)

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by duckprogrammerr** [comment]
When i use normal String with const it's works fine

**Comment by duckprogrammerr** [comment]
i solved it 🤓 .

just turn off my emulator and wiped the clipbaord then every thing just run fine

**Comment by duckprogrammerr** [comment]
i solved it 🤓 .

just turn off my emulator and wiped the clipbaord then every thing just run fine
