### ISSUE TITLE
Pattern matching crashed on dart pad

### ISSUE THREAD

**Issue by user97116** [flutter/flutter#119888]
## Steps to Reproduce

Hey, I am using pattern matching for test but it doesn't work, here is the code

```dart
(int,int,int) d() {
  return (1,2,3);
}
void main() {
  var (a,b,c) = d();
}
```

**Expected results:** it must return assigned values to a,b and c respectively

**Actual results:**  it shows crash

```
lib/main.dart:1:15:
Internal Error: The compiler crashed when compiling this element.
(int,int,int) d() {
              ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.0.0-103.0.dev), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Unsupported operation: Unhandled node RecordType((1.0, 2.0, 3.0)) (RecordLiteral)
#0      KernelSsaGraphBuilder.defaultNode (package:compiler/src/ssa/builder.dart:1736:5)
#1      Visitor.defaultTreeNode (package:kernel/visitor.dart:1154:39)
#2      TreeVisitor.defaultExpression (package:kernel/visitor.dart:199:43)
#3      TreeVisitor.visitRecordLiteral (package:kernel/visitor.dart:306:47)
#4      RecordLiteral.accept (package:kernel/ast.dart:8946:44)
#5      KernelSsaGraphBuilder.visitReturnStatement (package:compiler/src/ssa/builder.dart:1853:24)
#6      ReturnStatement.accept (package:kernel/ast.dart:10737:43)
#7      KernelSsaGraphBuilder.visitBlock (package:compiler/src/ssa/builder.dart:1791:17)
#8      Block.accept (package:kernel/ast.dart:9722:43)
#9      KernelSsaGraphBuilder._visitInlinedFunction (package:compiler/src/ssa/builder.dart:6466:31)
#10     KernelSsaGraphBuilder._doInline (package:compiler/src/ssa/builder.dart:6443:5)
#11     KernelSsaGraphBuilder._doTryInlineMethod.doInlining.<anonymous closure> (package:compiler/src/ssa/builder.dart:6129:11)
#12     KernelSsaGraphBuilder._inlinedFrom.<anonymous closure> (package:compiler/src/ssa/builder.dart:937:21)
#13     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#14     KernelSsaGraphBuilder._inlinedFrom (package:compiler/src/ssa/builder.dart:935:14)
#15     KernelSsaGraphBuilder._doTryInlineMethod.doInlining (package:compiler/src/ssa/builder.dart:6124:7)
#16     KernelSsaGraphBuilder._doTryInlineMethod (package:compiler/src/ssa/builder.dart:6136:7)
#17     KernelSsaGraphBuilder._tryInlineMethod (package:compiler/src/ssa/builder.dart:5893:21)
#18     KernelSsaGraphBuilder._pushStaticInvocation (package:compiler/src/ssa/builder.dart:5079:9)
#19     KernelSsaGraphBuilder.visitStaticInvocation (package:compiler/src/ssa/builder.dart:3921:7)
#20     StaticInvocation.accept (package:kernel/ast.dart:6980:44)
#21     KernelSsaGraphBuilder.visitVariableDeclaration (package:compiler/src/ssa/builder.dart:3630:25)
#22     VariableDeclaration.accept (package:kernel/ast.dart:11311:43)
#23     KernelSsaGraphBuilder.visitBlock (package:compiler/src/ssa/builder.dart:1791:17)
#24     Block.accept (package:kernel/ast.dart:9722:43)
#25     KernelSsaGraphBuilder._buildFunctionNode (package:compiler/src/ssa/builder.dart:1252:24)
#26     KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder.dart:450:15)
#27     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#28     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder.dart:435:21)
#29     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:533:22)
#30     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#31     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:515:18)
#32     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:361:21)
#33     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:87:28)
#34     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:420:30)
#35     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:322:43)
#36     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:474:29)
#37     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:771:70)
#38     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#39     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:771:32)
#40     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#41     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:769:28)
#42     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:142:15)
#43     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:767:18)
#44     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:252:12)
#45     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:268:5)
#46     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:763:16)
#47     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#48     Compiler.emptyQueue (package:compiler/src/compiler.dart:762:14)
#49     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:786:7)
#50     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#51     Compiler.processQueue (package:compiler/src/compiler.dart:780:14)
#52     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:517:5)
#53     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:712:23)
<asynchronous suspension>
#54     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:315:7)
<asynchronous suspension>
#55     Compiler.runInternal (package:compiler/src/compiler.dart:314:5)
<asynchronous suspension>
#56     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:235:11)
<asynchronous suspension>
#57     main (package:compiler/src/dart2js.dart:1449:3)
<asynchronous suspension>
```

Documentation

**Comment by danagbemava-nc** [comment]
Hi @user97116, kindly report this over on the dart repo as indicated by the error message. http://dartbug.com/new

Closing from here as this is not a flutter issue. 

Thank you
