### ISSUE TITLE
Missing windows-x64-profile\gen_snapshot in GN+Ninja archives

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#119887]
https://ci.chromium.org/p/flutter/builders/try/Windows%20windows_home_scroll_perf__timeline_summary/17603?

```
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [  +16 ms]   [  +13 ms] Target aot_elf_profile failed: ProcessException: Failed to find "C:\b\s\w\ir\x\w\recipe_cleanup\tmpkg7ee70_\flutter sdk\bin\cache\artifacts\engine\windows-x64-profile\gen_snapshot" in the search path.
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]                Command: C:\b\s\w\ir\x\w\recipe_cleanup\tmpkg7ee70_\flutter sdk\bin\cache\artifacts\engine\windows-x64-profile\gen_snapshot 
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:683:24)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #2      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [   +1 ms]              #3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:682:12)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #4      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:428:28)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #5      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:448:35)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #6      GenSnapshot.run (package:flutter_tools/src/base/build.dart:75:26)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #7      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:222:56)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #8      AotElfBase.build (package:flutter_tools/src/build_system/targets/common.dart:294:52)
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]              #9      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:27)
```

**Comment by godofredoc** [comment]
`gen_snapshot.exe` is missing in `windows-x64-profile/windows-x64-flutter.zip`

Recipes artifact: https://storage.cloud.google.com/flutter_infra_release/flutter/2696fff8716d26addcd39c051137bbbe8893d2b0/windows-x64-profile/windows-x64-flutter.zip

GN+Ninja artifact:

https://storage.cloud.google.com/flutter_infra_release/flutter/a2f53699c6782eea28de317d2e95b542a90d87d4/windows-x64-profile/windows-x64-flutter.zip

**Comment by godofredoc** [comment]
https://github.com/flutter/flutter/pull/119886/checks?check_run_id=11079329189

```
[  +11 ms]   [   +8 ms] Target aot_elf_release failed: ProcessException: Failed to find "C:\b\s\w\ir\x\w\flutter\bin\cache\artifacts\engine\windows-x64-release\gen_snapshot" in the search path.
[        ]                Command: C:\b\s\w\ir\x\w\flutter\bin\cache\artifacts\engine\windows-x64-release\gen_snapshot 
[        ]              #0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
[        ]              #1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:683:24)
[        ]              #2      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
[        ]              #3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:682:12)
[        ]              #4      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:428:28)
[        ]              #5      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:448:35)
[        ]              #6      GenSnapshot.run (package:flutter_tools/src/base/build.dart:75:26)
[        ]              #7      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:222:56)
[        ]              #8      AotElfBase.build (package:flutter_tools/src/build_system/targets/common.dart:294:52)
[        ]              #9      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:27)
[        ]              <asynchronous suspension>
```

**Comment by godofredoc** [comment]
List of failing builds:

* https://ci.chromium.org/p/flutter/builders/try/Windows%20windows_home_scroll_perf__timeline_summary/17604?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20tool_integration_tests_4_6/11694?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20tool_integration_tests_3_6/11702?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20build_tests_3_3/35283?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20build_tests_2_3/34925?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20build_tests_1_3/35300?

Error is here:

https://cs.opensource.google/flutter/engine/+/master:build/archives/BUILD.gn;l=228
