### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by KirstenDunst** [flutter/flutter#119800]
## Command
```
flutter run -d 7454d02739d1388b435231fd78e0fe9007ae05f3
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
#2      VmService.streamListen (package:vm_service/src/vm_service.dart:2209:7)
#3      IOSDeviceLogReader._listenToUnifiedLoggingEvents (package:flutter_tools/src/ios/devices.dart:672:44)
#4      IOSDeviceLogReader.connectedVMService= (package:flutter_tools/src/ios/devices.dart:658:7)
#5      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:337:50)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.1, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.7.1 on channel stable at /Users/caoshixin/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 7048ed95a5 (17 hours ago), 2023-02-01 09:07:31 -0800
    [32m•[39m Engine revision 800594f1f4
    [32m•[39m Dart version 2.19.1
    [32m•[39m DevTools version 2.20.1
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [32m•[39m Android SDK at /Users/caoshixin/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 30.0.3
    [32m•[39m ANDROID_HOME = /Users/caoshixin/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 13.4.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 13F100
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[32m[✓][39m VS Code (version 1.74.3)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.58.0

[32m[✓][39m Proxy Configuration
    [32m•[39m HTTP_PROXY is set
    [32m•[39m NO_PROXY is localhost,127.0.0.1,::1
    [32m•[39m NO_PROXY contains localhost
    [32m•[39m N

**Comment by huycozy** [comment]
Hi @KirstenDunst 
What target platform does the issue happen on? Can you retry on the latest master channel to see if it still occurs?

```
flutter channel master
flutter upgrade
```

If it still persists, can you share the complete output of `flutter run -v`?

**Comment by KirstenDunst** [comment]
I use channel stable，version 3.7.0

**Comment by huycozy** [comment]
@KirstenDunst Please help to clarify things at https://github.com/flutter/flutter/issues/119800#issuecomment-1413559292.

This may be related to https://github.com/flutter/flutter/issues/117988 or https://github.com/flutter/flutter/issues/101962 but the log is not exactly the same.
