### ISSUE TITLE
flutter build command fails when trying to build an app bundle with locally build engine

### ISSUE THREAD

**Issue by eladmaimoni** [flutter/flutter#119992]
## Steps to Reproduce

I build the flutter engine locally on my Windows 11 PC in order to experiment with the embedding API.
Now my understanding is (please correct me if I am wrong) that I should build my flutter application bundle targeting my specific engine. This is the command I run from the root directory of my flutter application:

`flutter build bundle --debug --local-engine-src-path=/c/Libraries/engine/src --local-engine=/c/Libraries/engine/src/out/host_debug_unopt`

note the if I comment out the problematic if statement in assertions.dart the error does not happen.

![image](https://user-images.githubusercontent.com/17446835/216760497-b45254c3-58b5-4308-bea8-d30c71ba0111.png)

## Logs

```
/C:/Libraries/flutter/packages/flutter/lib/src/foundation/assertions.dart:679:22: Error: 'NullThrownError' isn't a type.
    if (exception is NullThrownError) { // ignore: deprecated_member_use
                     ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:246:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#5      BundleBuilder.build (package:flutter_tools/src/bundle_builder.dart:75:32)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:138:5)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Failed to build bundle.


## Logs (verbose)

`$ flutter build bundle --debug --local-engine-src-path=/c/Libraries/engine/src --local-engine=/c/Libraries/engine/src/out/host_debug_unopt --verbose
[   +9 ms] executing: [C:\Libraries\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 7048ed95a5ad3e43d697e0c397464193991fc230
[        ] executing: [C:\Libraries\flutter/] git tag --points-at 7048ed95a5ad3e43d697e0c397464193991fc230
[  +35 ms] Exit code 0 from: git tag --points-at 7048ed95a5ad3e43d697e0c397464193991fc230
[        ] 3.7.1
[   +8 ms] Local engine source at C:/Libraries/engine/src
[   +3 ms] executing: [C:\Libraries\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\Libraries\flutter/] git ls-remote --get-url origin
[  +19 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +32 ms] executing: [C:\Libraries\flutter/] git rev-parse --abbrev-ref HEAD
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +33 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +32 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +35 ms] Skipping pub get: version match.
[ +116 ms] Generating C:\workspace\ultrawis\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +46 ms] 💪 Building with sound null safety 💪
[   +5 ms] Initializing file store
[   +7 ms] Done initializing file store
[  +23 ms] Skipping target: gen_localizations
[   +7 ms] Skipping target: gen_dart_plugin_registrant
[ +569 ms] kernel_snapshot: Starting due to {}
[   +6 ms] C:\Libraries\engine\src\out\host_debug_unopt\dart-sdk\bin\dart.exe --disable-dart-dev C:\Libraries\engine\src\out\host_debug_unopt\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\Libraries\engine\src\out\host_debug_unopt\flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--no-link-platform --packages C:\workspace\ultrawis\.dart_tool\package_config.json --output-dill C:\workspace\ultrawis\.dart_tool\flutter_build\665fc33563a318020b342084129978ff\app.dill --depfile
C:\workspace\ultrawis\.dart_tool\flutter_build\665fc33563a318020b342084129978ff\kernel_snapshot.d --filesystem-scheme org-dartlang-root --incremental --initialize-from-dill
C:\workspace\ultrawis\.dart_tool\flutter_build\665fc33563a318020b342084129978ff\app.dill --verbosity=error package:ultrawis/main.dart
[ +719 ms] /C:/Libraries/flutter/packages/flutter/lib/src/foundation/assertions.dart:679:22: Error: 'NullThrownError' isn't a type.
[   +1 ms]     if (exception is NullThrownError) { // ignore: deprecated_member_use
[        ]                      ^^^^^^^^^^^^^^^
[ +166 ms] Persisting file store
[   +8 ms] Done persisting file store
[   +3 ms] Target kernel_snapshot failed: Exception
           #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:246:7)
           <asynchronous suspension>
           #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
           <asynchronous suspension>
           #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
           <asynchronous suspension>
           #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
           <asynchronous suspension>
           #5      BundleBuilder.build (package:flutter_tools/src/bundle_builder.dart:75:32)
           <asynchronous suspension>
           #6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:138:5)
           <asynchronous suspension>
           #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[   +7 ms] "flutter bundle" took 1,823ms.
[   +3 ms] Failed to build bundle.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      BundleBuilder.build (package:flutter_tools/src/bundle_builder.dart:85:7)
           <asynchronous suspension>
           #2      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:138:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +61 ms] ensureAnalyticsSent: 60ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1`


</details>

**Comment by exaby73** [comment]
I am unable to currently compile the engine to reproduce this issue. Labelling for further insights from the team

**Comment by chinmaygarde** [comment]
It looks like you are trying to use a mismatched engine and framework. Both should be near tip-of-tree or using the same engine SHA specified in the [`engine.version` file](https://github.com/flutter/flutter/blob/40b5e4cb5e7720cc5ab5edb59cb96eab5530d829/bin/internal/engine.version).
