### ISSUE TITLE
[flutter_tools] `yes | flutter doctor --android-licenses` leads to broken pipe on macOS

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#120114]
This was obscured by a crash in a .catchError callback before https://github.com/flutter/flutter/commit/b8f5394a5ca6d2bce062d9d0a20aaffb4289fb4c

```
danny@Dannys-MacBook-Pro flutter % yes | flutter doctor --android-licenses
Warning: This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: Errors limit exceeded. To receive all errors set com.sun.xml.bind logger to FINEST level.
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}api-level>
All SDK package licenses accepted.======] 100% Computing updates...             

Echoing stdin to the licenses subprocess failed:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1195:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1938:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2385:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2128:26)
#4      _Socket._onData (dart:io-patch/socket_patch.dart:2356:19)
#5      _rootRunUnary (dart:async/zone.dart:1414:13)
#6      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1876:23)
#14     _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1354:14)
#15     _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1361:7)
#16     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1396:13)
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Comment by christopherfujino** [comment]
The relevant function looks like:

```dart
    try {
      final Process process = await _processManager.start(
        <String>[_androidSdk!.sdkManagerPath!, '--licenses'],
        environment: _androidSdk!.sdkManagerEnv,
      );

      // The real stdin will never finish streaming. Pipe until the child process
      // finishes.
      unawaited(process.stdin.addStream(_stdio.stdin)
        // If the process exits unexpectedly with an error, that will be
        // handled by the caller.
        .then(
          (Object? socket) => socket,
          onError: (dynamic err, StackTrace stack) {
            _logger.printError('Echoing stdin to the licenses subprocess failed:');
            _logger.printError('$err\n$stack');
          },
        ),
      );

      // Wait for stdout and stderr to be fully processed, because process.exitCode
      // may complete first.
      try {
        await Future.wait<void>(<Future<void>>[
          _stdio.addStdoutStream(process.stdout),
          _stdio.addStderrStream(process.stderr),
        ]);
      } on Exception catch (err, stack) {
        _logger.printError('Echoing stdout or stderr from the license subprocess failed:');
        _logger.printError('$err\n$stack');
      }

      final int exitCode = await process.exitCode;
      return exitCode == 0;
    } on ProcessException catch (e) {
      throwToolExit(_userMessages.androidCannotRunSdkManager(
        _androidSdk?.sdkManagerPath ?? '',
        e.toString(),
        _platform,
      ));
    }
```

The comment that the process exiting with an error will be handled by the caller appears not to be try (there is no error handling at the one non-test callsite in [lib/src/doctor.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L366)

**Comment by christopherfujino** [comment]
Oh, I see, this is just the stacktrace from the `_logger.printError`, since the sub-process exited 0 the tool also exited 0.

**Comment by christopherfujino** [comment]
This is Danny's full log output:

```
danny@Dannys-MacBook-Pro flutter % yes | flutter doctor --android-licenses
Warning: This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: Errors limit exceeded. To receive all errors set com.sun.xml.bind logger to FINEST level.
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}api-level>
All SDK package licenses accepted.======] 100% Computing updates...             

Echoing stdin to the licenses subprocess failed:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1195:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1938:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2385:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2128:26)
#4      _Socket._onData (dart:io-patch/socket_patch.dart:2356:19)
#5      _rootRunUnary (dart:async/zone.dart:1414:13)
#6      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1876:23)
#14     _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1354:14)
#15     _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1361:7)
#16     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1396:13)
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Comment by christopherfujino** [comment]
Reducing priority as this is not blocking anyone, just a confusing user experience.

**Comment by christopherfujino** [comment]
Ahh, so this is actually something we can most likely ignore (if the underlying sub-process has already finished, it doesn't really matter that we failed to forward tool stdin to it). This was previously being swallowed (and the stacktrace hidden unless you were in verbose mode) before sound null-safety. We should return to this behavior, with the added restraint that we toolexit if the sub-process exited non-zero.
