### ISSUE TITLE
[Plugins] Not a valid object name FETCH_HEAD when running  update-release-info

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#120116]
After following the instructions listed in the [plugin readme](https://github.com/flutter/plugins/blob/main/script/tool/README.md)
I have the tool fail with the following stack trace. 

To reproduce you can clone a fresh copy of the plugins repo or you can run `rm .git/FETCH_HEAD` from the root directory of plugins. 

The issue is that FETCH_HEAD is not guaranteed to be present in all git directories. It is a temporary file. 

Workaround for this issue is to run `git fetch`. 
```
dart run ./script/tool/bin/flutter_plugin_tools.dart update-release-info --version=minimal --changelog="SOME TEXT."
Unhandled exception:
ProcessException: fatal: Not a valid object name FETCH_HEAD
  Command: git merge-base FETCH_HEAD HEAD
#0      _throwIfProcessFailed (package:git/src/top_level.dart:39:5)
#1      runGit (package:git/src/top_level.dart:17:5)
<asynchronous suspension>
#2      GitVersionFinder.getBaseSha (package:flutter_plugin_tools/src/common/git_version_finder.dart:109:30)
<asynchronous suspension>
#3      GitVersionFinder.getChangedFiles (package:flutter_plugin_tools/src/common/git_version_finder.dart:36:28)
<asynchronous suspension>
#4      UpdateReleaseInfoCommand.initializeRun (package:flutter_plugin_tools/src/update_release_info_command.dart:110:25)
<asynchronous suspension>
#5      PackageLoopingCommand._runInternal (package:flutter_plugin_tools/src/common/package_looping_command.dart:280:5)
<asynchronous suspension>
#6      PackageLoopingCommand.run (package:flutter_plugin_tools/src/common/package_looping_command.dart:257:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      main.<anonymous closure> (package:flutter_plugin_tools/src/main.dart:94:12)
<asynchronous suspension>
```

**Comment by reidbaker** [comment]
https://github.com/flutter/plugins/pull/7111

**Comment by stuartmorgan** [comment]
I should add information about using `base-sha` to those instructions; I thought I already had, but apparently not.
