### ISSUE TITLE
Oops; flutter has exited unexpectedly: "type 'Null' is not a subtype of type 'String' in type cast".

### ISSUE THREAD

**Issue by DeToxer** [flutter/flutter#120187]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. Upgrade from flutter 3.3.10 to 3.7.1
2. Run pub get

Observe the following log:

Oops; flutter has exited unexpectedly: "type 'Null' is not a subtype of type 'String' in type cast".

## Logs
_CastError: (#0      new Plugin._fromLegacyYaml (package:flutter_tools/src/plugins.dart:198:66))
```
#0      new Plugin._fromLegacyYaml (package:flutter_tools/src/plugins.dart:198:66)
#1      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:88:19)
#2      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#3      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#4      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#5      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#6      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:182:7)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-arm64, locale nb-NO)
    • Flutter version 3.7.1 on channel stable at /Users/detoxer/dev/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (6 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/detoxer/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/detoxer/Library/Android/sdk
    • Java binary at: /Users/detoxer/dev/ide/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/detoxer/dev/ide/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.73.1)
    • VS Code at /Users/detoxer/dev/ide/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 8BFD8725-EF0B-4B05-97EC-7C810DCD7B6A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 0.0.1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: true
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null

**Comment by exaby73** [comment]
Hello @DeToxer. With a newly generated project in 3.3.10, I cannot reproduce this issue when trying to run `pub get` in 3.7.1. Is there a way that you were able to consistently reproduce this issue?

**Comment by DeToxer** [comment]
> Hello @DeToxer. With a newly generated project in 3.3.10, I cannot reproduce this issue when trying to run `pub get` in 3.7.1. Is there a way that you were able to consistently reproduce this issue?

Unfortunately no. I am experiencing the same as you. When creating a new project everything works fine.
It's only in my own project that this happens consistently, which if hard for anyone else but me to reproduce.

Are you able to see anything in my logs that can point me in the right direction regarding debugging this issue? Do you want me to provide more information?

**Comment by DeToxer** [comment]
Hi again. I managed to get it to work. The problem was in my pubspec.yaml file.

I changed from this implementation:

```
  plugin:
    package: com.example.myplugin
    pluginClass: MyPlugin
    ios:
      pluginClass: MyPlugin
```
to this one
```
  plugin:
    platforms:
      android:
        package:  com.example.myplugin
        pluginClass: MyPlugin
      ios:
        pluginClass: MyPlugin
```
and now I'm able to run the app just fine

**Comment by s0nerik** [comment]
The actual problem in my case was that `dartPluginClass` is no longer valid for web implementation definition as of Flutter 3.7. `pluginClass` has to be used instead. This is relevant only to web implementations, all other implementations must still use `dartPluginClass` for dart-only implementations.
