### ISSUE TITLE
App turns gray / black after deactivating debug paint mode

### ISSUE THREAD

**Issue by levrik** [flutter/flutter#12024]
## Steps to Reproduce

1. Create new project
2. Run project
3. Activate debug paint mode -> exception thrown (see below)
4. Deactivate debug paint mode -> Screen turns black
5. Activate debug paint mode again -> Screen turns gray

Hot reload does not work. Only full reload.

For more detail see the following GIF:

![2017-09-09_17-50-20](https://user-images.githubusercontent.com/9491603/30241638-9340173c-9587-11e7-9e17-78961e20c07e.gif)

**Edit:** Since the stacktrace includes stuff about text painter I removed all text from the default app -> issue persists!

**Edit 2:** Issue does not occurs with current alpha `Framework revision 1c372c6803 (9 days ago)`

## Logs

After activating debug paint mode:

```
I/flutter ( 4650): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4650): The following assertion was thrown during paint():
I/flutter ( 4650): TextPainter.textDirection must be set to a non-null value before using the TextPainter.
I/flutter ( 4650): 'package:flutter/src/painting/text_painter.dart': Failed assertion: line 330: 'textDirection !=
I/flutter ( 4650): null'
I/flutter ( 4650):
I/flutter ( 4650): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4650): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4650): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4650):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4650):
I/flutter ( 4650): When the exception was thrown, this was the stack:
I/flutter ( 4650): #2      TextPainter.layout (package:flutter/src/painting/text_painter.dart:330)
I/flutter ( 4650): #3      _RenderCustomClip.debugPaintSize.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:1043)
I/flutter ( 4650): #5      _RenderCustomClip.debugPaintSize (package:flutter/src/rendering/proxy_box.dart:1023)
I/flutter ( 4650): #6      RenderClipRect.debugPaintSize.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:1090)
I/flutter ( 4650): #8      RenderClipRect.debugPaintSize (package:flutter/src/rendering/proxy_box.dart:1088)
I/flutter ( 4650): #9      RenderBox.debugPaint.<anonymous closure> (package:flutter/src/rendering/box.dart:2015)
I/flutter ( 4650): #11     RenderBox.debugPaint (package:flutter/src/rendering/box.dart:2013)
I/flutter ( 4650): #12     RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2371)
I/flutter ( 4650): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2370)
I/flutter ( 4650): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:137)
I/flutter ( 4650): #16     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:68)
I/flutter ( 4650): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2364)
I/flutter ( 4650): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:137)
I/flutter ( 4650): #19     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:68)
I/flutter ( 4650): #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2364)
I/flutter ( 4650): #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:137)
I/flutter ( 4650): #22     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:125)
I/flutter ( 4650): #23     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:329)
I/flutter ( 4650): #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2364)
I/flutter ( 4650): #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:137)
I/flutter ( 4650): #26     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:125)
I/flutter ( 4650): #27     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1443)
I/flutter ( 4650): #28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2364)
I/flutter ( 4650): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:137)
I/flutter ( 4650): #30     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:125)
I/flutter ( 4650): #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2364)
I/flutter ( 4650): #32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:137)
I/flutter ( 4650): #33     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2179)
I/flutter ( 4650): #34     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:343)
I/flutter ( 4650): #35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2364)
I/flutter ( 4650): #36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:137)
I/flutter ( 4650): #37     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:125)
I/flutter ( 4650): #38     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:329)
I/flutter ( 4650): #39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2364)
I/flutter ( 4650): #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:137)
I/flutter ( 4650): #41     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:125)
I/flutter ( 4650): #42     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1443)
I/flutter ( 4650): #43     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2364)
I/flutter ( 4650): #44     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:137)
I/flutter ( 4650): #45     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:125)
I/flutter ( 4650): #46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2364)
I/flutter ( 4650): #47     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:117)
I/flutter ( 4650): #48     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1152)
I/flutter ( 4650): #49     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:258)
I/flutter ( 4650): #50     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:531)
I/flutter ( 4650): #51     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:194)
I/flutter ( 4650): #52     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713)
I/flutter ( 4650): #53     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649)
I/flutter ( 4650): #54     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:86)
I/flutter ( 4650): #55     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:75)
I/flutter ( 4650): (elided 6 frames from class _AssertionError)
I/flutter ( 4650):
I/flutter ( 4650): The following RenderObject was being processed when the exception was fired:
I/flutter ( 4650):   RenderPadding#1d5e7 relayoutBoundary=up5
I/flutter ( 4650):   creator: Padding ← Align ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter ( 4650):   _InkFeatures-[GlobalKey#ab9ef ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter ( 4650):   PhysicalModel ← AnimatedPhysicalModel ← Material ← AppBar ← _FlexibleSpaceBarSettings ←
I/flutter ( 4650):   ConstrainedBox ← ⋯
I/flutter ( 4650):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter ( 4650):   constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=80.0)
I/flutter ( 4650):   size: Size(360.0, 80.0)
I/flutter ( 4650):   padding: EdgeInsets(0.0, 24.0, 0.0, 0.0)
I/flutter ( 4650):   textDirection: ltr
I/flutter ( 4650): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 4650):   RenderClipRect#8d0d9 relayoutBoundary=up6
I/flutter ( 4650):     RenderCustomSingleChildLayoutBox#24d18 relayoutBoundary=up7
I/flutter ( 4650):       RenderPadding#b2bc6 relayoutBoundary=up8
I/flutter ( 4650):         RenderCustomMultiChildLayoutBox#23764 relayoutBoundary=up9
I/flutter ( 4650):           RenderParagraph#52121 relayoutBoundary=up10
I/flutter ( 4650): ════════════════════════════════════════════════════════════ ════════════════════════════════════════
I/flutter ( 4650): Another exception was thrown: TextPainter.textDirection must be set to a non-null value before using the TextPainter.
I/flutter ( 4650): Another exception was thrown: TextPainter.textDirection must be set to a non-null value before using the TextPainter.
I/flutter ( 4650): Another exception was thrown: TextPainter.textDirection must be set to a non-null value before using the TextPainter.
```

After deactivating debug paint mode:

```
I/flutter ( 4650): Another exception was thrown: Tried to paint a RenderObject reentrantly.
```

`flutter analyze` was fine.

## Flutter Doctor

```
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale de-DE, channel master)
    • Flutter at D:\flutter
    • Framework revision 4262c1e9d3 (16 hours ago), 2017-09-08 16:47:40 -0700
    • Engine revision 2d7c30033d
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Levin\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = C:\Users\Levin\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by Hixie** [comment]
Oops. Will fix.

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/12026
