### ISSUE TITLE
Floating SnackBar presented off screen exception is triggered when "SnackBarBehavior.floating" is used

### ISSUE THREAD

**Issue by nck974** [flutter/flutter#120308]
## Steps to Reproduce

1. Create a widget with a button that triggers a snackbar with behavior Floating:
2. Tap the button and wait for the exception to be triggered.
3. The exception is triggered.

**Expected results:**: The popup is displayed without an Exception.

**Actual results:** An exception is triggered

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class SettingsScreen extends StatefulWidget {
  static var routeName = '/settings';

  const SettingsScreen({super.key});
  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  Future<void> _onDataExport() async {
    Future.delayed(const Duration(seconds: 3))
        .then((value) => ScaffoldMessenger.of(context)
          ..hideCurrentSnackBar()
          ..showSnackBar(const SnackBar(
            behavior: SnackBarBehavior.floating,
            content: Text(
              'File saved to xxxxxxxx',
            ),
          )));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Settings'),
        ),
        body: TextButton(
          child: const Text('Export all my data'),
          onPressed: () => _onDataExport(),
        ));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
Floating SnackBar presented off screen.

A SnackBar with behavior property set to SnackBarBehavior.floating is fully or partially off screen because some or all the widgets provided to Scaffold.floatingActionButton, Scaffold.persistentFooterButtons and Scaffold.bottomNavigationBar take up too much vertical space.

Consider constraining the size of these widgets to allow room for the SnackBar to be visible.

The relevant error-causing widget was
Scaffold
dashboard.dart:69
When the exception was thrown, this was the stack
#0      _ScaffoldLayout.performLayout.<anonymous closure>
scaffold.dart:1189
#1      _ScaffoldLayout.performLayout
scaffold.dart:1204
#2      MultiChildLayoutDelegate._callPerformLayout
custom_layout.dart:240
#3      RenderCustomMultiChildLayoutBox.performLayout
custom_layout.dart:410
#4      RenderObject._layoutWithoutResize
object.dart:2027
#5      PipelineOwner.flushLayout
object.dart:1020
#6      RendererBinding.drawFrame
binding.dart:516
#7      WidgetsBinding.drawFrame
binding.dart:865
#8      RendererBinding._handlePersistentFrameCallback
binding.dart:381
#9      SchedulerBinding._invokeFrameCallback
binding.dart:1289
#10     SchedulerBinding.handleDrawFrame
binding.dart:1218
#11     SchedulerBinding._handleDrawFrame
binding.dart:1076
#12     _invoke (dart:ui/hooks.dart:145:13)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#14     _drawFrame (dart:ui/hooks.dart:112:31)
The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#49aae NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITI
```

No relevant information from flutter analyze.

```
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.19045.2486], locale en-US)
    • Flutter version 3.7.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (7 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\me\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.75.0)
    • VS Code at C:\Users\me\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2486]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 109.0.1518.61

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Example:
![exception](https://user-images.githubusercontent.com/18548911/217617208-1b158d1b-b8b3-4bc3-88ea-66ec5de3d546.gif)

**Comment by danagbemava-nc** [comment]
Hi @nck974, I cannot reproduce the bug using the code you have shared above. See the recording below. 

From your logs, it looks like the issue is caused by the `Scaffold` in your `dashboard.dart` file. 

Kindly provide a complete minimal reproducible code sample so that we can investigate the issue. 

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/217741546-98032314-8c55-4dc0-9adf-15fbc5493d24.mp4
</details>

<details>
<summary>code sample used</summary>

```dart
import 'package:flutter/material.dart';

final useMaterial3 = ValueNotifier(true);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<bool>(
      valueListenable: useMaterial3,
      builder: (context, value, child) {
        return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            useMaterial3: value,
            colorSchemeSeed: Colors.blue,
          ),
          home: const MyHomePage(title: 'Test App'),
        );
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(),
      bottomNavigationBar: NavigationBar(
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          NavigationDestination(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
        onDestinationSelected: (index) {
          // if (index == 0) {
          //   Navigator.of(context).pushNamed('/');
          // } else if (index == 1) {
          //   Navigator.of(context).pushNamed(SettingsScreen.routeName);
          // }
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (BuildContext context) => const SettingsScreen()),
          );
        },
        elevation: 0.0,
        child: const Icon(Icons.add),
      ),
    );
  }
}

class SettingsScreen extends StatefulWidget {
  static var routeName = '/settings';

  const SettingsScreen({super.key});
  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  Future<void> _onDataExport() async {
    Future.delayed(const Duration(seconds: 3)).then(
      (value) => ScaffoldMessenger.of(context)
        ..hideCurrentSnackBar()
        ..showSnackBar(
          const SnackBar(
            behavior: SnackBarBehavior.floating,
            content: Text(
              'File saved to xxxxxxxx',
            ),
          ),
        ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Settings'),
      ),
      body: TextButton(
        child: const Text('Export all my data'),
        onPressed: () => _onDataExport(),
      ),
    );
  }
}
```
</details>

**Comment by nck974** [comment]
Thank you for your time @danagbemava-nc . Since you mentioned my `dashboard.dart`. I started debugging in that file to see if I could minimize the issue to the minimum until it appears.

In that widget I have a custom floating action button which is built with a stack of elements that in a circle to offer multiple select options.
```dart
  @override
  Widget build(BuildContext context) {
    return SizedBox.expand(
      child: Stack(
        alignment: Alignment.bottomRight,
        children: [
          _closeButton(),
          ..._buildExpandableFabButtons(),
          _openButton()
        ],
      ),
    );
  }
```
After simplifying the issue. I could see that I can reproduce the issue in the `SettingsScreen`. If I just leave the `SizedBox.expanded` with a child in the screen that accesses to the SettingsScreen.

So using you minimal example I think it should be reproducible with this ugly example:

```dart
import 'package:flutter/material.dart';

final useMaterial3 = ValueNotifier(true);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<bool>(
      valueListenable: useMaterial3,
      builder: (context, value, child) {
        return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            useMaterial3: value,
            colorSchemeSeed: Colors.blue,
          ),
          home: const MyHomePage(title: 'Test App'),
        );
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(),
      bottomNavigationBar: NavigationBar(
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          NavigationDestination(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
        onDestinationSelected: (index) {
          // if (index == 0) {
          //   Navigator.of(context).pushNamed('/');
          // } else if (index == 1) {
          //   Navigator.of(context).pushNamed(SettingsScreen.routeName);
          // }
        },
      ),
      floatingActionButton: SizedBox.expand(
         child; IconButton(
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (BuildContext context) => const SettingsScreen()),
          );
        },
        elevation: 0.0,
        icon: const Icon(Icons.add),
      ),)
    );
  }
}

class SettingsScreen extends StatefulWidget {
  static var routeName = '/settings';

  const SettingsScreen({super.key});
  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  Future<void> _onDataExport() async {
    Future.delayed(const Duration(seconds: 3)).then(
      (value) => ScaffoldMessenger.of(context)
        ..hideCurrentSnackBar()
        ..showSnackBar(
          const SnackBar(
            behavior: SnackBarBehavior.floating,
            content: Text(
              'File saved to xxxxxxxx',
            ),
          ),
        ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Settings'),
      ),
      body: TextButton(
        child: const Text('Export all my data'),
        onPressed: () => _onDataExport(),
      ),
    );
  }
}
```

If this is how it gets triggered. Then I don't understand why this is happening. I though the SnackBar belongs only to the screen where I'm triggering it because I'm giving the context of the scaffold. I don't understand how the previous screen from where I accessed to the new screen can have an effect.

**Comment by danagbemava-nc** [comment]
> I thought the SnackBar belongs only to the screen where I'm triggering it because I'm giving the context of the scaffold. I don't understand how the previous screen from where I accessed to the new screen can have an effect.

Hi @nck974, this isn't entirely accurate. Normally the `Snackbar` does appear where it is called but the `SnackBar` also needs to be able to survive past the lifetime of the page it was called in. So for instance, if you open a `SnackBar` and go to the previous page, you'll still see the `Snackbar` there. See the recording below (captured using  `SnackBarBehavior.fixed`)

https://user-images.githubusercontent.com/88313112/218020156-7a10a1ae-4b8f-42c3-ba5f-c7f5a28414e1.mov


See https://github.com/flutter/flutter/issues/84263#issuecomment-1098558446 for why you get this issue with `SnackBarBehavior.floating`. A small demonstration of how `SnackBarBehavior.floating` works interacts with the FAB. 

https://user-images.githubusercontent.com/88313112/218020506-9c325ea9-f153-466d-bce5-d94d417668df.mov


So in your case, with an unconstrained FAB, there isn't enough space for the snackbar to appear which is why the error is thrown. So it would appear that the error message is indeed correct which means this is working as expected. You'll need to constrain the height of your CustomFab so that there's space for the `SnackBar` to appear on that 

Does this help explain why it's behaving this way?
