### ISSUE TITLE
Crash caused by plugin due to destroyed FlutterView

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#12036]
No known steps to reproduce and unclear whether this actually affects users (since the Flutter app seems to be dead already).

The crash collector reported the following stack trace in logcat:

```
java.lang.AssertionError
    at io.flutter.view.FlutterView.assertAttached(FlutterView.java:537)
    at io.flutter.view.FlutterView$3.reply(FlutterView.java:679)
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
    at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$3.run(GoogleSignInPlugin.java:264)
```

**Comment by tvolkert** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/12037
