### ISSUE TITLE
Getting crash on Flutter upgrade to 3.7.2

### ISSUE THREAD

**Issue by RafiIzzatulRizquFaris** [flutter/flutter#120335]
Step to reproduce : Upgrade Flutter from 3.7.1 to 3.7.2

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color --no-version-check precache

## exception

PathNotFoundException: PathNotFoundException: Creation failed, path = '/Users/rafiizzatulrizqufaris/Documents/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework' (OS Error: No such file or directory, errno = 2)

```
#0      _Directory.createSync (dart:io/directory_impl.dart:129:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:434:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:433:12)
#5      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:916:19)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#8      PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:168:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.7.2, on macOS 13.1 22C65 darwin-arm64, locale en-ID)
    • Flutter version 3.7.2 on channel stable at /Users/rafiizzatulrizqufaris/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 32fb2f948e (12 hours ago), 2023-02-08 07:30:10 -0800
    • Engine revision f40b73f8a4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/rafiizzatulrizqufaris/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-18.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 18+36-2087)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • M2103K19PG (mobile) • tw7x8pofkbnzhihi • android-arm64  • Android 12 (API 31)
    • macOS (desktop)     • macos            • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@RafiIzzatulRizquFaris 
I am unable to replicate this error after trying the said command in 3.7.1 and then upgraded to 3.7.2 which resulted in no crash.

Do you consistently get the crash everytime you run the command ?
