### ISSUE TITLE
Exception with TextField when maxLines = null

### ISSUE THREAD

**Issue by amardeep** [flutter/flutter#12046]
I want a TextField with no limit on the number of lines. 

https://docs.flutter.io/flutter/material/TextField/maxLines.html suggests that maxLines should be set to null.
But that throws an exception.

To reproduce, add a TextField with maxlines=null, type any text, and then click/tap on the text. I see the following error when running on ios simulator on the following line:
```dart
return new CompositedTransformFollower(
      ...
          children: <Widget>[
            new Positioned(
              left: point.dx,
              top: point.dy,
              child: widget.selectionControls.buildHandle(
                context,
                type,
                widget.renderObject.size.height / widget.renderObject.maxLines,
      ...
    );
```
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building _TextSelectionHandleOverlay(dirty, state:
_TextSelectionHandleOverlayState#29ce3):
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      double./ (dart:core-patch/double.dart:39)
#3      _TextSelectionHandleOverlayState.build (package:flutter/src/widgets/text_selection.dart:512:49)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3628:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3538:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3439:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3518:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3656:22)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3513:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2685:12)
#12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4520:14)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2685:12)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3550:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:3439:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3518:5)
#18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3656:22)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3513:5)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2685:12)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3550:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:3439:5)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3518:5)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3656:22)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3513:5)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2685:12)
#29     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4312:32)
#30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4635:17)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2674:15)
#32     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2674:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3550:16)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:3439:5)
#36     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2260:33)
#37     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:530:20)
#38     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:194:5)
#39     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713:15)
#40     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649:9)
#41     _invoke (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:86)
#42     _drawFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:75)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
```
## Flutter Doctor

Paste the output of running `flutter doctor` here.

flutter doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel alpha)
    • Flutter at /Users/amardeep/soft/flutter
    • Framework revision 1c372c6803 (12 days ago), 2017-08-31 15:54:45 -0700
    • Engine revision f9e00a7c72
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/amardeep/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/amardeep/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • iPhone 6 • 0E6F51C9-C9EA-499C-83FB-7637FF9B1305 • ios • iOS 10.3 (simulator)

**Comment by gdomingues** [comment]
I'm facing the same issue here. In the meanwhile I just set a huge number of lines (20) in order to prevent this exception being thrown.

**Comment by gusmd** [comment]
Just stumbled upon this. @gdomingues suggestion does help with the exception, but has the side-effect of making the `TextField` height become that of `maxLines` lines of text even without any text.

**Comment by pcomans** [comment]
+1 this is blocking us as well.

**Comment by sethladd** [comment]
If you're blocked on this, or really want to see this fixed, please "thumbs up" this issue. That helps us easily sort bugs and requests. Thank you!

**Comment by eseidelGoogle** [comment]
@maryx mentioned today that this is blocking her app.

**Comment by Hixie** [comment]
cc @jason-simmons who said he would take a look
