### ISSUE TITLE
Existing l10n.yaml file is mandatory or null check assertion is thrown in AppLocalizations.of

### ISSUE THREAD

**Issue by rjduffsep** [flutter/flutter#120457]
## Steps to Reproduce
Following [the documentation](https://docs.flutter.dev/development/accessibility-and-localization/internationalization) to install internationalization and localization **except not adding** the `l10n.yaml` file results in a null check operator exception when localizations are attempted to be used to set a`MaterialApp.title` property. Otherwise sensible defaults allow translations to work in the rest of the app. None of the default properties (`arb-dir, template-arb-file, or output-localization-file`) of the example `l10n.yaml` seem to have anything to do with using a null check operator versus returning a nullable type.

1. Follow [guide here](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#setting-up) to create a new project (`flutter create test`) and add internationalization.
2. Follow [guide here](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages) to add localizations, but do *not* add a `l10n.yaml` file (Step 3).
3. Add `app_en.arb` localization file (Step 4) as described.
4. Run `flutter gen-l10n`
5. Modify `main.dart` as described by the guide.
6. Call `AppLocalizations.of` in MyHomePage, see `main.dart` code file below.
7. Run app and observe application runs with translated text.

8. Call `AppLocalizations.of` in `MaterialApp.title`, see `main.dart` code file below.
9. Run app and observe application hits an exception of "Null check operator used on a null value" in the `of` method of the `AppLocalizations` class:
```
static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}
```

10. Add the `l10n.yaml` as described in step 3 of the [localizations guide](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages).
11. Run `flutter gen-l10n`
12. Observe that null check operator has disappeared from the `app_localizations.dart` file.
```
static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
}
```

13. Run app and observe application runs without an exception.

**Expected results:** 
Without a `l10n.yaml file` the `AppLocalizations` class file generated should still return a nullable type not throw a null check operator exception. Or a **much stronger** warning should be placed in the documented steps that broken behavior might occur without this file.

**Actual results:**
Application shows red screen with yellow text of "Null check operator used on a null value"
Debug window shows:
```
Exception has occurred.
_CastError (Null check operator used on a null value)
```

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: AppLocalizations.of(context)?.helloWorld ?? '',  // BREAKS IF l10n.yaml FILE NOT PROVIDED
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'), // English
        Locale('es'), // Spanish
      ],
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            Text(AppLocalizations.of(context)?.helloWorld.toUpperCase() ?? ''),
      ),
      body: Center(
          child: Text(
              AppLocalizations.of(context)?.helloWorld.toLowerCase() ?? '')),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[  +21 ms]
           ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
           The following _CastError was thrown building MyApp(dirty):
           Null check operator used on a null value

           The relevant error-causing widget was:
             MyApp MyApp:file:///C:/Users/*********/Documents/workspace/test-flutter/test/lib/main.dart:6:16

           When the exception was thrown, this was the stack:
           #0      AppLocalizations.of (package:flutter_gen/gen_l10n/app_localizations.dart:67:73)
           #1      MyApp.build (package:test/main.dart:16:31)
           #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038:49)
           #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
           #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
           #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
           #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
           #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
           #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
           #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
           #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
           #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
           #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
           #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
           #14     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
           #15     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
           #19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
           (elided 3 frames from class _Timer and dart:async-patch)

           ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
flutter analyze
Analyzing test...                                                       

warning - The receiver can't be null, so the null-aware operator '?.' is unnecessary - lib\main.dart:16:42 - invalid_null_aware_operator
warning - The receiver can't be null, so the null-aware operator '?.' is unnecessary - lib\main.dart:40:46 - invalid_null_aware_operator
warning - The receiver can't be null, so the null-aware operator '?.' is unnecessary - lib\main.dart:44:43 - invalid_null_aware_operator

3 issues found. (ran in 1.3s)
```

```
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version
    10.0.22621.1105], locale en-US)
    • Flutter version 3.7.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (9 days ago), 2023-02-01 09:07:31
      -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @rjduffsep 
Although I do see the error upon following the steps you mentioned, but the error is triggered because the step 3 mentioned in the document (to create l10n.yaml) is missing. If we add the step and follow all the steps from the document, the feature / functionality works as expected.
Since the step 3 is not optional and is integral to make internationalization work properly as mentioned in the document, the error seems to be expected ? It would be just like following any other manual and if we miss out on any step, the following steps would not work. 
What do you think ?

**Comment by rjduffsep** [comment]
The main issue was that a coworker missed that step and the resulting behavior was very unusual and hard to debug since on the face of things, a configuration file that doesn't mention null checks operators shouldn't effect whether the code generates a null assertion operator or not. Ideally, code shouldn't ever throw an exception when dereferencing a null value unless as a programmer the code was wrong, as opposed to some configuration step (unless something like a compiler flag for unsafe / less strict checking).

I.E.
```
// Expected to throw
String? iShouldNotBeNull = 'test';
iShouldNotBeNull = null;
print(iShouldNotBeNull!);

// Not expected to throw
var somethingFromALibrary = ALibrary.getAValue;

print(somthingFromALibrary.toString()); // Throws based on if we are at a certain place in the runtime and if a configuration file is present or not
```

Is there a reason the null assertion is made when the configuration file is absent verses present with default values?

**Comment by darshankawar** [comment]
Thanks for the feedback @rjduffsep 
I think it would be fair to maybe show a proper message to know what exactly is missing instead of throwing `(Null check operator used on a null value)` error.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.3 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.8.0-12.0.pre.49, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.8.0-12.0.pre.49 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b08cc8be79 (74 minutes ago), 2023-02-13 22:36:26 -0500
    • Engine revision c4f51bc786
    • Dart version 3.0.0 (build 3.0.0-233.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>
