### ISSUE TITLE
Navigator.pop(context, true) fails

### ISSUE THREAD

**Issue by Alexays** [flutter/flutter#12047]
## Steps to Reproduce

- Push a named route
- Pop with `Navigator.pop(context, true)`

Same as #11411 

## Logs

```
[ERROR:lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 9709): type 'bool' is not a subtype of type 'Null' of 'result' where
E/flutter ( 9709):   bool is from dart:core
E/flutter ( 9709):   Null is from dart:core
E/flutter ( 9709): 
E/flutter ( 9709): #0      TransitionRoute&&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:342:17)
E/flutter ( 9709): #1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1175:15)
E/flutter ( 9709): #2      Navigator.pop (package:flutter/src/widgets/navigator.dart:595:34)
E/flutter ( 9709): #3      _TestScreenState._handleEmail (package:test/ui/screens/test_screen.dart:30:17)
E/flutter ( 9709): <asynchronous suspension>
E/flutter ( 9709): #4      _TestScreenState.build.<anonymous closure>.<anonymous closure> (package:test/ui/screens/test_screen.dart:65:29)
E/flutter ( 9709): #5      EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:382:14)
E/flutter ( 9709): #6      _TextInputClientHandler._handleTextInputInvocation (package:flutter/src/services/text_input.dart:306:36)
E/flutter ( 9709): <asynchronous suspension>
E/flutter ( 9709): #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:201:55)
E/flutter ( 9709): <asynchronous suspension>
E/flutter ( 9709): #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:174:54)
E/flutter ( 9709): #9      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
E/flutter ( 9709): <asynchronous suspension>
E/flutter ( 9709): #10     _invoke3 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:128)
E/flutter ( 9709): #11     _dispatchPlatformMessage (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:42)
I/flutter ( 9709): Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1329 pos 12: '!_debugLocked': is not true.
```

## Flutter Doctor

```[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/rouill_a/bin/flutter
    • Framework revision fd6b9c7943 (2 hours ago), 2017-09-12 13:29:16 +0200
    • Engine revision 2d7c30033d
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /opt/android-sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • E6553                     • CB5A278YZJ    • android-arm • Android 7.1.1 (API 25)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
```

**Comment by Hixie** [comment]
Weird, I wonder where the Null is coming from.

**Comment by Hixie** [comment]
wherever we're instantiating the route, we're using Null instead of `T` or `dynamic`.

**Comment by Alexays** [comment]
i investigated on it but found nothing :/

**Comment by Alexays** [comment]
Ok my bad, bug found, it was from fluro https://github.com/goposse/fluro/blob/master/lib/src/router.dart#L105
just replace Null to dynamic and all working now :) but i thinks i will make my own router generator with params support :)
