### ISSUE TITLE
Flutter application unable to compile for windows or Android

### ISSUE THREAD

**Issue by Twantie** [flutter/flutter#120585]
## Steps to Reproduce

1. Install Flutter as described on the "Get Started Section" of the official website
2. Create a new application
3. Select Windows as device
4. Hit F5 (VSCode) or run "flutter run" or use play button on top right

**Expected results:** 
Window appearing with the demo app

**Actual results:** 
With F5 the app just exits without giving any logs.
With flutter run (after selecting Windows) it throws the error 
```
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.
```
With the play button it throws the error
`../../../../../../flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Dart library 'dart:ui' is not available on this platform.`
and showing multiple instances where it couldnt import the dart:ui library.
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(
            seedColor: const Color.fromARGB(255, 51, 255, 0)),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Test Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +24 ms] executing: [C:\Users\Jonas\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +127 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 53fe8a3f942526cc711b78b4aa877bbcda8d2d7b
[        ] executing: [C:\Users\Jonas\flutter/] git tag --points-at 53fe8a3f942526cc711b78b4aa877bbcda8d2d7b
[ +118 ms] Exit code 0 from: git tag --points-at 53fe8a3f942526cc711b78b4aa877bbcda8d2d7b
[   +2 ms] executing: [C:\Users\Jonas\flutter/] git describe --match *.*.* --long --tags 53fe8a3f942526cc711b78b4aa877bbcda8d2d7b
[ +123 ms] Exit code 0 from: git describe --match *.*.* --long --tags 53fe8a3f942526cc711b78b4aa877bbcda8d2d7b
[        ] 3.8.0-9.0.pre-34-g53fe8a3f94
[  +17 ms] executing: [C:\Users\Jonas\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +96 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/master
[        ] executing: [C:\Users\Jonas\flutter/] git ls-remote --get-url origin
[  +96 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +116 ms] executing: [C:\Users\Jonas\flutter/] git rev-parse --abbrev-ref HEAD
[ +154 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +67 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +90 ms] executing: C:\Users\Jonas\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +121 ms] List of devices attached
[  +32 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +120 ms] Multiple devices found:
[ +102 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2486]
[   +1 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
[   +1 ms] Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.41
[   +8 ms] [1]: Windows (windows)
[   +4 ms] [2]: Chrome (chrome)
[   +2 ms] [3]: Edge (edge)
[   +3 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] : 
[+3070 ms] 1
[  +23 ms] Skipping pub get: version match.
[ +224 ms] Generating C:\Users\Jonas\OneDrive\Dokumente\Dev\flutter_demo\demo-project\demo_application_1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +135 ms] Initializing file store
[  +18 ms] Skipping target: gen_localizations
[  +14 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: C:\Users\Jonas\OneDrive\Dokumente\Dev\flutter_demo\demo-project\demo_application_1\.dart_tool\package_config_subset}
[  +57 ms] gen_dart_plugin_registrant: Complete
[   +3 ms] Skipping target: _composite
[   +2 ms] complete
[   +7 ms] Launching lib\main.dart on Windows in debug mode...
[   +4 ms] C:\Users\Jonas\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\Jonas\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\Users\Jonas\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\JONAS~1.PLA\AppData\Local\Temp\1\flutter_tools.585186b9\flutter_tool.e54a38da\app.dill --packages C:\Users\Jonas\OneDrive\Dokumente\Dev\flutter_demo\demo-project\demo_application_1\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --verbosity=error --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[  +55 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[ +158 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] [
             {
               "instanceId": "c4833165",
               "installDate": "2022-02-17T09:39:15Z",
               "installationName": "VisualStudio/17.1.0+32210.238",
               "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "installationVersion": "17.1.32210.238",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "Leistungsstarke IDE, kostenlos für Studenten, Open-Source-Mitwirkende und Einzelpersonen",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.1#17.1.0",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2022-02-17T09:39:15.1960396Z",
               "catalog": {
                 "buildBranch": "d17.1",
                 "buildVersion": "17.1.32210.238",
                 "id": "VisualStudio/17.1.0+32210.238",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.1.0",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "0",
                 "productPreReleaseMilestoneSuffix": "7.0",
                 "productSemanticVersion": "17.1.0+32210.238",
                 "requiredEngineVersion": "3.1.2196.8931"
               },
               "properties": {
                 "campaignId": "2030",
                 "channelManifestId": "VisualStudio.17.Release/17.1.0+32210.238",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +8 ms] Building Windows application...
[  +22 ms] <- compile package:demo_application_1/main.dart
[   +2 ms] executing: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S C:\Users\Jonas\OneDrive\Dokumente\Dev\flutter_demo\demo-project\demo_application_1\windows -B build\windows -G Visual Studio 17 2022
[ +342 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
[+5318 ms] -- The CXX compiler identification is unknown
[ +145 ms] CMake Error at CMakeLists.txt:3 (project):
[  +23 ms]   No CMAKE_CXX_COMPILER could be found.
[  +79 ms] -- Configuring incomplete, errors occurred!
[  +11 ms] See also "C:/Users/Jonas/OneDrive/Dokumente/Dev/flutter_demo/demo-project/demo_application_1/build/windows/CMakeFiles/CMakeOutput.log".
[  +21 ms] See also "C:/Users/Jonas/OneDrive/Dokumente/Dev/flutter_demo/demo-project/demo_application_1/build/windows/CMakeFiles/CMakeError.log".
[  +19 ms] Building Windows application... (completed in 6,0s)
[+8817 ms] Exception: Unable to generate build files
[   +2 ms] "flutter run" took 19.333ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:740:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1287:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +142 ms] ensureAnalyticsSent: 140ms
[        ] Running 1 shutdown hook
[   +7 ms] Shutdown hooks complete
[        ] exiting with code 1    
```

```
Analyzing demo_application_1...                                         
No issues found! (ran in 35.2s)
```

```
[√] Flutter (Channel master, 3.8.0-10.0.pre.34, on Microsoft Windows [Version 10.0.19045.2486], locale de-DE)
    • Flutter version 3.8.0-10.0.pre.34 on channel master at C:\Users\Jonas.Platzer\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 53fe8a3f94 (2 hours ago), 2023-02-13 02:37:24 -0500
    • Engine revision 4107a7b71f
    • Dart version 3.0.0 (build 3.0.0-231.0.dev)
    • DevTools version 2.21.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Jonas.Platzer\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe
    • Java version OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Users\Jonas.Platzer\Android\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\Jonas.Platzer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

I have ticked the CMake box in the SDK Tools manager.
I am also unable to create the app for a android device, but it works for chrome.

**Comment by Twantie** [comment]
Reinstalling Visual Studio and Android Studio resolved the issue.
