### ISSUE TITLE
Overlay widget ancestor cannot befound although it is in the tree (since version 3.7)

### ISSUE THREAD

**Issue by Spitzbua** [flutter/flutter#120591]
## Steps to Reproduce

Since Flutter Version 3.7 the Overlay widget ancestor cannot be found although it is there. 

1. Run example https://pub.dev/packages/showcaseview/example
2. Open view where overlay will be used
3. Exception in output

The error message states that for example a MaterialApp should be used in tree which is the case.

**Expected results:** 
A overlay should be visible.

**Actual results:** 
Exception will be thrown and no overlay is visible

<details>
<summary>Code sample</summary>

```dart
https://pub.dev/packages/showcaseview/example
```

</details>

<details>
  <summary>Logs</summary>

```
E/flutter (32324): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: No Overlay widget found.
E/flutter (32324): Some widgets require an Overlay widget ancestor for correct operation.
E/flutter (32324): The most common way to add an Overlay to an application is to include a MaterialApp, CupertinoApp or Navigator widget in the runApp() call.
E/flutter (32324): The context from which that widget was searching for an overlay was:
E/flutter (32324):   ShowCaseWidget
E/flutter (32324): #0      Overlay.of.<anonymous closure>
package:flutter/…/widgets/overlay.dart:384
E/flutter (32324): #1      Overlay.of
package:flutter/…/widgets/overlay.dart:387
E/flutter (32324): #2      _OverlayBuilderState.addToOverlay
package:showcaseview/src/layout_overlays.dart:174
E/flutter (32324): #3      _OverlayBuilderState.showOverlay
package:showcaseview/src/layout_overlays.dart:164
E/flutter (32324): #4      _OverlayBuilderState.initState.<anonymous closure>
package:showcaseview/src/layout_overlays.dart:129
E/flutter (32324): #5      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1289
E/flutter (32324): #6      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1227
E/flutter (32324): #7      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1076
E/flutter (32324): #8      _invoke (dart:ui/hooks.dart:145:13)
E/flutter (32324): #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
E/flutter (32324): #10     _drawFrame (dart:ui/hooks.dart:112:31)
E/flutter (32324):
E/flutter (32324): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: No Overlay widget found.
E/flutter (32324): Some widgets require an Overlay widget ancestor for correct operation.
E/flutter (32324): The most common way to add an Overlay to an application is to include a MaterialApp, CupertinoApp or Navigator widget in the runApp() call.
E/flutter (32324): The context from which that widget was searching for an overlay was:
E/flutter (32324):   ShowCaseWidget
E/flutter (32324): #0      Overlay.of.<anonymous closure>
package:flutter/…/widgets/overlay.dart:384
E/flutter (32324): #1      Overlay.of
package:flutter/…/widgets/overlay.dart:387
E/flutter (32324): #2      _OverlayBuilderState.addToOverlay
package:showcaseview/src/layout_overlays.dart:174
E/flutter (32324): #3      _OverlayBuilderState.showOverlay
package:showcaseview/src/layout_overlays.dart:164
E/flutter (32324): #4      _OverlayBuilderState.initState.<anonymous closure>
package:showcaseview/src/layout_overlays.dart:129
E/flutter (32324): #5      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1289
E/flutter (32324): #6      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1227
E/flutter (32324): #7      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1076
E/flutter (32324): #8      _invoke (dart:ui/hooks.dart:145:13)
E/flutter (32324): #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
E/flutter (32324): #10     _drawFrame (dart:ui/hooks.dart:112:31)
E/flutter (32324):
```

```
0 issues found. (ran in 3.3s)
```

```
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1105], locale de-AT)
    • Flutter version 3.7.3 on channel stable at D:\Development\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\thoma\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Java\jdk-18\bin\java
    • Java version Java(TM) SE Runtime Environment (build 18+36-2087)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 202.8346

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by exaby73** [comment]
Hey @Spitzbua. Can you provide a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn't use any 3rd party libraries?

**Comment by isafiulin** [comment]
Hi all. It's not flutter problem(maybe..) I refactorted code of the 3rd pary plugin and resolve the same problem

new code without problem:
```
  Future<void> addToOverlay(OverlayEntry overlayEntry) async {
    if (mounted) {
      if (ShowCaseWidget.of(context)?.context != null) {
        final overlay = Overlay.of(context);
        WidgetsBinding.instance
            .addPostFrameCallback((_) => overlay.insert(overlayEntry));

      } else {
        final overlay = Overlay.of(context);
        WidgetsBinding.instance
            .addPostFrameCallback((_) => overlay.insert(overlayEntry));
      }
    }
  }
```


not working code

`  void addToOverlay(OverlayEntry overlayEntry) async {
    final showCaseContext = ShowCaseWidget.of(context).context;
    if (mounted) {
      if (Overlay.of(showCaseContext) != null) {
        Overlay.of(showCaseContext)!.insert(overlayEntry);
      } else {
        if (Overlay.of(context) != null) {
          Overlay.of(context)!.insert(overlayEntry);
        }
      }
    }
  }`

**Comment by Spitzbua** [comment]
@exaby73, thank you for your answer. Actually I have tried to create a complete and minimal, reproducible code sample but in that case it is not really simple. My codebase is quite big and to extract only that code that is problematic is not possible because it is actually a combination of the new flutter version, go router and the showcase plugin. 

It's a fact that the same codebase is working with 3.3.10 and is not working with 3.7 and above. The behaviour that changed is the search for an Overlay widget in the context. 

```
final showCaseContext = ShowCaseWidget.of(context).context;
Overlay.of(showCaseContext)
```

Using version 3.3.10 the call succeeded. Using version 3.7 ends in following exception.

```
E/flutter (23237): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: No Overlay widget found.
E/flutter (23237): Some widgets require an Overlay widget ancestor for correct operation.
E/flutter (23237): The most common way to add an Overlay to an application is to include a MaterialApp, CupertinoApp or Navigator widget in the runApp() call.
E/flutter (23237): The context from which that widget was searching for an overlay was:
E/flutter (23237):   ShowCaseWidget
```

**Comment by Spitzbua** [comment]
It seems the mystery is solved. Starting with version 3.7, the call
`Overlay.of(context)`
throws a hard error which no longer allows the condition check
` if (Overlay.of(context) != null)`

I guess the solution is to use the maybeOf method which throws an error. 
`if (Overlay.maybeOf(context) != null)`

**Comment by exaby73** [comment]
This looks like an issue in the package you're using. I suggest you raise an issue with the package author
