### ISSUE TITLE
An error when running: flutter doctor --android-licenses

### ISSUE THREAD

**Issue by Tangzheng-Dev-GitHub** [flutter/flutter#120515]
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:669)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:651)
# this happened when I was running 
```
$ flutter doctor --android-licenses
```
# please tell me the answer

**Comment by samithe7** [comment]
follow this https://github.com/flutter/flutter/issues/120564

**Comment by huycozy** [comment]
@Tangzheng-Dev-GitHub Please check answers in this [issue](https://github.com/flutter/flutter/issues/120388) to see if they can help for your case. Also, you can check [this SO](https://stackoverflow.com/questions/75328050/flutter-doctor-android-licenses-not-working-due-to-java-lang-unsupportedclassv) for another solutions.

**Comment by Tangzheng-Dev-GitHub** [comment]
> @Tangzheng-Dev-GitHub Please check answers in this [issue](https://github.com/flutter/flutter/issues/120388) to see if they can help for your case. Also, you can check [this SO](https://stackoverflow.com/questions/75328050/flutter-doctor-android-licenses-not-working-due-to-java-lang-unsupportedclassv) for another solutions.

thank you

**Comment by huycozy** [comment]
@Tangzheng-Dev-GitHub Once the issue is solved, please confirm it or feel free to close the issue. Thank you!
