### ISSUE TITLE
Unable to Install flutter extension on VScode

### ISSUE THREAD

**Issue by xclusiveskate** [flutter/flutter#120685]
this is the error log from my vscode

```
2023-02-14 05:32:00.074 [info] Electron sandbox mode is enabled!
2023-02-14 05:32:00.110 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-02-14 05:32:01.757 [error] Extension 'github.copilot' wants API proposal 'inlineCompletionsNew' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-02-14 05:32:01.758 [error] Extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-02-14 05:32:01.812 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.quick_fixes'. This property is already registered.
2023-02-14 05:32:01.813 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.fromMap.default_values'. This property is already registered.
2023-02-14 05:32:01.813 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.constructor.default_values'. This property is already registered.
2023-02-14 05:32:01.813 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.constructor.required'. This property is already registered.
2023-02-14 05:32:01.814 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.override.manual'. This property is already registered.
2023-02-14 05:32:01.814 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.json.seperate'. This property is already registered.
2023-02-14 05:32:01.815 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.constructor.enabled'. This property is already registered.
2023-02-14 05:32:01.815 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.copyWith.enabled'. This property is already registered.
2023-02-14 05:32:01.816 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.toMap.enabled'. This property is already registered.
2023-02-14 05:32:01.816 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.fromMap.enabled'. This property is already registered.
2023-02-14 05:32:01.817 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.toJson.enabled'. This property is already registered.
2023-02-14 05:32:01.817 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.fromJson.enabled'. This property is already registered.
2023-02-14 05:32:01.817 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.toString.enabled'. This property is already registered.
2023-02-14 05:32:01.818 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.equality.enabled'. This property is already registered.
2023-02-14 05:32:01.818 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.hashCode.enabled'. This property is already registered.
2023-02-14 05:32:01.818 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.hashCode.use_jenkins'. This property is already registered.
2023-02-14 05:32:01.819 [warning] [hzgood.dart-data-class-generator]: Cannot register 'dart_data_class_generator.useEquatable'. This property is already registered.
2023-02-14 05:32:01.819 [warning] [passionkind.prettier-vscode-with-tabs]: Cannot register 'prettier.printWidth'. This property is already registered.
2023-02-14 05:32:01.820 [warning] [passionkind.prettier-vscode-with-tabs]: Cannot register 'prettier.tabWidth'. This property is already registered.
2023-02-14 05:32:01.821 [warning] [passionkind.prettier-vscode-with-tabs]: Cannot register 'prettier.singleQuote'. This property is already registered.
2023-02-14 05:32:01.821 [warning] [passionkind.prettier-vscode-with-tabs]: Cannot register 'prettier.trailingComma'. This property is already registered.
2023-02-14 05:32:01.821 [warning] [passionkind.prettier-vscode-with-tabs]: Cannot register 'prettier.bracketSpacing'. This property is already registered.
2023-02-14 05:32:01.822 [warning] [passionkind.prettier-vscode-with-tabs]: Cannot register 'prettier.jsxBracketSameLine'. This property is already registered.
2023-02-14 05:32:01.822 [warning] [passionkind.prettier-vscode-with-tabs]: Cannot register 'prettier.useTabs'. This property is already registered.
2023-02-14 05:32:01.824 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.printWidth'. This property is already registered.
2023-02-14 05:32:01.824 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.tabWidth'. This property is already registered.
2023-02-14 05:32:01.825 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.useTabs'. This property is already registered.
2023-02-14 05:32:01.826 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.singleQuote'. This property is already registered.
2023-02-14 05:32:01.826 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.jsxSingleQuote'. This property is already registered.
2023-02-14 05:32:01.827 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.trailingComma'. This property is already registered.
2023-02-14 05:32:01.827 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.bracketSpacing'. This property is already registered.
2023-02-14 05:32:01.827 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.arrowParens'. This property is already registered.
2023-02-14 05:32:01.828 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.jsxBracketSameLine'. This property is already registered.
2023-02-14 05:32:01.828 [warning] [remimarsal.prettier-now]: Cannot register 'prettier.semi'. This property is already registered.
2023-02-14 05:32:01.831 [warning] [steoates.autoimport]: Cannot register 'autoimport.filesToScan'. This property is already registered.
2023-02-14 05:32:01.831 [warning] [steoates.autoimport]: Cannot register 'autoimport.showNotifications'. This property is already registered.
2023-02-14 05:32:01.831 [warning] [steoates.autoimport]: Cannot register 'autoimport.doubleQuotes'. This property is already registered.
2023-02-14 05:32:01.832 [warning] [steoates.autoimport]: Cannot register 'autoimport.spaceBetweenBraces'. This property is already registered.
2023-02-14 05:32:01.832 [warning] [steoates.autoimport]: Cannot register 'autoimport.autoComplete'. This property is already registered.
2023-02-14 05:32:01.833 [warning] [steoates.autoimport]: Cannot register 'autoimport.useSemiColon'. This property is already registered.
2023-02-14 05:32:01.834 [warning] [svipas.prettier-plus]: Cannot register 'prettier.disableLanguages'. This property is already registered.
2023-02-14 05:32:01.835 [warning] [svipas.prettier-plus]: Cannot register 'prettier.requireConfig'. This property is already registered.
2023-02-14 05:32:01.835 [warning] [svipas.prettier-plus]: Cannot register 'prettier.ignorePath'. This property is already registered.
2023-02-14 05:32:01.836 [warning] [svipas.prettier-plus]: Cannot register 'prettier.printWidth'. This property is already registered.
2023-02-14 05:32:01.836 [warning] [svipas.prettier-plus]: Cannot register 'prettier.tabWidth'. This property is already registered.
2023-02-14 05:32:01.836 [warning] [svipas.prettier-plus]: Cannot register 'prettier.singleQuote'. This property is already registered.
2023-02-14 05:32:01.837 [warning] [svipas.prettier-plus]: Cannot register 'prettier.trailingComma'. This property is already registered.
2023-02-14 05:32:01.837 [warning] [svipas.prettier-plus]: Cannot register 'prettier.bracketSpacing'. This property is already registered.
2023-02-14 05:32:01.837 [warning] [svipas.prettier-plus]: Cannot register 'prettier.jsxBracketSameLine'. This property is already registered.
2023-02-14 05:32:01.838 [warning] [svipas.prettier-plus]: Cannot register 'prettier.parser'. This property is already registered.
2023-02-14 05:32:01.838 [warning] [svipas.prettier-plus]: Cannot register 'prettier.semi'. This property is already registered.
2023-02-14 05:32:01.839 [warning] [svipas.prettier-plus]: Cannot register 'prettier.useTabs'. This property is already registered.
2023-02-14 05:32:01.839 [warning] [svipas.prettier-plus]: Cannot register 'prettier.proseWrap'. This property is already registered.
2023-02-14 05:32:01.839 [warning] [svipas.prettier-plus]: Cannot register 'prettier.arrowParens'. This property is already registered.
2023-02-14 05:32:01.840 [warning] [svipas.prettier-plus]: Cannot register 'prettier.jsxSingleQuote'. This property is already registered.
2023-02-14 05:32:01.840 [warning] [svipas.prettier-plus]: Cannot register 'prettier.htmlWhitespaceSensitivity'. This property is already registered.
2023-02-14 05:32:01.840 [warning] [svipas.prettier-plus]: Cannot register 'prettier.vueIndentScriptAndStyle'. This property is already registered.
2023-02-14 05:32:01.841 [warning] [svipas.prettier-plus]: Cannot register 'prettier.endOfLine'. This property is already registered.
2023-02-14 05:32:01.841 [warning] [svipas.prettier-plus]: Cannot register 'prettier.quoteProps'. This property is already registered.
2023-02-14 05:32:01.843 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.dontShowNewVersionMessage'. This property is already registered.
2023-02-14 05:32:01.843 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.dontShowConfigManuallyChangedMessage'. This property is already registered.
2023-02-14 05:32:01.843 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.projectDetection.autoReload'. This property is already registered.
2023-02-14 05:32:01.844 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.projectDetection.disableDetect'. This property is already registered.
2023-02-14 05:32:01.844 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.presets.angular'. This property is already registered.
2023-02-14 05:32:01.845 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.presets.jsOfficial'. This property is already registered.
2023-02-14 05:32:01.845 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.presets.tsOfficial'. This property is already registered.
2023-02-14 05:32:01.845 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.presets.jsonOfficial'. This property is already registered.
2023-02-14 05:32:01.846 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.presets.hideFolders'. This property is already registered.
2023-02-14 05:32:01.846 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.presets.foldersAllDefaultIcon'. This property is already registered.
2023-02-14 05:32:01.846 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.presets.hideExplorerArrows'. This property is already registered.
2023-02-14 05:32:01.847 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.customIconFolderPath'. This property is already registered.
2023-02-14 05:32:01.847 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.associations.files'. This property is already registered.
2023-02-14 05:32:01.848 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.associations.folders'. This property is already registered.
2023-02-14 05:32:01.848 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.associations.fileDefault.file'. This property is already registered.
2023-02-14 05:32:01.848 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.associations.fileDefault.file_light'. This property is already registered.
2023-02-14 05:32:01.849 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.associations.folderDefault.folder'. This property is already registered.
2023-02-14 05:32:01.849 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.associations.folderDefault.root_folder'. This property is already registered.
2023-02-14 05:32:01.849 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.associations.folderDefault.folder_light'. This property is already registered.
2023-02-14 05:32:01.850 [warning] [wayou.vscode-icons-mac]: Cannot register 'vsicons.associations.folderDefault.root_folder_light'. This property is already registered.
2023-02-14 05:32:01.950 [info] [eamodio.gitlens]: Command `gitlens.copyAutolinkUrl` appears multiple times in the `commands` section.
2023-02-14 05:32:01.954 [info] [hzgood.dart-data-class-generator]: Command `dart_data_class.generate.from_props` appears multiple times in the `commands` section.
2023-02-14 05:32:01.955 [info] [hzgood.dart-data-class-generator]: Command `dart_data_class.generate.from_json` appears multiple times in the `commands` section.
2023-02-14 05:32:05.177 [info] [perf] Render performance baseline is 292ms
2023-02-14 05:32:08.500 [error] [Extension Host] Failed to load message bundle for file c:\Users\Owner\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.1\out\extension
2023-02-14 05:32:08.502 [error] [Extension Host] Failed to load message bundle for file c:\Users\Owner\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.1\out\extension
2023-02-14 05:32:08.504 [error] [Extension Host] Failed to load message bundle for file c:\Users\Owner\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.1\out\extension
2023-02-14 05:32:08.505 [error] [Extension Host] Failed to load message bundle for file c:\Users\Owner\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.1\out\extension
2023-02-14 05:32:08.507 [error] [Extension Host] Failed to load message bundle for file c:\Users\Owner\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.1\out\extension
2023-02-14 05:32:08.507 [error] [Extension Host] Failed to load message bundle for file c:\Users\Owner\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.1\out\extension
2023-02-14 05:32:08.509 [error] [Extension Host] Failed to load message bundle for file c:\Users\Owner\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.1\out\extension
2023-02-14 05:32:08.510 [error] [Extension Host] Failed to load message bundle for file c:\Users\Owner\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.1\out\extension
2023-02-14 05:32:17.531 [error] [Extension Host] [ERROR] [default] [2023-02-14T13:32:17.526Z] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"
2023-02-14 05:33:04.533 [error] XHR failed: Error: XHR failed
    at I.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:77412)
2023-02-14 05:33:39.924 [error] XHR failed: Error: XHR failed
    at I.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:77412)
2023-02-14 05:33:50.715 [error] RequestService#request (browser) - error https://dzhavat.gallerycdn.vsassets.io/extensions/dzhavat/bracket-pair-toggler/0.0.3/1675812133561/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:33:58.045 [error] XHR failed: Error: XHR failed
    at I.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:77412)
2023-02-14 05:33:59.273 [error] XHR failed: Error: XHR failed
    at I.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:77412)
2023-02-14 05:34:00.214 [error] RequestService#request (browser) - error https://github.gallerycdn.vsassets.io/extensions/github/copilot/1.73.8685/1676307844358/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:34:00.786 [error] XHR failed: Error: XHR failed
    at I.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:77412)
2023-02-14 05:34:03.461 [error] XHR failed: Error: XHR failed
    at I.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:16:77412)
2023-02-14 05:34:09.814 [error] RequestService#request (browser) - error https://dzhavat.gallerycdn.vsassets.io/extensions/dzhavat/bracket-pair-toggler/0.0.3/1675812133561/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:34:21.611 [error] RequestService#request (browser) - error https://dzhavat.gallery.vsassets.io/_apis/public/gallery/publisher/dzhavat/extension/bracket-pair-toggler/0.0.3/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:34:21.611 [error] Error: XHR timeout: undefinedms
    at v.ontimeout (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1644)
2023-02-14 05:34:57.092 [error] RequestService#request (browser) - error https://github.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.73.8685/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:34:57.126 [error] Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
2023-02-14 05:35:03.473 [error] RequestService#request (browser) - error https://dzhavat.gallery.vsassets.io/_apis/public/gallery/publisher/dzhavat/extension/bracket-pair-toggler/0.0.3/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:35:03.502 [error] Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
2023-02-14 05:35:08.777 [error] RequestService#request (browser) - error https://dart-code.gallerycdn.vsassets.io/extensions/dart-code/flutter/3.58.0/1674641343189/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:35:11.090 [error] RequestService#request (browser) - error https://dart-code.gallerycdn.vsassets.io/extensions/dart-code/flutter/3.58.0/1674641343189/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:35:13.628 [error] RequestService#request (browser) - error https://dart-code.gallerycdn.vsassets.io/extensions/dart-code/flutter/3.58.0/1674641343189/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:35:28.601 [error] RequestService#request (browser) - error https://dart-code.gallerycdn.vsassets.io/extensions/dart-code/dart-code/3.58.0/1674641223313/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:35:28.743 [error] RequestService#request (browser) - error https://dart-code.gallerycdn.vsassets.io/extensions/dart-code/dart-code/3.58.0/1674641223313/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:35:29.892 [error] RequestService#request (browser) - error https://dart-code.gallerycdn.vsassets.io/extensions/dart-code/dart-code/3.58.0/1674641223313/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:35:41.818 [error] RequestService#request (browser) - error https://dart-code.gallery.vsassets.io/_apis/public/gallery/publisher/Dart-Code/extension/flutter/3.58.0/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:35:41.852 [error] Error: XHR timeout: undefinedms
    at v.ontimeout (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1644)
2023-02-14 05:36:02.766 [error] RequestService#request (browser) - error https://dart-code.gallery.vsassets.io/_apis/public/gallery/publisher/Dart-Code/extension/flutter/3.58.0/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:36:02.780 [error] Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
2023-02-14 05:36:02.818 [error] XHR failed: Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
2023-02-14 05:36:10.015 [error] RequestService#request (browser) - error https://dart-code.gallery.vsassets.io/_apis/public/gallery/publisher/Dart-Code/extension/flutter/3.58.0/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:36:10.015 [error] XHR failed: Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
2023-02-14 05:36:24.423 [error] RequestService#request (browser) - error https://dart-code.gallery.vsassets.io/_apis/public/gallery/publisher/Dart-Code/extension/dart-code/3.58.0/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:36:24.423 [error] Error: XHR timeout: undefinedms
    at v.ontimeout (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1644)
2023-02-14 05:36:26.119 [error] RequestService#request (browser) - error https://dart-code.gallery.vsassets.io/_apis/public/gallery/publisher/Dart-Code/extension/dart-code/3.58.0/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:36:26.132 [error] Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
2023-02-14 05:36:26.163 [error] XHR failed: Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
2023-02-14 05:36:27.487 [error] RequestService#request (browser) - error https://dart-code.gallery.vsassets.io/_apis/public/gallery/publisher/Dart-Code/extension/dart-code/3.58.0/assetbyname/Microsoft.VisualStudio.Code.Manifest {}
2023-02-14 05:36:27.488 [error] XHR timeout: undefinedms: Error: XHR timeout: undefinedms
    at v.ontimeout (vscode-file://vscode-app/c:/Users/Owner/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1644)
```

**Comment by darshankawar** [comment]
@xclusiveskate 
I think this issue belongs to VSCode plugin tracker, so please file this in dedicated repo: https://github.com/Dart-Code/Dart-Code/issues

Closing from here.
