### ISSUE TITLE
flutter create error - Image File not found

### ISSUE THREAD

**Issue by d3im** [flutter/flutter#120674]
## Steps to Reproduce

flutter create -v test

## Logs

<details>

```
flutter create -v test
[  +14 ms] executing: uname -m
[   +7 ms] Exit code 0 from: uname -m
[        ] x86_64
[        ] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9944297138845a94256f1cf37beb88ff9a8e811a
[        ] executing: [/opt/flutter/] git tag --points-at 9944297138845a94256f1cf37beb88ff9a8e811a
[   +8 ms] Exit code 0 from: git tag --points-at 9944297138845a94256f1cf37beb88ff9a8e811a
[        ] 3.7.3
[   +7 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +1 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +18 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +12 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +58 ms] Creating project test...
[  +88 ms] "flutter create" took 192ms.
[   +2 ms] Image File not found [projects folder]/test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:315:11)
           #2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
           #3      Template.render (package:flutter_tools/src/template.dart:248:24)
           #4      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:489:21)
           <asynchronous suspension>
           #5      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:512:23)
           <asynchronous suspension>
           #6      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:351:31)
           <asynchronous suspension>
           #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1


```

<summary>
command output
</summary>
</details>

```

[✓] Flutter (Channel stable, 3.7.3, on Gentoo Linux 6.1.9-gentoo-systemd, locale cs_CZ.UTF-8)
    • Flutter version 3.7.3 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (5 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /mnt/HDD4/FREE/android/android
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /mnt/HDD4/FREE/android/android
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.25.2
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Gentoo Linux 6.1.9-gentoo-systemd

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

**Comment by d3im** [comment]
if I create over and over it adds empty pictures - one each command - until it finally finishes creation of project

**Comment by huycozy** [comment]
@d3im I'm checking this on my Linux (Ubuntu distro) but don't see this issue. Does it always happen when creating a new project?

>if I create over and over it adds empty pictures - one each command - until it finally finishes creation of project

Do you mean you create the project (with the same name) repeatedly?

Can you also try switching to master channel and check if the issue still persists or not?
```
flutter channel master
flutter upgrade
```

**Comment by d3im** [comment]
Hi, thanks for reply, seem solved - after upgrade there somehow persisted older:
`packages/flutter_tools/.dart_tool/package_config.json`
After clean reinstall it seem working.
