### ISSUE TITLE
[iOS] - Dictation deltas don't respect app-side content updates

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#120724]
On iOS, when using dictation, the IME deltas that are dispatched to apps are delivered in a way that causes the app to get out of sync with the dictation system.

I've described the issue as it presents in Super Editor: https://github.com/superlistapp/super_editor/issues/1005

The summary of the issue is: The dictation system sends us one delta at a time, but the dictation system has already assembled multiple deltas that depend on each other. In cases where multiple deltas relate to each other, we're supposed to get the whole set of deltas at once. Instead, we get the deltas one at a time, which is supposed to let us immediately send our own app-side updates to the IME to alter the content (if we choose to) before the next delta comes in. But the next delta that comes in is based on the content of the first delta, which is now out of date.

Flutter version:
```
Flutter 3.8.0-12.0.pre.57 • channel master • https://github.com/flutter/flutter.git
Framework • revision 480c54c370 (82 minutes ago) • 2023-02-14 13:18:12 -0800
Engine • revision f4fcb911be
Tools • Dart 3.0.0 (build 3.0.0-233.0.dev) • DevTools 2.21.1
```

**Comment by matthew-carroll** [comment]
@justinmc @Renzo-Olivares - Can you please check the IME implementation for iOS and see whether this issue sits inside the dictation system, or whether it's how Flutter chooses to batch and submit deltas?

I'm hoping it's something that Flutter is doing, and that you can quickly and easily batch the deltas the way they should be.

**Comment by darshankawar** [comment]
I tried to verify and possibly replicate this reported behavior based on the details provided in [this](https://github.com/superlistapp/super_editor/issues/1005) issue and running the super_editor on iOS physical device but was unable to replicate it.  I tried below scenarios:

1.  Use microphone and speak that will go to next line.
2. Speak again that will go to next line.
3. Stop microphone which didn't remove the text entered in step 2 above.
4. Also tried to type-in using keyboard that will go to next line.
5. Use microphone which didn't remove the text entered in step 4.

<img width="347" alt="Screenshot 2023-02-15 at 3 04 25 PM" src="https://user-images.githubusercontent.com/67046386/218989422-3b894e88-6df7-445b-a7f0-fc6641960784.png">


I also tried using below simple `TextField` with multi-line enabled and repeated above steps which didn't replicate the behavior.

<img width="347" alt="Screenshot 2023-02-15 at 3 04 51 PM" src="https://user-images.githubusercontent.com/67046386/218989532-488ea302-a4e8-44fe-b14d-10f033f405b3.png">


I am not sure if above scenarios would properly help to replicate the reported behavior in attached issue, but based on the report, I am going ahead and labeling it for team's attention and insights.

**Comment by matthew-carroll** [comment]
Can you also try contractions on a line after the first line? For example: I'm, you're, we're, they're, etc.

**Comment by matthew-carroll** [comment]
On Super Editor we're now getting reports of many Samsung device errors and I'm concerned that it might be this same problem: https://github.com/superlistapp/super_editor/issues/1039

@justinmc can you have someone try to root cause this? If the Samsung problem is the same issue, then this is now a serious issue for Super Editor. Our clients are getting a lot of crash reports because the IME deltas seem to be out of sync with our app-side representation.

**Comment by Renzo-Olivares** [comment]
Hi @matthew-carroll i'll take a look at this and see if this issue is on the framework side or the iOS TextInputPlugin.

**Comment by matthew-carroll** [comment]
@Renzo-Olivares I think a big part of this question is what the Flutter contract is supposed to be. 

Putting aside Super Editor and dictation for a moment, it has historically always been the case with deltas that when a list of deltas arrive, those deltas are a batch, or transaction, and they are referentially separate from deltas that follow.

Perhaps this was incidental, rather than intentional. You'll have to tell me. But that was the case, and that was an important detail in the ability to implement the application of deltas to a structure that's more complex than a `TextEditingValue`.

Therefore, first, Flutter should decide, based on clear evidence from how multiple platforms send events, whether the concept of a transaction can be upheld, or not. What you're describing about iOS dictation sounds like it probably can't work in a world of delta transactions. But you should make absolutely sure of that before losing the power of transactions. You should also check Android dictation and see if you get any different results.

If delta transactions cannot be enforced, then it's important that Flutter demonstrate how deltas can be processed and applied for data structures other than `TextEditingValue`s. If there are no transactions, then when, exactly, is an app permitted to inject its own adjustment to content? We know we can't inject our own changed between deltas in a single list of deltas, but now we can't inject changes between notifications of deltas? This seems to indicate that there's no dependable time or place for an app to alter the IME content. Clearly, that's a problem.

> On the Flutter side we see the entire replacement of the dictation value and try to break it up as best as possible

Why are you altering what the platform IME is sending to Flutter? If the real IME is asking for a full replacement, then why not forward that replacement message to the app? I'm not sure why Flutter should have any influence on what's reported.

> Finally when pressing the microphone to turn dictation off

Does iOS notify the client when dictation starts and stops? If so, is Flutter forwarding this information? If not, Flutter certainly should. Because if this problem is unique to dictation, then we may be able to create an alternate code path to deal with this specifically.

**Comment by Renzo-Olivares** [comment]
> Putting aside Super Editor and dictation for a moment, it has historically always been the case with deltas that when a list of deltas arrive, those deltas are a batch, or transaction, and they are referentially separate from deltas that follow.

I'm not sure I completely understand what you mean by this. Do you mean that given delta batches A, B, C, that C should be able to be applied without first applying A?

> If delta transactions cannot be enforced, then it's important that Flutter demonstrate how deltas can be processed and applied for data structures other than TextEditingValues. If there are no transactions, then when, exactly, is an app permitted to inject its own adjustment to content? We know we can't inject our own changed between deltas in a single list of deltas, but now we can't inject changes between notifications of deltas? This seems to indicate that there's no dependable time or place for an app to alter the IME content. Clearly, that's a problem.

I agree that its not clear when a TextInputClient implementer can inject their own changes into the editing state, and I need to give it some more thought before giving a concrete answer.

> Why are you altering what the platform IME is sending to Flutter? If the real IME is asking for a full replacement, then why not forward that replacement message to the app? I'm not sure why Flutter should have any influence on what's reported.

iirc the decision for this was because on Android it was observed that the composing region was always active resulting in constant `replacements` instead of an `insertion` or `deletion`. I think some context for this decision can be found here https://github.com/flutter/engine/pull/28175#discussion_r698937876 . I don't believe that this abstraction of information is causing any issue with regards to this problem, is there cases where you think this might cause an issue?

> Does iOS notify the client when dictation starts and stops? If so, is Flutter forwarding this information? If not, Flutter certainly should. Because if this problem is unique to dictation, then we may be able to create an alternate code path to deal with this specifically.

It looks like apple provides an API to determine when the dictation ends https://developer.apple.com/documentation/uikit/uitextinput/1614507-dictationrecordingdidend, but i'm not seeing the same for when a dictation starts. I think we might be able to leverage [`currentInputModeDidChangeNotification`](https://developer.apple.com/documentation/uikit/uitextinputmode/1614517-currentinputmodedidchangenotific) and [`activeInputModes`](https://developer.apple.com/documentation/uikit/uitextinputmode/1614522-activeinputmodes) to determine this, but I will investigate that further and see if its feasible.

**Comment by matthew-carroll** [comment]
> I'm not sure I completely understand what you mean by this. Do you mean that given delta batches A, B, C, that C should be able to be applied without first applying A?

No. What I mean is that an editor should be able to apply "C" without any knowledge or memory that at some point in the past, "B" was applied. This dictation issue shows us that this currently is not the case. When "C" comes in, it's based on the result of "B", even though we've tried to change things after "B" and before "C". This is the transaction argument that I'm making.

> I don't believe that this abstraction of information is causing any issue with regards to this problem, is there cases where you think this might cause an issue?

Given that this issue is still being investigated, and that there's no clear proposal for a solution, I think it's far too early to draw conclusions about the source of the problem. There's this stream of events that's arriving at unknown times, with unknown historical assumptions, and Flutter is applying a greedy algorithm that transforms that information before it gets to the app developer. That transformation could easily prove to be a problem. But it seems like there hasn't been much of an investigation into the nuances of this IME communication, so we don't know. 

What we **do know** for sure, is that other apps have built editors on top of the iOS and Android IME messages. Therefore, the exact messages that come from the platform IME can be used, in some fashion, to implement this desired behavior. What we **don't know** is that Flutter's transformed stream of messages can be used to do that, because no one has done it yet. There are only a handful of Flutter apps and packages that have implemented partial functionality, such as `super_editor`.

### Moving Forward
I would encourage you and @justinmc and the Flutter team in general to begin approaching IME communication in a more structured and substantive way. The current pattern seems to be to deliver a little functionality, wait for another issue to be filed, and then start a new investigation into that all over again. It seems to result in decisions that are based on a relatively superficial understanding of the underlying platform IME. I, too, have a relatively superficial understanding of the platform IME, but I'm also not solely responsible for designing Flutter's API for that communication. 

Text input, and even general content input, is absolutely fundamental to application user interfaces. It happens everywhere, and it happens with great diversity. These IME interactions, which we've discussed across a growing number of tickets, are absolute table stakes in the long run for Flutter. 

The Flutter team should understand the platform IME as deeply as the Flutter team understands how to display the Flutter view on the platform, how to integrate with the touch event system on the platform, how to connect to the v-sync signal on the platform, etc. There should be at least one developer on the team, if not multiple developers, who have expert level knowledge of platform IME APIs and behaviors. Because, again, that behavior is absolutely fundamental to Flutter. It's fundamental to all user interfaces.

I think that taking IME issues seriously means establishing foundational assets to help educate the team, and keep the team up to date. For example, you might:

- Write up Wiki or website docs for how you believe the IME APIs work on the various platforms. Include code snippets that demonstrate your understanding. These documents can be circulated around the team, and publicly. Other developers can correct you if they see that you've described something that isn't quite right. You can also circulate those internally with the Android team to at least get absolute experts on that side of things. But I bet you could even find some current or former iOS team devs to help, too.
- Run a diverse set of input through each platform's IME, e.g., text input that's completely correct, text input that uses spell check, text input with emojis, text input with key swiping, text input with links, text input with images, text input on GBoard vs Samsung, text input with dictation. Take the IME events from each of those real-world examples and put those IME events in Flutter IME test suites so that the world can see what real events look like, and they can see Flutter handling those events. These tests wouldn't assert much of anything - they would just run those real-world event streams through a typical Flutter widget tree and make sure that nothing goes crazy.
- Add integration tests for whichever of these keyboard tests you can manage. My guess is that dictation isn't possible, but maybe there's a test API for that, too. I'm sure there would be fewer integration tests than there would be example tests from the point above, but the purpose of the integration tests would be to ensure, roughly, that nothing major has changed in real world IME behavior as compared to when you collected the events from the point above.

I'm sure I could come up with many more suggestions, too. But the overarching point is that IME isn't going anywhere. This communication will only become strictly more complex, and more important as time moves forward. Therefore, I would strongly encourage you two, and the team, to start building a strong foundation for IME delta and content communication, rather than occasionally react to bug reports and/or undocumented behavior reports.

This ticket seems to indicate that there is a fundamental IME behavior, which, at best, is not understood by the Flutter team. I think this is a great opportunity to begin instituting the suggestions above, and perhaps others, too. This is a good opportunity to start publishing what you *think* is happening in the IME, show the evidence you have to believe that, and then start iterating on that understanding until you've worked through the unknowns. Only when the unknowns are resolved, does it make sense to start engineering solutions on top.

**Comment by Renzo-Olivares** [comment]
> Does iOS notify the client when dictation starts and stops? If so, is Flutter forwarding this information? If not, Flutter certainly should. Because if this problem is unique to dictation, then we may be able to create an alternate code path to deal with this specifically.

After some more investigation I think this potential solution is not feasible given the API's publicly available to us. `UITextInputMode` does not provide enough information for us to determine that dictation has started. https://developer.apple.com/documentation/uikit/uitextinput/1614507-dictationrecordingdidend Does provide a way to detect that dictation has ended, but without knowing when it started this won't help this specific issue. I've tried plugging into other dictation related API's but they're all called after `dictationRecordingDidEnd` so they were not useful.

Similarly on Android I could not find an API that would notify us on the start/end of dictation.

I understand your position that Flutter's transformation of events is currently unproven while Android and IOS IME API's are proven. This will require more investigation on my part, given everything you said I suspect that maybe if Flutter did not transform those events for example gave you a straight replacement for all dictations instead of transformed insertions/deletions then a `/n` would never be detected and therefore the scenario where `super_editor` inserts a hidden period at a new line (It would be helpful if you could provide the code snippet where this happens)  would not happen for dictation and this would not be an issue. Though that is a very specific case, and it may not solve other issues.

> Moving Forward

I see your points and definitely agree that Text input is fundamental to lots of applications. I think I will need to re-visit my overview of how platform IME's work to figure out a way forward considering the growing number of issues regarding TextEditingDeltas. Some issues seem to be interrelated and some also seem to be a result of the editing states on the framework and engine side not being completely in-sync. Thank you for the suggestions, I will keep them in mind when moving forward with this issue and others.

**Comment by matthew-carroll** [comment]
@Renzo-Olivares would you like to collect specific IME interaction use-cases from us? Would you like to do some of this together so that we can encourage some forward progress?

**Comment by Renzo-Olivares** [comment]
@matthew-carroll It would be great to collect those IME use-cases and collaborate on this. I'll reach out on discord next week so we can sync up regarding this.

**Comment by Jethro87** [comment]
@Renzo-Olivares Any updates on this? We're getting lots of users complaining about their content being deleted immediately after dictating on iOS. It's a very bad experience that I am unable to fix.

**Comment by Renzo-Olivares** [comment]
Hi @Jethro87, I've been working on the general issue of detecting dictation on iOS but haven't made much headway. I have been able to detect dictation on versions lower than iOS 16, but ideally a solution would work on all versions.

Another solution i'm exploring is to stop synthesizing some of the replacement deltas into insertion deltas on iOS. This processing of the raw deltas was done mostly because of some Android specific behavior described below and it could potentially be loosened for iOS.
> iirc the decision for this was because on Android it was observed that the composing region was always active resulting in constant replacements instead of an insertion or deletion. I think some context for this decision can be found here https://github.com/flutter/engine/pull/28175#discussion_r698937876 . I don't believe that this abstraction of information is causing any issue with regards to this problem, is there cases where you think this might cause an issue?

Recently, I've also been having trouble reproducing this issue on `super_editor`s latest branch. Are there any concrete steps for reproducing this? What devices / iOS versions is the behavior being observed on?

My device is an iPhone 14 Pro Max on iOS 17.
https://github.com/flutter/flutter/assets/948037/524b1f1f-a5e9-4493-a952-e26cfa788895

**Comment by matthew-carroll** [comment]
@Renzo-Olivares WRT reproduction difficulty, please consider that a symptom of the broader problem, and a forcing function for better testing tools. Reproducing IME bugs is very frustrating for everyone, almost all the time. It doesn't necessarily have to be this way. Flutter could introduce tooling, such as IME interaction within integration tests, which would remove a lot of the burden and variability. Instead of treating that as a temporary frustration within this particular ticket, I would encourage you and @justinmc to think of it as a pervasive problem within IME based development, and look at it as an opportunity to solve your frustrations, and everyone else's frustrations, at the same time.

**Comment by Jethro87** [comment]
@Renzo-Olivares Here's an example I just recorded

https://github.com/flutter/flutter/assets/6467808/a8baface-ea9e-4fac-a1b5-e8a8c79888bd

I'm currently running an iPhone 12 mini on iOS 17, with the example in Flutter stable branch / super_editor stable branch and the Mobile Editing - iOS editor config demo. I removed all text before recording the demo.

But, echoing what @matthew-carroll said, this isn't reproducible 100% of the time.

Thanks for your attention to this issue.

**Comment by Renzo-Olivares** [comment]
@Jethro87 Thank you for the details.

I am also able to reproduce this issue more consistently using flutter stable branch / super_editor stable branch.


https://github.com/flutter/flutter/assets/948037/47003dd3-f47e-4fd1-8b58-6d8c5934214c

I also get this crash:
```
#4      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1864:63)
text_input.dart:1864
#5      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20)
text_input.dart:1753
#6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:55)
platform_channel.dart:547
#7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:540:34)
platform_channel.dart:540
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
binding.dart:567
#9      _invoke2 (dart:ui/hooks.dart:202:13)
hooks.dart:202
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
channel_buffers.dart:45
#11     _Channel.push (dart:ui/channel_buffers.dart:135:31)
channel_buffers.dart:135
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17)
channel_buffers.dart:331
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22)
platform_dispatcher.dart:736
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
hooks.dart:114

call:
  MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 1, oldText:
  , selectionAffinity: TextAffinity.downstream, deltaEnd: 0, deltaText:  , deltaStart: 0,
  composingExtent: -1, selectionIsDirectional: false, selectionExtent: 1, composingBase: -1}]}])
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Null check operator used on a null value
```

I tried testing super_editor main branch / flutter stable branch but they were not compatible because of the migration off deprecated APIs.

I tried super_editor stable branch / flutter master branch and experienced similar results of my video here https://github.com/flutter/flutter/issues/120724#issuecomment-1800196286 .

All using a physical iPhone 14 pro max on iOS 17.

The only change I think may have affected this issue is https://github.com/flutter/engine/pull/43267 which was not included in the latest stable release from my knowledge. Can you try it out using the flutter master branch and let me know if you're experiencing the same behavior? I can also try to see if reverting this commit on the flutter master branch breaks any behavior.

@matthew-carroll Yeah it would be great if we were able to test this more throughly and on real devices. I think you have an issue open regarding this https://github.com/flutter/flutter/issues/131510 . We are definitely thinking of this but have nothing concrete yet.

**Comment by Jethro87** [comment]
@Renzo-Olivares Thanks for digging in. I just did some testing on my iPhone 12 mini (iOS 17) on Flutter beta (as I believe that engine commit is now in beta) and super_editor stable. 

I haven't experienced the same issue of text being removed upon tapping the voice text button to stop the dictation. I get additional spaces added to the beginning and end of the dictation, though. All in all, it seems that https://github.com/flutter/engine/pull/43267 is having a positive impact here.

https://github.com/flutter/flutter/assets/6467808/22925d42-aae2-462d-b3b5-2f13e4ad541b

**Comment by Renzo-Olivares** [comment]
@Jethro87 thank you for confirming that the situation is a lot better after that change. 

I also see the added spaces on my end so I'll try to investigate whats causing them.
