### ISSUE TITLE
[app_dart]  Access forbbidden on listing release branch commits

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#120798]
```
$ curl 'http://flutter-dashboard.appspot.com/api/create-branch?branch=flutter-3.8-candidate.10' -H "X-Flutter-IdToken: $(gcloud auth print-identity-token)"
GitHub Error: Access Forbidden
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:462:9)
#1      GitHub.request (package:github/src/common/github.dart:425:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:38:20)
<asynchronous suspension>
#3      GithubService.listCommits (package:cocoon_service/src/service/github_service.dart:42:5)
<asynchronous suspension>
#4      BranchService.branchFlutterRecipes.<anonymous closure> (package:cocoon_service/src/service/branch_service.dart:106:19)
<asynchronous suspension>
#5      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
#6      BranchService.branchFlutterRecipes (package:cocoon_service/src/service/branch_service.dart:105:53)
<asynchronous suspension>
#7      CreateBranch.get (package:cocoon_service/src/request_handlers/create_branch.dart:30:5)
<asynchronous suspension>
#8      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:50:24)
<asynchronous suspension>
#9      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:151:9)
<asynchronous suspension>
#10     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)
<asynchronous suspension>
#11     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:288:11)
<asynchronous suspension>
```

This is preventing new release branches from being created.

**Comment by CaseyHillers** [comment]
Duplicate of https://github.com/flutter/flutter/issues/124763
