### ISSUE TITLE
libpath_ops.so does not exist in linux engine v2 builds

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#120726]
```
Invalid argument(s): Failed to load dynamic library 'libpath_ops.so': libpath_ops.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      _dylib.<anonymous closure> (package:path_ops/path_ops.dart:307:31)
#3      _dylib (package:path_ops/path_ops.dart:310:2)
#4      _dylib (package:path_ops/path_ops.dart)
#5      _createPathFn (package:path_ops/path_ops.dart:330:5)
#6      _createPathFn (package:path_ops/path_ops.dart)
#7      new Path (package:path_ops/path_ops.dart:135:17)
#8      main.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/flutter/tools/path_ops/dart/test/path_ops_test.dart:10:23)
#9      Test.run.<anonymous closure>.<anonymous closure> (package:litetest/src/test.dart:69:21)
#10     new Future.<anonymous closure> (dart:async/future.dart:253:37)
#11     _rootRun (dart:async/zone.dart:1390:47)
#12     _CustomZone.run (dart:async/zone.dart:1300:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
#15     _rootRun (dart:async/zone.dart:1398:13)
#16     _CustomZone.run (dart:async/zone.dart:1300:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Comment by godofredoc** [comment]
Link to failure:

https://ci.chromium.org/p/flutter/builders/try/recipes-with-led/b8789151852609550529?

**Comment by godofredoc** [comment]
Fixed adding proper ninja targets: https://github.com/flutter/engine/pull/39635
