### ISSUE TITLE
[camera] NPE in `CameraCaptureSession.close()`

### ISSUE THREAD

**Issue by emakar** [flutter/flutter#121079]
camera: 0.10.3
camera_android: 0.10.4
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1244)
	at io.flutter.plugins.camera.Camera$1.onClosed(Camera.java:372)
	at android.hardware.camera2.impl.CameraDeviceImpl$5.run(CameraDeviceImpl.java:234)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by huycozy** [comment]
Hi @emakar 
Thanks for the report and also file a PR for this. But I see there's an open issue addressing the case you described #114012 which has the similar log and many users are reporting it too.

So I will close this issue in favor of #114012 which will help users be notified the progress. Please also update your PR description (link to #114012).
