### ISSUE TITLE
"A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed"

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#121019]
I get the following error report. It tells me to report this to the Flutter project.

```log
E/flutter ( 5513): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#e1023(physicalKey: PhysicalKeyboardKey#e6f4b(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:05:18.591830, synthesized)
hardware_keyboard.dart:432
E/flutter ( 5513): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 5513): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 5513): #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
hardware_keyboard.dart:432
E/flutter ( 5513): #3      HardwareKeyboard._assertEventIsRegular
hardware_keyboard.dart:443
E/flutter ( 5513): #4      HardwareKeyboard.handleKeyEvent
hardware_keyboard.dart:535
E/flutter ( 5513): #5      KeyEventManager.handleKeyData
hardware_keyboard.dart:881
E/flutter ( 5513): #6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:430:41)
E/flutter ( 5513): #7      _invoke1 (dart:ui/hooks.dart:164:13)
E/flutter ( 5513): #8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:428:7)
E/flutter ( 5513): #9      _invoke2 (dart:ui/hooks.dart:183:13)
E/flutter ( 5513): #10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
E/flutter ( 5513): #11     _Channel.push (dart:ui/channel_buffers.dart:130:31)
E/flutter ( 5513): #12     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
E/flutter ( 5513): #13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
E/flutter ( 5513): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
```

## Steps to Reproduce

Install `flutter_form_builder` into a new Flutter project, and create the following widget:
```dart
class CompleteForm extends StatefulWidget {
  const CompleteForm({Key? key}) : super(key: key);

  @override
  State<CompleteForm> createState() {
    return _CompleteFormState();
  }
}

class _CompleteFormState extends State<CompleteForm> {
  final _formKey = GlobalKey<FormBuilderState>();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        FormBuilder(
          key: _formKey,
          onChanged: () {
            _formKey.currentState!.save();
            debugPrint(_formKey.currentState!.value.toString());
          },
          autovalidateMode: AutovalidateMode.disabled,
          skipDisabled: true,
          child: Column(
            children: <Widget>[

              FormBuilderTextField(
                name: 'specify',
                decoration: const InputDecoration(
                    labelText: 'If Other, please specify'),
                validator: (val) {
                  if (val == null || val.isEmpty) {
                    return 'Please specify';
                  }
                  return null;
                },
              ),
            ],
          ),
        ),
      ],
    );
  }
}
```

Type a character into the text field, then delete it.

The above error message is shown.

<details>

<summary>Logs</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.3, on Fedora Linux 36 (Workstation Edition) 6.1.9-100.fc36.x86_64, locale en_US.utf8)
    • Flutter version 3.7.3 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (9 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.5 (Fedora 14.0.5-2.fc36)
    • cmake version 3.25.2
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Fedora Linux 36 (Workstation Edition) 6.1.9-100.fc36.x86_64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 110.0.5481.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment]
Hello @lukehutch. Can you test this on the master channel? I believe a fix has landed for this issue

**Comment by lukehutch** [comment]
Sorry for the delay. I can no longer reproduce this after upgrading from Flutter 3.7.3 to 3.7.7, so I assume this has been fixed, and the fix rolled out to the current release version. Thanks.
