### ISSUE TITLE
Failed to build flutter application for android

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#12110]
I've installed on the Lnux computer the Android Studio, Android SDK, gradle, dart, flutter and Intellij IDEA. Without problems. Was create a standard flutter project, but an error occurred during the build:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Launching lib/main.dart on LG H840 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...

Oops; flutter has exited unexpectedly.
Crash report written to /home/michael/IdeaProjects/first_nuc/flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.

* Where:
Script '/home/michael/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 329

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command '/home/michael/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Finished with error: Gradle build failed: 1
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
What do you advise?
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Trace log flutter_03.log is given below:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build flx --suppress-analytics --target /home/michael/IdeaProjects/first_nuc/lib/main.dart --output-file /home/michael/IdeaProjects/first_nuc/build/app/intermediates/flutter/debug/app.flx --snapshot /home/michael/IdeaProjects/first_nuc/build/app/intermediates/flutter/debug/snapshot_blob.bin --depfile /home/michael/IdeaProjects/first_nuc/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --working-dir /home/michael/IdeaProjects/first_nuc/build/app/intermediates/flutter/debug/flx

## exception

ProcessException: ProcessException: No such file or directory
  Command: /home/michael/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot --assert_initializer --await_is_keyword --causal_async_stacks --vm_snapshot_data=/home/michael/flutter/bin/cache/artifacts/engine/linux-x64/vm_isolate_snapshot.bin --isolate_snapshot_data=/home/michael/flutter/bin/cache/artifacts/engine/linux-x64/isolate_snapshot.bin --packages=/home/michael/IdeaProjects/first_nuc/.packages --dependencies=/home/michael/IdeaProjects/first_nuc/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --print_snapshot_sizes --snapshot_kind=script --script_snapshot=/home/michael/IdeaProjects/first_nuc/build/app/intermediates/flutter/debug/snapshot_blob.bin /home/michael/IdeaProjects/first_nuc/lib/main.dart

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:125)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:55)
#2      Snapshotter._build (package:flutter_tools/src/base/build.dart:210)
<asynchronous suspension>
#3      Snapshotter.buildScriptSnapshot (package:flutter_tools/src/base/build.dart:175)
<asynchronous suspension>
#4      build (package:flutter_tools/src/flx.dart:58)
<asynchronous suspension>
#5      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:44)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#7      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#15     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1467)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#24     main (file:///home/michael/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[-] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/michael/flutter
    • Framework revision 701d534ba9 (3 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/michael/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /home/michael/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/michael/Downloads/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • LG H840 • LGH840b2ec63ed • android-arm • Android 6.0.1 (API 23)

```

**Comment by micrcx** [comment]
The problem is solved quite simply. When installing Android Studio (link: https://developer.android.com/studio/install.html) in Ubuntu or Linux Mint, pay attention to the next line:
**sudo apt-get install libc6: i386 libncurses5: i386 libstdc ++ 6: i386 lib32z1 libbz2-1.0: i386.**
I was inattentive and lost the day. Learn from other people's mistakes.
