### ISSUE TITLE
AboutListTile crash

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#12111]
Usage:
```
new AboutListTile(
          applicationName: "APP_NAME",
          applicationVersion: "AppVersion",
          aboutBoxChildren: [])
```
click "View Licenses"

Full stack trace as is:

```
E: [ERROR:lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
   'package:flutter/src/foundation/licenses.dart': Failed assertion: line 146: 'result.text.trimLeft() == result.text': is not true.
   #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
   #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
   #2      LicenseEntryWithLineBreaks.paragraphs.getParagraph (package:flutter/src/foundation/licenses.dart:146)
   #3      LicenseEntryWithLineBreaks.paragraphs (package:flutter/src/foundation/licenses.dart:189)
   #4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:61)
   #5      _LicensePageState._initLicenses.<anonymous closure> (package:flutter/src/material/about.dart:394)
   #6      State.setState (package:flutter/src/widgets/framework.dart:1161)
   #7      _LicensePageState._initLicenses (package:flutter/src/material/about.dart:376)
   <asynchronous suspension>
   #8      _LicensePageState.initState (package:flutter/src/material/about.dart:366)
   #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3666)
   #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3530)
   #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
   #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
   #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3567)
   #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3456)
   #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3535)
   #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3530)
   #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
   #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
   #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3567)
   #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3456)
   #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3535)
   #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3530)
   #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
   #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
   #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4537)
   #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
   #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
   #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4537)
   #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
   #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
   #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3567)
   #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3456)
   #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3535)
   #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3673)
   #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3530)
   #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
   #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
   #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3567)
   #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3456)
   #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3535)
   #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3530)
   #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
   #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
   #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4537)
   #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
   #46     Element.updateC
```

**Comment by Hixie** [comment]
What packages are you importing?

**Comment by JFixby** [comment]
`import 'package:flutter/material.dart';`

**Comment by Hixie** [comment]
I meant in your `pubspec.yaml`, sorry.

**Comment by JFixby** [comment]
I can't help on this issue, it was reported in September 2017. I don't even have the code I had the problem with.

**Comment by Hixie** [comment]
ok. I'm going to close this for now, someone will file it again at some point!

**Comment by mendieta** [comment]
Hi I have this same issue, the dependencies in the pubspec are:

`
dependencies:
  ads: ^0.11.0
  app_review: ^1.0.0
  fluro: ^1.5.0
  firebase_admob: ^0.9.0+1
  firebase_analytics: ^3.0.3
  firebase_core: ^0.4.0+6
  firebase_database: ^3.0.4
  firebase_dynamic_links: ^0.4.0+4
  firebase_remote_config: ^0.2.0+3
  cloud_functions: ^0.4.0+2
  device_id: ^0.2.0
  mobx: ^0.3.3+2
  flutter_mobx: ^0.3.0+1
  provider: ^3.0.0+1
  sqflite:
  shared_preferences: ^0.5.3+2
  url_launcher: ^5.0.5
  flutter_platform_widgets: ^0.12.0
  flutter_inner_drawer: ^0.3.0
  flutter_secure_storage: ^3.2.1+1
  package_info: ^0.4.0+4
  share: ^0.6.1+1
  flutter_search_bar:
  after_layout:
  flutter_map:
`

and the error log:

`
I/flutter (23452): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23452): The following assertion was thrown during a task callback:
I/flutter (23452): 'package:flutter/src/foundation/licenses.dart': Failed assertion: line 160 pos 14:
I/flutter (23452): 'result.text.trimLeft() == result.text': is not true.
`

Hope this helps solve this issue
