### ISSUE TITLE
FormatException: No ':' on line 

### ISSUE THREAD

**Issue by neqr** [flutter/flutter#12128]
> -> flutter packages get
> Oops; flutter has exited unexpectedly.
> ...

This error creeped in after a crash of Windows 10 x64. 

Now I get it with almost every flutter command (even flutter doctor sometimes).
When I get the "flutter doctor" command to actually run, it shows that all requirements are met.

## Log

FormatException: FormatException: No ':' on line (at offset 5810)

```
#0      parse (package:package_config/packages_file.dart:53)
#1      _parse (package:flutter_tools/src/dart/package_map.dart:13)
#2      PackageMap.load (package:flutter_tools/src/dart/package_map.dart:33)
#3      PackageMap.map (package:flutter_tools/src/dart/package_map.dart:37)
#4      FlutterCommandRunner._checkFlutterCopy (package:flutter_tools/src/runner/flutter_command_runner.dart:402)
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:242)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      new Future.sync (dart:async/future.dart:222)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#10     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     runZoned (dart:async/zone.dart:1467)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#19     main (file:///C:/tools/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

**Comment by Hixie** [comment]
As a workaround, try deleting your `.packages` file.

**Comment by Hixie** [comment]
The fundamental problem is that `_parse` in `package_map.dart` doesn't know how to handle failure.
I'm not sure exactly how we should handle it. Probably treat it as a missing file? I wonder what `pub` does with a broken `.packages` file.

**Comment by ericjatis** [comment]
Deleting .packages file works for me

**Comment by Predatorie** [comment]
Windows crashed this morning and then this error occurred.  Deleting .packages and updating fixed the issue.
