### ISSUE TITLE
The accept flutter licenses step is causing failure in the cirrus tests

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#121242]
```
Downloaded lcov data for package:flutter in 0.0s...
Ran pub get in packages/flutter_goldens_client in 5.3s...
Ran pub get in packages/flutter_goldens in 6.0s...
Ran pub get in packages/fuchsia_remote_debug_protocol in 6.8s...
Running "flutter pub get" in affected packages...                 176.5s

Ran 'pub get' 69 times and fetched coverage data in 176.5s.
flutter doctor -v
[!] Flutter (Channel unknown, 3.8.0-14.0.pre.32, on Ubuntu 18.04.6 LTS 5.10.109+, locale en_US.UTF-8)
    ! Flutter version 3.8.0-14.0.pre.32 on channel unknown at /tmp/flutter sdk
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision aef56fd16d (12 minutes ago), 2023-02-21 19:07:42 -0800
    • Engine revision 3aa112c75c
    • Dart version 3.0.0 (build 3.0.0-261.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/android_sdk
    • Platform android-30, build-tools 28.0.3
    • ANDROID_SDK_ROOT = /opt/android_sdk
    • Java binary at: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 18.04.6 LTS 5.10.109+
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
./dev/bots/accept_android_sdk_licenses.sh
Flutter SDK directory is: /tmp/flutter sdk
Accepting Android licenses.
Accepting Android licenses failed.
������������������������������������������������������������
```

**Comment by ricardoamador** [comment]
Okay the actual error is the following:
```
    • Java binary at: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 18.04.6 LTS 5.10.109+
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
./dev/bots/accept_android_sdk_licenses.sh
Flutter SDK directory is: /tmp/flutter sdk
Accepting Android licenses.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Android sdkmanager tool was found, but failed to run (/opt/android_sdk/cmdline-tools/latest/bin/sdkmanager): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
Accepting Android licenses failed.
������������������������������������������������������������
```

**Comment by ricardoamador** [comment]
This is mostly due to a difference in the JDK used to compile the bytecode. Probably java 11 was used and this is trying to run with jdk 8.

**Comment by reidbaker** [comment]
Java 11 was added in https://github.com/flutter/engine/pull/39375

**Comment by gspencergoog** [comment]
What's the status of this issue? Have we found the solution and are just waiting for deployment, or is it still unclear? (Just looking for a status update.)

**Comment by ricardoamador** [comment]
@gspencergoog this has been resolved. Please pull in the newest changes to your branch.
