### ISSUE TITLE
Tree is closed on Mac_ios spell_check_test test for platform_view commit

### ISSUE THREAD

**Issue by nehalvpatel** [flutter/flutter#121381]
Commit https://github.com/flutter/flutter/commit/1155d2719d5626a5bd31eb882707ffc56ea4b1ca is consistently failing the `Mac_ios spell_check_test test` after 5 attempts and closing the tree.

It is from this PR: [[platform_view]integration test for platform view not tappable issue](https://github.com/flutter/flutter/pull/120844).

<details>
  <summary>Screenshot</summary>
<img width="973" alt="Screenshot 2023-02-23 at 9 35 19 PM" src="https://user-images.githubusercontent.com/159021/221100354-e6cca472-9790-40de-824e-5e903866f56e.png">
</details>

---

It looks like all the tests are failing from the same error:
<details>
  <summary>Log</summary>

```
[spell_check_test_ios] [STDOUT] stdout: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[spell_check_test_ios] [STDOUT] stdout: The following assertion was thrown building KeyedSubtree-[GlobalKey#7366b]:
[spell_check_test_ios] [STDOUT] stdout: spellCheckService must be specified for this platform because no default service available
[spell_check_test_ios] [STDOUT] stdout: 'package:flutter/src/widgets/editable_text.dart':
[spell_check_test_ios] [STDOUT] stdout: Failed assertion: line 2411 pos 7: 'spellCheckService != null
[spell_check_test_ios] [STDOUT] stdout:       || WidgetsBinding.instance.platformDispatcher.nativeSpellCheckServiceDefined'
[spell_check_test_ios] [STDOUT] stdout: 
[spell_check_test_ios] [STDOUT] stdout: Either the assertion indicates an error in the framework itself, or we should provide substantially
[spell_check_test_ios] [STDOUT] stdout: more information in this error message to help you determine and fix the underlying cause.
[spell_check_test_ios] [STDOUT] stdout: In either case, please report this assertion by filing a bug on GitHub:
[spell_check_test_ios] [STDOUT] stdout:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
[spell_check_test_ios] [STDOUT] stdout: 
[spell_check_test_ios] [STDOUT] stdout: The relevant error-causing widget was:
[spell_check_test_ios] [STDOUT] stdout:   Scaffold
[spell_check_test_ios] [STDOUT] stdout:   Scaffold:file:///opt/s/w/ir/x/w/recipe_cleanup/tmp2w93tuli/flutter%20sdk/dev/integration_tests/spell_check/lib/main.dart:38:12
[spell_check_test_ios] [STDOUT] stdout: 
[spell_check_test_ios] [STDOUT] stdout: When the exception was thrown, this was the stack:
[spell_check_test_ios] [STDOUT] stdout: #2      EditableTextState._inferSpellCheckConfiguration (package:flutter/src/widgets/editable_text.dart:2411:7)
[spell_check_test_ios] [STDOUT] stdout: #3      EditableTextState.initState (package:flutter/src/widgets/editable_text.dart:2573:32)
[spell_check_test_ios] [STDOUT] stdout: #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5114:55)
[spell_check_test_ios] [STDOUT] stdout: #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4957:5)
[spell_check_test_ios] [STDOUT] stdout: ...     Normal element mounting (28 frames)
[spell_check_test_ios] [STDOUT] stdout: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3964:16)
[spell_check_test_ios] [STDOUT] stdout: #34     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6519:36)
[spell_check_test_ios] [STDOUT] stdout: #35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6531:32)
[spell_check_test_ios] [STDOUT] stdout: ...     Normal element mounting (136 frames)
[spell_check_test_ios] [STDOUT] stdout: #171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3964:16)
[spell_check_test_ios] [STDOUT] stdout: #172    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6519:36)
[spell_check_test_ios] [STDOUT] stdout: #173    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6531:32)
[spell_check_test_ios] [STDOUT] stdout: ...     Normal element mounting (172 frames)
[spell_check_test_ios] [STDOUT] stdout: #345    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3964:16)
[spell_check_test_ios] [STDOUT] stdout: #346    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6519:36)
[spell_check_test_ios] [STDOUT] stdout: #347    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6531:32)
[spell_check_test_ios] [STDOUT] stdout: ...     Normal element mounting (466 frames)
[spell_check_test_ios] [STDOUT] stdout: #813    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3964:16)
[spell_check_test_ios] [STDOUT] stdout: #814    Element.updateChild (package:flutter/src/widgets/framework.dart:3695:20)
[spell_check_test_ios] [STDOUT] stdout: #815    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5006:16)
[spell_check_test_ios] [STDOUT] stdout: #816    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
[spell_check_test_ios] [STDOUT] stdout: #817    ProxyElement.update (package:flutter/src/widgets/framework.dart:5312:5)
[spell_check_test_ios] [STDOUT] stdout: #818    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
[spell_check_test_ios] [STDOUT] stdout: #819    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5006:16)
[spell_check_test_ios] [STDOUT] stdout: #820    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5146:11)
[spell_check_test_ios] [STDOUT] stdout: #821    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
[spell_check_test_ios] [STDOUT] stdout: #822    StatefulElement.update (package:flutter/src/widgets/framework.dart:5169:5)
[spell_check_test_ios] [STDOUT] stdout: #823    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
[spell_check_test_ios] [STDOUT] stdout: #824    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5006:16)
[spell_check_test_ios] [STDOUT] stdout: #825    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
[spell_check_test_ios] [STDOUT] stdout: #826    ProxyElement.update (package:flutter/src/widgets/framework.dart:5312:5)
[spell_check_test_ios] [STDOUT] stdout: #827    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
[spell_check_test_ios] [STDOUT] stdout: #828    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5006:16)
[spell_check_test_ios] [STDOUT] stdout: #829    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
[spell_check_test_ios] [STDOUT] stdout: #830    StatelessElement.update (package:flutter/src/widgets/framework.dart:5057:5)
[spell_check_test_ios] [STDOUT] stdout: #831    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
[spell_check_test_ios] [STDOUT] stdout: #832    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6391:14)
[spell_check_test_ios] [STDOUT] stdout: #833    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
[spell_check_test_ios] [STDOUT] stdout: #834    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1196:16)
[spell_check_test_ios] [STDOUT] stdout: #835    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1173:5)
[spell_check_test_ios] [STDOUT] stdout: #836    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1187:7)
[spell_check_test_ios] [STDOUT] stdout: #837    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
[spell_check_test_ios] [STDOUT] stdout: #838    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2773:19)
[spell_check_test_ios] [STDOUT] stdout: #839    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:21)
[spell_check_test_ios] [STDOUT] stdout: #840    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
[spell_check_test_ios] [STDOUT] stdout: #841    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1286:15)
[spell_check_test_ios] [STDOUT] stdout: #842    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1216:9)
[spell_check_test_ios] [STDOUT] stdout: #843    LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1706:13)
[spell_check_test_ios] [STDOUT] stdout: #844    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1074:5)
[spell_check_test_ios] [STDOUT] stdout: #848    _invoke (dart:ui/hooks.dart:144:10)
[spell_check_test_ios] [STDOUT] stdout: #849    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:368:5)
[spell_check_test_ios] [STDOUT] stdout: #850    _drawFrame (dart:ui/hooks.dart:112:31)
[spell_check_test_ios] [STDOUT] stdout: (elided 5 frames from class _AssertionError and dart:async)
[spell_check_test_ios] [STDOUT] stdout: 
[spell_check_test_ios] [STDOUT] stdout: ════════════════════════════════════════════════════════════════════════════════════════════════════
[spell_check_test_ios] [STDOUT] stdout: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[spell_check_test_ios] [STDOUT] stdout: The following assertion was thrown during performLayout():
[spell_check_test_ios] [STDOUT] stdout: Each child must be laid out exactly once.
[spell_check_test_ios] [STDOUT] stdout: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following child:
[spell_check_test_ios] [STDOUT] stdout:   _ScaffoldSlot.body: RenderErrorBox#faffe NEEDS-LAYOUT NEEDS-PAINT
[spell_check_test_ios] [STDOUT] stdout: 
[spell_check_test_ios] [STDOUT] stdout: The relevant error-causing widget was:
[spell_check_test_ios] [STDOUT] stdout:   Scaffold
[spell_check_test_ios] [STDOUT] stdout:   Scaffold:file:///opt/s/w/ir/x/w/recipe_cleanup/tmp2w93tuli/flutter%20sdk/dev/integration_tests/spell_check/lib/main.dart:38:12
[spell_check_test_ios] [STDOUT] stdout: 
[spell_check_test_ios] [STDOUT] stdout: When the exception was thrown, this was the stack:
[spell_check_test_ios] [STDOUT] stdout: #0      MultiChildLayoutDelegate._callPerformLayout.<anonymous closure> (package:flutter/src/rendering/custom_layout.dart:238:11)
[spell_check_test_ios] [STDOUT] stdout: #1      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:250:8)
[spell_check_test_ios] [STDOUT] stdout: #2      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
[spell_check_test_ios] [STDOUT] stdout: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #4      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #6      RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #7      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #9      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
[spell_check_test_ios] [STDOUT] stdout: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #11     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #14     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #16     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #17     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #20     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #21     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
[spell_check_test_ios] [STDOUT] stdout: #22     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:585:43)
[spell_check_test_ios] [STDOUT] stdout: #23     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:612:12)
[spell_check_test_ios] [STDOUT] stdout: #24     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #25     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #28     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #30     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #31     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #34     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #36     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #37     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #39     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #40     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #42     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3753:13)
[spell_check_test_ios] [STDOUT] stdout: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #44     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #46     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #47     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #48     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:843:15)
[spell_check_test_ios] [STDOUT] stdout: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #50     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #52     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #53     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #56     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #59     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #61     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:549:11)
[spell_check_test_ios] [STDOUT] stdout: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #63     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #65     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #66     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #69     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #71     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: #72     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
[spell_check_test_ios] [STDOUT] stdout: #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
[spell_check_test_ios] [STDOUT] stdout: #74     RenderObject.layout (package:flutter/src/rendering/object.dart:2181:7)
[spell_check_test_ios] [STDOUT] stdout: 
[spell_check_test_ios] [STDOUT] stdout: 01:00 +4 -1: EditableText spell checks when text is entered and spell check enabled [E]                                                                                                                
[spell_check_test_ios] [STDOUT] stdout:   Test failed. See exception logs above.
[spell_check_test_ios] [STDOUT] stdout:   The test description was: EditableText spell checks when text is entered and spell check enabled
[spell_check_test_ios] [STDOUT] stdout:   
[spell_check_test_ios] [STDOUT] stdout: 
[spell_check_test_ios] [STDOUT] stdout: To run this test again: /opt/s/w/ir/x/w/recipe_cleanup/tmp2w93tuli/flutter sdk/bin/cache/dart-sdk/bin/dart test /opt/s/w/ir/x/w/recipe_cleanup/tmp2w93tuli/flutter sdk/dev/integration_tests/spell_check/integration_test/integration_test.dart -p vm --plain-name 'EditableText spell checks when text is entered and spell check enabled'
```
</details>

---

Build 677 step log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8788326569183901201/+/u/run_spell_check_test_ios/test_stdout

Build 678 step log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8788324462328743681/+/u/run_spell_check_test_ios/test_stdout

Build 679 step log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8788324092591267905/+/u/run_spell_check_test_ios/test_stdout

Build 682 step log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8788308558638668017/+/u/run_spell_check_test_ios/test_stdout

Build 683 step log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8788304787057200545/+/u/run_spell_check_test_ios/test_stdout

**Comment by cyanglaz** [comment]
Looks like it started failing at https://github.com/flutter/flutter/commit/56a54d6d100ea394d32f713bb2c15dd568ec04dc and it is fixed by https://github.com/flutter/flutter/commit/4811269379c253b3be833636ad3af2f24d6d8a6b
The PR actually broke the test is https://github.com/flutter/flutter/issues/39685?

I'm going to close this issue since the tree is open now.
