### ISSUE TITLE
Non-fatal: Null check operator used on a null value [SelectionOverlay._buildToolbar]

### ISSUE THREAD

**Issue by rohansohonee1** [flutter/flutter#121385]
## Steps to Reproduce
Unable to reproduce. Crash reported from firebase.

**Expected results:** 
Should not crash.

**Actual results:** 
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'Ria'.
#00 pc 0x4e0d8b com.agendaboa.app (SelectionOverlay._buildToolbar [text_selection.dart:984])
#01 pc 0x4e09bb com.agendaboa.app (SelectionOverlay._buildToolbar [text_selection.dart:979])
#02 pc 0x7df2bf com.agendaboa.app (_OverlayEntryWidgetState.build [overlay.dart:256])
#03 pc 0x916233 com.agendaboa.app (StatefulElement.build [framework.dart:4992])
#04 pc 0xbce33b com.agendaboa.app (ComponentElement.performRebuild [framework.dart:4878])
#05 pc 0x45778b com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5050])
#06 pc 0xc5eb23 com.agendaboa.app (StatefulElement.update [framework.dart:4604])
#07 pc 0x807327 com.agendaboa.app (RenderObjectElement.updateChildren [framework.dart:3570])
#08 pc 0x8087db com.agendaboa.app (MultiChildRenderObjectElement.update [framework.dart:6460])
#09 pc 0xbce5cf com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3570])
#10 pc 0x45778b com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5050])
#11 pc 0xbbfdcf com.agendaboa.app (BuildOwner.buildScope [framework.dart:4604])
#12 pc 0x4fa18f com.agendaboa.app (WidgetsBinding.drawFrame [binding.dart:882])
#13 pc 0x4f99c3 com.agendaboa.app (RendererBinding._handlePersistentFrameCallback [binding.dart:378])
#14 pc 0x4f998b com.agendaboa.app (RendererBinding._handlePersistentFrameCallback [binding.dart:377])
#15 pc 0xbb99d3 com.agendaboa.app (SchedulerBinding._invokeFrameCallback [binding.dart:1175])
#16 pc 0xbb9927 com.agendaboa.app (SchedulerBinding.handleDrawFrame [binding.dart:1104])
#17 pc 0x33c107 com.agendaboa.app (SchedulerBinding._handleDrawFrame [binding.dart:1015])
#18 pc 0x33bfb7 com.agendaboa.app (SchedulerBinding._handleDrawFrame [binding.dart:997])
#19 pc 0x31370b com.agendaboa.app (_invoke [hooks.dart:148])
#20 pc 0x313da7 com.agendaboa.app (PlatformDispatcher._drawFrame [platform_dispatcher.dart:318])
#21 pc 0x313d5b com.agendaboa.app (_drawFrame [hooks.dart:115])
#22 pc 0x313ddb com.agendaboa.app (_drawFrame [hooks.dart:113])
```

**Device details:**
```
Brand:samsung
Model:Galaxy A20
Orientation: Portrait
RAM free: 471.73 MB
Disk free: 1.99 GB
Operating System
Version:Android 11
Orientation: Portrait
Rooted:No
Crash
Date:Feb 24, 2023, 3:30:12 AM
App version:3.7.3 (176)
```

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6.3 21G419 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

**Comment by huycozy** [comment]
@rohansohonee1 Is this issue reproducible locally? If so, can you please share the output of `flutter run -v`?

And does it happen on other devices? Please also provide the percentage occurrence of the crash if any. Thanks!

**Comment by rohansohonee1** [comment]
@huycozy 
I don't know the steps to reproduce this. For now it has crashed 3 times for 1 user using a Samsung.

**Comment by huycozy** [comment]
Labeling the issue for the team's attention.

**Comment by acgacgacgacg** [comment]
Same issue here and occurs on Android only.
Android 10~14, devices varies from Sony Xperia 1 III, IV, Samsung Galaxy Note10+, Xiaomi 
Mi 11 Lite 5G, Google Pixel 7a etc.

Both `Overlay.of(context)` and `Overlay.maybeOf` will cause this problem.

I'm using flutter 3.16.5. Here is the crash report log.
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value
       at Element.widget(framework.dart:3474)
       at LookupBoundary.findAncestorStateOfType.<fn>(lookup_boundary.dart:171)
       at Element.visitAncestorElements(framework.dart:4857)
       at LookupBoundary.findAncestorStateOfType(lookup_boundary.dart:166)
       at Overlay.maybeOf(overlay.dart:520)
       at .showOverlay(overlay.dart:5)
       at startLiveHandsOn.<fn>(tutorial.dart:112)
       at TutorialCoachMarkWidgetState.build.<fn>(tutorial_coach_mark_widget.dart:106)
       at AnimatedFocusLightState._tapHandler(animated_focus_light.dart:130)
       at AnimatedPulseFocusLightState.build.<fn>(animated_focus_light.dart:385)
       at _InkResponseState.handleTap(ink_well.dart:1183)
       at GestureRecognizer.invokeCallback(recognizer.dart:275)
       at TapGestureRecognizer.handleTapUp(tap.dart:652)
       at BaseTapGestureRecognizer._checkUp(tap.dart:309)
       at BaseTapGestureRecognizer.handlePrimaryPointer(tap.dart:242)
       at PrimaryPointerGestureRecognizer.handleEvent(recognizer.dart:630)
       at PointerRouter._dispatch(pointer_router.dart:98)
       at PointerRouter._dispatchEventToRoutes.<fn>(pointer_router.dart:143)
       at _LinkedHashMapMixin.forEach(dart:collection)
       at PointerRouter._dispatchEventToRoutes(pointer_router.dart:141)
       at PointerRouter.route(pointer_router.dart:127)
       at GestureBinding.handleEvent(binding.dart:488)
       at GestureBinding.dispatchEvent(binding.dart:468)
       at RendererBinding.dispatchEvent(binding.dart:439)
       at GestureBinding._handlePointerEventImmediately(binding.dart:413)
       at GestureBinding.handlePointerEvent(binding.dart:376)
       at GestureBinding._flushPointerEventQueue(binding.dart:323)
       at GestureBinding._handlePointerDataPacket(binding.dart:292)
```
