### ISSUE TITLE
[webview_flutter] Crash following along with the README

### ISSUE THREAD

**Issue by NebulaFox** [flutter/flutter#121412]
Getting the error

```
A platform implementation for `webview_flutter` has not been set. Please ensure that an implementation of `WebViewPlatform` has been set to `WebViewPlatform.instance` before use. For unit testing, `WebViewPlatform.instance` can be set with your own test implementation.
'package:webview_flutter_platform_interface/src/platform_webview_controller.dart':
Failed assertion: line 25 pos 7: 'WebViewPlatform.instance != null'

When the exception was thrown, this was the stack
#2      new PlatformWebViewController (package:webview_flutter_platform_interface/src/platform_webview_controller.dart:25:7)
#3      new WebViewController.fromPlatformCreationParams (package:webview_flutter/src/webview_controller.dart:84:25)
#4      new WebViewController (package:webview_flutter/src/webview_controller.dart:49:14)
```

I followed the instructions on the `README` on `webview_flutter`:

* add `webview_flutter` (did so via `flutter pub add webview_flutter`)
* Created a `StatefulWidget` with `WebViewController` and `WebViewWidget`
* Used url `https://theuselessweb.com/`

I would expect `WebViewPlatform.instance` not requiring to be set by me.

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewPage extends StatefulWidget {
  final Uri url;
  final Widget? title;

  const WebViewPage({
    super.key,
    required this.url,
    this.title,
  });

  @override
  State<StatefulWidget> createState() => _WebViewPageState();
}

class _WebViewPageState extends State<WebViewPage> {
  late WebViewController _controller;
  late double _progress;

  @override
  void initState() {
    _progress = 0;
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(Colors.white)
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            setState(() {
              _progress = progress / 100;
            });
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            // if (request.url.startsWith('https://www.youtube.com/')) {
            //   return NavigationDecision.prevent;
            // }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(widget.url);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        title: widget.title,
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(6.0),
          child: LinearProgressIndicator(
            backgroundColor: theme.colorScheme.onPrimary,
            valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary),
            value: _progress,),
        ),
      ),
      body: WebViewWidget(controller: _controller,)
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6.2 21G320 darwin-arm64, locale
    en-GB)
    • Flutter version 3.7.3 on channel stable at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (2 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
```

</details>

**Comment by znromonk** [comment]
@NebulaFox 
`A platform implementation for 'webview_flutter' has not been set.` Similar message comes up when you do a `pub add` while the app is running/debugging. I ran your sample code on a newly created flutter project and it loaded up just fine on an iOS device.

You could also get the same error if you were trying to run on web or other unsupported platform. `webview_flutter` only supports Android and iOS. If you want to use on web, you need to explicitly add the web implementation [webview_flutter_web](https://pub.dev/packages/webview_flutter_web)

**Comment by NebulaFox** [comment]
Thank you @znromonk.
Turns out it was doing a `pub add` while running/debugging. Sometimes it never crosses my mind that when adding packages, I need to quit and rebuild the app.
