### ISSUE TITLE
Flutter Camera Plugin, CameraException(error, stop failed.) 

### ISSUE THREAD

**Issue by prathmeshz** [flutter/flutter#121459]
I am unable to stop video recording every time i click on stop it shows fail to stop.

Flutter version 3.3.8
camera version  ^0.10.3+1

stop failed: -1007
Failed to handle method call
java.lang.RuntimeException: stop failed.
at android.media.MediaRecorder.stop(Native Method)
at io.flutter.plugins.camera.Camera.stopVideoRecording(Camera.java:782)
at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:129)
at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by AbhishekDoshi26** [comment]
@prathmeshz did you first check whether the recorder has entered the recording mode or not?
I believe, you should first check whether the controller is recording or not.

**Comment by darshankawar** [comment]
@prathmeshz 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/79306 so please follow-up in it for further updates. Closing this as a duplicate.

Please do leave a thumbs up on the original author's post so we can track and prioritize the issue base on severity and demand. Thanks!
