### ISSUE TITLE
Execution error for Android

### ISSUE THREAD

**Issue by alirezabashi98** [flutter/flutter#121472]
The new version of Flutter, when I create a new raw project, it runs with the default code for Linux, but not for Android, and it gives the following error, what is the reason?

## Logs 

```
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:212)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1208)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception: Gradle task assembleDebug failed with exit code 1
```

```
[✓] Flutter (Channel stable, 3.7.5, on Manjaro Linux 5.15.94-1-MANJARO, locale
    en_US.UTF-8)
    • Flutter version 3.7.5 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (3 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/alireza/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/google/chrome/chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.25.2
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /opt/idea-IU-223.8214.52
    • Flutter plugin version 71.2.6
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • SM A536B (mobile) • 192.168.1.6:46507 • android-arm64  • Android 13 (API 33)
    • Linux (desktop)   • linux             • linux-x64      • Manjaro Linux 5.15.94-1-MANJARO
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 110.0.5481.100 unknown

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@alirezabashi98 
Looking at the error log, it seems to be related to network. Are you by any chance behind proxy / firewall ?

> it runs with the default code for Linux, but not for Android

Can you elaborate on this what exactly it means ? Also check if you are hitting ipv4 or ipv6.

**Comment by alirezabashi98** [comment]
@darshankawar 
It means that there is no problem when running on Linux, but it is a problem when running on Android
And I am connected to IPv4

**Comment by darshankawar** [comment]
@alirezabashi98 
The error thrown is to indicate potentially corrupt cached files when the Flutter tool sees network errors from Gradle. Try changing your gradle version or have it on latest version and run again.

**Comment by alirezabashi98** [comment]
The problem was solved

First, I created a normal native Android project with Android Studio and ran it to see if it works or not

Then I went to the Hay version of Kotlin and transferred it to the Flatrim project and it was fixed


And I also added the latest version of buildToolsVersion to Gridel


     buildToolsVersion '34.0.0 rc1'

     ext.kotlin_version = '1.7.20'

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip

**Comment by alirezabashi98** [comment]
The problem was solved

First, I created a normal native Android project with Android Studio and ran it to see if it works or not

Then I went to the Hay version of Kotlin and transferred it to the Flatrim project and it was fixed


And I also added the latest version of buildToolsVersion to Gridel


     buildToolsVersion '34.0.0 rc1'

     ext.kotlin_version = '1.7.20'

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
