### ISSUE TITLE
[tool_crash] ProcessException: error: The directory /Users/vuphuong/Desktop/food_e/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: /usr/bin/arch, OS error code: 78

### ISSUE THREAD

**Issue by vxphuongictu** [flutter/flutter#121508]
## Command
```
flutter build ipa -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2023-02-27 13:35:49.008 xcodebuild[95613:7197109] Writing error result bundle to /var/folders/z9/h4rj7rs175b735t_br80xsbw0000gn/T/ResultBundle_2023-27-02_13-35-0049.xcresult
xcodebuild: error: The directory /Users/vuphuong/Desktop/food_e/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: /usr/bin/arch, OS error code: 78
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:278:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:321:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/xcode_project.dart:318:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/xcode_project.dart:278:36)
<asynchronous suspension>
#5      IosProject._parseHostAppBundleName (package:flutter_tools/src/xcode_project.dart:254:55)
<asynchronous suspension>
#6      IosProject.hostAppBundleName (package:flutter_tools/src/xcode_project.dart:243:35)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:116:39)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:82:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp.<anonymous closure> (package:flutter_tools/src/commands/build_ios.dart:604:34)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:641:33)
<asynchronous suspension>
#11     BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:417:50)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1287:27)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.8.0-16.0.pre.57, on macOS 13.0 22A380 darwin-arm64, locale en-VN)
    [32m•[39m Flutter version 3.8.0-16.0.pre.57 on channel master at /Users/vuphuong/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 45723adf4d (2 hours ago), 2023-02-26 23:35:37 -0500
    [32m•[39m Engine revision 88b48c357b
    [32m•[39m Dart version 3.0.0 (build 3.0.0-275.0.dev)
    [32m•[39m DevTools version 2.22.1

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /Users/vuphuong/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14C18
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[32m[✓][39m Connected device (3 available)
    [32m•[39m macOS (desktop)  • macos      • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    [32m•[39m Web Server (web) • web-server • web-javascript • Flutter Tools
    [32m•[39m Chrome (web)     • chrome     • web-javascript • Google Chrome 110.0.5481.100

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9944297138845a94256f1cf37beb88ff9a8e811a
### Plugins
connectivity_plus-3.0.3
flutter_stripe-8.0.0+1
libphonenumber_plugin-0.2.5
libphonenumber_web-0.2.0+1
open_mail_app-0.4.5
path_provider-2.0.13
path_provider_android-2.0.23
path_provider_foundation-2.1.2
path_provider_linux-2.1.9
path_provider_windows-2.1.4
photo_manager-2.5.2
share_plus-6.3.1
shared_preferences-2.0.18
shared_preferences_android-2.0.16
shared_preferences_foundation-2.1.4
shared_preferences_linux-2.1.4
shared_preferences_web-2.0.5
shared_preferences_windows-2.1.4
sqflite-2.2.5
stripe_android-8.0.0+1
stripe_ios-8.0.0
url_launcher-6.1.10
url_launcher_android-6.0.24
url_launcher_ios-6.1.1
url_launcher_linux-3.0.3
url_launcher_macos-3.0.3
url_launcher_web-2.0.15
url_launcher_windows-3.0.4
video_player-2.5.2
video_player_android-2.3.11
video_player_avfoundation-2.3.9
video_player_web-2.0.14

**Comment by danagbemava-nc** [comment]
Hi @vxphuongictu,

What's the output of 
```
$ ls -la /Users/vuphuong/Desktop/food_e/ios
```
Are there two `.xcodeproj` directories in there?
