### ISSUE TITLE
Migrate Gradle plugin to Kotlin, away from Groovy

### ISSUE THREAD

**Issue by gnprice** [flutter/flutter#121541]
The Android Gradle Plugin team, when asked about the recurring flake #103230, said (per https://github.com/flutter/flutter/issues/103230#issuecomment-1125569034):
> it looks like a bug in Groovy's dynamic dispatch. If you invoke the method from something statically compiled (Java or Kotlin) you should be fine (or even just use @CompileStatic if you don't want to convert)
>
> For context, we got rid of all groovy production code in AGP many years ago for performance and correctness reasons

That sounds like a pretty clear recommendation that everyone else should do the same: migrate any production code written in Groovy (with the `.gradle` filename extension) either to Java, or to Kotlin (with `.gradle.kts`). When the AGP team did that migration "many years ago", Kotlin was young and the Gradle Kotlin DSL didn't exist, so they went for Java, but today the right choice is almost certainly Kotlin.

For Flutter, this means the files in `packages/flutter_tools/gradle/`, in particular `flutter.gradle`. These total about 1600 lines of code. An initial step was taken in #114660, moving a small piece of logic to a new `flutter.gradle.kts`.

Docs from Gradle upstream, on the Gradle Kotlin DSL (of `.gradle.kts` files) and on migrating to it:
https://docs.gradle.org/current/userguide/kotlin_dsl.html
https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html

This isn't urgent, and I don't think there's any need for it to be an immediate priority. Filing this so there's a clean issue to track it.

### Non-goals

A possible future step would be to migrate the `build.gradle` files generated by `flutter create` to be Kotlin files `build.gradle.kts` too. Then along with that, one should try to help migrate the `build.gradle` files in existing Flutter projects. These may also be good things to do, but can be left out of scope for this issue.

**Comment by gnprice** [comment]
> An initial step was taken in #114660, moving a small piece of logic to a new `flutter.gradle.kts`.

This step was targeted at the code that was flaking in #103230, but doesn't seem to have resolved the flake:
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_1_3/9476/overview

```
[        ] Script 'C:\b\s\w\ir\x\w\flutter\packages\flutter_tools\gradle\flutter.gradle.kts' line: 34
[        ] * What went wrong:
[        ] Failed to apply plugin class 'Flutter_gradle$FlutterPluginKts'.
[        ] > Comparison method violates its general contract!
[        ] * Try:
[        ] Run with --debug option to get more log output. Run with --scan to get full insights.
[        ] * Exception is:
[        ] org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin class 'Flutter_gradle$FlutterPluginKts'.
[        ] 	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:163)
[        ] 	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:141)
[        ] 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:170)
[        ] 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:154)
[        ] 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$100(DefaultObjectConfigurationAction.java:42)
[        ] 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$2.run(DefaultObjectConfigurationAction.java:86)
[        ] 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:183)
[        ] 	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:42)
[        ] 	at org.gradle.kotlin.dsl.support.CompiledKotlinBuildScript.apply(CompiledKotlinBuildScript.kt)
[        ] 	at Flutter_gradle.<init>(flutter.gradle.kts:34)
[        ] 	at Program.execute(Unknown Source)
[…]
```

I suspect this is because, even though the new code is in Kotlin, it's invoking Groovy dynamic dispatch:
```kt
        // Use withGroovyBuilder and getProperty() to access Groovy metaprogramming.
        project.withGroovyBuilder {
            getProperty("android").withGroovyBuilder {
```

So I think when pursuing this migration, a goal should be to avoid using `withGroovyBuilder` or other forms of Groovy dynamic dispatch, and convert the logic to be statically dispatched.

**Comment by reidbaker** [comment]
https://github.com/flutter/flutter/pull/118067 Is a starting attempt to use kotlin instead of groovy. 

I closed the pr because I dont think the team has the capacity to migrate our build tooling to kotlin.

**Comment by gnprice** [comment]
> #118067 Is a starting attempt to use kotlin instead of groovy.

Oh I see, and it's for the `build.gradle` files inside developers' individual Flutter projects. That PR falls into the "non-goals" section above. I agree that sounds like a sizable undertaking to support properly.

Migrating Flutter's own internal Gradle code to Kotlin (i.e., this issue) should be a smaller project than that, I think, because you have more control of all the pieces. And it's independent of migrating the `build.gradle` files inside Flutter projects, because Gradle's interoperability between languages is good (just like the AGP itself migrated all to Java a long time ago, while most developers write `build.gradle` files using it.)

To be clear, though, I'm not saying you should undertake this migration right now either. It probably isn't the right use of your team's capacity in the near term.

**Comment by bartekpacia** [comment]
Happy to see this being tracked.

I'd like to add that it'd be great if Flutter's Gradle Plugin could be applied using the [declarative plugins block](https://docs.gradle.org/current/userguide/plugins.html#plugins_dsl_limitations), so that developers would do:

```groovy
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "io.flutter.gradle.plugin" // possibly specify some version?
}
```

instead of current:

```groovy
plugins {
    id "com.android.application"
    id "kotlin-android"
}

// ...

apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

// ...
```

**Comment by gnprice** [comment]
> I'd like to add that it'd be great if Flutter's Gradle Plugin could be applied using the [declarative plugins block](https://docs.gradle.org/current/userguide/plugins.html#plugins_dsl_limitations), so that developers would do:

Yeah. This would be good to file as a separate issue.

Is there something the plugin itself needs to do differently to enable this, or is it just a matter of changing the `build.gradle` templates to do it that way? (But rather than answer that question here, please do so in the new issue you file :slightly_smiling_face: )

**Comment by reidbaker** [comment]
@bartekpacia can you file that as a separate feature request? 
I didnt know that was an option and it does seem like that might have some advantages but I would look at that independently of this issue.

**Comment by reidbaker** [comment]
> > #118067 Is a starting attempt to use kotlin instead of groovy.
> 
> Oh I see, and it's for the `build.gradle` files inside developers' individual Flutter projects. That PR falls into the "non-goals" section above. I agree that sounds like a sizable undertaking to support properly.
> 
> Migrating Flutter's own internal Gradle code to Kotlin (i.e., this issue) should be a smaller project than that, I think, because you have more control of all the pieces. And it's independent of migrating the `build.gradle` files inside Flutter projects, because Gradle's interoperability between languages is good (just like the AGP itself migrated all to Java a long time ago, while most developers use it from `build.gradle` files written in Groovy.)
> 
> To be clear, though, I'm not saying you should undertake this migration right now either. It probably isn't the right use of your team's capacity in the near term.

AH thanks for the clarification I see the difference now.

**Comment by stuartmorgan** [comment]
Isn't this a duplicate of https://github.com/flutter/flutter/issues/19625?

**Comment by reidbaker** [comment]
> Isn't this a duplicate of #19625?

I think it is but this is a better formatted bug and more clearly describes the scope.

**Comment by bartekpacia** [comment]
> can you file that as a separate feature request?

@reidbaker Sure, done in #121552 :)

**Comment by bartekpacia** [comment]
Is this something that could be contributed now? I'm interested in doing so.

**Comment by gnprice** [comment]
@bartekpacia Cool. I think a good first step that would definitely make sense to do now is to take the small piece of logic that's currently in Kotlin in `flutter.gradle.kts`, and try to fix that so that it uses proper Kotlin static dispatch instead of using Groovy APIs to keep doing dynamic dispatch. (As seen at https://github.com/flutter/flutter/issues/121541#issuecomment-1447002073 and https://github.com/flutter/flutter/issues/103230#issuecomment-1447020884 .)

That should fix the recurring flake #103230, which I think would make such a PR quite welcome.

Then as a bonus, it will mean that that code becomes more of a model of what we'd want the rest of the code in the Flutter Gradle plugin to look like if converted to Kotlin. So that would I think make it easier to gauge the idea of doing a larger conversion.

In order to know when you've successfully fixed the flake, it will be very helpful if you can find a way to reproduce it. That might be as simple as building a test app a bunch of times in a loop, or you might find that it requires more cleverness.

**Comment by reidbaker** [comment]
+1 to what @gnprice said. If you can make progress on https://github.com/flutter/flutter/issues/103230 that would be a welcome contribution.

**Comment by bartekpacia** [comment]
(in response to [this Discord comment](https://discord.com/channels/608014603317936148/846507907876257822/1180165883470032926))

I spent some time thinking about this issue and tinkering, and thought I'd share my thoughts in hope it will be helpful to anyone interested (but most likely @reidbaker).

The main problem with this task is **backward compatibility** w.r.t the existing project structure. Almost all existing Flutter apps depend on that structure, meaning they call:
- [`apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"`](https://github.com/flutter/flutter/blob/3.16.0/examples/flutter_view/android/app/build.gradle#L29) in `android/app/build.gradle`
- [`apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"`](https://github.com/flutter/flutter/blob/3.16.0/examples/flutter_view/android/settings.gradle#L21) in `android/settings.gradle`

As of 3.16.0, both `flutter.gradle` and `app_plugin_loader.gradle` are very simple:

https://github.com/flutter/flutter/blob/db7ef5bf9f59442b0e200a90587e8fa5e0c6336a/packages/flutter_tools/gradle/flutter.gradle#L5-L9

and:

https://github.com/flutter/flutter/blob/db7ef5bf9f59442b0e200a90587e8fa5e0c6336a/packages/flutter_tools/gradle/app_plugin_loader.gradle#L5-L9

**These 2 scripts above do not apply the plugin yet**. It's done in the respective plugin files, here:

https://github.com/flutter/flutter/blob/db7ef5bf9f59442b0e200a90587e8fa5e0c6336a/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L102-L106

and here:

https://github.com/flutter/flutter/blob/db7ef5bf9f59442b0e200a90587e8fa5e0c6336a/packages/flutter_tools/gradle/src/main/groovy/app_plugin_loader.groovy#L5-L7

This already hints at another but related problem: Groovy is much more dynamic and "laid back" than Kotlin. Things that we can do in Groovy (e.g. executing statements not inside a function – like those `apply` above) cannot be done in Kotlin.

We need to apply the same plugin both as a **script plugin** (old, imperative buildfiles, using `apply`) and **binary plugins** (new, declarative buildfiles, using `plugins {}` block). Actually, we are already doing this (i.e. it's already possible), but only because we were kind of lucky I'd say - the plugin is written in Groovy, and support for Groovy is built into Gradle. But if we were to migrate the plugins to Kotlin, we'd have to apply the Kotlin Gradle Plugin. It seems like an easy feat: just add a dependency on `kotln plugn` here:

https://github.com/flutter/flutter/blob/db7ef5bf9f59442b0e200a90587e8fa5e0c6336a/packages/flutter_tools/gradle/build.gradle.kts#L28-L34

Well, no. This will work only for Flutter apps that include the Gradle plugins declaratively (aka use the binary plugin, aka use the `plugins {}` block). Flutter apps that include the Gradle plugins imperatively (aka use the script plugin, aka use the `apply` function) will not get this dependency, and the build will fail for them.

And that's the hard thing to solve. While playing around, I was not able to accomplish this. It looks like this use-case is not supported by Gradle at all.

See also
- [Gradle docs about plugin types](https://docs.gradle.org/current/userguide/plugins.html#sec:types_of_plugins)

### How can we solve it?

**The simplest solution** I see is to force the ecosystem (read: Flutter apps) to migrate to use declarative apply of these 2 Gradle plugins. This will require:
1. Writing documentation – I already started tracking it in #135392 and doing it in https://github.com/flutter/website/pull/9857
2. Adding a simple print to these temporary files ([`flutter.gradle`](https://github.com/flutter/flutter/blob/3.16.0/packages/flutter_tools/gradle/flutter.gradle) and [`app_plugin_loader.gradle`](https://github.com/flutter/flutter/blob/3.16.0/packages/flutter_tools/gradle/app_plugin_loader.gradle))

One of main strengths of the declarative plugin apply is the additional level of indirection. With declarative plugin apply app's buildfiles no longer say "apply plugin from script /path/to/flutter.gradle` as they did in imperative apply - instead, they say "apply plugin flutter-gradle-plugin". This will let us write the plugin in basically any JVM language, split it easily into many files – in short, it's gonna be a proper Gradle plugin (also called a binary plugin).

Also @reidbaker you said on Discord:

> #121541 in our plan for 2024 
ou plan to do this in 2024. I'd be very happy to help you with this, or maybe even . Christmas is coming and I'll have more free time to play around with this.

**Comment by reidbaker** [comment]
Execution plan for this is to start by following the guidance here for what to do before converting. Then if there are areas where we can break out existing groovy code into seperate files we would do that in a different pr than one doing the conversion. 

Also we expect this work to make build time slower because kotlin is slower than groovy for builds. 

https://discord.com/channels/608014603317936148/846507907876257822/1187060608378617889

**Comment by reidbaker** [comment]
Advice from discord: 

* Migrate away from all legacy or deprecated Gradle functionality first. Like the old tasks API, old plugin application mechanism, etc. There might be other best practices to verify you're following first too.
* I'd consider having someone do a full pass of the plugin's Groovy implementation and just cleaning it up in a consistent style. Format it, remove any unnecessary portions, add some comments about confusing functionality or parts to be careful about during the migration, etc. I believe there's a guide on syntax changes you can make for it to be closer to Kotlin as well, but that's not super impactful. The same can be done for any existing Gradle scripts too.
* Set up formatting/linting for running locally and in CI first. If the plugins repo uses something, just match that. That way any discussion around that can be avoided. I'd hope the format
* I'd have a single place to document pain points, questions, tips, etc while completing the migration. While I mostly touched it when the DSL was brand new, it was very finicky and kept experiencing some surprises.  Definitely clearly document how to develop locally :)

**Comment by asaarnak** [comment]
My results from converting my app to kotlin.
Used flutter 3.16.5 and gradle 8.5.

1. Running `myApp/android` from Android Studio launches app. 
    Gradle prints: `Executing tasks: [:app:assembleDevelopmentDebug]`
2. Running `myApp` with `flutter run` gives this error:
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. To migrate
your project, follow the steps at:

https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  No `/myUser/myApp/android/AndroidManifest.xml` file
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Build failed due to use of deprecated Android v1 embedding.
```

`settings.gradle.kts`
```kotlin
pluginManagement {
    val flutterSdkPath = {
        val properties = java.util.Properties()
        file("local.properties").let { properties.load(it.inputStream()) }
        val flutterSdkPath = properties.getProperty("flutter.sdk")
        assert(flutterSdkPath != null) { "flutter.sdk not set in local.properties" }
        flutterSdkPath
    }
    settings.extensions.add("flutterSdkPath", flutterSdkPath())

    includeBuild("${settings.extensions["flutterSdkPath"]}/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("dev.flutter.flutter-plugin-loader") version "1.0.0"
    id("com.android.application") version "8.3.0-alpha18" apply false
    id("org.jetbrains.kotlin.android") version "1.9.22" apply false
    id("com.google.gms.google-services") version "4.4.0" apply false
    id("com.google.firebase.crashlytics") version "2.9.9" apply false
    id("com.google.firebase.firebase-perf") version "1.4.2" apply false
}

include(":app")
```

`build.gradle.kts`
```kotlin
rootProject.layout.buildDirectory.dir("../build")

subprojects {
    project.layout.buildDirectory.dir("${rootProject.layout.buildDirectory}/${project.name}")
    project.evaluationDependsOn(":app")
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
```

`app/build.gradle.kts`
```kotlin
import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    id("kotlin-android")
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
    id("com.google.firebase.crashlytics")
    id("com.google.firebase.firebase-perf")
}

val localProperties = Properties()
val localPropertiesFile = rootProject.file("local.properties")
localPropertiesFile.inputStream().bufferedReader(Charsets.UTF_8).use { inputStream ->
    localProperties.load(inputStream)
}

var flutterVersionCode = localProperties.getProperty("flutter.versionCode") ?: "1"
var flutterVersionName = localProperties.getProperty("flutter.versionName") ?: "1.0"

val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "com.myapp.myapp"
    compileSdk = 34

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    sourceSets {
        named("main") {
            java.srcDir("src/main/kotlin")
        }
    }

    defaultConfig {
        applicationId = "com.myapp.myapp"
        minSdk = 30
        targetSdk = 34
        versionCode = flutterVersionCode.toInt()
        versionName = flutterVersionName
    }

    signingConfigs {
        create("release") {
            keyAlias =
                if (keystorePropertiesFile.exists()) keystoreProperties["keyAlias"] as String else null
            keyPassword =
                if (keystorePropertiesFile.exists()) keystoreProperties["keyPassword"] as String else null
            storeFile =
                if (keystorePropertiesFile.exists()) file(keystoreProperties["storeFile"] as String) else null
            storePassword =
                if (keystorePropertiesFile.exists()) keystoreProperties["storePassword"] as String else null
        }
    }

    flavorDimensions += "default"
    productFlavors {
        create("production") {
            dimension = "default"
            applicationIdSuffix = ""
            manifestPlaceholders += mapOf(
                "appName" to "MyApp",
                "googleApiKey" to "....."
            )
        }
        create("staging") {
            dimension = "default"
            applicationIdSuffix = ".stg"
            manifestPlaceholders += mapOf(
                "appName" to "MyApp Staging",
                "googleApiKey" to "....."
            )
        }
        create("development") {
            dimension = "default"
            applicationIdSuffix = ".dev"
            manifestPlaceholders += mapOf(
                "appName" to "MyApp Development",
                "googleApiKey" to "...."
            )
        }
    }

    buildTypes {
        named("release") {
            signingConfig = signingConfigs.getByName("release")
            ndk {
                debugSymbolLevel = "FULL"
            }
        }
        named("debug") {
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

flutter {
    source = "../.."
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")
}
```

**Comment by asaarnak** [comment]
Flutter tools currently check `build.gradle` file only.
Maybe we could create new issue to support both `build.gradle` and `build.gradle.kts` in flutter tools and second follow up issue to enable `flutter create` migration to kotlin?
https://github.com/flutter/flutter/blob/ede594f8816f8c0e5a390f5bbb636b4dcaf55f62/packages/flutter_tools/lib/src/project.dart#L654-L656
Some more places where `build.gradle` is hardcoded:
https://github.com/flutter/flutter/blob/ede594f8816f8c0e5a390f5bbb636b4dcaf55f62/packages/flutter_tools/lib/src/project.dart#L558
https://github.com/flutter/flutter/blob/ede594f8816f8c0e5a390f5bbb636b4dcaf55f62/packages/flutter_tools/lib/src/project.dart#L674

**Comment by reidbaker** [comment]
> Flutter tools currently check `build.gradle` file only. Maybe we could create new issue to support both `build.gradle` and `build.gradle.kts` in flutter tools and second follow up issue to enable `flutter create` migration to kotlin?
> 
> https://github.com/flutter/flutter/blob/ede594f8816f8c0e5a390f5bbb636b4dcaf55f62/packages/flutter_tools/lib/src/project.dart#L654-L656
> 
> 
> Some more places where `build.gradle` is hardcoded:
> https://github.com/flutter/flutter/blob/ede594f8816f8c0e5a390f5bbb636b4dcaf55f62/packages/flutter_tools/lib/src/project.dart#L558
> 
> 
> https://github.com/flutter/flutter/blob/ede594f8816f8c0e5a390f5bbb636b4dcaf55f62/packages/flutter_tools/lib/src/project.dart#L674

Thank you for this comment. I filed https://github.com/flutter/flutter/issues/140548. 

https://github.com/flutter/flutter/issues/93238#issuecomment-973158259 might have temporary work around for you.

**Comment by gmackall** [comment]
The dependency version checking in https://github.com/flutter/flutter/pull/142000 is implemented as an additional plugin (to be able to call it from groovy), but as part of this migration we should move it to a simple import

**Comment by bartekpacia** [comment]
(posting some my thoughts here so it's accessible to everyone)

Both `FlutterPlugin` and `FlutterAppPluginLoaderPlugin` depend on `NativePluginLoader` "plugin".

It's a "plugin" only for historical reasons that no longer apply. In reality, it's a singleton (or could be thought of as just a bunch of global functions in Kotlin).

I converted `FlutterAppPluginLoaderPlugin` into `.kt`, but then I wasn't able to import `NativePluginLoader` (written in Groovy) into it (`app_plugin_loader.kt: Unresolved reference NativePluginLoader`). [This article](https://medium.com/whozapp/make-kotlin-and-groovy-work-together-ffcb4aee2191) says "Unlike Groovy and Java, or Kotlin and Java, mixing Kotlin and Groovy is not seamless". But maybe I did something wrong.

However I think it's best to convert `NativePluginLoader` to `.kt` first (as it's a leaf class), and then go up from it.

**Comment by kamaravichow** [comment]
I personally don't like Kotlin DSL

**Comment by bartekpacia** [comment]
This issue is not about what you will use as an app developer; it's about rewriting the Flutter Gradle Plugin's implementation.

As an app developer, you won't notice any difference.

**Comment by gmackall** [comment]
Will be completed by https://github.com/flutter/flutter/pull/166114
