### ISSUE TITLE
cannot connect to "android.googlesource.com"

### ISSUE THREAD

**Issue by haogg** [flutter/flutter#12162]
## Steps to Reproduce

In China, run the command "flutter doctor"

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

SocketException: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = android.googlesource.com, port = 51405

```
#0      fetchUrl (package:flutter_tools/src/base/net.dart:18)
<asynchronous suspension>
#1      _downloadFile (package:flutter_tools/src/cache.dart:405)
<asynchronous suspension>
#2      _downloadZippedTarball.<anonymous closure> (package:flutter_tools/src/cache.dart:421)
<asynchronous suspension>
#3      _withTemporaryFile (package:flutter_tools/src/cache.dart:433)
<asynchronous suspension>
#4      _downloadZippedTarball (package:flutter_tools/src/cache.dart:420)
#5      GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:394)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:223)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:196)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:225)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#16     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#25     main (file:///D:/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 6.1.7601], locale zh-CN, channel alpha)
    • Flutter at D:\flutter\flutter
    • Framework revision 701d534ba9 (6 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at D:\Android\sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: E:\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at E:\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • MI 5s • b17280b3 • android-arm • Android 7.0 (API 24)

```

**Comment by eseidelGoogle** [comment]
This looks like https://github.com/flutter/flutter/issues/11681.
