### ISSUE TITLE
demo run failed

### ISSUE THREAD

**Issue by mehao** [flutter/flutter#12163]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build flx --suppress-analytics --target lib/main.dart --output-file D:\flutter\examples\hello_world\build\app\intermediates\flutter\debug/app.flx --snapshot D:\flutter\examples\hello_world\build\app\intermediates\flutter\debug/snapshot_blob.bin --depfile D:\flutter\examples\hello_world\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --working-dir D:\flutter\examples\hello_world\build\app\intermediates\flutter\debug/flx

## exception

SocketException: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = android.googlesource.com, port = 64226

```
#0      fetchUrl (package:flutter_tools/src/base/net.dart:18)
<asynchronous suspension>
#1      _downloadFile (package:flutter_tools/src/cache.dart:405)
<asynchronous suspension>
#2      _downloadZippedTarball.<anonymous closure> (package:flutter_tools/src/cache.dart:421)
<asynchronous suspension>
#3      _withTemporaryFile (package:flutter_tools/src/cache.dart:433)
<asynchronous suspension>
#4      _downloadZippedTarball (package:flutter_tools/src/cache.dart:420)
#5      GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:394)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:223)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:196)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:225)
<asynchronous suspension>
#9      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     new Future.sync (dart:async/future.dart:222)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#17     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1467)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#26     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 10.0.15063], locale zh-CN, channel master)
    • Flutter at D:\flutter
    • Framework revision 2859a563ce (11 hours ago), 2017-09-18 14:55:20 -0700
    • Engine revision 82fb559566
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at D:\SDK
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = D:\SDK\platform-tools;D:\SDK\tools
    • Java binary at: F:\android-studio-ide-171.4195411-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at C:\android-studio\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 3.0)
    • Android Studio at F:\android-studio-ide-171.4195411-windows\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[-] IntelliJ IDEA Ultimate Edition (version 2017.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • MIX • a8331689 • android-arm • Android 6.0.1 (API 23)

```

**Comment by eseidelGoogle** [comment]
This looks like https://github.com/flutter/flutter/issues/11681
