### ISSUE TITLE
Surface was abandoned in Camera Package

### ISSUE THREAD

**Issue by prash4931** [flutter/flutter#121780]
```
D/AndroidRuntime(31457): Shutting down VM
E/AndroidRuntime(31457): FATAL EXCEPTION: main
E/AndroidRuntime(31457): Process: com.example.flutter_quikgate, PID: 31457
E/AndroidRuntime(31457): java.lang.IllegalArgumentException: Surface was abandoned
E/AndroidRuntime(31457): 	at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:89)
E/AndroidRuntime(31457): 	at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:260)
E/AndroidRuntime(31457): 	at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:145)
E/AndroidRuntime(31457): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:464)
E/AndroidRuntime(31457): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:390)
E/AndroidRuntime(31457): 	at io.flutter.plugins.camera.Camera.startPreview(Camera.java:1077)
E/AndroidRuntime(31457): 	at io.flutter.plugins.camera.Camera$1.onOpened(Camera.java:325)
E/AndroidRuntime(31457): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:149)
E/AndroidRuntime(31457): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(31457): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31457): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(31457): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(31457): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31457): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(31457): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime(31457): Caused by: android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
E/AndroidRuntime(31457): 	at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:73)
E/AndroidRuntime(31457): 	at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:606)
E/AndroidRuntime(31457): 	at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:87)
E/AndroidRuntime(31457): 	... 14 more
I/Process (31457): Sending signal. PID: 31457 SIG: 9
```

**Comment by darshankawar** [comment]
@prash4931 
Can you provide `flutter doctor -v` and complete minimal reproducible code sample along with steps to replicate that leads to this error log ?

Maybe similar to https://github.com/flutter/flutter/issues/97076
