### ISSUE TITLE
[image_picker] Invalid file name for chosen png files

### ISSUE THREAD

**Issue by reimager** [flutter/flutter#121878]
My android app now fails to load png chosen from the library using the image picker
It appears the path has changed in 0.8.5+8 image_picker_android and now appends ".jpg" even when its an ".png" file

The code:
XFile? file = await ImagePicker().pickImage(source: ImageSource.gallery);
...
imglib.Command cmd = imglib.Command()
  ..decodeImageFile(file.path)
  ..bakeOrientation()
  ..encodePngFile(newImagePath);
await cmd.executeThread();

Good config:
 image_picker_android: 0.8.5+7
Debug output:
I/flutter ( 6460): Loading Image /data/user/0/app.reimage/cache/image_picker2780929013025073694.png

Bad config:
 image_picker_android: 0.8.5+8
Debug output:
I/flutter ( 6927): Loading image /data/user/0/app.reimage/cache/054874a4-f2d8-4a15-b777-2fe505469ded/1000000070.jpg
...
E/flutter ( 4584): ImageException: Start Of Image marker not found.
E/flutter ( 4584): #0      JpegData._read (package:image/src/formats/jpeg/jpeg_data.dart:181:7)
E/flutter ( 4584): #1      JpegData.read (package:image/src/formats/jpeg/jpeg_data.dart:154:5)
E/flutter ( 4584): #2      JpegDecoder.decode (package:image/src/formats/jpeg_decoder.dart:44:30)
E/flutter ( 4584): #3      decodeImageFile (package:image/src/formats/formats.dart:204:20)
E/flutter ( 4584): <asynchronous suspension>
E/flutter ( 4584): #4      DecodeImageFileCmd.executeCommand (package:image/src/command/formats/decode_image_file_cmd.dart:12:19)
...

The exception is because its not a jpg, but a png.
According to the photos app and "My Files" the name is 1677861994058.png
Something in 0.8.5+8 has changed the location and name of the file path in the cache of the chosen image

This is the change in question:
https://github.com/flutter/packages/commit/1e396f9d711f1a53ae1ed8402450acd2391513d5

I believe the issue lies in the getImageName() method, as the cache filepath does not include the string "image_picker"
I don't know why/how getImageName() is returning 1000000070.jpg
I cant find any file named this, not sure where that is coming from.

@SynSzakala

**Comment by huycozy** [comment]
Thanks for filing the issue. This issue is reproducible on the latest plugin version: 

image_picker: ^0.8.6+4
image_picker_android: ^0.8.5+9

Using plugin sample code at: https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker_android/example


This may not be consistent with issue #91397 (where the expected result is returning HEIC image instead of jpg, see https://github.com/flutter/flutter/issues/91397#issuecomment-944906222)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.7.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (4 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.9.0-1.0.pre.49, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.9.0-1.0.pre.49 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 95387c6621 (25 hours ago), 2023-03-04 16:59:14 -0800
    • Engine revision de724e2632
    • Dart version 3.0.0 (build 3.0.0-290.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by SynSzakala** [comment]
Hi @reimager, I'll look into it!

**Comment by stuartmorgan** [comment]
This does indeed look like a regression from https://github.com/flutter/plugins/pull/6096. Most likely the image is being re-encoded, but the old filename is being used directly. If so we should instead keep the basename, but set the extension from `getImageExtension` as before.

/cc @gmackall as the code owner here to make sure this gets resolved.

**Comment by SynSzakala** [comment]
@stuartmorgan Created a PR which implements your recommendation. Also handling an additional edge case where we have the name from `ContentResolver` but mime-based extension cannot be detected - in this case we stick with the extension returned from `ContentResolver` instead of falling back to `.jpg` as previously. LMK if you think this is a good idea.
