### ISSUE TITLE
arm64 linux fails to build from source 3.7.6 on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by xnox** [flutter/flutter#121844]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Attempt to build flutter as part of the ubuntu-desktop-installer on arm64

full build log

[buildlog_snap_ubuntu_focal_arm64_ubuntu-desktop-installer_BUILDING.txt](https://github.com/flutter/flutter/files/10877196/buildlog_snap_ubuntu_focal_arm64_ubuntu-desktop-installer_BUILDING.txt)

Error snippets also in the logs section

```console
Compilation to SkSL failed.
flutter/lib/src/material/shaders/ink_sparkle.frag: GLSL to SPIRV failed; Compilation error. 3 error(s) and 1 warning(s).
flutter/lib/src/material/shaders/ink_sparkle.frag: warning: (version, profile) forced to be (460, core), while in source code it is (320, es)
flutter/lib/src/material/shaders/ink_sparkle.frag:9: error: '#include' : Included file not found. for header name: flutter/runtime_effect.glsl
flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: 'FlutterFragCoord' : no matching overloaded function found
flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: '=' :  cannot convert from ' const float' to ' temp 2-component vector of float'
```

### Actual results

failure to build.

last successful build was done with 3.3.x series

### Logs

<details>
<summary>Logs</summary>

```console
[        ] [ +173 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +4 ms] [  +31 ms] shaderc command: [/build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/bin/cache/artifacts/engine/linux-arm64/impellerc, --sksl, --iplr, --sl=/build/ubuntu-desktop-installer/parts/ubuntu-desktop-installer/build/packages/ubuntu_desktop_installer/build/flutter_assets/shaders/ink_sparkle.frag, --spirv=/build/ubuntu-desktop-installer/parts/ubuntu-desktop-installer/build/packages/ubuntu_desktop_installer/build/flutter_assets/shaders/ink_sparkle.frag.spirv, --input=/build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag, --remap-samplers, --include=/build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders, --include=/build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/bin/cache/artifacts/engine/linux-arm64/shader_lib]
[        ] [ +170 ms] Compilation to SkSL failed.
[        ]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: GLSL to SPIRV failed; Compilation error. 3 error(s) and 1 warning(s).
[   +1 ms]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: warning: (version, profile) forced to be (460, core), while in source code it is (320, es)
[   +5 ms]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:9: error: '#include' : Included file not found. for header name: flutter/runtime_effect.glsl
[        ]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: 'FlutterFragCoord' : no matching overloaded function found
[        ]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: '=' :  cannot convert from ' const float' to ' temp 2-component vector of float'
[        ] [   +8 ms] Persisting file store
[        ] [  +13 ms] Done persisting file store
[        ] [  +14 ms] Target release_bundle_linux-arm64_assets failed: ShaderCompilerException: Shader compilation of "/build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag" to "/build/ubuntu-desktop-installer/parts/ubuntu-desktop-installer/build/packages/ubuntu_desktop_installer/build/flutter_assets/shaders/ink_sparkle.frag" failed with exit code 1.
[        ]            impellerc stdout:
[        ]            impellerc stderr:
[        ]            Compilation to SkSL failed.
[        ]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: GLSL to SPIRV failed; Compilation error. 3 error(s) and 1 warning(s).
[        ]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: warning: (version, profile) forced to be (460, core), while in source code it is (320, es)
[        ]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:9: error: '#include' : Included file not found. for header name: flutter/runtime_effect.glsl
[        ]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: 'FlutterFragCoord' : no matching overloaded function found
[        ]            /build/ubuntu-desktop-installer/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: '=' :  cannot convert from ' const float' to ' temp 2-component vector of float'
[        ]            #0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:202:9)
[        ]            <asynchronous suspension>
[        ]            #1      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:127:25)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[        ]            <asynchronous suspension>
[        ]            #3      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:98:3)
[        ]            <asynchronous suspension>
[        ]            #4      BundleLinuxAssets.build (package:flutter_tools/src/build_system/targets/linux.dart:141:29)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
[        ]            <asynchronous suspension>
[        ]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:337:32)
[   +3 ms]            <asynchronous suspension>
[        ]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[        ]            <asynchronous suspension>
[        ]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #16     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +10 ms] "flutter assemble" took 83,404ms.
[        ] [   +4 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:354:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [        ] ensureAnalyticsSent: 0ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[  +10 ms] Building Linux application... (completed in 87.4s)
[   +1 ms] "flutter linux" took 93,507ms.
[   +5 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:183:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:76:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:86:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[        ] ensureAnalyticsSent: 0ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
Failed to run 'override-build': Exit code was 1.
Build failed
```

```

</details>


### Flutter Doctor output

as build failed, i do not have doctor output.

**Comment by darshankawar** [comment]
@xnox 
This looks similar to https://github.com/flutter/flutter/issues/116703, so please follow-up in it for further updates. I see that you have already commented in that issue.

Please do leave a thumbs up on the original author's post so we can track and prioritize the issue base on severity and demand. Thanks!
