### ISSUE TITLE
Run Flutter application on Androidbox name is MXQ4K Pro 

### ISSUE THREAD

**Issue by MistryBhavesh1997** [flutter/flutter#121923]
```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#61df2(logicalKey: LogicalKeyboardKey#0050c(keyId: "0x10000050c", keyLabel: "Select", debugName: "Select"), physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName: "Control Right"), repeat: false) and its data: RawKeyEventDataAndroid#59aba(flags: 8, codePoint: 0, plainCodePoint: 0, keyCode: 23, scanCode: 97, metaState: 0)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 682 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:682:7)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:878:30)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#6      _invoke2 (dart:ui/hooks.dart:186:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by darshankawar** [comment]
@MistryBhavesh1997 
Looking at error log, it looks similar to https://github.com/flutter/flutter/issues/101275, so follow-up in that issue for further updates.

Please do leave a thumbs up on the original author's post so we can track and prioritize the issue base on severity and demand. Thanks!
