### ISSUE TITLE
`SnapshotWidget` doesn't capture images

### ISSUE THREAD

**Issue by adil192** [flutter/flutter#121938]
## Steps to Reproduce

I've written a test for this (inspired by https://github.com/flutter/flutter/issues/114398#issuecomment-1298349198) in the "Code sample" section. You'll probably need to change the location of the image, but for completeness the one I've used is here: https://github.com/adil192/saber/blob/main/assets/icon/resized/icon-128x128.png

**Expected results:**
The image should be snapshotted.

**Actual results:** 
The snapshot is blank.

<details>
<summary>Code sample</summary>

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('SnapshotWidget should have same result when enabled', (tester) async {
    final controller = SnapshotController(allowSnapshotting: false);

    await tester.pumpWidget(MaterialApp(
      home: Center(
        child: SnapshotWidget(
          controller: controller,
          child: Image.asset('assets/icon/resized/icon-128x128.png'),
        ),
      ),
    ));

    // wait for image to load
    await tester.runAsync(() => Future.delayed(const Duration(milliseconds: 100)));

    final imageWhenDisabled = await _captureImage(tester.element(find.byType(MaterialApp)));

    controller.allowSnapshotting = true;
    await tester.pumpAndSettle();

    final imageWhenEnabled = await _captureImage(tester.element(find.byType(MaterialApp)));
    await expectLater(imageWhenEnabled, matchesReferenceImage(imageWhenDisabled));
  });
}

Future<ui.Image> _captureImage(Element element) {
  assert(element.renderObject != null);
  RenderObject renderObject = element.renderObject!;
  while (!renderObject.isRepaintBoundary) {
    renderObject = renderObject.parent! as RenderObject;
  }
  assert(!renderObject.debugNeedsPaint);
  final OffsetLayer layer = renderObject.debugLayer! as OffsetLayer;
  return layer.toImage(renderObject.paintBounds);
}
```

</details>

<details>
  <summary>Logs</summary>

```
adil@pop-os:~/StudioProjects/saber$ flutter test -r expanded test/snapshot_widget_of_image_test.dart 
00:00 +0: SnapshotWidget should have same result when enabled
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: rasterized image matches that of a [2400×1800] reference image
  Actual: Image:<[2400×1800]>
   Which: does not match on 127581 pixels

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _expect.<anonymous closure> (package:test_api/src/expect/expect.dart:109:9)
<asynchronous suspension>
<asynchronous suspension>
(elided 6 frames from dart:async and package:stack_trace)

The test description was:
  SnapshotWidget should have same result when enabled
════════════════════════════════════════════════════════════════════════════════════════════════════
00:00 +0 -1: SnapshotWidget should have same result when enabled [E]
  Test failed. See exception logs above.
  The test description was: SnapshotWidget should have same result when enabled
  
00:00 +0 -1: Some tests failed.
```

```
adil@pop-os:~/StudioProjects/saber$ flutter analyze test/snapshot_widget_of_image_test.dart 
Analyzing snapshot_widget_of_image_test.dart...                         
No issues found! (ran in 0.9s)
```

```
adil@pop-os:~/StudioProjects/saber$ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.6, on Pop!_OS 22.04 LTS 6.1.11-76060111-generic, locale en_GB.UTF-8)
    • Flutter version 3.7.6 on channel stable at /home/adil/Documents/Sources/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (3 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/adil/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/adil/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/223.7571.182.2231.9569140/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.5+0-17.0.5b762.1-9522829)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /home/adil/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/223.7571.182.2231.9569140
    • Flutter plugin version 72.1.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.5+0-17.0.5b762.1-9522829)

[✓] VS Code (version 1.75.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 22.04 LTS 6.1.11-76060111-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### Screenshots

I'm experimenting with using `SnapshotWidget` to invert the colors of images in https://github.com/adil192/saber. While debugging, I replaced the actual images with a placeholder of the Saber icon, and the snapshot is still blank.

![image](https://user-images.githubusercontent.com/21128619/222905987-b93031e2-e6ff-49de-9d0b-a6439737d9a6.png) ![image](https://user-images.githubusercontent.com/21128619/222905990-9b364eba-163c-40a4-9793-e5089d93ee60.png)

**Comment by jonahwilliams** [comment]
snapshot widget _does_ capture images, however what I suspect is happening is that when you take the snapshot the image has not yet loaded (it takes about a frame). So it will be blank in the result.

You could verify this by using the loadingBuilder with a sentinel

**Comment by adil192** [comment]
> the image has not yet loaded (it takes about a frame). So it will be blank in the result.

That's why I added in this line:
```dart
// wait for image to load
await tester.runAsync(() => Future.delayed(const Duration(milliseconds: 100)));
```
Without this delay, the test passes as both the before and after are just blank. 

***

> You could verify this by using the loadingBuilder with a sentinel

The `Image.asset` constructor doesn't accept a `loadingBuilder` argument as I assume it loads quickly enough not to need it.
But switching to the `Image` constructor (with `image: AssetImage(...)`) and providing a `loadingBuilder` doesn't change the result of the test.
```dart
child: SnapshotWidget(
  controller: controller,
  child: Image(
    image: const AssetImage('assets/icon/resized/icon-128x128.png'),
    loadingBuilder: (context, child, loadingProgress) {
      return const CircularProgressIndicator();
    },
  ),
),
```

**Comment by jonahwilliams** [comment]
Image.asset is asynchronous, all image loading is asynchronous unless you've precached the image. You're tester runAsync line also won't do anything - you need to use that callback to precache the image

**Comment by adil192** [comment]
> You're tester runAsync line also won't do anything 

Please can you explain more about this? The test passes without this as the image isn't loaded yet, but passes with this because the image is loaded. This can be verified with something like `flutter run test/snapshot_widget_of_image_test.dart`

**Comment by jonahwilliams** [comment]
I guess the timeout does seem to work but IMO that's a bit risky.  Here is a modified test that writes two files which shows the images are there as you'd expect. The difference is that there is a subtle pixel snap that is required to ensure that the rasterized image doesn't look fuzzy. Provided you're only using these to apply to quick animations, I don't particularly think that's a huge problem but YMMV

```dart
import 'dart:async';
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('SnapshotWidget should have same result when enabled', (tester) async {
    // wait for image to load
    await tester.runAsync(() async {
      var completer = Completer<void>();
      var listener = ImageStreamListener((image, synchronousCall) {
        completer.complete();
      });
      AssetImage('assets/img.png').resolve(ImageConfiguration.empty).addListener(listener);
      await completer.future;
    });

    final controller = SnapshotController(allowSnapshotting: false);

    await tester.pumpWidget(MaterialApp(
      home: Center(
        child: SnapshotWidget(
          controller: controller,
          child: Image.asset('assets/img.png'),
        ),
      ),
    ));
    await tester.pump();

    final imageWhenDisabled = await _captureImage(tester.element(find.byType(MaterialApp)));

    controller.allowSnapshotting = true;
    await tester.pump();
    await tester.pumpAndSettle();

    final imageWhenEnabled = await _captureImage(tester.element(find.byType(MaterialApp)));

    await tester.runAsync(() async {
      File('a.png').writeAsBytesSync((await imageWhenDisabled.toByteData(format: ui.ImageByteFormat.png))!.buffer.asUint8List());
      File('b.png').writeAsBytesSync((await imageWhenEnabled.toByteData(format: ui.ImageByteFormat.png))!.buffer.asUint8List());
    });

    await expectLater(imageWhenEnabled, matchesReferenceImage(imageWhenDisabled));
  });
}

Future<ui.Image> _captureImage(Element element) {
  assert(element.renderObject != null);
  RenderObject renderObject = element.renderObject!;
  while (!renderObject.isRepaintBoundary) {
    renderObject = renderObject.parent! as RenderObject;
  }
  assert(!renderObject.debugNeedsPaint);
  final OffsetLayer layer = renderObject.debugLayer! as OffsetLayer;
  return layer.toImage(renderObject.paintBounds);
}
```

**Comment by adil192** [comment]
Looks like you're right. Would you recommend running `ImageProvider.resolve` before snapshotting in a real application?

**Comment by jonahwilliams** [comment]
I would just use precacheImage, I only used resolve directly for the test since there is no build context

**Comment by jonahwilliams** [comment]
maybe the build context for precacheImage should be optional

**Comment by adil192** [comment]
Thanks for your help
