### ISSUE TITLE
[shared_preferences] built error in web mode

### ISSUE THREAD

**Issue by yingshaoxo** [flutter/flutter#121928]
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (3 months ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

```bash
Launching lib/main.dart on Chrome in debug mode...
main.dart:1
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:shared_preferences_web
 - package:shared_preferences_platform_interface

For solutions, see https://dart.dev/go/unsound-null-safety

Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:484:9)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:153:33)
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:705:47)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:612:9)
<asynchronous suspension>
#4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1210:11)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
Failed to compile application.
Exited
```

**Comment by stuartmorgan** [comment]
All of the component packages of `shared_preferences` have supported null safety since the app-facing package has. You need to run `flutter pub upgrade`, since you are running versions that are more than two years old.
