### ISSUE TITLE
video_player live stream stops after some time with below error , 

### ISSUE THREAD

**Issue by MRafiqAsim** [flutter/flutter#122025]
https://pub.dev/packages/video_player

```
E/ExoPlayerImplInternal(20448): Playback error
E/ExoPlayerImplInternal(20448):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:606)
E/ExoPlayerImplInternal(20448):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(20448):       at android.os.Looper.loop(Looper.java:154)
E/ExoPlayerImplInternal(20448):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(20448):   Caused by: com.google.android.exoplayer2.source.BehindLiveWindowException
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:440)
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:762)
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:386)
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.continueLoading(MaskingMediaPeriod.java:226)
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:221)
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:2292)
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:2255)
E/ExoPlayerImplInternal(20448):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:512)
E/ExoPlayerImplInternal(20448):       ... 3 more
I/ACodec  (20448): [OMX.Exynos.avc.dec] signalFlush
I/ACodec  (20448): [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 5/5 input, 0/15 output).
I/ACodec  (20448): [OMX.Exynos.avc.dec] Now Flushing
I/ACodec  (20448): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
I/ACodec  (20448): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
I/ACodec  (20448): [OMX.Exynos.avc.dec] Now Executing
I/ACodec  (20448): [OMX.google.aac.decoder] signalFlush
I/ACodec  (20448): [OMX.google.aac.decoder] ExecutingState flushing now (codec owns 4/4 input, 0/4 output).
I/ACodec  (20448): [OMX.google.aac.decoder] Now Flushing
I/ACodec  (20448): [OMX.google.aac.decoder] FlushingState onOMXEvent(0,1,0)
I/ACodec  (20448): [OMX.google.aac.decoder] FlushingState onOMXEvent(0,1,1)
I/ACodec  (20448): [OMX.google.aac.decoder] Now Executing
I/ACodec  (20448): [OMX.Exynos.avc.dec] Now Executing->Idle
I/ACodec  (20448): [OMX.Exynos.avc.dec] Now Idle->Loaded
I/ACodec  (20448): [OMX.Exynos.avc.dec] Now Loaded
I/ACodec  (20448):  [OMX.Exynos.avc.dec] Now uninitialized
I/ACodec  (20448):  [] Now kWhatShutdownCompleted event : 8445
I/MediaCodec(20448): Codec shutdown complete
I/ACodec  (20448): [OMX.google.aac.decoder] Now Executing->Idle
I/ACodec  (20448): [OMX.google.aac.decoder] Now Idle->Loaded
I/ACodec  (20448): [OMX.google.aac.decoder] Now Loaded
I/ACodec  (20448):  [OMX.google.aac.decoder] Now uninitialized
I/ACodec  (20448):  [] Now kWhatShutdownCompleted event : 8445
I/MediaCodec(20448): Codec shutdown complete
```

**Comment by darshankawar** [comment]
@MRafiqAsim 
Can you provide `flutter doctor -v` and steps you took that throws this exception ?
Maybe related to https://github.com/flutter/flutter/issues/94449
