### ISSUE TITLE
[tool_crash] SocketException: Write failed, OS Error: The pipe is being closed., errno = 232

### ISSUE THREAD

**Issue by nishat-nasir** [flutter/flutter#122001]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Write failed, OS Error: The pipe is being closed.
, errno = 232
```
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1190:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1916:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2356:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2104:26)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2078:11)
#5      _rootRunUnary (dart:async/zone.dart:1399:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     _StreamSinkImpl.add (dart:io/io_sink.dart:136:17)
#14     _IOSinkImpl.write (dart:io/io_sink.dart:269:5)
#15     _IOSinkImpl.writeln (dart:io/io_sink.dart:289:5)
#16     _Socket.writeln (dart:io-patch/socket_patch.dart:2196:45)
#17     _StdSink.writeln (dart:io/stdio.dart:342:11)
#18     DefaultResidentCompiler.reset (package:flutter_tools/src/compile.dart:966:20)
#19     DevFS.update (package:flutter_tools/src/devfs.dart:595:17)
#20     FlutterDevice.updateDevFS (package:flutter_tools/src/resident_runner.dart:551:29)
#21     HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:477:48)
<asynchronous suspension>
#22     HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:553:22)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.1265], locale en-US)
    • Flutter version 3.3.10 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:/Users/googl/AppData/Local/Android/Sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = C:/Users/googl/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33103.184
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.76.0)
    • VS Code at C:\Users\googl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • SM A805N (mobile) • emulator-5554 • android-x64    • Android 9 (API 28)
    • Windows (desktop) • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1265]
    • Chrome (web)      • chrome        • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)        • edge          • web-javascript • Microsoft Edge 110.0.1587.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 135454af32477f815a7525073027a3ff9eff1bfd
### Plugins
audioplayers-3.0.1
audioplayers_android-2.0.0
audioplayers_darwin-3.0.1
audioplayers_linux-1.0.4
audioplayers_web-2.2.0
audioplayers_windows-1.1.3
auto_updater-0.1.6
charset_converter-2.1.1
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
device_info_plus-3.2.4
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
firebase_core-2.7.0
firebase_core_web-2.2.1
firebase_messaging-14.2.5
firebase_messaging_web-3.2.15
flutter_libserialport-0.2.3
flutter_native_image-0.0.6+1
msix-3.7.0
ota_update-4.0.2
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-1.0.5
path_provider-2.0.13
path_provider_android-2.0.23
path_provider_foundation-2.1.2
path_provider_linux-2.1.9
path_provider_windows-2.0.7
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
platform_device_id_windows-0.0.1
screen_retriever-0.1.6
simplepay_api-fb920d5628ea51409c14831052771cc6bbcfeb83
soundpool-2.3.0
soundpool_macos-2.2.0
soundpool_web-2.2.0
sqflite-2.2.5
window_manager-0.3.1
window_size

**Comment by exaby73** [comment]
Hello @nishat-nasir. Can you try on the latest stable 3.7.6?
