### ISSUE TITLE
canvas paintImage() not working on certain IOS devices

### ISSUE THREAD

**Issue by fidelisakilan** [flutter/flutter#122267]
## Steps to Reproduce

Flutter version: 
```Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (6 weeks ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
```

1. Execute `flutter run` on the code sample 
2. The command paintImage() doesn't do anything on certain IOS device

**Expected results:** 
Image drawn over the canvas and resultant image should have input of previous image

**Actual results:** 
Resultant image is blank on IOS device, This issue is reproducible 50% of the time.

<details>
<summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

class ImageCropPainter {
  Future<ByteData> generate(File inputImageFile) async {
    ui.Image inputImage = await _loadImage(await inputImageFile.readAsBytes());
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(
        recorder,
        Rect.fromLTWH(
            0, 0, inputImage.width.toDouble(), inputImage.height.toDouble()));
    canvas.save();

    canvas.drawColor(Colors.white, BlendMode.color);

    paintImage(
      rect: Rect.fromLTWH(
          0, 0, inputImage.width.toDouble(), inputImage.height.toDouble()),
      canvas: canvas,
      image: inputImage,
      fit: BoxFit.contain,
    );

    final picture = recorder.endRecording();
    final img = await picture.toImage(inputImage.width, inputImage.height);
    final pngBytes = await img.toByteData(format: ui.ImageByteFormat.png);
    return pngBytes!;
  }

  Future<ui.Image> _loadImage(Uint8List imageBytes) async {
    final completer = Completer<ui.Image>();
    ui.decodeImageFromList(imageBytes, (ui.Image img) {
      completer.complete(img);
    });
    return completer.future;
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

https://user-images.githubusercontent.com/24905278/223926308-b8c67f6f-9770-457b-804b-a1923a9a0fc0.mp4

sample app repo: 
https://github.com/fidelisakilan/painter_bug

Device:
Iphone 6s IOS 15

**Comment by darshankawar** [comment]
Thanks for the report @fidelisakilan 
From your repro, I see that you are using `share_plus` plugin which is third party to flutter. Since your app tries to open the share feature, it may be related to this plugin. Does the same behavior occur without using that plugin and just using the iOS share default feature ?

**Comment by fidelisakilan** [comment]
Yes the same behaviour happens without share plugin also.
In the original app which had the same issue, the output image is displayed inside app as a Image.file().. In this case its displayed as blank image

**Comment by darshankawar** [comment]
Can you provide the updated repo without share plugin code / implementation ?

**Comment by fidelisakilan** [comment]
updated repo @darshankawar

**Comment by darshankawar** [comment]
@fidelisakilan 
I cloned the repo and ran it on iPhone 6s and observed as shown in the video. Also sharing the console log:


https://user-images.githubusercontent.com/67046386/224233408-fa68fbe2-ffc0-41e0-9e72-78d8b109e222.MP4

<details>
<summary> console log </summary>

```

======== Exception caught by image resource service ================================================
The following StateError was thrown resolving an image codec:
Bad state: File: '/var/mobile/Containers/Data/Application/9E98C12E-53ED-4F32-BCA4-DDE990AC7EDB/Library/Caches/image 58.png' is empty and cannot be loaded as an image.

When the exception was thrown, this was the stack: 
#0      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:1002:7)
<asynchronous suspension>
Path: /var/mobile/Containers/Data/Application/9E98C12E-53ED-4F32-BCA4-DDE990AC7EDB/Library/Caches/image 58.png
====================================================================================================
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:10979 (
	0   AXRuntime                           0x00000001ad00118c 4D58D647-3790-337C-B355-1A1D89EEF0A6 + 303500
	1   AXRuntime                           0x00000001acfba904 _AXGetPortFromCache + 696
	2   AXRuntime                           0x00000001acfbbfb8 AXUIElementPerformFencedActionWithValue + 484
	3   UIKit                               0x00000001de353474 C2DBE0FE-DB27-32EA-BB77-8DAB1AE90851 + 885876
	4   libdispatch.dylib                   0x00000001836211a4 95D85335-DD46-355E-905C-3743A10000EC + 405924
	5   libdispatch.dylib                   0x00000001836221a8 95D85335-DD46-355E-905C-3743A10000EC + 410024
	6   libdispatch.dylib                   0x00000001835c80e4 95D85335-DD46-355E-905C-3743A10000EC + 41188
	7   libdispatch.dylib                   0x00000001835c8b94 95D85335-DD46-355E-905C-3743A10000EC + 43924
	8   libdispatch.dylib                   0x00000001835d2760 95D85335-DD46-355E-905C-3743A10000EC + 83808
	9   libsystem_pthread.dylib             0x00000001de047e84 _pthread_wqthread + 284
	10  libsystem_pthread.dylib             0x00000001de0479f0 start_wqthread + 8
)
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:10979 (
	0   AXRuntime                           0x00000001ad00118c 4D58D647-3790-337C-B355-1A1D89EEF0A6 + 303500
	1   AXRuntime                           0x00000001acfba904 _AXGetPortFromCache + 696
	2   AXRuntime                           0x00000001acfbbfb8 AXUIElementPerformFencedActionWithValue + 484
	3   UIKit                               0x00000001de353474 C2DBE0FE-DB27-32EA-BB77-8DAB1AE90851 + 885876
	4   libdispatch.dylib                   0x00000001836211a4 95D85335-DD46-355E-905C-3743A10000EC + 405924
	5   libdispatch.dylib                   0x00000001836221a8 95D85335-DD46-355E-905C-3743A10000EC + 410024
	6   libdispatch.dylib                   0x00000001835c80e4 95D85335-DD46-355E-905C-3743A10000EC + 41188
	7   libdispatch.dylib                   0x00000001835c8b94 95D85335-DD46-355E-905C-3743A10000EC + 43924
	8   libdispatch.dylib                   0x00000001835d2760 95D85335-DD46-355E-905C-3743A10000EC + 83808
	9   libsystem_pthread.dylib             0x00000001de047e84 _pthread_wqthread + 284
	10  libsystem_pthread.dylib             0x00000001de0479f0 start_wqthread + 8
)
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:10979 (
	0   AXRuntime                           0x00000001ad00118c 4D58D647-3790-337C-B355-1A1D89EEF0A6 + 303500
	1   AXRuntime                           0x00000001acfba904 _AXGetPortFromCache + 696
	2   AXRuntime                           0x00000001acfbbfb8 AXUIElementPerformFencedActionWithValue + 484
	3   UIKit                               0x00000001de353474 C2DBE0FE-DB27-32EA-BB77-8DAB1AE90851 + 885876
	4   libdispatch.dylib                   0x00000001836211a4 95D85335-DD46-355E-905C-3743A10000EC + 405924
	5   libdispatch.dylib                   0x00000001836221a8 95D85335-DD46-355E-905C-3743A10000EC + 410024
	6   libdispatch.dylib                   0x00000001835c80e4 95D85335-DD46-355E-905C-3743A10000EC + 41188
	7   libdispatch.dylib                   0x00000001835c8b94 95D85335-DD46-355E-905C-3743A10000EC + 43924
	8   libdispatch.dylib                   0x00000001835d2760 95D85335-DD46-355E-905C-3743A10000EC + 83808
	9   libsystem_pthread.dylib             0x00000001de047e84 _pthread_wqthread + 284
	10  libsystem_pthread.dylib             0x00000001de0479f0 start_wqthread + 8
)
[Runner] findWriterForTypeAndAlternateType:119: unsupported file format 'public.heic'
[Runner] findWriterForTypeAndAlternateType:119: unsupported file format 'public.heic'

======== Exception caught by image resource service ================================================
The following StateError was thrown resolving an image codec:
Bad state: File: '/var/mobile/Containers/Data/Application/9E98C12E-53ED-4F32-BCA4-DDE990AC7EDB/Library/Caches/image 57.png' is empty and cannot be loaded as an image.

When the exception was thrown, this was the stack: 
#0      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:1002:7)
<asynchronous suspension>
Path: /var/mobile/Containers/Data/Application/9E98C12E-53ED-4F32-BCA4-DDE990AC7EDB/Library/Caches/image 57.png
====================================================================================================

```

</details>

Is this a correct interpretation of the issue you are reporting ?



If you see the console log, `Library/Caches/image 57.png`, it has space in the image name. Try to remove the space or use underscore and try again to see if you still get the same error / behavior as reported.

for `unsupported file format 'public.heic'` check this similar issue for your reference: https://github.com/flutter/flutter/issues/103248

**Comment by fidelisakilan** [comment]
This isssue was not reproducible by me, i can only test it in simulator and it worked fine. This issue was present friends device on production app. We didn't check with heic files mostly png only. But I don't get why image file name is failing for you.

**Comment by fidelisakilan** [comment]
I tried with naming file without space, i can still reproduce in iphone 6s

**Comment by darshankawar** [comment]
@fidelisakilan 
What exactly is the issue are you able to replicate ?
