### ISSUE TITLE
Unhandled exception: Exception: Error connecting to observatory

### ISSUE THREAD

**Issue by arnoldparge** [flutter/flutter#12223]
## Steps to Reproduce

Running from Intellij

## Logs

##Flutter run:
```
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8106/ws
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:738)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:566)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:414)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:243)
#5      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:88)
<asynchronous suspension>
#6      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:581)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:106)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:205)
<asynchronous suspension>
#9      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:414)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1467)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:770)
#17     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:412)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:261)
<asynchronous suspension>
#19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#20     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:227)
<asynchronous suspension>
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#22     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#28     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#29     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#30     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#31     _rootRun (dart:async/zone.dart:1120)
#32     _CustomZone.run (dart:async/zone.dart:1001)
#33     runZoned (dart:async/zone.dart:1467)
#34     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#35     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#36     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#37     main (file:///C:/Users/PARGE/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
##Flutter Analize:
```
Analyzing C:\Users\PARGE\IdeaProjects\kingdom...
  hint - Unused import at lib\components\comment_list_items.dart:3:8 - unused_import
  hint - Unused import at lib\components\comment_list_items.dart:4:8 - unused_import
  hint - Unused import at lib\components\more_list_items.dart:4:8 - unused_import
  hint - Unused import at lib\HomePage.dart:5:8 - unused_import
  hint - Unused import at lib\HomePage.dart:6:8 - unused_import
  hint - Unused import at lib\HomePage.dart:7:8 - unused_import
  hint - Unused import at lib\HomePage.dart:12:8 - unused_import
  hint - Unused import at lib\MainTabs\HomeTab.dart:9:8 - unused_import
  hint - Unused import at lib\pages\feed_comments.dart:2:8 - unused_import
  hint - Unused import at lib\pages\feed_comments.dart:6:8 - unused_import
10 issues found.
(Ran in 16.0s)
```

## Flutter Doctor

[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-IN, channel unknown)
    • Flutter at C:\Users\*****\flutter\flutter
    • Framework revision 1c372c6803 (3 weeks ago), 2017-08-31 15:54:45 -0700
    • Engine revision f9e00a7c72
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[√] Connected devices
    • Micromax A310 • ***.***.*.***:5555 • android-arm • Android 4.4.2 (API 19)

**Comment by Hixie** [comment]
We need more details on what could be causing this, as we can't reproduce it locally.

I'm not sure exactly what information would help, though.

Does it only happen with the Micromax A310?
