### ISSUE TITLE
Assertion in _GlowingOverscrollIndicatorState._handleScrollNotification

### ISSUE THREAD

**Issue by elsamuko** [flutter/flutter#122216]
## Steps to Reproduce

1. Execute `flutter run` on the code sample in an android simulator
2. Move one of the scrollable texts
3. At both ends you run into an assertion in `_GlowingOverscrollIndicatorState._handleScrollNotification`

**Expected results:** 
No assertion.

**Actual results:** 
Assertion which says to open this bug report.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Overscroll Indicator',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('Overscroll Indicator')),
        body: Scrollbar(
            child: ListView.builder(
                shrinkWrap: true,
                physics: ClampingScrollPhysics(),
                itemCount: 2,
                itemBuilder: (context, i) {
                  return ListTile(
                    title: SingleChildScrollView(
                      child: Text("Scroll me sideways " * 4),
                      scrollDirection: Axis.horizontal,
                    ),
                  );
                })));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:243:14)
#3      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#4      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3170:18)
#5      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#6      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#9      Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4534:24)
#10     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#11     DragScrollActivity.dispatchOverscrollNotification (package:flutter/src/widgets/scroll_activity.dart:474:135)
#12     ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:931:15)
#13     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:285:9)
#14     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:78:18)
#15     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:122:5)
#16     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
#17     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:719:12)
#18     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:483:55)
#19     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#20     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:483:7)
#21     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:330:9)
#22     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#23     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#24     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#25     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#26     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#27     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
#28     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#29     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
#30     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#31     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#32     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#33     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#34     _invoke1 (dart:ui/hooks.dart:164:13)
#35     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#36     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
Handler: "onUpdate"
Recognizer: HorizontalDragGestureRecognizer#e5373
  start behavior: start
====================================================================================================
```

```
[✓] Flutter (Channel stable, 3.7.6, on Ubuntu 22.04.2 LTS 5.15.0-67-generic, locale en_US.UTF-8)
    • Flutter version 3.7.6 on channel stable at /home/samuel/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (7 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1
```

</details>

**Comment by darshankawar** [comment]
@elsamuko 
Thanks for the report. I used the code sample and ran on latest stable and master version using iOS simulator, scrolled both texts sideways but didn't see the exception being triggered. I see a clean console log.
Can you provide a short video of exception being thrown ?

**Comment by darshankawar** [comment]
Thanks for the video. I was able to replicate this only on Android and that too only on stable version. Using same code sample on latest master version and running on Android emulator doesn't throw the reported exception. See below:


https://user-images.githubusercontent.com/67046386/224230427-2f1840ef-45a6-4427-ba9d-294b54cd7469.mov

This indicates the exception is fixed on master but not in stable yet. It should be available in next stable release. You may switch to latest master and run the scenario again to see the fix working.

Per our triage policy, since it is working and fixed on latest master, I'll go ahead and close this. If you disagree, write in comments and I'll reopen it.
