### ISSUE TITLE
Integration tests on Android fail because app is terminated via adb before all tests ran

### ISSUE THREAD

**Issue by janknips** [flutter/flutter#122386]
## Steps to Reproduce

I have the following CI script (it works 100% on iOS):

```
flutter emulators
flutter emulators --launch emulator &
adb wait-for-device
flutter devices
flutter test -d emulator-5554 --verbose integration_test/suites/suite_1 --machine
```

**Expected results:** The tests run properly

**Actual results:** The tests terminate after a certain point with the following error message
```
{"testID":5,"messageType":"print","message":"screen size: width=1080.0, height=2154.0","type":"print","time":1336610}
[+837537 ms] test 0: Test process is no longer needed by test harness
[        ] test 0: finished
[   +3 ms] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[        ] executing: /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.knips
[        ] test 0: Test harness is no longer needed by test process
{"testID":31,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346179}
{"test":{"id":32,"name":"Post statistics: should show recently published hint when adding new post","suiteID":0,"groupIDs":[2,28],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346187}
{"testID":32,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346190}
{"test":{"id":33,"name":"Post statistics: (tearDownAll)","suiteID":0,"groupIDs":[2,28],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1346190}
{"testID":33,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346190}
{"group":{"id":34,"suiteID":0,"parentID":2,"name":"Flow post statistics:","metadata":{"skip":false,"skipReason":null},"testCount":2,"line":97,"column":3,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/posts/post_statistics_test.dart"},"type":"group","time":1346191}
{"test":{"id":35,"name":"Flow post statistics: (setUpAll)","suiteID":0,"groupIDs":[2,34],"metadata":{"skip":false,"skipReason":null},"line":98,"column":5,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/posts/post_statistics_test.dart"},"type":"testStart","time":1346191}
{"testID":35,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346191}
{"test":{"id":36,"name":"Flow post statistics: should show correct values when statistics screen is opened","suiteID":0,"groupIDs":[2,34],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346191}
{"testID":36,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346191}
{"test":{"id":37,"name":"Flow post statistics: should show correct name when opening statistics details","suiteID":0,"groupIDs":[2,34],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346191}
{"testID":37,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346192}
{"test":{"id":38,"name":"Flow post statistics: (tearDownAll)","suiteID":0,"groupIDs":[2,34],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1346192}
{"testID":38,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346192}
{"group":{"id":39,"suiteID":0,"parentID":2,"name":"go_router (Deep link tests):","metadata":{"skip":false,"skipReason":null},"testCount":9,"line":24,"column":3,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"group","time":1346193}
{"test":{"id":40,"name":"go_router (Deep link tests): (setUpAll)","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":25,"column":5,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"testStart","time":1346193}
{"testID":40,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346193}
{"test":{"id":41,"name":"go_router (Deep link tests): opens /feed/feedId/unfollow","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346194}
{"testID":41,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346194}
{"test":{"id":42,"name":"go_router (Deep link tests): opens /feed/feedId/preferences","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346194}
{"testID":42,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346194}
{"test":{"id":43,"name":"go_router (Deep link tests): opens SinglePostScreen via full path of screen","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346194}
{"testID":43,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346194}
{"test":{"id":44,"name":"go_router (Deep link tests): opens SinglePostScreen via query parameter","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346195}
{"testID":44,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346195}
{"test":{"id":45,"name":"go_router (Deep link tests): opens SinglePostScreen via query parameter if more random parameters are added","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346195}
{"testID":45,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346195}
{"test":{"id":46,"name":"go_router (Deep link tests): redirects to home if invalid postId supplied","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346195}
{"testID":46,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346195}
{"test":{"id":47,"name":"go_router (Deep link tests): redirects to home if invalid feedId supplied","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346196}
{"testID":47,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346196}
{"test":{"id":48,"name":"go_router (Deep link tests): opens the given feed via URL","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346196}
{"testID":48,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346197}
{"test":{"id":49,"name":"go_router (Deep link tests): redirects to home if feedId given in URL does not exist","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346197}
{"testID":49,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346197}
{"test":{"id":50,"name":"go_router (Deep link tests): (tearDownAll)","suiteID":0,"groupIDs":[2,39],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1346197}
{"testID":50,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346197}
{"group":{"id":51,"suiteID":0,"parentID":2,"name":"go_router (Push notification tests):","metadata":{"skip":false,"skipReason":null},"testCount":3,"line":32,"column":3,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"group","time":1346197}
{"test":{"id":52,"name":"go_router (Push notification tests): (setUpAll)","suiteID":0,"groupIDs":[2,51],"metadata":{"skip":false,"skipReason":null},"line":33,"column":5,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"testStart","time":1346197}
{"testID":52,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346197}
{"test":{"id":53,"name":"go_router (Push notification tests): handles opening type newPost correctly","suiteID":0,"groupIDs":[2,51],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346198}
{"testID":53,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346198}
{"test":{"id":54,"name":"go_router (Push notification tests): handles opening type newSuggestion correctly","suiteID":0,"groupIDs":[2,51],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346198}
{"testID":54,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346198}
{"test":{"id":55,"name":"go_router (Push notification tests): handles opening type newFollower and all other types correctly","suiteID":0,"groupIDs":[2,51],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346198}
{"testID":55,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346198}
{"test":{"id":56,"name":"go_router (Push notification tests): (tearDownAll)","suiteID":0,"groupIDs":[2,51],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1346199}
{"testID":56,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346199}
{"group":{"id":57,"suiteID":0,"parentID":2,"name":"go_router (Universal link tests):","metadata":{"skip":false,"skipReason":null},"testCount":5,"line":40,"column":3,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"group","time":1346199}
{"test":{"id":58,"name":"go_router (Universal link tests): (setUpAll)","suiteID":0,"groupIDs":[2,57],"metadata":{"skip":false,"skipReason":null},"line":41,"column":5,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"testStart","time":1346199}
{"testID":58,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346199}
{"test":{"id":59,"name":"go_router (Universal link tests): opens SinglePostScreen from next app URL","suiteID":0,"groupIDs":[2,57],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346199}
{"testID":59,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346199}
{"test":{"id":60,"name":"go_router (Universal link tests): opens FeedScreen from next app URL","suiteID":0,"groupIDs":[2,57],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346200}
{"testID":60,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346200}
{"test":{"id":61,"name":"go_router (Universal link tests): opens SinglePostScreen from knips.app link","suiteID":0,"groupIDs":[2,57],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346200}
{"testID":61,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346200}
{"test":{"id":62,"name":"go_router (Universal link tests): opens FeedScreen from knips.app link","suiteID":0,"groupIDs":[2,57],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346200}
{"testID":62,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346200}
{"test":{"id":63,"name":"go_router (Universal link tests): opens the right page from web admin URL","suiteID":0,"groupIDs":[2,57],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346201}
{"testID":63,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346201}
{"test":{"id":64,"name":"go_router (Universal link tests): (tearDownAll)","suiteID":0,"groupIDs":[2,57],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1346201}
{"testID":64,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346201}
{"group":{"id":65,"suiteID":0,"parentID":2,"name":"legacy_routing (Deep link tests):","metadata":{"skip":false,"skipReason":null},"testCount":7,"line":48,"column":3,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"group","time":1346201}
{"test":{"id":66,"name":"legacy_routing (Deep link tests): (setUpAll)","suiteID":0,"groupIDs":[2,65],"metadata":{"skip":false,"skipReason":null},"line":49,"column":5,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"testStart","time":1346201}
{"testID":66,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346201}
{"test":{"id":67,"name":"legacy_routing (Deep link tests): opens /feed/feedId/unfollow","suiteID":0,"groupIDs":[2,65],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346202}
{"testID":67,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346202}
{"test":{"id":68,"name":"legacy_routing (Deep link tests): opens /feed/feedId/preferences","suiteID":0,"groupIDs":[2,65],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346202}
{"testID":68,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346202}
{"test":{"id":69,"name":"legacy_routing (Deep link tests): opens SinglePostScreen via full path of screen","suiteID":0,"groupIDs":[2,65],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346203}
{"testID":69,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346204}
{"test":{"id":70,"name":"legacy_routing (Deep link tests): opens SinglePostScreen via query parameter","suiteID":0,"groupIDs":[2,65],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346204}
{"testID":70,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346204}
{"test":{"id":71,"name":"legacy_routing (Deep link tests): opens SinglePostScreen via query parameter if more random parameters are added","suiteID":0,"groupIDs":[2,65],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346204}
{"testID":71,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346204}
{"test":{"id":72,"name":"legacy_routing (Deep link tests): opens the given feed via URL","suiteID":0,"groupIDs":[2,65],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346205}
{"testID":72,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346205}
{"test":{"id":73,"name":"legacy_routing (Deep link tests): redirects to home if feedId given in URL does not exist","suiteID":0,"groupIDs":[2,65],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346205}
{"testID":73,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346205}
{"test":{"id":74,"name":"legacy_routing (Deep link tests): (tearDownAll)","suiteID":0,"groupIDs":[2,65],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1346205}
{"testID":74,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346205}
{"group":{"id":75,"suiteID":0,"parentID":2,"name":"legacy_routing (Push notification tests):","metadata":{"skip":false,"skipReason":null},"testCount":3,"line":56,"column":3,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"group","time":1346206}
{"test":{"id":76,"name":"legacy_routing (Push notification tests): (setUpAll)","suiteID":0,"groupIDs":[2,75],"metadata":{"skip":false,"skipReason":null},"line":57,"column":5,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"testStart","time":1346206}
{"testID":76,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346206}
{"test":{"id":77,"name":"legacy_routing (Push notification tests): handles opening type newPost correctly","suiteID":0,"groupIDs":[2,75],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346206}
{"testID":77,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346206}
{"test":{"id":78,"name":"legacy_routing (Push notification tests): handles opening type newSuggestion correctly","suiteID":0,"groupIDs":[2,75],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346207}
{"testID":78,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346207}
{"test":{"id":79,"name":"legacy_routing (Push notification tests): handles opening type newFollower and all other types correctly","suiteID":0,"groupIDs":[2,75],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346207}
{"testID":79,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346207}
{"test":{"id":80,"name":"legacy_routing (Push notification tests): (tearDownAll)","suiteID":0,"groupIDs":[2,75],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1346207}
{"testID":80,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346208}
{"group":{"id":81,"suiteID":0,"parentID":2,"name":"legacy_routing (Universal link tests):","metadata":{"skip":false,"skipReason":null},"testCount":4,"line":64,"column":3,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"group","time":1346208}
{"test":{"id":82,"name":"legacy_routing (Universal link tests): (setUpAll)","suiteID":0,"groupIDs":[2,81],"metadata":{"skip":false,"skipReason":null},"line":65,"column":5,"url":"file:///Users/builder/clone/Users/builder/clone/integration_test/test/routing/routing_open_app_via_push_or_link_test.dart"},"type":"testStart","time":1346208}
{"testID":82,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346208}
{"test":{"id":83,"name":"legacy_routing (Universal link tests): opens SinglePostScreen from next app URL","suiteID":0,"groupIDs":[2,81],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346209}
{"testID":83,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346209}
{"test":{"id":84,"name":"legacy_routing (Universal link tests): opens FeedScreen from next app URL","suiteID":0,"groupIDs":[2,81],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346209}
{"testID":84,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346209}
{"test":{"id":85,"name":"legacy_routing (Universal link tests): opens SinglePostScreen from knips.app link","suiteID":0,"groupIDs":[2,81],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346209}
{"testID":85,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346210}
{"test":{"id":86,"name":"legacy_routing (Universal link tests): opens FeedScreen from knips.app link","suiteID":0,"groupIDs":[2,81],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart"},"type":"testStart","time":1346210}
{"testID":86,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346210}
{"test":{"id":87,"name":"legacy_routing (Universal link tests): (tearDownAll)","suiteID":0,"groupIDs":[2,81],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1346210}
{"testID":87,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346210}
{"test":{"id":88,"name":"(tearDownAll)","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":42,"column":5,"url":"package:integration_test/integration_test.dart"},"type":"testStart","time":1346210}
{"testID":88,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1346211}
{"success":false,"type":"done","time":1346218}
[  +49 ms] test package returned with exit code 1
[   +1 ms] Runtime for phase TestRunner: Wall-clock: 0:22:26.465983; combined: 0:22:26.466130.
[        ] Runtime for phase Compile: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase Run: Wall-clock: 0:22:26.139818; combined: 0:22:26.139901.
[        ] Runtime for phase CoverageTotal: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageParseJson: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageAddHitmap: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageDataCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase WatcherFinishedTest: Wall-clock: 0:00:00.003198; combined: 0:00:00.003200.
[   +2 ms] "flutter test" took 1,437,459ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:490:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +49 ms] ensureAnalyticsSent: 49ms
[        ] Running 1 shutdown hook
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1
```

<details>
<summary>Code sample</summary>

Affects integration tests, not code directly, lets see if somebody else faces this? Otherwise let me know if I should try to build a reproduction.

</details>

<details>
  <summary>Logs</summary>

https://drive.google.com/file/d/1Z_KO7COri_2Qpp0J91GPt5UoMUPtbljH/view?usp=sharing

```
Analyzing knips_app...                                                  
No issues found! (ran in 11.1s)
```

```
[✓] Flutter (Channel stable, 3.7.5, on macOS 12.6.1 21G217 darwin-x64, locale en-US)
    • Flutter version 3.7.5 on channel stable at /Users/builder/programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (2 weeks ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode-14.2.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @janknips 
Couple of things:

1. Do you get same behavior without using the script ? ie running with original command ?
2. Do you get same behavior with `flutter test` as well ? This is to see if the issue is with integration_test or underlying test package itself.

Looking at the logs, it seems similar to https://github.com/flutter/flutter/issues/101031 in which I see you have already commented.

**Comment by janknips** [comment]
> Thanks for the report @janknips Couple of things:
> 
> 1. Do you get same behavior without using the script ? ie running with original command ?
> 2. Do you get same behavior with `flutter test` as well ? This is to see if the issue is with integration_test or underlying test package itself.
> 
> Looking at the logs, it seems similar to #101031 in which I see you have already commented.

Thanks, you're right, it seems similar, but the log message is different I would say. I could not find any posts that had issues with "Test process is no longer needed by test harness" being printed too early.

1. I am not sure if I can remove any steps of the script, since launching and waiting for the emulator is required, but I will try with the bare minimum of steps.
2. I never had any issues outside of integration_test.

**Comment by darshankawar** [comment]
Take a look at the `integration_test` example and see if using it, you get same reported error or not.

**Comment by janknips** [comment]
> Take a look at the `integration_test` [example](https://github.com/flutter/flutter/tree/main/packages/integration_test/example) and see if using it, you get same reported error or not.

I tried only having these two before `flutter test`, same issue persists:
```
flutter emulators --launch emulator &
adb wait-for-device
```

Regarding the example, the problem is that this crash only occurs after a certain time, my estimate is about 10-15 minutes. The example is too short unfortunately. The first 5-10 tests that I run always work. 

If you think its worth to try it, I can do it.

**Comment by darshankawar** [comment]
I am unable to replicate this using the commands you shared  with integration_test example. For me it opens the emulator as below but nothing after that:

```
dhs@Dhss-MacBook-Pro example % flutter emulators --launch Pixel XL API 30 & adb wait-for-device
[1] 2809
dhs@Dhss-MacBook-Pro example % 
[1]  + done       flutter emulators --launch Pixel XL API 30
dhs@Dhss-MacBook-Pro example % 

```

**Comment by janknips** [comment]
> I am unable to replicate this using the commands you shared with integration_test example. For me it opens the emulator as below but nothing after that:
> 
> ```
> dhs@Dhss-MacBook-Pro example % flutter emulators --launch Pixel XL API 30 & adb wait-for-device
> [1] 2809
> dhs@Dhss-MacBook-Pro example % 
> [1]  + done       flutter emulators --launch Pixel XL API 30
> dhs@Dhss-MacBook-Pro example % 
> ```

Sorry just to clarify, the full set of commands I tried:

```
flutter emulators --launch emulator &
adb wait-for-device
flutter test -d emulator-5554 --verbose integration_test/suites/suite_1 --machine
```

**Comment by darshankawar** [comment]
Thanks for the update. I tried the same command on package example which worked properly:

```
[        ] Runtime for phase WatcherFinishedTest: Wall-clock: 0:00:00.000115;
combined: 0:00:00.000117.
[   +1 ms] "flutter test" took 113,406ms.
[ +172 ms] ensureAnalyticsSent: 168ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 0
dhs@Dhss-MacBook-Pro example % 
```

But yeah, since there were not many tests in that example, the verification may not be proper. If you could provide a demo repo that we can clone and run locally to verify, would be great to make this issue actionable.
