### ISSUE TITLE
Cannot get single element from stream by using EventChannel from plugin

### ISSUE THREAD

**Issue by Alexays** [flutter/flutter#12239]
## Steps to Reproduce

Use sensors plugin and just do

```
AccelerometerEvent event = await accelerometerEvents.single;
```
So either it produces an error or the await never finishes

## Logs
```
Bad state: Too many elements
E/flutter ( 8973): #0      Stream.single.<anonymous closure> (dart:async/stream.dart:1196)
E/flutter ( 8973): #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
E/flutter ( 8973): #2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
E/flutter ( 8973): #3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
E/flutter ( 8973): #4      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
E/flutter ( 8973): #5      _MapStream._handleData (dart:async/stream_pipe.dart:232)
E/flutter ( 8973): #6      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
E/flutter ( 8973): #7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
E/flutter ( 8973): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
E/flutter ( 8973): #9      _DelayedData.perform (dart:async/stream_impl.dart:579)
E/flutter ( 8973): #10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:695)
E/flutter ( 8973): #11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:655)
E/flutter ( 8973): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter ( 8973): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```
## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/rouill_a/bin/flutter
    • Framework revision 82ec7a2af5 (83 minutes ago), 2017-09-25 13:09:28 +0200
    • Engine revision 0a6e415b60
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /opt/android-sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
```

**Comment by jason-simmons** [comment]
Stream.single will throw an exception if the stream yields more than one element

Use stream.first if you are only interested in the first element of a stream
