### ISSUE TITLE
Crash on Android API level 16 devices

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#12235]
Flutter View uses View.getDisplay
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/view/FlutterView.java#L667

View.getDisplay was added in API level 17
https://developer.android.com/reference/android/view/View.html#getDisplay()

## Logs

```
Fatal Exception: java.lang.NoSuchMethodError: io.flutter.view.FlutterView.getDisplay
       at io.flutter.view.FlutterView.updateViewportMetrics(FlutterView.java:667)
       at io.flutter.view.FlutterView.fitSystemWindows(FlutterView.java:521)
       at android.view.ViewGroup.fitSystemWindows(ViewGroup.java:5105)
       at android.view.ViewGroup.fitSystemWindows(ViewGroup.java:5105)
       at android.view.ViewGroup.fitSystemWindows(ViewGroup.java:5105)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.fitSystemWindows(PhoneWindow.java:2653)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1230)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1019)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4276)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4886)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale ja-JP, channel master)
    • Flutter at /Applications/flutter
    • Framework revision 8e5ec0b153 (5 days ago), 2017-09-19 19:55:31 -0700
    • Engine revision bd64e8dc5a
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.1)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[✓] Connected devices
    • None
```

**Comment by eseidelGoogle** [comment]
@jason-simmons is probably the right person to ask here.
