### ISSUE TITLE
'_debugLifecycleState == _StateLifecycle.ready': is not true

### ISSUE THREAD

**Issue by ZayedKherani** [flutter/flutter#122459]
The code is the `onPressed` of a `FloatingActionButton` which would get the content of a `TextFormField`'s Controller and use that to pass text to a model class `Note` which would be in a list insde another model class `Notes`. The `Note` model also contains a timestamp precise to a minute of the note added.
Controller then gets cleared, and text value set to `""`. That for some reason never clears the `TextFormField` even after calling a `setState(() {});` so it gets assigned a new controller after the old one is disposed. The `Form` is keeping the text regardless requiring a reset of the `GlobalKey<FormState>` as well.
Somwhere along that lies the bug which causes the app to freeze and throw errors.
Running without a debugger in VSCode just spits out the error and the app refreshes onto the homescreen of the app defined in the `MaterialApp` in the `main.dart` file.
[Here](https://github.com/ZayedKherani/grassroots-app) is the GitHub which contains the code under the [ZayedKherani/TodayDayPlanNoteImplementation](https://github.com/ZayedKherani/grassroots-app/tree/ZayedKherani/TodayDayPlanNoteImplementation) Branch. The code is in the `lib/pages/today/add_notes/add_notes.dart` [file](https://github.com/ZayedKherani/grassroots-app/blob/ZayedKherani/TodayDayPlanNoteImplementation/lib/pages/today/add_notes/add_notes.dart).

## Steps to Reproduce
...`flutter run I suppose`?
App utilizes Firebase and will not run without.

**Expected results:**
No error logs to report on the debug console

**Actual results:**
Errors show up and debugger stops on uncaught exception before throwing errors onto the debug console

<details>
<summary>Code sample</summary>

```dart
onPressed: () async {
  if (addNoteKey!.currentState!.validate()) {
    await NotesService.addNote(
      noteToAdd: Note(
        message: addNoteController!.text,
        createdAt: DateTime(
          DateTime.now().year,
          DateTime.now().month,
          DateTime.now().day,
          DateTime.now().hour,
          DateTime.now().minute,
        ),
      ),
      notes: globalDayPlans!.dayPlansList![dayPlansIndex]!.notes!,
    );

    await DayPlanService.writeDayPlansToStorage();

    addNoteController!.clear();
    addNoteController!.text = "";

    addNoteController!.dispose();

    addNoteController = TextEditingController();

    // addNoteKey!.currentState!.reset();

    addNoteKey!.currentState!.dispose();

    addNoteKey = GlobalKey<FormState>();

    setState(
      () {},
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1242 pos 12: '_debugLifecycleState == _StateLifecycle.ready': is not true.
framework.dart:1242
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
  
When the exception was thrown, this was the stack
#2      State.dispose
framework.dart:1242
#3      StatefulElement.unmount
framework.dart:5179
#4      _InactiveElements._unmount
framework.dart:1960
#5      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#6      _InactiveElements._unmountAll
framework.dart:1969
#7      BuildOwner.lockState
framework.dart:2601
#8      BuildOwner.finalizeTree
framework.dart:3023
#9      WidgetsBinding.drawFrame
binding.dart:866
#10     RendererBinding._handlePersistentFrameCallback
binding.dart:381
#11     SchedulerBinding._invokeFrameCallback
binding.dart:1289
#12     SchedulerBinding.handleDrawFrame
binding.dart:1218
#13     SchedulerBinding._handleDrawFrame
binding.dart:1076
#14     _invoke (dart:ui/hooks.dart:145:13)
#15     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#16     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```

`flutter analyze`:
```
Analyzing grassroots-app...                                             
No issues found! (ran in 3.1s)
```

`flutter doctor -v`:
```
[√] Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.25300.1000], locale en-CA)
    • Flutter version 3.7.6 on channel stable at C:\files and stuff\pathItems\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (10 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\zayed\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Users\zayed\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Users\zayed\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335
    • Flutter plugin version 72.1.1
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code, 64-bit edition (version 1.71.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] VS Code, 64-bit edition (version 1.75.0-insider)
    • VS Code at C:\Program Files\Microsoft VS Code Insiders
    • Flutter extension version 3.58.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.25300.1000]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@ZayedKherani 
In order to properly analyze the issue and narrow it down to the framework, we would need a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party package code implementation that triggers the error you are reporting. The repo you shared seems to be an entire project with custom implementation, but we would need only minimal code sample containing framework code that triggers the error you are reporting, so if you can narrow it down and share the same here, it would help  to make this issue actionable.

**Comment by ZayedKherani** [comment]
@darshankawar I figured out the issue
```dart
onPressed: () async {
  if (addNoteKey!.currentState!.validate()) {
    await NotesService.addNote(
      noteToAdd: Note(
        message: addNoteController!.text,
        createdAt: DateTime(
          DateTime.now().year,
          DateTime.now().month,
          DateTime.now().day,
          DateTime.now().hour,
          DateTime.now().minute,
        ),
      ),
      notes: globalDayPlans!.dayPlansList![dayPlansIndex]!.notes!,
    );

    await DayPlanService.writeDayPlansToStorage();

    addNoteController!.clear();
    addNoteController!.text = "";

    addNoteController!.dispose();

    addNoteController = TextEditingController();

    // addNoteKey!.currentState!.reset();

    addNoteKey!.currentState!.dispose();

    addNoteKey = GlobalKey<FormState>();

    setState(
      () {},
    );
  }
}
```
The following lines of code cause an issue
```
addNoteController!.clear();
addNoteController!.text = "";

addNoteController!.dispose();

...

addNoteKey!.currentState!.dispose();
```
Removing them fixed the issue.
