### ISSUE TITLE
[tool_crash] _CastError: (#0      new Plugin._fromLegacyYaml (package:flutter_tools/src/plugins.dart:198:66))

### ISSUE THREAD

**Issue by naibbian** [flutter/flutter#122522]
## Command
```
flutter pub get component/lib_entity
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      new Plugin._fromLegacyYaml (package:flutter_tools/src/plugins.dart:198:66))
```
#0      new Plugin._fromLegacyYaml (package:flutter_tools/src/plugins.dart:198:66)
#1      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:88:19)
#2      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#3      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#4      PackagesGetCommand.usageValues (package:flutter_tools/src/commands/packages.dart:102:36)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1423:15)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.7, on macOS 13.0.1 22A400 darwin-arm64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.7.7 on channel stable at /Users/qubian/Desktop/Flutter/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2ad6cd72c0 (5 days ago), 2023-03-08 09:41:59 -0800
    [32m•[39m Engine revision 1837b5be5f
    [32m•[39m Dart version 2.19.4
    [32m•[39m DevTools version 2.20.1
    [32m•[39m Pub download mirror https://pub.dartlang.org
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/qubian/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m ANDROID_HOME = /Users/qubian/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14B47b
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[32m[✓][39m VS Code (version 1.76.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code

**Comment by darshankawar** [comment]
@naibbian 
This was fixed upstream as part of https://github.com/flutter/flutter/issues/120230, so please switch to latest master and run your command again to see the fix working.

`flutter channel master`
`flutter upgrade`

Closing from here, as this is already fixed using the linked issue above.
