### ISSUE TITLE
[video_player] Unremoved listener causes the example app to crash

### ISSUE THREAD

**Issue by gadishimwe** [flutter/flutter#122690]
Hi, I was playing with video_player package example, and when I tried this code: https://github.com/flutter/packages/blob/main/packages/video_player/video_player/example/lib/main.dart#L383-L438

The app crashed and this is the logs for the error which is actually being caused by calling `dispose` method without first removing the `listener` that was previously added.

![Screenshot 2023-03-15 at 14 06 16](https://user-images.githubusercontent.com/52411901/225308620-cf779bf3-1036-4516-b64e-fb07e14212e2.png)

Solution proposal: 

I fixed the issue by removing the added `listener` before calling `dispose` which is being called by calling `Navigator.pop(context);`

https://github.com/flutter/packages/blob/main/packages/video_player/video_player/example/lib/main.dart#L399-L401

Took the above code and moved it to this `listener` function and I added `_videoPlayerController.removeListener(listener);` for removing it before poping:
```
void listener() {
    if (startedPlaying && !_videoPlayerController.value.isPlaying) {
      //Remove the listener before poping
      _videoPlayerController.removeListener(listener);
      Navigator.pop(context);
    }
 }
 ```

**Comment by huycozy** [comment]
This issue is reproducible on the latest plugin version (`video_player: ^2.6.0`) and the plugin sample code as mentioned above.

<details>
<summary>Exception logs</summary>

```bash
======== Exception caught by foundation library ====================================================
The following StateError was thrown while dispatching notifications for VideoPlayerController:
Bad state: No element

When the exception was thrown, this was the stack: 
#0      ListMixin.lastWhere (dart:collection/list.dart:180:5)
#1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4994:40)
#2      Navigator.pop (package:flutter/src/widgets/navigator.dart:2486:27)
#3      _PlayerVideoAndPopPageState.listener (package:video_player_example/main.dart:403:17)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:381:24)
#5      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:495:5)
#6      VideoPlayerController.initialize.eventListener (package:video_player/video_player.dart:398:11)
(elided 13 frames from dart:async)
The VideoPlayerController sending notification was: VideoPlayerController#9536e(VideoPlayerValue(duration: 0:00:07.540000, size: Size(1280.0, 720.0), position: 0:00:07.457000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), captionOffset: 0:00:00.000000, buffered: [DurationRange(start: 0:00:00.000000, end: 0:00:07.539000)], isInitialized: true, isPlaying: false, isLooping: false, isBuffering: true, volume: 1.0, playbackSpeed: 1.0, errorDescription: null))
====================================================================================================

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for VideoPlayerController:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4989 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4989:12)
#3      Navigator.pop (package:flutter/src/widgets/navigator.dart:2486:27)
#4      _PlayerVideoAndPopPageState.listener (package:video_player_example/main.dart:403:17)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:381:24)
#6      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:495:5)
#7      VideoPlayerController._updatePosition (package:video_player/video_player.dart:674:5)
#8      VideoPlayerController.seekTo (package:video_player/video_player.dart:566:5)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
The VideoPlayerController sending notification was: VideoPlayerController#9536e(VideoPlayerValue(duration: 0:00:07.540000, size: Size(1280.0, 720.0), position: 0:00:07.540000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), captionOffset: 0:00:00.000000, buffered: [DurationRange(start: 0:00:00.000000, end: 0:00:07.539000)], isInitialized: true, isPlaying: false, isLooping: false, isBuffering: true, volume: 1.0, playbackSpeed: 1.0, errorDescription: null))
====================================================================================================

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for VideoPlayerController:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4989 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4989:12)
#3      Navigator.pop (package:flutter/src/widgets/navigator.dart:2486:27)
#4      _PlayerVideoAndPopPageState.listener (package:video_player_example/main.dart:403:17)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:381:24)
#6      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:495:5)
#7      VideoPlayerController.initialize.eventListener (package:video_player/video_player.dart:404:11)
(elided 15 frames from class _AssertionError and dart:async)
The VideoPlayerController sending notification was: VideoPlayerController#9536e(VideoPlayerValue(duration: 0:00:07.540000, size: Size(1280.0, 720.0), position: 0:00:07.540000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), captionOffset: 0:00:00.000000, buffered: [DurationRange(start: 0:00:00.000000, end: 0:00:07.539000)], isInitialized: true, isPlaying: false, isLooping: false, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: null))
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#6bcf7](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope, _FocusTraversalGroupMarker], state: NavigatorState#323eb(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5242 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5242:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#13     _invoke (dart:ui/hooks.dart:145:13)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#15     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.7.7 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (10 hours ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.9.0-8.0.pre.19, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.9.0-8.0.pre.19 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d043c93e1a (2 hours ago), 2023-03-15 21:44:10 -0400
    • Engine revision 903ea2eabc
    • Dart version 3.0.0 (build 3.0.0-322.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • SM T225 (mobile)       • R9JT3004VRJ                          • android-arm64  • Android 13 (API 33)
    • iPhone 14 Pro (mobile) • AB2EBB55-6852-40A7-9A12-057128370920 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Any PR is welcome, thank you!

**Comment by gadishimwe** [comment]
Hi @huycozy, I opened a PR to fix it. You may have a look at [it](https://github.com/flutter/packages/pull/3488). Thanks

**Comment by stuartmorgan** [comment]
https://github.com/flutter/packages/pull/3488 has a WIP PR for this if anyone is interested in completing it.
