### ISSUE TITLE
Hot reload not robust to import changes

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#122626]
For a Flutter program, I commented out `main()` and the associated imports, and pasted in an alternative `main()` that used different imports, then I ran the program. I then restored the state of the program back to the original, with the original code and imports, and hit Save. I got the following VM crash. (`routemaster` is one of the imports of the original `main()`.)

```
════════ Exception caught by image resource service ════════════════════════════
E/Dart    ( 8974): ../../third_party/dart/runtime/vm/object.cc: 4717: error: Unable to use class Library:'package:routemaster/routemaster.dart' Class: RouteMap which is not loaded yet.
routemaster.dart:1
E/DartVM  ( 8974): version=2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "android_x64"
E/DartVM  ( 8974): pid=8974, thread=9034, isolate_group=main(0x7de5824f3f60), isolate=main(0x7de582503d30)
E/DartVM  ( 8974): os=android, arch=x64, comp=yes, sim=no
E/DartVM  ( 8974): isolate_instructions=7de3ef267d60, vm_instructions=7de3ef267d60
E/DartVM  ( 8974):   pc 0x00007de3ef38eb7c fp 0x00007de3f390dd90 /data/app/~~Mv-015LE1F_irR9N88t5mQ==/app.clickdating-FeJjOYXUJyJi1UtbuHksyw==/base.apk!/lib/x86_64/libflutter.so+0x1c7ab7c
E/DartVM  ( 8974): -- End of DumpStackTrace
F/libc    ( 8974): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9034 (1.ui), pid 8974 (app.clickdating)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone64_x86_64/emu64x:13/TE1A.220922.010/9219351:userdebug/dev-keys'
Revision: '0'
ABI: 'x86_64'
Timestamp: 2023-03-14 12:54:32.845543218-0600
Process uptime: 443s
Cmdline: app.clickdating
pid: 8974, tid: 9034, name: 1.ui  >>> app.clickdating <<<
uid: 10185
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '../../third_party/dart/runtime/vm/object.cc: 4717: error: Unable to use class Library:'package:routemaster/routemaster.dart' Class: RouteMap which is not loaded yet.'
```

<details>

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.7, on Fedora Linux 36 (Workstation Edition) 6.1.14-100.fc36.x86_64, locale en_US.utf8)
    • Flutter version 3.7.7 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (6 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.5 (Fedora 14.0.5-2.fc36)
    • cmake version 3.25.2
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Fedora Linux 36 (Workstation Edition) 6.1.14-100.fc36.x86_64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by bernaferrari** [comment]
Do you have a reproducible code?

**Comment by lukehutch** [comment]
When I reload now, I get a different but related error:

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CompileTimeError was thrown building ProfileGrid(dirty, state: _ProfileGridState#139b6):
Unimplemented handling of missing static target

The relevant error-causing widget was
ProfileGrid
main.dart:56
When the exception was thrown, this was the stack
#0      StatefulElement.build
framework.dart:5080
#1      ComponentElement.performRebuild
framework.dart:4968
#2      StatefulElement.performRebuild
framework.dart:5133
#3      Element.rebuild
framework.dart:4690
#4      BuildOwner.buildScope
framework.dart:2743
#5      WidgetsBinding.drawFrame
binding.dart:863
#6      RendererBinding._handlePersistentFrameCallback
binding.dart:381
#7      SchedulerBinding._invokeFrameCallback
binding.dart:1289
#8      SchedulerBinding.handleDrawFrame
binding.dart:1218
#9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
binding.dart:942
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)
```

You can reproduce with almost any code, I think, as long as (after tree shaking) there are imports only reachable in one of the two versions of `main`.

I replicated it by replacing my `main()` with this code (flawlessly written by ChatGPT!) then running, then undoing the change back to my `main()`, then saving.

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dating Profile',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Dating Profile'),
        ),
        body: const ProfileGrid(),
      ),
    );
  }
}

class ProfileGrid extends StatefulWidget {
  const ProfileGrid({super.key});

  @override
  _ProfileGridState createState() => _ProfileGridState();
}

class _ProfileGridState extends State<ProfileGrid> {
  final List<String> _profilePictures = [
    'https://picsum.photos/id/100/100/100',
    'https://picsum.photos/id/101/100/100',
    'https://picsum.photos/id/102/100/100',
    'https://picsum.photos/id/103/100/100',
    'https://picsum.photos/id/104/100/100',
    'https://picsum.photos/id/105/100/100',
    'https://picsum.photos/id/106/100/100',
    'https://picsum.photos/id/107/100/100',
    'https://picsum.photos/id/108/100/100',
    'https://picsum.photos/id/109/100/100',
  ];

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 3,
        mainAxisSpacing: 10.0,
        crossAxisSpacing: 10.0,
      ),
      itemCount: _profilePictures.length,
      itemBuilder: (context, index) {
        return Container(
          decoration: BoxDecoration(
            image: DecorationImage(
              image: NetworkImage(_profilePictures[index]),
              fit: BoxFit.cover,
            ),
            borderRadius: BorderRadius.circular(10.0),
          ),
        );
      },
    );
  }
}
```

My `main()` builds a complex routed widget tree, so I can't include all the code here, but one of those classes uses a class that is not used by the ChatGPT code, hence the missing static target error.

**Comment by darshankawar** [comment]
@lukehutch 
Looking at the error log, it seems to be similar to https://github.com/flutter/flutter/issues/120841, so please take a look at that issue and see if it resembles your case too. If so, you can follow-up in it for further updates.

**Comment by lukehutch** [comment]
Hi @darshankawar that doesn't look related at all, the crash dump in that bug has nothing to do with the one I reported.

My bug has to do with whether a static dependency is available after tree shaking. New static dependencies cannot be loaded by hot reload, apparently.

**Comment by darshankawar** [comment]
> Hi @darshankawar that doesn't look related at all, the crash dump in that bug has nothing to do with the one I reported.

Thanks for the feedback. I just thought to share that issue here so that it may be related or just for reference :)

Coming back to your issue, I tried to replicate using sample code and follow the steps to replicate as you mentioned in OP, but didn't see the crash. Maybe I missed some steps to properly replicate it. If you could provide concrete steps that consistently replicates the crash, please provide the same so that we can make this issue actionable.

> I commented out `main()` and the associated imports, and pasted in an alternative `main()` that used different imports, then I ran the program. I then restored the state of the program back to the original, with the original code and imports, and hit Save.

**Comment by rmacnak-google** [comment]
We need a reproduction to investigate: a complete pair of original program and change to be reloaded that triggers the crash.

**Comment by darshankawar** [comment]
I was able to replicate this error following above details on master and stable.

```
Performing hot reload...
Syncing files to device iPhone 13...
Reloaded 2 of 1070 libraries in 276ms (compile: 74 ms, reload: 44 ms, reassemble: 40 ms).
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unimplemented handling of missing static target
#0      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#1      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.7, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.7 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (12 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.9.0-12.0.pre.18, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.9.0-12.0.pre.18 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 28f17d345b (39 minutes ago), 2023-03-20 21:08:41 -0700
    • Engine revision ea6ed14b4e
    • Dart version 3.0.0 (build 3.0.0-345.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by christopherfujino** [comment]
> @christopherfujino to myself, try to create repro instructions for the VM crash from the original post.

Ahh, looks like the stacktrace from the original post is indeed https://github.com/flutter/flutter/issues/120841.

> import 'package:flutter/material.dart';
>
> var debug = true;
>
> void main() {
>   Timer.periodic(const Duration(milliseconds: 1000), (t) => print(debug));
>   runApp(Container());
> }

I believe the error `E/flutter ( 5127): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unimplemented handling of missing static target` is then expected in this situation as you have changed a global/static definition. Please see https://docs.flutter.dev/development/tools/hot-reload#recent-code-change-is-included-but-app-state-is-excluded for more context.

@lukehutch is there another minimal repro you can provide that is not either a case of https://github.com/flutter/flutter/issues/120841 or a case of changing a static/global across a hot reload?

**Comment by mraleph** [comment]
Arguably if this is an expected error then error message should be updated to say something less cryptic than `Unimplemented handling of missing static target`, e.g. `Trying to use a field which was removed by hot reload` etc. /cc @rmacnak-google

**Comment by lukehutch** [comment]
@christopherfujino This could well be the same as #120841. However, I didn't get a stacktrace, and there was only one isolate (at least in my code), so the cause might be slightly different.

@mraleph admittedly I wouldn't have high expectations for any platform that supports hot sync being able to load fundamentally different code across restarts. So I'm OK with ignoring the second crash (the exception I got when I tried to replicate the first crash). Yes, the error message could be improved.

**Comment by rmacnak-google** [comment]
The exception happens because the program had captured old code that depended on things that were removed, mixing the old and new program. See https://github.com/dart-lang/sdk/wiki/Hot-reload

The correct behavior in this case would be a  `NoSuchMethodError(debug, [])` exception. The implementation used to handle that, but it was lost in the transition to kernel / Dart 2. It's a more difficult fix than changing the error message because things should also be delayed to runtime. Sometimes things may even succeed if, say, the missing static target is on a branch that is not taken.

The SIGABRT that started this issue is some other more serious bug in the VM.

**Comment by a-siva** [comment]
Closing issue as a fix seems to have been submitted earlier.
@lukehutch if you think the problem is not fixed by that change please reopen issue.
