### ISSUE TITLE
Windows antivirus reports malicius impellerc.exe and blocks dart.exe

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#122797]
After updating flutter beta from 3.8.0 -> 3.9.0 I got following error message and windows anitivirus kicked off when rebuilding my flutter windows app.:

```
Finished with error: Flutter failed to run "C:\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe --sksl --iplr --json --sl=build\flutter_assets\shaders/ink_sparkle.frag --spirv=build\flutter_assets\shaders/ink_sparkle.frag.spirv --input=C:\Flutter\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag --input-type=frag --include=C:\Flutter\flutter\packages\flutter\lib\src\material\shaders --include=C:\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:642:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1301:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>



```
and my antivurys kicked off with following information (in norwegian though...):
![image](https://user-images.githubusercontent.com/11217296/225599390-663f72d0-2f12-441b-a49d-01d00318f8f3.png)

Google translated to:
```
App or process blocked: dart.exe

Blocked by: Reduction of attack surface
Rule: Block executables from running unless they meet occurrence, age, or trusted list criteria

Blocked items: C:\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe
```
I am in an managed network, and have few tools to overrun this situation.

Why is `impellerc.exe` in the malicius list anyway, can it be granted or remedied ?

---

Flutter doctor:
```
PS C:\FlutterProjects\mOffice> flutter doctor -v
[√] Flutter (Channel beta, 3.9.0-1.0.pre.2, on Microsoft Windows [Version 10.0.22621.1413], locale nb-NO)
    • Flutter version 3.9.0-1.0.pre.2 on channel beta at c:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f732038a8c (12 hours ago), 2023-03-15 16:37:48 -0700
    • Engine revision dec409804a
    • Dart version 3.0.0 (build 3.0.0-290.1.beta)
    • DevTools version 2.22.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\RoarGronmo\AppData\Local\Android\sdk
    • Platform android-UpsideDownCake, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android Studio\Android Studio 2022.3.1.9\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2021.2.1.16
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2021.3.1.17
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2022.1.1.21
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2022.1.1.13
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.65
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.63

[√] Network resources
    • All expected network resources are available.

• No issues found!
PS C:\FlutterProjects\mOffice>

```

**Comment by darshankawar** [comment]
@RoarGronmo 
Thanks for the report. I think you are hitting https://github.com/flutter/flutter/issues/46696 so please follow-up in it for further updates. You may also share your findings in it for better tracking.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
