### ISSUE TITLE
NoSuchMethodError: io.flutter.view.FlutterView.getDisplay

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#12297]
```
E: java.lang.NoSuchMethodError: io.flutter.view.FlutterView.getDisplay
       at io.flutter.view.FlutterView.updateViewportMetrics(FlutterView.java:667)
       at io.flutter.view.FlutterView.fitSystemWindows(FlutterView.java:521)
       at android.view.ViewGroup.fitSystemWindows(ViewGroup.java:5102)
       at android.view.ViewGroup.fitSystemWindows(ViewGroup.java:5102)
       at android.view.ViewGroup.fitSystemWindows(ViewGroup.java:5102)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.fitSystemWindows(PhoneWindow.java:2347)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1203)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(Native Method)
E: FATAL EXCEPTION: main
   java.lang.NoSuchMethodError: io.flutter.view.FlutterView.getDisplay
       at io.flutter.view.FlutterView.updateViewportMetrics(FlutterView.java:667)
       at io.flutter.view.FlutterView.fitSystemWindows(FlutterView.java:521)
       at android.view.ViewGroup.fitSystemWindows(ViewGroup.java:5102)
       at android.view.ViewGroup.fitSystemWindows(ViewGroup.java:5102)
       at android.view.ViewGroup.fitSystemWindows(ViewGroup.java:5102)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.fitSystemWindows(PhoneWindow.java:2347)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1203)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(Native Method)
```

reproducible in standard emulator
```
Name: Nexus_5X_API_16 CPU/
ABI: Intel Atom (x86)
Path: C:\Users\j.android\avd\Nexus_5X_API_16.avd
Target: default [] (API level 16)
Skin: nexus_5x SD
Card: 100M hw.d
Pad: no runtime.network.
speed: full
```

```
D:\DaaNuu\van_mobile_app\van_mobile_flutter>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel master)
    • Flutter at D:\AndroidDev\flutter
    • Framework revision a0e91bf9e8 (2 days ago), 2017-09-26 15:21:01 +0200
    • Engine revision 005212683c
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at D:\AndroidDev\AndroidSDK
    • Platform android-26, build-tools 26.0.2
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[√] Connected devices
    • emulator-5554 • emulator-5554 • android-x86 • Android 4.1.2 (API 16) (emulator)


```

**Comment by Alexays** [comment]
You need to update flutter
```
flutter upgrade
```

**Comment by JFixby** [comment]
i did it is the same

**Comment by Alexays** [comment]
Do
```
flutter channel master
```

**Comment by Hixie** [comment]
It's not clear how to reproduce this. Do you still have the code that caused this problem?

**Comment by JFixby** [comment]
No.
Probably outdated. I'll close it.
