### ISSUE TITLE
Methods marked with @UiThread must be executed on the main thread. Current thread: WallpaperService

### ISSUE THREAD

**Issue by LondonX** [flutter/flutter#122900]
I'm trying to run `FlutterEngine` in Android `WallpaperService`, every thing works so far except some VIVO phone crashed and throw the `java.lang.RuntimeException` with message in title. 

## Steps to Reproduce
1. When `WallpaperService#onCreateEngine` getting called, and `WallpaperService.Engine#onCreate` getting called.
2. Some VIVO phone seem start the `WallpaperService` in a thread named "WallpaperService".

**Expected results:** 
Pass the `@UiThread` checking in Android Service

**Actual results:** 
Crash when calling `FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:36)`

<details>
<summary>LiveWallpaperFltService.kt</summary>

```kotlin
package com.LondonX.live_wallpaper_flt.service

import android.content.res.Configuration
import android.service.wallpaper.WallpaperService
import android.text.format.DateFormat
import android.view.SurfaceHolder
import android.view.ViewConfiguration
import com.LondonX.live_wallpaper_flt.entity.Config
import com.google.gson.Gson
import io.flutter.FlutterInjector
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.FlutterJNI
import io.flutter.embedding.engine.dart.DartExecutor
import io.flutter.embedding.engine.renderer.FlutterRenderer
import io.flutter.embedding.engine.systemchannels.SettingsChannel
import kotlinx.coroutines.*
import java.io.File

private const val TAG = "[live_wallpaper_flt]"

class LiveWallpaperFltService : WallpaperService() {

    override fun onCreateEngine(): Engine {
        return object : Engine() {
            private val config by lazy {
                val json = File(filesDir, "live_wallpaper_config.json").readText()
                Gson().fromJson(json, Config::class.java)
                    ?: throw Exception("${TAG}invalid config file, make sure you called LiveWallpaperFlt.instance.applyConfig first.")
            }
            private lateinit var flutterEngine: FlutterEngine

            private val scope = CoroutineScope(Dispatchers.Main)
            private var refreshJob: Job? = null

            private var width: Int? = null
            private var height: Int? = null
            private var isDark = false

            override fun onCreate(surfaceHolder: SurfaceHolder?) {
                super.onCreate(surfaceHolder)
                flutterEngine = FlutterEngine(this@LiveWallpaperFltService)
                flutterEngine.dartExecutor.executeDartEntrypoint(
                    DartExecutor.DartEntrypoint(
                        FlutterInjector.instance().flutterLoader().findAppBundlePath(),
                        config.entryFunction,
                    ),
                    listOf("is_started_from_wallpaper_service"),
                )
                isDark = isInDarkMode()
                applyPlatformDarkMode()
            }

            private fun engineScope(f: suspend FlutterEngine.() -> Unit) {
                scope.launch {
                    f.invoke(flutterEngine)
                }
            }

            private fun FlutterEngine.isAttached(): Boolean {
                surfaceHolder?.surface ?: return false
                val flutterJNI = FlutterRenderer::class.java.getDeclaredField("flutterJNI")
                    .apply { isAccessible = true }.get(renderer) as? FlutterJNI
                return flutterJNI?.isAttached == true
            }

            override fun onVisibilityChanged(visible: Boolean) {
                super.onVisibilityChanged(visible)
                if (visible) {
                    refreshJob = scope.launch {
                        while (true) {
                            delay(24)
                            if (flutterEngine.isAttached()) {
                                applyViewportMetrics()
                                if (isDark != isInDarkMode()) {
                                    isDark = isInDarkMode()
                                    applyPlatformDarkMode()
                                }
                            }
                        }
                    }
                    engineScope {
                        lifecycleChannel.appIsResumed()
                        if (flutterEngine.isAttached()) {
                            renderer.startRenderingToSurface(surfaceHolder.surface!!, true)
                        }
                    }
                } else {
                    refreshJob?.cancel()
                    engineScope {
                        lifecycleChannel.appIsPaused()
                        if (flutterEngine.isAttached()) {
                            renderer.stopRenderingToSurface()
                        }
                        lifecycleChannel.appIsInactive()
                    }
                }
            }

            override fun onDestroy() {
                refreshJob?.cancel()
                engineScope {
                    lifecycleChannel.appIsDetached()
                    destroy()
                }
                super.onDestroy()
            }

            override fun onSurfaceChanged(
                holder: SurfaceHolder?, format: Int, width: Int, height: Int
            ) {
                super.onSurfaceChanged(holder, format, width, height)
                this.width = width
                this.height = height
                if (!flutterEngine.renderer.isDisplayingFlutterUi) return
                applyViewportMetrics()
            }

            private fun applyViewportMetrics() {
                val width = this.width ?: resources.displayMetrics.widthPixels
                val height = this.height ?: resources.displayMetrics.heightPixels
                val viewportMetrics = FlutterRenderer.ViewportMetrics()
                viewportMetrics.devicePixelRatio = resources.displayMetrics.density
                viewportMetrics.height = height
                viewportMetrics.width = width
                viewportMetrics.physicalTouchSlop =
                    ViewConfiguration.get(this@LiveWallpaperFltService).scaledTouchSlop
                engineScope {
                    if (flutterEngine.isAttached()) {
                        renderer.setViewportMetrics(viewportMetrics)
                        renderer.surfaceChanged(width, height)
                    }
                }
            }

            private fun isInDarkMode(): Boolean {
                return resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK == Configuration.UI_MODE_NIGHT_YES
            }

            private fun applyPlatformDarkMode() {
                engineScope {
                    settingsChannel.startMessage()
                        .setTextScaleFactor(resources.configuration.fontScale)
                        .setUse24HourFormat(DateFormat.is24HourFormat(this@LiveWallpaperFltService))
                        .setPlatformBrightness(
                            if (isInDarkMode()) {
                                SettingsChannel.PlatformBrightness.dark
                            } else {
                                SettingsChannel.PlatformBrightness.light
                            }
                        ).send()
                }
            }
        }
    }
}
```

</details>

Still crash even I tried using `engineScope` to wrap codes running on `CoroutineScope(Dispatchers.Main)`.

<details>
<summary>Logs</summary>

```
Fatal Exception: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: WallpaperService
       at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:36)
       at io.flutter.embedding.engine.FlutterJNI.setPlatformMessageHandler(FlutterJNI.java)
       at io.flutter.embedding.engine.dart.DartExecutor.onAttachedToJNI(DartExecutor.java:11)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:58)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:8)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:11)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:6)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:1)
       at com.LondonX.live_wallpaper_flt.service.LiveWallpaperFltService$onCreateEngine$1.<init>(LiveWallpaperFltService.java:18)
       at com.LondonX.live_wallpaper_flt.service.LiveWallpaperFltService.onCreateEngine(LiveWallpaperFltService.java:2)
       at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:2192)
       at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```
</details>

<details>
<summary>flutter analyze</summary>

```
flutter analyze
Analyzing wallpaper_gpt...                                              
No issues found! (ran in 7.0s)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.7 on channel stable at /usr/local/Caskroom/flutter/1.22.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (9 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/london/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc2
    • ANDROID_HOME = /Users/london/Library/Android/sdk/
    • ANDROID_SDK_ROOT = /Users/london/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • London’s iPhone (mobile) • 00008101-001E39DE3A63001E • ios            • iOS 16.3.1 20D67
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by huycozy** [comment]
Please check these answers to see if they can work for you or not:

- https://github.com/flutter/flutter/issues/34993
- https://stackoverflow.com/questions/57447702/flutter-plugin-methods-marked-with-uithread-must-be-executed-on-the-main-thre

Also, for the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include complex implementation code or 3rd party plugins. Please try to provide such a sample. Thank you!

**Comment by LondonX** [comment]
Thanks for reply, but the link has no helps, my problem is VIVO(may be iqoo) start the `WallpaperService` in a thread named "WallpaperService", even I wrap the operations in `MainScope().launch` or `handle.post`, the `@UIThread` check still failed.

**Comment by huycozy** [comment]
Does it happen on another device? Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.

**Comment by LondonX** [comment]
As my app not has much DAU (around 400), for now, it happens on 100% vivo device, which running 68% Android 12 and 32% Android 13, device codes are V2111, V2105, V2146, Y21A.

I published my live wallpaper lib to github [live_wallpaper_flt](https://github.com/LondonX/live_wallpaper_flt), see if any one can reproduce the crash.
#### Usage
<details>
<summary>Add service in AndroidMenifest.xml</summary>

  ```xml
  <application>
    <service
        android:name="com.LondonX.live_wallpaper_flt.service.LiveWallpaperFltService"
        android:enabled="true"
        android:exported="true"
        android:permission="android.permission.BIND_WALLPAPER">
        <intent-filter>
            <action android:name="android.service.wallpaper.WallpaperService" />
        </intent-filter>
        <meta-data
            android:name="android.service.wallpaper"
            android:resource="@xml/live_wallpaper_flt" />
    </service>
  </application>
  ```

</details>
<details>
<summary>Add live_wallpaper_flt.xml into res/xml</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<wallpaper xmlns:android="http://schemas.android.com/apk/res/android"
    android:author="@string/live_wallpaper_flt_author"
    android:description="@string/live_wallpaper_flt_description"
    android:thumbnail="@mipmap/live_wallpaper_flt_thumbnail" />
```

</details>

<details>
<summary>Modify main.dart</summary>

```dart
import 'package:live_wallpaper_flt/live_wallpaper_flt.dart';

void main(List<String> args) {
  runApp(
    LiveWallpaperFlt.isStartFromService(args)
        ? Container(color: Colors.red)
        : const MyApp(),
  );
}
```

</details>

<details>
<summary>Set wallpaper</summary>

```dart
if (Platform.isAndroid) {
  await LiveWallpaperFlt.instance.applyConfig();
  await LiveWallpaperFlt.instance.requestSetWallpaper();
}
```

</details>

**Comment by huycozy** [comment]
Thanks for your response but it seems you are missing some res:

```
<wallpaper xmlns:android="http://schemas.android.com/apk/res/android"
    android:author="@string/live_wallpaper_flt_author"
    android:description="@string/live_wallpaper_flt_description"
    android:thumbnail="@mipmap/live_wallpaper_flt_thumbnail" />
```

Please add these res and also commit all changes from usage above so that I can update the code and run it on my devices. Thank you!

**Comment by LondonX** [comment]
Sorry, I assumed these are  common used values as you may write you own.

As in my app, this is the `strings.xml` in `res/values`
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="live_wallpaper_flt_author">Wallpaper FLT</string>
    <string name="live_wallpaper_flt_description">Wallpaper FLT</string>
</resources>
```
and this is the `live_wallpaper_flt_thumbnail.webp`(zipped) in `res/mipmap-xxxhdpi`
[live_wallpaper_flt_thumbnail.webp.zip](https://github.com/flutter/flutter/files/11045905/live_wallpaper_flt_thumbnail.webp.zip)

**Comment by huycozy** [comment]
Thanks for providing the remaining res. It runs normally now, but I don't see a crash similar to yours. Verifying this issue on `Realme 6, Android 11`:

https://user-images.githubusercontent.com/104349824/227108977-390cbd71-7b89-48d1-9d84-2f675cf6110f.mp4

Do you notice this issue only happens on your device or other devices as well? 

Also, I see there is a solution that you may want to apply for this case, see https://github.com/flutter/flutter/issues/34993#issue-459900986

**Comment by LondonX** [comment]
Thanks for trying my lib. Yes, the crash only happens on vivo for now, models are V2111, V2105, V2146, V2065, Y21A, running Android 12 and Android 13.

Not like the case you mentioned, these devices crash with quite precise thread name "WallpaperService", wich I suspect vivo changes the launch procedure of `WallpaperService` of android.

* Stacktrace
  ```
  Fatal Exception: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: WallpaperService
         at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:36)
         at io.flutter.embedding.engine.FlutterJNI.setPlatformMessageHandler(FlutterJNI.java)
         at io.flutter.embedding.engine.dart.DartExecutor.onAttachedToJNI(DartExecutor.java:11)
         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:58)
         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:8)
         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:11)
         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:6)
         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:1)
         at com.LondonX.live_wallpaper_flt.service.LiveWallpaperFltService$onCreateEngine$1.onCreate(LiveWallpaperFltService.java:7)
         at android.service.wallpaper.WallpaperService$Engine.attach(WallpaperService.java:1365)
         at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:2239)
         at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
         at android.os.Handler.dispatchMessage(Handler.java:106)
         at android.os.Looper.loopOnce(Looper.java:233)
         at android.os.Looper.loop(Looper.java:334)
         at android.os.HandlerThread.run(HandlerThread.java:67)
  ```

**Comment by huycozy** [comment]
It seems to be a device-specific issue since I can not reproduce it. Labeling the issue for further investigation. 

Complete sample code: [live_wallpaper_flt.zip](https://github.com/flutter/flutter/files/11049783/live_wallpaper_flt.zip)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (34 hours ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.9.0-15.0.pre.19, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.9.0-15.0.pre.19 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c0878572ba (75 minutes ago), 2023-03-22 21:44:02 -0400
    • Engine revision cd0a6ef932
    • Dart version 3.0.0 (build 3.0.0-356.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by LondonX** [comment]
Thank you any way, I will leave my eyes on this issue👁

**Comment by zyxia** [comment]
Does this problem solved?
