### ISSUE TITLE
[camera_windows] preview aspect ratio doesn't match the camera/recorded video has black bars

### ISSUE THREAD

**Issue by hillelcoren** [flutter/flutter#122966]
HI,

When opening my USB webcam using the built-in Windows camera app I see a reasonably high quality 1920 x 1080 (16:9) image. 

When accessing the same webcam using the camera_windows plugin the preview reports a size of 320 x 240 (4:3). When recording a video the video has a resolution of 1920 x 1080 but there are black bars on the left and right sides of the video.

It's worth noting changing the ResolutionPreset value doesn't appear to affect the quality of the preview or recorded video.

Thanks for your help!

**Comment by exaby73** [comment]
Hello @hillelcoren. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by hillelcoren** [comment]
Hi @exaby73, thanks for your response!

This problem can be reproduced using the example project for the package.

https://github.com/flutter/packages/tree/main/packages/camera/camera_windows/example

Regardless of which resolution preset is selected black bars are always added to the recorded video. It's worth noting in the example UI the black bars are only shown when the resolution preset is set to 'high' or better. 

<details>

<summary>flutter doctor -v</summary>

```
$ flutter doctor -v
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.19045.2728], locale en-US)
    • Flutter version 3.7.5 on channel stable at C:\Users\hillel\Documents\flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision c07f788888 (4 weeks ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hillel\AppData\Local\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30204.135
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\hillel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.65
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

<details>

<summary>flutter run -v</summary>

```
$ flutter run -v
[   +8 ms] executing: [C:\Users\hillel\Documents\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c07f7888888435fd9df505aa2efc38d3cf65681b
[        ] executing: [C:\Users\hillel\Documents\flutter/] git tag --points-at c07f7888888435fd9df505aa2efc38d3cf65681b
[  +40 ms] Exit code 0 from: git tag --points-at c07f7888888435fd9df505aa2efc38d3cf65681b
[        ] 3.7.5
[   +7 ms] executing: [C:\Users\hillel\Documents\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\Users\hillel\Documents\flutter/] git ls-remote --get-url origin
[  +28 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git
[  +38 ms] executing: [C:\Users\hillel\Documents\flutter/] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +49 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] executing: C:\Users\hillel\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +51 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +38 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
[        ] Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.65
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.76
[   +7 ms] "flutter run" took 303ms.
[  +18 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:499:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1381:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +241 ms] ensureAnalyticsSent: 239ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

**Comment by exaby73** [comment]
Hello. I cannot reproduce any black bars. Could you provide information about the versions of plugins you're using?

**Comment by hillelcoren** [comment]
I'm using `camera_windows: ^0.2.1+5` 

Maybe it's related to the specific webcam resolution?

**Comment by hillelcoren** [comment]
One problem you may be able to reproduce is that the dimensions of the recorded video (for me at least) was the same regardless of the resolution preset.

**Comment by exaby73** [comment]
Indeed the resolution in my experience is always the same, 720p in my case (laptop webcam is 720p), no matter which resolution I am recording on. But this issue, in my opinion deserves it's own issue. Please do also see if there is already an issue present which describes this.

As for the black bars, could you share a screen recording that demonstrates you recording the video and playing it back from the File Explorer? Also, would be helpful if you gave provide you webcam details, like model and resolution

**Comment by hillelcoren** [comment]
My sense is the two issues are likely related, the black bars are caused by the resolution mismatch.

I can produce the same problem using the 'take picture' option, here's a sample photo.

![PhotoCapture_2023_0320_182626_760](https://user-images.githubusercontent.com/4629496/226405327-bea5ed4c-dfac-4cf4-9980-a4c2b2e4aa2d.jpeg)

**Comment by exaby73** [comment]
Could you provide details about your webcam as well? Including what it's native resolution it vs what you get in the Flutter app?

**Comment by hillelcoren** [comment]
The webcam is made by Silver Line, I'm not sure the exact model. When I use Microsoft's built-in camera app to use the webcam to take a picture it captures a 1920 x 1080 photo without any black bars.

**Comment by exaby73** [comment]
Okay thanks for the input. I'll label this issue for further insights from the team. This may be device specific. If you are ever able to test with another webcam or a laptop webcam, please do provide details about it here. As for me, I cannot reproduce it with my setup (Integrated webcam on a Dell G15)

**Comment by kahochschild1** [comment]
Was there a solution for this problem?

**Comment by bawahakim** [comment]
I can also reproduce this on windows with a Logitech Brio 4k

**Comment by mchochula** [comment]
Hello, is there any ETA for the fix? Thank you

**Comment by Vidhanth** [comment]
> I can also reproduce this on windows with a Logitech Brio 4k

Have you managed to find a fix or a workaround? I'm using this library for a very important client and facing the same black bars issue.

**Comment by dasyad00** [comment]
I'm using this library for an upcoming project and it appears this issue is still a problem. Here are my personal findings:
- The Logitech Brio 4K is the only known affected webcam with the black bars. Other webcams do not show any black bars (tested Lenovo laptop webcam, HP laptop webcam)
- The black bars are visible for all `ResolutionPreset`s.
- The Logitech Brio 4K camera stream does not contain black bars in other programs (tested Windows 11 Camera, and Discord) nor using OpenCV with [`cv::CAP_MSMF`](https://docs.opencv.org/3.4/d4/d15/group__videoio__flags__base.html#gga023786be1ee68a9105bf2e48c700294da278d5ad4907c9c0fe6d1c6104b746019)
- Inside `TextureHandler::ConvertPixelBufferForFlutter` in `texture_handler.cpp`, if you check for black pixels, they are in the range `0 <= x <= 160`.

```c++
printf("pitch black at: ");
for (uint32_t y = 0; y < preview_frame_height_; y++) {
    uint32_t xStart = 0;
    for (uint32_t x = 0; x < preview_frame_width_; x++) {
    uint32_t sp = (y * preview_frame_width_) + x;

    if(src[sp].r == 0 && src[sp].g == 0 && src[sp].b == 0) {
        if (xStart == 0) {
        xStart = x;
        }
    } else {
        if (xStart != 0) {
        printf("(%u-%u, %u) ", xStart, x, y);
        xStart = 0;
        }
    };

    // mapping MFVideoFormatRGB32Pixel to FlutterDesktopPixel...
    }
}
printf("\n");
```

Currently I am suspecting either a missing camera initialization step in Microsoft Media Foundation, or an incomplete image buffer deep copy. Hopefully these insights will help other developers debug this issue.
