### ISSUE TITLE
[webview_flutter] crash with Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by a313** [flutter/flutter#123094]
Relatively rare crash that came in through Crashlytics, so no direct steps to reproduce. Crash is as follows:
```
Fatal Exception: java.lang.NullPointerException:
       at java.util.Objects.requireNonNull(Objects.java:220)
       at io.flutter.plugins.webviewflutter.WebChromeClientFlutterApiImpl.onProgressChanged(WebChromeClientFlutterApiImpl.java:13)
       at io.flutter.plugins.webviewflutter.WebChromeClientHostApiImpl$WebChromeClientImpl.onProgressChanged(WebChromeClientHostApiImpl.java:9)
       at ua.handleMessage(ua.java:278)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

It happened on Android 11

package version:
  ```
webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      sha256: b6cd42db3ced5411f3d01599906156885b18e4188f7065a8a351eb84bee347e0
      url: "https://pub.dev"
    source: hosted
    version: "4.0.6"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      sha256: c849dcb6bf7367f696869006fb9575c15bdc6a1d624ae13f12de5a147a740b12
      url: "https://pub.dev"
    source: hosted
    version: "3.4.2"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      sha256: "1939c39e2150fb4d30fd3cc59a891a49fed9935db53007df633ed83581b6117b"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      sha256: ab12479f7a0cf112b9420c36aaf206a1ca47cd60cd42de74a4be2e97a697587b
      url: "https://pub.dev"
    source: hosted
    version: "3.2.1"
```

Flutter (Channel stable, 3.7.6, on macOS 12.6) with no issues found!

**Comment by huycozy** [comment]
Thanks for the report, @a313 
How frequently does it happen? Can you please provide the list of affected device info and the percentage occurrence of the crash? Thanks!

**Comment by huycozy** [comment]
Thanks for your response. However, there was a similar issue reported recently at https://github.com/flutter/flutter/issues/123004. 

You can see the same error message at https://github.com/flutter/flutter/issues/123004#issuecomment-1477732165. Since it's a screenshot, I will copy your stack trace above and leave a comment there for better investigation.

Closing this issue in favor of #123004. Please follow up on it for further updates.
