### ISSUE TITLE
API `/api/github/webhook-branch-subscription` is failing every minute triggering the GAE alert

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#123032]
```
Condition
GAE Application - Response count (filtered) (grouped) [99TH PERCENTILE]

Metric
appengine.googleapis.com/http/server/response_count

Threshold
above 0.02

Observed
0.083
```

```
> INFO 2023-03-20T16:19:42.581Z the branch parsed from string request is flutter-3.9-candidate.10
> INFO 2023-03-20T16:19:42.581Z the id used to create branch key was flutter/flutter/flutter-3.9-candidate.10
> INFO 2023-03-20T16:19:42.786Z flutter/recipes commits: ({"commit":"747fcb15c92a1ba20f98d0c9e9f1a68f885feb18","tree":"60c540d79f8a4cbb1c502b5f70282fa4e21bbb29","author":{"name":"Keyong Han","email":"keyonghan@google.com","time":"2023-03-17T23:16:52.000Z"},"committer":{"name":"CQ Bot Account","email":"flutter-scoped@luci-project-accounts.iam.gserviceaccount.com","time":"2023-03-17T23:16:52.000Z"},"message":"Support build+test for devicelab ios tests\n\nSuccessful LED run based on https://github.com/flutter/flutter/pull/111164\n\nhttps://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/a43684afc067cba831ca3268c9621008cae1b916634886dada4c5c4a8c3d3587/+/build.proto\n\nChange-Id: Ia76e0593ddfa64939bca67ee3d68391b06ac558c\nBug: https://github.com/flutter/flutter/issues/103542\nReviewed-on: https://flutter-review.googlesource.com/c/recipes/+/40582\nReviewed-by: Godofredo Contreras <godofredoc@google.com>\nCommit-Queue: Keyong Han <keyonghan@google.com>\n"}, {"commit":"a0469282e638ed1d016e30a40effa9b3ccd317f2","tree":"40aa78cf52c94bb4f9fc26a6fa3bfa90cb454c5a","author":{"name":"Christopher Fujino","email":"fujino@google.com","time":"2023-03-17T22:02:15.000Z"},"committer":{"name":"CQ Bot Account","email":"flutter-scoped@luci-project-accounts.iam.gserviceaccount.com","time":"2023-03-17T22:02:15.000Z"},"message":"remove --sound-null-safety usage\n\nThis flag is already the default and will be removed.\n\nBug: https://github.com/flutter/flutter/issues/118810\nChange-Id: If86d60f2580377f0b9ad7cd450906ebae3f3eb61\nReviewed-on: https://flutter-review.googlesource.com/c/recipes/+/40800\nReviewed-by: Zach Anderson <zra@google.com>\nCommit-Queue: Christopher Fujino <fujino@google.com>\n"}, {"commit":"70272b5bb26a06fdf11e3ca73d650ecdd9f5c93a","tree":"ad2c5dba602a9f61b841634ef7d4f0785abf7cda","author":{"name":"Godofredo Contreras","email":"godofredoc@google.com","time":"2023-03-17T21:45:10.000Z"},"committer":{"name":"CQ Bot Account","email":"flutter-scoped@luci-project-accounts.iam.gserviceaccount.com","time":"2023-03-17T21:45:10.000Z"},"message":"Reland \"Migrate android debug artifacts to gn+ninja.\"\n\nThis reverts commit f0ca822b809d38beb23e2dfc12d124fcafba5376.\n\nReason for revert: The problems this CL was reverted for was actually caused by the removal of dimensions from the build drones.\n\nOriginal change's description:\n> Revert \"Migrate android debug artifacts to gn+ninja.\"\n>\n> This reverts commit 42e256d74dc9dc64f0181139016d214286c80fa1.\n>\n> Reason for revert: Android AOT builds are failing.\n>\n> Original change's description:\n> > Migrate android debug artifacts to gn+ninja.\n> >\n> > These artifacts have been validated for several months on staging and\n> > engine v2 recipes.\n> >\n> > Change-Id: I94a3fc37df239f547a7eff38c8439041eb395188\n> > Reviewed-on: https://flutter-review.googlesource.com/c/recipes/+/40660\n> > Reviewed-by: Zach Anderson <zra@google.com>\n> > Commit-Queue: Godofredo Contreras <godofredoc@google.com>\n>\n> TBR=zra@google.com,godofredoc@google.com,flutter-scoped@luci-project-accounts.iam.gserviceaccount.com\n>\n> Change-Id: Ic4cec8e1e0dc3a59fecd0200149b6d51f1b19f75\n> No-Presubmit: true\n> No-Tree-Checks: true\n> No-Try: true\n> Reviewed-on: https://flutter-review.googlesource.com/c/recipes/+/40740\n> Commit-Queue: Godofredo Contreras <godofredoc@google.com>\n> Reviewed-by: Godofredo Contreras <godofredoc@google.com>\n\n# Not skipping CQ checks because this is a reland.\n\nChange-Id: Ia07d2c9e780c39c02d604729c79296cc6fb34caf\nReviewed-on: https://flutter-review.googlesource.com/c/recipes/+/40780\nReviewed-by: Godofredo Contreras <godofredoc@google.com>\nCommit-Queue: Godofredo Contreras <godofredoc@google.com>\nReviewed-by: Zach Anderson <zra@google.com>\n"}, ..., {"commit":"6e0d66376975c492dfa9ec43276212d11bf8bc97","tree":"37a27327a0fbc4d7409d38e2e3d2d1825d0d7ec4","author":{"name":"Drew Roen","email":"drewroen@google.com","time":"2023-02-06T21:58:53.000Z"},"committer":{"name":"CQ Bot Account","email":"flutter-scoped@luci-project-accounts.iam.gserviceaccount.com","time":"2023-02-06T21:58:53.000Z"},"message":"Change dependency from fuchsia/gsutil to depot_tools/gsutil in order to unblock tree\n\nBug: https://github.com/flutter/flutter/issues/120111\nChange-Id: I492f86d3db76eab86c9e52a18d64c8eb08da2700\nReviewed-on: https://flutter-review.googlesource.com/c/recipes/+/38621\nCommit-Queue: Drew Roen <drewroen@google.com>\nReviewed-by: Yusuf Mohsinally <mohsinally@google.com>\n"}, {"commit":"c4e46327c5a5d4daf066e326c1dfedaa967c9a14","tree":"59761ea82f15d80883fa45e6b9e700e2093d5963","author":{"name":"Jesse Seales","email":"jseales@google.com","time":"2023-02-06T20:39:47.000Z"},"committer":{"name":"CQ Bot Account","email":"flutter-scoped@luci-project-accounts.iam.gserviceaccount.com","time":"2023-02-06T20:39:47.000Z"},"message":"Update release tagging & pushing recipe to use gh cli and new github PAT\n\nThe previous iteration of the recipe did not use the gh cli which created failures. This recipe uses the gh cli and also pushes after authenticating with a new github PAT generated for this workflow. That new PAT is stored in GCP.\n\nsuccessful led run: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/jseales_google.com/033d40a2747a0873179eadb866e20329b2c3927ceef8fd547630b5fb11c2f585/+/build.proto\n\nChange-Id: I6ad4538b887930ee22acc9d4695a0b27fb3a7389\nReviewed-on: https://flutter-review.googlesource.com/c/recipes/+/38320\nCommit-Queue: Jesse Seales <jseales@google.com>\nReviewed-by: Casey Hillers <chillers@google.com>\nReviewed-by: Godofredo Contreras <godofredoc@google.com>\n"})
> INFO 2023-03-20T16:19:42.786Z neat_cache: reading cache entry for "configgithubToken-flutter/flutter"
> ERROR 2023-03-20T16:19:44.368Z GitHub Error: Access Forbidden #0 GitHub.handleStatusCode (package:github/src/common/github.dart:460:9) #1 GitHub.request (package:github/src/common/github.dart:426:7) <asynchronous suspension> #2 PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:38:20) <asynchronous suspension> #3 GithubService.listCommits (package:cocoon_service/src/service/github_service.dart:42:5) <asynchronous suspension> #4 BranchService.branchFlutterRecipes.<anonymous closure> (package:cocoon_service/src/service/branch_service.dart:106:19) <asynchronous suspension> #5 RetryOptions.retry (package:retry/retry.dart:131:16) <asynchronous suspension> #6 BranchService.branchFlutterRecipes (package:cocoon_service/src/service/branch_service.dart:105:53) <asynchronous suspension> #7 GithubBranchWebhookSubscription.post (package:cocoon_service/src/request_handlers/github/branch_subscription.dart:49:7) <asynchronous suspension> #8 RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:24) <asynchronous suspension> #9 SubscriptionHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/subscription_handler.dart:139:19) <asynchronous suspension> #10 SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:5) <asynchronous suspension> #11 main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:288:11) <asynchronous suspension>
> ERROR 2023-03-20T16:19:44.369Z Failed to process Instance of 'PushMessage'
> ERROR 2023-03-20T16:19:44.370Z Purged write lock from cache
```

**Comment by keyonghan** [comment]
Oldest message is >24 hours. Purged all to see how it goes.

**Comment by drewroengoogle** [comment]
Based on the logs, the only reason I can see this failing is that we are making too many requests through the github api. Maybe it would help to see when new github tokens are being created versus when old tokens are being used?

**Comment by CaseyHillers** [comment]
It does run into a 3rd scenario, which is the correct behavior, see https://flutter.googlesource.com/recipes/+refs

Do we know if the pubsub messages are being retried? I'd expect this to resolve after a few retries as the data is propagated through GitHub and GoB's systems.

The last part about silently failing is due to the AppEngine request timeout being reached (60 seconds). We should lower the retry counts to ensure we explicitly timeout the code.

**Comment by drewroengoogle** [comment]
> It does run into a 3rd scenario, which is the correct behavior, see https://flutter.googlesource.com/recipes/+refs

I am mainly confused because I would expect to find cases of [a "Created flutter/recipes branch" log](https://github.com/flutter/cocoon/blob/4ffd03df44741d73877a0848935eea0d6cbfc1e9/app_dart/lib/src/request_handlers/github/branch_subscription.dart#L50), but I don't see any at all.

> Do we know if the pubsub messages are being retried? I'd expect this to resolve after a few retries as the data is propagated through GitHub and GoB's systems.

The call to get the commits is retried 3 times, but the Github client is not recreated for each retry. Do you think it would be worth changing it so we try to create the Github client?

> The last part about silently failing is due to the AppEngine request timeout being reached (60 seconds). We should lower the retry counts to ensure we explicitly timeout the code.

I queried recent calls to `webhook-branch-subscriptions` for any requests that reached 60 seconds, and while there are some, it is a small percentage of them, but there are also more cases of requests taking a few seconds where the branch starts to create and then no more logs happen until we get [a "Failed to process" log](https://github.com/flutter/cocoon/blob/07613fcf1b34d7200c62b92746b6c84c4ba35d1e/app_dart/lib/src/request_handling/subscription_handler.dart#L142). Here's the query I used to find some instances of this (and to ensure I'm not looking at it incorrectly):
```
protoPayload.resource = /api/github/webhook-branch-subscription
protoPayload.latency < 5s
"Creating branch"
```

**Comment by keyonghan** [comment]
I am wondering if we need to add a branch check here: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/github/branch_subscription.dart#L46

I expect most API calls and errors come from `master` branch`.

**Comment by drewroengoogle** [comment]
> I am wondering if we need to add a branch check here: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/github/branch_subscription.dart#L46
> 
> I expect most API calls and errors come from `master` branch`.

To be sure I understand, we could reject calls coming from `master` because creating a recipe branch does not apply? If this is correct, I can open a PR for this

**Comment by keyonghan** [comment]
That's correct. The purpose of this API is for release branches.

**Comment by ricardoamador** [comment]
@drewroengoogle Did you end up making a pr for this? I was reviewing and this error has not shown for the last 7 days.

**Comment by drewroengoogle** [comment]
> @drewroengoogle Did you end up making a pr for this? I was reviewing and this error has not shown for the last 7 days.

I talked with Keyong and after looking a bit more, there are no calls coming from `master` because create events are never going to be on the main/master branch, so instead Keyong cleared out the queue.

**Comment by ricardoamador** [comment]
Okay closing for now. If it happens again we can address it then.

**Comment by ricardoamador** [comment]
Thanks for adding this @keyonghan
