### ISSUE TITLE
How to build application under windows mode with some codes depend on dart:html library?

### ISSUE THREAD

**Issue by monkingame** [flutter/flutter#123188]
## Steps to Reproduce

I wrote a appliction to download file in web mode, but the app also run in windows mode.
When debug in windows mode, flutter got build errors and prevent debuging.
I want to exclude web codes when run in Windows mode(e.g. by kIsWeb),and include web codes when Web mode.
Such as :
if(kIsWeb){
  import 'dart:html';
  // run html codes
}else{
  // other codes
}

Under Web mode,the app runs correctly.
But under Windows mode,the app runs with build errors:

**Expected results:** 
The HtmlDownload class debug&run in both Web and Windows mode, seperate by kIsWeb or else methods.

**Actual results:** 

lib/html_download.dart(14,51): error G8A3C39EF: 'AnchorElement' isn't a type. [C:\test\test_html\build\windows\flutter\flutter_assemble.vcxproj]
html_download.dart:1
lib/html_download.dart(13,9): error G4127D1E8: The getter 'Url' isn't defined for the class 'HtmlDownload'. [C:\test\test_html\build\windows\flutter\flutter_assemble.vcxproj]

<details>
<summary>Code sample</summary>

here codes:
main.dart
`
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'html_download.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
      home: Scaffold(
          body: ElevatedButton(
              onPressed: () {
                if (kIsWeb) HtmlDownload(msg: 'test string down file').down();
              },
              child: const Text('test html'))));
}
`

html_download.dart
`
import 'dart:html';
import 'package:flutter/foundation.dart';

class HtmlDownload {
  final String msg;

  HtmlDownload({required this.msg});

  void down() {
    if (!kIsWeb) return;

    final url =
        Url.createObjectUrlFromBlob(Blob([Uint8List.fromList(msg.codeUnits)]));
    final anchor = document.createElement('a') as AnchorElement
      ..href = url
      ..style.display = 'none'
      ..download = 'test.txt';
    document.body?.children.add(anchor);
    anchor.click();
    document.body?.children.remove(anchor);
    Url.revokeObjectUrl(url);
  }
}

`
</details>

<details>
  <summary>Logs</summary>

```
[  +11 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] executing: [C:\tools\flutter/] git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[  +71 ms] Exit code 0 from: git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] 3.7.7
[  +12 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
[  +51 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +45 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +3 ms] Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[  +56 ms] executing: C:\Users\sun\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +49 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Multiple devices found:
[  +35 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.2788]
[        ] Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.65
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.44
[        ] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+10624 ms] q
[   +8 ms] "flutter run" took 10,957ms.
[  +18 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      FlutterCommand._chooseOneOfAvailableDevices (package:flutter_tools/src/runner/flutter_command.dart:1542:7)       
           <asynchronous suspension>
           #2      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1498:39)
           <asynchronous suspension>
           #3      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:497:15)
           <asynchronous suspension>
           #4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1381:5)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +256 ms] ensureAnalyticsSent: 250ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
PS C:\test\test_html> flutter run --verbose
[  +11 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] executing: [C:\tools\flutter/] git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[  +71 ms] Exit code 0 from: git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] 3.7.7
[  +12 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
[  +51 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +45 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +3 ms] Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[  +56 ms] executing: C:\Users\sun\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +49 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Multiple devices found:
[  +35 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.2788]
[        ] Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.65
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.44
[        ] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+10624 ms] q
[   +8 ms] "flutter run" took 10,957ms.
[  +18 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      FlutterCommand._chooseOneOfAvailableDevices (package:flutter_tools/src/runner/flutter_command.dart:1542:7)       
           <asynchronous suspension>
           #2      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1498:39)
           <asynchronous suspension>
           #3      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:497:15)
           <asynchronous suspension>
           #4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1381:5)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +256 ms] ensureAnalyticsSent: 250ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
PS C:\test\test_html> flutter analyze
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Analyzing test_html...                                                  

   info - Don't use web-only libraries outside Flutter web plugin packages - lib\html_download.dart:1:1 -
          avoid_web_libraries_in_flutter

1 issue found. (ran in 16.9s)
```

```
PS C:\test\test_html> flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 3.7.7, on Microsoft Windows [版本 10.0.19045.2788], locale zh-CN)
    • Flutter version 3.7.7 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (13 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\sun\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.76.2)
    • VS Code at C:\Users\sun\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.2788]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.65
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.44

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

![image](https://user-images.githubusercontent.com/4568610/226803018-758a241a-bc2e-46ee-85c8-0475e2597a7d.png)

**Comment by huycozy** [comment]
Hi @monkingame 
This reminds me of [`conditional imports`](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files). Please see [this](https://github.com/dart-lang/sdk/issues/34262#issuecomment-416129832) and related SO threads:

- https://stackoverflow.com/questions/67937479/how-to-add-conditional-imports-across-flutter-mobile-web-and-window
- https://stackoverflow.com/questions/62724798/conditional-package-import-for-desktop-in-flutter/67948233#67948233

Closing this issue as it's not Flutter issue itself. If you disagree, please write in the comments and I will reopen it. Thanks!
