### ISSUE TITLE
Fatal signal 11, when using TextOverflow.ellipsis with RichText on Android

### ISSUE THREAD

**Issue by LokieVikky** [flutter/flutter#123155]
## Steps to Reproduce

I'm trying to use TextOverflow.ellipsis inside RichText

<details>
<summary>Code sample</summary>

[](https://dartpad.dev/?id=faebcb48bcc2fff1084c429fe0f98e7e)

```dart
```

</details>

<details>
  <summary>Logs</summary>

```

[+2168 ms] E/SurfaceSyncer(23791): Failed to find sync for id=0
[   +8 ms] W/Parcel  (23791): Expecting binder but got null!
[+1033 ms] I/flutter (23791): saving File: '/data/user/0/com.acldigital.carecircle/files/Roboto_300_bbec9513a9c2e908ad0daf806d486b5d81670e0cb6e048d90c526c39c7226986.ttf'
[  +42 ms] I/flutter (23791): saving File: '/data/user/0/com.acldigital.carecircle/files/Roboto_500_ec3a64e46e2ee5f546845582e1d5409107780cef55bc43b052ee962f9807aee6.ttf'
[  +23 ms] I/flutter (23791): saving File: '/data/user/0/com.acldigital.carecircle/files/Roboto_regular_d1d7c5f4500eeb1a09e051781906c3642015a3f6c9b69046b905c8bf34c6ad60.ttf'
[+6254 ms] I/flutter (23791): Testing Event from ios
[  +76 ms] I/flutter (23791): Testing Event from ios
[ +714 ms] I/flutter (23791): Testing Event from ios
[ +470 ms] I/flutter (23791): saving File: '/data/user/0/com.acldigital.carecircle/files/OpenSans_700_c1a4ac0f9d9edcb71f32d358500c1a17ce863b86ca4cafbc55c9e493a609a7ba.ttf'
[+6395 ms] F/libc    (23791): Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x79ed092b3e in tid 23880 (1.ui), pid 23791 (ital.carecircle)
[ +450 ms] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[        ] Build fingerprint: 'google/sunfish/sunfish:13/TQ1A.230205.002/9471150:user/release-keys'
[        ] Revision: 'MP1.0'
[        ] ABI: 'arm64'
[        ] Timestamp: 2023-03-22 01:35:36.673541560+0530
[        ] Process uptime: 21s
[        ] Cmdline: com.acldigital.carecircle
[        ] pid: 23791, tid: 23880, name: 1.ui  >>> com.acldigital.carecircle <<<
[        ] uid: 10329
[        ] signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x00000079ed092b3e
[        ]     x0  b4000079ed092af0  x1  715f000000040104  x2  ffffffffffffffff  x3  b400007aabf52d38
[        ]     x4  0000000000000001  x5  0000000000000000  x6  0000007708c6eb10  x7  0000000000000749
[        ]     x8  b4000079ebc8d9b0  x9  0000000000000050  x10 0000000000000001  x11 b400007a5bd1fd18
[        ]     x12 000000000000a8c5  x13 0000000000000016  x14 0000000000000000  x15 00000078b6d01b00
[        ]     x16 0000000000000000  x17 b400007a8bca4b68  x18 00000078b6650000  x19 00000078b6d01890
[        ]     x20 b400007aabf52d38  x21 b400007a5bd1fce0  x22 00000078b6d01878  x23 ffffffffffffffff
[        ]     x24 ffffffffffffffff  x25 ffffffffffffffff  x26 0000000000000000  x27 ffffffffffffffff
[        ]     x28 b4000079ed092af0  x29 b4000079ed092af0
[        ]     lr  00000078b97ef5e4  sp  00000078b6d01790  pc  00000078b97ef63c  pst 00000000a0000000
[        ] backtrace:
[        ]       #00 pc 00000000019dc63c  /data/app/~~fzrfg0qM4Rpi59xMpifuig==/com.acldigital.carecircle-iHbQaIzOmUCmEAovWpXjVQ==/lib/arm64/libflutter.so (BuildId:
8e449d2cb830f440b6d00cf6d20116687477e615)
[        ]       #01 pc 00000000019df190  /data/app/~~fzrfg0qM4Rpi59xMpifuig==/com.acldigital.carecircle-iHbQaIzOmUCmEAovWpXjVQ==/lib/arm64/libflutter.so (BuildId:
8e449d2cb830f440b6d00cf6d20116687477e615)
[        ]       #02 pc 00000000019dcca0  /data/app/~~fzrfg0qM4Rpi59xMpifuig==/com.acldigital.carecircle-iHbQaIzOmUCmEAovWpXjVQ==/lib/arm64/libflutter.so (BuildId:
8e449d2cb830f440b6d00cf6d20116687477e615)
[        ]       #03 pc 00000000019db2a4  /data/app/~~fzrfg0qM4Rpi59xMpifuig==/com.acldigital.carecircle-iHbQaIzOmUCmEAovWpXjVQ==/lib/arm64/libflutter.so (BuildId:
8e449d2cb830f440b6d00cf6d20116687477e615)
[        ]       #04 pc 00000000019dd034  /data/app/~~fzrfg0qM4Rpi59xMpifuig==/com.acldigital.carecircle-iHbQaIzOmUCmEAovWpXjVQ==/lib/arm64/libflutter.so (BuildId:
8e449d2cb830f440b6d00cf6d20116687477e615)
[        ]       #05 pc 00000000019d8c98  /data/app/~~fzrfg0qM4Rpi59xMpifuig==/com.acldigital.carecircle-iHbQaIzOmUCmEAovWpXjVQ==/lib/arm64/libflutter.so (BuildId:
8e449d2cb830f440b6d00cf6d20116687477e615)
[        ]       #06 pc 0000000001989100  /data/app/~~fzrfg0qM4Rpi59xMpifuig==/com.acldigital.carecircle-iHbQaIzOmUCmEAovWpXjVQ==/lib/arm64/libflutter.so (BuildId:
8e449d2cb830f440b6d00cf6d20116687477e615)
[        ]       #07 pc 00000000019fee40  /data/app/~~fzrfg0qM4Rpi59xMpifuig==/com.acldigital.carecircle-iHbQaIzOmUCmEAovWpXjVQ==/lib/arm64/libflutter.so (BuildId:
8e449d2cb830f440b6d00cf6d20116687477e615)
[        ]       #08 pc 00000000019ead60  /data/app/~~fzrfg0qM4Rpi59xMpifuig==/com.acldigital.carecircle-iHbQaIzOmUCmEAovWpXjVQ==/lib/arm64/libflutter.so (BuildId:
8e449d2cb830f440b6d00cf6d20116687477e615)
[        ]       #09 pc 0000000000006f64  [anon:dart-code]
[ +121 ms] Service protocol connection closed.
[        ] Lost connection to device.
[        ] DevFS: Deleting filesystem on the device (file:///data/user/0/com.acldigital.carecircle/code_cache/connect_meBHQGQJ/connect_me/)
[ +252 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +1 ms] "flutter run" took 85,251ms.
[ +100 ms] ensureAnalyticsSent: 99ms
[        ] Running 1 shutdown hook
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 0

```

```

   info • Unused import: 'package:connect_me/shared/tool_tip.dart' • lib/features/authentication/presentation/sign_in_page.dart:6:8 • unused_import
   info • The declaration '_buildConnectMeLogo' isn't referenced • lib/features/authentication/presentation/sign_in_page.dart:126:10 • unused_element
   info • The value of the local variable 'response' isn't used • lib/features/stream/data/stream_repository.dart:299:21 • unused_local_variable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Group._id, Group._parent,
          Group._groupTitle • lib/features/stream/domain/group.dart:7:7 • must_be_immutable
   info • The declaration '_buildSearchIcon' isn't referenced • lib/features/stream/presentation/home_page.dart:142:10 • unused_element
   info • Unused import: 'package:connect_me/other_pages/root_page.dart' • lib/features/stream/presentation/post/photo_post/create_photo_post_page.dart:11:8 • unused_import
   info • The declaration '_parseHtmlString' isn't referenced • lib/features/stream/presentation/post/topic_post/topic_post_page.dart:110:11 • unused_element
   info • Unused import: 'package:connect_me/shared/interactive_viewer_overlay.dart' • lib/features/stream/presentation/stream/media_preview.dart:7:8 • unused_import
   info • Unused import: 'package:connect_me/libraries/assets.dart' • lib/features/stream/presentation/stream/stream_post.dart:17:8 • unused_import
   info • The declaration '_buildVideoPlayer' isn't referenced • lib/features/stream/presentation/stream/stream_post.dart:800:10 • unused_element
   info • The declaration '_buildPostMedia' isn't referenced • lib/features/stream/presentation/stream/stream_post.dart:818:10 • unused_element
   info • Unused import: 'dart:convert' • lib/other_pages/actions_page.dart:1:8 • unused_import
   info • Unused import: 'package:agora_rtc_engine/agora_rtc_engine.dart' • lib/other_pages/actions_page.dart:3:8 • unused_import
   info • Unused import: 'package:connect_me/libraries/svg_icons.dart' • lib/shared/custom_avatar.dart:6:8 • unused_import
   info • Unused import: 'package:connect_me/shared/svg_icon.dart' • lib/shared/custom_avatar.dart:7:8 • unused_import
   info • Don't invoke 'print' in production code • lib/shared/custom_avatar.dart:33:7 • avoid_print
   info • The declaration '_postError' isn't referenced • lib/shared/custom_avatar.dart:82:10 • unused_element
   info • Constructors for public widgets should have a named 'key' parameter • lib/shared/image_manipulation/custom_dismissible.dart:7:9 • use_key_in_widget_constructors
   info • Invalid use of a private type in a public API • lib/shared/image_manipulation/custom_dismissible.dart:20:3 • library_private_types_in_public_api
   info • Use 'const' with the constructor to improve performance • lib/shared/image_manipulation/custom_dismissible.dart:39:17 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/shared/image_manipulation/custom_dismissible.dart:70:14 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/shared/image_manipulation/custom_dismissible.dart:73:12 • prefer_const_constructors
   info • The import of 'dart:ui' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' •
          lib/shared/image_manipulation/hero_dialog_route.dart:1:8 • unnecessary_import
   info • Constructors for public widgets should have a named 'key' parameter • lib/shared/image_manipulation/interactive_viewer_boundary.dart:13:9 • use_key_in_widget_constructors
   info • Constructors for public widgets should have a named 'key' parameter • lib/shared/image_manipulation/interactiveviewer_gallery.dart:21:9 • use_key_in_widget_constructors
   info • Invalid use of a private type in a public API • lib/shared/image_manipulation/interactiveviewer_gallery.dart:47:3 • library_private_types_in_public_api
   info • Use 'const' with the constructor to improve performance • lib/shared/image_manipulation/interactiveviewer_gallery.dart:80:17 • prefer_const_constructors
   info • Unused import: 'package:connect_me/features/stream/presentation/stream/media_preview.dart' • lib/shared/post_detail_page.dart:3:8 • unused_import
   info • Unused import: 'package:dismissible_page/dismissible_page.dart' • lib/shared/post_detail_page.dart:11:8 • unused_import
   info • Constructors in '@immutable' classes should be declared as 'const' • lib/shared/tool_tip.dart:6:3 • prefer_const_constructors_in_immutables

```

lokeshn@Lokeshs-MacBook-Pro connect_me % flutter doctor -v

```

[✓] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.7 on channel stable at /Users/lokeshn/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (13 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lokeshn/SDK/android
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Pixel 4a (mobile)           • 09291JEC212245 • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554  • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos          • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)                • chrome         • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```
</details>

**Comment by iBelow** [comment]
same problem. first the emulator slows down, then crashes. and there is no text overflow anywhere
```
signal 11 (SIGSEGV), code -6 (SI_TKILL), fault addr --------
    rax 0000000000000000  rbx 0000725d98536fe8  rcx 0000000000000000  rdx 0000000000000002
    r8  0000000000000020  r9  0000000000000000  r10 0000725d93306390  r11 0000000000000000
    r12 0000725d98536f10  r13 0000725c0614cd71  r14 0000725d98536ff0  r15 0000725e4d5c64f0
    rdi 0000725e3d60f900  rsi 0000725d98536c50
    rbp 0000725d98536f50  rsp 0000725d98536f08  rip 0000725d9675dc1e
backtrace:
      #00 pc 0000000001aaec1e  /data/app/~~S3r51zHpDrjGeBPXSUShag==/APP-3I0krxj36fyECZazgdoCfw==/lib/x86_64/libflutter.so (BuildId: de2e2d744d896fd88f5ba6a3e517ebbe21ce0e9f)
      #01 pc 0000000001ab4913  /data/app/~~S3r51zHpDrjGeBPXSUShag==/APP-3I0krxj36fyECZazgdoCfw==/lib/x86_64/libflutter.so (BuildId: de2e2d744d896fd88f5ba6a3e517ebbe21ce0e9f)
      #02 pc 00000000000063ea  [anon:dart-code]
Lost connection to device.
Exited (sigterm)
```

**Comment by darshankawar** [comment]
@LokieVikky 
I ran the code sample provided using latest stable and master version on Pixel XL api 30 emulator but it didn't crash upon compiling the app and see a blank app:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:55776/Gq9LZLwhGYc=/ws
Syncing files to device Android SDK built for x86...
```

<img width="425" alt="Screenshot 2023-03-22 at 11 49 57 AM" src="https://user-images.githubusercontent.com/67046386/226818653-ace82855-1cf3-46b3-8d7b-05e951885824.png">


Does it crash consistently everytime you run the code and happens on other devices as well ?

**Comment by iBelow** [comment]
@darshankawar 
wait 5-7 minutes, then app will crash
> D/sentry-native( 9064): sending envelope
> D/sentry-native( 9064): serializing envelope into buffer
> I/sentry-native( 9064): crash has been captured
> F/libc    ( 9064): Fatal signal 11 (SIGSEGV), code -6 (SI_TKILL) in tid 9115 (1.ui), pid 9064 (.ntzx.bzone_btc)
> *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> Build fingerprint: 'google/sdk_gphone64_x86_64/emulator64_x86_64_arm64:12/SE1A.220826.005/9309864:userdebug/dev-keys'
> Revision: '0'
> ABI: 'x86_64'
> Timestamp: 2023-03-22 07:48:24.534013300+0000
> Process uptime: 0s
> Cmdline: com.ntzx.bzone_btc
> pid: 9064, tid: 9115, name: 1.ui  >>> com.ntzx.bzone_btc <<<
> uid: 10149
> signal 11 (SIGSEGV), code -6 (SI_TKILL), fault addr --------
>     rax 0000000000000000  rbx 00007bc57fed0718  rcx 00007bc30e4cdd49  rdx 00007bc57fed0710
>     r8  0000000000047208  r9  0000000000000047  r10 00007bc4d2b06390  r11 0000000000000000
>     r12 00007bc4c1c523aa  r13 00007bc30e4cdd28  r14 00007bc4dc60efa8  r15 00007bc30712b551
>     rdi 0000000000000000  rsi 00007bc57fed0718
>     rbp 00007bc4dc60f000  rsp 00007bc4dc60efa0  rip 00007bc4d646cd41
> backtrace:
>       #00 pc 0000000001a3ad41  /data/app/~~LsLgKdiPQ6ZYxuu-iqxW8Q==/com.ntzx.bzone_btc-js0dnRwCEQEd6HP69_qRKQ==/lib/x86_64/libflutter.so (BuildId: 02da83f7838015562f8e982f4e1381e8aa6dd508)
>       #01 pc 0000000001a3aefc  /data/app/~~LsLgKdiPQ6ZYxuu-iqxW8Q==/com.ntzx.bzone_btc-js0dnRwCEQEd6HP69_qRKQ==/lib/x86_64/libflutter.so (BuildId: 02da83f7838015562f8e982f4e1381e8aa6dd508)
>       #02 pc 00000000000063ea  [anon:dart-code]
> [sentry] [debug] Capture from onError 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5333 pos 16: 'child is! Parent
> framework.dart:5333
> [sentry.flutterError] [error] Exception caught by widgets library
> [sentry.flutterError] _AssertionError
> [sentry.flutterError] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
> #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
> #2      ParentDataElement._applyParentData.applyParentDataToChild
> framework.dart:5333
> #3      ComponentElement.visitChildren
> framework.dart:5020
> #4      ParentDataElement._applyParentData.applyParentDataToChild
> framework.dart:5334
> #5      ComponentElement.visitChildren
> framework.dart:5020
> #6      ParentDataElement._applyParentData
> framework.dart:5337
> #7      ParentDataElement.notifyClients
> framework.dart:5381
> #8      ProxyElement.updated
> framework.dart:5311
> #9      ProxyElement.update
> framework.dart:5300
> #10     Element.updateChild
> framework.dart:3660
> #11     RenderObjectElement.updateChildren
> framework.dart:5981
> #12     MultiChildRenderObjectElement.update
> framework.dart:6537
> #13     Element.updateChild
> framework.dart:3660
> #14     ComponentElement.performRebuild
> ...

**Comment by SelaseKay** [comment]
@darshankawar 
I think you're seeing a blank screen because there's no color attached to the TextStyle. Trying adding a color and you should see something.
