### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: 另一个程序正在使用此文件，进程无法访问。, errno = 32

### ISSUE THREAD

**Issue by Li-00** [flutter/flutter#123185]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
on android studio

1. flutter clean
2.flutter run

## Logs
FileSystemException: Deletion failed, OS Error: 另一个程序正在使用此文件，进程无法访问。
, errno = 32
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:420:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:486:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:485:12)
#6      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1015:22)
#7      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:964:5)
#8      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1055:5)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:316:5)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:177:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
```
```
[✓] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19044.2728], locale zh-CN)
    • Flutter version 2.10.0 at D:\environment\flutter_stable\flutter_windows_2.10.0-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (1 year, 2 months ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\environment\AndroidSDK\Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: E:\software\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Google\Chrome\Application\Chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.5.2)
    • Visual Studio at E:\software\vs
    • Visual Studio Professional 2022 version 17.5.33502.453
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2021.2)
    • Android Studio at E:\software\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.66
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.44

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.1.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
audioplayers-1.1.1
audioplayers_android-1.1.3
audioplayers_darwin-1.0.4
audioplayers_linux-1.0.2
audioplayers_web-2.0.1
audioplayers_windows-1.1.1
device_info-0.4.2+6
fast_rsa-3.4.7
file_picker-4.6.1
flutter_plugin_android_lifecycle-2.0.7
local_authentication
package_info-0.4.3+4
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.7
path_provider_windows-2.0.7
permission_handler-3.3.0
screen_retriever-0.1.6
shared_preferences-2.0.17
shared_preferences_android-2.0.15
shared_preferences_foundation-2.1.2
shared_preferences_linux-2.1.3
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.3
sqflite-2.0.2+1
url_launcher-6.1.8
url_launcher_android-6.0.23
url_launcher_ios-6.0.18
url_launcher_linux-3.0.2
url_launcher_macos-3.0.2
url_launcher_web-2.0.14
url_launcher_windows-3.0.2
webview_windows-0.2.1
window_manager-0.2.7

**Comment by darshankawar** [comment]
> Channel stable, 2.10.0

@Li-00 You are on very old version of the framework. Please upgrade to latest stable or master which has likely fixed the issue already.
Closing for now.
