### ISSUE TITLE
'backgroundColor != null

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#12321]
```
I/flutter ( 7232): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7232): The following assertion was thrown building Material(type: button, elevation: 0.0, dirty, state:
I/flutter ( 7232): _MaterialState#4eee6):
I/flutter ( 7232): 'package:flutter/src/material/material.dart': Failed assertion: line 210: 'backgroundColor != null
I/flutter ( 7232): || widget.type == MaterialType.transparency': is not true.
I/flutter ( 7232): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7232): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7232): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7232):   https://github.com/flutter/flutter/issues/new
I/flutter ( 7232): When the exception was thrown, this was the stack:
I/flutter ( 7232): #2      _MaterialState.build (package:flutter/src/material/material.dart:210)
I/flutter ( 7232): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7232): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3546)
I/flutter ( 7232): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3664)
I/flutter ( 7232): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4529)
I/flutter ( 7232): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4529)
I/flutter ( 7232): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4634)
I/flutter ( 7232): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4634)
I/flutter ( 7232): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3664)
I/flutter ( 7232): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4529)
I/flutter ( 7232): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4529)
I/flutter ( 7232): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3664)
I/flutter ( 7232): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3664)
I/flutter ( 7232): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4529)
I/flutter ( 7232): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #98     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4634)
I/flutter ( 7232): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4529)
I/flutter ( 7232): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4529)
I/flutter ( 7232): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #121    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #123    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3839)
I/flutter ( 7232): #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3558)
I/flutter ( 7232): #127    Element.rebuild (package:flutter/src/widgets/framework.dart:3447)
I/flutter ( 7232): #128    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3526)
I/flutter ( 7232): #129    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3664)
I/flutter ( 7232): #130    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3521)
I/flutter ( 7232): #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 7232): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 7232): #133    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:723)
I/flutter ( 7232): #134    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2226)
I/flutter ( 7232): #135    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:716)
I/flutter ( 7232): #136    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:239)
I/flutter ( 7232): #137    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2019)
I/flutter ( 7232): #138    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1109)
I/flutter ( 7232): #139    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2019)
I/flutter ( 7232): #140    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:228)
I/flutter ( 7232): #141    RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:398)
I/flutter ( 7232): #142    RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190)
I/flutter ( 7232): #143    RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233)
I/flutter ( 7232): #144    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #145    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:286)
I/flutter ( 7232): #146    RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1306)
I/flutter ( 7232): #147    RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1269)
I/flutter ( 7232): #148    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #149    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #150    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #151    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #152    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #153    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #154    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #155    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #156    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #157    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #158    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #159    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #160    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #161    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124)
I/flutter ( 7232): #162    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:91)
I/flutter ( 7232): #163    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194)
I/flutter ( 7232): #164    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338)
I/flutter ( 7232): #165    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #166    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #167    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #168    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #169    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1005)
I/flutter ( 7232): #170    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #171    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #172    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #173    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #174    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #175    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #176    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #177    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2731)
I/flutter ( 7232): #178    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #179    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 7232): #180    RenderObject.layout (package:flutter/src/rendering/object.dart:1923)
I/flutter ( 7232): #181    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:466)
I/flutter ( 7232): #182    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1798)
I/flutter ( 7232): #183    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1087)
I/flutter ( 7232): #184    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:256)
I/flutter ( 7232): #185    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:531)
I/flutter ( 7232): #186    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:194)
I/flutter ( 7232): #187    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713)
I/flutter ( 7232): #188    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649)
I/flutter ( 7232): #189    _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:86)
I/flutter ( 7232): #190    _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:75)
```

**Comment by eseidelGoogle** [comment]
I ran into this just now too, when creating a `new Material` which had an elevation but not a color set.

**Comment by Hixie** [comment]
Yup, if you want the Material to be transparent you have to say that by picking the transparency kind (which is unusual). Material is normally opaque. We should make the message clearer though.

**Comment by JFixby** [comment]
I have my own framework, similar to Flutter. In the framework each element has optional debug name. So when it is crashing, exception contains a path to the broken element in the widgets tree. Looks something like: `[root]/widget-foo/widget-bar/buggy-widget`. This way I can know what is breaking. I may suggest you to add similar function.

**Comment by Hixie** [comment]
We have that actually, each Element has a debugGetCreatorChain method that gives you the chain. The problem is that at the point where we catch the exception above we don't know which Element was responsible for it because the StackTrace isn't introspectable.
