### ISSUE TITLE
`Isolate.run` doesn't work with plugin for native image compression library

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#123247]
When trying to run the provided code sample, I'm getting an error about which I couldn't find any meaningful fix on the internet.
The issue happens when trying to compress a list of `XFile`s (before they're uploaded), but the `compressJpg` method is not working inside a `Isolate.run` call. I'm not sure yet if this is a Flutter issue, Dart issue, plugin issue or a wrong implementation of the code.
Tried different code implementations, but all of them led to the same issue. The plugin used is `image_compression_flutter`:
```yaml
image_compression_flutter:
    git:
      url: https://github.com/dmhernandez-su/image_compression_flutter.git
```

<details>
<summary>Code sample</summary>

```dart
class Api {
  static Future<void> uploadImages(List<String> files) async {
    ...
    final compressedFiles = await Isolate.run<Map<String, Uint8List>>(() async {
      final compressedFilesIsolate = <String, Uint8List>{};
      for (final file in files) {
        const config = Configuration(
          outputType: ImageOutputType.jpg,
          quality: 100,
          useJpgPngNativeCompressor: true,
        );
        final input = ImageFile(
          filePath: file,
          rawBytes: await XFile(file).readAsBytes(),
        );
        final compressed = await compressor.compressJpg(
          ImageFileConfiguration(input: input, config: config),
        );
        compressedFilesIsolate[file.split('/').last] = compressed.rawBytes;
      }
      return compressedFilesIsolate;
    });
    ...
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
I/flutter (28762): Bad state: The BackgroundIsolateBinaryMessenger.instance value is invalid until BackgroundIsolateBinaryMessenger.ensureInitialized is executed.
I/flutter (28762): #0      BackgroundIsolateBinaryMessenger.instance (package:flutter/src/services/_background_isolate_binary_messenger_io.dart:27:7)
I/flutter (28762): #1      _findBinaryMessenger (package:flutter/src/services/platform_channel.dart:135:42)
I/flutter (28762): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:273:56)
I/flutter (28762): #3      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:15)
I/flutter (28762): #4      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:491:12)
I/flutter (28762): #5      ImageCompressionFlutter.dummyCallNativeCode (package:image_compression_flutter/src/interface.dart:21:37)
I/flutter (28762): #6      ImageCompressionFlutterIO.compressJpg (package:image_compression_flutter/src/compressor_io.dart:54:18)
I/flutter (28762): #7      Api.uploadImages.<anonymous closure> (package:<elided>)
I/flutter (28762): <asynchronous suspension>
I/flutter (28762): #8      _RemoteRunner._run (dart:isolate:956:18)
I/flutter (28762): <asynchronous suspension>
```

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale
    en-DE)
    • Flutter version 3.7.7 on channel stable at
      /Users/cristianzazomillan/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (2 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/cristianzazomillan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • SM A217F (mobile) • RF8R30GZ8DJ • android-arm64  • Android 12 (API 31)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by jayjah** [comment]
@Zazo032 I think you should have a look at the following API: [api.flutter.dev - BackgroundIsolateBinaryMessenger](https://api.flutter.dev/flutter/services/BackgroundIsolateBinaryMessenger/ensureInitialized.html)

**Comment by huycozy** [comment]
@Zazo032 Please try @jayjah's suggestion above to see if it works for your case. 

If the issue still persists, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

**Comment by Zazo032** [comment]
Just tried a few different approaches (the documentation is not very clear on how `BackgroundIsolateBinaryMessenger.ensureInitialized` should be called), but none of them worked:

```dart
static Future<void> uploadImages(List<String> files) async {
  final isolateToken = ServicesBinding.rootIsolateToken!;
  final compressed = await Isolate.run<ImageFile>(() {
    BackgroundIsolateBinaryMessenger.ensureInitialized(isolateToken);
    ...
  });
}
```
This implementation results in the following error:
```
I/flutter ( 3282): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter ( 3282): The following _CastError was thrown during a platform message response callback:
I/flutter ( 3282): type 'Null' is not a subtype of type 'List<dynamic>' in type cast
I/flutter ( 3282): 
I/flutter ( 3282): When the exception was thrown, this was the stack:
I/flutter ( 3282): #0      BackgroundIsolateBinaryMessenger.ensureInitialized.<anonymous closure> (package:flutter/src/services/_background_isolate_binary_messenger_io.dart:51:46)
I/flutter ( 3282): #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
I/flutter ( 3282): (elided 6 frames from dart:async)
I/flutter ( 3282): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

And implementing it like this:
```dart
static Future<void> uploadImages(List<String> files) async {
  final isolateToken = ServicesBinding.rootIsolateToken!;
  BackgroundIsolateBinaryMessenger.ensureInitialized(isolateToken);
  final compressed = await Isolate.run<ImageFile>(() {
    ...
  });
}
```
Results in the original error:
```
I/flutter ( 3282): Bad state: The BackgroundIsolateBinaryMessenger.instance value is invalid until BackgroundIsolateBinaryMessenger.ensureInitialized is executed.
I/flutter ( 3282): #0      BackgroundIsolateBinaryMessenger.instance (package:flutter/src/services/_background_isolate_binary_messenger_io.dart:27:7)
I/flutter ( 3282): #1      _findBinaryMessenger (package:flutter/src/services/platform_channel.dart:135:42)
I/flutter ( 3282): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:273:56)
I/flutter ( 3282): #3      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:15)
I/flutter ( 3282): #4      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:491:12)
I/flutter ( 3282): #5      ImageCompressionFlutter.dummyCallNativeCode (package:image_compression_flutter/src/interface.dart:21:37)
I/flutter ( 3282): #6      ImageCompressionFlutterIO.compressJpg (package:image_compression_flutter/src/compressor_io.dart:54:18)
I/flutter ( 3282): #7      Api.uploadImages.<anonymous closure> (<elided>)
I/flutter ( 3282): #8      _RemoteRunner._run (dart:isolate:954:47)
I/flutter ( 3282): #9      _RemoteRunner._remoteExecute (dart:isolate:948:12)
I/flutter ( 3282): #10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:
```

I will try to get a complete code sample to reproduce it.

**Comment by jayjah** [comment]
@Zazo032 After some digging into it unfortunately the real issue is somewhere in the package that you are using:
```
image_compression_flutter:
    git:
      url: https://github.com/dmhernandez-su/image_compression_flutter.git
``` 

If you comment out the following part:
```
final compressed = await compressor.compressJpg(
          ImageFileConfiguration(input: input, config: config),
        );
```

AND


replacing this line
```
compressedFilesIsolate[file.split('/').last] = compressed.rawBytes;
```
with the following line
```
compressedFilesIsolate[file.split('/').last] = await XFile(file).readAsBytes();
```
It will just work fine.

**Comment by Zazo032** [comment]
I see, could be that the plugin is using some code incompatible with isolates? In that case, the error message could be improved, since it's not very helpful

**Comment by Zazo032** [comment]
Could be related to https://github.com/fluttercandies/flutter_image_compress/issues/235

**Comment by huycozy** [comment]
As far as I can see, it seems the issue is caused by 3rd plugin's issue. But with regard to the error message, it should be improved. Would you mind providing a completed sample code so that we can reproduce this and investigate it later?
