### ISSUE TITLE
ubuntu arm64 , Failed to start Flutter renderer: No GL implementation is available

### ISSUE THREAD

**Issue by panzhoutao** [flutter/flutter#123202]
<details>
  <summary>Logs</summary>

```
[  +51 ms] Unable to locate an Android SDK.
[  +13 ms] executing: uname -m
[  +12 ms] Exit code 0 from: uname -m
[        ] aarch64
[   +2 ms] executing: [/home/firefly/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +22 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +3 ms] 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] executing: [/home/firefly/snap/flutter/common/flutter/] git tag
--points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[  +55 ms] Exit code 0 from: git tag --points-at
2ad6cd72c040113b47ee9055e722606a490ef0da
[   +1 ms] 3.7.7
[  +21 ms] executing: [/home/firefly/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref --symbolic @{upstream}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/home/firefly/snap/flutter/common/flutter/] git ls-remote
--get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +39 ms] executing: [/home/firefly/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +53 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[   +4 ms] Flutter assets will be downloaded from https://storage.flutter-io.cn. Make
sure you
           trust this source!
[  +89 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +140 ms] Skipping pub get: version match.
[ +335 ms] Generating
/home/firefly/CodeProjects/flutter_application_1/android/app/src/main/java/io/flutter
/plugins/GeneratedPluginRegistrant.java
[ +234 ms] Initializing file store
[  +15 ms] Skipping target: gen_localizations
[  +10 ms] gen_dart_plugin_registrant: Starting due to
{InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/firefly/CodeProjects/flutter_application_1/.dart_tool/package_config_subset}
[  +43 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[  +14 ms] Launching lib/main.dart on Linux in debug mode...
[   +6 ms] /home/firefly/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/firefly/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_s
erver.dart.snapshot --sdk-root
/home/firefly/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_p
atched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.YAKSDV/flutter_tool.KQDLUP/app.dill --packages
/home/firefly/CodeProjects/flutter_application_1/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --verbosity=error
--enable-experiment=alternative-invalidation-strategy
[  +41 ms] Building Linux application...
[  +41 ms] <- compile package:flutter_application_1/main.dart
[   +6 ms] executing: [build/linux/arm64/debug/] cmake -G Ninja
-DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-arm64
/home/firefly/CodeProjects/flutter_application_1/linux
[ +116 ms] -- Configuring done
[   +6 ms] -- Generating done
[        ] -- Build files have been written to:
/home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug
[  +51 ms] executing: ninja -C build/linux/arm64/debug install
[  +31 ms] ninja: Entering directory `build/linux/arm64/debug'
[+5569 ms] [1/5] Generating /home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +5 ms] [  +15 ms] Unable to locate an Android SDK.
[        ] [  +25 ms] executing: uname -m
[        ] [   +6 ms] Exit code 0 from: uname -m
[        ] [        ] aarch64
[        ] [   +1 ms] executing: [/home/firefly/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] [        ] executing: [/home/firefly/snap/flutter/common/flutter/] git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] [  +19 ms] Exit code 0 from: git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] [        ] 3.7.7
[        ] [  +27 ms] executing: [/home/firefly/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +20 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +3 ms] Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[        ] [ +218 ms] executing: [/home/firefly/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [   +2 ms] origin/stable
[        ] [        ] executing: [/home/firefly/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [        ] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +60 ms] Initializing file store
[        ] [  +16 ms] Done initializing file store
[        ] [  +75 ms] Skipping target: gen_localizations
[        ] [  +12 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +566 ms] unpack_linux: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/firefly/CodeProjects/flutter_application_1/linux/flutter/ephemeral/libflutter_linux_gtk.so}
[        ] [ +639 ms] Skipping target: kernel_snapshot
[        ] [   +4 ms] unpack_linux: Complete
[        ] [ +385 ms] debug_bundle_linux-arm64_assets: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were missing:
/home/firefly/CodeProjects/flutter_application_1/build/flutter_assets/kernel_blob.bin}
[   +1 ms] [ +208 ms] shaderc command: [/home/firefly/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-arm64/impellerc, --sksl, --iplr,
--sl=/home/firefly/CodeProjects/flutter_application_1/build/flutter_assets/shaders/ink_sparkle.frag,
--spirv=/home/firefly/CodeProjects/flutter_application_1/build/flutter_assets/shaders/ink_sparkle.frag.spirv,
--input=/home/firefly/snap/flutter/common/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag, --remap-samplers,
--include=/home/firefly/snap/flutter/common/flutter/packages/flutter/lib/src/material/shaders,
--include=/home/firefly/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-arm64/shader_lib]
[   +1 ms] [ +367 ms] debug_bundle_linux-arm64_assets: Complete
[        ] [ +351 ms] Persisting file store
[        ] [  +11 ms] Done persisting file store
[        ] [  +12 ms] build succeeded.
[        ] [  +10 ms] "flutter assemble" took 3,002ms.
[        ] [ +159 ms] ensureAnalyticsSent: 153ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +565 ms] [2/5] Building CXX object CMakeFiles/flutter_application_1.dir/flutter/generated_plugin_registrant.cc.o
[  +42 ms] [3/5] Building CXX object CMakeFiles/flutter_application_1.dir/my_application.cc.o
[ +190 ms] [4/5] Linking CXX executable intermediates_do_not_run/flutter_application_1
[        ] [4/5] Install the project...
[  +12 ms] -- Install configuration: "Debug"
[  +47 ms] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/flutter_application_1
[        ] -- Set runtime path of "/home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/flutter_application_1" to "$ORIGIN/lib"
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/icudtl.dat
[   +2 ms] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/lib/libflutter_linux_gtk.so
[  +71 ms] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +52 ms] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +2 ms] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/shaders
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/shaders/ink_sparkle.frag
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/firefly/CodeProjects/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[  +27 ms] Building Linux application... (completed in 6.8s)
[ +404 ms] ** (flutter_application_1:51119): WARNING **: 09:45:15.123: Failed to start Flutter renderer: No GL implementation is available
[+432373 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +5 ms] Error launching application on Linux.
[  +19 ms] "flutter run" took 440,647ms.
[  +19 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:722:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

```
[✓] Flutter (Channel stable, 3.7.7, on Ubuntu 20.04.5 LTS 5.10.110, locale en_US.UTF-8)
    • Flutter version 3.7.7 on channel stable at /home/firefly/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (2 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.76.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Ubuntu 20.04.5 LTS 5.10.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by huycozy** [comment]
Thanks for filing the issue. This looks similar to https://github.com/flutter/flutter/issues/106941 and https://github.com/flutter/flutter/issues/76178. It seems there is a workaround that you may want to try (see https://github.com/flutter/flutter/issues/106941#issue-1291132401):
```
export LIBGL_ALWAYS_SOFTWARE=1
```
Closing this issue in favor of these issues. Please follow up on them for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
