### ISSUE TITLE
[go_router]: Bad state: Future already completed on context.pop()

### ISSUE THREAD

**Issue by eli1stark** [flutter/flutter#123369]
It started to reproduce in the 6.5.0 version of go_router, 6.4.1 works as expected.

## Steps to Reproduce

1. Make sure that you have `flutter: 3.7.8` and that you added `go_router: 6.5.0` as a dependency.
2. Use the code sample provided below
3. Run the app
4. Press the "Open Settings" button
5. Press the "Show" button in the Settings screen, and a dialog will appear
6. Press the "Pop" button, and a dialog will close
7. Press the "Show" button on the Settings screen, and a dialog will appear again
8.  Press the "Pop" button, and an error will be thrown (Bad state: Future already completed)

**Expected results:** 

The dialog should be popped without error.

**Actual results:** 

The dialog popped with the error: **Bad state: Future already completed**.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

final _router = GoRouter(
  debugLogDiagnostics: true,
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const Home(),
    ),
    GoRoute(
      path: '/settings',
      builder: (context, state) => const Settings(),
    ),
  ],
);

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
      debugShowCheckedModeBanner: false,
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: TextButton(
              onPressed: () {
                context.push('/settings');
              },
              child: const Text('Open Settings'),
            ),
          ),
        ],
      ),
    );
  }
}

class Settings extends StatelessWidget {
  const Settings({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          TextButton(
            onPressed: () {
              context.pop();
            },
            child: const Text('Back'),
          )
        ],
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: TextButton(
              onPressed: () {
                showMyDialog(context);
              },
              child: const Text('Show'),
            ),
          ),
        ],
      ),
    );
  }
}

void showMyDialog(BuildContext context) {
  showDialog(
    context: context,
    builder: (context) {
      return Center(
        child: Container(
          width: 100,
          height: 200,
          color: Colors.red,
          child: Column(
            children: [
              TextButton(
                onPressed: () {
                  context.pop();
                },
                child: const Text('Pop'),
              ),
            ],
          ),
        ),
      );
    },
  );
}

```

</details>

<details>
  <summary>Logs</summary>

```
                    ══╡ EXCEPTION CAUGHT BY GESTURE
╞═══════════════════════════════════════════════════════════════════
                    The following StateError was thrown while handling a gesture:
                    Bad state: Future already completed
                    
                    When the exception was thrown, this was the stack:
                    #1      ImperativeRouteMatch.complete (package:go_router/src/delegate.dart:334:16)
                    #2      GoRouterDelegate.pop (package:go_router/src/delegate.dart:133:33)
                    #3      GoRouter.pop (package:go_router/src/router.dart:347:21)
                    #4      GoRouterHelper.pop (package:go_router/src/misc/extensions.dart:69:65)
                    #5      showMyDialog.<anonymous closure>.<anonymous closure>
(package:example/main.dart:113:27)
                    #6      _InkResponseState.handleTap
(package:flutter/src/material/ink_well.dart:1096:21)
                    #7      GestureRecognizer.invokeCallback
(package:flutter/src/gestures/recognizer.dart:253:24)
                    #8      TapGestureRecognizer.handleTapUp
(package:flutter/src/gestures/tap.dart:627:11)
                    #9      BaseTapGestureRecognizer._checkUp
(package:flutter/src/gestures/tap.dart:306:5)
                    #10     BaseTapGestureRecognizer.handlePrimaryPointer
(package:flutter/src/gestures/tap.dart:239:7)
                    #11     PrimaryPointerGestureRecognizer.handleEvent
(package:flutter/src/gestures/recognizer.dart:615:9)
                    #12     PointerRouter._dispatch
(package:flutter/src/gestures/pointer_router.dart:98:12)
                    #13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
                    (package:flutter/src/gestures/pointer_router.dart:143:9)
                    #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
                    #15     PointerRouter._dispatchEventToRoutes
(package:flutter/src/gestures/pointer_router.dart:141:18)
                    #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
                    #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
                    #18     GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:440:22)
                    #19     RendererBinding.dispatchEvent
(package:flutter/src/rendering/binding.dart:336:11)
                    #20     GestureBinding._handlePointerEventImmediately
(package:flutter/src/gestures/binding.dart:395:7)
                    #21     GestureBinding.handlePointerEvent
(package:flutter/src/gestures/binding.dart:357:5)
                    #22     GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:314:7)
                    #23     GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:295:7)
                    #24     _invoke1 (dart:ui/hooks.dart:164:13)
                    #25     PlatformDispatcher._dispatchPointerDataPacket
(dart:ui/platform_dispatcher.dart:361:7)
                    #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
                    (elided one frame from dart:async)
                    
                    Handler: "onTap"
                    Recognizer:
                      TapGestureRecognizer#7e3fe

════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing example...                                                    
No issues found! (ran in 0.7s)
```

```
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
    • Flutter version 3.7.8 on channel stable at /Users/eli1stark/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (2 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/eli1stark/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 06D4130A-8626-4B40-82DA-F463E0719F26 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.2.1
      22D68 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Using code sample and steps to replicate, seeing same behavior as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.7, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.7 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (12 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.9.0-16.0.pre.42, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.9.0-16.0.pre.42 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a8afbfa22e (47 minutes ago), 2023-03-24 00:00:20 -0400
    • Engine revision 1da070c57c
    • Dart version 3.0.0 (build 3.0.0-362.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by patelkathan** [comment]
Any update on this one? We are still facing it.

**Comment by thphuc** [comment]
I am getting this issue just now after upgrading to ^6.5.1

**Comment by chunhtai** [comment]
This seems to be caused by https://github.com/flutter/packages/pull/3368/files cc @NazarenoCavazzon

**Comment by NazarenoCavazzon** [comment]
I think the problem is having the completer inside the ImperativeRouteMatch.

**Comment by NazarenoCavazzon** [comment]
It seems that is completing the Future of the `/settings` route instead of poping normally, using `Navigator.of(context).pop()` instead of context.pop() for dialogs works, but we need to add some kind of verification when completing the future.

**Comment by NazarenoCavazzon** [comment]
I think the best we can do is to take a look at the value we get in the pop, if the user wants to pop a value in a dialog it needs to use Navigator.of(context).pop(result) otherwise it'll not work because the showDialog method uses Navigator 1.0, and if they don't want to pop a value then because is null we don't complete the completer.

**Comment by kev-techi** [comment]
I got it working for the moment by using `Navigator.of(context).pop()` instead of `GoRouter.of(context).pop()` any time I am calling from inside some sort of alert, popup or dialog.

Seems like within dialogs, the Navigator and GoRouter are out of sync.
