### ISSUE TITLE
ios Simulator/iPhone connection issues

### ISSUE THREAD

**Issue by frederickcook** [flutter/flutter#12330]
## Steps to Reproduce

I have two issues that seem like they are likely related. These issues roughly correspond with when I upgraded to Xcode 9 but I can't say that for sure.

The first issue is that hot reload, full restart, and quit are not working from the command line. The terminal window simply prints the letter and does not take any action upon pressing `r`, `R`, or `q`. The same issue also exists in IntelliJ - hot reload and full restart are not options and Stop doesn't actually stop the application. Also, runtime logging (from `print` statements) is not showing up in either terminal or IntelliJ.

The second issue is that I am getting an error sometimes from `flutter run -v`. This is happening both with the simulator and my physical iPhone.

## Logs

```
% flutter run -v
[  +37 ms] [/Users/frederickcook/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[        ] [/Users/frederickcook/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/frederickcook/flutter/] git log -n 1 --pretty=format:%H
[  +20 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 701d534ba93eaa3452f5e6b8b73ad8bd5a48847b
[        ] [/Users/frederickcook/flutter/] git log -n 1 --pretty=format:%ar
[  +14 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[ +649 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +154 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 2.3
[ +414 ms] Listing devices using /Users/frederickcook/Library/Android/sdk/platform-tools/adb
[        ] /Users/frederickcook/Library/Android/sdk/platform-tools/adb devices -l
[  +34 ms] Exit code 0 from: /Users/frederickcook/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +5 ms] idevice_id -h
[ +192 ms] "flutter run" took 1,326ms.
idevice_id returned an error:
ERROR: Could not connect to lockdownd, error code -8


#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:88)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:84)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:38)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:145)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:91)
<asynchronous suspension>
#5      DeviceManager.getDevices (package:flutter_tools/src/device.dart:81)
#6      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:258)
<asynchronous suspension>
#7      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:222)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#15     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1467)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#24     main (file:///Users/frederickcook/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[ +187 ms] ensureAnalyticsSent: 166ms
[   +5 ms] exiting with code 1
```

## Flutter Doctor

```
% flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/frederickcook/flutter
    • Framework revision 701d534ba9 (2 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/frederickcook/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • iPhone 7 • 2AE532E3-5B4B-4D8D-8CFB-F54C3BF6F8EE • ios • iOS 11.0 (simulator)
```

**Comment by frederickcook** [comment]
Switching to channel `master`  fixed this issue, though I am still unable to get flutter to identify my phone. I'll post in a separate issue.

**Comment by g-balas** [comment]
This is closed but still have this issue on Android and iOS... restart everything (android studio, emulator, clean) seems to work sometimes...

**Comment by zoechi** [comment]
@g-balas follow #24600
