### ISSUE TITLE
Firebase API level 25 disabled, emulator flaky. Re-enable when possible.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123331]
I am seeing timeouts on these shards causing several rolls to fail. Here is an example:

https://github.com/flutter/flutter/pull/123326

The error is always a problem with Nexus6P-25-en-portrait:

```
More details are available at [ https://console.firebase.google.com/project/flutter-infra-staging/testlab/histories/bh.1b5619c8ceae9dab/matrices/8189569969374284640 ].
WARNING: Need help for test execution [Nexus6P-25-en-portrait]? Please join the #test-lab Slack channel at https://firebase.community/ and include test matrix ID [matrix-247c2wpmkeenp] with your question.
┌──────────────┬────────────────────────────┬────────────────────────┐
│   OUTCOME    │      TEST_AXIS_VALUE       │      TEST_DETAILS      │
├──────────────┼────────────────────────────┼────────────────────────┤
│ Passed       │ Nexus5-21-en-portrait      │ --                     │
│ Passed       │ Nexus5-22-en-portrait      │ --                     │
│ Passed       │ Nexus5-23-en-portrait      │ --                     │
│ Passed       │ Nexus6P-26-en-portrait     │ --                     │
│ Passed       │ Nexus6P-27-en-portrait     │ --                     │
│ Passed       │ NexusLowRes-29-en-portrait │ --                     │
│ Inconclusive │ Nexus6P-25-en-portrait     │ Infrastructure failure │
└──────────────┴────────────────────────────┴────────────────────────┘
```

@dnfield do you know if we have any way to figure out what's going on there?

**Comment by dnfield** [comment]
Seems like a firebase infra issue:

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.vending.selfupdate.INTENT_PACKAGE_INSTALL_COMMIT.com.android.vending flg=0x10 (has extras) } in com.google.android.finsky.selfupdate.a.m@6895a70
     FATAL EXCEPTION: main
Process: com.android.vending, PID: 5564
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.vending.selfupdate.INTENT_PACKAGE_INSTALL_COMMIT.com.android.vending flg=0x10 (has extras) } in com.google.android.finsky.selfupdate.a.m@6895a70
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.SecurityException: Caller has no access to session 1505710097
	at android.os.Parcel.readException(Parcel.java:1684)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.content.pm.IPackageInstaller$Stub$Proxy.abandonSession(IPackageInstaller.java:304)
	at android.content.pm.PackageInstaller.abandonSession(PackageInstaller.java:369)
	at com.google.android.finsky.selfupdate.a.m.onReceive(SourceFile:2170)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
	... 7 more
``` 

We retried it three times and gave up.

We could remove this device from the pool for now.

**Comment by dnfield** [comment]
I've also reached out to someone on the firebase team to see if they can help.

**Comment by dnfield** [comment]
Recipe change landed, going to lower priority on this and use it to track re-enabling the emulator when possible.

**Comment by temawi** [comment]
FYI, grpc-java has been seeing this with `Nexus6P-24-en-portrait` and `Nexus6P-25-en-portrait`.

**Comment by zanderso** [comment]
@dnfield Was there any advice from the FTL folks about if/when this emulator could be added back?

**Comment by dnfield** [comment]
No. They said it's a bug the Android team is working on.
