### ISSUE TITLE
[image_picker]: java.lang.IllegalArgumentException - Couldn't find meta-data for provider with authority

### ISSUE THREAD

**Issue by rohansohonee1** [flutter/flutter#123381]
Crash stack trace:
```
Caused by java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.agendaboa.app.flutter.image_provider
       at androidx.core.content.FileProvider.getFileProviderPathsMetaData(FileProvider.java:664)
       at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:695)
       at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:645)
       at androidx.core.content.FileProvider.attachInfo(FileProvider.java:424)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8210)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7746)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7566)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

## Steps to Reproduce
Unable to reproduce

**Expected results:** 
Should not crash.

**Actual results:** 
Application is crashing.

**Device details:**
```
Device
Brand:Samsung
Model:Galaxy A50
Orientation: Portrait
RAM free: 920.79 MB
Disk free: 63.71 GB
Operating System
Version:Android 11
Orientation: Portrait
Rooted:No
Crash
Date:Mar 19, 2023, 1:19:16 AM
```

**Flutter details:**
```
Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (5 months ago) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0
```

**Image picker version:**
```
image_picker: 0.8.6
```

Currently this issue has 1 crash event affecting 1 user.

**Comment by darshankawar** [comment]
Thanks for the report @rohansohonee1 
Without a concrete reproducible code, it'll be tough to make this issue actionable.
Looking at the error log, it may be related to how the manifest file is setup and could be misconfigure, but this is just my guess.
Maybe check [this](https://stackoverflow.com/a/59444356) SO link and see if it helps in your case or not.

**Comment by rohansohonee1** [comment]
This provider tag is implemented by image_picker library. See here https://github.com/flutter/packages/blob/main/packages/image_picker/image_picker_android/android/src/main/AndroidManifest.xml

**Comment by darshankawar** [comment]
See below links and check if they help:

https://github.com/flutter/flutter/issues/84324#issuecomment-861556973
https://github.com/flutter/flutter/issues/84324#issuecomment-867690365

**Comment by rohansohonee1** [comment]
The manifest file has the following:

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

<queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
            <category android:name="android.intent.category.DEFAULT" />
        </intent>
</queries>
```

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open for team's thoughts and attention.
