### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Illegal character in path: C:

### ISSUE THREAD

**Issue by ssharanyab** [flutter/flutter#123588]
## Command
```
flutter --no-color test --machine --platform chrome --coverage test
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Illegal character in path: C:
```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1841:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2879:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2854:38)
#3      JsonReporter._frameInfo.<anonymous closure> (package:test_core/src/runner/reporter/json.dart:314:19)
#4      IterableExtension.firstWhereOrNull (package:collection/src/iterable_extensions.dart:246:15)
#5      JsonReporter._frameInfo (package:test_core/src/runner/reporter/json.dart:312:35)
#6      JsonReporter._idsForGroups.<anonymous closure> (package:test_core/src/runner/reporter/json.dart:230:14)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#8      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#9      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#10     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#11     new List.of (dart:core-patch/array_patch.dart:51:28)
#12     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#13     JsonReporter._idsForGroups (package:test_core/src/runner/reporter/json.dart:236:8)
#14     JsonReporter._onTestStarted (package:test_core/src/runner/reporter/json.dart:133:11)
#15     _rootRunUnary (dart:async/zone.dart:1407:13)
#16     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#20     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#21     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#22     _rootRunUnary (dart:async/zone.dart:1399:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
```
```
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2728], locale en-IN)
    • Flutter version 3.3.10 on channel stable at D:\Installs\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\sshar\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Java\jdk-11.0.17\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.25)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33423.256
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.76.1)
    • VS Code at C:\Users\sshar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.111
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.5.11+42
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
connectivity_plus-3.0.3
file_picker-5.2.6
firebase_auth-4.3.0
firebase_auth_web-5.2.10
firebase_core-2.8.0
firebase_core_web-2.2.2
firebase_storage-11.0.16
firebase_storage_web-3.3.25
flutter_plugin_android_lifecycle-2.0.9
google_sign_in-5.4.4
google_sign_in_android-6.1.8
google_sign_in_ios-5.6.1
google_sign_in_web-0.10.2+1
package_info_plus-3.0.3
path_provider-2.0.14
path_provider_android-2.0.24
path_provider_foundation-2.2.0
path_provider_linux-2.1.10
path_provider_windows-2.1.5
sentry_flutter-6.22.0
shared_preferences-2.0.20
shared_preferences_android-2.0.17
shared_preferences_foundation-2.1.5
shared_preferences_linux-2.1.5
shared_preferences_web-2.0.6
shared_preferences_windows-2.1.5
sqflite-2.2.6

**Comment by exaby73** [comment]
Hello @ssharanyab. Could you provide the path of the project you are trying to run on your local machine?

**Comment by ssharanyab** [comment]
E:\[project_name]

**Comment by exaby73** [comment]
Can you try moving either the project and you Flutter install to your `C:` partition?
