### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by srkakadiya** [flutter/flutter#123539]
## Command
```
flutter run -d chrome --web-port=8080
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:77:7)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:184:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:162:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:843:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:488:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6.2 21G320 darwin-x64, locale en-GB)
    • Flutter version 3.3.10 on channel stable at /Users/eheuristic/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/eheuristic/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      Se

**Comment by huycozy** [comment]
Hi @srkakadiya 
Can you retry on the latest master channels to see if it's fixed or not?
