### ISSUE TITLE
flutter_plugin_tools: No such file or directory

### ISSUE THREAD

**Issue by MarcinusX** [flutter/flutter#12351]
I got an error when trying to run flutter_plugin_tools analyze or flutter_plugin_tools format:
## Steps to Reproduce
`pub global activate flutter_plugin_tools`
```
Package flutter_plugin_tools is currently active at version 0.0.5.
Resolving dependencies... (3.2s)
+ args 0.13.7 (1.0.0 available)
+ async 1.13.3 (2.0.0 available)
+ charcode 1.1.1
+ collection 1.14.3
+ flutter_plugin_tools 0.0.5
+ http 0.11.3+15
+ http_parser 3.1.1
+ path 1.4.2
+ source_span 1.4.0
+ stack_trace 1.8.2
+ string_scanner 1.0.2
+ typed_data 1.1.5
Precompiling executables... 
Precompiled flutter_plugin_tools:flutter_plugin_tools.
Activated flutter_plugin_tools 0.0.5.
```
`pub global run flutter_plugin_tools analyze`
```
Activating tuneup package...
Unhandled exception:
ProcessException: No such file or directory
  Command: pub global activate tuneup
#0      runAndStream (package:flutter_plugin_tools/src/common.dart:59)
<asynchronous suspension>
#1      AnalyzeCommand.run (package:flutter_plugin_tools/src/analyze_command.dart:25)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#4      new Future.sync (dart:async/future.dart:222)
#5      CommandRunner.run (package:args/command_runner.dart:109)
#6      main (package:flutter_plugin_tools/src/main.dart:37)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## Flutter Doctor
```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/marcinus/flutter
    • Framework revision 701d534ba9 (3 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/marcinus/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /home/marcinus/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/marcinus/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • None

```
I have tried reinstalling dart and pub, nothing helped.

**Comment by goderbauer** [comment]
Do you have `pub` in your path? The plugin_tools currently require it to be there.

**Comment by MarcinusX** [comment]
It solved the issue for `analyze` but `format` still gives me same error.

`pub global run flutter_plugin_tools format`
```
Downloading Google Java Format...
Formatting all .dart files...
Unchanged /MY_PATH/plugins/packages/firebase_messaging/test/firebase_messaging_test.dart
...
Unchanged /MY_PATH/plugins/packages/firebase_admob/example/lib/main.dart
Formatting all .java files...
Formatting all .m and .h files...
Unhandled exception:
ProcessException: No such file or directory
  Command: clang-format -i --style=Google /MY_PATH/plugins/packages/firebase_messaging/example/ios/Runner/AppDelegate.h
/MY_PATH/plugins/packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.h
...
/MY_PATH/plugins/packages/firebase_admob/ios/Classes/FirebaseAdmobPlugin.m
/MY_PATH/plugins/packages/firebase_admob/ios/Classes/MobileAd.m
#0      runAndStream (package:flutter_plugin_tools/src/common.dart:59)
<asynchronous suspension>
#1      FormatCommand._formatObjectiveC (package:flutter_plugin_tools/src/format_command.dart:82)
<asynchronous suspension>
#2      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:40)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#5      new Future.sync (dart:async/future.dart:222)
#6      CommandRunner.run (package:args/command_runner.dart:109)
#7      main (package:flutter_plugin_tools/src/main.dart:37)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by goderbauer** [comment]
`format` requires clang-format version 5 in your path to format Obj-C code. If it's not in your path, you can also specify where to find clang-format on your system with the `--clang-format=<path-to-clang-format-5>` parameter.

We should probably document this better / provide better error messages.

**Comment by MarcinusX** [comment]
From Ubuntu 16.04 perspective:
I have installed clang-format (an then `format` worked) but from what I see latest official release is 3.4. Do you have any guidelines how to install clang-format-5.0 on Linux?

**Comment by mit-mit** [comment]
@goderbauer any tips on the question above?

**Comment by goderbauer** [comment]
I don’t really. A quick google search points to http://apt.llvm.org, where it looks like “apt-get install clang-format-5.0” should just work, but I haven’t tried that.

**Comment by zoechi** [comment]
@MarcinusX is this still an issue?

**Comment by MarcinusX** [comment]
@zoechi Moved from ubuntu to mac, so I cannot reproduce anymore.

**Comment by zoechi** [comment]
@MarcinusX thanks for the update!
I'm going to close. Feel free to reopen if you run into it again.
