### ISSUE TITLE
Check that initState and didUpdateWidget don't return Futures

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12366]
If you make those functions async, all kinds of crazy things happen.

**Comment by alibitek** [comment]
For some reason this code:
```
  @override
  Future<Null> initState() async {
    await _init();
    super.initState();
  }
```

yields `[        ] E/flutter (12771): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 979 pos 12: '_debugLifecycleState == _StateLifecycle.created': is not true.` 

Stacktrace:
```
[ +140 ms] E/flutter (12771): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[        ] E/flutter (12771): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 979 pos 12: '_debugLifecycleState == _StateLifecycle.created': is not true.
[        ] E/flutter (12771): #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
[        ] E/flutter (12771): #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
[        ] E/flutter (12771): #2      State.initState (package:flutter/src/widgets/framework.dart:979:12)
[        ] E/flutter (12771): #3      OrdersAppState.initState (/data/user/0/com.company.app/cache/daviatacartiitaleKOFBDY/daviatacartiitale/lib/App.dart:81:20)
[        ] E/flutter (12771): <asynchronous suspension>
[        ] E/flutter (12771): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3711:14)
[        ] E/flutter (12771): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3577:5)
[        ] E/flutter (12771): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875:14)
[        ] E/flutter (12771): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2678:12)
[        ] E/flutter (12771): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:843:16)
[        ] E/flutter (12771): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:814:5)
[        ] E/flutter (12771): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:760:17)
[        ] E/flutter (12771): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2190:19)
[        ] E/flutter (12771): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:759:13)
[        ] E/flutter (12771): #13     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:648:7)
[        ] E/flutter (12771): #14     runApp (package:flutter/src/widgets/binding.dart:690:7)
[        ] E/flutter (12771): #15     main (/data/user/0/com.company.app/cache/daviatacartiitaleKOFBDY/daviatacartiitale/lib/App.dart:19:3)
[        ] E/flutter (12771): #16     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
[        ] E/flutter (12771): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by Hixie** [comment]
Yeah, if you don't call `super.initState` before returning then the `State` object will be in a broken state.

The code above is synchronously equivalent to:

```dart
  @override
  void initState() {
    _init();
  }
  // more code is run later, including the call to super.initState
```

**Comment by jonahwilliams** [comment]
I working on this currently

**Comment by watchdog19** [comment]
I also have this error
