### ISSUE TITLE
[Impeller] Gracefully handle the shader removal case in malioc_diff.py

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#123624]
Currently it just throws an uncaught exception instead of printing which shaders have been removed:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8785361854349439697/+/u/malioc_diff/stdout

```
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/flutter/impeller/tools/malioc_diff.py", line 306, in <module>
    sys.exit(main(sys.argv))
  File "/b/s/w/ir/cache/builder/src/flutter/impeller/tools/malioc_diff.py", line 282, in main
    if core not in after_json[filename].keys():
KeyError: 'flutter/impeller/entity/gaussian_blur.frag.vkspv'
```

**Comment by zanderso** [comment]
Done in https://github.com/flutter/engine/pull/40720
