### ISSUE TITLE
Unhandled Exception: 'package:go_router/src/matching.dart': Failed assertion: line 138 pos 12: 'index != -1': is not true.

### ISSUE THREAD

**Issue by h4h13** [flutter/flutter#123769]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... I'm using the go_router pub and whenever pop the page this error comes 
3. ... It's random times sometimes constantly come after poping the 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```
Check the code and repo here 
https://github.com/RetroMusicPlayer/Paisa/blob/master/lib/src/presentation/expense/pages/expense_page.dart
```

</details>

<details>
  <summary>Logs</summary>

```
flutter doctor --verbose 
[√] Flutter (Channel beta, 3.9.0-0.2.pre, on Microsoft Windows [Version 10.0.22621.1413], locale en-IN)
    • Flutter version 3.9.0-0.2.pre on channel beta at C:\Users\Hemanth S\flutter
[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32014.148
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\Hemanth S\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.69

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

```
Analyzing flutter_expense...                                            

   info - Use 'const' with the constructor to improve performance - lib\src\app\routes.dart:97:40 - prefer_const_constructors
   info - Don't invoke 'print' in production code - lib\src\core\currency_util.dart:74:3 - avoid_print
   info - Unnecessary type check; the result is always 'true' - lib\src\core\extensions\commont.dart:22:15 - unnecessary_type_check
   info - Unused import: 'package:collection/collection.dart' - lib\src\core\extensions\debt_extensions.dart:1:8 - unused_import
   info - Unused import: 'package:paisa/src/data/debt/models/transactions_model.dart' - lib\src\core\extensions\debt_extensions.dart:3:8 - unused_import
   info - Unused import: 'package:paisa/src/domain/debt/entities/transaction.dart' - lib\src\core\extensions\debt_extensions.dart:5:8 - unused_import
   info - The imported package 'flutter_web_plugins' isn't a dependency of the importing package - lib\src\di\di.dart:4:8 - depend_on_referenced_packages
   info - The imported package 'meta' isn't a dependency of the importing package - lib\src\presentation\accounts\bloc\accounts_bloc.dart:6:8 - depend_on_referenced_packages
   info - The import of '../../../core/extensions/account_extension.dart' is unnecessary because all of the used elements are also provided by the import of
          '../../../core/common.dart' - lib\src\presentation\accounts\widgets\account_card_v2.dart:7:8 - unnecessary_import
   info - The import of '../../../core/extensions/account_extension.dart' is unnecessary because all of the used elements are also provided by the import of
          '../../../core/common.dart' - lib\src\presentation\accounts\widgets\account_transaction_widget.dart:6:8 - unnecessary_import
   info - The import of '../../../core/extensions/account_extension.dart' is unnecessary because all of the used elements are also provided by the import of
          '../../../core/common.dart' - lib\src\presentation\accounts\widgets\accounts_page_view_widget.dart:3:8 - unnecessary_import
   info - Empty catch block - lib\src\presentation\category\widgets\set_budget_widget.dart:90:23 - empty_catches
   info - The import of 'package:paisa/src/domain/debt/use_case/delete_transactions_use_case.dart' is unnecessary because all of the used elements are also provided by the import
          of '../../../domain/debt/use_case/debt_use_case.dart' - lib\src\presentation\debits\cubit\debts_cubit.dart:7:8 - unnecessary_import
   info - Empty catch block - lib\src\presentation\debits\pages\add\add_debt_page.dart:390:23 - empty_catches
   info - Unused import: 'package:paisa/src/core/extensions/debt_extensions.dart' - lib\src\presentation\debits\widgets\debt_item_widget.dart:6:8 - unused_import
   info - The import of 'package:paisa/src/core/extensions/transaction_extension.dart' is unnecessary because all of the used elements are also provided by the import of
          '../../../core/common.dart' - lib\src\presentation\debits\widgets\debt_item_widget.dart:7:8 - unnecessary_import
   info - The import of 'package:meta/meta.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' -
          lib\src\presentation\expense\bloc\expense_bloc.dart:7:8 - unnecessary_import
   info - The imported package 'meta' isn't a dependency of the importing package - lib\src\presentation\expense\bloc\expense_bloc.dart:7:8 - depend_on_referenced_packages
   info - Unused import: '../pages/expense_page.dart' - lib\src\presentation\expense\bloc\expense_bloc.dart:20:8 - unused_import
   info - Empty catch block - lib\src\presentation\expense\pages\expense_page.dart:380:23 - empty_catches
   info - The import of '../../../core/extensions/account_extension.dart' is unnecessary because all of the used elements are also provided by the import of
          '../../../core/common.dart' - lib\src\presentation\expense\widgets\select_account_widget.dart:11:8 - unnecessary_import
   info - The imported package 'meta' isn't a dependency of the importing package - lib\src\presentation\home\bloc\home_bloc.dart:6:8 - depend_on_referenced_packages
   info - Use 'const' with the constructor to improve performance - lib\src\presentation\home\pages\home_desktop_widget.dart:169:23 - prefer_const_constructors
   info - The import of '../../../core/extensions/account_extension.dart' is unnecessary because all of the used elements are also provided by the import of
          '../../../core/common.dart' - lib\src\presentation\overview\pages\expense_list_page.dart:4:8 - unnecessary_import
   info - 'shareFiles' is deprecated and shouldn't be used. Use shareXFiles instead - lib\src\presentation\settings\widgets\export_expenses_widget.dart:69:11 -
          deprecated_member_use
   info - The import of '../../../core/extensions/account_extension.dart' is unnecessary because all of the used elements are also provided by the import of
          '../../../core/common.dart' - lib\src\presentation\summary\widgets\expense_total_widget.dart:6:8 - unnecessary_import
   info - Unused import: 'package:material_design_icons_flutter/material_design_icons_flutter.dart' - lib\src\presentation\widgets\paisa_user_image_widget.dart:5:8 -
          unused_import
   info - Use 'const' with the constructor to improve performance - lib\src\presentation\widgets\paisa_user_widget.dart:27:24 - prefer_const_constructors

28 issues found. (ran in 16.2s)
```

```
[√] Flutter (Channel beta, 3.9.0-0.2.pre, on Microsoft Windows [Version 10.0.22621.1413], locale en-IN)
    • Flutter version 3.9.0-0.2.pre on channel beta at C:\Users\Hemanth S\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0df8557c56 (6 days ago), 2023-03-23 22:02:01 -0500
    • Engine revision 1cc4b2d280
    • Dart version 3.0.0 (build 3.0.0-290.3.beta)
    • DevTools version 2.22.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Hemanth S\AppData\Local\Android\Sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.1
    • ANDROID_HOME = C:\Users\Hemanth S\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32014.148
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\Hemanth S\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.69

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

```
Restarted application in 1,218ms.
[GoRouter] Full paths for routes:
             => /intro
             => /login
             => /splash
             => /landing
             =>   /landing/add-expense
             =>   /landing/edit-expense/:eid
             =>   /landing/add-category
             =>   /landing/categories
             =>   /landing/edit-category/:cid
             =>   /landing/add-account
             =>   /landing/edit-account/:aid
             =>   /landing/account/:aid
             =>   /landing/expenses/:cid
             =>   /landing/export-import
             =>   /landing/settings
             =>   /landing/debit-add
             =>   /landing/debt/:did
             =>   /landing/debt
             => /user-name
             => /user-image
           known full paths for route names:
             intro => /intro
             login => /login
             splash => /splash
             landing => /landing
             add-expense => /landing/add-expense
             edit-expense => /landing/edit-expense/:eid
             add-category => /landing/add-category
             categories => /landing/categories
             edit-category => /landing/edit-category/:cid
             add-account => /landing/add-account
             edit-account => /landing/edit-account/:aid
             account-transaction => /landing/account/:aid
             expenses => /landing/expenses/:cid
             export-import => /landing/export-import
             settings => /landing/settings
             debit-add => /landing/debit-add
             edit-debt => /landing/debt/:did
             debt => /landing/debt
             user-name => /user-name
             user-image => /user-image
[GoRouter] setting initial location /intro
[GoRouter] redirecting to RouteMatchList(/landing)
[GoRouter] Using MaterialApp configuration
I/flutter ( 7055): dynamic_color: Core palette detected.
D/EGL_emulation( 7055): app_time_stats: avg=1321.14ms min=69.42ms max=5002.89ms count=4
[GoRouter] getting location for name: "add-expense"
[GoRouter] pushing /landing/add-expense
D/EGL_emulation( 7055): app_time_stats: avg=392.58ms min=62.57ms max=981.32ms count=3
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
W/OnBackInvokedCallback( 7055): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback( 7055): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/InsetsController( 7055): show(ime(), fromIme=true)
D/EGL_emulation( 7055): app_time_stats: avg=5723.19ms min=0.54ms max=74377.38ms count=13
D/EGL_emulation( 7055): app_time_stats: avg=105.92ms min=8.80ms max=664.51ms count=9
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputMethodManager( 7055): showSoftInput() view=io.flutter.embedding.android.FlutterView{89f7636 VFE...... .F...... 0,0-1080,2340 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 7055): show(ime(), fromIme=true)
D/InsetsController( 7055): show(ime(), fromIme=true)
D/EGL_emulation( 7055): app_time_stats: avg=21.72ms min=1.62ms max=261.84ms count=27
D/EGL_emulation( 7055): app_time_stats: avg=22.53ms min=1.61ms max=385.76ms count=21
D/EGL_emulation( 7055): app_time_stats: avg=219.03ms min=0.62ms max=2800.19ms count=13
D/EGL_emulation( 7055): app_time_stats: avg=11.29ms min=1.56ms max=168.77ms count=26
D/EGL_emulation( 7055): app_time_stats: avg=338.47ms min=1.96ms max=3202.20ms count=10
[GoRouter] popping /landing/add-expense
E/flutter ( 7055): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:go_router/src/matching.dart': Failed assertion: line 138 pos 12: 'index != -1': is not true.
E/flutter ( 7055): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 7055): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 7055): #2      RouteMatchList.remove
E/flutter ( 7055): #3      GoRouterDelegate._onPopPage
E/flutter ( 7055): #4      NavigatorState.pop
E/flutter ( 7055): #5      GoRouterDelegate.pop
E/flutter ( 7055): #6      GoRouter.pop
E/flutter ( 7055): #7      GoRouterHelper.pop
E/flutter ( 7055): #8      _ExpensePageState.build.<anonymous closure>.<anonymous closure>
E/flutter ( 7055): <asynchronous suspension>
E/flutter ( 7055):

════════ Exception caught by widgets library ═══════════════════════════════════
The following StateError was thrown building InheritedGoRouter(goRouter: Instance of 'GoRouter'):
Bad state: Future already completed

The relevant error-causing widget was
MaterialApp
When the exception was thrown, this was the stack
#1      Route.didComplete
#2      _RouteEntry.handleComplete
#3      NavigatorState._flushHistoryUpdates
#4      NavigatorState._updatePages
#5      NavigatorState.didUpdateWidget
#6      StatefulElement.update
#7      Element.updateChild
#8      ComponentElement.performRebuild
#9      Element.rebuild
#10     ProxyElement.update
#11     _InheritedNotifierElement.update
#12     Element.updateChild
#13     ComponentElement.performRebuild
#14     Element.rebuild
#15     ProxyElement.update
#16     _InheritedNotifierElement.update
#17     Element.updateChild
#18     ComponentElement.performRebuild
#19     Element.rebuild
#20     StatelessElement.update
#21     Element.updateChild
#22     ComponentElement.performRebuild
#23     Element.rebuild
#24     ProxyElement.update
#25     _InheritedNotifierElement.update
#26     Element.updateChild
#27     ComponentElement.performRebuild
#28     Element.rebuild
#29     StatelessElement.update
#30     Element.updateChild
#31     ComponentElement.performRebuild
#32     Element.rebuild
#33     ProxyElement.update
#34     Element.updateChild
#35     ComponentElement.performRebuild
#36     Element.rebuild
#37     ProxyElement.update
#38     Element.updateChild
#39     ComponentElement.performRebuild
#40     StatefulElement.performRebuild
#41     Element.rebuild
#42     BuildOwner.buildScope
#43     WidgetsBinding.drawFrame
#44     RendererBinding._handlePersistentFrameCallback
#45     SchedulerBinding._invokeFrameCallback
#46     SchedulerBinding.handleDrawFrame
#47     SchedulerBinding._handleDrawFrame
#48     _invoke (dart:ui/hooks.dart:142:13)
#49     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#50     _drawFrame (dart:ui/hooks.dart:112:31)
(elided one frame from dart:async)
════════════════════════════════════════════════════════════════════════════════
E/flutter ( 7055): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2918 pos 18: '!navigator._debugLocked': is not true.
E/flutter ( 7055): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 7055): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 7055): #2      _RouteEntry.handlePush.<anonymous closure>
E/flutter ( 7055): #3      TickerFuture.whenCompleteOrCancel.thunk
E/flutter ( 7055): <asynchronous suspension>
E/flutter ( 7055): #4      TickerFuture.whenCompleteOrCancel.thunk
E/flutter ( 7055): <asynchronous suspension>
E/flutter ( 7055):
D/EGL_emulation( 7055): app_time_stats: avg=337.78ms min=1.43ms max=3894.84ms count=12

```
</details>

**Comment by h4h13** [comment]
Video 
[crash.webm](https://user-images.githubusercontent.com/2574895/228835041-da6be0a9-0507-45eb-bd8c-5556a4fe93d4.webm)

**Comment by huycozy** [comment]
Hi @h4h13 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. Thank you!
