### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#12372]
```
[   +2 ms] :app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
[ +104 ms] :app:compileDebugJavaWithJavac
[        ] :app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
[+2191 ms] Note: Some input files use or override a deprecated API.
[   +1 ms] Note: Recompile with -Xlint:deprecation for details.
[        ] Note: Some input files use unchecked or unsafe operations.
[        ] Note: Recompile with -Xlint:unchecked for details.
[ +210 ms] :app:compileDebugNdk UP-TO-DATE
[        ] :app:compileDebugSources
[+2060 ms] :app:transformClassesWithJarMergingForDebug
[+6174 ms] :app:transformClassesWithMultidexlistForDebug
[+32583 ms] :app:transformClassesWithDexForDebug FAILED
[  +18 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:transformClassesWithDexForDebug'.
[        ] > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
[   +6 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[        ] BUILD FAILED
[        ] Total time: 56.249 secs
[ +701 ms] "flutter run" took 69,503ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:304)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:237)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/commands/build_apk.dart:82)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:361)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:249)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:199)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:345)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:241)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#16     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>

```

```
$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/reyer/reyer/flutter/master
    • Framework revision 0044ea2dbb (34 hours ago), 2017-10-02 00:06:24 -0700
    • Engine revision bdfedcc26f
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/reyer/Android/Sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /home/reyer/Android/Sdk
    • Java binary at: /home/reyer/.local/share/umake/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/reyer/.local/share/umake/android/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Android SDK built for x86 • emulator-5558 • android-x86 • Android 7.0 (API 24) (emulator)
    • emulator-5556             • emulator-5556 • android-x86 • Android 4.1.2 (API 16) (emulator)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

```

**Comment by Hixie** [comment]
We need more information to be able to do anything here, like what was the code you were trying to compile? What are the steps to reproduce?

**Comment by frlzjosh** [comment]
did you ever figure this out ?

**Comment by JFixby** [comment]
Sorry folks, it was in October. I just don't remember.

**Comment by Hixie** [comment]
Ok I'm going to close this. Thanks for filing the issue, don't hesitate to file a new one if you see this again!
