### ISSUE TITLE
[tool_crash] SessionNotCreatedException

### ISSUE THREAD

**Issue by sahithibv** [flutter/flutter#123764]
## Command
```
flutter drive \ --driver=test_driver/integration_test.dart \ --target=integration_test/app_test.dart \ -d chrome
```

## Steps to Reproduce
1. Run the test scripts using above command 
2. after integration tests completed 
3. crash shows 

## Logs
SessionNotCreatedException
```
#0      parseJsonWireResponse (package:webdriver/src/handler/json_wire/utils.dart:80:9)
#1      JsonWireSessionHandler.parseInfoResponse (package:webdriver/src/handler/json_wire/session.dart:27:21)
#2      JsonWireSessionHandler.parseCreateResponse (package:webdriver/src/handler/json_wire/session.dart:18:7)
#3      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:100:39)
#4      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#5      createDriver (package:webdriver/async_core.dart:64:19)
<asynchronous suspension>
#6      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
<asynchronous suspension>
#7      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:309:30)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version
    10.0.19044.1889], locale en-IN)
    [32m•[39m Flutter version 3.7.3 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 9944297138 (7 weeks ago), 2023-02-08
      15:46:04 -0800
    [32m•[39m Engine revision 248290d6d5
    [32m•[39m Dart version 2.19.2
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or
    higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK
    version 32.1.0-rc1)
    [32m•[39m Android SDK at C:\Users\nooor\AppData\Local\Android\Sdk
    [32m•[39m Platform android-32, build-tools 32.1.0-rc1
    [32m•[39m ANDROID_HOME =
      C:\Users\nooor\AppData\Local\Android\Sdk;C:\Users\nooor\AppDat
      a\Local\Android\Sdk\build-tools;C:\Users\nooor\AppData\Local\A
      ndroid\Sdk\platforms;C:\Users\nooor\AppData\Local\Android\Sdk\
      tools;C:\Users\nooor\AppData\Local\Android\Sdk\tools\bin;
    [32m•[39m Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Build Tools
    2019 16.11.17)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual
      Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.32630.194
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 4.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[32m[✓][39m VS Code (version 1.76.2)
    [32m•[39m VS Code at C:\Users\nooor\AppData\Local\Programs\Microsoft VS
      Code
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft
      Windows [Version 10.0.19044.1889]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome
      111.0.5563.147
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge
      109.0.1518.61

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 135454af32477f815a7525073027a3ff9eff1bfd
### Plugins
integration_test

**Comment by exaby73** [comment]
Hello @sahithibv. Does this happen with any test script or a specific one? Could you share a snippet of your test and app code so that I may test it as well?
