### ISSUE TITLE
malioc diff occassionally fails to produce a diff

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#123872]
See https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8785150541044992065/+/u/malioc_diff/stdout

The error is:

```
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/flutter/impeller/tools/malioc_diff.py", line 342, in <module>
    sys.exit(main(sys.argv))
  File "/b/s/w/ir/cache/builder/src/flutter/impeller/tools/malioc_diff.py", line 303, in main
    if compare_shaders(args.after, before_shader, after_shader):
  File "/b/s/w/ir/cache/builder/src/flutter/impeller/tools/malioc_diff.py", line 247, in compare_shaders
    differences += compare_variants(before_val, after_val)
  File "/b/s/w/ir/cache/builder/src/flutter/impeller/tools/malioc_diff.py", line 224, in compare_variants
    differences += compare_performance(
  File "/b/s/w/ir/cache/builder/src/flutter/impeller/tools/malioc_diff.py", line 207, in compare_performance
    pretty_list(before_cycles, fmt='f'),
  File "/b/s/w/ir/cache/builder/src/flutter/impeller/tools/malioc_diff.py", line 183, in pretty_list
    return (sep.join(['{:<{width}{fmt}}'] * len(lst))).format(
TypeError: unsupported format string passed to NoneType.__format__
```

Are we running with different version of python or missing dependencies sometimes? FYI @zanderso

**Comment by zanderso** [comment]
Not related to python version no. It looks like the problem is that not all data is captured for every shader. In particular the malioc.json golden has `null` recorded for some of the `longest_path_cycles` arrays. Taking a look.
