### ISSUE TITLE
[tool_crash] UnknownException

### ISSUE THREAD

**Issue by jaredsburrows** [flutter/flutter#123869]
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --web-browser-flag=--autoplay-policy=no-user-gesture-required --web-browser-flag=--disable-web-security --dart-define USE_LOCAL_SERVER=true
```

## Steps to Reproduce
1. git clone https://github.com/jaredsburrows/flutter-app-template
2. cd flutter-app-template
3. flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --web-browser-flag=--autoplay-policy=no-user-gesture-required --web-browser-flag=--disable-web-security --dart-define USE_LOCAL_SERVER=true

## Logs
UnknownException
```
#0      parseJsonWireResponse (package:webdriver/src/handler/json_wire/utils.dart:84:9)
#1      JsonWireSessionHandler.parseInfoResponse (package:webdriver/src/handler/json_wire/session.dart:27:21)
#2      JsonWireSessionHandler.parseCreateResponse (package:webdriver/src/handler/json_wire/session.dart:18:7)
#3      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:100:39)
#4      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#5      createDriver (package:webdriver/async_core.dart:64:19)
<asynchronous suspension>
#6      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
<asynchronous suspension>
#7      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:309:30)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.9, on macOS 13.0 22A8380 darwin-arm64, locale en-US)
    [32m•[39m Flutter version 3.7.9 on channel stable at /opt/homebrew/Caskroom/flutter/3.7.7/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 62bd79521d (21 hours ago), 2023-03-30 10:59:36 -0700
    [32m•[39m Engine revision ec975089ac
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /Users/<>/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m ANDROID_HOME = /Users/<>/Library/Android/sdk
    [32m•[39m ANDROID_SDK_ROOT = /Users/<>/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14C18
    [32m•[39m CocoaPods version 1.12.0

[32m[✓][39m Chrome - develop for the web
    [32m•[39m CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio Preview.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2023.1)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 72.1.5
    [32m•[39m Dart plugin version 231.8109.91

[32m[✓][39m VS Code (version 1.76.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (4 available)
    [32m•[39m sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    [32m•[39m macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0 22A8380 darwin-arm64
    [32m•[39m Web Server (web)            • web-server    • web-javascript • Flutter Tools
    [32m•[39m Chrome (web)                • chrome        • web-javascript • Brave Browser 111.1.49.128

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: fb57da5f945d02ef4f98dfd9409a72b7cce74268
### Plugins
integration_test

**Comment by jaredsburrows** [comment]
If I change:
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --web-browser-flag=--autoplay-policy=no-user-gesture-required --web-browser-flag=--disable-web-security --dart-define USE_LOCAL_SERVER=true
```
to:
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome--web-browser-flag=--autoplay-policy=no-user-gesture-required --web-browser-flag=--disable-web-security --dart-define USE_LOCAL_SERVER=true
```

Then the tests actually run. I am still seeing the following here:
```
Oops; flutter has exited unexpectedly: "UnknownException (13): unknown error: cannot find Chrome binary
  (Driver info: chromedriver=111.0.5563.64
  (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}),platform=Mac OS X 13.0.0 arm64)".
00:00 +0: Flutter Example starts at 0
00:00 +1: Flutter Example increments the counter
00:01 +2: Flutter Example increments the counter during animation
00:01 +3: (tearDownAll)
00:01 +4: All tests passed!
A crash report has been written to /Users/<>/repo/flutter-app-template/flutter_04.log.
This crash may already be reported. Check GitHub for similar crashes.
```

**Comment by huycozy** [comment]
Hi @jaredsburrows 

>Oops; flutter has exited unexpectedly: "UnknownException (13): unknown error: cannot find Chrome binary

Do you see this error on Chrome browser? Or does it only happen on Brave browser?

**Comment by jaredsburrows** [comment]
@huycozy Here is an example run on `ubuntu-latest` on Github actions - https://github.com/jaredsburrows/flutter-app-template/actions/runs/4572263954/jobs/8071335501. I believe this build has Chrome. It doe not show the warning.

However, I can set `CHROME_EXECUTABLE` and use the chromedriver to run tests with web successfully without chrome but the error still showed.

**Comment by huycozy** [comment]
Since I was facing https://github.com/flutter/flutter/issues/116936 when running the test, I did fix (minor) issues from your run command and sample code as below (to make sure others have correct steps to reproduce this)

1. Test command

(missing a space between `chrome` and `--web-browser-flag`)
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome --web-browser-flag=--autoplay-policy=no-user-gesture-required --web-browser-flag=--disable-web-security --dart-define USE_LOCAL_SERVER=true
```

2. Temporarily remove `setPathUrlStrategy()` on `main.dart`

And there is no error from the output:

```
💪 Running with sound null safety 💪
00:00 +0: Flutter Example starts at 0
00:00 +1: Flutter Example increments the counter
00:01 +2: Flutter Example increments the counter during animation
00:01 +3: (tearDownAll)
00:01 +4: All tests passed!
All tests passed.
No widgets found at Offset(787.8, 475.7).
Application finished.
```

I'm not sure why you changed `CHROME_EXECUTABLE` but it may be the cause of the issue. I suggest you reset it to the default to see if the test can run normally.

Chrome check status from my `flutter doctor -v`:
```
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```
