### ISSUE TITLE
Error in building apk and installing app in android.

### ISSUE THREAD

**Issue by vijayjvvc** [flutter/flutter#123960]
# I have also downloaded the gradle-7.5-all.zip file online but didn't work 
## Error is this :-
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\S\.gradle\wrapper\dists\gradle-7.5-all\6qsw290k5lz422uaf8jf6m7co\gradle-7.5-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by darshankawar** [comment]
> Timeout of 120000 reached waiting for exclusive access to file:

This most probably indicates a network related error. Try using a stable / fast internet connection.
Closing for now, as this doesn't seem to be a framework bug. If you disagree, write in comments and I'll reopen it.

**Comment by vijayjvvc** [comment]
Network is stable I am able to download and upload everything even dependency are syncing properly in my project only issue occurs while building apk and this problem is started in android studio latest version electric ele..

**Comment by darshankawar** [comment]
Can you provide complete error log by running `flutter build apk -v` ?

**Comment by darshankawar** [comment]
Also, check if [this](https://github.com/flutter/flutter/issues/124022#issuecomment-1494815573) helps in your case.
