### ISSUE TITLE
Unhandled exception related to AssetImage, reproducible on Android

### ISSUE THREAD

**Issue by mishadynin** [flutter/flutter#12392]
Ran into this with a recent Flutter upgrade.  It shows up if you rebuild the FLX with a recent flutter version.  Image appears to be loaded successfully.

## Steps to Reproduce

Working on isolating the use case.

## Logs

```
dynin-macpro:monarch dynin$ flutter run
Launching lib/main.dart on Nexus 9 in debug mode...
Initializing gradle...                                1.5s
Resolving dependencies...                             7.3s
Running 'gradlew assembleDebug'...                   16.0s
Built build/app/outputs/apk/app-debug.apk (30.9MB).
Installing build/app/outputs/apk/app.apk...          36.5s
Syncing files to device Nexus 9...                        
I/flutter (13519): Asset Id: assets/music/art.jpg uf false

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Nexus 9 is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
E/flutter (13519): [ERROR:lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (13519): Invalid argument(s)
E/flutter (13519): #0      SplayTreeMap.lastKeyBefore (dart:collection/splay_tree.dart:483)
E/flutter (13519): #1      AssetImage._findNearest (package:flutter/src/services/image_resolution.dart:236)
E/flutter (13519): #2      AssetImage._chooseVariant (package:flutter/src/services/image_resolution.dart:229)
E/flutter (13519): #3      AssetImage.obtainKey.<anonymous closure> (package:flutter/src/services/image_resolution.dart:169)
E/flutter (13519): #4      _RootZone.runUnary (dart:async/zone.dart:1371)
E/flutter (13519): #5      _FutureListener.handleValue (dart:async/future_impl.dart:129)
E/flutter (13519): #6      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
E/flutter (13519): #7      _Future._propagateToListeners (dart:async/future_impl.dart:665)
E/flutter (13519): #8      _Future._propagateToListeners (dart:async/future_impl.dart:563)
E/flutter (13519): #9      _Future._completeWithValue (dart:async/future_impl.dart:478)
E/flutter (13519): #10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
E/flutter (13519): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (13519): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
I/Choreographer(13519): Skipped 391 frames!  The application may be doing too much work on its main thread.
Application finished.
```
## Flutter Doctor

```
dynin-macpro:monarch dynin$ flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/dynin/flutter
    • Framework revision 701d534ba9 (3 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/dynin/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • Nexus 9 • HT4AFJT01242 • android-arm • Android 7.1.1 (API 25)
```

**Comment by mishadynin** [comment]
@emshack @krisgiesing created the bug to track the issue that shows up if you rebuild with FLX.

**Comment by Hixie** [comment]
cc @HansMuller and @szakarias who have worked in this area recently.

**Comment by mishadynin** [comment]
Added an isolated way to reproduce.
[imgbug.zip](https://github.com/flutter/flutter/files/1357196/imgbug.zip)

**Comment by mishadynin** [comment]
Note that sometimes when it runs, it hard crashes.
```dynin-macpro:imgbug dynin$ flutter run
Launching lib/main.dart on Nexus 9 in debug mode...
Initializing gradle...                                1.2s
Resolving dependencies...                             0.9s
Running 'gradlew assembleDebug'...                    1.3s
Built build/app/outputs/apk/app-debug.apk (26.0MB).
Syncing files to device Nexus 9...                        
I/flutter ( 3107): Asset Id: assets/music/art.jpg
F/libc    ( 3107): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 3124 (ui_thread)
Lost connection to device.
```

**Comment by mishadynin** [comment]
Further narrowing down the problem: the bug shows up if
`assetImage.obtainKey(ImageConfiguration.empty)` is called, and doesn't show up if it's not called.

**Comment by mishadynin** [comment]
Assigning to @HansMuller per conversation with @Hixie.

**Comment by HansMuller** [comment]
The problem here is that the _chooseVariant() logic in AssetImage.obtainKey() can't handle an ImageConfiguration with devicePixelRatio == null. ImageConfiguration.empty.devicePixelRatio is in fact null. 

If devicePixelRatio is null we should just use the main variant. I will submit a fix/test on Monday.

**Comment by krisgiesing** [comment]
Interesting. Why is devicePixelRatio null?

**Comment by HansMuller** [comment]
@krisgiesing The definition of [ImageConfiguration.empty](https://docs.flutter.io/flutter/services/ImageConfiguration/empty-constant.html) is essentially "no image configuration information".
