### ISSUE TITLE
No results appearing to me when I debug the application on chrome . 

### ISSUE THREAD

**Issue by MUGDAD-78** [flutter/flutter#124010]
When I try to debug my application on chrome there are no results that appear to me, I don't know if this issue is from my device or code.

I have added SVG Image to my project but I don't know if this issue came because of it, SVG Worked without a problem but the main problem is nothing is appearing in chrome when I debug it, also when I tried to debug it many times it took me to system.chrome.dart page. [flutter error](https://i.stack.imgur.com/pvYGX.png)

This is the Error :  

 ``` 
This RenderObject had the following child:
    text: TextSpan
Another exception was thrown: RuntimeError: unreachable
Another exception was thrown: Assertion failed: file:///C:/src/flutter/packages/flutter/lib/src/rendering/shifted_box.dart:348:12
Another exception was thrown: RuntimeError: unreachable
3
Another exception was thrown: Assertion failed: file:///C:/src/flutter/packages/flutter/lib/src/rendering/box.dart:1966:12
Another exception was thrown: RuntimeError: unreachable 
``` 

These are the codes : 

``` 
// ignore_for_file: prefer_const_literals_to_create_immutables, prefer_const_constructors, unused_import

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: FacebookApp(),
    );
  }
}

class FacebookApp extends StatelessWidget {
  const FacebookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("facebook",
            style: TextStyle(
                color: Colors.blueAccent,
                fontSize: 27,
                fontWeight: FontWeight.w700)),
        centerTitle: true,
        leading: IconButton(
          icon: Icon(
            Icons.menu,
            color: Colors.blueAccent,
            size: 30,
          ),
          onPressed: () {},
        ),
        actions: [
          IconButton(
              icon: Icon(
                Icons.message,
                color: Colors.blueAccent,
                size: 30,
              ),
              onPressed: () {}),
          IconButton(
            icon: Icon(
              Icons.search,
              color: Colors.blueAccent,
              size: 30,
            ),
            onPressed: () {},
          ),
        ],
        backgroundColor: Colors.white,
        elevation: 20,
      ),
    );
  }
} 
```

**Comment by exaby73** [comment]
Could you post the complete output of `flutter doctor -v`? If it's too large, you can upload it as a txt file or use a service like pastebin.com

**Comment by MUGDAD-78** [comment]
@exaby73 

``` 
C:\Windows\System32> flutter doctor -v
[√] Flutter (Channel master, 3.9.0-18.0.pre.7, on Microsoft Windows [Version 10.0.22621.1413], locale en-US)
    • Flutter version 3.9.0-18.0.pre.7 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1fb2158e36 (8 days ago), 2023-03-26 20:10:23 +0900
    • Engine revision 685fbc6f4d
    • Dart version 3.0.0 (build 3.0.0-366.0.dev)
    • DevTools version 2.22.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\megda\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.2
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8617.8

[√] VS Code (version 1.77.0)
    • VS Code at C:\Users\megda\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.62

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

C:\Windows\System32>jj

```

**Comment by exaby73** [comment]
Sorry my mistake. I need the output of `flutter run -v`

**Comment by MUGDAD-78** [comment]
@exaby73  

```
C:\Windows\System32> flutter run -v
[   +4 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1fb2158e3672a4b4e58d8bd883134aa931e07090
[        ] executing: [C:\src\flutter/] git tag --points-at 1fb2158e3672a4b4e58d8bd883134aa931e07090
[  +87 ms] Exit code 0 from: git tag --points-at 1fb2158e3672a4b4e58d8bd883134aa931e07090
[   +1 ms] executing: [C:\src\flutter/] git describe --match *.*.* --long --tags
1fb2158e3672a4b4e58d8bd883134aa931e07090
[  +80 ms] Exit code 0 from: git describe --match *.*.* --long --tags 1fb2158e3672a4b4e58d8bd883134aa931e07090
[        ] 3.9.0-17.0.pre-7-g1fb2158e36
[   +3 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +34 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/master
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +51 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +101 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +79 ms] executing: C:\Users\megda\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[+2189 ms] List of devices attached


                    * daemon not running; starting now at tcp:5037
                    * daemon started successfully
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] "flutter run" took 2,373ms.
[  +26 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1600:9)
           #2      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:516:19)
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1482:11)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1313:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +271 ms] ensureAnalyticsSent: 264ms
[   +1 ms] Running 0 shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1

```

**Comment by MUGDAD-78** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/129184865/229714195-951d5677-f780-42f3-81e3-8963c1397ed0.png)
@exaby73 

I notised that there is an error.

**Comment by exaby73** [comment]
You are running the command in your `System32` folder. You need to `cd` into your project folder first

**Comment by MUGDAD-78** [comment]
@exaby73 Can you show me how to run it in my project please?

**Comment by exaby73** [comment]
If you are using any Editor / IDE like VSCode or Android Studio, you can either run the project directly from the UI there, or use the integrated terminal provided. See https://docs.flutter.dev/get-started/test-drive for more details
