### ISSUE TITLE
Can't run app in Chrome

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#124133]
Running an app in Chrome using the main channel (Flutter 3.9.0-22.0.pre.6) results in an error:

```
Rejecting promise with error: Expected a value of type
'FontCollectionNamespace', but got one of type 'Null'
_js_helper.TypeErrorImpl.new
```

## Steps to reproduce:
1. `flutter channel main`
2. `flutter upgrade`
3. `flutter create app` 
4. `cd app`
5. `flutter run -d chrome`
6. Observe error

**Comment by yjbanov** [comment]
I feel like this should be either P0 or closed. I'll remove the P4 so it shows up at the triage.

**Comment by huycozy** [comment]
I also can reproduce this issue on Chrome but it's only happening on Windows and Linux host machines. On Chrome (MacOS), it doesn't occur.

### Additional reports
- It can boot up the Chrome window but only display a white screen
- The issue can reproduce on a newly created project.
- There is an error in the Chrome console output

<details>
<summary>Chrome console output</summary>

```bash
caught (in promise) _js_helper.TypeErrorImpl.newSymbol(_jsError): Error: Expected a value of type 'FontCollectionNamespace', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:50131/dart_sdk.js:5457:11)
    at Object.castError (http://localhost:50131/dart_sdk.js:5416:15)
    at dart.StaticInteropType.new.as (http://localhost:50131/dart_sdk.js:7331:40)
    at Object.getProperty (http://localhost:50131/dart_sdk.js:63162:14)
    at Object.CanvasKitExtension$124get$35FontCollection [as CanvasKitExtension|get#FontCollection] (http://localhost:50131/dart_sdk.js:196212:20)
    at [_registerWithFontProvider] (http://localhost:50131/dart_sdk.js:148308:128)
    at _engine.SkiaFontCollection.new.registerDownloadedFonts (http://localhost:50131/dart_sdk.js:148390:38)
    at initializeEngineServices (http://localhost:50131/dart_sdk.js:206708:39)
    at initializeEngineServices.next (<anonymous>)
    at http://localhost:50131/dart_sdk.js:41023:33
    at _RootZone.runUnary (http://localhost:50131/dart_sdk.js:40856:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50131/dart_sdk.js:36059:29)
    at handleValueCallback (http://localhost:50131/dart_sdk.js:36630:49)
    at _Future._propagateToListeners (http://localhost:50131/dart_sdk.js:36668:17)
    at [_completeWithValue] (http://localhost:50131/dart_sdk.js:36503:23)
    at http://localhost:50131/dart_sdk.js:35700:46
    at _RootZone.runUnary (http://localhost:50131/dart_sdk.js:40856:59)
    at _FutureListener.then.handleValue (http://localhost:50131/dart_sdk.js:36059:29)
    at handleValueCallback (http://localhost:50131/dart_sdk.js:36630:49)
    at _Future._propagateToListeners (http://localhost:50131/dart_sdk.js:36668:17)
    at [_completeWithValue] (http://localhost:50131/dart_sdk.js:36503:23)
    at http://localhost:50131/dart_sdk.js:35700:46
    at _RootZone.runUnary (http://localhost:50131/dart_sdk.js:40856:59)
    at _FutureListener.then.handleValue (http://localhost:50131/dart_sdk.js:36059:29)
    at handleValueCallback (http://localhost:50131/dart_sdk.js:36630:49)
    at _Future._propagateToListeners (http://localhost:50131/dart_sdk.js:36668:17)
    at [_completeWithValue] (http://localhost:50131/dart_sdk.js:36503:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50131/dart_sdk.js:36537:35)
    at Object._microtaskLoop (http://localhost:50131/dart_sdk.js:41166:13)
    at _startMicrotaskLoop (http://localhost:50131/dart_sdk.js:41172:13)
    at http://localhost:50131/dart_sdk.js:36893:9Symbol(_message): "Expected a value of type 'FontCollectionNamespace', but got one of type 'Null'"hashCode: (...)runtimeType: (...)stackTrace: (...)Symbol(dartx.hashCode): (...)Symbol(dartx.runtimeType): (...)Symbol(dartx.stackTrace): (...)[[Prototype]]: Error
Promise.then (async)
onEntrypointLoaded @ (index):51
didCreateEngineInitializer @ flutter.js:278
FlutterLoaderExtension$124didCreateEngineInitializer @ js_loader.dart:27
webOnlyWarmupEngine @ initialization.dart:90
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
webOnlyWarmupEngine @ initialization.dart:63
main @ web_entrypoint.dart:19
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
main$ @ web_entrypoint.dart:18
(anonymous) @ main_module.bootstrap.js:23
window.$dartRunMain @ main_module.bootstrap.js:22
(anonymous) @ unknown
runMain @ client.js:8972
(anonymous) @ client.js:24815
(anonymous) @ client.js:3575
call$2 @ client.js:11675
_asyncStartSync @ client.js:3539
$call$body$main__closure @ client.js:24828
call$1 @ client.js:24754
_rootRunUnary @ client.js:3939
runUnary$2$2 @ client.js:13074
runUnaryGuarded$1$2 @ client.js:13021
_sendData$1 @ client.js:12614
_add$1 @ client.js:12560
_add$1 @ client.js:12895
_handleData$2 @ client.js:12958
_handleData$1 @ client.js:12921
(anonymous) @ client.js:1339
_rootRunUnary @ client.js:3939
runUnary$2$2 @ client.js:13074
runUnaryGuarded$1$2 @ client.js:13021
_sendData$1 @ client.js:12614
_add$1 @ client.js:12560
_sendData$1 @ client.js:12405
add$1 @ client.js:12284
(anonymous) @ client.js:1397
_rootRunUnary @ client.js:3939
runUnary$2$2 @ client.js:13074
runUnaryGuarded$1$2 @ client.js:13021
_sendData$1 @ client.js:12614
_add$1 @ client.js:12560
_sendData$1 @ client.js:12405
add$1 @ client.js:12284
add$1 @ client.js:24248
call$1 @ client.js:24540
call$1 @ client.js:18036
_rootRunUnary @ client.js:3943
runUnary$2$2 @ client.js:13074
runUnaryGuarded$1$2 @ client.js:13021
call$1 @ client.js:13211
invokeClosure @ client.js:1229
(anonymous) @ client.js:1248
```
</details>

### Platforms
- Chrome Windows - since `3.9.0-20.0.pre.111`: ❌
- Chrome Linux (Ubuntu) - since `3.9.0-20.0.pre.92` : ❌
- Chrome MacOS - `3.9.0-22.0.pre.25`: ✅

✅: No Issue ❌: Issue reproduced

<details>
<summary>flutter doctor -v (Windows)</summary>

```bash
[!] Flutter (Channel master, 3.9.0-20.0.pre.111, on Microsoft Windows [Version 10.0.19045.2728], locale en-US)
    • Flutter version 3.9.0-20.0.pre.111 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current Flutter
      SDK checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK
      checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f076b7bac3 (22 minutes ago), 2023-04-04 00:58:34 -0400
    • Engine revision b5d2c056a0
    • Dart version 3.0.0 (build 3.0.0-403.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment]
See https://github.com/flutter/flutter/issues/123737

**Comment by Myratec** [comment]
Had same Problem. Updating to 3.10.0-6.0.pre.29 fixed it too.
