### ISSUE TITLE
Flutter test --coverage hangs with a segmentation fault (dart version 2.18.4)

### ISSUE THREAD

**Issue by alejovillegas7** [flutter/flutter#124145]
Hello flutter team! Im trying to run the 800 tests that I have on my application and generate a coverage report about them, but Im getting the following err 

```
Shell subprocess crashed with segmentation fault.
#0      FlutterTesterTestDevice.finished
(package:flutter_tools/src/test/flutter_tester_device.dart:241:73)
<asynchronous suspension>
#1      Future.any.onValue (dart:async/future.dart:612:5)
<asynchronous suspension>


unhandled error during finalization of test:
TestDeviceException(Shell subprocess crashed with segmentation fault.)
#0      FlutterTesterTestDevice.finished
(package:flutter_tools/src/test/flutter_tester_device.dart:241:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill
(package:flutter_tools/src/test/flutter_tester_device.dart:223:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure>
(package:flutter_tools/src/test/flutter_platform.dart:485:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest
(package:flutter_tools/src/test/flutter_platform.dart:538:11)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _FlutterPlatformStreamSinkWrapper.close.<anonymous closure>
(package:flutter_tools/src/test/flutter_platform.dart:648:7)
<asynchronous suspension>
```

when I try to run the tests without `--coverage`, they all pass without a problem. Seems like `--coverage` is causing something odd. 

another important info, this starts happening after upgrading to flutter 3.3.7 (was in 3.3.5), the dart version is `2.18.4` (was working fine with dart `2.18.2`).

thanks in advance!  will appreciate any clue around this.

**Comment by huycozy** [comment]
Hi @alejovillegas7 
Based on the stack trace, this looks similar to https://github.com/flutter/flutter/issues/106332. Could you share the test command and the complete stack trace if any?
Also, please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by alejovillegas7** [comment]
hey @huycozy sure! cant share the complete stack trace but the err showed in the post happens at some point and its the only one that appears there, as I said the process literally freezes and doesn't continue (unless you kill it). here is the flutter doctor diagnostic.

**Comment by eis6aer** [comment]
I can also confirm this happens from that version and still present on 3.7.9.

**Comment by eis6aer** [comment]
> Hi @alejovillegas7 Based on the stack trace, this looks similar to #106332. Could you share the test command and the complete stack trace if any? Also, please provide the output of `flutter doctor -v` as well. Thanks!

test command is `flutter test --coverage` (failing)
using `flutter test` (all test passed)

**Comment by huycozy** [comment]
@eis6aer Are you seeing this issue when running a large number of tests or just a few tests? And can you reproduce it all the time? 

@alejovillegas7 @eis6aer Also, I see there was a similar [issue](https://github.com/flutter/flutter/issues/108319) that happened with Enum class. Do your tests contain a similar one? If so, could you share the test so that I can check it?

**Comment by eis6aer** [comment]
> @eis6aer Are you seeing this issue when running a large number of tests or just a few tests? And can you reproduce it all the time?
> 
> @alejovillegas7 @eis6aer Also, I see there was a similar [issue](https://github.com/flutter/flutter/issues/108319) that happened with Enum class. Do your tests contain a similar one? If so, could you share the test so that I can check it?

Yes it happens around 510 + tests, if I remove random tests until 500 or less, everythings fine, also something worth mentioning, is that, running isolated folders even with `flutter test --coverage` process finishes successfully, this just happens when running all tests at once, with `--coverage` modifier

**Comment by eis6aer** [comment]
> @eis6aer Are you seeing this issue when running a large number of tests or just a few tests? And can you reproduce it all the time?
> 
> @alejovillegas7 @eis6aer Also, I see there was a similar [issue](https://github.com/flutter/flutter/issues/108319) that happened with Enum class. Do your tests contain a similar one? If so, could you share the test so that I can check it?

We double and triple checked that issue about enum classes, and no I dont have that scenario.

**Comment by alejovillegas7** [comment]
Hey @huycozy same as @eis6aer I just verified and no enums on my end neither. And also if I remove those tests(even the whole file) that fails at the beginning, then other tests/files starts failing for the same reason, there is no something like “this is the one that always fails”, it seems to be completely randomized

**Comment by huycozy** [comment]
Thank you for the responses. I'm not sure if it's possible to share the test sample code due to a large number of tests but it would be appreciated if you also could provide the complete stack trace (like [this](https://github.com/flutter/flutter/issues/106332#issuecomment-1163686833) if any) so that we may investigate the issue better. 

Also, could you please try on the latest master channel to see if the issue still persists or not?

**Comment by alejovillegas7** [comment]
hey @huycozy here u have a log around the issue

```
00:23 +507: /opt/qwerty/qwerty-mobile-app/test/mobile_feature/config/mobile_feature_session_test.dart: Session constructor callbacks test                                                                     
00:23 +508: /opt/qwerty/qwerty-mobile-app/test/mobile_feature/config/mobile_feature_session_test.dart: Session constructor callbacks test                                                                     [  +30 ms] <- accept
[        ] <- reset
[        ] Compiling file:///var/folders/pn/6r1gvf1s1qj40yhgr5rpgy640000gr/T/flutter_tools.DvDaVw/flutter_test_listener.kWkZ47/listener.dart took 168ms
[        ] test 94: starting test device
[        ] test 94: awaiting connection to test device
[        ] test 94: test harness socket server is running at port:52182
[        ] test 94: Starting flutter_tester process with command=[/Users/alejovillegas7/fvm/versions/3.7.5/bin/cache/artifacts/engine/darwin-x64/flutter_tester, --observatory-port=0, --enable-checked-mode, --verify-entry-points, --enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling, --non-interactive, --use-test-fonts, --disable-asset-fonts, --packages=/opt/qwerty/qwerty-mobile-app/.dart_tool/package_config.json, --flutter-assets-dir=/opt/qwerty/qwerty-mobile-app/build/unit_test_assets, /var/folders/pn/6r1gvf1s1qj40yhgr5rpgy640000gr/T/flutter_tools.DvDaVw/flutter_test_listener.kWkZ47/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE: /var/folders/pn/6r1gvf1s1qj40yhgr5rpgy640000gr/T/flutter_tools.DvDaVw/flutter_test_fonts.oDWjPG/fonts.conf, SERVER_PORT: 52182, APP_NAME: qwertymobile, UNIT_TEST_ASSETS: /opt/qwerty/qwerty-mobile-app/build/unit_test_assets}
[   +5 ms] test 94: Started flutter_tester process at pid 28179

00:23 +509: /opt/qwerty/qwerty-mobile-app/test/mobile_feature/config/mobile_feature_session_test.dart: Session constructor callbacks test                                                                     
00:23 +510: /opt/qwerty/qwerty-mobile-app/test/mobile_feature/config/mobile_feature_session_test.dart: Session constructor callbacks test                                                                     [   +6 ms] test 91: Test harness is no longer needed by test process
[        ] test 91: finished
[        ] Starting coverage collection
[        ] collecting coverage data from Flutter Tester (pid: 28163, running) for test 91 at http://127.0.0.1:52174/Od7N-PpLxyU=/...
[        ] test 91: Test process is no longer needed by test harness
[  +48 ms] Collected coverage data.
[        ] Merging coverage data...
[   +1 ms] Done merging coverage data into global coverage map.
[        ] test 90: cleaning up...
[        ] test 90: ensuring test device is terminated.
[        ] test 90: Terminating flutter_tester process
[        ] test 90: Shutting down test harness socket server
[   +2 ms] test 94: Shell: The Dart VM service is listening on http://127.0.0.1:52186/1QCCybWq0J8=/
[        ] test 94: Starting Dart Development Service
[   +2 ms] test 90: flutter_tester process at pid 28162 exited with code=-9
[        ] test 90: deleting temporary directory
[   +1 ms] test 90: finished
[        ] test 95: starting test /opt/qwerty/qwerty-mobile-app/test/mobile_feature/order_status_code_extension_test.dart
[   +1 ms] Stopping scan for flutter_test_config.dart; found project root at /opt/qwerty/qwerty-mobile-app
[        ] Compiling file:///var/folders/pn/6r1gvf1s1qj40yhgr5rpgy640000gr/T/flutter_tools.DvDaVw/flutter_test_listener.JlfqQ2/listener.dart
[   +4 ms] Found plugin qwerty at /Users/alejovillegas7/.pub-cache/git/qwerty-11e013a6ac6144fe5333188863a18bd77adc4b42/
[        ] Found plugin qwerty_sdk at /Users/alejovillegas7/.pub-cache/git/qwerty_sdk-0cc94cc30989f1055e91397365103b67b9ea257f/
[   +1 ms] Found plugin qwerty_version at /Users/alejovillegas7/.pub-cache/git/qwerty-get-version-299e4e3e9ac766b426ea8c7a67ac42904682dbff/
[        ] Found plugin qwerty_digitalkey_ui at /Users/alejovillegas7/.pub-cache/git/qwerty-mobile-digitalkey-ui-a85c23a43fe63e23b24d20dfc8ecb51bf89e4755/
[   +1 ms] Found plugin qwerty_connectivity at /Users/alejovillegas7/.pub-cache/git/qwerty_connectivity-1bd9eda1ee9b8b77e56d792ccb5c410f9bc96d09/
[        ] Found plugin qwerty_lib at /Users/alejovillegas7/.pub-cache/git/qwerty_lib-3fcc5d1b01fca8482307388287602911384f76d0/
[   +4 ms] Found plugin qwerty_new_relic at /Users/alejovillegas7/.pub-cache/git/qwerty_new_relic-33e6e02ebcf8c519dd3e57ae44cf8797c83c2ffd/
[        ] Found plugin qwerty_flutter at /Users/alejovillegas7/.pub-cache/git/qwerty_flutter-1fc12e4e69a457277d838c55462deb2238d41229/
[   +1 ms] Found plugin uni_links2 at /Users/alejovillegas7/.pub-cache/git/uni_links2-30fd6a81ac3988fed8f354833cc5271730d928c1/
[        ] Found plugin qwerty_flutter_plugin at /Users/alejovillegas7/.pub-cache/git/qwerty_flutter_plugin-88d5e8152e57a30ada423ec4cb10774b47d6441a/
[   +3 ms] Found plugin audioplayers at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/audioplayers-1.1.0/
[   +2 ms] Found plugin audioplayers_android at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/audioplayers_android-1.1.3/
[        ] Found plugin audioplayers_darwin at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/audioplayers_darwin-1.0.4/
[        ] Found plugin audioplayers_linux at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/audioplayers_linux-1.0.2/
[        ] Found plugin audioplayers_web at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/audioplayers_web-2.1.0/
[        ] Found plugin audioplayers_windows at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/audioplayers_windows-1.1.1/
[  +10 ms] Found plugin flutter_acpanalytics at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/flutter_acpanalytics-2.0.1/
[        ] Found plugin flutter_acpcqwerty at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/flutter_acpcqwerty-2.0.1/
[        ] Found plugin flutter_assurance at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/flutter_assurance-2.0.1/
[   +2 ms] Found plugin flutter_secure_storage at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/flutter_secure_storage-5.1.2/
[        ] Found plugin flutter_secure_storage_linux at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/flutter_secure_storage_linux-1.1.3/
[        ] Found plugin flutter_secure_storage_macos at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/flutter_secure_storage_macos-1.1.2/
[        ] Found plugin flutter_secure_storage_web at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/flutter_secure_storage_web-1.1.1/
[        ] Found plugin flutter_secure_storage_windows at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/flutter_secure_storage_windows-1.1.3/
[   +7 ms] Found plugin location at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/location-4.4.0/
[        ] Found plugin location_web at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/location_web-3.1.1/
[   +3 ms] Found plugin package_info_plus at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/package_info_plus-1.4.3+1/
[        ] Found plugin package_info_plus_linux at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/package_info_plus_linux-1.0.5/
[        ] Found plugin package_info_plus_macos at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/package_info_plus_macos-1.3.0/
[        ] Found plugin package_info_plus_web at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/package_info_plus_web-1.0.6/
[        ] Found plugin package_info_plus_windows at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/package_info_plus_windows-2.1.0/
[   +1 ms] Found plugin path_provider at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/path_provider-2.0.14/
[        ] Found plugin path_provider_android at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/path_provider_android-2.0.24/
[        ] Found plugin path_provider_foundation at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/path_provider_foundation-2.2.1/
[        ] Found plugin path_provider_linux at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.10/
[        ] Found plugin path_provider_windows at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/path_provider_windows-2.1.5/
[   +4 ms] Found plugin sensors at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/sensors-2.0.3/
[        ] Found plugin shared_preferences at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/shared_preferences-2.0.20/
[        ] Found plugin shared_preferences_android at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/shared_preferences_android-2.0.17/
[        ] Found plugin shared_preferences_foundation at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/shared_preferences_foundation-2.1.5/
[        ] Found plugin shared_preferences_linux at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/shared_preferences_linux-2.1.5/
[        ] Found plugin shared_preferences_web at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/shared_preferences_web-2.0.6/
[        ] Found plugin shared_preferences_windows at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/shared_preferences_windows-2.1.5/
[   +1 ms] Found plugin sqflite at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/sqflite-2.2.6/
[   +3 ms] Found plugin uni_links_web2 at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/uni_links_web2-0.1.0+2/
[        ] Found plugin url_launcher at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/url_launcher-6.1.10/
[        ] Found plugin url_launcher_android at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/url_launcher_android-6.0.26/
[        ] Found plugin url_launcher_ios at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/url_launcher_ios-6.1.3/
[        ] Found plugin url_launcher_linux at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/url_launcher_linux-3.0.4/
[        ] Found plugin url_launcher_macos at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/url_launcher_macos-3.0.4/
[        ] Found plugin url_launcher_web at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/url_launcher_web-2.0.16/
[        ] Found plugin url_launcher_windows at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/url_launcher_windows-3.0.5/
[        ] Found plugin video_player at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/video_player-2.4.9/
[        ] Found plugin video_player_android at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/video_player_android-2.4.3/
[        ] Found plugin video_player_avfoundation at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/video_player_avfoundation-2.4.2/
[        ] Found plugin video_player_web at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/video_player_web-2.0.15/
[   +1 ms] Found plugin webview_flutter at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/webview_flutter-3.0.4/
[        ] Found plugin webview_flutter_android at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/webview_flutter_android-2.10.4/
[        ] Found plugin webview_flutter_wkwebview at /Users/alejovillegas7/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-2.9.5/
[  +10 ms] <- recompile file:///var/folders/pn/6r1gvf1s1qj40yhgr5rpgy640000gr/T/flutter_tools.DvDaVw/flutter_test_listener.JlfqQ2/listener.dart 52971e51-b8f2-425a-86e7-e0ae9ff8a747
[        ] file:///var/folders/pn/6r1gvf1s1qj40yhgr5rpgy640000gr/T/flutter_tools.DvDaVw/flutter_test_listener.JlfqQ2/listener.dart
[        ] file:///opt/qwerty/qwerty-mobile-app/.dart_tool/flutter_build/dart_plugin_registrant.dart
[        ] <- 52971e51-b8f2-425a-86e7-e0ae9ff8a747
[   +1 ms] test 91: flutter_tester process at pid 28163 exited with code=-11
[        ] test 91: error caught during test; reporting to console
[        ] test 91: cleaning up...
[        ] test 91: ensuring test device is terminated.
[        ] test 91: Terminating flutter_tester process
[        ] test 91: Shutting down test harness socket server
[        ] test 91: error while cleaning up; reporting to console
[  +16 ms] test 91: deleting temporary directory
[        ] test 91: finished with out-of-band failure

00:23 +510 -1: loading /opt/qwerty/qwerty-mobile-app/test/mobile_feature/resources/repositories/mock/product_mock_repository_test.dart [E]                                                                  
  Shell subprocess crashed with segmentation fault.
  package:flutter_tools/src/test/flutter_tester_device.dart 232:73  FlutterTesterTestDevice.finished
  ===== asynchronous gap ===========================
  dart:async/future.dart 612:5                                      Future.any.onValue
  
[   +7 ms] test 92: connected to test device, now awaiting test result
[        ] test 92: Waiting for test harness or tests to finish

00:23 +510 -1: /opt/qwerty/qwerty-mobile-app/test/mobile_feature/config/mobile_feature_session_test.dart: Session constructor callbacks test                                                                  [  +54 ms] <- accept
[        ] <- reset
[        ] Compiling file:///var/folders/pn/6r1gvf1s1qj40yhgr5rpgy640000gr/T/flutter_tools.DvDaVw/flutter_test_listener.JlfqQ2/listener.dart took 165ms
[        ] test 95: starting test device
[        ] test 95: awaiting connection to test device
[        ] test 95: test harness socket server is running at port:52189
[        ] test 95: Starting flutter_tester process with command=[/Users/alejovillegas7/fvm/versions/3.7.5/bin/cache/artifacts/engine/darwin-x64/flutter_tester, --observatory-port=0, --enable-checked-mode, --verify-entry-points, --enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling, --non-interactive, --use-test-fonts, --disable-asset-fonts, --packages=/opt/qwerty/qwerty-mobile-app/.dart_tool/package_config.json, --flutter-assets-dir=/opt/qwerty/qwerty-mobile-app/build/unit_test_assets, /var/folders/pn/6r1gvf1s1qj40yhgr5rpgy640000gr/T/flutter_tools.DvDaVw/flutter_test_listener.JlfqQ2/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE: /var/folders/pn/6r1gvf1s1qj40yhgr5rpgy640000gr/T/flutter_tools.DvDaVw/flutter_test_fonts.oDWjPG/fonts.conf, SERVER_PORT: 52189, APP_NAME: qwertymobile, UNIT_TEST_ASSETS: /opt/qwerty/qwerty-mobile-app/build/unit_test_assets}
[   +5 ms] test 95: Started flutter_tester process at pid 28181
```

**Comment by alejovillegas7** [comment]
also @huycozy I tried with this flutter version
```
Flutter 3.9.0-0.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 0df8557c56 (3 weeks ago) • 2023-03-23 22:02:01 -0500
Engine • revision 1cc4b2d280
Tools • Dart 3.0.0 (build 3.0.0-290.3.beta) • DevTools 2.22.2
```

and the failure persist, same, without `--coverage `all the tests pass, after adding `--coverage`, they start failing

**Comment by huycozy** [comment]
>00:23 +510 -1: loading /opt/qwerty/qwerty-mobile-app/test/mobile_feature/resources/repositories/mock/product_mock_repository_test.dart [E]                                                                  
  Shell subprocess crashed with segmentation fault.
  package:flutter_tools/src/test/flutter_tester_device.dart 232:73  FlutterTesterTestDevice.finished
  ===== asynchronous gap ===========================
  dart:async/future.dart 612:5                                      Future.any.onValue

@alejovillegas7 Thanks. I see the issue caused by your test (`product_mock_repository_test`). Will this test cause the issue if you just run it without running all the other tests? (Just to confirm you and @eis6aer have the same case).

Also, I see you checked this on beta channel. Can you please also check this on the latest master channel? 

```
flutter channel master
flutter upgrade
```

**Comment by alejovillegas7** [comment]
hey @huycozy I tried running that file in an isolated way and it passes perfectly, also I changed my version to master channel and the same err happened, but this time more tests passed, the normal issue breaks the flow on the test number 500, after changing to master channel that number grows up until 600 

```
unhandled error during test:
Shell subprocess crashed with segmentation fault.
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:245:73)
<asynchronous suspension>
#1      Future.any.onValue (dart:async/future.dart:615:5)
<asynchronous suspension>
```

same segmentation fault.

**Comment by huycozy** [comment]
Thanks for checking on the master channel. Labeling the issue for more insights from others!

### Issue summary 
- The issue only happens when running with `--coverage` and with a large number of tests (500-600 tests)
- Reproducible on stable `3.3.7`, beta `3.9.0-0.2.pre`, and master

**Comment by alejovillegas7** [comment]
thanks a lot @huycozy any help will be appreciated

**Comment by eis6aer** [comment]
Hey guys, any news on this one??

**Comment by mraleph** [comment]
We need a reproduction to be able to diagnose this.

**Comment by huycozy** [comment]
@alejovillegas7 Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?
