### ISSUE TITLE
add verbose debugging when tool fails to download a zip on windows

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#124344]
Provide debugging for: https://github.com/flutter/flutter/issues/123519

When the tool fails to download an artifact on windows, detect and debugging:

1. print checksum of file
2. file attributes?

**Comment by christopherfujino** [comment]
Here's the stacktrace in question:

```
[2023-03-31 16:46:46.393577] [STDOUT] stderr: [   +3 ms] Flutter could not download and/or extract https://storage.googleapis.com/flutter_infra_release/flutter/a109903148725d475f0664f09cb2baaf93bfc8c8/android-arm64-release/windows-x64.zip. Ensure you have network connectivity and all of the required dependencies listed at flutter.dev/setup.
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            The original exception was: FileSystemException: Cannot open file, path = 'C:\opt\s\w\ir\x\w\recipe_cleanup\tmp80kqy73y\flutter sdk\bin\cache\downloads\storage.googleapis.com\flutter_infra_release\flutter\a109903148725d475f0664f09cb2baaf93bfc8c8\android-arm64-release\windows-x64.zip' (OS Error: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            , errno = 225).
[2023-03-31 16:46:46.393577] [STDOUT] stderr: [   +2 ms] 
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1115:11)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #2      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:908:7)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #3      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #4      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1514:7)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1331:27)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            #14     main (package:flutter_tools/executable.dart:91:3)
[2023-03-31 16:46:46.393577] [STDOUT] stderr:            <asynchronous suspension>
```

**Comment by christopherfujino** [comment]
Actually, since the OS won't let us read the file, I'm not sure there's anything we can do in this state.
