### ISSUE TITLE
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags.

### ISSUE THREAD

**Issue by reyou** [flutter/flutter#124301]
## Steps to Reproduce

1.  Create `IntegrationTest`
2.  in a `testWidgets` method place following code:

```
    testWidgets('Success', (tester) async {
    ...
    // Scroll down.
      await tester.drag(find.byType(ListView), const Offset(0, -300));
      await tester.pump();
      await Future.delayed(const Duration(seconds: 5));
    }
```

While application is waiting during `Future.delayed` if you do `ALT + TAB` in the launched window (in my case it is Windows App), following exception occurs.  
 

```

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key
event being sent doesn't properly set its modifier flags. This was the event:
RawKeyDownEvent#8fef2(logicalKey: LogicalKeyboardKey#e5ce6(keyId: "0x200000104", keyLabel: "Alt
Left", debugName: "Alt Left"), physicalKey: PhysicalKeyboardKey#f0183(usbHidUsage: "0x000700e2",
debugName: "Alt Left"), repeat: false) and its data: RawKeyEventDataWindows#2bce9(keyCode: 164,
scanCode: 56, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 683 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:683:7)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:951:30)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:214:49)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)
#10     _invoke2 (dart:ui/hooks.dart:185:10)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
```

**Expected results:**

Dont' throw this exception, or provide a way to handle gracefully.

**Actual results:**

Exception Thrown.

Code sample

```dart
 testWidgets('Success', (tester) async {
      

      app.main();
      await tester.pumpAndSettle();
     
      // Scroll down.
      await tester.drag(find.byType(ListView), const Offset(0, -300));
      await tester.pump();
      await Future.delayed(const Duration(seconds: 5));
    });
```

Logs

Supplied above.

**Comment by huycozy** [comment]
Hi @reyou 
I've tried reproducing this on Windows but the issue didn't happen on my end (even after pressing `Alt` + `Tab` several times). 

Could you provide a complete minimal sample code along with the output of `flutter doctor -v`?
