### ISSUE TITLE
[tool_crash] IndexError: RangeError (index): Index out of range: index should be less than 65496860: 70090672

### ISSUE THREAD

**Issue by mtolgae34** [flutter/flutter#124351]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
IndexError: RangeError (index): Index out of range: index should be less than 65496860: 70090672
```
#0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:4276:7)
#1      InputStream.readUint32 (package:archive/src/util/input_stream.dart:250:22)
#2      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:49:34)
#3      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
#4      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
#5      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:509:42)
#6      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1111:18)
<asynchronous suspension>
#7      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:908:7)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1377:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.19045.2728], locale en-US)
    [32m•[39m Flutter version 3.7.8 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 90c64ed42b (2 weeks ago), 2023-03-21 11:27:08 -0500
    [32m•[39m Engine revision 9aa7816315
    [32m•[39m Dart version 2.19.5
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at C:\Users\tolga.erturk\sdk
    [32m•[39m Platform android-33-ext4, build-tools 33.0.2
    [32m•[39m Java binary at: C:\sdk\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.5.0)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    [32m•[39m Visual Studio Build Tools 2022 version 17.5.33414.496
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at C:\sdk
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[32m[✓][39m VS Code (version 1.77.1)
    [32m•[39m VS Code at C:\Users\tolga.erturk\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.62.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    [32m•[39m Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    [32m•[39m Chrome (web)            • chrome        • web-javascript • Google Chrome 111.0.5563.147
    [32m•[39m Edge (web)              • edge          • web-javascript • Microsoft Edge 111.0.1661.62

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 90c64ed42ba53a52d18f0cb3b17666c8662ed2a0
### Plugins
cloud_firestore-4.5.0
cloud_firestore_web-3.4.0
firebase_auth-4.4.0
firebase_auth_web-5.3.0
firebase_core-2.9.0
firebase_core_web-2.3.0
google_sign_in-6.0.2
google_sign_in_android-6.1.8
google_sign_in_ios-5.6.1
google_sign_in_web-0.11.0+2
path_provider_linux-2.1.10
path_provider_windows-2.1.5
shared_preferences-2.1.0
shared_preferences_android-2.1.0
shared_preferences_foundation-2.2.0
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
url_launcher-6.1.10
url_launcher_android-6.0.26
url_launcher_ios-6.1.3
url_launcher_linux-3.0.4
url_launcher_macos-3.0.4
url_launcher_web-2.0.16
url_launcher_windows-3.0.5

**Comment by huycozy** [comment]
Hi @mtolgae34 
Does this issue happen on a new Flutter project? Please check this [comment](https://github.com/flutter/flutter/issues/84276#issuecomment-1110885991) if you also have a similar case.
