### ISSUE TITLE
App using 2 plugins which both contain onActivityResult throws RuntimeException

### ISSUE THREAD

**Issue by pamtbaau** [flutter/flutter#124309]
I have created an app and two different plugins, each plugin using an `onActivityResult` needed to respond to a request for permissions.

- When app imports only a single plugin, all goes well.
- When app imports both plugins, but calls the channel method of one of the plugins, both onActivityResult methods are being called, leading to a RuntimeException being thrown.

## Steps to Reproduce

- Create sample app + two plugins.
  ```
  $ flutter create --org com.mydomain --platforms android theapp
  $ flutter create --template plugin --org com.mydonain --platforms android plugin1
  $ flutter create --template plugin --org com.mydomain --platforms android plugin2
  ```
- Add to both plugins code to ask permission to access a folder
  ```
  val intent = Intent(Intent.ACTION_OPEN_DOCUMENT_TREE)
  thisActivity?.startActivityForResult(intent, REQUESTCODE_FOLDER_PERMISSION)
  ```
- **Add only Plugin1 to pubspec.yaml of App**
  ```
  plugin1:
    path: ../_plugins/plugin1
  ```
- Add call to App to call method on Plugin1: `final uriString = await Plugin1().getPermission();`
- Folderpicker is shown by Plugin1
- onActivityResult is called on Plugin1
- uriString of selected folder is returned correctly.
- **Add only Plugin2 to pubspec.yaml of App**

  ```
  plugin2:
    path: ../_plugins/plugin2
  ```
- Use call method **Plugin2**: `final uriString = await Plugin2().getPermission();`
- Folderpicker is shown by Plugin2
- onActivityResult is called on Plugin2
- uriString of selected folder is returned correctly.- 
- **Add Plugin1 + Plugin2 to pubspec.yaml of App**
  ```
  plugin1:
    path: ../_plugins/plugin1
  plugin2:
    path: ../_plugins/plugin2
  ```
- Use call method **Plugin1**: `final uriString = await Plugin1().getPermission();`
- No further changes.
- Rebuild App
- App calls method on Plugin1 again
- FolderPicker is shown
- onActivityResult is called on Plugin1
- Result is returned to App
- onActivityResult is called on Plugin2
- Runtime Exception
  ```
   E/AndroidRuntime( 4968): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, 
  data=Intent { dat=content://com.android.externalstorage.documents/... flg=0xc3 }} to activity 
  {com.mydomain.theapp/com.mydomain.theapp.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property 
  resultPlugin2 has not been initialized
  ```

**Expected results:** 
I would not expect that `onActivityResult` of Plugin2 to be called.

**Actual results:** 
The log shows that `onActivityResult` of Plugin2 is being called and a RuntimeException is thrown.

<details>
<summary>Code sample main.dart of TheApp</summary>

```dart
import 'package:flutter/material.dart';
import 'package:plugin1/plugin1.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  void initState() {
    init();

    super.initState();
  }

  Future<void> init() async {
    final uriString = await Plugin1().getPermission() ?? 'Unknown';
    print('Plugin1: $uriString');
  }

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>

<details>
  <summary>Code Plugin 1 - plugin1/android/src/main/kotlin/com/mydomain/plugin1/Plugin1Plugin.kt</summary>

```
package com.mydomain.plugin1

import androidx.annotation.NonNull

import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result

import android.annotation.SuppressLint
import android.app.Activity
import android.content.Intent
import android.content.Context
import android.content.UriPermission
import android.net.Uri
import android.os.Build
import android.util.Log
import androidx.annotation.RequiresApi
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
import io.flutter.plugin.common.PluginRegistry


/** Plugin1Plugin */
class Plugin1Plugin: FlutterPlugin, MethodCallHandler, ActivityAware,
    PluginRegistry.ActivityResultListener {
    /// The MethodChannel that will the communication between Flutter and native Android
    ///
    /// This local reference serves to register the plugin with the Flutter Engine and unregister it
    /// when the Flutter Engine is detached from the Activity

    private lateinit var channel: MethodChannel
    private lateinit var resultPlugin1: Result
    private lateinit var context: Context

    private var thisActivity: Activity? = null


    override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
      Log.e("xxx", "onAttachedToEngine: Plugin1")

      channel = MethodChannel(flutterPluginBinding.binaryMessenger, "plugin1")
      channel.setMethodCallHandler(this)

      context = flutterPluginBinding.applicationContext
    }

    override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: Result) {
      Log.e("xxx", "onMethodCall: Plugin1")

      resultPlugin1 = result
      
      if (call.method == "getPlatformVersion") {
        result.success("Android ${android.os.Build.VERSION.RELEASE}")
      } else if (call.method == "getPermission") {
        getPermission()
      } else {
        result.notImplemented()
      }
    }

    override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
      Log.e("xxx", "onDetachedFromEngine: Plugin1")

      channel.setMethodCallHandler(null)
    }

    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        Log.e("xxx", "onAttachedToActivity: Plugin1")

        thisActivity = binding.activity;
        binding.addActivityResultListener(this)
    }

    override fun onDetachedFromActivityForConfigChanges() {
      Log.e("xxx", "onDetachedFromActivityForConfigChanges: Plugin1")

      thisActivity = null
    }

    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
        Log.e("xxx", "onReattachedToActivityForConfigChanges: Plugin1")

        thisActivity = binding.activity
        binding.addActivityResultListener(this)
    }

    override fun onDetachedFromActivity() {
        Log.e("xxx", "onDetachedFromActivity: Plugin1")

        thisActivity = null
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, result: Intent?): Boolean {
        Log.e("xxx", "onActivityResult: Plugin1")

        if (requestCode == REQUESTCODE_FOLDER_PERMISSION) {
            if (resultCode == Activity.RESULT_OK) {
                val backupFolderUri = result?.data ?: throw IllegalArgumentException(
                    "No valid value returned by permission activity"
                )

                val takeFlags: Int = result.flags and
                        (Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
                thisActivity!!.contentResolver.takePersistableUriPermission(
                    backupFolderUri,
                    takeFlags
                )

                resultPlugin1.success(backupFolderUri.toString())
            } else {
                resultPlugin1.success(null)
            }

            return true
        }

        return false
    }

    @RequiresApi(Build.VERSION_CODES.LOLLIPOP)
    private fun getPermission() {
        val intent = Intent(Intent.ACTION_OPEN_DOCUMENT_TREE)
        thisActivity?.startActivityForResult(intent, REQUESTCODE_FOLDER_PERMISSION)
    }

    companion object {
        private const val REQUESTCODE_FOLDER_PERMISSION = 0
        private const val REQUESTCODE_FILE_PERMISSION = 1
    }
}
```
</details>

<details>
  <summary>Code Plugin 2 - plugin2/android/src/main/kotlin/com/mydomain/plugin2/Plugin2Plugin.kt</summary>

```
See Plugin 1, except references to Plugin1 are now references to Plugin2
```
</details>

<details>
  <summary>Logs</summary>

Had to remove Log of flutter run --verbose due to its length. The following is log form VSCode output.

```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:63157/p1mM2riV5ls=/ws
E/xxx     ( 8232): onMethodCall: Plugin1
D/CompatibilityChangeReporter( 8232): Compat change id reported: 78294732; UID 10162; state: ENABLED
E/xxx     ( 8232): onActivityResult: Plugin1
E/xxx     ( 8232): onActivityResult: Plugin2
D/AndroidRuntime( 8232): Shutting down VM
I/flutter ( 8232): Plugin1: content://com.android.externalstorage.documents/tree/13F3-341F%3AMapsforge
E/AndroidRuntime( 8232): FATAL EXCEPTION: main
E/AndroidRuntime( 8232): Process: com.mydomain.theapp, PID: 8232
E/AndroidRuntime( 8232): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/... flg=0xc3 }} to activity {com.mydomain.theapp/com.mydomain.theapp.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property resultPlugin2 has not been initialized
E/AndroidRuntime( 8232): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5323)
E/AndroidRuntime( 8232): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5362)
E/AndroidRuntime( 8232): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime( 8232): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 8232): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 8232): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 8232): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/AndroidRuntime( 8232): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8232): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 8232): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 8232): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 8232): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8232): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 8232): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 8232): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property resultPlugin2 has not been initialized
E/AndroidRuntime( 8232): 	at com.mydomain.plugin2.Plugin2Plugin.onActivityResult(Plugin2Plugin.kt:111)
E/AndroidRuntime( 8232): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
E/AndroidRuntime( 8232): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
E/AndroidRuntime( 8232): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
E/AndroidRuntime( 8232): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
E/AndroidRuntime( 8232): 	at android.app.Activity.dispatchActivityResult(Activity.java:8628)
E/AndroidRuntime( 8232): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5316)
E/AndroidRuntime( 8232): 	... 13 more
I/Process ( 8232): Sending signal. PID: 8232 SIG: 9
Lost connection to device.
Exited (sigterm)
```
</details>

<details>
  <summary>flutter analyze</summary>

```
Analyzing theapp...                                             

   info - Don't invoke 'print' in production code - lib\main.dart:63:5 - avoid_print
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[Γ£ô] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.22621.1485], locale en-NL)
    ΓÇó Flutter version 3.7.8 on channel stable at C:\DevTools\flutter
    ΓÇó Upstream repository https://github.com/flutter/flutter.git
    ΓÇó Framework revision 90c64ed42b (2 weeks ago), 2023-03-21 11:27:08 -0500
    ΓÇó Engine revision 9aa7816315
    ΓÇó Dart version 2.19.5
    ΓÇó DevTools version 2.20.1

[Γ£ô] Windows Version (Installed version of Windows is version 10 or higher)

[Γ£ô] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ΓÇó Android SDK at C:\Users\Xyz\AppData\Local\Android\Sdk
    ΓÇó Platform android-33, build-tools 33.0.0
    ΓÇó ANDROID_SDK_ROOT = C:\Users\Xyz\AppData\Local\Android\Sdk
    ΓÇó Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ΓÇó All Android licenses accepted.

[Γ£ô] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    ΓÇó Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    ΓÇó Visual Studio Community 2022 version 17.4.33213.308
    ΓÇó Windows 10 SDK version 10.0.22000.0

[Γ£ô] Android Studio (version 2022.1)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    ΓÇó Flutter plugin can be installed from:
      ≡ƒö¿ https://plugins.jetbrains.com/plugin/9212-flutter
    ΓÇó Dart plugin can be installed from:
      ≡ƒö¿ https://plugins.jetbrains.com/plugin/6351-dart
    ΓÇó Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[Γ£ô] VS Code (version 1.77.1)
    ΓÇó VS Code at C:\Users\Xyz\AppData\Local\Programs\Microsoft VS Code
    ΓÇó Flutter extension version 3.62.0

[Γ£ô] Connected device (2 available)
    ΓÇó sdk gphone64 x86 64 (mobile) ΓÇó emulator-5554 ΓÇó android-x64 ΓÇó Android 13 (API 33) (emulator)
    ΓÇó Windows (desktop)            ΓÇó windows       ΓÇó windows-x64 ΓÇó Microsoft Windows [Version 10.0.22621.1485]

[Γ£ô] HTTP Host Availability
    ΓÇó All required HTTP hosts are available

ΓÇó No issues found!
```
</details>

**Comment by huycozy** [comment]
Thanks for the detailed issue, @pamtbaau 
Could you please push the sample code to a GitHub repository so that I can pull and try running it?

**Comment by pamtbaau** [comment]
Here you go: https://github.com/pamtbaau/plugins_test/

**Comment by stuartmorgan** [comment]
> I would not expect that `onActivityResult` of Plugin2 to be called.

This expectation is not correct; all plugins that handle activity results are provided the opportunity to respond.

> both onActivityResult methods are being called, leading to a RuntimeException being thrown.

This is true, but only because the plugins' `onActivityResult` implementations are problematic. Each assumes that if the application receives an activity result with the request code "0", it must have been the source of that request, and that no other code in the application could have issued such a request. The test case you've created here shows why this is not a safe assumption.

Plugins should:
- use request codes that are expected to be unique across the application (e.g., by randomly generating an arbitrary integer to use as your constant, instead of picking values like 0 and 1), and/or
- expect that other code could be the source of the request, since as a plugin it's a given that you don't control all the code in the application, and thus have extra tracking to know whether or not the request came from your code (e.g., by making `resultPlugin1` non-null only during a request, and checking it rather than assuming it's non-null).

There is no way Flutter itself can resolve the problem created by plugins like the sample above that assume no other code could issue requests. If the engine allowed only the first plugin that returned true to handle it, the behavior would not be that both plugins worked, it would be that calling one of the plugins, arbitrarily, would always work, and the other would always crash.

Closing as this is a bug in the plugins, not in Flutter.

**Comment by pamtbaau** [comment]
@stuartmorgan, Thanks, interesting new information I wasn't aware of... Will test.

**Comment by stuartmorgan** [comment]
> when only a single channel is being called.

There is no channel involved in intent/activity handling; it's entirely native code. You are sending an intent (without involving Flutter code at all), which is handled by the OS, and then the app receives a response.

I'm not sure how you are expecting Flutter to call only a specific plugin instance with the response when it has no knowledge of the request being made.
