### ISSUE TITLE
[iOS] - app not running on simulator 

### ISSUE THREAD

**Issue by kkh975** [flutter/flutter#124442]
## Steps to Reproduce

1.flutter create foo --platforms ios,android 
2. cd foo 
3. flutter run

**Env:**
- Mac M1 Pro 
- ios Simulator: iphone14 pro (ios 16.4)
- flutter version 3.7.10

<details>
<summary>Code sample</summary>

```dart
Creating project bug...
Running "flutter pub get" in bug...
Resolving dependencies in bug... (1.3s)
+ async 2.10.0 (2.11.0 available)
+ boolean_selector 2.1.1
+ characters 1.2.1 (1.3.0 available)
+ clock 1.1.1
+ collection 1.17.0 (1.17.1 available)
+ cupertino_icons 1.0.5
+ fake_async 1.3.1
+ flutter 0.0.0 from sdk flutter
+ flutter_lints 2.0.1
+ flutter_test 0.0.0 from sdk flutter
+ js 0.6.5 (0.6.7 available)
+ lints 2.0.1
+ matcher 0.12.13 (0.12.15 available)
+ material_color_utilities 0.2.0 (0.3.0 available)
+ meta 1.8.0 (1.9.1 available)
+ path 1.8.2 (1.8.3 available)
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.9.1 (1.10.0 available)
+ stack_trace 1.11.0
+ stream_channel 2.1.1
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ test_api 0.4.16 (0.5.1 available)
+ vector_math 2.1.4
Changed 24 dependencies in bug!
Wrote 127 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd bug
  $ flutter run

Your application code is in bug/lib/main.dart.
```

</details>

<details>
  <summary>Logs</summary>

```
[        ] Xcode build done.                                            3.3s
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun xcresulttool get --path
/var/folders/k9/3kpzjsgj0j128198fg7_ypfm0000gn/T/flutter_tools.68RX0H/flutter_ios_build_temp_dirsbjtHk/temporary_xcresult_
bundle --format json
[  +53 ms] {
             "_type" : {
               "_name" : "ActionsInvocationRecord"
             },
             "actions" : {
               "_type" : {
                 "_name" : "Array"
               },
               "_values" : [
                 {
                   "_type" : {
                     "_name" : "ActionRecord"
                   },
                   "actionResult" : {
                     "_type" : {
                       "_name" : "ActionResult"
                     },
                     "coverage" : {
                       "_type" : {
                         "_name" : "CodeCoverageInfo"
                       }
                     },
                     "issues" : {
                       "_type" : {
                         "_name" : "ResultIssueSummaries"
                       }
                     },
                     "metrics" : {
                       "_type" : {
                         "_name" : "ResultMetrics"
                       }
                     },
                     "resultName" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "action"
                     },
                     "status" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "notRequested"
                     }
                   },
                   "buildResult" : {
                     "_type" : {
                       "_name" : "ActionResult"
                     },
                     "coverage" : {
                       "_type" : {
                         "_name" : "CodeCoverageInfo"
                       }
                     },
                     "issues" : {
                       "_type" : {
                         "_name" : "ResultIssueSummaries"
                       },
                       "errorSummaries" : {
                         "_type" : {
                           "_name" : "Array"
                         },
                         "_values" : [
                           {
                             "_type" : {
                               "_name" : "IssueSummary"
                             },
                             "issueType" : {
                               "_type" : {
                                 "_name" : "String"
                               },
                               "_value" : "Error"
                             },
                             "message" : {
                               "_type" : {
                                 "_name" : "String"
                               },
                               "_value" : "Unknown option: -Xlinker"
                             }
                           }
                         ]
                       }
                     },
                     "logRef" : {
                       "_type" : {
                         "_name" : "Reference"
                       },
                       "id" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "0~okbjBPyArz_FlR68zSc_f8kYc7KwoXaxT597CuBBbNY1vmtAC9CaG9PrH76LOdjLhCXm5aV8kc3EzDKM7f2HNQ=="
                       },
                       "targetType" : {
                         "_type" : {
                           "_name" : "TypeDefinition"
                         },
                         "name" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "ActivityLogSection"
                         }
                       }
                     },
                     "metrics" : {
                       "_type" : {
                         "_name" : "ResultMetrics"
                       },
                       "errorCount" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "1"
                       }
                     },
                     "resultName" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "build"
                     },
                     "status" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "failed"
                     }
                   },
                   "endedTime" : {
                     "_type" : {
                       "_name" : "Date"
                     },
                     "_value" : "2023-04-08T18:37:53.506+0900"
                   },
                   "runDestination" : {
                     "_type" : {
                       "_name" : "ActionRunDestinationRecord"
                     },
                     "displayName" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "iPhone 14 Pro"
                     },
                     "localComputerRecord" : {
                       "_type" : {
                         "_name" : "ActionDeviceRecord"
                       },
                       "busSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "cpuCount" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "1"
                       },
                       "cpuKind" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "Apple M1 Pro"
                       },
                       "cpuSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "identifier" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "00006000-001C39D23432801E"
                       },
                       "isConcreteDevice" : {
                         "_type" : {
                           "_name" : "Bool"
                         },
                         "_value" : "true"
                       },
                       "logicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "10"
                       },
                       "modelCode" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "MacBookPro18,1"
                       },
                       "modelName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "MacBook Pro"
                       },
                       "modelUTI" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "com.apple.macbookpro-16-2021"
                       },
                       "name" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "My Mac"
                       },
                       "nativeArchitecture" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "arm64e"
                       },
                       "operatingSystemVersion" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "13.2.1"
                       },
                       "operatingSystemVersionWithBuildNumber" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "13.2.1 (22D68)"
                       },
                       "physicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "10"
                       },
                       "platformRecord" : {
                         "_type" : {
                           "_name" : "ActionPlatformRecord"
                         },
                         "identifier" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "com.apple.platform.macosx"
                         },
                         "userDescription" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "macOS"
                         }
                       },
                       "ramSizeInMegabytes" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "32768"
                       }
                     },
                     "targetArchitecture" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "arm64"
                     },
                     "targetDeviceRecord" : {
                       "_type" : {
                         "_name" : "ActionDeviceRecord"
                       },
                       "busSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "cpuCount" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "cpuSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "identifier" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "AF722A56-86BA-45D8-9E7E-4E3DC9F469CA"
                       },
                       "isConcreteDevice" : {
                         "_type" : {
                           "_name" : "Bool"
                         },
                         "_value" : "true"
                       },
                       "logicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "modelCode" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iPhone15,2"
                       },
                       "modelName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iPhone 14 Pro"
                       },
                       "modelUTI" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "com.apple.iphone-14-pro-1"
                       },
                       "name" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iPhone 14 Pro"
                       },
                       "nativeArchitecture" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "arm64"
                       },
                       "operatingSystemVersion" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "16.4"
                       },
                       "operatingSystemVersionWithBuildNumber" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "16.4 (20E247)"
                       },
                       "physicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "platformRecord" : {
                         "_type" : {
                           "_name" : "ActionPlatformRecord"
                         },
                         "identifier" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "com.apple.platform.iphonesimulator"
                         },
                         "userDescription" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "iOS Simulator"
                         }
                       },
                       "ramSizeInMegabytes" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       }
                     },
                     "targetSDKRecord" : {
                       "_type" : {
                         "_name" : "ActionSDKRecord"
                       },
                       "identifier" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iphonesimulator16.4"
                       },
                       "name" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "Simulator - iOS 16.4"
                       },
                       "operatingSystemVersion" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "16.4"
                       }
                     }
                   },
                   "schemeCommandName" : {
                     "_type" : {
                       "_name" : "String"
                     },
                     "_value" : "Run"
                   },
                   "schemeTaskName" : {
                     "_type" : {
                       "_name" : "String"
                     },
                     "_value" : "Build"
                   },
                   "startedTime" : {
                     "_type" : {
                       "_name" : "Date"
                     },
                     "_value" : "2023-04-08T18:37:50.883+0900"
                   },
                   "title" : {
                     "_type" : {
                       "_name" : "String"
                     },
                     "_value" : "Build \"Runner\""
                   }
                 }
               ]
             },
             "issues" : {
               "_type" : {
                 "_name" : "ResultIssueSummaries"
               },
               "errorSummaries" : {
                 "_type" : {
                   "_name" : "Array"
                 },
                 "_values" : [
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Error"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Unknown option: -Xlinker"
                     }
                   }
                 ]
               }
             },
             "metadataRef" : {
               "_type" : {
                 "_name" : "Reference"
               },
               "id" : {
                 "_type" : {
                   "_name" : "String"
                 },
                 "_value" : "0~_mXPmpul8iWyj43-oMVe86d8Bo_ifmzBZfeGUHwKcPwburCTmNvxTGwF7iMmRUO8_Cd8amcfK2WB8-kR843nZQ=="
               },
               "targetType" : {
                 "_type" : {
                   "_name" : "TypeDefinition"
                 },
                 "name" : {
                   "_type" : {
                     "_name" : "String"
                   },
                   "_value" : "ActionsInvocationMetadata"
                 }
               }
             },
             "metrics" : {
               "_type" : {
                 "_name" : "ResultMetrics"
               },
               "errorCount" : {
                 "_type" : {
                   "_name" : "Int"
                 },
                 "_value" : "1"
               }
             }
           }
[   +4 ms] Failed to build iOS app
[        ] Error (Xcode): Unknown option: -Xlinker

[   +2 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14 Pro.
[   +1 ms] "flutter run" took 15,414ms.
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:722:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +77 ms] ensureAnalyticsSent: 76ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```
Analyzing bluring_fe_temp_start...
No issues found! (ran in 1.8s)
```

```
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-arm64, locale ko-KR)
    • Flutter version 3.7.10 on channel stable at /Users/user/Documents/app/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (4일 전), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/user/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/user/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.2.1
    • Dart plugin version 211.7817

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • iPhone 14 (mobile)     • 072523CD-B545-492B-A63A-B8AE514D2EC7 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro (mobile) • AF722A56-86BA-45D8-9E7E-4E3DC9F469CA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
@kkh975 Could you try switching to the latest master channel to see if the issue still persists or not? Also, please also try running iOS project from XCode as well. Thanks!

**Comment by kkh975** [comment]
@huycozy xcode is working. but cannot run with cmd `flutter run`.
stable / master also same.

**Comment by huycozy** [comment]
Can you please share the `Podfile` content?

**Comment by kkh975** [comment]
@huycozy 

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '16.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

**Comment by huycozy** [comment]
It's normal as I can see. Can you please compress the sample project and share it here? I guess it is caused by code signing in the project Build Settings. You may also check [this](https://stackoverflow.com/questions/19693769/xcode5-simulator-unknown-option-character-x-in-xlinker) if it helps.

**Comment by kkh975** [comment]
Sample App:
[sample.zip](https://github.com/flutter/flutter/files/11353911/sample.zip)

Result:
![스크린샷 2023-04-28 오후 10 28 42](https://user-images.githubusercontent.com/1680132/235160564-88cca64f-f22f-4845-ad7b-c23aee7013a2.png)

**Comment by huycozy** [comment]
I try your sample code above but it can run well without issue. It looks strange. The issue may come from XCode as the error message.
<details>
<summary>Demo</summary>

<img width="1438" alt="Screenshot 2023-04-29 at 11 01 58" src="https://user-images.githubusercontent.com/104349824/235282592-30153555-893c-4312-99cf-624419d10c72.png">
</details>

Can you please check if the issue always happens on a new Flutter project? And please also help to check if it occurs on the latest stable and master channels as well. Thank you!

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.12 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.10.0-16.0.pre.23, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0-16.0.pre.23 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 55c988fb45 (3 hours ago), 2023-04-27 20:32:55 -0400
    • Engine revision 1d25906b4c
    • Dart version 3.1.0 (build 3.1.0-49.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Flamingo.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio Flamingo.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by kkh975** [comment]
Thanks. Thah't wired.
I tried to reinstall xcode and flutter. But It didn't work.
So I tried to run sample app on the other mac book. It worked!
I have no idea what difference between them.

**Comment by darshankawar** [comment]
@kkh975 
From above details, it seems it works on intel chip but not on M1 chip, so see the installation guide on mac and see if it is related to rosetta to check if it helps in your case or not: https://docs.flutter.dev/get-started/install/macos#system-requirements
