### ISSUE TITLE
Project creation fails with self-dependency error

### ISSUE THREAD

**Issue by wichert** [flutter/flutter#12445]
## Steps to Reproduce

I followed the [installation instructions](https://flutter.io/setup-macos/#system-requirements) to install flutter on macOs. `flutter doctor` shows everything to be ok.

Next I tried to create a new project. This failed:

```
$ flutter -v create flutter_test
[  +12 ms] [/Users/wichert/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[        ] [/Users/wichert/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] ssh://git@github.com/flutter/flutter.git
[        ] [/Users/wichert/flutter/] git log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 701d534ba93eaa3452f5e6b8b73ad8bd5a48847b
[        ] [/Users/wichert/flutter/] git log -n 1 --pretty=format:%ar
[   +8 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 weeks ago
[ +158 ms] Creating project flutter_test...
[  +14 ms]   flutter_test/ios/Runner.xcworkspace/contents.xcworkspacedata (existing - skipped)
[        ]   flutter_test/ios/Runner/Info.plist (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (existing - skipped)
[        ]   flutter_test/ios/Runner/Base.lproj/LaunchScreen.storyboard (existing - skipped)
[        ]   flutter_test/ios/Runner/Base.lproj/Main.storyboard (existing - skipped)
[        ]   flutter_test/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (existing - skipped)
[        ]   flutter_test/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (existing - skipped)
[        ]   flutter_test/ios/Flutter/Debug.xcconfig (existing - skipped)
[        ]   flutter_test/ios/Flutter/Release.xcconfig (existing - skipped)
[   +1 ms]   flutter_test/ios/Flutter/AppFrameworkInfo.plist (existing - skipped)
[        ]   flutter_test/ios/.gitignore (existing - skipped)
[        ]   flutter_test/test/widget_test.dart (existing - skipped)
[        ]   flutter_test/flutter_test.iml (existing - skipped)
[        ]   flutter_test/.gitignore (existing - skipped)
[        ]   flutter_test/ios/Runner/AppDelegate.h (existing - skipped)
[        ]   flutter_test/ios/Runner/main.m (existing - skipped)
[        ]   flutter_test/ios/Runner/AppDelegate.m (existing - skipped)
[        ]   flutter_test/ios/Runner.xcodeproj/project.pbxproj (existing - skipped)
[        ]   flutter_test/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (existing - skipped)
[        ]   flutter_test/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (existing - skipped)
[        ]   flutter_test/android/app/src/main/res/drawable/launch_background.xml (existing - skipped)
[        ]   flutter_test/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (existing - skipped)
[        ]   flutter_test/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (existing - skipped)
[        ]   flutter_test/android/app/src/main/res/values/styles.xml (existing - skipped)
[        ]   flutter_test/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (existing - skipped)
[        ]   flutter_test/android/app/src/main/AndroidManifest.xml (existing - skipped)
[        ]   flutter_test/android/gradle/wrapper/gradle-wrapper.properties (existing - skipped)
[        ]   flutter_test/android/.gitignore (existing - skipped)
[        ]   flutter_test/android/gradle.properties (existing - skipped)
[        ]   flutter_test/android/settings.gradle (existing - skipped)
[        ]   flutter_test/pubspec.yaml (existing - skipped)
[        ]   flutter_test/README.md (existing - skipped)
[        ]   flutter_test/lib/main.dart (existing - skipped)
[        ]   flutter_test/android/app/build.gradle (existing - skipped)
[        ]   flutter_test/android/app/src/main/java/com/yourcompany/fluttertest/MainActivity.java (existing - skipped)
[        ]   flutter_test/android/build.gradle (existing - skipped)
[        ]   flutter_test/flutter_test_android.iml (existing - skipped)
[        ]   flutter_test/android.iml (existing - skipped)
[        ]   flutter_test/.idea/runConfigurations/main_dart.xml (existing - skipped)
[        ]   flutter_test/.idea/libraries/Flutter_for_Android.xml (existing - skipped)
[        ]   flutter_test/.idea/libraries/Dart_SDK.xml (existing - skipped)
[        ]   flutter_test/.idea/modules.xml (existing - skipped)
[        ]   flutter_test/.idea/workspace.xml (existing - skipped)
[  +12 ms] Wrote 2 files.
[   +6 ms] Running "flutter packages get" in flutter_test...
[   +2 ms] [/Users/wichert/Development/flutter_test/] /Users/wichert/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning get --no-precompile
[ +147 ms] Error on line 9, column 3 of pubspec.yaml: A package may not list itself as a dependency.
[        ]   flutter_test:
[        ]   ^^^^^^^^^^^^
[  +28 ms] "flutter create" took 348ms.
pub get failed (65)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      pub (package:flutter_tools/src/dart/pub.dart:110)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:60)
<asynchronous suspension>
#3      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:218)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#5      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#9      new Future.sync (dart:async/future.dart:222)
#10     CommandRunner.run (package:args/command_runner.dart:109)
#11     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#12     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#13     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#14     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#15     _rootRun (dart:async/zone.dart:1120)
#16     _CustomZone.run (dart:async/zone.dart:1001)
#17     runZoned (dart:async/zone.dart:1467)
#18     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#19     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#21     main (file:///Users/wichert/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[   +4 ms] exiting with code 65
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13 17A405, locale en-NL, channel alpha)
    • Flutter at /Users/wichert/flutter
    • Framework revision 701d534ba9 (4 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/wichert/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 172.4155.35
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • None
```

**Comment by jason-simmons** [comment]
flutter_test is the name of Flutter's test framework package:
    https://docs.flutter.io/flutter/flutter_test/flutter_test-library.html

There will be a name collision if your application package is also called flutter_test

**Comment by wichert** [comment]
That makes sense. As someone totally new to flutter this was confusing. Perhaps it would be possible to have `flutter create` check a blacklist for names that are known to fail so others won't run into this trap?

**Comment by sfla** [comment]
Did the same. 
Silly me.

**Comment by msbit** [comment]
And me!

**Comment by weldonla** [comment]
same! it's funny how common it is to name your first flutter project "flutter_test" haha

**Comment by victordidenko** [comment]
+1 to the company 😅

**Comment by bkonyi** [comment]
+1, how embarrassing...

**Comment by wowbob396** [comment]
+1, They are going to have to change the name of the test framework package at this rate!

**Comment by Felix-Seip** [comment]
+1, I fell for it too

**Comment by cyrsis** [comment]
+1 , I felt for it too

**Comment by mt40** [comment]
+1 another victim
