### ISSUE TITLE
CupertinoContextMenu is using setState after it was unmounted

### ISSUE THREAD

**Issue by tapkain** [flutter/flutter#124597]
In order to reproduce, delete a few items from the context menu.

<details>
<summary>Minimal reproducible code</summary>

```dart

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    home: Scaffold(
      body: SomeStateful(),
    ),
  ));
}

class SomeStateful extends StatefulWidget {
  const SomeStateful({super.key});

  @override
  State<SomeStateful> createState() => _SomeStatefulState();
}

class _SomeStatefulState extends State<SomeStateful> {
  final items = List.generate(2, (index) => index).toList();

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: items
          .map((e) => CupertinoContextMenu(
                  actions: [
                    CupertinoContextMenuAction(
                      child: const Text('DELETE'),
                      onPressed: () {
                        setState(() {
                          items.remove(e);
                        });
                        Navigator.of(context).pop();
                      },
                    )
                  ],
                  child: SizedBox(
                    width: MediaQuery.of(context).size.width,
                    child: Material(
                      child: ListTile(
                        title: Text('Item $e'),
                      ),
                    ),
                  )))
          .toList(),
    );
  }
}

```
</details>

<details>
<summary>Code block where the exception happens context_menu.dart</summary>

```dart
void _routeAnimationStatusListener(AnimationStatus status) {
    if (status != AnimationStatus.dismissed) {
      return;
    }
   // here the CupertinoContextMenu state is unmounted but we call setState
    setState(() {
      _childHidden = false;
    });
    _route!.animation!.removeStatusListener(_routeAnimationStatusListener);
    _route = null;
  }
```

</details>

**Comment by huycozy** [comment]
Hi @tapkain 
I'm not sure I can understand the issue. Can you be more specific? 
I'm seeing you call `setState()` on `CupertinoContextMenuAction`. How does this sample code present the issue?

**Comment by tapkain** [comment]
@huycozy it would be nice if you would run the example.
1. CupertinoContextMenu is pushing a preview route to render the context menu preview.
2. We delete an item in the CupertinoContextMenuAction and pop this preview route
3. CupertinoContextMenu route starts to play its route pop animation
4.  one of the "items" state property got removed  in CupertinoContextMenuAction, so we rebuild the State
5. CupertinoContextMenu unmounted itself from the widget tree, yet the route pop animation above calls setState inside CupertinoContextMenuState., bad things happen later.

my current solution which worked for me is just to check if the state is mounted in context_menu.dart > _routeAnimationStatusListener

the issue in nutshell is when there is a list of CupertinoContextMenus and they are built from some state and if we have a delete action inside those menus, it will always throw by playing the pop animation.

**Comment by huycozy** [comment]
>if we have a delete action inside those menus, it will always throw by playing the pop animation.

Do you mean it should not have pop animation? Can you be more specific on `Actual result` and `Expected result`?

It looks like a proposal to add `unmounted` check to `_routeAnimationStatusListener`. Can you be specific about that check with sample code?

**Comment by tapkain** [comment]
I mean it should not call setState if not mounted. The pop animation is fine.
*Actual result* - after pop animation calls setState while being unmounted
*Expected result* - after pop animation does not call setState

<details>
<summary>context_menu.dart change proposal</summary>
```dart
void _routeAnimationStatusListener(AnimationStatus status) {
    if (status != AnimationStatus.dismissed) {
      return;
    }
   // here the CupertinoContextMenu state is unmounted but we call setState
   // add here check for mounted
    if (mounted) {
    setState(() {
      _childHidden = false;
    });
    }
    _route!.animation!.removeStatusListener(_routeAnimationStatusListener);
    _route = null;
  }
```
</details>

**Comment by TahaTesser** [comment]
Thanks for raising the issue! @tapkain 

> Code block where the exception happens context_menu.dart


I can reproduce the exception using your code sample 

<details> 
<summary>logs</summary> 

```dart
flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown while notifying status listeners for ProxyAnimation:
flutter: setState() called after dispose(): _CupertinoContextMenuState#01594(lifecycle state: defunct, not
flutter: mounted, tickers: tracking 0 tickers)
flutter: This error happens if you call setState() on a State object for a widget that no longer appears in
flutter: the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error
flutter: can occur when code calls setState() from a timer or an animation callback.
flutter: The preferred solution is to cancel the timer or stop listening to the animation in the dispose()
flutter: callback. Another solution is to check the "mounted" property of this object before calling
flutter: setState() to ensure the object is still in the tree.
flutter: This error might indicate a memory leak if setState() is being called because another object is
flutter: retaining a reference to this State object after it has been removed from the tree. To avoid memory
flutter: leaks, consider breaking the reference to this object during dispose().
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1103:9)
flutter: #1      State.setState (package:flutter/src/widgets/framework.dart:1138:6)
flutter: #2      _CupertinoContextMenuState._routeAnimationStatusListener (package:flutter/src/cupertino/context_menu.dart:595:5)
flutter: #3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
flutter: #4      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
flutter: #5      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:815:7)
flutter: #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:831:5)
flutter: #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
flutter: #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
flutter: #9      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1141:11)
flutter: #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
flutter: #11     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1139:17)
flutter: #12     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056:5)
flutter: #13     _invoke1 (dart:ui/hooks.dart:158:13)
flutter: #14     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:337:5)
flutter: #15     _beginFrame (dart:ui/hooks.dart:101:31)
flutter: 
flutter: The ProxyAnimation notifying status listeners was:
flutter:   AnimationController#ce10a(⏮ 0.000; paused; for _ContextMenuRoute<void>)➩ProxyAnimation
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
``` 
	
</details>
