### ISSUE TITLE
Scrolling horizontally within TextField causes error "notification.metrics.axis == widget.axis': is not true."

### ISSUE THREAD

**Issue by aloh86** [flutter/flutter#124551]
I am running into exceptions when trying to scroll horizontally within a TextField. My guess is that there is some interaction between SingleChildScrollView, ListView, and the scrolling within overflowing TextFields that is leading to this issue. 

## Steps to Reproduce
1. Debug the example found at https://github.com/aloh86/overscroll_issue_example.
2. Type text into any of the TextFields so that the text extends beyond the width of the text field.
3. Using touch, scroll horizontally any direction.
4. Assertion error caught by debugger: _**'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.**_

**Expected results:** No failed assertion error on scrolling within the textfield.

**Actual results:**  Failed assertion error on scrolling within the textfield.

<details>
<summary>Code sample</summary>

```
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late List<TextEditingController> controllers;

  @override
  void initState() {
    super.initState();
    controllers = [];
    controllers.add(TextEditingController(text: "A"));
    controllers.add(TextEditingController(text: "B"));
    controllers.add(TextEditingController(text: "C"));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: SingleChildScrollView(
            child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisSize: MainAxisSize.min,
                children: [
                  ListView.builder(
                      shrinkWrap: true,
                      itemCount: controllers.length,
                      itemBuilder: (context, index) {
                        return Row(
                          children: [
                            Expanded(
                                child: TextField(
                                    controller: controllers[index],
                                    decoration: const InputDecoration(
                                      hintText: '(e.g. Road washout 8 miles in.)',
                                    ),
                                    onChanged: (text) {
                                      setState(() {
                                        if (index == controllers.length - 1) {
                                          controllers.add(TextEditingController(text: ""));
                                        }
                                      });
                                    }
                                )
                            ),
                            Flexible(
                                flex: 0,
                                child: index == 0 ? const SizedBox.shrink() : IconButton(
                                  onPressed: () {
                                    setState(() {
                                      controllers.removeAt(index);
                                    });
                                  },
                                  icon: const Icon(
                                    Icons.delete,
                                    color: Colors.red,
                                  ),
                                  color: Colors.red,
                                )
                            )
                          ],
                        );
                      }
                  )
                ]
            )
        ));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[        ] An Observatory debugger and profiler on Moto G 4 is available at: http://127.0.0.1:57222/8Pia9Q_VFnw=/
[+3947 ms] The Flutter DevTools debugger and profiler on Moto G 4 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:57222/8Pia9Q_VFnw=/
[+14393 ms] I/art     ( 9367): Do partial code cache collection, code=14KB, data=31KB
[   +2 ms] I/art     ( 9367): After code cache collection, code=14KB, data=31KB
[        ] I/art     ( 9367): Increasing code cache capacity to 128KB
[+10265 ms] 
                     ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
                     The following assertion was thrown while handling a gesture:
                     'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14:
                     'notification.metrics.axis == widget.axis': is not true.

                     Either the assertion indicates an error in the framework itself, or we should provide substantially
                     more information in this error message to help you determine and fix the underlying cause.
                     In either case, please report this assertion by filing a bug on GitHub:
                       https://github.com/flutter/flutter/issues/new?template=2_bug.md

                     When the exception was thrown, this was the stack:
                     #2      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:243:14)
                     #3      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
                     #4      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3170:18)
                     #5      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
                     #6      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
                     #7      Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4534:24)
                     #8      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
                     #9      DragScrollActivity.dispatchOverscrollNotification (package:flutter/src/widgets/scroll_activity.dart:474:135)
                     #10     ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:931:15)
                     #11     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:285:9)
                     #12     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:78:18)
                     #13     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:122:5)
                     #14     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
                     #15     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:719:12)
                     #16     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:483:55)
                     #17     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
                     #18     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:483:7)
                     #19     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:330:9)
                     #20     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
                     #21     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
                     #22     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
                     #23     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
                     #24     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
                     #25     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
                     #26     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
                     #27     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
                     #28     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
                     #29     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
                     #30     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
                     #31     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
                     #32     _invoke1 (dart:ui/hooks.dart:164:13)
                     #33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
                     #34     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
                     (elided 2 frames from class _AssertionError)

                     Handler: "onUpdate"
                     Recognizer:
                       HorizontalDragGestureRecognizer#b3192
                     ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +20 ms] 
           Another exception was thrown: 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.
[  +94 ms] 
           Another exception was thrown: 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.
[   +3 ms]
           Another exception was thrown: 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.

```

```
## Flutter Doctor ##
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.19044.2728], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2022.1)
[√] VS Code, 64-bit edition (version 1.51.1)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

</details>

**Comment by aloh86** [comment]
So I tried to narrow things down. I get the same issue when I remove the SingleChildScrollView and only have a ListView, so the problem seems that ListView does not like having the horizontally scrolling TextField for a row item.

**Comment by darshankawar** [comment]
@aloh86 
Can you provide updated / simplified code sample that triggers the reported error ? Also, try to run the same on latest master and see if you still get same exception on it or not.

`flutter channel master`
`flutter upgrade`

Also, check [this](https://github.com/flutter/flutter/issues/107772#issuecomment-1219906155) for your further reference:

**Comment by aloh86** [comment]
I read the thread at #107772, but changing the physics did not help. 

I've updated the repository with simplified code sample: https://github.com/aloh86/overscroll_issue_example

<details>
<summary>Updated Simplified Code Example</summary>
```
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter TextField Scrolling Issue'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late List<TextEditingController> controllers;

  @override
  void initState() {
    super.initState();
    controllers = [];
    controllers.add(TextEditingController(text: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum"));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: ListView.builder(
            shrinkWrap: true,
            itemCount: controllers.length,
            itemBuilder: (context, index) {
              return TextField(
                controller: controllers[index],
              );
            })
    );
  }
}
```
</details>

Fortunately, on `flutter channel master` and after `flutter upgrade` I no longer experience the issue. **Does this mean this issue has been fixed and will be released in a future stable channel release?** I think I can use my workaround of avoiding ListView until then.

**Comment by darshankawar** [comment]
Thanks for the update. If it works on latest master, then it is probably fixed and will be rolled into next stable release per Flutter team's release policy https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#stable
Based on your comment, I'll close this as fixed.
