### ISSUE TITLE
Crash when back from webview page on android 4.4(api19)

### ISSUE THREAD

**Issue by bailyzheng** [flutter/flutter#124652]
## Steps to Reproduce

1. Run on Android 4.4 API 19
2. Jump to webview page from any page
3. Back from webview page to top page

**Expected results:**  work well
**Actual results:** crash

<details>
<summary>Code sample</summary>

```dart
main.dart

import 'package:flutter/material.dart';
import 'package:untitled6/page_webview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _toWebviewPage() {
    Navigator.of(context).push(MaterialPageRoute(builder: (context) {
      return ZCWebViewPage(
          "https://stackoverflow.com/",
          title: "stackoverflow");
    }));
  }

  @override
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(color: Colors.red,),
      floatingActionButton: FloatingActionButton(
        onPressed: _toWebviewPage,
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  @override
  void dispose() {
    super.dispose();
  }
}

page_webview.dart

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class ZCWebViewPage extends StatefulWidget {
  final String url;
  final String? title;
  final bool hideTitle;

  ZCWebViewPage(this.url, {this.title, this.hideTitle = false});

  @override
  _ZCWebViewPageState createState() => _ZCWebViewPageState();
}

class _ZCWebViewPageState extends State<ZCWebViewPage> {
  late WebViewController controller;

  @override
  void initState() {
    super.initState();
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse(widget.url));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: widget.hideTitle ? null : AppBar(title: Text(widget.title!)),
        body: WebViewWidget(
          controller: controller,
        ));
  }
}


```

</details>

<details>
  <summary>Logs</summary>

```
I/BufferQueue(19639): [unnamed-19639-1](this:0x67b4e3f0,id:1,api:1,p:19639,c:19639) new GraphicBuffer needed
D/BufferQueue(19639):     [OLD] gb:NULL
D/GraphicBuffer(19639): create handle(0x6787d418) (w:608, h:1024, f:1)
I/BufferQueue(19639):     [NEW] gb=0x66f3b1b0, handle=0x6787d418, w=600, h=1024, s=608, fmt=1
I/BufferQueue(19639): [unnamed-19639-1](this:0x67b4e3f0,id:1,api:1,p:19639,c:19639) [queue] fps:0.10, dur:9628.48, max:9628.48, min:9628.48
I/BufferQueue(19639): [unnamed-19639-2](this:0x67b4ea58,id:2,api:1,p:19639,c:19639) new GraphicBuffer needed
D/BufferQueue(19639):     [OLD] gb:NULL
D/GraphicBuffer(19639): create handle(0x63af01c0) (w:608, h:1024, f:1)
I/BufferQueue(19639):     [NEW] gb=0x671557a8, handle=0x63af01c0, w=600, h=1024, s=608, fmt=1
I/BufferQueue(19639): [unnamed-19639-2](this:0x67b4ea58,id:2,api:1,p:19639,c:19639) [queue] fps:0.10, dur:9623.64, max:9623.64, min:9623.64
W/ImageReader_JNI(19639): Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
E/flutter (19639): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: maxImages (3) has already been acquired, call #close before acquiring more.
E/flutter (19639): 	at android.media.ImageReader.acquireNextImage(ImageReader.java:346)
E/flutter (19639): 	at android.media.ImageReader.acquireLatestImage(ImageReader.java:242)
E/flutter (19639): 	at io.flutter.embedding.android.FlutterImageView.acquireLatestImage(FlutterImageView.java:197)
E/flutter (19639): 	at io.flutter.embedding.android.FlutterView.acquireLatestImageViewFrame(FlutterView.java:1398)
E/flutter (19639): 	at io.flutter.plugin.platform.PlatformViewsController.onEndFrame(PlatformViewsController.java:1196)
E/flutter (19639): 	at io.flutter.embedding.engine.FlutterJNI.onEndFrame(FlutterJNI.java:1167)
E/flutter (19639): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (19639): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter (19639): 	at android.os.Looper.loop(Looper.java:150)
E/flutter (19639): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/flutter (19639): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter (19639): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter (19639): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
E/flutter (19639): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
E/flutter (19639): 	at dalvik.system.NativeStart.main(Native Method)
E/flutter (19639): 
F/flutter (19639): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1531)] Check failed: fml::jni::CheckException(env). 
F/libc    (19639): Fatal signal 6 (SIGABRT) at 0x00004cb7 (code=-6), thread 19639 (ample.untitled6)
handle_request(15)
check process 19639 name:ample.untitled6
tid 19639 abort msg address is:0
BOOM: pid=19639 uid=10062 gid=10062 tid=19639
[OnPurpose Redunant in preset_info] pid: 19639, tid: 19639, name: ample.untitled6  >>> com.example.untitled6 <<<
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'THTF/ratech82_cwet_rgk_kk/ratech82_cwet_rgk_kk:4.4.2/KOT49H/1436772508:user/test-keys'
pid: 19639, tid: 19639, name: ample.untitled6  >>> com.example.untitled6 <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    r0 00000000  r1 00004cb7  r2 00000006  r3 00000000
    r4 00000006  r5 00000002  r6 00004cb7  r7 0000010c
    r8 bed521a8  r9 ffffffff  sl 4014e795  fp 4014e69e
    ip 00000001  sp bed51f88  lr 400bf2b1  pc 400ce1f4  cpsr 000b0010
backtrace:
    #00  pc 000261f4  /system/lib/libc.so (tgkill+12)
    #01  pc 000172ad  /system/lib/libc.so (pthread_kill+48)
    #02  pc 000174c1  /system/lib/libc.so (raise+10)
    #03  pc 000161f5  /system/lib/libc.so
    #04  pc 00025aa4  /system/lib/libc.so (abort+4)
    #05  pc 0000077b  /data/app-lib/com.example.untitled6-1/libflutter.so
stack:
         bed51f48  bed51f60  [stack]
         bed51f4c  625732af  /data/app-lib/com.example.untitled6-1/libflutter.so
         bed51f50  bed5204c  [stack]
         bed51f54  00000020  
         bed51f58  bed51f60  [stack]
         bed51f5c  0000001f  
         bed51f60  62c72b60  /data/app-lib/com.example.untitled6-1/libflutter.so
         bed51f64  bed51f70  [stack]
         bed51f68  00000080  
         bed51f6c  4010f9c4  
         bed51f70  00000012  
         bed51f74  66f9eac8  
         bed51f78  400a396d  /system/lib/liblog.so
         bed51f7c  6134b2a7  /data/app-lib/com.example.untitled6-1/libflutter.so
         bed51f80  00000015  
         bed51f84  5d62fb28  
    #00  bed51f88  00000006  
         bed51f8c  00000002  
         bed51f90  00004cb7  
         bed51f94  00000001  
         bed51f98  00000001  
         bed51f9c  400bf2b1  /system/lib/libc.so (pthread_kill+52)
    #01  bed51fa0  00000006  
         bed51fa4  bed51ff4  [stack]
         bed51fa8  00000003  
         bed51fac  400bf4c5  /system/lib/libc.so (raise+14)
    #02  bed51fb0  bed51fbc  [stack]
         bed51fb4  400be1f9  /system/lib/libc.so
memory near r1:
    00004c94 ffffffff ffffffff ffffffff ffffffff  
    00004ca4 ffffffff ffffffff ffffffff ffffffff  
    00004cb4 ffffffff ffffffff ffffffff ffffffff  
    00004cc4 ffffffff ffffffff ffffffff ffffffff  
    00004cd4 ffffffff ffffffff ffffffff ffffffff  
    00004ce4 ffffffff ffffffff ffffffff ffffffff  
    00004cf4 ffffffff ffffffff ffffffff ffffffff  
    00004d04 ffffffff ffffffff ffffffff ffffffff  
    00004d14 ffffffff ffffffff ffffffff ffffffff  
    00004d24 ffffffff ffffffff ffffffff ffffffff  
    00004d34 ffffffff ffffffff ffffffff ffffffff  
    00004d44 ffffffff ffffffff ffffffff ffffffff  
    00004d54 ffffffff ffffffff ffffffff ffffffff  
    00004d64 ffffffff ffffffff ffffffff ffffffff  
    00004d74 ffffffff ffffffff ffffffff ffffffff  
    00004d84 ffffffff ffffffff ffffffff ffffffff  
memory near r6:
    00004c94 ffffffff ffffffff ffffffff ffffffff  
    00004ca4 ffffffff ffffffff ffffffff ffffffff  
    00004cb4 ffffffff ffffffff ffffffff ffffffff  
    00004cc4 ffffffff ffffffff ffffffff ffffffff  
    00004cd4 ffffffff ffffffff ffffffff ffffffff  
    00004ce4 ffffffff ffffffff ffffffff ffffffff  
    00004cf4 ffffffff ffffffff ffffffff ffffffff  
    00004d04 ffffffff ffffffff ffffffff ffffffff  
    00004d14 ffffffff ffffffff ffffffff ffffffff  
    00004d24 ffffffff ffffffff ffffffff ffffffff  
    00004d34 ffffffff ffffffff ffffffff ffffffff  
    00004d44 ffffffff ffffffff ffffffff ffffffff  
    00004d54 ffffffff ffffffff ffffffff ffffffff  
    00004d64 ffffffff ffffffff ffffffff ffffffff  
    00004d74 ffffffff ffffffff ffffffff ffffffff  
    00004d84 ffffffff ffffffff ffffffff ffffffff  
memory near r8:
    bed52188 5cd4db00 bed521e0 00000032 00000001  
    bed52198 bed521f8 4014e795 4014e69e 627e25f7  
    bed521a8 62b666ec 62fb8000 83e0cfd7 00000aac  
    bed521b8 bed521a8 62fc48f0 638c9acc 638c9ac0  
    bed521c8 62583045 62da1840 00000032 6257f5b7  
    bed521d8 83e2ad4e 00000aac 00000001 66f7c3f8  
    bed521e8 00000001 4014cc89 00000000 4014ccbd  
    bed521f8 5cd5b050 00000000 62d9f990 bed52230  
    bed52208 66fb32e0 4014a7d1 83e2ad4e 00000aac  
    bed52218 00000001 62583045 66f7c3f8 00000000  
    bed52228 00000032 5cd5b050 00000000 62583051  
    bed52238 00000032 4014bd35 5cd5b008 4014c765  
    bed52248 00000000 629cddfb bb84b4bc 00000001  
    bed52258 00000032 4014e69e 00000000 61356a37  
    bed52268 00000001 63480a68 00000032 00000000  
    bed52278 6787eb90 6787eb98 bed52308 00000000  
memory near sl:
    4014e774 7665206c 73746e65 25783020 6e6f2078  
    4014e784 6b617720 65722065 70206461 2e657069  
    4014e794 6e674900 6e69726f 6e752067 65707865  
    4014e7a4 64657463 6f706520 65206c6c 746e6576  
    4014e7b4 78302073 6f207825 6466206e 20642520  
    4014e7c4 74616874 20736920 6c206f6e 65676e6f  
    4014e7d4 65722072 74736967 64657265 6f43002e  
    4014e7e4 20646c75 20746f6e 61657263 77206574  
    4014e7f4 20656b61 65706970 6520202e 6f6e7272  
    4014e804 0064253d 6c756f43 6f6e2064 616d2074  
    4014e814 7720656b 20656b61 64616572 70697020  
    4014e824 6f6e2065 6c622d6e 696b636f 202e676e  
    4014e834 72726520 253d6f6e 6f430064 20646c75  
    4014e844 20746f6e 656b616d 6b617720 72772065  
    4014e854 20657469 65706970 6e6f6e20 6f6c622d  
    4014e864 6e696b63 20202e67 6e727265 64253d6f  
memory near fp:
    4014e67c 20736570 69687428 70253d73 6872202c  
    4014e68c 70253d73 65720029 746c7573 203d2120  
    4014e69c 6f4c0030 7265706f 756f4300 6e20646c  
    4014e6ac 6120746f 636f6c6c 20657461 20534c54  
    4014e6bc 2e79656b 68747000 64616572 636e6f5f  
    4014e6cc 61662065 64656c69 43005700 646c756f  
    4014e6dc 746f6e20 69727720 77206574 20656b61  
    4014e6ec 6e676973 202c6c61 6e727265 64253d6f  
    4014e6fc 72724500 7220726f 766f6d65 20676e69  
    4014e70c 6c6f7065 7665206c 73746e65 726f6620  
    4014e71c 20646620 202c6425 6e727265 64253d6f  
    4014e72c 6c6f5000 6166206c 64656c69 74697720  
    4014e73c 6e612068 656e7520 63657078 20646574  
    4014e74c 6f727265 65202c72 6f6e7272 0064253d  
    4014e75c 6f6e6749 676e6972 656e7520 63657078  
    4014e76c 20646574 6c6f7065 7665206c 73746e65  
memory near sp:
    bed51f68 00000080 4010f9c4 00000012 66f9eac8  
    bed51f78 400a396d 6134b2a7 00000015 5d62fb28  
    bed51f88 00000006 00000002 00004cb7 00000001  
    bed51f98 00000001 400bf2b1 00000006 bed51ff4  
    bed51fa8 00000003 400bf4c5 bed51fbc 400be1f9  
    bed51fb8 bed521a8 ffffffdf 00053e3c bed51ff4  
    bed51fc8 bed51ff4 00000003 bed51ff4 bed52014  
    bed51fd8 bed51ff4 400cdaa8 400a396d 6256377f  
    bed51fe8 00000001 6257ed9f bed52014 00000081  
    bed51ff8 0000007d 66f9eac8 418a8e30 62da14e4  
    bed52008 62da5bb0 6256ce35 61388388 62b49214  
    bed52018 62b48930 62c72b60 00000000 00000000  
    bed52028 00000000 67b6b710 67b6b78d 67b6b78f  
    bed52038 00000081 0000007f 67b6b710 67b6b78d  
    bed52048 00000010 62b49228 00001002 00000006  
    bed52058 00000000 00000000 00000000 bed52018  
code around pc:
    400ce1d4 e8bd00f0 e3700a01 912fff1e e2600000  
    400ce1e4 ea00b702 e92d50f0 e3a07f43 ef000000  
    400ce1f4 e8bd50f0 e3700a01 912fff1e e2600000  
    400ce204 ea00b6fa e92d50f0 e3a070ee ef000000  
    400ce214 e8bd50f0 e3700a01 912fff1e e2600000  
    400ce224 ea00b6f2 00000000 00000000 e92d400f  
    400ce234 e1a03000 e1a00001 e1a01003 eb000040  
    400ce244 e8bd400f e12fff1e e320f000 e92d403f  
    400ce254 e2522040 ba00002c e1a05001 e2455c01  
    400ce264 f5d5f000 f5d5f040 f5d5f080 f5d5f0c0  
    400ce274 e2411040 e2400040 e1a05000 e1a04001  
    400ce284 f424020d f424420d f405022d f405422d  
    400ce294 e2522040 ba00001c e2411040 e2400040  
    400ce2a4 e1a05000 e1a04001 f424020d f424420d  
    400ce2b4 f405022d f405422d e2522040 ba000012  
    400ce2c4 e2411040 e2400040 e1a05000 e1a04001  
code around lr:
    400bf290 447b4b13 42b3e010 4812d10e 44786a1e  
    400bf2a0 eb08f7f8 e9d8f00d 46224631 ef9cf00e  
    400bf2b0 d00a3001 e00b2400 2b00681b 480ad1eb  
    400bf2c0 44782403 eaf6f7f8 f001e002 6804fa1b  
    400bf2d0 fa18f001 46206005 bf00bd70 0005095a  
    400bf2e0 0005094e 00050946 00050922 bf7ef7ff  
    400bf2f0 43f0e92d 4a3d4b3c 589c447b 6823b08b  
    400bf300 460d4606 f0019309 46a1f9fd 8000f8d0  
    400bf310 d0482d00 f00f4628 280ffed5 d8444604  
    400bf320 ffe4f7ff d1064286 4629200f e8a2f00d  
    400bf330 d03c2800 482ee02e f7f84478 482dea3a  
    400bf340 e0154478 d11342b0 482b6a06 f7f84478  
    400bf350 4a2aeab2 447a2120 a8014633 e84af015  
    400bf360 a8012101 ef52f021 46061c42 e011d104  
    400bf370 28006800 e02cd1e6 46294630 f00d4622  
    400bf380 1c43e8de d11e4607 f9bcf001 29046801  
timed out waiting for tid=19642 to stop
timed out waiting for tid=19647 to stop
timed out waiting for tid=19648 to stop
timed out waiting for tid=19649 to stop
timed out waiting for tid=19650 to stop
timed out waiting for tid=19651 to stop
timed out waiting for tid=19652 to stop
timed out waiting for tid=19653 to stop

```

```
Analyzing untitled6...                                                  

   info • Constructors for public widgets should have a named 'key' parameter • lib/page_webview.dart:9:3 • use_key_in_widget_constructors
   info • Constructors in '@immutable' classes should be declared as 'const' • lib/page_webview.dart:9:3 • prefer_const_constructors_in_immutables
   info • Invalid use of a private type in a public API • lib/page_webview.dart:12:3 • library_private_types_in_public_api

3 issues found. (ran in 1.9s)

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3.1 22E261 darwin-x64, locale zh-Hans-CN)                                                                                                               Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @bailyzheng, this issue is being tracked in https://github.com/flutter/flutter/issues/93380. 

Kindly upvote the original issue. 

Closing from here as duplicate. 

Thank you
