### ISSUE TITLE
'_down == null && _up == null': is not true

### ISSUE THREAD

**Issue by HelloBitches** [flutter/flutter#124647]
```
======== Exception caught by gesture library =======================================================
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/tap.dart': Failed assertion: line 210 pos 14: '_down == null && _up == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      BaseTapGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/tap.dart:210:14)
#3      GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:160:7)
#4      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1498:18)
#5      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:3168:29)
#6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
#8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#12     _invoke1 (dart:ui/hooks.dart:164:13)
#13     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#14     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
Event: PointerDownEvent#ad541(position: Offset(61.5, 560.0))
  position: Offset(61.5, 560.0)
Target: RenderPointerListener#0f401 relayoutBoundary=up12
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=586.0)
  size: Size(414.0, 586.0)
  behavior: deferToChild
  listeners: down, panZoomStart
====================================================================================================
```

**Comment by danagbemava-nc** [comment]
Hi @HelloBitches,

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you
