### ISSUE TITLE
Wrapping a Scrollbar around a TabBar throws error `The Scrollbar's ScrollController has no ScrollPosition attached.`

### ISSUE THREAD

**Issue by zogol** [flutter/flutter#124608]
Wrapping a Scrollbar around a TabBar **works** but throws a console error 

**The Scrollbar's ScrollController has no ScrollPosition attached.**
A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.A ScrollView with an Axis.vertical ScrollDirection on mobile platforms will automatically use the PrimaryScrollController if the user has not provided a ScrollController. To use the PrimaryScrollController explicitly, set ScrollView.primary to true for the Scrollable widget.

The fix described in this commend https://github.com/flutter/flutter/issues/97873#issuecomment-1086520352 does not work because a tabcontroller cannot be applied to a scrollcontroller

```
PreferredSize(
              preferredSize: const Size.fromHeight(55),
              child: RawScrollbar(
                //controller: PrimaryScrollController.of(context),
                //padding: EdgeInsets.all(5),
                mainAxisMargin: 5,
                trackVisibility: false,
                thumbColor: Theme.of(context).focusColor,
                thickness: 3,
                thumbVisibility: true,
                interactive: false,
                scrollbarOrientation: ScrollbarOrientation.top,
                child: TabBar(
                  padding: const EdgeInsets.only(top: 5),
                  controller: _tabController,
                  labelPadding: const EdgeInsets.symmetric(horizontal: 20),
                  //padding: const EdgeInsets.only(top: 5,bottom: 5, left: 5, right: 5),
                  labelColor: Theme.of(context).colorScheme.primary,
                  labelStyle: Theme.of(context).textTheme.titleMedium,
                  isScrollable: true,
                  unselectedLabelColor:
                      Theme.of(context).focusColor.withOpacity(0.7),
                  indicatorColor: Theme.of(context).colorScheme.primary,
                  tabs: __tabs,
                ),
              ),
            ),
```

Working with **Channel stable, 3.7.10** and the issue appears on all platforms

**Comment by darshankawar** [comment]
@zogol 
`TabBarView` is also scrollable, so if you are wrapping `Scrollbar` around it, it might be causing conflict on scroll and hence the error could likely being thrown.

Can you provide us your use case for which you need to wrap scrollbar around tabbar ?
Also read this https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html and see if it helps in your use case.

**Comment by zogol** [comment]
The practical example in which I would apply it would be the following.
I have a tabbar with a large number of tabs. and similar to long vertically scrollable lists I would like to show my users an indicator where they are located inside the TabBar.


https://user-images.githubusercontent.com/100768486/231699218-cb0fb905-443d-4bf4-8ea1-a5c94232e2b8.mp4

**Comment by darshankawar** [comment]
@zogol 
Did you get a chance to look at NestedScrollView and see if it helps in implementing your use case ?

**Comment by zogol** [comment]
@darshankawar .no but i am not a professional in flutter yet either... 

i found another practical example right here on the github tabbar which also shows a scroll indicator.

https://user-images.githubusercontent.com/100768486/233711206-cdc4cc0b-0feb-424d-9a78-08dd93b39fd9.mp4

**Comment by darshankawar** [comment]
Thanks for the feedback. Please provide us a minimal code sample that throws the reported error so that we can analyze the issue further.

**Comment by zogol** [comment]
`   PreferredSize(
              preferredSize: const Size.fromHeight(55),
              child:
            /*  RawScrollbar(
                mainAxisMargin: 5,
                trackVisibility: false,
                thumbColor: Theme.of(context).colorScheme.secondary,
                thickness: 1,
                thumbVisibility: true,
                interactive: false,

                scrollbarOrientation: ScrollbarOrientation.top,
                child:*/

                TabBar(
                  padding: const EdgeInsets.only(top: 5),
                  controller: _tabController,
                  labelPadding: const EdgeInsets.symmetric(horizontal: 20),
                  //padding: const EdgeInsets.only(top: 5,bottom: 5, left: 5, right: 5),
                  labelColor: Theme.of(context).colorScheme.primary,
                  labelStyle: Theme.of(context).textTheme.titleMedium,
                  isScrollable: true,
                  unselectedLabelColor:
                      Theme.of(context).focusColor.withOpacity(0.7),
                  indicatorColor: Theme.of(context).colorScheme.primary,
                  tabs: _tabs
                      .map((value) => Tab(
                            height: 50,
                            text: value.label,
                            iconMargin: EdgeInsets.zero,
                            icon: Icon(IconData(value.iconCodePoint,
                                fontFamily: 'MaterialIcons')),
                          ))
                      .toList(),
                ),
              ),`


If you comment out the commented section with the "RawScrollbar", the described error will occur.

**Comment by darshankawar** [comment]
Thanks for the update. Please switch to latest master and try again to see if issue still persists or not. Also check [this](https://github.com/flutter/flutter/issues/97873#issuecomment-1431081368) comment / solution to see if it works in your case or not.

**Comment by zogol** [comment]
I still receive that error with flutter 3.10. I also tried to set PrimaryScrollController.of(context)

```
RawScrollbar(
      controller: PrimaryScrollController.of(context),
      mainAxisMargin: 5,
      trackVisibility: false,
      thickness: 2,
      thumbVisibility: true,
      interactive: false,
      scrollbarOrientation: ScrollbarOrientation.top,
      child:
```

**Comment by darshankawar** [comment]
Thanks for the update. I am able to replicate the originally reported behavior using the code sample [provided](https://github.com/flutter/flutter/issues/124608#issuecomment-1529985524).

<details>
<summary> console error log </summary>

```

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.When ScrollView.scrollDirection is Axis.vertical on mobile platforms will automatically use the PrimaryScrollController if the user has not provided a ScrollController. To use the PrimaryScrollController explicitly, set ScrollView.primary to true for the Scrollable widget.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1567:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1592:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1521:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1223:9)
#5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================

```

</details>

Referred [similar issue](https://github.com/flutter/flutter/issues/97873) raised, but the solutions mentioned in it doesn't seem to solve this use case, as here, the `Scrollbar` is wrapped around `TabBar`.  Tried by wrapping with `SingleChildScrollView` and passing the controller, but it didn't work.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.10.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.10.1 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (35 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.11.0-6.0.pre.134, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.11.0-6.0.pre.134 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f31dae2a80 (5 hours ago), 2023-05-17 17:18:51 -0700
    • Engine revision d970370779
    • Dart version 3.1.0 (build 3.1.0-118.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by Piinks** [comment]
TabBar scrolls horizontally so it will not try to use the PrimaryScrollController by default. And wrapping the scrollbar around the TabBar will not work without providing the scrollbar a scroll controller.
You could have this work a couple of ways, best would probably be through the ScrollBehavior.buildScrollbar. This is called for all scrollable widgets, so extending that would allow you to add a scrollbar. Similarly, ScrollBehavior.buildScrollbar won't add one for horizontal scrolling.

This reminded me of https://github.com/flutter/flutter/issues/123965 though, since it would allow this to work the way the OP has it by just directly providing the controller to the scrollbar and the tabbar.

**Comment by Ferrb9579** [comment]
```RawScrollbar(
  scrollbarOrientation: ScrollbarOrientation.right,
  radius: Radius.circular(100.h),
  mainAxisMargin: 2.h,
  thumbVisibility: true,
  controller: Scontroller,
  child: ListView.builder(
    // primary: true,
    controller: Scontroller,
    itemCount: _warehouseListedData.value?.map((e) => e["godown"]).toSet().toList().length,
    scrollDirection: Axis.vertical,
    shrinkWrap: true,
    padding: EdgeInsets.all(0.5.h),
    itemBuilder: (context, index) {
      return Container(
        width: double.infinity,
        margin: EdgeInsets.all(1.w),
        padding: EdgeInsets.symmetric(vertical: 1.h, horizontal: 2.w),
        decoration: BoxDecoration(color: Color.fromRGBO(34, 34, 34, 1), borderRadius: BorderRadius.circular(1.h)),
        child: Column(
          children: [
            IntrinsicHeight(
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  RichText(
                    text: TextSpan(
                      children: [
                        TextSpan(text: "GODOWN: ", style: TextStyle(fontSize: 18, decoration: TextDecoration.none, color: Colors.red, fontWeight: FontWeight.w500)),
                        TextSpan(text: "${_warehouseListedData.value?.map((e) => e["godown"]).toSet().toList()[index]}", style: TextStyle(fontSize: 20, decoration: TextDecoration.none, color: Colors.red, fontWeight: FontWeight.w600)),
                      ],
                    ),
                  ),
                  AspectRatio(
                    aspectRatio: 1,
                    child: Container(
                      decoration: BoxDecoration(borderRadius: BorderRadius.circular(0.5.h), border: Border.all(color: Color.fromARGB(255, 75, 75, 75), width: 2.5), color: Colors.white),
                      child: Center(
                        child: Padding(
                          padding: EdgeInsets.all(1.0.w),
                          child: Text(
                            "ALL",
                            style: TextStyle(fontWeight: FontWeight.w700, decoration: TextDecoration.none),
                          ),
                        ),
                      ),
                    ),
                  )
                ],
              ),
            ),
            SizedBox(
              height: 1.h,
            ),
            Column(
              children: () {
                List<Widget> widgets = [];

                var thisGodown = _warehouseListedData.value?.map((e) => e["godown"]).toSet().toList()[index];
                var thisGodownCompartments = _warehouseListedData.value
                    ?.map((e) {
                      if (e["godown"] == thisGodown) {
                        return e["compartment"];
                      }
                    })
                    .toSet()
                    .whereType<String>()
                    .toList();
                for (var compartment in thisGodownCompartments!) {
                  var thisCompartmentLocations = _warehouseListedData.value
                      ?.map((e) {
                        if (e["godown"] == thisGodown && e["compartment"] == compartment) {
                          return e["location"];
                        }
                      })
                      .toSet()
                      .whereType<String>()
                      .toList();
                  print(thisCompartmentLocations.toString());
                  ScrollController sc = ScrollController();
                  widgets.add(
                    Container(
                      height: 6.h,
                      margin: EdgeInsets.symmetric(horizontal: 0.5.w),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(1.h),
                        color: Color.fromARGB(255, 69, 69, 69),
                      ),
                      child: RawScrollbar(
                        controller: sc,
                        thumbVisibility: true,
                        scrollbarOrientation: ScrollbarOrientation.bottom,
                        child: ListView.builder(
                          // primary: true,
                          controller: sc,
                          shrinkWrap: true,

                          scrollDirection: Axis.horizontal,
                          itemCount: thisCompartmentLocations?.length,
                          itemBuilder: (context, index) {
                            return AspectRatio(
                              aspectRatio: 1,
                              child: Container(
                                margin: EdgeInsets.symmetric(vertical: 2.w, horizontal: 2.w),
                                decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(1.w)),
                              ),
                            );
                          },
                        ),
                      ),
                    ), // TODO
                  );
                  widgets.add(SizedBox(
                    height: 1.h,
                  ));
                }
                // print(thisGodownCompartments.toString());
                return widgets;
              }(),
            )
          ],
        ),
      );
    },
  ),
)
```
Sorry I was lazy to destructure. Hope someone finds it useful

The Scrollbar and ListView must contain same ScrollController.
The ListView Physics should not be defined
