### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY in animation

### ISSUE THREAD

**Issue by BlankRain** [flutter/flutter#12461]
I fork code from 
[dart_hub](https://github.com/SamThompson/dart_hub)
and just run ``` flutter run```
got an error here: 

```
Syncing files to device Android SDK built for x86...
I/flutter ( 3235): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3235): The following assertion was thrown building
I/flutter ( 3235): _ModalScope-[LabeledGlobalKey<_ModalScopeState>#eb38d](dirty, state: _ModalScopeState#38269):
I/flutter ( 3235): type '_AnimatedEvaluation<Offset>' is not a subtype of type 'Animation<FractionalOffsetGeometry>' of
I/flutter ( 3235): 'position' where
I/flutter ( 3235):   _AnimatedEvaluation is from package:flutter/src/animation/tween.dart
I/flutter ( 3235):   Offset is from dart:ui
I/flutter ( 3235):   double is from dart:core
I/flutter ( 3235):   Offset is from dart:ui
I/flutter ( 3235):   Animation is from package:flutter/src/animation/animation.dart
I/flutter ( 3235):   FractionalOffsetGeometry is from package:flutter/src/painting/fractional_offset.dart
I/flutter ( 3235):
I/flutter ( 3235): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3235): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3235): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3235):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3235):
I/flutter ( 3235): When the exception was thrown, this was the stack:
I/flutter ( 3235): #0      new SlideTransition (package:flutter/src/widgets/transitions.dart:106)
I/flutter ( 3235): #1      Router._standardTransitionsBuilder.<anonymous closure> (package:fluro/src/router.dart:138)
I/flutter ( 3235): #2      PageRouteBuilder.buildTransitions (package:flutter/src/widgets/pages.dart:121)
I/flutter ( 3235): #3      _ModalScopeState.build (package:flutter/src/widgets/routes.dart:469)
I/flutter ( 3235): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3646)
I/flutter ( 3235): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556)
I/flutter ( 3235): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
I/flutter ( 3235): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3536)
I/flutter ( 3235): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3674)
I/flutter ( 3235): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3531)
I/flutter ( 3235): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2900)
I/flutter ( 3235): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2703)
I/flutter ( 3235): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
I/flutter ( 3235): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
I/flutter ( 3235): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3536)
I/flutter ( 3235): #15     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3674)
I/flutter ( 3235): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3531)
I/flutter ( 3235): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2900)
I/flutter ( 3235): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2703)
I/flutter ( 3235): #19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4330)
I/flutter ( 3235): #20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653)
I/flutter ( 3235): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
I/flutter ( 3235): #22     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507)
I/flutter ( 3235): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
I/flutter ( 3235): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
I/flutter ( 3235): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
I/flutter ( 3235): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3693)
I/flutter ( 3235): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
I/flutter ( 3235): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
I/flutter ( 3235): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
I/flutter ( 3235): #30     ProxyElement.update (package:flutter/src/widgets/framework.dart:3803)
I/flutter ( 3235): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
I/flutter ( 3235): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4545)
I/flutter ( 3235): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
I/flutter ( 3235): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
I/flutter ( 3235): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
I/flutter ( 3235): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:3693)
I/flutter ( 3235): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
I/flutter ( 3235): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4545)
I/flutter ( 3235): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
I/flutter ( 3235): #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4545)
I/flutter ( 3235): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2692)
I/flutter ( 3235): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568)
I/flutter ( 3235): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3457)
I/flutter ( 3235): #44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2261)
I/flutter ( 3235): #45     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:530)
I/flutter ( 3235): #46     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:194)
I/flutter ( 3235): #47     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713)
I/flutter ( 3235): #48     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649)
I/flutter ( 3235): #49     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:86)
I/flutter ( 3235): #50     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:75)
I/flutter ( 3235): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 3235): Another exception was thrown: type '_AnimatedEvaluation<Offset>' is not a subtype of type 'Animation<FractionalOffsetGeometry>' of 'position' where

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8110/
For a more detailed help message, press "h". To quit, press "q".
D/EGL_emulation( 3235): eglMakeCurrent: 0xa0985780: ver 2 0 (tinfo 0xa0983ec0)
```

**Comment by Hixie** [comment]
This is probably because the Router class has not been updated to match @abarth's recent changes to SlideTransition.

It needs to change from using FractionalOffset to using Offset.

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by Hixie** [comment]
Filed on Fluro at https://github.com/goposse/fluro/issues/23

**Comment by BlankRain** [comment]
@Hixie  Thanks ...
