### ISSUE TITLE
Non-fatal: EditableTextState._scheduleShowCaretOnScreen throws _GrowableList.last Bad state: No element.

### ISSUE THREAD

**Issue by rohansohonee1** [flutter/flutter#124846]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Unable to reproduce this issue. The issue is reported from firebase crashlytics.

### Expected results

Should not throw the exception "Bad state: No element."

### Actual results

Throws the exception "Bad state: No element."

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: No element. Error thrown Instance of 'wja'.
#00 pc 0xc64a87 com.agendaboa.app (_GrowableList.last [growable_array.dart:348]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
#01 pc 0x33f88b com.agendaboa.app (EditableTextState._scheduleShowCaretOnScreen.<anonymous closure> [editable_text.dart:3206]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
#02 pc 0xc4a76b com.agendaboa.app (SchedulerBinding._invokeFrameCallback [binding.dart:1289]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
#03 pc 0xc4a5cf com.agendaboa.app (SchedulerBinding.handleDrawFrame [binding.dart:1227]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
#04 pc 0x34313f com.agendaboa.app (SchedulerBinding._handleDrawFrame [binding.dart:1076]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
#05 pc 0x342fef com.agendaboa.app (SchedulerBinding._handleDrawFrame [binding.dart:1058]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
#06 pc 0x32d01b com.agendaboa.app (_invoke [hooks.dart:145]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
#07 pc 0x32cf87 com.agendaboa.app (PlatformDispatcher._drawFrame [platform_dispatcher.dart:338]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
#08 pc 0x32cf3b com.agendaboa.app (_drawFrame [hooks.dart:112]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
#09 pc 0x32d077 com.agendaboa.app (_drawFrame [hooks.dart:110]) (BuildId: bca64abf3983671931bb8f1ccc469e31)
```

```
Device
Brand:Xiaomi
Model:Poco M3
Orientation: Portrait
RAM free: 1.05 GB
Disk free: 62.74 GB
Operating System
Version:Android 12
Orientation: Portrait
Rooted:No
Crash
Date:Apr 13, 2023, 9:54:56 PM
```

### Code sample

<details><summary>Code sample</summary>

```dart
class _CustomTextFieldFormState extends FormFieldState<String> {
  TextEditingController? _controller;

  TextEditingController get _effectiveController =>
      (widget.textEditingController ?? _controller)!;

  @override
  BoaTextField get widget => super.widget as BoaTextField;

  @override
  void initState() {
    super.initState();
    if (widget.textEditingController == null) {
      _controller = TextEditingController(text: widget.initialValue);
    } else {
      widget.textEditingController!.addListener(_handleControllerChanged);
    }
  }

  @override
  void didUpdateWidget(BoaTextField oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.textEditingController != oldWidget.textEditingController) {
      oldWidget.textEditingController?.removeListener(_handleControllerChanged);
      widget.textEditingController?.addListener(_handleControllerChanged);

      if (oldWidget.textEditingController != null &&
          widget.textEditingController == null) {
        _controller = TextEditingController.fromValue(
            oldWidget.textEditingController!.value);
      }
      if (widget.textEditingController != null) {
        setValue(widget.textEditingController!.text);
        if (oldWidget.textEditingController == null) _controller = null;
      }
    }
  }

  @override
  void dispose() {
    widget.textEditingController?.removeListener(_handleControllerChanged);
    super.dispose();
  }

  @override
  void didChange(String? value) {
    super.didChange(value);

    if (_effectiveController.text != value) {
      _effectiveController.text = value ?? '';
    }
  }

  @override
  void reset() {
    // setState will be called in the superclass, so even though state is being
    // manipulated, no setState call is needed here.
    _effectiveController.text = widget.initialValue ?? '';
    super.reset();
  }

  void _handleControllerChanged() {
    // Suppress changes that originated from within this class.
    //
    // In the case where a controller has been passed in to this widget, we
    // register this change listener. In these cases, we'll also receive change
    // notifications for changes originating from within this class -- for
    // example, the reset() method. In such cases, the FormField value will
    // already have been set.
    if (_effectiveController.text != value) {
      didChange(_effectiveController.text);
    }
  }
}




class CustomTextField extends FormField<String>{
@override
  FormFieldState<String> createState() => _CustomTextFieldFormState();
  
  CustomTextField(......):super(
          key: key,
          enabled: isEnabled,
          initialValue:
              textEditingController != null ? textEditingController.text : "",
          onSaved: onSaved,
          validator: validator,
          autovalidateMode: autoValidateMode,
          builder: (FormFieldState<String> state) {
            void onChangedHandler(String value) {
              state.didChange(value);
              if (onChanged != null) {
                onChanged(value);
              }
            }
            
            return TextFormField(.........);
         },
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 12.6.4 21G526 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @rohansohonee1 
Related to `EditableTextState._scheduleShowCaretOnScreen `, see if [this](https://github.com/flutter/flutter/issues/104500) helps and the solution mentioned in one of the comments for your reference if it can be used in your case
