### ISSUE TITLE
Flutter Daemon Terminated. Consider re-starting android studio. 

### ISSUE THREAD

**Issue by Sandeepsunil01** [flutter/flutter#124906]
I am unable to run apps on real device. When a real device is connected flutter daemon terminates immediately. When I disconnect is restarts itself. This is happening suddenly after a flutter plugin upgrade. I tried removing android studio, removing flutter, deleting sdk, deleting Gradle. I even formatted my entire system and reinstalled. But the problem, still exists.

### Flutter Doctor when not connected to real device

Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-x64, locale en-GB)
    • Flutter version 3.7.11 on channel stable at/Volumes/sandeep/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (3 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /Volumes/sandeep/SDK/android
    • Platform android-33, build-tools 34.0.0-rc3
    • ANDROID_HOME = /Volumes/sandeep/SDK/android
    • ANDROID_SDK_ROOT = /Volumes/sandeep/SDK/android
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 20+36-2344)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.3.1 22E261 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

### Flutter Doctor when connected to real device.

Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-x64, locale en-GB)
    • Flutter version 3.7.11 on channel stable at /Volumes/sandeep/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (3 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /Volumes/sandeep/SDK/android
    • Platform android-33, build-tools 34.0.0-rc3
    • ANDROID_HOME = /Volumes/sandeep/SDK/android
    • ANDROID_SDK_ROOT = /Volumes/sandeep/SDK/android
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 20+36-2344)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android `Studio` (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and
      ANDROID_SDK_ROOT environment variable:
      /Volumes/sandeep/SDK/android/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices
      (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices
      (package:flutter_tools/src/device.dart:394:54)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
      <asynchronous suspension>
      #4      DeviceManager.getAllConnectedDevices
      (package:flutter_tools/src/device.dart:182:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate
      (package:flutter_tools/src/doctor.dart:690:34)
      <asynchronous suspension>
      #6      Future.any.onValue (dart:async/future.dart:612:5)
      <asynchronous suspension>

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Same issue was reported on windows yesterday.**

**Comment by Sandeepsunil01** [comment]
I tweeted few settings in Android Studio and Everything worked fine.
