### ISSUE TITLE
 Image picker is already active  when running integration test 

### ISSUE THREAD

**Issue by abdalazeez1** [flutter/flutter#124921]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [ ] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

  image_picker: ^0.8.7+3
 

### Expected results

i need to mock image 

### Actual results

PlatformException(already_active, Image picker is already active, null, null)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:integration_test_flutter1/main.dart' as app;
import 'package:path_provider/path_provider.dart';
// flutter run  integration_test/app/signup/presentation/ui/sign_up_test.dart

void main() {
  group('test signup ', () {
    setUp(() {});
    IntegrationTestWidgetsFlutterBinding.ensureInitialized();

    ///mock image and put initial image [assets/image/dash.jpeg]
    const MethodChannel channel =
        MethodChannel('plugins.flutter.io/image_picker');
    channel.setMockMethodCallHandler((MethodCall methodCall) async {
      ByteData data = await rootBundle.load('assets/image/dash.jpeg');
      Uint8List bytes = data.buffer.asUint8List();
      Directory tempDir = await getTemporaryDirectory();
      File file = await File(
        '${tempDir.path}/tmp.tmp',
      ).writeAsBytes(bytes);
      debugPrint(file.path);
      return file.path;
    });
    testWidgets('sign up ', (WidgetTester tester) async {
      //build widget
      await tester.pumpApp(); //extension methode to pump [main()]

      ///find widget by key
      final addOrRemoveImage = find.byKey(const Key('add_or_remove_image'));

      final textFieldEmail = find.byKey(const Key('email_sign_up'));
      final textFieldName = find.byKey(const Key('name_sign_up'));
      final textFieldPassword = find.byKey(const Key('password_sign_up'));
      final textFieldSubmitPassword =
          find.byKey(const Key('submit_password_sign_up'));

      final buttonSignUp = find.byKey(const Key('sign_up_button'));
      final buttonPickDateTime = find.byKey(const Key('pick_date_time'));

      ///execute
      await tester.enterText(textFieldEmail, 'abd@abd');
      await tester.enterText(textFieldName, 'abd alazeez Alyosfi');
      await tester.enterText(textFieldPassword, '11111111');
      await tester.enterText(textFieldSubmitPassword, '11111111');
      await delay(2);

      ///chose date
      FocusManager.instance.primaryFocus?.unfocus();
      await tester.tap(buttonPickDateTime);
      await tester.pumpAndSettle();
      await delay();
      await tester.tap(find.text('15'));
      await delay();
      await tester.tap(find.text('OK'));
      await tester.pumpAndSettle();

      ///pick image

      await tester.tap(addOrRemoveImage);
      await delay(3);
      await tester.pumpAndSettle();

      ///delete iamge
      await tester.tap(addOrRemoveImage);
      await delay(3);
      await tester.pumpAndSettle();

      ///pick image

      await tester.tap(addOrRemoveImage);
      await delay(3);
      await tester.pumpAndSettle();

      ///sign up
      await tester.tap(buttonSignUp);
      await delay(2);
      await tester.pumpAndSettle();

      await tester.pumpAndSettle();
    });
  });
}

extension on WidgetTester {
  Future<void> pumpApp() async {
    app.main();
    await pumpAndSettle();
  }
}

Future<void> delay([int i = 1]) async {
  await Future.delayed(Duration(milliseconds: 500 * i));
}













```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
/home/abd-alazeez/snap/flutter/common/flutter/bin/flutter --no-color test --machine --start-paused -d RR8M607ENRK integration_test/app/signup/presentation/ui/sign_up_test.dart
Testing started at 4:38 PM ...
Running Gradle task 'assembleDebug'...                             24.7s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...          55.5s

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following PlatformException was thrown running a test:
PlatformException(already_active, Image picker is already active, null, null)

When the exception was thrown, this was the stack:
#0      ImagePickerApi.pickImages (package:image_picker_android/src/messages.g.dart:262:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  sign up
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test (but after the test had completed):
'package:flutter_test/src/binding.dart': Failed assertion: line 1822 pos 12: 'inTest': is not true.

When the exception was thrown, this was the stack:
#2      LiveTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1822:12)
#3      WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:679:23)
#6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#7      WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:672:27)
#8      main.<anonymous closure>.<anonymous closure> (file:///home/abd-alazeez/StudioProjects/humy-pioneer/integration_test_flutter1/integration_test/app/signup/presentation/ui/sign_up_test.dart:63:20)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from class _AssertionError, dart:async, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: sign up 

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.1, on Ubuntu 22.04.1 LTS 5.19.0-38-generic, locale en_US.UTF-8)                                                                  Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code
[✓] Connected device (3 available)
```

</details>

**Comment by stuartmorgan** [comment]
> i need to mock image

No endorsed implementations use the channel you are mocking, so you are using the actual plugin rather than your mocks. I would recommend reading https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests

Closing as this is a bug in the provided test code, not Flutter.
