### ISSUE TITLE
App crash on Pixel with Splash Screen: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()' on a null object reference

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#125122]
Hello!

I am posting this bug report on behalf of the other team and hence don't have a code that reproduces the issue, but I'm hoping other people will find this issue and also confirm it and provide such code example. So please do not close this issue straight away 🙏 

[Adding a splash screen to your Android app](https://docs.flutter.dev/development/platform-integration/android/splash-screen#android-12) recommends adding the following code snippet to support Android 12 Splash Screen API:

```java
import android.os.Build;
import android.os.Bundle;
import android.window.SplashScreenView;
import androidx.core.view.WindowCompat;
import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // Aligns the Flutter view vertically with the window.
        WindowCompat.setDecorFitsSystemWindows(getWindow(), false);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            // Disable the Android splash screen fade out animation to avoid
            // a flicker before the similar frame is drawn in Flutter.
            getSplashScreen()
                .setOnExitAnimationListener(
                    (SplashScreenView splashScreenView) -> {
                        splashScreenView.remove();
                    });
        }

        super.onCreate(savedInstanceState);
    }
}
```

The `setOnExitAnimationListener()` or `splashScreenView.remove()` crashes on Pixel devices on app start with the following stack trace:

```
java.lang.NullPointerException: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()' on a null object reference
  at android.view.SurfaceControl.-$$Nest$mcheckNotReleased(Unknown Source:0)
  at android.view.SurfaceControl$Transaction.checkPreconditions(SurfaceControl.java:2889)
  at android.view.SurfaceControl$Transaction.hide(SurfaceControl.java:3060)
  at android.app.ActivityThread.syncTransferSplashscreenViewTransaction(ActivityThread.java:4357)
  at android.app.ActivityThread.-$$Nest$msyncTransferSplashscreenViewTransaction(Unknown Source:0)
  at android.app.ActivityThread$1.onDraw(ActivityThread.java:4334)
  at android.view.ViewTreeObserver.dispatchOnDraw(ViewTreeObserver.java:1132)
  at android.view.ViewRootImpl.draw(ViewRootImpl.java:4770)
  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4537)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3723)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2442)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9375)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1388)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1396)
  at android.view.Choreographer.doCallbacks(Choreographer.java:1033)
  at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:408)
  at android.view.Choreographer.doFrame(Choreographer.java:900)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1371)
  at android.os.Handler.handleCallback(Handler.java:942)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:240)
  at android.os.Looper.loop(Looper.java:351)
  at android.app.ActivityThread.main(ActivityThread.java:8364)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

The preceding crashes happen on an app built with Flutter 3.3.7.

Looks like this is an already-known bug and many people from the native Android world have this issue: https://issuetracker.google.com/issues/242118185

For Android 12 users, there's [such fix](https://issuetracker.google.com/issues/242118185#comment5):
> Close this issue since it was fixed from android framework.
If the developer seeing this on eailer android verion(13-), the workaround might try to defer the finish call after activity resumed if that activity has register #setOnExitAnimationListener, or call #clearOnExitAnimationListener before finish and onResume.

It would be great to update the snippet in the docs with a fixed one that doesn't result in a critical crash for the whole family of (flagship) devices on Android 12.

**Comment by Albert221** [comment]
@huycozy I only have Pixel 2 XL with Android 11 :(

**Comment by huycozy** [comment]
I also try on `Realme 6, Android 11` but the splash screen displays well without this crash (also tried with `release` mode).

It would be great if someone can reproduce this and confirm the workaround mentioned above is applicable.
