### ISSUE TITLE
[local_auth] Available biometrics exception on Android app first launch

### ISSUE THREAD

**Issue by MrTilaris** [flutter/flutter#125214]
Android 13
Flutter 3.7.11
local_auth 2.1.6

There is available enrolled biometry at device. First launch of the app after clear installation. Catch exception when trying to call localAuth.getAvailableBiometrics().

There is exception with stacktrace below
```
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): java.lang.IllegalArgumentException: Unsupported value: 'WEAK' of type 'class io.flutter.plugins.localauth.Messages$AuthClassification'
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugins.localauth.Messages$LocalAuthApiCodec.writeValue(Messages.java:579)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugins.localauth.Messages$LocalAuthApiCodec.writeValue(Messages.java:579)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugins.localauth.Messages$LocalAuthApiCodec.writeValue(Messages.java:579)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugin.common.StandardMessageCodec.encodeMessage(StandardMessageCodec.java:76)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:222)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugins.localauth.Messages$LocalAuthApi$-CC.lambda$setup$3(Messages.java:704)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugins.localauth.Messages$LocalAuthApi$$ExternalSyntheticLambda3.onMessage(Unknown Source:2)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at android.os.Handler.handleCallback(Handler.java:942)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at android.os.Looper.loopOnce(Looper.java:226)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at android.os.Looper.loop(Looper.java:313)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at android.app.ActivityThread.main(ActivityThread.java:8747)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at java.lang.reflect.Method.invoke(Native Method)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics( 9824): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by stuartmorgan** [comment]
Pigeon doesn't handle `List<EnumType>` correctly, and unfortunately the list of enrolled biometrics in empty in our integration test environments. I've retracted the affected version of `local_auth_android` while I fix this.
