### ISSUE TITLE
DateTime fromMillisecondsSinceEpoch causing invalid range issue.

### ISSUE THREAD

**Issue by zahidch052** [flutter/flutter#125295]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
// sample server data: {index: 1, datetime: 20230421111500, epochtime: 1682075700000, open: 1.35296, high: 1.353065, low: 1.352655, close: 1.35305, dataset1: 0.0, dataset2: 0.0, dataset3: 0.0}
DateTime getEpochDatetime(int epochtime) {
    return DateTime.fromMillisecondsSinceEpoch(epochtime);
  }
```

### Expected results

Code : DateTime.fromMillisecondsSinceEpoch(serverTime)
this line should convert server epochtime from milliseconds to DateTime.  Sometimes it works fine and sometimes it gives exceptions.

### Actual results

Code : DateTime.fromMillisecondsSinceEpoch(serverTime)
this line should convert server epochtime from milliseconds to DateTime. 

But its giving exception

### Code sample

<details><summary>Code sample</summary>

```dart
// sample server data: {index: 1, datetime: 20230421111500, epochtime: 1682075700000, open: 1.35296, high: 1.353065, low: 1.352655, close: 1.35305, dataset1: 0.0, dataset2: 0.0, dataset3: 0.0}
DateTime getEpochDatetime(int epochtime) {
    return DateTime.fromMillisecondsSinceEpoch(epochtime);
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/21020363/233625985-5c439191-e5ca-4126-abb6-fbbd92fdd825.png">

</details>

### Logs

<details><summary>Logs</summary>

```console
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building LayoutBuilder:
RangeError (millisecondsSinceEpoch): Invalid value: Not in inclusive range -8640000000000000..8640000000000000: 638461934692680000

The relevant error-causing widget was: 
  SfCartesianChart SfCartesianChart:file:///Users/zahid/varcity-mobile3/lib/screens/forex_charts/candle_chart.dart:88:18
When the exception was thrown, this was the stack: 
#0      RangeError.checkValueInInterval (dart:core/errors.dart:327:7)
#1      DateTime._validateMilliseconds (dart:core-patch/date_patch.dart:59:18)
#2      new DateTime.fromMillisecondsSinceEpoch (dart:core-patch/date_patch.dart:38:13)
#3      _CandleSticksChartState.getEpochDatetime (package:VarCity/screens/forex_charts/candle_chart.dart:151:21)
#4      _CandleSticksChartState.build.<anonymous closure>.<anonymous closure> (package:VarCity/screens/forex_charts/candle_chart.dart:112:25)
#5      new XyDataSeries.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/chart_series/xy_data_series.dart:83:46)
#6      getChartPoint (package:syncfusion_flutter_charts/src/chart/utils/helper.dart:3180:18)
#7      ChartSeriesPanel._populateDataPoints (package:syncfusion_flutter_charts/src/chart/base/series_base.dart:190:25)
#8      ChartSeriesPanel.processData (package:syncfusion_flutter_charts/src/chart/base/series_base.dart:90:7)
#9      _ContainerAreaState._calculateBounds (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2573:41)
#10     _ContainerAreaState._initializeChart (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2557:5)
#11     _ContainerAreaState.build.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2548:34)
#12     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:119:77)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#14     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153:12)
#15     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2300:59)
#16     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1056:15)
#17     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2300:14)
#18     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228:7)
#19     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:313:5)
#20     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2027:7)
#21     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1020:18)
#22     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:516:19)
#23     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#24     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#25     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#26     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#27     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#28     _invoke (dart:ui/hooks.dart:145:13)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#30     _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================


```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
/Users/zahid/Documents/fluttersdk/flutter/bin/flutter doctor --verbose
[!] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-x64, locale en-PK)
    • Flutter version 3.7.11 on channel stable at /Users/zahid/Documents/fluttersdk/flutter
    ! The flutter binary is not on your path. Consider adding /Users/zahid/Documents/fluttersdk/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/zahid/Documents/fluttersdk/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (10 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/zahid/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 94665E31-5BDD-44BF-8C7C-0144050D5828 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.3.1 22E261 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
Process finished with exit code 0
```

</details>

**Comment by darshankawar** [comment]
@zahidch052 
I think you'll need to report this in dedicated repo: https://github.com/dart-lang/sdk/issues
Closing from here.
