### ISSUE TITLE
[local_auth_android 1.0.23] getAvailableBiometrics - Unhandled Exception: PlatformException

### ISSUE THREAD

**Issue by lukasgit** [flutter/flutter#125236]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

Possibly related to #125214 

@stuartmorgan 

### Steps to reproduce

`local_auth_android 1.0.23` - getAvailableBiometrics produces Unhandled Exception: PlatformException on some Android models.

`local_auth_android 1.0.21` - Does not produce PlatformException error.

### Expected results

`_availableBiometrics = await _localAuth.getAvailableBiometrics();` should not return PlatformException error.

### Actual results

PlatformException(channel-error, Unable to establish connection on channel., null, null)

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:local_auth/local_auth.dart';
import 'package:flutter/services.dart';
import 'dart:io' show Platform;


class BiometricsDataSource {
  final _localAuth = LocalAuthentication();
  List<BiometricType>? _availableBiometrics;

  bool isPlatformSupportedByLocalAuth =
      Platform.isAndroid || Platform.isIOS || Platform.isWindows;

  Future<bool> isAvailable() async {
    if (!isPlatformSupportedByLocalAuth) {
      return false;
    }

    late List<BiometricType> _availableBiometrics;
    try {
      _availableBiometrics = await _localAuth.getAvailableBiometrics();
    } on PlatformException catch (e) {
      debugPrint('[ERROR] local_auth getAvailableBiometrics: ${e}');
      return false;
    }

    if (await _localAuth.isDeviceSupported() &&
        await _localAuth.canCheckBiometrics &&
        _availableBiometrics.isNotEmpty
    ) {
      return true;
    } else {
      return false;
    }
  }
}
```

</details>

<details><summary>Logs</summary>

```console
I/flutter (12402): [ERROR] local_auth getAvailableBiometrics: PlatformException(channel-error, Unable to establish connection on channel., null, null)
```

</details>

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.11, on [redacted])
    • Flutter version 3.7.11 on channel stable at [redacted]
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (9 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
```

</details>

**Comment by huycozy** [comment]
Hi @lukasgit 
Please don't randomly mention someone because the issue will be addressed by the [triage](https://github.com/flutter/flutter/wiki/Triage) process.

As I can see, the current latest `local_auth_android` version is `local_auth_android: ^1.0.21` (see [Changelog](https://pub.dev/packages/local_auth_android/changelog)). It looks like you are using wrong plugin version, please see [this](https://stackoverflow.com/a/72889709/5921933) if it can help.

**Comment by lukasgit** [comment]
@huycozy read the threads and why @stuartmorgan was addressed, before you make an insulting an uninformed response. Stuart retracted the affected version of local_auth_android while he is fixing this issue, hence, he removed 1.0.23 from pub.dev

**Comment by huycozy** [comment]
Oops! It was my fault. Honestly, I didn't notice that issue (sorry about that). I also see a similar report [here](https://github.com/flutter/packages/pull/3748#issuecomment-1516141164) which is about `getEnrolledBiometrics`. 

When checking this with [local_auth example](https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth/example) and [local_auth_android example](https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth_android/example) (which has version `1.0.23`) on my device, I only see the crash happening with `getEnrolledBiometrics` but not with `getAvailableBiometrics`. And the PR https://github.com/flutter/packages/pull/3780 seems will fix for `getEnrolledBiometrics`. 

Can you please share the complete stack trace? Thank you!

<details>
<summary>Exception logs (getEnrolledBiometrics)</summary>

```bash
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): Failed to handle message
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): java.lang.IllegalArgumentException: Unsupported value: 'WEAK' of type 'class io.flutter.plugins.localauth.Messages$AuthClassification'
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApiCodec.writeValue(Messages.java:579)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApiCodec.writeValue(Messages.java:579)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApiCodec.writeValue(Messages.java:579)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.StandardMessageCodec.encodeMessage(StandardMessageCodec.java:76)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:222)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApi$-CC.lambda$setup$3(Messages.java:704)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApi$$ExternalSyntheticLambda3.onMessage(Unknown Source:2)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at android.os.Handler.handleCallback(Handler.java:938)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at android.os.Looper.loop(Looper.java:255)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at java.lang.reflect.Method.invoke(Native Method)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
I/flutter (26667): PlatformException(channel-error, Unable to establish connection on channel., null, null)
```
</details>

**Comment by huycozy** [comment]
Oops! It was my fault. Honestly, I didn't notice that issue (sorry about that). I also see a similar report https://github.com/flutter/packages/pull/3748#issuecomment-1516141164 which is about getEnrolledBiometrics.

When checking this with [local_auth example](https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth/example) and [local_auth_android example](https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth_android/example) (which has version 1.0.23) on my device, I can see the crash happening with `getEnrolledBiometrics`. 

On app-facing package, `getAvailableBiometrics` will call `getEnrolledBiometrics`, see [this](https://github.com/flutter/packages/blob/7e3f5da42e81f6d73789e112fa881acb7652f863/packages/local_auth/local_auth/lib/src/local_auth.dart#L74-L76).

The PR https://github.com/flutter/packages/pull/3780 seems will fix for getEnrolledBiometrics and may be landed on new version soon.

Thank you for your report!

<details>
<summary>Exception logs (getEnrolledBiometrics)</summary>

```bash
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): Failed to handle message
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): java.lang.IllegalArgumentException: Unsupported value: 'WEAK' of type 'class io.flutter.plugins.localauth.Messages$AuthClassification'
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApiCodec.writeValue(Messages.java:579)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApiCodec.writeValue(Messages.java:579)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApiCodec.writeValue(Messages.java:579)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.StandardMessageCodec.encodeMessage(StandardMessageCodec.java:76)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:222)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApi$-CC.lambda$setup$3(Messages.java:704)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugins.localauth.Messages$LocalAuthApi$$ExternalSyntheticLambda3.onMessage(Unknown Source:2)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at android.os.Handler.handleCallback(Handler.java:938)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at android.os.Looper.loop(Looper.java:255)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at java.lang.reflect.Method.invoke(Native Method)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/BasicMessageChannel#dev.flutter.pigeon.LocalAuthApi.getEnrolledBiometrics(26667): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
I/flutter (26667): PlatformException(channel-error, Unable to establish connection on channel., null, null)
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.12 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.10.0-10.0.pre.38, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0-10.0.pre.38 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7aa01f53f8 (38 minutes ago), 2023-04-20 22:31:11 -0400
    • Engine revision 122c3b3820
    • Dart version 3.1.0 (build 3.1.0-26.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Flamingo.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio Flamingo.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by stuartmorgan** [comment]
Closing as a duplicate given that full log.

@lukasgit In the future, please provide complete logs, not individual lines, when filing issues about exceptions.
