### ISSUE TITLE
PlatformException(UNAVAILABLE, BillingClient is unset. Try reconnecting., null, null)

### ISSUE THREAD

**Issue by j05u3** [flutter/flutter#125254]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

***Note***: I haven't tested these steps closely. I just had a big add-to-app flutter app on which it failed like this on my internal testing track (in Google Play Store), I took a look at the plugin code, issues and answers on stackoverflow and it all pointed that it should work, except that in my case it is an add-to-app scenario and I am killing (finish) the flutter activity at some points.

1. Setup an add-to-app flutter app.
2. Kill the Flutter activity and start a native activity.
3. Start the Flutter activity again reusing the flutter engine of the killed activity.
4. Call `await InAppPurchase.instance.isAvailable();` or try to purchase something.

### Expected results

Not to crash

### Actual results

It crashes with `Unhandled Exception: PlatformException(UNAVAILABLE, BillingClient is unset. Try reconnecting., null, null)
`

### Code sample

I am sorry, I didn't have time to create a minimal reproducible example. I'm just attaching the purchase function I am using.

<details><summary>Code sample</summary>

```dart

Future<bool> purchaseSubscriptionPlan(String productId) async {
  // fix from: https://stackoverflow.com/a/71730103/2469583
  final av = await InAppPurchase.instance.isAvailable();
  if (!av) {
    toast("InAppPurchase is not available");
    return false;
  }
  Set<String> kIds = <String>{productId};
  final ProductDetailsResponse response =
      await InAppPurchase.instance.queryProductDetails(kIds);
  if (response.notFoundIDs.isNotEmpty) {
    toast("Products not found: ${response.notFoundIDs}");
    return false;
  }
  List<ProductDetails> products = response.productDetails;
  final ProductDetails productDetails = products[0];
  final PurchaseParam purchaseParam =
      PurchaseParam(productDetails: productDetails);
  InAppPurchase.instance.buyNonConsumable(purchaseParam: purchaseParam);
  return true;
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
04-20 10:15:57.651  1949  2120 V DisplayPowerController[0]: Brightness [0.14998937] reason changing to: 'automatic', previous reason: 'automatic [ dim ]'.
04-20 10:15:57.710 25828 26047 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(UNAVAILABLE, BillingClient is unset. Try reconnecting., null, null)
04-20 10:15:57.710 25828 26047 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
04-20 10:15:57.710 25828 26047 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315)
04-20 10:15:57.710 25828 26047 E flutter : <asynchronous suspension>
04-20 10:15:57.710 25828 26047 E flutter : #2      BillingClient.isReady (package:in_app_purchase_android/src/billing_client_wrappers/billing_client_wrapper.dart:84)
04-20 10:15:57.710 25828 26047 E flutter : <asynchronous suspension>
04-20 10:15:57.710 25828 26047 E flutter : #3      purchaseSubscriptionPlan (package:flutter_module/util/billing/billing.dart:73)
04-20 10:15:57.710 25828 26047 E flutter : <asynchronous suspension>
04-20 10:15:57.710 25828 26047 E flutter : #4      _BillingTestingScreenState.build.<anonymous closure>.<anonymous closure> (package:flutter_module/testing/billing_testing.dart:35)
04-20 10:15:57.710 25828 26047 E flutter : <asynchronous suspension>
04-20 10:15:57.710 25828 26047 E flutter : 
04-20 10:15:59.222  1363 26530 I QC2Comp : [vp9D_20] Stats: Works: Q(25)/Done(19)| Work-Rate: Q(0.0/s Avg=0.0/s) Done(0.000/s Avg=0.009/s)| Stream: 30.30fps 1.2Mbps| Pending(8) i/p-done(0)
04-20 10:15:59.223  1363 26531 I QC2Comp : [vp9D_21] Stats: Works: Q(25)/Done(19)| Work-Rate: Q(0.0/s Avg=0.0/s) Done(0.000/s Avg=0.009/s)| Stream: 30.30fps 500.8Kbps| Pending(8) i/p-done(0)
04-20 10:15:59.502  1363 26565 W C2BqBuffer: last successful dequeue was 2106259802 us ago, 188737 consecutive failures

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.8, on macOS 12.6.1 21G217 darwin-x64, locale
    en-PE)
    • Flutter version 3.7.8 on channel stable at /Users/josue/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (4 weeks ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/josue/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/josue/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13
      (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS
      12.6.1 21G217 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available


```

</details>

**Comment by j05u3** [comment]
Btw, versions used:
```
in_app_purchase 3.1.5
in_app_purchase_android 0.2.5
```

**Comment by j05u3** [comment]
In case it helps, I did a fast fix by modifying the in_app_purchase_android code.

I added:
```dart
    try {
      await client.isReady();
    } catch (e, s) {
      print(e);
      debugPrintStack(stackTrace: s);
      _readyFuture = _connect();
      await _readyFuture;
    }

```

to these 2 functions: `runWithClient` and `runWithClientNonRetryable`. So it ended up looking like this (right part):

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/7897132/233499174-54bbd575-411b-43e2-9d4f-931e80824dcd.png">

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/7897132/233499273-c6f3b3a2-70c2-4daf-80eb-618b9fdd14f7.png">

**Comment by huycozy** [comment]
Thanks for the report @j05u3 
I try to replicate this case with reproduction steps at https://github.com/flutter/flutter/issues/33210#issuecomment-508190795 but the crash doesn't occur. It looks like the issue only can be reproducible in add-to-app scenario.

I will try creating a sample code for this, but can you please be more specific on these two steps? (Or provide a snippet code would be appriciated)

>Kill the Flutter activity and start a native activity.
Start the Flutter activity again reusing the flutter engine of the killed activity.

**Comment by j05u3** [comment]
> Thanks for the report @j05u3 I try to replicate this case with reproduction steps at [#33210 (comment)](https://github.com/flutter/flutter/issues/33210#issuecomment-508190795) but the crash doesn't occur. It looks like the issue only can be reproducible in add-to-app scenario.
> 
> I will try creating a sample code for this, but can you please be more specific on these two steps? (Or provide a snippet code would be appriciated)
> 
> > Kill the Flutter activity and start a native activity.
> > Start the Flutter activity again reusing the flutter engine of the killed activity.

Sure, my app starts with a splash screen activity coded in Java, then it navigates to my flutter activity (MyFlutterActivity) which starts flutter and in there I call to:

```dart
Future<bool?> open_my_activity() async {
  try {
    final bool result =
        await platform.invokeMethod('open_my_activity');
    return result;
  } catch (e, s) {
    debugPrint(e.toString());
    debugPrint(s.toString());
    await FirebaseCrashlytics.instance.recordError(e, s);
  }
  return null;
}
```

And I receive the method call like this inside MyFlutterActivity:

```java
if (call.method.equals("open_my_activity")) {

    startActivity(new Intent(getApplicationContext(),
        MyActivity.class));

    result.success(true);

    this.finish(); // killing this activity

}
```

Then I navigate again to MyFlutterActivity again and try to purchase and the issue happens. 

Btw, this is the code I use to navigate from native to flutter (i.e. open MyFlutterActivity): (see startFlutterActivity)

```java
    private static Intent getFlutterIntent(Activity activity) {
        FlutterActivity.CachedEngineIntentBuilder builder =
            new FlutterActivity.CachedEngineIntentBuilder(
                MyFlutterActivity.class,
                FLUTTER_ENGINE_ID);
        return builder
            .build(activity);
    }

    public static void startFlutterActivity(Activity activity) {
        FlutterUtil.startFlutterActivity(activity, null);
    }

    public static void startFlutterActivity(Activity activity, Integer requestCode) {
        warmUpEngine(activity);
        if (requestCode == null) {
            activity.startActivity(FlutterUtil.getFlutterIntent(activity));
        } else {
            activity.startActivityForResult(FlutterUtil.getFlutterIntent(activity), requestCode);
        }
    }
```

**Comment by huycozy** [comment]
Thanks for your response, I can reproduce this error from my end. It will take time to prepare a complete sample code, I will add it later but below is the steps I tried:

### Steps to reproduce
1. Clone and use `plugin` add-to-app sample at: https://github.com/flutter/samples/tree/main/add_to_app/plugin
2. Clone and use `in_app_purchase sample at: https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example (Use your own app id and purchase id to the sample)
3. In `add_to_app/plugin/flutter_module_using_plugin/lib/main.dart` (sample at step 1), add a button to navigate to IAP screen used in step 2
4. Run the Android native app from `add_to_app/plugin/android_using_plugin`
5. Click on `Launch Flutter activity` button -> IAP screen -> Check if all products can be shown and the status: "The store is available" on screen
6. Press back to previous screen and press `Exit this screen` to quit Flutter activity
7. Launch Flutter activity one more time and navigate to IAP screen
8. Check the status: "Trying to connect..." and the console log output has error as above

<details>
<summary>Demo video</summary>

https://user-images.githubusercontent.com/104349824/233639345-ddc56a93-e5de-4d5b-b2d1-8f4bcf5a9132.mov

</details>

Reproduced the issue on the latest version `in_app_purchase: ^3.1.5`. Labeling the issue for further insights!

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.12 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.10.0-10.0.pre.38, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0-10.0.pre.38 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7aa01f53f8 (38 minutes ago), 2023-04-20 22:31:11 -0400
    • Engine revision 122c3b3820
    • Dart version 3.1.0 (build 3.1.0-26.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Flamingo.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio Flamingo.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by j05u3** [comment]
> Thanks for your response, I can reproduce this error from my end. It will take time to prepare a complete sample code, I will add it later but below is the steps I tried:
> 
> ### Steps to reproduce
> 1. Clone and use `plugin` add-to-app sample at: https://github.com/flutter/samples/tree/main/add_to_app/plugin
> 2. Clone and use `in_app_purchase sample at: https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example (Use your own app id and purchase id to the sample)
> 3. In `add_to_app/plugin/flutter_module_using_plugin/lib/main.dart` (sample at step 1), add a button to navigate to IAP screen used in step 2
> 4. Run the Android native app from `add_to_app/plugin/android_using_plugin`
> 5. Click on `Launch Flutter activity` button -> IAP screen -> Check if all products can be shown and the status: "The store is available" on screen
> 6. Press back to previous screen and press `Exit this screen` to quit Flutter activity
> 7. Launch Flutter activity one more time and navigate to IAP screen
> 8. Check the status: "Trying to connect..." and the console log output has error as above
> 
> Demo video
> Reproduced the issue on the latest version `in_app_purchase: ^3.1.5`. Labeling the issue for further insights!
> 
> flutter doctor -v (stable and master)

Awesome, thanks 🙏

**Comment by Xezolpl** [comment]
> try { final bool available = await InAppPurchase.instance.isAvailable(); if (!available) { logger.e('initStoreInfo: The store cannot be reached or accessed'); return; } } on PlatformException catch (e) { logger.e('initStoreInfo: InAppPurchase = $e'); if (defaultTargetPlatform == TargetPlatform.android) { InAppPurchaseAndroidPlatform.registerPlatform(); } _initListenPurchase(); }

Workaround works for me

**Comment by xiaojianli** [comment]
I encountered the same problem：
1. Cold start the app
2. Go to the purchase page and call the isAvailable() and queryProductDetails() APIs
3. Then exit the application until MainActivity is destroyed
4. Open the app again and go to the purchase page
problems arise

Version:
in_app_purchase: ^3.2.3
in_app_purchase_android: ^0.4.0+2

We reused the Flutter engine.
```
public class MainActivity extends FlutterActivity {
    private static FlutterEngine flutterEngine;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {

        if (flutterEngine == null) {
            flutterEngine =  new FlutterEngineGroup(...).createAndRunEngine(...);
        }

        super.onCreate(savedInstanceState);
    }
}
```

When the activity is destroyed, the in_app_purchase_android plugin disconnects the BillingClient connection
```
  MethodCallHandlerImpl.java

  @Override
  public void onActivityDestroyed(@NonNull Activity activity) {
    if (this.activity == activity && this.applicationContext != null) {
      ((Application) this.applicationContext).unregisterActivityLifecycleCallbacks(this);
      endBillingClientConnection();
    }
  }
```
Since we reused the flutter engine, InAppPurchase.instance was not rebuilt，when calling the API again, the BillingClient in the plugin is null.
