### ISSUE TITLE
device doctor healthcheck error: b"error: protocol fault"

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#125306]
We are seeing this error pop up temporarily on bots in our devicelab pools (e.g. https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.staging&s=id). It goes away in a few seconds.

```Quarantined: device doctor healthcheck error: b"error: protocol fault (couldn't read status): Connection reset by peer\nUnhandled exception:\nExecutable adb failed with exit code 1.\n#0 fail (package:device_doctor/src/utils.dart:33)\n#1 eval (package:device_doctor/src/utils.dart:105)\n<asynchronous suspension>\n#2 Future.timeout.<anonymous closure> (dart:async/future_impl.dart:870)\n<asynchronous suspension>\n#3 AndroidDeviceDiscovery._deviceListOutputWithRetries.<anonymous closure> (package:device_doctor/src/android_device.dart:54)\n<asynchronous suspension>\n#4 RetryOptions.retry (package:retry/retry.dart:131)\n<asynchronous suspension>\n#5 AndroidDeviceDiscovery._deviceListOutputWithRetries (package:device_doctor/src/android_device.dart:52)\n<asynchronous suspension>\n#6 AndroidDeviceDiscovery.discoverDevices (package:device_doctor/src/android_device.dart:74)\n<asynchronous suspension>\n#7 AndroidDeviceDiscovery.checkDevices (package:device_doctor/src/android_device.dart:104)\n<asynchronous suspension>\n#8 main (file:///b/s/w/ir/x/w/cocoon/device_doctor/bin/main.dart:67)\n<asynchronous suspension>\n"```

**Comment by yusuf-goog** [comment]
cc @keyonghan
