### ISSUE TITLE
crash on Google Play Games Emulator(HPE).

### ISSUE THREAD

**Issue by 337240552** [flutter/flutter#125389]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run demo on HPE emulator.
2. Play the demo video.
3. crashed.
log detail
```
[SurfaceTexture-0-1488-0] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
2023-04-23 20:35:20.623  1488-1539  flutter                 io....er.plugins.videoplayerexample  E  [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
                                                                                                    	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
                                                                                                    	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
                                                                                                    	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:55)
2023-04-23 20:35:20.623  1488-1539  flutter                 io....er.plugins.videoplayerexample  A  [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1322)] Check failed: fml::jni::CheckException(env). 
2023-04-23 20:35:20.623  1488-1539  libc                    io....er.plugins.videoplayerexample  A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1539 (1.raster), pid 1488 (eoplayerexample)
```

### Expected results

Run as expected.

### Actual results

Crashed

### Code sample

<details><summary>Code sample</summary>

```dart
project demo code
```

</details>

### Screenshots or Video

no 

### Logs

<details><summary>Logs</summary>

```console
[SurfaceTexture-0-1488-0] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
2023-04-23 20:35:20.623  1488-1539  flutter                 io....er.plugins.videoplayerexample  E  [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
                                                                                                    	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
                                                                                                    	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
                                                                                                    	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:55)
2023-04-23 20:35:20.623  1488-1539  flutter                 io....er.plugins.videoplayerexample  A  [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1322)] Check failed: fml::jni::CheckException(env). 
2023-04-23 20:35:20.623  1488-1539  libc                    io....er.plugins.videoplayerexample  A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1539 (1.raster), pid 1488 (eoplayerexample)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19045.2604], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (version 4.1.0)
    X Unable to find bundled Java version.
[√] VS Code (version 1.71.2)
[√] Connected device (3 available)

! Doctor found issues in 2 categories.

```

</details>

**Comment by huycozy** [comment]
Maybe I haven't updated on this, can you please tell me how to create such an emulator currently? 
As I can see, it looks like HPE emulator hasn't been ready yet (https://developer.android.com/games/playgames/pg-emulator#download_and_install_the_developer_emulator)

Also, does this issue only happens on HPE emulator? What about other Android devices?
And please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Furthermore, you are using an old Flutter version (2.0.1). Please try upgrading your Flutter SDK to the latest and retry.

**Comment by huycozy** [comment]
This looks very similar to https://github.com/flutter/flutter/issues/116954. Please check it to see if it's also representing the same case (also use platform views)
