### ISSUE TITLE
SliverAppBar error

### ISSUE THREAD

**Issue by Alexays** [flutter/flutter#12545]
## Steps to Reproduce

Sometimes i just start the app and have this error :/

## Logs

```
I/flutter (16736): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (16736): The following ArgumentError was thrown during performLayout():
I/flutter (16736): Invalid argument(s): 50.0
I/flutter (16736): 
I/flutter (16736): When the exception was thrown, this was the stack:
I/flutter (16736): #0      _Double.clamp (dart:core-patch/dart:core/double.dart:147)
I/flutter (16736): #1      RenderSliverFloatingPinnedPersistentHeader.updateGeometry (package:flutter/src/rendering/sliver_persistent_header.dart:521)
I/flutter (16736): #2      RenderSliverFloatingPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:479)
I/flutter (16736): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #4      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:286)
I/flutter (16736): #5      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:979)
I/flutter (16736): #6      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:903)
I/flutter (16736): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #8      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #10     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #12     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #14     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #16     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #18     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #20     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124)
I/flutter (16736): #21     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:173)
I/flutter (16736): #22     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194)
I/flutter (16736): #23     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338)
I/flutter (16736): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #27     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #28     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1005)
I/flutter (16736): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #30     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:466)
I/flutter (16736): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #32     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #34     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #36     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #38     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #39     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2749)
I/flutter (16736): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #41     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #43     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:466)
I/flutter (16736): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #45     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #47     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #49     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #51     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (16736): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1962)
I/flutter (16736): #53     RenderView.performLayout (package:flutter/src/rendering/view.dart:142)
I/flutter (16736): #54     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1837)
I/flutter (16736): #55     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1126)
I/flutter (16736): #56     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:262)
I/flutter (16736): #57     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:581)
I/flutter (16736): #58     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:200)
I/flutter (16736): #59     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713)
I/flutter (16736): #60     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649)
I/flutter (16736): #61     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/rendering/binding.dart:286)
I/flutter (16736): #63     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:367)
I/flutter (16736): #64     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:401)
I/flutter (16736): #65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
I/flutter (16736): (elided one frame from package dart:async-patch)
I/flutter (16736): 
I/flutter (16736): The following RenderObject was being processed when the exception was fired:
I/flutter (16736):   _RenderSliverFloatingPinnedPersistentHeaderForWidgets#05bcf relayoutBoundary=up1 NEEDS-LAYOUT
I/flutter (16736):   NEEDS-PAINT
I/flutter (16736):   parentData: paintOffset=Offset(0.0, 0.0)
I/flutter (16736):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (16736):   scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 0.0, crossAxisDirection:
I/flutter (16736):   AxisDirection.right, viewportMainAxisExtent: 0.0)
I/flutter (16736):   geometry: null
I/flutter (16736):   maxExtent: 106.0
I/flutter (16736):   child position: null
I/flutter (16736):   effective scroll offset: 0.0
I/flutter (16736): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (16736):   RenderPhysicalModel#e4944 relayoutBoundary=up2 NEEDS-PAINT
I/flutter (16736):     _RenderInkFeatures#f3a00 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (16736):       RenderPositionedBox#4f37b relayoutBoundary=up4 NEEDS-PAINT
I/flutter (16736):         RenderPadding#5466b relayoutBoundary=up5 NEEDS-PAINT
I/flutter (16736):           RenderFlex#5ec36 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (16736): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (16736): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (16736): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
```

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/void/bin/flutter
    • Framework revision e697e5523f (5 hours ago), 2017-10-13 21:44:24 -0700
    • Engine revision 248af2d5b6
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • E6553                     • CB5A278YZJ    • android-arm • Android 7.1.2 (API 25)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
```

**Comment by Hixie** [comment]
Can you create a test app that demonstrates this problem?

**Comment by Alexays** [comment]
@Hixie i'm unable to reproduce this, it's happen some times, so i close this until i can reproduce this ?

**Comment by Hixie** [comment]
Sure.

We are definitely interested in fixing this if you can reproduce it. I've never seen this unfortunately. Please don't hesitate to file a new bug if you can repro.

**Comment by j4k0bk** [comment]
I get this from a SliverPersistentHeader whenever they keyboard is open

**Comment by najeira** [comment]
I get this error too, but I can not reproduce with the small code.
