### ISSUE TITLE
Flutter web: How to debug NoSuchMethodError

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#125431]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm building my flutter project for web however I'm getting `NoSuchMethodError` and I'm unsure how I can debug this. The app works in Android and before a rather large update (including updating all package dependencies) it deployed to web fine.

### Expected results

App to work in browser

### Actual results

Web page throws the following error:

```console
(index):115 Loading app from service worker.
main.dart.js:33514 Exception: something broke: NoSuchMethodError: method not found: 'gzv' on null
main.dart.js:33514     at Object.f (https://esc-management.web.app/main.dart.js:4799:3)
main.dart.js:33514     at ajw.$2 (https://esc-management.web.app/main.dart.js:118152:20)
main.dart.js:33514     at Qi.O (https://esc-management.web.app/main.dart.js:90920:12)
main.dart.js:33514     at lr.Y (https://esc-management.web.app/main.dart.js:95078:20)
main.dart.js:33514     at lr.n1 (https://esc-management.web.app/main.dart.js:95050:9)
main.dart.js:33514     at lr.n1 (https://esc-management.web.app/main.dart.js:95084:11)
main.dart.js:33514     at lr.IA (https://esc-management.web.app/main.dart.js:95020:6)
main.dart.js:33514     at lr.a6f (https://esc-management.web.app/main.dart.js:95021:19)
main.dart.js:33514     at akx.zH (https://esc-management.web.app/main.dart.js:94811:53)
main.dart.js:33514     at akx.axP (https://esc-management.web.app/main.dart.js:94833:20)
```

### Code sample

It's quite a large project, I don't have any specific code, I'm just running:

```
flutter build web
```

then deploying to firebase hosting

### Screenshots or Video

[You can try the web build here](https://esc-management.web.app)

### Logs

<details><summary>Logs & dependencies</summary>

```console
(index):115 Loading app from service worker.
main.dart.js:33514 Exception: something broke: NoSuchMethodError: method not found: 'gzv' on null
main.dart.js:33514     at Object.f (https://esc-management.web.app/main.dart.js:4799:3)
main.dart.js:33514     at ajw.$2 (https://esc-management.web.app/main.dart.js:118152:20)
main.dart.js:33514     at Qi.O (https://esc-management.web.app/main.dart.js:90920:12)
main.dart.js:33514     at lr.Y (https://esc-management.web.app/main.dart.js:95078:20)
main.dart.js:33514     at lr.n1 (https://esc-management.web.app/main.dart.js:95050:9)
main.dart.js:33514     at lr.n1 (https://esc-management.web.app/main.dart.js:95084:11)
main.dart.js:33514     at lr.IA (https://esc-management.web.app/main.dart.js:95020:6)
main.dart.js:33514     at lr.a6f (https://esc-management.web.app/main.dart.js:95021:19)
main.dart.js:33514     at akx.zH (https://esc-management.web.app/main.dart.js:94811:53)
main.dart.js:33514     at akx.axP (https://esc-management.web.app/main.dart.js:94833:20)
```

```console
jimmyff@jimmys-mbp-5 esc_management %  flutter pub deps -- --style=compact
Dart SDK 2.19.6
Flutter SDK 3.7.12
manage 1.0.0+2

dependencies:
- algolia 1.1.2 [meta http uuid universal_io]
- badges 3.1.1 [flutter]
- chroma 0.1.2 [vector_math logging image]
- clipboard 0.1.3 [flutter]
- cloud_firestore 4.5.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- csv 5.0.2
- cupertino_icons 1.0.5
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- equatable 2.0.5 [collection meta]
- esc_core 1.0.0 [intl http encrypt rocket_kit]
- extension_google_sign_in_as_googleapis_auth 2.0.9 [flutter google_sign_in googleapis_auth http meta]
- firebase_analytics 10.2.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.4.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 11.1.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_redux 0.10.0 [redux flutter]
- flutter_redux_navigation 0.7.1 [flutter redux]
- google_sign_in 6.1.0 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- googleapis 11.0.0 [_discoveryapis_commons http]
- googleapis_auth 1.4.0 [args crypto http http_parser js]
- http 0.13.5 [async http_parser meta path]
- image 4.0.15 [archive meta xml]
- image_cropper 3.0.3 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 0.8.7+4 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- intl 0.17.0 [clock path]
- page_transition 2.0.9 [flutter]
- redux 5.0.0
- rocket_kit 1.0.0 [geohash_plus openai_client uuid logging built_collection built_value redux intl]
- rocket_kit_flutter 0.0.1 [flutter built_collection built_value cloud_firestore_platform_interface cloud_firestore rocket_kit exif uuid flutter_image image blurhash_dart transparent_image material_design_icons_flutter intl badges]
- url_launcher 6.1.10 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- build_runner 2.3.3 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- build_web_compilers 3.2.7 [analyzer archive bazel_worker build build_config build_modules collection glob js logging path pool scratch_space source_maps source_span stack_trace]
- built_value_generator 8.4.4 [analyzer build build_config built_collection built_value collection source_gen]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _discoveryapis_commons 1.0.5 [http http_parser meta]
- _fe_analyzer_shared 58.0.0 [meta]
- _flutterfire_internals 1.1.1 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.10.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.0
- asn1lib 1.4.0
- async 2.10.0 [collection meta]
- bazel_worker 1.0.2 [async protobuf]
- blurhash_dart 1.2.1 [image]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_modules 4.0.7 [analyzer async bazel_worker build build_config collection crypto glob graphs json_annotation logging path scratch_space stream_transform]
- build_resolvers 2.2.0 [analyzer async build collection crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.7 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.4 [built_collection collection fixnum meta]
- characters 1.2.1
- checked_yaml 2.0.2 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 5.12.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.4.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.4.0 [built_collection built_value collection matcher meta]
- collection 1.17.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.2 [typed_data]
- dart_style 2.3.0 [analyzer args path pub_semver source_span]
- exif 3.1.4 [args collection convert json_annotation sprintf]
- fake_async 1.3.1 [clock collection]
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.4.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.2+1 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.13.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.3.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.6.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.3.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.2.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.4.1 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.1.0
- flutter_image 4.1.5 [flutter]
- flutter_plugin_android_lifecycle 2.0.9 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.2.0 [async path]
- geohash_plus 1.1.1
- glob 2.1.1 [async collection file path string_scanner]
- google_identity_services_web 0.2.1 [js meta]
- google_sign_in_android 6.1.11 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.1 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.12.0 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]
- graphs 2.2.0 [collection]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_cropper_for_web 1.0.3 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 3.0.3 [flutter plugin_platform_interface http]
- image_picker_android 0.8.6+7 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.12 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.7+3 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.3 [cross_file flutter http plugin_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.5 [meta]
- json_annotation 4.8.0 [meta]
- logging 1.1.1
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- material_design_icons_flutter 6.0.7096 [flutter]
- meta 1.8.0
- mime 1.0.4
- openai_client 0.0.7 [equatable http meta]
- package_config 2.1.0 [path]
- path 1.8.2
- petitparser 5.1.0 [meta]
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- protobuf 2.1.0 [fixnum collection meta]
- pub_semver 2.1.3 [collection meta]
- pubspec_parse 1.2.2 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- scratch_space 1.0.1 [build crypto path pool]
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.3 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.7 [analyzer async build dart_style glob path source_span yaml]
- source_maps 0.10.12 [source_span]
- source_span 1.9.1 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.1 [json_annotation]
- transparent_image 2.0.1
- typed_data 1.3.1 [collection]
- universal_io 2.2.0 [collection meta typed_data]
- url_launcher_android 6.0.27 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.4 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.16 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.5 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_math 2.1.4
- watcher 1.0.2 [async path]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- xml 6.2.2 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 12.6.2 21G320 darwin-arm64, locale en-GB)
    • Flutter version 3.7.12 on channel stable at /Users/jimmyff/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (7 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • Pixel 5 (mobile)            • 09021FDD40027X • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554  • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos          • darwin-arm64   • macOS 12.6.2 21G320 darwin-arm64
    • Chrome (web)                • chrome         • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!```

</details>

**Comment by danagbemava-nc** [comment]
Hi @jimmyff, can you try running your app in `profile` to see if you can get the non-minified stack trace? Usually, if the build fails in release mode (i.e flutter build web), it should also reproduce in `profile` mode.

**Comment by danagbemava-nc** [comment]
> I'm including the correct versions of the firebasejs libs (9.18.0) You can also see I'm including the firebase config in the as per the documentation which does include an apiKey in the config object. I guess you'll need me to take this to the flutterfire issue tracker?

Hi @jimmyff, yes, you'll need to report this on the flutterfire repo. 

Glad you've been able to discover the source of your issue. 

Closing from here. 

Thank you
