### ISSUE TITLE
`Matrix4.translate()` works on WEB when supplied with an `int` but crashes on Mobile

### ISSUE THREAD

**Issue by Sarraj-Sahar** [flutter/flutter#125585]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

To get the error :
1. Execute ````flutter run```` on the code sample on a Mobile device.

To see that the same code works fine : 

2. Execute ````flutter run```` on the code sample on a web browser.

Hi there, I know how to solve the following issue and I understand that we could pass a `double` value of `0.0` for the `x` param in the `Matrix4.identity()..translate` method, and that way the app wouldn't crash, but the question here is why does using a value of `0` work fine on web browsers but crashes on mobile? The code sample below runs without errors on a web browser but when tested on a mobile device, it throws an `[UnimplementedError]`. This can be confusing for new Flutter learners who had no issue getting their code to run successfully on a web browser but then encountered a sudden crash when testing on a mobile device. 

The error message doesn't provide clear instructions on how to fix the issue which can be simply avoided by stating something like: `Expected a value of type 'double', but got one of type 'int'`

I have noticed some users that have faced this exact same issue and were confused by the "sudden" crash even though they "didn't change anything in their code" That's why I am suggesting this change. It would help the users recognize what they did wrong faster.

### Expected results

 
 I have actually made a simple attempt to try and "solve this issue": simply adding a `Matrix4TypeError error` and calling it when the value of `x` is an `int` it would return this : 
 
 
 `═══════ Exception caught by widgets library ═══════════════════════════════════
The following message was thrown building OnTapTranslate(dirty, state: _OnTapTranslateState#a1a0d):
Expected a value of type 'double', but got one of type 'int'

The relevant error-causing widget was
OnTapTranslate
lib\main.dart:6
When the exception was thrown, this was the stack
#0      Matrix4.translate
package:vector_math/…/vector_math_64/matrix4.dart:682
#1      _OnTapTranslateState.build
package:hello_world/try_issues/gesture_matrix4.dart:13
#2      StatefulElement.build
package:flutter/…/widgets/framework.dart:5198
#3      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:5086
#4      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:5251
#5      Element.rebuild
package:flutter/…/widgets/framework.dart:4805
#6      ComponentElement._firstBuild
package:flutter/…/widgets/framework.dart:5068
#7      StatefulElement._firstBuild
package:flutter/…/widgets/framework.dart:5242
#8      ComponentElement.mount
package:flutter/…/widgets/framework.dart:5062`

### Actual results

<details><summary>Logs</summary>

```console
═══════ Exception caught by widgets library ═══════════════════════════════════
The following UnimplementedError was thrown building OnTapTranslate(dirty, state: _OnTapTranslateState#fe22e):
UnimplementedError

The relevant error-causing widget was
OnTapTranslate
lib\main.dart:6
When the exception was thrown, this was the stack
#0      Matrix4.translate
package:vector_math/…/vector_math_64/matrix4.dart:682
#1      _OnTapTranslateState.build
package:hello_world/try_issues/gesture_matrix4.dart:14
#2      StatefulElement.build
package:flutter/…/widgets/framework.dart:5198
#3      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:5086
#4      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:5251
#5      Element.rebuild
package:flutter/…/widgets/framework.dart:4805
#6      ComponentElement._firstBuild
package:flutter/…/widgets/framework.dart:5068
#7      StatefulElement._firstBuild
package:flutter/…/widgets/framework.dart:5242
#8      ComponentElement.mount
package:flutter/…/widgets/framework.dart:5062
...     Normal element mounting (27 frames)
#35     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3971
#36     Element.updateChild
package:flutter/…/widgets/framework.dart:3708
#37     RenderObjectToWidgetElement._rebuild
package:flutter/…/widgets/binding.dart:1253
#38     RenderObjectToWidgetElement.mount
package:flutter/…/widgets/binding.dart:1222
#39     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
package:flutter/…/widgets/binding.dart:1169
#40     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2720
#41     RenderObjectToWidgetAdapter.attachToRenderTree
package:flutter/…/widgets/binding.dart:1168
#42     WidgetsBinding.attachRootWidget
package:flutter/…/widgets/binding.dart:1001
#43     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
package:flutter/…/widgets/binding.dart:981
#47     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════
```

</details>

### Code sample

<details><summary>Code sample</summary>

```Dart
import 'package:flutter/material.dart';
void main() => runApp(OnTapTranslate());

class OnTapTranslate extends StatefulWidget {
  @override
  _OnTapTranslateState createState() => _OnTapTranslateState();
}

class _OnTapTranslateState extends State<OnTapTranslate> {
  bool isTapped = false;

  @override
  Widget build(BuildContext context) {
    final Matrix4 tapped = Matrix4.identity()..translate(0, -10, 0);
    final Matrix4 transform = isTapped ? tapped : Matrix4.identity();

    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Transform(
            transform: transform,
            alignment: FractionalOffset.center,
            child: GestureDetector(
              onTap: () {
                setState(() {
                  isTapped = !isTapped;
                });
              },
              child: Container(
                color: Colors.blue,
                height: 100.0,
                width: 200.0,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>video of the code working on a web browser</summary>

[translateOnWeb.webm](https://user-images.githubusercontent.com/82158584/234698491-3adfc99b-3335-4dba-b3fb-48e6ffadffc6.webm)

</details>
<details>
<summary>screenshot of the code crashing on a mobile device</summary>

![crash](https://user-images.githubusercontent.com/82158584/234698305-7c4f2dd6-9ebd-485c-8f19-8ad3b1a5c92f.jpg)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.9.0-17.0.pre.566, on Microsoft Windows [version 10.0.19045.2846], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] VS Code, 64-bit edition
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Seeing the same behavior as reported.

On mobile:

<details>
<summary> console error log </summary>

```

Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 3,616ms.

======== Exception caught by widgets library =======================================================
The following UnimplementedError was thrown building OnTapTranslate(dirty, state: _OnTapTranslateState#f8b59):
UnimplementedError

The relevant error-causing widget was: 
  OnTapTranslate OnTapTranslate:file:///Users/dhs/Documents/NCFlutter/flutter_app/lib/main.dart:2:23
When the exception was thrown, this was the stack: 
#0      Matrix4.translate (package:vector_math/src/vector_math_64/matrix4.dart:682:7)
#1      _OnTapTranslateState.build (package:flutter_app/main.dart:14:48)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5242:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (27 frames)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#37     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1253:16)
#38     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1222:5)
#39     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1169:18)
#40     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720:19)
#41     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1168:13)
#42     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1001:7)
#43     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:981:7)
#47     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following UnimplementedError was thrown building OnTapTranslate(dirty, state: _OnTapTranslateState#f8b59):
UnimplementedError

The relevant error-causing widget was: 
  OnTapTranslate OnTapTranslate:file:///Users/dhs/Documents/NCFlutter/flutter_app/lib/main.dart:2:23
When the exception was thrown, this was the stack: 
#0      Matrix4.translate (package:vector_math/src/vector_math_64/matrix4.dart:682:7)
#1      _OnTapTranslateState.build (package:flutter_app/main.dart:14:48)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1219:9)
#11     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:944:7)
#15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.12, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.12 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.10.0-15.0.pre.22, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.10.0-15.0.pre.22 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fdd6b87636 (44 minutes ago), 2023-04-27 00:29:23 -0400
    • Engine revision d9f91aadff
    • Dart version 3.1.0 (build 3.1.0-48.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by TahaTesser** [comment]
```console
======== Exception caught by widgets library =======================================================
The following UnimplementedError was thrown building OnTapTranslate(dirty, state: _OnTapTranslateState#f8b59):
UnimplementedError

The relevant error-causing widget was: 
  OnTapTranslate OnTapTranslate:file:///Users/dhs/Documents/NCFlutter/flutter_app/lib/main.dart:2:23
When the exception was thrown, this was the stack: 
#0      Matrix4.translate (package:vector_math/src/vector_math_64/matrix4.dart:682:7)
```


Looks like an UnimplementedError crash is coming from [vector_math](https://github.com/google/vector_math.dart) 

https://github.com/flutter/flutter/blob/1f602cb6ca116546dc16dec95cf36f68ccd117b5/packages/flutter/pubspec.yaml#L15

**Comment by wer-mathurin** [comment]
Any update on this?

**Comment by tirth-patel-nc** [comment]
# Triage Report

I was able to reproduce the issue using the provided code sample on both the `stable (3.29.3)` and master `(3.32.0-1.0.pre.463)` channels. I tested it on macOS desktop, iOS, and Android, and the issue occurs on all three platforms.

On web it works fine.

<details>
<summary>Code Sample (Same as OP)</summary>

```dart
import 'package:flutter/material.dart';
void main() => runApp(OnTapTranslate());

class OnTapTranslate extends StatefulWidget {
  @override
  _OnTapTranslateState createState() => _OnTapTranslateState();
}

class _OnTapTranslateState extends State<OnTapTranslate> {
  bool isTapped = false;

  @override
  Widget build(BuildContext context) {
    final Matrix4 tapped = Matrix4.identity()..translate(0, -10, 0);
    final Matrix4 transform = isTapped ? tapped : Matrix4.identity();

    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Transform(
            transform: transform,
            alignment: FractionalOffset.center,
            child: GestureDetector(
              onTap: () {
                setState(() {
                  isTapped = !isTapped;
                });
              },
              child: Container(
                color: Colors.blue,
                height: 100.0,
                width: 200.0,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Error Log</summary>

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following UnimplementedError was thrown building OnTapTranslate(dirty, state: _OnTapTranslateState#11730):
UnimplementedError

The relevant error-causing widget was:
    OnTapTranslate OnTapTranslate:file:///Users/tirthpatel/StudioProjects/hello_world/lib/main.dart:3:23

When the exception was thrown, this was the stack:
#0      Matrix4.translate (package:vector_math/src/vector_math_64/matrix4.dart:682:7)
#1      _OnTapTranslateState.build (package:hello_world/main.dart:15:48)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5823:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5715:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5697:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5865:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5691:5)
...     Normal element mounting (63 frames)
#71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4539:16)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:4004:18)
#73     _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:481:16)
#74     _RawViewElement.mount (package:flutter/src/widgets/view.dart:505:5)
...     Normal element mounting (15 frames)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4539:16)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:4004:18)
#91     RootElement._rebuild (package:flutter/src/widgets/binding.dart:1717:16)
#92     RootElement.mount (package:flutter/src/widgets/binding.dart:1686:5)
#93     RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1639:18)
#94     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3046:19)
#95     RootWidget.attach (package:flutter/src/widgets/binding.dart:1638:13)
#96     WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1376:27)
#97     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1361:5)
#98     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1347:7)
#102    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12)
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
The following UnimplementedError was thrown building OnTapTranslate(dirty, state: _OnTapTranslateState#11730):
UnimplementedError

The relevant error-causing widget was:
    OnTapTranslate OnTapTranslate:file:///Users/tirthpatel/StudioProjects/hello_world/lib/main.dart:3:23

When the exception was thrown, this was the stack:
#0      Matrix4.translate (package:vector_math/src/vector_math_64/matrix4.dart:682:7)
#1      _OnTapTranslateState.build (package:hello_world/main.dart:15:48)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5823:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5715:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#6      BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2694:15)
#7      BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056:18)
#9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1259:21)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1438:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1351:9)
#13     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1060:9)
#14     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:889:16)
#18     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12)
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 731 libraries in 82ms (compile: 10 ms, reload: 25 ms, reassemble: 23 ms).
```

</details>

<details>
  <summary>stable (3.29.3) - flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale
    en-IN) [970ms]
    • Flutter version 3.29.3 on channel stable at
      /Users/tirthpatel/Development/flutter_stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    [855ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [556ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [9ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available) [5.5s]
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.4.1 24E263 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 135.0.7049.115

[✓] Network resources [559ms]
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
  <summary>master (3.32.0-1.0.pre.463) - flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.32.0-1.0.pre.463, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [1,676ms]
    • Flutter version 3.32.0-1.0.pre.463 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 194fb17d2a (2 hours ago), 2025-05-07 20:28:23 -0700
    • Engine revision 194fb17d2a
    • Dart version 3.9.0 (build 3.9.0-97.0.dev)
    • DevTools version 2.46.0-dev.0

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [761ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [438ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [5.5s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 135.0.7049.115

[✓] Network resources [774ms]
    • All expected network resources are available.

• No issues found!
```

</details>
