### ISSUE TITLE
dart:async: Exception Caught by Scheduler Library

### ISSUE THREAD

**Issue by Azhng** [flutter/flutter#125579]
We observed the following message in our logs:

```
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1135 pos 20:
'node.isRepaintBoundary': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1135:20)
#3      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:518:19)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
(elided 5 frames from class _AssertionError and dart:async)
```

Flutter doctor 

```
$ flutter doctor                                                                                [16:30:24]
Building flutter tool...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3 22E252 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by darshankawar** [comment]
Based on the logs, it looks similar to https://github.com/flutter/flutter/issues/120874, so please follow-up in it for further updates. You may upvote the original issue for team's attention and priority.
Closing in favor of it.
