### ISSUE TITLE
Now when I'm using the latest google_sign_in_android: ^6.1.13

### ISSUE THREAD

**Issue by MohamedSafvanKP-MSIL** [flutter/flutter#125605]
Now when I'm using the latest google_sign_in_android: ^6.1.13
Unble to sync the native Android project.
getting following errors.
```
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/mohmedsafvankp/.pub-cache/hosted/pub.dev/google_sign_in_android-6.1.13/android/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':google_sign_in_android'.
> No signature of method: build_n3eadu0qz7ey661tsmy5sjq1.android() is applicable for argument types: (build_n3eadu0qz7ey661tsmy5sjq1$_run_closure2) values: [build_n3eadu0qz7ey661tsmy5sjq1$_run_closure2@73fd87a2]

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':google_sign_in_android'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
```

and 
```
Task failed with an exception.
-----------
* Where:
Script '/Users/mohmedsafvankp/flutter_sdk/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 463

* What went wrong:
A problem occurred configuring project ':google_sign_in_android'.
> Cannot invoke method substring() on null object

```

_Originally posted by @MohamedSafvanKP-MSIL in https://github.com/flutter/flutter/issues/125482#issuecomment-1524683735_

**Comment by aikonics** [comment]
I also encounter this problem when I updated a package and my app doesn't run anymore.

**Comment by BinarySatan** [comment]
i have the same problem

**Comment by danagbemava-nc** [comment]
Hi @MohamedSafvanKP-MSIL, please share the content of the following files

- `android/build.gradle`
- `android/gradle/wrapper/gradle-wrapper.properties`

Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by MohamedSafvanKP-MSIL** [comment]
hi @danagbemava-nc 
In build.gradle
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
and 
```
dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
```
In android/gradle/wrapper/gradle-wrapper.properties
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
```

note: Above is my native Android project setups.
Here I'm using Flutter as a module for my existing native application.

No issues facing while running modules alone.
But I'm facing then above issues only when I'm running the native application which is integrated with the Flutter module.

- flutter doctor -v
```
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2 22D49 darwin-arm64, locale en-IN)
    • Flutter version 3.7.8 on channel stable at /Users/mohmedsafvankp/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (5 weeks ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mohmedsafvankp/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • POCO M2 Pro (mobile) • 192.168.1.203:5555 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)      • macos              • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)         • chrome             • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by mustafa-707** [comment]
solved by doing 
```
flutter clean
flutter pub upgrade
```

and updating gradles 

in android/build.gradle 

```
    ext.kotlin_version = '1.7.10'
...

dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        ...
```

in android /gradle/wrapper

```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip

```

and finally in android/app/build.gradle 

```
   buildTypes {
        release {

            signingConfig signingConfigs.release
             //   useProguard true -------> remove this
            shrinkResources true. -------> add this 
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }

``` 
hope it solve the issue

**Comment by BinarySatan** [comment]
> 

Upgrading AGP requires a lot of adaptation work

**Comment by DayuEJ** [comment]
try limit all name start with io.io.flutter.plugins.xxxxx version number to use the previous version in pubspec.yaml, can fix it~

**Comment by stuartmorgan** [comment]
This an unexpected regression due to adding AGP 8.0 compatibility; https://github.com/flutter/flutter/issues/125621 tracks reverting the change; I expect that to happen later today.
