### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by WackyDawg** [flutter/flutter#125660]
## Command
```
flutter precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: Permission denied, errno = 13
```
#0      _Directory.createSync (dart:io/directory_impl.dart:129:7)
#1      _File.createSync (dart:io/file_impl.dart:303:14)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26:16)
#3      Initializer.createConfigFile (package:unified_analytics/src/initializer.dart:62:16)
#4      Initializer.run (package:unified_analytics/src/initializer.dart:110:7)
#5      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:314:17)
#6      new Analytics (package:unified_analytics/src/analytics.dart:111:12)
#7      getDefaultAnalytics (package:flutter_tools/src/globals.dart:97:38)
#8      analytics (package:flutter_tools/src/globals.dart:93:56)
#9      _exit (package:flutter_tools/runner.dart:278:15)
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:96:24)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.10.0-15.0.pre.17, on Kali GNU/Linux Rolling 5.16.0-kali7-amd64, locale en_NG)
    [32m•[39m Flutter version 3.10.0-15.0.pre.17 on channel master at /home/wackydawg/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision b3f3a0324a (26 hours ago), 2023-04-26 16:08:02 -0700
    [32m•[39m Engine revision cf975417ce
    [32m•[39m Dart version 3.1.0 (build 3.1.0-47.0.dev)
    [32m•[39m DevTools version 2.23.1

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[31m[✗][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Debian clang version 13.0.1-3+b2
    [31m✗[39m CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    [31m✗[39m ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    [31m✗[39m pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from https://www.freedesktop.org/wiki/Software/pkg-config/

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[32m[✓][39m Connected device (1 available)
    [32m•[39m Linux (desktop) •

**Comment by danagbemava-nc** [comment]
Labeling for further investigation as I cannot find any existing issues.
