### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Read-only file system, errno = 30

### ISSUE THREAD

**Issue by Marco-Nagy** [flutter/flutter#125775]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Read-only file system, errno = 30
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.openSync (dart:io/file_impl.dart:473:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:598:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:622:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:271:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:270:5)
#8      _renderTemplateToFile (package:flutter_tools/src/flutter_plugins.dart:33:8)
#9      _writeWebPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:960:3)
#10     injectBuildTimePluginFiles (package:flutter_tools/src/flutter_plugins.dart:1124:11)
<asynchronous suspension>
#11     WebProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:749:5)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:374:7)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1412:7)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
```
```
[!] Flutter (Channel stable, 3.7.12, on macOS 13.0 22A380 darwin-x64, locale en-US)
    • Flutter version 3.7.12 on channel stable at /Users/marconagy/Developer/flutter
    ! The flutter binary is not on your path. Consider adding /Users/marconagy/Developer/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/marconagy/Developer/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (13 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/marconagy/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 12cb4eb7a009f52b347b62ade7cb4854b926af72

**Comment by darshankawar** [comment]
Labeling this for team's attention and input, as I don't see an existing issue for same error.

/cc @christopherfujino

**Comment by christopherfujino** [comment]
@Marco-Nagy is your project directory mounted read-only? Or on some other unusual situation (network file share? usb-drive? tracked in dropbox?)

**Comment by Marco-Nagy** [comment]
It's read and write

**Comment by Marco-Nagy** [comment]
But located in another drive partition

**Comment by christopherfujino** [comment]
> But located in another drive partition

what file system does it use?

**Comment by Marco-Nagy** [comment]
> > But located in another drive partition
> 
> what file system does it use?

Not understand you 😔

**Comment by christopherfujino** [comment]
> > > But located in another drive partition
> > 
> > 
> > what file system does it use?
> 
> Not understand you pensive

Can you share the output of command:

`diskutil list`

(This will show all the partitions you have mounted on your system and what file system they are using). And also share which of these your app project is on.

**Comment by sixtusagbo** [comment]
I'm using Android emulator and I have storage permission enabled for the app yet I'm experiencing the same error.

**Comment by harshit82** [comment]
Using an emulator (Nexus 6 API 30)
Experienced a similar issue:

```
Exception has occurred. FileSystemException (FileSystemException: Cannot copy file to '#gsri%green_filter|18:6:50.jpg', path = '/data/user/0/com.example.calposcopy/cache/CAP181698039984606454.jpg' (OS Error: Read-only file system, errno = 30))
```
Debug Console:

```
E/flutter ( 4544): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot copy file to ' + #kje%green_filter|18:4:3.jpg', path = '/data/user/0/com.example.calposcopy/cache/CAP3854287394352118238.jpg' (OS Error: Read-only file system, errno = 30)
E/flutter ( 4544): #0      _checkForErrorResponse (dart:io/common.dart:55:9)
E/flutter ( 4544): #1      _File.copy.<anonymous closure> (dart:io/file_impl.dart:356:7)
E/flutter ( 4544): <asynchronous suspension>
E/flutter ( 4544): #2      _CameraAppState.saveToFolder
E/flutter ( 4544): <asynchronous suspension>
E/flutter ( 4544):
I/ExoPlayerImpl( 4544): Release eec0caa [ExoPlayerLib/2.18.1] [generic_x86, Android SDK built for x86, unknown, 30] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
I/CCodecConfig( 4544): query failed after returning 7 values (BAD_INDEX)
W/Codec2Client( 4544): query -- param skipped: index = 1342179345.
W/Codec2Client( 4544): query -- param skipped: index = 2415921170.
D/CCodecBuffers( 4544): [c2.android.mp3.decoder#511:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers( 4544):   int32_t channel-count = 2
D/CCodecBuffers( 4544):   string mime = "audio/raw"
D/CCodecBuffers( 4544):   int32_t sample-rate = 44100
D/CCodecBuffers( 4544): }
D/CCodecBufferChannel( 4544): [c2.android.mp3.decoder#511] MediaCodec discarded an unknown buffer
I/chatty  ( 4544): uid=10126(com.example.calposcopy) MediaCodec_loop identical 2 lines
D/CCodecBufferChannel( 4544): [c2.android.mp3.decoder#511] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder( 4544): onLastStrongRef automatically unlinking death recipients
D/BufferPoolAccessor2.0( 4544): bufferpool2 0xa9ecc4b8 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/32 (fetch/transfer)
Restarted application in 2,522ms.
D/BufferPoolAccessor2.0( 4544): bufferpool2 0xa9ecc4b8 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/32 (fetch/transfer)
D/BufferPoolAccessor2.0( 4544): evictor expired: 1, evicted: 1
I/flutter ( 4544): [{patient_id: ht21, patient_name: harshit, patient_age: 21, doctor_name: uttam, hospital_name: jipmer, margin_and_surface: null, vessel: null, lesion_size: null, acetic_acid: null, lugol_iodine: null, total_score: null, biopsy_taken: null, histopathology_report: null, lugol_iodine_img_path: null, green_filer_img_path: null, normal_saline_img_path: null, acetic_acid_img_path: null}, {patient_id: tat12, patient_name: tat, patient_age: 44, doctor_name: rst, hospital_name: trtr, margin_and_surface: null, vessel: null, lesion_size: null, acetic_acid: null, lugol_iodine: null, total_score: null, biopsy_taken: null, histopathology_report: null, lugol_iodine_img_path: null, green_filer_img_path: null, normal_saline_img_path: null, acetic_acid_img_path: null}, {patient_id: tet, patient_name: ttata, patient_age: 211, doctor_name: et, hospital_name: 4ty, margin_and_surface: null, vessel: null, lesion_size: null, acetic_acid: null, lugol_iodine: null, total_score: null, biopsy_taken: null, histopathology_report: null, l
I/flutter ( 4544): Data List =
I/flutter ( 4544): [{patient_id: ht21, patient_name: harshit, patient_age: 21, doctor_name: uttam, hospital_name: jipmer, margin_and_surface: null, vessel: null, lesion_size: null, acetic_acid: null, lugol_iodine: null, total_score: null, biopsy_taken: null, histopathology_report: null, lugol_iodine_img_path: null, green_filer_img_path: null, normal_saline_img_path: null, acetic_acid_img_path: null}, {patient_id: tat12, patient_name: tat, patient_age: 44, doctor_name: rst, hospital_name: trtr, margin_and_surface: null, vessel: null, lesion_size: null, acetic_acid: null, lugol_iodine: null, total_score: null, biopsy_taken: null, histopathology_report: null, lugol_iodine_img_path: null, green_filer_img_path: null, normal_saline_img_path: null, acetic_acid_img_path: null}, {patient_id: tet, patient_name: ttata, patient_age: 211, doctor_name: et, hospital_name: 4ty, margin_and_surface: null, vessel: null, lesion_size: null, acetic_acid: null, lugol_iodine: null, total_score: null, biopsy_taken: null, histopathology_report: null, l
I/flutter ( 4544): Patient Model =
I/flutter ( 4544): [Patient(patient_name: harshit, patient_id: ht21, patient_age: 21, doctor_name: uttam, hospital_name: jipmer, margin_and_surface: 0, vessel: 0, lesion_size: 0, acetic_acid: 0, lugol_iodine: 0, total_score: 0, biopsy_taken: , histopathology_report: , lugolIodineImagesPath: , greenFilterImagesPath: , normalSalineImagesPath: , aceticAcidImagesPath: ), Patient(patient_name: tat, patient_id: tat12, patient_age: 44, doctor_name: rst, hospital_name: trtr, margin_and_surface: 0, vessel: 0, lesion_size: 0, acetic_acid: 0, lugol_iodine: 0, total_score: 0, biopsy_taken: , histopathology_report: , lugolIodineImagesPath: , greenFilterImagesPath: , normalSalineImagesPath: , aceticAcidImagesPath: ), Patient(patient_name: ttata, patient_id: tet, patient_age: 211, doctor_name: et, hospital_name: 4ty, margin_and_surface: 0, vessel: 0, lesion_size: 0, acetic_acid: 0, lugol_iodine: 0, total_score: 0, biopsy_taken: , histopathology_report: , lugolIodineImagesPath: , greenFilterImagesPath: , normalSalineImagesPath: , aceticAcidIm
D/InputConnectionAdaptor( 4544): The input method toggled cursor monitoring on
D/InputConnectionAdaptor( 4544): The input method toggled cursor monitoring on
D/InputConnectionAdaptor( 4544): The input method toggled cursor monitoring on
D/InputConnectionAdaptor( 4544): The input method toggled cursor monitoring on
D/InputConnectionAdaptor( 4544): The input method toggled cursor monitoring on
I/TextInputPlugin( 4544): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper( 4544): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4544): getTextBeforeCursor on inactive InputConnection
D/InputConnectionAdaptor( 4544): The input method toggled cursor monitoring on
I/TextInputPlugin( 4544): Composing region changed by the framework. Restarting the input method.
D/InputConnectionAdaptor( 4544): The input method toggled cursor monitoring on
W/System  ( 4544): A resource failed to call release.
E/System  ( 4544): Uncaught exception thrown by finalizer
E/System  ( 4544): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$9H0ZdANdMrdpoq2bfIL2l3DVsKk@24b862f rejected from java.util.concurrent.ThreadPoolExecutor@464a43c[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 8]
E/System  ( 4544): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/System  ( 4544): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/System  ( 4544): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/System  ( 4544): 	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
E/System  ( 4544): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  ( 4544): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:587)
E/System  ( 4544): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:878)
E/System  ( 4544): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
E/System  ( 4544): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
E/System  ( 4544): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
E/System  ( 4544): 	at java.lang.Thread.run(Thread.java:923)
I/flutter ( 4544): {patient_name: dkhydy, patient_age: 5, patient_id: gsri, hospital_name: dst, doctor_name: rts}
I/flutter ( 4544): Directory path = /storage/emulated/0/Android/data/com.example.calposcopy/files/gsri_dkhydy

════════ Exception caught by widgets library ═══════════════════════════════════
The following LateError was thrown building CameraApp(dirty, state: _CameraAppState#09978):
LateInitializationError: Field 'controller' has not been initialized.

The relevant error-causing widget was
CameraApp
When the exception was thrown, this was the stack
#0      _CameraAppState.controller (package:CiARADS/camera.dart)
#1      _CameraAppState.build
#2      StatefulElement.build
#3      ComponentElement.performRebuild
#4      StatefulElement.performRebuild
#5      Element.rebuild
#6      ComponentElement._firstBuild
#7      StatefulElement._firstBuild
#8      ComponentElement.mount
...     Normal element mounting (220 frames)
#228    Element.inflateWidget
#229    MultiChildRenderObjectElement.inflateWidget
#230    Element.updateChild
#231    Element.updateChildren
#232    MultiChildRenderObjectElement.update
#233    Element.updateChild
#234    ComponentElement.performRebuild
#235    StatefulElement.performRebuild
#236    Element.rebuild
#237    StatefulElement.update
#238    Element.updateChild
#239    ComponentElement.performRebuild
#240    Element.rebuild
#241    ProxyElement.update
#242    Element.updateChild
#243    ComponentElement.performRebuild
#244    Element.rebuild
#245    ProxyElement.update
#246    _InheritedNotifierElement.update
#247    Element.updateChild
#248    ComponentElement.performRebuild
#249    StatefulElement.performRebuild
#250    Element.rebuild
#251    StatefulElement.update
#252    Element.updateChild
#253    ComponentElement.performRebuild
#254    Element.rebuild
#255    ProxyElement.update
#256    _InheritedNotifierElement.update
#257    Element.updateChild
#258    ComponentElement.performRebuild
#259    StatefulElement.performRebuild
#260    Element.rebuild
#261    StatefulElement.update
#262    Element.updateChild
#263    ComponentElement.performRebuild
#264    StatefulElement.performRebuild
#265    Element.rebuild
#266    StatefulElement.update
#267    Element.updateChild
#268    SingleChildRenderObjectElement.update
#269    Element.updateChild
#270    SingleChildRenderObjectElement.update
#271    Element.updateChild
#272    ComponentElement.performRebuild
#273    Element.rebuild
#274    ProxyElement.update
#275    Element.updateChild
#276    ComponentElement.performRebuild
#277    StatefulElement.performRebuild
#278    Element.rebuild
#279    BuildOwner.buildScope
#280    WidgetsBinding.drawFrame
#281    RendererBinding._handlePersistentFrameCallback
#282    SchedulerBinding._invokeFrameCallback
#283    SchedulerBinding.handleDrawFrame
#284    SchedulerBinding._handleDrawFrame
#285    _invoke (dart:ui/hooks.dart:170:13)
#286    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#287    _drawFrame (dart:ui/hooks.dart:140:31)
════════════════════════════════════════════════════════════════════════════════
I/Camera  ( 4544): close
I/Camera  ( 4544): open | onClosed
W/Camera  ( 4544): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
I/Camera  ( 4544): startPreview
I/Camera  ( 4544): CameraCaptureSession onConfigured
I/Camera  ( 4544): Updating builder settings
D/Camera  ( 4544): Updating builder with feature: ExposureLockFeature
D/Camera  ( 4544): Updating builder with feature: ExposurePointFeature
D/Camera  ( 4544): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 4544): Updating builder with feature: AutoFocusFeature
D/Camera  ( 4544): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 4544): updateNoiseReduction | currentSetting: fast
D/Camera  ( 4544): Updating builder with feature: FocusPointFeature
D/Camera  ( 4544): Updating builder with feature: ResolutionFeature
D/Camera  ( 4544): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 4544): Updating builder with feature: FlashFeature
D/Camera  ( 4544): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 4544): Updating builder with feature: FpsRangeFeature
I/Camera  ( 4544): refreshPreviewCaptureSession
I/Camera  ( 4544): runPrecaptureSequence
I/Camera  ( 4544): refreshPreviewCaptureSession
D/CameraCaptureCallback( 4544): CameraCaptureCallback | state: STATE_WAITING_PRECAPTURE_START | afState: 0 | aeState: 2
D/CameraCaptureCallback( 4544): CameraCaptureCallback | state: STATE_WAITING_PRECAPTURE_DONE | afState: 0 | aeState: 2
I/Camera  ( 4544): captureStillPicture
D/Camera  ( 4544): Updating builder with feature: ExposureLockFeature
D/Camera  ( 4544): Updating builder with feature: ExposurePointFeature
D/Camera  ( 4544): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 4544): Updating builder with feature: AutoFocusFeature
D/Camera  ( 4544): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 4544): updateNoiseReduction | currentSetting: fast
D/Camera  ( 4544): Updating builder with feature: FocusPointFeature
D/Camera  ( 4544): Updating builder with feature: ResolutionFeature
D/Camera  ( 4544): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 4544): Updating builder with feature: FlashFeature
D/Camera  ( 4544): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 4544): Updating builder with feature: FpsRangeFeature
I/Camera  ( 4544): sending capture request
D/CameraCaptureCallback( 4544): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 2
D/CameraCaptureCallback( 4544): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 2
D/CameraCaptureCallback( 4544): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
D/CameraCaptureCallback( 4544): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
I/Camera  ( 4544): unlockAutoFocus
I/Camera  ( 4544): refreshPreviewCaptureSession
I/Camera  ( 4544): onImageAvailable
I/ExoPlayerImpl( 4544): Init 2b0591f [ExoPlayerLib/2.18.1] [generic_x86, Android SDK built for x86, unknown, 30]
D/CCodec  ( 4544): allocate(c2.android.mp3.decoder)
I/CCodec  ( 4544): Created component [c2.android.mp3.decoder]
D/CCodecConfig( 4544): read media type: audio/mpeg
D/ReflectedParamUpdater( 4544): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 4544): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 4544): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4544): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4544): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4544): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 4544): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig( 4544): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig( 4544): c2 config diff is Dict {
D/CCodecConfig( 4544):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig( 4544):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig( 4544):   c2::u32 input.delay.value = 0
D/CCodecConfig( 4544):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig( 4544):   string output.media-type.value = "audio/raw"
D/CCodecConfig( 4544):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig( 4544):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig( 4544): }
D/CCodec  ( 4544): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 4544): no c2 equivalents for flags
D/CCodecConfig( 4544): config failed => CORRUPTED
W/Codec2Client( 4544): query -- param skipped: index = 1107298332.
D/CCodec  ( 4544): client requested max input size 4096, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  ( 4544): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  ( 4544): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 4544):   int32_t channel-count = 2
D/CCodec  ( 4544):   int32_t max-input-size = 8192
D/CCodec  ( 4544):   string mime = "audio/mpeg"
D/CCodec  ( 4544):   int32_t sample-rate = 44100
D/CCodec  ( 4544): } and output: AMessage(what = 0x00000000) = {
D/CCodec  ( 4544):   int32_t channel-count = 2
D/CCodec  ( 4544):   string mime = "audio/raw"
D/CCodec  ( 4544):   int32_t sample-rate = 44100
D/CCodec  ( 4544): }
W/Codec2Client( 4544): query -- param skipped: index = 1342179345.
W/Codec2Client( 4544): query -- param skipped: index = 2415921170.
E/FMQ     ( 4544): grantorIdx must be less than 3
E/FMQ     ( 4544): grantorIdx must be less than 3
D/CCodecBufferChannel( 4544): [c2.android.mp3.decoder#369] Created input block pool with allocatorID 16 => poolID 21 - OK (0)
D/BufferPoolAccessor2.0( 4544): bufferpool2 0xa9ecc4b8 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/32 (fetch/transfer)
D/BufferPoolAccessor2.0( 4544): Destruction - bufferpool2 0xa9ecc4b8 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 32, 88% unfetched
I/CCodecBufferChannel( 4544): [c2.android.mp3.decoder#369] Created output block pool with allocatorID 16 => poolID 35 - OK
D/CCodecBufferChannel( 4544): [c2.android.mp3.decoder#369] Configured output block pool ids 35 => OK
E/FMQ     ( 4544): grantorIdx must be less than 3
E/FMQ     ( 4544): grantorIdx must be less than 3
I/flutter ( 4544): Photo captured and saved to gallery
D/AudioTrack( 4544): getTimestamp_l(23): device stall time corrected using current time 9909811031300
D/AudioTrack( 4544): stop(23): called with 18432 frames delivered
D/BufferPoolAccessor2.0( 4544): bufferpool2 0xaa12bc58 : 5(40960 size) total buffers - 4(32768 size) used buffers - 0/5 (recycle/alloc) - 4/32 (fetch/transfer)
D/BufferPoolAccessor2.0( 4544): evictor expired: 2, evicted: 1
```

flutter doctor -v

```
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3570], locale en-IN)   
    • Flutter version 3.13.9 on channel stable at C:\FlutterSDK\flutter_windows_2.10.4-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (11 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-34, build-tools 31.0.0
    • Java binary at: E:\Applications\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components 

[√] Android Studio (version 2022.2)
    • Android Studio at E:\Applications\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.84.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 118.0.2088.76

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

Android manifest:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/> 
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.ACTION_MANAGE_WRITE_SETTINGS"/>
<uses-feature android:name="android.hardware.camera" />
    <application
        android:requestLegacyExternalStorage="true"
        android:label="CiARADS"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="false"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```
Error:
![image](https://github.com/flutter/flutter/assets/93983185/1452027f-d2ec-4a01-885b-02034ec7c20a)

**Comment by felipecastrosales** [comment]
I'm also facing with this error, using beta channel and Flutter 3.13.9 version. 

any feedbacks for this?

**Comment by MikeAngelE** [comment]
Am also facing this error. Channel main, 3.14.0-14.0.pre.82, Windows version 10 or higher. I can create and write a file through a php file within the same folder but am unable through a dart file using dart code.

example file: 'dartFile.dart' 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot open file, path = 'dartFile.dart' (OS Error: Read-only file system, errno = 30)

**Comment by s1dc0des** [comment]
same issue while setting up sambast.

**Comment by gxgl** [comment]
Hello,

the issue doesn't happen only on iOS and Android emulators but also on real hardware. At least on Android. In emulators is the same for IOS and Android. 

I have also tried out some workarounds from stackoverflow but didn't helped.

Best,
George

**Comment by delfme** [comment]
Hello, this issue occurs when the file is placed in a subfolder and subfolder is not created at first instance.
Example:
```
file = await File(filePath) // where filePath is **/folderName/fileName.ext**
...
final fileBytes = await file.readAsBytes(); // This throws error
```

But this code works:
```
file = await File(filePath).create(recursive: true) // where filePath is **/folderName/fileName.ext**
...
final fileBytes = await file.readAsBytes(); // It works as expected
```
