### ISSUE TITLE
I'm painting on a canvas and if a condition happens it should change to another page. When i try pushing a new page i get the following error:

### ISSUE THREAD

**Issue by Reconnact** [flutter/flutter#125882]
<details>
<summary> error log </summary>

```

══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for SnapshotController:
'package:flutter/src/rendering/object.dart': Failed assertion: line 2598 pos 12: 'owner == null ||
!owner!.debugDoingPaint': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RenderObject.markNeedsPaint (package:flutter/src/rendering/object.dart:2598:12)
#3      _RenderSnapshotWidget._onRasterValueChanged (package:flutter/src/widgets/snapshot_widget.dart:294:5)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:381:24)
#5      SnapshotController.allowSnapshotting= (package:flutter/src/widgets/snapshot_widget.dart:69:5)
#6      _ZoomTransitionBase.onAnimationStatusChange (package:flutter/src/material/page_transitions_theme.dart:805:20)
#7      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
#8      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
#9      ReverseAnimation._statusChangeHandler (package:flutter/src/animation/animations.dart:303:5)
#10     AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
#11     ReverseAnimation._statusChangeHandler (package:flutter/src/animation/animations.dart:303:5)
#12     AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
#13     AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
#14     ProxyAnimation.parent= (package:flutter/src/animation/animations.dart:215:9)
#15     TransitionRoute._setSecondaryAnimation (package:flutter/src/widgets/routes.dart:415:25)
#16     TransitionRoute._updateSecondaryAnimation (package:flutter/src/widgets/routes.dart:348:11)
#17     TransitionRoute.didChangeNext (package:flutter/src/widgets/routes.dart:320:5)
#18     NavigatorState._flushRouteAnnouncement (package:flutter/src/widgets/navigator.dart:4083:23)
#19     NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4023:5)
#20     NavigatorState._pushEntryAndRemoveUntil (package:flutter/src/widgets/navigator.dart:4743:5)
#21     NavigatorState.pushAndRemoveUntil (package:flutter/src/widgets/navigator.dart:4690:5)
#22     Navigator.pushAndRemoveUntil (package:flutter/src/widgets/navigator.dart:2242:34)
#23     GamePainter.showPossibleMoves (package:vektorrennen/app/gamePainter.dart:95:17)
#24     GamePainter.paint (package:vektorrennen/app/gamePainter.dart:58:5)
#25     RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:571:13)
#26     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:613:7)
#27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#29     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#32     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#35     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#36     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:415:5)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#40     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:653:11)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#43     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#44     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2110:15)
#45     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:564:14)
#46     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2097:21)
#47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#49     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#52     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#54     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#55     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#56     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1137:31)
#57     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:518:19)
#58     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#59     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#60     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#61     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#62     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#63     _invoke (dart:ui/hooks.dart:145:13)
#64     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#65     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)

The SnapshotController sending notification was:
  Instance of 'SnapshotController'
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2598 pos 12: 'owner == null || !owner!.debugDoingPaint': is not true.

Another exception was thrown: Build scheduled during frame.
E/flutter ( 3803): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2903 pos 18: '!navigator._debugLocked': is not true.
E/flutter ( 3803): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 3803): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 3803): #2      _RouteEntry.handlePush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:2903:18)
E/flutter ( 3803): #3      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:420:15)
E/flutter ( 3803): <asynchronous suspension>
E/flutter ( 3803): #4      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:419:5)
E/flutter ( 3803): <asynchronous suspension>
E/flutter ( 3803): 

```

</details>

**Comment by darshankawar** [comment]
@Reconnact 
In order to properly address the issue, please provide us a complete minimal reproducible code sample that throws the reported error log.
