### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: 系统找不到指定的文件。, errno = 2

### ISSUE THREAD

**Issue by mynamedaniel** [flutter/flutter#125992]
## Command
```
flutter create --template app --overwrite .
```

## Logs
FileSystemException: Cannot open file, OS Error: 系统找不到指定的文件。
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.openSync (dart:io/file_impl.dart:473:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:533:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:578:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#8      CreateBase._computeTemplateManifest (package:flutter_tools/src/commands/create_base.dart:674:37)
#9      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart:661:43)
#10     CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart)
#11     CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:487:25)
#12     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:512:29)
#13     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:351:37)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
    • Flutter version 3.7.12 on channel stable at D:\Software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\danie\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\danie\AppData\Local\Android
    • Java binary at: D:\Software\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    • Visual Studio at D:\Software\VisualStudio
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.2)
    • Android Studio at D:\Software\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 87.0.664.66

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by mynamedaniel** [comment]
Move flutter to disk C resolve this issue.
