### ISSUE TITLE
Setting stream handler when using kotlin fails due to lack of nullability annotations

### ISSUE THREAD

**Issue by tomaszpolanski** [flutter/flutter#12609]
## Steps to Reproduce

To reproduce the crash you only need to try to set a stream handler using kotlin in Android application:
```kotlin
        EventChannel(getFlutterView(), "ANY_CHANNEL").setStreamHandler(
                object : EventChannel.StreamHandler {
                    override fun onListen(arguments: Any, events: EventChannel.EventSink) {
                    }

                    override fun onCancel(arguments: Any) {
                    }
                }
        )
```
## Logs

This call will cause a similar exception:
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter arguments
   at tomek.com.podcast.MainActivity$onCreate$2.onListen(Unknown Source:2)
   at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:167)
   at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:155)
   at io.flutter.view.FlutterView.handlePlatformMessage(FlutterView.java:690)
   at android.os.MessageQueue.nativePollOnce(Native Method)
   at android.os.MessageQueue.next(MessageQueue.java:325)
   at android.os.Looper.loop(Looper.java:142)
   at android.app.ActivityThread.main(ActivityThread.java:6541)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

## Suggested solution
This issue is caused by lack of any nullability information in `onListen`:
```Kotlin
// Code from io.flutter.plugin.common.EventChannel
    public interface StreamHandler {
        void onListen(Object var1, EventChannel.EventSink var2);

        void onCancel(Object var1);
    }
```

When a handler is created with kotlin that assumes that `var1` in `onListen` is not nullable but it receives null, the mentioned exception happens. 
Would it be possible to add a nullability information to `StreamHandler` so kotlin would by default create the following code?

```Kotlin
        EventChannel(getFlutterView(), "ANY_CHANNEL").setStreamHandler(
                object : EventChannel.StreamHandler {
                    override fun onListen(arguments: Any?, events: EventChannel.EventSink) {
                    }

                    override fun onCancel(arguments: Any?) {
                    }
                }
        )
```
Here both `arguments` are of type `Any?`. Also, this solves my issue but other people using kotlin will for sure stumble upon this issue.

Thanks for the great work and amazing tool!

**Comment by cyanglaz** [comment]
@tomaszpolanski Hi, Thank you for the suggestion. It seems to be resolved when I tried. Could you try again to see if it is fixed?

**Comment by tomaszpolanski** [comment]
@cyanglaz Yes, I can confirm, this issue is no fixed

**Comment by cyanglaz** [comment]
> @cyanglaz Yes, I can confirm, this issue is no fixed

Im sorry. Is it fixed or not fixed? You mentioned it is not fixed but closed the issue, so I am a little confused.

**Comment by tomaszpolanski** [comment]
@cyanglaz Sorry, there was a typo. The issue is **now** fixed
