### ISSUE TITLE
Flutter won't build on droplet server anymore 

### ISSUE THREAD

**Issue by bksubhuti** [flutter/flutter#126139]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I created a droplet server.
I usually use 18.04 but have now tried three times.  I still want to use 18.04.. i have now wasted 2 hours building 18.04 , 20.04 and 22.04 and still get the same error.  I have built many times before.. there should be no reason why this does not work.

I have done this many times before to build an appimage.  However, it is not working anymore.

Normally I follow this recipe.
(I might be missing a step)
sudo apt update
sudo apt upgrade -y
sudo snap install flutter --classic
# i found another longer list below.. but snap installs ninja anyway (this was done based on many fails trying to make it work)
# old short list which still fails  
# sudo apt-get install libgtk-3-0 libblkid1 liblzma5 -y
sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
flutter doctor
#removed python-pip
sudo apt install p7zip-full p7zip-rar unzip python3-pip -y
pip install gdown

mkdir git
git clone https://github.com/bksubhuti/tipitaka-pali-reader.git
cd tipitaka-pali-reader/assets/database 
gdown 1REoQYE-TpJPXC6DFYKroCy6XwmJbAvcm
7z x tipitaka_pali.7z
sh split.sh
rm *.7z
# my old command had flutter build linux --desktop but that no longer works
flutter build linux --release

### Expected results

I want to build and have it work.  It does not work.

I get these results
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/tipitaka-pali-reader# flutter build linux --release
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎

💪 Building with sound null safety 💪

ERROR: Target kernel_snapshot failed: Exception
Building Linux application...
Build process failed
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/tipitaka-pali-reader#

### Actual results

root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/tipitaka-pali-reader# flutter build linux --release
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎

💪 Building with sound null safety 💪

ERROR: Target kernel_snapshot failed: Exception
Building Linux application...
Build process failed
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/tipitaka-pali-reader#

### Code sample

git code given

### Screenshots or Video

root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/tipitaka-pali-reader# flutter build linux --release
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎

💪 Building with sound null safety 💪

ERROR: Target kernel_snapshot failed: Exception
Building Linux application...
Build process failed
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/tipitaka-pali-reader#

### Logs

i don't see logs for building

### Flutter Doctor output

root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/tipitaka-pali-reader# flutter doctor
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on Ubuntu 22.04.2 LTS 5.15.0-67-generic, locale C.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 3 categories.
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/tipitaka-pali-reader#

**Comment by bksubhuti** [comment]
It should be noted..
flutter create test
flutter build linux --release also fails in the same way


```

root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~# flutter create test
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Creating project test...
Running "flutter pub get" in test...
Resolving dependencies in test... (1.3s)
+ async 2.10.0 (2.11.0 available)
+ boolean_selector 2.1.1
+ characters 1.2.1 (1.3.0 available)
+ clock 1.1.1
+ collection 1.17.0 (1.17.1 available)
+ cupertino_icons 1.0.5
+ fake_async 1.3.1
+ flutter 0.0.0 from sdk flutter
+ flutter_lints 2.0.1
+ flutter_test 0.0.0 from sdk flutter
+ js 0.6.5 (0.6.7 available)
+ lints 2.0.1 (2.1.0 available)
+ matcher 0.12.13 (0.12.16 available)
+ material_color_utilities 0.2.0 (0.5.0 available)
+ meta 1.8.0 (1.9.1 available)
+ path 1.8.2 (1.8.3 available)
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.9.1 (1.10.0 available)
+ stack_trace 1.11.0
+ stream_channel 2.1.1
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ test_api 0.4.16 (0.5.2 available)
+ vector_math 2.1.4
Changed 24 dependencies in test!
Wrote 127 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd test
  $ flutter run

Your application code is in test/lib/main.dart.

root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~# cd test
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/test# flutter build linux --release
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎

💪 Building with sound null safety 💪

ERROR: Target kernel_snapshot failed: Exception
Building Linux application...
Build process failed
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/test#
```

**Comment by huycozy** [comment]
Hi @bksubhuti 
Firstly, please try using Flutter as a normal user (not root) to see if there is any change. And next, please provide the complete output of `flutter run -v` so that we may verify the issue. Thank you!

**Comment by bksubhuti** [comment]
I am not skillful enough in linux commands even with chatgpt to get a user that has privileges.  The best I can do is still use sudo with that user but that still does root.  I'm a medium level linux user and used to have it on my own machine.  I have changed to windows because flutter development is not well supported by flutter devs.  So I go with a server on digitalocean.com .  
I was wondering.. can you create a server on DigitalOcean or anywhere as remote and run the proper commands and have a simple app build correctly?  I don't think it will work.  I have never had a problems building as root before.

I will have to wait for my linux helper to give me help on this before I can go further.  You can expedite this by trying to run this simple task on a fresh server.  I created now on 20.04.. i'll leave the server up for a little while longer.


sudo apt update
sudo apt upgrade -y
sudo snap install flutter --classic
sudo apt-get install libgtk-3-0 libblkid1 liblzma5 -y
flutter doctor
flutter create test
cd test
flutter build linux --release


I cannot do a flutter run -v on a droplet ssh server because it is a droplet remote ssh server.

droplet is 1gb ram server.  Maybe I used a bigger one before.. but I doubt it.
```
root@ubuntu-s-1vcpu-1gb-fra1-01:~/test# flutter doctor
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on Ubuntu 20.04.6 LTS 5.4.0-148-generic, locale C.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 3 categories.
root@ubuntu-s-1vcpu-1gb-fra1-01:~/test#
```



I did however run flutter build linux --release -v
The output is below:
```

root@ubuntu-s-1vcpu-1gb-fra1-01:~/test# flutter build linux --release -v
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
[  +30 ms] Unable to locate an Android SDK.
[  +11 ms] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] x86_64
[        ] executing: [/root/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +27 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
[        ] executing: [/root/snap/flutter/common/flutter/] git tag --points-at 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
[  +88 ms] Exit code 0 from: git tag --points-at 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
[        ] 3.7.12
[  +19 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +27 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +114 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +101 ms] Skipping pub get: version match.
[   +2 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/root/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +344 ms] Generating /root/test/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +81 ms] 💪 Building with sound null safety 💪
[  +31 ms] Building Linux application...
[  +11 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release
-DFLUTTER_TARGET_PLATFORM=linux-x64 /root/test/linux
[+1922 ms] -- The CXX compiler identification is Clang 10.0.0
[  +21 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[ +240 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- works
[   +3 ms] -- Detecting CXX compiler ABI info
[ +164 ms] -- Detecting CXX compiler ABI info - done
[  +18 ms] -- Detecting CXX compile features
[   +2 ms] -- Detecting CXX compile features - done
[  +66 ms] -- Found PkgConfig: /snap/flutter/current/usr/bin/pkg-config (found version "0.29.1")
[   +2 ms] -- Checking for module 'gtk+-3.0'
[  +33 ms] --   Found gtk+-3.0, version 3.24.20
[  +86 ms] -- Checking for module 'glib-2.0'
[  +15 ms] --   Found glib-2.0, version 2.64.6
[  +34 ms] -- Checking for module 'gio-2.0'
[  +14 ms] --   Found gio-2.0, version 2.64.6
[  +40 ms] -- Configuring done
[ +101 ms] -- Generating done
[   +2 ms] -- Build files have been written to: /root/test/build/linux/x64/release
[ +114 ms] executing: ninja -C build/linux/x64/release install
[   +8 ms] ninja: Entering directory `build/linux/x64/release'
[+57627 ms] [1/6] Generating /root/test/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/root/test/linux/flutter/ephemeral/flutter_linux/fl_value.h, /root/test/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/root/test/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +19 ms] FAILED: /root/test/linux/flutter/ephemeral/libflutter_linux_gtk.so
/root/test/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_engine.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_method_call.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_method_response.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h
/root/test/linux/flutter/ephemeral/flutter_linux/fl_value.h /root/test/linux/flutter/ephemeral/flutter_linux/fl_view.h
/root/test/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_
[   +9 ms] cd /root/test/build/linux/x64/release/flutter && /snap/flutter/130/usr/bin/cmake -E env
FLUTTER_ROOT=/root/snap/flutter/common/flutter PROJECT_DIR=/root/test DART_OBFUSCATION=false TRACK_WIDGET_CREATION=true
TREE_SHAKE_ICONS=true PACKAGE_CONFIG=/root/test/.dart_tool/package_config.json FLUTTER_TARGET=lib/main.dart
/root/snap/flutter/common/flutter/packages/flutter_tools/bin/tool_backend.sh linux-x64 Release
[        ]    Woah! You appear to be trying to run flutter as root.
[        ]    We strongly recommend running the flutter tool without superuser privileges.
[        ]   /
[   +4 ms] 📎
[   +5 ms] [  +21 ms] Unable to locate an Android SDK.
[   +4 ms] [  +18 ms] executing: uname -m
[        ] [   +4 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +2 ms] executing: [/root/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
[        ] [        ] executing: [/root/snap/flutter/common/flutter/] git tag --points-at
4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
[        ] [  +20 ms] Exit code 0 from: git tag --points-at 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
[        ] [        ] 3.7.12
[        ] [  +21 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +26 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +208 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [        ] origin/stable
[        ] [        ] executing: [/root/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [        ] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +41 ms] Initializing file store
[        ] [  +22 ms] Skipping target: gen_localizations
[        ] [  +30 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following
inputs have updated contents: /root/test/.dart_tool/package_config_subset}
[        ] [  +95 ms] gen_dart_plugin_registrant: Complete
[   +3 ms] [   +2 ms] unpack_linux: Starting due to {}
[        ] [ +206 ms] unpack_linux: Complete
[        ] [ +394 ms] kernel_snapshot: Starting due to {}
[   +1 ms] [   +8 ms] /root/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/root/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/root/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter
--no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --compact-async --aot --tfa
--packages /root/test/.dart_tool/package_config.json --output-dill
/root/test/.dart_tool/flutter_build/89961c524cd8ffdd6c069fa412edcffe/app.dill --depfile
/root/test/.dart_tool/flutter_build/89961c524cd8ffdd6c069fa412edcffe/kernel_snapshot.d --verbosity=error
package:test/main.dart
[   +6 ms] [+54515 ms] Persisting file store
[        ] [  +26 ms] Done persisting file store
[        ] [  +35 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:246:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:847:9)
[   +3 ms]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:785:32)
[   +1 ms]            <asynchronous suspension>
[   +5 ms]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:785:32)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[        ]            <asynchronous suspension>
[        ]            #7      _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:785:32)
[        ]            <asynchronous suspension>
[   +5 ms]            #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
[        ]            <asynchronous suspension>
[        ]            #9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:337:32)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1257:27)
[        ]            <asynchronous suspension>
[        ]            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[        ]            <asynchronous suspension>
[        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #15     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #18     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +58 ms] "flutter assemble" took 55,664ms.
[        ] [   +8 ms]
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[   +6 ms]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:354:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1257:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [   +9 ms] ensureAnalyticsSent: 0ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[  +38 ms] Building Linux application... (completed in 60.7s)
[   +6 ms] "flutter linux" took 61,422ms.
[  +13 ms] Build process failed
[  +12 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:183:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:76:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:86:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[   +4 ms] ensureAnalyticsSent: 0ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
root@ubuntu-s-1vcpu-1gb-fra1-01:~/test#
```

**Comment by bksubhuti** [comment]
Okay.. I doubled the memory.. it seems to work now.
That probably saved you lots of time.
Is this documented? 
I normally build on DO server because I make app images.  Even if I dual boot, I'd rather build on DO for appimages using a lower level Ubuntu release (as recommended by AppImage).
