### ISSUE TITLE
[Android] Can't build application if command is run outside of root folder

### ISSUE THREAD

**Issue by petrnymsa** [flutter/flutter#126143]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In our project we use monorepo approach where main application is under `apps` folder. E.g

```
apps/
├─ awesome_app/
│  ├─ lib/
│  │  ├─ main.dart
│  ├─ android/
│  ├─ ios/
packages/
scripts/
```

Run `flutter build` within project root folder like this
```console
flutter build apk -t apps/bakalari/lib/main.dart --release 
```

### Actual results

I am getting error

```console
Changing current working directory to: /Users/x/dev/AwesomeApp

Building without sound null safety ⚠️
Dart 3 will only support sound null safety, see https://dart.dev/null-safety

[!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.
```

If working directory is changed to `apps/awesome_app`, build works as expected 

```console
flutter build apk -t lib/main.dart --release 
```

### Logs

<details>
<summary>Logs</summary>

Details of failed build
```console
[!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new
project.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _exitWithUnsupportedProjectMessage (package:flutter_tools/src/android/gradle.dart:767:3)
           #2      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:239:7)
           #3      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:11)
           #4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:111:27)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[!] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale en-CZ)
    • Flutter version 3.7.12 on channel stable at /Users/petrnymsa/tools/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/petrnymsa/tools/flutter. Consider adding /Users/petrnymsa/tools/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/petrnymsa/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/petrnymsa/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by huycozy** [comment]
Hi @petrnymsa 
I'm building a project which has structure as below:

```
➜  main_not_in_root_dir_126143 tree -L 4
.
├── README.md
├── analysis_options.yaml
├── android
│   ├── app
│   │   ├── build.gradle
│   │   └── src
│   │       ├── debug
│   │       ├── main
│   │       └── profile
│   ├── build.gradle
│   ├── gradle
│   │   └── wrapper
│   │       ├── gradle-wrapper.jar
│   │       └── gradle-wrapper.properties
│   ├── gradle.properties
│   ├── gradlew
│   ├── gradlew.bat
│   ├── local.properties
│   ├── main_not_in_root_dir_126143_android.iml
│   └── settings.gradle
├── apps
│   └── abc
│       └── lib
│           └── main.dart
├── main_not_in_root_dir_126143.iml
├── pubspec.lock
└── pubspec.yaml
```

But it can build apk normally:

```
➜  main_not_in_root_dir_126143 flutter build apk  -t apps/abc/lib/main.dart --release

💪 Building with sound null safety 💪

Running Gradle task 'assembleRelease'...                           44.3s
✓  Built build/app/outputs/flutter-apk/app-release.apk (16.8MB).
```

Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by petrnymsa** [comment]
Maybe issue is that in root folder I have pubspec.yaml as well, beacuase Melos needs it?
https://github.com/petrnymsa/flutter_build_issue_126143
