### ISSUE TITLE
When errors are thrown in `initState`/`didUpdateWidget`/etc, the error message says "The following ... was thrown building Widget" which is confusing, thus may make message more explicit

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#126310]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Running the following demo code

<details>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  Never throwException() => throw Exception('deliberate');

  void prepareOnError() {
    final oldOnError = FlutterError.onError;
    FlutterError.onError = (details) {
      print('FlutterError.onError details=$details');
      print('current stack=${StackTrace.current}');
      oldOnError?.call(details);
    };
  }

  testWidgets('initState', (tester) async {
    print('------------------- SCENARIO: initState --------------------');
    prepareOnError();
    await tester.pumpWidget(Container(child: _MyWidget(onInitState: throwException)));
    expect(tester.takeException(), isNotNull);
  });

  testWidgets('build', (tester) async {
    print('------------------- SCENARIO: build --------------------');
    prepareOnError();
    await tester.pumpWidget(Container(child: _MyWidget(onBuild: throwException)));
    expect(tester.takeException(), isNotNull);
  });

  testWidgets('didUpdateWidget', (tester) async {
    print('------------------- SCENARIO: didUpdateWidget --------------------');
    prepareOnError();
    // pump twice to trigger didUpdateWidget
    await tester.pumpWidget(Container(child: _MyWidget(onDidUpdateWidget: throwException)));
    await tester.pumpWidget(Container(child: _MyWidget(onDidUpdateWidget: throwException)));
    expect(tester.takeException(), isNotNull);
  });

  testWidgets('dispose', (tester) async {
    print('------------------- SCENARIO: dispose --------------------');
    prepareOnError();
    await tester.pumpWidget(Container(child: _MyWidget(onDispose: throwException)));
    await tester.pumpWidget(Container());
    expect(tester.takeException(), isNotNull);
  });
}

class _MyWidget extends StatefulWidget {
  final VoidCallback? onInitState;
  final VoidCallback? onBuild;
  final VoidCallback? onDidUpdateWidget;
  final VoidCallback? onDispose;

  const _MyWidget({Key? key, this.onInitState, this.onBuild, this.onDidUpdateWidget, this.onDispose}) : super(key: key);

  @override
  State<_MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<_MyWidget> {
  @override
  void initState() {
    super.initState();
    widget.onInitState?.call();
  }

  @override
  void didUpdateWidget(covariant _MyWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    widget.onDidUpdateWidget?.call();
  }

  @override
  void dispose() {
    widget.onDispose?.call();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    widget.onBuild?.call();
    return const Placeholder();
  }
}
```

</details>

yields

<details>

```
/Users/tom/Main/yplusplus/.fvm/flutter_sdk/bin/flutter --no-color test --machine --start-paused test/a_test.dart
Testing started at 14:10 ...

------------------- SCENARIO: initState --------------------
FlutterError.onError details=══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following _Exception was thrown building Container:
Exception: deliberate

The relevant error-causing widget was:
  Container
  Container:file:///Users/tom/RefCode/bug/test/a_test.dart:19:29

When the exception was thrown, this was the stack:
#0      main.throwException (file:///Users/tom/RefCode/bug/test/a_test.dart:5:29)
#1      _MyWidgetState.initState (file:///Users/tom/RefCode/bug/test/a_test.dart:64:25)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5101:55)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (7 frames)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3676:20)
#12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#13     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1153:5)
#14     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1167:7)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#17     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1340:19)
#18     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#19     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#20     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#21     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1189:9)
#24     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#25     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1175:27)
#26     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:22)
#29     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#30     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:555:27)
#31     main.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:19:18)
#32     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

═════════════════════════════════════════════════════════════════
current stack=#0      main.prepareOnError.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:11:41)
#1      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1189:14)
#2      _reportException (package:flutter/src/widgets/framework.dart:6570:16)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4997:9)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3676:20)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#10     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1153:5)
#11     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1167:7)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#14     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1340:19)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#18     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1189:9)
#19     _rootRun (dart:async/zone.dart:1398:13)
#20     _CustomZone.run (dart:async/zone.dart:1300:19)
#21     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#22     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1175:27)
#23     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:22)
#24     _rootRun (dart:async/zone.dart:1398:13)
#25     _CustomZone.run (dart:async/zone.dart:1300:19)
#26     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#27     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:555:27)
#28     main.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:19:18)
#29     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
#30     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
------------------- SCENARIO: build --------------------
FlutterError.onError details=══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following _Exception was thrown building _MyWidget(dirty,
state: _MyWidgetState#16686):
Exception: deliberate

The relevant error-causing widget was:
  _MyWidget
  _MyWidget:file:///Users/tom/RefCode/bug/test/a_test.dart:26:46

When the exception was thrown, this was the stack:
#0      main.throwException (file:///Users/tom/RefCode/bug/test/a_test.dart:5:29)
#1      _MyWidgetState.build (file:///Users/tom/RefCode/bug/test/a_test.dart:81:21)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (7 frames)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3676:20)
#17     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#18     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1153:5)
#19     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1167:7)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#22     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1340:19)
#23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#26     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1189:9)
#29     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#30     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1175:27)
#31     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:22)
#34     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#35     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:555:27)
#36     main.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:26:18)
#37     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

═════════════════════════════════════════════════════════════════
current stack=#0      main.prepareOnError.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:11:41)
#1      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1189:14)
#2      _reportException (package:flutter/src/widgets/framework.dart:6570:16)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:9)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3676:20)
#17     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#18     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1153:5)
#19     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1167:7)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#22     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1340:19)
#23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#26     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1189:9)
#27     _rootRun (dart:async/zone.dart:1398:13)
#28     _CustomZone.run (dart:async/zone.dart:1300:19)
#29     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#30     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1175:27)
#31     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:22)
#32     _rootRun (dart:async/zone.dart:1398:13)
#33     _CustomZone.run (dart:async/zone.dart:1300:19)
#34     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#35     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:555:27)
#36     main.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:26:18)
#37     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
#38     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
------------------- SCENARIO: didUpdateWidget --------------------
FlutterError.onError details=══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following _Exception was thrown building Container:
Exception: deliberate

The relevant error-causing widget was:
  Container
  Container:file:///Users/tom/RefCode/bug/test/a_test.dart:35:29

When the exception was thrown, this was the stack:
#0      main.throwException (file:///Users/tom/RefCode/bug/test/a_test.dart:5:29)
#1      _MyWidgetState.didUpdateWidget (file:///Users/tom/RefCode/bug/test/a_test.dart:70:31)
#2      StatefulElement.update (package:flutter/src/widgets/framework.dart:5142:55)
#3      Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#6      StatelessElement.update (package:flutter/src/widgets/framework.dart:5044:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#9      RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1153:5)
#10     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1167:7)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#13     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1340:19)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#17     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1189:9)
#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#21     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1175:27)
#22     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:22)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#26     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:555:27)
#27     main.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:35:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

═════════════════════════════════════════════════════════════════
current stack=#0      main.prepareOnError.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:11:41)
#1      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1189:14)
#2      _reportException (package:flutter/src/widgets/framework.dart:6570:16)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4997:9)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#5      StatelessElement.update (package:flutter/src/widgets/framework.dart:5044:5)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#8      RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1153:5)
#9      RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1167:7)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#12     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1340:19)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#16     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1189:9)
#17     _rootRun (dart:async/zone.dart:1398:13)
#18     _CustomZone.run (dart:async/zone.dart:1300:19)
#19     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#20     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1175:27)
#21     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:22)
#22     _rootRun (dart:async/zone.dart:1398:13)
#23     _CustomZone.run (dart:async/zone.dart:1300:19)
#24     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#25     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:555:27)
#26     main.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:35:18)
<asynchronous suspension>
#27     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
------------------- SCENARIO: dispose --------------------
FlutterError.onError details=══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following _Exception was thrown while finalizing the widget
tree:
Exception: deliberate

When the exception was thrown, this was the stack:
#0      main.throwException (file:///Users/tom/RefCode/bug/test/a_test.dart:5:29)
#1      _MyWidgetState.dispose (file:///Users/tom/RefCode/bug/test/a_test.dart:75:23)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5179:11)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1960:13)
#4      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#5      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1969:25)
#6      BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2601:15)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3023:7)
#8      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1360:19)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#12     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1189:9)
#15     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#16     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1175:27)
#17     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:22)
#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#21     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:555:27)
#22     main.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:43:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
═════════════════════════════════════════════════════════════════
current stack=#0      main.prepareOnError.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:11:41)
#1      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1189:14)
#2      _reportException (package:flutter/src/widgets/framework.dart:6570:16)
#3      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3113:7)
#4      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1360:19)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#8      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1189:9)
#9      _rootRun (dart:async/zone.dart:1398:13)
#10     _CustomZone.run (dart:async/zone.dart:1300:19)
#11     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#12     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1175:27)
#13     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:22)
#14     _rootRun (dart:async/zone.dart:1398:13)
#15     _CustomZone.run (dart:async/zone.dart:1300:19)
#16     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#17     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:555:27)
#18     main.<anonymous closure> (file:///Users/tom/RefCode/bug/test/a_test.dart:43:18)
<asynchronous suspension>
#19     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>

```

</details>

In other words, when errors are thrown in `initState`/`didUpdateWidget`/etc, the error message says "The following ... was thrown building Widget" which is confusing. As we all know, in Flutter, "build", "initState", "didUpdateWidget", "dispose" are four *different* things. For example, when error is thrown in `dispose`, the message "thrown while finalizing the widget tree" is quite clear and expected. However, when thrown in initState/didUpdateWidget, the message "thrown building [some-widget-type]" makes people think that this error is thrown inside the `build()` function.

#### Proposal 1: Make message more explicit
Simply replace the string "thrown building Widget" with "thrown building Widget or initState/didUpdateWidget in its children".

#### Proposal 2: More error boundaries
Mimic how we catch errors for the "build" to add a few error try-catch blocks for initState/didUpdateWidget.
Drawback: May make performance worse.

**Comment by darshankawar** [comment]
@fzyzcjy 
I suggest to file a new issue for proposal 2 so that it can be tracked properly instead of filing multiple proposals in single issue.

Proposal 1 could be related to https://github.com/flutter/flutter/issues/103264.

**Comment by fzyzcjy** [comment]
Thanks, I see.

**Comment by goderbauer** [comment]
Closing this one as it looks like it was split up into https://github.com/flutter/flutter/issues/126325 and https://github.com/flutter/flutter/issues/126328.
