### ISSUE TITLE
Add checks to enforce build-phase code cannot touch layout-phase data?

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#126332]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

-

### Proposal

-

**Comment by ZelyTran** [comment]
Ok

**Comment by ZelyTran** [comment]
Helo

**Comment by darshankawar** [comment]
Treating this as a potential proposal.

**Comment by fzyzcjy** [comment]
### Quick update

Good news: the very naive sanity check catches #126312 using *only* existing tests
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781385992945961633/+/u/run_test.dart_for_framework_tests_shard_and_subshard_widgets/test_stdout

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building StatefulBuilder(state: _StatefulBuilderState#969d5):
'package:flutter/src/rendering/object.dart': Failed assertion: line 3124 pos 12:
'!BuildOwner.staticDebugBuilding': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack:
#2      RenderObject.sanityCheckNotBuilding (package:flutter/src/rendering/object.dart:3124:12)
#3      RenderProxyBoxMixin.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:142:5)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3180:24)
#5      EditableTextState._updateSizeAndTransform (package:flutter/src/widgets/editable_text.dart:3791:46)
#6      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:3154:7)
#7      EditableTextState.didUpdateWidget (package:flutter/src/widgets/editable_text.dart:2675:7)
#8      StatefulElement.update (package:flutter/src/widgets/framework.dart:5264:55)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3690:15)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5115:16)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5255:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4809:7)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2783:19)
#14     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1394:19)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1290:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1220:9)
#18     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1244:9)
#21     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#22     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1230:27)
#23     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:643:53)
#26     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#27     WidgetTester.pump (package:flutter_test/src/widget_tester.dart:643:27)
#28     main.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/widgets/editable_text_test.dart:3112:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

Bad news: Too many false positive. I may check them semi-manually to see whether there are more real bugs.

**Comment by fzyzcjy** [comment]
### Quick update: I explicitly constructed one bug (and expect that can catch a "series" of similar bugs)

Construction:

I manually looked at error logs of https://github.com/flutter/flutter/pull/126553. Take this error as an example:

<details>

```
00:16 +8: /b/s/w/ir/x/w/flutter/examples/api/test/widgets/editable_text/editable_text.on_content_inserted.0_test.dart: Image.memory displays inserted content                                          
00:17 +8: /b/s/w/ir/x/w/flutter/examples/api/test/widgets/editable_text/editable_text.on_content_inserted.0_test.dart: Image.memory displays inserted content                                          
00:17 +9: /b/s/w/ir/x/w/flutter/examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart: should show custom magnifier on drag (variant: TargetPlatform.iOS)                                
00:18 +9: /b/s/w/ir/x/w/flutter/examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart: should show custom magnifier on drag (variant: TargetPlatform.iOS)                                
00:18 +9: /b/s/w/ir/x/w/flutter/examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart: should show custom magnifier on drag (variant: TargetPlatform.iOS)                                
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building
_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#64433](dirty, state:
_OverlayEntryWidgetState#a4ef2):
'package:flutter/src/rendering/object.dart': Failed assertion: line 3124 pos 12:
'!BuildOwner.staticDebugBuilding': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///b/s/w/ir/x/w/flutter/examples/api/lib/widgets/text_magnifier/text_magnifier.0.dart:22:12

When the exception was thrown, this was the stack:
#2      RenderObject.sanityCheckNotBuilding (package:flutter/src/rendering/object.dart:3124:12)
#3      RenderProxyBoxMixin.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:142:5)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3180:24)
#5      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2617:39)
#6      SelectionOverlay.showToolbar.<anonymous closure> (package:flutter/src/widgets/text_selection.dart:1356:30)
#7      ContextMenuController.show.<anonymous closure> (package:flutter/src/widgets/context_menu_controller.dart:65:54)
#8      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:351:36)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:5202:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5090:15)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5255:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4809:7)
#13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5072:5)
#14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5246:11)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5066:5)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3975:16)
#17     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6574:36)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3712:18)
#19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6157:32)
#20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6599:17)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3690:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5115:16)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5255:11)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4809:7)
#25     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2783:19)
#26     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1394:19)
#27     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#28     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1290:15)
#29     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1220:9)
#30     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1244:9)
#33     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#34     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1230:27)
#35     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:702:23)
#38     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#39     WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:695:27)
#40     main.showMagnifier (file:///b/s/w/ir/x/w/flutter/examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart:60:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching node in the widget tree
  Actual: _WidgetTypeFinder:<zero widgets with type "CustomMagnifier" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///b/s/w/ir/x/w/flutter/examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart:90:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///b/s/w/ir/x/w/flutter/examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart line 90
The test description was:
  should show custom magnifier on drag (variant: TargetPlatform.iOS)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════

00:18 +9 -1: /b/s/w/ir/x/w/flutter/examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart: should show custom magnifier on drag (variant: TargetPlatform.iOS) [E]                         
  Test failed. See exception logs above.
  The test description was: should show custom magnifier on drag (variant: TargetPlatform.iOS)
  

To run this test again: /b/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test /b/s/w/ir/x/w/flutter/examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart -p vm --plain-name 'should show custom magnifier on drag (variant: TargetPlatform.iOS)'

00:18 +9 -1: /b/s/w/ir/x/w/flutter/examples/api/test/widgets/transitions/listenable_builder.0_test.dart: Changing focus changes border                                                                 
00:18 +9 -1: /b/s/w/ir/x/w/flutter/examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart: should show custom magnifier in TextDirection.rtl                                              
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building
```

</details>
