### ISSUE TITLE
license checker failing on missing `gclient revinfo`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#126447]
Right now the license checker is blocked because of this failure: https://github.com/flutter/flutter/issues/126441. https://github.com/flutter/engine/pull/41900 fixes that problem but it is now running into another problem where it can't find gclient.

## log
```
Verifying license script is still happy...
Using dart from: /b/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/dart

WARNING: There are 41 untracked/ignored files or directories in the flutter repository.
False positives may occur.
You can use 'git clean -dxf' in the flutter dir to clean out these files.
BUT, be warned that this will recursively remove all these files and directories:
ci/.dart_tool/
ci/pubspec.lock
flutter_frontend_server/.dart_tool/
flutter_frontend_server/pubspec.lock
impeller/golden_tests_harvester/.dart_tool/
impeller/golden_tests_harvester/pubspec.lock
lib/web_ui/.dart_tool/
lib/web_ui/pubspec.lock
prebuilts/
shell/vmservice/.dart_tool/
shell/vmservice/pubspec.lock
testing/android_background_image/.dart_tool/
testing/android_background_image/pubspec.lock
testing/benchmark/.dart_tool/
testing/benchmark/pubspec.lock
testing/dart/.dart_tool/
testing/dart/pubspec.lock
testing/litetest/.dart_tool/
testing/litetest/pubspec.lock
testing/scenario_app/.dart_tool/
testing/scenario_app/pubspec.lock
testing/smoke_test_failure/.dart_tool/
testing/smoke_test_failure/pubspec.lock
testing/symbols/.dart_tool/
testing/symbols/pubspec.lock
third_party/gn/
third_party/ninja/ninja
tools/android_lint/.dart_tool/
tools/android_lint/pubspec.lock
tools/api_check/.dart_tool/
tools/api_check/pubspec.lock
tools/clang_tidy/.dart_tool/
tools/clang_tidy/pubspec.lock
tools/const_finder/.dart_tool/
tools/const_finder/pubspec.lock
tools/githooks/.dart_tool/
tools/githooks/pubspec.lock
tools/licenses/.dart_tool/
tools/licenses/pubspec.lock
tools/path_ops/dart/.dart_tool/
tools/path_ops/dart/pubspec.lock

Dart SDK version: 3.0.0-417.4.beta (beta) (Tue May 2 10:26:14 2023 +0000) on "linux_x64"
unittest-suite-wait-for-done
Test "Block comments": Started
Test "Block comments": Passed
Test "Indenting blocks": Started
Test "Indenting blocks": Passed
Test "Leading blocks": Started
Test "Leading blocks": Passed
Test "Leading indented lines": Started
Test "Leading indented lines": Passed
Test "Leading indented blocks": Started
Test "Leading indented blocks": Passed
Test "Specific cases": Started
Test "Specific cases": Passed
unittest-suite-success
Finding files...
Detected changes to license tool. Forcing license collection for all components.
Collecting licenses for flutter

Collecting licenses for fuchsia

Collecting licenses for gpu

Collecting licenses for third_party

failure: ProcessException: No such file or directory
  Command: gclient revinfo
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      _RepositoryRootCertificatesDirectory.officialSourceLocation (package:licenses/main.dart:1604:56)
#4      MozillaLicense.toStringBody (package:licenses/licenses.dart:1314:93)
#5      groupLicenses (package:licenses/licenses.dart:219:44)
#6      _collectLicensesForComponent (package:licenses/main.dart:1951:41)
<asynchronous suspension>
#7      main (package:licenses/main.dart:2094:9)
<asynchronous suspension>

aborted.
```

## example
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781464925517288593/+/u/test:_licenses_check__2_/stdout

**Comment by gaaclarke** [comment]
This looks like the assumption is that gclient is on $PATH which doesn't seem to be the case: https://github.com/gaaclarke/engine/blob/d1c0d307bd4a89eb2dea480bbc14574d4e63970b/tools/licenses/lib/main.dart#L1604

**Comment by gaaclarke** [comment]
This is a new bot, no?

**Comment by sealesj** [comment]
It does look like a new bot, but I'm looking into the path issue

**Comment by godofredoc** [comment]
I'll take care of this one, for reference this is not a P0 as it is impacting a draft PR

**Comment by gaaclarke** [comment]
It's a p0 because it was affecting all PRs including a fix for opening back up rollers: https://github.com/flutter/engine/pull/41885

**Comment by gaaclarke** [comment]
To be clear, the draft PR was to unblock https://github.com/flutter/engine/pull/41885, but this issue was blocking the draft pr.

**Comment by godofredoc** [comment]
@gaaclarke please take a look at last week's announcement about infra priorities

**Comment by Hixie** [comment]
It seems to be affecting all PRs, e.g. https://github.com/flutter/engine/pull/41885 is also affected by this

If it is affecting all PRs, it is effectively closing the tree.

**Comment by godofredoc** [comment]
Thanks for the additional information, I'll send a CL to add gclient to path once the change is fully validated.

**Comment by godofredoc** [comment]
Validation build: https://chromium-swarm.appspot.com/task?id=621fdc7ddcf5f810

**Comment by godofredoc** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/44203

**Comment by godofredoc** [comment]
Infra issue is resolved, @gaaclarke please rebase your PR

**Comment by godofredoc** [comment]
Please send the bug back to me if the issue is not resolved yet

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/pull/41900 is passing its license checker test now, marking this closed.  thanks!
