### ISSUE TITLE
ListTile disappears with left side border and rounded corners

### ISSUE THREAD

**Issue by chris-herring** [flutter/flutter#126469]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Wrap a ListTile in a Container with a BoxDecoration with a left side border and rounded corners. The ListTile is not displayed. Remove the rounded corners. The ListTile displays.

### Expected results

I expect a ListTile to display with a left side border and rounded corners.

### Actual results

The ListTile is not displayed at all.

### Code sample

<details><summary>Code sample</summary>

Example here: [https://dartpad.dev/?id=b545f068068456c63725205797a7d24b](https://dartpad.dev/?id=b545f068068456c63725205797a7d24b)
```dart
import 'package:flutter/material.dart';

void main() => runApp(const Test1());

class Test1 extends StatelessWidget {
  const Test1({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          decoration: BoxDecoration(
            color: Colors.grey,
            border: const Border(
              left: BorderSide(
                color: Colors.green,
                width: 4
              )
            ),
            borderRadius: BorderRadius.circular(20),
          ),
          child: 
            const ListTile(
              title: Text("Item1")
            )
        )
      )
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
[✓] Flutter (Channel stable, 3.7.5, on macOS 12.5.1 21G83 darwin-arm64, locale en-AU)
    • Flutter version 3.7.5 on channel stable at /opt/homebrew/Caskroom/flutter/3.3.8/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (3 months ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • AE9B104C-346A-4BC0-B538-E55AC2DB0934 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @chris-herring, this is not an issue with `ListTile`. It will happen with even a `Text` widget. 

If you look in your logs, you should see an error that explains why it does not work. Below is the error I see when I run your code sample. 

What you're trying to do is not supported, which is why the widget does not display. 

Btw, you should upgrade to the latest version of flutter stable so that you can see a more detailed error. 

I'll be closing from here since this is an issue with your code sample. 

Thank you

PS: ListTile has its own shape property that you can use, so you shouldn't need to use a Container if you want to change the shape. You can also use a `ListTileTheme` if you want to provide the same styles to descendant ListTiles. 

<details>
<summary>logs</summary>

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
A borderRadius can only be given on borders with uniform colors and styles.

The following is not uniform:
BorderSide.color
BorderSide.style
The relevant error-causing widget was: 
  Container Container:file:///Users/nexus/projects/nevercode/foo/lib/main.dart:12:19
When the exception was thrown, this was the stack: 
#0      Border.paint.<anonymous closure> (package:flutter/src/painting/box_border.dart:626:9)
#1      Border.paint (package:flutter/src/painting/box_border.dart:634:6)
#2      _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:489:25)
#3      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2318:17)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#6      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2879:15)
#7      RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#11     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:664:11)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#15     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2076:15)
#16     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:562:14)
#17     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2063:21)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#25     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#26     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#27     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1147:31)
#28     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494:19)
#29     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#30     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#31     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1290:15)
#32     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1220:9)
#33     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:945:7)
#37     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#49314 relayoutBoundary=up1
...  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...  constraints: BoxConstraints(0.0<=w<=800.0, 0.0<=h<=600.0)
...  size: Size(81.0, 16.0)
...  decoration: BoxDecoration
...    color: MaterialColor(primary value: Color(0xff9e9e9e))
...    border: Border(left: BorderSide(color: MaterialColor(primary value: Color(0xff4caf50)), width: 4.0))
...    borderRadius: BorderRadius.circular(20.0)
...  configuration: ImageConfiguration(bundle: PlatformAssetBundle#21787(), devicePixelRatio: 2.0, locale: en_US, textDirection: TextDirection.ltr, platform: macOS)
RenderObject: RenderDecoratedBox#49314 relayoutBoundary=up1
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
  constraints: BoxConstraints(0.0<=w<=800.0, 0.0<=h<=600.0)
  size: Size(81.0, 16.0)
  decoration: BoxDecoration
    color: MaterialColor(primary value: Color(0xff9e9e9e))
    border: Border(left: BorderSide(color: MaterialColor(primary value: Color(0xff4caf50)), width: 4.0))
    borderRadius: BorderRadius.circular(20.0)
  configuration: ImageConfiguration(bundle: PlatformAssetBundle#21787(), devicePixelRatio: 2.0, locale: en_US, textDirection: TextDirection.ltr, platform: macOS)
...  child: RenderPadding#1d8ac relayoutBoundary=up2 NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=800.0, 0.0<=h<=600.0)
...    size: Size(81.0, 16.0)
...    padding: EdgeInsets(4.0, 0.0, 0.0, 0.0)
...    textDirection: ltr
...    child: RenderParagraph#ca1a7 relayoutBoundary=up3 NEEDS-PAINT
...      parentData: offset=Offset(4.0, 0.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=796.0, 0.0<=h<=600.0)
...      size: Size(77.0, 16.0)
...      textAlign: start
...      textDirection: ltr
...      softWrap: wrapping at box width
...      overflow: clip
...      locale: en_US
...      maxLines: unlimited
...      text: TextSpan
...        debugLabel: (englishLike bodyMedium 2014).merge(blackRedwoodCity bodyMedium)
...        inherit: false
...        color: Color(0xdd000000)
...        family: .AppleSystemUIFont
...        size: 14.0
...        weight: 400
...        baseline: alphabetic
...        decoration: TextDecoration.none
...        "Hello World"
====================================================================================================

```
</details>

**Comment by chris-herring** [comment]
Thanks, I did not see that error so will be sure to upgrade to get the detail.

The error makes sense. I've found a work around using ClipRect anyway. I originally used the shape property when just using rounded corners but then wanted to add a UI element to convey status.
