### ISSUE TITLE
License checker is tripping up on fuchsia artifacts

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#126441]
## error
```
Verifying license script is still happy...
Using dart from: /b/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/dart

WARNING: There are 40 untracked/ignored files or directories in the flutter repository.
False positives may occur.
You can use 'git clean -dxf' in the flutter dir to clean out these files.
BUT, be warned that this will recursively remove all these files and directories:
ci/.dart_tool/
ci/pubspec.lock
flutter_frontend_server/.dart_tool/
flutter_frontend_server/pubspec.lock
impeller/golden_tests_harvester/.dart_tool/
impeller/golden_tests_harvester/pubspec.lock
prebuilts/
shell/vmservice/.dart_tool/
shell/vmservice/pubspec.lock
testing/android_background_image/.dart_tool/
testing/android_background_image/pubspec.lock
testing/benchmark/.dart_tool/
testing/benchmark/pubspec.lock
testing/dart/.dart_tool/
testing/dart/pubspec.lock
testing/litetest/.dart_tool/
testing/litetest/pubspec.lock
testing/scenario_app/.dart_tool/
testing/scenario_app/pubspec.lock
testing/smoke_test_failure/.dart_tool/
testing/smoke_test_failure/pubspec.lock
testing/symbols/.dart_tool/
testing/symbols/pubspec.lock
third_party/gn/
third_party/ninja/ninja
tools/android_lint/.dart_tool/
tools/android_lint/pubspec.lock
tools/api_check/.dart_tool/
tools/api_check/pubspec.lock
tools/clang_tidy/.dart_tool/
tools/clang_tidy/pubspec.lock
tools/const_finder/.dart_tool/
tools/const_finder/pubspec.lock
tools/fuchsia/__pycache__/
tools/githooks/.dart_tool/
tools/githooks/pubspec.lock
tools/licenses/.dart_tool/
tools/licenses/pubspec.lock
tools/path_ops/dart/.dart_tool/
tools/path_ops/dart/pubspec.lock

Dart SDK version: 3.0.0-417.4.beta (beta) (Tue May 2 10:26:14 2023 +0000) on "linux_x64"
unittest-suite-wait-for-done
Test "Block comments": Started
Test "Block comments": Passed
Test "Indenting blocks": Started
Test "Indenting blocks": Passed
Test "Leading blocks": Started
Test "Leading blocks": Passed
Test "Leading indented lines": Started
Test "Leading indented lines": Passed
Test "Leading indented blocks": Started
Test "Leading indented blocks": Passed
Test "Specific cases": Started
Test "Specific cases": Passed
unittest-suite-success
Finding files...
../../../fuchsia/sdk/core.tar.gz!core.tar!/tools/arm64/aemu_internal/lib/pc-bios/efi-e1000.rom

failure: failed to handle ../../../fuchsia/sdk/core.tar.gz!core.tar!/tools/arm64/aemu_internal/lib/pc-bios/efi-e1000.rom
non-UTF8 data in ../../../fuchsia/sdk/core.tar.gz!core.tar!/tools/arm64/aemu_internal/lib/pc-bios/efi-e1000.rom
Original stack:
#0      _RepositorySourceFile._readFile (package:licenses/main.dart:79:7)
#1      new _RepositorySourceFile (package:licenses/main.dart:68:75)
#2      _RepositoryDirectory.createFile (package:licenses/main.dart:1061:14)
#3      _RepositoryDirectory.crawl (package:licenses/main.dart:966:43)
#4      new _RepositoryDirectory (package:licenses/main.dart:941:5)
#5      _RepositoryDirectory.createSubdirectory (package:licenses/main.dart:1025:12)
#6      _RepositoryDirectory.crawl (package:licenses/main.dart:961:46)
#7      new _RepositoryDirectory (package:licenses/main.dart:941:5)
```

## example 
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781470474024086689/+/u/test:_licenses_check/stdout

**Comment by gaaclarke** [comment]
This is blocking https://github.com/flutter/engine/pull/41885

**Comment by sealesj** [comment]
Looking into this

**Comment by gaaclarke** [comment]
@sealesj https://github.com/flutter/engine/pull/41900 solves the failure, but now we are blocked on the script not being able to find `gclient`: https://github.com/flutter/flutter/issues/126447

**Comment by gaaclarke** [comment]
Dropping the priority since it is no longer a blocker since engine_v2 license checker has been reverted: https://github.com/flutter/engine/pull/41903

**Comment by gaaclarke** [comment]
fixed in https://github.com/flutter/engine/pull/41942
