### ISSUE TITLE
[CupertinoPicker] Child paint transform happened to be null.

### ISSUE THREAD

**Issue by kishan-dhankecha** [flutter/flutter#126491]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Updated my old project environment sdk from `sdk: '>=2.19.6 <3.0.0'` to `sdk: '>=3.0.0 <4.0.0'`
2. Make sure all the dependencies are safe to use within that change
3. My app did build with no problems.
4. In my Home Screen I have CupertinoPicker which was working fine before this change
5. Now when I try to drag it gives me an error.

### Expected results

CupetinoPicker should work as before even after changing SDK constraints unless SDK changes CupertinoPicker widgets properties.

### Actual results

I get an error on dragging the picker to pick other items. 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      title: 'Flutter Demo',
      theme: CupertinoThemeData(),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 18),
          child: SizedBox(
            height: 120,
            child: CupertinoPicker(
              itemExtent: 55,
              diameterRatio: 0.9,
              onSelectedItemChanged: (idx) {
                //
              },
              children: ['1', '2', '3'].map<Widget>((diff) {
                return Center(child: Text(diff));
              }).toList(),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/68430205/44bf3108-a205-4a53-bd50-b77861f701e5

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on macOS in debug mode...
2023-05-11 08:18:03.768 xcodebuild[20261:160371] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006020-001A11360EE8C01E }
{ platform:macOS, arch:x86_64, id:00006020-001A11360EE8C01E }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
Connecting to VM Service at ws://127.0.0.1:58053/zqWb9056mo4=/ws
Reloaded 1 of 665 libraries in 167ms (compile: 35 ms, reload: 56 ms, reassemble: 52 ms).
Reloaded 1 of 665 libraries in 177ms (compile: 15 ms, reload: 65 ms, reassemble: 85 ms).

════════ Exception caught by gestures library ══════════════════════════════════
The following assertion was thrown while handling a pointer data packet:
Child paint transform happened to be null.

RenderListWheelViewport normally paints all of the children it has laid out.
Did you forget to update the ListWheelParentData.transform during the paint() call?
If this is intetional, change or remove this assertion accordingly.
When the exception was thrown, this was the stack
#0      RenderListWheelViewport._debugAssertValidPaintTransform
#1      RenderListWheelViewport.hitTestChildren
#2      RenderBox.hitTest
#3      RenderProxyBoxMixin.hitTestChildren
#4      RenderBox.hitTest
#5      RenderIgnorePointer.hitTest
#6      RenderProxyBoxMixin.hitTestChildren
#7      RenderBox.hitTest
#8      RenderProxyBoxMixin.hitTestChildren
#9      RenderProxyBoxWithHitTestBehavior.hitTest
#10     RenderProxyBoxMixin.hitTestChildren
#11     RenderProxyBoxWithHitTestBehavior.hitTest
#12     RenderProxyBoxMixin.hitTestChildren
#13     RenderProxyBoxWithHitTestBehavior.hitTest
#14     RenderProxyBoxMixin.hitTestChildren
#15     RenderBox.hitTest
#16     RenderProxyBoxMixin.hitTestChildren
#17     RenderBox.hitTest
#18     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>
#19     BoxHitTestResult.addWithPaintOffset
#20     RenderBoxContainerDefaultsMixin.defaultHitTestChildren
#21     RenderStack.hitTestChildren
#22     RenderBox.hitTest
#23     RenderProxyBoxMixin.hitTestChildren
#24     RenderBox.hitTest
#25     RenderProxyBoxMixin.hitTestChildren
#26     RenderBox.hitTest
#27     RenderShiftedBox.hitTestChildren.<anonymous closure>
#28     BoxHitTestResult.addWithPaintOffset
#29     RenderShiftedBox.hitTestChildren
#30     RenderBox.hitTest
#31     RenderShiftedBox.hitTestChildren.<anonymous closure>
#32     BoxHitTestResult.addWithPaintOffset
#33     RenderShiftedBox.hitTestChildren
#34     RenderBox.hitTest
#35     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>
#36     BoxHitTestResult.addWithPaintOffset
#37     RenderBoxContainerDefaultsMixin.defaultHitTestChildren
#38     RenderCustomMultiChildLayoutBox.hitTestChildren
#39     RenderBox.hitTest
#40     RenderProxyBoxMixin.hitTestChildren
#41     RenderBox.hitTest
#42     RenderProxyBoxMixin.hitTestChildren
#43     RenderBox.hitTest
#44     RenderPhysicalModel.hitTest
#45     RenderProxyBoxMixin.hitTestChildren
#46     RenderBox.hitTest
#47     RenderProxyBoxMixin.hitTestChildren
#48     RenderBox.hitTest
#49     RenderProxyBoxMixin.hitTestChildren
#50     RenderBox.hitTest
#51     RenderIgnorePointer.hitTest
#52     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>
#53     BoxHitTestResult.addWithPaintOffset
#54     RenderBoxContainerDefaultsMixin.defaultHitTestChildren
#55     RenderStack.hitTestChildren
#56     RenderBox.hitTest
#57     RenderProxyBoxMixin.hitTestChildren
#58     RenderBox.hitTest
#59     RenderProxyBoxMixin.hitTestChildren
#60     RenderFractionalTranslation.hitTestChildren.<anonymous closure>
#61     BoxHitTestResult.addWithPaintOffset
#62     RenderFractionalTranslation.hitTestChildren
#63     RenderFractionalTranslation.hitTest
#64     RenderProxyBoxMixin.hitTestChildren
#65     RenderFractionalTranslation.hitTestChildren.<anonymous closure>
#66     BoxHitTestResult.addWithPaintOffset
#67     RenderFractionalTranslation.hitTestChildren
#68     RenderFractionalTranslation.hitTest
#69     RenderProxyBoxMixin.hitTestChildren
#70     RenderBox.hitTest
#71     RenderProxyBoxMixin.hitTestChildren
#72     RenderBox.hitTest
#73     RenderProxyBoxMixin.hitTestChildren
#74     RenderBox.hitTest
#75     RenderOffstage.hitTest
#76     RenderProxyBoxMixin.hitTestChildren
#77     RenderBox.hitTest
#78     _RenderTheaterMixin.hitTestChildren.childHitTest
#79     BoxHitTestResult.addWithPaintOffset
#80     _RenderTheaterMixin.hitTestChildren
#81     RenderBox.hitTest
#82     RenderProxyBoxMixin.hitTestChildren
#83     RenderBox.hitTest
#84     RenderAbsorbPointer.hitTest
#85     RenderProxyBoxMixin.hitTestChildren
#86     RenderProxyBoxWithHitTestBehavior.hitTest
#87     RenderProxyBoxMixin.hitTestChildren
#88     RenderBox.hitTest
#89     RenderProxyBoxMixin.hitTestChildren
#90     RenderCustomPaint.hitTestChildren
#91     RenderBox.hitTest
#92     RenderProxyBoxMixin.hitTestChildren
#93     RenderBox.hitTest
#94     RenderProxyBoxMixin.hitTestChildren
#95     RenderBox.hitTest
#96     RenderProxyBoxMixin.hitTestChildren
#97     RenderTapRegionSurface.hitTest
#98     RenderProxyBoxMixin.hitTestChildren
#99     RenderBox.hitTest
#100    RenderProxyBoxMixin.hitTestChildren
#101    RenderBox.hitTest
#102    RenderProxyBoxMixin.hitTestChildren
#103    RenderBox.hitTest
#104    RenderProxyBoxMixin.hitTestChildren
#105    RenderBox.hitTest
#106    RenderView.hitTest
#107    RenderView.hitTestMouseTrackers
#108    RendererBinding.dispatchEvent.<anonymous closure>
#109    MouseTracker.updateWithEvent
#110    RendererBinding.dispatchEvent
#111    GestureBinding._handlePointerEventImmediately
#112    GestureBinding.handlePointerEvent
#113    GestureBinding._flushPointerEventQueue
#114    GestureBinding._handlePointerDataPacket
#115    _invoke1 (dart:ui/hooks.dart:158:13)
#116    PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#117    _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gestures library ══════════════════════════════════
Child paint transform happened to be null.
════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 665 libraries in 149ms (compile: 13 ms, reload: 65 ms, reassemble: 58 ms).
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-arm64, locale en-IN)
    • Flutter version 3.10.0 on channel stable at /Users/kishan/development/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/kishan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Thanks for the report! Reproduced this issue on the latest stable and master channels whilst it works as expected on the previous stable version `3.7.12`.

- stable 3.10.0: ❌
- master 3.11.0-2.0.pre.93: ❌
- stable 3.7.12: ✅

✅: No Issue ❌: Issue reproduced

### Additional info:
- The error is pointing to:
https://github.com/flutter/flutter/blob/0a63cd70f18e713bbfae4908d303daf76444d094/packages/flutter/lib/src/rendering/list_wheel_viewport.dart#L1070-L1080

- The issue will not occur if showing the picker inside a model like the sample code at [CupertinoPicker](https://api.flutter.dev/flutter/cupertino/CupertinoPicker-class.html).

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (35 hours ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-2.0.pre.93, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-2.0.pre.93 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 224c8b92dc (29 minutes ago), 2023-05-10 21:24:14 -0400
    • Engine revision ef771f95e9
    • Dart version 3.1.0 (build 3.1.0-94.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment]
it looks like `diameterRatio` causing this crash.  

Commenting this, get rid of it. This is also reproducible in the official code sample by adding the same line. 
```dart
      child: CupertinoPicker(
              itemExtent: 55,
           // diameterRatio: 0.9,
```

**Comment by TahaTesser** [comment]
This is regressed in https://github.com/flutter/flutter/pull/121342. The isn't reproducible before this a9c2c59b7ab16d7344d59ff21d8211fbb4b441ae

cc: @nt4f04uNd @Piinks

**Comment by nt4f04uNd** [comment]
Thank you for the report, seems like we were not right with this assertion :-(

Good news is this is a debug-only exception, it should affect the usability of the app in release mode.

Since this bug appears only with certain ListWheelScrollView configrations and it has already made its way into a stable release, there will not be much sense in reverting it, so my plan here is to fix this assertion and request cherry-picking it.

**Comment by kishan-dhankecha** [comment]
Thanks for this fast response.

One more thing @TahaTesser, Even after commenting `diameterRatio` I am getting the same error. Not every time as before, But It happens frequently.

![Actual Usecase Screenshot](https://github.com/flutter/flutter/assets/68430205/a7c481e1-e4d3-4d4f-ba75-9a1f9c46d687)

**Comment by kishan-dhankecha** [comment]
One more thing, Once this Exception is thrown and I continue to scroll or do anything on my application's window I get another exception related to mouse events.


<details>
<summary>Console Output</summary>

```console
Restarted application in 241ms.

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
Child paint transform happened to be null.

RenderListWheelViewport normally paints all of the children it has laid out.
Did you forget to update the ListWheelParentData.transform during the paint() call?
If this is intetional, change or remove this assertion accordingly.
When the exception was thrown, this was the stack
#0      RenderListWheelViewport._debugAssertValidPaintTransform
#1      RenderListWheelViewport.hitTestChildren
#2      RenderBox.hitTest
#3      RenderProxyBoxMixin.hitTestChildren
#4      RenderBox.hitTest
#5      RenderIgnorePointer.hitTest
#6      RenderProxyBoxMixin.hitTestChildren
#7      RenderBox.hitTest
#8      RenderProxyBoxMixin.hitTestChildren
#9      RenderProxyBoxWithHitTestBehavior.hitTest
#10     RenderProxyBoxMixin.hitTestChildren
#11     RenderProxyBoxWithHitTestBehavior.hitTest
#12     RenderProxyBoxMixin.hitTestChildren
#13     RenderProxyBoxWithHitTestBehavior.hitTest
#14     RenderProxyBoxMixin.hitTestChildren
#15     RenderBox.hitTest
#16     RenderProxyBoxMixin.hitTestChildren
#17     RenderBox.hitTest
#18     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>
#19     BoxHitTestResult.addWithPaintOffset
#20     RenderBoxContainerDefaultsMixin.defaultHitTestChildren
#21     RenderStack.hitTestChildren
#22     RenderBox.hitTest
#23     RenderProxyBoxMixin.hitTestChildren
#24     RenderBox.hitTest
#25     RenderProxyBoxMixin.hitTestChildren
#26     RenderBox.hitTest
#27     RenderShiftedBox.hitTestChildren.<anonymous closure>
#28     BoxHitTestResult.addWithPaintOffset
#29     RenderShiftedBox.hitTestChildren
#30     RenderBox.hitTest
#31     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>
#32     BoxHitTestResult.addWithPaintOffset
#33     RenderBoxContainerDefaultsMixin.defaultHitTestChildren
#34     RenderFlex.hitTestChildren
#35     RenderBox.hitTest
#36     RenderProxyBoxMixin.hitTestChildren
#37     RenderBox.hitTest
#38     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>
#39     BoxHitTestResult.addWithPaintOffset
#40     RenderBoxContainerDefaultsMixin.defaultHitTestChildren
#41     RenderFlex.hitTestChildren
#42     RenderBox.hitTest
#43     RenderShiftedBox.hitTestChildren.<anonymous closure>
#44     BoxHitTestResult.addWithPaintOffset
#45     RenderShiftedBox.hitTestChildren
#46     RenderBox.hitTest
#47     RenderShiftedBox.hitTestChildren.<anonymous closure>
#48     BoxHitTestResult.addWithPaintOffset
#49     RenderShiftedBox.hitTestChildren
#50     RenderBox.hitTest
#51     RenderShiftedBox.hitTestChildren.<anonymous closure>
#52     BoxHitTestResult.addWithPaintOffset
#53     RenderShiftedBox.hitTestChildren
#54     RenderBox.hitTest
#55     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>
#56     BoxHitTestResult.addWithPaintOffset
#57     RenderBoxContainerDefaultsMixin.defaultHitTestChildren
#58     RenderStack.hitTestChildren
#59     RenderBox.hitTest
#60     RenderProxyBoxMixin.hitTestChildren
#61     RenderBox.hitTest
#62     RenderProxyBoxMixin.hitTestChildren
#63     RenderBox.hitTest
#64     RenderProxyBoxMixin.hitTestChildren
#65     RenderBox.hitTest
#66     RenderProxyBoxMixin.hitTestChildren
#67     RenderBox.hitTest
#68     RenderIgnorePointer.hitTest
#69     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>
#70     BoxHitTestResult.addWithPaintOffset
#71     RenderBoxContainerDefaultsMixin.defaultHitTestChildren
#72     RenderStack.hitTestChildren
#73     RenderBox.hitTest
#74     RenderProxyBoxMixin.hitTestChildren
#75     RenderBox.hitTest
#76     RenderProxyBoxMixin.hitTestChildren
#77     RenderFractionalTranslation.hitTestChildren.<anonymous closure>
#78     BoxHitTestResult.addWithPaintOffset
#79     RenderFractionalTranslation.hitTestChildren
#80     RenderFractionalTranslation.hitTest
#81     RenderProxyBoxMixin.hitTestChildren
#82     RenderFractionalTranslation.hitTestChildren.<anonymous closure>
#83     BoxHitTestResult.addWithPaintOffset
#84     RenderFractionalTranslation.hitTestChildren
#85     RenderFractionalTranslation.hitTest
#86     RenderProxyBoxMixin.hitTestChildren
#87     RenderBox.hitTest
#88     RenderProxyBoxMixin.hitTestChildren
#89     RenderBox.hitTest
#90     RenderProxyBoxMixin.hitTestChildren
#91     RenderBox.hitTest
#92     RenderOffstage.hitTest
#93     RenderProxyBoxMixin.hitTestChildren
#94     RenderBox.hitTest
#95     _RenderTheaterMixin.hitTestChildren.childHitTest
#96     BoxHitTestResult.addWithPaintOffset
#97     _RenderTheaterMixin.hitTestChildren
#98     RenderBox.hitTest
#99     RenderProxyBoxMixin.hitTestChildren
#100    RenderBox.hitTest
#101    RenderAbsorbPointer.hitTest
#102    RenderProxyBoxMixin.hitTestChildren
#103    RenderProxyBoxWithHitTestBehavior.hitTest
#104    RenderProxyBoxMixin.hitTestChildren
#105    RenderBox.hitTest
#106    RenderProxyBoxMixin.hitTestChildren
#107    RenderBox.hitTest
#108    RenderProxyBoxMixin.hitTestChildren
#109    RenderTapRegionSurface.hitTest
#110    RenderProxyBoxMixin.hitTestChildren
#111    RenderBox.hitTest
#112    RenderProxyBoxMixin.hitTestChildren
#113    RenderBox.hitTest
#114    RenderProxyBoxMixin.hitTestChildren
#115    RenderBox.hitTest
#116    RenderView.hitTest
#117    RenderView.hitTestMouseTrackers
#118    MouseTracker._findAnnotations
#119    MouseTracker.updateAllDevices.<anonymous closure>
#120    MouseTracker._deviceUpdatePhase
#121    MouseTracker.updateAllDevices
#122    RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure>
#123    SchedulerBinding._invokeFrameCallback
#124    SchedulerBinding.handleDrawFrame
#125    SchedulerBinding._handleDrawFrame
#126    _invoke (dart:ui/hooks.dart:142:13)
#127    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#128    _drawFrame (dart:ui/hooks.dart:112:31)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 195 pos 12: '!_debugDuringDeviceUpdate': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 195 pos 12: '!_debugDuringDeviceUpdate': is not true.
════════════════════════════════════════════════════════════════════════════════
```

The below part is repeated for every mouse move event:
```console
════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 195 pos 12: '!_debugDuringDeviceUpdate': is not true.
════════════════════════════════════════════════════════════════════════════════

```

</details>


<details>
<summary>Screenshots / Video demonstration</summary>
[Video on G-Drive](https://drive.google.com/file/d/1tPNcmvV4R89iiMcBvUULfiGs7z127ciY/view?usp=sharing)
</details>

**Comment by kishan-dhankecha** [comment]
> One more thing, Once this Exception is thrown and I continue to scroll or do anything on my application's window I get another exception related to mouse events.
> 
> Console Output
> Screenshots / Video demonstration

@nt4f04uNd  What about this? Is it also solved by this PR?

**Comment by nt4f04uNd** [comment]
> The below part is repeated for every mouse move event:
> ```console
> ════════ Exception caught by scheduler library ═════════════════════════════════
> 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 195 pos 12: '!_debugDuringDeviceUpdate': is not true.
> ════════════════════════════════════════════════════════════════════════════════
> 
> ```
>
> @nt4f04uNd What about this? Is it also solved by this PR?

I didn't specifically fix this error, but it looks like it was caused by the error from your initial report.
Also, I cannot reproduce it even without a fix.

If you are still able to reproduce this on master branch I suggest that you file a separate bug for it.
