### ISSUE TITLE
[url_launcher] Declare if recievers should be exported or not. 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#126460]
Url launcher on android has receivers that should be either marked as exported or marked not exported. 
See:  
[RECEIVER_NOT_EXPORTED](http://cs/android-internal/frameworks/base/core/java/android/content/Context.java;l=603;rcl=0ac1f10eb98207bf0503fba905f2ec56afe65dea)

Public documentation: 
https://developer.android.com/about/versions/14/behavior-changes-14

(internal googler links only): 
https://critique.corp.google.com/cl/530531312
https://docs.google.com/document/d/16rHrghFfAD6P75RE237OwmsSwqcrmt2mDJlUMPsuxjU/edit?resourcekey=0-dEDIKmfyVVX1DCsKd0Nebg#heading=h.xgjl2srtytjt 

Android implementation code: 
https://github.com/flutter/packages/blob/main/packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java#L146 

example code 
```
ContextCompat.registerReceiver(
        application,
        broadcastReceiver,
        new IntentFilter(SOME_ACTION),
        ContextCompat.RECEIVER_EXPORTED);
```

**Comment by reidbaker** [comment]
This needs to be done soonish. 3 of these style bugs need to be done and merged to google3 in may.

**Comment by reidbaker** [comment]
https://b.corp.google.com/issues/281628158

**Comment by scolnet** [comment]
Hi Team,

@reidbaker It seams this commit breaks url_lancher on Android platform (under api 34).

When you open the link and click on the back button to return on the app, the app crashes with exception : 
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {xxx/io.flutter.plugins.urllauncher.WebViewActivity}: java.lang.IllegalArgumentException: Receiver not registered: io.flutter.plugins.urllauncher.WebViewActivity$a@3106981
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5746)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5779)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6085)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6000)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8381)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

When I override version with url_launcher_android: 6.0.31, it's ok.

It appears I'm not the only one : 
https://stackoverflow.com/questions/76244218/flutter-url-launcher-plugin-throws-java-lang-illegalargumentexception-receiver

Do you have an idea ?

Thanks
Sébastien

**Comment by reidbaker** [comment]
In that case feel free to roll the commit back (or I can). I tested on a non api33 device before putting the cl up for review but if it is hurting users I would rather have it reverted.

**Comment by scolnet** [comment]
I see a ticket has been created : #127014

If you can roll back, it would be nice ;)

Thanks

**Comment by stuartmorgan** [comment]
Re-opening since the PR was reverted.
