### ISSUE TITLE
Issue with MACOS-UI package after updating to flutter 3.10

### ISSUE THREAD

**Issue by nimr77** [flutter/flutter#126518]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Im on macOS, I was able to run my app on iPhone and debug it, and now after updating to flutter 3.10.0
this issue start to come 

Error (Xcode): ../../.pub-cache/hosted/pub.dev/macos_ui-1.12.2/lib/src/fields/text_field.dart:108:35: Error: The parameter 'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match the corresponding type, 'TapDragUpDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.
text_field.dart:108
Could not build the application for the simulator.
Error launching application on iPhone 14 Plus.

### Actual results

My app should be working and be able to debug it 

### Logs

<details>
<summary>Logs</summary>

```console

                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseMessaging\/FirebaseMessaging\/Sources\/FIRMes
                         sagingUtilities.m#CharacterRangeLen=0&EndingColumnNumber=41&EndingLineNumber=41&StartingColumnNumber=41&StartingLi
                         neNumber=41"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseMessaging\/FirebaseMessaging\/Sources\/FIRMes
                         sagingUtilities.m#CharacterRangeLen=0&EndingColumnNumber=35&EndingLineNumber=93&StartingColumnNumber=35&StartingLi
                         neNumber=93"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseMessaging\/FirebaseMessaging\/Sources\/FIRMes
                         sagingUtilities.m#CharacterRangeLen=0&EndingColumnNumber=35&EndingLineNumber=275&StartingColumnNumber=35&StartingL
                         ineNumber=275"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseMessaging\/FirebaseMessaging\/Sources\/FIRMes
                         sagingUtilities.m#CharacterRangeLen=0&EndingColumnNumber=33&EndingLineNumber=285&StartingColumnNumber=33&StartingL
                         ineNumber=285"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_core-2.11.0\/ios\/Classes\/messages.g.m#Char
                         acterRangeLen=0&EndingColumnNumber=58&EndingLineNumber=198&StartingColumnNumber=58&StartingLineNumber=198"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_core-2.11.0\/ios\/Classes\/messages.g.m#Char
                         acterRangeLen=0&EndingColumnNumber=57&EndingLineNumber=278&StartingColumnNumber=57&StartingLineNumber=278"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_core-2.11.0\/ios\/Classes\/FLTFirebaseCorePl
                         ugin.m#CharacterRangeLen=0&EndingColumnNumber=41&EndingLineNumber=63&StartingColumnNumber=41&StartingLineNumber=63
                         "
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Deprecations"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "'trackingID' is deprecated"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_core-2.11.0\/ios\/Classes\/FLTFirebaseCorePl
                         ugin.m#CharacterRangeLen=0&EndingColumnNumber=46&EndingLineNumber=65&StartingColumnNumber=46&StartingLineNumber=65
                         "
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Deprecations"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "'androidClientID' is deprecated"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_core-2.11.0\/ios\/Classes\/FLTFirebaseCorePl
                         ugin.m#CharacterRangeLen=0&EndingColumnNumber=12&EndingLineNumber=141&StartingColumnNumber=12&StartingLineNumber=1
                         41"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Deprecations"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "'trackingID' is deprecated"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_core-2.11.0\/ios\/Classes\/FLTFirebaseCorePl
                         ugin.m#CharacterRangeLen=0&EndingColumnNumber=12&EndingLineNumber=151&StartingColumnNumber=12&StartingLineNumber=1
                         51"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Deprecations"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "'androidClientID' is deprecated"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseRemoteConfig\/FirebaseRemoteConfig\/Sources\/
                         RCNDevice.m#CharacterRangeLen=0&EndingColumnNumber=35&EndingLineNumber=35&StartingColumnNumber=35&StartingLineNumb
                         er=35"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseRemoteConfig\/FirebaseRemoteConfig\/Sources\/
                         RCNDevice.m#CharacterRangeLen=0&EndingColumnNumber=40&EndingLineNumber=39&StartingColumnNumber=40&StartingLineNumb
                         er=39"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseRemoteConfig\/FirebaseRemoteConfig\/Sources\/
                         RCNDevice.m#CharacterRangeLen=0&EndingColumnNumber=35&EndingLineNumber=43&StartingColumnNumber=35&StartingLineNumb
                         er=43"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseRemoteConfig\/FirebaseRemoteConfig\/Sources\/
                         RCNDevice.m#CharacterRangeLen=0&EndingColumnNumber=43&EndingLineNumber=47&StartingColumnNumber=43&StartingLineNumb
                         er=47"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseRemoteConfig\/FirebaseRemoteConfig\/Sources\/
                         RCNDevice.m#CharacterRangeLen=0&EndingColumnNumber=38&EndingLineNumber=58&StartingColumnNumber=38&StartingLineNumb
                         er=58"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseRemoteConfig\/FirebaseRemoteConfig\/Sources\/
                         RCNConfigDBManager.m#CharacterRangeLen=0&EndingColumnNumber=49&EndingLineNumber=41&StartingColumnNumber=49&Startin
                         gLineNumber=41"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseRemoteConfig\/FirebaseRemoteConfig\/Sources\/
                         RCNConfigDBManager.m#CharacterRangeLen=0&EndingColumnNumber=55&EndingLineNumber=99&StartingColumnNumber=55&Startin
                         gLineNumber=99"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseCrashlytics\/Crashlytics\/Crashlytics\/Compon
                         ents\/FIRCLSHost.m#CharacterRangeLen=0&EndingColumnNumber=34&EndingLineNumber=108&StartingColumnNumber=34&Starting
                         LineNumber=108"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseCrashlytics\/Crashlytics\/Crashlytics\/Compon
                         ents\/FIRCLSCrashedMarkerFile.c#CharacterRangeLen=0&EndingColumnNumber=34&EndingLineNumber=20&StartingColumnNumber
                         =34&StartingLineNumber=20"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseFirestore\/Firestore\/core\/include\/firebase
                         \/firestore\/timestamp.h#CharacterRangeLen=0&EndingColumnNumber=35&EndingLineNumber=105&StartingColumnNumber=35&St
                         artingLineNumber=105"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Documentation Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Empty paragraph passed to '@param' command"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/Projects\/ticket\/ios\/Pods\/FirebaseFirestore\/Firestore\/core\/include\/firebase
                         \/firestore\/timestamp.h#CharacterRangeLen=0&EndingColumnNumber=21&EndingLineNumber=126&StartingColumnNumber=21&St
                         artingLineNumber=126"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Documentation Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Empty paragraph passed to '@param' command"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_auth-4.2.2\/ios\/Classes\/messages.g.m#Chara
                         cterRangeLen=0&EndingColumnNumber=61&EndingLineNumber=190&StartingColumnNumber=61&StartingLineNumber=190"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_auth-4.2.2\/ios\/Classes\/messages.g.m#Chara
                         cterRangeLen=0&EndingColumnNumber=64&EndingLineNumber=351&StartingColumnNumber=64&StartingLineNumber=351"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_auth-4.2.2\/ios\/Classes\/messages.g.m#Chara
                         cterRangeLen=0&EndingColumnNumber=57&EndingLineNumber=428&StartingColumnNumber=57&StartingLineNumber=428"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "A function declaration without a prototype is deprecated in all versions of C"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/firebase_auth-4.2.2\/ios\/Classes\/FLTFirebaseAuthPlu
                         gin.m#CharacterRangeLen=0&EndingColumnNumber=71&EndingLineNumber=102&StartingColumnNumber=71&StartingLineNumber=10
                         2"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Sending 'FLTFirebaseAuthPlugin *__strong' to parameter of incompatible type 'id<FLTFirebasePlugin>
                       _Nonnull'"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "DVTTextDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/nimrsawafta\/.pub-cache\/hosted\/pub.dev\/cloud_firestore-4.6.0\/ios\/Classes\/FLTFirebaseFires
                         torePlugin.m#CharacterRangeLen=0&EndingColumnNumber=28&EndingLineNumber=492&StartingColumnNumber=28&StartingLineNu
                         mber=492"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Semantic Issue"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Comparison of distinct pointer types ('FIRQuery *' and 'NSNull * _Nonnull')"
                     }
                   }
                 ]
               }
             },
             "metadataRef" : {
               "_type" : {
                 "_name" : "Reference"
               },
               "id" : {
                 "_type" : {
                   "_name" : "String"
                 },
                 "_value" : "0~gdTu6gI4DsNtRyuj25FZlPV6bDsSA-GaZVLIaNjKxeBvDkL71gSmFNr_o7bJ1DjyW7-Ji0be4oOsq2wjDINhLg=="
               },
               "targetType" : {
                 "_type" : {
                   "_name" : "TypeDefinition"
                 },
                 "name" : {
                   "_type" : {
                     "_name" : "String"
                   },
                   "_value" : "ActionsInvocationMetadata"
                 }
               }
             },
             "metrics" : {
               "_type" : {
                 "_name" : "ResultMetrics"
               },
               "errorCount" : {
                 "_type" : {
                   "_name" : "Int"
                 },
                 "_value" : "1"
               },
               "warningCount" : {
                 "_type" : {
                   "_name" : "Int"
                 },
                 "_value" : "94"
               }
             }
           }
[  +59 ms] Failed to build iOS app
[   +1 ms] Error (Xcode): [+3330 ms] ../../.pub-cache/hosted/pub.dev/macos_ui-1.12.2/lib/src/fields/text_field.dart:108:35: Error: The
parameter
           'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match
the
           corresponding type, 'TapDragUpDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.
           
[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14 Plus.
[   +1 ms] "flutter run" took 218,736ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +115 ms] ensureAnalyticsSent: 111ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (2 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64, locale en-MA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

</details>

**Comment by nimr77** [comment]
this issue is in the package of adaptive dialog, 
updating to this version fix the issue
https://pub.dev/packages/adaptive_dialog/versions/1.9.0-no-macos.2
