### ISSUE TITLE
Target dart2js failed on AWS

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#126534]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm trying to build my app for web on AWS.
It builds locally fine in release mode, and so do the mobile apps (iOS and Android).
The builds on AWS have been working for months, but now since this week they are failing and I can't figure out why.

I have included the verbose logs as an attachment, as they are too long to paste as a comment.

### Actual results

The build fails on AWS, but not locally.

### Logs

<details>
<summary>Logs</summary>

```console

See attachments


```

[aws-logs.txt](https://github.com/flutter/flutter/files/11452127/aws-logs.txt)

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console



Doctor summary (to see all details, run flutter doctor -v):
--
81 | [✓] Flutter (Channel stable, 3.10.0, on Ubuntu 22.04.2 LTS 4.14.309-231.529.amzn2.x86_64, locale en_US)
82 | [✗] Android toolchain - develop for Android devices
83 | ✗ Unable to locate Android SDK.
84 | Install Android Studio from: https://developer.android.com/studio/index.html
85 | On first launch it will assist you in installing the Android SDK components.
86 | (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
87 | If the Android SDK has been installed to a custom location, please use
88 | `flutter config --android-sdk` to update to that location.
89 |  
90 | [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
91 | ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
92 | [✗] Linux toolchain - develop for Linux desktop
93 | ✗ clang++ is required for Linux development.
94 | It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
95 | ✗ CMake is required for Linux development.
96 | It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
97 | ✗ ninja is required for Linux development.
98 | It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
99 | ✗ GTK 3.0 development libraries are required for Linux development.
100 | They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
101 | [!] Android Studio (not installed)
102 | [✓] Connected device (1 available)
103 | [✓] Network resources



```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Below are the failing entries from the log provided, for quick reference:

<details>
<summary> console error log </summary>

```

[+140631 ms] Persisting file store
[  +15 ms] Done persisting file store
[  +11 ms] Target dart2js failed: Exception: 
           #0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:226:7)
           <asynchronous suspension>
           #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
           <asynchronous suspension>
           #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
           <asynchronous suspension>
           #4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
           <asynchronous suspension>
           #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
           <asynchronous suspension>
           #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
           <asynchronous suspension>
           #7      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:81:34)
           <asynchronous suspension>
           #8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:191:5)
           <asynchronous suspension>
           #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

[  +31 ms] Compiling lib/main-customer_acceptance_enterprise.dart for the Web... (completed in 140.8s)
[   +2 ms] "flutter web" took 141,789ms.
[  +10 ms] Exception: Failed to compile application for the Web.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:118:7)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:191:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +34 ms] ensureAnalyticsSent: 0ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

[Container] 2023/05/11 11:53:16 Command did not exit successfully flutter build web --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE -t lib/$FLAVOR_ENTRYPOINT --release --source-maps --no-tree-shake-icons -v exit status 1
[Container] 2023/05/11 11:53:17 Phase complete: BUILD State: FAILED
[Container] 2023/05/11 11:53:17 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: flutter build web --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE -t lib/$FLAVOR_ENTRYPOINT --release --source-maps --no-tree-shake-icons -v. Reason: exit status 1
[Container] 2023/05/11 11:53:17 Entering phase POST_BUILD
[Container] 2023/05/11 11:53:17 Running command echo Pushing the Docker image...
Pushing the Docker image...

[Container] 2023/05/11 11:53:17 Running command docker tag $CODEBUILD_BUILD_ID $TARGET_CONTAINER_URL:$CB_GIT_BRANCH-$CODEBUILD_START_TIME
Error response from daemon: No such image: get-driven-customer-web-app:8cd867cf-a122-4d6a-aff4-f02ffc139dbd

[Container] 2023/05/11 11:53:17 Command did not exit successfully docker tag $CODEBUILD_BUILD_ID $TARGET_CONTAINER_URL:$CB_GIT_BRANCH-$CODEBUILD_START_TIME exit status 1
[Container] 2023/05/11 11:53:17 Phase complete: POST_BUILD State: FAILED
[Container] 2023/05/11 11:53:17 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker tag $CODEBUILD_BUILD_ID $TARGET_CONTAINER_URL:$CB_GIT_BRANCH-$CODEBUILD_START_TIME. Reason: exit status 1
[Container] 2023/05/11 11:53:17 Expanding base directory path: .
[Container] 2023/05/11 11:53:17 Assembling file list
[Container] 2023/05/11 11:53:17 Expanding .
[Container] 2023/05/11 11:53:17 Expanding file paths for base directory .
[Container] 2023/05/11 11:53:17 Assembling file list
[Container] 2023/05/11 11:53:17 Expanding get_driven_customer/imagedefinitions.json
[Container] 2023/05/11 11:53:17 Skipping invalid file path get_driven_customer/imagedefinitions.json
[Container] 2023/05/11 11:53:17 Phase complete: UPLOAD_ARTIFACTS State: FAILED
[Container] 2023/05/11 11:53:17 Phase context status code: CLIENT_ERROR Message: no matching artifact paths found

```

</details>

The actual exception seems to be empty, as it only shows `Target dart2js failed: Exception: `

@vixez Is there a way to get the actual exception that is thrown ? For example, in some of the below reports, it shows the actual exception:

https://github.com/flutter/flutter/issues/121339
https://github.com/flutter/flutter/issues/120787

`Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.`

`Target dart2js failed: ProcessException: Process exited abnormally:`

**Comment by vixez** [comment]
Hello @darshankawar,
I used to have 
```
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
```

So I decided to upgrade all dependencies to the latest version as much as possible.
Then this error went away.

After that I got an error about Font Awesome, so I had to add `--no-tree-shake-icons` (this wasn't needed before).

So now I ended up with this
`flutter build web --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE -t lib/$FLAVOR_ENTRYPOINT --release --source-maps --no-tree-shake-icons -v`

Now indeed it doesn't specify any exact error.
These are the verbose logs 

Is there a way I could get it to be even more verbose or have an actual exception be shown?

**Comment by darshankawar** [comment]
Thanks for the update @vixez 


> flutter build web --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE -t lib/$FLAVOR_ENTRYPOINT --release --source-maps --no-tree-shake-icons -v

Since this is rendered with canvaskit, in order to narrow it down to a particular renderer, is it possible to also check using `--web-renderer html` and see if you still get the same error or not ?

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open for team's input as there have been similar issue logs reported as mentioned https://github.com/flutter/flutter/issues/126534#issuecomment-1545208466

/cc @yjbanov for thoughts.

**Comment by annagrin** [comment]
[dart gardening] I created an sdk issue to investigate this: https://github.com/dart-lang/sdk/issues/52414

**Comment by biggs0125** [comment]
That message shows up when Dart2JS is invoked without the `--invoker=` flag. Though the "Warning:" prefix implies that Dart2JS is not exiting due to that flag being missing, that message is very likely a red herring.

Does Flutter expose a way to see the full output of the failing Dart2JS compilation process? We can't really root cause this without more information.

**Comment by sigmundch** [comment]
cc @christopherfujino - are there flutter-tools flags available to expose additional data here (e.g. what error and stack did dart2js produce)? If not, would it be possible to add that functionality?

**Comment by christopherfujino** [comment]
I doubt there's a flag, I think the tool just needs to dump the sub-process stdout/stderr to verbose logs. Let me take a look...

**Comment by christopherfujino** [comment]
Ahh, so actually I think after https://github.com/flutter/flutter/pull/126109, we do have much better logging. @vixez can you try to do an AWS build with the flutter master channel and see if we get better logs?

**Comment by vixez** [comment]
Hello @christopherfujino 
I use the command `git clone --depth 1 -b master https://github.com/flutter/flutter.git`
This results in `Flutter (Channel master, 0.0.0-unknown, on Ubuntu 22.04.2 LTS 4.14.309-231.529.amzn2.x86_64, locale en_US)`

Which makes version solving fail

```
[Container] 2023/05/18 08:41:03 Running command flutter pub get
--
169 | Resolving dependencies...
170 | The current Flutter SDK version is 0.0.0-unknown.
171 |  
172 | Because get_driven_customer depends on gd_vehicle_manager >=0.2.0 which requires Flutter SDK version >=1.17.0, version solving failed.


```

**Comment by vixez** [comment]
Hello @christopherfujino 

[Here](https://pastebin.com/ufdBByUs) is the new log from AWS.

**Comment by sigmundch** [comment]
@christopherfujino - I only see the error message from flutter tools, but not the output of dart2js.

I see in the code a call to `_logger.printTrace`, which should have what we need. I also see that this is only printed for verbose loggers. Shouldn't the `-v` in the command `Running command flutter build web --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE -t lib/$FLAVOR_ENTRYPOINT --release --source-maps --no-tree-shake-icons --web-renderer html -v` enable this output?

**Comment by sigmundch** [comment]
I noticed something curious - the web builds are done in two steps (dart -> .dill, then .dill -> js), and we are not seeing the output of the second step, but we are seeing output from the first step (all the warnings and final message indicating how long compilation took.)

Looking at `build_system/target/web.dart`, it seems like both commands are run with the same helper. So I'd expect the verbosity to match in both cases and to get some output for the second step.

Any chance the piping can break here? Could we run the dart2js command outside flutter-tools to see if we get a different signal?

**Comment by sigmundch** [comment]
One more question @christopherfujino 

Is it normal to see this kind of interleaving in the output:
```
[        ] executing: /codebuild/output/src627766568/src/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /codebuild/output/src627766568/src/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/codebuild/output/src627766568/src/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DSENTRY_RELEASE=get_driven_customer_acceptance_enterprise@3.7.0+329 -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/bfbd2e1dafb02db20634d9c7d7dd356ef2c83f39/ --native-null-assertions -O4 -o /codebuild/output/src627766568/src/get_driven_customer/.dart_tool/flutter_build/35ba6c40dff8e28ef447739954eb001f/main.dart.js /codebuild/output/src627766568/src/get_driven_customer/.dart_tool/flutter_build/35ba6c40dff8e28ef447739954eb001f/app.dill
[+81150 ms] Persisting file store
[   +8 ms] Done persisting file store
[   +6 ms] Target dart2js failed: ProcessException: Process exited abnormally:
```

In particular, that the tool started persisting storage before it reports the end of the target build?

**Comment by vixez** [comment]
Hello,
Any updates on this?

**Comment by vixez** [comment]
@christopherfujino @sigmundch 
In case you can use it, here are new logs built with master.

https://pastebin.com/CWhK8QmJ

**Comment by Am607** [comment]
@vixez  i have similar issue while iam using [docor image](https://github.com/cirruslabs/docker-images-flutter)

**Comment by christopherfujino** [comment]
@Am607 if you share your logs and `flutter doctor` and preferably your Docker image I will re-open this issue.
