### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: Системе не удается найти указанный путь., errno = 3

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#126529]
## Command
```
flutter run -d ch
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: Системе не удается найти указанный путь.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.createSync (dart:io/file_impl.dart:289:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26:16)
#3      ErrorHandlingFile.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:287:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#5      ErrorHandlingFile.createSync (package:flutter_tools/src/base/error_handling_io.dart:286:5)
#6      ErrorHan

**Comment by darshankawar** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/98066
