### ISSUE TITLE
Unable to successfully deploy a flutter web app from and build failing

### ISSUE THREAD

**Issue by faheemletitgo** [flutter/flutter#126526]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When deploying the web app for webm, during the build this error shows up.

### Expected results

Build successfull

### Actual results

I have attached this trimmed error being shown:

<details>
<summary> logs </summary>

```

2:35:25 PM: Waiting for other deploys from your team to complete. Check the queue: https://app.netlify.com/teams/admin-panel/builds
2:37:14 PM: build-image version: 900a223ea0f4a600c43255115089305a2b808649 (focal)
2:37:14 PM: buildbot version: ef13074d2cce7f50f6d57a698cb1897c8a6f2a51
2:37:14 PM: Fetching cached dependencies
2:37:14 PM: Starting to download cache of 796.9MB
2:37:19 PM: Finished downloading cache in 4.932s
2:37:19 PM: Starting to extract cache
2:37:23 PM: Finished extracting cache in 3.82s
2
2:37:26 PM: Started restoring cached go cache
2:
2:37:33 PM: Section completed: initializing
2:37:35 PM: ​
2:37:35 PM: Netlify Build                                                 
2:37:35 PM: ────────────────────────────────────────────────────────────────
2:37:35 PM: ​
2:37:35 PM: ❯ Version
2:37:35 PM:   @netlify/build 29.11.2
2:37:35 PM: ​
2:37:35 PM: ❯ Flags
2:37:35 PM:   baseRelDir: true
2:37:35 PM:   buildId: 645cb6dd8c53e10009fc90a0
2:37:35 PM:   deployId: 645cb6dd8c53e10009fc90a2
2:37:35 PM: ​
2:37:35 PM: ❯ Current directory
2:37:35 PM:   /opt/build/repo
2:37:35 PM: ​
2:37:35 PM: ❯ Config file
2:37:35 PM:   No config file was defined: using default values.
2:37:35 PM: ​
2:37:35 PM: ❯ Context
2:37:35 PM:   production
2:37:35 PM: ​
2:37:35 PM: ❯ Loading plugins
2:37:35 PM:    - netlify-plugin-flutter@1.1.0 from Netlify app
2:37:35 PM:    - @netlify/plugin-lighthouse@4.1.1 from Netlify app
2:37:36 PM: ​
2:37:36 PM: netlify-plugin-flutter (onPreBuild event)                     
2:37:36 PM: ────────────────────────────────────────────────────────────────
2:37:36 PM: ​
2:37:36 PM: ⚡️ Downloading Flutter Stable SDK
2:37:36 PM: Cloning into '/opt/buildhome/flutter'...
2:37:50 PM: ✅ Flutter SDK downloaded
2:37:50 PM: 🪄 Adding Flutter to PATH
2:37:50 PM: 🚀 Setting Flutter Channel to stable
2:37:50 PM: Downloading Linux x64 Dart SDK from Flutter engine d44b5a94c976fbb65815374f61ab5392a220b084...
2:37:50 PM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2:37:50 PM:                                  Dload  Upload   Total   Spent    Left  Speed
2:37:50 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2:37:51 PM:   0  203M    0  426k    0     0  1949k      0  0:01:47 --:--:--  0:01:47 1940k
2:37:52 PM:  63  203M   63  129M    0     0   106M      0  0:00:01  0:00:01 --:--:--  106M
2:37:52 PM: 100  203M  100  203M    0     0   109M      0  0:00:01  0:00:01 --:--:--  109M
2:37:56 PM: Building flutter tool...
2:37:56 PM: Resolving dependencies...

2:38:00 PM: 32 packages have newer versions incompatible with dependency constraints.
2:38:00 PM: Try `dart pub outdated` for more information.
2:38:11 PM: Downloading Material fonts...                                      310ms
2:38:11 PM: Downloading Gradle Wrapper...                                       23ms
2:38:11 PM: Downloading package sky_engine...                                   60ms
2:38:11 PM: Downloading flutter_patched_sdk tools...                           125ms
2:38:11 PM: Downloading flutter_patched_sdk_product tools...                   112ms
2:38:12 PM: Downloading linux-x64 tools...                                     925ms
2:38:13 PM: Downloading linux-x64/font-subset tools...                          55ms
2:38:13 PM: Switching to flutter channel 'stable'...
2:38:14 PM: git: Already on 'stable'
2:38:14 PM: git: Your branch is up to date with 'origin/stable'.
2:38:14 PM: Successfully switched to flutter channel 'stable'.
2:38:14 PM: To ensure that you're on the latest build from this channel, run 'flutter upgrade'🚀 Upgrading Flutter
2:38:14 PM: Flutter is already up to date on channel stable
2:38:14 PM: Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
2:38:14 PM: Framework • revision 84a1e904f4 (2 days ago) • 2023-05-09 07:41:44 -0700
2:38:14 PM: Engine • revision d44b5a94c9
2:38:14 PM: Tools • Dart 3.0.0 • DevTools 2.23.1
2:38:14 PM: ​
2:38:14 PM: (netlify-plugin-flutter onPreBuild completed in 38s)
2:38:14 PM: ​
2:38:14 PM: Build command from Netlify app                                
2:38:14 PM: ────────────────────────────────────────────────────────────────
2:38:14 PM: ​
2:38:14 PM: $ if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release
2:38:15 PM: From https://github.com/flutter/flutter
2:38:15 PM:    55c988fb45..0a63cd70f1  master          -> origin/master
2:38:15 PM:  + a14a4eac61...74e4b092e5 beta            -> origin/beta  (forced update)
2:38:15 PM:  * [new branch]            dependabot/github_actions/actions/labeler-2d89bd50598cb5288ebd91402d368ebb889ebdc6 -> origin/dependabot/github_actions/actions/labeler-2d89bd50598cb5288ebd91402d368ebb889ebdc6
2:38:15 PM:    69b6c94acd..84a1e904f4  flutter-3.10-candidate.1 -> origin/flutter-3.10-candidate.1
2:38:15 PM:  * [new branch]            flutter-3.10-candidate.16 -> origin/flutter-3.10-candidate.16
2:38:15 PM:  * [new branch]            flutter-3.10-candidate.17 -> origin/flutter-3.10-candidate.17
2:38:15 PM:  * [new branch]            flutter-3.10-candidate.18 -> origin/flutter-3.10-candidate.18
2:38:15 PM:  * [new branch]            flutter-3.11-candidate.0 -> origin/flutter-3.11-candidate.0
2:38:15 PM:  * [new branch]            flutter-3.11-candidate.1 -> origin/flutter-3.11-candidate.1
2:38:15 PM:  * [new branch]            flutter-3.11-candidate.2 -> origin/flutter-3.11-candidate.2
2:38:15 PM:  * [new branch]            flutter-3.11-candidate.3 -> origin/flutter-3.11-candidate.3
2:38:15 PM:  * [new branch]            flutter-3.11-candidate.4 -> origin/flutter-3.11-candidate.4


2:39:05 PM: Compiling lib/main.dart for the Web...
2:39:05 PM: Target dart2js failed: ProcessException: Process exited abnormally:
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/get-4.6.5/lib/get_navigation/src/nav2/get_information_parser.dart:29:50:
2:39:05 PM: Warning: Operand of null-aware operation '??' has type 'String' which excludes null.
2:39:05 PM:     final matchResult = Get.routeTree.matchRoute(location ?? initialRoute);
2:39:05 PM:                                                  ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/get-4.6.5/lib/get_navigation/src/nav2/get_router_delegate.dart:374:36:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
2:39:05 PM:             await backUntil(config.location!, popMode: PopMode.Page);
2:39:05 PM:                                    ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/another_flushbar-1.12.29/lib/flushbar.dart:439:38:
2:39:05 PM: Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.
2:39:05 PM:  - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart' ('flutter/packages/flutter/lib/src/painting/border_radius.dart').
2:39:05 PM:  - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('flutter/packages/flutter/lib/src/painting/border_radius.dart').
2:39:05 PM:                 borderRadius: widget.borderRadius,
2:39:05 PM:                                      ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/flutter_speed_dial-6.2.0/lib/src/speed_dial.dart:360:41:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
2:39:05 PM:  - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('flutter/packages/flutter/lib/src/widgets/overlay.dart').
2:39:05 PM:       if (widget.renderOverlay) Overlay.of(context)!.insert(backgroundOverlay!);
2:39:05 PM:                                         ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/flutter_speed_dial-6.2.0/lib/src/speed_dial.dart:361:15:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
2:39:05 PM:  - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('flutter/packages/flutter/lib/src/widgets/overlay.dart').
2:39:05 PM:       Overlay.of(context)!.insert(overlayEntry!);
2:39:06 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
2:39:05 PM:               ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:734:26:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:               headingRow.children![displayColumnIndex] =
2:39:05 PM:                          ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:739:40:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:                   fixedColumnsRows![0].children![displayColumnIndex] = h;
2:39:05 PM:                                        ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:741:39:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:                   fixedCornerRows![0].children![displayColumnIndex] = h;
2:39:05 PM:                                       ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:746:24:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:                       .children![displayColumnIndex - actualFixedColumns] = h;
2:39:05 PM:                        ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:749:24:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:                       .children![displayColumnIndex - actualFixedColumns] = h;
2:39:05 PM:                        ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:794:26:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:                         .children![displayColumnIndex] = c;
2:39:05 PM:                          ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:797:26:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:                         .children![displayColumnIndex] = c;
2:39:05 PM:                          ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:802:26:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:                         .children![displayColumnIndex - actualFixedColumns] = c;
2:39:05 PM:                          ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:805:26:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:                         .children![displayColumnIndex - actualFixedColumns] = c;
2:39:05 PM:                          ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:824:62:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:               return rows == null || rows.isEmpty || rows[0].children!.isEmpty;
2:39:05 PM:                                                              ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1043:18:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:       headingRow.children![0] = _buildCheckbox(
2:39:05 PM:                  ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1054:28:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:         fixedCornerRows[0].children![0] = headingRow.children![0];
2:39:05 PM:                            ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1054:54:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:         fixedCornerRows[0].children![0] = headingRow.children![0];
2:39:05 PM:                                                      ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1056:28:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:         fixedColumnRows[0].children![0] = headingRow.children![0];
2:39:05 PM:                            ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1056:54:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:         fixedColumnRows[0].children![0] = headingRow.children![0];
2:39:05 PM:                                                      ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1058:22:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:         fixedRows[0].children![0] = headingRow.children![0];
2:39:05 PM:                      ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1058:48:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:         fixedRows[0].children![0] = headingRow.children![0];
2:39:05 PM:                                                ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1060:22:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:         coreRows![0].children![0] = headingRow.children![0];
2:39:05 PM:                      ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1060:48:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:         coreRows![0].children![0] = headingRow.children![0];
2:39:05 PM:                                                ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1090:41:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:           fixedCornerRows[rowIndex + 1].children![0] = x;
2:39:05 PM:                                         ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1092:48:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:           fixedColumnRows[rowIndex - skipRows].children![0] = x;
2:39:05 PM:                                                ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1094:35:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:           fixedRows[rowIndex + 1].children![0] = x;
2:39:05 PM:                                   ^
2:39:05 PM: ../../buildhome/.pub-cache/hosted/pub.dev/data_table_2-2.4.2/lib/src/data_table_2.dart:1096:42:
2:39:05 PM: Warning: Operand of null-aware operation '!' has type 'List<Widget>' which excludes null.
2:39:05 PM:  - 'List' is from 'dart:core'.
2:39:05 PM:  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('flutter/packages/flutter/lib/src/widgets/framework.dart').
2:39:05 PM:           coreRows![rowIndex - skipRows].children![0] = x;
2:39:05 PM:                                          ^
2:39:05 PM: Error: Compilation failed.
2:39:05 PM:   Command: /opt/build/repo/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/build/repo/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/opt/build/repo/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/a0925f1581984d36378639ad9b1f54016d724ad9/ --native-null-assertions --no-source-maps -o /opt/build/repo/.dart_tool/flutter_build/8657d962cd674cd5bf0d305dbc2bef13/app.dill --packages=.dart_tool/package_config.json --cfe-only /opt/build/repo/.dart_tool/flutter_build/8657d962cd674cd5bf0d305dbc2bef13/main.dart
2:39:05 PM: #0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
2:39:05 PM: #1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:278:19)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:189:5)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:198:5)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1294:27)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:306:9)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254:5)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: #19     main (package:flutter_tools/executable.dart:91:3)
2:39:05 PM: <asynchronous suspension>
2:39:05 PM: Compiling lib/main.dart for the Web...                             12.7s
2:39:05 PM: Exception: Failed to compile application for the Web.
2:39:05 PM: ​
2:39:05 PM: "build.command" failed                                        
2:39:05 PM: ────────────────────────────────────────────────────────────────
2:39:05 PM: ​
2:39:05 PM:   Error message
2:39:05 PM:   Command failed with exit code 1: if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release (https://ntl.fyi/exit-code-1)
2:39:05 PM: ​
2:39:05 PM:   Error location
2:39:05 PM:   In Build command from Netlify app:
2:39:05 PM:   if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release
2:39:05 PM: ​
2:39:05 PM:   Resolved config
2:39:05 PM:   build:
2:39:05 PM:     command: if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release
2:39:05 PM:     commandOrigin: ui
2:39:05 PM:     publish: /opt/build/repo/build/web
2:39:05 PM:     publishOrigin: ui
2:39:05 PM:   plugins:
2:39:05 PM:     - inputs: {}
2:39:05 PM:       origin: ui
2:39:05 PM:       package: netlify-plugin-flutter
2:39:05 PM:     - inputs: {}
2:39:05 PM:       origin: ui
2:39:05 PM:       package: '@netlify/plugin-lighthouse'

2:39:05 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:39:05 PM: Failing build: Failed to build site
2:39:06 PM: Finished processing build request in 1m52.08s

```

</details>

### Code sample

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

### Screenshots or Video

<img width="1022" alt="image" src="https://github.com/flutter/flutter/assets/92992577/d6ed3ac0-8d9a-48b1-a94a-52fd7fb5abda">

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

4edoc@4EDocs-MacBook-Pro dashboard % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 11.6.8 20G730 darwin-x64, locale en-GB)
Checking Android licenses is taking an unexpectedly long time...⣯

**Comment by darshankawar** [comment]
@faheemletitgo 
This seems to be similar to https://github.com/flutter/flutter/issues/120787 based on the error log you shared, so please follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by faheemletitgo** [comment]
Ok, i will keep an eye on this, hope someone fixes the issue
