### ISSUE TITLE
Test bug with v3.10 about Scaffold.geometryOf()

### ISSUE THREAD

**Issue by codercengiz** [flutter/flutter#126513]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I had one widget test to test one page. This page has `BottomAppBar` that its shape is `CircularNotchedRectangle`.
On real device or emulator it works fine, only test failed.

Previously, my test was running successfully, but with new version it gives an error.

I think it is coming here
bottom_app_bar.dart 
line:254
```dart

  @override
  Path getClip(Size size) {
    // button is the floating action button's bounding rectangle in the
    // coordinate system whose origin is at the appBar's top left corner,
    // or null if there is no floating action button.
    final Rect? button = geometry.value.floatingActionButtonArea?.translate(0.0, bottomNavigationBarTop * -1.0);
    return shape.getOuterPath(Offset.zero & size, button?.inflate(notchMargin));
  }
  ``` 

### Expected results

The test should be passed successfully.

### Actual results

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Scaffold.geometryOf() must only be accessed during the paint phase.
The ScaffoldGeometry is only available during the paint phase, because its value is computed during
the animation and layout phases prior to painting.

When the exception was thrown, this was the stack:
#0      _ScaffoldGeometryNotifier.value.<anonymous closure> (package:flutter/src/material/scaffold.dart:831:9)
#1      _ScaffoldGeometryNotifier.value (package:flutter/src/material/scaffold.dart:838:6)
#2      _BottomAppBarClipper.getClip (package:flutter/src/material/bottom_app_bar.dart:258:35)
#3      _RenderCustomClip._updateClip (package:flutter/src/rendering/proxy_box.dart:1456:25)
#4      RenderPhysicalShape.hitTest (package:flutter/src/rendering/proxy_box.dart:2126:7)
#5      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2858:25)
#6      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#7      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2853:33)
#8      RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:413:12)
#9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#10     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#12     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#14     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:2008:18)
#15     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#17     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#19     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:2008:18)
#20     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#21     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#22     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2858:25)
#23     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#24     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2853:33)
#25     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:630:12)
#26     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#27     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#28     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#29     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#30     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#31     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#37     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3634:31)
#38     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#39     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#40     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#41     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#42     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#43     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#44     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#45     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#46     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#47     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#48     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#49     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#50     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#51     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#52     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3757:31)
#53     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#54     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#55     _RenderTheaterMixin.hitTestChildren.childHitTest (package:flutter/src/widgets/overlay.dart:850:81)
#56     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#57     _RenderTheaterMixin.hitTestChildren (package:flutter/src/widgets/overlay.dart:851:22)
#58     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#59     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#60     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#61     RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3867:17)
#62     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#63     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#64     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#65     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#66     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#67     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:544:18)
#68     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#69     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#70     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#71     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#72     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#73     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#74     RenderTapRegionSurface.hitTest (package:flutter/src/widgets/tap_region.dart:213:28)
#75     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#76     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#77     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#78     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#79     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#80     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#81     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#82     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#83     RenderView.hitTest (package:flutter/src/rendering/view.dart:189:14)
#84     RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:523:16)
#85     WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1316:15)
#86     WidgetController.getCenter (package:flutter_test/src/controller.dart:1232:12)
#87     WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#88     main.<anonymous closure>.<anonymous closure>.<anonymous closure> 
<asynchronous suspension>

The exception was caught asynchronously.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Please check [this](https://stackoverflow.com/questions/75310430/scaffold-geometryof-must-only-be-accessed-during-the-paint-phase) answer if it is helpful for this case. 

If the test still appears, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by davidag** [comment]
@codercengiz I was experiencing the same issue when popping a page. In my case, I *believe* it was caused by calling `setState()` *while* the route transition was in progress.

The solution I ended up applying was awaiting for the route transition to complete and then updating the state: 
```
// create route and await navigator push to get result
await route.completed
// update this page state with obtained result
```
