### ISSUE TITLE
`Linux framework smoke tests` flaking on MemoryAllocations `checkValidWeakTarget`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#126613]
## examples
- https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781354777818865009/+/u/Framework_test/test:_Framework_test/stdout
- https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781438844905436273/+/u/Framework_test/test:_Framework_test/stdout

## log 
```
10:10 +9876 ~81: /b/s/w/ir/cache/flutter/packages/flutter/test/material/about_test.dart: ListView of license entries is primary (variant: TargetPlatform.windows)                                      
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following ArgumentError was thrown MemoryAllocations while dispatching notifications for
PictureLayer:
Invalid argument (object): Cannot be a string, number, boolean, record, null, Pointer, Struct or
Union: 126605017

When the exception was thrown, this was the stack:
#0      checkValidWeakTarget (dart:_internal-patch/internal_patch.dart:220:5)
#1      Expando.[] (dart:core-patch/expando_patch.dart:31:5)
#2      FinalizerBase.detach (dart:_internal-patch/internal_patch.dart:335:32)
#3      ObjectTracker._checkForDuplicate (package:leak_tracker/src/leak_tracking/_object_tracker.dart:219:16)
#4      ObjectTracker.startTracking (package:leak_tracker/src/leak_tracking/_object_tracker.dart:51:9)
#5      dispatchObjectEvent (package:leak_tracker/src/leak_tracking/_dispatcher.dart:40:19)
#6      dispatchObjectEvent.<anonymous closure> (package:leak_tracker/src/leak_tracking/leak_tracker.dart:91:16)
#7      dispatchObjectEvent (package:leak_tracker/src/leak_tracking/leak_tracker.dart:94:4)
#8      _withFlutterLeakTracking.flutterEventToLeakTracker (file:///b/s/w/ir/cache/flutter/packages/flutter/test/foundation/leak_tracking.dart:109:12)
#9      MemoryAllocations.dispatchObjectEvent (package:flutter/src/foundation/memory_allocations.dart:238:23)
#10     MemoryAllocations.dispatchObjectCreated (package:flutter/src/foundation/memory_allocations.dart:272:5)
#11     new Layer (package:flutter/src/rendering/layer.dart:143:34)
#12     new PictureLayer (package:flutter/src/rendering/layer.dart)
#13     PaintingContext._startRecording (package:flutter/src/rendering/object.dart:336:21)
#14     PaintingContext.canvas (package:flutter/src/rendering/object.dart:328:7)
#15     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:620:33)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#21     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#24     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#36     RenderView.paint (package:flutter/src/rendering/view.dart:213:15)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#38     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#39     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#40     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1147:31)
#41     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1400:27)
#42     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#43     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1290:15)
#44     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1220:9)
#45     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1244:9)
#48     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#49     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1230:27)
#50     WidgetTester._pumpWidget (package:flutter_test/src/widget_tester.dart:585:20)
#51     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:570:14)
#54     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#55     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:569:27)
#56     main.<anonymous closure> (file:///b/s/w/ir/cache/flutter/packages/flutter/test/material/about_test.dart:929:18)
#57     testWidgetsWithLeakTracking.wrappedCallback.<anonymous closure> (file:///b/s/w/ir/cache/flutter/packages/flutter/test/foundation/leak_tracking.dart:58:27)
#58     withLeakTracking (package:leak_tracker/src/leak_tracking/orchestration.dart:88:19)
#59     _withFlutterLeakTracking.<anonymous closure> (file:///b/s/w/ir/cache/flutter/packages/flutter/test/foundation/leak_tracking.dart:117:27)
#62     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#63     _withFlutterLeakTracking (file:///b/s/w/ir/cache/flutter/packages/flutter/test/foundation/leak_tracking.dart:112:25)
#64     testWidgetsWithLeakTracking.wrappedCallback (file:///b/s/w/ir/cache/flutter/packages/flutter/test/foundation/leak_tracking.dart:57:11)
#65     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:163:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from dart:async and package:stack_trace)

The PictureLayer sending notification was:
  PictureLayer#bd6d9 DETACHED
════════════════════════════════════════════════════════════════════════════════════════════════════

10:10 +9876 ~81 -1: /b/s/w/ir/cache/flutter/packages/flutter/test/material/about_test.dart: ListView of license entries is primary (variant: TargetPlatform.windows) [E]                               
  Test failed. See exception logs above.
  The test description was: ListView of license entries is primary (variant: TargetPlatform.windows)
  

To run this test again: /b/s/w/ir/cache/flutter/bin/cache/dart-sdk/bin/dart test /b/s/w/ir/cache/flutter/packages/flutter/test/material/about_test.dart -p vm --plain-name 'ListView of license entries is primary (variant: TargetPlatform.windows)'
```

**Comment by gaaclarke** [comment]
closing as duplicate of https://github.com/flutter/flutter/issues/126259
