### ISSUE TITLE
Cannot run a flutter app - dart compiler exited unexpectly

### ISSUE THREAD

**Issue by i-dentify** [flutter/flutter#126640]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Regardless of being it an existing app or a freshly created app: when I try to start the app via `flutter run` an exception is thrown. This happens when starting from Android Studio as well as when running from command line.

As a side note: due to a previous issue I have been on the beta channel recently with version `3.9.0-0.2.pre`. I now switched back to the stable channel and upgraded to `3.10.0`. I ran `flutter clean` and `flutter pub get` and - to be save - also upgraded my local system (`brew update && brew upgrade`)

### Actual results

```
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Unhandled exception:
Unexpected Kernel Format Version 89 (expected 101)
#0      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:686:9)
#1      Timeline.timeSync (dart:developer/timeline.dart:166:22)
#2      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:673:21)
#3      _InitializationFromSdkSummary._prepareSummary (package:front_end/src/fasta/incremental_compiler.dart:2488:12)
#4      _InitializationFromUri.initialize (package:front_end/src/fasta/incremental_compiler.dart:2562:23)
<asynchronous suspension>
#5      IncrementalCompiler._ensurePlatformAndInitialize (package:front_end/src/fasta/incremental_compiler.dart:1423:25)
<asynchronous suspension>
#6      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:312:11)
<asynchronous suspension>
#7      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
<asynchronous suspension>
#8      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:595:11)
<asynchronous suspension>
#9      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1308:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```

### Logs

<details>
<summary>Logs</summary>

```console

[   +4 ms] executing: [/usr/local/Caskroom/flutter/3.0.3/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +25 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 84a1e904f44f9b0e9c4510138010edcc653163f8
[        ] executing: [/usr/local/Caskroom/flutter/3.0.3/flutter/] git tag --points-at 84a1e904f44f9b0e9c4510138010edcc653163f8
[  +35 ms] Exit code 0 from: git tag --points-at 84a1e904f44f9b0e9c4510138010edcc653163f8
[        ] 3.10.0
[   +2 ms] executing: [/usr/local/Caskroom/flutter/3.0.3/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +18 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.3.1
[        ] executing: sw_vers -buildVersion
[  +20 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22E772610a
[        ] executing: uname -m
[   +6 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +7 ms] executing: sysctl hw.optional.arm64
[   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +12 ms] executing: [/usr/local/Caskroom/flutter/3.0.3/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/usr/local/Caskroom/flutter/3.0.3/flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +115 ms] executing: sysctl hw.optional.arm64
[   +9 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +592 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 14.3
           Build version 14E222b
[   +4 ms] executing: xcrun xcdevice list --timeout 5
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] executing: /Users/mario/Library/Android/sdk/platform-tools/adb devices -l
[        ] executing: xcrun xcdevice list --timeout 2
[   +1 ms] xcrun simctl list devices booted iOS --json
[        ] executing: xcrun simctl list devices booted iOS --json
[   +3 ms] executing: xcrun simctl list devices booted
[ +299 ms] Exit code 0 from: xcrun simctl list devices booted
[        ] == Devices ==
           -- iOS 16.4 --
               iPhone 14 Pro (FC47ACEB-6F55-4C11-8E20-3E1532B0CE69) (Booted)
[  +71 ms] List of devices attached
           20226523022720         device usb:338690048X product:TC26PG model:TC26 device:TC26 transport_id:1
[ +309 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.iOS-16-4" : [
                          {
                            "lastBootedAt" : "2023-05-12T06:54:20Z",
                            "dataPath" : "\/Users\/mario\/Library\/Developer\/CoreSimulator\/Devices\/FC47ACEB-6F55-4C11-8E20-3E1532B0CE69\/data",
                            "dataPathSize" : 594149376,
                            "logPath" : "\/Users\/mario\/Library\/Logs\/CoreSimulator\/FC47ACEB-6F55-4C11-8E20-3E1532B0CE69",
                            "udid" : "FC47ACEB-6F55-4C11-8E20-3E1532B0CE69",
                            "isAvailable" : true,
                            "logPathSize" : 98304,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-14-Pro",
                            "state" : "Booted",
                            "name" : "iPhone 14 Pro"
                          }
                        ]
                      }
                    }
[+2819 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,7",
                        "identifier" : "0F6A8A57-BBBD-458D-AEE4-062A3984A85F",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-1",
                        "modelName" : "iPhone 14",
                        "name" : "iPhone 14",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,8",
                        "identifier" : "80447C3E-31C6-4617-B176-E2BC26C3FFE3",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-plus-1",
                        "modelName" : "iPhone 14 Plus",
                        "name" : "iPhone 14 Plus",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,3",
                        "identifier" : "B737E2F0-C543-4ADA-A8D2-1806796BBBA6",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-11-4th-1",
                        "modelName" : "iPad Pro (11-inch) (4th generation)",
                        "name" : "iPad Pro (11-inch) (4th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,2",
                        "identifier" : "FC47ACEB-6F55-4C11-8E20-3E1532B0CE69",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-pro-1",
                        "modelName" : "iPhone 14 Pro",
                        "name" : "iPhone 14 Pro",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,18",
                        "identifier" : "06A204E8-4189-4404-9E1F-36AEBAB19FC4",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-10-1",
                        "modelName" : "iPad (10th generation)",
                        "name" : "iPad (10th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,6",
                        "identifier" : "205AAE87-DECD-44C1-89C6-165307D2A771",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-se3-1",
                        "modelName" : "iPhone SE (3rd generation)",
                        "name" : "iPhone SE (3rd generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,3",
                        "identifier" : "49DCCDA8-EB9E-4397-8DC4-A2FCE80D1FAA",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-pro-max-1",
                        "modelName" : "iPhone 14 Pro Max",
                        "name" : "iPhone 14 Pro Max",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,5",
                        "identifier" : "64CDA0C2-66ED-455B-A514-C0C9731BBD8D",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-12point9-6th-1",
                        "modelName" : "iPad Pro (12.9-inch) (6th generation)",
                        "name" : "iPad Pro (12.9-inch) (6th generation)",
                        "ignored" : false
                      },
                      {
                        "ignored" : false,
                        "modelCode" : "MacBookPro15,1",
                        "simulator" : false,
                        "modelName" : "MacBook Pro",
                        "operatingSystemVersion" : "13.3.1 (22E261)",
                        "identifier" : "B4F74C55-8F8C-5A2D-9453-EDB43509D04E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "x86_64h",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookpro-15-retina-touchid-2018"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,1",
                        "identifier" : "EB6CA3F2-5050-4846-A49F-ED3C1B219A89",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-mini6-1",
                        "modelName" : "iPad mini (6th generation)",
                        "name" : "iPad mini (6th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.4 (20E247)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,17",
                        "identifier" : "06AEBCF1-EEE7-488A-81CE-F55E1DB62959",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-air5-1",
                        "modelName" : "iPad Air (5th generation)",
                        "name" : "iPad Air (5th generation)",
                        "ignored" : false
                      }
                    ]

                    2023-05-12 09:43:52.874 xcdevice[92547:12898330] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default
                    (DVTEnableCoreDevice=disabled)
[   +9 ms] /Users/mario/Library/Android/sdk/platform-tools/adb -s 20226523022720 shell getprop
[ +127 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +89 ms] Connected devices:
[   +1 ms] ro.hardware = qcom
[   +5 ms] TC26 (mobile)          • 20226523022720                       • android-arm64 • Android 10 (API 29)
[        ] iPhone 14 Pro (mobile) • FC47ACEB-6F55-4C11-8E20-3E1532B0CE69 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
[        ] Checking for wireless devices...
[        ] [1]: TC26 (20226523022720)
[        ] [2]: iPhone 14 Pro (FC47ACEB-6F55-4C11-8E20-3E1532B0CE69)
[   +1 ms] Please choose one (or "q" to quit)
[        ] : 
[+1762 ms] 2
[  +14 ms] Skipping pub get: version match.
[ +143 ms] Generating /Users/mario/Dev/untitled/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +88 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +7 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/Users/mario/Dev/untitled/.dart_tool/package_config_subset}
[  +29 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +2 ms] complete
[   +5 ms] Launching lib/main.dart on iPhone 14 Pro in debug mode...
[   +4 ms] /usr/local/Caskroom/flutter/3.0.3/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/usr/local/Caskroom/flutter/3.0.3/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/usr/local/Caskroom/flutter/3.0.3/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/d44b5a94c976fbb65815374f61ab5392a220b084/ --output-dill
/var/folders/k6/8q3b7phx6k5bmb9dl2trnq4m0000gn/T/flutter_tools.cHvu4Q/flutter_tool.E8vhOj/app.dill --packages
/Users/mario/Dev/untitled/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/d2250437cd2797886fcf0d3395b1b8f5.cache.dill.track.dill --verbosity=error
--enable-experiment=alternative-invalidation-strategy
[   +7 ms] executing: [/Users/mario/Dev/untitled/ios/] xcrun xcodebuild -list
[  +18 ms] <- compile package:untitled/main.dart
[ +171 ms] Unhandled exception:
[   +1 ms] Unexpected Kernel Format Version 89 (expected 101)
[        ] #0      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:686:9)
[        ] #1      Timeline.timeSync (dart:developer/timeline.dart:166:22)
[        ] #2      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:673:21)
[        ] #3      _InitializationFromSdkSummary._prepareSummary (package:front_end/src/fasta/incremental_compiler.dart:2488:12)
[        ] #4      _InitializationFromUri.initialize (package:front_end/src/fasta/incremental_compiler.dart:2562:23)
[        ] <asynchronous suspension>
[        ] #5      IncrementalCompiler._ensurePlatformAndInitialize (package:front_end/src/fasta/incremental_compiler.dart:1423:25)
[        ] <asynchronous suspension>
[        ] #6      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:312:11)
[        ] <asynchronous suspension>
[        ] #7      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
[        ] <asynchronous suspension>
[        ] #8      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:595:11)
[        ] <asynchronous suspension>
[        ] #9      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1308:11)
[        ] <asynchronous suspension>
[  +27 ms] the Dart compiler exited unexpectedly.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:817:13)
           #2      _rootRun (dart:async/zone.dart:1391:47)
           #3      _CustomZone.run (dart:async/zone.dart:1301:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:141:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1391:47)
           #14     _CustomZone.run (dart:async/zone.dart:1301:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1391:47)
           #26     _CustomZone.run (dart:async/zone.dart:1301:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:784:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:639:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:632:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2375:21)
           #35     _rootRunUnary (dart:async/zone.dart:1415:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:650:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:598:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1893:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1336:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
           #48     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
           
           
[   +4 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[   +1 ms] the Dart compiler exited unexpectedly.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:817:13)
           #2      _rootRun (dart:async/zone.dart:1391:47)
           #3      _CustomZone.run (dart:async/zone.dart:1301:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:141:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1391:47)
           #14     _CustomZone.run (dart:async/zone.dart:1301:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1391:47)
           #26     _CustomZone.run (dart:async/zone.dart:1301:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:784:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:639:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:632:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2375:21)
           #35     _rootRunUnary (dart:async/zone.dart:1415:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:650:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:598:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1893:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1336:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
           #48     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
           
           
[   +2 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-x64, locale de-DE)
    • Flutter version 3.10.0 on channel stable at /usr/local/Caskroom/flutter/3.0.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (vor 3 Tagen), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/mario/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/mario/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/mario/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/mario/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/mario/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • TC26 (mobile)          • 20226523022720                       • android-arm64  • Android 10 (API 29)
    • iPhone 14 Pro (mobile) • FC47ACEB-6F55-4C11-8E20-3E1532B0CE69 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!


```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @i-dentify 
Based on the logs shared, it seems to be similar to an already open issue https://github.com/flutter/flutter/issues/64849 but it was reported for Android platform and another one while trying to build a local engine https://github.com/flutter/flutter/issues/64849

Are you consistently getting this error upon trying to run on iOS ? Does it work on any other iOS device or OS version / simulator ?

Can you also try as mentioned [here](https://github.com/flutter/flutter/issues/50885#issuecomment-587121181) and see if it helps ?

**Comment by i-dentify** [comment]
Hi - thanks for your reply. Btw - I forgot to mention, that I also tried running on an android emulator, but with the same result. However: your linked comment indeed has helped. Running

```
rm -rf FLUTTER_ROOT/bin/cache
flutter precache
```

solved the issue.

**Comment by therasuldev** [comment]
Could you solve the problem ?
