### ISSUE TITLE
Error with 'resizeChannelBuffer' call in MethodChannel on Android platform

### ISSUE THREAD

**Issue by shin-ichiro-matsui** [flutter/flutter#126632]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Call `MethodChannel#resizeChannelBuffer` in the Android platform implementation.

### Actual results

Currently we are getting an error by calling `MethodChannel#resizeChannelBuffer` in the Android implementation of our application.

In our app, we need to perform initialization processing in a class that extends Android's Application.java and pass the necessary values to Flutter.

At this time, it was expected that `setMethodCallHandler` of `MethodChannel` was not set up on the Flutter side, so it was necessary to use `resizeChannelBuffer`.

However, when calling `MethodChannel#resizeChannelBuffer` in the Android implementation
```
E/flutter: [ERROR: flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Index out of range: no indices are valid: 0
```
I noticed that there is an error log saying.

Also, the buffer was not changed, just the last called `MethodChannel#invokeMethod` was processed on the Flutter side.

Below is a sample code to reproduce.

<details>
<summary>AndroidManifest.xml</summary>

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.sample_resize_buffer_test">
   <application
        android:label="sample_resize_buffer_test"
        android:name=".SampleApplication"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```

</details>

<details>
<summary>SampleApplication.java</summary>

```java
package com.example.sample_resize_buffer_test;

import android.app.Application;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.FlutterEngineCache;
import io.flutter.embedding.engine.FlutterEngineGroup;
import io.flutter.plugin.common.MethodChannel;

public class SampleApplication extends Application {

    public FlutterEngineGroup mFlutterEngineGroup;

    @Override
    public void onCreate() {
        super.onCreate();
        mFlutterEngineGroup = new FlutterEngineGroup(this);
        final FlutterEngine mainFlutterEngine = mFlutterEngineGroup.createAndRunDefaultEngine(this);
        FlutterEngineCache.getInstance().put("main:engine", mainFlutterEngine);
        final MethodChannel mainChannel = new MethodChannel(mainFlutterEngine.getDartExecutor().getBinaryMessenger(), "main:channel");
        mainChannel.resizeChannelBuffer(3);
        // sample invoke
        mainChannel.invokeMethod("onCreateApp", null);
        mainChannel.invokeMethod("etc1", null);
        mainChannel.invokeMethod("etc2", null);
    }
}

```
</details>

<details>
<summary>MainActivity.java</summary>

```java
package com.example.sample_resize_buffer_test;

import android.content.Context;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.FlutterEngineCache;

public class MainActivity extends FlutterActivity {

    @Nullable
    @Override
    public FlutterEngine provideFlutterEngine(@NonNull Context context) {
        FlutterEngine engine = FlutterEngineCache.getInstance().get("main:engine");
        if (engine == null) {
            engine = ((SampleApplication)getApplication()).mFlutterEngineGroup.createAndRunDefaultEngine(getApplicationContext());
        }
        return engine;
    }
}
```
</details>

<details>
<summary>main.dart</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const channel = MethodChannel('main:channel');

  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }


  @override
  void initState() {
    super.initState();
    channel.setMethodCallHandler((call) async {
      if(call.method == 'onCreateApp') {
        print('invokeMethod call from Android.');
      } else {
        print('no such method.');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Logs

<details>
<summary>Logs</summary>

```console
E/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Index out of range: no indices are valid: 0
    #0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:4276:7)
    #1      ChannelBuffers.handleMessage (dart:ui/channel_buffers.dart:437:14)
    #2      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:649:24)
    #3      _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
E/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Index out of range: no indices are valid: 0
    #0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:4276:7)
    #1      ChannelBuffers.handleMessage (dart:ui/channel_buffers.dart:437:14)
    #2      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:649:24)
    #3      _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.5.1 21G83 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report @shin-ichiro-matsui 
Can you verify the same using latest master or stable version to see if the same error persists or not ?

**Comment by shin-ichiro-matsui** [comment]
@darshankawar 
I verified with `Flutter-3.10.0`, but it was the same behavior.

**Comment by bleroux** [comment]
I encountered this issue recently and I think I have a possible fix for it.
I will try to file a PR soon.

**Comment by bleroux** [comment]
@shin-ichiro-matsui Thank you for reporting this issue.
@darshankawar Thank you for confirming it.

I filed https://github.com/flutter/engine/pull/41982 to fix this, in the meantime, I think it is possible to use the same code I wrote in the PR directly in your Java file instead of calling `MethodChannel.resizeChannelBuffer`:

```java
  static void resizeChannelBuffer(
      @NonNull BinaryMessenger messenger, @NonNull String channel, int newSize) {
    try {
      final String content = String.format("resize\r%s\r%d", channel, newSize);
      final byte[] bytes = content.getBytes("UTF-8");
      ByteBuffer packet = ByteBuffer.allocateDirect(bytes.length);
      packet.put(bytes);
      messenger.send(BasicMessageChannel.CHANNEL_BUFFERS_CHANNEL, packet);
    } catch (UnsupportedEncodingException e) {
      Log.e(TAG, "Failed to resize channel buffer named " + channel, e);
    }
  }
```

**Comment by shin-ichiro-matsui** [comment]
@bleroux 
具体的な解決策と「PR」ありがとう！
助かりました！
