### ISSUE TITLE
API `/api/file_flaky_issue_and_pr` fails due to exceeding `secondary rate limit`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#126604]
```
GitHub Error: {"message":"You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#secondary-rate-limits"}
#0      IssuesService.create (package:github/src/common/issues_service.dart:186:7)
<asynchronous suspension>
#1      FileFlakyIssueAndPR._fileIssueAndPR (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:91:13)
<asynchronous suspension>
#2      FileFlakyIssueAndPR.get (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:61:7)
<asynchronous suspension>
#3      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:50:24)
<asynchronous suspension>
#4      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:151:9)
<asynchronous suspension>
#5      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)
<asynchronous suspension>
#6      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:297:11)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
Related https://github.com/flutter/flutter/issues/124272

**Comment by keyonghan** [comment]
Based on historical data, it makes sense to focus on top 10 flaky targets. Before we have a clear solution about `how to create such PRs only after corresponding flaky bugs get triaged and labeled with a new tag`, we can try limiting 2 bugs/PRs at each time, and schedule the API 5 times early in the morning weekly: 1:00am, 1:30am, 2:00am, 2:30am, 3:00am every Wed. morning.

**Comment by ricardoamador** [comment]
Just something to consider with this, is that it may not directly be the call to create the issue but all of the calls to GitHub that we make during processing this request. We could limit the number of concurrent calls or space out the calls with waits between them for now.

**Comment by keyonghan** [comment]
https://github.com/flutter/cocoon/pull/2726 to add a 1s delay. Let's see how it goes.
