### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by Cooooper** [flutter/flutter#126916]
## Command
```
flutter build ios-framework --universal --no-xcframework --physical-archs=arm64 --no-tree-shake-icons --user-ios-ld=true --split-notices-raw=unused --split-debug-info=notused --force-skip-icons=MaterialIcons-Regular.otf --extreme-image-optimizer=true --no-sound-null-safety --no-bitcode --no-profile --split-elf-symbol=aot-symbols 
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1892:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1436:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
#14     _rootRunUnary (dart:async/zone.dart:1444:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#20     _StreamController._add (dart:async/stream_controller.dart:607:7)
#21     _StreamController.add (dart:async/stream_controller.dart:554:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1702:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel feature/v2.5.1.5_aion_lite, 2.5.1.5-0.1.pre, on macOS 13.1 22C65 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.1.5-0.1.pre at /Users/yuanzhan/.emas/build/29854406/workspace/.flutter
    • Upstream repository git@gitlab.alibaba-inc.com:flutter/flutter.git
    • Framework revision ab88ac472c89f0ac8ba60428 (9 weeks ago), 2023-03-14 20:32:17 +0800
    • Engine revision 2.5.1.5-220927142038
    • Dart version 2.14.2
    • Pub download mirror https://flutter.alibaba-inc.com
    • Flutter download mirror http://flutter-storage.effirst.com:8284/uc
    • UC_FLUTTER_CACHE_ENGINE: true
    • FLUTTER_DOWNLOADS_CACHE_DIR: /Users/yuanzhan/.flutter_downloads
    • JAVA_HOME: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 14.1, Build version 14B47b
    ! Unknown CocoaPods version installed.
        Flutter is unable to determine the installed CocoaPods's version.
        Ensure that the output of 'pod --version' contains only digits and . to be recognized by Flutter.
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 5 categories.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.taobao.trip.fportal
**iOS bundle identifier**: com.taobao.trip.fportal
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
fliggy_basic_flutter_map-9e41ace1826f87ef38fdabbc8c8a9403ddfc047e
apm_uploader-f2fa91f17e0982eccfb3391e6f040b4f5a91aab3
connectivity-0.4.6+1
device_info-2.0.3
fbridge-932e610104704d6e76db347a90701ae349403b4c
ficonfont-7fbb136cd05a2e54865b4f523b89b780195e95ec
fliggy_config-ec8c487d631571b72eb3a5f0b63b191b7ff02430
fliggy_destination-f15af29fc7d6d1077b5a35ae901c74bb81fe8d16
fliggy_destination_new-2d64f40285789e16d0e47974559117de59b04b01
flutter_fliggy_player-8bd622e026b96518f60a460c1c5b8489f3e64315
flutterHotel-2b126af29d06e8182d81f401de42dc777badb0c8
fliggy_location-8e13289c928c46567398f3abe57453c3c98e6646
fliggy_login-9ea5aa47ef14c4bc59de0048b1e125ca775fd81a
fliggy_flutter_map-aa2cb9e85b56757515834ef86d9a8058db1af32a
fliggy_storage-39fc5744763b72abd208130d8845103329c69a44
fliggy_map_search-7103688e417474835f320ab0a7f026c0340f1bab
fliggy_mtop-0.0.3
fliggy_router-48f6e3fd843e6d5c5be42cee9c43a2c57489aebc
fliggy_usertrack-b0124f6d443009cfec74ca1ef54091f0fe32925a
fliggy_webview-77ab54e40294cece0eedb3e9e34d81f025e299e4
flutter_boost-ee991c559c50c94e8beaf31f41b5afe2579900f2
flutter_plugin_android_lifecycle-2.0.6
flutter_travel_memories_photo_album-b2362874040f90391ec580dd253340e3b8c9fa1b
flutter_travel_share-b9d70149bbd3aeba6be66c0d1f8d3a80a3acf47c
fpicker-9725d96a9f9c125cdc4b0cb16858ba403c61f4fa
ftitlebar_adapter-5f7b8f431cab0d07997591ce4110aa7ecffd3204
flutter_high_avaliable-889aec7115a716f5394733bc4e7c0309f0fb4d67
IFCommon-6e8e470bb6f34981dce5af24a7a44425773a32e7
package_info-2.0.2
path_provider-2.0.4
path_provider_linux-2.1.6
path_provider_macos-2.0.6
path_provider_windows-2.0.6
permission_handler-6.1.3
shared_preferences-2.0.7
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.2
url_launcher-5.1.2
wpk_uploader-969600d07f0eac81a185cd8991bc141c87905f14

**Comment by darshankawar** [comment]
Based on error log, it looks similar to https://github.com/flutter/flutter/issues/81666 so please follow-up in it for further updates.
Closing this as a duplicate.
