### ISSUE TITLE
Problem running the app

### ISSUE THREAD

**Issue by therasuldev** [flutter/flutter#127097]
```
Launching lib/main.dart on sdk gphone arm64 in debug mode...
main.dart:1
Unhandled exception:
Unexpected Kernel SDK Version 7a6514d137 (expected 1618a77599).
#0      BinaryBuilder._readAndVerifySdkHash (package:kernel/binary/ast_from_binary.dart:657:7)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:689:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:166:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:673:21)
#4      _InitializationFromSdkSummary._prepareSummary (package:front_end/src/fasta/incremental_compiler.dart:2488:12)
#5      _InitializationFromUri.initialize (package:front_end/src/fasta/incremental_compiler.dart:2562:23)
<asynchronous suspension>
#6      IncrementalCompiler._ensurePlatformAndInitialize (package:front_end/src/fasta/incremental_compiler.dart:1423:25)
<asynchronous suspension>
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:312:11)
<asynchronous suspension>
#8      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
<asynchronous suspension>
#9      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:595:11)
<asynchronous suspension>
#10     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1308:11)
<asynchronous suspension>

2
the Dart compiler exited unexpectedly.
Exited (1)
```

**Comment by darshankawar** [comment]
Not an ideal solution that, but does that resolved the issue ?

**Comment by jensjoha** [comment]
7a6514d137 is dart 3.0.0.
1618a77599 is dart 3.0.1.
So it seems that the code running is from dart 3.0.1, but that the platform it was asked to use was from 3.0.0.
Could the flutter upgrade have been interrupted somehow? (so that it didn't delete the old platform and didn't download a new platform for instance)

**Comment by therasuldev** [comment]
> Not an ideal solution that, but does that resolved the issue ?

yes,
