### ISSUE TITLE
FlutterError

### ISSUE THREAD

**Issue by mazab99** [flutter/flutter#127033]
```
I/flutter (28786): stack==>>#0      BindingBase.debugCheckZone.<anonymous closure> (package:flutter/src/foundation/binding.dart:497:29)
I/flutter (28786): #1      BindingBase.debugCheckZone (package:flutter/src/foundation/binding.dart:502:6)
I/flutter (28786): #2      runApp (package:flutter/src/widgets/binding.dart:1080:18)
I/flutter (28786): #3      bootstrap.<anonymous closure> (package:khodrah_clean_arc/src/core/app/bootstrap.dart:30:7)
I/flutter (28786): <asynchronous suspension>
I/flutter (28786): #4      bootstrap (package:khodrah_clean_arc/src/core/app/bootstrap.dart:25:3)
I/flutter (28786): <asynchronous suspension>
I/flutter (28786): #5      main (package:khodrah_clean_arc/main.dart:22:3)
I/flutter (28786): <asynchronous suspension>



[FlutterError details==>>Zone mismatch.
I/flutter (28786): The Flutter bindings were initialized in a different zone than is now being used. This will likely cause confusion and bugs as any zone-specific configuration will inconsistently use the configuration of the original binding initialization zone or this zone based on hard-to-predict factors such as which zone was active when a particular callback was set.
I/flutter (28786): It is important to use the same zone when calling `ensureInitialized` on the binding as when calling `runApp` later.
I/flutter (28786): To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are initialized (i.e. as the first statement in `void main() { }`)., FlutterError stackTrace==>>#0      BindingBase.debugCheckZone.<anonymous closure> (package:flutter/src/foundation/binding.dart:497:29)
I/flutter (28786): #1      BindingBase.debugCheckZone (package:flutter/src/foundation/binding.dart:502:6)
I/flutter (28786): #2      runApp (package:flutter/src/widgets/binding.dart:1080:18)

`  await bootstrap(
    builder: () {
      return MyApp(
        startWidget: widget,
      );
    },
    tasks: RunAppTasks(),
  );`

`Future<void> bootstrap({
  required FutureOr<Widget> Function() builder,
  required RunTasks tasks,
}) async {
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.presentError(details);
    Zone.current.handleUncaughtError(details.exception, details.stack!);
    PrintManager.printItem(
      item: [
        'FlutterError details==>>${details.exceptionAsString()}',
        'FlutterError stackTrace==>>${details.stack}',
      ],
    );
  };
  Bloc.observer = MyBlocObserver();

  await runZonedGuarded<Future<void>>(
    () async {
      final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
      await tasks.beforeRun(widgetsBinding);

      runApp(await builder());

      await tasks.afterRun();
    },
    tasks.onError,
  );
}

abstract class RunTasks {
  Future<void> beforeRun(WidgetsBinding widgetsBinding);

  Future<void> afterRun();

  void onError(Object error, StackTrace stack);
}

class RunAppTasks extends RunTasks {
  @override
  Future<void> beforeRun(WidgetsBinding widgetsBinding) async {
    FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  }

  @override
  Future<void> afterRun() async {
    FlutterNativeSplash.remove();
  }

  @override
  void onError(Object error, StackTrace stack) {
    PrintManager.printItem(
      item: 'stack==>>${stack.toString()}',
    );
  }
}`
```

**Comment by darshankawar** [comment]
@mazab99 
You are probably hitting the zone mismatch error due to breaking changes in 3.10. See this document for your reference: https://docs.flutter.dev/release/breaking-changes/zone-errors and migration guide on how to fix it : https://docs.flutter.dev/release/breaking-changes/zone-errors#migration-guide

Closing this issue, as you are seeing the error due to breaking changes.

**Comment by mazab99** [comment]
I saw the documentation but I couldn't fixed it 
I don't know where is the error in my code

**Comment by mazab99** [comment]
Note : I put this at the first line of main fun 

WidgetsFlutterBinding.ensureInitialized();
