### ISSUE TITLE
Column header icons not displaying in cocoon

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127038]
Not sure when this started or if the change is intentional, but I find the headers useful.

<img width="934" alt="Screenshot 2023-05-17 at 9 32 45 AM" src="https://github.com/flutter/flutter/assets/6343103/079922db-46e8-4052-914f-953cfa911f5c">

**Comment by ricardoamador** [comment]
cc @andrewkolos Can you please take a look at this?
Error being returned:
![image](https://github.com/flutter/flutter/assets/32242716/7f087e95-9733-4f23-888d-4e66a5d2a7b7)

**Comment by ricardoamador** [comment]
From the cocoon log:
```
logMessage: "Null check operator used on a null value
#0      StaticFileHandler.get (package:cocoon_service/src/request_handling/static_file_handler.dart:53:39)
#1      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:50:30)
#2      _rootRun (dart:async/zone.dart:1399:13)
#3      _CustomZone.run (dart:async/zone.dart:1301:19)
#4      _runZoned (dart:async/zone.dart:1804:10)
#5      runZoned (dart:async/zone.dart:1747:10)
#6      RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:42:12)
#7      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:318:61)
#8      runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#9      runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:18)
#10     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:205:19)
#11     _rootRun (dart:async/zone.dart:1399:13)
#12     _CustomZone.run (dart:async/zone.dart:1301:19)
#13     _runZoned (dart:async/zone.dart:1804:10)
#14     runZonedGuarded (dart:async/zone.dart:1792:12)
#15     runZoned (dart:async/zone.dart:1744:12)
#16     _ServiceScope._fork (package:gcloud/service_scope.dart:204:12)
#17     fork (package:gcloud/service_scope.dart:102:30)
#18     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:55:12)
#19     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:17)
#20     _rootRunUnary (dart:async/zone.dart:1407:47)
#21     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#25     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#26     _StreamController._add (dart:async/stream_controller.dart:650:7)
#27     _StreamController.add (dart:async/stream_controller.dart:598:5)
#28     _HttpServer._handleRequest (dart:_http/http_impl.dart:3326:19)
#29     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:3110:19)
#30     _rootRunUnary (dart:async/zone.dart:1407:47)
#31     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#35     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#36     _StreamController._add (dart:async/stream_controller.dart:650:7)
#37     _StreamController.add (dart:async/stream_controller.dart:598:5)
#38     _HttpParser._headersEnd (dart:_http/http_parser.dart:389:19)
#39     _HttpParser._doParse (dart:_http/http_parser.dart:745:15)
#40     _HttpParser._parse (dart:_http/http_parser.dart:319:7)
#41     _rootRunUnary (dart:async/zone.dart:1407:47)
#42     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#46     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#47     _StreamController._add (dart:async/stream_controller.dart:650:7)
#48     _StreamController.add (dart:async/stream_controller.dart:598:5)
#49     _Socket._onData (dart:io-patch/socket_patch.dart:2368:41)
#50     _rootRunUnary (dart:async/zone.dart:1415:13)
#51     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#56     _StreamController._add (dart:async/stream_controller.dart:650:7)
#57     _StreamController.add (dart:async/stream_controller.dart:598:5)
#58     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1886:33)
#59     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1343:14)
#60     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#61     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#62     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#63     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
"
```

**Comment by andrewkolos** [comment]
I'm sorry I'm just seeing this. This is possibly related to https://github.com/flutter/flutter/pull/126077 (which had a corresponding g3fix). I wonder if some reference wasn't updated. I'm also curious why some icons are displays while others aren't.

**Comment by ricardoamador** [comment]
Would there need to be an update somewhere in cocoon?

**Comment by ricardoamador** [comment]
I would guess this is coming from the build of the flutter dashboard app so I am looking to see if I can find where this is coming from.

**Comment by ricardoamador** [comment]
Okay this is the issue. I was able to build the dashboard locally and the change references your new AssetManifest.smcbin file.

**Comment by ricardoamador** [comment]
The AssetManifest.smcbin is getting used now with the newest version of flutter but the error is persisting. Still looking...

**Comment by ricardoamador** [comment]
Adding to our queue since this is customer facing.

**Comment by ricardoamador** [comment]
Okay found the issue during our triage meeting. Since this is a made up format, we needed to actually map the mimetype to binary so that we could serve this file type. I changed it to map it to 'application/octet-stream' which is the same as binary. Will have a PR shortly.

![image](https://github.com/flutter/flutter/assets/32242716/cae135c7-d81a-49dd-92cb-39e4f92cb1a5)
