### ISSUE TITLE
editable.dart error: 'package:flutter/src/rendering/editable.dart': Failed assertion: line 1310 pos 14: 'readOnly && !obscureText': is not true.

### ISSUE THREAD

**Issue by shAdow-XJY** [flutter/flutter#127091]
Here's a problem I'm having:
Premise: rewrite a TextEditingController, add click event TapGestureRecognizer in TextSpan buildTextSpan.
Result: It can be clicked normally when running on Windows PC, but the following error will be reported when running on Android mobile.
```
my source code: https://github.com/shAdow-XJY/click_text_field/blob/master/lib/src/click_text_edit_controller.dart
 @override
  TextSpan buildTextSpan({required BuildContext context, TextStyle? style, required bool withComposing}) {
    // debugPrint('scanning text as follow:');
    // debugPrint(text);

    var atIndex = 0;
    var spans = <InlineSpan>[];

    _scanner = StringScanner(text);
    if (regExp.pattern.isNotEmpty) {
      while (!_scanner.isDone) {
        // debugPrint('scanning');
        // print('position: ${_scanner.position}');
        if (_scanner.scan(regExp)) {
          int startIndex = _scanner.lastMatch?.start ?? 0;
          int endIndex = _scanner.lastMatch?.end ?? 0;
          // print('startIndex: ${startIndex}');
          // print('endIndex: ${endIndex}');
          if (startIndex < endIndex) {
            spans.add(TextSpan(
              text: text.substring(atIndex, startIndex),
              style: _textStyle,
              mouseCursor: SystemMouseCursors.text,
            ));
            spans.add(
                TextSpan(
                  text: text.substring(startIndex, endIndex),
                  style: _clickTextStyle,
                  mouseCursor: SystemMouseCursors.click,
                  recognizer: TapGestureRecognizer()
                    ..onTap = () =>
                        _onTap(text.substring(startIndex, endIndex)),
                ),
            );
            // debugPrint('is highlight text span!!!!');
            atIndex = endIndex;
            _scanner.position = atIndex;
          } else {
            _scanner.position++;
          }
        } else if (text.length > _scanner.position) {
          _scanner.position++;
        } else {
          break;
        }
      }
    }
    _scanner.position = 0;
    spans.add(TextSpan(
      text: text.substring(atIndex, (text.isNotEmpty) ? text.length : 0),
      style: _textStyle,
      mouseCursor: SystemMouseCursors.text,
    ));
    spans.add(const TextSpan(
      text: ' ',
      mouseCursor: SystemMouseCursors.text,
    ));
    // debugPrint('build TextSpan successfully');
    return TextSpan(
      children: spans,
      mouseCursor: SystemMouseCursors.text,
    );
  }
```

```
======== Exception caught by widgets library=======================================================
The following assertion was thrown building _ScribbleFocusable(state: _ScribbleFocusableState#245b5):
'package:flutter/src/rendering/editable.dart': Failed assertion: line 1310 pos 14: 'readOnly && !obscureText': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

The relevant error-causing widget was: 
  ClickTextField ClickTextField:file:///E:/AndroidStudioProjects/writing_writer/lib/pages/common/chapter_edit_page/common_chapter_edit_body.dart:172:19
When the exception was thrown, this was the stack: 
#2      RenderEditable.describeSemanticsConfiguration (package:flutter/src/rendering/editable.dart:1310:14)
#3      RenderObject._semanticsConfiguration (package:flutter/src/rendering/object.dart:3098:7)
#4      RenderObject.attach (package:flutter/src/rendering/object.dart:1771:34)
#5      RelayoutWhenSystemFontsChangeMixin.attach (package:flutter/src/rendering/object.dart:4068:11)
#6      ContainerRenderObjectMixin.attach (package:flutter/src/rendering/object.dart:3936:11)
#7      RenderEditable.attach (package:flutter/src/rendering/editable.dart:1619:11)
#8      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:137:13)
#9      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1493:11)
#10     RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:3653:7)
#11     SingleChildRenderObjectElement.insertRenderObjectChild (package:flutter/src/widgets/framework.dart:6400:18)
#12     RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6164:35)
#13     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5839:5)
#14     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6527:11)
...     Normal element mounting (125 frames)
#139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3964:16)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3701:18)
#141    SlottedRenderObjectElement._updateChildren (package:flutter/src/widgets/slotted_render_object_widget.dart:270:33)
#142    SlottedRenderObjectElement.mount (package:flutter/src/widgets/slotted_render_object_widget.dart:224:5)
...     Normal element mounting (101 frames)
#243    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3964:16)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:3695:20)
#245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5007:16)
#246    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5147:11)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
#248    StatefulElement.update (package:flutter/src/widgets/framework.dart:5170:5)
#249    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
#250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5007:16)
```

**Comment by shAdow-XJY** [comment]
here is the result of `flutter doctor -v`
```
[√] Flutter (Channel beta, 3.9.0-0.2.pre, on Microsoft Windows [版本 10.0.22000.1936], locale zh-CN)
    • Flutter version 3.9.0-0.2.pre on channel beta at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0df8557c56 (8 weeks ago), 2023-03-23 22:02:01 -0500
    • Engine revision 1cc4b2d280
    • Dart version 3.0.0 (build 3.0.0-290.3.beta)
    • DevTools version 2.22.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\12902\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.16)
    • Visual Studio at D:\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32602.291
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2021.2.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • OCE AN50 (mobile) • 8QM0221608010355 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [版本 10.0.22000.1936]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 111.0.5563.65
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 113.0.1774.42

```

**Comment by huycozy** [comment]
Hi @shAdow-XJY 
As I can see from [your repository](https://github.com/shAdow-XJY/click_text_field), you are using 3rd party package. 

In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party packages/plugins or complex production code so that we may verify this. Thank you!

**Comment by shAdow-XJY** [comment]
@huycozy 
Hi, great to hear from you.
The following is a small program I rewritten without using a third-party plug-in package. When it is still running on the mobile terminal, the error mentioned above will occur.

Feel free to @me if you need more details.

source code here: https://github.com/shAdow-XJY/click_text_field/blob/master/example/lib/main.dart

```
TextField(
              maxLines: null,
              controller: ClickController(),
            )
```
```
class ClickController extends TextEditingController {

  @override
  TextSpan buildTextSpan({required BuildContext context, TextStyle? style, required bool withComposing}) {

    var spans = <InlineSpan>[];

    int startIndex = 0;

    for (var i = 0; i < text.length; ++i) {
      if (text[i] == 'A') {
        spans.add(
          TextSpan(
            text: text.substring(startIndex, i),
            mouseCursor: SystemMouseCursors.click,
            recognizer: TapGestureRecognizer()..onTap = () => debugPrint('click A'),
          ),
        );
        spans.add(
          TextSpan(
            text: 'A',
            mouseCursor: SystemMouseCursors.click,
            recognizer: TapGestureRecognizer()..onTap = () => debugPrint('click A'),
          ),
        );
        startIndex = i + 1;
      }
    }
    if (startIndex < text.length) {
      spans.add(
        TextSpan(
          text: text.substring(startIndex, text.length),
          mouseCursor: SystemMouseCursors.text,
        ),
      );
    }

    return TextSpan(
      children: spans,
      mouseCursor: SystemMouseCursors.text,
    );
  }
}
```

**Comment by huycozy** [comment]
Thanks for your response, but the sample code above still uses `click_text_field` from your package which is quite complex for us to verify this. 

You should narrow down the issue by removing unrelated/unaffected classes and isolating the issue into a simple main.dart file that can be run independently. If the issue's still reproducible, please provide that main.dart file along with clear `Steps by steps` to reproduce the issue.

**Comment by shAdow-XJY** [comment]
ok, I'm sorry. @huycozy 
I create a new repository, it only has a ClickController class extends TextEditingController.

repository link:  https://github.com/shAdow-XJY/textfiled_mobile_wrong/blob/master/lib/main.dart
run on mobile video:  https://github.com/shAdow-XJY/textfiled_mobile_wrong/blob/master/example.mp4

The error I mentioned occurs when Android is running, and the window does not have this problem：
 `When you input an 'A', TextSpan will add a TapGestureRecognizer, then report an error.`

main.dart:
```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'text_field',
      theme: ThemeData(
          brightness: Brightness.dark
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);


  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('click_text_field'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            TextField(
              maxLines: null,
              controller: ClickController(),
            )
          ],
        ),
      ),
    );
  }
}

class ClickController extends TextEditingController {

  @override
  TextSpan buildTextSpan({required BuildContext context, TextStyle? style, required bool withComposing}) {

    var spans = <InlineSpan>[];

    int startIndex = 0;

    for (var i = 0; i < text.length; ++i) {
      if (text[i] == 'A') {
        spans.add(
          TextSpan(
            text: text.substring(startIndex, i),
            mouseCursor: SystemMouseCursors.click,
            recognizer: TapGestureRecognizer()..onTap = () => debugPrint('click A'),
          ),
        );
        spans.add(
          TextSpan(
            text: 'A',
            mouseCursor: SystemMouseCursors.click,
            recognizer: TapGestureRecognizer()..onTap = () => debugPrint('click A'),
          ),
        );
        startIndex = i + 1;
      }
    }
    if (startIndex < text.length) {
      spans.add(
        TextSpan(
          text: text.substring(startIndex, text.length),
          mouseCursor: SystemMouseCursors.text,
        ),
      );
    }

    return TextSpan(
      children: spans,
      mouseCursor: SystemMouseCursors.text,
    );
  }
}
```

**Comment by huycozy** [comment]
Thanks, it's great. But when I test this on my Android device, it works well without issue.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/f4174b09-60d6-4962-93ef-3721a4a09bc7

</details>

Can you please retry on the latest stable/master channel and confirm this?

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (26 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-6.0.pre.153, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-6.0.pre.153 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e49d35d3a6 (35 minutes ago), 2023-05-18 22:26:29 -0400
    • Engine revision bca11a423f
    • Dart version 3.1.0 (build 3.1.0-125.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by shAdow-XJY** [comment]
I'm so sorry! @huycozy 
The situation seems to only happen on my own mobile phone. I tried the emulator and two other Android phones, and this error did not appear.
Also tried flutter channel stable, same situation. . . . . .
Sorry to bother you, I will try to research the problem by myself first, and then raise other issues if I have any problems
