### ISSUE TITLE
Failed assertion  in gestures/converter.dart ('!state.down': is not true.)

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#12713]
## Steps to Reproduce

I just had this happening twice when going back from a demo page to the home page in the gallery app (TalkBack was on).
I was running unmodified Flutter TOT (synced to cbfed1960f80964ba89f0093a49e1a0d44ca95d9)

## Logs
```
E/flutter ( 3509): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3509): 'package:flutter/src/gestures/converter.dart': Failed assertion: line 131: '!state.down': is not true.
E/flutter ( 3509): #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
E/flutter ( 3509): #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
E/flutter ( 3509): #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:131)
E/flutter ( 3509): #3      _SyncIterator.moveNext (dart:core-patch/dart:core/core_patch.dart:149)
E/flutter ( 3509): #4      ListQueue.addAll (dart:collection/queue.dart:635)
E/flutter ( 3509): #5      BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:46)
E/flutter ( 3509): #6      _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:115)
E/flutter ( 3509): #7      _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:73)
E/flutter ( 3509): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3509): 'package:flutter/src/gestures/converter.dart': Failed assertion: line 131: '!state.down': is not true.
E/flutter ( 3509): #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
E/flutter ( 3509): #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
E/flutter ( 3509): #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:131)
E/flutter ( 3509): #3      _SyncIterator.moveNext (dart:core-patch/dart:core/core_patch.dart:149)
E/flutter ( 3509): #4      ListQueue.addAll (dart:collection/queue.dart:635)
E/flutter ( 3509): #5      BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:46)
E/flutter ( 3509): #6      _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:115)
E/flutter ( 3509): #7      _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:73)
```
Run `flutter analyze` and attach any output of that command also.

```
Analyzing 1277 files...
No analyzer warnings! (ran in 37.8s; 13 public members lack documentation)
```

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
• Flutter at /usr/local/google/home/amirha/git/flutter
• Framework revision cbfed19 (2 hours ago), 2017-10-25 07:18:09 -0700
• Engine revision ec19da1c80
• Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
• Android SDK at /usr/local/google/home/amirha/Android/Sdk
• Platform android-26, build-tools 26.0.2
• Java binary at: /usr/local/google/home/amirha/progs/android-studio/jre/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
• Android Studio at /opt/android-studio-with-blaze-2.3
• Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
• Android Studio at /usr/local/google/home/amirha/progs/android-studio
• Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
• Flutter plugin version 18.0
• Dart plugin version 172.4155.35

[✓] Connected devices
• Pixel • FA6890301419 • android-arm • Android 8.1.0 (API 27)
```

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by amirh** [comment]
Hard to say without further analysis, though if know one hit this for a year I guess we can close it and re-open or open a new issue the first time we see it again.
