### ISSUE TITLE
Failed assertion in scrollable.dart ('_drag == null': is not true.)

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#12712]
## Steps to Reproduce

Just had this happen once when scrolling in the gallery app  home screen (Flutter unmodified TOT sycned to cbfed1960f80964ba89f0093a49e1a0d44ca95d9) with TalkBack on (was scrolling with 2 fingers).
The scroll was not responding and I had this crash in the log.

Couldn't reproduce this again.

## Logs

E/flutter ( 3509): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3509): 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 437: '_drag == null': is not true.
E/flutter ( 3509): #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
E/flutter ( 3509): #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
E/flutter ( 3509): #2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:437)
E/flutter ( 3509): #3      RawGestureDetectorState._handleSemanticsVerticalDragUpdate (package:flutter/src/widgets/gesture_detector.dart:674)
E/flutter ( 3509): #4      RenderSemanticsGestureHandler._performSemanticScrollUp (package:flutter/src/rendering/proxy_box.dart:3129)
E/flutter ( 3509): #5      SemanticsOwner.performAction (package:flutter/src/rendering/semantics.dart:865)
E/flutter ( 3509): #6      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handleSemanticsAction (package:flutter/src/rendering/binding.dart:188)
E/flutter ( 3509): #7      _invoke2 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:129)
E/flutter ( 3509): #8      _dispatchSemanticsAction (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:77)

Run `flutter analyze` and attach any output of that command also.

Analyzing 1277 files...
No analyzer warnings! (ran in 37.8s; 13 public members lack documentation)

## Flutter Doctor
$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /usr/local/google/home/amirha/git/flutter
    • Framework revision cbfed1960f (2 hours ago), 2017-10-25 07:18:09 -0700
    • Engine revision ec19da1c80
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /usr/local/google/home/amirha/Android/Sdk
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /usr/local/google/home/amirha/progs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /usr/local/google/home/amirha/progs/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Pixel • FA6890301419 • android-arm • Android 8.1.0 (API 27)

**Comment by zoechi** [comment]
Looks stale. Is this still relevant?

**Comment by CatEatFishs** [comment]
I have the same problem，how to solve it

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/hongka-liming/Downloads/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hongka-liming/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • COR AL00 • 6EJ7N18526001222 • android-arm64 • Android 9 (API 28)

**Comment by alexviquez** [comment]
I got this problem when inactive the scrollPhysics and touch the component who has this scroll inactivated

´´´
StreamBuilder(
            stream: bloc.places,
            initialData: [],
            builder: (context, snapshot) {
              if (snapshot.data == null) return Container();
              return StreamBuilder(
                stream: bloc.scrollable,
                initialData: true,
                builder: (context, scroll) =>
                    SingleChildScrollView(
                      controller: listScroll,
                      physics: scroll.data
                          ? NeverScrollableScrollPhysics()
                          : ClampingScrollPhysics(),
                      child: Column(
                        children: snapshot.data
                            .toList()
                            .map<Widget>((place) => _row(context, place, bloc))
                            .toList(),
                      ),
                    ),
              );
            },
          )
´´´

**Comment by TatsuUkraine** [comment]
@amirh exact same issue with exact same case as in prev example. It seems that when physics is changing, while scroll was in progress, it doesn't clear prev state of `drag` and `hold`

Code
```dart
StreamBuilder<double>(
          stream: _heightStream,
          initialData: _height.value,
          builder: (context, snapshot) {
            return Container(
              width: double.infinity,
              height: snapshot.data,
              color: Theme.of(context).canvasColor,
              child: CustomScrollView(
                controller: _scrollController,
                physics: _isOpened ? AlwaysScrollableScrollPhysics() : NeverScrollableScrollPhysics(),
                primary: false,
                slivers: widget.children,
              ),
            );
          }
        )
```

Exception
```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 480 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:480:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:359:44)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:359:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:236:7)
...
Handler: "onDown"
Recognizer: VerticalDragGestureRecognizer#d1f23
  start behavior: start
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by gesture ═══════════════════════════════════════════════════════════
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 489 pos 12: '_drag == null': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale
    ru-UA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by akshathjain** [comment]
@amirh Can we reopen this? I've been having the same issue in a very similar scenario to @TatsuUkraine while developing [sliding_up_panel](https://github.com/akshathjain/sliding_up_panel).

**Comment by TatsuUkraine** [comment]
@akshathjain btw, it seems flutter has built in widget that does exact same as your package

**Comment by akshathjain** [comment]
@TatsuUkraine yeah lol, I released my package before that was introduced (although I think that mine provides many more features)

**Comment by yonatann** [comment]
I am seeing the same issue, I recommend that this will be reopened.

**Comment by SouravDatta1995** [comment]
Seeing the same issue, recommended reopening this issue

**Comment by 8fdafs2** [comment]
Observing the same issue when attaching a ScrollController to a CustomScrollView widget.

**Comment by RaashVision** [comment]
Still having the same issue.

**Comment by amirc901** [comment]
Same issue here

**Comment by Flucadetena** [comment]
Still having the same problem! Please reopen this issue.

**Comment by gadearaujo** [comment]
Still having the same problem! Please reopen this issue.

**Comment by HeebeLee** [comment]
Please reopen this issue, Because I have almost the same code as @amirc901 , this problem still exists.

Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (6 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

**Comment by ivan-pavliuk** [comment]
Any updates?

**Comment by albrownwood** [comment]
same issue here, any updates?

**Comment by jja08111** [comment]
`animateTo` using `ScrollController` of `NestedScrollView` has same issue

**Comment by mregnauld** [comment]
Same issue here

**Comment by Gcii** [comment]
resolví el problema gracias a TatsuUcrania.
Efectivamente esto sucede cuando el scroll está en movimiento y se escribe "neverScrollable...". 
para solucionarlo utilicé timers justo antes de activar  "neverScrollable...".  y use otro timer justo después de desactivar.

**Comment by vytautas-pranskunas-** [comment]
same here

**Comment by vytautas-pranskunas-** [comment]
I needed to disable scrolling if calendar was expanded and needed enable scrolling ater calendar is minimized so I have found another workaround:

basically on swipe up I am moving list by 2 pixels up and adding if check atEgde

```
child: Listener(
                    onPointerMove: (PointerMoveEvent details) {
                      if (!_scrollController.position.atEdge &&
                          details.delta.dy < 0 &&
                          _ordersStore.calendarFormat != CalendarFormat.month) {
                        return;
                      }

                      if (_ordersStore.calendarFormat == CalendarFormat.month && _isSwipingUp(details)) {
                        _ordersStore.calendarFormat = CalendarFormat.week;
                        // Moving list up in order to be not atEdge otherways double list scroll error kicks in
                        _scrollController.animateTo(
                          2,
                          curve: Curves.ease,
                          duration: Duration(microseconds: 10),
                        );
                      }
}
```

also added conditional physics on ListView

```
physics: _ordersStore.calendarFormat == CalendarFormat.month
                                ? NeverScrollableScrollPhysics()
                                : ClampingScrollPhysics(),
```
