### ISSUE TITLE
Batch backfiller stops back filling tasks

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#127208]
<img width="1227" alt="Screenshot 2023-05-19 at 9 42 53 AM" src="https://github.com/flutter/flutter/assets/54558023/faba247b-f908-470f-b0de-2be7842f92bb">

From backend:
```
Bad state: No element
#0      ListBase.singleWhere (dart:collection/list.dart:167:5)
#1      BatchBackfiller.backfillRepository (package:cocoon_service/src/request_handlers/scheduler/batch_backfiller.dart:73:54)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      BatchBackfiller.get (package:cocoon_service/src/request_handlers/scheduler/batch_backfiller.dart:48:5)
<asynchronous suspension>
#4      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:50:24)
<asynchronous suspension>
#5      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:297:11)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
Suspicious culprit: https://github.com/flutter/cocoon/pull/2771 /cc @godofredoc . To unblock, switching to an older version.

**Comment by keyonghan** [comment]
Switched to an earlier version, and the logic is back. Lowering the priority to P2 to track the issue fix, otherwise this will break again on Monday.
