### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by JiangHongTiao** [flutter/flutter#127271]
I'm writing a project where I want to have a Menu with that pops up on long press and display list of available languages. 
The menu is horizontally scrollable:
![image](https://github.com/flutter/flutter/assets/14805613/666b08c8-0ba1-401a-8f83-9368e298a03c)

It works smoothly with simple widgets. However when I include complex widget tree that is built dynamically, it causes an error. 
Not sure which component causes that. 

Hope at least details below could help.

Error details:

```
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#4fd9e](state: OverlayState#5e756(entries: [OverlayEntry#e1a1a(opaque: true; maintainState: false), OverlayEntry#1227a(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5403 pos 14: '_dependents.isEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5403:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5405:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1982:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1984:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1980:13)
#10     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1992:7)
#11     Element.deactivateChild (package:flutter/src/widgets/framework.dart:3996:30)
#12     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6076:11)
#13     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#23     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#24     _invoke (dart:ui/hooks.dart:145:13)
#25     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#26     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
```
=================================================================================================

The menu widget:
```flutter
class QuickLanguageContextMenu extends StatefulWidget {
  final Widget child;
  final List<Language> languages;
  final double iconSize;
  final double height = 80.0;
  final LanguageSelectedTapCallback? onLanguageSelect;

  const QuickLanguageContextMenu({Key? key, required this.child, this.onLanguageSelect, required this.languages, this.iconSize = 24.0}) : super(key: key);

  @override
  State<QuickLanguageContextMenu> createState() => _QuickLanguageContextMenuState();
}

class _QuickLanguageContextMenuState extends State<QuickLanguageContextMenu> {
  Offset _globalPosition = Offset.zero;

  void _getTapPosition(TapDownDetails tapPosition) {
    setState(() {
      _globalPosition = tapPosition.globalPosition;
    });
  }

  void _showContextMenu(BuildContext context) async {
    final RenderObject? overlay = Overlay.of(context).context.findRenderObject();
    final overlaySize = overlay!.paintBounds.size;

    await showMenu(
      context: context,
      position: RelativeRect.fromRect(
        Rect.fromLTWH(_globalPosition.dx, _globalPosition.dy - widget.height, 100, 100),
        Rect.fromLTWH(0, 0, overlaySize.width, overlaySize.height),
      ),
      items: [
        PopupMenuItem(
          padding: EdgeInsets.zero,
          child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Row(
              children: List<Widget>.generate(
                widget.languages.length,
                (index) => _languageIconWidget(widget.languages[index]),
              ),
            ),
          ),
        ),
      ],
      elevation: 8.0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(10.0),
      ),
      color: Colors.white.withOpacity(0.3),
    );
  }

  Widget _languageIconWidget(Language language) {
    var l10n = L10n.fromLang(language);
    var textStyle = Theme.of(context).textTheme.labelSmall;

    return GestureDetector(
      behavior: HitTestBehavior.translucent,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 4.0),
        child: Column(
          children: [
            RichText(
              overflow: TextOverflow.ellipsis,
              textAlign: TextAlign.center,
              text: TextSpan(children: [
                WidgetSpan(
                  child: LangIcon(flag: l10n.flagsCode, width: widget.iconSize, height: widget.iconSize),
                ),
                const TextSpan(text: "\n"),
                TextSpan(text: l10n.language.languageName(), style: textStyle),
                const TextSpan(text: "\n"),
                TextSpan(text: l10n.language.languageNativeName(), style: textStyle),
              ]),
            ),
          ],
        ),
      ),
      onTap: () {
        widget.onLanguageSelect?.call(language);
        Navigator.pop(context);
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTapDown: (position) => {_getTapPosition(position)},
      onLongPress: () => {_showContextMenu(context)},
      onDoubleTap: () => {_showContextMenu(context)},
      child: widget.child,
    );
  }
}
```

**Comment by WitchOfDark** [comment]
You should post the code which gives error, what complex tree, how to dynamically change it
