### ISSUE TITLE
`Failed assertion: line 1966 pos 12: 'hasSize'` error when `SelectionOverlay.showToolbar`

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#127258]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

-

### Expected results

-

### Actual results

-

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by fzyzcjy** [comment]
Thanks for the reply, I will check that later

**Comment by fzyzcjy** [comment]
@darshankawar Hi, I can still reproduce it.

version

```
(base) ➜  bug /Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --version             
Flutter 3.11.0-12.0.pre.26 • channel main • https://github.com/flutter/flutter.git
Framework • revision 81971c961b (61 minutes ago) • 2023-05-23 20:49:25 -0400
Engine • revision 76afb431a7
Tools • Dart 3.1.0 (build 3.1.0-139.0.dev) • DevTools 2.23.1
```

logs

<details>

```
(base) ➜  bug /Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter test test/hi_test.dart
00:02 +0: should show custom magnifier on drag                                                                                 
_HackyWidgetState.build enable=false
hi 1
hi 2
_HackyWidgetState.build enable=true
hi 3
hi 4
_HackyWidgetState.build enable=false
hi 5
hi 6
_HackyWidgetState.build enable=true
hi 7
hi 8
hi 9 - 0
_HackyWidgetState.build enable=false
hi 9 - 1
_HackyWidgetState.build enable=true
hi 9 - 2
_HackyWidgetState.build enable=false
hi 9 - 3
_HackyWidgetState.build enable=true
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building
_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#a3f09](dirty, state:
_OverlayEntryWidgetState#939c3):
RenderBox was not laid out: RenderFractionalTranslation#231ad NEEDS-LAYOUT NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1966 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///Users/tom/RefCode/bug/test/hi_test.dart:160:12

When the exception was thrown, this was the stack:
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1966:12)
#3      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2988:24)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3174:24)
#5      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2616:39)
#6      SelectionOverlay.showToolbar.<anonymous closure> (package:flutter/src/widgets/text_selection.dart:1356:30)
#7      ContextMenuController.show.<anonymous closure> (package:flutter/src/widgets/context_menu_controller.dart:65:54)
#8      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:351:36)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6093:32)
#16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595:17)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#21     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#29     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#30     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#38     Element.rebuild (pa

...
```

</details>

code (test/hi_test.dart)

<details>

```
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_test/flutter_test.dart';

class HackyWidget extends StatefulWidget {
  final Widget child;

  const HackyWidget({Key? key, required this.child}) : super(key: key);

  @override
  State<HackyWidget> createState() => _HackyWidgetState();
}

class _HackyWidgetState extends State<HackyWidget> {
  final childKey = GlobalKey();

  // var enable = true;
  var enable = false;

  @override
  Widget build(BuildContext context) {
    print('$runtimeType.build enable=$enable');

    SchedulerBinding.instance.addPostFrameCallback((_) {
      if (mounted) setState(() => enable = !enable);
    });

    final inner = KeyedSubtree(key: childKey, child: widget.child);

    return enable
        ? FractionalTranslation(
      translation: Offset(0.1, 0.1),
      child: inner,
    )
        : inner;
  }
}


List<TextSelectionPoint> _globalize(
    Iterable<TextSelectionPoint> points, RenderBox box) {
  return points.map<TextSelectionPoint>((TextSelectionPoint point) {
    return TextSelectionPoint(
      box.localToGlobal(point.point),
      point.direction,
    );
  }).toList();
}

RenderEditable _findRenderEditable<T extends State<StatefulWidget>>(WidgetTester tester) {
  return (tester.state(find.byType(TextField))
  as TextSelectionGestureDetectorBuilderDelegate)
      .editableTextKey
      .currentState!
      .renderEditable;
}

Offset _textOffsetToPosition<T extends State<StatefulWidget>>(WidgetTester tester, int offset) {
  final RenderEditable renderEditable = _findRenderEditable(tester);

  final List<TextSelectionPoint> endpoints = renderEditable
      .getEndpointsForSelection(
    TextSelection.collapsed(offset: offset),
  )
      .map<TextSelectionPoint>((TextSelectionPoint point) => TextSelectionPoint(
    renderEditable.localToGlobal(point.point),
    point.direction,
  ))
      .toList();

  return endpoints[0].point + const Offset(0.0, -2.0);
}

void main() {
  const Duration durationBetweenActions = Duration(milliseconds: 20);
  const String defaultText = 'I am a magnifier, fear me!';

  Future<void> showMagnifier(WidgetTester tester, String characterToTapOn) async {
    final Offset tapOffset = _textOffsetToPosition(tester, defaultText.indexOf(characterToTapOn));

    print('hi 1');
    // Double tap 'Magnifier' word to show the selection handles.
    final TestGesture testGesture = await tester.startGesture(tapOffset);
    print('hi 2');
    await tester.pump(durationBetweenActions);
    print('hi 3');
    await testGesture.up();
    print('hi 4');
    await tester.pump(durationBetweenActions);
    print('hi 5');
    await testGesture.down(tapOffset);
    print('hi 6');
    await tester.pump(durationBetweenActions);
    print('hi 7');
    await testGesture.up();
    print('hi 8');
    // await tester.pumpAndSettle();
    for(var i=0;i<100;++i) {
      print('hi 9 - $i');
      await tester.pump(const Duration(milliseconds: 100));
    }

    final TextSelection selection = tester
        .firstWidget<TextField>(find.byType(TextField))
        .controller!
        .selection;

    final RenderEditable renderEditable = _findRenderEditable(tester);
    final List<TextSelectionPoint> endpoints = _globalize(
      renderEditable.getEndpointsForSelection(selection),
      renderEditable,
    );

    final Offset handlePos = endpoints.last.point + const Offset(10.0, 10.0);

    final TestGesture gesture = await tester.startGesture(handlePos);

    await gesture.moveTo(
      _textOffsetToPosition(
        tester,
        defaultText.length - 2,
      ),
    );
    await tester.pump();
  }

  testWidgets('should show custom magnifier on drag', (WidgetTester tester) async {
    // await tester.pumpWidget(const TextMagnifierExampleApp(text: defaultText));
    await tester.pumpWidget(HackyWidget(child: const TextMagnifierExampleApp(text: defaultText)));

    await showMagnifier(tester, 'e');
    expect(find.byType(CustomMagnifier), findsOneWidget);

    // await expectLater(
    //   find.byType(TextMagnifierExampleApp),
    //   matchesGoldenFile('text_magnifier.0_test.png'),
    // );
  });
}

class TextMagnifierExampleApp extends StatelessWidget {
  const TextMagnifierExampleApp({
    super.key,
    this.textDirection = TextDirection.ltr,
    required this.text,
  });

  final TextDirection textDirection;
  final String text;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 48.0),
          child: Center(
            child: TextField(
              textDirection: textDirection,
              // Create a custom magnifier configuration that
              // this `TextField` will use to build a magnifier with.
              magnifierConfiguration: TextMagnifierConfiguration(
                magnifierBuilder: (_, __, ValueNotifier<MagnifierInfo> magnifierInfo) => CustomMagnifier(
                  magnifierInfo: magnifierInfo,
                ),
              ),
              controller: TextEditingController(text: text),
            ),
          ),
        ),
      ),
    );
  }
}

class CustomMagnifier extends StatelessWidget {
  const CustomMagnifier({super.key, required this.magnifierInfo});

  static const Size magnifierSize = Size(200, 200);

  // This magnifier will consume some text data and position itself
  // based on the info in the magnifier.
  final ValueNotifier<MagnifierInfo> magnifierInfo;

  @override
  Widget build(BuildContext context) {
    // Use a value listenable builder because we want to rebuild
    // every time the text selection info changes.
    // `CustomMagnifier` could also be a `StatefulWidget` and call `setState`
    // when `magnifierInfo` updates. This would be useful for more complex
    // positioning cases.
    return ValueListenableBuilder<MagnifierInfo>(
        valueListenable: magnifierInfo,
        builder: (BuildContext context, MagnifierInfo currentMagnifierInfo, _) {
          // We want to position the magnifier at the global position of the gesture.
          Offset magnifierPosition = currentMagnifierInfo.globalGesturePosition;

          // You may use the `MagnifierInfo` however you'd like:
          // In this case, we make sure the magnifier never goes out of the current line bounds.
          magnifierPosition = Offset(
            clampDouble(
              magnifierPosition.dx,
              currentMagnifierInfo.currentLineBoundaries.left,
              currentMagnifierInfo.currentLineBoundaries.right,
            ),
            clampDouble(
              magnifierPosition.dy,
              currentMagnifierInfo.currentLineBoundaries.top,
              currentMagnifierInfo.currentLineBoundaries.bottom,
            ),
          );

          // Finally, align the magnifier to the bottom center. The initial anchor is
          // the top left, so subtract bottom center alignment.
          magnifierPosition -= Alignment.bottomCenter.alongSize(magnifierSize);

          return Positioned(
            left: magnifierPosition.dx,
            top: magnifierPosition.dy,
            child: RawMagnifier(
              magnificationScale: 2,
              // The focal point starts at the center of the magnifier.
              // We probably want to point below the magnifier, so
              // offset the focal point by half the magnifier height.
              focalPointOffset: Offset(0, magnifierSize.height / 2),
              // Decorate it however we'd like!
              decoration: const MagnifierDecoration(
                shape: StarBorder(
                  side: BorderSide(
                    color: Colors.green,
                    width: 2,
                  ),
                ),
              ),
              size: magnifierSize,
            ),
          );
        });
  }
}

```

</details>

**Comment by darshankawar** [comment]
Thanks for the update. I am still unable to replicate. Just to confirm, I copy paste the complete code you shared above and ran the app in debug mode which compiled and built the app and then started to run the tests. Is this a correct way to replicate the issue ? or are you doing anything different ?

**Comment by darshankawar** [comment]
Thanks for the update. Running the test code gives me the reported behavior.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.10.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.10.1 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (35 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.11.0-13.0.pre.21, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.11.0-13.0.pre.21 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e4104b094 (2 hours ago), 2023-05-24 23:09:20 -0400
    • Engine revision 62a83490ee
    • Dart version 3.1.0 (build 3.1.0-143.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by goderbauer** [comment]
@chunhtai FYI
