### ISSUE TITLE
[tool_crash] ProcessException: %1 n’est pas une application Win32 valide. Command: C:\Developpement\flutter-apps\martraff\android\gradlew.bat, OS error code: 193

### ISSUE THREAD

**Issue by mohmallahi** [flutter/flutter#127278]
## Command
```
flutter --no-color build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: %1 n’est pas une application Win32 valide.
 Command: C:\Developpement\flutter-apps\martraff\android\gradlew.bat, OS error code: 193
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:696:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:568:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:695:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:429:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:449:35)
#8      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:382:38)
#9      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:11)
#10     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:111:27)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[✓] Flutter (Channel stable, 3.7.10, on Microsoft Windows [version 10.0.19044.2965], locale fr-FR)
    • Flutter version 3.7.10 on channel stable at C:\Developpement\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (7 weeks ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\lenovo\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19044.2965]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.35

[!] HTTP Host Availability
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection terminated during handshake
    ✗ HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection terminated during handshake
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection terminated during handshake

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4b12645012342076800eb701bcdfe18f87da21cf
### Plugins
cloud_firestore-4.7.1
cloud_firestore_web-3.5.1
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
firebase_auth-4.6.1
firebase_auth_web-5.5.1
firebase_core-2.13.0
firebase_core_web-2.5.0
firebase_database-10.2.1
firebase_database_web-0.2.3+1
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.10
path_provider_windows-2.1.6
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
sqflite-2.2.8+4

**Comment by darshankawar** [comment]
I don't see a similar / exact tool crash issue with reported stack trace, so labeling for team's attention.

**Comment by eliasyishak** [comment]
Are you still experiencing this issue?

**Comment by andrewkolos** [comment]
Closing as stale.
