### ISSUE TITLE
Flutter tool "crashed" instead of displaying error when iOS Simulator was closed

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12738]
I had my iOS Simulator closed (maybe I closed it while `flutter run` was starting?)

And instead of a nice message I got a crash log:

```
Launching lib/main.dart on iPhone 6 in debug mode...
Running Xcode build...                               14.4s

Oops; flutter has exited unexpectedly: "Exit code 53 from: /usr/bin/xcrun simctl install 80FD76E9-4422-479B-B503-2EFE5C622125 /src/bug/build/ios/iphonesimulator/Runner.app:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=53):
Error returned in reply: Connection interrupted
Software caused connection abort".
Sending crash report to Google.
Crash report sent (report ID: bc87b60e323035df)
Crash report written to /src/bug/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

## command

flutter run

## exception

String: Exit code 53 from: /usr/bin/xcrun simctl install 80FD76E9-4422-479B-B503-2EFE5C622125 /src/bug/build/ios/iphonesimulator/Runner.app:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=53):
Error returned in reply: Connection interrupted
Software caused connection abort

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:242)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:129)
#2      IOSSimulator._buildAndInstallApplicationBundle (package:flutter_tools/src/ios/simulators.dart:419)
<asynchronous suspension>
#3      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:401)
<asynchronous suspension>
#4      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:323)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:267)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:211)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:348)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:253)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:193)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#16     run.<anonymous closure> (package:flutter_tools/executable.dart:145)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:116)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:68)
<asynchronous suspension>
#25     main (file:///src/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /src/flutter
    • Framework revision 154f2e5402 (3 hours ago), 2017-10-26 09:55:36 -0700
    • Engine revision ec19da1c80
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • iPhone 6 • 80FD76E9-4422-479B-B503-2EFE5C622125 • ios • iOS 10.3 (simulator)

```

**Comment by jonahwilliams** [comment]
This has since been fixed
