### ISSUE TITLE
Tried to make a child into a parent of itself.

### ISSUE THREAD

**Issue by jonny7737** [flutter/flutter#127385]
```
class UserInputController extends GetxController {
  late final FocusNode textFieldFocusNode;

  UserInputController() {
    textFieldFocusNode = FocusNode(
      onKey: (FocusNode node, RawKeyEvent evt) {
        if (!evt.isShiftPressed && evt.logicalKey.keyLabel == 'Enter') {
          if (evt is RawKeyDownEvent) {
            // sendMessage();
          }
          return KeyEventResult.handled;
        } else {
          return KeyEventResult.ignored;
        }
      },
    );
  }
}
```

```
 Expanded(
     child: TextField(
=>       focusNode: controller.textFieldFocusNode,
         minLines: 1,
         maxLines: 5,
         controller: TextEditingController(),
         decoration: const InputDecoration(
                hintText: 'Type a message...',
                border: OutlineInputBorder(),
          ),
     ),
 ),
```

When assigning the focusNode of a TextField:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building _ActionsScope:
Tried to make a child into a parent of itself.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 974 pos 12: 'child != this'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  TextField TextField:file:///Users/jonny/StudioProjects/collab_chat/lib/screens/widgets/user_input_widget.dart:42:20
When the exception was thrown, this was the stack: 
#2      FocusNode._reparent (package:flutter/src/widgets/focus_manager.dart:974:12)
#3      FocusAttachment.reparent (package:flutter/src/widgets/focus_manager.dart:235:14)
#4      _FocusState.didChangeDependencies (package:flutter/src/widgets/focus_scope.dart:576:23)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5237:11)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (63 frames)
#69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#71     SlottedRenderObjectElement._updateChildren (package:flutter/src/widgets/slotted_render_object_widget.dart:270:33)
#72     SlottedRenderObjectElement.mount (package:flutter/src/widgets/slotted_render_object_widget.dart:224:5)
...     Normal element mounting (70 frames)
#142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#143    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#144    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (19 frames)
#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#164    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#165    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (73 frames)
#238    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#239    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#240    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (159 frames)
#399    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#400    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#401    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (178 frames)
#579    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#580    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#581    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (503 frames)
#1084   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#1085   Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#1086   RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1240:16)
#1087   RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1209:5)
#1088   RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1156:18)
#1089   BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720:19)
#1090   RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1155:13)
#1091   WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:988:7)
#1092   WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:7)
#1096   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================
```

**Comment by tomg2012** [comment]
Hi, I'm unable to reproduce this scenario with the code provided. I tried the code snippets and they seem to work by themselves. Can you please provide the following information:

1. The output of ` flutter doctor -v `
2. A complete test app that reproduces this error (bare minimum app).

Thanks!

**Comment by huycozy** [comment]
Hi @jonny7737 
As the suggestion above, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thanks!

**Comment by jonny7737** [comment]
As stated above, i will provide the requested minimal example code as soon as i can.

Also, the entire reason for filing this bug report is included in theinitial post - I was requested to do so:

"Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
"
