### ISSUE TITLE
Engine 3.10.1 source cannot be downloaded

### ISSUE THREAD

**Issue by RossComputerGuy** [flutter/flutter#127348]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Follow the wiki and use engine commit b4fb11214dd2dda6ce012dd98ea498e9e8b91262
2. `gn sync`

### Expected results

All source code should be downloaded

### Actual results

It appears https://chromium.googlesource.com/external/fontconfig is being downloaded but no longer exists.

Relevant line in [DEPS](https://github.com/flutter/engine/blob/b4fb11214dd2dda6ce012dd98ea498e9e8b91262/DEPS#L582). Replacing this to use https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/c336b8471877371f0190ba06f7547c54e2b890ba actually works.

```
src/third_party/fontconfig/src (ERROR)
----------------------------------------
[0:00:29] Started.
[0:00:29]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/fontconfig.git /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/_gclient_src_8rg0yybl' in '/home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1'

[0:00:29] Cloning into '/home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/_gclient_src_8rg0yybl'...
[0:00:29] remote: PERMISSION_DENIED: The caller does not have permission
[0:00:29] remote: [type.googleapis.com/google.rpc.RequestInfo]
[0:00:29] remote: request_id: "d08334a931bb4cf5b02b34b75a48b558"
[0:00:29] fatal: Authentication failed for 'https://chromium.googlesource.com/external/fontconfig.git/'
[0:00:31]
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/fontconfig.git /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/_gclient_src_8rg0yybl' in '/home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1' attempt 2 / 2

[0:00:31] Cloning into '/home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/_gclient_src_8rg0yybl'...
[0:00:32] remote: PERMISSION_DENIED: The caller does not have permission
[0:00:32] remote: [type.googleapis.com/google.rpc.RequestInfo]
[0:00:32] remote: request_id: "ef9c0b17698d46ce8dccf9a790364085"
[0:00:32] fatal: Authentication failed for 'https://chromium.googlesource.com/external/fontconfig.git/'
Traceback (most recent call last):
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_scm.py", line 1169, in _Clone
    self._Run(clone_cmd,
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_scm.py", line 1515, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_utils.py", line 715, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/fontconfig.git /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/_gclient_src_8rg0yybl' returned non-zero exit status 128 in /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1
[0:00:36] _____ Conflicting directory found in /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/src. Moving to /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/_bad_scm/src/third_party/fontconfig/srcssrxuv5b.
----------------------------------------


Warnings:
Conflicting directory /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/src moved to /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/_bad_scm/src/third_party/fontconfig/srcssrxuv5b.
Traceback (most recent call last):
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_scm.py", line 647, in update
    self._Clone(revision, url, options)
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_scm.py", line 1169, in _Clone
    self._Run(clone_cmd,
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_scm.py", line 1515, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_utils.py", line 715, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/fontconfig.git /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/_gclient_src_8rg0yybl' returned non-zero exit status 128 in /home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/rpri9nb8xpwwqakyrqbg8zdslkjs2hd3-python3-3.10.11/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/src' -> '/home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/_bad_scm/src/third_party/fontconfig/srcssrxuv5b/src'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/metrics.py", line 301, in print_notice_and_exit
    yield
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient.py", line 3536, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient.py", line 3522, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient.py", line 3073, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient.py", line 2036, in RunOnDeps
    work_queue.flush(revision_overrides,
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_utils.py", line 1016, in flush
    reraise(e[0], e[1], e[2])
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_utils.py", line 70, in reraise
    raise value
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_utils.py", line 1093, in run
    self.item.run(*self.args, **self.kwargs)
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient.py", line 1011, in run
    self._got_revision = self._used_scm.RunCommand(command, options, args,
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_scm.py", line 128, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_scm.py", line 650, in update
    self._DeleteOrMove(options.force)
  File "/home/ross/ExpidusOS/neutron/vendor/bindings/zig-flutter/src/depot_tools/gclient_scm.py", line 203, in _DeleteOrMove
    shutil.move(self.checkout_path, dest_path)
  File "/nix/store/rpri9nb8xpwwqakyrqbg8zdslkjs2hd3-python3-3.10.11/lib/python3.10/shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "/nix/store/rpri9nb8xpwwqakyrqbg8zdslkjs2hd3-python3-3.10.11/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/rpri9nb8xpwwqakyrqbg8zdslkjs2hd3-python3-3.10.11/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ross/ExpidusOS/neutron/zig-cache/o/5699f17aa00f8a66a9ba79a14eb27dc1/src/third_party/fontconfig/src'
```

### Code sample

N/A

### Screenshots or Video

Went to the Chromium source page and tried logging in with my Google Account.

![image](https://github.com/flutter/flutter/assets/19699320/6be3041b-4840-4128-b5d2-25b46411071c)

### Logs

<details><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
N/A
```

</details>

**Comment by huycozy** [comment]
Hi @RossComputerGuy 
Looks like it can not pull that repository. I try cloning it manually and it's successful without authentication. Can you also try doing that? (pulling repository manually)

**Comment by RossComputerGuy** [comment]
Yeah, it's working now with `gclient`, `git`, and the website.
