### ISSUE TITLE
We don't handle calling setState in State subclass constructor

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#12731]
The constructor of the StatefulWidget widget executing this code and get and `NoSuchMethodError`
I think there should be a better error message. This was in a bigger project and it took me quite a while to find this.

```class _MyHomePageState extends State<MyHomePage> {
  bool _isDone;

  _MyHomePageState(){
    var controller = new TextEditingController();
    setState(()=> _isDone = controller.text.isEmpty);
  }
```

This is the Exception:

```
+1092 ms] I/flutter ( 3715): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +13 ms] I/flutter ( 3715): The following NoSuchMethodError was thrown building _ModalScopeStatus(active):
[        ] I/flutter ( 3715): The method 'markNeedsBuild' was called on null.
[        ] I/flutter ( 3715): Receiver: null
[        ] I/flutter ( 3715): Tried calling: markNeedsBuild()
[  +54 ms] I/flutter ( 3715): 
[        ] I/flutter ( 3715): When the exception was thrown, this was the stack:
[  +35 ms] I/flutter ( 3715): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
[        ] I/flutter ( 3715): #1      State.setState (package:flutter/src/widgets/framework.dart:1178)
[        ] I/flutter ( 3715): #2      new _MyHomePageState (file:///C:/Projects/simpletest/lib/main.dart:52)
[        ] I/flutter ( 3715): #3      MyHomePage.createState (file:///C:/Projects/simpletest/lib/main.dart:44)
[        ] I/flutter ( 3715): #4      new StatefulElement (package:flutter/src/widgets/framework.dart:3620)`

```
This is the man.dart code to reproduce:

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or press Run > Flutter Hot Reload in IntelliJ). Notice that the
        // counter didn't reset back to zero; the application is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _isDone;

  _MyHomePageState(){
    var controller = new TextEditingController();
    setState(()=> _isDone = controller.text.isEmpty);
  }

  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: new Text(widget.title),
      ),
      body: new Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: new Column(
          // Column is also layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug paint" (press "p" in the console where you ran
          // "flutter run", or select "Toggle Debug Paint" from the Flutter tool
          // window in IntelliJ) to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by Hixie** [comment]
Workaround: Move any logic you have in State constructors to the initState method.

**Comment by ride4sun** [comment]
yes I know, I was more concerned about the error message because I am probably not the only one doing this.
