### ISSUE TITLE
Flutter_markdown throws assertion for footnotes with latest `markdown`

### ISSUE THREAD

**Issue by Cellaryllis** [flutter/flutter#127425]
Hello,

I updated our project to 3.10 and noticed that some of our tests failed which I tracked down to some specific syntax that we have in some test widgets to test markdown. Namely the following:

```
Footnote 1 link[^first].
[^first]: Footnote **can have markup**
```

Now I am quite certain that footnotes aren't supported, but at least there shouldn't be an assertion. Full markdown source is here: https://sarveshh.github.io/markdownerr/

![image](https://github.com/flutter/flutter/assets/95936504/f587f898-6b2f-42bf-92df-eb44e20af903)
![image](https://github.com/flutter/flutter/assets/95936504/057ddddf-6214-4d55-a45d-348ea528492e)

I looked to see if this was elsewhere reported but I couldn't find it, if it was already reported please close this one :)

Steps to reproduce:

Create a widget and add:
```
MarkdownBody(
        data: text,
);
```
Text being the above text or a copy paste from the URL referenced.

Thanks for any input you can have on this!

**Comment by Cellaryllis** [comment]
I want to add, we noticed this in 3.10, our production app in 3.7 does not show this.
I quickly did some more dependency checks and I noticed a discrepancy between flutter_markdown and the dependency markdown.

flutter_markdown wants 7.0.0, but our dependency was 7.1.0, probably from another package. 
I added
```
dependency_overrides:
  markdown: 7.0.0
```
which seems to have fixed it. So I suppose this can be closed?

**Comment by stuartmorgan** [comment]
> flutter_markdown wants 7.0.0

`^7.0.0` means any 7.x.x version, not exactly 7.0.0. `pub` will get the latest resolvable version any time you `pub upgrade`.

> So I suppose this can be closed?

It depends on whether it's a bug in `markdown`, or a latent bug in `flutter_markdown` that the update to `markdown` exposed. The code in the screenshot suggests that the latter is plausible, since it's using `!` without any obvious local check that doing so is safe.

**Comment by Cellaryllis** [comment]
The `!` does feel unsafe, especially when you look at [this code in flutter_markdown](https://github.com/flutter/packages/blob/fba97fa4cc86a2100a06a58205a5ccb366101cdc/packages/flutter_markdown/lib/src/builder.dart#L180), a null entry is explicitly being added. I will admit I have no idea why and I'm sure there's a reason for it but considering it's using `!` further down it feels like a possible issue.

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate this on stable 3.7.12, 3.10.1 and latest master.

<details>
<summary> runnable code sample </summary>

```




import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MinimalMarkdownDemo(),
    );
  }
}

const String _data = '''
Footnote 1 link[^first].
[^first]: Footnote **can have markup**
''';

class MinimalMarkdownDemo extends StatelessWidget {
  const MinimalMarkdownDemo({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Markdown Demo')),
      body: MarkdownBody(
        styleSheet: MarkdownStyleSheet(
          h1Align: WrapAlignment.center,
          h2Align: WrapAlignment.end,
        ),
        data: _data,
      ),
    );
  }
}

```

</details>

<details>
<summary> console error log </summary>

```

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:58728/fs3nEKpPKvc=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation(12498): eglMakeCurrent: 0xe4d80480: ver 3 0 (tinfo 0xc0957260)

======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building KeyedSubtree-[GlobalKey#0801c]:
Null check operator used on a null value

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///Users/dhs/Documents/NCFlutter/dummy_test/lib/main.dart:34:12
When the exception was thrown, this was the stack: 
#0      MarkdownBuilder._addParentInlineIfNeeded (package:flutter_markdown/src/builder.dart:614:37)
#1      MarkdownBuilder.visitElementBefore (package:flutter_markdown/src/builder.dart:255:7)
#2      Element.accept (package:markdown/src/ast.dart:47:17)
#3      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:184:12)
#4      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:340:25)
#5      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:284:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5237:11)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (25 frames)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#33     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (330 frames)
#364    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#365    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#366    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (467 frames)
#833    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#834    Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#835    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1253:16)
#836    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1222:5)
#837    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1169:18)
#838    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720:19)
#839    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1168:13)
#840    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1001:7)
#841    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:981:7)
#845    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
D/EGL_emulation(12498): eglMakeCurrent: 0xe4d71840: ver 3 0 (tinfo 0xd97cac90)

```

</details>

While adding the package `flutter pub add flutter_markdown`, it adds `markdown version 7.1.0`:

```
dhs@Dhss-MacBook-Pro dummy_test % flutter pub add flutter_markdown
Resolving dependencies... 
+ args 2.4.1
  csslib 0.17.2 (0.17.3 available)
+ flutter_markdown 0.6.14
  go_router 7.0.1 (7.1.1 available)
  lints 2.0.0 (2.1.0 available)
  logging 1.1.1 (1.2.0 available)
+ markdown 7.1.0
  matcher 0.12.15 (0.12.16 available)

```

As mentioned above, adding dependency_override seems to resolve the issue:

I added to pubspec:

```
dependency_overrides:
  markdown: 7.0.0
```

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.10.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.10.1 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (35 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.11.0-12.0.pre.28, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.11.0-12.0.pre.28 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 216605b60f (63 minutes ago), 2023-05-23 23:40:27 -0400
    • Engine revision eebcf36cd3
    • Dart version 3.1.0 (build 3.1.0-139.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>
