### ISSUE TITLE
Assertion failed with an empty DropdownButton

### ISSUE THREAD

**Issue by blastrock** [flutter/flutter#12740]
## Steps to Reproduce

```dart
new DropdownButton(
                        value: null,
                        items: [],
                      )
```

## Logs

```
I/flutter ( 5322): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5322): The following assertion was thrown during performLayout():
I/flutter ( 5322): RenderIndexedStack object was given an infinite size during layout.
I/flutter ( 5322): This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter ( 5322): inside another render object that allows its children to pick their own size.
I/flutter ( 5322): The nearest ancestor providing an unbounded width constraint is:
I/flutter ( 5322):   RenderFlex#d3d9f relayoutBoundary=up31 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 5322):   creator: Row ← SizedBox ← DefaultTextStyle ← Stack ← Listener ← _GestureSemantics ←
I/flutter ( 5322):   RawGestureDetector ← GestureDetector ← DropdownButton ← Expanded ← Row ← Column ← ⋯
I/flutter ( 5322):   parentData: <none> (can use size)
I/flutter ( 5322):   constraints: BoxConstraints(0.0<=w<=214.0, 0.0<=h<=Infinity)
I/flutter ( 5322):   size: Size(214.0, Infinity)
I/flutter ( 5322):   direction: horizontal
I/flutter ( 5322):   mainAxisAlignment: space-between
I/flutter ( 5322):   mainAxisSize: min
I/flutter ( 5322):   crossAxisAlignment: center
I/flutter ( 5322):   textDirection: ltr
I/flutter ( 5322):   verticalDirection: down
I/flutter ( 5322): The nearest ancestor providing an unbounded height constraint is:
I/flutter ( 5322):   _RenderSingleChildViewport#fbd29 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 5322):   creator: _SingleChildViewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#05361] ← Listener ←
I/flutter ( 5322):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#825d9] ←
I/flutter ( 5322):   RepaintBoundary ← CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification> ←
I/flutter ( 5322):   GlowingOverscrollIndicator ← Scrollable ← ⋯
I/flutter ( 5322):   parentData: <none> (can use size)
I/flutter ( 5322):   constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=512.0)
I/flutter ( 5322):   layer: OffsetLayer#3386c
I/flutter ( 5322):   size: Size(360.0, 512.0)
I/flutter ( 5322): The constraints that applied to the RenderIndexedStack were:
I/flutter ( 5322):   BoxConstraints(unconstrained)
I/flutter ( 5322): The exact size it was given was:
I/flutter ( 5322):   Size(Infinity, Infinity)
I/flutter ( 5322): See https://flutter.io/layout/ for more information.
I/flutter ( 5322): When the exception was thrown, this was the stack:
I/flutter ( 5322): #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1685:9)
I/flutter ( 5322): #1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1759:6)
I/flutter ( 5322): #2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1494:17)
I/flutter ( 5322): #3      RenderBox.size= (package:flutter/src/rendering/box.dart:1494:65)
I/flutter ( 5322): #4      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:481:7)
I/flutter ( 5322): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #6      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:737:15)
I/flutter ( 5322): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #8      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:257:13)
I/flutter ( 5322): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #10     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:466:15)
I/flutter ( 5322): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #12     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #14     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #16     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:797:17)
I/flutter ( 5322): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #18     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:737:15)
I/flutter ( 5322): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #20     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:197:11)
I/flutter ( 5322): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #22     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #24     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #26     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:466:15)
I/flutter ( 5322): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #28     RenderAnimatedSize.performLayout (package:flutter/src/rendering/animated_size.dart:168:11)
I/flutter ( 5322): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #30     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #31     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1005:24)
I/flutter ( 5322): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #33     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:737:15)
I/flutter ( 5322): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #35     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:197:11)
I/flutter ( 5322): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #37     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #39     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #41     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1005:24)
I/flutter ( 5322): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #44     RenderListBody.performLayout (package:flutter/src/rendering/list_body.dart:142:15)
I/flutter ( 5322): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #46     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #48     RenderListBody.performLayout (package:flutter/src/rendering/list_body.dart:142:15)
I/flutter ( 5322): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #50     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:197:11)
I/flutter ( 5322): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #52     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:737:15)
I/flutter ( 5322): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #54     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:197:11)
I/flutter ( 5322): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #56     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:315:13)
I/flutter ( 5322): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #58     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #60     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #62     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #64     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #66     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #68     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #70     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124:11)
I/flutter ( 5322): #71     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:91:7)
I/flutter ( 5322): #72     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
I/flutter ( 5322): #73     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
I/flutter ( 5322): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #75     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #77     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #78     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1005:24)
I/flutter ( 5322): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #80     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #82     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #84     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #86     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #87     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2749:26)
I/flutter ( 5322): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #89     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #91     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:466:15)
I/flutter ( 5322): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #93     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #95     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #97     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #99     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #101    RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5322): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1969:7)
I/flutter ( 5322): #103    RenderView.performLayout (package:flutter/src/rendering/view.dart:142:13)
I/flutter ( 5322): #104    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1844:7)
I/flutter ( 5322): #105    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1133:18)
I/flutter ( 5322): #106    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:262:19)
I/flutter ( 5322): #107    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:581:22)
Reloaded 1 of 473 libraries in 1,929ms.
I/flutter ( 5322): #108    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:200:5)
I/flutter ( 5322): #109    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713:15)
I/flutter ( 5322): #110    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649:9)
I/flutter ( 5322): #111    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/rendering/binding.dart:286:20)
I/flutter ( 5322): #113    _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:367)
I/flutter ( 5322): #114    _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:401)
I/flutter ( 5322): #115    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
I/flutter ( 5322): (elided one frame from package dart:async-patch)
I/flutter ( 5322): The following RenderObject was being processed when the exception was fired:
I/flutter ( 5322):   RenderIndexedStack#33407 relayoutBoundary=up32 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 5322):   creator: IndexedStack ← Row ← SizedBox ← DefaultTextStyle ← Stack ← Listener ← _GestureSemantics ←
I/flutter ( 5322):   RawGestureDetector ← GestureDetector ← DropdownButton ← Expanded ← Row ← ⋯
I/flutter ( 5322):   parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
I/flutter ( 5322):   constraints: BoxConstraints(unconstrained)
I/flutter ( 5322):   size: Size(Infinity, Infinity)
I/flutter ( 5322):   alignment: Alignment.centerLeft
I/flutter ( 5322):   textDirection: ltr
I/flutter ( 5322):   fit: loose
I/flutter ( 5322):   overflow: clip
I/flutter ( 5322):   index: null
I/flutter ( 5322): This RenderObject has no descendants.
I/flutter ( 5322): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/blastrock/packages/flutter
    • Framework revision 4424892c79 (2 weeks ago), 2017-10-10 16:45:11 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/blastrock/android-sdk-linux
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /home/blastrock/android-sdk-linux
    • Java binary at: /home/blastrock/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/blastrock/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • Nexus 5 • 02c2b28ed02107dc • android-arm • Android 6.0.1 (API 23)

**Comment by shadowsheep1** [comment]
Even just with one required parameters, you get a rendering problem:

- `DropdownButton(items: [], onChanged: (int) {})`
- `DropdownButton(items: itemList, onChanged: null)`
- `DropdownButton(items: [], onChanged: null)`

**Comment by HansMuller** [comment]
This was (finally) fixed by @jimshepherd  in https://github.com/flutter/flutter/pull/26143
