### ISSUE TITLE
Flutter desktop error

### ISSUE THREAD

**Issue by HimorriveL** [flutter/flutter#127612]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. On Visual Studio Code, Press F1
2. Flutter: New Project
3. flutter run -d windows

### Actual results

Exception: Build process failed.

### Logs

<details>
<summary>Logs</summary>

```console

D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client> flutter --version
Flutter 3.11.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 350d2c3a6c (2 days ago) • 2023-05-23 15:52:05 -0700
Engine • revision 7eca5cd1c5
Tools • Dart 3.1.0 (build 3.1.0-63.1.beta) • DevTools 2.23.1

D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client> flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
Building Windows application...                                  2.767ms
Exception: Build process failed.

D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client> flutter run -d windows --verbose
[   +2 ms] executing: [D:\flutter_sdk_3.10.2/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 350d2c3a6ca4c3c39787e1c18a8ddf0aca8d2ae2
[        ] executing: [D:\flutter_sdk_3.10.2/] git tag --points-at 350d2c3a6ca4c3c39787e1c18a8ddf0aca8d2ae2
[  +72 ms] Exit code 0 from: git tag --points-at 350d2c3a6ca4c3c39787e1c18a8ddf0aca8d2ae2
[        ] 3.11.0-0.1.pre
[   +2 ms] executing: [D:\flutter_sdk_3.10.2/] git rev-parse --abbrev-ref HEAD
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +59 ms] executing: [D:\flutter_sdk_3.10.2/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/beta
[        ] executing: [D:\flutter_sdk_3.10.2/] git ls-remote --get-url origin
[  +58 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +103 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +79 ms] Skipping pub get: version match.
[  +25 ms] Found plugin desktop_window at C:\Users\Rodrigo\AppData\Local\Pub\Cache\hosted\pub.dev\desktop_window-0.4.0\
[ +122 ms] Found plugin desktop_window at C:\Users\Rodrigo\AppData\Local\Pub\Cache\hosted\pub.dev\desktop_window-0.4.0\
[  +36 ms] Found plugin desktop_window at C:\Users\Rodrigo\AppData\Local\Pub\Cache\hosted\pub.dev\desktop_window-0.4.0\
[  +77 ms] Generating
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +83 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +5 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated
contents:
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\.dart_tool\package_config_subset}
[  +12 ms] Found plugin desktop_window at C:\Users\Rodrigo\AppData\Local\Pub\Cache\hosted\pub.dev\desktop_window-0.4.0\
[  +19 ms] gen_dart_plugin_registrant: Complete
[   +2 ms] Skipping target: _composite
[   +1 ms] complete
[   +4 ms] Launching lib\main.dart on Windows in debug mode...
[   +3 ms] D:\flutter_sdk_3.10.2\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\flutter_sdk_3.10.2\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
D:\flutter_sdk_3.10.2\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/7eca5cd1c5cca97929a7c8ea4381441447a36f26/ --output-dill      
C:\Users\Rodrigo\AppData\Local\Temp\flutter_tools.96d6b5d3\flutter_tool.585d1014\app.dill --packages
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root     
--initialize-from-dill build\effb9e9476fd16260fdd8a35f26268c7.cache.dill.track.dill --verbosity=error
--enable-experiment=alternative-invalidation-strategy
[  +26 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest
-version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.VC.CMake.Project
[  +54 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8
-latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64      
Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "48f66ff5",
               "installDate": "2023-04-24T21:54:15Z",
               "installationName": "VisualStudio/17.6.1+33717.318",
               "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "installationVersion": "17.6.33717.318",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "IDE avançado, gratuito para estudantes, colaboradores de software livre e indivíduos",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelId": "VisualStudio.17.Release",
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.6#17.6.1",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2023-05-24T17:46:49.4789005Z",
               "catalog": {
                 "buildBranch": "d17.6",
                 "buildVersion": "17.6.33717.318",
                 "id": "VisualStudio/17.6.1+33717.318",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.6.1",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "1",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "17.6.1+33717.318",
                 "requiredEngineVersion": "3.6.2115.31769"
               },
               "properties": {
                 "campaignId": "2030:d512d5eaf0ad448ea6dde8b196786419",
                 "channelManifestId": "VisualStudio.17.Release/17.6.1+33717.318",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +5 ms] Building Windows application...
[  +12 ms] <- compile package:food_system_frontend_client/main.dart
[   +1 ms] executing: C:\Program Files\Microsoft Visual
Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows -B build\windows -G Visual Studio 
17 2022
[  +62 ms] -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
[  +20 ms] -- Configuring done (0.0s)
[ +230 ms] -- Generating done (0.2s)
[  +16 ms] -- Build files have been written to:
D:/JavaScript/JavaScript/Projetos/Desenvolvimento/FoodSystem/food_system_frontend_client/build/windows
[   +7 ms] executing: C:\Program Files\Microsoft Visual
Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build build\windows --config Debug        
--target INSTALL --verbose
[ +137 ms] MSBuild version 17.6.3+07e294721 for .NET Framework
[ +269 ms] Compila��o de 25/05/2023 16:21:53 iniciada.
[+1038 ms] Projeto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\INSTALL.vcxproj" no n� 1   
(destinos padr�o).
[   +1 ms] O projeto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\INSTALL.vcxproj" (1) est�  
compilando
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\ZERO_CHECK.vcxproj" (2) no 
n� 1 (destinos padr�o).
[   +1 ms] InitializeBuildStatus:
[        ]   Criando "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
[  +56 ms] CustomBuild:
[        ]   Todas as sa�das est�o atualizadas.
[  +46 ms] FinalizeBuildStatus:
[        ]   Excluindo o arquivo "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[        ]   Tocando "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
[   +4 ms] Projeto de compila��o pronto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\ZERO_CHECK.vcxproj"        
(destinos padr�o).
[  +95 ms] O projeto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\INSTALL.vcxproj" (1) est�  
compilando
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\ALL_BUILD.vcxproj" (3) no  
n� 1 (destinos padr�o).
[   +1 ms] O projeto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\ALL_BUILD.vcxproj" (3) est�compilando
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\plugins\desktop_window\desktop_window_plugin.vcxproj" (4) no n� 1 (destinos padr�o).
[   +1 ms] O projeto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\plugins\desktop_window\desktop_window_plugin.vcxproj" (4) est� compilando
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_assemble.vcxproj" (5) no n� 1 (destinos padr�o).
[   +1 ms] InitializeBuildStatus:
[        ]   Criando "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.  
[   +7 ms] CustomBuild:
[        ]   "O build de
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\CMakeFiles\1a923473dab979b56bac59e32a3f71e0\flutter_assemble.rule' depende de
'D:\JAVASCRIPT\JAVASCRIPT\PROJETOS\DESENVOLVIMENTO\FOODSYSTEM\FOOD_SYSTEM_FRONTEND_CLIENT\WINDOWS\FLUTTER\EPHEMERAL\FLUTTER_WINDOWS.DLL', que � gerado pelo build de
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\CMakeFiles\c3e7b7da6fa0bf2ee57809ad8f8fb31f\flutter_windows.dll.rule'. Os itens n�o podem ser compilados em paralelo."
[ +106 ms] FinalizeBuildStatus:
[        ]   Excluindo o arquivo "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
[        ]   Tocando "x64\Debug\flutter_assemble\flutter_assemble.tlog\flutter_assemble.lastbuildstate".
[        ] Projeto de compila��o pronto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_assemble.vcxproj" (destinos padr�o).
[  +30 ms] O projeto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\plugins\desktop_window\desktop_window_plugin.vcxproj" (4) est� compilando
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (6) no n� 1 (destinos padr�o).
[   +1 ms] InitializeBuildStatus:
[        ]   Tocando "flutter_wrapper_plugin.dir\Debug\flutter_.1AEC90FF.tlog\unsuccessfulbuild".
[        ] CustomBuild:
[        ]   Todas as sa�das est�o atualizadas.
[  +69 ms] ClCompile:
[   +1 ms]   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\CL.exe /c
/ID:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\include /ID:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral  
/Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D _DEBUG /D     
UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR      
/std:c++17 /Fo"flutter_wrapper_plugin.dir\Debug\\"
/Fd"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\Debug\flutter_wrapper_plugin.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\core_implementations.cc
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\standard_codec.cc
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\plugin_registrar.cc
[  +70 ms]   core_implementations.cc
[  +41 ms] c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\core_implementations.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_plugin.vcxproj]
[ +124 ms]   standard_codec.cc
[   +6 ms] c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\standard_codec.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_plugin.vcxproj]
[   +2 ms]   plugin_registrar.cc
[   +6 ms] c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\plugin_registrar.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_plugin.vcxproj]
[   +2 ms]   Gerando C�digo...
[  +40 ms] Projeto de compila��o pronto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (destinos padr�o) -- FALHA.
[   +1 ms] Projeto de compila��o pronto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\plugins\desktop_window\desktop_window_plugin.vcxproj" (destinos padr�o) -- FALHA.
[  +31 ms] O projeto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\ALL_BUILD.vcxproj" (3) est�compilando
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj" (7) no n� 1 (destinos padr�o).
[   +1 ms] InitializeBuildStatus:
[        ]   Tocando "flutter_wrapper_app.dir\Debug\flutter_.B2785BD1.tlog\unsuccessfulbuild".
[   +1 ms] CustomBuild:
[        ]   Todas as sa�das est�o atualizadas.
[  +14 ms] ClCompile:
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\CL.exe /c
/ID:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\include /ID:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral  
/Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D _DEBUG /D     
UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR      
/std:c++17 /Fo"flutter_wrapper_app.dir\Debug\\"
/Fd"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\Debug\flutter_wrapper_app.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\core_implementations.cc
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\standard_codec.cc
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\flutter_engine.cc
D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\flutter_view_controller.cc
[  +64 ms]   core_implementations.cc
[   +8 ms] c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\core_implementations.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj]
[   +3 ms]   standard_codec.cc
[   +6 ms] c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\standard_codec.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj]
[   +2 ms]   flutter_engine.cc
[   +7 ms] c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\flutter_engine.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj]
[   +2 ms]   flutter_view_controller.cc
[   +6 ms] c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\flutter_view_controller.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj]
[   +1 ms]   Gerando C�digo...
[  +22 ms] Projeto de compila��o pronto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj" (destinos padr�o) -- FALHA.
[  +35 ms] Projeto de compila��o pronto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\ALL_BUILD.vcxproj"
(destinos padr�o) -- FALHA.
[   +1 ms] Projeto de compila��o pronto
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\INSTALL.vcxproj" (destinos 
padr�o) -- FALHA.
[  +26 ms] FALHA da compila��o.
[   +5 ms] "D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\INSTALL.vcxproj"(destino padr�o) (1) ->
[        ]
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\ALL_BUILD.vcxproj" (destinopadr�o) (3) ->
[        ]
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\plugins\desktop_window\desktop_window_plugin.vcxproj" (destino padr�o) (4) ->
[        ]
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (destino padr�o) (6) ->
[        ] (ClCompile destino) ->
[        ]   c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\core_implementations.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_plugin.vcxproj]
[   +1 ms]   c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\standard_codec.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_plugin.vcxproj]
[   +1 ms]   c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\plugin_registrar.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_plugin.vcxproj]
[   +1 ms] "D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\INSTALL.vcxproj"(destino padr�o) (1) ->
[        ]
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\ALL_BUILD.vcxproj" (destinopadr�o) (3) ->
[        ]
"D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj" (destino padr�o) (7) ->
[   +1 ms]   c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\core_implementations.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj]
[   +1 ms]   c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\standard_codec.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj]
[   +1 ms]   c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\flutter_engine.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj]
[   +1 ms]   c1xx : fatal  error C1083: N�o � poss�vel abrir arquivo fonte:
'D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\windows\flutter\ephemeral\cpp_client_wrapper\flutter_view_controller.cc': No such file or directory
[D:\JavaScript\JavaScript\Projetos\Desenvolvimento\FoodSystem\food_system_frontend_client\build\windows\flutter\flutter_wrapper_app.vcxproj]
[   +1 ms]     0 Aviso(s)
[        ]     7 Erro(s)
[        ] Tempo Decorrido 00:00:02.01
[  +26 ms] Building Windows application... (completed in 2.803ms)
[+5744 ms] Exception: Build process failed.
[   +4 ms] "flutter run" took 9.218ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1294:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +82 ms] ensureAnalyticsSent: 73ms
[   +1 ms] Running 1 shutdown hook
[   +9 ms] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 3.11.0-0.1.pre, on Microsoft Windows [versÆo 10.0.19045.2965], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.1)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.76.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Based on the logs, it seems to be similar to https://github.com/flutter/flutter/issues/121366, so please follow-up in it for further updates. Closing this as a duplicate.
