### ISSUE TITLE
Extend FlutterFragment  ```Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)```

### ISSUE THREAD

**Issue by quangtuyen1993** [flutter/flutter#127645]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Extends Flutter Fragment.
My fragment is extended from FlutterFragment. 
Then I use dart third-party lib (image-picker) to handle get photos or capture.
But I meet an issue: ```[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null).```
I don't know, What things are wrong with my code, or the flutter fragment doesn't support extend
Note: I tested with FlutterActivity everything is fine. This issue is just in the Flutter Fragment.

### Expected results

Method channel in pubspec.yaml to working

### Actual results

Method channel: From third-party lib in pubspec.yaml not working.

### Code sample

<details><summary>Code sample</summary>

```kt
abstract class SocialFragment : FlutterFragment(), ISocialClubCallback,
    ICommonCallback {
    private val bindings: SocialClubBindings by lazy {
        SocialClubBindings.Builder(requireContext())
            .setToken(arguments?.getString(SocialClubArgs.TOKEN) ?: "")
            .setInitialRoute(arguments?.getString(SocialClubArgs.ROUTE) ?: "")
            .setLocale(getLocale())
            .setCallback(this)
            .setCommonCallback(this)
            .build()
    }

    init {
        super.setArguments(Bundle())
    }

    override fun shouldAttachEngineToActivity(): Boolean {
        return super.shouldAttachEngineToActivity()
    }
    override fun onAttach(context: Context) {
        super.onAttach(context)
        bindings.onAttach()
    }

    override fun provideFlutterEngine(context: Context): FlutterEngine? {
        return bindings.engine
    }

    override fun onDestroy() {
        bindings.onDetach()
        super.onDestroy()

    }

    open fun getLocale(): Locale {
        val defaultLocale = Locale.ENGLISH
        val locale = arguments?.getSafeSerializable(SocialClubArgs.LOCALE, Locale::class.java)
        return locale ?: defaultLocale
    }

    fun notifyBioVerified(isVerified: Boolean) {
        bindings.commonDelegate?.onBioVerified(isVerified)
    }

    @Deprecated("Deprecated in Java")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        bindings.engine.activityControlSurface.onActivityResult(requestCode, resultCode, data)
    }


    private inline fun <reified T : Serializable> Bundle.getSafeSerializable(
        key: String,
        clazz: Class<T>,
    ): T? {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            getSerializable(key, clazz)
        } else {
            @Suppress("DEPRECATION")
            getSerializable(key) as? T
        }
    }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                    #0      ImagePickerApi.pickImages (package:image_picker_android/src/messages.g.dart:257:7)
                                                    <asynchronous suspension>
                                                    #1      ImagePickerAndroid._getImagePath (package:image_picker_android/image_picker_android.dart:110:33)
                                                    <asynchronous suspension>
                                                    #2      ImagePickerAndroid.getImageFromSource (package:image_picker_android/image_picker_android.dart:171:26)
                                                    <asynchronous suspension>
                                                    #3      _BottomState._takePhoto (package:socialclub/src/modules/post_new/presentation/widgets/post_new_media_box.dart:98:35)
                                                    <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E772610a darwin-arm64, locale en-VN)
    • Flutter version 3.10.2 on channel stable at /Users/tuyen/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (2 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/tuyen/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Users/tuyen/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/231.7864.76.2311.10114981/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/tuyen/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/tuyen/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio
    • Android Studio at /Users/tuyen/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/231.7864.76.2311.10195651/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2023.1.1)
    • IntelliJ at /Users/tuyen/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.8770.65/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
    • IntelliJ at /Users/tuyen/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.9011.34/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (5 available)
    • SM G977N (mobile)                    • R3CM402ZKGK   • android-arm64  • Android 12 (API 31)
    • sdk gphone arm64 (mobile)            • emulator-5556 • android-arm64  • Android 11 (API 30) (emulator)
    • Android SDK built for arm64 (mobile) • emulator-5558 • android-arm64  • Android 9 (API 28) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 113.0.5672.126
    ! Device emulator-5554 is offline.

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by darshankawar** [comment]
@quangtuyen1993 
In order to properly address the issue, please provide us complete minimal reproducible code sample without any third party package code implementation, ie, your `mainActivity` file and dart implementation that we can directly use to verify.

Take a look at [this](https://docs.flutter.dev/platform-integration/platform-channels#example) and see if it helps in your case or not.

**Comment by quangtuyen1993** [comment]
Thank you for your replies. I think I know where is the problem. That around in function ``` override fun shouldAttachEngineToActivity(): Boolean```. I misunderstand the default value of the function of FlutterFragment and FlutterFragmentCache.
So I will close this issue. 
Thank you
