### ISSUE TITLE
Error is not thrown when trying to launch url and there is no application which can handle the url

### ISSUE THREAD

**Issue by IlyaMax** [flutter/flutter#127665]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. use code sample provided

### Expected results

we get error in catchError clause but not as "false" value

### Actual results

we get "false" instead of error despite we have log of error in logs(see logs)

### Code sample

<details><summary>Code sample</summary>

```dart
 launchUrlString(
     'viber://pa?chatURI="enter_any_chat_uri',
      mode: LaunchMode.externalApplication,
    ).catchError(
      (obj) {
        // on android we go here and that's a correct behavior
      },
    ).then((opened) {
      // on ios we go here with opened false. we are unable to differ case when url can't be handled because there is no app
      // and case when we forbid to open it in dialog(shown when trying to open another app first time)
    }
```

</details>

### Logs

<details><summary>Logs</summary>

in console we have only this log: Failed to open URL viber://pa?chatURI="enter_any_chat_uri"

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 12.5.1 21G83 darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.76.1)```

</details>

**Comment by dam-ease** [comment]
Hi @IlyaMax. Thanks for filing this issue. I am able to reproduce this issue on the latest `master` and `stable` channels and with the latest `url_launcher` package.

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher_string.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
            body: Center(
          child: TextButton(
              onPressed: () {
                launchUrlString(
                  'viber://pa?chatURI="enter_any_chat_uri"',
                  mode: LaunchMode.externalApplication,
                ).catchError(
                  (obj) {
                    print(obj);
                    // on android we go here and that's a correct behavior
                  },
                ).then((opened) {
                  // on ios we go here with opened false. we are unable to differ case when url can't be handled because there is no app
                  // and case when we forbid to open it in dialog(shown when trying to open another app first time)
                });
              },
              child: Text("Launch URL")),
        )));
  }
}

``` 

</p>
</details> 

<details><summary>Log</summary>
<p>

```
flutter: PlatformException(argument_error, Unable to parse URL, Provided URL: viber://pa?chatURI="enter_any_chat_uri", null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type
#0      _FutureListener.handleError (dart:async/future_impl.dart:181:7)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:817:13)
#3      Future._completeError (dart:async/future_impl.dart:592:5)
<asynchronous suspension>
``` 

</p>
</details> 


<details> <summary> flutter doctor -v </summary>

```bash
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (2 weeks ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                            • android-arm64  • Android 11 (API 30) (emulator)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e • ios            • iOS 16.4 20E247
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
```bash
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3 22E252 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.2 on channel stable at /Users/dammya/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (29 hours ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        •
      android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Comment by stuartmorgan** [comment]
> we get error in catchError clause but not as "false" value

Why is that the behavior you are expecting? The documentation says:

>> Returns true if the URL was launched successful, otherwise either returns
>> false or throws a [PlatformException] depending on the failure.

We can use this to track the `url_launcher` subset of https://github.com/flutter/flutter/issues/124800, but for this plugin the impact will be minimal.

We'll need to evaluate the set of possible error information we can get across platforms and design a return structure. IIRC varies from only a bool on some to arbitrary error codes on others, so we probably want something like a return record (assuming Dart 3+) with a bool and an optional error detail class.

**Comment by IlyaMax** [comment]
@stuartmorgan I guess the answer on your question in comments of code sample I provided 

> on ios we go here with opened false. we are unable to differ case when url can't be handled because there is no app
> and case when we forbid to open it in dialog(shown when trying to open another app first time)

I understand that everything works according to the docs, but we get not very clear behavior in this case. That looks like a minor but anyway a reason to change the behavior which mentioned in the docs.

**Comment by stuartmorgan** [comment]
The iOS API for launching a URL just returns a bool. Changing the way the plugin reports that failure cannot create any additional information about why it didn't work.

**Comment by markbeij** [comment]
> As a workaround, I have created a wrapper method in my project for `launchUrl` that returns a `(bool, PlatfromException?)` record.

Would you mind share the wrapper @jeetparte ?

**Comment by jeetparte** [comment]
@markbeij I haven't looked into Flutter for more than a year now. But this is what my wrapper looked like back then —

```dart
  /// Invokes url_launcher's [launchUrl] method but 
  /// returns with a more consistent return type.
  Future<({bool success, PlatformException? exception})> launch({
    LaunchMode mode = LaunchMode.platformDefault,
    WebViewConfiguration webViewConfiguration = const WebViewConfiguration(),
    String? webOnlyWindowName,
  }) async {
    try {
      final success = await launchUrl(this,
          mode: mode,
          webViewConfiguration: webViewConfiguration,
          webOnlyWindowName: webOnlyWindowName);
      return (success: success, exception: null);
    } on PlatformException catch (e) {
      return (success: false, exception: e);
    }
  }
```

This means you always get the bool indicating success (and still have access to any exception that occurs).
