### ISSUE TITLE
Integration tests fail with sendFramesToEngine error

### ISSUE THREAD

**Issue by arashbi** [flutter/flutter#127679]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We have a rather big application, and trying to add integration tests to it. 
The simple test we have runs, but reports failure with 

```
The following assertion was thrown while executing callbacks for FrameTiming:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 881 pos 16: 'sendFramesToEngine':
is not true.
```
It happens even though tests seems to be running to the end successfully

Application uses many plugins, notably Everything from firebase.
We also use native splash screen.
 
This seems to be the bug reported  [here](https://github.com/flutter/flutter/issues/77225)

### Expected results

I expect the test to report success.

### Actual results

══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following assertion was thrown while executing callbacks for FrameTiming:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 881 pos 16: 'sendFramesToEngine':
is not true.

### Code sample

<details><summary>Test Case</summary>

```dart

void main() async {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;

  group('end-to-end test', () {
    testWidgets('Test',
            (tester) async {
          await application.main();
          await tester.pumpAndSettle(Duration(seconds: 20));

          // Verify the counter starts at 0.
          final Finder finder = find.text('Skip');
          expect(finder, findsOneWidget);
          await tester.tap(finder);
          await tester.pumpAndSettle();

        });
  });
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following assertion was thrown while executing callbacks for FrameTiming:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 881 pos 16: 'sendFramesToEngine':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      WidgetsBinding.drawFrame.<anonymous closure> (package:flutter/src/widgets/binding.dart:881:16)
#3      SchedulerBinding._executeTimingsCallbacks (package:flutter/src/scheduler/binding.dart:329:19)
#7      _invoke1 (dart:ui/hooks.dart:160:10)
#8      PlatformDispatcher._reportTimings (dart:ui/platform_dispatcher.dart:555:5)
#9      _reportTimings (dart:ui/hooks.dart:107:31)
(elided 5 frames from class _AssertionError and dart:async)

The TimingsCallback that gets executed was:
  Closure: (List<FrameTiming>) => void
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Test
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.4 22F66 darwin-arm64, locale en-CA)
    • Flutter version 3.10.0 on channel stable at /opt/homebrew/Caskroom/flutter/3.10.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/abizhanzadeh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /Users/abizhanzadeh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8770.15

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • Pixel 3a XL (mobile) • 94EAX0DTAC • android-arm64  • Android 12 (API 32)
    • macOS (desktop)      • macos      • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)         • chrome     • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this issue. Closing this as duplicate as it seems to be a similar issue to #89651. Kindly follow up with this issue for updates.
