### ISSUE TITLE
```java.lang.NullPointerException``` while using image_picker for flutter module

### ISSUE THREAD

**Issue by quangtuyen1993** [flutter/flutter#127637]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

My project structure is:
├── Android native
 |   ├── flutter_module
 │    |   ├── flutter_plugin
 |    |    |   ├── **/*.dart
 
Case 1: I run the example application in the Flutter plugin 
Case 2: I run on the Android native host app -> I pick a photo or video

### Expected results

Working on Android native host

### Actual results

case 1-> working fine
case 2-> app crash

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<void> _onGalleryPicker() async {
    final List<XFile> pickedFileList = await _picker.pickMultiImage(
      imageQuality: 90,
      maxWidth: 1980,
      maxHeight: 1020,
    );
    if (mounted) {
      context.read<PostNewCubit>().pickPhoto(pickedFileList);
    }
  }

  Future<void> _onPickVideo() async {
    final XFile? pickedFileList = (await _picker.pickVideo(
      source: ImageSource.gallery,
    ));
    if (mounted) {
      context.read<PostNewCubit>().pickVideo(pickedFileList,
          context.s.post_new_file_is_too_large_for_destination_file_system);
    }
  }

  Future<void> _takePhoto() async {
    final XFile? pickedFileList = await _picker.pickImage(
      imageQuality: 90,
      source: ImageSource.camera,
      maxWidth: 1980,
      maxHeight: 1020,
    );
    if (mounted) {
      context.read<PostNewCubit>().takePhoto(pickedFileList);
    }
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
FATAL EXCEPTION: pool-7-thread-1
                                                    java.lang.NullPointerException: uri
                                                    	at java.util.Objects.requireNonNull(Objects.java:245)
                                                    	at android.content.ContentResolver.openInputStream(ContentResolver.java:1508)
                                                    	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:55)
                                                    	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseMultiImageResult(ImagePickerDelegate.java:604)
                                                    	at io.flutter.plugins.imagepicker.ImagePickerDelegate.lambda$onActivityResult$1$io-flutter-plugins-imagepicker-ImagePickerDelegate(ImagePickerDelegate.java:565)
                                                    	at io.flutter.plugins.imagepicker.ImagePickerDelegate$$ExternalSyntheticLambda1.run(Unknown Source:6)
                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                    	at java.lang.Thread.run(Thread.java:920)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on macOS
    13.3.1 22E772610a darwin-arm64, locale en-VN)
    • Flutter version 3.10.2 on channel stable at
      /Users/tuyen/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (2 days ago),
      2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices
    (Android SDK version 33.0.2)
    • Android SDK at
      /Users/tuyen/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-17.jdk/
      Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment
      (build 17.0.7+8-LTS-224)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at
      /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at
      /Users/tuyen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/
      ch-1/231.7864.76.2311.10114981/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flu
      tter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-dar
      t
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.2)
    • Android Studio at
      /Users/tuyen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/
      ch-0/222.4459.24.2221.9971841/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flu
      tter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-dar
      t
    • Java version OpenJDK Runtime Environment
      (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at
      /Users/tuyen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/
      ch-0/222.4459.24.2221.10121639/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flu
      tter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-dar
      t
    • Java version OpenJDK Runtime Environment
      (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio
    • Android Studio at
      /Users/tuyen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/
      ch-1/231.7864.76.2311.10195651/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flu
      tter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-dar
      t
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version
    2023.1.1)
    • IntelliJ at /Users/tuyen/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/23
      1.8770.65/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flu
      tter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-dar
      t

[✓] IntelliJ IDEA Community Edition (version
    2023.1.2)
    • IntelliJ at /Users/tuyen/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/23
      1.9011.34/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flu
      tter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-dar
      t

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (5 available)
    • SM G977N (mobile)                    •
      R3CM402ZKGK   • android-arm64  • Android 12
      (API 31)
    • sdk gphone arm64 (mobile)            •
      emulator-5556 • android-arm64  • Android 11
      (API 30) (emulator)
    • Android SDK built for arm64 (mobile) •
      emulator-5558 • android-arm64  • Android 9
      (API 28) (emulator)
    • macOS (desktop)                      • macos
      • darwin-arm64   • macOS 13.3.1 22E772610a
      darwin-arm64
    • Chrome (web)                         • chrome
      • web-javascript • Google Chrome
      113.0.5672.126
    ! Device emulator-5554 is offline.

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by quangtuyen1993** [comment]
My bad

**Comment by alihassan04ali** [comment]
anyone find the solution?
