### ISSUE TITLE
Engine jobs queueing for 200+ minutes even though many bots are idle

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127709]
See https://ci.chromium.org/p/flutter/builders/prod/Linux%20Benchmarks

**Comment by zanderso** [comment]
<img width="867" alt="Screenshot 2023-05-26 at 2 11 12 PM" src="https://github.com/flutter/flutter/assets/6343103/3b43f003-82b4-4ae0-b069-ba0600418b96">

**Comment by zanderso** [comment]
cc @yusuf-goog infra on call

**Comment by yusuf-goog** [comment]
Builds are running right now. Will dig into this why there might have been a delay in processing jobs.

**Comment by zanderso** [comment]
I'm not sure where you're looking, but as I'm typing this neither [Linux Android Emulator Tests](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Android%20Emulator%20Tests) nor [Linux Benchmarks](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Benchmarks) have any jobs running.

**Comment by zanderso** [comment]
Escalating to P0 since this is going to block Engine -> Framework rolls.

**Comment by zanderso** [comment]
cc @bdero the engine sheriff

**Comment by zanderso** [comment]
The Engine ci.yaml roller has been failing for roughly the same period of time https://ci.chromium.org/p/flutter/builders/staging/Linux%20ci_yaml%20engine%20roller.

**Comment by keyonghan** [comment]
Seems the ci.yaml format is incorrect, causing scheduling failures:
```
FormatException: Unexpected character (at line 4, character 1)
}
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:907:13)
#2      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      Target._parseProperty (package:cocoon_service/src/model/ci_yaml/target.dart:204:14)
#7      Target._getTargetProperties (package:cocoon_service/src/model/ci_yaml/target.dart:158:25)
#8      Target.getProperties (package:cocoon_service/src/model/ci_yaml/target.dart:115:44)
#9      LuciBuildService._createPostsubmitScheduleBuild (package:cocoon_service/src/service/luci_build_service.dart:581:60)
#10     LuciBuildService.schedulePostsubmitBuilds (package:cocoon_service/src/service/luci_build_service.dart:466:63)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#12     Scheduler._batchScheduleBuilds (package:cocoon_service/src/service/scheduler.dart:182:5)
<asynchronous suspension>
#13     Scheduler._addCommit (package:cocoon_service/src/service/scheduler.dart:164:5)
<asynchronous suspension>
#14     Scheduler.addPullRequest (package:cocoon_service/src/service/scheduler.dart:121:5)
<asynchronous suspension>
#15     GithubWebhookSubscription.post (package:cocoon_service/src/request_handlers/github/webhook_subscription.dart:104:9)
<asynchronous suspension>
#16     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:24)
<asynchronous suspension>
#17     SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:5)
<asynchronous suspension>
#18     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:297:11)
<asynchronous suspension>
```
