### ISSUE TITLE
RenderBox was not laid out

### ISSUE THREAD

**Issue by SonVietAu** [flutter/flutter#127847]
Was trying to build a widget with a ListView inside a FutureBuilder inside an encompassing FutureBuilder. Once the encompassing FutureBuilder's future finished, another future was set for the inner FutureBuilder and the resulting data is to be displayed on a ListView. There were about 20 items to display in the ListView. There is also an idea to display hundreds of such item. 

Got the following exception and was asked to report. 

The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderPointerListener#310e5 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2009 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  ListView ListView:file:///..../lib/MainWidget.dart:78:41
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2009:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:121:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#6      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#7      RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:836:43)
#8      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:938:32)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#10     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#11     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:240:12)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#13     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#14     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#15     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1080:7)
#16     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#17     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410:14)
#18     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2027:7)
#19     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1020:18)
#20     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:516:19)
#21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#25     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#26     _invoke (dart:ui/hooks.dart:145:13)
#27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#28     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: _RenderScrollSemantics#a0842 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=390.0, 0.0<=h<=Infinity)
...  semantic boundary
...  size: MISSING
RenderObject: _RenderScrollSemantics#a0842 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=390.0, 0.0<=h<=Infinity)
  semantic boundary
  size: MISSING
...  child: RenderPointerListener#310e5 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=390.0, 0.0<=h<=Infinity)
...    size: MISSING
...    behavior: deferToChild
...    listeners: signal
...    child: RenderSemanticsGestureHandler#62aca relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=390.0, 0.0<=h<=Infinity)
...      size: MISSING
...      behavior: opaque
...      gestures: <none>
...      child: RenderPointerListener#68b67 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=390.0, 0.0<=h<=Infinity)
...        size: MISSING
...        behavior: opaque
...        listeners: down, panZoomStart
...        child: RenderSemanticsAnnotations#32130 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=390.0, 0.0<=h<=Infinity)
...          size: MISSING
====================================================================================================

**Comment by SonVietAu** [comment]
This is now a non-issue. My code was updated to have the ListView inside a single Future and all
