### ISSUE TITLE
Scribbe issue - RenderBox was not laid out: RenderFractionalTranslation#23d29 NEEDS-LAYOUT NEEDS-PAINT

### ISSUE THREAD

**Issue by marcoancona** [flutter/flutter#127803]
The following error occurs when focusing a `TextIField` using the Apple Pencil on iPad. The error is not raised when tapping with a finger on the field to use the virtual keyboard. Scribbe does not work when this error is raised.

```
════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during method call TextInputClient.requestElementsInRect:
RenderBox was not laid out: RenderFractionalTranslation#23d29 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
box.dart:1
Failed assertion: line 1966 pos 12: 'hasSize'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      RenderBox.size
box.dart:1966
#3      RenderFractionalTranslation.applyPaintTransform
proxy_box.dart:2988
#4      RenderObject.getTransformTo
object.dart:3174
#5      _ScribbleFocusableState.bounds
editable_text.dart:5006
#6      _ScribbleFocusableState.isInScribbleRect
editable_text.dart:4984
#7      TextInput._handleTextInputInvocation.<anonymous closure>
text_input.dart:1771
#8      WhereIterator.moveNext (dart:_internal/iterable.dart:441:13)
#9      MappedIterator.moveNext (dart:_internal/iterable.dart:392:19)
#10     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#11     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#12     new List.of (dart:core-patch/array_patch.dart:47:28)
#13     Iterable.toList (dart:core/iterable.dart:494:7)
#14     TextInput._handleTextInputInvocation
text_input.dart:1779
#15     TextInput._loudlyHandleTextInputInvocation
text_input.dart:1746
#16     MethodChannel._handleAsMethodCall
platform_channel.dart:547
#17     MethodChannel.setMethodCallHandler.<anonymous closure>
platform_channel.dart:540
#18     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
binding.dart:479
#19     _invoke2 (dart:ui/hooks.dart:174:13)
#20     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#21     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#22     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#23     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:686:22)
#24     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 2 frames from class _AssertionError)
call: MethodCall(TextInputClient.requestElementsInRect, [271.5, 371.5, 60, 120])
════════════════════════════════════════════════════════════════════════════════
```

[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0 22A380 darwin-arm64, locale en-CH)
    • Flutter version 3.10.2 on channel stable at /Users/marcoancona/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (6 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/marcoancona/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: ...
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

**Comment by danagbemava-nc** [comment]
Hi @marcoancona, please provide a complete minimal reproducible code sample along with steps to reproduce so that we can investigate this issue. I tested with the counter app with a TextField but I could not reproduce the error. 

Thank you

**Comment by danagbemava-nc** [comment]
Issue is reproducible using the code sample provided in https://github.com/flutter/flutter/issues/127803#issuecomment-1569127172. 

Removing/Commenting home in the sample code makes Scribble work again. Looking at the widget tree in devtools, there are 2 `NewWidget` nodes so perhaps that's why the scribble cannot determine where to start and as such throws the error. 

<img width="491" alt="Screenshot 2023-05-31 at 07 02 21" src="https://github.com/flutter/flutter/assets/88313112/999cd45b-9121-4551-b7e5-f218216a5723">

The error logs are the same as what OP shared above. I agree that improving the error message would be helpful. 

Labeling for further insight from the team. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale en-GB)
    • Flutter version 3.10.2 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (7 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 16.5 20F66
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 16.5 20F66
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 113.0.5672.126
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.11.0-16.0.pre.22, on macOS 13.4 22F66 darwin-arm64, locale en-GB)
    • Flutter version 3.11.0-16.0.pre.22 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c8279488b1 (89 minutes ago), 2023-05-31 01:39:00 -0400
    • Engine revision b7fced3708
    • Dart version 3.1.0 (build 3.1.0-155.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 16.5 20F66
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 16.5 20F66
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 113.0.5672.126
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by LongCatIsLooong** [comment]
It looks like `isInScribbleRect` is called on a text field that's in a inactive route. We should be scribble for the text fields that can't be interacted with.

**Comment by justinmc** [comment]
Moving this to team-text-input since @LongCatIsLooong is taking a look.
