### ISSUE TITLE
Asserts in ServicesBinding on receiving a lifecycle message on macOS

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#127974]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The following asserts are now seen in the latest master on macOS:

```
═╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following _TypeError was thrown during a platform message callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:264:71)
binding.dart:264
#1      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
platform_channel.dart:212
#2      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:490:35)
binding.dart:490
#3      _invoke2 (dart:ui/hooks.dart:202:13)
hooks.dart:202
#4      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
channel_buffers.dart:40
#5      _Channel.push (dart:ui/channel_buffers.dart:130:31)
channel_buffers.dart:130
#6      ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
channel_buffers.dart:326
#7      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:718:22)
platform_dispatcher.dart:718
#8      _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
hooks.dart:114
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Null check operator used on a null value
```

### Expected results

...

### Actual results

...

### Code sample

n/a

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter --version
Flutter 3.11.0-16.0.pre.24 • channel master • https://github.com/flutter/flutter.git
Framework • revision 224667e90f (9 hours ago) • 2023-05-31 04:24:27 -0400
Engine • revision 5294709d68
Tools • Dart 3.1.0 (build 3.1.0-155.0.dev) • DevTools 2.23.1
```

</details>

**Comment by tgucio** [comment]
/cc @gspencergoog 

I'm guessing this is after https://github.com/flutter/engine/pull/42418. If landing https://github.com/flutter/flutter/pull/123274 is going to take a while more perhaps this should get a quick @ dirty fix.

**Comment by tgucio** [comment]
The incoming state change is AppLifecycleState.hidden BTW.
