### ISSUE TITLE
NPE in Android Studio 3.0 Flutter Plugin MacOS 10.12.6

### ISSUE THREAD

**Issue by pgluck** [flutter/flutter#12798]
## Steps to Reproduce

1. Clone Flutter repository and run flutter doctor until errors are resolved.
2. Download and install Android Studio 3.0 (stable release Build #AI-171.4408382 built 20 October 2017)
3. Install Flutter plugin 
4. Restart Android Studio
5. Configure Flutter SDK path
6. Restart Android Studio
7. Observe NPE when loading Flutter plugin 

## Logs

null
java.lang.NullPointerException
	at io.flutter.FlutterInitializer.getAnalytics(Unknown Source)
	at io.flutter.FlutterInitializer.runActivity(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivitiesFromExtensions$1(StartupManagerImpl.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:346)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$2(StartupManagerImpl.java:161)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:305)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

## Flutter Doctor

MacBook-Air-3.local:pgluck /Users/pgluck/tools/flutter <39> flutter doctor
[â] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    â¢ Flutter at /Users/pgluck/tools/flutter
    â¢ Framework revision e8aa40eddd (13 days ago), 2017-10-17 15:42:40 -0700
    â¢ Engine revision 7c4142808c
    â¢ Tools Dart version 1.25.0-dev.11.0

[â] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    â¢ Android SDK at /Users/pgluck/Library/Android/sdk
    â¢ Platform android-25, build-tools 25.0.2
    â¢ Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    â¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[â] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    â¢ Xcode at /Applications/Xcode.app/Contents/Developer
    â¢ Xcode 9.0.1, Build version 9A1004
    â¢ ios-deploy 1.9.2
    â¢ CocoaPods version 1.3.1

[â] Android Studio (version 3.0)
    â¢ Android Studio at /Applications/Android Studio.app/Contents
    â¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[â] Connected devices
    â¢ Peter's iPhone 6s â¢ 946cf89ea60fe0400316456d1432206f3de53641 â¢ ios â¢ iOS 11.1

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by adshead** [comment]
The same bug occurs on Windows too, and it seems to happen each time you start Android Studio. Interestingly you do seem to be able to continue using the plugin and successfully build/deploy flutter apps to a device.

**Comment by mit-mit** [comment]
Thanks for reporting @pgluck, I can repro this. We'll get this fixed ASAP!
