### ISSUE TITLE
[integration_test][Chrome] Github action running for web giving WebDriverException

### ISSUE THREAD

**Issue by dewbambs** [flutter/flutter#127940]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Fork this given project https://github.com/dewbambs/flutter_github_actions
2. Check the file in `.github/e2e_test.yml`
3. Initiate the `e2e_test.yml` by pushing some random change in this branch.
4. In local setup this test will pass when you run the command `flutter drive --driver=test_driver/integration_test.dart --target=e2e/home_scenario.dart -d web-server --profile --browser-name=chrome`
5. But the similar code will not execute in Github Actions CI.

### Expected results

```
[  +11 ms] dart2js: Starting due to {}
[  +34 ms] compiling dart code to kernel with command "/Users/riteshsingh/Documents/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/riteshsingh/Documents/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/Users/riteshsingh/Documents/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.profile=true
-DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/90fa3ae28fe6ddaee1af2c120f01e50201c1401b/ -o
/Users/riteshsingh/Documents/Projects/PersonalProjects/flutter_github_actions/.dart_tool/flutter_build/ddb4dd0fa0bc95312f5b59db7f56b227/app.dill
--packages=.dart_tool/package_config.json --cfe-only
/Users/riteshsingh/Documents/Projects/PersonalProjects/flutter_github_actions/.dart_tool/flutter_build/ddb4dd0fa0bc95312f5b59db7f56b227/main.dart"
[+4778 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,17",
                        "identifier" : "FD8E70A7-398D-4779-AC72-4CB4C767C8BD",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-air5-1",
                        "modelName" : "iPad Air (5th generation)",
                        "name" : "iPad Air (5th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,8",
                        "identifier" : "B80F7331-63AC-4EA4-81C4-A30E7151309F",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-plus-1",
                        "modelName" : "iPhone 14 Plus",
                        "name" : "iPhone 14 Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,6",
                        "identifier" : "4DD9E9B9-631C-4391-99D2-DFFB7D275934",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-se3-1",
                        "modelName" : "iPhone SE (3rd generation)",
                        "name" : "iPhone SE (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,5",
                        "identifier" : "E793FC66-AD5C-4DD5-9AD3-C3439AE933A9",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-12point9-6th-1",
                        "modelName" : "iPad Pro (12.9-inch) (6th generation)",
                        "name" : "iPad Pro (12.9-inch) (6th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,7",
                        "identifier" : "49BF6771-3036-45F1-AB82-549A2C94598D",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-1",
                        "modelName" : "iPhone 14",
                        "name" : "iPhone 14"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,3",
                        "identifier" : "DAD025FE-FA6D-468A-AD45-F0548DBAB7C6",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-11-4th-1",
                        "modelName" : "iPad Pro (11-inch) (4th generation)",
                        "name" : "iPad Pro (11-inch) (4th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,2",
                        "identifier" : "EC4FEF39-7E90-4898-A447-CDE4AF34D420",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-pro-1",
                        "modelName" : "iPhone 14 Pro",
                        "name" : "iPhone 14 Pro"
                      },
                      {
                        "simulator" : false,
                        "operatingSystemVersion" : "12.6.5 (21G531)",
                        "interface" : "usb",
                        "available" : true,
                        "platform" : "com.apple.platform.macosx",
                        "modelCode" : "MacBookAir7,2",
                        "identifier" : "890A1A0B-D569-546B-874E-174C88C4CD57",
                        "architecture" : "x86_64h",
                        "modelUTI" : "com.apple.macbookair-13-unibody",
                        "modelName" : "MacBook Air",
                        "name" : "My Mac"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,1",
                        "identifier" : "E4219670-CF3C-48BA-B7E0-3BE2D54465D5",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-mini6-1",
                        "modelName" : "iPad mini (6th generation)",
                        "name" : "iPad mini (6th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,3",
                        "identifier" : "F354C37C-4959-4B29-BB3E-57BD3D41C8C6",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-14-pro-max-1",
                        "modelName" : "iPhone 14 Pro Max",
                        "name" : "iPhone 14 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.1 (20B72)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,18",
                        "identifier" : "E5587292-45C6-4FB0-8C15-B030DD0DEAE1",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-10-1",
                        "modelName" : "iPad (10th generation)",
                        "name" : "iPad (10th generation)"
                      }
                    ]
[+54763 ms] dart2js: Complete
[+1090 ms] web_release_bundle: Starting due to {}
[ +220 ms] shaderc command: [/Users/riteshsingh/Documents/flutter/bin/cache/artifacts/engine/darwin-x64/impellerc, --sksl, --iplr, --json,
--sl=build/web/assets/shaders/ink_sparkle.frag, --spirv=build/web/assets/shaders/ink_sparkle.frag.spirv,
--input=/Users/riteshsingh/Documents/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag,
--include=/Users/riteshsingh/Documents/flutter/packages/flutter/lib/src/material/shaders,
--include=/Users/riteshsingh/Documents/flutter/bin/cache/artifacts/engine/darwin-x64/shader_lib]
[ +447 ms] web_release_bundle: Complete
[ +608 ms] web_service_worker: Starting due to {}
[ +469 ms] web_service_worker: Complete
[ +227 ms] Persisting file store
[  +16 ms] Done persisting file store
[  +44 ms] Compiling e2e/home_scenario.dart for the Web... (completed in 63.1s)
[   +4 ms] e2e/home_scenario.dart is being served at http://localhost:58403
[   +2 ms] The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved
development
           workflow.
[  +23 ms] Registering signal handlers...
[+1431 ms] executing: /Users/riteshsingh/Documents/flutter/bin/cache/dart-sdk/bin/dart test_driver/integration_test.dart -rexpanded
[+6828 ms] All tests passed.
[ +102 ms] Unregistering signal handlers...
[   +4 ms] Application finished.
[   +9 ms] "flutter drive" took 77,817ms.
[ +272 ms] ensureAnalyticsSent: 252ms
[        ] Running 1 shutdown hook
[   +3 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

### Actual results

Output from running integration test in CI environment:

```
FINE: Sending analytics timing "pub-get" took 1589 miliseconds
IO  : Writing 10002 characters to text file .dart_tool/package_config.json.
FINE: Contents:
    | {
    |   "configVersion": 2,
    |   "packages": [
    |     {
    |       "name": "async",
    |       "rootUri": "file:///Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/.pub-cache/hosted/pub.dev/async-2.11.0",
    |       "packageUri": "lib/",
    |       "languageVersion": "2.18"
    |     },
    |     {
    |       "name": "bloc",
    |       "rootUri": "file:///Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/.pub-cache/hosted/pub.dev/bloc-8.1.2",
    |       "packageUri": "lib/",
    |       "languageVersion": "2.12"
    |     },
    |     {
    |       "name": "boolean_selector",
    |       "rootUri": "file:///Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/.pub-cache/hosted/pub.dev/boolean_selector-2.1.1",
    |       "packageUri": "lib/",
    |       "languageVersion": "2.17"
    |     },
    |     {
    |       "name": "characters",
    |       "rootUri": "file:///Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/.pub-cache/hosted/pub.dev/characters-1.3.0",
    |       "packageUri": "lib/",
    |       "languageVersion": "2.12"
    |     },
    |     {
    |       "name": "clock",
    |       "rootUri": "file:///Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/.pub-cache/hosted/pub.dev/clock-1.1.1",
    |       "packageUri": "lib/",
    |       "languageVersion": "2.12"
    |     },
    |     {
    |       "name": "collection",
    |       "rootUri": "file:///Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/.pub-cache/hosted/pub.dev/collection-1.17.1",
    |       "packageUri": "lib/",
    |       "languageVersion": "2.18"
    |     },
    |     {
    |       "name": "cupertino_icons",
    |       "rootUri": "file:///Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/.pub-cache/hosted/pub.dev/cupertino_icons-1.0.5",
    |       "packageUri": "lib/",
    |       "languageVersion": "2.12"
    |     },
[  +19 ms] Found plugin firebase_core at /Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/.pub-cache/hosted/pub.dev/firebase_core-2.13.1/
[   +2 ms] Found plugin firebase_core_web at /Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/.pub-cache/hosted/pub.dev/firebase_core_web-2.5.0/
[  +23 ms] Found plugin integration_test at /Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/packages/integration_test/
[   +3 ms] web_entrypoint: Complete
[   +2 ms] dart2js: Starting due to {}
[  +11 ms] compiling dart code to kernel with command "/Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.profile=true -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/90fa3ae28fe6ddaee1af2c120f01e50201c1401b/ -o /Users/runner/work/flutter_github_actions/flutter_github_actions/.dart_tool/flutter_build/ddb4dd0fa0bc95312f5b59db7f56b227/app.dill --packages=.dart_tool/package_config.json --cfe-only /Users/runner/work/flutter_github_actions/flutter_github_actions/.dart_tool/flutter_build/ddb4dd0fa0bc95312f5b59db7f56b227/main.dart"
[+63513 ms] dart2js: Complete
[ +472 ms] web_release_bundle: Starting due to {}
[ +179 ms] shaderc command: [/Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/bin/cache/artifacts/engine/darwin-x64/impellerc, --sksl, --iplr, --json, --sl=build/web/assets/shaders/ink_sparkle.frag, --spirv=build/web/assets/shaders/ink_sparkle.frag.spirv, --input=/Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag, --include=/Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/packages/flutter/lib/src/material/shaders, --include=/Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64/bin/cache/artifacts/engine/darwin-x64/shader_lib]
[ +648 ms] web_release_bundle: Complete
[ +591 ms] web_service_worker: Starting due to {}
[ +376 ms] web_service_worker: Complete
[ +214 ms] Persisting file store
[  +10 ms] Done persisting file store
[  +35 ms] Compiling e2e/home_scenario.dart for the Web... (completed in 66.2s)
[   +1 ms] e2e/home_scenario.dart is being served at http://localhost:49267
[        ] The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[  +18 ms] Registering signal handlers...

[ +108 ms] "flutter drive" took 101,589ms.
WebDriverException (400): Error parsing response body: unhandled request
#0      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:97:7)
#1      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#2      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
[  +45 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
#3      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
[   +1 ms] Shutdown hooks complete
<asynchronous suspension>
[        ] exiting with code 1
#4      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:332:30)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

I have tested the version of chrome and version of chromedriver and both match as my local environment. 

Chromium version:
```
Run echo Installed chromium version: 114.0.5735.90
Installed chromium version: 114.0.5735.90
Google Chrome 114.0.5735.90 
```

Chrome driver version:
```
Run chromedriver -v
ChromeDriver 114.0.5735.16
```

I also confirmed that I have started the chrome driver on port 4444:

```
Run lsof -i :4444

COMMAND    PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
chromedri 5222 runner    5u  IPv4 0xba32ca32ebf464cb      0t0  TCP localhost:krb524 (LISTEN)
chromedri 5222 runner    6u  IPv6 0xba32ca32ed238913      0t0  TCP localhost:krb524 (LISTEN)
```

### Code sample

Code can be found here https://github.com/dewbambs/flutter_github_actions

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.10.2, on macOS 12.6.5 21G531 darwin-x64, locale en)
    • Flutter version 3.10.2 on channel stable at /Users/runner/hostedtoolcache/flutter/stable-3.10.2-x64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (7 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/runner/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/runner/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/runner/Library/Android/sdk
    • Java binary at: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.372-7/x64/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Temurin)(build 1.8.0_372-b07)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode_14.2.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.5 21G[53](https://github.com/dewbambs/flutter_github_actions/actions/runs/5131158427/jobs/9230874583#step:12:54)1 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.[56](https://github.com/dewbambs/flutter_github_actions/actions/runs/5131158427/jobs/9230874583#step:12:57)[72](https://github.com/dewbambs/flutter_github_actions/actions/runs/5131158427/jobs/9230874583#step:12:73).63

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
The Flutter CLI developer tool uses Google Analytics to report usage and diagnostic data
along with package dependencies, and crash reporting to send basic crash reports.
This data is used to help improve the Dart platform, Flutter framework, and related tools.

Telemetry is not sent on the very first run.
To disable reporting of telemetry, run this terminal command:

flutter --disable-telemetry.
If you opt out of telemetry, an opt-out event will be sent,
and then no further information will be sent.
This data is collected in accordance with the
Google Privacy Policy (https://policies.google.com/privacy).

**Comment by huycozy** [comment]
@dewbambs I wonder how you start `chromedriver` on GitHub Action environment. Can you please share?

**Comment by dewbambs** [comment]
@huycozy by mistake while testing I changed the code for `e2e_test.yml`. I have changed it back to the failing code. Please check the `e2e_test.yml` now.

**Comment by huycozy** [comment]
Thanks for the update. I also try this on master channel and see the same result (GH Action [result](https://github.com/huycozy/GH-integration-test-127940/actions/runs/5152209258/jobs/9278096065) on master channel). Labeling the issue for further investigation.

<details>
<summary>flutter doctor -v (master on GH Action)</summary>

```bash
[✓] Flutter (Channel master, 3.11.0-18.0.pre.57, on macOS 12.6.5 21G531 darwin-x64, locale en)
    • Flutter version 3.11.0-18.0.pre.57 on channel master at /Users/runner/hostedtoolcache/flutter/master-master-x64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 60a87d0798 (67 minutes ago), 2023-06-01 21:27:17 -0700
    • Engine revision 3a453f2ccb
    • Dart version 3.1.0 (build 3.1.0-160.0.dev)
    • DevTools version 2.24.0
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/runner/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/runner/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/runner/Library/Android/sdk
    • Java binary at: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.372-7/x64/Contents/Home/bin/java
    ✗ Could not determine java version
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode_14.2.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.5 21G531 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.63
[✓] Network resources
    • All expected network resources are available.
! Doctor found issues in 2 categories.
```
</details>

**Comment by christopherfujino** [comment]
```
Run lsof -i :4444

COMMAND    PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
chromedri 5222 runner    5u  IPv4 0xba32ca32ebf464cb      0t0  TCP localhost:krb524 (LISTEN)
chromedri 5222 runner    6u  IPv6 0xba32ca32ed238913      0t0  TCP localhost:krb524 (LISTEN)
```

To clarify, was this run on your action? I wonder if there is some permission the action requires?

**Comment by dewbambs** [comment]
@christopherfujino I ran this on my action to verify that the chromedrivers were indeed starting on port 4444. I don't think we need additional permission for this.

**Comment by christopherfujino** [comment]
> @christopherfujino I ran this on my action to verify that the chromedrivers were indeed starting on port 4444. I don't think we need additional permission for this.

🤔

**Comment by yjbanov** [comment]
Is there output from `chromedriver`? Preferably `chromedriver --verbose`.

**Comment by dewbambs** [comment]
@yjbanov I was not able to get much data using `chromedriver --verbose`. This is the logs for command `chromedriver --port=4444 --verbose` it's same as `chromedriver --port=4444`.

```
Starting ChromeDriver 114.0.5735.16 (7e1ff058633f5b79b1cd7479aca585ba385519d8-refs/branch-heads/5735@{#182}) on port 4444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

**Comment by ditman** [comment]
@dewbambs any reason why you're running tests in `runs-on: macos-latest`?

The Firebase team seems to be able to run their web e2e in github actions with a somewhat similar setup to yours, could you see if this serves as inspiration?

https://github.com/firebase/flutterfire/blob/master/.github/workflows/e2e_tests.yaml#L247
