### ISSUE TITLE
Unable to change form ca-camera to picture-camera in flutter web, ok in native not in web.

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#128032]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When using the described example, I am unable to change from face-camera to picture-camera in web. I native it works perfectly well.

```
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

import '../../../../common/globals.dart';
import '../../../message/message.dart';

class MWorkCamera extends StatefulWidget{
  const MWorkCamera({super.key});

  @override
  State<MWorkCamera> createState() => _MWorkCameraState();
}

class _MWorkCameraState extends State<MWorkCamera> {

  CameraController? _cameraController;
  late Future<void> _initializeControllerFuture;

  @override
  void initState() {
    super.initState();
    if(currentCamera!=null) {
      _cameraController = CameraController(
        currentCamera!,
        ResolutionPreset.ultraHigh,
        //TODO: Resolution should be selectable
      );
    }

    if(_cameraController!=null) {
      _initializeControllerFuture = _cameraController!.initialize();
    }

  }

  @override
  Widget build(BuildContext context) {

    return FutureBuilder(
        future: _initializeControllerFuture,
        builder: (context, snapshot){
          if(snapshot.connectionState==ConnectionState.done){
            if(_cameraController!=null) {
              return Stack(
                children: [
                  SizedBox(
                      height: double.infinity,
                      width: double.infinity,
                      child: CameraPreview(_cameraController!)
                  ),
                  Positioned.fill(
                      child: Align(
                        alignment: Alignment.bottomCenter,
                        child: Padding(
                          padding: const EdgeInsets.only(bottom:4.0),
                          child: ElevatedButton(
                              onPressed: () async {
                                try {
                                  var pictureFile = await _cameraController
                                      ?.takePicture();
                                  Message.info("${pictureFile?.path.toString()}",durationSeconds: 60);
                                }catch(exception){
                                  Message.error(exception.toString());
                                }
                              },
                              child: const Icon(Icons.photo_camera),),
                        )
                      )
                  ),
                  Positioned.fill(
                      child: Align(
                        alignment: Alignment.bottomRight,
                        child: Padding(
                          padding: const EdgeInsets.all(4.0),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.end,
                            children: [
                              OutlinedButton(
                                  onPressed: () async {


                                  },
                                  child: Icon(Icons.info_outline)
                              ),
                              OutlinedButton(
                                  onPressed: (cameras?.length??0)>=2?(){
                                    toggleCameraLens();
                                  }:null,
                                  child: Icon(Icons.cameraswitch_outlined)
                              )

                            ],
                          ),
                        ),
                      )
                  )

                ],
              );
            } else {
              return const Center(child: Card(child: Text("Camera not properly initialized"),),);
            }
          } else {
            return const Center(child: CircularProgressIndicator());
          }
        }
      );
  }

  void toggleCameraLens(){
    print("cameras?.length = ${cameras?.length}");
    if((cameras?.length??0)<2) return;
    var lensDirection = _cameraController?.description.lensDirection;
    if(lensDirection == CameraLensDirection.front){
      print("cameras.first = ${cameras?.first}");
      setState(() {
        _cameraController = CameraController(
            cameras!.first,
            ResolutionPreset.ultraHigh);
      });
    } else {
      print("cameras.last = ${cameras?.last}");
      setState(() {
        _cameraController = CameraController(
            cameras!.last,
            ResolutionPreset.ultraHigh);
      });
    }

    if(_cameraController!=null) {
      _initializeControllerFuture = _cameraController!.initialize();
    }
  }


}
```

The `camras` variable is achieved in `main.dart`:

```
...
 cameras = await availableCameras();
 
     if(cameras?.isEmpty??true){
      Message.warn("Could not find camera, camera functions will be turned off !!");
    }

    currentCamera = cameras?.first;

    if(currentCamera==null){
      Message.error("Camera definition detected, but could not be read, camera functions are turned off !!");
    }
    
...

 
```

Tested in:
Samsung S9+ android 10: native ok, web fails.
Asus :native ok, web fails
Emulator Pixel 4 API 33: native ok, web fails.

### Expected results

Expected the camera to be shifted.

Both cameras are listed, shifts correctly in native,  but will not shift in web.

### Actual results

Please see expected results and steps to reproduce.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

import '../../../../common/globals.dart';
import '../../../message/message.dart';

class MWorkCamera extends StatefulWidget{
  const MWorkCamera({super.key});

  @override
  State<MWorkCamera> createState() => _MWorkCameraState();
}

class _MWorkCameraState extends State<MWorkCamera> {

  CameraController? _cameraController;
  late Future<void> _initializeControllerFuture;

  @override
  void initState() {
    super.initState();
    if(currentCamera!=null) {
      _cameraController = CameraController(
        currentCamera!,
        ResolutionPreset.ultraHigh,
        //TODO: Resolution should be selectable
      );
    }

    if(_cameraController!=null) {
      _initializeControllerFuture = _cameraController!.initialize();
    }

  }

  @override
  Widget build(BuildContext context) {

    return FutureBuilder(
        future: _initializeControllerFuture,
        builder: (context, snapshot){
          if(snapshot.connectionState==ConnectionState.done){
            if(_cameraController!=null) {
              return Stack(
                children: [
                  SizedBox(
                      height: double.infinity,
                      width: double.infinity,
                      child: CameraPreview(_cameraController!)
                  ),
                  Positioned.fill(
                      child: Align(
                        alignment: Alignment.bottomCenter,
                        child: Padding(
                          padding: const EdgeInsets.only(bottom:4.0),
                          child: ElevatedButton(
                              onPressed: () async {
                                try {
                                  var pictureFile = await _cameraController
                                      ?.takePicture();
                                  Message.info("${pictureFile?.path.toString()}",durationSeconds: 60);
                                }catch(exception){
                                  Message.error(exception.toString());
                                }
                              },
                              child: const Icon(Icons.photo_camera),),
                        )
                      )
                  ),
                  Positioned.fill(
                      child: Align(
                        alignment: Alignment.bottomRight,
                        child: Padding(
                          padding: const EdgeInsets.all(4.0),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.end,
                            children: [
                              OutlinedButton(
                                  onPressed: () async {


                                  },
                                  child: Icon(Icons.info_outline)
                              ),
                              OutlinedButton(
                                  onPressed: (cameras?.length??0)>=2?(){
                                    toggleCameraLens();
                                  }:null,
                                  child: Icon(Icons.cameraswitch_outlined)
                              )

                            ],
                          ),
                        ),
                      )
                  )

                ],
              );
            } else {
              return const Center(child: Card(child: Text("Camera not properly initialized"),),);
            }
          } else {
            return const Center(child: CircularProgressIndicator());
          }
        }
      );
  }

  void toggleCameraLens(){
    print("cameras?.length = ${cameras?.length}");
    if((cameras?.length??0)<2) return;
    var lensDirection = _cameraController?.description.lensDirection;
    if(lensDirection == CameraLensDirection.front){
      print("cameras.first = ${cameras?.first}");
      setState(() {
        _cameraController = CameraController(
            cameras!.first,
            ResolutionPreset.ultraHigh);
      });
    } else {
      print("cameras.last = ${cameras?.last}");
      setState(() {
        _cameraController = CameraController(
            cameras!.last,
            ResolutionPreset.ultraHigh);
      });
    }

    if(_cameraController!=null) {
      _initializeControllerFuture = _cameraController!.initialize();
    }
  }


}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

[native ok.webm](https://github.com/flutter/flutter/assets/11217296/e53795a0-0526-4e44-b080-dbb9f50fcb0e)

[web not ok.webm](https://github.com/flutter/flutter/assets/11217296/a3391100-6edf-4b63-9f37-076acb871023)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS C:\FlutterProjects\mwork> flutter doctor -v
[√] Flutter (Channel beta, 3.11.0-0.1.pre, on Microsoft Windows [Version 10.0.22621.1702], locale nb-NO)
    • Flutter version 3.11.0-0.1.pre on channel beta at c:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 350d2c3a6c (8 days ago), 2023-05-23 15:52:05 -0700
    • Engine revision 7eca5cd1c5
    • Dart version 3.1.0 (build 3.1.0-63.1.beta)
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\RoarGronmo\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android Studio\Android Studio 2023.1.1.6\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2022.1.1.21
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2022.2.1.20
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2022.2.1.16
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2022.3.1.15
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 113.0.1774.57

[√] Network resources
    • All expected network resources are available.

• No issues found!
PS C:\FlutterProjects\mwork>

```

</details>

**Comment by danagbemava-nc** [comment]
I can reproduce the issue using the plugin code sample. 

### Steps to reproduce
- Run the camera plugin sample on mobile web
- Select a camera
- Attempt to switch to another camera


In my case, the camera just turned black. I caught an exception using the chrome inspector tool, shared below. 


<details>
<summary>recording</summary>

| iOS | android | 
| -- | -- |
| <video src="https://github.com/flutter/flutter/assets/88313112/086b9cb0-d8b2-4188-b13e-baa280038cc7" /> | <video src="https://github.com/flutter/flutter/assets/88313112/8e35004f-93e1-4192-94e2-c5d60f362e09" /> |

</details>

<details>
<summary>logs from chrome inspector</summary>

```
Uncaught PlatformException(unregistered_view_type, A HtmlElementView widget is trying to create a platform view with an unregistered type: <plugins.flutter.io/camera_2>., If you are the author of the PlatformView, make sure `registerViewFactory` is invoked., null)
    at Object.b (https://bundle-oasis.web.app/main.dart.js:4700:19)
    at a_3.yF (https://bundle-oasis.web.app/main.dart.js:56377:14)
    at https://bundle-oasis.web.app/main.dart.js:56467:98
    at a8p.a (https://bundle-oasis.web.app/main.dart.js:5998:62)
    at a8p.$2 (https://bundle-oasis.web.app/main.dart.js:33597:14)
    at a7u.$1 (https://bundle-oasis.web.app/main.dart.js:33591:21)
    at a5T.a5h (https://bundle-oasis.web.app/main.dart.js:34379:33)
    at a5T.px (https://bundle-oasis.web.app/main.dart.js:34381:21)
    at a41.$0 (https://bundle-oasis.web.app/main.dart.js:33973:11)
    at Object.pB (https://bundle-oasis.web.app/main.dart.js:6088:40)
```
</details>



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale en-GB)
    • Flutter version 3.10.2 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (9 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 16.5 20F66
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 16.5 20F66
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 114.0.5735.90

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.11.0-18.0.pre.57, on macOS 13.4 22F66 darwin-arm64, locale en-GB)
    • Flutter version 3.11.0-18.0.pre.57 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 60a87d0798 (5 hours ago), 2023-06-01 21:27:17 -0700
    • Engine revision 3a453f2ccb
    • Dart version 3.1.0 (build 3.1.0-160.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 16.5 20F66
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 16.5 20F66
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 114.0.5735.90
    ! Error: Dean’s iPad is busy: Fetching debug symbols for Dean’s iPad. Xcode will continue when Dean’s iPad is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by stuartmorgan** [comment]
cc @ditman

**Comment by ditman** [comment]
@RoarGronmo do you have any JS Console errors in your web app? You should probably be able to connect your Chrome desktop devtools to your phone to debug (See [docs](https://developer.chrome.com/docs/devtools/remote-debugging/))

My suspicion is that `ResolutionPreset.ultraHigh` may be "too much" for the cameras on the web, and you might be getting an ["over constrained" DOM Exception](https://developer.mozilla.org/en-US/docs/Web/API/OverconstrainedError).

**Comment by RoarGronmo** [comment]
@ditman did a quick test on setting resolution to low and republished at codemagic, same issue when reloading web app on chrome on device (samsung s9+ w/android 10).

tested same web app "built in" samsung browser on device (samsung s9+ w/android 10), same issue.

tested same web app on chrome on Android Emulator Pixel 4 with API 33, same issue.

--

will hook up the samsung device as mentioned in your post above, it will take some time though...

**Comment by ditman** [comment]
> You cannot anticipate that cameras.first is front camera, and camleras.last is the back camera (as it was in the examples I used). In the samsung device I tested there where actually three lences (didn't expect that it detected dual lence camera on each lence).

As devices cameras get more sophisticated, this might become a growing pain (we might need to update the documentation/example of this to handle multiple front/back cameras).

@RoarGronmo is there any documentation/example you followed that made this harder than it should be? What would be the documentation/code example that would have helped you find out about this on your own?

**Comment by ditman** [comment]
Interesting, I guess that the plugin could attempt to do some smart detection and default to the most likely wanted camera, but the moment that there's multiple options it should return multiple values, giving the user the option.

The most immediate fix to me sounds like updating the documentation of the `camera` package, letting users know that they might have to handle the case where there's multiple cameras pointing to the same direction.

(The plugin could also be adapted to be "smart" and if there's only one camera facing the desired direction, immediately pick that one, but when there's ambiguity, return the multiple cameras facing that direction).

**Comment by NamanShergill** [comment]
I figured out the issue, you need to dispose the previous camera controller before initialising a new one for the new camera.

Try this function (And show a loading indicator when the `loading` bool is true)
```dart
  Future<void> onCameraSelected(CameraDescription cameraDescription) async {
    if (kIsWeb) {
      setState(() {
        _isDisposing = true;
      });
      await controller?.dispose();
    }
    controller = CameraController(
      cameraDescription,
      ResolutionPreset.veryHigh,
    );
    try {
      await controller!.initialize();

      setState(() {
        if (kIsWeb) {
          _isDisposing = false;
        }
      });
    } catch (e) {
      print(e);
    }
  }
  ```

**Comment by farookeei** [comment]
_initCamera() async {
    try {
      final cameras = await availableCameras();
      _currentCameraIndex = _currentCameraIndex.clamp(0, cameras.length - 1);
 
      final selectedCamera = cameras[_currentCameraIndex];

      _cameraController =
          CameraController(selectedCamera, ResolutionPreset.max);

      await _cameraController.initialize();
      setState(() => _isLoading = false);
    } catch (e) {
      log(e.toString());
     }
  }

 _toggleCamera() async {
    try {
      final cameras = await availableCameras();

      _currentCameraIndex = (_currentCameraIndex + 1) % cameras.length;
      final selectedCamera = cameras[_currentCameraIndex];

      
        await _cameraController.setDescription(selectedCamera);
     
    } catch (e) {
      log(e.toString());
    }
  }



This will make sure the cameras are switching properly

**Comment by wreppun** [comment]
There are multiple issues here:

1. An assumption that there are a finite set of cameras (covered by @RoarGronmo above).
2. The exception in the title, which fires whenever `controller.setDescription(...)` is called on the web

@RoarGronmo 's fix for multiple cameras (in-comment, above) also re-initializes the CameraController, which incidentally does get camera switching working.

But run [the example from the camera repo](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) on a browser with multiple cameras available (say, a builtin laptop camera and a plugin webcam)
- Pick an initial camera (great!)
- Switch cameras

The exception is thrown, and the preview disappears, and won't return even after switching back to the initial camera.

I have a workaround, which seems to be fine for now (dispose, and then re-initialize the controller), but it would be nice to have consistent behavior across platforms for `setDescription`.

Note: I didn't open a separate issue, because this behavior closely matches the initial reproduction by @danagbemava-nc, and the changed title of this issue.  Happy to do so though.

**Comment by wreppun** [comment]
This could well be related to #126823
