### ISSUE TITLE
Random crash "the getter stderr was called on null"

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#12816]
As I develop, randomly upon fresh deployment I will get this error. Redeploying it again a second time works fine.

```
Unhandled exception:
NoSuchMethodError: The getter 'stderr' was called on null.
Receiver: null
Tried calling: stderr
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      stderr (package:flutter_tools/src/base/io.dart:161)
#3      StdoutLogger.printError (package:flutter_tools/src/base/logger.dart:67)
#4      _AppRunLogger.printError (package:flutter_tools/src/commands/daemon.dart:797)
#5      printError (package:flutter_tools/src/globals.dart:21)
#6      _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:301)
<asynchronous suspension>
#7      _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:298)
<asynchronous suspension>
#8      _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:298)
<asynchronous suspension>
#9      _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:298)
<asynchronous suspension>
#10     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#11     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#12     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#13     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#14     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#15     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#16     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#17     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#18     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#19     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#20     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#21     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#22     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#23     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#24     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#25     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#26     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#27     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#28     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#29     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#30     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#31     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#32     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#33     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#34     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#35     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#36     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#37     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#38     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#39     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#40     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#41     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#42     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#43     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#44     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#45     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#46     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#47     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#48     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#49     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#50     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#51     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#52     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#53     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#54     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#55     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#56     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#57     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#58     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#59     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#60     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#61     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#62     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#63     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#64     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#65     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#66     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#67     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#68     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#69     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#70     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#71     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#72     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#73     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#74     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#75     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#76     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#77     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#78     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#79     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#80     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#81     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#82     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#83     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#84     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#85     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#86     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#87     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#88     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#89     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#90     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#91     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#92     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#93     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#94     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#95     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#96     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#97     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#98     _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#99     _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#100    _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#101    _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#102    _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#103    _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#104    _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#105    _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#106    _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#107    _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#108    _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#109    _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#110    _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#111    _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#112    _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#113    _DevFSHttpWriter._scheduleWrite (package:flutter_tools/src/devfs.dart:308)
<asynchronous suspension>
#114    _DevFSHttpWriter._scheduleWrites (package:flutter_tools/src/devfs.dart:269)
#115    _DevFSHttpWriter.write (package:flutter_tools/src/devfs.dart:256)
<asynchronous suspension>
#116    DevFS.update (package:flutter_tools/src/devfs.dart:498)
<asynchronous suspension>
#117    FlutterDevice.updateDevFS (package:flutter_tools/src/resident_runner.dart:360)
<asynchronous suspension>
#118    HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:268)
<asynchronous suspension>
#119    HotRunner.attach (package:flutter_tools/src/run_hot.dart:137)
<asynchronous suspension>
#120    HotRunner.run (package:flutter_tools/src/run_hot.dart:221)
<asynchronous suspension>
#121    AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:419)
<asynchronous suspension>
#122    AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#123    AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#124    _rootRun (dart:async/zone.dart:1120)
#125    _CustomZone.run (dart:async/zone.dart:1001)
#126    runZoned (dart:async/zone.dart:1467)
#127    AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#128    AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:774)
#129    AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:417)
<asynchronous suspension>
#130    RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:250)
<asynchronous suspension>
#131    FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:253)
<asynchronous suspension>
#132    FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:193)
<asynchronous suspension>
#133    CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#134    FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#135    CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#136    new Future.sync (dart:async/future.dart:222)
#137    CommandRunner.run (package:args/command_runner.dart:109)
#138    FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#139    run.<anonymous closure> (package:flutter_tools/executable.dart:145)
<asynchronous suspension>
#140    AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#141    AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#142    _rootRun (dart:async/zone.dart:1120)
#143    _CustomZone.run (dart:async/zone.dart:1001)
#144    runZoned (dart:async/zone.dart:1467)
#145    AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#146    run (package:flutter_tools/executable.dart:116)
<asynchronous suspension>
#147    main (package:flutter_tools/executable.dart:68)
<asynchronous suspension>
#148    main (file:///Users/faisalabid/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#149    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#150    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

```
[✓] Flutter (on Mac OS X 10.13 17A405, locale en-US, channel master)
    • Flutter at /Users/faisalabid/Development/flutter
    • Framework revision 9184dfba14 (6 hours ago), 2017-10-31 14:22:33 -0700
    • Engine revision fe92a5120c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /Users/faisalabid/Library/Android/sdk
    • Platform android-27, build-tools 27.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 18.3
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Pixel XL • HT6A60208436 • android-arm • Android 8.1.0 (API 27)
```

**Comment by eseidelGoogle** [comment]
@devoncarew do you know who knows the devfs code these days?

**Comment by Hixie** [comment]
So somewhere we're creating a `context` but not setting its `Stdio` entry.

**Comment by Hixie** [comment]
cc @tvolkert

**Comment by tvolkert** [comment]
> So somewhere we're creating a context but not setting its Stdio entry.

That's what it looks like to me as well.  It's not obvious how that's happening though, since we *do* populate the `Stdio` in the root context in [`executable.dart`](https://github.com/flutter/flutter/blob/1affb4237a289c15849e7c8eedb9c5218cc48f72/packages/flutter_tools/lib/executable.dart#L123), and the child context in [`daemon.dart`](https://github.com/flutter/flutter/blob/1affb4237a289c15849e7c8eedb9c5218cc48f72/packages/flutter_tools/lib/src/commands/daemon.dart#L57) *should* inherit from that root context.

**Comment by zoechi** [comment]
I assume this issue is stale. Please let us know if you're still seeing this problem.
