### ISSUE TITLE
3.10.2 sources fail to run on iOS with modified Dart

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#128261]
Likely similar root cause to https://github.com/flutter/flutter/issues/128135.

However I did *not* hit this when running on a newer flutter/engine, e.g. flutter/engine@6ff02c1726, so it must have been fixed.  

I'm most interested in learning how I can back port those fixes to stable so I can compile 3.10.2 with a modified Dart and thus ship to customers. :)

```
eseidel@erics-mbp src % cat ../.gclient
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "https://flutter.googlesource.com/mirrors/engine",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
eseidel@erics-mbp src % gclient sync
Updating depot_tools...
Syncing projects: 100% (137/137), done.
Running hooks: 100% (11/11), done.     
eseidel@erics-mbp src % git -C flutter rev-parse HEAD         
90fa3ae28fe6ddaee1af2c120f01e50201c1401b
eseidel@erics-mbp src % git -C third_party/dart rev-parse HEAD
063c854bc4f55fafc2cf09aad74f0357c4fe69be
eseidel@erics-mbp src % echo "foo" > third_party/dart/foo
eseidel@erics-mbp src % git -C third_party/dart add foo
eseidel@erics-mbp src % git -C third_party/dart commit -a -m "just touch dart"
[detached HEAD 174a7e3c813] just touch dart
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 foo
eseidel@erics-mbp src % git -C third_party/dart rev-parse HEAD
174a7e3c813ca9aee683c12fe59cbf0fc7e95975
eseidel@erics-mbp src % rm -rf out/host_release_unopt
eseidel@erics-mbp src % rm -rf out/ios_release_unopt_arm64
eseidel@erics-mbp src % ./flutter/tools/gn --no-goma --unoptimized --runtime-mode=release --no-enable-unittests
<elided>
eseidel@erics-mbp src % ninja -C out/host_release_unopt
<elided>
eseidel@erics-mbp src % ./flutter/tools/gn --no-goma --unoptimized --runtime-mode=release --ios --mac-cpu=arm64
<elided>
eseidel@erics-mbp src % ninja -C out/ios_release_unopt_arm64
<elided>
eseidel@erics-mbp GitHub % cd ../../
eseidel@erics-mbp GitHub % flutter create ios_test
<elided>
eseidel@erics-mbp GitHub % cd ios_test

eseidel@erics-mbp ios_test % open ios/Runner.xcworkspace
(set up signing stuff in XCode)
eseidel@erics-mbp ios_test % flutter run -d iphone --release --local-engine-src-path=$HOME/Documents/GitHub/engine_test/src --local-engine ios_release_unopt_arm64 -v  
<elided>

                    [   +3 ms] /Users/eseidel/Documents/GitHub/engine_test/src/out/host_release_unopt/dart-sdk/bin/dart --disable-dart-dev
                    /Users/eseidel/Documents/GitHub/engine_test/src/out/host_release_unopt/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
                    /Users/eseidel/Documents/GitHub/engine_test/src/out/ios_release_unopt_arm64/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true
                    -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/90fa3ae28fe6ddaee1af2c120f01e50201c1401b/ -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --packages
                    /Users/eseidel/Documents/GitHub/ios_test/.dart_tool/package_config.json --output-dill
                    /Users/eseidel/Documents/GitHub/ios_test/.dart_tool/flutter_build/98c8e8eb93b966a0769d5410f491f86c/app.dill --depfile
                    /Users/eseidel/Documents/GitHub/ios_test/.dart_tool/flutter_build/98c8e8eb93b966a0769d5410f491f86c/kernel_snapshot.d --verbosity=error package:ios_test/main.dart
                    [  +27 ms] Persisting file store
                    [   +1 ms] Done persisting file store
                    [   +3 ms] "flutter assemble" took 1,618ms.
                    [   +3 ms] ensureAnalyticsSent: 0ms
                    [        ] Running 0 shutdown hooks
                    [        ] Shutdown hooks complete
                    [        ] exiting with code 1
                    error: [ +170 ms] Unhandled exception:
                               Crash when compiling package:ios_test/main.dart:
                               Unexpected Kernel SDK Version 1ee17d8fc0 (expected 063c854bc4).

                               #0      BinaryBuilder._readAndVerifySdkHash (package:kernel/binary/ast_from_binary.dart:657:7)
                               #1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:689:7)
                               #2      Timeline.timeSync (dart:developer/timeline.dart:166:22)
                               #3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:673:21)
                               #4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:480:10)
                               #5      ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:426:13)
                               <asynchronous suspension>
                               #6      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:79:31)
                               <asynchronous suspension>
                               #7      withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
                               <asynchronous suspension>
                               #8      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:62:29)
                               <asynchronous suspension>
                               #9      kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:61:10)
                               <asynchronous suspension>
                               #10     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50:11)
                               <asynchronous suspension>
                               #11     compileToKernel (package:vm/kernel_front_end.dart:452:22)
                               <asynchronous suspension>
                               #12     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:620:17)
                               <asynchronous suspension>
                               #13     starter (package:frontend_server/starter.dart:99:12)
                               <asynchronous suspension>
                               #14     main (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
                               <asynchronous suspension>

                    [   +1 ms] Target kernel_snapshot failed: Exception
                               #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:244:7)
                               <asynchronous suspension>
                               #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
                               <asynchronous suspension>
                               #2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
                               <asynchronous suspension>
                               #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
                               <asynchronous suspension>
                               #4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
                               <asynchronous suspension>
                               #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
                               <asynchronous suspension>
                               #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
                               <asynchronous suspension>
                               #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:32)
                               <asynchronous suspension>
                               #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
                               <asynchronous suspension>
                               #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                               <asynchronous suspension>
                               #10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
                               <asynchronous suspension>
                               #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
                               <asynchronous suspension>
                               #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                               <asynchronous suspension>
                               #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
                               <asynchronous suspension>
                               #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
                               <asynchronous suspension>
                               #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                               <asynchronous suspension>
                               #16     main (package:flutter_tools/executable.dart:91:3)
                               <asynchronous suspension>

                    [   +1 ms] 
                               #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                               #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:332:7)
                               <asynchronous suspension>
                               #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
                               <asynchronous suspension>
                               #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                               <asynchronous suspension>
                               #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
                               <asynchronous suspension>
                               #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
                               <asynchronous suspension>
                               #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                               <asynchronous suspension>
                               #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
                               <asynchronous suspension>
                               #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
                               <asynchronous suspension>
                               #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                               <asynchronous suspension>
                               #10     main (package:flutter_tools/executable.dart:91:3)
                               <asynchronous suspension>
                    Failed to package /Users/eseidel/Documents/GitHub/ios_test.

                    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from
                    project 'Runner')
                    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from
                    project 'Runner')

                    Result bundle written to path:
                        /var/folders/fv/fqqmfjqd6zvdqrbrv78gt4m80000gn/T/flutter_tools.mF4WkD/flutter_ios_build_temp_dir0Aa8eJ/temporary_xcresult_bundle
```

**Comment by eseidel** [comment]
The most helpful thing someone could do would be to provide me any pointers to what might have fixed this on main (otherwise I guess I'll just git-bisect across flutter and engine versions?).

**Comment by eseidel** [comment]
I wonder if this issue exists on main, just the `flutter` tool has some behavior to disable these checks when you use main?

**Comment by eseidel** [comment]
Another thing which could be helpful is for someone to tell me how I'm supposed to to this. :) My usecase is that I want to be able to take a flutter version and modify it's Dart VM a small amount. (I need to do this because code push on iOS requires a modified Dart VM).

**Comment by eseidel** [comment]
Hmm, I suspect I was getting past this on `main` due to using `--no-prebuild-dart-sdk`, which doesn't work on 3.10.2 due to https://github.com/flutter/flutter/issues/128135

**Comment by eseidel** [comment]
Per @zanderso's suggestion disabling the check in the SDK when building makes this go away: https://github.com/dart-lang/sdk/blob/main/sdk_args.gni#L31

**Comment by danagbemava-nc** [comment]
Labeling based on the information shared above for further insight from the team.

**Comment by jason-simmons** [comment]
I was able to get this to work using this process:
* reset the framework tree to the `3.10.2` tag
* reset the engine tree to the `3.10.2` tag and run `gclient sync`
* in the engine tree, cd to `src/flutter` and run `../tools/dart/create_updated_flutter_deps.py`
  * This updates the engine's `DEPS` to match the Dart SDK in `third_party/dart`
  * (see https://github.com/flutter/flutter/issues/127606#issuecomment-1573113871)
* Run `gclient sync` again
* Apply patches to `third_party/dart`
* Build the host and target engines with the `--no-prebuilt-dart-sdk` flag

After that I can use `flutter run --local-engine` to produce an iOS binary using the locally patched Dart SDK sources.

**Comment by eseidel** [comment]
Sounds like `--no-prebuilt-dart-sdk` is the correct path forward and that's just blocked on https://github.com/flutter/flutter/issues/127606#issuecomment-1573113871, and we can just dup this against that?

**Comment by jason-simmons** [comment]
Yes - the `--no-prebuilt-dart-sdk` flag should always be used when building the engine with a modified Dart SDK.

Unfortunately, the release branches currently have a `DEPS` file that is out of sync with the branch's Dart SDK.  This will require a manual workaround until https://github.com/flutter/flutter/issues/127606 is resolved.

**Comment by eseidel** [comment]
Thanks!  I dropped the `--no-prebuilt-dart-sdk` as part of brainstorming with @zanderso, but happy to move back to using it. Thank you for looking!
