### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by AbhirKarande** [flutter/flutter#128238]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:200:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:191:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:169:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:871:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:520:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:308:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.3, on macOS 12.6.6 21G646 darwin-x64, locale
    en-US)
    [32m•[39m Flutter version 3.10.3 on channel stable at
      /Users/abhirkarande/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f92f44110e (4 days ago), 2023-06-01 18:17:33 -0500
    [32m•[39m Engine revision 2a3401c9bb
    [32m•[39m Dart version 3.0.3
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /Users/abhirkarande/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.0)
    [32m•[39m Xcode at /Users/abhirkarande/Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14A309
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at /Users/abhirkarande/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 12.6.6 21G646 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f92f44110e87bad5ff168335c36da6f6053036e6

**Comment by danagbemava-nc** [comment]
Hi @AbhirKarande, what platform were you attempting to run on? How often do you run into this issue?

**Comment by AbhirKarande** [comment]
Hello @danagbemava-nc, for this particular run that crashed, I selected Chrome. I just got flutter installed yesterday, and successfully got all of the flutter doctor aspects setup properly. Furthermore, when running it, I get this issue that pops up on my mac: “impellerc” can’t be opened because Apple cannot check it for malicious software. I have looked at previous issues but none of the fixes work for some reason.

**Comment by danagbemava-nc** [comment]
> “impellerc” can’t be opened because Apple cannot check it for malicious software

Hi @AbhirKarande, if you allow this in your settings, do you still get the crash? You should be able to allow it by following the instructions in https://support.apple.com/en-za/guide/mac-help/mchleab3a043/12.0/mac/12.0

**Comment by AbhirKarande** [comment]
Yes, it still does crash. When following the instructions I get this message: “impellerc” can’t be opened because Apple cannot check it for malicious software.

**Comment by danagbemava-nc** [comment]
One more thing, can you check on the `master` channel to see if you still face this issue?
