### ISSUE TITLE
execute `flutter doctor` always failed on macOS

### ISSUE THREAD

**Issue by cqululei** [flutter/flutter#12838]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

SocketException: SocketException: OS Error: Operation timed out, errno = 60, address = storage.googleapis.com, port = 50754

```
#0      _attempt (package:flutter_tools/src/base/net.dart:40)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:405)
<asynchronous suspension>
#3      _downloadZipArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:412)
<asynchronous suspension>
#4      _withTemporaryFile (package:flutter_tools/src/cache.dart:433)
<asynchronous suspension>
#5      _downloadZipArchive (package:flutter_tools/src/cache.dart:411)
#6      FlutterEngine._downloadItem (package:flutter_tools/src/cache.dart:378)
#7      FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:346)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:223)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:196)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:193)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#18     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1120)
#22     _CustomZone.run (dart:async/zone.dart:1001)
#23     runZoned (dart:async/zone.dart:1467)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#27     main (file:///Users/lulei/Develop/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[-] Flutter (on Mac OS X 10.12.1 16B2657, locale zh-Hans-CN, channel alpha)
    • Flutter at /Users/lulei/Develop/flutter
    • Framework revision e8aa40eddd (2 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/lulei/Develop/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/lulei/Develop/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

[-] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    ✗ Flutter requires a minimum Xcode version of 8.0.0.
      Download the latest version or update via the Mac App Store.
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.2.0

[-] Android Studio (version 2.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.3
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • SM A3009 • 614bdcd7 • android-arm • Android 5.0.2 (API 21)

```

**Comment by InMatrix** [comment]
Quick question: are you installing Flutter in China? Were you using a VPN?

The Flutter tool downloads some dependencies that are not accessible from China. Please watch #11681 as we continue investigating this issue.

**Comment by xster** [comment]
Fixed now https://github.com/flutter/flutter/wiki/Using-Flutter-in-China
