### ISSUE TITLE
Crash on Flutter version 3.10.3

### ISSUE THREAD

**Issue by gabrielgarciagava** [flutter/flutter#128316]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We are seeing an increasing number of crashes in crashlytics after upgrading to flutter 3.10.X.
Unfortunately, I don't have any steps to reproduce, and also the stack trace is unreadable to figure out where it is happening.

Is there a way to symbolicate it?

Stacktrace:
```
Crashed: com.apple.main-thread
0  Flutter                        0x33c9c (Missing UUID 4c4c44e755553144a19362a9728e600a)
1  Flutter                        0x496d5c (Missing UUID 4c4c44e755553144a19362a9728e600a)
2  Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
3  Flutter                        0x497f10 (Missing UUID 4c4c44e755553144a19362a9728e600a)
4  Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
5  Flutter                        0x497f10 (Missing UUID 4c4c44e755553144a19362a9728e600a)
6  Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
7  Flutter                        0x497f10 (Missing UUID 4c4c44e755553144a19362a9728e600a)
8  Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
9  Flutter                        0x497f10 (Missing UUID 4c4c44e755553144a19362a9728e600a)
10 Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
11 Flutter                        0x495050 (Missing UUID 4c4c44e755553144a19362a9728e600a)
12 Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
13 Flutter                        0x497f10 (Missing UUID 4c4c44e755553144a19362a9728e600a)
14 Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
15 Flutter                        0x497f10 (Missing UUID 4c4c44e755553144a19362a9728e600a)
16 Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
17 Flutter                        0x48afb0 (Missing UUID 4c4c44e755553144a19362a9728e600a)
18 Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
19 Flutter                        0x497f10 (Missing UUID 4c4c44e755553144a19362a9728e600a)
20 Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
21 Flutter                        0x497f10 (Missing UUID 4c4c44e755553144a19362a9728e600a)
22 Flutter                        0x48c850 (Missing UUID 4c4c44e755553144a19362a9728e600a)
23 Flutter                        0x493e18 (Missing UUID 4c4c44e755553144a19362a9728e600a)
24 Flutter                        0x487e48 (Missing UUID 4c4c44e755553144a19362a9728e600a)
25 Flutter                        0x3dd6c8 (Missing UUID 4c4c44e755553144a19362a9728e600a)
26 Flutter                        0x3dda58 (Missing UUID 4c4c44e755553144a19362a9728e600a)
27 Flutter                        0x2e4ae8 (Missing UUID 4c4c44e755553144a19362a9728e600a)
28 Flutter                        0x3dd174 (Missing UUID 4c4c44e755553144a19362a9728e600a)
29 Flutter                        0x3de9a0 (Missing UUID 4c4c44e755553144a19362a9728e600a)
30 Flutter                        0x3ddc98 (Missing UUID 4c4c44e755553144a19362a9728e600a)
31 Flutter                        0x3f3dbc (Missing UUID 4c4c44e755553144a19362a9728e600a)
32 Flutter                        0x2e3120 (Missing UUID 4c4c44e755553144a19362a9728e600a)
33 Flutter                        0x2e644c (Missing UUID 4c4c44e755553144a19362a9728e600a)
34 CoreFoundation                 0xae678 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
35 CoreFoundation                 0x32654 __CFRunLoopDoTimer + 1064
36 CoreFoundation                 0x2ce00 __CFRunLoopDoTimers + 320
37 CoreFoundation                 0xb4b0 __CFRunLoopRun + 1936
38 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
39 GraphicsServices               0x1374 GSEventRunModal + 164
40 UIKitCore                      0x514b58 -[UIApplication _run] + 1100
41 UIKitCore                      0x296090 UIApplicationMain + 364
42 Runner                         0xa920 main + 13 (AppDelegate.swift:13)
43 ???                            0x102a71da4 (Missing)
```

### Expected results

Not crash

### Actual results

Crash

### Code sample

<details><summary>Code sample</summary>
No code sample, unfortunately
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

Bear in mind that even though it is complaining about not being in a channel, this is indeed the same commit of the stable channel

```console
[!] Flutter (Channel unknown, 3.10.3, on macOS 13.3.1 22E772610a darwin-arm64, locale en-NL)
    ! Flutter version 3.10.3 on channel unknown at REDACTED
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision f92f44110e (4 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update
      checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/gabrielgava/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by Muskan3101** [comment]
Please make sure that binding has been initialized!
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const MyApp());
}

**Comment by dam-ease** [comment]
Hi @gabrielgarciagava. Can you provide a pattern or any other additional logs that can be helpful to analyze this issue further?

**Comment by dam-ease** [comment]
Thanks for the log @mraleph. From the log, this may be related to #127095. @gabrielgarciagava kindly check if you are using BackdropFilter with ImageFilter.blur() in your code.

**Comment by RandyXi** [comment]
My first attempt installing Flutter ran me into a brick wall while I sit here days envying other installing Flutter successful, anyone want to exchange seats? anywho here is where I am dealing with this... help? if I get any progress I will post what I did to resolve.... wish me best luck but solutions first be nice...



RandyXi@ECAD MINGW64 ~
$ flutter doctor
The system cannot find the path specified.
'B' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
Doctor summary (to see all details, run flutter doctor -v):
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://git
    X Exception: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH en
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.6.2)
    ! Unable to locate a Windows 10 SDK. If building fails, install the Windows 10 SDK in Visual Studio.
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.78.2)
[√] Connected device (2 available)
[√] Network resources

! Doctor found issues in 3 categories.

RandyXi@ECAD MINGW64 ~
$ flutter doctor
The system cannot find the path specified.
'B' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
Doctor summary (to see all details, run flutter doctor -v):
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://git
    X Exception: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH en
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.6.2)
    ! Unable to locate a Windows 10 SDK. If building fails, install the Windows 10 SDK in Visual Studio.
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.78.2)
[√] Connected device (2 available)
[√] Network resources

! Doctor found issues in 3 categories.

RandyXi@ECAD MINGW64 ~
$ flutter doctor -v
The system cannot find the path specified.
'B' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://git
    X Exception: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH en
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:488:7)
      #2      OperatingSystemUtils.which (package:flutter_tools/src/base/os.dart:92:31)
      #3      FlutterValidator._validateSdkBinary (package:flutter_tools/src/doctor.dart:610:52)
      #4      FlutterValidator._validateRequiredBinaries (package:flutter_tools/src/doctor.dart:597:47)
      #5      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:511:7)
      #6      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:251:72)
      #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #8      _rootRun (dart:async/zone.dart:1399:13)
      #9      _CustomZone.run (dart:async/zone.dart:1301:19)
      #10     _runZoned (dart:async/zone.dart:1804:10)
      #11     runZonedGuarded (dart:async/zone.dart:1792:12)
      #12     runZoned (dart:async/zone.dart:1744:12)
      #13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:243:9)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:371:72)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1568:12)
      <asynchronous suspension>
      #18     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
      <asynchronous suspension>
      #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #20     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
      <asynchronous suspension>
      #21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
      <asynchronous suspension>
      #22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
      <asynchronous suspension>
      #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
      <asynchronous suspension>
      #25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #26     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>


[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\RandyXi\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.6.2)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.6.33723.286
    ! Unable to locate a Windows 10 SDK. If building fails, install the Windows 10 SDK in Visual Studio.

[√] Android Studio (version 2022.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\RandyXi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome  • web-javascript • unknown

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
