### ISSUE TITLE
[Pigeon] Unhandled exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by nosadaniel** [flutter/flutter#128570]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When I run bash:

```
flutter pub run pigeon \
  --input pigeons/message.dart \
  --dart_out lib/pigeon.dart \
  --kotlin_out android/app/src/main/kotlin/dev/flutter/pigeon/Pigeon.kt \
  --kotlin_package "dev.flutter.pigeon" \
```
 

Here is my pubspec.yaml

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: 10.0.1
```

Flutter version

```
Flutter 3.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 682aa387cf (3 days ago) • 2023-06-05 18:04:56 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1
```

Any Suggestion will be appreciated
@gaaclarke 

### Expected results

success

### Actual results

It seem a null value is being used somewhere

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:pigeon/pigeon.dart';

class Book {
  String? title;
  String? author;
}

@HostApi()
abstract class BookApi {
  List<Book?> search(String keyword);
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details><summary>Logs</summary>

```console
Unhandled exception:
Null check operator used on a null value
#0      _RootBuilder.visitMethodDeclaration (package:pigeon/pigeon_lib.dart:1051:68)
#1      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8988:50)
#2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9721:20)
#3      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2059:13)
#4      _RootBuilder.visitClassDeclaration (package:pigeon/pigeon_lib.dart:988:10)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2049:50)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9721:20)
#7      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2594:21)
#8      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:930:10)
#9      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2587:50)
#10     Pigeon.parseFile (package:pigeon/pigeon_lib.dart:1260:16)
#11     Pigeon.runWithOptions (package:pigeon/pigeon_lib.dart:1453:16)
#12     Pigeon.run (package:pigeon/pigeon_lib.dart:1421:12)
#13     runCommandLine (package:pigeon/pigeon_cl.dart:14:17)
#14     main (file:///Users/nosakharedanielahanor/.pub-cache/hosted/pub.dev/pigeon-10.0.0/bin/pigeon.dart:10:14)
#15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en-GB)
    ! Warning: `flutter` on your path resolves to
      /Users/nosakharedanielahanor/Documents/development/flutter/bin/flutter, which is not inside your current
      Flutter SDK checkout at /Users/nosakharedanielahanor/documents/development/flutter. Consider adding
      /Users/nosakharedanielahanor/documents/development/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nosakharedanielahanor/Documents/development/flutter/bin/dart,
      which is not inside your current Flutter SDK checkout at
      /Users/nosakharedanielahanor/documents/development/flutter. Consider adding
      /Users/nosakharedanielahanor/documents/development/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I tried replicating using the package example but was unable to see the reported error. Upon running the said command, I got below:

```
Building package executable... 
Built pigeon:pigeon.
dhs@Dhss-MacBook-Pro app % 
```

Keeping this issue open based on the report and error thrown.

**Comment by stuartmorgan** [comment]
It may depend on a dependency version. @nosadaniel could you provide your pubspec.lock file so we can try testing with the same versions of dependencies (most likely `analyzer`, but possibly something else).

The Pigeon code definitely looks unsafe, so we can fix it speculatively, but it would be good to have a repro case to ensure that the fix works.

**Comment by nosadaniel** [comment]
Thanks @darshankawar and @stuartmorgan for your kind feedback.

I was enable to fix the issue by using the following commands
```flutter clean  && flutter pub cache repair
&& flutter pub get````

I think it might have been an issue with some old cache dependency
