### ISSUE TITLE
Crash in device deamon

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12861]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2017.2.5` • Flutter plugin `18.4` • Dart plugin `172.4343.25`

Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision 35bb855c0d (8 hours ago) • 2017-11-02 18:11:34 -0700
Engine • revision 3021e8f6c3
Tools • Dart 1.25.0-dev.11.0

## Exception

```
A Flutter device daemon stopped unexpectedly.
Details: Daemon #2 exited. Exit code: 255. Stderr:
Unhandled exception:
Exception: adb not responding
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      AndroidDevice._getProperty (package:flutter_tools/src/android/android_device.dart:94)
<asynchronous suspension>
#2      AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart:125)
<asynchronous suspension>
#3      _deviceToMap (package:flutter_tools/src/commands/daemon.dart:693)
<asynchronous suspension>
#4      DeviceDomain._onDeviceEvent.<anonymous closure>.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:576)
<asynchronous suspension>
#5      _rootRunUnary (dart:async/zone.dart:1128)
#6      _CustomZone.runUnary (dart:async/zone.dart:1012)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#10     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:343)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
	at io.flutter.run.daemon.DeviceService.daemonStopped(Unknown Source)
	at io.flutter.run.daemon.DeviceDaemon$Listener.processTerminated(DeviceDaemon.java:357)
	at io.flutter.run.daemon.DaemonApi$1.processTerminated(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
	at com.sun.proxy.$Proxy15.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$3.run(ProcessHandler.java:184)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:260)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:165)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:161)
	at com.intellij.execution.process.BaseOSProcessHandler.onOSProcessTerminated(BaseOSProcessHandler.java:192)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:92)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:155)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:140)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mit-mit** [comment]
cc @devoncarew

**Comment by Hixie** [comment]
I'm going to close this since it doesn't seem to have sufficient information to be actionable.
