### ISSUE TITLE
[tool_crash] _CastError: (#0      new Plugin._fromLegacyYaml (package:flutter_tools/src/plugins.dart:198:66))

### ISSUE THREAD

**Issue by sadaqatdev** [flutter/flutter#128655]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      new Plugin._fromLegacyYaml (package:flutter_tools/src/plugins.dart:198:66))
```
#0      new Plugin._fromLegacyYaml (package:flutter_tools/src/plugins.dart:198:66)
#1      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:88:19)
#2      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#3      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#4      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#5      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#6      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:179:5)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-PK)
    • Flutter version 3.7.12 on channel stable at /Users/sadaqathussain/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (8 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sadaqathussain/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/sadaqathussain/Library/Android/sdk
    • Java binary at: /Applications/AndroidStudio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/AndroidStudio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • SM G973F (mobile) • 192.168.43.14:34977                           • android-arm64  • Android 12 (API 31)
    • SM G973F (mobile) • adb-RF8M328SNDL-KEGtSX._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos                                         • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)      • chrome                                        • web-javascript • Google Chrome 114.0.5735.106

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.1.0+45
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1

**Comment by darshankawar** [comment]
@sadaqatdev 
This issue has been already fixed as part of https://github.com/flutter/flutter/issues/120230 and is available on latest stable version:

<img width="794" alt="Screenshot 2023-06-12 at 2 15 47 PM" src="https://github.com/flutter/flutter/assets/67046386/44ba0051-799c-41ff-bf06-104cb6518fcc">

You will need to upgrade to latest stable or master to see the fix working.
Closing, as this is already fixed.

**Comment by sadaqatdev** [comment]
our project is not on full null saftey , we use null safe lib and our code is not support null safe , and we cannot use the latest 3.10.0 
so how we can handle this
