### ISSUE TITLE
Fail to load AndroidDeviceInfo with Nexus 7 Android 4.4.4 (API 19)

### ISSUE THREAD

**Issue by jimmyshiau** [flutter/flutter#12862]
## Steps to Reproduce
```
AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
```

```
E/MethodChannel#plugins.flutter.io/device_info(27326): Failed to handle method call
E/MethodChannel#plugins.flutter.io/device_info(27326): java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.String;@41ec8c98
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:250)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:52)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at io.flutter.plugins.deviceinfo.DeviceInfoPlugin.onMethodCall(DeviceInfoPlugin.java:76)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at io.flutter.view.FlutterView.handlePlatformMessage(FlutterView.java:709)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at android.os.Looper.loop(Looper.java:123)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/MethodChannel#plugins.flutter.io/device_info(27326): 	at dalvik.system.NativeStart.main(Native Method)
E/flutter (27326): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (27326): PlatformException(error, Unsupported value: [Ljava.lang.String;@41ec8c98, null)
E/flutter (27326): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514)
E/flutter (27326): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter (27326): <asynchronous suspension>
E/flutter (27326): #2      DeviceInfoPlugin.androidInfo (package:device_info/device_info.dart:25)
```

* Works fine if make `EMPTY_STRING_LIST` to string List
```java
if (VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP) {
	build.put("supported32BitAbis", Arrays.asList(Build.SUPPORTED_32_BIT_ABIS));
	build.put("supported64BitAbis", Arrays.asList(Build.SUPPORTED_64_BIT_ABIS));
	build.put("supportedAbis", Arrays.asList(Build.SUPPORTED_ABIS));
} else {
	build.put("supported32BitAbis", Arrays.asList(EMPTY_STRING_LIST));
	build.put("supported64BitAbis", Arrays.asList(EMPTY_STRING_LIST));
	build.put("supportedAbis", Arrays.asList(EMPTY_STRING_LIST));
}
```

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-TW, channel master)
    • Flutter at /usr/local/flutter/flutter
    • Framework revision 3914214641 (29 hours ago), 2017-11-01 22:31:29 -0700
    • Engine revision 88cf09ffe6
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/jimmy/Library/Android/sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/jimmy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3757.55

[✓] Connected devices
    • Nexus 7                   • 0874da9c                             • android-arm • Android 4.4.4 (API 19)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 5.1.1 (API 22) (emulator)
    • iPhone 6s                 • 81CCEA92-249F-4C84-B335-AECBE16A4499 • ios         • iOS 11.0 (simulator)

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
Standard message codec does not accept object arrays (mainly because it would not be symmetric, as you'd never be able to get a `String[]` or similar back from Dart). The plugin should not attempt to send one.
