### ISSUE TITLE
[tool_crash] _TypeError: (#0      LicenseCollector.obtainLicenses.<anonymous closure> (package:flutter_tools/src/license_collector.dart:87:67))

### ISSUE THREAD

**Issue by Mahsanali0786** [flutter/flutter#128680]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=WSBAWS8P75U8TSUW --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      LicenseCollector.obtainLicenses.<anonymous closure> (package:flutter_tools/src/license_collector.dart:87:67))
```
#0      LicenseCollector.obtainLicenses.<anonymous closure> (package:flutter_tools/src/license_collector.dart:87:67)
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:393:20)
#2      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#3      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#4      new List.of (dart:core-patch/array_patch.dart:47:28)
#5      Iterable.toList (dart:core/iterable.dart:494:7)
#6      LicenseCollector.obtainLicenses (package:flutter_tools/src/license_collector.dart:90:10)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:444:59)
<asynchronous suspension>
#8      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:457:26)
<asynchronous suspension>
#9      HotRunner.attach (package:flutter_tools/src/run_hot.dart:279:40)
<asynchronous suspension>
#10     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:648:9)
<asynchronous suspension>
#11     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:646:5)
<asynchronous suspension>
#12     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:638:15)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.10.3, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.10.3 on channel stable at C:\flutterSrc\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (10 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\maali\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.79.0)
    • VS Code at C:\Users\maali\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • vivo Y67 (mobile) • WSBAWS8P75U8TSUW • android-arm64  • Android 6.0 (API 23)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 114.0.5735.110
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 114.0.1823.43

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 90c64ed42ba53a52d18f0cb3b17666c8662ed2a0
### Plugins
cloud_firestore-4.8.0
cloud_firestore_web-3.6.0
connectivity_plus-3.0.6
firebase_auth-4.6.2
firebase_auth_web-5.5.2
firebase_core-2.13.1
firebase_core_web-2.5.0
firebase_storage-11.2.2
firebase_storage_web-3.6.2
flutter_plugin_android_lifecycle-2.0.15
image_picker-0.8.7+5
image_picker_android-0.8.6+19
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+4
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.6
printing-5.11.0
share_extend-2.0.0
share_plus-7.0.2
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
smart_auth-1.0.8
url_launcher_linux-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6

**Comment by darshankawar** [comment]
This seems to be a new issue as I couldn't find an already triaged / existing issue with same log.

/cc @christopherfujino

**Comment by Mahsanali0786** [comment]
i dont why i was seeing this. But it was solved later on.

**Comment by Mahsanali0786** [comment]
closing

**Comment by darshankawar** [comment]
Let's keep it open as there's a PR to fix.

**Comment by christopherfujino** [comment]
Fixed in https://github.com/flutter/flutter/pull/128748
