### ISSUE TITLE
[shared_preferences] SharedPreferences.getInstance() throws java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by SamedHrmn** [flutter/flutter#128666]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Except for the first clean run, I try to open the app again in my Android phone.
2. The application crashes when trying to initialize the shared_preference object (**shared_preferences: ^2.1.2**).

### Expected results

No exception

### Actual results

java.lang.OutOfMemoryError

### Code sample

<details><summary>Code sample</summary>

```dart
class AppSharedPrefs {  // My utility class

static final AppSharedPrefs _instance = AppSharedPrefs._internal();
AppSharedPrefs._internal();

 factory AppSharedPrefs() {
    return _instance;
  }

SharedPreferences? sharedPreferences;

Future<void> initSharedPref() async {
    if (sharedPreferences != null) return;
    sharedPreferences = await SharedPreferences.getInstance();
  }

}

//---------------------------------------------------------------------------

void main() async {
   
runZonedGuarded<Future<void>>(() async {
    final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
    FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.top, SystemUiOverlay.bottom]);
    await ScreenUtil.ensureScreenSize();
    await Firebase.initializeApp();
    await AppSharedPrefs().initSharedPref();  // crash here

    if (!kDebugMode) {
      FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
    }

    OneSignalUtil().init();
    await HiveManager().initHiveDB();
 
    showDevicePreview = true;
    if (showDevicePreview && kDebugMode) {
      runApp(DevicePreview(
        builder: (context) => const MyApp(),
      ));
    } else {
      runApp(const MyApp());
    }
  }, (error, stack) {
    print(stack.toString());
    if (!kDebugMode) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true, printDetails: true);
    }
  });
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console

[ +485 ms] --------- beginning of main
                    06-11 21:09:11.120 D/SemNscXgbL2Nrt( 1372): L2 NRT 1 sample inference time: 0.796038 msecs
[   +6 ms] executing: C:\Users\samed\SDK\android\platform-tools\adb.exe -s 192.168.1.24:37161 shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode
true --ez verify-entry-points true com.deepsport.exercise.demo/com.deepsport.exercise.demo.MainActivity
[ +239 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=com.deepsport.exercise.demo/.MainActivity (has extras) }
[        ] Waiting for VM Service port to be available...
[ +360 ms] D/FlutterGeolocator(26920): Attaching Geolocator to activity
[  +38 ms] VM Service URL on device: http://127.0.0.1:44495/yWTBzxmZ0xY=/
[        ] executing: C:\Users\samed\SDK\android\platform-tools\adb.exe -s 192.168.1.24:37161 forward tcp:0 tcp:44495
[  +28 ms] 58407
[        ] Forwarded host port 58407 to device port 44495 for VM Service
[   +3 ms] Caching compiled dill
[  +38 ms] Connecting to service protocol: http://127.0.0.1:58407/yWTBzxmZ0xY=/
[  +97 ms] D/FlutterGeolocator(26920): Creating service.
[        ] D/FlutterGeolocator(26920): Binding to location service.
[  +94 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:58407/yWTBzxmZ0xY=/.
[  +47 ms] D/FlutterGeolocator(26920): Geolocator foreground service connected
[        ] D/FlutterGeolocator(26920): Initializing Geolocator services
[        ] D/FlutterGeolocator(26920): Flutter engine connected. Connected engine count 1
[ +181 ms] DDS is listening at http://127.0.0.1:58410/-IfwZMe1kf0=/.
[  +52 ms] Successfully connected to service protocol: http://127.0.0.1:58407/yWTBzxmZ0xY=/
[  +69 ms] DevFS: Creating new filesystem on the device (null)
[  +20 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.deepsport.exercise.demo/code_cache/deepsport_iosHJJGIR/deepsport_ios/)
[   +1 ms] Updating assets
[ +402 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +3 ms] Syncing files to device SM G990E...
[   +2 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:deepsport_ios/main.dart 700f8c33-dddc-44df-9c47-461af2a75775
[        ] <- 700f8c33-dddc-44df-9c47-461af2a75775
[  +50 ms] Bundle processing done.
[   +2 ms] I/t.exercise.demo(26920): Compiler allocated 6133KB to compile void android.view.ViewRootImpl.performTraversals()
[  +64 ms] I/t.exercise.demo(26920): Background concurrent copying GC freed 1180(80KB) AllocSpace objects, 3(108MB) LOS objects, 22% free, 83MB/107MB, paused 21.054ms,25us total 52.064ms
[ +113 ms] I/t.exercise.demo(26920): Waiting for a blocking GC Alloc
[  +14 ms] I/t.exercise.demo(26920): WaitForGcToComplete blocked Alloc on Background for 15.856ms
[        ] I/t.exercise.demo(26920): Starting a blocking GC Alloc
[   +4 ms] I/t.exercise.demo(26920): Forcing collection of SoftReferences for 109MB allocation
[        ] I/t.exercise.demo(26920): Starting a blocking GC Alloc
[   +3 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device SM G990E... (completed in 258ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +1 ms] I/t.exercise.demo(26920): Alloc concurrent copying GC freed 2549(159KB) AllocSpace objects, 0(0B) LOS objects, 13% free, 155MB/179MB, paused 20us,23us total 12.039ms
[        ] W/t.exercise.demo(26920): Throwing OutOfMemoryError "Failed to allocate a 114393596 byte allocation with 25165824 free bytes and 100MB until OOM, target footprint 188276272, growth limit 268435456" (VmSize 20257280 kB)
[        ] I/t.exercise.demo(26920): Starting a blocking GC Alloc
[        ] I/t.exercise.demo(26920): Starting a blocking GC Alloc
[   +4 ms] I/t.exercise.demo(26920): Alloc concurrent copying GC freed 23(47KB) AllocSpace objects, 0(0B) LOS objects, 13% free, 155MB/179MB, paused 20us,21us total 7.589ms
[        ] I/t.exercise.demo(26920): Forcing collection of SoftReferences for 109MB allocation
[        ] I/t.exercise.demo(26920): Starting a blocking GC Alloc
[        ] Connected to _flutterView/0xb4000076c1a98660.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[   +1 ms] A Dart VM Service on SM G990E is available at: http://127.0.0.1:58410/-IfwZMe1kf0=/
[   +1 ms] The Flutter DevTools debugger and profiler on SM G990E is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:58410/-IfwZMe1kf0=/
[   +5 ms] I/t.exercise.demo(26920): Alloc concurrent copying GC freed 33(32KB) AllocSpace objects, 0(0B) LOS objects, 13% free, 155MB/179MB, paused 21us,22us total 11.378ms
[        ] W/t.exercise.demo(26920): Throwing OutOfMemoryError "Failed to allocate a 114393600 byte allocation with 25165824 free bytes and 100MB until OOM, target footprint 188292424, growth limit 268435456" (VmSize 20257280 kB)
[  +44 ms] D/CompatibilityChangeReporter(26920): Compat change id reported: 194532703; UID 10394; state: ENABLED
[  +17 ms] I/TRuntime.CctTransportBackend(26920): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
[  +20 ms] D/TrafficStats(26920): tagSocket(132) with statsTag=0xffffffff, statsUid=-1
[+1985 ms] E/AndroidRuntime(26920): FATAL EXCEPTION: flutter-worker-1
[        ] E/AndroidRuntime(26920): Process: com.deepsport.exercise.demo, PID: 26920
[        ] E/AndroidRuntime(26920): java.lang.OutOfMemoryError: Failed to allocate a 114393600 byte allocation with 25165824 free bytes and 100MB until OOM, target footprint 188292424, growth limit 268435456
[        ] E/AndroidRuntime(26920):     at java.util.Arrays.copyOf(Arrays.java:3670)
[        ] E/AndroidRuntime(26920):     at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
[        ] E/AndroidRuntime(26920):     at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
[        ] E/AndroidRuntime(26920):     at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
[        ] E/AndroidRuntime(26920):     at io.flutter.plugin.common.StandardMessageCodec.writeBytes(StandardMessageCodec.java:196)
[        ] E/AndroidRuntime(26920):     at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:244)
[        ] E/AndroidRuntime(26920):     at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
[        ] E/AndroidRuntime(26920):     at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
[        ] E/AndroidRuntime(26920):     at io.flutter.plugin.common.StandardMessageCodec.encodeMessage(StandardMessageCodec.java:76)
[        ] E/AndroidRuntime(26920):     at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:222)
[        ] E/AndroidRuntime(26920):     at io.flutter.plugins.sharedpreferences.Messages$SharedPreferencesApi$-CC.lambda$setup$7(Messages.java:309)
[        ] E/AndroidRuntime(26920):     at io.flutter.plugins.sharedpreferences.Messages$SharedPreferencesApi$$ExternalSyntheticLambda7.onMessage(Unknown Source:2)
[        ] E/AndroidRuntime(26920):     at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
[        ] E/AndroidRuntime(26920):     at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] E/AndroidRuntime(26920):     at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
[        ] E/AndroidRuntime(26920):     at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] E/AndroidRuntime(26920):     at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
[        ] E/AndroidRuntime(26920):     at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0$io-flutter-embedding-engine-dart-DartMessenger$SerialTaskQueue(DartMessenger.java:163)
[        ] E/AndroidRuntime(26920):     at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue$$ExternalSyntheticLambda1.run(Unknown Source:2)
[        ] E/AndroidRuntime(26920):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[        ] E/AndroidRuntime(26920):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[        ] E/AndroidRuntime(26920):     at java.lang.Thread.run(Thread.java:1012)
[        ] I/TRuntime.CctTransportBackend(26920): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
[        ] D/TrafficStats(26920): tagSocket(140) with statsTag=0xffffffff, statsUid=-1
[  +38 ms] I/Process (26920): Sending signal. PID: 26920 SIG: 9
[  +60 ms] Service protocol connection closed.
[        ] Lost connection to device.
[        ] DevFS: Deleting filesystem on the device (file:///data/user/0/com.deepsport.exercise.demo/code_cache/deepsport_iosHJJGIR/deepsport_ios/)
[ +266 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed

[   +2 ms] "flutter run" took 36.902ms.
[ +196 ms] ensureAnalyticsSent: 191ms
[        ] Running 1 shutdown hook
[   +9 ms] Shutdown hooks complete
[        ] exiting with code 0

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.3, on Microsoft Windows [Version 10.0.19044.2965], locale tr-TR)
    • Flutter version 3.10.3 on channel stable at C:\Users\samed\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (10 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\samed\SDK\android
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = C:\Users\samed\SDK\android
    • Java binary at: C:\Program Files (x86)\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.2)   
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community  
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files (x86)\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 32-bit edition (version 1.79.0)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.66.0

[√] Connected device (4 available)
    • SM G990E (mobile) • 192.168.1.24:37161 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19044.2965]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 114.0.5735.110
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 113.0.1774.57

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
What are you storing in `shared_preferences`? According to the crash message the platform messaging system is trying to send over 100MB of pref data back to Dart.

**Comment by SamedHrmn** [comment]
> 

I store multiple videos as UInt8List as the only thing that can take up much space but I don't read that data when the app starts. Why does just initializing the object cause an out of memory? Shouldn't I see the error during data reading?
Also, is there a memory usage limit within the shared_preference that I don't know?

**Comment by stuartmorgan** [comment]
> I store multiple videos as UInt8List

As the name suggests, `shared_preferences` is meant for preferences; it is absolutely not intended to store large files. It's also noted in the description of the plugin that it is for "simple key-value pairs".

In addition to `shared_preferences` in particular not being a good place to store video files, platform channels are a very poor mechanism for moving large amounts of data between native and Dart, because you are guaranteed to end up with at least two copies of that data in memory (and likely more than two) in order to load it. You will get much better performance from storing video files as files, and just reading those files directly in Dart.

> Why does just initializing the object cause an out of memory?

Because the data is cached when you call `getInstance` (per the docs for that method: "Loads and parses the SharedPreferences for this app from disk.") so that access to values is synchronous.

Closing as out of scope. This is not a supported use case for the plugin, and we cannot prevent OOM when very large amounts of data are stored there.
