### ISSUE TITLE
Missing files or incorrect lines?

### ISSUE THREAD

**Issue by PlanovskyJus** [flutter/flutter#12865]
## Steps to Reproduce

I really don't know how to reproduce this because I have no idea what is happing to cause this in the first place. I have a copied version of a working project. But whenever I have this project to run it messes up and doesn't work. I just get this error.

I have the same project structure on the other one and I have specified all the SDK's needed, but this one just prompts me with this.

## Logs
```
--flutter run
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0.8s
Resolving dependencies...                             1.3s
Running 'gradlew assembleDebug'...                    1.7s
Built build/app/outputs/apk/app-debug.apk (21.3MB).
E/flutter ( 4473): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(189)] WARNING: Could not create offscreen surface. This device or emulator does not support color correct rendering. Fallbacks are in effect. Colors on this device will differ from those displayed on most other devices. This warning will only be logged once.
I/flutter ( 4473): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4473): The following assertion was thrown building _ScrollableScope:
I/flutter ( 4473): 'package:flutter/src/painting/basic_types.dart': Failed assertion: line 216: 'textDirection !=
I/flutter ( 4473): null': is not true.
I/flutter ( 4473): 
I/flutter ( 4473): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4473): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4473): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4473):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4473): 
I/flutter ( 4473): When the exception was thrown, this was the stack:
I/flutter ( 4473): #2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart:216)
I/flutter ( 4473): #3      _getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:23)
I/flutter ( 4473): #4      Viewport.createRenderObject (package:flutter/src/widgets/viewport.dart:131)
I/flutter ( 4473): #5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4165)
I/flutter ( 4473): #6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4634)
I/flutter ( 4473): #7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:176)
I/flutter ( 4473): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter ( 4473): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter ( 4473): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter ( 4473): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter ( 4473): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter ( 4473): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter ( 4473): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter ( 4473): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter ( 4473): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #57     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter ( 4473): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter ( 4473): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter ( 4473): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #89     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3843)
I/flutter ( 4473): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #91     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4638)
I/flutter ( 4473): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter ( 4473): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter ( 4473): #102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4473): #103    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter ( 4473): #104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4473): #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 4473): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 4473): #107    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:809)
I/flutter ( 4473): #108    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:780)
I/flutter ( 4473): #109    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:726)
I/flutter ( 4473): #110    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2231)
I/flutter ( 4473): #111    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:725)
I/flutter ( 4473): #112    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:616)
I/flutter ( 4473): #113    runApp (package:flutter/src/widgets/binding.dart:658)
I/flutter ( 4473): #114    main (file:///Users/justinplanovsky/kics_something/lib/main.dart:6)
I/flutter ( 4473): #115    _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
I/flutter ( 4473): #116    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
I/flutter ( 4473): (elided 2 frames from class _AssertionError)
I/flutter ( 4473): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device Android SDK built for x86...      
I/flutter ( 4473): Another exception was thrown: No Directionality widget found.
I/chatty  ( 4473): uid=10082(com.yourcompany.kics3v2) ui_thread identical 3 lines
I/flutter ( 4473): Another exception was thrown: No Directionality widget found.
I/flutter ( 4473): Another exception was thrown: 'package:flutter/src/painting/alignment.dart': Failed assertion: line 513: 'direction != null': is not true.


--flutter analyze
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' at test/widget_test.dart:15:29 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'MyApp' at test/widget_test.dart:15:33 • undefined_class
  lint • Name non-constant identifiers using lowerCamelCase at lib/main.dart:449:35 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/main.dart:452:36 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/main.dart:479:33 • non_constant_identifier_names
  hint • Unused import at test/widget_test.dart:10:8 • unused_import
6 issues found.
(Ran in 6.6s)
```
## Flutter Doctor

--flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/justinplanovsky/flutter
    • Framework revision e8aa40eddd (2 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /Users/justinplanovsky/Library/Android/sdk
    • Platform android-27, build-tools 27.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.3
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by stefanocoding** [comment]
Did you try deleting the file `test/widget_test.dart`?

**Comment by Hixie** [comment]
It's hard to tell exactly what the problem is without seeing the main.dart source code. Do you have a MaterialApp in your main.dart?

**Comment by PlanovskyJus** [comment]
This was fixed just by creating a new flutter app from the terminal. I originally was working on this when I cloned it from someone else to work on it from them. I had to copy paste a lot of the code into the new flutter project.
