### ISSUE TITLE
Map accessing with passed record generic type crashes on Android

### ISSUE THREAD

**Issue by TabooSun** [flutter/flutter#128758]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

By executing this piece of code:
```dart
final LinkedHashMap<Type, String> map = LinkedHashMap<Type, String>();
void testPrint<T>() {
    print(map[T]);
}

testPrint<
(
  int legCount,
  int headCount,
)>();
```

### Expected results

Return `null` for both Android & iOS.

### Actual results

Throw this on Android:

```console
The method '&' was called on null.
Receiver: null
Tried calling: &(0)

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      _HashBase._hashPattern (dart:collection-patch/compact_hash.dart:186:37)
#2      _LinkedHashMapMixin._getValueOrData (dart:collection-patch/compact_hash.dart:580:39)
#3      _LinkedHashMapMixin.[] (dart:collection-patch/compact_hash.dart:602:13)
```

Return `null` on iOS

### Code sample

<details><summary>Code sample</summary>

```dart
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale zh-Hans-MY)
    • Flutter version 3.10.4 on channel stable at /Users/taboosun/fvm/versions/3.10.4
    ! Warning: `dart` on your path resolves to /Users/taboosun/Development/flutter/bin/cache/dart-sdk/bin/dart, which is not inside your current Flutter SDK checkout at /Users/taboosun/fvm/versions/3.10.4. Consider adding /Users/taboosun/fvm/versions/3.10.4/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (7 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/taboosun/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/taboosun/Library/Android/sdk
    • Java binary at: /Users/taboosun/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/taboosun/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/taboosun/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/taboosun/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/taboosun/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (6 available)
    • SM N986B (mobile)                   • adb-R5CR50H04AH-jJS6jr._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile)         • emulator-5554                                 • android-arm64  • Android 13 (API 33) (emulator)
    • 神的iPhone 14 Pro Max (mobile)        • 00008120-000E69D00E90C01E                     • ios            • iOS 16.5 20F66
    • iPhone SE (3rd generation) (mobile) • 4D7FC90E-3286-4272-B9D2-F4E3118FBAE5          • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                     • macos                                         • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                        • chrome                                        • web-javascript • Google Chrome 114.0.5735.106
    ! Error: (null) needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by dam-ease** [comment]
Hi @TabooSun. 
Looking at this issue, it seems the issue is best suited to report in dart-lang/sdk [repo](https://github.com/dart-lang/sdk). Kindly report the issue in the designated repo. Thank you.
