### ISSUE TITLE
java.util.concurrent.RejectedExecutionException: 

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [flutter/flutter#128945]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

java.util.concurrent.RejectedExecutionException: 

I use image picker inside of Bloc

### Expected results

no issue

### Actual results

```
Uncaught exception thrown by finalizer
E/System  (20675): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda2@b067cfb rejected from java.util.concurrent.ThreadPoolExecutor@f9e118[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 9]
E/System  (20675): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/System  (20675): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/System  (20675): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/System  (20675): 	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
E/System  (20675): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (20675): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:588)
E/System  (20675): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:879)
E/System  (20675): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
E/System  (20675): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
E/System  (20675): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
E/System  (20675): 	at java.lang.Thread.run(Thread.java:920)
``` 

### Code sample

```dart
try {
      final xFile = await ImagePicker().pickImage(
        source: ImageSource.camera,
      );

      if (xFile == null) {
        return emit(state.copyWith(status: PhotoManagerStatus.close));
      }

      final pickedFileBodyBytes = await xFile.readAsBytes();
      final List<Uint8List> chosenImages = List<Uint8List>.from(state.chosenImages)
        ..add(pickedFileBodyBytes);
      final List<String> chosenImagesPath = List<String>.from(state.chosenImagesPath)
        ..add(xFile.path);


      emit(state.copyWith(
        status: PhotoManagerStatus.pictureTaken,
        chosenImages: chosenImages,
        chosenImagesPath: chosenImagesPath,
      ));
    }
``` 

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @Soliardi-Chyngyz. 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you
