### ISSUE TITLE
Flutter VSC cant run on ios 17 | Xcode 15

### ISSUE THREAD

**Issue by manuel75o** [flutter/flutter#129193]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create new Flutter Application
2. Open in Xcode 15 and change Bundle Identifier for Runner and RunnerTests
3. Run in Xcode 15 -> Build Succeeds -> Install on iPhone Succeeds -> Run on iPhone Succeeds
or
5. Run Flutter Application in VSC with "flutter run" or press execute
6. Build Succeeds -> Install on iPhone Succeeds -> Error:

    Could not run build/ios/iphoneos/Runner.app on 00008020-00186DCE0A33002E.
    Try launching Xcode and selecting "Product > Run" to fix the problem:
      open ios/Runner.xcworkspace

### Expected results

The Flutter App runs perfectly fine when Compiling in Xcode 15.

The Flutter App does not run via VSC.

### Actual results

I ran "flutter run --verbose" and the output before the crash is shown below:
Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably
means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!

Funny thing is that the Device Support File for iOS 17 is not even in the folder.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

</details>


### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably
means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!

<img width="592" alt="image" src="https://github.com/flutter/flutter/assets/67610849/89bce8e1-6fea-4b82-8f47-65195124c3ef">

</details>


### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
2023-06-20 19:08:18.238 ios-deploy[21379:195653] [ !! ] Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably
means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
[        ] Script started, output file is /dev/null
[        ] Script done, output file is /dev/null
[        ] ios-deploy exited with code 0
[   +1 ms] Could not run build/ios/iphoneos/Runner.app on 00008020-00186DCE0A33002E.
[        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Installing and launching... (completed in 10,7s)
[        ] Error launching application on iPhone von Manuel.
[        ] "flutter run" took 24 208ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +173 ms] ensureAnalyticsSent: 171ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1
</details>


### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale de-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
</details>

**Comment by manuel75o** [comment]
A working workaround is:
https://github.com/flutter/flutter/issues/128531#issuecomment-1587984546

**Comment by darshankawar** [comment]
Thanks for the report.
Currently we are unable to replicate this due to lack of latest config (Xcode 15 and iOS 17), but based on the report, adding applicable labels for team's attention.

Below is the list of issues related to Flutter, Xcode 15 and iOS 17 for reference:

https://github.com/orgs/flutter/projects/87/views/1

/cc @vashworth

**Comment by leighajarett** [comment]
Is this a duplicate? https://github.com/flutter/flutter/issues/128531

@vashworth?

**Comment by stuartmorgan** [comment]
Yes, this is the same issue. Closing as a duplicate.
