### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by raceburg** [flutter/flutter#129124]
## Command
```
flutter pub add path_provider
```

## Logs
FileSystemException: Cannot create link, OS Error: Operation not permitted, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:355:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.5, on Ubuntu 22.04.2 LTS 5.15.0-75-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.10.5 on channel stable at /home/st/snap/flutter/common/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 796c8ef792 (6 days ago), 2023-06-13 15:51:02 -0700
    [32m•[39m Engine revision 45f6e00911
    [32m•[39m Dart version 3.0.5
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /home/st/Android/Sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m ANDROID_SDK_ROOT = /home/st/Android/Sdk
    [32m•[39m Java binary at: /home/st/Android/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 10.0.0-4ubuntu1
    [32m•[39m cmake version 3.16.3
    [32m•[39m ninja version 1.10.0
    [32m•[39m pkg-config version 0.29.1

[32m[✓][39m Android Studio (version 4.1)
    [32m•[39m Android Studio at /home/st/work/mdevelop/android-studio
    [32m•[39m Flutter plugin version 57.0.1
    [32m•[39m Dart plugin version 201.9380
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /home/st/Android/android-studio
    [32m•[39m Flutter plugin version 73.0.2
    [32m•[39m Dart plugin version 222.4560
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code
    [32m•[39m VS Code at /snap/code/current
    [32m•[39m Flutter extension version 3.66.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m M2101K7BNY (mobile) • QC9HJRTK6PEU55PV • android-arm64  • Android 13 (API 33)
    [32m•[39m Linux (desktop)     • linux            • linux-x64      • Ubuntu 22.04.2 LTS 5.15.0-75-generic
    [32m•[39m Chrome (web)        • chrome           • web-javascript • Google Chrome 98.0.4758.102

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9cd3d0d9ff05768afa249e036acc66e8abe93bff
### Plugins
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7

**Comment by raceburg** [comment]
Hi @dam-ease. The project was on an external disk with the file system exfat. I moved the project to my linux home directory and the problem disappeared. Probably, i have problems with the disk. I'm sorry, i didn't see it myself.
Thanks for your reply.
