### ISSUE TITLE
[camera] Integration test flake on Android

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#129223]
I've been seeing more flake from `camera` recently; not always the same thing, so I'm not sure if it's due to a specific test. https://firebase.corp.google.com/project/flutter-cirrus/testlab/histories/bh.a4615392b31c422b/matrices/7812188579420293815/executions/bs.70622e6cb42fe131/logs is a recent example crash, but I've also seen timeouts.

This isn't very actionable yet, but I've seen camera specifically enough recently that there's clearly something going on that we'll need to gather data on and investigate.

**Comment by stuartmorgan** [comment]
Two more failures were crashes, both the same, and both on the 26 device. It may be only that one, so we should keep an eye out for failures on the other config.

```
java.lang.RuntimeException: native_reset failed.
     FATAL EXCEPTION: CameraBackground
Process: io.flutter.plugins.cameraexample, PID: 15185
java.lang.RuntimeException: native_reset failed.
	at android.media.MediaRecorder.native_reset(Native Method)
	at android.media.MediaRecorder.reset(MediaRecorder.java:1344)
	at io.flutter.plugins.camera.Camera.close(Camera.java:1233)
	at io.flutter.plugins.camera.Camera$1.onOpened(Camera.java:338)
	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:139)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

Could be a real bug in our `close` handling?

**Comment by camsim99** [comment]
I have to suspect this is an issue with the camera on a particular device, but I'm not sure of a good way to confirm. The error seems to be coming from [this sort of call](https://android.googlesource.com/platform/frameworks/base/+/android-4.2.2_r1.2/media/jni/android_media_MediaRecorder.cpp#366) that comes from calling `mediaRecorder.reset()` in our `close()` method, and [the docs](https://developer.android.com/reference/android/media/MediaRecorder#reset()) don't mention any potential issues with this besides needing to reconfigure the `mediaRecorder` if we need it again.

I'll dig a bit deeper into the test to see if there's potentially anything weird we are doing in the test with managing the `mediaRecorder`.

**Comment by camsim99** [comment]
On the `native_reset` issue: When `onOpened` gets called when the camera finishes opening, we start a preview. Starting a preview may fail with an `InterruptedException` or a `CameraAccessException`, and in case of error, we call `mediaRecorder.reset()` from our `close()` method ([source](https://github.com/flutter/packages/blob/main/packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/Camera.java#L339) of all this). I'm wondering if this is causing a conflict of some kind, but I think it will be hard for me to dig deeper without a repro.

If we see more repros, we should note here the actual error that is logged `E/Camera: open | onOpened error: ...`, so we can track down the cause.

**Comment by stuartmorgan** [comment]
I just saw several rounds of this in a flutter->packages roll; same `java.lang.RuntimeException: native_reset failed` crash
