### ISSUE TITLE
[in-app-purchase][Android] Issue on Android API 34 when no billing provider is available

### ISSUE THREAD

**Issue by Mihai-B** [flutter/flutter#129285]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add the library
2. Use an emulator without billing support and android API version 34
3.  Call code
```
final iapConnection = IAPConnection.instance;
await iapConnection.isAvailable();
```

### Expected results

I should get a true or false if the billing is supported or not

### Actual results

I get a huge stacktrace

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

-

</details>

### Logs

<details><summary>Logs</summary>

```console
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): Failed to handle method call
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): java.lang.SecurityException: ro.madcodestudios.ticket.box: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Parcel.createException(Parcel.java:3041)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Parcel.readException(Parcel.java:3024)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Parcel.readException(Parcel.java:2966)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5668)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at com.android.billingclient.api.zzn.zzc(com.android.billingclient:billing@@5.2.0:1)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at com.android.billingclient.api.zzo.zze(com.android.billingclient:billing@@5.2.0:3)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at com.android.billingclient.api.BillingClientImpl.startConnection(com.android.billingclient:billing@@5.2.0:36)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.startConnection(MethodCallHandlerImpl.java:400)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:140)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13895)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2563)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2708)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Binder.execTransactInternal(Binder.java:1339)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236): 	at android.os.Binder.execTransact(Binder.java:1275)
E/MethodChannel#plugins.flutter.io/in_app_purchase( 5236):
E/flutter ( 5236): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, ro.madcodestudios.ticket.box: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, java.lang.SecurityException: ro.madcodestudios.ticket.box: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/flutter ( 5236): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/flutter ( 5236): 	at android.os.Parcel.createException(Parcel.java:3041)
E/flutter ( 5236): 	at android.os.Parcel.readException(Parcel.java:3024)
E/flutter ( 5236): 	at android.os.Parcel.readException(Parcel.java:2966)
E/flutter ( 5236): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5668)
E/flutter ( 5236): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
E/flutter ( 5236): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
E/flutter ( 5236): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
E/flutter ( 5236): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
E/flutter ( 5236): 	at com.android.billingclient.api.zzn.zzc(com.android.billingclient:billing@@5.2.0:1)
E/flutter ( 5236): 	at com.android.billingclient.api.zzo.zze(com.android.billingclient:billing@@5.2.0:3)
E/flutter ( 5236): 	at com.android.billingclient.api.BillingClientImpl.startConnection(com.android.billingclient:billing@@5.2.0:36)
E/flutter ( 5236): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.startConnection(MethodCallHandlerImpl.java:400)
E/flutter ( 5236): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:140)
E/flutter ( 5236): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 5236): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 5236): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 5236): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 5236): 	at android.os.Handler.handleCallback(Handler.java:958)
E/flutter ( 5236): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 5236): 	at android.os.Looper.loopOnce(Looper.java:205)
E/flutter ( 5236): 	at android.os.Looper.loop(Looper.java:294)
E/flutter ( 5236): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
E/flutter ( 5236): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5236): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/flutter ( 5236): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter ( 5236): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter ( 5236): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13895)
E/flutter ( 5236): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2563)
E/flutter ( 5236): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2708)
E/flutter ( 5236): 	at android.os.Binder.execTransactInternal(Binder.java:1339)
E/flutter ( 5236): 	at android.os.Binder.execTransact(Binder.java:1275)
E/flutter ( 5236):
E/flutter ( 5236): )

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.10.5, on Manjaro Linux 6.3.5-2-MANJARO, locale en_US.UTF-8)
```

</details>

**Comment by dam-ease** [comment]
Hi @Mihai-B 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you
