### ISSUE TITLE
CameraException(error, Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.abortCaptures()' on a null object reference)

### ISSUE THREAD

**Issue by ketanphpdots** [flutter/flutter#129267]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Stop Recording is not working in Android 33 and Above version

Getting CameraException(error, Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.abortCaptures()' on a null object reference)

### Expected results

It should return the path where the video is saved

### Actual results

CameraException(error, Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.abortCaptures()' on a null object reference)

### Code sample

```
Future<void> stopRecording() async {
    if (cameraController!.value.isRecordingVideo) {
      await cameraController!.stopVideoRecording().then((file) {
        
      }).onError((error, stackTrace) {
        // Here getting error: CameraException(error, Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.abortCaptures()' on a null object reference)
    }
  }
```

### Logs

/MethodChannel#plugins.flutter.io/camera_android(15093): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera_android(15093): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.abortCaptures()' on a null object reference
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at io.flutter.plugins.camera.Camera.stopVideoRecording(Camera.java:791)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:129)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at android.app.ActivityThread.main(ActivityThread.java:7892)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android(15093): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.4 22F63 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by dam-ease** [comment]
Hi @ketanphpdots. Thanks for filing this issue. Can you upgrade to the latest stable flutter version and latest version of the package to confirm this issue still persists?
