### ISSUE TITLE
crash when scrolling in AnimatedList

### ISSUE THREAD

**Issue by hreinhardt** [flutter/flutter#12922]
Consider the following program:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class MessageList extends StatefulWidget {
    @override
    MessageListState createState() => new MessageListState();
}

class MessageListState extends State<MessageList> {
    final GlobalKey<AnimatedListState> animatedList = new GlobalKey<AnimatedListState>();

    void onLoadMore() {
        for(int i=0; i<150; i++) {
            animatedList.currentState?.insertItem(0, duration: new Duration(seconds: 8));
        }
    }

    Widget mkRow(BuildContext context, int index, Animation<double> anim) {
        if(index == 0) {
            return new RaisedButton(child: new Text("load"), onPressed: onLoadMore);
        }
        return new SizeTransition(
            sizeFactor: anim,
            child: new Text(index.toString())
        );
    }

    @override
    build(BuildContext context) {
         return new AnimatedList(
             key: animatedList,
             padding: new EdgeInsets.all(4.0), // removing this line prevents the crashing
             itemBuilder: mkRow,
             initialItemCount: 10
         );
    }
}
```

If I run it, press the 'load' button and then quickly scroll up and down (while the animation is running), I can reliaby produce this error:

```
I/flutter ( 2844): Observatory listening on http://127.0.0.1:55444/
I/flutter ( 2844): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2844): The following assertion was thrown building SizeTransition(animation: AnimationController#53d0f(▶
I/flutter ( 2844): 0.208), state: _AnimatedState#74bf9):
I/flutter ( 2844): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1325 pos 14:
I/flutter ( 2844): '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.
I/flutter ( 2844):
I/flutter ( 2844): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 2844): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 2844): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 2844):   https://github.com/flutter/flutter/issues/new
I/flutter ( 2844):
I/flutter ( 2844): When the exception was thrown, this was the stack:
I/flutter ( 2844): #2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1325:14)
I/flutter ( 2844): #3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:1778:26)
I/flutter ( 2844): #4      RenderPositionedBox.heightFactor= (package:flutter/src/rendering/shifted_box.dart:364:5)
I/flutter ( 2844): #5      Align.updateRenderObject (package:flutter/src/widgets/basic.dart:1250:9)
I/flutter ( 2844): #6      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4199:12)
I/flutter ( 2844): #7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4565:17)
I/flutter ( 2844): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 2844): #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4567:14)
I/flutter ( 2844): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 2844): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter ( 2844): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter ( 2844): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2260:33)
I/flutter ( 2844): #14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:20)
I/flutter ( 2844): #15     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:200:5)
I/flutter ( 2844): #16     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713:15)
I/flutter ( 2844): #17     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649:9)
I/flutter ( 2844): #18     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:101)
I/flutter ( 2844): #19     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:90)
I/flutter ( 2844): (elided 2 frames from class _AssertionError)
I/flutter ( 2844): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 2844): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1325 pos 14: '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.
I/flutter ( 2844): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1325 pos 14: '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.

```
Interestingly, the crash disappears if I remove the padding from the AnimatedList.

I tried both the "master" and the "alpha" branch of Flutter and they give the same error.

**Comment by hreinhardt** [comment]
I cannot reproduce this using the latest master-branch, so I guess it is fixed.
