### ISSUE TITLE
scale.dart assertion

### ISSUE THREAD

**Issue by giftofhealth** [flutter/flutter#129376]
```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
'package:flutter/src/gestures/scale.dart': Failed assertion: line 770 pos 16: 'false': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      ScaleGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/scale.dart:770:16)
#3      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:465:9)
#4      ScaleGestureRecognizer.rejectGesture (package:flutter/src/gestures/scale.dart:757:5)
#5      GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:278:24)
#6      GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:239:9)
#7      GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53:12)
#8      DoubleTapGestureRecognizer._registerSecondTap (package:flutter/src/gestures/multitap.dart:338:19)
#9      DoubleTapGestureRecognizer._handleEvent (package:flutter/src/gestures/multitap.dart:258:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:465:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:445:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:331:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
#22     _invoke1 (dart:ui/hooks.dart:158:13)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)

router: Instance of 'PointerRouter'
route: Closure: (PointerEvent) => void from Function '_handleEvent@1222391311':.
event: _TransformedPointerUpEvent#7ea67(position: Offset(171.3, 546.3))
════════════════════════════════════════════════════════════════════════════════════════════════════
```

I hit this assertion when attempting to gesture and scale the font size in an app I'm writing.

**Comment by huycozy** [comment]
Hi @giftofhealth 
Please provide the information indicated below so that we may verify the issue properly:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps
- Target platform (Android/iOS/Web/MacOS/Windows/Linux)

Thank you!
