### ISSUE TITLE
FMDB - DYLD 1 Library missing

### ISSUE THREAD

**Issue by mtical** [flutter/flutter#129311]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open iOS simulator
2. `flutter run -v`

### Expected results

A running app.

### Actual results

App downloads to simulator but fails when opened.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:english_words/english_words.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (context) => MyAppState(),
      child: MaterialApp(
        title: 'Namer App',
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepOrange),
        ),
        home: MyHomePage(),
      ),
    );
  }
}

class MyAppState extends ChangeNotifier {
  var current = WordPair.random();
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var appState = context.watch<MyAppState>();

    return Scaffold(
      body: Column(
        children: [
          Text('A random idea:'),
          Text(appState.current.asLowerCase),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console

Apple error:

Incident Identifier: 42FB915B-B02C-423A-9FE8-2DDCED9CCF5A
CrashReporter Key:   D977D340-0F7D-5784-DE58-B5DE482BD1B7
Hardware Model:      MacBookPro16,1
Version:             2.0.1 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [49203]
Coalition:           com.apple.CoreSimulator.SimDevice.90C4BB35-9004-441D-978B-5F9C685E2396 [79457]
Responsible Process: SimulatorTrampoline [50365]

Date/Time:           2023-06-21 13:39:05.8885 -0700
Launch Time:         2023-06-21 13:39:05.8565 -0700
OS Version:          macOS 13.1 (22C65)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/FMDB.framework/FMDB
Referenced from: <B37F3B5B-39AF-32B3-9FC7-E9DCD38CC72B> /Users/USER/Library/Developer/CoreSimulator/Devices/90C4BB35-9004-441D-978B-5F9C685E2396/data/Containers/Bundle/Application/96804B53-3482-4F15-B476-5E7351C2695B/BALLN.app/BALLN
Reason: tried: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FMDB.framework/FMDB' (no such file), '/usr/lib/swift/FMDB.framework/FMDB' (no such file, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FMDB.framework/FMDB' (no such file), '/usr/lib/swift/FMDB.framework/FMDB' (no such file, not in dyld cache), '/Users/matt/Library/Developer/CoreSimulator/Devices/90C4BB35-9004-441D-978B-5F9C685E2396/data/Containers/Bundle/Application/96804B53-3482-4F1
(terminated at launch; ignore backtrace)
```
```
flutter run error:

[ +377 ms] An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
                    Simulator device returned an error for the requested operation.
                    The request was denied by service delegate (SBMainWorkspace).
                    Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
                        The request to open "com.balln" failed.
                        The request was denied by service delegate (SBMainWorkspace).
[   +5 ms] Exception: Unable to launch com.balln on 90C4BB35-9004-441D-978B-5F9C685E2396:
           ProcessException: Process exited abnormally:
           An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
           Simulator device returned an error for the requested operation.
           The request was denied by service delegate (SBMainWorkspace).
           Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
                The request to open "com.balln" failed.
                The request was denied by service delegate (SBMainWorkspace).
             Command: xcrun simctl launch 90C4BB35-9004-441D-978B-5F9C685E2396 com.balln --enable-dart-profiling --enable-checked-mode --verify-entry-points
[   +2 ms] Error launching application on iPhone 14 Pro Max.
[   +4 ms] "flutter run" took 583,472ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +91 ms] ensureAnalyticsSent: 84ms
[        ] Running 1 shutdown hook
[   +5 ms] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.1 22C65 darwin-x64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/matt/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.3739.24

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 90C4BB35-9004-441D-978B-5F9C685E2396 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @mtical 
Although I am not on latest iOS simulator as you are, tried running the code sample which built the app properly on simulator 15.3.

As for the error log, it seems to be happening and pointing to FMDB library `Library not loaded: @rpath/FMDB.framework/FMDB`

Can you try the solution mentioned [here](https://github.com/flutter/flutter/issues/115053#issuecomment-1340161984) and see if it helps in your case ?
