### ISSUE TITLE
Cannot receive errors from EventChannel

### ISSUE THREAD

**Issue by robryk** [flutter/flutter#12935]
## Steps to Reproduce

1. Modify the `platform_channel` example so that:
a) the charging state channel always sends back an error.
b) `_onError` sets the text to "Battery status: error."
2. Do `flutter run`.

Observed behaviour: 
1. The battery status text says "Battery status: error."
2. `flutter run` prints the following error:
```
I/flutter ( 4038): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter ( 4038): The following PlatformException was thrown during a platform message callback:
I/flutter ( 4038): PlatformException(UNAVAILABLE, Charging status unavailable, null)
I/flutter ( 4038): 
I/flutter ( 4038): When the exception was thrown, this was the stack:
I/flutter ( 4038): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514)
I/flutter ( 4038): #1      EventChannel.receiveBroadcastStream.<anonymous closure>.<anonymous closure> (package:flutter/src/services/platform_channel.dart:285)
I/flutter ( 4038): <asynchronous suspension>
I/flutter ( 4038): #2      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67)
I/flutter ( 4038): <asynchronous suspension>
I/flutter ( 4038): #3      _invoke3 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:133)
I/flutter ( 4038): #4      _dispatchPlatformMessage (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:47)
I/flutter ( 4038): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Expected behaviour:
1. _onError runs and changes the battery state label to mention "error".
2. There is no uncaught exception

It appears that `receiveBroadcastStream` doesn't handle `PlatformException`s thrown from `codec.decodeEnvelope`, which should rather be caught and passed to `StreamController`'s `addError`.

## Logs

```
[robryk@sharya-rana platform_channel]$ flutter run
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (21.3MB).
Installing build/app/outputs/apk/app.apk...
Syncing files to device Nexus 5X...
I/vndksupport( 4038): sphal namespace is not configured for this process. Loading /vendor/lib/hw/gralloc.msm8992.so from the current namespace instead.
I/flutter ( 4038): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter ( 4038): The following PlatformException was thrown during a platform message callback:
I/flutter ( 4038): PlatformException(UNAVAILABLE, Charging status unavailable, null)
I/flutter ( 4038): 
I/flutter ( 4038): When the exception was thrown, this was the stack:
I/flutter ( 4038): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514)
I/flutter ( 4038): #1      EventChannel.receiveBroadcastStream.<anonymous closure>.<anonymous closure> (package:flutter/src/services/platform_channel.dart:285)
I/flutter ( 4038): <asynchronous suspension>
I/flutter ( 4038): #2      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67)
I/flutter ( 4038): <asynchronous suspension>
I/flutter ( 4038): #3      _invoke3 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:133)
I/flutter ( 4038): #4      _dispatchPlatformMessage (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:47)
I/flutter ( 4038): ════════════════════════════════════════════════════════════════════════════════════════════════════

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Nexus 5X is available at: http://127.0.0.1:8106/
For a more detailed help message, press "h". To quit, press "q".
I/flutter ( 4038): Another exception was thrown: PlatformException(UNAVAILABLE, Charging status unavailable, null)
Application finished.
```

```
[robryk@sharya-rana platform_channel]$ flutter analyze
Analyzing 1263 files...
[warning] The method 'encodePng' isn't defined for the class 'Upload'. (/home/robryk/flutter/dev/devicelab/lib/tasks/save_catalog_screenshots.dart, line 83, col 20)
[warning] The method 'decodePng' isn't defined for the class 'Upload'. (/home/robryk/flutter/dev/devicelab/lib/tasks/save_catalog_screenshots.dart, line 83, col 41)
[warning] The method 'copyResize' isn't defined for the class 'Upload'. (/home/robryk/flutter/dev/devicelab/lib/tasks/save_catalog_screenshots.dart, line 83, col 30)
[error] Target of URI doesn't exist: 'package:image/image.dart'. (/home/robryk/flutter/dev/devicelab/lib/tasks/save_catalog_screenshots.dart, line 10, col 8)
[error] Target of URI doesn't exist: 'package:url_launcher/url_launcher.dart'. (/home/robryk/flutter/examples/flutter_gallery/lib/gallery/updates.dart, line 10, col 8)
[warning] The method 'launch' isn't defined for the class 'UpdaterState'. (/home/robryk/flutter/examples/flutter_gallery/lib/gallery/updates.dart, line 46, col 9)
[warning] The method 'launch' isn't defined for the class 'GalleryDrawer'. (/home/robryk/flutter/examples/flutter_gallery/lib/gallery/drawer.dart, line 224, col 9)
[error] Target of URI doesn't exist: 'package:url_launcher/url_launcher.dart'. (/home/robryk/flutter/examples/flutter_gallery/lib/gallery/drawer.dart, line 11, col 8)
[warning] The method 'launch' isn't defined for the class 'LinkTextSpan'. (/home/robryk/flutter/examples/flutter_gallery/lib/gallery/drawer.dart, line 32, col 7)
[lint] 20 public members lack documentation (ran in 70.0s)
```

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_GB.UTF-8, channel alpha)
    • Flutter at /home/robryk/flutter
    • Framework revision e8aa40eddd (3 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Android Studio (version 2.2)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Connected devices
    • Nexus 5X • 00cc66b83650b5a5 • android-arm • Android 8.0.0 (API 26)

```

**Comment by eseidelGoogle** [comment]
@mravn-google would know.

**Comment by mravn-google** [comment]
@robryk Thanks for reporting, this is indeed an oversight.

**Comment by janardhanmupparaju** [comment]
I am trying to develop web application with geolocation and webcam using flutter but getting this error. any one can you please help me

The following StateError was thrown during a platform message response callback:

Bad state: Future already completed



When the exception was thrown, this was the stack:

dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 195:49  throw_

dart-sdk/lib/async/future_impl.dart 42:79                                     complete

packages/flutter/src/services/binding.dart 176:18                             <fn>

dart-sdk/lib/async/zone.dart 1374:10                                          runUnaryGuarded

lib/_engine/engine/window.dart 331:23                                         <fn>

lib/_engine/engine/window.dart 488:17                                         <fn>

dart-sdk/lib/async/zone.dart 1439:54                                          runUnary

dart-sdk/lib/async/future_impl.dart 141:18                                    handleValue

dart-sdk/lib/async/future_impl.dart 682:44                                    handleValueCallback

dart-sdk/lib/async/future_impl.dart 711:32
_propagateToListeners

dart-sdk/lib/async/future_impl.dart 516:7                                     [_complete]

dart-sdk/lib/async/future.dart 315:15                                         <fn>

dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 50:19       internalCallback

═════════════════════════════════════════════════════════════════════════════════════════════════
═══
