### ISSUE TITLE
Exception caught by gesture when using scroll notification

### ISSUE THREAD

**Issue by rocksolid911** [flutter/flutter#129425]
```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:243:14)
#3      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#4      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3170:18)
#5      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#6      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#9      Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4534:24)
#10     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#11     DragScrollActivity.dispatchOverscrollNotification (package:flutter/src/widgets/scroll_activity.dart:474:135)
#12     ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:931:15)
#13     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:285:9)
#14     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:78:18)
#15     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:122:5)
#16     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
#17     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:719:12)
#18     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:483:55)
#19     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#20     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:483:7)
#21     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:330:9)
#22     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#23     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#24     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#25     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#26     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#27     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
#28     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#29     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
#30     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#31     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#32     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#33     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#34     _invoke1 (dart:ui/hooks.dart:164:13)
#35     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#36     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
Handler: "onUpdate"
Recognizer: HorizontalDragGestureRecognizer#a24b1
  start behavior: start
====================================================================================================
'''
 '''
```

**Comment by darshankawar** [comment]
@rocksolid911 
Can you run your scenario again on latest master and see if you still get the same exception or not ?
See https://github.com/flutter/flutter/issues/124551 for reference.

`flutter channel master`
`flutter upgrade`
