### ISSUE TITLE
Assertion error in painting.dart while redirecting to home page

### ISSUE THREAD

**Issue by linkanyadav** [flutter/flutter#129438]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Launch the application.
2. Wait for the splash screen to appear.
3. Observe the splash screen with the blue background and account icon.
4. After 2 seconds, the app should automatically navigate to the login page.
5. On the login page, enter a valid username and password.
6. Tap on the "Login" button.
7. The app should attempt to authenticate the user.
8. Observe that instead of redirecting to the home page, an assertion error is thrown and this is error 
![Screenshot (17)](https://github.com/flutter/flutter/assets/137530986/f1050fa5-14ba-44ac-84d8-af43dd37e46b)
_AssertionError ('dart:ui/painting.dart': Failed assertion: line 184 pos 12: '<optimized out>': is not true.)

### Expected results

I expect when i click login button then should open my home page

### Actual results

1. Launch the application.
2. Wait for the splash screen to appear.
3. Observe the splash screen with the blue background and account icon.
4. After 2 seconds, the app should automatically navigate to the login page.
5. On the login page, enter a valid username and password.
6. Tap on the "Login" button.
7. The app should attempt to authenticate the user.
8. Observe that instead of redirecting to the home page, an assertion error is thrown and this is error 
![Screenshot (17)](https://github.com/flutter/flutter/assets/137530986/f1050fa5-14ba-44ac-84d8-af43dd37e46b)
_AssertionError ('dart:ui/painting.dart': Failed assertion: line 184 pos 12: '<optimized out>': is not true.)
![Screenshot (18)](https://github.com/flutter/flutter/assets/137530986/b8ba6639-f292-4744-97de-fb3fc8e886c4)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'login_page.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(),
      home: SplashPage(),
    );
  }
}

class SplashPage extends StatefulWidget {
  const SplashPage({Key? key}) : super(key: key);

  @override
  State<SplashPage> createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    Timer(
      Duration(seconds: 2),
      () {
        Navigator.pushReplacement(
            context,
            MaterialPageRoute(
              builder: (context) => LoginPage(),
            ));
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.blue,
        child: Center(
          child: Icon(
            Icons.account_circle,
            color: Colors.white,
            size: 50,
          ),
        ),
      ),
    );
  }
}
]

`import 'package:animated_container/home_page.dart';
import 'package:flutter/material.dart';

class LoginPage extends StatelessWidget {
  final TextEditingController uNameController = TextEditingController();
  final TextEditingController passController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Login'),
      ),
      body: Container(
        padding: EdgeInsets.all(20.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Icon(
              Icons.account_circle,
              color: Colors.blue,
              size: 70.0,
            ),
            SizedBox(height: 20.0),
            TextField(
              controller: uNameController,
              decoration: InputDecoration(
                prefixIcon: Icon(Icons.account_circle_outlined),
                labelText: 'Username',
                contentPadding: EdgeInsets.symmetric(
                  vertical: 12.0,
                  horizontal: 16.0,
                ),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(10.0),
                  borderSide: BorderSide(color: Colors.blue),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(10.0),
                  borderSide: BorderSide(color: Colors.blue),
                ),
              ),
            ),
            SizedBox(height: 20.0),
            TextField(
              controller: passController,
              decoration: InputDecoration(
                prefixIcon: Icon(Icons.lock),
                labelText: 'Password',
                contentPadding: EdgeInsets.symmetric(
                  vertical: 12.0,
                  horizontal: 12.0,
                ),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(10.0),
                  borderSide: BorderSide(color: Colors.blue),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(10.0),
                  borderSide: BorderSide(color: Colors.blue),
                ),
              ),
              // obscureText: true,
            ),
            SizedBox(height: 20.0),
            ElevatedButton(
              onPressed: () {
                Navigator.pushReplacement(
                  context,
                  MaterialPageRoute(builder: (context) => HomePage()),
                );
              },
              child: Text('Login'),
            ),
          ],
        ),
      ),
    );
  }
}
`

`import 'package:flutter/material.dart';


class HomePage extends StatelessWidget{
  @override
  Widget build(BuildContext context){
    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text('Home')),
      ),

      body:Container(
        color: Colors.blue.shade100,
        child: Center(
          child: Icon(Icons.home, color: Colors.white.withOpacity(8),),
        ),
      ),


    );
  }
}`
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app-debug.apk...
Debug service listening on ws://127.0.0.1:62034/J1ccG9PBW2M=/ws
Syncing files to device sdk gphone64 x86 64...
W/Parcel  (12439): Expecting binder but got null!
D/EGL_emulation(12439): app_time_stats: avg=897.26ms min=3.36ms max=1791.17ms count=2
D/EGL_emulation(12439): app_time_stats: avg=467.25ms min=4.11ms max=1704.11ms count=4

======== Exception caught by widgets library =======================================================
The following assertion was thrown building HomePage(dirty):
'dart:ui/painting.dart': Failed assertion: line 184 pos 12: '<optimized out>': is not true.

The relevant error-causing widget was: 
  HomePage HomePage:file:///C:/Users/linka/Desktop/Flutter%20Projects/login/lib/login_page.dart:70:59
When the exception was thrown, this was the stack: 
#2      Color.withOpacity (dart:ui/painting.dart:184:12)
#3      HomePage.build (package:login/home_page.dart:15:33)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5156:49)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (220 frames)
#228    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#229    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#230    Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#231    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6153:32)
#232    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595:17)
#233    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#235    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#236    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#237    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#238    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#239    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#241    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#242    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#243    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#244    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#245    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#246    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#247    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#248    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#249    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#250    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#251    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#252    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#253    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#254    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#255    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#256    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#258    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#259    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#260    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#261    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#262    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#263    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#264    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#265    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#266    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#267    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#268    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#269    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#270    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#271    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#272    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#273    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#274    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#275    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#276    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#277    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#278    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#279    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#280    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#281    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#282    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#283    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#284    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#285    _invoke (dart:ui/hooks.dart:142:13)
#286    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#287    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-IN)
    • Flutter version 3.10.5 on channel stable at C:\Users\linka\Desktop\flutter_windows_3.7.12-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (10 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\linka\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.79.2)
    • VS Code at C:\Users\linka\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 114.0.1823.43

[√] Network resources
    • All expected network resources are available.

• No issues found!]
```

</details>

**Comment by linkanyadav** [comment]
Please Resolve this error as soon as possible if any issue with my repot or I'm doing any fault just tell me.
