### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by imshobhitbajpai** [flutter/flutter#129481]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
Just run the above command

## Logs
FormatException
```
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
#3      _Uri._uriDecode (dart:core/uri.dart:3078:21)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#6      new List.from (dart:core-patch/array_patch.dart:37:17)
#7      new List.unmodifiable (dart:core-patch/array_patch.dart:67:24)
#8      _Uri._computePathSegments (dart:core/uri.dart:2029:11)
#9      _Uri.pathSegments (dart:core/uri.dart:1554:42)
#10     _Uri.pathSegments (dart:core/uri.dart)
#11     ManifestAssetBundle._createAssetManifestBinary.parseScale (package:flutter_tools/src/asset.dart:693:20)
#12     ManifestAssetBundle._createAssetManifestBinary (package:flutter_tools/src/asset.dart:712:49)
#13     ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:441:50)
<asynchronous suspension>
#14     ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:502:26)
<asynchronous suspension>
#15     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:308:41)
<asynchronous suspension>
#16     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19044.2965], locale en-IN)
    [32m•[39m Flutter version 3.10.5 on channel stable at C:\Users\SHOBHIT\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 796c8ef792 (10 days ago), 2023-06-13 15:51:02 -0700
    [32m•[39m Engine revision 45f6e00911
    [32m•[39m Dart version 3.0.5
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    [32m•[39m Android SDK at C:\Users\SHOBHIT\AndroidSDK\Sdk
    [32m•[39m Platform android-34, build-tools 32.1.0-rc1
    [32m•[39m Java binary at: C:\Users\SHOBHIT\AndroidStudioSpecial\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.2.32616.157
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at C:\Users\SHOBHIT\AndroidStudioSpecial
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[32m[✓][39m VS Code, 64-bit edition (version 1.77.1)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 3.66.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2965]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.110
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.50

[33m[!][39m Network resources
    [31m✗[39m A cryptographic error occurred while checking "https://pub.dev/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your
      computer.
    [31m✗[39m An HTTP error occurred while checking "https://storage.googleapis.com/": Connection closed before full header was received
    [31m✗[39m A cryptographic error occurred while checking "https://maven.google.com/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your
      computer.
    [31m✗[39m A cryptographic error occurred while checking "https://cocoapods.org/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your
      computer.
    [31m✗[39m A cryptographic error occurred while checking "https://github.com/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your
      computer.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 90c64ed42ba53a52d18f0cb3b17666c8662ed2a0
### Plugins
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.10
path_provider_windows-2.1.6

**Comment by darshankawar** [comment]
I don't see an open issue with similar tracktrace so keeping it open for team's attention.

/cc @christopherfujino

**Comment by yjbanov** [comment]
cc @andrewkolos - `_createAssetManifestBinary` implies this is related to the new binary manifest. I thought on the web we were going to use JSON in text format.

**Comment by andrewkolos** [comment]
> cc @andrewkolos - `_createAssetManifestBinary` implies this is related to the new binary manifest.

@yjbanov Looking at the stacktrace, this appears to be related to the code that parses that asset key as a URI. This code, if I recall correctly, was not changed by the introduction of the new binary asset manifest format.

> I thought on the web we were going to use JSON in text format.

This was considered as a fix to https://github.com/flutter/flutter/issues/124883. See [this comment](https://github.com/flutter/flutter/issues/128456#issuecomment-1583218046) for the source. This hasn't been implemented yet, and I first want to try to directly include the asset manifest in the entry point of the flutter app so that Flutter does not need to make a network request for the asset manifest.

**Comment by andrewkolos** [comment]
@imshobhitbajpai, since this error probably has something to do with the `assets` section of the pubspec.yaml file, it would be helpful if you could share what that part of your pubspec looks like. In the event that you cannot share this, you could also create a similar one and see if that also results in a crash upon running `flutter run`.

**Comment by imshobhitbajpai** [comment]
Thank you for your attention to this issue. I wanted to provide an update and let you know that I have discovered a solution. The problem was caused by a file located at assets/images/ABC_10%.png. After changing its format to ABC_TEN_PERC.png, the issue has been resolved.

**Comment by andrewkolos** [comment]
I'm glad you were able to get the issue resolved! I tried to reproduce this issue so it could be properly investigated and fixed. I made an example app with an asset named `assets/imags/ABC_10%.png` and ran it on Chrome, but was unable to reproduce this issue.
