### ISSUE TITLE
[url_launcher] PlatformException(java.lang.SecurityException: Permission Denial: starting Intent

### ISSUE THREAD

**Issue by hungryemon** [flutter/flutter#129499]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On opening url n some devices.

### Expected results

Successfully redirect to website

### Actual results

```console
PlatformException(java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://cdn.ostad.app/... cmp=com.mxtech.videoplayer.ad/com.mxtech.videoplayer.ActivityWebBrowser (has extras) } from ProcessRecord{64c184a 7132:com.ostad.app/u0a294} (pid=7132, uid=10294) not exported from uid 10215, SecurityException, Cause: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1247)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1338)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:919)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1437)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1389)
, Stacktrace: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://cdn.ostad.app/... cmp=com.mxtech.videoplayer.ad/com.mxtech.videoplayer.ActivityWebBrowser (has extras) } from ProcessRecord{64c184a 7132:com.ostad.app/u0a294} (pid=7132, uid=10294) not exported from uid 10215
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3025)
	at android.os.Parcel.createException(Parcel.java:3009)
	at android.os.Parcel.readException(Parcel.java:2992)
	at android.os.Parcel.readException(Parcel.java:2934)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3136)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1801)
	at android.app.Activity.startActivityForResult(Activity.java:5875)
	at android.app.Activity.startActivityForResult(Activity.java:5833)
	at android.app.Activity.startActivity(Activity.java:6331)
	at android.app.Activity.startActivity(Activity.java:6298)
	at io.flutter.plugins.urllauncher.UrlLauncher.launchUrl(UrlLauncher.java:5)
	at io.flutter.plugins.urllauncher.Messages$UrlLauncherApi.lambda$setup$1(Messages.java:5)
	at io.flutter.plugins.urllauncher.Messages$UrlLauncherApi.b(Unknown Source:0)
	at io.flutter.plugins.urllauncher.a.onMessage(Unknown Source:2)
	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:3)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:2)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:3)
	at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
	at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1247)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1338)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:919)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1437)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1389)

, null)
```

### Code sample

<details><summary>Code sample</summary>
Here is my manifest

```dart

  <application android:name="${applicationName}" android:allowBackup="true" android:icon="@mipmap/ic_launcher">
  
  <activity android:name=".MainActivity" 
    android:exported="true" 
    android:launchMode="singleTop" 
    android:theme="@style/LaunchTheme" 
    android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" 
    android:hardwareAccelerated="true" 
    android:windowSoftInputMode="adjustResize">
  

      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <action android:name="FLUTTER_NOTIFICATION_CLICK" />
        <category android:name="android.intent.category.DEFAULT" />
      </intent-filter>


    </activity>
    <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
    <meta-data android:name="flutterEmbedding" android:value="2" />
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />
    <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token" />
    <activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/app_name" />

    <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="@string/fb_login_protocol_scheme" />
      </intent-filter>
    </activity>
  
    <meta-data
        android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="@drawable/notification_icon" />
    <meta-data android:name="com.google.firebase.messaging.default_notification_color"
        android:resource="@color/notificationColor" />
  </application>
 
  <queries>
    <!-- If your app opens https URLs -->
    <intent>
      <action android:name="android.intent.action.VIEW" />
      <data android:scheme="https" />
    </intent>
    <!-- If your app makes calls -->
    <intent>
      <action android:name="android.intent.action.DIAL" />
      <data android:scheme="tel" />
    </intent>
    <!-- If your sends SMS messages -->
    <intent>
      <action android:name="android.intent.action.SENDTO" />
      <data android:scheme="smsto" />
    </intent>
    <!-- If your app sends emails -->
    <intent>
      <action android:name="android.intent.action.SEND" />
      <data android:mimeType="*/*" />
    </intent>
  </queries>
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by hungryemon** [comment]
[Fixed] MX Player was trying to start intent of zoom url instead of browser. Removed MX Player from user's device worked fine.
