### ISSUE TITLE
Full restart breaks EventChannels

### ISSUE THREAD

**Issue by robryk** [flutter/flutter#12956]
## Steps to Reproduce

1. Check out either branch `alpha` or `master`.
2. Do `flutter run` in `examples/platform_channel`.
3. Once the application loads, press `R` to cause a full restart.
4. Observe the `PlatformException(error, Stream already active, null)` being thrown.

I'd expect no such exception to occur.

I am running the application on Android. This problem reproduces most of the time, but not exactly always (possibly it doesn't reproduce if I restart the application early enough).

## Logs

```
[robryk@sharya-rana platform_channel]$ flutter run
Downloading Material fonts...
Downloading package sky_engine...
Downloading common tools...
Downloading linux-x64 tools...
Downloading linux-x64 tools...
Downloading android-arm-profile/linux-x64 tools...
Downloading android-arm-release/linux-x64 tools...
Downloading android-x86 tools...
Downloading android-x64 tools...
Downloading android-arm tools...
Downloading android-arm-profile tools...
Downloading android-arm-release tools...
Running "flutter packages get" in platform_channel...
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (22.0MB).
Installing build/app/outputs/apk/app.apk...
I/vndksupport(14384): sphal namespace is not configured for this process. Loading /vendor/lib/hw/gralloc.msm8992.so from the current namespace instead.
RSyncing files to device Nexus 5X...

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Nexus 5X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

Performing full restart...
Syncing files to device Nexus 5X...
Restarted app in 2,834ms.
I/flutter (14384): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (14384): The following PlatformException was thrown while activating platform stream on channel
I/flutter (14384): samples.flutter.io/charging:
I/flutter (14384): PlatformException(error, Stream already active, null)
I/flutter (14384): 
I/flutter (14384): When the exception was thrown, this was the stack:
I/flutter (14384): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514:7)
I/flutter (14384): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
I/flutter (14384): <asynchronous suspension>
I/flutter (14384): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:293:29)
I/flutter (14384): <asynchronous suspension>
I/flutter (14384): #7      _PlatformChannelState.initState (/data/user/0/io.flutter.examples.platform_channel/cache/platform_channelOXVKJL/platform_channel/lib/main.dart:40:43)
I/flutter (14384): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3683:14)
I/flutter (14384): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4560:14)
I/flutter (14384): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4560:14)
I/flutter (14384): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4560:14)
I/flutter (14384): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4560:14)
I/flutter (14384): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4560:14)
I/flutter (14384): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #75     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #78     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4665:32)
I/flutter (14384): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #81     _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
I/flutter (14384): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #87     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #97     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4560:14)
I/flutter (14384): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #103    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #107    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4560:14)
I/flutter (14384): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4560:14)
I/flutter (14384): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #116    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #122    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #123    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #126    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4560:14)
I/flutter (14384): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #148    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #149    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #150    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #151    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #155    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #156    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #157    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #160    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #161    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #168    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #173    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #179    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #181    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #184    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #186    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #187    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #188    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #189    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #190    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #192    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #193    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #198    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #199    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #200    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #201    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #202    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #204    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #205    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #206    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #207    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #211    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #212    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #213    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3584:16)
I/flutter (14384): #217    Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
I/flutter (14384): #218    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3552:5)
I/flutter (14384): #219    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3690:22)
I/flutter (14384): #220    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (14384): #221    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (14384): #222    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (14384): #223    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:856:16)
I/flutter (14384): #224    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:827:5)
I/flutter (14384): #225    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:773:17)
I/flutter (14384): #226    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2240:19)
I/flutter (14384): #227    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:772:13)
I/flutter (14384): #228    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:663:7)
I/flutter (14384): #229    runApp (package:flutter/src/widgets/binding.dart:705:7)
I/flutter (14384): #230    main (/data/user/0/io.flutter.examples.platform_channel/cache/platform_channelOXVKJL/platform_channel/lib/main.dart:83:3)
I/flutter (14384): #231    _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
I/flutter (14384): #232    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
I/flutter (14384): (elided 4 frames from package dart:async)
I/flutter (14384): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

## Flutter Doctor

```
[robryk@sharya-rana platform_channel]$ flutter doctor
[✓] Flutter (on Linux, locale en_GB.UTF-8, channel master)
    • Flutter at /home/robryk/flutter
    • Framework revision 93c81ffc76 (39 minutes ago), 2017-11-09 12:51:45 -0800
    • Engine revision bc2acf7bdd
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Android Studio (version 2.2)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Connected devices
    • Nexus 5X • 192.168.0.115:5555 • android-arm • Android 8.0.0 (API 26)

```

**Comment by eseidelGoogle** [comment]
@mravn-google or @a-siva might know.  One solution may be telling plugins that we've hot-reloaded so they can reset their state appropriately.

**Comment by robryk** [comment]
Please note that I'm not talking about a hot reload, but a full restart.

In the meantime I've tried cancelling the `StreamSubscription` in the `_PlatformChannelState`'s `dispose()`, but that didn't change anything.

**Comment by mravn-google** [comment]
@robryk Thanks for reporting. The error comes from [this line](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/common/EventChannel.java#L175). That code is written under the (false) assumption that the life span of the Dart isolate is 1-1 with that of the FlutterView.

**Comment by mravn-google** [comment]
On iOS, each `FlutterStreamHandler` implementation needs to deal with the consecutive calls to `onListenWithArguments:` that typical result from hot restarts. The `FlutterStreamHandler` in the `platform_channel` example doesn't do that, so following a few hot restarts, we get each event several times.

We should make the event channel implementation more consistent across iOS and Android.

**Comment by robryk** [comment]
I would expect that it is a good idea anyway to close channels when state gets dispose()d of. I've noticed that dispose() seems not to be called on state objects getting destroyed during hot restart. Why wouldn't it be a good idea to fix this (ie. cause state to be disposed of) and recommend that channels get closed in State.dispose()?

**Comment by mravn-google** [comment]
@Hixie Do you have an opinion on calling `dispose` on all `State` objects as part of hot restart?

@robryk The current solution for plugins that hold native resources is to make the Dart side invoke custom plugin initialization code on start-up, and treat repeated such calls as requests for reinitialization on the native side.

**Comment by robryk** [comment]
@mravn-google There's an additional problem caused by the current approach. Currently, upon hot restart, the channels will remain open from the POV of the Java side, even if the Dart side doesn't reopen them. This might sometimes waste resources (which isn't terribly important for a development mode), but can also sometimes affect semantics (e.g. if I have a method that configures the events that will be reported via a channel which must not be called while the channel is open).

**Comment by mravn-google** [comment]
@robryk Thanks for taking the time to discuss this! I don't have all the answers, but some comments:

Plugins that use static/singleton initialization on the Dart side would not automatically have cleanup code executed, even with `dispose` being called on all `State` objects on hot reload. It may be better to have allow plugins to register for lifecycle callbacks such as `onIsolateSpawned()`/`onIsolateDestroyed()` that they would receive directly from the Flutter engine. Not clear to me what arguments these should take (Bundles on Android?), and whether we should make the calls before or after we spawn/kill the isolate. Perhaps both... But then again, if this is to support development-time lifecycle only, it may be overkill.

Concerning waste of resources: If the Java side of your plugin consumes resources, it may want to reuse some of those resources on Dart isolate relaunch. Or it may want to stop consuming them until that Dart isolate makes a suitable request. The Flutter framework cannot possibly know what makes more sense to your plugin. This is not really an argument for or against, just that I'm reluctant to define too much lifecycle semantics to Flutter plugins as part of the framework. Leaving it up to each plugin seems more flexible.

Concerning your example: Suppose your plugin is initialized by first defining which events to report, using method _m_. Then a second call to _m_ should currently be considered, by the Java code, as reinitialization (which might involve unregistering current native event listeners). If you are able to make _m_=`onListen(args)`, then that should happen automatically with the latest flutter/engine changes, provided unregistration is already implemented in `onCancel`.
