### ISSUE TITLE
Webview goes blank and freezes after scrolling[Android]

### ISSUE THREAD

**Issue by zmeid** [flutter/flutter#129601]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Using `webview_flutter: ^4.2.2` and testing on Samsung S23 Ultra Android 13 (API 33), some web pages make the webview go blank or/and freeze. Generally happens when scrolling. See the 12. sec in attached video.

I migrated from `webview_flutter: ^3.0.4` to `^4.2.2` and from`Flutter 3.7.12` to `3.10.5`. There was no such issue with webview `^3.0.4` and Flutter `3.7.12`.

### Expected results

Webview should not show a blank screen when scrolling.

### Actual results

Webview sometimes shows blank screen when scrolling.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/flutter/flutter/assets/13780749/04134825-bc90-4a0d-a7b5-a0eff84e1ab8)

</details>

### Logs

<details><summary>Logs</summary>

```console
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
I/chromium(15833): [INFO:CONSOLE(1)] "<link rel=preload> has an invalid `href` value", source: https://www.benzinga.com/news/23/06/32996785/eus-ai-act-includes-a-category-for-unacceptable-risk-applications (1)
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
E/FrameEvents(15833): updateAcquireFence: Did not find frame.
I/cr_DWTrigger(15833): updateDWServiceStatus() : isEnabled = true
I/cr_DWTrigger(15833): updateDWServiceStatus() : isEnabled = true
E/FrameEvents(15833): updateAcquireFence: Did not find frame.

======== Exception caught by image resource service ================================================
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2751:9)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2622:7)
#2      IOClient.send (package:http/src/io_client.dart:63:38)
#3      HttpFileService.get (package:flutter_cache_manager/src/web/file_service.dart:35:44)
#4      WebHelper._download (package:flutter_cache_manager/src/web/web_helper.dart:121:24)
#5      WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:103:28)
<asynchronous suspension>
#6      WebHelper._downloadOrAddToQueue (package:flutter_cache_manager/src/web/web_helper.dart:71:7)
<asynchronous suspension>
Image provider: CachedNetworkImageProvider("", scale: 1.0) 
 Image key: CachedNetworkImageProvider("", scale: 1.0): CachedNetworkImageProvider("", scale: 1.0)
====================================================================================================
W/cr_AwContents(15833): WebView.destroy() called while WebView is still attached to window.
I/chromium(15833): [INFO:CONSOLE(1)] "<link rel=preload> has an invalid `href` value", source: https://www.benzinga.com/news/23/06/32996785/eus-ai-act-includes-a-category-for-unacceptable-risk-applications (1)
I/chromium(15833): [INFO:CONSOLE(34)] "RUNTIME_ENV: development", source: https://www.benzinga.com/_next/static/chunks/pages/_app-0211be21e8c24c37.js (34)
I/chromium(15833): [INFO:CONSOLE(8)] "isBZTrackLoaded:  false", source: https://www.benzinga.com/_next/static/chunks/pages/_app-0211be21e8c24c37.js (8)
I/chromium(15833): [INFO:CONSOLE(8)] "isAnalyticsShouldRun:  true", source: https://www.benzinga.com/_next/static/chunks/pages/_app-0211be21e8c24c37.js (8)
I/chromium(15833): [INFO:CONSOLE(8)] "Google Push Data::{"event":"page_view","page_url":"/news/23/06/32996785/eus-ai-act-includes-a-category-for-unacceptable-risk-applications","path":"/news/23/06/32996785/eus-ai-act-includes-a-category-for-unacceptable-risk-applications","ageOfArticle":3,"authorId":1347780,"authorName":"Chris Bibey","authorType":"Benzinga Staff Writer","channels":"News:Startups:Tech","contentType":"story","pageType":"story","viewAmpAppWeb":0}", source: https://www.benzinga.com/_next/static/chunks/pages/_app-0211be21e8c24c37.js (8)
I/chromium(15833): [INFO:CONSOLE(8)] "Google Push Data::{"event":"gtm.js","gtm.start":1687831459741}", source: https://www.benzinga.com/_next/static/chunks/pages/_app-0211be21e8c24c37.js (8)
I/chromium(15833): [INFO:CONSOLE(1)] "WBC Event - Tracking with payload:  [object Object]", source: https://www.benzinga.com/_next/static/chunks/pages/_app-0211be21e8c24c37.js (1)
D/BufferPoolAccessor2.0(15833): evictor expired: 7, evicted: 0
I/chromium(15833): [INFO:CONSOLE(6)] "Completing build for article page: 32996785", source: https://www.benzinga.com/_next/static/chunks/pages/article/%5Bid%5D-b78b023559eb292c.js (6)
I/chromium(15833): [INFO:CONSOLE(2)] "Uncaught ReferenceError: OneSignal is not defined", source: https://www.benzinga.com/news/23/06/32996785/eus-ai-act-includes-a-category-for-unacceptable-risk-applications (2)
I/chromium(15833): [INFO:CONSOLE(6)] "Completing build for article page: 32996785", source: https://www.benzinga.com/_next/static/chunks/pages/article/%5Bid%5D-b78b023559eb292c.js (6)
I/chromium(15833): [INFO:CONSOLE(6)] "Completing build for article page: 32996785", source: https://www.benzinga.com/_next/static/chunks/pages/article/%5Bid%5D-b78b023559eb292c.js (6)
I/chromium(15833): [INFO:CONSOLE(6)] "Completing build for article page: 32996785", source: https://www.benzinga.com/_next/static/chunks/pages/article/%5Bid%5D-b78b023559eb292c.js (6)
I/chromium(15833): [INFO:CONSOLE(6)] "Completing build for article page: 32996785", source: https://www.benzinga.com/_next/static/chunks/pages/article/%5Bid%5D-b78b023559eb292c.js (6)
I/chromium(15833): [INFO:CONSOLE(6)] "Completing build for article page: 32996785", source: https://www.benzinga.com/_next/static/chunks/pages/article/%5Bid%5D-b78b023559eb292c.js (6)
I/chromium(15833): [INFO:CONSOLE(1)] "WBC Event - Tracking response:  [object Response]", source: https://www.benzinga.com/_next/static/chunks/pages/_app-0211be21e8c24c37.js (1)
I/chromium(15833): [INFO:CONSOLE(6)] "Completing build for article page: 32996785", source: https://www.benzinga.com/_next/static/chunks/pages/article/%5Bid%5D-b78b023559eb292c.js (6)
I/chromium(15833): [INFO:CONSOLE(10)] "The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202306220101/pubads_impl.js (10)
I/chromium(15833): [INFO:CONSOLE(10)] "googletag.pubads().setCookieOptions() has been removed, and no longer has any effect. Consider migrating to Limited Ads.", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202306220101/pubads_impl.js (10)
I/chromium(15833): [INFO:CONSOLE(10)] "[GPT] Invalid arguments: PubAdsService.setTargeting('BZ_POS_KEYWORD_GROUP', undefined).", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202306220101/pubads_impl.js (10)
I/chromium(15833): [INFO:CONSOLE(10)] "[GPT] Invalid arguments: PubAdsService.setTargeting('BZ_POS_KEYWORD_GROUP', undefined).", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202306220101/pubads_impl.js (10)
I/chromium(15833): [INFO:CONSOLE(6)] "Completing build for article page: 32996785", source: https://www.benzinga.com/_next/static/chunks/pages/article/%5Bid%5D-b78b023559eb292c.js (6)
I/chromium(15833): [INFO:CONSOLE(0)] "Access to image at 'android-webview-video-poster:default_video_poster/-6565598786964969295' from origin 'https://www.benzinga.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://www.benzinga.com/news/23/06/32996785/eus-ai-act-includes-a-category-for-unacceptable-risk-applications (0)
D/SensorManager(15833): registerListener :: 151, Game Rotation Vector  Non-wakeup, 16666, 0, 
D/SensorManager(15833): unregisterListener
W/System.err(15833): java.io.IOException: Pipe closed
W/System.err(15833): 	at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:263)
W/System.err(15833): 	at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:271)
W/System.err(15833): 	at java.io.PipedInputStream.receive(PipedInputStream.java:234)
W/System.err(15833): 	at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
W/System.err(15833): 	at android.graphics.Bitmap.nativeCompress(Native Method)
W/System.err(15833): 	at android.graphics.Bitmap.compress(Bitmap.java:1471)
W/System.err(15833): 	at Ar.run(chromium-TrichromeWebViewGoogle6432.aab-stable-573513133:105)
D/OpenGLRenderer(15833): ------- write threw an exception
D/BufferPoolAccessor2.0(15833): bufferpool2 0xb4000072a0a73828 : 0(0 size) total buffers - 0(0 size) used buffers - 16/21 (recycle/alloc) - 5/17 (fetch/transfer)
D/BufferPoolAccessor2.0(15833): evictor expired: 1, evicted: 1
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/xxxxx/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (13 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xxxxx/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM S918U1 (mobile) • adb-R5CW51BMYLV-fsX5j0._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • macOS (desktop)    • macos                                         • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)       • chrome                                        • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@zmeid 
Can you provide [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the reported behavior ?

**Comment by zmeid** [comment]
While I was preparing to provide a code sample, I noticed that I set up/initialize the webview controller in widget's `build` method. After moving controller initialization to `init` method, the issue was solved. Closing that bug, thank you!
