### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException

### ISSUE THREAD

**Issue by Vidhyasagar731** [flutter/flutter#129760]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
DartDevelopmentServiceException
```
#0      DartDevelopmentServiceImpl._startDDSServer (package:dds/src/dds_impl.dart:213:7)
<asynchronous suspension>
#1      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:116:7)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#3      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:154:12)
<asynchronous suspension>
#4      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:466:7)
<asynchronous suspension>
#5      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:241:21)
<asynchronous suspension>
#6      Dwds.debugConnection (package:dwds/dart_web_debug_service.dart:61:30)
<asynchronous suspension>
#7      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:713:15)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.10, on macOS 13.2 22D49 darwin-x64, locale en-GB)
    [32m•[39m Flutter version 3.7.10 on channel stable at /Users/vidhyasagar/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4b12645012 (3 months ago), 2023-04-03 17:46:48 -0700
    [32m•[39m Engine revision ec975089ac
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/vidhyasagar/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m ANDROID_HOME = /Users/vidhyasagar/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14C18
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.66.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 13.2 22D49 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 52b3dc25f6471c27b2144594abb11c741cb88f57
### Plugins
audio_session-0.1.13
file_picker-5.2.10
firebase_analytics-10.2.0
firebase_analytics_web-0.5.2
firebase_core-2.9.0
firebase_core_web-2.3.0
firebase_messaging-14.4.0
firebase_messaging_web-3.3.0
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_local_notifications-13.0.0
flutter_plugin_android_lifecycle-2.0.9
image_picker-0.8.7+1
image_picker_android-0.8.6+6
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+3
just_audio-0.9.32
just_audio_web-0.4.7
path_provider-2.0.14
path_provider_android-2.0.24
path_provider_foundation-2.2.1
path_provider_linux-2.1.10
path_provider_windows-2.1.5
quill_html_editor-2.1.8
share_plus-6.3.2
shared_preferences-2.1.0
shared_preferences_android-2.1.0
shared_preferences_foundation-2.2.0
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
smart_auth-1.0.8
sqflite-2.2.8+1
url_launcher-6.1.10
url_launcher_android-6.0.26
url_launcher_ios-6.1.4
url_launcher_linux-3.0.4
url_launcher_macos-3.0.4
url_launcher_web-2.0.16
url_launcher_windows-3.0.5
video_player-2.6.1
video_player_android-2.4.7
video_player_avfoundation-2.4.5
video_player_web-2.0.16
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-4.2.0
webview_flutter_android-3.6.2
webview_flutter_wkwebview-3.4.0

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108848
