### ISSUE TITLE
Error in the Navigator of the flutter framework

### ISSUE THREAD

**Issue by AshikGtHb** [flutter/flutter#129711]
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#03beb](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope], state: NavigatorState#ea040(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5234 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/Users/Asus/Desktop/Flutter_Projects/ChatApp/lib/main.dart:60:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5234:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#12     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#35     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#39     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#47     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#52     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#56     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#60     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#65     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#69     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#73     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#77     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#81     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#85     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#90     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#92     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#94     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#98     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#99     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#102    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#104    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#107    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#109    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#113    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#116    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#118    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#124    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#125    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#128    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#130    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#133    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#135    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#139    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#142    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#144    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#146    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#150    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#151    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#154    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#156    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#159    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#160    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#161    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#164    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#165    StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#166    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#167    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#168    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#170    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#171    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#172    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#175    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#176    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#177    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#180    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#182    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#185    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#186    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#189    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#190    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#191    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#194    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#195    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#196    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#198    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#199    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#200    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#203    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#204    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#205    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#207    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#209    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#212    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#214    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#215    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#216    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#217    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#219    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#220    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#221    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#222    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#223    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#224    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#226    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#229    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#230    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#234    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#235    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#237    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#238    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#239    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#240    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#242    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#243    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#244    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#245    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#246    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#247    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#248    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#249    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#253    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================
```

**Comment by darshankawar** [comment]
@AshikGtHb 
Although the error log does say to file an issue, but we need more details like reproducible code sample, steps to replicate so that we can properly address the issue. So if you have a concrete reproducible code sample that triggers the error, please provide one so as to make the issue actionable along with `flutter doctor -v` on which the error is occuring.
