### ISSUE TITLE
dll works with dart, but makes flutter die on windows

### ISSUE THREAD

**Issue by mpl** [flutter/flutter#129764]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I generate a dynamic library from Go code (basically an HTTP server, and an mDNS server) with CGO. (`CGO_ENABLED=1 go build -buildmode=c-shared`). I redo that step (generate an .so when on Unix, or a .dll when on windows) for each separate platform of course.
Then I use it with ffi.DynamicLibrary.open , lookup a function, call it, etc.

It works without any problem on Mac. (with `flutter run -d macos`)

On windows (on a windows machine, with `flutter run -d windows`), the call to .open seems to work (try catch around it does not show any exception), but right after that, the dart VM seems to die? The very first time this happens, the message is:

```
A Dart VM Service on Windows is available at: http://127.0.0.1:59115/otsWGWwNHvw=/
Lost connection to device.
```

Then all the subsequent runs fail with:

```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:59148/gYFWwYfFGH0=/
```

as the only indication. No stacktrace, no other error message. The GUI from my app does not even have time to show up.

But here's the real kicker:

1) If I open and use the dll just with dart on windows (no flutter), no problem, it works.

2) If I ssh (from my mac) to windows (yeah, there's sshd on windows, who knew...), and if I run the app in flutter that way, then of course I get some error messages due to the fact that the GUI cannot show up (because over ssh), but then the dll actually loads and works too!

Given that there's no output to work with, I'm really stumped as how to debug that.
Does anyone have any suggestion on how I could get more debugging info about what's going on?

Update: with --verbose enabled, I get this:

```
[   +4 ms] √  Built build\windows\runner\Debug\my_app.exe.
[ +329 ms] VM Service URL on device: http://127.0.0.1:59186/dWdn3z3UvSc=/
[   +5 ms] Caching compiled dill
[  +58 ms] Connecting to service protocol: http://127.0.0.1:59186/dWdn3z3UvSc=/
[ +152 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:59186/dWdn3z3UvSc=/.
[  +92 ms] DDS is listening at http://127.0.0.1:59189/RMAiJllI4EM=/.
[ +868 ms] Fail to connect to service protocol: http://127.0.0.1:59186/dWdn3z3UvSc=/: Exception: DDS shut down too early
[   +1 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:59186/dWdn3z3UvSc=/
[   +5 ms] "flutter run" took 13,581ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +26 ms] ensureAnalyticsSent: 20ms
[        ] Running 1 shutdown hook
[   +6 ms] Shutdown hooks complete
[        ] exiting with code 2
```

Does anyone know how I can get more info as to why the DDS died?

### Expected results

I would not expect the DDS to die.

I would expect loading the dll not to cause any problem, especially since it works in standalone dart.

### Actual results

The app dies immediately. Apparently because the DDS dies?

### Code sample

Would it actually help if I shared a minimum Go source to reproduce the problem, and how to create the dll from it?
If yes, then I'll definitely do it.
Then it's just the regular dart:ffi way of loading it, as described on https://dart.dev/guides/libraries/c-interop

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[   +4 ms] √  Built build\windows\runner\Debug\my_app.exe.
[ +329 ms] VM Service URL on device: http://127.0.0.1:59186/dWdn3z3UvSc=/
[   +5 ms] Caching compiled dill
[  +58 ms] Connecting to service protocol: http://127.0.0.1:59186/dWdn3z3UvSc=/
[ +152 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:59186/dWdn3z3UvSc=/.
[  +92 ms] DDS is listening at http://127.0.0.1:59189/RMAiJllI4EM=/.
[ +868 ms] Fail to connect to service protocol: http://127.0.0.1:59186/dWdn3z3UvSc=/: Exception: DDS shut down too early
[   +1 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:59186/dWdn3z3UvSc=/
[   +5 ms] "flutter run" took 13,581ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +26 ms] ensureAnalyticsSent: 20ms
[        ] Running 1 shutdown hook
[   +6 ms] Shutdown hooks complete
[        ] exiting with code 2
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3086], locale en-150)
    • Flutter version 3.10.5 on channel stable at E:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at E:/sdk/Android/Sdk/
    • Platform android-33, build-tools 33.0.2
    • Java binary at: E:\sdk\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.6.1)
    • Visual Studio at E:\sdk\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.6.33717.318
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at E:\sdk\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3086]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.135
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.43

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dcharkes** [comment]
The lookup path for dlopen might be different for Flutter Desktop Windows apps vs Dart standalone.

In order to get more debug information we need to run the executable from visual studio. VS will open the debugger on crash (which will likely be in dlopen, or the dynamic loader that tries to load other dynamic libraries that your dynamic library depends on).
To open the executable in visual studio:

1. open visual studio
2. drag the executable into visual studio. The executable will be in a path similar to `C:\src\dacoharkes\playground\my_package\example\build\windows\runner\Debug\my_package_example.exe`
3. run with: 
<img width="84" alt="image" src="https://github.com/flutter/flutter/assets/3601775/29a3b668-bdf4-4209-817a-35632e34a484">


Side note:

> Then I use it with ffi.DynamicLibrary.open , lookup a function, call it, etc.

Did you add any logic to bundle & sign the dll in the Flutter desktop apps? Otherwise your app will only work on the system where you build it.

**Comment by mpl** [comment]
Hello @dcharkes ,

Thanks for the reply.
I am quite confident that the .dll is actually found, because:

1) there's no error indicating that it has not been found (I have had to deal with that in the past already).
2) as I said, when I run flutter over ssh on windows (same windows machine, same project directory, etc, but simply sshed to it instead of sitting on it), then the code from the dll actually works (the HTTP server is running, the mDNS server is running too, etc).

I am not using Visual Studio, but it's true that I could maybe get more hints from there I suppose, thanks for the idea.

> Did you add any logic to bundle & sign the dll in the Flutter desktop apps? Otherwise your app will only work on the system where you build it.

No I haven't yet but it's on my TODO list. That is the least of my worries for now, since flutter already dies in dev mode. :-)

**Comment by mpl** [comment]
Just to reiterate, this is what I see when I run it over ssh:
```
[   +4 ms] √  Built build\windows\runner\Debug\my_app.exe.
[ +199 ms] [ERROR:flutter/shell/platform/windows/direct_manipulation.cc(201)] manager_->Activate(window_->GetWindowHandle()) failed
[   +1 ms] ERR: SwapChain11.cpp:636 (reset): Could not create additional swap chains or offscreen surfaces, HRESULT: 0x887A0022
[        ] ERR: SwapChain11.cpp:636 (reset): Could not create additional swap chains or offscreen surfaces, HRESULT: 0x887A0022
[        ] ERR: SwapChain11.cpp:643 (reset): Device lost in SwapChain11::reset HRESULT: 0x887A0022, reason: HRESULT: 0x00000000
[        ] ERR: SwapChain11.cpp:643 (reset): Device lost in SwapChain11::reset HRESULT: 0x887A0022, reason: HRESULT: 0x00000000
[        ] [ERROR:flutter/shell/platform/windows/angle_surface_manager.cc(15)] EGL: Surface creation failed.
[        ] [ERROR:flutter/shell/platform/windows/angle_surface_manager.cc(16)] EGL: eglGetError returned 12302
[   +6 ms] [ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(121)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[        ] [ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(43)] Could not make the context current to set up the Gr context.
[        ] [ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(81)] Could not make the context current to set up the Gr context.
[        ] [ERROR:flutter/shell/common/platform_view.cc(75)] Failed to create platform view rendering surface
[  +81 ms] VM Service URL on device: http://127.0.0.1:59479/pH_AAC-8hAg=/
[   +5 ms] Caching compiled dill
[  +50 ms] Connecting to service protocol: http://127.0.0.1:59479/pH_AAC-8hAg=/
[  +54 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:59479/pH_AAC-8hAg=/.
[  +55 ms] DDS is listening at http://127.0.0.1:59482/rs5cqiGW7iY=/.
[   +8 ms] DATABASE AT E:\XXXX\XXXX\.dart_tool\sqflite_common_ffi\databases\ftc.db
[        ] STARTING TO SERVE
[  +17 ms] Successfully connected to service protocol: http://127.0.0.1:59479/pH_AAC-8hAg=/
[  +20 ms] DevFS: Creating new filesystem on the device (null)
[  +20 ms] DevFS: Created new filesystem on the device (file:///E:/sdk/msys64/tmp/notflutter5e1dadb1/notflutter/)
[   +2 ms] Updating assets
[ +163 ms] Syncing files to device Windows...
[   +3 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[   +1 ms] <- recompile package:my_app/main.dart 071b3fd8-237d-4954-95a9-33366d739882
[        ] <- 071b3fd8-237d-4954-95a9-33366d739882
[   +4 ms] Bundle processing done.
[ +177 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Windows... (completed in 188ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +2 ms] Connected to _flutterView/0x2688b963920.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload.
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[   +1 ms] A Dart VM Service on Windows is available at: http://127.0.0.1:59482/rs5cqiGW7iY=/
[ +262 ms] The Flutter DevTools debugger and profiler on Windows is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:59482/rs5cqiGW7iY=/
```

So yes, as expected the GUI stuff is failing (because no ssh -X for windows oc), but otoh, in this case the DLL is loaded fine and actually works (the "DATABASE" and "STARTING TO SERVE" messages). And as you can see the DDS does not die then. So weird that somehow my DLL would be an interference with the GUI parts?

**Comment by stuartmorgan** [comment]
As mentioned above, running this under the Visual Studio debugger is going to be the way to find out what is killing the process; it's pretty much impossible to speculate about what could be happening without that information.

**Comment by mpl** [comment]
@stuartmorgan ah sorry, I forgot to report back about that. I did run it in VSCode earlier today (apparently with debugging), but I saw absolutely no more information. Then again, I have barely ever used that tool, so maybe I have missed something obvious I should do?

**Comment by stuartmorgan** [comment]
VSCode is not the same thing as Visual Studio; running a Flutter application under VSCode will just do essentially what `flutter run` does. You need the Visual Studio debugger, which will catch crashes in native code.

**Comment by mpl** [comment]
Haha I had a suspicion I was making that confusion. Thanks, I'll try it out
tomorrow.

**Comment by mpl** [comment]
So I have managed to run it with Visual Studio, but for now I have no more additional clue as to what's going on.
As soon as it starts running, it gets into the dll, it stops because of a breakpoint instruction (__debugbreak()) and nothing is displayed because it says "No symbol file loaded for stuff.dll". I can keep on clicking, going from one breakpoint to another, but it does not help me for now.
I have checked what cgo is doing (with -x), and it seems that it is calling gcc with -g, so I would naively expect the debug symbols to be there, but who knows...
I'll keep on digging and report if I find anything interesting.

**Comment by mpl** [comment]
Alright, since I haven't had any more luck, (and also to prove myself that I hadn't messed something up in my app) I have at least created the smallest possible repro, on top of the default app provided by 'flutter create'. Same results, which are:

1) dynlib loads and works on mac
2) DLL loads and works on windows, if I am remotely logged in over ssh to windows (hence, the GUI parts are failing).
3) fails on windows (DLL fails to load probably?)

I have provided the .dll and the .h in the project, but they can be recreated from the src/desktop directory, see instruction on top of the stuff.go file.

Since I have already lost so much time on this, and it is still not looking hopeful, I will probably try to see if I can somehow run the Go code through the platform-channels technique instead.

[superproject.zip](https://github.com/flutter/flutter/files/11918061/superproject.zip)

**Comment by mpl** [comment]
Btw, am I correct in thinking that the reason the DLL can't be debugged in VS, is because it was compiled with gcc ?

**Comment by mpl** [comment]
As an additional data point: it was a pain, but I did succeed with running some code from a .dll generated with cgo (hence gcc), including it as part of the build in windows/runner, and then calling it through a method channel from flutter.
Definitely not as convenient as loading the code directly as FFI, but I guess it will be my workaround for now.

**Comment by stuartmorgan** [comment]
Are you running code that has specific threading requirements?

**Comment by mpl** [comment]
@stuartmorgan if you're asking if my go code would have goroutines and such, it probably would yes. But as you can see in the repro I posted above (superproject.zip), I can't even make a trivial hello world from the main thread work anyway.

**Comment by mpl** [comment]
Alright, by pure chance (and because I got some insights while fixing related problems with the platform channel technique) I have found out a crazy work-around, so please bear with me.

First of all @dcharkes , you were right on part of the story, as part of it is a matter of where the .dll is placed. And here is why I go tricked:

1) if the .dll is not found or does not exist, (when doing ffi.DynamicLibrary.open) one gets an error message such as:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libstuff.dll': error code 126`

2) if I place the .dll at the root of the flutter project (I know, not for production purposes), like I do for MacOS, then there's no such message, and the app crashes as I have already described.

3) if I move the .dll near the .exe (so in build/windows/runner/Debug), then it still crashes, but I'm mentioning it, because at the end of the story, that's actually where we'll want it to be for things to work.

Now for the crazy part:

when I was working on making things work with the platform channel technique (instead of FFI), I figured out that I needed to do the whole dance of generating a `.lib` along with the `.dll` (which is not what gcc or cgo does by default), and have Cmake take into account that .lib. Then I need, to include my `.h` in windows/runner/flutter_window.cpp , and add the bit of code in there (in `bool FlutterWindow::OnCreate`) that sets up the method call handler on the method channel, right?

Well, it turns out that if I keep all that, then the ffi.DynamicLibrary.open call works, and I can actually directly call my methods (without having to go through the method channel)! It's basically as if doing all that makes the symbols actually be known and usable by the FFI technique.

Now, I narrowed it all down, and for the ffi.DynamicLibrary.open call to actually work, here are the pieces that I actually needed:

1) in `windows/runner/CMakeLists.txt`:

target_link_libraries(${BINARY_NAME} PRIVATE "${CMAKE_SOURCE_DIR}/runner/libstuff.lib") # just like for the platform channel technique

2) in `windows/runner/flutter_window.cpp`:

#include "libstuff.h" // just like for teh platform channel technique

AND any reference to the function that you're going to call later, but no need for the whole flutter::MethodChannel machinery. e.g.

```
	// because we don't actually want to ever call it from here
	if (false) {
		MyCFunc();
	}
```
in OnCreate is enough (but necessary afaict).

3) place `libstuff.dll` in `build/windows/runner/Debug`

At first I thought 3) would be the only step needed, but I retried many times, and I really believe 1) and 2) are needed too.

So while I got it working, I think it's just by luck and/or side-effect, and I don't think the issue should be considered closed. But hey, at least I can move forward now. :-)

**Comment by gspencergoog** [comment]
Removing the Desktop tag, as this isn't something for the desktop team.  Perhaps, since this appears to do with Dart specifically, the issue should be moved to the Dart issue tracker? I suspect that the end result might just be some extra documentation in the Dart docs. (Desktop Triage)

**Comment by dcharkes** [comment]
> Removing the Desktop tag, as this isn't something for the desktop team. Perhaps, since this appears to do with Dart specifically, the issue should be moved to the Dart issue tracker? I suspect that the end result might just be some extra documentation in the Dart docs. (Desktop Triage)

It works on Dart standalone for the user:

> 1. If I open and use the dll just with dart on windows (no flutter), no problem, it works.

So it has to do with the difference between a compiled Flutter Windows Desktop app and the `dart.exe`.

That being said, it could also be something specific to this dll.

> As soon as it starts running, it gets into the dll, it stops because of a breakpoint instruction (__debugbreak()) and nothing is displayed because it says "No symbol file loaded for stuff.dll"

> DLL loads and works on (flutter) windows, if I am remotely logged in over ssh to windows

Is your dll trying to call windows APIs to draw UI elements? Maybe those UIs are thread-bound. Flutter doesn't run the main isolate on the system thread.

Does the app also crash if you only try to sum two numbers through FFI in Go via CGo? (E.g. super simple Go code, no dependencies, only a single function that sums two numbers.)

**Comment by mpl** [comment]
> > Removing the Desktop tag, as this isn't something for the desktop team. Perhaps, since this appears to do with Dart specifically, the issue should be moved to the Dart issue tracker? I suspect that the end result might just be some extra documentation in the Dart docs. (Desktop Triage)
> 
> It works on Dart standalone for the user:
> 
> > 1. If I open and use the dll just with dart on windows (no flutter), no problem, it works.

yep.

> So it has to do with the difference between a compiled Flutter Windows Desktop app and the `dart.exe`.

That is very much my suspicion too.

> That being said, it could also be something specific to this dll.
> 
> > As soon as it starts running, it gets into the dll, it stops because of a breakpoint instruction (__debugbreak()) and nothing is displayed because it says "No symbol file loaded for stuff.dll"
> 
> > DLL loads and works on (flutter) windows, if I am remotely logged in over ssh to windows
> 
> Is your dll trying to call windows APIs to draw UI elements? Maybe those UIs are thread-bound. Flutter doesn't run the main isolate on the system thread.

I sure hope it does not, given that all it is supposed to do is `println("hello world")`.
You can see for yourself with https://github.com/flutter/flutter/files/11918061/superproject.zip ;)

> Does the app also crash if you only try to sum two numbers through FFI in Go via CGo? (E.g. super simple Go code, no dependencies, only a single function that sums two numbers.)

I have just retried with `_ = 3 + 2` as the only code in the repro above, same result (works with dart, but crashes with flutter).

**Comment by lucien-F** [comment]
i have the same problem. 
1、 the dll can work fine with dart standlone  in the same windows PC, 
2、the application（above mentioned） which flutter complied work fine in the other windows PC.
3、the dll can be ffi.DynamicLibrary.open currect  with low probability ,but mostly die

**Comment by lucien-F** [comment]
@mpl set the intelGraphic output primary display instead nvidia output in your windows setting. then your flutter exe can load cgo dll currect.  this is a  Flutter Graphic BUG!

**Comment by mpl** [comment]
Wow. I can confirm that @lucien-F 's work-around indeed works for me too, even though my DLL (as we have already established before with @dcharkes ) should have nothing to do with displaying UI elements (in theory at least).
That at least explains why things were working when I was starting flutter over SSH.

**Comment by dcharkes** [comment]
> @mpl set the intelGraphic output primary display instead nvidia output in your windows setting. then your flutter exe can load cgo dll currect. this is a Flutter Graphic BUG!

Wow, that's an amazing find! 👍

**Comment by mpl** [comment]
> > @mpl set the intelGraphic output primary display instead nvidia output in your windows setting. then your flutter exe can load cgo dll currect. this is a Flutter Graphic BUG!
> 
> Wow, that's an amazing find! 👍

indeed. I would have never thought of that... And I really wonder how @lucien-F came up with the idea :)

**Comment by lucien-F** [comment]
> > > @mpl set the intelGraphic output primary display instead nvidia output in your windows setting. then your flutter exe can load cgo dll currect. this is a Flutter Graphic BUG!
> > 
> > 
> > Wow, that's an amazing find! 👍
> 
> indeed. I would have never thought of that... And I really wonder how @lucien-F came up with the idea :)
1、your issue inspired me ;
2、I happen to know that Nvidia and Intel use different driver implementations。

**Comment by lucien-F** [comment]
I really want this bug fixed as soon as possible.

**Comment by mpl** [comment]
> I really want this bug fixed as soon as possible.

Did you see that you can "fix" this dynamic loading, if you beforehand dynamically link the final app executable to your DLL?
There are a couple of tricks to it though, so let me know if you want me to elaborate on that.

**Comment by lucien-F** [comment]
> > I really want this bug fixed as soon as possible.
> 
> Did you see that you can "fix" this dynamic loading, if you beforehand dynamically link the final app executable to your DLL? There are a couple of tricks to it though, so let me know if you want me to elaborate on that.

I see but not understand that you mentioned.   so .... show me your magic ! Please  :)

**Comment by mpl** [comment]
@lucien-F 

ok, in the following, assume that my Go code is in ./src/stuff , relative to the root of the flutter project.
Here's pretty much my build process, when in ./src/stuff

```
# just cleaning up from previous builds
rm -f stuff.def libstuff.dll libstuff.exp libstuff.h libstuff.lib

# you want this CGO_LDFLAGS_ALLOW in conjunction with the following in your Go code:
# // #cgo LDFLAGS: -Wl,--output-def=stuff.def
# import "C"

# in order to enable the generation of stuff.def, which will be used later on to create a .lib
CGO_LDFLAGS_ALLOW='-Wl.*' CGO_ENABLED=1 go build -buildmode=c-shared -o libstuff.dll . 

# this is basically like a sed, to remove some typedefs in libstuff.h about complex types that MSVC chokes on. I didn't have the patience to understand why, since my code for now does not rely on complex types.
go run ./stripcomplex/main.go

# $ cat stuff.defheader 
# LIBRARY libstuff.dll
cat stuff.defheader stuff.def > fullstuff.def
mv fullstuff.def stuff.def

# the same MSVC tools that my flutter install depends on
/e/sdk/Microsoft\ Visual\ Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/lib.exe //def:stuff.def //out:libstuff.lib //machine:x64

# technically, I don't even think we need the .dll there, only the .lib and the .h, but whatever.
cp libstuff.dll libstuff.h libstuff.lib ../../windows/runner/

# because we'll need the .dll there at runtime, and I can't be bothered to learn the horror that is CMake.
mkdir -p ../../build/windows/runner/Debug/
cp libstuff.dll ../../build/windows/runner/Debug/
```

And here are the other changes you need:

1) in ./windows/runner/CMakeLists.txt :

```
# Add dependency libraries and include directories. Add any application-specific
# dependencies here.
target_link_libraries(${BINARY_NAME} PRIVATE flutter flutter_wrapper_app)
target_link_libraries(${BINARY_NAME} PRIVATE "dwmapi.lib")
target_link_libraries(${BINARY_NAME} PRIVATE "${CMAKE_SOURCE_DIR}/runner/libstuff.lib") # <-- this one
target_include_directories(${BINARY_NAME} PRIVATE "${CMAKE_SOURCE_DIR}")
```

2) in ./windows/runner/flutter_window.cpp

```
#include "libstuff.h"
```

and 

```
bool FlutterWindow::OnCreate() {
  // this here should be done for each of your Go/CGO functions/methods that you want to call from flutter
  if (false) {
    MyCGOFuncThatIWantToUseInFlutter("NEVER CALLED");
  }
  // end of modification

  if (!Win32Window::OnCreate()) {
    return false;
  }
```

I should probably at some point make another fully contained minimal repro with all of this in. Might be easier for people to understand that way.

**Comment by lucien-F** [comment]
> 

Got IT!  Indeed, that is less of  constraint.  and  it will help me much. Thanks for sharing :)

be the way ,are you  commented out  ffi.dynamic.open in your dart code?

**Comment by mpl** [comment]
> > 
> 
> Got IT! Indeed, that is less of constraint. and it will help me much. Thanks for sharing :)
> 
> be the way ,are you commented out ffi.dynamic.open in your dart code?

Sorry, I don't understand the question. Are you asking if I use ffi.DynamicLibrary.open in my code? If yes, then of course I do. Being able to use this call is the whole point of the "fix" described above.

But it is true that with the build process I described, the code now being dynamically linked, one could use platform channels instead of dynamic loading, but I see no point in doing so, as it is more cumbersome imho.

**Comment by lucien-F** [comment]
OK , Thanks for the explanation, buddy :)

**Comment by mpl** [comment]
> OK , Thanks for the explanation, buddy :)

Np, that's the beauty of open-source. You helped move forward this issue, and now you've also gotten some help in return :)

**Comment by mpl** [comment]
Kindly pinging @ianlancetaylor in case he has any insight on the question.

**Comment by ianlancetaylor** [comment]
I'm sorry, I really don't.  I don't know enough about Windows DLLs.

**Comment by loic-sharma** [comment]
Is this an accurate summary of the CGO DLL problem?

Status | App kind | Technique | Notes
-- | -- | -- | --
✅ | Standalone Dart on Windows | Dart FFI | 
✅ | Flutter Windows app using Intel graphics driver | Dart FFI | https://github.com/flutter/flutter/issues/129764#issuecomment-1630229570
❌ | Flutter Windows app using NVIDIA graphics driver | Dart FFI | https://github.com/flutter/flutter/issues/129764#issuecomment-1630229570
✅ | Flutter Windows app | Dynamic linking | https://github.com/flutter/flutter/issues/129764#issuecomment-1632263077

@mpl Could you create a minimal repro of a Flutter Windows app using Dart FFI on a CGO DLL? FYI, Windows Defender flagged your [superproject.zip above](https://github.com/flutter/flutter/issues/129764#issuecomment-1614832260), I'd consider making a GitHub repo instead.

>  intelGraphic output primary display instead nvidia output in your windows setting

Are you doing this by disabling your GPU's device in `Device Manager`, under `Display adapters`?

**Comment by mpl** [comment]
> Is this an accurate summary of the CGO DLL problem?
> 
> Status	App kind	Technique	Notes
> ✅	Standalone Dart on Windows	Dart FFI	
> ✅	Flutter Windows app using Intel graphics driver	Dart FFI	[#129764 (comment)](https://github.com/flutter/flutter/issues/129764#issuecomment-1630229570)
> ❌	Flutter Windows app using NVIDIA graphics driver	Dart FFI	[#129764 (comment)](https://github.com/flutter/flutter/issues/129764#issuecomment-1630229570)
> ✅	Flutter Windows app	Dynamic linking	[#129764 (comment)](https://github.com/flutter/flutter/issues/129764#issuecomment-1632263077)

Almost. On the last line, the technique is still Dart FFI (i.e. I'm still calling ffi.DynamicLibrary.open , in the same way we're doing for the three other cases). Only, it looks like it only works because I am _also_ beforehand dynamic linking everything that is going to be needed (just like I would do if I wanted to the invoke the functions through the platform channels).

> @mpl Could you create a minimal repro of a Flutter Windows app using Dart FFI on a CGO DLL? FYI, Windows Defender flagged your [superproject.zip above](https://github.com/flutter/flutter/issues/129764#issuecomment-1614832260), I'd consider making a GitHub repo instead.

Sure, will do. Although if you're willing to bet that Windows Defender is an idiot, you could just take my .zip and create the repo with it ;)
But no worries, I'll do it later on tonight or tomorrow.

> > intelGraphic output primary display instead nvidia output in your windows setting
> 
> Are you doing this by disabling your GPU's device in `Device Manager`, under `Display adapters`?

yep. and AFAIR, you don't even need to reboot for that trick to take effect as far as flutter is concerned.

**Comment by mpl** [comment]
@loic-sharma there you go: https://github.com/mpl/superproject
