### ISSUE TITLE
[tool_crash] _TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))

### ISSUE THREAD

**Issue by arimateiaoliveira** [flutter/flutter#129772]
## Command
```
flutter build appbundle --analyze-size --target-platform android-arm
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))
```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:508:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildAab (package:flutter_tools/src/android/gradle.dart:228:5)
<asynchronous suspension>
#11     BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:153:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-BR)
    • Flutter version 3.10.5 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at 
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.base_app_module
**iOS bundle identifier**: com.example.baseAppModule
**Creation channel**: stable
**Creation framework version**: 9944297138845a94256f1cf37beb88ff9a8e811a
### Plugins
device_info_plus-9.0.2
external_app_launcher-3.1.0
flutter_web_auth-0.5.0
fluttertoast-8.2.2
package_info_plus-4.0.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
share_files_and_screenshot_widgets-1.0.6
share_plus-7.0.2
shared_preferences-2.1.2
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
smart_auth-1.0.8
url_launcher-6.1.11
url_launcher_android-6.0.36
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6
webview_flutter-4.2.2
webview_flutter_android-3.8.0
webview_flutter_wkwebview-3.6.0

**Comment by dam-ease** [comment]
Hi @arimateiaoliveira 
There was a similar report recently and has been fixed on Dart side (see https://github.com/flutter/flutter/issues/128402). It's available on the latest master channel now, so please switch to master and retry.

```
flutter channel master
flutter upgrade
```

Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/128402. Could also be a possible duplicate of https://github.com/flutter/flutter/issues/129706. Thanks!
