### ISSUE TITLE
[tool_crash] _TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))

### ISSUE THREAD

**Issue by galunecandrey** [flutter/flutter#129704]
## Command
```
flutter build macos --build-name=23.6.28 --build-number=2060 --analyze-size --code-size-directory /Users/visionable/bitbucket-runner/temp/14ef2ece-6c36-58df-82f8-9c6873a20375/build --dart-define=ServiceHost=https://app.visionable.one --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))
```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:61:59)
#8      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:160:60)
<asynchronous suspension>
#9      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
```
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/visionable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 13.4.1 22F82 darwin-arm64 (Rosetta)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.0+15
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
app_links-3.4.3
app_settings-4.2.0
audio_session-0.1.16
audioplayers-4.1.0
audioplayers_android-3.0.2
audioplayers_darwin-4.1.0
audioplayers_linux-2.1.0
audioplayers_web-3.1.0
audioplayers_windows-2.0.2
connectivity_plus-4.0.1
desktop_lifecycle-0.1.1
desktop_sleep
desktop_window-0.4.0
file_picker-5.3.2
firebase_core-2.14.0
firebase_core_web-2.6.0
firebase_messaging-14.6.3
firebase_messaging_web-3.5.3
flutter_app_badger-1.5.0
flutter_local_notifications-14.1.1
flutter_plugin_android_lifecycle-2.0.15
flutter_udid-2.0.1
integration_test
meeting_sdk
notification_module
package_info_plus-4.0.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
permission_handler-10.3.0
permission_handler_android-10.2.3
permission_handler_apple-9.1.0
permission_handler_windows-0.1.2
realm-1.2.0
sentry_flutter-7.8.0
system_tools
system_tray-2.0.3
url_launcher-6.1.11
url_launcher_android-6.0.35
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
win_local_notifier

**Comment by galunecandrey** [comment]
@danagbemava-nc it does not help
https://github.com/flutter/flutter/issues/129706
