### ISSUE TITLE
FloatingActionButton Hero error

### ISSUE THREAD

**Issue by darkstarx** [flutter/flutter#129892]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create two pages with FAB. One of them is opening from another one.
2. Make any button on the second page which calls the async function on tap; this function hides the FAB for a while, shows it and pops the page.
3. The operation must be not longer than the FAB animation duration (let's take 100ms).

### Expected results

The second page hides, the first page has emerging FAB (since heroTags are equal).

### Actual results

The second page hides, the first page has not FAB because of the error: `There are multiple heroes that share the same tag within a subtree.`

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';


void main()
{
  runApp(const MyApp());
}


class MyApp extends StatelessWidget
{
  const MyApp({ super.key });

  @override
  Widget build(final BuildContext context)
  {
    return MaterialApp(
      routes: {
        '/page1': (context) => const Page1(),
        '/page2': (context) => const Page2(),
      },
      initialRoute: '/page1',
    );
  }
}


class Page1 extends StatelessWidget
{
  const Page1({ super.key });

  @override
  Widget build(final BuildContext context)
  {
    return Scaffold(
      appBar: AppBar(title: const Text('Page1')),
      body: Center(
        child: OutlinedButton(
          onPressed: () {
            Navigator.of(context).pushNamed('/page2');
          },
          child: const Text('Open Page2'),
        )
      ),
      floatingActionButton: FloatingActionButton(
        key: const ValueKey(1),
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }
}


class Page2 extends StatefulWidget
{
  const Page2({ super.key });

  @override
  State<Page2> createState() => _Page2State();
}


class _Page2State extends State<Page2>
{
  @override
  Widget build(final BuildContext context)
  {
    return Scaffold(
      appBar: AppBar(title: const Text('Page2')),
      body: Center(
        child: OutlinedButton(
          onPressed: () async {
            setState(() => _processing = true);
            await Future.delayed(const Duration(milliseconds: 100));
            setState(() => _processing = false);
            SchedulerBinding.instance.addPostFrameCallback((_) {
              if (context.mounted) Navigator.of(context).pop();
            });
          },
          child: const Text('Do async op'),
        )
      ),
      floatingActionButton: _processing ? null : FloatingActionButton(
        key: const ValueKey(2),
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }

  bool _processing = false;
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/3534966/643dee15-9e81-4a26-8097-887b0741fcb5

</details>

### Logs

<details><summary>Logs</summary>

```console
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
Here is the subtree for one of the offending heroes: Hero
    tag: <default FloatingActionButton tag>
    state: _HeroState#7d0de
When the exception was thrown, this was the stack
#0      Hero._allHeroesFor.inviteHero.<anonymous closure>
#1      Hero._allHeroesFor.inviteHero
#2      Hero._allHeroesFor.visitor
#3      SingleChildRenderObjectElement.visitChildren
#4      Hero._allHeroesFor.visitor
#5      ComponentElement.visitChildren
#6      Hero._allHeroesFor.visitor
#7      SingleChildRenderObjectElement.visitChildren
#8      Hero._allHeroesFor.visitor
#9      ComponentElement.visitChildren
#10     Hero._allHeroesFor.visitor
#11     SingleChildRenderObjectElement.visitChildren
#12     Hero._allHeroesFor.visitor
#13     ComponentElement.visitChildren
#14     Hero._allHeroesFor.visitor
#15     MultiChildRenderObjectElement.visitChildren
#16     Hero._allHeroesFor.visitor
#17     ComponentElement.visitChildren
#18     Hero._allHeroesFor.visitor
#19     ComponentElement.visitChildren
#20     Hero._allHeroesFor.visitor
#21     ComponentElement.visitChildren
#22     Hero._allHeroesFor.visitor
#23     MultiChildRenderObjectElement.visitChildren
#24     Hero._allHeroesFor.visitor
#25     ComponentElement.visitChildren
#26     Hero._allHeroesFor.visitor
#27     ComponentElement.visitChildren
#28     Hero._allHeroesFor.visitor
#29     ComponentElement.visitChildren
#30     Hero._allHeroesFor.visitor
#31     ComponentElement.visitChildren
#32     Hero._allHeroesFor.visitor
#33     ComponentElement.visitChildren
#34     Hero._allHeroesFor.visitor
#35     SingleChildRenderObjectElement.visitChildren
#36     Hero._allHeroesFor.visitor
#37     ComponentElement.visitChildren
#38     Hero._allHeroesFor.visitor
#39     SingleChildRenderObjectElement.visitChildren
#40     Hero._allHeroesFor.visitor
#41     ComponentElement.visitChildren
#42     Hero._allHeroesFor.visitor
#43     ComponentElement.visitChildren
#44     Hero._allHeroesFor.visitor
#45     ComponentElement.visitChildren
#46     Hero._allHeroesFor.visitor
#47     ComponentElement.visitChildren
#48     Hero._allHeroesFor.visitor
#49     ComponentElement.visitChildren
#50     Hero._allHeroesFor.visitor
#51     ComponentElement.visitChildren
#52     Hero._allHeroesFor.visitor
#53     ComponentElement.visitChildren
#54     Hero._allHeroesFor.visitor
#55     ComponentElement.visitChildren
#56     Hero._allHeroesFor.visitor
#57     ComponentElement.visitChildren
#58     Hero._allHeroesFor.visitor
#59     SingleChildRenderObjectElement.visitChildren
#60     Hero._allHeroesFor.visitor
#61     ComponentElement.visitChildren
#62     Hero._allHeroesFor.visitor
#63     SingleChildRenderObjectElement.visitChildren
#64     Element.visitChildElements
#65     Hero._allHeroesFor
#66     HeroController._startHeroTransition
#67     HeroController._maybeStartHeroTransition.<anonymous closure>
#68     SchedulerBinding._invokeFrameCallback
#69     SchedulerBinding.handleDrawFrame
#70     SchedulerBinding._handleDrawFrame
#71     _invoke (dart:ui/hooks.dart:142:13)
#72     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#73     _drawFrame (dart:ui/hooks.dart:112:31)
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.1 22C65 darwin-x64, locale ru-RU)
    • Flutter version 3.10.5 on channel stable at /opt/flutter2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sergey/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • 5D8DA38D-7AFB-44EF-885F-C320A68B77E3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)   • macos                                • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @darkstarx, can you try adding a delay before popping the current route to see if you still get the issue?

**Comment by darkstarx** [comment]
> Hi @darkstarx, can you try adding a delay before popping the current route to see if you still get the issue?

Sure, I did this first thing when I diagnosed the error. If the async function lasts longer the FAB animation (say, 300ms is enough), you won't get this error. But the point is that I don't know how long the function will last 'cause it depends on backend respond or some other unpredictable things.
Measuring the execution time and adjusting the function duration with Future.delayed is not a good solution. I need the page to be closed as soon as possible, I can't wait for some extra time just because some implicit widget can't handle the situation correctly. Anyway, that's not an obvious solution for other people who will probably face with this situation.

**Comment by danagbemava-nc** [comment]
Hi @darkstarx, if you need the page to be closed as soon as possible you should be able to just call Navigator.pop(context) in the .then method of the future. 

It seems like updating the state before popping the route is causing the issue with the FAB.

I tried setting different hero-tags for the FAB but the error was still thrown.

Labeling for further investigation. 

<details>
<summary>updated sample</summary>


```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(final BuildContext context) {
    return MaterialApp(
      routes: {
        '/page1': (context) => const Page1(),
        '/page2': (context) => const Page2(),
      },
      initialRoute: '/page1',
    );
  }
}

class Page1 extends StatelessWidget {
  const Page1({super.key});

  @override
  Widget build(final BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Page1')),
      body: Center(
        child: OutlinedButton(
          onPressed: () {
            Navigator.of(context).pushNamed('/page2');
          },
          child: const Text('Open Page2'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        key: const ValueKey(1),
        heroTag: '<page 1 hero tag/>',
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }
}

class Page2 extends StatefulWidget {
  const Page2({super.key});

  @override
  State<Page2> createState() => _Page2State();
}

class _Page2State extends State<Page2> {
  @override
  Widget build(final BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Page2')),
      body: Center(
        child: OutlinedButton(
          onPressed: () async {
            setState(() => _processing = true);

            await Future.delayed(const Duration(milliseconds: 100)).then((value) {
              if (context.mounted) {
                // uncomment this to see the error
                // setState(() {
                //   _processing = false;
                // });

                Navigator.of(context).pop();
              }
            });
          },
          child: const Text('Do async op'),
        ),
      ),
      floatingActionButton: _processing
          ? null
          : FloatingActionButton(
              key: const ValueKey(2),
              onPressed: () {},
              heroTag: '<page 2 hero tag/>',
              child: const Icon(Icons.add),
            ),
    );
  }

  bool _processing = false;
}
```

</details>

<details>
<summary>logs</summary>

```
Restarted application in 1,045ms.
Reloaded 1 of 1088 libraries in 157ms (compile: 53 ms, reload: 71 ms, reassemble: 5 ms).
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: There are multiple heroes that share the same tag within a subtree.
flutter: Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must
flutter: have a unique non-null tag.
flutter: In this case, multiple heroes had the following tag: <page 2 hero tag/>
flutter: ├# Here is the subtree for one of the offending heroes: Hero
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:278:11)
flutter: #1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:289:8)
flutter: #2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:307:11)
flutter: #3      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6420:14)
flutter: #4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:322:15)
flutter: #5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5349:14)
flutter: #6      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:322:15)
flutter: #7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6420:14)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-GB)
    • Flutter version 3.10.5 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.12.0-13.0.pre.40, on macOS 13.4.1 22F82 darwin-arm64, locale en-GB)
    • Flutter version 3.12.0-13.0.pre.40 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ddb16b7d92 (12 hours ago), 2023-07-03 14:27:33 -0400
    • Engine revision 987b621eac
    • Dart version 3.1.0 (build 3.1.0-262.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>
