### ISSUE TITLE
packages failing to install on devicelab linux Ubuntu 20 hosts

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#129857]
ID: packages
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2385, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1280, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 1703, in installed
                  result = _find_install_targets(
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 584, in _find_install_targets
                  desired = _repack_pkgs(pkgs, normalize=normalize)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/pkg_resource.py", line 38, in _repack_pkgs
                  raise SaltInvocationError(
              salt.exceptions.SaltInvocationError: You are passing a list of packages that contains duplicated packages names: ['autoconf', 'automake', 'bison', 'build-essential', 'flex', 'gettext', 'gperf', 'groff', 'libtool', 'pkg-config', 'wget', 'acpica-tools', 'build-essential', 'curl', 'dejagnu', 'dosfstools', 'g++-multilib', 'ifupdown', 'libblkid-dev', 'libc6-dev-i386', 'libedit-dev', 'libegl1-mesa', 'libfreetype6-dev', 'libgles2-mesa-dev', 'libglib2.0-dev', 'libglu1-mesa-dev', 'libgtk-3-dev', 'liblz4-tool', 'libncurses5-dev', 'libssl-dev', 'libx11-dev', 'libxcursor-dev', 'libxinerama-dev', 'libxrandr-dev', 'libxxf86vm-dev', 'lsof', 'mesa-common-dev', 'mtools', 'nasm', 'net-tools', 'python3-dev', 'swig', 'tcpdump', 'texinfo', 'unzip', 'uuid-dev', 'vim', 'xvfb', 'xz-utils', 'zip', 'zlib1g-dev']. This cannot be processed. In case you are targeting different versions of the same package, please target them individually

**Comment by yusuf-goog** [comment]
fix in go/di-cl/1601
