### ISSUE TITLE
_TypeError: type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by aleliottasyn** [flutter/flutter#129835]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

## command

flutter run -d chrome --web-port 8083

### Expected results

No Error

## exception

_TypeError: type 'Null' is not a subtype of type 'String' in type cast

```
#0      ChromeProxyService._setUpChromeConsoleListeners.<anonymous closure> (package:dwds/src/services/chrome_proxy_service.dart:1111:49)
#1      _rootRunUnary (dart:async/zone.dart:1407:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#4      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#5      _rootRunUnary (dart:async/zone.dart:1407:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#12     WipDomain.eventStream.<anonymous closure>.<anonymous closure> (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:377:22)
#13     _HandlerEventSink.add (dart:async/stream_transformers.dart:209:17)
#14     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#15     _rootRunUnary (dart:async/zone.dart:1407:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#19     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#20     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#21     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#22     _rootRun (dart:async/zone.dart:1391:47)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _rootRun (dart:async/zone.dart:1399:13)
#27     _CustomZone.run (dart:async/zone.dart:1301:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#33     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
[flutter_08.log](https://github.com/flutter/flutter/files/11917441/flutter_08.log)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.10.5, on macOS 12.2.1 21D62 darwin-x64, locale it-IT)
    [32m•[39m Flutter version 3.10.5 on channel stable at /Users/alessioliotta/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 796c8ef792 (2 weeks ago), 2023-06-13 15:51:02 -0700
    [32m•[39m Engine revision 45f6e00911
    [32m•[39m Dart version 3.0.5
    [32m•[39m DevTools version 2.23.1

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    [32m•[39m Android SDK at /Users/alessioliotta/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[32m[✓][39m VS Code (version 1.79.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.66.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.
```

</details>

**Comment by aleliottasyn** [comment]
## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+9
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
flutter_secure_storage-8.0.0
flutter_secure_storage_linux-1.1.3
flutter_secure_storage_macos-3.0.0
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-2.0.0
package_info_plus-4.0.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11

**Comment by huycozy** [comment]
Hi @aleliottasyn,
I see there's an open issue in `dart-lang/webdev` repository that is addressing the case you described https://github.com/dart-lang/webdev/issues/2161.

Closing this issue in favor of that one, so please follow up on it for further updates. Thanks!
