### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by EddieKe** [flutter/flutter#129994]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:200:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:191:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:169:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:871:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:520:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:308:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3086], locale en-US)
    [32m•[39m Flutter version 3.10.5 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    [32m•[39m Engine revision 45f6e00911
    [32m•[39m Dart version 3.0.5
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[31m[✗][39m Android toolchain - develop for Android devices
    [32m•[39m Android SDK at C:\Users\Latitude\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[33m[!][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m VS Code (version 1.79.2)
    [32m•[39m VS Code at C:\Users\Latitude\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.68.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3086]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.58

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 90c64ed42ba53a52d18f0cb3b17666c8662ed2a0
### Plugins
cloud_firestore-4.8.0
cloud_firestore_web-3.6.0
firebase_auth-4.6.2
firebase_auth_web-5.5.2
firebase_core-2.13.1
firebase_core_web-2.5.0
firebase_storage-11.2.2
firebase_storage_web-3.6.2
flutter_plugin_android_lifecycle-2.0.15
google_maps_flutter-2.2.8
google_maps_flutter_android-2.4.15
google_maps_flutter_ios-2.2.3
google_sign_in-5.4.4
google_sign_in_android-6.1.14
google_sign_in_ios-5.6.2
google_sign_in_web-0.10.2+1
image_picker-0.8.7+5
image_picker_android-0.8.6+15
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+4
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.6

**Comment by EddieKe** [comment]
I keep getting this issue

**Comment by danagbemava-nc** [comment]
Hi @EddieKe, can you retry on the latest master channel to see if you still face this issue? 

You can switch to the master channel by running 

```
flutter channel master
flutter upgrade
```

If you still face this issue after switching to the master channel, please provide the flutter doctor output of the master channel. 

Thank you
