### ISSUE TITLE
Windows Build fails with error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32

### ISSUE THREAD

**Issue by angularsen** [flutter/flutter#129997]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
flutter create app
cd app
flutter run -d windows
```

Followed getting started instructions:
https://docs.flutter.dev/platform-integration/desktop

Environment: 
- Windows 11
- Visual Studio 2022 + `Desktop development with C++` workload 
- Also tried VS 2019 with the same workload, but got the same error as shown in logs in this issue.

### Expected results

Expected to run Flutter app on Windows.

### Actual results

error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32

```
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 05.07.2023 13:05:28.
    Project "C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32. [C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj]
    Done Building Project "C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32. [C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.12


  Exit code: 1
```

<details><summary>VCTargetsPath.vcxproj only contains Debug|x64:</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup Label="ProjectConfigurations">
		<ProjectConfiguration Include="Debug|x64">
			<Configuration>Debug</Configuration>
			<Platform>x64</Platform>
		</ProjectConfiguration>
	</ItemGroup>
	<PropertyGroup Label="Globals">
		<ProjectGuid>{F3FC6D86-508D-3FB1-96D2-995F08B142EC}</ProjectGuid>
		<Keyword>Win32Proj</Keyword>
		<Platform>x64</Platform>
		<WindowsTargetPlatformVersion>10.0.19041.0</WindowsTargetPlatformVersion>
	</PropertyGroup>
	<Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props"/>
	<PropertyGroup>
		<PreferredToolArchitecture>x64</PreferredToolArchitecture>
	</PropertyGroup>
	<PropertyGroup Label="Configuration">
		<ConfigurationType>Utility</ConfigurationType>
		<CharacterSet>MultiByte</CharacterSet>
		<PlatformToolset>v142</PlatformToolset>
	</PropertyGroup>
	<Import Project="$(VCTargetsPath)\Microsoft.Cpp.props"/>
	<ItemDefinitionGroup>
		<PostBuildEvent>
			<Command>echo VCTargetsPath=$(VCTargetsPath)</Command>
		</PostBuildEvent>
	</ItemDefinitionGroup>
	<Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets"/>
</Project>
```

</details>

### Code sample

None

### Screenshots or Video

None

### Logs

<details><summary>Logs</summary>

```console
flutter run

Connected devices:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199
Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.58
[1]: Windows (windows)
[2]: Chrome (chrome)
[3]: Edge (edge)
```

```console
flutter --verbose run -d windows


$ flutter --verbose run -d windows
[   +2 ms] executing: [C:\dev\_deps\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 796c8ef79279f9c774545b3771238c3098dbefab
[        ] executing: [C:\dev\_deps\flutter/] git tag --points-at 796c8ef79279f9c774545b3771238c3098dbefab
[  +39 ms] Exit code 0 from: git tag --points-at 796c8ef79279f9c774545b3771238c3098dbefab
[        ] 3.10.5
[   +1 ms] executing: [C:\dev\_deps\flutter/] git rev-parse --abbrev-ref HEAD
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +31 ms] executing: [C:\dev\_deps\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\dev\_deps\flutter/] git ls-remote --get-url origin
[  +22 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +63 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +42 ms] Skipping pub get: version match.
[  +94 ms] Generating C:\dev\core\temp\app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +59 ms] Initializing file store
[   +5 ms] Skipping target: gen_localizations
[   +3 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: C:\dev\core\temp\app\.dart_tool\package_config_subset}
[  +16 ms] gen_dart_plugin_registrant: Complete
[   +2 ms] Skipping target: _composite
[   +1 ms] complete
[   +4 ms] Launching lib\main.dart on Windows in debug mode...
[   +2 ms] C:\dev\_deps\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\dev\_deps\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\dev\_deps\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/45f6e009110df4f34ec2cf99f63cf73b71b7a420/ --output-dill
C:\Users\andre\AppData\Local\Temp\flutter_tools.b73c91ef\flutter_tool.fb6ab1e0\app.dill --packages C:\dev\core\temp\app\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\4d25a1cda3833f76c80232d3b1a3704b.cache.dill.track.dill
--verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +19 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +37 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "911b58cd",
               "installDate": "2023-07-03T18:20:37Z",
               "installationName": "VisualStudio/16.11.27+33801.447",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.11.33801.447",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelId": "VisualStudio.16.Release",
               "installedChannelUri": "https://aka.ms/vs/16/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.11#16.11.27",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2023-07-03T18:20:37.7482158Z",
               "catalog": {
                 "buildBranch": "d16.11",
                 "buildVersion": "16.11.33801.447",
                 "id": "VisualStudio/16.11.27+33801.447",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.11.27",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "27",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.11.27+33801.447",
                 "requiredEngineVersion": "2.11.72.18200"
               },
               "properties": {
                 "campaignId": "69173160879",
                 "channelManifestId": "VisualStudio.16.Release/16.11.27+33801.447",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +2 ms] Building Windows application...
[  +10 ms] <- compile package:app/main.dart
[   +1 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S C:\dev\core\temp\app\windows -B
build\windows -G Visual Studio 16 2019
[  +37 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
[ +234 ms] CMake Error at CMakeLists.txt:3 (project):
[   +2 ms]   Failed to run MSBuild command:
[   +1 ms]     C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe
[        ]   to get the value of VCTargetsPath:
[        ]     Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
[        ]     Copyright (C) Microsoft Corporation. All rights reserved.
[        ]     Build started 05.07.2023 12:59:32.
[        ]     Project "C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj" on node 1 (default targets).
[        ]     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: This project doesn't contain the
Configuration and Platform combination of Debug|Win32. [C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj]
[        ]     Done Building Project "C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj" (default targets) -- FAILED.
[        ]     Build FAILED.
[        ]     "C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj" (default target) (1) ->
[        ]     (PrepareForBuild target) ->
[        ]       C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: This project doesn't contain the
Configuration and Platform combination of Debug|Win32. [C:\dev\core\temp\app\build\windows\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj]
[        ]         0 Warning(s)
[        ]         1 Error(s)
[        ]     Time Elapsed 00:00:00.13
[        ]   Exit code: 1
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "C:/dev/core/temp/app/build/windows/CMakeFiles/CMakeOutput.log".
[   +7 ms] Building Windows application... (completed in 297ms)
[+4632 ms] Exception: Unable to generate build files
[   +2 ms] "flutter run" took 5 292ms.
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +28 ms] ensureAnalyticsSent: 25ms
[        ] Running 1 shutdown hook
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**CMakeOutput.log**
```
The system is: Windows - 10.0.22621 - AMD64
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale nb-NO)
    • Flutter version 3.10.5 on channel stable at C:\dev\_deps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\andre\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Users\andre\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.27)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.33801.447
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Users\andre\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at C:\Users\andre\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.58

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @angularsen 
I checked this on my Windows 11 but it ran well without issue. Is this the first time you see this issue or after upgrading OS/Flutter SDK?

Could you try this again in `profile` or `release` mode to see if the issue still persists or not?

**Comment by angularsen** [comment]
@huycozy Same error with `--release` and `--profile` flags.
I also tried in PowerShell 7, Cmd and Git Bash shells.
Tried `flutter clean` in between.

I am new to Flutter and started testing it a few weeks ago, following the current getting started guide. 

I tried on 2 computers, both running Win11 with Visual Studio 2022 Community installed. 
Not sure if relevant, but am running Norwegian culture on both.

Am a bit at a loss on what next to try.

**Comment by huycozy** [comment]
Thanks for your response. This could be a VisualStudio issue ([MSBuild error MSB8013](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8013?view=vs-2022)). I will label this for more information from others.

**Comment by angularsen** [comment]
@huycozy Breakthrough! I restarted Windows and now it builds just fine. 

There were no messages during Visual Studio installer steps, or instructions in the getting started guide to hint that a reboot was required, but apparently this may be required.

Confirmed both computers worked after a reboot.

**Comment by angularsen** [comment]
@huycozy Digging more, reboot was not it.

Today I created the app in a different path, outside our existing .NET project structure. That's what made it work.

Found it was due to this file existing in the root of the project structure:

**Directory.Build.props**
```xml
@@ -1,19 +0,0 @@
<Project>
  <PropertyGroup>
    <Platform>AnyCPU</Platform>
    <LangVersion>default</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- CS1591: Missing XML comment for publicly visible type or member -->
    <NoWarn>$(NoWarn);1591</NoWarn>
    <WarningsAsErrors>
      CS4014, <!-- CS4014: Async method invocation without await expression -->
    </WarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <SolutionDir Condition="'$(SolutionDir)' == ''">$(MSBuildThisFileDirectory)</SolutionDir>
  </PropertyGroup>

  <Import Condition="$(MSBuildProjectName.EndsWith('Tests'))" Project="$(MSBuildThisFileDirectory)Common.TestProject.props" />
</Project>
```

This file, by design, affects all projects in subfolders.

Turns out, `<Platform>AnyCPU</Platform>` was the offending line. It did not play well with Flutter's use of msbuild.

**Comment by angularsen** [comment]
Workaround for disabling msbuild properties set by `Directory.Build.props` file in any of the parent directories:
- Add new `Directory.Build.props` file in Flutter project dir with this content

```xml
<Project>
</Project>
```

MSBuild looks for the nearest `Directory.Build.props` file in the directory structure, so adding an empty one will clear any values set higher up.

**Comment by huycozy** [comment]
Glad you solved this. Your workaround above may be helpful for someone who looks into this later. Thanks for sharing!
