### ISSUE TITLE
Exception caught by services library

### ISSUE THREAD

**Issue by Leszek-Cierniak** [flutter/flutter#129908]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The bug is not stopping my program. It seems to be inside Flutter/Dart.
I will try to find a cause, but in meantime lets take a look at what is reported.

### Expected results

My program starts with no exception.

### Actual results

```
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
√  Built build\windows\runner\Debug\events.exe.
Debug service listening on ws://127.0.0.1:51338/27aod3uTSGw=/ws
Syncing files to device Windows...
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#5568e(logicalKey: LogicalKeyboardKey#d0ba2(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), physicalKey: PhysicalKeyboardKey#ea6e1(usbHidUsage: "0x000700e0", debugName: "Control Left"), repeat: false) and its data: RawKeyEventDataWindows#d1085(keyCode: 162, scanCode: 29, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 695 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:695:7)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1018:30)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:492:35)
#6      _invoke2 (dart:ui/hooks.dart:202:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:130:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:727:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

### Code sample

no code - it looks like a Flutter/Dart internal issue.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
PS D:\projects.flutter\events> flutter doctor -v
[√] Flutter (Channel beta, 3.12.0-1.1.pre, on Microsoft Windows [Version 10.0.19045.3086], locale pl-PL)
    • Flutter version 3.12.0-1.1.pre on channel beta at D:\developer\flutter                            
    • Upstream repository https://github.com/flutter/flutter.git                                        
    • Framework revision e2e0aa7037 (12 days ago), 2023-06-20 19:48:59 -0700                            
    • Engine revision 45712dd2f1                                                                        
    • Dart version 3.1.0 (build 3.1.0-163.1.beta)                                                       
    • DevTools version 2.24.0                                                                           
                                                                                                        
[√] Windows Version (Installed version of Windows is version 10 or higher)                              
                                                                          
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at D:\IntelliJ IDEA Community Edition 2021.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G955F (mobile) • ce0517153acc7b1e01 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19045.3086]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 114.0.1823.58

[√] Network resources
    • All expected network resources are available.

• No issues found!

</details>

**Comment by darshankawar** [comment]
Looking at the error log, it most probably is same as https://github.com/flutter/flutter/issues/107972, so please follow-up in it for further updates.
Closing this as a duplicate.
