### ISSUE TITLE
Flutter Bug Filing

### ISSUE THREAD

**Issue by anirbangoa** [flutter/flutter#129922]
```
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Column Column:file:///F:/MobileApp/mydashboard/lib/screens/formistcollections.dart:24:18
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1966:12)
#3      RenderBox.paintBounds (package:flutter/src/rendering/box.dart:2633:41)
#4      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:56)
#5      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#6      PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:264:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:245:7)
#8      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2879:15)
#9      RenderFlex.paint (package:flutter/src/rendering/flex.dart:1040:7)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#12     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#15     _RenderSingleChildViewport.paint.paintContents (package:flutter/src/widgets/single_child_scroll_view.dart:535:17)
#16     _RenderSingleChildViewport.paint (package:flutter/src/widgets/single_child_scroll_view.dart:549:9)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#18     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#19     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#20     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:264:7)
#21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:245:7)
#22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#37     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#40     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#42     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#43     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#44     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:264:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:245:7)
#46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#47     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:618:11)
#48     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#50     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#52     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#53     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#54     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:264:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:245:7)
#56     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2879:15)
#57     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#60     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#61     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:664:11)
#62     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#63     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#64     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#65     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2076:15)
#66     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:562:14)
#67     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2063:21)
#68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#70     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#73     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#74     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#75     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#76     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#77     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:264:7)
#78     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:245:7)
#79     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#82     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#83     _ZoomExitTransitionPainter.paint (package:flutter/src/material/page_transitions_theme.dart:995:23)
#84     _RenderSnapshotWidget.paint (package:flutter/src/widgets/snapshot_widget.dart:335:15)
#85     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#86     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#87     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#88     _ZoomEnterTransitionPainter.paint (package:flutter/src/material/page_transitions_theme.dart:923:23)
#89     _RenderSnapshotWidget.paint (package:flutter/src/widgets/snapshot_widget.dart:335:15)
#90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#91     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#92     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#93     _ZoomExitTransitionPainter.paint (package:flutter/src/material/page_transitions_theme.dart:995:23)
#94     _RenderSnapshotWidget.paint (package:flutter/src/widgets/snapshot_widget.dart:335:15)
#95     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#96     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#97     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#98     _ZoomEnterTransitionPainter.paint (package:flutter/src/material/page_transitions_theme.dart:923:23)
#99     _RenderSnapshotWidget.paint (package:flutter/src/widgets/snapshot_widget.dart:335:15)
#100    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#101    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#102    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#103    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#104    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#105    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#106    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1147:31)
#107    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494:19)
#108    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#109    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#110    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#111    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#112    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#113    _invoke (dart:ui/hooks.dart:142:13)
#114    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#115    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderFlex#2627f relayoutBoundary=up12
...  needs compositing
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...  size: Size(411.4, 230.0)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: start
...  textDirection: ltr
...  verticalDirection: down
RenderObject: RenderFlex#2627f relayoutBoundary=up12
  needs compositing
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  size: Size(411.4, 230.0)
  direction: vertical
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: start
  textDirection: ltr
  verticalDirection: down
...  child 1: RenderConstrainedBox#eae7d relayoutBoundary=up13
...    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...    size: Size(0.0, 50.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=50.0)
...  child 2: RenderFlex#c0b36 relayoutBoundary=up13
...    parentData: offset=Offset(0.0, 50.0); flex=null; fit=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...    size: Size(411.4, 27.0)
...    direction: horizontal
...    mainAxisAlignment: start
...    mainAxisSize: max
...    crossAxisAlignment: center
...    textDirection: ltr
...    verticalDirection: down
...    child 1: RenderConstrainedBox#f60d4 relayoutBoundary=up14
...      parentData: offset=Offset(0.0, 13.5); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(40.0, 0.0)
...      additionalConstraints: BoxConstraints(w=40.0, 0.0<=h<=Infinity)
...    child 2: RenderSemanticsAnnotations#1c8a4 relayoutBoundary=up14
...      parentData: offset=Offset(40.0, 2.5); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(17.0, 22.0)
...      child: RenderImage#7d311 relayoutBoundary=up15
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(unconstrained)
...        size: Size(17.0, 22.0)
...        image: [17×22]
...        alignment: Alignment.center
...        invertColors: false
...        filterQuality: low
...    child 3: RenderConstrainedBox#45985 relayoutBoundary=up14
...      parentData: offset=Offset(57.0, 13.5); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(60.0, 0.0)
...      additionalConstraints: BoxConstraints(w=60.0, 0.0<=h<=Infinity)
...    child 4: RenderParagraph#460eb relayoutBoundary=up14
...      parentData: offset=Offset(117.0, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(148.0, 27.0)
...      textAlign: start
...      textDirection: ltr
...      softWrap: wrapping at box width
...      overflow: clip
...      locale: en_US
...      maxLines: unlimited
...      text: TextSpan
...        debugLabel: ((englishLike bodyMedium 2014).merge((blackMountainView bodyMedium).apply)).merge(unknown)
...        inherit: false
...        color: Color(0xff59706f)
...        family: Poppins
...        size: 18.0
...        weight: 500
...        baseline: alphabetic
...        decoration: TextDecoration.none
...        "Cash Statement"
...  child 3: RenderConstrainedBox#99f71 relayoutBoundary=up13
...    parentData: offset=Offset(0.0, 77.0); flex=null; fit=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...    size: Size(0.0, 15.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=15.0)
...  child 4: RenderFlex#9c998 relayoutBoundary=up13
...    needs compositing
...    parentData: offset=Offset(0.0, 92.0); flex=null; fit=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...    size: Size(411.4, 62.0)
...    direction: horizontal
...    mainAxisAlignment: center
...    mainAxisSize: max
...    crossAxisAlignment: center
...    textDirection: ltr
...    verticalDirection: down
...    child 1: RenderConstrainedBox#d1394 relayoutBoundary=up14
...      needs compositing
...      parentData: offset=Offset(65.7, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(120.0, 62.0)
...      additionalConstraints: BoxConstraints(w=120.0, 0.0<=h<=Infinity)
...      child: RenderMouseRegion#dd397 relayoutBoundary=up15
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=120.0, 0.0<=h<=Infinity)
...        size: Size(120.0, 62.0)
...        behavior: opaque
...        listeners: enter, exit
...        cursor: SystemMouseCursor(text)
...        child: RenderTapRegion#2ab26 relayoutBoundary=up16
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=120.0, 0.0<=h<=Infinity)
...          size: Size(120.0, 62.0)
...          behavior: deferToChild
...          groupId: EditableText
...    child 2: RenderConstrainedBox#1b4fc relayoutBoundary=up14
...      parentData: offset=Offset(185.7, 31.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(40.0, 0.0)
...      additionalConstraints: BoxConstraints(w=40.0, 0.0<=h<=Infinity)
...    child 3: RenderConstrainedBox#750a3 relayoutBoundary=up14
...      needs compositing
...      parentData: offset=Offset(225.7, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(120.0, 62.0)
...      additionalConstraints: BoxConstraints(w=120.0, 0.0<=h<=Infinity)
...      child: RenderMouseRegion#15a21 relayoutBoundary=up15
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=120.0, 0.0<=h<=Infinity)
...        size: Size(120.0, 62.0)
...        behavior: opaque
...        listeners: enter, exit
...        cursor: SystemMouseCursor(text)
...        child: RenderTapRegion#43cf6 relayoutBoundary=up16
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=120.0, 0.0<=h<=Infinity)
...          size: Size(120.0, 62.0)
...          behavior: deferToChild
...          groupId: EditableText
...  child 5: RenderConstrainedBox#e0ac2 relayoutBoundary=up13
...    parentData: offset=Offset(0.0, 154.0); flex=null; fit=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...    size: Size(0.0, 40.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=40.0)
...  child 6: RenderRepaintBoundary#72b55 relayoutBoundary=up13 NEEDS-PAINT
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...    layer: OffsetLayer#3b15d DETACHED
...      handles: 1
...      offset: Offset(0.0, 0.0)
...    size: MISSING
...    metrics: 0.0% useful (1 bad vs 0 good)
...    diagnosis: insufficient data to draw conclusion (less than five repaints)
...    child: RenderCustomPaint#3c032 relayoutBoundary=up14 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...      size: MISSING
...      painter: null
...      foregroundPainter: _GlowingOverscrollIndicatorPainter(_GlowController(color: Color(0xff2196f3), axis: vertical), _GlowController(color: Color(0xff2196f3), axis: vertical))
...      child: RenderRepaintBoundary#a2154 relayoutBoundary=up15 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...        size: MISSING
...        usefulness ratio: no metrics collected yet (never painted)
...        child: _RenderScrollSemantics#d65e1 relayoutBoundary=up16 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...          semantic boundary
...          size: MISSING
====================================================================================================
```

**Comment by huycozy** [comment]
Hi @anirbangoa 
Can you please provide the complete output of `flutter run -v` along with a minimal sample code (in a single `main.dart` file if possible) so that we may verify the issue? Thank you!
