### ISSUE TITLE
`availableCameras()` throws exception, because `camera['lensFacing']` returns null;

### ISSUE THREAD

**Issue by chinaq** [flutter/flutter#129930]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. install [camera 0.10.5+2](https://pub.dev/packages/camera)
2. use `avaibleCameras()`
3. run it on android phone - Letv Y1Pro+
4. `camera['lensFacing']` return null;

### Expected results

`availableCameras()` works well and returns a list of cameras;

### Actual results

`availableCameras()` throws exception, because `camera['lensFacing']` returns null;

The Letv phone return 3 cameras
- {name: 0, sensorOrientation: 90, lensFacing: back}
- {name: 1, sensorOrientation: 270, lensFacing: front}
- {name: 2, sensorOrientation: -1}

The 3rd one lack of `lenFacing`, if change 
``` dart
lensDirection:
    parseCameraLensDirection(camera['lensFacing']! as String),
```
to
``` dart
lensDirection: parseCameraLensDirection(camera['lensFacing'] == null
    ? 'external'
    : camera['lensFacing']! as String),
```
It works.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

class CamerasGetter extends StatefulWidget {
  const CamerasGetter({super.key});

  @override
  State<CamerasGetter> createState() => _CamerasGetterState();
}

class _CamerasGetterState extends State<CamerasGetter> {
  String _cameras = 'Cameras to list here';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Cameras Getter')),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ElevatedButton(
              onPressed: () async {
                await getCameras();
              },
              child: const Text('Get Cameras'),
            ),
            Text(_cameras),
          ],
        ),
      ),
    );
  }

  getCameras() async {
    final cameras = await availableCameras();
    debugPrint(cameras.toString());
    setState(() {
      _cameras = 'cameras: ${cameras.toString()}';
    });
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![_20230704_105607](https://github.com/flutter/flutter/assets/6382133/0fbae01b-e8f3-4e8f-9331-e62742fa855e)

![39f734b2bc9da7b5d355c37697a64cf](https://github.com/flutter/flutter/assets/6382133/e09debf6-511b-4cd4-b368-c776600aa6cb)

![1127f4773820ff0608cbd5abd701146](https://github.com/flutter/flutter/assets/6382133/f195b486-3ce0-4579-9c2e-e257b8b95f1e)

</details>

### Logs

<details><summary>Logs</summary>

```console
[  +24 ms] E/flutter ( 3462): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3462): #0      AndroidCamera.availableCameras.<anonymous closure> (package:camera_android/src/android_camera.dart:85:60)
[        ] E/flutter ( 3462): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
[        ] E/flutter ( 3462): #2      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
[        ] E/flutter ( 3462): #3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
[        ] E/flutter ( 3462): #4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
[        ] E/flutter ( 3462): #5      new List.of (dart:core-patch/array_patch.dart:52:28)
[        ] E/flutter ( 3462): #6      ListIterable.toList (dart:_internal/iterable.dart:214:7)
[        ] E/flutter ( 3462): #7      AndroidCamera.availableCameras (package:camera_android/src/android_camera.dart:88:10)
[        ] E/flutter ( 3462): <asynchronous suspension>
[        ] E/flutter ( 3462): #8      _CamerasGetterState.getCameras (package:gasmeter_repair_app_2023/screens/testings/photo/camera_getter.dart:36:21)
[        ] E/flutter ( 3462): <asynchronous suspension>
[        ] E/flutter ( 3462): #9      _CamerasGetterState.build.<anonymous closure> (package:gasmeter_repair_app_2023/screens/testings/photo/camera_getter.dart:24:17)
[        ] E/flutter ( 3462): <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.3086], locale zh-CN)
    • Flutter version 3.7.12 on channel stable at C:\Users\sofu-qiang\fvm\versions\3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\Users\sofu-qiang\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = D:\Users\sofu-qiang\AppData\Local\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33815.320
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2022.2)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (2 available)
    • Letv L6B (mobile) • K0TYA13429144823 • android-arm64 • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64   • Microsoft Windows [Version 10.0.19045.3086]

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by darshankawar** [comment]
@chinaq 
The `lensFacing` is currently not exposed by the camera package yet. See [this](https://github.com/flutter/flutter/issues/118730) open issue for reference and you can track in it for further updates.
Closing this as a duplicate.
