### ISSUE TITLE
While debugging Flutter app on Chrome, IDE closed connection and printed this

### ISSUE THREAD

**Issue by negahdaripour** [flutter/flutter#129901]
```
Finished with error: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: ║                     "🤦‍♀️🙌🙌🙌🙌🙌😉😢😊💕😉😢💋🐱‍🏍🐱‍👓🐱‍💻🐱‍🏍🐱‍🏍🎂👏💖🤦‍♂️😍❤�
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[226, 149, 145, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 34, 240, 159, 164, 166, 226, 128, 141, 226, 153, 128, 239, 184, 143, 240, 159, 153, 140, 240, 159, 153, 140, 240, 159, 153, 140, 240, 159, 153, 140, 240, 159, 153, 140, 240, 159, 152, 137, 240, 159, 152, 162, 240, 159, 152, 138, 240, 159, 146, 149, 240, 159, 152, 137, 240, 159, 152, 162, 240, 159, 146, 139, 240, 159, 144, 177, 226, 128, 141, 240, 159, 143, 141, 240, 159, 144, 177, 226, 128, 141, 240, 159, 145, 147, 240, 159, 144, 177, 226, 128, 141, 240, 159, 146, 187, 240, 159, 144, 177, 226, 128, 141, 240, 159, 143, 141, 240, 159, 144, 177, 226, 128, 141, 240, 159, 143, 141, 240, 159, 142, 130, 240, 159, 145, 143, 240, 159, 146, 150, 240, 159, 164, 166, 226, 128, 141, 226, 153, 130, 239, 184, 143, 240, 159, 152, 141, 226, 157, 164, 239, 191, 189, 10]

[+3606 ms] Failed to clean up temp directory: /tmp/flutter_tools.PYVLJW/flutter_tools.BLQCQI
[        ] "flutter run" took 357,211ms.
[  +12 ms] ChromeProxyService: Destroying isolate
[        ] BatchedExpressionEvaluator: Closed
[        ] ChromeProxyService: Destroying isolate
[        ] ChromeProxyService: Destroying isolate
[        ] ChromeProxyService: Destroying isolate
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:659:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

I'm using Route Management, State Management and Dependency Injection from Get package.

**Comment by huycozy** [comment]
Hi @negahdaripour 
Does the issue happen on a newly created Flutter project? (without using any 3rd party packages)

If it works well on Flutter default app and only occurs on your current code, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
