### ISSUE TITLE
Firebase authentication works in production flavor, but not development flavor

### ISSUE THREAD

**Issue by partiallyanonymous1** [flutter/flutter#129928]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Follow the guide at https://flutter.github.io/news_toolkit/ to make a new app from the template using mason.  Then follow the firebase set up steps.  This includes adding the SHA-1 and SHA-256 keys to the firebase project.  (I tried various mason versions of the flutter news template on various computers [windows, mac])
2.  Using android studio, run the app and use the prebuilt/default UI to click "Log In" and "Continue with Google"
3. Observe that when you run the production flavor, signing in with google works, but it doesn't work for the development flavor.

### Actual results

I don't know what's happening, nothing I do seems to have any impact on anything.  
and the error is identical every time i hit continue with google, though on the first time I do it, the app takes me through the sign up process hosted by google, whereas all future times it immediately errors without letting me select which google account i want to sign in with. and the error is also identical on the simulated iphone on my friend's mac laptop.

### Logs

<details>
<summary>
Currently the error code I get when I run the development flavor of the app on a simulated pixel 4 api 31 on windows 11 with android studio is:</summary>

```console

[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.pure(value: , isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.failure, false), event: LoginGoogleSubmitted(AnalyticsEvent(LoginGoogleSubmitted, null)), nextState: LoginState(FormzInput<String, EmailValidationError>.pure(value: , isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.inProgress, false) }
W/System  ( 5017): Ignoring header X-Firebase-Locale because its value was null.
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.pure(value: , isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.inProgress, false), event: LoginGoogleSubmitted(AnalyticsEvent(LoginGoogleSubmitted, null)), nextState: LoginState(FormzInput<String, EmailValidationError>.pure(value: , isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.failure, false) }
[log] onError LoginBloc
      Instance of 'LogInWithGoogleFailure'
      #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
      #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
      <asynchronous suspension>
      #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:518:43)
      <asynchronous suspension>
      #3      MethodChannelFirebaseAuth.signInWithCredential (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:461:12)
      <asynchronous suspension>
      #4      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:526:9)
      <asynchronous suspension>
      #5      FirebaseAuthenticationClient.logInWithGoogle (package:firebase_authentication_client/src/firebase_authentication_client.dart:105:7)
      <asynchronous suspension>
      #6      UserRepository.logInWithGoogle (package:user_repository/src/user_repository.dart:121:7)
      <asynchronous suspension>
      #7      LoginBloc._onGoogleSubmitted (package:daily_globe/login/bloc/login_bloc.dart:60:7)
      <asynchronous suspension>
      #8      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:226:13)
      <asynchronous suspension>
D/EGL_emulation( 5017): app_time_stats: avg=118.94ms min=3.73ms max=4017.17ms count=38

```
</details>
<details>
<summary>One other thing that might be relevant is that no matter the production flavor or anything else I do, I can never successfully "continue with email"  For example, if I try to make an account for e@e.com this is the output (where the first few paragraphs of log output are it processing each letter typed: </summary>
```console
log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.pure(value: , isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false), event: LoginEmailChanged(e), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false), event: LoginEmailChanged(e@), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false), event: LoginEmailChanged(e@e), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false), event: LoginEmailChanged(e@e.), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e., isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e., isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false), event: LoginEmailChanged(e@e.x), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.x, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.x, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false), event: LoginEmailChanged(e@e.), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e., isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e., isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false), event: LoginEmailChanged(e@e.c), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.c, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.c, isValid: false, error: EmailValidationError.invalid), FormzSubmissionStatus.initial, false), event: LoginEmailChanged(e@e.co), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.co, isValid: true, error: null), FormzSubmissionStatus.initial, true) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.co, isValid: true, error: null), FormzSubmissionStatus.initial, true), event: LoginEmailChanged(e@e.com), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.com, isValid: true, error: null), FormzSubmissionStatus.initial, true) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.com, isValid: true, error: null), FormzSubmissionStatus.initial, true), event: SendEmailLinkSubmitted(AnalyticsEvent(SendEmailLinkSubmitted, null)), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.com, isValid: true, error: null), FormzSubmissionStatus.inProgress, true) }
[log] onTransition LoginBloc: Transition { currentState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.com, isValid: true, error: null), FormzSubmissionStatus.inProgress, true), event: SendEmailLinkSubmitted(AnalyticsEvent(SendEmailLinkSubmitted, null)), nextState: LoginState(FormzInput<String, EmailValidationError>.dirty(value: e@e.com, isValid: true, error: null), FormzSubmissionStatus.failure, true) }
[log] onError LoginBloc
      Instance of 'SendLoginEmailLinkFailure'
      #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
      #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
      <asynchronous suspension>
      #2      MethodChannelFirebaseAuth.sendSignInLinkToEmail (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:360:7)
      <asynchronous suspension>
      #3      FirebaseAuth.sendSignInLinkToEmail (package:firebase_auth/src/firebase_auth.dart:364:5)
      <asynchronous suspension>
      #4      FirebaseAuthenticationClient.sendLoginEmailLink (package:firebase_authentication_client/src/firebase_authentication_client.dart:219:7)
      <asynchronous suspension>
      #5      UserRepository.sendLoginEmailLink (package:user_repository/src/user_repository.dart:170:7)
      <asynchronous suspension>
      #6      LoginBloc._onSendEmailLinkSubmitted (package:antifacial_intelligence/login/bloc/login_bloc.dart:44:7)
      <asynchronous suspension>
      #7      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:226:13)
      <asynchronous suspension>
```
</details>

### Flutter Doctor output

<details>
<summary>Doctor output from windows computer used</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
    • Flutter version 3.7.12 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\miros\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.79.2)
    • VS Code at C:\Users\miros\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 114.0.1823.67

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>
<details>
<summary>Doctor output from mac computer used</summary>

```console
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)

    • Flutter version 3.7.9 on channel stable at /Users/siruiwang/Desktop/miro/flutter

    • Upstream repository https://github.com/flutter/flutter.git

    • Framework revision 62bd79521d (3 months ago), 2023-03-30 10:59:36 -0700

    • Engine revision ec975089ac

    • Dart version 2.19.6

    • DevTools version 2.20.1


[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)

    • Android SDK at /Users/siruiwang/Library/Android/sdk

    • Platform android-33, build-tools 33.0.2

    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java

    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

    • All Android licenses accepted.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)

    • Xcode at /Applications/Xcode.app/Contents/Developer

    • Build 14E300c

    • CocoaPods version 1.12.0


[✓] Chrome - develop for the web

    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome


[✓] Android Studio (version 2022.1)

    • Android Studio at /Applications/Android Studio.app/Contents

    • Flutter plugin can be installed from:

      🔨 https://plugins.jetbrains.com/plugin/9212-flutter

    • Dart plugin can be installed from:

      🔨 https://plugins.jetbrains.com/plugin/6351-dart

    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)


[✓] VS Code (version 1.79.2)

    • VS Code at /Applications/Visual Studio Code.app/Contents

    • Flutter extension version 3.68.0


[✓] Connected device (3 available)

    • iPhone 12 (mobile) • 37338B90-31A0-4719-8F93-215472A0A52A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5

      (simulator)

    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64

    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 114.0.5735.198


[✓] HTTP Host Availability

    • All required HTTP hosts are available


• No issues found!
```
</details>

**Comment by darshankawar** [comment]
@partiallyanonymous1 
Firebase related issues need to be reported in dedicated repo:  https://github.com/firebase/flutterfire/issues

Closing from here.
