### ISSUE TITLE
Assertion while rendering GoldenBuilder test with MaterialApp wrapping

### ISSUE THREAD

**Issue by mdazy** [flutter/flutter#129902]
## Actual results

A golden test with a simple widget using `golden_toolkit`'s `GoldenBuilder` triggers an assert in Flutter if a `MaterialApp` wrapper is used (e.g. `materialAppWrapper`):

```dart
// this works
      final builder = GoldenBuilder.grid(
        columns: 2,
        widthToHeightRatio: 1,
      )..addScenario( /*...*/ );

// this crashes Flutter
    final builder = GoldenBuilder.grid(
      columns: 2,
      widthToHeightRatio: 1,
      wrap: (widget) => MaterialApp(home: widget), // basically what golden_toolkit's materialAppWrapper() does
    )..addScenario( /*...*/ );
```

The second case causes an assert with this log
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderPadding#d67b0 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1966 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  GridView
  GridView:file:///Users/mdazy/.pub-cache/hosted/pub.dev/golden_toolkit-0.15.0/lib/src/golden_builder.dart:132:21

When the exception was thrown, this was the stack:
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1966:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:123:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#8      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#9      RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:491:13)
#10     RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:635:17)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#12     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139:12)
#13     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361:11)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#15     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534:13)
#16     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1882:12)
#17     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1833:20)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#19     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#22     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
[ 125 more frames omitted for brevity ]
```

## Expected results
- Second case works - wrapping is necessary in real-world case to add localization and theming

## Flutter version
Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9cd3d0d9ff (6 weeks ago) • 2023-05-23 20:57:28 -0700
Engine • revision 90fa3ae28f
Tools • Dart 3.0.2 • DevTools 2.23.1

## Repro
https://github.com/mdazy/golden_builder_assert

## Related
https://github.com/eBay/flutter_glove_box/issues/174

**Comment by huycozy** [comment]
I run your first test but I get below error. Do you know how to solve this error?

<details>
<summary>First test error</summary>

```console
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Golden "goldens/grid.works.png": Pixel test failed, 0.00% diff detected.
Failure feedback can be found at
/Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/OPClone/golden_builder_assert/test/failures

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:101:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The exception was caught asynchronously.
════════════════════════════════════════════════════════════════════════════════════════════════════

```
</details>

Also, `golden_toolkit` is a 3rd package. For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party package or complex production code. Please try to provide such a sample if any.

**Comment by mdazy** [comment]
Please try this other repro instead: https://github.com/mdazy/flutter_test_material_app_assert

It reproduces the assert independently of `golden_toolkit` and golden testing entirely, but probably reproduces what is happening - possibly the inclusion of `MaterialApp` inside an other layout widget is a no-go here.

**Comment by huycozy** [comment]
Thanks for your update. I run your above sample code and see the new error:

```console
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performResize():
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 1078 pos 12:
'constraints.biggest.isFinite': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/OPClone/flutter_test_material_app_assert/test/widget_test.dart:22:11

```

Taking a look at the failed test code, you are putting MaterialApp inside a Column widget without giving it a height constraint. Below is the updated code that makes it works, please try it and confirm if it's applicable to your case.

```dart
testWidgets('asserts', (tester) async {
  await tester.pumpWidget(
    const Column(
      children: [
        Expanded(
          child: MaterialApp(
            home: Information(version: '1.0.0'),
          ),
        ),
      ],
    ),
  );
});
```

**Comment by mdazy** [comment]
Thanks for your answer. It does fix the assertion here and also hints at the right way for me to do things with the rest of the libraries.

**Comment by huycozy** [comment]
Glad it works for you. Closing the issue as solved.
