### ISSUE TITLE
Could not execute "salt-call state.apply" command on Linux machines running Ubuntu 20.04 due to bug in the Provision script.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#130029]
Could not execute "salt-call state.apply" command on Linux machines running Ubuntu 20.04 due to bug in the Provision script.

flutter@flutter-devicelab-linux-29:/etc/salt/minion.d$ sudo salt-call state.apply
/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/x509.py:98: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
  salt.utils.versions.warn_until(
/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509.py:211: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
  salt.utils.versions.warn_until(
[ERROR   ] State 'cipd.ensure' was not found in SLS 'fastboot'
Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'

[ERROR   ] State 'cipd.ensure' was not found in SLS 'flutter/packages'
Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'

[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2385, in call
    ret = self.states[cdata["full"]](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1280, in wrapper
    return f(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 1703, in installed
    result = _find_install_targets(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 584, in _find_install_targets
    desired = _repack_pkgs(pkgs, normalize=normalize)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/pkg_resource.py", line 38, in _repack_pkgs
    raise SaltInvocationError(
salt.exceptions.SaltInvocationError: You are passing a list of packages that contains duplicated packages names: ['autoconf', 'automake', 'bison', 'build-essential', 'flex', 'gettext', 'gperf', 'groff', 'libtool', 'pkg-config', 'wget', 'acpica-tools', 'build-essential', 'curl', 'dejagnu', 'dosfstools', 'g++-multilib', 'ifupdown', 'libblkid-dev', 'libc6-dev-i386', 'libedit-dev', 'libegl1-mesa', 'libfreetype6-dev', 'libgles2-mesa-dev', 'libglib2.0-dev', 'libglu1-mesa-dev', 'libgtk-3-dev', 'liblz4-tool', 'libncurses5-dev', 'libssl-dev', 'libx11-dev', 'libxcursor-dev', 'libxinerama-dev', 'libxrandr-dev', 'libxxf86vm-dev', 'lsof', 'mesa-common-dev', 'mtools', 'nasm', 'net-tools', 'python3-dev', 'swig', 'tcpdump', 'texinfo', 'unzip', 'uuid-dev', 'vim', 'xvfb', 'xz-utils', 'zip', 'zlib1g-dev']. This cannot be processed. In case you are targeting different versions of the same package, please target them individually

[ERROR   ] State 'cipd.ensure' was not found in SLS 'flutter/device_doctor'
Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'

[ERROR   ] State 'cipd.ensure' was not found in SLS 'flutter/device_doctor'
Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'

[ERROR   ] State 'cipd.ensure' was not found in SLS 'machine_tokend'
Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'

[WARNING ] State for file: /etc/pki/flutter-devicelab-linux-29.mtv.corp.google.com.crt - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
local:
----------
          ID: /usr/local/share/ca-certificates/intca.crt
    Function: file.managed
      Result: True
     Comment: File /usr/local/share/ca-certificates/intca.crt is in the correct state
     Started: 14:20:33.088835
    Duration: 895.53 ms
     Changes:   
----------
          ID: /etc/udev/rules.d/99-android.rules
    Function: file.managed
      Result: True
     Comment: File /etc/udev/rules.d/99-android.rules is in the correct state
     Started: 14:20:33.984679
    Duration: 548.507 ms
     Changes:   
----------
          ID: reload_udev_rules
    Function: cmd.run
        Name: udevadm control --reload-rules
udevadm trigger

      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 14:20:34.535505
    Duration: 0.012 ms
     Changes:   
----------
          ID: remove_system_fastboot
    Function: pkg.removed
        Name: fastboot
      Result: True
     Comment: All specified packages are already absent
     Started: 14:20:35.011767
    Duration: 34.68 ms
     Changes:   
----------
          ID: install_fastboot
    Function: cipd.ensure
      Result: False
     Comment: State 'cipd.ensure' was not found in SLS 'fastboot'
              Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'
     Changes:   
----------
          ID: install_fastboot
    Function: file.symlink
        Name: /usr/bin/fastboot
      Result: False
     Comment: One or more requisite failed: fastboot.install_fastboot
     Started: 14:20:35.263143
    Duration: 0.003 ms
     Changes:   
----------
          ID: python3
    Function: cipd.ensure
      Result: False
     Comment: State 'cipd.ensure' was not found in SLS 'flutter/packages'
              Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'
     Changes:   
----------
          ID: psutil3
    Function: cmd.run
        Name: /opt/swarming-support/bin/python3 /opt/swarming-support/bin/pip3 install psutil
      Result: False
     Comment: One or more requisite failed: flutter/packages.python3
     Started: 14:20:35.263431
    Duration: 0.002 ms
     Changes:   
----------
          ID: packages
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2385, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1280, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 1703, in installed
                  result = _find_install_targets(
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 584, in _find_install_targets
                  desired = _repack_pkgs(pkgs, normalize=normalize)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/pkg_resource.py", line 38, in _repack_pkgs
                  raise SaltInvocationError(
              salt.exceptions.SaltInvocationError: You are passing a list of packages that contains duplicated packages names: ['autoconf', 'automake', 'bison', 'build-essential', 'flex', 'gettext', 'gperf', 'groff', 'libtool', 'pkg-config', 'wget', 'acpica-tools', 'build-essential', 'curl', 'dejagnu', 'dosfstools', 'g++-multilib', 'ifupdown', 'libblkid-dev', 'libc6-dev-i386', 'libedit-dev', 'libegl1-mesa', 'libfreetype6-dev', 'libgles2-mesa-dev', 'libglib2.0-dev', 'libglu1-mesa-dev', 'libgtk-3-dev', 'liblz4-tool', 'libncurses5-dev', 'libssl-dev', 'libx11-dev', 'libxcursor-dev', 'libxinerama-dev', 'libxrandr-dev', 'libxxf86vm-dev', 'lsof', 'mesa-common-dev', 'mtools', 'nasm', 'net-tools', 'python3-dev', 'swig', 'tcpdump', 'texinfo', 'unzip', 'uuid-dev', 'vim', 'xvfb', 'xz-utils', 'zip', 'zlib1g-dev']. This cannot be processed. In case you are targeting different versions of the same package, please target them individually
     Started: 14:20:35.268100
    Duration: 7.499 ms
     Changes:   
----------
          ID: install_psutil
    Function: pip.installed
        Name: psutil
      Result: True
     Comment: Python package psutil was already installed
              All specified packages are already installed
     Started: 14:20:35.275707
    Duration: 814.149 ms
     Changes:   
----------
          ID: ensure_device_doctor
    Function: cipd.ensure
      Result: False
     Comment: State 'cipd.ensure' was not found in SLS 'flutter/device_doctor'
              Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'
     Changes:   
----------
          ID: ensure_device_doctor_staging
    Function: cipd.ensure
      Result: False
     Comment: State 'cipd.ensure' was not found in SLS 'flutter/device_doctor'
              Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'
     Changes:   
----------
          ID: /opt/flutter/provision/fqdn.sh
    Function: file.managed
      Result: True
     Comment: File /opt/flutter/provision/fqdn.sh is in the correct state
     Started: 14:20:36.090387
    Duration: 528.84 ms
     Changes:   
----------
          ID: fix_fqdn
    Function: cmd.run
        Name: /opt/flutter/provision/fqdn.sh fix
      Result: True
     Comment: unless condition is true
     Started: 14:20:36.619555
    Duration: 10.487 ms
     Changes:   
----------
          ID: docker
    Function: group.present
      Result: True
     Comment: Group docker is present and up to date
     Started: 14:20:36.630137
    Duration: 0.444 ms
     Changes:   
----------
          ID: android-tools-adb
    Function: pkg.installed
      Result: True
     Comment: unless condition is true
     Started: 14:20:36.630750
    Duration: 10.436 ms
     Changes:   
----------
          ID: git
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 14:20:36.641286
    Duration: 6.294 ms
     Changes:   
----------
          ID: python3-pip
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 14:20:36.647653
    Duration: 5.217 ms
     Changes:   
----------
          ID: pip3-m2crypto
    Function: pip.installed
        Name: m2crypto == 0.31.0
      Result: True
     Comment: Python package m2crypto == 0.31.0 was already installed
              All specified packages are already installed
     Started: 14:20:36.653114
    Duration: 948.715 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/machine_tokend
    Function: cipd.ensure
      Result: False
     Comment: State 'cipd.ensure' was not found in SLS 'machine_tokend'
              Reason: 'cipd' __virtual__ returned False: No module named 'salt.ext.six'
     Changes:   
----------
          ID: /etc/pki
    Function: file.directory
      Result: True
     Comment: The directory /etc/pki is in the correct state
     Started: 14:20:37.602980
    Duration: 0.626 ms
     Changes:   
----------
          ID: /etc/pki/flutter-devicelab-linux-29.mtv.corp.google.com.key
    Function: x509.private_key_managed
      Result: True
     Comment: File /etc/pki/flutter-devicelab-linux-29.mtv.corp.google.com.key is in the correct state
     Started: 14:20:37.603743
    Duration: 19.263 ms
     Changes:   
----------
          ID: /etc/pki/flutter-devicelab-linux-29.mtv.corp.google.com.crt
    Function: x509.certificate_managed
      Result: True
     Comment: Certificate /etc/pki/flutter-devicelab-linux-29.mtv.corp.google.com.crt is valid and up to date
     Started: 14:20:37.623290
    Duration: 405.759 ms
     Changes:   
----------
          ID: /var/lib/luci_machine_tokend
    Function: file.directory
      Result: True
     Comment: The directory /var/lib/luci_machine_tokend is in the correct state
     Started: 14:20:38.029356
    Duration: 1.044 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: machine_tokend./opt/luci/machine_tokend/machine_tokend
     Started: 14:20:38.030658
    Duration: 0.002 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: machine_tokend./opt/luci/machine_tokend/run.sh
     Started: 14:20:38.031148
    Duration: 0.002 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh >/dev/null 2>&1
    Function: cron.present
      Result: False
     Comment: One or more requisite failed: machine_tokend./opt/luci/machine_tokend/run.sh
     Started: 14:20:38.031358
    Duration: 0.001 ms
     Changes:   
----------
          ID: /usr/local/bin/validate_json.py
    Function: file.managed
      Result: True
     Comment: File /usr/local/bin/validate_json.py is in the correct state
     Started: 14:20:38.031387
    Duration: 525.978 ms
     Changes:   
----------
          ID: /etc/systemd/system/swarming-start-bot.service.d/override.conf
    Function: file.managed
      Result: True
     Comment: File /etc/systemd/system/swarming-start-bot.service.d/override.conf is in the correct state
     Started: 14:20:38.557664
    Duration: 892.532 ms
     Changes:   
----------
          ID: dialout
    Function: group.present
      Result: True
     Comment: Group dialout is present and up to date
     Started: 14:20:39.450459
    Duration: 1.312 ms
     Changes:   
----------
          ID: kvm
    Function: group.present
      Result: True
     Comment: Group kvm is present and up to date
     Started: 14:20:39.451997
    Duration: 1.245 ms
     Changes:   
----------
          ID: plugdev
    Function: group.present
      Result: True
     Comment: Group plugdev is present and up to date
     Started: 14:20:39.453455
    Duration: 1.095 ms
     Changes:   
----------
          ID: swarming
    Function: user.present
      Result: True
     Comment: User swarming is present and up to date
     Started: 14:20:39.455808
    Duration: 4.511 ms
     Changes:   
----------
          ID: /etc/sudoers
    Function: file.append
      Result: True
     Comment: File /etc/sudoers is in correct state
     Started: 14:20:39.460775
    Duration: 2.195 ms
     Changes:   
----------
          ID: /opt/s
    Function: file.directory
      Result: True
     Comment: The directory /opt/s is in the correct state
     Started: 14:20:39.463187
    Duration: 0.871 ms
     Changes:   
----------
          ID: /opt/s/bot_code.py
    Function: cmd.script
      Result: True
     Comment: unless condition is true
     Started: 14:20:39.464442
    Duration: 3.948 ms
     Changes:   
----------
          ID: /etc/systemd/system/swarming-start-bot.service
    Function: file.managed
      Result: True
     Comment: File /etc/systemd/system/swarming-start-bot.service is in the correct state
     Started: 14:20:39.468612
    Duration: 1235.72 ms
     Changes:   
----------
          ID: swarming-start-bot
    Function: service.running
      Result: True
     Comment: The service swarming-start-bot is already running
     Started: 14:20:40.704909
    Duration: 25.747 ms
     Changes:   
----------
          ID: fuchsia/salt-version-base
    Function: event.send
      Result: True
     Comment: Event fired
     Started: 14:20:40.730905
    Duration: 183.494 ms
     Changes:   
              ----------
              data:
                  ----------
                  hash:
                      10eb4eeef93ab59252d15d4c602cbcbb3b87dfd4
                  date:
                      2023-05-15
              tag:
                  fuchsia/salt-version-base

Summary for local
-------------
Succeeded: 28 (changed=1)
Failed:    11

**Comment by yusuf-goog** [comment]
The issue with `You are passing a list of packages that contains duplicated packages names` has been fixed. Please retry with that and let me know what errors are showing up.

**Comment by Ripper66Six** [comment]
Good morning,

we have the same issue with Ubuntu 20.04


```
ID: pkg_installed
    Function: pkg.installed
        Name: pkg_installed
      Result: false
     Comment: An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/state.py", line 2401, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1282, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/pkg.py", line 1701, in installed
    result = _find_install_targets(
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/pkg.py", line 584, in _find_install_targets
    desired = _repack_pkgs(pkgs, normalize=normalize)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/pkg_resource.py", line 38, in _repack_pkgs
    raise SaltInvocationError(
salt.exceptions.SaltInvocationError: You are passing a list of packages that contains duplicated packages names: [OrderedDict([('ntfs-3g:amd64', '1:2017.3.23AR.3-3ubuntu1.
```

The issue was coming up yesterday after the deployment of a new Ubuntu 20.04 virtual machine.


Kind regards
