### ISSUE TITLE
Null check error in vm_snapshot_analysis

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#130009]
Starting in the Engine -> Framework roll here https://github.com/flutter/flutter/pull/129914, builds started failing with:

```
Null check operator used on a null value
            #0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:450:53)
            #1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
            #2      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:444:23)
            #3      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
            #4      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:54)
            #5      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
            #6      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
            #7      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
            #8      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
            #9      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
            #10     treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
            #11     SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
            #12     AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:623:60)
            #13     AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:604:15)
            <asynchronous suspension>
            #14     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:242:5)
            <asynchronous suspension>
            #15     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
            <asynchronous suspension>
            #16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
            <asynchronous suspension>
            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
            <asynchronous suspension>
            #18     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
            <asynchronous suspension>
            #19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
            <asynchronous suspension>
            #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
            <asynchronous suspension>
            #21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
            <asynchronous suspension>
            #22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
            <asynchronous suspension>
            #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
            <asynchronous suspension>
            #24     main (package:flutter_tools/executable.dart:90:3)
            <asynchronous suspension>
```

It looks like this was introduced by the Dart roll here:

with the change: https://dart.googlesource.com/sdk.git/+/a4f59b8c205e69f902a1ea146e440eaa9c9c211e

cc @rmacnak-google

**Comment by zanderso** [comment]
It looks like @rmacnak-google's change may have been an attempt to fix https://dart.googlesource.com/sdk.git/+/99db606baba3642203a2718fbd80adac5094e22b from @mkustermann

**Comment by aam** [comment]
Looks like the thing that is needed to fix the roll is to update vm_snapshot_analysis dependency from 0.7.2 to 0.7.4

**Comment by mkustermann** [comment]
(Tess made https://github.com/flutter/flutter/pull/129950)

**Comment by drewroengoogle** [comment]
I currently have https://github.com/flutter/flutter/pull/129788 which was initially intended for another fix, but it also updates `vm_snapshot_analysis` from 0.7.2 to 0.7.4. It seems like the tests are continuing to give the same null check error as above.

Example: https://ci.chromium.org/p/flutter/builders/try/Linux%20build_tests_3_3/7356?

**Comment by sstrickl** [comment]
Yes, I'm looking into it now.

**Comment by aam** [comment]
Looks like vm_snapshot_analysis 0.7.4 expects updated dart sdk, won't work with older dart sdk.
https://dart-review.googlesource.com/c/sdk/+/312640 is to help flutter to get on 0.7.4 while staying on older dart sdk.

**Comment by sstrickl** [comment]
`package:vm_snapshot_analysis` 0.7.6 got rolled in as part of https://github.com/flutter/flutter/pull/130163, which should fix the issue. Please reopen if this is seen again with a release that includes it.
