### ISSUE TITLE
[go_router] Route extra is not correctly restored when restoring StatefulShellBranch

### ISSUE THREAD

**Issue by astubenbord** [flutter/flutter#130063]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the example below
2. Go to the second route
3. Open details route
4. Navigate back to the first route
5. Navigate back to the second route
6. Extra model is now a Map<String, dynamic> and not of type MyExtraModel!

### Expected results

The stack ['/b', '/details'] and the extra parameter previously passed to the /details route should be restored correctly.

### Actual results

The stack is correctly restored, but the extra parameter previously passed to the details route is not.

Since `MyExtraModel` has a `toJson` method, it seems that the model is not correctly de-serialized, since output of the `toJson` is returned (tested with different hard coded values inside the toJson). If the toJson is used for serialization, then the fromJson (if available) should also be used for de-serialization. 

When removing the `toJson` method, the extra parameter is always Null when restoring the branch.

EDIT: It does not matter whether the /details route is nested in the /b route or not.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class MyExtraModel {
  final String name;
  final int value;

  MyExtraModel(this.name, this.value);

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'value': value,
    };
  }

  factory MyExtraModel.fromJson(Map<String, dynamic> json) {
    return MyExtraModel(json['name'] as String, json['value'] as int);
  }
}

class _MyAppState extends State<MyApp> {
  late final _router = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        redirect: (context, state) => '/a',
      ),
      GoRoute(
        path: '/details',
        builder: (context, state) {
          final extra = state.extra as MyExtraModel;
          return DetailsPage(extra: extra);
        },
      ),
      StatefulShellRoute.indexedStack(
        builder: (context, state, navigationShell) {
          return RotuerScaffoldWrapper(
            key: GlobalKey(),
            shell: navigationShell,
          );
        },
        branches: [
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: "/a",
                builder: (context, state) => APage(),
              ),
            ],
          ),
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: '/b',
                builder: (context, state) => BPage(),
              ),
            ],
          )
        ],
      ),
    ],
  );
  @override
  Widget build(BuildContext context) {
    return CupertinoApp.router(
      routerConfig: _router,
    );
  }
}

class APage extends StatelessWidget {
  const APage({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text("A"),
    );
  }
}

class BPage extends StatelessWidget {
  const BPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        child: Text("Details"),
        onPressed: () {
          GoRouter.of(context).push('/details', extra: MyExtraModel('Test', 1));
        },
      ),
    );
  }
}

class DetailsPage extends StatelessWidget {
  final MyExtraModel extra;
  const DetailsPage({super.key, required this.extra});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text("Details"),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Text(extra.name),
          Text(extra.value.toString()),
        ],
      ),
    );
  }
}

class RotuerScaffoldWrapper extends StatelessWidget {
  final StatefulNavigationShell shell;
  const RotuerScaffoldWrapper({super.key, required this.shell});

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home)),
          BottomNavigationBarItem(icon: Icon(Icons.details)),
        ],
        onTap: shell.goBranch,
        currentIndex: shell.currentIndex,
      ),
      tabBuilder: (context, index) {
        return shell;
      },
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Restarted application in 216ms.
[GoRouter] Full paths for routes:
             => /
             => /details
             => /a
             => /b
[GoRouter] setting initial location null
[GoRouter] redirecting to RouteMatchList(/a)
[GoRouter] Using CupertinoApp configuration
[GoRouter] going to /b
[GoRouter] pushing /details
[GoRouter] going to /a
[GoRouter] going to /b

════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building Builder:
type '_Map<String, dynamic>' is not a subtype of type 'MyExtraModel' in type cast

The relevant error-causing widget was
CupertinoTabScaffold
When the exception was thrown, this was the stack
#0      _MyAppState._router.<anonymous closure>
#1      RouteBuilder._callGoRouteBuilder.<anonymous closure>
#2      Builder.build
#3      StatelessElement.build
#4      ComponentElement.performRebuild
#5      Element.rebuild
#6      StatelessElement.update
#7      Element.updateChild
#8      SingleChildRenderObjectElement.update
#9      Element.updateChild
#10     ComponentElement.performRebuild
#11     Element.rebuild
#12     StatelessElement.update
#13     Element.updateChild
#14     SingleChildRenderObjectElement.update
#15     Element.updateChild
#16     SingleChildRenderObjectElement.update
#17     Element.updateChild
#18     ComponentElement.performRebuild
#19     StatefulElement.performRebuild
#20     Element.rebuild
#21     StatefulElement.update
#22     Element.updateChild
#23     RenderObjectElement.updateChildren
#24     MultiChildRenderObjectElement.update
#25     Element.updateChild
#26     ComponentElement.performRebuild
#27     StatefulElement.performRebuild
#28     Element.rebuild
#29     StatefulElement.update
#30     Element.updateChild
#31     SingleChildRenderObjectElement.update
#32     Element.updateChild
#33     ComponentElement.performRebuild
#34     StatefulElement.performRebuild
#35     Element.rebuild
#36     StatefulElement.update
#37     Element.updateChild
#38     SingleChildRenderObjectElement.update
#39     Element.updateChild
#40     ComponentElement.performRebuild
#41     StatefulElement.performRebuild
#42     Element.rebuild
#43     StatefulElement.update
#44     Element.updateChild
#45     SingleChildRenderObjectElement.update
#46     Element.updateChild
#47     ComponentElement.performRebuild
#48     StatefulElement.performRebuild
#49     Element.rebuild
#50     StatefulElement.update
#51     Element.updateChild
#52     ComponentElement.performRebuild
#53     Element.rebuild
#54     StatelessElement.update
#55     Element.updateChild
#56     ComponentElement.performRebuild
#57     StatefulElement.performRebuild
#58     Element.rebuild
#59     StatefulElement.update
#60     Element.updateChild
#61     SingleChildRenderObjectElement.update
#62     Element.updateChild
#63     ComponentElement.performRebuild
#64     Element.rebuild
#65     ProxyElement.update
#66     _InheritedNotifierElement.update
#67     Element.updateChild
#68     SingleChildRenderObjectElement.update
#69     Element.updateChild
#70     ComponentElement.performRebuild
#71     StatefulElement.performRebuild
#72     Element.rebuild
#73     StatefulElement.update
#74     Element.updateChild
#75     ComponentElement.performRebuild
#76     Element.rebuild
#77     ProxyElement.update
#78     Element.updateChild
#79     ComponentElement.performRebuild
#80     Element.rebuild
#81     ProxyElement.update
#82     Element.updateChild
#83     ComponentElement.performRebuild
#84     StatefulElement.performRebuild
#85     Element.rebuild
#86     StatefulElement.update
#87     Element.updateChild
#88     ComponentElement.performRebuild
#89     Element.rebuild
#90     StatelessElement.update
#91     Element.updateChild
#92     ComponentElement.performRebuild
#93     Element.rebuild
#94     StatelessElement.update
#95     Element.updateChild
#96     SingleChildRenderObjectElement.update
#97     Element.updateChild
#98     ComponentElement.performRebuild
#99     Element.rebuild
#100    ProxyElement.update
#101    Element.updateChild
#102    ComponentElement.performRebuild
#103    Element.rebuild
#104    ProxyElement.update
#105    Element.updateChild
#106    ComponentElement.performRebuild
#107    StatefulElement.performRebuild
#108    Element.rebuild
#109    StatefulElement.update
#110    Element.updateChild
#111    ComponentElement.performRebuild
#112    StatefulElement.performRebuild
#113    Element.rebuild
#114    StatefulElement.update
#115    Element.updateChild
#116    ComponentElement.performRebuild
#117    StatefulElement.performRebuild
#118    Element.rebuild
#119    BuildOwner.buildScope
#120    WidgetsBinding.drawFrame
#121    RendererBinding._handlePersistentFrameCallback
#122    SchedulerBinding._invokeFrameCallback
#123    SchedulerBinding.handleDrawFrame
#124    SchedulerBinding._handleDrawFrame
#125    _invoke (dart:ui/hooks.dart:142:13)
#126    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#127    _drawFrame (dart:ui/hooks.dart:112:31)
════════════════════════════════════════════════════════════════════════════════

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E261 darwin-arm64, locale en-DE)
    • Flutter version 3.10.2 on channel stable at /Users/antonstubenbord/Development/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (6 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/antonstubenbord/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • iPhone 14 Pro Max (mobile) • 181AC5C1-B212-47AD-9C86-07903B15B7ED • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64 • macOS 13.3.1 22E261 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by astubenbord** [comment]
Possibly related to #99099

**Comment by astubenbord** [comment]
@darshankawar Yes, seems to be exactly my problem. I'll close this as duplicate. Thanks.
