### ISSUE TITLE
`tester.tap()` cannot detect a tapping gesture on the previous/next child widgets on the `PageView`

### ISSUE THREAD

**Issue by heeyunlee** [flutter/flutter#130111]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have a `PageView` widget with the `viewportFraction` set to `0.5`, making 1/4 of the previous and next pages visible. Every child widget is wrapped inside the `GestureDetector` widget, and when tapped, the widget animates to the tapped page. This works as described on simulators/actual devices, but when I tried to create a test, the `tester.tap()` method fails saying that the widget is "actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events". What am I doing wrong here? How can I create a widget test that passes?

### Expected results

`tester.tap()` can tap on the second child of the `PageView` and the test passes.

### Actual results

`tester.tap()` **_cannot_** tap on the second child of the `PageView` for some reason and the test fails.

### Code sample

<details><summary>Code sample</summary>

main.dart:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(
        pageController: PageController(
          initialPage: 0,
          viewportFraction: 0.5,
        ),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({
    required this.pageController,
    super.key,
  });

  final PageController pageController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView(
        controller: pageController,
        scrollDirection: Axis.horizontal,
        children: List.generate(
          3,
          (index) {
            return GestureDetector(
              key: ValueKey('page-$index'),
              behavior: HitTestBehavior.translucent,
              onTap: () => pageController.animateToPage(
                index,
                duration: const Duration(milliseconds: 300),
                curve: Curves.easeInOut,
              ),
              child: Placeholder(
                child: Center(
                  child: Text(
                    'Page $index',
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

widget_test.dart:
``` dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:test_page_view/main.dart';

void main() {
  late PageController pageController;

  setUp(() {
    pageController = PageController(
      initialPage: 0,
      viewportFraction: 0.5,
    );
  });

  tearDown(() {
    pageController.dispose();
  });

  testWidgets(
    'PageView should animate to the second page when tapped',
    (WidgetTester tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: MyHomePage(
            pageController: pageController,
          ),
        ),
      );
      await tester.pumpAndSettle();
      final firstPage = find.byKey(const ValueKey('page-0'));
      expect(firstPage, findsOneWidget);
      expect(pageController.page, 0);

      final secondPage = find.byKey(const ValueKey('page-1'));
      expect(secondPage, findsOneWidget);
      await tester.tap(secondPage);
      await tester.pumpAndSettle();
      expect(pageController.page, 1);
    },
  );
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/32585133/90c2376f-2aa8-47e2-8014-cdf249958393

</details>

### Logs

<details><summary>Logs</summary>

```console
Warning: A call to tap() with finder "exactly one widget with key [<'page-1'>] (ignoring offstage widgets): GestureDetector-[<'page-1'>](startBehavior: start, dependencies: [MediaQuery])" derived an Offset (Offset(800.0, 300.0)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
Indeed, Offset(800.0, 300.0) is outside the bounds of the root of the render tree, Size(800.0, 600.0).
The finder corresponds to this RenderBox: RenderSemanticsGestureHandler#b2646
The hit test result at that offset is: HitTestResult(HitTestEntry<HitTestTarget>#9f955(RenderView#5fc98), HitTestEntry<HitTestTarget>#fe409(<AutomatedTestWidgetsFlutterBinding>))
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1347:25)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1232:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3      main.<anonymous closure> (file:///Users/heeyunlee/Developer/test_page_view/test/widget_test.dart:44:20)
<asynchronous suspension>
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
To silence this warning, pass "warnIfMissed: false" to "tap()".
To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <1>
  Actual: <0.0>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/heeyunlee/Developer/test_page_view/test/widget_test.dart:46:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/heeyunlee/Developer/test_page_view/test/widget_test.dart line 46
The test description was:
  PageView should animate to the second page when tapped
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: PageView should animate to the second page when tapped

✖ PageView should animate to the second page when tapped
Exited (1)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/heeyunlee/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (11 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/heeyunlee/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • John Doe’s iPhone (mobile) • 00008101-000A48C40251003A            • ios            • iOS 16.5.1 20F75
    • iPhone 14 Pro (mobile)     • B8250ED7-3D7D-421D-9A5C-D6AF4FD8E7B6 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.4.1 22F82
      darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @heeyunlee 
As I can see from your test, you only invoke a `tap` gesture that will not make the 2nd page becomes visible. You need a `drag`/`swipe` gesture to make it work. 

Use `await tester.drag(firstPage, const Offset(-300, 0));` instead of `await tester.tap(secondPage)`.

And then you can do more gestures (`tap`) on the next pages.

Closing the issue since the error message is correct. If you disagree, please write in the comments and I will reopen it.
