### ISSUE TITLE
[go_router/go_router_builder] App throws `There is no modal route above current context`

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#130213]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

don't  need 

### Expected results

App start time  : 

```
════════ Exception caught by foundation library ════════════════════════════════
The following GoError was thrown while dispatching notifications for GoRouterDelegate:
There is no modal route above the current context.

.
.
.
```
When push a Screen:

```
═══════ Exception caught by foundation library ════════════════════════════════
There is no modal route above the current context.
```

### Actual results

every time I push a  new screen with go_router this  Exception is caught.  The app is ok,  no red screen in the simulator  but an exception is caught message debug  console 

### Code sample

```dart
don't  need 
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1
    22F82 darwin-arm64, locale en-AU)
Checking Android licenses is taking an unexpectedly long                                                        [✓] Android toolchain - develop for Android devices
    (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

</details>

**Comment by danagbemava-nc** [comment]
Hi @samithe7, please provide a complete minimal reproducible code sample so that we can investigate this issue. 

I ran a few of the go_router sample apps but I did not get any errors. 

Thank you

**Comment by samithe7** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'main.g.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final router = GoRouter(
      initialLocation: GoxHome().location,
      debugLogDiagnostics: true,
      routes: $appRoutes,
    );

    router.routerDelegate.addListener(() {
      debugPrint('Route: ${GoRouterState.of(context).location}');
      // FirebaseCrashlytics.instance
      //     .log('Route: ${GoRouterState.of(context).location}');
    });
    return MaterialApp.router(
      routerConfig: router,
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
    );
  }
}

@TypedGoRoute<GoxDlinkxNews>(
  path: '/newx/:url',
)
class GoxDlinkxNews extends GoRouteData {
  GoxDlinkxNews(this.url);
  final String url;

  @override
  Widget build(BuildContext context, GoRouterState state) => DeepLinkPage(
        data: url,
        //key: Key('$b++${Random().nextInt(7)}'),
      );
}

class DeepLinkPage extends StatelessWidget {
  const DeepLinkPage({super.key, required this.data});
  final String data;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Deep Link'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              '$data',
            ),
          ],
        ),
      ),
    );
  }
}

@TypedGoRoute<GoxHome>(
  path: '/',
  routes: [
    TypedGoRoute<GoxDetail>(
      path: 'one',
    ),
    TypedGoRoute<GoxDetailTwo>(
      path: 'two',
    ),
  ],
)
class GoxHome extends GoRouteData {
  @override
  Widget build(BuildContext context, GoRouterState state) {
    return MyHomePage();
  }
}

class GoxDetail extends GoRouteData {
  const GoxDetail({this.$extra});
  final String? $extra;

  @override
  Widget build(BuildContext context, GoRouterState state) => DetailOne(
        key: Key($extra ?? 'xx'),
        data: $extra,
      );
}

class GoxDetailTwo extends GoRouteData {
  const GoxDetailTwo({this.$extra});
  final String? $extra;

  @override
  Widget build(BuildContext context, GoRouterState state) => DetailTwo(
        data: $extra,
      );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    super.key,
  });

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text('Go router demo'),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: TextButton.icon(
                onPressed: () {
                  GoxDetail($extra: 'Detail One').go(context);
                },
                icon: Icon(Icons.details),
                label: Text('Detail One'),
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: TextButton.icon(
                onPressed: () {
                  GoxDetailTwo($extra: 'Detail Two').go(context);
                },
                icon: Icon(Icons.details),
                label: Text('Detail Two'),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class DetailOne extends StatelessWidget {
  const DetailOne({super.key, this.data});

  final String? data;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Detail One'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              '$data  ',
            ),
          ],
        ),
      ),
    );
  }
}

class DetailTwo extends StatelessWidget {
  const DetailTwo({super.key, this.data});

  final String? data;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Detail Two'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              '$data',
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by samithe7** [comment]
Steps to reproduce : 

1. add dependencies  : go_router: ^9.0.3
2.  add dev_dependencies : go_router_builder: ^2.2.0  and  build_runner: ^2.4.6
3.  run  : flutter pub run build_runner build --delete-conflicting-outputs
4.

**Comment by jacobsimionato** [comment]
This also seems to be affecting an internal Google app after upgrading from v7 to v9. We're in the process of filing an internal bug with the details.

**Comment by danagbemava-nc** [comment]
The bug is reproducible using the code sample in https://github.com/flutter/flutter/issues/130213#issuecomment-1630692679 and the steps outlined in https://github.com/flutter/flutter/issues/130213#issuecomment-1630705251

I was able to reproduce it on 8.2.0 as well. 

Labeling for further insight

<details>
<summary>generated file</summary>

```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'main.dart';

// **************************************************************************
// GoRouterGenerator
// **************************************************************************

List<RouteBase> get $appRoutes => [
      $goxDlinkxNews,
      $goxHome,
    ];

RouteBase get $goxDlinkxNews => GoRouteData.$route(
      path: '/newx/:url',
      factory: $GoxDlinkxNewsExtension._fromState,
    );

extension $GoxDlinkxNewsExtension on GoxDlinkxNews {
  static GoxDlinkxNews _fromState(GoRouterState state) => GoxDlinkxNews(
        state.pathParameters['url']!,
      );

  String get location => GoRouteData.$location(
        '/newx/${Uri.encodeComponent(url)}',
      );

  void go(BuildContext context) => context.go(location);

  Future<T?> push<T>(BuildContext context) => context.push<T>(location);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location);

  void replace(BuildContext context) => context.replace(location);
}

RouteBase get $goxHome => GoRouteData.$route(
      path: '/',
      factory: $GoxHomeExtension._fromState,
      routes: [
        GoRouteData.$route(
          path: 'one',
          factory: $GoxDetailExtension._fromState,
        ),
        GoRouteData.$route(
          path: 'two',
          factory: $GoxDetailTwoExtension._fromState,
        ),
      ],
    );

extension $GoxHomeExtension on GoxHome {
  static GoxHome _fromState(GoRouterState state) => GoxHome();

  String get location => GoRouteData.$location(
        '/',
      );

  void go(BuildContext context) => context.go(location);

  Future<T?> push<T>(BuildContext context) => context.push<T>(location);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location);

  void replace(BuildContext context) => context.replace(location);
}

extension $GoxDetailExtension on GoxDetail {
  static GoxDetail _fromState(GoRouterState state) => GoxDetail(
        $extra: state.extra as String?,
      );

  String get location => GoRouteData.$location(
        '/one',
      );

  void go(BuildContext context) => context.go(location, extra: $extra);

  Future<T?> push<T>(BuildContext context) =>
      context.push<T>(location, extra: $extra);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location, extra: $extra);

  void replace(BuildContext context) =>
      context.replace(location, extra: $extra);
}

extension $GoxDetailTwoExtension on GoxDetailTwo {
  static GoxDetailTwo _fromState(GoRouterState state) => GoxDetailTwo(
        $extra: state.extra as String?,
      );

  String get location => GoRouteData.$location(
        '/two',
      );

  void go(BuildContext context) => context.go(location, extra: $extra);

  Future<T?> push<T>(BuildContext context) =>
      context.push<T>(location, extra: $extra);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location, extra: $extra);

  void replace(BuildContext context) =>
      context.replace(location, extra: $extra);
}

```
</details>

<details>
<summary>logs</summary>

```
Launching lib/main.dart on macOS in debug mode...
2023-07-12 06:32:37.244 xcodebuild[21306:369865] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-000329201AD1001E }
{ platform:macOS, arch:x86_64, id:00008103-000329201AD1001E }

flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following GoError was thrown while dispatching notifications for GoRouterDelegate:
flutter: There is no modal route above the current context.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      GoRouterState.of (package:go_router/src/state.dart:120:7)
flutter: #1      MyApp.build.<anonymous closure> (package:grb/main.dart:23:42)
flutter: #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
flutter: #3      GoRouterDelegate.setNewRoutePath (package:go_router/src/delegate.dart:145:7)
flutter: #4      RouterDelegate.setInitialRoutePath (package:flutter/src/widgets/router.dart:1319:12)
flutter: #5      _RouterState._processParsedRouteInformation.<anonymous closure> (package:flutter/src/widgets/router.dart:753:34)
flutter: #6      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:39)
flutter: #7      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:745:8)
flutter: #8      _RouterState.restoreState (package:flutter/src/widgets/router.dart:622:7)
flutter: #9      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:923:5)
flutter: #10     RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:909:7)
flutter: #11     _RouterState.didChangeDependencies (package:flutter/src/widgets/router.dart:692:11)
flutter: #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5448:11)
flutter: #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
flutter: ...     Normal element mounting (405 frames)
flutter: #418    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
flutter: #419    Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)
flutter: #420    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1253:16)
flutter: #421    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1222:5)
flutter: #422    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1169:18)
flutter: #423    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719:19)
flutter: #424    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1168:13)
flutter: #425    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1001:7)
flutter: #426    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:981:7)
flutter: #430    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
flutter: (elided 3 frames from class _Timer and dart:async-patch)
flutter:
flutter: The GoRouterDelegate sending notification was:
flutter:   Instance of 'GoRouterDelegate'
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Application finished.

Exited.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-GB)
    • Flutter version 3.10.5 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.13.0-2.0.pre.53, on macOS 13.4.1 22F82 darwin-arm64, locale en-GB)
    • Flutter version 3.13.0-2.0.pre.53 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1d30e3e4fb (30 minutes ago), 2023-07-12 02:05:57 -0400
    • Engine revision 1b44d7ee1a
    • Dart version 3.1.0 (build 3.1.0-298.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Comment by chunhtai** [comment]
This is trying to access goRouterState above the GoRouter context. Please see migration guide flutter.dev/go/go-router-v9-breaking-changes

**Comment by chunhtai** [comment]
Are you in t latest version? I thought it is exposed after v9.0.2

**Comment by remi-denele** [comment]
You're right, my bad. I was still on a 8.x version where I tested it, thanks!
