### ISSUE TITLE
Issue from website page A Tour of the Flutter Widget Framework

### ISSUE THREAD

**Issue by AnmAtAnm** [flutter/flutter#13025]
From URL: https://flutter.io/widgets-intro.md

The minimal app...

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new Center(child: new Text('Hello, world!')));
}
```

Fails with error:

```
I/flutter ( 4315): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4315): The following assertion was thrown building Text("Hello, world!"):
I/flutter ( 4315): No Directionality widget found.
I/flutter ( 4315): RichText widgets require a Directionality widget ancestor.
I/flutter ( 4315): The specific widget that could not find a Directionality ancestor was:
I/flutter ( 4315):   RichText
I/flutter ( 4315): The ownership chain for the affected widget is:
I/flutter ( 4315):   RichText ← Text ← Center ← [root]
I/flutter ( 4315): Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the
I/flutter ( 4315): top of your application widget tree. It determines the ambient reading direction and is used, for
I/flutter ( 4315): example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve
I/flutter ( 4315): EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.
I/flutter ( 4315): 
I/flutter ( 4315): When the exception was thrown, this was the stack:
I/flutter ( 4315): #0      debugCheckHasDirectionality.<anonymous closure> (package:flutter/src/widgets/debug.dart:223:7)
I/flutter ( 4315): #1      debugCheckHasDirectionality (package:flutter/src/widgets/debug.dart:239:4)
I/flutter ( 4315): #2      RichText.createRenderObject (package:flutter/src/widgets/basic.dart:3863:37)
```

Seems related to #11859

This alternative worked:

```dart
void main() {
  runApp(new Center(
      child: new Directionality(
          textDirection: TextDirection.ltr,
          child: new Text('Hello, world!'))));
}
```

**Comment by AnmAtAnm** [comment]
Based on [this comment](https://github.com/flutter/flutter/issues/12065#issuecomment-329275613) on #12065, the necessity for Directionality in this minimal, untranslated app is counter to the agreed upon design (as of Sept 13).

**Comment by Hixie** [comment]
Well the problem is that we don't know whether the text is left-to-right or right-to-left, so we don't know how to render it. See also the discussion at: https://master-docs-flutter-io.firebaseapp.com/flutter/dart-ui/TextDirection-class.html

**Comment by Hixie** [comment]
(https://github.com/flutter/website/pull/732 is about fixing the example.)

**Comment by mjohnsullivan** [comment]
Website's been updated with a working example.

**Comment by lockerfish** [comment]
This also works without Directionality class
```
void main() {
	runApp(
		new Center(
			child: new Text("Hello World!", textDirection: TextDirection.ltr)
		)
	);
}
```

**Comment by milanpatel18** [comment]
Duplicate of #14146
