### ISSUE TITLE
Null check operator used on a null value thrown in ConstantsTransformer._checkExhaustiveness on Flutter 3.10.5 while debugging

### ISSUE THREAD

**Issue by jonas-zebari** [flutter/flutter#130267]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Start Flutter (3.10.5) app in debug mode
2. Create a new file and add a new stateless widget
3. In the build method, combine the use of the `??` and `switch (expression)` operators. For example:

```dart
final backgroundColor = this.backgroundColor ??
        switch (_type) {
          _Type.primary => theme.primary,
          _Type.background => theme.white,
          _Type.outline || _Type.text => theme.transparent,
        };
```

4. Edit the file and hot reload as you would while developing

### Expected results

The app hot reloads and changes made to the file are reflected in the app immediately.

### Actual results

The console prints a large error stack trace leading to a `Null check operator used on a null value` and then the app crashes completely.

### Code sample

<details><summary>Code sample</summary>

```dart
enum _TypeEnum {
  typeA,
  typeB,
  typeC,
  typeD,
}

class TestWidget extends StatelessWidget {
  const TestWidget({super.key, required this.type, this.backgroundColor});

  final _TypeEnum type;
  final Color? backgroundColor;

  @override
  Widget build(BuildContext context) {
    final backgroundColor = this.backgroundColor ??
        switch (type) {
          _TypeEnum.typeA => Colors.white,
          _TypeEnum.typeB => Colors.black,
          _TypeEnum.typeC || TypeEnum.typeD => Colors.red,
        };
    return FilledButton(
      style: FilledButton.styleFrom(backgroundColor: backgroundColor),
      onPressed: () {
        print('onPressed');
      },
      child: const Text('Button'),
    );
  }
}
```

</details>
The error seems related to the use of a switch expression on a private enum type and the `??` operator. I have not been able to figure out exactly what combination though.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Unhandled exception:
Null check operator used on a null value
#0      ConstantsTransformer._checkExhaustiveness (package:front_end/src/fasta/kernel/constant_evaluator.dart:1542:43)
#1      ConstantsTransformer.visitSwitchExpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:2045:5)
#2      SwitchExpression.accept1 (package:kernel/src/ast/patterns.dart:1926:14)
#3      RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#4      ConditionalExpression.transformOrRemoveChildren (package:kernel/ast.dart:7466:16)
#5      RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#6      TreeVisitor1.defaultExpression (package:kernel/visitor.dart:547:50)
#7      TreeVisitor1.visitConditionalExpression (package:kernel/visitor.dart:632:7)
#8      ConditionalExpression.accept1 (package:kernel/ast.dart:7424:9)
#9      RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#10     Let.transformOrRemoveChildren (package:kernel/ast.dart:9311:16)
#11     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#12     TreeVisitor1.defaultExpression (package:kernel/visitor.dart:547:50)
#13     TreeVisitor1.visitLet (package:kernel/visitor.dart:698:34)
#14     Let.accept1 (package:kernel/ast.dart:9280:59)
#15     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1970:21)
#16     RemovingTransformer.transformOrRemoveExpression (package:kernel/visitor.dart:1943:12)
#17     ReturnStatement.transformOrRemoveChildren (package:kernel/ast.dart:10808:22)
#18     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2226:10)
#19     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:780:48)
#20     TreeVisitor1.visitReturnStatement (package:kernel/visitor.dart:826:7)
#21     ReturnStatement.accept1 (package:kernel/ast.dart:10790:9)
#22     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#23     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:651:19)
#24     FunctionNode.accept1 (package:kernel/ast.dart:4202:9)
#25     RemovingTransformer.transform (package:kernel/visitor.dart:1934:17)
#26     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:552:23)
#27     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:5259:18)
#28     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:550:23)
#29     transformProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:176:24)
#30     KernelTarget.runProcedureTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1587:15)
#31     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:2062:28)
<asynchronous suspension>
#32     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1855:12)
<asynchronous suspension>
#33     FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:973:28)
<asynchronous suspension>
#34     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1409:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-x64, locale en)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.17.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/jonaszebari/fvm/versions/3.10.5. Consider adding /Users/jonaszebari/fvm/versions/3.10.5/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @jonas-zebari, this is not a flutter issue but rather a crash in the dart compiler and should be reported on their repo over here https://github.com/dart-lang/sdk/issues?q=is:issue+is:open+sort:updated-desc. 

You may want to check on the master channel to see if you still face this issue before you file it on their repo as the master channel uses a newer version of the dart SDK so there's a chance the issue may have been fixed over there. 

Unfortunately, I cannot transfer this issue over there since they are different organizations, so I will have to close this issue. 

Thank you
