### ISSUE TITLE
io.flutter.embedding.engine.FlutterJNI.loadLibrary | Crash issues

### ISSUE THREAD

**Issue by rahmanprofile** [flutter/flutter#130237]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.jobkar.jobkar/com.jobkar.jobkar.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/base.apk", zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.en.apk", zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.es.apk", zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.x86.apk", zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/base.apk!/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.en.apk!/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.es.apk!/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.x86.apk!/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.xxhdpi.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"

### Expected results

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jobkar.jobkar/com.jobkar.jobkar.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/base.apk", zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.en.apk", zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.es.apk", zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.x86.apk", zip file "/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/base.apk!/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.en.apk!/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.es.apk!/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.x86.apk!/lib/x86, /data/app/com.jobkar.jobkar-s7xVmVZfsFUg9dfPH2Es-w==/split_config.xxhdpi.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Actual results

[com.jobkar.jobkar_issue_65ba2e8079346923b845161e869084d9_crash_session_64AAD02900AC000121F8023537EE3089_DNE_0_v2_stacktrace.txt](https://github.com/flutter/flutter/files/11998008/com.jobkar.jobkar_issue_65ba2e8079346923b845161e869084d9_crash_session_64AAD02900AC000121F8023537EE3089_DNE_0_v2_stacktrace.txt)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Thanks for filing the issue, @rahmanprofile
I see there's an open issue similar to this: https://github.com/flutter/flutter/issues/83596. Closing this issue as a duplicate, so please follow up on it for further updates.
