### ISSUE TITLE
CocoaPods considered not working, but a reinstall doesn't help

### ISSUE THREAD

**Issue by dpetrou-continua** [flutter/flutter#130501]
(Some discussion at https://discord.com/channels/608014603317936148/1125887981346095197.)

Flutter doctor is giving me the following:

```
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
```

even after I’ve uninstalled and reinstalled cocoapods.

After adding some logging to flutter_tools/lib/src/macos/cocoapods.dart in cocoaPodsVersionText(), I see that the execution of `pod --version` is emitting the following to stderr:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/date-3.3.3/lib/date_core.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/date-3.3.3/lib/date_core.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Ruby/Gems/2.6.0/gems/date-3.3.3/lib/date_core.bundle' (no such file), '/Library/Ruby/Gems/2.6.0/gems/date-3.3.3/lib/date_core.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')) - /Library/Ruby/Gems/2.6.0/gems/date-3.3.3/lib/date_core.bundle (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Library/Ruby/Gems/2.6.0/gems/date-3.3.3/lib/date.rb:4:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/time.rb:3:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.7.4/lib/active_support/xml_mini.rb:3:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.7.4/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/dpetrou/.gem/gems/cocoapods-1.12.1/lib/cocoapods.rb:9:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/dpetrou/.gem/gems/cocoapods-1.12.1/bin/pod:36:in `<top (required)>'
        from /Users/dpetrou/.gem/bin/pod:23:in `load'
        from /Users/dpetrou/.gem/bin/pod:23:in `<main>'
```

I was asked by @stuartmorgan to file this issue.

**Comment by stuartmorgan** [comment]
Ideally we should be noticing the distinctive `mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')` message here, and providing more targeted instructions. (We'd need to figure out exactly what those are for this case; I suspect it's re-installing some lower-level gems.)

**Comment by jmagman** [comment]
We aren't investing further in CocoaPods tooling. You can follow along with our Swift Package Manager adoption here https://github.com/flutter/flutter/issues/126005.
