### ISSUE TITLE
Uncaught exception thrown by finalizer

### ISSUE THREAD

**Issue by lalit-1729** [flutter/flutter#130657]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Open the camera preview, close it then wait for some time 10-15 minutes you will see the error in the logs.

### Expected results

No errors should there, as the camera is already off

### Actual results

```
 Uncaught exception thrown by finalizer
E/System  (30406): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$9H0ZdANdMrdpoq2bfIL2l3DVsKk@f897ea1 rejected from java.util.concurrent.ThreadPoolExecutor@3a628c6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
E/System  (30406):      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/System  (30406):      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/System  (30406):      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/System  (30406):      at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
E/System  (30406):      at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (30406):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:536)
E/System  (30406):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:827)
E/System  (30406):      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
E/System  (30406):      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
E/System  (30406):      at java.lang.Daemons$Daemon.run(Daemons.java:139)
E/System  (30406):      at java.lang.Thread.run(Thread.java:919)
```
### Code sample
<details>
<summary>Sample code</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class PanImageTaker extends StatefulWidget {
  static const String screenName = "/panImageScreen";
  final List<CameraDescription> cameras;

  const PanImageTaker({Key? key, required this.cameras}) : super(key: key);

  @override
  State<PanImageTaker> createState() => _PanImageTakerState();
}

class _PanImageTakerState extends State<PanImageTaker> {
  late CameraController _controller;

  bool isLoading = false;

  @override
  void initState() {
    super.initState();
    _controller = CameraController(
      widget.cameras[0],
      ResolutionPreset.high,
      enableAudio: false,
    );
    _controller.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    }).catchError((Object e) {
      if (e is CameraException) {
        switch (e.code) {
          case 'CameraAccessDenied':
            printInDebug('Access denied');
            Navigator.pop(context);
            CommonAlerts.showFlushBar(
              context,
              message: 'Camera Permission Denied',
            );
            break;
          default:
            // Handle other errors here.
            break;
        }
      }
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final double width = MediaQuery.of(context).size.width;
    final double height = MediaQuery.of(context).size.height;
    if (!_controller.value.isInitialized) {
      return const Material(
        child: Text(
          'Camera Permission Denied',
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.w900,
          ),
        ),
      );
    }

    return Scaffold(
      body: Column(
          children: [
            Expanded(
              child: AspectRatio(
                aspectRatio: 3 / 4,
                child: Stack(
                  fit: StackFit.expand,
                  children: [
                    CameraPreview(_controller),
                    cameraOverlay(
                      padding: width * 0.05,
                      aspectRatio: 1.5,
                      color: Colors.black.withOpacity(0.6),
                    ),
                  ],
                ),
              ),
            ),
            Align(
              alignment: Alignment.bottomCenter,
              child: Container(
                color: Colors.black,
                height: height * 0.15,
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Material(
                      color: Colors.black,
                      child: BlocBuilder<KycBloc, KycState>(
                        builder: (context, state) {
                          return IconButton(
                            onPressed: _takePicture,
                            iconSize: height * 0.08,
                            padding: EdgeInsets.zero,
                            constraints: const BoxConstraints(),
                            icon: state is ChooossingImage || isLoading
                                ? const CircularProgressIndicator(
                                    color: resources.secondary1,
                                  )
                                : const Icon(
                                    Icons.camera,
                                    color: Colors.white,
                                  ),
                          );
                        },
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      
    );
  }

  Widget cameraOverlay(
      {required double padding,
      required double aspectRatio,
      required Color color}) {
    return LayoutBuilder(
      builder: (context, constraints) {
        double parentAspectRatio = constraints.maxWidth / constraints.maxHeight;
        double horizontalPadding;
        double verticalPadding;

        if (parentAspectRatio < aspectRatio) {
          horizontalPadding = padding;
          verticalPadding = (constraints.maxHeight -
                  ((constraints.maxWidth - 2 * padding) / aspectRatio)) /
              2;
        } else {
          verticalPadding = padding;
          horizontalPadding = (constraints.maxWidth -
                  ((constraints.maxHeight - 2 * padding) * aspectRatio)) /
              2;
        }
        return Stack(
          fit: StackFit.expand,
          children: [
            Align(
              alignment: Alignment.centerLeft,
              child: Container(
                width: horizontalPadding,
                color: color,
              ),
            ),
            Align(
              alignment: Alignment.centerRight,
              child: Container(width: horizontalPadding, color: color),
            ),
            Align(
              alignment: Alignment.topCenter,
              child: Container(
                margin: EdgeInsets.only(
                  left: horizontalPadding,
                  right: horizontalPadding,
                ),
                height: verticalPadding,
                color: color,
              ),
            ),
            Align(
              alignment: Alignment.bottomCenter,
              child: Container(
                margin: EdgeInsets.only(
                  left: horizontalPadding,
                  right: horizontalPadding,
                ),
                height: verticalPadding,
                color: color,
              ),
            ),
            Container(
              margin: EdgeInsets.symmetric(
                horizontal: horizontalPadding,
                vertical: verticalPadding,
              ),
              decoration: BoxDecoration(
                border: Border.all(color: resources.primary3, width: 2),
              ),
            )
          ],
        );
      },
    );
  }

  Future _takePicture() async {
    if (!_controller.value.isInitialized) {
      return null;
    }
    if (_controller.value.isTakingPicture) {
      return null;
    }
    setState(() => isLoading = true);
    try {
      await _controller.lockCaptureOrientation();
      await _controller.setFlashMode(FlashMode.off);
      await _controller.takePicture().then((value) {
        setState(() => isLoading = false);
        BlocProvider.of<KycBloc>(context).add(TakeImageFromCamera(value));
      });
    } on CameraException catch (e) {
      debugPrint('+++Error occured while taking picture:++\n$e');
      return null;
    }
  }
}

```
</details>

### Screenshots or Video

Nothing to show

### Logs
```
 Uncaught exception thrown by finalizer
E/System  (30406): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$9H0ZdANdMrdpoq2bfIL2l3DVsKk@f897ea1 rejected from java.util.concurrent.ThreadPoolExecutor@3a628c6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
E/System  (30406):      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/System  (30406):      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/System  (30406):      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/System  (30406):      at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
E/System  (30406):      at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (30406):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:536)
E/System  (30406):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:827)
E/System  (30406):      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
E/System  (30406):      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
E/System  (30406):      at java.lang.Daemons$Daemon.run(Daemons.java:139)
E/System  (30406):      at java.lang.Thread.run(Thread.java:919)
```
### Flutter Doctor output

Nothing wrong there i have checked

**Comment by huycozy** [comment]
Thanks for the report!  This is a known issue being tracked at https://github.com/flutter/flutter/issues/108941. Closing this issue as a duplicate, so please follow up on it for further updates.
