### ISSUE TITLE
Got an exception from within the Flutter animation framework, the exception message asked me to submit this report

### ISSUE THREAD

**Issue by schaneville** [flutter/flutter#130681]
Using the package "flutter_login: 4.2.0", I clicked the "Login" button and wound up with the following stack trace from within the Flutter animation framework:
---------------------------------

```
Launching lib\main.dart on Windows in debug mode...
√  Built build\windows\runner\Debug\nubitecture.exe.
Connecting to VM Service at ws://127.0.0.1:51839/HZZpJ0nWb7M=/ws
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12:
flutter: 'elapsedInSeconds >= 0.0': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      AnimationController._tick
flutter: #3      Ticker._tick
flutter: #4      SchedulerBinding._invokeFrameCallback
flutter: #5      SchedulerBinding.handleBeginFrame.<anonymous closure>
flutter: #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
flutter: #7      SchedulerBinding.handleBeginFrame
flutter: #8      SchedulerBinding._handleBeginFrame
flutter: #12     _invoke1 (dart:ui/hooks.dart:160:10)
flutter: #13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:337:5)
flutter: #14     _beginFrame (dart:ui/hooks.dart:101:31)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter:
flutter: This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
flutter: #2      SchedulerBinding.scheduleFrameCallback
flutter: #3      Ticker.scheduleTick
flutter: #4      Ticker.start
flutter: #5      AnimationController._startSimulation
flutter: #6      AnimationController._animateToInternal
flutter: #7      AnimationController.reverse
flutter: #8      _FlushbarState._configurePulseAnimation.<anonymous closure>
flutter: #9      AnimationLocalStatusListenersMixin.notifyStatusListeners
flutter: #10     AnimationController._checkStatusChanged
flutter: #11     AnimationController._tick
flutter: #12     Ticker._tick
flutter: #13     SchedulerBinding._invokeFrameCallback
flutter: #14     SchedulerBinding.handleBeginFrame.<anonymous closure>
flutter: #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
flutter: #16     SchedulerBinding.handleBeginFrame
flutter: #17     SchedulerBinding._handleBeginFrame
flutter: #21     _invoke1 (dart:ui/hooks.dart:160:10)
flutter: #22     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:337:5)
flutter: #23     _beginFrame (dart:ui/hooks.dart:101:31)
flutter: (elided 5 frames from class _FrameCallbackEntry and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Here is my code that consumes the flutter_login package, in case that is helpful:
---------------------------------
```
import 'package:flutter/material.dart';
import 'package:flutter_login/flutter_login.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';

import '../../models/app_state/local_user_app_state.dart';
import '../../services/page_container_service.dart';
import '../../services/server_api/command_service_dtos.g.dart';

class LoginPage2 extends StatelessWidget {
  final PageContainerService _pcs;

  const LoginPage2(this._pcs, {super.key});

  Duration get loginTime => const Duration(milliseconds: 2250);

  Future<String?> _onLoginClick(BuildContext context, LoginData data) async {
    void navigate() {
      if (context.canPop()) {
        context.pop();
      } else {
        context.push("/");
      }
    }

    var userInfo = context.read<LocalUserAppState>();
    var request = LoginCommandRequest();
    request.Username = data.name;
    request.Password = data.password;
    var future = _pcs.api
        .Login(request, showNotificationOnFailure: false)
        .then((value) => _onLoginSucceeded(userInfo, value, navigate))
        .catchError((error, stackTrace) => _onLoginFailed(context, error));
    return future;
  }

  Future<String?> _onLoginSucceeded(LocalUserAppState userInfo,
      LoginCommandResponse response, void Function() navigate) {
    userInfo.userInfo = response.UserInfo;
    return Future.value(null);
  }

  Future<String?> _onLoginFailed(BuildContext context, error) {
    return Future.value("Login Failed");
  }

  Future<String?> _signupUser(SignupData data) {
    debugPrint('Signup Name: ${data.name}, Password: ${data.password}');
    return Future.delayed(loginTime).then((_) {
      return null;
    });
  }

  Future<String?> _recoverPassword(String name) {
    throw UnimplementedError();
    // debugPrint('Name: $name');
    // return Future.delayed(loginTime).then((_) {
    //   if (!users.containsKey(name)) {
    //     return 'User not exists';
    //   }
    //   return null;
    // });
  }

  @override
  Widget build(BuildContext context) {
    return FlutterLogin(
      logo: const AssetImage('lib/assets/images/logo-white.png'),
      onLogin: (data) => _onLoginClick(context, data),
      onSignup: _signupUser,
      loginProviders: <LoginProvider>[
        LoginProvider(
          icon: FontAwesomeIcons.google,
          label: 'Google',
          callback: () async {
            debugPrint('start google sign in');
            await Future.delayed(loginTime);
            debugPrint('stop google sign in');
            return null;
          },
        ),
        LoginProvider(
          icon: FontAwesomeIcons.facebookF,
          label: 'Facebook',
          callback: () async {
            debugPrint('start facebook sign in');
            await Future.delayed(loginTime);
            debugPrint('stop facebook sign in');
            return null;
          },
        ),
        LoginProvider(
          icon: FontAwesomeIcons.linkedinIn,
          callback: () async {
            debugPrint('start linkdin sign in');
            await Future.delayed(loginTime);
            debugPrint('stop linkdin sign in');
            return null;
          },
        ),
        LoginProvider(
          icon: FontAwesomeIcons.githubAlt,
          callback: () async {
            debugPrint('start github sign in');
            await Future.delayed(loginTime);
            debugPrint('stop github sign in');
            return null;
          },
        ),
      ],
      onSubmitAnimationCompleted: () {
        context.push("/");
      },
      onRecoverPassword: _recoverPassword,
    );
  }
}

```

**Comment by darshankawar** [comment]
@schaneville 
Even though the error says to file an issue with the stacktrace, we would need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party package implementation, so that we can properly analyze and address the error reported.
`flutter_login` is third party and I also see other third party package code in the sample you provided.
If you are able to replicate the same error only using framework code, file a new issue by providing relevant info requested in the template so that we can properly address the issue. 
Closing for now.

**Comment by stevenubitz** [comment]
Ok, no worries, I was just submitting this for y'all. I am not getting the issue anymore anyway, I only saw the exception the one time. 

Thanks!
~Steve
