### ISSUE TITLE
[tool_crash] _TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))

### ISSUE THREAD

**Issue by Fateme2121** [flutter/flutter#130701]
## Command
```
flutter build apk --target-platform android-arm --analyze-size
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))
```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:548:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
    [32m•[39m Flutter version 3.10.1 on channel stable at D:\flutterNew\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision d3d8effc68 (9 weeks ago), 2023-05-16 17:59:05 -0700
    [32m•[39m Engine revision b4fb11214d
    [32m•[39m Dart version 3.0.1
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at C:\Users\salameh.fatemeh\AppData\Local\Android\sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[32m[✓][39m Connected device (4 available)
    [32m•[39m PM85 (mobile)     • 21272A0083 • android-arm64  • Android 9 (API 28)
    [32m•[39m Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    [32m•[39m Chrome (web)      • chrome     • web-javascript • Google Chrome 114.0.5735.199
    [32m•[39m Edge (web)        • edge       • web-javascript • Microsoft Edge 114.0.1823.82

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.86.1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: cd41fdd495f6944ecd3506c21e94c6567b073278
### Plugins
app_installer-1.1.0
flutter_bluetooth_serial-0.4.0
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
fluttertoast-8.2.2
geolocator-9.0.2
geolocator_android-4.1.8
geolocator_apple-2.2.5
geolocator_web-2.1.6
geolocator_windows-0.1.1
location-5.0.0
location_web-4.0.0
ota_update-5.1.0
package_info_plus-4.0.1
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.6
permission_handler-10.2.0
permission_handler_android-10.2.1
permission_handler_apple-9.0.8
permission_handler_windows-0.1.2
photo_manager-2.6.0
qr_code_scanner-1.0.1
restart_app-1.1.3
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
sqflite-2.2.8+4
telephony-0.2.0
video_player-2.6.1
video_player_android-2.4.8
video_player_avfoundation-2.4.6
video_player_web-2.0.16

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/129706
