### ISSUE TITLE
Exception caught by foundation library

### ISSUE THREAD

**Issue by michalovmarek** [flutter/flutter#130762]
```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for TextEditingController:
Range start 6 is out of text of length 5
'package:flutter/src/services/text_input.dart':
Failed assertion: line 963 pos 12: 'range.start >= 0 && range.start <= text.length'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TextEditingValue._textRangeIsValid (package:flutter/src/services/text_input.dart:963:12)
#3      TextEditingValue.toJSON (package:flutter/src/services/text_input.dart:918:12)
#4      _PlatformTextInputControl.setEditingState (package:flutter/src/services/text_input.dart:2249:13)
#5      TextInput._setEditingState (package:flutter/src/services/text_input.dart:1938:15)
#6      TextInputConnection.setEditingState (package:flutter/src/services/text_input.dart:1362:25)
#7      EditableTextState._updateRemoteEditingValueIfNeeded (package:flutter/src/widgets/editable_text.dart:3060:27)
#8      EditableTextState._didChangeTextEditingValue (package:flutter/src/widgets/editable_text.dart:3709:5)
#9      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#10     ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:530:5)
#11     TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:240:11)
#12     ObjDvaEditRowState.build.<anonymous closure> (package:store_check/ui/screen_offline/report/obj_dva/edit/ObjDvaEditRow.dart:117:36)
#13     State.setState (package:flutter/src/widgets/framework.dart:1139:30)
#14     ObjDvaEditRowState.build (package:store_check/ui/screen_offline/report/obj_dva/edit/ObjDvaEditRow.dart:113:13)
#15     StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#25     _invoke (dart:ui/hooks.dart:142:13)
#26     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#27     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
The TextEditingController sending notification was: TextEditingController#d07d7(TextEditingValue(text: ┤2.033├, selection: TextSelection.collapsed(offset: 6, affinity: TextAffinity.upstream, isDirectional: false), composing: TextRange(start: -1, end: -1)))
```

**Comment by danagbemava-nc** [comment]
Hi @michalovmarek, 

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you
