### ISSUE TITLE
FontLoader() displays "SyntaxError: Invalid font data in ArrayBuffer." When the web is loaded on the mobile side of the small screen.

### ISSUE THREAD

**Issue by Sansuihe** [flutter/flutter#130785]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Since I carry fonts with me when I run the web side, it is very slow for me to load them, so I want to put these fonts on the server and dynamically request them after the project runs。
 I used the method FontLoader().addfont () to load them dynamically. This method was successful on the App and on the large screen web, but when I switched to the mobile web debugging, it did not succeed and kept reporting errors。
He kept telling me 

```
"main.dart.js:8495 OTS parsing error: vhea: Failed to parse table" and "Exception: SyntaxError: Invalid font data in ArrayBuffer.”
出错：error==>,Exception: Failed to load font 
 出错：stack==>,Exception: Failed to load font
    at Object.c (https://dev.scet.com.cn/mobile/main.dart.js:4701:3)
    at https://dev.scet.com.cn/mobile/main.dart.js:27799:9
    at aIa.a (https://dev.scet.com.cn/mobile/main.dart.js:5968:62)
    at aIa.$2 (https://dev.scet.com.cn/mobile/main.dart.js:41502:14)
    at aGQ.$2 (https://dev.scet.com.cn/mobile/main.dart.js:41499:16)
    at Object.aHX (https://dev.scet.com.cn/mobile/main.dart.js:6236:19)
    at Vy.<anonymous> (https://dev.scet.com.cn/mobile/main.dart.js:95952:70)
    at Yb.Bq (https://dev.scet.com.cn/mobile/main.dart.js:42589:12)
    at l2.amp (https://dev.scet.com.cn/mobile/main.dart.js:41764:18)
    at azh.$0 (https://dev.scet.com.cn/mobile/main.dart.js:41909:37)
``` 

### Expected results

Please tell me how I should dynamically load the font files in the server correctly in the mobile web. Thank you very much.

### Actual results

<details><summary>Actual Result</summary>
<p>

```
main.dart.js:8495 OTS parsing error: vhea: Failed to parse table
aUe @ main.dart.js:8495
a5l @ main.dart.js:483
aUq @ main.dart.js:466
ac8 @ main.dart.js:37897
Aw @ main.dart.js:37870
(anonymous) @ main.dart.js:8668
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
aJ_ @ main.dart.js:8671
$1 @ main.dart.js:73384
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
bO @ main.dart.js:41491
w @ main.dart.js:5958
(anonymous) @ main.dart.js:27838
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
$1 @ main.dart.js:41496
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
bO @ main.dart.js:41491
w @ main.dart.js:5958
(anonymous) @ main.dart.js:26366
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
$1 @ main.dart.js:41496
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
bO @ main.dart.js:41491
w @ main.dart.js:5958
(anonymous) @ main.dart.js:26413
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
$1 @ main.dart.js:41496
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
$0 @ main.dart.js:41866
aHW @ main.dart.js:6227
(anonymous) @ main.dart.js:95950
oF @ main.dart.js:42585
mX @ main.dart.js:42561
$0 @ main.dart.js:42633
b7D @ main.dart.js:6137
b7X @ main.dart.js:6139
$1 @ main.dart.js:41446
b9X @ main.dart.js:4782
(anonymous) @ main.dart.js:4790
childList (async)
$1 @ main.dart.js:41453
aTZ @ main.dart.js:6144
aHZ @ main.dart.js:6248
j7 @ main.dart.js:42603
Mz @ main.dart.js:41838
hM @ main.dart.js:41836
bO @ main.dart.js:41752
$1 @ main.dart.js:92443
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
iv @ main.dart.js:41827
aGV @ main.dart.js:6206
$1 @ main.dart.js:42033
$1 @ main.dart.js:45871
aHY @ main.dart.js:6233
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
oH @ main.dart.js:42565
$1 @ main.dart.js:42636
b9X @ main.dart.js:4782
(anonymous) @ main.dart.js:4790
load (async)
abc @ main.dart.js:45288
pR @ main.dart.js:45284
aYs @ main.dart.js:28382
FJ @ main.dart.js:45862
iW @ main.dart.js:45853
gS @ main.dart.js:41938
(anonymous) @ main.dart.js:92409
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
$1 @ main.dart.js:41496
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
$0 @ main.dart.js:41866
aHW @ main.dart.js:6227
(anonymous) @ main.dart.js:95950
oF @ main.dart.js:42585
mX @ main.dart.js:42561
$0 @ main.dart.js:42633
b7D @ main.dart.js:6137
b7X @ main.dart.js:6139
$1 @ main.dart.js:41446
b9X @ main.dart.js:4782
(anonymous) @ main.dart.js:4790
childList (async)
$1 @ main.dart.js:41453
aTZ @ main.dart.js:6144
aHZ @ main.dart.js:6248
j7 @ main.dart.js:42697
Mz @ main.dart.js:41838
hM @ main.dart.js:41836
bO @ main.dart.js:41488
w @ main.dart.js:5958
(anonymous) @ main.dart.js:1375
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
aNu @ main.dart.js:1376
(anonymous) @ main.dart.js:46593
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
$0 @ main.dart.js:46596
(anonymous) @ main.dart.js:28570
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
$2 @ main.dart.js:28573
b2P @ main.dart.js:4657
b0U @ main.dart.js:7115
b6n @ main.dart.js:27652
(anonymous) @ main.dart.js:27648
$1 @ main.dart.js:28560
$0 @ main.dart.js:28561
b2P @ main.dart.js:4657
b0U @ main.dart.js:7115
b6n @ main.dart.js:27652
(anonymous) @ main.dart.js:27648
onEntrypointLoaded @ (index):86
await in onEntrypointLoaded (async)
didCreateEngineInitializer @ flutter.js:256
Function.$1 @ main.dart.js:102382
(anonymous) @ main.dart.js:8585
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
aJW @ main.dart.js:8587
(anonymous) @ main.dart.js:27631
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
aJ1 @ main.dart.js:27633
(anonymous) @ main.dart.js:102408
(anonymous) @ main.dart.js:102402
dartProgram @ main.dart.js:102405
(anonymous) @ main.dart.js:102408
main.dart.js:27642 Exception: SyntaxError: Invalid font data in ArrayBuffer.
main.dart.js:27642 出错：error==>,Exception: Failed to load font 
 出错：stack==>,Exception: Failed to load font
    at Object.c (https://dev.scet.com.cn/mobile/main.dart.js:4701:3)
    at https://dev.scet.com.cn/mobile/main.dart.js:27799:9
    at aIa.a (https://dev.scet.com.cn/mobile/main.dart.js:5968:62)
    at aIa.$2 (https://dev.scet.com.cn/mobile/main.dart.js:41502:14)
    at aGQ.$2 (https://dev.scet.com.cn/mobile/main.dart.js:41499:16)
    at Object.aHX (https://dev.scet.com.cn/mobile/main.dart.js:6236:19)
    at Vy.<anonymous> (https://dev.scet.com.cn/mobile/main.dart.js:95952:70)
    at Yb.Bq (https://dev.scet.com.cn/mobile/main.dart.js:42589:12)
    at l2.amp (https://dev.scet.com.cn/mobile/main.dart.js:41764:18)
    at azh.$0 (https://dev.scet.com.cn/mobile/main.dart.js:41909:37)
``` 

</p>
</details> 

### Code sample

```
static Future<void> fontGetLoad() async {
      FontLoader fontR = FontLoader("R");
      fontR.addFont(fetchFont());
       await fontR.load();
  }

 static Future<ByteData> fetchFont() async {
     var url = Uri.parse(‘Font Http Url’);
      final response = await http.get(url);
      return ByteData.view(response.bodyBytes.buffer);
 }
``` 

### Logs

<details><summary>Logs</summary>
<p>

```
main.dart.js:8495 OTS parsing error: vhea: Failed to parse table
aUe @ main.dart.js:8495
a5l @ main.dart.js:483
aUq @ main.dart.js:466
ac8 @ main.dart.js:37897
Aw @ main.dart.js:37870
(anonymous) @ main.dart.js:8668
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
aJ_ @ main.dart.js:8671
$1 @ main.dart.js:73384
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
bO @ main.dart.js:41491
w @ main.dart.js:5958
(anonymous) @ main.dart.js:27838
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
$1 @ main.dart.js:41496
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
bO @ main.dart.js:41491
w @ main.dart.js:5958
(anonymous) @ main.dart.js:26366
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
$1 @ main.dart.js:41496
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
bO @ main.dart.js:41491
w @ main.dart.js:5958
(anonymous) @ main.dart.js:26413
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
$1 @ main.dart.js:41496
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
$0 @ main.dart.js:41866
aHW @ main.dart.js:6227
(anonymous) @ main.dart.js:95950
oF @ main.dart.js:42585
mX @ main.dart.js:42561
$0 @ main.dart.js:42633
b7D @ main.dart.js:6137
b7X @ main.dart.js:6139
$1 @ main.dart.js:41446
b9X @ main.dart.js:4782
(anonymous) @ main.dart.js:4790
childList (async)
$1 @ main.dart.js:41453
aTZ @ main.dart.js:6144
aHZ @ main.dart.js:6248
j7 @ main.dart.js:42603
Mz @ main.dart.js:41838
hM @ main.dart.js:41836
bO @ main.dart.js:41752
$1 @ main.dart.js:92443
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
iv @ main.dart.js:41827
aGV @ main.dart.js:6206
$1 @ main.dart.js:42033
$1 @ main.dart.js:45871
aHY @ main.dart.js:6233
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
oH @ main.dart.js:42565
$1 @ main.dart.js:42636
b9X @ main.dart.js:4782
(anonymous) @ main.dart.js:4790
load (async)
abc @ main.dart.js:45288
pR @ main.dart.js:45284
aYs @ main.dart.js:28382
FJ @ main.dart.js:45862
iW @ main.dart.js:45853
gS @ main.dart.js:41938
(anonymous) @ main.dart.js:92409
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
$1 @ main.dart.js:41496
aHY @ main.dart.js:6230
(anonymous) @ main.dart.js:95951
oG @ main.dart.js:42587
$0 @ main.dart.js:41899
xn @ main.dart.js:6105
nm @ main.dart.js:41831
$0 @ main.dart.js:41866
aHW @ main.dart.js:6227
(anonymous) @ main.dart.js:95950
oF @ main.dart.js:42585
mX @ main.dart.js:42561
$0 @ main.dart.js:42633
b7D @ main.dart.js:6137
b7X @ main.dart.js:6139
$1 @ main.dart.js:41446
b9X @ main.dart.js:4782
(anonymous) @ main.dart.js:4790
childList (async)
$1 @ main.dart.js:41453
aTZ @ main.dart.js:6144
aHZ @ main.dart.js:6248
j7 @ main.dart.js:42697
Mz @ main.dart.js:41838
hM @ main.dart.js:41836
bO @ main.dart.js:41488
w @ main.dart.js:5958
(anonymous) @ main.dart.js:1375
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
aNu @ main.dart.js:1376
(anonymous) @ main.dart.js:46593
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
$0 @ main.dart.js:46596
(anonymous) @ main.dart.js:28570
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
$2 @ main.dart.js:28573
b2P @ main.dart.js:4657
b0U @ main.dart.js:7115
b6n @ main.dart.js:27652
(anonymous) @ main.dart.js:27648
$1 @ main.dart.js:28560
$0 @ main.dart.js:28561
b2P @ main.dart.js:4657
b0U @ main.dart.js:7115
b6n @ main.dart.js:27652
(anonymous) @ main.dart.js:27648
onEntrypointLoaded @ (index):86
await in onEntrypointLoaded (async)
didCreateEngineInitializer @ flutter.js:256
Function.$1 @ main.dart.js:102382
(anonymous) @ main.dart.js:8585
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
aJW @ main.dart.js:8587
(anonymous) @ main.dart.js:27631
(anonymous) @ main.dart.js:5968
$2 @ main.dart.js:41502
x @ main.dart.js:5954
aJ1 @ main.dart.js:27633
(anonymous) @ main.dart.js:102408
(anonymous) @ main.dart.js:102402
dartProgram @ main.dart.js:102405
(anonymous) @ main.dart.js:102408
main.dart.js:27642 Exception: SyntaxError: Invalid font data in ArrayBuffer.
main.dart.js:27642 出错：error==>,Exception: Failed to load font 
 出错：stack==>,Exception: Failed to load font
    at Object.c (https://dev.scet.com.cn/mobile/main.dart.js:4701:3)
    at https://dev.scet.com.cn/mobile/main.dart.js:27799:9
    at aIa.a (https://dev.scet.com.cn/mobile/main.dart.js:5968:62)
    at aIa.$2 (https://dev.scet.com.cn/mobile/main.dart.js:41502:14)
    at aGQ.$2 (https://dev.scet.com.cn/mobile/main.dart.js:41499:16)
    at Object.aHX (https://dev.scet.com.cn/mobile/main.dart.js:6236:19)
    at Vy.<anonymous> (https://dev.scet.com.cn/mobile/main.dart.js:95952:70)
    at Yb.Bq (https://dev.scet.com.cn/mobile/main.dart.js:42589:12)
    at l2.amp (https://dev.scet.com.cn/mobile/main.dart.js:41764:18)
    at azh.$0 (https://dev.scet.com.cn/mobile/main.dart.js:41909:37)

``` 

</p>
</details> 

### Flutter Doctor output

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!

<details><summary>flutter doctor -v</summary>
<p>

```
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [版本 10.0.18363.1556], locale zh-CN)
    • Flutter version 3.7.0 on channel stable at D:\tool\flutterSdk3.7.0\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (6 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at E:\tools\AndroidStudioTool\Android\Sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.1
    • ANDROID_HOME = E:\tools\AndroidStudioTool\Android\Sdk
    • Java binary at: D:\tool\android studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\asus\AppData\Local\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio 15 生成工具 2017 15.9.13)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio 15 生成工具 2017 version 15.9.28307.718
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at D:\tool\android studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 4.1)
    • Android Studio at D:\tool\android-studio-ide-4.1.3-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.18363.1556]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by dam-ease** [comment]
Hi @Sansuihe. Thanks for filing this issue. I see you are on an older version of the stable version of flutter. Can you upgrade to the latest versions of flutter to confirm this issue still persists? If it does, kindly share a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. 
Thank you!

**Comment by paul-cunanan** [comment]
Hi @dam-ease.  I'm getting a similar issue.  I have a flutter web app trying to load a .TTF font.  It works fine in Chrome Web desktop, Safari desktop and IOS.  But doesn't work on Android Chrome mobile web.  Below is the code snippet of an initState function in a widget.  I originally just had the font loaded as per the yaml file definition.  But as it wasn't loading, so I manually called the fontLoader functions to find the issue.  I also tried changing the font to load an .OTF, and experienced the same issue SyntaxError: Invalid font data in ArrayBuffer

Here is the code snippet:  

`  @override
  void initState() {
    super.initState();

    _loadFont();
    // initVideo();
  }

  void _loadFont() async {
    try {
      final Future<ByteData> lovelyCoffee =
          rootBundle.load('assets/fonts/LovelyCoffee.ttf');
      final FontLoader fontLoader = FontLoader(_fontName)
        ..addFont(lovelyCoffee);
      fontLoader.load().then(
        (value) {
          setState(() => _isFontLoaded = true);
        },
      ).onError((error, stackTrace) {
        setState(() {
          _isFontLoaded = false;
          _exceptionString = error.toString();
        });
      });
    } catch (e) {
      debugPrint(e.toString());
      setState(() {
        _isFontLoaded = false;
        _exceptionString = e.toString();
      });
    }
  }
`

I'm using the latest stable flutter version:  

`>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 3.5)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.80.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.`
