### ISSUE TITLE
An assertion thrown during the performLayout()

### ISSUE THREAD

**Issue by KennedyKenei** [flutter/flutter#130713]
This bug came when I was working on implementing the stack widget. I implemented the widget in the following manner. First, I designed the layout using a card, then the child a container with the size parameters then placed the stack as the child. Then as for the children, I designed them using the column widget. The following error emerged as a result though the code working on the phone. Please help me understand how to resolve it.

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout().
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1974 pos 13: 'debugDoingThisResize || debugDoingThisLayout || _computingThisDryLayout ||
              (RenderObject.debugActiveLayout == parent && size._canBeUsedByParent)'

The relevant error-causing widget was: 
  Card Card:file:///home/kennedykenei/Documents/raves_app/lib/Ravers/Adult/AdultRaversHome.dart:513:13
When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1974:13)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:1987:6)
#4      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:123:21)
#5      RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:554:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#7      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#9      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#12     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#14     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#17     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#18     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#19     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#20     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#22     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#23     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:491:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#25     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#28     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#31     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#34     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#37     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#40     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#43     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#46     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#48     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:554:11)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#50     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#54     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#55     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056:7)
#56     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
#57     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#59     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#62     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#64     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#66     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#69     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#71     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#73     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#76     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#79     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#82     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#85     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#87     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3751:13)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#89     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#92     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#93     _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:832:15)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#95     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#98     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#101    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#102    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#103    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#104    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#107    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#110    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#112    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3751:13)
#113    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#114    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#115    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#116    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:580:43)
#117    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:607:12)
#118    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#119    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#120    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#121    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#122    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#123    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#124    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#125    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#126    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#127    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#128    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#129    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#130    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#131    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#132    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#133    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:580:43)
#134    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:607:12)
#135    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#136    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#137    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#138    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#139    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#140    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#141    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056:7)
#142    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
#143    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#144    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#145    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#146    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#147    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#148    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#149    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#150    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#151    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#152    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#153    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#154    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#155    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#156    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#157    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#158    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#159    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#160    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#161    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#162    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#163    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#164    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#165    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#166    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#167    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#168    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#169    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#170    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#171    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#172    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#173    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#174    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#175    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#176    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#177    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#178    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#179    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#180    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#181    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3751:13)
#182    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#183    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#184    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#185    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#186    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#187    _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:832:15)
#188    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#189    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#190    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#191    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#192    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#193    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#194    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#195    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#196    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#197    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#198    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#199    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#200    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#201    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#202    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#203    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#204    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#205    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#206    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#207    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#208    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#209    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#210    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#211    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#212    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#213    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#214    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#215    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#216    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#217    RenderView.performLayout (package:flutter/src/rendering/view.dart:173:14)
#218    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2234:7)
#219    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1016:18)
#220    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:492:19)
#221    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#222    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#223    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#224    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#225    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#229    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#2f34e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE DETACHED
...  parentData: MISSING (can use size)
...  constraints: BoxConstraints(0.0<=w<=352.0, 0.0<=h<=Infinity)
...  size: Size(352.0, 548.0)
...  painter: null
...  foregroundPainter: _ShapeBorderPainter#2b22a()
RenderObject: RenderCustomPaint#2f34e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE DETACHED
  parentData: MISSING (can use size)
  constraints: BoxConstraints(0.0<=w<=352.0, 0.0<=h<=Infinity)
  size: Size(352.0, 548.0)
  painter: null
  foregroundPainter: _ShapeBorderPainter#2b22a()
...  child: _RenderInkFeatures#f7a02 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE DETACHED
...    parentData: MISSING (can use size)
...    constraints: BoxConstraints(0.0<=w<=352.0, 0.0<=h<=Infinity)
...    size: Size(352.0, 548.0)
...    child: RenderSemanticsAnnotations#69772 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE DETACHED
...      parentData: MISSING (can use size)
...      constraints: BoxConstraints(0.0<=w<=352.0, 0.0<=h<=Infinity)
...      size: Size(352.0, 548.0)
...      child: RenderConstrainedBox#22ba0 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE DETACHED
...        parentData: MISSING (can use size)
...        constraints: BoxConstraints(0.0<=w<=352.0, 0.0<=h<=Infinity)
...        size: Size(352.0, 548.0)
...        additionalConstraints: BoxConstraints(w=360.0, h=548.0)
...        child: RenderPositionedBox#fda56 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE DETACHED
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=352.0, h=548.0)
...          size: Size(352.0, 548.0)
...          alignment: Alignment.center
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
```

**Comment by dam-ease** [comment]
Hi @KennedyKenei. Kindly share a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code and your `flutter doctor -v`.

**Comment by KennedyKenei** [comment]
I rearranged the widgets starting with the stack widget and then the rest of the widget and it solved the bug. However, I am concerned that using a digit in defining the height constraint in the container as shown below is not a good idea considering the variation in phone sizes all over the world. What do you recommend for defining height constraints?

Stack(
        children: <Widget>[
          Card(
            color: CupertinoColors.extraLightBackgroundGray,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
                  ListTile(
                    leading: Image.asset('lib/assets/images/RAVES.png'),
                    title: const Text('Raves Hub'),
                    subtitle: const Text('Mombasa, Kenya'),
                    trailing: const Icon(Icons.star_sharp),
                  ),
                  Container(
                    alignment: Alignment.center,
                    height: MediaQuery.of(context).size.height - kBottomNavigationBarHeight
                        - kToolbarHeight - kMinInteractiveDimension - kToolbarHeight - 76,
                    width: MediaQuery.of(context).size.width,
                    child: Card(
                      elevation: 20,
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(20.0)
                      ),
                      color: Colors.brown,
                      child: 
                      ),
                    ),
                  )
                ],
              ),
          ),
        ],
      );

**Comment by dam-ease** [comment]
Hi @KennedyKenei. Thanks for your response. Depending on the child of the `Container` widget, you can make use of `MediaQuery` or use `Padding` property to ensure it suits all screen sizes.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you.
