### ISSUE TITLE
Xcode 14. Failed to build iOS app, Xcode Undefined symbol: _SKAdNetwork

### ISSUE THREAD

**Issue by gabrielcerono** [flutter/flutter#130816]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello I am having issues, that is driving me crazy:

I am trying to run a simple flutter app with just a registration screen using Firebase.

I can run the app in a Simulator in Android no problem, and I can also build it from Xcode and it works perfectly. When I try to use "fluter run" with an iPhone simulator I get this error: 

```
[   +8 ms] Failed to build iOS app
[        ] Error (Xcode): Undefined symbol: _SKAdNetworkCoarseConversionValueHigh
           
[   +1 ms] Error (Xcode): Undefined symbol: _SKAdNetworkCoarseConversionValueLow
           
[        ] Error (Xcode): Undefined symbol: _SKAdNetworkCoarseConversionValueMedium
           
[        ] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14.
[   +1 ms] "flutter run" took 152,921ms.
```

I could previously run the baseline app, but this error started happening after importing firebase... I also still cannot understand why I can build it without any issue from Xcode app...

Does anybody has any idea how to fix this? I have tried everything I found on GitHub issues and forums... but not avail. 

### Actual results

```
[   +8 ms] Failed to build iOS app
[        ] Error (Xcode): Undefined symbol: _SKAdNetworkCoarseConversionValueHigh
           
[   +1 ms] Error (Xcode): Undefined symbol: _SKAdNetworkCoarseConversionValueLow
           
[        ] Error (Xcode): Undefined symbol: _SKAdNetworkCoarseConversionValueMedium
           
[        ] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14.
[   +1 ms] "flutter run" took 152,921ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1322:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

### Logs

<details>
<summary>Logs</summary>

```console

[   +8 ms] Failed to build iOS app
[        ] Error (Xcode): Undefined symbol: _SKAdNetworkCoarseConversionValueHigh
           
[   +1 ms] Error (Xcode): Undefined symbol: _SKAdNetworkCoarseConversionValueLow
           
[        ] Error (Xcode): Undefined symbol: _SKAdNetworkCoarseConversionValueMedium
           
[        ] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14.
[   +1 ms] "flutter run" took 152,921ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1322:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel master, 3.13.0-5.0.pre.6, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
    • Flutter version 3.13.0-5.0.pre.6 on channel master at /Users/gabrielcerono/Desktop/dart/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a1190a5a8 (33 hours ago), 2023-07-17 11:42:13 +0300
    • Engine revision 683087731f
    • Dart version 3.1.0 (build 3.1.0-315.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gabrielcerono/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/gabrielcerono/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • 44ECBA47-FD99-4881-9E5F-72983CE11CEF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 114.0.5735.198


[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ncooke3** [comment]
Hi @gabrielcerono, I posted an [answer](https://stackoverflow.com/a/76745758/9331576) for what appears to be the same issue on StackOverflow. @darshankawar is correct that these symbols have a dependency on a particular Xcode version. 

The issue is that Xcode 14.0 is being used here, but the Firebase version being used does not support Xcode 14.0. **Firebase currently supports Xcode 14.1 or later** (this changes over time, so be sure to check [here](https://firebase.google.com/docs/ios/setup#prerequisites) in the docs to know the latest Xcode version to use when updating to the latest Firebase version).

Upgrading to a newer Xcode should resolve the issue.
