### ISSUE TITLE
Documentation bug: text field with label example doesn't run

### ISSUE THREAD

**Issue by MichaelRFairhurst** [flutter/flutter#13089]
I think this example needs to include a `new Scaffold()`: https://flutter.io/text-input/

## Steps to Reproduce

Using the example exactly, I get:

```
I/flutter (28170): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28170): The following assertion was thrown building InputDecorator(decoration: InputDecoration(hintText:
I/flutter (28170): "Type something"), baseStyle: null, isFocused: false, isEmpty: true, dirty):
I/flutter (28170): No Material widget found.
I/flutter (28170): InputDecorator widgets require a Material widget ancestor.
I/flutter (28170): In material design, most widgets are conceptually "printed" on a sheet of material. In Flutter's
I/flutter (28170): material library, that material is represented by the Material widget. It is the Material widget
I/flutter (28170): that renders ink splashes, for instance. Because of this, many material library widgets require that
I/flutter (28170): there be a Material widget in the tree above them.
I/flutter (28170): To introduce a Material widget, you can either directly include one, or use a widget that contains
I/flutter (28170): Material itself, such as a Card, Dialog, Drawer, or Scaffold.
I/flutter (28170): The specific widget that could not find a Material ancestor was:
I/flutter (28170):   InputDecorator(decoration: InputDecoration(hintText: "Type something"), baseStyle: null,
I/flutter (28170):   isFocused: false, isEmpty: true)
I/flutter (28170): The ownership chain for the affected widget is:
I/flutter (28170):   InputDecorator ← AnimatedBuilder ← Listener ← _GestureSemantics ← RawGestureDetector ←
I/flutter (28170):   GestureDetector ← TextField ← Column ← MySetupPage ← _ModalScopeStatus ← ⋯
I/flutter (28170): 
I/flutter (28170): When the exception was thrown, this was the stack:
I/flutter (28170): #0      debugCheckHasMaterial.<anonymous closure> (package:flutter/src/material/debug.dart:26)
I/flutter (28170): #1      debugCheckHasMaterial (package:flutter/src/material/debug.dart:41)
I/flutter (28170): #2      InputDecorator.build (package:flutter/src/material/input_decorator.dart:430)
I/flutter (28170): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3605)
I/flutter (28170): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3550)
I/flutter (28170): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #42     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4638)
I/flutter (28170): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #73     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #83     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #86     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #95     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #101    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #108    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #109    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #115    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #118    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4638)
I/flutter (28170): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #121    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493)
I/flutter (28170): #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #127    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
Syncing files to device ONEPLUS A5000...                  
I/flutter (28170): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #137    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #141    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #142    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #143    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #147    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #150    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #151    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #155    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #156    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #157    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #158    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #159    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #161    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #162    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #163    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #166    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533)
I/flutter (28170): #167    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #171    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #172    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #173    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #176    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #177    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #178    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #179    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #180    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #182    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #183    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #184    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #185    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #186    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #188    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #189    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #190    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #194    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #195    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #196    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #200    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #202    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #204    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #206    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #207    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #208    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #209    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #210    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #213    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #214    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #215    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #216    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #219    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #220    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #221    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #224    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #226    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #227    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #228    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #229    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #230    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #232    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #233    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #234    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #235    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #236    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #238    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #239    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #240    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #241    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #242    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #243    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #244    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #245    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #246    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #247    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #248    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #249    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #251    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #252    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #253    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #254    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #255    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #257    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #258    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #259    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668)
I/flutter (28170): #260    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #261    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #262    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #263    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562)
I/flutter (28170): #264    Element.rebuild (package:flutter/src/widgets/framework.dart:3451)
I/flutter (28170): #265    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530)
I/flutter (28170): #266    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525)
I/flutter (28170): #267    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter (28170): #268    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter (28170): #269    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:809)
I/flutter (28170): #270    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:780)
I/flutter (28170): #271    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:726)
I/flutter (28170): #272    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2231)
I/flutter (28170): #273    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:725)
I/flutter (28170): #274    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:616)
I/flutter (28170): #275    runApp (package:flutter/src/widgets/binding.dart:658)
I/flutter (28170): #276    main (file:///home/mfairhurst/dart/reader/lib/main.dart:6)
I/flutter (28170): #277    _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
I/flutter (28170): #278    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
I/flutter (28170): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (28170): Another exception was thrown: No Material widget found.
I/flutter (28170): Another exception was thrown: A vertical RenderFlex overflowed by 199269 pixels.
```

## Flutter Doctor

```
~/dart/reader φ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/mfairhurst/dart/flutter
    • Framework revision e8aa40eddd (4 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[-] IntelliJ IDEA Ultimate Edition (version 2016.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 162.2485
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[-] IntelliJ IDEA Ultimate Edition (version 2017.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 172.2791
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[-] IntelliJ IDEA Ultimate Edition (version 2016.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 163.8651
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected devices
    • None
```

**Comment by Hixie** [comment]
Not necessarily a Scaffold, but you do need a Material, as it says in the error message.

The examples intentionally don't list everything because that would get tedious. We generally assume you have a MaterialApp and a Scaffold in your app.
