### ISSUE TITLE
[Android iOS] Error Occurs when Switching TextField with Chinese Input Method

### ISSUE THREAD

**Issue by sunfa-airgram** [flutter/flutter#130880]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.Place two TextField components on the page.
2.Enter a number in the first TextField, switch to Chinese input method, and continue entering Chinese characters.
3.Switch focus to the second TextField.

### Expected results

After switching the input method, I should be able to enter Chinese characters correctly, and the focus should switch to the next TextField without any errors.

### Actual results

An error occurs when switching to the next TextField. 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
           TextField(),
            TextField(),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/85091498/ccebf1b0-7db2-4824-9ad6-aebc9624a3c4

</details>

### Logs

<details><summary>Logs</summary>

```console
======== Exception caught by services library ======================================================
The following assertion was thrown during method call TextInputClient.updateEditingStateWithTag:
Range end 17 is out of text of length 9
'package:flutter/src/services/text_input.dart':
Failed assertion: line 965 pos 12: 'range.end >= 0 && range.end <= text.length'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TextEditingValue._textRangeIsValid (package:flutter/src/services/text_input.dart:965:12)
#3      new TextEditingValue.fromJSON (package:flutter/src/services/text_input.dart:790:12)
#4      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1811:68)
#5      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1746:20)
#6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:55)
#7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:540:34)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:35)
#9      _invoke2 (dart:ui/hooks.dart:174:13)
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#11     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:686:22)
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 2 frames from class _AssertionError)
call: MethodCall(TextInputClient.updateEditingStateWithTag, [0, {EditableText-859341985: {selectionBase: 9, composingExtent: 17, selectionAffinity: TextAffinity.downstream, text: jdofjckfn, selectionIsDirectional: false, selectionExtent: 9, composingBase: 8}}])
====================================================================================================
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 12.6 21G115 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @sunfa-airgram. Thanks for filing this issue. I‘m able to reproduce this issue on the latest `master` and `stable` channels. The error is logged to the console although it functions fine and you would still be able to continue typing. This issue seems to occur only on Android and iOS as I can't reproduce on the web and desktop(macOS).

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.6 on channel stable at /Users/dammya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)    • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                •
      darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               •
      web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
```
[✓] Flutter (Channel master, 3.13.0-6.0.pre.34, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.13.0-6.0.pre.34 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 37ed50ac34 (2 hours ago), 2023-07-19 05:54:05 -0400
    • Engine revision 09389b16d6
    • Dart version 3.1.0 (build 3.1.0-325.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)    • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```  

</p>
</details>

**Comment by sunfa-airgram** [comment]
> Hi @sunfa-airgram. Thanks for filing this issue. I‘m able to reproduce this issue on the latest `master` and `stable` channels. The error is logged to the console although it functions fine and you would still be able to continue typing. This issue seems to occur only on Android and iOS as I can't reproduce on the web and desktop(macOS).
> 
> flutter doctor -v

Hi @dam-ease. Thank you for confirming the reproduction.
I'm sorry, I haven't tested it on the web and desktop(macOS), but I've noticed that this issue also occurs in 3.7.12.
If possible, I hope this issue can be resolved in the latest version. 
Thank you!

**Comment by LongCatIsLooong** [comment]
> Hi @sunfa-airgram. Thanks for filing this issue. I‘m able to reproduce this issue on the latest `master` and `stable` channels. The error is logged to the console although it functions fine and you would still be able to continue typing. This issue seems to occur only on Android and iOS as I can't reproduce on the web and desktop(macOS).
> 
> flutter doctor -v

What keyboard did you use to reproduce it on Android? I don't think this is reproducible on Android using Gboard since Gboard doesn't use composing region for pinyin input?

**Comment by dam-ease** [comment]
Hi @LongCatIsLooong. Apologies for the late response. I recently formatted the physical Android device I was previously using and can't seem to remember the keyboard with which this was reproduced. Tried reproducing with Gboard keyboard and this doesn't reproduce.
Thank you!

**Comment by LongCatIsLooong** [comment]
The iOS text input plugin implementation removes the text and resets the selection, but doesn't clear the marked text range when `resignFirstResponder` is called.
