### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by PrashanthKumarDS-yourdost** [flutter/flutter#130869]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --web-renderer html --dart-define=flutter.inspector.structuredErrors=true lib/main-staging.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 3.0.2, on Ubuntu 22.04.2 LTS 5.19.0-46-generic, locale en_IN)
    • Flutter version 3.0.2 at /home/prashanthkumards/snap/flutter/common/flutter
    • Upstream repository unknown
    • Framework revision cd41fdd495 (1 year, 1 month ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/prashanthkumards/Android/Sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (version 2022.2)
    • Android Studio at /snap/android-studio/126/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 72.1.1
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 115.0.5790.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
cloud_firestore-4.4.5
cloud_firestore_web-3.3.5
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
file_picker-4.6.1
firebase_auth-4.3.0
firebase_auth_web-5.2.10
firebase_core-2.8.0
firebase_core_web-2.2.2
firebase_database-10.0.16
firebase_database_web-0.2.1+25
firebase_messaging-14.3.0
firebase_messaging_web-3.2.17
firebase_remote_config-3.0.15
firebase_remote_config_web-1.1.24
flutter_downloader-1.10.2
flutter_native_timezone-2.0.0
flutter_plugin_android_lifecycle-2.0.14
fluttertoast-8.2.1
package_info-2.0.2
path_provider-2.0.14
path_provider_android-2.0.27
path_provider_foundation-2.2.1
path_provider_linux-2.1.10
path_provider_windows-2.0.7
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.8
permission_handler_windows-0.1.2
share_plus-4.5.3
share_plus_linux-3.0.1
share_plus_macos-3.0.1
share_plus_web-3.1.0
share_plus_windows-3.0.1
shared_preferences-2.1.0
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.1
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
url_launcher-6.1.10
url_launcher_android-6.0.26
url_launcher_ios-6.0.18
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.16
url_launcher_windows-3.0.6
video_player-2.6.1
video_player_android-2.4.3
video_player_avfoundation-2.3.9
video_player_web-2.0.16
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.8.0
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by danagbemava-nc** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/95916. 

It ha already been fixed on newer versions of flutter. You are using an older version of flutter. Kindly upgrade to the latest version of flutter stable. 

Closing from here as this has already been fixed. 

Thank you
