### ISSUE TITLE
url_launcher crashes on iOS

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13082]
## Steps to Reproduce

1. Add `url_launcher` to `pubspec.yaml` pointing to head of git:
```
  url_launcher:
    git:
      url: git://github.com/flutter/plugins/
      path: packages/url_launcher
```

2. Add this to `main.dart`:

```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(new MaterialApp(home: new MyHomePage()));

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new RaisedButton(
        onPressed: () {
          launch('http://flutter.io');
        },
        child: new Text('Click me'),
      ),
    );
  }
}
```

3. Run the program against the iOS simulator
4. Click the button in the app
5. After the page has loaded, click the 'X' button in the top, right-hand corner

=> app crashes with:

```
PlatformException(Error, Error while launching http://flutter.io, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
<asynchronous suspension>
#2      launch (package:url_launcher/url_launcher.dart:19:19)
#3      MyHomePage.build.<anonymous closure> (/Users/mit/Library/Developer/CoreSimulator/Devices/A9635DDE-7C2D-4BD3-969D-279994B6E85E/data/Containers/Data/Application/22433235-D926-412A-A298-D243C8F64E65/tmp/urltestoAPtow/urltest/lib/main.dart:19:11)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:323:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:375:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/ta<…>
```

**Comment by mit-mit** [comment]
cc @mehmetf @xster

**Comment by mit-mit** [comment]
Apologies, I had not upgraded to the latest push of the package. It works great after doing that!
