### ISSUE TITLE
no such file or directory running flutter run command on linux Mint 18

### ISSUE THREAD

**Issue by isleofmax** [flutter/flutter#13083]
This is the crash report when I try to run "flutter run" command on my linux Mint

## command

flutter build flx --suppress-analytics --target /home/massimo/prove/myapp/lib/main.dart --output-file /home/massimo/prove/myapp/build/app/intermediates/flutter/debug/app.flx --snapshot /home/massimo/prove/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin --depfile /home/massimo/prove/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --working-dir /home/massimo/prove/myapp/build/app/intermediates/flutter/debug/flx

## exception

ProcessException: ProcessException: No such file or directory
  Command: /home/massimo/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot --await_is_keyword --causal_async_stacks --vm_snapshot_data=/home/massimo/flutter/bin/cache/artifacts/engine/linux-x64/vm_isolate_snapshot.bin --isolate_snapshot_data=/home/massimo/flutter/bin/cache/artifacts/engine/linux-x64/isolate_snapshot.bin --packages=/home/massimo/prove/myapp/.packages --dependencies=/home/massimo/prove/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --print_snapshot_sizes --snapshot_kind=script --script_snapshot=/home/massimo/prove/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin --enable-mirrors=false /home/massimo/prove/myapp/lib/main.dart

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:126)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:54)
#2      Snapshotter._build (package:flutter_tools/src/base/build.dart:210)
<asynchronous suspension>
#3      Snapshotter.buildScriptSnapshot (package:flutter_tools/src/base/build.dart:175)
<asynchronous suspension>
#4      build (package:flutter_tools/src/flx.dart:58)
<asynchronous suspension>
#5      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:44)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:253)
<asynchronous suspension>
#7      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:193)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#11     new Future.sync (dart:async/future.dart:222)
#12     CommandRunner.run (package:args/command_runner.dart:109)
#13     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#14     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     runZoned (dart:async/zone.dart:1467)
#20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#21     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#23     main (file:///home/massimo/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[-] Flutter (on Linux, locale it_IT.UTF-8, channel alpha)
    • Flutter at /home/massimo/flutter
    • Framework revision e8aa40eddd (5 settimane fa), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /home/massimo/Android/Sdk
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /home/massimo/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/massimo/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • KIW L21 • W6HDU16112003516 • android-arm • Android 6.0.1 (API 23)

```

**Comment by Hixie** [comment]
Try running `sudo apt-get install lib32stdc++6`. (See the message in "flutter doctor".)
