### ISSUE TITLE
Problem with rendering ScrollablePositionedList

### ISSUE THREAD

**Issue by sviluppobss** [flutter/flutter#130866]
The first element of the ScrollablePositionedList did not work as expected:

```
======== Exception caught by Flutter framework =====================================================
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.getLayoutExplorerNode":
MultiChildRenderObjectElement unmounted
'package:flutter/src/widgets/framework.dart':
Failed assertion: line 5859 pos 12: '_renderObject != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderObjectElement.renderObject (package:flutter/src/widgets/framework.dart:5859:12)
#3      MultiChildRenderObjectElement.renderObject (package:flutter/src/widgets/framework.dart:6489:18)
#4      WidgetInspectorService._getLayoutExplorerNode.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:2054:71)
#5      InspectorSerializationDelegate.additionalNodeProperties (package:flutter/src/widgets/widget_inspector.dart:3634:53)
#6      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#7      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#8      _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#9      WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1652:18)
#10     WidgetInspectorService._getLayoutExplorerNode (package:flutter/src/widgets/widget_inspector.dart:2045:14)
#11     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:936:32)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
====================================================================================================

======== Exception caught by Flutter framework =====================================================
The following _TypeError was thrown during a service extension callback for "ext.flutter.inspector.getDetailsSubtree":
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      Element.widget (package:flutter/src/widgets/framework.dart:3361:31)
#1      LeafRenderObjectElement.debugDescribeChildren (package:flutter/src/widgets/framework.dart:6401:12)
#2      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2936:48)
#3      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1609:32)
#4      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#5      _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#6      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#8      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#9      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#10     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#11     new List.of (dart:core-patch/array_patch.dart:47:28)
#12     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#13     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#14     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#15     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#16     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#17     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#18     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#19     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#20     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#21     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#22     new List.of (dart:core-patch/array_patch.dart:47:28)
#23     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#24     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#25     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#26     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#27     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#28     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#29     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#30     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#31     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#32     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#33     new List.of (dart:core-patch/array_patch.dart:47:28)
#34     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#35     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#36     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#37     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#38     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#39     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#40     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#41     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#42     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#43     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#44     new List.of (dart:core-patch/array_patch.dart:47:28)
#45     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#46     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#47     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#48     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#49     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#50     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#51     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#52     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#53     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#54     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#55     new List.of (dart:core-patch/array_patch.dart:47:28)
#56     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#57     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#58     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#59     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#60     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#61     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#62     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#63     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#64     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#65     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#66     new List.of (dart:core-patch/array_patch.dart:47:28)
#67     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#68     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#69     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#70     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#71     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#72     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#73     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#74     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#75     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#76     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#77     new List.of (dart:core-patch/array_patch.dart:47:28)
#78     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#79     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#80     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#81     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#82     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#83     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#84     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#85     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#86     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#87     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#88     new List.of (dart:core-patch/array_patch.dart:47:28)
#89     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#90     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#91     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#92     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#93     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#94     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#95     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#96     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#97     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#98     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#99     new List.of (dart:core-patch/array_patch.dart:47:28)
#100    ListIterable.toList (dart:_internal/iterable.dart:214:7)
#101    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#102    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#103    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#104    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#105    WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1652:18)
#106    WidgetInspectorService._getDetailsSubtree (package:flutter/src/widgets/widget_inspector.dart:1924:12)
#107    WidgetInspectorService.initServiceExtensions.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:1174:21)
#108    BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:936:32)
<asynchronous suspension>
====================================================================================================

======== Exception caught by Flutter framework =====================================================
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.getLayoutExplorerNode":
MultiChildRenderObjectElement unmounted
'package:flutter/src/widgets/framework.dart':
Failed assertion: line 5859 pos 12: '_renderObject != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderObjectElement.renderObject (package:flutter/src/widgets/framework.dart:5859:12)
#3      MultiChildRenderObjectElement.renderObject (package:flutter/src/widgets/framework.dart:6489:18)
#4      WidgetInspectorService._getLayoutExplorerNode.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:2054:71)
#5      InspectorSerializationDelegate.additionalNodeProperties (package:flutter/src/widgets/widget_inspector.dart:3634:53)
#6      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#7      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#8      _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4841:45)
#9      WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1652:18)
#10     WidgetInspectorService._getLayoutExplorerNode (package:flutter/src/widgets/widget_inspector.dart:2045:14)
#11     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:936:32)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by dam-ease** [comment]
Hi @sviluppobss
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps
