### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1992 pos 12: '_elements.contains(element)': is not true. error occurs in the dart in flutter

### ISSUE THREAD

**Issue by 5undaram900d** [flutter/flutter#130852]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

This message shown in the flutter when I  running my app, Please help me, How can I resolve it.

also some of the line shown in the error -
The relevant error-causing widget was: 
  GetMaterialApp GetMaterialApp:file:///D:/Flutter%20Tut/GetX/getx_tut/lib/main.dart:20:12
When the exception was thrown, this was the stack: 
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:1992:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3911:30)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:35)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)

**Comment by 5undaram900d** [comment]
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> 
> This message shown in the flutter when I running my app, Please help me, How can I resolve it.
> 
> also some of the line shown in the error - The relevant error-causing widget was: GetMaterialApp GetMaterialApp:file:///D:/Flutter%20Tut/GetX/getx_tut/lib/main.dart:20:12 When the exception was thrown, this was the stack: #2 _InactiveElements.remove (package:flutter/src/widgets/framework.dart:1992:12) #3 Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3911:30) #4 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:35) #5 Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18) #6 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16) #7 Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7) #8 StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5) #9 Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)

**Comment by 5undaram900d** [comment]
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> 
> This message shown in the flutter when I running my app, Please help me, How can I resolve it.
> 
> also some of the line shown in the error - The relevant error-causing widget was: GetMaterialApp GetMaterialApp:file:///D:/Flutter%20Tut/GetX/getx_tut/lib/main.dart:20:12 When the exception was thrown, this was the stack: #2 _InactiveElements.remove (package:flutter/src/widgets/framework.dart:1992:12) #3 Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3911:30) #4 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:35) #5 Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18) #6 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16) #7 Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7) #8 StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5) #9 Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)

I resolve the problem, basically error occurring due to the route problem by Getx, Initially I take the GetMaterialApp on the both main and home page and I had define all route with incluting initial route property in home page, then but according to app initial route was main page show that I remove initial route property, and in main.dart I take MaterialApp in place of GetMaterialApp. So this problem resolve.
May be this will help if anyone got such type of error.
