### ISSUE TITLE
Using a label without a text controller throws "toDouble called on null"

### ISSUE THREAD

**Issue by MichaelRFairhurst** [flutter/flutter#13090]
## Steps to Reproduce

```
    return new Scaffold(                                                         
        appBar: new AppBar(                                                      
          title: new Text('Enter text to read'),                                 
        ),                                                                       
        body: new Center(                                                        
          child: new TextField(                                                  
              maxLines: null,                                                    
              decoration: new InputDecoration(                                   
                hintText: 'Enter some text for paced reading',                   
              ),                                                                 
              onChanged: _action,                                                
              onSubmitted: (String str) {                                        
                Navigator.of(context).push(new MaterialPageRoute<Null>(          
                    builder: (_) => new MyReadPage(text: str)));                 
              }),                                                                
        ));                 
```

Though, it seems to happen somewhat sporadically. First it happened on first load, later it happened upon deleting some characters.

## Logs

```
I/flutter (28170): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28170): The following NoSuchMethodError was thrown building _TextSelectionHandleOverlay(dirty, state:
I/flutter (28170): _TextSelectionHandleOverlayState#8b639):
I/flutter (28170): The method 'toDouble' was called on null.
I/flutter (28170): Receiver: null
I/flutter (28170): Tried calling: toDouble()
I/flutter (28170): 
I/flutter (28170): When the exception was thrown, this was the stack:
I/flutter (28170): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter (28170): #1      double./ (dart:core-patch/dart:core/double.dart:41)
I/flutter (28170): #2      _TextSelectionHandleOverlayState.build (package:flutter/src/widgets/text_selection.dart:512:49)
I/flutter (28170): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3640:27)
I/flutter (28170): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3550:15)
I/flutter (28170): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter (28170): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (28170): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:22)
I/flutter (28170): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter (28170): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (28170): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (28170): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4533:14)
I/flutter (28170): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (28170): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (28170): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter (28170): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter (28170): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (28170): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:22)
I/flutter (28170): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter (28170): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (28170): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (28170): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter (28170): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter (28170): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (28170): #24     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:22)
I/flutter (28170): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3525:5)
I/flutter (28170): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (28170): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (28170): #28     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4325:32)
I/flutter (28170): #29     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4648:17)
I/flutter (28170): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (28170): #31     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (28170): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (28170): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3562:16)
I/flutter (28170): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3451:5)
I/flutter (28170): #35     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2251:33)
I/flutter (28170): #36     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:580:20)
I/flutter (28170): #37     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:200:5)
I/flutter (28170): #38     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713:15)
I/flutter (28170): #39     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649:9)
I/flutter (28170): #40     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
I/flutter (28170): #41     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:80)
I/flutter (28170): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

analyze reported no issues

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/mfairhurst/dart/flutter
    • Framework revision e8aa40eddd (4 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[-] IntelliJ IDEA Ultimate Edition (version 2016.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 162.2485
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[-] IntelliJ IDEA Ultimate Edition (version 2017.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 172.2791
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[-] IntelliJ IDEA Ultimate Edition (version 2016.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 163.8651
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.
```

**Comment by MichaelRFairhurst** [comment]
Looks like this might occur on long press?

**Comment by MichaelRFairhurst** [comment]
Looks like a duplicate of https://github.com/flutter/flutter/issues/11573
