### ISSUE TITLE
Flutter web release build failed with optimization options.

### ISSUE THREAD

**Issue by kj415j45** [flutter/flutter#130961]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create an empty flutter project with `flutter create .`
2. Build the project with command `flutter build web --release --dart2js-optimization=O0`.
3. Serve the web build via [`http-server`](https://www.npmjs.com/package/http-server).
4. Visit web via Safari.

### Expected results

Example app is loading and runs correctly.

### Actual results

Flutter engine failed to initialize. Console log reports an error:
```
[Error] Unhandled Promise Rejection: NoSuchMethodError: method not found: 'clear$0' (J.getInterceptor$ax(receiver).clear$0 is not a function. (In 'J.getInterceptor$ax(receiver).clear$0(receiver)', 'J.getInterceptor$ax(receiver).clear$0' ...

[Warning] Rejecting promise with error: NoSuchMethodError: method not found: 'clear$0' (J.getInterceptor$ax(receiver).clear$0 is not a function. (In 'J.getInterceptor$ax(receiver).clear$0(receiver)', 'J.getInterceptor$ax(receiver).clear$0' is undefined)) (main.dart.js, line 24272)
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

App template code without any modification.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[  +14 ms] executing: [/Users/imac/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +90 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] executing: [/Users/imac/Development/flutter/] git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[ +394 ms] Exit code 0 from: git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[   +3 ms] 3.10.6
[   +5 ms] executing: [/Users/imac/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +8 ms] executing: sw_vers -productName
[  +34 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] macOS
[        ] executing: sw_vers -productVersion
[  +43 ms] Exit code 0 from: sw_vers -productVersion
[   +1 ms] 12.6.2
[        ] executing: sw_vers -buildVersion
[  +40 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 21G320
[        ] executing: uname -m
[  +14 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +16 ms] executing: sysctl hw.optional.arm64
[  +11 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +2 ms] sysctl: unknown oid 'hw.optional.arm64'
[  +19 ms] executing: [/Users/imac/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[   +5 ms] origin/stable
[   +1 ms] executing: [/Users/imac/Development/flutter/] git ls-remote --get-url origin
[  +79 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +340 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +14 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +274 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +38 ms] Changing current working directory to: /Users/imac/Desktop/working/flutter-build-web
[ +179 ms] Skipping pub get: version match.
[ +714 ms] Generating /Users/imac/Desktop/working/flutter-build-web/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +189 ms] generated_plugin_registrant.dart not found. Skipping.
[   +2 ms] Compiling lib/main.dart for the Web...
[  +10 ms] Initializing file store
[  +16 ms] Done initializing file store
[ +191 ms] Skipping target: web_entrypoint
[   +2 ms] Skipping target: gen_localizations
[   +9 ms] web_static_assets: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were missing:
/Users/imac/Desktop/working/flutter-build-web/.dart_tool/flutter_build/59d92f6a7f86309985f6b50aa267327f/flutter.js,/Users/imac/Desktop/working/flutter-build-web/.dart_tool/flutter_build/5
9d92f6a7f86309985f6b50aa267327f/canvaskit/skwasm.js,/Users/imac/Desktop/working/flutter-build-web/.dart_tool/flutter_build/59d92f6a7f86309985f6b50aa267327f/canvaskit/skwasm.wasm,/Users/im
ac/Desktop/working/flutter-build-web/.dart_tool/flutter_build/59d92f6a7f86309985f6b50aa267327f/canvaskit/chromium/canvaskit.js,/Users/imac/Desktop/working/flutter-build-web/.dart_tool/flu
tter_build/59d92f6a7f86309985f6b50aa267327f/canvaskit/chromium/canvaskit.wasm,/Users/imac/Desktop/working/flutter-build-web/.dart_tool/flutter_build/59d92f6a7f86309985f6b50aa267327f/canva
skit/canvaskit.js,/Users/imac/Desktop/working/flutter-build-web/.dart_tool/flutter_build/59d92f6a7f86309985f6b50aa267327f/canvaskit/canvaskit.wasm,/Users/imac/Desktop/working/flutter-buil
d-web/.dart_tool/flutter_build/59d92f6a7f86309985f6b50aa267327f/canvaskit/skwasm.worker.js}
[+1007 ms] Skipping target: dart2js
[   +3 ms] web_static_assets: Complete
[ +488 ms] Skipping target: web_release_bundle
[ +559 ms] Skipping target: web_service_worker
[   +1 ms] Persisting file store
[  +14 ms] Done persisting file store
[  +34 ms] Compiling lib/main.dart for the Web... (completed in 2,314ms)
[   +3 ms] "flutter web" took 3,933ms.
[ +188 ms] ensureAnalyticsSent: 167ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 12.6.2 21G320 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at /Users/imac/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/imac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] VS Code (version 1.81.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.68.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.2 21G320 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.98

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Thanks for your report. I can see this issue on the latest master channel as well. Verified this with local server in Python and Safari/Chrome browsers.

But I see the issue only occurs with optimization level 0 (`--dart2js-optimization=0`). It works fine with levels 2/3/4. 

<details>
<summary>Strack trace from browser console</summary>

```console
localhost/:1 Uncaught (in promise) JsNoSuchMethodError {__js_helper$_message: 'J.getInterceptor$ax(...).clear$0 is not a function', _method: 'clear$0', _receiver: undefined, $thrownJsError: TypeError: J.getInterceptor$ax(...).clear$0 is not a function
    at Object.clear$0$ax (http://loca…}$thrownJsError: TypeError: J.getInterceptor$ax(...).clear$0 is not a function
    at Object.clear$0$ax (http://localhost:8088/main.dart.js:48733:44)
    at http://localhost:8088/main.dart.js:7846:17
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8088/main.dart.js:18998:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8088/main.dart.js:81541:12)
    at Object._asyncStartSync (http://localhost:8088/main.dart.js:18963:20)
    at Object._downloadAssetFonts (http://localhost:8088/main.dart.js:7874:16)
    at http://localhost:8088/main.dart.js:7784:139
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8088/main.dart.js:18998:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8088/main.dart.js:81541:12)
    at Object._asyncStartSync (http://localhost:8088/main.dart.js:18963:20)$cachedTrace: _StackTrace {_exception: TypeError: J.getInterceptor$ax(...).clear$0 is not a function
    at Object.clear$0$ax (http://loca…, _trace: null}message: "J.getInterceptor$ax(...).clear$0 is not a function"stack: "TypeError: J.getInterceptor$ax(...).clear$0 is not a function\n    at Object.clear$0$ax (http://localhost:8088/main.dart.js:48733:44)\n    at http://localhost:8088/main.dart.js:7846:17\n    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8088/main.dart.js:18998:15)\n    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8088/main.dart.js:81541:12)\n    at Object._asyncStartSync (http://localhost:8088/main.dart.js:18963:20)\n    at Object._downloadAssetFonts (http://localhost:8088/main.dart.js:7874:16)\n    at http://localhost:8088/main.dart.js:7784:139\n    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8088/main.dart.js:18998:15)\n    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8088/main.dart.js:81541:12)\n    at Object._asyncStartSync (http://localhost:8088/main.dart.js:18963:20)"[[Prototype]]: Error__js_helper$_message: "J.getInterceptor$ax(...).clear$0 is not a function"_method: "clear$0"_receiver: undefined[[Prototype]]: Error$isJsNoSuchMethodError: ƒ JsNoSuchMethodError(t0, t1, t2)$isNoSuchMethodError: 1constructor: ƒ JsNoSuchMethodError(t0, t1, t2)toString$0: ƒ toString$0(_)[[Prototype]]: Object
Promise.then (async)
onEntrypointLoaded @ (index):55
didCreateEngineInitializer @ flutter.js:278
_callMethodUnchecked1 @ main.dart.js:24285
FlutterLoaderExtension_didCreateEngineInitializer @ main.dart.js:7887
(anonymous) @ main.dart.js:24901
(anonymous) @ main.dart.js:18998
call$2 @ main.dart.js:81541
_asyncStartSync @ main.dart.js:18963
webOnlyWarmupEngine$body @ main.dart.js:24908
webOnlyWarmupEngine @ main.dart.js:24870
(anonymous) @ main.dart.js:46501
(anonymous) @ main.dart.js:18998
call$2 @ main.dart.js:81541
_asyncStartSync @ main.dart.js:18963
main @ main.dart.js:46508
(anonymous) @ main.dart.js:152702
(anonymous) @ main.dart.js:152685
dartProgram @ main.dart.js:152696
(anonymous) @ main.dart.js:152704

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 hours ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.13.0-7.0.pre.27, on macOS 13.4.1 22F770820d darwin-x64, locale en-VN)
    • Flutter version 3.13.0-7.0.pre.27 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 123413b052 (39 minutes ago), 2023-07-19 22:37:23 -0400
    • Engine revision 56e88e8b0e
    • Dart version 3.1.0 (build 3.1.0-328.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by yjbanov** [comment]
This looks like a compiler issue. Consider filing an issue at https://github.com/dart-lang/sdk/issues.
