### ISSUE TITLE
Flake: Windows build_tests_1_4 fails to find Visual Studio toolchain

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#130916]
This blocked the engine roll once:
- https://github.com/flutter/flutter/pull/130903
- ci: https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20build_tests_1_4/3874/overview
- stdout: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8775126610645379105/+/u/run_test.dart_for_build_tests_shard_and_subshard_1_4/test_stdout

```
[   +4 ms] Unable to find suitable Visual Studio toolchain. Please run `flutter doctor` for more details.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:77:5)
           #2      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:56:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1322:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

**Comment by bdero** [comment]
This de-flaked. Zach mentioned this might be due to the scheduler sometimes running tasks against the wrong machine.

**Comment by godofredoc** [comment]
Change to fail the build when vs_build does not install correctly: https://flutter-review.googlesource.com/c/recipes/+/55163

**Comment by godofredoc** [comment]
Closing this issue, with the recipe change above failures to install vs_build will be correctly reported as an infra issue rather than as a test issue.
