### ISSUE TITLE
/api/file_flaky_issue_and_pr keeps failing

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#130902]
```
FormatException: Unexpected character (at line 5, character 1)
-->
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:913:48)
#2      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      retrieveMetaTagsFromContent (package:cocoon_service/src/request_handlers/flaky_handler_utils.dart:380:10)
#7      getExistingIssues (package:cocoon_service/src/request_handlers/flaky_handler_utils.dart:240:44)
<asynchronous suspension>
#8      FileFlakyIssueAndPR.get (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:54:53)
<asynchronous suspension>
#9      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:50:24)
<asynchronous suspension>
#10     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:151:9)
<asynchronous suspension>
#11     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)
<asynchronous suspension>
#12     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:293:11)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
This has been fixed.
