### ISSUE TITLE
Internal error 'Cannot register an empty map of shortcuts' when trying MenuBar example with at least one shortcut specifiedd

### ISSUE THREAD

**Issue by hydroper** [flutter/flutter#131137]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This code is based on the first example at the [`MenuBar` API documentation](https://api.flutter.dev/flutter/material/MenuBar-class.html).

1. Run `flutter create bug`
2. Run `cd bug`
3. Place code sample at `lib/main.dart` and `lib/ui/menu_bar.dart`
4. Run `flutter run`

### Expected results

A menu bar with an incomplete context menu.

### Actual results

Internal error:

> Cannot register an empty map of shortcuts

I've provided at least one shortcut.

### Code sample

<details><summary>Code sample</summary>

**lib/main.dart**

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import './ui/menu_bar.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      shortcuts: <LogicalKeySet, Intent>{
        LogicalKeySet(LogicalKeyboardKey.keyB): Intent.doNothing,
      },
      home: const MyHomePage(title: 'Bug Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  ShortcutRegistryEntry? _shortcutsEntry;

  @override
  void dispose() {
    _shortcutsEntry?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(children: <Widget>[
        MenuBar(
          children: MenuEntry.build(_getMenus()),
        ),
        Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text(
                'Nothing here',
              ),
            ],
          ),
        )
      ]),
    );
  }

  List<MenuEntry> _getMenus() {
    final List<MenuEntry> result = [
      MenuEntry(
        label: 'File',
        menuChildren: <MenuEntry>[
          MenuEntry(
            label: 'New File...',
            onPressed: () {
              // show dialog
            },
          ),
        ],
      ),
    ];
    _shortcutsEntry?.dispose();
    _shortcutsEntry =
        ShortcutRegistry.of(context).addAll(MenuEntry.shortcuts(result));
    return result;
  }
}
```

**lib/ui/menu_bar.dart**

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class MenuEntry {
  const MenuEntry(
      {required this.label, this.shortcut, this.onPressed, this.menuChildren})
      : assert(menuChildren == null || onPressed == null,
            'onPressed is ignored if menuChildren are provided');
  final String label;

  final MenuSerializableShortcut? shortcut;
  final VoidCallback? onPressed;
  final List<MenuEntry>? menuChildren;

  static List<Widget> build(List<MenuEntry> selections) {
    Widget buildSelection(MenuEntry selection) {
      if (selection.menuChildren != null) {
        return SubmenuButton(
          menuChildren: MenuEntry.build(selection.menuChildren!),
          child: Text(selection.label),
        );
      }
      return MenuItemButton(
        shortcut: selection.shortcut,
        onPressed: selection.onPressed,
        child: Text(selection.label),
      );
    }

    return selections.map<Widget>(buildSelection).toList();
  }

  static Map<MenuSerializableShortcut, Intent> shortcuts(
      List<MenuEntry> selections) {
    final Map<MenuSerializableShortcut, Intent> result =
        <MenuSerializableShortcut, Intent>{};
    for (final MenuEntry selection in selections) {
      if (selection.menuChildren != null) {
        result.addAll(MenuEntry.shortcuts(selection.menuChildren!));
      } else {
        if (selection.shortcut != null && selection.onPressed != null) {
          result[selection.shortcut!] =
              VoidCallbackIntent(selection.onPressed!);
        }
      }
    }
    return result;
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/110610266/849367a5-52aa-49fa-8145-e352f7b54719)

</details>

### Logs

<details><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MyHomePage(dirty, dependencies:
[_ShortcutRegistrarScope], state: _MyHomePageState#55081):
Cannot register an empty map of shortcuts
'package:flutter/src/widgets/shortcuts.dart':
Failed assertion: line 1242 pos 12: 'value.isNotEmpty'

The relevant error-causing widget was:
  MyHomePage
  MyHomePage:file:///C:/Users/Mathe/UnsyncDocuments/Flutter%20Projects/bug/lib/main.dart:23:19

When the exception was thrown, this was the stack:
#2      ShortcutRegistry.addAll (package:flutter/src/widgets/shortcuts.dart:1242:12)
#3      _MyHomePageState._getMenus (package:bug/main.dart:83:38)
#4      _MyHomePageState.build (package:bug/main.dart:51:37)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5242:11)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (220 frames)
#231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#232    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#233    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (467 frames)
#700    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#701    Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#702    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1240:16)
#703    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1209:5)
#704    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
(package:flutter/src/widgets/binding.dart:1156:18)
#705    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720:19)
#706    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1155:13)
#707    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:988:7)
#708    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:7)
#712    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-US)
    • Flutter version 3.10.6 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (10 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.80.1)
    • VS Code at C:\Users\Mathe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1992]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.201
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.82

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by hydroper** [comment]
I've also tried using `Shortcuts` around the home widget instead of specifying the map directly in the `MaterialApp` and same result.

**Comment by danagbemava-nc** [comment]
Hi @hydroper, it seems like your inner `MenuEntry` (the one with the label `New File`)  is missing a shortcut definition, can you try adding one to see if you still get the error?

**Comment by hydroper** [comment]
@danagbemava-nc Yeah, right, adding a shortcut to that `MenuEntry` solves the problem. In the API's example they omitted it for one of the `MenuEntry`ies, so I thought it could work.

**Comment by danagbemava-nc** [comment]
The example worked because there was at least one shortcut in the ShortCutRregistry. 

Closing from here as this has been resolved. 

Thank you
