### ISSUE TITLE
[google_maps_flutter] PlatformException(error, Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0.

### ISSUE THREAD

**Issue by AngeloAvv** [flutter/flutter#131158]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^4.0.1
  collection: ^1.17.0
  copy_with_extension: ^5.0.3
  cupertino_icons:
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  flutter_offline: ^3.0.0
  equatable: ^2.0.5
  intl: ^0.18.0
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.0.15
  path: ^1.8.3
  pretty_dio_logger: ^1.3.1
  timeago: ^3.5.0
  url_launcher: ^6.1.12
  google_maps_flutter: ^2.3.1
  google_maps_cluster_manager: ^3.0.0+1
  geolocator: ^9.0.2
  numberpicker: ^2.1.2
  permission_handler: ^10.4.2
  rxdart: ^0.27.7
  sliding_up_panel: ^2.0.0+1
  retrofit: ^4.0.1
  app_settings: ^5.0.0
  tuple: ^2.0.2
  settings_ui: ^2.0.2
  flutter_essentials_kit: ^2.4.0
  rate_my_app: ^2.0.0
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3
  google_mobile_ads: ^3.0.0
  app_tracking_transparency: ^2.0.4
  auto_route: ^7.7.0
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^9.1.2
  provider: ^6.0.5
  dio: ^5.2.1+1
  nested: ^1.0.0
  pine: ^1.0.2
  logger: ^1.4.0
  webfeed_revised: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.3
  flutter_lints: ^2.0.2
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  drift_dev: ^2.9.0
  auto_route_generator: ^7.2.0
  freezed: ^2.3.5
  mockito: ^5.4.2
  data_fixture_dart: ^2.2.0
  network_info_plus: ^4.0.0
  visibility_detector: ^0.3.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/resources/google_maps/dark_mode.json
```

</details>

### Steps to reproduce

Cannot reproduce locally, and found crashes on crashlytics.

Related to [this](https://github.com/flutter/flutter/issues/27936) and [this](https://github.com/firebase/flutterfire/issues/445).

### Expected results

According to [this](https://github.com/flutter/flutter/issues/27936), by adding an addPostFrameCallback the issue should be solved, but it's not

### Actual results

App is randomly crashing when trying to animate camera and center the markers. App stability is reduced to approx 65 to 75% due to this problem

### Code sample

<details><summary>Code sample</summary>

``` dart
Widget _googleMaps(
    BuildContext context, {
    required models.Route route,
    List<Vehicle> vehicles = const [],
    Shape? shape,
  }) {
    final primaryColor = Theme.of(context).primaryColor;
    final stopsMarkerFuture = route.stops.futureIndexedMap(
      (index, stop) async {
        final icon = await getMarkerBitmap(
          size: 75,
          text: '${index + 1}',
          primaryColor: primaryColor,
        );

        return Marker(
          markerId: MarkerId(stop.id.toString()),
          position: stop.location,
          consumeTapEvents: false,
          draggable: false,
          icon: icon!,
        );
      },
    );
    final vehiclesMarkerFuture = vehicles.futureMap(
      (vehicle) async {
        final icon = await getMarkerBitmap(
          size: 75,
          icon: Icons.directions_bus,
          primaryColor: Colors.blue,
        );

        return Marker(
          markerId: MarkerId(vehicle.id.toString()),
          position: vehicle.coordinates,
          consumeTapEvents: false,
          draggable: false,
          icon: icon!,
        );
      },
    );

    return FutureBuilder<List<List<Marker>>>(
      future: Future.wait<List<Marker>>([
        stopsMarkerFuture,
        vehiclesMarkerFuture,
      ]),
      builder: (context, futures) {
        final stops = futures.hasData ? futures.data![0] : <Marker>[];
        final vehicles = futures.hasData ? futures.data![1] : <Marker>[];
        final markers = <Marker>{...stops, ...vehicles};
        final polyLines = <Polyline>{};

        if (shape?.polygons?.isNotEmpty ?? false) {
          polyLines.add(shape!.polyLines);
        }

        return markers.isEmpty
            ? const CenterCircularProgressIndicator()
            : GoogleMap(
                zoomGesturesEnabled: false,
                zoomControlsEnabled: false,
                tiltGesturesEnabled: false,
                scrollGesturesEnabled: false,
                rotateGesturesEnabled: false,
                myLocationButtonEnabled: false,
                mapToolbarEnabled: false,
                buildingsEnabled: false,
                compassEnabled: false,
                indoorViewEnabled: false,
                trafficEnabled: false,
                initialCameraPosition: App.initialCameraPosition,
                onMapCreated: (controller) {
                  if (context.mounted &&
                      context.read<ThemeCubit>().state.isDark) {
                    final mapStyle = context
                        .read<DarkModeConfigCubit>()
                        .state
                        .googleMapsStyle;

                    if (mapStyle != null) {
                      controller.setMapStyle(mapStyle);
                    }
                  }

                  WidgetsBinding.instance.addPostFrameCallback((_) async {
                    try {
                      await controller.getVisibleRegion();
                      controller.animateCamera(
                        vehicles.isEmpty
                            ? CameraUpdate.newLatLngBounds(
                                stops.bounds,
                                50,
                              )
                            : CameraUpdate.newLatLngZoom(
                                vehicles.first.position,
                                15,
                              ),
                      );
                    } catch (error, stackTrace) {
                      if (context.mounted) {
                        context.read<AppLoggerService>().error(
                              _tag,
                              'Cannot animate camera',
                              error: error,
                          stackTrace: stackTrace,
                            );
                      }
                    }
                  });
                },
                markers: markers,
                polylines: polyLines,
              );
      },
    );
  }
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occurred for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions., null, com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occurred for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
	at com.google.maps.api.android.lib6.common.m.h(:com.google.android.gms.dynamite_mapsdynamite@232517028@23.25.17 (100400-0):0)
	at com.google.maps.api.android.lib6.gmm6.api.c.l(:com.google.android.gms.dynamite_mapsdynamite@232517028@23.25.17 (100400-0):1)
	at com.google.maps.api.android.lib6.impl.ae.a(:com.google.android.gms.dynamite_mapsdynamite@232517028@23.25.17 (100400-0):0)
	at com.google.maps.api.android.lib6.gmm6.api.c.z(:com.google.android.gms.dynamite_mapsdynamite@232517028@23.25.17 (100400-0):3)
	at com.google.maps.api.android.lib6.impl.bk.o(:com.google.android.gms.dynamite_mapsdynamite@232517028@23.25.17 (100400-0):1)
	at com.google.android.gms.maps.internal.i.bb(:com.google.android.gms.dynamite_mapsdynamite@232517028@23.25.17 (100400-0):263)
	at m.fm.onTransact(:com.google.android.gms.dynamite_mapsdynamite@232517028@23.25.17 (100400-0):4)
	at android.os.Binder.transact(Binder.java:949)
	at m3.a.u1(Unknown Source:7)
	at q3.h0.R6(Unknown Source:8)
	at p3.c.f(Unknown Source:11)
	at io.flutter.plugins.googlemaps.GoogleMapController.F(Unknown Source:2)
	at io.flutter.plugins.googlemaps.GoogleMapController.a(Unknown Source:1029)
	at c6.k$a.a(Unknown Source:17)
	at p5.c.l(Unknown Source:18)
	at p5.c.m(Unknown Source:40)
	at p5.c.i(Unknown Source:0)
	at p5.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at<truncated: 307 chars>
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:652)
       at MethodChannel._invokeMethod(platform_channel.dart:310)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-arm64, locale it-IT)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/angeloavv/fvm/versions/3.10.6. Consider adding /Users/angeloavv/fvm/versions/3.10.6/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.3)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @AngeloAvv. Thanks for filing this issue. From the logs, this might not be specific to flutter. I can see a similar/related issue in https://github.com/react-native-maps/react-native-maps/issues/3154. Can you try out either of the suggested solutions to see if any works in your case?

**Comment by kaciula** [comment]
@dam-ease The Fluttter google map API does not provide a callback for when the map has been loaded. We only have onMapCreated and I and others assumed that it's safe to do operations on the map at this point.

The Android maps API has a onLoadedCallback method to notify when the map has actually been loaded on screen.

**Comment by AngeloAvv** [comment]
Hi @dam-ease . I don't know how to reproduce the React Native behavior on a Flutter Framework. I feel like the SDKs are conceived and act differently.

I also tried switching from animateCamera to moveCamera as suggested but it didn't fix the problem. I released something like more than fifteen different versions with tentative fixes and none of them solved the problem. My app stability is around 70% due to this unknown failure which is completely unreproducible on my devices using both debug and release build targets.

From what I understand, sounds like the Google Maps SDK is calling the onMapCreated even though the map hasn't really been loaded yet, causing the app to crash when we try to perform map operations with its controller, which is a contradiction.

**Comment by dam-ease** [comment]
Hi @AngeloAvv @kaciula. Thanks for your response. Trying to check with your code on my end, can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code? Taking out the code snippet you attached above might take out the reproducibility of the issue.
