### ISSUE TITLE
type 'Null' is not a subtype of type 'bool'

### ISSUE THREAD

**Issue by Sanchit-Batra** [flutter/flutter#131122]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Access the given repo
2. Run it
3. Try to click on the edit icon and search for a location that has a timezone (for eg. Cairo)
4. Select it.

### Expected results

It is expected that after selecting the item it should change the time on the home screen and other such data.

### Actual results

Instead, it is returning an error saying: 

type 'Null' is not a subtype of type 'bool'

### Code sample

Path to git repo: [World-Time](https://github.com/Sanchit-Batra/World-Clock)

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building Home(dirty, dependencies: [_ModalScopeStatus], state: _HomeState#51f36):
type 'Null' is not a subtype of type 'bool'

The relevant error-causing widget was: 
  Home Home:file:///Users/sanchitbatra/StudioProjects/world_time/lib/main.dart:13:34
When the exception was thrown, this was the stack: 
#0      _HomeState.build (package:world_time/pages/home.dart:29:27)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#6      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#7      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#10     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
```
</details>
<details><summary>Simulator</summary>
type 'Null' is not a subtype of type 'bool'
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale en-US)
    • Flutter version 3.10.6 on channel stable at /Users/sanchitbatra/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (10 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/sanchitbatra/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.69.20230703

[✓] Connected device (2 available)
    • iPhone 14 Pro Max (mobile) • B99E9B8C-45F5-4B81-94D5-FE403B6CDCC0 • ios          •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64 • macOS 13.4 22F66 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by stuartmorgan** [comment]
As indicated in the stack, this error is coming from that project's code, not Flutter. For help with your own code, consider trying one of the resources listed at https://flutter.dev/community#community-grid

Closing as this is not a Flutter bug.
