### ISSUE TITLE
Exception caught by gesture

### ISSUE THREAD

**Issue by AlbertoSavazzi** [flutter/flutter#131259]
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
scroll_controller.dart:1
Failed assertion: line 105 pos 12: '_positions.isNotEmpty'

When the exception was thrown, this was the stack
#2      ScrollController.position
scroll_controller.dart:105
#3      RawScrollbarState.handleThumbPressUpdate
scrollbar.dart:1794
#4      RawScrollbarState._gestures.<anonymous closure>.<anonymous closure>
scrollbar.dart:1967
#5      LongPressGestureRecognizer._checkLongPressMoveUpdate.<anonymous closure>
long_press.dart:753
#6      GestureRecognizer.invokeCallback
recognizer.dart:275
#7      LongPressGestureRecognizer._checkLongPressMoveUpdate
long_press.dart:753
#8      LongPressGestureRecognizer.handlePrimaryPointer
long_press.dart:652
#9      PrimaryPointerGestureRecognizer.handleEvent
recognizer.dart:630
#10     PointerRouter._dispatch
pointer_router.dart:98
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure>
pointer_router.dart:143
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#13     PointerRouter._dispatchEventToRoutes
pointer_router.dart:141
#14     PointerRouter.route
pointer_router.dart:127
#15     GestureBinding.handleEvent
binding.dart:465
#16     GestureBinding.dispatchEvent
binding.dart:445
#17     RendererBinding.dispatchEvent
binding.dart:331
#18     GestureBinding._handlePointerEventImmediately
binding.dart:400
#19     GestureBinding.handlePointerEvent
binding.dart:363
#20     GestureBinding._flushPointerEventQueue
binding.dart:320
#21     GestureBinding._handlePointerDataPacket
binding.dart:293
#22     _invoke1 (dart:ui/hooks.dart:158:13)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
Handler: "onLongPressMoveUpdate"
Recognizer: _ThumbPressGestureRecognizer#31ad7
    debugOwner: _MaterialScrollbarState#c714b(tickers: tracking 2 tickers)
    state: possible

**Comment by dam-ease** [comment]
Hi @AlbertoSavazzi 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
