### ISSUE TITLE
[Flutter][iOS][NoInternet]The http request close with `HttpException: Operation timed out` occasionally at the first time network down

### ISSUE THREAD

**Issue by LongXiangGuo** [flutter/flutter#131379]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Open the flutter app in iPhone device, turn off the network and go to other page with network request.

### Expected results

When no internet work, the network request should return SocketException error

### Actual results

When the iPhone change to no network, the http request show `HttpException: Operation timed out` occasionally at the first time network down, could not to display the correct error page based on the general timeout errors.

### Code sample

Trying to produce.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console

This tracker is for issues related to:

* Dart core libraries ("dart:async", "dart:io", etc.)
* Dart SDK Version: Dart SDK version: 2.19.6 (stable)

Device: iPhone 12 ,16.0

When the iPhone change to no network, the http request show `HttpException: Operation timed out` occasionally at the first time network down, could not to display the correct error page based on the general timeout errors.

- Correct exception type when no internet.


[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed host lookup: 'cj.sina.com.cn' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:694)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1855)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:297)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2462)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2906)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2911)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2766)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2609)
#10     _MyHomePageState._makeRequest.<anonymous closure> (package:example/main.dart:45)
#11     new _GrowableList.generate (dart:core-patch/growable_ar<…>

- Wrong exception type


2023-07-17T14:28:11.975506 - [ERROR] [NET] GenericError (999) - HttpException: Operation timed out, uri = https://xxxxxx.xxxxx/settings on Request: GET https://xxxxx.xxx.com/xxxx/settings  CorrelationId: 9187e616-fee3-4b0b-895e-c1122c795dc7 
#1      FutureExtensions.onError.<anonymous closure> (dart:async/future.dart:1048)
#2      _rootRunBinary (dart:async/zone.dart:1422)
#3      _CustomZone.runBinary (dart:async/zone.dart:1314)
#4      _FutureListener.handleError (dart:async/future_impl.dart:162)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779)
#6      Future._propagateToListeners (dart:async/future_impl.dart:800)
#7      Future._completeError (dart:async/future_impl.dart:575)
#8      Future.wait.handleError (dart:async/future.dart:507)
#9      _rootRunBinary (dart:async/zone.dart:1422)
#10     _CustomZone.runBinary (dart:async/zone.dart:1314)
#11     _FutureListener.handleError (dart:async/future_impl.dart:162)
#12     Future._propagateToListeners.handleError (dart:async/future_impl.dart:779)
#13     Future._propagateToListeners (dart:async/future_impl.dart:800)
#14     Future._completeError (dart:async/future_impl.dart:575)
#15     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:520)
#16     _rootRun (dart:async/zone.dart:1398)
#17     _CustomZone.run (dart:async/zone.dart:1300)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1208)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

I could not able to reproduce it the examples, does any one have ideas about it.### 

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```
console
[!] Flutter (Channel unknown, 3.7.12, on macOS 13.3.1 22E772610a darwin-x64,
    locale zh-Hans-CN)
    ! Flutter version 3.7.12 on channel unknown at
      /Users/qxz3ln7/versions/stable
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    • Framework revision 4d9e56e694 (3 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://mobile20unpubfrontdoor.azurefd.net
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @LongXiangGuo, this should be reported on the dart-lang/sdk repo. I see you have already reported this in https://github.com/dart-lang/sdk/issues/53040. 

Closing from here as this involves core dart libraries. 

Please make sure you're using the latest stable version of dart. You may also try the [cupertino_http](https://pub.dev/packages/cupertino_http) package from the dart team to see if it helps. 

Thank you
