### ISSUE TITLE
[camera_android] startImageStream error when imageFormatGroup is JPEG

### ISSUE THREAD

**Issue by lowapple** [flutter/flutter#131320]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Using the [example](https://github.com/flutter/packages/blob/main/packages/camera/camera/example/lib/main.dart) code for Camera as inspiration, create a camera example app in Flutter
2. camera hardware info using
```dart
_cameras = await availableCameras();
```
3. Create camera controller
```dart
controller = CameraController(_cameras[0], ResolutionPreset.max, enableAudio: false, imageFormatGroup: ImageFormatGroup.jpeg)
```
4. Initialize the camera, using `await controller.initialize()`
5. An error occurs when calling the `startImageStream` event registration method after initialization is complete

In my current test, the 
The error does not occur until camera_android version 0.10.8+2. After 0.10.8+3, the error occurs.

If I clear the code below, it works fine.
```java
// code: camera/camera_android/android/src/main/java/io/flutter/plugins/camera/Camera.java:551

// Add pictureImageReader surface to allow for still capture
// during recording/image streaming.
surfaces.add(pictureImageReader.getSurface());
```
The device is a Galaxy Note20 5G.

### Expected results

The image data must come in as a JPEG.

### Actual results

An error occurs when calling startImageStream.

### Code sample

<details><summary>Code sample</summary>

```dart
  @override
  void initState() {
    super.initState();
    controller = CameraController(_cameras[0], ResolutionPreset.max,
        enableAudio: false, imageFormatGroup: ImageFormatGroup.jpeg);
    controller.initialize().then((_) async {
      if (!mounted) {
        return;
      }
      setState(() {});
      await controller.startImageStream((image) {
        // ERROR !!!
      });
    }).catchError((Object e) {
      if (e is CameraException) {
        switch (e.code) {
          case 'CameraAccessDenied':
            // Handle access errors here.
            break;
          default:
            // Handle other errors here.
            break;
        }
      }
    });
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
2023-07-26 17:07:48.437  6728-6798  Camera                  com...flutter_camera_android_stream  I  startPreview
2023-07-26 17:07:48.440  6728-6728  ViewRootIm...nActivity] com...flutter_camera_android_stream  I  MSG_WINDOW_FOCUS_CHANGED 1 1
2023-07-26 17:07:48.444  6728-6728  InputMethodManager      com...flutter_camera_android_stream  D  startInputInner - Id : 0
2023-07-26 17:07:48.444  6728-6728  InputMethodManager      com...flutter_camera_android_stream  I  startInputInner - mService.startInputOrWindowGainedFocus
2023-07-26 17:07:48.452  6728-6803  CameraManagerGlobal     com...flutter_camera_android_stream  I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.example.flutter_camera_android_stream API Level 2
2023-07-26 17:07:48.454  6728-6728  InputMethodManager      com...flutter_camera_android_stream  D  startInputInner - Id : 0
2023-07-26 17:07:48.717  6728-6820  Camera                  com...flutter_camera_android_stream  I  CameraCaptureSession onConfigured
2023-07-26 17:07:48.717  6728-6820  Camera                  com...flutter_camera_android_stream  I  Updating builder settings
2023-07-26 17:07:48.717  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: ExposureLockFeature
2023-07-26 17:07:48.718  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: ExposurePointFeature
2023-07-26 17:07:48.718  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: ZoomLevelFeature
2023-07-26 17:07:48.719  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: AutoFocusFeature
2023-07-26 17:07:48.721  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: NoiseReductionFeature
2023-07-26 17:07:48.722  6728-6820  Camera                  com...flutter_camera_android_stream  I  updateNoiseReduction | currentSetting: fast
2023-07-26 17:07:48.722  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: FocusPointFeature
2023-07-26 17:07:48.723  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: ResolutionFeature
2023-07-26 17:07:48.723  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: SensorOrientationFeature
2023-07-26 17:07:48.723  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: FlashFeature
2023-07-26 17:07:48.723  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: ExposureOffsetFeature
2023-07-26 17:07:48.724  6728-6820  Camera                  com...flutter_camera_android_stream  D  Updating builder with feature: FpsRangeFeature
2023-07-26 17:07:48.725  6728-6820  Camera                  com...flutter_camera_android_stream  I  refreshPreviewCaptureSession
2023-07-26 17:07:48.735  6728-6803  CameraManagerGlobal     com...flutter_camera_android_stream  I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.example.flutter_camera_android_stream API Level 2
2023-07-26 17:07:49.041  6728-6803  BufferQueueProducer     com...flutter_camera_android_stream  I  [SurfaceTexture-0-6728-0](id:1a4800000002,api:4,p:1242,c:6728) queueBuffer: queued for the first time.
2023-07-26 17:07:49.964  6728-6803  CameraManagerGlobal     com...flutter_camera_android_stream  I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.example.flutter_camera_android_stream API Level 2
2023-07-26 17:07:50.281  6728-6728  CameraCaptureSession    com...flutter_camera_android_stream  E  Session 1: Failed to create capture session; configuration failed
2023-07-26 17:07:50.281  6728-6744  _android_strea          com...flutter_camera_android_stream  W  Long monitor contention with owner main (6728) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1339) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative, android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 505ms
2023-07-26 17:07:50.282  6728-6983  Camera                  com...flutter_camera_android_stream  I  CameraCaptureSession onConfigureFailed
2023-07-26 17:07:50.287  6728-6798  _android_strea          com...flutter_camera_android_stream  W  Long monitor contention with owner main (6728) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1339) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 511ms
2023-07-26 17:07:50.289  6728-6771  flutter                 com...flutter_camera_android_stream  E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(CameraAccess, CAMERA_ERROR (3): endConfigure:697: Camera 0: Error configuring streams: Function not implemented (-38), null, null)
                                                                                                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
                                                                                                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      AndroidCamera._startPlatformStream (package:camera_android/src/android_camera.dart:326:5)
                                                                                                    <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.10.5, on macOS 13.4.1 22F770820d darwin-arm64, locale ko-KR)
    ! Flutter version 3.10.5 on channel unknown at /Users/lowapple/Workspace/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 796c8ef792 (6주 전), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lowapple/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/lowapple/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.62+17-CA (build 11.0.18+10-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • SM N981N (mobile) • R3CN70FE9HF • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.


```

</details>

**Comment by dam-ease** [comment]
Hi @lowapple. Thanks for filing this issue. I am unable to reproduce this issue on the latest versions of flutter and the latest version of the camera package `0.10.5+2` using the code sample below. Can you try upgrading to the latest versions of flutter and run below code sample to see if this issue still persists?

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

late List<CameraDescription> _cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  _cameras = await availableCameras();
  runApp(const CameraApp());
}

/// CameraApp is the Main Application.
class CameraApp extends StatefulWidget {
  /// Default Constructor
  const CameraApp({super.key});

  @override
  State<CameraApp> createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  late CameraController controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(_cameras[0], ResolutionPreset.max,
        enableAudio: false, imageFormatGroup: ImageFormatGroup.jpeg);
    controller.initialize().then((_) async {
      if (!mounted) {
        return;
      }
      setState(() {});
      await controller.startImageStream((image) {
        // ERROR !!!
      });
    }).catchError((Object e) {
      if (e is CameraException) {
        switch (e.code) {
          case 'CameraAccessDenied':
            // Handle access errors here.
            break;
          default:
            // Handle other errors here.
            break;
        }
      }
    });
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!controller.value.isInitialized) {
      return Container();
    }
    return MaterialApp(
      home: CameraPreview(controller),
    );
  }
}
``` 


</p>
</details> 

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.6 on channel stable at /Users/dammya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (13 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)    • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                •
      darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               •
      web-javascript • Google Chrome 114.0.5735.248

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by lowapple** [comment]
Yes, I am experiencing the same issue with the latest camera version after upgrading to Flutter 3.10.6.

#### Flutter Doctor Output
<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel unknown, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale ko-KR)
    ! Flutter version 3.10.6 on channel unknown at /Users/lowapple/Workspace/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision f468f3366c (2주 전), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lowapple/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/lowapple/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.62+17-CA (build 11.0.18+10-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • SM N981N (mobile) • R3CN70FE9HF • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 114.0.5735.248

[✓] Network resources
    • All expected network resources are available.


```
</details>

#### Logs
<details>
<summary>Logs</summary>

```
I/Camera  (24039): startPreview
I/ViewRootImpl@9abdc6f[MainActivity](24039): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(24039): startInputInner - Id : 0
I/InputMethodManager(24039): startInputInner - mService.startInputOrWindowGainedFocus
I/CameraManagerGlobal(24039): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.example.flutter_camera_android_stream API Level 2
D/InputMethodManager(24039): startInputInner - Id : 0
I/Camera  (24039): CameraCaptureSession onConfigured
I/Camera  (24039): Updating builder settings
D/Camera  (24039): Updating builder with feature: ExposureLockFeature
D/Camera  (24039): Updating builder with feature: ExposurePointFeature
D/Camera  (24039): Updating builder with feature: ZoomLevelFeature
D/Camera  (24039): Updating builder with feature: AutoFocusFeature
D/Camera  (24039): Updating builder with feature: NoiseReductionFeature
I/Camera  (24039): updateNoiseReduction | currentSetting: fast
D/Camera  (24039): Updating builder with feature: FocusPointFeature
D/Camera  (24039): Updating builder with feature: ResolutionFeature
D/Camera  (24039): Updating builder with feature: SensorOrientationFeature
D/Camera  (24039): Updating builder with feature: FlashFeature
D/Camera  (24039): Updating builder with feature: ExposureOffsetFeature
D/Camera  (24039): Updating builder with feature: FpsRangeFeature
I/Camera  (24039): refreshPreviewCaptureSession
I/CameraManagerGlobal(24039): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.example.flutter_camera_android_stream API Level 2
I/BufferQueueProducer(24039): [SurfaceTexture-0-24039-0](id:5de700000002,api:4,p:1242,c:24039) queueBuffer: queued for the first time.
I/CameraManagerGlobal(24039): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.example.flutter_camera_android_stream API Level 2
I/Camera  (24039): CameraCaptureSession onConfigureFailed
E/CameraCaptureSession(24039): Session 1: Failed to create capture session; configuration failed
W/_android_strea(24039): Long monitor contention with owner main (24039) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1339) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 499ms
I/Camera  (24039): open | onError
I/Camera  (24039): close
E/flutter (24039): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(CameraAccess, CAMERA_ERROR (3): endConfigure:697: Camera 0: Error configuring streams: Function not implemented (-38), null, null)
E/flutter (24039): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (24039): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (24039): <asynchronous suspension>
E/flutter (24039): #2      AndroidCamera._startPlatformStream (package:camera_android/src/android_camera.dart:326:5)
E/flutter (24039): <asynchronous suspension>
E/flutter (24039): 
I/Camera  (24039): open | onClosed
I/CameraManagerGlobal(24039): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.example.flutter_camera_android_stream API Level 2
```
</details>

dpendencies looks like this

```
dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.5+2
```
It works fine after adding dependency_overrides as shown below.
```
dependency_overrides:
  camera_android: 0.10.8+2
```

The test device was a physical device.

**Comment by dam-ease** [comment]
Hi @lowapple. Thanks for confirming. I can see that on my physical android device, the screen shows black but I still can't reproduce the error being logged to the console. After adding dependency_overrides, the camera comes up and works fine. Based on the above crash log you provided, I see there's an open issue that has a similar log: https://github.com/flutter/flutter/issues/102644.
Please try this https://github.com/flutter/flutter/issues/102644#issuecomment-1116766881 to confirm if it works in your use case.

**Comment by cyberpwnn** [comment]
This is still a problem. Android is totally broken on most versions now.
