### ISSUE TITLE
Simple MaterialApp with a home route throws TypeError if inside FutureBuilder

### ISSUE THREAD

**Issue by songyang-dev** [flutter/flutter#131448]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new project with the following three files in the code sample.
2. Launch an Android emulator
3. `flutter run`

### Expected results

Seeing the home screen

### Actual results

Red screen with a yellow error message saying the null check error.

**Possible workaround**
If a `home` argument is added explicitly to the `MaterialApp` and the `'/'` path is removed from the routes, the app runs without issue.

### Code sample

<details><summary>Code sample</summary>

`main.dart`
```dart
import 'package:flutter/material.dart';
import 'package:null_check_error_home_route/routes.dart';

void main(List<String> args) {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Future.value(99),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return MaterialApp(
            routes: appRoutes,
          );
        }

        return const MaterialApp(
          home: Scaffold(
            body: Text("waiting or error"),
          ),
        );
      },
    );
  }
}
```

`routes.dart`
```dart
import 'package:null_check_error_home_route/home.dart';

var appRoutes = {
  '/': (context) => HomeScreen(),
};
```

`home.dart`
```dart
import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Text("Home"),
    );
  }
}

```

</details>

### Logs

<details><summary>Logs</summary>

```console
$ flutter run
Using hardware rendering with device sdk gphone64 x86 64. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Parameter format not correct -
Running Gradle task 'assembleDebug'...                              9.7s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app-debug.apk...        1,895ms

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building Builder:
Null check operator used on a null value

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///C:/Users/songy/Documents/My%20Documents/Professional/2023/Professional%20Development/Flutter%20by%20
  Fireship/apps/null_check_error_home_route/lib/main.dart:17:18

When the exception was thrown, this was the stack:
#0      _WidgetsAppState._onGenerateRoute.<anonymous closure> (package:flutter/src/widgets/app.dart:1414:48)
#1      MaterialPageRoute.buildContent (package:flutter/src/material/page.dart:51:55)
#2      MaterialRouteTransitionMixin.buildPage (package:flutter/src/material/page.dart:109:27)
#3      _ModalScopeState.build.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/routes.dart:951:53)   
#4      Builder.build (package:flutter/src/widgets/basic.dart:7531:48)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:5156:49)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#17     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#31     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#36     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#43     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#48     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#50     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#53     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#55     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#59     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#62     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#64     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#70     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#71     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#78     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#82     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#86     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#91     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#95     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#99     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#105    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#109    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#112    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#114    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#117    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#119    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#122    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#124    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#125    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#126    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#127    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#128    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#129    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)       
#133    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

Syncing files to device sdk gphone64 x86 64...                     113ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on sdk gphone64 x86 64 is available at: http://127.0.0.1:57991/l5f6oQDSWhg=/
The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at:
http://127.0.0.1:9103?uri=http://127.0.0.1:57991/l5f6oQDSWhg=/
W/rror_home_route( 4670): Verification of void androidx.window.java.layout.WindowInfoTrackerCallbackAdapter.<init>(androidx.window.layout.WindowInfoTracker) took 136.398ms (197.95 bytecodes/s) (1960B approximate peak alloc)
W/OpenGLRenderer( 4670): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
W/OpenGLRenderer( 4670): Failed to initialize 101010-2 format, error = EGL_SUCCESS
I/Gralloc4( 4670): mapper 4.x is not supported
E/OpenGLRenderer( 4670): Unable to match the desired swap behavior.
I/Choreographer( 4670): Skipped 43 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer( 4670): Davey! duration=802ms; Flags=1, FrameTimelineVsyncId=12802, IntendedVsync=238445051224, Vsync=239161717862, InputEventId=0, HandleInputStart=239171296927, AnimationStart=239171304957, PerformTraversalsStart=239171307420, DrawStart=239185119874, FrameDeadline=238461717890, FrameInterval=239170206706, FrameStartTime=16666666, SyncQueued=239196507954, SyncStart=239208155207, IssueDrawCommandsStart=239210511540, SwapBuffers=239225964780, FrameCompleted=239259428523, DequeueBufferDuration=1921115, QueueBufferDuration=26778101, GpuCompleted=239257440568, SwapBuffersCompleted=239259428523, DisplayPresentTime=135816958663440, CommandSubmissionCompleted=239225964780,

Application finished.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-CA)
    • Flutter version 3.10.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\songy\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\songy\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.27)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33801.447
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.80.1)
    • VS Code at C:\Users\songy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1992]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.183

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @songyang-dev. Thanks for filing this issue. I am able to produce this issue on the latest versions of flutter as well. There are some possible workarounds/solutions in this [Thread](https://stackoverflow.com/questions/64902427/navigation-problem-with-futurebuilder-and-materialapp). Can you try them out if they match your use case?

**Comment by songyang-dev** [comment]
Hi @dam-ease, thank you for your reply. I have a similar workaround, which I shared in the issue. If this workaround isn't enough for my use case, I will try out the suggestions on your linked thread.
