### ISSUE TITLE
iOS tests skipping remaining tests on unknown error

### ISSUE THREAD

**Issue by baconcheese113** [flutter/flutter#131588]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Unable to reproduce this issue locally, but you can see the logs [here](https://github.com/baconcheese113/handle-it-app/actions/runs/5710329537/job/15470331866) 

### Expected results

I would expect a stacktrace that mentions which error was encountered, instead of saying that both tests passed.
Also the other tests shouldn't be skipped.

### Actual results

Currently it runs 2/4 tests, says they both pass, and then throws `throwToolExit (package:flutter_tools/src/base/common.dart:10:3)`
The other 2 tests are skipped.

### Logs

<details><summary>Logs sample</summary>

```text
✅ auth test Should register
  didNotificationLaunchApp: false, initialRoute: /login, payload: null
  notificationsReady: false
  android local_notifications hasPermissions: null
  Looking for existing token
  app: init state
  Rendering authenticationState.loading true and isLoading true
  Initialroute = /login
  authenticationState listener triggered with loading: false, isLoading = true
  Rendering authenticationState.loading false and isLoading false
  Initialroute = /login
  [VRouter: INFO] Successfully navigated to "/login" using VRouter.to 
  Render of login called
  [VRouter: INFO] Successfully navigated to "/register" using VRouter.to 
  [VRouter: INFO] Successfully navigated to "/home" using VRouter.to 
  Intro tutorial has not been completed
  [VRouter: INFO] Successfully navigated to "/login" using VRouter.to 
  Render of login called
  disposing
Looking for existing token
app: init state
Rendering authenticationState.loading true and isLoading true
Initialroute = /login
authenticationState listener triggered with loading: false, isLoading = true
Rendering authenticationState.loading false and isLoading false
Initialroute = /login
[VRouter: INFO] Successfully navigated to "/login" using VRouter.to 
Render of login called
Render of login called
Render of login called
Render of login called
Render of login called
switchToHome called
[VRouter: INFO] Successfully navigated to "/home" using VRouter.to 
Intro tutorial has been completed
Scanned peripheral HandleIt Hub, MAC a7:c7:93:34:28:e9
Scanned peripheral HandleIt Hub, MAC a7:c7:93:34:28:e9
no devices connected and scan stopped
no devices connected and scan stopped
✅ auth test Should sign-in
  didNotificationLaunchApp: false, initialRoute: /login, payload: null
  notificationsReady: false
  android local_notifications hasPermissions: null
  fcmToken is kys apple
  disposing
[+22995 ms] test 0: Test process is no longer needed by test harness
[   +2 ms] test 0: finished
[   +7 ms] 
[   +5 ms] test 0: cleaning up...
[   +1 ms] test 0: ensuring test device is terminated.
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ] executing: xcrun simctl terminate D2FA4C6B-D1C9-42EB-9B9E-BB6A93829C87 io.handleit.devtest
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:504:7)
[   +4 ms] test 0: Test harness is no longer needed by test process
           <asynchronous suspension>
✅ network test Creates/deletes network and adds members
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
✅ add device test Creates a hub, then adds sensor
           <asynchronous suspension>

           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
🎉 2 tests passed.
           <asynchronous suspension>
[ +179 ms] test package returned with exit code 1
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[   +2 ms] Runtime for phase TestRunner: Wall-clock: 0:06:31.951208; combined: 0:06:31.951321.
           <asynchronous suspension>
[        ] Runtime for phase Compile: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
[        ] Runtime for phase Run: Wall-clock: 0:06:31.396591; combined: 0:06:31.396670.
           <asynchronous suspension>
[   +1 ms] Runtime for phase CoverageTotal: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[        ] Runtime for phase CoverageCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageParseJson: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageAddHitmap: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageDataCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase WatcherFinishedTest: Wall-clock: 0:00:00.004054; combined: 0:00:00.004056.
[   +7 ms] "flutter test" took 402,351ms.
[  +52 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
Error: Process completed with exit code 1.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
 Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-US)
    • Flutter version 3.10.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\bacon\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 115.0.1901.183

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by baconcheese113** [comment]
Hey @darshankawar They are being run in Github Actions, you can view them [here](https://github.com/baconcheese113/handle-it-app/actions/runs/5710329537/job/15470331866)

I'm unable to reproduce this behavior locally, and it only occurs for the iOS tests after upgrading past flutter 3.7.7, which required using macos-13 in place of macos-12 due to the lack of GPU passthrough support as mentioned in [this issue](https://github.com/flutter/flutter/issues/126768#issuecomment-1560529775)

You can follow this pull request to update the flutter version here https://github.com/baconcheese113/handle-it-app/pull/19
Towards the bottom, the commit [clean podfile lock](https://github.com/baconcheese113/handle-it-app/actions/runs/5676527250/job/15383399357) worked outside of the impeller issue, which required bumping up to macos-13 from macos-12.

Then after fixing some issues with postgres and Apple Push Notification (APN)s you can see the issue happening for the commit [don't attempt to get fcm token on iOS due to missing apn api key crash](https://github.com/baconcheese113/handle-it-app/pull/19/commits/bd8ee9b3eb5583788ac376d770052e0bc3789f55)

**Comment by darshankawar** [comment]
Thanks for the update. Keeping the issue open for team's input.

**Comment by baconcheese113** [comment]
I've explored a little more to find exactly where I begin to receive the issue and it appears to work fine on macos-13 with flutter 3.7.12. But upgrading to 3.10.0 reproduces the error, as you can see [here](https://github.com/baconcheese113/handle-it-app/pull/19/commits/12f57d1ccd061145f9f73420142760343e6265b0)

**Comment by stuartmorgan** [comment]
It's really hard to tell what's going on here from the minimal description, without reverse-engineering the CI. Could you please provide (here) the test code, a list of the commands being run ,and the specific error output? If that's too much code or too many steps, please try to make a reduced test case.

**Comment by baconcheese113** [comment]
Hey @stuartmorgan I recently tried to reproduce this with 3.13 instead of 3.10 and I'm no longer running into the error I had before!
You can see the same tests passing with 3.13 [here](https://github.com/baconcheese113/handle-it-app/pull/29)

I'm still unsure what caused this with 3.10, but I'll close this for now. Thanks!
