### ISSUE TITLE
ios_app_with_extensions_test fails when moving to host only

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#131693]
I tried to move the ios_app_with_extension_test to hostonly as it does not seem to involve any steps that require a device. https://github.com/flutter/flutter/pull/131441

However, the new tests are failing due to 

```
[2023-07-28 19:09:21.388161] [STDOUT] stderr: [   +1 ms] CocoaPods not installed or not in valid state.
[2023-07-28 19:09:21.388374] [STDOUT] stderr: [        ] 
[2023-07-28 19:09:21.388386] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[2023-07-28 19:09:21.388393] [STDOUT] stderr:            #1      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:168:9)
[2023-07-28 19:09:21.388400] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388407] [STDOUT] stderr:            #2      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:43:30)
[2023-07-28 19:09:21.388414] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388420] [STDOUT] stderr:            #3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:244:3)
[2023-07-28 19:09:21.388427] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388433] [STDOUT] stderr:            #4      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:651:37)
[2023-07-28 19:09:21.388439] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388446] [STDOUT] stderr:            #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1322:27)
[2023-07-28 19:09:21.388452] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388458] [STDOUT] stderr:            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[2023-07-28 19:09:21.388464] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388471] [STDOUT] stderr:            #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[2023-07-28 19:09:21.388477] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388483] [STDOUT] stderr:            #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
[2023-07-28 19:09:21.388490] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388496] [STDOUT] stderr:            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[2023-07-28 19:09:21.388503] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388509] [STDOUT] stderr:            #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
[2023-07-28 19:09:21.388515] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388521] [STDOUT] stderr:            #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
[2023-07-28 19:09:21.388528] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388534] [STDOUT] stderr:            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[2023-07-28 19:09:21.388540] [STDOUT] stderr:            <asynchronous suspension>
[2023-07-28 19:09:21.388546] [STDOUT] stderr:            #13     main (package:flutter_tools/executable.dart:90:3)
[2023-07-28 19:09:21.388552] [STDOUT] stderr:            <asynchronous suspension>```

Cocoapods are installed on the machine, I'm not sure why it failed. The failure might not be related to whether a device is connected.

Detailed failure log:https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64%20ios_app_with_extensions_test/35/overview

**Comment by cyanglaz** [comment]
cc @keyonghan

**Comment by keyonghan** [comment]
@cyanglaz Could you try adding `{"dependency": "gems", "version": "v3.3.14"},` to the new targets?

**Comment by keyonghan** [comment]
And led shows it passes with the gems dependency:
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/a720e0abfd7369f300d38a5c1f244c600cfdd77b28731c9b09e196f3cc22483f/+/build.proto
