### ISSUE TITLE
 EXCEPTION CAUGHT BY RENDERING LIBRARY

### ISSUE THREAD

**Issue by saqiDev** [flutter/flutter#131722]
```
D/EGL_emulation(16787): app_time_stats: avg=2150.11ms min=37.20ms max=5792.82ms count=3
D/EGL_emulation(16787): app_time_stats: avg=58.93ms min=1.76ms max=1219.83ms count=25
D/EGL_emulation(16787): app_time_stats: avg=53.27ms min=8.37ms max=1049.24ms count=30
D/EGL_emulation(16787): app_time_stats: avg=43.44ms min=2.66ms max=1020.32ms count=34
I/flutter (16787): Slected [Instance of 'Ingredients']
I/flutter (16787): Slected [Instance of 'Ingredients']
D/EGL_emulation(16787): app_time_stats: avg=70.73ms min=3.39ms max=1203.13ms count=23
D/EGL_emulation(16787): app_time_stats: avg=35.15ms min=2.82ms max=800.26ms count=35
I/flutter (16787): Slected [Instance of 'Ingredients', Instance of 'Ingredients']
I/flutter (16787): Slected [Instance of 'Ingredients', Instance of 'Ingredients']
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  DropdownButtonFormField<dynamic>
  DropdownButtonFormField:file:///C:/Projects/what_you_cook_today/lib/screens/admin/recipe_add_screen.dart:149:32

When the exception was thrown, this was the stack:
#2      RenderIndexedStack._childAtIndex (package:flutter/src/rendering/stack.dart:734:12)
#3      RenderIndexedStack.paintStack (package:flutter/src/rendering/stack.dart:760:29)
#4      RenderStack.paint (package:flutter/src/rendering/stack.dart:655:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#7      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2879:15)
#8      RenderFlex.paint (package:flutter/src/rendering/flex.dart:1040:7)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#11     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#17     _RenderDecoration.paint.doPaint (package:flutter/src/material/input_decorator.dart:1538:17)
#18     _RenderDecoration.paint (package:flutter/src/material/input_decorator.dart:1600:5)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#21     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#24     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#36     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#39     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#42     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#43     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#44     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#45     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#47     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#48     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2879:15)
#49     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1040:7)
#50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#52     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#54     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#55     _RenderSingleChildViewport.paint.paintContents (package:flutter/src/widgets/single_child_scroll_view.dart:535:17)
#56     _RenderSingleChildViewport.paint (package:flutter/src/widgets/single_child_scroll_view.dart:549:9)
#57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3059:7)
#58     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#59     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#60     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1147:31)
#61     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494:19)
#62     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#63     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#64     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#65     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#66     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#67     _invoke (dart:ui/hooks.dart:142:13)
#68     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#69     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)

The following RenderObject was being processed when the exception was fired: RenderIndexedStack#42485 relayoutBoundary=up1:
  creator: _RawIndexedStack ← IndexedStack ← Row ← Padding ← ConstrainedBox ← Container ←
    DefaultTextStyle ← _Decorator ← InputDecorator ← Listener ← RawGestureDetector ← GestureDetector ←
    ⋯
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=24.0)
  size: Size(314.2, 24.0)
  alignment: AlignmentDirectional.centerStart
  textDirection: ltr
  fit: loose
  index: 2
This RenderObject had the following descendants (showing up to depth 5):
    child 1: _RenderVisibility#727b6 relayoutBoundary=up2 NEEDS-PAINT
      child: RenderConstrainedBox#31fb6 relayoutBoundary=up3 NEEDS-PAINT
        child: RenderSemanticsAnnotations#d47e5 NEEDS-PAINT
          child: RenderMouseRegion#6eb2c NEEDS-PAINT
            child: RenderSemanticsAnnotations#6bb14 NEEDS-PAINT
    child 2: _RenderVisibility#61e09 relayoutBoundary=up2 NEEDS-PAINT
      child: RenderIgnorePointer#730b6 relayoutBoundary=up3 NEEDS-PAINT
        child: RenderConstrainedBox#00646 relayoutBoundary=up4 NEEDS-PAINT
          child: RenderPositionedBox#89eac relayoutBoundary=up5 NEEDS-PAINT
            child: RenderParagraph#54372 relayoutBoundary=up6 NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 734 pos 12: 'child != null': is not true.

D/EGL_emulation(16787): app_time_stats: avg=443.84ms min=11.93ms max=6637.00ms count=16
```

**Comment by danagbemava-nc** [comment]
Hi @saqiDev,

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Even though the error message says to file an issue, without the information requested above, we cannot proceed with this issue. 

Thank you
