### ISSUE TITLE
[google_maps_flutter_android] `testToggleInfoWindow` persistently flaky

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#131783]
The[ `testToggleInfoWindow` test](https://github.com/flutter/packages/blob/3dc00c1a32f6659206f4e038ce989bb49bdfb36f/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/google_maps_tests.dart#L921) in the `google_maps_flutter_android` integration test suite is persistently flaky and currently blocking the tree. It runs as a part of (and thus fails when running) the tests in `example/integration_test/latest_renderer_test.dart`. This test will be skipped for now, but should be fixed or deleted.

Example failure: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8773902782530458049/+/u/Run_package_tests/Firebase_Test_Lab/stdout

**Stacktrace from logs:**
```
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure was thrown running a test:
Expected: <true>
  Actual: <false>

When the exception was thrown, this was the stack:
#4      googleMapsTests.<anonymous closure> (file:///b/s/w/ir/x/w/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/google_maps_tests.dart:956:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:165:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1008:5)
<asynchronous suspension>
#7      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:799:12)
<asynchronous suspension>

This was caught by the test expectation on the following line:
  file:///b/s/w/ir/x/w/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/google_maps_tests.dart line 956
The test description was:
  testToggleInfoWindow
═════════════════════════════════════════════════════════════════

	at dev.flutter.plugins.integration_test.FlutterTestRunner.run(FlutterTestRunner.java:81)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
```

**Comment by mossmana** [comment]
I'm consistently getting a ```VMServiceFlutterDriver: The root isolate is taking an unusually long time to start.``` error when attempting to run the google_maps integration tests.

**Comment by mossmana** [comment]
At first I theorized that maybe the issue I'm seeing was related to a missing Google Maps API key, but per @stuartmorgan, we aren't using it after the LUCI migration. I'll need to investigate further.

**Comment by mossmana** [comment]
I was able to get the tests to run using the updated instructions on https://github.com/flutter/flutter/wiki/Plugin-Tests, but there are occasional flakes with the other tests in `latest_renderer_test.dart` even before adding back the `testToggleInfoWindow` test:

```00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testLiteModeEnabled - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testRotateGesturesEnabled - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testTiltGesturesEnabled - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testScrollGesturesEnabled - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testInitialCenterLocationAtCenter - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testGetVisibleRegion - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testTraffic - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testBuildings - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testSetMapStyle valid Json String - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testSetMapStyle invalid Json String - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testSetMapStyle null string - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testGetLatLng - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testGetZoomLevel - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testScreenCoordinate - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: testResizeWidget - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: fromAssetImage - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: set tileOverlay correctly - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: update tileOverlays correctly - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: remove tileOverlays correctly - did not complete [E]
00:53 +35 ~10: /Users/mossman/Development/projects/packages/packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/latest_renderer_test.dart: (tearDownAll) - did not complete [E]
00:53 +35 ~10: Some tests failed.```

**Comment by mossmana** [comment]
I created a basic Flutter app with a Google Map in it and the infowindow toggle behavior seems to work for ```GoogleMapController```, so there's likely an issue in the ```ExampleGoogleMapController ```

**Comment by mossmana** [comment]
There were some changes related to markers that could affect this test: https://pub.dev/packages/google_maps_flutter_android/changelog ```2.4.16 - Fixes unawaited_futures violations```

**Comment by mossmana** [comment]
After further investigation, this issue appears related to https://github.com/flutter/flutter/issues/54758. The same workaround appears to address this issue, but it is not an long-term ideal solution as it adds an additional uninterruptible second to the run time of the tests. I'll put up a PR shortly.

**Comment by stuartmorgan** [comment]
> The same workaround appears to address this issue, but it is not a long-term ideal solution as it adds an additional uninterruptible second to the run time of the tests.

Why does the existing wait loop not work, if a sleep does?

**Comment by mossmana** [comment]
I was unable to figure out why. I even tried increasing the number of times
though the loop from 100 to 500 and that did not seem to address the issue.
It seems 1 second is the magic number. Perhaps there was a delay elsewhere
that added up to one second previously that recently got removed?
