### ISSUE TITLE
Build got stuck during cleanup and then timed out

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#131809]
https://luci-milo.appspot.com/ui/p/flutter/builders/try/Mac%20Engine%20Drone/305870/overview

**Comment by zanderso** [comment]
From chat:
```
[I2023-08-02T13:13:31.017976-07:00 38815 0 cleanup.go:42] cleanup "cleanupComplete" succeeded
panic: context deadline exceeded

goroutine 178 [running]:
go.chromium.org/luci/luciexe/host.cleanupSlice.run({0x140008cc540, 0x8, 0x140001cea08?}, {0x1038a2ac0, 0x140005a54a0})
    go.chromium.org/luci/luciexe/host/cleanup.go:46 +0x2cc
go.chromium.org/luci/luciexe/host.Run.func7()
    go.chromium.org/luci/luciexe/host/host.go:161 +0x140
created by go.chromium.org/luci/luciexe/host.Run
    go.chromium.org/luci/luciexe/host/host.go:156 +0xbe0
```

**Comment by yusuf-goog** [comment]
Following up with the LUCI team on what these errors are

**Comment by yusuf-goog** [comment]
Closing, reopen if this happens again.
