### ISSUE TITLE
The Android application crashes when using, which mostly appears in Xiaomi mobile phones

### ISSUE THREAD

**Issue by liuyangzhu** [flutter/flutter#131833]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [ ] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. In most of our application scenarios, flutter_webview can be used to load h5 pages, and some Xiaomi models have irregularly crashed on h5 pages recently. Through the user line trajectory analysis, most problematic users appear in the h5 page during interactive operations.

2. flutter_webview version：3.0.4 

### Expected results

/

### Actual results

/

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
crash message：
Caused by : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
#00 pc 000811aa  /apex/com.android.runtime/lib/bionic/libc.so (__res_nsend+4909)
java stacktrace:
null
```
```console
system error：
0	07-19 18:46:18.915 E/LoadedApk( 2521): Unable to instantiate appComponentFactory
1	07-19 18:46:18.915 E/LoadedApk( 2521): java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/~~Fqys_h2_6zqIuk-K3jsMsg==/com.pazl.jzkapp-U_gyZmCFsDd6uVwd05CJFg==/base.apk"],nativeLibraryDirectories=[/data/app/~~Fqys_h2_6zqIuk-K3jsMsg==/com.pazl.jzkapp-U_gyZmCFsDd6uVwd05CJFg==/lib/arm, /data/app/~~Fqys_h2_6zqIuk-K3jsMsg==/com.pazl.jzkapp-U_gyZmCFsDd6uVwd05CJFg==/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]
2	07-19 18:46:18.915 E/LoadedApk( 2521): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
3	07-19 18:46:18.915 E/LoadedApk( 2521): at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
4	07-19 18:46:18.915 E/LoadedApk( 2521): at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
5	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.LoadedApk.createAppFactory(LoadedApk.java:286)
6	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1056)
7	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.LoadedApk.getClassLoader(LoadedApk.java:1143)
8	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.LoadedApk.getResources(LoadedApk.java:1402)
9	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.ContextImpl.createAppContext(ContextImpl.java:3101)
10	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.ContextImpl.createAppContext(ContextImpl.java:3093)
11	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7024)
12	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
13	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2263)
14	07-19 18:46:18.915 E/LoadedApk( 2521): at android.os.Handler.dispatchMessage(Handler.java:106)
15	07-19 18:46:18.915 E/LoadedApk( 2521): at android.os.Looper.loopOnce(Looper.java:211)
16	07-19 18:46:18.915 E/LoadedApk( 2521): at android.os.Looper.loop(Looper.java:300)
17	07-19 18:46:18.915 E/LoadedApk( 2521): at android.app.ActivityThread.main(ActivityThread.java:8294)
18	07-19 18:46:18.915 E/LoadedApk( 2521): at java.lang.reflect.Method.invoke(Native Method)
19	07-19 18:46:18.915 E/LoadedApk( 2521): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
20	07-19 18:46:18.915 E/LoadedApk( 2521): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
21	--------- beginning of main

```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 11.7.4 20G1120 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.2)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.80.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @liuyangzhu, you are using older versions of both flutter & webview_flutter. Kindly upgrade to the latest stable version of flutter and webview_flutter to see if you still face this issue.  

You may also check https://stackoverflow.com/questions/60472222/e-loadedapk-unable-to-instantiate-appcomponentfactory-only-on-android-q-api-29 to see if you can use anything in there to fix your issue. 

If you still face this issue after upgrading to the latest version of flutter and trying the solution above, please provide the updated output of `flutter doctor -v` and `webview_flutter`. Please also provide the version(s) of android that these devices are crashing on. 

Thank you
