### ISSUE TITLE
View is stretched when using canvaskit in an iFrame

### ISSUE THREAD

**Issue by cordierben** [flutter/flutter#131934]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have an Angular project, with an Iframe containing my Flutter Web project. I want to dynamically set the height of the iframe to make it look like a website, and not an embedded widget inside the iframe.

When running the project with the HTML renderer, the view is correctly displayed, accordingly to the size of the iframe set. However, using canvaskit, the whole Flutter view is stretched and blurred when I want to set a size of ~1150px or more, and then my whole application is stretched until the next resize of the iframe. And as my website contains a lot of animations, I need to use canvaskit

I have seen some similar issues : [#122541](https://github.com/flutter/flutter/issues/122541), I don't really know if this could be related?

I am running the Flutter project in 3.7.12, but I have tried 3.10.5 and the issue was still there.

Steps to reproduce : 

1. Create a Flutter project
2. Embedded it in an HTML Iframe
3. Build and run the project using canvaskit
4. Change the size of the iFrame dynamically (using a button and window.parent.postMessage for instance)

### Expected results

The view is not stretched, the iFrame is resized and when I scroll, it scrolls onto in the Angular project and not in the iFrame

### Actual results

The view is completely stretched, with the top of my view hidden by the header, and no possibility to scroll (the iFrame seems to be correctly resized, but content is stretched)

### Screenshots or Video

Current result : 

<img width="308" alt="Capture d’écran 2023-08-04 à 17 00 56" src="https://github.com/flutter/flutter/assets/61388583/7f532ef8-ed8b-4691-bcd0-45866c603299">

Expected result: 

<img width="308" alt="Capture d’écran 2023-08-04 à 17 02 08" src="https://github.com/flutter/flutter/assets/61388583/958a1459-70af-4ebb-b18c-06911165d082">

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.2 22D49 darwin-arm64, locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

**Comment by huycozy** [comment]
Hi @cordierben 
Issue https://github.com/flutter/flutter/issues/122541 is only mentioned to blurry behavior so I'm not sure if this is the same.

I tried checking this with a minimal sample using `HtmlElementView` but can't reproduce the issue. Perhaps it's not enough implementation code. Could you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by cordierben** [comment]
Hi @huycozy, thanks for your reply.
Yes the issue is a bit different, but the input to reproduce it is pretty much the same.

Here is a minimal reproducible code sample : 

Flutter - main.dart (by clicking one of the amber tiles, you will send a resize event) ==> Flutter 3.7
```
import 'dart:convert';
import 'dart:html';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ListView.builder(
          itemCount: 50,
          itemBuilder: ((context, index) => GestureDetector(
                onTap: () => window.parent?.postMessage(
                    jsonEncode({"type": "pageHeight", "pageHeight": 1700}),
                    '*'),
                child: Container(
                  color: Colors.amber,
                  child: const SizedBox(height: 20, width: 100),
                ),
              )),
        ),
      ),
    );
  }
}
```

Angular - app.component.html (better to do it with a header and a footer to see the iframe be stretched and not the angular part)

```
<app-header></app-header>
<div #flutterContainer id="flutter-container">
	<iframe #iframe id="flutter-iframe" class="absolute w-full h-full opacity-0 z-1000 m-0 p-0"
		src="assets/flutter/index.html" title="Total Energies - Charging Services"></iframe>
</div>
<app-footer>
</app-footer>

```

Angular - app.component.ts (listen to the event and resize the iframe accordingly)

```
this.flutterCommunicationService.eventFlutterPageHeight.subscribe(
			(event) => {
				this.iframe!.nativeElement.style.height = `${event.pageHeight}px`
			},
		);
```

I have made the Angular code poorly as I suppose it can be reproduces using any framework. I can make it more precisely if needed.

**Comment by huycozy** [comment]
Thanks for your update. But I'm not quite familiar with Angular. Can you please provide a complete sample code in a GitHub project and share it here along with detailed steps to replicate the issue?

**Comment by cordierben** [comment]
Ok, I have made a complete Angular/Flutter project and I can reproduce the issue on a mobile device only, there you go : https://github.com/cordierben/iframe-communication-sample

This is the angular project with the iframe and the flutter project contained in the assets to be embedded in the iframe.

Here is also sample-app-resize, which is the flutter project I have put in the iFrame : https://github.com/cordierben/flutter-sample-app-resize

Therefore you just need to download iframe-communication-sample, and `yarn run start` it.
Once it is running, click on one of the text ("Hello") displayed, and it will send an event to resize the iframe, and it will be stretched on a mobile device : 

https://github.com/flutter/flutter/assets/61388583/0fe7c5bb-ab78-4603-9cae-2fbb2aed7946

**Comment by huycozy** [comment]
Thanks for your update. But I got below error when embedding the built flutter web to your Angular project and running it. Am I correct when putting all built Flutter web file into `assets/flutter` directory? Is there any missing steps?

<details>
<summary>Error output log</summary>

```console
GET http://localhost:4200/flutter.js net::ERR_ABORTED 404 (Not Found)
index.html:43 Refused to execute script from 'http://localhost:4200/flutter.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
core.mjs:10194 ERROR SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at iframe-container.component.ts:16:33
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25990:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25990:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:26300:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:483:34)
handleError @ core.mjs:10194
next @ core.mjs:27079
next @ Subscriber.js:91
_next @ Subscriber.js:60
next @ Subscriber.js:31
(anonymous) @ Subject.js:34
errorContext @ errorContext.js:19
next @ Subject.js:27
emit @ core.mjs:22773
(anonymous) @ core.mjs:26339
invoke @ zone.js:368
run @ zone.js:129
runOutsideAngular @ core.mjs:26212
onHandleError @ core.mjs:26339
handleError @ zone.js:372
runTask @ zone.js:176
invokeTask @ zone.js:483
invokeTask @ zone.js:1631
globalCallback @ zone.js:1662
globalZoneAwareCallback @ zone.js:1695
postMessage (async)
sendMsg @ sendMessage.js:10
ok @ index.js:221
(anonymous) @ socket.js:62
client.onmessage @ WebSocketClient.js:45
Show 24 more frames
Show less
index.html:46 Uncaught ReferenceError: _flutter is not defined
    at index.html:46:7
```
</details>

<details>
<summary>Screenshot error</summary>

![Screenshot 2023-08-09 at 11 48 46](https://github.com/flutter/flutter/assets/104349824/8a14c0f9-59bf-48d0-8c24-895af59c8634)

</details>

**Comment by huycozy** [comment]
Thanks for your update, I can run it now. I rebuild Flutter project to check this on the latest SDK. When I rebuild it on the latest Flutter stable 3.10.6 and master channels, then use the built web inside Angular project, it displays well in `html` renderer but is stretched in `canvaskit` renderer.

### Steps to reproduce
I collect all steps above and summarize them here:

1. Clone two projects above:
- Flutter project: https://github.com/cordierben/flutter-sample-app-resize
- Angular project: https://github.com/cordierben/iframe-communication-sample

2. Build web on Flutter project with explicit canvaskit renderer:
```
flutter build web --web-renderer canvaskit
```
3. Copy the built web output files to `iframe-communication-sample/src/assets/flutter` and replace `<base href="/">` with `<base href="./">` in `index.html` file
4. In the root path of `iframe-communication-sample` project, run `yarn run start` (you may need to install some missing packages, just follow the hint in the output console)
5. Open the output web on mobile browser, click on yellow item in the list and observe the result

<details>
<summary>Demo</summary>

<img width="400" src="https://github.com/flutter/flutter/assets/104349824/bf2080e7-25d3-47ff-a6fb-846fb4ad6d0f">
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5195m
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.13.0-19.0.pre.103, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.0-19.0.pre.103 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d7877d1fe0 (43 minutes ago), 2023-08-08 22:27:24 -0400
    • Engine revision 8ec575168d
    • Dart version 3.2.0 (build 3.2.0-42.0.dev)
    • DevTools version 2.26.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by mdebbar** [comment]
The html renderer has been removed, and we made many fixes in the canvaskit renderer. Are you still seeing this issue?
