### ISSUE TITLE
[tool_crash] UnknownException since chrome version 115

### ISSUE THREAD

**Issue by slrongji** [flutter/flutter#131921]
## Command
```
flutter drive --driver=test_driver/integration_e2e_driver.dart --target=e2e/gherkin_suite_test.dart -d chrome --browser-name chrome --driver-port 4444 --web-browser-flag --disable-dev-shm-usage --web-browser-flag --disable-web-security --browser-dimension 1920,1080 --web-renderer canvaskit --release --no-headless
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnknownException
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:102:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:332:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19044.3208], locale en-DE)
    [32m•[39m Flutter version 3.10.6 on channel stable at C:\SDKs\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at C:\Users\diadt659\AppData\Local\Android\Sdk
    [32m•[39m Platform android-33-ext5, build-tools 33.0.2
    [32m•[39m ANDROID_HOME = C:\Users\diadt659\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.25)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    [32m•[39m Visual Studio Community 2019 version 16.11.33423.256
    [32m•[39m Windows 10 SDK version 10.0.20348.0

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2022.3)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.3
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m VS Code (version 1.80.2)
    [32m•[39m VS Code at C:\Users\diadt659\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.70.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.3208]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.171
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.188

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b8f7f1f9869bb2d116aa6a70dbeac61000b52849
### Plugins
app_links-3.4.3
cloud_firestore-4.8.1
cloud_firestore_web-3.6.1
cryptography_flutter-2.3.0
datadog_flutter_plugin-1.5.1
firebase_core-2.14.0
firebase_core_web-2.6.0
flutter_native_splash-2.3.1
integration_test
path_provider_linux-2.1.11
path_provider_windows-2.1.7
shared_preferences-2.1.2
shared_preferences_android-2.1.4
shared_preferences_content_provider-0.0.5
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
url_launcher-6.1.11
url_launcher_android-6.0.35
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6
video_player-2.6.1
video_player_android-2.4.9
video_player_avfoundation-2.4.6
video_player_web-2.0.16
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by dam-ease** [comment]
Hi @slrongji. Thanks for filing this issue. This seems to be similar to https://github.com/flutter/flutter/issues/123602. You can see https://github.com/flutter/flutter/issues/123602#issuecomment-1490895875 and https://github.com/flutter/flutter/issues/123602#issuecomment-1662235796 for solution and check if it works for you.

**Comment by dam-ease** [comment]
Thanks for responding @slrongji. Can you provide more information on how this issue occurs?
