### ISSUE TITLE
`packages_autoroller` step is failing with GitHub auth error

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#131968]
Framework tree is red on the `packages_autoroller` step.

An example failure is here:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20packages_autoroller/6534/overview

```
Executing "gh auth login --hostname github.com --git-protocol https --with-token" in null
Unhandled exception:
Exception: GitException: Exception on command "auth login --hostname github.com --git-protocol https --with-token": error validating token: HTTP 401: Bad credentials (https://api.github.com//)
Try authenticating with:  gh auth login


#0      PackageAutoroller.roll (package:conductor_core/src/packages_autoroller.dart:101:7)
<asynchronous suspension>
#1      run (file:///b/s/w/ir/x/w/flutter/dev/conductor/core/bin/packages_autoroller.dart:88:3)
<asynchronous suspension>
```

It appears GitHub is rejecting our credentials.

**Comment by yusuf-goog** [comment]
token looks like it was updated in July.

**Comment by christopherfujino** [comment]
Lowering the priority as this is no longer blocking the tree

**Comment by yusuf-goog** [comment]
@christopherfujino anything still needs to be done with this?
