### ISSUE TITLE
Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.

### ISSUE THREAD

**Issue by Cadburies** [flutter/flutter#131995]
I was asked to submit this exception....not sure what else you needed so, here is the stack trace:

```
═══════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.
animation_controller.dart:822
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      AnimationController._tick
animation_controller.dart:822
#3      Ticker._tick
ticker.dart:249
#4      SchedulerBinding._invokeFrameCallback
binding.dart:1284
#5      SchedulerBinding.handleBeginFrame.<anonymous closure>
binding.dart:1136
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#7      SchedulerBinding.handleBeginFrame
binding.dart:1134
#8      SchedulerBinding._handleBeginFrame
binding.dart:1051
#9      _invoke1 (dart:ui/hooks.dart:158:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:337:5)
#11     _beginFrame (dart:ui/hooks.dart:101:31)
(elided 2 frames from class _AssertionError)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
#2      SchedulerBinding.scheduleFrameCallback
binding.dart:568
#3      Ticker.scheduleTick
ticker.dart:265
#4      Ticker.start
ticker.dart:171
#5      AnimationController._startSimulation
animation_controller.dart:745
#6      AnimationController._animateToInternal
animation_controller.dart:612
#7      AnimationController.forward
animation_controller.dart:461
#8      ImplicitlyAnimatedWidgetState.didUpdateWidget
implicit_animations.dart:395
#9      StatefulElement.update
framework.dart:5260
#10     Element.updateChild
framework.dart:3686
#11     ComponentElement.performRebuild
framework.dart:5111
#12     StatefulElement.performRebuild
framework.dart:5251
#13     Element.rebuild
framework.dart:4805
#14     StatefulElement.update
framework.dart:5274
#15     Element.updateChild
framework.dart:3686
#16     SingleChildRenderObjectElement.update
framework.dart:6442
#17     Element.updateChild
framework.dart:3686
#18     SingleChildRenderObjectElement.update
framework.dart:6442
#19     Element.updateChild
framework.dart:3686
#20     ComponentElement.performRebuild
framework.dart:5111
#21     StatefulElement.performRebuild
framework.dart:5251
#22     Element.rebuild

framework.dart:4805
#23     BuildOwner.buildScope
framework.dart:2780
#24     WidgetsBinding.drawFrame
binding.dart:903
#25     RendererBinding._handlePersistentFrameCallback
binding.dart:358
#26     SchedulerBinding._invokeFrameCallback
binding.dart:1284
#27     SchedulerBinding.handleDrawFrame
binding.dart:1214
#28     SchedulerBinding._handleDrawFrame
binding.dart:1072
#29     _invoke (dart:ui/hooks.dart:142:13)
#30     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#31     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _FrameCallbackEntry)
════════════════════════════════════════════════════════════════════════════════
```

**Comment by dam-ease** [comment]
Hi @Cadburies.
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Thank you!
