### ISSUE TITLE
Video Player should accept sources with expired SSL

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#131969]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Load any https video url with the site's SSL certificate expired. I dont see any way to override it (please guide if there is a way).
```
VideoPlayerController.networkUrl(Uri.parse(""));
```

### Expected results

Should still load the video/audio

### Actual results

throws exception bad certificate. tried use clear text traffic attribute in android manifests xml and it doesnt work.

also tried HttpOverrides.global, doesnt work.

### Code sample

<details><summary>Code sample</summary>

```dart
VideoPlayerController.networkUrl(Uri.parse("HTTPS_URL_WITH_EXPIRED_SSL"));
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_1691196048](https://github.com/flutter/flutter/assets/3955470/ffd6e630-95ef-47e5-bd14-f9bd5dcd104f)

</details>

### Logs

<details><summary>Logs</summary>

```console
E/ExoPlayerImplInternal( 9723): Playback error
E/ExoPlayerImplInternal( 9723):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
E/ExoPlayerImplInternal( 9723):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 9723):       at android.os.Looper.loopOnce(Looper.java:201)
E/ExoPlayerImplInternal( 9723):       at android.os.Looper.loop(Looper.java:288)
E/ExoPlayerImplInternal( 9723):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 9723):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: Chain validation failed
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:382)
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal( 9723):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/ExoPlayerImplInternal( 9723):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/ExoPlayerImplInternal( 9723):       at java.lang.Thread.run(Thread.java:1012)
E/ExoPlayerImplInternal( 9723):   Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
E/ExoPlayerImplInternal( 9723):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:653)
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:550)
E/ExoPlayerImplInternal( 9723):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:376)
E/ExoPlayerImplInternal( 9723):       ... 7 more
E/ExoPlayerImplInternal( 9723):   Caused by: java.security.cert.CertificateException: Chain validation failed
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:717)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:547)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:568)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:613)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:613)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:503)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:423)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:351)
E/ExoPlayerImplInternal( 9723):       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
E/ExoPlayerImplInternal( 9723):       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:256)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
E/ExoPlayerImplInternal( 9723):       ... 29 more
E/ExoPlayerImplInternal( 9723):   Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
E/ExoPlayerImplInternal( 9723):       at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
E/ExoPlayerImplInternal( 9723):       at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
E/ExoPlayerImplInternal( 9723):       at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
E/ExoPlayerImplInternal( 9723):       at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
E/ExoPlayerImplInternal( 9723):       at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:713)
E/ExoPlayerImplInternal( 9723):       ... 45 more
E/ExoPlayerImplInternal( 9723):   Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Wed Jul 19 16:26:51 GMT+08:00 2023 (compared to Sat Aug 05 08:40:06 GMT+08:00 2023)
E/ExoPlayerImplInternal( 9723):       at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:269)
E/ExoPlayerImplInternal( 9723):       at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
E/ExoPlayerImplInternal( 9723):       at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
E/ExoPlayerImplInternal( 9723):       at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
E/ExoPlayerImplInternal( 9723):       ... 50 more
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-PH)
    • Flutter version 3.10.5 on channel stable at /Users/chitgoks/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/chitgoks/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
This is not configurable at the ExoPlayer level; see https://exoplayer.dev/troubleshooting.html#fixing-sslhandshakeexception-certpathvalidatorexception-and-err_cert_authority_invalid-errors

> also tried HttpOverrides.global, doesnt work.

The network requests are performed by ExoPlayer, so Dart network configuration wouldn't apply to it. If you want to handle this at the Dart level rather than the native Android level, you would need to download the videos, then load them as files.

Closing as out of scope for the plugin.
