### ISSUE TITLE
Using Flutter in Github Codespaces caused a crash

### ISSUE THREAD

**Issue by mark-dropbear** [flutter/flutter#131992]
While attempting to run Flutter in Github Codespaces I created a `launch.json` file (as per these instructions https://docs.flutter.dev/tools/devtools/vscode)  in VSCode with the following contents:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "My App",
            "request": "launch",
            "type": "dart",
            "args": ["--web-hostname=0.0.0.0", "--web-port=3000"]
        },
        {
            "name": "My App (profile mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "profile",
            "args": ["--web-hostname=0.0.0.0", "--web-port=3000"]
        },
        {
            "name": "My App (release mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "release",
            "args": ["--web-hostname=0.0.0.0", "--web-port=3000"]
        }
    ]
}
```

Then I noticed shortly after launching the app had crashed and asked me to file a bug report with the following information as outlined below:

## Command
```
flutter run --machine --start-paused -d web-server --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-server-debug-injected-client-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart --web-hostname=0.0.0.0 --web-port=3000
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:134:32))
```
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:134:32)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#2      new ExtensionDebugger.<anonymous closure> (package:dwds/src/servers/extension_debugger.dart:75:37)
#3      _rootRunUnary (dart:async/zone.dart:1407:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#9      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#11     _rootRunUnary (dart:async/zone.dart:1415:13)
#12     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#17     _StreamController._add (dart:async/stream_controller.dart:650:7)
#18     _StreamController.add (dart:async/stream_controller.dart:598:5)
#19     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:730:21)
#20     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:36)
#21     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:204:15)
#22     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:24)
#23     _rootRunUnary (dart:async/zone.dart:1407:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
```
```
[✓] Flutter (Channel stable, 3.10.6, on Debian GNU/Linux 11 (bullseye) 5.15.0-1042-azure, locale en_US)
    • Flutter version 3.10.6 on channel stable at /home/vscode/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from https://www.freedesktop.org/wiki/Software/pkg-config/

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop)  • linux      • linux-x64      • Debian GNU/Linux 11 (bullseye) 5.15.0-1042-azure
    • Web Server (web) • web-server • web-javascript • Flutter Tools

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null

**Comment by dam-ease** [comment]
Hi @mark-dropbear. From the log, the error seems to be pointing to an external package `built_value`:

```
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:134:32)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)

```

If you follow the same steps to replicate on a new Flutter project, do you still get the same error?

**Comment by mark-dropbear** [comment]
That's quite odd... This was actually a fresh application built using the skeleton template. Repo is open and here but it's a fresh app in every sense. https://github.com/dropbear-software/crm

**Comment by dam-ease** [comment]
Hi @mark-dropbear. Thanks for your response. Cloned the project and tried reproducing it but can't seem to reproduce it. Is there any other additional information that could help in triaging this (reproducible steps)?
