### ISSUE TITLE
[go_router] exception on opening app by deeplink

### ISSUE THREAD

**Issue by dudeck** [flutter/flutter#132044]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Assume that we have a sample Flutter app (com.example.app) which uses goRouter (for example sample from pub dev).
1. Open that app
2. Send app to background
3. Open app using deeplink `yoursScheme://com.example.app`

### Expected results

App is brought from background to front on the same screen that we left it without exception.

### Actual results

App opens on the screen was left going into background but apps throws exception.

Note
When app opened with `yoursScheme://com.example.app/` app goes to home screen configured as "/", but use case is to just bring app from background without chaning the location.

### Code sample

<details><summary>Code sample</summary>

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app shows an app with two screens.
///
/// The first route '/' is mapped to [HomeScreen], and the second route
/// '/details' is mapped to [DetailsScreen].
///
/// The buttons use context.go() to navigate to each destination. On mobile
/// devices, each destination is deep-linkable and on the web, can be navigated
/// to using the address bar.
void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'details',
          builder: (BuildContext context, GoRouterState state) {
            return const DetailsScreen();
          },
        ),
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () => context.go('/details'),
          child: const Text('Go to the Details screen'),
        ),
      ),
    );
  }
}

/// The details screen
class DetailsScreen extends StatelessWidget {
  /// Constructs a [DetailsScreen]
  const DetailsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Details Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () => context.go('/'),
          child: const Text('Go back to the Home screen'),
        ),
      ),
    );
  }
}
```
Sample from pub dev
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
10.10.0 - [FirebaseAnalytics][I-ACS023000] Deep Link Web URL query is empty
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞═════════════════════
flutter: The following RangeError was thrown while dispatching
flutter: notifications for GoRouteInformationProvider:
flutter: RangeError (startIndex): Invalid value: Only valid value is 0: 1
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RangeError.checkValueInInterval (dart:core/errors.dart:313:7)
flutter: #1      _StringBase.replaceFirst (dart:core-patch/string_patch.dart:591:16)
flutter: #2      canonicalUri (package:go_router/src/path_utils.dart:136:17)
flutter: #3      RouteConfiguration.findMatch (package:go_router/src/configuration.dart:271:31)
flutter: #4      GoRouteInformationParser.parseRouteInformationWithDependencies (package:go_router/src/parser.dart:86:23)
flutter: #5      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:705:8)
flutter: #6      _RouterState._handleRouteInformationProviderNotification (package:flutter/src/widgets/router.dart:723:5)
flutter: #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
flutter: #8      GoRouteInformationProvider.notifyListeners (package:go_router/src/information_provider.dart:141:11)
flutter: #9      GoRouteInformationProvider._platformReportsNewRouteInformation (package:go_router/src/information_provider.dart:236:5)
flutter: #10     GoRouteInformationProvider.didPushRouteInformation (package:go_router/src/information_provider.dart:267:5)
flutter: #11     WidgetsBinding._handlePushRouteInformation (package:flutter/src/widgets/binding.dart:685:24)
flutter: <asynchronous suspension>
flutter: #12     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:42)
flutter: <asynchronous suspension>
flutter: #13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:22)
flutter: <asynchronous suspension>
flutter:
flutter: The GoRouteInformationProvider sending notification was:
flutter:   Instance of 'GoRouteInformationProvider'
flutter: ═════════════════════════════════════════════════════════════════
flutter: while dispatching notifications for GoRouteInformationProvider: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞═════════════════════
flutter: The following RangeError was thrown while dispatching
flutter: notifications for GoRouteInformationProvider:
flutter: RangeError (startIndex): Invalid value: Only valid value is 0: 1
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RangeError.checkValueInInterval (dart:core/errors.dart:313:7)
flutter: #1      _StringBase.replaceFirst (dart:core-patch/string_patch.dart:591:16)
flutter: #2      canonicalUri (package:go_router/src/path_utils.dart:136:17)
flutter: #3      RouteConfiguration.findMatch (package:go_router/src/configuration.dart:271:31)
flutter: #4      GoRouteInformationParser.parseRouteInformationWithDependencies (package:go_router/src/parser.dart:86:23)
flutter: #5      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:705:8)
flutter: #6      _RouterState._handleRouteInformationProviderNotification (package:flutter/src/widgets/router.dart:723:5)
flutter: #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
flutter: #8      GoRouteInformationProvider.notifyListeners (package:go_router/src/information_provider.dart:141:11)
flutter: #9      GoRouteInformationProvider._platformReportsNewRouteInformation (package:go_router/src/information_provider.dart:236:5)
flutter: #10     GoRouteInformationProvider.didPushRouteInformation (package:go_router/src/information_provider.dart:267:5)
flutter: #11     WidgetsBinding._handlePushRouteInformation (package:flutter/src/widgets/binding.dart:685:24)
flutter: <asynchronous suspension>
flutter: #12     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:42)
flutter: <asynchronous suspension>
flutter: #13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:22)
flutter: <asynchronous suspension>
flutter:
flutter: The GoRouteInformationProvider sending notification was:
flutter:   Instance of 'GoRouteInformationProvider'
flutter: ═════════════════════════════════════════════════════════════════
flutter: RangeError (startIndex): Invalid value: Only valid value is 0: 1
flutter: #0      RangeError.checkValueInInterval (dart:core/errors.dart:313:7)
flutter: #1      _StringBase.replaceFirst (dart:core-patch/string_patch.dart:591:16)
flutter: #2      canonicalUri (package:go_router/src/path_utils.dart:136:17)
flutter: #3      RouteConfiguration.findMatch (package:go_router/src/configuration.dart:271:31)
flutter: #4      GoRouteInformationParser.parseRouteInformationWithDependencies (package:go_router/src/parser.dart:86:23)
flutter: #5      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:705:8)
flutter: #6      _RouterState._handleRouteInformationProviderNotification (package:flutter/src/widgets/router.dart:723:5)
flutter: #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
flutter: #8      GoRouteInformationProvider.notifyListeners (package:go_router/src/information_provider.dart:141:11)
flutter: #9      GoRouteInformationProvider._platformReportsNewRouteInformation (package:go_router/src/information_provider.dart:236:5)
flutter: #10     GoRouteInformationProvider.didPushRouteInformation (package:go_router/src/information_provider.dart:267:5)
flutter: #11     WidgetsBinding._handlePushRouteInformation (package:flutter/src/widgets/binding.dart:685:24)
flutter: <asynchronous suspension>
flutter: #12     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:42)
flutter: <asynchronous suspension>
flutter: #13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:22)
flutter: <asynchronous suspension>
flutter:

======== Exception caught by foundation library ====================================================
The following RangeError was thrown while dispatching notifications for GoRouteInformationProvider:
RangeError (startIndex): Invalid value: Only valid value is 0: 1

When the exception was thrown, this was the stack: 
#0      RangeError.checkValueInInterval (dart:core/errors.dart:313:7)
#1      _StringBase.replaceFirst (dart:core-patch/string_patch.dart:591:16)
#2      canonicalUri (package:go_router/src/path_utils.dart:136:17)
#3      RouteConfiguration.findMatch (package:go_router/src/configuration.dart:271:31)
#4      GoRouteInformationParser.parseRouteInformationWithDependencies (package:go_router/src/parser.dart:86:23)
#5      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:705:8)
#6      _RouterState._handleRouteInformationProviderNotification (package:flutter/src/widgets/router.dart:723:5)
#7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#8      GoRouteInformationProvider.notifyListeners (package:go_router/src/information_provider.dart:141:11)
#9      GoRouteInformationProvider._platformReportsNewRouteInformation (package:go_router/src/information_provider.dart:236:5)
#10     GoRouteInformationProvider.didPushRouteInformation (package:go_router/src/information_provider.dart:267:5)
#11     WidgetsBinding._handlePushRouteInformation (package:flutter/src/widgets/binding.dart:685:24)
<asynchronous suspension>
#12     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:42)
<asynchronous suspension>
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:22)
<asynchronous suspension>
The GoRouteInformationProvider sending notification was: Instance of 'GoRouteInformationProvider'
====================================================================================================
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.6, on macOS 13.3.1 22E772610a darwin-x64, locale pl-PL)
    • Flutter version 3.10.6 on channel stable at /Users/mateuszdudkowski/fvm/versions/3.10.6
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.18.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/mateuszdudkowski/fvm/versions/3.10.6. Consider adding /Users/mateuszdudkowski/fvm/versions/3.10.6/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mateuszdudkowski/Library/Android/sdk
    • Platform android-33, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone (Mateusz Dudkowski) (mobile) • ------------------ • ios            • iOS 16.5.1 20F75
    • macOS (desktop)                     • macos                     • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)                        • chrome                    • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @dudeck 
What go_router package version are you using ?
Can you also take a look at the breaking changes of the package and see if they help in your case or not ?

https://pub.dev/packages/go_router/changelog#1000

**Comment by dudeck** [comment]
@darshankawar 
Thanks you for your response. We are using go_router v.9.0.0 in production, but i checked also on 10.0.0 and it is the same problem.

**Comment by darshankawar** [comment]
Thanks for the update. Using the code sample provided and steps to replicate, seeing the same error as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.10.6, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.10.6 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.13.0-19.0.pre.77, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.13.0-19.0.pre.77 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 08b2c44413 (2 hours ago), 2023-08-07 22:59:25 -0400
    • Engine revision 9c83d90b01
    • Dart version 3.2.0 (build 3.2.0-42.0.dev)
    • DevTools version 2.26.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by hangyujin** [comment]
I tested on my pixel with go_router 9.0.0 and 10.0.0 and I can't reproduce the issue.

Can you provide more information? 

like the testing device, the command to trigger the issue, the whole repo of the project?

**Comment by elihaialgoaitech** [comment]
I have similar problem, I have `refreshListenable` class when user is auth.
But after the auth I got the same exception. And It occured after upgrade to version 10
If I restart the application it doing welll, it happen only on the first login.
This is my `refreshListenable`:

```
class GoRouterRefreshStream extends ChangeNotifier {
  GoRouterRefreshStream(Stream<dynamic> stream) {
    notifyListeners();
    _subscription = stream.asBroadcastStream().listen(
          (dynamic _) => notifyListeners(),
        );
  }

  late final StreamSubscription<dynamic> _subscription;

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }
}
```
```
GoRouter(
    initialLocation: AppPages.home.routePath,
    navigatorKey: Get.key,
    debugLogDiagnostics: kDebugMode,
    errorBuilder: (context, state) => ErrorPage(
      errorTitleKey: 'pageNotFound',
      bottomTextKey: 'toHomePage',
      onButtonClick: () => context.replace('/'),
    ),
    refreshListenable:
        GoRouterRefreshStream(locator<AuthRepository>().isProfileReadyStream),
    redirect: (context, state) async {
    // If I put here BP it doesn't arrive here
      },

    routes: _routes,
  );
```
 My exception:
 ```
 
======== Exception caught by foundation library ====================================================
The following RangeError was thrown while dispatching notifications for GoRouteInformationProvider:
RangeError (startIndex): Invalid value: Only valid value is 0: 1

When the exception was thrown, this was the stack: 
#0      RangeError.checkValueInInterval (dart:core/errors.dart:313:7)
#1      _StringBase.replaceFirst (dart:core-patch/string_patch.dart:591:16)
#2      canonicalUri (package:go_router/src/path_utils.dart:136:17)
#3      RouteConfiguration.findMatch (package:go_router/src/configuration.dart:273:31)
#4      _RouteMatchListDecoder.convert (package:go_router/src/match.dart:430:23)
#5      Codec.decode (dart:convert/codec.dart:30:34)
#6      GoRouteInformationParser.parseRouteInformationWithDependencies (package:go_router/src/parser.dart:72:32)
#7      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:744:8)
#8      _RouterState._handleRouteInformationProviderNotification (package:flutter/src/widgets/router.dart:762:5)
#9      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#10     GoRouteInformationProvider.notifyListeners (package:go_router/src/information_provider.dart:141:11)
#11     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#12     new GoRouterRefreshStream.<anonymous closure> (package:mujual_app/navigation/go_router_refresh_stream.dart:9:26)
#27     _MultiControllerSink.add (package:rxdart/src/utils/forwarding_stream.dart:130:35)
#28     _StartWithStreamSink.onData (package:rxdart/src/transformers/start_with.dart:12:31)
(elided 31 frames from dart:async)
The GoRouteInformationProvider sending notification was: Instance of 'GoRouteInformationProvider'
====================================================================================================
D/EGL_emulation( 8204): app_time_stats: avg=30.59ms min=19.66ms max=88.90ms count=32
D/EGL_emulation( 8204): app_time_stats: avg=23.63ms min=19.00ms max=33.30ms count=41
```

Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (3 weeks ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0

  go_router: ^10.1.2

**Comment by weitangli** [comment]
I had the same problem, it happens the first time you login by notifyListeners.

Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (8 weeks ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1
go_router: 10.1.2

**Comment by elihaialgoaitech** [comment]
> I had the same problem, it happens the first time you login by notifyListeners.
> 
> Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git Framework • revision [f468f33](https://github.com/flutter/flutter/commit/f468f3366c26a5092eb964a230ce7892fda8f2f8) (8 weeks ago) • 2023-07-12 15:19:05 -0700 Engine • revision cdbeda788a Tools • Dart 3.0.6 • DevTools 2.23.1 go_router: 10.1.2

Try my fork: https://github.com/elihaialgoaitech/packages/tree/main

**Comment by dudeck** [comment]
> I tested on my pixel with go_router 9.0.0 and 10.0.0 and I can't reproduce the issue.
> 
> Can you provide more information?
> 
> like the testing device, the command to trigger the issue, the whole repo of the project?

I was testing it on iPhone XR iOS 16.5.1. 

You can use example project from GitHub of go_router package:
https://github.com/flutter/packages/tree/main/packages/go_router/example

And modify main.dart using attached code of this issue.

**Comment by dudeck** [comment]
> I tested on my pixel with go_router 9.0.0 and 10.0.0 and I can't reproduce the issue.
> 
> Can you provide more information?
> 
> like the testing device, the command to trigger the issue, the whole repo of the project?

I was testing it on iPhone XR iOS 16.5.1. 

You can use example project from GitHub of go_router package:
https://github.com/flutter/packages/tree/main/packages/go_router/example

And modify main.dart using attached code of this issue.

**Comment by glaceon2000** [comment]
I have the same problem in web

**Comment by Nithsua** [comment]
I'm facing the same issue. For me it even weirder. So I send a email with magic link to the user. When the app is launched directly from mail app by tapping on the hyperlink it throws the exception but when i copy the url and open it in a new browser tab it launches the mobile app and everything works fine.

**Comment by cornwe19** [comment]
Having the same issue myself

> > I had the same problem, it happens the first time you login by notifyListeners.
> > Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git Framework • revision [f468f33](https://github.com/flutter/flutter/commit/f468f3366c26a5092eb964a230ce7892fda8f2f8) (8 weeks ago) • 2023-07-12 15:19:05 -0700 Engine • revision cdbeda788a Tools • Dart 3.0.6 • DevTools 2.23.1 go_router: 10.1.2
> 
> Try my fork: https://github.com/elihaialgoaitech/packages/tree/main

@elihaialgoaitech This fork does seem to resolve the issue for me. Do you have a PR open with this fix by any chance?

**Comment by Nithsua** [comment]
> Having the same issue myself
> 
> > > I had the same problem, it happens the first time you login by notifyListeners.
> > > Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git Framework • revision [f468f33](https://github.com/flutter/flutter/commit/f468f3366c26a5092eb964a230ce7892fda8f2f8) (8 weeks ago) • 2023-07-12 15:19:05 -0700 Engine • revision cdbeda788a Tools • Dart 3.0.6 • DevTools 2.23.1 go_router: 10.1.2
> > 
> > 
> > Try my fork: https://github.com/elihaialgoaitech/packages/tree/main
> 
> @elihaialgoaitech This fork does seem to resolve the issue for me. Do you have a PR open with this fix by any chance?

Seems the PR is temporarily closed https://github.com/flutter/packages/pull/4846

**Comment by Vedsaga** [comment]
Can confirm this is still happening in version 13.0

**Comment by emilypriddy** [comment]
Experiencing the same on version 12.1.3. Is this being worked on?

**Comment by HelioPC** [comment]
Has anyone managed to resolve this problem?

**Comment by chunhtai** [comment]
Is this still an issue?

**Comment by Vedsaga** [comment]
Last time checked was happening... in version `13.X`

**Comment by harkairt** [comment]
having the same issue

**Comment by umuieme** [comment]
any update in this? Still facing this issue.

**Comment by darrenzjd** [comment]
is this fixed? running into the same issue
