### ISSUE TITLE
Possible Flutter framework error using StaggeredGridView

### ISSUE THREAD

**Issue by rahuloak** [flutter/flutter#132060]
I'm using a StaggeredGridView to display gifs on screen with crossAxisCount set to 2. The App works as expected on both iOS and Android, but I get this error every time the page loads: 

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderIndexedSemantics#15313 NEEDS-LAYOUT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 3457 pos 12: '!_needsLayout'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3457:12)
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3473:61)
#4      Iterable.forEach (dart:core/iterable.dart:346:35)
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:296:29)
#6      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3612:5)
#7      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3471:5)
#8      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3473:61)
#9      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3889:14)
#10     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3612:5)
#11     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3471:5)
#12     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3473:61)
#13     Iterable.forEach (dart:core/iterable.dart:346:35)
#14     RenderViewportBase.visitChildrenForSemantics (package:flutter/src/rendering/viewport.dart:247:10)
#15     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3471:5)
#16     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3473:61)
#17     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3643:14)
#18     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3471:5)
#19     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3473:61)
#20     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3889:14)
#21     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3612:5)
#22     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4269:11)
#23     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3471:5)
#24     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3473:61)
#25     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3889:14)
#26     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3612:5)
#27     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3471:5)
#28     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3473:61)
#29     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3889:14)
#30     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3612:5)
#31     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3471:5)
#32     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3473:61)
#33     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3889:14)
#34     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3612:5)
#35     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3471:5)
#36     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3473:61)
#37     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3889:14)
#38     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3612:5)
#39     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3471:5)
#40     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3435:41)
#41     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1268:16)
#42     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:21)
#43     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#44     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#45     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#46     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#47     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#48     _invoke (dart:ui/hooks.dart:142:13)
#49     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#50     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
===============================================================================================
```

Please LMK what additional information you need to debug.

**Comment by danagbemava-nc** [comment]
Hi @rahuloak, 

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third-party packages along with steps to reproduce so that we can investigate this issue. 

Thank you
