### ISSUE TITLE
API `/api/postsubmit-luci-subscription` fails due to `Bad state: No element`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#132065]
API `/api/postsubmit-luci-subscription` has been failing frequently due to `Bad state: No element`

```
Bad state: No element
#0      ListBase.singleWhere (dart:collection/list.dart:167:5)
#1      PostsubmitLuciSubscription.post (package:cocoon_service/src/request_handlers/postsubmit_luci_subscription.dart:94:52)
<asynchronous suspension>
#2      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:24)
<asynchronous suspension>
#3      SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:5)
<asynchronous suspension>
#4      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:293:11)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
This is caused by obsoleted targets. https://github.com/flutter/cocoon/pull/2984 to fix.

F.Y.I. @ricardoamador @drewroengoogle This should be the same issue as in the release branches.
