### ISSUE TITLE
Gettings errors "could not install psutils package" on machine mac-38.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#132074]
Gettings errors "could not install psutils package" on machine mac-38.

----------
          ID: psutil3
    Function: cmd.run
        Name: /opt/swarming-support/bin/python3 /opt/swarming-support/bin/pip3 install psutil
      Result: False
     Comment: Command "/opt/swarming-support/bin/python3 /opt/swarming-support/bin/pip3 install psutil" run
     Started: 10:50:01.649932
    Duration: 1408.299 ms
     Changes:   
              ----------
              pid:
                  925
              retcode:
                  1
              stderr:
                  Traceback (most recent call last):
                    File "/opt/swarming-support/bin/pip3", line 5, in <module>
                      from pip._internal.cli.main import main
                    File "/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
                      from pip._internal.cli.autocompletion import autocomplete
                    File "/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
                      from pip._internal.cli.main_parser import create_main_parser
                    File "/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
                      from pip._internal.cli import cmdoptions
                    File "/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 25, in <module>
                      from pip._internal.cli.progress_bars import BAR_TYPES
                    File "/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 12, in <module>
                      from pip._internal.utils.logging import get_indentation
                    File "/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 18, in <module>
                      from pip._internal.utils.misc import ensure_dir
                    File "/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 34, in <module>
                      from pip._internal.locations import get_major_minor_version, site_packages, user_site
                    File "/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
                      from . import _distutils, _sysconfig
                    File "/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/locations/_sysconfig.py", line 8, in <module>
                      from pip._internal.exceptions import InvalidSchemeCombination, UserInstallationInvalid
                  ImportError: cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' (/opt/swarming-support/lib/python3.8/site-packages/pip/_internal/exceptions.py)
              stdout:

Summary for local
-------------
Succeeded: 42 (changed=11)
Failed:     1
-------------
Total states run:     43
Total run time:   17.603 s

**Comment by yusuf-goog** [comment]
The provisioning profile looks to be good on mac-38. It has the new file and the file contains the UUID of the attached device.

Looking into why we are getting the message `Device healthcheck failed: codesigning_cert: 0 valid identities found;
`

**Comment by kentnguyen99** [comment]
Machine mac-38 is in bad state, could resolve nor fix the error and it requires to re-install OS and rebuild machine.  There is another ticket was opened to re-image the machine.
