### ISSUE TITLE
flutter build -v windows Error: Unable to generate build files

### ISSUE THREAD

**Issue by tcbuger** [flutter/flutter#132026]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce
(win 10) 
i had installed Visual Studio and Microsoft Visual C++(many times), and create a new flutter project in Visual Studio Code. I started it and  it worked at the first time, but just disappear quickly, and then i tried to run it, it didn't work. 

i also changed the flutter channel to master, it didn't work.

### Actual results

it just doesnt work, i found some same issues in 'issues' ,but they cant resolve my problem.

### Logs

<details>
<summary>Logs</summary>

```console

[   +8 ms] Skipping pub get: version match.
[ +131 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +3 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated        
contents: H:\Saves\Flutter\test0807\.dart_tool\package_config_subset}
[  +21 ms] gen_dart_plugin_registrant: Complete
[   +2 ms] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib\main.dart on Windows in debug mode...
[   +2 ms] H:\Tools\DevelopEnviroment\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
H:\Tools\DevelopEnviroment\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
H:\Tools\DevelopEnviroment\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/cdbeda788a293fa29665dc3fa3d6e63bd221cb0d/ --output-dill        
C:\Users\Connect\AppData\Local\Temp\flutter_tools.ad03dbd4\flutter_tool.47705a22\app.dill --packages
H:\Saves\Flutter\test0807\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\ade00fc64fa695e0daed02c1105f6d67.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy 
[  +17 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest
-version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.VC.CMake.Project
[  +59 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8
-latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64        
Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] [
             {
               "instanceId": "f66358ae",
               "installDate": "2023-08-07T04:41:22Z",
               "installationName": "VisualStudio/17.6.5+33829.357",
               "installationPath": "H:\\Tools\\VisualStudio\\VisualStudio",
               "installationVersion": "17.6.33829.357",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "H:\\Tools\\VisualStudio\\VisualStudio\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "功能强大的 IDE，供学生、开放源代码参与者和个人免费使用",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelId": "VisualStudio.17.Release",
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.6#17.6.5",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2023-08-07T04:41:22.6021785Z",
               "catalog": {
                 "buildBranch": "d17.6",
                 "buildVersion": "17.6.33829.357",
                 "id": "VisualStudio/17.6.5+33829.357",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.6.5",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "5",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "17.6.5+33829.357",
                 "requiredEngineVersion": "3.6.2115.31769"
               },
               "properties": {
                 "campaignId": "2030:1156185748f3461abaf2afc25493b6b6",
                 "channelManifestId": "VisualStudio.17.Release/17.6.5+33829.357",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +5 ms] Building Windows application...
[  +24 ms] <- compile package:test0807/main.dart
[   +1 ms] executing: H:\Tools\VisualStudio\VisualStudio\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
H:\Saves\Flutter\test0807\windows -B build\windows -G Visual Studio 17 2022
[  +90 ms] Building Windows application... (completed in 109ms)
[+6870 ms] Exception: Unable to generate build files
[   +1 ms] "flutter run" took 26,056ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +62 ms] ensureAnalyticsSent: 57ms
[        ] Running 1 shutdown hook
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [版本 10.0.19045.3208], locale zh-CN)
    • Flutter version 3.10.6 on channel stable at H:\Tools\DevelopEnviroment\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at G:\WorkAbout\AndroidSDK\android-sdk-windows
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.5)
    • Visual Studio at H:\Tools\VisualStudio\VisualStudio
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.3208]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5927.0
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.188

[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by tcbuger** [comment]
i resolved this by open vscode as administrator......................................
