### ISSUE TITLE
API `/api/dart-internal-subscription` has been failing consistently due to `Key not found`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#132066]
```
> ERROR 2023-08-07T16:00:54.409Z Found 0 entries for builder Windows engine_release_builder
> ERROR 2023-08-07T16:00:54.409Z Failed to find an existing task for the buildbucket build: HTTP 500: Expected to find 1 task for Windows engine_release_builder, but found 0
> ERROR 2023-08-07T16:00:54.409Z Creating Task from Buildbucket result
> ERROR 2023-08-07T16:00:54.409Z Creating task from buildbucket result: build(id: 8774037139995263905, builderId: dart-internal/flutter/Windows engine_release_builder, number: 579, status: Status.success, tags: null)
> ERROR 2023-08-07T16:00:54.409Z Repository: engine
> ERROR 2023-08-07T16:00:54.409Z Branch: flutter-3.13-candidate.13
> ERROR 2023-08-07T16:00:54.409Z Hash: 590ff28649eb547b6f4dd4ac162a7c373d1042be
> ERROR 2023-08-07T16:00:54.409Z Slug: flutter/engine
> ERROR 2023-08-07T16:00:54.409Z Start/end time (ms): 1690823153724, 1690827371803
> ERROR 2023-08-07T16:00:54.417Z Key not found: Commit:flutter/engine/flutter-3.13-candidate.13/590ff28649eb547b6f4dd4ac162a7c373d1042be #0 DatastoreDB.lookupValue (package:gcloud/src/db/db.dart:382:9) <asynchronous suspension> #1 Task.fromBuildbucketBuild (package:cocoon_service/src/model/appengine/task.dart:161:27) <asynchronous suspension> #2 DartInternalSubscription.post (package:cocoon_service/src/request_handlers/dart_internal_subscription.dart:96:22) <asynchronous suspension> #3 RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:24) <asynchronous suspension> #4 SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:5) <asynchronous suspension> #5 main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:293:11) <asynchronous suspension>
> ERROR 2023-08-07T16:00:54.417Z Failed to process Instance of 'PushMessage'. (500) Key not found: Commit:flutter/engine/flutter-3.13-candidate.13/590ff28649eb547b6f4dd4ac162a7c373d1042be #0 DatastoreDB.lookupValue (package:gcloud/src/db/db.dart:382:9) <asynchronous suspension> #1 Task.fromBuildbucketBuild (package:cocoon_service/src/model/appengine/task.dart:161:27) <asynchronous suspension> #2 DartInternalSubscription.post (package:cocoon_service/src/request_handlers/dart_internal_subscription.dart:96:22) <asynchronous suspension> #3 RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:24) <asynchronous suspension> #4 SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:5) <asynchronous suspension> #5 main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:293:11) <asynchronous suspension>
```

```
Failed to process Instance of 'PushMessage'. (500) Key not found: Commit:flutter/engine/flutter-3.13-candidate.13/590ff28649eb547b6f4dd4ac162a7c373d1042be
#0      DatastoreDB.lookupValue (package:gcloud/src/db/db.dart:382:9)
<asynchronous suspension>
#1      Task.fromBuildbucketBuild (package:cocoon_service/src/model/appengine/task.dart:161:27)
<asynchronous suspension>
#2      DartInternalSubscription.post (package:cocoon_service/src/request_handlers/dart_internal_subscription.dart:96:22)
<asynchronous suspension>
#3      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:24)
<asynchronous suspension>
#4      SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:5)
<asynchronous suspension>
#5      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:293:11)
<asynchronous suspension>
```

**Comment by drewroengoogle** [comment]
I think the following is occurring:

A new candidate branch is cut, which cocoon doesn't schedule builds for. However, the LUCI scheduler still schedules builds, and when it tries to find a commit to link the task to, it doesn't find it, because it is relying on one of the cocoon tasks to create a commit.

This is probably a P1 given that it isn't affecting any releases, but is causing a lot of noise. I'll take a look at creating a fix today.

**Comment by yusuf-goog** [comment]
ready to close?

**Comment by yusuf-goog** [comment]
@ricardoamador confirmed that is good to close
