### ISSUE TITLE
Flutter android.graphics.ImageDecoder fails to decode jpg image

### ISSUE THREAD

**Issue by carra-hamner** [flutter/flutter#132184]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce
0. use Android version 13 for the testing machine and flutter 3.10.6
1. put some sample jpg files in the directory path of join(appDocumentsDirectory.path, 'images'
2.  run the code sample

### Expected results

index on the left, actual images on the right

### Actual results

index on the left, an image with "Exception: Invalid image data" underneath of a red box with a red "X" inside of it

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:image/image.dart' as widget;
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FTP ListView Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  MyHomePageState createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  List imgFiles = [];
  @override
  void initState() {
    super.initState();
    _getImages();
  }

 Future<void> _getImages() async {
    try {
      Directory appDocumentsDirectory = await getApplicationDocumentsDirectory();
      //creates a directory called "images" for images in the app's designated memory
      Directory directory = Directory(join(appDocumentsDirectory.path, 'images'));
      List<FileSystemEntity> fileList = directory.listSync();

      for(FileSystemEntity e in fileList){
        if(e is File && e.path.toLowerCase().endsWith('.jpg')){
          imgFiles.add(e.path);
        }
      }

      setState(() {});
    } catch (e) {
      if (kDebugMode) {
        print('Error: $e');
      }
    }
  }

@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Local JPG List Example'),
      ),
      body: ListView.builder(
        itemCount: imgFiles.length,
        itemBuilder: (context, index) {
          return ListTile(
            leading: Text((index + 1).toString()),
            title: Image.file(File(imgFiles[index])),
            onTap: () {
              // Handle tile tap (e.g., open the image)
            },
          );
        },
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/55858984/305520db-0de8-421f-9c18-57b971465b65)

</details>

### Logs

<details><summary>Logs</summary>

```console
======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:6637:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6494:12)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2291:60)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:182:15)
#4      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:1598:20)
<asynchronous suspension>
Path: /data/user/0/com.example.place_holder_name/app_flutter/images/some_jpg.jpg
====================================================================================================
E/FlutterJNI( 9097): Failed to decode image
E/FlutterJNI( 9097): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 9097): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 9097): 	at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI( 9097): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:242)
E/FlutterJNI( 9097): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:2015)
E/FlutterJNI( 9097): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:2008)
E/FlutterJNI( 9097): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:538)

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3208], locale en-US)
    • Flutter version 3.10.6 on channel stable at C:\Users\genac\flutter\flutter_3.10.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at C:\Users\genac\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G991U1 (mobile) • R5CR715D70Y • android-arm64  • Android 13 (API 33)
    • Windows (desktop)  • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.3208]
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)         • edge        • web-javascript • Microsoft Edge 115.0.1901.188

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @carra-hamner. Thanks for filing this issue. I can't seem to reproduce this on my device `Android 9` though, is this specific to Android version 13, also, are there specific jpg images that this reproduces with (if possible, you could as well share a link to the images that reproduces this issue).

**Comment by carra-hamner** [comment]
Hi @dam-ease . Thank you for replying to me. The problem was not rooted in Flutter official codes, but in a community package (FTPConnect). After some research, I have found the solution to the issue. The problem was rooted in Dart package "ftpconnect" (import 'package:ftpconnect/ftpconnect.dart';); its default FTP transfer format is for text files, not for binary files. Therefore, I downloaded these jpg files as text files and was unable to retrieve them in my Flutter app.
(for whoever faced the same problem, please follow this link: https://github.com/salim-lachdhaf/dartFTP/issues/21)
