### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by findofthe** [flutter/flutter#132236]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Operation not permitted, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:992:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:355:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
```
```
[✓] Flutter (Channel stable, 3.10.6, on Ubuntu 22.04.3 LTS 6.2.0-26-generic, locale tr_TR.UTF-8)
    • Flutter version 3.10.6 on channel stable at /home/kursat/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 hafta önce), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /mnt/Android/Android/Sdk/
    • Platform android-34, build-tools 34.0.0-rc2
    • ANDROID_HOME = /mnt/Android/Android/Sdk
    • Java binary at: /opt/android-studio-2022.2.1/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio-2022.2.1/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-26-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.170
    ! Device emulator-5554 is offline.

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.12+12
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7e9793dee1b85a243edd0e06cb1658e98b077561
### Plugins
device_info-2.0.3
firebase_core-2.13.0
firebase_core_web-2.5.0
firebase_messaging-14.6.1
firebase_messaging_web-3.5.1
google_mobile_ads-3.0.0
platform_device_id-1.0.1
platform_device_id_linux-1.0.0
platform_device_id_macos-1.0.0
platform_device_id_web-1.0.0
platform_device_id_windows-1.0.0
webview_flutter-4.2.1
webview_flutter_android-3.7.1
webview_flutter_wkwebview-3.4.4

**Comment by huycozy** [comment]
Please check https://github.com/flutter/flutter/issues/129124#issuecomment-1603773416 if it can solve your case.
