### ISSUE TITLE
Can not build apk in github codespace

### ISSUE THREAD

**Issue by cvphat** [flutter/flutter#132383]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce
1. new empty repository
2. add config dev container:
```json
{
  "image": "ghcr.io/instrumentisto/flutter:3.10.6",
  "features": {
  },
  "customizations": {
      "vscode": {
          "extensions": [
            "Dart-Code.dart-code",
            "Dart-Code.flutter",
          ]
      }
   }
}
````
3. create codespace and open by vs code
4. create flutter project: `flutter create --empty .` 
5. run `flutter build apk`

### Expected results

Build success

### Actual results

Build failed with an exception

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Checking the license for package SDK Patch Applier v4 in /opt/android-sdk-linux/licenses
License for package SDK Patch Applier v4 accepted.
Preparing "Install SDK Patch Applier v4 (revision: 1)".
"Install SDK Patch Applier v4 (revision: 1)" ready.
Installing SDK Patch Applier v4 in /opt/android-sdk-linux/patcher/v4
"Install SDK Patch Applier v4 (revision: 1)" complete.
"Install SDK Patch Applier v4 (revision: 1)" finished.
Checking the license for package Android Emulator in /opt/android-sdk-linux/licenses
License for package Android Emulator accepted.
Preparing "Install Android Emulator (revision: 32.1.14)".
"Install Android Emulator (revision: 32.1.14)" ready.
Installing Android Emulator in /opt/android-sdk-linux/emulator
"Install Android Emulator (revision: 32.1.14)" complete.
"Install Android Emulator (revision: 32.1.14)" finished.
Checking the license for package Android SDK Tools in /opt/android-sdk-linux/licenses
License for package Android SDK Tools accepted.
Preparing "Install Android SDK Tools (revision: 26.1.1)".
"Install Android SDK Tools (revision: 26.1.1)" ready.
Installing Android SDK Tools in /opt/android-sdk-linux/tools
"Install Android SDK Tools (revision: 26.1.1)" complete.
"Install Android SDK Tools (revision: 26.1.1)" finished.
Checking the license for package Android SDK Build-Tools 30.0.3 in /opt/android-sdk-linux/licenses
License for package Android SDK Build-Tools 30.0.3 accepted.
Preparing "Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)".
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" ready.
Installing Android SDK Build-Tools 30.0.3 in /opt/android-sdk-linux/build-tools/30.0.3
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=b9068f4a-5751-44a0-81c2-3aa11be8b2d7, currentDir=/workspaces/flutter_mobile_codespace/android}
Attempting to read last messages from the daemon log...
Daemon pid: 3266
  log file: /root/.gradle/daemon/7.5/daemon-3266.out.log
----- Last  20 lines from daemon log file - daemon-3266.out.log -----
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" ready.
Installing Android SDK Build-Tools 30.0.3 in /opt/android-sdk-linux/build-tools/30.0.3
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
Remove shutdown hook failed
java.lang.IllegalStateException: Shutdown in progress
        at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
        at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:244)
        at org.gradle.process.internal.shutdown.ShutdownHooks.removeShutdownHook(ShutdownHooks.java:38)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:208)
        at org.gradle.process.internal.DefaultExecHandle.aborted(DefaultExecHandle.java:366)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:108)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:84)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
----- End of the daemon log -----


FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Running Gradle task 'assembleRelease'...                          166.4s
Gradle task assembleRelease failed with exit code 1
```

</details>

<details><summary>Gradle daemon output</summary>

```console
2023-08-11T10:03:23.084+0000 [DEBUG] [org.gradle.launcher.daemon.bootstrap.DaemonMain] Assuming the daemon was started with following jvm opts: [--add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.base/java.lang=ALL-UNNAMED, --add-opens, java.base/java.lang.invoke=ALL-UNNAMED, --add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.prefs/java.util.prefs=ALL-UNNAMED, --add-opens, java.prefs/java.util.prefs=ALL-UNNAMED, --add-opens, java.base/java.nio.charset=ALL-UNNAMED, --add-opens, java.base/java.net=ALL-UNNAMED, --add-opens, java.base/java.util.concurrent.atomic=ALL-UNNAMED, -Xmx1536M, -Dfile.encoding=UTF-8, -Duser.country=US, -Duser.language=en, -Duser.variant]
2023-08-11T10:03:23.322+0000 [INFO] [org.gradle.launcher.daemon.server.Daemon] start() called on daemon - DefaultDaemonContext[uid=e3b10c11-c402-477b-814f-7eea9b106b90,javaHome=/usr/lib/jvm/java-11-openjdk-amd64,daemonRegistryDir=/root/.gradle/daemon,pid=3266,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx1536M,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
2023-08-11T10:03:23.397+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface docker0
2023-08-11T10:03:23.397+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? false
2023-08-11T10:03:23.398+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /172.17.0.1
2023-08-11T10:03:23.398+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface eth0
2023-08-11T10:03:23.398+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? false
2023-08-11T10:03:23.399+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /fe80:0:0:0:20d:3aff:fea3:fa0f%eth0
2023-08-11T10:03:23.400+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /172.16.5.4
2023-08-11T10:03:23.400+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface lo
2023-08-11T10:03:23.400+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? true
2023-08-11T10:03:23.401+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /0:0:0:0:0:0:0:1%lo
2023-08-11T10:03:23.401+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /127.0.0.1
2023-08-11T10:03:23.403+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.TcpIncomingConnector] Listening on [acdcc18d-c7da-4e37-94fc-9a1bcab4c460 port:36621, addresses:[localhost/127.0.0.1]].
2023-08-11T10:03:23.454+0000 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] Daemon starting at: Fri Aug 11 10:03:23 GMT 2023, with address: [acdcc18d-c7da-4e37-94fc-9a1bcab4c460 port:36621, addresses:[localhost/127.0.0.1]]
2023-08-11T10:03:23.454+0000 [INFO] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Advertising the daemon address to the clients: [acdcc18d-c7da-4e37-94fc-9a1bcab4c460 port:36621, addresses:[localhost/127.0.0.1]]
2023-08-11T10:03:23.455+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Advertised daemon context: DefaultDaemonContext[uid=e3b10c11-c402-477b-814f-7eea9b106b90,javaHome=/usr/lib/jvm/java-11-openjdk-amd64,daemonRegistryDir=/root/.gradle/daemon,pid=3266,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx1536M,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
2023-08-11T10:03:23.456+0000 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Storing daemon address: [acdcc18d-c7da-4e37-94fc-9a1bcab4c460 port:36621, addresses:[localhost/127.0.0.1]], context: DefaultDaemonContext[uid=e3b10c11-c402-477b-814f-7eea9b106b90,javaHome=/usr/lib/jvm/java-11-openjdk-amd64,daemonRegistryDir=/root/.gradle/daemon,pid=3266,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx1536M,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
2023-08-11T10:03:23.461+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
2023-08-11T10:03:23.464+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-08-11T10:03:23.469+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2023-08-11T10:03:23.469+0000 [LIFECYCLE] [org.gradle.launcher.daemon.server.Daemon] Daemon server started.
2023-08-11T10:03:23.474+0000 [DEBUG] [org.gradle.launcher.daemon.bootstrap.DaemonStartupCommunication] Completed writing the daemon greeting. Closing streams...
2023-08-11T10:03:23.491+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.TcpIncomingConnector] Accepted connection from /127.0.0.1:44358 to /127.0.0.1:36621.
2023-08-11T10:03:23.502+0000 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] stopOnExpiration() called on daemon
2023-08-11T10:03:23.509+0000 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] awaitExpiration() called on daemon
2023-08-11T10:03:23.510+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
2023-08-11T10:03:23.533+0000 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 17: received class org.gradle.launcher.daemon.protocol.Build
2023-08-11T10:03:23.534+0000 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] thread 17: Received non-IO message from client: Build{id=b9068f4a-5751-44a0-81c2-3aa11be8b2d7, currentDir=/workspaces/flutter_mobile_codespace/android}
2023-08-11T10:03:23.534+0000 [INFO] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Received command: Build{id=b9068f4a-5751-44a0-81c2-3aa11be8b2d7, currentDir=/workspaces/flutter_mobile_codespace/android}.
2023-08-11T10:03:23.536+0000 [DEBUG] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Starting executing command: Build{id=b9068f4a-5751-44a0-81c2-3aa11be8b2d7, currentDir=/workspaces/flutter_mobile_codespace/android} with connection: socket connection from /127.0.0.1:36621 to /127.0.0.1:44358.
2023-08-11T10:03:23.539+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command execution: started DaemonCommandExecution[command = Build{id=b9068f4a-5751-44a0-81c2-3aa11be8b2d7, currentDir=/workspaces/flutter_mobile_codespace/android}, connection = DefaultDaemonConnection: socket connection from /127.0.0.1:36621 to /127.0.0.1:44358] after 0.0 minutes of idle
2023-08-11T10:03:23.541+0000 [INFO] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Marking the daemon as busy, address: [acdcc18d-c7da-4e37-94fc-9a1bcab4c460 port:36621, addresses:[localhost/127.0.0.1]]
2023-08-11T10:03:23.542+0000 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Marking busy by address: [acdcc18d-c7da-4e37-94fc-9a1bcab4c460 port:36621, addresses:[localhost/127.0.0.1]]
2023-08-11T10:03:23.542+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
2023-08-11T10:03:23.543+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-08-11T10:03:23.544+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2023-08-11T10:03:23.544+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] resetting idle timer
2023-08-11T10:03:23.544+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
2023-08-11T10:03:23.546+0000 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=b9068f4a-5751-44a0-81c2-3aa11be8b2d7, currentDir=/workspaces/flutter_mobile_codespace/android}. Dispatching build started information...
2023-08-11T10:03:23.546+0000 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 19: dispatching org.gradle.launcher.daemon.protocol.BuildStarted@7a0030f6
2023-08-11T10:03:23.548+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: [PATH, CODESPACES, CODESPACE_VSCODE_FOLDER, VSCODE_GIT_IPC_HANDLE, ANDROID_HOME, GITHUB_API_URL, COLORTERM, VSCODE_GIT_ASKPASS_NODE, PWD, TERM_PROGRAM_VERSION, GIT_ASKPASS, LANGUAGE, GLIBCPP_FORCE_NEW, SHELL, GITHUB_TOKEN, GITHUB_GRAPHQL_URL, OLDPWD, GITHUB_CODESPACE_TOKEN, ANDROID_PLATFORM_VERSION, ContainerVersion, ANDROID_BUILD_TOOLS_VERSION, GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN, LC_ALL, GITHUB_USER, LS_COLORS, SHLVL, FLUTTER_VERSION, BROWSER, GITHUB_SERVER_URL, CLOUDENV_ENVIRONMENT_ID, ANDROID_SDK_TOOLS_VERSION, RepositoryName, FLUTTER_ROOT, TERM, FLUTTER_HOME, LANG, VSCODE_GIT_ASKPASS_MAIN, INTERNAL_VSCS_TARGET_URL, VSCODE_IPC_HOOK_CLI, GITHUB_REPOSITORY, VSCODE_GIT_ASKPASS_EXTRA_ARGS, TERM_PROGRAM, SHELL_LOGGED_IN, ANDROID_SDK_ROOT, GLIBCXX_FORCE_NEW, FLUTTER_ALREADY_LOCKED, HOSTNAME, CODESPACE_NAME, HOME]
2023-08-11T10:03:23.563+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start relaying all logs to the client via the connection.
2023-08-11T10:03:23.563+0000 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 3266). The daemon log file: /root/.gradle/daemon/7.5/daemon-3266.out.log
2023-08-11T10:03:23.573+0000 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting build in new daemon [memory: 1.5 GiB]
2023-08-11T10:03:23.584+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
2023-08-11T10:03:23.584+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=e3b10c11-c402-477b-814f-7eea9b106b90,javaHome=/usr/lib/jvm/java-11-openjdk-amd64,daemonRegistryDir=/root/.gradle/daemon,pid=3266,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx1536M,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
Checking the license for package SDK Patch Applier v4 in /opt/android-sdk-linux/licenses
License for package SDK Patch Applier v4 accepted.
Preparing "Install SDK Patch Applier v4 (revision: 1)".
"Install SDK Patch Applier v4 (revision: 1)" ready.
Installing SDK Patch Applier v4 in /opt/android-sdk-linux/patcher/v4
"Install SDK Patch Applier v4 (revision: 1)" complete.
"Install SDK Patch Applier v4 (revision: 1)" finished.
Checking the license for package Android Emulator in /opt/android-sdk-linux/licenses
License for package Android Emulator accepted.
Preparing "Install Android Emulator (revision: 32.1.14)".
"Install Android Emulator (revision: 32.1.14)" ready.
Installing Android Emulator in /opt/android-sdk-linux/emulator
"Install Android Emulator (revision: 32.1.14)" complete.
"Install Android Emulator (revision: 32.1.14)" finished.
Checking the license for package Android SDK Tools in /opt/android-sdk-linux/licenses
License for package Android SDK Tools accepted.
Preparing "Install Android SDK Tools (revision: 26.1.1)".
"Install Android SDK Tools (revision: 26.1.1)" ready.
Installing Android SDK Tools in /opt/android-sdk-linux/tools
"Install Android SDK Tools (revision: 26.1.1)" complete.
"Install Android SDK Tools (revision: 26.1.1)" finished.
Checking the license for package Android SDK Build-Tools 30.0.3 in /opt/android-sdk-linux/licenses
License for package Android SDK Build-Tools 30.0.3 accepted.
Preparing "Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)".
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" ready.
Installing Android SDK Build-Tools 30.0.3 in /opt/android-sdk-linux/build-tools/30.0.3
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
Remove shutdown hook failed
java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:244)
	at org.gradle.process.internal.shutdown.ShutdownHooks.removeShutdownHook(ShutdownHooks.java:38)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:208)
	at org.gradle.process.internal.DefaultExecHandle.aborted(DefaultExecHandle.java:366)
	at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:108)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:84)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on Ubuntu 22.04.2 LTS 5.15.0-1042-azure, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.2 LTS 5.15.0-1042-azure

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by dam-ease** [comment]
Hi @cvphat. I can't seem to be able to reproduce this. Are there specific actions that reproduces this or this seems to occur with all new projects?

**Comment by cvphat** [comment]
Hi @dam-ease , I think the issue is related to codespace. I rechecked many times and sometime it builds successfully
