### ISSUE TITLE
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true

### ISSUE THREAD

**Issue by wujek-srujek** [flutter/flutter#132399]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I would like to mention I found tickets similar to this one (https://github.com/flutter/flutter/issues/43501) but they got closed because of no samples to reproduce. Hopefully this one helps you track it down.

Setup the test project:
1. `flutter create --template plugin --platforms android myplugin`
2. `cd myplugin`
3.  `rm -rf lib/ test/ example/test/ example/integration_test/` - we don't need any of this code.
4. Replace the contents of `android/src/main/kotlin/com/example/myplugin/MypluginPlugin.kt` with the Kotlin code shown in 'code samples' below.
5. Replace the contents of `example/lib/main.dart` with the Dart code shown in 'code samples' below.

Now you can start the application.
1. Start VS Code and open the project.
2. Open the `example/lib/main.dart` file and start the app, doesn't matter if 'debug' or 'run'.
3. Press the `Subscribe` button. This fetches a stream using `EventChannel` and subscribes to it. You should see increasing numbers below the `Cancel` button - they come from the platform in 1 second intervals.
4. Press the `Cancel ` button. This cancels the subscription, the numbers stop being updated.
5. This seems to be imperative: make a change in the `example/lib/main.dart` file. I comment in or out line 31 (`print('Comment in and out');`).
6. Save to trigger hot reload.
7. One hot reload is done, press the `Subscribe` button again. Observe the error mentioned in the title.

Unfortunately, this seems to be device-dependent. I cannot reproduce on my Pixel 7 Pro, but consistently (maybe not every time, but very, very often) reproduce with my Samsung Galaxy S22 Ultra S908B.

### Expected results

There is no error, or the error tells me what is wrong. Right now the error seems to be coming from very deep in the framework and it seems I can't do anything about it.

### Actual results

The following error is shown:

```console
I/System.out( 1285): >>> Listening

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      AnimationController._tick
#3      Ticker._tick
#4      SchedulerBinding._invokeFrameCallback
#5      SchedulerBinding.handleBeginFrame.<anonymous closure>
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#7      SchedulerBinding.handleBeginFrame
#8      SchedulerBinding._handleBeginFrame
#9      _invoke1 (dart:ui/hooks.dart:158:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:337:5)
#11     _beginFrame (dart:ui/hooks.dart:101:31)
(elided 2 frames from class _AssertionError)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
#2      SchedulerBinding.scheduleFrameCallback
#3      Ticker.scheduleTick
#4      Ticker.start
#5      AnimationController._startSimulation
#6      AnimationController._animateToInternal
#7      AnimationController.forward
#8      ImplicitlyAnimatedWidgetState.didUpdateWidget
#9      StatefulElement.update
#10     Element.updateChild
#11     ComponentElement.performRebuild
#12     StatefulElement.performRebuild
#13     Element.rebuild
#14     StatefulElement.update
#15     Element.updateChild
#16     SingleChildRenderObjectElement.update
#17     Element.updateChild
#18     SingleChildRenderObjectElement.update
#19     Element.updateChild
#20     SingleChildRenderObjectElement.update
#21     Element.updateChild
#22     ComponentElement.performRebuild
#23     StatefulElement.performRebuild
#24     Element.rebuild
#25     BuildOwner.buildScope
#26     WidgetsBinding.drawFrame
#27     RendererBinding._handlePersistentFrameCallback
#28     SchedulerBinding._invokeFrameCallback
#29     SchedulerBinding.handleDrawFrame
#30     SchedulerBinding._handleDrawFrame
#31     _invoke (dart:ui/hooks.dart:142:13)
#32     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#33     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _FrameCallbackEntry)
════════════════════════════════════════════════════════════════════════════════
```

### Code sample

<details><summary>Code sample</summary>

`android/src/main/kotlin/com/example/myplugin/MypluginPlugin.kt`:
```kotlin
package com.example.myplugin

import android.os.Handler
import android.os.Looper
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.EventChannel.StreamHandler
import java.util.Timer
import kotlin.concurrent.fixedRateTimer

class MypluginPlugin : FlutterPlugin {
    private lateinit var intEventChannel: EventChannel

    override fun onAttachedToEngine(flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        intEventChannel = EventChannel(flutterPluginBinding.binaryMessenger, "ints").apply {
            setStreamHandler(IntEventHandler())
        }
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        intEventChannel.setStreamHandler(null)
    }
}

class IntEventHandler : StreamHandler {
    private val mainThreadHandler = Handler(Looper.getMainLooper())
    private var timer: Timer? = null

    override fun onListen(arguments: Any?, events: EventChannel.EventSink) {
        println(">>> Listening")
        var i = 0
        timer = fixedRateTimer(period = 1000L) {
            mainThreadHandler.post {
                events.success(++i)
            }
        }
    }

    override fun onCancel(arguments: Any?) {
        println(">>> Cancelling")
        timer?.cancel()
        timer = null
    }
}
```

`example/lib/main.dart`:
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late final EventChannel _channel;
  late final Stream<int> _stream;

  final List<StreamSubscription<int>> _subscriptions = [];
  String _intText = '';

  @override
  void initState() {
    super.initState();

    _channel = const EventChannel('ints');
    _stream = _channel.receiveBroadcastStream().map<int>(
      (value) {
        print('Comment in and out');
        return value as int;
      },
    );
  }

  @override
  void dispose() {
    for (final s in _subscriptions) {
      unawaited(s.cancel());
    }

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                onPressed: () {
                  _subscriptions.add(
                    _stream.listen((value) {
                      setState(() {
                        _intText = '$value';
                      });
                    }),
                  );
                  setState(() {});
                },
                child: const Text('Subscribe'),
              ),
              ElevatedButton(
                onPressed: _subscriptions.isNotEmpty
                    ? () {
                        unawaited(
                          _subscriptions.removeLast().cancel(),
                        );
                        setState(() {});
                      }
                    : null,
                child: Text('Cancel 1 of ${_subscriptions.length}'),
              ),
              Text(_intText),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report @wujek-srujek 
I followed the steps mentioned but was unable to replicate the reported error / crash, although I tried on Pixel 6 emulator and using latest master version.
Can you switch to latest master and run your scenario again on affected device to check if the error persists or not ?

**Comment by wujek-srujek** [comment]
I can reproduce with 3.10.6 (original version), 3.13.0, and main (`Framework • revision 8617a18575 (58 minutes ago) • 2023-08-16 15:36:49 -0400`). It did take me a few more tries with main, but I also fully updated and restarted the problematic phone. No idea if this was just coincidence.

**Comment by darshankawar** [comment]
Thanks for the update. Since you mentioned S22 Ultra device, I think you are hitting https://github.com/flutter/flutter/issues/106277 which talks about same error and could be device specific and related to refresh rate of the device as also mentioned in the linked issue.
I suggest you to follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by wujek-srujek** [comment]
Thanks @darshankawar it looks like a duplicate indeed.
