### ISSUE TITLE
Wonderous gets unresponsive when opening a world wonder

### ISSUE THREAD

**Issue by gianfrancopapa** [flutter/flutter#132307]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open Wonderous app
2. Navigate to the Great Wall
3. Check that the Great Wall is loaded but gets unresponsive

Environment:
- Samsung Galaxy A03 - API 30
- Pixel 6 - API 33

### Expected results

World wonder screen should load without issues

### Actual results

World wonder screen gets unresponsive

### Code sample

<details><summary>Code sample</summary>

Flutter-wonderous-app : main branch of the repository with latest changes

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/63058517/b4773e5d-7910-4aff-95b9-d0fd1a17a012

</details>

### Logs

<details><summary>Logs</summary>

```console
W/OnBackInvokedCallback(16212): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback(16212): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
I/flutter (16212): Navigate to: /wonder/greatWall?t=0
D/MapsInitializer(16212): preferredRenderer: null
D/zzcb    (16212): preferredRenderer: null
I/zzcb    (16212): Making Creator dynamically
W/ziparchive(16212): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/00000035/DynamiteLoader.dm': No such file or directory
W/ziparchive(16212): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/00000035/DynamiteLoader.dm': No such file or directory
I/DynamiteModule(16212): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203115000
I/DynamiteModule(16212): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203115000
V/DynamiteModule(16212): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/System  (16212): ClassLoader referenced unknown path:
D/nativeloader(16212): Configuring classloader-namespace for other apk . target_sdk_version=33, uses_libraries=, library_path=/data/app/~~REq4MfBdN7N1Q5sa_zfz3w==/com.google.android.gms-l41Di-7ki2oRI5zoFthkAw==/lib/arm64:/data/app/~~REq4MfBdN7N1Q5sa_zfz3w==/com.google.android.gms-l41Di-7ki2oRI5zoFthkAw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
W/ziparchive(16212): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/00000039/MapsDynamite.dm': No such file or directory
W/ziparchive(16212): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/00000039/MapsDynamite.dm': No such file or directory
I/Google Maps Android API(16212): Google Play services client version: 12451000
D/CompatibilityChangeReporter(16212): Compat change id reported: 183155436; UID 10244; state: ENABLED
I/Google Maps Android API(16212): Google Play services package version: 232414044
I/Google Maps Android API(16212): Google Play services maps renderer version(legacy): 203115000
D/MapsInitializer(16212): loadedRenderer: LEGACY
D/zzcb    (16212): preferredRenderer: null
I/Google Maps Android API(16212): Google Play services package version: 232414044
I/Google Maps Android API(16212): Google Play services maps renderer version(legacy): 203115000
D/CompatibilityChangeReporter(16212): Compat change id reported: 210923482; UID 10244; state: ENABLED
D/CompatibilityChangeReporter(16212): Compat change id reported: 171228096; UID 10244; state: ENABLED
I/PlatformViewsController(16212): Using hybrid composition for platform view: 0
W/OnBackInvokedCallback(16212): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback(16212): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
E/GoogleMapController(16212): Cannot enable MyLocation layer as location permissions are not granted
D/TrafficStats(16212): tagSocket(178) with statsTag=0x30001101, statsUid=-1
I/bb      (16212): Successfully registered with Phenotype.
W/DynamiteModule(16212): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(16212): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:7
I/DynamiteModule(16212): Selected remote version of com.google.android.gms.googlecertificates, version >= 7
W/ziparchive(16212): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/00000038/GoogleCertificates.dm': No such file or directory
W/ziparchive(16212): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/00000038/GoogleCertificates.dm': No such file or directory
I/SnapshotHandler(16212): Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#com.gskinner.flutter.wonders, using defaults.
W/MobStoreFlagStore(16212): Unable to update local snapshot for com.google.android.libraries.consentverifier#com.gskinner.flutter.wonders, may result in stale flags.
W/MobStoreFlagStore(16212): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.gskinner.flutter.wonders, sha256=[6e404f6c0fb48a010fea31245b32fa23f9f0be40c2c3a2611f4714165d92c436], atk=false, ver=232414044.true (go/gsrlt)
W/MobStoreFlagStore(16212): 	at m.ajx.s(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):3)
W/MobStoreFlagStore(16212): 	at m.ajx.get(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):2)
W/MobStoreFlagStore(16212): 	at m.alh.g(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):2)
W/MobStoreFlagStore(16212): 	at m.yz.c(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):1)
W/MobStoreFlagStore(16212): 	at m.zb.run(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):0)
W/MobStoreFlagStore(16212): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
W/MobStoreFlagStore(16212): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/MobStoreFlagStore(16212): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
W/MobStoreFlagStore(16212): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/MobStoreFlagStore(16212): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/MobStoreFlagStore(16212): 	at java.lang.Thread.run(Thread.java:1012)
W/MobStoreFlagStore(16212): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.gskinner.flutter.wonders, sha256=[6e404f6c0fb48a010fea31245b32fa23f9f0be40c2c3a2611f4714165d92c436], atk=false, ver=232414044.true (go/gsrlt)
W/MobStoreFlagStore(16212): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
W/MobStoreFlagStore(16212): 	at android.os.Parcel.createException(Parcel.java:2995)
W/MobStoreFlagStore(16212): 	at android.os.Parcel.readException(Parcel.java:2978)
W/MobStoreFlagStore(16212): 	at android.os.Parcel.readException(Parcel.java:2920)
W/MobStoreFlagStore(16212): 	at m.fe.c(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):2)
W/MobStoreFlagStore(16212): 	at m.ry.a(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):4)
W/MobStoreFlagStore(16212): 	at m.jl.e(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):2)
W/MobStoreFlagStore(16212): 	at m.kj.t(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):2)
W/MobStoreFlagStore(16212): 	at m.kj.u(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):3)
W/MobStoreFlagStore(16212): 	at m.kj.e(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):2)
W/MobStoreFlagStore(16212): 	at m.kn.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@232414044@23.24.14 (190400-0):78)
W/MobStoreFlagStore(16212): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/MobStoreFlagStore(16212): 	at android.os.Looper.loopOnce(Looper.java:201)
W/MobStoreFlagStore(16212): 	at android.os.Looper.loop(Looper.java:288)
W/MobStoreFlagStore(16212): 	at android.os.HandlerThread.run(HandlerThread.java:67)
Application finished.

Exited.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.13.0-19.0.pre.78, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.13.0-19.0.pre.78 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 436df69a46 (15 hours ago), 2023-08-08 01:58:16 -0400
    • Engine revision 146c4c9487
    • Dart version 3.2.0 (build 3.2.0-42.0.dev)
    • DevTools version 2.26.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • SM A032F (mobile)           • R7AT900J3RP   • android-arm    • Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by huycozy** [comment]
Hi @gianfrancopapa 
I run the [project](https://github.com/gskinnerTeam/flutter-wonderous-app) on the latest master channel, and follow steps above but it works as expected. Verified on Realme 6, Android 11.

<details>
<summary>Demo</summary>


https://github.com/flutter/flutter/assets/104349824/c620277c-b143-48df-b858-16a21f18dcdb


</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5195m
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-3.0.pre.32, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-3.0.pre.32 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 653187668a (60 minutes ago), 2023-08-10 22:12:34 -0400
    • Engine revision 578a8e8aab
    • Dart version 3.2.0 (build 3.2.0-58.0.dev)
    • DevTools version 2.26.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

The latest master version I checked is: `3.14.0-3.0.pre.32`. Can you retry and confirm?

**Comment by gianfrancopapa** [comment]
Hey @huycozy! I was able to re-test the flow using the latest version of the master channel:
[✓] Flutter (Channel master, 3.14.0-3.0.pre.39, on macOS 13.5 22G74 darwin-arm64, locale en-US)
In a Samsung Galaxy A03 API30 y Pixel 6 API 33
And it worked this time! Should we close the issue?

**Comment by huycozy** [comment]
Thank you for confirming this. Closing the issue as fixed on the latest master version.
