### ISSUE TITLE
Exception caught by rendering library

### ISSUE THREAD

**Issue by Jimmy-Lee05** [flutter/flutter#132302]
RenderBox was not laid out: RenderIgnorePointer#74c81 relayoutBoundary=up31 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1966 pos 12: 'hasSize'

**The Error wanted me to report this issue here, please ask if there is a open question.
I added the error Message and my source**

```
The relevant error-causing widget was: 
  TextField TextField:file:///C:/Users/CENSORED/lib/widgets/AdjustableListWidget.dart:33:35
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1966:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:123:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#6      RenderTapRegion.layout (package:flutter/src/widgets/tap_region.dart:519:11)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#9      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#10     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#11     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#12     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#14     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#17     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#19     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#21     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#24     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#25     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#26     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#27     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#34     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#36     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#37     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:297:14)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#39     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#40     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#42     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#43     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#45     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#46     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#47     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#48     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#50     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#51     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#58     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#61     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#63     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#64     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#65     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#66     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#68     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#69     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:438:14)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#71     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#72     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:491:14)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#74     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#77     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#80     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#83     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#86     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#89     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#92     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#95     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#97     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:554:11)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#99     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#101    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#102    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#103    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#105    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#106    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#107    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056:7)
#108    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
#109    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#110    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2234:7)
#111    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1016:18)
#112    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:492:19)
#113    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#114    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#115    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#116    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#117    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#118    _invoke (dart:ui/hooks.dart:142:13)
#119    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#120    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderTapRegion#d50f7 relayoutBoundary=up30 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(unconstrained)
...  size: MISSING
...  behavior: deferToChild
...  groupId: EditableText
RenderObject: RenderTapRegion#d50f7 relayoutBoundary=up30 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(unconstrained)
  size: MISSING
  behavior: deferToChild
  groupId: EditableText
...  child: RenderIgnorePointer#74c81 relayoutBoundary=up31 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(unconstrained)
...    size: MISSING
...    ignoring: false
...    ignoringSemantics: implicitly false
...    child: RenderSemanticsAnnotations#6012d relayoutBoundary=up32 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: MISSING
...      child: RenderPointerListener#6fb97 relayoutBoundary=up33 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(unconstrained)
...        size: MISSING
...        behavior: translucent
...        listeners: down, panZoomStart
...        child: _RenderDecoration#00131 relayoutBoundary=up34 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(unconstrained)
...          size: MISSING
```

```
class AdjustableListWidget {
  Widget generate(
      String title, List<String> list, bool editable, Function(List<String>) onSave, var update, Function(int) onChangeEditIndex, int editIndex) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 12),
      child: SizedBox(
        width: double.infinity,
        child: ClipRRect(
          borderRadius: const BorderRadius.all(Radius.circular(20)),
          child: Container(
            color: CColor.background.withOpacity(0.27),
            child: Column(
              children: [
                Padding(
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  child: Text(title, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 28)),
                ),
                for (int i = 0; i < list.length; i++)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 8, left: 8, right: 8),
                    child: ClipRRect(
                      borderRadius: const BorderRadius.all(Radius.circular(20)),
                      child: Container(
                        color: CColor.foreground,
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            editIndex == i
                                ? TextField(
                                    //decoration: const InputDecoration(isDense: true),
                                    onSubmitted: (str) {
                                      return;
                                      list.removeAt(i);
                                      list.insert(i, str);
                                      onChangeEditIndex(-1);
                                      onSave(list);
                                    },
                                    //controller: TextEditingController()..text = list[i],
                                  )
                                : Padding(
                                  padding: const EdgeInsets.only(left: 12, top: 10, bottom: 10),
                                  child: Text(list[i], style: const TextStyle(fontSize: 16)),
                                ),
                            // modify buttons
                            Row(
                              children: [
                                GestureDetector(
                                  onTap: () {
                                    onChangeEditIndex(i);
                                    update();
                                  },
                                  child: Icon(Icons.edit, color: (editIndex == i ? Colors.blue : Colors.green)),
                                ),
                                Padding(
                                  padding: const EdgeInsets.symmetric(horizontal: 8),
                                  child: GestureDetector(
                                    onTap: () {
                                      list.removeAt(i);
                                      onSave(list);
                                    },
                                    child: const Icon(Icons.delete_outline),
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                // add new element
                GestureDetector(
                  onTap: () {
                    list.add("test");
                    onSave(list);
                  },
                  child: Padding(
                    padding: const EdgeInsets.only(bottom: 8, left: 8, right: 8),
                    child: ClipRRect(
                      borderRadius: const BorderRadius.all(Radius.circular(20)),
                      child: Container(
                        color: CColor.foreground,
                        child: const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 15),
                          child: Icon(Icons.add, size: 34),
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by dam-ease** [comment]
Hi @Jimmy-Lee05,

Please provide your flutter doctor -v and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue.

Even though the error message says to file an issue, without the information requested above, we cannot proceed with this issue.

Thank you.
