### ISSUE TITLE
Import flutter module to IOS app native 

### ISSUE THREAD

**Issue by farhantandia** [flutter/flutter#132483]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Make a flutter plugin and module
2. using path_provider and quick_blue packages
3. add2app using option A https://docs.flutter.dev/add-to-app/ios/project-setup 
4. call functions from path_provider or quick_blue

### Expected results

I hope the integration work like when using android native

### Actual results

error for path_provider:
`2023-08-14 18:55:57.089106+0800 MyApplicationIOS[22851:4442097] flutter: PlatformException(channel-error, Unable to establish connection on channel., null, null)
2023-08-14 18:55:57.089232+0800 MyApplicationIOS[22851:4442097] flutter: #0      PathProviderApi.getDirectoryPath (package:path_provider_foundation/messages.g.dart:40:7)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121:24)
<asynchronous suspension>
#2      CmdCommonFun.writeFiletoRoot (package:tptaq_bms_util_plugin/tp_bms_lib/read_config/common_fun.dart:118:19)
<asynchronous suspension>`

error for quick_blue:
`Unhandled Exception: MissingPluginException(No implementation found for method stopScan on channel quick_blue/method)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      MethodChannelQuickBlue.stopScan.<anonymous closure> (package:quick_blue_platform_interface/method_channel_quick_blue.dart:44:15)
<asynchronous suspension>`

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console

2023-08-14 18:55:57.089106+0800 MyApplicationIOS[22851:4442097] flutter: PlatformException(channel-error, Unable to establish connection on channel., null, null)
2023-08-14 18:55:57.089232+0800 MyApplicationIOS[22851:4442097] flutter: #0      PathProviderApi.getDirectoryPath (package:path_provider_foundation/messages.g.dart:40:7)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121:24)
<asynchronous suspension>
#2      CmdCommonFun.writeFiletoRoot (package:tptaq_bms_util_plugin/tp_bms_lib/read_config/common_fun.dart:118:19)
<asynchronous suspension>
2023-08-14 18:55:57.090702+0800 MyApplicationIOS[22851:4442097] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method startScan on channel quick_blue/method)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      MethodChannelQuickBlue.startScan.<anonymous closure> (package:quick_blue_platform_interface/method_channel_quick_blue.dart:38:15)
<asynchronous suspension>
2023-08-14 18:56:02.093186+0800 MyApplicationIOS[22851:4442097] flutter: []
2023-08-14 18:56:02.094234+0800 MyApplicationIOS[22851:4442097] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method stopScan on channel quick_blue/method)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      MethodChannelQuickBlue.stopScan.<anonymous closure> (package:quick_blue_platform_interface/method_channel_quick_blue.dart:44:15)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.14.0-3.0.pre.58, on macOS 13.4.1 22F770820d
    darwin-arm64, locale en-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.2)
[✓] VS Code (version 1.68.0)
[✓] Connected device (4 available)
[✓] Network resources


```

</details>

**Comment by dam-ease** [comment]
Hi @farhantandia. Thanks for filing this issue. From the logs for path_provider, can you check out https://stackoverflow.com/a/75083240 to see if this works in your case? If not, you could share a simple github repo that has a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue.
Thank you!

**Comment by farhantandia** [comment]
Hi @dam-ease Thanks for the reference, where do I need put the override functions? in my plugin or in my init block of ios native code?

**Comment by dam-ease** [comment]
Hi @farhantandia. Thanks for your response. I can't seem to reproduce this error with the sample provided. Can you help with reproduction action/steps to produce this with the repo.
Thank you!

**Comment by farhantandia** [comment]
Hi @dam-ease 
1. open the module and run flutter pub get
2. install pod inside the ios app project
3. build the ios xcode project
4. tap 'Diagnosis' button in the app UI

**Comment by farhantandia** [comment]
I also try using swiftUI ios app, but the error is still the same, any walkaround in this case?

**Comment by dam-ease** [comment]
Hi @farhantandia. Thanks for your response. Following the reproduction steps, I am able to reproduce this on my end. Not too familiar with iOS native for a possible workaround but I'd label for further insights.

<details><summary>Log</summary>
<p>

```
2023-08-16 09:52:41.138932+0100 MyApplicationIOS[11646:109156] flutter: The Dart VM service is listening on http://127.0.0.1:55474/8pshAEQ4Z3o=/
2023-08-16 09:55:13.918104+0100 MyApplicationIOS[11646:109137] flutter: 2023-08-16 09:55:13.897127
2023-08-16 09:55:13.919854+0100 MyApplicationIOS[11646:109137] flutter: trendpower 1234
2023-08-16 09:55:13.919916+0100 MyApplicationIOS[11646:109137] flutter: test path provider
2023-08-16 09:55:13.923876+0100 MyApplicationIOS[11646:109137] flutter: PlatformException(channel-error, Unable to establish connection on channel., null, null)
2023-08-16 09:55:13.924331+0100 MyApplicationIOS[11646:109137] flutter: #0      PathProviderApi.getDirectoryPath (package:path_provider_foundation/messages.g.dart:40:7)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121:24)
<asynchronous suspension>
#2      TPBMSUtils.writeFiletoRoot (package:tptaq_bms_util_plugin/tp_bms_lib/tp_bms_utils.dart:104:21)
<asynchronous suspension>
#3      TPBMSUtils.copyConfigFile (package:tptaq_bms_util_plugin/tp_bms_lib/tp_bms_utils.dart:125:18)
<asynchronous suspension>
#4      TPBMSUtils.BMSDiagnosis (package:tptaq_bms_util_plugin/tp_bms_lib/tp_bms_utils.dart:156:7)
<asynchronous suspension>
#5      MethodChannelTptaqBmsUtilPlugin.methodHandler (package:tptaq_bms_util_plugin/tptaq_bms_util_plugin_method_channel.dart:24:20)
<asynchronous suspension>
#6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:42)
<asynchronous suspension>
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:22)
<asynchronous suspension>
Optional(["message": {
    Message = "Start BMS Diagnosis...";
}])
2023-08-16 09:55:14.017221+0100 MyApplicationIOS[11646:109137] flutter: test quick blue
2023-08-16 09:55:14.024806+0100 MyApplicationIOS[11646:109137] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method startScan on channel quick_blue/method)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
2023-08-16 09:55:19.029956+0100 MyApplicationIOS[11646:109137] flutter: []
2023-08-16 09:55:19.031594+0100 MyApplicationIOS[11646:109137] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method stopScan on channel quick_blue/method)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>

``` 

</p>
</details> 

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.6 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.14.0-4.0.pre.29, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.14.0-4.0.pre.29 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b4842cfade (54 minutes ago), 2023-08-15 03:00:39 -0400
    • Engine revision a17130ac4d
    • Dart version 3.2.0 (build 3.2.0-70.0.dev)
    • DevTools version 2.26.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by farhantandia** [comment]
Hi @dam-ease , any response from Flutter team?

**Comment by kundankuldeep** [comment]
Hi @farhantandia, Got one Work around to solve this issue :

Below are the steps you can follow - 

1. Instead of calling " await getApplicationDocumentsDirectory() " to get the document dir path. 
2. Get the path from Native IOS through channel while app initialisation, you can get that by below code. 

    func getDocPath() -> String {
        let docUrl = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first;
        NSLog("Flutter Client : docUrl -> path \(String(describing: docUrl?.path))");
        return docUrl?.path ?? "";
    }

3. Now that you have the path, send this path to flutter framework and create a Directory from that path.
Directory docsDir = Directory(docDirPath ?? "");

4. as getApplicationDocumentsDirectory() returns a Directory object so now you can use " docsDir " to create the storage path

var storePath = p.join(docsDir.path, "sample-db");

This worked for me, you can try if it works for you. thanks!!

**Comment by farhantandia** [comment]
@kundankuldeep Thank you for the suggestion it should work, however, the issue is related to the dependencies importing to ios, not only for path_provider, in this case, I also use BLE package which I need for my plugin function. My plugin goal is to make users easy to use without making additional functions from the native side. I think Flutter team needs to clarify how to solve this issue, hence the use of the Flutter plugin is that it can be implemented for multi-platform, and currently, only on Android it can work seamlessly..

**Comment by jmagman** [comment]
Looks like you are missing `GeneratedPluginRegistrant.register`?
```
     // Connects plugins with iOS platform code to this app.
     GeneratedPluginRegistrant.register(with: self.flutterEngine);
```
https://docs.flutter.dev/add-to-app/ios/add-flutter-screen#create-a-flutterengine

**Comment by jmagman** [comment]
We could make the error message more helpful.
