### ISSUE TITLE
[tool_crash] _Exception

### ISSUE THREAD

**Issue by ibraheemalayan** [flutter/flutter#132501]
## Command
```
flutter attach --machine -d 00008101-000504542603001E --devtools-server-address http://127.0.0.1:9100/ --target lib/main_development.dart --target lib/main_development.dart
```

## Steps to Reproduce

1. build an app from Xcode ( app works and launches )
2. run on a wireless device ( IOS 17 )
3. attach it from vscode 

## Logs
_Exception
```
#0      XCDevice.waitForDeviceToConnect (package:flutter_tools/src/macos/xcdevice.dart:353:9)
#1      IOSDevices.waitForDeviceToConnect (package:flutter_tools/src/ios/devices.dart:228:24)
#2      TargetDevicesWithExtendedWirelessDeviceDiscovery._waitForIOSDeviceToConnect (package:flutter_tools/src/runner/target_devices.dart:422:58)
#3      TargetDevicesWithExtendedWirelessDeviceDiscovery.findAllTargetDevices (package:flutter_tools/src/runner/target_devices.dart:488:33)
<asynchronous suspension>
#4      FlutterCommand.findTargetDevice (package:flutter_tools/src/runner/flutter_command.dart:1615:32)
<asynchronous suspension>
#5      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:263:28)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.5 22G74 darwin-arm64, locale en-IL)
    • Flutter version 3.10.5 on channel stable at /Users/ibraheemalyan/Desktop/ws/OLD/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (9 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ibraheemalyan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android S

**Comment by darshankawar** [comment]
Thanks for the report @ibraheemalayan 
Can you try couple of things as below?

1. Try using https://developer.android.com/studio/run/device#wireless
2. `lib/main_development.dart --target lib/main_development.dart` instead of flavors, if you run directly with `lib/main`, does it still throw the same error ?

With above, trying to confirm if the issue is specific to running through Xcode and flavors or not.
