### ISSUE TITLE
[tool_crash] UnknownException

### ISSUE THREAD

**Issue by hoantruong** [flutter/flutter#132619]
## Command
```
flutter drive \ --driver=test_driver/integration_test.dart \ --target=integration_test/multiple_features_test.dart \ -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnknownException
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:102:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:332:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
    • Flutter version 3.10.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\truh\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.81.1)
    • VS Code at C:\Users\truh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.3086]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.203

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.7.29
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6
### Plugins
file_picker-4.6.1
flutter_dropzone-3.0.6
flutter_dropzone_web-3.0.10
flutter_plugin_android_lifecycle-2.0.15
integration_test
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-1.0.5
path_provider-2.0.15
path_provider_android-2.1.0
path_provider_foundation-2.3.0
path_provider_linux-2.2.0
path_provider_windows-2.0.7
shared_preferences-2.2.0
shared_preferences_android-2.2.0
shared_preferences_foundation-2.3.2
shared_preferences_linux-2.3.0
shared_preferences_web-2.2.0
shared_preferences_windows-2.3.0
url_launcher-6.1.12
url_launcher_android-6.0.38
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.6
url_launcher_web-2.0.18
url_launcher_windows-3.0.7
webview_flutter-4.2.2
webview_flutter_android-3.9.3
webview_flutter_wkwebview-3.7.3

**Comment by darshankawar** [comment]
@hoantruong 
Check [this](https://github.com/flutter/flutter/issues/123602) issue and underlying comments and see if it helps in your case or not.
Also check [this](https://github.com/flutter/flutter/issues/131297#issuecomment-1651399775) and see what chromedriver version are you using and whether Downgrading chromedriver than your current version solves the issue or not. 
Closing from here, as this isn't related to flutter but could be related to the chromedriver version's compatibility. If you disagree, write in comments and I'll reopen it.
