### ISSUE TITLE
GitHub quota is used up occasionally

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#132616]
We have occasionally used up GitHub quota these days:

![Screenshot 2023-08-15 at 8 07 21 PM](https://github.com/flutter/flutter/assets/54558023/013012ae-0316-415a-b1f4-e1615302250f)

```
GitHub Error: API rate limit exceeded for installation ID 10381585.
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:486:5)
#1      GitHub.request (package:github/src/common/github.dart:422:7)
<asynchronous suspension>
#2      GitHub.requestJson (package:github/src/common/github.dart:323:22)
<asynchronous suspension>
#3      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
#4      GithubChecksService.updateCheckStatus (package:cocoon_service/src/service/github_checks_service.dart:87:38)
<asynchronous suspension>
#5      PostsubmitLuciSubscription.post (package:cocoon_service/src/request_handlers/postsubmit_luci_subscription.dart:116:7)
<asynchronous suspension>
#6      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:24)
<asynchronous suspension>
#7      SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:5)
<asynchronous suspension>
#8      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:293:11)
<asynchronous suspension>
```

The usage of quota has been increasing over time considering we have more tests/targets in our CI.
The situation becomes worse when GitHub incidence happens, like today with [webhook](https://www.githubstatus.com/incidents/ljhhhw2tplqp).

This may be even worse when we consider separating tasks into separate sub-tasks.

We should consider separating API calls to be based on different installation IDs.

**Comment by keyonghan** [comment]
We are calling `get check` run API every time we need to update a check run status!!
https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/github_checks_service.dart#L88

This is not needed at all because the update check run only needs the check run id, which we can get from the build user data. Removing this get check run API call, I would expect our quota use drops dramatically.

**Comment by keyonghan** [comment]
For newly scheduled build, there is no `startedTimestamp` available yet:
<img width="1345" alt="Screenshot 2023-10-13 at 11 15 45 AM" src="https://github.com/flutter/flutter/assets/54558023/b398fd46-79e0-46e1-a829-ac5e57539f63">

**Comment by keyonghan** [comment]
Log warning was added in https://github.com/flutter/cocoon/pull/3212, and alert is setup as [GitHub Quota Usage](https://console.cloud.google.com/monitoring/alerting/policies/10780742383187435448?project=flutter-dashboard0

**Comment by keyonghan** [comment]
Hourly usage is roughly below 50% for the past two weeks. Closing.
