### ISSUE TITLE
report a bug on my device （ huawei  HONOR 50 Pro）

### ISSUE THREAD

**Issue by DevChen** [flutter/flutter#132617]
```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#5051f(physicalKey: PhysicalKeyboardKey#3b725(usbHidUsage: "0x1100000004", debugName: "Key with ID 0x1100000004"), logicalKey: LogicalKeyboardKey#5dfc4(keyId: "0x100001005", keyLabel: "Go Back", debugName: "Go Back"), character: null, timeStamp: 0:00:08.747686)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 434 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:434:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:445:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:537:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:956:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:35)
#8      _invoke2 (dart:ui/hooks.dart:174:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:223:31)
(elided 4 frames from class _AssertionError and dart:async)
====================================================================================================
```

**Comment by danagbemava-nc** [comment]
Hi @DevChen, thanks for filing this issue. 

Please provide the output of `flutter doctor -v`. 
Does this crash occur every time? 
Does it prevent you from typing with the keyboard? 
Also what keyboard are you using?
