### ISSUE TITLE
MaterialApp constructor missing parameter exception message is over-complicated

### ISSUE THREAD

**Issue by jcollins-g** [flutter/flutter#13276]
Filing as requested by @Hixie from the Flutter PDX Hackathon notes:

--snip--
While doing the Friendlychat tutorial, I mistakenly had ChatScreen extend MaterialApp instead of StatelessWidget at this stage: 
   https://codelabs.developers.google.com/codelabs/flutter/index.html#3

Only one analysis hint helped me and the flutter run diagnostic wasn't useful:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building FriendlyChatApp(dirty):
Either the home property must be specified, or the routes table must include an entry for "/", or
there must be on onGenerateRoute callback specified, or there must be an onUnknownRoute callback
specified, because otherwise there is nothing to fall back on if the app is started with an intent
that specifies an unknown route.
'package:flutter/src/material/app.dart': Failed assertion: line 110 pos 10: 'home != null ||
routes.containsKey(Navigator.defaultRouteName) ||
onGenerateRoute != null ||
onUnknownRoute != null'
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new
```
Figured it out in a minute on a second look at the code, but the error message was a distraction.
--snip--

It might just be a case of the error message being too complicated. If I had known instead that I hadn't passed the required parameters, I would have guessed I was using the wrong class.

Instead, the error message optimistically assumed I really knew a lot about the framework and was convinced I had some valid reason for doing what I was asking for, which I didn't.  In this case, "missing required parameters" followed maybe by a terse list would have steered me in the right direction.

**Comment by zoechi** [comment]
Sounds like this would require a way to require one of a list of parameters to be passed or did I misunderstand the request?

When I look at https://github.com/flutter/flutter/blob/a0efb78640750ccc6b7a461a14ab7b1f74df7817/packages/flutter/lib/src/widgets/app.dart#L182-L188 I think a few line breaks to see the code like in the source would make it much easier to read.

**Comment by jcollins-g** [comment]
This isn't a problem with the formatting of the error message, it's that the error message assumes I know what I'm doing by extending that class but a common problem is that I'm not actually extending what I should be.  There's a long explanation of parameters instead of something drawing my attention to the real problem (e.g. "missing parameters" with a terse list of what's missing).  If I had seen that, I would have been able to quickly identify that I was extending the wrong class rather than have to read a paragraph and deduce that.

**Comment by jcollins-g** [comment]
As far as the "terse list of what's missing" part, that's not as vital as something easily spottable that says "missing parameters".   I think the most important things in this message are, in order of priority:

1) Location of the error
2) There are missing parameters to a constructor
3) What the missing parameters are

I can find 1 with only a bit of difficulty because I'm used to searching for stack traces in big piles of output, but for two and three I have to read a wall of text.

**Comment by markusaksli-nc** [comment]
Seems like this has regressed when checking on the latest master `1.21.0-2.0.pre.114`.
Minimal reproducible code sample:

 ```
import 'package:flutter/material.dart';
void main() => runApp(MaterialApp());
```
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-2.0.pre.114, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.21.0-2.0.pre.114 at C:\Development\flutter_master
    • Framework revision ddb8e6e3bf (7 hours ago), 2020-07-22 20:00:07 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (5 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.18362.900]
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>
<details>
 <summary>Output</summary>

 ```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
Could not find a generator for route RouteSettings("/", null) in the _WidgetsAppState.

Generators for routes are searched for in the following order:
 1. For the "/" route, the "home" property, if non-null, is used.
 2. Otherwise, the "routes" table is used, if it has an entry for the route.
 3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not handled by "home" and "routes".
 4. Finally if all else fails onUnknownRoute is called.
Unfortunately, onUnknownRoute was not set.
The relevant error-causing widget was: 
  ChatApp file:///C:/Users/Isa/Google%20Drive/Nevercode/triage/lib/main.dart:14:15
When the exception was thrown, this was the stack: 
#0      _WidgetsAppState._onUnknownRoute.<anonymous closure> (package:flutter/src/widgets/app.dart:1018:9)
#1      _WidgetsAppState._onUnknownRoute (package:flutter/src/widgets/app.dart:1031:6)
#2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:3396:36)
#3      Navigator.defaultGenerateInitialRoutes (package:flutter/src/widgets/navigator.dart:2295:28)
#4      NavigatorState.initState (package:flutter/src/widgets/navigator.dart:2781:39)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [GlobalObjectKey<NavigatorState> _WidgetsAppState#67b3d]
The parent of the widgets with that key was: IconTheme
  color: Color(0xdd000000)
The first child to get instantiated with that key became: Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#67b3d]
  dirty
  state: NavigatorState#7d670(lifecycle state: created)
The second child that was to be instantiated with that key was: IconTheme
  color: Color(0xdd000000)
A GlobalKey can only be specified on one widget at a time in the widget tree.
The relevant error-causing widget was: 
  ChatApp file:///C:/Users/Isa/Google%20Drive/Nevercode/triage/lib/main.dart:14:15
When the exception was thrown, this was the stack: 
#0      Element._retakeInactiveElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:3441:11)
#1      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3455:8)
#2      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3485:32)
#3      Element.updateChild (package:flutter/src/widgets/framework.dart:3259:20)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4584:16)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by justinmc** [comment]
I've improved the error message a bit in https://github.com/flutter/flutter/pull/63005.  Unfortunately it's not possible to catch this in the asserts because the logic for determining if the route is handled can be complicated.  Hopefully the new error message will guide people in the right direction, though.
