### ISSUE TITLE
[go_router] Assertion was thrown when getting `GoRouterState.of(context)` inside a nested Navigator

### ISSUE THREAD

**Issue by crizant** [flutter/flutter#132824]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use go_router 10
2. Run the code sample on chrome or simulator
3. Observe the console output

It used to work with go_router 8.x.x when I was able to get the router location by using `GoRouter.of(context).location`.

### Expected results

Able to get go router state within the routes of a nested Navigator.

### Actual results

Assertion was thrown.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final router = GoRouter(routes: [
  GoRoute(
    path: '/',
    builder: (BuildContext context, GoRouterState state) => const MyHomePage(),
  ),
]);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      routerConfig: router,
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Navigator(
        pages: const [
          MaterialPage(
            child: MySubPage(),
          ),
        ],
        onPopPage: (route, result) {
          if (!route.didPop(result)) {
            return false;
          }
          return true;
        },
      ),
    );
  }
}

class MySubPage extends StatelessWidget {
  const MySubPage({super.key});

  @override
  Widget build(BuildContext context) {
    final fullPath = GoRouterState.of(context).fullPath ?? '';
    return Center(
      child: Text(fullPath),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MySubPage(dirty,
dependencies:
[GoRouterStateRegistryScope, _ModalScopeStatus]):
'package:go_router/src/state.dart': Failed assertion: line 204 pos
12: 'registry.containsKey(page)':
is not true.

The relevant error-causing widget was:
  MySubPage
  MySubPage:file:///Users/CrizantLai/Documents/go_router_test/lib/
  main.dart:42:20

When the exception was thrown, this was the stack:
#2      GoRouterStateRegistry._createPageRouteAssociation
(package:go_router/src/state.dart:204:12)
#3      GoRouterState.of (package:go_router/src/state.dart:126:25)
#4      MySubPage.build (package:go_router_test/main.dart:61:36)
#5      StatelessElement.build
(package:flutter/src/widgets/framework.dart:5156:49)
#6      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:5086:15)
#7      Element.rebuild
(package:flutter/src/widgets/framework.dart:4805:7)
#8      ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:5068:5)
#9      ComponentElement.mount
(package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (24 frames)
#33     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3971:16)
#34     MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6570:36)
#35     MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (178 frames)
#213    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3971:16)
#214    MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6570:36)
#215    MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (95 frames)
#310    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3971:16)
#311    MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6570:36)
#312    MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (140 frames)
#452    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3971:16)
#453    MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6570:36)
#454    MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (178 frames)
#632    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3971:16)
#633    MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6570:36)
#634    MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (525 frames)
#1159   Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3971:16)
#1160   Element.updateChild
(package:flutter/src/widgets/framework.dart:3708:18)
#1161   RenderObjectToWidgetElement._rebuild
(package:flutter/src/widgets/binding.dart:1240:16)
#1162   RenderObjectToWidgetElement.mount
(package:flutter/src/widgets/binding.dart:1209:5)
#1163   RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous
closure> (package:flutter/src/widgets/binding.dart:1156:18)
#1164   BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2720:19)
#1165   RenderObjectToWidgetAdapter.attachToRenderTree
(package:flutter/src/widgets/binding.dart:1155:13)
#1166   WidgetsBinding.attachRootWidget
(package:flutter/src/widgets/binding.dart:988:7)
#1167   WidgetsBinding.scheduleAttachRootWidget.<anonymous
closure> (package:flutter/src/widgets/binding.dart:968:7)
#1171   _RawReceivePort._handleMessage
(dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and
dart:async-patch)

══════════════════════════════════════════════════════════════════
══════════════════════════════════
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d
    darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I do see the same error as reported.
Although there's another similar error reported in https://github.com/flutter/flutter/issues/131217, but it makes use of `ShellRoute` and also when `extendBodyBehindAppBar` is `true`, but in above case, both implementations aren't use, but still throwing the same error, which could be another use case triggering the similar error in both issues.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.13.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (27 hours ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.14.0-6.0.pre, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.14.0-6.0.pre on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b7046b32db (26 hours ago), 2023-08-17 01:04:23 -0300
    • Engine revision 533670269c
    • Dart version 3.2.0 (build 3.2.0-78.0.dev)
    • DevTools version 2.26.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by sorich87** [comment]
I got the same error, and moving the GlobalKey variables from the global state fixed the issue, as suggested in this StackOverflow answer: https://stackoverflow.com/a/75101717

**Comment by crizant** [comment]
> I got the same error, and moving the GlobalKey variables from the global state fixed the issue, as suggested in this StackOverflow answer: https://stackoverflow.com/a/75101717

Man, I didn't even use a single `GlobalKey` in my code sample.

**Comment by sorich87** [comment]
@crizant of course. I just wanted to share a similar issue in case it gives some clues.

**Comment by ReversedHourglass** [comment]
Got the same issue using a `ShellRoute` but without using `extendBodyBehindAppBar`. I'm not creating a new Issue for this since it seems pretty similar to this one, feel free to ask me to do it if you think that it's relevant.

Retrieving `path` `fullPath` or `uri` from  `GoRouterState.of(context)` result in the same bug. 

It is particularly a problem from me because I was using this to be able to move to different branches regardless of the parent. Allowing me to use the same page for two distinct routes. Didn't found any other solution to this except using the path. (Using PageY as a children of PageA and PageB, without needing to pass any argument to PageY specifying his parent.)

```
goCustomGoAdd({
  required BuildContext context,
  required String path,
  Object? extra,
}) {
  final String location = GoRouterState.of(context).uri.toString();

  context.push('$location/$path', extra: extra);
}
```

Anyways, here is a code sample using `StatefulShellRoute`

<details>
  <summary>Code sample</summary>


```
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final GoRouter router = GoRouter(
  initialLocation: '/a',
  routes: <RouteBase>[
    StatefulShellRoute(
        builder: (BuildContext context, GoRouterState state,
            StatefulNavigationShell navigationShell) {
          return navigationShell;
        },
        navigatorContainerBuilder: (BuildContext context,
            StatefulNavigationShell navigationShell, List<Widget> children) {
          return TabPage(navigationShell: navigationShell, children: children);
        },
        branches: <StatefulShellBranch>[
          StatefulShellBranch(
            routes: <RouteBase>[
              GoRoute(
                path: '/a',
                builder: (BuildContext context, GoRouterState state) =>
                    const MyHomePage(),
              ),
              GoRoute(
                path: '/b',
                builder: (BuildContext context, GoRouterState state) =>
                    const MyHomePage(),
              ),
            ],
          ),
        ])
  ],
);

void main() {
  runApp(const MyApp());
}

class TabPage extends StatelessWidget {
  final StatefulNavigationShell navigationShell;
  final List<Widget> children;

  const TabPage({
    Key? key,
    required this.navigationShell,
    required this.children,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: children[navigationShell.currentIndex],
        bottomNavigationBar: BottomNavigationBar(
          showSelectedLabels: true,
          showUnselectedLabels: false,
          backgroundColor: Theme.of(context).scaffoldBackgroundColor,
          currentIndex: navigationShell.currentIndex,
          onTap: (index) {
            _onItemTapped(index, context);
          },
          items: const [
            BottomNavigationBarItem(
              label: 'A',
              icon: Icon(Icons.home),
            ),
            BottomNavigationBarItem(
              label: 'B',
              icon: Icon(Icons.home),
            ),
          ],
        ));
  }

  void _onItemTapped(int index, BuildContext context) {
    navigationShell.goBranch(
      index,
      initialLocation: index == navigationShell.currentIndex,
    );
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      routerConfig: router,
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Navigator(
        pages: const [
          MaterialPage(
            child: MySubPage(),
          ),
        ],
        onPopPage: (route, result) {
          if (!route.didPop(result)) {
            return false;
          }
          return true;
        },
      ),
    );
  }
}

class MySubPage extends StatelessWidget {
  const MySubPage({super.key});

  @override
  Widget build(BuildContext context) {
    final fullPath = GoRouterState.of(context).fullPath ?? '';
    return Center(
      child: Text(fullPath),
    );
  }
}
```

</details>


<details>
  <summary>Console logs</summary>


```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MySubPage(dirty, dependencies:
[GoRouterStateRegistryScope, _ModalScopeStatus]):
Assertion failed:
file:///Users/tomalegre/.pub-cache/hosted/pub.dev/go_router-10.1.2/lib/src/state.dart:204:12
state.dart:204
registry.containsKey(page)
is not true
The relevant error-causing widget was:
MySubPage
main.dart:108
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3    assertFailed
packages/go_router/src/state.dart 204:37                                      [_createPageRouteAssociation]
packages/go_router/src/state.dart 126:14                                      of
packages/goroutertest/main.dart 127:48                                        build
```

</details>

**Comment by Dboy233** [comment]
> I got the same error, and moving the GlobalKey variables from the global state fixed the issue, as suggested in this StackOverflow answer: https://stackoverflow.com/a/75101717

I used the method you recommended to convert the global GoRouter into a dynamically generated approach, so that this error won't occur during hot reloading.

``` dart

final rootNavigationKey = GlobalKey<NavigatorState>();
final shellNavigationKey = GlobalKey<NavigatorState>();

createRouter() => GoRouter(
    navigatorKey: rootNavigationKey,
    ...
   );
```

**Comment by ivanthz** [comment]
Same problem here...

**Comment by ja2375** [comment]
Same problem here, and in my case this issue makes the app stop working after navigating through routes for the first time.

**Comment by antoijo** [comment]
Same issue here, 

There is an issue in the comparison (== operator) used during the assert line 204 of state.dart. 

The page object is in the registry but the two objects (page parameter and the page in the registry) don't have the same hash code.

I haven't found yet why the two objects are somehow different, but maybe an override of the == operator to compare the key of each page instead of the whole object could fix the issue.

**Comment by shareefhadid** [comment]
Updating to the latest version produced this issue for me.

**Comment by crizant** [comment]
> Just tried the code sample,
> 
> The issue come from GoRouter trying to obtain the Route from inner Navigator though `ModalRoute.of(context) in GoRouterState of(BuildContext context)` (you can see `MaterialPage.name` from screenshot below) that didn't create by GoRouter itself therefore can't find in the registery
> 
> ![image](https://private-user-images.githubusercontent.com/9416042/288111590-226a014c-dbd0-423c-bdb4-23b0497f8932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTY5MTksIm5iZiI6MTcwNDY5NjYxOSwicGF0aCI6Ii85NDE2MDQyLzI4ODExMTU5MC0yMjZhMDE0Yy1kYmQwLTQyM2MtYmRiNC0yM2IwNDk3Zjg5MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDY1MDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmViN2E4NWIwNTA2ZGQ5ODhjMDJkOTQwNWZiNzgxMWQ0ZTU3YTk1MmRmNmZkOTEzNzE3NjEyOWRkOTk2NzI3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZCKgFzRHx1T7RHCLXngA6vhYArZMjIUUCIPA7QDfIJo)
> 
> Also do some quick test for it, i tried modify sample code below, use the context in `Navigator` so it can get the route by walk though the element tree start from Navigator, and it can get the path name `/` successfully
> 
> ```dart
> class MySubPage extends StatelessWidget {
>   const MySubPage({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     final outerContext = Navigator.of(context).context;
>     final fullPath = GoRouterState.of(outerContext).fullPath ?? 'empty';
> 
>     return Center(
>       child: Text(fullPath),
>     );
>   }
> }
> ```

@tomcheung Your workaround does work. But the `build` method of the `MySubPage` won't be invoked again if the path is changed.
I need this because I have something like:
```
final isActive = routerState.fullPath == '/settings/account',
```
Then the `isActive` variable will not be updated on route change.

**Comment by crizant** [comment]
> Got the same issue using a `ShellRoute` but without using `extendBodyBehindAppBar`. I'm not creating a new Issue for this since it seems pretty similar to this one, feel free to ask me to do it if you think that it's relevant.
> 
> Retrieving `path` `fullPath` or `uri` from `GoRouterState.of(context)` result in the same bug.
> 
> It is particularly a problem from me because I was using this to be able to move to different branches regardless of the parent. Allowing me to use the same page for two distinct routes. Didn't found any other solution to this except using the path. (Using PageY as a children of PageA and PageB, without needing to pass any argument to PageY specifying his parent.)
> 
> ```
> goCustomGoAdd({
>   required BuildContext context,
>   required String path,
>   Object? extra,
> }) {
>   final String location = GoRouterState.of(context).uri.toString();
> 
>   context.push('$location/$path', extra: extra);
> }
> ```
> 
> Anyways, here is a code sample using `StatefulShellRoute`
> 
> Code sample
> Console logs
> @crizant Do you found any downgraded version which fixes the Issue ? With your sample and using go_router `8.2.0` I still have the same Issue.

go_router 8.0.3 do not have this issue.
