### ISSUE TITLE
[tool_crash] XmlTagException

### ISSUE THREAD

**Issue by msalman360** [flutter/flutter#132801]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
XmlTagException
```
#0      XmlAnnotator.annotate (package:xml/src/xml_events/annotations/annotator.dart:88:13)
#1      XmlEventIterator.moveNext (package:xml/src/xml_events/iterator.dart:32:20)
#2      Iterable.forEach (dart:core/iterable.dart:325:23)
#3      XmlNodeDecoder.convertIterable (package:xml/src/xml_events/converters/node_decoder.dart:53:12)
#4      new XmlDocument.parse (package:xml/src/xml/nodes/document.dart:34:41)
#5      AndroidProject.computeEmbeddingVersion (package:flutter_tools/src/project.dart:649:30)
#6      AndroidProject.checkForDeprecation (package:flutter_tools/src/project.dart:592:50)
#7      FlutterProject.checkForDeprecation (package:flutter_tools/src/project.dart:381:15)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1333:13)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[!] Flutter (Channel unknown, 3.3.0-0.2.pre, on macOS 13.5 22G74 darwin-x64, locale en-GB)
    ! Flutter version 3.3.0-0.2.pre on channel unknown at /Users/apple/Desktop/development/flutter
    ! Upstream repository unknown
    • Framework revision 7ac27ac8e6 (1 year ago), 2022-08-02 14:35:08 -0700
    • Engine revision d1e7dc18bf
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 02c026b03cd31dd3f867e5faeb7e104cce174c5f
### Plugins
path_provider-2.0.4
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
shared_preferences-2.0.12
shared_preferences_android-2.0.10
shared_preferences_ios-2.0.9
shared_preferences_linux-2.0.4
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.3
shared_preferences_windows-2.0.4

**Comment by danagbemava-nc** [comment]
Hi @msalman360, you are using an outdated version of flutter. This has been fixed in recent releases on flutter. Kindly upgrade to the latest version of flutter. 

Closing as this has already been fixed in newer versions of flutter.

**Comment by msalman360** [comment]
thank you so much 🙂
