### ISSUE TITLE
[url_launcher] exposed beyond app through Intent.getData(), null, android.os.FileUriExposedException

### ISSUE THREAD

**Issue by dipak2726** [flutter/flutter#132829]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. download file from url or write file to path on android
2.  try to open file using  await launchUrl(uri);

### Expected results

should open file

### Actual results

throw exception 

```console
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): Failed to handle method call
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): android.os.FileUriExposedException: file:///data/user/0/com.socilogica.fishingApp/app_flutter/dfo/FR%20-%20Lobster%20Instructions.pdf exposed beyond app through Intent.getData()
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2208)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.net.Uri.checkFileUriExposed(Uri.java:2407)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:11895)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:11844)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1833)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Activity.startActivityForResult(Activity.java:5471)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Activity.startActivityForResult(Activity.java:5429)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Activity.startActivity(Activity.java:5927)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Activity.startActivity(Activity.java:5894)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.plugins.urllauncher.UrlLauncher.launch(UrlLauncher.java:91)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onLaunch(MethodCallHandlerImpl.java:96)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:41)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[log] PlatformException(error, file:///data/user/0/com.socilogica.fishingApp/app_flutter/dfo/FR%20-%20Lobster%20Instructions.pdf exposed beyond app through Intent.getData(), null, android.os.FileUriExposedException: file:///data/user/0/com.socilogica.fishingApp/app_flutter/dfo/FR%20-%20Lobster%20Instructions.pdf exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2208)
	at android.net.Uri.checkFileUriExposed(Uri.java:2407)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11895)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11844)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1833)
	at android.app.Activity.startActivityForResult(Activity.java:5471)
	at android.app.Activity.startActivityForResult(Activity.java:5429)
	at android.app.Activity.startActivity(Activity.java:5927)
	at android.app.Activity.startActivity(Activity.java:5894)
	at io.flutter.plugins.urllauncher.UrlLauncher.launch(UrlLauncher.java:91)
	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onLaunch(MethodCallHandlerImpl.java:96)
	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:41)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
)
```
### Code sample

<details><summary>Code sample</summary>

```dart
    final appDocumentsDir = await getApplicationDocumentsDirectory();
    final path = '${appDocumentsDir.absolute.path}/dfo/${val.name}.pdf';
    final Uri uri = Uri.file(path);

    if (File(path).existsSync()) {
      log('File exists at $path');

      await launchUrl(uri);
    } else {
      log('File does not exist at $path');

      try {
        final httpService = ref.watch(httpServiceProvider);
        final res = await httpService.download(val.url, path);

        log('downloaded file at $path');

        await launchUrl(uri);
      } on Exception catch (e) {
        log(e.toString());
        showErrorSnackBar(context, e.toString());
      }
    }

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): Failed to handle method call
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): android.os.FileUriExposedException: file:///data/user/0/com.socilogica.fishingApp/app_flutter/dfo/FR%20-%20Lobster%20Instructions.pdf exposed beyond app through Intent.getData()
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2208)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.net.Uri.checkFileUriExposed(Uri.java:2407)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:11895)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:11844)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1833)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Activity.startActivityForResult(Activity.java:5471)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Activity.startActivityForResult(Activity.java:5429)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Activity.startActivity(Activity.java:5927)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.Activity.startActivity(Activity.java:5894)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.plugins.urllauncher.UrlLauncher.launch(UrlLauncher.java:91)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onLaunch(MethodCallHandlerImpl.java:96)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:41)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#plugins.flutter.io/url_launcher_android( 5814): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[log] PlatformException(error, file:///data/user/0/com.socilogica.fishingApp/app_flutter/dfo/FR%20-%20Lobster%20Instructions.pdf exposed beyond app through Intent.getData(), null, android.os.FileUriExposedException: file:///data/user/0/com.socilogica.fishingApp/app_flutter/dfo/FR%20-%20Lobster%20Instructions.pdf exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2208)
	at android.net.Uri.checkFileUriExposed(Uri.java:2407)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11895)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11844)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1833)
	at android.app.Activity.startActivityForResult(Activity.java:5471)
	at android.app.Activity.startActivityForResult(Activity.java:5429)
	at android.app.Activity.startActivity(Activity.java:5927)
	at android.app.Activity.startActivity(Activity.java:5894)
	at io.flutter.plugins.urllauncher.UrlLauncher.launch(UrlLauncher.java:91)
	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onLaunch(MethodCallHandlerImpl.java:96)
	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:41)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
dipak@dipaks-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F770820d darwin-x64,
    locale en-IN)
    • Flutter version 3.13.0 on channel stable at
      /Users/dipak/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (2 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/dipak/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/dipak/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/dipak/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.8660.129

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13
      (API 33) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 13.4.1
      22F770820d darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google
      Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
dipak@dipaks-MacBook-Pro ~ % 

```

</details>

**Comment by huycozy** [comment]
Hi @dipak2726 
This is a behavior change since Android API 24: https://developer.android.com/about/versions/nougat/android-7.0-changes#sharing-files:

>To share files between applications, you should send a content:// URI and grant a temporary access permission on the URI. The easiest way to grant this permission is by using the [FileProvider](https://developer.android.com/reference/android/support/v4/content/FileProvider) class. For more information on permissions and sharing files, see [Sharing Files](https://developer.android.com/training/secure-file-sharing).

You can try this [SO answer](https://stackoverflow.com/a/38858040/5921933) or other answers there to see if it works. 

Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Closing for now.

**Comment by dipak2726** [comment]
> Hi @dipak2726 This is a behavior change since Android API 24: https://developer.android.com/about/versions/nougat/android-7.0-changes#sharing-files:
> 
> > To share files between applications, you should send a content:// URI and grant a temporary access permission on the URI. The easiest way to grant this permission is by using the [FileProvider](https://developer.android.com/reference/android/support/v4/content/FileProvider) class. For more information on permissions and sharing files, see [Sharing Files](https://developer.android.com/training/secure-file-sharing).
> 
> You can try this [SO answer](https://stackoverflow.com/a/38858040/5921933) or other answers there to see if it works.
> 
> Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Closing for now.

@huycozy I tried above way by adding file provider
but that file provider need to invocated by native code, not via flutter code

**Comment by huycozy** [comment]
You should handle this on native (Android) rather than Flutter. Please also see flutter's [community](https://flutter.dev/community) for resources and ask questions like this as well.
