### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\spesc_000\Desktop\FlutterDev\PracticeProjects\foo\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\Users\spesc_000\Desktop\FlutterDev\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: アクセスが拒否されました。, errno = 5)

### ISSUE THREAD

**Issue by mhammedkaled** [flutter/flutter#132966]
## Command
```
flutter --verbose create foo
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\spesc_000\Desktop\FlutterDev\PracticeProjects\foo\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\Users\spesc_000\Desktop\FlutterDev\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: アクセスが拒否されました。
, errno = 5)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:227:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#6      Template.render (package:flutter_tools/src/template.dart:153:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:630:21)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
```
```
[✓] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.1082], locale ja-JP)
    • Flutter version 1.17.3 at C:\Users\spesc_000\Desktop\FlutterDev\flutter
    • Framework revision b041144f83 (3 months ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\spesc_000\Desktop\FlutterDev\androidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Users\spesc_000\Desktop\FlutterDev\androidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.0)
    • VS Code at C:\Users\spesc_000\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
> Channel stable, v1.17.3

@mhammedkaled You are on obsolete version of the framework. Current version is 3.13.0. I recommend to upgrade your setup to latest and try again to check if you still get same error or not.

Closing for now.
