### ISSUE TITLE
 W/MessageQueue( 4199): Handler (android.os.Handler) {e74f040} sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by madmouse17** [flutter/flutter#132905]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

i use the package [camera ](camera: ^0.10.5+3) on redmi note 9 pro and error hanlded on a dead thread

### Expected results

Yesterday it was running normally but now there is an error

### Actual results

sometimes getsurface error occurs

### Code sample

<details><summary>Code sample</summary>

```dart
Future<CameraDescription> getCamera(CameraLensDirection dir) async {
  return cameras!.firstWhere(
    (CameraDescription camera) => camera.lensDirection == dir,
  );
}
initializeCamera(){
 CameraDescription description = await getCamera(_direction);

    _camera = CameraController(description, ResolutionPreset.low,
        enableAudio: false, imageFormatGroup: ImageFormatGroup.yuv420);
    await _camera!.initialize();

if (_camera != null && _camera!.value.isInitialized) {
 _camera!.startImageStream((CameraImage image) {
//my logic code tflite
  }
 }
}

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // App state changed before we got the chance to initialize.
    if (_camera == null || !_camera!.value.isInitialized) {
      log('nonot');
      return;
    }

    if (state == AppLifecycleState.inactive) {
      pauseCamera();
    } else if (state == AppLifecycleState.resumed) {
      resumeCamera();
    } else if (state == AppLifecycleState.paused) {
      return;
    } else if (state == AppLifecycleState.detached) {
      return;
    }
  }

  void pauseCamera() {
    if (_camera != null && _camera!.value.isInitialized) {
      _camera!.pausePreview();
    }
  }

  void resumeCamera() {
    if (_camera != null) {
      if (_camera!.value.isPreviewPaused) {
        _camera!.resumePreview();
      } else {
        onNewCameraSelected();
      }
    }
  }

  void onNewCameraSelected() async {
    if (_camera != null) {
      await _camera!.dispose();
    }
    CameraDescription description = await getCamera(_direction);

    _camera = CameraController(description, ResolutionPreset.low,
        enableAudio: false, imageFormatGroup: ImageFormatGroup.yuv420);
    log('onNewCameraSelected');

    // If the controller is updated then update the UI.
    _camera!.addListener(() {
      log('errord');

      if (mounted) setState(() {});
      if (_camera!.value.hasError) {
        log('errorc');
        AlertBottom().snackBarAlertPermission(
            text: "Camera error ${_camera!.value.errorDescription}");
        // showInSnackBar('Camera error ${controller.value.errorDescription}');
      }
    });

    try {
      await _camera!.initialize();
    } on CameraException catch (e) {
      print('errorcamera:' + e.description.toString());
    }

    if (mounted) {
      setState(() {});
    }
  }

  @override
  void dispose() async {
    // TODO: implement dispose
    super.dispose();
    WidgetsBinding.instance.removeObserver(this);
    if (_camera != null && _camera!.value.isInitialized) {
      await _camera!.stopImageStream();

      _camera!.dispose();

      _faceDetector.close();
    }
  }



```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![Cuplikan layar 2023-08-20 141949](https://github.com/flutter/flutter/assets/33163281/51297268-fd75-4b4e-9a93-c6e983aea1cb)
</details>

### Logs

<details><summary>Logs</summary>

```console
[   +4 ms] W/libc    ( 3784): Access denied finding property "persist.vendor.camera.privapp.list"
[        ] D/CameraExtImplXiaoMi( 3784): initCameraDevice: 1
[  +18 ms] I/Camera  ( 3784): startPreview
[   +5 ms] W/libc    ( 3784): Access denied finding property "persist.vendor.camera.privapp.list"
[        ] D/CameraExtImplXiaoMi( 3784): initCameraDevice: 1
[        ] W/CameraDevice-JV-1( 3784): Device error received, code 0, frame number 0, request ID -1, subseq ID 0
[   +1 ms] D/CameraDevice-JV-1( 3784): waitUntilIdle: E. id = 1
[   +7 ms] D/CameraDevice-JV-1( 3784): waitUntilIdle: X
[   +2 ms] E/CameraCaptureSession( 3784): Session 0: Failed to create capture session; configuration failed
[  +10 ms] I/Camera  ( 3784): open | onOpened error: CAMERA_DISCONNECTED (2): checkPidStatus:2329: The camera device has been disconnected
[        ] I/Camera  ( 3784): close
[        ] D/CameraExtImplXiaoMi( 3784): releaseCameraDevice: 1
[        ] D/CameraDevice-JV-1( 3784): close: E. id = 1
[        ] D/CameraDevice-JV-1( 3784): close: X
[        ] I/Camera  ( 3784): open | onClosed
[        ] I/Camera  ( 3784): CameraCaptureSession onConfigureFailed
[   +2 ms] W/MessageQueue( 3784): Handler (android.os.Handler) {adf22d3} sending message to a Handler on a dead thread
[        ] W/MessageQueue( 3784): java.lang.IllegalStateException: Handler (android.os.Handler) {adf22d3} sending message to a Handler on a dead thread   
[        ] W/MessageQueue( 3784):       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:572)
[        ] W/MessageQueue( 3784):       at android.os.Handler.enqueueMessage(Handler.java:778)
[        ] W/MessageQueue( 3784):       at android.os.Handler.sendMessageAtTime(Handler.java:727)
[        ] W/MessageQueue( 3784):       at android.os.Handler.sendMessageDelayed(Handler.java:697)
[        ] W/MessageQueue( 3784):       at android.os.Handler.post(Handler.java:427)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2374)       
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.impl.CameraDeviceImpl.setRemoteDevice(CameraDeviceImpl.java:351)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:731)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:961)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:982)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:820)
[        ] W/MessageQueue( 3784):       at io.flutter.plugins.camera.Camera.open(Camera.java:315)
[        ] W/MessageQueue( 3784):       at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:96)
[        ] W/MessageQueue( 3784):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] W/MessageQueue( 3784):       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] W/MessageQueue( 3784):       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
[        ] W/MessageQueue( 3784):       at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)    
[        ] W/MessageQueue( 3784):       at android.os.Handler.handleCallback(Handler.java:938)
[        ] W/MessageQueue( 3784):       at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] W/MessageQueue( 3784):       at android.os.Looper.loopOnce(Looper.java:210)
[        ] W/MessageQueue( 3784):       at android.os.Looper.loop(Looper.java:299)
[        ] W/MessageQueue( 3784):       at android.app.ActivityThread.main(ActivityThread.java:8319)
[        ] W/MessageQueue( 3784):       at java.lang.reflect.Method.invoke(Native Method)
[        ] W/MessageQueue( 3784):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
[        ] W/MessageQueue( 3784):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
[        ] W/MessageQueue( 3784): Handler (android.os.Handler) {adf22d3} sending message to a Handler on a dead thread
[        ] W/MessageQueue( 3784): java.lang.IllegalStateException: Handler (android.os.Handler) {adf22d3} sending message to a Handler on a dead thread   
[        ] W/MessageQueue( 3784):       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:572)
[        ] W/MessageQueue( 3784):       at android.os.Handler.enqueueMessage(Handler.java:778)
[        ] W/MessageQueue( 3784):       at android.os.Handler.sendMessageAtTime(Handler.java:727)
[        ] W/MessageQueue( 3784):       at android.os.Handler.sendMessageDelayed(Handler.java:697)
[        ] W/MessageQueue( 3784):       at android.os.Handler.post(Handler.java:427)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2374)       
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.impl.CameraDeviceImpl.setRemoteDevice(CameraDeviceImpl.java:352)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:731)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:961)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:982)
[        ] W/MessageQueue( 3784):       at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:820)
[        ] W/MessageQueue( 3784):       at io.flutter.plugins.camera.Camera.open(Camera.java:315)
[        ] W/MessageQueue( 3784):       at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:96)
[        ] W/MessageQueue( 3784):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] W/MessageQueue( 3784):       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] W/MessageQueue( 3784):       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
[        ] W/MessageQueue( 3784):       at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)    
[        ] W/MessageQueue( 3784):       at android.os.Handler.handleCallback(Handler.java:938)
[        ] W/MessageQueue( 3784):       at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] W/MessageQueue( 3784):       at android.os.Looper.loopOnce(Looper.java:210)
[        ] W/MessageQueue( 3784):       at android.os.Looper.loop(Looper.java:299)
[        ] W/MessageQueue( 3784):       at android.app.ActivityThread.main(ActivityThread.java:8319)
[        ] W/MessageQueue( 3784):       at java.lang.reflect.Method.invoke(Native Method)
[        ] W/MessageQueue( 3784):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
[        ] W/MessageQueue( 3784):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)


```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.2134], locale id-ID)
    • Flutter version 3.3.10 on channel stable at C:\flutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (8 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\MadMouse\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\MadMouse\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (4 available)
    • Redmi Note 9 Pro (mobile) • 1f36d0e4 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)         • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 115.0.5790.173
    • Edge (web)                • edge     • web-javascript • Microsoft Edge 115.0.1901.203


[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

 
my code followed this [link](https://github.com/flutter/flutter/issues/96140#issuecomment-1012146331) but still error.

**Comment by huycozy** [comment]
Hi @madmouse17 

In order to address the issue properly, please provide the detailed `Steps to reproduce` along with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. 

Also, please provide the entire output of `flutter run -v` which may contain the stack trace of crash. The crash log should be in text format instead of a screenshot for better readability. Thanks!

**Comment by madmouse17** [comment]
please check my code and my log I have updated
thanks.

**Comment by madmouse17** [comment]
camera is run but i found error another


<details><summary>Details</summary>
<p>

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
E/flutter ( 1701): 	at io.flutter.plugins.camera.Camera.startCapture(Camera.java:549)
E/flutter ( 1701): 	at io.flutter.plugins.camera.Camera.startPreviewWithImageStream(Camera.java:1139)
E/flutter ( 1701): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:258)
E/flutter ( 1701): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 1701): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 1701): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/flutter ( 1701): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter ( 1701): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 1701): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 1701): 	at android.os.Looper.loopOnce(Looper.java:210)
E/flutter ( 1701): 	at android.os.Looper.loop(Looper.java:299)
E/flutter ( 1701): 	at android.app.ActivityThread.main(ActivityThread.java:8319)
E/flutter ( 1701): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 1701): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter ( 1701): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
E/flutter ( 1701): )

</p>
</details>

**Comment by huycozy** [comment]
Thanks for the update. Based on your error stack trace, this is similar to a known issue being tracked at https://github.com/flutter/flutter/issues/97076. Closing this issue as a duplicate, so please follow up on it for further updates.
