### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: Dosya adı, dizin adı veya birim etiketi sözdizimi hatalı., errno = 123

### ISSUE THREAD

**Issue by mustafayaylali** [flutter/flutter#133055]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: Dosya adı, dizin adı veya birim etiketi sözdizimi hatalı.
, errno = 123
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:240:85)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:f

**Comment by christopherfujino** [comment]
This is the number 2 most common crasher on the new stable/3.13.0 release.

**Comment by christopherfujino** [comment]
https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/lib/src/android/android_studio.dart#L240
