### ISSUE TITLE
An InputDecorator, which is typically created by a TextField, cannot have an unbounded width.

### ISSUE THREAD

**Issue by RubenGarcia** [flutter/flutter#133042]
Flutter indicated I should create a bug report with the following information:

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
An InputDecorator, which is typically created by a TextField, cannot have an unbounded width.
This happens when the parent widget does not provide a finite width constraint. For example, if the InputDecorator is contained by a Row, then its width must be constrained. An Expanded widget or a SizedBox can be used to constrain the width of the InputDecorator or the TextField that contains it.
'package:flutter/src/material/input_decorator.dart':
Failed assertion: line 938 pos 7: 'layoutConstraints.maxWidth < double.infinity'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  TextFormField TextFormField:file:///C:/tmp/sdip-test-apps/off_board/lib/view/screens/service_screen.dart:251:9
When the exception was thrown, this was the stack: 
#2      _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:938:7)
#3      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1350:44)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#8      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#14     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#17     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#18     RenderTapRegion.layout (package:flutter/src/widgets/tap_region.dart:519:11)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#21     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#22     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#23     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#24     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#27     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#28     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#29     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#31     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#34     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#35     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:297:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#37     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#40     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#43     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#44     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#45     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#46     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#49     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#50     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056:7)
#51     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
#52     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#54     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#57     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#59     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#61     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#64     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#67     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#70     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#73     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#76     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#78     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3751:13)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#80     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#83     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#84     _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:832:15)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#86     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#89     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#92     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#95     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#98     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#101    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#103    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#104    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#107    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#110    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#112    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2234:7)
#113    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1016:18)
#114    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:492:19)
#115    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#116    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#117    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#118    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#119    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#120    _invoke (dart:ui/hooks.dart:142:13)
#121    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#122    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: _RenderDecoration#900b5 relayoutBoundary=up13 NEEDS-LAYOUT NEEDS-PAINT 

NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(unconstrained)
...  size: MISSING
RenderObject: _RenderDecoration#900b5 relayoutBoundary=up13 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(unconstrained)
  size: MISSING
...  input: RenderRepaintBoundary#b2d4e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0)
...    constraints: MISSING
...    size: MISSING
...    usefulness ratio: no metrics collected yet (never painted)
...    child: _RenderCompositionCallback#18a42 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      child: RenderTapRegion#13a90 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        behavior: deferToChild
...        debugLabel: EditableText
...        groupId: EditableText
...        child: RenderMouseRegion#8ab35 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          behavior: opaque
...          listeners: <none>
...  helperError: RenderConstrainedBox#5ba5b NEEDS-LAYOUT NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0)
...    constraints: MISSING
...    size: MISSING
...    additionalConstraints: BoxConstraints(w=0.0, h=0.0)
...  container: RenderCustomPaint#d4601 NEEDS-LAYOUT NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0)
...    constraints: MISSING
...    size: MISSING
...    painter: null
...    foregroundPainter: _InputBorderPainter#db17d
====================================================================================================

======== Exception caught by rendering library =====================================================

The following assertion was thrown during performLayout():
RenderBox was not laid out: _RenderDecoration#900b5 relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1966 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

**Comment by RubenGarcia** [comment]
I was missing these lines in my TextFormField widget
```
                                  decoration: const InputDecoration(
                                    border: InputBorder.none,
                                    labelText: 'Iterations',
                                  ),
```
