### ISSUE TITLE
HardwareKeyboard error while pressing key and launching on Linux

### ISSUE THREAD

**Issue by WatchDogsDev** [flutter/flutter#133332]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a flutter project
1. Start a flutter desktop app on Linux (Ubuntu 22.04)
2. Press any buttons before window appears
3. The error is given

### Expected results

This should not happen or at least error should be ignored.

### Actual results

```console
Launching lib/main.dart on Linux in debug mode...
main.dart:1
(mind_games:73506): Gdk-CRITICAL **: 19:46:59.860: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
** (mind_games:73506): WARNING **: 19:47:00.738: Unable to retrieve framework response: Message is not valid JSON
Connecting to VM Service at ws://127.0.0.1:45713/HAj1z7li30I=/ws
** (mind_games:73506): WARNING **: 19:47:01.545: Unable to retrieve framework response: Message is not valid JSON

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0ae64(physicalKey: PhysicalKeyboardKey#e6f4b(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:59:24.035000)
'package:flutter/src/services/hardware_keyboard.dart':
hardware_keyboard.dart:1
Failed assertion: line 471 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
hardware_keyboard.dart:471
#3      HardwareKeyboard._assertEventIsRegular
hardware_keyboard.dart:482
#4      HardwareKeyboard.handleKeyEvent
hardware_keyboard.dart:601
#5      KeyEventManager.handleRawKeyMessage
hardware_keyboard.dart:1021
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
platform_channel.dart:212
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
binding.dart:567
#8      _invoke2 (dart:ui/hooks.dart:202:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:228:31)
(elided 4 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
```

### Code sample

Just create a simple flutter project

### Logs

```console
Launching lib/main.dart on Linux in debug mode...
main.dart:1
(mind_games:73506): Gdk-CRITICAL **: 19:46:59.860: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
** (mind_games:73506): WARNING **: 19:47:00.738: Unable to retrieve framework response: Message is not valid JSON
Connecting to VM Service at ws://127.0.0.1:45713/HAj1z7li30I=/ws
** (mind_games:73506): WARNING **: 19:47:01.545: Unable to retrieve framework response: Message is not valid JSON

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0ae64(physicalKey: PhysicalKeyboardKey#e6f4b(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:59:24.035000)
'package:flutter/src/services/hardware_keyboard.dart':
hardware_keyboard.dart:1
Failed assertion: line 471 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
hardware_keyboard.dart:471
#3      HardwareKeyboard._assertEventIsRegular
hardware_keyboard.dart:482
#4      HardwareKeyboard.handleKeyEvent
hardware_keyboard.dart:601
#5      KeyEventManager.handleRawKeyMessage
hardware_keyboard.dart:1021
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
platform_channel.dart:212
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
binding.dart:567
#8      _invoke2 (dart:ui/hooks.dart:202:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:228:31)
(elided 4 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
```

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on Ubuntu 22.04.3 LTS 6.2.0-26-generic, locale en_US.UTF-8)
    • Flutter version 3.13.0 on channel stable at /dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (10 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /AndroidSDK
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.2)
    • Android Studio at /Desktop/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.70.0
    ✗ Unable to determine VS Code version.

[✓] VS Code (version 1.67.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-26-generic
    • Chrome (web)    • chrome • web-javascript • Chromium 116.0.5845.110 snap

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by bleroux** [comment]
FYI, I can reproduce this issue on master (it is easier to reproduce during a hot restart but it also happen during startup). It is already tracked in https://github.com/flutter/flutter/issues/125975.

**Comment by huycozy** [comment]
Thanks for linking the issue, Bruno. Marking this issue as a duplicate of https://github.com/flutter/flutter/issues/125975
