### ISSUE TITLE
floatingActionButton is not displayed after pop() of a page created by a pageBuilder in pushReplacement with reverseTransitionDuration set to 1

### ISSUE THREAD

**Issue by tanguy-penfen** [flutter/flutter#133324]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Have a page with a `floatingActionButton`
2. Push a second page
3. Pushreplace a new page with `floatingActionButton: null` using a pageBuilder with `reverseTransitionDuration: const Duration(milliseconds: 0)`
4. Pop this new page

### Expected results

The first page should be correctly displayed including the floatingActionButton

### Actual results

`floatingActionButton` won't show and trying to select it in the inspector will throw an exception

Note : Setting `reverseTransitionDuration: const Duration(milliseconds: 1)` will prevent this issue
Note2 : Popping a page directly won't have this issue (if the page was pushed with `push()` instead pf `pushReplacent()`

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
      
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _pushNewPage() {
   Navigator.push(
            context,
            PageRouteBuilder(
              pageBuilder: (context, animation1, animation2) => const SecondPage(title: 'second page'),
            ));
  }

  @override
  Widget build(BuildContext context) {
   
    return Scaffold(
      appBar: AppBar(
      
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
     
        title: Text(widget.title),
      ),
      body: const Center(
      
        child: Column(
       
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'In home page',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _pushNewPage,
        tooltip: 'push new',
        child: const Icon(Icons.skip_next),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class SecondPage extends StatefulWidget {
  const SecondPage({super.key, required this.title});

  final String title;

  @override
  State<SecondPage> createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {

  void _pushNewPage() {
   Navigator.pushReplacement(
            context,
            PageRouteBuilder(
              pageBuilder: (context, animation1, animation2) => const NewPage(title: 'New Page'),
              reverseTransitionDuration: const Duration(milliseconds: 0),
            ));
  }

  @override
  Widget build(BuildContext context) {
   
    return Scaffold(
      appBar: AppBar(
      
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
     
        title: Text(widget.title),
      ),
      body: const Center(
      
        child: Column(
       
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'In  second page',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _pushNewPage,
        tooltip: 'push new',
        child: const Icon(Icons.skip_next),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class NewPage extends StatefulWidget {
  const NewPage({super.key, required this.title});
  final String title;

  @override
  State<NewPage> createState() => _NewPageState();
}

class _NewPageState extends State<NewPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
      
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
       
        title: Text(widget.title),
      ),
      body: const Center(
       
        child: Column(
          
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'NewPage',
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [version 10.0.19045.3324], locale fr-FR)
    • Flutter version 3.13.0 on channel stable at C:\Users\Ciblelec\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (9 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Ciblelec\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\Ciblelec\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (4 available)
    • RMX3085 (mobile)  • BEBM9LCELRW8EMSG • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [version 10.0.19045.3324]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 115.0.1901.203

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @tanguy-penfen. Thanks for filing this issue. I'm able to reproduce this issue on the latest `master` and `stable` channels. This seems to be peculiar to using `PageBuilder` with `pushReplacement` and adding `reverseTransitionDuration: const Duration(milliseconds: 1)` would not reproduce the issue. Using `MaterialPageRoute` doesn't reproduce this issue.

https://github.com/flutter/flutter/assets/53122008/f6e21d8d-4121-45d3-bb8a-2864153ed2e9


<details><summary>Logs when checking from Widget Inspector</summary>
<p>

```
#3568   _ElementDiagnosticableTreeNode.toJsonMap
framework.dart:5052
#3569   WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
widget_inspector.dart:2089
#3570   InspectorSerializationDelegate.additionalNodeProperties
widget_inspector.dart:3647
#3571   DiagnosticsNode.toJsonMap.<anonymous closure>
diagnostics.dart:1635
#3572   DiagnosticsNode.toJsonMap
diagnostics.dart:1650
#3573   _ElementDiagnosticableTreeNode.toJsonMap
framework.dart:5052
#3574   WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
widget_inspector.dart:2089
#3575   InspectorSerializationDelegate.additionalNodeProperties
widget_inspector.dart:3647
#3576   DiagnosticsNode.toJsonMap.<anonymous closure>
diagnostics.dart:1635
#3577   DiagnosticsNode.toJsonMap
diagnostics.dart:1650
#3578   _ElementDiagnosticableTreeNode.toJsonMap
framework.dart:5052
#3579   WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
widget_inspector.dart:2089
#3580   InspectorSerializationDelegate.additionalNodeProperties
widget_inspector.dart:3647
#3581   DiagnosticsNode.toJsonMap.<anonymous closure>
diagnostics.dart:1635
#3582   DiagnosticsNode.toJsonMap
diagnostics.dart:1650
#3583   _ElementDiagnosticableTreeNode.toJsonMap
framework.dart:5052
#3584   DiagnosticsNode.toJsonList.<anonymous closure>
diagnostics.dart:1675
#3585   MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3586   ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#3587   new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#3588   new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#3589   new List.of (dart:core-patch/array_patch.dart:47:28)
#3590   ListIterable.toList (dart:_internal/iterable.dart:214:7)
#3591   DiagnosticsNode.toJsonList
diagnostics.dart:1676
#3592   DiagnosticsNode.toJsonMap.<anonymous closure>
diagnostics.dart:1643
#3593   DiagnosticsNode.toJsonMap
diagnostics.dart:1650
#3594   _ElementDiagnosticableTreeNode.toJsonMap
framework.dart:5052
#3595   WidgetInspectorService._nodeToJson
widget_inspector.dart:1676
#3596   WidgetInspectorService._getLayoutExplorerNode
widget_inspector.dart:2061
#3597   BindingBase.registerServiceExtension.<anonymous closure>
binding.dart:958
#3607   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 10 frames from class _AssertionError, class _Timer, dart:async, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════

``` 

</p>
</details> 

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.1 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (2 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 8 (mobile)           • 218697C0-911E-4F4E-9568-C387ACB184ED • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile)          • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.14.0-9.0.pre.89, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.14.0-9.0.pre.89 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3c1dd2f9fa (6 hours ago), 2023-08-25 03:05:27 -0400
    • Engine revision 0f8962208a
    • Dart version 3.2.0 (build 3.2.0-97.0.dev)
    • DevTools version 2.26.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 8 (mobile)           • 218697C0-911E-4F4E-9568-C387ACB184ED • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile)          • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by TahaTesser** [comment]
This seems to be an issue with the `Hero` widget.

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('HomePage'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            const Hero(
              tag: 'test',
              child: Card(
                child: SizedBox(
                  width: 200,
                  height: 100,
                  child: Center(
                    child: Text('Card with Hero widget'),
                  ),
                ),
              ),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  PageRouteBuilder(
                    pageBuilder: (context, animation1, animation2) {
                      return const SecondPage();
                    },
                  ),
                );
              },
              child: const Text('Go to a page created with push'),
            ),
          ],
        ),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SecondPage'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            const Hero(
              tag: 'test',
              child: Card(
                child: SizedBox(
                  width: 200,
                  height: 100,
                  child: Center(
                    child: Text('Card with Hero widget'),
                  ),
                ),
              ),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.pushReplacement(
                  context,
                  PageRouteBuilder(
                    pageBuilder: (context, animation1, animation2) {
                      return Scaffold(
                        appBar: AppBar(
                          title:
                              const Text('Page created with pushReplacement'),
                        ),
                        body: const Center(child: Text('Click back button to go the home page'),),
                      );
                    },
                    reverseTransitionDuration: const Duration(milliseconds: 0),
                  ),
                );
              },
              child: const Text('Go to a page created with pushReplacement'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

Here I can reproduce using Hero with `pushReplacement` and `reverseTransitionDuration` set to zero.

https://github.com/flutter/flutter/assets/48603081/f08d8b2a-ba24-48b3-865e-ca17d64f02e6
