### ISSUE TITLE
[google_sign_in] [web] initWithParams asserts should be runtime if/throw checks

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#133403]
### Problem

The following is the definition of [`GoogleSignInPlugin#initWithParams()`](https://github.com/flutter/packages/blob/c80df448549228a631bb4936fec1fc0f56979218/packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart#L140C1-L172C1) for the web:

```dart
  @override
  Future<void> initWithParams(SignInInitParameters params) async {
    final String? appClientId = params.clientId ?? autoDetectedClientId;
    assert(
        appClientId != null,
        'ClientID not set. Either set it on a '
        '<meta name="google-signin-client_id" content="CLIENT_ID" /> tag,'
        ' or pass clientId when initializing GoogleSignIn');

    assert(params.serverClientId == null,
        'serverClientId is not supported on Web.');

    assert(
        !params.scopes.any((String scope) => scope.contains(' ')),
        "OAuth 2.0 Scopes for Google APIs can't contain spaces. "
        'Check https://developers.google.com/identity/protocols/googlescopes '
        'for a list of valid OAuth 2.0 scopes.');

    _initCalled = Completer<void>();

    await _jsSdkLoadedFuture;

    _gisSdkClient ??= GisSdkClient(
      clientId: appClientId!,
      hostedDomain: params.hostedDomain,
      initialScopes: List<String>.from(params.scopes),
      userDataController: _userDataController,
      loggingEnabled: kDebugMode,
    );

    _initCalled!.complete(); // Signal that `init` is fully done.
  }
```

When compiled for web (JS/canvaskit) using `--dart2js-optimization=O1`, the following JavaScript code is produced.

```javascript
    initWithParams$1(params) {
      var $async$goto = 0,
        $async$completer = A._makeAsyncAwaitCompleter(type$.void),
        $async$self = this, t2, t3, t4, idConfig, t5, t6, tokenConfig, t1;
      var $async$initWithParams$1 = A._wrapJsFunctionForAsync(function($async$errorCode, $async$result) {
        if ($async$errorCode === 1)
          return A._asyncRethrow($async$result, $async$completer);
        while (true)
          switch ($async$goto) {
            case 0:
              // Function start
              t1 = $async$self.__GoogleSignInPlugin_autoDetectedClientId_A;
              t1 === $ && A.throwLateFieldNI("autoDetectedClientId");
              $async$self._initCalled = new A._AsyncCompleter(new A._Future($.Zone__current, type$._Future_void), type$._AsyncCompleter_void);
              t2 = $async$self.__GoogleSignInPlugin__jsSdkLoadedFuture_A;
              t2 === $ && A.throwLateFieldNI("_jsSdkLoadedFuture");
              $async$goto = 2;
              return A._asyncAwait(t2, $async$initWithParams$1);
            case 2:
              // returning from await.
              if ($async$self._gisSdkClient == null) {
                t1.toString;
                t2 = new A.GisSdkClient(false, A.List_List$from(params.scopes, true, type$.String), $async$self._userDataController);
                t2._configureStreams$0();
                t3 = type$.void_Function_JavaScriptObject;
                t4 = type$.JavaScriptObject;
                idConfig = t4._as({client_id: t1, auto_select: true, callback: A.allowInterop(t3._as(t2.get$_onCredentialResponse()), t3), cancel_on_tap_outside: false});
                self.google.accounts.id.initialize(idConfig);
                t5 = type$.void_Function_nullable_Object;
                t6 = t5._as(t2.get$_onTokenError());
                tokenConfig = t4._as({client_id: t1, callback: A.allowInterop(t3._as(t2.get$_onTokenResponse()), t3), scope: " ", error_callback: A.allowInterop(t6, t5), hosted_domain: params.hostedDomain});
                t2.__GisSdkClient__tokenClient_A = t4._as(self.google.accounts.oauth2.initTokenClient(tokenConfig));
                $async$self._gisSdkClient = t2;
              }
              $async$self._initCalled.complete$0(0);
              // implicit return
              return A._asyncReturn(null, $async$completer);
          }
      });
      return A._asyncStartSync($async$initWithParams$1, $async$completer);
    },
```

On the line that reads `t1.toString`, in https://tvolkert.dev/photos/, if you hit the right arrow twice, it runs this code, and `t1` is null, which is causing an NPE to be thrown.  The error is pretty opaque:

```
Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at main.dart.js:75420:20
    at _wrapJsFunctionForAsync_closure.$protected (main.dart.js:8882:15)
    at _wrapJsFunctionForAsync_closure.call$2 (main.dart.js:40329:12)
    at _awaitOnObject_closure.call$1 (main.dart.js:40317:32)
    at _RootZone.runUnary$2$2 (main.dart.js:42009:18)
    at _Future__propagateToListeners_handleValueCallback.call$0 (main.dart.js:41057:51)
    at Object._Future__propagateToListeners (main.dart.js:9069:93)
    at _Future__addListener_closure.call$0 (main.dart.js:40952:9)
    at Object._microtaskLoop (main.dart.js:9135:24)
    at StaticClosure._startMicrotaskLoop (main.dart.js:9141:11)
```

I wonder if this is the `assert(appClientId != null)` being hit?  If so, why isn't the associated "ClientID not set...." message showing up as well?

Note that with the default optimization level (`--dart2js-optimization=O4`), the error is even more inscrutible:

```
Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at main.dart.js:36475:24
    at R4.a (main.dart.js:4152:62)
    at R4.$2 (main.dart.js:20377:14)
    at Qq.$1 (main.dart.js:20371:21)
    at PD.L3 (main.dart.js:21062:31)
    at PD.pz (main.dart.js:21064:21)
    at OB.$0 (main.dart.js:20672:11)
    at Object.kB (main.dart.js:4241:39)
    at Os.$0 (main.dart.js:20621:8)
    at Object.a6X (main.dart.js:4273:5)
```

### Version

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.12.0-14.0.pre.26, on macOS 13.5 22G74 darwin-arm64, locale en)
    • Flutter version 3.12.0-14.0.pre.26 on channel main at /Users/tvolkert/project/flutter/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision aa5f4a28e9 (8 weeks ago), 2023-06-30 18:16:21 -0700
    • Engine revision e6b8292705
    • Dart version 3.1.0 (build 3.1.0-262.0.dev)
    • DevTools version 2.25.0
```

`google_sign_in_web` version is "0.12.0+3"

**Comment by yjbanov** [comment]
This is expected behavior. Assertions are disabled in profile and release modes (this matches all platforms). The program keeps on trucking until it hits the expression `appClientId!` and fails the null assertion.

One thing that's unique to web is that, it turns out, the most efficient way to assert null (which in JS can also be `undefined`) is to attempt to dereference a method on the object. dart2js uses the `nullableObject.toString` expression to do that. That's why you see the `t1.toString` in the output (the reason the variable becomes `t1` is likely because [SSA](https://en.wikipedia.org/wiki/Static_single-assignment_form) ends up reusing variables to reduce code size).

Do you think we can improve this somehow? Or can we close it?

**Comment by tvolkert** [comment]
Ah, duh :-)

This can be closed.
