### ISSUE TITLE
When I return to the page of the root controller from a page, pull down to refresh and report an error

### ISSUE THREAD

**Issue by shengbin1998** [flutter/flutter#133553]
```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 701 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:701:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:450:51)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:450:7)
#6      DragGestureRecognizer._addPointer (package:flutter/src/gestures/monodrag.dart:277:7)
#7      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:289:5)
#8      GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:160:7)
#9      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1498:18)
#10     RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:3168:29)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#17     _invoke1 (dart:ui/hooks.dart:164:13)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
Handler: "onDown"
Recognizer: VerticalDragGestureRecognizer#042dd
  start behavior: start
====================================================================================================
```

**Comment by darshankawar** [comment]
@shengbin1998 
Can you provide us a [runnable but minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with `flutter doctor -v` that throws the reported error ?

**Comment by shengbin1998** [comment]
Sorry, I checked for a long time and found that although an error was reported in the refresh component, it was actually caused by the destruction of my child controller due to Get
