### ISSUE TITLE
Trying to read .page from PageController crashes

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13367]
During the build() that lays out the PageView that hosts a PageController, reading PageController.page crashes with an obscure ish error:
```
I/flutter (18335): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18335): The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#054ca):
I/flutter (18335): ScrollController not attached to any scroll views.
I/flutter (18335): 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 109 pos 12:
I/flutter (18335): '_positions.isNotEmpty'
I/flutter (18335):
I/flutter (18335): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18335): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18335): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18335):   https://github.com/flutter/flutter/issues/new
I/flutter (18335):
I/flutter (18335): When the exception was thrown, this was the stack:
I/flutter (18335): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:109:12)
I/flutter (18335): #3      PageController.page (package:flutter/src/widgets/page_view.dart:80:41)
```

Though semantically, it seems mostly adequate. Since there's an initial page set. Maybe it needs some special pre-attach handling.

**Comment by xster** [comment]
I suspect the original reason why it throws is semantically, it's difficult to say what the return value should be if the PageController became attached to a PageView, got detached and .page was called.
