### ISSUE TITLE
[devtools] Integration tests do not run with Chrome driver for chrome 116.0.5845.110

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#133617]
I am forced to use Chrome 116.0.5845.110 by company policy.

There is [no chrome driver](https://chromedriver.chromium.org/downloads) for 116 published.
I downloaded 116.0.5845.96 from [chrome for testing](https://googlechromelabs.github.io/chrome-for-testing/)

But it gives me error:

```
dart run integration_test/run_tests.dart --target=integration_test/test/live_connection/eval_and_browse_test.dart
Unhandled exception:
LateInitializationError: Field '_process@19135828' has not been initialized.
#0      ChromeDriver._process (file:///Users/polinach/_/devtools/packages/devtools_app/integration_test/test_infra/run/_chrome_driver.dart)
#1      ChromeDriver.stop (file:///Users/polinach/_/devtools/packages/devtools_app/integration_test/test_infra/run/_chrome_driver.dart:35:26)
<asynchronous suspension>
#2      main (file:///Users/polinach/_/devtools/packages/devtools_app/integration_test/run_tests.dart:58:5)
<asynchronous suspension>
```

Steps to repro:
1. Install 116.0.5845.96 from [chrome for testing](https://googlechromelabs.github.io/chrome-for-testing/) 
2. Clone [devtools](https://github.com/flutter/devtools)
3. Run `tool/refresh.sh`
4. cd packages/devtools_app
5. Run `dart run integration_test/run_tests.dart --target=integration_test/test/live_connection/eval_and_browse_test.dart`

Is there workaround I can use to debug integration tests for web on my mac?

**Comment by danagbemava-nc** [comment]
Reproducible using the steps outlined above. 

Labeling for further insight. 

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel master, 3.14.0-12.0.pre.107, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-12.0.pre.107 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 56ea352cc0 (10 hours ago), 2023-08-29 21:00:10 -0700
    • Engine revision 69f04bdfe9
    • Dart version 3.2.0 (build 3.2.0-122.0.dev)
    • DevTools version 2.26.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 16.6 20G75
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by yjbanov** [comment]
Is this the correct repo for this issue? The stack trace points to code in devtools. I realize we may need to make some changes in Flutter to accommodate the change to "Chrome for testing", but that would be done in the Flutter tool, some of our test scripts and/or packages, which won't fix the crash that happens in the devtool.

**Comment by polina-c** [comment]
> Is this the correct repo for this issue? The stack trace points to code in devtools. I realize we may need to make some changes in Flutter to accommodate the change to "Chrome for testing", but that would be done in the Flutter tool, some of our test scripts and/or packages, which won't fix the crash that happens in the devtool.

Thanks. I think I can get more details of the failure.
Here is the Flutter code that should initialize the variable:

```
_process = await Process.start(
        'chromedriver',
        [
          '--port=4444',
        ],
      );
```
I will experiment more to figure out what is going on.

**Comment by polina-c** [comment]
The issue was cause by combination of error reporting issue and changed name of 'zip in chrome for testing'.
