### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: Operation not supported, errno = 45

### ISSUE THREAD

**Issue by lalayiersan** [flutter/flutter#133626]
## command

flutter build ipa

## exception

FileSystemException: FileSystemException: Deletion failed, path = '/var/folders/m5/nxzhvd1s199d5611z8_77gyc0000gn/T/flutter_tools.YVIJ2W/flutter_ios_build_temp_dirdeDj4Y' (OS Error: Operation not supported, errno = 45)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:193:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:431:13)
<asynchronous suspension>
#4      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:650:37)
<asynchronous suspension>
#5      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:417:50)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.13.1, on macOS 13.2.1 22D68 darwin-x64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.13.1 on channel stable at /Users/apple/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision e1e47221e8 (7 days ago), 2023-08-22 21:43:18 -0700
    [32m•[39m Engine revision b20183e040
    [32m•[39m Dart version 3.1.0
    [32m•[39m DevTools version 2.25.0
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /Users/apple/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14C18
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2023.1.3)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 74.0.4
    [32m•[39m Dart plugin version 231.9161.14

[32m[✓][39m VS Code (version 1.81.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.70.0

[33m[!][39m Proxy Configuration
    [32m•[39m HTTP_PROXY is set
    [33m![39m NO_PROXY is not set

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.110

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.
```

**Comment by lalayiersan** [comment]
I modified the operation permissions for file '/var/folders/m5/nxzhvd1s199d5611z8_77gyc0000gn/T' use command 'chmod', but it still doesn't work

**Comment by dam-ease** [comment]
Hi @lalayiersan. I can see similar logs in https://github.com/flutter/flutter/issues/31111. Can you try the suggested solutions if it works in your case?

**Comment by lalayiersan** [comment]
> Hi @lalayiersan. I can see similar logs in #31111. Can you try the suggested solutions if it works in your case?

Sorry, I tried , but i don't know where to execute the code: https://github.com/flutter/flutter/issues/31111#issuecomment-500875465

**Comment by dam-ease** [comment]
Hi @lalayiersan. Thanks for your response. You can do this at the entry point of your application to see if it works
