### ISSUE TITLE
Using Future.wait and rootBundle.load in tests returns an empty list

### ISSUE THREAD

**Issue by Robbendebiene** [flutter/flutter#133751]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a new flutter project with 2 dummy asset files (`assets/asset01` & `assets/asset02`) and run the attached tests.

### Expected results

All tests should pass (the returned list should not be empty), or an exception should be thrown if `rootBundle` cannot be used this way in tests.

### Actual results

The first 2 tests fail, because the list returned by `Future.wait` is empty. I would have never expected that `Future.wait` can return a `List` of a different length then the supplied `Future` count.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Test with Future.wait', (WidgetTester tester) async {
    TestWidgetsFlutterBinding.ensureInitialized();

    final a = await Future.wait([
      rootBundle.load('assets/asset01'),
      rootBundle.load('assets/asset02'),
    ]);

    expect(a, hasLength(2));
  });

  testWidgets('Test with Future.wait and runAsync', (WidgetTester tester) async {
    TestWidgetsFlutterBinding.ensureInitialized();

    final a = await tester.runAsync(() => Future.wait([
      rootBundle.load('assets/asset01'),
      rootBundle.load('assets/asset02'),
    ]));

    expect(a, hasLength(2));
  });

  testWidgets('Test without Future.wait', (WidgetTester tester) async {
    TestWidgetsFlutterBinding.ensureInitialized();

    final a = [
      await rootBundle.load('assets/asset01'),
      await rootBundle.load('assets/asset02'),
    ];

    expect(a, hasLength(2));
  });
}

```

</details>

### Logs

<details><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: an object with length of <2>
  Actual: []
   Which: has length of <0>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/robin/Projekte/OpenStop/test/widget_test.dart:13:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/robin/Projekte/OpenStop/test/widget_test.dart line 13
The test description was:
  Test with Future.wait
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: Test with Future.wait

✖ Test with Future.wait
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: an object with length of <2>
  Actual: []
   Which: has length of <0>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/robin/Projekte/OpenStop/test/widget_test.dart:25:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/robin/Projekte/OpenStop/test/widget_test.dart line 25
The test description was:
  Test with Future.wait and runAsync
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: Test with Future.wait and runAsync

✖ Test with Future.wait and runAsync
✓ Test without Future.wait
Exited (1)

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on Fedora Linux 38 (Workstation Edition) 6.4.11-200.fc38.x86_64, locale de_DE.UTF-8)
    • Flutter version 3.10.5 on channel stable at /home/robin/Toolkits/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (vor 3 Monaten), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/robin/Toolkits/android
    • Platform android-33, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/robin/Toolkits/android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (Red_Hat-11.0.20.0.8-1.fc38) (build 11.0.20+8)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/lib64/chromium-browser/chromium-browser

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-2.fc38)
    • cmake version 3.27.3
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.4.11-200.fc38.x86_64
    • Chrome (web)    • chrome • web-javascript • Chromium 116.0.5845.96 Fedora Project

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate this using latest stable and master version wherein, it throws same console error log as described.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.13.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.2 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (7 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.14.0-13.0.pre.27, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.14.0-13.0.pre.27 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dd51bf0970 (18 minutes ago), 2023-08-31 00:58:35 -0400
    • Engine revision e88b21b6d4
    • Dart version 3.2.0 (build 3.2.0-122.0.dev)
    • DevTools version 2.26.2
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by slaci** [comment]
Hello, I have ran into this also today. Seems like it is not possible to load assets in parallel in tests. `Future.wait` returns an unexpected empty list, but when trying `[].wait` or `().wait` then it hangs forever. I'm currently on only flutter `3.16.7`.

For example this test fails:

```dart
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  testWidgets('returns both assets', (tester) async {
      final result = await Future.wait([
        rootBundle.load('assets/logo.png'),
        rootBundle.load('assets/other.png'),
      ]);
      expect(result, isNotEmpty);
  });
}
```

And this test hangs "forever" (well until test timeout):

```dart
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  testWidgets('returns both assets', (tester) async {
      final result = await [
        rootBundle.load('assets/logo.png'),
        rootBundle.load('assets/other.png'),
      ].wait;
      expect(result, isNotEmpty);
  });
}
```

Same with records:

```dart
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('returns both assets', (tester) async {
      final (first, second) = await (
        rootBundle.load('assets/logo.png'),
        rootBundle.load('assets/other.png'),
      ).wait;
      expect(first, isA<ByteData>());
      expect(second, isA<ByteData>());
  });
}
```

All of these work perfectly in a running flutter app.
