### ISSUE TITLE
Run process immediately exited when i run the app with 'flutter run' on iOS

### ISSUE THREAD

**Issue by MichaelAmadheo** [flutter/flutter#133829]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Do 'flutter run'
2. 'Xcode build done' and the app is opened on emulator
3. The running process on the terminal is immediately exited and i can't do anything like hot reload or hot refresh

### Actual results

This is only happening on my older project, it does not happen when i do it on a new project. when i do 'flutter run' the app is opened on the emulator, but if i look at the terminal, the running process is exited the same way like when you do a 'control + c' or 'ctrl c' on the terminal when flutter is running.

I can't explain much but by seeing the logs i provided i think you should understand what i mean by 'exited' immediately.

The sdk version of the project is  sdk: ">=2.17.6 <3.0.0", while the flutter version on my device is Flutter 3.10.6

### Logs

<details>
<summary>Logs</summary>

```console

Launching lib/main.dart on iPhone 14 in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         6.4s
Xcode build done.                                           18.8s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
S000-50105204s-MacBook-Pro:ios s000-50105204$ 

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @MichaelAmadheo. Thanks for filing this. Please can you try the following to see if issue still persists:

- I see you are on an older version of flutter, kindly upgrade to the latest versions
- What IDE are you currently running this in? Can you please check if this issue occurs when running the app from IntelliJ? Can you try running the app from the terminal or from vscode?

**Comment by MichaelAmadheo** [comment]
Hi @dam-ease sorry for my late response, i tried to upgrade environment in pubspec.yaml to sdk: '>=3.0.6 <4.0.0' and it still showing the same result. I have tried running using both terminal and vscode

**Comment by dam-ease** [comment]
Thanks for your response @MichaelAmadheo. Can you share the full output of your `flutter run -v`?

**Comment by MichaelAmadheo** [comment]
The full output is too long, but i notice that there's a red colored error near the end of the output when i run flutter run -v:

`
[ +607 ms] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
[  +86 ms] VM Service URL on device: http://127.0.0.1:59174/8z5muZ-vuZ4=/
[   +7 ms] "flutter run" took 53,986ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +129 ms] ensureAnalyticsSent: 115ms
[        ] Running 1 shutdown hook
[   +8 ms] Shutdown hooks complete
[        ] exiting with code 1
S000-50105204s-MacBook-Pro:gudo_inventory_app s000-50105204$ 
`
