### ISSUE TITLE
Unable to run flutter project in a multipass instance

### ISSUE THREAD

**Issue by git-elliot** [flutter/flutter#134014]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install Multipass and launch an instance.
2. Install flutter using snap.
3. Create sample flutter project (say example)
4. Run project 
    a. cd example
    b. flutter run

### Expected results

Should build or tell error specifically if I need to install something. 

### Actual results

```
Launching lib/main.dart on Linux in debug mode...
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Building Linux application...             
```
### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[   +8 ms] Could not interpret results of "git describe": 3.14.0-14.0.pre.93
[  +11 ms] Unable to locate an Android SDK.
[   +2 ms] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] aarch64
[  +70 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +97 ms] Skipping pub get: version match.
[ +133 ms] Generating /home/ubuntu/projects/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +45 ms] Initializing file store
[   +5 ms] Skipping target: gen_localizations
[   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated
contents: /home/ubuntu/projects/example/.dart_tool/package_config_subset}
[  +20 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[        ] complete
[   +2 ms] Launching lib/main.dart on Linux in debug mode...
[   +1 ms] /home/ubuntu/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/ubuntu/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/ubuntu/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/fbc6f4a54047e95abc0fef7077f27da9f8e55b77/ --output-dill
/tmp/flutter_tools.ACBAZV/flutter_tool.GOPELV/app.dill --packages /home/ubuntu/projects/example/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/0ae86c1787aeedab7d764223dd117bca.cache.dill.track.dill --verbosity=error
--enable-experiment=alternative-invalidation-strategy
[  +14 ms] Building Linux application...
[   +5 ms] <- compile package:example/main.dart
[   +1 ms] executing: [build/linux/arm64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-arm64
/home/ubuntu/projects/example/linux
[ +707 ms] -- Configuring done
[ +735 ms] -- Generating done
[   +6 ms] -- Build files have been written to: /home/ubuntu/projects/example/build/linux/arm64/debug
[   +4 ms] executing: ninja -C build/linux/arm64/debug install
[   +4 ms] ninja: Entering directory `build/linux/arm64/debug'
[+7239 ms] the Dart compiler exited unexpectedly.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:830:13)
           #2      _rootRun (dart:async/zone.dart:1391:47)
           #3      _CustomZone.run (dart:async/zone.dart:1301:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:141:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1391:47)
           #14     _CustomZone.run (dart:async/zone.dart:1301:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1391:47)
           #26     _CustomZone.run (dart:async/zone.dart:1301:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:640:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2452:21)
           #35     _rootRunUnary (dart:async/zone.dart:1415:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:658:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:606:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1941:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1370:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #48     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[  +26 ms] ensureAnalyticsSent: 7ms
[   +1 ms] Running 1 shutdown hook
[   +5 ms] Shutdown hooks complete
[        ] the Dart compiler exited unexpectedly.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:830:13)
           #2      _rootRun (dart:async/zone.dart:1391:47)
           #3      _CustomZone.run (dart:async/zone.dart:1301:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:141:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1391:47)
           #14     _CustomZone.run (dart:async/zone.dart:1301:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1391:47)
           #26     _CustomZone.run (dart:async/zone.dart:1301:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:640:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2452:21)
           #35     _rootRunUnary (dart:async/zone.dart:1415:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:658:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:606:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1941:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1370:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #48     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[   +6 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.93, on Ubuntu 22.04.3 LTS 5.15.0-82-generic, locale C.UTF-8)
    • Flutter version 3.14.0-14.0.pre.93 on channel master at /home/ubuntu/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef9befc9da (35 hours ago), 2023-09-03 11:23:20 -0700
    • Engine revision fbc6f4a540
    • Dart version 3.2.0 (build 3.2.0-131.0.dev)
    • DevTools version 2.27.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Ubuntu 22.04.3 LTS 5.15.0-82-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

**Comment by huycozy** [comment]
Hi @git-elliot 
I wonder if the issue also appears with Flutter installed manually (instead of snap)? Also, can you share your multipass instance info? (image/architecture/etc)

**Comment by git-elliot** [comment]
```
Name:           primary
State:          Running
IPv4:           192.168.64.6
Release:        Ubuntu 22.04.3 LTS
Image hash:     41a8587b4994 (Ubuntu 22.04 LTS)
CPU(s):         1
Load:           0.21 0.09 0.03
Disk usage:     2.6GiB out of 4.8GiB
Memory usage:   149.6MiB out of 962.4MiB
Mounts:         /Users/home => Home
                    UID map: 501:default
                    GID map: 20:default
```

**Comment by git-elliot** [comment]
I increased the specifications of the instance and now it's working. I'm putting my specifications here in case someone comes across the same issue in future. 
```
Name:           primary
State:          Running
IPv4:           192.168.64.6
Release:        Ubuntu 22.04.3 LTS
Image hash:     41a8587b4994 (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.20 0.17 0.07
Disk usage:     2.7GiB out of 9.6GiB
Memory usage:   161.2MiB out of 3.8GiB
Mounts:         /Users/home => Home
                    UID map: 501:default
                    GID map: 20:default
```
