### ISSUE TITLE
http_disallow_http_connections_test engine test fails with Xcode 15

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#134079]
Engine tests for `http_disallow_http_connections_test` fail on host_debug, host_profile, host_release, host_debug_unopt

```
Running command "/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/flutter_tester --force-multithreading --disable-observatory --use-test-fonts --icu-data-file-path=/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/icudtl.dat --flutter-assets-dir=/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/flutter/lib/ui/assets --disable-asset-fonts /opt/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/path_test.dart.dill"
2023-08-18 08:18:59.645 flutter_tester[53518:361658] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}
2023-08-18 08:18:59.645 flutter_tester[53518:361658] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
2023-08-18 08:18:59.645 flutter_tester[53518:361658] XType: unable to make a connection to the font daemon!
2023-08-18 08:18:59.645 flutter_tester[53518:361658] XType: XTFontStaticRegistry is enabled as fontd is not available.
Test "Scene.toImageSync succeeds": Started
Test "Scene.toImageSync succeeds": Started
unittest-suite-wait-for-done
[ERROR:flutter/shell/testing/tester_main.cc(429)] Unhandled exception
Exception: SocketException: Failed host lookup: 'flutter-devicelab-mac-45.mtv.corp.google.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
Stack trace: #0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:520:9)
#1      _rootRunUnary (dart:async/zone.dart:1407:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#3      _NativeSocket._resolveHost (dart:io-patch/socket_patch.dart:1000:20)
<asynchronous suspension>
#4      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1014:21)
<asynchronous suspension>
#5      _RawServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:1810:15)
<asynchronous suspension>
#6      _ServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2095:15)
<asynchronous suspension>
#7      _HttpServer.bind.<anonymous closure> (dart:_http/http_impl.dart:3184:27)
<asynchronous suspension>
#8      bindServerAndTest (file:///opt/s/w/ir/cache/builder/src/flutter/testing/dart/http_disallow_http_connections_test.dart:35:29)
<asynchronous suspension>
#9      main.<anonymous closure> (file:///opt/s/w/ir/cache/builder/src/flutter/testing/dart/http_disallow_http_connections_test.dart:73:5)
<asynchronous suspension>
#10     Test.run.<anonymous closure>.<anonymous closure> (package:litetest/src/test.dart:69:11)
<asynchronous suspension>
#11     Test.run.<anonymous closure> (package:litetest/src/test.dart:65:7)
<asynchronous suspension>
#12     test.<anonymous closure> (package:async_helper/async_minitest.dart:50:17)
<asynchronous suspension>
```

https://chromium-swarm.appspot.com/task?id=6421f96f92516c10
https://chromium-swarm.appspot.com/task?id=643ccbfb6dd98910
https://chromium-swarm.appspot.com/task?id=643ccc6f9b8fcf10
https://chromium-swarm.appspot.com/task?id=643ccccb64ecd110

Unsure if it's due to the bot I'm using or if it's actually specific to Xcode 15.

**Comment by vashworth** [comment]
Appears to be a problem with running the test on a devicelab bot. Passes on a chromium bot. Closing
