### ISSUE TITLE
Framework PRs blocked by failing customer test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#134043]
I suspect the tree will turn red soon, too.

One example is here: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20customer_testing/60502/overview

```
| 01:09 +2758 ~4 -1: /Volumes/Work/s/w/ir/x/t/flutter_customer_testing.super_editor.sex6rQ/tests/super_editor/test/super_textfield/super_textfield_ime_test.dart: SuperTextField with IME input source inserts line when NUMPAD ENTER is pressed in middle of text (on Windows)
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following assertion was thrown running a test:
| Key LogicalKeyboardKey#cb5bf(keyId: "0x20000020d", keyLabel: "Numpad Enter", debugName: "Numpad
| Enter") not found in windows keyCode map
| 'package:flutter_test/src/event_simulation.dart':
| Failed assertion: line 138 pos 14: 'keyCode != null'
|
| When the exception was thrown, this was the stack:
| #2      KeyEventSimulator._getKeyCode (package:flutter_test/src/event_simulation.dart:138:14)
| #3      KeyEventSimulator.getKeyData (package:flutter_test/src/event_simulation.dart:261:25)
| #4      KeyEventSimulator.simulateKeyDownEvent.simulateByRawEvent.<anonymous closure> (package:flutter_test/src/event_simulation.dart:735:16)
| #5      KeyEventSimulator._simulateKeyEventByRawEvent.<anonymous closure> (package:flutter_test/src/event_simulation.dart:657:65)
| #8      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
| #9      KeyEventSimulator._simulateKeyEventByRawEvent (package:flutter_test/src/event_simulation.dart:653:27)
| #10     KeyEventSimulator.simulateKeyDownEvent.simulateByRawEvent (package:flutter_test/src/event_simulation.dart:733:14)
| #11     KeyEventSimulator.simulateKeyDownEvent (package:flutter_test/src/event_simulation.dart:740:16)
| #12     simulateKeyDownEvent (package:flutter_test/src/event_simulation.dart:873:48)
| #13     WidgetController.sendKeyEvent (package:flutter_test/src/controller.dart:1460:32)
| #14     KeyboardInput.pressNumpadEnter (package:flutter_test_robots/src/keyboard.dart:80:11)
| #15     main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/t/flutter_customer_testing.super_editor.sex6rQ/tests/super_editor/test/super_textfield/super_textfield_ime_test.dart:341:24)
| <asynchronous suspension>
| #16     testWidgetsOnWindows.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/t/flutter_customer_testing.super_editor.sex6rQ/tests/super_editor/test/test_tools.dart:314:7)
| <asynchronous suspension>
| #17     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
| <asynchronous suspension>
| #18     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1012:5)
| <asynchronous suspension>
| <asynchronous suspension>
| (elided 5 frames from class _AssertionError, dart:async, and package:stack_trace)
|
| The test description was:
|   when NUMPAD ENTER is pressed in middle of text (on Windows)
| ════════════════════════════════════════════════════════════════════════════════════════════════════
```

cc @dnfield framework gardener
cc @matthew-carroll for super_textfield

**Comment by zanderso** [comment]
cc @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
PR to bump the super_editor version: https://github.com/flutter/tests/pull/294

**Comment by LongCatIsLooong** [comment]
customer tests are passing now. Closing.
