### ISSUE TITLE
This problem must be solved in the bloc please.

### ISSUE THREAD

**Issue by ERTIQA-SOFT** [flutter/flutter#134007]
```
======== Exception caught by widgets library =======================================================
The following StateError was thrown building InheritedProvider<AppCubit>:
Bad state: Tried to read a provider that threw during the creation of its value.
The exception occurred during the creation of type AppCubit.

══╡ EXCEPTION CAUGHT BY PROVIDER ╞═══════════════════════════════
The following LateError was thrown:
LateInitializationError: Field
'_currencySellFieldPining@59465044' has not been initialized.

When the exception was thrown, this was the stack:
#0      _currencySellFieldPining (package:eqmoney/helper/setting_helper.dart)
#1      SettingHelper.currency_sell_currency1 (package:eqmoney/helper/setting_helper.dart:842:12)
#2      new AppCubit (package:eqmoney/cubit/cubit.dart:1784:34)
#3      MyApp.build.<anonymous closure> (package:eqmoney/main.dart:177:16)
#4      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:736:36)
#5      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:590:33)
#6      Provider.of (package:provider/src/provider.dart:303:37)
#7      ReadContext.read (package:provider/src/provider.dart:649:21)
#8      _BlocListenerBaseState.initState (package:flutter_bloc/src/bloc_listener.dart:143:36)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5101:55)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
#11     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#18     _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#25     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#32     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#41     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#42     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#43     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
#44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#45     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
#46     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
#47     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
#51     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)
═════════════════════════════════════════════════════════════════

The relevant error-causing widget was: 
  InheritedProvider<AppCubit> InheritedProvider:file:///C:/Users/alaad/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_bloc-8.1.3/lib/src/bloc_provider.dart:126:11
When the exception was thrown, this was the stack: 
#0      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:709:7)
#1      _CreateInheritedProviderState.debugFillProperties (package:provider/src/inherited_provider.dart:806:44)
#2      _InheritedProviderScopeElement.debugFillProperties (package:provider/src/inherited_provider.dart:631:20)
#3      DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2958:17)
#4      DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2961:8)
#5      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2975:105)
#6      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1278:63)
#7      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1151:14)
#8      DiagnosticsNode.toStringDeep.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1816:9)
#9      DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:1823:6)
#10     DiagnosticsNode.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1734:18)
#11     DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:1746:6)
#12     Diagnosticable.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:3131:78)
#13     Diagnosticable.toString (package:flutter/src/foundation/diagnostics.dart:3133:6)
#14     _StringBase._interpolate (dart:core-patch/string_patch.dart:851:19)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4998:44)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
#19     _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#26     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#33     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#42     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#43     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#44     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
#45     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#46     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
#47     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
#48     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
#52     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
E/flutter ( 4979): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2685 pos 20: '_debugCurrentBuildTarget == context': is not true.
E/flutter ( 4979): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 4979): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 4979): #2      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2685:20)
E/flutter ( 4979): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2689:12)
E/flutter ( 4979): #4      RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
E/flutter ( 4979): #5      WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
E/flutter ( 4979): #6      WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
E/flutter ( 4979): #7      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 4979): #8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 4979): #9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 4979): #10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
E/flutter ( 4979): 
W/Gralloc3( 4979): mapper 3.x is not supported
D/OpenGLRenderer( 4979): makeCurrent EglSurface : 0x0 -> 0x79a2cf2100

======== Exception caught by widgets library =======================================================
The following assertion was thrown building BlocProvider<AppCubit>:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
```

**Comment by danagbemava-nc** [comment]
This is likely an issue with how you are using your cubits, not a flutter issue. You should visit other flutter communities or post on StackOverflow so that others can help you as this is not a forum for that. 

Closing from here. 

Thank you
