### ISSUE TITLE
Missing some artifacts files or folders

### ISSUE THREAD

**Issue by LeonardoRosaa** [flutter/flutter#134160]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Go through [riverpod_lint_flutter_test](https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_lint_flutter_test);
2. Run the command `flutter test`

### Actual results

The Flutter throws many exceptions when running the tests using the `flutter test` command. The exceptions looks like missing some artifacts files/folders.

### Logs

<details>
<summary>Logs</summary>

```console

To run this test again: /Users/leonardo/flutter/bin/cache/dart-sdk/bin/dart test /Users/leonardo/www/riverpod/packages/riverpod_lint_flutter_test/test/assists/convert_to_widget_test.dart -p vm --plain-name 'Convert widgets to consumerStatefulWidgets without hooks_riverpod and flutter_hooks dependency'
00:03 +1 -22: /Users/leonardo/www/riverpod/packages/riverpod_lint_flutter_test/test/assists/convert_to_widget_test.dart: Convert widgets to statefulWidgets without hooks_riverpod and flutter_hooks dependency                                                                                                                                                          
[exception: PathNotFoundException(path=/Users/leonardo/flutter/bin/cache/artifacts/engine/lib/_internal/sdk_library_metadata/lib/libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:159:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:499:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:398:18)
#3      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:200:21)
#4      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:110:15)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:99:36)
#6      _createAnalysisContext (package:analyzer/dart/analysis/utilities.dart:127:42)
#7      resolveFile2 (package:analyzer/dart/analysis/utilities.dart:117:7)
#8      _runGoldenTest.<anonymous closure> (file:///Users/leonardo/www/riverpod/packages/riverpod_lint_flutter_test/test/assists/convert_to_widget_test.dart:161:28)
#9      testGolden.<anonymous closure> (file:///Users/leonardo/www/riverpod/packages/riverpod_lint_flutter_test/test/golden.dart:29:31)
#10     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
#11     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:213:7)
<asynchronous suspension>
#12     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:258:9)
<asynchronous suspension>
]
[exception: PathNotFoundException(path=/Users/leonardo/flutter/bin/cache/artifacts/engine/lib/_internal/libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:159:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:499:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:398:18)
#3      ContextBuilderImpl._createSdk (package:analyzer/src/dart/analysis/context_builder.dart:200:21)
#4      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:110:15)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:99:36)
#6      _createAnalysisContext (package:analyzer/dart/analysis/utilities.dart:127:42)
#7      resolveFile2 (package:analyzer/dart/analysis/utilities.dart:117:7)
#8      _runGoldenTest.<anonymous closure> (file:///Users/leonardo/www/riverpod/packages/riverpod_lint_flutter_test/test/assists/convert_to_widget_test.dart:161:28)
#9      testGolden.<anonymous closure> (file:///Users/leonardo/www/riverpod/packages/riverpod_lint_flutter_test/test/golden.dart:29:31)
#10     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
#11     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:213:7)
<asynchronous suspension>
#12     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:258:9)
<asynchronous suspension>
]
00:03 +1 -23: /Users/leonardo/www/riverpod/packages/riverpod_lint_flutter_test/test/assists/convert_to_widget_test.dart: Convert widgets to statefulWidgets without hooks_riverpod and flutter_hooks dependency [E]                                                                                                                                                      
  PathNotFoundException(path=/Users/leonardo/flutter/bin/cache/artifacts/engine/version; message=Cannot open file)
  package:analyzer/file_system/physical_file_system.dart 159:7               _PhysicalFile.readAsStringSync
  package:analyzer/src/dart/sdk/sdk.dart 422:12                              FolderBasedDartSdk.languageVersion
  package:analyzer/src/dart/analysis/context_builder.dart 220:40             ContextBuilderImpl._createSdk
  package:analyzer/src/dart/analysis/context_builder.dart 110:15             ContextBuilderImpl.createContext
  package:analyzer/src/dart/analysis/analysis_context_collection.dart 99:36  new AnalysisContextCollectionImpl
  package:analyzer/dart/analysis/utilities.dart 127:42                       _createAnalysisContext
  package:analyzer/dart/analysis/utilities.dart 117:7                        resolveFile2
  test/assists/convert_to_widget_test.dart 161:28                            _runGoldenTest.<fn>
  test/golden.dart 29:31                                                     testGolden.<fn>
  

To run this test again: /Users/leonardo/flutter/bin/cache/dart-sdk/bin/dart test /Users/leonardo/www/riverpod/packages/riverpod_lint_flutter_test/test/assists/convert_to_widget_test.dart -p vm --plain-name 'Convert widgets to statefulWidgets without hooks_riverpod and flutter_hooks dependency'
00:03 +1 -23: Some tests failed.   
```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[!] Flutter (Channel master, 3.14.0-14.0.pre.93, on macOS 13.4 22F66 darwin-arm64, locale en-BR)
    • Flutter version 3.14.0-14.0.pre.93 on channel master at /Users/leonardo/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/leonardo/flutter. Consider adding /Users/leonardo/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef9befc9da (3 days ago), 2023-09-03 11:23:20 -0700
    • Engine revision fbc6f4a540
    • Dart version 3.2.0 (build 3.2.0-131.0.dev)
    • DevTools version 2.27.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/leonardo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • Leonardo’s iPhone (mobile) • 86146fab9285d40b2372e9ce51f70a740408cb69 • ios            • iOS 15.6.1 19G82
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                                   • web-javascript • Brave Browser 116.1.57.57

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @LeonardoRosaa 
Which old Flutter version did this work? I ran the package test with Flutter 3.10.6 but it also failed same as the latest stable 3.13.2. 

Also, I'm not familiar with the package. Can you provide a simple sample test to reproduce the issue without using the package?

**Comment by LeonardoRosaa** [comment]
> Hi @LeonardoRosaa Which old Flutter version did this work? I ran the package test with Flutter 3.10.6 but it also failed same as the latest stable 3.13.2.
> 
> Also, I'm not familiar with the package. Can you provide a simple sample test to reproduce the issue without using the package?

Hi @huycozy 

I don't have any idea which version this did work. It's my first time facing this package. Sorry, I can't answer this.

I could create a simple sample but I need some time to study about :)

**Comment by huycozy** [comment]
>I could create a simple sample but I need some time to study about :)

Yes, please do so that we can verify this properly. Thanks!

**Comment by huycozy** [comment]
Glad you solved it. Closing the issue as solved.
