### ISSUE TITLE
ListView does not compile with IntrinsicHeight

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#134225]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run

```dart
IntrinsicHeight(
  child: ListView(
    scrollDirection: Axis.horizontal,
    children: [
      Container(
        constraints: const BoxConstraints(
          minHeight: 10,
        ),
        width: 100,
        color: Colors.yellow,
        child: const Text('Test\n Test'),
      ),
      Container(
        constraints: const BoxConstraints(
          minHeight: 10,
        ),
        color: Colors.red,
        width: 100,
        child: const Text(''),
      ),
    ],
  ),
),

```

### Expected results

Behave the same as with row

```dart
IntrinsicHeight(
  child: Row(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    children: [
      Container(
        constraints: const BoxConstraints(
          minHeight: 10,
        ),
        width: 100,
        color: Colors.yellow,
        child: const Text('Test\n Test'),
      ),
      Container(
        constraints: const BoxConstraints(
          minHeight: 10,
        ),
        color: Colors.red,
        width: 100,
        child: const Text(''),
      ),
    ],
  ),
),

```

### Actual results

Error in the console.

I prefer to use `ListView` since I am building my widgets from items in the server, and intend to use `ListView.separated`

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>How it should look like</summary>

![image](https://github.com/flutter/flutter/assets/9304740/655cfeba-864e-49ed-9cbc-e53fa223fc42)

</details>

### Logs

<details><summary>Logs</summary>

```console

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderViewport does not support returning intrinsic dimensions.

Calculating the intrinsic dimensions would require instantiating every child of the viewport, which defeats the point of viewports being lazy.

If you are merely trying to shrink-wrap the viewport in the main axis direction, consider a RenderShrinkWrappingViewport render object (ShrinkWrappingViewport widget), which achieves that effect without implementing the intrinsic dimension API.

The relevant error-causing widget was: 
  IntrinsicHeight IntrinsicHeight:file:///home/guy/Documents/git/remepy/frontend/packages/widgets/lib/organisms/library_organisms/library_overview_organism.dart:144:29
When the exception was thrown, this was the stack: 
#0      RenderViewportBase.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:424:9)
#1      RenderViewportBase.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:438:6)
#2      RenderViewportBase.computeMaxIntrinsicHeight (package:flutter/src/rendering/viewport.dart:462:12)
#3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#6      RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#7      RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:98:21)
#8      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#10     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#11     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#12     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:98:21)
#13     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#14     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#15     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#16     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#17     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:98:21)
#18     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#19     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#20     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#21     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#22     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:98:21)
#23     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#24     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#25     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#26     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#27     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:98:21)
#28     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#29     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#30     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#31     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#32     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:98:21)
#33     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#34     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#35     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#36     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#37     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:98:21)
#38     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#39     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#40     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#41     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#42     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:98:21)
#43     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#44     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#45     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#46     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#47     RenderIntrinsicHeight._computeSize (package:flutter/src/rendering/proxy_box.dart:836:38)
#48     RenderIntrinsicHeight.performLayout (package:flutter/src/rendering/proxy_box.dart:856:12)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#50     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#51     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#52     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#53     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#55     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#56     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#57     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#58     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#61     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#62     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:868:45)
#63     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#65     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#66     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#68     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#71     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#74     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#75     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:240:19)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#77     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139:12)
#78     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:160:11)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#80     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534:13)
#81     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1511:12)
#82     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1420:20)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#84     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#87     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#89     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#90     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#92     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#93     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#96     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#99     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#101    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#102    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#105    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#106    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#107    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#109    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#110    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:315:14)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#112    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#113    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#114    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056:7)
#115    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
#116    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#118    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#120    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#121    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#122    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#123    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#124    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#125    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#126    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#127    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#128    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#129    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#130    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#131    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#132    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#133    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#134    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#135    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#136    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#137    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#138    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#139    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#140    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#141    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#142    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#143    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#144    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#145    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3751:13)
#146    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#147    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#148    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#149    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#150    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#151    _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:832:15)
#152    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#153    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#154    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#155    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#156    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#157    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#158    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#159    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#160    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#161    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#162    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#163    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#164    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:554:11)
#165    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#166    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#167    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#168    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#169    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#170    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#171    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#172    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#173    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#174    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#175    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#176    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#177    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#178    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#179    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#180    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#181    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#182    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#183    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#184    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#185    RenderView.performLayout (package:flutter/src/rendering/view.dart:173:14)
#186    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2234:7)
#187    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1016:18)
#188    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:492:19)
#189    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#190    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#191    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#192    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#193    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#197    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderIntrinsicHeight#9e88e relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...  size: Size(392.7, 52.0)
RenderObject: RenderIntrinsicHeight#9e88e relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
  size: Size(392.7, 52.0)
...  child: RenderClipRect#89224 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none>
...    constraints: MISSING
...    size: MISSING
...    child: RenderTransform#fec22 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...      origin: null
...      alignment: Alignment.centerLeft
...      textDirection: rtl
...      transformHitTests: true
...      child: _RenderScrollSemantics#6959e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        semantic boundary
...        size: MISSING
...        child: RenderPointerListener#6a7fc NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          behavior: deferToChild
...          listeners: signal
====================================================================================================
]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on Ubuntu 23.04 6.2.0-31-generic, locale en_IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.2)
[✓] VS Code
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @guyluz11. Thanks for filing this. From the logs, this seems to be a conflict between the `IntinsticHeight` and `ListView`, you can try adding a height to the `ListView` to solve this. See code sample below for a workaround this situation.

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IntrinsicHeight(
        child: Container(
          height: double.maxFinite,
          child: ListView(
            scrollDirection: Axis.horizontal,
            children: [
              Container(
                constraints: const BoxConstraints(
                  minHeight: 10,
                ),
                width: 100,
                color: Colors.yellow,
                child: const Text('Test\n Test'),
              ),
              Container(
                constraints: const BoxConstraints(
                  minHeight: 10,
                ),
                color: Colors.red,
                width: 100,
                child: const Text(''),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
``` 

</p>
</details> 

Here is a similar issue of a conflict between `IntrinsicWidth` and `ListView` you might want to checkout https://github.com/flutter/flutter/issues/18108.
Closing this as this seems to be expected, if you disagree, kindly comment and I'd reopen this.
Thank you!
