### ISSUE TITLE
[go_router] If you use Scaffold.showBottomSheet, page transitions will no longer be possible.

### ISSUE THREAD

**Issue by lynrin** [flutter/flutter#134370]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a main page and subpage, and implement the process to display the bottom sheet on the subpage.
2. With the bottom sheet displayed on the subpage, press the back button on the AppBar to close the bottom sheet.
3. If you press the AppBar back button again, an exception will occur and you will not be able to return to the main page.

### Expected results

I can return to the main page by pressing the AppBar's back button.

### Actual results

The following exception occurs.

> E/flutter (29106): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
> E/flutter (29106): #0      List.last (dart:core-patch/growable_array.dart:348:5)
> E/flutter (29106): #1      _PagePopContext.onPopPage (package:go_router/src/builder.dart:596:57)
> E/flutter (29106): #2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5045:28)
> E/flutter (29106): #3      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5005:9)
> E/flutter (29106): <asynchronous suspension>

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app shows an app with two screens.
///
/// The first route '/' is mapped to [HomeScreen], and the second route
/// '/details' is mapped to [DetailsScreen].
///
/// The buttons use context.go() to navigate to each destination. On mobile
/// devices, each destination is deep-linkable and on the web, can be navigated
/// to using the address bar.
void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'details',
          builder: (BuildContext context, GoRouterState state) {
            return const DetailsScreen();
          },
        ),
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () => context.go('/details'),
          child: const Text('Go to the Details screen'),
        ),
      ),
    );
  }
}

/// The details screen
class DetailsScreen extends StatelessWidget {
  /// Constructs a [DetailsScreen]
  const DetailsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Details Screen')),
      body: const DetailInnerScreen(),
    );
  }
}

class DetailInnerScreen extends StatelessWidget {
  /// Constructs a [DetailInnerScreen]
  const DetailInnerScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          ElevatedButton(
            onPressed: () => context.go('/'),
            child: const Text('Go back to the Home screen'),
          ),
          ElevatedButton(
            onPressed: () {
              showBottomSheet(
                context: context,
                backgroundColor: Colors.orange,
                builder: (context) {
                  return SizedBox(
                    height: 300,
                    width: double.infinity,
                    child: TextButton.icon(
                      onPressed: () {
                        Navigator.pop(context);
                      },
                      icon: const Icon(Icons.close),
                      label: const Text('Close'),
                    ),
                  );
                },
              );
            },
            child: const Text('Show the Bottom sheet'),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-arm64, locale ja-JP)
    • Flutter version 3.13.3 on channel stable at /Users/user/.asdf/installs/flutter/3.13.3-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (3 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 13.5.2 22G91 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by lynrin** [comment]
This issue has been occurring since go_router 10.1.1.

For your reference:
https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/builder.dart#L596-L597
This can be avoided by changing lines 596 to 597 of go_router/lib/src/builder.dart to the following.

```dart
  bool onPopPage(Route<dynamic> route, dynamic result) {
    final Page<Object?> page = route.settings as Page<Object?>;

    final RouteMatch match = _routeMatchesLookUp[page]!.last;

    // If a popup is opened using something like Scaffold.showBottomSheet,
    // it will be registered in LocalHistoryRoute._localHistory,
    // so it should be deleted from _routeMatchesLookUp only if
    // LocalHistoryRoute.willHandlePopInternally is false.
    if (route is LocalHistoryRoute && route.willHandlePopInternally == false) {
      _routeMatchesLookUp[page]!.removeLast();
    }

    return onPopPageWithRouteMatch(route, result, match);
  }
```

(Diff)
```diff
    bool onPopPage(Route<dynamic> route, dynamic result) {
      final Page<Object?> page = route.settings as Page<Object?>;
  
      final RouteMatch match = _routeMatchesLookUp[page]!.last;
-     _routeMatchesLookUp[page]!.removeLast();
+
+     // If a popup is opened using something like Scaffold.showBottomSheet,
+     // it will be registered in LocalHistoryRoute._localHistory,
+     // so it should be deleted from _routeMatchesLookUp only if
+     // LocalHistoryRoute.willHandlePopInternally is false.
+     if (route is LocalHistoryRoute && route.willHandlePopInternally == false) {
+       _routeMatchesLookUp[page]!.removeLast();
+     }
  
      return onPopPageWithRouteMatch(route, result, match);
    }
```

I'm posting this as an issue because I can't accurately judge whether this is the correct solution.

**Comment by darshankawar** [comment]
Thanks for the report @lynrin 
I ran the code sample using latest master and package version but unable to replicate the reported error:


https://github.com/flutter/flutter/assets/67046386/dbad472a-c077-4d13-a2ae-913804207e22

The console log didn't throw any error. Can you use the latest package version and try again ?

**Comment by lynrin** [comment]
Thanks for checking @darshankawar.

I'm using go_router version 10.1.2.
I also shot a video here.
Steps are
1. Click the "Go to the Details screen" button.
2. Click the "Show the bottom sheet" button.
3. Click the back button on the AppBar. (The bottom sheet closes.)
4. Click the back button on the AppBar. (An exception occurred.)

I get an exception at "4. Click the back button on the AppBar."

https://github.com/flutter/flutter/assets/12870525/4e06bab1-903a-438f-84ce-dba51b046223

**Comment by darshankawar** [comment]
Thanks for the update. Yes, I now see the same error as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.13.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.2 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (7 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.14.0-14.0.pre.212, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.14.0-14.0.pre.212 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffe1ebd207 (67 minutes ago), 2023-09-11 03:46:15 -0400
    • Engine revision 1aa11b6448
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by lynrin** [comment]
Thank you very much.

I have also sent the corrected code written in the comments as a Pull Request(flutter/packages#4882).

**Comment by chunhtai** [comment]
I didn't see error when pressing back button, only when clicking Go back to home screen.

**Comment by lynrin** [comment]
Thank you @chunhtai for checking.

Could you please post the steps and video of the operation you performed?

**Comment by keithcwk** [comment]
@lynrin Was also facing a similar issue in v10.1.2, upgraded the package to v12.0.0 and the issue seems to be resolved, however, you might want to find out from which version onwards was this issue fixed

**Comment by lynrin** [comment]
@darshankawar @chunhtai @keithcwk ,

It seems that this problem has stopped occurring since the release of v11.0.0.
https://github.com/flutter/packages/blob/55b7293656e01eabc96b3ef8d9c641b832e803ff/packages/go_router/lib/src/builder.dart#L596-L599

I will close this issue.
