### ISSUE TITLE
`flutter create` fails in an empty directory: no pubspec.yaml found

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#13435]
## Steps to Reproduce
```
$ mkdir new_app
$ cd new_app
$ flutter create .
/<snip>/new_app: no pubspec.yaml found
```

## Flutter Doctor

[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /<snip>/flutter
    • Framework revision 9315a79b11 (2 hours ago), 2017-12-07 13:31:32 -0800
    • Engine revision f888186e50
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.e7b7b68ef6e7b1e5df379b628134764c489901dc

**Comment by sethladd** [comment]
cc @mit-mit @devoncarew

**Comment by devoncarew** [comment]
Hmm, I wasn't able to repro this:
```
mkdir foo
cd foo
flutter create .
...
All done! In order to run your application, type:
```

@DaveShuckerow, can you try and repro using `flutter create -v .`? That may give us more indication about where it's failing. Thanks!

**Comment by mit-mit** [comment]
I can't repro this either; closing. @DaveShuckerow if still have a repro, feel free to reopen.

**Comment by DaveShuckerow** [comment]
I upgraded to the latest Flutter and this issue no longer occurred.  This can stay closed.

For future reference, this is the verbose error that I got:

```
$ flutter create -v .
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:109)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
<asynchronous suspension>
#3      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      new Future.sync (dart:async/future.dart:222)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#10     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     runZoned (dart:async/zone.dart:1467)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:44)
<asynchronous suspension>
#19     main (file:///usr/local/google/home/djshuckerow/Code/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
