### ISSUE TITLE
Error "Scaffold.geometryOf() must only be accessed during the paint phase" freezes any further interactions in debug mode

### ISSUE THREAD

**Issue by lyskouski** [flutter/flutter#134408]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run application in debug mode
2. Go through the pages
3. Come back (by using "back" button) to the main page

### Expected results

Interactive state of an application

### Actual results

Application became fully unfunctional (not responding to any clicks or ever)

Similar issues:
- https://github.com/flutter/flutter/issues/126513
- https://github.com/flutter/flutter/issues/108363
- https://github.com/flutter/flutter/issues/76325
- https://github.com/flutter/flutter/issues/107355
- https://github.com/flutter/flutter/issues/107063

### Code sample

<details><summary>Code sample</summary>

Taken from #108363:

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(const MaterialApp(home: Search()));
}

class SearchState extends State<Search> {
  final List<String> _languages = ["French", "Dutch"];
  List<String> _items = [];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Languages'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: [
            TextField(
              autofocus: true,
              onChanged: (value) async {
                List<String> items = [value, "word 1", "word 2", "word 3"];
                setState(() {
                  _items = items;
                });
              },
              decoration: const InputDecoration(
                hintText: 'Search',
                contentPadding:
                    EdgeInsets.symmetric(vertical: 10.0, horizontal: 20.0),
                border: OutlineInputBorder(),
                enabledBorder: OutlineInputBorder(
                  borderSide:
                      BorderSide(color: Colors.lightBlueAccent, width: 1.0),
                ),
                focusedBorder: OutlineInputBorder(
                  borderSide:
                      BorderSide(color: Colors.lightBlueAccent, width: 2.0),
                ),
              ),
            ),
            Expanded(
              child: ListView.builder(
                  scrollDirection: Axis.vertical,
                  itemCount: _items.length,
                  itemBuilder: (context, index) {
                    return ListTile(
                      title: Text(_items[index]),
                      shape: const RoundedRectangleBorder(
                        side: BorderSide(color: Colors.black38, width: .3),
                        borderRadius: BorderRadius.all(Radius.circular(3)),
                      ),
                      onTap: () async {
                        Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (context) => WordDisplay(),
                            ));
                      },
                    );
                  }),
            )
          ],
        ),
      ),
    );
  }
}

class Search extends StatefulWidget {
  const Search({super.key});

  @override
  SearchState createState() => SearchState();
}

class WordDisplay extends StatelessWidget {
  const WordDisplay({Key? key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Word"),
      ),
      bottomNavigationBar: BottomAppBar(
        shape: const CircularNotchedRectangle(),
        child: Container(
          height: 50,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => {},
        tooltip: 'Tables of forms',
        child: const Icon(Icons.grid_on_outlined),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      body: const Text("data"),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/8281925/012cf449-94b9-4328-aa3b-0a0f3c6b678f

</details>

### Logs

<details><summary>Logs</summary>

```console
# first error:
The following assertion was thrown while handling a pointer data packet:
Scaffold.geometryOf() must only be accessed during the paint phase.
The ScaffoldGeometry is only available during the paint phase, because its value is computed during
the animation and layout phases prior to painting.

When the exception was thrown, this was the stack:
#0      _ScaffoldGeometryNotifier.value.<anonymous closure> (package:flutter/src/material/scaffold.dart:831:9)
#1      _ScaffoldGeometryNotifier.value (package:flutter/src/material/scaffold.dart:838:6)
#2      _BottomAppBarClipper.getClip (package:flutter/src/material/bottom_app_bar.dart:262:35)
#3      _RenderCustomClip._updateClip (package:flutter/src/rendering/proxy_box.dart:1438:25)
#4      RenderPhysicalShape.hitTest (package:flutter/src/rendering/proxy_box.dart:2099:7)

Another exception was thrown: Scaffold.geometryOf() must only be accessed during the paint phase.

# infinite loop of:
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 205 pos 12: '!_debugDuringDeviceUpdate': is not true.

# additional errors:
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 226 pos 12: '(event is PointerAddedEvent) == (lastEvent is
PointerRemovedEvent)': is not true.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on KDE neon 5.27 6.2.0-32-generic, locale en_AG)
    • Flutter version 3.13.3 on channel stable at /home/vlyskouski/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (4 дня назад), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0
```

</details>

**Comment by dam-ease** [comment]
Hi @lyskouski. Thanks for filing this. Running the sample provided on the latest stable version, I'm unable to reproduce this. Can you please provide more information on how this reproduces?

https://github.com/flutter/flutter/assets/53122008/6fdf8219-ef82-479a-b57c-d953af144e66

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.3 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (5 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (6 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 13 Pro (mobile)      • 14B6FEE4-2F1C-401F-8804-A5115D7A6DA2 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile)          • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro (mobile)      • 6548B0D1-7674-4306-9852-198C465F1104 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by lyskouski** [comment]
It can be used "more complex" [example](https://github.com/lyskouski/app-finance):
- step through initial steps (confirm settings, acknowledge privacy policy, next steps can be skipped by refresh button | reopen app [hot reload])
- Menu -> Settings -> Recovery -> Recovery from file: [app-finance.log](https://github.com/flutter/flutter/files/12577341/app-finance.log)
- Refresh page | reopen app (hot reload)
- Click on "qwe" Bill, then tap on "Back" button

https://github.com/flutter/flutter/assets/8281925/d618f370-72a4-496d-81c6-662ee799d400

**Comment by dam-ease** [comment]
Thanks for your response @lyskouski. I see you're reproducing this with a large app, Please check [this](https://stackoverflow.com/questions/75310430/scaffold-geometryof-must-only-be-accessed-during-the-paint-phase) answer to see if it is helpful for this case.

If this still appears, please we'd need you to provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. 

Thank you!

**Comment by lyskouski** [comment]
Helllo @dam-ease,
You're right, I've been able to caught a constantly reproducible state of the issue on a large app. The minimal code, is not giving a stable outcome, it's been attached at the beginning. Assume, it might be a platform specific issue as well (I've seen your video for macOS, on Linux it was much easier to catch). 

I've forked Flutter repository to unblock myself with the change: https://github.com/flutter/flutter/pull/134409/files
Might rely on your assistance to fix tests by not seeing the output of failures (| 01:57 +3162 ~4 -10: Some tests failed).

Thanks in advance

**Comment by dam-ease** [comment]
Thanks for your response. Not sure I fully understand this. Are you able to solve the issue with resetting the `FABLocation`?
Note: For us to proceed with the issue we'd need to be able to reproduce on our end with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Kindly let me know if the solution in the Thread worked or more info on this?

**Comment by lyskouski** [comment]
Nope, I wasn't able to solve the issue by resetting the `FABLocation`, I've forked Flutter repository, patched, and bind it via  `export PATH="$PATH:~/flutter_patch/bin"`.

I'll try to prepare a minimal code sample.

**Comment by lyskouski** [comment]
Next sample can be used: 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        bottomNavigationBar: BottomAppBar(
          color: Colors.yellow,
          padding: EdgeInsets.zero,
          notchMargin: CircularProgressIndicator.strokeAlignCenter,
          clipBehavior: Clip.none,
          elevation: 0.0,
          height: 40,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [Text('1'), Text('2')],
          ),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          tooltip: 'Sample 1',
          child: const Icon(Icons.add),
        ),
        body: Container(
          width: double.infinity,
          color: Colors.grey,
          child: SingleChildScrollView(
            child: Column(
              children: <Widget>[
                const Text(
                  'Start App, uncomment `Expanded`, '
                  'resize window to 100x100 for the scrolling, '
                  'apply hot reload (r), '
                  'scroll down',
                ),
                SizedBox(height: MediaQuery.sizeOf(context).height / 2),
                const Text(
                  'Start App, uncomment `Expanded`, '
                  'resize window to 100x100 for the scrolling, '
                  'apply hot reload (r), '
                  'scroll down',
                ),
                SizedBox(height: MediaQuery.sizeOf(context).height / 2),
                Column(
                  children: [
                    //Expanded(child:
                    Text('Error state'),
                    //),
                    SizedBox(height: 100),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by huycozy** [comment]
@lyskouski Thanks for the update. But when uncommenting the `Expanded` widget as stated in the sample code, I got another layout issue instead. I managed to fix it as the following sample code:

- Replace `Expanded` with `Flexible`
- Add `mainAxisSize: MainAxisSize.min` to the nested Column

<details>
<summary>Updated sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        bottomNavigationBar: const BottomAppBar(
          color: Colors.yellow,
          padding: EdgeInsets.zero,
          notchMargin: CircularProgressIndicator.strokeAlignCenter,
          clipBehavior: Clip.none,
          elevation: 0.0,
          height: 40,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [Text('1'), Text('2')],
          ),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          tooltip: 'Sample 1',
          child: const Icon(Icons.add),
        ),
        body: Container(
          width: double.infinity,
          color: Colors.grey,
          child: SingleChildScrollView(
            child: Column(
              children: <Widget>[
                const Text(
                  'Start App, uncomment `Expanded`, '
                  'resize window to 100x100 for the scrolling, '
                  'apply hot reload (r), '
                  'scroll down',
                ),
                SizedBox(height: MediaQuery.sizeOf(context).height / 2),
                const Text(
                  'Start App, uncomment `Expanded`, '
                  'resize window to 100x100 for the scrolling, '
                  'apply hot reload (r), '
                  'scroll down',
                ),
                SizedBox(height: MediaQuery.sizeOf(context).height / 2),
                const Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Flexible(
                      child: Text('Error state'),
                    ),
                    SizedBox(height: 100),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```
</details>

Then follow the steps there but can't reproduce this issue. Can you check this updated code and retry? 

It would be appreciated if you could provide detailed steps (a recorded video). Thanks!

**Comment by lyskouski** [comment]
Video with updated sample:

https://github.com/flutter/flutter/assets/8281925/22599b4c-41e4-4d53-a227-2031a88bc48a

**Comment by dam-ease** [comment]
Hi @lyskouski. Thanks for your response. I see the issue you are experiencing running the latest code sample you shared but this seems to be a layout issue looking at the logs, replacing the `Expanded` widget in the sample with a `Flexible` widget solves this (see code sample below). Can you try this out?
If this doesn't work for your use case, could you provide more information to help understand this better?

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    final state = UniqueKey();
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        bottomNavigationBar: const BottomAppBar(
          color: Colors.yellow,
          padding: EdgeInsets.zero,
          notchMargin: CircularProgressIndicator.strokeAlignCenter,
          clipBehavior: Clip.none,
          elevation: 0.0,
          height: 40,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [Text('1'), Text('2')],
          ),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          tooltip: 'Sample 1',
          child: const Icon(Icons.add),
        ),
        body: Container(
          width: double.infinity,
          color: Colors.grey,
          child: SingleChildScrollView(
            child: Column(
              children: <Widget>[
                Tooltip(
                  message: '$state Start App, uncomment `Expanded`, '
                      'resize window to 100x100 for the scrolling, '
                      'apply hot reload (r), '
                      'scroll down',
                  child: Text(
                    '$state Start App, uncomment `Expanded`, '
                    'resize window to 100x100 for the scrolling, '
                    'apply hot reload (r), '
                    'scroll down',
                  ),
                ),
                SizedBox(height: MediaQuery.sizeOf(context).height / 2),
                Tooltip(
                  message: '$state Start App, `Flexible` to `Expanded`, '
                      'resize window to 100x100 for the scrolling, '
                      'apply hot reload (r), '
                      'scroll down',
                  child: Text(
                    '$state Start App, `Flexible` to `Expanded`, '
                    'resize window to 100x100 for the scrolling, '
                    'apply hot reload (r), '
                    'scroll down',
                  ),
                ),
                SizedBox(height: MediaQuery.sizeOf(context).height / 2),
                Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Flexible(
                      child: Text('$state Error state'),
                    ),
                    const SizedBox(height: 100),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
``` 

</p>
</details>
