### ISSUE TITLE
Image Picker error

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#13446]
Hi, after the last updates of android studio and flutter, if i launch this:

`var fileName = await ImagePicker.pickImage();`

i receive this error:

```
W/art     (13656): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/ResourceType(13656): Invalid package identifier when getting bag for resource number 0x00000000
D/EGL_emulation(13656): eglMakeCurrent: 0x9c885600: ver 2 0 (tinfo 0x9c883e40)
D/skia    (13656): --- SkAndroidCodec::NewFromStream returned null
D/skia    (13656): --- SkAndroidCodec::NewFromStream returned null
D/AndroidRuntime(13656): Shutting down VM
E/AndroidRuntime(13656): FATAL EXCEPTION: main
E/AndroidRuntime(13656): Process: com.shuttertop.app, PID: 13656
E/AndroidRuntime(13656): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { (has extras) }} to activity {com.shuttertop.app/com.shuttertop.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.CallbackManager.onActivityResult(int, int, android.content.Intent)' on a null object reference
E/AndroidRuntime(13656): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
E/AndroidRuntime(13656): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
E/AndroidRuntime(13656): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime(13656): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
E/AndroidRuntime(13656): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(13656): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(13656): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/AndroidRuntime(13656): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13656): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime(13656): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/AndroidRuntime(13656): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.CallbackManager.onActivityResult(int, int, android.content.Intent)' on a null object reference
E/AndroidRuntime(13656): 	at com.appnormal.plugin.fblogin.ApnFbLoginPlugin.onActivityResult(ApnFbLoginPlugin.java:133)
E/AndroidRuntime(13656): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:160)
E/AndroidRuntime(13656): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime(13656): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:122)
E/AndroidRuntime(13656): 	at android.app.Activity.dispatchActivityResult(Activity.java:6932)
E/AndroidRuntime(13656): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
E/AndroidRuntime(13656): 	... 9 more

```

**Comment by roughike** [comment]
This doesn't seem to be caused by the ImagePicker plugin, but some other plugin related to Facebook login. See this line:

```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.CallbackManager.onActivityResult(int, int, android.content.Intent)' on a null object reference
```

What is the `com.appnormal.plugin.fblogin.ApnFbLoginPlugin` and where is it from? 

My guess is that it listens for the activity result from the Facebook login dialog, and the instance of `ApnFbLoginPlugin` is only created when the Facebook login is called. Since the activity result comes from the image picker instead, there's no instance of the `ApnFbLoginPlugin` instantiated, which results in a `NullPointerException`.

(this is just speculation, hard to be 100% sure since I don't have access to your source code)

**Comment by sethladd** [comment]
cc @collinjackson

**Comment by romaluca** [comment]
Ok. The issue was in apn_fb_login plugin.
It is resolved now.

Thanks

https://github.com/markmooibroek/apn_fb_login/issues/2
