### ISSUE TITLE
Unable to widgetTester.enterText 2 times or more in the same text fields in flutter integration test

### ISSUE THREAD

**Issue by ThatPham2000** [flutter/flutter#134604]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. I entered invalid email text into the text field with the text 'Email'
2. I clicked 'Sign in'
3. I checked the error text.
4. I re-entered a valid email to this field.

### Expected results

The email text field value should be the new valid email.

### Actual results

The email text field value still kept the old invalid email.

### Code sample

<details><summary>Code sample</summary>

```dart
await tester.enterText(
          find.widgetWithText(TextField, 'Email'),
          'invalid@gmail..com',
        );
await tester.pumpAndSettle();

await tester.tap(find.widgetWithText(
            ElevatedButton, 'Sign in'));
await tester.pumpAndSettle();
expect(find.text('Invalid email'), findsOneWidget);

await tester.enterText(
          find.widgetWithText(TextField, 'Email'),
          'valid@gmail.com',
        );
await tester.pumpAndSettle();
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale
    en-VN)
    • Flutter version 3.13.2 on channel stable at /Users/phat/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (3 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/phat/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • F8FD829A-C7E2-480D-BB26-BE7B40808AE0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by tixngo-mobile-github** [comment]
I face the same issue, please help to fix it

**Comment by hoantruong** [comment]
Please help to fix this issue, it happens many times when running my test. Thanks!

**Comment by windymv025** [comment]
Same issues

**Comment by dam-ease** [comment]
Hi @ThatPham2000. Thanks for filing this. I see this is similar to https://github.com/flutter/flutter/issues/120060. Are you experiencing any different behaviour from that shared in the already open issue? If yes, kindly share this.

Note: Thanks everyone for sharing but instead of commenting, kindly upvote the issue to draw more attention to this. Thank you!

**Comment by ThatPham2000** [comment]
Hello @dam-ease. In my case, I tested it on another platform that was mobile (iOS simulators) instead of the web. Besides, I entered an invalid email, checked the invalid message, and re-entered a valid email without clearing the text field. It is the difference. Thank you.

**Comment by dam-ease** [comment]
Thanks for your response. Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code as in the related issue?
Also, in your case, does this reproduce only on mobile or it does on the web as well?

**Comment by ThatPham2000** [comment]
**main.dart**
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _controller = TextEditingController();
  final _formKey = GlobalKey<FormState>();

  void _doAction() =>
      (_formKey.currentState?.validate() ?? false) ? print('valid') : null;

  void _dismissKeyboard() => FocusManager.instance.primaryFocus?.unfocus();

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: _dismissKeyboard,
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: Text(widget.title),
        ),
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Form(
              key: _formKey,
              child: TextFormField(
                controller: _controller,
                decoration: const InputDecoration(labelText: 'Email'),
                validator: (value) {
                  if (value?.isEmpty ?? true) {
                    return 'Required';
                  }
                  if (!RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$')
                      .hasMatch(value!)) {
                    return 'Invalid email';
                  }
                  return null;
                },
              ),
            ),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            _dismissKeyboard();
            _doAction();
          },
          child: const Icon(Icons.check),
        ),
      ),
    );
  }
}
``` 

**app_integration_test.dart**
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:test_text_field/main.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('App integration test', () {
    testWidgets('Check re-entering text field', (tester) async {
      await tester.pumpWidget(const MyApp());
      await tester.pumpAndSettle();

      await tester.tap(find.byIcon(Icons.check));
      await tester.pumpAndSettle();
      expect(find.text('Required'), findsOneWidget);

      await tester.enterText(
          find.widgetWithText(TextFormField, 'Email'), 'abcdef');
      await tester.pumpAndSettle();
      await tester.tap(find.byIcon(Icons.check));
      await tester.pumpAndSettle();
      expect(find.text('Invalid email'), findsOneWidget);

      await tester.enterText(
        find.widgetWithText(TextFormField, 'Email'),
        'super-tester@gmail.com',
      );
      await tester.pumpAndSettle();
      await tester.tap(find.byIcon(Icons.check));
      await tester.pumpAndSettle();
      expect(find.text('Required'), findsNothing);
      expect(find.text('Invalid email'), findsNothing);
    });
  });
}
```

**Comment by dam-ease** [comment]
Hi @ThatPham2000. Thanks for your response. Running this on my end, I get the log below, can you confirm this on your end as well or kindly help with  sharing the logs on your end (if any)

<details><summary>Details</summary>
<p>

```
  Actual: _TextWidgetFinder:<Found 1 widget with text "Invalid email": [
            Text("Invalid email", debugLabel: ((englishLike bodySmall 2021).merge((blackCupertino
bodySmall).apply)).copyWith, inherit: false, color: Color(0xffba1a1a), family: .SF UI Text, size:
12.0, weight: 400, letterSpacing: 0.4, baseline: alphabetic, height: 1.3x, leadingDistribution:
even, decoration: Color(0xff1d1b1e) TextDecoration.none, textAlign: start, overflow: ellipsis,
dependencies: [DefaultSelectionStyle, DefaultTextStyle, MediaQuery]),
          ]>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/damilolaalimi/development/master/master/integration_test/app_integration_test.dart:33:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
2
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/damilolaalimi/development/master/master/integration_test/app_integration_test.dart line 33
The test description was:
  Check re-entering text field
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: Check re-entering text field


``` 

</p>
</details>

**Comment by ThatPham2000** [comment]
Hello @dam-ease dam

<details><summary>This is my log</summary>
<p>

/Users/phat/Developer/flutter/bin/flutter --no-color test --machine --start-paused -d F8FD829A-C7E2-480D-BB26-BE7B40808AE0 integration_test/app_test.dart
Testing started at 16:41 ...
Running Xcode build...                                          
Xcode build done.                                           11.6s

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: no matching nodes in the widget tree
  Actual: _TextFinder:<exactly one widget with text "Invalid email" (ignoring offstage widgets):
Text("Invalid email", debugLabel: ((englishLike bodySmall 2021).merge((blackCupertino
bodySmall).apply)).copyWith, inherit: false, color: Color(0xffba1a1a), family: .SF UI Text, size:
12.0, weight: 400, letterSpacing: 0.4, baseline: alphabetic, height: 1.3x, leadingDistribution:
even, decoration: Color(0xff1d1b1e) TextDecoration.none, textAlign: start, overflow: ellipsis,
dependencies: [DefaultSelectionStyle, DefaultTextStyle, MediaQuery])>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/phat/Desktop/test_text_field/integration_test/app_test.dart:33:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/phat/Desktop/test_text_field/integration_test/app_test.dart line 33
The test description was:
  Check re-entering text field
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Check re-entering text field

</p>
</details>

**Comment by ThatPham2000** [comment]
Hello @dam-ease 
This is my log.
```
/Users/phat/Developer/flutter/bin/flutter --no-color test --machine --start-paused -d F8FD829A-C7E2-480D-BB26-BE7B40808AE0 integration_test/app_test.dart
Testing started at 16:41 ...
Running Xcode build...                                          
Xcode build done.                                           11.6s

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: no matching nodes in the widget tree
  Actual: _TextFinder:<exactly one widget with text "Invalid email" (ignoring offstage widgets):
Text("Invalid email", debugLabel: ((englishLike bodySmall 2021).merge((blackCupertino
bodySmall).apply)).copyWith, inherit: false, color: Color(0xffba1a1a), family: .SF UI Text, size:
12.0, weight: 400, letterSpacing: 0.4, baseline: alphabetic, height: 1.3x, leadingDistribution:
even, decoration: Color(0xff1d1b1e) TextDecoration.none, textAlign: start, overflow: ellipsis,
dependencies: [DefaultSelectionStyle, DefaultTextStyle, MediaQuery])>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/phat/Desktop/test_text_field/integration_test/app_test.dart:33:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/phat/Desktop/test_text_field/integration_test/app_test.dart line 33
The test description was:
  Check re-entering text field
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Check re-entering text field
```

**Comment by dam-ease** [comment]
Thanks for your response. I can reproduce the same on the latest `master` and `stable` channels. I'd be labelling this for more insights.
Thank you!

**Comment by jBorkowska** [comment]
Had the same issue, in our case adding `tester.testTextInput.register();` before `enterText()` helped.

**Comment by ne3Vubeki** [comment]
enterText() does not work even with `tester.testTextInput.register()` if the input field has no focus. But if you add `.tap()` after `tester.testTextInput.register()`, it works. Can this point be improved?

**Comment by ne3Vubeki** [comment]
If you click on the field before tester.testTextInput.register(), enterText() will not work. I added this extension to my project to make it work:
```
extension PatrolFinderExt on PatrolFinder {
  Future<void> enterTextExt(
    String text, {
    SettlePolicy? settlePolicy,
    Duration? visibleTimeout,
    Duration? settleTimeout,
  }) async {
    tester.tester.testTextInput.register();
    await tap();
    await enterText(
      text,
      settlePolicy: settlePolicy,
      visibleTimeout: visibleTimeout,
      settleTimeout: settleTimeout,
    );
    tester.tester.testTextInput.unregister();
  }
}
```

**Comment by desmond206x** [comment]
@ne3Vubeki I think you can register the testTextInput at test startup and unregister at after the test finished. So no need to do it on every enterText method call.
But even without the problem that we need to call tester.testTextInput.register(); you have to tap into an input field before you can enter text.

**Comment by javiermrz** [comment]
Any updates on this? Using `tester.tester.testTextInput.register();` does not work for me because I use a `GestureDetector` to focus an input and do some extra action, and using the `register` method somehow makes those extra actions to stop working (when I press manually on the input, it does work).

**Comment by o7planning** [comment]
I had the same issue, and fixed it with below code:

```
final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized() as IntegrationTestWidgetsFlutterBinding;

// Necessary for being able to enterText when not in debug mode
binding.testTextInput.register();
```
