### ISSUE TITLE
 flutter build ios --analyze-size throws `PathNotFoundException: Cannot open file`

### ISSUE THREAD

**Issue by siddew201** [flutter/flutter#134711]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We need to braking down the iOS build size
We have run 'flutter build ios --analyze-size'
We are getting following error

```
Oops; flutter has exited unexpectedly: "PathNotFoundException: Cannot open file,
path = 'build/flutter_size_02/snapshot.arm64.json' (OS Error: No such file or
directory, errno = 2)".
A crash report has been written to
/Users/siddharthtiwari/Documents/myApp/app/myApp/flutter_01.log.
```

### Expected results

We should get high level summary of the size breakdown in the terminal and appropriate JSON file in DevTools.

### Actual results

```
Oops; flutter has exited unexpectedly: "PathNotFoundException: Cannot open file,
path = 'build/flutter_size_02/snapshot.arm64.json' (OS Error: No such file or
directory, errno = 2)".
A crash report has been written to
/Users/siddharthtiwari/Documents/myApp/app/myApp/flutter_01.log.
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ios --analyze-size

## exception

PathNotFoundException: PathNotFoundException: Cannot open file, path = 'build/flutter_size_02/snapshot.arm64.json' (OS Error: No such file or directory, errno = 2)


#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#8      SizeAnalyzer.analyzeAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:57:64)
#9      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:699:62)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>


## flutter doctor

[33m[!][39m Flutter (Channel stable, 3.10.6, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en-IN)
    [32m•[39m Flutter version 3.10.6 on channel stable at /Users/siddharthtiwari/Developer/Flutter
    [33m![39m Warning: `flutter` on your path resolves to /Users/siddharthtiwari/Developer/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at
      /Users/siddharthtiwari/Developer/Flutter. Consider adding /Users/siddharthtiwari/Developer/Flutter/bin to the front of your path.
    [33m![39m Warning: `dart` on your path resolves to /Users/siddharthtiwari/Developer/flutter/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/siddharthtiwari/Developer/Flutter. Consider adding /Users/siddharthtiwari/Developer/Flutter/bin to the front of your path.
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (9 weeks ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/siddharthtiwari/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3)
    [32m•[39m Xcode at /Applications/Xcode_14.3.app/Contents/Developer
    [32m•[39m Build 14E222b
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2020.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[32m[✓][39m VS Code (version 1.81.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.72.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64 (Rosetta)
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.6, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/siddharthtiwari/Developer/Flutter
    ! Warning: `flutter` on your path resolves to /Users/siddharthtiwari/Developer/flutter/bin/flutter, which is not inside your current
      Flutter SDK checkout at /Users/siddharthtiwari/Developer/Flutter. Consider adding /Users/siddharthtiwari/Developer/Flutter/bin to the
      front of your path.
    ! Warning: `dart` on your path resolves to /Users/siddharthtiwari/Developer/flutter/bin/dart, which is not inside your current Flutter SDK
      checkout at /Users/siddharthtiwari/Developer/Flutter. Consider adding /Users/siddharthtiwari/Developer/Flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update
      checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/siddharthtiwari/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode_14.3.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64 (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @siddew201, I noticed you're using an older version of flutter stable. Kindly upgrade to the latest version of flutter stable (3.13.4) to see if you still experience this crash. 

Thank you

**Comment by hrajwade96** [comment]
@danagbemava-nc  upgraded flutter to 3.13.4 

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.1 22G90 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.71.2)


still facing same issue 
Oops; flutter has exited unexpectedly: "PathNotFoundException: Cannot open file, path = 'build/flutter_size_23/snapshot.arm64.json' (OS Error: No such file or directory, errno = 2)".

adding comment here as https://github.com/flutter/flutter/issues/134725 is closed.

**Comment by danagbemava-nc** [comment]
Hi @hrajwade96, do you have this issue when you create a new project as well? I tried running it a new project but I did not get any issues

**Comment by hrajwade96** [comment]
@danagbemava-nc  checked by creating separate project, it is working for that project.
Seems it is some issue in my project, what can be the issue any idea?
It is a Flutter only project (not add to app), btw we are using melos can it cause any issues?

**Comment by danagbemava-nc** [comment]
Hi @hrajwade96, unfortunately, I'm not sure what the issue is. Tool crashes can sometimes be tricky since they don't always reproduce across devices/projects. 

Labeling for further insight from the tool team.

**Comment by christopherfujino** [comment]
cc @christopherfujino to do a preliminary investigation

**Comment by hrajwade96** [comment]
@danagbemava-nc yes the issue is only in iOS.
I will share the logs with -v soon.

**Comment by christopherfujino** [comment]
> @danagbemava-nc yes the issue is only in iOS. Android it is working fine in same project. I will share the logs with -v soon.

I took a preliminary look at the code, and it's not obvious what's wrong. It would help to have those verbose logs. In particular, I'm curious what this value is, that we're passing to gen_snapshot: https://github.com/christopherfujino/flutter/blob/f468f3366c26a5092eb964a230ce7892fda8f2f8/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L93
