### ISSUE TITLE
[tool_crash] _TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))

### ISSUE THREAD

**Issue by MichalNemec** [flutter/flutter#134788]
## Command
```
flutter build apk --release --analyze-size --target-platform android-arm64
```

## Steps to Reproduce
1. flutter build apk --release --analyze-size --target-platform android-arm64

## Logs
_TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))
```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:548:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-CZ)
    [32m•[39m Flutter version 3.10.6 on channel stable at /Users/michalnemec/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (9 weeks ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    [32m•[39m Android SDK at /Users/michalnemec/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0-rc4
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3.1)

**Comment by danagbemava-nc** [comment]
Hi @MichalNemec, this has been fixed in the latest version of flutter stable. See https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#3134-september-13-2023. 

Closing from here. If you still face this issue on the latest version of flutter stable (3.13.4), kindly leave a comment below and I will reopen this. 

See https://github.com/flutter/flutter/issues/132695 for the original issue. 

Thank you
