### ISSUE TITLE
/api/github/webhook-subscription keeps failing to process `push`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#134746]
![Screenshot 2023-09-14 at 9 39 21 AM](https://github.com/flutter/flutter/assets/54558023/50a526ad-5200-45d5-a022-a67e56991381)

```
type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      _$RepositoryFromJson (package:github/src/common/model/repos.g.dart:125:48)
#1      new Repository.fromJson (package:github/src/common/model/repos.dart:456:7)
#2      _$PushEventFromJson (package:github/src/server/hooks.g.dart:183:24)
#3      new PushEvent.fromJson (package:github/src/server/hooks.dart:252:7)
#4      GithubWebhookSubscription.post (package:cocoon_service/src/request_handlers/github/webhook_subscription.dart:117:47)
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:30)
#6      _rootRun (dart:async/zone.dart:1399:13)
#7      _CustomZone.run (dart:async/zone.dart:1301:19)
#8      _runZoned (dart:async/zone.dart:1804:10)
#9      runZoned (dart:async/zone.dart:1747:10)
#10     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:42:12)
#11     SubscriptionHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/subscription_handler.dart:139:25)
#12     _rootRun (dart:async/zone.dart:1399:13)
#13     _CustomZone.run (dart:async/zone.dart:1301:19)
#14     _runZoned (dart:async/zone.dart:1804:10)
#15     runZoned (dart:async/zone.dart:1747:10)
#16     SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:11)
<asynchronous suspension>
#17     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:305:11)
<asynchronous suspension>
```

Suspicious culprit: https://github.com/flutter/cocoon/pull/3060 /cc @drewroengoogle

**Comment by drewroengoogle** [comment]
This should be resolved with https://github.com/flutter/cocoon/commit/1fa2c4671ad9188e1b2caf07935a819b6146b5e5, but I will close once I confirm after the next deployment :)

**Comment by ricardoamador** [comment]
This has been resolved.
