### ISSUE TITLE
FloatingActionButton should report more clearly when it is used more than once on a page

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#13477]
I have a PageView, I call the following in two of the pages:
```dart
Navigator.of(context).pushNamed("/profile");
```
the first page brings up a black screen, but the second page brings it correctly.

Video: https://youtu.be/X7NL8AHbNzk
_

```
PS> flutter --version
Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision e8aa40eddd (8 weeks ago) • 2017-10-17 15:42:40 -0700
Engine • revision 7c4142808c
Tools • Dart 1.25.0-dev.11.0

```

**Comment by p30arena** [comment]
Ok, I found the source of the problem:

I use two FloatingActionButton
when I remove them, the black screen is gone.

is i a BUG?

**Comment by p30arena** [comment]
This is the replacement for FloatingActionButton borrowed from source code:

```

import 'package:flutter/material.dart';

import 'package:flutter/foundation.dart';
//import 'package:flutter/widgets.dart';

const double _kSize = 56.0;
const double _kSizeMini = 40.0;

class CircleButton extends StatefulWidget {
  CircleButton({
    Key key,
    this.child,
    this.backgroundColor,
    this.elevation: 6.0,
    this.highlightElevation: 12.0,
    @required this.onPressed,
    this.mini: false,
  })
      : super(key: key);

  final Widget child;
  final Color backgroundColor;
  final double elevation;
  final double highlightElevation;
  final bool mini;
  final VoidCallback onPressed;

  @override
  CircleButtonState createState() => new CircleButtonState();
}

class CircleButtonState extends State<CircleButton> {
  bool _highlight = false;

  void _handleHighlightChanged(bool value) {
    setState(() {
      _highlight = value;
    });
  }

  @override
  Widget build(BuildContext context) {
    Color iconColor = Colors.white;
    Color materialColor = widget.backgroundColor;

    Widget result;

    if (widget.child != null) {
      result = new Center(
        child: IconTheme.merge(
          data: new IconThemeData(color: iconColor),
          child: widget.child,
        ),
      );
    }

    result = new Material(
      color: materialColor,
      type: MaterialType.circle,
      elevation: _highlight ? widget.highlightElevation : widget.elevation,
      child: new Container(
        width: widget.mini ? _kSizeMini : _kSize,
        height: widget.mini ? _kSizeMini : _kSize,
        child: new InkWell(
          onTap: widget.onPressed,
          onHighlightChanged: _handleHighlightChanged,
          child: result,
        ),
      ),
    );

    return result;
  }
}

```

**Comment by Hixie** [comment]
Are there any messages in the console?

**Comment by Hixie** [comment]
Are you testing in release mode or debug mode?

**Comment by p30arena** [comment]
@Hixie 
It is in debug mode.


```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\app-debug.apk (23.0MB).
I/FlutterActivityDelegate( 4098): onResume setting current activity to this
I/flutter ( 4098): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4098): The following assertion was thrown during a scheduler callback:
I/flutter ( 4098): There are multiple heroes that share the same tag within a subtree.
I/flutter ( 4098): Within each subtree for which heroes are to be animated (typically a PageRoute subtree), each Hero
I/flutter ( 4098): must have a unique non-null tag.
I/flutter ( 4098): In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
I/flutter ( 4098): Here is the subtree for one of the offending heroes:
I/flutter ( 4098): # Hero(tag: <default FloatingActionButton tag>, state: _HeroState#21a61)
I/flutter ( 4098): # └KeyedSubtree-[GlobalKey#9f57b]
I/flutter ( 4098): #  └Material(type: circle, elevation: 6.0, color: Color(0xffff9800), state: _MaterialState#95a31)
I/flutter ( 4098): #   └AnimatedPhysicalModel(duration: 200ms, shape: circle, borderRadius: BorderRadius.zero, elevation: 6.0, color: Color(0xffff9800), animateColor: false, shadowColor: Color(0xff000000), animateShadowColor: true, state: _AnimatedPhysicalModelState#7431d(ticker inactive))
I/flutter ( 4098): #    └PhysicalModel(shape: circle, borderRadius: BorderRadius.zero, elevation: 6.0, color: Color(0xffff9800), shadowColor: Color(0xff000000), renderObject: RenderPhysicalModel#c7b3a relayoutBoundary=up9)
I/flutter ( 4098): #     └NotificationListener<LayoutChangedNotification>
I/flutter ( 4098): #      └_InkFeatures-[GlobalKey#5ba91 ink renderer](renderObject: _RenderInkFeatures#d5bd1 relayoutBoundary=up10)
I/flutter ( 4098): #       └AnimatedDefaultTextStyle(duration: 200ms, debugLabel: blackMountainView body1 < englishLike body1, inherit: false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, state: _AnimatedDefaultTextStyleState#04a86(ticker inactive))
I/flutter ( 4098): #        └DefaultTextStyle(debugLabel: blackMountainView body1 < englishLike body1, inherit: false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none)
I/flutter ( 4098): #         └Container(constraints: BoxConstraints(w=56.0, h=56.0))
I/flutter ( 4098): #          └ConstrainedBox(BoxConstraints(w=56.0, h=56.0), renderObject: RenderConstrainedBox#2d18d relayoutBoundary=up11)
I/flutter ( 4098): #           └InkWell(gestures: [tap], clipped to BoxShape.rectangle, state: _InkResponseState<InkResponse>#203ae)
I/flutter ( 4098): #            └GestureDetector
I/flutter ( 4098): #             └RawGestureDetector(state: RawGestureDetectorState#5a440(gestures: [tap], behavior: opaque))
I/flutter ( 4098): #              └_GestureSemantics(renderObject: RenderSemanticsGestureHandler#69569)
I/flutter ( 4098): #               └Listener(listeners: [down], behavior: opaque, renderObject: RenderPointerListener#75f24)
I/flutter ( 4098): #                └Center(alignment: Alignment.center, renderObject: RenderPositionedBox#303c6)
I/flutter ( 4098): #                 └Builder
I/flutter ( 4098): #                  └IconTheme(color: Color(0xffffffff))
I/flutter ( 4098): #                   └Icon(IconData(U+0E625))
I/flutter ( 4098): #                    └Semantics(container: false, properties: SemanticsProperties#a602f, label: null, value: null, hint: null, renderObject: RenderSemanticsAnnotations#e171b relayoutBoundary=up1)
I/flutter ( 4098): #                     └ExcludeSemantics(excluding: true, renderObject: RenderExcludeSemantics#2a571 relayoutBoundary=up2)
I/flutter ( 4098): #                      └SizedBox(width: 24.0, height: 24.0, renderObject: RenderConstrainedBox#d8923 relayoutBoundary=up3)
I/flutter ( 4098): #                       └Center(alignment: Alignment.center, renderObject: RenderPositionedBox#5e9fb)
I/flutter ( 4098): #                        └RichText(textDirection: rtl, softWrap: wrapping at box width, maxLines: unlimited, text: "", renderObject: RenderParagraph#e26a7 relayoutBoundary=up1)
I/flutter ( 4098): When the exception was thrown, this was the stack:
I/flutter ( 4098): #0      Hero._allHeroesFor.visitor.<anonymous closure> (package:flutter/src/widgets/heroes.dart:128)
I/flutter ( 4098): #1      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:138)
I/flutter ( 4098): #2      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #3      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #4      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4620)
I/flutter ( 4098): #5      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #6      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4620)
I/flutter ( 4098): #7      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #9      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #11     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #13     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #14     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #15     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #17     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #19     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #21     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #23     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #25     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #27     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #28     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #29     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #31     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #33     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #34     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4620)
I/flutter ( 4098): #35     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #36     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4620)
I/flutter ( 4098): #37     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #39     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #41     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #43     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #45     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #47     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #49     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #51     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #52     List.forEach (dart:core-patch/dart:core/growable_array.dart:270)
I/flutter ( 4098): #53     SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:866)
I/flutter ( 4098): #54     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #55     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4620)
I/flutter ( 4098): #56     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #57     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #58     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #59     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #60     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #61     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #62     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #63     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #64     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #66     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #67     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #68     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #69     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #70     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #71     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #72     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #74     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #75     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #76     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #78     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #80     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #81     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #82     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #84     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #86     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #87     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4620)
I/flutter ( 4098): #88     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #89     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #90     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #92     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #93     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #94     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #96     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #97     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4520)
I/flutter ( 4098): #98     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #99     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #100    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #102    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #103    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #104    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #105    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #106    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #108    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #109    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #110    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #111    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #112    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #114    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:142)
I/flutter ( 4098): #115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3580)
I/flutter ( 4098): #116    Element.visitChildElements (package:flutter/src/widgets/framework.dart:2592)
I/flutter ( 4098): #117    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:144)
I/flutter ( 4098): #118    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:508)
I/flutter ( 4098): #119    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:490)
I/flutter ( 4098): #120    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713)
I/flutter ( 4098): #121    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:657)
I/flutter ( 4098): #122    _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:113)
I/flutter ( 4098): #123    _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:102)
I/flutter ( 4098): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by p30arena** [comment]
@Hixie 
I don't use hero tags anywhere in my code.

**Comment by p30arena** [comment]
@Hixie 
I think that's because I'm using Two FloatingActionButtons.
I have to assign a unique hero tag to each one.

BUT I don't need the Hero Animation.
_
suggestions?
_

**Comment by Hixie** [comment]
Ah, interesting. Yes, that will do it.
The FloatingActionButton isn't expected to be used more than once per page (doing so violates the Material design guidelines). See https://master-docs-flutter-io.firebaseapp.com/flutter/material/FloatingActionButton-class.html (third paragraph).

We should make that clearer though.

**Comment by fukemy** [comment]
i didnt use floatingacitonbutton, but I got same problem

**Comment by bizz84** [comment]
@Hixie I just had the same problem. 

I believe the problem appears as long as there are two `FloatingActionButtons` in the affected path of the widget tree.

In my case I have page A and page B, both containing a `FloatingActionButton`. 
Somewhere in page A I push a new `MaterialPageRoute` to show page B.

Tapping on the `FloatingActionButton` on page B causes a modal presentation like so:
```dart
    await Navigator.of(context, rootNavigator: true).push(MaterialPageRoute<void>(
          fullscreenDialog: true,
          builder: (BuildContext context) {
            return EntryPage(
              jobName: jobName,
              entry: entry,
            );
          },
        ));
```

Note the use of `Navigator.of(context, rootNavigator: true)` to get the top-most Navigator (my app has a `BottomNavigationBar` and nested navigators).

This configuration causes the same error described by @p30arena.

**Comment by timsneath** [comment]
Closing this issue for now, since it seems as if the right things are happening, at least in current builds:

The documentation for `FloatingActionButton` now has a clear warning about the results of more than one being in the tree: https://github.com/flutter/flutter/blob/007a415c2a/packages/flutter/lib/src/material/floating_action_button.dart#L44

When multiple FABs are included, the error message clearly identifies a solution (using distinct `heroTag` values), as noted [above](https://github.com/flutter/flutter/issues/13477#issuecomment-350968165).

Feel free to reopen the bug (or create a new one) if there's a different resolution that you think is required.
