### ISSUE TITLE
PathNotFoundException for flutter build ios --analyze-size

### ISSUE THREAD

**Issue by hrajwade96** [flutter/flutter#134725]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I ran flutter build ios --analyze-size in my project.
got this exception 

Oops; flutter has exited unexpectedly: "PathNotFoundException: Cannot open file, path = 'build/flutter_size_02/snapshot.arm64.json' (OS Error: No such file or directory, errno =
2)".
A crash report has been written to /Users/hrishikeshrajwade/StudioProjects/new_clone/my_app/app/my_app/flutter_02.log.

### Expected results

it is expected to create json file which i can open in dev tools.

### Actual results

it is throwing exception PathNotFoundException

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
// no code req
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ios --analyze-size

## exception

PathNotFoundException: PathNotFoundException: Cannot open file, path = 'build/flutter_size_04/snapshot.arm64.json' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#8      SizeAnalyzer.analyzeAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:57:64)
#9      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:699:62)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on macOS 13.5.1 22G90 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.10.6 on channel stable at /Users/hrishikeshrajwade/Downloads/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (9 weeks ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    [32m•[39m Android SDK at /Users/hrishikeshrajwade/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 32.1.0-rc1
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E300c
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2023.1)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [32m•[39m Flutter plugin version 73.0.4
    [32m•[39m Dart plugin version 231.8109.91

[32m[✓][39m VS Code (version 1.71.2)
    [32m•[39m VS Code at /Users/hrishikeshrajwade/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (5 available)
    [32m•[39m sdk gphone64 arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    [32m•[39m Hrishikesh’s iPhone (mobile) • 00008120-000E445836FBC01E            • ios            • iOS 16.6.1 20G81
    [32m•[39m iPhone 14 Pro Max (mobile)   • F0AA0D55-4971-4D0D-B74C-73D6D4FA7B72 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    [32m•[39m macOS (desktop)              • macos                                • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    [32m•[39m Chrome (web)                 • chrome                               • web-javascript • Google Chrome 116.0.5845.140

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```
## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on macOS 13.5.1 22G90 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.10.6 on channel stable at /Users/hrishikeshrajwade/Downloads/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (9 weeks ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    [32m•[39m Android SDK at /Users/hrishikeshrajwade/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 32.1.0-rc1
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E300c
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2023.1)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [32m•[39m Flutter plugin version 73.0.4
    [32m•[39m Dart plugin version 231.8109.91

[32m[✓][39m VS Code (version 1.71.2)
    [32m•[39m VS Code at /Users/hrishikeshrajwade/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (5 available)
    [32m•[39m sdk gphone64 arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    [32m•[39m Hrishikesh’s iPhone (mobile) • 00008120-000E445836FBC01E            • ios            • iOS 16.6.1 20G81
    [32m•[39m iPhone 14 Pro Max (mobile)   • F0AA0D55-4971-4D0D-B74C-73D6D4FA7B72 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    [32m•[39m macOS (desktop)              • macos                                • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    [32m•[39m Chrome (web)                 • chrome                               • web-javascript • Google Chrome 116.0.5845.140

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
</details>

**Comment by danagbemava-nc** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/134711. Please try https://github.com/flutter/flutter/issues/134711#issuecomment-1718960660 to see if you still face this issue on the latest version of flutter stable. 

Thank you
