### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by Tearsoul** [flutter/flutter#134851]
## Command
```
flutter --no-color attach --machine --device-id=7e09e08 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:338:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-arm64 (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.7.12 on channel stable at /Users/cross/Documents/Source/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (5 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cross/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • M2012K11AC (mobile) • 7e09e08 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)     • macos   • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64 (Rosetta)
    • Chrome (web)        • chrome  • web-javascript • Google Chrome 116.0.5845.187

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.ai_flutter
**iOS bundle identifier**: com.example.aiFlutter
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
flutter_boost-b4bb39f6a09c1cbd1f4e46dd6c1504555866b9ba
package_info_plus-1.4.3+1
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-2.1.0
path_provider-2.0.15
path_provider_android-2.0.11
path_provider_foundation-2.2.4
path_provider_linux-2.1.11
path_provider_windows-2.1.7
permission_handler-9.0.2
shared_preferences-2.2.1
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.1
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.1
sqflite-2.0.2
video_player-2.7.1
video_player_android-2.4.10
video_player_avfoundation-2.4.10
video_player_web-2.0.17
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by iapicca** [comment]
> Flutter (Channel stable, 3.7.12 [...]

did you try upgrading to the latest stable?
if it's a bug may have been already fixed

**Comment by dam-ease** [comment]
Hi @Tearsoul. I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/77581
Please follow up on that issue, I'm closing the current one as a duplicate.
Thank you
