### ISSUE TITLE
[windows] pressing control key while right clicking on a SelectionArea throws failed assertion exception

### ISSUE THREAD

**Issue by PassionPenguin** [flutter/flutter#134900]
### Exception

```log
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/rendering/paragraph.dart': Failed assertion: line 1512 pos 12: 'word.start >= range.start && word.end <= range.end': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      _SelectableFragment._handleSelectWord (package:flutter/src/rendering/paragraph.dart:1512:12)
#3      _SelectableFragment.dispatchSelectionEvent (package:flutter/src/rendering/paragraph.dart:1401:18)
#4      MultiSelectableSelectionContainerDelegate.dispatchSelectionEventToChild (package:flutter/src/widgets/selectable_region.dart:2068:23)
#5      _SelectableRegionContainerDelegate.dispatchSelectionEventToChild (package:flutter/src/widgets/selectable_region.dart:1393:18)
#6      MultiSelectableSelectionContainerDelegate.handleSelectWord (package:flutter/src/widgets/selectable_region.dart:1882:9)
#7      _SelectableRegionContainerDelegate.handleSelectWord (package:flutter/src/widgets/selectable_region.dart:1334:42)
#8      MultiSelectableSelectionContainerDelegate.dispatchSelectionEvent (package:flutter/src/widgets/selectable_region.dart:2029:18)
#9      _SelectionContainerState.dispatchSelectionEvent (package:flutter/src/widgets/selection_container.dart:186:29)
#10     SelectableRegionState._selectWordAt (package:flutter/src/widgets/selectable_region.dart:863:18)
#11     SelectableRegionState._handleRightClickDown (package:flutter/src/widgets/selectable_region.dart:494:5)
#12     TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:630:79)
#13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#14     TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:630:11)
#15     BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:302:5)
#16     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279:7)
#17     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:268:25)
#18     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:248:31)
(elided 4 frames from class _AssertionError and dart:async)
Handler: "onSecondaryTapDown"
Recognizer: TapGestureRecognizer#407f4
  debugOwner: SelectableRegionState#06f15
  state: possible
  button: 2
====================================================================================================
```

### Reproducible Code

To reproduce the assertion exception, the SelectionArea should include both TextSpan and WidgetSpan. Removing the WidgetSpan below in the code will not throw any exception.

The issue was produced on both Debug and Run mode of Android Studio Flutter Plugin.

minimal reproducible code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const TMP());
}

class TMP extends StatelessWidget {
  const TMP({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: buildDefault());
  }

  Widget buildDefault() {
    return Scaffold(
        body: SelectionArea(
      child: Column(children: [
        Text.rich(TextSpan(children: [
          TextSpan(
              text:
                  "LOREM IPSUM DOABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTR"),
          WidgetSpan(
              child: MaterialButton(
            child: Text("Hello World"),
            onPressed: () {},
            color: Colors.red,
            textColor: Colors.white,
          )),
          TextSpan(
              text:
              "LOREM IPSUM DOABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTR"),
        ])),
      ]),
    ));
  }
}
```

### Flutter Doctor -v

```log
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3448], locale en-US)
    • Flutter version 3.10.6 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (10 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Hoarfroster\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code, 64-bit edition (version 1.81.0-insider)
    • VS Code at C:\Program Files\Microsoft VS Code Insiders
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • M2007J17C (mobile) • 168f8adf • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.19045.3448]
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 116.0.1938.81

[✓] Network resources
    • All expected network resources are available.
```

### Relevant issue

relevant issue: #74138 #130651 #110911

**Comment by huycozy** [comment]
Hi @PassionPenguin 
I checked this issue on the latest Flutter stable 3.13.4 but can't reproduce it. Can you upgrade to that version and confirm?

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.13.4, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
    • Flutter version 3.13.4 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (2 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.82.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.180
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-14.0.pre.309, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
    • Flutter version 3.14.0-14.0.pre.309 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current
      Flutter SDK checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK
      checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b540a87f1 (80 minutes ago), 2023-09-15 13:39:30 +0900
    • Engine revision 45bc4307cd
    • Dart version 3.2.0 (build 3.2.0-162.0.dev)
    • DevTools version 2.28.0-dev.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.82.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 116.0.5845.180
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>
