### ISSUE TITLE
After Turning On Windows 11 Developer Mode

### ISSUE THREAD

**Issue by khmuzo** [flutter/flutter#134929]
I was working fine using windows 11 and flutter to preview the app I'm developing. As I'm new to this I'm not sure what change i made to my system but after using my physical phone as an emulator when i wanted to switch over to desktop again, i was instructed to turn on Developer Mode. after doing this I'm getting the following error:

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 195 pos 12: '!_debugDuringDeviceUpdate': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:195:12)
#3      MouseTracker.updateAllDevices (package:flutter/src/rendering/mouse_tracker.dart:352:5)
#4      RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure> (package:flutter/src/rendering/binding.dart:375:22)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1223:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#8      _invoke (dart:ui/hooks.dart:142:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#10     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```
I'm grateful for any and all help you can give. Thanks

**Comment by lyskouski** [comment]
Assume, it's similar to the mine - https://github.com/flutter/flutter/pull/134409

**Comment by darshankawar** [comment]
@khmuzo 
Based on the error log provided, it seems similar to https://github.com/flutter/flutter/issues/84241, so please follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
