### ISSUE TITLE
LocalAuth plugin needs to guard against duplicate replies

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#13506]
Leafy has been seeing exceptions of this kind sporadically:

```
java.lang.IllegalStateException
	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:132)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
	at io.flutter.plugins.localauth.LocalAuthPlugin$1.onFailure(LocalAuthPlugin.java:56)
	at io.flutter.plugins.localauth.AuthenticationHelper.stop(AuthenticationHelper.java:146)
	at io.flutter.plugins.localauth.AuthenticationHelper.access$000(AuthenticationHelper.java:36)
	at io.flutter.plugins.localauth.AuthenticationHelper$2.onClick(AuthenticationHelper.java:234)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
```

The exceptions always come from the same line (User tapping cancel button on the dialog). We could not reproduce this exception unfortunately. So we have to guard against a flow that we do not fully understand. Luckily the reasoning is simple: If we have `stop()`ped before, do not stop again. Other plugins implement similar logic (such as google_sign_in).

**Comment by mehmetf** [comment]
I was able to reproduce this. Basically if the user clicks cancel while scanning his finger, we can run into this situation. We produce success and failure messages in random order. In this degenerate case, we should allow only one of them to win.
