### ISSUE TITLE
`Image.toByteData` throws when the app goes to background

### ISSUE THREAD

**Issue by ggirotto** [flutter/flutter#135245]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Download the example project
2. Tap the + button and minimize the app immediately
3. The error will be thrown once the Timer fires

### Expected results

It wouldn't throw, just return an empty byte array or something like that

### Actual results

The app throws.

### Code sample

[bug.zip](https://github.com/flutter/flutter/files/12690683/bug.zip)

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/11745745/c9eabacc-12c1-4395-87f6-45351cb59298

</details>

### Logs

<details><summary>Logs</summary>

```console
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1959:25)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-BR)
    • Flutter version 3.13.4 on channel stable at /Users/guilhermegirotto/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (9 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/guilhermegirotto/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • Girotto iPhone (mobile) • 00008120-000130EE21B8C01E            • ios            • iOS 16.6.1 20G81
    • iPhone 15 Pro (mobile)  • 842308C5-D48F-47C0-9BD0-63841A67FB31 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Brave Browser 117.1.58.127
    ! Error: Guilherme’s Apple Watch needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ggirotto** [comment]
This issue is very critic IMO because it's not possible to avoid it by using `try catch` or any mechanism (if it's, please let me know). This is polluting a lot our crash log dashboard

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample shared above. This seems to be an issue with impeller as I could not reproduce with skia. 

I added a few logs to show the timeline of events. 

<details>
<summary>updated code</summary>

```dart
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeAppLifecycleState(ui.AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);

    print("[${DateTime.now()}] state is now: $state");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('You have pushed the button this many times:'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          print("[${DateTime.now()}] button clicked");
          Future.delayed(Duration(seconds: 5), () async {
            await _getBytesFromAsset('images/pin.png');
          });
        },
        tooltip: 'Bug',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Future<Uint8List> _getBytesFromAsset(String path) async {
    final data = await rootBundle.load(path);
    final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
    final fi = await codec.getNextFrame();
    final byteData = await fi.image.toByteData(format: ui.ImageByteFormat.png);
    if (byteData != null) return byteData.buffer.asUint8List();
    return Uint8List(0);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
}

```
</details>

<details>
<summary>logs</summary>

### Impeller

```
Launching lib/main.dart on Nexus in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Xcode build done.                                           23.8s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
The Dart VM Service was not discovered after 60 seconds. This is taking much longer than expected...
Open the Xcode window the project is opened in to ensure the app is running. If the app is not running, try selecting "Product > Run" to fix the problem.

[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
flutter: [2023-09-22 08:49:57.913177] button clicked
flutter: [2023-09-22 08:49:58.764372] state is now: AppLifecycleState.inactive
flutter: [2023-09-22 08:49:59.560780] state is now: AppLifecycleState.hidden
flutter: [2023-09-22 08:49:59.560968] state is now: AppLifecycleState.paused
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1961:25)
flutter: [2023-09-22 08:50:08.090296] state is now: AppLifecycleState.hidden
flutter: [2023-09-22 08:50:08.090686] state is now: AppLifecycleState.inactive
flutter: [2023-09-22 08:50:08.549380] state is now: AppLifecycleState.resumed
Application finished.

Exited.
```

### SKIA

```
Launching lib/main.dart on Nexus in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         5.4s
Xcode build done.                                           25.0s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Installing and launching...                                        20.3s
Syncing files to device Nexus...                                   485ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Nexus is available at: http://127.0.0.1:53413/Py6KB7xXJVE=/
The Flutter DevTools debugger and profiler on Nexus is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:53413/Py6KB7xXJVE=/
flutter: [2023-09-22 08:47:27.055943] button clicked
flutter: [2023-09-22 08:47:27.722331] state is now: AppLifecycleState.inactive
flutter: [2023-09-22 08:47:28.540126] state is now: AppLifecycleState.hidden
flutter: [2023-09-22 08:47:28.540277] state is now: AppLifecycleState.paused
flutter: [2023-09-22 08:47:44.758269] state is now: AppLifecycleState.hidden
flutter: [2023-09-22 08:47:44.758801] state is now: AppLifecycleState.inactive
flutter: [2023-09-22 08:47:45.073173] state is now: AppLifecycleState.resumed
Application finished.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB)
    • Flutter version 3.13.5 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (3 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.0 21A329
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.0 21A329
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
 
```
[!] Flutter (Channel master, 3.15.0-6.0.pre.3, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB)
    • Flutter version 3.15.0-6.0.pre.3 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 07cc3f7a61 (27 hours ago), 2023-09-21 07:54:19 +0200
    • Engine revision 3e66ffa6aa
    • Dart version 3.2.0 (build 3.2.0-185.0.dev)
    • DevTools version 2.28.0-dev.12
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.0 21A329
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.0 21A329
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by jonahwilliams** [comment]
The crash is caused by us not returning an error string from the impeller encoder when toByteData fails, which dart:ui intereprets as a success and uses a `!` on a null object.

**Comment by jonahwilliams** [comment]
We don't have any mechanism for the rendering backend to return errors: https://github.com/flutter/engine/blob/main/lib/ui/painting/image_encoding.cc#L165

**Comment by chinmaygarde** [comment]
So the issue is that the error is not being propagated. And not something about actually attempting to access the GPU from the background right?

**Comment by jonahwilliams** [comment]
Yes

**Comment by utkarsh1097** [comment]
If `Image.toByteData` is failing for Impeller but not for Skia when the app goes to the background, this could either be due to how the two engines fundamentally work under the hood (I don't know the working details) or it is a bug. 

In case it is decided that propagating the exception to Flutter is a fix, I think it will be nice if we document this somewhere that the developer should "retry" this step when the app comes to the foreground. 

For example, one can use `AppLifecycleState.resumed` as a workaround for this.

**Comment by gaaclarke** [comment]
This is returning null because the sync switch is failing at https://github.com/flutter/engine/blob/d379d53b8ab1f53244cce9fc6e9918bbdd18ecd6/lib/ui/painting/image_encoding_impeller.cc#L66

The GPU is needed because the `DlImage::impeller_texture` is returning a texture that is `kDevicePrivate`, `ImageEncodingImpeller::ConvertDlImageToSkImage` will draw it to an offscreen buffer to access the pixels from the CPU.   If those textures were host visible we wouldn't need access to the GPU.

That texture is `MTLStorageModePrivate` because of `ImageDecoderImpeller::Decode` calls `ImageDecoderImpeller::UploadTextureToPrivate` which can operate safely without the gpu, but creates a private texture.

Switching to host visible unequivocally would have performance ramifications but would allow us to access the pixels from the background.

**Comment by gaaclarke** [comment]
I chatted with the team a bit and there isn't a good criteria for deciding if a `dart:ui/Image` should be backed with a host visible texture.  The problem isn't just render performance, which may be acceptable, but memory size which is less acceptable.

The reproduction is a bit contrived but I think for a portion of users that are running into this, their best bet would be to avoid using the `dart:ui` package to decode images.  Instead they should be using something like the `image` package.

Even if we implemented host visible textures, it wouldn't be possible to use on all setups, like where host visible textures aren't available (all? discrete gpus).  So, we'd still have to handle the error case.

**Comment by gaaclarke** [comment]
@dnfield had a good suggestion that instead of making this now start returning an error, we manage the retries in the engine.  The limitations on accessing texture memory aren't the most obvious to how the API looks or how I suspect most people are using it.  Especially considering how it behaved with Skia.
