### ISSUE TITLE
[iOS] Flutter run throws Runner quit unexpectedly after upgrading Xcode and Simulator

### ISSUE THREAD

**Issue by afnx** [flutter/flutter#135208]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Upgrade Xcode, Simulator, and Flutter to the latest versions.
2. Download and install iOS 14 on Xcode.
3. Create and open a Simulator with iOS 14.
4. Run the app: `futter run`

### Expected results

Should be able to run the app on iOS 14/15/16/17 without any crashing.

### Actual results

Currently not able to run the app on iOS 14 at all. Throws a "Runner quit unexpectedly" and never starts the app. 

Looks like only Simulator with iOS 17 installed works, but it's extremely slow and laggy. Sometimes crashes (mostly while using the keyboard).

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

### Logs

<details><summary>The log from the console after running the app:</summary>

```console
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                       23.2s⣷
Xcode build done.                                           49.6s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
Syncing files to device iPhone 15 Pro Max...  
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91
    darwin-x64, locale en-US)
    • Flutter version 3.13.5 on channel stable at
      /Users/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (35 hours ago), 2023-09-19
      13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK
    version 33.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) •
      23231853-7B41-4390-A29A-D8E19E2041FC • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)                       • macos
      • darwin-x64     • macOS 13.5.2 22G91 darwin-x64
    • Chrome (web)                          • chrome
      • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @afnx 
Does the issue only happen on iOS 14? I don't have such version but it works normally on my iOS 15.7.2 device (XCode 15).

Please provide the entire output log of `flutter run -v` which may contain crash stack trace. Thanks!

**Comment by ChrisElliotUK** [comment]
<details>
<summary>Flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB)
    • Flutter version 3.13.5 on channel stable at /Users/christopherelliot/Develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (2 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/christopherelliot/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone (91) (mobile) • 00008110-000918AE14D0401E • ios            • iOS 17.0 21A329
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
<summary>And I get this error in Xcode after it fails to build every time</summary>

```
Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.
Domain: com.apple.dt.CoreDeviceError
Code: 1005
User Info: {
    DVTErrorCreationDateKey = "2023-09-21 14:23:27 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
    NSURL = "file:///~/Library/Developer/Xcode/DerivedData/Runner-ftlqhmisktdpoqelkcitcillumqf/Build/Products/Debug-iphoneos/Runner.app";
}

The file couldn’t be opened because it doesn’t exist.
Domain: NSCocoaErrorDomain
Code: 260
Failure Reason: The file doesn’t exist.

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPhone14,5";
    "device_osBuild" = "17.0 (21A329)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "348.1";
    "dvt_mobiledevice_version" = "1643.2.4";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 2;
    "operation_errorCode" = 260;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.1005.NSCocoaErrorDomain";
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.0";
    "sdk_osVersion" = "17.0";
    "sdk_variant" = iphoneos;
}

System Information

macOS Version 13.5.2 (Build 22G91)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-09-21T15:23:27+01:00
```

</details>

<details>
<summary>I am having an issue since upgrading to 3.13.5. This shows when I run flutter run.</summary>
```
Unexpected debug results: 
  Status: succeeded
  Completed: true
  Error Message: null
```
</details>
<details>
<summary>Further error when I run flutter run -v </summary>

```
 +466 ms] Could not run build/ios/iphoneos/Runner.app on ~~~~~~~~.
[        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Installing and launching... (completed in 10.4s)
[        ] Error launching application on iPhone (91).
[   +1 ms] "flutter run" took 84,626ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +60 ms] ensureAnalyticsSent: 57ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

**Comment by dale-lakes** [comment]
Same issue. Building and running my app directly in XCode works fine. I only run into this issue when using `flutter run`.

**Comment by huycozy** [comment]
I'm on Flutter stable channel 3.13.5, XCode 15, iOS 17.0 but can't reproduce this issue. 

>[        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace

@ChrisElliotUK Looks like your device is disconnected or something else, can you try again? Or follow the suggestion there to see if it works?

@dale-lakes Can you please share the output of `flutter run -v` and `flutter doctor -v`?

Also, the original issue is filed for iOS 14 and missing stack trace to determine the same issue. If you also see this issue on different iOS versions, please file a new issue for that. Thanks!

**Comment by afnx** [comment]
Hi @huycozy, I've been trying to install different iOS versions to check if it's the same on all. However, I couldn't install any other iOS Simulator. I had to downgrade from Xcode 15 to Xcode 14 which has built-in iOS 16.4 Simulator.

Then, I managed to run the app on iOS 16.4 using Xcode 14, and it performed as expected.

When I tried the iOS 17 Simulator again, I encountered an error when opening the keyboard: "InputUI quit unexpectedly." There was no crash stack trace in the `flutter run -v` logs. Also, the Simulator was extremely slow even before launching the app. While the app did run, it was nearly impossible to work with due to the severe lag.

I checked the Apple Developer Forum and found similar threads with complaints about the same issue. At this point, I believe this problem is more related to Xcode than Flutter.

**Comment by ChrisElliotUK** [comment]
> I'm on Flutter stable channel 3.13.5, XCode 15, iOS 17.0 but can't reproduce this issue.
> 
> > [        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
> > [        ]   open ios/Runner.xcworkspace
> 
> @ChrisElliotUK Looks like your device is disconnected or something else, can you try again? Or follow the suggestion there to see if it works?
> 
> @dale-lakes Can you please share the output of `flutter run -v` and `flutter doctor -v`?
> 
> Also, the original issue is filed for iOS 14 and missing stack trace to determine the same issue. If you also see this issue on different iOS versions, please file a new issue for that. Thanks!

My device is connected and runs perfectly when I do `product>run` from Xcode and then `flutter attach`. Not sure why flutter run doesn't seem to work.

**Comment by huycozy** [comment]
@afnx Could you try opening iOS module (in Flutter project) on XCode and retry to see if there is any crash (if there is, please share the entire trace log here that will be helpful)

>I checked the Apple Developer Forum and found similar threads with complaints about the same issue.

Can you share it here as well? 

---

>Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.

@ChrisElliotUK Regarding your initial error message at https://github.com/flutter/flutter/issues/135208#issuecomment-1729735614, it looks similar to some reports at https://github.com/flutter/flutter/issues/134667. You can follow up on it for updates or please file a separate issue if your case is not really similar to that issue.

**Comment by afnx** [comment]
@huycozy, I tried that as well. There are no crashes or logs. It gets stuck at "Running Runner on iPhone" and the Simulator only displays a white screen.

Here are some posts that I think similar:

https://developer.apple.com/forums/thread/735177
https://developer.apple.com/forums/thread/737798
https://developer.apple.com/forums/thread/737975
https://developer.apple.com/forums/thread/737471
https://developer.apple.com/forums/thread/737648
https://developer.apple.com/forums/thread/737828
https://developer.apple.com/forums/thread/737822
https://developer.apple.com/forums/thread/737689

**Comment by dale-lakes** [comment]
> 
> @dale-lakes Can you please share the output of `flutter run -v` and `flutter doctor -v`?
> 

Flutter doctor:
```bash
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
    • Flutter version 3.13.5 on channel stable at /Users/dalelakes/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (5 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dalelakes/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Users/dalelakes/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • Pixel 5a (mobile)      • 18191JECB06609            • android-arm64  • Android 13 (API 33)
    • cxx{========> (mobile) • 00008110-00146DE011E8401E • ios            • iOS 17.0 21A329
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 13.5.2 22G91
      darwin-arm64
    • Chrome (web)           • chrome                    • web-javascript • Brave Browser
      117.1.58.124

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

Flutter run verbose: https://gist.github.com/dale-lakes/24f979d8c5799255fd51c44a4fc28601

**Comment by dale-lakes** [comment]
I get the same error as @ChrisElliotUK which was marked off-topic

**Comment by huycozy** [comment]
@dale-lakes Thanks for the update. It's worth trying on XCode as well to know if you see the same error at https://github.com/flutter/flutter/issues/134667#issuecomment-1730978188. If it is, please follow up on https://github.com/flutter/flutter/issues/134667 for updates. 

@afnx Could you provide the entire output log of `flutter run -v` that may be helpful. Also, to clarify whether this issue only occurs with Flutter, could you try it on an iOS native project?
