### ISSUE TITLE
doctor issue , cannot read . system was removed form the environement variable

### ISSUE THREAD

**Issue by BRIKIAchraf** [flutter/flutter#135383]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH environment variable. Ensure that this is present and then try again after restarting the terminal and/or IDE.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:488:7)
      #2      OperatingSystemUtils.which (package:flutter_tools/src/base/os.dart:92:31)
      #3      FlutterValidator._validateSdkBinary (package:flutter_tools/src/doctor.dart:617:52)
      #4      FlutterValidator._validateRequiredBinaries (package:flutter_tools/src/doctor.dart:604:47)
      #5      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:518:7)
      #6      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:258:72)
      #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #8      _rootRun (dart:async/zone.dart:1399:13)
      #9      _CustomZone.run (dart:async/zone.dart:1301:19)
      #10     _runZoned (dart:async/zone.dart:1804:10)
      #11     runZonedGuarded (dart:async/zone.dart:1792:12)
      #12     runZoned (dart:async/zone.dart:1744:12)
      #13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:250:9)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:378:72)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:48)
      #17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1616:12)
      <asynchronous suspension>
      #18     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
      <asynchronous suspension>
      #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #20     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
      <asynchronous suspension>
      #21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
      <asynchronous suspension>
      #22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
      <asynchronous suspension>
      #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
      <asynchronous suspension>
      #25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #26     main (package:flutter_tools/executable.dart:90:3)
      <asynchronous suspension>
```
### Actual results

flutter does not work 

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
>    X Exception: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH environment variable. Ensure that this is present and then try again after restarting the terminal and/or IDE.

This looks like you have forgotten this part: [Update your path](https://docs.flutter.dev/get-started/install/windows#update-your-path). Please follow step-by-step there to see if it helps. You can also check this SO thread as well: https://stackoverflow.com/questions/49609889/flutter-doctor-doesnt-work-on-neither-command-prompt-or-powershell-window

Your question is best suited for support channels like StackOverflow, so please ask the same there for solution if any. Closing for now. If there isn't any solution that can apply to the issue, please write in comments with more information and I will re-open issue for further support. Thanks!
