### ISSUE TITLE
App Stopped - x86 release

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#13538]
App Stopped - x86 release

```
android {
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a'
            universalApk true
        }
    }
```

```
12-13 21:04:45.571 3294-3294/ir.idepm.dadshid W/System: ClassLoader referenced unknown path: /data/app/ir.idepm.dadshid-1/lib/x86
12-13 21:04:45.592 3294-3294/ir.idepm.dadshid D/AndroidRuntime: Shutting down VM
12-13 21:04:45.593 3294-3294/ir.idepm.dadshid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: ir.idepm.dadshid, PID: 3294
                                                                java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ir.idepm.dadshid-1/base.apk"],nativeLibraryDirectories=[/data/app/ir.idepm.dadshid-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                    at java.lang.System.loadLibrary(System.java:1076)
                                                                    at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:152)
                                                                    at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:137)
                                                                    at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:20)
                                                                    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                    at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by p30arena** [comment]
I can see that flutter doesn't support x86 builds right now, aren't you gonna support it anytime soon?!

**Comment by tvolkert** [comment]
Closing as a dup of https://github.com/flutter/flutter/issues/9253
