### ISSUE TITLE
Failed assertion: line 1021 pos 12: 'activity!.isScrolling': is not true.

### ISSUE THREAD

**Issue by windows7lake** [flutter/flutter#135484]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Keep dragging the tabbar in nestedScrollView
2. Switch the tabbar to refresh widget
3. After finish refreshing, it will report the error.

### Expected results

no showing error

### Actual results

report: Failed assertion: line 1021 pos 12: 'activity!.isScrolling': is not true.

### Code sample

<details><summary>Code sample</summary>

```dart

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final ScrollController topScrollController = ScrollController();
  final ScrollController nestedScrollController = ScrollController();

  int times = 10;
  Timer? timer;

  double get headerHeight =>
      MediaQuery.of(context).size.height -
      MediaQuery.of(context).padding.top -
      MediaQuery.of(context).padding.bottom -
      56 -
      100;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("NestedScrollView Demo")),
      body: NestedScrollView(
        controller: nestedScrollController,
        headerSliverBuilder: (context, innerBoxIsScrolled) {
          return [
            SliverToBoxAdapter(
              child: Listener(
                onPointerDown: (details) {
                  print("onPanStart");
                },
                onPointerUp: (details) {
                  print("onPanEnd");
                },
                onPointerMove: (details) {
                  print("onPointerMove: ${details.delta.dy}");
                  if (topScrollController.offset >=
                          topScrollController.position.maxScrollExtent &&
                      details.delta.dy < 0) {
                    nestedScrollController.animateTo(
                      headerHeight,
                      duration: const Duration(milliseconds: 200),
                      curve: Curves.easeInOut,
                    );
                  }
                },
                child: ConstrainedBox(
                  constraints: BoxConstraints(
                    maxHeight: headerHeight,
                  ),
                  child: ListView.builder(
                    controller: topScrollController,
                    itemBuilder: (context, index) {
                      return ListTile(
                        title: Text("Item $index"),
                      );
                    },
                    itemCount: 20,
                  ),
                ),
              ),
            ),
          ];
        },
        body: DefaultTabController(
          length: 2,
          child: Column(
            children: [
              TabBar(
                tabs: const [Tab(text: "Tab1"), Tab(text: "Tab2")],
                onTap: (index) {
                  times = 3;
                  setState(() {});
                  timer = Timer.periodic(
                    const Duration(milliseconds: 1000),
                    (_) {
                      print("times: $times");
                      if (--times <= 0) {
                        timer?.cancel();
                        setState(() {});
                      }
                    },
                  );
                },
              ),
              Expanded(
                child: times <= 0
                    ? ListView.builder(
                        shrinkWrap: true,
                        itemBuilder: (context, index) {
                          return ListTile(
                            title: Text("Item $index"),
                          );
                        },
                        itemCount: 20,
                      )
                    : Container(
                        width: double.infinity,
                        height: 1000,
                        color: Colors.grey.shade400,
                        alignment: Alignment.center,
                        child: const Text(
                          "Loading...",
                          style: TextStyle(
                            fontSize: 20,
                            color: Colors.white,
                          ),
                        ),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Video](https://github.com/flutter/flutter/assets/10578898/58b2b273-8e35-47d3-8a92-d9cc3e1b10f9)

</details>

### Logs

<details><summary>Logs</summary>

```console
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 1021 pos 12: 'activity!.isScrolling': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:1021:12)
#3      _NestedScrollPosition.applyFullDragUpdate (package:flutter/src/widgets/nested_scroll_view.dart:1318:7)
#4      _NestedScrollCoordinator.applyUserOffset (package:flutter/src/widgets/nested_scroll_view.dart:1105:31)
#5      ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:385:14)
#6      ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:811:12)
#7      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:550:55)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#9      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:550:7)
#10     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:391:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#23     _invoke1 (dart:ui/hooks.dart:186:13)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
(elided 2 frames from class _AssertionError)
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#6a6bf
  start behavior: start
====================================================================================================

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.2.1 22D68 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.13.3 on channel stable at /Users/10733/fvm/versions/3.13.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (3 weeks ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/10733/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • MEIZU 18 (mobile)           • 181QGFYA225DE • android-arm64  • Android 13 (API 33)
    • Pixel 3 XL (mobile)         • 89SY0B6DE     • android-arm64  • Android 12 (API 31)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @windows7lake. Thanks for filing this. I tried reproducing this on the latest stable version but can't reproduce. Are you able to upgrade to the latest versions to check if this issue persists?

https://github.com/flutter/flutter/assets/53122008/81389c16-7029-4dba-a9b2-86efabeb163e

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.5 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (6 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro Max (mobile)      • BB55E997-7F31-462D-B3B1-6B177D9B40C7 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPad (10th generation) (mobile) • 5B1DA2B3-69EC-435B-95F8-550B7F3A9FBB •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by yakagami** [comment]
@dam-ease I am on the latest version. The issue is with zooming, not scrolling as in your video.
