### ISSUE TITLE
Context lost for Focus Node

### ISSUE THREAD

**Issue by NeelM19** [flutter/flutter#135419]
```dart
import 'package:flutter/material.dart';

class NewCompetitionSecondPage extends StatefulWidget {
  final TextEditingController locationController;
  final TextEditingController countryController;
  final FocusNode locationFocus;
  final FocusNode countryFocus;
 
  
  NewCompetitionSecondPage({
    super.key,
    required this.locationController,
    required this.countryController,
  });

  @override
  State<NewCompetitionSecondPage> createState() =>
      _NewCompetitionSecondPageState();
}

class _NewCompetitionSecondPageState extends State<NewCompetitionSecondPage> {

  @override
  void initState() {
    super.initState();
    widget.locationFocus.attach(context);
    widget.countryFocus.attach(context);
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: EdgeInsets.only(bottom: PointSize.value24),
          child: CommonTextFieldWithTitle(
            inputAction: TextInputAction.next,
            textInputType: TextInputType.text,
            title: SFLStrings.label.kLocation,
            controller: widget.locationController,
            focusNode: widget.locationFocus,
            checkValidator: (val) {
              return Utilities.validateCompetitionLocation(val);
            },
            onSubmitted: (term) {
              Utilities.fieldFocusChange(
                  context, widget.locationFocus, widget.countryFocus);
              return null;
            },
          ),
        ),
        Padding(
                padding: EdgeInsets.only(bottom: PointSize.value24),
                child: CommonTextFieldWithTitle(
                  inputAction: TextInputAction.next,
                  textInputType: TextInputType.text,
                  title: SFLStrings.label.kCountry,
                  controller: widget.countryController,
                  focusNode: widget.countryFocus,
                  checkValidator: (val) {
                    return Utilities.validateCountryName(val);
                  },
                  onSubmitted: (term) {
                    Utilities.fieldFocusChange(
                        context, widget.countryFocus, widget.stateFocus);
                    return null;
                  },
                ),
              ),
            ),
            
  }

``` 

> I am getting the following error

```
Exception caught by services library ======================================================
The following assertion was thrown during method call TextInputClient.performAction:
Tried to get the bounds of a focus node that didn't have its context set yet.
The context needs to be set before trying to evaluate traversal policies. Setting the context is typically done with the attach method.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 790 pos 7: 'context != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      FocusNode.rect (package:flutter/src/widgets/focus_manager.dart:790:7)
#3      new _ReadingOrderSortData (package:flutter/src/widgets/focus_traversal.dart:872:21)
#4      ReadingOrderTraversalPolicy.sortDescendants (package:flutter/src/widgets/focus_traversal.dart:1115:49)
#5      FocusTraversalPolicy._sortAllDescendants (package:flutter/src/widgets/focus_traversal.dart:333:65)
#6      FocusTraversalPolicy._moveFocus (package:flutter/src/widgets/focus_traversal.dart:406:41)
#7      FocusTraversalPolicy.next (package:flutter/src/widgets/focus_traversal.dart:238:39)
#8      FocusNode.nextFocus (package:flutter/src/widgets/focus_manager.dart:1136:56)
#9      EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:2757:30)
#10     EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:2618:9)
#11     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:37)
#12     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20)
#13     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555:55)
#14     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548:34)
#15     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#16     _invoke2 (dart:ui/hooks.dart:183:13)
#17     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#18     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#19     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#20     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#21     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 2 frames from class _AssertionError)
call: MethodCall(TextInputClient.performAction, [6, TextInputAction.next])
```

**Comment by dam-ease** [comment]
Hi @NeelM19  
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code (a single `main.dart` file)
- The output of flutter doctor -v
- Reproduction steps

Thank you!
