### ISSUE TITLE
[go_router_builder] Runtime exception when using required extra with a nullable named record field. 

### ISSUE THREAD

**Issue by rubenferreira97** [flutter/flutter#135591]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the code sample example (tweaked the `extra_example` to reproduce the bug).

### Expected results

Check the generated code:

```dart
  static RequiredExtraRoute _fromState(GoRouterState state) =>
      RequiredExtraRoute(
        $extra: state.extra as List<({int id, String name})>,
      );
```
Should be:

```dart
  static RequiredExtraRoute _fromState(GoRouterState state) =>
      RequiredExtraRoute(
        $extra: state.extra as List<({int id, String? name})>,
      );
```

### Actual results

When try to call `.go` the following runtime exception appears:

> ════════ Exception caught by foundation library ════════════════════════════════
> type 'List<({int id, String? name})>' is not a subtype of type 'List<({int id, String name})>' in type cast
> ═════════════════════════════════════════════════════════════════

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'extra_example.g.dart';

void main() => runApp(const App());

final GoRouter _router = GoRouter(
  routes: $appRoutes,
  initialLocation: '/splash',
);

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

typedef Extra = List<({int id, String? name})>;

@TypedGoRoute<RequiredExtraRoute>(path: '/requiredExtra')
class RequiredExtraRoute extends GoRouteData {
  const RequiredExtraRoute({required this.$extra});

  final Extra $extra;

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      RequiredExtraScreen(extra: $extra);
}

class RequiredExtraScreen extends StatelessWidget {
  const RequiredExtraScreen({super.key, required this.extra});

  final Extra extra;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Required Extra')),
      body: Center(child: Text('Extra: $extra')),
    );
  }
}

@TypedGoRoute<OptionalExtraRoute>(path: '/optionalExtra')
class OptionalExtraRoute extends GoRouteData {
  const OptionalExtraRoute({this.$extra});

  final Extra? $extra;

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      OptionalExtraScreen(extra: $extra);
}

class OptionalExtraScreen extends StatelessWidget {
  const OptionalExtraScreen({super.key, this.extra});

  final Extra? extra;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Optional Extra')),
      body: Center(child: Text('Extra: $extra')),
    );
  }
}

@TypedGoRoute<SplashRoute>(path: '/splash')
class SplashRoute extends GoRouteData {
  const SplashRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) => const Splash();
}

class Splash extends StatelessWidget {
  const Splash({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Splash')),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          const Placeholder(),
          ElevatedButton(
            onPressed: () =>
                const RequiredExtraRoute($extra: [(id: 1, name: 'test1')])
                    .go(context),
            child: const Text('Required Extra'),
          ),
          ElevatedButton(
            onPressed: () =>
                const OptionalExtraRoute($extra: [(id: 2, name: 'test2')])
                    .go(context),
            child: const Text('Optional Extra'),
          ),
          ElevatedButton(
            onPressed: () => const OptionalExtraRoute().go(context),
            child: const Text('Optional Extra (null)'),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22621.2283], locale pt-PT)
    • Flutter version 3.13.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (8 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at C:\Users\Eu\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0-rc2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.82.2)
    • VS Code at C:\Users\Eu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (4 available)
    • Redmi Note 9S (mobile) • 14f27be • android-arm64  • Android 12 (API 31)
    • Windows (desktop)      • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)           • chrome  • web-javascript • unknown
    • Edge (web)             • edge    • web-javascript • Microsoft Edge 117.0.2045.43

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample shared above. 

<details>
<summary>generated code</summary>

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'main.dart';

// **************************************************************************
// GoRouterGenerator
// **************************************************************************

List<RouteBase> get $appRoutes => [
      $requiredExtraRoute,
      $optionalExtraRoute,
      $splashRoute,
    ];

RouteBase get $requiredExtraRoute => GoRouteData.$route(
      path: '/requiredExtra',
      factory: $RequiredExtraRouteExtension._fromState,
    );

extension $RequiredExtraRouteExtension on RequiredExtraRoute {
  static RequiredExtraRoute _fromState(GoRouterState state) =>
      RequiredExtraRoute(
        $extra: state.extra as List<({int id, String name})>,
      );

  String get location => GoRouteData.$location(
        '/requiredExtra',
      );

  void go(BuildContext context) => context.go(location, extra: $extra);

  Future<T?> push<T>(BuildContext context) =>
      context.push<T>(location, extra: $extra);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location, extra: $extra);

  void replace(BuildContext context) =>
      context.replace(location, extra: $extra);
}

RouteBase get $optionalExtraRoute => GoRouteData.$route(
      path: '/optionalExtra',
      factory: $OptionalExtraRouteExtension._fromState,
    );

extension $OptionalExtraRouteExtension on OptionalExtraRoute {
  static OptionalExtraRoute _fromState(GoRouterState state) =>
      OptionalExtraRoute(
        $extra: state.extra as List<({int id, String? name})>?,
      );

  String get location => GoRouteData.$location(
        '/optionalExtra',
      );

  void go(BuildContext context) => context.go(location, extra: $extra);

  Future<T?> push<T>(BuildContext context) =>
      context.push<T>(location, extra: $extra);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location, extra: $extra);

  void replace(BuildContext context) =>
      context.replace(location, extra: $extra);
}

RouteBase get $splashRoute => GoRouteData.$route(
      path: '/splash',
      factory: $SplashRouteExtension._fromState,
    );

extension $SplashRouteExtension on SplashRoute {
  static SplashRoute _fromState(GoRouterState state) => const SplashRoute();

  String get location => GoRouteData.$location(
        '/splash',
      );

  void go(BuildContext context) => context.go(location);

  Future<T?> push<T>(BuildContext context) => context.push<T>(location);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location);

  void replace(BuildContext context) => context.replace(location);
}

```
</details>

<details>
<summary>logs</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following _TypeError was thrown while dispatching notifications for GoRouteInformationProvider:
flutter: type 'List<({int id, String? name})>' is not a subtype of type 'List<({int id, String name})>' in
flutter: type cast
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      $RequiredExtraRouteExtension._fromState (package:hx/main.g.dart:23:29)
flutter: #1      GoRouteData.$route.factoryImpl (package:go_router/src/route_data.dart:97:53)
flutter: #2      GoRouteData.$route.redirect (package:go_router/src/route_data.dart:107:9)
flutter: #3      RouteConfiguration._getRouteLevelRedirect (package:go_router/src/configuration.dart:464:44)
flutter: #4      RouteConfiguration.redirect.processRedirect.processTopLevelRedirect (package:go_router/src/configuration.dart:422:13)
flutter: #5      RouteConfiguration.redirect.processRedirect (package:go_router/src/configuration.dart:438:16)
flutter: #6      RouteConfiguration.redirect (package:go_router/src/configuration.dart:444:14)
flutter: #7      GoRouteInformationParser._redirect (package:go_router/src/parser.dart:154:10)
flutter: #8      GoRouteInformationParser.parseRouteInformationWithDependencies (package:go_router/src/parser.dart:95:32)
flutter: #9      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:741:8)
flutter: #10     _RouterState._handleRouteInformationProviderNotification (package:flutter/src/widgets/router.dart:759:5)
flutter: #11     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
flutter: #12     GoRouteInformationProvider.notifyListeners (package:go_router/src/information_provider.dart:147:11)
flutter: #13     GoRouteInformationProvider._setValue (package:go_router/src/information_provider.dart:155:7)
flutter: #14     GoRouteInformationProvider.go (package:go_router/src/information_provider.dart:177:5)
flutter: #15     GoRouter.go (package:go_router/src/router.dart:342:30)
flutter: #16     GoRouterHelper.go (package:go_router/src/misc/extensions.dart:25:25)
flutter: #17     $RequiredExtraRouteExtension.go (package:hx/main.g.dart:30:44)
flutter: #18     Splash.build.<anonymous closure> (package:hx/main.dart:98:22)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.6 22G120 darwin-arm64, locale en-GB)
    • Flutter version 3.13.5 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (8 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 13 (API 33)
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.0.1 21A340
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 117.0.5938.92
    ! Error: Browsing on the local area network for Nexus. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.15.0-10.0.pre.12, on macOS 13.6 22G120 darwin-arm64, locale en-GB)
    • Flutter version 3.15.0-10.0.pre.12 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bea63d7c81 (13 hours ago), 2023-09-26 20:46:25 -0400
    • Engine revision 0a8ad236e4
    • Dart version 3.2.0 (build 3.2.0-199.0.dev)
    • DevTools version 2.28.0-dev.12
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 13 (API 33)
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.0.1 21A340
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 117.0.5938.92
    ! Error: Browsing on the local area network for Nexus. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by chunhtai** [comment]
Not entirely sure why this happen, seems like the code gen uses ParameterElement.type.getDisplayString from analyzer package to generate the statement. There may be something wrong with this method when using pattern match. Probably need to upgrade the package

**Comment by Fhenix96** [comment]
I have the same Problem. I am using a Map which contains multiple extra parameters:

Route

```dart
final class InvalidExtraParamRoute extends GoRouteData {
  final Map<String, Object?> $extra;

  const InvalidExtraParamRoute(this.$extra);
}
```

Generated code

```dart
extension $InvalidExtraParamRouteExtension on InvalidExtraParamRoute {
  static InvalidExtraParamRoute _fromState(GoRouterState state) =>
      InvalidExtraParamRoute(
        state.extra as Map<String, Object>, // <= NOT nullable
      );

  String get location => GoRouteData.$location(
        '/path',
      );

  void go(BuildContext context) => context.go(location, extra: $extra);

  Future<T?> push<T>(BuildContext context) =>
      context.push<T>(location, extra: $extra);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location, extra: $extra);

  void replace(BuildContext context) =>
      context.replace(location, extra: $extra);
}

```
