### ISSUE TITLE
Unable to run Flutter Apps on any ios device

### ISSUE THREAD

**Issue by KeterVM** [flutter/flutter#135677]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. flutter create project
2. flutter pub get
3. flutter run -v

### Actual results

unable to run flutter apps on any ios devices.

since i upgrade my macbook OS to Sonoma and upgrade xcode version to 15, i cant run any flutter project on my device anymore.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->
[        ] Debugger state set to launching.
[ +348 ms] error: Cannot launch '/private/var/containers/Bundle/Application/7BE8329D-EBB2-47CD-8F0D-53D55752EF9D/Runner.app': failed to get the task for process 1476
[        ] Debugger state set to detached.
[   +2 ms] Could not run build/ios/iphoneos/Runner.app on 00008020.
[   +3 ms] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[   +2 ms] Installing and launching... (completed in 37.4s)
[        ] Error launching application on Iphone.
[   +3 ms] "flutter run" took 71,294ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +86 ms] ensureAnalyticsSent: 46ms
[        ] Running 1 shutdown hook
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-MY)
    • Flutter version 3.13.6 on channel stable at /Users/ketervm/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ketervm/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/ketervm/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/ketervm/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • Namcha (mobile) • 00008020-000129083E62002E • ios            • iOS 16.1 20B82
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by KeterVM** [comment]
Could not launch “Runner”
Domain: IDEDebugSessionErrorDomain
Code: 3

this is the outputs if i try to run in xcode

**Comment by KeterVM** [comment]
https://github.com/flutter/flutter/issues/86699#issuecomment-884126252
