### ISSUE TITLE
When both WebView and AndroidView are present at the same time, a white screen may appear and PlatformException `Trying to create a platform view of unregistered type: plugins.flutter.io/webview`

### ISSUE THREAD

**Issue by J-Yaleen** [flutter/flutter#135643]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. In Flutter, when using WebView, everything is displayed correctly.

<img width="400" src="https://github.com/flutter/flutter/assets/107242550/8af82054-c5cd-4f92-b3fb-306ddbd72b3e">

2. According to the documentation at https://docs.flutter.dev/platform-integration/android/platform-views#virtual-display, after registering the platform view, the WebView appears as a white screen.

<img width="400" src="https://github.com/flutter/flutter/assets/107242550/1d89b708-2a6c-4cee-939c-55c72fdd2be7">

demo: https://github.com/J-Yaleen/demo_20230928

### Actual results

Both WebView and AndroidView can be displayed normally

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
Hi @J-Yaleen 
Do you notice there are these errors from the output console? I ran your sample project and saw these error:

<details>
<summary>Output log</summary>

```console
E/flutter ( 1188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 1188): #0      WebChromeClientHostApi.create
android_webview.g.dart:1908
E/flutter ( 1188): <asynchronous suspension>
E/flutter ( 1188):
E/flutter ( 1188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 1188): #0      WebViewHostApi.setWebChromeClient
android_webview.g.dart:1011
E/flutter ( 1188): <asynchronous suspension>
E/flutter ( 1188):
E/flutter ( 1188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 1188): #0      WebViewHostApi.loadUrl
android_webview.g.dart:489
E/flutter ( 1188): <asynchronous suspension>
E/flutter ( 1188):
E/flutter ( 1188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter ( 1188): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:496)
E/flutter ( 1188): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:191)
E/flutter ( 1188): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/flutter ( 1188): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 1188): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 1188): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 1188): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 1188): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 1188): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 1188): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 1188): 	at android.os.Looper.loop(Looper.java:255)
E/flutter ( 1188): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/flutter ( 1188): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 1188): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/flutter ( 1188): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/flutter ( 1188): , null, null)
E/flutter ( 1188): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
E/flutter ( 1188): #1      MethodChannel._invokeMethod
platform_channel.dart:310
E/flutter ( 1188): <asynchronous suspension>
E/flutter ( 1188): #2      SurfaceAndroidViewController._sendCreateMessage
platform_views.dart:976
E/flutter ( 1188): <asynchronous suspension>
E/flutter ( 1188): #3      AndroidViewController.create
platform_views.dart:763
E/flutter ( 1188): <asynchronous suspension>
E/flutter ( 1188):
```
</details>

**Comment by J-Yaleen** [comment]
> 你好@J-Yaleen 您注意到输出控制台有这些错误吗？我运行了您的示例项目并看到了这些错误：
> 
> 输出日志
> ```
> E/flutter ( 1188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
> E/flutter ( 1188): #0      WebChromeClientHostApi.create
> android_webview.g.dart:1908
> E/flutter ( 1188): <asynchronous suspension>
> E/flutter ( 1188):
> E/flutter ( 1188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
> E/flutter ( 1188): #0      WebViewHostApi.setWebChromeClient
> android_webview.g.dart:1011
> E/flutter ( 1188): <asynchronous suspension>
> E/flutter ( 1188):
> E/flutter ( 1188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
> E/flutter ( 1188): #0      WebViewHostApi.loadUrl
> android_webview.g.dart:489
> E/flutter ( 1188): <asynchronous suspension>
> E/flutter ( 1188):
> E/flutter ( 1188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
> E/flutter ( 1188): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:496)
> E/flutter ( 1188): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:191)
> E/flutter ( 1188): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
> E/flutter ( 1188): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
> E/flutter ( 1188): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
> E/flutter ( 1188): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
> E/flutter ( 1188): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
> E/flutter ( 1188): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> E/flutter ( 1188): 	at android.os.Handler.handleCallback(Handler.java:938)
> E/flutter ( 1188): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/flutter ( 1188): 	at android.os.Looper.loop(Looper.java:255)
> E/flutter ( 1188): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
> E/flutter ( 1188): 	at java.lang.reflect.Method.invoke(Native Method)
> E/flutter ( 1188): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
> E/flutter ( 1188): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> E/flutter ( 1188): , null, null)
> E/flutter ( 1188): #0      StandardMethodCodec.decodeEnvelope
> message_codecs.dart:652
> E/flutter ( 1188): #1      MethodChannel._invokeMethod
> platform_channel.dart:310
> E/flutter ( 1188): <asynchronous suspension>
> E/flutter ( 1188): #2      SurfaceAndroidViewController._sendCreateMessage
> platform_views.dart:976
> E/flutter ( 1188): <asynchronous suspension>
> E/flutter ( 1188): #3      AndroidViewController.create
> platform_views.dart:763
> E/flutter ( 1188): <asynchronous suspension>
> E/flutter ( 1188):
> ```

I can run this demo normally here. If there is no more information, I am not sure how to solve this problem.

You can also follow the following steps to create this demo:

1. Use the fluent create command to create a new project

Flutter create my_ App

2. Use this package as the library for webview and copy its sample code https://pub.dev/packages/webview_flutter/install

3. Register the platform view according to this document https://docs.flutter.dev/platform-integration/android/platform-views#virtual -Display

**Comment by J-Yaleen** [comment]
你好 @huycozy 
I can run this demo normally here. If there is no more information, I am not sure how to solve this problem.

You can also follow the following steps to create this demo:

1. Use the fluent create command to create a new project

Flutter create my_ App

2. Use this package as the library for webview and copy its sample code https://pub.dev/packages/webview_flutter/install

3. Register the platform view according to this document https://docs.flutter.dev/platform-integration/android/platform-views#virtual -Display

**Comment by J-Yaleen** [comment]
你好 @huycozy 
I can run this demo normally here. If there is no more information, I am not sure how to solve this problem.

You can also follow the following steps to create this demo:

1. Use `flutter create` command to create a new project
```shell
flutter create my_ app
```
2. Use this package as the library for webview and copy its sample code https://pub.dev/packages/webview_flutter/install

3. Register the platform view according to this document https://docs.flutter.dev/platform-integration/android/platform-views#virtual -Display

**Comment by huycozy** [comment]
I also see the white portion instead of WebView. If you notice the console log output, you may see the same exception as mine above. 

Some additional info:

- If I remove `configureFlutterEngine` callback on `MainActivity.kt`, the WebView renders normally but there will be no platform view. 
- The issue also happens with `Hybrid composition` mode. Sample code: [webview-and-platformview-135643](https://github.com/huycozy/platformviews-demo/tree/webview-and-platformview-135643)

<details>
<summary>Demo screenshot</summary>

<img width="400" src="https://github.com/flutter/flutter/assets/104349824/fa03b1aa-0dca-41ef-bc4d-2b6bb5d1f779">


</details>

<details>
<summary>Complete output log</summary>

```console
Launching lib/main.dart on RMX2001 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:61525/yBadegzZWJA=/ws
Syncing files to device RMX2001...
I/t_platformview( 7919): ProcessProfilingInfo new_methods=1050 is saved saved_to_disk=1 resolve_classes_delay=5000
I/t_platformview( 7919): Compiler allocated 4670KB to compile void android.view.ViewRootImpl.performTraversals()
E/ion     ( 7919): ioctl c0044901 failed with code -1: Invalid argument
D/ViewRootImpl( 7919): enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=517.0, y[0]=1053.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=277649571, downTime=277649571, deviceId=-1, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity]( 7919): processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=517.0, y[0]=1053.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=277649571, downTime=277649571, deviceId=-1, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity]( 7919): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=517.0, y[0]=1053.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=277649571, downTime=277649571, deviceId=-1, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity]( 7919): processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=517.0, y[0]=1053.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=277649627, downTime=277649571, deviceId=-1, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity]( 7919): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=517.0, y[0]=1053.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=277649627, downTime=277649571, deviceId=-1, source=0x1002, displayId=0 }
E/OplusCustomizeRestrictionManager( 7919): sInstance is null, start a new sInstance
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      InstanceManagerHostApi.clear (package:webview_flutter_android/src/android_webview.g.dart:230:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebStorageHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:2410:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebViewHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:479:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebSettingsHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:1182:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebSettingsHostApi.setDomStorageEnabled (package:webview_flutter_android/src/android_webview.g.dart:1205:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebSettingsHostApi.setJavaScriptCanOpenWindowsAutomatically (package:webview_flutter_android/src/android_webview.g.dart:1229:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebSettingsHostApi.setSupportMultipleWindows (package:webview_flutter_android/src/android_webview.g.dart:1253:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebSettingsHostApi.setLoadWithOverviewMode (package:webview_flutter_android/src/android_webview.g.dart:1371:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebSettingsHostApi.setUseWideViewPort (package:webview_flutter_android/src/android_webview.g.dart:1394:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebSettingsHostApi.setDisplayZoomControls (package:webview_flutter_android/src/android_webview.g.dart:1418:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebSettingsHostApi.setBuiltInZoomControls (package:webview_flutter_android/src/android_webview.g.dart:1442:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebChromeClientHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:2011:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebViewHostApi.setWebChromeClient (package:webview_flutter_android/src/android_webview.g.dart:1086:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebSettingsHostApi.setJavaScriptEnabled (package:webview_flutter_android/src/android_webview.g.dart:1276:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebViewHostApi.setBackgroundColor (package:webview_flutter_android/src/android_webview.g.dart:1109:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebViewClientHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:1617:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      DownloadListenerHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:1930:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebViewClientHostApi.setSynchronousReturnValueForShouldOverrideUrlLoading (package:webview_flutter_android/src/android_webview.g.dart:1641:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebViewHostApi.setWebViewClient (package:webview_flutter_android/src/android_webview.g.dart:986:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): #1      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): #2      AndroidWebViewController.setPlatformNavigationDelegate (package:webview_flutter_android/src/android_webview_controller.dart:421:5)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7919): #0      WebViewHostApi.loadUrl (package:webview_flutter_android/src/android_webview.g.dart:564:7)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
I/PlatformViewsController( 7919): Hosting view in view hierarchy for platform view: 1
I/BufferQueueConsumer( 7919): [](id:1eef00000000,api:0,p:-1,c:7919) connect(): controlledByApp=true
D/Surface ( 7919): lockHardwareCanvas
I/BufferQueueProducer( 7919): [SurfaceTexture-0-7919-0](id:1eef00000000,api:1,p:7919,c:7919) connect(): api=1 producerControlledByApp=true
E/FrameEvents( 7919): updateAcquireFence: Did not find frame.
D/Surface ( 7919): lockHardwareCanvas
E/FrameEvents( 7919): updateAcquireFence: Did not find frame.
E/flutter ( 7919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter ( 7919): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:496)
E/flutter ( 7919): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:191)
E/flutter ( 7919): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/flutter ( 7919): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 7919): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 7919): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 7919): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 7919): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 7919): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 7919): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7919): 	at android.os.Looper.loop(Looper.java:255)
E/flutter ( 7919): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/flutter ( 7919): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7919): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/flutter ( 7919): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/flutter ( 7919): , null, null)
E/flutter ( 7919): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 7919): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): #2      SurfaceAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:976:30)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:763:5)
E/flutter ( 7919): <asynchronous suspension>
E/flutter ( 7919): 
E/libEGL  ( 7919): Invalid file path for libcolorx-loader.so
D/ViewRootImpl( 7919): processKeyEvent,KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=0, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x0, repeatCount=0, eventTime=277657936, downTime=277657936, deviceId=-1, source=0x101, displayId=-1 }
D/DecorView( 7919): dispatchKeyEvent handled=false, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=0, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x0, repeatCount=0, eventTime=277657936, downTime=277657936, deviceId=-1, source=0x101, displayId=-1 }, activity=com.example.test_platformviews.MainActivity@3ed5621, mFeatureId=-1
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-x64, locale en-VN)
    • Flutter version 3.13.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Giraffe.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.16.0-6.0.pre.39, on macOS 14.0 23A344 darwin-x64, locale en-VN)
    • Flutter version 3.16.0-6.0.pre.39 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e27dc0a3f5 (35 minutes ago), 2023-10-08 22:51:26 -0400
    • Engine revision e58a9b3c54
    • Dart version 3.3.0 (build 3.3.0-1.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Giraffe.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by bparrishMines** [comment]
@J-Yaleen It looks like the issue is caused by the fact you are overriding configureFlutterEngine. You need to also call the super method so that all the plugins get registered.

This file: https://github.com/J-Yaleen/demo_20230928/blob/main/android/app/src/main/kotlin/com/example/demo_20230928/MainActivity.kt

Should look something like this:

```kotlin
package com.example.demo_20230928

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        flutterEngine.platformViewsController.registry.registerViewFactory(
                "<platform-view-type>",
                NativeViewFactory()
        )
    }
}
```
