### ISSUE TITLE
animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.

### ISSUE THREAD

**Issue by corepuncher** [flutter/flutter#135714]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Am unable to reproduce this error, as it happens fairly randomly, and maybe only 1 or 2 times if I let the app run all day, although the "Another exception was thrown" / short line may print 20 times in a row. I will say that sometimes I do not even have to interact with the app for this error to pop up in debug.  This means the only thing that is running in the background is an API data timer, with periodic screen updates.

### Expected results

I would expect no red error messages in the debug window, as the app seems to perform ok, including the animated icon, when called. 

### Actual results

Exception prints in debug console, even when not "using" the animation.  Tapping the icon results in expected animation, so not sure if this is only a debug version issue or not.

### Code sample

<details><summary>Code sample</summary>

```dart
// This is all the code I have regarding an animation controller. 
  late AnimationController _animationController;
  late Animation<Color?> _starAnimation;

  @override
  void initState() {
    super.initState();

// Blinking Favorites Icon
    _animationController = AnimationController(
      duration: const Duration(milliseconds: 200),
      vsync: this,
    );
    _starAnimation = ColorTween(
      begin: Colors.white,
      end: const Color.fromARGB(255, 0, 0, 0),
    ).animate(_animationController);
  }

  @override
  void dispose() {
    _animationTimer?.cancel();
    super.dispose();
  }

  void _startBlinkAnimation() {
    if (mounted) {
      _animationController.repeat(reverse: true, period: const Duration(milliseconds: 100));
      Future.delayed(const Duration(milliseconds: 600), () {
        if (mounted) {
          _animationController.stop();
          _animationController.reset();
        }
      });
    }
  }

IconButton(
              icon: Icon(isFavorite ? Icons.star : Icons.star_border),
              color: isFavorite ? const Color.fromARGB(255, 108, 255, 113) : Colors.white,
              iconSize: 25,
              onPressed: () {
                setState(() {
               Future.delayed(const Duration(milliseconds: 1500), () {
                      // Prevents crash if user taps map before menu closes
                      if (Navigator.canPop(context)) {
                        Navigator.of(context).pop();
                      }
                      _startBlinkAnimation();
                    });
                    _saveFavorites();
                });
              },
            ),

// In build widget
// These two are in different Positioned() widgets

                if (isDevice || !isLandscape)
                                  AnimatedBuilder(
                                    animation: _starAnimation,
                                    builder: (context, child) => InkWell(
                                      // Favorites Icon
                                      onTap: () {
                                        _showFavorites();
                                        setState(() {
                                          isMeasuring = false;
                                          isDrawingLine = false;
                                          endPosition = null;
                                          distance = 0;
                                          bearing = 0;
                                        });
                                      },
                                      child: Icon(
                                        Icons.star_border_outlined,
                                        color: _starAnimation.value,
                                        size: 29,
                                        shadows: const <Shadow>[
                                          Shadow(
                                            offset: Offset(1.0, 1.0),
                                            blurRadius: 2.0,
                                            color: Color.fromARGB(255, 0, 0, 0),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),

               if (!isDevice && isLandscape)
                                    AnimatedBuilder(
                                      animation: _starAnimation,
                                      builder: (context, child) => InkWell(
                                        // Favorites Icon
                                        onTap: () {
                                          _showFavorites();
                                          setState(() {
                                            isMeasuring = false;
                                            isDrawingLine = false;
                                            endPosition = null;
                                            distance = 0;
                                            bearing = 0;
                                          });
                                        },
                                        child: Icon(
                                          Icons.star_border_outlined,
                                          color: _starAnimation.value,
                                          size: 29,
                                          shadows: const <Shadow>[
                                            Shadow(
                                              offset: Offset(1.0, 1.0),
                                              blurRadius: 2.0,
                                              color: Color.fromARGB(255, 0, 0, 0),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
EXCEPTION CAUGHT BY SCHEDULER LIBRARY 
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12:
'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1149:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1147:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1064:5)
#9      _invoke1 (dart:ui/hooks.dart:186:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:379:5)
#11     _beginFrame (dart:ui/hooks.dart:129:31)
(elided 2 frames from class _AssertionError)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:580:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:265:46)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:171:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:745:42)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:612:12)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:461:12)
#8      TileImage._display.<anonymous closure> (package:flutter_map/src/layer/tile_layer/tile_image.dart:212:33)
#9      TileDisplay.when (package:flutter_map/src/layer/tile_layer/tile_display.dart:55:38)
#10     TileImage._display (package:flutter_map/src/layer/tile_layer/tile_image.dart:198:18)
#11     TileImage._onImageLoadSuccess (package:flutter_map/src/layer/tile_layer/tile_image.dart:165:7)
#12     ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:651:25)
#13     MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:992:5)
#14     MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:971:7)
<asynchronous suspension>
(elided 2 frames from class _FrameCallbackEntry)
══
Another exception was thrown: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.
Another exception was thrown: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)    
    • Flutter version 3.13.6 on channel stable at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\name\AppData\Local\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34018.315
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.82.2)
    • VS Code at C:\Users\name\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (1 available)
    • SM S916U1 (mobile) • ip:port • android-arm64  • Android 13 (API 33)

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @corepuncher, I noticed that you have a Samsung S23+ in your flutter doctor, is this the device you're experiencing the issue on? Do you by any chance have the high refresh rate (120hz) enabled when you run into this issue?

**Comment by corepuncher** [comment]
> Hi @corepuncher, I noticed that you have a Samsung S23+ in your flutter doctor, is this the device you're experiencing the issue on? Do you by any chance have the high refresh rate (120hz) enabled when you run into this issue?

Yes.  It is set to "Adaptive" which automatically adjusts up to 120 hz.  Let me change it to Standard / 60 hz and see if the problem persists.

**Comment by corepuncher** [comment]
> > Hi @corepuncher, I noticed that you have a Samsung S23+ in your flutter doctor, is this the device you're experiencing the issue on? Do you by any chance have the high refresh rate (120hz) enabled when you run into this issue?
> 
> Yes. It is set to "Adaptive" which automatically adjusts up to 120 hz. Let me change it to Standard / 60 hz and see if the problem persists.

That was not the cause, as the exception appeared once again.

**Comment by danagbemava-nc** [comment]
Thanks for the info. There appears to be a general issue with 120hz+ devices. There's an issue already tracking this in https://github.com/flutter/flutter/issues/106277. 

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you
