### ISSUE TITLE
Error (Xcode): Cycle inside Runner; building could produce unreliable results.

### ISSUE THREAD

**Issue by tajjacob** [flutter/flutter#135739]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Upgrade to Xcode 15.0
2. Upgrade to Flutter 3.13.6
3. Upgrade IOS 17

### Expected results

Expecting Flutter run with no problem on ios 17 device and simulator.

### Actual results

Once upgrade to Xcode 15, ios 17, and Flutter 3.13, Flutter failed to run on ios 17 simulator and device. 
Flutter run with no problem on android device and emulator.

### Code sample

<details><summary>Podfile</summary>

```dart
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

target 'ImageNotification' do
  use_frameworks!
  pod 'Firebase/Messaging'
end

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[        ] Error (Xcode): Cycle inside Runner; building could produce unreliable results.
           Cycle details:
           → Target 'Runner': ExtractAppIntentsMetadata
           ○ Target 'Runner' has copy command from '/Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/ImageNotification.appex' to '/Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/ImageNotification.appex'
           ○ That command depends on command in Target 'Runner': script phase “Thin Binary”
           ○ Target 'Runner' has process command with output '/Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist'
           ○ Target 'Runner' has copy command from '/Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/ImageNotification.appex' to '/Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/ImageNotification.appex'


           Raw dependency cycle trace:

           target:  ->

           node: <all> ->

           command: <all> ->

           node: /Users/tajjacob/Library/Developer/Xcode/DerivedData/Runner-gxlwoqmjkycsztgdgyhutgfdkqof/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/ExtractedAppShortcutsMetadata.stringsdata ->

           command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ExtractAppIntentsMetadata ->

           node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase8--cp--copy-pods-resources> ->

           command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase8--cp--copy-pods-resources ->

           node: /Users/tajjacob/Library/Developer/Xcode/DerivedData/Runner-gxlwoqmjkycsztgdgyhutgfdkqof/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-22AF991EE5A9A021C73C9815-Pods-Runner-resources-Debug-input-files-370465e8ece3ac55ebe5ba4fafd0eed2-resolved.xcfilelist ->

           command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/tajjacob/Library/Developer/Xcode/DerivedData/Runner-gxlwoqmjkycsztgdgyhutgfdkqof/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-22AF991EE5A9A021C73C9815-Pods-Runner-resources-Debug-input-files-370465e8ece3ac55ebe5ba4fafd0eed2-resolved.xcfilelist ->

           node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7--firebase-crashlytics--crashlytics-upload-symbols> ->

           command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7--firebase-crashlytics--crashlytics-upload-symbols ->

           node: /Users/tajjacob/Library/Developer/Xcode/DerivedData/Runner-gxlwoqmjkycsztgdgyhutgfdkqof/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-6D67C3605085DB13E79B2139.sh ->

           command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/tajjacob/Library/Developer/Xcode/DerivedData/Runner-gxlwoqmjkycsztgdgyhutgfdkqof/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-6D67C3605085DB13E79B2139.sh ->

           node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6-copy-files> ->

           command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6-copy-files ->

           node: <Copy /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/ImageNotification.appex> ->

           CYCLE POINT ->

           command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/ImageNotification.appex /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/ImageNotification.appex ->

           node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks> ->

           command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks ->

           node: /Users/tajjacob/Library/Developer/Xcode/DerivedData/Runner-gxlwoqmjkycsztgdgyhutgfdkqof/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-564FBEE53C6B8E45E470E579-Pods-Runner-frameworks-Debug-input-files-8dcb11941ee2ff322c70687d702fd085-resolved.xcfilelist ->

           command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/tajjacob/Library/Developer/Xcode/DerivedData/Runner-gxlwoqmjkycsztgdgyhutgfdkqof/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-564FBEE53C6B8E45E470E579-Pods-Runner-frameworks-Debug-input-files-8dcb11941ee2ff322c70687d702fd085-resolved.xcfilelist ->

           node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->

           command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->

           node: <execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-> ->

           command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary /Users/tajjacob/Library/Developer/Xcode/DerivedData/Runner-gxlwoqmjkycsztgdgyhutgfdkqof/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh ->

           node: /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist/ ->

           directoryTreeSignature: d ->

           directoryContents: /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

           node: /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

           command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/Info.plist /Users/tajjacob/StudioProjects/superapp/ios/Runner/Info.plist ->

           node: /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/ImageNotification.appex ->

           command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/ImageNotification.appex /Users/tajjacob/StudioProjects/superapp/build/ios/Debug-iphonesimulator/ImageNotification.appex

[   +2 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 15 Pro Max.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:662:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] VS Code (version 1.83.0-insider)
[✓] Connected device (6 available)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment]
Hi @tajjacob 
Does your project contain any `Extensions`? If it does, this could be a stale XCode issue. Please follow this [solution](https://github.com/flutter/flutter/issues/134256#issuecomment-1712053622) to see if it works for your.

**Comment by bahadirarslan** [comment]
I don't have any Extension also there is no Embed App Extensions step at Build Phase to move up still had the same problem.
But my project contains Watch app so there is a Embed Watch Content step at Build Phase, so I moved it up just below Copy Bundle Resources as suggested for extensions and it worked.

**Comment by whitesoil** [comment]
You should change **Build Phases** order on **TARGETS -> Runner -> Build Phases**

I solved the issue in this order.

<img width="715" alt="스크린샷 2023-10-01 오전 1 57 32" src="https://github.com/flutter/flutter/assets/34286430/e69eaede-f656-4ddf-bd3b-b8aa2138776f">

**Comment by tajjacob** [comment]
> You should change **Build Phases** order on **TARGETS -> Runner -> Build Phases**
> 
> I solved the issue in this order.
> <img alt="스크린샷 2023-10-01 오전 1 57 32" width="715" src="https://user-images.githubusercontent.com/34286430/271785854-e69eaede-f656-4ddf-bd3b-b8aa2138776f.png">

Thanks for the solution! Already run flutter on ios device and simulator.

**Comment by huycozy** [comment]
Closing the issue as solved.
