### ISSUE TITLE
DropdownMenu throws an assert error if keyboard is closed while menu is open

### ISSUE THREAD

**Issue by howljs** [flutter/flutter#135865]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code on simulator
2. Select the textfield
3. Select the dropdown menu
4. Press done to close the keyboard

### Expected results

No crash

### Actual results

Crash

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: const SingleChildScrollView(
        child: Column(
          children: [
            Padding(
              padding: EdgeInsets.symmetric(vertical: 20, horizontal: 16),
              child: Column(
                children: [
                  SizedBox(height: 500),
                  TextField(
                    decoration: InputDecoration(label: Text('Textfield')),
                  ),
                  SizedBox(height: 24),
                  DropdownMenu<int>(
                    label: Text('Dropdown'),
                    dropdownMenuEntries: [
                      DropdownMenuEntry(value: 1, label: 'Dropdown Item 1'),
                      DropdownMenuEntry(value: 2, label: 'Dropdown Item 2'),
                      DropdownMenuEntry(value: 3, label: 'Dropdown Item 3'),
                      DropdownMenuEntry(value: 4, label: 'Dropdown Item 4')
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/33460888/8d5f27f6-243d-4ee3-a28d-81ef09265fd8

</details>

### Logs

<details><summary>Logs</summary>

```console
[+10554 ms] ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
                     The following assertion was thrown while dispatching notifications for ValueNotifier<bool>:
                     Build scheduled during frame.
                     While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild
                     the widget tree.
                     This might be because setState() was called from a layout or paint callback. If a change is needed
                     to the widget tree, it should be applied as the tree is being built. Scheduling a change for the
                     subsequent frame instead results in an interface that lags behind by one frame. If this was done to
                     make your build dependent on a size measured at layout time, consider using a LayoutBuilder,
                     CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is
                     the desired effect, for example because this is an animation, consider scheduling the frame in a
                     post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to
                     trigger the animation.
                     
                     When the exception was thrown, this was the stack:
                     #0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:849:9)
                     #1      WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:872:6)
                     #2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2721:24)
                     #3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5050:12)
                     #4      State.setState (package:flutter/src/widgets/framework.dart:1223:15)
                     #5      _MenuAnchorState._close (package:flutter/src/material/menu_anchor.dart:563:7)
                     #6      _MenuAnchorState._handleScroll (package:flutter/src/material/menu_anchor.dart:472:13)
                     #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
                     #8      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
                     #9      ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:1003:25)
                     #10     ScrollPositionWithSingleContext.beginActivity
(package:flutter/src/widgets/scroll_position_with_single_context.dart:113:11)
                     #11     ScrollPositionWithSingleContext.goBallistic
(package:flutter/src/widgets/scroll_position_with_single_context.dart:146:7)
                     #12     IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:159:14)
                     #13     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:706:15)
                     #14     ScrollPositionWithSingleContext.applyNewDimensions
(package:flutter/src/widgets/scroll_position_with_single_context.dart:102:11)
                     #15     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:635:7)
                     #16     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:499:12)
                     #17     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #18     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #20     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #21     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #23     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #24     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #26     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #27     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #29     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #30     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #32     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #33     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #35     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #36     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #37     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
                     #38     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
                     #39     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
                     #40     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
                     #41     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
                     #42     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
                     #43     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
                     #44     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
                     #45     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
                     #46     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
                     #47     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
                     #48     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
                     #49     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
                     #50     _invoke (dart:ui/hooks.dart:312:13)
                     #51     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
                     #52     _drawFrame (dart:ui/hooks.dart:283:31)
                     
                     The ValueNotifier<bool> sending notification was:
                       ValueNotifier<bool>#01070(true)
                     ════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.16.0-2.0.pre.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-VN)
    • Flutter version 3.16.0-2.0.pre.6 on channel master at /Users/howl/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bfd4cf6a2b (77 minutes ago), 2023-10-02 12:12:14 -0400
    • Engine revision c0cf135b11
    • Dart version 3.2.0 (build 3.2.0-221.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/howl/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/howl/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPorn 14 (mobile)          • 00008120-001A593811E0C01E            • ios            • iOS 17.0 21A329
    • iPhone 15 Pro Max (mobile) • E1D76201-773A-4AF6-9CBC-19AF1A033835 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0
      (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample and the steps outlined above. 

<details>
<summary>logs</summary>

```
Launching lib/main.dart on Pixel 7 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
I/com.example.hx( 6004): Compiler allocated 4413KB to compile void android.view.ViewRootImpl.performTraversals()
D/InputMethodManager( 6004): showSoftInput() view=io.flutter.embedding.android.FlutterView{9a271f4 VFED..... .F....ID 0,0-1080,2293 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/AssistStructure( 6004): Flattened final assist data: 372 bytes, containing 1 windows, 3 views
D/InputConnectionAdaptor( 6004): The input method toggled cursor monitoring on
D/InsetsController( 6004): show(ime(), fromIme=true)
D/InputConnectionAdaptor( 6004): The input method toggled cursor monitoring off
I/flutter ( 6004): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter ( 6004): The following assertion was thrown while dispatching notifications for ValueNotifier<bool>:
I/flutter ( 6004): Build scheduled during frame.
I/flutter ( 6004): While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild
I/flutter ( 6004): the widget tree.
I/flutter ( 6004): This might be because setState() was called from a layout or paint callback. If a change is needed
I/flutter ( 6004): to the widget tree, it should be applied as the tree is being built. Scheduling a change for the
I/flutter ( 6004): subsequent frame instead results in an interface that lags behind by one frame. If this was done to
I/flutter ( 6004): make your build dependent on a size measured at layout time, consider using a LayoutBuilder,
I/flutter ( 6004): CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is
I/flutter ( 6004): the desired effect, for example because this is an animation, consider scheduling the frame in a
I/flutter ( 6004): post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to
I/flutter ( 6004): trigger the animation.
I/flutter ( 6004):
I/flutter ( 6004): When the exception was thrown, this was the stack:
I/flutter ( 6004): #0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:849:9)
I/flutter ( 6004): #1      WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:872:6)
I/flutter ( 6004): #2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2721:24)
I/flutter ( 6004): #3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5050:12)
I/flutter ( 6004): #4      State.setState (package:flutter/src/widgets/framework.dart:1223:15)
I/flutter ( 6004): #5      _MenuAnchorState._close (package:flutter/src/material/menu_anchor.dart:563:7)
I/flutter ( 6004): #6      _MenuAnchorState._handleScroll (package:flutter/src/material/menu_anchor.dart:472:13)
I/flutter ( 6004): #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
I/flutter ( 6004): #8      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
I/flutter ( 6004): #9      ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:1003:25)
I/flutter ( 6004): #10     ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:113:11)
I/flutter ( 6004): #11     ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:146:7)
I/flutter ( 6004): #12     IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:159:14)
I/flutter ( 6004): #13     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:706:15)
I/flutter ( 6004): #14     ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:102:11)
I/flutter ( 6004): #15     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:635:7)
I/flutter ( 6004): #16     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:499:12)
I/flutter ( 6004): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
I/flutter ( 6004): #18     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
I/flutter ( 6004): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
I/flutter ( 6004): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
I/flutter ( 6004): #21     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
I/flutter ( 6004): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
I/flutter ( 6004): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
I/flutter ( 6004): #24     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
I/flutter ( 6004): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
I/flutter ( 6004): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
I/flutter ( 6004): #27     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
I/flutter ( 6004): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
I/flutter ( 6004): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
I/flutter ( 6004): #30     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
I/flutter ( 6004): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
I/flutter ( 6004): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
I/flutter ( 6004): #33     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
I/flutter ( 6004): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
I/flutter ( 6004): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
I/flutter ( 6004): #36     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
I/flutter ( 6004): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
I/flutter ( 6004): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
I/flutter ( 6004): #39     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
I/flutter ( 6004): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
I/flutter ( 6004): #41     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
I/flutter ( 6004): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
I/flutter ( 6004): #43     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
I/flutter ( 6004): #44     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
I/flutter ( 6004): #45     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
I/flutter ( 6004): #46     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
I/flutter ( 6004): #47     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
I/flutter ( 6004): #48     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
I/flutter ( 6004): #49     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
I/flutter ( 6004): #50     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
I/flutter ( 6004): #51     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
I/flutter ( 6004): #52     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
I/flutter ( 6004): #53     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
I/flutter ( 6004): #54     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
I/flutter ( 6004): #55     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
I/flutter ( 6004): #56     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
I/flutter ( 6004): #57     _invoke (dart:ui/hooks.dart:312:13)
I/flutter ( 6004): #58     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
I/flutter ( 6004): #59     _drawFrame (dart:ui/hooks.dart:283:31)
I/flutter ( 6004):
I/flutter ( 6004): The ValueNotifier<bool> sending notification was:
I/flutter ( 6004):   ValueNotifier<bool>#453b1(true)
I/flutter ( 6004): ════════════════════════════════════════════════════════════════════════════════════════════════════
Application finished.

Exited.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.13.6 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (6 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.0.2 21A351
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.0.2 21A351
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
 
```
[✓] Flutter (Channel master, 3.16.0-2.0.pre.17, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.16.0-2.0.pre.17 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 047bd6cebd (2 hours ago), 2023-10-03 13:26:41 +0800
    • Engine revision 1549d58b6e
    • Dart version 3.2.0 (build 3.2.0-222.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.0.2 21A351
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.0.2 21A351
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by howljs** [comment]
It worked normally when I wrapped it in `SchedulerBinding.instance.addPostFrameCallback`:

```
SchedulerBinding.instance.addPostFrameCallback((Duration _) {
        widget.onClose?.call();
        setState(() {});
 });

```
<img width="1390" alt="Screenshot 2023-10-03 at 16 58 34" src="https://github.com/flutter/flutter/assets/33460888/d2e7069b-881f-4cdc-8e39-4624a05724c6">

**Comment by Piinks** [comment]
The change that closed this was reverted, reopening

**Comment by Piinks** [comment]
I added the repro for the test that was broken by https://github.com/flutter/flutter/pull/136239 in https://github.com/flutter/flutter/issues/105733
