### ISSUE TITLE
GoogleMap: Animating the camera in onMapCreated causes a PlatformException: Map size can't be 0

### ISSUE THREAD

**Issue by AndreasKl** [flutter/flutter#135874]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code below, press the "Toggle Map" button.
2. One of two options can happen:
3. A stacktrace is emitted, nothing else happens.
3. The city of Bonn is zoomed into view.
4. When adding a **delay** of 500ms+ before calling `animateCamera` the animation is always applied.

> Note: This looks like a race, between the Maps widget knowing it's size and emitting the `onMapCreated` to early, causing the `animateCamera` to fail.

The issue was reported multiple times https://github.com/flutter/flutter/issues/47241, https://github.com/flutter/flutter/issues/29181 but never resolved.

### Expected results

The camera should be moved to the bounding box, zooming to the city.

### Actual results

An exception is raised, the camera does not move to the desired position.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MapsMapsEverywhere());
}

class MapsMapsEverywhere extends StatefulWidget {
  const MapsMapsEverywhere({super.key});

  @override
  State<MapsMapsEverywhere> createState() => _MapsMapsEverywhereState();
}

class _MapsMapsEverywhereState extends State<MapsMapsEverywhere> {
  bool _showMap = false;
  GoogleMapController? _controller;

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () {
                setState(() {
                  _showMap = !_showMap;
                });
              },
              child: const Text(
                'Toggle Map',
              ),
            ),
            _showMap ? Expanded(child: _buildGoogleMap()) : Container(),
          ],
        ),
      ),
    );
  }

  GoogleMap _buildGoogleMap() {
    return GoogleMap(
      onMapCreated: (c) async {
        _controller = c;
        await c.animateCamera(
          CameraUpdate.newLatLngBounds(_bounds(), 50),
        );
      },
      initialCameraPosition: const CameraPosition(
        zoom: 8.6,
        target: LatLng(50.733334, 7.100000),
      ),
    );
  }

  LatLngBounds _bounds() {
    return LatLngBounds(
        southwest: const LatLng(50.6, 7.05),
        northeast: const LatLng(50.8, 7.09));
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }
}
```

</details>

### Logs

<details><summary>Logs</summary>

```console
E/flutter (11641): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occurred for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions., null, com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occurred for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
E/flutter (11641): 	at com.google.maps.api.android.lib6.common.m.h(:com.google.android.gms.dynamite_mapsdynamite@233715047@23.37.15 (190800-0):8)
E/flutter (11641): 	at com.google.maps.api.android.lib6.gmm6.api.c.l(:com.google.android.gms.dynamite_mapsdynamite@233715047@23.37.15 (190800-0):28)
E/flutter (11641): 	at com.google.maps.api.android.lib6.impl.ae.a(:com.google.android.gms.dynamite_mapsdynamite@233715047@23.37.15 (190800-0):10)
E/flutter (11641): 	at com.google.maps.api.android.lib6.gmm6.api.c.z(:com.google.android.gms.dynamite_mapsdynamite@233715047@23.37.15 (190800-0):31)
E/flutter (11641): 	at com.google.maps.api.android.lib6.impl.bk.o(:com.google.android.gms.dynamite_mapsdynamite@233715047@23.37.15 (190800-0):25)
E/flutter (11641): 	at com.google.android.gms.maps.internal.i.bb(:com.google.android.gms.dynamite_mapsdynamite@233715047@23.37.15 (190800-0):1924)
E/flutter (11641): 	at m.fi.onTransact(:com.google.android.gms.dynamite_mapsdynamite@233715047@23.37.15 (190800-0):21)
E/flutter (11641): 	at android.os.Binder.transact(Binder.java:1064)
E/flutter (11641): 	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
E/flutter (11641): 	at com.google.android.gms.maps.internal.zzg.animateCamera(com.google.android.gms:play-services-maps@@18.1.0:3)
E/flutter (11641): 	at com.google.android.gms.maps.GoogleMap.animateCamera(com.google.android.gms:play-services-maps@@18.1.0:2)
E/flutter (11641): 	at io.flutter.plugins.googlemaps.GoogleMapController.animateCamera(GoogleMapController.java:131)
E/flutter (11641): 	at io.flutter.plugins.googlemaps.GoogleMapController.onMethodCall(GoogleMapController.java:306)
E/flutter (11641): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (11641): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (11641): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (11641): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (11641): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (11641): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (11641): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (11641): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (11641): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/flutter (11641): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11641): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (11641): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (11641): )
E/flutter (11641): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (11641): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (11641): <asynchronous suspension>
E/flutter (11641): #2      _MapsMapsEverywhereState._buildGoogleMap.<anonymous closure> (package:maps/main.dart:47:9)
E/flutter (11641): <asynchronous suspension>
E/flutter (11641): 
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[xx@fedora maps]$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on Fedora Linux 38 (Workstation Edition) 6.5.5-200.fc38.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
[xx@fedora maps]$ 
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report. Was able to replicate the error using latest stable and master versions on Android. The reported exception doesn't occur while running on iOS.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.13.6, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.6 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.15.0-13.0.pre.2, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.15.0-13.0.pre.2 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 938bb217fb (4 days ago), 2023-09-28 21:11:31 -0700
    • Engine revision 2052515c44
    • Dart version 3.2.0 (build 3.2.0-210.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by stuartmorgan** [comment]
> The issue was reported multiple times #47241, #29181 but never resolved.

https://github.com/flutter/flutter/issues/29181 is still open; please don't deliberately file duplicate issues. If there is new technical information that would contribute to a solution, please add it there.

Closing as a duplicate.
