### ISSUE TITLE
Unable to provide reliable builds of the plugin using `kotlinx.serialization` across different Kotlin versions

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#135995]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. `git clone git@github.com:bartekpacia/flutter_kotlinx_serialization_version_mismatch_bug.git`
2. `cd flutter_kotlinx_serialization_version_mismatch_bug`
3. `flutter run`
4. Tap on the "use kotlinx.serialization" button

### Expected results

Perfect: No exception is thrown.

Still good: gotchas around using `kotlinx.serialization` are explained in the documentation for plugin authors.

### Actual results

Runtime error is thrown.

### Code sample

provided in the repo above

### Screenshots or Video

N/A

### Logs

<details><summary>Logs</summary>

```console
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: Failed to handle method call
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: kotlinx.serialization.SerializationException: Serializer for class 'Person' is not found.
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:28)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:134)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at kotlinx.serialization.SerializersKt.serializer(Unknown Source:1)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at com.example.flutter_kotlinx_serialization_version_mismatch_bug.FlutterKotlinxSerializationVersionMismatchBugPlugin.onMethodCall(FlutterKotlinxSerializationVersionMismatchBugPlugin.kt:49)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at io.flutter.plugin.common.MethodChannel.onMessage(MethodChannel.java:258)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda/opt/homebrew/bin/zsh-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at io.flutter.embedding.engine.dart.DartMessenger60920ExternalSyntheticLambda0.run(Unknown Source:12)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at android.os.Handler.handleCallback(Handler.java:883)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at android.os.Looper.loop(Looper.java:214)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at java.lang.reflect.Method.invoke(Native Method)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at com.android.internal.os.RuntimeInit.run(RuntimeInit.java:492)
10-04 17:47:37.490 11630 11630 E MethodChannel#flutter_kotlinx_serialization_version_mismatch_bug: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-04 17:47:37.493   181  5116 W audio_hw_generic: Not supplying enough data to HAL, expected position 2665818 , only wrote 2665813
10-04 17:47:37.494 11630 11681 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Serializer for class 'Person' is not found.
10-04 17:47:37.494 11630 11681 E flutter : Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
10-04 17:47:37.494 11630 11681 E flutter : , null, kotlinx.serialization.SerializationException: Serializer for class 'Person' is not found.
10-04 17:47:37.494 11630 11681 E flutter : Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
10-04 17:47:37.494 11630 11681 E flutter : 
10-04 17:47:37.494 11630 11681 E flutter : 	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
10-04 17:47:37.494 11630 11681 E flutter : 	at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:28)
10-04 17:47:37.494 11630 11681 E flutter : 	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:134)
10-04 17:47:37.494 11630 11681 E flutter : 	at kotlinx.serialization.SerializersKt.serializer(Unknown Source:1)
10-04 17:47:37.494 11630 11681 E flutter : 	at com.example.flutter_kotlinx_serialization_version_mismatch_bug.FlutterKotlinxSerializationVersionMismatchBugPlugin.onMethodCall(FlutterKotlinxSerializationVersionMismatchBugPlugin.kt:49)
10-04 17:47:37.494 11630 11681 E flutter : 	at io.flutter.plugin.common.MethodChannel.onMessage(MethodChannel.java:258)
10-04 17:47:37.494 11630 11681 E flutter : 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
10-04 17:47:37.494 11630 11681 E flutter : 	at io.flutter.embedding.engine.dart.DartMessenger.lambda/opt/homebrew/bin/zsh-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
10-04 17:47:37.494 11630 11681 E flutter : 	at io.flutter.embedding.engine.dart.DartMessenger60920ExternalSyntheticLambda0.run(Unknown Source:12)
10-04 17:47:37.494 11630 11681 E flutter : 	at android.os.Handler.handleCallback(Handler.java:883)
10-04 17:47:37.494 11630 11681 E flutter : 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-04 17:47:37.494 11630 11681 E flutter : 	at android.os.Looper.loop(Looper.java:214)
10-04 17:47:37.494 11630 11681 E flutter : 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-04 17:47:37.494 11630 11681 E flutter : 	at java.lang.reflect.Method.invoke(Native Method)
10-04 17:47:37.494 11630 11681 E flutter : 	at com.android.internal.os.RuntimeInit.run(RuntimeInit.java:492)
10-04 17:47:37.494 11630 11681 E flutter : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-04 17:47:37.494 11630 11681 E flutter : )
10-04 17:47:37.494 11630 11681 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
10-04 17:47:37.494 11630 11681 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
10-04 17:47:37.494 11630 11681 E flutter : <asynchronous suspension>
10-04 17:47:37.494 11630 11681 E flutter : #2      MethodChannelFlutterKotlinxSerializationVersionMismatchBug.useKotlinxSerialization (package:flutter_kotlinx_serialization_version_mismatch_bug/flutter_kotlinx_serialization_version_mismatch_bug_method_channel.dart:23:5)
10-04 17:47:37.494 11630 11681 E flutter : <asynchronous suspension>
10-04 17:47:37.494 11630 11681 E flutter : 
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-PL)
    • Flutter version 3.13.6 on channel stable at /Users/bartek/fvm/versions/3.13.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (8 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/bartek/androidsdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/bartek/androidsdk
    • Java binary at: /Users/bartek/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/bartek/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/bartek/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 10 (API 29) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
> ### Workaround #1
> Make sure both the plugin Gradle project and the app Gradle project depend on the same version of Kotlin.

How is this a workaround? Based on [the project docs](https://github.com/Kotlin/kotlinx.serialization#setup) it sounds like this is a fundamental requirement of choosing to make this compiler plugin a requirement of your Flutter plugin's code.

**Comment by bartekpacia** [comment]
That's correct. My question is how can I make it play nicely with Flutter's ecosystem of Android plugins, where often the `app` and plugins depend on different versions of Kotlin.

If it's impossible – that's also an answer that I'll accept, of course.

**Comment by stuartmorgan** [comment]
> My question is how can I make it play nicely with Flutter's ecosystem of Android plugins, where often the `app` and plugins depend on different versions of Kotlin.

For support questions, consider one of the options listed at https://flutter.dev/community#community-grid.

This doesn't seem to be an actionable Flutter issue, since I don't see what Flutter could do in this scenario; the version-specific install requirement appears to be fundamental to the tool you are choosing to depend on, so I don't see how you could do this without requiring your users to set it up for their compiler version. Given that, closing.

**Comment by bartekpacia** [comment]
For whoever might be interested in this: we ended up migrating Patrol from `kotlinx.serialization` to Gson. See https://github.com/leancodepl/patrol/pull/1782.
