### ISSUE TITLE
Warning log: Google certificate not found

### ISSUE THREAD

**Issue by DiegoGW** [flutter/flutter#135929]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Get latest version of Wonderous app (This is the log when this issue was created - commit a04d8bbb71c2a1a00e393218de6e44dc2ad0559a (HEAD -> main, origin/main, origin/HEAD)

Merge: https://github.com/flutter/flutter/commit/8a29d67fa4eb7947b01c5eba330f1fd52a23da47 509487f
Author: Shawn [shawn@gskinner.com](mailto:shawn@gskinner.com)
Date: Mon Oct 2 14:02:12 2023 -0600
Merge pull request https://github.com/flutter/flutter/issues/124 from yangsfang/yangsfang-patch-1
Fix throttler calling an action twice
)

2. Run Wonderous in Android Studio (target: Pixel 6 + Android 13)
3. Navigate to the Great Wall (Navigate to: /wonder/greatWall?t=0)
4. Check the log:
```
W/DynamiteModule( 9098): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 9098): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:7
I/DynamiteModule( 9098): Selected remote version of com.google.android.gms.googlecertificates, version >= 7
W/MobStoreFlagStore( 9098): Unable to update local snapshot for com.google.android.libraries.consentverifier#com.gskinner.flutter.wonders, may result in stale flags.
W/MobStoreFlagStore( 9098): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.gskinner.flutter.wonders, sha256=[6e404f6c0fb48a010fea31245b32fa23f9f0be40c2c3a2611f4714165d92c436], atk=false, ver=233515044.true (go/gsrlt)
W/MobStoreFlagStore( 9098): 	at m.arn.s(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):21)
W/MobStoreFlagStore( 9098): 	at m.arn.get(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):5)
W/MobStoreFlagStore( 9098): 	at m.ats.a(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):2)
W/MobStoreFlagStore( 9098): 	at m.asx.h(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):7)
W/MobStoreFlagStore( 9098): 	at m.aal.c(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):1)
W/MobStoreFlagStore( 9098): 	at m.aao.run(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):5)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/MobStoreFlagStore( 9098): 	at java.lang.Thread.run(Thread.java:1012)
W/MobStoreFlagStore( 9098): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.gskinner.flutter.wonders, sha256=[6e404f6c0fb48a010fea31245b32fa23f9f0be40c2c3a2611f4714165d92c436], atk=false, ver=233515044.true (go/gsrlt)
W/MobStoreFlagStore( 9098): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
W/MobStoreFlagStore( 9098): 	at android.os.Parcel.createException(Parcel.java:2995)
W/MobStoreFlagStore( 9098): 	at android.os.Parcel.readException(Parcel.java:2978)
W/MobStoreFlagStore( 9098): 	at android.os.Parcel.readException(Parcel.java:2920)
W/MobStoreFlagStore( 9098): 	at m.fh.c(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):11)
W/MobStoreFlagStore( 9098): 	at m.sk.a(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):39)
W/MobStoreFlagStore( 9098): 	at m.jt.e(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):11)
W/MobStoreFlagStore( 9098): 	at m.kr.t(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):10)
W/MobStoreFlagStore( 9098): 	at m.kr.u(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):22)
W/MobStoreFlagStore( 9098): 	at m.kr.e(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):16)
W/MobStoreFlagStore( 9098): 	at m.kv.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):774)
W/MobStoreFlagStore( 9098): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/MobStoreFlagStore( 9098): 	at android.os.Looper.loopOnce(Looper.java:201)
W/MobStoreFlagStore( 9098): 	at android.os.Looper.loop(Looper.java:288)
W/MobStoreFlagStore( 9098): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Expected results

None warning should be logged

### Actual results

Warning logs due to com.google.android.gms.googlecertificates not found are logged.

### Code sample

<details><summary>Code sample</summary>

```Wonderous
git clone  https://github.com/gskinnerTeam/flutter-wonderous-app.git
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![navigate to great wall](https://github.com/flutter/flutter/assets/11681325/18afb405-6717-4750-b4a0-6e7a42275998)

</details>

### Logs

<details><summary>Logs</summary>

```console
W/DynamiteModule( 9098): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 9098): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:7
I/DynamiteModule( 9098): Selected remote version of com.google.android.gms.googlecertificates, version >= 7
W/MobStoreFlagStore( 9098): Unable to update local snapshot for com.google.android.libraries.consentverifier#com.gskinner.flutter.wonders, may result in stale flags.
W/MobStoreFlagStore( 9098): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.gskinner.flutter.wonders, sha256=[6e404f6c0fb48a010fea31245b32fa23f9f0be40c2c3a2611f4714165d92c436], atk=false, ver=233515044.true (go/gsrlt)
W/MobStoreFlagStore( 9098): 	at m.arn.s(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):21)
W/MobStoreFlagStore( 9098): 	at m.arn.get(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):5)
W/MobStoreFlagStore( 9098): 	at m.ats.a(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):2)
W/MobStoreFlagStore( 9098): 	at m.asx.h(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):7)
W/MobStoreFlagStore( 9098): 	at m.aal.c(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):1)
W/MobStoreFlagStore( 9098): 	at m.aao.run(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):5)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/MobStoreFlagStore( 9098): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/MobStoreFlagStore( 9098): 	at java.lang.Thread.run(Thread.java:1012)
W/MobStoreFlagStore( 9098): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.gskinner.flutter.wonders, sha256=[6e404f6c0fb48a010fea31245b32fa23f9f0be40c2c3a2611f4714165d92c436], atk=false, ver=233515044.true (go/gsrlt)
W/MobStoreFlagStore( 9098): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
W/MobStoreFlagStore( 9098): 	at android.os.Parcel.createException(Parcel.java:2995)
W/MobStoreFlagStore( 9098): 	at android.os.Parcel.readException(Parcel.java:2978)
W/MobStoreFlagStore( 9098): 	at android.os.Parcel.readException(Parcel.java:2920)
W/MobStoreFlagStore( 9098): 	at m.fh.c(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):11)
W/MobStoreFlagStore( 9098): 	at m.sk.a(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):39)
W/MobStoreFlagStore( 9098): 	at m.jt.e(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):11)
W/MobStoreFlagStore( 9098): 	at m.kr.t(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):10)
W/MobStoreFlagStore( 9098): 	at m.kr.u(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):22)
W/MobStoreFlagStore( 9098): 	at m.kr.e(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):16)
W/MobStoreFlagStore( 9098): 	at m.kv.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@233515044@23.35.15 (190400-0):774)
W/MobStoreFlagStore( 9098): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/MobStoreFlagStore( 9098): 	at android.os.Looper.loopOnce(Looper.java:201)
W/MobStoreFlagStore( 9098): 	at android.os.Looper.loop(Looper.java:288)
W/MobStoreFlagStore( 9098): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.16.0-2.0.pre.8, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.16.0-2.0.pre.8 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b71f8ce7ae (2 hours ago), 2023-10-02 15:09:38 -0400
    • Engine revision f3a92cb0c4
    • Dart version 3.2.0 (build 3.2.0-221.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • Pixel 6 (mobile)         • 1A141FDF600823            • android-arm64  • Android 13 (API 33)
    • Somnio’s iPhone (mobile) • 00008120-001168D83C87C01E • ios            • iOS 17.0.2 21A351
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by nanaykubo** [comment]
Up for this

**Comment by huycozy** [comment]
Checking this on the latest Fluter stable 3.29.2, on Pixel 7, Android 15, I see the log (`googlecertificates not found`) appears but don't see the `SecurityException` as reported. Adding the appropriate labels for tracking further.

<details open>
<summary>Output log</summary>

```console
W/DynamiteModule(13163): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(13163): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:7
I/DynamiteModule(13163): Selected remote version of com.google.android.gms.googlecertificates, version >= 7
W/flutter.wonders(13163): ClassLoaderContext classpath element checksum mismatch. expected=3729656857, found=2320135659 (DLC[];PCL[base.apk*3729656857]{PCL[/system/framework/org.apache.http.legacy.jar*2884979375]#PCL[/system/framework/com.android.media.remotedisplay.jar*56884057]#PCL[/system/framework/com.android.location.provider.jar*690536414]#PCL[/system_ext/framework/androidx.window.extensions.jar*2579805202]#PCL[/system_ext/framework/androidx.window.sidecar.jar*3633536204]} | DLC[];PCL[/data/app/~~7ZGKFOaiLkr-oUZ2TJdovw==/com.gskinner.flutter.wonders-PQh8bruGsrJDVRD0g4r-yA==/base.apk*2320135659]{PCL[/system_ext/framework/androidx.window.extensions.jar*2579805202]#PCL[/system_ext/framework/androidx.window.sidecar.jar*3633536204]#PCL[/system/framework/org.apache.http.legacy.jar*2884979375]})
W/ProxyAndroidLoggerBackend(13163): Too many Flogger logs received before configuration. Dropping old logs.
D/Google Android Maps SDK(13163): For capability in capabilities, log:
D/Google Android Maps SDK(13163): "AdvancedMarkers: false: Capabilities unavailable without a Map ID."Data-driven styling: false
W/ProxyAndroidLoggerBackend(13163): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(13163): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(13163): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(13163): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(13163): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(13163): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(13163): Too many Flogger logs received before configuration. Dropping old logs.
```
</details>


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.3.2 24D81 darwin-x64, locale en-VN) [1,207ms]
    • Flutter version 3.29.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (5 days ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [6.4s]
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [4.5s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [49ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [48ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] VS Code (version 1.98.2) [44ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Connected device (3 available) [7.3s]
    • iPhone 16 pro max (mobile) • 00008140-00194CC23A68801C • ios            • iOS 18.3.2 22D82
    • macOS (desktop)            • macos                     • darwin-x64     • macOS 15.3.2 24D81 darwin-x64
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 134.0.6998.89

[✓] Network resources [490ms]
    • All expected network resources are available.

• No issues found!
```
</details>
