### ISSUE TITLE
[tool_crash] RangeError: RangeError: Value not in range: 353

### ISSUE THREAD

**Issue by Microcrab** [flutter/flutter#136008]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=00008101-001831223CB8001E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. Run ’main.dart‘

## Logs
RangeError: RangeError: Value not in range: 353
```
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:5234:5)
#1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1936:5)
#2      new Uint8List.view (dart:typed_data:883:19)
#3      decodeMDnsResponse.readResourceRecord (package:multicast_dns/src/packet.dart:343:23)
#4      decodeMDnsResponse (package:multicast_dns/src/packet.dart:372:38)
#5      MDnsClient._handleIncoming (package:multicast_dns/multicast_dns.dart:239:46)
#6      MDnsClient.start.<anonymous closure> (package:multicast_dns/multicast_dns.dart:160:47)
#7      _rootRunUnary (dart:async/zone.dart:1415:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#13     _StreamController._add (dart:async/stream_controller.dart:658:7)
#14     _StreamController.add (dart:async/stream_controller.dart:606:5)
#15     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2535:33)
#16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
```
```
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.13.6 on channel stable at /Users/yq05871/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (8 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yq05871/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/yq05871/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/XCode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (1 available)
    • 尛螃蟹的 iPhone 12 Pro Max (mobile) • 00008101-001831223CB8001E • ios • iOS 17.0.2 21A351
    ! Error: 尛螃蟹的Apple Watch has not finished loading development services. Please select a different device, or wait for the device to load development services and try again. (code 8)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.5.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 84a1e904f44f9b0e9c4510138010edcc653163f8
### Plugins
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
flutter_contacts-1.1.7+1
flutter_keyboard_visibility-5.4.3
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_plugin_android_lifecycle-2.0.16
fluttertoast-8.2.2
image_picker-1.0.4
image_picker_android-0.8.8+1
image_picker_for_web-3.0.1
image_picker_ios-0.8.8+2
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
mobcommonlib-1.1.5
mobile_scanner-3.4.1
mobsms-1.1.10
package_info_plus-4.1.0
path_provider-2.1.1
path_provider_android-2.2.0
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.0.1
permission_handler_android-11.0.5
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
shared_preferences-2.2.1
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.1
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.1
sharesdk_plugin-1.3.10
sqflite-2.3.0
sqlite3_flutter_libs-0.5.17
url_launcher-6.1.14
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.6
url_launcher_macos-3.0.7
url_launcher_web-2.0.20
url_launcher_windows-3.0.8

**Comment by darshankawar** [comment]
> #3      decodeMDnsResponse.readResourceRecord (package:multicast_dns/src/packet.dart:343:23)
> #4      decodeMDnsResponse (package:multicast_dns/src/packet.dart:372:38)
> #5      MDnsClient._handleIncoming (package:multicast_dns/multicast_dns.dart:239:46)
> #6      MDnsClient.start.<anonymous closure> (package:multicast_dns/multicast_dns.dart:160:47)

This is pointing to multicast_dns package. @Microcrab Are there concrete steps / code sample to replicate the error consistently that you can share here ?

**Comment by Microcrab** [comment]
目前没有复现的步骤或者代码。

**Comment by darshankawar** [comment]
@Microcrab 
Please write in English so that it'll be easier for anyone seeing this issue.
Labeling this based on the report, as I don't see a similar issue open currently.

**Comment by christopherfujino** [comment]
Unfortunately, I don't think there's much we can do at this time without reproducible steps. However, I will leave this open, and if there are more reports, hopefully we can narrow down a reproduction.
