### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH Command: /usr/bin/arch, OS error code: 72

### ISSUE THREAD

**Issue by Mugamba669** [flutter/flutter#136087]
## Command
```
flutter build macos
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH Command: /usr/bin/arch, OS error code: 72
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:278:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:324:30)
<asynchronous suspension>
#3      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:96:41)
<asynchronous suspension>
#4      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.5, on macOS 14.0 23A344 darwin-arm64, locale en-UG)
    [32m•[39m Flutter version 3.13.5 on channel stable at /Users/malticard/Downloads/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 12fccda598 (2 weeks ago), 2023-09-19 13:56:11 -0700
    [32m•[39m Engine revision bd986c5ed2
    [32m•[39m Dart version 3.1.2
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /Users/malticard/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m ANDROID_HOME = /Users/malticard/Android/Sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[32m[✓][39m VS Code (version 1.83.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.74.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.149

[33m[!][39m Network resources
    [31m✗[39m A network error occurred while checking "https://pub.dev/": Connection refused
    [31m✗[39m A network error occurred while checking "https://storage.googleapis.com/": Connection refused
    [31m✗[39m A network error occurred while checking "https://maven.google.com/": Connection refused
    [31m✗[39m A network error occurred while checking "https://cocoapods.org/": Connection refused
    [31m✗[39m A network error occurred while checking "https://github.com/": Connection refused

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ff5b5b5fa6f35b717667719ddfdb1521d8bdd05a
### Plugins
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+2
file_selector_windows-0.9.3+1
flutter_native_splash-2.3.2
flutter_plugin_android_lifecycle-2.0.16
fluttertoast-8.2.2
image_cropper-5.0.0
image_cropper_for_web-3.0.0
image_picker-1.0.4
image_picker_android-0.8.8
image_picker_for_web-3.0.1
image_picker_ios-0.8.8+2
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.1
path_provider_android-2.2.0
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.1
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.1
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.1
sqflite-2.3.0
url_launcher-6.1.14
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.6
url_launcher_macos-3.0.7
url_launcher_web-2.0.20
url_launcher_windows-3.0.8

**Comment by danagbemava-nc** [comment]
Hi @Mugamba669, can you try https://stackoverflow.com/a/72423768 to see if it helps?

**Comment by Mugamba669** [comment]
okay thanks

**Comment by danagbemava-nc** [comment]
Hi @Mugamba669, did that resolve your issue?

**Comment by Mugamba669** [comment]
The problem was actually with my xcode, i had to redownload xcode. I was
using ventura but when i switched to sonoma it got corrupted.

**Comment by huycozy** [comment]
@Mugamba669 Do you mean the issue still appears even after you followed the solution mentioned in the SO link above? 

>Open Xcode and choose a version to point
Xcode -> Preferences -> Locations -> Command Line Tools -> XX.XX

Looking at the output of `flutter doctor -v`, it indicated `Xcode installation is incomplete`, please make sure it's complete and retry to see if the issue still persists.
