### ISSUE TITLE
After upgrades of iOS, MacOS and Xcode 15-->failed to build iOS app. Could not build precompiled application for the device. Parse issue (Xcode)

### ISSUE THREAD

**Issue by wjmetcalfiiii** [flutter/flutter#136077]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Resurrecting and updating/upgrading an app (not mine) with an original iOS target of 12.0.  I bit the bullet and chose iOS 16.6.1 on an iPhone 14 Pro and MacOS 14.0 Sonoma as the new development environment a few weeks ago. I have immersed myself in yaml, flutter, pods and podfiles. I am now running Xcode 15 after upgrading from 14. Prior to the OS upgrades, the app worked fine and could be deployed to the iPhone 14 Pro and was deployed to iPhone 15 Pro iOS 17 (I'm looking at it function right now from an old build on this simulator). After the upgrade I cannot do a proper build.  Geolocator_apple-2.3.2 does not match the geolocator_apple-1.2.0 listed in the flutter diagnostics. Possible issue? Same thing happens on the Simulator no matter the target. Verbose log attached as a file (it is gargantuan but has everything in it). Flutter doctor all fine. I must admit scripting some of these flutter and pod commands seems often times like everyone has their own cookbook when I scour the ideas to fix thing.

/*-Setting up the flutter/pod stuff---------------------------------*/
/*-Setting up the flutter/pod stuff---------------------------------*/
/*-Setting up the flutter/pod stuff---------------------------------*/

```
cd /Users/wjmetcalfiii/AndroidStudio/myPOH/ios
clear
flutter pub upgrade --major-versions
pod cache clean --all
pod deintegrate
sudo gem install cocoapods-deintegrate cocoapods-clean
sudo arch -arm64 gem install ffi
pod setup
pod repo remove trunk
arch -arm64 pod install
pod update
flutter run --verbose > flutter_job_verbose_log.txt
```

/*-Log output from the above script--------------------------------*/
/*-Log output from the above script--------------------------------*/
/*-Log output from the above script--------------------------------*/
/*-Log output from the above script--------------------------------*/

```
Resolving dependencies in ..... 
  _discoveryapis_commons 1.0.6
  _fe_analyzer_shared 61.0.0 (64.0.0 available)
  analyzer 5.13.0 (6.2.0 available)
  args 2.4.2
  async 2.11.0
  audio_streamer 4.0.0
  boolean_selector 2.1.1
  characters 1.3.0
  charts_common 0.12.0 (discontinued)
  charts_flutter 0.12.0 (discontinued)
  clock 1.1.1
  collection 1.17.2 (1.18.0 available)
  convert 3.1.1
[flutter_job_verbose_log.txt](https://github.com/flutter/flutter/files/12833759/flutter_job_verbose_log.txt)

  crypto 3.0.3
  csslib 1.0.0
  cupertino_icons 1.0.6
  dbus 0.7.8
  expandable 5.0.1
  fake_async 1.3.1
  ffi 2.1.0
  file 7.0.0
  flutter 0.0.0 from sdk flutter
  flutter_plugin_android_lifecycle 2.0.16
  flutter_test 0.0.0 from sdk flutter
  flutter_web_plugins 0.0.0 from sdk flutter
  geolocator 10.1.0
  geolocator_android 4.3.1
  geolocator_apple 2.3.2
  geolocator_platform_interface 4.1.1
  geolocator_web 2.2.0
  geolocator_windows 0.2.1
  glob 2.1.2
  google_identity_services_web 0.2.1+1
  google_maps 6.3.0
  google_maps_flutter 2.5.0
  google_maps_flutter_android 2.5.1
  google_maps_flutter_ios 2.3.1
  google_maps_flutter_platform_interface 2.4.1
  google_maps_flutter_web 0.5.4+2
  google_sign_in 6.1.5
  google_sign_in_android 6.1.20
  google_sign_in_ios 5.6.4
  google_sign_in_platform_interface 2.4.2
  google_sign_in_web 0.12.0+5
  googleapis 11.4.0
  html 0.15.4
  http 1.1.0
  http_parser 4.0.2
  intl 0.17.0 (0.18.1 available)
  js 0.6.7
  js_wrapping 0.7.4
  logging 1.2.0
  matcher 0.12.16
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.10.0 available)
  nested 1.0.0
  network_info_plus 4.0.2
  network_info_plus_platform_interface 1.1.3
  nm 0.5.0
  noise_meter 5.0.2
  open_file 3.3.2
  package_config 2.1.0
  package_info_plus 4.1.0
  package_info_plus_platform_interface 2.0.1
  path 1.8.3
  path_provider 2.1.1
  path_provider_android 2.2.0
  path_provider_foundation 2.3.1
  path_provider_linux 2.2.1
  path_provider_platform_interface 2.1.1
  path_provider_windows 2.2.1
  permission_handler 11.0.1
  permission_handler_android 11.0.5
  permission_handler_apple 9.1.4
  permission_handler_platform_interface 3.11.5
  permission_handler_windows 0.1.3
  petitparser 5.4.0 (6.0.1 available)
  pigeon 11.0.1 (12.0.0 available)
  platform 3.1.2
  plugin_platform_interface 2.1.6
  provider 6.0.5
  pub_semver 2.1.4
  quiver 3.2.1
  sanitize_html 2.1.0
  sensors_plus 3.0.3
  sensors_plus_platform_interface 1.1.3
  sky_engine 0.0.99 from sdk flutter
  source_span 1.10.0
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  stream_transform 2.1.0
  string_scanner 1.2.0
  term_glyph 1.2.1
  test_api 0.6.0 (0.6.1 available)
  typed_data 1.3.2
  udp 5.0.3
  uuid 3.0.7 (4.1.0 available)
  vector_math 2.1.4
  wakelock 0.4.0 (0.6.2 available)
  wakelock_macos 0.1.0+3 (0.4.0 available)
  wakelock_platform_interface 0.2.1+3 (0.3.0 available)
  wakelock_web 0.2.0+3 (0.4.0 available)
  watcher 1.1.0
  web 0.1.4-beta (0.2.2-beta available)
  win32 5.0.9
  xdg_directories 1.0.3
  xml 6.3.0 (6.4.2 available)
  yaml 3.1.2
No dependencies changed in ...
2 packages are discontinued.
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
```

```
No changes to pubspec.yaml!
Ignoring ffi-1.16.1 because its extensions are not built. Try: gem pristine ffi --version 1.16.1
Ignoring ffi-1.16.1 because its extensions are not built. Try: gem pristine ffi --version 1.16.1
Deintegrating `Runner.xcodeproj`
Deleted 1 'Copy Pods Resources' build phases.
Deleted 1 'Check Pods Manifest.lock' build phases.
Deleted 1 'Embed Pods Frameworks' build phases.
- Pods_Runner.framework
Deleting Pod file references from project
- Pods-Runner.debug.xcconfig
- Pods-Runner.release.xcconfig
- Pods-Runner.profile.xcconfig
Deleted 1 empty `Frameworks` groups from project.
Removing `Pods` directory.

Project has been deintegrated. No traces of CocoaPods left in project.
Note: The workspace referencing the Pods project still remains.
Successfully installed cocoapods-deintegrate-1.0.5
Parsing documentation for cocoapods-deintegrate-1.0.5
Done installing documentation for cocoapods-deintegrate after 0 seconds
Successfully installed cocoapods-clean-0.0.1
Parsing documentation for cocoapods-clean-0.0.1
Done installing documentation for cocoapods-clean after 0 seconds
2 gems installed
Building native extensions. This could take a while...
Successfully installed ffi-1.16.3
Parsing documentation for ffi-1.16.3
Done installing documentation for ffi after 3 seconds
1 gem installed
Ignoring ffi-1.16.1 because its extensions are not built. Try: gem pristine ffi --version 1.16.1
Setup completed
Ignoring ffi-1.16.1 because its extensions are not built. Try: gem pristine ffi --version 1.16.1
Removing spec repo `trunk`
Ignoring ffi-1.16.1 because its extensions are not built. Try: gem pristine ffi --version 1.16.1
Analyzing dependencies
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
Downloading dependencies
Installing AppAuth (1.6.2)
Installing Flutter (1.0.0)
Installing GTMAppAuth (1.3.1)
Installing GTMSessionFetcher (2.3.0)
Installing GoogleMaps (7.4.0)
Installing GoogleSignIn (6.2.4)
Installing audio_streamer (0.0.1)
Installing geolocator_apple (1.2.0)
Installing google_maps_flutter_ios (0.0.1)
Installing google_sign_in_ios (0.0.1)
Installing network_info_plus (0.0.1)
Installing open_file (0.0.1)
Installing package_info_plus (0.4.5)
Installing path_provider_foundation (0.0.1)
Installing permission_handler_apple (9.1.1)
Installing sensors_plus (0.0.1)
Installing wakelock (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 12 dependencies from the Podfile and 17 total pods installed.
Ignoring ffi-1.16.1 because its extensions are not built. Try: gem pristine ffi --version 1.16.1
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 12 dependencies from the Podfile and 17 total pods installed.

Build exception thrown.........


[        ] Parse Issue (Xcode): Expected expression
           /Users/wjmetcalfiii/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.2/ios/Classes/GeolocatorPlugin.m:186:54

[        ] Semantic Issue (Xcode): Use of undeclared identifier 'options'
           /Users/wjmetcalfiii/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.2/ios/Classes/GeolocatorPlugin.m:186:28

[        ] Semantic Issue (Xcode): Use of undeclared identifier 'completionHandler'
           /Users/wjmetcalfiii/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.2/ios/Classes/GeolocatorPlugin.m:186:36

[        ] Could not build the application for the simulator.
[        ] Error launching application on iPad Pro (11-inch) (4th generation).
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

wjmetcalfiii@Jims-Mac-mini ios % 

### Actual results

I am unable to build the iOS app and then deploy it to either a physical phone or simulator phone.

### Logs

<details>
<summary>Logs</summary>

```console

Log attached in first section

```

</details>

### Flutter Doctor output

wjmetcalfiii@Jims-Mac-mini ios % flutter doctor --verbose
```
[✓] Flutter (Channel stable, 3.13.2, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.13.2 on channel stable at /Users/wjmetcalfiii/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (6 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wjmetcalfiii/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Users/wjmetcalfiii/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] VS Code (version 1.82.0)
    • VS Code at /Users/wjmetcalfiii/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • 9FC53206-A19C-4770-BA1E-0563981293C1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
wjmetcalfiii@Jims-Mac-mini ios % 

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
> [        ] Parse Issue (Xcode): Expected expression
>            /Users/wjmetcalfiii/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.2/ios/Classes/GeolocatorPlugin.m:186:54
> 
> [        ] Semantic Issue (Xcode): Use of undeclared identifier 'options'
>            /Users/wjmetcalfiii/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.2/ios/Classes/GeolocatorPlugin.m:186:28
> 
> [        ] Semantic Issue (Xcode): Use of undeclared identifier 'completionHandler'
>            /Users/wjmetcalfiii/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.2/ios/Classes/GeolocatorPlugin.m:186:36

@wjmetcalfiiii 
These errors are pointing to [geolocator](https://pub.dev/packages/geolocator) package which is third party. Since you upgraded your setup to latest, maybe the package is incompatible with the latest updates, so I suggest you to file this issue in dedicated [repo](https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen) for further updates.
I'll close this for now from here, as this looks like a package compatiblility issue with latest iOS, macOS and Xcode config.
If you disagree, write in comments and I'll reopen it.
