### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: Is a directory, errno = 21

### ISSUE THREAD

**Issue by phillipohwotemu** [flutter/flutter#136137]
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: Is a directory, errno = 21
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.createSync (dart:io/file_impl.dart:306:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26:16)
#3      ErrorHandlingFile.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:283:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.createSync (package:flutter_tools/src/base/error_handling_io.dart:282:5)
#6      _updateGeneratedXcodePropertiesFile (package:flutter_tools/src/ios/xcode_build_settings.dart:78:32)
#7      updateGeneratedXcodeProperties (package:flutter_tools/src/ios/xcode_build_settings.dart:49:3)
<asynchronous suspension>
#8      IosProject._updateGeneratedXcodeConfigIfNeeded (package:flutter_tools/src/xcode_project.dart:548:7)
<asynchronous suspension>
#9      IosProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/xcode_project.dart:468:5)
<asynchronous suspension>
#10     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:362:7)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1

**Comment by danagbemava-nc** [comment]
Hi @phillipohwotemu, please provide the output of `flutter doctor -v`
