### ISSUE TITLE
`fatal error C1083: Cannot open include file: 'include/flutter_secure_storage_windows/flutter_secure_storage_windows_plugin.h': No such file or directory` error on Windows

### ISSUE THREAD

**Issue by hpelitebook745G2** [flutter/flutter#136159]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

My app works on Mac and I want to extend to support for Windows. The error below is preventing my whole app from building and running.

I have both tried Visual Studio 2019 and 2022 and installed respective [C++ ATL libraries](https://github.com/mogol/flutter_secure_storage#configure-windows-version).

I am aware of these issues as well:
https://stackoverflow.com/q/11123088/1968739
https://stackoverflow.com/q/3898287/1968739

### Expected results

My app works on Mac and I want to extend to support for Windows.

### Actual results

I got this error:
```
C:\Users\<user>\test_app\windows\flutter\ephemeral\.plugin_symlinks\flutter_secure_storage_windows\windows\flutter_secure_storage_windows_plugin.cpp(1,10): fatal  error C1083: Cannot open include file: 'include/flutter_secure_storage_windows/flutter_secure_storage_windows_plugin.h': No such file or directory [C:\Users\<user>\test_app\build\windows\x64\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj]
```

Please see the verbose logs below for more details.

### Code sample

<details><summary>My dependencies:</summary>

```dart
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ...
  <my-custom-packages-here>
  ...
  flutter_secure_storage: ^9.0.0
  biometric_storage: ^5.0.0
  local_auth: ^2.1.6
  flutter_local_authentication: ^0.0.3
  system_tray: ^2.0.3
  provider: ^6.0.5
  window_manager: ^0.3.5
  get_it: ^7.6.4
  flutter_local_notifications: ^15.1.1
  flutter_platform_alert: ^0.4.0
```

</details>

### Screenshots or Video

VS 2019:
![VS 2019](https://github.com/flutter/flutter/assets/27658429/3e3e7773-f240-4cb9-b893-79f98090d919)

VS 2022:
![VS 2022_1](https://github.com/flutter/flutter/assets/27658429/b1b066e9-a96c-44d8-b2b4-86db637d44df)
![VS 2022_2](https://github.com/flutter/flutter/assets/27658429/fa432516-cc0a-4987-ac86-89e71b8bca36)

### Logs

<details><summary>Verbose Logs where the error occurred:</summary>

```console
...
[ +463 ms] Link:
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\<user>\test_app\build\windows\x64\plugins\window_manager\Debug\window_manager_plugin.dll" /INCREMENTAL /ILK:"window_manager_plugin.dir\Debug\window_manager_plugin.ilk" /NOLOGO ..\..\flutter\Debug\flutter_wrapper_plugin.lib "C:\Users\<user>\test_app\windows\flutter\ephemeral\flutter_windows.dll.lib" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/<user>/test_app/build/windows/x64/plugins/window_manager/Debug/window_manager_plugin.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/<user>/test_app/build/windows/x64/plugins/window_manager/Debug/window_manager_plugin.lib" /MACHINE:X64  /machine:x64 /DLL window_manager_plugin.dir\Debug\window_manager.obj
[        ]   window_manager_plugin.dir\Debug\window_manager_plugin.obj
[ +177 ms]      Creating library C:/Users/<user>/test_app/build/windows/x64/plugins/window_manager/Debug/window_manager_plugin.lib and object C:/Users/<user>/test_app/build/windows/x64/plugins/window_manager/Debug/window_manager_plugin.exp
[ +221 ms]   window_manager_plugin.vcxproj -> C:\Users\<user>\test_app\build\windows\x64\plugins\window_manager\Debug\window_manager_plugin.dll
[  +18 ms] FinalizeBuildStatus:
[        ]   Deleting file "window_manager_plugin.dir\Debug\window_m.0D08092A.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "window_manager_plugin.dir\Debug\window_m.0D08092A.tlog\window_manager_plugin.lastbuildstate".
[   +1 ms] Done Building Project "C:\Users\<user>\test_app\build\windows\x64\plugins\window_manager\window_manager_plugin.vcxproj" (default targets).
[   +1 ms] Done Building Project "C:\Users\<user>\test_app\build\windows\x64\runner\test_app.vcxproj" (default targets) -- FAILED.
[        ] Done Building Project "C:\Users\<user>\test_app\build\windows\x64\ALL_BUILD.vcxproj" (default targets) -- FAILED.
[        ] Done Building Project "C:\Users\<user>\test_app\build\windows\x64\INSTALL.vcxproj" (default targets) -- FAILED.
[  +42 ms] Build FAILED.
[   +7 ms] "C:\Users\<user>\test_app\build\windows\x64\INSTALL.vcxproj" (default target) (1) ->
[        ] "C:\Users\<user>\test_app\build\windows\x64\ALL_BUILD.vcxproj" (default target) (3) ->
[        ] "C:\Users\<user>\test_app\build\windows\x64\runner\test_app.vcxproj" (default target) (4) ->
[        ] "C:\Users\<user>\test_app\build\windows\x64\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj" (default target) (8) ->
[        ] (ClCompile target) -> 
[        ]   C:\Users\<user>\test_app\windows\flutter\ephemeral\.plugin_symlinks\flutter_secure_storage_windows\windows\flutter_secure_storage_windows_plugin.cpp(1,10): fatal  error C1083: Cannot open include file: 'include/flutter_secure_storage_windows/flutter_secure_storage_windows_plugin.h': No such file or directory [C:\Users\<user>\test_app\build\windows\x64\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj]
[        ]     0 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:01:39.81
[  +54 ms] Exception: Build process failed.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:667:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
2

[  +35 ms] "flutter run" took 133,843ms.
[  +58 ms] ensureAnalyticsSent: 51ms
[        ] Running 1 shutdown hook
[  +13 ms] Shutdown hooks complete
[        ] exiting with code 1

Exited (1).
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.16.0-6.0.pre.29, on Microsoft Windows [Version 10.0.22000.2295], locale en-US)
    • Flutter version 3.16.0-6.0.pre.29 on channel master at C:\tools\flutter_windows_3.10.6-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5207a309e8 (34 hours ago), 2023-10-07 02:51:32 -0400
    • Engine revision 8711c1fd21
    • Dart version 3.3.0 (build 3.3.0-0.0.dev)
    • DevTools version 2.28.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\<user>\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\<user>\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.83.0)
    • VS Code at C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2295]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.60

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
> I have both tried Visual Studio 2019 and 2022 and installed respective [C++ ATL libraries](https://github.com/mogol/flutter_secure_storage#configure-windows-version).
> 
> I am aware of these issues as well: https://stackoverflow.com/q/11123088/1968739 https://stackoverflow.com/q/3898287/1968739

I'm not sure why you believe this is related to ATL; the error isn't about ATL headers.

The error here is coming from the build of a third-party plugin, so this needs to be reported to the plugin authors. Closing as this is not a Flutter bug.
