### ISSUE TITLE
Flutter crash when build flutter_view with XCode9.2

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#13639]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --suppress-analytics build aot --output-dir=build/aot --target-platform=ios --target=lib/main.dart --interpreter --debug

## exception

SocketException: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = storage.googleapis.com, port = 443

```
#0      _attempt (package:flutter_tools/src/base/net.dart:40)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:452)
<asynchronous suspension>
#3      _downloadZipArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:459)
<asynchronous suspension>
#4      _withTemporaryFile (package:flutter_tools/src/cache.dart:480)
<asynchronous suspension>
#5      _downloadZipArchive (package:flutter_tools/src/cache.dart:458)
#6      FlutterEngine._downloadItem (package:flutter_tools/src/cache.dart:424)
#7      FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:392)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:247)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:220)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:242)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1120)
#22     _CustomZone.run (dart:async/zone.dart:1001)
#23     runZoned (dart:async/zone.dart:1467)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:44)
<asynchronous suspension>
#27     main (file:///Users/carlos/Documents/GitHub/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for /Users/carlos/Documents/GitHub/flutter/bin/cache/artifacts/engine/darwin-x64/dart-sdk/bin/dart.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
#2      Cache.engineDartVersion (package:flutter_tools/src/cache.dart:139)
#3      FlutterVersion.engineDartVersion (package:flutter_tools/src/version.dart:69)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:212)
<asynchronous suspension>
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:106)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:236)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1120)
#10     _CustomZone.run (dart:async/zone.dart:1001)
#11     runZoned (dart:async/zone.dart:1467)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:236)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:211)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:166)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:93)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:44)
<asynchronous suspension>
#25     main (file:///Users/xxx/Documents/GitHub/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by realcarlos** [comment]
also when I type flutter upgrade 
Upgrading Flutter from /Users/xxx/Documents/GitHub/flutter...
Already up-to-date.

Upgrading engine...
Downloading package sky_engine...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.

**Comment by cbracken** [comment]
@realcarlos Thanks for filing! Could you please attach the output of a `flutter doctor` run?

Can you also try the following steps and report back whether it helps?
1. Delete your flutter install's cache directory: from your flutter install directory `rm -rf bin/cache`.
2. Type `flutter doctor` to re-download the binaries.

**Comment by realcarlos** [comment]
Thank you ! Solved ,I will close this issue.
