### ISSUE TITLE
[go_router] Calling pop from initial route

### ISSUE THREAD

**Issue by ixsans** [flutter/flutter#136313]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm exploring go_router as navigation solution for my Flutter app and facing a simple scenario I'm struggling with.

I have initial route /home that navigate screen to HomePage. Inside HomePage I have a close button to just simply close HomePage, which is the first stack of the screens.

I was expecting that I can do something exactly the same to what I do using standard Navigator: Navigator.of(context).pop() that will close entire app since I'm in the first stack of the route.

But when I call context.pop() it gives me the following error:

```
======== Exception caught by gesture ===============================================================
The following GoError was thrown while handling a gesture:
There is nothing to pop

When the exception was thrown, this was the stack: 
#0      GoRouterDelegate.pop (package:go_router/src/delegate.dart:94:5)
#1      GoRouter.pop (package:go_router/src/router.dart:492:20)
#2      GoRouterHelper.pop (package:go_router/src/misc/extensions.dart:71:65)
#3      HomeView.build.<anonymous closure> (package:navigation/home_view.dart:25:33)
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1096:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#17     _invoke1 (dart:ui/hooks.dart:164:13)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#94750
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(165.4, 119.6)
  finalLocalPosition: Offset(31.6, 25.6)
  button: 1
  sent tap down
====================================================================================================
``` 

### Expected results

I'm expecting that I can do something exactly the same to what I do using standard Navigator: Navigator.of(context).pop() that will close entire app when I am in the first stack of the route.

### Actual results

It gives the following error when call `context.pop()` from the initial route (first stack):

```
======== Exception caught by gesture ===============================================================
The following GoError was thrown while handling a gesture:
There is nothing to pop
```

### Code sample

<details><summary>Code sample</summary>

```dart
final router = GoRouter(
    navigatorKey: _rootNavigatorKey,
    initialLocation: '/home',
    routes: [
      GoRoute(
        parentNavigatorKey: _rootNavigatorKey,
        path: '/home',
        builder: (context, state) =>
            const HomePage(),
      )
    ]);
    
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
        title: 'Flutter Demo',
        routerConfig: router,);
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: Container(
        color: Colors.purple,
        child: Center(
            child: ElevatedButton(
          onPressed: () {
            context.pop();
          },
          child: const Text('Close'),
        )),
      ),
    );
  }
}    
    
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.0, on macOS 13.5.1 22G90 darwin-x64, locale en-ID)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.18.7/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/ixsans/fvm/versions/3.10.0. Consider adding /Users/ixsans/fvm/versions/3.10.0/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2021.3)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @ixsans
Can you take a look at [this](https://stackoverflow.com/a/76008627) and check if it helps in your case or not ?
Also I suggest you to go through go_router's [documentation](https://pub.dev/packages/go_router#documentation) as well as migration [guide](https://pub.dev/packages/go_router#migration-guides) and see if it helps in your context or not.

**Comment by ixsans** [comment]
Hi @darshankawar thanks, the SO link you provide has different scenario with mine. That's about pop from second screen to previous one. 
But in my case is actually just very simple where I only have one page (Home) as initial route specified in goRouter initialization, and i just wanted to close my app like what I used to do using `Navigator.of(context).pop()`.

Actually I can do with `SystemNavigator.pop()`, but I would like to know if there's `go_router` solution for this.

**Comment by darshankawar** [comment]
Thanks for the update. Can you check [this](https://stackoverflow.com/questions/75873393/alternative-to-popuntil-in-go-router-in-flutter) and see if it helps to answer your question ?

**Comment by ixsans** [comment]
The link you post is talking about `popUntil` which is different case in which it will pop until particular route. But I think my my case here pretty clear which is just to pop first navigation stack to exit app.

**Comment by darshankawar** [comment]
Thanks for the update. I am going to keep this issue open and label for team's attention for the behavior and error reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.13.6, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.6 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.16.0-10.0.pre.68, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.16.0-10.0.pre.68 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7d79472531 (2 hours ago), 2023-10-13 04:35:46 +0200
    • Engine revision ffb3b5b67f
    • Dart version 3.3.0 (build 3.3.0-19.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by chunhtai** [comment]
The Navigator.pop will pop to a black screen.
This is the code I was using
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app demonstrates how to use GoRoute.onExit.
void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Builder(
          builder: (context) => Center(child: ElevatedButton(child: Text('o'), onPressed: () => Navigator.of(context).pop(),),
      )),
    ),
  ));
  // WidgetsFlutterBinding.ensureInitialized().ensureSemantics();
}
```

SystemNavigator.pop only works for Android, it won't work for iOS. I don't think an app closing itself is a good user experience though, that is also why iOS doesn't provide an API to close the app.
