### ISSUE TITLE
[tool_crash] WebDriverException

### ISSUE THREAD

**Issue by suhailzoft** [flutter/flutter#136375]
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome --web-port=4444
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WebDriverException
```
#0      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:94:7)
#1      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#2      createDriver (package:webdriver/async_core.dart:64:19)
<asynchronous suspension>
#3      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
<asynchronous suspension>
#4      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:309:30)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<async

**Comment by darshankawar** [comment]
Thanks for the report @suhailzoft 
Can you provide `flutter doctor -v` ? Does this crash occur everytime you run the said command ?
Can you also check if you get any output after running `chromedriver --verbose` and provide the same here ?
