### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Uri c:/Users/Lokesh%20Upputri/Desktop/SimpleWebApp/test_project/lib/fonts/Poppins-Regular.ttf must have scheme 'file:'.

### ISSUE THREAD

**Issue by LokiBoyy** [flutter/flutter#136439]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Uri c:/Users/Lokesh%20Upputri/Desktop/SimpleWebApp/test_project/lib/fonts/Poppins-Regular.ttf must have scheme 'file:'.
```
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:86:7)
#1      Context.fromUri (package:path/src/context.dart:1040:32)
#2      ManifestAssetBundle._resolveAsset (package:flutter_tools/src/asset.dart:966:47)
#3      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:857:34)
#4      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:262:54)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:502:26)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:308:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22621.2283], locale de-DE)
    [32m•[39m Flutter version 3.10.1 on channel stable at C:\Flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision d3d8effc68 (5 months ago), 2023-05-16 17:59:05 -0700
    [32m•[39m Engine revision b4fb11214d
    [32m•[39m Dart version 3.0.1
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at C:\Users\Lokesh Upputri\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.17)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.32630.194
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[32m[✓][39m VS Code (version 1.83.1)
    [32m•[39m VS Code at C:\Users\Lokesh Upputri\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.74.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.152
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.60

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: d3d8effc686d73e0114d71abdcccef63fa1f25d2

**Comment by huycozy** [comment]
Hi @LokiBoyy 
Could you always reproduce this issue or does it only occur one time? If it occurs persistently, please share a minimal sample code so we can investigate this issue. Thank you!

Maybe similar/related: https://github.com/flutter/flutter/issues/116737
