### ISSUE TITLE
`Linux Framework Smoke Tests` continually timing out

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#136483]
`Linux Framework Smoke Tests` has timed out 3 times in a row.  The errors printed out to the screen are not apropos to the changes in [the PR](https://github.com/flutter/engine/pull/46738).

# example timeout

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Framework%20Smoke%20Tests/38544/overview

## log
```
/b/s/w/ir/cache/flutter/packages/flutter/test/widgets/widget_inspector_test.dart
TestDeviceException(Shell subprocess crashed with SIGTERM (-15).)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:241:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:223:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:510:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:566:11)
<asynchronous suspension>

unhandled error during finalization of test:
/b/s/w/ir/cache/flutter/packages/flutter/test/widgets/widget_inspector_test.dart
PathNotFoundException: Deletion failed, path = '/b/s/w/ir/x/t/flutter_tools.LVBCTA/flutter_test_listener.QYVPPP' (OS Error: No such file or directory, errno = 2)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:193:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:414:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      FlutterPlatform._createListenerDart.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:602:15)
#4      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:566:26)
<asynchronous suspension>

```

**Comment by gaaclarke** [comment]
I don't know if those errors getting printed out are related to some hang, or are a result of cancelling the task after 60 minutes.

**Comment by gaaclarke** [comment]
I looked through the test `flutter/packages/flutter/test/widgets/widget_inspector_test.dart` to see if it is using `dart:ui/Image.toByteData` since that's where the change in the logic would happen in that PR.  There is no usage in that test and none of the error logs seem to match errors that would happen in `dart:ui/Image.toByteData`.

**Comment by gaaclarke** [comment]
This is probably the more apropos error message, all the tests are printing out something like:
```
22:36 +14740 ~132 -2: /b/s/w/ir/cache/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: layout explorer ext.flutter.inspector.getLayoutExplorerNode for RenderBox with BoxParentData [E]
  TimeoutException after 0:10:00.000000: Test timed out after 10 minutes.
  dart:isolate  _RawReceivePort._handleMessage
```

**Comment by gaaclarke** [comment]
I looked through other runs over the past 48 hours and I didn't see another timeout in different PRs.

**Comment by gaaclarke** [comment]
I wonder if this PR is just surfacing an error that was previously happening but was just manifesting as a print statement that was gobbled up.  Now it is an exception (who apparently is also getting gobbled up).  Maybe it is related to the skip for linux I had to add here: https://github.com/flutter/engine/pull/46738/files#diff-db8cb9c777f7c8430c97e5722237b95c297f2b18e0ace4b2f61442ccccb12597R232

I believe that skip is necessary not because of the platform though per say, but because of the status of impeller on other platforms.  These widget tests shouldn't be using impeller though.

**Comment by gaaclarke** [comment]
I'm able to reproduce this locally, but it doesn't give much more information about the failure.  It looks like the failure is happening in a subprocess and the stdout/stderr is getting thrown away.
```
$ flutter -v --local-engine=host_debug_unopt --local-engine-host=host_debug_unopt --local-engine-src-path=/usr/local/google/home/aaclarke/dev/engine/src test ./test/widgets/widget_inspector_test.dart
...
[   +1 ms] test 0: Starting flutter_tester process with command=[/usr/local/google/home/aaclarke/dev/engine/src/out/host_debug_unopt/flutter_tester, --disable-vm-service,
--enable-checked-mode, --verify-entry-points, --enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling, --non-interactive, --use-test-fonts,
--disable-asset-fonts, --packages=/usr/local/google/home/aaclarke/dev/flutter/packages/flutter/.dart_tool/package_config.json,
--flutter-assets-dir=/usr/local/google/home/aaclarke/dev/flutter/packages/flutter/build/unit_test_assets,
/tmp/flutter_tools.VCZRFP/flutter_test_listener.LWWNDH/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
/tmp/flutter_tools.VCZRFP/flutter_test_fonts.HLBBII/fonts.conf, SERVER_PORT: 36717, APP_NAME: flutter, UNIT_TEST_ASSETS:
/usr/local/google/home/aaclarke/dev/flutter/packages/flutter/build/unit_test_assets}
[  +13 ms] test 0: Started flutter_tester process at pid 1120943
00:02 +0: loading /usr/local/google/home/aaclarke/dev/flutter/packages/flutter/test/widgets/widget_inspector_test.dart                                                     [ +528 ms] test 0: connected to test device, now awaiting test result
[        ] test 0: Waiting for test harness or tests to finish
00:47 +113 ~1: ext.flutter.inspector.screenshot                                                                                                                            ^C[+45695 ms] ensureAnalyticsSent: 14ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[   +9 ms] test 0: Test process is no longer needed by test harness
[        ] test 0: finished
[   +5 ms] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[        ] test 0: Terminating flutter_tester process
[        ] test 0: Shutting down DevTools server
[        ] test 0: Test harness is no longer needed by test process
[        ] test 0: Shutting down test harness socket server
[   +3 ms] test 0: flutter_tester process at pid 1120943 exited with code=-2
[        ] test 0: error while cleaning up; reporting to console
[        ] unhandled error during finalization of test:
           /usr/local/google/home/aaclarke/dev/flutter/packages/flutter/test/widgets/widget_inspector_test.dart
           TestDeviceException(Shell subprocess terminated by ^C (SIGINT, -2).)
           #0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:241:5)
           <asynchronous suspension>
           #1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:223:5)
           <asynchronous suspension>
           #2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:510:9)
           <asynchronous suspension>
           #3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:566:11)
           <asynchronous suspension>
           
[   +2 ms] test 0: deleting temporary directory
[   +1 ms] test 0: error while cleaning up; reporting to console
[   +2 ms] unhandled error during finalization of test:
           /usr/local/google/home/aaclarke/dev/flutter/packages/flutter/test/widgets/widget_inspector_test.dart
           PathNotFoundException: Deletion failed, path = '/tmp/flutter_tools.VCZRFP/flutter_test_listener.LWWNDH' (OS Error: No such file or directory, errno = 2)
           #0      _Directory._deleteSync (dart:io/directory_impl.dart:193:7)
           #1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:414:7)
           #2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
           #3      FlutterPlatform._createListenerDart.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:602:15)
           #4      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:566:26)
           <asynchronous suspension>
           
[        ] test 0: finished with out-of-band failure
00:47 +113 ~1 -1: loading /usr/local/google/home/aaclarke/dev/flutter/packages/flutter/test/widgets/widget_inspector_test.dart [E]                                         
  Exception: the Dart compiler exited unexpectedly.
  package:flutter_tools/src/base/common.dart 10:3  throwToolExit
  package:flutter_tools/src/compile.dart 896:9     DefaultResidentCompiler._compile.<fn>
  dart:async/zone.dart 1407:47                     _rootRunUnary
  dart:async/zone.dart 1308:19                     _CustomZone.runUnary
  dart:async/future_impl.dart 846:45               Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 875:13               Future._propagateToListeners
  dart:async/future_impl.dart 647:5                Future._completeWithValue
  dart:async/future_impl.dart 721:7                Future._asyncCompleteWithValue.<fn>
  dart:async/zone.dart 1399:13                     _rootRun
  dart:async/zone.dart 1301:19                     _CustomZone.run
  dart:async/zone.dart 1209:7                      _CustomZone.runGuarded
  dart:async/zone.dart 1249:23                     _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 40:21         _microtaskLoop
  dart:async/schedule_microtask.dart 49:5          _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13     _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 185:5      _RawReceivePort._handleMessage
```

**Comment by gaaclarke** [comment]
I'm removing infra, since I don't think there is something actionable for them.

**Comment by gaaclarke** [comment]
I was able to verify there is a fix for that PR.  There is some magic related to zones that provides zero feedback when it goes wrong.
