### ISSUE TITLE
Missing pillars for flutter-devicelab-mac-10	

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#136486]
```
[WARNING ] State for file: /etc/pki/flutter-devicelab-mac-10.mtv.corp.google.com.crt - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
local:
----------
          ID: /usr/local/share/ca-certificates/intca.crt
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.7-py3.7.egg/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.7-py3.7.egg/salt/loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.7-py3.7.egg/salt/states/file.py", line 3218, in managed
                  tmp_filename = salt.utils.files.mkstemp(suffix=tmp_ext, dir=tmp_dir)
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.7-py3.7.egg/salt/utils/files.py", line 106, in mkstemp
                  fd_, f_path = tempfile.mkstemp(*args, **kwargs)
                File "/opt/salt/lib/python3.7/tempfile.py", line 340, in mkstemp
                  return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
                File "/opt/salt/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
                  fd = _os.open(file, flags, 0o600)
              OSError: [Errno 30] Read-only file system: '__salt.tmp.cq2267lv'
     Started: 13:00:40.720635
    Duration: 179.718 ms
     Changes:  
```

**Comment by godofredoc** [comment]
This is now fixed. It was caused by machine_tokend failing to run and create the initial certificates.
