### ISSUE TITLE
[tool_crash] WebDriverException

### ISSUE THREAD

**Issue by therdm** [flutter/flutter#136490]
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/Test/login_test.dart -d chrome --web-port=4444
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WebDriverException
```
#0      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:97:7)
#1      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#2      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#3      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
<asynchronous suspension>
#4      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:332:30)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutt

**Comment by darshankawar** [comment]
Thanks for the report @therdm 
Can you provide flutter doctor -v ? Does this crash occur everytime you run the said command ?
Can you also check if you get any output after running chromedriver --verbose and provide the same here ?
Also, can you provide webdriver version you are using along with chrome version as well ?
