### ISSUE TITLE
Cannot profile device on iOS 17 + Sonoma

### ISSUE THREAD

**Issue by andreacimino** [flutter/flutter#136517]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. flutter run --profile --cache-sksl --purge-persistent-cache  

### Expected results

I should be able to profile the device.

### Actual results

2. Result otained:

```
Installing and launching...                                         5,5s
SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1051:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#2      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:212:7)
<asynchronous suspension>
#3      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:184:56)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:429:50)
<asynchronous suspension>
#5      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:656:22)
<asynchronous suspension>
#6      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:534:33)
<asynchronous suspension>
#7      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:753:27)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

```
### Code sample

flutter create my_app

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
!] Flutter (Channel [user-branch], 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale it)
    ! Flutter version 3.13.7 on channel [user-branch] at /Users/andrea/Downloads/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 2f708eb839 (4 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/andrea/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

⣟
⣿
⣽
⢿
[✓] Connected device (3 available)
    • iPhone di Andrea (mobile) • 00008030-0012544C3E32802E • ios            • iOS 17.0.3 21A360
    • macOS (desktop)           • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
From the log output, it seems similar to https://github.com/flutter/flutter/issues/78937 apart from some entries that are different in this issue's stacktrace, but it does seem to point to multicast_dns package which is also the case with the linked issue.
I'll tentatively close this issue in favor of https://github.com/flutter/flutter/issues/78937 based on the `SocketException` received and the error message and code being the same as linked issue.

/cc @stuartmorgan for look-in if this need to be tracked separately, as the flutter command is different from the tool_crash issue which was reported for `flutter attach`.

**Comment by andreacimino** [comment]
Please notice that at the moment we are not able to release our apps since:

1. Profiling does not work on real device
2. We cannot produce sksl warm-up file, unfortunately impeller at the moment is not a option.

Do you have any suggestions?

**Comment by stuartmorgan** [comment]
Does `flutter attach` work for you if you provide a target URL (which I believe will bypass the mDNS code that is erroring out here)? If so, you should be able to run directly from Xcode, adding whatever arguments are necessary, and then attach.

**Comment by andreacimino** [comment]
I will try and let you know, thanks for the support.

Il giorno ven 13 ott 2023 alle ore 17:16 stuartmorgan <
***@***.***> ha scritto:

**Comment by andreacimino** [comment]
That's the output from flutter attach.

`Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter attach

## exception

SocketException: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353

```
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1051:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#2      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:212:7)
<asynchronous suspension>
#3      MDnsVmServiceDiscovery.queryForAttach (package:flutter_tools/src/mdns_discovery.dart:91:56)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.getVMServiceUriForAttach (package:flutter_tools/src/mdns_discovery.dart:393:50)
<asynchronous suspension>
#5      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:380:22)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:271:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[!] Flutter (Channel [user-branch], 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale it)
    ! Flutter version 3.13.7 on channel [user-branch] at /Users/andrea/Downloads/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 2f708eb839 (5 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/andrea/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • iPhone di Andrea (mobile)       • 00008030-0012544C3E32802E • ios            • iOS 17.0.3 21A360
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • designed-for-ipad         • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.`

**Comment by stuartmorgan** [comment]
Please see my comment above; if you just run `flutter attach` without a target URL to attach to, you are using the same codepath as `flutter run`.

**Comment by andreacimino** [comment]
Sorry for not understanding properly the way to do it. What target URL should I use in order to attach? Should i see it from the logs of the app?
