### ISSUE TITLE
Hot reload causing weird error

### ISSUE THREAD

**Issue by Xyndra** [flutter/flutter#136584]
I am only filing this report since the error log told me to do so.
```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: RenderTable#149e1
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1965 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///D:/Code/Flutter/MemoryOrganizer/lib/main.dart:14:12
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1965:12)
#3      RenderBox.debugPaintSize.<anonymous closure> (package:flutter/src/rendering/box.dart:2723:41)
#4      RenderBox.debugPaintSize (package:flutter/src/rendering/box.dart:2725:6)
#5      RenderBox.debugPaint.<anonymous closure> (package:flutter/src/rendering/box.dart:2700:9)
#6      RenderBox.debugPaint (package:flutter/src/rendering/box.dart:2709:6)
#7      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:3162:7)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3166:6)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#13     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#15     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#16     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#17     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
#18     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
#19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#23     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:952:7)
#27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#9e57e
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=1120.0, h=1408.0)
...  size: Size(1120.0, 1408.0)
RenderObject: RenderSemanticsAnnotations#9e57e
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1120.0, h=1408.0)
  size: Size(1120.0, 1408.0)
...  child: RenderTable#149e1
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=1120.0, h=1408.0)
...    size: MISSING
...    default column width: FlexColumnWidth(1.0)
...    table size: 1×2
...    column offsets: 0.0
...    row offsets: 0.0
...    child (0, 0): RenderSemanticsAnnotations#f050a relayoutBoundary=up1 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0); default vertical alignment (can use size)
...      constraints: BoxConstraints(w=1120.0, 0.0<=h<=Infinity)
...      size: MISSING
...      child: RenderPhysicalModel#03895 relayoutBoundary=up2 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=1120.0, 0.0<=h<=Infinity)
...        size: MISSING
...        elevation: 0.0
...        color: Color(0xfffffbff)
...        shadowColor: Color(0xfffffbff)
...        shape: BoxShape.rectangle
...        borderRadius: BorderRadius.zero
...        child: _RenderInkFeatures#513f1 relayoutBoundary=up3 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=1120.0, 0.0<=h<=Infinity)
...          size: MISSING
...    child (0, 1): RenderPhysicalModel#d13bb NEEDS-LAYOUT NEEDS-PAINT
...      parentData: offset=Offset(0.0, 0.0); default vertical alignment
...      constraints: MISSING
...      size: MISSING
...      elevation: 0.0
...      color: Color(0xff303030)
...      shadowColor: Color(0xff303030)
...      shape: BoxShape.rectangle
...      borderRadius: BorderRadius.zero
...      child: _RenderInkFeatures#31830 NEEDS-LAYOUT NEEDS-PAINT
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        child: RenderCustomMultiChildLayoutBox#c3654 NEEDS-LAYOUT NEEDS-PAINT
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
====================================================================================================
```

**Comment by Xyndra** [comment]
I just found out that the log was way bigger, here is everything:
https://paste.gg/p/anonymous/587594049b0e4b47a03aef4a8487aca6

**Comment by Xyndra** [comment]
Seems to have been a hot  reload problem since it fixed itself after restart

**Comment by Xyndra** [comment]
I have added a lot more code since then, however the problem has disappeared.
It was some weird hot reload problem which completely disappeared after closing and reopening the window.

**Comment by darshankawar** [comment]
Closing for now, as this doesn't seem to be consistently replicable. If you get concrete steps to replicate, write in comments and I'll reopen it.
