### ISSUE TITLE
WebSocketChannelException seen frequently during iOS devicelab tests (flake)

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#13655]
E.g. https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci82OGJmNGIzYzYyZjM3NmJkNWZjNTE3ZTkzYzA3ZDJhNDg1YzRjMTJmDAsSBFRhc2sYgICAgICAoAoM

Log excerpt:
```text
stdout: [        ] [ 49%] Copying /Users/mac4/.cocoon/flutter/examples/flutter_gallery/build/ios/iphoneos/Runner.app/PkgInfo to device
stdout: [        ] [ 49%] Copying /Users/mac4/.cocoon/flutter/examples/flutter_gallery/build/ios/iphoneos/Runner.app/Runner to device
stdout: [ +602 ms] [ 52%] CreatingStagingDirectory
stdout: [        ] [ 57%] ExtractingPackage
stdout: [        ] [ 60%] InspectingPackage
stdout: [  +27 ms] [ 60%] TakingInstallLock
stdout: [  +19 ms] [ 65%] PreflightingApplication
stdout: [  +38 ms] [ 65%] InstallingEmbeddedProfile
stdout: [  +51 ms] [ 70%] VerifyingApplication
stdout: [ +485 ms] [ 75%] CreatingContainer
stdout: [  +13 ms] [ 80%] InstallingApplication
stdout: [   +5 ms] [ 85%] PostflightingApplication
stdout: [   +3 ms] [ 90%] SandboxingApplication
stdout: [  +24 ms] [ 95%] GeneratingApplicationMap
stdout: [  +82 ms] [100%] Installed package build/ios/iphoneos/Runner.app
stdout: [ +374 ms] ------ Debug phase ------
stdout: [        ] Starting debug of iPhone 6 (GSM) 'Emily Fortuna’s iPhone' (f2943620b1e218437e4014a75d136d5121f199d9) connected through USB...
stdout: [ +429 ms] [  0%] Looking up developer disk image
stdout: [+1083 ms] [ 90%] Mounting developer disk image
stdout: [ +116 ms] [ 95%] Developer disk image already mounted
stdout: [ +767 ms] [100%] Connecting to remote debug server
stdout: [        ] -------------------------
stdout: [ +171 ms] (lldb) command source -s 0 '/tmp/CFA78A83-12C3-487E-9FD1-2DDF7DCCE9EA/fruitstrap-lldb-prep-cmds-f2943620b1e218437e4014a75d136d5121f199d9'
stdout: [        ] Executing commands in '/tmp/CFA78A83-12C3-487E-9FD1-2DDF7DCCE9EA/fruitstrap-lldb-prep-cmds-f2943620b1e218437e4014a75d136d5121f199d9'.
stdout: [        ] (lldb)     platform select remote-ios --sysroot '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/10.3/Symbols'
stdout: [        ]   Platform: remote-ios
stdout: [        ]  Connected: no
stdout: [        ]   SDK Path: "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/10.3/Symbols"
stdout: [        ] (lldb)     target create "/Users/mac4/.cocoon/flutter/examples/flutter_gallery/build/ios/iphoneos/Runner.app"
stdout: [ +957 ms] Current executable set to '/Users/mac4/.cocoon/flutter/examples/flutter_gallery/build/ios/iphoneos/Runner.app' (arm64).
stdout: [        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/3C5E5390-31C2-4A55-801F-A0EED38C8EF7/Runner.app"
stdout: [   +1 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:55426"
stdout: [        ] (lldb)     command script import "/tmp/CFA78A83-12C3-487E-9FD1-2DDF7DCCE9EA/fruitstrap_f2943620b1e218437e4014a75d136d5121f199d9.py"
stdout: [  +18 ms] (lldb)     command script add -f fruitstrap_f2943620b1e218437e4014a75d136d5121f199d9.connect_command connect
stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_f2943620b1e218437e4014a75d136d5121f199d9.run_command run
stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_f2943620b1e218437e4014a75d136d5121f199d9.autoexit_command autoexit
stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_f2943620b1e218437e4014a75d136d5121f199d9.safequit_command safequit
stdout: [        ] (lldb)     connect
stdout: [  +38 ms] (lldb)     run
stdout: [ +489 ms] success
stdout: [        ] (lldb)     safequit
stdout: [ +126 ms] Process 15196 detached
stdout: [  +10 ms] Application launched on the device. Waiting for observatory port.
stdout: [ +732 ms] Observatory URL on device: http://127.0.0.1:52200/
stdout: [   +6 ms] /usr/local/bin/iproxy 8100 52200 f2943620b1e218437e4014a75d136d5121f199d9
stdout: [   +3 ms] Forwarded port ForwardedPort HOST:8100 to DEVICE:52200
stdout: [        ] Forwarded host port 8100 to device port 52200 for Observatory
stdout: [   +2 ms] Connecting to service protocol: http://127.0.0.1:8100/
stdout: [  +55 ms] "flutter run" took 69,704ms.
stderr: 
stderr: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 55428
stderr: #0      new IOWebSocketChannel._withoutSocket. (package:web_socket_channel/io.dart:83)
stderr: #1      _invokeErrorHandler (dart:async/async_error.dart:13)
stderr: #2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:286)
stderr: #3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:168)
stderr: #4      _rootRunBinary (dart:async/zone.dart:1140)
stderr: #5      _CustomZone.runBinary (dart:async/zone.dart:1023)
stderr: #6      _CustomZone.runBinaryGuarded (dart:async/zone.dart:917)
stderr: #7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:350)
stderr: #8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:368)
stderr: #9      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:266)
stderr: #10     _StreamController&&_SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:800)
stderr: #11     _StreamController._addError (dart:async/stream_controller.dart:675)
stderr: #12     _rootRunBinary (dart:async/zone.dart:1140)
stderr: #13     _CustomZone.runBinary (dart:async/zone.dart:1023)
stderr: #14     _CustomZone.runBinaryGuarded (dart:async/zone.dart:917)
stderr: #15     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:350)
stderr: #16     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:368)
stderr: #17     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:266)
stderr: #18     _StreamController&&_SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:800)
stderr: #19     _StreamController._addError (dart:async/stream_controller.dart:675)
stderr: #20     new Stream.fromFuture. (dart:async/stream.dart:110)
stderr: #21     _rootRunBinary (dart:async/zone.dart:1140)
stderr: #22     _CustomZone.runBinary (dart:async/zone.dart:1023)
stderr: #23     _FutureListener.handleError (dart:async/future_impl.dart:142)
stderr: #24     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:648)
stderr: #25     _Future._propagateToListeners (dart:async/future_impl.dart:669)
stderr: #26     _Future._completeError (dart:async/future_impl.dart:486)
stderr: #27     _Future._asyncCompleteError. (dart:async/future_impl.dart:536)
stderr: #28     _rootRun (dart:async/zone.dart:1120)
stderr: #29     _CustomZone.run (dart:async/zone.dart:1001)
stderr: #30     _CustomZone.bindCallback. (dart:async/zone.dart:928)
stderr: #31     _microtaskLoop (dart:async/schedule_microtask.dart:41)
stderr: #32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
stderr: #33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
stderr: #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
stderr: 
stdout: [   +7 ms] exiting with code 1
exitcode: 1
Task failed: Executable failed with exit code 1.

Stack trace:
package:flutter_devicelab/framework/utils.dart 77:3        fail
package:flutter_devicelab/framework/utils.dart 257:5       exec
===== asynchronous gap ===========================
dart:async                                                 _Completer.completeError
package:flutter_devicelab/framework/utils.dart 260:1       exec
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_devicelab/framework/utils.dart 235:10      exec
package:flutter_devicelab/framework/utils.dart 305:10      flutter
package:flutter_devicelab/tasks/perf_tests.dart 117:13     StartupTest.run.
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_devicelab/tasks/perf_tests.dart 110:54     StartupTest.run.
package:flutter_devicelab/framework/utils.dart 329:24      inDirectory
===== asynchronous gap ===========================
dart:async                                                 new Future.microtask
package:flutter_devicelab/framework/utils.dart 325:80      inDirectory
package:flutter_devicelab/tasks/perf_tests.dart 110:18     StartupTest.run
===== asynchronous gap ===========================
dart:async                                                 new Future.microtask
package:flutter_devicelab/tasks/perf_tests.dart 109:34     StartupTest.run
package:flutter_devicelab/framework/framework.dart 125:36  _TaskRunner._performTask.
===== asynchronous gap ===========================
dart:async                                                 new Future.microtask
package:flutter_devicelab/framework/framework.dart 124:28  _TaskRunner._performTask.
package:stack_trace                                        Chain.capture
package:flutter_devicelab/framework/framework.dart 124:11  _TaskRunner._performTask
package:flutter_devicelab/framework/framework.dart 84:39   _TaskRunner.run



Task failed with the following reason:
Task failed: Executable failed with exit code 1.
```

**Comment by cbracken** [comment]
@yjbanov who I believe has been looking into this.

**Comment by yjbanov** [comment]
This reappeared in the test lab after being gone for several months. I'm going to look into it today.

**Comment by chinmaygarde** [comment]
@yjbanov: This is the last remaining TODAY issue. Can you give a go/no-go on the beta roll?

**Comment by chinmaygarde** [comment]
I investigated this some more and the tool is port forwarding to one local port but connection to another port altogether. 8100 (remote) -> 52200 (local) -> 55428 (connect)

```
stdout: [   +3 ms] Forwarded port ForwardedPort HOST:8100 to DEVICE:52200
stdout: [        ] Forwarded host port 8100 to device port 52200 for Observatory
stdout: [   +2 ms] Connecting to service protocol: http://127.0.0.1:8100/
stdout: [  +55 ms] "flutter run" took 69,704ms.
stderr: 
stderr: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 55428
``

**Comment by colde** [comment]
@chinmaygarde That is no the case in #13747 though. So in that case, those might be separate issues.

**Comment by chinmaygarde** [comment]
@colde You're right. I am going to reopen that issue.

**Comment by yjbanov** [comment]
Port `port = 55428` is a red herring. That's not the target port that the source port. It's still attempting to connect to 8100. IOW it is attempting to connect to the _correct_ port.

**Comment by yjbanov** [comment]
This was not fixed by #16770. I will try a different method.

**Comment by tvolkert** [comment]
@yjbanov was it not fixed even by the follow-on https://github.com/flutter/flutter/pull/16785?  The flakes I had seen since then were entirely different flakes, so it looked like it was fixed.
