### ISSUE TITLE
`flutter build bundle` fails on latest beta

### ISSUE THREAD

**Issue by fertrig** [flutter/flutter#136547]
On macOS, the command below fails on latest beta `3.16.0-0.2.pre`. 

```
flutter build bundle -t lib/main.dart --debug --target-platform darwin --asset-dir flutter_assets --verbose
```

The same command works as expected on the previous beta version `3.15.0-15.2.pre` and it also works on latest stable `3.13.6`.

The error message seems to be: 
```
Target native_assets required define DarwinArchs but it was not provided
```

### Steps to reproduce:
1. Use flutter beta 3.16.0-0.2.pre
2. Create a new flutter project using flutter beta
3. Run the `flutter build bundle` command above inside that new project
4. Expect error message below

```
# Using flutter beta 3.16.0-0.2.pre

$ flutter create foo
$ cd foo
$ flutter build bundle -t lib/main.dart --debug --target-platform darwin --asset-dir flutter_assets --verbose
```

<details>
<summary>`flutter build bundle` output </summary>
<pre>
[   +8 ms] executing: sw_vers -productName
[  +23 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.5.1
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22G90
[        ] executing: uname -m
[   +5 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +5 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +81 ms] Skipping pub get: version match.
[ +232 ms] Generating /Users/PATH/TO/foo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +58 ms] Initializing file store
[  +15 ms] native_assets: Starting due to {}
[   +2 ms] Skipping target: gen_localizations
[   +9 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/Users/PATH/TO/foo/.dart_tool/package_config_subset}
[  +54 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Persisting file store
[   +2 ms] Done persisting file store
[   +2 ms] Target native_assets failed: Target native_assets required define DarwinArchs but it was not provided
           #0      NativeAssets.build (package:flutter_tools/src/build_system/targets/native_assets.dart:106:11)
           <asynchronous suspension>
           #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
           <asynchronous suspension>
           #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
           <asynchronous suspension>
           #4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
           <asynchronous suspension>
           #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
           <asynchronous suspension>
           #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
           <asynchronous suspension>
           #7      BundleBuilder.build (package:flutter_tools/src/bundle_builder.dart:75:32)
           <asynchronous suspension>
           #8      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:129:5)
           <asynchronous suspension>
           #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>

[  +12 ms] "flutter bundle" took 524ms.
[   +3 ms] Failed to build bundle.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      BundleBuilder.build (package:flutter_tools/src/bundle_builder.dart:85:7)
           <asynchronous suspension>
           #2      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:129:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[   +5 ms] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
</pre>
</details>

**Comment by PuzzleTakX** [comment]
The error message you're encountering, "Target native_assets required define DarwinArchs but it was not provided," is related to changes in Flutter's beta version 3.16.0-0.2.pre. It appears to be a configuration issue with the DarwinArchs. To address this problem, you can try the following steps:

1. **Update Your Flutter Version:**
   Ensure you're using the latest version of Flutter by running the following command:

   ```
   flutter upgrade
   ```

2. **Check Your Flutter Project Configuration:**
   Verify that your Flutter project's configuration, especially in your `pubspec.yaml` and `ios/Runner/Info.plist`, is correctly set up for your target platform.

3. **Define DarwinArchs:**
   As the error suggests, you might need to define the `DarwinArchs` for your target platform in your project's configuration. This should typically be set in your `ios/Flutter/AppFrameworkInfo.plist` file. Here's an example of how you can define `DarwinArchs` for a specific platform (e.g., arm64):

   ```xml
   <key>DarwinArchs</key>
   <array>
     <string>arm64</string>
   </array>
   ```

4. **Check Target Platform:**
   Ensure that you have correctly specified the target platform. For macOS, it should be 'darwin'. Double-check your command:

   ```shell
   flutter build bundle -t lib/main.dart --debug --target-platform darwin --asset-dir flutter_assets --verbose
   ```

5. **Reporting the Issue:**
   If the problem persists and you believe it's a bug in the Flutter beta version 3.16.0-0.2.pre, consider reporting the issue on the Flutter GitHub repository. Include details of the error message and steps to reproduce so that the Flutter team can investigate and provide a solution.

Remember that beta versions of Flutter might have issues and are intended for testing, so it's not uncommon to encounter problems. Upgrading to a newer version or reporting the issue to the Flutter team is the best course of action to address this specific problem.

**Comment by fertrig** [comment]
It is still failing. 

I added `DarwinArchs` to ios/Flutter/AppFrameworkInfo.plist and I got the same error.

I also tried running the command with `--dart-define=DarwinArchs=arm64` and it failed with the same error message.

```
flutter build bundle -t lib/main.dart --debug --target-platform darwin --asset-dir flutter_assets --verbose --dart-define=DarwinArchs=arm64
```

**Comment by dcharkes** [comment]
I have definitely touched some of the arg requirements for the backend (`flutter assemble`). I'll take a look.

**Comment by dcharkes** [comment]
I'm unsure about what `flutter bundle` is supposed to do. The documentation is cryptic:

```
$ flutter build --help
[...]
Available subcommands:
[...]
  bundle            Build the Flutter assets directory from your app.


$ flutter build bundle --help
Build the Flutter assets directory from your app.
[...]
```

@stuartmorgan @jonahwilliams could you elaborate?

Should this "bundle" contain the dynamic libraries from the native assets?

It builds one of the two following targets:

```dart
    final Target target = buildInfo.mode == BuildMode.debug
        ? const CopyFlutterBundle()
        : const ReleaseCopyFlutterBundle();
```

Which were added in https://github.com/flutter/flutter/pull/37508.

These targets depend on `KernelSnapshot`, which depends on `NativeAssets`.

I don't see any logic of defining an architecture for the target.

(We don't treat the target consistently, inside `CopyFlutterBundle` the code targets Android?

```dart
    final Depfile assetDepfile = await copyAssets(
      environment,
      environment.outputDir,
      targetPlatform: TargetPlatform.android,
      buildMode: buildMode,
      shaderTarget: ShaderTarget.sksl,
    );
```
)

@jonahwilliams The kernel snapshot (`app.dill`) that we produce, is that intended for users? If yes, that kernel snapshot needs the native assets mapping inside the kernel file to be able to resolve `@Native`s at runtime. And then we should also probably provide the native assets themselves.

If that is the case, we `flutter build bundle` to specify the hardware architectures for every target that is multi-arch (macos/ios) in the `flutter build` CLI.

Though, maybe I've misunderstood completely what `flutter build bundle` is used for, please elaborate.

**Comment by stuartmorgan** [comment]
IIRC `build bundle` is intended for custom embedders, so that they don't have to reinvent all of the Dart and asset compilation, and can instead focus on building just their embedding, and let `build bundle` do the other parts, to create everything needed to run. @jonahwilliams can correct me if I'm wrong :)

That does suggest we'll probably need to add target architecture information and full native asset support (although, maybe for backwards compat we should just skip native assets if that's not provided—with a warning—rather than error?)

@fertrig What's your use case for this command, so that we can make sure whatever we do will support at least that case?

**Comment by jonahwilliams** [comment]
Yeah @stuartmorgan is correct. But in this case I'm not sure if the existing native asset bundling makes sense in this feature or not. Technically the bundle should be (relatively) platform independent, so using the current host platform to configure the native assets may not work.

To start with, I would probably want the native assets feature disabled for build bundle

**Comment by stuartmorgan** [comment]
> using the current host platform to configure the native assets may not work.

Agreed, I was actually envisioning a new flag to `bundle` that would provide the requested architecture(s). That's why I figured we'd need a fallback behavior of disabling it when the flag isn't present.

**Comment by dcharkes** [comment]
Thanks for the clarification!

> To start with, I would probably want the native assets feature disabled for build bundle

The `KernelSnapshot` `Target` depends on the `NativeAssets` `Target`. So we either need to put something in the environment that will make `NativeAssets` a no-op, or subclass the `KernelSnapshot` target so that we have two target for kernel snapshots, one with the native assets lookup information embedded (getting this info means a dependency on the `NativeAssets` target) and one without. I think if we want fallback behavior, we should put that in the environment.

**Comment by fertrig** [comment]
@stuartmorgan 

> What's your use case for this command, so that we can make sure whatever we do will support at least that case?

Our use case is that of a developer tool which runs on macos, windows, and linux. The tool has two windows, each window runs its own flutter process. There is a third headless flutter process as well. 

We use `flutter build bundle` to generate the flutter_assets directory from the flutter code of each module. We then use the path to the flutter_assets directory to create dart project objects on each platform.

```
// on macos
FlutterDartProject.init(precompiledDartBundle: bundle)

// on windows
flutter::DartProject controllerProject(to_wstring(_bundlePath));

// on linux
fl_dart_project_set_assets_path(project, flutter_assets_path);
```

Then we use the `DartProject` to create either a `FlutterEngine` (macos, windows), `FlutterViewController` (macos), `FlutterWindow` (windows), or `FlView` (linux).

**Comment by stuartmorgan** [comment]
So this is essentially a manual add-to-app structure?

In that scenario we could potentially either add native asset support, or have a new command for native assets. Longer term we'd have distinct commands for this for Windows and Linux. (For macOS there's already `framework`; if there's a reason you can't use that please let us know).

**Comment by darshankawar** [comment]
I was able to replicate the reported behavior on latest master. On stable though, the command runs properly and completes successfully as below:

```
[ +476 ms] copy_flutter_bundle: Complete
[ +654 ms] Persisting file store
[   +7 ms] Done persisting file store
[  +25 ms] "flutter bundle" took 43,964ms.
[  +92 ms] ensureAnalyticsSent: 85ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
dhs@Dhss-MacBook-Pro test_project % 

```

<details>
<summary> master flutter doctor -v </summary>

```

[!] Flutter (Channel master, 3.16.0-11.0.pre.68, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.16.0-11.0.pre.68 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9f985ad755 (2 hours ago), 2023-10-15 23:24:25 -0400
    • Engine revision 452e75f2a6
    • Dart version 3.3.0 (build 3.3.0-27.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by dcharkes** [comment]
> I would probably want the native assets feature disabled for build bundle

https://github.com/flutter/flutter/pull/136641

Based on the use case, I believe we might want to default to the host architecture instead of disabling it. Though maybe we should hold off on that until we add proper add-2-app for Linux/Windows?

**Comment by fertrig** [comment]
@stuartmorgan 

1. I'm not familiar with the add-to-app structure. However, from the docs, it looks similar. 

2. I'm not sure what you mean by "native assets".

3. When you say there is `framework` command for macos, do you mean `flutter build macos-framework`? If so, last time I tried the `macos-framework` and `ios-framework` commands I noticed they didn't expose the `track-widget-creation` flag. So, currently there is no way to set `track-widget-creation` to on when using the `*-framework` commands. 
 
The command `flutter build bundle` exposes the `track-widget-creation` flag. For my use case, I need to be able to set that flag.

**Comment by dcharkes** [comment]
> 2\. I'm not sure what you mean by "native assets".

Dart standalone packages that have native code packaged in dynamic libraries. You can read more about it in the tracking bugs: https://github.com/dart-lang/sdk/issues/50565 and https://github.com/flutter/flutter/issues/129757.

If the app inside your developer tool depends on any package with native assets support (currently in experimental), you'll need support for this, otherwise calling the C/C++/Rust code will just fail at runtime.

**Comment by stuartmorgan** [comment]
> If the app inside your developer tool depends on any package with native assets support (currently in experimental), you'll need support for this, otherwise calling the C/C++/Rust code will just fail at runtime.

Although thinking about this a bit more, that's probably already true of any plugin packages in the scenario above, since `build bundle` isn't going to build any plugin code.
