### ISSUE TITLE
SocketException Error: SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64)

### ISSUE THREAD

**Issue by Wang-code-say** [flutter/flutter#136520]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. There is no problem with the request interface, everything is normal 

```dart
Response result =
        await Dio().get( http://47.102.195.137:9306/v1/user-center-app/sys/user/querySysUser, options: Options(headers: {"X-Access-Token": SPUtils.getLoginToken()}), queryParameters: {'vinList': [001]});
    print(result);
    http://47.102.195.137:9306/v1/user-center-app/sys/user/querySysUser,
``` 

2.When I use WiFi connection function

```dart
static Future<bool> connectWifi(wifi, wifiPasswordController) async {

    var result = await WiFiForIoTPlugin.findAndConnect(
      wifi.ssid!,
      password: wifiPasswordController.text,
      bssid: wifi.bssid,
    );
    WiFiForIoTPlugin.isConnected().then((value) => print('connect status$value'));
    WiFiForIoTPlugin.getIP().then((value) => print('current ip$value'));
    return result;
    /*  var ipResult = WiFiForIoTPlugin.getIP();
    if (isValidIPv4Address(ipResult.toString())) {
      return true;
    } else {
      return false;
    }*/
  }
``` 

3. Then this problem occurred when I disconnected from WiFi
 
```dart
  WiFiForIoTPlugin.removeWifiNetwork(widget.arguments!['ssid']);
    WiFiForIoTPlugin.disconnect();
     DioError [DioErrorType.other]: SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64), address = 47.102.195.137, port = 9306，
``` 

 Then my permission information is like this：
 
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.NEARBY_WIFI_DEVICES" />
    <uses-permission android:name="android.permission.MANAGE_DEVICE_POLICY_WIFI" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
``` 

### Expected results

I need to know if the Android version automatically reconnects to the WiFi after the network is disconnected from the WiFi. I have tried not to automatically connect, and even physically disconnected the WiFi on the phone to restore it, but it did not work. Only after restarting the project will return to normal

### Actual results

All current requests have this error. It will only be restored after restarting the project

### Code sample

<details><summary>Code Sample</summary>
<p>

```dart
 static Future<bool> connectWifi(wifi, wifiPasswordController) async {
 
    var result = await WiFiForIoTPlugin.findAndConnect(
      wifi.ssid!,
      password: wifiPasswordController.text,
      bssid: wifi.bssid,
    );
    WiFiForIoTPlugin.isConnected().then((value) => print('connect status $value'));
    WiFiForIoTPlugin.getIP().then((value) => print('current ip$value'));
    return result;
  
  }
   static Future<List<AppControlVehConditionVoList>?> checkVehiclePermissions(List<String> canConnectWifi) async {
    Response result =
        await Dio().get([HttpApi.baseUrl + HttpApi.checkVehiclePermissions](http://47.102.195.137:9306/v1/user-center-app/sys/user/querySysUser), options: Options(headers: {"X-Access-Token": SPUtils.getLoginToken()}), queryParameters: {'vinList': canConnectWifi});
    print(result);
    AppRequestBean bean = AppRequestBean.fromJson(result.data);
    if (bean.code == '000000') {
      CarsInfoModel carsInfoModel = CarsInfoModel.fromJson(bean.result as Map<String, dynamic>);
      if (carsInfoModel.appControlVehConditionVoList!.isNotEmpty) {
        SPUtils.setCarsInfoModel(carsInfoModel);
      }
      return carsInfoModel.appControlVehConditionVoList;
    } else if (bean.code == 'AG1001' || bean.code == 'AG1002' || bean.code == 'AG1003') {
      Global.logout();
    } else {
      ToastUtils.toast('${bean.message}');
      return SPUtils.getCarsInfoModel();
    }
    return SPUtils.getCarsInfoModel();
  }
``` 

</p>
</details> 

### Screenshots or Video

<img width="500" src="https://github.com/flutter/flutter/assets/84007125/5989deae-4651-4396-94cd-edbd0d881014">

### Logs

<details><summary>Details</summary>
<p>

```
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioError [DioErrorType.other]: SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64), address = 47.102.195.137, port = 9306
E/flutter (11830): Source stack:
E/flutter (11830): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
E/flutter (11830): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
E/flutter (11830): #2      DioMixin.get (package:dio/src/dio_mixin.dart:61:12)
E/flutter (11830): #3      RemoteViewModel.checkVehiclePermissions (package:flutter_et_car/view_model/remote_view_model.dart:22:21)
E/flutter (11830): #4      _RemotePageState.wifiConnectContent.<anonymous closure>.<anonymous closure> (package:flutter_et_car/page/remote/remote_page.dart:130:45)
E/flutter (11830): <asynchronous suspension>
E/flutter (11830): #5      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:628:33)
E/flutter (11830): <asynchronous suspension>
E/flutter (11830): 
E/flutter (11830): #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:643:7)
E/flutter (11830): #1      _RootZone.runBinary (dart:async/zone.dart:1665:54)
E/flutter (11830): #2      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (11830): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
E/flutter (11830): #4      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
E/flutter (11830): #5      Future._completeError (dart:async/future_impl.dart:575:5)
E/flutter (11830): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
E/flutter (11830): #7      _Completer.completeError (dart:async/future_impl.dart:23:5)
E/flutter (11830): #8      Future.any.onError (dart:async/future.dart:617:45)
E/flutter (11830): #9      _RootZone.runBinary (dart:async/zone.dart:1665:54)
E/flutter (11830): #10     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (11830): #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
E/flutter (11830): #12     Future._propagateToListeners (dart:async/future_impl.dart:800:13)
E/flutter (11830): #13     Future._completeError (dart:async/future_impl.dart:575:5)
E/flutter (11830): #14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:666:7)
E/flutter (11830): #15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (11830): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (11830): 
``` 

</p>
</details> 

### Flutter Doctor output

<details><summary>flutter doctor -v</summary>
<p>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [version 10.0.22621.2283], locale zh-CN)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] VS Code
[!] Proxy Configuration
    ! NO_PROXY does not contain localhost
    ! NO_PROXY does not contain ::1
    ! NO_PROXY does not contain 127.0.0.1
[√] Connected device (4 available)
[√] HTTP Host Availability

``` 

</p>
</details>

**Comment by dam-ease** [comment]
Hi @Wang-code-say. Thanks for filing this. I see you are on an older version of flutter, can you upgrade to the latest versions of flutter to see if this issue still persists? Also, what other packages are you using asides `Dio`, can you help with a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code (usually a single `main.dart` file)?

**Comment by Wang-code-say** [comment]
I'm not sure if it's a problem with my code. I need time to confirm. If it's solved, I will close this issue as soon as possible. Thank you for your attention.
