### ISSUE TITLE
the description of the `throwsToolExit` matcher is vague

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#136698]
See title. If you run a test that has a failing `throwsToolExit` matcher, you may see output similar to this:

```
Expected: throws (<Instance of 'ToolExit'> and satisfies function)
  Actual: <Instance of 'Future<void>'>
   Which: threw ToolExit:<Exception: Error parsing assemble command: your generated configuration may be out of date. Try re-running 'flutter build ios' or the appropriate build command.>
          stack package:flutter_tools/src/base/common.dart 10:3                     throwToolExit
                package:flutter_tools/src/commands/assemble.dart 294:7              AssembleCommand.runCommand
...
```

While there is no useful information about the mismatch, this is generally still sufficient--there are only two fields `throwsToolExit` can match on.

However, where this can be confusing when writing tests that involve multiple `throwsToolExit` matchers, because it isn't necessarily easy to figure out in which the mismatch occurred, especially if the stack traces are long enough to get truncated. This is a situation that should ideally be rare, but I've encountered a couple of times now.

**Comment by christopherfujino** [comment]
> However, where this can be confusing when writing tests that involve multiple throwsToolExit matchers

I'm just curious, how could the tool throw multiple times in one test?

**Comment by andrewkolos** [comment]
> > However, where this can be confusing when writing tests that involve multiple throwsToolExit matchers
> 
> I'm just curious, how could the tool throw multiple times in one test?

It doesn't need to throw multiple times for there to be confusion. If I have a test that has two or more `throwsToolExit` matchers with message and/or exit code conditions, and the test fails on one of those matchers, it can be difficult to discern which matcher failed if the stack trace is truncated.

**Comment by christopherfujino** [comment]
> > > However, where this can be confusing when writing tests that involve multiple throwsToolExit matchers
> > 
> > 
> > I'm just curious, how could the tool throw multiple times in one test?
> 
> It doesn't need to throw multiple times for there to be confusion. If I have a test that has two or more `throwsToolExit` matchers with message and/or exit code conditions, and the test fails on one of those matchers, it can be difficult to discern which matcher failed if the stack trace is truncated.

so you're matching multiple times, but only expecting it to throw once? or am I missing something?

**Comment by andrewkolos** [comment]
> so you're matching multiple times, but only expecting it to throw once? or am I missing something?

Let me try through a contrived example:

```dart
testUsingContext('foo fails when bad args are provided', () async {
  await expectLater(createTestCommandRunner(command).run(<String>[
    'foo',
    '--bad-arg'
  ]), throwsToolExit(message: "I don't know what --bad-arg is"));
  await expectLater(createTestCommandRunner(command).run(<String>[
    'foo',
    '--even-worse-arg'
  ]), throwsToolExit(message: "I don't know what --even-worse-arg is"));
}, overrides: <Type, Generator>{
  FileSystem: () => fs,
  ProcessManager: () => FakeProcessManager.any(),
});
```

Running this via the VSCode editor UI, you will see this output:

<details>
<summary> output </summary>

```
Expected: throws (<Instance of 'ToolExit'> and satisfies function)
  Actual: <Instance of 'Future<void>'>
   Which: threw UsageException:<Could not find a command named "foo".
                
                Usage: flutter <command> [arguments]
                
                Global options:
                -h, --help                  Print this usage information.
                -v, --verbose               Noisy logging, including all shell commands executed.
                                            If used with "--help", shows hidden options. If used with "flutter doctor", shows additional diagnostic information. (Use "-vv" to force verbose logging in those cases.)
                -d, --device-id             Target device id or name (prefixes allowed).
                    --version               Reports the version of this tool.
                    --enable-analytics      Enable telemetry reporting each time a flutter or dart command runs.
                    --disable-analytics     Disable telemetry reporting each time a flutter or dart command runs, until it is re-enabled.
                    --suppress-analytics    Suppress analytics reporting for the current CLI invocation.
                
                Available commands:
                
                Project
                  run   Run your Flutter app on an attached device.
                
                Run "flutter help <command>" for more information about a command.
                Run "flutter help -v" for verbose help output, including less commonly used options.>
          stack package:args/command_runner.dart 105:7                               CommandRunner.usageException
                package:args/command_runner.dart 178:13                              CommandRunner.runCommand
                package:flutter_tools/src/runner/flutter_command_runner.dart 348:21  FlutterCommandRunner.runCommand.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/runner/flutter_command_runner.dart 294:5   FlutterCommandRunner.runCommand
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                test/commands.shard/hermetic/run_test.dart 698:3                     main.<fn>.<fn>.<fn>
                ===== asynchronous gap ===========================
                test/src/context.dart 140:26                                         testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                test/src/context.dart 101:5                                          testUsingContext.<fn>
                
          which is not an instance of 'ToolExit'
#0      fail (package:matcher/src/expect/expect.dart:149:31)
#1      _expect.<anonymous closure> (package:matcher/src/expect/expect.dart:125:9)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#4      OutstandingWork.complete (package:test_api/hooks.dart:75:3)
<asynchronous suspension>
#5      main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/andrewkolos/Documents/GitHub/flutter/packages/flutter_tools/test/commands.shard/hermetic/run_test.dart:698:3)
<asynchronous suspension>
#6      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/andrewkolos/Documents/GitHub/flutter/packages/flutter_tools/test/src/context.dart:140:26)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     testUsingContext.<anonymous closure> (file:///Users/andrewkolos/Documents/GitHub/flutter/packages/flutter_tools/test/src/context.dart:101:5)
<asynchronous suspension>
#11     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:9)
<asynchronous suspension>
#12     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:213:7)
<asynchronous suspension>
#13     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:258:9)
<asynchronous suspension>
Expected: throws (<Instance of 'ToolExit'> and satisfies function)
  Actual: <Instance of 'Future<void>'>
   Which: threw UsageException:<Could not find a command named "foo".

                Usage: flutter <command> [arguments]

                Global options:
                -h, --help                  Print this usage information.
                -v, --verbose               Noisy logging, including all shell commands executed.
                                            If used with "--help", shows hidden options. If used with "flutter doctor", shows additional diagnostic information. (Use "-vv" to force verbose logging in those cases.)
                -d, --device-id             Target device id or name (prefixes allowed).
                    --version               Reports the version of this tool.
                    --enable-analytics      Enable telemetry reporting each time a flutter or dart command runs.
                    --disable-analytics     Disable telemetry reporting each time a flutter or dart command runs, until it is re-enabled.
                    --suppress-analytics    Suppress analytics reporting for the current CLI invocation.

                Available commands:

                Project
                  run   Run your Flutter app on an attached device.

                Run "flutter help <command>" for more information about a command.
                Run "flutter help -v" for verbose help output, including less commonly used options.>
          stack package:args/command_runner.dart 105:7                               CommandRunner.usageException
                package:args/command_runner.dart 178:13                              CommandRunner.runCommand
                package:flutter_tools/src/runner/flutter_command_runner.dart 348:21  FlutterCommandRunner.runCommand.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/runner/flutter_command_runner.dart 294:5   FlutterCommandRunner.runCommand
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                test/commands.shard/hermetic/run_test.dart 698:3                     main.<fn>.<fn>.<fn>
                ===== asynchronous gap ===========================
                test/src/context.dart 140:26                                         testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                package:flutter_tools/src/base/context.dart 150:19                   AppContext.run.<fn>
                ===== asynchronous gap ===========================
                test/src/context.dart 101:5                                          testUsingContext.<fn>

          which is not an instance of 'ToolExit'
test/commands.shard/hermetic/run_test.dart 698:3    main.<fn>.<fn>.<fn>
===== asynchronous gap ===========================
test/src/context.dart 140:26                        testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
===== asynchronous gap ===========================
package:flutter_tools/src/base/context.dart 150:19  AppContext.run.<fn>
===== asynchronous gap ===========================
package:flutter_tools/src/base/context.dart 150:19  AppContext.run.<fn>
===== asynchronous gap ===========================
package:flutter_tools/src/base/context.dart 150:19  AppContext.run.<fn>
===== asynchronous gap ===========================
test/src/context.dart 101:5                         testUsingContext.<fn>
```
</details>

The description of the matcher (the first line of any matcher failure output) doesn't provide enough information to figure out which of the two `throwsToolExit` calls the test failure originated from.

Oftentimes, the output from `ToolExit:toString` thats included in the mismatch description (the `Which:` line) is enough to form a solid guess[^1]. If the stack trace isn't truncated, you can use that too. However, contributors shouldn't have to look past the first few lines of the test output to figure out which matcher failed.

[^1]: Fun fact, the `ToolExit` we throw when no target devices are found has a `message` of null, so if you forgot to hook up a fake `Device` in your test, you don't even have this output to help you out.

**Comment by christopherfujino** [comment]
> > so you're matching multiple times, but only expecting it to throw once? or am I missing something?
> 
> Let me try through a contrived example:
> 
> ```dart
> testUsingContext('foo fails when bad args are provided', () async {
>   await expectLater(createTestCommandRunner(command).run(<String>[
>     'foo',
>     '--bad-arg'
>   ]), throwsToolExit(message: "I don't know what --bad-arg is"));
>   await expectLater(createTestCommandRunner(command).run(<String>[
>     'foo',
>     '--even-worse-arg'
>   ]), throwsToolExit(message: "I don't know what --even-worse-arg is"));
> }, overrides: <Type, Generator>{
>   FileSystem: () => fs,
>   ProcessManager: () => FakeProcessManager.any(),
> });
> ```
> 
> Notice this test has two `throwsToolExit` matchers that are both expected to pass. Running this via the VSCode editor UI, you will see this output:

So this test essentially has two tool entrypoints, because we're running `command` twice. I feel like, unless this is an integration test that took minutes to set up, it would usually be desirable to split this up into multiple tests. Even in instances when it seems like the two entrypoints are strongly correlated, over time I've seen these tests evolve to be essentially just a suite of tests all concatenated together in a single "test".

**Comment by andrewkolos** [comment]
> So this test essentially has two tool entrypoints, because we're running `command` twice. I feel like, unless this is an integration test that took minutes to set up, it would usually be desirable to split this up into multiple tests.

I completely agree. This is something I meant to hint at in the very end of my initial comment, but forgot to elaborate on. Perhaps the issue title should be relaxed. To re-summarize my thoughts, `throwsToolExit` is sufficient at what it does, but it could be improved. These improvements would be most helpful for newer/visiting contributors who already have enough to figure out when trying to write/modify tools tests.
