### ISSUE TITLE
About null safty in Flutter 3.7.12 Linux Platform

### ISSUE THREAD

**Issue by Li-00** [flutter/flutter#136791]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1、Install and configure Flutter 3.7.12 on Linux
2、run  flutte  build  linux --release  --no-sound-null-safety or  flutter run -d linux  --no-sound-null-safet

### Actual results

1、My commercial project was created during Flutter 1.2, so it does not support empty exceptions in many places, and I currently run my project on Windows using Flutter 3.7.12 with @dart=2.9 annotations.This can satisfy the normal use of all functions
2、When I installed and configured Flutter 3.7.12 on an X86 Linux system, The project can be started, but many functions are unavailable due to null check exceptions
3、Besides changing the overall project code, I would like to know if there is any way to make it run on linux platform, because there is no time to adapt the project code due to some problems, and I have specifically checked the official website. 3.7.12 is the last version that supports no-space check

### Logs

<details>
some log error 

```console
: getCustomXmlIcons failed or xml file not exist
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Failed assertion: boolean expression must not be null
#0      new AuthDirectManager.<anonymous closure>.<anonymous closure> (package:nova_login/manager/direct_auth_manager.dart:50)
<asynchronous suspension>

flutter: getCustomXmlIcons failed or xml file not exist
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Failed assertion: boolean expression must not be null
#0      new AuthDirectManager.<anonymous closure>.<anonymous closure> (package:nova_login/manager/direct_auth_manager.dart:50)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Failed assertion: boolean expression must not be null
#0      new AuthDirectManager.<anonymous closure>.<anonymous closure> (package:nova_login/manager/direct_auth_manager.dart:50)
<asynchronous suspension>

..
flutter: StandardAreaManager.getAreaList.usedLocalDeviceKeys length=0,localDeviceMap length=0
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '+' was called on null.
Receiver: null
Tried calling: +()


```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

 flutter doctor -v
[✓] Flutter (Channel stable, 3.7.12, on Kylin V10 SP1 5.4.18-53-generic, locale zh_CN.UTF-8)
    • Flutter version 3.7.12 on channel stable at /home/it0/flutter/flutter_3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 个月前), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4kylin1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Kylin V10 SP1 5.4.18-53-generic


```

</details>

**Comment by huycozy** [comment]
Hi @Li-00 
For null-safety migration, please check our document https://dart.dev/null-safety/migration-guide as a guideline. Closing as this is not a Flutter bug or feature request.
