### ISSUE TITLE
ExoPlaybackException: MediaCodecVideoRenderer error - NO_EXCEEDS_CAPABILITIES

### ISSUE THREAD

**Issue by kamaravichow** [flutter/flutter#136807]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Network Video Url

### Expected results

Play the video

### Actual results

PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D0033, -1, null, [2072, 2732, 30.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, null, null)

### Code sample

<details><summary>Code sample</summary>

```dart
final videoController = VideoPlayerController.networkUrl(
      Uri.parse(videoItem.illustration),
      videoPlayerOptions: VideoPlayerOptions(
        mixWithOthers: true,
        allowBackgroundPlayback: true,
      ),
    );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console

E/ExoPlayerImplInternal( 7265): Playback error
E/ExoPlayerImplInternal( 7265):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D0033, -1, null, [2072, 2732, 30.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
E/ExoPlayerImplInternal( 7265):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Error initializing video player: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D0033, -1, null, [2072, 2732, 30.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, null, null)


E/ExoPlayerImplInternal( 7265): Playback error
E/ExoPlayerImplInternal( 7265):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D0033, -1, null, [2072, 2732, 30.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
E/ExoPlayerImplInternal( 7265):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
```

</details>

**Comment by dam-ease** [comment]
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/81804. Please follow up on it for further updates. Also, this is more like an ExoPlayer's issue, please see this [filter](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+is%3Aopen+com.google.android.exoplayer2.ExoPlaybackException%3A+MediaCodecVideoRenderer+error) on ExoPlayer repository.
