### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/henrygao/fvm/versions/1.22.6/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.

### ISSUE THREAD

**Issue by HenryGaoGH** [flutter/flutter#136890]
## Command
```
flutter --quiet assemble --depfile /Users/henrygao/Documents/Life/FreeFish/geeme_flutter_app/build/app/intermediates/flutter/productRelease/flutter_build.d --output /Users/henrygao/Documents/Life/FreeFish/geeme_flutter_app/build/app/intermediates/flutter/productRelease -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/henrygao/fvm/versions/1.22.6/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:462:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:356:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:462:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:477:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:496:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:248:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
<asynchronous suspension>
#11     _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:744:35)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:744:21)
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:566:36)
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#18     _rootRunUnary (dart:async/zone.dart:1198:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 14.0 23A344 darwin-arm, locale zh-Hans-CN)
    • Flutter version 1.22.6 at /Users/henrygao/fvm/versions/1.22.6
    • Framework revision 9b2d32b605 (2 years, 9 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/henrygao/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/henrygao/Library/Java/JavaVirtualMachines/corretto-1.8.0_382/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.382.05.1 (build 1.8.0_382-b05)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 15.0, Build version 15A240d
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 14 (API 34) (emulator)
    • iPhone 15 Pro (mobile)      • EE295B3A-4E8C-461B-A7BA-EA8FD22BE39F • ios           • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    ! Error: Henry‘iPhone is not connected. Xcode will continue when Henry‘iPhone is connected and unlocked. (code -13)

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.12+18
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe
### Plugins
connectivity-0.4.9+5
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
file_picker-1.13.3
flutter_plugin_android_lifecycle-1.0.11
package_info-0.4.3+4
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+4
webview_flutter-1.0.7

**Comment by dam-ease** [comment]
Hi @HenryGaoGH 
This is a known issue https://github.com/flutter/flutter/issues/68475 that has been fixed with https://github.com/flutter/flutter/pull/78272.
As far as I can see, you are using the old Flutter version 1.22.6, the latest Flutter stable is 3.13.8 and the master is 3.16.0. Please try upgrading Flutter stable or master channel to the latest and retry to see if this issue still reproduces.
