### ISSUE TITLE
_TypeError: type '_Map<String, Object>' is not a subtype of type 'String?' in type cast

### ISSUE THREAD

**Issue by pawankumar-creator** [flutter/flutter#136957]
## command

flutter build ipa

## exception

_TypeError: type '_Map<String, Object>' is not a subtype of type 'String?' in type cast

```
#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:182:24)
#1      BuildIOSArchiveCommand._validateXcodeBuildSettingsAfterArchive (package:flutter_tools/src/commands/build_ios.dart:381:67)
<asynchronous suspension>
#2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:422:7)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[33m[!][39m Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.13.6 on channel stable at /users/taiyarikarlo/flutter
    [33m![39m Warning: `flutter` on your path resolves to /Users/taiyarikarlo/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at
      /users/taiyarikarlo/flutter. Consider adding /users/taiyarikarlo/flutter/bin to the front of your path.
    [33m![39m Warning: `dart` on your path resolves to /Users/taiyarikarlo/flutter/bin/dart, which is not inside your current Flutter SDK checkout at
      /users/taiyarikarlo/flutter. Consider adding /users/taiyarikarlo/flutter/bin to the front of your path.
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision ead455963c (3 weeks ago), 2023-09-26 18:28:17 -0700
    [32m•[39m Engine revision a794cf2681
    [32m•[39m Dart version 3.1.3
    [32m•[39m DevTools version 2.25.0
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
    [32m•[39m Android SDK at /Users/taiyarikarlo/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0-rc4
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15A240d
    [32m•[39m CocoaPods version 1.13.0

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m android-studio-dir = /Applications/Android Studio.app
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.79.0)
    [32m•[39m VS Code at /Users/taiyarikarlo/Downloads/Visual Studio Code 2.app/Contents
    [32m•[39m Flutter extension version 3.74.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone 15 (mobile) • C46A868B-0559-4480-8CB6-CC93222E118A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    [32m•[39m macOS (desktop)    • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    [32m•[39m Chrome (web)       • chrome                               • web-javascript • Google Chrome 118.0.5993.88

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.
```

**Comment by dam-ease** [comment]
Hi @pawankumar-creator. From the error you are getting, this might be an issue with your code, does this happen when you run you app in debug mode as well?

When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v

Kindly provide these information so this can be properly addressed.

**Comment by pawankumar-creator** [comment]
\
Flutter Doctor output is already included in the details I provided. The error I reported in the GitHub repository occurs when I run `flutter build ipa`. To resolve this, I have tried building the IPA using Xcode's Archive option, but it still throws the same error even when I use `flutter build ipa`. 

Additionally, the logs were auto-generated by Flutter.

**Comment by dam-ease** [comment]
Hi @pawankumar-creator. Thanks for your response and patience. Can you try building ipa again with a newly created flutter project? Also can you upgrade to the latest flutter versions to see if this issue still persists there.
