### ISSUE TITLE
Not able to open local file using launchUrl(Uri.file(absolute path));

### ISSUE THREAD

**Issue by halhwadi** [flutter/flutter#137041]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1- Upload Image using Image Picker from flutter
2- create the absolute path for this image
3-pass the absolute path to launchUrl(Uri.file(absolute path));

### Expected results

Open the image 

### Actual results

Not able to open the image.
**Note** same image on server can be opened by using launchUrl(Uri.parse(Image url));

### Code sample

<details><summary>Code sample</summary>

```dart
[InkWell(
                                            onTap: () {
                                              // Uri.file('http://192.168.63.172:8000/media/chat/' + _messages[index][0],);
                                              // launchUrl(Uri.parse('http://192.168.63.172:8000/media/chat/' +
                                              //     _messages[index][0],));
                                              launchUrl(Uri.file(_imagelocal!.absolute.path));
                                            },
                                            child: Container(
                                              // height: 200.0,
                                              width: MediaQuery
                                                  .of(context)
                                                  .size
                                                  .width * .8,
                                              alignment: Alignment.topRight,
                                              decoration: BoxDecoration(
                                                  border: Border.all(),
                                                  color: Colors.white70
                                              ),
                                              child: Image.file(File(_messages[index][8]),
                                                  fit: BoxFit.fitWidth,
                                                  width: 600),
                                            ),),]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(android.os.FileUriExposedException: file:///data/user/0/org.bikum/cache/scaled_VIDEO0177_0000000440.jpg exposed beyond app through Intent.getData(), FileUriExposedException, Cause: null, Stacktrace: android.os.FileUriExposedException: file:///data/user/0/org.bikum/cache/scaled_VIDEO0177_0000000440.jpg exposed beyond app through Intent.getData()
E/flutter (10999): 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2141)
E/flutter (10999): 	at android.net.Uri.checkFileUriExposed(Uri.java:2391)
E/flutter (10999): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:11848)
E/flutter (10999): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:11797)
E/flutter (10999): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1722)
E/flutter (10999): 	at android.app.Activity.startActivityForResult(Activity.java:5377)
E/flutter (10999): 	at android.app.Activity.startActivityForResult(Activity.java:5335)
E/flutter (10999): 	at android.app.Activity.startActivity(Activity.java:5721)
E/flutter (10999): 	at android.app.Activity.startActivity(Activity.java:5674)
E/flutter (10999): 	at io.flutter.plugins.urllauncher.UrlLauncher.launchUrl(UrlLauncher.java:89)
E/flutter (10999): 	at io.flutter.plugins.urllauncher.Messages$UrlLauncherApi$-CC.lambda$setup$1(Messages.java:240)
E/flutter (10999): 	at io.flutter.plugins.urllauncher.Messages$UrlLauncherApi$$ExternalSyntheticLambda1.onMessage(Unknown Source:2)
E/flutter (10999): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:219)
E/flutter (10999): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (10999): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (10999): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (10999): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (10999): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (10999): 	at android.os.Looper.loop(Looper.java:246)
E/flutter (10999): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/flutter (10999): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10999): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (10999): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (10999): , null)
E/flutter (10999): #0      UrlLauncherApi.launchUrl (package:url_launcher_android/src/messages.g.dart:121:7)
E/flutter (10999): <asynchronous suspension>
E/flutter (10999): #1      UrlLauncherAndroid.launch (package:url_launcher_android/url_launcher_android.dart:74:19)
E/flutter (10999): <asynchronous suspension>]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22621.2283], locale en-AE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2022.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
]
```

</details>

**Comment by stuartmorgan** [comment]
Please see https://developer.android.com/reference/android/os/FileUriExposedException for an explanation of this exception. This is not a behavior of the plugin, but the OS.

Closing as this is expected behavior on Android. Handling of schemes is OS-dependent, as explained in the plugin README.
