### ISSUE TITLE
Flutter fails to build aot snapshot in --preview-dart-2 mode on windows

### ISSUE THREAD

**Issue by aam** [flutter/flutter#13708]
```
C:\src\flutter\flutter\examples\flutter_gallery>..\..\bin\flutter build aot --preview-dart-2 --release -v
[  +25 ms] [C:\src\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +1 ms] [C:\src\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[   +1 ms] [C:\src\flutter\flutter\] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] git@github.com:flutter/flutter.git
[   +1 ms] [C:\src\flutter\flutter\] git log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 81d4834278e0df8c7331d933a65b9f7a4fadadb1
[   +4 ms] [C:\src\flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +43 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +2 ms] 2 hours ago
[ +112 ms] Building AOT snapshot in release mode (android-arm-release)...
[+1008 ms] compile debug message: Unhandled exception:
                   FileSystemException(uri=c:; message=PhysicalFileSystem only supports file:* URIs)
                   #0      PhysicalFileSystem.entityForUri (package:front_end/src/api_prototype/physical_file_system.dart:24)
                   #1      ProcessedOptions.validateOptions (package:front_end/src/base/processed_options.dart:200)
                   <asynchronous suspension>
                   #2      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:45)
                   <asynchronous suspension>
                   #3      kernelForProgram.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:43)
                   <asynchronous suspension>
                   #4      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:96)
                   #5      _rootRun (dart:async/zone.dart:1126)
                   #6      _CustomZone.run (dart:async/zone.dart:1023)
                   #7      runZoned (dart:async/zone.dart:1501)
                   #8      CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:96)
                   #9      CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:107)
                   #10     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:42)
                   <asynchronous suspension>
                   #11     compileToKernel (package:vm/kernel_front_end.dart:26)
                   <asynchronous suspension>
                   #12     _FrontendCompiler.compile.<anonymous closure> (package:frontend_server/server.dart:173)
                   #13     new Future.<anonymous closure> (dart:async/future.dart:174)
                   #14     _rootRun (dart:async/zone.dart:1122)
                   #15     _CustomZone.run (dart:async/zone.dart:1023)
                   #16     _CustomZone.runGuarded (dart:async/zone.dart:925)
                   #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
                   #18     _rootRun (dart:async/zone.dart:1126)
                   #19     _CustomZone.run (dart:async/zone.dart:1023)
                   #20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
                   #21     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
                   #22     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:367)
                   #23     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:401)
                   #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

This is at `81d4834278e0df8c7331d933a65b9f7a4fadadb1`.

cc @alexmarkov

**Comment by aam** [comment]
This is not specific to aot, build flx fails as well:
```
C:\src\flutter\flutter\examples\flutter_gallery>..\..\bin\flutter build flx --preview-dart-2  -v
[  +24 ms] [C:\src\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +77 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[   +3 ms] [C:\src\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[   +7 ms] [C:\src\flutter\flutter\] git log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 5d40ef35c15b2b5fe5915372c468e241941d7b95
[   +3 ms] [C:\src\flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +36 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +2 ms] 3 weeks ago
[+1119 ms] compile debug message: Unhandled exception:
                   FileSystemException(uri=c:.packages; message=PhysicalFileSystem only supports file:* URIs)
                   #0      PhysicalFileSystem.entityForUri (package:front_end/physical_file_system.dart:24)
                   #1      ProcessedOptions._findPackages.checkInDir (package:front_end/src/base/processed_options.dart:430)
                   <asynchronous suspension>
                   #2      ProcessedOptions._findPackages (package:front_end/src/base/processed_options.dart:435)
                   <asynchronous suspension>
                   #3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:378)
                   <asynchronous suspension>
                   #4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:311)
                   <asynchronous suspension>
                   #5      IncrementalKernelGenerator.newInstance.<anonymous closure> (package:front_end/incremental_kernel_generator.dart:144)
                   <asynchronous suspension>
                   #6      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89)
                   #7      _rootRun (dart:async/zone.dart:1126)
                   #8      _CustomZone.run (dart:async/zone.dart:1023)
                   #9      runZoned (dart:async/zone.dart:1501)
                   #10     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89)
                   #11     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96)
                   #12     IncrementalKernelGenerator.newInstance (package:front_end/incremental_kernel_generator.dart:143)
                   <asynchronous suspension>
                   #13     _FrontendCompiler.compile (package:frontend_server/server.dart:160)
                   <asynchronous suspension>
                   #14     starter (package:frontend_server/server.dart:269)
                   <asynchronous suspension>
                   #15     main (file:///E:/b/build/slave/Windows_Engine/build/src/flutter/frontend_server/bin/starter.dart:6)
                   #16     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
                   #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by alexmarkov** [comment]
@aam, is it possible to reproduce the problem with Fasta command-line tool outside of Flutter?

**Comment by aam** [comment]
@alexmarkov no, it is not because the issue is not with Fasta :-) It's with path handling in flutter frontend server.

**Comment by aam** [comment]
I am reverting 1fb5858 because with frontend_server producing correct kernel file, then `gen_snapshot` fails when generating aot snapshot from that kernel, @sivachandra .

The reason `gen_snapshot` fails is because it expects to resolve dependency file added here https://github.com/dart-lang/sdk/blob/master/runtime/bin/gen_snapshot.cc#L1429 , but dependency file resolution invoked from https://github.com/dart-lang/sdk/blob/master/runtime/bin/gen_snapshot.cc#L576 has no chance of succeeding because when generating from kernel service isolate port is not configured. So message to service isolate is never sent(because port is not configured), reply is never processed, `file_path` remains `NULL` and it starts doing weird things with null pointer here https://github.com/dart-lang/sdk/blob/master/runtime/bin/loader.cc#L316.
