### ISSUE TITLE
[web]: Unicode char throws `Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER)` error

### ISSUE THREAD

**Issue by d-polikhranidi** [flutter/flutter#137025]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have searched that there were similar issues but they are closed without any fix. I suppose that error in Flutter debug console in Android Studio or something related with this. I suppose so because there's no any issues with rendering such special characters but only if there appears in console (you can see this in attached video)

Second, I think the problem is wrong conversion from special char (in my case **�**) to bytes (`[239, 191, 189, 10]` but it must be `[239, 191, 189]`).

There's no any problems in release mode or if I go to `localhost` from other browser instance which is not connected to Flutter debugger. But using other instance of browser is not a solution because it makes development very difficult in such circumstances))

To reproduce just start my example code

### Expected results

Flutter debugger shows **�** in console

### Actual results

App crashes

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {

    const String crashString = "�";

    return MaterialApp(
      title: 'App crasher',
      home: Center(
        child: TextButton(onPressed: () => print(crashString), child: const Text("Crash app")),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/76728763/cd66f344-1dc1-4785-b40a-f14f9cee0206

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:54270/2-5SauS8BYM=/ws
Debug service listening on ws://127.0.0.1:54270/2-5SauS8BYM=/ws
Debug service listening on ws://127.0.0.1:54270/2-5SauS8BYM=/ws
Finished with error: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: �
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[239, 191, 189, 10]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale ru-BY)
    • Flutter version 3.13.8 on channel stable at /Users/admin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (3 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/admin/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/admin/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008030-00125C940292802E • ios            • iOS 17.0.3 21A360
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 118.0.5993.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by d-polikhranidi** [comment]
Aha, I found from where this error rises: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/convert.dart#L60

I believe that � not indicates malformed input.

**Comment by LucyJeong** [comment]
@d-polikhranidi How to fix it? just remove � char??

**Comment by d-polikhranidi** [comment]
> @d-polikhranidi How to fix it? just remove � char?? or handling � char??

if you experiencing problems only in `print` function (output inside your console) just use `log` instead of `print`

**Comment by darshankawar** [comment]
Thanks for the report. I see that the reported error occurs only on web, as it works as expected on mobile and desktop. 

1. On web:

```
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: �
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[239, 191, 189, 10]

```

2. On mobile and desktop:

```
2023-10-23 13:15:58.992136+0530 Runner[10743:121715] flutter: �
2023-10-23 13:16:02.315964+0530 Runner[10743:121715] flutter: �
2023-10-23 13:16:03.340706+0530 Runner[10743:121715] flutter: �
2023-10-23 13:16:04.818441+0530 Runner[10743:121715] flutter: �

```

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.13.8, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.8 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (5 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.16.0-15.0.pre.1, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.16.0-15.0.pre.1 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eefafdacdb (3 days ago), 2023-10-20 00:06:34 -0400
    • Engine revision 9dd59f7fcf
    • Dart version 3.3.0 (build 3.3.0-45.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by andrewkolos** [comment]
Here's a stack trace:

<details>

<summary>stack trace</summary>

```
[   +1 ms] Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: �
           . The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
           https://github.com/flutter/flutter/issues/new/choose
           The source bytes were:
           [239, 191, 189, 10]
           
           
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      Utf8Decoder.convert (package:flutter_tools/src/convert.dart:61:7)
           #2      Codec.decode (dart:convert/codec.dart:30:34)
           #3      processVmServiceMessage (package:flutter_tools/src/vmservice.dart:1112:31)
           #4      ResidentWebRunner.attach.onLogEvent (package:flutter_tools/src/isolated/resident_web_runner.dart:572:32)
           #5      _rootRunUnary (dart:async/zone.dart:1407:47)
           #6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
           #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
           #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #9      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
           #10     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
           #11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
           #12     _rootRun (dart:async/zone.dart:1391:47)
           #13     _CustomZone.run (dart:async/zone.dart:1301:19)
           #14     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
           #16     _rootRun (dart:async/zone.dart:1399:13)
           #17     _CustomZone.run (dart:async/zone.dart:1301:19)
           #18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
           #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

</details>

From this, we can see that the log message comes from a VM service instance to the Flutter tool code in the form of a UTF-8 encoded byte array. The code to check for U+FFFD and throw a `ToolExit` was introduced by https://github.com/flutter/flutter/pull/26650 (which was intended to help troubleshoot issues such as https://github.com/flutter/flutter/issues/15646).

Strings containing UTF noncharacters are valid[^1]. Therefore, they should arguably be allowed in `print` calls. Still, I doubt fixing this issue would be quick and simple. @d-polikhranidi, if you are able to share, why do you wish to be able to log U+FFFD? Is your app explicitly choosing to print U+FFFD (such as in the code sample), or are you logging malformed Unicode strings coming from somewhere else (such as the user or a server)? This would help me better understand the impact of this issue and better prioritize it.

[^1]: Noncharacters are not _intended_ for interchange, but interchange of them is technically valid. See  https://www.unicode.org/faq/private_use.html.

**Comment by d-polikhranidi** [comment]
> Here's a stack trace:
> 
> stack trace
> From this, we can see that the log message comes from a VM service instance to the Flutter tool code in the form of a UTF-8 encoded byte array. The code to check for U+FFFD and throw a `ToolExit` was introduced by #26650 (which was intended to help troubleshoot issues such as #15646).
> 
> Strings containing UTF noncharacters are valid[1](#user-content-fn-1-fad7fe079b58318891b1474494ae0d92). Therefore, they should arguably be allowed in `print` calls. Still, I doubt fixing this issue would be quick and simple. @d-polikhranidi, if you are able to share, why do you wish to be able to log U+FFFD? Is your app explicitly choosing to print U+FFFD (such as in the code sample), or are you logging malformed Unicode strings coming from somewhere else (such as the user or a server)? This would help me better understand the impact of this issue and better prioritize it.
> 
> ## Footnotes
> 1. Noncharacters are not _intended_ for interchange, but interchange of them is technically valid. See  https://www.unicode.org/faq/private_use.html. [↩](#user-content-fnref-1-fad7fe079b58318891b1474494ae0d92)

Hello @andrewkolos

I'm logging everything that comes from server and sometimes there are strings with �. For now I fixed it with using `log` instead of `print`

**Comment by andrewkolos** [comment]
> I'm logging everything that comes from server and sometimes there are strings with �.

This makes sense. Thanks for letting me know. 

> For now I fixed it with using `log` instead of `print`

This should work for development. Keep in mind that `log` might not work in production builds. From https://api.flutter.dev/flutter/dart-developer/dart-developer-library.html:

> The functionality provided by this library is generally only available to Dart code run in development mode, e.g., dart run, and not in production mode, e.g., the output of dart compile exe.

**Comment by andrewkolos** [comment]
Unfortunately, I currently don't have the bandwidth to investigate the full code path and devise and implement a solution, so I will be unassigning myself—at least for now.

**Comment by d-polikhranidi** [comment]
> > I'm logging everything that comes from server and sometimes there are strings with �.
> 
> This makes sense. Thanks for letting me know.
> 
> > For now I fixed it with using `log` instead of `print`
> 
> This should work for development. Keep in mind that `log` might not work in production builds. From https://api.flutter.dev/flutter/dart-developer/dart-developer-library.html:
> 
> > The functionality provided by this library is generally only available to Dart code run in development mode, e.g., dart run, and not in production mode, e.g., the output of dart compile exe.

Yep, I'm understand that `log` doesn't work in production mode :)

**Comment by ditman** [comment]
The exception comes from here:

* https://github.com/flutter/flutter/blob/92ea5e0ab3b8a7cebb37e0667a8889da9e770d0e/packages/flutter_tools/lib/src/convert.dart#L56-L69

It seems the flutter tool has its own Utf8 codec that may be configured to log this error or not, right before throwing (I wonder if it can be configured to remove these weird characters, or replace them by a tofu box □ instead, so the app can continue)

**Comment by nvbien2000** [comment]
Should this issue be resolved soon?

**Comment by grobarko** [comment]
Facing this issue as well. Any resolution plans?

**Comment by andrewkolos** [comment]
Per https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#when-will-my-bug-be-fixed, please don't ask for updates. Such comments ultimately slow down work on the project. Instead, consider adding a +1 reaction on the top level comment.

Any updates will be posted as they are available, or the issue will have an assignee if it's being worked on. As always, anyone is welcome to submit their own pull request to resolve the issue.

**Comment by x544D** [comment]
any news about this ?
