### ISSUE TITLE
Mac-3 has been failing tasks consistently for days

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#137101]
Builds failed on `Dismiss dialogs` step: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20integration_test_test_ios/13356/overview

<img width="755" alt="Screenshot 2023-10-23 at 2 52 58 PM" src="https://github.com/flutter/flutter/assets/54558023/80cc28c4-9e39-4345-8c70-304dd138269d">

<img width="1489" alt="Screenshot 2023-10-23 at 2 52 23 PM" src="https://github.com/flutter/flutter/assets/54558023/62fba245-9eb4-4fcb-b711-32ce4e87dbb9">

**Comment by keyonghan** [comment]
@kentnguyen99 could you help take a look at this bot? Most likely there is some unexpected dialog on the phone. Please help capture and paste what you found here.

**Comment by kentnguyen99** [comment]
I power recycle the phone and rebooting machine, it's running fine now. Will check machine again tomorrow.
<img width="1494" alt="Screenshot 2023-10-23 at 4 16 21 PM" src="https://github.com/flutter/flutter/assets/120754754/713bd1a9-efee-4cda-b86a-718ab007f587">

**Comment by kentnguyen99** [comment]
@keyonghan Machine mac-3 is running normal now.  Can I close this service ticket?
<img width="1315" alt="Screenshot 2023-10-24 at 9 56 57 AM" src="https://github.com/flutter/flutter/assets/120754754/96733b4e-a991-498b-89f2-a18c7ec31e39">

**Comment by keyonghan** [comment]
When you powered cycle the phone, did you see any dialog on the screen? To your question, yeah, we can close the bug.

**Comment by kentnguyen99** [comment]
Nope, nothing displayed on the phone device.

**Comment by keyonghan** [comment]
Could you help create a bug to track why device doctor didn't power cycle the phone when tasks consistently failed? I would expect the device doctor's post task recovery would recover the phone considering power cycle is the only thing you did to bring the phone back.

**Comment by keyonghan** [comment]
Or you can check the `swarming_bot.log` of the bot to see if any info about phone recovery.

**Comment by kentnguyen99** [comment]
Yes, I can create a bug track ticket; However, I don't have permission to create a ticket in bug track ticket system.

**Comment by kentnguyen99** [comment]
Below the swarming_bot.log file shows.

2023-10-23 16:55:01.302 E: after-task call to device doctor recovery failed: Command '['/opt/flutter/device_doctor/device_doctor', '--action', 'recovery', '--device-os', 'ios']' timed out after 150 seconds
Traceback (most recent call last):
  File "injected.py", line 158, in on_after_task
  File "/opt/s/swarming_bot.1.zip/utils/subprocess42.py", line 607, in communicate
    return super(Popen, self).communicate(
  File "/opt/swarming-support/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/opt/swarming-support/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/opt/swarming-support/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/opt/flutter/device_doctor/device_doctor', '--action', 'recovery', '--device-os', 'ios']' timed out after 150 seconds


2023-10-23 22:42:42.952 D: Dimensions {'cipd_platform': ['mac-amd64'], 'cores': ['12'], 'cpu': ['x86', 'x86-64', 'x86-64-i7-8700B'], 'gpu': ['8086', '8086:3e9b'], 'id': ['flutter-devicelab-mac-3'], 'os': ['Mac', 'Mac-12', 'Mac-12.6', 'Mac-12.6-21G115'], 'pool': ['default'], 'python': ['3', '3.8', '3.8.10+chromium.17'], 'caches': ['vpython'], 'hidpi': ['0'], 'machine_type': ['n1-standard-8'], 'gce': ['0'], 'ssd': ['1'], 'inside_docker': ['0'], 'mac_model': ['Macmini8,1'], 'display_attached': ['1'], 'server_version': ['7419-34ac013']}
107 2023-10-23 22:42:42.953 D: State {'audio': ['Mac mini Speakers'], 'cpu_name': 'Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz', 'cost_usd_hour': 1.2907762586805556, 'cwd': '/opt/s', 'disks': {'/': {'free_mb': 629550.7, 'size_mb': 953904.1}, '/System/Volumes/VM': {'free_mb': 629550.7, 'size_mb': 953904.1}, '/System/Volumes/Preboot': {'free_mb': 629550.7, 'size_mb': 953904.1}, '/System/Volumes/Update': {'free_mb': 629550.7, 'size_mb': 953904.1}, '/System/Volumes/Data': {'free_mb': 629550.7, 'size_mb': 953904.1}}, 'env': {'PATH': '/opt/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin'}, 'gpu': ['Intel UHD Graphics 630'], 'hostname': 'flutter-devicelab-mac-3.mtv.corp.google.com', 'ip': '100.91.177.19', 'nb_files_in_temp': 53, 'pid': 107, 'python': {'executable': '/opt/swarming-support/bin/python3', 'packages': None, 'version': '3.8.10+chromium.17 (default, May  5 2021, 18:52:52) \n[Clang 12.0.0 (clang-1200.0.32.2)]'}, 'ram': 32768, 'running_time': 7, 'ssd': ['disk0'], 'started_ts': 1698100956, 'uptime': 14, 'user': 'swarming', 'named_caches': {'vpython': [['V9', 454288703], 1698100922]}, 'xcode': {}, 'temp': {'cpu': 40.06}, 'cpu': ['x86', 'x86-64', 'x86-64-i7-8700B'], 'os': ['Mac', 'Mac-12', 'Mac-12.6', 'Mac-12.6-21G115'], 'quarantined': 'Device healthcheck failed: attached_device: No device is available;', 'original_bot_id': 'flutter-devicelab-mac-3', 'sleep_streak': 0}

**Comment by keyonghan** [comment]
I am not sure if any action item here. But just for reference, all infra failures started consistently since a test timeout:
https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_ios%20draw_points_perf_ios__timeline_summary/475/overview
<img width="1486" alt="Screenshot 2023-10-24 at 8 37 46 PM" src="https://github.com/flutter/flutter/assets/54558023/28868e50-4911-4a0a-9d0c-affd1e28bc8a">

**Comment by kentnguyen99** [comment]
I didn't find anything in the swarming_bot.log that indicating all tasks failing consistently. However, mac-3 is running normal now so I close this service ticket.

<img width="1380" alt="Screenshot 2023-10-25 at 10 04 00 AM" src="https://github.com/flutter/flutter/assets/120754754/60ceadd5-f718-4cd4-9349-11447659caa2">
