### ISSUE TITLE
Hero issue when Navigating

### ISSUE THREAD

**Issue by xswen** [flutter/flutter#137124]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Press the "save and add new station button"

### Expected results

Navigate to the same page while discarding the previous details of the page. This happens on another page that also uses context.goNamed(), but navigates from Page A -> Page B instead of this example where it's PageA -> PageA.  Pasted example is the smallest code base we have that triggers this error log.

### Actual results

It does navigate properly but the error log appears.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class SurfaceSubstrateStationInfoPage extends StatefulWidget {
  static const String routeName = "surfaceSubstrateStationInfo";
  final GoRouterState state;

  const SurfaceSubstrateStationInfoPage(this.state, {super.key});

  @override
  State<SurfaceSubstrateStationInfoPage> createState() =>
      _SurfaceSubstrateStationInfoPageState();
}

class _SurfaceSubstrateStationInfoPageState
    extends State<SurfaceSubstrateStationInfoPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.state.pathParameters["ssStationNum"]!),
      ),
      body: Center(
        child: ElevatedButton(
            onPressed: () async {
              Map<String, String> pathParms = widget.state.pathParameters;
              pathParms["ssStationNum"] = "${pathParms["ssStationNum"]}1";

              context.goNamed(
                SurfaceSubstrateStationInfoPage.routeName,
                pathParameters: pathParms,
              );
            },
            child: const Text("Save and Add New Station")),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[GoRouter] getting location for name: "surfaceSubstrateStationInfo", pathParameters: {surveyId: 2, ssSummaryId: 1, ssHeaderId: 1, ssStationNum: 11}
[GoRouter] going to /dashboard/survey-info/2/surface-substrate/1/header/1/station_info/11
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 644 pos 12: '() {
      final Animation<double> initial = initialManifest.animation;
      final HeroFlightDirection type = initialManifest.type;
      switch (type) {
        case HeroFlightDirection.pop:
          return initial.value == 1.0 && initialManifest.isUserGestureTransition
              // During user gesture transitions, the animation controller isn't
              // driving the reverse transition, but should still be in a previously
              // completed stage with the initial value at 1.0.
              ? initial.status == AnimationStatus.completed
              : initial.status == AnimationStatus.reverse;
        case HeroFlightDirection.push:
          return initial.value == 0.0 && initial.status == AnimationStatus.forward;
      }
    }()': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      _HeroFlight.start (package:flutter/src/widgets/heroes.dart:644:12)
#3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:969:60)
#4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:891:9)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1236:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#8      _invoke (dart:ui/hooks.dart:170:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#10     _drawFrame (dart:ui/hooks.dart:140:31)
(elided 2 frames from class _AssertionError)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
survey_app$ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-CA)
    • Flutter version 3.13.8 on channel stable at /Users/n/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (6 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /Users/n/Library/Android/sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPad Pro (12.9-inch) (6th generation) (mobile) • FE72FEEA-9581-4480-A717-B58E7E68942E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0
      (simulator)
    • macOS (desktop)                                • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 118.0.5993.88
    ! Error: Browsing on the local area network for Nope's iPad (2). Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @xswen 
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thank you!

**Comment by xswen** [comment]
This is the minimum complexity sample I could reproduce. The app is warped by ProviderScope from Riverpod and uses GoRouter for navigation. Issue only appears when using context.goNamed. Does not appear with .pushNamed.

**Comment by huycozy** [comment]
The updated example is a single page only. Please provide a runnable and complete example so that we can copy-paste and verify the issue. Thanks!
