### ISSUE TITLE
Flutter tools should report failures when frontend server (used in preview-dart-2) stumbles on exception

### ISSUE THREAD

**Issue by aam** [flutter/flutter#13712]
When frontend-server used for `preview-dart-2` fails, `flutter build` still reports successful completion:

```
C:\src\flutter\flutter\examples\flutter_gallery>..\..\bin\flutter build flx --preview-dart-2  -v
[  +24 ms] [C:\src\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +77 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[   +3 ms] [C:\src\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[   +7 ms] [C:\src\flutter\flutter\] git log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 5d40ef35c15b2b5fe5915372c468e241941d7b95
[   +3 ms] [C:\src\flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +36 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +2 ms] 3 weeks ago
[+1119 ms] compile debug message: Unhandled exception:
                   FileSystemException(uri=c:.packages; message=PhysicalFileSystem only supports file:* URIs)
                   #0      PhysicalFileSystem.entityForUri (package:front_end/physical_file_system.dart:24)
                   #1      ProcessedOptions._findPackages.checkInDir (package:front_end/src/base/processed_options.dart:430)
                   <asynchronous suspension>
                   #2      ProcessedOptions._findPackages (package:front_end/src/base/processed_options.dart:435)
                   <asynchronous suspension>
                   #3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:378)
                   <asynchronous suspension>
                   #4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:311)
                   <asynchronous suspension>
                   #5      IncrementalKernelGenerator.newInstance.<anonymous closure> (package:front_end/incremental_kernel_generator.dart:144)
                   <asynchronous suspension>
                   #6      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89)
                   #7      _rootRun (dart:async/zone.dart:1126)
                   #8      _CustomZone.run (dart:async/zone.dart:1023)
                   #9      runZoned (dart:async/zone.dart:1501)
                   #10     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89)
                   #11     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96)
                   #12     IncrementalKernelGenerator.newInstance (package:front_end/incremental_kernel_generator.dart:143)
                   <asynchronous suspension>
                   #13     _FrontendCompiler.compile (package:frontend_server/server.dart:160)
                   <asynchronous suspension>
                   #14     starter (package:frontend_server/server.dart:269)
                   <asynchronous suspension>
                   #15     main (file:///E:/b/build/slave/Windows_Engine/build/src/flutter/frontend_server/bin/starter.dart:6)
                   #16     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
                   #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

C:\src\flutter\flutter\examples\flutter_gallery>echo %errorlevel%
0
```

**Comment by mit-mit** [comment]
@aam are you the right assignee of this?

**Comment by aam** [comment]
Sure this can be assigned to me, @mit-mit

**Comment by aam** [comment]
#13982 had to be reverted, new https://github.com/flutter/flutter/pull/14040 with the reland.

**Comment by aam** [comment]
#14040 landed, closing.
