### ISSUE TITLE
Inspector crash

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13724]
## What happened

Create new app, enable inspector, select top node in widget tree, and then move selection down in the tree with arrow down about 20 times

## Version information

```
Android Studio `3.0.1` • Flutter plugin `io.flutter 20.0.1` • Dart plugin `171.4424`

Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 7766b2a196 (4 hours ago) • 2017-12-20 15:13:34 +0100
Engine • revision 718bda0c9c
Tools • Dart 1.25.0-dev.11.0
```

## Exception
```
Error evaluating expression:
Unhandled exception:
Build scheduled during frame.
While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree. This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.
#0      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:506:9)
#1      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:525:6)
#2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2077:23)
#3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3416:11)
#4      State.setState (package:flutter/src/widgets/framework.dart:1101:14)
#5      _WidgetInspectorState.initState.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:474:7)
#6      WidgetInspectorService.setSelection (package:flutter/src/widgets/widget_inspector.dart:284:33)
#7      WidgetInspectorService.setSelectionById (package:flutter/src/widgets/widget_inspector.dart:260:12)
#8      Eval (evaluate:source:1:39)
#9      Eval (evaluate:source:1:4)
#10     new ImageConfiguration (package:flutter/src/painting/image_provider.dart:40:5)
#11     ImageConfiguration.copyWith (package:flutter/src/painting/image_provider.dart:54:16)
#12     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1576:66)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#15     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#16     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2039:18)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#19     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#20     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2039:18)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#26     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#27     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:2452:16)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#30     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#33     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2183:15)
#34     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:580:5)
#35     RenderStack.paint (package:flutter/src/rendering/stack.dart:588:7)
#36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#38     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#41     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#44     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#47     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#48     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#50     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#53     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#56     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2183:15)
#57     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:580:5)
#58     RenderStack.paint (package:flutter/src/rendering/stack.dart:588:7)
#59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#60     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#61     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
#62     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:559:16)
#63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#64     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136:13)
#65     RenderView.paint (package:flutter/src/rendering/view.dart:173:15)
#66     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999:7)
#67     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:116:11)
#68     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:784:29)
#69     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:272:19)
#70     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:612:22)
#71     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#72     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:921:15)
#73     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:861:9)
#74     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:773:5)
#75     _invoke (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:120)
#76     _drawFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:109)
```

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
   at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
   at io.flutter.inspector.EvalOnDartLibrary$1.received(EvalOnDartLibrary.java:98)
   at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:410)
   at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:432)
   at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:99)
   at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by mit-mit** [comment]
cc @jacob314

**Comment by jacob314** [comment]
This has been fixed for a couple months.
