### ISSUE TITLE
Exception thrown whilst pressing keyboard keys at startup

### ISSUE THREAD

**Issue by dannyglover** [flutter/flutter#137261]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1) Open the counter example in Visual studio code
2) Press F5 to run.
3) Whilst the app is building, hold `ctrl` + `shift` and keep tapping the `A` key.

### Expected results

An exception should not be thrown.

### Actual results

An exception is thrown several times along with a host of warnings.

### Code sample

<details><summary>Code sample</summary>

```dart
Use the counter example app.
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on Linux in debug mode...

(myapp:62126): Gdk-CRITICAL **: 17:24:24.008: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

** (myapp:62126): WARNING **: 17:24:24.558: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:24.577: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:24.838: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:24.980: Unable to retrieve framework response: Message is not valid JSON
Connecting to VM Service at ws://127.0.0.1:46687/1SCKtRFwxlk=/ws

** (myapp:62126): WARNING **: 17:24:25.205: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:25.371: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:25.614: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:25.783: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:26.057: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:26.368: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:26.527: Unable to retrieve framework response: Message is not valid JSON
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs
in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure
that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the
event: KeyUpEvent#25b1e(physicalKey: PhysicalKeyboardKey#7b545(usbHidUsage: "0x00070004", debugName:
"Key A"), logicalKey: LogicalKeyboardKey#12bb1(keyId: "0x00000061", keyLabel: "A", debugName: "Key
A"), character: null, timeStamp: 4:15:05.572000)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 482 pos 13: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:482:13)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:494:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:616:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1041:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#8      _invoke2 (dart:ui/hooks.dart:202:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:228:31)
(elided 4 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#25b1e(physicalKey: PhysicalKeyboardKey#7b545(usbHidUsage: "0x00070004", debugName: "Key A"), logicalKey: LogicalKeyboardKey#12bb1(keyId: "0x00000061", keyLabel: "A", debugName: "Key A"), character: null, timeStamp: 4:15:05.572000)


** (myapp:62126): WARNING **: 17:24:26.577: Unable to retrieve framework response: Message is not valid JSON
Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#25b1e(physicalKey: PhysicalKeyboardKey#7b545(usbHidUsage: "0x00070004", debugName: "Key A"), logicalKey: LogicalKeyboardKey#12bb1(keyId: "0x00000061", keyLabel: "A", debugName: "Key A"), character: null, timeStamp: 4:15:05.572000)


** (myapp:62126): WARNING **: 17:24:26.812: Unable to retrieve framework response: Message is not valid JSON
Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#25b1e(physicalKey: PhysicalKeyboardKey#7b545(usbHidUsage: "0x00070004", debugName: "Key A"), logicalKey: LogicalKeyboardKey#12bb1(keyId: "0x00000061", keyLabel: "A", debugName: "Key A"), character: null, timeStamp: 4:15:05.572000)


** (myapp:62126): WARNING **: 17:24:28.618: Unable to retrieve framework response: Message is not valid JSON

** (myapp:62126): WARNING **: 17:24:28.658: Unable to retrieve framework response: Message is not valid JSON
Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#25b1e(physicalKey: PhysicalKeyboardKey#7b545(usbHidUsage: "0x00070004", debugName: "Key A"), logicalKey: LogicalKeyboardKey#12bb1(keyId: "0x00000061", keyLabel: "A", debugName: "Key A"), character: null, timeStamp: 4:15:05.572000)


** (myapp:62126): WARNING **: 17:24:28.740: Unable to retrieve framework response: Message is not valid JSON
Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#25b1e(physicalKey: PhysicalKeyboardKey#7b545(usbHidUsage: "0x00070004", debugName: "Key A"), logicalKey: LogicalKeyboardKey#12bb1(keyId: "0x00000061", keyLabel: "A", debugName: "Key A"), character: null, timeStamp: 4:15:05.572000)


** (myapp:62126): WARNING **: 17:24:28.758: Unable to retrieve framework response: Message is not valid JSON
Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#25b1e(physicalKey: PhysicalKeyboardKey#7b545(usbHidUsage: "0x00070004", debugName: "Key A"), logicalKey: LogicalKeyboardKey#12bb1(keyId: "0x00000061", keyLabel: "A", debugName: "Key A"), character: null, timeStamp: 4:15:05.572000)

Application finished.

Exited.

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on Fedora Linux 38 (Workstation Edition) 6.5.6-200.fc38.x86_64,
    locale en_GB.UTF-8)
    • Flutter version 3.13.6 on channel stable at /home/danny/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (4 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/danny/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at:
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio/jbr/bi
      n/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[!] Android Studio (version unknown)
    • Android Studio at
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • android-studio-dir =
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 38 (Workstation Edition)
      6.5.6-200.fc38.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Thanks for your report. This is a known issue being tracked at https://github.com/flutter/flutter/issues/125975. Closing this issue as a duplicate, so please follow up on it for further updates.
