### ISSUE TITLE
NoMatchingConfigurationSelectionException: Unable to find a matching configuration of project :shared_preferences:

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#13726]
I'm on Gradle 4.1 and Android plugin 3.0.1
My pubspeck.yaml:
```
dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.2.0
  image_carousel: ^0.2.0
  cached_network_image: ^0.0.2

  firebase_storage: ^0.1.0
  firebase_database: ^0.1.4
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
```

Gradle stacktrace:
```
Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: Unable to find a matching configuration of project :shared_preferences:
  - Configuration 'debugApiElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
  - Configuration 'debugRuntimeElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' and found incompatible value 'java-runtime'.
  - Configuration 'releaseApiElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
  - Configuration 'releaseRuntimeElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' and found incompatible value 'java-runtime'.
        at org.gradle.internal.component.model.LocalComponentDependencyMetadata.selectConfigurations(LocalComponentDependencyMetadata.java:122)
        at org.gradle.internal.component.local.model.DslOriginDependencyMetadataWrapper.selectConfigurations(DslOriginDependencyMetadataWrapper.java:65)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.calculateTargetConfigurations(DependencyGraphBuilder.java:454)
        ... 98 more

```

**Comment by kelvinwatson** [comment]
Same issue here. Where you able to find a solution?

**Comment by long1eu** [comment]
No, it just worked next day

**Comment by UlfS** [comment]
The workaround mentioned in another issue worked for me: https://github.com/flutter/flutter/issues/10992#issuecomment-337356417.
Also here: https://github.com/flutter/flutter/issues/13880#issuecomment-355198231

**Comment by long1eu** [comment]
@UlfS thanks
