### ISSUE TITLE
hot_mode_dev_cycle_linux__benchmark test flaked

### ISSUE THREAD

**Issue by aam** [flutter/flutter#13722]
```
stdout: [   +4 ms] Connecting to service protocol: http://127.0.0.1:8100/
stdout: [ +589 ms] Successfully connected to service protocol: http://127.0.0.1:8100/
stdout: [   +2 ms] getVM: {}
stdout: [  +20 ms] getIsolate: {isolateId: isolates/1052946669}
stdout: [   +1 ms] _flutter.listViews: {}
stdout: [  +71 ms] DevFS: Creating new filesystem on the device (null)
stdout: [        ] _createDevFS: {fsName: edited_flutter_gallery}
stdout: [ +100 ms] DevFS: Created new filesystem on the device (file:///data/user/0/io.flutter.examples.gallery/cache/edited_flutter_galleryPWAFJL/edited_flutter_gallery/)
stdout: [   +1 ms] Updating assets
stdout: [ +218 ms] Syncing files to device Moto G 4...
stdout: [   +3 ms] DevFS: Starting sync from LocalDirectory: '/tmp/edited_flutter_gallery'
stdout: [        ] Scanning project files
stdout: [  +11 ms] Scanning package files
stdout: [  +68 ms] Scanning asset files
stdout: [   +3 ms] Scanning for deleted files
stdout: [   +5 ms] Updating files
stdout: [+3869 ms] F/libc    ( 9170): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 9201 (ui_thread)
stdout: [ +163 ms] Retrying writing "packages/flutter/src/material/ink_well.dart" to DevFS due to error: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/
stdout: [        ] Retrying writing "packages/flutter/src/material/icons.dart" to DevFS due to error: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/
stdout: [        ] Retrying writing "packages/flutter/src/material/ink_highlight.dart" to DevFS due to error: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/
stdout: [        ] Retrying writing "packages/flutter/src/material/grid_tile_bar.dart" to DevFS due to error: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/
stdout: [        ] Retrying writing "packages/flutter/src/material/ink_splash.dart" to DevFS due to error: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/
stdout: [        ] Retrying writing "packages/flutter/src/material/icon_button.dart" to DevFS due to error: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/
stdout: [   +1 ms] Service protocol connection closed.
stdout: [        ] Lost connection to device.
stdout: [   +8 ms] DevFS sync failed. Lost connection to device: SocketException: OS Error: Broken pipe, errno = 32, address = 127.0.0.1, port = 46180
stdout: [  +10 ms] "flutter run" took 35,430ms.
stderr: 
stderr: #0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
stderr: #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:341)
stderr: 
stderr: #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
stderr: 
stderr: #3      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
stderr: 
stderr: #4      CommandRunner.runCommand (package:args/command_runner.dart:194)
stderr: 
stderr: #5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
stderr: 
stderr: #6      CommandRunner.run. (package:args/command_runner.dart:109)
stderr: #7      new Future.sync (dart:async/future.dart:222)
stderr: #8      CommandRunner.run (package:args/command_runner.dart:109)
stderr: #9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
stderr: #10     run. (package:flutter_tools/runner.dart:89)
stderr: 
stderr: #11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
stderr: 
stderr: #12     AppContext.runInZone. (package:flutter_tools/src/base/context.dart:66)
stderr: #13     _rootRun (dart:async/zone.dart:1120)
stderr: #14     _CustomZone.run (dart:async/zone.dart:1001)
stderr: #15     runZoned (dart:async/zone.dart:1467)
stderr: #16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
stderr: #17     run (package:flutter_tools/runner.dart:60)
stderr: 
stderr: #18     main (package:flutter_tools/executable.dart:44)
stderr: 
stderr: #19     main (file:///home/linux2/.cocoon/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
stderr: #20     _startIsolate. (dart:isolate-patch/isolate_patch.dart:263)
stderr: #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
stderr: 
stderr: 
stdout: [   +8 ms] exiting with code 3
exitcode: 3
Task failed: FileSystemException: Cannot open file, path = '/tmp/edited_flutter_gallery/hot_benchmark.json' (OS Error: No such file or directory, errno = 2)

Stack trace:
dart:io                                                    _File.readAsStringSync
package:flutter_devicelab/tasks/hot_mode_tests.dart 80:21  createHotModeTest.
===== asynchronous gap ===========================
dart:async                                                 _Completer.completeError
package:flutter_devicelab/tasks/hot_mode_tests.dart 105:3  createHotModeTest.
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_devicelab/tasks/hot_mode_tests.dart 19:19  createHotModeTest.
package:flutter_devicelab/framework/framework.dart 125:36  _TaskRunner._performTask.
===== asynchronous gap ===========================
dart:async                                                 new Future.microtask
package:flutter_devicelab/framework/framework.dart 124:28  _TaskRunner._performTask.
package:stack_trace                                        Chain.capture
package:flutter_devicelab/framework/framework.dart 124:11  _TaskRunner._performTask
package:flutter_devicelab/framework/framework.dart 84:39   _TaskRunner.run

Task execution finished
```

This is on af4ac72

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by godofredoc** [comment]
This is not flaky anymore. Please reopen if it fails again.
