### ISSUE TITLE
Flutter Web: (Release Mode) Uncaught FormatException: SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)

### ISSUE THREAD

**Issue by jerrypaulsam** [flutter/flutter#137323]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Navigate to a page in flutter web release mode that has several formfields and dropdown buttons.

### Expected results

There shouldn't be a parsing error when navigating to screens.

### Actual results

```
main.dart.js:5175 Uncaught FormatException: SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)
    at Object.e (https://demo.com/main.dart.js:5175:19)
    at Object.awR (https://demo.com/main.dart.js:7582:9)
    at aPP.EY (https://demo.com/main.dart.js:50237:21)
    at aPP.d3 (https://demo.com/main.dart.js:50239:21)
    at bfL.$1 (https://demo.com/main.dart.js_301.part.js:5927:50)
    at bdF.$1 (https://demo.com/main.dart.js:52759:21)
    at ci2 (https://demo.com/main.dart.js:5265:17)
    at https://demo.com/main.dart.js:5273:51
```

<details><summary>Logs</summary>
<p>

```


e | @ | main.dart.js:5175
-- | -- | --
  | awR | @ | main.dart.js:7582
  | EY | @ | main.dart.js:50237
  | d3 | @ | main.dart.js:50239
  | $1 | @ | main.dart.js_301.part.js:5927
  | $1 | @ | main.dart.js:52759
  | ci2 | @ | main.dart.js:5265
  | (anonymous) | @ | main.dart.js:5273
  | postMessage (async) |   |  
  | SendXHRCandidate | @ | VM404:1
  | onreadystatechange | @ | VM404:1
  | XMLHttpRequest.send (async) |   |  
  | XMLHttpRequest.send | @ | VM404:1
  | (anonymous) | @ | main.dart.js:55773
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | aXi | @ | main.dart.js:55778
  | N8 | @ | main.dart.js:55715
  | (anonymous) | @ | main.dart.js:55969
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | $1 | @ | main.dart.js:47631
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | tr | @ | main.dart.js:48019
  | $0 | @ | main.dart.js:48066
  | cdE | @ | main.dart.js:6848
  | cep | @ | main.dart.js:6850
  | $1 | @ | main.dart.js:47580
  | ci2 | @ | main.dart.js:5265
  | (anonymous) | @ | main.dart.js:5273
  | childList (async) |   |  
  | $1 | @ | main.dart.js:47587
  | bSN | @ | main.dart.js:6855
  | pX | @ | main.dart.js:6945
  | a3E | @ | main.dart.js:48026
  | ly | @ | main.dart.js:48024
  | dJ | @ | main.dart.js:47622
  | o | @ | main.dart.js:6647
  | (anonymous) | @ | main.dart.js:56065
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | aQe | @ | main.dart.js:56066
  | Le | @ | main.dart.js:56023
  | (anonymous) | @ | main.dart.js:55962
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | aBh | @ | main.dart.js:56018
  | vG | @ | main.dart.js:55956
  | $2 | @ | main.dart.js:56134
  | $0 | @ | main.dart.js:56084
  | $0 | @ | main.dart.js:47849
  | $0 | @ | main.dart.js:47611
  | ci2 | @ | main.dart.js:5264
  | (anonymous) | @ | main.dart.js:5273
  | setTimeout (async) |   |  
  | ax7 | @ | main.dart.js:47596
  | c9U | @ | main.dart.js:6637
  | bGS | @ | main.dart.js:6633
  | dv | @ | main.dart.js:6920
  | Om | @ | main.dart.js:6702
  | (anonymous) | @ | main.dart.js:56075
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | $1 | @ | main.dart.js:56080
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | nl | @ | main.dart.js:48015
  | dJ | @ | main.dart.js:47943
  | $1 | @ | main.dart.js:47881
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | tr | @ | main.dart.js:48019
  | $0 | @ | main.dart.js:48066
  | cdE | @ | main.dart.js:6848
  | cep | @ | main.dart.js:6850
  | $1 | @ | main.dart.js:47580
  | ci2 | @ | main.dart.js:5265
  | (anonymous) | @ | main.dart.js:5273
  | childList (async) |   |  
  | $1 | @ | main.dart.js:47587
  | bSN | @ | main.dart.js:6855
  | pX | @ | main.dart.js:6945
  | a3E | @ | main.dart.js:48026
  | ly | @ | main.dart.js:48024
  | dJ | @ | main.dart.js:47937
  | j5 | @ | main.dart.js:56162
  | xl | @ | main.dart.js:56172
  | (anonymous) | @ | main.dart.js:5307
  | $0 | @ | main.dart.js:56084
  | $0 | @ | main.dart.js:47849
  | $0 | @ | main.dart.js:47611
  | ci2 | @ | main.dart.js:5264
  | (anonymous) | @ | main.dart.js:5273
  | setTimeout (async) |   |  
  | ax7 | @ | main.dart.js:47596
  | c9U | @ | main.dart.js:6637
  | bGS | @ | main.dart.js:6633
  | dv | @ | main.dart.js:6920
  | Om | @ | main.dart.js:6702
  | (anonymous) | @ | main.dart.js:56075
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | $1 | @ | main.dart.js:56080
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | nl | @ | main.dart.js:48015
  | dJ | @ | main.dart.js:47943
  | $1 | @ | main.dart.js:47881
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | tr | @ | main.dart.js:48019
  | $0 | @ | main.dart.js:48066
  | cdE | @ | main.dart.js:6848
  | cep | @ | main.dart.js:6850
  | $1 | @ | main.dart.js:47580
  | ci2 | @ | main.dart.js:5265
  | (anonymous) | @ | main.dart.js:5273
  | childList (async) |   |  
  | $1 | @ | main.dart.js:47587
  | bSN | @ | main.dart.js:6855
  | pX | @ | main.dart.js:6945
  | a3E | @ | main.dart.js:48026
  | ly | @ | main.dart.js:48024
  | dJ | @ | main.dart.js:47937
  | j5 | @ | main.dart.js:56162
  | xl | @ | main.dart.js:56281
  | (anonymous) | @ | main.dart.js:5307
  | $0 | @ | main.dart.js:56084
  | $0 | @ | main.dart.js:47849
  | $0 | @ | main.dart.js:47611
  | ci2 | @ | main.dart.js:5264
  | (anonymous) | @ | main.dart.js:5273
  | setTimeout (async) |   |  
  | ax7 | @ | main.dart.js:47596
  | c9U | @ | main.dart.js:6637
  | bGS | @ | main.dart.js:6633
  | dv | @ | main.dart.js:6920
  | Om | @ | main.dart.js:6702
  | (anonymous) | @ | main.dart.js:56075
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | $1 | @ | main.dart.js:56080
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | nl | @ | main.dart.js:48015
  | $0 | @ | main.dart.js:47849
  | $0 | @ | main.dart.js:47611
  | ci2 | @ | main.dart.js:5264
  | (anonymous) | @ | main.dart.js:5273
  | setTimeout (async) |   |  
  | ax7 | @ | main.dart.js:47596
  | c9U | @ | main.dart.js:6637
  | bGS | @ | main.dart.js:6633
  | dv | @ | main.dart.js:6920
  | Om | @ | main.dart.js:6702
  | (anonymous) | @ | main.dart.js:55942
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | aXj | @ | main.dart.js:55955
  | Ys | @ | main.dart.js:55928
  | (anonymous) | @ | main.dart.js:55923
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | b3v | @ | main.dart.js:55927
  | B8 | @ | main.dart.js:55877
  | b3u | @ | main.dart.js:55878
  | jI | @ | main.dart.js:55865
  | ko | @ | main.dart.js:55866
  | (anonymous) | @ | main.dart.js:111009
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | $1 | @ | main.dart.js:47631
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | tr | @ | main.dart.js:48019
  | dJ | @ | main.dart.js:47625
  | o | @ | main.dart.js:6647
  | (anonymous) | @ | main.dart.js:110092
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | $1 | @ | main.dart.js:47631
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | tr | @ | main.dart.js:48019
  | dJ | @ | main.dart.js:47625
  | o | @ | main.dart.js:6647
  | (anonymous) | @ | main.dart.js:103318
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | $1 | @ | main.dart.js:47631
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | tr | @ | main.dart.js:48019
  | $0 | @ | main.dart.js:48066
  | cdE | @ | main.dart.js:6848
  | cep | @ | main.dart.js:6850
  | $1 | @ | main.dart.js:47580
  | ci2 | @ | main.dart.js:5265
  | (anonymous) | @ | main.dart.js:5273
  | childList (async) |   |  
  | $1 | @ | main.dart.js:47587
  | bSN | @ | main.dart.js:6855
  | pX | @ | main.dart.js:6945
  | a3E | @ | main.dart.js:48026
  | ly | @ | main.dart.js:48024
  | dJ | @ | main.dart.js:47937
  | $1 | @ | main.dart.js:53301
  | ci2 | @ | main.dart.js:5265
  | (anonymous) | @ | main.dart.js:5273
  | Promise.then (async) |   |  
  | iG | @ | main.dart.js:9451
  | (anonymous) | @ | main.dart.js:103314
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | $1 | @ | main.dart.js:47631
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | tr | @ | main.dart.js:48019
  | dJ | @ | main.dart.js:47625
  | o | @ | main.dart.js:6647
  | (anonymous) | @ | main.dart.js:103271
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | $1 | @ | main.dart.js:47631
  | b3V | @ | main.dart.js:48780
  | a01 | @ | main.dart.js:48782
  | $0 | @ | main.dart.js:48095
  | Jm | @ | main.dart.js:6816
  | tr | @ | main.dart.js:48019
  | $0 | @ | main.dart.js:48066
  | cdE | @ | main.dart.js:6848
  | cep | @ | main.dart.js:6850
  | $1 | @ | main.dart.js:47580
  | ci2 | @ | main.dart.js:5265
  | (anonymous) | @ | main.dart.js:5273
  | childList (async) |   |  
  | $1 | @ | main.dart.js:47587
  | bSN | @ | main.dart.js:6855
  | pX | @ | main.dart.js:6945
  | a3E | @ | main.dart.js:48026
  | ly | @ | main.dart.js:48024
  | dJ | @ | main.dart.js:47937
  | $1 | @ | main.dart.js:53301
  | ci2 | @ | main.dart.js:5265
  | (anonymous) | @ | main.dart.js:5273
  | Promise.then (async) |   |  
  | iG | @ | main.dart.js:9451
  | (anonymous) | @ | main.dart.js:103253
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | aDK | @ | main.dart.js:103272
  | vN | @ | main.dart.js:103239
  | (anonymous) | @ | main.dart.js:103308
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | aAT | @ | main.dart.js:103319
  | CM | @ | main.dart.js:103300
  | (anonymous) | @ | main.dart.js:103234
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | b2T | @ | main.dart.js:103238
  | P8 | @ | main.dart.js:103227
  | (anonymous) | @ | main.dart.js:110088
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | b3_ | @ | main.dart.js:110093
  | aP | @ | main.dart.js:110084
  | (anonymous) | @ | main.dart.js:111001
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | kp | @ | main.dart.js:111013
  | (anonymous) | @ | main.dart.js:109856
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | kp | @ | main.dart.js:109865
  | (anonymous) | @ | main.dart.js:108263
  | (anonymous) | @ | main.dart.js:6657
  | $2 | @ | main.dart.js:47637
  | p | @ | main.dart.js:6643
  | kp | @ | main.dart.js:108274
  | V | @ | main.dart.js_195.part.js:5867
  | SS | @ | main.dart.js:87959
  | iw | @ | main.dart.js:87929
  | Aw | @ | main.dart.js:87799
  | hU | @ | main.dart.js:87702
  | oH | @ | main.dart.js:87936
  | Pc | @ | main.dart.js:87886
  | Pb | @ | main.dart.js:87887
  | SS | @ | main.dart.js:87930
  | iw | @ | main.dart.js:87929
  | Aw | @ | main.dart.js:87799
  | Aw | @ | main.dart.js:88111
  | hU | @ | main.dart.js:87702
  | akD | @ | main.dart.js:87735
  | PL | @ | main.dart.js:87750
  | dX | @ | main.dart.js:88125
  | hU | @ | main.dart.js:87699
  | oH | @ | main.dart.js:87936
  | Pc | @ | main.dart.js:87886
  | dX | @ | main.dart.js:87993
  | hU | @ | main.dart.js:87699
  | dX | @ | main.dart.js:88084
  | hU | @ | main.dart.js:87699
  | oH | @ | main.dart.js:87936
  | Pc | @ | main.dart.js:87886
  | dX | @ | main.dart.js:87956
  | hU | @ | main.dart.js:87699
  | oH | @ | main.dart.js:87936
  | oH | @ | main.dart.js:87964
  | Pc | @ | main.dart.js:87886
  | Pb | @ | main.dart.js:87887
  | Ej | @ | main.dart.js:87630
  | aTe | @ | main.dart.js:87651
  | Y7 | @ | main.dart.js:84464
  | aGu | @ | main.dart.js:73815
  | (anonymous) | @ | main.dart.js:5306
  | a7D | @ | main.dart.js:80494
  | a7C | @ | main.dart.js:80498
  | agt | @ | main.dart.js:80484
  | aFj | @ | main.dart.js:80460
  | (anonymous) | @ | main.dart.js:5305
  | vn | @ | main.dart.js:1952
  | $1 | @ | main.dart.js:40589
  | c5z | @ | main.dart.js:5133
  | bN_ | @ | main.dart.js:7803
  | cbq | @ | main.dart.js:9435
  | (anonymous) | @ | main.dart.js:9431
  | requestAnimationFrame (async) |   |  
  | $0 | @ | main.dart.js:40577
  | qo | @ | main.dart.js:41187
  | qo | @ | main.dart.js:80438
  | Yh | @ | main.dart.js:80430
  | B9 | @ | main.dart.js:76057
  | a5 | @ | main.dart.js:76191
  | swm | @ | main.dart.js:79550
  | YT | @ | main.dart.js:73790
  | YT | @ | main.dart.js:84440
  | (anonymous) | @ | main.dart.js:5305
  | vn | @ | main.dart.js:1952
  | Zn | @ | main.dart.js:41059
  | aJS | @ | main.dart.js:36430
  | (anonymous) | @ | main.dart.js:5306
  | b3W | @ | main.dart.js:48762
  | H6 | @ | main.dart.js:48766
  | np | @ | main.dart.js:48449
  | a_o | @ | main.dart.js:48512
  | $0 | @ | main.dart.js:48537
  | cdE | @ | main.dart.js:6848
  | cep | @ | main.dart.js:6850
  | $1 | @ | main.dart.js:47580
  | ci2 | @ | main.dart.js:5265
  | (anonymous) | @ | main.dart.js:5273
  | childList (async) |   |  
  | $1 | @ | main.dart.js:47587
  | bSN | @ | main.dart.js:6855
  | pX | @ | main.dart.js:6945
  | hY | @ | main.dart.js:6867
  | Ih | @ | main.dart.js:48523
  | qB | @ | main.dart.js:48446
  | np | @ | main.dart.js:47838
  | I | @ | main.dart.js:47771
  | aLf | @ | main.dart.js:45549
  | (anonymous) | @ | main.dart.js:5306
  | c5z | @ | main.dart.js:5133
  | bN_ | @ | main.dart.js:7803
  | cbq | @ | main.dart.js:9435
  | (anonymous) | @ | main.dart.js:9431



```

</p>
</details> 

### Code sample

WHen navigating to pages that contains a lot of contents or formfields with dropdown buttons.

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter Doctor output
<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
• Flutter version 3.13.9 on channel stable at /Users/Documents/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/d211f42860350d914a5ad8102f9ec32764dc6d06 (9 hours ago), 2023-10-25 13:42:25 -0700
• Engine revision 0545f8705d
• Dart version 3.1.5
• DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
• Android SDK at /Users/Library/Android/sdk
• Platform android-33, build-tools 33.0.0
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 15A240d
• CocoaPods version 1.13.0

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.83.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
• iPhone (mobile) • 00008110-0018696A1EF0401E • ios • iOS 17.0.3 21A360
• macOS (desktop) • macos • darwin-arm64 • macOS 14.0 23A344 darwin-arm64
• Chrome (web) • chrome • web-javascript • Google Chrome 118.0.5993.88

[✓] Network resources
• All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by dam-ease** [comment]
Hi @jerrypaulsam. Thanks for filing this. Can you check out https://github.com/flutter/flutter/issues/120967#issuecomment-1434648277 to see if it works in your case?

**Comment by jerrypaulsam** [comment]
Hey @dam-ease I saw that comment before. I tried it, but it doesn't work for me unfortunately.

**Comment by dam-ease** [comment]
Thanks for your response. Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
