### ISSUE TITLE
[GoRouter] $extra is null after notifyListeners() forces reload

### ISSUE THREAD

**Issue by claudius-kienle** [flutter/flutter#137397]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open the app and click on 'Go to extra page'
2. Click on 'Click to reload router'

This will first open a page that has as custom typed `$extra` parameter. Everything works as expected, the passed value for this parameter is handed to the new page. But if the router gets forced to reload via `notifyListeners()`, the `$extra` will be None, causing the app to raise an exception.

### Expected results

Just reload the page with the same value for `$extra` as before.

### Actual results

`$extra` is None

### Code sample

Minimal flutter app to reproduce:
[https://github.com/claudius-kienle/flutter-river-pod-bug](https://github.com/claudius-kienle/flutter-river-pod-bug)

### Logs

<details><summary>Logs</summary>

```console
Restarted application in 3,403ms.
[log] Going to / with extra null
[log] Going to / with extra null
[log] Going to /extra-page with extra ExtraClass(content: This is the content)
[log] Going to /extra-page with extra null

════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building Builder:
Null check operator used on a null value

The relevant error-causing widget was
MaterialApp
When the exception was thrown, this was the stack
#0      ExtraPageRoute.build
#1      GoRouteData.$route.builder
#2      RouteBuilder._callGoRouteBuilder.<anonymous closure>
#3      Builder.build
#4      StatelessElement.build
#5      ComponentElement.performRebuild
#6      Element.rebuild
#7      StatelessElement.update
#8      Element.updateChild
#9      SingleChildRenderObjectElement.update
#10     Element.updateChild
#11     ComponentElement.performRebuild
#12     Element.rebuild
#13     StatelessElement.update
#14     Element.updateChild
#15     SingleChildRenderObjectElement.update
#16     Element.updateChild
#17     SingleChildRenderObjectElement.update
#18     Element.updateChild
#19     ComponentElement.performRebuild
#20     StatefulElement.performRebuild
#21     Element.rebuild
#22     StatefulElement.update
#23     Element.updateChild
#24     SingleChildRenderObjectElement.update
#25     Element.updateChild
#26     ComponentElement.performRebuild
#27     StatefulElement.performRebuild
#28     Element.rebuild
#29     StatefulElement.update
#30     Element.updateChild
#31     SingleChildRenderObjectElement.update
#32     Element.updateChild
#33     ComponentElement.performRebuild
#34     StatefulElement.performRebuild
#35     Element.rebuild
#36     StatefulElement.update
#37     Element.updateChild
#38     ComponentElement.performRebuild
#39     StatefulElement.performRebuild
#40     Element.rebuild
#41     StatefulElement.update
#42     Element.updateChild
#43     SingleChildRenderObjectElement.update
#44     Element.updateChild
#45     ComponentElement.performRebuild
#46     StatefulElement.performRebuild
#47     Element.rebuild
#48     StatefulElement.update
#49     Element.updateChild
#50     SingleChildRenderObjectElement.update
#51     Element.updateChild
#52     ComponentElement.performRebuild
#53     StatefulElement.performRebuild
#54     Element.rebuild
#55     StatefulElement.update
#56     Element.updateChild
#57     ComponentElement.performRebuild
#58     StatefulElement.performRebuild
#59     Element.rebuild
#60     StatefulElement.update
#61     Element.updateChild
#62     ComponentElement.performRebuild
#63     Element.rebuild
#64     StatelessElement.update
#65     Element.updateChild
#66     ComponentElement.performRebuild
#67     StatefulElement.performRebuild
#68     Element.rebuild
#69     StatefulElement.update
#70     Element.updateChild
#71     SingleChildRenderObjectElement.update
#72     Element.updateChild
#73     ComponentElement.performRebuild
#74     Element.rebuild
#75     ProxyElement.update
#76     _InheritedNotifierElement.update
#77     Element.updateChild
#78     SingleChildRenderObjectElement.update
#79     Element.updateChild
#80     ComponentElement.performRebuild
#81     StatefulElement.performRebuild
#82     Element.rebuild
#83     StatefulElement.update
#84     Element.updateChild
#85     ComponentElement.performRebuild
#86     Element.rebuild
#87     ProxyElement.update
#88     Element.updateChild
#89     ComponentElement.performRebuild
#90     Element.rebuild
#91     ProxyElement.update
#92     Element.updateChild
#93     ComponentElement.performRebuild
#94     StatefulElement.performRebuild
#95     Element.rebuild
#96     StatefulElement.update
#97     Element.updateChild
#98     ComponentElement.performRebuild
#99     Element.rebuild
#100    StatelessElement.update
#101    Element.updateChild
#102    ComponentElement.performRebuild
#103    Element.rebuild
#104    StatelessElement.update
#105    Element.updateChild
#106    SingleChildRenderObjectElement.update
#107    Element.updateChild
#108    ComponentElement.performRebuild
#109    Element.rebuild
#110    ProxyElement.update
#111    Element.updateChild
#112    ComponentElement.performRebuild
#113    Element.rebuild
#114    ProxyElement.update
#115    Element.updateChild
#116    ComponentElement.performRebuild
#117    StatefulElement.performRebuild
#118    Element.rebuild
#119    StatefulElement.update
#120    Element.updateChild
#121    ComponentElement.performRebuild
#122    StatefulElement.performRebuild
#123    Element.rebuild
#124    StatefulElement.update
#125    Element.updateChild
#126    ComponentElement.performRebuild
#127    StatefulElement.performRebuild
#128    Element.rebuild
#129    BuildOwner.buildScope
#130    WidgetsBinding.drawFrame
#131    RendererBinding._handlePersistentFrameCallback
#132    SchedulerBinding._invokeFrameCallback
#133    SchedulerBinding.handleDrawFrame
#134    SchedulerBinding._handleDrawFrame
#135    _invoke (dart:ui/hooks.dart:170:13)
#136    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#137    _drawFrame (dart:ui/hooks.dart:140:31)
════════════════════════════════════════════════════════════════════════════════

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.7, on Arch Linux 6.5.7-arch1-1, locale C.UTF-8)
    • Flutter version 3.13.7 on channel stable at /home/claudiusk/.development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (3 weeks ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/claudiusk/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/claudiusk/Android/Sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/brave

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (3 available)
    • Pixel 6a (mobile) • 192.168.178.24:5555 • android-arm64  • Android 14 (API 34)
    • Linux (desktop)   • linux               • linux-x64      • Arch Linux 6.5.7-arch1-1
    • Chrome (web)      • chrome              • web-javascript • Brave Browser 106.1.44.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

**Comment by huycozy** [comment]
Hi @claudius-kienle 
Could you narrow down the sample code by only using `go_router_builder` and ValueNotifier to see if the issue still persists?

**Comment by claudius-kienle** [comment]
Hi @huycozy,
sure! I just simplified the example and removed as many dependencies as possible.
The issue still persists. One thing though is that if I replace the custom class `ExtraClass` as type for `$extra` with a standard type, e.g. `String`, the exception does not occur and the code runs as intended.

**Comment by huycozy** [comment]
Thanks for the update. 

>One thing I figured out though is that if I replace the custom class ExtraClass as type for $extra with a standard type, e.g. String, the exception does not occur and the code runs as intended.

Yes, it's indeed the cause. You are using a custom object for extra parameter which is not supported yet, please see [Type conversions](https://pub.dev/packages/go_router_builder#type-conversions) and a known proposal for this at https://github.com/flutter/flutter/issues/110781.

Closing this issue in favor of #110781. Please follow up on it for updates.
