### ISSUE TITLE
flutter_module_test frequent failures in build.dart

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#137418]
This appears to be a bug in the packages depended on by the tests ffi `build.dart` generated by https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/package_ffi/build.dart.tmpl#L1

@dcharkes 

```
[2023-10-27 02:46:19.229580] [STDOUT] stdout:                        build.dart returned with exit code: 255.
[2023-10-27 02:46:19.229586] [STDOUT] stdout:                        To reproduce run:
[2023-10-27 02:46:19.229593] [STDOUT] stdout:                        /opt/s/w/ir/x/w/recipe_cleanup/tmp8mlkod7v/flutter sdk/bin/dart --packages=/opt/s/w/ir/x/t/flutter_module_test.NhBYM6/hello/.dart_tool/package_config.json /opt/s/w/ir/x/t/flutter_module_test.NhBYM6/ffi_package/build.dart --config=/opt/s/w/ir/x/t/flutter_module_test.NhBYM6/hello/.dart_tool/native_assets_builder/e5f052c3025f3a319f6dd3717bed6fa6/config.yaml
[2023-10-27 02:46:19.229599] [STDOUT] stdout:                        stderr:
[2023-10-27 02:46:19.229605] [STDOUT] stdout:                        Unhandled exception:
[2023-10-27 02:46:19.229611] [STDOUT] stdout:                        Unsupported operation: Cannot add to an unmodifiable list
[2023-10-27 02:46:19.229617] [STDOUT] stdout:                        #0      UnmodifiableListMixin.addAll (dart:_internal/list.dart:129:5)
[2023-10-27 02:46:19.229623] [STDOUT] stdout:                        #1      CBuilder.run (package:native_toolchain_c/src/cbuilder/cbuilder.dart:276:45)
[2023-10-27 02:46:19.229629] [STDOUT] stdout:                        <asynchronous suspension>
[2023-10-27 02:46:19.229635] [STDOUT] stdout:                        #2      main (file:///opt/s/w/ir/x/t/flutter_module_test.NhBYM6/ffi_package/build.dart:18:3)
[2023-10-27 02:46:19.229641] [STDOUT] stdout:                        <asynchronous suspension>
```

https://github.com/dart-lang/native/blob/main/pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart#L276

**Comment by zanderso** [comment]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64_ios%20module_test_ios/8637/overview

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_5_6/10537/overview

**Comment by dcharkes** [comment]
I have retracted the bad package version (0.3.1), so pub should resolve the build.dart dependency to 0.3.0 again.

The builds should succeed again now.

Cross linking issues on other repos:

* https://github.com/dart-lang/sdk/issues/53881
* https://github.com/dart-lang/native/issues/168

I'll keep this issue open, because we should hard-pin the dependencies in the template, instead of letting 0.3.0 resolve to 0.3.1.

Lowering prio, so I can take a look at this on Monday. (Please set it back to P0 if there are still failures occurring.)
