### ISSUE TITLE
Android project doesn't run but the Linux one does

### ISSUE THREAD

**Issue by yolowex** [flutter/flutter#137417]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open my project Intellij 
2. run the project on android either with the run button or the "flutter run" command
3. the project doesn't run on android

### Actual results

I entered my hello world project and run "flutter run" while my android phone is connected to the pc and the debug mode is on.
sometimes it gives me a prompt like below, sometimes it runs forever and neither compiles the project nor gives me any errors.

The Linux build works perfectly, after 2~3 seconds, the hello world project runs on my desktop.

I should also mention that "flutter build apk" also doesn't work. it doesn't give me an error and runs forever, never running the project.

Also, I ran many apps in debug mode on my phone (using Java), so there's no way it's a problem with my phone or adb.

I tried, "flutter clean" too, but no luck.

### Logs

<details>
<summary>Logs</summary>

```console

```
Launching lib/main.dart on SM A225F in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1616)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1434)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1336)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2787)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1426)
	... 18 more
[!] Gradle threw an error while downloading artifacts from the network.
Retrying Gradle Build: #1, wait time: 100ms
Running Gradle task 'assembleDebug'...

```

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
└─$ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.8, on Kali GNU/Linux Rolling 6.4.0-kali3-amd64, locale en_US.UTF-8)
    • Flutter version 3.13.8 on channel stable at /home/yolo/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (9 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/yolo/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /home/yolo/android-studio-chipmunk/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.0)
    • Android Studio at /home/yolo/android-studio-old
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "1.8.0_152-release"

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/yolo/android-studio-chipmunk
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "11.0.12" 2021-07-20

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /home/yolo/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.6008.13
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /home/yolo/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.9011.34
    • Flutter plugin version 74.0.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM A225F (mobile) • R58R918KD3B • android-arm64 • Android 12 (API 31)
    • Linux (desktop)   • linux       • linux-x64     • Kali GNU/Linux Rolling 6.4.0-kali3-amd64

[!] Network resources                   
    ✗ A network error occurred while checking "https://maven.google.com/": Connection timed out

! Doctor found issues in 2 categories
```

</details>

**Comment by yolowex** [comment]
The problem was solved after I created a new project using "flutter create".
It seems that how I created my project with Intellij was the problem.
network connection was part of the problem too.
