### ISSUE TITLE
Failed assertion: line 205 pos 12: '!_debugDuringDeviceUpdate': is not true.

### ISSUE THREAD

**Issue by alpeshshiyal** [flutter/flutter#137599]
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 205 pos 12: '!_debugDuringDeviceUpdate': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:205:12)
#3      MouseTracker.updateAllDevices (package:flutter/src/rendering/mouse_tracker.dart:366:5)
#4      RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure> (package:flutter/src/rendering/binding.dart:398:22)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#8      _invoke (dart:ui/hooks.dart:145:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#10     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

This issue is causes when meedu player for video is open in windows 11

**Comment by huycozy** [comment]
Hi @alpeshshiyal 
If the issue is caused by meedu player plugin/package, you should report an issue to its developers for better support there. Otherwise, please fill out all information indicated in the issue template so that we can address this issue properly (see [Report a bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml) template)
