### ISSUE TITLE
The following assertion was thrown while dispatching notifications for FocusNode

### ISSUE THREAD

**Issue by Hibecode** [flutter/flutter#137552]
```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for FocusNode:
Range start 2 is out of text of length 1
'package:flutter/src/services/text_input.dart':
Failed assertion: line 963 pos 12: 'range.start >= 0 && range.start <= text.length'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TextEditingValue._textRangeIsValid (package:flutter/src/services/text_input.dart:963:12)
#3      TextEditingValue.toJSON (package:flutter/src/services/text_input.dart:918:12)
#4      AutofillConfiguration.toJson (package:flutter/src/services/autofill.dart:742:47)
#5      TextInputConfiguration.toJson (package:flutter/src/services/text_input.dart:692:66)
#6      _PlatformTextInputControl._configurationToJson (package:flutter/src/services/text_input.dart:2214:53)
#7      _PlatformTextInputControl.attach (package:flutter/src/services/text_input.dart:2227:9)
#8      TextInput._setClient (package:flutter/src/services/text_input.dart:1917:15)
#9      TextInput._attach (package:flutter/src/services/text_input.dart:1704:5)
#10     TextInput.attach (package:flutter/src/services/text_input.dart:1693:15)
#11     EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:3147:21)
#12     EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:3183:7)
#13     EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:3719:5)
#14     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#15     FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1048:5)
#16     FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1644:12)
(elided 4 frames from class _AssertionError and dart:async)
The FocusNode sending notification was: FocusNode#62c3d([PRIMARY FOCUS])
  context: Focus
  PRIMARY FOCUS

```

**Comment by darshankawar** [comment]
@Hibecode 
Only posting error log isn't much helpful. You also need to provide `flutter doctor -v` and a minimal reproducible code sample that shows the reported error, so that we can properly address the issue.
