### ISSUE TITLE
flutter installation was not successful on MacBook Pro M2  

### ISSUE THREAD

**Issue by srikrishnaraorakuten** [flutter/flutter#137662]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Step 1 : 

I followed the instructions from https://docs.flutter.dev/get-started/install/macos 
and downloaded the Flutter bundle from the following link https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.13.9-stable.zip 
 	

Step 2: 

Extract the file in the desired location. For example:

content_copy
 cd ~/development
 unzip ~/Downloads/flutter_macos_arm64_3.13.9-stable.zip
Add the flutter tool to your path:
content_copy
 export PATH="$PATH:`pwd`/flutter/bin"
This command sets your PATH variable for the current terminal window only. To permanently add Flutter to your path, check out Update your path.

Step 3: 

check flutter installation by running `flutter` and there was no problem 

Step 4 : 
When i executed 
`flutter  doctor -v`

I had an error 

### Actual results

srikrishna.rao@macbook% flutter doctor -v 

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:323:5)
<asynchronous suspension>
#3      PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:126:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:679:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1566:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
``` 

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:323:5)
<asynchronous suspension>
#3      PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:126:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:679:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1566:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>



```

</details>

**Comment by dam-ease** [comment]
Hi @srikrishnaraorakuten. It seems the installation hasn't been fully completed, are you certain you are setting the PATH correctly, also when you run `which flutter` from your terminal, do you get a response?

**Comment by srikrishnaraorakuten** [comment]
@dam-ease  

This is my response for which command 

srikrishna.rao@MACBOOK Learning %  which flutter
/Users/srikrishna.rao/Learning/flutter/bin/flutter

**Comment by dam-ease** [comment]
Hi @srikrishnaraorakuten. Thanks for your response. Can you try reinstalling flutter on your machine probably following the video suggested [here](https://github.com/flutter/flutter/issues/137662#issuecomment-1788582549) to see if this still reoccurs?
