### ISSUE TITLE
[tool_crash] WebDriverException

### ISSUE THREAD

**Issue by RockyIsHere** [flutter/flutter#137640]
## Command
```
flutter driver --driver=test_driver/integration_test_driver.dart --target=test/integration_test/auth_test.dart -d chrome --web-port=4444 --browser-name=chrome --screenshot=test_report --profile-memory=profile_memory.json
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WebDriverException
```
#0      InferSessionHandler.parseCreateResponse (package:webdriver/src/han

**Comment by dam-ease** [comment]
Hi @RockyIsHere. Thanks for filing this. 
Can you provide flutter doctor -v ? Does this crash occur everytime you run the said command ?
Can you also check if you get any output after running chromedriver --verbose and provide the same here ?
Also, can you provide webdriver version you are using along with chrome version as well ?

**Comment by RockyIsHere** [comment]
chrome version = 118.0.5993.117

**Comment by RockyIsHere** [comment]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter driver --driver=test_driver/integration_test_driver.dart --target=test/integration_test/auth_test.dart -d chrome --web-port=4444 --browser-name=chrome --screenshot=test_report --profile-memory=profile_memory.json

## exception

WebDriverException: WebDriverException (404): Error parsing response body: <empty response>

```
#0      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:97:7)
#1      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#2      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#3      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:144:19)
<asynchronous suspension>
#4      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:323:30)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-x64, locale en-IN)
    [32m•[39m Flutter version 3.13.6 on channel stable at /Users/rockykarmakar/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision ead455963c (5 weeks ago), 2023-09-26 18:28:17 -0700
    [32m•[39m Engine revision a794cf2681
    [32m•[39m Dart version 3.1.3
    [32m•[39m DevTools version 2.25.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/rockykarmakar/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 15.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15A240d
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA Edu.app
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m VS Code (version 1.83.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.74.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 14.0 23A344 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.105

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.
```

**Comment by dam-ease** [comment]
I don't see a similar issue present, so labelling it for further investigation from the team.
