### ISSUE TITLE
[pigeon] [v12.0.0] NullPointerException crash because of wrong pigeon generation for FlutterApi which has void as return type

### ISSUE THREAD

**Issue by SharmaPrateek196** [flutter/flutter#137699]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have created a flutter api as below 
```
@FlutterApi()
abstract class AuthRefresherHandler {
  void logout();
}
```

The generated pigeon for this is as below 
```
public static class AuthRefresherHandler {
    private final @NonNull BinaryMessenger binaryMessenger;

    public AuthRefresherHandler(@NonNull BinaryMessenger argBinaryMessenger) {
      this.binaryMessenger = argBinaryMessenger;
    }

    /** Public interface for sending reply. */ 
    /** The codec used by AuthRefresherHandler. */
    static @NonNull MessageCodec<Object> getCodec() {
      return new StandardMessageCodec();
    }

public void logout(@NonNull Result<Void> result) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, "dev.flutter.pigeon.network.AuthRefresherHandler.logout", getCodec());
      channel.send(
          null,
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), (String) listReply.get(2)));
              } else {
                **result.success(null);** // This line is causing the issue
              }
            }  else {
              result.error(new FlutterError("channel-error",  "Unable to establish connection on channel.", ""));
            } 
          });
    }
}
```

I am using this pigeon from kotlin code like below 
```
val myObj = object : Network.Result<Void> {
            override fun success(result: Void) {
                TODO("Not yet implemented")
            }

            override fun error(error: Throwable) {
                TODO("Not yet implemented")
            }
        }
        withContext(Dispatchers.Main) {
            AuthRefresherHandler(flutterPluginBinding.binaryMessenger).logout(myObj)
        }
```

Once I call this method from native, I get the below crash

> Failed to handle message reply
                                                                                                    java.lang.NullPointerException: Parameter specified as non-null is null: method cred.biz.network.AuthRefresherImpl$logout$myObj$1.success, parameter result
                                                                                                    	at cred.biz.network.AuthRefresherImpl$logout$myObj$1.success(Unknown Source:2)
                                                                                                    	at cred.biz.network.AuthRefresherImpl$logout$myObj$1.success(NetworkPluginInitializer.kt:146)
                                                                                                    	at cred.biz.network.Network$AuthRefresherHandler.lambda$logout$1(Network.java:771)
                                                                                                    	at cred.biz.network.Network$AuthRefresherHandler$$ExternalSyntheticLambda0.reply(Unknown Source:2)
                                                                                                    	at io.flutter.plugin.common.BasicMessageChannel$IncomingReplyHandler.reply(BasicMessageChannel.java:200)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:380)
                                                                                                    	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:1021)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

 **result.success(null);** // This line in the generated code is causing the null pointer exception.

**Note: my flutter version is 3.10.5 and pigeons version is 12.0.0**

### Expected results

The app should not get NullPointerException. And pigeon call should be successful.

### Actual results

App is getting NullPointerException because the generated pigeon is passing null in a result.success of type void.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Failed to handle message reply
                                                                                                    java.lang.NullPointerException: Parameter specified as non-null is null: method cred.biz.network.AuthRefresherImpl$logout$myObj$1.success, parameter result
                                                                                                    	at cred.biz.network.AuthRefresherImpl$logout$myObj$1.success(Unknown Source:2)
                                                                                                    	at cred.biz.network.AuthRefresherImpl$logout$myObj$1.success(NetworkPluginInitializer.kt:146)
                                                                                                    	at cred.biz.network.Network$AuthRefresherHandler.lambda$logout$1(Network.java:771)
                                                                                                    	at cred.biz.network.Network$AuthRefresherHandler$$ExternalSyntheticLambda0.reply(Unknown Source:2)
                                                                                                    	at io.flutter.plugin.common.BasicMessageChannel$IncomingReplyHandler.reply(BasicMessageChannel.java:200)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:380)
                                                                                                    	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:1021)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

</details>

### Flutter Doctor output

<details><summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-arm64, locale en-IN)
    • Flutter version 3.10.5 on channel stable at /Users/prateeksharma/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/prateeksharma/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 13.0.1 22A400 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
> **result.success(null);** // This line is causing the issue

`null` is the only possible value to use with `Void` in Java, so I don't think the title is correct that the Pigeon generation is incorrect here. If you use `Void?` as the type in your Kotlin code, does it work?

(Out of curiosity, if you are calling this from Kotlin code, is there a reason you are using the Java generator rather than the Kotlin generator?)

**Comment by SharmaPrateek196** [comment]
I tried kotlin generator and that is generating Unit instead of null and that is working fine. 
I think I should use kotlin one only.

**Comment by stuartmorgan** [comment]
> I tried kotlin generator and that is generating Unit instead of null

That's expected; Kotlin and Java don't express this concept in the same way.

Did using a different type in your Kotlin code interoperate with the Java `Result<Void>`?
