### ISSUE TITLE
google_sign_in - com.google.android.gms.common.api.ApiException: 10

### ISSUE THREAD

**Issue by Konstanius** [flutter/flutter#137614]
Is there an existing issue for this?

- [x]  I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x]  I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

After reading through countless similar issues
e.g.:

- https://stackoverflow.com/questions/61541415/flutter-platformexceptionsign-in-failed-com-google-android-gms-common-api-ap
- https://stackoverflow.com/questions/54557479/flutter-and-google-sign-in-plugin-platformexceptionsign-in-failed-com-google
- https://github.com/flutter/flutter/issues/75224

and other documentation, changing my Firebase configuration, google-services.json, creating and recreating countless Google Cloud credentials, I have finally decided to post my issue here in hopes of help from others.

My Flutter app is supposed to connect with the Google Calendar of the user logging in, to synchronize their events in their calendar across their devices.

This requires the sensitive scopes:

```dart
static const List<String> scopes = ['https://www.googleapis.com/auth/calendar', 'https://www.googleapis.com/auth/calendar.events'];
```

Secondly, to sign in with google, I tried using https://pub.dev/packages/googleapis_auth, but after that failed due to Googles migration away from loopback URLs, I found https://pub.dev/packages/extension_google_sign_in_as_googleapis_auth, which uses https://pub.dev/packages/google_sign_in to let the user sign in, and then provide me with an AuthClient.

Trying this out successfully opens a dialog to the user, asking them, which Google Account they would like to sign in with, but upon selecting any, I get the (now dreaded) ```com.google.android.gms.common.api.ApiException: 10```

Through reading issues others had with Google oAuth, I found the following, leading me to my current configuration:

## Getting the certificates
- I got the playstore signing and playstore upload certificate hashes from the Play Console
- The debug certificate hashes were found using ```gradlew signingReport```

## Firebase:
- Both the SHA1 and SHA256 hashes have to be uploaded for each certificate
- I added that for the playstore signing, playstore upload, and my apps debug certificate
- I re-downloaded the google-services.json and added it to my app
- The support email was set
- Flutter clean was run before cold starting the app

## Google Cloud:
- All 3 of these certificates SHA1 hashes have a separate Android oAuth credential
- I decided to test it by using my debug certificate, so I downloaded the debug clientId and implemented it in my code:

```dart
GoogleSignIn _googleSignIn = GoogleSignIn(
  clientId: debugClientId, // Technically unused
  serverClientId: debugClientId,
  forceCodeForRefreshToken: true,
  scopes: scopes,
);
```

- The consent dialog had to be setup properly, which I did by filling out all fields whilst keeping the dialog in testing mode, to prevent it from requiring verification
- The consent dialog, since it is in testing mode, required me to add all emails which it would be enabled for, which I did for the emails that I would be clicking in the sign in with Google dialog

## Actually signing in:
- The app was built
- I wait until the appropriate time to ask the user for permission
- The sign in with Google dialog was called using the below dart code:

```dart
GoogleSignInAccount? currentUser = await _googleSignIn.signIn()
```

However, this just yields the issue as described above, here with its complete StackTrace:

```
I/flutter ( 6057): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
I/flutter ( 6057): #0      GoogleSignInApi.signIn (package:google_sign_in_android/src/messages.g.dart:221:7)
I/flutter ( 6057): <asynchronous suspension>
I/flutter ( 6057): #1      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:278:30)
I/flutter ( 6057): <asynchronous suspension>
I/flutter ( 6057): #2      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
I/flutter ( 6057): <asynchronous suspension>
I/flutter ( 6057): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
I/flutter ( 6057): #0      GoogleSignInApi.signIn (package:google_sign_in_android/src/messages.g.dart:221:7)
I/flutter ( 6057): <asynchronous suspension>
I/flutter ( 6057): #1      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:278:30)
I/flutter ( 6057): <asynchronous suspension>
I/flutter ( 6057): #2      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
I/flutter ( 6057): <asynchronous suspension>
```

At this point, I am considering canceling the feature entirely and staying with local calendars, as it is not a core feature, but this has to work somehow, right?

Flutter doctor
<details>
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.25336.1010], locale en-GB)
    • Flutter version 3.13.3 on channel stable at C:\Users\Konstanius\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (8 weeks ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Konstanius\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33414.496
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at C:\Users\Konstanius\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 232.10072.19

[√] VS Code (version 1.79.0)
    • VS Code at C:\Users\Konstanius\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • RMX1921 (mobile)  • abb55705 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.25336.1010]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 118.0.5993.118
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 120.0.2172.1

[√] Network resources
    • All expected network resources are available.

• No issues found!
</details>

**Comment by Konstanius** [comment]
So I also just for fun decided to remove the clientId from the GoogleSignIn information, and turns out that works, letting me sign in and warning me that the app is not yet verified.

But does that solve this issue?

**Comment by darshankawar** [comment]
Thanks for the report @Konstanius 
The error you are getting seems to be a known issue as mentioned in the linked issue and ideally need to be followed-up in it and also https://github.com/flutter/flutter/issues/33393. Do check if https://github.com/flutter/flutter/issues/33393#issuecomment-510395178 or https://github.com/flutter/flutter/issues/33393#issuecomment-1682116137 helps in your case or not.

Another solution that worked for others is as mentioned [here](https://github.com/flutter/flutter/issues/117761#issuecomment-1367957461).

**Comment by Konstanius** [comment]
So, using a web client Id seems to have worked exactly the same way as using no client Id at all, which is rather even more confusing.

With this in mind, I went back to https://pub.dev/packages/googleapis_auth to try and see if the issue of it can be resolved also by using a web client Id and its secret, instead of Android, which got me a long way further than the loopback issue I described before, letting me select a google account, but the redirect (which had to be added to google cloud as "http://127.0.0.1:<port>) did not function correctly, instead opening in a Browser.

I think there should be a general overhaul to the documentation of both https://pub.dev/packages/googleapis_auth and https://pub.dev/packages/google_sign_in, since there are hundreds of issues around the correct setup. Thank you for your response.

**Comment by darshankawar** [comment]
> I think there should be a general overhaul to the documentation of both https://pub.dev/packages/googleapis_auth and https://pub.dev/packages/google_sign_in, since there are hundreds of issues around the correct setup. Thank you for your response.

@Konstanius  https://pub.dev/packages/googleapis_auth  is a google package for which you'll need to open respective issue in dedicated repo: https://github.com/google/googleapis.dart/issues

For https://pub.dev/packages/google_sign_in, can you elaborate on what exactly need to be added in the documentation so that we can address it properly. The same then can be linked to the original issue for better tracking.

**Comment by Konstanius** [comment]
https://github.com/flutter/packages/pull/5296 should be enough information added

**Comment by darshankawar** [comment]
Thanks for the update and potential fix.

**Comment by stuartmorgan** [comment]
We may want to collect several of these as duplicates into a single issue for adding something to the README (and to see if any more information is available on the native side that we could pass back), but confirming for now to track docs.

**Comment by abdurrahmanarikan** [comment]
I still have the same issue even though I have followed all the steps from above suggestions. The funny thing is that we generate release version of apk and it perfectly works. When we publish it, it starts to show the same error message again:
google_sign_in - com.google.android.gms.common.api.ApiException: 10

PS: I suspect that Google might not allow our app because we are still waiting for  OAuth consent screen to be completed:

<img width="578" alt="image" src="https://github.com/flutter/flutter/assets/24858031/35d57bb0-eda2-4f51-bd12-8bf9bb7dfe8d">
(even though it is already more than 10 days, we did not receive any official email from Google, but this is irrelevant from flutter)

**Comment by kjxbyz** [comment]
same issue, it works for me.

**Comment by bguan** [comment]
I am calling Cloud Text to Speech API (not Firebase) and has the same issue:
* in my flutter 3.19.5 app (ported from old code 2 years ago)
* via googleapis 13.1.0
* using extension_google_sign_in_as_googleapis_auth 2.0.12

I am getting this exception:
* PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
* When running app in Android emulator Pixel 3A API 34
* Reading docs from https://pub.dev/packages/google_sign_in_android provides no clue on how to achieve the same under ios and web e.g. setting oauth client ID via configuration.


Note that developing on my Macbook Air M2 running macos 14.4.1 in Android Studio I am able to get it to work in:

* ios 17.4.1 on my physical iPhone 14 pro
  * (referencing https://pub.dev/packages/google_sign_in_ios)
  * by configuring GIDClientID and CFBundleURLTypes 
  * in Info.plist 
  * with values from Google cloud console apis/credentials/oauthclient of type ios
 
* chrome 123.0.6312.122 on my laptop
  * (referencing https://pub.dev/packages/google_sign_in_web)
  * by configuring google-signin-client_id
  * in index.html 
  * with values from Google cloud console apis/credentials/oauthclient of type web app
  * also setting Authorized JavaScript origins in console properly, including localhost and port for local debugging

Also note that I was able to get all 3 platforms working 2 years ago with no such fuss.

**Comment by crushman1** [comment]
Is there no solution to this ? i have been trying to figure it out for 3 days now. I have tried very possible solution

**Comment by DaxeshV** [comment]
If google don't want to provide any solution then remove google login option from firebase.

**Comment by Yan22Oliveira** [comment]
> Então, também por diversão, decidi remover o clientId das informações do GoogleSignIn e descobri que funciona, permitindo-me fazer login e avisando que o aplicativo ainda não foi verificado.
> 
> Mas isso resolve esse problema?

Fiquei uma semana tentando descobrir qual era esse erro. Até que removi essa linha do clientId e deu certo!!! 

Muito obrigado pela resposta

**Comment by dagyu** [comment]
I too have had the same problem and I understand your frustrations, in fact I don't understand why nowhere is the proper setup well explained. I solved it by adding the SHA-1 found on Play Console under App Signin > App signing key certificate.

So, when you create the client ID on google cloud console, in addition to the SHA-1 of the release and debug variant another one needs to be added, for a total of 3 SHA-1s to be entered.

* If you use firebase ,the SHA-1 should be entered in the appropriate section of app setup and the new `google-service.json` should be downloaded.  
* If you do not use firebase, however, follow [this guide](https://medium.com/codebrew/flutter-google-sign-in-without-firebase-3680713966fb) (mentioned above), remembering that a third client ID must be created in addition to the 2 client IDs for debug and release.

I hope this helps you and you too can solve it.

**Comment by digitpk** [comment]
After extensive research and testing, I successfully resolved the error by adding the SHA1 key from the Google Play Console to my Firebase project settings. Strangely, I did not upload the key for determining the issue but was automatically generated by Google during the initial app publication.

**Comment by stargaze-061** [comment]
> I still have the same issue even though I have followed all the steps from above suggestions. The funny thing is that we generate release version of apk and it perfectly works. When we publish it, it starts to show the same error message again: google_sign_in - com.google.android.gms.common.api.ApiException: 10
> 
> PS: Our Cred API SHA1 and SHA256 keys are already in firebase app settings config. I suspect that Google might not allow our app because we are still waiting for OAuth consent screen to be completed:
> 
> <img alt="image" width="578" src="https://private-user-images.githubusercontent.com/24858031/292052674-35d57bb0-eda2-4f51-bd12-8bf9bb7dfe8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDY5MTMsIm5iZiI6MTcyMDk0NjYxMywicGF0aCI6Ii8yNDg1ODAzMS8yOTIwNTI2NzQtMzVkNTdiYjAtZWRhMi00ZjUxLWJkMTItOGJmOWJiN2RmZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA4NDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTZiZDljZGVlMzRiMzQ0NjRhYjRiZTI0N2MxNjdjNTc0YzA1YzQxZTFkODdmMjhlNjg5YTg0NTM4ZGRiMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92s8eoA9EMr7jry-2uSTGAENaNY_OPKNelW0fakc774"> (even though it is already more than 10 days, we did not receive any official email from Google, but this is irrelevant from flutter)

Did you receive any response from Google? Was the problem solved after passing the OAuth Consent screen review?

**Comment by Tananga** [comment]
I have the same issue. Google_signin package was last updated 9 months ago. This is a critical feature.

**Comment by trunghieuvn** [comment]
I happened same as issue, I tried fixed and work well for me
https://github.com/googlesamples/google-services/issues/253#issuecomment-2365227410

**Comment by allComputableThings** [comment]
> I too have had the same problem and I understand your frustrations, in fact I don't understand why nowhere is the proper setup well explained. I solved it by adding the SHA-1 found on Play Console under App Signin > App signing key certificate.

Is this the expected behavior. Does Google Sign In depend on a Google Play items for the app?

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/33393. (As noted there, we have other issues tracking docs updates.)
