### ISSUE TITLE
Unable to run Flutter app for armeabi-v7a architecture due to "libflutter.so not found" error

### ISSUE THREAD

**Issue by Vofchuk** [flutter/flutter#137622]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am attempting to build my Flutter app for the `armeabi-v7a` architecture because it uses a android SDK that only works with  `armeabi-v7a` Despite setting the `abiFilters` to `'armeabi-v7a'` in my `build.gradle` file, I am encountering a "libflutter.so not found" error when trying to run the app.

1. Create a new flutter project
2. Set the abiFilters to 'armeabi-v7a' in the android/app/build.gradle file.
```dart
android {
    ...
    defaultConfig {
        ...
        ndk {
            abiFilters 'armeabi-v7a'
        }
    }
}
```
3. Run the project
4. Observe the "libflutter.so not found" error.

### Expected results

The app should run normaly

### Actual results

```console
Launching lib/main.dart on Pixel 6 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/FlutterLoader( 3302): Flutter initialization failed.
E/FlutterLoader( 3302): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 3302): 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
E/FlutterLoader( 3302): 	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
E/FlutterLoader( 3302): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:241)
E/FlutterLoader( 3302): 	at io.flutter.embedding.engine.FlutterEngineGroup.<init>(FlutterEngineGroup.java:63)
E/FlutterLoader( 3302): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:324)
E/FlutterLoader( 3302): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:189)
E/FlutterLoader( 3302): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:643)
E/FlutterLoader( 3302): 	at android.app.Activity.performCreate(Activity.java:8595)
E/FlutterLoader( 3302): 	at android.app.Activity.performCreate(Activity.java:8573)
E/FlutterLoader( 3302): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
E/FlutterLoader( 3302): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
E/FlutterLoader( 3302): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
E/FlutterLoader( 3302): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/FlutterLoader( 3302): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/FlutterLoader( 3302): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/FlutterLoader( 3302): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
E/FlutterLoader( 3302): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader( 3302): 	at android.os.Looper.loopOnce(Looper.java:205)
E/FlutterLoader( 3302): 	at android.os.Looper.loop(Looper.java:294)
E/FlutterLoader( 3302): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/FlutterLoader( 3302): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader( 3302): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/FlutterLoader( 3302): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/FlutterLoader( 3302): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 3302): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
E/FlutterLoader( 3302): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/FlutterLoader( 3302): 	at java.lang.System.loadLibrary(System.java:1661)
E/FlutterLoader( 3302): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/FlutterLoader( 3302): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:191)
E/FlutterLoader( 3302): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:184)
E/FlutterLoader( 3302): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/FlutterLoader( 3302): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/FlutterLoader( 3302): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/FlutterLoader( 3302): 	at java.lang.Thread.run(Thread.java:1012)
Application finished.

Exited.
```

### Code sample

<details><summary>Code sample</summary>
The only thing changed:

```dart
defaultConfig {

        ndk {//ADDED THIS LINE
        abiFilters 'armeabi-v7a'
        }

        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.armeabi_v7a_not_run"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-BR)
    • Flutter version 3.13.6 on channel stable at /Users/dani/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dani/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.75.20231002

[✓] Connected device (5 available)
    • Pixel 6 (mobile)            • 1C101FDF6005SY            • android-arm64  • Android 14 (API 34)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone Vizo 2 (mobile)      • 00008020-000B58AA1A44402E • ios            • iOS 16.5.1 20F75
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 118.0.5993.117
    ! Error: iPhone Vizo 2 is busy: Preparing iPhone Vizo 2. Xcode will continue when iPhone Vizo 2 is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by Vofchuk** [comment]
I just found [this article](https://yrom.net/blog/2019/04/24/flutter-run-lost-libflutter-so-when-using-abiFilters/) that explains why this is happening, but I don't see any solution

**Comment by dam-ease** [comment]
Hi @Vofchuk. Thanks for filing this. I see there is an open issue describing this case https://github.com/flutter/flutter/issues/57237. Can you check out the solutions there to see if any works in your case? 
Also, kindly comment, upvote and follow up on the issue for updates. I'll be closing this in favour of the already open issue, if you disagree please comment and I'll reopen this.
Thank you!
