### ISSUE TITLE
[web] - Autofill dispatches empty key events on Chrome + Safari which cause console errors

### ISSUE THREAD

**Issue by htoor3** [flutter/flutter#137771]
When we handle key events in the engine, we expect them to be non-null.  However, on Chrome and Safari, autofill dispatches empty keydown and keyup events (events with null properties like `code`, `keyCode` etc), which triggers the console errors. 

From what I've seen, this doesn't cause any functionality issues on Desktop Web.  This also doesn't occur on Firefox. 
<img width="528" alt="Screenshot 2023-11-02 at 11 10 45 AM" src="https://github.com/flutter/flutter/assets/110993981/2448c4f8-db39-42dd-8811-f9b5d18c3cf9">

**Comment by dam-ease** [comment]
I can reproduce this on the latest `master` and `stable` channels on Safari and Chrome. Tested on Firefox but couldn't reproduce as well.

| Chrome | Safari |
|--------|--------|
| <img width="700" alt="Screenshot 2023-11-10 at 15 20 06" src="https://github.com/flutter/flutter/assets/53122008/90548c20-9d25-4da0-b33d-464bfdbb0d76"> | <img width="700" alt="Screenshot 2023-11-10 at 15 27 32" src="https://github.com/flutter/flutter/assets/53122008/f5118138-1445-4f9b-9cb7-332108db77d9"> | 

<details><summary>Logs</summary>
<p>

```
errors.dart:294 Uncaught Error: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:294:49)
    at Object.nullCheck (operations.dart:855:63)
    at [_handleEvent] (keyboard_binding.dart:372:38)
    at _engine.KeyboardConverter.new.handleEvent (keyboard_binding.dart:582:7)
    at keyboard_binding.dart:101:18
    at loggedHandler (keyboard_binding.dart:140:16)
    at Object._checkAndCall (operations.dart:574:37)
    at Object.dcall (operations.dart:579:39)
    at ret (js_allow_interop_patch.dart:17:11)
``` 

</p>
</details> 

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.9 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Damilola’s iPhone (mobile) • 00008110-001964480AE1801E            • ios
      • iOS 17.0.2 21A351
    • iPhone 14 Pro (mobile)     • 6548B0D1-7674-4306-9852-198C465F1104 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 
```
[!] Flutter (Channel master, 3.17.0-5.0.pre.39, on macOS 14.0 23A344 darwin-arm64, locale en-NG)
    • Flutter version 3.17.0-5.0.pre.39 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d7bf0a8f3d (5 hours ago), 2023-11-10 01:00:32 -0500
    • Engine revision b020893cba
    • Dart version 3.3.0 (build 3.3.0-113.0.dev)
    • DevTools version 2.30.0-dev.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Damilola’s iPhone (mobile) • 00008110-001964480AE1801E            • ios            • iOS 17.0.2 21A351
    • iPhone 14 Pro (mobile)     • 6548B0D1-7674-4306-9852-198C465F1104 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by Sadoge** [comment]
Any updates on this issue? As it is still happening in 3.19.4

**Comment by MyBuzzTechnologies** [comment]
Any progress on these? Autofill has been broken for a while now, with lots of related bugs reports but nobody seems interested in fixing them. We've just had to roll back to 3.16.9 because of these issues which is real pain.

**Comment by callmephil** [comment]
It's still happening on 3.29.3

```sh
The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

TypeError: null: type 'JSNull' is not a subtype of type 'String'

    at Object.wrapException (http://localhost:53276/dwds/src/injected/client.js:1249:43)
    at Object._asString (http://localhost:53276/dwds/src/injected/client.js:2840:15)
    at main__closure7.call$1 (http://localhost:53276/dwds/src/injected/client.js:26677:54)
    at _EventStreamSubscription_closure.call$1 (http://localhost:53276/dwds/src/injected/client.js:26040:26)
    at StaticClosure._rootRunUnary (http://localhost:53276/dwds/src/injected/client.js:4382:16)
    at _CustomZone.runUnary$2$2 (http://localhost:53276/dwds/src/injected/client.js:14273:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:53276/dwds/src/injected/client.js:14220:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:53276/dwds/src/injected/client.js:14407:25)
    at _callDartFunctionFast1 (http://localhost:53276/dwds/src/injected/client.js:7680:25)
    at http://localhost:53276/dwds/src/injected/client.js:7656:18
```
