### ISSUE TITLE
[Android] Autofill from saved credentials doesn't work

### ISSUE THREAD

**Issue by TatsuUkraine** [flutter/flutter#137760]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a form with username and password field
2. Try to use password manager such as Google Password Manager
3. Ensure that password usage requires biometric auth (not sure if it changes anything)
4. Click in Key icon on keyboard and select password

### Device for testing
Google Pixel 7 pro, Android 14 (34)

### Expected results

Form prepopulates with the selected username/password combination

### Actual results

Input loses focus and nothing happens.

Form can be prepopulated only if login/password combination is selected from Keyboard quick actions and no biometric check is requested

### Code sample

<details><summary>Code sample (very simple autofillgroup with 2 inputs)</summary>

```dart
           AutofillGroup(
              child: Column(
                children: [
                  TextField(
                    autofillHints: [AutofillHints.username],
                  ),
                  TextField(
                    autofillHints: [AutofillHints.password],
                  ),
                ],
              ),
            ),
```

</details>

### Screenshots or Video

<details><summary>Video</summary>

https://github.com/flutter/flutter/assets/621542/c669e975-df2f-40cf-86a6-2b46ad15f05e

</details>

### Logs

<details><summary>Logs</summary>

```console
[+1656 ms] I/ImeTracker(29289): com.example.flutter_three_thirteen:355d8ebd: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
[        ] D/InputMethodManager(29289): showSoftInput() view=io.flutter.embedding.android.FlutterView{5267c32 VFE...... .F...... 0,0-1440,3036 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[  +21 ms] D/InputConnectionAdaptor(29289): The input method toggled cursor monitoring on
[  +43 ms] D/InsetsController(29289): show(ime(), fromIme=true)
[ +298 ms] I/ImeTracker(29289): com.example.flutter_three_thirteen:355d8ebd: onShown
[+1871 ms] D/InputConnectionAdaptor(29289): The input method toggled cursor monitoring off
[        ] W/WindowOnBackDispatcher(29289): sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@122401794 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@dd07025
[        ] I/ImeTracker(29289): com.google.android.gms:418f75e2: onCancelled at PHASE_CLIENT_ANIMATION_CANCEL
[   +9 ms] I/ImeTracker(29289): com.example.flutter_three_thirteen:f278d0eb: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
[        ] I/ImeTracker(29289): com.example.flutter_three_thirteen:f278d0eb: onFailed at PHASE_CLIENT_VIEW_SERVED

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.5.2 22G91 darwin-arm64, locale ru)
    • Flutter version 3.13.9 on channel stable at /Users/tatsu/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (8 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at ****
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = ****
    • Java binary at: ****
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (4 available)


[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by dam-ease** [comment]
Hi @TatsuUkraine. When you setup details, have you also set those up in the system "autofill service" settings and provide relevant information to the autofill service for it to work ?

**Comment by TatsuUkraine** [comment]
@dam-ease sorry, not sure that I understood the question( for this example I didn't do any native configuration for Android, basically this issue appears only when app looses focus either because of biometric auth or because you go into the password manager. If biometric auth is not requested, and you using password suggestions from the keyboard quick action - all works fine

**Comment by TatsuUkraine** [comment]
@dam-ease I already replied😅

**Comment by TatsuUkraine** [comment]
@dam-ease I added video to the description to better explain what is going on. On a video when screen goes black - it asks for biometric verification. On a video there are 3 attempts: 

1. Using Key icon to go to the password manager. 
2. Using quick action with biometric verification
3. Using quick action without biometric verification

**Comment by dam-ease** [comment]
I guess the time you replied and the time the label updated were the same. 
We can reproduce the issue when clicking on Key icon > select saved account (without needing biometric verification). We tested with a Realme 6, Android 11.
Can you confirm again if you also can see the issue when removing biometric verification or not? 

https://github.com/flutter/flutter/assets/53122008/693d98e0-19c9-400d-b567-5156fa1c2efd

**Comment by TatsuUkraine** [comment]
It seems biometric verification doesn't affect behavior a lot. If I disable biometric check for password usages only one difference is that there is no scenario 2 (from my prev comment). So it seems autofill just stops working when the app goes to background, either because of password manager bottom sheet or because of biometric check


https://github.com/flutter/flutter/assets/621542/99b4159b-558e-4d43-9556-adda78b2a5ae


Also, one note, I'm not entirely sure, since I didn't check this explicitly, but I think all was working in prev stable release

**Comment by AhmadHusein5853** [comment]
I started to notice this issue once my device got Android 14 update. on Android 13 it was working fine.

**Comment by tiltmaster** [comment]
I am also facing this issue on a S23 Ultra, after verifying biometric it does not autofill up until i have to type the same account name and select it from the dropdown menu

**Comment by tototo23** [comment]
I've got the same issue with my apps, only on Android 14. Works fine on Android 13 or less and iOS, seems that the password manager is well shown but then doesn't fill the fields _ONLY ON THE FIRST TRY. (What is weird is that if I start editing the field then the password manager is able to auto fill.)_

**Comment by tiltmaster** [comment]
> I've got the same issue with my apps, only on Android 14. Works fine on Android 13 or less and iOS, seems that the password manager is well shown but then doesn't fill the fields _ONLY ON THE FIRST TRY. (What is weird is that if I start editing the field then the password manager is able to auto fill.)_

I am facing the same for weeks, its just not capturing after verifying the biometric

**Comment by tiltmaster** [comment]
any feedback on this?

**Comment by ReelhopCTO** [comment]
On iOS once the app has called for iCloud Keychain to be displayed, next time you select the username field it loses focus whilst performing biometric check.  Hence the username and password are no longer populated from Keychain.  This behaviour persists until the app is force closed at which point you can again use Keychain with biometrics as expected.  On Android this behaviour of the TextField losing focus makes the newPassword hint unusable as the value never gets populated in the application.

**Comment by vbuberen** [comment]
I see the same issue with both the default Android Google credential manager and other password managers, like 1Password. Namely, it seems that I observe exactly the same behavior as @davidpryor mentions above.
Here is what I see in logs when trying to click `Open 1Password` and select credentials there (left comments on what happens when):

```
/// Clicked on a TextField with password
I/ImeTracker(20699): io.***.android.dev:552ae0cc: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
D/InputMethodManager(20699): showSoftInput() view=io.flutter.embedding.android.FlutterView{c99b7d1 VFE...... .F...... 0,0-1080,2337 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/AssistStructure(20699): Flattened final assist data: 584 bytes, containing 1 windows, 4 views
D/InputConnectionAdaptor(20699): The input method toggled cursor monitoring on
D/InsetsController(20699): show(ime(), fromIme=true)
I/ImeTracker(20699): io.***.android.dev:552ae0cc: onShown
D/BufferPoolAccessor2.0(20699): bufferpool2 0xb400007e87f2c648 : 5(36700160 size) total buffers - 5(36700160 size) used buffers - 273/278 (recycle/alloc) - 5/278 (fetch/transfer)
/// Clicked on `Open 1Password` from suggestions above keyboard
W/WindowOnBackDispatcher(20699): sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@240663259 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@9dab2c7
I/ImeTracker(20699): com.onepassword.android:c40ea466: onCancelled at PHASE_CLIENT_ANIMATION_CANCEL
I/ImeTracker(20699): io.***.android.dev:baa2f98a: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
I/ImeTracker(20699): io.***.android.dev:baa2f98a: onFailed at PHASE_CLIENT_VIEW_SERVED
I/FA      (20699): Application backgrounded at: timestamp_millis: 1704548949197
/// Selected credentials in 1Password
D/CompatibilityChangeReporter(21934): Compat change id reported: 78294732; UID 10234; state: ENABLED
```

In the end nothing happens when I pick credentials in 1Password or other password managers. 

Logs recorded from Pixel 7 with Android 14, but the issue happens on other devices with older Android versions as well.
Log entries are the same on both Flutter 3.13.7 and on 3.16.5

**Comment by VladPetruM** [comment]
Has anyone found an workaround to this?

**Comment by gerken-tss** [comment]
I am able to reproduce this issue on Pixel 4a. On iOS, everything works like charm. There is nothing in the logs that indicates anything related to this issue.

**Comment by PerLycke** [comment]
I want to underscore the critical nature of the autofill functionality not working as expected. This issue isn't just about convenience, it directly impacts the first impression our users have and poses significant security concerns:

First Impressions Matter: Autofill is often part of the initial interaction users have with an app. A seamless experience here is crucial for user retention and satisfaction.

Security Implications: A functional "Select strong password" feature is vital for encouraging secure password practices. As of now, while the credentials are saved to the user's password manager, the passwords aren't populated back into the app, leaving users unaware it was ever saved.

Not being able to offer a working sign up process could push users away. Given the importance of both user experience and security, I believe this issue warrants immediate attention and should be labeled a P1. Addressing it would not only align with best practices for application development but also reinforce Flutter's commitment to providing a secure and user-friendly platform.

**Comment by tototo23** [comment]
@PerLycke Thank you for this comment, same situation here. My clients and customers complain about it, as the login page is the first page, the first impression is that the app is bugged... Hopefully it can be fixed in the next release, it's more than annoying for the customers and critical for us.

**Comment by djsjr** [comment]
No update since early November? @dam-ease This should be P1. My app users can't even sign in/up!

**Comment by ReelhopCTO** [comment]
@PerLycke - We completely agree with your senitments.  We have ahd to remove Autofill capability from our flutter application which is far from ideal, but the user experience is far worse with it enabled.

**Comment by djsjr** [comment]
Developed a workaround using a combination of FocusNodes, listeners, and watching LifeCycle changes. It seems to be working for me.

1. Initialize FocusNodes and pass them to your text inputs.
2. Create a `AppLifecycleState state` variable.
3. Implement the `didChangeAppLifecycleState` method, and update `state` each time it changes.
4. Create a listener for each node, in which you `requestFocus()` if `state == AppLifecycleState.inactive`.

Example:
```
class _SignInFormState extends State<SignInForm> with WidgetsBindingObserver {
  late FocusNode passwordNode;
  late FocusNode emailNode;
  AppLifecycleState state = AppLifecycleState.resumed;

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    this.state = state;
  }

  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    passwordNode = FocusNode();
    passwordNode.addListener(() async {
      if (state == AppLifecycleState.inactive)
        passwordNode.requestFocus();

    });
    emailNode = FocusNode();
    emailNode.addListener(() async {
      if (state == AppLifecycleState.inactive) 
        emailNode.requestFocus();
    });
    super.initState();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    passwordNode.dispose();
    emailNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return 
        ...
        TextField(
            focusNode: emailNode, 
        ...
        TextField(
            focusNode: passwordNode,
        ...
    }
}
```
(Thanks to @davidpryor for mentioning forcing focus).

**Comment by tiltmaster** [comment]
> Developed a workaround using a combination of FocusNodes, listeners, and watching LifeCycle changes. It seems to be working for me.
> 
> 1. Initialize FocusNodes and pass them to your text inputs.
> 2. Create a `AppLifecycleState state` variable.
> 3. Implement the `didChangeAppLifecycleState` method, and update `state` each time it changes.
> 4. Create a listener for each node, in which you `requestFocus()` if `state == AppLifecycleState.inactive`.
> 
> Example:
> 
> ```
> class _SignInFormState extends State<SignInForm> with WidgetsBindingObserver {
>   late FocusNode passwordNode;
>   late FocusNode emailNode;
>   AppLifecycleState state = AppLifecycleState.resumed;
> 
>   @override
>   void didChangeAppLifecycleState(AppLifecycleState state) {
>     super.didChangeAppLifecycleState(state);
>     this.state = state;
>   }
> 
>   @override
>   void initState() {
>     WidgetsBinding.instance.addObserver(this);
>     passwordNode = FocusNode();
>     passwordNode.addListener(() async {
>       if (state == AppLifecycleState.inactive)
>         passwordNode.requestFocus();
> 
>     });
>     emailNode = FocusNode();
>     emailNode.addListener(() async {
>       if (state == AppLifecycleState.inactive) 
>         emailNode.requestFocus();
>     });
>     super.initState();
>   }
> 
>   @override
>   void dispose() {
>     WidgetsBinding.instance.removeObserver(this);
>     passwordNode.dispose();
>     emailNode.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return 
>         ...
>         TextField(
>             focusNode: emailNode, 
>         ...
>         TextField(
>             focusNode: passwordNode,
>         ...
>     }
> }
> ```
> 
> (Thanks to @davidpryor for mentioning forcing focus).

If i can kiss you using githubt i would so I will invoke this command:

Git Kiss @djsjr --force 

You are a true MVP i struggled for months

**Comment by VladPetruM** [comment]
> Developed a workaround using a combination of FocusNodes, listeners, and watching LifeCycle changes. It seems to be working for me.
> 
> 1. Initialize FocusNodes and pass them to your text inputs.
> 2. Create a `AppLifecycleState state` variable.
> 3. Implement the `didChangeAppLifecycleState` method, and update `state` each time it changes.
> 4. Create a listener for each node, in which you `requestFocus()` if `state == AppLifecycleState.inactive`.
> 
> Example:
> 
> ```
> class _SignInFormState extends State<SignInForm> with WidgetsBindingObserver {
>   late FocusNode passwordNode;
>   late FocusNode emailNode;
>   AppLifecycleState state = AppLifecycleState.resumed;
> 
>   @override
>   void didChangeAppLifecycleState(AppLifecycleState state) {
>     super.didChangeAppLifecycleState(state);
>     this.state = state;
>   }
> 
>   @override
>   void initState() {
>     WidgetsBinding.instance.addObserver(this);
>     passwordNode = FocusNode();
>     passwordNode.addListener(() async {
>       if (state == AppLifecycleState.inactive)
>         passwordNode.requestFocus();
> 
>     });
>     emailNode = FocusNode();
>     emailNode.addListener(() async {
>       if (state == AppLifecycleState.inactive) 
>         emailNode.requestFocus();
>     });
>     super.initState();
>   }
> 
>   @override
>   void dispose() {
>     WidgetsBinding.instance.removeObserver(this);
>     passwordNode.dispose();
>     emailNode.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return 
>         ...
>         TextField(
>             focusNode: emailNode, 
>         ...
>         TextField(
>             focusNode: passwordNode,
>         ...
>     }
> }
> ```
> 
> (Thanks to @davidpryor for mentioning forcing focus).

You are indeed amazing, thank you!

**Comment by tototo23** [comment]
Thanks a lot @djsjr !! :D
Can other developers it works ot their side?

It doesn't on mine, unfortunatly... Maybe because i use `TextFormField`, maybe for other reasons on my Widget tree, but i still have the same behaviour : the autofill doesnt fill the fields after selecting login/pwd from the manager, but after a first fail, if i type 'a' in login or password field, then delete, and click on autofill suggestion, this 2nd time it fills the fields successfully.

I still hope your workaround help most of people !

**Comment by VladPetruM** [comment]
> Thanks a lot @djsjr !! :D Can other developers confim if it works ot their side?
> 
> It doesn't on mine, unfortunatly... Maybe because i use `TextFormField`, maybe for other reasons on my Widget tree, but i still have the same behaviour : the autofill doesnt fill the fields after selecting login/pwd from the manager, but after a first fail, if i type 'a' in login or password field, then delete, and click on autofill suggestion, this 2nd time it fills the fields successfully.
> 
> I still hope your workaround help most of people !

I can try to help you. I am using Textform field and djsjr fix is working

**Comment by tototo23** [comment]
@VladPetruM @djsjr Sorry i did juste a small mistake on my side whe  saving sttae, it works well too !!!!
Thank you very much for that workaround ! It helps a lot!!!

**Comment by vbuberen** [comment]
Can also confirm that the workaround works. Thanks a lot for this! 

However, I also have a small nitpick to it - `super.initState()` should be called first in the override as mentioned in the documentation: https://github.com/flutter/flutter/blob/5187b45e4d1468c13ca9ab1795b300d876fd9453/packages/flutter/lib/src/widgets/framework.dart#L998-L999

So the `initState()` should look like this and it works fine 😉 :

```
@override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    passwordNode = FocusNode();
    passwordNode.addListener(() async {
      if (state == AppLifecycleState.inactive)
        passwordNode.requestFocus();

    });
    emailNode = FocusNode();
    emailNode.addListener(() async {
      if (state == AppLifecycleState.inactive) 
        emailNode.requestFocus();
    });
  }

**Comment by TatsuUkraine** [comment]
> Developed a workaround using a combination of FocusNodes, listeners, and watching LifeCycle changes. It seems to be working for me.
> 
> 1. Initialize FocusNodes and pass them to your text inputs.
> 2. Create a `AppLifecycleState state` variable.
> 3. Implement the `didChangeAppLifecycleState` method, and update `state` each time it changes.
> 4. Create a listener for each node, in which you `requestFocus()` if `state == AppLifecycleState.inactive`.
> 
> Example:
> 
> ```
> class _SignInFormState extends State<SignInForm> with WidgetsBindingObserver {
>   late FocusNode passwordNode;
>   late FocusNode emailNode;
>   AppLifecycleState state = AppLifecycleState.resumed;
> 
>   @override
>   void didChangeAppLifecycleState(AppLifecycleState state) {
>     super.didChangeAppLifecycleState(state);
>     this.state = state;
>   }
> 
>   @override
>   void initState() {
>     WidgetsBinding.instance.addObserver(this);
>     passwordNode = FocusNode();
>     passwordNode.addListener(() async {
>       if (state == AppLifecycleState.inactive)
>         passwordNode.requestFocus();
> 
>     });
>     emailNode = FocusNode();
>     emailNode.addListener(() async {
>       if (state == AppLifecycleState.inactive) 
>         emailNode.requestFocus();
>     });
>     super.initState();
>   }
> 
>   @override
>   void dispose() {
>     WidgetsBinding.instance.removeObserver(this);
>     passwordNode.dispose();
>     emailNode.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return 
>         ...
>         TextField(
>             focusNode: emailNode, 
>         ...
>         TextField(
>             focusNode: passwordNode,
>         ...
>     }
> }
> ```
> 
> (Thanks to @davidpryor for mentioning forcing focus).

another possible workaround (depends on what kind of form you have on the screen)
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class InactiveFocusScopeObserver extends StatefulWidget {
  final Widget child;

  const InactiveFocusScopeObserver({
    super.key,
    required this.child,
  });

  @override
  State<InactiveFocusScopeObserver> createState() => _InactiveFocusScopeObserverState();
}

class _InactiveFocusScopeObserverState extends State<InactiveFocusScopeObserver> {
  final FocusScopeNode _focusScope = FocusScopeNode();

  AppLifecycleListener? _listener;
  FocusNode? _lastFocusedNode;

  @override
  void initState() {
    _registerListener();

    super.initState();
  }

  @override
  Widget build(BuildContext context) => FocusScope(
    node: _focusScope,
    child: widget.child,
  );

  @override
  void dispose() {
    _listener?.dispose();
    _focusScope.dispose();

    super.dispose();
  }

  void _registerListener() {
    /// optional if you want this workaround for any platform and not just for android
    if (defaultTargetPlatform != TargetPlatform.android) {
      return;
    }

    _listener = AppLifecycleListener(
      onInactive: () {
        _lastFocusedNode = _focusScope.focusedChild;
      },
      onResume: () {
        _lastFocusedNode = null;
      },
    );

    _focusScope.addListener(_onFocusChanged);
  }

  void _onFocusChanged() {
    if (_lastFocusedNode?.hasFocus == false) {
      _lastFocusedNode?.requestFocus();
      _lastFocusedNode = null;
    }
  }
}
```
so it can be used with any number of fields that may potentially suffer from this bug
```dart
InactiveFocusScopeObserver(
  child: FormWithTheFeildsThatMayLooseFocus(),
)
```

**Comment by rsiva229** [comment]
The workaround mentioned in this thread works fine for android. But I haven't been able to get iOS to work. The save password prompt doesn't show up. Does any one here have a working solution for iOS? Please share.

**Comment by zigapovhe** [comment]
Our clients reported exactly the same issue, but we can replicate it even without having biometric auth enabled for autofill. Using inline autofill (via keyboard), try to not directly autofill credentials, but via IME, open autofill app, and try autofilling from there. 

It indeed looks like the issue is lost focus. We replicated that on Google Password Manager and on Bitwarden everytime.

**Comment by LongCatIsLooong** [comment]
I can't reproduce the issue with biometric authentication on: 

https://github.com/flutter/flutter/assets/31859944/0e0e19f1-c00a-4d79-92fd-2576cd011b40

**Comment by LongCatIsLooong** [comment]
Additional note: 

https://github.com/flutter/flutter/blob/6826fc08faaa157d449dbc4cd57160b97e3f411e/packages/flutter/lib/src/widgets/focus_manager.dart#L1524-L1533

It doesn't seem that moving the app to the background affects the in-app focus on Android (at least not in the framework).

**Comment by adonisRodxander** [comment]
@LongCatIsLooong In which version of flutter did you test it? I am testing it on version **3.19.6,** and **I can reproduce the issue**, in my case it happens with Samsung Account on a physical device, using biometric authentication, it does not autocomplete the textfields (email and password).

**Comment by adonisRodxander** [comment]
UPDATE: On version **3.22.0** works fine

**Comment by LongCatIsLooong** [comment]
Looks like the first bad commit is https://github.com/flutter/flutter/commit/04e284a49dc9169bb9f4ec02dd005eabe0227b7c. The issue went away when the commit was reverted.

**Comment by catalunha** [comment]
The error still happens in flutter 3.22. Touching the textField triggers this error.

catalunha@pop-os:~/heetoo/biblingo_mobile$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on Pop!_OS 22.04 LTS 6.8.0-76060800daily20240311-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
![image](https://github.com/flutter/flutter/assets/19995819/406fa7db-32ab-4f98-b619-a2e1ed329fdf)

**Comment by gnprice** [comment]
@catalunha That stack trace appears to be on web, and the issue above was specific to Android. Please file it as its own issue, answering all the questions in the new-issue template, and then it can be investigated.

**Comment by gnprice** [comment]
> Looks like the first bad commit is [04e284a](https://github.com/flutter/flutter/commit/04e284a49dc9169bb9f4ec02dd005eabe0227b7c). The issue went away when the commit was reverted.

To unpack this a bit:
Commit 04e284a49 was an engine roll, pulling in flutter/engine@c97a0deccbc1.

That engine commit was reverted in flutter/engine@500ae6c4d947879da2a879d8b2f1a4e7f4b41432.

That revert rolled into flutter/flutter in commit d35c08e9cf134eca78d1eab2a316fe0ce5a074c2, which was part of Flutter 3.22.0 but not 3.19.6 (the previous release).

**Comment by udaychandra** [comment]
We're facing the same issue with password autofill.

Using Flutter 3.22.1

**Comment by TatsuUkraine** [comment]
All works fine for me on Android after update to 3.22.1. Fields aren't loosing focus during biometric verification in password manager

**Comment by TatsuUkraine** [comment]
@LongCatIsLooong I don't know why bot reopened the issue, sorry 😅

**Comment by AristideVB** [comment]
> @LongCatIsLooong I don't know why bot reopened the issue, sorry 😅

Might be a sign ! 😄 On Android Username is not saved to Google Password Manager for me, only suggested password

_While on iOS existing password autofill does not fill the fields anymore (but I will investigate and open an issue)_

**Comment by zigapovhe** [comment]
Jup, works for me on android, but I still have the same old issues on iOS build

**Comment by alarkirikal** [comment]
We are still running the exact same issue on iOS running Flutter 3.22.2. I noticed that after returning to the app, the username/password fields are unfocused. As soon as I manually tap on them to regain focus, the autofill values from the password manager (1Password in my case) are entered correctly. Thus this feels like the issue as explained above, where the fields losing focus on the app being sent to the background being the issue.

**Comment by TatsuUkraine** [comment]
@alarkirikal There is an ongoing issue for iOS autofill.
https://github.com/flutter/flutter/issues/148475

Based on discussion looks like it's a patch candidate

**Comment by alarkirikal** [comment]
> @alarkirikal There is an ongoing issue for iOS autofill. #148475
> 
> Based on discussion looks like it will be fixed in the next stable release

Just a bit later found that issue as well - wasn't that obvious to find at first glance due to its Closed status. But thank you for confirming.

**Comment by AnnaPS** [comment]
Hi, is there any update on this? I can reproduce the issue using the example code on Flutter version 3.24.3. I tried the workaround and it works perfectly (android), but I also see some people saying that on version 3.22.1 it works now, but not for me (I also tried with this specific version). Thanks

**Comment by Anfet** [comment]
Google Password Manager autofill generates this error on password save:
`2025-01-15 19:08:51.600 12950-12950 ChromesyncPasswordDataS com.google.android.gms.persistent    E  Saving or updating passwords failed [CONTEXT service_id=177 ]
                                                                                                    java.lang.IllegalArgumentException: Comparison method violates its general contract!
                                                                                                    	at java.util.TimSort.mergeLo(TimSort.java:781)
                                                                                                    	at java.util.TimSort.mergeAt(TimSort.java:518)
                                                                                                    	at java.util.TimSort.mergeCollapse(TimSort.java:448)
                                                                                                    	at java.util.TimSort.sort(TimSort.java:245)
                                                                                                    	at java.util.Arrays.sort(Arrays.java:1351)
                                                                                                    	at fcou.R(:com.google.android.gms@245034029@24.50.34 (190400-713002902):12)
                                                                                                    	at fcos.n(:com.google.android.gms@245034029@24.50.34 (190400-713002902):7)
                                                                                                    	at admk.b(:com.google.android.gms@245034029@24.50.34 (190400-713002902):77)
                                                                                                    	at dagger.producers.internal.AbstractProducesMethodProducer.a(:com.google.android.gms@245034029@24.50.34 (190400-713002902):6)
                                                                                                    	at fhse.d(:com.google.android.gms@245034029@24.50.34 (190400-713002902):3)
                                                                                                    	at fhsg.run(:com.google.android.gms@245034029@24.50.34 (190400-713002902):38)
                                                                                                    	at apvb.c(:com.google.android.gms@245034029@24.50.34 (190400-713002902):50)
                                                                                                    	at apvb.run(:com.google.android.gms@245034029@24.50.34 (190400-713002902):76)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at aqam.run(:com.google.android.gms@245034029@24.50.34 (190400-713002902):8)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

**Comment by pogorv12** [comment]
Hi! I have the same issue on the web app.

**Comment by tototo23** [comment]
> Hi! I have the same issue on the web app.

Hi, are you using Windows Hello to protect the credentials on Chrome ?
If yes, it is probably the same issue i created here : https://github.com/flutter/flutter/issues/162066

**Comment by pogorv12** [comment]
> > Hi! I have the same issue on the web app.
> 
> Hi, are you using Windows Hello to protect the credentials on Chrome ? If yes, it is probably the same issue i created here : [#162066](https://github.com/flutter/flutter/issues/162066)

No. I don't. 

Actually my comment is related to password manager in chrome on Android that has exactly the same behaviour as described in the ticket description.

Chrome for desktop, safary on iphone works as expected.

**Comment by MichaelBoublil** [comment]
Hello, I have a similar issue, where when I use Google Password Manager it generates the password but doesn't fill the inputs.
Then, it asks me if I want to save it in my password manager, but again nothing really gets saved.

In the logs I find this line that matches the moment the password is generated

```
I/AutofillManager(29152): onAuthenticationResult(): empty intent
```

My flutter doctor:

```
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.3.1 24D70 darwin-arm64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 16.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.100.0)
[✓] Connected device (4 available)
[✓] Network resources
```

**Comment by igorgbp** [comment]
@MichaelBoublil any update on this?

**Comment by michaelboublil** [comment]
Hi @igorgbp,

It works now, but I've actually seen the main difference that makes it works:

- When the Google Password Manager uses the package name (e.g.: `com.domain.app`) it works well ✅ 
- When the Google Password Manager uses an identified domain name that belongs to me and where you can find my `assetlinks.json` linked to my package name it doesn't work ❌ 

The only thing is, I don't know what makes the Google Password Manager choose one or the other. So as far as I know tomorrow it could again stop working

**Comment by BenBaggley** [comment]
Is there any update on this issue? 
I'm still seeing this happen in Flutter 3.44.0. Whichever field is focused when autofill starts, does not get filled after choosing a credential the first time.
If the credential has been chosen once during the same session, it works on subsequent autofills.
