### ISSUE TITLE
Failed assertion

### ISSUE THREAD

**Issue by vicichaudhary** [flutter/flutter#137884]
![Screenshot_1](https://github.com/flutter/flutter/assets/75554925/bb427c04-a8cb-43cd-abbd-ccac547c38af)
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

```
The relevant error-causing widget was: 
  GetMaterialApp GetMaterialApp:file:///C:/Users/Admin/AndroidStudioProjects/documenttemplate/lib/main.dart:29:70
When the exception was thrown, this was the stack: 
#2      new StatefulElement (package:flutter/src/widgets/framework.dart:5185:12)
#3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:776:38)
...     Normal element mounting (287 frames)
#290    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#291    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#292    Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#293    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6153:32)
#294    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595:17)
#295    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#296    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#297    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#298    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#299    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#300    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#301    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#302    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#303    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#304    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#305    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#306    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#307    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#308    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#309    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#310    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#311    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#312    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#313    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#314    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#315    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#316    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#317    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#318    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#319    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#320    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#321    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#322    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#323    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#324    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#325    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#326    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#327    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#328    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#329    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#330    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#331    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#332    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#333    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#334    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#335    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#336    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#337    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#338    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#339    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#340    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#341    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#342    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#343    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#344    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#345    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#346    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#347    _invoke (dart:ui/hooks.dart:142:13)
#348    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#349    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
```

**Comment by darshankawar** [comment]
@vicichaudhary 
Although the log says to file this as an issue, but we also need a complete runnable but reproducible code sample that shows the error, so please provide one in order to make the issue actionable along with `flutter doctor -v`.
