### ISSUE TITLE
Build Process Failed  Windows

### ISSUE THREAD

**Issue by RaiFernandesdosSantos** [flutter/flutter#137882]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I created an app with `flutter create`, after that I tried running it with `flutter run` and choose windows, but the build failed

### Actual results

Tried the solution of other similar issues, but it don`t resolve

This is the messagem from the failed build :

```console
Launching lib\main.dart on Windows in debug mode...
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: o build personalizado para 'C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\CMakeFiles\076bb69fd8ee3768e1e74db9a5f78652\flutter_windows.dll.rule;C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\CMakeFiles\d711ad149578f398145eec4f400bea68\flutter_assemble.rule' foi encerrado com o c�digo 1. [C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...                                     3,5s
Exception: Build process failed.
```

### Logs

<details>
<summary>Logs</summary>

```console

`[  +88 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +35 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] Skipping pub get: version match.
[ +164 ms] Generating C:\Users\Usuário\Desktop\programacao\flutter\erp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +78 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\Users\Usuário\Desktop\programacao\flutter\erp\.dart_tool\package_config_subset}
[  +16 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib\main.dart on Windows in debug mode...
[   +1 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/0545f8705df301877d787107bac1a6e9fc9ee1ad/ --output-dill
C:\Users\USURIO~2\AppData\Local\Temp\flutter_tools.60e1e6c3\flutter_tool.4323a654\app.dill --packages C:\Users\Usuário\Desktop\programacao\flutter\erp\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\93cae48154605b2b23f957321f3fac0a.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +28 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +25 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.VCTools   
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +25 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.VCTools Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "8c45ab0c",
               "installDate": "2023-09-30T12:44:31Z",
               "installationName": "VisualStudio/17.7.4+34031.279",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools",
               "installationVersion": "17.7.34031.279",
               "productId": "Microsoft.VisualStudio.Product.BuildTools",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\LaunchDevCmd.bat",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Ferramentas de Build do Visual Studio 2022",
               "description": "As Ferramentas de Build do Visual Studio permitem que você compile aplicativos nativos e gerenciados com base no MSBuild sem precisar do IDE do Visual Studio. Há  
               opções para instalar as bibliotecas e os compiladores do Visual C++, MFC, ATL e suporte C++/CLI.",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelId": "VisualStudio.17.Release",
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.7#17.7.4",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2023-09-30T12:44:31.43508Z",
               "catalog": {
                 "buildBranch": "d17.7",
                 "buildVersion": "17.7.34031.279",
                 "id": "VisualStudio/17.7.4+34031.279",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.7.4",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "4",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "17.7.4+34031.279",
                 "requiredEngineVersion": "3.7.2181.36443"
               },
               "properties": {
                 "campaignId": "2030:519a5475181a484a9fbd58e915eaea3a",
                 "channelManifestId": "VisualStudio.17.Release/17.7.4+34031.279",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +3 ms] Building Windows application...
[  +10 ms] <- compile package:erp/main.dart
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
C:\Users\Usuário\Desktop\programacao\flutter\erp\windows -B build\windows -G Visual Studio 17 2022
[  +90 ms] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
[ +105 ms] -- Configuring done (0.1s)
[ +254 ms] -- Generating done (0.2s)
[  +19 ms] -- Build files have been written to: C:/Users/Usuário/Desktop/programacao/flutter/erp/build/windows
[   +6 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build build\windows --config Debug
--target INSTALL --verbose
[ +126 ms] Vers�o do MSBuild 17.7.2+d6990bcfa para .NET Framework
[  +39 ms] Compila��o de 04/11/2023 00:28:31 iniciada.
[ +141 ms] Projeto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\INSTALL.vcxproj" no n� 1 (destinos padr�o).
[        ] O projeto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\INSTALL.vcxproj" (1) est� compilando
"C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\ZERO_CHECK.vcxproj" (2) no n� 1 (destinos padr�o).
[   +1 ms] InitializeBuildStatus:
[        ]   Criando "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
[        ]   Tocando "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[  +10 ms] CustomBuild:
[        ]   Todas as sa�das est�o atualizadas.
[  +20 ms] FinalizeBuildStatus:
[        ]   Excluindo o arquivo "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[        ]   Tocando "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
[        ] Projeto de compila��o pronto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\ZERO_CHECK.vcxproj" (destinos padr�o).
[  +45 ms] O projeto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\INSTALL.vcxproj" (1) est� compilando
"C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\ALL_BUILD.vcxproj" (3) no n� 1 (destinos padr�o).
[        ] O projeto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\ALL_BUILD.vcxproj" (3) est� compilando
"C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\runner\erp.vcxproj" (4) no n� 1 (destinos padr�o).
[        ] O projeto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\runner\erp.vcxproj" (4) est� compilando
"C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\flutter\flutter_assemble.vcxproj" (5) no n� 1 (destinos padr�o).
[        ] InitializeBuildStatus:
[        ]   Tocando "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
[   +3 ms] CustomBuild:
[        ]   "O build de 'C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\CMakeFiles\d711ad149578f398145eec4f400bea68\flutter_assemble.rule' depende de
'C:\USERS\USU�RIO\DESKTOP\PROGRAMACAO\FLUTTER\ERP\WINDOWS\FLUTTER\EPHEMERAL\FLUTTER_WINDOWS.DLL', que � gerado pelo build de
'C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\CMakeFiles\076bb69fd8ee3768e1e74db9a5f78652\flutter_windows.dll.rule'. Os itens n�o podem ser compilados em paralelo."
[  +57 ms]   Generating C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/flutter_windows.dll,
C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/flutter_export.h, C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/flutter_windows.h,        
C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/flutter_messenger.h,
C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/flutter_plugin_registrar.h,
C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/flutter_texture_registrar.h,
C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/cpp_client_wrapper/core_implementations.cc,
C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/cpp_client_wrapper/standard_codec.cc,
C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/cpp_client_wrapper/plugin_registrar.cc,
C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/cpp_client_wrapper/flutter_engine.cc,
C:/Users/Usu�rio/Desktop/programacao/flutter/erp/windows/flutter/ephemeral/cpp_client_wrapper/flutter_view_controller.cc, _phony_
[ +396 ms]   [  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ]   [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms]   [  +57 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ]   [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +18 ms]   [  +20 ms] Initializing file store
[  +13 ms]   [  +13 ms] Done initializing file store
[  +49 ms]   [  +49 ms] Skipping target: gen_localizations
[   +9 ms]   [   +9 ms] Skipping target: gen_dart_plugin_registrant
[+2112 ms]   [+2112 ms] Skipping target: unpack_windows
[ +245 ms]   [ +245 ms] Skipping target: kernel_snapshot
[   +1 ms]   [   +2 ms] debug_bundle_windows_assets: Starting due to {}
[ +147 ms]   [ +146 ms] shaderc command: [C:\src\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --sksl, --iplr,
--sl=C:\Users\Usuário\Desktop\programacao\flutter\erp\build\flutter_assets\shaders/ink_sparkle.frag,
--spirv=C:\Users\Usuário\Desktop\programacao\flutter\erp\build\flutter_assets\shaders/ink_sparkle.frag.spirv, --input=C:\src\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag,  
--input-type=frag, --include=C:\src\flutter\packages\flutter\lib\src\material\shaders, --include=C:\src\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib]
[ +231 ms]   [ +231 ms] Could not write file to C:\Users\Usuário\Desktop\programacao\flutter\erp\build\flutter_assets\shaders/ink_sparkle.frag.spirv
[        ]   [   +1 ms] Persisting file store
[   +4 ms]   [   +5 ms] Done persisting file store
[   +6 ms]   [   +6 ms] Target debug_bundle_windows_assets failed: ShaderCompilerException: Shader compilation of "C:\src\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag" to  
"C:\Users\Usuário\Desktop\programacao\flutter\erp\build\flutter_assets\shaders/ink_sparkle.frag" failed with exit code 1.
[        ]              impellerc stdout:
[        ]              impellerc stderr:
[        ]              Could not write file to C:\Users\Usuário\Desktop\programacao\flutter\erp\build\flutter_assets\shaders/ink_sparkle.frag.spirv
[        ]              #0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:200:9)
[        ]              <asynchronous suspension>
[        ]              #1      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:134:25)
[        ]              <asynchronous suspension>
[        ]              #2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
[        ]              <asynchronous suspension>
[        ]              #3      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:106:3)
[        ]              <asynchronous suspension>
[        ]              #4      BundleWindowsAssets.build (package:flutter_tools/src/build_system/targets/windows.dart:138:29)
[        ]              <asynchronous suspension>
[        ]              #5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
[        ]              <asynchronous suspension>
[        ]              #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
[        ]              <asynchronous suspension>
[        ]              #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:32)
[        ]              <asynchronous suspension>
[        ]              #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
[        ]              <asynchronous suspension>
[        ]              #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]              <asynchronous suspension>
[        ]              #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
[        ]              <asynchronous suspension>
[        ]              #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
[        ]              <asynchronous suspension>
[        ]              #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
[        ]              <asynchronous suspension>
[        ]              #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #16     main (package:flutter_tools/executable.dart:90:3)
[        ]              <asynchronous suspension>
[        ]   [   +5 ms] "flutter assemble" took 2.914ms.
[   +2 ms]   [   +3 ms]
[        ]              #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]              #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:332:7)
[        ]              <asynchronous suspension>
[        ]              #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
[        ]              <asynchronous suspension>
[        ]              #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]              <asynchronous suspension>
[        ]              #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
[        ]              <asynchronous suspension>
[        ]              #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
[        ]              <asynchronous suspension>
[        ]              #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
[        ]              <asynchronous suspension>
[        ]              #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #10     main (package:flutter_tools/executable.dart:90:3)
[        ]              <asynchronous suspension>
[ +156 ms]   [ +159 ms] ensureAnalyticsSent: 153ms
[        ]   [        ] Running 0 shutdown hooks
[        ]   [        ] Shutdown hooks complete
[        ]   [        ] exiting with code 1
[  +31 ms] C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: o build personalizado para
'C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\CMakeFiles\076bb69fd8ee3768e1e74db9a5f78652\flutter_windows.dll.rule;C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\window
s\CMakeFiles\d711ad149578f398145eec4f400bea68\flutter_assemble.rule' foi encerrado com o c�digo 1.
[C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\flutter\flutter_assemble.vcxproj]
[   +4 ms] Projeto de compila��o pronto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\flutter\flutter_assemble.vcxproj" (destinos padr�o) -- FALHA.
[        ] Projeto de compila��o pronto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\runner\erp.vcxproj" (destinos padr�o) -- FALHA.
[  +38 ms] Projeto de compila��o pronto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\ALL_BUILD.vcxproj" (destinos padr�o) -- FALHA.
[        ] Projeto de compila��o pronto "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\INSTALL.vcxproj" (destinos padr�o) -- FALHA.
[   +1 ms] FALHA da compila��o.
[   +3 ms] "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\INSTALL.vcxproj" (destino padr�o) (1) ->
[        ] "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\ALL_BUILD.vcxproj" (destino padr�o) (3) ->
[        ] "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\runner\erp.vcxproj" (destino padr�o) (4) ->
[        ] "C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\flutter\flutter_assemble.vcxproj" (destino padr�o) (5) ->
[        ] (CustomBuild destino) ->
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: o build personalizado para
'C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\CMakeFiles\076bb69fd8ee3768e1e74db9a5f78652\flutter_windows.dll.rule;C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\window
s\CMakeFiles\d711ad149578f398145eec4f400bea68\flutter_assemble.rule' foi encerrado com o c�digo 1.
[C:\Users\Usu�rio\Desktop\programacao\flutter\erp\build\windows\flutter\flutter_assemble.vcxproj]
[        ]     0 Aviso(s)
[        ]     1 Erro(s)
[        ] Tempo Decorrido 00:00:03.82
[  +13 ms] Building Windows application... (completed in 4,5s)
[ +398 ms] Exception: Build process failed.
[   +2 ms] "flutter run" took 5.375ms.
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +74 ms] ensureAnalyticsSent: 70ms
[        ] Running 1 shutdown hook
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1`

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

`[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [versÆo 10.0.22631.2506], locale pt-BR)
    • Flutter version 3.13.9 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (9 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Ferramentas de Build do Visual Studio 2022 17.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Ferramentas de Build do Visual Studio 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.84.0)
    • VS Code at C:\Users\Usuário\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22631.2506]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 118.0.2088.69

[√] Network resources
    • All expected network resources are available.

• No issues found!`

```

</details>

**Comment by huycozy** [comment]
Hi @RaiFernandesdosSantos 
I noticed this from your verbose log:

>[   +6 ms]   [   +6 ms] Target debug_bundle_windows_assets failed: ShaderCompilerException: Shader compilation of "C:\src\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag" to  
"C:\Users\Usuário\Desktop\programacao\flutter\erp\build\flutter_assets\shaders/ink_sparkle.frag" failed with exit code 1.
[        ]              impellerc stdout:
[        ]              impellerc stderr:
[        ]              Could not write file to C:\Users\Usuário\Desktop\programacao\flutter\erp\build\flutter_assets\shaders/ink_sparkle.frag.spirv

Can you check if you enabled [Current system locale beta: UTF-8 Support](https://helpcenter.nshift.com/hc/article_attachments/360017209459/mceclip0.png)?

Also, the project path contains `Usuário` that could be related. Could you retry on a directory path that contains English alphabet only?

**Comment by RaiFernandesdosSantos** [comment]
Thank you, I changed the user`s folder and now it worked
