### ISSUE TITLE
ExpansionTile Failed assertion: line 49 pos 12: '_state != null': is not true. 

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [flutter/flutter#137831]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Start project

I can prevent the error if I wrap the trailing Widget with a `Builder`, but I'm not sure if it is intended.

### Expected results

The value of `controller.isExpanded` should be the same as the `initialValue` of the `ExpansionTile`.

### Actual results

Receiving this error.
```
The following assertion was thrown building MyApp(dirty, state: _MyAppState#7db30):
'package:flutter/src/material/expansion_tile.dart': Failed assertion: line 49 pos 12: '_state != null': is not true.

The relevant error-causing widget was: 
  MyApp MyApp:file:///Users/huynh/StudioProjects/app/lib/main.dart:4:16
When the exception was thrown, this was the stack: 
#2      ExpansionTileController.isExpanded (package:flutter/src/material/expansion_tile.dart:49:12)
#3      _MyAppState.build (package:app/main.dart:26:29)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
#9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#13     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:952:7)
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _controller = ExpansionTileController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ExpansionTile(
            controller: _controller,
            title: Text('Title'),
            trailing: Icon(
                _controller.isExpanded ? Icons.expand_less : Icons.expand_more),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-x64, locale de-DE)
    • Flutter version 3.13.9 on channel stable at /Users/huynh/.asdf/installs/flutter/3.13.9-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (vor 9 Tagen), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/huynh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/huynh/Library/Android/sdk
    • Java binary at: /Users/huynh/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10811636/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/huynh/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10811636/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/huynh/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10671973/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.4)
    • IntelliJ at /Users/huynh/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.1.4
    • Dart plugin version 232.10072.19

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.4)
    • IntelliJ at /Users/huynh/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.10203.10/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Users/huynh/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.10072.27/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (5 available)
    • 2203129G (mobile)                  • adb-723c1722-1XNpMz._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • Android SDK built for x86 (mobile) • emulator-5554                              • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 15 (mobile)                 • DB01FF6A-DA97-4FF9-9268-4B0FE07D2FFE       • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                    • macos                                      • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)                       • chrome                                     • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the sample code provided above. 

I can confirm that using the builder, the assertion is not thrown. 

Labeling for further insight from the team. 


<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.13.9 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (9 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.0.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.1 21B74
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1 21B74
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```


```
[✓] Flutter (Channel master, 3.16.0-23.0.pre.32, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.16.0-23.0.pre.32 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef8deb5d69 (8 hours ago), 2023-11-03 01:11:39 -0400
    • Engine revision 78e8475ddb
    • Dart version 3.3.0 (build 3.3.0-91.0.dev)
    • DevTools version 2.29.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.0.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.1 21B74
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1 21B74
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by Am607** [comment]
Got the same issue in flutter version 3.10.6 at stable branch

**Comment by TahaTesser** [comment]
Using `ExpansionTileController` to control `ExpansionTile` using `Builder` to access it from build context  is documented with a complete example.

https://api.flutter.dev/flutter/material/ExpansionTile-class.html#material.ExpansionTile.2


You can also use `onExpansionChanged` callback to update the expanded state for the trailing widget.  This is consistent with other widgets that have changed callback.

```dart
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool isExpanded = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ExpansionTile(
            onExpansionChanged: (bool expanded) {
              setState(() {
                isExpanded = expanded;
              });
            },
            title: Text('Title'),
            trailing: Builder(builder: (context) {
              return Icon(isExpanded ? Icons.expand_less : Icons.expand_more);
            }),
          ),
        ),
      ),
    );
  }
}

```

**Comment by TahaTesser** [comment]
cc: @fischerscode 
Given  expected behavior using `ExpansionTileController`  and it being documented very well and we can use `onExpansionChanged` to update the state for trailing widget without `Builder` as designed.

I'm not sure if we need move expansion state.

**Comment by quoc-huynh-cosee** [comment]
Hi @TahaTesser ,

What's the purpose of `_controller.isExpanded`, if I cannot use it directly here? I think it is not intuitv to wrap it in a `Builder`.
Also your solution requires a `StatefulWidget` to hold the expansion state. Shouldn't this be the job of the controller and not the surrounding widget (in this case)? The controller should be the "source of truth". We could omit the `StatefullWidget` from your solution if we could read the `_controller.isExpanded`  without a `Builder`.

Another point is, that other controllers, e.g. `TextEditingController`,  we can also set the initial value with the controller and can access it directly. It seems inconsistence that the `ExpansionTileController` doesn't support it.

**Comment by fischerscode** [comment]
When I browsed through the open issues, I didn't feel like the current behavior was intuitive.
For me, the controller should control the behavior and not delegate the task to an other (maybe unavailable) component. That's why I moved the expansion state to the controller.

However, I am also fine with the current behavior. But, if it is decided to be an adequate implementation, I think this issue should be closed.

*(cc: @TahaTesser)*

**Comment by TahaTesser** [comment]
> Hi @TahaTesser ,
> 
> What's the purpose of `_controller.isExpanded`, if I cannot use it directly here? I think it is not intuitv to wrap it in a `Builder`. 

it returns the expanded state in a appropriate build context. Same way you can't call `ScaffoldMessenger` to show snack bar in the context as `Scaffold`. The widget calling `ScaffoldMessenger.of(context)` needs to be a `Scaffold` child to access the scaffold context aka `Scaffold` should be an ancestor to call this.

https://master-api.flutter.dev/flutter/material/ScaffoldMessenger/of.html

`ExpansionTileController` also doing the same here. It needs to be a child of the `ExpansionTile` in the widget tree. Easiest way you can do that wrapping `Builder` widget.  You could also use `StatefulBuilder` when you don't want to use `StatefulWidget`.
This is done so each `ExpansionTile` manage owns controller and you don't need to manually dispose these controllers.  When the `ExpansionTile` is off stage or out of the view bounds, it will dispose these internal controllers automatically.

I believe this solves the issue you've reported. If you wish to propose a change. please do a file a proposal with the reasons.

**Comment by quoc-huynh-cosee** [comment]
Alright, I'll open a new issue for that request.
