### ISSUE TITLE
Running bin/tasks/module_test.dart locally

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#137950]
I am trying to figure out what the requirements are to get `bin/tasks/module_test.dart` running locally.

Flutter doctor is happy, but the test is failing.

cc @reidbaker Am I holding this test wrong?

```
$ cd /Users/dacoharkes/flt/engine/flutter/dev/devicelab && dart bin/test_runner.dart test -t module_test

[...]

[2023-11-06 18:02:14.948225] [STDOUT] stderr: * What went wrong:
[2023-11-06 18:02:14.948232] [STDOUT] stderr: Execution failed for task ':app:processDebugMainManifest'.
[2023-11-06 18:02:14.948240] [STDOUT] stderr: > Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @3c6376ff
[2023-11-06 18:02:14.948248] [STDOUT] stderr: 
[2023-11-06 18:02:14.948255] [STDOUT] stderr: * Try:
[2023-11-06 18:02:14.948261] [STDOUT] stderr: > Run with --stacktrace option to get the stack trace.
[2023-11-06 18:02:14.948287] [STDOUT] stderr: > Run with --info or --debug option to get more log output.
[2023-11-06 18:02:14.948296] [STDOUT] stderr: > Run with --scan to get full insights.
[2023-11-06 18:02:14.948302] [STDOUT] stderr: 
[2023-11-06 18:02:14.948309] [STDOUT] stderr: * Get more help at https://help.gradle.org
[2023-11-06 18:02:14.948316] [STDOUT] stdout: 
[2023-11-06 18:02:14.948322] [STDOUT] stdout: Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[2023-11-06 18:02:14.948329] [STDOUT] stdout: 
[2023-11-06 18:02:14.948336] [STDOUT] stdout: You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[2023-11-06 18:02:14.948343] [STDOUT] stdout: 
[2023-11-06 18:02:14.948352] [STDOUT] stdout: See https://docs.gradle.org/7.6.1/userguide/command_line_interface.html#sec:command_line_warnings
[2023-11-06 18:02:14.948369] [STDOUT] stderr: 
[2023-11-06 18:02:14.948376] [STDOUT] stderr: BUILD FAILED in 5s
[2023-11-06 18:02:14.948393] [STDOUT] stdout: 27 actionable tasks: 27 executed
[2023-11-06 18:02:15.742930] [STDOUT] Checking for reboot
[module_test] Process terminated with exit code 0.
Task result:
{
  "success": false,
  "reason": "Executable \"./gradlew\" failed with exit code 1."
}


════════════════════╡ ••• Finished task "module_test" ••• ╞═════════════════════



═══════════════════╡ ••• Flaky status for "module_test" ••• ╞═══════════════════

Consistently failed across all 3 executions.
flaky: false
```

[full log in gist](https://gist.github.com/dcharkes/0990b48b7f06cac03b8afc345b310573)

I updated my Android Studio and the Android SDK today to be able to test properly with Android SDK 34.

```
$ flutter doctor -v
[!] Flutter (Channel [user-branch], 3.17.0-1.0.pre.66, on macOS 14.1 23B74 darwin-arm64, locale en)
    ! Flutter version 3.17.0-1.0.pre.66 on channel [user-branch] at /Users/dacoharkes/flt/engine/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    • Upstream repository git@github.com:flutter/flutter
    • Framework revision b66f533fae (6 hours ago), 2023-11-06 12:40:35 +0100
    • Engine revision 555ffa17b5
    • Dart version 3.3.0 (build 3.3.0-97.0.dev)
    • DevTools version 2.29.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dacoharkes/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/dacoharkes/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/dacoharkes/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • Daco’s iPhone (mobile)      • 00008110-001410883A78401E • ios            • iOS 17.1 21B74
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 14.1 23B74 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

Not sure if this is relevant, but I had to update Android Studio to get a newer JDK. The new Android studio has OpenJDK 17 instead of 11.

```
$ /Applications/Android\ Studio.app/Contents/jbr/Contents/Home/bin/java --version
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
OpenJDK 64-Bit Server VM (build 17.0.6+0-17.0.6b829.9-10027231, mixed mode)
```

The old Android studio JDK 11 had issues running the newest command-line tools:

```
$ flutter doctor --android-licenses
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Android sdkmanager tool was found, but failed to run
(/Users/dacoharkes/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
```

The OpenJDK 11 can only run command-line tools 10, not 11.

**Comment by dcharkes** [comment]
With Android Studio 2021.3 Dolphin including openJDK 11 the `Build debug host APK` step completes, but the test fails in a later step:

```
[2023-11-06 19:09:54.707588] [STDOUT] ══════════════════════╡ ••• Check files in debug APK ••• ╞══════════════════════
[2023-11-06 19:09:54.707610] [STDOUT] 
[2023-11-06 19:09:54.710124] [STDOUT] Executing "/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java -Dcom.android.sdklib.toolsdir=/Users/dacoharkes/Library/Android/sdk/tools -classpath .:/Users/dacoharkes/Library/Android/sdk/tools/lib/* com.android.tools.apk.analyzer.ApkAnalyzerCli files list /var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/flutter_module_test.OMbdC8/hello_host_app/app/build/outputs/apk/debug/app-debug.apk" in "/Users/dacoharkes/flt/engine/flutter/dev/devicelab" with environment {BOT: true, LANG: en_US.UTF-8}
[2023-11-06 19:09:54.884687] [STDOUT] stderr: Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
[2023-11-06 19:09:54.884746] [STDOUT] stderr:   at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
[2023-11-06 19:09:54.884758] [STDOUT] stderr:   at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
[2023-11-06 19:09:54.884768] [STDOUT] stderr:   at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
[2023-11-06 19:09:54.884778] [STDOUT] stderr:   at com.android.tools.apk.analyzer.ApkAnalyzerCli.getAaptInvokerFromSdk(ApkAnalyzerCli.java:277)
[2023-11-06 19:09:54.884787] [STDOUT] stderr:   at com.android.tools.apk.analyzer.ApkAnalyzerCli.main(ApkAnalyzerCli.java:129)
[2023-11-06 19:09:54.884812] [STDOUT] stderr: Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
[2023-11-06 19:09:54.884826] [STDOUT] stderr:   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
[2023-11-06 19:09:54.884836] [STDOUT] stderr:   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[2023-11-06 19:09:54.884845] [STDOUT] stderr:   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[2023-11-06 19:09:54.884854] [STDOUT] stderr:   ... 5 more
[2023-11-06 19:09:55.373668] [STDOUT] Checking for reboot
[module_test] Process terminated with exit code 0.
```

[full log gist](https://gist.github.com/dcharkes/afca8dc10a20c863a0844def1e825bd8)

**Comment by dcharkes** [comment]
Investigating the apkanalyzer error a bit more.

The error can be reproduced with a commandline invocation of `apkanalyzer`:

```
$ /Users/dacoharkes/Library/Android/sdk/tools/bin/apkanalyzer 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
```

It's part of the Android SDK Tools (Obsolete).

<img width="621" alt="image" src="https://github.com/flutter/flutter/assets/3601775/720e2e56-b99a-47dd-bd5b-e31fd66ed27c">

Uninstalling these leads to a different failure locally in the devicelab test:

```
[2023-11-06 20:57:00.607201] [STDOUT] ══════════════════════╡ ••• Check files in debug APK ••• ╞══════════════════════
[2023-11-06 20:57:00.607233] [STDOUT] 
[2023-11-06 20:57:00.609708] [STDOUT] Executing "/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java -Dcom.android.sdklib.toolsdir=/Users/dacoharkes/Library/Android/sdk/tools -classpath .:/Users/dacoharkes/Library/Android/sdk/tools/lib/* com.android.tools.apk.analyzer.ApkAnalyzerCli files list /var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/flutter_module_test.5An1AB/hello_host_app/app/build/outputs/apk/debug/app-debug.apk" in "/Users/dacoharkes/flt/engine/flutter/dev/devicelab" with environment {BOT: true, LANG: en_US.UTF-8}
[2023-11-06 20:57:00.710186] [STDOUT] stderr: Error: Could not find or load main class com.android.tools.apk.analyzer.ApkAnalyzerCli
[2023-11-06 20:57:00.710240] [STDOUT] stderr: Caused by: java.lang.ClassNotFoundException: com.android.tools.apk.analyzer.ApkAnalyzerCli
[2023-11-06 20:57:01.204121] [STDOUT] Checking for reboot
[module_test] Process terminated with exit code 0.
```

Diving a bit more into the apkanalyzer in our CIPD package: we have two:

```
dacoharkes-macbookpro2:example dacoharkes$ ~/Downloads/all-mac-arm64/sdk/cmdline-tools/latest/bin/apkanalyzer 
Subject must be one of: apk, files, manifest, dex, resources

apk summary              Prints the application Id, version code and version name.
apk file-size            Prints the file size of the APK.                         
apk download-size        Prints an estimate of the download size of the APK.      
apk features             Prints features used by the APK.                         
apk compare              Compares the sizes of two APKs.                          
files list               Lists all files in the zip.                              
files cat                Prints the given file contents to stdout                 
manifest print           Prints the manifest in XML format                        
manifest application-id  Prints the application id.                               
manifest version-name    Prints the version name.                                 
manifest version-code    Prints the version code.                                 
manifest min-sdk         Prints the minimum sdk.                                  
manifest target-sdk      Prints the target sdk                                    
manifest permissions     Prints a list of used permissions                        
manifest debuggable      Prints if the app is debuggable                          
dex list                 Prints a list of dex files in the APK                    
dex references           Prints number of references in dex files                 
dex packages             Prints the class tree from DEX.                          
                         P,C,M,F: indicates packages, classes methods, fields     
                         x,k,r,d: indicates removed, kept, referenced and defined 
                           nodes                                                  
dex code                 Prints the bytecode of a class or method in smali format 
dex reference-tree       Prints a reference tree to a given or a list of          
                           classes/methods/fields.                                
resources packages       Prints a list of packages in resources table             
resources configs        Prints a list of configurations for a type               
resources value          Prints the given resource's value                        
resources names          Prints a list of resource names for a type               
resources xml            Prints the human readable form of a binary XML           

Usage:
apkanalyzer [global options] <subject> <verb> [options] <apk> [<apk2>]

Option            Description                         
------            -----------                         
--human-readable  Print sizes in human readable format
dacoharkes-macbookpro2:example dacoharkes$ ~/Downloads/all-mac-arm64/sdk/tools/bin/apkanalyzer 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.tools.apk.analyzer.ApkAnalyzerCli.getAaptInvokerFromSdk(ApkAnalyzerCli.java:277)
	at com.android.tools.apk.analyzer.ApkAnalyzerCli.main(ApkAnalyzerCli.java:129)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more
```

The error message feels like we're invoking the old one.

This would align with the `tools/` folder being obsolete.

Our code tries to invoke the new commandline tools indeed, and then falls back to the old apkanalyzer:
https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/apk_utils.dart#L115-L158

Downloading [the SDK/NDK CIPD package](https://chrome-infra-packages.appspot.com/p/flutter/android/sdk/all/mac-arm64/+/SCC5dhGdwZKgsz8crR95kieryrc6sq_NAz-JrOhQm3cC) and using that instead of something installed from Android Studio makes the test succeed locally. (Which unblocks me.)

**Comment by dcharkes** [comment]
And now using Android Studio to updating everything to the newest versions also still makes the test pass locally.

My hypothesis is that I somehow had gotten a corrupted /Users/dacoharkes/Library/Android/sdk. Closing issue.

**Comment by dcharkes** [comment]
Updating everything with Android Studio 2022.3 Giraffe broke things again, because the test is then trying to use Java 17 again.

So, for this specific test we're only compatible to Android Studio 2021.3 Dolphin, due to the Java being selected from Android studio.

**Comment by reidbaker** [comment]
You can override the version of java used with a config variable I believe.
