### ISSUE TITLE
[tool_crash] UnimplementedError: UnimplementedError: The preview device is not supported with local engine builds

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#137982]
## command

flutter run --local-engine-src-path=Z:\home\xubaolin\engine\src --local-engine=android_debug_unopt_arm64 --local-engine-host=host_debug_unopt

## exception

UnimplementedError: UnimplementedError: The preview device is not supported with local engine builds

```
#0      CachedLocalEngineArtifacts.getArtifactPath (package:flutter_tools/src/artifacts.dart:1031:9)
#1      PreviewDeviceDiscovery.devices (package:flutter_tools/src/preview_device.dart:68:60)
#2      DeviceManager.getAllDevices (package:flutter_tools/src/device.dart:213:20)
#3      DeviceManager.getDevices (package:flutter_tools/src/device.dart:194:14)
#4      DeviceBasedDevelopmentArtifacts.requiredArtifacts (package:flutter_tools/src/runner/flutter_command.dart:1855:63)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1656:43)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:349:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[33m[!][39m Flutter (Channel [user-branch], 3.16.0-20.0.pre.9, on Microsoft Windows [Version 10.0.19044.3324], locale zh-CN)
    [33m![39m Flutter version 3.16.0-20.0.pre.9 on channel [user-branch] at D:\Code\flutter\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    [32m•[39m Upstream repository git@github.com:flutter/flutter.git
    [32m•[39m Framework revision 13c049b42c (7 days ago), 2023-10-31 02:53:11 -0400
    [32m•[39m Engine revision b4de734eb7
    [32m•[39m Dart version 3.3.0 (build 3.3.0-80.0.dev)
    [32m•[39m DevTools version 2.28.1
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at D:\Users\80256643\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.7.34221.43
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[32m[✓][39m VS Code (version 1.84.0)
    [32m•[39m VS Code at D:\Users\80256643\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.76.0

[31m[☠][39m Connected device (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    [31m✗[39m UnimplementedError: The preview device is not supported with local engine builds
    [32m•[39m #0      CachedLocalEngineArtifacts.getArtifactPath (package:flutter_tools/src/artifacts.dart:1031:9)
      #1      PreviewDeviceDiscovery.devices (package:flutter_tools/src/preview_device.dart:68:60)
      #2      PreviewDeviceDiscovery.discoverDevices (package:flutter_tools/src/preview_device.dart:98:12)
      #3      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:232:20)
      #4      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:733:55)
      #5      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:266:72)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1399:13)
      #8      _CustomZone.run (dart:async/zone.dart:1301:19)
      #9      _runZoned (dart:async/zone.dart:1804:10)
      #10     runZonedGuarded (dart:async/zone.dart:1792:12)
      #11     runZoned (dart:async/zone.dart:1744:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:258:9)
      #14     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:786:60)
      #15     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
      #16     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:790:53)
      #17     DoctorText.text (package:flutter_tools/src/doctor.dart:782:36)
      #18     DoctorText.text (package:flutter_tools/src/doctor.dart)
      #19     _createLocalCrashReport (package:flutter_tools/runner.dart:257:51)
      #20     _handleToolError (package:flutter_tools/runner.dart:219:31)
      <asynchronous suspension>
      #21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #22     main (package:flutter_tools/executable.dart:90:3)
      <asynchronous suspension>


[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

**Comment by xu-baolin** [comment]
@AlexV525

**Comment by christopherfujino** [comment]
@xu-baolin whoops, this is my fault, lemme take a look
