### ISSUE TITLE
Dialogs fail when shown from "single page" apps

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13795]
## Steps to Reproduce

1. Create app with the following in `main.dart`:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  MyAppState createState() => new MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Test app'),
        ),
        body: new Center(
          child: new RaisedButton(
            child: new Text('Click me'),
            onPressed: () {
              showDialog(
                context: context,
                child: new AlertDialog(
                  title: new Text("My dialog"),
                  content: new Text("Hi from dialog"),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

```

2. Run it, and click the button

=>

```
I/flutter ( 1170): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 1170): The following assertion was thrown while handling a gesture:
I/flutter ( 1170): Navigator operation requested with a context that does not include a Navigator.
I/flutter ( 1170): The context used to push or pop routes from the Navigator must be that of a widget that is a
I/flutter ( 1170): descendant of a Navigator widget.
I/flutter ( 1170):
```

**Comment by mit-mit** [comment]
I feel like there is something very basic I'm missing here?

**Comment by fractalemagic** [comment]
Should be due to the same issue as described in the documentation for `Scaffold.of`

```
  /// When the [Scaffold] is actually created in the same `build` function, the
  /// `context` argument to the `build` function can't be used to find the
  /// [Scaffold] (since it's "above" the widget being returned). In such cases,
  /// the following technique with a [Builder] can be used to provide a new
  /// scope with a [BuildContext] that is "under" the [Scaffold]:
```

The `Navigator` is built by `MaterialApp` / `WidgetsApp` i.e. in the same `build` function, so it can't be found. If you wrap the `RaisedButton` in a `Builder` then the dialog shows up fine.

**Comment by mit-mit** [comment]
Ah, yes, confirmed that this small refactoring makes it work:

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      new MaterialApp(
        home: new Scaffold(
          appBar: new AppBar(
            title: new Text('Test app'),
          ),
          body: new MyHome(),
        ),
      ),
    );

class MyHome extends StatefulWidget {
  const MyHome({Key key}) : super(key: key);

  @override
  MyHomeState createState() => new MyHomeState();
}

class MyHomeState extends State<MyHome> {
  @override
  Widget build(BuildContext context) {
    return new Center(
      child: new RaisedButton(
        child: new Text('Click me'),
        onPressed: () {
          showDialog(
            context: context,
            child: new AlertDialog(
              title: new Text("My dialog"),
              content: new Text("Hi from dialog"),
            ),
          );
        },
      ),
    );
  }
}
```

I wonder if we could better detect the original case, and provide a more informative error?

**Comment by Hixie** [comment]
What would have been more informative? Knowing what the problem is, the text of the original message does describe it precisely. Not knowing what it is, the error message doesn't help much, but it's not clear to me what we could say instead...

**Comment by mit-mit** [comment]
Does the asset know that the scaffold was created in the same build method? If so, would be great to mention that being the issue specifically.

**Comment by Hixie** [comment]
you mean does the showDialog method know that it is being called from a closure that has a `context` to an element whose widget's build method is the one that built the MaterialApp that then indirectly built the Navigator?

If so, then the answer is not really.

**Comment by branflake2267** [comment]
I think I'm getting the same issue. 

General Layout
FirebaseAnimatedList > ListTile > onTap > showDialog

When I click on show dialog it is displayed, but when I try to pop it throws this exception.

```
 ] I/flutter (32665): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[   +4 ms] W/zygote  (32665): Attempt to remove non-JNI local reference, dumping thread
[  +12 ms] I/chatty  (32665): uid=10083(u0_a83) com.wrightwaycs.economy identical 1 line
[        ] W/zygote  (32665): Attempt to remove non-JNI local reference, dumping thread
[        ] I/flutter (32665): The following assertion was thrown while handling a gesture:
[        ] I/flutter (32665): Looking up a deactivated widget's ancestor is unsafe.
[        ] I/flutter (32665): At this point the state of the widget's element tree is no longer stable. To safely refer to a
[        ] I/flutter (32665): widget's ancestor in its dispose() method, save a reference to the ancestor by calling
[        ] I/flutter (32665): inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
[  +13 ms] I/flutter (32665): 
[        ] I/flutter (32665): When the exception was thrown, this was the stack:
[   +3 ms] I/flutter (32665): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3181:9)
[   +6 ms] I/flutter (32665): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3190:6)
[        ] I/flutter (32665): #2      Element.ancestorStateOfType (package:flutter/src/widgets/framework.dart:3232:12)
[        ] I/flutter (32665): #3      Navigator.of (package:flutter/src/widgets/navigator.dart:722:19)
[        ] I/flutter (32665): #4      allowInviteDialog.<anonymous closure> (package:economy/main.dart:417:23)
[        ] I/flutter (32665): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
[        ] I/flutter (32665): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
[        ] I/flutter (32665): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[        ] I/flutter (32665): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
[        ] I/flutter (32665): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
[        ] I/flutter (32665): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
[        ] I/flutter (32665): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
[        ] I/flutter (32665): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
[        ] I/flutter (32665): #13     BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
[        ] I/flutter (32665): #14     BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
[        ] I/flutter (32665): #15     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
[        ] W/zygote  (32665): Attempt to remove non-JNI local reference, dumping thread
[        ] I/flutter (32665): #16     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
[        ] I/flutter (32665): #17     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
[        ] I/flutter (32665): #18     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:134)
[        ] I/flutter (32665): #19     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
[        ] I/flutter (32665): 
[        ] I/flutter (32665): Handler: onTap
[        ] I/flutter (32665): Recognizer:
[        ] I/flutter (32665):   TapGestureRecognizer#1d033(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
[        ] I/flutter (32665):   Offset(125.1, 393.7), sent tap down)
[        ] I/flutter (32665): ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +1 ms] W/zygote  (32665): Attempt to remove non-JNI local reference, dumping thread
```

```
// called from the list tile on tap
Future<Null> allowInviteDialog(BuildContext context, String inviteCode,
    String userName, String asUserName) async {

  bool selected = await showDialog<bool>(
    context: context,
    child: new SimpleDialog(
      title: new Text(
          "$userName has accepted invite to sign in as $asUserName. Allow them to sign in?"),
      children: <Widget>[
        new SimpleDialogOption(
          child: const Text('Yes, I approve'),
          onPressed: () {
            // ~~~ broken!!!
            Navigator.of(context).pop(true);
          },
        ),
        new SizedBox(height: 15.0,),
        new SimpleDialogOption(
          child: const Text("No, I don't approve"),
          onPressed: () {
            // ~~~ broken!!!
            Navigator.of(context).pop(false);
          },
        ),
      ],
    ),
  );

  // ...
  }
}
```

**Comment by Hixie** [comment]
@mit-mit Any suggestions on what change we could make that would address your concern?

**Comment by mit-mit** [comment]
Sorry, I don't know this well enough to suggest any concrete changes
