### ISSUE TITLE
[animation] OpenContainer An error occurred when using Navigator.pop to return with parameters

### ISSUE THREAD

**Issue by Int-0X7FFFFFFF** [flutter/flutter#137926]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. https://github.com/Int-0X7FFFFFFF/container_transform_test
2. Using this prepared example,
3. First click FloatingActionButton to go to the next page
4. Click the 123 button on the next page to return to the previous page and carry the parameters

### Expected results

onClosed is triggered and prints out 123

### Actual results

════════ Exception caught by gesture ═══════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'String' is not a subtype of type 'Null' of 'result'

### Code sample

<details><summary>Code sample</summary>

```dart
[class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
        appBar: AppBar(
          // TRY THIS: Try changing the color here to a specific color (to
          // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
          // change color while the other colors stay the same.
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text(widget.title),
        ),
        body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: Column(
            // Column is also a layout widget. It takes a list of children and
            // arranges them vertically. By default, it sizes itself to fit its
            // children horizontally, and tries to be as tall as its parent.
            //
            // Column has various properties to control how it sizes itself and
            // how it positions its children. Here we use mainAxisAlignment to
            // center the children vertically; the main axis here is the vertical
            // axis because Columns are vertical (the cross axis would be
            // horizontal).
            //
            // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
            // action in the IDE, or press "p" in the console), to see the
            // wireframe for each widget.
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
            ],
          ),
        ),
        floatingActionButton: OpenContainer(
          closedBuilder: (context, action) {
            return FloatingActionButton(
              onPressed: () {
                _incrementCounter();
                action();
              },
              tooltip: 'Increment',
              child: const Icon(Icons.add),
            );
          },
          openBuilder: (context, action) {
            return const NextPage();
          },
          onClosed: (data) {
            print(data);
          },
        ) // This trailing comma makes auto-formatting nicer for build methods.
        );
  }
}

class NextPage extends StatefulWidget {
  const NextPage({super.key});

  @override
  State<NextPage> createState() => _NextPageState();
}

class _NextPageState extends State<NextPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: ElevatedButton(
            onPressed: () {
              Navigator.pop(context, "123");
            },
            child: const Text("123")),
      ),
    );
  }
}
]
```

</details>
https://github.com/Int-0X7FFFFFFF/container_transform_test

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[════════ Exception caught by gesture ═══════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'String' is not a subtype of type 'Null' of 'result'

When the exception was thrown, this was the stack
#0      _OpenContainerRoute.didPop (package:animations/src/open_container.dart)
open_container.dart:1
#1      _RouteEntry.handlePop
navigator.dart:2978
#2      NavigatorState._flushHistoryUpdates
navigator.dart:3977
#3      NavigatorState.pop
navigator.dart:5003
#4      Navigator.pop
navigator.dart:2515
#5      _NextPageState.build.<anonymous closure>
main.dart:156
#6      _InkResponseState.handleTap
ink_well.dart:1154
#7      GestureRecognizer.invokeCallback
recognizer.dart:275
#8      TapGestureRecognizer.handleTapUp
tap.dart:654
#9      BaseTapGestureRecognizer._checkUp
tap.dart:311
#10     BaseTapGestureRecognizer.handlePrimaryPointer
tap.dart:244
#11     PrimaryPointerGestureRecognizer.handleEvent
recognizer.dart:630
#12     PointerRouter._dispatch
pointer_router.dart:98
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
pointer_router.dart:143
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#15     PointerRouter._dispatchEventToRoutes
pointer_router.dart:141
#16     PointerRouter.route
pointer_router.dart:127
#17     GestureBinding.handleEvent
binding.dart:465
#18     GestureBinding.dispatchEvent
binding.dart:445
#19     RendererBinding.dispatchEvent
binding.dart:331
#20     GestureBinding._handlePointerEventImmediately
binding.dart:400
#21     GestureBinding.handlePointerEvent
binding.dart:363
#22     GestureBinding._flushPointerEventQueue
binding.dart:320
#23     GestureBinding._handlePointerDataPacket
binding.dart:293
#24     _invoke1 (dart:ui/hooks.dart:158:13)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#a3918
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(209.9, 475.8)
    finalLocalPosition: Offset(40.7, 22.1)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[[flutter] flutter doctor -v
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [版本 10.0.19045.3570], locale zh-CN)
    • Flutter version 3.10.5 on channel stable at D:\software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\software\adnroidSDK\
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = D:\software\adnroidSDK
    • Java binary at: D:\software\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at D:\software\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [版本 10.0.19045.3570]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 118.0.5993.120
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 118.0.2088.76

[√] Network resources
    • All expected network resources are available.
```

Also animations: ^2.0.8
</details>

**Comment by dam-ease** [comment]
Hi @Int-0X7FFFFFFF. Thanks for filing this. I see you are on an older version of flutter, can you please upgrade to the latest versions to see if this issue still persists?

**Comment by Int-0X7FFFFFFF** [comment]
I ran flutter upgrade and now my version information is as follows. The problem has not been solved. The error message is still the same as before.

```[flutter] flutter upgrade
Flutter is already up to date on channel stable
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (12 days ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
exit code 0
```

```[flutter] flutter doctor -v
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [版本 10.0.19045.3570], locale zh-CN)
    • Flutter version 3.13.9 on channel stable at D:\software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
```


````══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'String' is not a subtype of type 'Null' of 'result'

When the exception was thrown, this was the stack:
#0      _OpenContainerRoute.didPop (package:animations/src/open_container.dart:621:18)
open_container.dart:621
#1      _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:2974:16)
navigator.dart:2974
#2      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4039:22)
navigator.dart:4039
#3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5055:7)
navigator.dart:5055
#4      Navigator.pop (package:flutter/src/widgets/navigator.dart:2507:27)
navigator.dart:2507
#5      _NextPageState.build.<anonymous closure> (package:container_transform_test/main.dart:156:25)
main.dart:156
#6      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
ink_well.dart:1154
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
recognizer.dart:275
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
tap.dart:654
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
tap.dart:311
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)
tap.dart:244
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
recognizer.dart:630
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
pointer_router.dart:98
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
pointer_router.dart:143
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
compact_hash.dart:625
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
pointer_router.dart:141
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
pointer_router.dart:127
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
binding.dart:488
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
binding.dart:468
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
binding.dart:333
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
binding.dart:413
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
binding.dart:376
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
binding.dart:323
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
binding.dart:292
#24     _invoke1 (dart:ui/hooks.dart:186:13)
hooks.dart:186
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
platform_dispatcher.dart:424
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
hooks.dart:119

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#3c039
`════════════════════════════════════════════════════════════════════════════════════════════════════```

The row number reporting the error is no longer the first row. This should help us identify the problem.

**Comment by dam-ease** [comment]
Thanks for your response @Int-0X7FFFFFFF. I can reproduce this in the latest versions of flutter as well.
This seems to be related to https://github.com/flutter/flutter/issues/75905 but the existing issue described a behaviour with `WillPopScope`.

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel master, 3.17.0-1.0.pre.60, on macOS 14.0 23A344 darwin-arm64, locale en-NG)
    • Flutter version 3.17.0-1.0.pre.60 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `flutter` on your path resolves to /Users/damilolaalimi/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6007b91a37 (8 minutes ago), 2023-11-07 02:43:32 -0500
    • Engine revision 7f4d56a7f4
    • Dart version 3.3.0 (build 3.3.0-102.0.dev)
    • DevTools version 2.30.0-dev.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios            • iOS 17.0.2 21A351
    • iPhone 15 Pro Max (mobile)  • 56A225C9-B8F6-4201-A0AE-8C3CFA4CE152 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 119.0.6045.105

[!] Network resources
    ✗ A network error occurred while checking "https://github.com/": Operation timed out

! Doctor found issues in 3 categories.
``` 
```
[!] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.9 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.0.2 21A351
    • iPhone 15 Pro Max (mobile)  • 56A225C9-B8F6-4201-A0AE-8C3CFA4CE152 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
``` 

</p>
</details>

**Comment by Int-0X7FFFFFFF** [comment]
> Thanks for your response @Int-0X7FFFFFFF. I can reproduce this in the latest versions of flutter as well. This seems to be related to #75905 but the existing issue described a behaviour with `WillPopScope`.
> 
> stable, master flutter doctor -v

I created a new PR in the hope of fixing this problem
https://github.com/flutter/packages/pull/5342

**Comment by goderbauer** [comment]
This is not an issue with the package, but with the code that is using it. When using the OpenContainer widget with a return value, you need to specify the type of that return value when instantiating the OpenContainer widget (see also the [documentation](https://pub.dev/documentation/animations/latest/animations/OpenContainer-class.html)). 

So, you need to change this line:

https://github.com/Int-0X7FFFFFFF/container_transform_test/blob/adb196b4d109020c39c659e1d543e7e92e007323/lib/main.dart#L119

to:

```dart
        floatingActionButton: OpenContainer<String>(
```

(Note the addition of `<String>`). That will resolve the problem.
