### ISSUE TITLE
Only fullscreen activities can request orientation.

### ISSUE THREAD

**Issue by Ilya-Vys** [flutter/flutter#138081]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. On app initialization call SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

### Expected results

Have no exception

### Actual results

Sometimes there is a PlatformException

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/services.dart';

    void main() async => {
          WidgetsFlutterBinding.ensureInitialized();
          await SystemChrome.setPreferredOrientations(
              [DeviceOrientation.portraitUp],
          ); 
          runApp(MainApp());
        };
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(error, Only fullscreen activities can request orientation, null, java.lang.IllegalStateException: Only fullscreen activities can request orientation at android.os.Parcel.readException(Parcel.java:1975) at android.os.Parcel.readException(Parcel.java:1913) at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:6206) at android.app.Activity.setRequestedOrientation(Activity.java:5840) at io.flutter.plugin.platform.c.y(Unknown Source:2) at io.flutter.plugin.platform.c.b(Unknown Source:0) at io.flutter.plugin.platform.c$a.i(Unknown Source:2) at io.flutter.embedding.engine.systemchannels.i$a.onMethodCall(PlatformChannel.java:48) at le.k$a.a(MethodChannel.java:2) at zd.c.l(DartMessenger.java:2) at zd.c.m(DartMessenger.java:3) at zd.c.i(Unknown Source:0) at zd.b.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:789) at android.os.Handler.dispatchMessage(Handler.java:98) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6944) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) )
JSONMethodCodec.decodeEnvelope (message_codecs.dart:181)

SystemChrome.setPreferredOrientations (system_chrome.dart:380)
ScreenOrientationFeature.initialize (app_initializable_features.dart:221)
InitializableEntitiesHandler.handleEntities.<fn> (initializable_entities_handler.dart:33)
Future.wait.<fn> (dart:async)
InitializableEntitiesHandler.handleEntities (initializable_entities_handler.dart:25)
InitializationBloc._onPreformInitialization (initialization_bloc.dart:124)
Bloc.on.<fn>.handleEvent (bloc.dart:229)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.0.1 22A400 darwin-arm64, locale en-RU)
    • Flutter version 3.13.9 on channel stable at /Users/ilavysockij/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ilavysockij/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @Ilya-Vys. Thanks for filing this issue. From the logs, this doesn't seem to be an issue with Flutter itself. I see an issue related to this being tracked here https://issuetracker.google.com/issues/68454482 and has been reported fixed in newer Android versions, if you can still reproduce the issue in earlier versions, you might want to file an issue there. 
Closing this as it's not an issue with flutter, if you disagree please comment and I'll reopen this.
Thank you!

**Comment by mozochek** [comment]
Hi @dam-ease, this issue looks like an issue of flutter engine, because flutter engine did not process this case correctly. This is known bug with orientation for android 8, when I call `SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])` it shouldn't complete with error because of engine that did not handle this android bug.
