### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Niepoprawna funkcja., errno = 1

### ISSUE THREAD

**Issue by DariuszBaraniewicz** [flutter/flutter#138138]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Niepoprawna funkcja.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:355:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.19044.2130], locale pl-PL)
    [32m•[39m Flutter version 3.10.4 on channel stable at C:\Flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 682aa387cf (5 months ago), 2023-06-05 18:04:56 -0500
    [32m•[39m Engine revision 2a3401c9bb
    [32m•[39m Dart version 3.0.3
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    [32m•[39m Android SDK at C:\Users\ProBOOK\AppData\Local\Android\sdk
    [32m•[39m Platform android-33, build-tools 33.0.1
    [32m•[39m Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.4.33205.214
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[33m[!][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m VS Code (version 1.84.1)
    [32m•[39m VS Code at C:\Users\ProBOOK\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.76.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m SM G525F (mobile) • R58W11LF6ER • android-arm64  • Android 13 (API 33)
    [32m•[39m Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.2130]
    [32m•[39m Chrome (web)      • chrome      • web-javascript • Google Chrome 119.0.6045.105
    [32m•[39m Edge (web)        • edge        • web-javascript • Microsoft Edge 119.0.2151.44

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 682aa387cfe4fbd71ccd5418b2c2a075729a1c66
### Plugins
flutter_inappwebview-5.8.0
permission_handler-11.0.1
permission_handler_android-11.1.0
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3

**Comment by dam-ease** [comment]
Thanks for filing this @DaroVRI. I see this has been fixed in newer versions, can you upgrade to the latest versions to confirm this issue no longer persists?
