### ISSUE TITLE
ArgumentError: Invalid argument(s): No host specified in URI

### ISSUE THREAD

**Issue by zarub2k** [flutter/flutter#13821]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color packages get

## exception

```
ArgumentError: Invalid argument(s): No host specified in URI flutter_infra/flutter/fonts/13ac995daa9dda0a6ba0a45f1fccc541e616a74c/fonts.zip

#0      _HttpClient._openUrl (dart:io/http_impl.dart:1788)
#1      _HttpClient.getUrl (dart:io/http_impl.dart:1723)
#2      _attempt (package:flutter_tools/src/base/net.dart:40)
<asynchronous suspension>
#3      fetchUrl (package:flutter_tools/src/base/net.dart:22)
<asynchronous suspension>
#4      _downloadFile (package:flutter_tools/src/cache.dart:428)
<asynchronous suspension>
#5      _downloadZipArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:435)
<asynchronous suspension>
#6      _withTemporaryFile (package:flutter_tools/src/cache.dart:456)
<asynchronous suspension>
#7      _downloadZipArchive (package:flutter_tools/src/cache.dart:434)
#8      MaterialFonts.updateInner (package:flutter_tools/src/cache.dart:265)
#9      CachedArtifact.update (package:flutter_tools/src/cache.dart:247)
<asynchronous suspension>
#10     Cache.updateAll (package:flutter_tools/src/cache.dart:220)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:242)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:222)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#19     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     runZoned (dart:async/zone.dart:1467)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#28     main (file:///Users/tham/softwares/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-IN, channel alpha)
    • Flutter at /Users/tham/softwares/flutter
    • Framework revision 8f65fec5f5 (3 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d4cfecb1065d322d3670df7e9ec9a0cc2d4b90f0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/tham/Library/Android/sdk
    • Android NDK location not configured (this optional configuration is useful for native profiling support)
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at http://brew.sh/.

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3.2)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.4127.31

[✓] Connected devices
    • iPhone X • C6AF25EA-13FD-4845-B7B6-86056580ABB4 • ios • iOS 11.2 (simulator)

```

**Comment by tangkunyin** [comment]
@zarub2k 
![image](https://user-images.githubusercontent.com/4197468/42440789-4d7867bc-8399-11e8-9bfc-924b8b625c4c.png)

It works for me when set that above

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by vishweshsoni** [comment]
got same Issue can u guide @zoechi
