### ISSUE TITLE
[tool_crash] FileSystemException: readInto failed, OS Error: Operation timed out, errno = 60

### ISSUE THREAD

**Issue by nguyentin082** [flutter/flutter#138281]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readInto failed, OS Error: Operation timed out, errno = 60
```
#0      _RandomAccessFile.readIntoSync (dart:io/file_impl.dart:834:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:593:35)
#2      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#4      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#5      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#6      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#7      VsCode._getVersionFromPackageJson (package:flutter_tools/src/vscode/vscode.dart:292:64)
#8      new VsCode.fromDirectory (package:flutter_tools/src/vscode/vscode.dart:68:35)
#9      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:272:28)
#10     VsCode._installedMacOS (package:flutter_tools/src/vscode/vscode.dart:136:12)
#11     VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:94:14)
#12     VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:20:10)
#13     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:119:26)
#14     Doctor.validators (package:flutter_tools/src/doctor.dart:237:47)
#15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:243:45)
#16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:378:72)
#17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:48)
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1616:12)
<asynchronous suspension>
#19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#21     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
```
```
encountered exception: FileSystemException: readInto failed, path = '/Users/snit/Library/CloudStorage/GoogleDrive-nguyentin082@gmail.com/My Drive/DOWNLOAD FOLDER/Visual Studio Code.app/Contents/resources/app/package.json' (OS Error: Operation timed out, errno = 60)

#0      _RandomAccessFile.readIntoSync (dart:io/file_impl.dart:834:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:593:35)
#2      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#4      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#5      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#6      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#7      VsCode._getVersionFromPackageJson (package:flutter_tools/src/vscode/vscode.dart:292:64)
#8      new VsCode.fromDirectory (package:flutter_tools/src/vscode/vscode.dart:68:35)
#9      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:272:28)
#10     VsCode._installedMacOS (package:flutter_tools/src/vscode/vscode.dart:136:12)
#11     VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:94:14)
#12     VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:20:10)
#13     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:119:26)
#14     Doctor.validators (package:flutter_tools/src/doctor.dart:237:47)
#15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:243:45)
#16     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:741:60)
#17     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
#18     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:745:53)
#19     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart:738:47)
#20     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart)
#21     CrashReporter.informUser (package:flutter_tools/src/reporting/crash_reporting.dart:92:32)
#22     _handleToolError (package:flutter_tools/runner.dart:220:36)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by huycozy** [comment]
Hi @nguyentin082 
Looking at the Visual Studio Code path, it's on a cloud sync directory. What is your VS Code version? Can you open a standalone instance? (Opening it directly). 

If you install VS Code to Applications as usual, will the issue persists?

**Comment by huycozy** [comment]
Hi @nguyentin082 
Looking at the Visual Studio Code path, it's on a cloud sync directory. What is your VS Code version? Can you open a standalone instance? (Opening it directly). 

If you install VS Code to Applications as usual, will the issue persist?
