### ISSUE TITLE
Engine failing to roll to the framework on failure in Linux web_benchmarks_html

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#138326]
Starting with the roll in https://github.com/flutter/flutter/pull/138284, the test `Linux web_benchmarks_html` is failing in presubmit.

That roll contains only the Dart SDK roll https://github.com/flutter/engine/pull/47945, which contains the commits https://dart.googlesource.com/sdk.git/+log/370145bbbd4f..a03a7b62eb4e.

There are several dart2js commits in that range from @osa1 and @biggs0125.

The exception thrown from dart2js is:
```
[2023-11-10 22:17:05.429326] [STDOUT] stderr: Uncaught exception in diagnostic handler: RangeError (offset): Invalid value: Not in inclusive range 0..1: 8312
[2023-11-10 22:17:05.429377] [STDOUT] stderr: #0      RangeError.checkValueInInterval (dart:core/errors.dart:313:7)
[2023-11-10 22:17:05.429418] [STDOUT] stderr: #1      Source.getLocation (package:kernel/ast.dart:14940:16)
[2023-11-10 22:17:05.429457] [STDOUT] stderr: #2      SourceFile.getLocationMessage (package:compiler/src/io/source_file.dart:113:50)
[2023-11-10 22:17:05.429500] [STDOUT] stderr: #3      FormattingDiagnosticHandler.report (package:compiler/src/source_file_provider.dart:277:20)
[2023-11-10 22:17:05.429552] [STDOUT] stderr: #4      Compiler.callUserHandler.<anonymous closure> (package:compiler/src/compiler.dart:819:17)
[2023-11-10 22:17:05.429600] [STDOUT] stderr: #5      CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
[2023-11-10 22:17:05.429638] [STDOUT] stderr: #6      Compiler.callUserHandler (package:compiler/src/compiler.dart:818:23)
[2023-11-10 22:17:05.429680] [STDOUT] stderr: #7      Compiler._reportDiagnosticMessage (package:compiler/src/compiler.dart:810:7)
[2023-11-10 22:17:05.429719] [STDOUT] stderr: #8      Compiler.reportDiagnostic (package:compiler/src/compiler.dart:791:5)
[2023-11-10 22:17:05.429755] [STDOUT] stderr: #9      DiagnosticReporter._reportDiagnostic (package:compiler/src/diagnostics/diagnostic_listener.dart:134:15)
[2023-11-10 22:17:05.429794] [STDOUT] stderr: #10     DiagnosticReporter._reportDiagnosticInternal (package:compiler/src/diagnostics/diagnostic_listener.dart:129:5)
[2023-11-10 22:17:05.429830] [STDOUT] stderr: #11     DiagnosticReporter.reportHint (package:compiler/src/diagnostics/diagnostic_listener.dart:78:5)
[2023-11-10 22:17:05.429914] [STDOUT] stderr: #12     DiagnosticReporter.reportHintMessage (package:compiler/src/diagnostics/diagnostic_listener.dart:83:5)
[2023-11-10 22:17:05.429969] [STDOUT] stderr: #13     NoSuchMethodData.emitDiagnostic.<anonymous closure> (package:compiler/src/js_backend/no_such_method_registry.dart:260:18)
[2023-11-10 22:17:05.430018] [STDOUT] stderr: #14     SetBase.forEach (dart:collection/set.dart:143:30)
[2023-11-10 22:17:05.430060] [STDOUT] stderr: #15     NoSuchMethodData.emitDiagnostic (package:compiler/src/js_backend/no_such_method_registry.dart:258:28)
[2023-11-10 22:17:05.430100] [STDOUT] stderr: #16     JsBackendStrategy.assembleProgram (package:compiler/src/js_model/js_strategy.dart:370:34)
[2023-11-10 22:17:05.430321] [STDOUT] stderr: #17     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:475:39)
[2023-11-10 22:17:05.430383] [STDOUT] stderr: #18     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:675:27)
[2023-11-10 22:17:05.430425] [STDOUT] stderr: <asynchronous suspension>
[2023-11-10 22:17:05.430474] [STDOUT] stderr: #19     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:315:7)
[2023-11-10 22:17:05.430519] [STDOUT] stderr: <asynchronous suspension>
[2023-11-10 22:17:05.430557] [STDOUT] stderr: #20     Compiler.runInternal (package:compiler/src/compiler.dart:314:5)
[2023-11-10 22:17:05.430590] [STDOUT] stderr: <asynchronous suspension>
[2023-11-10 22:17:05.430636] [STDOUT] stderr: #21     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:235:11)
[2023-11-10 22:17:05.430671] [STDOUT] stderr: <asynchronous suspension>
[2023-11-10 22:17:05.430698] [STDOUT] stderr: #22     compile.<anonymous closure> (package:compiler/compiler_api.dart:256:30)
[2023-11-10 22:17:05.430721] [STDOUT] stderr: <asynchronous suspension>
[2023-11-10 22:17:05.430744] [STDOUT] stderr: #23     compile.compilationDone (package:compiler/src/dart2js.dart:729:3)
[2023-11-10 22:17:05.430771] [STDOUT] stderr: <asynchronous suspension>
[2023-11-10 22:17:05.430795] [STDOUT] stderr: #24     main (package:compiler/src/dart2js.dart:1232:3)
[2023-11-10 22:17:05.430878] [STDOUT] stderr: <asynchronous suspension>
```

**Comment by osa1** [comment]
> There are several dart2js commits in that range from @osa1 and @biggs0125.

My commit in that range only added a test for a regression in dart2wasm.

**Comment by jason-simmons** [comment]
Bisected this to https://dart.googlesource.com/sdk/+/b9e25afcb4d0e448524f144ba213d729065fab6b

**Comment by jonahwilliams** [comment]
Revert is in progress, once that rolls and we re-enable the roller I will close this issue.

**Comment by zanderso** [comment]
Just noting here that `Linux web_benchmarks_html` does not appear to run on https://ci.chromium.org/p/dart/g/monorepo

**Comment by sigmundch** [comment]
cc @athomas @whesse

**Comment by zanderso** [comment]
Rolls are unblocked on this, so I'll go ahead and close it.
