### ISSUE TITLE
external_ui test failure

### ISSUE THREAD

**Issue by aam** [flutter/flutter#13844]
The test failed after d5cc865 engine roll:
```
stdout: [ +395 ms] 00:00 [32m+0[0m: texture suite (setUpAll)[0m
stderr: [  +32 ms] [info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:8100/
stderr: [ +503 ms] [trace] FlutterDriver: Looking for the isolate
stderr: [ +187 ms] [trace] FlutterDriver: Isolate is paused at start.
stderr: [  +21 ms] [trace] FlutterDriver: Attempting to resume isolate
stderr: [  +18 ms] [trace] FlutterDriver: Waiting for service extension
stdout: [ +386 ms] I/flutter (15235): Application starting...
stdout: [+1312 ms] I/flutter (15235): Awaiting calm (3 second pause)...
stderr: [  +57 ms] [info ] FlutterDriver: Connected to Flutter application.
stdout: [   +5 ms] 00:02 [32m+0[0m: texture suite texture rendering[0m
stdout: [+2946 ms] I/flutter (15235): Calibrating...
stdout: [ +653 ms] I/flutter (15235): Calibrating... 5%
stdout: [ +501 ms] I/flutter (15235): Calibrating... 10%
stdout: [ +503 ms] I/flutter (15235): Calibrating... 15%
stdout: [ +505 ms] I/flutter (15235): Calibrating... 20%
stdout: [ +501 ms] I/flutter (15235): Calibrating... 25%
stdout: [ +503 ms] I/flutter (15235): Calibrating... 30%
stdout: [ +504 ms] I/flutter (15235): Calibrating... 35%
stdout: [ +511 ms] I/flutter (15235): Calibrating... 40%
stdout: [ +495 ms] I/flutter (15235): Calibrating... 45%
stdout: [ +558 ms] I/flutter (15235): Calibrating... 50%
stdout: [ +448 ms] I/flutter (15235): Calibrating... 55%
stdout: [ +503 ms] I/flutter (15235): Calibrating... 60%
stdout: [ +504 ms] I/flutter (15235): Calibrating... 65%
stdout: [ +504 ms] I/flutter (15235): Calibrating... 70%
stdout: [ +502 ms] I/flutter (15235): Calibrating... 75%
stdout: [ +503 ms] I/flutter (15235): Calibrating... 80%
stdout: [ +503 ms] I/flutter (15235): Calibrating... 85%
stdout: [ +503 ms] I/flutter (15235): Calibrating... 90%
stdout: [ +513 ms] I/flutter (15235): Calibrating... 95%
stdout: [ +499 ms] I/flutter (15235): Calibrated: frame rate 58.8fps.
stdout: [ +559 ms] I/flutter (15235): Starting .5x speed test...
stdout: [+8131 ms] I/flutter (15235): Stopping .5x speed test...
stdout: [ +230 ms] I/flutter (15235): Starting 2x speed test...
stdout: [+6439 ms] I/FlutterActivityDelegate(14716): onResume setting current activity to this
stdout: [+9082 ms] 00:40 [32m+0[0m[31m -1[0m: texture suite texture rendering [1m[31m[E][0m[0m
stdout: [  +43 ms]   DriverError: Failed to fulfill Tap: Flutter application not responding
stdout: [        ]   Original error: TimeoutException after 0:00:07.500000: Future not completed
stdout: [        ]   Original stack trace:
stdout: [        ]   #0      FlutterDriver._sendCommand (package:flutter_driver/src/driver/driver.dart:324:18)
stdout: [        ]   
stdout: [        ]   #1      FlutterDriver.tap (package:flutter_driver/src/driver/driver.dart:368:11)
stdout: [        ]   
stdout: [        ]   #2      main.. (file:///Users/fortuna/.cocoon/flutter/dev/integration_tests/external_ui/test_driver/main_test.dart:53:20)
stdout: [        ]   
stdout: [        ]   #3      Declarer.test.. (package:test/src/backend/declarer.dart:160:19)
stdout: [        ]   
stdout: [        ]   #4      Invoker.waitForOutstandingCallbacks. (package:test/src/backend/invoker.dart:206:15)
stdout: [        ]   
stdout: [        ]   #5      _rootRun (dart:async/zone.dart:1120)
stdout: [        ]   #6      _CustomZone.run (dart:async/zone.dart:1001)
stdout: [        ]   #7      runZoned (dart:async/zone.dart:1467)
stdout: [        ]   #8      Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:203:5)
stdout: [        ]   #9      Declarer.test. (package:test/src/backend/declarer.dart:158:29)
stdout: [        ]   
stdout: [        ]   #10     Invoker._onRun... (package:test/src/backend/invoker.dart:351:23)
stdout: [        ]   
stdout: [        ]   #11     new Future. (dart:async/future.dart:174)
stdout: [        ]   #12     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
stdout: [        ]   #13     StackZoneSpecification._registerCallback. (package:stack_trace/src/stack_zone_specification.dart:119:48)
stdout: [        ]   #14     _rootRun (dart:async/zone.dart:1116)
stdout: [        ]   #15     _CustomZone.run (dart:async/zone.dart:1001)
stdout: [        ]   #16     _CustomZone.runGuarded (dart:async/zone.dart:901)
stdout: [        ]   #17     _CustomZone.bindCallback. (dart:async/zone.dart:926)
stdout: [        ]   #18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
stdout: [        ]   #19     StackZoneSpecification._registerCallback. (package:stack_trace/src/stack_zone_specification.dart:119:48)
stdout: [        ]   #20     _rootRun (dart:async/zone.dart:1120)
stdout: [        ]   #21     _CustomZone.run (dart:async/zone.dart:1001)
stdout: [        ]   #22     _CustomZone.runGuarded (dart:async/zone.dart:901)
stdout: [        ]   #23     _CustomZone.bindCallback. (dart:async/zone.dart:926)
stdout: [        ]   #24     Timer._createTimer. (dart:async-patch/timer_patch.dart:21)
stdout: [        ]   #25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
stdout: [        ]   #26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
stdout: [        ]   #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
stdout: [  +13 ms] 00:40 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
stderr: [   +1 ms] Unhandled exception:
stderr: [        ] Dummy exception to set exit code.
stderr: [        ] #0      _rootHandleUncaughtError. (dart:async/zone.dart:1108)
stderr: [        ] #1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
stderr: [        ] #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
stderr: [        ] #3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
stderr: [        ] #4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
stderr: [        ] #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
stdout: [  +20 ms] Stopping application instance.
stdout: [        ] Stopping application.
stdout: [        ] /Users/fortuna/Library/Android/sdk/platform-tools/adb -s ZY223TDZ45 shell am force-stop io.flutter.externalui
stdout: [ +967 ms] "flutter drive" took 79,448ms.
stderr: Driver tests failed: 255
stderr: 
stderr: #0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
stderr: #1      _runTests (package:flutter_tools/src/commands/drive.dart:304)
stderr: 
stderr: #2      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:133)
stderr: 
stderr: #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
stderr: 
stderr: #4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
stderr: 
stderr: #5      CommandRunner.runCommand (package:args/command_runner.dart:194)
stderr: 
stderr: #6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
stderr: 
stderr: #7      CommandRunner.run. (package:args/command_runner.dart:109)
stderr: #8      new Future.sync (dart:async/future.dart:222)
stderr: #9      CommandRunner.run (package:args/command_runner.dart:109)
stderr: #10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
stderr: #11     run. (package:flutter_tools/runner.dart:89)
stderr: 
stderr: #12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
stderr: 
stderr: #13     AppContext.runInZone. (package:flutter_tools/src/base/context.dart:66)
stderr: #14     _rootRun (dart:async/zone.dart:1120)
stderr: #15     _CustomZone.run (dart:async/zone.dart:1001)
stderr: #16     runZoned (dart:async/zone.dart:1467)
stderr: #17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
stderr: #18     run (package:flutter_tools/runner.dart:60)
stderr: 
stderr: #19     main (package:flutter_tools/executable.dart:44)
stderr: 
stderr: #20     main (file:///Users/fortuna/.cocoon/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
stderr: #21     _startIsolate. (dart:isolate-patch/isolate_patch.dart:263)
stderr: #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
stderr: 
stderr: 
stdout: [   +5 ms] exiting with code 255
exitcode: 255
Task failed: Executable failed with exit code 255.
```

Not able to reproduce the failure locally.
```
flutter/flutter/dev/integration_tests/external_ui$ flutter drive -v -t lib/main.dart
...
[ +478 ms] I/flutter ( 7993): Starting .5x speed test...
[+8119 ms] I/flutter ( 7993): Stopping .5x speed test...
[ +327 ms] I/flutter ( 7993): Starting 2x speed test...
[+8054 ms] I/flutter ( 7993): Stopping 2x speed test...
[ +198 ms] 00:32 +1: texture suite (tearDownAll)
[  +23 ms] 00:32 +1: All tests passed!
[  +30 ms] Stopping application instance.
[        ] Stopping application.
...
[ +288 ms] "flutter drive" took 55,630ms.
[ +221 ms] ensureAnalyticsSent: 218ms
[   +1 ms] exiting with code 0
...

**Comment by aam** [comment]
@mravn-google

**Comment by aam** [comment]
Am able to reliably reproduce this on mac with android emulator starting from commit eee4a1e.

@sigurdm

**Comment by jason-simmons** [comment]
I can reproduce this on an Android device.

AndroidExternalTextureGL::UpdateTransform() is leaking a JNI reference to the transformMatrix array.  transformMatrix should be declared as:

```
  fml::jni::ScopedJavaLocalRef<jfloatArray> transformMatrix(
      env, env->NewFloatArray(16));
```

**Comment by sigurdm** [comment]
Thanks for investigating this!

**Comment by mravn-google** [comment]
Fixed now, closing.
