### ISSUE TITLE
Engine failing to roll to framework on customer_testing failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#138485]
Starting with https://github.com/flutter/flutter/pull/138476 the analysis_server is crashing on a test in the customer_testing shard:

From https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20customer_testing/67131/overview

```
>> dart fix --apply
| Computing fixes in devtools_app...
| Error from the analysis server: Exception while getting bulk fixes: type 'NotLibraryButPartResult' is not a subtype of type 'ParsedLibraryResult' in type cast
| #0      BulkFixProcessor._computeChangesToPubspec (package:analysis_server/src/services/correction/bulk_fix_processor.dart:376:13)
| #1      BulkFixProcessor.fixPubspec (package:analysis_server/src/services/correction/bulk_fix_processor.dart:287:7)
| #2      EditBulkFixes.handle (package:analysis_server/src/handler/legacy/edit_bulk_fixes.dart:56:38)
| #3      LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:559:25)
| #4      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:29)
| #5      LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:540:29)
| #6      _rootRun (dart:async/zone.dart:1399:13)
| #7      _CustomZone.run (dart:async/zone.dart:1301:19)
| #8      _runZoned (dart:async/zone.dart:1804:10)
| #9      runZonedGuarded (dart:async/zone.dart:1792:12)
| #10     LegacyAnalysisServer.handleRequest (package:analysis_server/src/legacy_analysis_server.dart:536:5)
| #11     LegacyAnalysisServer.handleRequestOrResponse (package:analysis_server/src/legacy_analysis_server.dart:600:7)
| #12     _rootRunUnary (dart:async/zone.dart:1407:47)
| #13     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
| #14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
| #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
| #16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
| #17     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
| #18     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
| #19     new _DebounceRequests.<anonymous closure>.<anonymous closure> (package:analysis_server/src/server/debounce_requests.dart:50:20)
| #20     _rootRun (dart:async/zone.dart:1391:47)
| #21     _CustomZone.run (dart:async/zone.dart:1301:19)
| #22     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
| #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
| #24     _rootRun (dart:async/zone.dart:1399:13)
| #25     _CustomZone.run (dart:async/zone.dart:1301:19)
| #26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233:23)
| #27     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
| #28     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
| #29     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
| #30     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

The Engine roll contains only the Dart roll at https://github.com/flutter/engine/pull/48060.

Guessing it's related to https://dart.googlesource.com/sdk.git/+/9186eb1b94ebe93a6e36d16cd926bae9e629bee0 cc @keertip

**Comment by keertip** [comment]
Reverting the commit in https://dart-review.googlesource.com/c/sdk/+/336460

**Comment by keertip** [comment]
@zanderso, how do I test this against flutter? Would like to get this to stick the next time around.

**Comment by a-siva** [comment]
Can this be closed as the CL has been reverted.

**Comment by zanderso** [comment]
Yes, the Dart rolls are moving again.
