### ISSUE TITLE
[tool_crash] _TypeError: (#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24))

### ISSUE THREAD

**Issue by aykutkilic** [flutter/flutter#138465]
## Command
```
flutter run --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24))
```
#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24)
#1      FlutterApplicationMigration.migrate (package:flutter_tools/src/macos/migrations/flutter_application_migration.dart:30:31)
#2      ProjectMigration.run (package:flutter_tools/src/base/project_migrator.dart:84:16)
#3      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:65:13)
#4      MacOSDevice.buildForDevice (package:flutter_tools/src/macos/macos_device.dart:71:11)
#5      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:119:13)
#6      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:533:47)
<asynchronous suspension>
#7      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:745:27)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
```
```
[32m[✓][39m Flutter (Channel beta, 3.16.0-0.5.pre, on macOS 14.1 23B74 darwin-arm64, locale en-TR)
    [32m•[39m Flutter version 3.16.0-0.5.pre on channel beta at /Users/aykutkilic/devtools/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision adc7dfe87e (7 days ago), 2023-11-07 18:30:33 -0800
    [32m•[39m Engine revision ab14aba1d5
    [32m•[39m Dart version 3.2.0 (build 3.2.0-210.4.beta)
    [32m•[39m DevTools version 2.28.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/aykutkilic/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.0.1)
    [32m•[39m Xcode at /Applications

**Comment by aykutkilic** [comment]
When I create a new default application, during generation I get the following warnings:
```
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-001209CC0AE2801E }
{ platform:macOS, arch:x86_64, id:00006000-001209CC0AE2801E }
2023-11-15 10:32:33.793 xcodebuild[38130:397482] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
Function: createItemModels(for:itemModelSource:)
Thread:   <_NSMainThread: 0x600000cf42c0>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-11-15 10:32:33.794 xcodebuild[38130:397482] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
Function: createItemModels(for:itemModelSource:)
Thread:   <_NSMainThread: 0x600000cf42c0>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-11-15 10:32:33.794 xcodebuild[38130:397482] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
Function: createItemModels(for:itemModelSource:)

```

**Comment by danagbemava-nc** [comment]
Labeling for further investigation from the team. I could not reproduce the tool crash using the steps outlined above. 

> When I create a new default application, during generation I get the following warnings:

@aykutkilic, this is a warning that comes from Xcode itself. This issue was initially tracked in https://github.com/flutter/flutter/issues/135277. It has now been suppressed on the master channel

**Comment by christopherfujino** [comment]
@aykutkilic could you by any chance share your Info.plist file, probably at `your_flutter_app/macos/Runner/Info.plist`? It would help to see what that file looks like, to know why we're failing to parse.

Also @gspencergoog since it looks like you added the migration that checks the key `NSPrincipalClass` in https://github.com/flutter/flutter/commit/c2f5bf99f1d8997cd4ef5e402047d88bdfd36c1c#diff-36c0930d3142bd1c31c68ba49145d35c5964543a24fd71972f813b162f9792b4R33, do you know that that key is guaranteed to be present?

**Comment by gspencergoog** [comment]
I don't know that it is guaranteed to be present. I think it should be, and it was in all of the Info.plist files I saw.

I should point out that we no longer perform that migration (or at least I don't think we do), since Chris found a better way to do it that didn't involve overriding the NSApplication.

**Comment by christopherfujino** [comment]
> I should point out that we no longer perform that migration (or at least I don't think we do), since Chris found a better way to do it that didn't involve overriding the NSApplication.

By "we no longer perform that migration" you mean we deleted it upstream?

**Comment by gspencergoog** [comment]
> By "we no longer perform that migration" you mean we deleted it upstream?

Yes, AFAIK.

**Comment by christopherfujino** [comment]
> > By "we no longer perform that migration" you mean we deleted it upstream?
> 
> Yes, AFAIK.

That's good to know, maybe we won't even need to fix this then.

**Comment by christopherfujino** [comment]
@gspencergoog it looks like this is still wired into build_macos at HEAD: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/macos/build_macos.dart#L82 & https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/macos/migrations/flutter_application_migration.dart#L18C7-L18C34

**Comment by gspencergoog** [comment]
Oh, yes, that's right, we do, because some people might have migrated to use `FlutterApplication` in the short period (a few weeks) when we required it. This is the "fix" for that so that it would go back to `NSApplication` if they did that.  But it should be OK if there isn't any `NSPrincipalClass` key set to `FlutterApplication`.

We can probably remove this migration, though;  Anyone who needed it has probably long been fixed by it, and it has the flaw that if someone *did* want to set their own `NSPrincipalClass` to something, and happened to call it "FlutterApplication", this would revert it.

**Comment by gspencergoog** [comment]
Also, it still shouldn't fail even if `NSPrincipalClass` doesn't exist: it explicitly checks for that and returns.

**Comment by daksh-gargas** [comment]
Attaching `info.plist` from #145740 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>FLTEnableImpeller</key>
	<string>false</string>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>$(APP_DISPLAY_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIcons</key>
	<dict/>
	<key>CFBundleIcons~ipad</key>
	<dict/>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Wildr</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Bundle ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>DevGoogleSignIn</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>xxx</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>ProdGoogleSignIn</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>xxx</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>StagingGoogleSignIn</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>xxx</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FirebaseDynamicLinksCustomDomains</key>
	<array>
		<string>xxx</string>
	</array>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSAppliLSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>xxx</string>
	<key>NSContactsUsageDescription</key>
	<string>xxx</string>
	<key>NSLocalNetworkUsageDescription</key>
	<string></string>
	<key>NSMicrophoneUsageDescription</key>
	<string>xxx</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>xxx</string>
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>xxx.</string>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleDefault</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

```

cc @christopherfujino

**Comment by Chojecki** [comment]
Hi, facing the same issue: ['String' is not a subtype of type 'bool?' in type cast when bulding for iOS](https://github.com/flutter/flutter/issues/145740)


My plist file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>FLTEnableImpeller</key>
	<string>$(ENABLE_IMPELLER)</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>$(APP_DISPLAY_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>talkoutapp</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>AppGroupId</key>
	<string>$(CUSTOM_GROUP_ID)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>googlegmail</string>
		<string>x-dispatch</string>
		<string>readdle-spark</string>
		<string>airmail</string>
		<string>ms-outlook</string>
		<string>ymail</string>
		<string>fastmail</string>
	</array>
	<key>FirebaseDynamicLinksCustomDomains</key>
	<array>
		<string>$(FIREBASE_DYNAMIC_LINKS_DOMAIN)</string>
	</array>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.auth0.talkout-mobile</string>
				<string>ShareMedia-$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Bundle ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			</array>
		</dict>
		<dict>
      		<key>CFBundleTypeRole</key>
      		<string>Editor</string>
      		<key>CFBundleURLName</key>
      		<string>app.dev.reelyze.dev</string>
      		<key>CFBundleURLSchemes</key>
      		<array>
        		<string>reelyzeapp</string>
      		</array>
    </dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSMicrophoneUsageDescription</key>
	<string>We need access to your microphone to allow you to share videos taken directly in app. No content other than taken videos will be uploaded.</string>
	<key>NSCameraUsageDescription</key>
	<string>We need access to your camera to allow you to upload profile pictures and content you want to share in the app. No content other than taken photos and videos will be uploaded.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>We need access to your photo library to allow you to upload profile pictures and content you want to share in the app. No content other than specific images and videos you select will be uploaded.</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
</dict>
</plist>
```

It blocks my CI Pipeline. Not sure what caused the issue 🤔

**Comment by Chojecki** [comment]
I just noticed that I had FLTEnableImpeller set as string. According to docs now it's boolean. Setting it as boolean fixed CI pipeline issue.

Don't know when Flutter team decided to change it and if was it announced in release notes (can't see it). If no its such a shame that it was forgotten :/
