### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by unique-gautam-yadav** [flutter/flutter#138625]
## Command
```
flutter run -d macos
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      Target.clearStamp (package:flutter_tools/src/build_system/build_system.dart:166:29)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:880:19)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#10     FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart:694:16)
<asynchronous suspension>
#11     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart:1271:18)
<asynchronous suspension>
#12     HotRunner.run (package:flutter_tools/src/run_hot.dart:377:7)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:753:27)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.13.9 on channel stable at /Users/gautam/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision d211f42860 (3 weeks ago), 2023-10-25 13:42:25 -0700
    [32m•[39m Engine revision 0545f8705d
    [32m•[39m Dart version 3.1.5
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/gautam/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.0.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15A507
    [32m•[39m CocoaPods version 1.13.0

[32m[✓][39m Chrome - develop for the

**Comment by huycozy** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/138458. Please check https://github.com/flutter/flutter/issues/138458#issuecomment-1811919311 and confirm. Thanks!
