### ISSUE TITLE
Reload fails when DateTime crosses midnight

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#13862]
## Steps to Reproduce
Run flutter run of an app at 11:58pm, perform hot reload and/or full restart. 

After 12am, press 'R' to full restart. Flutter crashes and loses connection to device (at least, I think that's what's happening). 

See below:

```
Performing hot reload...
Reloaded 0 of 593 libraries in 419ms.

Performing full restart...
Restarted app in 1,453ms.

Performing full restart...
NoSuchMethodError: The method 'isAfter' was called on null.
Receiver: null
Tried calling: isAfter(Instance of 'DateTime')
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      DevFSFileContent.isModified (package:flutter_tools/src/devfs.dart:103)
#3      DevFS.update.<anonymous closure> (package:flutter_tools/src/devfs.dart:448)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#5      DevFS.update (package:flutter_tools/src/devfs.dart:440)
<asynchronous suspension>
#6      FlutterDevice.updateDevFS (package:flutter_tools/src/resident_runner.dart:363)
<asynchronous suspension>
#7      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:272)
<asynchronous suspension>
#8      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:359)
<asynchronous suspension>
#9      HotRunner.restart (package:flutter_tools/src/run_hot.dart:435)
<asynchronous suspension>
#10     HotRunner.handleTerminalCommand (package:flutter_tools/src/run_hot.dart:235)
<asynchronous suspension>
#11     ResidentRunner.processTerminalInput (package:flutter_tools/src/resident_runner.dart:725)
<asynchronous suspension>
#12     _rootRunUnary (dart:async/zone.dart:1128)
#13     _CustomZone.runUnary (dart:async/zone.dart:1012)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#17     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379)
#18     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254)
#19     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:480)
#20     _rootRunUnary (dart:async/zone.dart:1128)
#21     _CustomZone.runUnary (dart:async/zone.dart:1012)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#28     _SimpleAsciiDecoderSink.add (dart:convert/ascii.dart:296)
#29     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#31     _rootRunUnary (dart:async/zone.dart:1128)
#32     _CustomZone.runUnary (dart:async/zone.dart:1012)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#36     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#37     _StreamController._add (dart:async/stream_controller.dart:667)
#38     _StreamController.add (dart:async/stream_controller.dart:613)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#40     _rootRunUnary (dart:async/zone.dart:1132)
#41     _CustomZone.runUnary (dart:async/zone.dart:1012)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#45     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#46     _StreamController._add (dart:async/stream_controller.dart:667)
#47     _StreamController.add (dart:async/stream_controller.dart:613)
#48     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#49     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)

Lost connection to device.
```

**Comment by Hixie** [comment]
cc @aam

**Comment by jason-simmons** [comment]
fwiw, I tried simulating this on an Ubuntu box using the "faketime" utility but wasn't able to reproduce the bug.  Hot reload worked as expected after the clock passed midnight.

**Comment by Hixie** [comment]
Since we are unable to reproduce, and since this has an easy workaround, I'm going to punt this to the next milestone for now.

**Comment by timsneath** [comment]
Closing for now.
