### ISSUE TITLE
Better error message for sliver grid

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#13861]
I'm getting a NaN in sliver_grid.dart.

```
I/flutter (13931): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13931): The following UnsupportedError was thrown during performLayout():
I/flutter (13931): Unsupported operation: Infinity or NaN toInt
I/flutter (13931): 
I/flutter (13931): When the exception was thrown, this was the stack:
I/flutter (13931): #0      _Double.toInt (dart:core-patch/dart:core/double.dart:151)
I/flutter (13931): #1      _Double.ceil (dart:core-patch/dart:core/double.dart:126)
I/flutter (13931): #2      SliverGridDelegateWithMaxCrossAxisExtent.getLayout (package:flutter/src/rendering/sliver_grid.dart:425)
I/flutter (13931): #3      RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:522)

```

**Comment by long1eu** [comment]
problem solved, I was settings 
```
mainAxisSpacing: 0.0,
crossAxisSpacing: 0.0
```

**Comment by Hixie** [comment]
I'm going to reopen this so that we can make the error message better.

**Comment by long1eu** [comment]
Sure, I like that about you. You always want to help. :D

**Comment by edman** [comment]
I'm getting the same error in a test. Weird thing is it works when running the app.

This works..

```dart
void main() => runApp(
      MaterialApp(
        home: Row(
          mainAxisSize: MainAxisSize.max,
          children: <Widget>[Expanded(child: LinearProgressIndicator())],
        ),
      ),
    );
```

But this doesn't..

```dart
tester.pumpWidget(
  MaterialApp(
    home: Row(
      mainAxisSize: MainAxisSize.max,
      children: <Widget>[Expanded(child: LinearProgressIndicator())],
    ),
  ),
);
```

How can I fix the test? The above is a simplification, but in my app I have a widget that I want to expand horizontally; and inside this widget there's a row of widgets, among which some will also expand horizontally.
