### ISSUE TITLE
_createDevFS: Unexpected exception:PathNotFoundException

### ISSUE THREAD

**Issue by TENX-S** [flutter/flutter#138783]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run `flutter run -d macos` under https://github.com/flutter/packages/tree/main/packages/two_dimensional_scrollables/example

### Expected results

devtools should works

### Actual results

devtool disappeared

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details>
<summary>Logs</summary>

```console
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run -d macos

## exception

RPCError: _createDevFS: (-32603) Internal error
_createDevFS: Unexpected exception:PathNotFoundException: Creation of temporary directory failed, path = '/Users/ares/Library/Containers/com.example.example/Data/tmp' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory.createTemp.<anonymous closure> (dart:io/directory_impl.dart:152:7)
<asynchronous suspension>
#2      createTempDirCallback (dart:vmservice_io:203:16)
<asynchronous suspension>
#3      DevFS._createDevFS (dart:_vmservice/devfs.dart:182:21)
<asynchronous suspension>
#4      VMService._routeRequestImpl (dart:_vmservice:811:16)
<asynchronous suspension>
#5      VMService.routeRequest (dart:_vmservice:774:22)
<asynchronous suspension>
#6      WebSocketClient.post (dart:vmservice_io/vmservice_server.dart:64:3)
<asynchronous suspension>



#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1930:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2499:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2470:14)
#3      FlutterVmService.createDevFS (package:flutter_tools/src/vmservice.dart:1042:20)
#4      DevFS.create (package:flutter_tools/src/devfs.dart:512:61)
#5      FlutterDevice.setupDevFS (package:flutter_tools/src/resident_runner.dart:392:19)
#6      HotRunner._initDevFS (package:flutter_tools/src/run_hot.dart:467:23)
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:270:41)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:745:27)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-CN)
    • Flutter version 3.16.0 on channel stable at /Users/ares/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (6 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/ares/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Microsoft Edge 119.0.2151.72

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @TENX-S, do you experience this issue every time or was it a one-off?

**Comment by TENX-S** [comment]
every time @danagbemava-nc

**Comment by danagbemava-nc** [comment]
Hi @TENX-S, I can't seem to reproduce the issue. 

How do you launch the devtools? Do you use the link that appears in the flutter run command or do you launch it a different way? And is this only happening when you want to open devtools?
