### ISSUE TITLE
Flutter Test: scrollUntilVisible no longer works in Flutter 3.16.0

### ISSUE THREAD

**Issue by tformatix** [flutter/flutter#138735]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Ran tests in Flutter 3.13.6
2. All tests ran through
3. Upgraded Flutter to 3.16.0
4. Tests are failing when scrollUntilVisible was in use

### Expected results

A Widget is located in a ListView. To find and verify it's visibility I used scrollUntilVisible because it's located on the bottom of the ListView.

</details>

### Actual results

Test is failing because the expected item cannot be found.

<details><summary>Warning</summary>

```console
Warning: A call to tap() with finder "Found 1 widget with type "TextButton": [
  TextButton(dependencies: [MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#5d4ca], _ScrollableScope], state: _ButtonStyleState#30c27),
]" derived an Offset (Offset(400.0, 610.0)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
Indeed, Offset(400.0, 610.0) is outside the bounds of the root of the render tree, Size(800.0, 600.0).
The finder corresponds to this RenderBox: RenderSemanticsAnnotations#757d8 relayoutBoundary=up7
The hit test result at that offset is: HitTestResult(HitTestEntry<HitTestTarget>#139be(_ReusableRenderView#f5ee3), HitTestEntry<HitTestTarget>#bec53(<AutomatedTestWidgetsFlutterBinding>))
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1409:25)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1292:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:613:18)
#3      main.<anonymous closure> (file:///C:/path/to/flutter/App/test/screens/settings/settings_screen_test.dart:36:18)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
<asynchronous suspension>
#6      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:114:42)
<asynchronous suspension>
To silence this warning, pass "warnIfMissed: false" to "tap()".
To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.
```

</details>

### Code sample

<details><summary>Code sample</summary>

```dart
testWidgets('SettingsScreen: logout', (WidgetTester tester) async {
    await loadWidget(tester);

    final buttonFinder = find.byType(TextButton);
    await tester.scrollUntilVisible(buttonFinder, 500); // error occurs here
    await tester.tap(buttonFinder);
    await tester.pumpAndSettle();

    verify(authenticationRepository.logoutUser());
    expect(find.byType(SettingsScreen), findsNothing);
    expect(find.byType(StartupScreen), findsOneWidget);
});
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22621.2715], locale de-AT)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
[√] VS Code (version 1.84.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by tformatix** [comment]
Hi @danagbemava-nc, thanks for the fast response!

I did some more research and stumbled across the error. It is due to the ```physics: isLoading ? const NeverScrollableScrollPhysics() : null```. If I delete that, the test works. But I have not changed any code in this section - so it worked in the previous version of flutter.

You can find the code here. I have made some sections unrecognizable where the business logic is contained.

### SettingsScreen

``` dart
class SettingsScreen extends StatelessWidget {
  const SettingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            title: Text(AppLocalizations.of(context)?.settings_title ?? '')),
        body: const Shimmer(child: SettingsScreenBody()));
  }
}

class SettingsScreenBody extends StatelessWidget implements BaseScreenBody {
  const SettingsScreenBody({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => SettingsBloc(
          authenticationRepository: context.read<AuthenticationRepository>(),
          settingsRepository: context.read<SettingsRepository>())
        ..add(SettingsFetchEvent()),
      child: Center(child: BlocBuilder<SettingsBloc, SettingsState>(
          builder: (context, settingsState) {
        if (settingsState is SettingsLogoutState) {
          WidgetsBinding.instance.addPostFrameCallback((_) {
            Navigator.pushAndRemoveUntil(
                context,
                MaterialPageRoute(builder: (context) => const StartupScreen()),
                ModalRoute.withName('/'));
          });
          return Container();
        } else {
          final isLoading = settingsState is SettingsLoadingState;

          return RefreshIndicator(
              onRefresh: () async => onRefresh(context),
              child: ListView(
                  physics:
                      isLoading ? const NeverScrollableScrollPhysics() : null,
                  children: [
                      // some children
                  ]));
        }
      })),
    );
  }

  @override
  Future<void> onRefresh(BuildContext context) async {
    context.read<SettingsBloc>().add(SettingsFetchEvent());
  }
}
```
### SettingsBloc
``` dart
class SettingsBloc extends Bloc<SettingsEvent, SettingsState> {
  final AuthenticationRepository authenticationRepository;
  final SettingsRepository settingsRepository;

  SettingsBloc(
      {required this.authenticationRepository,
      required this.settingsRepository})
      : super(SettingsLoadingState()) {
    on<SettingsFetchEvent>((_, emit) async => _onSettingsFetchEvent(emit));
    on<SettingsLogoutEvent>((_, emit) async => _onLogoutEvent(emit));
  }

  void _onSettingsFetchEvent(Emitter<SettingsState> emit) async {
    _emitLoadingState(emit);
    emit(SettingsState(someData: await settingsRepository.getSomeData()));
  }

  void _onLogoutEvent(Emitter<SettingsState> emit) {
    authenticationRepository.logoutUser();
    emit(SettingsLogoutState());
  }

  void _emitLoadingState(Emitter<SettingsState> emit) {
    emit(SettingsLoadingState());
  }
}
```

### Test of SettingsScreen
``` dart
testWidgets('SettingsScreen: logout', (WidgetTester tester) async {
    // mock generated with @GenerateNiceMocks([MockSpec<AuthenticationRepository>()])
    final authenticationRepository = MockAuthenticationRepository();
    final settingsRepository = MockSettingsRepository();

    await tester.pumpWidget(MultiRepositoryProvider(providers: [
      RepositoryProvider<AuthenticationRepository>(
          create: (context) => authenticationRepository),
      RepositoryProvider<SettingsRepository>(
          create: (context) => settingsRepository),
    ], child: const MaterialApp(home: SettingsScreenBody())));

    final buttonFinder = find.byType(TextButton);
    await tester.scrollUntilVisible(buttonFinder, 500);
    await tester.tap(buttonFinder);
    await tester.pumpAndSettle();

    verify(authenticationRepository.logoutUser());
    expect(find.byType(SettingsScreen), findsNothing);
    expect(find.byType(StartupScreen), findsOneWidget);
});
```

Is this sufficient or should I recreate everything in a separate project?

**Comment by danagbemava-nc** [comment]
Hi @tformatix, would it be possible for you to provide a test case without any third-party packages? This would help us to know if the failure is indeed caused by something in the framework.

**Comment by tformatix** [comment]
Hi @danagbemava-nc, I can't reproduce it without third party packages. Therefore it must be caused by flutter_bloc or mockito.

I think we can close this issue at this stage, sorry for taking your time.

**Comment by danagbemava-nc** [comment]
That's alright, if you do manage to come up with a sample that doesn't involve any third-party packages, do leave a comment below with the sample and I will reopen this. 

Thank you
