### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by fiurthorn** [flutter/flutter#138710]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```dart
import 'package:form_bloc/form_bloc.dart' as form_bloc;

/// [BlocListener] that reacts to the state changes of the FormBloc.
class FormBlocListener<
        FormBloc extends form_bloc.FormBloc<SuccessResponse, ErrorResponse>,
        SuccessResponse,
        ErrorResponse>
    extends BlocListener<FormBloc,
        form_bloc.FormBlocState<SuccessResponse, ErrorResponse>> {
```

### Expected results

Compiling with 3.13.9 works, but with 3.16 it no longer works.

### Actual results

```
Target dart2js failed: ProcessException: Process exited abnormally:
../../../.pub-cache/hosted/pub.dev/flutter_form_bloc-0.31.0/lib/src/form_bloc_listener.dart:6:9:
Error: Type 'FormBlocState' can't use itself as a bound.
        FormBlocState extends form_bloc
        ^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/flutter_form_bloc-0.31.0/lib/src/form_bloc_listener.dart:14:9:
Error: Type 'FormBloc' can't use itself as a bound.
        FormBloc extends form_bloc.FormBloc<SuccessResponse, ErrorResponse>,
        ^^^^^^^^
../../../.pub-cache/hosted/pub.dev/pdfx-2.4.0/lib/src/viewer/pdf_page_image_provider.dart:24:55:
Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(PdfPageImageProvider key, DecoderCallback decode) =>
                                                      ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/pdfx-2.4.0/lib/src/viewer/pdf_page_image_provider.dart:40:7:
Error: Type 'DecoderCallback' not found.
      DecoderCallback decode) async {
      ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/flutter_form_bloc-0.31.0/lib/src/form_bloc_listener.dart:17:13:
Error: Type argument 'FormBloc' doesn't conform to the bound 'StateStreamable<S>' of the type variable 'B' on 'BlocListener'.
 - 'StateStreamable' is from 'package:bloc/src/bloc.dart' ('../../../.pub-cache/hosted/pub.dev/bloc-8.1.2/lib/src/bloc.dart').
    extends BlocListener<FormBloc,
            ^
../../../.pub-cache/hosted/pub.dev/flutter_bloc-8.1.3/lib/src/bloc_listener.dart:76:20:
Info: This is the type variable whose bound isn't conformed to.
class BlocListener<B extends StateStreamable<S>, S>
                   ^
../../../.pub-cache/hosted/pub.dev/go_router-12.1.1/lib/src/information_provider.dart:131:34:
Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
      location: routeInformation.location!,
                                 ^
../../../.pub-cache/hosted/pub.dev/go_router-12.1.1/lib/src/parser.dart:90:50:
Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
        configuration.findMatch(routeInformation.location!, extra: state.extra);
                                                 ^
../../../.pub-cache/hosted/pub.dev/pdfx-2.4.0/lib/src/viewer/pdf_page_image_provider.dart:24:55:
Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(PdfPageImageProvider key, DecoderCallback decode) =>
                                                      ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/pdfx-2.4.0/lib/src/viewer/pdf_page_image_provider.dart:40:7:
Error: 'DecoderCallback' isn't a type.
      DecoderCallback decode) async {
      ^^^^^^^^^^^^^^^
Error: Compilation failed.
  Command: /home/weinmann/.local/flutter-3.16/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/weinmann/.local/flutter-3.16/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
  --platform-binaries=/home/weinmann/.local/flutter-3.16/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLAVOR=portal -DFLUTTER_WEB_AUTO_DETECT=false
  -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/74d16627b940bb15e50891f82cad6c3e3465bd6d/ --native-null-assertions -o
  /home/weinmann/workspace/intexforms/client/.dart_tool/flutter_build/a6b1e266b57431f9c91642de9c94b434/app.dill --packages=.dart_tool/package_config.json --cfe-only
  /home/weinmann/workspace/intexforms/client/.dart_tool/flutter_build/a6b1e266b57431f9c91642de9c94b434/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:280:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:189:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:199:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Compiling lib/portal.dart for the Web...                           19,3s
Exception: Failed to compile application for the Web.
Error: exit status 1
```

**Comment by danagbemava-nc** [comment]
This is an issue with flutter_form_bloc and should be reported on their repo. See https://github.com/GiancarloCode/form_bloc/issues/339

Closing from here as this is not a flutter issue. 

Thank you

**Comment by fiurthorn** [comment]
No its not ist a Problem with e the flutter compiler since its compiles find with 3.13.
The dart compiler cant differ between `FormBlocState`  and `form_bloc.FormBlocState`.

unless you simply changed the compiler specification.

It would be nice if someone with expertise looked at it, not the bouncer, just closed it.

**Comment by fiurthorn** [comment]
@danagbemava-nc if U look yourself to the solution, he renames the symbols.
that would be the compiler's job.

![image](https://github.com/flutter/flutter/assets/13510039/6c5ab1c9-bdb0-46be-89b4-e080d0022a64)

**Comment by fiurthorn** [comment]
https://github.com/flutter/flutter/issues/138785
