### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by mrpyae** [flutter/flutter#138725]
## Command
```
flutter channel
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:644:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      Session.getSessionId (package:unified_analytics/src/session.dart:59:17)
#6      UserProperty._toMap (package:unified_analytics/src/user_property.dart:61:31)
#7      UserProperty.preparePayload (package:unified_analytics/src/user_property.dart:48:47)
#8      generateRequestBody (package:unified_analytics/src/utils.dart:109:39)
#9      AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:583:18)
#10     FlutterCommand._sendPostUsage (package:flutter_tools/src/runner/flutter_command.dart:1620:15)
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1393:13)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:...

**Comment by danagbemava-nc** [comment]
Hi @mrpyae, 

Can you please confirm that the user you are running the tool as has permission to write to the directory where your Flutter project is?

Also, what version of flutter is installed on your system?
