### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument (string): Contains invalid characters.: "远程计算机拒绝网络连接。\r\n"

### ISSUE THREAD

**Issue by jacklee1995** [flutter/flutter#138868]
## Command
```
flutter config --no-analytics
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument (string): Contains invalid characters.: "远程计算机拒绝网络连接。\r\n"
```
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      new Response (package:http/src/response.dart:37:49)
#3      GAClient.sendData (package:unified_analytics/src/ga_client.dart:73:47)
<asynchronous suspension>
#4      ConfigCommand.runCommand (package:flutter_tools/src/commands/config.dart:152:7)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous sus

**Comment by dam-ease** [comment]
Thanks for filing this. 

> "The remote computer refused the network connection.\r\n"

Can you please confirm this and share your results:

- You have a stable network connection?
- You to the latest version of flutter `3.16.0`, also share the full output of your `flutter doctor -v`
