### ISSUE TITLE
Firestore crashes after Firebase Signoff - Missing a feature to stop listening?

### ISSUE THREAD

**Issue by Arno-Z** [flutter/flutter#13883]
Hi,

When i run the code below, it all works fine, until i sign off. The Widget containing the StreamBuilder is unloaded by setting _currentUser = null. 

I am not sure what the issue is, on one side i expect the listener to halt when the authstate is changed. As the listener is not halted the security error is logical but should in my opinion have been picked up by  if (snapshot.hasError).

On the other hand, i would also find it logical if it were my responsibility to close the listener before signing the user out. A method i have not been able to locate.

Snippet of code which runs:

```dart
    return new StreamBuilder<QuerySnapshot>(
        stream: Firestore.instance
            .collection('expenses')
            .where("owner", isEqualTo: _currentUser.uid)
            .where("status", isEqualTo: choice.statusCode)
            .where("expenseDate", isGreaterThanOrEqualTo: _cutOffDate)
            .orderBy("expenseDate", descending: true)
            .snapshots,
        builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
          if (snapshot.hasError)
            return new Center(
              child: new Column(
                children: <Widget>[
                  new Icon(Icons.cloud_off),
                  new Text('An error has occured'),
                ],
              ),
            );
```
Works Ok throughout the app. Until the users sign's off:
```dart
Future<Null> _handleSignOut() async {
    print("_handleSignOut");
    try {
      setState(() {
        _currentUser = null;
      });

      await _googleSignIn.signOut();
      await _auth.signOut();


      print("_handleSignOut Completed");
    } catch (error) {
      print(error);
    }
  }
```

## Logs

```
I/flutter (19097): _handleSignOut Completed
I/System.out(19097): com.google.firebase.firestore.FirebaseFirestoreException: PERMISSION_DENIED: Missing or insufficient permissions.
D/AndroidRuntime(19097): Shutting down VM
E/AndroidRuntime(19097): FATAL EXCEPTION: main
E/AndroidRuntime(19097): Process: com.qlouder.expenses, PID: 19097
E/AndroidRuntime(19097): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.google.firebase.firestore.QuerySnapshot.getDocuments()' on a null object reference
E/AndroidRuntime(19097): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:137)
E/AndroidRuntime(19097): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:119)
E/AndroidRuntime(19097): 	at com.google.firebase.firestore.zzi.onEvent(Unknown Source)
E/AndroidRuntime(19097): 	at com.google.android.gms.internal.zzevc.zza(Unknown Source)
E/AndroidRuntime(19097): 	at com.google.android.gms.internal.zzevd.run(Unknown Source)
E/AndroidRuntime(19097): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(19097): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(19097): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(19097): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/AndroidRuntime(19097): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19097): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/AndroidRuntime(19097): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

## Flutter Analyze
```
flutter analyze
Analyzing /Users/arno/AndroidStudioProjects/...
No issues found!
Ran in 6.6s
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-NL, channel alpha)
    • Flutter at /Users/arno/flutter
    • Framework revision 8f65fec5f5 (3 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/arno/Library/Android/sdk
    • Android NDK at /Users/arno/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0.beta.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.0 (API 24) (emulator)
    • iPhone X                  • F0BB54B0-B069-490B-A231-200E104E3FDF • ios         • iOS 11.2 (simulator)
```

**Comment by Arno-Z** [comment]
@collinjackson may i just bring this to your attention?

**Comment by collinjackson** [comment]
I'm wondering whether you're still seeing this in `cloud_firestore` version `0.2.1`. Just want to confirm that it's not #12714.

If so: do you see the issue on iOS as well, or just Android?

**Comment by Arno-Z** [comment]
Hi,

Can confirm it is still an issue with 2.1. Only on Android.

On signout the widget showing the document list is replaced with the login widget. (Thus the document collecting should no longer exist?)

Shortly after the login widget is shown the app will crash. Android will suggest a restart. The restart is Ok, because the DocumentCollection is not yet loaded.

So in essence i have 3 questions:
1- can i stop the listener myself (don't see it in the source)
2- Shouldn't the DocumentCollection unload itself when the widget ia unloaded.
3- Shouldn't the error by trapped by the snapshot.haserrror

Thanks!

Arno

**Comment by bramvbilsen** [comment]
This issue is specific to the Firebase Authentication plugin. I'm gettng the same logs without using any other plugins.
Is there any update on this?

**Comment by mortenboye** [comment]
I'm also experiencing this. 
Are there any developments on this issue?

**Comment by collinjackson** [comment]
I believe that the issue probably no longer happens because CloudFirestorePlugin.java has been rewritten to include this null check

```java
    if (querySnapshot == null) return new HashMap<>();
```

If I am mistaken please provide a test case app and I'd be happy to look into it further.

**Comment by kroikie** [comment]
@Arno-Z

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/920. Any further collaboration will be done there.
