### ISSUE TITLE
Failed assertion: line 5234 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by DomainiHabib** [flutter/flutter#138989]
```
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  GetMaterialApp GetMaterialApp:file:///C:/Users/Administrator/StudioProjects/ecommercecourse/lib/main.dart:25:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5234:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#12     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#27     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#35     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#39     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#47     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#51     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#55     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#58     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#60     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#64     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#68     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#73     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#77     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#81     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#89     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#106    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#107    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#110    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#112    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#115    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#117    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#121    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#124    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#126    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#131    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#132    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#133    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#136    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#138    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#141    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#143    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#147    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#150    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#152    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#154    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#158    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#159    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#162    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#164    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#167    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#168    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#169    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#172    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#173    StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#174    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#175    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#179    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#180    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#183    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#184    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#185    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#186    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#188    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#189    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#190    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#191    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#194    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#197    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#198    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#199    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#200    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#201    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#202    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#203    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#204    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#206    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#207    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#208    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#211    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#212    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#213    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#215    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#216    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#217    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#220    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#221    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#222    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#224    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#225    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#227    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#228    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#229    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#230    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#232    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#234    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#235    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#237    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#238    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#241    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#242    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#245    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#246    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#247    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#248    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#250    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#251    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#252    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#253    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#254    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#255    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#256    StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#258    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#259    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#260    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#261    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#262    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#263    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#264    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#265    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#269    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
```

**Comment by bartekpacia** [comment]
This issue is not reproducible.

Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by darshankawar** [comment]
@DomainiHabib 
Looking at the error log, it might be that you are calling Navigator before the build, so you'll need to revisit your code implementation and see if there's anything missing to properly structure it. If not, as requested above, provide reproducible code sample without any third party package implementation so that we can address it properly.

**Comment by DomainiHabib** [comment]
Thank u ,it turns out that after I closed android studio and turn it on
again It worked fine

**Comment by darshankawar** [comment]
Closing as resolved.
