### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect., errno = 123

### ISSUE THREAD

**Issue by Syamsiut** [flutter/flutter#138999]
## Command
```
flutter create page:introduction
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      IosProject.existsSync (package:flutter_tools/src/xcode_project.dart:215:50)
#6      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:139:13)
#7      CreateBase.getOrganization (package:flutter_tools/src/commands/create_base.dart:258:63)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:249:39)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1662:12)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous sus

**Comment by darshankawar** [comment]
@Syamsiut 


> flutter create page:introduction

The correct command should be `flutter create page_introduction` with which you can try and check if you still get same error or not.
The tool seems to be correctly identifying what could be wrong in the command and then throwing the appropriate error, so this isn't a bug but due to incorrect syntax you passed.
I'll close this as not an issue. If you disagree, write in comments and I'll reopen it.
