### ISSUE TITLE
NPE in FirebaseAuthPlugin 

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#13899]
I'm getting a `NullPointerException` when calling `getCurrentUser()`. I'm logging in using Firebase Phone Auth through Firebase UI, after that, first time I call `getCurrentUser` I get this crash. After that the method works fine.

```
I/flutter ( 8489): D/ProfilePageState                : User logged in yA1V2NUkUSQsKTYwc7mSnlQhiXn2.
D/AndroidRuntime( 8489): Shutting down VM
E/AndroidRuntime( 8489): FATAL EXCEPTION: main
E/AndroidRuntime( 8489): Process: app.id, PID: 8489
E/AndroidRuntime( 8489): java.lang.NullPointerException: null value in entry: uid=null
E/AndroidRuntime( 8489): 	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
E/AndroidRuntime( 8489): 	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49)
E/AndroidRuntime( 8489): 	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:122)
E/AndroidRuntime( 8489): 	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:198)
E/AndroidRuntime( 8489): 	at io.flutter.firebaseauth.FirebaseAuthPlugin.userInfoToMap(FirebaseAuthPlugin.java:287)
E/AndroidRuntime( 8489): 	at io.flutter.firebaseauth.FirebaseAuthPlugin.mapFromUser(FirebaseAuthPlugin.java:305)
E/AndroidRuntime( 8489): 	at io.flutter.firebaseauth.FirebaseAuthPlugin.access$000(FirebaseAuthPlugin.java:31)
E/AndroidRuntime( 8489): 	at io.flutter.firebaseauth.FirebaseAuthPlugin$1.onAuthStateChanged(FirebaseAuthPlugin.java:124)
E/AndroidRuntime( 8489): 	at com.google.firebase.auth.zzi.run(Unknown Source)
E/AndroidRuntime( 8489): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 8489): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 8489): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 8489): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/AndroidRuntime( 8489): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8489): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/AndroidRuntime( 8489): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by alibitek** [comment]
Already fixed in https://github.com/flutter/plugins/pull/329/files#diff-2ed885c78d229177455b276c34e93577R537 (when it'll be merged)

**Comment by long1eu** [comment]
Hi! Thanks I see that this is you plugin addition. How about iOS?

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by kroikie** [comment]
@long1eu

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/919. Any further collaboration will be done there.
