### ISSUE TITLE
DatePickerEntryMode.input does not work on iOS real devices

### ISSUE THREAD

**Issue by KoheiKanagu** [flutter/flutter#139120]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Please run the code sample on an iOS real device.

I have tested the issue on my iPhone 11 Pro with iOS 17.1.1 and iPhone 14 Pro with iOS 17.2.
The issue was not reproducible on the iOS simulator.

The issue also occurs in release mode.

### Expected results

Keyboard appears and date can be entered.

### Actual results

Keyboard does not appear and date cannot be entered.

### Code sample

<details><summary>Code sample</summary>

https://github.com/KoheiKanagu/date_picker_dialog

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FilledButton(
          onPressed: () {
            showDatePicker(
              context: context,
              firstDate: DateTime(2023),
              lastDate: DateTime(2024),
            );
          },
          child: const Text("Show Date Picker"),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/6175794/d92d52fe-eb5e-47f2-b34e-d4e166b10139

</details>

### Logs

<details><summary>Logs</summary>

Nothing is output

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.16.1, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
    • Flutter version 3.16.1 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (13 hours ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/kingu/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/kingu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/kingu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Users/kingu/Develop/global/dotfiles/google-chrome-unsafe.sh

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (6 available)
    • KingPad K10 (mobile)    • VKK104GJP0000443                     • android-arm64  • Android 10 (API 29)
    • KiPhone 11 Pro (mobile) • 00008030-00111C983630802E            • ios            • iOS 17.1.1 21B91
    • KiPhone 14 Pro (mobile) • 00008120-001159C40CEB401E            • ios            • iOS 17.2 21C5046c
    • iPhone 15 Pro (mobile)  • 3FAE5DA3-24C3-4431-95B6-13F1CE5E2F3A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by KoheiKanagu** [comment]
The problem was resolved by specifying `TextScaler.noScaling` as follows:

```dart
showDatePicker(
  context: context,
  firstDate: DateTime(2023),
  lastDate: DateTime(2024),
  builder: (context, child) => MediaQuery(
    data: MediaQuery.of(context).copyWith(
      textScaler: TextScaler.noScaling,
    ),
    child: child!,
  ),
);
```

There seems to be an issue with `isFullyPortrait` added in #133327

The related issue is probably #138696

**Comment by huycozy** [comment]
Hi @KoheiKanagu 
I checked this on `iPhone 7, iOS 15.8` (physical device) but the issue is not there. 

I also checked this on iPhone 15 Pro, iOS 17.0 (emulator) but the issue is also not reproducible (this is similar to your result as stated above).

<details>
<summary>Demo - iPhone 7, iOS 15.8</summary>

https://github.com/flutter/flutter/assets/104349824/193440e6-b5ff-471d-b86f-f3ae9987f165
</details>

I wonder if this issue is only reproducible on iOS 17? Unfortunately I don't have such a device to check this.

Could you also help to check this on previous release 3.13.9?

**Comment by KoheiKanagu** [comment]
@huycozy Thank you for checking.

Sorry, all my devices are iOS 17 so I cannot test on other versions of iOS.

When tested on iPhone 11 Pro with Flutter v3.13.9, there were layout issues, but the TextField was displayed.
<https://github.com/KoheiKanagu/date_picker_dialog/tree/flutter_3.13.9>

https://github.com/flutter/flutter/assets/6175794/eee49375-337c-4913-a77b-16782ead0a18

<details><summary>Logs</summary>

```dart
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 2.8 pixels on the bottom.

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///Users/kingu/Develop/date_picker_dialog/lib/main.dart:12:18

To inspect this widget in Flutter DevTools, visit:
http://127.0.0.1:9100/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A51258%2FE75UJAeM6O8%3D%2F&inspectorRef=inspector-0

The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be
seen. If the content is legitimately bigger than the available space, consider clipping it with a
ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
like a ListView.
The specific RenderFlex in question is: RenderFlex#29677 OVERFLOWING:
  needs compositing
  creator: Column ← Semantics ← _FocusInheritedScope ← Focus ← Shortcuts ← Padding ← ConstrainedBox ←
    Container ← _FormScope ← WillPopScope ← Form-[LabeledGlobalKey<FormState>#0038e] ← Expanded ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=232.0, h=50.4)
  size: Size(232.0, 50.4)
  direction: vertical
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: A RenderFlex overflowed by 2.8 pixels on the bottom.
```
</details>

An interesting point is that the layout issue did not occur in the iOS simulator, but only on the physical device.

https://github.com/flutter/flutter/assets/6175794/e20fa30a-46ec-4570-9978-a64f9936160c

**Comment by KoheiKanagu** [comment]
@huycozy I was able to reproduce the issue on the iOS simulator as well.
When reducing the text size, problems occur.

https://github.com/flutter/flutter/assets/6175794/c626ea92-937c-447e-9246-c276152e4a5c

My iOS device had reduced text size, which seems to have caused the problem.

**Comment by huycozy** [comment]
Thanks for investigating this. Now I can reproduce the issue. 

Also, if I toggle the entry mode one more time (switch to calendar mode), it outputs an exception as below:

<details>
<summary>Exception log</summary>

```console
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following _TypeError was thrown while handling a gesture:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _DatePickerDialogState._handleEntryModeToggle.<anonymous closure> (package:flutter/src/material/date_picker.dart:467:32)
flutter: #1      State.setState (package:flutter/src/widgets/framework.dart:1203:30)
flutter: #2      _DatePickerDialogState._handleEntryModeToggle (package:flutter/src/material/date_picker.dart:460:5)
flutter: #3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
flutter: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:291:24)
flutter: #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
flutter: #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
flutter: #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279:7)
flutter: #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
flutter: #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492:20)
flutter: #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
flutter: #11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
flutter: #12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
flutter: #13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
flutter: #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
flutter: #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
flutter: #16     _invoke1 (dart:ui/hooks.dart:328:13)
flutter: #17     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:409:7)
flutter: #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
flutter:
flutter: Handler: "onTap"
flutter: Recognizer:
flutter:   TapGestureRecognizer#df215
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2
flutter: Another exception was thrown: Null check operator used on a null value
```
</details>

<details>
<summary>Demo video</summary>


https://github.com/flutter/flutter/assets/104349824/6e1df7b0-288f-4884-a2b1-b9abe8dcc504


</details>

Reproduced this on the latest stable and master channels. On the previous stable 3.13.9, the issue doesn't appear.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (9 hours ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe Patch 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.17.0-17.0.pre.47, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.17.0-17.0.pre.47 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7a0508e5de (10 minutes ago), 2023-11-28 22:01:04 -0500
    • Engine revision 4beaa1195b
    • Dart version 3.3.0 (build 3.3.0-170.0.dev)
    • DevTools version 2.30.0-dev.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe Patch 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by HansMuller** [comment]
CC @LongCatIsLooong
