### ISSUE TITLE
Text widget assert error not printing call stack

### ISSUE THREAD

**Issue by dudeofawesome** [flutter/flutter#13930]
## Steps to Reproduce

> Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

I have a text widget somewhere in my Flutter app that is getting a `null` value for `data`. The default error logging did not provide any call stack, making it very difficult to track down the error. Running with `-v` showed a full call stack, allowing me to easily find and fix the issue.

**It seems like it would make sense to provide the full stack by default.**

> If the problem is with your application's rendering, please attach a screenshot and any relevant source code.

![image](https://user-images.githubusercontent.com/1683595/34539833-733f25a0-f08f-11e7-97a1-b96d9852fb6c.png)

> If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

> Run your application with `flutter run` and attach all the log output.

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
'package:flutter/src/widgets/text.dart': Failed assertion: line 212 pos 15: 'data != null': is not
true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
```

When run in verbose mode, this stack was provided
<details><summary>Click to expand</summary><p>

```
[        ] When the exception was thrown, this was the stack:
[   +4 ms] [DEVICE LOG] 2018-01-03 14:16:20.904999-0700  localhost Runner[76476]: (Flutter) #2      new Text (package:flutter/src/widgets/text.dart:212:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.905168-0700  localhost Runner[76476]: (Flutter) #3      Comment.build (package:hn_flutter/components/comment.dart:107:26)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.905288-0700  localhost Runner[76476]: (Flutter) #4      StoreWatcherState.build (package:flutter_flux/src/store_watcher.dart:81:19)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.905407-0700  localhost Runner[76476]: (Flutter) #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3690:27)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.905506-0700  localhost Runner[76476]: (Flutter) #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3602:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.905617-0700  localhost Runner[76476]: (Flutter) #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.905726-0700  localhost Runner[76476]: (Flutter) #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.905846-0700  localhost Runner[76476]: (Flutter) #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.906018-0700  localhost Runner[76476]: (Flutter) #10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4317:32)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.906166-0700  localhost Runner[76476]: (Flutter) #11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.906288-0700  localhost Runner[76476]: (Flutter) #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.906394-0700  localhost Runner[76476]: (Flutter) #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.906494-0700  localhost Runner[76476]: (Flutter) #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.906587-0700  localhost Runner[76476]: (Flutter) #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.906698-0700  localhost Runner[76476]: (Flutter) #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.906799-0700  localhost Runner[76476]: (Flutter) #17     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.906922-0700  localhost Runner[76476]: (Flutter) #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.907059-0700  localhost Runner[76476]: (Flutter) #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.907186-0700  localhost Runner[76476]: (Flutter) #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.907297-0700  localhost Runner[76476]: (Flutter) #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.907409-0700  localhost Runner[76476]: (Flutter) #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.907519-0700  localhost Runner[76476]: (Flutter) #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.907666-0700  localhost Runner[76476]: (Flutter) #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.907826-0700  localhost Runner[76476]: (Flutter) #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.907919-0700  localhost Runner[76476]: (Flutter) #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.908336-0700  localhost Runner[76476]: (Flutter) #27     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:696:34)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.908495-0700  localhost Runner[76476]: (Flutter) #28     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:665:7)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.908656-0700  localhost Runner[76476]: (Flutter) #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.908836-0700  localhost Runner[76476]: (Flutter) #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.909023-0700  localhost Runner[76476]: (Flutter) #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.909234-0700  localhost Runner[76476]: (Flutter) #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.909479-0700  localhost Runner[76476]: (Flutter) #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.909946-0700  localhost Runner[76476]: (Flutter) #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.910461-0700  localhost Runner[76476]: (Flutter) #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.910827-0700  localhost Runner[76476]: (Flutter) #36     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4317:32)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.911499-0700  localhost Runner[76476]: (Flutter) #37     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.912044-0700  localhost Runner[76476]: (Flutter) #38     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:182:17)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.912320-0700  localhost Runner[76476]: (Flutter) #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.912496-0700  localhost Runner[76476]: (Flutter) #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.912763-0700  localhost Runner[76476]: (Flutter) #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.912979-0700  localhost Runner[76476]: (Flutter) #42     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.913178-0700  localhost Runner[76476]: (Flutter) #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.913328-0700  localhost Runner[76476]: (Flutter) #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.913433-0700  localhost Runner[76476]: (Flutter) #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.913618-0700  localhost Runner[76476]: (Flutter) #46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.913741-0700  localhost Runner[76476]: (Flutter) #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.913845-0700  localhost Runner[76476]: (Flutter) #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.913945-0700  localhost Runner[76476]: (Flutter) #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.914036-0700  localhost Runner[76476]: (Flutter) #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.914162-0700  localhost Runner[76476]: (Flutter) #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.914282-0700  localhost Runner[76476]: (Flutter) #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.914385-0700  localhost Runner[76476]: (Flutter) #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[   +3 ms] [DEVICE LOG] 2018-01-03 14:16:20.914525-0700  localhost Runner[76476]: (Flutter) #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.914633-0700  localhost Runner[76476]: (Flutter) #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.914765-0700  localhost Runner[76476]: (Flutter) #56     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.914877-0700  localhost Runner[76476]: (Flutter) #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.914980-0700  localhost Runner[76476]: (Flutter) #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.915256-0700  localhost Runner[76476]: (Flutter) #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.915430-0700  localhost Runner[76476]: (Flutter) #60     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.915584-0700  localhost Runner[76476]: (Flutter) #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.915695-0700  localhost Runner[76476]: (Flutter) #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.915835-0700  localhost Runner[76476]: (Flutter) #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.915950-0700  localhost Runner[76476]: (Flutter) #64     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.916051-0700  localhost Runner[76476]: (Flutter) #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.916156-0700  localhost Runner[76476]: (Flutter) #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.916276-0700  localhost Runner[76476]: (Flutter) #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.916400-0700  localhost Runner[76476]: (Flutter) #68     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.916520-0700  localhost Runner[76476]: (Flutter) #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.916646-0700  localhost Runner[76476]: (Flutter) #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.916762-0700  localhost Runner[76476]: (Flutter) #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.916892-0700  localhost Runner[76476]: (Flutter) #72     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.917012-0700  localhost Runner[76476]: (Flutter) #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.917173-0700  localhost Runner[76476]: (Flutter) #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.917294-0700  localhost Runner[76476]: (Flutter) #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.917429-0700  localhost Runner[76476]: (Flutter) #76     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.917552-0700  localhost Runner[76476]: (Flutter) #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.917677-0700  localhost Runner[76476]: (Flutter) #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.917849-0700  localhost Runner[76476]: (Flutter) #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.918020-0700  localhost Runner[76476]: (Flutter) #80     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.918201-0700  localhost Runner[76476]: (Flutter) #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.918326-0700  localhost Runner[76476]: (Flutter) #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.918435-0700  localhost Runner[76476]: (Flutter) #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.918578-0700  localhost Runner[76476]: (Flutter) #84     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.918686-0700  localhost Runner[76476]: (Flutter) #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.918800-0700  localhost Runner[76476]: (Flutter) #86     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4317:32)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.918948-0700  localhost Runner[76476]: (Flutter) #87     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.919076-0700  localhost Runner[76476]: (Flutter) #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.919240-0700  localhost Runner[76476]: (Flutter) #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.919367-0700  localhost Runner[76476]: (Flutter) #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.919520-0700  localhost Runner[76476]: (Flutter) #91     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.919645-0700  localhost Runner[76476]: (Flutter) #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.919875-0700  localhost Runner[76476]: (Flutter) #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.920012-0700  localhost Runner[76476]: (Flutter) #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.920133-0700  localhost Runner[76476]: (Flutter) #95     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.920257-0700  localhost Runner[76476]: (Flutter) #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.920409-0700  localhost Runner[76476]: (Flutter) #97     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.920582-0700  localhost Runner[76476]: (Flutter) #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.920752-0700  localhost Runner[76476]: (Flutter) #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.920880-0700  localhost Runner[76476]: (Flutter) #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.921061-0700  localhost Runner[76476]: (Flutter) #101    StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.921193-0700  localhost Runner[76476]: (Flutter) #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.921340-0700  localhost Runner[76476]: (Flutter) #103    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.921568-0700  localhost Runner[76476]: (Flutter) #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.921716-0700  localhost Runner[76476]: (Flutter) #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.921933-0700  localhost Runner[76476]: (Flutter) #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.922049-0700  localhost Runner[76476]: (Flutter) #107    StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.922152-0700  localhost Runner[76476]: (Flutter) #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.922407-0700  localhost Runner[76476]: (Flutter) #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.922580-0700  localhost Runner[76476]: (Flutter) #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.922710-0700  localhost Runner[76476]: (Flutter) #111    StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.922832-0700  localhost Runner[76476]: (Flutter) #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.922936-0700  localhost Runner[76476]: (Flutter) #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.923112-0700  localhost Runner[76476]: (Flutter) #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.923252-0700  localhost Runner[76476]: (Flutter) #115    ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.923399-0700  localhost Runner[76476]: (Flutter) #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.923544-0700  localhost Runner[76476]: (Flutter) #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.923790-0700  localhost Runner[76476]: (Flutter) #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.923919-0700  localhost Runner[76476]: (Flutter) #119    ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.924034-0700  localhost Runner[76476]: (Flutter) #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.924177-0700  localhost Runner[76476]: (Flutter) #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.924288-0700  localhost Runner[76476]: (Flutter) #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.924484-0700  localhost Runner[76476]: (Flutter) #123    StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.924605-0700  localhost Runner[76476]: (Flutter) #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.924741-0700  localhost Runner[76476]: (Flutter) #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.924938-0700  localhost Runner[76476]: (Flutter) #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.925053-0700  localhost Runner[76476]: (Flutter) #127    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2210:33)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.925199-0700  localhost Runner[76476]: (Flutter) #128    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:612:20)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.925338-0700  localhost Runner[76476]: (Flutter) #129    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.925521-0700  localhost Runner[76476]: (Flutter) #130    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:921:15)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.925656-0700  localhost Runner[76476]: (Flutter) #131    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:861:9)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.925816-0700  localhost Runner[76476]: (Flutter) #132    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:773:5)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.925932-0700  localhost Runner[76476]: (Flutter) #133    _invoke (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:120)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.926132-0700  localhost Runner[76476]: (Flutter) #134    _drawFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:109)
[        ] [DEVICE LOG] 2018-01-03 14:16:20.926285-0700  localhost Runner[76476]: (Flutter) (elided 2 frames from class _Assert
```

</p></details>
<br />
<br />

## Flutter Doctor

> Paste the output of running `flutter doctor` here.
```
 ~/G/hn_flutter   master ±  flutter doctor
[✓] Flutter (on Mac OS X 10.13.1 17B1003, locale en-US, channel master)
    • Flutter at /Users/dudeofawesome/Library/Developer/flutter
    • Framework revision 70b32e85a3 (12 days ago), 2017-12-22 14:58:53 -0800
    • Engine revision 7c126001d8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.9e8a3e2d31621c1bdf6139d068e7898a2ac2ab5a

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/dudeofawesome/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/dudeofawesome/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • iPhone X • 072375FC-E01B-417E-88FA-2D94A7DE6993 • ios • iOS 11.2 (simulator)
```

**Comment by Hixie** [comment]
I believe this was a typo in our regular expression for showing the logs on iOS, which @xster fixed recently.

**Comment by dudeofawesome** [comment]
So this would be fixed by upgrading my Flutter install?

**Comment by xster** [comment]
Likely the same issue since it's on a simulator. If you're on the master branch, it'll be fixed with `flutter upgrade`. It will be rolled into alpha branch soon. 

(hn client in flutter \o/)

**Comment by xster** [comment]
Dupe is #13769
