### ISSUE TITLE
I want use flutter_sound in background[BUG]:

### ISSUE THREAD

**Issue by ImanGhasemiArani** [flutter/flutter#139309]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I User Background service and open player with Flutter_sound package

### Expected results

I want use player/recorder as stream in ```background_service``` in foreground mode. but when open player/recorder get exception that is ```MissingPluginException(No implementation found for method resetPlugin on channel com.dooboolab.flutter_sound_player)```.

 I tested it on android.

### Actual results

.

### Code sample

<details><summary> no code</summary>

```dart
no code
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
I/flutter (18930): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): │ #0   new FlutterSoundPlayer (package:flutter_sound/public/flutter_sound_player.dart:132:13)
I/flutter (18930): │ #1   BackgroundService.startCall.<anonymous closure> (package:wifoneapp/services/background_service.dart:176:36)
I/flutter (18930): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (18930): │ 🐛 ctor: FlutterSoundPlayer()
I/flutter (18930): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:511:13)
I/flutter (18930): │ #1   FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:504:17)
I/flutter (18930): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (18930): │ 🐛 FS:---> openAudioSession
I/flutter (18930): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:524:15)
I/flutter (18930): │ #1   FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:504:17)
I/flutter (18930): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (18930): │ 🐛 Resetting flutter_sound Player Plugin
I/flutter (18930): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/flutter (18930): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method resetPlugin on channel com.dooboolab.flutter_sound_player)
E/flutter (18930): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #1      FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:526:7)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #2      FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:504:11)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #4      FlutterSoundPlayer.openPlayer (package:flutter_sound/public/flutter_sound_player.dart:503:5)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #5      BackgroundService.startCall.<anonymous closure> (package:wifoneapp/services/background_service.dart:177:7)
E/flutter (18930): <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22631.2715], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
The way `background_service` is implemented requires specific code to wire up plugin support, as shown in the plugin's README. If it does not work correctly, that would be a bug in the plugin which you would need to report to the plugin's developer; Flutter itself does not automatically register plugins in dynamically-generated engine instances.
