### ISSUE TITLE
[TLHC] slow platform view loading time compared to HC

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#139354]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

To reproduce the issue, compile this sample repo
https://github.com/delfme/flutter-native-text-input-repo

Switch between HC and TLHC from here:
https://github.com/delfme/flutter-native-text-input-repo/blob/294c630a8db70f5308016d4f1055cd7adc91ff7d/flutter-native-text-input/lib/flutter_native_text_input.dart#L575

Tap button to open demo screen. You will see that EditText is rendered with 1 sec delay on the first run.
Issue doesn't occur with HC.

### Expected results

TLHC rendering performance should be equal, if not better, than HC.

### Actual results

TLHC rendering is slow.

### Code sample

https://github.com/delfme/flutter-native-text-input-repo

### Screenshots or Video

HC - fast

https://github.com/flutter/flutter/assets/53510751/11f1e5d6-b9f2-4d74-81f7-f68682370ff2

TLHC - slow

https://github.com/flutter/flutter/assets/53510751/a93430a8-2340-42a4-a5cf-606fd388ab3f

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.17.0-17.0.pre.25, on macOS 12.6.5 21G531 darwin-arm64, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
✗ cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by johnmccutchan** [comment]
@jonahwilliams could this be related to #129742 ?

**Comment by jonahwilliams** [comment]
Possibly, this could be tested by running with `--dart-define=flutter.benchmarks.force_disable_snapshot=true` @delfme

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate the reported behavior using details provided in original description.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.16.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.16.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (12 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.18.0-1.0.pre.24, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.18.0-1.0.pre.24 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18f365d6da (7 hours ago), 2023-12-03 17:37:36 -0500
    • Engine revision 69cbf87f33
    • Dart version 3.3.0 (build 3.3.0-186.0.dev)
    • DevTools version 2.30.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by johnmccutchan** [comment]
> Will try to open another issue that might be related to this first-frame issue. Coz with Impeller android (vulcan backend) sometimes the first frame is skipped also when rendering images (not just platform view). Is this issue already known to you guys?

Please file a separate issue

**Comment by johnmccutchan** [comment]
I can't reproduce this on HEAD.

**Comment by johnmccutchan** [comment]
What mode were you running the app (debug, profile, or release)?

What device or emulator and what API version were you using?

On Android API 34 they both behave the same.

**Comment by delfme** [comment]
Hello @darshankawar , since you were able to replicate the issue, can you please look into this? Coz Im out travelling and cannot check it soon.

**Comment by delfme** [comment]
Hello @johnmccutchan, I see things have changed with latest master.

Here is my report:
1) I no longer see the 1 sec delay in rendering textfield

2) With android 32, app crashes, here logs
```
Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
E/flutter (  842): [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Image is already closed
E/flutter (  842):      at android.media.Image.throwISEIfImageIsInvalid(Image.java:79)
E/flutter (  842):      at android.media.ImageReader$SurfaceImage.getFence(ImageReader.java:1245)
E/flutter (  842):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.waitOnFence(Unknown Source:0)
E/flutter (  842):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.maybeWaitOnFence(Unknown Source:14)
E/flutter (  842):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.acquireLatestImage(Unknown Source:10)
E/flutter (  842): 
F/flutter (  842): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1621)] Check failed: fml::jni::CheckException(env). 
E/flutter ( 2067): [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Image is already closed
E/flutter ( 2067):      at android.media.Image.throwISEIfImageIsInvalid(Image.java:79)
E/flutter ( 2067):      at android.media.ImageReader$SurfaceImage.getFence(ImageReader.java:1245)
E/flutter ( 2067):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.waitOnFence(Unknown Source:0)
E/flutter ( 2067):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.maybeWaitOnFence(Unknown Source:14)
E/flutter ( 2067):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.acquireLatestImage(Unknown Source:10)
E/flutter ( 2067): 
F/flutter ( 2067): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1621)] Check failed: fml::jni::CheckException(env). 
E/flutter ( 3024): [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Image is already closed
E/flutter ( 3024):      at android.media.Image.throwISEIfImageIsInvalid(Image.java:79)
E/flutter ( 3024):      at android.media.ImageReader$SurfaceImage.getFence(ImageReader.java:1245)
E/flutter ( 3024):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.waitOnFence(Unknown Source:0)
E/flutter ( 3024):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.maybeWaitOnFence(Unknown Source:14)
E/flutter ( 3024):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.acquireLatestImage(Unknown Source:10)
E/flutter ( 3024): 
F/flutter ( 3024): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1621)] Check failed: fml::jni::CheckException(env). 
E/flutter ( 3976): [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Image is already closed
E/flutter ( 3976):      at android.media.Image.throwISEIfImageIsInvalid(Image.java:79)
E/flutter ( 3976):      at android.media.ImageReader$SurfaceImage.getFence(ImageReader.java:1245)
E/flutter ( 3976):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.waitOnFence(Unknown Source:0)
E/flutter ( 3976):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.maybeWaitOnFence(Unknown Source:14)
E/flutter ( 3976):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.acquireLatestImage(Unknown Source:10)
E/flutter ( 3976): 
F/flutter ( 3976): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1621)] Check failed: fml::jni::CheckException(env). 
E/flutter ( 4190): [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Image is already closed
E/flutter ( 4190):      at android.media.Image.throwISEIfImageIsInvalid(Image.java:79)
E/flutter ( 4190):      at android.media.ImageReader$SurfaceImage.getFence(ImageReader.java:1245)
E/flutter ( 4190):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.waitOnFence(Unknown Source:0)
E/flutter ( 4190):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.maybeWaitOnFence(Unknown Source:14)
E/flutter ( 4190):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.acquireLatestImage(Unknown Source:10)
E/flutter ( 4190): 
F/flutter ( 4190): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1621)] Check failed: fml::jni::CheckException(env). 
```

3) With android api 34 app crashes with this log
```
E/flutter ( 5215): [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Image is already closed
E/flutter ( 5215):      at android.media.Image.throwISEIfImageIsInvalid(Image.java:79)
E/flutter ( 5215):      at android.media.ImageReader$SurfaceImage.getFence(ImageReader.java:1245)
E/flutter ( 5215):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.waitOnFence(Unknown Source:0)
E/flutter ( 5215):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.maybeWaitOnFence(Unknown Source:14)
E/flutter ( 5215):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.acquireLatestImage(Unknown Source:10)
E/flutter ( 5215): 
F/flutter ( 5215): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1621)] Check failed: fml::jni::CheckException(env). 
```

4) I see no issues or crashes with HC, but now with HC I now get a screen glitch when entering or exiting the screen, at the being or end of the screen navigation, see vid below. It doesn't occur at every tap.

Video of sample app
https://github.com/flutter/flutter/assets/53510751/f2c67dba-a6ac-4127-8d60-23ff7fb4d71b

Our app video
https://github.com/flutter/flutter/assets/53510751/833557ea-0ea1-441f-aa76-678165ad514d

**Comment by delfme** [comment]
With TLHC, the glitch during screen animation can occur also at the begin of the animation.

I couldnt check https://github.com/flutter/flutter/issues/139230 due to the crashes.

LMK when you want me to check things again.

**Comment by delfme** [comment]
@johnmccutchan I was able to debug the glitch issue.
It is caused by the override `getRenderMode()` in `MainActivity.kt`
```
  override fun getRenderMode(): RenderMode {
        return RenderMode.texture
    }
```

To quick recap:
We added `getRenderMode()` in order to get the magnifier lens (which didnt work with TLHC).
However, that override slows down performance and causes that glitch during screen animation.

I confirm that we have no issues with HC if `getRenderMode()` is removed.

**Issues with TLHC:**
1) Magnifier lens is lost unless we add `getRenderMode()`. But that causes screen glitch during a screen animation and slow down performance.
2) https://github.com/flutter/flutter/issues/139230
3) crashes on both android api 32 and 34. Tested with master 3.19.0-9.0.pre.204, Xiaomi Mi Lite 5GG, Vulcan backend, release mode.

Video showing flawless sample code when using HC.

https://github.com/flutter/flutter/assets/53510751/9e58bf5c-96b9-40b1-b9bf-aff79bd89436

**Comment by johnmccutchan** [comment]
The crashes were fixed yesterday. Apologies for the breakage to master.

For other issues with platform views, can you please file separate issues and not keep appending them to this issue?

**Comment by johnmccutchan** [comment]
As reported by @delfme the slow loading issue can't be reproduced anymore.
