### ISSUE TITLE
White screen when reopen app after close with back button 

### ISSUE THREAD

**Issue by juani21** [flutter/flutter#13948]
Hi, i have this code:

```dart
runApp(new MaterialApp(
      //home: new HomePage(),
      theme: appTheme,
      home: new StartScreen(),
    )
    );

class StartScreen extends StatefulWidget {
  @override
  _StartScreenState createState() => new _StartScreenState();
}

class _StartScreenState extends State<StartScreen> {

  bool isFirstLaunch = true;

  @override
  Widget build(BuildContext context) {
    if (isFirstLaunch) {
      return new Scaffold(
        body: new Center(
          child: new Row(
            children: <Widget>[
              new IconButton(
                  icon: new Icon(Icons.satellite),
                  onPressed: () {
                    setState(() {
                      isFirstLaunch = false;
                    });
                  }
              )
            ],
          ),
        ),
      );
    }
    return new Scaffold(
      body: new Text("HELLO"),
    );
  }
}
```

When close the app with back button and reopen i have white screen with this error:
```
Performing full restart...
Restarted app in 1.638ms.
D/EGL_emulation(17858): eglMakeCurrent: 0xb31055a0: ver 2 0 (tinfo 0xb314c3d0)
I/FlutterActivityDelegate(17858): onResume setting current activity to this
D/EGL_emulation(17858): eglCreateContext: 0x9241e4e0: maj 2 min 0 rcv 2
D/EGL_emulation(17858): eglMakeCurrent: 0x9241e4e0: ver 2 0 (tinfo 0xa5936080)
D/EGL_emulation(17858): eglMakeCurrent: 0x9241e4e0: ver 2 0 (tinfo 0xa59367e0)
E/flutter (17858): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (17858): 'package:flutter/src/material/app.dart': Failed assertion: line 112: 'home == null ||
E/flutter (17858):       !routes.containsKey(Navigator.defaultRouteName)': If the home property is specified, the routes table cannot include an entry for "/", since it would be redundant.
E/flutter (17858): #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
E/flutter (17858): #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
E/flutter (17858): #2      new MaterialApp (package:flutter/src/material/app.dart:112)
E/flutter (17858): #3      new Routes (package:ordine_app/Routes.dart:18)
E/flutter (17858): #4      main (file://********/lib/main.dart:5)
E/flutter (17858): #5      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
E/flutter (17858): #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**FLUTTER DOCTOR**

```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale it-IT, channel alpha)
    • Flutter at /Users/gio/flutter
    • Framework revision 8f65fec5f5 (3 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/gio/Library/Android/sdk
    • Android NDK at /Users/gio/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by passsy** [comment]
When you use hot reload during development those changes are not persistent. When the app gets restarted (press back button and open again) you lose all changes applied with hot reload. The source code running now is the one of the first complete restart.

Reinstall the app and you'll be able to restart the app correctly without this error.

**Comment by juani21** [comment]
the problem persist, i try to create another project and the code work....i dont now because...

**Comment by juani21** [comment]
no it is gone

**Comment by zoechi** [comment]
I'll close then. Add a comment if you encounter it again and I'll reopen.
