### ISSUE TITLE
[ERR] "`!` operator used on `null` value", in `OverlayEntry.remove`, via `EditableTextState.dispose`, from `TextField`

### ISSUE THREAD

**Issue by gintominto5329** [flutter/flutter#139459]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

We use a **meta-framework**, instead of directly using flutter, its source-code is private.

The meta-framework, does NOT use `Navigator*`, `*App`(`WidgetsApp` etc), `Material*`(except `TextField`), `Cupertino*`(except `ProgressIndicator`), classes. We have all their equivalents, in-house.

So I can only provide, flutter side code; Hope you understand.

Flutter-side code (does NOT run):
```
page: Overlay(
  initialEntries: [
    OverlayEntry(
      builder: (final _) => //
          Localizations(
        locale: app_locale,
        delegates: const <LocalizationsDelegate<Object>>[
          DefaultWidgetsLocalizations.delegate,
          DefaultMaterialLocalizations.delegate,
        ],
        child: page_foundation/* like Scaffold */(
          listing_generated/* like ListView.generate */(
            scroll_manager: scroll_manager,
            page_title: component_page_title_aligned_center(
              "Demo page",
            ),
            items_count: 1,
            item_build: (final _, final i) => //
                Material(
              color: Colors.transparent,
              child: TextField(
                decoration: null,
                controller: text_controller,
                focusNode: focus_controller,
                style: component_text_style(
                  font_color: input_font_color,
                  font_size: input_font_size,
                  /*font_weight: FontWeight.w600,*/
                  font_family: input_font_family,
                ),
                cursorOpacityAnimates: false,
                cursorColor: color_foreground_dim,
                cursorRadius: radius_1,
                keyboardType: input_type,
                textInputAction: input_submit_indicator,
                textCapitalization: input_capitalization,
                autofocus: true,
                maxLines: 10,
                minLines: 1,
                onChanged: input_handle,
                onSubmitted: input_submit,
                inputFormatters: <TextInputFormatter>[
                  LengthLimitingTextInputFormatter(
                    input_wide_chars_count_max,
                    maxLengthEnforcement: MaxLengthEnforcement.enforced,
                  ),
                  FilteringTextInputFormatter(
                    RegExp(input_filter.regex_string),
                    allow: input_filter.b_allow,
                  ),
                ],
                keyboardAppearance: (app_interface_b_dark //
                    ? Brightness.dark
                    : Brightness.light),
                scrollPhysics: scroll_physics_natural,
              ),
            ),
            floating: navigation_bottom_stored(
              pages: pages,
              initial_id: 1,
            ),
            floating_padding_bottom: 0,
          ),
        ),
      ),
    ),
  ],
),
```

Trace:
```
I/flutter (27969): #0      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:189)
I/flutter (27969): #1      SelectionOverlay.hide (package:flutter/src/widgets/text_selection.dart:1478)
I/flutter (27969): #2      SelectionOverlay.dispose (package:flutter/src/widgets/text_selection.dart:1509)
I/flutter (27969): #3      TextSelectionOverlay.dispose (package:flutter/src/widgets/text_selection.dart:588)
I/flutter (27969): #4      EditableTextState.dispose (package:flutter/src/widgets/editable_text.dart:2948)
I/flutter (27969): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5689)
I/flutter (27969): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2076)
I/flutter (27969): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074)
I/flutter (27969): #8      RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1308)
I/flutter (27969): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072)
I/flutter (27969): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074)
I/flutter (27969): #11     _RawViewElement.visitChildren (package:flutt
```

I traced the "Trace", the problematic part is:
```
  void /*OverlayEntry.*/remove() {
    //...
    final OverlayState overlay = _overlay!;
    _overlay = null;
    //...
  }
```

### Expected results

Error is NOT thrown

### Flutter version

**Master** channel, updated **yesterday**.

<details><summary>Doctor output</summary>

```console
[  +45 ms] [!] Flutter (Channel master, 3.18.0-1.0.pre.16, on Debian GNU/Linux 12 (bookworm) 6.1.0-13-amd64, locale en_US.UTF-8)
[        ]     • Flutter version 3.18.0-1.0.pre.16 on channel master at /home/_/bin/flutter
[        ]     ! The flutter binary is not on your path. Consider adding /home/_/bin/flutter/bin to your path.
[        ]     ! The dart binary is not on your path. Consider adding /home/_/bin/flutter/bin to your path.
[        ]     • Upstream repository https://github.com/flutter/flutter.git
[        ]     • Framework revision 12dfd99a3f (2 days ago), 2023-12-02 02:20:06 -0500
[        ]     • Engine revision d441f08705
[        ]     • Dart version 3.3.0 (build 3.3.0-180.0.dev)
[        ]     • DevTools version 2.30.0
[   +1 ms]     • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
[  +73 ms] List of devices attached
           192.168.1.4:41377      device product:capri_retailin model:moto_g_10__power device:capri transport_id:1
[   +8 ms] /home/_/bin/android/sdk/platform-tools/adb -s 192.168.1.4:41377 shell getprop
[ +321 ms] ro.hardware = qcom
[  +16 ms] executing: /home/_/bin/android/sdk/platform-tools/adb devices -l
[  +24 ms] List of devices attached
           192.168.1.4:41377      device product:capri_retailin model:moto_g_10__power device:capri transport_id:1
[+3348 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[        ]     • Android SDK at /home/_/bin/android/sdk
[        ]     • Platform android-34, build-tools 34.0.0
[        ]     • Java binary at: /home/_/bin/android/studio/jbr/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
[        ]     • All Android licenses accepted.
[        ] [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
[        ]     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[        ] [✓] Linux toolchain - develop for Linux desktop
[        ]     • Debian clang version 14.0.6
[        ]     • cmake version 3.25.1
[        ]     • ninja version 1.11.1
[        ]     • pkg-config version 1.8.1
[        ] [✓] Android Studio (version 2022.3)
[        ]     • Android Studio at /home/_/bin/android/studio
[        ]     • Flutter plugin version 75.1.2
[        ]     • Dart plugin can be installed from:
[        ]       🔨 https://plugins.jetbrains.com/plugin/6351-dart
[        ]     • android-studio-dir = /home/_/bin/android/studio
[        ]     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
[        ] [✓] Connected device (2 available)
[        ]     • moto g 10 power (mobile) • 192.168.1.4:41377 • android-arm64 • Android 11 (API 30)
[        ]     • Linux (desktop)          • linux             • linux-x64     • Debian GNU/Linux 12 (bookworm) 6.1.0-13-amd64
[        ] [✓] Network resources
[        ]     • All expected network resources are available.
[        ] ! Doctor found issues in 2 categories.
```

</details>

**Comment by gintominto5329** [comment]
Its a native app, for Android, Ios systems

**Comment by gintominto5329** [comment]
I cannot share more source-code, its not legal for me.

the "Trace" is enough i think, because, why is `!` being used, instead of `?`

**Comment by huycozy** [comment]
As I mentioned above, you should provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) (please visit this link) that demonstrates the issue you're facing, not your production/project code. This will allow others to understand the problem and help you find a solution without exposing your entire codebase.

Regarding the stack trace, it's important to note that it may not always provide the complete picture of the issue. In your case, the problematic part you shared is just the code inside the classes that are used. To fully understand what's causing the issue, we need to see how these classes are being used and what other code is interacting with them.

**Comment by gintominto5329** [comment]
hi

Working(on Android-11) code:
```dart
import "package:flutter/material.dart";

void main() {
  final focus_controller = FocusNode(), text_controller = TextEditingController();

  runApp(
    ScrollConfiguration(
      behavior: const MaterialScrollBehavior(),
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: Stack(
          textDirection: TextDirection.ltr,
          children: <Widget>[
            Overlay(
              initialEntries: [
                OverlayEntry(
                  builder: (final _) => //
                      Localizations(
                    locale: const Locale("en", "US"),
                    delegates: const <LocalizationsDelegate<Object>>[
                      DefaultWidgetsLocalizations.delegate,
                      DefaultMaterialLocalizations.delegate,
                    ],
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(
                                top: 50,
                                left: 20,
                                right: 20,
                              ),
                              child: SizedBox(
                                width: double.maxFinite,
                                child: ColoredBox(
                                  color: Colors.grey,
                                  child: Material(
                                    color: Colors.transparent,
                                    child: TextField(
                                      decoration: null,
                                      controller: text_controller,
                                      focusNode: focus_controller,
                                      cursorColor: Colors.black,
                                      keyboardType: TextInputType.text,
                                      textInputAction: TextInputAction.done,
                                      style: const TextStyle(
                                        color: Colors.black,
                                        fontSize: 20,
                                      ),
                                      autofocus: true,
                                      maxLines: 10,
                                      minLines: 1,
                                      onSubmitted: (final String input) {
                                        print("submitted: \"$input\"");
                                      },
                                    ),
                                  ),
                                ),
                              ),
                            )
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    ),
  );
}
```
Steps:
1. Launch on Android 11 phone.
2. type "abc"
3. Long press the typed text
4. Check console, for error and trace

Error:
```
I/flutter (28608): Null check operator used on a null value
I/flutter (28608): #0      MaterialLocalizations.of (package:flutter/src/material/material_localizations.dart:684)
I/flutter (28608): #1      AdaptiveTextSelectionToolbar.getButtonLabel (package:flutter/src/material/adaptive_text_selection_toolbar.dart:212)
I/flutter (28608): #2      AdaptiveTextSelectionToolbar.getAdaptiveButtons (package:flutter/src/material/adaptive_text_selection_toolbar.dart:273)
I/flutter (28608): #3      AdaptiveTextSelectionToolbar.build (package:flutter/src/material/adaptive_text_selection_toolbar.dart:306)
I/flutter (28608): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550)
I/flutter (28608): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
I/flutter (28608): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (28608): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
I/flutter (28608): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
I/flutter (28608): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
I/flutter (28608): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
I/flutter (28608): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (28608): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
I/flutter (28608): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
I/flutter (28608): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
I/flutter (28608): #27     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
I/flutter (28608): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (28608): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
I/flutter (28608): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
I/flutter (28608): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
I/flutter (28608): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (28608): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
I/flutter (28608): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
I/flutter (28608): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (28608): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
I/flutter (28608): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
I/flutter (28608): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (28608): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
I/flutter (28608): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
I/flutter (28608): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (28608): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
I/flutter (28608): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
I/flutter (28608): #59     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
I/flutter (28608): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (28608): #62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
I/flutter (28608): #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
I/flutter (28608): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
I/flutter (28608): #67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
I/flutter (28608): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (28608): #70     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
I/flutter (28608): #71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
I/flutter (28608): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
I/flutter (28608): #73     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893)
I/flutter (28608): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
I/flutter (28608): #75     Element.updateChildren (package:flutter/src/widgets/framework.dart:4033)
I/flutter (28608): #76     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
I/flutter (28608): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
I/flutter (28608): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
I/flutter (28608): #79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
I/flutter (28608): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
I/flutter (28608): #81     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
I/flutter (28608): #82     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
I/flutter (28608): #83     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
I/flutter (28608): #84     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
I/flutter (28608): #85     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
I/flutter (28608): #86     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
I/flutter (28608): #87     _invoke (dart:ui/hooks.dart:312)
I/flutter (28608): #88     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:382)
I/flutter (28608): #89     _drawFrame (dart:ui/hooks.dart:283)
```

thanks

**Comment by huycozy** [comment]
Did you solve this issue or close it accidentally? Regarding the issue, looks like you can solve it by moving `Localizations` widget to the outermost. Let's try it and confirm if it works.
