### ISSUE TITLE
error in starting a app in debug mode.

### ISSUE THREAD

**Issue by vaidic-dodwani** [flutter/flutter#139440]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Confidential Code

### Expected results

Starts the app.

### Actual results

On starting the debug mode, the debug console shows
 ```D/ProfileInstaller(28916): Installing profile for com.plypicker.plypickerapp```
 and the flutter app crashes.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter debug_adapter

## exception

StateError: Bad state: Future already completed

```
#0      _Completer.completeError (dart:async/future_impl.dart:19:31)
#1      ThreadInfo.resolveUrisToPathsBatch.<anonymous closure> (package:dds/src/dap/isolate_manager.dart:1150:58)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#3      ThreadInfo.resolveUrisToPathsBatch (package:dds/src/dap/isolate_manager.dart:1150:20)
<asynchronous suspension>
#4      ThreadInfo.resolveUrisToPackageLibPathsBatch (package:dds/src/dap/isolate_manager.dart:1103:21)
<asynchronous suspension>
#5      IsolateManager._sendLibraryDebuggables (package:dds/src/dap/isolate_manager.dart:927:5)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      IsolateManager._configureIsolate (package:dds/src/dap/isolate_manager.dart:465:7)
<asynchronous suspension>
#8      IsolateManager.registerIsolate (package:dds/src/dap/isolate_manager.dart:258:7)
<asynchronous suspension>
#9      DartDebugAdapter._configureExistingIsolates.<anonymous closure> (package:dds/src/dap/adapters/dart.dart:790:11)
<asynchronous suspension>
#10     Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#11     DartDebugAdapter._configureExistingIsolates (package:dds/src/dap/adapters/dart.dart:783:5)
<asynchronous suspension>
#12     DartDebugAdapter._withErrorHandling (package:dds/src/dap/adapters/dart.dart:2596:14)
<asynchronous suspension>
#13     DartDebugAdapter.connectDebugger (package:dds/src/dap/adapters/dart.dart:716:5)
<asynchronous suspension>
#14     FlutterDebugAdapter._connectDebugger (package:flutter_tools/src/debug_adapters/flutter_adapter.dart:381:9)
<asynchronous suspension>
#15     FlutterDebugAdapter._handleDebugPort (package:flutter_tools/src/debug_adapters/flutter_adapter.dart:462:7)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.22631.2715], locale en-US)
    • Flutter version 3.16.2 on channel stable at C:\Coding\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (3 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\vaidi\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] VS Code (version 1.84.2)
    • VS Code at C:\Users\vaidi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • RMX3771 (mobile) • 6P6DTGMVW4SKHU89 • android-arm64  • Android 13 (API 33)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 119.0.6045.200
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 119.0.2151.93

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by darshankawar** [comment]
Based on the log, it seems similar to https://github.com/flutter/flutter/issues/137163, so please follow-up in that issue for further updates. Closing this as a duplicate.
