### ISSUE TITLE
Documentation error for LicenseEntryWithLineBreaks

### ISSUE THREAD

**Issue by justathoughtor2** [flutter/flutter#13947]
## Steps to Reproduce

Copy the code from the `LicenseEntryWithLineBreaks` sample available at https://docs.flutter.io/flutter/foundation/LicenseEntryWithLineBreaks-class.html into a new Flutter app's main method. If you omit the expected closing parentheses and semicolon, I expect you'll get additional errors, but that isn't what this is about; this is about the `yield` keyword being used outside of a generator function.

It took me a while to figure this out, as I am new to the Dart language. It should be a simple fix for the documentation.

Simply replace the code in the sample with something like...

```dart
LicenseRegistry.addLicense(() async* {
    yield new LicenseEntryWithLineBreaks(<String>['my_library'], '''
...
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.''');
  });
```

...and the issue resolves itself.

## Logs
```
Performing full restart...
Restarted app in 1,413ms.
E/flutter ( 2413): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 2413): '/data/user/0/justathoughtor2.com.thatsinsulting/cache/thats_insultingKEKMPS/thats_insulting/lib/main.dart': error: line 7 pos 5: yield statement only allowed in generator functions
E/flutter ( 2413):     yield new LicenseEntryWithLineBreaks(<String>['ramiabraham/insult-generator'], '''
E/flutter ( 2413):     ^
E/flutter ( 2413): 
E/flutter ( 2413): #0      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
E/flutter ( 2413): #1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

Analyzing C:\Users\thoug\IntelliJ\thats_insulting...
  error - Expected to find ';' at lib\main.dart:7:5 - expected_token
  error - Undefined name 'yield' at lib\main.dart:7:5 - undefined_identifier
2 issues found.
(Ran in 8.1s)
```

## Flutter Doctor
```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.125], locale en-US, channel alpha)
    • Flutter at C:\Users\thoug\flutter
    • Framework revision 8f65fec5f5 (3 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\thoug\AppData\Local\Android\sdk
    • Android NDK at C:\Users\thoug\AppData\Local\Android\sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.4127.31

[√] Connected devices
    • Pixel XL • HT6BH0201917 • android-arm • Android 8.1.0 (API 27)
```

**Comment by markusaksli-nc** [comment]
Closing as this has been fixed in the referenced sample.
