### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4809 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by barisozdmiir** [flutter/flutter#139489]
When I try to add the list named 'taps' to the body of 'BottomNavigationBar', I get this error.
`class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _currentIndex = 0;
  @override
  Widget build(BuildContext context) {
    List<Widget> taps = [
      const HomePage(),
      const UploadTap(),
      const ScanTap(),
      const NotificationTap(),
      const ProfileTap(),
    ];
    return SafeArea(
      child: Scaffold(
        bottomNavigationBar: BottomNavigationBar(
          currentIndex: _currentIndex,
          fixedColor: primary,
          unselectedItemColor: secondaryColor,
          backgroundColor: Colors.white,
          elevation: 0,
          onTap: (int index) {
            if (index == 0) {
              setState(() {
                _currentIndex = index;
              });
            } else if (index == 1) {
              setState(() {
                _currentIndex = index;
              });
            } else if (index == 2) {
              setState(() {
                _currentIndex = index;
              });
            } else if (index == 3) {
              setState(() {
                _currentIndex = index;
              });
            } else if (index == 4) {
              setState(() {
                _currentIndex = index;
              });
            }
          },
          type: BottomNavigationBarType.fixed,
          items: const [
            BottomNavigationBarItem(
                icon: Icon(IconlyBold.home), label: 'Home',),
            BottomNavigationBarItem(
                icon: Icon(IconlyBold.upload), label: 'Upload'),
            BottomNavigationBarItem(
                icon: Icon(IconlyBold.scan), label: 'Scan'),
            BottomNavigationBarItem(
                icon: Icon(IconlyBold.notification), label: 'Notification'),
            BottomNavigationBarItem(
                icon: Icon(IconlyBold.profile), label: 'Profile'),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          backgroundColor: primary,
          elevation: 0,
          child: const Icon(
            IconlyBold.scan,
            size: 30,
          ),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        body: taps[_currentIndex],
      ),
    );
  }
}`
Error:
`======== Exception caught by widgets library =======================================================
The following assertion was thrown building HomePage(state: _HomePageState#d5ce3):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4809 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  HomePage HomePage:file:///C:/Users/baris/StudioProjects/firststoreproject/lib/Pages/home_page.dart:21:13
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4809:16)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4812:8)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (33 frames)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#39     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#40     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#192    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#193    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#194    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#346    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#347    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#348    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#500    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#501    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#502    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#654    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#655    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#656    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#808    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#809    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#810    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#962    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#963    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#964    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#1116   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#1117   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#1118   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#1270   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#1271   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#1272   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#1424   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#1425   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#1426   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#1578   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#1579   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#1580   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#1732   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#1733   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#1734   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#1886   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#1887   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#1888   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#2040   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#2041   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#2042   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#2194   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#2195   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#2196   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#2348   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#2349   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#2350   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#2502   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#2503   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#2504   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#2656   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#2657   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#2658   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#2810   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#2811   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#2812   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#2964   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#2965   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#2966   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#3118   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#3119   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#3120   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#3272   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#3273   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#3274   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#3426   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#3427   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#3428   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#3580   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#3581   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#3582   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#3734   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#3735   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#3736   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#3888   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#3889   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#3890   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#4042   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#4043   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#4044   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#4196   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#4197   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#4198   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#4350   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#4351   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#4352   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#4504   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#4505   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#4506   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#4658   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#4659   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#4660   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#4812   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#4813   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#4814   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#4966   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#4967   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#4968   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#5120   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#5121   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#5122   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#5274   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#5275   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#5276   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#5428   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#5429   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#5430   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#5582   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#5583   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#5584   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#5736   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#5737   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#5738   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#5890   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#5891   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#5892   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#6044   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#6045   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#6046   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#6198   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#6199   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#6200   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#6352   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#6353   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#6354   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#6506   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#6507   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#6508   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#6660   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#6661   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#6662   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#6814   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#6815   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#6816   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#6968   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#6969   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#6970   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#7122   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#7123   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#7124   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#7276   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#7277   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#7278   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#7430   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#7431   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#7432   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#7584   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#7585   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#7586   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#7738   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#7739   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#7740   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#7892   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#7893   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#7894   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#8046   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#8047   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#8048   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (152 frames)
#8200   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#8201   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#8202   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (347 frames)
#8549   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#8550   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#8551   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (467 frames)
#9018   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#9019   Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#9020   RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1240:16)
#9021   RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1209:5)
#9022   RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1156:18)
#9023   BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720:19)
#9024   RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1155:13)
#9025   WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:988:7)
#9026   WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:7)
#9030   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)`

**Comment by azamongithub** [comment]
I am also getting this same issue

**Comment by darshankawar** [comment]
@barisozdmiir 
I think the error is occuring due to your code implementation and not a bug in framework.
Looking at the code, I see that you are calling the `HomePage` as below:

```
Widget build(BuildContext context) {
    List<Widget> taps = [
      const HomePage(),
```

which also happens to be your main class name:

```
class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}
```

Instead, you should do something like below:

```
Widget build(BuildContext context) {
    List<Widget> taps = [
      Home(),
```
And create class called `Home` which will resolve the error and compile your app properly:

<img width="227" alt="Screenshot 2023-12-05 at 2 06 36 PM" src="https://github.com/flutter/flutter/assets/67046386/5c5ca7d5-a3fa-4492-af67-36a25b46ce02">

<details>
<summary> Full runnable code below </summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: HomePage(),
  ));
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    List<Widget> taps = [
      Home(),
   //   const UploadTap(),
   //   const ScanTap(),
   //   const NotificationTap(),
   //   const ProfileTap(),
    ];
    return SafeArea(
      child: Scaffold(
        bottomNavigationBar: BottomNavigationBar(
          currentIndex: _currentIndex,
          fixedColor: Colors.black,
          unselectedItemColor: Colors.red,
          backgroundColor: Colors.white,
          elevation: 0,
          onTap: (int index) {
            if (index == 0) {
              setState(() {
                _currentIndex = index;
              });
            } else if (index == 1) {
              setState(() {
                _currentIndex = index;
              });
            } else if (index == 2) {
              setState(() {
                _currentIndex = index;
              });
            } else if (index == 3) {
              setState(() {
                _currentIndex = index;
              });
            } else if (index == 4) {
              setState(() {
                _currentIndex = index;
              });
            }
          },
          type: BottomNavigationBarType.fixed,
          items: const [
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: 'Home',
            ),
            BottomNavigationBarItem(
                icon: Icon(Icons.upload), label: 'Upload'),
            BottomNavigationBarItem(icon: Icon(Icons.scale), label: 'Scan'),
            BottomNavigationBarItem(
                icon: Icon(Icons.notification_add), label: 'Notification'),
            BottomNavigationBarItem(
                icon: Icon(Icons.abc), label: 'Profile'),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          backgroundColor: Colors.amber,
          elevation: 0,
          child: const Icon(
            Icons.ac_unit,
            size: 30,
          ),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        body: taps[_currentIndex],
      ),
    );
  }
}

class Home extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(),
    );
  }
}

```

</details>


Closing, as this is not an issue.

**Comment by barisozdmiir** [comment]
> Closing, as this is not an issue.

Thanks. I did not notice.
