### ISSUE TITLE
When wrapping a network image with BoxFit.scaleDown in Flutter, an error occur

### ISSUE THREAD

**Issue by ehxie** [flutter/flutter#139539]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

i will show all source code

### Expected results

can render the image

### Actual results

received some errors

The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [FittedBox].

void main() => runApp(const FittedBoxApp());

class FittedBoxApp extends StatelessWidget {
  const FittedBoxApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('FittedBox Sample')),
        body: const Center(
          child: FittedBoxExample(),
        ),
      ),
    );
  }
}

class FittedBoxExample extends StatelessWidget {
  const FittedBoxExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 400,
      width: 300,
      color: Colors.blue,
      child: FittedBox(
          // TRY THIS: Try changing the fit types to see how they change the way
          // the placeholder fits into the container.
          fit: BoxFit.scaleDown,
          clipBehavior: Clip.hardEdge,
          alignment: Alignment.bottomRight,
          // case1: work well
          // child: Placeholder(),

          // case2: received some errors
          child: Image.network(
            'https://oss-media.cdn.bcebos.com/content_square/33d57650-8078-9ae5-5f93-7dc50285b4bf.jpg',
            fit: BoxFit.scaleDown,
          )

          // case3: work well
          // child: Container(
          //   width: 200,
          //   height: 200,
          //   child: Image.network(
          //     'https://oss-media.cdn.bcebos.com/content_square/33d57650-8078-9ae5-5f93-7dc50285b4bf.jpg',
          //     fit: BoxFit.scaleDown,
          //   )
          // ),
          ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![image](https://github.com/flutter/flutter/assets/74121241/b8c5959e-89e8-4d98-934b-4ac3ad6297b8)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.1 23B81 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 3 categories.

```

</details>

**Comment by ehxie** [comment]
I think this might be due to the initial lack of height for Image.network. After wrapping Image.network with a Container (specifying the size) in case3, the error no longer occurs.

**Comment by huycozy** [comment]
Thanks for filing the issue. I can reproduce this on Android and Web platforms. This issue will not happen if I remove the outer `FittedBox` widget.

<details>
<summary>Output stack trace</summary>

```console
I/flutter ( 1455): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 1455): The following assertion was thrown during performLayout():
I/flutter ( 1455): 'package:flutter/src/rendering/box.dart': Failed assertion: line 327 pos 12: 'width > 0.0': is not
I/flutter ( 1455): true.
I/flutter ( 1455): 
I/flutter ( 1455): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 1455): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 1455): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 1455):   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
I/flutter ( 1455): 
I/flutter ( 1455): The relevant error-causing widget was:
I/flutter ( 1455):   FittedBox
I/flutter ( 1455):   FittedBox:file:///Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/reproduce_issues_2/lib/boxfit_139539.dart:32:14
I/flutter ( 1455): 
I/flutter ( 1455): When the exception was thrown, this was the stack:
I/flutter ( 1455): #2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:327:12)
I/flutter ( 1455): #3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2735:58)
I/flutter ( 1455): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #5      RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #8      RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:280:14)
I/flutter ( 1455): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #11     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #12     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:456:14)
I/flutter ( 1455): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #14     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #15     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
I/flutter ( 1455): #16     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1063:7)
I/flutter ( 1455): #17     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
I/flutter ( 1455): #18     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
I/flutter ( 1455): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #20     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #23     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #25     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1440:11)
I/flutter ( 1455): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #27     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #30     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #33     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #36     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #39     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #70     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #73     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #75     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
I/flutter ( 1455): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #77     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #80     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #83     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #86     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #89     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #91     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #92     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
I/flutter ( 1455): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
I/flutter ( 1455): #95     RenderBox.layout (package:flutter/src/rendering/box.dart:2396:11)
I/flutter ( 1455): #96     RenderView.performLayout (package:flutter/src/rendering/view.dart:219:14)
I/flutter ( 1455): #97     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2414:7)
I/flutter ( 1455): #98     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
I/flutter ( 1455): #99     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
I/flutter ( 1455): #100    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:582:23)
I/flutter ( 1455): #101    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:991:13)
I/flutter ( 1455): #102    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
I/flutter ( 1455): #103    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
I/flutter ( 1455): #104    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
I/flutter ( 1455): #105    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1034:7)
I/flutter ( 1455): #109    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
I/flutter ( 1455): (elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
I/flutter ( 1455): 
I/flutter ( 1455): The following RenderObject was being processed when the exception was fired: RenderFittedBox#2c9a1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter ( 1455):   creator: FittedBox ← ColoredBox ← ConstrainedBox ← Container ← FittedBoxExample ← Center ←
I/flutter ( 1455):     KeyedSubtree-[GlobalKey#fb0c9] ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter ( 1455):     CustomMultiChildLayout ← _ActionsScope ← ⋯
I/flutter ( 1455):   parentData: <none> (can use size)
I/flutter ( 1455):   constraints: BoxConstraints(w=300.0, h=400.0)
I/flutter ( 1455):   size: MISSING
I/flutter ( 1455):   fit: scaleDown
I/flutter ( 1455):   alignment: Alignment.bottomRight
I/flutter ( 1455):   textDirection: ltr
I/flutter ( 1455): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 1455):     child: RenderSemanticsAnnotations#e1cdd relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 1455):       child: RenderImage#2c6eb relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 1455): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 1455): Another exception was thrown: RenderBox was not laid out: RenderFittedBox#2c9a1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 1455): Another exception was thrown: RenderBox was not laid out: _RenderColoredBox#47595 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 1455): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 345 pos 12: 'child!.hasSize': is not true.
I/flutter ( 1455): Another exception was thrown: RenderBox was not laid out: _RenderColoredBox#47595
E/ion     ( 1455): ioctl c0044901 failed with code -1: Invalid argument
I/eproduce_issue( 1455): ProcessProfilingInfo new_methods=1556 is saved saved_to_disk=1 resolve_classes_delay=5000
D/ProfileInstaller( 1455): Installing profile for com.example.reproduce_issues
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (9 hours ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe Patch 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.18.0-2.0.pre.22, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.18.0-2.0.pre.22 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bfaacd5ef8 (12 minutes ago), 2023-12-04 22:48:25 -0500
    • Engine revision f43ef6cbdd
    • Dart version 3.3.0 (build 3.3.0-190.0.dev)
    • DevTools version 2.30.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe Patch 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by ehxie** [comment]
@huycozy 
Thank you for your answer. Removing the `FittedBox` widget works well, but in `case2` (in the example), I want to position the `image` at the bottom of the `Container` widget and make it flexible.
When I use FittedBox to wrap a network image, it works well with other values for the fit attribute. However, when I use BoxFit.scaleDown, it throws an error.

**Comment by prasadsunny1** [comment]
What do you think should be the correct behaviour @ehxie?
