### ISSUE TITLE
Connection closed while receiving data, 

### ISSUE THREAD

**Issue by kazerdira** [flutter/flutter#139608]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

i m getting my data in json form from the backend it is laravel , and i m getting all the need   name , id , and thumbnail (which is a url for a picture in backend) etc...
when i try to access the thumbnail using NetworkImage widget  i am getting error , but when i try it in navigator inside the emulator i access the image with no problem but with flutter app no , 
i tried to edit the manifest file by adding this 
android:usesCleartextTraffic="true"
android:networkSecurityConfig="@xml/network_security_config">

but still not getting the image 

### Expected results

i expected to get the image in thecontainer where the NetworkImage is its child inside the decorationBox

### Actual results

i am getting the error
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (11014): The following HttpException was thrown resolving an image codec:
I/flutter (11014): Connection closed while receiving data, uri =
I/flutter (11014): http://172.29.192.1:8000/uploads/images/91b140ce34402d0022f8268ff57840e1.png
I/flutter (11014): 
I/flutter (11014): When the exception was thrown, this was the stack:
I/flutter (11014): #0      _HttpIncoming.listen.<anonymous closure> (dart:_http/http_impl.dart:442:7)
I/flutter (11014): #11     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1201:22)
I/flutter (11014): #12     _HttpParser._onDone (dart:_http/http_parser.dart:899:9)
I/flutter (11014): #20     _Socket._onData (dart:io-patch/socket_patch.dart:2454:21)
I/flutter (11014): #27     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1943:35)
I/flutter (11014): #28     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1372:18)
I/flutter (11014): (elided 25 frames from dart:async)
I/flutter (11014): 
I/flutter (11014): Image provider:
I/flutter (11014):   NetworkImage("http://172.29.192.1:8000/uploads/images/91b140ce34402d0022f8268ff57840e1.png",
I/flutter (11014):   scale: 1.0)
I/flutter (11014): Image key:
I/flutter (11014):   NetworkImage("http://172.29.192.1:8000/uploads/images/91b140ce34402d0022f8268ff57840e1.png",
I/flutter (11014):   scale: 1.0)
```

### Code sample

```
Widget gridCourses(CourseItem? course, BuildContext context) {
  print(
      'the correspending image is  ${AppConstants.SERVER_UPLOADS}${course!.thumbnail!}');
  return GestureDetector(
    onTap: () {
      Navigator.of(context).pushNamed(
        AppRoutes.COURSE_DETAIL_PAGE,
        arguments: {'id': course.id},
      );
    },
    child: Container(
      height: 50.h,
      width: 50.w,
      padding: EdgeInsets.all(8.w),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(15.w),
        image: DecorationImage(
            fit: BoxFit.fill,
            image: NetworkImage(
              '${AppConstants.SERVER_UPLOADS}${course!.thumbnail!}',
            ) // NetworkImage(AppConstants.SERVER_UPLOADS + course!.thumbnail!),
            ),
      ),
      child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            Container(
              child: Text(
                course.name ?? "",
                maxLines: 1,
                overflow: TextOverflow.fade,
                textAlign: TextAlign.left,
                softWrap: false,
                style: TextStyle(
                    color: AppColors.primaryElementText,
                    fontWeight: FontWeight.bold,
                    fontSize: 12.sp),
              ),
            ),
            SizedBox(
              height: 5.h,
            ),
            Text(
              course.description ?? "",
              maxLines: 1,
              overflow: TextOverflow.fade,
              textAlign: TextAlign.left,
              softWrap: false,
              style: TextStyle(
                  color: AppColors.primaryFourElementText,
                  fontWeight: FontWeight.bold,
                  fontSize: 10.sp),
            ),
          ]),
    ),
  );
}

```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```
I/flutter (11014): the correspending image is  http://172.29.192.1:8000/uploads/images/91b140ce34402d0022f8268ff57840e1.png
I/flutter (11014): the correspending image is  http://172.29.192.1:8000/uploads/images/c19a75f75373803f4e8dfd7d9c80bccb.png
I/flutter (11014): the correspending image is  http://172.29.192.1:8000/uploads/images/38bc92bede94779df2f6cf855ba71b7d.png
I/flutter (11014): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (11014): The following HttpException was thrown resolving an image codec:
I/flutter (11014): Connection closed while receiving data, uri =
I/flutter (11014): http://172.29.192.1:8000/uploads/images/91b140ce34402d0022f8268ff57840e1.png
I/flutter (11014): 
I/flutter (11014): When the exception was thrown, this was the stack:
I/flutter (11014): #0      _HttpIncoming.listen.<anonymous closure> (dart:_http/http_impl.dart:442:7)
I/flutter (11014): #11     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1201:22)
I/flutter (11014): #12     _HttpParser._onDone (dart:_http/http_parser.dart:899:9)
I/flutter (11014): #20     _Socket._onData (dart:io-patch/socket_patch.dart:2454:21)
I/flutter (11014): #27     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1943:35)
I/flutter (11014): #28     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1372:18)
I/flutter (11014): (elided 25 frames from dart:async)
I/flutter (11014): 
I/flutter (11014): Image provider:
I/flutter (11014):   NetworkImage("http://172.29.192.1:8000/uploads/images/91b140ce34402d0022f8268ff57840e1.png",
I/flutter (11014):   scale: 1.0)
I/flutter (11014): Image key:
I/flutter (11014):   NetworkImage("http://172.29.192.1:8000/uploads/images/91b140ce34402d0022f8268ff57840e1.png",
I/flutter (11014):   scale: 1.0)
```

### Flutter Doctor output

my flutter doctor 

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.18.0-3.0.pre.20, on Microsoft Windows [version 10.0.22621.2715], locale fr-FR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.3)
[√] Android Studio (version 2022.1)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.2)
[√] Connected device (5 available)
[√] Network resources

**Comment by darshankawar** [comment]
@kazerdira 
Looking at the error, it doesn't seem to be sdk related but could be server side. Can you try by modifying the server-side code ? 
Also, these type of issues are better suited for support channels like StackOverflow, so please ask the same there.
Closing for now. If you disagree, write in comments and I'll reopen it.

**Comment by kazerdira** [comment]
sorry , but the serverside is ok , i mean all the json came from back side is ok , and the url of the picture is opening with no problem in the navigator , i think it is with flutter ,

**Comment by darshankawar** [comment]
Thanks for the feedback. Can you provide us a complete runnable reproducible code sample without any third party implementation that still shows the error ?
