### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by jsxtech** [flutter/flutter#139629]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Operation not permitted, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1069:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:991:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1101:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:359:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:365:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.0, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_IN)
    [32m•[39m Flutter version 3.16.0 on channel stable at /home/jesie/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision db7ef5bf9f (3 weeks ago), 2023-11-15 11:25:44 -0800
    [32m•[39m Engine revision 74d16627b9
    [32m•[39m Dart version 3.2.0
    [32m•[39m DevTools version 2.28.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /home/jesie/Android/Sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /home/jesie/Android/Sdk
    [32m•[39m Java binary at: /home/jesie/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Ubuntu clang version 14.0.0-1ubuntu1.1
    [32m•[39m cmake version 3.22.1

**Comment by darshankawar** [comment]
@jsxtech 
Can you check [this](https://github.com/flutter/flutter/issues/129124#issuecomment-1603773416) and see if it helps to resolve your case ?
