### ISSUE TITLE
[ERROR][Image_Picker]: java.lang.RuntimeException: Unable to get provider io.flutter.plugins.imagepicker.ImagePickerFileProvider: java.lang.NullPointerException

### ISSUE THREAD

**Issue by hurkanugur** [flutter/flutter#139655]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1) Release the flutter app using "**flutter build apk --release**"
2) Try to open release apk in Android Studio with emulator or in a real device.
3) App crashes due to **image_picker: ^1.0.4**

### Expected results

Opening the release app in the emulator without a problem.

### Actual results

The emulator crashes and app won't open due to **image_picker: ^1.0.4**

### Logs

<details><summary>Logs</summary>

```console
FATAL EXCEPTION: main
Process: com.example.test, PID: 17918
java.lang.RuntimeException: Unable to get provider io.flutter.plugins.imagepicker.ImagePickerFileProvider: java.lang.NullPointerException: Attempt to read from field 'long android.content.res.XmlBlock$Parser.mParseState' on a null object reference in method 'int android.content.res.XmlBlock$Parser.getAttributeListValue(java.lang.String, java.lang.String, java.lang.String[], int)'
    at android.app.ActivityThread.installProvider(ActivityThread.java:7467)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to read from field 'long android.content.res.XmlBlock$Parser.mParseState' on a null object reference in method 'int android.content.res.XmlBlock$Parser.getAttributeListValue(java.lang.String, java.lang.String, java.lang.String[], int)'
    at android.content.res.XmlBlock$Parser.getAttributeListValue(XmlBlock.java:346)
    at androidx.core.content.b.h(Unknown Source:19)
    at androidx.core.content.b.e(Unknown Source:11)
    at androidx.core.content.b.attachInfo(Unknown Source:31)
    at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.2 23B92 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.2.4)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### Extra Info

ext.kotlin_version = '1.9.21'
classpath 'com.android.tools.build:gradle:8.2.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-all.zip

**Comment by hurkanugur** [comment]
After a very very long research, I found out that the problem occurs due to obfuscation in release mode in Android.

How to solve this:

1) Go to **android/app/build.gradle** and define your proguard files:

```console
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug

            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type. Make sure to use a build
            // variant with `debuggable false`.
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
```
    
2) Create **proguard-rules.pro** in **android/app**:

```console
-keep class org.xmlpull.** { *; }
```

That's it!
