### ISSUE TITLE
[tool_crash] _TypeError: (#0      StreamGroup.add (package:async/src/stream_group.dart))

### ISSUE THREAD

**Issue by nageshbanchhor** [flutter/flutter#139732]
## Command
```
flutter run --machine --start-paused -d chrome --devtools-server-address http://127.0.0.1:9100/ --target lib\main.dart
```

## exception

_TypeError: type '_HttpServer' is not a subtype of type 'Stream<HttpRequest>' of 'stream'

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      StreamGroup.add (package:async/src/stream_group.dart))

```
#0      StreamGroup.add (package:async/src/stream_group.dart)
#1      List.forEach (dart:core-patch/growable_array.dart:416:8)
#2      StreamGroup.merge (package:async/src/stream_group.dart:95:13)
#3      new HttpMultiServer (package:http_multi_server/http_multi_server.dart:102:27)
#4      HttpMultiServer._loopback (package:http_multi_server/http_multi_server.dart:216:14)
<asynchronous suspension>
#5      startHttpServer (package:dwds/src/utilities/server.dart:57:20)
<asynchronous suspension>
#6      ExtensionBackend.start (package:dwds/src/servers/extension_backend.dart:60:20)
<asynchronous suspension>
#7      Dwds.start (package:dwds/dart_web_debug_service.dart:109:26)
<asynchronous suspension>
#8      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:279:23)
<asynchronous suspension>
#9      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:762:22)
<asynchronous suspension>
#10     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:305:25)
<asynchronous suspension>
#11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22631.2792], locale en-IN)
    • Flutter version 3.10.6 on channel stable at C:\Users\sweta\Downloads\flutter_windows_3.10.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\sweta\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at C:\Users\sweta\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.2792]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.200
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.97

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f468f3366c26a5092eb964a230ce7892fda8f2f8
### Plugins
cloud_firestore-4.13.3
cloud_firestore_web-3.8.7
firebase_auth-4.15.0
firebase_auth_web-5.8.9
firebase_core-2.24.0
firebase_core_web-2.9.0

**Comment by danagbemava-nc** [comment]
Hi @nageshbanchhor, you are using an older version of flutter. 

Can you upgrade to the latest version of flutter stable (3.16.3) to see if you still experience this issue? If you do, please provide the updated output of `flutter doctor -v`.

Thank you

**Comment by danagbemava-nc** [comment]
Thanks for the update. 

Tentatively closing this as fixed. If you run into this issue with the latest version of flutter, kindly leave a comment below with the full crash logs and flutter doctor -v and I will reopen this. 

Thank you

**Comment by nageshbanchhor** [comment]
Thanks for the support
