### ISSUE TITLE
Selection Area inside scrollable throw when selectionDelegate points are outside.

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#139797]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Select some words and expend a bit your selection.
2. Scroll the page until one of the starting selection controller is not visible.
3. Now Scroll up or down the page few times

### Expected results

Nothing wrong should happen.

### Actual results

Exception thrown

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      const App(),
    );

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: const Text("SelectionArea issue"),
      ),
      body: SafeArea(
        child: SelectionArea(
          child: ListView.separated(
            padding: const EdgeInsets.symmetric(horizontal: 15, vertical: 10),
            itemCount: 50,
            separatorBuilder: (BuildContext context, int index) =>
                const Divider(height: 1),
            itemBuilder: (BuildContext context, int index) {
              return IntrinsicHeight(
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: <Widget>[
                    Expanded(
                      child: ColoredBox(
                        color: Colors.grey,
                        child: Padding(
                          padding: const EdgeInsets.all(16),
                          child: Text("key-$index"),
                        ),
                      ),
                    ),
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(16),
                        child: Text(
                          "value$index",
                        ),
                      ),
                    ),
                  ],
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![flutter-issue](https://github.com/flutter/flutter/assets/37028599/bff75fee-8827-44d9-902e-1d117fc5dabd)

</details>

### Logs

<details><summary>Logs</summary>

```console
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#11d63](dirty, state: _OverlayEntryWidgetState#8d0ab):
Null check operator used on a null value

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/earminjon/Documents/projects/flutter-deploy-copy/lib/main_frx.dart:17:18
When the exception was thrown, this was the stack: 
#0      SelectableRegionState.startGlyphHeight (package:flutter/src/widgets/selectable_region.dart:1078:56)
#1      SelectableRegionState.contextMenuAnchors (package:flutter/src/widgets/selectable_region.dart:962:25)
#2      new AdaptiveTextSelectionToolbar.selectableRegion (package:flutter/src/material/adaptive_text_selection_toolbar.dart:171:40)
#3      SelectionArea._defaultContextMenuBuilder (package:flutter/src/material/selection_area.dart:96:41)
#4      SelectableRegionState._onAnyDragEnd.<anonymous closure> (package:flutter/src/widgets/selectable_region.dart:592:43)
#5      SelectionOverlay.showToolbar.<anonymous closure> (package:flutter/src/widgets/text_selection.dart:1402:36)
#6      ContextMenuController.show.<anonymous closure> (package:flutter/src/widgets/context_menu_controller.dart:65:54)
#7      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:351:36)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409:27)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297:15)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#18     _invoke (dart:ui/hooks.dart:170:13)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#20     _drawFrame (dart:ui/hooks.dart:140:31)
====================================================================================================

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.1.1 23B81 darwin-arm64, locale fr-FR)
    • Flutter version 3.13.7 on channel stable at /Users/earminjon/fvm/versions/3.13.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (9 weeks ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/earminjon/Library/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/earminjon/Library/Android/Sdk
    • Java binary at: /Users/earminjon/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/earminjon/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/earminjon/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.76.2)
    • VS Code at /Users/earminjon/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 119.0.6045.199
    
[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by EArminjon** [comment]
Same as https://github.com/flutter/flutter/issues/124078.
Created for data purpose.
