### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 247078143** [flutter/flutter#139802]
```console
======== Exception caught by widgets library =======================================================
The following assertion was thrown building TBExceptionRoute(state: _TBExceptionRouteState#e73c8):
'package:flutter/src/rendering/object.dart': Failed assertion: line 1609 pos 14: '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  TBExceptionRoute TBExceptionRoute:file:///Users/songwenshan/baidu/app/app_all/lib/main.dart:227:12
When the exception was thrown, this was the stack: 
#2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1609:14)
#3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2320:11)
#4      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1334:5)
#5      ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:3312:5)
#6      MultiChildRenderObjectElement.insertRenderObjectChild (package:flutter/src/widgets/framework.dart:6273:18)
#7      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5870:35)
#8      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5544:5)
#9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6194:11)
...     Normal element mounting (1209 frames)
#1218   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#1219   Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#1220   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4703:16)
#1221   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#1222   Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#1223   BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#1224   WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#1225   RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#1226   SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#1227   SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#1228   SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#1232   _invoke (dart:ui/hooks.dart:166:10)
#1233   PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#1234   _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1609 pos 14: '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.
```

**Comment by xjyribro** [comment]
Hi, please follow the template for filing bugs:

**Is there an existing issue for this?

Steps to reproduce

Expected results

Actual results

Code sample

Logs

Flutter Doctor output**

**Comment by huycozy** [comment]
@247078143 When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing the issue. Once you update the issue with more information in the issue template, please write in comments and I will reopen this for further investigation. Thanks!
