### ISSUE TITLE
[image_picker] getting asynchronous suspension on using pick image method

### ISSUE THREAD

**Issue by gitsak12** [flutter/flutter#139858]
<details>
<summary>Code</summary>

```
File? _selectedImage;

  Future<void> _takePicture() async {
    final ImagePicker picker = ImagePicker();
    final XFile? pickedImage =
        await picker.pickImage(source: ImageSource.camera, maxWidth: 600);

    if (pickedImage == null) {
      return;
    }
    setState(() {
      _selectedImage = File(pickedImage.path);
    });
  }

```

</details>

**PlatForm Exception.**

<details>
<summary>Log</summary>

```
E/flutter ( 6902): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 6902): #0      ImagePickerApi.pickImages (package:image_picker_android/src/messages.g.dart:311:7)
E/flutter ( 6902): <asynchronous suspension>
E/flutter ( 6902): #1      ImagePickerAndroid._getImagePath (package:image_picker_android/image_picker_android.dart:116:33)
E/flutter ( 6902): <asynchronous suspension>
E/flutter ( 6902): #2      ImagePickerAndroid.getImageFromSource (package:image_picker_android/image_picker_android.dart:183:26)
E/flutter ( 6902): <asynchronous suspension>
E/flutter ( 6902): #3      _ImageInputState._takePicture (package:favourite_place/Widgets/image_input.dart:20:9)
E/flutter ( 6902): <asynchronous suspension>
```

</details>

**Comment by darshankawar** [comment]
@gitsak12 
Can you provide  `flutter doctor -v` and device on which the error occurs ?
Also check the [plugin example](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) and run on same device to see if it also gives you same error or not ?

**Comment by gitsak12** [comment]
I resolved that issue by setting 'minSdkVersion 21'. But this should be written in package doc

**Comment by darshankawar** [comment]
@gitsak12 
It does say the same:

<img width="152" alt="Screenshot 2023-12-12 at 10 53 07 AM" src="https://github.com/flutter/flutter/assets/67046386/0887780a-30ee-462f-856a-24252bb0697a">

Closing as resolved.
