### ISSUE TITLE
lerp is receiving NaN

### ISSUE THREAD

**Issue by philmayes** [flutter/flutter#139820]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code sample supplied.
2. Touch one of the tiles.
3. lerp exception is thrown, see Actual Results.
4. During the stripping down of my code, I was sometimes getting:

> The following assertion was thrown building Text("F", dirty, dependencies: [DefaultSelectionStyle, DefaultTextStyle, MediaQuery]):
> 'package:flutter/src/widgets/widget_span.dart': Failed assertion: line 135 pos 16: 'poppedFontSize == fontSizeToPush': is not true.
> 

See screenshot of changes for Flutter 3.16

### Expected results

The tile should shrink to nothing because its size has been changed to 0, see AnimatedContainer at line 268. The tiles above it will then fall down. See FourFit in the App or Play Store for this working with an earlier version of Flutter.
I don't think it is relevant, but there is code to maintain fonts at the same size, ignoring any textScaler (now scale) factor, see source lines 105-109.

### Actual results

Lerp Exception is thrown:

Launching lib\main.dart on Pixel 7 Pro in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:60653/oOUHpKEoA9w=/ws

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building AnimatedDefaultTextStyle(duration: 200ms, inherit: true, color: Color(0xffffffff), size: NaN, softWrap: wrapping at box width, overflow: clip, dirty, state: _AnimatedDefaultTextStyleState#3daff(ticker active)):
Cannot interpolate between finite and non-finite values
'dart:ui/lerp.dart':
Failed assertion: line 20 pos 10: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    TextButton TextButton:file:///E:/dev/fourfit/bug/lib/main.dart:276:22

When the exception was thrown, this was the stack:
#2      lerpDouble (dart:ui/lerp.dart:20:10)
#3      TextStyle.lerp (package:flutter/src/painting/text_style.dart:1238:20)
#4      TextStyleTween.lerp (package:flutter/src/widgets/implicit_animations.dart:214:41)
#5      Tween.transform (package:flutter/src/animation/tween.dart:362:12)
#6      Animatable.evaluate (package:flutter/src/animation/tween.dart:68:46)
#7      _AnimatedDefaultTextStyleState.build (package:flutter/src/widgets/implicit_animations.dart:1961:22)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#18     _invoke (dart:ui/hooks.dart:312:13)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#20     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════

### Code sample

<details><summary>Code sample</summary>

```dart
// ignore_for_file: constant_identifier_names, avoid_print

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

//=====================SETTINGS.DART=============================

// Game layout
const int COL_COUNT = 6;
const int ROW_COUNT = 4;
const int TILE_COUNT = COL_COUNT * ROW_COUNT;
const int WORD_LEN = 4;
const int WORD_MAX = TILE_COUNT ~/ WORD_LEN;

// Miscellaneous
const String DEFAULT_STYLE = 'Vibrant';

//===========================styles.dart=======================

class Style {

  Style(
    this.name,
    this.uncolored,
    this.unused,
    this.selected,
    this.selectedLast,
    this.selectedLastName,
    this.choices,
    this.letterUnselected,
    this.letterSelected,
    this.weightUnselected,
    this.weightSelected,
  );
  static MaterialColor normalTheme = Colors.blue;
  static Color screenBackground = Colors.blue.shade50;
  static const BorderRadiusGeometry buttonCorner = BorderRadius.all(Radius.circular(8));
  
  String name;                      // name of this style
  Color uncolored;                  // color of an uncolored, unselected tile
  Color unused;                     // an unused color, used for consistency check
  Color selected;                   // color of a selected tile
  Color selectedLast;               // color of the most recently-selected tile
  String selectedLastName;          // color name for the above tile
  List<Color> choices;              // 6 different colors, one for each word
  Color letterUnselected;           // color of letter on unselected tile
  Color letterSelected;             // color of letter on selected tile
  FontWeight weightUnselected;      // font weight of letter on unselected tile
  FontWeight weightSelected;        // font weight of letter on selected tile
}

List<Style> styles = <Style>[
  Style(
    DEFAULT_STYLE,                  // name of this style, 'Vibrant'
    Colors.grey.shade400,         // color of an uncolored, unselected tile
    Colors.deepPurple,            // an unused color, used for consistency check
    Colors.yellow.shade100,       // color of a selected tile
    Colors.yellow,                // color of the most recently-selected tile
    'yellow',                       // color name for the above tile
    <Color>[                        // 6 different colors, one for each word
      Colors.red,
      Colors.orange,
      Colors.green,
      Colors.cyan,
      Colors.blue,
      Colors.purple,
    ],
    Colors.white,                 // color of letter on unselected tile
    Colors.indigo,                // color of letter on selected tile
    FontWeight.w700,                // font weight of letter on unselected tile
    FontWeight.w900,                // font weight of letter on selected tile
  ),
];

Style nameToStyle(String name) {
  for (final Style style in styles) {
    if (name == style.name) {
      return style;
    }
  }
  return styles[0];
}

//=========================media_info.dart=================

// BEWARE!!! _gameRatio etc. must be changed if score, etc. are added above the info.
// Their values are determined pragmatically with the Widget Inspector.
const double _infoRatio = 0.72;  // smallest Y/X ratio for portrait view
const double _gameRatio = 0.90;  // smallest Y/X ratio for portrait view
const double _bothRatio = _gameRatio + _infoRatio;
const double _gameFraction = 0.6;// width allocated for game in landscape view

class MediaInfo {
  static double screenX = 0;
  static double screenY = 0;

  static double safeX = 0;
  static double safeY = 0;
  static double leftPadding = 0;
  static double topPadding = 0;

  static bool isDark = false;
  static bool isPortrait = false;
  static bool isLandscape = true;
  /// Is the textScaler function from MediaQueryData.
  static double Function(double) scale = (double x) => 1.0;
  /// Returns the font size required for it to be displayed unchanged.
  static double unscaled (double nominal) {
    return nominal * nominal / scale(nominal);
  }

  static double tileSize = 0;
  static double width = 0;
  static double height = 0;
  static double width1 = 0;
  static double width2 = 0;

  void init(BuildContext context) {
    final MediaQueryData mediaQueryData = MediaQuery.of(context);
    screenX = mediaQueryData.size.width;
    screenY = mediaQueryData.size.height;
    scale = mediaQueryData.textScaler.scale;

    leftPadding = mediaQueryData.viewPadding.left;
    topPadding = mediaQueryData.viewPadding.top;
    safeX = screenX - leftPadding - mediaQueryData.viewPadding.right;
    safeY = screenY - topPadding  - mediaQueryData.viewPadding.bottom;

    isDark = mediaQueryData.platformBrightness == Brightness.dark;
    isPortrait = safeY > safeX;
    isLandscape = !isPortrait;

    // PERFORM PLAY SCREEN LAYOUT CALCULATIONS

    width = safeX;
    height = safeY - kToolbarHeight;

    // Calculate tile size
    double gameWidth = width;
    if (isPortrait) {
      final double screenRatio = height / width;
      // If the screen is not tall enough to accommodate Part1 and Part2 as is,
      // adjust width to shrink Part1 and gameWidth to shrink Part2.
      if (_bothRatio > screenRatio) {
        final double scale = screenRatio / _bothRatio;
        width *= scale;
        gameWidth *= scale;
      }
    } else {
      // landscape
      gameWidth *= _gameFraction;
    }
    // Even a split screen may still be too wide to hold the game...
    if (height / gameWidth < _gameRatio) {
      gameWidth = height / _gameRatio;
    }
    tileSize = gameWidth / (COL_COUNT + 1);
    if (isPortrait) {
    width2 = gameWidth;
    width1 = gameWidth;
    } else {
    width2 = width * _gameFraction;
    width1 = width - width2;
    }
  }
}

//=========================tile_state.dart======================

enum Picker {none, user, replay, letterHint, wordBonus}

const double noSize = -1.0;

/// A class that Model uses to represent a single tile.
class TileState {
  double size = noSize;
  Picker selected = Picker.none;
  int wordNo = 0;
  int letterNo = 0;
  String letter = '?';
  int colNo = -1;
  int rowNo = -1;

  /// Sets information about the tile.
  void setInfo(String info) {
    wordNo = int.parse(info[0]);
    letterNo = int.parse(info[1]);
    letter = info[2];
  }

  void reset(double newSize) {
    size = newSize;
    selected = Picker.none;
  }
}

/// An immutable class that
/// 1. allows Tile.build to make one call
/// 2. allows context.select to recognize unchanged tiles
///    (this is why the equality operator is needed)
@immutable
class TileDraw {
  const TileDraw(
    this.backgroundColor,
    this.foregroundColor,
    this.text,
    this.textStyle,
    this.wordNo,
    this.letterNo,
    this.size,
  );
  final Color backgroundColor;
  final Color foregroundColor;
  final String text;
  final TextStyle textStyle;
  final int wordNo;
  final int letterNo;
  final double size;

  @override
  bool operator ==(Object other) =>
    other is TileDraw &&
    other.backgroundColor == backgroundColor &&
    other.foregroundColor == foregroundColor &&
    other.text == text &&
    other.textStyle == textStyle &&
    other.size == size;
    
  @override
  int get hashCode => 
    backgroundColor.hashCode ^
    foregroundColor.hashCode ^
    text.hashCode ^
    textStyle.hashCode ^
    size.hashCode;
}

//=========================tile.dart=========================

const double tilePad = 2; // Amount of padding WITHIN tileSize

class Tile extends StatefulWidget {
  const Tile({
    super.key,
    required this.col,
    required this.row
  });
  final int col;
  final int row;

  @override
  State<Tile> createState() => _TileState();
}

class _TileState extends State<Tile> {
  @override
  Widget build(BuildContext context) {
    // By getting the immutable object [tileDraw] from the model, we:
    // 1. avoid the multiple calls that were formerly used
    // 2. allow the Flutter framework to recognize when a tile has not changed
    //    and not rebuild this widget, see
    // https://flutterbyexample.com/lesson/using-context-extensions-for-more-control
    final TileDraw tileDraw = context.select(
      (Model m) => m.getTileDraw(widget.col, widget.row)
    );
    final double size = tileDraw.size;

    return AnimatedContainer(
      width: tileDraw.size,
      height: size,
      duration: const Duration(milliseconds: 200),
      child: Stack(
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.all(tilePad),
              child: TextButton(
                style: TextButton.styleFrom(
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(size / 10),
                  ),
                  fixedSize: Size(size, size),
                  backgroundColor: tileDraw.backgroundColor,
                  textStyle: tileDraw.textStyle,
                  foregroundColor: tileDraw.foregroundColor,
                ),
                onPressed: (){},
                child: Text(tileDraw.text),
            ),
          ),
        ],
      ),
    );
  }
}

/// Gets a puzzle as used by Model().
List<String> getPuzzle() {
  return <String>['13T21A22N03D', '12S20S23G02I', '11O10H01A00P', '53E52S51A50E', '30M40S43T33T', '31U41E42N32S'];
}

List<List<String>> makeGrid() {
  final List<List<String>> grid = List<List<String>>.generate(COL_COUNT, (int i) => <String>[]);
  return grid;
}

//===========================games.dart======================

/// Returns a game at [level] as a string, e.g. 13T21A22N03D...
///
/// Each 3 characters represents one tile as wordNo, letterNo, letter,
/// see TileState.setInfo(String)
/// The first 12 chars == 4 tiles are column 0, rows 0-3, etc.
String getGame() {
  return getPuzzle().join();
}

//===========================model.dart========================

/// The state of the game
enum Mode {
  /// The user is playing
  play,
  /// The game is being replayed to show the user
  replay,
  /// The user has paused replay
  paused,
  /// The game has been replayed; show the user the whole game again
  replayed,
  /// User is blocked from interfering while we remove tiles
  removing,
  /// The user won the game, it's displayed in color, waiting for tap
  won,
  /// A game is being dealt
  deal,
}

enum Dragging {
  allowed,        // dragging can start or has started
  done,           // dragging no longer wanted; ignore actions until allowed
}

List<Color> _wordColors = List<Color>.filled(WORD_MAX, Colors.white);
List<Color> _allColors = List<Color>.filled(WORD_MAX, Colors.white);

// class Persistent extends ChangeNotifier {
class Model extends ChangeNotifier {
  // style_name is snake style b/c Model uses styleName as the public interface
  // ignore: non_constant_identifier_names
  String style_name = DEFAULT_STYLE;
  String gameString = '22N32C33S23D21O41U42D31I20P40R43E30S11O10B01U00R12N51G50A02E13E52E53D03D';
  List<int> randomWord = List<int>.generate(WORD_MAX, (int i) => i, growable: false);
  List<int> randomColor = List<int>.generate(WORD_MAX, (int i) => i, growable: false);
  Mode mode = Mode.play;
  double _tileSize = noSize;
  List<List<TileState>> puzzle = List<List<TileState>>.generate(COL_COUNT, 
    (int i) => List<TileState>.generate(ROW_COUNT, (int i) => TileState())
  );
  // The following list is by reference, i.e. the tiles exist in puzzle
  List<TileState> selectedTiles = <TileState>[];  // tiles that are currently selected

  // The following items need to be reinitialized for a factory reset.
  Style style = nameToStyle(DEFAULT_STYLE);

  // ========= constructor ===================================================

  /// A fake constructor
  Future<void> setUp() async {
     _gameStringToCols(gameString, reset: true);
    style = nameToStyle(style_name);
    _newGame();
  }

  // ========= getters and setters ===========================================

  double get tileSize => _tileSize;

  set tileSize(double size) {
    _tileSize = size;
    // Set the width and height of all the tiles.
    for (int colNo = 0; colNo < puzzle.length; colNo++) {
      final List<TileState> col = puzzle[colNo];
      for (int rowNo = 0; rowNo < col.length; rowNo++) {
        final TileState tileState = col[rowNo];
        if (tileState.size != 0) {
          tileState.size = size;
        }
      }
    }
  }

  // ========= member functions ==============================================

  /// Selects a tile by dragging.
  Dragging drag(int colNo, int rowNo) {
    if (mode != Mode.play) {
      // Don't allow the user to interfere with playback
      return Dragging.done;
    }
    // Map screen col/row to tile col/row and also
    // reject any location that is "whitespace"
    //
    // tile column  widget
    // w/row+size   locations
    // +------+     +------+
    // | row3 |     |      |
    // |   58 |     |      |
    // +------+     +------+
    // | row2 |     | row3 |      For example, suppose
    // |   58 |     |      |  <-- drag touches here
    // +------+     +------+
    // | row1 |     | row2 |
    // |    0 |     |      |
    // +------+     +------+
    // | row0 |     | row0 |
    // |   58 |     |      |
    // +------+     +------+
    //
    // Before drag was implemented, select would be called directly by Tile(),
    // supplying its row as 3. Select uses _getRow to find its rowNo in the
    // 6x4 grid so that it can determine adjacency.
    // This requirement also applies to replay, which takes its col/row from
    // the tileState.
    // The drag operation at GameWidgetState.selectTile) calculates col/row by
    // screen location, so we need to find the tile at that location and switch
    // to its rowNo. This also allows whitespace to be recognized and ignored.
    //
    // final List<TileState> colTiles = puzzle[colNo];
    int visible = -1;
    bool match = false;
    for (final TileState tileState in puzzle[colNo]) {
      if (tileState.size > 0) {
        visible++;
      }
      if (rowNo == visible) {
        rowNo = tileState.rowNo;
        match = true;
        break;
      }
    }
    if (!match) {
      // It's whitespace.
      return Dragging.allowed;
    }

    final TileState tileState = puzzle[colNo][rowNo];
    if (tileState.selected == Picker.none) {
      final bool word = select(colNo, rowNo, Picker.user);
      return word ? Dragging.done : Dragging.allowed;
    } else {
      // If it's not the last selected, remove extra selections until it /is/.
      while (selectedTiles.isNotEmpty) {
        final TileState lastTile = selectedTiles.last;
        if (lastTile == tileState) {
          break;
        }
        select(lastTile.colNo, lastTile.rowNo, Picker.user);
      }
      return Dragging.allowed;
    }
  }

  /// Populates the puzzle array from a game as a string (see getGame)
  void _gameStringToCols(String gameString, {bool reset=false}) {
    int stringIndex = 0;
    for (int colNo = 0; colNo < COL_COUNT; colNo++) {
      for (int rowNo = 0; rowNo < ROW_COUNT; rowNo++) {
        final TileState tileState = puzzle[colNo][rowNo];
        tileState.rowNo = rowNo;
        tileState.colNo = colNo;
        tileState.setInfo(gameString.substring(stringIndex, stringIndex + 3));
        if (reset) {
          tileState.reset(_tileSize);
        }
        stringIndex += 3;
      }
    }
  }

  /// Gets the background color of a specific tile.
  Color getBgColor(TileState tileState) {
    if (tileState.selected != Picker.none && tileState.size > 0) {
      if (selectedTiles.isNotEmpty && tileState == selectedTiles.last) {
        return style.selectedLast;
      }
      return style.selected;
    }
    return _allColors[tileState.wordNo];
  }

  /// Gets the letter color of a specific tile.
  Color getLetterColor(TileState tileState) {
    Color color;
    if (tileState.selected != Picker.none) {
      color = style.letterSelected;
    } else {
      color = style.letterUnselected;
    }
    return color;
  }

  /// Gets the row for this tile, either visible row or 6x4 row.
  int _getRow(TileState tileState, [bool visible=true]) {
    final List<TileState> colTiles = puzzle[tileState.colNo];
    int rowNo = 0;
    for (int i = 0; i < ROW_COUNT; i++) {
      final TileState other = colTiles[i];
      if (other == tileState) {
        break;
      }
      if (visible && other.size == 0) {
        continue;
      }
      rowNo += 1;
    }
    return rowNo;
  }

  /// Returns TextStyle for a specific tile.
  TextStyle getTextStyle(TileState tileState) {
    return TextStyle(
      fontSize: MediaInfo.unscaled(tileState.size * 0.5),
    );
  }

  /// Assigns the tile colors at random depending on the level.
  ///
  /// The randomness has been previously created
  /// by shuffling randomWord and randomColor.
  void _getTileColors() {
    for (int i = 0; i < WORD_MAX; i++) {
      // pick a word at random
      final int wordNo = randomWord[i];
      // pick a random color for it
      final Color c =  style.choices[randomColor[wordNo]];
      _allColors[wordNo] = c;
      _wordColors[wordNo] = c;
    }
  }

  /// Returns an immutable object containing everything needed to draw a tile.
  TileDraw getTileDraw(int colNo, int rowNo) {
    final TileState tileState = puzzle[colNo][rowNo];
    return TileDraw(
      getBgColor(tileState),
      getLetterColor(tileState),
      tileState.letter,
      getTextStyle(tileState),
      tileState.wordNo,
      tileState.letterNo,
      tileState.size,
    );
  }

  /// Sets up a new or existing game
  void _newGame() {
    mode = Mode.deal;
    gameString = getGame();
    randomWord.shuffle();
    randomColor.shuffle();
    _getTileColors();
    _gameStringToCols(gameString);
    notifyListeners();
    _setMode(Mode.play);
  }

  /// Removes any existing selection.
  ///
  /// It removes one tile at a time, with a short delay between each,
  /// by calling itself back on a timer.
  void _removeSelection() {
    // Bail if there are no more selected tiles.
    if (selectedTiles.isEmpty) {
      return;
    }
    // Remove a letter at a time
    final TileState tile = selectedTiles.removeAt(0);
    tile.selected = Picker.none;
    tile.size = 0;
    notifyListeners();
    if (selectedTiles.isNotEmpty) {
      // If there are more letters to remove, do so.
      _removeSelection();
    } else {
      // All selected tiles have been removed; user can interact again
      if (mode == Mode.removing) {
        _setMode(Mode.play);
      }
    }
  }

  /// Resets all the tile states.
  void _resetTiles() {
    for (int colNo = 0; colNo < puzzle.length; colNo++) {
      final List<TileState> col = puzzle[colNo];
      for (int rowNo = 0; rowNo < col.length; rowNo++) {
        col[rowNo].reset(_tileSize);
      }
    }
    selectedTiles = <TileState>[];
  }

  /// (Un)selects a single tile for various actors (see Picker in tile_state).
  ///
  /// Returns true if a word (== 4 tiles, valid or not) is selected.
  bool select(int colNo, int rowNo, Picker picker) {
    // User has (un)selected a tile
    final TileState tileState = puzzle[colNo][rowNo];
    // The rowNo supplied includes invisible tiles, so recalculate it
    rowNo = _getRow(tileState);
    selectedTiles.add(tileState);
    tileState.selected = picker;
    _removeSelection();
    notifyListeners();
    return true;
  }

  /// Performs actions after winning a game.
  ///
  /// It's only public so that dev_screen can use it.
  void winGame() {
    // Display last game
    mode = Mode.won;
    _resetTiles();
    notifyListeners();
    // At this point, we are either waiting for user to respond to the bonus
    // or reward dialog, or for user to tap on the status.
    // tapped() will call _newGame.
  }

  void _setMode(Mode m) {
    // The reason for putting this in a function is that the status is always
    // going to change and it saves the caller from having to do that.
    // assert(mode != m);
    mode = m;
  }
}

//===========================MAIN.DART=========================

/// Executes various async startup requirements.
Future<Model> setup(Model model) async {
  // populate model with saved values
  await model.setUp();
  return model;
}

Future<void> main() async {
  // ensureInitialized avoids various startup failures
  WidgetsFlutterBinding.ensureInitialized();

  final Model model = Model();
  await setup(model);

  runApp(
    ChangeNotifierProvider<Model>(
      create: (BuildContext context) => model,
      child: MyApp(model),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp(this.model, {super.key});
  final Model model;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'lerp failure',
      theme: ThemeData(
        primarySwatch: Style.normalTheme,
        scaffoldBackgroundColor: Style.screenBackground,
        appBarTheme: AppBarTheme(
          foregroundColor: Colors.white,
        backgroundColor: Style.normalTheme,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            foregroundColor: Colors.white,
            backgroundColor: Style.normalTheme,
            disabledForegroundColor: Colors.black26,
          ),
        ),
        sliderTheme: SliderThemeData(
          activeTrackColor: Style.normalTheme,
          // inactiveTrackColor: Colors.black12,
          thumbColor: Style.normalTheme,
        ),
      ),
      home: const PlayScreen(),
    );
  }
}

//===========================spacer.dart======================================

/// Returns a box of size [w] x [h] with optional [color].
SizedBox spacer(double w, double h, [Color? color = Colors.black]) {
  Widget? decor;
  if (color != Colors.black) {
    decor = DecoratedBox(
      decoration: BoxDecoration(
        color: color,
      ),
    );
  }
  return SizedBox(
    width: w,
    height: h,
    child: decor,
  );
}

//===========================game_widget.dart=========================

class TileColumnWidget extends StatelessWidget {
  const TileColumnWidget(this.col, this.tileSize, {super.key});
  final int col;
  final double tileSize;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Tile(col: col, row: 3, key: UniqueKey()),
        Tile(col: col, row: 2, key: UniqueKey()),
        Tile(col: col, row: 1, key: UniqueKey()),
        Tile(col: col, row: 0, key: UniqueKey()),
        SizedBox(width: tileSize, height: tileSize * buttonGap),
      ],
    );

  }
}

const double gamePadding = 0.25;  // Pad the game above and below by this * tileSize
const double buttonGap = 0.5;     // Separate the game and the buttons by this * tileSize
GlobalKey _key = GlobalKey();     // Global key helps get the widget's position

class GameWidget extends StatefulWidget {
  const GameWidget(this.tileSize, {super.key});
  final double tileSize;

  @override
  State<GameWidget> createState() => _GameWidgetState();
}

class _GameWidgetState extends State<GameWidget> {
  late double orgX;
  Dragging dragState = Dragging.allowed;

  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback(_afterLayout);
    super.initState();
  }

  /// Calback when object has finished rendering.
  ///
  /// At this point, we can determine the size and position on-screen, see
  /// https://www.woolha.com/tutorials/flutter-get-widget-size-and-position
  void _afterLayout(_) {
    final BuildContext? context = _key.currentContext;
    if (context != null) {
      final RenderObject? renderObj = context.findRenderObject();
      if (renderObj != null) {
        // The row of [TileColumnWidget]s uses MainAxisAlignment.center, and in
        // landscape mode, there may be extra space at the left and right.
        // Determine the size of this space for selectTile() so it can take it
        // into account when calculating which tile is being touched.
        // (This conveniently handles the SizedBox that preceds the columns.)
        final RenderBox box = renderObj as RenderBox;
        orgX = (box.size.width - COL_COUNT * widget.tileSize) / 2;
      }
    }
  }

  /// The user has touched the widget.
  void panDown(DragDownDetails details) {
    dragState = Dragging.allowed;
    selectTile(details.localPosition);
  }

  /// The user is dragging within the widget.
  void panUpdate(DragUpdateDetails details) {
    if (dragState != Dragging.done) {
      selectTile(details.localPosition);
    }
  }

  /// Selects the tile being touched.
  ///
  /// It does this by:
  /// * using local [offset], i.e. relative to the origin of the GestureDetector
  /// * adjusting for space at the left, see commentary in_afterLayout()
  /// * dividing by [tileSize] to get column and row indices
  void selectTile(Offset offset) {
    int col = (offset.dx - orgX) ~/ widget.tileSize;
    int row = ROW_COUNT - 1 - offset.dy ~/ widget.tileSize;
    if (col < COL_COUNT && row < ROW_COUNT) {
      // DEBUG HACKS
      if (col < 0) {
        col = 0;
      }
      if (row < 0) {
        row = 0;
      }
      dragState = context.read<Model>().drag(col, row);
    }
  }

  @override
  Widget build(BuildContext context) {
    final double boxHeight = widget.tileSize * (ROW_COUNT + buttonGap);
    return GestureDetector(
      key: _key,
      onPanDown: panDown,
      onPanUpdate: panUpdate,
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.end,
        children: <Widget>[
          SizedBox(width: 1, height: boxHeight),
          TileColumnWidget(0, widget.tileSize),
          TileColumnWidget(1, widget.tileSize),
          TileColumnWidget(2, widget.tileSize),
          TileColumnWidget(3, widget.tileSize),
          TileColumnWidget(4, widget.tileSize),
          TileColumnWidget(5, widget.tileSize),
          SizedBox(width: 1, height: boxHeight),
        ],
      ),
    );
  }
}

//===========================PLAY_SCREEN.DART=========================

/// Lays out the widgets vertically.
class PortraitWidget extends StatelessWidget {
  const PortraitWidget(
    this.width,
    this.tileSize,
    {super.key});
  final double width;
  final double tileSize;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Part2Widget(MediaInfo.tileSize),
      ],
    );
  }
}

/// Gets the widgets making up part 2, the game.
class Part2Widget extends StatelessWidget {
  const Part2Widget(this.tileSize, {super.key});
    final double tileSize;// = MediaInfo.tileSize;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
      GameWidget(tileSize),
    ]);
  }
}

class PlayScreen extends StatefulWidget {
  const PlayScreen({super.key});

  @override
  PlayScreenState createState() => PlayScreenState();
}

class PlayScreenState extends State<PlayScreen> {

  @override
  Widget build(BuildContext context) {
    // Get screen size and determine tile size
    final MediaInfo info = MediaInfo();
    info.init(context);

    // First time through, width==0 => negative tileSize => crash
    if (MediaInfo.tileSize > 0) {
      // If tile size has changed, update model and force a full redraw.
      // This is needed to make tiles change their size.
      final double oldSize = Provider.of<Model>(context, listen: false).tileSize;
      if (MediaInfo.tileSize != oldSize) {
        Provider.of<Model>(context, listen: false).tileSize = MediaInfo.tileSize;
      }
    }
    return Scaffold(
      // backgroundColor: bgColor,
      appBar: AppBar(
        title: const Text('lerp failure'),
        backgroundColor: Style.normalTheme,
        // actions: icons,
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          PortraitWidget(
            MediaInfo.width1,
            MediaInfo.tileSize,
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![dart-diff](https://github.com/flutter/flutter/assets/8864679/af5745d7-700b-4eda-9859-9a9eada9a621)
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
>flutter doctor -v
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version
    10.0.19045.3693], locale en-US)
    • Flutter version 3.16.2 on channel stable at E:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (8 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc5)
    • Android SDK at C:\Users\Phil\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0-rc5
    • Java binary at: E:\devtools\Android\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at E:\devtools\Android
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\Phil\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (4 available)
    • Pixel 7 Pro (mobile) • 29301FDH300434 • android-arm64  • Android 14 (API
      34)
    • Windows (desktop)    • windows        • windows-x64    • Microsoft Windows
      [Version 10.0.19045.3693]
    • Chrome (web)         • chrome         • web-javascript • Google Chrome
      109.0.5414.149
    • Edge (web)           • edge           • web-javascript • Microsoft Edge
      119.0.2151.97

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by philmayes** [comment]
Closing the issue. This was my bug. The code to reverse text scaling gave NaN when text size was 0.
