### ISSUE TITLE
Race condition when manipulate same `ChildVicinity`

### ISSUE THREAD

**Issue by definev** [flutter/flutter#140094]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I create custom infinity canvas with new two dimensional scrolling API. Checkout example project in [here](https://github.com/definev/widget_canvas/tree/main/example)

My implementation convention for `ChildVicinity` is:
- `yIndex: 1`: Vertical divider
- `yIndex: 2`: Horizontal divider
- `yIndex: 3`: Where the `CanvasElement` laid out

The `getVisibleElement` function to find all element visible in viewport. I implement an wrapper for sorting `List<CanvasElement>` and binary searching part of visible list.

See `WidgetCanvasChildDelegate`:
```dart
class WidgetCanvasChildDelegate extends TwoDimensionalChildDelegate {
  WidgetCanvasChildDelegate({
    required this.elements,
    required this.builder,
    this.showGrid = true,
    this.dimension = 100,
  });

  static Comparator<CanvasElement> defaultCompare(Axis axis) => switch (axis) {
        Axis.horizontal => (a, b) => a.offset.dx.compareTo(b.offset.dx),
        Axis.vertical => (a, b) => a.offset.dy.compareTo(b.offset.dy),
      };

  final BinaryList<CanvasElement> elements;
  final Widget Function(BuildContext context, CanvasElement element) builder;
  final bool showGrid;
  final double dimension;

  Map<ChildVicinity, CanvasElement> _sortedElements = {};
  List<(ChildVicinity, CanvasElement)> getVisibleElement(Offset topLeft, Offset bottomRight) {
    ...
  }

  (ChildVicinity, CanvasElement) _toVicinity(o) {
    final copyVicinity = o.vicinity;
    _sortedElements[copyVicinity] = o;
    return (copyVicinity, o);
  }

  @override
  Widget? build(BuildContext context, ChildVicinity vicinity) {
    if (vicinity.yIndex == 1) {
      return const VerticalDivider(width: 1);
    }
    if (vicinity.yIndex == 2) {
      return const Divider(height: 1);
    }
    if (_sortedElements[vicinity] case final element?) {
      return builder(context, element);
    }

    return null;
  }

  @override
  bool shouldRebuild(covariant WidgetCanvasChildDelegate oldDelegate) =>
      oldDelegate.elements != elements || oldDelegate.showGrid != showGrid || oldDelegate.dimension != dimension;
}
```

---
The implementation for `WidgetCanvasRenderTwoDimensionalViewport` `layoutChildSequence` function:
```dart
  void layoutChildSequence() {
    final horizontalPixels = horizontalOffset.pixels;
    final verticalPixels = verticalOffset.pixels;
    final viewportHeight = viewportDimension.height + cacheExtent;
    final viewportWidth = viewportDimension.width + cacheExtent;

    final canvasDelegate = delegate as WidgetCanvasChildDelegate;
    if (canvasDelegate.showGrid) {
      final dimension = canvasDelegate.dimension;
      final baseColumn = (horizontalPixels / dimension).floor();
      for (var column = 0; column < viewportWidth ~/ dimension; column += 1) {
        if (buildOrObtainChildFor(ChildVicinity(xIndex: column, yIndex: 1)) case final child?) {
          child.layout(constraints.loosen());
          parentDataOf(child).layoutOffset = Offset((baseColumn + column) * dimension, 0) - Offset(horizontalPixels, 0);
        }
      }
      final baseRow = (verticalPixels / dimension).floor();
      for (var row = 0; row < viewportHeight ~/ dimension; row += 1) {
        if (buildOrObtainChildFor(ChildVicinity(xIndex: row, yIndex: 2)) case final child?) {
          child.layout(constraints.loosen());
          parentDataOf(child).layoutOffset = Offset(0, (baseRow + row) * dimension) - Offset(0, verticalPixels);
        }
      }
    }

    final elements = canvasDelegate.getVisibleElement(
      Offset(horizontalPixels, verticalPixels) - Offset(cacheExtent, cacheExtent),
      Offset(horizontalPixels + viewportWidth, verticalPixels + viewportHeight),
    );

    for (final (vicinity, element) in elements) {
      if (buildOrObtainChildFor(vicinity) case final child?) {
        child.layout(constraints.loosen());
        parentDataOf(child).layoutOffset = element.offset - Offset(horizontalPixels, verticalPixels);
      }
    }

    verticalOffset.applyContentDimensions(double.negativeInfinity, double.infinity);
    horizontalOffset.applyContentDimensions(double.negativeInfinity, double.infinity);
  }
```

### Expected results

Move `CanvasElement` freely

### Actual results

Throw `'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 316 pos 14: '_newVicinityToChild![vicinity] == null': is not true.`

### Code sample

<details><summary>Code sample</summary>

```dart
class HomeView extends StatefulWidget {
  const HomeView({super.key});

  @override
  State<HomeView> createState() => _HomeViewState();
}

class _HomeViewState extends State<HomeView> {
  final elements = ValueNotifier<BinaryList<CanvasElement>>(
    <CanvasElement>[].binaryList(WidgetCanvasChildDelegate.defaultCompare(Axis.horizontal)),
  );

  @override
  void initState() {
    super.initState();
    elements.value = <CanvasElement>[
      for (int i = 4; i < 17; i += 1)
        CanvasElement(
          id: i,
          offset: Offset(i % 5 * 100.0, i ~/ 5 * 100.0),
        ),
    ].binaryList(WidgetCanvasChildDelegate.defaultCompare(Axis.horizontal));
    elements.addListener(() =>  setState(() {}));
  }

  @override
  void dispose() {
    elements.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('App'),
      ),
      body: WidgetCanvas(
        diagonalDragBehavior: DiagonalDragBehavior.free,
        delegate: WidgetCanvasChildDelegate(
          showGrid: true,
          dimension: 100,
          elements: elements.value,
          builder: (context, element) => MovableCanvasElement(
            snap: false,
            dimension: 100,
            element: element,
            elements: elements,
            child: Card(
              margin: EdgeInsets.zero,
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text('${element.id} ${element.offset}'),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/62325868/bd97286d-d062-45cb-8245-b7e152d86701

</details>

### Logs

<details><summary>Logs</summary>

```console
Restarted application in 184ms.

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 316 pos 14: '_newVicinityToChild![vicinity] == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    WidgetCanvasTwoDimensionalViewport WidgetCanvasTwoDimensionalViewport:file:///Users/daiduong/Desktop/source/github.com/definev/widget_canvas/lib/src/widget_canvas.dart:27:12

When the exception was thrown, this was the stack:
#2      _TwoDimensionalViewportElement._buildChild.<anonymous closure> (package:flutter/src/widgets/two_dimensional_viewport.dart:316:14)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835:19)
#4      _TwoDimensionalViewportElement._buildChild (package:flutter/src/widgets/two_dimensional_viewport.dart:307:12)
#5      RenderTwoDimensionalViewport.buildOrObtainChildFor.<anonymous closure> (package:flutter/src/widgets/two_dimensional_viewport.dart:1427:23)
#6      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657:59)
#7      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071:15)
#8      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657:14)
#9      RenderTwoDimensionalViewport.buildOrObtainChildFor (package:flutter/src/widgets/two_dimensional_viewport.dart:1426:7)
#10     WidgetCanvasRenderTwoDimensionalViewport.layoutChildSequence (package:widget_canvas/src/widget_canvas.dart:136:13)
#11     RenderTwoDimensionalViewport.performLayout (package:flutter/src/widgets/two_dimensional_viewport.dart:1252:5)
#12     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
#13     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
#14     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
#15     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#16     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#17     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#20     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#21     _invoke (dart:ui/hooks.dart:312:13)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#23     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
The paint extent of the child has not been determined yet.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gestures library ══════════════════════════════════
The paint extent of the child has not been determined yet.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gestures library ══════════════════════════════════
The paint extent of the child has not been determined yet.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gestures library ══════════════════════════════════
The paint extent of the child has not been determined yet.
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.18.0-11.0.pre.12, on macOS 14.1.1 23B81 darwin-arm64, locale en-VN)
    • Flutter version 3.18.0-11.0.pre.12 on channel master at /Users/daiduong/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 11a9cb7029 (17 hours ago), 2023-12-12 20:09:13 -0800
    • Engine revision 9039ac78cf
    • Dart version 3.3.0 (build 3.3.0-219.0.dev)
    • DevTools version 2.30.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/daiduong/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Volumes/Data/Users/daiduong/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Volumes/Data/Users/daiduong/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10811636/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /Volumes/Data/Users/daiduong/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.8109.175/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Volumes/Data/Users/daiduong/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.8836.41/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Volumes/Data/Users/daiduong/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Volumes/Data/Users/daiduong/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.0)
    • VS Code at /Volumes/Data/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by definev** [comment]
please help me @Piinks

**Comment by definev** [comment]
Not working yet but have a bug in my code, close when i fix it. I duplicate 2 ChildVicinity in `getVisibleElement` function
