### ISSUE TITLE
[flutter_tools] UnsupportedError at _Uri._checkWindowsPathReservedCharacters when parsing directory entries with invalid characters in `assets` section in pubspec.yaml

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#140092]
On `beta/3.18.0-0.1.pre`.
Command: `run --machine --start-paused -d chrome --devtools-server-address http://127.0.0.1:9100/ --target <redacted>/<redacted>.dart`

Stack trace:
```
UnsupportedError: Unsupported operation: Illegal character in path: http:
at _Uri._checkWindowsPathReservedCharacters(uri.dart:1840)
at _Uri._toWindowsFilePath(uri.dart:2893)
at _Uri.toFilePath(uri.dart:2865)
at ManifestAssetBundle._parseAssetsFromFolder(asset.dart:895)
at ManifestAssetBundle._parseAssets(asset.dart:810)
at ManifestAssetBundle.build(asset.dart:265)
at <asynchronous gap>(async)
at ResidentWebRunner._updateDevFS(resident_web_runner.dart:527)
at <asynchronous gap>(async)
at ResidentWebRunner.run.<anonymous closure>(resident_web_runner.dart:320)
at <asynchronous gap>(async)
at asyncGuard.<anonymous closure>(async_guard.dart:111)
at <asynchronous gap>(async)
```

**Comment by andrewkolos** [comment]
14 crashes to-date from one user.

**Comment by andrewkolos** [comment]
I was able to reproduce this on my Windows 11 machine.

<details> 

<summary>`flutter doctor -v`</summary>

```
[√] Flutter (Channel stable, 3.13.8, on Microsoft Windows [Version 10.0.22621.2715], locale en-US)
    • Flutter version 3.13.8 on channel stable at C:\Users\Jozz\Documents\GitHub\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (8 weeks ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Jozz\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: E:\Programs\New folder\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34003.232
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at E:\Programs\New folder
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\Jozz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.79.20231130

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2715]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.71
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.61

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

Repro steps:
1) Create a new flutter project.
2) In the `assets` section of your pubspec, add a list item that includes `:` anywhere in the path.
3) `flutter run -d chrome` (the crash does not happen when using `-d windows`).

**Comment by andrewkolos** [comment]
> 14 crashes to-date from one user.

Addendum: there are about 250 crashes in total across various versions.

**Comment by andrewkolos** [comment]
Up to date stack traces as of 29db9dbd44b1dbf781a84318811db676aadd6fd7 (using `flutter run -d chrome`):

<details>
<summary> "http://whitehouse.gov/foo.png" </summary>

```

FileSystemException: FileSystemException: Exists failed, path = 'C:\Users\Jozz\Desktop\deleteme\assets_test\http:\\whitehouse.gov' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)

#0      _Directory.existsSync (dart:io/directory_impl.dart:87:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:490:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:489:12)
#5      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1254:43)
#6      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:974:37)
#7      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:829:9)
#8      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:267:54)
<asynchronous suspension>
#9      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:531:26)
<asynchronous suspension>
#10     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:319:41)
<asynchronous suspension>
#11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```

</details>


<details>
<summary> "http://whitehouse.gov/pictures/" </summary>

```

UnsupportedError: Unsupported operation: Illegal character in path: http:

#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1840:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2893:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2865:38)
#3      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:916:29)
#4      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:817:9)
#5      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:267:54)
<asynchronous suspension>
#6      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:531:26)
<asynchronous suspension>
#7      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:319:41)
<asynchronous suspension>
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
</details>

Another thing to note is that if I instead use `flutter run -d windows`, I don't get a crash. Instead, I get an error from VS that's even less useful than a crash:

```
Launching lib\main.dart on Windows in debug mode...
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: Custom build for 'C:\Users\Jozz\Desktop\deleteme\assets_test\build\windows\x64\CMakeFiles\2103228256e52c9a1428711c685a3aa3\flutter_windows.dll.rule;C:\Users\Jozz\Desktop\deleteme\assets_test\build\windows\x64\CMakeFiles\b847e1c2ab5b4b4fa16f57a4fdf59571\flutter_assemble.rule' exited with code 1. [C:\Users\Jozz\Desktop\deleteme\assets_test\build\windows\x64\flutter\flutter_assemble.vcxproj]
Building Windows application...                                     5.9s
Error: Build process failed.
```
