### ISSUE TITLE
Error in integration_test on timeout: '!inTest': is not true.

### ISSUE THREAD

**Issue by vcgupta-indihood** [flutter/flutter#140149]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In any flutter project follow below steps:

1. Create file `test_driver/main_test.dart`
```
import 'dart:io';
import 'package:integration_test/integration_test_driver_extended.dart';

Future<void> main() async {
  print('Starting test driver');

  try {
    var driver = await integrationDriver(
      onScreenshot: (
        String screenshotName,
        List<int> screenshotBytes, [
        Map<String, Object?>? metadata,
      ]) async {
        final File image = await File('screenshots/$screenshotName.png')
            .create(recursive: true);
        image.writeAsBytesSync(screenshotBytes);
        return true;
      },
    );
  } catch (err) {
    print('Error occurred $err');
  }
}
```
2. Create file `integration_/main.dart` and add below code:
```
import 'dart:async';

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import '../lib/main.dart' as app_main;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  group("All tests", () {
    setUpAll(() async {
      print("Setup all is run");
      app_main.main();
    });
    testWidgets("first test", (widgetTester) async {
      // This should get successful.
      await widgetTester.pumpAndSettle();
      print("First test is run");
    });
    testWidgets("second test", (widgetTester) async {
      // This should get successful.
      await widgetTester.pumpAndSettle();
      print("Second test is run");
    });
    testWidgets("third test", (widgetTester) async {
      // This will throw test error.
      await widgetTester.pumpAndSettle();
      print("Third test is starting");
      print("tapped button");

      TestAsyncUtils.guard(() async {
        await Future.delayed(Duration(seconds: 15));
      });
      await widgetTester.pumpAndSettle();
      print("Third test is finished");
    }, timeout: const Timeout(Duration(seconds: 10)));

    testWidgets("last test", (widgetTester) async {
      // This should get successful. but its not
      await widgetTester.pumpAndSettle();
      print("last test is run");
    });
  });
}

```
3. Add project dev_dependecies in pubspec.yaml:
```
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
```
4. Run following command
`flutter driver --target=integration_test/main.dart`

It will have errors.

### Expected results

The `last test` in integration_test should be independently run successful without getting affected from `third test` failure. 

### Actual results

The last test fails due to Timeout failure in Third test.

### Code sample

<details><summary>Integration test file</summary>

```dart
import 'dart:async';

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import '../lib/main.dart' as app_main;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  group("All tests", () {
    setUpAll(() async {
      print("Setup all is run");
      app_main.main();
    });
    testWidgets("first test", (widgetTester) async {
      // This should get successful.
      await widgetTester.pumpAndSettle();
      print("First test is run");
    });
    testWidgets("second test", (widgetTester) async {
      // This should get successful.
      await widgetTester.pumpAndSettle();
      print("Second test is run");
    });
    testWidgets("third test", (widgetTester) async {
      // This will throw test error.
      await widgetTester.pumpAndSettle();
      print("Third test is starting");
      print("tapped button");

      TestAsyncUtils.guard(() async {
        await Future.delayed(Duration(seconds: 15));
      });
      await widgetTester.pumpAndSettle();
      print("Third test is finished");
    }, timeout: const Timeout(Duration(seconds: 10)));

    testWidgets("last test", (widgetTester) async {
      // This should get successful. but its not
      await widgetTester.pumpAndSettle();
      print("last test is run");
    });
  });
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs from above project</summary>

```console

I/flutter (18171): 03:00 +1 -1: Home page tests test_desc-1 [E]
I/flutter (18171):   'package:flutter_test/src/binding.dart': Failed assertion: line 1960 pos 12: '!inTest': is not true.
I/flutter (18171):   dart:core-patch/errors_patch.dart 51:61                _AssertionError._doThrowNew
I/flutter (18171):   dart:core-patch/errors_patch.dart 40:5                 _AssertionError._throwNew
I/flutter (18171):   package:flutter_test/src/binding.dart 1960:12          LiveTestWidgetsFlutterBinding.runTest
I/flutter (18171):   package:integration_test/integration_test.dart 239:17  IntegrationTestWidgetsFlutterBinding.runTest
I/flutter (18171):   package:flutter_test/src/widget_tester.dart 158:24     testWidgets.<fn>
I/flutter (18171):   package:test_api/src/backend/declarer.dart 215:19      Declarer.test.<fn>.<fn>
I/flutter (18171):   ===== asynchronous gap ===========================
I/flutter (18171):   package:test_api/src/backend/declarer.dart 213:7       Declarer.test.<fn>
I/flutter (18171):   ===== asynchronous gap ===========================
I/flutter (18171):   package:test_api/src/backend/invoker.dart 258:9        Invoker._waitForOutstandingCallbacks.<fn>
I/flutter (18171):
I/flutter (18171):   'package:flutter_test/src/binding.dart': Failed assertion: line 1984 pos 12: '!_expectingFrame': is not true.
I/flutter (18171):   dart:core-patch/errors_patch.dart 51:61           _AssertionError._doThrowNew
I/flutter (18171):   dart:core-patch/errors_patch.dart 40:5            _AssertionError._throwNew
I/flutter (18171):   package:flutter_test/src/binding.dart 1984:12     LiveTestWidgetsFlutterBinding.postTest
I/flutter (18171):   dart:async/future.dart 305:31                     new Future.sync
I/flutter (18171):   package:test_api/src/backend/invoker.dart 236:18  Invoker.runTearDowns.<fn>.<fn>
I/flutter (18171):   package:test_api/src/backend/invoker.dart 258:17  Invoker._waitForOutstandingCallbacks.<fn>
I/flutter (18171):   dart:async/zone.dart 1399:13                      _rootRun
I/flutter (18171):   dart:async/zone.dart 1301:19                      _CustomZone.run
I/flutter (18171):   dart:async/zone.dart 1804:10                      _runZoned
I/flutter (18171):   dart:async/zone.dart 1747:10                      runZoned
I/flutter (18171):   package:test_api/src/backend/invoker.dart 254:5   Invoker._waitForOutstandingCallbacks
I/flutter (18171):   package:test_api/src/backend/invoker.dart 235:9   Invoker.runTearDowns.<fn>
I/flutter (18171):   dart:async/zone.dart 1399:13                      _rootRun
I/flutter (18171):   dart:async/zone.dart 1301:19
```

</details>

<details><summary>Other logs from my private project</summary>
```console
I/flutter (18171): 03:00 +1 -1: Home page tests test_desc-1 [E]
I/flutter (18171):   'package:flutter_test/src/binding.dart': Failed assertion: line 1960 pos 12: '!inTest': is not true.
I/flutter (18171):   dart:core-patch/errors_patch.dart 51:61                _AssertionError._doThrowNew
I/flutter (18171):   dart:core-patch/errors_patch.dart 40:5                 _AssertionError._throwNew
I/flutter (18171):   package:flutter_test/src/binding.dart 1960:12          LiveTestWidgetsFlutterBinding.runTest
I/flutter (18171):   package:integration_test/integration_test.dart 239:17  IntegrationTestWidgetsFlutterBinding.runTest
I/flutter (18171):   package:flutter_test/src/widget_tester.dart 158:24     testWidgets.<fn>
I/flutter (18171):   package:test_api/src/backend/declarer.dart 215:19      Declarer.test.<fn>.<fn>
I/flutter (18171):   ===== asynchronous gap ===========================
I/flutter (18171):   package:test_api/src/backend/declarer.dart 213:7       Declarer.test.<fn>
I/flutter (18171):   ===== asynchronous gap ===========================
I/flutter (18171):   package:test_api/src/backend/invoker.dart 258:9        Invoker._waitForOutstandingCallbacks.<fn>
I/flutter (18171):
I/flutter (18171):   'package:flutter_test/src/binding.dart': Failed assertion: line 1984 pos 12: '!_expectingFrame': is not true.
I/flutter (18171):   dart:core-patch/errors_patch.dart 51:61           _AssertionError._doThrowNew
I/flutter (18171):   dart:core-patch/errors_patch.dart 40:5            _AssertionError._throwNew
I/flutter (18171):   package:flutter_test/src/binding.dart 1984:12     LiveTestWidgetsFlutterBinding.postTest
I/flutter (18171):   dart:async/future.dart 305:31                     new Future.sync
I/flutter (18171):   package:test_api/src/backend/invoker.dart 236:18  Invoker.runTearDowns.<fn>.<fn>
I/flutter (18171):   package:test_api/src/backend/invoker.dart 258:17  Invoker._waitForOutstandingCallbacks.<fn>
I/flutter (18171):   dart:async/zone.dart 1399:13                      _rootRun
I/flutter (18171):   dart:async/zone.dart 1301:19                      _CustomZone.run
I/flutter (18171):   dart:async/zone.dart 1804:10                      _runZoned
I/flutter (18171):   dart:async/zone.dart 1747:10                      runZoned
I/flutter (18171):   package:test_api/src/backend/invoker.dart 254:5   Invoker._waitForOutstandingCallbacks
I/flutter (18171):   package:test_api/src/backend/invoker.dart 235:9   Invoker.runTearDowns.<fn>
I/flutter (18171):   dart:async/zone.dart 1399:13                      _rootRun
I/flutter (18171):   dart:async/zone.dart 1301:19
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.13.6, on macOS 13.2.1 22D68 darwin-arm64, locale en-IN)                                                                                                                             ok  18:20:30 
    ! Flutter version 3.13.6 on channel [user-branch] at /Users/vcgupta/Documents/Tools/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision ead455963c (3 months ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/vcgupta/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/vcgupta/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/vcgupta/Desktop/Archived/Android Studio - Flamingo | 2022.2.1 Patch 1/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
    • IntelliJ at /Users/vcgupta/Desktop/Archived/IntelliJ IDEA CE/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 120.0.6099.71

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
> 4\. Run following command
>     `flutter driver --target=integration_test/main.dart`

@vcgupta-indihood You seem to be using `flutter driver` command, but after updates made to integration_test framework, you can simply run `flutter test integration_test` that'll run all the tests in the directory.
you can read more about it here: https://docs.flutter.dev/testing/integration-tests#running-using-the-flutter-command and see if it helps to resolve the error or still get the same error.

**Comment by vcgupta-indihood** [comment]
I get the same error. Following are logs:
```console
> flutter test integration_test/main.dart
00:00 +0: loading /Users/vcgupta/source/bug/integration_test/main.dart                                                                                                                                                                 R00:07 +0: loading /Users/vcgupta/source/bug/integration_test/main.dart                                                                                                                                                             7.7s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
00:08 +0: loading /Users/vcgupta/source/bug/integration_test/main.dart                                                                                                                                                                 I00:09 +0: loading /Users/vcgupta/source/bug/integration_test/main.dart                                                                                                                                                            554ms
00:10 +0: All tests (setUpAll)                                                                                                                                                                                                         
Setup all is run
00:11 +0: All tests first test                                                                                                                                                                                                         
First test is run
00:11 +1: All tests second test                                                                                                                                                                                                        
Second test is run
00:11 +2: All tests third test                                                                                                                                                                                                         
Third test is starting
tapped button
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Guarded function conflict.
You must use "await" with all Future-returning test APIs.
The guarded method "<anonymous" from class main was called from
package:stack_trace/src/stack_zone_specification.dart on line 124.
Then, the "pumpAndSettle" method from class WidgetTester was called from
file:///Users/vcgupta/source/bug/integration_test/main.dart on line 33.
The first method (main.<anonymous) had not yet finished executing at the time that the second method
(WidgetTester.pumpAndSettle) was called. Since both are guarded, and the second was not a nested
call inside the first, the first must complete its execution before the second can be called.
Typically, this is achieved by putting an "await" statement in front of the call to the first.

When the first method (main.<anonymous) was called, this was the stack:
#0      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:66:54)
#1      main.<anonymous closure>.<anonymous closure> (file:///Users/vcgupta/source/bug/integration_test/main.dart:30:22)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

When the exception was thrown, this was the stack:
#0      TestAsyncUtils.guardSync (package:flutter_test/src/test_async_utils.dart:270:5)
#1      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:60:5)
#2      WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:697:27)
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/vcgupta/source/bug/integration_test/main.dart:33:26)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  third test
════════════════════════════════════════════════════════════════════════════════════════════════════
00:11 +2 -1: All tests third test [E]                                                                                                                                                                                                  
  Test failed. See exception logs above.
  The test description was: third test
  

To run this test again: /Users/vcgupta/Documents/Tools/flutter/bin/cache/dart-sdk/bin/dart test /Users/vcgupta/source/bug/integration_test/main.dart -p vm --plain-name 'All tests third test'
00:11 +2 -1: All tests last test                                                                                                                                                                                                       
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Guarded function conflict.
You must use "await" with all Future-returning test APIs.
The guarded method "<anonymous" from class main was called from
package:stack_trace/src/stack_zone_specification.dart on line 124.
Then, the "pump" method from class LiveTestWidgetsFlutterBinding was called from
package:flutter_test/src/binding.dart on line 971.
The first method (main.<anonymous) had not yet finished executing at the time that the second method
(LiveTestWidgetsFlutterBinding.pump) was called. Since both are guarded, and the second was not a
nested call inside the first, the first must complete its execution before the second can be called.
Typically, this is achieved by putting an "await" statement in front of the call to the first.

When the first method (main.<anonymous) was called, this was the stack:
#0      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:66:54)
#1      main.<anonymous closure>.<anonymous closure> (file:///Users/vcgupta/source/bug/integration_test/main.dart:30:22)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

When the exception was thrown, this was the stack:
#0      TestAsyncUtils.guardSync (package:flutter_test/src/test_async_utils.dart:270:5)
#1      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:60:5)
#2      LiveTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1909:27)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:971:11)
#6      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:960:14)
#7      LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1963:12)
#8      IntegrationTestWidgetsFlutterBinding.runTest (package:integration_test/integration_test.dart:239:17)
#9      testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:158:24)
#10     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The test description was:
  last test
════════════════════════════════════════════════════════════════════════════════════════════════════
00:11 +2 -2: All tests last test [E]                                                                                                                                                                                                   
  Test failed. See exception logs above.
  The test description was: last test
  

To run this test again: /Users/vcgupta/Documents/Tools/flutter/bin/cache/dart-sdk/bin/dart test /Users/vcgupta/source/bug/integration_test/main.dart -p vm --plain-name 'All tests last test'
00:11 +2 -2: Some tests failed.                                                                                                                                                                                                        


```

**Comment by vcgupta-indihood** [comment]
As this is just demo project tests I created. In actual project I have multiple test files having separate group, each group having multiple `testWidgets`. All tests starts failing once one of them is failed due to framework errors. It seems timeout errors within framework are not handled properly to release `test runner` and variables like `inTest` and `_expectingFrame` are not reset to run next test case without issues.

**Comment by darshankawar** [comment]
@vcgupta-indihood 
I followed the [documentation](https://docs.flutter.dev/cookbook/testing/integration/introduction) and used your code snippet in it with which I didn't get the reported error.
Looking at your code implementation, I think the usage of below is causing the behavior:

```
TestAsyncUtils.guard(() async {
        await Future.delayed(Duration(seconds: 15));
      });
      await widgetTester.pumpAndSettle();
```

The error says below:

```
The following assertion was thrown running a test:
Guarded function conflict.
You must use "await" with all Future-returning test APIs.
The guarded method "<anonymous" from class main was called from
package:stack_trace/src/stack_zone_specification.dart on line 124.
Then, the "pump" method from class LiveTestWidgetsFlutterBinding was called from
package:flutter_test/src/binding.dart on line 971.
The first method (main.<anonymous) had not yet finished executing at the time that the second method
(LiveTestWidgetsFlutterBinding.pump) was called. Since both are guarded, and the second was not a
nested call inside the first, the first must complete its execution before the second can be called.
Typically, this is achieved by putting an "await" statement in front of the call to the first.
```

That indicates the code implementation need to be carefully revisited and check how you are using / calling the `await` including `pump` method.

**Comment by vcgupta-indihood** [comment]
Hi @darshankawar 

I have created a git repo to repro the issue I am facing. The exact same issue appears for me.

https://github.com/vcgupta/flutter-integration-test-bug/

**Comment by darshankawar** [comment]
Thanks for the update. Using it, I was able to see the same error as reported originally.

```
_test/app_test.dart -p vm --plain-name 'All tests third test'
00:29 +2 -2: All tests last test [E]                                                                                                                                       
  'package:flutter_test/src/binding.dart': Failed assertion: line 2015 pos 12: '!inTest': is not true.
  dart:core                                                                                                               _AssertionError._throwNew
  package:flutter_test/src/binding.dart 2015:12                                                                           LiveTestWidgetsFlutterBinding.runTest
  package:integration_test/integration_test.dart 234:17                                                                   IntegrationTestWidgetsFlutterBinding.runTest
  package:flutter_test/src/widget_tester.dart 161:24                                                                      testWidgets.<fn>
  ===== asynchronous gap ===========================
  package:stream_channel                                                                                                  _GuaranteeSink.add
  /var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/flutter_tools.4EKKPe/flutter_test_listener.QSYk0p/listener.dart 53:22  main.<fn>
  
  'package:flutter_test/src/binding.dart': Failed assertion: line 2039 pos 12: '!_expectingFrame': is not true.
  dart:core                                                                                                               _AssertionError._throwNew
  package:flutter_test/src/binding.dart 2039:12                                                                           LiveTestWidgetsFlutterBinding.postTest
  ===== asynchronous gap ===========================
  package:stream_channel                                                                                                  _GuaranteeSink.add
  /var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/flutter_tools.4EKKPe/flutter_test_listener.QSYk0p/listener.dart 53:22  main.<fn>
  

To run this test again: /Users/dhs/documents/fluttersdk/flutter/bin/cache/dart-sdk/bin/dart test /Users/dhs/Documents/NCFlutter/flutter-integration-test-bug/bug/integration_test/app_test.dart -p vm --plain-name 'All tests last test'
00:29 +2 -2: Some tests failed.  
```

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.16.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.16.3 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (5 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.18.0-11.0.pre.111, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.18.0-11.0.pre.111 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6368d65622 (25 minutes ago), 2023-12-18 20:28:09 -0800
    • Engine revision bbfee6f59b
    • Dart version 3.3.0 (build 3.3.0-241.0.dev)
    • DevTools version 2.31.0-dev.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by vcgupta-indihood** [comment]
Hi @darshankawar 

Thank you for considering the bug. I was going through your suggestion to run tests using `flutter test integration_test/test_name.dart`. I have additional setup for `flutter driver` in `test_driver/test_name_test.dart` but it is not being called. It contains following code:

```

Future<void> main() async {
  print('Before Granting Permission: integration_driver');
  await grantPermissionsUsingShellCommand();

  try {
    var driver = await integrationDriver(
      onScreenshot: (
        String screenshotName,
        List<int> screenshotBytes, [
        Map<String, Object?>? metadata,
      ]) async {
        final File image = await File('screenshots/$screenshotName.png')
            .create(recursive: true);
        image.writeAsBytesSync(screenshotBytes);
        return true;
      },
    );
  } catch (err) {
    print('Error occurred $err');
  }
}
```

What is param to provide driver setup file path to `flutter test` command for integration driver
