### ISSUE TITLE
Exception: `DraggableScrollableSheet` with `StatefulWidget` calls `markNeedsBuild` During Build

### ISSUE THREAD

**Issue by natsuk4ze** [flutter/flutter#140214]
### I have not yet figured out the least code for a reliable method. Please use the sample code below.

1. Wrap a `DraggableScrollableSheet` with a `StatefullWidget`.
2. Drag hard as shown in the video below.

### Expected results

Works without Exception.

### Actual results

Exception caught by foundation library.

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() => runApp(const App());

class App extends StatefulWidget {
  const App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        bottomSheet: DraggableScrollableSheet(
          builder: (BuildContext context, ScrollController scrollController) =>
              Container(
            color: Colors.blue[100],
            child: ListView.builder(
              controller: scrollController,
              itemCount: 25,
              itemBuilder: (BuildContext context, int index) =>
                  ListTile(title: Text('Item $index')),
            ),
          ),
        ),
        body: Container(),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/50433979/16aa5556-a58b-4122-96e1-7a879236bc12

</details>

### Logs

<details open><summary>Logs</summary>

```console

════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for _ResetNotifier:
setState() or markNeedsBuild() called during build.
This _InheritedResetNotifier widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: _InheritedResetNotifier
The widget which was currently being built when the offending call was made was: DraggableScrollableSheet
    dirty
    dependencies: [_InheritedResetNotifier]
    state: _DraggableScrollableSheetState#b6f45

When the exception was thrown, this was the stack:
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:5042:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5054:6)
#2      _InheritedNotifierElement._handleUpdate (package:flutter/src/widgets/inherited_notifier.dart:118:5)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
#4      _ResetNotifier.sendReset (package:flutter/src/widgets/draggable_scrollable_sheet.dart:1075:5)
#5      _InheritedResetNotifier._sendReset (package:flutter/src/widgets/draggable_scrollable_sheet.dart:1088:34)
#6      DraggableScrollableActuator.reset (package:flutter/src/widgets/draggable_scrollable_sheet.dart:1032:21)
#7      ScaffoldState._maybeBuildPersistentBottomSheet.persistentBottomSheetExtentChanged.<anonymous closure> (package:flutter/src/material/scaffold.dart:2213:43)
#8      LocalHistoryEntry._notifyRemoved (package:flutter/src/widgets/routes.dart:524:15)
#9      LocalHistoryRoute.removeLocalHistoryEntry (package:flutter/src/widgets/routes.dart:702:11)
#10     LocalHistoryEntry.remove (package:flutter/src/widgets/routes.dart:519:13)
#11     ScaffoldState._maybeBuildPersistentBottomSheet.persistentBottomSheetExtentChanged (package:flutter/src/material/scaffold.dart:2221:41)
#12     _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#13     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3320:18)
#14     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3323:13)
#15     Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4942:24)
#16     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#17     _DraggableSheetExtent.updateSize (package:flutter/src/widgets/draggable_scrollable_sheet.dart:581:7)
#18     _DraggableScrollableSheetScrollController.reset (package:flutter/src/widgets/draggable_scrollable_sheet.dart:825:12)
#19     _DraggableScrollableSheetState.didChangeDependencies (package:flutter/src/widgets/draggable_scrollable_sheet.dart:680:25)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5640:13)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#22     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#23     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#24     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#25     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#26     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#27     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#28     _invoke (dart:ui/hooks.dart:312:13)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:382:5)
#30     _drawFrame (dart:ui/hooks.dart:283:31)

The _ResetNotifier sending notification was: Instance of '_ResetNotifier'
════════════════════════════════════════════════════════════════════════════════
Restarted application in 595ms.

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.18.0-0.2.pre, on macOS 14.2 23C64 darwin-arm64, locale ja-JP)
    • Flutter version 3.18.0-0.2.pre on channel beta at /Users/xxx/Hack/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fed06b31d9 (2 days ago), 2023-12-13 14:53:33 -0800
    • Engine revision 39c6dc9bdd
    • Dart version 3.3.0 (build 3.3.0-174.3.beta)
    • DevTools version 2.30.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • iPhone 13 mini (mobile) • 00008110-0019388A3E98801E            • ios            • iOS 17.3 21D5026f
    • iPhone 15 (mobile)      • 0E947B51-7F23-4C2E-839A-86B51D892881 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @natsuk4ze, do you only experience this issue on the simulator or are physical devices affected as well? How many times to you have to perform the motion to reproduce the issue? 

Is there an easier way to reproduce the issue? If so, kindly share it. I tried to reproduce it on my physical device, but it hasn't reproduced for me yet

**Comment by natsuk4ze** [comment]
Hi @danagbemava-nc 

I can reproduce it only in the simulator so far.

**Comment by danagbemava-nc** [comment]
Hi @natsuk4ze, 1 more thing, did this only happen in the iOS simulator or did it reproduce for you with the android emulator as well?

**Comment by natsuk4ze** [comment]
Hi, @danagbemava-nc  I have not tried it on Android, but it is no longer a problem in my environment, so I will close it. Thank you very much.
