### ISSUE TITLE
examples/widgets/container.dart does not display the buttons

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#1402]
If I run examples/widgets/container.dart, I get the following warning in the log and the app does not display the buttons:

```
01-27 09:32:45.874 28073 28100 I flutter : RaisedButton(disabled) needs to be placed inside a Material widget. Ownership chain:
01-27 09:32:45.875 28073 28100 I flutter : RaisedButton ← Row ← Padding ← DecoratedBox ← Container ← Column ← ContainerApp ← [root]
01-27 09:32:45.878 28073 28100 I flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
01-27 09:32:45.878 28073 28100 I flutter : Exception caught while building RaisedButton(disabled)
01-27 09:32:45.881 28073 28100 I flutter : 'packages/flutter/src/material/debug.dart': Failed assertion: line 10: '() {
01-27 09:32:45.881 28073 28100 I flutter :         if (context.widget is Material || context.ancestorWidgetOfExactType(Material) != null)
01-27 09:32:45.881 28073 28100 I flutter :         return true;
01-27 09:32:45.881 28073 28100 I flutter :         Element element = context;
01-27 09:32:45.881 28073 28100 I flutter :         debugPrint("${context.widget} needs to be placed inside a Material widget. Ownership chain:\n${element.debugGetOwnershipChain(10)}");
01-27 09:32:45.881 28073 28100 I flutter :         return false;
01-27 09:32:45.881 28073 28100 I flutter :       }' is not true.
01-27 09:32:45.881 28073 28100 I flutter : Stack trace:
01-27 09:32:45.888 28073 28100 I flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
01-27 09:32:45.888 28073 28100 I flutter : #1      debugCheckHasMaterial (packages/flutter/src/material/debug.dart:10)
01-27 09:32:45.888 28073 28100 I flutter : #2      MaterialButtonState.build (packages/flutter/src/material/material_button.dart:105)
01-27 09:32:45.888 28073 28100 I flutter : #3      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1182)
01-27 09:32:45.888 28073 28100 I flutter : #4      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1123)
01-27 09:32:45.888 28073 28100 I flutter : #5      ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1169)
01-27 09:32:45.888 28073 28100 I flutter : #6      StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1270)
01-27 09:32:45.888 28073 28100 I flutter : #7      ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1164)
01-27 09:32:45.888 28073 28100 I flutter : #8      Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
01-27 09:32:45.888 28073 28100 I flutter : #9      MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1801)
01-27 09:32:45.888 28073 28100 I flutter : #10     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
01-27 09:32:45.888 28073 28100 I flutter : #11     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
01-27 09:32:45.888 28073 28100 I flutter : #12     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1720)
01-27 09:32:45.888 28073 28100 I flutter : #13     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
01-27 09:32:45.888 28073 28100 I flutter : #14     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
01-27 09:32:45.888 28073 28100 I flutter : #15     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1720)
01-27 09:32:45.888 28073 28100 I flutter : #16     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
01-27 09:32:45.888 28073 28100 I flutter : #17     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
01-27 09:32:45.888 28073 28100 I flutter : #18     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1202)
01-27 09:32:45.888 28073 28100 I flutter : #19     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1123)
01-27 09:32:45.888 28073 28100 I flutter : #20     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1169)
01-27 09:32:45.888 28073 28100 I flutter : #21     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1164)
01-27 09:32:45.888 28073 28100 I flutter : #22     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
01-27 09:32:45.888 28073 28100 I flutter : #23     MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1801)
01-27 09:32:45.889 28073 28100 I flutter : #24     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
01-27 09:32:45.889 28073 28100 I flutter : #25     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
01-27 09:32:45.889 28073 28100 I flutter : #26     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1202)
01-27 09:32:45.889 28073 28100 I flutter : #27     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1123)
01-27 09:32:45.889 28073 28100 I flutter : #28     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1169)
01-27 09:32:45.889 28073 28100 I flutter : #29     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1270)
01-27 09:32:45.889 28073 28100 I flutter : #30     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1164)
01-27 09:32:45.889 28073 28100 I flutter : #31     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
01-27 09:32:45.889 28073 28100 I flutter : #32     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
01-27 09:32:45.889 28073 28100 I flutter : #33     RenderObjectToWidgetElement.mount (packages/flutter/src/widgets/binding.dart:236)
01-27 09:32:45.889 28073 28100 I flutter : #34     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (packages/flutter/src/widgets/binding.dart:202)
01-27 09:32:45.889 28073 28100 I flutter : #35     BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:1056)
01-27 09:32:45.889 28073 28100 I flutter : #36     RenderObjectToWidgetAdapter.attachToRenderTree (packages/flutter/src/widgets/binding.dart:199)
01-27 09:32:45.889 28073 28100 I flutter : #37     WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:156)
01-27 09:32:45.889 28073 28100 I flutter : #38     runApp (packages/flutter/src/widgets/binding.dart:163)
01-27 09:32:45.889 28073 28100 I flutter : #39     main (/media/jimbe/mojossd/flutter/examples/widgets/animate.dart:59)
```

**Comment by abarth** [comment]
Thanks for the report!

**Comment by jimbeveridge** [comment]
Adam,

Can you added a comment on why the Material object is there? Since the name of the example is "Container", the reason for the added complexity is not obvious to the novice user.

**Comment by abarth** [comment]
We should just delete the example.  It's not clear what it's purpose is anymore.
