### ISSUE TITLE
Column inside SliverGrid breaks tapping widget byKey in test

### ISSUE THREAD

**Issue by JaspervanRiet** [flutter/flutter#140379]
### Steps to reproduce

Run the test in the code sample. The steps seem to be:

1. Make a SliverGrid
2. Add a child with a Column
3. Try to tap the child in a test by using `byKey` or `byType`, they will fail. `find.text` DOES work!

### Expected results

The test in the sample is expected to succeed. Indeed, removing the column makes it succeed. Similarly, changing the sliver to a SliverList will also make it work.

### Actual results

The test fails, the child cannot be tapped.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int? valueOfIndexThatWasTapped;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: CustomScrollView(
        slivers: [
          SliverToBoxAdapter(
            child: Text('Tapped: $valueOfIndexThatWasTapped'),
          ),
          SliverGrid(
            delegate: SliverChildBuilderDelegate(
              (context, index) => GestureDetector(
                key: Key('key_$index'),
                onTap: () {
                  setState(() {
                    valueOfIndexThatWasTapped = index;
                  });
                },
                child: Column(
                  children: [
                    Text('Item $index'),
                  ],
                ),
              ),
            ),
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 2,
            ),
          ),
        ],
      ),
    );
  }
}
```
</details>

<details open><summary>Test sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:example/main.dart';

void main() {
  testWidgets('Taps item in list', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(const MyApp());

    expect(find.text('Tapped: null'), findsOneWidget);
    expect(find.text('Tapped: 1'), findsNothing);

    await tester.tap(find.byKey(const Key('key_1')));
    await tester.pumpAndSettle();

    expect(find.text('Tapped: null'), findsNothing);
    expect(find.text('Tapped: 1'), findsOneWidget);

    // If you remove the Column, this test will succeed.
    // Similarly, if you replace the `find.byKey` with `find.text`,
    // it will also succeed.
  });
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

This shows that for actual usage, the tapping does work.

https://github.com/flutter/flutter/assets/5138348/55794746-574d-499a-b02f-ac1ffd0f7b1c

</details>

### Logs

<details open><summary>Logs</summary>

```console
jasper@Jaspers-MacBook-Pro example % flutter test
00:02 +0: Taps item in list                                                                

Warning: A call to tap() with finder "exactly one widget with key [<'key_1'>] (ignoring offstage widgets): GestureDetector-[<'key_1'>](startBehavior: start, dependencies: [MediaQuery])" derived an Offset (Offset(600.0, 276.0)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
The finder corresponds to this RenderBox: RenderSemanticsGestureHandler#96f9b
The hit test result at that offset is: HitTestResult(RenderPointerListener#fc746@Offset(600.0, 220.0), RenderSemanticsGestureHandler#f7e2e@Offset(600.0, 220.0), RenderPointerListener#3a77b@Offset(600.0, 220.0), _RenderScrollSemantics#17ad2@Offset(600.0, 220.0), RenderClipRect#758e3@Offset(600.0, 220.0), RenderCustomMultiChildLayoutBox#5ad2f@Offset(600.0, 276.0), _RenderInkFeatures#52ea8@Offset(600.0, 276.0), RenderPhysicalModel#f621a@Offset(600.0, 276.0), RenderSemanticsAnnotations#95e8a@Offset(600.0, 276.0), RenderRepaintBoundary#3972e@Offset(600.0, 276.0), RenderIgnorePointer#4bd68@Offset(600.0, 276.0), _RenderSnapshotWidget#1c768@Offset(600.0, 276.0), _RenderSnapshotWidget#7d433@Offset(600.0, 276.0), _RenderSnapshotWidget#99be4@Offset(600.0, 276.0), _RenderSnapshotWidget#7e90e@Offset(600.0, 276.0), RenderRepaintBoundary#0bcab@Offset(600.0, 276.0), RenderSemanticsAnnotations#dfa9f@Offset(600.0, 276.0), RenderOffstage#8fb19@Offset(600.0, 276.0), RenderSemanticsAnnotations#f4c98@Offset(600.0, 276.0), _RenderTheater#64d01@Offset(600.0, 276.0), RenderAbsorbPointer#43eaf@Offset(600.0, 276.0), RenderPointerListener#3f924@Offset(600.0, 276.0), RenderSemanticsAnnotations#a31b7@Offset(600.0, 276.0), RenderCustomPaint#e8e41@Offset(600.0, 276.0), RenderSemanticsAnnotations#fa526@Offset(600.0, 276.0), RenderSemanticsAnnotations#40e34@Offset(600.0, 276.0), RenderTapRegionSurface#d3c22@Offset(600.0, 276.0), RenderSemanticsAnnotations#ab5b8@Offset(600.0, 276.0), RenderSemanticsAnnotations#2ab33@Offset(600.0, 276.0), RenderSemanticsAnnotations#3fc39@Offset(600.0, 276.0), HitTestEntry<HitTestTarget>#4a994(RenderView#d22f9), HitTestEntry<HitTestTarget>#c3d12(<AutomatedTestWidgetsFlutterBinding>))
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1349:25)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1233:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3      main.<anonymous closure> (file:///Users/jasper/dev/misc/example/test/widget_test.dart:14:18)
<asynchronous suspension>
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
To silence this warning, pass "warnIfMissed: false" to "tap()".
To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: no matching nodes in the widget tree
  Actual: _TextFinder:<exactly one widget with text "Tapped: null" (ignoring offstage widgets):
Text("Tapped: null", dependencies: [DefaultSelectionStyle, DefaultTextStyle, MediaQuery])>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/jasper/dev/misc/example/test/widget_test.dart:17:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/jasper/dev/misc/example/test/widget_test.dart line 17
The test description was:
  Taps item in list
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: Taps item in list [E]                                                         
  Test failed. See exception logs above.
  The test description was: Taps item in list
  

To run this test again: /opt/homebrew/Caskroom/flutter/3.7.0/flutter/bin/cache/dart-sdk/bin/dart test /Users/jasper/dev/misc/example/test/widget_test.dart -p vm --plain-name 'Taps item in list'
00:02 +0 -1: Some tests failed.                                                            
jasper@Jaspers-MacBook-Pro example % flutter test --verbose
[   +2 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +10 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.5.2
[        ] executing: sw_vers -buildVersion
[  +10 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22G91
[        ] executing: uname -m
[   +6 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: sysctl hw.optional.arm64
[   +4 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +38 ms] Found 1 files which will be executed as Widget Tests.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +16 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +25 ms] Skipping pub get: version match.
[  +97 ms] Generating
/Users/jasper/dev/misc/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginR
egistrant.java
[  +73 ms] running test package with arguments: [--chain-stack-traces, --,
file:///Users/jasper/dev/misc/example/test/widget_test.dart]
00:00 +0: loading /Users/jasper/dev/misc/example/test/widget_test.dart                     [  +83 ms] test 0: starting test /Users/jasper/dev/misc/example/test/widget_test.dart
[   +2 ms] Stopping scan for flutter_test_config.dart; found project root at
/Users/jasper/dev/misc/example
[   +1 ms] Compiler will use the following file as its incremental dill file:
/var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_compiler.
b1IP1i/output.dill
[        ] Listening to compiler controller...
[   +3 ms] Compiling
file:///var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_li
stener.DHx5GP/listener.dart
[  +10 ms] /opt/homebrew/Caskroom/flutter/3.7.0/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/opt/homebrew/Caskroom/flutter/3.7.0/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_serve
r.dart.snapshot --sdk-root
/opt/homebrew/Caskroom/flutter/3.7.0/flutter/bin/cache/artifacts/engine/common/flutter_patch
ed_sdk/ --incremental --no-print-incremental-dependencies --target=flutter
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_compiler.
b1IP1i/output.dill --packages /Users/jasper/dev/misc/example/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--initialize-from-dill
/Users/jasper/dev/misc/example/build/test_cache/build/c075001b96339384a97db4862b8ab8db.cache
.dill.track.dill --verbosity=error
[   +6 ms] <- compile
file:///var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_li
stener.DHx5GP/listener.dart
[ +629 ms] <- accept
[        ] <- reset
[        ] Compiling
file:///var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_li
stener.DHx5GP/listener.dart took 646ms
[        ] test 0: starting test device
[   +1 ms] test 0: awaiting connection to test device
[        ] test 0: VM Service uri is not available
[   +1 ms] test 0: test harness socket server is running at port:58331
[        ] Using this directory for fonts configuration:
/var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_fonts.9ut
WED
[        ] test 0: Starting flutter_tester process with
command=[/opt/homebrew/Caskroom/flutter/3.7.0/flutter/bin/cache/artifacts/engine/darwin-x64/
flutter_tester, --disable-vm-service, --enable-checked-mode, --verify-entry-points,
--enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling,
--non-interactive, --use-test-fonts, --disable-asset-fonts,
--packages=/Users/jasper/dev/misc/example/.dart_tool/package_config.json,
--flutter-assets-dir=/Users/jasper/dev/misc/example/build/unit_test_assets,
/var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_listener.
DHx5GP/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
/var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_fonts.9ut
WED/fonts.conf, SERVER_PORT: 58331, APP_NAME: example, UNIT_TEST_ASSETS:
/Users/jasper/dev/misc/example/build/unit_test_assets}
[   +4 ms] test 0: Started flutter_tester process at pid 22385
[ +280 ms] test 0: connected to test device, now awaiting test result
[        ] test 0: Waiting for test harness or tests to finish
00:01 +0: Taps item in list                                                                

Warning: A call to tap() with finder "exactly one widget with key [<'key_1'>] (ignoring offstage widgets): GestureDetector-[<'key_1'>](startBehavior: start, dependencies: [MediaQuery])" derived an Offset (Offset(600.0, 276.0)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
The finder corresponds to this RenderBox: RenderSemanticsGestureHandler#5cfd4
The hit test result at that offset is: HitTestResult(RenderPointerListener#f6e51@Offset(600.0, 220.0), RenderSemanticsGestureHandler#e8197@Offset(600.0, 220.0), RenderPointerListener#1f9d4@Offset(600.0, 220.0), _RenderScrollSemantics#72d95@Offset(600.0, 220.0), RenderClipRect#db570@Offset(600.0, 220.0), RenderCustomMultiChildLayoutBox#895e3@Offset(600.0, 276.0), _RenderInkFeatures#2f958@Offset(600.0, 276.0), RenderPhysicalModel#5f7e5@Offset(600.0, 276.0), RenderSemanticsAnnotations#9cc22@Offset(600.0, 276.0), RenderRepaintBoundary#f36ab@Offset(600.0, 276.0), RenderIgnorePointer#016d6@Offset(600.0, 276.0), _RenderSnapshotWidget#412b1@Offset(600.0, 276.0), _RenderSnapshotWidget#4dda0@Offset(600.0, 276.0), _RenderSnapshotWidget#6345c@Offset(600.0, 276.0), _RenderSnapshotWidget#8fe12@Offset(600.0, 276.0), RenderRepaintBoundary#7b2b9@Offset(600.0, 276.0), RenderSemanticsAnnotations#c26cc@Offset(600.0, 276.0), RenderOffstage#01c80@Offset(600.0, 276.0), RenderSemanticsAnnotations#bdda4@Offset(600.0, 276.0), _RenderTheater#8b838@Offset(600.0, 276.0), RenderAbsorbPointer#140c0@Offset(600.0, 276.0), RenderPointerListener#5c0b7@Offset(600.0, 276.0), RenderSemanticsAnnotations#3f936@Offset(600.0, 276.0), RenderCustomPaint#fbd43@Offset(600.0, 276.0), RenderSemanticsAnnotations#90991@Offset(600.0, 276.0), RenderSemanticsAnnotations#4f13e@Offset(600.0, 276.0), RenderTapRegionSurface#935f4@Offset(600.0, 276.0), RenderSemanticsAnnotations#00ff7@Offset(600.0, 276.0), RenderSemanticsAnnotations#092cc@Offset(600.0, 276.0), RenderSemanticsAnnotations#d49ce@Offset(600.0, 276.0), HitTestEntry<HitTestTarget>#4e456(RenderView#cf9f3), HitTestEntry<HitTestTarget>#2eec1(<AutomatedTestWidgetsFlutterBinding>))
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1349:25)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1233:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3      main.<anonymous closure> (file:///Users/jasper/dev/misc/example/test/widget_test.dart:14:18)
<asynchronous suspension>
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
To silence this warning, pass "warnIfMissed: false" to "tap()".
To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: no matching nodes in the widget tree
  Actual: _TextFinder:<exactly one widget with text "Tapped: null" (ignoring offstage widgets):
Text("Tapped: null", dependencies: [DefaultSelectionStyle, DefaultTextStyle, MediaQuery])>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/jasper/dev/misc/example/test/widget_test.dart:17:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/jasper/dev/misc/example/test/widget_test.dart line 17
The test description was:
  Taps item in list
════════════════════════════════════════════════════════════════════════════════════════════════════
00:01 +0 -1: Taps item in list [E]                                                         
  Test failed. See exception logs above.
  The test description was: Taps item in list
  

To run this test again: /opt/homebrew/Caskroom/flutter/3.7.0/flutter/bin/cache/dart-sdk/bin/dart test /Users/jasper/dev/misc/example/test/widget_test.dart -p vm --plain-name 'Taps item in list'
[ +472 ms] test 0: Test harness is no longer needed by test process
[        ] test 0: finished
[        ] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[        ] test 0: Terminating flutter_tester process
[        ] test 0: Shutting down DevTools server
[        ] test 0: Test process is no longer needed by test harness
[        ] test 0: Shutting down test harness socket server
[   +3 ms] test 0: flutter_tester process at pid 22385 exited with code=-9
[        ] test 0: deleting temporary directory
[   +1 ms] test 0: finished
00:01 +0 -1: Some tests failed.                                                            
[   +3 ms] Deleting
/var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_compiler.
b1IP1i...
[        ] killing pid 22379
[   +9 ms] Deleting
/var/folders/6z/x5x26tw94pb7f074mbwg36540000gp/T/flutter_tools.TIr74Z/flutter_test_fonts.9ut
WED...
[   +1 ms] test package returned with exit code 1
[        ] Runtime for phase TestRunner: Wall-clock: 0:00:01.526711; combined:
0:00:01.526729.
[        ] Runtime for phase Compile: Wall-clock: 0:00:00.647854; combined: 0:00:00.647873.
[        ] Runtime for phase Run: Wall-clock: 0:00:00.763139; combined: 0:00:00.763141.
[        ] Runtime for phase CoverageTotal: Wall-clock: 0:00:00.000000; combined:
0:00:00.000000.
[        ] Runtime for phase CoverageCollect: Wall-clock: 0:00:00.000000; combined:
0:00:00.000000.
[        ] Runtime for phase CoverageParseJson: Wall-clock: 0:00:00.000000; combined:
0:00:00.000000.
[        ] Runtime for phase CoverageAddHitmap: Wall-clock: 0:00:00.000000; combined:
0:00:00.000000.
[        ] Runtime for phase CoverageDataCollect: Wall-clock: 0:00:00.000000; combined:
0:00:00.000000.
[        ] Runtime for phase WatcherFinishedTest: Wall-clock: 0:00:00.000393; combined:
0:00:00.000394.
[   +6 ms] "flutter test" took 1,750ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand
(package:flutter_tools/src/commands/test.dart:506:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +85 ms] ensureAnalyticsSent: 80ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
jasper@Jaspers-MacBook-Pro example % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.5.2 22G91 darwin-arm64 (Rosetta), locale
    en-NL)
    • Flutter version 3.13.7 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.7.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (2 months ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/jasper/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/jasper/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33)
      (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.2 22G91
      darwin-arm64 (Rosetta)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome
      120.0.6099.109
    ! Error: Browsing on the local area network for Jasper’s iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample provided above. 

As reported above, with `find.text`, the test is successful but it fails with `find.byKey`
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.16.4 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (8 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.2 21C62
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
  
```
[!] Flutter (Channel master, 3.18.0-14.0.pre.31, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.18.0-14.0.pre.31 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62d699961f (3 hours ago), 2023-12-19 20:59:27 -0800
    • Engine revision c70f0a495a
    • Dart version 3.3.0 (build 3.3.0-244.0.dev)
    • DevTools version 2.31.0-dev.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.2 21C62
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by goderbauer** [comment]
You will probably have to change the HitTestBehavior of the GestureDetector to make this work, see also: https://main-api.flutter.dev/flutter/widgets/GestureDetector/behavior.html.

My guess is that the test probably tries to tap on a space in the column where there is nothing to hit. If you want the gesture detector to respond to that you'd need to set the hit test behavior to something like  opaque or translucent.
