### ISSUE TITLE
onPopInvoked in the PopScope widget throws an assertion error when a screen is popped.

### ISSUE THREAD

**Issue by Desmond235** [flutter/flutter#140447]
### Steps to reproduce

1. Use this project https://github.com/Desmond235/Meals, which is a flutter project made of meals. 
2. Clone the project using the remote directly.
3. cd into the project directory and run the project

### Expected results

please I expected the filter screen to be popped and the selected filters applied to show the meals.

### Actual results

The screen doesn't get popped, instead an error is thrown.

### Code sample

```
enum Filter {
  glutenFree,
  lactosFree,
  vegetarianFree,
  veganFree,
}

class FiltersScreen extends StatefulWidget {
  const FiltersScreen({
    super.key,
    required this.currentFilters,
  });

  final Map<Filter, bool> currentFilters;
  @override
  State<FiltersScreen> createState() => _FiltersScreenState();
}

class _FiltersScreenState extends State<FiltersScreen> {
  var _glutenFree = false;
  var _lactosFree = false;
  var _vegetarianFree = false;
  var _veganFree = false;

// Assigns and saves the filters chosen by the user
  @override
  void initState() {
    super.initState();
    _glutenFree = widget.currentFilters[Filter.glutenFree]!;
    _lactosFree = widget.currentFilters[Filter.lactosFree]!;
    _vegetarianFree = widget.currentFilters[Filter.vegetarianFree]!;
    _veganFree = widget.currentFilters[Filter.veganFree]!;
  }

  Widget switchLisTile(
      String data, String text, bool setBool, void Function(bool) onChanged) {
    return SwitchListTile(
      value: setBool,
      onChanged: onChanged,
      title: Text(
        data,
        style: Theme.of(context)
            .textTheme
            .titleLarge!
            .copyWith(color: Theme.of(context).colorScheme.onBackground),
      ),
      subtitle: Text(
        text,
        style: Theme.of(context)
            .textTheme
            .labelMedium!
            .copyWith(color: Theme.of(context).colorScheme.onBackground),
      ),
      activeColor: Theme.of(context).colorScheme.tertiary,
      contentPadding: const EdgeInsets.only(left: 34, right: 22),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Your Filters'),
      ),
      // drawer: SideBar(selectedScreen: (identifier) {
      //   Navigator.of(context).pop();
      //   if (identifier == 'meals') {
      //     Navigator.of(context).pushReplacement(
      //       MaterialPageRoute(
      //         builder: (context) => const TabsScreen(),
      //       ),
      //     );
      //   }
      // }),
      body: PopScope(
        onPopInvoked: (didPop) {
          Navigator.of(context).pop({
            Filter.glutenFree: _glutenFree,
            Filter.lactosFree: _lactosFree,
            Filter.vegetarianFree: _vegetarianFree,
            Filter.veganFree: _veganFree
          });
        },
```

### Screenshots or Video

![Screenshot (1)](https://github.com/flutter/flutter/assets/102704899/fd5ff397-1efe-499e-8bbf-935b30321ac7)

I removed the "=>" and the error still got thrown anyway.  So it is not what was causing the error.

### Logs

```
E/flutter (17891): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5238 pos 12: '!_debugLocked': is not true.
E/flutter (17891): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (17891): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (17891): #2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5238:12)
E/flutter (17891): #3      _FiltersScreenState.build.<anonymous closure> (package:meal/screens/filters.dart:81:33)
E/flutter (17891): #4      ModalRoute.onPopInvoked (package:flutter/src/widgets/routes.dart:1574:30)
E/flutter (17891): #5      _RouteEntry.pop (package:flutter/src/widgets/navigator.dart:3083:11)
E/flutter (17891): #6      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5251:13)
E/flutter (17891): #7      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5204:9)
E/flutter (17891): <asynchronous suspension>
E/flutter (17891): 
```

### Flutter Doctor output

```
PS C:\Users\Desmond\OneDrive\Desktop\Flutter projects\Meals> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.19045.3693], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.85.1)        
[√] Connected device (4 available)  
[√] Network resources

! Doctor found issues in 1 category.
PS C:\Users\Desmond\OneDrive\Desktop\Flutter projects\Meals> 
```

**Comment by Christyansoft** [comment]
Every time that user tries call pop, the method onPopInvoked is called. So you should verify if pop already was called to prevent this error. Like this:

```
  PopScope(
    canPop: false,
      onPopInvoked: (bool didPop) {
        if (didPop) {
          return;
        }
        //Navigator.of(context).pop...
      }
  )
```

**Comment by danagbemava-nc** [comment]
Hi @Desmond235, does the comment above resolve your issue?

**Comment by Desmond235** [comment]
Yes, Thank you

**Comment by Desmond235** [comment]
cccccc
