### ISSUE TITLE
Build failing for missing asset does not surface the reason

### ISSUE THREAD

**Issue by rock3r** [flutter/flutter#14045]
## Steps to Reproduce

Try to build the [dart-conf/conference_app](https://github.com/dart-lang/conference_app) for Android, without putting in the required `assets/app.token.txt` file that contains the Twitter API key.

Observe that the build will fail but no reason as for why it failed is printed:

```
Running "flutter packages get" in flutter-conf...
Launching lib/main.dart on Pixel XL in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
No file or variants found for asset: assets/app.token.txt.

Error detected in pubspec.yaml:
Error building /Users/rock3r/src/flutter-conf/build/app/intermediates/flutter/debug/app.flx: 1

FAILURE: Build failed with an exception.

* Where:
Script '/Users/rock3r/src/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 361

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command '/Users/rock3r/src/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Finished with error: Gradle build failed: 1
```

If you do `flutter run -v` then you discover that:

```
$ flutter run -v
...
[        ] :app:prepareDebugDependencies
[   +4 ms] :app:compileDebugAidl UP-TO-DATE
[   +2 ms] :app:compileDebugRenderscript UP-TO-DATE
[   +4 ms] :app:generateDebugBuildConfig UP-TO-DATE
[        ] :app:flutterDependenciesDebug UP-TO-DATE
[+1260 ms] :app:flutterBuildDebug
[        ] Error detected in pubspec.yaml:
[        ] No file or variants found for asset: assets/app.token.txt.
[  +13 ms] Error building /Users/rock3r/src/flutter-conf/build/app/intermediates/flutter/debug/app.flx: 1
[  +21 ms] :app:flutterBuildDebug FAILED
[   +1 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/rock3r/src/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 361
[        ] * What went wrong:
[        ] Execution failed for task ':app:flutterBuildDebug'.
[        ] > Process 'command '/Users/rock3r/src/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[        ] BUILD FAILED
[        ] Total time: 2.729 secs
[ +425 ms] "flutter run" took 8,612ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:314)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:238)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:36)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:365)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:267)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:215)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:335)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#25     main (file:///Users/rock3r/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[  +15 ms] ensureAnalyticsSent: 5ms
[   +1 ms] exiting with code 1
```

In which, if you're eagle-eyed enough, will notice that `No file or variants found for asset: assets/app.token.txt.` is the error (as expected).

The problem is that the crucial information on why the build failed is not surfaced if you're not using `-v` (which is the default behaviour in an IDE for example). It's in my opinion quite important that it is immediately clear to users what went wrong, regardless of verbosity.

## Logs

The `flutter run -v` log is attached in the previous section.

As for `flutter analyze`:

```
$ flutter analyze
Running "flutter packages get" in flutter-conf...     2.4s
Analyzing /Users/rock3r/src/flutter-conf...
No issues found!
Ran in 4.9s
```

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Mac OS X 10.13.2 17C205, locale en-GB, channel master)
    • Flutter at /Users/rock3r/src/flutter
    • Framework revision aad36ab7dd (4 hours ago), 2018-01-11 08:47:16 +0100
    • Engine revision 5a72197b73
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.bd6cbd1ec7e79730ea1fd8ba01139f4e18a02290

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/rock3r/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /Users/rock3r/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • Pixel XL • HT73V0201200 • android-arm • Android 8.1.0 (API 27)

Process finished with exit code 0
```

**Comment by devoncarew** [comment]
We should definitely fail better here when running. Note that the latest version of flutter does contains support for linting the assets section of the pubspec file, so you'll get some indication of an issue at edit time:

<img width="414" alt="screen shot 2018-01-11 at 8 08 05 am" src="https://user-images.githubusercontent.com/1269969/34834302-96bbd2ea-f6a6-11e7-83e3-fd1142c71382.png">

**Comment by rock3r** [comment]
Yeah I have noticed that. I suppose underlining it in the editor as an error might help too :)

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/commit/981afe39ae3de8d779466aca0d8af752b7323538
