### ISSUE TITLE
`Scrollable.ensureVisible` throws inside of `OverlayPortal` when inside an outer `ScrollView`

### ISSUE THREAD

**Issue by clragon** [flutter/flutter#140547]
### Steps to reproduce

1. Create some kind of `ScrollView`, e.g. a `PageView`
2. Create a `OverlayPortal` inside of said `ScrollView`
3. Use `focusNode.focusInDirection` inside of said `OverlayPortal`

### Expected results

`Scrollable.ensureVisible` should ignore Scrollables which it is not actually inside of,
therefore, not throw. 

### Actual results

`Scrollable.ensureVisible` throws because it looks for all parent Scrollables, including the Scrollable parent which is above the `OverlayPortal`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
      ),
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  LayerLink link = LayerLink();
  final FocusNode focusNode = FocusNode();
  bool focused = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: PageView(
        children: [
          VerySpecificChild(
            link: link,
            child: Center(
              child: CompositedTransformTarget(
                link: link,
                child: Focus(
                  onFocusChange: (value) => setState(() {
                    focused = value;
                  }),
                  focusNode: focusNode,
                  child: IconButton(
                    color: Colors.deepPurple,
                    onPressed: () {
                      if (focused) {
                        focusNode.unfocus();
                      } else {
                        focusNode.requestFocus();
                      }
                    },
                    icon: Icon(focused ? Icons.close : Icons.add),
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class VerySpecificChild extends StatefulWidget {
  const VerySpecificChild({
    super.key,
    required this.child,
    required this.link,
  });

  final Widget child;
  final LayerLink link;

  @override
  State<VerySpecificChild> createState() => _VerySpecificChildState();
}

class _VerySpecificChildState extends State<VerySpecificChild> {
  final controller = OverlayPortalController();
  final FocusNode focusNode = FocusNode();
  bool focused = false;

  @override
  void initState() {
    super.initState();
    controller.show();
  }

  @override
  Widget build(BuildContext context) {
    return OverlayPortal(
      controller: controller,
      overlayChildBuilder: (context) => Focus(
        onFocusChange: (value) => setState(() {
          focused = value;
        }),
        focusNode: focusNode,
        child: Center(
          child: Center(
            child: Padding(
              padding: const EdgeInsets.only(top: 120),
              child: IconButton(
                color: Colors.redAccent,
                onPressed: () {
                  if (focused) {
                    focusNode.unfocus();
                  } else {
                    focusNode.focusInDirection(TraversalDirection.down);
                  }
                },
                icon: Icon(focused ? Icons.close : Icons.add),
              ),
            ),
          ),
        ),
      ),
      child: widget.child,
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Restarted application in 211ms.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
RenderAbstractViewport.of() was called with a render object that was not a descendant of a RenderAbstractViewport.
No RenderAbstractViewport render object ancestor could be found starting from the object that was passed to RenderAbstractViewport.of().
The render object where the viewport search started was:
RenderSemanticsAnnotations#239f2 relayoutBoundary=up9

When the exception was thrown, this was the stack:
#0      RenderAbstractViewport.of.<anonymous closure> (package:flutter/src/rendering/viewport.dart:68:9)
#1      RenderAbstractViewport.of (package:flutter/src/rendering/viewport.dart:78:6)
#2      ScrollPosition.ensureVisible (package:flutter/src/widgets/scroll_position.dart:800:68)
#3      _PagePosition.ensureVisible (package:flutter/src/widgets/page_view.dart:337:18)
#4      ScrollableState._performEnsureVisible (package:flutter/src/widgets/scrollable.dart:1038:55)
#5      Scrollable.ensureVisible (package:flutter/src/widgets/scrollable.dart:474:45)
#6      FocusTraversalPolicy.defaultTraversalRequestFocusCallback (package:flutter/src/widgets/focus_traversal.dart:181:16)
#7      DirectionalFocusTraversalPolicyMixin.inDirection (package:flutter/src/widgets/focus_traversal.dart:994:31)
#8      FocusNode.focusInDirection (package:flutter/src/widgets/focus_manager.dart:1161:91)
#9      _VerySpecificChildState.build.<anonymous closure>.<anonymous closure> (package:e/main.dart:116:31)
#10     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#28     _invoke1 (dart:ui/hooks.dart:328:13)
#29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410:7)
#30     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)

Handler: "onTap"
Recognizer: TapGestureRecognizer#2a6ec
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(209.0, 391.0)
    finalLocalPosition: Offset(23.0, 11.0)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22631.2861], locale de-CH)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @clragon, it appears that this has been fixed on the master channel as I can reproduce this on the stable channel but not on the `master` branch. Can you check if this is the same for you as well?

**Comment by clragon** [comment]
Yes, this appears to be fixed on `master`. Thank you.
