### ISSUE TITLE
[go_router] Failed assertion: line 3817 pos 18: '!keyReservation.contains(key)': is not true.

### ISSUE THREAD

**Issue by Vedsaga** [flutter/flutter#140586]
### Steps to reproduce

1. Copy the paste the given code, & `pubspec.ymal`

2. dart run build_runner watch --delete-conflicting-outputs

3. Keep Clicking on the button 

From screen A -> Push to B -> Push to C -> Push Replacement to A -> (Push to B) cause the error.

Note, `B & C` is in shell route...

### Expected results

It should have push to the intented route, 

### Actual results

I see an error in the console (see the "Logs" section).

This only started happening since `go_router: ^13.0.0`  which was released 2 days ago.

Also, found similar reporting earlier, 
https://github.com/flutter/flutter/issues/107045

### Code sample

<details open><summary>Code sample</summary>

**Pubspec.yaml**

```yaml
name: go_router_bug
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  go_router_builder: ^2.4.0

flutter:
  uses-material-design: true
```
**main.dart**
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'main.g.dart';

void main() {
  runApp(const MyApp());
}

final parentNavigationKey = GlobalKey<NavigatorState>();
final shellRouteKey = GlobalKey<NavigatorState>();

class AScreen extends StatelessWidget {
  const AScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('A Screen')),
      body: Center(
        child: FilledButton(
          onPressed: () => const BScreenRoute().push<void>(context),
          child: const Text('Push to B'),
        ),
      ),
    );
  }
}

class BScreen extends StatelessWidget {
  const BScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('B Screen')),
      body: Center(
        child: FilledButton(
          onPressed: () => const CScreenRoute().push(context),
          child: const Text('Push to C'),
        ),
      ),
    );
  }
}

class CScreen extends StatelessWidget {
  const CScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('C Screen')),
      body: Center(
        child: FilledButton(
          onPressed: () => const AScreenRoute().pushReplacement(context),
          child: const Text('Push Replacement to A'),
        ),
      ),
    );
  }
}

@TypedGoRoute<AScreenRoute>(
  path: '/a',
  name: 'a',
)
@immutable
class AScreenRoute extends GoRouteData {
  const AScreenRoute();

  @override
  Page<void> buildPage(BuildContext context, GoRouterState state) {
    return NoTransitionPage(
      key: state.pageKey,
      child: const AScreen(),
    );
  }
}

@immutable
class BScreenRoute extends GoRouteData {
  const BScreenRoute();

  @override
  Page<void> buildPage(BuildContext context, GoRouterState state) {
    return NoTransitionPage(
      key: state.pageKey,
      child: const BScreen(),
    );
  }
}

@immutable
class CScreenRoute extends GoRouteData {
  const CScreenRoute();

  @override
  Page<void> buildPage(BuildContext context, GoRouterState state) {
    return NoTransitionPage(
      key: state.pageKey,
      child: const CScreen(),
    );
  }
}

@TypedShellRoute<BAndCScreenShellRoute>(routes: [
  TypedGoRoute<BScreenRoute>(
    path: '/b',
    name: 'b',
  ),
  TypedGoRoute<CScreenRoute>(
    path: '/c',
    name: 'c',
  ),
])
@immutable
class BAndCScreenShellRoute extends ShellRouteData {
  const BAndCScreenShellRoute();

  static final GlobalKey<NavigatorState> $navigatorKey = shellRouteKey;

  @override
  Page<void> pageBuilder(
    BuildContext context,
    GoRouterState state,
    Widget navigator,
  ) {
    return NoTransitionPage(
      key: state.pageKey,
      child: navigator,
    );
  }
}

final router = GoRouter(
  navigatorKey: parentNavigationKey,
  initialLocation: '/a',
  routes: [
    $aScreenRoute,
    $bAndCScreenShellRoute,
  ],
);

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationProvider: router.routeInformationProvider,
      routeInformationParser: router.routeInformationParser,
      routerDelegate: router.routerDelegate,
      theme: ThemeData(
        colorScheme: const ColorScheme.highContrastLight(secondary: Colors.amber),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
estarted application in 3,265ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building HeroControllerScope:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3817 pos 18: '!keyReservation.contains(key)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    MaterialApp MaterialApp:file:///C:/flutter-bug-report/go_router_bug/lib/main.dart:148:24

When the exception was thrown, this was the stack:


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    MaterialApp MaterialApp:file:///C:/flutter-bug-report/go_router_bug/lib/main.dart:148:24

When the exception was thrown, this was the stack:
#2      NavigatorState._debugCheckDuplicatedPageKeys.<anonymous closure> (package:flutter/src/widgets/navigator.dart:3817:18)
navigator.dart:3817
#3      NavigatorState._debugCheckDuplicatedPageKeys (package:flutter/src/widgets/navigator.dart:3822:6)
navigator.dart:3822
#4      NavigatorState._updatePages.<anonymous closure> (package:flutter/src/widgets/navigator.dart:3884:7)
navigator.dart:3884
#5      NavigatorState._updatePages (package:flutter/src/widgets/navigator.dart:3887:6)
navigator.dart:3887
#6      NavigatorState.didUpdateWidget (package:flutter/src/widgets/navigator.dart:3803:7)
navigator.dart:3803
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5643:55)
framework.dart:5643
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
framework.dart:5800
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#15     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
framework.dart:5800
#16     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
inherited_notifier.dart:105
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
framework.dart:5634
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#21     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
framework.dart:5657
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
framework.dart:5800
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#29     StatelessElement.update (package:flutter/src/widgets/framework.dart:5547:5)
framework.dart:5547
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#33     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
framework.dart:5800
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#37     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
framework.dart:5800
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
framework.dart:5634
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#42     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
framework.dart:2895
#43     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
binding.dart:984
#44     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
binding.dart:457
#45     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
binding.dart:1325
#46     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
binding.dart:1255
#47     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
binding.dart:1113
#48     _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#49     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
platform_dispatcher.dart:383
#50     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 2 frames from class _AssertionError)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS C:\flutter-bug-report\go_router_bug> flutter doctor -v
[!] Flutter (Channel stable, 3.16.4, on Microsoft Windows [Version 10.0.22621.2861], locale en-IN)
    • Flutter version 3.16.4 on channel stable at C:\Users\harsh\fvm\default
    ! Warning: `flutter` on your path resolves to C:\Users\harsh\fvm\versions\stable\bin\flutter, which is not inside
      your current Flutter SDK checkout at C:\Users\harsh\fvm\default. Consider adding C:\Users\harsh\fvm\default\bin to      the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\harsh\fvm\versions\stable\bin\dart, which is not inside your
      current Flutter SDK checkout at C:\Users\harsh\fvm\default. Consider adding C:\Users\harsh\fvm\default\bin to the
      front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (13 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\harsh\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\harsh\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at C:\Users\harsh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • vivo 1907 (mobile) • 8TBYBE6H7H55USFE • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.2861]
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 120.0.6099.129
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 118.0.2088.76

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Vedsaga, thanks for filing this issue. Which version of go_router were you using prior to upgrading to `13.0.0`?

**Comment by Vedsaga** [comment]
> Hi @Vedsaga, thanks for filing this issue. Which version of go_router were you using prior to upgrading to `13.0.0`?

Was on [12.1.3](https://pub.dev/packages/go_router/versions/12.1.3) which was latest version before major version update to 13.0.0

cc:
@danagbemava-nc

**Comment by danagbemava-nc** [comment]
Thanks for the update. 

I can confirm this is a regression in go_router 13.0.0 as the bug did not reproduce on 12.1.3 but it did on 13.0.0

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.16.5 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (8 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 120.0.6099.129
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.18.0-18.0.pre.39, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.18.0-18.0.pre.39 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0b0e423d6 (6 hours ago), 2023-12-28 09:38:38 +0800
    • Engine revision afd214dccc
    • Dart version 3.3.0 (build 3.3.0-264.0.dev)
    • DevTools version 2.31.0-dev.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 120.0.6099.129
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by dhikshith12** [comment]
I'm facing the same problem, the tldr; of the problem i understood is when trying to navigate between an outerroute into a shell route it's throwing this error.

**Comment by armin1440** [comment]
same for me

**Comment by jperezr21** [comment]
Same error here

**Comment by danagbemava-nc** [comment]
For anyone else encountering this issue, please do not add same here or me too comments. Please add a thumbs up to the issue instead. Kindly read https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs

Thank you

**Comment by jaumard** [comment]
Is there any workaround until we have a fix? Or the only way is to go back to v12

**Comment by dkbast** [comment]
Looks like the refactoring did not work as expected - I was wondering if we should add the above example as a test case to make future refactorings more robust? For production I rolled back to 12.1.3

**Comment by subzero911** [comment]
Same here.
In my case, it happens with the following setup:

```dart
StatefulShellBranch(
          routes: [
            GoRoute(
                path: '/rewards',
                builder: (context, state) => RewardsScreen(),
                routes: [
                  GoRoute(
                    path: 'new-reward',
                    parentNavigatorKey: rootNavigatorKey, // open it not in the inner Navigator, but in a root Navigator
                    builder: (context,state) => EditRewardScreen(),
                   ),
                   GoRoute(
                    path: 'reward-search',
                    builder: (context, state) => RewardSearchScreen(),
                   ),
                  );
```
When I tried to context.push(RouteNames.rewardSearch) above the new-reward route, then the crash will happen.
When I added `parentNavigatorKey: rootNavigatorKey` to rewardSearch route, it works well,.

**Comment by ArbazIrshad** [comment]
The above solution wasn't working for me as I was pushing a shell route on top of an outer route. So, I just pushed the route the normal way by using `Navigator.of(context).push()`. If anyone knows a better way to fix this problem. Please let me know.

**Comment by resucutie** [comment]
I am also looking for a fix.

After some debugging, at least with my app, I found the issue was with a `ShellRoute` having two instances of itself. Here's the following example:
```dart
[
  GoRoute(
    path: "/a",
    routes: [
      ShellRoute(
        routes: [
          GoRoute(path: "b")
        ]
      )
    ]
  ),
  GoRoute(path: "/c")
]
```
If I start at `/a`, then push to `/a/b`, then to `/c`, and then to `/a/b` again, the bug happens

I tried to downgrade to 12.1.3, but #125752 prevents the ShellRoute to even run build()

**Comment by bawahakim** [comment]
Is there a reason this was changed to P2? This is a pretty major regression, making it impossible for us to upgrade to 13.x and above (14.x also has this issue)

**Comment by narendh2naddy** [comment]
Instead of push use go 
context.go .. this will clear the history and navigate to screen

**Comment by dkbast** [comment]
@chunhtai could you please clarify why this was moved down in priority? This is a big problem for those who encounter it, moving it to P2 without clarification seems wrong to me.

**Comment by spydon** [comment]
> Instead of push use go context.go .. this will clear the history and navigate to screen

To wipe the whole history stack isn't really a viable workaround.

**Comment by sethladd** [comment]
IIUC the issue is triggered when you navigate between an outerroute into a shell route.

Is there a work around for folks that want to upgrade to 13+ and still want to navigate between outer route and a shell route?

**Comment by dkbast** [comment]
From my research there is currently no workaround to this bug - some fixes which might work in some situations have been suggested (like go vs push) but thats not a viable workaround in most cases. I would also assume that if somebody had found a workaround they would have shared it here, or after they got notified of your comment they would have responded with their solution. So it stands to reason that there is no workaround at the moment.

**Comment by OgnenValtech** [comment]
Yes would be great if someone can look into this issue, since it has been around for a while and no workaround is available for it.

**Comment by JacoNeto** [comment]
I have the same issue here.

**Comment by yassine-bennkhay** [comment]
I had the same issue. I am using go_router v14.1.4. What worked for me was using `context.go` and `context.goNamed `instead of `context.push` and `context.pushNamed`, respectively.

**Comment by JacoNeto** [comment]
> I had the same issue. I am using go_router v14.1.4. What worked for me was using `context.go` and `context.goNamed `instead of `context.push` and `context.pushNamed`, respectively.

I also had to use context.go for getting it to work in v14.2.7, but it is not the ideal behaviour in my case (my app needs context.go for IOS and web and context.push for android). I think this is an important bug.

**Comment by AllinProgram** [comment]
If you used `StatefulShellBranch`, try to make the routers occur problem all in the same `StatefulShellBranch`.

**Comment by Ning7013** [comment]
Any updates here?  
pushing another page in shellroute from page outside shellroute which the shellroute is already in history stack cause this exception.
using go_router v14.6.1

**Comment by yelmuratoff** [comment]
> Any updates here? pushing another page in shellroute from page outside shellroute which the shellroute is already in history stack cause this exception. using go_router v14.6.1

+

Such errors force you to switch to another package or write your own navigation solution.

**Comment by mhmzdev** [comment]
I'm literally shifting back to custom navigation service which I've been using for years. I shifted to `go_router` first time and after setting up whole app I'm stuck here. And I can that this issue is opened since last year so probably nobody is going to resolve it.

Cheers

**Comment by yelmuratoff** [comment]
> I'm literally shifting back to custom navigation service which I've been using for years. I shifted to `go_router` first time and after setting up whole app I'm stuck here. And I can that this issue is opened since last year so probably nobody is going to resolve it.
> 
> Cheers

We also migrated our navigation. I advise you to check octopus: https://pub.dev/packages/octopus

**Comment by jimpatrick** [comment]
I used shell route too and i have same problem as they said, please don't force me to remove this feature from my app.

**Comment by elmissouri16** [comment]
Is there any update on this issue fix progress @chunhtai ?

**Comment by gbaccetta** [comment]
I haven't found a workaround for this yet. The only solution that worked for me—and was acceptable for my use case (though it may not apply universally)—was to first pop all the routes before pushing B.

Since C was a small embedded flow (C → D → E) that needed to be restarted from the beginning anyway, this approach was a reasonable compromise.

**Comment by chunhtai** [comment]
I am not currently working on this due to other high priority issue

**Comment by bahadirarslan** [comment]
Downgrading back to 12.1.3 worked for me, at least.

**Comment by reduxdj** [comment]
This is pretty glaring, any chance this will be fixed...?

**Comment by andnlv** [comment]
Hello, we encountered the same issue with go router version `14.2.0`. Downgrading to `12.1.3` solved the error for us. Can this bug be prioritized, please? Thank you!

**Comment by konlanx** [comment]
This issue still exists with GoRouter 16.0.0

**Comment by phougt** [comment]
This issue still exists with GoRouter 16.1.0.

**Comment by haykgalstyan** [comment]
Not fixed for such a long time...

**Comment by Gustl22** [comment]
The problem is, when pushing a Page with the same ShellRoute on top of another Page (which uses the same ShellRoute), the key of the ShellRouteMatch is reused, which makes sense, as its the same ShellRoutePage.
See: https://github.com/flutter/packages/blob/b1db3a5b0b01c00f9f42ba4aa5890d643281c156/packages/go_router/lib/src/match.dart#L183

The idea was that one could set a custom ShellRoute::pageBuilder and use a different pageKey for the `MaterialPage`:

```
ShellRoute(
  pageBuilder: (context, state, child) {
    return MaterialPage(
      key: ValueKey(
        'some-key-${GoRouter.of(context).routerDelegate.currentConfiguration.matches.indexWhere((element) => element.matchedLocation == state.matchedLocation)}',
      ),
      child: child,
    );
  })
```

But this then raises errors using the same GlobalKey on in the widget tree (not sure, but it might is the navigatorKey of ShellRouteMatch).
The same happens, if simply ignoring the assertion in [Navigator](https://github.com/flutter/flutter/blob/8cbca238166807bf0e6ac124a04595a45de9986b/packages/flutter/lib/src/widgets/navigator.dart#L4024).

I do not have a solution yet, also struggling to find the time to debug further. Just wanted to drop some infos.

Edit: The problem seems actually be another one, as if pushing two pages with the shell route sequentially, they the last common ShellRoute is used, but if there is a page in between, the shell route page is not the last in the list anymore and a new ShellRoute page is pushed:
https://github.com/flutter/packages/blob/b1db3a5b0b01c00f9f42ba4aa5890d643281c156/packages/go_router/lib/src/match.dart#L641

Edit2: I reviewed again, and it was my fault: I did not consequently set the `parentNavigatorKey` for all sub routes. Which may or may is not a failure of the package (as it should be able to grab the parents key automatically, if set to null). In any case, the error message, has to be more descriptive. I tried this approach, but I think my fix is actually wrong, as the children need to set a key, and not the parent. But the test might is a good starting point for providing a fix:
https://github.com/flutter/packages/compare/main...Gustl22:flutter_packages:140586-shell-route-push

**Comment by manh-nguyen-dev** [comment]
Does anyone have solutions?

**Comment by Agyapaldhiman** [comment]
Is anyone currently working on this issue? It’s becoming quite frustrating and is causing ongoing problems.
