### ISSUE TITLE
[two_dimensional_scrollables] Quickly resizing a TableView throws an assertion error

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#140589]
### Steps to reproduce

1. flutter create tableview_sample
2. flutter pub add two_dimensional_scrollables (I managed to reproduce with version 0.0.5)
3. Paste the code sample into main.dart
4. Run the app
5. Drag both sliders to their maximum
6. Scroll both axes to their end, so that the tile in the bottom corner of the table view is visible on the bottom right (tile "x:63, y:63")
7. Drag the "Row" slider back to its minimum, as fast as possible. I ran the app on Windows since using a mouse makes it easy to reproduce.
8. An assert is logged, even though the table view looks fine

### Expected results

No assertions and a properly rendered table view

### Actual results

An assertion is logged when shrinking the table view

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:two_dimensional_scrollables/two_dimensional_scrollables.dart';

void main() {
  runApp(const MaterialApp(home: TableViewTest()));
}

class TableViewTest extends StatefulWidget {
  const TableViewTest({super.key});

  @override
  State<TableViewTest> createState() => _TableViewTestState();
}

class _TableViewTestState extends State<TableViewTest> {
  int rows = 1;
  int columns = 1;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('TableView example'),
      ),
      body: Row(
        children: [
          Expanded(
            child: TableView.builder(
              columnCount: columns,
              rowCount: rows,
              columnBuilder: (int index) => const TableSpan(
                extent: FixedTableSpanExtent(64),
              ),
              rowBuilder: (int index) => const TableSpan(
                extent: FixedTableSpanExtent(64),
              ),
              cellBuilder: (context, vicinity) => Container(
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.red),
                ),
                width: 64,
                height: 64,
                child: Center(
                  child: Text('x: ${vicinity.xIndex} y: ${vicinity.yIndex}'),
                ),
              ),
            ),
          ),
          SizedBox(
            width: 200,
            child: Column(
              children: [
                const Text('Rows'),
                Slider(
                  min: 1,
                  max: 64,
                  value: rows.toDouble(),
                  onChanged: (value) {
                    if (mounted) {
                      setState(() {
                        rows = value.floor();
                      });
                    }
                  },
                ),
                const Text('Columns'),
                Slider(
                  min: 1,
                  max: 64,
                  value: columns.toDouble(),
                  onChanged: (value) {
                    if (mounted) {
                      setState(() {
                        columns = value.floor();
                      });
                    }
                  },
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
PS C:\Users\Navaron\Desktop\tableview_sample> flutter run
Launching lib\main.dart on Windows in debug mode...
Building Windows application...                                    11,1s
√  Built build\windows\x64\runner\Debug\tableview_sample.exe.
Syncing files to device Windows...                                  98ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Windows is available at: http://127.0.0.1:51886/KWVYjXmcjOE=/
The Flutter DevTools debugger and profiler on Windows is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:51886/KWVYjXmcjOE=/

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12:
'_leadingXIndex != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
  TableViewport
  TableViewport:file:///C:/Users/Navaron/AppData/Local/Pub/Cache/hosted/pub.dev/two_dimensional_scrollables-0.0.5/lib/src/table_view/table.dart:191:12

When the exception was thrown, this was the stack:
#2      RenderTwoDimensionalViewport._reifyChildren (package:flutter/src/widgets/two_dimensional_viewport.dart:1289:12)
#3      RenderTwoDimensionalViewport.performLayout.<anonymous closure> (package:flutter/src/widgets/two_dimensional_viewport.dart:1268:7)
#4      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657:59)
#5      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071:15)
#6      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657:14)
#7      RenderTwoDimensionalViewport.performLayout (package:flutter/src/widgets/two_dimensional_viewport.dart:1258:5)
#8      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
#9      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
#10     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
#11     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#17     _invoke (dart:ui/hooks.dart:312:13)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#19     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)

The following RenderObject was being processed when the exception was fired: RenderTableViewport#7cad0 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: TableViewport ← IgnorePointer-[GlobalKey#ebb8b] ← Semantics ← Listener ← _GestureSemantics
    ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#eaa89] ← Listener ←
    _ScrollableScope ← _ScrollSemantics-[GlobalKey#07bcc] ←
    NotificationListener<ScrollMetricsNotification> ←
    _HorizontalInnerDimension-[LabeledGlobalKey<ScrollableState>#28b0c] ←
    IgnorePointer-[GlobalKey#1889c] ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1064.0, 0.0<=h<=625.0)
  layer: OffsetLayer#142e1
  size: Size(1064.0, 625.0)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 1289 pos 12: '_leadingXIndex != null': is not true.

Application finished.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.3803], locale nl-BE)
    • Flutter version 3.16.5 on channel stable at E:\Documenten\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (5 days ago), 2023-12-19 16:14:14 -0800        
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)   
    • Android SDK at E:\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = E:\Android\Sdk
    • Java binary at: E:\Android\AndroidStudio\jre\bin\java
    X Cannot execute E:\Android\AndroidStudio\jre\bin\java to determine the version

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe        

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    • Visual Studio at E:\Program Files\VisualStudio
    • Visual Studio Community 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3803]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by Mairramer** [comment]
https://github.com/flutter/flutter/issues/140589

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample and steps provided above. 

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.16.5, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.16.5 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (8 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
  
```
[✓] Flutter (Channel master, 3.18.0-18.0.pre.30, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.18.0-18.0.pre.30 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f15364efe4 (10 hours ago), 2023-12-26 21:57:40 -0500
    • Engine revision 2c04f3e2af
    • Dart version 3.3.0 (build 3.3.0-262.0.dev)
    • DevTools version 2.31.0-dev.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by tomasweigenast** [comment]
Any update on this?

**Comment by davoutuk** [comment]
I have experienced the same problem.  What's happening on this problem??

**Comment by wlsquid** [comment]
I took a look at this as I was having the same assertion error (among other errors lol) coming up when I was using the `TreeView` widget. I took a look at the flutter source and from my debugging what I have been able to ascertain is that this assert is being called on the private function `_reifyChildren()` which is called `performLayout()` on the `RenderTwoDimensionalViewport` class in the `flutter\packages\flutter\lib\src\widgets\two_dimensional_viewport.dart` file. 

From what I could see the only way `_leadingXIndex` to be set is for the function `buildOrObtainChildFor()` to be called. Which is called by the implementations of `layoutChildSequence()` on the `RenderTreeViewport` and `RenderTableViewport` classes. _However_ there is no guarantee that any of these classes will call `buildOrObtainChildFor()` so `_leadingXIndex` and all the other similarly named variables can end up unassigned and `null`.

I don't really know a huge amount about the flutter render object so I am not sure how to correct this or if this is intentional or not? Seems odd perhaps there should be a check before reify children is called rather than the asserts? like:
```
if (_leadingXIndex != null &&
          _trailingXIndex != null &&
          _leadingYIndex != null &&
          _trailingYIndex != null) {
      _reifyChildren();
}
```
But maybe the idea is to throw this error elsewhere? Or what I am describing is just an effect from a lower level system failing when the items are removed?

Also just thought I should mention the `buildOrObtainChildFor()` methods asserts:
```
if (_leadingXIndex == null ||
        _trailingXIndex == null ||
        _leadingXIndex == null || <--- checking twice?
        _trailingYIndex == null) {
```

**Comment by frank-weindel** [comment]
This also occurs if you do an overscroll to the point where your `layoutChildSequence()` would no longer have any reason to call `buildOrObtainChildFor()`. The TwoDimensionalViewport should really allow for that case as it is completely valid.

**Comment by Piinks** [comment]
I am going to close this as no longer reproducible. There has been significant refactoring in both the 2D foundation and the package itself, and now it no longer reproduces. If anyone is able to, please file a new issue with updated information. Thanks!
