### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.platform.PlatformPlugin$PlatformPluginDelegate.setFrameworkHandlesBack(boolean)' on a null object reference

### ISSUE THREAD

**Issue by 0xZOne** [flutter/flutter#140600]
```console
E/MethodChannel#flutter/platform(13561): Failed to handle method call
E/MethodChannel#flutter/platform(13561): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.platform.PlatformPlugin$PlatformPluginDelegate.setFrameworkHandlesBack(boolean)' on a null object reference
E/MethodChannel#flutter/platform(13561): 	at io.flutter.plugin.platform.PlatformPlugin.setFrameworkHandlesBack(PlatformPlugin.java:493)
E/MethodChannel#flutter/platform(13561): 	at io.flutter.plugin.platform.PlatformPlugin.access$800(PlatformPlugin.java:31)
E/MethodChannel#flutter/platform(13561): 	at io.flutter.plugin.platform.PlatformPlugin$1.setFrameworkHandlesBack(PlatformPlugin.java:123)
E/MethodChannel#flutter/platform(13561): 	at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:142)
E/MethodChannel#flutter/platform(13561): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform(13561): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform(13561): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter/platform(13561): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform(13561): 	at android.os.Handler.handleCallback(Handler.java:966)
E/MethodChannel#flutter/platform(13561): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/MethodChannel#flutter/platform(13561): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#flutter/platform(13561): 	at android.os.Looper.loop(Looper.java:293)
E/MethodChannel#flutter/platform(13561): 	at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
E/MethodChannel#flutter/platform(13561): 	at android.app.ActivityThread.main(ActivityThread.java:9923)
E/MethodChannel#flutter/platform(13561): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform(13561): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
E/MethodChannel#flutter/platform(13561): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

```

The code that creates `PlatformPlugin` through the following constructor will throw a NullPointerException when running on Flutter 3.16.x.

```java
  public PlatformPlugin(@NonNull Activity activity, @NonNull PlatformChannel platformChannel) {
    this(activity, platformChannel, null);
  }

```

<details><summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel main, 3.18.0-18.0.pre.26, on macOS 13.1 22C65 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.18.0-18.0.pre.26 on channel main at /Users/zero/fvm/versions/main
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a86e91f3c4 (9 小时前), 2023-12-25 21:47:35 -0500
    • Engine revision bdf261b536
    • Dart version 3.3.0 (build 3.3.0-261.0.dev)
    • DevTools version 2.31.0-dev.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /Users/zero/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc2
    • ANDROID_HOME = /Users/zero/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/zero/Dev/GitHub/Flutter_src/engine/src/third_party/android_tools/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by shougonyiren** [comment]
好使了踢我一下～

**Comment by 0xZOne** [comment]
> 好使了踢我一下～

你是用FlutterBoost遇到的问题吧，已经在5.0.0修复了~
