### ISSUE TITLE
Navigator's push or pop cause "Scaffold.geometryOf() must only be accessed during the paint phase." error when both scaffolds have a FABs and bottom navigation bars

### ISSUE THREAD

**Issue by antek-bizon** [flutter/flutter#140733]
### Steps to reproduce

1. Click "Open new" button
2. Return to previous page with back button
3. Sometimes you need to repeat this process a few times

### Expected results

When clicking "Open new" a test widget should be opened. Then when clicking back button a test widget should be closed. Everything should work without errors.

### Actual results

Clicking back button causes scheduler exception "Scaffold.geometryOf() must only be accessed during the paint phase."

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextButton(
                onPressed: () {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => const TestWidget(),
                      ));
                },
                child: const Text("Open new")),
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: BottomAppBar(
        // color: Theme.of(context).colorScheme.primary,
        shape: const CircularNotchedRectangle(),
        notchMargin: 10,
        child: Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            IconButton(
              tooltip: "Learn",
              onPressed: () {},
              icon: const Icon(
                Icons.present_to_all,
                // color: Theme.of(context).colorScheme.onPrimary,
              ),
            ),
            IconButton(
              tooltip: "Exam",
              onPressed: () {},
              icon: const Icon(
                Icons.play_arrow_rounded,
                // color: Theme.of(context).colorScheme.onPrimary,
              ),
            )
          ],
        ),
      ),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class TestWidget extends StatelessWidget {
  const TestWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text("test"),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[Text("test")],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: BottomAppBar(
        // color: Theme.of(context).colorScheme.primary,
        shape: const CircularNotchedRectangle(),
        notchMargin: 10,
        child: Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            IconButton(
              tooltip: "Learn",
              onPressed: () {},
              icon: const Icon(
                Icons.present_to_all,
                // color: Theme.of(context).colorScheme.onPrimary,
              ),
            ),
            IconButton(
              tooltip: "Exam",
              onPressed: () {},
              icon: const Icon(
                Icons.play_arrow_rounded,
                // color: Theme.of(context).colorScheme.onPrimary,
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/18379810/5d15699d-bd5e-4c87-8d03-0bee575dc72c

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY
╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Scaffold.geometryOf() must only be accessed during the paint phase.
The ScaffoldGeometry is only available during the paint phase, because its value is computed
during
the animation and layout phases prior to painting.

When the exception was thrown, this was the stack:
#0      _ScaffoldGeometryNotifier.value.<anonymous closure>
(package:flutter/src/material/scaffold.dart:837:9)
#1      _ScaffoldGeometryNotifier.value (package:flutter/src/material/scaffold.dart:844:6)
#2      _BottomAppBarClipper.getClip (package:flutter/src/material/bottom_app_bar.dart:262:35)
#3      _RenderCustomClip._updateClip (package:flutter/src/rendering/proxy_box.dart:1441:25)
#4      RenderPhysicalShape.hitTest (package:flutter/src/rendering/proxy_box.dart:2092:7)
#5      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>
(package:flutter/src/rendering/box.dart:2861:25)
#6      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#7      RenderBoxContainerDefaultsMixin.defaultHitTestChildren
(package:flutter/src/rendering/box.dart:2856:33)
#8      RenderCustomMultiChildLayoutBox.hitTestChildren
(package:flutter/src/rendering/custom_layout.dart:413:12)
#9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#10     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#12     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#14     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1984:18)
#15     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#17     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#19     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#21     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3591:31)
#22     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#23     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#24     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#26     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#28     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#30     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#32     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#33     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#34     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#35     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#36     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3720:31)
#37     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#38     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#39     _RenderTheaterMixin.hitTestChildren.childHitTest
(package:flutter/src/widgets/overlay.dart:902:81)
#40     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#41     _RenderTheaterMixin.hitTestChildren (package:flutter/src/widgets/overlay.dart:903:22)
#42     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#43     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#44     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#45     RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3843:17)
#46     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#47     RenderProxyBoxWithHitTestBehavior.hitTest
(package:flutter/src/rendering/proxy_box.dart:172:19)
#48     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#49     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#50     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#51     RenderCustomPaint.hitTestChildren
(package:flutter/src/rendering/custom_paint.dart:559:18)
#52     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#53     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#54     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#55     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#56     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#57     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#58     RenderTapRegionSurface.hitTest (package:flutter/src/widgets/tap_region.dart:213:28)
#59     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#60     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#61     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#62     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#63     RenderProxyBoxMixin.hitTestChildren
(package:flutter/src/rendering/proxy_box.dart:117:19)
#64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#65     RenderView.hitTest (package:flutter/src/rendering/view.dart:211:14)
#66     RendererBinding.hitTestInView (package:flutter/src/rendering/binding.dart:624:34)
#67     RendererBinding.initMouseTracker.<anonymous closure>
(package:flutter/src/rendering/binding.dart:425:7)
#68     MouseTracker._findAnnotations (package:flutter/src/rendering/mouse_tracker.dart:261:60)
#69     MouseTracker.updateAllDevices.<anonymous closure>
(package:flutter/src/rendering/mouse_tracker.dart:375:80)
#70     MouseTracker._deviceUpdatePhase
(package:flutter/src/rendering/mouse_tracker.dart:210:9)
#71     MouseTracker.updateAllDevices (package:flutter/src/rendering/mouse_tracker.dart:372:5)
#72     RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure>
(package:flutter/src/rendering/binding.dart:474:22)
#73     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1325:15)
#74     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264:9)
#75     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#76     _invoke (dart:ui/hooks.dart:312:13)
#77     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#78     _drawFrame (dart:ui/hooks.dart:283:31)
═══════════════════════════════════════════════════════════════════════════════════════════════
═════

Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed
assertion: line 205 pos 12: '!_debugDuringDeviceUpdate': is not true.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on Fedora Linux 37 (Xfce) 6.5.12-100.fc37.x86_64, locale
    pl_PL.utf8)
    • Flutter version 3.16.5 on channel stable at /home/pab/Szablony/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (9 dni temu), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/pab/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7 (Fedora 15.0.7-2.fc37)
    • cmake version 3.27.7
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 37 (Xfce) 6.5.12-100.fc37.x86_64

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by dam-ease** [comment]
Hi @antek-bizon.
Can you please try out to suggested solutions in this SO thread to see if they work in your case https://stackoverflow.com/questions/75310430/scaffold-geometryof-must-only-be-accessed-during-the-paint-phase?

**Comment by antek-bizon** [comment]
I've already tried them and they do not work in my case. However, I found that setting different heroTag in FloatingActionButton fixes the bug. The problem is that it also disables the transition animation of FAB. 
```dart
// MyHomePage's FAB
floatingActionButton: FloatingActionButton(
    onPressed: _incrementCounter,
     tooltip: 'Increment',
    heroTag: '1',
    child: const Icon(Icons.add),
),
// TestWidget's FAB
floatingActionButton: FloatingActionButton(
    onPressed: () {},
    tooltip: 'Increment',
    heroTag: '2',
    child: const Icon(Icons.add),
),
```

**Comment by dam-ease** [comment]
Thanks for your response. I tried reproducing this multiple times on my end but can't seem to reproduce it (see video below), how often does this reproduce on your end?

https://github.com/flutter/flutter/assets/53122008/c1a6fa08-83e1-4d4f-ab6b-613bbfaa9c03

<details><summary>flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.16.6, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.16.6 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (32 hours ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 (mobile)          • F17D2919-6D61-4295-8408-1719692FE958 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by antek-bizon** [comment]
Ok, I've done more testing. This bug happens only when I build the app using ```flutter run``` and linux-desktop as a target. When using Android Emulator or doing release build (```flutter build```) everything works fine.

https://github.com/flutter/flutter/assets/18379810/850e635f-3fdc-4316-baa5-332d2266da02

https://github.com/flutter/flutter/assets/18379810/a4abbdf6-01e8-4f0d-aca4-804bd0de40aa

**Comment by huycozy** [comment]
I can reproduce this on my Linux machine. The exception is thrown right after going back to previous page. 

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.7, on Ubuntu 22.04.3 LTS 6.2.0-39-generic, locale en_US.UTF-8)
    • Flutter version 3.16.7 on channel stable at /home/huynq/Documents/Working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (11 hours ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.80.0

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.80.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-39-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.19.0-4.0.pre.42, on Ubuntu 22.04.3 LTS 6.2.0-39-generic, locale en_US.UTF-8)
    • Flutter version 3.19.0-4.0.pre.42 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/huynq/Documents/Working/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5931b4f21d (4 hours ago), 2024-01-11 20:42:07 -0800
    • Engine revision 44a0a6ee4d
    • Dart version 3.4.0 (build 3.4.0-16.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.80.0

[✓] VS Code (version 1.85.1)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-39-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by cbracken** [comment]
Just to confirm @dam-ease, this did not repro on macOS? 

@huycozy Has a repro been attempted for windows and did this fail to reproduce?

Intuitively this feels potentially like a framework-side race condition, but could be something specific to the linux task runner? (Desktop triage)

**Comment by huycozy** [comment]
@cbracken I also checked this issue on Windows (Windows desktop app) and it also appears there in debug mode (not in release mode). And the issue doesn't appear on macOS, Android, iOS, or Web platforms.

To summarize my results, please see:

| Android | iOS | Web | MacOS | Linux | Windows |
| --------------- | --------------- | --------------- | --------------- | --------------- | --------------- |
✅ | ✅ | ✅ | ✅ | ❗ | ❗

✅: No Issue ❗: Issue reproduced

**Comment by mohsinnaqvi606** [comment]
Steps to reproduce
Create 2 screens

Create a Screen (A) with BottomNavigationBar to have a floating action button in the centerDocked.
Create another Screen(B) and add a floating action button in the end float.
Now navigate from screen A to B, and go back.
Repeat step 3 for 5,6 times and you will see this error.
Note: Screen B should not be part of the bottom navigation bar. it should be a separate screen.


Details description is [here](https://github.com/flutter/flutter/issues/145458#issue-2197206207)

**Comment by AllinProgram** [comment]
It can be reproduced on windows11.

**Comment by Sesa1988** [comment]
I frequently encounter this error while working on my app targeting Windows, and it's extremely frustrating. It occurs in about 30% of the redirects.

**Comment by Mairramer** [comment]
@tirth-patel-nc I opened this PR: https://github.com/flutter/flutter/pull/172914, which fixes https://github.com/flutter/flutter/issues/172866. I don’t have access to a Linux or Windows machine at the moment to verify if it also resolves this issue too, but I’ll try to check it later.
