### ISSUE TITLE
Memory leak / out of memory error : Barcode scanner

### ISSUE THREAD

**Issue by sidetraxaudio** [flutter/flutter#140734]
### Steps to reproduce

Context is barcode scanner
1) Create camera controller (ok)
2) Start ImageStream (ok - no leaks and memory disposal is fine)
3) Convert to inputimage and pass the images to instance of barcode scanner. 
4) Memory management will proceed fine UNTIL a barcodes start being scanned. MUST scan barcodes.
5) After scanning barcodes this available memory will continually drop until OOM error.
6) Have pointed phone to thin air with lots of movement and does not cause OOM. Only when barcodes start getting scanned, especially when multiple barcodes are visible at the same time, eg. a page of them. 
7) Barcodes in this case are GS1-128 but this seems irrelevant . There are around 6 or 7 barcodes on the screen at the same time I'm testing it with.

### Expected results

No out of memory errors when using barcode recognition of camera images stream.

### Actual results

App crashes with OOM error after approx 30 sec when actual barcodes start getting detected. 

### Code sample

<details open><summary>Code sample</summary>

```dart
//! START CAMERA
  Future<void> startCamera() async {
    if (!isCameraAllowed.value || allCameras.isEmpty) return;
    final imageFormat = (Platform.isAndroid) ? ImageFormatGroup.nv21 : ImageFormatGroup.bgra8888;
    ccam = CameraController(selectedCamera, currentResoloution, enableAudio: false, imageFormatGroup: imageFormat);
    if (ccam != null) await ccam!.initialize();
    maxZoom = await ccam!.getMaxZoomLevel();
    minZoom = await ccam!.getMinZoomLevel();
    await ccam!.setFlashMode(FlashMode.torch);
    isCameraControllerReady.value = true;
    await streamCameraImages();
  }


/! STREAM CAMERA IMAGES
  Future<void> streamCameraImages() async {
    await ccam!.startImageStream((image) async {
      var ccc = InputImageMetadata(
          size: Size(image.width.roundToDouble(), image.height.roundToDouble()),
          rotation: InputImageRotation.rotation90deg,
          format: InputImageFormat.nv21,
          bytesPerRow: 0);
      final InputImage img = InputImage.fromBytes(bytes: image.planes[0].bytes, metadata: ccc);
      BarcodeScanner bcs = BarcodeScanner();
      final barcodes = await bcs.processImage(img);

    });
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
/ample.coretekv(32471): Alloc concurrent copying GC freed 207(78KB) AllocSpace objects, 1(1352KB) LOS objects, 0% free, 382MB/384MB, paused 63us total 45.869ms
I/ample.coretekv(32471): Forcing collection of SoftReferences for 2700KB allocation
I/ample.coretekv(32471): Starting a blocking GC Alloc
I/ample.coretekv(32471): Waiting for a blocking GC Alloc
I/ample.coretekv(32471): Clamp target GC heap from 406MB to 384MB
I/ample.coretekv(32471): Alloc concurrent copying GC freed 92(19KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 382MB/384MB, paused 127us total 55.558ms
I/ample.coretekv(32471): WaitForGcToComplete blocked Background on HeapTrim for 115.080ms
I/ample.coretekv(32471): WaitForGcToComplete blocked Alloc on HeapTrim for 90.834ms
I/ample.coretekv(32471): Starting a blocking GC Alloc
W/ample.coretekv(32471): Throwing OutOfMemoryError "Failed to allocate a 2764976 byte allocation with 1694600 free bytes and 1654KB until OOM, target footprint 402653184, growth limit 402653184" (VmSize 29293476 kB)
D/AndroidRuntime(32471): Shutting down VM
E/AndroidRuntime(32471): FATAL EXCEPTION: main
E/AndroidRuntime(32471): Process: com.example.coretekv1, PID: 32471
E/AndroidRuntime(32471): java.lang.OutOfMemoryError: Failed to allocate a 2764976 byte allocation with 1694600 free bytes and 1654KB until OOM, target footprint 402653184, growth limit 402653184
E/AndroidRuntime(32471): 	at java.util.Arrays.copyOf(Arrays.java:3161)
E/AndroidRuntime(32471): 	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
E/AndroidRuntime(32471): 	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
E/AndroidRuntime(32471): 	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:135)
E/AndroidRuntime(32471): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:243)
E/AndroidRuntime(32471): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:284)
E/AndroidRuntime(32471): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
E/AndroidRuntime(32471): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime(32471): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:61)
E/AndroidRuntime(32471): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:251)
E/AndroidRuntime(32471): 	at io.flutter.plugins.camera.media.ImageStreamReader.lambda$onImageAvailable$0(ImageStreamReader.java:118)
E/AndroidRuntime(32471): 	at io.flutter.plugins.camera.media.ImageStreamReader$$ExternalSyntheticLambda1.run(Unknown Source:4)
E/AndroidRuntime(32471): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(32471): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(32471): 	at android.os.Looper.loop(Looper.java:264)
E/AndroidRuntime(32471): 	at android.app.ActivityThread.main(ActivityThread.java:8312)
E/AndroidRuntime(32471): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32471): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/AndroidRuntime(32471): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
I/Process (32471): Sending signal. PID: 32471 SIG: 9
Lost connection to device.

Exited.

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel beta, 3.18.0-0.2.pre, on Microsoft Windows [Version 10.0.22631.2861], locale en-AU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.1)
[√] Connected device (5 available)
[√] Network resources

• No issues found!

C:\Users\mark\OneDrive\~DEVELOPMENT\coretekv1>flutter doctor -v
[√] Flutter (Channel beta, 3.18.0-0.2.pre, on Microsoft Windows [Version 10.0.22631.2861], locale en-AU)
    • Flutter version 3.18.0-0.2.pre on channel beta at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fed06b31d9 (2 weeks ago), 2023-12-13 14:53:33 -0800
    • Engine revision 39c6dc9bdd
    • Dart version 3.3.0 (build 3.3.0-174.3.beta)
    • DevTools version 2.30.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\mark\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\mark\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.81.20231227

[√] Connected device (5 available)
    • CPH1979 (mobile)             • IZRKS4HM5TY9L7VK • android-arm64  • Android 11 (API 30)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.2861]
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 120.0.6099.130
    • Edge (web)                   • edge             • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

**Comment by sidetraxaudio** [comment]
FYI 2 Resolution presets tested - medium and high. Same results

**Comment by huycozy** [comment]
Hi @sidetraxaudio 
To address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thank you!
