### ISSUE TITLE
Flutter can't decode this image:

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#14074]
http://www.greatbarrierreefs.com.au/wp-content/uploads/YEAH-EAT-IT.jpg

I put the above image in a new Image.network() and flutter says:

01-12 12:19:08.628 10568 10585 E flutter : [ERROR:flutter/lib/ui/painting/codec.cc(82)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.

**Comment by apwilson** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
The image decodes as expected if you download it to a file and render it with an Image.asset()

Something is going wrong when the HTTP client downloads the image from this server.  The response is an error message:
```<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 1327680365516166696</body></html>```

**Comment by apwilson** [comment]
So what does flutter do differently in those two situations?  This is still a flutter bug, right?

**Comment by jason-simmons** [comment]
This is an incompatibility between the Dart HTTP client package and the firewall/web server used to host that image.

**Comment by maryx** [comment]
I'm also getting this with a URL like this:
```
new Image.network(
'https://lh3.googleusercontent.com/G6z4dyg20zs-dEnV5mMhhzvVkicp3B2v3l_DOrqojOhKJD7snLIKeTV_Ubo1yyNRm-qoazQepU4=s220'
)
```

This is the full error:
```
[72758.981] 297909.298713> [ERROR:third_party/flutter/lib/ui/painting/codec.cc(82)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
[72759.005] 297909.297930>  EXCEPTION CAUGHT BY SERVICES 
[72759.008] 297909.297930> The following _Exception was thrown resolving an image codec:
[72759.008] 297909.297930> Exception: operation failed
[72759.013] 297909.297930> 
[72759.013] 297909.297930> When the exception was thrown, this was the stack:
[72759.018] 297909.297930> #0      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:447)
[72759.018] 297909.297930> <asynchronous suspension>
[72759.018] 297909.297930> #1      NetworkImage.load (package:flutter/src/painting/image_provider.dart:424)
[72759.018] 297909.297930> #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:264)
[72759.018] 297909.297930> #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82)
[72759.018] 297909.297930> #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:264)
[72759.018] 297909.297930> #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
[72759.018] 297909.297930> #6      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:262)
[72759.018] 297909.297930> #7      _ImageState._resolveImage (package:flutter/src/widgets/image.dart:524)
[72759.018] 297909.297930> #8      _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:499)
[72759.018] 297909.297930> #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3716)
[72759.018] 297909.297930> #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3577)
[72759.018] 297909.297930> #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875)
[72759.018] 297909.297930> #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2678)
[72759.018] 297909.297930> #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4588)
[72759.018] 297909.297930> #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875)
[72759.018] 297909.297930> #15     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4693)
[72759.018] 297909.297930> #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875)
[72759.018] 297909.297930> #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2678)
[72759.018] 297909.297930> #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613)
[72759.018] 297909.297930> #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
[72759.018] 297909.297930> #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3582)
[72759.018] 297909.297930> #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3577)
[72759.018] 297909.297930> #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875)
[72759.018] 297909.297930> #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2678)
[72759.018] 297909.297930> #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4588)
[72759.018] 297909.297930> #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875)
[72759.018] 297909.297930> #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2678)
[72759.018] 297909.297930> #27     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4375)
[72759.019] 297909.297930> #28     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703)
[72759.019] 297909.297930> #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2667)
[72759.019] 297909.297930> #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613)
[72759.019] 297909.297930> #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
[72759.019] 297909.297930> #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847)
[72759.019] 297909.297930> #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2667)
[72759.019] 297909.297930> #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613)
[72759.019] 297909.297930> #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
[72759.019] 297909.297930> #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737)
[72759.019] 297909.297930> #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2667)
[72759.019] 297909.297930> #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595)
[72759.019] 297909.297930> #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2667)
[72759.019] 297909.297930> #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613)
[72759.019] 297909.297930> #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
[72759.019] 297909.297930> #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662)
[72759.019] 297909.297930> #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2667)
[72759.019] 297909.297930> #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595)
[72759.019] 297909.297930> #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2667)
[72759.019] 297909.297930> #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613)
[72759.019] 297909.297930> #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
[72759.019] 297909.297930> #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737)
[72759.019] 297909.297930> #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2667)
[72759.019] 297909.297930> #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613)
[72759.019] 297909.297930> #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
[72759.019] 297909.297930> #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737)
[72759.019] 297909.297930> #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2667)
[72759.019] 297909.297930> #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613)
[72759.019] 297909.297930> #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
[72759.019] 297909.297930> #56     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2210)
[72759.019] 297909.297930> #57     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:612)
[72759.019] 297909.297930> #58     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
[72759.019] 297909.297930> #59     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:931)
[72759.019] 297909.297930> #60     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:871)
[72759.019] 297909.297930> #61     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:783)
[72759.019] 297909.297930> #62     _invoke (file:///usr/local/google/home/maryxia/fuchsia/third_party/flutter/lib/ui/hooks.dart:120)
[72759.019] 297909.297930> #63     _drawFrame (file:///usr/local/google/home/maryxia/fuchsia/third_party/flutter/lib/ui/hooks.dart:109)
[72759.022] 297909.297930> 
[72759.022] 297909.297930> Image provider:
[72759.022] 297909.297930> NetworkImage("https://drive.google.com/a/fuchsia.com/uc?id=1cZAvs-Lze1EnTLDKrCPGiCUcU6zl5HU8&export=download",
[72759.022] 297909.297930> scale: 1.0)
[72759.022] 297909.297930> Image key:
[72759.022] 297909.297930> NetworkImage("https://drive.google.com/a/fuchsia.com/uc?id=1cZAvs-Lze1EnTLDKrCPGiCUcU6zl5HU8&export=download",
[72759.022] 297909.297930> scale: 1.0)
[72759.022] 297909.297930> 
```

**Comment by jason-simmons** [comment]
I'm getting a 403 error response from the googleusercontent URL now

**Comment by maryx** [comment]
Ah I think it's because the thumbnail (or the file itself) is restricted to my Google Drive account. Any google drive thumbnail link should work. 

Here's one that should be public: https://lh3.googleusercontent.com/VOkSCYpShB-Mx8L2qgY1OwBYGdyRTBmw41KVe5qJK1yR0M0qM4iaSwsp-9OwiEbWiIpmPaH8sM0=s220

**Comment by maryx** [comment]
The thumbnail image was not the culprit! Turns out it was an entirely different Image.network() causing the error. In my case, it was trying to load in a link, but didn't verify whether it was an image link before creating the Image.network(). Hence the error.

**Comment by ericwindmill** [comment]
@maryx What did you have to change to get this to work -- if you got it to work at all? I'm trying to load in images using Firebase auth and getting this same error

**Comment by maryx** [comment]
My issue was poor programming on my part, where I forgot to check whether the link I was passing into Image.network() was actually an _image_ URL.
This is what I had: 

```
String fileLocation = getFileFromAPI(fileId);
return new Image.network(
  fileLocation,
);
```
I didn't check that `fileLocation` actually pointed to an image - it sometimes pointed to a video. Adding a check for the mimeType resolved this for me.

Maybe you can try loading the hardcoded image URL from Firebase in your `Image.network()` widget, or see if that image loads in an incognito browser window, to ensure it's not an auth issue?

**Comment by Hixie** [comment]
We don't think there's really anything actionable for us here, so I'm going to close this bug. If you run into problems, please don't hesitate to file a new bug.

**Comment by xinwen-mao** [comment]
Using 'Image.network', I also encountered the same problem, occasionally going wrong in the LAN, not seen in the mobile network.

`I/flutter (23759): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (23759): The following SocketException was thrown resolving an image codec:
I/flutter (23759): OS Error: Connection timed out, errno = 110, address = in.kuaiqudi.com, port = 44741
I/flutter (23759): 
I/flutter (23759): When the exception was thrown, this was the stack:
I/flutter (23759): #0      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:490:39)
I/flutter (23759): <asynchronous suspension>
I/flutter (23759): #1      NetworkImage.load (package:flutter/src/painting/image_provider.dart:475:14)
I/flutter (23759): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:285:105)`

**Comment by omidh28** [comment]
Changing 127.0.0.1 to 192.168.1.2 solved my problem.

@svenmao

**Comment by softmarshmallow** [comment]
in case you are running the code on target macOS

you have to allow in entitlements for network access.



DebugProfile.entitlements
```xml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
</dict>
</plist>


```



Release.entitlements
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
</dict>
</plist>


```
