### ISSUE TITLE
Descriptive log on Flutter build when `FLUTTER_BUILD_DIR` environment variable isn't configured.

### ISSUE THREAD

**Issue by felipebonezi** [flutter/flutter#140845]
### Steps to reproduce

1. Install `flutter` using `git`.
2. Use the `3.16` stable version.
3. Go to your Flutter project.
4. Run `flutter build`.

### Expected results

Inform to us using `flutter doctor` or a simple log that we haven't configured the `FLUTTER_BUILD_DIR` environment variable.

### Actual results

An error is throw because we don't have an environment variabl called `FLUTTER_BUILD_DIR` defined.

```console
Null check operator used on a null value
    #0      Context.embedFlutterFrameworks (file:///Users/felipebonezi/flutter/packages/flutter_tools/bin/xcode_backend.dart:235:68)
    #1      Context.run (file:///Users/felipebonezi/flutter/packages/flutter_tools/bin/xcode_backend.dart:59:9)
    #2      main (file:///Users/felipebonezi/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
    #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

### Code sample

<details open><summary>Code sample</summary>

Any flutter project.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="742" alt="Screenshot 2024-01-02 at 23 44 44" src="https://github.com/flutter/flutter/assets/1410319/f9f44c2e-f03f-4d15-a94d-80aac50163b8">

<img width="971" alt="Screenshot 2024-01-02 at 23 53 08" src="https://github.com/flutter/flutter/assets/1410319/e889b322-3602-424a-8f21-7dfaad9afe8c">

</details>

### Logs

<details open><summary>Logs</summary>

```console
Unhandled exception:
    Null check operator used on a null value
    #0      Context.embedFlutterFrameworks (file:///Users/felipebonezi/flutter/packages/flutter_tools/bin/xcode_backend.dart:235:68)
    #1      Context.run (file:///Users/felipebonezi/flutter/packages/flutter_tools/bin/xcode_backend.dart:59:9)
    #2      main (file:///Users/felipebonezi/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
    #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
    Command PhaseScriptExecution failed with a nonzero exit code
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.2 23B92 darwin-arm64, locale en-BR)
    • Flutter version 3.16.5 on channel stable at /Users/felipebonezi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (2 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/felipebonezi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/felipebonezi/Library/Android/sdk
    • Java binary at: /Users/felipebonezi/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/felipebonezi/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.1)
    • IntelliJ at /Users/felipebonezi/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • iPhone de FB (mobile)      • XXXXX-XXXXXX            • ios            • iOS 17.2.1 21C66
    • iPhone 15 Pro Max (mobile) • XXXXX-XXXXXX.           • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @felipebonezi.
This is similar to https://github.com/flutter/flutter/issues/138795. Can you check out the suggested solutions if they help in your case?
Or is this a proposal to 

> Inform to us using flutter doctor or a simple log that we haven't configured the FLUTTER_BUILD_DIR environment variable.

instead of the error message being displayed?

**Comment by felipebonezi** [comment]
> Thanks for filing this @felipebonezi.
> 
> This is similar to https://github.com/flutter/flutter/issues/138795. Can you check out the suggested solutions if they help in your case?
> 
> Or is this a proposal to 
> 
> 
> 
> > Inform to us using flutter doctor or a simple log that we haven't configured the FLUTTER_BUILD_DIR environment variable.
> 
> 
> 
> instead of the error message being displayed?
> 
> 

Yes, it's similar but I would propose to inform how to fix the problem when we use the flutter doctor command. 

What do you think about it?

**Comment by dam-ease** [comment]
Thanks for your response @felipebonezi.
Please can you file a separate issue with details proposing this instead, so it's easier to track?

**Comment by felipebonezi** [comment]
Sure, do I need to report as a new feature request or a bug?

**Comment by dam-ease** [comment]
Hi @felipebonezi. Thanks for your response. 
Looking through again, there might be no need to file a new issue for this as this quite describes the issue, would be labelling this instead.
Thank you!

**Comment by christopherfujino** [comment]
> Inform to us using flutter doctor or a simple log that we haven't configured the FLUTTER_BUILD_DIR environment variable.

@felipebonezi we do not expect the user to set this environment build, but we depend on it being from Xcode. In addition, `flutter doctor` runs in the context of your entire system, not a specific flutter app, so even if we could parse all a project's Xcode configurations and detect this bad state, we could not do it from `fluter doctor`.

It sounds like in https://github.com/flutter/flutter/issues/138795#issuecomment-1821481564 the issue was that the user had an Xcode scheme that did not have a `baseConfigurationReference` set...is this the same case for you? And if so, do you know how you got into this state?

**Comment by dimman7** [comment]
i have the same problem. what fixed the problem for me was that i selected release instead of pods-runner.release in the base configuration section in xcode

**Comment by hellohuanlin** [comment]
@vashworth can you take a look at this?

**Comment by ssenchenko** [comment]
This is pretty sad. The first issue https://github.com/flutter/flutter/issues/138795 was open in Nov 2023, *3 months ago*. It's already Flutter 3.16.9 and nothing has been done better than repeating a customers work-around to copy manually iOS files from a fresh project to an existing one? What about all changes done in Xcode project file?

A non-working product has 0 value for its user regardless of the reason it's not working.
You cannot simply clame 
>we do not expect the user to set this environment build, but we depend on it being provided by Xcode
Since Flutter team cannot guarantee what next change Apple will introduce in Xcode and environmental, be at least open about the risk. Tell us not to upgrade Xcode above a version XX till you are sure you support that version. And obviously don't release your own version which breaks compatibility. And yes, teach your customers to set the enviroment, to make the build work.

**Comment by xjchen2008** [comment]
Hi all, I fixed the exception by putting "FLUTTER_BUILD_DIR=build" in the Run/Debug Configurations->environmental variables. I hope this helps.

**Comment by vashworth** [comment]
As @christopherfujino mentioned, `FLUTTER_BUILD_DIR` gets set automatically.

In the code below, `updateGeneratedXcodeProperties` is where `FLUTTER_BUILD_DIR` gets set, which always happens before the `xcodebuild` command.
https://github.com/flutter/flutter/blob/78666c8dc57e9f7548ca9f8dd0740fbf0c658dc9/packages/flutter_tools/lib/src/ios/mac.dart#L240-L255

My suspicion if that your build configuration file is not importing the `Generated.xcconfig`.

If you open the ios/Runner.xcworkspace in Xcode, and view the Configurations for the project (see screenshot below). 

![Screenshot 2024-01-30 at 1 08 00 PM](https://github.com/flutter/flutter/assets/15619084/50bbd5f2-34a5-404c-8f41-182e877f4df4)

Each configuration file should include the following:
```
#include "Generated.xcconfig"
```

Here's an example: https://github.com/flutter/packages/blob/95f2e500cd6cd3cdf01355bf64faf697a6f5bd5b/packages/animations/example/ios/Flutter/Debug.xcconfig

**Comment by AhmedHdeawy** [comment]
I resolved this issue by update values for each environment like this image

![image](https://github.com/flutter/flutter/assets/15928500/f5bdc082-8eb5-40e8-b4cb-072368b40755)

**Comment by christopherfujino** [comment]
I think the action item here is to catch this state in xcode_backend and provide a more user-friendly error message.

**Comment by darshankawar** [comment]
Reopening this issue based on https://github.com/flutter/flutter/issues/140845#issuecomment-1930815401 comment and it seems it was closed by bot based on `waiting` label.

**Comment by asimolmez** [comment]
same issue

**Comment by stam0912** [comment]
> i have the same problem. what fixed the problem for me was that i selected release instead of pods-runner.release in the base configuration section in xcode

This works for me, thanks. I don't know why it works though, would be nice if someone can explain a little bit more.

**Comment by lukehutch** [comment]
> i have the same problem. what fixed the problem for me was that i selected release instead of pods-runner.release in the base configuration section in xcode

Worked for me too. There are many things that seem to change these settings the broken `Pods-Runner` settings (e.g. I think `pod install` changes it back). This has broken for me many times, and I have to keep changing it back.

**Comment by GraficoWalab** [comment]
> I resolved this issue by update values for each environment like this image
> 
> ![image](https://private-user-images.githubusercontent.com/15928500/302134292-f5bdc082-8eb5-40e8-b4cb-072368b40755.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDAyNDYsIm5iZiI6MTcyMTEzOTk0NiwicGF0aCI6Ii8xNTkyODUwMC8zMDIxMzQyOTItZjViZGMwODItOGViNS00MGU4LWI0Y2ItMDcyMzY4YjQwNzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYTdmYzI2M2ZjNDIyOTVlYjM3NjQyMjAwN2M2OWE5MDJhMmUwNjg2YTAxMzk4MDM1YjVjOTliNWVjODg5MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHvwhMnVsLU0X3BJ7DUM5X5EijKRzb-C5LbssS_f7p0)

Hi, I have the same issue and this is the only way to make the build succeed. Why? I don't want to run it manually every time. Also, it only works with Xcode; when I try in VScode the 'Run without debugging' option, it fails.

**Comment by AliKarimiENT** [comment]
Thanks to @GraficoWalab I solved this issue after 8hrs wasting time and checking lots of solutions.

**Comment by GreenAsJade** [comment]
Could someone clarify what is involved here:

 "After that, from the source control (VSCode with GitHub), I discarded the changes for the customized files"
 
 What is the "right" version of these files?

**Comment by bszyman** [comment]
> This is pretty sad. The first issue #138795 was open in Nov 2023, **3 months ago**. It's already Flutter 3.16.9 and nothing has been done better than repeating a customers work-around to copy manually iOS files from a fresh project to an existing one? What about all changes done in Xcode project file?

Wow, will copying over a new Xcode project actually fix this issue?

The config settings always get wiped out any time I run `flutter build iOS` from the cli in the project folder. Setting the Debug/Release/Release again seems to fix it for me, but it wasn't always like this. I have just kind of been suffering though it for a while.

**Comment by ibrahimdevs** [comment]
@AhmedHdeawy thanks, I fixed my error with settings like yours. But firstly, spent many hours to figure out what was is going on. It would be much better to put some meaningful logs there please.

> I resolved this issue by update values for each environment like this image
> 
> ![image](https://github.com/flutter/flutter/assets/15928500/f5bdc082-8eb5-40e8-b4cb-072368b40755)
