### ISSUE TITLE
On test failure with flutter test integration_test/main.dart does not automatically stop/cleanup/delete app

### ISSUE THREAD

**Issue by ckxddd0324** [flutter/flutter#140900]
### Steps to reproduce

1. Create integration_test folder
2. add integration test
3. add the integration to `integration_tests/main.dart`
4. update a test to have a failure
5. run the integration test

### Expected results

When the tests encounter a failure, I would expect the test should continue to the next test or report a test failure and exit. If I run when vscode built in runner, it would allow me to interact with the element and show selector.

### Actual results

The test processor get stuck on the failed view and it did not automatically close/cleanup the test and remove the app

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
    • Flutter version 3.10.6 on channel stable at /Users/a820757/DevTools/flutter_2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (6 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/a820757/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/a820757/library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 093BEC44-149E-49E3-A4A4-CD63E8666C82 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @ckxddd0324 
Can you provide what command are you running to run integration tests ? Is it `flutter test integration_test` or are you using `flutter drive` ?
Also, is the behavior observed on ios or android ?

**Comment by ckxddd0324** [comment]
@darshankawar I am using `flutter test --machine integration_test -d $deviceID | tojunit` . And I was testing it on iOS 14 Pro. I dont think it is related to #129338 since I dont have `flavors` in my app.

**Comment by darshankawar** [comment]
> flutter test --machine integration_test -d $deviceID | tojunit

If you just run `flutter test integration_test`, do you see same behavior ?

**Comment by ckxddd0324** [comment]
@darshankawar yes, once the assertion failed or unable to find the locator/widget, it gets stuck with current frame and unable to continue or exit processor.

**Comment by darshankawar** [comment]
Thanks for the update @ckxddd0324 
I tried sample integration_test and ran on android emulator which gave expected result, ie, one test failed and exited the run, as shown below:

```
This was caught by the test expectation on the following line:
  file:///Users/dhs/Documents/NCFlutter/integration_test_app/integration_test/app_test.dart line 56
The test description was:
  tap on the floating action button, verify counter
════════════════════════════════════════════════════════════════════════════════════════════════════
01:46 +1 -2: end-to-end test tap on the floating action button, verify counter [E]                                                                                         
  Test failed. See exception logs above.
  The test description was: tap on the floating action button, verify counter
  

To run this test again: /Users/dhs/documents/fluttersdk/flutter/bin/cache/dart-sdk/bin/dart test /Users/dhs/Documents/NCFlutter/integration_test_app/integration_test/app_test.dart -p vm --plain-name 'end-to-end test tap on the floating action button, verify counter'
01:47 +1 -2: Some tests failed.                                                                                                                                            
dhs@Dhss-MacBook-Pro integration_test_app % 
```

**Comment by ckxddd0324** [comment]
So I was running with iOS/iphone and on my failed step, this is the logs
```
{"testID":6,"error":"'package:flutter_test/src/binding.dart': Failed assertion: line 954 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.","stackTrace":"dart:core                                                                                                              _AssertionError._throwNew\npackage:flutter_test/src/binding.dart 954:14                                                                           TestWidgetsFlutterBinding._runTest.handleUncaughtError\npackage:flutter_test/src/binding.dart 959:9                                                                            TestWidgetsFlutterBinding._runTest.<fn>\n===== asynchronous gap ===========================\npackage:flutter_test/src/binding.dart 975:5                                                                            TestWidgetsFlutterBinding._runTestBody\ndart:async                                                                                                             _CustomZone.runBinary\npackage:flutter_test/src/binding.dart 964:14                                                                           TestWidgetsFlutterBinding._runTest\npackage:flutter_test/src/binding.dart 1935:12                                                                          LiveTestWidgetsFlutterBinding.runTest\npackage:integration_test/integration_test.dart 245:17                                                                  IntegrationTestWidgetsFlutterBinding.runTest\npackage:flutter_test/src/widget_tester.dart 163:24                                                                     testWidgets.<fn>\n===== asynchronous gap ===========================\npackage:stream_channel                                                                                                 _GuaranteeSink.add\nvar/folders/lk/vmg1hzf54cq7d3t6s53tfqpr0000gq/T/flutter_tools.1F4qXf/flutter_test_listener.VB4cGO/listener.dart 53:22  main.<fn>\n","isFailure":false,"type":"error","time":156074}
```

**Comment by darshankawar** [comment]
Thanks for the logs

> ```shell
> Failed assertion: line 954 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.
>   dart:core                                                                                                              _AssertionError._throwNew
>   package:flutter_test/src/binding.dart 954:14                                                                           TestWidgetsFlutterBinding._runTest.handleUncaughtError
>   package:flutter_test/src/binding.dart 959:9                                                                            TestWidgetsFlutterBinding._runTest.<fn>
>   ===== asynchronous gap ===========================
>   package:flutter_test/src/binding.dart 975:5                                                                            TestWidgetsFlutterBinding._runTestBody
>   dart:async                                                                                                             _CustomZone.runBinary
>   package:flutter_test/src/binding.dart 964:14                                                                           TestWidgetsFlutterBinding._runTest
> ```

This seems to be pointing to `flutter_test` package instead of `integration_test`.  For it, check https://github.com/flutter/flutter/issues/34499 and underlying comments, specially https://github.com/flutter/flutter/issues/34499#issuecomment-1412878975 and see if it helps in your case or not.

**Comment by ckxddd0324** [comment]
@darshankawar So I added the code from the comments but still getting similar issue 

```bash
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with key [<'clsebutton'>] (ignoring offstage widgets)" (used in a call to
"tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1293:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1232:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3      LandingPage.enableTouchId ()
#4      main.<anonymous closure>.<anonymous closure> ()
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Login without interact with login screen
════════════════════════════════════════════════════════════════════════════════════════════════════
01:35 +0 -1: e2e testing Login without interact with login screen [E]                                                                                                                        
  'package:flutter_test/src/binding.dart': Failed assertion: line 954 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.
  dart:core                                                                                                              _AssertionError._throwNew
  package:flutter_test/src/binding.dart 954:14                                                                           TestWidgetsFlutterBinding._runTest.handleUncaughtError
  package:flutter_test/src/binding.dart 959:9                                                                            TestWidgetsFlutterBinding._runTest.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                                                             _CustomZone.registerBinaryCallback
  package:flutter_test/src/binding.dart 975:5                                                                            TestWidgetsFlutterBinding._runTestBody
  dart:async                                                                                                             _CustomZone.runBinary
  package:flutter_test/src/binding.dart 964:14                                                                           TestWidgetsFlutterBinding._runTest
  package:flutter_test/src/binding.dart 1935:12                                                                          LiveTestWidgetsFlutterBinding.runTest
  package:integration_test/integration_test.dart 245:17                                                                  IntegrationTestWidgetsFlutterBinding.runTest
  package:flutter_test/src/widget_tester.dart 163:24                                                                     testWidgets.<fn>
  ===== asynchronous gap ===========================
  package:stream_channel                                                                                                 _GuaranteeSink.add
  var/folders/lk/vmg1hzf54cq7d3t6s53tfqpr0000gq/T/flutter_tools.zttW1v/flutter_test_listener.z4JjTx/listener.dart 53:22  main.<fn>

```

**Comment by darshankawar** [comment]
See if [this](https://github.com/flutter/flutter/issues/120865#issuecomment-1432750123) helps.

**Comment by ckxddd0324** [comment]
So I tried to wrap it like the comment you shared-
now I am getting error
```bash
caught an execption: The finder "zero widgets with key [<'United Staes'>] that has ancestor(s) with key [<'countryListViewOptions'>] (ignoring offstage widgets)" (used in a call to "tap()") could not find any matching widgets.
```
Then it still not exit the processor on it own.

Is there config that would affect the run?

**Comment by ckxddd0324** [comment]
not sure if it is something with setup but I found some solution online that doing something like this
```dart
void main() {
  // ignore: omit_local_variable_types
  final IntegrationTestWidgetsFlutterBinding binding =
      IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;

  group('e2e testing', () {
    setUp(() async {
      app.main();
    });

    testWidgets('Test descirption', (widgetTester) async {
      var loginPage = LoginPage(widgetTester);
      // wrap originalOnError and FlutterError.onError between pumpAndSettle
      final originalOnError = FlutterError.onError;
      await widgetTester.pumpAndSettle(const Duration(seconds: 15));
      FlutterError.onError = originalOnError
```

this seems to fix the issue when the test failed with unable to find widget.

**Comment by darshankawar** [comment]
> ```dart
> final IntegrationTestWidgetsFlutterBinding binding =
>       IntegrationTestWidgetsFlutterBinding.ensureInitialized();
>   binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;
> ```

I guess you are pointing to this solution. If so, it seems to be mentioned in the [codelabs](https://codelabs.developers.google.com/codelabs/flutter-app-testing#7) as well, so it seems to be a working solution. 
If you are satisfied with it, we can close this issue as resolved.

**Comment by ckxddd0324** [comment]
OK, thanks

**Comment by darshankawar** [comment]
Closing as resolved based on https://github.com/flutter/flutter/issues/140900#issuecomment-1886252267 and https://github.com/flutter/flutter/issues/140900#issuecomment-1886166012
