### ISSUE TITLE
Flutter web 'Error from backend:  Error: Bad state: Not connected to an application.'

### ISSUE THREAD

**Issue by dumabg** [flutter/flutter#140904]
### Steps to reproduce

Flutter web gives the error "Error from backend: Error: Bad state: Not connected to an application".

Firefox shows the error when the app starts and every time navigates to another screen with the navigator. Chrome doesn't show anything. 

When do a navigation pop, the pop is done, returns to the caller, but puts the screen in blank.

On previous releases of Flutter works well.

Steps to reproduce:
1) flutter create . --platforms=web
2) flutter run -d chrome
3) Copy the url to Firefox
4) See the Firefox console

### Expected results

Doesn't appear the error and navigate correctly

### Actual results

```
Error from backend:

Error: Bad state: Not connected to an application.

Stack Trace:
#0      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:271:13)
#1      _rootRunUnary (dart:async/zone.dart:1407:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#9      _rootRunUnary (dart:async/zone.dart:1415:13)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#15     _StreamController._add (dart:async/stream_controller.dart:658:7)
#16     _StreamController.add (dart:async/stream_controller.dart:606:5)
#17     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:730:21)
#18     _rootRunUnary (dart:async/zone.dart:1407:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#25     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:319:23)
#26     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:218:46)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#28     _rootRunUnary (dart:async/zone.dart:1407:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#34     _StreamController._add (dart:async/stream_controller.dart:658:7)
#35     _StreamController.add (dart:async/stream_controller.dart:606:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
#37     _rootRunUnary (dart:async/zone.dart:1415:13)
#38     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#43     _StreamController._add (dart:async/stream_controller.dart:658:7)
#44     _StreamController.add (dart:async/stream_controller.dart:606:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#50     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
181 client.js:24977:34
    1 http://localhost:39907/dwds/src/injected/client.js:24977
    $protected http://localhost:39907/dwds/src/injected/client.js:3589
    call$2 http://localhost:39907/dwds/src/injected/client.js:11698
    _asyncStartSync http://localhost:39907/dwds/src/injected/client.js:3553
    $call$body$main__closure http://localhost:39907/dwds/src/injected/client.js:24985
    call$1 http://localhost:39907/dwds/src/injected/client.js:24911
    _rootRunUnary http://localhost:39907/dwds/src/injected/client.js:3948
    runUnary$2$2 http://localhost:39907/dwds/src/injected/client.js:13095
    runUnaryGuarded$1$2 http://localhost:39907/dwds/src/injected/client.js:13042
    _sendData$1 http://localhost:39907/dwds/src/injected/client.js:12635
    _add$1 http://localhost:39907/dwds/src/injected/client.js:12581
    _add$1 http://localhost:39907/dwds/src/injected/client.js:12916
    _handleData$2 http://localhost:39907/dwds/src/injected/client.js:12979
    _handleData$1 http://localhost:39907/dwds/src/injected/client.js:12942
    Closure_cspForwardCall http://localhost:39907/dwds/src/injected/client.js:1348
    _rootRunUnary http://localhost:39907/dwds/src/injected/client.js:3948
    runUnary$2$2 http://localhost:39907/dwds/src/injected/client.js:13095
    runUnaryGuarded$1$2 http://localhost:39907/dwds/src/injected/client.js:13042
    _sendData$1 http://localhost:39907/dwds/src/injected/client.js:12635
    _add$1 http://localhost:39907/dwds/src/injected/client.js:12581
    _sendData$1 http://localhost:39907/dwds/src/injected/client.js:12427
    add$1 http://localhost:39907/dwds/src/injected/client.js:12306
    Closure_cspForwardInterceptedCall http://localhost:39907/dwds/src/injected/client.js:1406
    _rootRunUnary http://localhost:39907/dwds/src/injected/client.js:3948
    runUnary$2$2 http://localhost:39907/dwds/src/injected/client.js:13095
    runUnaryGuarded$1$2 http://localhost:39907/dwds/src/injected/client.js:13042
    _sendData$1 http://localhost:39907/dwds/src/injected/client.js:12635
    _add$1 http://localhost:39907/dwds/src/injected/client.js:12581
    _sendData$1 http://localhost:39907/dwds/src/injected/client.js:12427
    add$1 http://localhost:39907/dwds/src/injected/client.js:12306
    add$1 http://localhost:39907/dwds/src/injected/client.js:24411
    call$1 http://localhost:39907/dwds/src/injected/client.js:24701
    call$1 http://localhost:39907/dwds/src/injected/client.js:18104
    _rootRunUnary http://localhost:39907/dwds/src/injected/client.js:3952
    runUnary$2$2 http://localhost:39907/dwds/src/injected/client.js:13095
    runUnaryGuarded$1$2 http://localhost:39907/dwds/src/injected/client.js:13042
    call$1 http://localhost:39907/dwds/src/injected/client.js:13232
    invokeClosure http://localhost:39907/dwds/src/injected/client.js:1238
    $function http://localhost:39907/dwds/src/injected/client.js:1257
    (Asíncrono: EventListener.handleEvent)
    _addEventListener$3 http://localhost:39907/dwds/src/injected/client.js:17029
    addEventListener$3 http://localhost:39907/dwds/src/injected/client.js:17023
    addEventListener$3$x http://localhost:39907/dwds/src/injected/client.js:9273
    _tryResume$0 http://localhost:39907/dwds/src/injected/client.js:18085
    _EventStreamSubscription$ http://localhost:39907/dwds/src/injected/client.js:6930
    HtmlWebSocketChannel$1 http://localhost:39907/dwds/src/injected/client.js:24646
    HtmlWebSocketChannel$connect http://localhost:39907/dwds/src/injected/client.js:8718
    0 http://localhost:39907/dwds/src/injected/client.js:24754
    $protected http://localhost:39907/dwds/src/injected/client.js:3589
    call$2 http://localhost:39907/dwds/src/injected/client.js:11698
    _asyncStartSync http://localhost:39907/dwds/src/injected/client.js:3553
    call$0 http://localhost:39907/dwds/src/injected/client.js:24806
    _rootRun http://localhost:39907/dwds/src/injected/client.js:3933
    run$1$1 http://localhost:39907/dwds/src/injected/client.js:13087
    runZonedGuarded http://localhost:39907/dwds/src/injected/client.js:4045
    main http://localhost:39907/dwds/src/injected/client.js:8756
    <anonymous> http://localhost:39907/dwds/src/injected/client.js:26813
    <anonymous> http://localhost:39907/dwds/src/injected/client.js:26796
    dartProgram http://localhost:39907/dwds/src/injected/client.js:26807
    <anonymous> http://localhost:39907/dwds/src/injected/client.js:26815
```

### Code sample

A default new flutter web project

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output
<details open>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.16.5, on KDE neon 5.27 6.2.0-39-generic, locale es_ES.UTF-8)
    • Flutter version 3.16.5 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (hace 2 semanas), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android-sdk/
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio-2023.1.1/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.27.5
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.1)
    • Android Studio at /opt/android-studio-2023.1.1/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[!] Android Studio (version unknown)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • KDE neon 5.27 6.2.0-39-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @dumabg, which version of flutter did this work for you in? According to https://github.com/flutter/flutter/issues/120691#issuecomment-1433590688, this isn't guaranteed to work. 

Have you tried running with `flutter run -d web-server` to see if that works?

**Comment by dumabg** [comment]
> Hi @dumabg, which version of flutter did this work for you in? According to [#120691 (comment)](https://github.com/flutter/flutter/issues/120691#issuecomment-1433590688), this isn't guaranteed to work.
> 
> Have you tried running with `flutter run -d web-server` to see if that works?

Hi @danagbemava-nc, it works on 3.13. 

With `flutter run -d web-server ` Firefox doesn't show any errors.

**Comment by dumabg** [comment]
The debugger on VSC, gives this errors when try to inspect the variables:

`getObject: (-32603) Unexpected DWDS error for getObject: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast`


```
NavigatorState (NavigatorState#d0fb8(tickers: tracking 2 tickers))
getObject: (-32603) Unexpected DWDS error for getObject: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1930:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2499:21)
#2      VmService.getObject (package:vm_service/src/vm_service.dart:2231:7)
#3      ProtocolConverter._getterNamesForClassHierarchy (package:dds/src/dap/protocol_converter.dart:728:25)
<asynchronous suspension>
#4      ProtocolConverter.convertVmInstanceToVariablesList (package:dds/src/dap/protocol_converter.dart:299:13)
<asynchronous suspension>
#5      DartDebugAdapter.variablesRequest (package:dds/src/dap/adapters/dart.dart:1972:26)
<asynchronous suspension>
#6      BaseDebugAdapter.handle (package:dds/src/dap/base_debug_adapter.dart:141:7)
<asynchronous suspension>

```

**Comment by danagbemava-nc** [comment]
Hi @dumabg, that issue is being tracked in https://github.com/dart-lang/webdev/issues/2297

You may follow up in that issue for updates. 

Closing this as solved since the recommended way to test on browsers other than chrome is to use the web-server. 

Thank you
