### ISSUE TITLE
Null check operator used on a null value for paragraph.dart

### ISSUE THREAD

**Issue by ThatPham2000** [flutter/flutter#141007]
### Steps to reproduce

I can not reproduce because it does not always occur.
I run the integration test for mobile (iPhone 15, iOS 17). It occurred and stopped my test.

### Expected results

It will go fine without null pointer exception

### Actual results

Null check operator used on a null value

### Code sample

<details open><summary>Code sample</summary>

```dart
// Flutter integration test
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Null check operator used on a null value
  package:flutter/src/rendering/paragraph.dart 313:43                                                                    RenderParagraph.text
  package:flutter/src/rendering/paragraph.dart 1273:7                                                                    RenderParagraph.debugDescribeChildren
  package:flutter/src/foundation/diagnostics.dart 2901:48                                                                DiagnosticableTreeNode.getChildren
  package:flutter/src/foundation/diagnostics.dart 1193:43                                                                TextTreeRenderer._debugRender
  package:flutter/src/foundation/diagnostics.dart 1125:14                                                                TextTreeRenderer.render
  package:flutter/src/foundation/diagnostics.dart 1326:39                                                                TextTreeRenderer._debugRender
  package:flutter/src/foundation/diagnostics.dart 1125:14                                                                TextTreeRenderer.render
  package:flutter/src/foundation/diagnostics.dart 1782:9                                                                 DiagnosticsNode.toStringDeep.<fn>
  package:flutter/src/foundation/diagnostics.dart 1789:6                                                                 DiagnosticsNode.toStringDeep
  package:flutter/src/foundation/assertions.dart 743:65                                                                  FlutterErrorDetails.toString
  package:integration_test/integration_test.dart 86:67                                                                   new IntegrationTestWidgetsFlutterBinding.<fn>
  package:flutter_test/src/binding.dart 810:28                                                                           TestWidgetsFlutterBinding._createTestCompletionHandler.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                                                             Future.whenComplete
  package:flutter_test/src/binding.dart 992:8                                                                            TestWidgetsFlutterBinding._runTest
  package:flutter_test/src/binding.dart 2013:12                                                                          LiveTestWidgetsFlutterBinding.runTest
  package:integration_test/integration_test.dart 234:17                                                                  IntegrationTestWidgetsFlutterBinding.runTest
  package:flutter_test/src/widget_tester.dart 161:24                                                                     testWidgets.<fn>
  ===== asynchronous gap ===========================
  package:stream_channel                                                                                                 _GuaranteeSink.add
  var/folders/3w/f1qw569546bd9dsdx5y2w6q00000gq/T/flutter_tools.y1c6kb/flutter_test_listener.D2ag9I/listener.dart 53:22  main.<fn>
  
  Null check operator used on a null value
  package:flutter/src/rendering/paragraph.dart 313:43                                                                    RenderParagraph.text
  package:flutter/src/rendering/paragraph.dart 1273:7                                                                    RenderParagraph.debugDescribeChildren
  package:flutter/src/foundation/diagnostics.dart 2901:48                                                                DiagnosticableTreeNode.getChildren
  package:flutter/src/foundation/diagnostics.dart 1193:43                                                                TextTreeRenderer._debugRender
  package:flutter/src/foundation/diagnostics.dart 1125:14                                                                TextTreeRenderer.render
  package:flutter/src/foundation/diagnostics.dart 1326:39                                                                TextTreeRenderer._debugRender
  package:flutter/src/foundation/diagnostics.dart 1125:14                                                                TextTreeRenderer.render
  package:flutter/src/foundation/assertions.dart 1019:13                                                                 FlutterError.dumpErrorToConsole
  package:flutter_test/src/binding.dart 873:24                                                                           TestWidgetsFlutterBinding._runTest.<fn>
  package:flutter/src/foundation/assertions.dart 1181:14                                                                 FlutterError.reportError
  package:flutter/src/widgets/widget_inspector.dart 3461:20                                                              _parseDiagnosticsNode.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                                                             scheduleMicrotask
  package:flutter/src/widgets/widget_inspector.dart 3460:5                                                               _parseDiagnosticsNode
  package:flutter/src/widgets/widget_inspector.dart 3434:21                                                              debugTransformDebugCreator
  package:flutter/src/foundation/assertions.dart 1292:31                                                                 _FlutterErrorDetailsNode.builder
  package:flutter/src/foundation/diagnostics.dart 2873:105                                                               DiagnosticableNode.getProperties
  package:flutter/src/foundation/diagnostics.dart 1252:63                                                                TextTreeRenderer._debugRender
  package:flutter/src/foundation/diagnostics.dart 1125:14                                                                TextTreeRenderer.render
  package:flutter/src/foundation/diagnostics.dart 1782:9                                                                 DiagnosticsNode.toStringDeep.<fn>
  package:flutter/src/foundation/diagnostics.dart 1789:6                                                                 DiagnosticsNode.toStringDeep
  package:flutter/src/foundation/assertions.dart 743:65                                                                  FlutterErrorDetails.toString
  package:integration_test/integration_test.dart 86:67                                                                   new IntegrationTestWidgetsFlutterBinding.<fn>
  package:flutter_test/src/binding.dart 810:28                                                                           TestWidgetsFlutterBinding._createTestCompletionHandler.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                                                             Future.whenComplete
  package:flutter_test/src/binding.dart 992:8                                                                            TestWidgetsFlutterBinding._runTest
  package:flutter_test/src/binding.dart 2013:12                                                                          LiveTestWidgetsFlutterBinding.runTest
  package:integration_test/integration_test.dart 234:17                                                                  IntegrationTestWidgetsFlutterBinding.runTest
  package:flutter_test/src/widget_tester.dart 161:24                                                                     testWidgets.<fn>
  ===== asynchronous gap ===========================
  package:stream_channel                                                                                                 _GuaranteeSink.add
  var/folders/3w/f1qw569546bd9dsdx5y2w6q00000gq/T/flutter_tools.y1c6kb/flutter_test_listener.D2ag9I/listener.dart 53:22  main.<fn>
  
══╡ EXCEPTION CAUGHT BY WIDGET INSPECTOR ╞══════════════════════════════════════════════════════════
The following assertion was thrown:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4729:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4743:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4855:12)
#3      _describeRelevantUserCode (package:flutter/src/widgets/widget_inspector.dart:3535:13)
#4      _parseDiagnosticsNode (package:flutter/src/widgets/widget_inspector.dart:3458:12)
#5      debugTransformDebugCreator (package:flutter/src/widgets/widget_inspector.dart:3434:21)
#6      _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1292:31)
#7      DiagnosticableNode.emptyBodyDescription (package:flutter/src/foundation/diagnostics.dart:2870:77)
#8      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1290:14)
#9      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1125:14)
#10     DiagnosticsNode.toStringDeep.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1782:9)
#11     DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:1789:6)
#12     FlutterErrorDetails.toString (package:flutter/src/foundation/assertions.dart:743:65)
#13     new IntegrationTestWidgetsFlutterBinding.<anonymous closure> (package:integration_test/integration_test.dart:86:67)
#14     TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:810:28)
<asynchronous suspension>
(elided 8 frames from dart:async and package:stack_trace)

This exception was caught while trying to describe the user-relevant code of another error.
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGET INSPECTOR ╞══════════════════════════════════════════════════════════
The following assertion was thrown:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4729:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4743:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4855:12)
#3      _describeRelevantUserCode (package:flutter/src/widgets/widget_inspector.dart:3535:13)
#4      _parseDiagnosticsNode (package:flutter/src/widgets/widget_inspector.dart:3458:12)
#5      debugTransformDebugCreator (package:flutter/src/widgets/widget_inspector.dart:3434:21)
#6      _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1292:31)
#7      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2873:105)
#8      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1252:63)
#9      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1125:14)
#10     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1019:13)
#11     TestWidgetsFlutterBinding._runTest.<anonymous closure> (package:flutter_test/src/binding.dart:873:24)
#12     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1181:14)
#13     _parseDiagnosticsNode.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:3461:20)
(elided 14 frames from dart:async and package:stack_trace)

This exception was caught while trying to describe the user-relevant code of another error.
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGET INSPECTOR ╞══════════════════════════════════════════════════════════
The following assertion was thrown:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4729:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4743:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4855:12)
#3      _describeRelevantUserCode (package:flutter/src/widgets/widget_inspector.dart:3535:13)
#4      _parseDiagnosticsNode (package:flutter/src/widgets/widget_inspector.dart:3458:12)
#5      debugTransformDebugCreator (package:flutter/src/widgets/widget_inspector.dart:3434:21)
#6      _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1292:31)
#7      DiagnosticableNode.emptyBodyDescription (package:flutter/src/foundation/diagnostics.dart:2870:77)
#8      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1290:14)
#9      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1125:14)
#10     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1019:13)
#11     TestWidgetsFlutterBinding._runTest.<anonymous closure> (package:flutter_test/src/binding.dart:873:24)
#12     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1181:14)
#13     _parseDiagnosticsNode.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:3461:20)
(elided 14 frames from dart:async and package:stack_trace)

This exception was caught while trying to describe the user-relevant code of another error.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.6.1 22G313 darwin-arm64, locale
    en-VN)
    • Flutter version 3.16.5 on channel stable at /Users/phat/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (2 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/phat/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/phat/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • BBED109D-1CDB-480A-9F39-7C6F13F4E28B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 13.6.1 22G313 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
> Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

From the logs, this might be an issue with your code structure and not necessarily an issue with Flutter itself.

Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code or a sample repo or a simple repo to run on our end?
Thank you

**Comment by Nirwana206** [comment]
According to the logs the error is with your structure

**Comment by moffatman** [comment]
Please share the integration test that causes this exception to be thrown

**Comment by AliKales** [comment]
Having same problem. I just upgraded to Flutter 3.16.5 and now i cant run new projects

**Comment by AliKales** [comment]
I just went back to 3.16.4 now everything works fine

**Comment by soltanzadehErfan** [comment]
if you upgrade your flutter manually you should run this command :
flutter pub cache repair OR flutter pub cache clean

**Comment by ThatPham2000** [comment]
> I just went back to 3.16.4 now everything works fine

It sometimes occurs. I do not know why. Therefore, you can try it several times whether it happens or not.

**Comment by ThatPham2000** [comment]
> Please share the integration test that causes this exception to be thrown

```
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('App test', () {
    // app set up => call API 
    // app tear down

    group('Test 1', () {
      // setUp
      testWidgets(
        '1a',
        (tester) async {
          // call api config for this test case
          
          // start app
          app.main();
          await tester.pumpAndSettle();
          
          // Do some normal actions
          
          // call api to fetch new app config or data and update it to the app
        },
      );
      
      testWidgets('1b', (tester) async {
        // Similar to 1a
      });
    });
    
    group('Test 2', () {
      // Similar to Test 1
    });
  });
}
```

**Comment by ThatPham2000** [comment]
Do we have any solutions when a test case throws an exception then another test case still runs as usual?
