### ISSUE TITLE
Slow operations with setRefreshRateFPS causing ANR on android devices

### ISSUE THREAD

**Issue by matinzd** [flutter/flutter#141095]
### Steps to reproduce

I have no idea how it's happening since it's on production

### Code sample

<details open><summary>Code sample</summary>

```dart
// Something is happening in the flutter core
```

</details>

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

Galaxy S22+ (Android 14)

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Logs

<details open><summary>Logs</summary>

```console
main (runnable):tid=1 systid=26660 
       at io.flutter.embedding.engine.FlutterJNI.setRefreshRateFPS(FlutterJNI.java)
       at io.flutter.view.VsyncWaiter$DisplayListener.onDisplayChanged(VsyncWaiter.java:32)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:1774)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.lambda$sendDisplayEvent$0(DisplayManagerGlobal.java:1742)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.$r8$lambda$aO0d1U2yv7-42_0MvY8uEf7AtpE(unavailable)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate$$ExternalSyntheticLambda0.run(unavailable:6)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.9, on macOS 13.6.1 22G313 darwin-arm64, locale en-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by orestesgaolin** [comment]
Hopefully it's going to be helpful, but it happens to our app as well, so far to OnePlus 10T 5G (120 Hz screen) running Android 14 and flutter 3.13.8.

```
main (runnable):tid=1 systid=10986 
       at io.flutter.embedding.engine.FlutterJNI.setRefreshRateFPS(FlutterJNI.java:277)
       at io.flutter.view.VsyncWaiter$DisplayListener.onDisplayChanged(VsyncWaiter.java:41)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:1180)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.lambda$sendDisplayEvent$0(DisplayManagerGlobal.java:1147)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.$r8$lambda$aO0d1U2yv7-42_0MvY8uEf7AtpE(unavailable)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate$$ExternalSyntheticLambda0.run(unavailable:6)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8815)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by darshankawar** [comment]
@orestesgaolin 


> Is there a way for you to find out what kind of slow operations are being performed on the devices ?
> The more info you could provide, the more it'll help us to properly analyze the issue.
