### ISSUE TITLE
Flutter test crashes with generated test case on Windows

### ISSUE THREAD

**Issue by letsar** [flutter/flutter#14106]
## Steps to Reproduce

1. Create a new Flutter package (or Flutter application) from Android Studio
2. Run the generated tests or run flutter test with the generated file as argument

### Results

The command crashes: 

> Shell: [ERROR:e:\b\build\slave\windows_engine\build\src\topaz\lib\tonic\logging\dart_error.cc(16)] Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
> Shell: [ERROR:e:\b\build\slave\windows_engine\build\src\topaz\lib\tonic\logging\dart_error.cc(16)] Dart_GetClosure expects argument 'library' to be non-null.
> Failed to load "D:\Dev\flutter_devs\graviton\test\graviton_test.dart":
> Shell subprocess crashed with unexpected exit code 254 before connecting to test harness.
> Test: D:\Dev\flutter_devs\graviton\test\graviton_test.dart
> Shell: D:\Dev\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester

### Notes

There are no problems if I run the tests with dart.exe:

``` powershell
PS D:\Dev\flutter_devs\flutter_package\test> D:\dev\flutter\bin\cache\dart-sdk\bin\dart.exe .\flutter_package_test.dart
00:00 +0: adds one to input values
00:00 +1: All tests passed!
```

## Logs
From D:\Dev\flutter_devs\flutter_package> flutter test .\test\flutter_package_test.dart

``` powershell
Shell: [ERROR:e:\b\build\slave\windows_engine\build\src\topaz\lib\tonic\logging\dart_error.cc(16)] Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
Shell: [ERROR:e:\b\build\slave\windows_engine\build\src\topaz\lib\tonic\logging\dart_error.cc(16)] Dart_GetClosure expects argument 'library' to be non-null.
00:00 +0 -1: loading D:\Dev\flutter_devs\flutter_package\.\test\flutter_package_test.dart [E]
  Failed to load "D:\Dev\flutter_devs\flutter_package\.\test\flutter_package_test.dart":
  Shell subprocess crashed with unexpected exit code 254 before connecting to test harness.
  Test: D:\Dev\flutter_devs\flutter_package\.\test\flutter_package_test.dart
  Shell: D:\Dev\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester


00:00 +0 -1: Some tests failed.
PS D:\Dev\flutter_devs\flutter_package> flutter test -v .\test\flutter_package_test.dart
[  +24 ms] [D:\Dev\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[        ] [D:\Dev\flutter\] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] alpha
[        ] [D:\Dev\flutter\] git ls-remote --get-url origin
[  +53 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [D:\Dev\flutter\] git log -n 1 --pretty=format:%H
[  +54 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8f65fec5f5f7d7afbb0965f4a44bdb330a28fb19
[        ] [D:\Dev\flutter\] git log -n 1 --pretty=format:%ar
[  +55 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 weeks ago
[ +147 ms] running test package with arguments: [--, D:\Dev\flutter_devs\flutter_package\.\test\flutter_package_test.dart]
[ +171 ms] test 0: starting test D:\Dev\flutter_devs\flutter_package\.\test\flutter_package_test.dart
[  +22 ms] test 0: starting shell process
[        ] D:\Dev\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester --disable-observatory --enable-dart-profiling --non-interactive --enable-checked-mode --use-test-fonts --packages=D:\Dev\flutter_devs\flutter_package\.packages D:\Système\Temp\dart_test_listener979753c1-fa2e-11e7-b86d-408d5cb3c159/listener.dart
[ +171 ms] test 0: awaiting initial result for pid 1316
[ +159 ms] Shell: [ERROR:e:\b\build\slave\windows_engine\build\src\topaz\lib\tonic\logging\dart_error.cc(16)] Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
[   +1 ms] Shell: [ERROR:e:\b\build\slave\windows_engine\build\src\topaz\lib\tonic\logging\dart_error.cc(16)] Dart_GetClosure expects argument 'library' to be non-null.
[  +68 ms] test 0: process with pid 1316 crashed before connecting to test harness
[   +5 ms] test 0: waiting for controller sink to close
[  +10 ms] test 0: cleaning up...
[   +7 ms] test 0: shutting down test harness socket server
00:00 +0 -1: loading D:\Dev\flutter_devs\flutter_package\.\test\flutter_package_test.dart [E]
  Failed to load "D:\Dev\flutter_devs\flutter_package\.\test\flutter_package_test.dart":
  Shell subprocess crashed with unexpected exit code 254 before connecting to test harness.
  Test: D:\Dev\flutter_devs\flutter_package\.\test\flutter_package_test.dart
  Shell: D:\Dev\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester


00:00 +0 -1: Some tests failed.
[  +23 ms] test package returned with exit code 1
[  +12 ms] "flutter test" took 698ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:217)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
<asynchronous suspension>
#3      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      new Future.sync (dart:async/future.dart:222)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#10     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     runZoned (dart:async/zone.dart:1467)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#19     main (file:///D:/Dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[  +10 ms] test 0: deleting temporary directory
[   +2 ms] test 0: finished
[  +18 ms] ensureAnalyticsSent: 22ms
[   +4 ms] exiting with code 1

```
## Flutter Doctor

[√] Flutter (on Microsoft Windows [version 10.0.16299.64], locale fr-FR, channel alpha)
    • Flutter at D:\Dev\flutter
    • Framework revision 8f65fec5f5 (5 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at D:\DevResources\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = D:\DevResources\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices
    • Samsung Galaxy S8, 7 0 0, API 24, 1440x2960 • 192.168.156.101:5555 • android-x86 • Android 7.0 (API 24)

**Comment by Hixie** [comment]
We believe this is fixed now. If you still see it, please file a new bug and we'll look into it.
