### ISSUE TITLE
[tool_crash] SessionNotCreatedException

### ISSUE THREAD

**Issue by KarthikPrabhu123** [flutter/flutter#141010]
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SessionNotCreatedException
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:81:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:144:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:323:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.6, on Ubuntu 20.04.6 LTS 5.15.0-91-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.13.6 on channel stable at /home/karthik/snap/flutter/common/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision ead455963c (3 months ago), 2023-09-26 18:28:17 -0700
    [32m•[39m Engine revision a794cf2681
    [32m•[39m Dart version 3.1.3
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /home/karthik/Android/Sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /snap/android-studio/140/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 10.0.0-4ubuntu1
    [32m•[39m cmake version 3.16.3
    [32m•[39m ninja version 1.10.0
    [32m•[39m pkg-config version 0.29.1

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at /snap/android-studio/128/android-studio
    [32m•[39m Flutter plugin version 76.1.2
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /snap/android-studio/140
    [32m•[39m Flutter plugin version 77.1.2
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version unknown)
    [32m•[39m VS Code at /snap/code/current
    [32m•[39m Flutter extension version 3.80.0
    [31m✗[39m Unable to determine VS Code version.

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.6 LTS 5.15.0-91-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.109

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 135454af32477f815a7525073027a3ff9eff1bfd
### Plugins
integration_test

**Comment by dam-ease** [comment]
Thanks for filing this issue @KarthikPrabhu123. This seems to be similar to https://github.com/flutter/flutter/issues/123602. You can see https://github.com/flutter/flutter/issues/123602#issuecomment-1490895875 and https://github.com/flutter/flutter/issues/123602#issuecomment-1662235796 for solution and check if it works for you.
Also check https://github.com/flutter/flutter/issues/131297#issuecomment-1651399775 and see what chromedriver version are you using and whether Downgrading chromedriver than your current version solves the issue or not.
Closing from here, as this isn't related to flutter but could be related to the chromedriver version's compatibility. If you disagree, write in comments and I'll reopen it.

**Comment by KarthikPrabhu123** [comment]
As mentioned in the comment, I downgraded the Chrome driver version to (ChromeDriver 114.0.5735.90 ) and am currently facing the same error.

**Comment by ZhuChanJuan** [comment]
actually this issue doesn't relate to the chromedriver version's compatibility.
please check my issue detail : https://github.com/flutter/flutter/issues/148029
