### ISSUE TITLE
http_disallow_http_connections_test.dart flakes on mac in engine CI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#141149]
From https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/239932/overview

```
[ERROR:flutter/shell/testing/tester_main.cc(666)] Unhandled exception
Exception: SocketException: Failed to create server socket (OS Error: Can't assign requested address, errno = 49), address = build846-m9.golo.chromium.org, port = 0
Stack trace: #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1032:7)
<asynchronous suspension>
#1      _RawServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:1812:15)
<asynchronous suspension>
#2      _ServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2097:15)
<asynchronous suspension>
#3      _HttpServer.bind.<anonymous closure> (dart:_http/http_impl.dart:3186:27)
<asynchronous suspension>
#4      bindServerAndTest (file:///Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/dart/http_disallow_http_connections_test.dart:35:29)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/dart/http_disallow_http_connections_test.dart:73:5)
<asynchronous suspension>
#6      Test.run.<anonymous closure>.<anonymous closure> (package:litetest/src/test.dart:69:11)
<asynchronous suspension>
#7      Test.run.<anonymous closure> (package:litetest/src/test.dart:65:7)
<asynchronous suspension>
#8      test.<anonymous closure> (package:async_helper/async_minitest.dart:52:17)
<asynchronous suspension>
```

**Comment by zanderso** [comment]
@aam It looks like this test has become very flaky on an update to our macOS infrastructure. Do you have any thoughts on what the issue might be? Also cc @brianquinlan.

**Comment by matanlurey** [comment]
@zanderso:

> I suspect it is related to the dialog that pops up when the test runs locally.
>
> on an arm mac

**Comment by matanlurey** [comment]
I don't mind taking a quick look - I have an ARM Mac.

**Comment by matanlurey** [comment]
Using the prebuilt Dart SDK this test failsy (ignores `// FlutterTesterOptions=--disallow-insecure-connections`).

This pops up during execution:

<img width="233" alt="Screenshot 2024-01-09 at 11 18 04 AM" src="https://github.com/flutter/flutter/assets/168174/b02cdab1-1574-46b1-839a-7a3238ba4b62">

```bash
$ ./prebuilts/macos-arm64/dart-sdk/bin/dart testing/dart/http_disallow_http_connections_test.dart

...

Unhandled exception:
In test "testWithLocalIP" Expect.deepEquals(expected: <true>, actual: <false>) fails.
#0      Expect._fail (package:expect/expect.dart:721:5)
#1      Expect.deepEquals (package:expect/expect.dart:572:7)
#2      equals.<anonymous closure> (package:async_helper/async_minitest.dart:164:14)
#3      expect (package:async_helper/async_minitest.dart:72:4)
#4      asyncExpectThrows (file:///Users/matanl/Developer/engine/src/flutter/testing/dart/http_disallow_http_connections_test.dart:23:3)
```

FWIW, it _does_ pass locally when run using the CI configuration (and there is no pop-up):

```bash
$ flutter % ../out/host_debug_unopt_arm64/flutter_tester --disable-observatory --disallow-insecure-connections 
../out/host_debug_unopt_arm64/gen/http_disallow_http_connections_test.dart.dill

Test "testWithHostname": Skipped
unittest-suite-wait-for-done
Test "testWithLocalIP": Started
Test "testWithLoopback": Started
Test "testWithIPV6": Started
Test "testWithLocalIP": Passed
Test "testWithIPV6": Passed
Test "testWithLoopback": Passed
unittest-suite-success
```

**Comment by matanlurey** [comment]
Ok I tried one more thing:

```bash
$ for i in {1..1000}; do
../out/host_debug_unopt_arm64/flutter_tester --disable-observatory --disallow-insecure-connections ../out/host_debug_unopt_arm64/gen/http_disallow_http_connections_test.dart.dill
done
```

<img width="273" alt="Screenshot 2024-01-09 at 11 27 30 AM" src="https://github.com/flutter/flutter/assets/168174/e5c39e21-0d5c-4a54-a644-88fc30ca4e36">

**Comment by zanderso** [comment]
Skipping this test addresses the flake, and the functionality is being tested on platforms aside from macOS, so I'm going to drop the priority of this down to P2.

**Comment by aam** [comment]
I see "accept incoming connection" dialog showing up/disappearing quickly quite a few times during the test run `python3 flutter/testing/run_tests.py --variant host_profile --type dart` locally, and that doesn't seem to affect the tests passing.
I was not able to reproduce original error `OS Error: Can't assign requested address, errno = 49` locally.
What was the update to macos infrastructure that supposedly triggered flakiness, do you know @zanderso ?

**Comment by zanderso** [comment]
Looking at the bots where the test succeeds vs. fails, they are the same architecture, OS version, and Xcode version, so I think my theory that the flakes are related to infra upgrades is incorrect.

**Comment by brianquinlan** [comment]
Would it be easy to check if using socketfilterfw to add a firewall rule for the tests fixes the issue?

This is the approach that nodejs uses:
https://github.com/nodejs/node/blob/5398cb55ca10d34ed7ba5592f95b3b9f588e5754/tools/macos-firewall.sh

**Comment by aam** [comment]
@brianquinlan like I mentioned above I see popup showing up briefly when running tests locally and the tests still pass fine. So it doesn't look like a popup is a symptom of a problem.
