### ISSUE TITLE
[tool_crash] ProcessException: 应用程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。 Command: C:\Users\FYB\AppData\Local\Google\Chrome\Application\chrome.exe, OS error code: 14001

### ISSUE THREAD

**Issue by phfyb1** [flutter/flutter#141157]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: 应用程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。
 Command: C:\Users\FYB\AppData\Local\Google\Chrome\Application\chrome.exe, OS error code: 14001
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:689:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:559:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:688:12)
#6      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:260:53)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:219:36)
<asynchronous suspension>
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:145:17)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:332:9)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on Microsoft Windows [版本 10.0.23612.1000], locale zh-CN)
    [32m•[39m Flutter version 3.10.6 on channel stable at D:\Flutter\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (6 months ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    [32m•[39m Android SDK at D:\androidSDK
    [32m•[39m Platform android-33, build-tools 32.1.0-rc1
    [32m•[39m Java binary at: D:\android_studio1\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Users\FYB\AppData\Local\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at D:\android_studio1
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.23612.1000]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.200
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.4

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f468f3366c26a5092eb964a230ce7892fda8f2f8

**Comment by phfyb1** [comment]
因为升级了chrome，在原来目录下生成了一个new_chrome.exe，原来的chrome.exe失效了，删除chrome.exe并将new_chrome.exe重命名为chrome.exe，即可解决
