### ISSUE TITLE
[video_player] Very frequent flake on Android emulators

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#141145]
One of the issues we've been fighting since the break is frequent flake in the `video_player` integration tests. https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8759433708003124641/+/u/Run_package_tests/drive_examples/stdout is an example run, where the failure is:
```
02:13 +6: /b/s/w/ir/x/w/packages/packages/video_player/video_player/example/integration_test/video_player_test.dart: asset videos stay paused when seeking after video completed                       
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <false>
  Actual: <true>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/x/w/packages/packages/video_player/video_player/example/integration_test/video_player_test.dart:136:9)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///b/s/w/ir/x/w/packages/packages/video_player/video_player/example/integration_test/video_player_test.dart line 136
The test description was:
  stay paused when seeking after video completed
════════════════════════════════════════════════════════════════════════════════════════════════════

02:13 +6 -1: /b/s/w/ir/x/w/packages/packages/video_player/video_player/example/integration_test/video_player_test.dart: asset videos stay paused when seeking after video completed [E]                
  Test failed. See exception logs above.
  The test description was: stay paused when seeking after video completed
```

I know I've seen that one fail in other cases, but I believe there's at least one other that's flaking quite a bit. I believe we had some flake in this test before, but as with https://github.com/flutter/flutter/issues/141136 and https://github.com/flutter/flutter/issues/140987 it seems like this got dramatically worse recently on emulators for unknown reasons.

We'll want to collect more failure data from recent failures on the waterfall, but I wanted to capture this now since as we've handled some of the other issues it's becoming clearer how bad this one is. (E.g., https://github.com/flutter/packages/pull/5847 to try to fix other flake flaked on this test.)

I don't have numbers yet, but I think this one will also need some kind of disabling if we can't fix it soon. I can probably try to investigate a bit tomorrow.

/cc @reidbaker

**Comment by stuartmorgan** [comment]
I added some logging in a PR, and what I'm seeing is that when it fails the `isPlaying` value (which is controlled from the Android side by the `onIsPlayingChanged` callback is true, but the position isn't advancing, so test code like:
```dart
        final Duration tenMillisBeforeEnd =
            controller.value.duration - const Duration(milliseconds: 10);
        await controller.seekTo(tenMillisBeforeEnd);
        await controller.play();
        await tester.pumpAndSettle(_playDuration);
        expect(controller.value.isPlaying, false);
        expect(controller.value.position, controller.value.duration);
```

(where `_playDuration` is 1s) is failing, because `isPlaying` is still true.

I think the next step is to wire up `onPlaybackSuppressionReasonChanged` on the native side and see if we are getting anything. I'm wondering if this actually is dialog-related after all (like the other two), and we're losing audio focus and thus playback is being temporarily suppressed.

**Comment by gmackall** [comment]
Adding p1 because it seems you are actively working on this @stuartmorgan , feel free to change as you see fit

**Comment by stuartmorgan** [comment]
> I added some logging in a PR, and what I'm seeing is that when it fails the `isPlaying` value (which is controlled from the Android side by the `onIsPlayingChanged` callback) is true, but the position isn't advancing

It turns out this is sometimes true, but not always; sometimes it's advanced some, but it's still true that it's still "playing" even though it's been far too long for that to make sense. My guess is that there's a race where whatever happens (e.g., a mystery dialog pops up, if my theory is right) sometimes happens *during* the test, making it non-deterministic. For now I'm going to make it skip this test on Android any time `isPlaying` is still true after 1s.

**Comment by stuartmorgan** [comment]
@reidbaker Why is this closed? What I landed was intended as a temporary workaround, and it has a TODO to remove it once the underlying issue is fixed, referencing this issue for tracking.

**Comment by reidbaker** [comment]
> @reidbaker Why is this closed? What I landed was intended as a temporary workaround, and it has a TODO to remove it once the underlying issue is fixed, referencing this issue for tracking.

Sorry I was trying to be helpful.

**Comment by stuartmorgan** [comment]
Hm, this is still flaking. Most recently:

```
The following TestFailure was thrown running a test:
Expected: Duration:<0:00:07.540000>
  Actual: Duration:<0:00:07.566000>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/x/w/packages/packages/video_player/video_player/example/integration_test/video_player_test.dart:149:9)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///b/s/w/ir/x/w/packages/packages/video_player/video_player/example/integration_test/video_player_test.dart line 149
```

**Comment by reidbaker** [comment]
@stuartmorgan FWIW that is significantly closer than the margin we allow for camera length recordings.

**Comment by stuartmorgan** [comment]
In this case it seems like what's happened is that the video is reporting a play position that is slightly *after* the reported max duration of the video. I'm not sure how that would happen, but it seems like it's probably an exoplayer behavior, and that we should allow a bit of slop in this comparison.

**Comment by stuartmorgan** [comment]
> In this case it seems like what's happened is that the video is reporting a play position that is slightly _after_ the reported max duration of the video.

I'm changing the app-facing package's implementation to clamp the reported value in https://github.com/flutter/packages/pull/6899 since I think it's better to insulate clients from this weirdness than to make the test handle it.
