### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by hellolgl** [flutter/flutter#141238]
```
flutter run 
```
error
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

```
sudo flutter run  
```
Unable to find the currently connected Apple phone device, but Flutter devices can find it

MacBook-Pro flutter_private_app % sudo flutter run
Password:
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Connected devices:
macOS (desktop) • macos  • darwin-arm64   • macOS 12.6.2 21G320 darwin-arm64 (Rosetta)
Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

No wireless devices were found.

[1]: macOS (macos)
[2]: Chrome (chrome)
Please choose one (or "q" to quit): q

```
flutter devices 
```
MacBook-Pro flutter_private_app % flutter devices
3 connected devices:

iPhone 14 Pro (mobile) • A1D7951F-4265-4D4E-8037-53C0C24DEFE6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6.2 21G320 darwin-arm64 (Rosetta)
Chrome (web)           • chrome                               • web-javascript • Google Chrome 120.0.6099.199

```
flutter doctor 
```
[✓] Flutter (Channel stable, 3.13.1, on macOS 12.6.2 21G320 darwin-arm64 (Rosetta), locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      Target.clearStamp (package:flutter_tools/src/build_system/build_system.dart:166:29)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:880:19)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#10     FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart:694:16)
<asynchronous suspension>
#11     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart:1271:18)
<asynchronous suspension>
#12     HotRunner.run (package:flutter_tools/src/run_hot.dart:377:7)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:753:27)
<asynchronous suspension>
#14     Flutter

**Comment by hellolgl** [comment]
[flutter_05.log](https://github.com/flutter/flutter/files/13883895/flutter_05.log)

**Comment by danagbemava-nc** [comment]
Hi @hellolgl, does the user you are running the tool as have permissions to write to the directory where your flutter project is?

**Comment by hellolgl** [comment]
User does not have permission to write
<img width="458" alt="image" src="https://github.com/flutter/flutter/assets/56718826/0c354285-49b7-4c6e-8fdd-d9fc306a203d">
<img width="579" alt="image" src="https://github.com/flutter/flutter/assets/56718826/467d708a-dc0c-4bd6-a00c-4ca3cbb41a79">
This is strange

**Comment by huycozy** [comment]
Please try to grant the write permission to that user to see if it works.

**Comment by hellolgl** [comment]
My terminal's initial configuration files are the Zsh shell configuration files,. zshrc files, and. bash files_ The profile files are all configured with Flutter, and the paths are different. It is estimated that they were configured a long time ago. Thank you for your reply

**Comment by hellolgl** [comment]
The default situation is the configuration file of the Zsh shell

**Comment by huycozy** [comment]
I wonder if the shell configuration relates to the original issue. Could you confirm if the issue persists after granting right permissions?

**Comment by hellolgl** [comment]
Shell configuration is related to the original issue, and when I configure the shell correctly, this issue has been resolved

**Comment by huycozy** [comment]
I see. Closing the issue as solved.
