### ISSUE TITLE
NewEngineFragmentBuilder and NewEngineInGroupFragmentBuilder in FlutterFragment should respect shouldDestroyEngineWithHost when using provideFlutterEngine

### ISSUE THREAD

**Issue by techwn** [flutter/flutter#141239]
### Use case

We use local_auth plugin which used androidx Biometric on Android.

androidx biometric force use fragment Activity, so we change our super class to FlutterFragmentActivity.

Previously, we override `getCachedEngineId` to used cached fragment, but this result in blank screen after put app in background for over one night.

Then we  remove `getCachedEngineId`, and use override of `provideFlutterEngine`.

Recently, when using monkey test on Android, we found crash log for flutter fragment like this:

```console
crash:
// CRASH: com.mini.myBMW.preseries.cn.univ (pid 28143) (dump time: 2024-01-05 00:34:21
// Version: 
// Long Msg: java.lang.AssertionError: The internal FlutterEngine created by FlutterFragment{c10f699} (940cd33c-d79f-4781-adf4-f4001eed9003 id=0x1 tag=flutter_fragment) has been attached to by another activity. To persist a FlutterEngine beyond the ownership of this activity, explicitly create a FlutterEngine
// 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.detachFromFlutterEngine(Unknown Source:40)
// 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(Unknown Source:9)
// 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:37)
// 	at io.flutter.embedding.android.FlutterFragment.onAttach(Unknown Source:11)
// 	at androidx.fragment.app.Fragment.performAttach(Unknown Source:49)
// 	at androidx.fragment.app.FragmentStateManager.attach(Unknown Source:186)
// 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:134)
// 	at androidx.fragment.app.FragmentManager.executeOpsTogether(Unknown Source:347)
// 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(Unknown Source:81)
// 	at androidx.fragment.app.FragmentManager.execPendingActions(Unknown Source:21)
// 	at androidx.fragment.app.FragmentManager.dispatchStateChange(Unknown Source:38)
// 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(Unknown Source:11)
// 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(Unknown Source:4)
// 	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:20)
// 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1470)
// 	at android.app.Activity.performStart(Activity.java:8513)
// 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4656)
// 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
// 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
// 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
// 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
// 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2928)
// 	at android.os.Handler.dispatchMessage(Handler.java:117)
// 	at android.os.Looper.loopOnce(Looper.java:205)
// 	at android.os.Looper.loop(Looper.java:293)
// 	at android.app.ActivityThread.main(ActivityThread.java:9596)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
// crashend

```

### Proposal

I checked the start process of FlutterFragmentActivity and found this:

method `ensureFlutterFragmentCreated` in FlutterFragmentActivity will call `createFlutterFragment`,
when `getCachedEngineId() != null` it will use `CachedEngineFragmentBuilder` to build the Fragment, which provide `destroyEngineWithFragment` method to hook the engine.

But when using  provideFlutterEngine, It will use NewEngineFragmentBuilder, which config `ARG_DESTROY_ENGINE_WITH_FRAGMENT` to true in `createArgs`.
```java
    @NonNull
    protected Bundle createArgs() {
      Bundle args = new Bundle();
      args.putString(ARG_CACHED_ENGINE_GROUP_ID, cachedEngineGroupId);
      args.putString(ARG_DART_ENTRYPOINT, dartEntrypoint);
      args.putString(ARG_INITIAL_ROUTE, initialRoute);
      args.putBoolean(ARG_HANDLE_DEEPLINKING, handleDeeplinking);
      args.putString(
          ARG_FLUTTERVIEW_RENDER_MODE,
          renderMode != null ? renderMode.name() : RenderMode.surface.name());
      args.putString(
          ARG_FLUTTERVIEW_TRANSPARENCY_MODE,
          transparencyMode != null ? transparencyMode.name() : TransparencyMode.transparent.name());
      args.putBoolean(ARG_SHOULD_ATTACH_ENGINE_TO_ACTIVITY, shouldAttachEngineToActivity);
      args.putBoolean(ARG_DESTROY_ENGINE_WITH_FRAGMENT, true);
      args.putBoolean(
          ARG_SHOULD_AUTOMATICALLY_HANDLE_ON_BACK_PRESSED, shouldAutomaticallyHandleOnBackPressed);
      args.putBoolean(ARG_SHOULD_DELAY_FIRST_ANDROID_VIEW_DRAW, shouldDelayFirstAndroidViewDraw);
      return args;
    }
```

The same issue with NewEngineInGroupFragmentBuilder.

In FlutterFragment `shouldDestroyEngineWithHost` method, it deal with the cached case and provided case in same process.
But because NewEngineFragmentBuilder not respect to what we configured in FlutterFragmentActivity with `shouldDestroyEngineWithHost` method, we got this issue.

I think we should respect cached engine and provided engine in both creation of fragment and `detachFromFlutterEngine` in 
`FlutterActivityAndFragmentDelegate`

**Comment by techwn** [comment]
Currently, we found this crash in monkey test, We still can't confirm the stable reproduce steps for this crash. 
But I'm sure only the `FlutterActivityAndFragmentDelegate's` detachFromFlutterEngine method can throw this error, and the only call case is that there is another fragment calling 'onAttach'.

**Comment by techwn** [comment]
I'm not sure if this is caused by empty onAttachFragment override? since system sometimes kill the app and then relaunch the app, it will provide the fragment in this method. But it's hard to test this case.

**Comment by techwn** [comment]
Or should we reconsider, If it's reasonable to use NewEngineFragmentBuilder when we provide a engine?
```java
@NonNull
  protected FlutterFragment createFlutterFragment() {
    final BackgroundMode backgroundMode = getBackgroundMode();
    final RenderMode renderMode = getRenderMode();
    final TransparencyMode transparencyMode =
        backgroundMode == BackgroundMode.opaque
            ? TransparencyMode.opaque
            : TransparencyMode.transparent;
    final boolean shouldDelayFirstAndroidViewDraw = renderMode == RenderMode.surface;

    if (getCachedEngineId() != null) {
      Log.v(
          TAG,
          "Creating FlutterFragment with cached engine:\n"
              + "Cached engine ID: "
              + getCachedEngineId()
              + "\n"
              + "Will destroy engine when Activity is destroyed: "
              + shouldDestroyEngineWithHost()
              + "\n"
              + "Background transparency mode: "
              + backgroundMode
              + "\n"
              + "Will attach FlutterEngine to Activity: "
              + shouldAttachEngineToActivity());

      return FlutterFragment.withCachedEngine(getCachedEngineId())
          .renderMode(renderMode)
          .transparencyMode(transparencyMode)
          .handleDeeplinking(shouldHandleDeeplinking())
          .shouldAttachEngineToActivity(shouldAttachEngineToActivity())
          .destroyEngineWithFragment(shouldDestroyEngineWithHost())
          .shouldDelayFirstAndroidViewDraw(shouldDelayFirstAndroidViewDraw)
          .build();
    } else {
      Log.v(
          TAG,
          "Creating FlutterFragment with new engine:\n"
              + "Cached engine group ID: "
              + getCachedEngineGroupId()
              + "\n"
              + "Background transparency mode: "
              + backgroundMode
              + "\n"
              + "Dart entrypoint: "
              + getDartEntrypointFunctionName()
              + "\n"
              + "Dart entrypoint library uri: "
              + (getDartEntrypointLibraryUri() != null ? getDartEntrypointLibraryUri() : "\"\"")
              + "\n"
              + "Initial route: "
              + getInitialRoute()
              + "\n"
              + "App bundle path: "
              + getAppBundlePath()
              + "\n"
              + "Will attach FlutterEngine to Activity: "
              + shouldAttachEngineToActivity());

      if (getCachedEngineGroupId() != null) {
        return flutterFragment
            .withNewEngineInGroup(getCachedEngineGroupId())
            .dartEntrypoint(getDartEntrypointFunctionName())
            .initialRoute(getInitialRoute())
            .handleDeeplinking(shouldHandleDeeplinking())
            .renderMode(renderMode)
            .transparencyMode(transparencyMode)
            .shouldAttachEngineToActivity(shouldAttachEngineToActivity())
            .shouldDelayFirstAndroidViewDraw(shouldDelayFirstAndroidViewDraw)
            .build();
      }

      return FlutterFragment.withNewEngine()
          .dartEntrypoint(getDartEntrypointFunctionName())
          .dartLibraryUri(getDartEntrypointLibraryUri())
          .dartEntrypointArgs(getDartEntrypointArgs())
          .initialRoute(getInitialRoute())
          .appBundlePath(getAppBundlePath())
          .flutterShellArgs(FlutterShellArgs.fromIntent(getIntent()))
          .handleDeeplinking(shouldHandleDeeplinking())
          .renderMode(renderMode)
          .transparencyMode(transparencyMode)
          .shouldAttachEngineToActivity(shouldAttachEngineToActivity())
          .shouldDelayFirstAndroidViewDraw(shouldDelayFirstAndroidViewDraw)
          .build();
    }
  }
```

**Comment by gmackall** [comment]
cc @dnfield Dan would you take a look and see if you think the priority is correct?

**Comment by techwn** [comment]
Currently, we disable restore state by override:
```Kotlin
    override fun onAttachFragment(fragment: Fragment) {
        if (fragment is FlutterFragment) {
            fragment.arguments?.putBoolean("enable_state_restoration", false)
        }
    }
```
We will keep testing and feedback later.

**Comment by masayoshinag** [comment]
Are there any updates on this issue? 
In my app, same issue has been occurred recently.

**Comment by relaxedSoul** [comment]
I would like to ask if it was intentional: 

[In this comment](https://github.com/flutter/flutter/issues/141239#issuecomment-1884440387) The code fragment describes the function `createFlutterFragment`.

There are 3 places where the `return` is called with 3 different ways of creating the fragment. 
The first one is called, if the cached engine id is provided. **Only in this case, the method `.destroyEngineWithFragment(shouldDestroyEngineWithHost())` is called.** 

So, if it is expected behavior, please can you add some more clarification why for keeping engine running (not calling destroy), the ID is required? 

Also, it would help a lot if at least the requirement to provide the cached engine ID is noted in the documentation for the method `FlutterFragmentActivity.shouldDestroyEngineWithHost`. 

Currently, there is text about default value for return of the function, but it doesn't clarify that overriding the method does nothing if there is no cached engine ID provided via `FlutterFragmentActivity.getCachedEngineId`
