### ISSUE TITLE
Unable to perform a correct page transition with go_router when the locale change event refreshes the app.

### ISSUE THREAD

**Issue by dulejo** [flutter/flutter#141315]
### Steps to reproduce

1. setup the app with go_router, bottom navigation bar, auth and locale change logic (check the code)
2. change your current locale by either changing device's default language (I tried it on Android device), or by changing it throughout the app.

It can not be observed if you stay on login screen. (tried changing device's language and then check the app and it works fine), but once you log in and try the same or try to change app's language by clicking buttons on the HomeScreen it starts happening.

### Expected results

Upon changing locale labels on my screen are updated according to new language.

### Actual results

Just black screen is presented when page transition occurs. Sometimes I can see labels updated correctly for a brief moment before screen goes black.

### Code sample

<details open><summary>Code sample</summary>

```dart
main.dart
void main() async {
  Bloc.observer = SimpleBlocObserver();
  runApp(const MyApp());
}


class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late LocaleManager localeManager;
  late final UserRepository userRepository;
  bool isLocaleManagerInitialized = false;


  @override
  void initState() {
    super.initState();
    userRepository = UserRepositoryImpl();
  }

  // Closing stream
  @override
  void dispose() {
    userRepository.dispose();
    if (localeManager != null) {
      WidgetsBinding.instance.removeObserver(localeManager);
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext buildContext) {
    List<Locale> localeList = AppLocalizations.supportedLocales;

          return RepositoryProvider(
              create: (context) => userRepository,
              child: MultiBlocProvider(
                  providers: [
                    BlocProvider(
                      create: (context) =>
                      SplashBloc(userRepository: userRepository)
                        ..add(AnimationStartEvent()),
                    ),
                    BlocProvider(
                      create: (context) =>
                      LocaleBloc()
                        ..add(LoadLocale(View
                            .of(buildContext)
                            .platformDispatcher
                            .locale)),
                    ),
                    BlocProvider<AuthenticationBloc>(
                      create: (context) => AuthenticationBloc(
                          authenticationRepository: userRepository as UserRepositoryImpl),
                    )
                  ],
                  child: BlocBuilder<LocaleBloc, LocaleState>(
                      builder: (context, localeState) {
                        if (!isLocaleManagerInitialized) {
                          isLocaleManagerInitialized = true;

                          localeManager =
                              LocaleManager(onLocaleChanged: (Locale newLocale) {
                                context.read<LocaleBloc>().add(
                                    ChangeLocale(newLocale));
                              });

                          WidgetsBinding.instance.addPostFrameCallback((_) {
                            if (localeManager != null) {
                              WidgetsBinding.instance.addObserver(localeManager!);
                            }
                          });
                        }

                        return MaterialApp.router(
                          routerConfig: AppRouter.createRouter(context),
                          title: 'BloC Login Demo',
                          localizationsDelegates: AppLocalizations
                              .localizationsDelegates,
                          supportedLocales: localeList,
                          locale: localeState.locale,
                          theme: ThemeData(
                            colorScheme: ColorScheme.fromSeed(
                                seedColor: Colors.orange),
                            useMaterial3: true,
                            bottomNavigationBarTheme: const BottomNavigationBarThemeData(
                              backgroundColor: Colors.orange,
                              selectedItemColor: Colors.redAccent,
                              unselectedItemColor: Colors.grey,
                            ),
                          ),
                        );
                      })),
            );
  }
}
router.dart
class AppRouter {
  static final _rootNavigatorKey = GlobalKey<NavigatorState>();
  static final _shellNavigatorKey = GlobalKey<NavigatorState>();

  static GoRouter createRouter(BuildContext context) {
    return GoRouter(
      navigatorKey: _rootNavigatorKey,
      debugLogDiagnostics: true,
      refreshListenable: AuthenticationListenable(
          BlocProvider.of<AuthenticationBloc>(context)),
      redirect: (BuildContext context, GoRouterState state) {
        final authState = context.read<AuthenticationBloc>().state;

        final loggingIn = state.matchedLocation.contains('/login');
        final home = state.matchedLocation.contains('/first') ||
            state.matchedLocation.contains('/second') ||
            state.matchedLocation.contains('/third') ||
            state.matchedLocation.contains('/fourth') ||
            state.matchedLocation.contains('/fifth');

        if (authState.status == AuthenticationStatus.unknown) {
          return '/';
        }

        if (authState.status == AuthenticationStatus.unauthenticated &&
            !loggingIn) {
          return '/login';
        }

        if (authState.status == AuthenticationStatus.authenticated && !home) {
          return '/first';
        }
        return null;
      },
      routes: [
        ShellRoute(
          navigatorKey: _shellNavigatorKey,
          builder: (context, state, child) {
            return AppScaffold(child: child);
          },
          routes: <RouteBase>[
            GoRoute(
              parentNavigatorKey: _shellNavigatorKey,
              path: '/first',
              name: 'home',
              pageBuilder: (context, state) => NoTransitionPage(
                key: state.pageKey,
                child: const HomeScreen(
                  title: 'Home',
                ),
              ),
            ),
            GoRoute(
              parentNavigatorKey: _shellNavigatorKey,
              path: '/second',
              name: 'secondtab',
              pageBuilder: (context, state) => NoTransitionPage(
                key: state.pageKey,
                child: const SecondScreen(),
              ),
            ),
            GoRoute(
              parentNavigatorKey: _shellNavigatorKey,
              path: '/third',
              name: 'thirdtab',
              pageBuilder: (context, state) => NoTransitionPage(
                key: state.pageKey,
                child: const ThirdScreen(),
              ),
            ),
            GoRoute(
              parentNavigatorKey: _shellNavigatorKey,
              path: '/fourth',
              name: 'fourthtab',
              pageBuilder: (context, state) => NoTransitionPage(
                key: state.pageKey,
                child: const FourthScreen(),
              ),
            ),
            GoRoute(
              parentNavigatorKey: _shellNavigatorKey,
              path: '/fifth',
              name: 'fifthTab',
              pageBuilder: (context, state) => NoTransitionPage(
                key: state.pageKey,
                child: const FifthScreen(),
              ),
            ),
          ],
        ),
        GoRoute(
          path: '/',
          name: 'splash',
          pageBuilder: (context, state) => NoTransitionPage(
            key: state.pageKey,
            child: const SplashScreen(),
          ),
        ),
        GoRoute(
          path: '/login',
          name: 'login',
          pageBuilder: (context, state) => NoTransitionPage(
            key: state.pageKey,
            child: LoginView(),
          ),
        ),
      ],
      errorPageBuilder: (context, state) => NoTransitionPage(
        key: state.pageKey,
        child: Scaffold(
          body: Center(
            child: Text(
              'Page not found',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ),
        ),
      ),
    );
  }
}

app_scaffold.dart
class AppScaffold extends StatefulWidget {
  const AppScaffold({Key? key, required this.child}) : super(key: key);
  final Widget child;

  @override
  State<AppScaffold> createState() => _AppScaffoldState();
}

class _AppScaffoldState extends State<AppScaffold> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: widget.child,
      bottomNavigationBar: BottomNavigationBar(
              currentIndex: _calculateSelectedIndex(context),
              onTap: onTap,
              items: const [
                BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
                BottomNavigationBarItem(
                    icon: Icon(Icons.people), label: 'Second'),
                BottomNavigationBarItem(
                    icon: Icon(Icons.calendar_month), label: 'Third'),
                BottomNavigationBarItem(
                    icon: Icon(Icons.dashboard), label: 'Fourth'),
                BottomNavigationBarItem(icon: Icon(Icons.menu), label: 'Fifth'),
              ],
            ),
    );
  }

  int _calculateSelectedIndex(BuildContext context) {
    final GoRouterState route = GoRouterState.of(context);
    final String location = route.uri.toString();
    if (location.startsWith('/first')) {
      return 0;
    }
    if (location.startsWith('/second')) {
      return 1;
    }
    if (location.startsWith('/third')) {
      return 2;
    }
    if (location.startsWith('/fourth')) {
      return 3;
    }
    if (location.startsWith('/fifth')) {
      return 4;
    }
    return 0;
  }

  void onTap(int value) {
    switch (value) {
      case 0:
        return context.go('/first');
      case 1:
        return context.go('/second');
      case 2:
        return context.go('/third');
      case 3:
        return context.go('/fourth');
      case 4:
        return context.go('/fifth');
      default:
        return context.go('/first');
    }
  }
}

home_screen.dart
class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key, required String title});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('BloC Login Demo')),
        body: Center(
      child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
        Text(
          AppLocalizations.of(context)!.homeScreen,
          style:
              const TextStyle(color: Colors.green, fontWeight: FontWeight.bold),
        ),
        Text(
          AppLocalizations.of(context)!
              .user(context.read<AuthenticationBloc>().state.user.displayName),
        ),
        Text(
          AppLocalizations.of(context)!.numdays(daysLeftInMonth()),
        ),
        Text(
          AppLocalizations.of(context)!
              .commonCurrentDateTime(DateTime.now(), DateTime.now()),
        ),
        Text(formatCustomDate(DateTime.now(), context)),
        ElevatedButton(
          onPressed: () {
            context.read<LocaleBloc>().add(
                ChangeLocale(const Locale.fromSubtags(languageCode: 'en')));
          },
          child: Text(AppLocalizations.of(context)!.languageEn),
        ),
        ElevatedButton(
          onPressed: () {
            context.read<LocaleBloc>().add(ChangeLocale(
                const Locale.fromSubtags(
                    languageCode: 'sr',
                    scriptCode: 'Latn',
                    countryCode: 'RS')));
          },
          child: Text(AppLocalizations.of(context)!.languageSrLatn),
        ),
        ElevatedButton(
          onPressed: () {
            context.read<LocaleBloc>().add(ChangeLocale(
                const Locale.fromSubtags(
                    languageCode: 'sr',
                    scriptCode: 'Cyrl',
                    countryCode: 'RS')));
          },
          child: Text(AppLocalizations.of(context)!.languageSrCyrl),
        ),
        ElevatedButton(
          onPressed: () {
            context
                .read<AuthenticationBloc>()
                .add(AuthenticationLogoutRequested());
          },
          child: Text(AppLocalizations.of(context)!.logout),
        ),
      ]),
    ));
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
====================================================================================================
E/flutter (18222): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/focus_manager.dart': Failed assertion: line 1256 pos 12: '_focusedChildren.isEmpty || _focusedChildren.last.enclosingScope == this': Focused child does not have the same idea of its enclosing scope as the scope does.
E/flutter (18222): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (18222): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (18222): #2      FocusScopeNode.focusedChild (package:flutter/src/widgets/focus_manager.dart:1256:12)
E/flutter (18222): #3      _Autofocus.applyIfValid (package:flutter/src/widgets/focus_manager.dart:140:37)
E/flutter (18222): #4      FocusManager.applyFocusChangesIfNeeded (package:flutter/src/widgets/focus_manager.dart:1640:17)
E/flutter (18222): #5      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (18222): #6      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (18222): 

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Focused child does not have the same idea of its enclosing scope as the scope does.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 1256 pos 12: '_focusedChildren.isEmpty || _focusedChildren.last.enclosingScope == this'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      FocusScopeNode.focusedChild (package:flutter/src/widgets/focus_manager.dart:1256:12)
#3      FocusScopeNode._doRequestFocus (package:flutter/src/widgets/focus_manager.dart:1341:17)
#4      FocusScopeNode._doRequestFocus (package:flutter/src/widgets/focus_manager.dart:1357:18)
#5      FocusNode.unfocus (package:flutter/src/widgets/focus_manager.dart:901:15)
#6      FocusAttachment.detach (package:flutter/src/widgets/focus_manager.dart:197:15)
#7      _FocusState.dispose (package:flutter/src/widgets/focus_scope.dart:561:23)
#8      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5680:11)
#9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2067:13)
#10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6722:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6722:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2065:7)
#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2063:13)
#58     ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#59     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2076:25)
#60     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2755:15)
#61     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3165:7)
#62     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:987:19)
#63     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#64     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#65     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#66     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#67     _invoke (dart:ui/hooks.dart:312:13)
#68     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#69     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22621.2861], locale en-US)
    • Flutter version 3.16.0 on channel stable at C:\src\flutter\flutter_windows_3.10.4-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (8 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\developer\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio2\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components


[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @dulejo 
Can you try https://github.com/flutter/flutter/issues/119849#issuecomment-1460969657 and see if it helps in your case or not ?

**Comment by dulejo** [comment]
Thanks for reply!
I wrapped the app with a FocusScope as suggested in #119849 and problem still persists.

```dart

 return  FocusScope(
                          child: MaterialApp.router(
                            routerConfig: AppRouter.createRouter(context),
                            title: 'BloC Login Demo',
                            localizationsDelegates: AppLocalizations
                                .localizationsDelegates,
                            supportedLocales: localeList,
                            locale: localeState.locale,
                            theme: ThemeData(
                              colorScheme: ColorScheme.fromSeed(
                                  seedColor: Colors.orange),
                              useMaterial3: true,
                              bottomNavigationBarTheme: const BottomNavigationBarThemeData(
                                backgroundColor: Colors.orange,
                                selectedItemColor: Colors.redAccent,
                                unselectedItemColor: Colors.grey,
                              ),
                            ),
                          ),
                        );

```

output

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Focused child does not have the same idea of its enclosing scope as the scope does.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 1256 pos 12: '_focusedChildren.isEmpty || _focusedChildren.last.enclosingScope == this'

**Comment by darshankawar** [comment]
Thanks for the update. Using the original code sample, I was able to replicate the error reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.16.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.16.5 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (13 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.19.0-3.0.pre.50, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.19.0-3.0.pre.50 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3e5cad037c (68 minutes ago), 2024-01-10 22:42:23 -0500
    • Engine revision ade9f18fa0
    • Dart version 3.4.0 (build 3.4.0-16.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

Maybe it is related to framework ?

**Comment by chunhtai** [comment]
Can you try define and store the GoRouter outside of the widget in a static place?
