### ISSUE TITLE
[tool_crash] _TypeError: (#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49))

### ISSUE THREAD

**Issue by vvRevanth** [flutter/flutter#141450]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49))
```
#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49)
#1      CachedArtifact.update (package:flutter_tools/src/cache.dart:812:11)
#2      Cache.updateAll (package:flutter_tools/src/cache.dart:679:24)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1566:7)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22621.2861], locale en-IN)
    [32m•[39m Flutter version 3.13.1 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision e1e47221e8 (5 months ago), 2023-08-22 21:43:18 -0700
    [32m•[39m Engine revision b20183e040
    [32m•[39m Dart version 3.1.0
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    [32m•[39m Android SDK at C:\Users\KIIT\AppData\Local\Android\sdk
    [32m•[39m Platform android-TiramisuPrivacySandbox, build-tools 33.0.1
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.7.34024.191
    [31m✗[39m The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[32m[✓][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at C:\Users\KIIT\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.81.20231227

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2861]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.201
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.121

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: efbf63d9c66b9f6ec30e9ad4611189aa80003d31

**Comment by huycozy** [comment]
Hello @vvRevanth 
The error is thrown here:

https://github.com/flutter/flutter/blob/e1e47221e86272429674bec4f1bd36acc4fc7b77/packages/flutter_tools/lib/src/flutter_cache.dart#L151C29-L151C29

```dart
final Uri archiveUri = _toStorageUri(version!);
```

I see there are some similar issues: https://github.com/flutter/flutter/issues/112872, https://github.com/flutter/flutter/issues/90092. I think we should centralize on one issue, so I will leave my comment at #112872. 

Please follow up on it for updates. Closing this issue in favor of that one. Thanks!
