### ISSUE TITLE
segmentation fault on librem11

### ISSUE THREAD

**Issue by nohkumado** [flutter/flutter#141534]
### Steps to reproduce

hello,
i have a project i am developing on my desktop (and that runs fine), i copied it over to my tablet (pureos on Intel celerons), but when trying to run it,  i get 
```
flutter run -d linux
Resolving dependencies... 
  file_picker 5.5.0 (6.1.1 available)
  google_fonts 5.1.0 (6.1.0 available)
  intl 0.18.1 (0.19.0 available)
  js 0.6.7 (0.7.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.11.0 available)
  path 1.8.3 (1.9.0 available)
  permission_handler 10.4.5 (11.1.0 available)
  permission_handler_android 10.3.6 (12.0.1 available)
  permission_handler_apple 9.1.4 (9.2.0 available)
  permission_handler_platform_interface 3.12.0 (4.0.2 available)
  permission_handler_windows 0.1.3 (0.2.0 available)
  posix 5.0.0 (6.0.1 available)
  test_api 0.6.1 (0.7.0 available)
  web 0.3.0 (0.4.2 available)
Got dependencies!
16 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Linux in debug mode...

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x3f0d98005d18
version=3.2.4 (stable) (Thu Dec 21 19:13:53 2023 +0000) on "linux_x64"
pid=15538, thread=15554, isolate_group=main(0x55d1f8f646b0), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=7f0dbd7d8000, vm_instructions=55d1f7a8bc80
fp=7f0da3b7ca90, sp=7f0da3b7ca40, pc=55d1f7c307e1
  pc 0x000055d1f7c307e1 fp 0x00007f0da3b7ca90 dart::AbstractType::IsSubtypeOf+0x11
  pc 0x000055d1f7e5382f fp 0x00007f0da3b7cad0 dart::CompileType::ComputeRefinedType+0x1df
  pc 0x000055d1f7e5148c fp 0x00007f0da3b7cf40 dart::FlowGraphTypePropagator::VisitValue+0x9c
  pc 0x000055d1f7e510c7 fp 0x00007f0da3b7cf80 dart::FlowGraphTypePropagator::PropagateRecursive+0xc7
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7cfc0 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d000 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d040 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d080 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d0c0 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d100 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d140 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d180 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d1c0 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d200 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d240 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d280 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d2c0 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e511a3 fp 0x00007f0da3b7d300 dart::FlowGraphTypePropagator::PropagateRecursive+0x1a3
  pc 0x000055d1f7e509b4 fp 0x00007f0da3b7d770 dart::FlowGraphTypePropagator::Propagate+0x24
  pc 0x000055d1f7e5097a fp 0x00007f0da3b7d890 dart::FlowGraphTypePropagator::Propagate+0x4a
  pc 0x000055d1f7e62090 fp 0x00007f0da3b7d8a0 dart::CompilerPass_TypePropagation::DoBody+0x10
  pc 0x000055d1f7e61840 fp 0x00007f0da3b7d960 dart::CompilerPass::Run+0x120
  pc 0x000055d1f7e61e1c fp 0x00007f0da3b7d980 dart::CompilerPass::RunPipeline+0x18c
  pc 0x000055d1f7d18163 fp 0x00007f0da3b7e070 dart::CompileParsedFunctionHelper::Compile+0x693
  pc 0x000055d1f7d18a50 fp 0x00007f0da3b7e770 dart::CompileFunctionHelper+0x420
  pc 0x000055d1f7d19017 fp 0x00007f0da3b7e810 dart::Compiler::CompileOptimizedFunction+0x107
  pc 0x000055d1f7d196c1 fp 0x00007f0da3b7ed60 dart::BackgroundCompiler::Run+0xe1
  pc 0x000055d1f7d074ab fp 0x00007f0da3b7ede0 dart::ThreadPool::WorkerLoop+0x14b
  pc 0x000055d1f7d07748 fp 0x00007f0da3b7ee10 dart::ThreadPool::Worker::Main+0x78
  pc 0x000055d1f7c90d36 fp 0x00007f0da3b7eed0 dart::ThreadStart+0xd6
-- End of DumpStackTrace
=== Crash occurred when compiling package:front_end/src/fasta/source/outline_builder.dart_OutlineBuilder_endFormalParameter in optimizing JIT mode in
TypePropagation pass
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```

instead of the expected ui.....

### Expected results

expecting the build up of an ui

### Actual results

crash

### Code sample

<details open><summary>Code sample</summary>

so i tried to see what happens with the default project:
 ```
flutter create testit
Creating project testit...
Resolving dependencies in testit... (1.1s)
Got dependencies in testit.
Wrote 129 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd testit
  $ flutter run

Your application code is in testit/lib/main.dart.

bboett@pureos:~/projects$ cd testit/
bboett@pureos:~/projects/testit$ flutter run
Launching lib/main.dart on Linux in debug mode...
Unhandled exception:
Crash when compiling package:flutter/src/material/icons.dart:
type 'FunctionTypeBuilderImpl' is not a subtype of type 'String?' in type cast

#0      TypeParameterScopeBuilder.resolveNamedTypes (package:front_end/src/fasta/source/source_library_builder.dart:5878:32)
#1      SourceLibraryBuilder._addClass (package:front_end/src/fasta/source/source_library_builder.dart:1993:13)
#2      SourceLibraryBuilder.addClass (package:front_end/src/fasta/source/source_library_builder.dart:1902:5)
#3      OutlineBuilder.endClassDeclaration (package:front_end/src/fasta/source/outline_builder.dart:1333:22)
#4      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2665:14)
#5      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2621:14)
#6      Parser._handleModifiersForClassDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:819:12)
#7      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:658:14)
#8      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:603:14)
#9      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:411:15)
#10     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:1195:10)
<asynchronous suspension>
#11     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:1016:7)
<asynchronous suspension>
#12     KernelTarget.computeNeededPrecompilations.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:329:7)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#14     KernelTarget.computeNeededPrecompilations (package:front_end/src/fasta/kernel/kernel_target.dart:327:12)
<asynchronous suspension>
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:379:13)
<asynchronous suspension>
#16     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139:3)
<asynchronous suspension>
#17     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
<asynchronous suspension>
#18     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:610:11)
<asynchronous suspension>
#19     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1323:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Building Linux application...                                          ⠴bboett@pureos:~/projects/testit$ 
```

not what i did expect either....
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[  +23 ms] executing: uname -m
[  +12 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +76 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +96 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +98 ms] Skipping pub get: version match.
[ +285 ms] Generating /home/bboett/projects/testit/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +168 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +6 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/bboett/projects/testit/.dart_tool/package_config_subset}
[  +90 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/bboett/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/bboett/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /home/bboett/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/4a585b79294e830fa89c24924d58a27cc8fbf406/ --output-dill /tmp/flutter_tools.BGVCWO/flutter_tool.RNCGOB/app.dill --packages /home/bboett/projects/testit/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/92154e35268c86b762be48909da71bff.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +30 ms] Building Linux application...
[   +8 ms] <- compile package:testit/main.dart
[   +3 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/bboett/projects/testit/linux
[  +53 ms] -- Configuring done
[        ] -- Generating done
[   +8 ms] -- Build files have been written to: /home/bboett/projects/testit/build/linux/x64/debug
[   +9 ms] executing: ninja -C build/linux/x64/debug install
[  +10 ms] ninja: Entering directory `build/linux/x64/debug'
[ +333 ms] [1/6] Generating /home/bboett/projects/testit/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +7 ms] FAILED: /home/bboett/projects/testit/linux/flutter/ephemeral/libflutter_linux_gtk.so /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_engine.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_method_call.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_method_response.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_value.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/fl_view.h /home/bboett/projects/testit/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_ /home/bboett/projects/testit/build/linux/x64/debug/flutter/_phony_ 
[   +1 ms] cd /home/bboett/projects/testit/build/linux/x64/debug/flutter && /usr/bin/cmake -E env FLUTTER_ROOT=/home/bboett/flutter PROJECT_DIR=/home/bboett/projects/testit DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC80YTU4NWI3OTI5NGU4MzBmYTg5YzI0OTI0ZDU4YTI3Y2M4ZmJmNDA2Lw== DART_OBFUSCATION=false TRACK_WIDGET_CREATION=true TREE_SHAKE_ICONS=false PACKAGE_CONFIG=/home/bboett/projects/testit/.dart_tool/package_config.json FLUTTER_TARGET=/home/bboett/projects/testit/lib/main.dart /home/bboett/flutter/packages/flutter_tools/bin/tool_backend.sh linux-x64 Debug
[        ] ===== CRASH =====
[        ] si_signo=Segmentation fault(11), si_code=1, si_addr=0x5914bc242068
[        ] version=3.2.4 (stable) (Thu Dec 21 19:13:53 2023 +0000) on "linux_x64"
[        ] pid=17274, thread=17280, isolate_group=kernel-service(0x7f14c0011ed0), isolate=kernel-service(0x7f14c0019650)
[        ] os=linux, arch=x64, comp=no, sim=no
[        ] isolate_instructions=7f14bf5b4000, vm_instructions=558c859ebc80
[        ] fp=7f14bccfd6c0, sp=7f14bccfd668, pc=7f14bf753304
[        ]   pc 0x00007f14bf753304 fp 0x00007f14bccfd6c0 Unknown symbol
[        ]   pc 0x00007f14bfdc4ccd fp 0x00007f14bccfd728 Unknown symbol
[        ]   pc 0x00007f14bfdc7103 fp 0x00007f14bccfd810 Unknown symbol
[        ]   pc 0x00007f14bfdc8384 fp 0x00007f14bccfd848 Unknown symbol
[        ]   pc 0x00007f14bfdc8b3f fp 0x00007f14bccfd930 Unknown symbol
[        ]   pc 0x00007f14bf7c5f51 fp 0x00007f14bccfd968 Unknown symbol
[        ]   pc 0x00007f14bf7c66dc fp 0x00007f14bccfd9b0 Unknown symbol
[        ]   pc 0x00007f14bfbf788b fp 0x00007f14bccfd9e8 Unknown symbol
[        ]   pc 0x00007f14bfbf7bf2 fp 0x00007f14bccfda68 Unknown symbol
[        ]   pc 0x00007f14bfbf7ff6 fp 0x00007f14bccfdaf8 Unknown symbol
[        ]   pc 0x00007f14bfd0eb29 fp 0x00007f14bccfdb78 Unknown symbol
[        ]   pc 0x00007f14bfd1138b fp 0x00007f14bccfdbf8 Unknown symbol
[        ]   pc 0x00007f14bfd119c1 fp 0x00007f14bccfdc88 Unknown symbol
[        ]   pc 0x00007f14bf5d3a1f fp 0x00007f14bccfdd28 Unknown symbol
[        ]   pc 0x00007f14bfcb0410 fp 0x00007f14bccfdda8 Unknown symbol
[        ]   pc 0x00007f14bfd1421d fp 0x00007f14bccfdea0 Unknown symbol
[        ]   pc 0x00007f14bfd81639 fp 0x00007f14bccfdf88 Unknown symbol
[        ]   pc 0x00007f14bff93cfc fp 0x00007f14bccfdfd8 Unknown symbol
[        ]   pc 0x00007f14bfd857a4 fp 0x00007f14bccfe058 Unknown symbol
[        ]   pc 0x00007f14bfd85ab6 fp 0x00007f14bccfe0c0 Unknown symbol
[        ]   pc 0x00007f14bfd87b52 fp 0x00007f14bccfe158 Unknown symbol
[        ]   pc 0x00007f14bff9344f fp 0x00007f14bccfe1a8 Unknown symbol
[        ]   pc 0x00007f14bfd84b9a fp 0x00007f14bccfe220 Unknown symbol
[        ]   pc 0x00007f14bfd84d73 fp 0x00007f14bccfe280 Unknown symbol
[        ]   pc 0x00007f14bf69424f fp 0x00007f14bccfe310 Unknown symbol
[        ]   pc 0x00007f14bfd8437d fp 0x00007f14bccfe360 Unknown symbol
[        ]   pc 0x00007f14bfd85cad fp 0x00007f14bccfe3a8 Unknown symbol
[        ]   pc 0x00007f14bfd86015 fp 0x00007f14bccfe3e8 Unknown symbol
[        ]   pc 0x00007f14bfd86216 fp 0x00007f14bccfe410 Unknown symbol
[        ]   pc 0x00007f14bf690d09 fp 0x00007f14bccfe450 Unknown symbol
[        ]   pc 0x00007f14bf692480 fp 0x00007f14bccfe4d0 Unknown symbol
[        ]   pc 0x00007f14bf68f3b3 fp 0x00007f14bccfe508 Unknown symbol
[        ]   pc 0x00007f14bf68f479 fp 0x00007f14bccfe538 Unknown symbol
[        ]   pc 0x00007f14bf6916a6 fp 0x00007f14bccfe5a0 Unknown symbol
[        ]   pc 0x00007f14bff94edc fp 0x00007f14bccfe5f8 Unknown symbol
[        ]   pc 0x00007f14d0502e46 fp 0x00007f14bccfe670 Unknown symbol
[        ]   pc 0x0000558c85b29bd3 fp 0x00007f14bccfe6d0 dart::DartEntry::InvokeFunction+0x163
[        ]   pc 0x0000558c85b2b616 fp 0x00007f14bccfe710 dart::DartLibraryCalls::HandleMessage+0x126
[        ]   pc 0x0000558c85b47c5f fp 0x00007f14bccfeca0 dart::IsolateMessageHandler::HandleMessage+0x2bf
[        ]   pc 0x0000558c85b69e87 fp 0x00007f14bccfed10 dart::MessageHandler::HandleMessages+0x127
[        ]   pc 0x0000558c85b6a478 fp 0x00007f14bccfed60 dart::MessageHandler::TaskCallback+0x1e8
[        ]   pc 0x0000558c85c674ab fp 0x00007f14bccfede0 dart::ThreadPool::WorkerLoop+0x14b
[        ]   pc 0x0000558c85c67748 fp 0x00007f14bccfee10 dart::ThreadPool::Worker::Main+0x78
[        ]   pc 0x0000558c85bf0d36 fp 0x00007f14bccfeed0 dart::ThreadStart+0xd6
[        ] -- End of DumpStackTrace
[        ] Subprocess aborted
[        ] ninja: build stopped: subcommand failed.
[  +19 ms] Building Linux application... (completed in 447ms)
[   +1 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
[   +3 ms] "flutter run" took 2,337ms.
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on PureOS 11 (Crimson) 6.1.0-15-amd64, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 2 categories.

```

</details>

**Comment by nohkumado** [comment]
Sure,
As said it's a quad Celeron tablet, what else can I provide?
Do you want a full lsproc? Something else?

Ciao

Bruno Böttcher
--
35 rue de la république, FR-6720 Schwindratzheim
email: ***@***.***, ***@***.***
Fon:+33 3 88 89 91, Mob:+33 6 76 55 82 68
-------------------------------------------------
Dev: Java/Perl/PHP OS:GNU/LINUX, Android

huycozy ***@***.***> schrieb am Mo., 15. Jan. 2024, 11:28:

**Comment by huycozy** [comment]
Yes. Some information like device model, CPU, RAM, Storage.

**Comment by nohkumado** [comment]
I think easiest is the website of the producer?
https://puri.sm/products/librem-11/
But I can also post a /proc/cpuinfo?
Ciao

Bruno Böttcher
--
35 rue de la république, FR-6720 Schwindratzheim
email: ***@***.***, ***@***.***
Fon:+33 3 88 89 91, Mob:+33 6 76 55 82 68
-------------------------------------------------
Dev: Java/Perl/PHP OS:GNU/LINUX, Android

huycozy ***@***.***> schrieb am Di., 16. Jan. 2024, 04:41:

**Comment by mraleph** [comment]
@nohkumado could you run something like memtest on your tablet? 

I really think this is just a hardware issue and has nothing to do with Dart or Flutter to that matter.

**Comment by nohkumado** [comment]
well running memtest wasn't easy :D  and its still running, and indeed its spitting out errors... 

so, sorry for barking up the wrong tree.....

**Comment by mraleph** [comment]
@nohkumado Thanks! No worries. I have gotten pretty adept in divining hardware failures based on Dart VM crashes :)
