### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by MhmdAlkashif** [flutter/flutter#141525]
### Steps to reproduce

when I run the flutter app on IOS after initializing the bloc providers it returns the error on the MaterialApp

### Expected results

It should continue the app and open it normally

### Actual results

it return an error more than 100 times on 
The relevant error-causing widget was:

'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
The relevant error-causing widget was:
    MaterialApp MaterialApp:file:///Users/qamacbook/Desktop/abwaab-mobile-v3/lib/app.dart:41:20

When the exception was thrown, this was the stack:
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:5191:16)
framework.dart:5191
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:5194:8)
framework.dart:5194
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453:5)
framework.dart:5453
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
framework.dart:5447
...     Normal element mounting (366 frames)
#371    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (15 frames)
#386    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
inherited_provider.dart:411
...     Normal element mounting (7 frames)
#393    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#400    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#407    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
inherited_provider.dart:411
...     Normal element mounting (7 frames)
#414    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#421    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#428    _NestedHookElement.mount (package:nested/nested.dart:187:11)
nested.dart:187
...     Normal element mounting (7 frames)
#435    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
inherited_provider.dart:411
...     Normal element mounting (7 frames)
#442    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#449    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#456    _NestedHookElement.mount (package:nested/nested.dart:187:11)
nested.dart:187
...     Normal element mounting (7 frames)
#463    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
inherited_provider.dart:411
...     Normal element mounting (7 frames)
#470    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#477    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#484    _NestedHookElement.mount (package:nested/nested.dart:187:11)
nested.dart:187
...     Normal element mounting (7 frames)
#491    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
inherited_provider.dart:411
...     Normal element mounting (7 frames)
#498    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#505    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
nested.dart:222
...     Normal element mounting (7 frames)
#512    _NestedHookElement.mount (package:nested/nested.dart:187:11)
nested.dart:187
...     Normal element mounting (7 frames)
#519    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
inherited_provider.dart:411
════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════
...     Normal element mounting (7 frames)```

</details>


### Flutter Doctor output
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.1.2 23B92 darwin-x64, locale en-JO)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@MhmdAlkashif 
In order to properly address the issue, please provide us complete runnable but reproducible code sample without any third party package implementation and check if without third party implementation, you get same error or not.

**Comment by longphgcs17521** [comment]
following this issue

**Comment by longphgcs17521** [comment]
Dear @darshankawar 
This issue just only happens when I run debug for ios platform
The cause is MaterialApp.router in my case (.../main_application.dart:503:44)

![Screenshot 2024-01-24 at 15 02 58](https://github.com/flutter/flutter/assets/46739316/bb6ee672-2a27-41b3-95c0-8f687018aa6b)

**Comment by MhmdAlkashif** [comment]
@longphgcs17521 how did you fix the issue

**Comment by MhmdAlkashif** [comment]
@darshankawar its a big structure, can't provide you a runnable code cause it is company based code

**Comment by longphgcs17521** [comment]
@MhmdAlkashif  
I have not fixed yet, I got the issue as your case. Iam following this post to find the solution

**Comment by darshankawar** [comment]
@MhmdAlkashif 
That's why we need a runnable but reproducible code sample without third party implementation so as to know which area of the framework could be causing the error. Most likely it occurs due to conflict between various packages you are using and looking at the logs, there are entries pointing to `provider` third party package. Without reproducible code, we can't make the issue actionable. You can search for similar issues o stackoverflow to see if they help to solve the issue.
