### ISSUE TITLE
Crash: Error  dd.q$e in <init>

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#141557]
### Steps to reproduce

no idea, found in sentry

### Expected results

no crash

### Actual results

![grafik](https://github.com/flutter/flutter/assets/16635729/07adfcab-37ae-4861-b4b0-f85766ab5bcb)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.3930], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @escamoteur
Does this crash only occur on Android 13 and that device? 

The stack trace doesn't seem to have much information to investigate (it's obfuscated), could you try running your project in `release` mode to see if it can be reproduced locally?

Please also provide the stack trace in text format instead of a screenshot. Thanks!

**Comment by escamoteur** [comment]
```console
PlatformException: PlatformException(error, invalid composing start: 2, null, java.lang.IndexOutOfBoundsException: invalid composing start: 2
	at dd.q$e.<init>(TextInputChannel.java:15)
	at dd.q$e.a(TextInputChannel.java:6)
	at dd.q$a.onMethodCall(TextInputChannel.java:43)
	at ed.k$a.a(MethodChannel.java:2)
	at sc.c.l(DartMessenger.java:2)
	at sc.c.m(DartMessenger.java:3)
	at sc.c.h(Unknown Source:0)
	at sc.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
)
  File "message_codecs.dart", line 180, in JSONMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 322, in MethodChannel._invokeMethod

IndexOutOfBoundsException: invalid composing start: 2
    at dd.q$e.<init>(TextInputChannel.java:15)
    at dd.q$e.a(TextInputChannel.java:6)
    at dd.q$a.onMethodCall(TextInputChannel.java:43)
    at ed.k$a.a(MethodChannel.java:2)
    at sc.c.l(DartMessenger.java:2)
    at sc.c.m(DartMessenger.java:3)
    at sc.c.h(Unknown Source:0)
    at sc.b.run(Unknown Source:12)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8757)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by escamoteur** [comment]
![grafik](https://github.com/flutter/flutter/assets/16635729/9ec2a861-785c-4092-affb-a7237bb31dd6)

Unfortunately I can't reproduce in debug environment

**Comment by huycozy** [comment]
Thanks for the update. Looking at the stack trace, this seems to be similar to https://github.com/flutter/flutter/issues/100319 which has reproduction steps there (`typing something while holding selection endpoint`). Keep this for other's input.

**Comment by Correct-Syntax** [comment]
Also getting the same error in production with Android 8.1, 9, 10, and 13 on Flutter 3.19.3.
```
PlatformException(error, invalid selection start: 3, null, java.lang.IndexOutOfBoundsException: invalid selection start: 3
	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(SourceFile:104)
	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(SourceFile:34)
	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(SourceFile:420)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(SourceFile:18)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(SourceFile:19)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(SourceFile:42)
	at io.flutter.embedding.engine.dart.DartMessenger.a(SourceFile:1)
	at io.flutter.embedding.engine.dart.a.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
)
```

**Comment by escamoteur** [comment]
Still happening in Flutter 3.24. on Android 12,13 and 14

**Comment by Mastersam07** [comment]
Any idea how to resolve on flutter 3.24.3?

`PlatformException(error, invalid selection start: 2, null, java.lang.IndexOutOfBoundsException: invalid selection start: 2 at sp.s$e.<init>(TextInputChannel.java:13) at sp.s$e.a(TextInputChannel.java:6) at sp.s$a.onMethodCall(TextInputChannel.java:43) at tp.k$a.a(MethodChannel.java:2) at hp.c.l(DartMessenger.java:2) at hp.c.m(DartMessenger.java:4) at hp.c.i(Unknown Source:0) at hp.b.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop(Looper.java:313) at android.app.ActivityThread.main(ActivityThread.java:8751) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) )`

**Comment by hasanmhallak** [comment]
same, and no idea how to reproduce it.

**Comment by hasanmhallak** [comment]
any idea how to fix this or at least reproduce it? it keeps popping in our crash analytics.

**Comment by akash-dhedhi** [comment]
We’re also encountering this crash in our app, and it’s being reported in Crashlytics across multiple devices. Is there any update or recommended workaround to resolve this issue? Any guidance on how to handle this would be appreciated. 

Flutter 3.29.2 
Tools • Dart 3.7.2 • DevTools 2.42.3


<img width="1004" alt="Image" src="https://github.com/user-attachments/assets/0c9b1420-ae01-454a-a380-f705c4aeff8b" />
<img width="1076" alt="Image" src="https://github.com/user-attachments/assets/314bbab8-f148-45b7-8307-fdbb9cee7f31" />

**Comment by hasanmhallak** [comment]
any update on this?

**Comment by hasanmhallak** [comment]
still happens on stable channel v3.32.1
