### ISSUE TITLE
tool crashes when using `--empty` with `flutter create --template=plugin_ffi`

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#141592]
## Command
```
flutter create --template=plugin_ffi --empty --platforms=windows ffi_test
```

## Steps to Reproduce
1. Run `flutter create --template=plugin_ffi --empty --platforms=windows ffi_test` 

This doesn't crash when I remove `--empty`.

## Logs
FileSystemException: Directory listing failed, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:228:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      CreateCommand._removeTestDir (package:flutter_tools/src/commands/create.dart:767:50)
#5      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:453:29)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
```
[33m[!][39m Flutter (Channel master, 3.19.0-5.0.pre.4, on Microsoft Windows [Version
    10.0.22621.3007], locale en-US)
    [32m•[39m Flutter version 3.19.0-5.0.pre.4 on channel master at
      C:\Users\Jozz\Documents\GitHub\flutter
    [33m![39m Upstream repository https://github.com/andrewkolos/flutter.git is not a
      standard remote.
      Set environment variable "FLUTTER_GIT_URL" to
      https://github.com/andrewkolos/flutter.git to dismiss this error.
    [32m•[39m Framework revision f5fb61b953 (5 days ago), 2024-01-11 10:46:22 -0500
    [32m•[39m Engine revision ecdaed76f2
    [32m•[39m Dart version 3.4.0 (build 3.4.0-16.0.dev)
    [32m•[39m DevTools version 2.31.0
    [32m•[39m If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\Jozz\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.7+0-b2043.56-10550314)
    [33m![39m Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.0)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.7.34003.232
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.7+0-b2043.56-10550314)

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at C:\Users\Jozz\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.81.20231227

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.22621.3007]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome
      120.0.6099.217
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge
      120.0.2210.133
    [33m![39m Device R9HR701BH0H is not authorized.
      You might need to check your device for an authorization dialog.

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by dcharkes** [comment]
`--empty` was added in:

* https://github.com/flutter/flutter/pull/113873

```dart
      help: 'Specifies creating using an application template with a main.dart that is minimal, '
        'including no comments, as a starting point for a new application. Implies "--template=app".',
```

It should not crash on other templates, but give an error message that it's not supported for other templates.

@gspencergoog You added support for `--empty`, could you please take a look?
