### ISSUE TITLE
[tool_crash] RangeError: RangeError: Value not in range: 354

### ISSUE THREAD

**Issue by Microcrab** [flutter/flutter#141544]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=00008101-001831223CB8001E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. Create a new flutter project
2. Run main.dart
3. No more information can be provided at this time, but the problem persists

## Logs
RangeError: RangeError: Value not in range: 354
```
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:5441:5)
#1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1921:5)
#2      new Uint8List.view (dart:typed_data:883:19)
#3      decodeMDnsResponse.readResourceRecord (package:multicast_dns/src/packet.dart:343:23)
#4      decodeMDnsResponse (package:multicast_dns/src/packet.dart:372:38)
#5      MDnsClient._handleIncoming (package:multicast_dns/multicast_dns.dart:239:46)
#6      MDnsClient.start.<anonymous closure> (package:multicast_dns/multicast_dns.dart:160:47)
#7      _rootRunUnary (dart:async/zone.dart:1415:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#13     _StreamController._add (dart:async/stream_controller.dart:658:7)
#14     _StreamController.add (dart:async/stream_controller.dart:606:5)
#15     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2535:33)
#16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.16.5 on channel stable at /Users/yq05871/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (4 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yq05871/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/yq05871/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/XCode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (1 available)
    • 尛螃蟹的 iPhone 12 Pro Max (mobile) • 00008101-001831223CB8001E • ios • iOS 17.2.1 21C66
    ! Error: 尛螃蟹的Apple Watch has not finished loading development services. Please select a different device, or wait for the device to load development services and try again. (code 8)
    ! Error: Browsing on the local area network for 消费者体验开发部 iPhone 12. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78666c8dc57e9f7548ca9f8dd0740fbf0c658dc9

**Comment by Microcrab** [comment]
After comparative testing, it was found that this problem will occur on iPhones running iOS 17, but not on iPhones running earlier than iOS 17.
