### ISSUE TITLE
RawKeyboardListener -> Tooltip -> TextField，Exception : Tried to make a child into a parent of itself.

### ISSUE THREAD

**Issue by bigedev** [flutter/flutter#141596]
### Steps to reproduce

Use RawKeyboardListener to listen the key press event in TextField.

RawKeyboardListener -> Tooltip -> TextField

### Expected results

Detect the Escape key is pressed.

### Actual results

The following assertion was thrown building _ActionsScope:
Tried to make a child into a parent of itself.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 978 pos 12: 'child != this'

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final FocusNode _searchFocusNode = FocusNode();
  final TextEditingController _searchContoller = TextEditingController();
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: RawKeyboardListener(
                focusNode: _searchFocusNode,
                onKey: (RawKeyEvent event) {
                  if (event.runtimeType == RawKeyDownEvent) {
                    if (event.logicalKey == LogicalKeyboardKey.enter) {
                      // do something
                    }
                    if (event.logicalKey == LogicalKeyboardKey.escape) {
                      Navigator.of(context).pop();
                    }
                  }
                },
                child: Tooltip(
                  message: 'Type in search text...',
                  child: TextField(
                    autofocus: true,
                    focusNode: _searchFocusNode,
                    controller: _searchContoller,
                    decoration: const InputDecoration(
                      hintText: 'Type in search text...',
                      filled: true,
                      fillColor: Colors.white,
                    ),
                  ),
                ),
              ),
            ),
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/128558433/be5596a5-9a9d-400d-b943-4755f3f99de6)

</details>

### Logs

<details open><summary>Logs</summary>

```console
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#197    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#198    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
framework.dart:5800
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#201    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#202    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
framework.dart:5800
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#205    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#206    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
framework.dart:5800
#207    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#209    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
framework.dart:5634
#210    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#211    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
framework.dart:5657
#212    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#214    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#215    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
framework.dart:5800
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#218    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
framework.dart:5634
#219    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#220    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
framework.dart:5657
#221    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
framework.dart:3815
#222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
framework.dart:5496
#223    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
framework.dart:5634
#224    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#225    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
framework.dart:2895
#226    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
binding.dart:984
#227    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
binding.dart:457
#228    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
binding.dart:1325
#229    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
binding.dart:1255
#230    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:978:7)
binding.dart:978
#234    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
isolate_patch.dart:184
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
[✓] VS Code (version 1.85.1)
[✓] Proxy Configuration
⣻^C%                                                                                                      
eltoro@localhost dart_sm % flutter doctor -v
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.16.7 on channel stable at /Users/eltoro/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (5 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/eltoro/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version null

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hello @bigedev.
I can see this issue on my end as well and it seems to be caused by Focus node being used by more than one widget at a time.
This is similar/related to https://github.com/flutter/flutter/issues/48076.
Per this https://github.com/flutter/flutter/issues/48076#issuecomment-571242607, it is WAI.
Kindly go through these to confirm this is similar to yours and for possible workarounds.
