### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.nio.Buffer java.nio.ByteBuffer.rewind()' on a null object reference

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#141662]
### Steps to reproduce

I just got this exception multiple times while debugging some code that works with text input fields in Flutter (I can't share the code, unfortunately). I haven't seen this before, and I'm not able to reproduce this.

```
E/DartMessenger(14566): Uncaught exception in binary message reply handler
E/DartMessenger(14566): java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.Buffer java.nio.ByteBuffer.rewind()' on a null object reference
E/DartMessenger(14566): 	at io.flutter.embedding.android.KeyEmbedderResponder.lambda$sendKeyEvent$2(KeyEmbedderResponder.java:401)
E/DartMessenger(14566): 	at io.flutter.embedding.android.KeyEmbedderResponder$$ExternalSyntheticLambda0.reply(Unknown Source:2)
E/DartMessenger(14566): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:376)
E/DartMessenger(14566): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:1071)
E/DartMessenger(14566): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(14566): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/DartMessenger(14566): 	at android.os.Looper.loopOnce(Looper.java:161)
E/DartMessenger(14566): 	at android.os.Looper.loop(Looper.java:288)
E/DartMessenger(14566): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/DartMessenger(14566): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(14566): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/DartMessenger(14566): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)```
```

### Expected results

No exception

### Actual results

Exception

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 3.19.0-0.1.pre, on Fedora Linux 39 (Workstation Edition) 6.6.9-200.fc39.x86_64, locale en_US.utf8)
    • Flutter version 3.19.0-0.1.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a9a60d044 (6 days ago), 2024-01-10 13:38:09 -0800
    • Engine revision bbebee1465
    • Dart version 3.3.0 (build 3.3.0-279.0.dev)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6 (Fedora 17.0.6-1.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.81.20231227

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.79.20231130

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.6.9-200.fc39.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by bleroux** [comment]
Thanks for reporting this.
I'm able to reproduce it when using an Android TV emulator and pressing the 'Select' button (the round one in the fake remote control provided by the emulator).

To get the error, one should send key events during a hot restart (at this tilme the engine is ready to send key events but the framework has not started and can not handle the event, the engine will receive a null message as a response and should handle it (this is not the case currently).
