### ISSUE TITLE
firebase_auth not working in Android release mode.

### ISSUE THREAD

**Issue by theankurkedia** [flutter/flutter#14163]
## Steps to Reproduce

The apps runs fine without error in debug mode but when I run it in release mode on Android, it gives this error. 

## Logs
```
flutter run --release
E/flutter (29019): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (29019): PlatformException(status, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)
E/flutter (29019): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514)
E/flutter (29019): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter (29019): <asynchronous suspension>
E/flutter (29019): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:156)
E/flutter (29019): <asynchronous suspension>
E/flutter (29019): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:196)
E/flutter (29019): #4      _RootZone.run (dart:async/zone.dart:1376)
E/flutter (29019): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151)
E/flutter (29019): #6      _Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603)
E/flutter (29019): #7      _Future._propagateToListeners (dart:async/future_impl.dart:659)
E/flutter (29019): #8      _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
E/flutter (29019): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (29019): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
E/flutter (29019): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (29019): PlatformException(status, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)
E/flutter (29019): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514)
E/flutter (29019): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter (29019): <asynchronous suspension>
E/flutter (29019): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:156)
E/flutter (29019): <asynchronous suspension>
E/flutter (29019): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:196)
E/flutter (29019): #4      _RootZone.run (dart:async/zone.dart:1376)
E/flutter (29019): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151)
E/flutter (29019): #6      _Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603)
E/flutter (29019): #7      _Future._propagateToListeners (dart:async/future_impl.dart:659)
E/flutter (29019): #8      _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
E/flutter (29019): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (29019): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
I/FlutterActivityDelegate(29019): onResume setting current activity to this
```
```
flutter analyze
No issues found!
Ran in 7.2s
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G1114, locale en-IN, channel alpha)
    • Flutter at /Users/ankurkedia/flutter
    • Framework revision 8f65fec5f5 (5 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/ankurkedia/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/ankurkedia/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.1
    ✗ ios-deploy out of date (1.9.2 is required). To upgrade:
        brew upgrade ios-deploy
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3757.55

[✓] Connected devices
    • Redmi Note 3 • 22bb2c37 • android-arm • Android 5.1.1 (API 22)
```

**Comment by cyanglaz** [comment]
Could you try to update to the latest firebase_auth plugin and see if the issue still persists for you? @theankurkedia

**Comment by kroikie** [comment]
@theankurkedia

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/911. Any further collaboration will be done there.
