### ISSUE TITLE
App gets stuck on the loading screen - BUT only if built as an app bundle and distributed via PlayStore

### ISSUE THREAD

**Issue by chrisDK1977** [flutter/flutter#141605]
### Steps to reproduce

As we have a very large project and no idea where the problem could be, we can only offer the description what we are doing and the flutter doctor output and logcat below.

Problem:

What is not working:
We develop an app and it is working on the simulator and on physical decices when connected to the ide (IDEA Ultimate and Android Studio), we can build an apk in release mode and the app is working as expected on simulator and real devices (Pixel 6a, Huawei P30 Pro, Samsung Galaxy 21 FE).

What is NOT working:
We build an appbundle, upload it to the PlayStore Console and install the release App via PlayStore or download the "Signiertes, universelles APK" ("Signed, universal APK") and install it on an device. Then the app does not go beyond the splash screen.

### Expected results

We expect the app to behave in the same way when building a local APK as the APK generated from an appbundle via the PlayStore Console. 

### Actual results

App is working when build on our machines and crashing when it is built via the PlayStore Console.

### Code sample

Not possible as described above.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

LOGCAT:

2024-01-16 15:10:29.123  1579-2739  ActivityTaskManager     system_server                        I  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.myCompanyName.myAppName/.MainActivity bnds=[792,313][1044,628]} with LAUNCH_SINGLE_TOP from uid 10207 (BAL_ALLOW_ALLOWLISTED_COMPONENT) result code=0
2024-01-16 15:10:29.124  1967-1991  WindowManagerShell      com.android.systemui                 V  Transition requested: android.os.BinderProxy@90769d9 TransitionRequestInfo { type = 1, triggerTask = TaskInfo{userId=0 taskId=218 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.myCompanyName.myAppName/.MainActivity } baseActivity=ComponentInfo{com.myCompanyName.myAppName/com.myCompanyName.myAppName.MainActivity} topActivity=ComponentInfo{com.myCompanyName.myAppName/com.myCompanyName.myAppName.MainActivity} origActivity=null realActivity=ComponentInfo{com.myCompanyName.myAppName/com.myCompanyName.myAppName.MainActivity} numActivities=1 lastActiveTime=142906428 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@13e5f9e} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 132 - 0, 0) topActivityInfo=ActivityInfo{ae50a7f com.myCompanyName.myAppName.MainActivity} launchCookies=[android.os.BinderProxy@9f25a4c] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false isTopActivityTransparent=false locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden}, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@67bca95, appThread = android.app.IApplicationThread$Stub$Proxy@eacd7aa, debugName = QuickstepLaunch }, displayChange = null, flags = 0 }
2024-01-16 15:10:29.124  1967-1991  WindowManagerShell      com.android.systemui                 V  RemoteTransition directly requested for android.os.BinderProxy@90769d9: RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@67bca95, appThread = android.app.IApplicationThread$Stub$Proxy@eacd7aa, debugName = QuickstepLaunch }
2024-01-16 15:10:29.124  1579-4462  Compatibil...geReporter system_server                        D  Compat change id reported: 168419799; UID 10417; state: DISABLED
2024-01-16 15:10:29.124  1579-4462  Compatibil...geReporter system_server                        D  Compat change id reported: 273564678; UID 10417; state: DISABLED
2024-01-16 15:10:29.124 28146-28146 StatsLog                com...le.android.apps.nexuslauncher  D  LAUNCHER_APP_LAUNCH_TAP
2024-01-16 15:10:29.125 28146-28146 StatsLog                com...le.android.apps.nexuslauncher  D  LAUNCHER_HOTSEAT_RANKED
2024-01-16 15:10:29.125 28146-28172 QuickstepModelDelegate  com...le.android.apps.nexuslauncher  D  notifyAppTargetEvent action=1 launchLocation=predictions
2024-01-16 15:10:29.128  1579-4465  ActivityManager         system_server                        D  quick sync unfreeze 15291 for 1
2024-01-16 15:10:29.130  1579-1686  ActivityManager         system_server                        D  sync unfroze 15291 com.myCompanyName.myAppName for 1
2024-01-16 15:10:29.136  1579-4465  CoreBackPreview         system_server                        D  Window{d673387 u0 Splash Screen com.myCompanyName.myAppName}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@3f98123, mPriority=0, mIsAnimationCallback=false}
2024-01-16 15:10:29.139   625-29560 gralloc4                and...graphics.allocator-V1-service  W  Unable to set buffer name VRI[community2]#692(BLAST Consumer)692: File name too long
2024-01-16 15:10:29.140   625-29560 gralloc4                and...graphics.allocator-V1-service  W  Unable to set buffer name VRI[community2]#692(BLAST Consumer)692: File name too long
2024-01-16 15:10:29.142   625-29560 gralloc4                and...graphics.allocator-V1-service  W  Unable to set buffer name VRI[community2]#692(BLAST Consumer)692: File name too long
2024-01-16 15:10:29.144   623-623   BpBinder                surfaceflinger                       I  onLastStrongRef automatically unlinking death recipients: 
2024-01-16 15:10:29.145  1579-1683  WindowManager           system_server                        V  Sent Transition #673 createdAt=01-16 15:10:29.107 via request=TransitionRequestInfo { type = 1, triggerTask = TaskInfo{userId=0 taskId=218 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.myCompanyName.myAppName/.MainActivity } baseActivity=ComponentInfo{com.myCompanyName.myAppName/com.myCompanyName.myAppName.MainActivity} topActivity=ComponentInfo{com.myCompanyName.myAppName/com.myCompanyName.myAppName.MainActivity} origActivity=null realActivity=ComponentInfo{com.myCompanyName.myAppName/com.myCompanyName.myAppName.MainActivity} numActivities=1 lastActiveTime=142906428 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{f59299e Task{6de4e08 #218 type=standard A=10417:com.myCompanyName.myAppName}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 132 - 0, 0) topActivityInfo=ActivityInfo{1d90c7f com.myCompanyName.myAppName.MainActivity} launchCookies=[android.os.BinderProxy@473344c] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false isTopActivityTransparent=false locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden}, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@dc49c95, appThread = android.app.IApplicationThread$Stub$Proxy@4aa41aa, debugName = QuickstepLaunch }, displayChange = null, flags = 0 }
2024-01-16 15:10:29.145  1967-1991  WindowManagerShell      com.android.systemui                 V  onTransitionReady android.os.BinderProxy@90769d9: {id=673 t=OPEN f=0x0 trk=0 r=[0@Point(0, 0)] c=[{WCT{android.window.IWindowContainerToken$Stub$Proxy@1097b49} m=OPEN f=NONE leash=Surface(name=Task=218)/@0x504b202 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{WCT{android.window.IWindowContainerToken$Stub$Proxy@80fec4e} m=TO_BACK f=SHOW_WALLPAPER leash=Surface(name=Task=1)/@0xc89713 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
2024-01-16 15:10:29.145  1579-1683  WindowManager           system_server                        V      startWCT=WindowContainerTransaction { changes = {} hops = [] errorCallbackToken=null taskFragmentOrganizer=null }
2024-01-16 15:10:29.145  1967-1991  WindowManagerShell      com.android.systemui                 V  Playing animation for (#673)android.os.BinderProxy@90769d9@0
2024-01-16 15:10:29.145  1579-1683  WindowManager           system_server                        V      info={id=673 t=OPEN f=0x0 trk=0 r=[0@Point(0, 0)] c=[{WCT{RemoteToken{f59299e Task{6de4e08 #218 type=standard A=10417:com.myCompanyName.myAppName}}} m=OPEN f=NONE leash=Surface(name=Task=218)/@0xaa6d620 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{WCT{RemoteToken{490b12c Task{7fb062 #1 type=home}}} m=TO_BACK f=SHOW_WALLPAPER leash=Surface(name=Task=1)/@0x8c6f95f sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
2024-01-16 15:10:29.145  1967-1991  WindowManagerShell      com.android.systemui                 V   try firstHandler com.android.wm.shell.transition.DefaultMixedHandler@92b6a87
2024-01-16 15:10:29.145  1967-1991  WindowManagerShell      com.android.systemui                 V   Delegate animation for #673 to RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@67bca95, appThread = android.app.IApplicationThread$Stub$Proxy@eacd7aa, debugName = QuickstepLaunch }
2024-01-16 15:10:29.147  1967-1991  WindowManagerShell      com.android.systemui                 V   animated by firstHandler
2024-01-16 15:10:29.148 28146-28146 b/279059025             com...le.android.apps.nexuslauncher  D  current animation cancelled
2024-01-16 15:10:29.149 28146-28146 BaseDepthController     com...le.android.apps.nexuslauncher  D  mSurface is null and mCurrentBlur is: 0
2024-01-16 15:10:29.149 28146-28146 BaseDepthController     com...le.android.apps.nexuslauncher  D  mSurface is null and mCurrentBlur is: 0
2024-01-16 15:10:29.149 28146-28146 BaseDepthController     com...le.android.apps.nexuslauncher  D  mSurface is null and mCurrentBlur is: 0
2024-01-16 15:10:29.161 28146-28146 BaseDepthController     com...le.android.apps.nexuslauncher  D  mSurface is null and mCurrentBlur is: 0
2024-01-16 15:10:29.174 15291-16028 flutter                 com.myCompanyName.myAppName                I  Initializing Binding: LogBinding...
2024-01-16 15:10:29.179  1579-4465  CoreBackPreview         system_server                        D  Window{421c0e4 u0 com.myCompanyName.myAppName/com.myCompanyName.myAppName.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@bdcf913, mPriority=0, mIsAnimationCallback=false}
2024-01-16 15:10:29.186 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.194   626-626   binder:626_2            and...graphics.composer@2.4-service  W  type=1400 audit(0.0:9893): avc:  denied  { search } for  name="log" dev="dm-53" ino=313 scontext=u:r:hal_graphics_composer_default:s0 tcontext=u:object_r:vendor_log_file:s0 tclass=dir permissive=0
2024-01-16 15:10:29.194   626-626   binder:626_2            and...graphics.composer@2.4-service  W  type=1400 audit(0.0:9894): avc:  denied  { search } for  name="log" dev="dm-53" ino=313 scontext=u:r:hal_graphics_composer_default:s0 tcontext=u:object_r:vendor_log_file:s0 tclass=dir permissive=0
2024-01-16 15:10:29.193 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.197   626-626   hwc-display             and...graphics.composer@2.4-service  E  [PrimaryDisplay] resetColorMappingInfoForClientComp:: resetColorMappingInfo() idx=1 error(-22)
2024-01-16 15:10:29.197   626-626   hwc-display             and...graphics.composer@2.4-service  E  Fail to open file /data/vendor/log/hwc/PrimaryDisplay_hwc_error_log0.txt, error: Permission denied
2024-01-16 15:10:29.197   626-626   hwc-display             and...graphics.composer@2.4-service  E  Fail to open file /data/log/PrimaryDisplay_hwc_error_log0.txt, error: No such file or directory
2024-01-16 15:10:29.197   626-626   hwc-display             and...graphics.composer@2.4-service  E  Unable to open log file for PrimaryDisplay_hwc_error_log0.txt
2024-01-16 15:10:29.210 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.226 15524-15524 dwpx                    com....android.googlequicksearchbox  I  onPause
2024-01-16 15:10:29.227 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.234 15524-16010 ClearcutMetricXmitter   com....android.googlequicksearchbox  V  Transmission is done.
2024-01-16 15:10:29.243 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.260 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.277 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.293 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.310 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.327 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.344 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.360 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.377 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.382  3814-4569  AiAiStatsd              com.google.android.as                I  (REDACTED) Successfully logged feature usage for %s.
2024-01-16 15:10:29.394 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.395 28146-28146 QuickstepLauncher       com...le.android.apps.nexuslauncher  D  Bind extra container items
2024-01-16 15:10:29.395 28146-28146 QuickstepLauncher       com...le.android.apps.nexuslauncher  D  Bind extra container item is hotseat prediction
2024-01-16 15:10:29.396 28146-28146 HotseatPre...Controller com...le.android.apps.nexuslauncher  D  Predicted items: [WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.myCompanyName.myAppName/com.myCompanyName.myAppName.MainActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=MyApp Title), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.google.android.apps.nbu.files/com.google.android.apps.nbu.files.home.HomeActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Files), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.facebook.katana/com.facebook.katana.LoginActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Facebook), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.linkedin.android/com.linkedin.android.authenticator.LaunchActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=LinkedIn), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.whatsapp/com.whatsapp.Main} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=WhatsApp), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.android.vending/com.android.vending.AssetBrowserActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Play Store), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.google.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=YouTube), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.opongo.android/com.opongo.android.ActivitySplashScreen} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Mein Deal), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.google.android.apps.kids.familylink/com.google.android.apps.kids.familylink.flutter.standalone.HomeActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Family Link), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{de.metro.alex.customer.digitalcard.metro/com.metronom.app.companion.ui.main.MainActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=METRO), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{de.spiegel.android.app.spon/de.spiegel.android.app.spon.activities.SplashScreenActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=DER SPIEGEL), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.isarinteractive.skat.android.ad/com.isarinteractive.GameActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Skat), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f79dd targetComponent=ComponentInfo{com.netbiscuits.kicker/com.tickaroo.kicker.purabo.onboarding.KPurAboOnboardingActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=kicker), WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@19f7
2024-01-16 15:10:29.396 28146-28146 HotseatPre...Controller com...le.android.apps.nexuslauncher  D  fillGapsWithPrediction flags: FLAG_UPDATE_PAUSED
2024-01-16 15:10:29.410 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.427 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.444 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.461 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.477 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.493 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.510 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.527 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.544 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.560 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.577 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.593 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
2024-01-16 15:10:29.610 15291-15291 VRI[MainActivity]       com.myCompanyName.myAppName                D  Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.19044.3086], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.9.5)
[√] Android Studio (version 2023.1)
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
PS C:\Users\XXX\StudioProjects\XXX> 
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @chrisDK1977 
Since the issue is occuring upon building app bundle, can you try by testing it offline as mentioned in the [documentation](https://docs.flutter.dev/deployment/android#offline-using-the-bundle-tool) and see if it gives any more hints as why the app is getting stuck ?

Another area you could explore more related to app bundle is R8 code shrinker which might be shrinking some code in your app leading to the behavior you are getting. You can try by passing the flag `--no-shrink` and see if using it, you still get same behavior or not.

**Comment by darshankawar** [comment]
Thanks for the update @chrisDK1977 
I think in order to properly address the issue, is there a way for you to isolate it so that we can pinpoint what exactly could be causing it ? Because since it is occuring in full fledged app, identifying the root-cause would be difficult.

**Comment by chrisDK1977** [comment]
It seems the problem is in reading from FlutterSecureStorage while starting the app

  FlutterSecureStorage _secure = new FlutterSecureStorage();

_log.info("secure keys:");
for (String key in (await _secure.readAll()).keys) {
   _log.info("  $key");
}

removing the previous lines seem to fix the problem.

**Comment by darshankawar** [comment]
> Do you have any idea what the problem could be - or in which area? Could the problem be in a specific flutter version?
> What could be different when building via the PlayStore than when building locally?

Can't really say. We have seen similar issues wherein release mode shows a grey screen and stuck at loading screen, but our first impression about such cases is an error in code implementation. When it comes to a production app in which there are lot of custom implementations including third party packages, we can't really be sure to pinpoint a root-cause.



> It seems the problem is in reading from FlutterSecureStorage while starting the app
> 
> FlutterSecureStorage _secure = new FlutterSecureStorage();

Is this coming from https://pub.dev/packages/flutter_secure_storage ? If so, it is a third party package and if you are confident about it, you may need to report this in dedicated repo.

**Comment by chrisDK1977** [comment]
Thanks @darshankawar . I have tried to copy the part of the app initialisation into a test project - but the problem does not occur there. I will try to reproduce it in a small project.

**Comment by chrisDK1977** [comment]
@darshankawar 

The final Problem is:

PlatformException(Exception encountered, readAll, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
                                                                                                                 at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
                                                                                                                 at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
                                                                                                                 at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
                                                                                                                 at javax.crypto.Cipher.doFinal(Cipher.java:2056)
                                                                                                                 at y3.h.b(Unknown Source:35)
                                                                                                                 at x3.a.c(Unknown Source:11)
                                                                                                                 at x3.a.m(Unknown Source:92)
                                                                                                                 at x3.e$b.run(Unknown Source:204)
                                                                                                                 at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                                 at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                                 at android.os.Looper.loop(Looper.java:294)
                                                                                                                 at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    , null)
                                                                                                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
                                                                                                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:


Is this a problem at flutter_secure_storage?
