### ISSUE TITLE
Flutter Installation is not going beyond Resolving dependencies...

### ISSUE THREAD

**Issue by adityarath302** [flutter/flutter#141703]
### Steps to reproduce

Remove Flutter from system
Download zip and put back flutter into the same folder
Run Flutter doctor or Flutter doctor -v

### Actual results

Not going beyond flutter Resolving dependencies...

### Logs

<details open>
<summary>Logs</summary>

```console
Upgrading Flutter to 3.16.8 from 3.16.7 in
Downloading Darwin arm64 Dart SDK from Flutter engine 6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  207M    0 15087    0     0  21304      0  2:49:54 --:--:--  2:49:54 21279
  0  207M    0 88870    0     0  68058      0  0:53:11  0:00:01  0:53:10 68047
  0  207M    0 1790k    0     0   776k      0  0:04:32  0:00:02  0:04:30  776k
  6  207M    6 14.0M    0     0  4336k      0  0:00:48  0:00:03  0:00:45 4336k
 13  207M   13 27.2M    0     0  6473k      0  0:00:32  0:00:04  0:00:28 6472k
 19  207M   19 40.4M    0     0  7806k      0  0:00:27  0:00:05  0:00:22 9005k
 25  207M   25 53.6M    0     0  8712k      0  0:00:24  0:00:06  0:00:18 10.7M
 32  207M   32 66.5M    0     0  9332k      0  0:00:22  0:00:07  0:00:15 12.9M
 37  207M   37 78.6M    0     0  9704k      0  0:00:21  0:00:08  0:00:13 12.9M
 44  207M   44 91.9M    0     0   9.8M      0  0:00:20  0:00:09  0:00:11 12.9M
 50  207M   50  105M    0     0  10.1M      0  0:00:20  0:00:10  0:00:10 12.9M
 57  207M   57  118M    0     0  10.4M      0  0:00:19  0:00:11  0:00:08 12.9M
 63  207M   63  131M    0     0  10.6M      0  0:00:19  0:00:12  0:00:07 12.9M
 68  207M   68  141M    0     0  10.6M      0  0:00:19  0:00:13  0:00:06 12.4M
 73  207M   73  151M    0     0  10.6M      0  0:00:19  0:00:14  0:00:05 11.9M
 79  207M   79  164M    0     0  10.7M      0  0:00:19  0:00:15  0:00:04 11.8M
 85  207M   85  176M    0     0  10.8M      0  0:00:19  0:00:16  0:00:03 11.5M
 89  207M   89  185M    0     0  10.6M      0  0:00:19  0:00:17  0:00:02 10.7M
 95  207M   95  198M    0     0  10.8M      0  0:00:19  0:00:18  0:00:01 11.4M
100  207M  100  207M    0     0  10.8M      0  0:00:19  0:00:19 --:--:-- 11.4M
Building flutter tool...
Resolving dependencies...
<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

```

</details>

**Comment by huycozy** [comment]
Hi @adityarath302 
As my understanding, you downloaded `3.16.7` zip file and then ran the command `flutter upgrade`. Thereby, the `upgrade` command is stuck and is not finished, right?

Could you please share the entire output of `flutter upgrade -v`? Thanks!

**Comment by adrian-cytrix** [comment]
```[   +9 ms] executing: uname -m
[   +8 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +41 ms] executing: [/home/drei/snap/flutter/common/flutter/] git tag
--points-at HEAD
[  +20 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 3.16.8
[   +1 ms] executing: [/home/drei/snap/flutter/common/flutter/] git fetch --tags
123[+11152 ms] From https://github.com/flutter/flutter
                        91aceaa051..f77f82435a  main       -> origin/main
                        91aceaa051..f77f82435a  master     -> origin/master
[        ] executing: [/home/drei/snap/flutter/common/flutter/] git rev-parse
--verify @{upstream}
[   +5 ms] 67457e669f79e9f8d13d7a68fe09775fefbb79f4
[        ] executing: [/home/drei/snap/flutter/common/flutter/] git tag
--points-at 67457e669f79e9f8d13d7a68fe09775fefbb79f4
[  +17 ms] Exit code 0 from: git tag --points-at
67457e669f79e9f8d13d7a68fe09775fefbb79f4
[        ] 3.16.8
[        ] Flutter is already up to date on channel stable
[        ] executing: [/home/drei/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%ar
[        ] 2 days ago

[   +1 ms] Flutter 3.16.8 • channel stable •
https://github.com/flutter/flutter.git
           Framework • revision 67457e669f (2 days ago) • 2024-01-16 16:22:29
-0800
           Engine • revision 6e2ea58a5c
           Tools • Dart 3.2.5 • DevTools 2.28.5
[   +9 ms] "flutter upgrade" took 11,243ms.
[ +253 ms] ensureAnalyticsSent: 250ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
drei@macos:/media/drei/Local Repo/Flutter-Projects$ 123
123: command not found
drei@macos:/media/drei/Local Repo/Flutter-Projects$ flutter upgrade -v
[   +9 ms] executing: uname -m
[   +8 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +42 ms] executing: [/home/drei/snap/flutter/common/flutter/] git tag
--points-at HEAD
[  +19 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 3.16.8
[   +1 ms] executing: [/home/drei/snap/flutter/common/flutter/] git fetch --tags
[+6909 ms] executing: [/home/drei/snap/flutter/common/flutter/] git rev-parse
--verify @{upstream}
[   +7 ms] 67457e669f79e9f8d13d7a68fe09775fefbb79f4
[        ] executing: [/home/drei/snap/flutter/common/flutter/] git tag
--points-at 67457e669f79e9f8d13d7a68fe09775fefbb79f4
[  +17 ms] Exit code 0 from: git tag --points-at
67457e669f79e9f8d13d7a68fe09775fefbb79f4
[        ] 3.16.8
[        ] Flutter is already up to date on channel stable
[        ] executing: [/home/drei/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%ar
[        ] 2 days ago
[   +1 ms] Flutter 3.16.8 • channel stable •
https://github.com/flutter/flutter.git
           Framework • revision 67457e669f (2 days ago) • 2024-01-16 16:22:29
-0800
           Engine • revision 6e2ea58a5c
           Tools • Dart 3.2.5 • DevTools 2.28.5
[   +9 ms] "flutter upgrade" took 7,001ms.
[ +254 ms] ensureAnalyticsSent: 251ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
``` 
my internet is too slow to create a project?

**Comment by dustincatap** [comment]
Same issue with me, after running `flutter upgrade`, it doesn't go beyond `Resolving dependencies`. Tried running other commands, and its the same result. I do have stable internet connection btw.

![image](https://github.com/flutter/flutter/assets/56006524/0fd5b9b4-20dd-4837-a2ad-71bd95486183)

**Comment by huycozy** [comment]
@adrian-cytrix Which command does the output you give come from? Are you also having the same problem as @adityarath302?

This issue reminds me of an open issue at https://github.com/flutter/flutter/issues/140138 which is suspected to be happening on older processors. What is your machine's processor?

**Comment by dustincatap** [comment]
This is somewhat similar to https://github.com/flutter/flutter/issues/141113

**Comment by ProZhar** [comment]
It starts with 3.16.0 and all new versions do not work on older processors. #139792

**Comment by aivantuquero** [comment]
Have you tried using a vpn? Sometimes, this doesn't work if you have an unsecured connection. Google may reject requests that are not secured, resulting in an endless loop of rejected response.

**Comment by gu1llermo** [comment]
> It starts with 3.16.0 and all new versions do not work on older processors. #139792 Everyone with an old CPU is stuck using only 3.13.9

Why do you blame the old processors? that is a problem with the slash separator they are using, which is mixing the \\ of windows with / of linux

```powershell
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 6a687bef2c18ad36540e6babebe66a685881535c...
Expanding downloaded archive with PowerShell...
Building flutter tool...
Running pub upgrade...
Resolving dependencies...
Got dependencies.
Downloading android-arm-profile/windows-x64 tools...
PS C:\Users\prozhar\Flutter\_tests>
``` 
Note that the update ends when this file is downloading, if you can see the path has an inverted slash to that of the operating system

Downloading android-arm-profile **/** windows-x64 tools...
PS C:\Users\prozhar\Flutter **\\** _tests>

**Comment by ProZhar** [comment]
> > It starts with 3.16.0 and all new versions do not work on older processors. #139792 Everyone with an old CPU is stuck using only 3.13.9
> 
> Why do you blame the old processors? that is a problem with the slash separator they are using, which is mixing the \ of windows with / of linux
> 
> ```powershell
> Checking Dart SDK version...
> Downloading Dart SDK from Flutter engine 6a687bef2c18ad36540e6babebe66a685881535c...
> Expanding downloaded archive with PowerShell...
> Building flutter tool...
> Running pub upgrade...
> Resolving dependencies...
> Got dependencies.
> Downloading android-arm-profile/windows-x64 tools...
> PS C:\Users\prozhar\Flutter\_tests>
> ```
> 
> Note that the update ends when this file is downloading, if you can see the path has an inverted slash to that of the operating system
> 
> Downloading android-arm-profile **/** windows-x64 tools... PS C:\Users\prozhar\Flutter **\** _tests>

I don't think so.
Why do you blame the the slash separator? 99% of Windows users do not have this problem, so the slash separator has nothing to do with it. The only thing we have identified so far in common among those who have problems after 3.13.9 is the use of an old x86_64 CPU

**Comment by gu1llermo** [comment]
> Why do you blame the the slash separator?

Because if you mix them in the same path it gives you an error and doesn't let you save the file

**Comment by gu1llermo** [comment]
> The only thing we have identified so far in common among those who have problems after 3.13.9 is the use of an old x86_64 CPU

And I have identified that the error is in the download of the files

**Comment by gu1llermo** [comment]
The only logical explanation is that the latest generation processors correct a path sent to save a file, but if that is the case, they still have that problem of mixing the slashes and I see that they do not support it and that is wrong.

**Comment by gu1llermo** [comment]
```powershell
PS C:\Users\guillermo> flutter upgrade -v
[ +295 ms] executing: [C:\dev\flutter/] git tag --points-at HEAD
[ +434 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 3.13.9
[   +5 ms] executing: [C:\dev\flutter/] git fetch --tags
[+4479 ms] From https://github.com/flutter/flutter
                       67457e669f..41456452f2  stable          -> origin/stable
                       67457e669f..41456452f2  flutter-3.16-candidate.0 -> origin/flutter-3.16-candidate.0
                     * [new branch]            flutter-3.19-candidate.10 -> origin/flutter-3.19-candidate.10
                     * [new branch]            flutter-3.19-candidate.9 -> origin/flutter-3.19-candidate.9
                       49447fc68b..f61d2f53c6  main            -> origin/main
                       49447fc68b..f61d2f53c6  master          -> origin/master
                     * [new branch]            zanderso-try-android-ndk -> origin/zanderso-try-android-ndk
                     * [new tag]               3.16.9          -> 3.16.9
                     * [new tag]               3.19.0-10.0.pre -> 3.19.0-10.0.pre
                     * [new tag]               3.19.0-9.0.pre  -> 3.19.0-9.0.pre
[   +5 ms] executing: [C:\dev\flutter/] git rev-parse --verify @{upstream}
[ +111 ms] 41456452f29d64e8deb623a3c927524bcf9f111b
[   +3 ms] executing: [C:\dev\flutter/] git tag --points-at 41456452f29d64e8deb623a3c927524bcf9f111b
[ +132 ms] Exit code 0 from: git tag --points-at 41456452f29d64e8deb623a3c927524bcf9f111b
[   +1 ms] 3.16.9
[   +1 ms] executing: [C:\dev\flutter/] git status -s
[+9403 ms] Upgrading Flutter to 3.16.9 from 3.13.9 in C:\dev\flutter...
[   +3 ms] executing: [C:\dev\flutter/] git reset --hard 41456452f29d64e8deb623a3c927524bcf9f111b
[+7069 ms] HEAD is now at 41456452f2 [flutter_releases] Flutter stable 3.16.9 Framework Cherrypicks (#142231)

                    Updating files:  21% (497/2347)Updating files:  22% (517/2347)Updating files:  23%
                    (540/2347)Updating files:  24% (564/2347)Updating files:  25% (587/2347)Updating files:  26%
                    (611/2347)Updating files:  27% (634/2347)Updating files:  28% (658/2347)Updating files:  29%
                    (681/2347)Updating files:  30% (705/2347)Updating files:  31% (728/2347)Updating files:  32%
                    (752/2347)Updating files:  33% (775/2347)Updating files:  34% (798/2347)Updating files:  35%
                    (822/2347)Updating files:  36% (845/2347)Updating files:  37% (869/2347)Updating files:  38%
                    (892/2347)Updating files:  38% (900/2347)Updating files:  39% (916/2347)Updating files:  40%
                    (939/2347)Updating files:  41% (963/2347)Updating files:  42% (986/2347)Updating files:  43%
                    (1010/2347)Updating files:  44% (1033/2347)Updating files:  45% (1057/2347)Updating files:  46%
                    (1080/2347)Updating files:  47% (1104/2347)Updating files:  48% (1127/2347)Updating files:  49%
                    (1151/2347)Updating files:  50% (1174/2347)Updating files:  51% (1197/2347)Updating files:  52%
                    (1221/2347)Updating files:  53% (1244/2347)Updating files:  53% (1259/2347)Updating files:  54%
                    (1268/2347)Updating files:  55% (1291/2347)Updating files:  56% (1315/2347)Updating files:  57%
                    (1338/2347)Updating files:  58% (1362/2347)Updating files:  59% (1385/2347)Updating files:  60%
                    (1409/2347)Updating files:  61% (1432/2347)Updating files:  62% (1456/2347)Updating files:  63%
                    (1479/2347)Updating files:  64% (1503/2347)Updating files:  65% (1526/2347)Updating files:  66%
                    (1550/2347)Updating files:  67% (1573/2347)Updating files:  68% (1596/2347)Updating files:  69%
                    (1620/2347)Updating files:  70% (1643/2347)Updating files:  71% (1667/2347)Updating files:  71%
                    (1684/2347)Updating files:  72% (1690/2347)Updating files:  73% (1714/2347)Updating files:  74%
                    (1737/2347)Updating files:  75% (1761/2347)Updating files:  76% (1784/2347)Updating files:  77%
                    (1808/2347)Updating files:  78% (1831/2347)Updating files:  79% (1855/2347)Updating files:  80%
                    (1878/2347)Updating files:  81% (1902/2347)Updating files:  82% (1925/2347)Updating files:  83%
                    (1949/2347)Updating files:  84% (1972/2347)Updating files:  85% (1995/2347)Updating files:  86%
                    (2019/2347)Updating files:  87% (2042/2347)Updating files:  88% (2066/2347)Updating files:  89%
                    (2089/2347)Updating files:  90% (2113/2347)Updating files:  91% (2136/2347)Updating files:  91%
                    (2150/2347)Updating files:  92% (2160/2347)Updating files:  93% (2183/2347)Updating files:  94%
                    (2207/2347)Updating files:  94% (2216/2347)Updating files:  95% (2230/2347)Updating files:  96%
                    (2254/2347)Updating files:  97% (2277/2347)Updating files:  98% (2301/2347)Updating files:  99%
                    (2324/2347)Updating files: 100% (2347/2347)Updating files: 100% (2347/2347), done.
[  +28 ms] executing: [C:\dev\flutter/] bin\flutter upgrade --continue --no-version-check
[ +618 ms] Checking Dart SDK version...
[   +9 ms] Downloading Dart SDK from Flutter engine f40e976bedff57e69e1b3d89a7c2a3c617a03dad...
[+27042 ms] Expanding downloaded archive with PowerShell...
[+15618 ms] Building flutter tool...
[  +11 ms] Running pub upgrade...
[ +719 ms] Resolving dependencies...
[+10736 ms] Got dependencies.
[+90637 ms] Upgrading engine...
[+3358 ms] Downloading android-arm-profile/windows-x64 tools...
[ +984 ms] "flutter upgrade" took 171,481ms.
[  +14 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      UpgradeCommandRunner.flutterUpgradeContinue (package:flutter_tools/src/commands/upgrade.dart:201:7)
           <asynchronous suspension>
           #2      UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:176:7)
           <asynchronous suspension>
           #3      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:106:7)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +266 ms] ensureAnalyticsSent: 237ms
[   +7 ms] Running 0 shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +3 ms] exiting with code -1073741795
PS C:\Users\guillermo>
``` 

It is curious that the update generates an error when downloading the files, and by following up on the error log, I came to this part of the code:

```dart
Future<void> flutterUpgradeContinue() async {
    final int code = await globals.processUtils.stream(
      <String>[
        globals.fs.path.join('bin', 'flutter'),
        'upgrade',
        '--continue',
        '--no-version-check',
      ],
      workingDirectory: workingDirectory,
      allowReentrantFlutter: true,
      environment: Map<String, String>.of(globals.platform.environment),
    );
    if (code != 0) {
      throwToolExit(null, exitCode: code);
    }
  }
``` 

And precisely the error is generated when they join the path

```dart
globals.fs.path.join('bin', 'flutter'),
``` 

I want to help, but not being able to install flutter has discouraged me a little, but logic tells me that there is a problem here.
I really sincerely hope that you can solve this problem, because I don't know if you are even reading me.

**Comment by huycozy** [comment]
@gu1llermo What is the current Flutter version you are upgrading from? Could you share the output of `flutter doctor -v`?

**Comment by gu1llermo** [comment]
Hi @huycozy, I downloaded version 3.16.8 of Flutter and proceeded to update, I show you:
```powershell
PS C:\Users\guillermo> flutter doctor -v
[√] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Versi¢n 10.0.19045.3930], locale es-MX)
    • Flutter version 3.16.8 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (9 days ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Android\sdk\
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34408.163
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\guillermo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.3930]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.200
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.133

[√] Network resources
    • All expected network resources are available.

• No issues found!
PS C:\Users\guillermo>
``` 
Now I proceed to update it and it stays there:

```powershell
PS C:\Users\guillermo> flutter upgrade -v
[ +321 ms] executing: [C:\dev\flutter/] git tag --points-at HEAD
[ +131 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 3.16.8
[   +6 ms] executing: [C:\dev\flutter/] git fetch --tags
[+1420 ms] executing: [C:\dev\flutter/] git rev-parse --verify @{upstream}
[ +106 ms] 41456452f29d64e8deb623a3c927524bcf9f111b
[   +6 ms] executing: [C:\dev\flutter/] git tag --points-at 41456452f29d64e8deb623a3c927524bcf9f111b
[ +118 ms] Exit code 0 from: git tag --points-at 41456452f29d64e8deb623a3c927524bcf9f111b
[   +3 ms] 3.16.9
[   +3 ms] executing: [C:\dev\flutter/] git status -s
[+2959 ms] Upgrading Flutter to 3.16.9 from 3.16.8 in C:\dev\flutter...
[   +4 ms] executing: [C:\dev\flutter/] git reset --hard 41456452f29d64e8deb623a3c927524bcf9f111b
[ +512 ms] HEAD is now at 41456452f2 [flutter_releases] Flutter stable 3.16.9 Framework Cherrypicks (#142231)
[   +6 ms] executing: [C:\dev\flutter/] bin\flutter upgrade --continue --no-version-check
[ +538 ms] Checking Dart SDK version...
[+1384877 ms] Downloading Dart SDK from Flutter engine f40e976bedff57e69e1b3d89a7c2a3c617a03dad...
[  +10 ms] Building flutter tool...
[   +1 ms] Running pub upgrade...
[   +3 ms] Expanding downloaded archive with PowerShell...
[   +1 ms] Resolving dependencies...
[   +1 ms] Got dependencies.
[   +2 ms] Upgrading engine...
[   +1 ms] Downloading android-arm-profile/windows-x64 tools...
PS C:\Users\guillermo>
```

**Comment by gu1llermo** [comment]
If the code was written in Java I could solve it myself, but it is in Dart and I don't master Dart, rather I want to learn Dart to program with Flutter, but if I can't install Flutter, why would I learn Dart?

**Comment by gu1llermo** [comment]
Now using Flutter version 3.13.9
```powershell
PS C:\Users\guillermo> flutter doctor -v
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Versi¢n 10.0.19045.3930], locale es-MX)
    • Flutter version 3.13.9 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 months ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Android\sdk\
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34408.163
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\guillermo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.3930]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.200
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.133

[√] Network resources
    • All expected network resources are available.

• No issues found!
``` 
Updating:
```powershell
PS C:\Users\guillermo> flutter upgrade -v
[ +225 ms] executing: [C:\dev\flutter/] git tag --points-at HEAD
[ +137 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 3.13.9
[   +5 ms] executing: [C:\dev\flutter/] git fetch --tags
[+1497 ms] executing: [C:\dev\flutter/] git rev-parse --verify @{upstream}
[ +103 ms] 41456452f29d64e8deb623a3c927524bcf9f111b
[   +4 ms] executing: [C:\dev\flutter/] git tag --points-at 41456452f29d64e8deb623a3c927524bcf9f111b
[ +125 ms] Exit code 0 from: git tag --points-at 41456452f29d64e8deb623a3c927524bcf9f111b
[   +1 ms] 3.16.9
[   +1 ms] executing: [C:\dev\flutter/] git status -s
[+2792 ms] Upgrading Flutter to 3.16.9 from 3.13.9 in C:\dev\flutter...
[   +2 ms] executing: [C:\dev\flutter/] git reset --hard 41456452f29d64e8deb623a3c927524bcf9f111b
[+5673 ms] HEAD is now at 41456452f2 [flutter_releases] Flutter stable 3.16.9 Framework Cherrypicks (#142231)

                    Updating files:  27% (634/2347)Updating files:  28% (658/2347)Updating files:  29% (681/2347)Updating files:  30% (705/2347)Updating files:  31% (728/2347)Updating files:
                    32% (752/2347)Updating files:  33% (775/2347)Updating files:  34% (798/2347)Updating files:  35% (822/2347)Updating files:  36% (845/2347)Updating files:  37%
                    (869/2347)Updating files:  38% (892/2347)Updating files:  39% (916/2347)Updating files:  40% (939/2347)Updating files:  41% (963/2347)Updating files:  42%
                    (986/2347)Updating files:  43% (1010/2347)Updating files:  44% (1033/2347)Updating files:  45% (1057/2347)Updating files:  46% (1080/2347)Updating files:  46%
                    (1100/2347)Updating files:  47% (1104/2347)Updating files:  48% (1127/2347)Updating files:  49% (1151/2347)Updating files:  50% (1174/2347)Updating files:  51%
                    (1197/2347)Updating files:  52% (1221/2347)Updating files:  53% (1244/2347)Updating files:  54% (1268/2347)Updating files:  55% (1291/2347)Updating files:  56%
                    (1315/2347)Updating files:  57% (1338/2347)Updating files:  58% (1362/2347)Updating files:  59% (1385/2347)Updating files:  60% (1409/2347)Updating files:  61%
                    (1432/2347)Updating files:  62% (1456/2347)Updating files:  63% (1479/2347)Updating files:  64% (1503/2347)Updating files:  65% (1526/2347)Updating files:  66%
                    (1550/2347)Updating files:  67% (1573/2347)Updating files:  68% (1596/2347)Updating files:  68% (1618/2347)Updating files:  69% (1620/2347)Updating files:  70%
                    (1643/2347)Updating files:  71% (1667/2347)Updating files:  72% (1690/2347)Updating files:  73% (1714/2347)Updating files:  74% (1737/2347)Updating files:  75%
                    (1761/2347)Updating files:  76% (1784/2347)Updating files:  77% (1808/2347)Updating files:  78% (1831/2347)Updating files:  79% (1855/2347)Updating files:  80%
                    (1878/2347)Updating files:  81% (1902/2347)Updating files:  82% (1925/2347)Updating files:  83% (1949/2347)Updating files:  84% (1972/2347)Updating files:  85%
                    (1995/2347)Updating files:  86% (2019/2347)Updating files:  87% (2042/2347)Updating files:  88% (2066/2347)Updating files:  89% (2089/2347)Updating files:  90%
                    (2113/2347)Updating files:  90% (2124/2347)Updating files:  91% (2136/2347)Updating files:  92% (2160/2347)Updating files:  93% (2183/2347)Updating files:  94%
                    (2207/2347)Updating files:  95% (2230/2347)Updating files:  96% (2254/2347)Updating files:  97% (2277/2347)Updating files:  98% (2301/2347)Updating files:  99%
                    (2324/2347)Updating files:  99% (2343/2347)Updating files: 100% (2347/2347)Updating files: 100% (2347/2347), done.
[  +24 ms] executing: [C:\dev\flutter/] bin\flutter upgrade --continue --no-version-check
[ +547 ms] Checking Dart SDK version...
[   +8 ms] Downloading Dart SDK from Flutter engine f40e976bedff57e69e1b3d89a7c2a3c617a03dad...
[+26363 ms] Expanding downloaded archive with PowerShell...
[+13801 ms] Building flutter tool...
[  +10 ms] Running pub upgrade...
[ +740 ms] Resolving dependencies...
[+32668 ms] Got dependencies.
[+47282 ms] Upgrading engine...
[+2883 ms] Downloading android-arm-profile/windows-x64 tools...
[ +937 ms] "flutter upgrade" took 135,677ms.
[  +13 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      UpgradeCommandRunner.flutterUpgradeContinue (package:flutter_tools/src/commands/upgrade.dart:201:7)
           <asynchronous suspension>
           #2      UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:176:7)
           <asynchronous suspension>
           #3      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:106:7)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +270 ms] ensureAnalyticsSent: 247ms
[   +7 ms] Running 0 shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +3 ms] exiting with code -1073741795
PS C:\Users\guillermo>
``` 

Here shows a log where the error occurs, and if you follow it you realize what happens when they join a path

**Comment by huycozy** [comment]
I see, it should have run `flutter doctor` once finished. I checked the issue database and found you filed one at https://github.com/flutter/flutter/issues/141399. I also see your comment at https://github.com/flutter/flutter/issues/140138, so please follow that issue for updates.
