### ISSUE TITLE
[tool_crash] FileSystemException: Creation of temporary directory failed, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by onesmus1024** [flutter/flutter#141857]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation of temporary directory failed, OS Error: Permission denied, errno = 13
```
#0      _Directory.createTempSync (dart:io/directory_impl.dart:175:7)
#1      ForwardingDirectory.createTempSync (package:file/src/forwarding/forwarding_directory.dart:28:21)
#2      LocalFileSystem.systemTempDirectory (package:flutter_tools/src/base/file_system.dart:228:46)
#3      ForwardingFileSystem.systemTempDirectory (package:file/src/forwarding/forwarding_file_system.dart:33:49)
#4      new ResidentRunner (package:flutter_tools/src/resident_runner.dart:1107:24)
#5      new ResidentWebRunner (package:flutter_tools/src/isolated/resident_web_runner.dart:103:8)
#6      DwdsWebRunnerFactory.createWebRunner (package:flutter_tools/src/isolated/resident_web_runner.dart:62:12)
#7      RunCommand.createRunner (package:flutter_tools/src/commands/run.dart:626:32)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:748:35)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.8, on Kali GNU/Linux Rolling 6.5.0-kali3-amd64, locale C.UTF-8)
    [32m•[39m Flutter version 3.16.8 on channel stable at /home/onemus/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 67457e669f (3 days ago), 2024-01-16 16:22:29 -0800
    [32m•[39m Engine revision 6e2ea58a5c
    [32m•[39m Dart version 3.2.5
    [32m•[39m DevTools version 2.28.5

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /home/onemus/Android/Sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[31m[✗][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Debian clang version 16.0.6 (16)
    [31m✗[39m CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    [31m✗[39m ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    [32m•[39m pkg-config version 1.8.1
    [31m✗[39m GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /opt/android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version openjdk version "17.0.7" 2023-04-18

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.80.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Kali GNU/Linux Rolling 6.5.0-kali3-amd64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.62

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 6c4930c4ac86fb286f30e31d0ec8bffbcbb9953e
### Plugins
path_provider-2.1.1
path_provider_android-2.2.1
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1

**Comment by dam-ease** [comment]
Thanks for the report!
I see a similar issue that was solved by https://github.com/flutter/flutter/issues/99601#issuecomment-1060658491. 
Can you check it out if it works in your case?

**Comment by onesmus1024** [comment]
Yes, it worked.
Thank you!
