### ISSUE TITLE
Cannot develop for Android without Android Studio

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14189]
Flutter doctor reports that the user can "develop for Android devices" with the "Android toolchain" item checked, even if the "Android Studio" item is only partially checked:

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel unknown)
    • Flutter at <redacted>
    • Framework revision 0a96f96c4f (11 days ago), 2018-01-08 15:01:43 +0100
    • Engine revision 12e0e38a8b
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.8d7219a5b6a7c2505ff57f23e7cf80da4c724512

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at <redacted>
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-2ubuntu0.14.04.1)

[-] Android Studio
    • Android Studio at <redacted>
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)
```

Yet, when I attempt to run the gallery, Gradle crashes:

```
$ flutter run --debug
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                   |
Oops; flutter has exited unexpectedly: "Exit code 1 from: /usr/local/google/home/tvolkert/project/flutter/flutter/examples/flutter_gallery/android/gradlew -v:
Downloading https://services.gradle.org/distributions/gradle-4.1-all.zip


Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1914)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1872)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1855)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1376)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1353)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1366)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
	at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1024)
	at sun.security.pkcs11.P11Key.equals(P11Key.java:158)
	at java.util.ArrayList.indexOf(ArrayList.java:302)
	at java.util.ArrayList.contains(ArrayList.java:285)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:239)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1459)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:961)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:897)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1033)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1369)
	... 13 more
Caused by: java.security.InvalidKeyException: EC parameters error
	at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:284)
	at sun.security.ec.ECPublicKeyImpl.<init>(ECPublicKeyImpl.java:59)
	at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1021)
	... 28 more
Caused by: java.security.NoSuchProviderException: no such provider: SunEC
	at sun.security.jca.GetInstance.getService(GetInstance.java:83)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at java.security.Security.getImpl(Security.java:697)
	at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:199)
	at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:279)
	... 30 more".
 
Sending crash report to Google.
Crash report sent (report ID: 67b0b9155d6b5ac8)
```

**Comment by jason-simmons** [comment]
This is probably due to the configuration of the JVM used to run Gradle in your environment (see https://github.com/gradle/gradle/issues/2421)

**Comment by tvolkert** [comment]
Updating Android Studio (by blowing away the old `~/android-studio` folder and unzipping a newly downloaded `android-studio.zip` in its place) did solve the problem, and my JVM lives in a system location that only root has access to modify, so I'm not sure that the newly installed Android Studio would have been able to install any crypto certs on my behalf in my JVM installation.

**Comment by iapicca** [comment]
Hi @tvolkert is this issue still meant to be open?
