### ISSUE TITLE
Golden file testing for flutter/flutter is unreliable

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#141880]
https://github.com/flutter/flutter/pull/140101 introduced a regression that causes failures at head to not break the tree.
Because of this, there is no enforcement of approved/unapproved images right now for flutter/flutter.

The revert is currently blocked.

- Revert: https://github.com/flutter/flutter/pull/141814
- Blocked by https://github.com/flutter/flutter/issues/140169
  - https://github.com/flutter/flutter/pull/141427

Until resolved, contributors should consider refraining from introducing image changes. If necessary, i.e. from an engine roll, please check https://flutter-gold.skia.org/ after the change lands to ensure any new images or updated images are properly approved. Otherwise changes may cascade down to other PRs looking for approval.

We do have a safety net of sorts against regressions due to extensive golden file testing inside of Google, which is executed when Flutter rolls into Google.

**Comment by Hixie** [comment]
When I made the precommit testing use the postcommit logic in the refactored code, it failed like this:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following SkiaException was thrown while running async test code:
Skia Gold received an unapproved image in post-submit testing. Golden file images in flutter/flutter
are triaged in pre-submit during code review for the given PR.

Visit https://flutter-gold.skia.org// to view and approve the image(s), or revert the associated
change. For more information, visit the wiki:
  https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

imgtest add failed with exit code 1.

stdout from gold:
  Given image with hash b69d8376aaf056c0046488bb8d84b245 for test
widgets.inconsequential_golden_file
  Expectation for test: 08bb9be9631c06cb292828de6cf2f542 (positive)
  Expectation for test: 1d4a2df1b8e3ce03d5b5efa4a5196916 (positive)
  Expectation for test: 558879480ee59948f70ae118c71d8155 (positive)
  Expectation for test: a5e59a594e5e49b1a9c938ecd08704d5 (positive)
  Untriaged or negative image:
https://flutter-gold.skia.org/detail?grouping=name%3Dwidgets.inconsequential_golden_file%26source_type%3Dflutter&digest=b69d8376aaf056c0046488bb8d84b245



stderr from gold:
  Test: widgets.inconsequential_golden_file FAIL

When the exception was thrown, this was the stack:
#0      SkiaGoldClient._retry (package:flutter_goldens/skia_client.dart:179:7)
<asynchronous suspension>
#1      SkiaGoldClient.imgtestAdd (package:flutter_goldens/skia_client.dart:295:5)
<asynchronous suspension>
#2      FlutterPostSubmitFileComparator.compare (package:flutter_goldens/flutter_goldens.dart:312:5)
<asynchronous suspension>
#3      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from dart:async)

The exception was caught asynchronously.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

The working code just now failed like this:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following SkiaException was thrown while running async test code:
Skia Gold received an unapproved image in post-submit
testing. Golden file images in flutter/flutter are triaged
in pre-submit during code review for the given PR.

Visit https://flutter-gold.skia.org// to view and approve
the image(s), or revert the associated change. For more
information, visit the wiki:
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

Debug information for Gold --------------------------------
stdout: Given image with hash 3ceac0ec44faa127e6d7d5028647aaec for test
cupertino.text_field_golden.TextSelectionStyle.1
Expectation for test: 3a5dc3f6e13adfc3211a319761c009c9 (positive)
Expectation for test: 58f3667e3688d3d99d581fbf7c75d999 (positive)
Expectation for test: 62c5ed83ef4bc9d23502b6bfadcd2498 (positive)
Expectation for test: d8539c084e253dc82f41a5dbdaf34921 (positive)
Expectation for test: 3c42826843d2fbe805635dcf943b3a65 (positive)
Expectation for test: a7a583ea870e6524bb4032699cd6a09c (positive)
Expectation for test: bc9f49c4fec58831c05fc57953141a50 (positive)
Expectation for test: d92a7dff089ad9c43d2ecd9281017758 (positive)
Expectation for test: e1f901d43418ea0907b3df09f515c316 (positive)
Expectation for test: ef7c481797da3a542eb6f033a47c4594 (positive)
Expectation for test: 218c711695c56854f87f16d80cb4699f (positive)
Expectation for test: 3c234ba75737732c613bb2d576ed1abd (positive)
Expectation for test: 9acd7b59de548f9830ecb394bc53a297 (positive)
Expectation for test: ab2856b91547320175417ed798ea34c9 (positive)
Expectation for test: e787ace65a50d9435cc7830c2f341bc5 (positive)
Expectation for test: 37c217382a4c4e344278cdc9c798be93 (positive)
Expectation for test: 753f60cb7da09fb940803d71d39bc875 (positive)
Expectation for test: a22f317c23bb5c6c6df8e47efc262c44 (positive)
Expectation for test: c2ce42704cf62496597ffee10e09da1d (positive)
Expectation for test: 441d3934bc932cee0b6ad95701073c7f (positive)
Expectation for test: 7b028dd6bf93ec0dc91db38773acd400 (positive)
Expectation for test: e7cb5b4d2d7f77669c6c2094df2b48d5 (positive)
Expectation for test: 0d0673dadefaa289bfd65cb0a81368d8 (positive)
Expectation for test: 22db2aa6f2955bc15e20951170ea50fc (positive)
Expectation for test: a2bdfe38910aa5b766d2cda6b0cea4cc (positive)
Expectation for test: c3997f75552f9fbf88433b9a9949abf8 (positive)
Expectation for test: e070aa3abf7f5f07f7c36f34892d7326 (positive)
Expectation for test: 26394dbcb3350aa5692d48adcb5d19b8 (positive)
Expectation for test: 87f168b6be45c48c112b033137d73811 (positive)
Expectation for test: d3e76ae1c89d0060356e4d68efea3778 (positive)
Expectation for test: e69d7a9b3cb2280d4cfb34ad84df2702 (positive)
Untriaged or negative image:
https://flutter-gold.skia.org/detail?grouping=name%3Dcupertino.text_field_golden.TextSelectionStyle.1%26source_type%3Dflutter&digest=3ceac0ec44faa127e6d7d5028647aaec


stderr: Test: cupertino.text_field_golden.TextSelectionStyle.1 FAIL


result-state.json: No result file found.

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.imgtestAdd (package:flutter_goldens_client/skia_client.dart:244:7)
<asynchronous suspension>
#1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from dart:async)

The exception was caught asynchronously.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

...so both are interpreting the failure the same way, basically. I am so curious to find out what the actual cause of it not catching failures post-submit on `main` is.

**Comment by Piinks** [comment]
> precommit testing use the postcommit logic

The logic for these are not interchangeable. The postsubmit logic is not permitted to actually work in presubmit because postsubmit operations in Gold require a valid commit on the master branch.
I would consider feedback from swapping them as irrelevant.

**Comment by Hixie** [comment]
Sure, I'm just trying to narrow down where the problem can be. Since (whether permitted or not) the imgtestAdd function did fail the same way in both cases, it indicates that the failure is not in the logic that catches imgtestAdd failures. (This was not a given, it could easily have been that the post-commit code somehow wouldn't catch imgtestAdd failures at all.)
