### ISSUE TITLE
flutter返回上一页面Navigator.pop(context);有时会报错，有人遇到过么

### ISSUE THREAD

**Issue by weiwuxing** [flutter/flutter#141923]
### Steps to reproduce

1.Jump to new page;
2.Flutter returns to the previous page Navigator.pop(context); sometimes an error will be reported, you can click more times.

### Expected results

normal return
### Actual results

Sometimes you can go back. Sometimes an error will be reported
```
======== Exception caught by gesture ===============================================================
The following RangeError was thrown while handling a gesture:
RangeError (index): Invalid value: Not in inclusive range 0..1: -1

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _History.[] (package:flutter/src/widgets/navigator.dart:3436:18)
#2      NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:5418:44)
#3      new _CupertinoBackGestureController (package:flutter/src/cupertino/route.dart:720:15)
#4      CupertinoRouteTransitionMixin._startPopGesture (package:flutter/src/cupertino/route.dart:248:12)
#5      CupertinoRouteTransitionMixin.buildPageTransitions.<anonymous closure> (package:flutter/src/cupertino/route.dart:295:36)
#6      _CupertinoBackGestureDetectorState._handleDragStart (package:flutter/src/cupertino/route.dart:635:54)
#7      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:529:53)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#9      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:529:7)
#10     DragGestureRecognizer._checkDrag (package:flutter/src/gestures/monodrag.dart:496:5)
#11     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:429:7)
#12     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:268:25)
#13     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:248:31)
(elided 2 frames from dart:async)
Handler: "onStart"
Recognizer: HorizontalDragGestureRecognizer#f041c
  debugOwner: _CupertinoBackGestureDetectorState<dynamic>#3d09f
  start behavior: start
====================================================================================================

======== Exception caught by gesture ===============================================================
The following StateError was thrown while handling a gesture:
Bad state: No element
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```appBar: AppBar(
          title: Image.asset("images/saolei/title.png",height: 30,),
          backgroundColor: Colors.transparent,
          leading:  IconButton(
          icon: const Icon(Icons.menu),
          onPressed: () {
            Navigator.pop(context);
          },
         )

</details>


### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@weiwuxing 
As mentioned above, please use above steps while filing a new issue and use new issue template so that we can properly address the issue.
Looking at the error log, it seems similar to https://github.com/flutter/flutter/issues/86459 so follow-up in it for further updates.
Closing as duplicate.

**Comment by l941230** [comment]
你是怎么复现的
