### ISSUE TITLE
[go_router] when shortcut command register in not working correctly

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#141927]
### Steps to reproduce

```
MaterialApp.router(
      routerConfig: DesktopRoutes.goRouter,
      
      shortcuts: {
        LogicalKeySet(
            (Platform.isMacOS
                ? LogicalKeyboardKey.meta
                : LogicalKeyboardKey.control),
            LogicalKeyboardKey.keyV): const PasteIntent(),
      },
      actions: {
        PasteIntent: PasteAction()
           
      },
      builder: (context, child) {
        final mediaQueryData = MediaQuery.of(context);

        final scale = mediaQueryData.textScaler
            .clamp(minScaleFactor: 0.9, maxScaleFactor: 1.0);
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(textScaler: scale),
          child: child ?? const SizedBox(),
        );
      },
      debugShowCheckedModeBanner: false,
      
    );
  }
```
if this router configuration is used 

### Expected results

paste should only triggered when command+v is pressed its need to be triggered corrrectly on every command+v combination

### Actual results

paste should only triggered when command+v is pressed its triggered correctly on one time 
on the second time if only the command is pressed the paste action triggered without combining v

### Code sample

<details open><summary>Code sample</summary>

```
MaterialApp.router(
      routerConfig: DesktopRoutes.goRouter,
      
      shortcuts: {
        LogicalKeySet(
            (Platform.isMacOS
                ? LogicalKeyboardKey.meta
                : LogicalKeyboardKey.control),
            LogicalKeyboardKey.keyV): const PasteIntent(),
      },
      actions: {
        PasteIntent: PasteAction()
           
      },
      builder: (context, child) {
        final mediaQueryData = MediaQuery.of(context);

        final scale = mediaQueryData.textScaler
            .clamp(minScaleFactor: 0.9, maxScaleFactor: 1.0);
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(textScaler: scale),
          child: child ?? const SizedBox(),
        );
      },
      debugShowCheckedModeBanner: false,
      
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter --verbose create foo.
[   +3 ms] executing: sw_vers -productName
[  +11 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +5 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.2.1
[        ] executing: sw_vers -buildVersion
[   +5 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23C71
[        ] executing: uname -m
[   +1 ms] Exit code 0 from: uname -m
[        ] arm64
[   +2 ms] executing: sysctl hw.optional.arm64
[   +2 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +25 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +46 ms] executing: which security
[  +19 ms] executing: which openssl
[   +5 ms] executing: security find-identity -p codesigning -v
[  +41 ms]   1) EAE84901E1B30CC30CB467BA708C1F0B5A625BF8 "Apple Development: Ahmad Sattar (467SN49542)"
             2) BEDA1EEC0B121B390EA3E723E75DDD5F46D9942E "Apple Development: Abdul Rehman (SKGXHD22J6)"
                2 valid identities found
[   +1 ms] Signing iOS app for device deployment using developer identity: "Apple Development: Ahmad Sattar (467SN49542)"
[        ] executing: security find-certificate -c 467SN49542 -p
[  +13 ms] -----BEGIN CERTIFICATE-----
           MIIFxjCCBK6gAwIBAgIQTLiWTKWUr0ap1cyO9r42MzANBgkqhkiG9w0BAQsFADB1
           MUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBD
           ZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTELMAkGA1UECwwCRzMxEzARBgNVBAoMCkFw
           cGxlIEluYy4xCzAJBgNVBAYTAlVTMB4XDTIzMTIyMDA5MjgzN1oXDTI0MTIxOTA5
           MjgzNlowgYwxGjAYBgoJkiaJk/IsZAEBDApNVUMyNjY4OTY5MTUwMwYDVQQDDCxB
           cHBsZSBEZXZlbG9wbWVudDogQWhtYWQgU2F0dGFyICg0NjdTTjQ5NTQyKTETMBEG
           A1UECwwKSzI4WEE4VEw5UjEVMBMGA1UECgwMQWhtYWQgU2F0dGFyMQswCQYDVQQG
           EwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPxdNNyZ3cgddMyd
           8Zzfu/DiJUpFG+wcxsFPl0SQQ81+ekMAjX2de19rlBZJ0BUbEv6Ru2pK9F7dss/Y
           Kp6QFoaD51bB3G480hheOVzHmCnF9/kAxwuaBr2WxK/VqHpSKJtTRgIHNAP9dstp
           3lBZ63eTQxVYG0xtk6GY6ugfW3sq3db+rxzJUxsLoHZL0gmn7EWaHbE0/MG6m311
           AFd+UdzPvitvSNsz9O/M1LiS4CM/RhXmMkfBgHW+c6rbB2f2XHibsI+79v23I1ma
           1VjMfigGeTQDBNteg6F6v9pvUO+eJGYfqjaF0b8o//Y7wLH6ZTGhQRzoz6HkRVtC
           aN7C6R8CAwEAAaOCAjgwggI0MAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUCf7A
           FZD5r2QKkhK5JihjDJfsp7IwcAYIKwYBBQUHAQEEZDBiMC0GCCsGAQUFBzAChiFo
           dHRwOi8vY2VydHMuYXBwbGUuY29tL3d3ZHJnMy5kZXIwMQYIKwYBBQUHMAGGJWh0
           dHA6Ly9vY3NwLmFwcGxlLmNvbS9vY3NwMDMtd3dkcmczMDQwggEeBgNVHSAEggEV
           MIIBETCCAQ0GCSqGSIb3Y2QFATCB/zCBwwYIKwYBBQUHAgIwgbYMgbNSZWxpYW5j
           ZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2Vw
           dGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQg
           Y29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlm
           aWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjA3BggrBgEFBQcCARYraHR0cHM6
           Ly93d3cuYXBwbGUuY29tL2NlcnRpZmljYXRlYXV0aG9yaXR5LzAWBgNVHSUBAf8E
           DDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUZprvGGUI2d4hmvXB6lEnoR583YAwDgYD
           VR0PAQH/BAQDAgeAMBMGCiqGSIb3Y2QGAQIBAf8EAgUAMBMGCiqGSIb3Y2QGAQwB
           Af8EAgUAMA0GCSqGSIb3DQEBCwUAA4IBAQBmErE42Xwo9miNJIqR/WIVX/LQJVGq
           u27dmtv0OE63qsYeO7+fQbpSTxh8BIrd784feFUgyOgjY+fgTQUardgfZoHbHR7q
           Z1ToCqZA6TBA6K3F4EzSP+huJaNvtbFoyo4y0qyoFlX6od1dN1EGV1aifp1czqYN
           zMRa3TbIc8gLQDSXWBdL40sIszjieVwb+1q4Z97ReGbo60MtD9dkoNMG4XOOjbZa
           bUnQmt7GGtQGhjMeFOv3979WZeM1g1///VA7wlxWyVaE341GK43FCOIhz4Hjba2M
           44HpfmdBmh6nppL8Gsdue3p3daZOYWD5q/67jfJiV5agzcbijVBq8hEq
           -----END CERTIFICATE-----
[        ] executing: openssl x509 -subject
[  +85 ms] "flutter create" took 237ms.
[   +3 ms] "foo." is not a valid Dart package name.
           
           The name should be all lowercase, with underscores to separate words, "just_like_this".Use only basic Latin letters and Arabic digits: [a-z0-9_].Also, make sure the name is a valid Dart identifier—that
it doesn't
           start with digits and isn't a reserved word.
           See https://dart.dev/tools/pub/pubspec#name for more information.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      CreateBase.projectName (package:flutter_tools/src/commands/create_base.dart:332:9)
           #2      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:316:62)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +253 ms] ensureAnalyticsSent: 252ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-arm64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by alihassan143** [comment]
@huycozy i don't know how but the issue is resolved in m project just cleaning cache i thinks its happened due to some cache issue
