### ISSUE TITLE
[Impeller] Support Vulkan YUV texture sampling for composition of video player frames.

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#142082]
I'm toying with migrating [`video_player_android`](https://github.com/flutter/packages/tree/8255fbed74465425a1ec06a1804225e705e29f52/packages/video_player/video_player_android) to the new consumer-agnostic `SurfaceProducer` API.

<details>

<summary>Patch</summary>

```diff
diff --git a/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java b/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
index 57fc1037c..f9557a494 100644
--- a/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
+++ b/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
@@ -50,7 +50,7 @@ final class VideoPlayer {
 
   private Surface surface;
 
-  private final TextureRegistry.SurfaceTextureEntry textureEntry;
+  private final TextureRegistry.SurfaceProducer textureProducer;
 
   private QueuingEventSink eventSink;
 
@@ -67,13 +67,13 @@ final class VideoPlayer {
   VideoPlayer(
       Context context,
       EventChannel eventChannel,
-      TextureRegistry.SurfaceTextureEntry textureEntry,
+      TextureRegistry.SurfaceProducer textureProducer,
       String dataSource,
       String formatHint,
       @NonNull Map<String, String> httpHeaders,
       VideoPlayerOptions options) {
     this.eventChannel = eventChannel;
-    this.textureEntry = textureEntry;
+    this.textureProducer = textureProducer;
     this.options = options;
 
     ExoPlayer exoPlayer = new ExoPlayer.Builder(context).build();
@@ -96,12 +96,12 @@ final class VideoPlayer {
   VideoPlayer(
       ExoPlayer exoPlayer,
       EventChannel eventChannel,
-      TextureRegistry.SurfaceTextureEntry textureEntry,
+      TextureRegistry.SurfaceProducer textureProducer,
       VideoPlayerOptions options,
       QueuingEventSink eventSink,
       DefaultHttpDataSource.Factory httpDataSourceFactory) {
     this.eventChannel = eventChannel;
-    this.textureEntry = textureEntry;
+    this.textureProducer = textureProducer;
     this.options = options;
     this.httpDataSourceFactory = httpDataSourceFactory;
 
@@ -186,7 +186,7 @@ final class VideoPlayer {
           }
         });
 
-    surface = new Surface(textureEntry.surfaceTexture());
+    surface = textureProducer.getSurface();
     exoPlayer.setVideoSurface(surface);
     setAudioAttributes(exoPlayer, options.mixWithOthers);
 
@@ -330,7 +330,7 @@ final class VideoPlayer {
     if (isInitialized) {
       exoPlayer.stop();
     }
-    textureEntry.release();
+    textureProducer.release();
     eventChannel.setStreamHandler(null);
     if (surface != null) {
       surface.release();
diff --git a/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java b/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
index c0c602793..41f48731d 100644
--- a/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
+++ b/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
@@ -119,11 +119,10 @@ public class VideoPlayerPlugin implements FlutterPlugin, AndroidVideoPlayerApi {
   }
 
   public @NonNull TextureMessage create(@NonNull CreateMessage arg) {
-    TextureRegistry.SurfaceTextureEntry handle =
-        flutterState.textureRegistry.createSurfaceTexture();
+    TextureRegistry.SurfaceProducer producer = flutterState.textureRegistry.createSurfaceProducer();
     EventChannel eventChannel =
         new EventChannel(
-            flutterState.binaryMessenger, "flutter.io/videoPlayer/videoEvents" + handle.id());
+            flutterState.binaryMessenger, "flutter.io/videoPlayer/videoEvents" + producer.id());
 
     VideoPlayer player;
     if (arg.getAsset() != null) {
@@ -138,7 +137,7 @@ public class VideoPlayerPlugin implements FlutterPlugin, AndroidVideoPlayerApi {
           new VideoPlayer(
               flutterState.applicationContext,
               eventChannel,
-              handle,
+              producer,
               "asset:///" + assetLookupKey,
               null,
               new HashMap<>(),
@@ -149,15 +148,15 @@ public class VideoPlayerPlugin implements FlutterPlugin, AndroidVideoPlayerApi {
           new VideoPlayer(
               flutterState.applicationContext,
               eventChannel,
-              handle,
+              producer,
               arg.getUri(),
               arg.getFormatHint(),
               httpHeaders,
               options);
     }
-    videoPlayers.put(handle.id(), player);
+    videoPlayers.put(producer.id(), player);
 
-    return new TextureMessage.Builder().setTextureId(handle.id()).build();
+    return new TextureMessage.Builder().setTextureId(producer.id()).build();
   }
 
   public void dispose(@NonNull TextureMessage arg) {
```

</details>

While I'm not currently focused on the `HardwareBuffer`/`ImageReader` code path, it crashes at HEAD:

```txt
E/flutter (17339): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.lang.IllegalArgumentException: The image dimensions must be positive, IllegalArgumentException, Cause: null, Stacktrace: java.lang.IllegalArgumentException: The image dimensions must be positive
E/flutter (17339):      at android.media.ImageReader.initializeImageReader(ImageReader.java:319)
E/flutter (17339):      at android.media.ImageReader.<init>(ImageReader.java:363)
E/flutter (17339):      at android.media.ImageReader.<init>(Unknown Source:0)
E/flutter (17339):      at android.media.ImageReader$Builder.build(ImageReader.java:1093)
E/flutter (17339):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.createImageReader33(FlutterRenderer.java:658)
E/flutter (17339):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.createImageReader(FlutterRenderer.java:678)
E/flutter (17339):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.maybeCreateReader(FlutterRenderer.java:568)
E/flutter (17339):      at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.getSurface(FlutterRenderer.java:519)
E/flutter (17339):      at io.flutter.plugins.videoplayer.VideoPlayer.setUpVideoPlayer(VideoPlayer.java:189)
```

I'm going to overlook this for the moment and focus on the surface-texture code path, but filing for posterity.

/cc @johnmccutchan

**Comment by matanlurey** [comment]
There is a trivial but not necessarily correct fix:

```diff
diff --git a/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java b/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java
index e6dacdf6fa1..c715e207559 100644
--- a/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java
+++ b/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java
@@ -416,8 +416,8 @@ public class FlutterRenderer implements TextureRegistry {
     private boolean released;
     private boolean ignoringFence = false;
 
-    private int requestedWidth = 0;
-    private int requestedHeight = 0;
+    private int requestedWidth = 1;
+    private int requestedHeight = 1;
```

The problem is creating an 0x0 `ImageReader`, and it looks like lifecycle wise we don't know the correct size of the texture until _after_ creating one. Maybe that's something we can fix better though, I'll keep looking at it.

With the above patch, Skia + ImageReader passes. Impeller has a segfault:

```txt
E/goldfish_vulkan(19160): exportSyncFdForQSRILocked: Failed to dup() QSRI sync fd : sterror: Bad file descriptor errno: 9
E/ImageReaderSurfaceProducer(19160): acquireLatestImage image's fence was never signalled.
E/flutter (19160): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
E/flutter (19160): --- Vulkan Debug Report  ----------------------------------------
E/flutter (19160): |                Severity: Error
E/flutter (19160): |                    Type: { Validation }
E/flutter (19160): |                 ID Name: VUID-VkImageCreateInfo-pNext-02397
E/flutter (19160): |               ID Number: -892915494
E/flutter (19160): |       Queue Breadcrumbs: [NONE]
E/flutter (19160): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter (19160): |         Related Objects: Device [497961051392] [ImpellerDevice]
E/flutter (19160): |                 Trigger: Validation Error: [ VUID-VkImageCreateInfo-pNext-02397 ] Object 0: handle = 0x73f0caa500, name = ImpellerDevice, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xcac730da | vkCreateImage(): VkImageCreateInfo struct has a chained VkExternalFormatANDROID struct with non-zero externalFormat, but usage includes bits (0x84) other than VK_IMAGE_USAGE_SAMPLED_BIT. The Vulkan spec states: If the pNext chain includes a VkExternalFormatANDROID structure whose externalFormat member is not 0, usage must not include any usages except VK_IMAGE_USAGE_SAMPLED_BIT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageCreateInfo-pNext-02397)
E/flutter (19160): -----------------------------------------------------------------
E/flutter (19160): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
E/flutter (19160): --- Vulkan Debug Report  ----------------------------------------
E/flutter (19160): |                Severity: Error
E/flutter (19160): |                    Type: { Validation }
E/flutter (19160): |                 ID Name: VUID-VkImageCreateInfo-pNext-00990
E/flutter (19160): |               ID Number: 1181525669
E/flutter (19160): |       Queue Breadcrumbs: [NONE]
E/flutter (19160): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter (19160): |         Related Objects: Device [497961051392] [ImpellerDevice]
E/flutter (19160): |                 Trigger: Validation Error: [ VUID-VkImageCreateInfo-pNext-00990 ] Object 0: handle = 0x73f0caa500, name = ImpellerDevice, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x466ca6a5 | vkCreateImage(): The handle type (VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID), format (VK_FORMAT_UNDEFINED), type (VK_IMAGE_TYPE_2D), tiling (VK_IMAGE_TILING_OPTIMAL), usage (VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT), flags (VkImageCreateFlags(0)) is not supported combination of parameters and vkGetPhysicalDeviceImageFormatProperties2 returned back VK_ERROR_FORMAT_NOT_SUPPORTED. The Vulkan spec states: If the pNext chain includes a VkExternalMemoryImageCreateInfo structure, its handleTypes member must only contain bits that are also in VkExternalImageFormatProperties::externalMemoryProperties.compatibleHandleTypes, as returned by vkGetPhysicalDeviceImageFormatProperties2 with format, imageType, tiling, usage, and flags equal to those in this structure, and with a VkPhysicalDeviceExternalImageFormatInfo structure included in the pNext chain, with a handleType equal to any one of the handle types specified in VkExternalMemoryImageCreateInfo::handleTypes (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageCreateInfo-pNext-00990)
E/flutter (19160): -----------------------------------------------------------------
E/flutter (19160): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
E/flutter (19160): --- Vulkan Debug Report  ----------------------------------------
E/flutter (19160): |                Severity: Error
E/flutter (19160): |                    Type: { Validation }
E/flutter (19160): |                 ID Name: VUID-vkAllocateMemory-pAllocateInfo-01714
E/flutter (19160): |               ID Number: -764142661
E/flutter (19160): |       Queue Breadcrumbs: [NONE]
E/flutter (19160): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter (19160): |         Related Objects: Device [497961051392] [ImpellerDevice]
E/flutter (19160): |                 Trigger: Validation Error: [ VUID-vkAllocateMemory-pAllocateInfo-01714 ] Object 0: handle = 0x73f0caa500, name = ImpellerDevice, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd2741bbb | vkAllocateMemory: attempting to allocate memory type 1, which is not a valid index. Device only advertises 1 memory types. The Vulkan spec states: pAllocateInfo->memoryTypeIndex must be less than VkPhysicalDeviceMemoryProperties::memoryTypeCount as returned by vkGetPhysicalDeviceMemoryProperties for the VkPhysicalDevice that device was created from (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAllocateMemory-pAllocateInfo-01714)
E/flutter (19160): -----------------------------------------------------------------
E/flutter (19160): [ERROR:flutter/impeller/renderer/backend/vulkan/android_hardware_buffer_texture_source_vk.cc(142)] vkAllocateMemory failed : -9
F/flutter (19160): [FATAL:flutter/impeller/renderer/backend/vulkan/android_hardware_buffer_texture_source_vk.cc(194)] Check failed: IsValid(). 
```

**Comment by matanlurey** [comment]
@johnmccutchan Here are some reproduction instructions for you:

1. Navigate to [`packages/packages/video_player/video_player_android`](https://github.com/flutter/packages/tree/main/packages/video_player/video_player_android).
2. Apply the following patch:
```diff
diff --git a/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java b/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
index 57fc1037c..f9557a494 100644
--- a/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
+++ b/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
@@ -50,7 +50,7 @@ final class VideoPlayer {
 
   private Surface surface;
 
-  private final TextureRegistry.SurfaceTextureEntry textureEntry;
+  private final TextureRegistry.SurfaceProducer textureProducer;
 
   private QueuingEventSink eventSink;
 
@@ -67,13 +67,13 @@ final class VideoPlayer {
   VideoPlayer(
       Context context,
       EventChannel eventChannel,
-      TextureRegistry.SurfaceTextureEntry textureEntry,
+      TextureRegistry.SurfaceProducer textureProducer,
       String dataSource,
       String formatHint,
       @NonNull Map<String, String> httpHeaders,
       VideoPlayerOptions options) {
     this.eventChannel = eventChannel;
-    this.textureEntry = textureEntry;
+    this.textureProducer = textureProducer;
     this.options = options;
 
     ExoPlayer exoPlayer = new ExoPlayer.Builder(context).build();
@@ -96,12 +96,12 @@ final class VideoPlayer {
   VideoPlayer(
       ExoPlayer exoPlayer,
       EventChannel eventChannel,
-      TextureRegistry.SurfaceTextureEntry textureEntry,
+      TextureRegistry.SurfaceProducer textureProducer,
       VideoPlayerOptions options,
       QueuingEventSink eventSink,
       DefaultHttpDataSource.Factory httpDataSourceFactory) {
     this.eventChannel = eventChannel;
-    this.textureEntry = textureEntry;
+    this.textureProducer = textureProducer;
     this.options = options;
     this.httpDataSourceFactory = httpDataSourceFactory;
 
@@ -186,7 +186,7 @@ final class VideoPlayer {
           }
         });
 
-    surface = new Surface(textureEntry.surfaceTexture());
+    surface = textureProducer.getSurface();
     exoPlayer.setVideoSurface(surface);
     setAudioAttributes(exoPlayer, options.mixWithOthers);
 
@@ -330,7 +330,7 @@ final class VideoPlayer {
     if (isInitialized) {
       exoPlayer.stop();
     }
-    textureEntry.release();
+    textureProducer.release();
     eventChannel.setStreamHandler(null);
     if (surface != null) {
       surface.release();
```
3. Navigate to `video_player_android/example`
4. Run with a local engine:
```shell
$ flutter run \
  --local-engine-host=$ENGINE/out/host_debug_unopt_arm64 \
  --local-engine=$ENGINE/out/android_debug_unopt_arm64
```

**Comment by johnmccutchan** [comment]
Updating for posterity:

I took Matan's patch and started hacking on making this work with Vulkan. I only managed to create more validation check failures not fewer.

I got something to render (incorrectly) and not crash but we need to wire up support for https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_sampler_ycbcr_conversion.html to handle the video player format.

**Comment by johnmccutchan** [comment]
@bdero This is the Vulkan-specific bug around video player support for Impeller Android

**Comment by bdero** [comment]
Continuing our discussion starting from https://github.com/flutter/flutter/issues/141636#issuecomment-1932720229:
> I'm confused We've had external texture support for Vulkan checked-in for months: See https://github.com/flutter/engine/blob/main/impeller/renderer/backend/vulkan/android_hardware_buffer_texture_source_vk.h

@johnmccutchan Where are the spot(s) in the codebase where we're forming the DisplayList image for external textures and asking Impeller to render them? Or does it not work similarly to the OpenGL route in the Android embedder?

I figured this would be in the patch you mentioned when you said this in the other issue, but I might have that wrong:
> I took Matan's patch and started hacking on making this work with Vulkan. I only managed to create more validation check failures not fewer.

**Comment by johnmccutchan** [comment]
Here is where we make DisplayList calls:

https://github.com/flutter/engine/blob/main/shell/platform/android/image_external_texture_vk.cc

**Comment by johnmccutchan** [comment]
The patch I'm talking about is above is for the video_player plugin and you can see it [here](https://github.com/flutter/flutter/issues/142082#issuecomment-1912955858)

Applying that patch and following Matan's suggestions will lead to validation errors/crashes when run under Vulkan.

**Comment by chinmaygarde** [comment]
[The patch I had to apply was slightly different](https://github.com/flutter/flutter/files/14289583/migrate.patch). The original missed a file. But I see the errors now.

**Comment by chinmaygarde** [comment]
Scoped out what was necessary to get this over the finish line. I've summarized it below.

* Frames from the video player are imported as Android Hardware Buffer texture sources.
* These sources are in a YUV format that we don't currently understand and have difficulty binding to. By bind, I mean import a Android Hardware Buffer as a Vulkan image. `AndroidHardwareBufferTextureSourceVK` needs to be patched to support this. These textures are not from our own allocators.
* Having these textures as Vulkan images is necessary but not sufficient since our shaders can't sample from them.
* Samplers need information about the format of these (multi-planar) images as well as additional information about how to sample from them.
* When Impeller attempts to sample from an AHB backed texture, we must create a special sampler for the shaders to use (`vkCreateSamplerYcbcrConversion` thats tacked onto the sampler-create-info). These variants must be stored in their respective sampler libraries for later reference.
* In the shaders, the samplers look like regular `sampler2D`s and the the YUV to RGB conversion happens appropriately.

The necessary utilities are in [`VK_KHR_sampler_ycbcr_conversion`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_sampler_ycbcr_conversion.html) which is core in 1.1 behind a capability check.

Seems straightforward if tedious which I suppose is par for the course with Vulkan. Let me know if I've missed anything or if you have any additional context. Going to burn down this list next.

**Comment by johnmccutchan** [comment]
@chinmaygarde

This sounds correct to me.

I got as far as realizing we needed to wire up support for `[VK_KHR_sampler_ycbcr_conversion](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_sampler_ycbcr_conversion.html)` in `AndroidHardwareBufferTextureSourceVK` and then realized I was not the right person to be writing this code :)

**Comment by johnmccutchan** [comment]
> * These sources are in a YUV format that we don't currently understand and have difficulty binding to. By bind, I mean import a Android Hardware Buffer as a Vulkan image. `AndroidHardwareBufferTextureSourceVK` needs to be patched to support this. These textures are not from our own allocators.


Just to be clear `AndroidHardwareBufferTextureSourceVK` already suports importing Android Hardware Buffers as Vulkan images. It just doesn't handle the YUV format case correctly.

**Comment by bdero** [comment]
Thanks for taking this @chinmaygarde ! 🙇‍♂️ 

One potentially easier stopgap route to unblock would be to do what we do for iOS and use the YUV->RGB filter when forming the DL image, but I haven't scoped it out: https://github.com/flutter/flutter/issues/141636#issuecomment-1928781004
