### ISSUE TITLE
No interface method anyMatch(Lj$/util/function/Predicate;)Z in class Lj$/util/stream/Stream

### ISSUE THREAD

**Issue by ntaworking** [flutter/flutter#142096]
### Steps to reproduce

Just run app.

### Expected results

Don't occur error.

### Actual results

Occur error.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/102949116/bdecf985-e882-480d-95b5-81534c17a635)

</details>

### Logs

```
Fatal Exception: java.lang.NoSuchMethodError: No interface method anyMatch(Lj$/util/function/Predicate;)Z in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~i0GoKASwlDXSx_godYytgA==/androidx.test.tools.crawler-kndEwteQh3hZ2moVnBwEEQ==/base.apk!classes2.dex)
       at io.flutter.embedding.android.j.B(:48)
       at io.flutter.embedding.android.j.n(:263)
       at io.flutter.embedding.android.d.s(:130)
       at io.flutter.embedding.android.c.D(:20)
       at io.flutter.embedding.android.c.onCreate(:31)
       at android.app.Activity.performCreate(Activity.java:8342)
       at android.app.Activity.performCreate(Activity.java:8321)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7918)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.0 23A344 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by ntaworking** [comment]
@dam-ease Sorry for mention. Please help!

**Comment by dam-ease** [comment]
Hello @ntaworking.
Thanks for filing this.
Does this happen running the default counter app, if not, Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

**Comment by camsim99** [comment]
Closing as a duplicate https://github.com/flutter/flutter/issues/141949; will post future updates there!
