### ISSUE TITLE
NullPointerException signInWithCustomToken.

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#14208]
This is a plugin problem, right?
```
W/BiChannelGoogleApi(18413): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms
D/FirebaseAuth(18413): Notifying id token listeners about user ( K6KxjCzEPaTMX7FI801vgDfeX333 ).
D/FirebaseApp(18413): Notifying auth state listeners.
D/FirebaseApp(18413): Notified 0 auth state listeners.
D/FirebaseAuth(18413): Notifying auth state listeners about user ( K6KxjCzEPaTMX7FI801vgDfeX333 ).
D/AndroidRuntime(18413): Shutting down VM
E/AndroidRuntime(18413): FATAL EXCEPTION: main
E/AndroidRuntime(18413): Process: com.communup.dev, PID: 18413
E/AndroidRuntime(18413): java.lang.NullPointerException: null value in entry: uid=null
E/AndroidRuntime(18413): 	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
E/AndroidRuntime(18413): 	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49)
E/AndroidRuntime(18413): 	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:122)
E/AndroidRuntime(18413): 	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:198)
E/AndroidRuntime(18413): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.userInfoToMap(FirebaseAuthPlugin.java:312)
E/AndroidRuntime(18413): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.mapFromUser(FirebaseAuthPlugin.java:330)
E/AndroidRuntime(18413): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.access$000(FirebaseAuthPlugin.java:24)
E/AndroidRuntime(18413): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$SignInCompleteListener.onComplete(FirebaseAuthPlugin.java:302)
E/AndroidRuntime(18413): 	at com.google.android.gms.tasks.zzf.run(Unknown Source)
E/AndroidRuntime(18413): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(18413): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(18413): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(18413): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/AndroidRuntime(18413): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18413): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/AndroidRuntime(18413): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by tinder-paulblakely** [comment]
I'm also seeing this issue, upon successfully logging in with email + password:
```
D/FirebaseInstanceId(19565): topic sync succeeded
D/FirebaseAuth(19565): Notifying id token listeners about user ( vOdLnP5p6QQXC8ra5RgH77jMXpp1 ).
D/FirebaseAuth(19565): Notifying auth state listeners about user ( vOdLnP5p6QQXC8ra5RgH77jMXpp1 ).
D/FirebaseApp(19565): Notifying auth state listeners.
D/FirebaseApp(19565): Notified 0 auth state listeners.
D/AndroidRuntime(19565): Shutting down VM
E/AndroidRuntime(19565): FATAL EXCEPTION: main
E/AndroidRuntime(19565): Process: com.callboard, PID: 19565
E/AndroidRuntime(19565): java.lang.NullPointerException: null value in entry: uid=null
E/AndroidRuntime(19565): 	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
E/AndroidRuntime(19565): 	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49)
E/AndroidRuntime(19565): 	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:122)
E/AndroidRuntime(19565): 	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:198)
E/AndroidRuntime(19565): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.userInfoToMap(FirebaseAuthPlugin.java:422)
E/AndroidRuntime(19565): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.mapFromUser(FirebaseAuthPlugin.java:440)
E/AndroidRuntime(19565): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.access$000(FirebaseAuthPlugin.java:25)
E/AndroidRuntime(19565): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$SignInCompleteListener.onComplete(FirebaseAuthPlugin.java:375)
E/AndroidRuntime(19565): 	at com.google.android.gms.tasks.zzj.run(Unknown Source:23)
E/AndroidRuntime(19565): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(19565): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19565): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(19565): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(19565): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19565): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(19565): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by carlosjs23** [comment]
The problem still occurs to me only with the signInWithCustomToken method, the app crash but when I open it again the user data is saved so I can get it with FirebaseAuth.currentUser().

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by tinder-paulblakely** [comment]
To respond to my above comment: I retried last night, actually, and somewhere between `firebase_auth: 0.5.12` and `firebase_auth: 0.5.15` this appears to have been fixed. My comment related to `signInWithEmailAndPassword`, so OP's issue may still exist.

**Comment by zoechi** [comment]
Duplicate of #13899

**Comment by kroikie** [comment]
@long1eu

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/909. Any further collaboration will be done there.
