### ISSUE TITLE
An error occurred while using "dart run jnigen --config jnigen.yaml" in flutter plugin

### ISSUE THREAD

**Issue by wang409205743** [flutter/flutter#142122]
### Steps to reproduce

1. execute “dart pub add jni dev:jnigen”  command.
2. add jnigen.yaml in flutter plugin
3.  execute "dart run jnigen --config jnigen.yaml" 

### Actual results

```
Unable to automatically generate binding files and error info:
:dart run jnigen --config jnigen.yaml

Building package executable... (2.4s)
Built jnigen:jnigen.
(jnigen) INFO: ApiSummarizer.jar exists. Skipping build..
(jnigen) INFO: trying to obtain gradle dependencies [getReleaseCompileClasspath]...
(jnigen) INFO: Restoring build scripts
Unhandled exception:


gradle exited with status 1
. This can be because the Android build is not yet cached. Please run `flutter build apk` in ./ and try again

#0      AndroidSdkTools._runGradleStub (package:jnigen/src/tools/android_sdk_tools.dart:207:7)
#1      AndroidSdkTools.getGradleClasspaths (package:jnigen/src/tools/android_sdk_tools.dart:144:7)
#2      getSummary (package:jnigen/src/summary/summary.dart:136:34)
#3      generateJniBindings (package:jnigen/src/generate_bindings.dart:32:21)
<asynchronous suspension>

```
### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->
Building package executable... (2.4s)
Built jnigen:jnigen.
(jnigen) INFO: ApiSummarizer.jar exists. Skipping build..
(jnigen) INFO: trying to obtain gradle dependencies [getReleaseCompileClasspath]...
(jnigen) INFO: Restoring build scripts
Unhandled exception:


gradle exited with status 1
. This can be because the Android build is not yet cached. Please run `flutter build apk` in ./ and try again

#0      AndroidSdkTools._runGradleStub (package:jnigen/src/tools/android_sdk_tools.dart:207:7)
#1      AndroidSdkTools.getGradleClasspaths (package:jnigen/src/tools/android_sdk_tools.dart:144:7)
#2      getSummary (package:jnigen/src/summary/summary.dart:136:34)
#3      generateJniBindings (package:jnigen/src/generate_bindings.dart:32:21)
<asynchronous suspension>

</details>


### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->
[✓] Flutter (Channel stable, 3.16.3, on macOS 13.5.2 22G91 darwin-arm64 (Rosetta), locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[✓] Connected device (3 available)
[!] Network resources                   
    ✗ A network error occurred while checking "https://storage.googleapis.com/": Connection reset by peer
    ✗ An HTTP error occurred while checking "https://maven.google.com/": Proxy failed to establish tunnel (503 Service Unavailable)
```

</details>

**Comment by darshankawar** [comment]
@wang409205743 
I think this need to be reported in dedicated repo: https://github.com/dart-lang/native/issues
See [this](https://github.com/dart-lang/native/issues/593) similar issue for your reference.

Closing from here.
