### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by thanhdt1998** [flutter/flutter#142105]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#6      _readFileContent (package:flutter_tools/src/flutter_plugins.dart:275:35)
#7      _writeFlutterPluginsList (package:flutter_tools/src/flutter_plugins.dart:221:47)
#8      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1099:24)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:359:5)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:368:9)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
```
```
[33m[!][39m Flutter (Channel stable, 3.16.2, on macOS 14.1 23B74 darwin-arm64, locale en-VN)
    [32m•[39m Flutter version 3.16.2 on channel stable at /Users/dev/fvm/versions/3.16.2
    [33m![39m Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.3/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dev/fvm/versions/3.16.2. Consider adding /Users/dev/fvm/versions/3.16.2/bin to
      the front of your path.
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 9e1c857886 (8 weeks ago), 2023-11-30 11:51:18 -0600
    [32m•[39m Engine revision cf7a9d0800
    [32m•[39m Dart version 3.2.2
    [32m•[39m DevTools version 2.28.3
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/dev/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/dev/Library/Android/sdk
    [32m•[39m ANDROID_SDK_ROOT = /Users/dev/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.0.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15A507
    [32m•[39m CocoaPods version 1.12.0

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.80.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m MI 8 (mobile)                      • 360dae46                                 • android-arm64  • Android 10 (API 29)
    [32m•[39m Dang Trong Thanh’s iPhone (mobile) • 5f8134ee123858d3676880a030d104696c0a3335 • ios            • iOS 15.5 19F77
    [32m•[39m macOS (desktop)                    • macos                                    • darwin-arm64   • macOS 14.1 23B74
      darwin-arm64
    [32m•[39m Chrome (web)                       • chrome                                   • web-javascript • Google Chrome
      113.0.5672.126

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 0.0.7
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: true
**Android package**: com.example.ys_play
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null

**Comment by thanhdt1998** [comment]
Duplicate issue
https://github.com/flutter/flutter/issues/65021
