### ISSUE TITLE
App crashes on Nexus 6P with some gomobile code

### ISSUE THREAD

**Issue by rusenask** [flutter/flutter#14231]
## Steps to Reproduce

When I add a module created via gomobile bind it crashes on my Nexus 6P phone with an error, logs attached.

When I create an emulator of the same phone, it works.

Is it because of the android-arm vs android-x86? Or is there something wrong with my phone?

```
➜  example git:(master) ✗ flutter devices
2 connected devices:

Android SDK built for x86 • emulator-5554    • android-x86 • Android 8.1.0 (API 27) (emulator)
Nexus 6P                  • ENU7N15A27000419 • android-arm • Android 8.1.0 (API 27)
```

## Logs

```
01-23 15:52:17.515 32415-32415/? I/zygote64: Late-enabling -Xcheck:jni
01-23 15:52:17.689 32415-32415/com.sebible.fluttergoexample D/AndroidRuntime: Shutting down VM
01-23 15:52:17.692 32415-32415/com.sebible.fluttergoexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.sebible.fluttergoexample, PID: 32415
                                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sebible.fluttergoexample-mBNMHjAnYLLgDecVAq3R9g==/base.apk"],nativeLibraryDirectories=[/data/app/com.sebible.fluttergoexample-mBNMHjAnYLLgDecVAq3R9g==/lib/arm64, /data/app/com.sebible.fluttergoexample-mBNMHjAnYLLgDecVAq3R9g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
                                                                                  at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                                  at java.lang.System.loadLibrary(System.java:1657)
                                                                                  at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:152)
                                                                                  at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:137)
                                                                                  at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:20)
                                                                                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
                                                                                  at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

## Flutter Doctor

```

[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-GB, channel alpha)
    • Flutter at /Users/karolisrusenas/Projects/flutter
    • Framework revision 8f65fec5f5 (6 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/karolisrusenas/Library/Android/sdk
    • Android NDK at /Users/karolisrusenas/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/karolisrusenas/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

**Comment by rusenask** [comment]
Hi, thanks! My confidence in this is increasing :) 

Release APK looks like this:

![screen shot 2018-01-23 at 22 28 59](https://user-images.githubusercontent.com/9080105/35304648-2d07137c-008e-11e8-8f78-8e5efa25f53e.png)

I guess that arm64-v8a shouldn't be there, right?

**Comment by rmtmckenzie** [comment]
Yeah. Eventually they need to actually fix this properly but for now making sure that doesn't get included in the apk should let it run properly =)

**Comment by rusenask** [comment]
With 
```
android {
 ...
    packagingOptions {
        exclude 'lib/arm64-v8a/libgojni.so'
        exclude 'lib/x86/libgojni.so'
        exclude 'lib/x86_64/libgojni.so'
    }
}
```

it works, yay! Any suggestions how to keep same configuration when working with both emulator and phone? Or just comment/uncomment excluded libs?

**Comment by rmtmckenzie** [comment]
You shouldn't have to ignore lib/x86 or lib/x86_64 to get it to work on a mobile device. arm64_v8a is really the culprit here; that is picked up first as your phone supports v8a (and I can only assume that later versions are better considering its a later revision? but not an expert), and then it continues to look for other native libraries of the same ABI.  When you exclude the v8a folder, it looks for other compatible ABIs (i.e. v7a) and then when the java vm loads any library it will look there. Having x86 and x86_64 won't cause any problems because your ARM phone will never try to load from x86. (And vice-versa - the x86 or x86_64 emulator will never try to load the ARM libraries). 

Hope that makes sense =)

**Comment by gedw99** [comment]
I also hit this problem. So +1 for the remedy

**Comment by jonahwilliams** [comment]
The listed ABI support is included in https://flutter.dev/docs/deployment/android#build-an-app-bundle . There is no other remediation we could make here that seems reasonable.
