### ISSUE TITLE
Hot reload crashes with multiple views

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#142480]
It crashes on this line because `_ancestorRenderObjectElement` is null:

https://github.com/flutter/flutter/blob/1af09dde125c3fc1c4ec3012d463e1b2914307b2/packages/flutter/lib/src/widgets/framework.dart#L6539

I suspect, this crash is covering up another bug.

**Comment by goderbauer** [comment]
Replacing the `!` with`?` gives us the following more interesting error:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.
The ParentDataWidget LayoutId-[<_ScaffoldSlot.body>](id: _ScaffoldSlot.body) wants to apply
ParentData of type MultiChildLayoutParentData to a RenderObject, which has not been set up to
receive any ParentData.
Usually, this means that the LayoutId widget has the wrong ancestor RenderObjectWidget. Typically,
LayoutId widgets are placed directly inside CustomMultiChildLayout widgets.
The ownership chain for the RenderObject that received the incompatible parent data was:
  _RawView-[_DeprecatedRawViewKey FlutterView#1d4ba] ← View ← Window ← _ViewScope ←
_MultiChildComponentWidget ← ViewAnchor ← WindowedContextMenu ← KeyedSubtree-[GlobalKey#415f3] ←
_BodyBuilder ← MediaQuery ← ⋯

When the exception was thrown, this was the stack:
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:6538:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:6555:6)
#2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5857:15)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5533:14)
#4      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5859:15)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5533:14)
#6      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5859:15)
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5533:14)
#8      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5859:15)
#9      _MultiChildComponentElement.visitChildren (package:flutter/src/widgets/view.dart:689:16)
#10     ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5859:15)
#11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5533:14)
#12     ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5859:15)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5533:14)
#14     ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5859:15)
#15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5533:14)
#16     ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5859:15)
#17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5533:14)
#18     ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5859:15)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5533:14)
#20     ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5859:15)
#21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5533:14)
#22     ParentDataElement._applyParentData (package:flutter/src/widgets/framework.dart:5862:5)
#23     ParentDataElement.notifyClients (package:flutter/src/widgets/framework.dart:5905:5)
#24     ProxyElement.updated (package:flutter/src/widgets/framework.dart:5820:5)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#27     Element.updateChildren (package:flutter/src/widgets/framework.dart:3974:32)
#28     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6922:17)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#32     ProxyElement.update (package:flutter/src/widgets/framework.dart:5810:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5644:11)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:5667:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5644:11)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:5667:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#46     ProxyElement.update (package:flutter/src/widgets/framework.dart:5810:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#49     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5644:11)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#51     StatefulElement.update (package:flutter/src/widgets/framework.dart:5667:5)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6769:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#57     ProxyElement.update (package:flutter/src/widgets/framework.dart:5810:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6769:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#62     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5644:11)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#64     StatefulElement.update (package:flutter/src/widgets/framework.dart:5667:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5644:11)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#69     StatefulElement.update (package:flutter/src/widgets/framework.dart:5667:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#73     ProxyElement.update (package:flutter/src/widgets/framework.dart:5810:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#77     ProxyElement.update (package:flutter/src/widgets/framework.dart:5810:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#81     ProxyElement.update (package:flutter/src/widgets/framework.dart:5810:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5644:11)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#86     StatefulElement.update (package:flutter/src/widgets/framework.dart:5667:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#90     ProxyElement.update (package:flutter/src/widgets/framework.dart:5810:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#93     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5644:11)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#95     StatefulElement.update (package:flutter/src/widgets/framework.dart:5667:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3825:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5506:16)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5644:11)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:5197:7)
#100    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#101    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:993:21)
#102    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#103    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#104    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#105    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1034:7)
#109    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

It appears that `LayoutId` wants to apply its parent data to a renderobject in a different view. Likely indicating that there is a problem with how the ParentData widget walks the widget tree to find the render object it targets. It should only walk the part of the widget tree that's backed by the same render tree and ignore branches that belong to a different render tree (or View).
