### ISSUE TITLE
Flutter "version" file in repo root is missing and being created then deleted by the tool on branches named master/main

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#142521]
### Steps to reproduce

I'm on the latest `master` (commit ccb2b4439a) and I noticed a number of things not working as expected in VS Code. It turns out, Dart-Code thinks I'm on Flutter version 0.0.0 and is therefore disabling all functionality that requires a specific Flutter version. This seems to be because I don't have the `version` file in the repo root.

I found https://github.com/flutter/flutter/pull/133097 while searching which seems to describe the same issue, however I'm on a much newer version than that (cc @christopherfujino )

### Expected results

There should be a file named `version` in the root of the repository.

### Actual results

There is no file.

### Code sample

N/A

### Screenshots or Video

```
PS C:\Dev\Google\flutter> flutter --version
Flutter 3.19.0-13.0.pre.32 • channel master • git@github.com:DanTup/flutter.git
Framework • revision ccb2b4439a (5 hours ago) • 2024-01-30 14:59:24 +0800
Engine • revision 438e9b4d7d
Tools • Dart 3.4.0 (build 3.4.0-82.0.dev) • DevTools 2.31.0
PS C:\Dev\Google\flutter> ls

    Directory: C:\Dev\Google\flutter

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          30/01/2024    11:24                .github
d----          19/12/2023    12:02                .vscode
d----          19/12/2023    12:02                bin
d----          30/01/2024    11:24                dev
d----          19/12/2023    12:02                examples
d----          01/06/2023    20:01                packages
-a---          30/01/2024    11:24         187181 .ci.yaml
-a---          01/06/2023    20:01            858 .gitattributes
-a---          19/12/2023    12:02           2932 .gitignore
-a---          19/12/2023    12:02          11615 analysis_options.yaml
-a---          30/01/2024    11:24           4714 AUTHORS
-a---          19/12/2023    12:02           2939 CODE_OF_CONDUCT.md
-a---          30/01/2024    11:24            489 CODEOWNERS
-a---          30/01/2024    11:24          11619 CONTRIBUTING.md
-a---          30/01/2024    11:24           2035 dartdoc_options.yaml
-a---          01/06/2023    20:01           1731 flutter_console.bat
-a---          01/06/2023    20:01           1544 LICENSE
-a---          01/06/2023    20:01           1124 PATENT_GRANT
-a---          30/01/2024    11:24           7055 README.md
-a---          30/01/2024    11:24          27988 TESTOWNERS

PS C:\Dev\Google\flutter>
```

### Flutter Doctor output

```
PS C:\Dev\Google\flutter> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.19.0-13.0.pre.32, on Microsoft Windows [Version 10.0.22621.3007], locale en-GB)
    ! Warning: `dart` on your path resolves to C:\Dev\Tools\Dart\Stable\bin\dart.exe, which is not inside your current Flutter SDK checkout at
      C:\Dev\Google\flutter. Consider adding C:\Dev\Google\flutter\bin to the front of your path.
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.2)
[✓] VS Code (version 1.86.0-insider)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment]
This is very odd... I can repro running from source and added some `print`s, and it seems like it is creating the file:

```
PS C:\Dev\Google\flutter\packages\flutter_tools> ../../bin/dart .\bin\flutter_tools.dart --version; ls ../..
Ensuring version file (_FlutterVersionGit)!
Inside _FlutterVersionGit.ensureVersionFile
Writing 3.19.0-13.0.pre.32 to LocalFile: 'C:\Dev\Google\flutter\version' using ErrorHandlingFileSystem
Calling LocalFile("C:\Dev\Google\flutter\version").writeAsStringSync()
Calling LocalFile("C:\Dev\Google\flutter\bin\cache\flutter.version.json").writeAsStringSync()
Flutter 3.19.0-13.0.pre.32 • channel master • git@github.com:DanTup/flutter.git
Framework • revision ccb2b4439a (5 hours ago) • 2024-01-30 14:59:24 +0800
Engine • revision 438e9b4d7d
Tools • Dart 3.4.0 (build 3.4.0-82.0.dev) • DevTools 2.31.0
```

And nothing in the `delete` calls prints, so it doesn't seem like it's being deleted.

I'll try to debug a bit more shortly... This could be a big issue if widespread, because VS Code uses this version to switch quite a bit of Dart-Code functionality.

**Comment by DanTup** [comment]
@christopherfujino here is the issue:

```
Inside _FlutterVersionGit.ensureVersionFile
Writing 3.19.0-13.0.pre.32 to LocalFile: 'C:\Dev\Google\flutter\version' using ErrorHandlingFileSystem
Calling LocalFile("C:\Dev\Google\flutter\version").writeAsStringSync()
Exists now? true
Calling LocalFile("C:\Dev\Google\flutter\bin\cache\flutter.version.json").writeAsStringSync()
Exists now? true
Deleting the new version file!!!!!!
Deleting the legacy version file!!!!!!
```

The files are being deleted by:

https://github.com/flutter/flutter/blob/ccb2b4439a430d4a736bcb294ba8f00be79fc66c/packages/flutter_tools/lib/src/version.dart#L109

Stack trace is like:

```
#0      new FlutterVersion (package:flutter_tools/src/version.dart:111:26)
#1      FlutterVersion.fetchTagsAndGetVersion (package:flutter_tools/src/version.dart:178:12)
#2      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:65)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
```

It's created here on line 311 and then deleted because of the call on line 338:

![image](https://github.com/flutter/flutter/assets/1078012/daed28f7-eca7-40f6-a814-0bc0709d0d60)

Doesn't _seem_ to affect beta, but I haven't yet figured out why, since most of the code seems the same.

**Comment by DanTup** [comment]
Ok, the reason this doesn't happen on beta is because of this early exit, which prevents the constructor running that deletes the file:

https://github.com/flutter/flutter/blob/ccb2b4439a430d4a736bcb294ba8f00be79fc66c/packages/flutter_tools/lib/src/version.dart#L172-L174

So the issue is isolated to branches named `master`/`main`.

**Comment by darshankawar** [comment]
Thanks for the detailed report and analysis. Labeling this for tracking.

**Comment by eliasyishak** [comment]
@christopherfujino leaving to you for prioritizing

**Comment by DanTup** [comment]
Not sure if it's the same thing, but I just noticed that the GitHub actions are often failing the coverage step because the Flutter version is reported as 0.0.0-unknown:

![image](https://github.com/flutter/flutter/assets/1078012/fb847133-38e0-4300-aa2a-59b06a9d427c)

Example: https://github.com/flutter/flutter/actions/runs/8999603670/job/24722091985

**Comment by DanTup** [comment]
This came up again in https://github.com/Dart-Code/Dart-Code/issues/5226, where we were using old versions of DevTools page IDs because we thought we were on an old version of the Flutter SDK.

@christopherfujino @andrewkolos does anyone know why we have a difference in this path for master/main? If we remove the `if` statement quoted above (so that master/main did the same as other branches, and never triggered the delete), would anything break? 🤔

**Comment by christopherfujino** [comment]
> @christopherfujino @andrewkolos does anyone know why we have a difference in this path for master/main? If we remove the `if` statement quoted above (so that master/main did the same as other branches, and never triggered the delete), would anything break? 🤔

We have a difference on master/main because what we report as the version changes as new tags are added upstream. If we removed the if statement, once we cache the version, this would remain as long as you're on the same commit, even if we publish a beta from an OLDER commit, and our version should now reflect that it is AFTER the beta.

**Comment by DanTup** [comment]
Ah, gotcha. Should there be an `ensureVersionFile` call somewhere _after_ that `fetchTagsAndGetVersions()` then? Oddly, I can't see where `fetchTagsAndGetVersions()` (or the constructor it calls) actually fetches any tags (seems like it just calls `gitLog` 🤔).

**Comment by DanTup** [comment]
Some additional info I just noticed:

- running `flutter doctor` results in the file being deleted and not replaced
- running `flutter --version` results in the file being deleted and not replaced
- running `flutter --help` results in the file **remaining** (or **not** being deleted)

Seems like Dart-Code is triggering this sometimes when you have a Flutter SDK with no Dart SDK because we force it to initialize by calling `flutter doctor` (and showing the output to the user). If we call `flutter --help` afterwards, then we'll have a good version number, but it is slightly weird.

**Comment by christopherfujino** [comment]
> Some additional info I just noticed:
> 
> * running `flutter doctor` results in the file being deleted and not replaced
> * running `flutter --version` results in the file being deleted and not replaced
> * running `flutter --help` results in the file **remaining** (or **not** being deleted)
> 
> Seems like Dart-Code is triggering this sometimes when you have a Flutter SDK with no Dart SDK because we force it to initialize by calling `flutter doctor` (and showing the output to the user). If we call `flutter --help` afterwards, then we'll have a good version number, but it is slightly weird.

Let me carve out some time today to dig in a little bit. I'll take me a while to get back up to speed on all the convoluted logic here (I remember thinking I could implement this in a few days, but it actually took me weeks, I've already had to fix a bad bug, and clearly there's another one).

**Comment by DanTup** [comment]
Thanks! I implemented a few tweaks in Dart-Code (such as calling `flutter --help` directly after `flutter doctor` in the case where we force initialization) which I think will reduce the chance of hitting this, but it's pretty hacky and it'd be nice to remove them if it's not a ton of work here.

**Comment by christopherfujino** [comment]
Ahh, as I read this issue carefully, am I correct in understanding that dart-code is parsing `$FLUTTER_ROOT/version` in order to conditionally disable some features? If that is the case, the fix here is migrating to use `$FLUTTER_ROOT/bin/cache/flutter.version.json`.

I (mistakenly) thought that the only tool that was reading this was pub, which was migrated here: https://github.com/dart-lang/pub/pull/4113.

Does devtools also parse this file @kenzieschmoll ?

**Comment by DanTup** [comment]
Ah, that sounds reasonable. Currently we're just reading the version the same way for Dart and Flutter (Dart also has a `version`), but reading the JSON if it is there should work too. If it's only the "legacy" file being removed, this will remove the need for my other workaround too. I've filed https://github.com/Dart-Code/Dart-Code/issues/5231 about this.

**Comment by DanTup** [comment]
I've switched Dart-Code to reading the new JSON file first and just using the legacy `version` file if it fails to find (or parse a version from) the JSON file.

As such, I/Dart-Code doesn't care so much about this behaviour now - if this version file is considered legacy and shouldn't be used, this issue could be closed.

(although it may also be worth checking with @helin24 / @jwren whether IntelliJ uses the original file)

**Comment by DanTup** [comment]
> Ahh, as I read this issue carefully, am I correct in understanding that dart-code is parsing $FLUTTER_ROOT/version in order to conditionally disable some features? If that is the case, the fix here is migrating to use $FLUTTER_ROOT/bin/cache/flutter.version.json.

Today I noticed that this file is also not present in my Flutter checkout. Combined with the `version` file missing, that means Dart-Code is currently treated the Flutter version as unknown (and as 999.999 for all version checks).

If I run an invalid command like `flutter foo`, the file appears (as does the legacy one), but if I then run `flutter doctor`, the files both get deleted again.

So it seems that migrating to the new version file hasn't actually solved the problem.

**Comment by kenzieschmoll** [comment]
> I (mistakenly) thought that the only tool that was reading this was pub, which was migrated here: https://github.com/dart-lang/pub/pull/4113.
> 
> Does devtools also parse this file @kenzieschmoll ?

Late on the response here... but this is the only other place I am aware of. It looks like it is using the correct file path:
https://github.com/dart-lang/sdk/blob/master/pkg/dtd_impl/lib/src/service/unified_analytics_service.dart/#L158

**Comment by bkonyi** [comment]
I'm assuming this is still an issue @DanTup?

**Comment by bkonyi** [comment]
> Any progress? I think this is possibly also the cause of [#157627](https://github.com/flutter/flutter/issues/157627).

Nope, I haven't had a chance to look into this and probably won't for a while. I'm the only one on the tools team at the moment so I don't have cycles to investigate, I just didn't want this triaged issue to disappear into the void by leaving it unassigned.

**Comment by jwren** [comment]
Thank you @bkonyi!

**Comment by bkonyi** [comment]
> Thank you @bkonyi!

No problem! Sorry for the delay on this one!

**Comment by DanTup** [comment]
@bkonyi FYI I appear to still see this - I updated Dart-Code's E2E tests to use Flutter's master branch, but it ends up without a version file. `flutter doctor` shows `0.0.0-unknown` and `flutter create` fails with:

```
Run flutter pub get
Resolving dependencies...
Note: leak_tracker_flutter_testing is pinned to version 3.0.10 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

The current Flutter SDK version is 0.0.0-unknown.

Because every version of flutter_test from sdk depends on leak_tracker_flutter_testing >=2.0.3 which requires Flutter SDK version >=3.18.0-18.0.pre.54, flutter_test from sdk is forbidden.
So, because flutter_counter depends on flutter_test from sdk, version solving failed.
Failed to update packages.
```

The log is here:

https://github.com/Dart-Code/E2E-Tests/commit/de4289de6e974ccc6123f2fd2b21237911f1ee8b/checks

I'm fetching it with the GitHub action like this:

```
    - name: Checkout Flutter SDK
      uses: actions/checkout@v4
      with:
        repository: flutter/flutter
        path: flutter
        fetch-tags: true
```

**Comment by DanTup** [comment]
Hmm, seems like the issue is specific to how GitHub is cloning with `actions/checkout` because replacing that action with:

```yaml
    - name: Checkout Flutter SDK
      run: git clone https://github.com/flutter/flutter
```

Has resolved the issue. I'll stick with this instead.
