### ISSUE TITLE
Security Vulnerability: Unauthorized Exposure of Logs from Other Applications

### ISSUE THREAD

**Issue by vickyleu** [flutter/flutter#142683]
### Steps to reproduce

1. Install the Xianyu app [goofish](https://www.goofish.com/) on an iOS device (requires logging in with a Taobao account).

2. Create a new Flutter project.
   Select the iOS device as the target and run the application.
   Open the console and observe. On the iOS device, open the Xianyu app.

3. Navigate to the product details page.
   Go to the message page. Click on interactive messages.
   watch to the console during this process.

### Expected results

No logs from applications other than the currently active Flutter project should be visible in the console on the iOS device.

### Actual results

This represents a severe security concern, as unauthorized access to logs from other applications compromises user data privacy and violates the expected behavior of sandboxed environments on iOS. Immediate attention and action are required to address this issue and safeguard user information.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter: External:INoticePageListener, I:INoticePage
flutter: External:IMessageListViewListener, I:IMessageListView
flutter: publishUt exposureWithSpmCD action is MsgCard spmC is MsgCard spmD is 0 args is{source_mark: hermesXRealtime, material_id: 504212, source: HermesX, task_id: 1002261}
flutter: publishUt exposureWithSpmCD action is MsgCard spmC is MsgCard spmD is 1 args is{source_mark: hermesXRealtime, material_id: 504213, source: HermesX, task_id: 1002262}
flutter: getColorValue: ff999999
flutter: getColorValue: ffa3a3a3
flutter: getColorValue: ffa3a3a3
flutter: getColorValue: fffafafa
flutter: getColorValue: ff333333
flutter: publishUt exposureWithSpmCD action is Appear-Session spmC is Appear-Session spmD is 18 args is{user_id: xxxxxxxx, session_id: 32561712003, type: 1}
flutter: publishUt exposureWithSpmCD action is Appear-Session spmC is Appear-Session spmD is 19 args is{user_id: xxxxxxxx, session_id: 28560918628, type: 1}
flutter: publishUt ctrlClickedWithSpmCD action is Button-Refresh spmC is Refresh spmD is 1 args is{pageNumber: 1, rowsPerPage: 10, disableHierarchicalSort: 0, keyword: 思锐碳纤维, extraFilterValue: {"divisionList":[],"excludeMultiPlacesSellers":"0"}, fromSuggest: false, suggestBucketNum: 1, fromShade: false, shadeBucketNum: 39, fromKits: false, fromLeaf: false, bizFrom: home, userPositionJson: {"city":"深圳","province":"广东","district":"龙岗区"}, activeSearch: true, forceUseInputKeyword: false, fromFilter: false, resultListLastIndex: 0, forceUseTppRepair: false, searchReqFromPage: xyHome, searchTabType: SEARCH_TAB_MAIN, searchReqFromActivatePagePart: historyItem, relateResultPageNumber: 1, relateResultListLastIndex: 0, supportFlexFilter: true, abConfigs: {"isSearchResultKun":true,"isSearchActiveKun":true,"isSearchSugKun":false,"isPowerLayoutFlow":true,"isNewReminder":true,"reminderBucketId":"650816"}, api_name: mtop.taobao.idlemtopsearch.search, api_version: 1.0, searchKunBucketId:<…>
flutter: EVENT_UPDATE_REMINDER_DATA{userFollowRecordId: 0, iconClose: https://gw.alicdn.com/imgextra/i4/O1CN01mNANYf205XISSTnVW_!!6000000006798-2-tps-120-120.png, trackParams: {args: {bucket_id: 39, search_from_page: xyHome, rn: 29802160c0c74d48bfc32fc146ed414e, search_id: 7a865499c9e9e0747d8f6a827ee0d0f3, keyword: 思锐碳纤维}, arg1: EnterFishingButton, page: Page_xySearchResult}, newArrivalNums: 0, query: 思锐碳纤维, showSubscribeTips: false, icon: https://gw.alicdn.com/imgextra/i4/O1CN01PZ2zrC1vznsnB02C6_!!6000000006244-2-tps-168-168.png}
flutter: TagWrapperModel mount...
flutter: TagWrapperModel updateTagUtParam...search
flutter: TagWrapperModel mount...
flutter: TagWrapperModel updateTagUtParam...search

xxxxxxxx

Performing hot reload...
Syncing files to device iPhone13 Pro...
Reloaded 0 libraries in 285ms (compile: 76 ms, reload: 0 ms, reassemble: 64 ms).
flutter: External:INoticePageListener, I:INoticePage
flutter: External:IMessageListViewListener, I:IMessageListView
flutter: publishUt exposureWithSpmCD action is MsgCard spmC is MsgCard spmD is 0 args is{source_mark: hermesXRealtime, material_id: 504212, source: HermesX, task_id: 1002261}
flutter: publishUt exposureWithSpmCD action is MsgCard spmC is MsgCard spmD is 1 args is{source_mark: hermesXRealtime, material_id: 504213, source: HermesX, task_id: 1002262}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.16.8 on channel stable at /Volumes/Extra/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (2 weeks ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Volumes/Extra/Android/sdk/
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Volumes/Extra/Android/sdk/
    • Java binary at: /Volumes/Extra/JetBrains/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Volumes/Extra/JetBrains/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Volumes/Extra/JetBrains/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13763.5

[✓] Connected device (4 available)
    • BMH AN10 (mobile)     • XPC0220413019945          • android-arm64  •
      Android 12 (API 31)
    • iPhone13 Pro (mobile) • 00008110-00122DA63622801E • ios            • iOS
      17.3 21D50
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS
      14.2.1 23C71 darwin-arm64
    • Chrome (web)          • chrome                    • web-javascript •
      Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by moffatman** [comment]
I don't think there is any way for flutter tool to be more specific about which components' logs are shown when connecting to device for debugging in certain ways. (It just reads full system log and filters for the phrases `flutter` or `Runner`?). If there is private data in that log, it is the responsibility of that app to restrict what it prints.

But anyway, when plugged into iOS device in development mode like this, many things are possible beyond just reading system log. There isn't any case where information leaks between two apps within the device.

**Comment by huycozy** [comment]
@vickyleu Could you check if the logs also appear in `adb logcat` output? (I don't have a Taobao account to check this)

**Comment by vickyleu** [comment]
> @vickyleu Could you check if the logs also appear in `adb logcat` output? (I don't have a Taobao account to check this)

I checked and found the same issue on the Google Pixel 4a device. After running my Flutter project, I can see logs in the console of the "Run" panel [main.dart (Pixel 4a)] in Android Studio for any Flutter-based program. Similarly, the logs are visible in Android Logcat. It seems that, as mentioned by @moffatman, the Flutter tool is filtering logs with system tags "flutter" and "Runner," and the logs are not shared between the two programs.
😳 

Here is a portion of the logs from the Run panel 
```
I/flutter (14374): main(), args = []
I/flutter (14374): not small memory device
I/flutter (14374): use_dx_isolate_accelerate:false
I/flutter (14374): start method channel!
I/flutter (14374): update font
I/flutter (14374): MultiMediaManager init 11
I/flutter (14374): External:ILoginChangeListener, I:ILoginChange
I/flutter (14374): External:IMessageChangeListener, I:IMessageChange
I/flutter (14374): External:IMessageInfoChangeListener, I:IMessageInfoChange
I/flutter (14374): External:IMessageSendListener, I:IMessageSend
I/flutter (14374): External:ISessionChangeListener, I:ISessionChange
I/flutter (14374): External:ISessionInfoChangeListener, I:ISessionInfoChange
I/flutter (14374): External:IUserInfoChangeListener, I:IUserInfoChange
I/flutter (14374): External:IMessagePluginListener, I:IMessagePlugin
I/flutter (14374): External:IPushOperationHandlerListener, I:IPushOperationHandler
I/flutter (14374): External:IMessageNpsListener, I:IMessageNps
I/flutter (14374): External:IMessageRiskListener, I:IMessageRisk
I/flutter (14374): External:ISessionDataCenterListener, I:ISessionDataCenter
I/flutter (14374): External:IGroupSessionChangeListener, I:IGroupSessionChange
I/flutter (14374): External:IMessageUpgradeListener, I:IMessageUpgrade
I/flutter (14374): External:ICommentServiceListener, I:ICommentService
I/flutter (14374): External:ICommentSendListener, I:ICommentSend
I/flutter (14374): [PowerPlayer] ## Reset Global Native Player: TBPlayer
I/flutter (14374): ============= root engine init success ==============
I/flutter (14374): Zone caught an error:NoSuchMethodError: The getter 'iterator' was called on null.
I/flutter (14374): Receiver: null
I/flutter (14374): Tried calling: iterator
I/flutter (14374): #0      _GrowableList.addAll (dart:core-patch/growable_array.dart:318)
I/flutter (14374): #1      AppPerformance.initSwitch.<anonymous closure> (package:fish_config/src/app_config/app_performance.dart:64)
I/flutter (14374): #2      _rootRunUnary (dart:async/zone.dart:1399)
I/flutter (14374): #3      _CustomZone.runUnary (dart:async/zone.dart:1300)
I/flutter (14374): <asynchronous suspension>
I/flutter (14374): font family changing Roboto`
I/flutter (14374): #### isPerformanceUploadOpenStr: false
I/flutter (14374): mtop request fail, apiName:mtop.taobao.idlemessage.ab.get, errorCode:FAIL_BIZ_UNAUTHORIZED, errorMsg:这个Modulet需要登录!
I/flutter (14374): FunSwitch: {}
I/flutter (14374): mtop request fail, apiName:mtop.taobao.idlemessage.sessiontypes.gray, errorCode:FAIL_BIZ_UNAUTHORIZED, errorMsg:这个Modulet需要登录!
D/CrashReport(11599): [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.biz.b
D/CrashReport(11599): Uploading frequency will not be checked if SDK is in debug mode.
D/CrashReport(11599): [UserInfo] Upload user info(size: 2)
```

**Comment by huycozy** [comment]
@vickyleu 
Do these logs come from native apps? Is this possible to reproduce the issue without using 3rd app (Xianyu)?

```console
I/flutter (14374): External:ILoginChangeListener, I:ILoginChange
I/flutter (14374): External:IMessageChangeListener, I:IMessageChange
I/flutter (14374): External:IMessageInfoChangeListener, I:IMessageInfoChange
I/flutter (14374): External:IMessageSendListener, I:IMessageSend
I/flutter (14374): External:ISessionChangeListener, I:ISessionChange
I/flutter (14374): External:ISessionInfoChangeListener, I:ISessionInfoChange
I/flutter (14374): External:IUserInfoChangeListener, I:IUserInfoChange
....
```

I quote a part of Dan's [comment](https://github.com/flutter/flutter/issues/58611#issuecomment-645505527) here for more information:

>If you have shared sensitive info in your logs, anyone with access to your device will be able to read those logs. For example, if you plug your phone in, run several applications (Flutter, JetPack Compose, Regular Android, NDK Android, whatever) that print logs, and run adb logcat while running them, you will see all of the logs from all of those applications. This includes applications that you did not write, and may include release applications from the store if the author did not strip out logging as part of their release process.

I haven't tried checking this with Xcode's device console but it could be the same to Android Studio logcat.
