### ISSUE TITLE
[go_router] two Navigator.pop() calls drops the whole navigation stack inside StatefulShellRoute

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#142678]
### Steps to reproduce

1. Create a shell route.
2. Go to a shell branch, push a detail screen with context.push().
3. Show a modal bottomSheet (without any GoRoutes), then show a modal dialog (again, without a GoRouter).
4. Try to remove both with two Navigator.pop() calls in a modal dialog callback.

### Expected results

Before introducing StatefulShellBranch, it worked as expected, both modals were closed

### Actual results

It puts an app into the inconsistent state with a black screen, when no pages are in the navigation stack.

### Code sample

<details open><summary>Code sample</summary>

```dart
      StatefulShellBranch(
          routes: [
            GoRoute(
              path: '/wallet',
              name: RouteNames.wallet,
              builder: (context, state) => WalletScreen(),
              routes: [
                GoRoute(
                  path: 'exchange-coins-requests',
                  name: RouteNames.exchangeCoinsRequests,
                  redirect: loginRedirect,
                  pageBuilder: (context, state) => CupertinoPage(
                    child: ExchangeCoinsRequestsScreen(),
                  ),
                ),
           ]),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

ExchangeCoinsRequestTile
onTap:
<img width="662" alt="image" src="https://github.com/flutter/flutter/assets/12999702/857f79f7-08dc-490d-8d42-10c16e961e4e">

ExchangeActionsBottomSheet
onTap:
<img width="488" alt="image" src="https://github.com/flutter/flutter/assets/12999702/e07cb4f0-6465-4eef-9fe0-c099be019ada">

RequestRejectModal:
<img width="435" alt="image" src="https://github.com/flutter/flutter/assets/12999702/11904977-1f87-4bae-a2d0-4449b9ccfcab">

Bug Demo:

https://github.com/flutter/flutter/assets/12999702/61b034f8-f15c-4cd1-8205-9043a39e9482

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/flutter ( 7075): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:go_router/src/delegate.dart': Failed assertion: line 116 pos 7: 'currentConfiguration.isNotEmpty': You have popped the last page off of the stack, there are no pages left to show
E/flutter ( 7075): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 7075): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 7075): #2      GoRouterDelegate._debugAssertMatchListNotEmpty (package:go_router/src/delegate.dart:116:7)
E/flutter ( 7075): #3      GoRouterDelegate._completeRouteMatch.<anonymous closure> (package:go_router/src/delegate.dart:156:7)
E/flutter ( 7075): #4      GoRouterDelegate._completeRouteMatch (package:go_router/src/delegate.dart:158:6)
E/flutter ( 7075): #5      GoRouterDelegate._handlePopPageWithRouteMatch (package:go_router/src/delegate.dart:132:7)
E/flutter ( 7075): #6      _CustomNavigatorState._handlePopPage (package:go_router/src/builder.dart:408:42)
E/flutter ( 7075): #7      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5245:28)
E/flutter ( 7075): #8      Navigator.pop (package:flutter/src/widgets/navigator.dart:2569:27)
E/flutter ( 7075): #9      RejectRequestModal.build.<anonymous closure> (package:goldy/features/wallet/widgets/exchange_coins_requests/bottomsheets/exchange_actions_bottom_sheet.dart:280:19)
E/flutter ( 7075): #10     ModalCardDialog.build.<anonymous closure> (package:mts_granat/src/widgets/modal_card_dialog.dart:103:53)
E/flutter ( 7075): #11     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
E/flutter ( 7075): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.16.2, on macOS 13.0.1 22A400 darwin-arm64, locale ru-RU)
    • Flutter version 3.16.2 on channel stable at /Users/svmolchan1/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (9 weeks ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/svmolchan1/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • M2101K9AG (mobile) • cc706425 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)    • macos    • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Hi @subzero911 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thanks!

**Comment by subzero911** [comment]
I can provide it after vacation (after next Wednesday).
I currently found a following workaround:
```dart
Navigator.pop(context); // close the modal dialog
context.pop(); // close the bottom sheet
```
For some reason, a bottom sheet should be closed via context.pop, despite it's not a GoRoute.
Maybe because a bottom sheet is inside the inner navigator, go_router considers it as its route? `O_o`
If it has been closed by Navigator.pop, we have a black screen crash.
If I'm doing
```dart
context.pop();
context.pop();
```
then bottom sheet (behind the modal dialog) is closed, then the details screen is closed, while the dialog remains untouched.

**Comment by subzero911** [comment]
@huycozy 
Here you are! I created a minimal example.

https://github.com/subzero911/gorouter_branch_bug

**Comment by huycozy** [comment]
Thanks for the update. But I see your second pop call using a wrong context. It should use `showModalBottomSheet`'s builder context instead. Let's try below updated sample code and confirm if it works for your case:

<details>
<summary>Sample code (only main.dart in your repository above)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:gorouter_branch_bug/routes.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Go Router Branch Bug',
      routerConfig: router,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.amber),
        useMaterial3: true,
      ),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key, required this.title});

  final String title;

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              child: const Text('show bottomsheet'),
              onPressed: () {
                showModalBottomSheet(
                    context: context,
                    builder: (ct) {
                      return Padding(
                        padding: const EdgeInsets.all(20.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            const Text('BottomSheet'),
                            const SizedBox(height: 32),
                            ElevatedButton(
                              child: const Text('show modal dialog'),
                              onPressed: () {
                                showDialog(
                                    context: context,
                                    builder: (context) {
                                      return SimpleDialog(
                                        title: const Text('dialog'),
                                        children: [
                                          ElevatedButton(
                                            onPressed: () {
                                              // I wanted to close both this dialog and bottomsheet...
                                              Navigator.pop(context);
                                              Navigator.pop(ct); // CRASH!
                                            },
                                            child: const Text('close dialog'),
                                          ),
                                        ],
                                      );
                                    });
                              },
                            ),
                            const SizedBox(height: 32),
                            ElevatedButton(
                                child: const Text('close bottomsheet'),
                                onPressed: () {
                                  context.pop();
                                }),
                          ],
                        ),
                      );
                    });
              },
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

**Comment by subzero911** [comment]
Yes, this config worked properly:

<img width="854" alt="image" src="https://github.com/flutter/flutter/assets/12999702/7dabc0ea-5601-45d5-ae2a-4d428b5d2b07">

\
But this one still working incorrect:
<img width="1143" alt="image" src="https://github.com/flutter/flutter/assets/12999702/b0e6675d-0e93-4ad4-a000-6daa00d8287c">

Here I just dropped both the bottomSheet builder context and the Dialog builder context, and used a parental HomePage context.
Expected behaviour: a dialog popped, than a bottomsheet popped.
Actual behaviour: `Navigator.pop(context)` skipped the modal dialog and closed the bottomsheet, then a HomePage, and it crashed.

Also, I tried this config:
<img width="865" alt="image" src="https://github.com/flutter/flutter/assets/12999702/16031843-5a86-410f-b380-fec8f7731ca4">

I opened the dialog using the bottom sheet context.
Now a `Navigator.pop(context);` call tries to close the root HomePage right away, and it leads to crash

Also, I believe you should think about a more meaningful error message:
<img width="827" alt="image" src="https://github.com/flutter/flutter/assets/12999702/a8457acd-2d40-4dca-a240-b8e4e78c3127">

Something like `You used the wrong context and accidentally popped the topmost page from the StatefulBranch.`

**Comment by huycozy** [comment]
Thanks for checking it. I can reproduce that case as well. Whereas, the issue doesn't appear without using `go_router` (run an example with a single HomePage class).


<details>
<summary>Complete error stack trace</summary>

```console
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:61534/9Jt4cyWZjpQ=/ws
Debug service listening on ws://127.0.0.1:61534/9Jt4cyWZjpQ=/ws
Connecting to VM Service at ws://127.0.0.1:61534/9Jt4cyWZjpQ=/ws
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Assertion failed:
file:///Users/huynq/.pub-cache/hosted/pub.dev/go_router-13.2.0/lib/src/delegate.dart:116:7
currentConfiguration.isNotEmpty
"You have popped the last page off of the stack, there are no pages left to show"

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
packages/go_router/src/delegate.dart 116:28                                       [_debugAssertMatchListNotEmpty]
packages/go_router/src/delegate.dart 156:7                                        <fn>
packages/go_router/src/delegate.dart 157:14                                       [_completeRouteMatch]
packages/go_router/src/delegate.dart 132:7                                        [_handlePopPageWithRouteMatch]
packages/go_router/src/builder.dart 409:42                                        [_handlePopPage]
packages/flutter/src/widgets/navigator.dart 5284:18                               pop
packages/flutter/src/widgets/navigator.dart 2573:25                               pop
packages/gorouter_branch_bug/main.dart 71:57                                      <fn>
packages/flutter/src/material/ink_well.dart 1171:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 315:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 652:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 309:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 242:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 670:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:7                            [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:7           forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 495:5                                  handleEvent
packages/flutter/src/gestures/binding.dart 475:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 425:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 420:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 383:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 330:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 299:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1418:5                                invoke1
lib/_engine/engine/platform_dispatcher.dart 332:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 398:30                                    [_sendToFramework]
lib/_engine/engine/pointer_binding.dart 224:7                                     onPointerData
lib/_engine/engine/pointer_binding.dart 1001:20                                   <fn>
lib/_engine/engine/pointer_binding.dart 930:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 531:9                                     loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#df3e0
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Assertion failed: file:///Users/huynq/Documents/GitHub/flutter_master/packages/flutter/lib/src/widgets/navigator.dart:3882:12

```
</details>


<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (29 hours ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-11.0.pre.106, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-11.0.pre.106 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 59da873ef0 (4 minutes ago), 2024-02-22 19:16:20 -0800
    • Engine revision 0f3ad23b84
    • Dart version 3.4.0 (build 3.4.0-167.0.dev)
    • DevTools version 2.33.0-dev.11
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 122.0.6261.57

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by myxzlpltk** [comment]
Oh you're using go_router v13. Downgrading to v12 fixed the issue 🤣

**Comment by adrianwinau** [comment]
I have the same problem. The downgrade to v12 recommended by @myxzlpltk fixes this problem. But I wonder if this issue can be expected in newer version of go_router? Is there a solution or is the only solution currently not updating go_router?

**Comment by Windisch94** [comment]
any update on this?

**Comment by broqiang** [comment]
go_router 14.2.0 still has this problem, it works fine when downgrading to 12.1.3

**Comment by AlvaroVasconcelos** [comment]
any update?

**Comment by TheStrongest** [comment]
This is a major issue. I use statefulshellroute for my bottom navigation bar. navigating to a page from one of the shell branches and popping that page pops everything on the navigation stack.

**Comment by G705-Ghilan** [comment]
Hi, I found a great solution to solve this issue
and it works pretty amazing for me !!

just instead of scaffold for your tab page wrap it with CustomScaffold:
```dart
import 'package:flutter/material.dart';

class CustomScaffold extends StatelessWidget {
  const CustomScaffold({
    super.key,
    required this.body,
  });
  final Widget body;

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: false,
      onPopInvoked: (didPop) {
        if (Navigator.of(context, rootNavigator: true).canPop()) {
          Navigator.of(context, rootNavigator: true).pop();
        } else {
          Navigator.pop(context);
        }
      },
      child: Scaffold(body: body),
    );
  }
}
```

**Comment by chunhtai** [comment]
yes this is due to the use of root navigator or nested navigator when pushing dialog or bottom sheet. Nothing we can really do here
