### ISSUE TITLE
RenderBox was not laid out: RenderPadding#25314 NEEDS-LAYOUT NEEDS-PAINT 'package:flutter/src/rendering/box.dart': Failed assertion: line 1965 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by appxclusive** [flutter/flutter#142697]
### Steps to reproduce

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///Users/NEX4WUI/Working/Development/projects/ssto2_comm_extras/sendsuitmobile/lib/ui/place_in_locker/front_locker/front_loading_locker_screen.dart:364:9
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1965:12)
#3      InkDecoration.paintFeature (package:flutter/src/material/ink_decoration.dart:408:26)
#4      InkFeature._paint (package:flutter/src/material/material.dart:806:7)
#5      _RenderInkFeatures.paint (package:flutter/src/material/material.dart:659:20)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#9      RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2049:15)
#10     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:561:14)
#11     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2036:21)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#19     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#20     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#21     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#26     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
#27     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:639:5)
#28     RenderStack.paint (package:flutter/src/rendering/stack.dart:655:7)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#32     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2311:11)
#33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#35     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#36     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2951:13)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#40     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2951:13)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#43     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#45     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#46     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#47     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#49     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#52     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#53     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3752:11)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#56     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#59     _RenderTheaterMixin.paint (package:flutter/src/widgets/overlay.dart:866:15)
#60     _RenderTheater.paint (package:flutter/src/widgets/overlay.dart:1126:13)
#61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#63     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#66     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#69     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#72     _RenderTheaterMixin.paint (package:flutter/src/widgets/overlay.dart:866:15)
#73     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:472:12)
#74     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:532:7)
#75     _RenderTheater.paint (package:flutter/src/widgets/overlay.dart:1116:38)
#76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#78     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#79     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:664:11)
#80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#82     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#83     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2049:15)
#84     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:561:14)
#85     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2036:21)
#86     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#87     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#88     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#89     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#90     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#91     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#92     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#93     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#94     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#95     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#96     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#97     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#98     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#99     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#100    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#101    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#102    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#103    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#104    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#105    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#106    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#107    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#108    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#109    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#110    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#111    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#112    RenderView.paint (package:flutter/src/rendering/view.dart:206:15)
#113    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#114    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#115    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#116    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
#117    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
#118    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#119    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#120    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#121    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#122    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#123    _invoke (dart:ui/hooks.dart:170:13)
#124    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#125    _drawFrame (dart:ui/hooks.dart:140:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: _RenderInkFeatures#8b49a
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=414.0, h=896.0)
...  size: Size(414.0, 896.0)
RenderObject: _RenderInkFeatures#8b49a
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=414.0, h=896.0)
  size: Size(414.0, 896.0)
...  child: RenderCustomMultiChildLayoutBox#6a7bb NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=414.0, h=896.0)
...    size: Size(414.0, 896.0)
...    child 1: RenderPadding#3fbcf relayoutBoundary=up1 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...      constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=798.0)
...      size: MISSING
...      padding: EdgeInsets(0.0, 0.0, 0.0, 34.0)
...      textDirection: ltr
...      child: RenderFlex#36fed relayoutBoundary=up2 NEEDS-PAINT
...        needs compositing
...        parentData: offset=Offset(0.0, 0.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=764.0)
...        size: MISSING
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: start
...        textDirection: ltr
...        verticalDirection: down
...        child 1: _RenderScrollSemantics#0973f relayoutBoundary=up3 NEEDS-PAINT
...          needs compositing
...          parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, h=694.0)
...          semantic boundary
...          size: MISSING
...        child 2: RenderDecoratedBox#ec37e relayoutBoundary=up3 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
...          size: Size(414.0, 70.0)
...          decoration: BoxDecoration
...            color: Color(0xffffffff)
...            boxShadow: BoxShadow(Color(0x999e9e9e), Offset(0.0, 3.0), 7.0, 5.0, BlurStyle.normal)
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#8d7d7(), devicePixelRatio: 2.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...    child 2: RenderConstrainedBox#93e00 relayoutBoundary=up1 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.appBar (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=896.0)
...      size: Size(414.0, 98.0)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=98.0)
...      child: RenderSemanticsAnnotations#c4e09 relayoutBoundary=up2 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=98.0)
...        semantic boundary
...        size: Size(414.0, 98.0)
...        child: RenderAnnotatedRegion<SystemUiOverlayStyle>#c41db relayoutBoundary=up3 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, 0.0<=h<=98.0)
...          size: Size(414.0, 98.0)
...    child 3: RenderStack#06f40 NEEDS-LAYOUT NEEDS-PAINT
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.floatingActionButton
...      constraints: MISSING
...      size: MISSING
...      alignment: Alignment.centerRight
...      textDirection: ltr
...      fit: loose
...      child 1: RenderTransform#6f270 NEEDS-LAYOUT NEEDS-PAINT
...        parentData: not positioned; offset=Offset(0.0, 0.0)
...        constraints: MISSING
...        size: MISSING
...        transform matrix: [0] 0.0,0.0,0.0,0.0
[1] 0.0,0.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: Alignment.center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderTransform#52551 NEEDS-LAYOUT NEEDS-PAINT
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          transform matrix: [0] 0.7,0.7,0.0,0.0
[1] -0.7,0.7,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...          origin: null
...          alignment: Alignment.center
...          textDirection: ltr
...          transformHitTests: true
...    child 4: RenderPointerListener#fc303 NEEDS-LAYOUT NEEDS-PAINT
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.statusBar
...      constraints: MISSING
...      size: MISSING
...      behavior: opaque
...      listeners: down, panZoomStart
====================================================================================================

### Expected results

Should load scaffold widget without error

### Actual results

Not loading scaffold widget without error

### Code sample

<details open><summary>Code sample</summary>

```dart
 return WillPopScope(
      onWillPop: () async {
        _onBackPressed();
        return false;
      },
      child: getScaffoldMessenger(
        **Scaffold**(
          backgroundColor: AppColors.white,
          appBar: PreferredSize(
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hello @appxclusive.
I can't seem to reproduce this with the code snippet shared.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you
