### ISSUE TITLE
EXCEPTION CAUGHT BY SCHEDULER LIBRARY

### ISSUE THREAD

**Issue by umamoneynmore** [flutter/flutter#142601]
### Steps to reproduce

<details><summary>Logs</summary>
<p>

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12:
'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1177:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1175:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1092:5)
#9      _invoke1 (dart:ui/hooks.dart:328:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:351:5)
#11     _beginFrame (dart:ui/hooks.dart:272:31)
(elided 2 frames from class _AssertionError)


This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as
opposed to when the exception was thrown), this was the stack:
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:579:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:265:46)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:171:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:745:42)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:612:12)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:461:12)
#8      new InkSparkle (package:flutter/src/material/ink_sparkle.dart:133:8)
#9      _InkSparkleFactory.create (package:flutter/src/material/ink_sparkle.dart:464:12)
#10     _InkResponseState._createSplash (package:flutter/src/material/ink_well.dart:1070:72)
#11     _InkResponseState._startNewSplash (package:flutter/src/material/ink_well.dart:1166:42)
#12     _InkResponseState.handleAnyTapDown (package:flutter/src/material/ink_well.dart:1133:5)
#13     _InkResponseState.handleTapDown (package:flutter/src/material/ink_well.dart:1137:5)
#14     TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:624:61)
#15     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#16     TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:624:11)
#17     BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:300:5)
#18     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:277:7)
#19     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:268:25)
#20     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:248:31)
(elided 4 frames from class _FrameCallbackEntry and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos
12: 'elapsedInSeconds >= 0.0': is not true.
I/TRuntime.CctTransportBackend(16554): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
D/TrafficStats(16554): tagSocket(5) with statsTag=0xffffffff, statsUid=-1
I/TRuntime.CctTransportBackend(16554): Status Code: 200
``` 

</p>
</details> 

### Expected results

show right way page

### Actual results

not good

### Code sample

<details><summary>Code Sample</summary>
<p>

```dart
class GetStartedCard extends StatefulWidget {
  const GetStartedCard({super.key});

  @override
  State<GetStartedCard> createState() => _GetStartedCardState();
}

class _GetStartedCardState extends State<GetStartedCard>
    with DesignComponentMixin {
  late MfDataBloc mfDataBloc;
  late TextEditingController _controller;
  final BehaviorSubject<double> iconPadding =
      BehaviorSubject<double>.seeded(10);

  @override
  void initState() {
    mfDataBloc = BlocProvider.of<MfDataBloc>(context);
    super.initState();
    _controller = TextEditingController(text: '₹1,000');
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return Container(
      padding: getOverAllPaddingForBody(),
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: <Color>[
            Color.fromRGBO(225, 224, 249, 0.75),
            Color.fromRGBO(225, 224, 249, 0.0),
          ],
        ),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          SvgPicture.asset(SvgAssetPath.piggySavingSvg),
          getVerticalSizedBox(16),
          Text(
            AppString.investInGoal,
            style: theme.textTheme.headlineMedium
                ?.copyWith(color: theme.colorScheme.onSurface),
          ),
          getVerticalSizedBox(16),
          investementHighlight(theme),
          getVerticalSizedBox(SpaceToken.lg),
          investmentSelectorWidget(theme),
          getVerticalSizedBox(SpaceToken.lg),
          CustomFilledButton(
            borderRadius: 8,
            onPressed: navigateToGrowthCalculator,
            child: Text(
              AppString.getStarted,
              style: theme.textTheme.labelLarge
                  ?.copyWith(color: theme.colorScheme.onPrimary),
            ),
          )
        ],
      ),
    );
  }

  Widget investmentSelectorWidget(ThemeData theme) => CustomBoxShadowCard(
        backgroundColor:
            theme.extension<CustomColors>()!.surfaceContainerLowest,
        child: SizedBox(
          width: getScreenWidth(),
          child: Column(
            children: <Widget>[
              getVerticalSizedBox(SpaceToken.lg),
              Text(
                AppString.amount,
                style: theme.textTheme.labelMedium,
              ),
              Stack(
                alignment: Alignment.center,
                children: <Widget>[
                  StreamBuilder<double>(
                      stream: iconPadding.stream,
                      builder: (BuildContext context,
                          AsyncSnapshot<double> snapshot) {
                        return Padding(
                          padding: EdgeInsets.only(
                            left: 150 + (snapshot.data ?? 0),
                          ),
                          child: IconButton(
                            icon: const Icon(Icons.mode_edit_outlined,
                                size: 16.0),
                            onPressed: () {},
                          ),
                        );
                      }),
                  Padding(
                    padding: getOnlyPadding(left: 20, right: 40),
                    child: TextFormField(
                      onTapOutside: (PointerDownEvent event) {
                        FocusManager.instance.primaryFocus?.unfocus();
                      },
                      maxLength: 12,
                      onChanged: (String val) {
                        mfDataBloc.getInvestmentAmount = cleanedString(val);
                        iconPadding.add(customPadding());
                      },
                      inputFormatters: <TextInputFormatter>[
                        FilteringTextInputFormatter.digitsOnly,
                        RupeeFormatter()
                      ],
                      controller: _controller,
                      keyboardType: TextInputType.phone,
                      textAlign: TextAlign.center,
                      style: const TextStyle(
                        fontSize: 45.0,
                      ),
                      decoration: const InputDecoration(
                        counterText: '',
                        contentPadding: EdgeInsets.zero,
                        border: InputBorder.none,
                      ),
                    ),
                  ),
                ],
              ),
              getVerticalSizedBox(SpaceToken.lg),
              const Divider(height: 0),
              chooseInvestmentType(theme)
            ],
          ),
        ),
      );
  double customPadding() {
    return double.parse(_controller.text.length.toString()) * 10;
  }

  void amount() {
    mfDataBloc.getInvestementPeriod = '5 years';
    if (mfDataBloc.isSipEnabled()) {
      String amount = '₹1,000';
      amount = _controller.text;
      mfDataBloc.getInvestmentAmount = cleanedString(amount);
    } else {
      String amount = '₹4,000';
      amount = _controller.text;
      mfDataBloc.getInvestmentAmount = cleanedString(amount);
    }
  }

  void cleanAmount() {
    if (mfDataBloc.isSipEnabled()) {
      const String amount = '₹1,000';
      _controller.text = amount;
    } else {
      const String amount = '₹4,000';
      _controller.text = amount;
    }
  }

  void switchAmount() {
    if (mfDataBloc.isSipEnabled()) {
      const String amount = '₹1,000';
      _controller.text = amount;
      mfDataBloc.getInvestmentAmount = cleanedString(amount);
    } else {
      const String amount = '₹4,000';
      _controller.text = amount;
      mfDataBloc.getInvestmentAmount = cleanedString(amount);
    }
  }

  void navigateToGrowthCalculator() {
    amount();
    GoRouter.of(context)
        .pushNamed(MfRoute.selectMutualFund)
        .then((Object? value) {
      setState(() {});
    });
    cleanAmount();
  }

  Widget chooseInvestmentType(ThemeData theme) => Container(
        padding: getOnlyPadding(top: 8, bottom: 8),
        clipBehavior: Clip.hardEdge,
        decoration: const BoxDecoration(
          borderRadius: BorderRadius.only(
              bottomLeft: Radius.circular(8), bottomRight: Radius.circular(8)),
          color: Color.fromRGBO(225, 224, 249, 0.60),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              AppString.monthlySip,
              style: theme.textTheme.titleSmall?.copyWith(
                  fontWeight:
                      mfDataBloc.isSipEnabled() ? FontWeight.w500 : null,
                  color: mfDataBloc.isSipEnabled()
                      ? theme.colorScheme.primary
                      : null),
            ),
            getHorizontalSizedBox(20),
            CustomSwitch(
                value: !mfDataBloc.isSipEnabled(),
                onChange: (bool val) {
                  if (val) {
                    mfDataBloc.investmentType = InvestmentType.LUMPSUM;
                  } else {
                    mfDataBloc.investmentType = InvestmentType.SIP;
                  }
                  switchAmount();
                  setState(() {});
                }),
            getHorizontalSizedBox(20),
            Text(
              AppString.lumpSum,
              style: theme.textTheme.titleSmall?.copyWith(
                  fontWeight: mfDataBloc.isSipEnabled() == false
                      ? FontWeight.w500
                      : null,
                  color: mfDataBloc.isSipEnabled() == false
                      ? theme.colorScheme.primary
                      : null),
            )
          ],
        ),
      );

  Widget investementHighlight(ThemeData theme) => Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          investHelperText(theme, AppString.startWith),
          dividerCircle(),
          investHelperText(theme, AppString.selectReturn),
          dividerCircle(),
          investHelperText(theme, AppString.withdrawAnytime)
        ],
      );
  Widget dividerCircle() => Icon(
        Icons.circle,
        size: 6,
        color: Theme.of(context).extension<CustomColors>()!.surfaceDim,
      );

  Widget investHelperText(ThemeData theme, String text) => Text(
        text,
        style: theme.textTheme.bodySmall
            ?.copyWith(color: theme.colorScheme.secondary),
      );
}

String cleanedString(String amount) {
  return amount.replaceAll('₹', '').replaceAll(',', '');
}
``` 

</p>
</details> 

### Screenshots or Video

screen is gooad not any issue

### Logs

<details><summary>Logs</summary>
<p>

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12:
'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1177:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1175:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1092:5)
#9      _invoke1 (dart:ui/hooks.dart:328:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:351:5)
#11     _beginFrame (dart:ui/hooks.dart:272:31)
(elided 2 frames from class _AssertionError)


This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as
opposed to when the exception was thrown), this was the stack:
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:579:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:265:46)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:171:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:745:42)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:612:12)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:461:12)
#8      new InkSparkle (package:flutter/src/material/ink_sparkle.dart:133:8)
#9      _InkSparkleFactory.create (package:flutter/src/material/ink_sparkle.dart:464:12)
#10     _InkResponseState._createSplash (package:flutter/src/material/ink_well.dart:1070:72)
#11     _InkResponseState._startNewSplash (package:flutter/src/material/ink_well.dart:1166:42)
#12     _InkResponseState.handleAnyTapDown (package:flutter/src/material/ink_well.dart:1133:5)
#13     _InkResponseState.handleTapDown (package:flutter/src/material/ink_well.dart:1137:5)
#14     TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:624:61)
#15     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#16     TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:624:11)
#17     BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:300:5)
#18     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:277:7)
#19     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:268:25)
#20     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:248:31)
(elided 4 frames from class _FrameCallbackEntry and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos
12: 'elapsedInSeconds >= 0.0': is not true.
I/TRuntime.CctTransportBackend(16554): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
D/TrafficStats(16554): tagSocket(5) with statsTag=0xffffffff, statsUid=-1
I/TRuntime.CctTransportBackend(16554): Status Code: 200

``` 

</p>
</details> 

### Flutter Doctor output

<details><summary>Details</summary>
<p>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on Linux Mint 20.3 5.15.0-92-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.85.2)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
``` 

</p>
</details>

**Comment by dam-ease** [comment]
Hello @umamoneynmore 

From the logs, this might be similar to a known issue https://github.com/flutter/flutter/issues/106277 which occurs on device with 120hz refresh rate (mostly seen on Samsung S22 Ultra device).
Can you share the device information of the device you are running this on? 

Moreover, your shared code sample is incomplete and seems to contain some third-party package codes, hence I'm unable to run this on my end.
Please can you update this to a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
