### ISSUE TITLE
Null check operator used on a null value on Range Slider

### ISSUE THREAD

**Issue by KalaliEhsan** [flutter/flutter#142695]
### Steps to reproduce

I have copied the [sample code](https://api.flutter.dev/flutter/material/RangeSlider-class.html) in my app.

### Expected results

run without any bug

### Actual results

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following _TypeError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      _RenderRangeSlider.assembleSemanticsNode (package:flutter/src/material/range_slider.dart:1703:28)
range_slider.dart:1703
#1      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4947:13)
object.dart:4947
#2      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4936:16)
object.dart:4936
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4936:16)
object.dart:4936
#10     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4637:16)
object.dart:4637
#11     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3601:25)
object.dart:3601
#12     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1277:16)
object.dart:1277
#13     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1282:15)
object.dart:1282
#14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:598:25)
binding.dart:598
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
binding.dart:986
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
binding.dart:457
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
binding.dart:1325
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
binding.dart:1255
#19     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:978:7)
``` 

### Code sample

<details open><summary>Code sample</summary>

```dart

class CustomRangeSlider extends StatefulWidget {
  const CustomRangeSlider({super.key});

  @override
  State<CustomRangeSlider> createState() => _CustomRangeSliderState();
}

class _CustomRangeSliderState extends State<CustomRangeSlider> {
  late TokenNameColor _tokenName;
  RangeValues _currentRangeValues = const RangeValues(0, 100);

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _tokenName = Theme.of(context).extension<TokenNameColor>()!;
  }

  @override
  Widget build(BuildContext context) {
    return SliderTheme(
        data: SliderTheme.of(context).copyWith(
          activeTrackColor: _tokenName.backgroundDefaultPrimary,
          inactiveTrackColor: _tokenName.backgroundFrameBase,
          trackShape: const RoundedRectSliderTrackShape(),
          trackHeight: 4.0,
          thumbShape: const RoundSliderThumbShape(
            enabledThumbRadius: 50.0,
            disabledThumbRadius: 10,
          ),
          thumbColor: _tokenName.backgroundFrameMain,
          overlayColor: Colors.red.withAlpha(32),
          overlayShape: const RoundSliderOverlayShape(overlayRadius: 0.0),
          tickMarkShape: const RoundSliderTickMarkShape(),
          activeTickMarkColor: Colors.red[700],
          inactiveTickMarkColor: Colors.red[100],
          valueIndicatorShape: const PaddleSliderValueIndicatorShape(),
          valueIndicatorColor: Colors.yellow,
          valueIndicatorTextStyle: const TextStyle(color: Colors.white),
        ),
        child: RangeSlider(
          values: _currentRangeValues,
          min: 0,
          max: 100,
          divisions: 1,
          activeColor: _tokenName.backgroundDefaultPrimary,
          inactiveColor: _tokenName.backgroundFrameBase,
          labels: RangeLabels(
            _currentRangeValues.start.round().toString(),
            _currentRangeValues.end.round().toString(),
          ),
          onChanged: (RangeValues values) {
            setState(() {
              _currentRangeValues = values;
            });
          },
        ));
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console


════════ Exception caught by scheduler library ═════════════════════════════════
The following _TypeError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      _RenderRangeSlider.assembleSemanticsNode (package:flutter/src/material/range_slider.dart:1703:28)
range_slider.dart:1703
#1      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4947:13)
object.dart:4947
#2      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4936:16)
object.dart:4936
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
object.dart:4871
#9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4936:16)
object.dart:4936
#10     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4637:16)
object.dart:4637
#11     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3601:25)
object.dart:3601
#12     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1277:16)
object.dart:1277
#13     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1282:15)
object.dart:1282
#14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:598:25)
binding.dart:598
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
binding.dart:986
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
binding.dart:457
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
binding.dart:1325
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
binding.dart:1255
#19     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:978:7)
binding.dart:978
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
isolate_patch.dart:184
(elided 3 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════
flutter: FlutterError.onError:::::: Null check operator used on a null value /// #0      _RenderRangeSlider.assembleSemanticsNode (package:flutter/src/material/range_slider.dart:1703:28)
#1      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4947:13)
#2      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4936:16)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4871:18)
#8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/obj<…>

════════ Exception caught by Flutter framework ═════════════════════════════════
Bad state: Future already completed
════════════════════════════════════════════════════════════════════════════════
flutter: FlutterError.onError:::::: Bad state: Future already completed /// #0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      WidgetsBinding.drawFrame.<anonymous closure> (package:flutter/src/widgets/binding.dart:974:30)
#2      SchedulerBinding._executeTimingsCallbacks (package:flutter/src/scheduler/binding.dart:328:19)
#3      _invoke1 (dart:ui/hooks.dart:328:13)
#4      PlatformDispatcher._reportTimings (dart:ui/platform_dispatcher.dart:583:5)
#5      _reportTimings (dart:ui/hooks.dart:278:31)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.2 23C64 darwin-arm64, locale en-IR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @KalaliEhsan.
I can reproduce this on the latest `stable` channel but can't on the latest `master` channel. 
This looks similar/related to https://github.com/flutter/flutter/issues/141953 which has been fixed.
I'll be closing this as fixed as it now works fine in newer versions, if you disagree, please comment and I'll reopen this.

<details><summary>master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel master, 3.19.0-15.0.pre.38, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.19.0-15.0.pre.38 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e02e2079be (4 hours ago), 2024-02-01 02:00:32 -0500
    • Engine revision 68943afd62
    • Dart version 3.4.0 (build 3.4.0-97.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • Damilola’s iPhone (mobile)      • 00008110-001964480AE1801E            • ios            • iOS 17.1.1 21B91
    • iPhone 15 Pro (mobile)          • 79E44FCE-BEA4-4C4B-9C1C-EFBD9964E172 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>
