### ISSUE TITLE
FormatException: FormatException: Bad UTF-8 encoding 0xc3 (at offset 107)

### ISSUE THREAD

**Issue by peace2knowledge** [flutter/flutter#14264]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xc3 (at offset 107)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:490)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:762)
#11     _StreamController._add (dart:async/stream_controller.dart:638)
#12     _StreamController.add (dart:async/stream_controller.dart:584)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1654)
#14     _rootRunUnary (dart:async/zone.dart:1138)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:762)
#20     _StreamController._add (dart:async/stream_controller.dart:638)
#21     _StreamController.add (dart:async/stream_controller.dart:584)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1231)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:111)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 10.0.16299.125], locale zh-CN, channel master)
    • Flutter version 0.0.21-pre.304 at D:\flutter
    • Framework revision d3705f3ea9 (2 hours ago), 2018-01-24 22:27:24 -0800
    • Engine revision d715860925
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.8d9d68751a505426eb5f59a9d29f103fde6bd474

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Android NDK at C:\Users\Administrator\AppData\Local\Android\sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3942.31

[✓] Connected devices
    • MI 6 • dcf581ed • android-arm • Android 7.1.1 (API 25)

```

**Comment by lubi888** [comment]
Hi,

 I don't know if this [#14232](https://github.com/flutter/flutter/issues/14232) could be of any help but I had to delete an unknown file that was causing the issue. It might be in your /home/usr folder but perhaps elsewhere. You'll likely know it when you see it.

**Comment by peace2knowledge** [comment]
I can not find error file, i delete android dir. I find new problem, the android project can not add so file, when  add so file, build successfully , but do not install successfully @lubi888

**Comment by lubi888** [comment]
I don't have any other ideas. Maybe try a fresh install of flutter from github or rechecking you android setup.

**Comment by Hixie** [comment]
We don't really have enough information here to act on this. If you still see this problem please file a new bug and we'll see if we can tease out what is going on.
