### ISSUE TITLE
[google_maps_flutter_android] Failed to fetch cloudMapId style

### ISSUE THREAD

**Issue by Jjagg** [flutter/flutter#142798]
### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad70e8443c99234dc3328f442e811f1d8fd1a72f1c8ad0f69a605"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.0"
  clock:
    dependency: transitive
    description:
      name: clock
      sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: ee67cb0715911d28db6bf4af1026078bd6f0128b07a5f66fb2ed94ec6783c09a
      url: "https://pub.dev"
    source: hosted
    version: "1.18.0"
  csslib:
    dependency: transitive
    description:
      name: csslib
      sha256: "706b5707578e0c1b4b7550f64078f0a0f19dec3f50a178ffae7006b0a9ca58fb"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      sha256: "511392330127add0b769b75a987850d136345d9227c6b94c96a04cf4a391bf78"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: a25a15ebbdfc33ab1cd26c63a6ee519df92338a9c10f122adda92938253bef04
      url: "https://pub.dev"
    source: hosted
    version: "2.0.3"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      sha256: b068ffc46f82a55844acfa4fdbb61fad72fa2aef0905548419d97f0f95c456da
      url: "https://pub.dev"
    source: hosted
    version: "2.0.17"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  google_maps:
    dependency: transitive
    description:
      name: google_maps
      sha256: "555d5d736339b0478e821167ac521c810d7b51c3b2734e6802a9f046b64ea37a"
      url: "https://pub.dev"
    source: hosted
    version: "6.3.0"
  google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      sha256: ae66fef3e71261d7df2eff29b2a119e190b2884325ecaa55321b1e17b5504066
      url: "https://pub.dev"
    source: hosted
    version: "2.5.3"
  google_maps_flutter_android:
    dependency: "direct main"
    description:
      name: google_maps_flutter_android
      sha256: "714530f865f13bb3b9505c58821c3baed5d247a871724acf5d2ea5808fbed02c"
      url: "https://pub.dev"
    source: hosted
    version: "2.6.2"
  google_maps_flutter_ios:
    dependency: transitive
    description:
      name: google_maps_flutter_ios
      sha256: c89556ed0338fcb4b843c9fcdafac7ad2df601c8b41286d82f0727f7f66434e4
      url: "https://pub.dev"
    source: hosted
    version: "2.3.6"
  google_maps_flutter_platform_interface:
    dependency: "direct main"
    description:
      name: google_maps_flutter_platform_interface
      sha256: "6060779f020638a8eedeb0fb14234818e5fa32ec45a4653d6428ab436e2bbc64"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.3"
  google_maps_flutter_web:
    dependency: transitive
    description:
      name: google_maps_flutter_web
      sha256: "6245721c160d6f531c1ef568cf9bef8d660cd585a982aa75121269030163785a"
      url: "https://pub.dev"
    source: hosted
    version: "0.5.4+3"
  html:
    dependency: transitive
    description:
      name: html
      sha256: "3a7812d5bcd2894edf53dfaf8cd640876cf6cef50a8f238745c8b8120ea74d3a"
      url: "https://pub.dev"
    source: hosted
    version: "0.15.4"
  js:
    dependency: transitive
    description:
      name: js
      sha256: f2c445dce49627136094980615a031419f7f3eb393237e4ecd97ac15dea343f3
      url: "https://pub.dev"
    source: hosted
    version: "0.6.7"
  js_wrapping:
    dependency: transitive
    description:
      name: js_wrapping
      sha256: e385980f7c76a8c1c9a560dfb623b890975841542471eade630b2871d243851c
      url: "https://pub.dev"
    source: hosted
    version: "0.7.4"
  lints:
    dependency: transitive
    description:
      name: lints
      sha256: "0a217c6c989d21039f1498c3ed9f3ed71b354e69873f13a8dfc3c9fe76f1b452"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: "1803e76e6653768d64ed8ff2e1e67bea3ad4b923eb5c56a295c3e634bad5960e"
      url: "https://pub.dev"
    source: hosted
    version: "0.12.16"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      sha256: "9528f2f296073ff54cb9fee677df673ace1218163c3bc7628093e7eed5203d41"
      url: "https://pub.dev"
    source: hosted
    version: "0.5.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: a6e590c838b18133bb482a2745ad77c5bb7715fb0451209e1a7567d416678b8e
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "8829d8a55c13fc0e37127c29fedf290c102f4e40ae94ada574091fe0ff96c917"
      url: "https://pub.dev"
    source: hosted
    version: "1.8.3"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      sha256: "4820fbfdb9478b1ebae27888254d445073732dae3d6ea81f0b7e06d5dedc3f02"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.8"
  sanitize_html:
    dependency: transitive
    description:
      name: sanitize_html
      sha256: "12669c4a913688a26555323fb9cec373d8f9fbe091f2d01c40c723b33caa8989"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: "73713990125a6d93122541237550ee3352a2d84baad52d375a4cad2eb9b7ce0b"
      url: "https://pub.dev"
    source: hosted
    version: "1.11.1"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: ba2aa5d8cc609d96bbb2899c28934f9e1af5cddbd60a827822ea467161eb54e7
      url: "https://pub.dev"
    source: hosted
    version: "2.1.2"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      sha256: "14a00e794c7c11aa145a170587321aedce29769c08d7f58b1d141da75e3b1c6f"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: "5c2f730018264d276c20e4f1503fd1308dfbbae39ec8ee63c5236311ac06954b"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.1"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  web:
    dependency: transitive
    description:
      name: web
      sha256: afe077240a270dcfd2aafe77602b4113645af95d0ad31128cc02bce5ac5d5152
      url: "https://pub.dev"
    source: hosted
    version: "0.3.0"
sdks:
  dart: ">=3.2.3 <4.0.0"
  flutter: ">=3.13.0"
```

</details>

### Steps to reproduce

1. Create a new project and follow the set up instructions for google_maps_flutter: https://pub.dev/packages/google_maps_flutter
2. Initialize `google_maps_flutter_android` with the `latest` renderer: https://pub.dev/packages/google_maps_flutter_android#map-renderer
3. Display a `GoogleMap` with a `cloudMapId` with a custom style attached.

### Expected results

The custom style is applied to the map.

### Actual results

The default style is used.

I have tried on an emulator and a real device, with restricted and unrestricted API keys, but no dice.

### Code sample

<details open><summary>Code sample</summary>

Check out a sample project here: https://github.com/Jjagg/flutter_maps_android_test/tree/main.
- Replace the cloudMapId in `main.dart` with your cloud map id: `cloudMapId: '<YOUR CLOUD MAP ID>',`.
- Replace the API key in the manifest in `android/app/src/main/AndroidManifest.xml`: `<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR_MAPS_API_KEY"/>`

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/GoogleApiManager(11098): Failed to get service from broker. 
E/GoogleApiManager(11098): java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
E/GoogleApiManager(11098): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/GoogleApiManager(11098): 	at android.os.Parcel.createException(Parcel.java:3041)
E/GoogleApiManager(11098): 	at android.os.Parcel.readException(Parcel.java:3024)
E/GoogleApiManager(11098): 	at android.os.Parcel.readException(Parcel.java:2966)
E/GoogleApiManager(11098): 	at m.cqy.q(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:180)
E/GoogleApiManager(11098): 	at m.cpk.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:54)
E/GoogleApiManager(11098): 	at android.os.Handler.handleCallback(Handler.java:958)
E/GoogleApiManager(11098): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/GoogleApiManager(11098): 	at android.os.Looper.loopOnce(Looper.java:205)
E/GoogleApiManager(11098): 	at android.os.Looper.loop(Looper.java:294)
E/GoogleApiManager(11098): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/GoogleMapController(11098): Cannot enable MyLocation layer as location permissions are not granted
E/m.esq   (11098): referer is null for url=https://mapsresources-pa.googleapis.com/v1/styleTables/<styleTableId>?configVersion=934f82f71ffc3fffbf6d4d7388714d41&configSet=roadmap&version=3389395395459911205
E/m.epx   (11098): Error RESOURCE_SERVER_ERROR occurred while loading style table https://mapsresources-pa.googleapis.com/v1/styleTables/<styleTableId>?configVersion=934f82f71ffc3fffbf6d4d7388714d41&configSet=roadmap&version=3389395395459911205.  Will keep trying: false
```

These last two lines seem to be pointing to the error, but I'm not sure what could be the cause of the issue.
```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    • Flutter version 3.16.5 on channel stable at /Users/<...>/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (6 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/<...>/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/<...>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode-15.1.0.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 14 (API 34)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by huycozy** [comment]
Thanks for the report. I can reproduce this issue as well.

**Comment by huycozy** [comment]
Thanks for the report. I can reproduce this issue as well. I also noticed some trace logs with `MobStoreFlagStore` TAG, which looks like a map internal service.

<details>
<summary>Output log</summary>

```console
D/MapsInitializer(20058): loadedRenderer: LATEST
I/Choreographer(20058): Skipped 42 frames!  The application may be doing too much work on its main thread.
E/GoogleApiManager(20058): Failed to get service from broker.
E/GoogleApiManager(20058): java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
E/GoogleApiManager(20058): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
E/GoogleApiManager(20058): 	at android.os.Parcel.createException(Parcel.java:2373)
E/GoogleApiManager(20058): 	at android.os.Parcel.readException(Parcel.java:2356)
E/GoogleApiManager(20058): 	at android.os.Parcel.readException(Parcel.java:2298)
E/GoogleApiManager(20058): 	at m.cqy.q(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:180)
E/GoogleApiManager(20058): 	at m.cpk.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:54)
E/GoogleApiManager(20058): 	at android.os.Handler.handleCallback(Handler.java:938)
E/GoogleApiManager(20058): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/GoogleApiManager(20058): 	at android.os.Looper.loop(Looper.java:255)
E/GoogleApiManager(20058): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/MobStoreFlagStore(20058): Unable to update local snapshot for com.google.android.gms.maps#com.google.android.gms, may result in stale flags.
W/MobStoreFlagStore(20058): java.util.concurrent.ExecutionException: m.few: 17: 17: API: Phenotype.API is not available on this device. Connection failed with: cmc{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
W/MobStoreFlagStore(20058): 	at m.gua.s(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:21)
W/MobStoreFlagStore(20058): 	at m.gua.get(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:5)
W/MobStoreFlagStore(20058): 	at m.gwy.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:2)
W/MobStoreFlagStore(20058): 	at m.gvt.h(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:10)
W/MobStoreFlagStore(20058): 	at m.fgk.c(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
W/MobStoreFlagStore(20058): 	at m.fgr.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:5)
W/MobStoreFlagStore(20058): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/MobStoreFlagStore(20058): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/MobStoreFlagStore(20058): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/MobStoreFlagStore(20058): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/MobStoreFlagStore(20058): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/MobStoreFlagStore(20058): 	at java.lang.Thread.run(Thread.java:923)
W/MobStoreFlagStore(20058): Caused by: m.few: 17: 17: API: Phenotype.API is not available on this device. Connection failed with: cmc{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
W/MobStoreFlagStore(20058): 	at m.fey.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:13)
W/MobStoreFlagStore(20058): 	at m.gtx.e(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:3)
W/MobStoreFlagStore(20058): 	at m.gtz.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:139)
W/MobStoreFlagStore(20058): 	at m.guz.execute(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
W/MobStoreFlagStore(20058): 	at m.gua.q(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
W/MobStoreFlagStore(20058): 	at m.gua.k(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:96)
W/MobStoreFlagStore(20058): 	at m.gua.n(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:19)
W/MobStoreFlagStore(20058): 	at m.fbx.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:35)
W/MobStoreFlagStore(20058): 	at m.cyi.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:12)
W/MobStoreFlagStore(20058): 	at m.guz.execute(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
W/MobStoreFlagStore(20058): 	at m.cyj.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:12)
W/MobStoreFlagStore(20058): 	at m.cyr.b(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:36)
W/MobStoreFlagStore(20058): 	at m.cyv.g(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:20)
W/MobStoreFlagStore(20058): 	at m.cyf.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:83)
W/MobStoreFlagStore(20058): 	at m.guz.execute(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
W/MobStoreFlagStore(20058): 	at m.cyg.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:8)
W/MobStoreFlagStore(20058): 	at m.cyr.b(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:36)
W/MobStoreFlagStore(20058): 	at m.cys.c(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:25)
W/MobStoreFlagStore(20058): 	at m.coj.c(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:7)
W/MobStoreFlagStore(20058): 	at m.cpi.s(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:48)
W/MobStoreFlagStore(20058): 	at m.cpi.f(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:10)
W/MobStoreFlagStore(20058): 	at m.cpi.j(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:177)
W/MobStoreFlagStore(20058): 	at m.cpi.i(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:2)
W/MobStoreFlagStore(20058): 	at m.cpk.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:82)
W/MobStoreFlagStore(20058): 	at android.os.Handler.handleCallback(Handler.java:938)
W/MobStoreFlagStore(20058): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/MobStoreFlagStore(20058): 	at android.os.Looper.loop(Looper.java:255)
W/MobStoreFlagStore(20058): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/MobStoreFlagStore(20058): Caused by: m.cno: 17: API: Phenotype.API is not available on this device. Connection failed with: cmc{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
W/MobStoreFlagStore(20058): 	at m.cqp.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:13)
W/MobStoreFlagStore(20058): 	at m.coj.c(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:3)
W/MobStoreFlagStore(20058): 	... 9 more
E/Parcel  (20058): Reading a NULL string not supported here.
E/Parcel  (20058): Reading a NULL string not supported here.
E/Parcel  (20058): Reading a NULL string not supported here.
I/eproduce_issue(20058): ProcessProfilingInfo new_methods=1638 is saved saved_to_disk=1 resolve_classes_delay=5000
D/MapsInitializer(20058): preferredRenderer: null
D/zzcc    (20058): preferredRenderer: null
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.9 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (14 hours ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-1.0.pre.20, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-1.0.pre.20 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f8a77225f3 (13 hours ago), 2024-02-04 14:28:18 +0000
    • Engine revision f34c658b96
    • Dart version 3.4.0 (build 3.4.0-99.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • iPad (mobile)   • 00008103-000A1464346A201E • ios            • iOS 17.2 21C62
    • macOS (desktop) • macos                     • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by gmackall** [comment]
@AlexQuidditch If you are encountering the same issue, please use the thumbs up feature to raise the visibility of the initial report
