### ISSUE TITLE
Plugin: camera - crash when reopening the app

### ISSUE THREAD

**Issue by btastic** [flutter/flutter#14274]
## Steps to Reproduce

1. Start the example in the camera repository [https://github.com/flutter/plugins/tree/master/packages/camera](https://github.com/flutter/plugins/tree/master/packages/camera)
2. Open a camera
3. Close the app by clicking back on the arrow keys (hardware or software)
4. Open the app again
5. Crash

This is on Android API 25 and I observed that this does not happen on Android API 22.

## Logs

Last words before crashing:
```
I/RequestQueue( 3547): Repeating capture request cancelled.
W/MessageQueue( 3547): Handler (android.graphics.SurfaceTexture$1) {569b5fd} sending message to a Handler on a dead thread
W/MessageQueue( 3547): java.lang.IllegalStateException: Handler (android.graphics.SurfaceTexture$1) {569b5fd} sending message to a Handler on a dead thread
W/MessageQueue( 3547): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
W/MessageQueue( 3547): 	at android.os.Handler.enqueueMessage(Handler.java:643)
W/MessageQueue( 3547): 	at android.os.Handler.sendMessageAtTime(Handler.java:612)
W/MessageQueue( 3547): 	at android.os.Handler.sendMessageDelayed(Handler.java:582)
W/MessageQueue( 3547): 	at android.os.Handler.sendEmptyMessageDelayed(Handler.java:546)
W/MessageQueue( 3547): 	at android.os.Handler.sendEmptyMessage(Handler.java:531)
W/MessageQueue( 3547): 	at android.graphics.SurfaceTexture.postEventFromNative(SurfaceTexture.java:380)
D/EGL_emulation( 3547): eglMakeCurrent: 0xa5605600: ver 2 0 (tinfo 0xa5603fc0)
I/CameraManager( 3547): Using legacy camera HAL.
I/CameraManager( 3547): Using legacy camera HAL.
I/FlutterActivityDelegate( 3547): onResume setting current activity to this
I/CameraDeviceState( 3547): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0( 3547): Configure outputs: 2 surfaces configured.
D/Camera  ( 3547): app passed NULL surface
E/BufferQueueProducer( 3547): [ImageReader-640x480f100m2-3547-1] connect: already connected (cur=4 req=4)
E/Legacy-CameraDevice-JNI( 3547): connectSurface: Unable to connect to surface, error Invalid argument (-22).
E/Legacy-CameraDevice-JNI( 3547): LegacyCameraDevice_nativeConnectSurface: Error while configuring surface Invalid argument (-22).
E/AndroidRuntime( 3547): FATAL EXCEPTION: RequestThread-0
E/AndroidRuntime( 3547): Process: io.flutter.plugins.cameraexample, PID: 3547
E/AndroidRuntime( 3547): java.lang.UnsupportedOperationException: Unknown error -22
E/AndroidRuntime( 3547): 	at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:77)
E/AndroidRuntime( 3547): 	at android.hardware.camera2.legacy.LegacyCameraDevice.connectSurface(LegacyCameraDevice.java:666)
E/AndroidRuntime( 3547): 	at android.hardware.camera2.legacy.RequestThreadManager.configureOutputs(RequestThreadManager.java:406)
E/AndroidRuntime( 3547): 	at android.hardware.camera2.legacy.RequestThreadManager.-wrap0(RequestThreadManager.java)
E/AndroidRuntime( 3547): 	at android.hardware.camera2.legacy.RequestThreadManager$5.handleMessage(RequestThreadManager.java:704)
E/AndroidRuntime( 3547): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime( 3547): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 3547): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

## Flutter Doctor

```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale de-DE, channel master)
    • Flutter version 0.0.21-pre.295 at C:\Users\bkons\Source\Repos\meddlr\flutter
    • Framework revision 5ae770345a (2 days ago), 2018-01-23 13:46:14 -0800
    • Engine revision 171d032f86
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.93d8c9fe2a2c22dc95ec85866af108cfab71ad06

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\bkons\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by mravn-google** [comment]
cc @sigurdm

**Comment by btastic** [comment]
Any news on this? Kind of a deal breaker for our app right now :/

If anyone points me in the right direction I might be able to fix this myself, but I already looked into it but I couldn't figure it out.

Thanks!

**Comment by sigurdm** [comment]
Thanks for pinging me. Hopefully this will solve the issue

**Comment by sigurdm** [comment]
Can you confirm camera 0.0.3 solves your problem on android 25?

**Comment by btastic** [comment]
Unfortunately a new error occured.

Steps: 
1. Opened the sample application
2. Selected back camera
3. Save a picture
4. Crash

Below is the error log

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk (24.5MB).
I/FlutterActivityDelegate(22807): onResume setting current activity to this
D/        (22807): HostConnection::get() New Host Connection established 0xa55d8c40, tid 22824
D/EGL_emulation(22807): eglMakeCurrent: 0xa755a620: ver 2 0 (tinfo 0x93fc4070)
I/Choreographer(22807): Skipped 44 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(22807): eglMakeCurrent: 0xa755a440: ver 2 0 (tinfo 0xa55d9080)
I/CameraManagerGlobal(22807): Connecting to camera service
I/CameraManager(22807): Using legacy camera HAL.
I/CameraDeviceState(22807): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0(22807): Configure outputs: 2 surfaces configured.
D/Camera  (22807): app passed NULL surface
I/RequestThread-0(22807): configureOutputs - set take picture size to 640x480
D/        (22807): HostConnection::get() New Host Connection established 0x91c7c440, tid 22856
D/EGL_emulation(22807): eglCreateContext: 0xb4c855a0: maj 2 min 0 rcv 2
D/EGL_emulation(22807): eglMakeCurrent: 0xb4c855a0: ver 2 0 (tinfo 0x8f3d30b0)
E/EGL_emulation(22807): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation(22807): tid 22856: eglQueryContext(1777): error 0x3004 (EGL_BAD_ATTRIBUTE)
I/CameraDeviceState(22807): Legacy camera service transitioning to state IDLE
I/RequestQueue(22807): Repeating capture request set.
W/LegacyRequestMapper(22807): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyMetadataMapper(22807): convertAfModeToLegacy - ignoring unsupported mode 4, defaulting to fixed
W/LegacyRequestMapper(22807): convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
D/        (22807): HostConnection::get() New Host Connection established 0xa55d8780, tid 22820
I/CameraDeviceState(22807): Legacy camera service transitioning to state CAPTURING
D/        (22807): HostConnection::get() New Host Connection established 0x91c7c600, tid 22836
D/        (22807): HostConnection::get() New Host Connection established 0xa55d8300, tid 22819
D/skia    (22807): Could not invert viewmatrix
W/LegacyRequestMapper(22807): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyRequestMapper(22807): convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
I/flutter (22807): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter (22807): The following FileSystemException was thrown resolving an image codec:
I/flutter (22807): Cannot open file, path = '/data/user/0/io.flutter.plugins.cameraexample/cache/picture0.jpg' (OS
I/flutter (22807): Error: No such file or directory, errno = 2)
I/flutter (22807):
I/flutter (22807): When the exception was thrown, this was the stack:
I/flutter (22807): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:351)
I/flutter (22807): (elided 8 frames from package dart:async)
I/flutter (22807):
I/flutter (22807): Path: /data/user/0/io.flutter.plugins.cameraexample/cache/picture0.jpg
I/flutter (22807): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/RequestThread-0(22807): Received jpeg.
I/RequestThread-0(22807): Producing jpeg buffer...
D/        (22807): HostConnection::get() New Host Connection established 0xa55d8600, tid 22845
W/LegacyRequestMapper(22807): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyMetadataMapper(22807): convertAfModeToLegacy - ignoring unsupported mode 4, defaulting to fixed
W/LegacyRequestMapper(22807): convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
D/AndroidRuntime(22807): Shutting down VM
E/AndroidRuntime(22807): FATAL EXCEPTION: main
E/AndroidRuntime(22807): Process: io.flutter.plugins.cameraexample, PID: 22807
E/AndroidRuntime(22807): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(22807): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:143)
E/AndroidRuntime(22807): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime(22807): 	at io.flutter.plugins.camera.CameraPlugin$Cam$6.onImageAvailable(CameraPlugin.java:565)
E/AndroidRuntime(22807): 	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:687)
E/AndroidRuntime(22807): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22807): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(22807): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/AndroidRuntime(22807): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22807): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime(22807): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
I/art     (22807): Do partial code cache collection, code=18KB, data=24KB
I/art     (22807): After code cache collection, code=18KB, data=24KB
I/art     (22807): Increasing code cache capacity to 128KB
Lost connection to device.
```

**Comment by sigurdm** [comment]
Oops - good catch - I "overcorrected" without thinking. Another fix is coming up...

**Comment by sigurdm** [comment]
Now there is a version 0.0.4

**Comment by btastic** [comment]
Working on both emulator and a hardware device. Both on API 25. 

Thank you Sigurd!
