### ISSUE TITLE
android: FlutterEngine destroyed/detach

### ISSUE THREAD

**Issue by qeepcologne** [flutter/flutter#142797]
### Steps to reproduce

starting flutter activity with cached engine.
start native activity from flutter
start flutter activity from that native activity
start native activity from flutter
then back,back,back,back

### Expected results

expected that flutter engine survives activity.
checked FlutterActivity, it shouldn't be destroyed when cachedEngineId is set.

### Actual results

the first time back to flutter works, the second time the engine is removed

FlutterActivity io.flutter.embedding.android.FlutterActivity@26a9582 connection to the engine io.flutter.embedding.engine.FlutterEngine@6048067 evicted by another attaching activity

FlutterActivity 227426304 onResume called after detach.

### Code sample

```java
    private void initFluter(){
        FlutterEngine flutterEngine = new FlutterEngine(getApplicationContext());
        flutterEngine.getDartExecutor().executeDartEntrypoint(DartExecutor.DartEntrypoint.createDefault());
        FlutterEngineCache.getInstance().put(FLUTTER_ENGINE_CACHE_KEY, flutterEngine);
    }
```

```java
    public void startFlutterActivity(String route) {
        FlutterEngineCache.getInstance().get(FLUTTER_ENGINE_CACHE_KEY).getNavigationChannel().pushRoute(route);
        startActivity(FlutterActivity.withCachedEngine(FLUTTER_ENGINE_CACHE_KEY).build(getActivity()));
    }
```

the last backPress just calling getOnBackPressedDispatcher().onBackPressed()

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on Ubuntu Noble Numbat (development branch) 6.6.0-14-generic, locale en_DE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
bwahlen@devel2:~$ flutter doctor -v
[✓] Flutter (Channel stable, 3.16.9, on Ubuntu Noble Numbat (development branch) 6.6.0-14-generic, locale en_DE.UTF-8)
    • Flutter version 3.16.9 on channel stable at /home/bwahlen/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (8 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/bwahlen/android-sdk-linux
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/bwahlen/android-sdk-linux
    • Java binary at: /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/bwahlen/android-studio
    • Flutter plugin version 77.2.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "17.0.7" 2023-04-18

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu Noble Numbat (development branch)
      6.6.0-14-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hello @qeepcologne.
From the logs, this might be similar/related to https://github.com/flutter/flutter/issues/110138. Can you check it out?
If not, kindly share a sample repo we could run on our end to reproduce this issue.
Thank you!

**Comment by qeepcologne** [comment]
don't think so:
- no need to change any settings
- happens all the time, 100% reproduceable, not timing related (fast&slow, debug&live, emulator (android14) and real device (android11))

**Comment by dam-ease** [comment]
Thanks for your response @qeepcologne.
Kindly share a sample repo we could run on our end to reproduce this issue.

**Comment by qeepcologne** [comment]
Thanks a log. I tried to strip down the issue into minimal sample app, but at the moment i cannot reproduce it there. I am working on it to find out the difference.

**Comment by dam-ease** [comment]
Thanks for your response @qeepcologne.
Running the repo shared, I get a `Page Not Found` error on the screen. Calling the `ChatMainWidget()` directly and clicking the `fire native` button, I get the logs below with no changes.
<details><summary>Logs</summary>
<p>

```
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:101)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#dev.fluttercommunity.plus/android_intent( 5957): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter ( 5957): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unable to find explicit activity class {com.example.myapplication/com.example.myapplication.MainActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?, null, android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.myapplication/com.example.myapplication.MainActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
E/flutter ( 5957): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2236)
E/flutter ( 5957): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
E/flutter ( 5957): 	at android.app.Activity.startActivityForResult(Activity.java:5589)
E/flutter ( 5957): 	at android.app.Activity.startActivityForResult(Activity.java:5547)
E/flutter ( 5957): 	at android.app.Activity.startActivity(Activity.java:6045)
E/flutter ( 5957): 	at android.app.Activity.startActivity(Activity.java:6012)
E/flutter ( 5957): 	at dev.fluttercommunity.plus.androidintent.IntentSender.send(IntentSender.java:55)
E/flutter ( 5957): 	at dev.fluttercommunity.plus.androidintent.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:101)
E/flutter ( 5957): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 5957): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 5957): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 5957): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 5957): 	at android.os.Handler.handleCallback(Handler.java:958)
E/flutter ( 5957): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 5957): 	at android.os.Looper.loopOnce(Looper.java:205)
E/flutter ( 5957): 	at android.os.Looper.loop(Looper.java:294)
E/flutter ( 5957): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
E/flutter ( 5957): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5957): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/flutter ( 5957): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter ( 5957): )
E/flutter ( 5957): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 5957): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter ( 5957): <asynchronous suspension>
E/flutter ( 5957): #2      AndroidIntent.launch (package:android_intent_plus/android_intent.dart:150:5)
E/flutter ( 5957): <asynchronous suspension>
E/flutter ( 5957): #3      _fireNativeView (package:flutter_module/src/features/chat/presentation/chat_main.dart:58:5)
E/flutter ( 5957): <asynchronous suspension>
``` 

</p>
</details> 

Can you recheck this as well on your end to confirm you see similar logs?

**Comment by qeepcologne** [comment]
I cannot reproduce these problems, but i stripped down the app a little more. I also tested build on fresh dockerized jenkins and installed this build on real device and still cannot reproduce your issue. I added the Dockerfile and steps for the job (jenkins-job).

**Comment by huycozy** [comment]
I can reproduce this issue with sample code at https://github.com/flutter/flutter/issues/142797#issuecomment-1924112872 on `Realme 6, Android 11`.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/6b09fc91-f618-47ab-9b85-19fad25edcea
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.9 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (14 hours ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-2.0.pre.17, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-2.0.pre.17 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6322fef7e0 (29 minutes ago), 2024-02-05 21:53:12 -0500
    • Engine revision 808886312e
    • Dart version 3.4.0 (build 3.4.0-104.0.dev)
    • DevTools version 2.32.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by jonahwilliams** [comment]
FYI @gaaclarke , we don't have enough context on this API to know if it is working or not. I would expect that if a cache is tied to an activity, then we'd lose the cache if the OS kills the activity.

**Comment by qeepcologne** [comment]
when calling
startActivity(new FlutterActivity.CachedEngineIntentBuilder(FlutterActivity.class, FLUTTER_ENGINE_CACHE_KEY).build(getActivity()));
the second time
FlutterActivity.cleanUpFlutterEngine is called
but even when i remove the super call, problem is still there.

when i set android:launchMode= "singleInstance", here is no empty screen, but then backstack is lost
from this point and app minimizes.

**Comment by qeepcologne** [comment]
any progress? this bug is really annoying when you have a mixed app jumping in and out of flutter a lot. Users are complaining stat they are stuck on that grey screens.

**Comment by AbdelrahmanEsam** [comment]
any progress ?
