### ISSUE TITLE
[tool_crash] crash at flutter analyze

### ISSUE THREAD

**Issue by miguelfs** [flutter/flutter#142888]
## Command
```
flutter analyze
```

## Steps to Reproduce
1. passing an `onGenerateRoute` parameter like below. Must remove the commentary.
2. Calling flutter analyze from the cmd line.

## Necessary snippet to reproduce the error:
```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      // onGenerateRoute: (settings) {
      //   switch (settings.name) {
      //     case '/splash':
      //       return MaterialPageRoute(builder: (_) => const SplashScreen());
      //     case '/home' or '/':
      //       return MaterialPageRoute(builder: (_) => const BlocProvider(
      //   create: (_) => FeatureFlagsBloc(),
      //   HomeScreen(),
      //   ),);
      //    case '/profile':
      //       return MaterialPageRoute(builder: (_) => const ProfileScreen());
      //    case '/flags':
      //       return MaterialPageRoute(builder: (_) => const FlagsScreen());
      //     default:
      //       throw Exception('Invalid route: ${settings.name}');
      //   }
      // },
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.orangeAccent),
        useMaterial3: true,
        textTheme: GoogleFonts.montaguSlabTextTheme(
          Theme.of(context).textTheme,
        ),
      ),
      home: const SplashScreen(),
    );
  }
}
```

## Logs

flutter analyze:
```
❯ flutter analyze
Unhandled exception:
Null check operator used on a null value
#0      Parser._attemptPrecedenceLevelRecovery (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6053:55)
#1      Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6037:11)
#2      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5808:12)
#3      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5724:15)
#4      Parser.parseExpressionStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5685:13)
#5      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8056:16)
#6      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5486:14)
#7      Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5476:20)
#8      Parser.parseStatementsInSwitchCase (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8932:17)
#9      Parser.parseSwitchBlock (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8891:15)
#10     Parser.parseSwitchStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8809:13)
#11     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5527:14)
#12     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5476:20)
#13     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5381:15)
#14     Parser.parseAsyncOptBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5206:13)
#15     Parser.parseFunctionExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5135:13)
#16     Parser.parseParenthesizedExpressionFunctionLiteralOrRecordLiteral
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:6580:16)
#17     Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6549:14)
#18     Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6341:12)
#19     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5784:13)
#20     Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5724:15)
#21     Parser.parseArgumentsRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7650:15)
#22     Parser.parseArguments (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7626:12)
#23     Parser.parseArgumentsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7607:14)
#24     Parser.parseSend (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7546:13)
#25     Parser.parseSendOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7069:12)
#26     Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6450:14)
#27     Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6341:12)
#28     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5784:13)
#29     Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5724:15)
#30     Parser.parseReturnStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5627:13)
#31     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5503:14)
#32     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5476:20)
#33     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5381:15)
#34     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4877:15)
#35     Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4678:15)
#36     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4295:15)
#37     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2663:13)
#38     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2621:14)
#39     Parser._handleModifiersForClassDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:819:12)
#40     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:658:14)
#41     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:531:14)
#42     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:411:15)
#43     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:97:32)
#44     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:93:12)
#45     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:746:23)
#46     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:501:14)
#47     FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:692:16)
#48     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:547:27)
#49     FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1487:10)
#50     FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1317:14)
#51     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1301:12)
#52     AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1653:16)
#53     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1056:5)
#54     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2262:24)
<asynchronous suspension>


#0      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:503:7)
#1      FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:692:16)
#2      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:547:27)
#3      FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1487:10)
#4      FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1317:14)
#5      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1301:12)
#6      AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1653:16)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1056:5)
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2262:24)
<asynchronous suspension>
```

_Exception
```
_Exception: Exception: analysis server exited with code 255 and output:
[stderr] #48     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:547:27)
[stderr] #49     FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1487:10)
[stderr] #50     FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1317:14)
[stderr] #51     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1301:12)
[stderr] #52     AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1653:16)
[stderr] #53     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1056:5)
[stderr] #54     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2262:24)
[stderr] <asynchronous suspension>
[stderr] 
[stderr] 
[stderr] #0      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:503:7)
[stderr] #1      FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:692:16)
[stderr] #2      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:547:27)
[stderr] #3      FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1487:10)
[stderr] #4      FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1317:14)
[stderr] #5      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1301:12)
[stderr] #6      AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1653:16)
[stderr] #7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1056:5)
[stderr] #8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2262:24)
[stderr] <asynchronous suspension>

```
```
[32m[✓][39m Flutter (Channel stable, 3.16.9, on macOS 14.0 23A344 darwin-arm64, locale pt-BR)
    [32m•[39m Flutter version 3.16.9 on channel stable at /Users/miguel/Developer/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 41456452f2 (10 days ago), 2024-01-25 10:06:23 -0800
    [32m•[39m Engine revision f40e976bed
    [32m•[39m Dart version 3.2.6
    [32m•[39m DevTools version 2.28.5

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/miguel/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15A5219j
    [32m•[39m CocoaPods version 1.14.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version 1.85.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.80.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone 14 Pro Max (mobile) • C906B3F8-AA2E-4708-A7A6-9DD93D3DECB3 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    [32m•[39m macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    [32m•[39m Chrome (web)               • chrome                               • web-javascript • Google Chrome 121.0.6167.139
    [33m![39m Error: Browsing on the local area network for iPhone Mini de Miguel. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 367f9ea16bfae1ca451b9cc27c1366870b187ae2
### Plugins
flutter_plugin_android_lifecycle-2.0.17
google_maps_flutter-2.5.3
google_maps_flutter_android-2.6.2
google_maps_flutter_ios-2.4.1
google_maps_flutter_web-0.5.4+3
mobile_scanner-3.5.6
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
qr_code_scanner-1.0.1
sign_in_with_apple-5.0.0
sign_in_with_apple_web-1.0.1
webview_flutter-4.4.4
webview_flutter_android-3.14.0
webview_flutter_wkwebview-3.11.0

**Comment by dam-ease** [comment]
Hello @miguelfs.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
