### ISSUE TITLE
[tool_crash] FileSystemException: writeFrom failed, OS Error: Operation timed out, errno = 60

### ISSUE THREAD

**Issue by ganzyhax** [flutter/flutter#142859]
## Command
```
flutter pub get --no-example
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: writeFrom failed, OS Error: Operation timed out, errno = 60
```
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:904:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:646:14)
#2      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#3      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#4      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:267:22)
#5      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#6      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:266:5)
#7      _DefaultPub._updatePackageConfig (package:flutter_tools/src/dart/pub.dart:732:8)
<asynchronous suspension>
#8      _DefaultPub._updateVersionAndPackageConfig (package:flutter_tools/src/dart/pub.dart:707:5)
<asynchronous suspension>
#9      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:538:7)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:314:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.2.1 23C71 darwin-arm64, locale ru-KZ)
    • Flutter version 3.13.9 on channel stable at /Users/macos/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 months ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/macos/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.82.2)
    • VS Code at /Users/macos/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554             • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone Мухаммад (mobile)  • 00008110-000E5C123AD1801E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)           • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+5
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: d211f42860350d914a5ad8102f9ec32764dc6d06
### Plugins
cloud_firestore-4.13.6
cloud_firestore_web-3.8.10
device_info-2.0.3
file_picker-4.6.1
firebase_core-2.24.2
firebase_core_web-2.10.0
firebase_storage-11.5.6
firebase_storage_web-3.6.17
flutter_credit_card-4.0.1
flutter_plugin_android_lifecycle-2.0.17
path_provider-2.0.15
path_provider_android-2.2.0
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.0.7
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2

**Comment by dam-ease** [comment]
Hello @ganzyhax.
I see you are on an older version of flutter, can you please check if this occurs when you upgrade to the latest version of flutter?
