### ISSUE TITLE
Does not seem to be supported so file in Android

### ISSUE THREAD

**Issue by peace2knowledge** [flutter/flutter#14280]
I want to integrate Baidu map flflter project, but when I add Baidu sdk, he includes jar files and so files. Project compiled successfully, but the installation has not been completed. The logs are as follows, including some warnings,
Mainly I want to prove that flutter projects can integrate existing third-party SDKs such as payments, statistics, they are not SDK, we are in China.

```
Launching lib\main.dart on MI 6 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.baidu.mapapi.search.route.d) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
。。。。。。。
Built build\app\outputs\apk\debug\app-debug.apk (36.3MB).
Installing build\app\outputs\apk\app.apk...
````
```
01-26 10:17:25.439 3002-3010/io.flutter.examples.platform_channel I/art: Debugger is no longer active
01-26 10:17:25.439 3002-3010/io.flutter.examples.platform_channel I/art: Starting a blocking GC Instrumentation
01-26 10:19:48.944 3002-3002/io.flutter.examples.platform_channel I/FlutterActivityDelegate: onResume setting current activity to this
01-26 10:19:48.989 3002-3036/io.flutter.examples.platform_channel I/OpenGLRenderer: Initialized EGL, version 1.4
01-26 10:19:48.989 3002-3036/io.flutter.examples.platform_channel D/OpenGLRenderer: Swap behavior 1
01-26 10:19:53.178 3002-3002/io.flutter.examples.platform_channel E/ActivityThread: Activity com.example.platformchannel.MainActivity has leaked IntentReceiver com.example.platformchannel.MainActivity$3@c192b9d that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                    android.app.IntentReceiverLeaked: Activity com.example.platformchannel.MainActivity has leaked IntentReceiver com.example.platformchannel.MainActivity$3@c192b9d that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1167)
                                                                                        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:950)
                                                                                        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1339)
                                                                                        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1319)
                                                                                        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1313)
                                                                                        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:596)
                                                                                        at com.example.platformchannel.MainActivity$1.onListen(MainActivity.java:41)
                                                                                        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:181)
                                                                                        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:160)
                                                                                        at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:133)
                                                                                        at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                        at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                        at android.os.Looper.loop(Looper.java:142)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6365)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
```

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
@peace2knowledge It is not clear from the logs that there are issues with the integration of third-party dependencies with Flutter as such.

- The Gradle warning seems to concern how the third-party jar file is built. That should appear also when building a non-Flutter Android app.
- The adb log error indicates a programming error in the `MainActivity` class, like registering a `BroadcastReceiver` in `onCreate` and not unregistering it in `onPause`. Hard to tell, since we have no code to look at.
