### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: O sistema não pode encontrar o arquivo especificado., errno = 2

### ISSUE THREAD

**Issue by CabeloSG** [flutter/flutter#142827]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: O sistema não pode encontrar o arquivo especificado.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:644:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:267:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:266:5)
#8      Cache.setStampFor (package:flutter_tools/src/cache.dart:675:35)
#9      VersionCheckStamp.store (package:flutter_tools/src/version.dart:802:30)
#10     FlutterVersion._getLatestAvailableFlutterDate (package:flutter_tools/

**Comment by darshankawar** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/76479
