### ISSUE TITLE
Error assertion was thrown while executing callbacks for FrameTiming when run test for integration test in flutter app

### ISSUE THREAD

**Issue by apatheticL** [flutter/flutter#142964]
### Steps to reproduce

1. I run command `flutter test integration_test/test.dart` then UI in app show test starting... and run auto click  create_account and show error this log and app skill now

### Expected results

app skill for unknown reasons

### Actual results

app skill for unknown reasons

### Code sample

```
void main() async {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;

  try {
    await initializeTest();
    FlutterError.onError = (details) {
      print('error caught by FlutterError.onError');
      print(details.exception.toString());
    };
  } catch (e) {
    print('error caught by catch');
    print(e);
  }
}

Future<void> initializeTest() async {
  group('signUp', () {
    startTest();
  });
}

void startTest() {
  testWidgets('start application', (tester) async {
    app.main();

    // Wait for the SplashScreen to disappear.
    while (find.byType(SplashScreenNew).evaluate().isNotEmpty) {
      await tester.pumpAndSettle();
    }
   
    // Find the 'StartScreen' widget.
    while (find.byType(StartScreen).evaluate().isEmpty) {
      await tester.pumpAndSettle();
    }
    // case 1
    await startSignUpTest(tester);
    // await startTestCaseSignUpPhone(tester);

  });
}


Future<void> startSignUpTest(WidgetTester tester) async {
    // Find the 'Create Account' button. Replace 'CreateAccountButton' with the actual key or type of your button.
    var createAccountButton = find.byKey(Key('create_account'));

    // Check if the button is present.
    expect(createAccountButton, findsOneWidget);

    // Tap on the 'Create Account' button.
    await tester.tap(createAccountButton);
}



```

### Logs

```
00:00 +0: loading D:/nhatle/mobileapp/integration_test/test.dart                                                                                                                                       R00:30 +0: loading D:/nhatle/mobileapp/integration_test/test.dart                                                                                                                                  29.8s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
00:31 +0: loading D:/nhatle/mobileapp/integration_test/test.dart                                                                                                                                       I00:43 +0: loading D:/nhatle/mobileapp/integration_test/test.dart                                                                                                                                  12.0s
00:50 +0: signUp start application
almost done load common data: null
DateTime 2024-02-06 09:26:54.381719
after load common data: false
building the start screen?
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following assertion was thrown while executing callbacks for FrameTiming:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 894 pos 16: 'sendFramesToEngine':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

#8      PlatformDispatcher._reportTimings (dart:ui/platform_dispatcher.dart:597:5)
#9      _reportTimings (dart:ui/hooks.dart:135:31)
(elided 5 frames from class _AssertionError and dart:async)

The TimingsCallback that gets executed was:
  Closure: (List<FrameTiming>) => void
════════════════════════════════════════════════════════════════════════════════════════════════════
00:51 +0 -1: signUp start application [E]
  Test failed. See exception logs above.
  The test description was: start application


To run this test again: C:\Users\tinhn\flutter\bin\cache\dart-sdk\bin\dart.exe test D:/nhatle/mobileapp/integration_test/test.dart -p vm --plain-name "signUp start application"
00:51 +0 -1: Some tests failed.


### Flutter Doctor output

`[!] Flutter (Channel [user-branch], 3.13.6, on Microsoft Windows [Version 10.0.22000.2713], locale en-US)
    ! Flutter version 3.13.6 on channel [user-branch] at C:\Users\tinhn\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision ead455963c (4 months ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\tinhn\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\tinhn\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\tinhn\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.2
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\tinhn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • 2201116TG (mobile) • GMZDQSX8CI8P8HFA • android-arm64  • Android 13 (API 33)
    • Windows (desktop)  • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.2713]
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 120.0.6099.227
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 121.0.2277.98

[√] Network resources
    • All expected network resources are available.`
```

**Comment by darshankawar** [comment]
Thanks for the bug report.
Based on the error log, it looks similar to https://github.com/flutter/flutter/issues/89651, so please follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
