### ISSUE TITLE
Flutter Doctor: Connected device (the doctor check crashed)... Exception: Unable to run "adb" ...

### ISSUE THREAD

**Issue by Rudentsov** [flutter/flutter#142996]
### Steps to reproduce

1. I connect the device via USB to the computer.

2. I run the command `flutter doctor -v`

3. The command gives an error: "Connected device (the doctor check crashed)... Exception: Unable to run "adb" ..."

### Actual results

When the device is connected via USB, the command `flutter doctor -v` produces the following error:

```
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: D:\ProgramData\Android\Sdk\platform-tools\adb.exe
```

This error began to appear after updating flutter from version 3.13.6 to version 3.16.9.

But after rolling back to flutter version 3.13.6, this problem did not disappear.

In addition, the device was no longer recognized in Android Studio, although everything worked fine before the flutter update.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
    • Flutter version 3.13.6 on channel stable at D:\ProgramData\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (4 months ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[X] Windows Version (Unable to determine Windows version (command `ver` returned Microsoft Windows [Version 6.1.7601]))

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at D:\ProgramData\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = D:/ProgramData/Android/Sdk
    • Java binary at: D:\ProgramData\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.9)
    • Visual Studio at D:\ProgramData\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at D:\ProgramData\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\ProgramData\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: D:\ProgramData\Android\Sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:563:36)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
      <asynchronous suspension>
      #4      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:231:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:690:34)
      <asynchronous suspension>
      #6      Future.any.onValue (dart:async/future.dart:615:5)
      <asynchronous suspension>


[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
@Rudentsov 
Do you have any anti-virus that might be blocking adb ?

**Comment by Rudentsov** [comment]
> @Rudentsov Do you have any anti-virus that might be blocking adb ?

Hello. No, there are no antivirus programs on the device. There are also no antivirus programs on the computer, except for the native firewall. In the native Windows firewall, adb is allowed.
The only thing is that the computer is now connected to another Wi-Fi router (“Keenetic Start”), previously it was connected to the “DrayTek VigorFly 200”. But the router does not have any antivirus software or blocking software.

**Comment by Rudentsov** [comment]
I noticed this:

When the device is not connected to USB, the result of the command `adb devices` is as follows:

```
C:\Users\User>adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached

```

And when the device is connected to USB, the result of executing the command `adb devices` is as follows - an error occurs and adb.exe starts and ends immediately:

```
C:\Users\User>adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
error: protocol fault (couldn't read status): Connection reset by peer

```

**Comment by Rudentsov** [comment]
I tried to use the Android Studio utility "Menu / Tools / Troubleshoot Device Connections". The result of scanning devices is as follows (device found - Lenovo TAB4 10):

![изображение](https://github.com/flutter/flutter/assets/58599124/d47ab635-4a77-43ec-a616-ee6e7ef26213)

USB debugging is allowed:

![изображение](https://github.com/flutter/flutter/assets/58599124/22daf8fd-5a5a-4838-b75b-4effbeb824cf)

But restarting the adb server results in the error "Unable to locate ADB.":

![изображение](https://github.com/flutter/flutter/assets/58599124/a304830b-b572-4317-8c42-6c4e77ccb98c)

**Comment by Rudentsov** [comment]
I tried the following commands:

```
C:\Users\User>set ADB_TRACE=all

C:\Users\User>adb devices
02-07 16:19:42.018  7660  1924 D adb     : adb_trace.cpp:187 Android Debug Bridge version 1.0.41
02-07 16:19:42.018  7660  1924 D adb     : adb_trace.cpp:187 Version 34.0.5-10900879
02-07 16:19:42.018  7660  1924 D adb     : adb_trace.cpp:187 Installed as D:\ProgramData\Android\Sdk\platform-tools\adb.exe
02-07 16:19:42.018  7660  1924 D adb     : adb_trace.cpp:187 Running on Windows 6.1.7601
02-07 16:19:42.018  7660  1924 D adb     : adb_trace.cpp:187
02-07 16:19:42.018  7660  1924 D adb     : adb_client.cpp:160 _adb_connect: host:version
02-07 16:19:43.030  7660  1924 D adb     : sysdeps_win32.cpp:1032 could not connect to tcp:5037: cannot connect to 127.0.0.1:5037: ╨Я╨╛╨┤╨║╨╗╤О╤З╨╡╨╜╨╕╨╡ ╨╜╨╡ ╤
Г╤Б╤В╨░╨╜╨╛╨▓╨╗╨╡╨╜╨╛, ╤В.╨║. ╨║╨╛╨╜╨╡╤З╨╜╤Л╨╣ ╨║╨╛╨╝╨┐╤М╤О╤В╨╡╤А ╨╛╤В╨▓╨╡╤А╨│ ╨╖╨░╨┐╤А╨╛╤Б ╨╜╨░ ╨┐╨╛╨┤╨║╨╗╤О╤З╨╡╨╜╨╕╨╡. (10061)
02-07 16:19:43.030  7660  1924 D adb     : sysdeps_win32.cpp:602 _socket_set_errno: mapping Windows error code 10061 to errno 22
* daemon not running; starting now at tcp:5037
02-07 16:19:43.060  7044  6496 D adb     : adb_trace.cpp:187 Android Debug Bridge version 1.0.41
02-07 16:19:43.060  7044  6496 D adb     : adb_trace.cpp:187 Version 34.0.5-10900879
02-07 16:19:43.060  7044  6496 D adb     : adb_trace.cpp:187 Installed as D:\ProgramData\Android\Sdk\platform-tools\adb.exe
02-07 16:19:43.060  7044  6496 D adb     : adb_trace.cpp:187 Running on Windows 6.1.7601
02-07 16:19:43.060  7044  6496 D adb     : adb_trace.cpp:187
* daemon started successfully
02-07 16:20:04.561  7660  1924 D adb     : sysdeps_win32.cpp:151 _fh_from_int: invalid fd -2 passed to adb_close
List of devices attached
02-07 16:20:04.561  7660  1924 D adb     : adb_client.cpp:400 adb_query: host:devices
02-07 16:20:04.561  7660  1924 D adb     : adb_client.cpp:358 adb_connect: service: host:devices
02-07 16:20:04.561  7660  1924 D adb     : adb_client.cpp:160 _adb_connect: host:devices
02-07 16:20:04.561  7660  1924 D adb     : sysdeps_win32.cpp:1040 port 5037 type tcp => fd 2048
02-07 16:20:04.561  7660  1924 D adb     : adb_io.cpp:107 writex: fd=2048 len=16 30303063686f73743a64657669636573 000chost:devices
02-07 16:20:04.561  7660  1924 D adb     : adb_io.cpp:81 readx: fd=2048 wanted=4
02-07 16:20:04.571  7660  1924 D adb     : sysdeps_win32.cpp:689 recv fd 2048 failed: ╨г╨┤╨░╨╗╨╡╨╜╨╜╤Л╨╣ ╤Е╨╛╤Б╤В ╨┐╤А╨╕╨╜╤Г╨┤╨╕╤В╨╡╨╗╤М╨╜╨╛ ╤А╨░╨╖╨╛╤А╨▓╨░╨╗ ╤Б
╤Г╤Й╨╡╤Б╤В╨▓╤Г╤О╤Й╨╡╨╡ ╨┐╨╛╨┤╨║╨╗╤О╤З╨╡╨╜╨╕╨╡. (10054)
02-07 16:20:04.571  7660  1924 D adb     : adb_io.cpp:88 readx: fd=2048 error 108: Connection reset by peer
02-07 16:20:04.571  7660  1924 D adb     : sysdeps_win32.cpp:537 adb_close: 2048(lo-client:5037)
02-07 16:20:04.571  7660  1924 D adb     : adb_client.cpp:372 _adb_connect error: protocol fault (couldn't read status): Connection reset by peer
02-07 16:20:04.571  7660  1924 D adb     : adb_client.cpp:376 adb_connect: return fd -1
error: protocol fault (couldn't read status): Connection reset by peer
```

**Comment by Rudentsov** [comment]
After searching for various options, the cause of the error was found.

Android SDK Platform-Tools version 34.0.5 is incompatible with my configuration Android Studio (Electric Eel | 2022.1.1 Patch 1) or SDK Developer Tools.

After the rollback on the Android SDK Platform-Tools version 34.0.4, the error disappeared - the device connected to the USB is recognized in Android Studio and Flutter.

The problem is solved.
