### ISSUE TITLE
AssetImage manifest crashes with invalid JSON

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#14297]
## Steps to Reproduce
Fake an AssetBundle with invalid JSON and try to pass it into an AssetImage constructor.  The resulting error is unclear about the actual cause.

I think this is related to #14070, and that the appropriate fix is to parse the JSON into a well-defined object instead of using dynamic typing.

## Logs
This is from Flutter at commit `75b97b00dfaffdcd7de6e00610bf6cd98216f730`
```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown while resolving an image:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String' of 'value' where
  _InternalLinkedHashMap is from dart:collection
  String is from dart:core
  String is from dart:core

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#0      List.[]= (dart:core-patch/dart:core/growable_array.dart:143)
#1      new List.from (dart:core-patch/dart:core/array_patch.dart:42)
#2      AssetImage._manifestParser.<anonymous closure> (package:flutter/src/painting/image_resolution.dart:221:40)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#4      Maps._fillMapWithIterables (dart:collection/maps.dart:363)
#5      new LinkedHashMap.fromIterables (dart:collection/linked_hash_map.dart:132)
#6      AssetImage._manifestParser (package:flutter/src/painting/image_resolution.dart:220:13)
...
```

**Comment by zoechi** [comment]
I tried to reproduce but wasn't able to. 

I came up with below code but I don't know where to pass invalid JSON and what kind of invalid it should be.

```dart
import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'foo text',
            ),
            DefaultAssetBundle(
              bundle: AssetBundleMock(),
              child: Image.asset('key'),
            ),
          ],
        ),
      ),
    );
  }
}

class AssetBundleMock extends CachingAssetBundle {
  @override
  Future<ByteData> load(String key) async {
    return ByteData.view(
        Uint8List.fromList(utf8.encode('{"$key":["$key"]}')).buffer);
  }
}
```

**Comment by goderbauer** [comment]
@DaveShuckerow Can you post some actual code that reproduces the problem? Looks like @zoechi wasn't able to reproduce it.

**Comment by Piinks** [comment]
This bug has not been updated in a while, and is currently not actionable without a reproduction. Please don't hesitate to comment on the issue if you have a reproduction for us; we will reopen it right away!
