### ISSUE TITLE
Crash when requesting focus for a TextField located below a sliver of infinite height

### ISSUE THREAD

**Issue by yiiim** [flutter/flutter#143047]
### Steps to reproduce

Run the following code and click the button.

### Expected results

I'm not sure what the expected behavior should be, but it definitely shouldn't crash.

### Actual results

The application crashes.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

FocusNode focusNode = FocusNode();
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverList.builder(
              itemBuilder: (context, index) {
                return Container(
                  height: 44,
                );
              },
            ),
            SliverToBoxAdapter(
              child: TextField(
                focusNode: focusNode,
              ),
            ),
          ],
        ),
        floatingActionButton: IconButton(
          onPressed: focusNode.requestFocus,
          icon: const Icon(Icons.add),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.20.0-3.0.pre.23, on macOS 13.4 22F66 darwin-arm64, locale en-CN)
    ! Flutter version 3.20.0-3.0.pre.23 on channel [user-branch] at /Users/10906/source/repo/github/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository git@github.com:yiiim/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:yiiim/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    ! CocoaPods 1.11.3 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Thanks for the report. I also can reproduce this issue.

<details>
<summary>Output exception log</summary>

```console
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:63004/BEtd2mSK-Us=/ws
I/eproduce_issue(22927): Compiler allocated 4670KB to compile void android.view.ViewRootImpl.performTraversals()
I/eproduce_issue(22927): ProcessProfilingInfo new_methods=1518 is saved saved_to_disk=1 resolve_classes_delay=5000
E/ion     (22927): ioctl c0044901 failed with code -1: Invalid argument
D/ProfileInstaller(22927): Installing profile for com.example.reproduce_issues
D/ViewRootImpl(22927): enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=971.0, y[0]=2170.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=125596066, downTime=125596066, deviceId=3, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity](22927): processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=971.0, y[0]=2170.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=125596066, downTime=125596066, deviceId=3, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity](22927): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=971.0, y[0]=2170.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=125596066, downTime=125596066, deviceId=3, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity](22927): processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=971.0, y[0]=2170.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=125596159, downTime=125596066, deviceId=3, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity](22927): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=971.0, y[0]=2170.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=125596159, downTime=125596066, deviceId=3, source=0x1002, displayId=0 }
E/flutter (22927): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Converting object to an encodable object failed: NaN
E/flutter (22927): #0      _JsonStringifier.writeObject (dart:convert/json.dart:793:7)
E/flutter (22927): #1      _JsonStringifier.writeList (dart:convert/json.dart:844:9)
E/flutter (22927): #2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:823:7)
E/flutter (22927): #3      _JsonStringifier.writeObject (dart:convert/json.dart:784:9)
E/flutter (22927): #4      _JsonStringifier.writeMap (dart:convert/json.dart:874:7)
E/flutter (22927): #5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:829:21)
E/flutter (22927): #6      _JsonStringifier.writeObject (dart:convert/json.dart:784:9)
E/flutter (22927): #7      _JsonStringifier.writeMap (dart:convert/json.dart:874:7)
E/flutter (22927): #8      _JsonStringifier.writeJsonValue (dart:convert/json.dart:829:21)
E/flutter (22927): #9      _JsonStringifier.writeObject (dart:convert/json.dart:784:9)
E/flutter (22927): #10     _JsonStringStringifier.printOn (dart:convert/json.dart:982:17)
E/flutter (22927): #11     _JsonStringStringifier.stringify (dart:convert/json.dart:967:5)
E/flutter (22927): #12     JsonEncoder.convert (dart:convert/json.dart:345:30)
E/flutter (22927): #13     JsonCodec.encode (dart:convert/json.dart:231:45)
E/flutter (22927): #14     JSONMessageCodec.encodeMessage (package:flutter/src/services/message_codecs.dart:102:51)
E/flutter (22927): #15     JSONMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:138:37)
E/flutter (22927): #16     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:323:34)
E/flutter (22927): #17     OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:601:18)
E/flutter (22927): #18     _PlatformTextInputControl.setEditableSizeAndTransform (package:flutter/src/services/text_input.dart:2326:14)
E/flutter (22927): #19     TextInput._setEditableSizeAndTransform (package:flutter/src/services/text_input.dart:2009:15)
E/flutter (22927): #20     TextInputConnection.setEditableSizeAndTransform (package:flutter/src/services/text_input.dart:1431:27)
E/flutter (22927): #21     EditableTextState._updateSizeAndTransform (package:flutter/src/widgets/editable_text.dart:4130:27)
E/flutter (22927): #22     EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:3493:7)
E/flutter (22927): #23     EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:3528:7)
E/flutter (22927): #24     EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:4074:5)
E/flutter (22927): #25     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
E/flutter (22927): #26     FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1089:5)
E/flutter (22927): #27     FocusManager.applyFocusChangesIfNeeded (package:flutter/src/widgets/focus_manager.dart:1794:12)
E/flutter (22927): #28     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (22927): #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (22927): 
I/AssistStructure(22927): Flattened final assist data: 400 bytes, containing 1 windows, 3 views
D/InputConnectionAdaptor(22927): The input method toggled cursor monitoring on

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1508 pos 12: 'correctedOffset.isFinite': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    CustomScrollView CustomScrollView:file:///Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/reproduce_issues_2/lib/tf_crash_143047.dart:15:15

When the exception was thrown, this was the stack:
#2      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1508:12)
viewport.dart:1508
#3      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1464:20)
viewport.dart:1464
#4      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2414:7)
object.dart:2414
#5      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
object.dart:1051
#6      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
object.dart:1064
#7      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577:23)
binding.dart:577
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:995:13)
binding.dart:995
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
binding.dart:443
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1387:15)
binding.dart:1387
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1312:9)
binding.dart:1312
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1170:5)
binding.dart:1170
#13     _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#15     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 2 frames from class _AssertionError)

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.9 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (14 hours ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-2.0.pre.17, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-2.0.pre.17 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6322fef7e0 (29 minutes ago), 2024-02-05 21:53:12 -0500
    • Engine revision 808886312e
    • Dart version 3.4.0 (build 3.4.0-104.0.dev)
    • DevTools version 2.32.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by Piinks** [comment]
I would expect an assertion like the one we are discussing adding in https://github.com/flutter/flutter/pull/141671

Having a sliver of infinite height in the group, with another sliver expected to follow (containing the text field here), is not valid. You would never be able to scroll to the second sliver in the group. This is why I think we should assert against this.

**Comment by Paulik8** [comment]
I haven't reproduced the crash on Redmi Note 9 Pro (android-arm64 Android 10 (API 29))
So may somebody from flutter team check that issue?

Additionally, [there’s a check using assert](https://github.com/yiiim/flutter/blob/1de678f1bdb17059692786bdc9d0db58e254f59f/packages/flutter/lib/src/rendering/viewport.dart#L1508). Are any additional `assert`-s really necessary?
If no additional `assert`-s  are needed and the bug cannot be reproduced, is it correct to close the issue?

<details>
  <summary>fvm flutter doctor -v</summary>
  
  ```
[✓] Flutter (Channel stable, 3.27.2, on macOS 14.7.2 23H311 darwin-arm64, locale en)
    • Flutter version 3.27.2 on channel stable at /Users/khotinp/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68415ad1d9 (12 days ago), 2025-01-13 10:22:03 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    • Android SDK at /Users/khotinp/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_HOME = /Users/khotinp/Library/Android/sdk
    • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.13+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.1.1
    • Dart plugin version 223.8977

[✓] IntelliJ IDEA Community Edition (version 2024.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 83.0.3
    • Dart plugin version 242.24931

[✓] Connected device (5 available)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
  ```
</details>
