### ISSUE TITLE
An error with ListView

### ISSUE THREAD

**Issue by artmexbet** [flutter/flutter#143083]
### Steps to reproduce

I tried to use Card class as a navigation bar pages (like [there](https://api.flutter.dev/flutter/material/NavigationBar-class.html)).

### Expected results

I expected to see an list view on the screen

### Actual results

I catch this error:
```
The following assertion was thrown during paint():
RenderBox was not laid out: RenderTransform#78598 relayoutBoundary=up3
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  ListView ListView:file:///F:/Project/TeacherApplication/lib/main.dart:180:17
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1972:12)
#3      RenderTransform._effectiveTransform (package:flutter/src/rendering/proxy_box.dart:2481:49)
#4      RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2518:33)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#7      RenderClipRect.paint (package:flutter/src/rendering/proxy_box.dart:1541:17)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#10     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2882:15)
#11     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1040:7)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#14     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#24     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:662:11)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#28     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:633:11)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#32     RenderPhysicalShape.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2156:15)
#33     PaintingContext.pushClipPath (package:flutter/src/rendering/object.dart:614:14)
#34     RenderPhysicalShape.paint (package:flutter/src/rendering/proxy_box.dart:2143:21)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#37     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#40     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#43     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2882:15)
#44     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#47     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#48     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:662:11)
#49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#51     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#52     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2043:15)
#53     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:575:14)
#54     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2030:21)
#55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#57     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#60     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#62     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:166:11)
#63     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:109:5)
#64     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1156:31)
#65     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1166:15)
#66     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:593:23)
#67     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#68     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#69     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#70     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#71     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#72     _invoke (dart:ui/hooks.dart:312:13)
#73     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#74     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderTransform#78598 relayoutBoundary=up3
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=395.4, 0.0<=h<=Infinity)
...  size: MISSING
...  transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...  origin: null
...  alignment: AlignmentDirectional.bottomCenter
...  textDirection: ltr
...  transformHitTests: true
RenderObject: RenderTransform#78598 relayoutBoundary=up3
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=395.4, 0.0<=h<=Infinity)
  size: MISSING
  transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
  origin: null
  alignment: AlignmentDirectional.bottomCenter
  textDirection: ltr
  transformHitTests: true
...  child: _RenderScrollSemantics#36a0e relayoutBoundary=up4 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=395.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: MISSING
...    child: RenderPointerListener#4fafa relayoutBoundary=up5 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=395.4, 0.0<=h<=Infinity)
...      size: MISSING
...      behavior: deferToChild
...      listeners: signal
...      child: RenderSemanticsGestureHandler#91163 relayoutBoundary=up6 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=395.4, 0.0<=h<=Infinity)
...        size: MISSING
...        behavior: opaque
...        gestures: <none>
...        child: RenderPointerListener#064ca relayoutBoundary=up7 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=395.4, 0.0<=h<=Infinity)
...          size: MISSING
...          behavior: opaque
...          listeners: down, panZoomStart

```

### Code sample

<details open><summary>Code sample</summary>

```dart
Card(
            shadowColor: Colors.transparent,
            margin: const EdgeInsets.all(8.0),
            child: SizedBox.expand(
                child: Center(
                    child: Column(
              children: <Widget>[
                ListView(
                  children: <Widget>[
                    GestureDetector(
                      onTap: () {}, // TODO: Write transition
                      child: Card(),
                    )
                  ],
                ),
                FilledButton(
                    onPressed: () {}, child: const Text("Add student"))
              ],
            ))))
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.3930], locale ru-RU)
    • Flutter version 3.16.9 on channel stable at F:\FlutterSDK\flutter                           
    • Upstream repository https://github.com/flutter/flutter.git                                  
    • Framework revision 41456452f2 (13 days ago), 2024-01-25 10:06:23 -0800                      
    • Engine revision f40e976bed                                                                  
    • Dart version 3.2.6                                                  
    • DevTools version 2.28.5                                             
                                                                          
[√] Windows Version (Installed version of Windows is version 10 or higher)
                                                                          
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0) 
    • Android SDK at C:\Users\2004m\AppData\Local\Android\sdk                    
    • Platform android-34, build-tools 34.0.0                                    
    • Java binary at: F:\Programms\Android Studio 2\jbr\bin\java                 
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
    • Visual Studio at F:\VisualStudio
    • Visual Studio Community 2022 version 17.8.34525.116
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at F:\Programms\Android Studio 2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at F:\Programms\IntelliJ IDEA Ultimate
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 121.0.2277.106

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by moffatman** [comment]
Put expanded() around the listview

**Comment by moffatman** [comment]
You can get a good overview here 

https://youtu.be/jckqXR5CrPI?si=L1uBkLnNF7GDlsaj
