### ISSUE TITLE
SliverPadding.debugPaint assert with zero height (?) child

### ISSUE THREAD

**Issue by jouino16** [flutter/flutter#14318]
## Steps to Reproduce
Exception encountered when trying to work on [Flutter codelab](https://codelabs.developers.google.com/codelabs/flutter/).
After finishing step 6, I run the app on an emulator and I sent a couple  of messages (it's a chat app). Then when I tried to **Toggle Debug Paint** from **Flutter Inspector**, the app crashed with the below log message (does not always crash). And if I **Toggle Debug Paint** before sending messages, the sent messages are not rendered (added message widgets disappear as shown below). Same thing happens (added message widgets disappear), when trying to hot reload with the **Toggle Debug Paint** activated.

**Environment**: Windows 10, Android Studio 3.0.1, Flutter plugin 21.1.1

![white-space](https://user-images.githubusercontent.com/12447492/35486739-a72de274-0472-11e8-931b-1ad51caf01c3.png)

## Logs

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\app-debug.apk (23.3MB).
I/FlutterActivityDelegate(11396): onResume setting current activity to this
Syncing files to device Android SDK built for x86...
E/eglCodecCommon(11396): glUtilsParamSize: unknow param 0x00008824
D/        (11396): HostConnection::get() New Host Connection established 0xa56989c0, tid 11413
D/EGL_emulation(11396): eglMakeCurrent: 0x998c4860: ver 3 1 (tinfo 0x99a7f210)
D/EGL_emulation(11396): eglMakeCurrent: 0x9c2055a0: ver 3 1 (tinfo 0x9c203fe0)
I/zygote  (11396): Background concurrent copying GC freed 3192(1320KB) AllocSpace objects, 0(0B) LOS objects, 76% free, 480KB/2016KB, paused 10.610ms total 59.542ms
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
I/zygote  (11396): Do partial code cache collection, code=29KB, data=23KB
I/zygote  (11396): After code cache collection, code=29KB, data=23KB
I/zygote  (11396): Increasing code cache capacity to 128KB
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
I/zygote  (11396): Do partial code cache collection, code=60KB, data=41KB
I/zygote  (11396): After code cache collection, code=60KB, data=41KB
I/zygote  (11396): Increasing code cache capacity to 256KB
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(11396): getCursorCapsMode on inactive InputConnection
I/flutter (11396): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (11396): The following assertion was thrown during paint():
I/flutter (11396): 'package:flutter/src/rendering/sliver_padding.dart': Failed assertion: line 314: 'innerRect.bottom
I/flutter (11396): <= outerRect.bottom': is not true.
I/flutter (11396): 
I/flutter (11396): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11396): more information in this error message to help you determine and fix the underlying cause.
I/flutter (11396): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (11396):   https://github.com/flutter/flutter/issues/new
I/flutter (11396): 
I/flutter (11396): When the exception was thrown, this was the stack:
I/flutter (11396): #2      RenderSliverPadding.debugPaint.<anonymous closure> (package:flutter/src/rendering/sliver_padding.dart:314)
I/flutter (11396): #3      RenderSliverPadding.debugPaint (package:flutter/src/rendering/sliver_padding.dart:319)
I/flutter (11396): #4      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2006)
I/flutter (11396): #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2010)
I/flutter (11396): #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136)
I/flutter (11396): #7      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:341)
I/flutter (11396): #8      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:313)
I/flutter (11396): #9      PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:330)
I/flutter (11396): #10     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:332)
I/flutter (11396): #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1999)
I/flutter (11396): #12     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:116)
I/flutter (11396): #13     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:784)
I/flutter (11396): #14     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:267)
I/flutter (11396): #15     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:612)
I/flutter (11396): #16     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:203)
I/flutter (11396): #17     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:916)
I/flutter (11396): #18     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:856)
I/flutter (11396): #19     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:768)
I/flutter (11396): #20     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:113)
I/flutter (11396): #21     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:102)
I/flutter (11396): (elided 2 frames from class _AssertionError)
I/flutter (11396): 
I/flutter (11396): The following RenderObject was being processed when the exception was fired:
I/flutter (11396):   RenderViewport#7ef2b
I/flutter (11396):   creator: Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#a0db9] ← Listener ←
I/flutter (11396):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#aa24a] ←
I/flutter (11396):   RepaintBoundary ← CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification> ←
I/flutter (11396):   GlowingOverscrollIndicator ← Scrollable ← ⋯
I/flutter (11396):   parentData: <none> (can use size)
I/flutter (11396):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=272.1)
I/flutter (11396):   layer: OffsetLayer#c8e28
I/flutter (11396):   size: Size(411.4, 272.1)
I/flutter (11396):   axisDirection: up
I/flutter (11396):   crossAxisDirection: right
I/flutter (11396):   offset: ScrollPositionWithSingleContext#2c1a0(offset: 0.0, range: 0.0..463.9, viewport: 272.1,
I/flutter (11396):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#c043c,
I/flutter (11396):   ScrollDirection.idle)
I/flutter (11396):   anchor: 0.0
I/flutter (11396): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (11396):   RenderSliverPadding#46809 relayoutBoundary=up1
I/flutter (11396):     RenderSliverList#cc2d4 relayoutBoundary=up2
I/flutter (11396):       RenderRepaintBoundary#3271a relayoutBoundary=up3
I/flutter (11396):         RenderPadding#b0458 relayoutBoundary=up4
I/flutter (11396):           RenderFlex#fd9a6 relayoutBoundary=up5
I/flutter (11396):       RenderRepaintBoundary#7a5a7 relayoutBoundary=up3
I/flutter (11396):         RenderPadding#892ae relayoutBoundary=up4
I/flutter (11396):           RenderFlex#25469 relayoutBoundary=up5
I/flutter (11396):       RenderRepaintBoundary#7ec6c relayoutBoundary=up3
I/flutter (11396):         RenderPadding#40128 relayoutBoundary=up4
I/flutter (11396):           RenderFlex#24e7e relayoutBoundary=up5
I/flutter (11396):       RenderRepaintBoundary#40af1 relayoutBoundary=up3
I/flutter (11396):         RenderPadding#f0083 relayoutBoundary=up4
I/flutter (11396):           RenderFlex#7a7f2 relayoutBoundary=up5
I/flutter (11396):       RenderRepaintBoundary#06fb6 relayoutBoundary=up3
I/flutter (11396):         RenderPadding#3cff1 relayoutBoundary=up4
I/flutter (11396):           RenderFlex#01411 relayoutBoundary=up5
I/flutter (11396): ════════════════════════════════════════════════════════════════════════════════════════════════════
F/libc    (11396): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 11414 (ui_thread)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.0.0/OSR1.170901.056/4497355:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
pid: 11396, tid: 11414, name: ui_thread  >>> com.yourcompany.flutterapp.flutterapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc
Cause: null pointer dereference
    eax 88861850  ebx 8c5efaa0  ecx 8b45d4fe  edx 00000000
    esi 00000000  edi 8ac85cac
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
    eip 8b46a422  ebp 8ac85c78  esp 8ac85c50  flags 00210296
backtrace:
    #00 pc 00092422  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #01 pc 00093421  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #02 pc 00091e5c  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #03 pc 0068ce02  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #04 pc 0068cc63  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #05 pc 00000556  <anonymous:8a000000>
    #06 pc 00005815  <anonymous:81580000>
    #07 pc 0001fb50  <anonymous:83d40000>
    #08 pc 000223db  <anonymous:83d40000>
    #09 pc 000139d9  <anonymous:83d40000>
    #10 pc 00024cef  <anonymous:83d40000>
    #11 pc 00024c85  <anonymous:83d40000>
    #12 pc 00024c85  <anonymous:83d40000>
    #13 pc 000223bf  <anonymous:83d40000>
    #14 pc 00004381  <anonymous:81580000>
    #15 pc 00024cd9  <anonymous:83d40000>
    #16 pc 000223bf  <anonymous:83d40000>
    #17 pc 000031a4  <anonymous:81580000>
    #18 pc 0000262c  <anonymous:81580000>
    #19 pc 0002a779  <anonymous:83200000>
    #20 pc 00029f0c  <anonymous:83200000>
    #21 pc 00029b78  <anonymous:83200000>
    #22 pc 000299f9  <anonymous:83200000>
    #23 pc 0000b548  <anonymous:83d40000>
    #24 pc 0002959d  <anonymous:83200000>
    #25 pc 000288de  <anonymous:83200000>
    #26 pc 0001ae19  <anonymous:81580000>
    #27 pc 0001acf6  <anonymous:81580000>
    #28 pc 0003f325  <anonymous:87c80000>
    #29 pc 000054d5  <anonymous:88a00000>
    #30 pc 0001a9f3  <anonymous:81580000>
    #31 pc 00000723  <anonymous:8a000000>
    #32 pc 0063a523  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #33 pc 0063a0ce  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #34 pc 0097b81d  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #35 pc 0054d4d0  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #36 pc 000acb2f  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #37 pc 000b5526  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #38 pc 000b92e1  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #39 pc 000b6426  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #40 pc 000b7f16  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #41 pc 00082050  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #42 pc 0008ccff  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #43 pc 0008c8b2  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #44 pc 00091232  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #45 pc 00014a37  /system/lib/libutils.so (_ZN7android20SimpleLooperCallback11handleEventEiiPv+39)
    #46 pc 0001586c  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+988)
    #47 pc 00015406  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+118)
    #48 pc 00010e1e  /system/lib/libandroid.so (ALooper_pollOnce+94)
    #49 pc 0009116a  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #50 pc 0008cdc5  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #51 pc 0008c11e  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #52 pc 0008f063  /data/app/com.yourcompany.flutterapp.flutterapp-ikR_ogNzZI-Y0dKsAPVTLw==/lib/x86/libflutter.so
    #53 pc 000709b5  /system/lib/libc.so (_ZL15__pthread_startPv+53)
    #54 pc 0002050b  /system/lib/libc.so (__start_thread+75)
    #55 pc 0001eda6  /system/lib/libc.so (__bionic_clone+70)
Lost connection to device.

```

**Comment by Piinks** [comment]
This is a dup of https://github.com/flutter/flutter/issues/28406 which will be fixed once https://github.com/flutter/flutter/pull/37033 has landed.
If this is not the case and this bug persists on master after that PR lands, please feel free to re-open.
