### ISSUE TITLE
SurfaceTexturePlatformViewRenderTarget throws displayed below API level 23

### ISSUE THREAD

**Issue by centy** [flutter/flutter#143252]
### Steps to reproduce

We are experiencing a lot of this type of crashes on devices with api 22 and 21.
Callstack on Crashlitics looks like this:
```
PlatformDispatcher.onError: PlatformException(error, Platform views cannot be displayed below API level 23You can prevent this issue by setting `minSdkVersion: 23` in build.gradle., null, java.lang.UnsupportedOperationException: Platform views cannot be displayed below API level 23You can prevent this issue by setting `minSdkVersion: 23` in build.gradle.
      	at io.flutter.plugin.platform.SurfaceTexturePlatformViewRenderTarget.<init>(SurfaceTexturePlatformViewRenderTarget.java:106)
      	at io.flutter.plugin.platform.PlatformViewsController.makePlatformViewRenderTarget(PlatformViewsController.java:978)
      	at io.flutter.plugin.platform.PlatformViewsController.configureForVirtualDisplay(PlatformViewsController.java:554)
      	at io.flutter.plugin.platform.PlatformViewsController.access$800(PlatformViewsController.java:49)
      	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:221)
      	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
      	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
      	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
      	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
      	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
      	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
      	at android.os.Handler.handleCallback(Handler.java:739)
      	at android.os.Handler.dispatchMessage(Handler.java:95)
      	at android.os.Looper.loop(Looper.java:135)
      	at android.app.ActivityThread.main(ActivityThread.java:5254)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at java.lang.reflect.Method.invoke(Method.java:372)
      	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
      )
```

### Expected results

We assume that dart/flutter supports devices from API 21, we expecting that this should not happen

### Actual results

App does not crashes, crashlitics is reporting this execption

### Code sample

We are unable to find which element is causing that crash in our app

### Screenshots or Video

No screenshots

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.3930], locale pl-PL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[√] Android Studio (version 2023.1)
[√] IntelliJ IDEA Community Edition (version 2023.3)
[√] VS Code (version 1.86.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

</details>

**Comment by darshankawar** [comment]
@centy 
Can you check if you are using AndroidView which requires api 23 per https://api.flutter.dev/flutter/widgets/AndroidView-class.html

**Comment by darshankawar** [comment]
> Is there any way to overcome this problem?

You may need to reach out to the third party package owner to upgrade their build.gradle to support api 23.
