### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by UddhavHivare** [flutter/flutter#143215]
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#8      CreateBase._computeTemplateManifest (package:flutter_tools/src/commands/create_base.dart:669:37)
#9      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart:656:43)
#10     CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart)
#11     CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:481:25)
#12     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:506:29)
#13     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:361:37)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22000.2416], locale en-US)
    • Flutter version 3.16.9 on channel stable at D:\flutter_windows_3.16.9-stable\flutter
    ! The flutter binary is not on your path. Consider adding D:\flutter_windows_3.16.9-stable\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding D:\flutter_windows_3.16.9-stable\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (2 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • Java binary at: D:\android\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
    • Visual Studio at D:\VS Code
    • Visual Studio Community 2022 version 17.8.34525.116
    ✗ The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[✓] Android Studio (version 2023.1)
    • Android Studio at D:\android
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2416]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.161
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by dam-ease** [comment]
Thanks for filing this @UddhavHivare.
Kindly check out the suggested solutions at https://github.com/flutter/flutter/issues/106953 to see if they help.
