### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by Aditya-1708** [flutter/flutter#143429]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:414:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      _writeFlutterPluginsListLegacy (package:flutter_tools/src/flutter_plugins.dart:257:36)
#7      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1097:30)
<asynchronous suspension>
#8      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:359:5)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1665:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.9, on Arch Linux 6.7.4-arch1-1, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.16.9 on channel stable at /home/aditya/.flutter/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    [32m•[39m Engine revision f40e976bed
    [32m•[39m Dart version 3.2.6
    [32m•[39m DevTools version 2.28.5

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /home/aditya/Android/Sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /opt/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 16.0.6
    [32m•[39m cmake version 3.28.3
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 2.1.0

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /opt/android-studio
    [32m•[39m Flutter plugin version 77.2.1
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m Connected device (3 available)
    [32m•[39m SM S911B (mobile) • RZCW82DMYYA • android-arm64  • Android 14 (API 34)
    [32m•[39m Linux (desktop)   • linux       • linux-x64      • Arch Linux 6.7.4-arch1-1
    [32m•[39m Chrome (web)      • chrome      • web-javascript • Google Chrome 121.0.6167.160

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 67457e669f79e9f8d13d7a68fe09775fefbb79f4
### Plugins
cloud_firestore-4.15.4
cloud_firestore_web-3.10.4
firebase_analytics-10.8.5
firebase_analytics_web-0.5.5+17
firebase_auth-4.17.4
firebase_auth_web-5.9.4
firebase_core-2.25.4
firebase_core_web-2.11.4
firebase_messaging-14.7.15
firebase_messaging_web-3.6.4
flutter_local_notifications-16.3.2
flutter_native_splash-2.3.10
flutter_plugin_android_lifecycle-2.0.17
geocoding-2.1.1
geocoding_android-2.1.2
geocoding_ios-2.1.1
google_maps_flutter-2.5.3
google_maps_flutter_android-2.6.2
google_maps_flutter_ios-2.4.1
google_maps_flutter_web-0.5.4+3
location-5.0.3
location_web-4.2.0

**Comment by Aditya-1708** [comment]
got it just had to give read and write permissions to the USER for this particular folder

"chmod -R +rw directory"
