### ISSUE TITLE
App Crashes from Video Player in PageView

### ISSUE THREAD

**Issue by ChristineWasike** [flutter/flutter#143441]
### Steps to reproduce

1. Install the latest version of the [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager/install) package
2. Install the latest version of the [video_player](https://pub.dev/packages/video_player/install) package
3. Run the app
4. Swipe horizontally through the videos

You notice that the videos continue to play in the background from the sound. Meaning that there is something wrong with disposing the controllers some how.

I'd really appreciate your help, thank you!

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Video Player with PageView Demo",
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: const SamplePageView(),
    );
  }
}

class SamplePageView extends StatefulWidget {
  const SamplePageView({super.key});

  @override
  State<SamplePageView> createState() => _SamplePageViewState();
}

class _SamplePageViewState extends State<SamplePageView> {
  List<String> videos = [];
  List<String> videoThumbnails = [];

  @override
  void initState() {
    super.initState();

    /// generate a list of 100 random videos
    setState(() {
      for (var i = 0; i < 100; i++) {
        switch (i % 3) {
          case 0:
            videos.add(
                "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4");
            break;
          case 1:
            videos.add(
                "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4");
            break;
          case 2:
            videos.add(
                "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4");
            break;
        }
      }
    });

    /// generate a list of 100 random video thumbnails
    setState(() {
      for (var i = 0; i < 100; i++) {
        switch (i % 3) {
          case 0:
            videoThumbnails.add(
                "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg");
            break;
          case 1:
            videoThumbnails.add(
                "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg");
            break;
          case 2:
            videoThumbnails.add(
                "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg");
            break;
        }
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView.builder(
        itemCount: 100,
        itemBuilder: (context, index) {
          return CentralVideoPlayer(
            videoUrl: videos[index],
            videoThumbnail: videoThumbnails[index],
            isMuted: false,
          );
        },
      ),
    );
  }
}

class CentralVideoPlayer extends StatefulWidget {
  const CentralVideoPlayer(
      {required this.videoUrl,
      required this.videoThumbnail,
      this.videoFile,
      this.isDiscover = false,
      this.isMuted = false,
      super.key});

  final String videoUrl;
  final String videoThumbnail;
  final File? videoFile;
  final bool isDiscover;
  final bool isMuted;

  @override
  State<CentralVideoPlayer> createState() => _CentralVideoPlayerState();
}

class _CentralVideoPlayerState extends State<CentralVideoPlayer> {
  VideoPlayerController? videoController;
  bool isVideoInitialized = false;

  initializeVideo() async {
    if (widget.isMuted) {
      /// video not in view direct view so:

      /// cache video as a file with the DefaultCacheManager for later consumption
      /// video is only cached once then file is used for all future plays
      var file = await DefaultCacheManager().getSingleFile(widget.videoUrl);

      /// ... play cached video
      videoController = VideoPlayerController.file(
        file,
        videoPlayerOptions: VideoPlayerOptions(
          mixWithOthers: true,
        ),
      )
        ..setLooping(true)
        ..initialize().then((_) {
          if (mounted) {
            setState(() {});
          }

          videoController!.setVolume(0);

          videoController!.play();
        });
    } else {
      /// ... do something with volume

      /// cache video as a file with the DefaultCacheManager for later consumption
      /// video is only cached once then file is used for all future plays
      var file = await DefaultCacheManager().getSingleFile(widget.videoUrl);

      /// ... play cached video
      videoController = VideoPlayerController.file(
        file,
        videoPlayerOptions: VideoPlayerOptions(
          mixWithOthers: true,
        ),
      )
        ..setLooping(true)
        ..initialize().then((_) {
          if (mounted) {
            setState(() {});
          }
          if (mounted) {
            /// ... do something with volume
          }
          if (widget.isMuted) {
            videoController!.setVolume(0);
          } else {
            /// ... do something with volume
          }

          /// ... do something with volume
          videoController!.play();
        });
    }
  }

  @override
  void initState() {
    super.initState();

    initializeVideo();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          if (widget.videoThumbnail.isNotEmpty)
            Positioned.fill(
              child: Image.network(
                widget.videoThumbnail,
                fit: BoxFit.cover,
              ),
            ),
          SizedBox.expand(
            child: FittedBox(
              fit: BoxFit.cover,
              child: videoController != null
                  ? SizedBox(
                      width: videoController!.value.size.width,
                      height: videoController!.value.size.height,
                      child: VideoPlayer(videoController!),
                    )
                  : widget.videoThumbnail.isNotEmpty
                      ? Image.network(
                          widget.videoThumbnail,
                          fit: BoxFit.cover,
                        )
                      : Container(),
            ),
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    videoController?.dispose();
    super.dispose();
  }
}
```

</details>

### What target platforms are you seeing this bug on?

Android, iOS

### OS/Browser name and version | Device information

iOS Minimum - 13.0
Android API Level - 24

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Logs

<details open><summary>Logs</summary>

```console
// Crash log errors
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 115(3560B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 156us total 69.065ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 69.084ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Alloc young concurrent copying GC freed 93(4960B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 142us total 16.089ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 16.098ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 324(16KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 129us total 67.256ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 67.159ms
I/ocialai.limite(23624): Forcing collection of SoftReferences for 64KB allocation
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 145(8728B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 137us total 64.760ms
E/ocialai.limite(23624): [MemLeak.JavaTrack]: failed to write oom info: Operation not permitted
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 64.923ms
W/ocialai.limite(23624): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 39432 free bytes and 38KB until OOM, target footprint 402653184, growth limit 402653184" (VmSize 17180928 kB)
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 43.791ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 269(11KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 169us total 74.148ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 74.160ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Alloc young concurrent copying GC freed 54(1848B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 151us total 17.410ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 17.332ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 267(11KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 140us total 70.447ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 69.379ms
I/ocialai.limite(23624): Forcing collection of SoftReferences for 64KB allocation
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 667(30KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 155us total 75.677ms
E/ocialai.limite(23624): [MemLeak.JavaTrack]: failed to write oom info: Operation not permitted
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 75.475ms
W/ocialai.limite(23624): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 41224 free bytes and 40KB until OOM, target footprint 402653184, growth limit 402653184" (VmSize 17183996 kB)
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Alloc young concurrent copying GC freed 248(34KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 149us total 13.762ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 13.387ms
E/LoadTask(23624): OutOfMemory error loading stream
E/LoadTask(23624):   java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 41224 free bytes and 40KB until OOM, target footprint 402653184, growth limit 402653184
E/LoadTask(23624):       at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
E/LoadTask(23624):       at com.google.android.exoplayer2.source.SampleDataQueue.preAppend(SampleDataQueue.java:233)
E/LoadTask(23624):       at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:176)
E/LoadTask(23624):       at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:590)
E/LoadTask(23624):       at com.google.android.exoplayer2.extractor.TrackOutput.sampleData(TrackOutput.java:157)
E/LoadTask(23624):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:652)
E/LoadTask(23624):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:259)
E/LoadTask(23624):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
E/LoadTask(23624):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
E/LoadTask(23624):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/LoadTask(23624):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/LoadTask(23624):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/LoadTask(23624):       at java.lang.Thread.run(Thread.java:929)
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Background concurrent copying GC freed 435(39KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 186us total 138.010ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 82.172ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 81.877ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 76.340ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 72.261ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 58.909ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 86.950ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Background young concurrent copying GC freed 248(11KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 5.398ms total 36.192ms
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Background concurrent copying GC freed 409(17KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 172us total 119.201ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 67.791ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Alloc young concurrent copying GC freed 103(3264B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 250us total 33.507ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 33.177ms
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 88.453ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 178(7656B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 385us total 87.308ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 86.266ms
I/ocialai.limite(23624): Forcing collection of SoftReferences for 64KB allocation
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 185(11KB) AllocSpace objects, 1(68KB) LOS objects, 0% free, 383MB/384MB, paused 394us total 83.389ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 82.479ms
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 28.507ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 197(12KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 276us total 116.694ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 110.809ms
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 49.506ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Alloc young concurrent copying GC freed 12(456B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 196us total 16.589ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 415(44KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 142us total 74.508ms
I/ocialai.limite(23624): WaitForGcToComplete blocked HeapTrim on HeapTrim for 91.024ms
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Forcing collection of SoftReferences for 64KB allocation
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 59.066ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
E/ExoPlayerImplInternal(23624): Playback error
E/ExoPlayerImplInternal(23624):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:620)
E/ExoPlayerImplInternal(23624):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(23624):       at android.os.Looper.loop(Looper.java:213)
E/ExoPlayerImplInternal(23624):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(23624):   Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65552 byte allocation with 48328 free bytes and 47KB until OOM, target footprint 402653184, growth limit 402653184
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:441)
E/ExoPlayerImplInternal(23624):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(23624):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(23624):       at java.lang.Thread.run(Thread.java:929)
E/ExoPlayerImplInternal(23624):   Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 48328 free bytes and 47KB until OOM, target footprint 402653184, growth limit 402653184
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.source.SampleDataQueue.preAppend(SampleDataQueue.java:233)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:176)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:590)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.extractor.TrackOutput.sampleData(TrackOutput.java:157)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:652)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:259)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
E/ExoPlayerImplInternal(23624):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(23624):       ... 3 more
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 244(85KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 182us total 75.210ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 74.647ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 71.279ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 69.113ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 60.146ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Alloc young concurrent copying GC freed 16(560B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 147us total 16.864ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 16.939ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 88.659ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
W/ACodec  (23624): forcing OMX state to Idle when received shutdown in ExecutingState
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
D/SurfaceUtils(23624): disconnecting from surface 0x72ae7e0010, reason disconnectFromSurface
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 354(15KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 147us total 79.655ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 79.363ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 33.043ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 31.619ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Forcing collection of SoftReferences for 64KB allocation
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 404MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 235(11KB) AllocSpace objects, 54(3672KB) LOS objects, 0% free, 380MB/384MB, paused 1.885ms total 72.651ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 119.679ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 72.998ms
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 111.526ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
D/CCodecBuffers(23624): [c2.android.aac.decoder#625:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): WaitForGcToComplete blocked Alloc on HeapTrim for 83.390ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 99(3504B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 193us total 153.299ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Alloc young concurrent copying GC freed 5(200B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 171us total 17.914ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 171.814ms
I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Clamp target GC heap from 407MB to 384MB
I/ocialai.limite(23624): Alloc concurrent copying GC freed 64(2272B) AllocSpace objects, 0(0B) LOS objects, 0% free, 383MB/384MB, paused 143us total 87.309ms
I/ocialai.limite(23624): WaitForGcToComplete blocked Background on HeapTrim for 85.832ms
I/ocialai.limite(23624): Forcing collection of SoftReferences for 64KB allocation
I/ocialai.limite(23624): Starting a blocking GC Alloc

...

I/ocialai.limite(23624): Starting a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
I/ocialai.limite(23624): Waiting for a blocking GC Alloc
F/libc    (23624): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 23897 (1.ui), pid 23624 (ocialai.limited)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/STK-L21MDV/HWSTK-HF:10/HUAWEISTK-L21/10.0.0.274C185:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-02-14 12:22:19+0300
pid: 23624, tid: 23897, name: 1.ui  >>> com.socialai.limited <<<
uid: 10335
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1306)] Check failed: fml::jni::CheckException(env). 
'
    x0  0000000000000000  x1  0000000000005d59  x2  0000000000000006  x3  000000741f9fa600
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  5ed79cdcdd41bb4c  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 0000000000000003  x14 0000000000000001  x15 ffffffffffffffff
    x16 000000752366f908  x17 000000752364f700  x18 000000741ba96000  x19 0000000000005c48
    x20 0000000000005d59  x21 00000000ffffffff  x22 00000074926d6450  x23 0000000000000011
    x24 0000000000000021  x25 000000741f922000  x26 000000743264a200  x27 00000073097cb940
    x28 0000000800000073  x29 000000741f9fa6a0
    sp  000000741f9fa5e0  lr  0000007523604580  pc  00000075236045ac
backtrace:
      #00 pc 00000000000705ac  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 8ee0932e058bcf6b353f0a24aaef0e4e)
      #01 pc 0000000000000f50  /data/app/com.socialai.limited-1fKVwWoF_oq_zX6osRMTxQ==/base.apk
```

</details>

[Paste bin](https://pastebin.com/gZ2yd0hh)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-KE)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.86.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @ChristineWasike 
I checked this on `Realme 6, Android 11, 4GB RAM`, swiped through more than 10 videos but didn't see the crash.

>E/LoadTask(23624):   java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 41224 free bytes and 40KB until OOM, target footprint 402653184, growth limit 402653184

>E/ExoPlayerImplInternal(23624):   Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 48328 free bytes and 47KB until OOM, target footprint 402653184, growth limit 402653184


These logs came from ExoPlayer underlying and they indicate issues buffering media with ExoPlayer rather than a `video_player` Flutter plugin issue. Please check some known issues: https://github.com/google/ExoPlayer/issues/4221, https://github.com/google/ExoPlayer/issues/7354. 

So I would recommend you open issue at ExoPlayer's repository for better support there. Closing this as it doesn't seem a `video_player` Flutter plugin issue.
