### ISSUE TITLE
Flutter StackOverflow 

### ISSUE THREAD

**Issue by qu-ngx** [flutter/flutter#143668]
### Steps to reproduce

- Created a new dart file as a new page for the application. 
- Called the object of the created file in nav_pages.dart as a new body / new pag
- fn + F5 to run the app in debug mode
- App gives a log full of stackoverflow

### Expected results

The screen will load a new page.

### Actual results

The app crashes and gives a log full of StackOverflow

### Code sample

```
import 'package:nufit/pages/dictionary/dictionary_page.dart';
import 'package:nufit/pages/food_detection/fd_front.dart';
import 'package:nufit/pages/meal_planner/meal_planner_page.dart';
import 'package:nufit/pages/quizz/quizz_page.dart';
import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  //// Second Nav Bar
  // int _page = 0;
  // final GlobalKey<CurvedNavigationBarState> _bottomNavigationKey = GlobalKey();

  PageController selectedPage = PageController(initialPage: 0);

  final Color _iconColor = Colors.white;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      backgroundColor: Colors.white,
      floatingActionButton: SizedBox(
        height: 70,
        width: 70,
        child: FloatingActionButton(
            tooltip: "AI Camera",
            shape: const CircleBorder(),
            onPressed: () {
              selectedPage.jumpToPage(2);
            },
            elevation: 1,
            backgroundColor: Colors.orange.shade200,
            child: const Icon(
              Icons.camera_alt_outlined,
              size: 40,
              color: Colors.white,
            )),
      ),

      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,

      bottomNavigationBar: Theme(
        data: Theme.of(context).copyWith(),
        child: BottomAppBar(
          color: Colors.orange,
          shape: const CircularNotchedRectangle(),
          notchMargin: 6,
          surfaceTintColor: Colors.transparent,
          elevation: 5.0,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              IconButton(
                iconSize: 30,
                selectedIcon: Image.asset(
                  'assets/icons/homepage.png',
                  color: _iconColor,
                  height: 200,
                ),
                onPressed: () {
                  selectedPage.jumpToPage(0);
                },
                icon: Image.asset(
                  'assets/icons/homepage.png',
                  color: _iconColor,
                  height: 200,
                ),
              ),
              IconButton(
                iconSize: 80,
                selectedIcon: Image.asset(
                  'assets/icons/s_meals.png',
                  color: _iconColor,
                  height: 200,
                ),
                onPressed: () {
                  selectedPage.jumpToPage(1);
                },
                icon: Image.asset(
                  'assets/icons/meals.png',
                  color: _iconColor,
                  height: 200,
                ),
              ),
              IconButton(
                iconSize: 15,
                onPressed: () {
                  selectedPage.jumpToPage(3);
                },
                icon: Image.asset(
                  'assets/icons/book.png',
                  color: _iconColor,
                  height: 34,
                ),
              ),
              IconButton(
                iconSize: 33,
                onPressed: () {
                  selectedPage.jumpToPage(4);
                },
                icon: Icon(
                  Icons.quiz_outlined,
                  size: 36,
                  color: _iconColor,
                ),
              ),
            ],
          ),
        ),
      ),

      body: PageView(
        controller: selectedPage,
        children: const <Widget>[
          Center(
            child: HomePage(),
          ),
          Center(
            child: MealPlannerPage(),
          ),
          Center(
            child: FoodML(),
          ),
          Center(
            child: DictPage(),
          ),
          Center(
            child: QuizzPage(),
          )
        ],
      ),
      
      // key: _bottomNavigationKey,
      // body: const [
      //   MealPlannerPage(),
      //   FoodML(),
      //   DictPage(),
      //   QuizzPage(),
      //   ProfilePage(),
      // ][_page],
      // backgroundColor: Colors.transparent,
      // bottomNavigationBar: CurvedNavigationBar(
      //     backgroundColor: Colors.transparent,
      //     color: Colors.orange,
      //     animationDuration: const Duration(milliseconds: 300),
      //     buttonBackgroundColor: Colors.orange.shade100,
      //     onTap: (index) {
      //       setState(() {
      //         _page = index;
      //       });
      //     },
      //     items: [
      //       Icon(
      //         Icons.dinner_dining_sharp,
      //         size: 30,
      //         color: Colors.grey.shade600,
      //       ),
      //       Image.asset(
      //         'assets/icons/home_camera.png',
      //         width: 30,
      //         height: 30,
      //         color: Colors.grey.shade600,
      //       ),
      //        Image.asset(
      //         'assets/icons/dictionary.png',
      //         width: 33,
      //         height: 33,
      //         color: Colors.grey.shade600,
      //       ),
      //       Icon(
      //         Icons.quiz_outlined,
      //         size: 30,
      //         color: Colors.grey.shade600,
      //       ),
      //       Icon(
      //         Icons.person,
      //         size: 30,
      //         color: Colors.grey.shade600,
      //       ),
      //     ]),

      //// First Nav Bar
      // body: const [
      //   MealPlannerPage(),
      //   FoodML(),
      //   DictPage(),
      //   ProfilePage()
      // ][selectedPageIndex],
      // bottomNavigationBar: NavigationBar(
      //   selectedIndex: selectedPageIndex,
      //   onDestinationSelected: (int index) {
      //     setState(() {
      //       selectedPageIndex = index;
      //     });
      //   },
      //   elevation: 0.0,
      //   destinations: <NavigationDestination>[
      //     NavigationDestination(
      //       icon: Icon(
      //         Icons.dinner_dining_sharp,
      //         size: 34,
      //       ),
      //       label: "Meals",
      //     ),
      //     NavigationDestination(
      //       icon: Image.asset('assets/icons/home_camera.png',
      //           width: 30, height: 30),
      //       label: 'Camera',
      //     ),
      //     NavigationDestination(
      //       icon: Image.asset('assets/icons/dictionary.png',
      //           width: 30, height: 30),
      //       label: 'Dictionary',
      //     ),
      //     const NavigationDestination(
      //         icon: Icon(Icons.person), label: 'Profile')
      //   ],
      // ),
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
D/EGL_emulation(17333): app_time_stats: avg=1689.58ms min=13.78ms max=19726.82ms count=12

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building InkWell:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    IconButton IconButton:file:///Users/quangnguyen/Documents/nufit/lib/pages/nav_pages.dart:59:15

When the exception was thrown, this was the stack:
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:5191:16)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:5194:8)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625:11)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
...     Normal element mounting (89 frames)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#96     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#97     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (130 frames)
#227    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#228    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#229    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (156 frames)
#385    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#386    Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#387    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:858:37)
#388    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:843:20)
#389    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835:19)
#390    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:835:12)
#391    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#392    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657:59)
#393    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071:15)
#394    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657:14)
#395    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#396    RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:424:5)
#397    RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:274:12)
#398    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#399    RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139:12)
#400    _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:160:11)
#401    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#402    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601:13)
#403    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1554:12)
#404    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1463:20)
#405    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#406    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#407    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#408    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#409    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#410    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#411    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#412    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#413    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#414    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#415    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#416    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#417    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#418    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#419    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#420    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#421    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#422    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#423    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#424    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#425    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#426    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#427    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#428    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#429    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
#430    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#431    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#432    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:310:14)
#433    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#434    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#435    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#436    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
#437    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#438    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#439    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#440    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#441    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#442    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#443    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#444    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#445    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
#446    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#447    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#448    RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:434:14)
#449    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#450    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#451    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5191 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2838 pos 20: '_debugCurrentBuildTarget == context': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════
Restarted application in 9,937ms.
W/WindowOnBackDispatcher(17333): sendCancelIfRunning: isInProgress=falsecallback=io.flutter.embedding.android.FlutterActivity$1@373431
D/EGL_emulation(17333): app_time_stats: avg=6149.30ms min=6149.30ms max=6149.30ms count=1
Reloaded 1 of 2231 libraries in 1,144ms (compile: 59 ms, reload: 525 ms, reassemble: 457 ms).
D/EGL_emulation(17333): app_time_stats: avg=484085.38ms min=484085.38ms max=484085.38ms count=1



```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 13.4.1 22F770820d darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.0)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by qu-ngx** [comment]
I found out the way to solve this bug for anyone who does not know why:
- I created another file with the same class called HomePage and I called it in my new class in another file also named HomePage, which creates recursion and this is how I got StackOverflow
-> Just mind the name of your class. Even if you call another object from a class with the same name in your class, you will still cause a recursion.
